clang: lib/StaticAnalyzer/Checkers/ArrayBoundCheckerV2.cpp File Reference
ArrayBoundCheckerV2.cpp File Reference
#include "clang/AST/CharUnits.h"
#include "clang/StaticAnalyzer/Checkers/BuiltinCheckerRegistration.h"
#include "clang/StaticAnalyzer/Checkers/Taint.h"
#include "clang/StaticAnalyzer/Core/BugReporter/BugType.h"
#include "clang/StaticAnalyzer/Core/Checker.h"
#include "clang/StaticAnalyzer/Core/CheckerManager.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/APSIntType.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/CheckerContext.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/DynamicExtent.h"
#include "clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
Functions
static SVal computeExtentBegin (SValBuilder &svalBuilder, const MemRegion *region)
static std::pair< NonLoc, nonloc::ConcreteInt > getSimplifiedOffsets (NonLoc offset, nonloc::ConcreteInt extent, SValBuilder &svalBuilder)
static SVal getValue (SVal val, SValBuilder &svalBuilder)
static SVal scaleValue (ProgramStateRef state, NonLoc baseVal, CharUnits scaling, SValBuilder &sb)
static SVal addValue (ProgramStateRef state, SVal x, SVal y, SValBuilder &svalBuilder)
Function Documentation
addValue()
static SVal addValue (ProgramStateRef state, SVal x, SVal y, SValBuilder & svalBuilder) static
Definition at line 293 of file ArrayBoundCheckerV2.cpp.
References state, and x.
computeExtentBegin()
static SVal computeExtentBegin (SValBuilder & svalBuilder, const MemRegion * region) static
Definition at line 72 of file ArrayBoundCheckerV2.cpp.
getSimplifiedOffsets()
static std::pair<NonLoc, nonloc::ConcreteInt> getSimplifiedOffsets (NonLoc offset, nonloc::ConcreteInt extent, SValBuilder & svalBuilder) static
Definition at line 86 of file ArrayBoundCheckerV2.cpp.
getValue()
static SVal getValue (SVal val, SValBuilder & svalBuilder) inline static
Definition at line 277 of file ArrayBoundCheckerV2.cpp.
Referenced by clang::ento::SimpleConstraintManager::assumeInclusiveRangeInternal(), clang::ento::nonloc::CompoundVal::begin(), clang::ento::nonloc::CompoundVal::end(), clang::tooling::OptionRequirement< OptionType >::evaluate(), clang::ento::StoreManager::getLValueElement(), clang::threadSafety::getSourceLiteralString(), nodeToCommandLine(), clang::APValue::Profile(), and clang::ento::ExprEngine::VisitLogicalExpr().
scaleValue()
static SVal scaleValue (ProgramStateRef state, NonLoc baseVal, CharUnits scaling, SValBuilder & sb) inline static
Definition at line 283 of file ArrayBoundCheckerV2.cpp.
References clang::CharUnits::getQuantity(), and state.