clang: lib/AST/ASTStructuralEquivalence.cpp File Reference
ASTStructuralEquivalence.cpp File Reference
#include "clang/AST/ASTStructuralEquivalence.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTDiagnostic.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclFriend.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclOpenMP.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/ExprConcepts.h"
#include "clang/AST/ExprObjC.h"
#include "clang/AST/ExprOpenMP.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/StmtObjC.h"
#include "clang/AST/StmtOpenMP.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/Type.h"
#include "clang/Basic/ExceptionSpecificationType.h"
#include "clang/Basic/IdentifierTable.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/SourceLocation.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include <cassert>
#include <optional>
#include <utility>
#include "clang/AST/StmtNodes.inc"
#include "clang/AST/DeclNodes.inc"
Macros
#define STMT(CLASS, PARENT)
#define STMT(CLASS, PARENT)
#define ABSTRACT_STMT(S)
#define ABSTRACT_DECL(DECL)
#define DECL(DERIVED, BASE)
Functions
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, QualType T1, QualType T2)
Determine structural equivalence of two types.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, Decl *D1, Decl *D2)
Determine structural equivalence of two declarations.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, const TemplateArgument &Arg1, const TemplateArgument &Arg2)
Determine whether two template arguments are equivalent.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, const TemplateArgumentLoc &Arg1, const TemplateArgumentLoc &Arg2)
Determine whether two template argument locations are equivalent.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, NestedNameSpecifier *NNS1, NestedNameSpecifier *NNS2)
Determine whether two nested-name-specifiers are equivalent.
static bool IsStructurallyEquivalent (const IdentifierInfo *Name1, const IdentifierInfo *Name2)
Determine whether two identifiers are equivalent.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, const DeclarationName Name1, const DeclarationName Name2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, const Stmt *S1, const Stmt *S2)
Determine structural equivalence of two statements.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, const TemplateName &N1, const TemplateName &N2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, ArrayRef< TemplateArgument > Args1, ArrayRef< TemplateArgument > Args2)
Determine structural equivalence of two template argument lists.
static bool IsArrayStructurallyEquivalent (StructuralEquivalenceContext &Context, const ArrayType *Array1, const ArrayType *Array2)
Determine structural equivalence for the common part of array types.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FunctionType::ExtInfo EI1, FunctionType::ExtInfo EI2)
Determine structural equivalence based on the ExtInfo of functions.
static bool IsEquivalentExceptionSpec (StructuralEquivalenceContext &Context, const FunctionProtoType *Proto1, const FunctionProtoType *Proto2)
Check the equivalence of exception specifications.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FieldDecl *Field1, FieldDecl *Field2, QualType Owner2Type)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FieldDecl *Field1, FieldDecl *Field2)
Determine structural equivalence of two fields.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, CXXMethodDecl *Method1, CXXMethodDecl *Method2)
Determine structural equivalence of two methods.
static bool IsStructurallyEquivalentLambdas (StructuralEquivalenceContext &Context, CXXRecordDecl *D1, CXXRecordDecl *D2)
Determine structural equivalence of two lambda classes.
static bool IsRecordContextStructurallyEquivalent (RecordDecl *D1, RecordDecl *D2)
Determine if context of a class is equivalent.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, RecordDecl *D1, RecordDecl *D2)
Determine structural equivalence of two records.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, EnumConstantDecl *D1, EnumConstantDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, EnumDecl *D1, EnumDecl *D2)
Determine structural equivalence of two enums.
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, TemplateParameterList *Params1, TemplateParameterList *Params2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, TemplateTypeParmDecl *D1, TemplateTypeParmDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, NonTypeTemplateParmDecl *D1, NonTypeTemplateParmDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, TemplateTemplateParmDecl *D1, TemplateTemplateParmDecl *D2)
static bool IsTemplateDeclCommonStructurallyEquivalent (StructuralEquivalenceContext &Ctx, TemplateDecl *D1, TemplateDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, ClassTemplateDecl *D1, ClassTemplateDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FunctionTemplateDecl *D1, FunctionTemplateDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, ConceptDecl *D1, ConceptDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FriendDecl *D1, FriendDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, TypedefNameDecl *D1, TypedefNameDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, FunctionDecl *D1, FunctionDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, ObjCIvarDecl *D1, ObjCIvarDecl *D2, QualType Owner2Type)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, ObjCIvarDecl *D1, ObjCIvarDecl *D2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, ObjCMethodDecl *Method1, ObjCMethodDecl *Method2)
static bool IsStructurallyEquivalent (StructuralEquivalenceContext &Context, ObjCCategoryDecl *D1, ObjCCategoryDecl *D2)
Macro Definition Documentation
ABSTRACT_DECL
#define ABSTRACT_DECL (DECL)
ABSTRACT_STMT
#define ABSTRACT_STMT (S)
DECL
#define DECL (DERIVED, BASE)
Value:
  case Decl::Kind::DERIVED:                                                    \
    return ::IsStructurallyEquivalent(*this, static_cast<DERIVED##Decl *>(D1), \
                                      static_cast<DERIVED##Decl *>(D2));
STMT [1/2]
#define STMT (CLASS, PARENT)
Value:
  bool TraverseStmt(const CLASS *S1, const CLASS *S2) {                        \
    if (!TraverseStmt(static_cast<const PARENT *>(S1),                         \
                      static_cast<const PARENT *>(S2)))                        \
      return false;                                                            \
    return IsStmtEquivalent(S1, S2);                                           \
  }
Definition at line 377 of file ASTStructuralEquivalence.cpp.
STMT [2/2]
#define STMT (CLASS, PARENT)
Value:
  case Stmt::StmtClass::CLASS##Class:                                          \
    return TraverseStmt(static_cast<const CLASS *>(S1),                        \
                        static_cast<const CLASS *>(S2));
Definition at line 377 of file ASTStructuralEquivalence.cpp.
Function Documentation
IsArrayStructurallyEquivalent()
static bool IsArrayStructurallyEquivalent (StructuralEquivalenceContext & Context, const ArrayType * Array1, const ArrayType * Array2) static
Determine structural equivalence for the common part of array types.
Definition at line 638 of file ASTStructuralEquivalence.cpp.
References clang::ArrayType::getElementType(), clang::ArrayType::getIndexTypeQualifiers(), clang::ArrayType::getSizeModifier(), and IsStructurallyEquivalent().
Referenced by IsStructurallyEquivalent().
IsEquivalentExceptionSpec()
static bool IsEquivalentExceptionSpec (StructuralEquivalenceContext & Context, const FunctionProtoType * Proto1, const FunctionProtoType * Proto2) static
Check the equivalence of exception specifications.
Definition at line 679 of file ASTStructuralEquivalence.cpp.
References clang::EST_Dynamic, clang::FunctionProtoType::getExceptionSpecType(), clang::FunctionProtoType::getExceptionType(), clang::FunctionProtoType::getNoexceptExpr(), clang::FunctionProtoType::getNumExceptions(), clang::isComputedNoexcept(), IsStructurallyEquivalent(), and clang::isUnresolvedExceptionSpec().
Referenced by IsStructurallyEquivalent().
IsRecordContextStructurallyEquivalent()
static bool IsRecordContextStructurallyEquivalent (RecordDecl * D1, RecordDecl * D2) static
Determine if context of a class is equivalent.
Definition at line 1421 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getDeclContext(), clang::DeclContext::getDeclKind(), clang::DeclContext::getNonTransparentContext(), clang::DeclContext::getParent(), clang::DeclContext::isFunctionOrMethod(), clang::DeclContext::isInlineNamespace(), IsStructurallyEquivalent(), and clang::DeclContext::isTranslationUnit().
Referenced by IsStructurallyEquivalent().
IsStructurallyEquivalent() [1/31]
static bool IsStructurallyEquivalent (const IdentifierInfo * Name1, const IdentifierInfo * Name2) static
Determine whether two identifiers are equivalent.
Definition at line 442 of file ASTStructuralEquivalence.cpp.
References clang::IdentifierInfo::getName().
IsStructurallyEquivalent() [2/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, ArrayRef< TemplateArgument > Args1, ArrayRef< TemplateArgument > Args2) static
Determine structural equivalence of two template argument lists.
Definition at line 616 of file ASTStructuralEquivalence.cpp.
References IsStructurallyEquivalent().
IsStructurallyEquivalent() [3/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, ClassTemplateDecl * D1, ClassTemplateDecl * D2) static
Definition at line 1914 of file ASTStructuralEquivalence.cpp.
References clang::ClassTemplateDecl::getTemplatedDecl(), IsStructurallyEquivalent(), and IsTemplateDeclCommonStructurallyEquivalent().
IsStructurallyEquivalent() [4/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, ConceptDecl * D1, ConceptDecl * D2) static
Definition at line 1938 of file ASTStructuralEquivalence.cpp.
References clang::ConceptDecl::getConstraintExpr(), IsStructurallyEquivalent(), and IsTemplateDeclCommonStructurallyEquivalent().
IsStructurallyEquivalent() [5/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, const DeclarationName Name1, const DeclarationName Name2) static
Definition at line 113 of file ASTStructuralEquivalence.cpp.
References clang::DeclarationName::CXXConstructorName, clang::DeclarationName::CXXConversionFunctionName, clang::DeclarationName::CXXDeductionGuideName, clang::DeclarationName::CXXDestructorName, clang::DeclarationName::CXXLiteralOperatorName, clang::DeclarationName::CXXOperatorName, clang::DeclarationName::CXXUsingDirective, clang::DeclarationName::getAsIdentifierInfo(), clang::DeclarationName::getCXXDeductionGuideTemplate(), clang::DeclarationName::getCXXLiteralIdentifier(), clang::DeclarationName::getCXXNameType(), clang::DeclarationName::getCXXOverloadedOperator(), clang::NamedDecl::getDeclName(), clang::DeclarationName::getNameKind(), clang::DeclarationName::Identifier, IsStructurallyEquivalent(), clang::DeclarationName::ObjCMultiArgSelector, clang::DeclarationName::ObjCOneArgSelector, and clang::DeclarationName::ObjCZeroArgSelector.
IsStructurallyEquivalent() [6/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, const Stmt * S1, const Stmt * S2) static
Determine structural equivalence of two statements.
Definition at line 417 of file ASTStructuralEquivalence.cpp.
References clang::Stmt::children(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [7/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, const TemplateArgument & Arg1, const TemplateArgument & Arg2) static
Determine whether two template arguments are equivalent.
Definition at line 567 of file ASTStructuralEquivalence.cpp.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::TemplateArgument::getIntegralType(), clang::TemplateArgument::getKind(), clang::TemplateArgument::Integral, IsStructurallyEquivalent(), clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_elements(), clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, and clang::TemplateArgument::Type.
IsStructurallyEquivalent() [8/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, const TemplateArgumentLoc & Arg1, const TemplateArgumentLoc & Arg2) static
Determine whether two template argument locations are equivalent.
Definition at line 629 of file ASTStructuralEquivalence.cpp.
References clang::TemplateArgumentLoc::getArgument(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [9/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, const TemplateName & N1, const TemplateName & N2) static
Definition at line 489 of file ASTStructuralEquivalence.cpp.
References clang::TemplateName::AssumedTemplate, clang::OverloadedTemplateStorage::begin(), clang::TemplateName::DependentTemplate, clang::OverloadedTemplateStorage::end(), clang::SubstTemplateTemplateParmPackStorage::getArgumentPack(), clang::TemplateName::getAsAssumedTemplateName(), clang::TemplateName::getAsDependentTemplateName(), clang::TemplateName::getAsOverloadedTemplate(), clang::SubstTemplateTemplateParmPackStorage::getAssociatedDecl(), clang::TemplateName::getAsSubstTemplateTemplateParmPack(), clang::TemplateName::getAsTemplateDecl(), clang::AssumedTemplateStorage::getDeclName(), clang::DependentTemplateName::getIdentifier(), clang::SubstTemplateTemplateParmPackStorage::getIndex(), clang::TemplateName::getKind(), clang::DependentTemplateName::getOperator(), clang::DependentTemplateName::getQualifier(), clang::DependentTemplateName::isIdentifier(), clang::DependentTemplateName::isOverloadedOperator(), IsStructurallyEquivalent(), clang::TemplateName::OverloadedTemplate, clang::TemplateName::QualifiedTemplate, clang::TemplateName::SubstTemplateTemplateParm, clang::TemplateName::SubstTemplateTemplateParmPack, clang::TemplateName::Template, and clang::TemplateName::UsingTemplate.
IsStructurallyEquivalent() [10/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, CXXMethodDecl * Method1, CXXMethodDecl * Method2) static
Determine structural equivalence of two methods.
Definition at line 1356 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getAccess(), clang::DeclContext::getDeclKind(), clang::NamedDecl::getIdentifier(), clang::FunctionDecl::getOverloadedOperator(), clang::CXXMethodDecl::getRefQualifier(), clang::ValueDecl::getType(), clang::CXXMethodDecl::isConst(), clang::FunctionDecl::isDefaulted(), clang::FunctionDecl::isDeleted(), clang::FunctionDecl::isPure(), clang::CXXMethodDecl::isStatic(), IsStructurallyEquivalent(), clang::CXXMethodDecl::isVirtual(), and clang::CXXMethodDecl::isVolatile().
IsStructurallyEquivalent() [11/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, Decl * D1, Decl * D2) static
Determine structural equivalence of two declarations.
Definition at line 2115 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getCanonicalDecl(), and P.
IsStructurallyEquivalent() [12/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, EnumConstantDecl * D1, EnumConstantDecl * D2) static
Definition at line 1707 of file ASTStructuralEquivalence.cpp.
References clang::NamedDecl::getIdentifier(), clang::EnumConstantDecl::getInitExpr(), clang::EnumConstantDecl::getInitVal(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [13/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, EnumDecl * D1, EnumDecl * D2) static
Determine structural equivalence of two enums.
Definition at line 1728 of file ASTStructuralEquivalence.cpp.
References clang::EnumDecl::enumerator_begin(), clang::EnumDecl::enumerator_end(), clang::EnumDecl::getDefinition(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::ASTContext::getTypeDeclType(), clang::TagDecl::getTypedefNameForAnonDecl(), IsStructurallyEquivalent(), and clang::threadSafety::sx::toString().
IsStructurallyEquivalent() [14/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FieldDecl * Field1, FieldDecl * Field2) static
Determine structural equivalence of two fields.
Definition at line 1348 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getDeclContext(), clang::ASTContext::getTypeDeclType(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [15/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FieldDecl * Field1, FieldDecl * Field2, QualType Owner2Type) static
Definition at line 1293 of file ASTStructuralEquivalence.cpp.
References clang::Type::castAs(), clang::FieldDecl::getBitWidth(), clang::Decl::getDeclContext(), clang::NamedDecl::getDeclName(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::FieldDecl::isAnonymousStructOrUnion(), clang::FieldDecl::isBitField(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [16/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FriendDecl * D1, FriendDecl * D2) static
Definition at line 1950 of file ASTStructuralEquivalence.cpp.
References clang::FriendDecl::getFriendDecl(), clang::FriendDecl::getFriendType(), clang::TypeSourceInfo::getType(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [17/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FunctionDecl * D1, FunctionDecl * D2) static
Definition at line 1975 of file ASTStructuralEquivalence.cpp.
References clang::NamedDecl::getIdentifier(), clang::FunctionDecl::getOverloadedOperator(), clang::ValueDecl::getType(), clang::FunctionDecl::isOverloadedOperator(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [18/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FunctionTemplateDecl * D1, FunctionTemplateDecl * D2) static
Definition at line 1926 of file ASTStructuralEquivalence.cpp.
References clang::FunctionTemplateDecl::getTemplatedDecl(), clang::ValueDecl::getType(), IsStructurallyEquivalent(), and IsTemplateDeclCommonStructurallyEquivalent().
IsStructurallyEquivalent() [19/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, FunctionType::ExtInfo EI1, FunctionType::ExtInfo EI2) static
Determine structural equivalence based on the ExtInfo of functions.
This is inspired by ASTContext::mergeFunctionTypes(), we compare calling conventions bits but must not compare some other bits.
Definition at line 655 of file ASTStructuralEquivalence.cpp.
References clang::FunctionType::ExtInfo::getCC(), clang::FunctionType::ExtInfo::getHasRegParm(), clang::FunctionType::ExtInfo::getNoCallerSavedRegs(), clang::FunctionType::ExtInfo::getNoCfCheck(), clang::FunctionType::ExtInfo::getProducesResult(), and clang::FunctionType::ExtInfo::getRegParm().
IsStructurallyEquivalent() [20/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, NestedNameSpecifier * NNS1, NestedNameSpecifier * NNS2) static
Determine whether two nested-name-specifiers are equivalent.
Definition at line 451 of file ASTStructuralEquivalence.cpp.
References clang::NestedNameSpecifier::getAsIdentifier(), clang::NestedNameSpecifier::getAsNamespace(), clang::NestedNameSpecifier::getAsNamespaceAlias(), clang::NestedNameSpecifier::getAsRecordDecl(), clang::NestedNameSpecifier::getAsType(), clang::NestedNameSpecifier::getKind(), clang::NestedNameSpecifier::getPrefix(), clang::NestedNameSpecifier::Global, clang::NestedNameSpecifier::Identifier, IsStructurallyEquivalent(), clang::NestedNameSpecifier::Namespace, clang::NestedNameSpecifier::NamespaceAlias, clang::NestedNameSpecifier::Super, clang::NestedNameSpecifier::TypeSpec, and clang::NestedNameSpecifier::TypeSpecWithTemplate.
IsStructurallyEquivalent() [21/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, NonTypeTemplateParmDecl * D1, NonTypeTemplateParmDecl * D2) static
Definition at line 1852 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getLocation(), clang::ValueDecl::getType(), clang::NonTypeTemplateParmDecl::isParameterPack(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [22/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, ObjCCategoryDecl * D1, ObjCCategoryDecl * D2) static
Definition at line 2057 of file ASTStructuralEquivalence.cpp.
References clang::ObjCCategoryDecl::getClassInterface(), clang::NamedDecl::getIdentifier(), clang::ASTContext::getObjCInterfaceType(), IsStructurallyEquivalent(), clang::ObjCCategoryDecl::ivar_begin(), clang::ObjCCategoryDecl::ivar_end(), clang::ObjCContainerDecl::meth_begin(), clang::ObjCContainerDecl::meth_end(), clang::ObjCCategoryDecl::protocol_begin(), and clang::ObjCCategoryDecl::protocol_end().
IsStructurallyEquivalent() [23/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, ObjCIvarDecl * D1, ObjCIvarDecl * D2) static
Definition at line 2004 of file ASTStructuralEquivalence.cpp.
References clang::ObjCIvarDecl::getContainingInterface(), clang::ASTContext::getObjCInterfaceType(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [24/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, ObjCIvarDecl * D1, ObjCIvarDecl * D2, QualType Owner2Type) static
Definition at line 1994 of file ASTStructuralEquivalence.cpp.
References clang::ObjCIvarDecl::getAccessControl(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [25/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, ObjCMethodDecl * Method1, ObjCMethodDecl * Method2) static
Definition at line 2011 of file ASTStructuralEquivalence.cpp.
References clang::Selector::getIdentifierInfoForSlot(), clang::Selector::getNumArgs(), clang::ObjCMethodDecl::getReturnType(), clang::ObjCMethodDecl::getSelector(), clang::ObjCMethodDecl::isDirectMethod(), clang::ObjCMethodDecl::isInstanceMethod(), IsStructurallyEquivalent(), clang::ObjCMethodDecl::isVariadic(), clang::ObjCMethodDecl::param_size(), clang::ObjCMethodDecl::param_type_begin(), and clang::ObjCMethodDecl::param_type_end().
IsStructurallyEquivalent() [26/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, QualType T1, QualType T2) static
Determine structural equivalence of two types.
Definition at line 709 of file ASTStructuralEquivalence.cpp.
References clang::ASTContext::getCanonicalType(), clang::DependentSizedMatrixType::getColumnExpr(), clang::QualType::getDesugaredType(), clang::MatrixType::getElementType(), getKind(), clang::ConstantMatrixType::getNumColumns(), clang::ConstantMatrixType::getNumRows(), clang::QualType::getQualifiers(), clang::DependentSizedMatrixType::getRowExpr(), clang::Type::getTypeClass(), getUnderlyingType(), IsArrayStructurallyEquivalent(), IsEquivalentExceptionSpec(), clang::QualType::isNull(), and Paren.
Referenced by IsArrayStructurallyEquivalent(), clang::StructuralEquivalenceContext::IsEquivalent(), IsEquivalentExceptionSpec(), IsRecordContextStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalentLambdas(), and IsTemplateDeclCommonStructurallyEquivalent().
IsStructurallyEquivalent() [27/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, RecordDecl * D1, RecordDecl * D2) static
Determine structural equivalence of two records.
Definition at line 1457 of file ASTStructuralEquivalence.cpp.
References clang::ExternalASTSource::CompleteType(), clang::RecordDecl::field_begin(), clang::RecordDecl::field_end(), clang::StructuralEquivalenceContext::findUntaggedStructOrUnionIndex(), clang::Decl::getASTContext(), clang::CXXBaseSpecifier::getBeginLoc(), clang::NamedDecl::getDeclName(), clang::RecordDecl::getDefinition(), clang::ASTContext::getExternalSource(), clang::NamedDecl::getIdentifier(), clang::Decl::getLocation(), clang::CXXBaseSpecifier::getSourceRange(), clang::TagDecl::getTagKind(), clang::CXXBaseSpecifier::getType(), clang::ASTContext::getTypeDeclType(), clang::TagDecl::getTypedefNameForAnonDecl(), clang::DeclContext::hasExternalLexicalStorage(), clang::TagDecl::isBeingDefined(), IsRecordContextStructurallyEquivalent(), IsStructurallyEquivalent(), IsStructurallyEquivalentLambdas(), clang::TagDecl::isUnion(), and clang::Minimal.
IsStructurallyEquivalent() [28/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, TemplateParameterList * Params1, TemplateParameterList * Params2) static
Definition at line 1799 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getKind(), clang::Decl::getLocation(), clang::TemplateParameterList::getParam(), clang::TemplateParameterList::getTemplateLoc(), IsStructurallyEquivalent(), and clang::TemplateParameterList::size().
IsStructurallyEquivalent() [29/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, TemplateTemplateParmDecl * D1, TemplateTemplateParmDecl * D2) static
Definition at line 1883 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getLocation(), clang::TemplateDecl::getTemplateParameters(), clang::TemplateTemplateParmDecl::isParameterPack(), and IsStructurallyEquivalent().
IsStructurallyEquivalent() [30/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, TemplateTypeParmDecl * D1, TemplateTypeParmDecl * D2) static
Definition at line 1834 of file ASTStructuralEquivalence.cpp.
References clang::Decl::getLocation(), and clang::TemplateTypeParmDecl::isParameterPack().
IsStructurallyEquivalent() [31/31]
static bool IsStructurallyEquivalent (StructuralEquivalenceContext & Context, TypedefNameDecl * D1, TypedefNameDecl * D2) static
Definition at line 1966 of file ASTStructuralEquivalence.cpp.
References clang::NamedDecl::getIdentifier(), clang::TypedefNameDecl::getUnderlyingType(), and IsStructurallyEquivalent().
IsStructurallyEquivalentLambdas()
static bool IsStructurallyEquivalentLambdas (StructuralEquivalenceContext & Context, CXXRecordDecl * D1, CXXRecordDecl * D2) static
Determine structural equivalence of two lambda classes.
Definition at line 1409 of file ASTStructuralEquivalence.cpp.
References clang::CXXRecordDecl::getLambdaCallOperator(), clang::CXXRecordDecl::isLambda(), and IsStructurallyEquivalent().
Referenced by IsStructurallyEquivalent().
IsTemplateDeclCommonStructurallyEquivalent()
static bool IsTemplateDeclCommonStructurallyEquivalent (StructuralEquivalenceContext & Ctx, TemplateDecl * D1, TemplateDecl * D2) static
Definition at line 1903 of file ASTStructuralEquivalence.cpp.
References clang::NamedDecl::getIdentifier(), clang::NamedDecl::getNameAsString(), clang::TemplateDecl::getTemplateParameters(), and IsStructurallyEquivalent().
Referenced by IsStructurallyEquivalent().