clang: lib/Driver/ToolChains/BareMetal.cpp File Reference
BareMetal.cpp File Reference
#include "BareMetal.h"
#include "CommonArgs.h"
#include "Gnu.h"
#include "clang/Driver/InputInfo.h"
#include "Arch/RISCV.h"
#include "clang/Driver/Compilation.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "llvm/Option/ArgList.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/Support/raw_ostream.h"
Functions
static Multilib makeMultilib (StringRef commonSuffix)
static bool findRISCVMultilibs (const Driver &D, const llvm::Triple &TargetTriple, const ArgList &Args, DetectedMultilibs &Result)
static bool isARMBareMetal (const llvm::Triple &Triple)
Is the triple {arm,thumb}-none-none-{eabi,eabihf} ?
static bool isAArch64BareMetal (const llvm::Triple &Triple)
Is the triple aarch64-none-elf?
static bool isRISCVBareMetal (const llvm::Triple &Triple)
Function Documentation
findRISCVMultilibs()
static bool findRISCVMultilibs (const Driver & D, const llvm::Triple & TargetTriple, const ArgList & Args, DetectedMultilibs & Result) static
Definition at line 35 of file BareMetal.cpp.
References clang::driver::tools::addMultilibFlag(), clang::driver::MultilibSet::Either(), clang::driver::Multilib::flag(), clang::driver::tools::riscv::getRISCVABI(), clang::driver::tools::riscv::getRISCVArch(), and makeMultilib().
Referenced by clang::driver::toolchains::BareMetal::findMultilibs().
isAArch64BareMetal()
static bool isAArch64BareMetal (const llvm::Triple & Triple) static
Is the triple aarch64-none-elf?
Definition at line 130 of file BareMetal.cpp.
Referenced by clang::driver::toolchains::BareMetal::handlesTarget().
isARMBareMetal()
static bool isARMBareMetal (const llvm::Triple & Triple) static
Is the triple {arm,thumb}-none-none-{eabi,eabihf} ?
Definition at line 111 of file BareMetal.cpp.
Referenced by clang::driver::toolchains::BareMetal::handlesTarget().
isRISCVBareMetal()
static bool isRISCVBareMetal (const llvm::Triple & Triple) static
Definition at line 143 of file BareMetal.cpp.
Referenced by clang::driver::toolchains::BareMetal::findMultilibs(), and clang::driver::toolchains::BareMetal::handlesTarget().
makeMultilib()
static Multilib makeMultilib (StringRef commonSuffix) static
Definition at line 31 of file BareMetal.cpp.
Referenced by findRISCVMultilibs().