clang: lib/CodeGen/CGClass.cpp File Reference
CGClass.cpp File Reference
#include "CGBlocks.h"
#include "CGCXXABI.h"
#include "CGDebugInfo.h"
#include "CGRecordLayout.h"
#include "CodeGenFunction.h"
#include "TargetInfo.h"
#include "clang/AST/Attr.h"
#include "clang/AST/CXXInheritance.h"
#include "clang/AST/CharUnits.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/EvaluatedExprVisitor.h"
#include "clang/AST/RecordLayout.h"
#include "clang/AST/StmtCXX.h"
#include "clang/Basic/CodeGenOptions.h"
#include "clang/Basic/TargetBuiltins.h"
#include "clang/CodeGen/CGFunctionInfo.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Transforms/Utils/SanitizerStats.h"
#include <optional>
Functions
static Address ApplyNonVirtualAndVirtualOffset (CodeGenFunction &CGF, Address addr, CharUnits nonVirtualOffset, llvm::Value *virtualOffset, const CXXRecordDecl *derivedClass, const CXXRecordDecl *nearestVBase)
static bool BaseInitializerUsesThis (ASTContext &C, const Expr *Init)
static void EmitBaseInitializer (CodeGenFunction &CGF, const CXXRecordDecl *ClassDecl, CXXCtorInitializer *BaseInit)
static bool isMemcpyEquivalentSpecialMember (const CXXMethodDecl *D)
static void EmitLValueForAnyFieldInitialization (CodeGenFunction &CGF, CXXCtorInitializer *MemberInit, LValue &LHS)
static void EmitMemberInitializer (CodeGenFunction &CGF, const CXXRecordDecl *ClassDecl, CXXCtorInitializer *MemberInit, const CXXConstructorDecl *Constructor, FunctionArgList &Args)
static bool isInitializerOfDynamicClass (const CXXCtorInitializer *BaseInit)
static bool FieldHasTrivialDestructorBody (ASTContext &Context, const FieldDecl *Field)
static bool HasTrivialDestructorBody (ASTContext &Context, const CXXRecordDecl *BaseClassDecl, const CXXRecordDecl *MostDerivedClassDecl)
static bool CanSkipVTablePointerInitialization (CodeGenFunction &CGF, const CXXDestructorDecl *Dtor)
CanSkipVTablePointerInitialization - Check whether we need to initialize any vtable pointers before calling this destructor.
static bool canEmitDelegateCallArgs (CodeGenFunction &CGF, const CXXConstructorDecl *Ctor, CXXCtorType Type, CallArgList &Args)
static const CXXRecordDecl * LeastDerivedClassWithSameLayout (const CXXRecordDecl *RD)
Function Documentation
ApplyNonVirtualAndVirtualOffset()
static Address ApplyNonVirtualAndVirtualOffset (CodeGenFunction & CGF, Address addr, CharUnits nonVirtualOffset, llvm::Value * virtualOffset, const CXXRecordDecl * derivedClass, const CXXRecordDecl * nearestVBase) static
Definition at line 248 of file CGClass.cpp.
References clang::CharUnits::alignmentAtOffset(), clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::Address::getAlignment(), clang::TargetInfo::getCXXABI(), clang::CodeGen::CodeGenModule::getItaniumVTableContext(), clang::CodeGen::Address::getPointer(), clang::CharUnits::getQuantity(), clang::CodeGen::CodeGenModule::getTarget(), clang::CodeGen::CodeGenModule::getVBaseAlignment(), clang::CodeGen::CodeGenTypeCache::Int32Ty, clang::CodeGen::CodeGenTypeCache::Int8Ty, clang::TargetCXXABI::isItaniumFamily(), clang::ItaniumVTableContext::isRelativeLayout(), clang::CharUnits::isZero(), and clang::CodeGen::CodeGenTypeCache::PtrDiffTy.
Referenced by clang::CodeGen::CodeGenFunction::EmitVTableAssumptionLoad(), clang::CodeGen::CodeGenFunction::GetAddressOfBaseClass(), and clang::CodeGen::CodeGenFunction::InitializeVTablePointer().
BaseInitializerUsesThis()
static bool BaseInitializerUsesThis (ASTContext & C, const Expr * Init) static
Definition at line 550 of file CGClass.cpp.
Referenced by EmitBaseInitializer().
canEmitDelegateCallArgs()
static bool canEmitDelegateCallArgs (CodeGenFunction & CGF, const CXXConstructorDecl * Ctor, CXXCtorType Type, CallArgList & Args) static
Definition at line 2171 of file CGClass.cpp.
References clang::TargetCXXABI::areArgsDestroyedLeftToRightInCallee(), clang::CodeGen::CodeGenTypes::arrangeCXXConstructorCall(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CodeGenFunction::getContext(), clang::TargetInfo::getCXXABI(), clang::CodeGen::CodeGenFunction::getTarget(), clang::CodeGen::CodeGenModule::getTypes(), clang::FunctionDecl::isVariadic(), P, clang::FunctionDecl::parameters(), and clang::CodeGen::CGFunctionInfo::usesInAlloca().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall().
CanSkipVTablePointerInitialization()
static bool CanSkipVTablePointerInitialization (CodeGenFunction & CGF, const CXXDestructorDecl * Dtor) static
CanSkipVTablePointerInitialization - Check whether we need to initialize any vtable pointers before calling this destructor.
Definition at line 1415 of file CGClass.cpp.
References FieldHasTrivialDestructorBody(), clang::RecordDecl::fields(), clang::CodeGen::CodeGenFunction::getContext(), clang::CXXMethodDecl::getParent(), clang::FunctionDecl::hasTrivialBody(), clang::CXXRecordDecl::isDynamicClass(), and clang::CXXRecordDecl::isEffectivelyFinal().
Referenced by clang::CodeGen::CodeGenFunction::EmitDestructorBody().
EmitBaseInitializer()
static void EmitBaseInitializer (CodeGenFunction & CGF, const CXXRecordDecl * ClassDecl, CXXCtorInitializer * BaseInit) static
Definition at line 556 of file CGClass.cpp.
References BaseInitializerUsesThis(), clang::Type::castAs(), clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::AggValueSlot::DoesNotNeedGCBarriers, clang::CodeGen::EHCleanup, clang::CodeGen::CodeGenFunction::EHStack, clang::CodeGen::CodeGenFunction::EmitAggExpr(), clang::CodeGen::AggValueSlot::forAddr(), clang::CodeGen::CodeGenFunction::GetAddressOfDirectBaseInCompleteClass(), clang::CXXCtorInitializer::getBaseClass(), clang::CodeGen::CodeGenFunction::getContext(), clang::RecordType::getDecl(), clang::CXXCtorInitializer::getInit(), clang::CodeGen::CodeGenModule::getLangOpts(), clang::CodeGen::CodeGenFunction::getOverlapForBaseInit(), clang::CodeGen::CodeGenFunction::InitializeVTablePointers(), clang::CXXCtorInitializer::isBaseInitializer(), clang::CXXCtorInitializer::isBaseVirtual(), clang::CodeGen::AggValueSlot::IsDestructed, clang::CodeGen::AggValueSlot::IsNotAliased, clang::CodeGen::CodeGenFunction::LoadCXXThisAddress(), and V.
Referenced by clang::CodeGen::CodeGenFunction::EmitCtorPrologue().
EmitLValueForAnyFieldInitialization()
static void EmitLValueForAnyFieldInitialization (CodeGenFunction & CGF, CXXCtorInitializer * MemberInit, LValue & LHS) static
Definition at line 615 of file CGClass.cpp.
References clang::IndirectFieldDecl::chain(), clang::CodeGen::CodeGenFunction::EmitLValueForFieldInitialization(), clang::CXXCtorInitializer::getAnyMember(), clang::CXXCtorInitializer::getIndirectMember(), and clang::CXXCtorInitializer::isIndirectMemberInitializer().
Referenced by EmitMemberInitializer().
EmitMemberInitializer()
static void EmitMemberInitializer (CodeGenFunction & CGF, const CXXRecordDecl * ClassDecl, CXXCtorInitializer * MemberInit, const CXXConstructorDecl * Constructor, FunctionArgList & Args) static
Definition at line 629 of file CGClass.cpp.
References clang::CodeGen::CodeGenFunction::Builder, clang::CodeGen::CodeGenFunction::CGM, clang::CodeGen::CGBuilderTy::CreateLoad(), clang::Ctor_Base, clang::CodeGen::CodeGenFunction::CurGD, clang::CodeGen::CodeGenFunction::EmitAggregateCopy(), clang::CodeGen::CodeGenFunction::EmitInitializerForField(), EmitLValueForAnyFieldInitialization(), clang::CodeGen::CodeGenFunction::EmitLValueForFieldInitialization(), clang::CodeGen::LValue::getAddress(), clang::CodeGen::CodeGenFunction::GetAddrOfLocalVar(), clang::CXXCtorInitializer::getAnyMember(), clang::ASTContext::getAsConstantArrayType(), clang::ASTContext::getBaseElementType(), clang::CXXConstructExpr::getConstructor(), clang::CodeGen::CodeGenFunction::getContext(), clang::GlobalDecl::getCtorType(), clang::CodeGen::CodeGenModule::getCXXABI(), clang::CXXCtorInitializer::getInit(), clang::CodeGen::CodeGenFunction::getOverlapForFieldInit(), clang::CXXCtorInitializer::getSourceLocation(), clang::CodeGen::CGCXXABI::getSrcArgforCopyCtor(), clang::ASTContext::getTypeDeclType(), clang::CXXCtorInitializer::isAnyMemberInitializer(), clang::QualType::isDestructedType(), isMemcpyEquivalentSpecialMember(), clang::QualType::isPODType(), clang::CodeGen::LValue::isVolatileQualified(), clang::CodeGen::CodeGenFunction::LoadCXXThis(), clang::CodeGen::CodeGenFunction::MakeNaturalAlignAddrLValue(), clang::CodeGen::CodeGenFunction::MakeNaturalAlignPointeeAddrLValue(), clang::CodeGen::CodeGenFunction::needsEHCleanup(), and clang::CodeGen::CodeGenFunction::pushEHDestroy().
FieldHasTrivialDestructorBody()
static bool FieldHasTrivialDestructorBody (ASTContext & Context, const FieldDecl * Field) static
Definition at line 1395 of file CGClass.cpp.
References clang::Type::getAs(), clang::ASTContext::getBaseElementType(), clang::RecordType::getDecl(), HasTrivialDestructorBody(), clang::RecordDecl::isAnonymousStructOrUnion(), and clang::TagDecl::isUnion().
Referenced by CanSkipVTablePointerInitialization(), and HasTrivialDestructorBody().
HasTrivialDestructorBody()
static bool HasTrivialDestructorBody (ASTContext & Context, const CXXRecordDecl * BaseClassDecl, const CXXRecordDecl * MostDerivedClassDecl) static
Definition at line 1352 of file CGClass.cpp.
References clang::CXXRecordDecl::bases(), FieldHasTrivialDestructorBody(), clang::RecordDecl::fields(), clang::RecordType::getDecl(), clang::CXXRecordDecl::getDestructor(), clang::FunctionDecl::hasTrivialBody(), clang::CXXRecordDecl::hasTrivialDestructor(), and clang::CXXRecordDecl::vbases().
Referenced by FieldHasTrivialDestructorBody().
isInitializerOfDynamicClass()
static bool isInitializerOfDynamicClass (const CXXCtorInitializer * BaseInit) static
Definition at line 1261 of file CGClass.cpp.
References clang::Type::castAs(), clang::CXXCtorInitializer::getBaseClass(), and clang::RecordType::getDecl().
Referenced by clang::CodeGen::CodeGenFunction::EmitCtorPrologue().
isMemcpyEquivalentSpecialMember()
static bool isMemcpyEquivalentSpecialMember (const CXXMethodDecl * D) static
Definition at line 598 of file CGClass.cpp.
References clang::CXXMethodDecl::getParent(), clang::CXXMethodDecl::isCopyAssignmentOperator(), clang::FunctionDecl::isDefaulted(), clang::CXXMethodDecl::isMoveAssignmentOperator(), clang::FunctionDecl::isTrivial(), clang::TagDecl::isUnion(), and clang::RecordDecl::mayInsertExtraPadding().
Referenced by clang::CodeGen::CodeGenFunction::EmitCXXConstructorCall(), and EmitMemberInitializer().
LeastDerivedClassWithSameLayout()
static const CXXRecordDecl* LeastDerivedClassWithSameLayout (const CXXRecordDecl * RD) static
Definition at line 2708 of file CGClass.cpp.
References clang::CXXRecordDecl::bases_begin(), clang::RecordDecl::field_empty(), clang::Type::getAsCXXRecordDecl(), clang::CXXRecordDecl::getNumBases(), clang::CXXRecordDecl::getNumVBases(), clang::CXXBaseSpecifier::getType(), clang::Decl::isImplicit(), clang::CXXMethodDecl::isVirtual(), and clang::CXXRecordDecl::methods().
Referenced by clang::CodeGen::CodeGenFunction::EmitVTablePtrCheckForCall(), and clang::CodeGen::CodeGenFunction::EmitVTablePtrCheckForCast().