clang: clang::Designator Class Reference
clang::Designator Class Reference
Designator - A designator in a C99 designated initializer.
#include "clang/AST/Designator.h"
Public Member Functions
Designator ()
bool isFieldDesignator () const
bool isArrayDesignator () const
bool isArrayRangeDesignator () const
const IdentifierInfo * getFieldName () const
FieldDecl * getField () const
void setField (FieldDecl *FD)
SourceLocation getDotLoc () const
SourceLocation getFieldLoc () const
template<typename Ty = Expr *>
Ty getArrayIndex () const
Expr * getArrayRangeStart () const
Expr * getArrayRangeEnd () const
SourceLocation getLBracketLoc () const
SourceLocation getEllipsisLoc () const
SourceLocation getRBracketLoc () const
void setRBracketLoc (SourceLocation RBracketLoc)
unsigned getFirstExprIndex () const
SourceLocation getBeginLoc () const LLVM_READONLY
Source location accessors.
SourceLocation getEndLoc () const LLVM_READONLY
SourceRange getSourceRange () const LLVM_READONLY
Static Public Member Functions
static Designator CreateFieldDesignator (const IdentifierInfo *FieldName, SourceLocation DotLoc, SourceLocation NameLoc)
FieldDesignatorInfo:
static Designator CreateArrayDesignator (Expr *Start, SourceLocation LBracketLoc, SourceLocation RBracketLoc=SourceLocation())
ArrayDesignatorInfo:
static Designator CreateArrayDesignator (unsigned Start, SourceLocation LBracketLoc, SourceLocation RBracketLoc=SourceLocation())
static Designator CreateArrayRangeDesignator (Expr *Start, Expr *End, SourceLocation LBracketLoc, SourceLocation EllipsisLoc, SourceLocation RBracketLoc=SourceLocation())
ArrayRangeDesignatorInfo:
static Designator CreateArrayRangeDesignator (unsigned Index, SourceLocation LBracketLoc, SourceLocation EllipsisLoc, SourceLocation RBracketLoc=SourceLocation())
Detailed Description
Designator - A designator in a C99 designated initializer.
This class is a discriminated union which holds the various different sorts of designators possible. A Designation is an array of these. An example of a designator are things like this:
 [8] .field [47]        // C99 designation: 3 designators
 [8 ... 47]  field:     // GNU extensions: 2 designators
These occur in initializers, e.g.:
 int a[10] = {2, 4, [8]=9, 10};
Definition at line 40 of file Designator.h.
Constructor & Destructor Documentation
Designator()
clang::Designator::Designator () inline
Definition at line 122 of file Designator.h.
Member Function Documentation
CreateArrayDesignator() [1/2]
static Designator clang::Designator::CreateArrayDesignator (Expr * Start, SourceLocation LBracketLoc, SourceLocation RBracketLoc = SourceLocation()) inline static
ArrayDesignatorInfo:
Definition at line 165 of file Designator.h.
References ArrayInfoExpr.
Referenced by clang::ASTNodeImporter::import().
CreateArrayDesignator() [2/2]
static Designator clang::Designator::CreateArrayDesignator (unsigned Start, SourceLocation LBracketLoc, SourceLocation RBracketLoc = SourceLocation()) inline static
Definition at line 173 of file Designator.h.
References ArrayInfoInt.
CreateArrayRangeDesignator() [1/2]
static Designator clang::Designator::CreateArrayRangeDesignator (Expr * Start, Expr * End, SourceLocation LBracketLoc, SourceLocation EllipsisLoc, SourceLocation RBracketLoc = SourceLocation()) inline static
ArrayRangeDesignatorInfo:
Definition at line 188 of file Designator.h.
References ArrayInfoExpr, and End.
Referenced by clang::ASTNodeImporter::import().
CreateArrayRangeDesignator() [2/2]
static Designator clang::Designator::CreateArrayRangeDesignator (unsigned Index, SourceLocation LBracketLoc, SourceLocation EllipsisLoc, SourceLocation RBracketLoc = SourceLocation()) inline static
Definition at line 197 of file Designator.h.
CreateFieldDesignator()
static Designator clang::Designator::CreateFieldDesignator (const IdentifierInfo * FieldName, SourceLocation DotLoc, SourceLocation NameLoc) inline static
FieldDesignatorInfo:
Definition at line 133 of file Designator.h.
References FieldInfo.
Referenced by clang::Sema::ActOnDesignatedInitializer(), and clang::ASTNodeImporter::import().
getArrayIndex()
template<typename Ty = Expr *> Ty clang::Designator::getArrayIndex () const inline
Definition at line 181 of file Designator.h.
References ArrayInfoExpr, and isArrayDesignator().
getArrayRangeEnd()
Expr* clang::Designator::getArrayRangeEnd () const inline
Definition at line 211 of file Designator.h.
References ArrayInfoExpr, and isArrayRangeDesignator().
getArrayRangeStart()
Expr* clang::Designator::getArrayRangeStart () const inline
Definition at line 206 of file Designator.h.
References ArrayInfoExpr, and isArrayRangeDesignator().
getBeginLoc()
SourceLocation clang::Designator::getBeginLoc () const inline
Source location accessors.
Definition at line 287 of file Designator.h.
References getDotLoc(), getFieldLoc(), getLBracketLoc(), isFieldDesignator(), and clang::SourceLocation::isInvalid().
Referenced by clang::DesignatedInitExpr::getDesignatorsSourceRange(), and getSourceRange().
getDotLoc()
SourceLocation clang::Designator::getDotLoc () const inline
Definition at line 153 of file Designator.h.
References FieldInfo, and isFieldDesignator().
Referenced by clang::Sema::ActOnDesignatedInitializer(), ExpandAnonymousFieldDesignator(), getBeginLoc(), and clang::ASTNodeImporter::import().
getEllipsisLoc()
SourceLocation clang::Designator::getEllipsisLoc () const inline
Definition at line 232 of file Designator.h.
References ArrayInfoExpr, and ArrayInfoInt.
Referenced by clang::ASTNodeImporter::import().
getEndLoc()
SourceLocation clang::Designator::getEndLoc () const inline
Definition at line 292 of file Designator.h.
References getFieldLoc(), getRBracketLoc(), and isFieldDesignator().
Referenced by getSourceRange().
getField()
FieldDecl* clang::Designator::getField () const inline
Definition at line 143 of file Designator.h.
References FieldInfo, and isFieldDesignator().
getFieldLoc()
SourceLocation clang::Designator::getFieldLoc () const inline
Definition at line 158 of file Designator.h.
References FieldInfo, and isFieldDesignator().
Referenced by clang::Sema::ActOnDesignatedInitializer(), ExpandAnonymousFieldDesignator(), getBeginLoc(), getEndLoc(), and clang::ASTNodeImporter::import().
getFieldName()
const IdentifierInfo * Designator::getFieldName () const
Definition at line 4392 of file Expr.cpp.
References FieldInfo, and isFieldDesignator().
Referenced by clang::Sema::ActOnDesignatedInitializer(), and clang::ASTNodeImporter::import().
getFirstExprIndex()
unsigned clang::Designator::getFirstExprIndex () const inline
Definition at line 278 of file Designator.h.
References ArrayInfoInt.
Referenced by clang::DesignatedInitExpr::getArrayIndex(), clang::DesignatedInitExpr::getArrayRangeEnd(), clang::DesignatedInitExpr::getArrayRangeStart(), and clang::ASTNodeImporter::import().
getLBracketLoc()
SourceLocation clang::Designator::getLBracketLoc () const inline
Definition at line 216 of file Designator.h.
References ArrayInfoExpr, and ArrayInfoInt.
Referenced by getBeginLoc(), and clang::ASTNodeImporter::import().
getRBracketLoc()
SourceLocation clang::Designator::getRBracketLoc () const inline
Definition at line 246 of file Designator.h.
References ArrayInfoExpr, and ArrayInfoInt.
Referenced by getEndLoc(), and clang::ASTNodeImporter::import().
getSourceRange()
SourceRange clang::Designator::getSourceRange () const inline
Definition at line 295 of file Designator.h.
References getBeginLoc(), and getEndLoc().
Referenced by clang::DesignatedInitExpr::getDesignatorsSourceRange().
isArrayDesignator()
bool clang::Designator::isArrayDesignator () const inline
Definition at line 125 of file Designator.h.
Referenced by clang::Sema::ActOnDesignatedInitializer(), CheckArrayDesignatorSyntax(), getArrayIndex(), clang::DesignatedInitExpr::getArrayIndex(), and clang::ASTNodeImporter::import().
isArrayRangeDesignator()
bool clang::Designator::isArrayRangeDesignator () const inline
Definition at line 128 of file Designator.h.
Referenced by CheckArrayDesignatorSyntax(), getArrayRangeEnd(), clang::DesignatedInitExpr::getArrayRangeEnd(), getArrayRangeStart(), clang::DesignatedInitExpr::getArrayRangeStart(), and clang::ASTNodeImporter::import().
isFieldDesignator()
bool clang::Designator::isFieldDesignator () const inline
Definition at line 124 of file Designator.h.
Referenced by clang::Sema::ActOnDesignatedInitializer(), getBeginLoc(), getDotLoc(), getEndLoc(), getField(), getFieldLoc(), getFieldName(), clang::ASTNodeImporter::import(), and setField().
setField()
void clang::Designator::setField (FieldDecl * FD) inline
Definition at line 148 of file Designator.h.
References FieldInfo, and isFieldDesignator().
setRBracketLoc()
void clang::Designator::setRBracketLoc (SourceLocation RBracketLoc) inline
Definition at line 262 of file Designator.h.
References ArrayInfoExpr, and ArrayInfoInt.
Member Data Documentation
ArrayInfoExpr
ArrayDesignatorInfo<Expr *> clang::Designator::ArrayInfoExpr
Definition at line 115 of file Designator.h.
Referenced by CreateArrayDesignator(), CreateArrayRangeDesignator(), getArrayIndex(), getArrayRangeEnd(), getArrayRangeStart(), getEllipsisLoc(), getLBracketLoc(), getRBracketLoc(), and setRBracketLoc().
ArrayInfoInt
ArrayDesignatorInfo<unsigned> clang::Designator::ArrayInfoInt
Definition at line 116 of file Designator.h.
Referenced by CreateArrayDesignator(), getEllipsisLoc(), getFirstExprIndex(), getLBracketLoc(), getRBracketLoc(), and setRBracketLoc().
FieldInfo
FieldDesignatorInfo clang::Designator::FieldInfo
Definition at line 114 of file Designator.h.
Referenced by CreateFieldDesignator(), getDotLoc(), getField(), getFieldLoc(), getFieldName(), and setField().
The documentation for this class was generated from the following files:
include/clang/AST/Designator.h
lib/AST/Expr.cpp