clang: clang::OptionalFileEntryRefDegradesToFileEntryPtr Class Reference
clang::OptionalFileEntryRefDegradesToFileEntryPtr Class Reference
Wrapper around OptionalFileEntryRef that degrades to 'const FileEntry*', facilitating incremental patches to propagate FileEntryRef.
#include "clang/Basic/FileEntry.h"
Public Member Functions
OptionalFileEntryRefDegradesToFileEntryPtr ()=default
OptionalFileEntryRefDegradesToFileEntryPtr (OptionalFileEntryRefDegradesToFileEntryPtr &&)=default
OptionalFileEntryRefDegradesToFileEntryPtr (const OptionalFileEntryRefDegradesToFileEntryPtr &)=default
OptionalFileEntryRefDegradesToFileEntryPtr & operator= (OptionalFileEntryRefDegradesToFileEntryPtr &&)=default
OptionalFileEntryRefDegradesToFileEntryPtr & operator= (const OptionalFileEntryRefDegradesToFileEntryPtr &)=default
OptionalFileEntryRefDegradesToFileEntryPtr (std::nullopt_t)
OptionalFileEntryRefDegradesToFileEntryPtr (FileEntryRef Ref)
OptionalFileEntryRefDegradesToFileEntryPtr (OptionalFileEntryRef MaybeRef)
OptionalFileEntryRefDegradesToFileEntryPtr & operator= (std::nullopt_t)
OptionalFileEntryRefDegradesToFileEntryPtr & operator= (FileEntryRef Ref)
OptionalFileEntryRefDegradesToFileEntryPtr & operator= (OptionalFileEntryRef MaybeRef)
operator const FileEntry * () const
Degrade to 'const FileEntry *' to allow FileEntry::LastRef and FileEntry::getName have been deleted, delete this class and replace instances with OptionalFileEntryRef.
Public Member Functions inherited from clang::CustomizableOptional< FileEntryRef >
constexpr CustomizableOptional ()=default
constexpr CustomizableOptional (std::nullopt_t)
constexpr CustomizableOptional (const FileEntryRef &y)
constexpr CustomizableOptional (const CustomizableOptional &O)=default
constexpr CustomizableOptional (FileEntryRef &&y)
constexpr CustomizableOptional (CustomizableOptional &&O)=default
constexpr CustomizableOptional (std::in_place_t, ArgTypes &&...Args)
constexpr CustomizableOptional (const std::optional< FileEntryRef > &y)
constexpr CustomizableOptional (std::optional< FileEntryRef > &&y)
CustomizableOptional & operator= (FileEntryRef &&y)
CustomizableOptional & operator= (CustomizableOptional &&O)=default
CustomizableOptional & operator= (const FileEntryRef &y)
CustomizableOptional & operator= (const CustomizableOptional &O)=default
void emplace (ArgTypes &&...Args)
Create a new object by constructing it in place with the given arguments.
void reset ()
constexpr const FileEntryRef * getPointer () const
FileEntryRef * getPointer ()
constexpr const FileEntryRef & value () const &
FileEntryRef & value () &
FileEntryRef && value () &&
constexpr operator bool () const
constexpr bool has_value () const
constexpr const FileEntryRef * operator-> () const
FileEntryRef * operator-> ()
constexpr const FileEntryRef & operator* () const &
FileEntryRef & operator* () &
FileEntryRef && operator* () &&
constexpr FileEntryRef value_or (U &&alt) const &
FileEntryRef value_or (U &&alt) &&
operator std::optional< FileEntryRef > & () const &
operator std::optional< FileEntryRef > && () const &&
Additional Inherited Members
Public Types inherited from clang::CustomizableOptional< FileEntryRef >
using value_type = FileEntryRef
Detailed Description
Wrapper around OptionalFileEntryRef that degrades to 'const FileEntry*', facilitating incremental patches to propagate FileEntryRef.
This class can be used as return value or field where it's convenient for an OptionalFileEntryRef to degrade to a 'const FileEntry*'. The purpose is to avoid code churn due to dances like the following:
// Old code.
lvalue = rvalue;
// Temporary code from an incremental patch.
OptionalFileEntryRef MaybeF = rvalue;
lvalue = MaybeF ? &MaybeF.getFileEntry() : nullptr;
// Final code.
lvalue = rvalue;
FIXME: Once FileEntryRef is "everywhere" and FileEntry::LastRef and FileEntry::getName have been deleted, delete this class and replace instances with OptionalFileEntryRef.
Definition at line 290 of file FileEntry.h.
Constructor & Destructor Documentation
OptionalFileEntryRefDegradesToFileEntryPtr() [1/6]
clang::OptionalFileEntryRefDegradesToFileEntryPtr::OptionalFileEntryRefDegradesToFileEntryPtr () default
OptionalFileEntryRefDegradesToFileEntryPtr() [2/6]
clang::OptionalFileEntryRefDegradesToFileEntryPtr::OptionalFileEntryRefDegradesToFileEntryPtr (OptionalFileEntryRefDegradesToFileEntryPtr &&) default
OptionalFileEntryRefDegradesToFileEntryPtr() [3/6]
clang::OptionalFileEntryRefDegradesToFileEntryPtr::OptionalFileEntryRefDegradesToFileEntryPtr (const OptionalFileEntryRefDegradesToFileEntryPtr &) default
OptionalFileEntryRefDegradesToFileEntryPtr() [4/6]
clang::OptionalFileEntryRefDegradesToFileEntryPtr::OptionalFileEntryRefDegradesToFileEntryPtr (std::nullopt_t) inline
Definition at line 302 of file FileEntry.h.
OptionalFileEntryRefDegradesToFileEntryPtr() [5/6]
clang::OptionalFileEntryRefDegradesToFileEntryPtr::OptionalFileEntryRefDegradesToFileEntryPtr (FileEntryRef Ref) inline
Definition at line 303 of file FileEntry.h.
OptionalFileEntryRefDegradesToFileEntryPtr() [6/6]
clang::OptionalFileEntryRefDegradesToFileEntryPtr::OptionalFileEntryRefDegradesToFileEntryPtr (OptionalFileEntryRef MaybeRef) inline
Definition at line 305 of file FileEntry.h.
Member Function Documentation
operator const FileEntry *()
clang::OptionalFileEntryRefDegradesToFileEntryPtr::operator const FileEntry * () const inline
Degrade to 'const FileEntry *' to allow FileEntry::LastRef and FileEntry::getName have been deleted, delete this class and replace instances with OptionalFileEntryRef.
Definition at line 325 of file FileEntry.h.
References clang::CustomizableOptional< FileEntryRef >::has_value().
operator=() [1/5]
OptionalFileEntryRefDegradesToFileEntryPtr& clang::OptionalFileEntryRefDegradesToFileEntryPtr::operator= (const OptionalFileEntryRefDegradesToFileEntryPtr &) default
operator=() [2/5]
OptionalFileEntryRefDegradesToFileEntryPtr& clang::OptionalFileEntryRefDegradesToFileEntryPtr::operator= (FileEntryRef Ref) inline
Definition at line 312 of file FileEntry.h.
References clang::CustomizableOptional< FileEntryRef >::operator=().
operator=() [3/5]
OptionalFileEntryRefDegradesToFileEntryPtr& clang::OptionalFileEntryRefDegradesToFileEntryPtr::operator= (OptionalFileEntryRef MaybeRef) inline
Definition at line 317 of file FileEntry.h.
References clang::CustomizableOptional< FileEntryRef >::operator=().
operator=() [4/5]
OptionalFileEntryRefDegradesToFileEntryPtr& clang::OptionalFileEntryRefDegradesToFileEntryPtr::operator= (OptionalFileEntryRefDegradesToFileEntryPtr &&) default
operator=() [5/5]
OptionalFileEntryRefDegradesToFileEntryPtr& clang::OptionalFileEntryRefDegradesToFileEntryPtr::operator= (std::nullopt_t) inline
Definition at line 308 of file FileEntry.h.
References clang::CustomizableOptional< FileEntryRef >::operator=().
The documentation for this class was generated from the following file:
include/clang/Basic/FileEntry.h