clang: clang::dataflow::Value Class Reference
clang::dataflow::Value Class Reference
Base class for all values computed by abstract interpretation.
#include "clang/Analysis/FlowSensitive/Value.h"
Public Types
enum Kind {
Kind::Integer, Kind::Reference, Kind::Pointer, Kind::Struct,
Kind::TopBool, Kind::AtomicBool, Kind::Conjunction, Kind::Disjunction,
Kind::Negation, Kind::Implication, Kind::Biconditional
}
Public Member Functions
Value (Kind ValKind)
Value (const Value &)=delete
Value & operator= (const Value &)=delete
virtual ~Value ()=default
Kind getKind () const
Value * getProperty (llvm::StringRef Name) const
Returns the value of the synthetic property with the given Name or null if the property isn't assigned a value.
void setProperty (llvm::StringRef Name, Value &Val)
Assigns Val as the value of the synthetic property with the given Name.
Detailed Description
Base class for all values computed by abstract interpretation.
Don't use Value instances by value. All Value instances are allocated and owned by DataflowAnalysisContext.
Definition at line 33 of file Value.h.
Member Enumeration Documentation
Kind
enum clang::dataflow::Value::Kind strong
Enumerator
Integer
Reference
Pointer
Struct
TopBool
AtomicBool
Conjunction
Disjunction
Negation
Implication
Biconditional
Definition at line 35 of file Value.h.
Constructor & Destructor Documentation
Value() [1/2]
clang::dataflow::Value::Value (Kind ValKind) inline explicit
Definition at line 51 of file Value.h.
Value() [2/2]
clang::dataflow::Value::Value (const Value &) delete
~Value()
virtual clang::dataflow::Value::~Value () virtual default
Member Function Documentation
getKind()
Kind clang::dataflow::Value::getKind () const inline
Definition at line 61 of file Value.h.
Referenced by clang::dataflow::areEquivalentValues(), clang::dataflow::buildBooleanFormula(), clang::dataflow::BoolValue::classof(), clang::dataflow::TopBoolValue::classof(), clang::dataflow::AtomicBoolValue::classof(), clang::dataflow::ConjunctionValue::classof(), clang::dataflow::DisjunctionValue::classof(), clang::dataflow::NegationValue::classof(), clang::dataflow::ImplicationValue::classof(), clang::dataflow::BiconditionalValue::classof(), clang::dataflow::IntegerValue::classof(), clang::dataflow::ReferenceValue::classof(), clang::dataflow::PointerValue::classof(), clang::dataflow::StructValue::classof(), clang::dataflow::compareDistinctValues(), and clang::dataflow::operator<<().
getProperty()
Value* clang::dataflow::Value::getProperty (llvm::StringRef Name) const inline
Returns the value of the synthetic property with the given Name or null if the property isn't assigned a value.
Definition at line 65 of file Value.h.
operator=()
Value& clang::dataflow::Value::operator= (const Value &) delete
setProperty()
void clang::dataflow::Value::setProperty (llvm::StringRef Name, Value & Val) inline
Assigns Val as the value of the synthetic property with the given Name.
Definition at line 72 of file Value.h.
The documentation for this class was generated from the following file:
include/clang/Analysis/FlowSensitive/Value.h