clang: clang::format::QualifierAlignmentFixer Class Reference
clang::format::QualifierAlignmentFixer Class Reference
#include "/home/cambricon/llvm/llvm-project/clang/lib/Format/QualifierAlignmentFixer.h"
Public Member Functions
QualifierAlignmentFixer (const Environment &Env, const FormatStyle &Style, StringRef &Code, ArrayRef< tooling::Range > Ranges, unsigned FirstStartColumn, unsigned NextStartColumn, unsigned LastStartColumn, StringRef FileName)
std::pair< tooling::Replacements, unsigned > analyze (TokenAnnotator &Annotator, SmallVectorImpl< AnnotatedLine * > &AnnotatedLines, FormatTokenLexer &Tokens) override
Public Member Functions inherited from clang::format::TokenAnalyzer
TokenAnalyzer (const Environment &Env, const FormatStyle &Style)
std::pair< tooling::Replacements, unsigned > process (bool SkipAnnotation=false)
Public Member Functions inherited from clang::format::UnwrappedLineConsumer
virtual ~UnwrappedLineConsumer ()
Static Public Member Functions
static void PrepareLeftRightOrdering (const std::vector< std::string > &Order, std::vector< std::string > &LeftOrder, std::vector< std::string > &RightOrder, std::vector< tok::TokenKind > &Qualifiers)
Additional Inherited Members
Protected Member Functions inherited from clang::format::TokenAnalyzer
void consumeUnwrappedLine (const UnwrappedLine &TheLine) override
void finishRun () override
Protected Attributes inherited from clang::format::TokenAnalyzer
FormatStyle Style
const Environment & Env
AffectedRangeManager AffectedRangeMgr
SmallVector< SmallVector< UnwrappedLine, 16 >, 2 > UnwrappedLines
encoding::Encoding Encoding
Detailed Description
Definition at line 28 of file QualifierAlignmentFixer.h.
Constructor & Destructor Documentation
QualifierAlignmentFixer()
clang::format::QualifierAlignmentFixer::QualifierAlignmentFixer (const Environment & Env, const FormatStyle & Style, StringRef & Code, ArrayRef< tooling::Range > Ranges, unsigned FirstStartColumn, unsigned NextStartColumn, unsigned LastStartColumn, StringRef FileName)
Definition at line 28 of file QualifierAlignmentFixer.cpp.
Member Function Documentation
analyze()
std::pair< tooling::Replacements, unsigned > clang::format::QualifierAlignmentFixer::analyze (TokenAnnotator & Annotator, SmallVectorImpl< AnnotatedLine * > & AnnotatedLines, FormatTokenLexer & Tokens) override virtual
Implements clang::format::TokenAnalyzer.
Definition at line 62 of file QualifierAlignmentFixer.cpp.
References clang::tooling::Replacements::add(), clang::tooling::applyAllReplacements(), clang::tooling::calculateRangesAfterReplacements(), clang::format::TokenAnalyzer::Env, clang::format::Environment::make(), clang::tooling::Replacements::merge(), and clang::threadSafety::sx::toString().
PrepareLeftRightOrdering()
void clang::format::QualifierAlignmentFixer::PrepareLeftRightOrdering (const std::vector< std::string > & Order, std::vector< std::string > & LeftOrder, std::vector< std::string > & RightOrder, std::vector< tok::TokenKind > & Qualifiers) static
Definition at line 467 of file QualifierAlignmentFixer.cpp.
References clang::format::LeftRightQualifierAlignmentFixer::getTokenFromQualifier(), and s.
The documentation for this class was generated from the following files:
lib/Format/QualifierAlignmentFixer.h
lib/Format/QualifierAlignmentFixer.cpp