clang: lib/Analysis/FlowSensitive/DataflowAnalysisContext.cpp File Reference
DataflowAnalysisContext.cpp File Reference
#include "clang/Analysis/FlowSensitive/DataflowAnalysisContext.h"
#include "clang/AST/ExprCXX.h"
#include "clang/Analysis/FlowSensitive/DebugSupport.h"
#include "clang/Analysis/FlowSensitive/Value.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/Support/Debug.h"
#include <cassert>
#include <memory>
#include <utility>
Namespaces
clang
clang::dataflow
Dataflow Directional Tag Classes.
Functions
static std::pair< BoolValue *, BoolValue * > clang::dataflow::makeCanonicalBoolValuePair (BoolValue &LHS, BoolValue &RHS)
static void getFieldsFromClassHierarchy (QualType Type, llvm::DenseSet< const FieldDecl * > &Fields)
Function Documentation
getFieldsFromClassHierarchy()
static void getFieldsFromClassHierarchy (QualType Type, llvm::DenseSet< const FieldDecl * > & Fields) static
Definition at line 403 of file DataflowAnalysisContext.cpp.
References clang::RecordDecl::fields(), clang::Type::getAsCXXRecordDecl(), clang::Type::getAsRecordDecl(), clang::Type::isDependentType(), clang::Type::isIncompleteType(), and clang::Type::isRecordType().
Referenced by clang::dataflow::getObjectFields().