clang: lib/AST/DeclPrinter.cpp File Reference
DeclPrinter.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/Attr.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclObjC.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclVisitor.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/PrettyPrinter.h"
#include "clang/Basic/Module.h"
#include "llvm/Support/raw_ostream.h"
#include "clang/Basic/AttrList.inc"
Macros
#define ATTR(X)
#define PRAGMA_SPELLING_ATTR(X) case attr::X:
#define ATTR(X)
#define PRAGMA_SPELLING_ATTR(X) case attr::X:
Functions
static QualType GetBaseType (QualType T)
static QualType getDeclType (Decl *D)
static void printExplicitSpecifier (ExplicitSpecifier ES, llvm::raw_ostream &Out, PrintingPolicy &Policy, unsigned Indentation, const ASTContext &Context)
Macro Definition Documentation
ATTR [1/2]
#define ATTR (X)
ATTR [2/2]
#define ATTR (X)
PRAGMA_SPELLING_ATTR [1/2]
#define PRAGMA_SPELLING_ATTR (X) case attr::X:
PRAGMA_SPELLING_ATTR [2/2]
#define PRAGMA_SPELLING_ATTR (X) case attr::X:
Function Documentation
GetBaseType()
static QualType GetBaseType (QualType T) static
Definition at line 150 of file DeclPrinter.cpp.
References clang::Type::getAs(), clang::Type::getPointeeType(), and clang::Type::isSpecifierType().
getDeclType()
static QualType getDeclType (Decl * D) static
Definition at line 180 of file DeclPrinter.cpp.
printExplicitSpecifier()
static void printExplicitSpecifier (ExplicitSpecifier ES, llvm::raw_ostream & Out, PrintingPolicy & Policy, unsigned Indentation, const ASTContext & Context) static
Definition at line 577 of file DeclPrinter.cpp.