clang: lib/Driver/ToolChains/Arch/AArch64.cpp File Reference
AArch64.cpp File Reference
#include "AArch64.h"
#include "../CommonArgs.h"
#include "clang/Driver/Driver.h"
#include "clang/Driver/DriverDiagnostic.h"
#include "clang/Driver/Options.h"
#include "llvm/Option/ArgList.h"
#include "llvm/TargetParser/AArch64TargetParser.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/TargetParser/TargetParser.h"
Functions
static bool isCPUDeterminedByTriple (const llvm::Triple &Triple)
static bool DecodeAArch64Features (const Driver &D, StringRef text, std::vector< StringRef > &Features, const llvm::AArch64::ArchInfo &ArchInfo)
static bool DecodeAArch64Mcpu (const Driver &D, StringRef Mcpu, StringRef &CPU, std::vector< StringRef > &Features)
static bool getAArch64ArchFeaturesFromMarch (const Driver &D, StringRef March, const ArgList &Args, std::vector< StringRef > &Features)
static bool getAArch64ArchFeaturesFromMcpu (const Driver &D, StringRef Mcpu, const ArgList &Args, std::vector< StringRef > &Features)
static bool getAArch64MicroArchFeaturesFromMtune (const Driver &D, StringRef Mtune, const ArgList &Args, std::vector< StringRef > &Features)
static bool getAArch64MicroArchFeaturesFromMcpu (const Driver &D, StringRef Mcpu, const ArgList &Args, std::vector< StringRef > &Features)
Function Documentation
DecodeAArch64Features()
static bool DecodeAArch64Features (const Driver & D, StringRef text, std::vector< StringRef > & Features, const llvm::AArch64::ArchInfo & ArchInfo) static
Definition at line 71 of file AArch64.cpp.
References clang::driver::Driver::Diag(), clang::driver::tools::Split, and clang::comments::tok::text.
Referenced by DecodeAArch64Mcpu(), and getAArch64ArchFeaturesFromMarch().
DecodeAArch64Mcpu()
static bool DecodeAArch64Mcpu (const Driver & D, StringRef Mcpu, StringRef & CPU, std::vector< StringRef > & Features) static
Definition at line 123 of file AArch64.cpp.
References DecodeAArch64Features(), and clang::driver::tools::Split.
Referenced by getAArch64ArchFeaturesFromMcpu(), getAArch64MicroArchFeaturesFromMcpu(), and getAArch64MicroArchFeaturesFromMtune().
getAArch64ArchFeaturesFromMarch()
static bool getAArch64ArchFeaturesFromMarch (const Driver & D, StringRef March, const ArgList & Args, std::vector< StringRef > & Features) static
Definition at line 156 of file AArch64.cpp.
References DecodeAArch64Features(), clang::driver::tools::Split, and string().
getAArch64ArchFeaturesFromMcpu()
static bool getAArch64ArchFeaturesFromMcpu (const Driver & D, StringRef Mcpu, const ArgList & Args, std::vector< StringRef > & Features) static
Definition at line 188 of file AArch64.cpp.
References DecodeAArch64Mcpu(), and string().
getAArch64MicroArchFeaturesFromMcpu()
static bool getAArch64MicroArchFeaturesFromMcpu (const Driver & D, StringRef Mcpu, const ArgList & Args, std::vector< StringRef > & Features) static
Definition at line 222 of file AArch64.cpp.
References DecodeAArch64Mcpu(), getAArch64MicroArchFeaturesFromMtune(), and string().
getAArch64MicroArchFeaturesFromMtune()
static bool getAArch64MicroArchFeaturesFromMtune (const Driver & D, StringRef Mtune, const ArgList & Args, std::vector< StringRef > & Features) static
Definition at line 200 of file AArch64.cpp.
References DecodeAArch64Mcpu(), and string().
Referenced by getAArch64MicroArchFeaturesFromMcpu().
isCPUDeterminedByTriple()
static bool isCPUDeterminedByTriple (const llvm::Triple & Triple) static
Returns
true if the given triple can determine the default CPU type even if -arch is not specified.
Definition at line 26 of file AArch64.cpp.