clang: lib/Driver/ToolChains/Flang.cpp File Reference
Flang.cpp File Reference
#include "Flang.h"
#include "CommonArgs.h"
#include "clang/Driver/Options.h"
#include <cassert>
Functions
static void addDashXForInput (const ArgList &Args, const InputInfo &Input, ArgStringList &CmdArgs)
Add -x lang to CmdArgs for Input.
static void addFloatingPointOptions (const Driver &D, const ArgList &Args, ArgStringList &CmdArgs)
Function Documentation
addDashXForInput()
static void addDashXForInput (const ArgList & Args, const InputInfo & Input, ArgStringList & CmdArgs) static
Add -x lang to CmdArgs for Input.
Definition at line 23 of file Flang.cpp.
References clang::driver::InputInfo::getType(), and clang::driver::types::getTypeName().
Referenced by clang::driver::tools::Flang::ConstructJob().
addFloatingPointOptions()
static void addFloatingPointOptions (const Driver & D, const ArgList & Args, ArgStringList & CmdArgs) static
Definition at line 116 of file Flang.cpp.
References clang::driver::Driver::Diag().
Referenced by clang::driver::tools::Flang::ConstructJob().