clang: lib/Sema/SemaTemplateDeduction.cpp File Reference
SemaTemplateDeduction.cpp File Reference
#include "clang/Sema/TemplateDeduction.h"
#include "TreeTransform.h"
#include "TypeLocBuilder.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/ASTLambda.h"
#include "clang/AST/Decl.h"
#include "clang/AST/DeclAccessPair.h"
#include "clang/AST/DeclBase.h"
#include "clang/AST/DeclCXX.h"
#include "clang/AST/DeclTemplate.h"
#include "clang/AST/DeclarationName.h"
#include "clang/AST/Expr.h"
#include "clang/AST/ExprCXX.h"
#include "clang/AST/NestedNameSpecifier.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/AST/TemplateBase.h"
#include "clang/AST/TemplateName.h"
#include "clang/AST/Type.h"
#include "clang/AST/TypeLoc.h"
#include "clang/AST/UnresolvedSet.h"
#include "clang/Basic/AddressSpaces.h"
#include "clang/Basic/ExceptionSpecificationType.h"
#include "clang/Basic/LLVM.h"
#include "clang/Basic/LangOptions.h"
#include "clang/Basic/PartialDiagnostic.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/Specifiers.h"
#include "clang/Sema/Ownership.h"
#include "clang/Sema/Sema.h"
#include "clang/Sema/Template.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include <algorithm>
#include <cassert>
#include <optional>
#include <tuple>
#include <type_traits>
#include <utility>
#include "clang/AST/TypeNodes.inc"
Classes
struct clang::DeducedPack
A pack that we're currently deducing.
struct IsPartialSpecialization< T >
struct IsPartialSpecialization< ClassTemplatePartialSpecializationDecl >
struct IsPartialSpecialization< VarTemplatePartialSpecializationDecl >
Namespaces
clang
Macros
#define NON_CANONICAL_TYPE(Class, Base) case Type::Class: llvm_unreachable("deducing non-canonical type: " #Class);
#define TYPE(Class, Base)
#define TYPE(Class, Base)
#define ABSTRACT_TYPE(Class, Base)
#define DEPENDENT_TYPE(Class, Base)
#define NON_CANONICAL_TYPE(Class, Base) case Type::Class:
Enumerations
enum clang::TemplateDeductionFlags {
clang::TDF_None = 0, clang::TDF_ParamWithReferenceType = 0x1, clang::TDF_IgnoreQualifiers = 0x02, clang::TDF_DerivedClass = 0x04,
clang::TDF_SkipNonDependent = 0x08, clang::TDF_TopLevelParameterTypeList = 0x10, clang::TDF_AllowCompatibleFunctionType = 0x20, clang::TDF_ArgWithReferenceType = 0x40
}
Various flags that control template argument deduction.
Functions
static bool hasSameExtendedValue (llvm::APSInt X, llvm::APSInt Y)
Compare two APSInts, extending and switching the sign as necessary to compare their values regardless of underlying type.
static Sema::TemplateDeductionResult DeduceTemplateArgumentsByTypeMatch (Sema &S, TemplateParameterList *TemplateParams, QualType P, QualType A, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, unsigned TDF, bool PartialOrdering, bool DeducedFromArrayBound)
Deduce the template arguments by comparing the parameter type and the argument type (C++ [temp.deduct.type]).
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, ArrayRef< TemplateArgument > Ps, ArrayRef< TemplateArgument > As, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, bool NumberOfArgumentsMustMatch)
static void MarkUsedTemplateParameters (ASTContext &Ctx, const TemplateArgument &TemplateArg, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by this template argument.
static void MarkUsedTemplateParameters (ASTContext &Ctx, QualType T, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by the given type.
static const NonTypeTemplateParmDecl * getDeducedParameterFromExpr (const Expr *E, unsigned Depth)
If the given expression is of a form that permits the deduction of a non-type template parameter, return the declaration of that non-type template parameter.
static const NonTypeTemplateParmDecl * getDeducedParameterFromExpr (TemplateDeductionInfo &Info, Expr *E)
static bool isSameDeclaration (Decl *X, Decl *Y)
Determine whether two declaration pointers refer to the same declaration.
static DeducedTemplateArgument checkDeducedTemplateArguments (ASTContext &Context, const DeducedTemplateArgument &X, const DeducedTemplateArgument &Y)
Verify that the given, deduced template arguments are compatible.
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, const DeducedTemplateArgument &NewDeduced, QualType ValueType, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter as the given deduced template argument.
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, const llvm::APSInt &Value, QualType ValueType, bool DeducedFromArrayBound, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter from the given integral constant.
static Sema::TemplateDeductionResult DeduceNullPtrTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, QualType NullPtrType, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter from the given null pointer template argument type.
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, Expr *Value, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter from the given type- or value-dependent expression.
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema &S, TemplateParameterList *TemplateParams, const NonTypeTemplateParmDecl *NTTP, ValueDecl *D, QualType T, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the value of the given non-type template parameter from the given declaration.
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, TemplateName Param, TemplateName Arg, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
static Sema::TemplateDeductionResult DeduceTemplateSpecArguments (Sema &S, TemplateParameterList *TemplateParams, const QualType P, QualType A, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Deduce the template arguments by comparing the template parameter type (which is a template-id) with the template argument type.
static bool IsPossiblyOpaquelyQualifiedTypeInternal (const Type *T)
static bool IsPossiblyOpaquelyQualifiedType (QualType T)
Determines whether the given type is an opaque type that might be more qualified when instantiated.
static TemplateParameter makeTemplateParameter (Decl *D)
Helper function to build a TemplateParameter when we don't know its type statically.
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, const QualType *Params, unsigned NumParams, const QualType *Args, unsigned NumArgs, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, unsigned TDF, bool PartialOrdering=false)
Deduce the template arguments by comparing the list of parameter types to the list of argument types, as in the parameter-type-lists of function types (C++ [temp.deduct.type]p10).
static bool hasInconsistentOrSupersetQualifiersOf (QualType ParamType, QualType ArgType)
Determine whether the parameter has qualifiers that the argument lacks.
static unsigned getFirstInnerIndex (FunctionTemplateDecl *FTD)
Get the index of the first template parameter that was originally from the innermost template-parameter-list.
static bool isForwardingReference (QualType Param, unsigned FirstInnerIndex)
Determine whether a type denotes a forwarding reference.
static CXXRecordDecl * getCanonicalRD (QualType T)
static Sema::TemplateDeductionResult DeduceTemplateBases (Sema &S, const CXXRecordDecl *RD, TemplateParameterList *TemplateParams, QualType P, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
Attempt to deduce the template arguments by checking the base types according to (C++20 [temp.deduct.call] p4b3.
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, const TemplateArgument &P, TemplateArgument A, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
static bool hasTemplateArgumentForDeduction (ArrayRef< TemplateArgument > &Args, unsigned &ArgIdx)
Determine whether there is a template argument to be used for deduction.
static bool hasPackExpansionBeforeEnd (ArrayRef< TemplateArgument > Args)
Determine whether the given set of template arguments has a pack expansion that is not the last template argument.
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema &S, TemplateParameterList *TemplateParams, const TemplateArgumentList &ParamList, const TemplateArgumentList &ArgList, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced)
static bool isSameTemplateArg (ASTContext &Context, TemplateArgument X, const TemplateArgument &Y, bool PartialOrdering, bool PackExpansionMatchesPack=false)
Determine whether two template arguments are the same.
static bool ConvertDeducedTemplateArgument (Sema &S, NamedDecl *Param, DeducedTemplateArgument Arg, NamedDecl *Template, TemplateDeductionInfo &Info, bool IsDeduced, SmallVectorImpl< TemplateArgument > &SugaredOutput, SmallVectorImpl< TemplateArgument > &CanonicalOutput)
Convert the given deduced template argument and add it to the set of fully-converted template arguments.
template<typename TemplateDeclT >
static Sema::TemplateDeductionResult ConvertDeducedTemplateArguments (Sema &S, TemplateDeclT *Template, bool IsDeduced, SmallVectorImpl< DeducedTemplateArgument > &Deduced, TemplateDeductionInfo &Info, SmallVectorImpl< TemplateArgument > &SugaredBuilder, SmallVectorImpl< TemplateArgument > &CanonicalBuilder, LocalInstantiationScope *CurrentInstantiationScope=nullptr, unsigned NumAlreadyConverted=0, bool PartialOverloading=false)
static DeclContext * getAsDeclContextOrEnclosing (Decl *D)
template<typename TemplateDeclT >
static bool DeducedArgsNeedReplacement (TemplateDeclT *Template)
template<>
bool DeducedArgsNeedReplacement< VarTemplatePartialSpecializationDecl > (VarTemplatePartialSpecializationDecl *Spec)
template<>
bool DeducedArgsNeedReplacement< ClassTemplatePartialSpecializationDecl > (ClassTemplatePartialSpecializationDecl *Spec)
template<typename TemplateDeclT >
static Sema::TemplateDeductionResult CheckDeducedArgumentConstraints (Sema &S, TemplateDeclT *Template, ArrayRef< TemplateArgument > SugaredDeducedArgs, ArrayRef< TemplateArgument > CanonicalDeducedArgs, TemplateDeductionInfo &Info)
template<typename T >
static std::enable_if_t< IsPartialSpecialization< T >::value, Sema::TemplateDeductionResult > FinishTemplateArgumentDeduction (Sema &S, T *Partial, bool IsPartialOrdering, const TemplateArgumentList &TemplateArgs, SmallVectorImpl< DeducedTemplateArgument > &Deduced, TemplateDeductionInfo &Info)
Complete template argument deduction for a partial specialization.
static Sema::TemplateDeductionResult FinishTemplateArgumentDeduction (Sema &S, TemplateDecl *Template, bool PartialOrdering, const TemplateArgumentList &TemplateArgs, SmallVectorImpl< DeducedTemplateArgument > &Deduced, TemplateDeductionInfo &Info)
Complete template argument deduction for a class or variable template, when partial ordering against a partial specialization.
static bool isSimpleTemplateIdType (QualType T)
Determine whether the given type T is a simple-template-id type.
static Sema::TemplateDeductionResult CheckOriginalCallArgDeduction (Sema &S, TemplateDeductionInfo &Info, Sema::OriginalCallArg OriginalArg, QualType DeducedA)
Check whether the deduced argument type for a call to a function template matches the actual argument type per C++ [temp.deduct.call]p4.
static unsigned getPackIndexForParam (Sema &S, FunctionTemplateDecl *FunctionTemplate, const MultiLevelTemplateArgumentList &Args, unsigned ParamIdx)
Find the pack index for a particular parameter index in an instantiation of a function template with specific arguments.
static QualType GetTypeOfFunction (Sema &S, const OverloadExpr::FindResult &R, FunctionDecl *Fn)
Gets the type of a function for template-argument-deducton purposes when it's considered as part of an overload set.
static QualType ResolveOverloadForDeduction (Sema &S, TemplateParameterList *TemplateParams, Expr *Arg, QualType ParamType, bool ParamWasReference)
Apply the deduction rules for overload sets.
static bool AdjustFunctionParmAndArgTypesForDeduction (Sema &S, TemplateParameterList *TemplateParams, unsigned FirstInnerIndex, QualType &ParamType, QualType &ArgType, Expr *Arg, unsigned &TDF)
Perform the adjustments to the parameter and argument types described in C++ [temp.deduct.call].
static bool hasDeducibleTemplateParameters (Sema &S, FunctionTemplateDecl *FunctionTemplate, QualType T)
static Sema::TemplateDeductionResult DeduceTemplateArgumentsFromCallArgument (Sema &S, TemplateParameterList *TemplateParams, unsigned FirstInnerIndex, QualType ParamType, Expr *Arg, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, SmallVectorImpl< Sema::OriginalCallArg > &OriginalCallArgs, bool DecomposedParam, unsigned ArgIdx, unsigned TDF)
Perform template argument deduction per [temp.deduct.call] for a single parameter / argument pair.
static Sema::TemplateDeductionResult DeduceFromInitializerList (Sema &S, TemplateParameterList *TemplateParams, QualType AdjustedParamType, InitListExpr *ILE, TemplateDeductionInfo &Info, SmallVectorImpl< DeducedTemplateArgument > &Deduced, SmallVectorImpl< Sema::OriginalCallArg > &OriginalCallArgs, unsigned ArgIdx, unsigned TDF)
Attempt template argument deduction from an initializer list deemed to be an argument in a function call.
static bool CheckDeducedPlaceholderConstraints (Sema &S, const AutoType &Type, AutoTypeLoc TypeLoc, QualType Deduced)
static void AddImplicitObjectParameterType (ASTContext &Context, CXXMethodDecl *Method, SmallVectorImpl< QualType > &ArgTypes)
If this is a non-static member function,.
static bool isAtLeastAsSpecializedAs (Sema &S, SourceLocation Loc, FunctionTemplateDecl *FT1, FunctionTemplateDecl *FT2, TemplatePartialOrderingContext TPOC, unsigned NumCallArguments1, bool Reversed)
Determine whether the function template FT1 is at least as specialized as FT2.
static bool isSameTemplate (TemplateDecl *T1, TemplateDecl *T2)
Determine if the two templates are equivalent.
template<typename TemplateLikeDecl >
static bool isAtLeastAsSpecializedAs (Sema &S, QualType T1, QualType T2, TemplateLikeDecl *P2, TemplateDeductionInfo &Info)
Determine whether one partial specialization, P1, is at least as specialized than another, P2.
template<typename TemplateLikeDecl , typename PrimaryDel >
static TemplateLikeDecl * getMoreSpecialized (Sema &S, QualType T1, QualType T2, TemplateLikeDecl *P1, PrimaryDel *P2, TemplateDeductionInfo &Info)
Returns the more specialized template specialization between T1/P1 and T2/P2.
static void MarkUsedTemplateParameters (ASTContext &Ctx, const Expr *E, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by the given expression.
static void MarkUsedTemplateParameters (ASTContext &Ctx, NestedNameSpecifier *NNS, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by the given nested name specifier.
static void MarkUsedTemplateParameters (ASTContext &Ctx, TemplateName Name, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector &Used)
Mark the template parameters that are used by the given template name.
Macro Definition Documentation
ABSTRACT_TYPE
#define ABSTRACT_TYPE (Class, Base)
DEPENDENT_TYPE
#define DEPENDENT_TYPE (Class, Base)
NON_CANONICAL_TYPE [1/2]
#define NON_CANONICAL_TYPE (Class, Base) case Type::Class: llvm_unreachable("deducing non-canonical type: " #Class);
NON_CANONICAL_TYPE [2/2]
#define NON_CANONICAL_TYPE (Class, Base) case Type::Class:
TYPE [1/2]
#define TYPE (Class, Base)
TYPE [2/2]
#define TYPE (Class, Base)
Function Documentation
AddImplicitObjectParameterType()
static void AddImplicitObjectParameterType (ASTContext & Context, CXXMethodDecl * Method, SmallVectorImpl< QualType > & ArgTypes) static
If this is a non-static member function,.
Definition at line 4990 of file SemaTemplateDeduction.cpp.
References clang::ASTContext::getLValueReferenceType(), clang::CXXMethodDecl::getMethodQualifiers(), clang::CXXMethodDecl::getParent(), clang::ASTContext::getQualifiedType(), clang::CXXMethodDecl::getRefQualifier(), clang::ASTContext::getRValueReferenceType(), clang::ASTContext::getTypeDeclType(), and clang::RQ_RValue.
AdjustFunctionParmAndArgTypesForDeduction()
static bool AdjustFunctionParmAndArgTypesForDeduction (Sema & S, TemplateParameterList * TemplateParams, unsigned FirstInnerIndex, QualType & ParamType, QualType & ArgType, Expr * Arg, unsigned & TDF) static
Perform the adjustments to the parameter and argument types described in C++ [temp.deduct.call].
Returns
true if the caller should not attempt to perform any template argument deduction based on this P/A pair because the argument is an overloaded function set that could not be resolved.
Definition at line 3838 of file SemaTemplateDeduction.cpp.
CheckDeducedArgumentConstraints()
template<typename TemplateDeclT > static Sema::TemplateDeductionResult CheckDeducedArgumentConstraints (Sema & S, TemplateDeclT * Template, ArrayRef< TemplateArgument > SugaredDeducedArgs, ArrayRef< TemplateArgument > CanonicalDeducedArgs, TemplateDeductionInfo & Info) static
Definition at line 2863 of file SemaTemplateDeduction.cpp.
CheckDeducedPlaceholderConstraints()
static bool CheckDeducedPlaceholderConstraints (Sema & S, const AutoType & Type, AutoTypeLoc TypeLoc, QualType Deduced) static
Definition at line 4640 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::DeduceAutoType().
checkDeducedTemplateArguments()
static DeducedTemplateArgument checkDeducedTemplateArguments (ASTContext & Context, const DeducedTemplateArgument & X, const DeducedTemplateArgument & Y) static
Verify that the given, deduced template arguments are compatible.
Returns
The deduced template argument, or a NULL template argument if the deduced template arguments were incompatible.
Definition at line 212 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgument::CreatePackCopy(), clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getAsTemplate(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::ASTContext::getCommonSugaredType(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getNonTypeTemplateArgumentType(), clang::TemplateArgument::getNullPtrType(), clang::Expr::getType(), hasSameExtendedValue(), clang::ASTContext::hasSameTemplateName(), clang::ASTContext::hasSameType(), clang::TemplateArgument::Integral, clang::TemplateArgument::isNull(), clang::QualType::isNull(), isSameDeclaration(), clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_begin(), clang::TemplateArgument::pack_size(), clang::Stmt::Profile(), clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, clang::TemplateArgument::Type, clang::DeducedTemplateArgument::wasDeducedFromArrayBound(), and clang::tooling::X().
CheckOriginalCallArgDeduction()
static Sema::TemplateDeductionResult CheckOriginalCallArgDeduction (Sema & S, TemplateDeductionInfo & Info, Sema::OriginalCallArg OriginalArg, QualType DeducedA) static
Check whether the deduced argument type for a call to a function template matches the actual argument type per C++ [temp.deduct.call]p4.
Definition at line 3389 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::DeduceAutoType(), and clang::Sema::FinishTemplateArgumentDeduction().
ConvertDeducedTemplateArgument()
static bool ConvertDeducedTemplateArgument (Sema & S, NamedDecl * Param, DeducedTemplateArgument Arg, NamedDecl * Template, TemplateDeductionInfo & Info, bool IsDeduced, SmallVectorImpl< TemplateArgument > & SugaredOutput, SmallVectorImpl< TemplateArgument > & CanonicalOutput) static
Convert the given deduced template argument and add it to the set of fully-converted template arguments.
Definition at line 2614 of file SemaTemplateDeduction.cpp.
ConvertDeducedTemplateArguments()
template<typename TemplateDeclT > static Sema::TemplateDeductionResult ConvertDeducedTemplateArguments (Sema & S, TemplateDeclT * Template, bool IsDeduced, SmallVectorImpl< DeducedTemplateArgument > & Deduced, TemplateDeductionInfo & Info, SmallVectorImpl< TemplateArgument > & SugaredBuilder, SmallVectorImpl< TemplateArgument > & CanonicalBuilder, LocalInstantiationScope * CurrentInstantiationScope = nullptr, unsigned NumAlreadyConverted = 0, bool PartialOverloading = false) static
Definition at line 2709 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::FinishTemplateArgumentDeduction().
DeducedArgsNeedReplacement()
template<typename TemplateDeclT > static bool DeducedArgsNeedReplacement (TemplateDeclT * Template) static
Definition at line 2847 of file SemaTemplateDeduction.cpp.
DeducedArgsNeedReplacement< ClassTemplatePartialSpecializationDecl >()
template<> bool DeducedArgsNeedReplacement< ClassTemplatePartialSpecializationDecl > (ClassTemplatePartialSpecializationDecl * Spec)
Definition at line 2856 of file SemaTemplateDeduction.cpp.
References clang::ClassTemplateSpecializationDecl::isClassScopeExplicitSpecialization().
DeducedArgsNeedReplacement< VarTemplatePartialSpecializationDecl >()
template<> bool DeducedArgsNeedReplacement< VarTemplatePartialSpecializationDecl > (VarTemplatePartialSpecializationDecl * Spec)
Definition at line 2851 of file SemaTemplateDeduction.cpp.
References clang::VarTemplateSpecializationDecl::isClassScopeExplicitSpecialization().
DeduceFromInitializerList()
static Sema::TemplateDeductionResult DeduceFromInitializerList (Sema & S, TemplateParameterList * TemplateParams, QualType AdjustedParamType, InitListExpr * ILE, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, SmallVectorImpl< Sema::OriginalCallArg > & OriginalCallArgs, unsigned ArgIdx, unsigned TDF) static
Attempt template argument deduction from an initializer list deemed to be an argument in a function call.
Definition at line 3941 of file SemaTemplateDeduction.cpp.
DeduceNonTypeTemplateArgument() [1/4]
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, const DeducedTemplateArgument & NewDeduced, QualType ValueType, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter as the given deduced template argument.
All non-type template parameter deduction is funneled through here.
Definition at line 380 of file SemaTemplateDeduction.cpp.
DeduceNonTypeTemplateArgument() [2/4]
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, const llvm::APSInt & Value, QualType ValueType, bool DeducedFromArrayBound, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter from the given integral constant.
Definition at line 433 of file SemaTemplateDeduction.cpp.
DeduceNonTypeTemplateArgument() [3/4]
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, Expr * Value, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter from the given type- or value-dependent expression.
Returns
true if deduction succeeded, false otherwise.
Definition at line 468 of file SemaTemplateDeduction.cpp.
DeduceNonTypeTemplateArgument() [4/4]
static Sema::TemplateDeductionResult DeduceNonTypeTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, ValueDecl * D, QualType T, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter from the given declaration.
Returns
true if deduction succeeded, false otherwise.
Definition at line 481 of file SemaTemplateDeduction.cpp.
DeduceNullPtrTemplateArgument()
static Sema::TemplateDeductionResult DeduceNullPtrTemplateArgument (Sema & S, TemplateParameterList * TemplateParams, const NonTypeTemplateParmDecl * NTTP, QualType NullPtrType, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the value of the given non-type template parameter from the given null pointer template argument type.
Definition at line 447 of file SemaTemplateDeduction.cpp.
DeduceTemplateArguments() [1/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, ArrayRef< TemplateArgument > Ps, ArrayRef< TemplateArgument > As, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, bool NumberOfArgumentsMustMatch) static
Definition at line 2362 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::CheckFunctionTemplateSpecialization(), clang::Sema::CheckVarTemplateId(), and clang::Sema::DeduceTemplateArguments().
DeduceTemplateArguments() [2/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, const QualType * Params, unsigned NumParams, const QualType * Args, unsigned NumArgs, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, unsigned TDF, bool PartialOrdering = false) static
Deduce the template arguments by comparing the list of parameter types to the list of argument types, as in the parameter-type-lists of function types (C++ [temp.deduct.type]p10).
Parameters
S The semantic analysis object within which we are deducing
TemplateParams The template parameters that we are deducing
Params The list of parameter types
NumParams The number of types in Params
Args The list of argument types
NumArgs The number of types in Args
Info information about the template argument deduction itself
Deduced the deduced template arguments
TDF bitwise OR of the TemplateDeductionFlags bits that describe how template argument deduction is performed.
PartialOrdering If true, we are performing template argument deduction for during partial ordering for a call (C++0x [temp.deduct.partial]).
Returns
the result of template argument deduction so far. Note that a "success" result means that template argument deduction has not yet failed, but it may still fail, later, for other reasons.
Definition at line 1024 of file SemaTemplateDeduction.cpp.
DeduceTemplateArguments() [3/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, const TemplateArgument & P, TemplateArgument A, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Definition at line 2226 of file SemaTemplateDeduction.cpp.
DeduceTemplateArguments() [4/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, const TemplateArgumentList & ParamList, const TemplateArgumentList & ArgList, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Definition at line 2443 of file SemaTemplateDeduction.cpp.
DeduceTemplateArguments() [5/5]
static Sema::TemplateDeductionResult DeduceTemplateArguments (Sema & S, TemplateParameterList * TemplateParams, TemplateName Param, TemplateName Arg, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Definition at line 493 of file SemaTemplateDeduction.cpp.
DeduceTemplateArgumentsByTypeMatch()
static Sema::TemplateDeductionResult DeduceTemplateArgumentsByTypeMatch (Sema & S, TemplateParameterList * TemplateParams, QualType P, QualType A, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, unsigned TDF, bool PartialOrdering, bool DeducedFromArrayBound) static
Deduce the template arguments by comparing the parameter type and the argument type (C++ [temp.deduct.type]).
Parameters
S the semantic analysis object within which we are deducing
TemplateParams the template parameters that we are deducing
P the parameter type
A the argument type
Info information about the template argument deduction itself
Deduced the deduced template arguments
TDF bitwise OR of the TemplateDeductionFlags bits that describe how template argument deduction is performed.
PartialOrdering Whether we're performing template argument deduction in the context of partial ordering (C++0x [temp.deduct.partial]).
Returns
the result of template argument deduction so far. Note that a "success" result means that template argument deduction has not yet failed, but it may still fail, later, for other reasons.
Definition at line 1367 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::DeduceTemplateArguments().
DeduceTemplateArgumentsFromCallArgument()
static Sema::TemplateDeductionResult DeduceTemplateArgumentsFromCallArgument (Sema & S, TemplateParameterList * TemplateParams, unsigned FirstInnerIndex, QualType ParamType, Expr * Arg, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced, SmallVectorImpl< Sema::OriginalCallArg > & OriginalCallArgs, bool DecomposedParam, unsigned ArgIdx, unsigned TDF) static
Perform template argument deduction per [temp.deduct.call] for a single parameter / argument pair.
Definition at line 4008 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::DeduceAutoType(), and clang::Sema::DeduceTemplateArguments().
DeduceTemplateBases()
static Sema::TemplateDeductionResult DeduceTemplateBases (Sema & S, const CXXRecordDecl * RD, TemplateParameterList * TemplateParams, QualType P, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Attempt to deduce the template arguments by checking the base types according to (C++20 [temp.deduct.call] p4b3.
Parameters
S the semantic analysis object within which we are deducing.
RD the top level record object we are deducing against.
TemplateParams the template parameters that we are deducing.
P the template specialization parameter type.
Info information about the template argument deduction itself.
Deduced the deduced template arguments.
Returns
the result of template argument deduction with the bases. "invalid" means no matches, "success" found a single item, and the "MiscellaneousDeductionFailure" result happens when the match is ambiguous.
Definition at line 1248 of file SemaTemplateDeduction.cpp.
DeduceTemplateSpecArguments()
static Sema::TemplateDeductionResult DeduceTemplateSpecArguments (Sema & S, TemplateParameterList * TemplateParams, const QualType P, QualType A, TemplateDeductionInfo & Info, SmallVectorImpl< DeducedTemplateArgument > & Deduced) static
Deduce the template arguments by comparing the template parameter type (which is a template-id) with the template argument type.
Parameters
S the Sema
TemplateParams the template parameters that we are deducing
P the parameter type
A the argument type
Info information about the template argument deduction itself
Deduced the deduced template arguments
Returns
the result of template argument deduction so far. Note that a "success" result means that template argument deduction has not yet failed, but it may still fail, later, for other reasons.
Definition at line 556 of file SemaTemplateDeduction.cpp.
FinishTemplateArgumentDeduction() [1/2]
template<typename T > static std::enable_if_t<IsPartialSpecialization<T>::value, Sema::TemplateDeductionResult> FinishTemplateArgumentDeduction (Sema & S, T * Partial, bool IsPartialOrdering, const TemplateArgumentList & TemplateArgs, SmallVectorImpl< DeducedTemplateArgument > & Deduced, TemplateDeductionInfo & Info) static
Complete template argument deduction for a partial specialization.
Definition at line 2903 of file SemaTemplateDeduction.cpp.
FinishTemplateArgumentDeduction() [2/2]
static Sema::TemplateDeductionResult FinishTemplateArgumentDeduction (Sema & S, TemplateDecl * Template, bool PartialOrdering, const TemplateArgumentList & TemplateArgs, SmallVectorImpl< DeducedTemplateArgument > & Deduced, TemplateDeductionInfo & Info) static
Complete template argument deduction for a class or variable template, when partial ordering against a partial specialization.
Definition at line 2996 of file SemaTemplateDeduction.cpp.
getAsDeclContextOrEnclosing()
static DeclContext* getAsDeclContextOrEnclosing (Decl * D) static
Definition at line 2829 of file SemaTemplateDeduction.cpp.
References clang::Decl::getDeclContext().
getCanonicalRD()
static CXXRecordDecl* getCanonicalRD (QualType T) static
Definition at line 1224 of file SemaTemplateDeduction.cpp.
References clang::Type::castAs(), clang::TagDecl::getCanonicalDecl(), and clang::RecordType::getDecl().
getDeducedParameterFromExpr() [1/2]
static const NonTypeTemplateParmDecl* getDeducedParameterFromExpr (const Expr * E, unsigned Depth) static
If the given expression is of a form that permits the deduction of a non-type template parameter, return the declaration of that non-type template parameter.
Definition at line 162 of file SemaTemplateDeduction.cpp.
References Depth.
Referenced by getDeducedParameterFromExpr(), and MarkUsedTemplateParameters().
getDeducedParameterFromExpr() [2/2]
static const NonTypeTemplateParmDecl* getDeducedParameterFromExpr (TemplateDeductionInfo & Info, Expr * E) static
Definition at line 192 of file SemaTemplateDeduction.cpp.
References clang::sema::TemplateDeductionInfo::getDeducedDepth(), and getDeducedParameterFromExpr().
getFirstInnerIndex()
static unsigned getFirstInnerIndex (FunctionTemplateDecl * FTD) static
Get the index of the first template parameter that was originally from the innermost template-parameter-list.
This is 0 except when we concatenate the template parameter lists of a class template and a constructor template when forming an implicit deduction guide.
Definition at line 1202 of file SemaTemplateDeduction.cpp.
References clang::FunctionTemplateDecl::getTemplatedDecl().
Referenced by clang::Sema::DeduceTemplateArguments().
getMoreSpecialized()
template<typename TemplateLikeDecl , typename PrimaryDel > static TemplateLikeDecl* getMoreSpecialized (Sema & S, QualType T1, QualType T2, TemplateLikeDecl * P1, PrimaryDel * P2, TemplateDeductionInfo & Info) static
Returns the more specialized template specialization between T1/P1 and T2/P2.
If IsMoreSpecialThanPrimaryCheck is true, T1/P1 is the partial specialization and T2/P2 is the primary template.
otherwise, both T1/P1 and T2/P2 are the partial specialization.
Parameters
T1 the type of the first template partial specialization
T2 if IsMoreSpecialThanPrimaryCheck is true, the type of the second template partial specialization; otherwise, the type of the primary template.
P1 the first template partial specialization
P2 if IsMoreSpecialThanPrimaryCheck is true, the second template partial specialization; otherwise, the primary template.
Returns
- If IsMoreSpecialThanPrimaryCheck is true, returns P1 if P1 is more specialized, returns nullptr if P1 is not more specialized.
otherwise, returns the more specialized template partial specialization. If neither partial specialization is more specialized, returns NULL.
Definition at line 5577 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::getMoreSpecializedPartialSpecialization(), and clang::Sema::isMoreSpecializedThanPrimary().
getPackIndexForParam()
static unsigned getPackIndexForParam (Sema & S, FunctionTemplateDecl * FunctionTemplate, const MultiLevelTemplateArgumentList & Args, unsigned ParamIdx) static
Find the pack index for a particular parameter index in an instantiation of a function template with specific arguments.
Returns
The pack index for whichever pack produced this parameter, or -1 if this was not produced by a parameter. Intended to be used as the ArgumentPackSubstitutionIndex for further substitutions.
Definition at line 3510 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::FinishTemplateArgumentDeduction().
GetTypeOfFunction()
static QualType GetTypeOfFunction (Sema & S, const OverloadExpr::FindResult & R, FunctionDecl * Fn) static
Gets the type of a function for template-argument-deducton purposes when it's considered as part of an overload set.
Definition at line 3706 of file SemaTemplateDeduction.cpp.
hasDeducibleTemplateParameters()
bool hasDeducibleTemplateParameters (Sema & S, FunctionTemplateDecl * FunctionTemplate, QualType T) static
Definition at line 6305 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::DeduceTemplateArguments().
hasInconsistentOrSupersetQualifiersOf()
static bool hasInconsistentOrSupersetQualifiersOf (QualType ParamType, QualType ArgType) static
Determine whether the parameter has qualifiers that the argument lacks.
Put another way, determine whether there is no way to add a deduced set of qualifiers to the ParamType that would result in its qualifiers matching those of the ArgType.
Definition at line 1146 of file SemaTemplateDeduction.cpp.
References clang::Qualifiers::getAddressSpace(), clang::Qualifiers::getCVRQualifiers(), clang::Qualifiers::getObjCGCAttr(), clang::Qualifiers::getObjCLifetime(), clang::QualType::getQualifiers(), clang::Qualifiers::hasAddressSpace(), clang::Qualifiers::hasObjCGCAttr(), and clang::Qualifiers::hasObjCLifetime().
hasPackExpansionBeforeEnd()
static bool hasPackExpansionBeforeEnd (ArrayRef< TemplateArgument > Args) static
Determine whether the given set of template arguments has a pack expansion that is not the last template argument.
Definition at line 2343 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgument::Pack.
Referenced by MarkUsedTemplateParameters(), and clang::Sema::MarkUsedTemplateParameters().
hasSameExtendedValue()
static bool hasSameExtendedValue (llvm::APSInt X, llvm::APSInt Y) static
Compare two APSInts, extending and switching the sign as necessary to compare their values regardless of underlying type.
Definition at line 116 of file SemaTemplateDeduction.cpp.
References clang::tooling::X().
Referenced by checkDeducedTemplateArguments(), and isSameTemplateArg().
hasTemplateArgumentForDeduction()
static bool hasTemplateArgumentForDeduction (ArrayRef< TemplateArgument > & Args, unsigned & ArgIdx) static
Determine whether there is a template argument to be used for deduction.
This routine "expands" argument packs in-place, overriding its input parameters so that Args[ArgIdx] will be the available template argument.
Returns
true if there is another template argument (which will be at Args[ArgIdx]), false otherwise.
Definition at line 2326 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgument::getKind(), clang::TemplateArgument::Pack, and clang::TemplateArgument::pack_elements().
isAtLeastAsSpecializedAs() [1/2]
template<typename TemplateLikeDecl > static bool isAtLeastAsSpecializedAs (Sema & S, QualType T1, QualType T2, TemplateLikeDecl * P2, TemplateDeductionInfo & Info) static
Determine whether one partial specialization, P1, is at least as specialized than another, P2.
Template Parameters
TemplateLikeDecl The kind of P2, which must be a TemplateDecl or {Class,Var}TemplatePartialSpecializationDecl.
Parameters
T1 The injected-class-name of P1 (faked for a variable template).
T2 The injected-class-name of P2 (faked for a variable template).
Definition at line 5435 of file SemaTemplateDeduction.cpp.
isAtLeastAsSpecializedAs() [2/2]
static bool isAtLeastAsSpecializedAs (Sema & S, SourceLocation Loc, FunctionTemplateDecl * FT1, FunctionTemplateDecl * FT2, TemplatePartialOrderingContext TPOC, unsigned NumCallArguments1, bool Reversed) static
Determine whether the function template FT1 is at least as specialized as FT2.
Definition at line 5011 of file SemaTemplateDeduction.cpp.
Referenced by clang::Sema::getMoreSpecializedTemplate(), and clang::Sema::isTemplateTemplateParameterAtLeastAsSpecializedAs().
isForwardingReference()
static bool isForwardingReference (QualType Param, unsigned FirstInnerIndex) static
Determine whether a type denotes a forwarding reference.
Definition at line 1210 of file SemaTemplateDeduction.cpp.
References clang::Type::getAs(), and clang::TemplateTypeParmType::getIndex().
IsPossiblyOpaquelyQualifiedType()
static bool IsPossiblyOpaquelyQualifiedType (QualType T) static
Determines whether the given type is an opaque type that might be more qualified when instantiated.
Definition at line 651 of file SemaTemplateDeduction.cpp.
References clang::Type::getCanonicalTypeInternal(), clang::QualType::getTypePtr(), and IsPossiblyOpaquelyQualifiedTypeInternal().
IsPossiblyOpaquelyQualifiedTypeInternal()
static bool IsPossiblyOpaquelyQualifiedTypeInternal (const Type * T) static
Definition at line 625 of file SemaTemplateDeduction.cpp.
References clang::Type::getTypeClass(), and clang::Type::isCanonicalUnqualified().
Referenced by IsPossiblyOpaquelyQualifiedType().
isSameDeclaration()
static bool isSameDeclaration (Decl * X, Decl * Y) static
Determine whether two declaration pointers refer to the same declaration.
Definition at line 198 of file SemaTemplateDeduction.cpp.
References clang::Decl::getCanonicalDecl(), and clang::tooling::X().
Referenced by checkDeducedTemplateArguments(), and isSameTemplateArg().
isSameTemplate()
static bool isSameTemplate (TemplateDecl * T1, TemplateDecl * T2) static
Determine if the two templates are equivalent.
Definition at line 5317 of file SemaTemplateDeduction.cpp.
References clang::Decl::getCanonicalDecl().
Referenced by clang::Sema::getMostSpecialized().
isSameTemplateArg()
static bool isSameTemplateArg (ASTContext & Context, TemplateArgument X, const TemplateArgument & Y, bool PartialOrdering, bool PackExpansionMatchesPack = false) static
Determine whether two template arguments are the same.
Definition at line 2454 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgument::Declaration, clang::TemplateArgument::Expression, clang::TemplateArgument::getAsDecl(), clang::TemplateArgument::getAsExpr(), clang::TemplateArgument::getAsIntegral(), clang::TemplateArgument::getAsTemplateOrTemplatePattern(), clang::TemplateArgument::getAsType(), clang::TemplateName::getAsVoidPointer(), clang::ASTContext::getCanonicalTemplateName(), clang::ASTContext::getCanonicalType(), clang::TemplateArgument::getKind(), clang::TemplateArgument::getNullPtrType(), hasSameExtendedValue(), clang::ASTContext::hasSameType(), clang::TemplateArgument::Integral, clang::TemplateArgument::isPackExpansion(), isSameDeclaration(), clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, clang::TemplateArgument::Pack, clang::TemplateArgument::pack_elements(), clang::TemplateArgument::pack_size(), clang::PartialOrdering, clang::Stmt::Profile(), clang::TemplateArgument::Template, clang::TemplateArgument::TemplateExpansion, clang::TemplateArgument::Type, and clang::tooling::X().
isSimpleTemplateIdType()
static bool isSimpleTemplateIdType (QualType T) static
Determine whether the given type T is a simple-template-id type.
Definition at line 3145 of file SemaTemplateDeduction.cpp.
References clang::Type::getAs().
makeTemplateParameter()
static TemplateParameter makeTemplateParameter (Decl * D) static
Helper function to build a TemplateParameter when we don't know its type statically.
Definition at line 658 of file SemaTemplateDeduction.cpp.
MarkUsedTemplateParameters() [1/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, const Expr * E, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector & Used) static
Mark the template parameters that are used by the given expression.
Definition at line 5840 of file SemaTemplateDeduction.cpp.
References Depth, getDeducedParameterFromExpr(), clang::NonTypeTemplateParmDecl::getDepth(), clang::NonTypeTemplateParmDecl::getIndex(), clang::ASTContext::getLangOpts(), clang::ValueDecl::getType(), MarkUsedTemplateParameters(), and Used.
MarkUsedTemplateParameters() [2/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, const TemplateArgument & TemplateArg, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector & Used) static
Mark the template parameters that are used by this template argument.
Definition at line 6209 of file SemaTemplateDeduction.cpp.
References clang::TemplateArgument::Declaration, Depth, clang::TemplateArgument::Expression, clang::TemplateArgument::Integral, clang::TemplateArgument::Null, clang::TemplateArgument::NullPtr, P, clang::TemplateArgument::Pack, clang::TemplateArgument::Template, clang::TemplateArg, clang::TemplateArgument::TemplateExpansion, clang::TemplateArgument::Type, and Used.
Referenced by MarkUsedTemplateParameters().
MarkUsedTemplateParameters() [3/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, NestedNameSpecifier * NNS, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector & Used) static
Mark the template parameters that are used by the given nested name specifier.
Definition at line 5871 of file SemaTemplateDeduction.cpp.
References Depth, clang::NestedNameSpecifier::getAsType(), clang::NestedNameSpecifier::getPrefix(), MarkUsedTemplateParameters(), and Used.
MarkUsedTemplateParameters() [4/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, QualType T, bool OnlyDeduced, unsigned Level, llvm::SmallBitVector & Deduced) static
Mark the template parameters that are used by the given type.
Definition at line 5913 of file SemaTemplateDeduction.cpp.
References Depth, clang::DependentAddressSpaceType::getAddrSpaceExpr(), clang::SubstTemplateTypeParmPackType::getArgumentPack(), clang::Type::getAs(), clang::ASTContext::getCanonicalType(), clang::MemberPointerType::getClass(), clang::DependentSizedMatrixType::getColumnExpr(), clang::TemplateTypeParmDecl::getDepth(), clang::TemplateTypeParmType::getDepth(), clang::DependentSizedExtVectorType::getElementType(), clang::MatrixType::getElementType(), clang::TemplateTypeParmType::getIndex(), clang::SubstTemplateTypeParmPackType::getIndex(), clang::FunctionProtoType::getNoexceptExpr(), clang::FunctionProtoType::getNumParams(), clang::FunctionProtoType::getParamType(), clang::MemberPointerType::getPointeeType(), clang::DependentAddressSpaceType::getPointeeType(), clang::DependentTemplateSpecializationType::getQualifier(), clang::SubstTemplateTypeParmPackType::getReplacedParameter(), clang::FunctionType::getReturnType(), clang::DependentSizedMatrixType::getRowExpr(), clang::DependentSizedExtVectorType::getSizeExpr(), clang::TemplateSpecializationType::getTemplateName(), clang::Type::getTypeClass(), clang::QualType::getTypePtr(), getUnderlyingType(), hasPackExpansionBeforeEnd(), clang::Type::isDependentType(), clang::QualType::isNull(), MarkUsedTemplateParameters(), clang::TemplateSpecializationType::template_arguments(), clang::DependentTemplateSpecializationType::template_arguments(), and Used.
MarkUsedTemplateParameters() [5/5]
static void MarkUsedTemplateParameters (ASTContext & Ctx, TemplateName Name, bool OnlyDeduced, unsigned Depth, llvm::SmallBitVector & Used) static
Mark the template parameters that are used by the given template name.
Definition at line 5888 of file SemaTemplateDeduction.cpp.
ResolveOverloadForDeduction()
static QualType ResolveOverloadForDeduction (Sema & S, TemplateParameterList * TemplateParams, Expr * Arg, QualType ParamType, bool ParamWasReference) static
Apply the deduction rules for overload sets.
Returns
the null type if this argument should be treated as an undeduced context
Definition at line 3733 of file SemaTemplateDeduction.cpp.