clang: lib/Sema/SemaRISCVVectorLookup.cpp File Reference
SemaRISCVVectorLookup.cpp File Reference
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/Basic/Builtins.h"
#include "clang/Basic/TargetInfo.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Sema/Lookup.h"
#include "clang/Sema/RISCVIntrinsicManager.h"
#include "clang/Sema/Sema.h"
#include "clang/Support/RISCVVIntrinsicUtils.h"
#include "llvm/ADT/SmallVector.h"
#include <optional>
#include <string>
#include <vector>
#include "clang/Basic/riscv_vector_builtin_sema.inc"
Namespaces
clang
Macros
#define DECL_SIGNATURE_TABLE
#define DECL_INTRINSIC_RECORDS
Functions
static ArrayRef< PrototypeDescriptor > ProtoSeq2ArrayRef (uint16_t Index, uint8_t Length)
static QualType RVVType2Qual (ASTContext &Context, const RVVType *Type)
std::unique_ptr< sema::RISCVIntrinsicManager > clang::CreateRISCVIntrinsicManager (Sema &S)
Variables
static const PrototypeDescriptor RVVSignatureTable []
static const RVVIntrinsicRecord RVVIntrinsicRecords []
Macro Definition Documentation
DECL_INTRINSIC_RECORDS
#define DECL_INTRINSIC_RECORDS
DECL_SIGNATURE_TABLE
#define DECL_SIGNATURE_TABLE
Function Documentation
ProtoSeq2ArrayRef()
static ArrayRef<PrototypeDescriptor> ProtoSeq2ArrayRef (uint16_t Index, uint8_t Length) static
Definition at line 68 of file SemaRISCVVectorLookup.cpp.
RVVType2Qual()
static QualType RVVType2Qual (ASTContext & Context, const RVVType * Type) static
Definition at line 73 of file SemaRISCVVectorLookup.cpp.
References clang::RISCV::Boolean, clang::ASTContext::BoolTy, clang::ASTContext::DoubleTy, clang::RISCV::Float, clang::ASTContext::Float16Ty, clang::ASTContext::FloatTy, clang::ASTContext::getConstType(), clang::ASTContext::getIntTypeForBitwidth(), clang::ASTContext::getPointerDiffType(), clang::ASTContext::getPointerType(), clang::ASTContext::getScalableVectorType(), clang::ASTContext::getSizeType(), clang::RISCV::Invalid, clang::ASTContext::LongTy, clang::RISCV::Ptrdiff_t, clang::RISCV::SignedInteger, clang::RISCV::SignedLong, clang::RISCV::Size_t, clang::RISCV::UnsignedInteger, clang::RISCV::UnsignedLong, clang::ASTContext::UnsignedLongTy, and clang::ASTContext::VoidTy.
Variable Documentation
RVVIntrinsicRecords
const RVVIntrinsicRecord RVVIntrinsicRecords[] static
Initial value:
= {
#define DECL_INTRINSIC_RECORDS
}
Definition at line 61 of file SemaRISCVVectorLookup.cpp.
RVVSignatureTable
const PrototypeDescriptor RVVSignatureTable[] static
Initial value:
= {
#define DECL_SIGNATURE_TABLE
}
Definition at line 55 of file SemaRISCVVectorLookup.cpp.