clang: clang::DeclaratorChunk Struct Reference
clang::DeclaratorChunk Struct Reference
One instance of this struct is used for each type in a declarator that is parsed.
#include "clang/Sema/DeclSpec.h"
Classes
struct ArrayTypeInfo
struct BlockPointerTypeInfo
struct FunctionTypeInfo
struct MemberPointerTypeInfo
struct ParamInfo
ParamInfo - An array of paraminfo objects is allocated whenever a function declarator is parsed.
struct PipeTypeInfo
struct PointerTypeInfo
struct ReferenceTypeInfo
struct TypeAndRange
Public Types
enum {
Pointer, Reference, Array, Function,
BlockPointer, MemberPointer, Paren, Pipe
}
Public Member Functions
DeclaratorChunk ()
SourceRange getSourceRange () const
void destroy ()
const ParsedAttributesView & getAttrs () const
If there are attributes applied to this declaratorchunk, return them.
ParsedAttributesView & getAttrs ()
bool isParen () const
Static Public Member Functions
static DeclaratorChunk getPointer (unsigned TypeQuals, SourceLocation Loc, SourceLocation ConstQualLoc, SourceLocation VolatileQualLoc, SourceLocation RestrictQualLoc, SourceLocation AtomicQualLoc, SourceLocation UnalignedQualLoc)
Return a DeclaratorChunk for a pointer.
static DeclaratorChunk getReference (unsigned TypeQuals, SourceLocation Loc, bool lvalue)
Return a DeclaratorChunk for a reference.
static DeclaratorChunk getArray (unsigned TypeQuals, bool isStatic, bool isStar, Expr *NumElts, SourceLocation LBLoc, SourceLocation RBLoc)
Return a DeclaratorChunk for an array.
static DeclaratorChunk getFunction (bool HasProto, bool IsAmbiguous, SourceLocation LParenLoc, ParamInfo *Params, unsigned NumParams, SourceLocation EllipsisLoc, SourceLocation RParenLoc, bool RefQualifierIsLvalueRef, SourceLocation RefQualifierLoc, SourceLocation MutableLoc, ExceptionSpecificationType ESpecType, SourceRange ESpecRange, ParsedType *Exceptions, SourceRange *ExceptionRanges, unsigned NumExceptions, Expr *NoexceptExpr, CachedTokens *ExceptionSpecTokens, ArrayRef< NamedDecl * > DeclsInPrototype, SourceLocation LocalRangeBegin, SourceLocation LocalRangeEnd, Declarator &TheDeclarator, TypeResult TrailingReturnType=TypeResult(), SourceLocation TrailingReturnTypeLoc=SourceLocation(), DeclSpec *MethodQualifiers=nullptr)
DeclaratorChunk::getFunction - Return a DeclaratorChunk for a function.
static DeclaratorChunk getBlockPointer (unsigned TypeQuals, SourceLocation Loc)
Return a DeclaratorChunk for a block.
static DeclaratorChunk getPipe (unsigned TypeQuals, SourceLocation Loc)
Return a DeclaratorChunk for a block.
static DeclaratorChunk getMemberPointer (const CXXScopeSpec &SS, unsigned TypeQuals, SourceLocation StarLoc, SourceLocation EndLoc)
static DeclaratorChunk getParen (SourceLocation LParenLoc, SourceLocation RParenLoc)
Return a DeclaratorChunk for a paren.
Public Attributes
enum clang::DeclaratorChunk:: { ... } Kind
SourceLocation Loc
Loc - The place where this type was defined.
SourceLocation EndLoc
EndLoc - If valid, the place where this chunck ends.
ParsedAttributesView AttrList
union {
PointerTypeInfo Ptr
ReferenceTypeInfo Ref
ArrayTypeInfo Arr
FunctionTypeInfo Fun
BlockPointerTypeInfo Cls
MemberPointerTypeInfo Mem
PipeTypeInfo PipeInfo
};
Detailed Description
One instance of this struct is used for each type in a declarator that is parsed.
This is intended to be a small value object.
Definition at line 1196 of file DeclSpec.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Pointer
Reference
Array
Function
BlockPointer
MemberPointer
Paren
Pipe
Definition at line 1199 of file DeclSpec.h.
Constructor & Destructor Documentation
DeclaratorChunk()
clang::DeclaratorChunk::DeclaratorChunk () inline
Definition at line 1197 of file DeclSpec.h.
Member Function Documentation
destroy()
void clang::DeclaratorChunk::destroy () inline
Definition at line 1581 of file DeclSpec.h.
References Arr, Array, BlockPointer, Cls, clang::DeclaratorChunk::PointerTypeInfo::destroy(), clang::DeclaratorChunk::ReferenceTypeInfo::destroy(), clang::DeclaratorChunk::ArrayTypeInfo::destroy(), clang::DeclaratorChunk::FunctionTypeInfo::destroy(), clang::DeclaratorChunk::BlockPointerTypeInfo::destroy(), clang::DeclaratorChunk::MemberPointerTypeInfo::destroy(), clang::DeclaratorChunk::PipeTypeInfo::destroy(), Fun, Function, Kind, Mem, MemberPointer, Paren, Pipe, PipeInfo, Pointer, Ptr, Ref, and Reference.
getArray()
static DeclaratorChunk clang::DeclaratorChunk::getArray (unsigned TypeQuals, bool isStatic, bool isStar, Expr * NumElts, SourceLocation LBLoc, SourceLocation RBLoc) inline static
Return a DeclaratorChunk for an array.
Definition at line 1631 of file DeclSpec.h.
References Arr, Array, EndLoc, clang::DeclaratorChunk::ArrayTypeInfo::hasStatic, clang::DeclaratorChunk::ArrayTypeInfo::isStar, Kind, Loc, clang::DeclaratorChunk::ArrayTypeInfo::NumElts, and clang::DeclaratorChunk::ArrayTypeInfo::TypeQuals.
getAttrs() [1/2]
ParsedAttributesView& clang::DeclaratorChunk::getAttrs () inline
Definition at line 1597 of file DeclSpec.h.
References AttrList.
getAttrs() [2/2]
const ParsedAttributesView& clang::DeclaratorChunk::getAttrs () const inline
If there are attributes applied to this declaratorchunk, return them.
Definition at line 1596 of file DeclSpec.h.
References AttrList.
Referenced by addContextSensitiveTypeNullability(), clang::Sema::checkUnusedDeclAttributes(), distributeFunctionTypeAttr(), distributeFunctionTypeAttrToInnermost(), distributeNullabilityTypeAttr(), distributeObjCPointerTypeAttr(), distributeObjCPointerTypeAttrFromDeclarator(), and takeDeclAttributes().
getBlockPointer()
static DeclaratorChunk clang::DeclaratorChunk::getBlockPointer (unsigned TypeQuals, SourceLocation Loc) inline static
Return a DeclaratorChunk for a block.
Definition at line 1674 of file DeclSpec.h.
References BlockPointer, Cls, Kind, Loc, and clang::DeclaratorChunk::BlockPointerTypeInfo::TypeQuals.
getFunction()
DeclaratorChunk DeclaratorChunk::getFunction (bool hasProto, bool isAmbiguous, SourceLocation LParenLoc, ParamInfo * Params, unsigned NumParams, SourceLocation EllipsisLoc, SourceLocation RParenLoc, bool RefQualifierIsLvalueRef, SourceLocation RefQualifierLoc, SourceLocation MutableLoc, ExceptionSpecificationType ESpecType, SourceRange ESpecRange, ParsedType * Exceptions, SourceRange * ExceptionRanges, unsigned NumExceptions, Expr * NoexceptExpr, CachedTokens * ExceptionSpecTokens, ArrayRef< NamedDecl * > DeclsInPrototype, SourceLocation LocalRangeBegin, SourceLocation LocalRangeEnd, Declarator & TheDeclarator, TypeResult TrailingReturnType = TypeResult(), SourceLocation TrailingReturnTypeLoc = SourceLocation(), DeclSpec * MethodQualifiers = nullptr) static
DeclaratorChunk::getFunction - Return a DeclaratorChunk for a function.
"TheDeclarator" is the declarator that this will be added to.
Definition at line 161 of file DeclSpec.cpp.
References clang::DeclaratorChunk::FunctionTypeInfo::DeclsInPrototype, clang::DeclaratorChunk::FunctionTypeInfo::DeleteParams, clang::DeclaratorChunk::FunctionTypeInfo::EllipsisLoc, EndLoc, clang::EST_DependentNoexcept, clang::EST_Dynamic, clang::EST_NoexceptFalse, clang::EST_NoexceptTrue, clang::EST_None, clang::EST_Unparsed, clang::DeclaratorChunk::FunctionTypeInfo::Exceptions, clang::DeclaratorChunk::FunctionTypeInfo::ExceptionSpecLocBeg, clang::DeclaratorChunk::FunctionTypeInfo::ExceptionSpecLocEnd, clang::DeclaratorChunk::FunctionTypeInfo::ExceptionSpecTokens, clang::DeclaratorChunk::FunctionTypeInfo::ExceptionSpecType, clang::DeclSpec::forEachCVRUQualifier(), Fun, Function, clang::ActionResult< PtrTy, CompressInvalid >::get(), clang::DeclSpec::getAttributePool(), clang::DeclSpec::getAttributes(), clang::SourceRange::getBegin(), clang::SourceRange::getEnd(), clang::DeclSpec::getTypeQualifiers(), clang::DeclaratorChunk::FunctionTypeInfo::hasPrototype, clang::DeclaratorChunk::FunctionTypeInfo::HasTrailingReturnType, clang::Declarator::InlineParams, clang::DeclaratorChunk::FunctionTypeInfo::isAmbiguous, clang::ActionResult< PtrTy, CompressInvalid >::isInvalid(), clang::ActionResult< PtrTy, CompressInvalid >::isUsable(), clang::SourceLocation::isValid(), clang::DeclaratorChunk::FunctionTypeInfo::isVariadic, Kind, Loc, clang::DeclaratorChunk::FunctionTypeInfo::LParenLoc, clang::DeclaratorChunk::FunctionTypeInfo::MethodQualifiers, clang::DeclaratorChunk::FunctionTypeInfo::MutableLoc, clang::DeclaratorChunk::FunctionTypeInfo::NoexceptExpr, clang::DeclaratorChunk::FunctionTypeInfo::NumExceptionsOrDecls, clang::DeclaratorChunk::FunctionTypeInfo::NumParams, clang::DeclaratorChunk::FunctionTypeInfo::Params, clang::DeclaratorChunk::FunctionTypeInfo::QualAttrFactory, clang::DeclaratorChunk::TypeAndRange::Range, clang::DeclaratorChunk::FunctionTypeInfo::RefQualifierIsLValueRef, clang::DeclaratorChunk::FunctionTypeInfo::RefQualifierLoc, clang::DeclaratorChunk::FunctionTypeInfo::RParenLoc, clang::DeclSpec::SetTypeQual(), clang::ParsedAttributesView::size(), clang::AttributePool::takeAllFrom(), clang::ParsedAttributes::takeAllFrom(), clang::DeclSpec::TQ_atomic, clang::DeclaratorChunk::FunctionTypeInfo::TrailingReturnType, clang::DeclaratorChunk::FunctionTypeInfo::TrailingReturnTypeLoc, and clang::DeclaratorChunk::TypeAndRange::Ty.
Referenced by maybeSynthesizeBlockSignature().
getMemberPointer()
static DeclaratorChunk clang::DeclaratorChunk::getMemberPointer (const CXXScopeSpec & SS, unsigned TypeQuals, SourceLocation StarLoc, SourceLocation EndLoc) inline static
Definition at line 1693 of file DeclSpec.h.
References EndLoc, clang::CXXScopeSpec::getBeginLoc(), Kind, Loc, Mem, MemberPointer, clang::DeclaratorChunk::MemberPointerTypeInfo::ScopeMem, clang::DeclaratorChunk::MemberPointerTypeInfo::StarLoc, and clang::DeclaratorChunk::MemberPointerTypeInfo::TypeQuals.
getParen()
static DeclaratorChunk clang::DeclaratorChunk::getParen (SourceLocation LParenLoc, SourceLocation RParenLoc) inline static
Return a DeclaratorChunk for a paren.
Definition at line 1709 of file DeclSpec.h.
References EndLoc, Kind, Loc, and Paren.
getPipe()
static DeclaratorChunk clang::DeclaratorChunk::getPipe (unsigned TypeQuals, SourceLocation Loc) inline static
Return a DeclaratorChunk for a block.
Definition at line 1684 of file DeclSpec.h.
References Cls, Kind, Loc, Pipe, and clang::DeclaratorChunk::BlockPointerTypeInfo::TypeQuals.
getPointer()
static DeclaratorChunk clang::DeclaratorChunk::getPointer (unsigned TypeQuals, SourceLocation Loc, SourceLocation ConstQualLoc, SourceLocation VolatileQualLoc, SourceLocation RestrictQualLoc, SourceLocation AtomicQualLoc, SourceLocation UnalignedQualLoc) inline static
Return a DeclaratorChunk for a pointer.
Definition at line 1600 of file DeclSpec.h.
References clang::DeclaratorChunk::PointerTypeInfo::AtomicQualLoc, clang::DeclaratorChunk::PointerTypeInfo::ConstQualLoc, Kind, Loc, Pointer, Ptr, clang::DeclaratorChunk::PointerTypeInfo::RestrictQualLoc, clang::DeclaratorChunk::PointerTypeInfo::TypeQuals, clang::DeclaratorChunk::PointerTypeInfo::UnalignedQualLoc, and clang::DeclaratorChunk::PointerTypeInfo::VolatileQualLoc.
getReference()
static DeclaratorChunk clang::DeclaratorChunk::getReference (unsigned TypeQuals, SourceLocation Loc, bool lvalue) inline static
Return a DeclaratorChunk for a reference.
Definition at line 1620 of file DeclSpec.h.
References clang::DeclaratorChunk::ReferenceTypeInfo::HasRestrict, Kind, Loc, clang::DeclaratorChunk::ReferenceTypeInfo::LValueRef, Ref, Reference, and clang::DeclSpec::TQ_restrict.
getSourceRange()
SourceRange clang::DeclaratorChunk::getSourceRange () const inline
Definition at line 1208 of file DeclSpec.h.
References EndLoc, clang::SourceLocation::isInvalid(), and Loc.
isParen()
bool clang::DeclaratorChunk::isParen () const inline
Definition at line 1718 of file DeclSpec.h.
References Kind, and Paren.
Member Data Documentation
@213
union { ... }
Arr
ArrayTypeInfo clang::DeclaratorChunk::Arr
Definition at line 1574 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew(), clang::Sema::containsUnexpandedParameterPacks(), destroy(), getArray(), and clang::Declarator::isArrayOfUnknownBound().
AttrList
ParsedAttributesView clang::DeclaratorChunk::AttrList
Definition at line 1214 of file DeclSpec.h.
Referenced by getAttrs().
Cls
BlockPointerTypeInfo clang::DeclaratorChunk::Cls
Definition at line 1576 of file DeclSpec.h.
Referenced by destroy(), getBlockPointer(), and getPipe().
EndLoc
SourceLocation clang::DeclaratorChunk::EndLoc
EndLoc - If valid, the place where this chunck ends.
Definition at line 1206 of file DeclSpec.h.
Referenced by getArray(), getFunction(), getMemberPointer(), getParen(), and getSourceRange().
Fun
FunctionTypeInfo clang::DeclaratorChunk::Fun
Definition at line 1575 of file DeclSpec.h.
Referenced by clang::Sema::CheckExtraCXXDefaultArguments(), clang::Sema::containsUnexpandedParameterPacks(), destroy(), and getFunction().
Kind
enum { ... } clang::DeclaratorChunk::Kind
Referenced by clang::Sema::ActOnCXXNew(), clang::Sema::CheckExtraCXXDefaultArguments(), clang::Sema::containsUnexpandedParameterPacks(), destroy(), distributeFunctionTypeAttr(), distributeFunctionTypeAttrToInnermost(), distributeNullabilityTypeAttr(), distributeObjCPointerTypeAttr(), distributeObjCPointerTypeAttrFromDeclarator(), fillAtomicQualLoc(), getArray(), getBlockPointer(), getFunction(), getMemberPointer(), getParen(), getPipe(), getPointer(), getReference(), hasOuterPointerLikeChunk(), clang::Declarator::isArrayOfUnknownBound(), IsNoDerefableChunk(), isOmittedBlockReturnType(), isParen(), isPipeDeclarator(), and maybeMovePastReturnType().
Loc
SourceLocation clang::DeclaratorChunk::Loc
Loc - The place where this type was defined.
Definition at line 1204 of file DeclSpec.h.
Referenced by clang::Sema::ActOnCXXNew(), distributeNullabilityTypeAttr(), getArray(), getBlockPointer(), getFunction(), getMemberPointer(), getParen(), getPipe(), getPointer(), getReference(), and getSourceRange().
Mem
MemberPointerTypeInfo clang::DeclaratorChunk::Mem
Definition at line 1577 of file DeclSpec.h.
Referenced by clang::Sema::containsUnexpandedParameterPacks(), destroy(), and getMemberPointer().
PipeInfo
PipeTypeInfo clang::DeclaratorChunk::PipeInfo
Definition at line 1578 of file DeclSpec.h.
Referenced by destroy().
Ptr
PointerTypeInfo clang::DeclaratorChunk::Ptr
Definition at line 1572 of file DeclSpec.h.
Referenced by destroy(), fillAtomicQualLoc(), and getPointer().
Ref
ReferenceTypeInfo clang::DeclaratorChunk::Ref
Definition at line 1573 of file DeclSpec.h.
Referenced by destroy(), and getReference().
The documentation for this struct was generated from the following files:
include/clang/Sema/DeclSpec.h
lib/Sema/DeclSpec.cpp