clang: lib/Analysis/UnsafeBufferUsage.cpp File Reference
UnsafeBufferUsage.cpp File Reference
#include "clang/Analysis/Analyses/UnsafeBufferUsage.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/Lex/Preprocessor.h"
#include "clang/Lex/Lexer.h"
#include "llvm/ADT/SmallVector.h"
#include <memory>
#include <optional>
#include "clang/Analysis/Analyses/UnsafeBufferUsageGadgets.def"
Classes
class clang::ast_matchers::MatchDescendantVisitor
struct WarningGadgetSets
struct FixableGadgetSets
Namespaces
clang
clang::ast_matchers
Macros
#define GADGET(x) x,
#define NEXT ++numFound
#define FIXABLE_GADGET(name)
#define WARNING_GADGET(name)
#define FIXABLE_GADGET(x) x ## Gadget::matcher().bind(#x),
#define WARNING_GADGET(x) allOf(x ## Gadget::matcher().bind(#x), notInSafeBufferOptOut(&Handler)),
Functions
clang::ast_matchers::AST_MATCHER_P (Stmt, forEveryDescendant, internal::Matcher< Stmt >, innerMatcher)
clang::ast_matchers::AST_MATCHER_P (Stmt, notInSafeBufferOptOut, const UnsafeBufferUsageHandler *, Handler)
clang::ast_matchers::AST_MATCHER_P (CastExpr, castSubExpr, internal::Matcher< Expr >, innerMatcher)
static internal::Matcher< Stmt > clang::ast_matchers::isInUnspecifiedLvalueContext (internal::Matcher< Expr > innerMatcher)
static auto hasPointerType ()
static auto hasArrayType ()
static std::tuple< FixableGadgetList, WarningGadgetList, DeclUseTracker > findGadgets (const Decl *D, const UnsafeBufferUsageHandler &Handler)
Scan the function and return a list of gadgets found with provided kits.
static WarningGadgetSets groupWarningGadgetsByVar (WarningGadgetList &&AllUnsafeOperations)
static FixableGadgetSets groupFixablesByVar (FixableGadgetList &&AllFixableOperations)
static std::string getAPIntText (APInt Val)
template<typename NodeTy >
static SourceLocation getEndCharLoc (const NodeTy *Node, const SourceManager &SM, const LangOptions &LangOpts)
template<typename NodeTy >
static SourceLocation getPastLoc (const NodeTy *Node, const SourceManager &SM, const LangOptions &LangOpts)
static StringRef getExprText (const Expr *E, const SourceManager &SM, const LangOptions &LangOpts)
static FixItList populateInitializerFixItWithSpan (const Expr *Init, const ASTContext &Ctx, const StringRef UserFillPlaceHolder)
static FixItList fixVarDeclWithSpan (const VarDecl *D, const ASTContext &Ctx, const StringRef UserFillPlaceHolder)
static FixItList fixVariableWithSpan (const VarDecl *VD, const DeclUseTracker &Tracker, const ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static FixItList fixVariable (const VarDecl *VD, Strategy::Kind K, const DeclUseTracker &Tracker, const ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static bool overlapWithMacro (const FixItList &FixIts)
static std::map< const VarDecl *, FixItList > getFixIts (FixableGadgetSets &FixablesForUnsafeVars, const Strategy &S, const DeclUseTracker &Tracker, const ASTContext &Ctx, UnsafeBufferUsageHandler &Handler)
static Strategy getNaiveStrategy (const llvm::SmallVectorImpl< const VarDecl * > &UnsafeVars)
Macro Definition Documentation
FIXABLE_GADGET [1/2]
#define FIXABLE_GADGET (name)
Value:
      if (Result.Nodes.getNodeAs<Stmt>(#name)) {                               \
        FixableGadgets.push_back(std::make_unique<name ## Gadget>(Result));           \
        NEXT;                                                                  \
      }
FIXABLE_GADGET [2/2]
#define FIXABLE_GADGET (x) x ## Gadget::matcher().bind(#x),
GADGET
#define GADGET (x) x,
Definition at line 173 of file UnsafeBufferUsage.cpp.
NEXT
#define NEXT ++numFound
WARNING_GADGET [1/2]
#define WARNING_GADGET (name)
Value:
      if (Result.Nodes.getNodeAs<Stmt>(#name)) {                               \
        WarningGadgets.push_back(std::make_unique<name ## Gadget>(Result));           \
        NEXT;                                                                  \
      }
WARNING_GADGET [2/2]
#define WARNING_GADGET (x) allOf(x ## Gadget::matcher().bind(#x), notInSafeBufferOptOut(&Handler)),
Function Documentation
findGadgets()
static std::tuple<FixableGadgetList, WarningGadgetList, DeclUseTracker> findGadgets (const Decl * D, const UnsafeBufferUsageHandler & Handler) static
Scan the function and return a list of gadgets found with provided kits.
Definition at line 558 of file UnsafeBufferUsage.cpp.
References clang::ast_matchers::MatchFinder::addMatcher(), clang::ast_matchers::allOf, clang::ast_matchers::anyOf, clang::ast_matchers::declRefExpr, clang::ast_matchers::declStmt, clang::ast_matchers::eachOf, FIXABLE_GADGET, clang::Decl::getASTContext(), clang::Decl::getBody(), hasArrayType(), hasPointerType(), include(), clang::ast_matchers::MatchFinder::match(), NEXT, clang::transformer::run(), clang::ast_matchers::stmt, clang::ast_matchers::varDecl, WARNING_GADGET, and x.
Referenced by clang::checkUnsafeBufferUsage().
fixVarDeclWithSpan()
static FixItList fixVarDeclWithSpan (const VarDecl * D, const ASTContext & Ctx, const StringRef UserFillPlaceHolder) static
Definition at line 872 of file UnsafeBufferUsage.cpp.
References clang::QualType::getAsString(), clang::DeclaratorDecl::getBeginLoc(), getEndCharLoc(), clang::VarDecl::getInit(), clang::ASTContext::getLangOpts(), clang::NamedDecl::getName(), clang::Type::getPointeeType(), clang::ASTContext::getSourceManager(), clang::ValueDecl::getType(), clang::QualType::isNull(), populateInitializerFixItWithSpan(), and SM.
Referenced by fixVariableWithSpan().
fixVariable()
static FixItList fixVariable (const VarDecl * VD, Strategy::Kind K, const DeclUseTracker & Tracker, const ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 924 of file UnsafeBufferUsage.cpp.
References fixVariableWithSpan(), clang::ValueDecl::getType(), clang::VarDecl::isLocalVarDecl(), and clang::Type::isPointerType().
fixVariableWithSpan()
static FixItList fixVariableWithSpan (const VarDecl * VD, const DeclUseTracker & Tracker, const ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 905 of file UnsafeBufferUsage.cpp.
References fixVarDeclWithSpan(), clang::UnsafeBufferUsageHandler::getUserFillPlaceHolder(), and clang::DeclStmt::isSingleDecl().
Referenced by fixVariable().
getAPIntText()
static std::string getAPIntText (APInt Val) static
Definition at line 764 of file UnsafeBufferUsage.cpp.
getEndCharLoc()
template<typename NodeTy > static SourceLocation getEndCharLoc (const NodeTy * Node, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 774 of file UnsafeBufferUsage.cpp.
Referenced by fixVarDeclWithSpan().
getExprText()
static StringRef getExprText (const Expr * E, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 787 of file UnsafeBufferUsage.cpp.
getFixIts()
static std::map<const VarDecl *, FixItList> getFixIts (FixableGadgetSets & FixablesForUnsafeVars, const Strategy & S, const DeclUseTracker & Tracker, const ASTContext & Ctx, UnsafeBufferUsageHandler & Handler) static
Definition at line 959 of file UnsafeBufferUsage.cpp.
Referenced by clang::checkUnsafeBufferUsage().
getNaiveStrategy()
static Strategy getNaiveStrategy (const llvm::SmallVectorImpl< const VarDecl * > & UnsafeVars) static
Definition at line 1002 of file UnsafeBufferUsage.cpp.
Referenced by clang::checkUnsafeBufferUsage().
getPastLoc()
template<typename NodeTy > static SourceLocation getPastLoc (const NodeTy * Node, const SourceManager & SM, const LangOptions & LangOpts) static
Definition at line 781 of file UnsafeBufferUsage.cpp.
groupFixablesByVar()
static FixableGadgetSets groupFixablesByVar (FixableGadgetList && AllFixableOperations) static
Definition at line 690 of file UnsafeBufferUsage.cpp.
References FixableGadgetSets::byVar, and clang::DeclRefExpr::getDecl().
Referenced by clang::checkUnsafeBufferUsage().
groupWarningGadgetsByVar()
static WarningGadgetSets groupWarningGadgetsByVar (WarningGadgetList && AllUnsafeOperations) static
Definition at line 662 of file UnsafeBufferUsage.cpp.
References WarningGadgetSets::byVar, clang::DeclRefExpr::getDecl(), and WarningGadgetSets::noVar.
Referenced by clang::checkUnsafeBufferUsage().
hasArrayType()
static auto hasArrayType () static
Definition at line 157 of file UnsafeBufferUsage.cpp.
References clang::ast_matchers::arrayType.
Referenced by findGadgets().
hasPointerType()
static auto hasPointerType () static
Definition at line 153 of file UnsafeBufferUsage.cpp.
References clang::ast_matchers::pointerType.
Referenced by findGadgets().
overlapWithMacro()
static bool overlapWithMacro (const FixItList & FixIts) static
Definition at line 946 of file UnsafeBufferUsage.cpp.
References clang::CharSourceRange::getBegin(), and clang::FixItHint::RemoveRange.
populateInitializerFixItWithSpan()
static FixItList populateInitializerFixItWithSpan (const Expr * Init, const ASTContext & Ctx, const StringRef UserFillPlaceHolder) static
Definition at line 809 of file UnsafeBufferUsage.cpp.
References clang::ASTContext::getSourceManager(), and SM.
Referenced by fixVarDeclWithSpan().