LLVM: lib/Target/AArch64/Disassembler/AArch64Disassembler.cpp File Reference
AArch64Disassembler.cpp File Reference
#include "AArch64Disassembler.h"
#include "AArch64ExternalSymbolizer.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "MCTargetDesc/AArch64MCTargetDesc.h"
#include "TargetInfo/AArch64TargetInfo.h"
#include "Utils/AArch64BaseInfo.h"
#include "llvm-c/Disassembler.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCRelocationInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include <algorithm>
#include <memory>
#include "AArch64GenDisassemblerTables.inc"
#include "AArch64GenInstrInfo.inc"
Macros
#define DEBUG_TYPE "aarch64-disassembler"
#define Success MCDisassembler::Success
#define Fail MCDisassembler::Fail
#define SoftFail MCDisassembler::SoftFail
Typedefs
using DecodeStatus = MCDisassembler::DecodeStatus
Functions
static DecodeStatus DecodeFPR128RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR128_loRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR64RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR16RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR8RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPR64commonRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPR64RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPR64x8ClassRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPR64spRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMatrixIndexGPR32_8_11RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMatrixIndexGPR32_12_15RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPR32spRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeQQRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeQQQRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeQQQQRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDDRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDDDRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDDDDRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeZPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeZPR_4bRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeZPR_3bRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeZPR2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeZPR3RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeZPR4RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeZPR2Mul2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeZPR4Mul4RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeZPR2StridedRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeZPR4StridedRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
template<unsigned NumBitsForTile>
static DecodeStatus DecodeMatrixTile (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMatrixTileListRegisterClass (MCInst &Inst, unsigned RegMask, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePPR_3bRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePPR_p8to15RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePPR2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodePPR2Mul2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFixedPointScaleImm32 (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFixedPointScaleImm64 (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePCRelLabel19 (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemExtend (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMRSSystemRegister (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMSRSystemRegister (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeThreeAddrSRegInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMoveImmInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeUnsignedLdStInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSignedLdStInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeExclusiveLdStInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePairLdStInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAuthLoadInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddSubERegInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLogicalImmInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeModImmInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeModImmTiedInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAdrInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddSubImmShift (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeUnconditionalBranch (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSystemPStateImm0_15Instruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSystemPStateImm0_1Instruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeTestAndBranch (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFMOVLaneInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR64Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR64ImmNarrow (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR32Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR32ImmNarrow (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR16Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR16ImmNarrow (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftR8Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftL64Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftL32Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftL16Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeVecShiftL8Imm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeWSeqPairsClassRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeXSeqPairsClassRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSyspXzrInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSVELogicalImmInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
template<int Bits>
static DecodeStatus DecodeSImm (MCInst &Inst, uint64_t Imm, uint64_t Address, const MCDisassembler *Decoder)
template<int ElementWidth>
static DecodeStatus DecodeImm8OptLsl (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSVEIncDecImm (MCInst &Inst, unsigned Imm, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSVCROp (MCInst &Inst, unsigned Imm, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCPYMemOpInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodeSETMemOpInstruction (MCInst &Inst, uint32_t insn, uint64_t Addr, const MCDisassembler *Decoder)
static DecodeStatus DecodePRFMRegInstruction (MCInst &Inst, uint32_t insn, uint64_t Address, const MCDisassembler *Decoder)
static MCDisassembler * createAArch64Disassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
static MCSymbolizer * createAArch64ExternalSymbolizer (const Triple &TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAArch64Disassembler ()
static DecodeStatus DecodeVecShiftRImm (MCInst &Inst, unsigned Imm, unsigned Add)
static DecodeStatus DecodeVecShiftLImm (MCInst &Inst, unsigned Imm, unsigned Add)
static bool isInvalidPState (uint64_t Op1, uint64_t Op2)
static DecodeStatus DecodeGPRSeqPairsClassRegisterClass (MCInst &Inst, unsigned RegClassID, unsigned RegNo, uint64_t Addr, const MCDisassembler *Decoder)
Variables
static const SmallVector< SmallVector< unsigned, 16 >, 5 > MatrixZATileDecoderTable
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-disassembler"
Definition at line 34 of file AArch64Disassembler.cpp.
Fail
#define Fail MCDisassembler::Fail
Definition at line 301 of file AArch64Disassembler.cpp.
SoftFail
#define SoftFail MCDisassembler::SoftFail
Definition at line 302 of file AArch64Disassembler.cpp.
Success
#define Success MCDisassembler::Success
Definition at line 300 of file AArch64Disassembler.cpp.
Typedef Documentation
DecodeStatus
using DecodeStatus = MCDisassembler::DecodeStatus
Definition at line 37 of file AArch64Disassembler.cpp.
Function Documentation
createAArch64Disassembler()
static MCDisassembler* createAArch64Disassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 304 of file AArch64Disassembler.cpp.
Referenced by LLVMInitializeAArch64Disassembler().
createAArch64ExternalSymbolizer()
static MCSymbolizer* createAArch64ExternalSymbolizer (const Triple & TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void * DisInfo, MCContext * Ctx, std::unique_ptr< MCRelocationInfo > && RelInfo) static
Definition at line 385 of file AArch64Disassembler.cpp.
References move.
Referenced by LLVMInitializeAArch64Disassembler().
DecodeAddSubERegInstruction()
static DecodeStatus DecodeAddSubERegInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1609 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeGPR32RegisterClass(), DecodeGPR32spRegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), extend(), Fail, llvm::MCInst::getOpcode(), shift, and Success.
DecodeAddSubImmShift()
static DecodeStatus DecodeAddSubImmShift (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1772 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeGPR32RegisterClass(), DecodeGPR32spRegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), Fail, llvm::RISCVMatInt::Imm, S, Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeAdrInstruction()
static DecodeStatus DecodeAdrInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1754 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeGPR64RegisterClass(), Fail, Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeAuthLoadInstruction()
static DecodeStatus DecodeAuthLoadInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1576 of file AArch64Disassembler.cpp.
References Addr, DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), Fail, llvm::MCInst::getOpcode(), SoftFail, Success, and uint64_t.
DecodeCPYMemOpInstruction()
static DecodeStatus DecodeCPYMemOpInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 2003 of file AArch64Disassembler.cpp.
References Addr, DecodeGPR64commonRegisterClass(), DecodeGPR64RegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeDDDDRegisterClass()
static DecodeStatus DecodeDDDDRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 838 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeDDDRegisterClass()
static DecodeStatus DecodeDDDRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 827 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeDDRegisterClass()
static DecodeStatus DecodeDDRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 816 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeExclusiveLdStInstruction()
static DecodeStatus DecodeExclusiveLdStInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1360 of file AArch64Disassembler.cpp.
References Addr, DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), Fail, llvm::MCInst::getOpcode(), SoftFail, and Success.
DecodeFixedPointScaleImm32()
static DecodeStatus DecodeFixedPointScaleImm32 (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 849 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and Success.
DecodeFixedPointScaleImm64()
static DecodeStatus DecodeFixedPointScaleImm64 (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 858 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and Success.
DecodeFMOVLaneInstruction()
static DecodeStatus DecodeFMOVLaneInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 906 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), DecodeFPR128RegisterClass(), DecodeGPR64RegisterClass(), Insn, and Success.
DecodeFPR128_loRegisterClass()
static DecodeStatus DecodeFPR128_loRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 430 of file AArch64Disassembler.cpp.
References Addr, DecodeFPR128RegisterClass(), and Fail.
DecodeFPR128RegisterClass()
static DecodeStatus DecodeFPR128RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 417 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeFMOVLaneInstruction(), DecodeFPR128_loRegisterClass(), DecodeModImmInstruction(), DecodeModImmTiedInstruction(), DecodePairLdStInstruction(), DecodeSignedLdStInstruction(), and DecodeUnsignedLdStInstruction().
DecodeFPR16RegisterClass()
static DecodeStatus DecodeFPR16RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 461 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeSignedLdStInstruction(), and DecodeUnsignedLdStInstruction().
DecodeFPR32RegisterClass()
static DecodeStatus DecodeFPR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 449 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodePairLdStInstruction(), DecodeSignedLdStInstruction(), and DecodeUnsignedLdStInstruction().
DecodeFPR64RegisterClass()
static DecodeStatus DecodeFPR64RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 437 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeModImmInstruction(), DecodePairLdStInstruction(), DecodeSignedLdStInstruction(), and DecodeUnsignedLdStInstruction().
DecodeFPR8RegisterClass()
static DecodeStatus DecodeFPR8RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 473 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeSignedLdStInstruction(), and DecodeUnsignedLdStInstruction().
DecodeGPR32RegisterClass()
static DecodeStatus DecodeGPR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 563 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeAddSubERegInstruction(), DecodeAddSubImmShift(), DecodeExclusiveLdStInstruction(), DecodeLogicalImmInstruction(), DecodeMoveImmInstruction(), DecodePairLdStInstruction(), DecodePRFMRegInstruction(), DecodeSignedLdStInstruction(), DecodeTestAndBranch(), DecodeThreeAddrSRegInstruction(), and DecodeUnsignedLdStInstruction().
DecodeGPR32spRegisterClass()
static DecodeStatus DecodeGPR32spRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 575 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeAddSubERegInstruction(), DecodeAddSubImmShift(), and DecodeLogicalImmInstruction().
DecodeGPR64commonRegisterClass()
static DecodeStatus DecodeGPR64commonRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 486 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeCPYMemOpInstruction(), and DecodeSETMemOpInstruction().
DecodeGPR64RegisterClass()
static DecodeStatus DecodeGPR64RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 498 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeAddSubERegInstruction(), DecodeAddSubImmShift(), DecodeAdrInstruction(), DecodeAuthLoadInstruction(), DecodeCPYMemOpInstruction(), DecodeExclusiveLdStInstruction(), DecodeFMOVLaneInstruction(), DecodeLogicalImmInstruction(), DecodeMoveImmInstruction(), DecodePairLdStInstruction(), DecodePRFMRegInstruction(), DecodeSETMemOpInstruction(), DecodeSignedLdStInstruction(), DecodeSyspXzrInstruction(), DecodeTestAndBranch(), DecodeThreeAddrSRegInstruction(), and DecodeUnsignedLdStInstruction().
DecodeGPR64spRegisterClass()
static DecodeStatus DecodeGPR64spRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 525 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeAddSubERegInstruction(), DecodeAddSubImmShift(), DecodeAuthLoadInstruction(), DecodeExclusiveLdStInstruction(), DecodeLogicalImmInstruction(), DecodePairLdStInstruction(), DecodePRFMRegInstruction(), DecodeSignedLdStInstruction(), and DecodeUnsignedLdStInstruction().
DecodeGPR64x8ClassRegisterClass()
static DecodeStatus DecodeGPR64x8ClassRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 511 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeGPRSeqPairsClassRegisterClass()
static DecodeStatus DecodeGPRSeqPairsClassRegisterClass (MCInst & Inst, unsigned RegClassID, unsigned RegNo, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1895 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeWSeqPairsClassRegisterClass(), and DecodeXSeqPairsClassRegisterClass().
DecodeImm8OptLsl()
template<int ElementWidth> static DecodeStatus DecodeImm8OptLsl (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1975 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, llvm::RISCVMatInt::Imm, Shift, and Success.
DecodeLogicalImmInstruction()
static DecodeStatus DecodeLogicalImmInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1666 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeGPR32RegisterClass(), DecodeGPR32spRegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), Fail, llvm::MCInst::getOpcode(), llvm::AArch64_AM::isValidDecodeLogicalImmediate(), and Success.
DecodeMatrixIndexGPR32_12_15RegisterClass()
static DecodeStatus DecodeMatrixIndexGPR32_12_15RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 550 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeMatrixIndexGPR32_8_11RegisterClass()
static DecodeStatus DecodeMatrixIndexGPR32_8_11RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 537 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeMatrixTile()
template<unsigned NumBitsForTile> static DecodeStatus DecodeMatrixTile (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 717 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, MatrixZATileDecoderTable, and Success.
DecodeMatrixTileListRegisterClass()
static DecodeStatus DecodeMatrixTileListRegisterClass (MCInst & Inst, unsigned RegMask, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 695 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, and Success.
DecodeMemExtend()
static DecodeStatus DecodeMemExtend (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 880 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and Success.
Referenced by DecodePRFMRegInstruction().
DecodeModImmInstruction()
static DecodeStatus DecodeModImmInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1697 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeFPR128RegisterClass(), DecodeFPR64RegisterClass(), llvm::MCInst::getOpcode(), and Success.
DecodeModImmTiedInstruction()
static DecodeStatus DecodeModImmTiedInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1736 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeFPR128RegisterClass(), and Success.
DecodeMoveImmInstruction()
static DecodeStatus DecodeMoveImmInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1069 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), Fail, llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), shift, and Success.
DecodeMRSSystemRegister()
static DecodeStatus DecodeMRSSystemRegister (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 888 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and Success.
DecodeMSRSystemRegister()
static DecodeStatus DecodeMSRSystemRegister (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 898 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and Success.
DecodePairLdStInstruction()
static DecodeStatus DecodePairLdStInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1442 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeFPR128RegisterClass(), DecodeFPR32RegisterClass(), DecodeFPR64RegisterClass(), DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), Fail, llvm::MCInst::getOpcode(), SoftFail, and Success.
DecodePCRelLabel19()
static DecodeStatus DecodePCRelLabel19 (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 865 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), llvm::MCInst::getOpcode(), llvm::RISCVMatInt::Imm, Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodePPR2Mul2RegisterClass()
static DecodeStatus DecodePPR2Mul2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 772 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodePPR2RegisterClass()
static DecodeStatus DecodePPR2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 760 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodePPR_3bRegisterClass()
static DecodeStatus DecodePPR_3bRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 740 of file AArch64Disassembler.cpp.
References Addr, DecodePPRRegisterClass(), and Fail.
DecodePPR_p8to15RegisterClass()
static DecodeStatus DecodePPR_p8to15RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 751 of file AArch64Disassembler.cpp.
References Addr, DecodePPRRegisterClass(), and Fail.
DecodePPRRegisterClass()
static DecodeStatus DecodePPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 728 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodePPR_3bRegisterClass(), and DecodePPR_p8to15RegisterClass().
DecodePRFMRegInstruction()
static DecodeStatus DecodePRFMRegInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2052 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), DecodeMemExtend(), Fail, llvm::MCInst::getOpcode(), llvm::BitmaskEnumDetail::Mask(), Shift, Success, and uint64_t.
DecodeQQQQRegisterClass()
static DecodeStatus DecodeQQQQRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 805 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeQQQRegisterClass()
static DecodeStatus DecodeQQQRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 794 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeQQRegisterClass()
static DecodeStatus DecodeQQRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 783 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeSETMemOpInstruction()
static DecodeStatus DecodeSETMemOpInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 2028 of file AArch64Disassembler.cpp.
References Addr, DecodeGPR64commonRegisterClass(), DecodeGPR64RegisterClass(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeSignedLdStInstruction()
static DecodeStatus DecodeSignedLdStInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1161 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeFPR128RegisterClass(), DecodeFPR16RegisterClass(), DecodeFPR32RegisterClass(), DecodeFPR64RegisterClass(), DecodeFPR8RegisterClass(), DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), Fail, llvm::MCInst::getOpcode(), SoftFail, and Success.
DecodeSImm()
template<int Bits> static DecodeStatus DecodeSImm (MCInst & Inst, uint64_t Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1960 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::tgtok::Bits, llvm::MCOperand::createImm(), Fail, llvm::RISCVMatInt::Imm, and Success.
DecodeSVCROp()
static DecodeStatus DecodeSVCROp (MCInst & Inst, unsigned Imm, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1994 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, llvm::RISCVMatInt::Imm, and Success.
DecodeSVEIncDecImm()
static DecodeStatus DecodeSVEIncDecImm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1987 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and Success.
DecodeSVELogicalImmInstruction()
static DecodeStatus DecodeSVELogicalImmInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1944 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeZPRRegisterClass(), Fail, llvm::MCInst::getOpcode(), llvm::AArch64_AM::isValidDecodeLogicalImmediate(), and Success.
DecodeSyspXzrInstruction()
static DecodeStatus DecodeSyspXzrInstruction (MCInst & Inst, uint32_t insn, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1923 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeGPR64RegisterClass(), Fail, and Success.
DecodeSystemPStateImm0_15Instruction()
static DecodeStatus DecodeSystemPStateImm0_15Instruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1829 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), isInvalidPState(), Success, and uint64_t.
DecodeSystemPStateImm0_1Instruction()
static DecodeStatus DecodeSystemPStateImm0_1Instruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1850 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Fail, llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), isInvalidPState(), Success, and uint64_t.
DecodeTestAndBranch()
static DecodeStatus DecodeTestAndBranch (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1871 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, bit, llvm::MCOperand::createImm(), DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), Success, llvm::MCDisassembler::tryAddingSymbolicOperand(), and uint64_t.
DecodeThreeAddrSRegInstruction()
static DecodeStatus DecodeThreeAddrSRegInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1008 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), Fail, llvm::MCInst::getOpcode(), shift, Success, and x3.
DecodeUnconditionalBranch()
static DecodeStatus DecodeUnconditionalBranch (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1807 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeUnsignedLdStInstruction()
static DecodeStatus DecodeUnsignedLdStInstruction (MCInst & Inst, uint32_t insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1103 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), Addr, llvm::MCOperand::createImm(), DecodeFPR128RegisterClass(), DecodeFPR16RegisterClass(), DecodeFPR32RegisterClass(), DecodeFPR64RegisterClass(), DecodeFPR8RegisterClass(), DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), Fail, llvm::MCInst::getOpcode(), Success, and llvm::MCDisassembler::tryAddingSymbolicOperand().
DecodeVecShiftL16Imm()
static DecodeStatus DecodeVecShiftL16Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 995 of file AArch64Disassembler.cpp.
References DecodeVecShiftLImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftL32Imm()
static DecodeStatus DecodeVecShiftL32Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 989 of file AArch64Disassembler.cpp.
References DecodeVecShiftLImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftL64Imm()
static DecodeStatus DecodeVecShiftL64Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 983 of file AArch64Disassembler.cpp.
References DecodeVecShiftLImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftL8Imm()
static DecodeStatus DecodeVecShiftL8Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1001 of file AArch64Disassembler.cpp.
References DecodeVecShiftLImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftLImm()
static DecodeStatus DecodeVecShiftLImm (MCInst & Inst, unsigned Imm, unsigned Add) static
Definition at line 935 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and Success.
Referenced by DecodeVecShiftL16Imm(), DecodeVecShiftL32Imm(), DecodeVecShiftL64Imm(), and DecodeVecShiftL8Imm().
DecodeVecShiftR16Imm()
static DecodeStatus DecodeVecShiftR16Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 965 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftR16ImmNarrow()
static DecodeStatus DecodeVecShiftR16ImmNarrow (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 971 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftR32Imm()
static DecodeStatus DecodeVecShiftR32Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 953 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftR32ImmNarrow()
static DecodeStatus DecodeVecShiftR32ImmNarrow (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 959 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftR64Imm()
static DecodeStatus DecodeVecShiftR64Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 941 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftR64ImmNarrow()
static DecodeStatus DecodeVecShiftR64ImmNarrow (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 947 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftR8Imm()
static DecodeStatus DecodeVecShiftR8Imm (MCInst & Inst, unsigned Imm, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 977 of file AArch64Disassembler.cpp.
References DecodeVecShiftRImm(), and llvm::RISCVMatInt::Imm.
DecodeVecShiftRImm()
static DecodeStatus DecodeVecShiftRImm (MCInst & Inst, unsigned Imm, unsigned Add) static
Definition at line 929 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and Success.
Referenced by DecodeVecShiftR16Imm(), DecodeVecShiftR16ImmNarrow(), DecodeVecShiftR32Imm(), DecodeVecShiftR32ImmNarrow(), DecodeVecShiftR64Imm(), DecodeVecShiftR64ImmNarrow(), and DecodeVecShiftR8Imm().
DecodeWSeqPairsClassRegisterClass()
static DecodeStatus DecodeWSeqPairsClassRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1908 of file AArch64Disassembler.cpp.
References Addr, and DecodeGPRSeqPairsClassRegisterClass().
DecodeXSeqPairsClassRegisterClass()
static DecodeStatus DecodeXSeqPairsClassRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Addr, const MCDisassembler * Decoder) static
Definition at line 1916 of file AArch64Disassembler.cpp.
References Addr, and DecodeGPRSeqPairsClassRegisterClass().
DecodeZPR2Mul2RegisterClass()
static DecodeStatus DecodeZPR2Mul2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 648 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeZPR2RegisterClass()
static DecodeStatus DecodeZPR2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 615 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeZPR2StridedRegisterClass()
static DecodeStatus DecodeZPR2StridedRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 670 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeZPR3RegisterClass()
static DecodeStatus DecodeZPR3RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 626 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeZPR4Mul4RegisterClass()
static DecodeStatus DecodeZPR4Mul4RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 659 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeZPR4RegisterClass()
static DecodeStatus DecodeZPR4RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 637 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeZPR4StridedRegisterClass()
static DecodeStatus DecodeZPR4StridedRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 682 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
DecodeZPR_3bRegisterClass()
static DecodeStatus DecodeZPR_3bRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 607 of file AArch64Disassembler.cpp.
References DecodeZPRRegisterClass(), and Fail.
DecodeZPR_4bRegisterClass()
static DecodeStatus DecodeZPR_4bRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 599 of file AArch64Disassembler.cpp.
References DecodeZPRRegisterClass(), and Fail.
DecodeZPRRegisterClass()
static DecodeStatus DecodeZPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 587 of file AArch64Disassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, and Success.
Referenced by DecodeSVELogicalImmInstruction(), DecodeZPR_3bRegisterClass(), and DecodeZPR_4bRegisterClass().
isInvalidPState()
static bool isInvalidPState (uint64_t Op1, uint64_t Op2) static
Definition at line 1822 of file AArch64Disassembler.cpp.
Referenced by DecodeSystemPStateImm0_15Instruction(), and DecodeSystemPStateImm0_1Instruction().
LLVMInitializeAArch64Disassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAArch64Disassembler ()
Definition at line 393 of file AArch64Disassembler.cpp.
References createAArch64Disassembler(), createAArch64ExternalSymbolizer(), llvm::getTheAArch64_32Target(), llvm::getTheAArch64beTarget(), llvm::getTheAArch64leTarget(), llvm::getTheARM64_32Target(), llvm::getTheARM64Target(), llvm::TargetRegistry::RegisterMCDisassembler(), and llvm::TargetRegistry::RegisterMCSymbolizer().
Variable Documentation
MatrixZATileDecoderTable
const SmallVector<SmallVector<unsigned, 16>, 5> MatrixZATileDecoderTable static
Initial value:
= {
        {AArch64::ZAB0},
        {AArch64::ZAH0, AArch64::ZAH1},
        {AArch64::ZAS0, AArch64::ZAS1, AArch64::ZAS2, AArch64::ZAS3},
        {AArch64::ZAD0, AArch64::ZAD1, AArch64::ZAD2, AArch64::ZAD3,
         AArch64::ZAD4, AArch64::ZAD5, AArch64::ZAD6, AArch64::ZAD7},
        {AArch64::ZAQ0, AArch64::ZAQ1, AArch64::ZAQ2, AArch64::ZAQ3,
         AArch64::ZAQ4, AArch64::ZAQ5, AArch64::ZAQ6, AArch64::ZAQ7,
         AArch64::ZAQ8, AArch64::ZAQ9, AArch64::ZAQ10, AArch64::ZAQ11,
         AArch64::ZAQ12, AArch64::ZAQ13, AArch64::ZAQ14, AArch64::ZAQ15}}
Definition at line 705 of file AArch64Disassembler.cpp.
Referenced by DecodeMatrixTile().