LLVM: lib/Target/AArch64/AArch64TargetTransformInfo.cpp File Reference
AArch64TargetTransformInfo.cpp File Reference
#include "AArch64TargetTransformInfo.h"
#include "AArch64ExpandImm.h"
#include "AArch64PerfectShuffle.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "llvm/Analysis/IVDescriptors.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/CostTable.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include "llvm/Transforms/Vectorize/LoopVectorizationLegality.h"
#include <algorithm>
#include <optional>
Macros
#define DEBUG_TYPE "aarch64tti"
Functions
static std::optional< Instruction * > processPhiNode (InstCombiner &IC, IntrinsicInst &II)
The function will remove redundant reinterprets casting in the presence of the control flow.
static std::optional< Instruction * > tryCombineFromSVBoolBinOp (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineConvertFromSVBool (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVESel (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVEDup (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVEDupX (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVECmpNE (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVELast (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVECondLast (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineRDFFR (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVECntElts (InstCombiner &IC, IntrinsicInst &II, unsigned NumElts)
static std::optional< Instruction * > instCombineSVEPTest (InstCombiner &IC, IntrinsicInst &II)
template<Intrinsic::ID MulOpc, typename Intrinsic::ID FuseOpc>
static std::optional< Instruction * > instCombineSVEVectorFuseMulAddSub (InstCombiner &IC, IntrinsicInst &II, bool MergeIntoAddendOp)
static bool isAllActivePredicate (Value *Pred)
static std::optional< Instruction * > instCombineSVELD1 (InstCombiner &IC, IntrinsicInst &II, const DataLayout &DL)
static std::optional< Instruction * > instCombineSVEST1 (InstCombiner &IC, IntrinsicInst &II, const DataLayout &DL)
static Instruction::BinaryOps intrinsicIDToBinOpCode (unsigned Intrinsic)
static std::optional< Instruction * > instCombineSVEVectorBinOp (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVEVectorAdd (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVEVectorSub (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVEVectorMul (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVEUnpack (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVETBL (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVEZip (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineLD1GatherIndex (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineST1ScatterIndex (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVESDIV (InstCombiner &IC, IntrinsicInst &II)
bool SimplifyValuePattern (SmallVector< Value * > &Vec, bool AllowPoison)
static std::optional< Instruction * > instCombineSVEDupqLane (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineMaxMinNM (InstCombiner &IC, IntrinsicInst &II)
static std::optional< Instruction * > instCombineSVESrshl (InstCombiner &IC, IntrinsicInst &II)
static unsigned getSVEGatherScatterOverhead (unsigned Opcode)
static void getFalkorUnrollingPreferences (Loop *L, ScalarEvolution &SE, TargetTransformInfo::UnrollingPreferences &UP)
Variables
static cl::opt< bool > EnableFalkorHWPFUnrollFix ("enable-falkor-hwpf-unroll-fix", cl::init(true), cl::Hidden)
static cl::opt< unsigned > SVEGatherOverhead ("sve-gather-overhead", cl::init(10), cl::Hidden)
static cl::opt< unsigned > SVEScatterOverhead ("sve-scatter-overhead", cl::init(10), cl::Hidden)
TailFoldingKind TailFoldingKindLoc
cl::opt< TailFoldingKind, true, cl::parser< std::string > > SVETailFolding ("sve-tail-folding", cl::desc("Control the use of vectorisation using tail-folding for SVE:" "\ndisabled No loop types will vectorize using tail-folding" "\ndefault Uses the default tail-folding settings for the target " "CPU" "\nall All legal loop types will vectorize using tail-folding" "\nsimple Use tail-folding for simple loops (not reductions or " "recurrences)" "\nreductions Use tail-folding for loops containing reductions" "\nrecurrences Use tail-folding for loops containing fixed order " "recurrences"), cl::location(TailFoldingKindLoc))
static cl::opt< bool > EnableFixedwidthAutovecInStreamingMode ("enable-fixedwidth-autovec-in-streaming-mode", cl::init(false), cl::Hidden)
static cl::opt< bool > EnableScalableAutovecInStreamingMode ("enable-scalable-autovec-in-streaming-mode", cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64tti"
Definition at line 31 of file AArch64TargetTransformInfo.cpp.
Function Documentation
getFalkorUnrollingPreferences()
static void getFalkorUnrollingPreferences (Loop * L, ScalarEvolution & SE, TargetTransformInfo::UnrollingPreferences & UP) static
Definition at line 2685 of file AArch64TargetTransformInfo.cpp.
References BB, llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::dbgs(), llvm::LoadInst::getPointerOperand(), llvm::ScalarEvolution::getSCEV(), I, llvm::SCEVAddRecExpr::isAffine(), llvm::Loop::isLoopInvariant(), LLVM_DEBUG, llvm::Log2_32(), and llvm::TargetTransformInfo::UnrollingPreferences::MaxCount.
Referenced by llvm::AArch64TTIImpl::getUnrollingPreferences().
getSVEGatherScatterOverhead()
static unsigned getSVEGatherScatterOverhead (unsigned Opcode) static
Definition at line 2536 of file AArch64TargetTransformInfo.cpp.
References llvm::SPII::Load, SVEGatherOverhead, and SVEScatterOverhead.
Referenced by llvm::AArch64TTIImpl::getGatherScatterOpCost().
instCombineConvertFromSVBool()
static std::optional<Instruction *> instCombineConvertFromSVBool (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 627 of file AArch64TargetTransformInfo.cpp.
References llvm::CallBase::getArgOperand(), llvm::User::getOperand(), llvm::Value::getType(), llvm::SmallVectorImpl< T >::insert(), processPhiNode(), llvm::InstCombiner::replaceInstUsesWith(), and tryCombineFromSVBoolBinOp().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineLD1GatherIndex()
static std::optional<Instruction *> instCombineLD1GatherIndex (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1340 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::ConstantAggregateZero::get(), llvm::Value::getContext(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), Ptr, llvm::InstCombiner::replaceInstUsesWith(), and llvm::Value::takeName().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineMaxMinNM()
static std::optional<Instruction *> instCombineMaxMinNM (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1532 of file AArch64TargetTransformInfo.cpp.
References B, llvm::CallBase::getArgOperand(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineRDFFR()
static std::optional<Instruction *> instCombineRDFFR (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 939 of file AArch64TargetTransformInfo.cpp.
References llvm::LegalityPredicates::all(), Builder, llvm::ConstantInt::get(), llvm::Value::getContext(), llvm::Type::getInt32Ty(), llvm::Value::getType(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineST1ScatterIndex()
static std::optional<Instruction *> instCombineST1ScatterIndex (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1373 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::InstCombiner::eraseInstFromFunction(), llvm::Value::getContext(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::User::getOperand(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), and Ptr.
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVECmpNE()
static std::optional<Instruction *> instCombineSVECmpNE (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 718 of file AArch64TargetTransformInfo.cpp.
References llvm::LegalityPredicates::all(), Arg, Builder, llvm::ConstantInt::get(), llvm::ScalableVectorType::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Constant::getNullValue(), llvm::getSplatValue(), llvm::Value::getType(), I, llvm::BitmaskEnumDetail::Mask(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::AArch64::SVEBitsPerBlock.
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVECntElts()
static std::optional<Instruction *> instCombineSVECntElts (InstCombiner & IC, IntrinsicInst & II, unsigned NumElts) static
Definition at line 957 of file AArch64TargetTransformInfo.cpp.
References llvm::LegalityPredicates::all(), Builder, llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::getNumElementsFromSVEPredPattern(), llvm::Value::getType(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVECondLast()
static std::optional<Instruction *> instCombineSVECondLast (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 895 of file AArch64TargetTransformInfo.cpp.
References Builder, Fallback, llvm::VectorType::get(), llvm::CallBase::getArgOperand(), getBitWidth(), llvm::Value::getContext(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Value::getType(), llvm::Type::isIntegerTy(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEDup()
static std::optional<Instruction *> instCombineSVEDup (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 682 of file AArch64TargetTransformInfo.cpp.
References llvm::InsertElementInst::Create(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Type::getInt64Ty(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), Insert, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEDupqLane()
static std::optional<Instruction *> instCombineSVEDupqLane (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1468 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::ConstantInt::get(), llvm::ConstantAggregateZero::get(), llvm::ScalableVectorType::get(), llvm::PoisonValue::get(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::Value::getType(), I, llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), and SimplifyValuePattern().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEDupX()
static std::optional<Instruction *> instCombineSVEDupX (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 706 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Value::getType(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::Value::takeName().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVELast()
static std::optional<Instruction *> instCombineSVELast (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 819 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::ExtractElementInst::Create(), llvm::BinaryOperator::CreateWithCopiedFlags(), llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Type::getInt64Ty(), llvm::IntrinsicInst::getIntrinsicID(), llvm::getNumElementsFromSVEPredPattern(), llvm::getSplatValue(), llvm::Value::getType(), llvm::isSplatValue(), LHS, llvm::PatternMatch::m_BinOp(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), and RHS.
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVELD1()
static std::optional<Instruction *> instCombineSVELD1 (InstCombiner & IC, IntrinsicInst & II, const DataLayout & DL) static
Definition at line 1114 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::Instruction::copyMetadata(), DL, llvm::ConstantAggregateZero::get(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::Value::getPointerAlignment(), llvm::Type::getPointerTo(), llvm::Value::getType(), isAllActivePredicate(), llvm::SPII::Load, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEPTest()
static std::optional<Instruction *> instCombineSVEPTest (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 979 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Value::getType(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVESDIV()
static std::optional<Instruction *> instCombineSVESDIV (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1405 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::ConstantInt::get(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::getSplatValue(), llvm::Value::getType(), llvm::ConstantInt::getValue(), Int32Ty, llvm::APInt::isNegatedPowerOf2(), llvm::APInt::isPowerOf2(), llvm::APInt::logBase2(), llvm::SISrcMods::NEG, llvm::APInt::negate(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVESel()
static std::optional<Instruction *> instCombineSVESel (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 674 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::User::getOperand(), llvm::InstCombiner::replaceInstUsesWith(), and Select.
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVESrshl()
static std::optional<Instruction *> instCombineSVESrshl (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1542 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::User::getOperand(), llvm::Value::getType(), isAllActivePredicate(), llvm::AArch64_AM::LSL, llvm::PatternMatch::m_NonNegative(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::InstCombiner::replaceInstUsesWith(), and Shift.
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEST1()
static std::optional<Instruction *> instCombineSVEST1 (InstCombiner & IC, IntrinsicInst & II, const DataLayout & DL) static
Definition at line 1137 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::Instruction::copyMetadata(), DL, llvm::InstCombiner::eraseInstFromFunction(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::Value::getPointerAlignment(), llvm::Type::getPointerTo(), llvm::Value::getType(), isAllActivePredicate(), and llvm::SPII::Store.
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVETBL()
static std::optional<Instruction *> instCombineSVETBL (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1299 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::Value::getContext(), llvm::VectorType::getElementCount(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::User::getOperand(), llvm::getSplatValue(), llvm::Value::getType(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEUnpack()
static std::optional<Instruction *> instCombineSVEUnpack (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1277 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::IntrinsicInst::getIntrinsicID(), llvm::getSplatValue(), llvm::Value::getType(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::Value::takeName().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEVectorAdd()
static std::optional<Instruction *> instCombineSVEVectorAdd (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1188 of file AArch64TargetTransformInfo.cpp.
References llvm::ISD::FMAD, instCombineSVEVectorBinOp(), and instCombineSVEVectorFuseMulAddSub().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEVectorBinOp()
static std::optional<Instruction *> instCombineSVEVectorBinOp (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1173 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::Value::getContext(), llvm::Instruction::getFastMathFlags(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), intrinsicIDToBinOpCode(), llvm::PatternMatch::match(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by instCombineSVEVectorAdd(), instCombineSVEVectorMul(), and instCombineSVEVectorSub().
instCombineSVEVectorFuseMulAddSub()
template<Intrinsic::ID MulOpc, typename Intrinsic::ID FuseOpc> static std::optional<Instruction *> instCombineSVEVectorFuseMulAddSub (InstCombiner & IC, IntrinsicInst & II, bool MergeIntoAddendOp) static
Definition at line 1052 of file AArch64TargetTransformInfo.cpp.
References llvm::FastMathFlags::allowContract(), Builder, llvm::Value::getContext(), llvm::Instruction::getFastMathFlags(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::Type::isFPOrFPVectorTy(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), Mul, P, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by instCombineSVEVectorAdd(), and instCombineSVEVectorSub().
instCombineSVEVectorMul()
static std::optional<Instruction *> instCombineSVEVectorMul (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1230 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::Value::getContext(), llvm::User::getOperand(), llvm::getSplatValue(), I, instCombineSVEVectorBinOp(), llvm::PatternMatch::m_FPOne(), llvm::PatternMatch::m_One(), llvm::PatternMatch::match(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEVectorSub()
static std::optional<Instruction *> instCombineSVEVectorSub (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1211 of file AArch64TargetTransformInfo.cpp.
References instCombineSVEVectorBinOp(), and instCombineSVEVectorFuseMulAddSub().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
instCombineSVEZip()
static std::optional<Instruction *> instCombineSVEZip (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 1324 of file AArch64TargetTransformInfo.cpp.
References B, llvm::CallBase::getArgOperand(), llvm::IntrinsicInst::getIntrinsicID(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::AArch64TTIImpl::instCombineIntrinsic().
intrinsicIDToBinOpCode()
static Instruction::BinaryOps intrinsicIDToBinOpCode (unsigned Intrinsic) static
Definition at line 1159 of file AArch64TargetTransformInfo.cpp.
Referenced by instCombineSVEVectorBinOp().
isAllActivePredicate()
static bool isAllActivePredicate (Value * Pred) static
Definition at line 1097 of file AArch64TargetTransformInfo.cpp.
References llvm::Value::getType(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by instCombineSVELD1(), instCombineSVESrshl(), and instCombineSVEST1().
processPhiNode()
static std::optional<Instruction *> processPhiNode (InstCombiner & IC, IntrinsicInst & II) static
The function will remove redundant reinterprets casting in the presence of the control flow.
Definition at line 527 of file AArch64TargetTransformInfo.cpp.
References llvm::PHINode::addIncoming(), assert(), Builder, llvm::CallBase::getArgOperand(), llvm::Value::getType(), I, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by instCombineConvertFromSVBool().
SimplifyValuePattern()
bool SimplifyValuePattern (SmallVector< Value * > & Vec, bool AllowPoison)
Definition at line 1439 of file AArch64TargetTransformInfo.cpp.
References llvm::isPowerOf2_64(), LHS, llvm::SmallVectorImpl< T >::resize(), RHS, and llvm::ARMII::VecSize.
Referenced by instCombineSVEDupqLane().
tryCombineFromSVBoolBinOp()
static std::optional<Instruction *> tryCombineFromSVBoolBinOp (InstCombiner & IC, IntrinsicInst & II) static
Definition at line 575 of file AArch64TargetTransformInfo.cpp.
References Builder, llvm::Value::getContext(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::InstCombiner::replaceInstUsesWith().
Referenced by instCombineConvertFromSVBool().
Variable Documentation
EnableFalkorHWPFUnrollFix
cl::opt<bool> EnableFalkorHWPFUnrollFix("enable-falkor-hwpf-unroll-fix", cl::init(true), cl::Hidden) static
Referenced by llvm::AArch64TTIImpl::getUnrollingPreferences().
EnableFixedwidthAutovecInStreamingMode
cl::opt<bool> EnableFixedwidthAutovecInStreamingMode("enable-fixedwidth-autovec-in-streaming-mode", cl::init(false), cl::Hidden) static
Referenced by llvm::AArch64TTIImpl::getRegisterBitWidth().
EnableScalableAutovecInStreamingMode
cl::opt<bool> EnableScalableAutovecInStreamingMode("enable-scalable-autovec-in-streaming-mode", cl::init(false), cl::Hidden) static
Referenced by llvm::AArch64TTIImpl::getRegisterBitWidth().
SVEGatherOverhead
cl::opt<unsigned> SVEGatherOverhead("sve-gather-overhead", cl::init(10), cl::Hidden) static
Referenced by getSVEGatherScatterOverhead().
SVEScatterOverhead
cl::opt<unsigned> SVEScatterOverhead("sve-scatter-overhead", cl::init(10), cl::Hidden) static
Referenced by getSVEGatherScatterOverhead().
SVETailFolding
cl::opt<TailFoldingKind, true, cl::parser<std::string> > SVETailFolding("sve-tail-folding", cl::desc("Control the use of vectorisation using tail-folding for SVE:" "\ndisabled No loop types will vectorize using tail-folding" "\ndefault Uses the default tail-folding settings for the target " "CPU" "\nall All legal loop types will vectorize using tail-folding" "\nsimple Use tail-folding for simple loops (not reductions or " "recurrences)" "\nreductions Use tail-folding for loops containing reductions" "\nrecurrences Use tail-folding for loops containing fixed order " "recurrences"), cl::location(TailFoldingKindLoc))
TailFoldingKindLoc
TailFoldingKind TailFoldingKindLoc
Definition at line 95 of file AArch64TargetTransformInfo.cpp.
Referenced by llvm::AArch64TTIImpl::preferPredicateOverEpilogue().