LLVM: lib/Target/AArch64/AArch64MachineScheduler.cpp File Reference
AArch64MachineScheduler.cpp File Reference
#include "AArch64MachineScheduler.h"
#include "AArch64InstrInfo.h"
#include "AArch64Subtarget.h"
#include "MCTargetDesc/AArch64MCTargetDesc.h"
Functions
static bool needReorderStoreMI (const MachineInstr *MI)
static bool mayOverlapWrite (const MachineInstr &MI0, const MachineInstr &MI1, int64_t &Off0, int64_t &Off1)
Function Documentation
mayOverlapWrite()
static bool mayOverlapWrite (const MachineInstr & MI0, const MachineInstr & MI1, int64_t & Off0, int64_t & Off1) static
Definition at line 36 of file AArch64MachineScheduler.cpp.
References llvm::MachineOperand::getImm(), llvm::AArch64InstrInfo::getLdStBaseOp(), llvm::AArch64InstrInfo::getLdStOffsetOp(), llvm::AArch64InstrInfo::getMemScale(), llvm::MachineInstr::getOpcode(), llvm::AArch64InstrInfo::hasUnscaledLdStOffset(), llvm::MachineOperand::isIdenticalTo(), llvm::AArch64InstrInfo::isPairedLdSt(), and MI.
Referenced by llvm::AArch64PostRASchedStrategy::tryCandidate().
needReorderStoreMI()
static bool needReorderStoreMI (const MachineInstr * MI) static
Definition at line 16 of file AArch64MachineScheduler.cpp.
References llvm::AArch64InstrInfo::getLdStOffsetOp(), llvm::MachineOperand::isImm(), and MI.
Referenced by llvm::AArch64PostRASchedStrategy::tryCandidate().