LLVM: lib/Target/AArch64/AArch64CallingConvention.cpp File Reference
AArch64CallingConvention.cpp File Reference
#include "AArch64CallingConvention.h"
#include "AArch64.h"
#include "AArch64InstrInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/IR/CallingConv.h"
#include "AArch64GenCallingConv.inc"
Functions
static bool finishStackBlock (SmallVectorImpl< CCValAssign > &PendingMembers, MVT LocVT, ISD::ArgFlagsTy &ArgFlags, CCState &State, Align SlotAlign)
static bool CC_AArch64_Custom_Stack_Block (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
The Darwin variadic PCS places anonymous arguments in 8-byte stack slots.
static bool CC_AArch64_Custom_Block (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
Given an [N x Ty] block, it should be passed in a consecutive sequence of registers.
Variables
static const MCPhysReg XRegList []
static const MCPhysReg HRegList []
static const MCPhysReg SRegList []
static const MCPhysReg DRegList []
static const MCPhysReg QRegList []
static const MCPhysReg ZRegList []
Function Documentation
CC_AArch64_Custom_Block()
static bool CC_AArch64_Custom_Block (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Given an [N x Ty] block, it should be passed in a consecutive sequence of registers.
If no such sequence is available, mark the rest of the registers of that type as used and place the argument on the stack.
Definition at line 123 of file AArch64CallingConvention.cpp.
References llvm::CCState::addLoc(), llvm::CCValAssign::AExtUpper, Align, llvm::alignTo(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateRegBlock(), assert(), DRegList, llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, finishStackBlock(), llvm::MachineFunction::getDataLayout(), llvm::CCState::getMachineFunction(), llvm::ISD::ArgFlagsTy::getNonZeroMemAlign(), llvm::CCValAssign::getPending(), llvm::CCState::getPendingLocs(), llvm::CCValAssign::getReg(), llvm::DataLayout::getStackAlignment(), llvm::MachineFunction::getSubtarget(), HRegList, llvm::MVT::i32, llvm::MVT::i64, Info, llvm::MVT::is128BitVector(), llvm::MVT::is32BitVector(), llvm::MVT::is64BitVector(), llvm::ISD::ArgFlagsTy::isInConsecutiveRegsLast(), llvm::MVT::isScalableVector(), llvm::AArch64Subtarget::isTargetDarwin(), llvm::AArch64Subtarget::isTargetILP32(), llvm::AArch64Subtarget::isTargetMachO(), llvm::max(), llvm::min(), QRegList, llvm::MVT::SimpleTy, SRegList, XRegList, llvm::CCValAssign::ZExt, and ZRegList.
CC_AArch64_Custom_Stack_Block()
static bool CC_AArch64_Custom_Stack_Block (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
The Darwin variadic PCS places anonymous arguments in 8-byte stack slots.
An [N x Ty] type must still be contiguous in memory though.
Definition at line 104 of file AArch64CallingConvention.cpp.
References Align, finishStackBlock(), llvm::CCValAssign::getPending(), llvm::CCState::getPendingLocs(), and llvm::ISD::ArgFlagsTy::isInConsecutiveRegsLast().
finishStackBlock()
static bool finishStackBlock (SmallVectorImpl< CCValAssign > & PendingMembers, MVT LocVT, ISD::ArgFlagsTy & ArgFlags, CCState & State, Align SlotAlign) static
Definition at line 42 of file AArch64CallingConvention.cpp.
References llvm::CCState::addLoc(), Align, llvm::CCState::AllocateReg(), llvm::CCState::AllocateStack(), llvm::AArch64TargetLowering::CCAssignFnForCall(), llvm::SmallVectorImpl< T >::clear(), llvm::CCState::DeallocateReg(), llvm::CCValAssign::Full, llvm::CCState::getCallingConv(), llvm::CCState::getMachineFunction(), llvm::MVT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::AArch64Subtarget::getTargetLowering(), I, llvm::CCState::isAllocated(), llvm::MVT::isScalableVector(), llvm_unreachable, llvm::ISD::ArgFlagsTy::setInConsecutiveRegs(), llvm::ISD::ArgFlagsTy::setInConsecutiveRegsLast(), and ZRegList.
Referenced by CC_AArch64_Custom_Block(), and CC_AArch64_Custom_Stack_Block().
Variable Documentation
DRegList
const MCPhysReg DRegList[] static
Initial value:
= {AArch64::D0, AArch64::D1, AArch64::D2,
                                     AArch64::D3, AArch64::D4, AArch64::D5,
                                     AArch64::D6, AArch64::D7}
Definition at line 32 of file AArch64CallingConvention.cpp.
Referenced by CC_AArch64_Custom_Block().
HRegList
const MCPhysReg HRegList[] static
Initial value:
= {AArch64::H0, AArch64::H1, AArch64::H2,
                                     AArch64::H3, AArch64::H4, AArch64::H5,
                                     AArch64::H6, AArch64::H7}
Definition at line 26 of file AArch64CallingConvention.cpp.
Referenced by CC_AArch64_Custom_Block().
QRegList
const MCPhysReg QRegList[] static
Initial value:
= {AArch64::Q0, AArch64::Q1, AArch64::Q2,
                                     AArch64::Q3, AArch64::Q4, AArch64::Q5,
                                     AArch64::Q6, AArch64::Q7}
Definition at line 35 of file AArch64CallingConvention.cpp.
Referenced by CC_AArch64_Custom_Block().
SRegList
const MCPhysReg SRegList[] static
Initial value:
= {AArch64::S0, AArch64::S1, AArch64::S2,
                                     AArch64::S3, AArch64::S4, AArch64::S5,
                                     AArch64::S6, AArch64::S7}
Definition at line 29 of file AArch64CallingConvention.cpp.
Referenced by CC_AArch64_Custom_Block().
XRegList
const MCPhysReg XRegList[] static
Initial value:
= {AArch64::X0, AArch64::X1, AArch64::X2,
                                     AArch64::X3, AArch64::X4, AArch64::X5,
                                     AArch64::X6, AArch64::X7}
Definition at line 23 of file AArch64CallingConvention.cpp.
Referenced by CC_AArch64_Custom_Block().
ZRegList
const MCPhysReg ZRegList[] static
Initial value:
= {AArch64::Z0, AArch64::Z1, AArch64::Z2,
                                     AArch64::Z3, AArch64::Z4, AArch64::Z5,
                                     AArch64::Z6, AArch64::Z7}
Definition at line 38 of file AArch64CallingConvention.cpp.
Referenced by CC_AArch64_Custom_Block(), and finishStackBlock().