LLVM: lib/Target/AArch64/AArch64GlobalsTagging.cpp File Reference
AArch64GlobalsTagging.cpp File Reference
#include "AArch64.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <set>
Functions
static bool shouldTagGlobal (GlobalVariable &G)
static void tagGlobalDefinition (Module &M, GlobalVariable *G)
INITIALIZE_PASS_BEGIN (AArch64GlobalsTagging, "aarch64-globals-tagging", "AArch64 Globals Tagging Pass", false, false) INITIALIZE_PASS_END(AArch64GlobalsTagging
Variables
static const Align kTagGranuleSize = Align(16)
aarch64 globals tagging
aarch64 globals AArch64 Globals Tagging Pass
aarch64 globals AArch64 Globals Tagging false
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AArch64GlobalsTagging , "aarch64-globals-tagging" , "AArch64 Globals Tagging Pass" , false , false)
shouldTagGlobal()
static bool shouldTagGlobal (GlobalVariable & G) static
Definition at line 29 of file AArch64GlobalsTagging.cpp.
References assert(), and G.
tagGlobalDefinition()
static void tagGlobalDefinition (Module & M, GlobalVariable * G) static
Definition at line 68 of file AArch64GlobalsTagging.cpp.
References llvm::alignTo(), G, llvm::ConstantDataArray::get(), llvm::ConstantStruct::getAnon(), llvm::Value::getType(), kTagGranuleSize, M, llvm::max(), llvm::GlobalValue::None, and uint64_t.
Variable Documentation
false
aarch64 globals AArch64 Globals Tagging false
Definition at line 138 of file AArch64GlobalsTagging.cpp.
kTagGranuleSize
const Align kTagGranuleSize = Align(16) static
Definition at line 27 of file AArch64GlobalsTagging.cpp.
Referenced by tagGlobalDefinition().
Pass
aarch64 globals AArch64 Globals Tagging Pass
Definition at line 138 of file AArch64GlobalsTagging.cpp.
tagging
aarch64 globals tagging
Definition at line 137 of file AArch64GlobalsTagging.cpp.