LLVM: lib/Target/AMDGPU/AMDGPUInstCombineIntrinsic.cpp File Reference
AMDGPUInstCombineIntrinsic.cpp File Reference
#include "AMDGPUInstrInfo.h"
#include "AMDGPUTargetTransformInfo.h"
#include "GCNSubtarget.h"
#include "llvm/ADT/FloatingPointMode.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include <optional>
#include "InstCombineTables.inc"
Macros
#define DEBUG_TYPE "AMDGPUtti"
#define GET_AMDGPUImageDMaskIntrinsicTable_IMPL
Functions
static APFloat fmed3AMDGCN (const APFloat &Src0, const APFloat &Src1, const APFloat &Src2)
static bool canSafelyConvertTo16Bit (Value &V, bool IsFloat)
static Value * convertTo16Bit (Value &V, InstCombiner::BuilderTy &Builder)
static std::optional< Instruction * > modifyIntrinsicCall (IntrinsicInst &OldIntr, Instruction &InstToReplace, unsigned NewIntr, InstCombiner &IC, std::function< void(SmallVectorImpl< Value * > &, SmallVectorImpl< Type * > &)> Func)
Applies Func(OldIntr.Args, OldIntr.ArgTys), creates intrinsic call with modified arguments (based on OldIntr) and replaces InstToReplace with this newly created intrinsic call.
static std::optional< Instruction * > simplifyAMDGCNImageIntrinsic (const GCNSubtarget *ST, const AMDGPU::ImageDimIntrinsicInfo *ImageDimIntr, IntrinsicInst &II, InstCombiner &IC)
static Value * simplifyAMDGCNMemoryIntrinsicDemanded (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, int DMaskIdx=-1)
Implement SimplifyDemandedVectorElts for amdgcn buffer and image intrinsics.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "AMDGPUtti"
Definition at line 27 of file AMDGPUInstCombineIntrinsic.cpp.
GET_AMDGPUImageDMaskIntrinsicTable_IMPL
#define GET_AMDGPUImageDMaskIntrinsicTable_IMPL
Definition at line 35 of file AMDGPUInstCombineIntrinsic.cpp.
Function Documentation
canSafelyConvertTo16Bit()
static bool canSafelyConvertTo16Bit (Value & V, bool IsFloat) static
Definition at line 65 of file AMDGPUInstCombineIntrinsic.cpp.
References llvm::APFloat::convert(), llvm::APInt::getActiveBits(), llvm::Value::getType(), llvm::APFloatBase::IEEEhalf(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_FPExt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), and llvm::APFloatBase::rmTowardZero.
Referenced by simplifyAMDGCNImageIntrinsic().
convertTo16Bit()
static Value* convertTo16Bit (Value & V, InstCombiner::BuilderTy & Builder) static
Definition at line 103 of file AMDGPUInstCombineIntrinsic.cpp.
References Builder, llvm::Value::getContext(), llvm::Type::getHalfTy(), llvm::Type::getInt16Ty(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), and llvm_unreachable.
fmed3AMDGCN()
static APFloat fmed3AMDGCN (const APFloat & Src0, const APFloat & Src1, const APFloat & Src2) static
Definition at line 44 of file AMDGPUInstCombineIntrinsic.cpp.
References assert(), llvm::APFloatBase::cmpEqual, llvm::APFloatBase::cmpUnordered, llvm::APFloat::compare(), and llvm::maxnum().
Referenced by llvm::GCNTTIImpl::instCombineIntrinsic().
modifyIntrinsicCall()
static std::optional<Instruction *> modifyIntrinsicCall (IntrinsicInst & OldIntr, Instruction & InstToReplace, unsigned NewIntr, InstCombiner & IC, std::function< void(SmallVectorImpl< Value * > &, SmallVectorImpl< Type * > &)> Func) static
Applies Func(OldIntr.Args, OldIntr.ArgTys), creates intrinsic call with modified arguments (based on OldIntr) and replaces InstToReplace with this newly created intrinsic call.
Definition at line 118 of file AMDGPUInstCombineIntrinsic.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::CallBase::args(), llvm::InstCombiner::Builder, llvm::Instruction::copyFastMathFlags(), llvm::Instruction::copyMetadata(), llvm::IRBuilderBase::CreateCall(), llvm::InstCombiner::eraseInstFromFunction(), llvm::CallBase::getCalledFunction(), llvm::Intrinsic::getDeclaration(), llvm::Intrinsic::getIntrinsicSignature(), llvm::Instruction::getModule(), llvm::Value::getType(), I, llvm::Type::isVoidTy(), llvm::InstCombiner::replaceInstUsesWith(), and llvm::Value::takeName().
Referenced by simplifyAMDGCNImageIntrinsic().
simplifyAMDGCNImageIntrinsic()
static std::optional<Instruction *> simplifyAMDGCNImageIntrinsic (const GCNSubtarget * ST, const AMDGPU::ImageDimIntrinsicInfo * ImageDimIntr, IntrinsicInst & II, InstCombiner & IC) static
Definition at line 154 of file AMDGPUInstCombineIntrinsic.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), canSafelyConvertTo16Bit(), for, llvm::Value::getContext(), llvm::Type::getHalfTy(), llvm::AMDGPU::getImageDimIntrinsicByBaseOpcode(), llvm::Type::getInt16Ty(), llvm::IntrinsicInst::getIntrinsicID(), llvm::AMDGPU::getMIMGBaseOpcodeInfo(), llvm::AMDGPU::getMIMGBiasMappingInfo(), llvm::AMDGPU::getMIMGLZMappingInfo(), llvm::AMDGPU::getMIMGMIPMappingInfo(), llvm::AMDGPU::getMIMGOffsetMappingInfo(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::Value::hasOneUse(), if(), llvm::Type::isFloatingPointTy(), llvm::Type::isHalfTy(), modifyIntrinsicCall(), llvm::AMDGPU::MIMGBaseOpcodeInfo::Sampler, llvm::ARM_MB::ST, and llvm::Instruction::user_back().
Referenced by llvm::GCNTTIImpl::instCombineIntrinsic().
simplifyAMDGCNMemoryIntrinsicDemanded()
static Value* simplifyAMDGCNMemoryIntrinsicDemanded (InstCombiner & IC, IntrinsicInst & II, APInt DemandedElts, int DMaskIdx = -1) static
Implement SimplifyDemandedVectorElts for amdgcn buffer and image intrinsics.
Note: This only supports non-TFE/LWE image intrinsic calls; those have struct returns.
Definition at line 1065 of file AMDGPUInstCombineIntrinsic.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::CallBase::args(), llvm::tgtok::Bit, llvm::InstCombiner::Builder, llvm::Instruction::copyMetadata(), llvm::APInt::countPopulation(), llvm::APInt::countTrailingZeros(), llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateCall(), llvm::IRBuilderBase::CreateInsertElement(), llvm::IRBuilderBase::CreateShuffleVector(), llvm::ConstantInt::get(), llvm::FixedVectorType::get(), llvm::UndefValue::get(), llvm::APInt::getActiveBits(), llvm::CallBase::getCalledFunction(), llvm::InstCombiner::getDataLayout(), llvm::Intrinsic::getDeclaration(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Intrinsic::getIntrinsicSignature(), llvm::Instruction::getModule(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::ConstantInt::getZExtValue(), llvm::APInt::isMask(), llvm::Offset, llvm::popcount(), llvm::CallBase::setArgOperand(), llvm::IRBuilderBase::SetInsertPoint(), llvm::Shuffle, and llvm::Value::takeName().
Referenced by llvm::GCNTTIImpl::simplifyDemandedVectorEltsIntrinsic().