LLVM: lib/Target/AMDGPU/AMDGPUPrintfRuntimeBinding.cpp File Reference
AMDGPUPrintfRuntimeBinding.cpp File Reference
#include "AMDGPU.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "printfToRuntime"
#define DWORD_ALIGN 4
Functions
INITIALIZE_PASS_BEGIN (AMDGPUPrintfRuntimeBinding, "amdgpu-printf-runtime-binding", "AMDGPU Printf lowering", false, false) INITIALIZE_PASS_END(AMDGPUPrintfRuntimeBinding
ModulePass * llvm::createAMDGPUPrintfRuntimeBinding ()
static bool shouldPrintAsStr (char Specifier, Type *OpType)
constexpr StringLiteral NonLiteralStr ("???")
static StringRef getAsConstantStr (Value *V)
static void diagnoseInvalidFormatString (const CallBase *CI)
Variables
amdgpu printf runtime binding
amdgpu printf runtime AMDGPU Printf lowering
amdgpu printf runtime AMDGPU Printf false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "printfToRuntime"
Definition at line 36 of file AMDGPUPrintfRuntimeBinding.cpp.
DWORD_ALIGN
#define DWORD_ALIGN 4
Definition at line 37 of file AMDGPUPrintfRuntimeBinding.cpp.
Function Documentation
diagnoseInvalidFormatString()
static void diagnoseInvalidFormatString (const CallBase * CI) static
Definition at line 151 of file AMDGPUPrintfRuntimeBinding.cpp.
References llvm::LLVMContext::diagnose(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::Instruction::getParent(), and llvm::BasicBlock::getParent().
getAsConstantStr()
static StringRef getAsConstantStr (Value * V) static
Definition at line 143 of file AMDGPUPrintfRuntimeBinding.cpp.
References llvm::getConstantStringInfo(), NonLiteralStr(), and S.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPUPrintfRuntimeBinding , "amdgpu-printf-runtime-binding" , "AMDGPU Printf lowering" , false , false)
NonLiteralStr()
constexpr StringLiteral NonLiteralStr ("???") constexpr
Referenced by getAsConstantStr().
shouldPrintAsStr()
static bool shouldPrintAsStr (char Specifier, Type * OpType) static
Definition at line 136 of file AMDGPUPrintfRuntimeBinding.cpp.
Variable Documentation
binding
amdgpu printf runtime binding
Definition at line 89 of file AMDGPUPrintfRuntimeBinding.cpp.
false
amdgpu printf runtime AMDGPU Printf false
Definition at line 90 of file AMDGPUPrintfRuntimeBinding.cpp.
lowering
amdgpu printf runtime AMDGPU Printf lowering
Definition at line 90 of file AMDGPUPrintfRuntimeBinding.cpp.