LLVM: lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp File Reference
AMDGPUInstructionSelector.cpp File Reference
#include "AMDGPUInstructionSelector.h"
#include "AMDGPU.h"
#include "AMDGPUGlobalISelUtils.h"
#include "AMDGPUInstrInfo.h"
#include "AMDGPURegisterBankInfo.h"
#include "AMDGPUTargetMachine.h"
#include "SIMachineFunctionInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/CodeGen/GlobalISel/GISelKnownBits.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelectorImpl.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include <optional>
#include "AMDGPUGenGlobalISel.inc"
Macros
#define DEBUG_TYPE "amdgpu-isel"
#define GET_GLOBALISEL_IMPL
#define AMDGPUSubtarget GCNSubtarget
#define GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Functions
static unsigned getLogicalBitOpcode (unsigned Opc, bool Is64)
static int getV_CMPOpcode (CmpInst::Predicate P, unsigned Size, const GCNSubtarget &ST)
static unsigned gwsIntrinToOpcode (unsigned IntrID)
static bool parseTexFail (uint64_t TexFailCtrl, bool &TFE, bool &LWE, bool &IsTexFail)
static int sizeToSubRegIndex (unsigned Size)
static bool shouldUseAndMask (unsigned Size, unsigned &Mask)
static bool isConstant (const MachineInstr &MI)
static bool isVCmpResult (Register Reg, MachineRegisterInfo &MRI)
static std::pair< Register, unsigned > computeIndirectRegIndex (MachineRegisterInfo &MRI, const SIRegisterInfo &TRI, const TargetRegisterClass *SuperRC, Register IdxReg, unsigned EltSize, GISelKnownBits &KnownBits)
Return the register to use for the index value, and the subregister to use for the indirectly accessed register.
static Register matchZeroExtendFromS32 (MachineRegisterInfo &MRI, Register Reg)
Match a zero extend from a 32-bit value to 64-bits.
static Register getWaveAddress (const MachineInstr *Def)
static void addZeroImm (MachineInstrBuilder &MIB)
static Register buildRSRC (MachineIRBuilder &B, MachineRegisterInfo &MRI, uint32_t FormatLo, uint32_t FormatHi, Register BasePtr)
Return a resource descriptor for use with an arbitrary 64-bit pointer.
static Register buildAddr64RSrc (MachineIRBuilder &B, MachineRegisterInfo &MRI, const SIInstrInfo &TII, Register BasePtr)
static Register buildOffsetSrc (MachineIRBuilder &B, MachineRegisterInfo &MRI, const SIInstrInfo &TII, Register BasePtr)
static std::optional< uint64_t > getConstantZext32Val (Register Reg, const MachineRegisterInfo &MRI)
Get an immediate that must be 32-bits, and treated as zero extended.
static MachineInstr * stripBitCast (MachineInstr *MI, MachineRegisterInfo &MRI)
static MachineInstr * isExtractHiElt (MachineInstr *Inst, MachineRegisterInfo &MRI)
Variables
static cl::opt< bool > AllowRiskySelect ("amdgpu-global-isel-risky-select", cl::desc("Allow GlobalISel to select cases that are likely to not work yet"), cl::init(false), cl::ReallyHidden)
Detailed Description
This file implements the targeting of the InstructionSelector class for AMDGPU.
Todo:
This should be generated by TableGen.
Definition in file AMDGPUInstructionSelector.cpp.
Macro Definition Documentation
AMDGPUSubtarget
#define AMDGPUSubtarget GCNSubtarget
Definition at line 43 of file AMDGPUInstructionSelector.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-isel"
Definition at line 31 of file AMDGPUInstructionSelector.cpp.
GET_GLOBALISEL_IMPL
#define GET_GLOBALISEL_IMPL
Definition at line 42 of file AMDGPUInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_PREDICATES_INIT
GET_GLOBALISEL_TEMPORARIES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Function Documentation
addZeroImm()
static void addZeroImm (MachineInstrBuilder & MIB) static
Definition at line 4488 of file AMDGPUInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm().
buildAddr64RSrc()
static Register buildAddr64RSrc (MachineIRBuilder & B, MachineRegisterInfo & MRI, const SIInstrInfo & TII, Register BasePtr) static
Definition at line 4537 of file AMDGPUInstructionSelector.cpp.
References B, buildRSRC(), llvm::Hi_32(), MRI, TII, and uint64_t.
buildOffsetSrc()
static Register buildOffsetSrc (MachineIRBuilder & B, MachineRegisterInfo & MRI, const SIInstrInfo & TII, Register BasePtr) static
Definition at line 4546 of file AMDGPUInstructionSelector.cpp.
References B, buildRSRC(), llvm::Hi_32(), MRI, TII, and uint64_t.
buildRSRC()
static Register buildRSRC (MachineIRBuilder & B, MachineRegisterInfo & MRI, uint32_t FormatLo, uint32_t FormatHi, Register BasePtr) static
Return a resource descriptor for use with an arbitrary 64-bit pointer.
If BasePtr is not valid, a null base pointer will be used.
Definition at line 4494 of file AMDGPUInstructionSelector.cpp.
References B, llvm::MachineRegisterInfo::createVirtualRegister(), and MRI.
Referenced by buildAddr64RSrc(), and buildOffsetSrc().
computeIndirectRegIndex()
static std::pair<Register, unsigned> computeIndirectRegIndex (MachineRegisterInfo & MRI, const SIRegisterInfo & TRI, const TargetRegisterClass * SuperRC, Register IdxReg, unsigned EltSize, GISelKnownBits & KnownBits) static
Return the register to use for the index value, and the subregister to use for the indirectly accessed register.
Definition at line 2897 of file AMDGPUInstructionSelector.cpp.
References assert(), llvm::AMDGPU::getBaseWithConstantOffset(), MRI, llvm::Offset, llvm::ArrayRef< T >::size(), and TRI.
getConstantZext32Val()
static std::optional<uint64_t> getConstantZext32Val (Register Reg, const MachineRegisterInfo & MRI) static
Get an immediate that must be 32-bits, and treated as zero extended.
Definition at line 4809 of file AMDGPUInstructionSelector.cpp.
References llvm::getIConstantVRegSExtVal(), llvm::Lo_32(), and MRI.
getLogicalBitOpcode()
static unsigned getLogicalBitOpcode (unsigned Opc, bool Is64) static
Definition at line 271 of file AMDGPUInstructionSelector.cpp.
References llvm_unreachable.
getV_CMPOpcode()
static int getV_CMPOpcode (CmpInst::Predicate P, unsigned Size, const GCNSubtarget & ST) static
Definition at line 1129 of file AMDGPUInstructionSelector.cpp.
References llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm_unreachable, P, Select, and llvm::ARM_MB::ST.
getWaveAddress()
static Register getWaveAddress (const MachineInstr * Def) static
Definition at line 4310 of file AMDGPUInstructionSelector.cpp.
References llvm::tgtok::Def.
gwsIntrinToOpcode()
static unsigned gwsIntrinToOpcode (unsigned IntrID) static
Definition at line 1576 of file AMDGPUInstructionSelector.cpp.
References llvm_unreachable.
isConstant()
static bool isConstant (const MachineInstr & MI) static
Definition at line 2605 of file AMDGPUInstructionSelector.cpp.
References MI.
Referenced by llvm::buildModuleSummaryIndex(), llvm::MDBuilder::createTBAANode(), llvm::HexagonInstrInfo::expandPostRAPseudo(), getMemcpyLoadsAndStores(), and runIPSCCP().
isExtractHiElt()
static MachineInstr* isExtractHiElt (MachineInstr * Inst, MachineRegisterInfo & MRI) static
Definition at line 4878 of file AMDGPUInstructionSelector.cpp.
References assert(), llvm::LLT::fixed_vector(), llvm::getDefIgnoringCopies(), llvm::getIConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getShuffleMask(), llvm::MachineRegisterInfo::getType(), LHS, llvm::BitmaskEnumDetail::Mask(), MRI, and stripBitCast().
isVCmpResult()
static bool isVCmpResult (Register Reg, MachineRegisterInfo & MRI) static
Definition at line 2696 of file AMDGPUInstructionSelector.cpp.
References llvm::MachineRegisterInfo::getUniqueVRegDef(), MI, and MRI.
matchZeroExtendFromS32()
static Register matchZeroExtendFromS32 (MachineRegisterInfo & MRI, Register Reg) static
Match a zero extend from a 32-bit value to 64-bits.
Definition at line 3164 of file AMDGPUInstructionSelector.cpp.
References assert(), llvm::tgtok::Def, llvm::getDefIgnoringCopies(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_ZeroInt(), llvm::MIPatternMatch::mi_match(), MRI, and llvm::LLT::scalar().
parseTexFail()
static bool parseTexFail (uint64_t TexFailCtrl, bool & TFE, bool & LWE, bool & IsTexFail) static
Definition at line 1731 of file AMDGPUInstructionSelector.cpp.
References uint64_t, and x2().
shouldUseAndMask()
static bool shouldUseAndMask (unsigned Size, unsigned & Mask) static
Returns
true if a bitmask for Size bits will be an inline immediate.
Definition at line 2265 of file AMDGPUInstructionSelector.cpp.
References llvm::BitmaskEnumDetail::Mask().
sizeToSubRegIndex()
static int sizeToSubRegIndex (unsigned Size) static
Definition at line 2123 of file AMDGPUInstructionSelector.cpp.
References llvm::bit_ceil().
stripBitCast()
static MachineInstr* stripBitCast (MachineInstr * MI, MachineRegisterInfo & MRI) static
Definition at line 4870 of file AMDGPUInstructionSelector.cpp.
References llvm::getDefIgnoringCopies(), MI, and MRI.
Referenced by isExtractHiElt().
Variable Documentation
AllowRiskySelect
cl::opt<bool> AllowRiskySelect("amdgpu-global-isel-risky-select", cl::desc("Allow GlobalISel to select cases that are likely to not work yet"), cl::init(false), cl::ReallyHidden) static