LLVM: lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCTargetDesc.cpp File Reference
AMDGPUMCTargetDesc.cpp File Reference
#include "AMDGPUMCTargetDesc.h"
#include "AMDGPUELFStreamer.h"
#include "AMDGPUInstPrinter.h"
#include "AMDGPUMCAsmInfo.h"
#include "AMDGPUTargetStreamer.h"
#include "R600InstPrinter.h"
#include "R600MCTargetDesc.h"
#include "TargetInfo/AMDGPUTargetInfo.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "AMDGPUGenInstrInfo.inc"
#include "AMDGPUGenSubtargetInfo.inc"
#include "R600GenSubtargetInfo.inc"
#include "AMDGPUGenRegisterInfo.inc"
#include "R600GenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define NoSchedModel NoSchedModelR600
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createAMDGPUMCInstrInfo ()
static MCRegisterInfo * createAMDGPUMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createAMDGPUMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCInstPrinter * createAMDGPUMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createAMDGPUAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool isVerboseAsm)
static MCTargetStreamer * createAMDGPUObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCTargetStreamer * createAMDGPUNullTargetStreamer (MCStreamer &S)
static MCStreamer * createMCStreamer (const Triple &T, MCContext &Context, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCInstrAnalysis * createAMDGPUMCInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUTargetMC ()
Detailed Description
This file provides AMDGPU specific target descriptions.
Definition in file AMDGPUMCTargetDesc.cpp.
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 39 of file AMDGPUMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 38 of file AMDGPUMCTargetDesc.cpp.
GET_REGINFO_MC_DESC [1/2]
#define GET_REGINFO_MC_DESC
Definition at line 53 of file AMDGPUMCTargetDesc.cpp.
GET_REGINFO_MC_DESC [2/2]
#define GET_REGINFO_MC_DESC
Definition at line 53 of file AMDGPUMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC [1/2]
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 46 of file AMDGPUMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC [2/2]
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 46 of file AMDGPUMCTargetDesc.cpp.
NoSchedModel
#define NoSchedModel NoSchedModelR600
Definition at line 45 of file AMDGPUMCTargetDesc.cpp.
Function Documentation
createAMDGPUAsmTargetStreamer()
static MCTargetStreamer* createAMDGPUAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint, bool isVerboseAsm) static
Definition at line 95 of file AMDGPUMCTargetDesc.cpp.
References OS, and S.
Referenced by LLVMInitializeAMDGPUTargetMC().
createAMDGPUMCInstPrinter()
static MCInstPrinter* createAMDGPUMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 84 of file AMDGPUMCTargetDesc.cpp.
References MRI, and llvm::Triple::r600.
Referenced by LLVMInitializeAMDGPUTargetMC().
createAMDGPUMCInstrAnalysis()
static MCInstrAnalysis* createAMDGPUMCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 146 of file AMDGPUMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeAMDGPUTargetMC().
createAMDGPUMCInstrInfo()
static MCInstrInfo* createAMDGPUMCInstrInfo () static
Definition at line 56 of file AMDGPUMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeAMDGPUTargetMC().
createAMDGPUMCRegisterInfo()
static MCRegisterInfo* createAMDGPUMCRegisterInfo (const Triple & TT) static
Definition at line 62 of file AMDGPUMCTargetDesc.cpp.
References llvm::Triple::r600, and X.
Referenced by LLVMInitializeAMDGPUTargetMC().
createAMDGPUMCSubtargetInfo()
static MCSubtargetInfo* createAMDGPUMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 78 of file AMDGPUMCTargetDesc.cpp.
References llvm::X86AS::FS, and llvm::Triple::r600.
Referenced by LLVMInitializeAMDGPUTargetMC().
createAMDGPUNullTargetStreamer()
static MCTargetStreamer* createAMDGPUNullTargetStreamer (MCStreamer & S) static
Definition at line 108 of file AMDGPUMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeAMDGPUTargetMC().
createAMDGPUObjectTargetStreamer()
static MCTargetStreamer* createAMDGPUObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 102 of file AMDGPUMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeAMDGPUTargetMC().
createMCStreamer()
static MCStreamer* createMCStreamer (const Triple & T, MCContext & Context, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 112 of file AMDGPUMCTargetDesc.cpp.
References Context, llvm::createAMDGPUELFStreamer(), Emitter, and move.
Referenced by LLVMInitializeAMDGPUTargetMC().
LLVMInitializeAMDGPUTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUTargetMC ()
Definition at line 150 of file AMDGPUMCTargetDesc.cpp.
References llvm::createAMDGPUAsmBackend(), createAMDGPUAsmTargetStreamer(), createAMDGPUMCInstPrinter(), createAMDGPUMCInstrAnalysis(), createAMDGPUMCInstrInfo(), createAMDGPUMCRegisterInfo(), createAMDGPUMCSubtargetInfo(), createAMDGPUNullTargetStreamer(), createAMDGPUObjectTargetStreamer(), createMCStreamer(), llvm::createR600MCCodeEmitter(), llvm::createR600MCInstrInfo(), llvm::createSIMCCodeEmitter(), llvm::getTheAMDGPUTarget(), llvm::getTheGCNTarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), and X.