LLVM: lib/Target/AMDGPU/MCA/AMDGPUCustomBehaviour.cpp File Reference
AMDGPUCustomBehaviour.cpp File Reference
#include "AMDGPUCustomBehaviour.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIInstrInfo.h"
#include "TargetInfo/AMDGPUTargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/WithColor.h"
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
llvm::mca
Functions
static CustomBehaviour * createAMDGPUCustomBehaviour (const MCSubtargetInfo &STI, const mca::SourceMgr &SrcMgr, const MCInstrInfo &MCII)
static InstrPostProcess * createAMDGPUInstrPostProcess (const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUTargetMCA ()
Extern function to initialize the targets for the AMDGPU backend.
Detailed Description
This file implements methods from the AMDGPUCustomBehaviour class.
Definition in file AMDGPUCustomBehaviour.cpp.
Function Documentation
createAMDGPUCustomBehaviour()
static CustomBehaviour* createAMDGPUCustomBehaviour (const MCSubtargetInfo & STI, const mca::SourceMgr & SrcMgr, const MCInstrInfo & MCII) static
Definition at line 336 of file AMDGPUCustomBehaviour.cpp.
References llvm::SrcMgr.
Referenced by LLVMInitializeAMDGPUTargetMCA().
createAMDGPUInstrPostProcess()
static InstrPostProcess* createAMDGPUInstrPostProcess (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) static
Definition at line 343 of file AMDGPUCustomBehaviour.cpp.
Referenced by LLVMInitializeAMDGPUTargetMCA().
LLVMInitializeAMDGPUTargetMCA()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUTargetMCA ()
Extern function to initialize the targets for the AMDGPU backend.
Definition at line 350 of file AMDGPUCustomBehaviour.cpp.
References createAMDGPUCustomBehaviour(), createAMDGPUInstrPostProcess(), llvm::getTheAMDGPUTarget(), llvm::getTheGCNTarget(), llvm::TargetRegistry::RegisterCustomBehaviour(), and llvm::TargetRegistry::RegisterInstrPostProcess().