LLVM: lib/Transforms/IPO/Annotation2Metadata.cpp File Reference
Annotation2Metadata.cpp File Reference
#include "llvm/Transforms/IPO/Annotation2Metadata.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/IPO.h"
Macros
#define DEBUG_TYPE "annotation2metadata"
Functions
static bool convertAnnotation2Metadata (Module &M)
INITIALIZE_PASS_BEGIN (Annotation2MetadataLegacy, DEBUG_TYPE, "Annotation2Metadata", false, false) INITIALIZE_PASS_END(Annotation2MetadataLegacy
Variables
DEBUG_TYPE
Annotation2Metadata
false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "annotation2metadata"
Definition at line 26 of file Annotation2Metadata.cpp.
Function Documentation
convertAnnotation2Metadata()
static bool convertAnnotation2Metadata (Module & M) static
Definition at line 28 of file Annotation2Metadata.cpp.
References llvm::OptimizationRemarkEmitter::allowExtraAnalysis(), I, llvm::instructions(), and M.
Referenced by llvm::Annotation2MetadataPass::run().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (Annotation2MetadataLegacy , DEBUG_TYPE , "Annotation2Metadata" , false , false)
Variable Documentation
Annotation2Metadata
Annotation2Metadata
Definition at line 89 of file Annotation2Metadata.cpp.
DEBUG_TYPE
DEBUG_TYPE
Definition at line 88 of file Annotation2Metadata.cpp.
false
false
Definition at line 89 of file Annotation2Metadata.cpp.