LLVM: lib/Transforms/Scalar/AnnotationRemarks.cpp File Reference
AnnotationRemarks.cpp File Reference
#include "llvm/Transforms/Scalar/AnnotationRemarks.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/MemoryOpRemark.h"
Macros
#define DEBUG_TYPE "annotation-remarks"
#define REMARK_PASS DEBUG_TYPE
Functions
static void tryEmitAutoInitRemark (ArrayRef< Instruction * > Instructions, OptimizationRemarkEmitter &ORE, const TargetLibraryInfo &TLI)
static void runImpl (Function &F, const TargetLibraryInfo &TLI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "annotation-remarks"
Definition at line 25 of file AnnotationRemarks.cpp.
REMARK_PASS
#define REMARK_PASS DEBUG_TYPE
Definition at line 26 of file AnnotationRemarks.cpp.
Function Documentation
runImpl()
static void runImpl (Function & F, const TargetLibraryInfo & TLI) static
Definition at line 43 of file AnnotationRemarks.cpp.
References llvm::OptimizationRemarkEmitter::allowExtraAnalysis(), llvm::OptimizationRemarkEmitter::emit(), F, I, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), llvm::instructions(), REMARK_PASS, and tryEmitAutoInitRemark().
Referenced by llvm::AnnotationRemarksPass::run().
tryEmitAutoInitRemark()
static void tryEmitAutoInitRemark (ArrayRef< Instruction * > Instructions, OptimizationRemarkEmitter & ORE, const TargetLibraryInfo & TLI) static
Definition at line 28 of file AnnotationRemarks.cpp.
References llvm::AutoInitRemark::canHandle(), DL, F, I, Instructions, llvm::Remark, and REMARK_PASS.
Referenced by runImpl().