LLVM: lib/Target/ARC/MCTargetDesc/ARCMCTargetDesc.cpp File Reference
ARCMCTargetDesc.cpp File Reference
#include "ARCMCTargetDesc.h"
#include "ARCInstPrinter.h"
#include "ARCMCAsmInfo.h"
#include "ARCTargetStreamer.h"
#include "TargetInfo/ARCTargetInfo.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "ARCGenInstrInfo.inc"
#include "ARCGenSubtargetInfo.inc"
#include "ARCGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createARCMCInstrInfo ()
static MCRegisterInfo * createARCMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createARCMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCAsmInfo * createARCMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstPrinter * createARCMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool isVerboseAsm)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARCTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 29 of file ARCMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 28 of file ARCMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 35 of file ARCMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 32 of file ARCMCTargetDesc.cpp.
Function Documentation
createARCMCAsmInfo()
static MCAsmInfo* createARCMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 55 of file ARCMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), and llvm::MCCFIInstruction::cfiDefCfa().
Referenced by LLVMInitializeARCTargetMC().
createARCMCInstPrinter()
static MCInstPrinter* createARCMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 67 of file ARCMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeARCTargetMC().
createARCMCInstrInfo()
static MCInstrInfo* createARCMCInstrInfo () static
Definition at line 38 of file ARCMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeARCTargetMC().
createARCMCRegisterInfo()
static MCRegisterInfo* createARCMCRegisterInfo (const Triple & TT) static
Definition at line 44 of file ARCMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeARCTargetMC().
createARCMCSubtargetInfo()
static MCSubtargetInfo* createARCMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 50 of file ARCMCTargetDesc.cpp.
References llvm::X86AS::FS.
Referenced by LLVMInitializeARCTargetMC().
createTargetAsmStreamer()
static MCTargetStreamer* createTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint, bool isVerboseAsm) static
Definition at line 78 of file ARCMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeARCTargetMC().
LLVMInitializeARCTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARCTargetMC ()
Definition at line 86 of file ARCMCTargetDesc.cpp.
References createARCMCAsmInfo(), createARCMCInstPrinter(), createARCMCInstrInfo(), createARCMCRegisterInfo(), createARCMCSubtargetInfo(), createTargetAsmStreamer(), llvm::getTheARCTarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), and X.