LLVM: lib/Target/ARC/ARCTargetMachine.cpp File Reference
ARCTargetMachine.cpp File Reference
#include "ARCTargetMachine.h"
#include "ARC.h"
#include "ARCMachineFunctionInfo.h"
#include "ARCTargetTransformInfo.h"
#include "TargetInfo/ARCTargetInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include <optional>
Functions
static Reloc::Model getRelocModel (std::optional< Reloc::Model > RM)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARCTarget ()
Function Documentation
getRelocModel()
static Reloc::Model getRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 25 of file ARCTargetMachine.cpp.
References llvm::AArch64::RM, and llvm::Reloc::Static.
LLVMInitializeARCTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARCTarget ()
Definition at line 90 of file ARCTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheARCTarget(), llvm::initializeARCDAGToDAGISelPass(), and X.