LLVM: lib/Target/ARM/MCTargetDesc/ARMELFStreamer.cpp File Reference
ARMELFStreamer.cpp File Reference
#include "ARMRegisterInfo.h"
#include "ARMUnwindOpAsm.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCFragment.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Support/ARMBuildAttributes.h"
#include "llvm/Support/ARMEHABI.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/TargetParser.h"
#include <algorithm>
#include <cassert>
#include <climits>
#include <cstddef>
#include <cstdint>
#include <string>
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static std::string GetAEABIUnwindPersonalityName (unsigned Index)
static std::pair< unsigned, unsigned > collectHWRegs (const MCRegisterInfo &MRI, unsigned Idx, const SmallVectorImpl< unsigned > &RegList, bool IsVector, uint32_t &Mask_)
MCTargetStreamer * llvm::createARMTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool isVerboseAsm)
MCTargetStreamer * llvm::createARMNullTargetStreamer (MCStreamer &S)
MCTargetStreamer * llvm::createARMObjectTargetELFStreamer (MCStreamer &S)
MCELFStreamer * llvm::createARMELFStreamer (MCContext &Context, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter, bool RelaxAll, bool IsThumb, bool IsAndroid)
Function Documentation
collectHWRegs()
static std::pair<unsigned, unsigned> collectHWRegs (const MCRegisterInfo & MRI, unsigned Idx, const SmallVectorImpl< unsigned > & RegList, bool IsVector, uint32_t & Mask_) static
Definition at line 1403 of file ARMELFStreamer.cpp.
References assert(), llvm::tgtok::Bit, llvm::BitmaskEnumDetail::Mask(), and MRI.
GetAEABIUnwindPersonalityName()
static std::string GetAEABIUnwindPersonalityName (unsigned Index) static
Definition at line 60 of file ARMELFStreamer.cpp.
References assert(), and llvm::ARM::EHABI::NUM_PERSONALITY_INDEX.