LLVM: lib/TargetParser/ARMTargetParser.cpp File Reference
ARMTargetParser.cpp File Reference
#include "llvm/TargetParser/ARMTargetParser.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/TargetParser/ARMTargetParserCommon.h"
#include "llvm/TargetParser/Triple.h"
#include <cctype>
#include "llvm/TargetParser/ARMTargetParser.def"
Macros
#define ARM_CPU_NAME(NAME, ID, DEFAULT_FPU, IS_DEFAULT, DEFAULT_EXT) .Case(NAME, DEFAULT_FPU)
#define ARM_CPU_NAME(NAME, ID, DEFAULT_FPU, IS_DEFAULT, DEFAULT_EXT)
Functions
static StringRef getHWDivSynonym (StringRef HWDiv)
static ARM::ProfileKind getProfileKind (ARM::ArchKind AK)
static bool stripNegationPrefix (StringRef &Name)
static unsigned findDoublePrecisionFPU (unsigned InputFPUKind)
Macro Definition Documentation
ARM_CPU_NAME [1/2]
#define ARM_CPU_NAME (NAME, ID, DEFAULT_FPU, IS_DEFAULT, DEFAULT_EXT) .Case(NAME, DEFAULT_FPU)
ARM_CPU_NAME [2/2]
#define ARM_CPU_NAME (NAME, ID, DEFAULT_FPU, IS_DEFAULT, DEFAULT_EXT)
Value:
  .Case(NAME,                                                                  \
        ARMArchNames[static_cast<unsigned>(ArchKind::ID)].ArchBaseExtensions | \
            DEFAULT_EXT)
Function Documentation
findDoublePrecisionFPU()
static unsigned findDoublePrecisionFPU (unsigned InputFPUKind) static
Definition at line 365 of file ARMTargetParser.cpp.
References llvm::ARM::D16, llvm::LoongArch::FK_INVALID, llvm::ARM::FPUNames, llvm::ARM::FPUName::FPUVer, llvm::ARM::FPUName::NeonSupport, llvm::ARM::FPUName::Restriction, and llvm::ARM::SP_D16.
Referenced by llvm::ARM::appendArchExtFeatures().
getHWDivSynonym()
static StringRef getHWDivSynonym (StringRef HWDiv) static
Definition at line 22 of file ARMTargetParser.cpp.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
Referenced by llvm::ARM::parseHWDiv().
getProfileKind()
static ARM::ProfileKind getProfileKind (ARM::ArchKind AK) static
Definition at line 94 of file ARMTargetParser.cpp.
References llvm::ARM::A, llvm::AArch64::ARMV8_1A, llvm::AArch64::ARMV8_2A, llvm::AArch64::ARMV8_3A, llvm::AArch64::ARMV8_4A, llvm::AArch64::ARMV8_5A, llvm::AArch64::ARMV8_6A, llvm::AArch64::ARMV8_7A, llvm::AArch64::ARMV8_8A, llvm::AArch64::ARMV8_9A, llvm::AArch64::ARMV8A, llvm::AArch64::ARMV8R, llvm::AArch64::ARMV9_1A, llvm::AArch64::ARMV9_2A, llvm::AArch64::ARMV9_3A, llvm::AArch64::ARMV9_4A, llvm::AArch64::ARMV9A, llvm::ARM::INVALID, llvm_unreachable, llvm::ARM::M, and llvm::ARM::R.
Referenced by llvm::ARM::convertV9toV8(), and llvm::ARM::parseArchProfile().
stripNegationPrefix()
static bool stripNegationPrefix (StringRef & Name) static
Definition at line 347 of file ARMTargetParser.cpp.
Referenced by llvm::ARM::appendArchExtFeatures(), and llvm::ARM::getArchExtFeature().