LLVM: lib/MC/MCParser/AsmLexer.cpp File Reference
AsmLexer.cpp File Reference
#include "llvm/MC/MCParser/AsmLexer.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SaveAndRestore.h"
#include <cassert>
#include <cctype>
#include <cstdio>
#include <cstring>
#include <string>
#include <tuple>
#include <utility>
Functions
static bool isIdentifierChar (char C, bool AllowAt, bool AllowHash)
LexIdentifier: [a-zA-Z_$.@?][a-zA-Z0-9_$.#?]*.
static void SkipIgnoredIntegerSuffix (const char *&CurPtr)
static unsigned doHexLookAhead (const char *&CurPtr, unsigned DefaultRadix, bool LexHex)
static const char * findLastDigit (const char *CurPtr, unsigned DefaultRadix)
static AsmToken intToken (StringRef Ref, APInt &Value)
static std::string radixName (unsigned Radix)
Function Documentation
doHexLookAhead()
static unsigned doHexLookAhead (const char *& CurPtr, unsigned DefaultRadix, bool LexHex) static
Definition at line 265 of file AsmLexer.cpp.
References isDigit(), and isHexDigit().
findLastDigit()
static const char* findLastDigit (const char * CurPtr, unsigned DefaultRadix) static
Definition at line 290 of file AsmLexer.cpp.
intToken()
static AsmToken intToken (StringRef Ref, APInt & Value) static
Definition at line 297 of file AsmLexer.cpp.
References llvm::AsmToken::BigNum, llvm::AsmToken::Integer, and llvm::Ref.
isIdentifierChar()
static bool isIdentifierChar (char C, bool AllowAt, bool AllowHash) static
LexIdentifier: [a-zA-Z_$.@?][a-zA-Z0-9_$.#?]*.
Definition at line 148 of file AsmLexer.cpp.
radixName()
static std::string radixName (unsigned Radix) static
Definition at line 303 of file AsmLexer.cpp.
References llvm::to_string().
SkipIgnoredIntegerSuffix()
static void SkipIgnoredIntegerSuffix (const char *& CurPtr) static
Definition at line 253 of file AsmLexer.cpp.