LLVM: lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp File Reference
AsmPrinterInlineAsm.cpp File Reference
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static void EmitInlineAsmStr (const char *AsmStr, const MachineInstr *MI, MachineModuleInfo *MMI, const MCAsmInfo *MAI, AsmPrinter *AP, uint64_t LocCookie, raw_ostream &OS)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 42 of file AsmPrinterInlineAsm.cpp.
Function Documentation
EmitInlineAsmStr()
static void EmitInlineAsmStr (const char * AsmStr, const MachineInstr * MI, MachineModuleInfo * MMI, const MCAsmInfo * MAI, AsmPrinter * AP, uint64_t LocCookie, raw_ostream & OS) static
Definition at line 132 of file AsmPrinterInlineAsm.cpp.
References llvm::InlineAsm::AD_Intel, llvm::LLVMContext::emitError(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::MachineModuleInfo::getContext(), llvm::Module::getContext(), llvm::MCAsmInfo::getEmitGNUAsmStartIndentationMarker(), llvm::MachineModuleInfo::getModule(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineModuleInfo::getTarget(), isDigit(), llvm::InlineAsm::isMemKind(), llvm::AsmPrinter::MAI, MI, llvm::InlineAsm::MIOp_FirstOperand, llvm::AMDGPU::SendMsg::Msg, OS, llvm::MCSymbol::print(), llvm::AsmPrinter::PrintAsmMemoryOperand(), llvm::AsmPrinter::PrintAsmOperand(), llvm::AsmPrinter::PrintSpecial(), llvm::MCContext::registerInlineAsmLabel(), llvm::report_fatal_error(), llvm::LLVMTargetMachine::unqualifiedInlineAsmVariant(), and llvm::raw_ostream::write().