LLVM: lib/IR/Attributes.cpp File Reference
Attributes.cpp File Reference
#include "llvm/IR/Attributes.h"
#include "AttributeImpl.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ModRef.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <optional>
#include <string>
#include <tuple>
#include <utility>
#include "llvm/IR/Attributes.inc"
Classes
struct AttributeComparator
Attribute comparator that only compares attribute keys.
struct EnumAttr
struct StrBoolAttr
Macros
#define GET_ATTR_NAMES
#define ATTRIBUTE_ENUM(ENUM_NAME, DISPLAY_NAME) .Case(#DISPLAY_NAME, Attribute::ENUM_NAME)
#define GET_ATTR_NAMES
#define ATTRIBUTE_ENUM(ENUM_NAME, DISPLAY_NAME)
#define GET_ATTR_NAMES
#define ATTRIBUTE_ALL(ENUM_NAME, DISPLAY_NAME) .Case(#DISPLAY_NAME, true)
#define GET_ATTR_PROP_TABLE
#define GET_ATTR_NAMES
#define ATTRIBUTE_ENUM(ENUM_NAME, DISPLAY_NAME)
#define ATTRIBUTE_STRBOOL(ENUM_NAME, DISPLAY_NAME)
#define GET_ATTR_COMPAT_FUNC
Enumerations
enum AttributeProperty { FnAttr = (1 << 0), ParamAttr = (1 << 1), RetAttr = (1 << 2) }
Functions
static uint64_t packAllocSizeArgs (unsigned ElemSizeArg, const std::optional< unsigned > &NumElemsArg)
static std::pair< unsigned, std::optional< unsigned > > unpackAllocSizeArgs (uint64_t Num)
static uint64_t packVScaleRangeArgs (unsigned MinValue, std::optional< unsigned > MaxValue)
static std::pair< unsigned, std::optional< unsigned > > unpackVScaleRangeArgs (uint64_t Value)
static const char * getModRefStr (ModRefInfo MR)
static bool hasAttributeProperty (Attribute::AttrKind Kind, AttributeProperty Prop)
static unsigned attrIdxToArrayIdx (unsigned Index)
Map from AttributeList index to the internal array index.
template<typename K >
static void addAttributeImpl (SmallVectorImpl< Attribute > &Attrs, K Kind, Attribute Attr)
template<typename AttrClass >
static bool isEqual (const Function &Caller, const Function &Callee)
template<typename AttrClass >
static void setAND (Function &Caller, const Function &Callee)
Compute the logical AND of the attributes of the caller and the callee.
template<typename AttrClass >
static void setOR (Function &Caller, const Function &Callee)
Compute the logical OR of the attributes of the caller and the callee.
static void adjustCallerSSPLevel (Function &Caller, const Function &Callee)
If the inlined function had a higher stack protection level than the calling function, then bump up the caller's stack protection level.
static void adjustCallerStackProbes (Function &Caller, const Function &Callee)
If the inlined function required stack probes, then ensure that the calling function has those too.
static void adjustCallerStackProbeSize (Function &Caller, const Function &Callee)
If the inlined function defines the size of guard region on the stack, then ensure that the calling function defines a guard region that is no larger.
static void adjustMinLegalVectorWidth (Function &Caller, const Function &Callee)
If the inlined function defines a min legal vector width, then ensure the calling function has the same or larger min legal vector width.
static void adjustNullPointerValidAttr (Function &Caller, const Function &Callee)
If the inlined function has null_pointer_is_valid attribute, set this attribute in the caller post inlining.
Variables
static const unsigned AllocSizeNumElemsNotPresent = -1
Macro Definition Documentation
ATTRIBUTE_ALL
#define ATTRIBUTE_ALL (ENUM_NAME, DISPLAY_NAME) .Case(#DISPLAY_NAME, true)
ATTRIBUTE_ENUM [1/3]
#define ATTRIBUTE_ENUM (ENUM_NAME, DISPLAY_NAME) .Case(#DISPLAY_NAME, Attribute::ENUM_NAME)
Definition at line 2103 of file Attributes.cpp.
ATTRIBUTE_ENUM [2/3]
#define ATTRIBUTE_ENUM (ENUM_NAME, DISPLAY_NAME)
Value:
  case Attribute::ENUM_NAME:                                                   \
    return #DISPLAY_NAME;
Definition at line 2103 of file Attributes.cpp.
ATTRIBUTE_ENUM [3/3]
#define ATTRIBUTE_ENUM (ENUM_NAME, DISPLAY_NAME)
Value:
  struct ENUM_NAME##Attr : EnumAttr {                                          \
    static enum Attribute::AttrKind getKind() {                                \
      return llvm::Attribute::ENUM_NAME;                                       \
    }                                                                          \
  };
Definition at line 2103 of file Attributes.cpp.
ATTRIBUTE_STRBOOL
#define ATTRIBUTE_STRBOOL (ENUM_NAME, DISPLAY_NAME)
Value:
  struct ENUM_NAME##Attr : StrBoolAttr {                                       \
    static StringRef getKind() { return #DISPLAY_NAME; }                       \
  };
Definition at line 2109 of file Attributes.cpp.
GET_ATTR_COMPAT_FUNC
#define GET_ATTR_COMPAT_FUNC
Definition at line 2115 of file Attributes.cpp.
GET_ATTR_NAMES [1/4]
#define GET_ATTR_NAMES
Definition at line 2102 of file Attributes.cpp.
GET_ATTR_NAMES [2/4]
#define GET_ATTR_NAMES
Definition at line 2102 of file Attributes.cpp.
GET_ATTR_NAMES [3/4]
#define GET_ATTR_NAMES
Definition at line 2102 of file Attributes.cpp.
GET_ATTR_NAMES [4/4]
#define GET_ATTR_NAMES
Definition at line 2102 of file Attributes.cpp.
GET_ATTR_PROP_TABLE
#define GET_ATTR_PROP_TABLE
Definition at line 598 of file Attributes.cpp.
Enumeration Type Documentation
AttributeProperty
enum AttributeProperty
Enumerator
FnAttr
ParamAttr
RetAttr
Definition at line 592 of file Attributes.cpp.
Function Documentation
addAttributeImpl()
template<typename K > static void addAttributeImpl (SmallVectorImpl< Attribute > & Attrs, K Kind, Attribute Attr) static
Definition at line 1677 of file Attributes.cpp.
References Attrs, llvm::Function::end(), llvm::Function::insert(), llvm::lower_bound(), and std::swap().
Referenced by llvm::AttrBuilder::addAttribute().
adjustCallerSSPLevel()
static void adjustCallerSSPLevel (Function & Caller, const Function & Callee) static
If the inlined function had a higher stack protection level than the calling function, then bump up the caller's stack protection level.
Definition at line 1978 of file Attributes.cpp.
References llvm::AttributeMask::addAttribute(), and Callee.
adjustCallerStackProbes()
static void adjustCallerStackProbes (Function & Caller, const Function & Callee) static
If the inlined function required stack probes, then ensure that the calling function has those too.
Definition at line 2008 of file Attributes.cpp.
References Callee.
adjustCallerStackProbeSize()
static void adjustCallerStackProbeSize (Function & Caller, const Function & Callee) static
If the inlined function defines the size of guard region on the stack, then ensure that the calling function defines a guard region that is no larger.
Definition at line 2019 of file Attributes.cpp.
References Callee, llvm::StringRef::getAsInteger(), llvm::Attribute::getValueAsString(), llvm::Attribute::isValid(), and uint64_t.
adjustMinLegalVectorWidth()
static void adjustMinLegalVectorWidth (Function & Caller, const Function & Callee) static
If the inlined function defines a min legal vector width, then ensure the calling function has the same or larger min legal vector width.
If the caller has the attribute, but the callee doesn't, we need to remove the attribute from the caller since we can't make any guarantees about the caller's requirements. This function is called after the inlining decision has been made so we have to merge the attribute this way. Heuristics that would use min-legal-vector-width to determine inline compatibility would need to be handled as part of inline cost analysis.
Definition at line 2047 of file Attributes.cpp.
References Callee, llvm::StringRef::getAsInteger(), llvm::Attribute::getValueAsString(), llvm::Attribute::isValid(), and uint64_t.
adjustNullPointerValidAttr()
static void adjustNullPointerValidAttr (Function & Caller, const Function & Callee) static
If the inlined function has null_pointer_is_valid attribute, set this attribute in the caller post inlining.
Definition at line 2068 of file Attributes.cpp.
References Callee.
attrIdxToArrayIdx()
static unsigned attrIdxToArrayIdx (unsigned Index) static
Map from AttributeList index to the internal array index.
Adding one happens to work, because -1 wraps around to 0.
Definition at line 1043 of file Attributes.cpp.
Referenced by llvm::AttributeList::addParamAttribute(), llvm::AttributeListImpl::AttributeListImpl(), llvm::AttributeList::get(), llvm::AttributeList::getAttributes(), and llvm::AttributeList::removeAttributesAtIndex().
getModRefStr()
static const char* getModRefStr (ModRefInfo MR) static
Definition at line 399 of file Attributes.cpp.
References llvm_unreachable, llvm::Mod, llvm::ModRef, llvm::NoModRef, and llvm::Ref.
Referenced by llvm::Attribute::getAsString().
hasAttributeProperty()
static bool hasAttributeProperty (Attribute::AttrKind Kind, AttributeProperty Prop) static
Definition at line 601 of file Attributes.cpp.
References assert(), Index, and size.
Referenced by llvm::Attribute::canUseAsFnAttr(), llvm::Attribute::canUseAsParamAttr(), and llvm::Attribute::canUseAsRetAttr().
isEqual()
template<typename AttrClass > static bool isEqual (const Function & Caller, const Function & Callee) static
Definition at line 1947 of file Attributes.cpp.
References Callee.
Referenced by llvm::ImutAVLFactory< ImutInfo >::add_internal(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::clear(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::copyFrom(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::destroyAll(), llvm::ImutAVLTree< ImutInfo >::find(), llvm::SmallDenseMap< const llvm::RecurrenceDescriptor *, unsigned, N >::grow(), llvm::ImutAVLTree< ImutInfo >::isElementEqual(), llvm::DenseMapInfo< CachedHashStringRef >::isEqual(), llvm::DenseMapInfo< MCRegister >::isEqual(), llvm::DenseMapInfo< BasicBlockEdge >::isEqual(), llvm::DenseMapInfo< Register >::isEqual(), llvm::DenseMapInfo< WeakVH >::isEqual(), llvm::DenseMapInfo< std::pair< T, U > >::isEqual(), llvm::DenseMapInfo< orc::ExecutorAddr >::isEqual(), llvm::DenseMapInfo< AA::ValueAndContext >::isEqual(), llvm::DenseMapInfo< AA::ValueScope >::isEqual(), llvm::DenseMapInfo< PoisoningVH< T > >::isEqual(), llvm::DenseMapInfo< FunctionSummary::ConstVCall >::isEqual(), llvm::DenseMapInfo< TargetInstrInfo::RegSubRegPair >::isEqual(), llvm::DenseMapInfo< ReachabilityQueryInfo< ToTy > * >::isEqual(), llvm::DenseMapInfo< std::tuple< Ts... > >::isEqualImpl(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::moveFromOldBuckets(), llvm::rdf::RegisterAggr::operator==(), llvm::ImutAVLFactory< ImutInfo >::remove_internal(), and llvm::SmallDenseMap< const llvm::RecurrenceDescriptor *, unsigned, N >::swap().
packAllocSizeArgs()
static uint64_t packAllocSizeArgs (unsigned ElemSizeArg, const std::optional< unsigned > & NumElemsArg) static
Definition at line 57 of file Attributes.cpp.
References AllocSizeNumElemsNotPresent, assert(), and uint64_t.
Referenced by llvm::AttrBuilder::addAllocSizeAttr(), and llvm::Attribute::getWithAllocSizeArgs().
packVScaleRangeArgs()
static uint64_t packVScaleRangeArgs (unsigned MinValue, std::optional< unsigned > MaxValue) static
Definition at line 77 of file Attributes.cpp.
References uint64_t.
Referenced by llvm::AttrBuilder::addVScaleRangeAttr(), and llvm::Attribute::getWithVScaleRangeArgs().
setAND()
template<typename AttrClass > static void setAND (Function & Caller, const Function & Callee) static
Compute the logical AND of the attributes of the caller and the callee.
This function sets the caller's attribute to false if the callee's attribute is false.
Definition at line 1958 of file Attributes.cpp.
References Callee, and set.
setOR()
template<typename AttrClass > static void setOR (Function & Caller, const Function & Callee) static
Compute the logical OR of the attributes of the caller and the callee.
This function sets the caller's attribute to true if the callee's attribute is true.
Definition at line 1970 of file Attributes.cpp.
References Callee, and set.
unpackAllocSizeArgs()
static std::pair<unsigned, std::optional<unsigned> > unpackAllocSizeArgs (uint64_t Num) static
Definition at line 67 of file Attributes.cpp.
References AllocSizeNumElemsNotPresent, and llvm::max().
Referenced by llvm::Attribute::getAllocSizeArgs().
unpackVScaleRangeArgs()
static std::pair<unsigned, std::optional<unsigned> > unpackVScaleRangeArgs (uint64_t Value) static
Definition at line 83 of file Attributes.cpp.
References llvm::max().
Referenced by llvm::Attribute::getVScaleRangeMax(), and llvm::Attribute::getVScaleRangeMin().
Variable Documentation
AllocSizeNumElemsNotPresent
const unsigned AllocSizeNumElemsNotPresent = -1 static
Definition at line 55 of file Attributes.cpp.
Referenced by packAllocSizeArgs(), and unpackAllocSizeArgs().