LLVM: lib/Target/AVR/AVRISelDAGToDAG.cpp File Reference
AVRISelDAGToDAG.cpp File Reference
#include "AVR.h"
#include "AVRTargetMachine.h"
#include "MCTargetDesc/AVRMCTargetDesc.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "AVRGenDAGISel.inc"
Macros
#define DEBUG_TYPE "avr-isel"
#define PASS_NAME "AVR DAG->DAG Instruction Selection"
Functions
template<>
bool AVRDAGToDAGISel::select< ISD::FrameIndex > (SDNode *N)
template<>
bool AVRDAGToDAGISel::select< ISD::STORE > (SDNode *N)
template<>
bool AVRDAGToDAGISel::select< ISD::LOAD > (SDNode *N)
template<>
bool AVRDAGToDAGISel::select< AVRISD::CALL > (SDNode *N)
template<>
bool AVRDAGToDAGISel::select< ISD::BRIND > (SDNode *N)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "avr-isel"
Definition at line 22 of file AVRISelDAGToDAG.cpp.
PASS_NAME
#define PASS_NAME "AVR DAG->DAG Instruction Selection"
Definition at line 23 of file AVRISelDAGToDAG.cpp.
Function Documentation
AVRDAGToDAGISel::select< AVRISD::CALL >()
template<> bool AVRDAGToDAGISel::select< AVRISD::CALL > (SDNode * N)
Definition at line 440 of file AVRISelDAGToDAG.cpp.
References Callee, DL, llvm::numbers::e, llvm::SDValue::getValue(), llvm::MVT::Glue, i, llvm::MVT::i16, N, llvm::MVT::Other, llvm::ISD::TargetExternalSymbol, and llvm::ISD::TargetGlobalAddress.
AVRDAGToDAGISel::select< ISD::BRIND >()
template<> bool AVRDAGToDAGISel::select< ISD::BRIND > (SDNode * N)
Definition at line 481 of file AVRISelDAGToDAG.cpp.
References DL, N, and llvm::MVT::Other.
AVRDAGToDAGISel::select< ISD::FrameIndex >()
template<> bool AVRDAGToDAGISel::select< ISD::FrameIndex > (SDNode * N)
Definition at line 305 of file AVRISelDAGToDAG.cpp.
References DL, llvm::MVT::i16, and N.
AVRDAGToDAGISel::select< ISD::LOAD >()
template<> bool AVRDAGToDAGISel::select< ISD::LOAD > (SDNode * N)
Definition at line 356 of file AVRISelDAGToDAG.cpp.
References DL, llvm::AVR::getProgramMemoryBank(), llvm::SDValue::getValue(), llvm::MVT::i16, llvm::MVT::i8, llvm::AVR::isProgramMemoryAccess(), llvm::ARM_MB::LD, llvm_unreachable, N, NC, llvm::MVT::Other, Ptr, llvm::report_fatal_error(), and llvm::MVT::SimpleTy.
AVRDAGToDAGISel::select< ISD::STORE >()
template<> bool AVRDAGToDAGISel::select< ISD::STORE > (SDNode * N)
Definition at line 319 of file AVRISelDAGToDAG.cpp.
References DL, llvm::MVT::i16, int, N, llvm::Offset, llvm::MVT::Other, RN, and llvm::ARM_MB::ST.