LLVM: lib/Target/AVR/MCTargetDesc/AVRMCTargetDesc.cpp File Reference
AVRMCTargetDesc.cpp File Reference
#include "AVRMCTargetDesc.h"
#include "AVRELFStreamer.h"
#include "AVRInstPrinter.h"
#include "AVRMCAsmInfo.h"
#include "AVRMCELFStreamer.h"
#include "AVRTargetStreamer.h"
#include "TargetInfo/AVRTargetInfo.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "AVRGenInstrInfo.inc"
#include "AVRGenSubtargetInfo.inc"
#include "AVRGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCRegisterInfo * createAVRMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createAVRMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCInstPrinter * createAVRMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCStreamer * createMCStreamer (const Triple &T, MCContext &Context, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCTargetStreamer * createAVRObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCTargetStreamer * createMCAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool isVerboseAsm)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAVRTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 30 of file AVRMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 29 of file AVRMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 36 of file AVRMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 33 of file AVRMCTargetDesc.cpp.
Function Documentation
createAVRMCInstPrinter()
static MCInstPrinter* createAVRMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 60 of file AVRMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeAVRTargetMC().
createAVRMCRegisterInfo()
static MCRegisterInfo* createAVRMCRegisterInfo (const Triple & TT) static
Definition at line 48 of file AVRMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeAVRTargetMC().
createAVRMCSubtargetInfo()
static MCSubtargetInfo* createAVRMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 55 of file AVRMCTargetDesc.cpp.
References llvm::X86AS::FS.
Referenced by LLVMInitializeAVRTargetMC().
createAVRObjectTargetStreamer()
static MCTargetStreamer* createAVRObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 82 of file AVRMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeAVRTargetMC().
createMCAsmTargetStreamer()
static MCTargetStreamer* createMCAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint, bool isVerboseAsm) static
Definition at line 86 of file AVRMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeAVRTargetMC().
createMCStreamer()
static MCStreamer* createMCStreamer (const Triple & T, MCContext & Context, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 72 of file AVRMCTargetDesc.cpp.
References Context, llvm::createELFStreamer(), Emitter, and move.
Referenced by LLVMInitializeAVRTargetMC().
LLVMInitializeAVRTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAVRTargetMC ()
Definition at line 93 of file AVRMCTargetDesc.cpp.
References llvm::createAVRAsmBackend(), llvm::createAVRMCCodeEmitter(), createAVRMCInstPrinter(), llvm::createAVRMCInstrInfo(), createAVRMCRegisterInfo(), createAVRMCSubtargetInfo(), createAVRObjectTargetStreamer(), createMCAsmTargetStreamer(), createMCStreamer(), llvm::getTheAVRTarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), and X.