LLVM: lib/Analysis/BlockFrequencyInfoImpl.cpp File Reference
BlockFrequencyInfoImpl.cpp File Reference
#include "llvm/Analysis/BlockFrequencyInfoImpl.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/BlockFrequency.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/ScaledNumber.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <list>
#include <numeric>
#include <optional>
#include <utility>
#include <vector>
Classes
struct llvm::GraphTraits< IrreducibleGraph >
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "block-freq"
Functions
cl::opt< bool > llvm::CheckBFIUnknownBlockQueries ("check-bfi-unknown-block-queries", cl::init(false), cl::Hidden, cl::desc("Check if block frequency is queried for an unknown block " "for debugging missed BFI updates"))
cl::opt< bool > llvm::UseIterativeBFIInference ("use-iterative-bfi-inference", cl::Hidden, cl::desc("Apply an iterative post-processing to infer correct BFI counts"))
cl::opt< unsigned > llvm::IterativeBFIMaxIterationsPerBlock ("iterative-bfi-max-iterations-per-block", cl::init(1000), cl::Hidden, cl::desc("Iterative inference: maximum number of update iterations " "per block"))
cl::opt< double > llvm::IterativeBFIPrecision ("iterative-bfi-precision", cl::init(1e-12), cl::Hidden, cl::desc("Iterative inference: delta convergence precision; smaller values " "typically lead to better results at the cost of worsen runtime"))
static char getHexDigit (int N)
static void combineWeight (Weight &W, const Weight &OtherW)
static void combineWeightsBySorting (WeightList &Weights)
static void combineWeightsByHashing (WeightList &Weights)
static void combineWeights (WeightList &Weights)
static uint64_t shiftRightAndRound (uint64_t N, int Shift)
static void cleanup (BlockFrequencyInfoImplBase &BFI)
Clear all memory not needed downstream.
static void debugAssign (const BlockFrequencyInfoImplBase &BFI, const DitheringDistributer &D, const BlockNode &T, const BlockMass &M, const char *Desc)
static void convertFloatingToInteger (BlockFrequencyInfoImplBase &BFI, const Scaled64 &Min, const Scaled64 &Max)
static void unwrapLoop (BlockFrequencyInfoImplBase &BFI, LoopData &Loop)
Unwrap a loop package.
static void findIrreducibleHeaders (const BlockFrequencyInfoImplBase &BFI, const IrreducibleGraph &G, const std::vector< const IrreducibleGraph::IrrNode * > &SCC, LoopData::NodeList &Headers, LoopData::NodeList &Others)
Find extra irreducible headers.
static void createIrreducibleLoop (BlockFrequencyInfoImplBase &BFI, const IrreducibleGraph &G, LoopData *OuterLoop, std::list< LoopData >::iterator Insert, const std::vector< const IrreducibleGraph::IrrNode * > &SCC)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "block-freq"
Definition at line 40 of file BlockFrequencyInfoImpl.cpp.
Function Documentation
cleanup()
static void cleanup (BlockFrequencyInfoImplBase & BFI) static
Clear all memory not needed downstream.
Releases all memory not used downstream. In particular, saves Freqs.
Definition at line 303 of file BlockFrequencyInfoImpl.cpp.
References llvm::AMDGPUISD::BFI, and move.
Referenced by llvm::BlockFrequencyInfoImplBase::finalizeMetrics(), llvm::CrashRecoveryContext::registerCleanup(), and llvm::CrashRecoveryContext::unregisterCleanup().
combineWeight()
static void combineWeight (Weight & W, const Weight & OtherW) static
Definition at line 161 of file BlockFrequencyInfoImpl.cpp.
References assert(), UINT64_MAX, and llvm::RISCVFenceField::W.
Referenced by combineWeightsByHashing(), and combineWeightsBySorting().
combineWeights()
static void combineWeights (WeightList & Weights) static
Definition at line 217 of file BlockFrequencyInfoImpl.cpp.
References combineWeightsByHashing(), and combineWeightsBySorting().
Referenced by llvm::BlockFrequencyInfoImplBase::Distribution::normalize().
combineWeightsByHashing()
static void combineWeightsByHashing (WeightList & Weights) static
Definition at line 198 of file BlockFrequencyInfoImpl.cpp.
References combineWeight(), I, llvm::NextPowerOf2(), and llvm::RISCVFenceField::W.
Referenced by combineWeights().
combineWeightsBySorting()
static void combineWeightsBySorting (WeightList & Weights) static
Definition at line 177 of file BlockFrequencyInfoImpl.cpp.
References combineWeight(), E, I, llvm::RISCVFenceField::O, and llvm::sort().
Referenced by combineWeights().
convertFloatingToInteger()
static void convertFloatingToInteger (BlockFrequencyInfoImplBase & BFI, const Scaled64 & Min, const Scaled64 & Max) static
Definition at line 481 of file BlockFrequencyInfoImpl.cpp.
References llvm::AMDGPUISD::BFI, llvm::dbgs(), Index, llvm::ScaledNumber< DigitsT >::inverse(), LLVM_DEBUG, llvm::max(), Scaled, and uint64_t.
Referenced by llvm::BlockFrequencyInfoImplBase::finalizeMetrics().
createIrreducibleLoop()
static void createIrreducibleLoop (BlockFrequencyInfoImplBase & BFI, const IrreducibleGraph & G, LoopData * OuterLoop, std::list< LoopData >::iterator Insert, const std::vector< const IrreducibleGraph::IrrNode * > & SCC) static
Definition at line 781 of file BlockFrequencyInfoImpl.cpp.
References llvm::AMDGPUISD::BFI, llvm::dbgs(), findIrreducibleHeaders(), G, Insert, LLVM_DEBUG, N, and llvm::AMDGPU::CPol::SCC.
Referenced by llvm::BlockFrequencyInfoImplBase::analyzeIrreducible().
debugAssign()
static void debugAssign (const BlockFrequencyInfoImplBase & BFI, const DitheringDistributer & D, const BlockNode & T, const BlockMass & M, const char * Desc) static
Definition at line 434 of file BlockFrequencyInfoImpl.cpp.
References llvm::AMDGPUISD::BFI, D, llvm::dbgs(), and M.
Referenced by llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), llvm::BlockFrequencyInfoImplBase::distributeIrrLoopHeaderMass(), and llvm::BlockFrequencyInfoImplBase::distributeMass().
findIrreducibleHeaders()
static void findIrreducibleHeaders (const BlockFrequencyInfoImplBase & BFI, const IrreducibleGraph & G, const std::vector< const IrreducibleGraph::IrrNode * > & SCC, LoopData::NodeList & Headers, LoopData::NodeList & Others) static
Find extra irreducible headers.
Find entry blocks and other blocks with backedges, which exist when G contains irreducible sub-SCCs.
Definition at line 712 of file BlockFrequencyInfoImpl.cpp.
References assert(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::begin(), llvm::AMDGPUISD::BFI, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::count(), llvm::dbgs(), E, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), I, LLVM_DEBUG, llvm::make_range(), P, llvm::AMDGPU::CPol::SCC, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::size(), and llvm::sort().
Referenced by createIrreducibleLoop().
getHexDigit()
static char getHexDigit (int N) static
Definition at line 74 of file BlockFrequencyInfoImpl.cpp.
References assert(), and N.
Referenced by llvm::bfi_detail::BlockMass::print().
shiftRightAndRound()
static uint64_t shiftRightAndRound (uint64_t N, int Shift) static
Definition at line 227 of file BlockFrequencyInfoImpl.cpp.
References assert(), N, and Shift.
Referenced by llvm::BlockFrequencyInfoImplBase::Distribution::normalize().
unwrapLoop()
static void unwrapLoop (BlockFrequencyInfoImplBase & BFI, LoopData & Loop) static
Unwrap a loop package.
Visits all the members of a loop, adjusting their BlockData according to the loop's pseudo-node.
Definition at line 520 of file BlockFrequencyInfoImpl.cpp.
References llvm::AMDGPUISD::BFI, llvm::dbgs(), F, LLVM_DEBUG, and N.
Referenced by llvm::BlockFrequencyInfoImplBase::unwrapLoops().