LLVM: lib/Target/BPF/Disassembler/BPFDisassembler.cpp File Reference
BPFDisassembler.cpp File Reference
#include "MCTargetDesc/BPFMCTargetDesc.h"
#include "TargetInfo/BPFTargetInfo.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/MathExtras.h"
#include <cstdint>
#include "BPFGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "bpf-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
typedef DecodeStatus(* DecodeFunc) (MCInst &MI, unsigned insn, uint64_t Address, const MCDisassembler *Decoder)
Functions
static MCDisassembler * createBPFDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFDisassembler ()
static DecodeStatus DecodeGPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t, const MCDisassembler *)
static DecodeStatus DecodeGPR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t, const MCDisassembler *)
static DecodeStatus decodeMemoryOpValue (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus readInstruction64 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint64_t &Insn, bool IsLittleEndian)
Variables
static const unsigned GPRDecoderTable []
static const unsigned GPR32DecoderTable []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "bpf-disassembler"
Definition at line 28 of file BPFDisassembler.cpp.
Typedef Documentation
DecodeFunc
typedef DecodeStatus(* DecodeFunc) (MCInst &MI, unsigned insn, uint64_t Address, const MCDisassembler *Decoder)
Definition at line 224 of file BPFDisassembler.cpp.
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 30 of file BPFDisassembler.cpp.
Function Documentation
createBPFDisassembler()
static MCDisassembler* createBPFDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 80 of file BPFDisassembler.cpp.
Referenced by LLVMInitializeBPFDisassembler().
DecodeGPR32RegisterClass()
static DecodeStatus DecodeGPR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t , const MCDisassembler *) static
Definition at line 117 of file BPFDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, GPR32DecoderTable, and llvm::MCDisassembler::Success.
DecodeGPRRegisterClass()
static DecodeStatus DecodeGPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t , const MCDisassembler *) static
Definition at line 101 of file BPFDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, GPRDecoderTable, and llvm::MCDisassembler::Success.
decodeMemoryOpValue()
static DecodeStatus decodeMemoryOpValue (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 127 of file BPFDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, GPRDecoderTable, Insn, llvm::Offset, and llvm::MCDisassembler::Success.
LLVMInitializeBPFDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFDisassembler ()
Definition at line 87 of file BPFDisassembler.cpp.
References createBPFDisassembler(), llvm::getTheBPFbeTarget(), llvm::getTheBPFleTarget(), llvm::getTheBPFTarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
readInstruction64()
static DecodeStatus readInstruction64 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint64_t & Insn, bool IsLittleEndian) static
Definition at line 142 of file BPFDisassembler.cpp.
References llvm::MCDisassembler::Fail, Insn, llvm::Make_64(), llvm::ArrayRef< T >::size(), llvm::MCDisassembler::Success, and uint64_t.
Variable Documentation
GPR32DecoderTable
const unsigned GPR32DecoderTable[] static
Initial value:
= {
    BPF::W0,  BPF::W1,  BPF::W2,  BPF::W3,  BPF::W4,  BPF::W5,
    BPF::W6,  BPF::W7,  BPF::W8,  BPF::W9,  BPF::W10, BPF::W11}
Definition at line 112 of file BPFDisassembler.cpp.
Referenced by DecodeGPR32RegisterClass().
GPRDecoderTable
const unsigned GPRDecoderTable[] static
Initial value:
= {
    BPF::R0,  BPF::R1,  BPF::R2,  BPF::R3,  BPF::R4,  BPF::R5,
    BPF::R6,  BPF::R7,  BPF::R8,  BPF::R9,  BPF::R10, BPF::R11}
Definition at line 97 of file BPFDisassembler.cpp.
Referenced by DecodeGPRRegisterClass(), and decodeMemoryOpValue().