LLVM: lib/Target/BPF/MCTargetDesc/BPFMCTargetDesc.cpp File Reference
BPFMCTargetDesc.cpp File Reference
#include "MCTargetDesc/BPFMCTargetDesc.h"
#include "MCTargetDesc/BPFInstPrinter.h"
#include "MCTargetDesc/BPFMCAsmInfo.h"
#include "TargetInfo/BPFTargetInfo.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/TargetParser/Host.h"
#include "BPFGenInstrInfo.inc"
#include "BPFGenSubtargetInfo.inc"
#include "BPFGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createBPFMCInstrInfo ()
static MCRegisterInfo * createBPFMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createBPFMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCStreamer * createBPFMCStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCInstPrinter * createBPFMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCInstrAnalysis * createBPFInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 25 of file BPFMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 24 of file BPFMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 31 of file BPFMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 28 of file BPFMCTargetDesc.cpp.
Function Documentation
createBPFInstrAnalysis()
static MCInstrAnalysis* createBPFInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 97 of file BPFMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeBPFTargetMC().
createBPFMCInstPrinter()
static MCInstPrinter* createBPFMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 62 of file BPFMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeBPFTargetMC().
createBPFMCInstrInfo()
static MCInstrInfo* createBPFMCInstrInfo () static
Definition at line 36 of file BPFMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeBPFTargetMC().
createBPFMCRegisterInfo()
static MCRegisterInfo* createBPFMCRegisterInfo (const Triple & TT) static
Definition at line 42 of file BPFMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeBPFTargetMC().
createBPFMCStreamer()
static MCStreamer* createBPFMCStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 53 of file BPFMCTargetDesc.cpp.
References llvm::createELFStreamer(), Emitter, and move.
Referenced by LLVMInitializeBPFTargetMC().
createBPFMCSubtargetInfo()
static MCSubtargetInfo* createBPFMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 48 of file BPFMCTargetDesc.cpp.
References llvm::X86AS::FS.
Referenced by LLVMInitializeBPFTargetMC().
LLVMInitializeBPFTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeBPFTargetMC ()
Definition at line 101 of file BPFMCTargetDesc.cpp.
References llvm::createBPFAsmBackend(), llvm::createBPFbeAsmBackend(), llvm::createBPFbeMCCodeEmitter(), createBPFInstrAnalysis(), llvm::createBPFMCCodeEmitter(), createBPFMCInstPrinter(), createBPFMCInstrInfo(), createBPFMCRegisterInfo(), createBPFMCStreamer(), createBPFMCSubtargetInfo(), llvm::getTheBPFbeTarget(), llvm::getTheBPFleTarget(), llvm::getTheBPFTarget(), llvm::sys::IsLittleEndianHost, llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), and X.