LLVM: lib/Support/BranchProbability.cpp File Reference
BranchProbability.cpp File Reference
#include "llvm/Support/BranchProbability.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cmath>
Functions
template<uint32_t ConstD>
static uint64_t scale (uint64_t Num, uint32_t N, uint32_t D)
Function Documentation
scale()
template<uint32_t ConstD> static uint64_t scale (uint64_t Num, uint32_t N, uint32_t D) static
Definition at line 69 of file BranchProbability.cpp.
References assert(), D, N, UINT64_MAX, and uint64_t.
Referenced by llvm::IntelExpr::IntelExpr(), norm(), and llvm::ARMInstPrinter::printAdrLabelOperand().