LLVM: lib/Transforms/Utils/BreakCriticalEdges.cpp File Reference
BreakCriticalEdges.cpp File Reference
#include "llvm/Transforms/Utils/BreakCriticalEdges.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/PostDominators.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/InitializePasses.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
Macros
#define DEBUG_TYPE "break-crit-edges"
Functions
STATISTIC (NumBroken, "Number of blocks inserted")
static BasicBlock * findIBRPredecessor (BasicBlock *BB, SmallVectorImpl< BasicBlock * > &OtherPreds)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "break-crit-edges"
Definition at line 37 of file BreakCriticalEdges.cpp.
Function Documentation
findIBRPredecessor()
static BasicBlock* findIBRPredecessor (BasicBlock * BB, SmallVectorImpl< BasicBlock * > & OtherPreds) static
Definition at line 313 of file BreakCriticalEdges.cpp.
References BB, llvm::Instruction::getOpcode(), and llvm::predecessors().
Referenced by llvm::SplitIndirectBrCriticalEdges().
STATISTIC()
STATISTIC (NumBroken , "Number of blocks inserted")