LLVM: lib/IR/BuiltinGCs.cpp File Reference
BuiltinGCs.cpp File Reference
#include "llvm/IR/BuiltinGCs.h"
#include "llvm/IR/GCStrategy.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/Support/Casting.h"
Variables
static GCRegistry::Add< ErlangGC > A ("erlang", "erlang-compatible garbage collector")
static GCRegistry::Add< OcamlGC > B ("ocaml", "ocaml 3.10-compatible GC")
static GCRegistry::Add< ShadowStackGC > C ("shadow-stack", "Very portable GC for uncooperative code generators")
static GCRegistry::Add< StatepointGC > D ("statepoint-example", "an example strategy for statepoint")
static GCRegistry::Add< CoreCLRGC > E ("coreclr", "CoreCLR-compatible GC")
Variable Documentation
A
GCRegistry::Add<ErlangGC> A("erlang", "erlang-compatible garbage collector") static
B
GCRegistry::Add<OcamlGC> B("ocaml", "ocaml 3.10-compatible GC") static
Referenced by llvm::AttributeList::addAllocSizeParamAttr(), llvm::AttributeSet::addAttribute(), llvm::AttributeList::addAttributeAtIndex(), llvm::AttributeSet::addAttributes(), llvm::AttributeList::addAttributesAtIndex(), llvm::Argument::addAttrs(), llvm::xray::Profile::addBlock(), llvm::jitlink::BlockAddressMap::addBlock(), llvm::jitlink::BlockAddressMap::addBlocks(), llvm::jitlink::BlockAddressMap::addBlocksWithoutChecking(), llvm::jitlink::BlockAddressMap::addBlockWithoutChecking(), llvm::FoldingSetNodeID::AddBoolean(), llvm::AttributeList::addDereferenceableOrNullParamAttr(), llvm::AttributeList::addDereferenceableParamAttr(), llvm::AttributeList::addDereferenceableRetAttr(), addDiscriminators(), llvm::AttributeList::addFnAttributes(), llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::codeview::DebugLinesSubsection::addLineAndColumnInfo(), llvm::codeview::DebugLinesSubsection::addLineInfo(), llvm::AttributeList::addParamAttribute(), llvm::AttributeList::addParamAttributes(), llvm::ScheduleDAGInstrs::addPhysRegDeps(), llvm::SpillPlacement::addPrefSpill(), addRawAttributeValue(), llvm::AttributeList::addRetAttributes(), llvm::addRuntimeChecks(), llvm::addStringImm(), addWithOverflow(), adjustedSumFreq(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::AMDGPUAAResult::alias(), llvm::jitlink::alignToBlock(), llvm::lowertypetests::ByteArrayBuilder::allocate(), allocateHSAUserSGPRs(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::PPCInstrInfo::analyzeBranch(), llvm::GenericUniformityAnalysisImpl< ContextT >::analyzeControlDivergence(), llvm::InterleavedAccessInfo::analyzeInterleaving(), llvm::object::append(), llvm::jitlink::BasicLayout::apply(), applyAArch64MulConstCombine(), applyBuildVectorToDup(), AMDGPURegBankCombinerHelper::applyClamp(), AMDGPUPreLegalizerCombinerHelper::applyClampI64ToI16(), AMDGPUPostLegalizerCombinerHelper::applyCvtF32UByteN(), applyDupLane(), applyExtractVecEltPairwiseAdd(), llvm::jitlink::loongarch::applyFixup(), llvm::jitlink::i386::applyFixup(), llvm::jitlink::aarch64::applyFixup(), llvm::jitlink::x86_64::applyFixup(), applyFoldGlobalOffset(), applyFoldMergeToZext(), llvm::AMDGPURegisterBankInfo::applyMappingBFE(), llvm::AMDGPURegisterBankInfo::applyMappingDynStackAlloc(), llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::AMDGPURegisterBankInfo::applyMappingMAD_64_32(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), AMDGPURegBankCombinerHelper::applyMed3(), applyMutateAnyExtToZExt(), AMDGPUPostLegalizerCombinerHelper::applySelectFCmpToFMinToFMaxLegacy(), applySplitStoreZero128(), AMDGPUPostLegalizerCombinerHelper::applyUCharToFloat(), applyVectorSextInReg(), areConsecutiveOrMatch(), llvm::Bitfield::areContiguous(), llvm::MemoryDepChecker::areDepsSafe(), AreEquivalentAddressValues(), llvm::TargetLibraryInfo::areInlineCompatible(), llvm::AttributeFuncs::areOutlineCompatible(), llvm::jitlink::BasicLayout::BasicLayout(), BBIsJumpedOver(), BitsProperlyConcatenate(), llvm::BlockDataT< T >::BlockDataT(), llvm::rdf::DataFlowGraph::build(), buildAddr64RSrc(), buildBitFieldInsert(), buildBufferLoad(), buildCopyFromRegs(), buildCopyToRegs(), buildFrameType(), buildMul(), llvm::AMDGPULegalizerInfo::buildMultiply(), buildNonAtomicBinOp(), buildOffsetSrc(), buildOrChain(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), llvm::AMDGPURegisterBankInfo::buildReadFirstLane(), buildRSRC(), buildSymbolDiff(), llvm::AMDGPURegisterBankInfo::buildVCopy(), llvm::codeview::DebugLinesSubsection::calculateSerializedSize(), canBeMerged(), canComputePointerDiff(), canonicalizeBitSelect(), canonicalizeICmpBool(), canonicalizeSaturatedSubtract(), llvm::canReplacePointersIfEqual(), CanShareConstantPoolEntry(), llvm::castToCStr(), ceilingOfQuotient(), checkAndReplaceCondition(), llvm::checkedMulAdd(), llvm::checkedMulAddUnsigned(), checkOuterLoopInsts(), llvm::IRSimilarity::IRSimilarityCandidate::checkRelativeLocations(), llvm::BitTracker::RegisterCell::cl(), clampDynamicVectorIndex(), llvm::object::MinidumpFile::classof(), llvm::object::XCOFFObjectFile::classof(), llvm::VPHeaderPHIRecipe::classof(), coalescable(), collectBitParts(), combineADDCARRYDiamond(), combineCmpOp(), combineFMA(), llvm::Combiner::combineMachineInstrs(), llvm::AA::combineOptionalValuesInAAValueLatice(), llvm::codeview::DebugLinesSubsection::commit(), llvm::IRComparer< T >::compare(), llvm::object::compareAddress(), llvm::IRSimilarity::IRSimilarityCandidate::compareCommutativeOperandMapping(), llvm::IRSimilarity::IRSimilarityCandidate::compareNonCommutativeOperandMapping(), llvm::ValueDFS_Compare::comparePHIRelated(), compareSegmentsByOffset(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::BaseIndexOffset::computeAliasing(), llvm::computeDelta(), computeKnownBitsFromAssume(), llvm::rdf::Liveness::computeLiveIns(), computeUnlikelySuccessors(), llvm::MDNode::concatenate(), ConnectEpilog(), ConnectProlog(), llvm::AMDGPURegisterBankInfo::constrainOpWithReadfirstlane(), constrainRegToBank(), llvm::rdf::NodeAttrs::contains(), llvm::RegionBase< RegionTraits< Function > >::contains(), llvm::MIRPrinter::convertCallSiteObjects(), convertImageAddrToPacked(), convertStrToInt(), llvm::SimplifyCFGOptions::convertSwitchRangeToICmp(), llvm::SimplifyCFGOptions::convertSwitchToLookupTable(), llvm::AArch64RegisterBankInfo::copyCost(), llvm::RegisterBankInfo::copyCost(), llvm::FeatureBitset::count(), llvm::CallBase::CountBundleInputs(), llvm::SanitizerStatReport::create(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::create(), llvm::orc::StaticLibraryDefinitionGenerator::Create(), llvm::jitlink::SimpleSegmentAlloc::Create(), llvm::sampleprof::SampleProfileReader::create(), llvm::jitlink::loongarch::createAnonymousPointer(), llvm::jitlink::i386::createAnonymousPointer(), llvm::jitlink::aarch64::createAnonymousPointer(), llvm::jitlink::x86_64::createAnonymousPointer(), CreateAssert(), CreateAssertNot(), llvm::ARMTargetLowering::createComplexDeinterleavingIR(), llvm::AArch64TargetLowering::createComplexDeinterleavingIR(), llvm::dxil::DXILOpBuilder::createDXILOpCall(), llvm::InnerLoopVectorizer::createInductionResumeValue(), createMaskedBitTest(), llvm::createOrderedReduction(), llvm::jitlink::i386::createPointerJumpStubBlock(), llvm::jitlink::aarch64::createPointerJumpStubBlock(), llvm::jitlink::x86_64::createPointerJumpStubBlock(), createPowWithIntegerExponent(), CreatePrologue(), llvm::createStepForVF(), llvm::createTargetReduction(), llvm::ThunkInserter< Derived, InsertedThunksTy >::createThunkFunction(), CreateTripRemainder(), llvm::Function::createWithDefaultAttr(), llvm::BitTracker::RegisterCell::ct(), DbgGatherSalvagableDVI(), llvm::DCData::DCData(), DecodeBranchTargetS(), DecodeFromCyclicRange(), decodeLLVMAttributesForBitcode(), DecodeSignedOperand(), decompose(), doList(), llvm::MachinePostDominatorTree::dominates(), llvm::MachineDominatorTree::dominates(), dominates(), llvm::DominatorTreeBase< BasicBlock, false >::dominates(), doUnion(), llvm::ms_demangle::Demangler::dumpBackReferences(), dumpMachineInstrRangeWithSlotIndex(), llvm::BitTracker::MachineEvaluator::eCLB(), llvm::BitTracker::MachineEvaluator::eCTB(), llvm::object::elf_section_iterator::elf_section_iterator(), llvm::M68kFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), eliminateConstraints(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::MCPseudoProbeInlineTree::emit(), llvm::MCPseudoProbeSections::emit(), llvm::emitBCmp(), llvm::emitBinaryFloatFnCall(), emitBinaryFloatFnCallHelper(), llvm::BitstreamWriter::emitBlob(), llvm::emitCalloc(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::emitFPutC(), llvm::emitFPutS(), llvm::AsmPrinter::emitFunctionBody(), llvm::emitFWrite(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), emitInvalidCostRemarks(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCCpy(), llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitMemCpyChk(), llvm::emitMemPCpy(), llvm::emitMemRChr(), emitOrXorXorTree(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::HexagonFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), llvm::emitPutChar(), llvm::emitPutS(), emitReciprocalU64(), llvm::emitSNPrintf(), llvm::emitSPrintf(), llvm::emitStpCpy(), llvm::emitStpNCpy(), llvm::emitStrCat(), llvm::emitStrChr(), llvm::emitStrCpy(), llvm::emitStrDup(), llvm::emitStrLCat(), llvm::emitStrLCpy(), llvm::emitStrLen(), llvm::emitStrNCat(), llvm::emitStrNCmp(), llvm::emitStrNCpy(), emitTransformedIndex(), llvm::emitUnaryFloatFnCall(), emitUnaryFloatFnCallHelper(), RISCVELFStreamer::emitValueImpl(), llvm::emitVSNPrintf(), llvm::emitVSPrintf(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::equal_range(), llvm::BaseIndexOffset::equalBaseIndex(), llvm::InstrProfLookupTrait::EqualKey(), llvm::memprof::RecordLookupTrait::EqualKey(), llvm::memprof::FrameLookupTrait::EqualKey(), llvm::sys::fs::equivalent(), equivalentAddressValues(), llvm::rdf::DeadCodeElimination::erase(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::VPWidenRecipe::execute(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::BitstreamWriter::ExitBlock(), expandBinOp(), expandUDivOrURem(), extendLow32IntoHigh32(), llvm::BitTracker::MachineEvaluator::eXTR(), llvm::BitTracker::RegisterCell::extract(), extractF64Exponent(), extractInstructionFeatures(), factorizeMinMaxTree(), llvm::FeatureBitset::FeatureBitset(), llvm::BitTracker::RegisterCell::fill(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::opt::ArgList::filtered(), llvm::opt::ArgList::filtered_reverse(), llvm::AccelTableBase::finalize(), llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), llvm::MachineDominanceFrontier::find(), llvm::DominanceFrontierBase< BasicBlock, false >::find(), findCommonType(), llvm::wholeprogramdevirt::findLowestOffset(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::MachineDominatorTree::findNearestCommonDominator(), llvm::DominatorTreeBase< BasicBlock, false >::findNearestCommonDominator(), llvm::SanitizerStatReport::finish(), llvm::BitTracker::BitMask::first(), first_use_of_in_block(), firstCommonClass(), llvm::AMDGPULegalizerInfo::fixStoreSourceType(), llvm::InnerLoopVectorizer::fixupIVUsers(), floorOfQuotient(), llvm::AMDGPULibCalls::fold(), foldAndToXor(), foldComplexAndOrPatterns(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpOfUAddOv(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithConstant(), llvm::InstCombinerImpl::foldICmpWithZero(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), foldNotXor(), llvm::InstCombinerImpl::FoldOpIntoSelect(), foldOrToXor(), foldSelectICmpAndAnd(), foldUnsignedUnderflowCheck(), llvm::InstCombinerImpl::foldUsingDistributiveLaws(), foldXorToXor(), llvm::format_provider< codeview::GloballyHashedType >::format(), llvm::format_provider< bool >::format(), llvm::SimplifyCFGOptions::forwardSwitchCondToPhi(), llvm::DIExpression::fragmentCmp(), llvm::DIExpression::fragmentsOverlap(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), llvm::hlsl::FrontendResource::FrontendResource(), fullyContains(), gcd(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), generateCreationChecks(), generateCreationChecksForBinOp(), llvm::IRComparer< T >::generateFunctionData(), llvm::msf::MSFBuilder::generateLayout(), llvm::VPTransformState::get(), llvm::AttributeSetNode::get(), llvm::AttributeSet::get(), llvm::AttributeList::get(), llvm::VarBitInit::get(), llvm::MCValue::getAccessVariant(), llvm::ScalarEvolution::getAddExpr(), llvm::HexagonFrameLowering::getAlignaInstr(), llvm::rdf::Liveness::getAllReachingDefs(), AMDGPURegBankCombinerHelper::getAsVgpr(), llvm::objcarc::getAttachedARCFunction(), llvm::VarBitInit::getBit(), getBitcastWiderVectorElementOffset(), llvm::jitlink::LinkGraph::getBlockContentReader(), llvm::jitlink::LinkGraph::getBlockContentWriter(), llvm::jitlink::BlockAddressMap::getBlockCovering(), getBlockName(), llvm::SIScheduleBlockCreator::getBlocks(), llvm::AArch64InstrInfo::getBranchDestBlock(), getBranchDisplacementBits(), llvm::RegionInfoBase< RegionTraits< Function > >::getCommonRegion(), llvm::TargetRegisterInfo::getCommonSubClass(), llvm::getDeadRegState(), llvm::getDebugRegState(), llvm::getDefRegState(), llvm::HexagonInstrInfo::getDotNewPredJumpOp(), getEmscriptenFunction(), llvm::NonRelocatableStringpool::getEntriesForEmission(), llvm::MipsInstrInfo::getEquivalentCompactForm(), llvm::MachineBasicBlock::getFirstInstrTerminator(), llvm::MachineBasicBlock::getFirstTerminator(), getFPBinOp(), getFPTernOp(), llvm::DbgVariable::getFrameIndexExprs(), llvm::StatepointOpers::getGCPointerMap(), getHashValueImpl(), llvm::BlockFrequencyInfoImplBase::LoopData::getHeaderIndex(), llvm::AMDGPULegalizerInfo::getImplicitArgPtr(), llvm::getImplRegState(), llvm::SlotIndexes::getIndexBefore(), getInputSegmentList(), llvm::getInternalReadRegState(), llvm::HexagonSubtarget::getIntrinsicId(), getIntToFPVal(), getIntTy(), llvm::AMDGPULegalizerInfo::getKernargParameterPtr(), llvm::getKillRegState(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::AMDGPULegalizerInfo::getLDSKernelId(), getLeastCommonType(), getLiveInRegsAt(), getLiveOutRegsAt(), llvm::DILocation::getMaskedDiscriminator(), getMaskedICmpType(), getMaskedTypeForICmpPair(), llvm::getMatchingCondBranchOpcode(), llvm::X86RegisterInfo::getMatchingSuperRegClass(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), llvm::GlobalValue::getMinUnnamedAddr(), getMinVisibility(), llvm::MDNode::getMostGenericAliasScope(), llvm::MDNode::getMostGenericAlignmentOrDereferenceable(), llvm::MDNode::getMostGenericFPMath(), llvm::MDNode::getMostGenericRange(), llvm::MDNode::getMostGenericTBAA(), llvm::APIntOps::GetMostSignificantDifferentBit(), llvm::rdf::Liveness::getNearestAliasedRef(), getNonDebugInstr(), llvm::DomTreeNodeTraits< VPBlockBase >::getParent(), llvm::HvxSelector::getPerfectCompletions(), GetQuadraticEquation(), llvm::getRenamableRegState(), llvm::jitlink::getRISCVPCRelHi20(), llvm::getRuntimeVF(), llvm::getRuntimeVFAsFloat(), llvm::GCNIterativeScheduler::getSchedulePressure(), llvm::jitlink::SimpleSegmentAlloc::getSegInfo(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), getSizeTTy(), getSqrtCall(), getStackGuard(), getStatepointArgs(), getSymbolOffsetImpl(), getUnconditionalBranch(), llvm::getUndefRegState(), getUnmergePieces(), llvm::jitlink::COFFLinkGraphBuilder::graphifySections(), llvm::jitlink::ELFLinkGraphBuilder< object::ELF64LE >::graphifySections(), greaterWithBias(), llvm::APIntOps::GreatestCommonDivisor(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), llvm::InLineChangePrinter::handleFunctionCompare(), handleMemIntrinsicPtrUse(), llvm::GenericUniformityInfo< SSAContext >::hasDivergentTerminator(), llvm::GenericUniformityAnalysisImpl< ContextT >::hasDivergentTerminator(), llvm::HexagonInstrInfo::hasEHLabel(), llvm::ReachingDefAnalysis::hasSameReachingDef(), HasSameValue(), llvm::hasSingleElement(), llvm::HexagonInstrInfo::hasUncondBranch(), llvm::haveNoCommonBitsSet(), llvm::SelectionDAG::haveNoCommonBitsSet(), haveNoCommonBitsSetCommutative(), hoistAndMergeSGPRInits(), llvm::SimplifyCFGOptions::hoistCommonInsts(), llvm::rdf::NodeAllocator::id(), llvm::jitlink::BlockAddressMap::includeNonNull(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::initEmpty(), INITIALIZE_PASS(), llvm::mca::initializeUsedResources(), llvm::BitTracker::RegisterCell::insert(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::AArch64InstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), llvm::HexagonFrameLowering::insertCFIInstructions(), llvm::DIBuilder::insertDbgAssign(), llvm::LiveIntervals::InsertMachineInstrRangeInMaps(), insertSinCosCall(), instCombineMaxMinNM(), instCombineSVEZip(), llvm::HexagonBlockRanges::InstrIndexMap::InstrIndexMap(), llvm::ScalarEvolution::instructionCouldExistWitthOperands(), intersect(), llvm::MDNode::intersect(), is_empty(), llvm::InstructionOrdering::isBefore(), IsBetterCanonical(), llvm::LoongArchInstrInfo::isBranchOffsetInRange(), llvm::MipsInstrInfo::isBranchOffsetInRange(), isClampZeroToOne(), llvm::IRSimilarity::isClose(), isCommutableVPERMV3Instruction(), llvm::isConsecutiveAccess(), isContiguous(), llvm::jitlink::isCStringBlock(), llvm::SlotIndex::isEarlierEqualInstr(), llvm::SlotIndex::isEarlierInstr(), llvm::AMDGPUCallLowering::isEligibleForTailCallOptimization(), llvm::DenseMapInfo< CSKYTargetStreamer::SymbolIndex >::isEqual(), llvm::DenseMapInfo< std::pair< const MCSymbol *, MCSymbolRefExpr::VariantKind > >::isEqual(), llvm::DenseMapInfo< LocIdx >::isEqual(), llvm::DenseMapInfo< ValueIDNum >::isEqual(), llvm::DenseMapInfo< SlotWithTag >::isEqual(), llvm::DenseMapInfo< object::SectionRef >::isEqual(), llvm::DenseMapInfo< AA::RangeTy >::isEqual(), llvm::DenseMapInfo< DIExpression::FragmentInfo >::isEqual(), llvm::DenseMapInfo< DebugVariable >::isEqual(), llvm::SelectionDAG::isEqualTo(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), isHorizontalBinOp(), isInstructionPairAdd(), isInstructionPairMul(), IsInterestingCmp(), llvm::LiveRangeCalc::isJointlyDominated(), llvm::isKnownNegation(), llvm::LoopVectorizationCostModel::isMoreProfitable(), llvm::isOverflowIntrinsicNoWrap(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::isPermutation(), isPointerBitcastEqualTo(), llvm::isPotentiallyReachable(), llvm::SlotIndex::isSameInstr(), isSignExtendedW(), llvm::IRSimilarity::IRSimilarityCandidate::isSimilar(), isSortedByValueNo(), llvm::AArch64_AM::isSVEMoveMaskPreferredLogicalImmediate(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolved(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::AMDGPUMachineModuleInfo::isSyncScopeInclusion(), isTruePredicate(), llvm::isUncondBranchOpcode(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::AMDGPULegalizerInfo::legalizeAtomicIncDec(), llvm::AMDGPULegalizerInfo::legalizeBufferAtomic(), llvm::AMDGPULegalizerInfo::legalizeBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeBufferStore(), llvm::AMDGPULegalizerInfo::legalizeBuildVector(), llvm::AMDGPULegalizerInfo::legalizeBVHIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeCTLZ_CTTZ(), llvm::AMDGPULegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeDebugTrapIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFceil(), llvm::AMDGPULegalizerInfo::legalizeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFDIV16(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFDIVFastIntrin(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeFlog(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeFPow(), llvm::AMDGPULegalizerInfo::legalizeFPTOI(), llvm::AMDGPULegalizerInfo::legalizeFPTruncRound(), llvm::AMDGPULegalizerInfo::legalizeFrem(), llvm::AMDGPULegalizerInfo::legalizeFrint(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc(), llvm::AMDGPULegalizerInfo::legalizeIsAddrSpace(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeKernargMemParameter(), llvm::AMDGPULegalizerInfo::legalizeLDSKernelId(), llvm::AMDGPULegalizerInfo::legalizeLoad(), llvm::AMDGPULegalizerInfo::legalizeMul(), llvm::AMDGPULegalizerInfo::legalizePreloadedArgIntrin(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeSBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeSignedDIV_REM(), llvm::AMDGPULegalizerInfo::legalizeSinCos(), llvm::AMDGPULegalizerInfo::legalizeTrapEndpgm(), llvm::AMDGPULegalizerInfo::legalizeTrapHsa(), llvm::AMDGPULegalizerInfo::legalizeTrapHsaQueuePtr(), llvm::AMDGPULegalizerInfo::legalizeTrapIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM32Impl(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM64Impl(), llvm::cfg::LegalizeUpdates(), llvm::AMDGPULegalizerInfo::legalizeWorkitemIDIntrinsic(), llvm::HexagonInstr::lessCore(), llvm::HexagonInstr::lessCVI(), llvm::HexagonResource::lessUnits(), llvm::HexagonResource::lessWeight(), LLVMBuildAdd(), LLVMBuildAddrSpaceCast(), LLVMBuildAggregateRet(), LLVMBuildAlloca(), LLVMBuildAnd(), LLVMBuildArrayAlloca(), LLVMBuildArrayMalloc(), LLVMBuildAShr(), LLVMBuildAtomicCmpXchg(), LLVMBuildAtomicRMW(), LLVMBuildBinOp(), LLVMBuildBitCast(), LLVMBuildBr(), LLVMBuildCall2(), LLVMBuildCast(), LLVMBuildCatchPad(), LLVMBuildCatchRet(), LLVMBuildCatchSwitch(), LLVMBuildCleanupPad(), LLVMBuildCleanupRet(), LLVMBuildCondBr(), LLVMBuildExactSDiv(), LLVMBuildExactUDiv(), LLVMBuildExtractElement(), LLVMBuildExtractValue(), LLVMBuildFAdd(), LLVMBuildFCmp(), LLVMBuildFDiv(), LLVMBuildFence(), LLVMBuildFMul(), LLVMBuildFNeg(), LLVMBuildFPCast(), LLVMBuildFPExt(), LLVMBuildFPToSI(), LLVMBuildFPToUI(), LLVMBuildFPTrunc(), LLVMBuildFree(), LLVMBuildFreeze(), LLVMBuildFRem(), LLVMBuildFSub(), LLVMBuildGEP2(), LLVMBuildGlobalString(), LLVMBuildGlobalStringPtr(), LLVMBuildICmp(), LLVMBuildInBoundsGEP2(), LLVMBuildIndirectBr(), LLVMBuildInsertElement(), LLVMBuildInsertValue(), LLVMBuildIntCast(), LLVMBuildIntCast2(), LLVMBuildIntToPtr(), LLVMBuildInvoke2(), LLVMBuildIsNotNull(), LLVMBuildIsNull(), LLVMBuildLandingPad(), LLVMBuildLoad2(), LLVMBuildLShr(), LLVMBuildMalloc(), LLVMBuildMemCpy(), LLVMBuildMemMove(), LLVMBuildMemSet(), LLVMBuildMul(), LLVMBuildNeg(), LLVMBuildNot(), LLVMBuildNSWAdd(), LLVMBuildNSWMul(), LLVMBuildNSWNeg(), LLVMBuildNSWSub(), LLVMBuildNUWAdd(), LLVMBuildNUWMul(), LLVMBuildNUWNeg(), LLVMBuildNUWSub(), LLVMBuildOr(), LLVMBuildPhi(), LLVMBuildPointerCast(), LLVMBuildPtrDiff2(), LLVMBuildPtrToInt(), LLVMBuildResume(), LLVMBuildRet(), LLVMBuildRetVoid(), LLVMBuildSDiv(), LLVMBuildSelect(), LLVMBuildSExt(), LLVMBuildSExtOrBitCast(), LLVMBuildShl(), LLVMBuildShuffleVector(), LLVMBuildSIToFP(), LLVMBuildSRem(), LLVMBuildStore(), LLVMBuildStructGEP2(), LLVMBuildSub(), LLVMBuildSwitch(), LLVMBuildTrunc(), LLVMBuildTruncOrBitCast(), LLVMBuildUDiv(), LLVMBuildUIToFP(), LLVMBuildUnreachable(), LLVMBuildURem(), LLVMBuildVAArg(), LLVMBuildXor(), LLVMBuildZExt(), LLVMBuildZExtOrBitCast(), LLVMInitializeAMDGPUAsmParser(), LLVMInitializeARMAsmParser(), LLVMInitializeARMAsmPrinter(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsAsmPrinter(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializePowerPCAsmParser(), LLVMInitializePowerPCTarget(), LLVMInitializeSparcAsmParser(), LLVMSetNormalDest(), LLVMSetUnwindDest(), llvm::orc::StaticLibraryDefinitionGenerator::Load(), llvm::coverage::CoverageMapping::load(), llvm::object::ResourceSectionRef::load(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::ValueDFS_Compare::localComesBefore(), lookForCompound(), llvm::LegalizerHelper::lowerBitCount(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), lowerIntrinsic(), lowerLoadRelative(), LowerMUL(), LowerMULH(), LowerMULO(), llvm::AMDGPUCallLowering::lowerReturn(), LowervXi8MulWithUNPCK(), maintainNoSignedWrap(), llvm::MachineFunction::makeDebugValueSubstitution(), llvm::makeGuardControlFlowExplicit(), llvm::jitlink::makeTargetOutOfRangeError(), llvm::rdf::DataFlowGraph::markBlock(), MarkBlocksLiveIn(), matchAArch64MulConstCombine(), matchAccessTags(), llvm::CombinerHelper::matchAddEToAddO(), llvm::CombinerHelper::matchAddOBy0(), llvm::CombinerHelper::matchAndOrDisjointMask(), llvm::CombinerHelper::matchBitfieldExtractFromAnd(), llvm::CombinerHelper::matchBitfieldExtractFromShrAnd(), llvm::CombinerHelper::matchCombineFAbsOfFNeg(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineLoadWithAndMask(), llvm::CombinerHelper::matchCombineUnmergeUndef(), matchDeMorgansLaws(), matchesAdd(), matchesOr(), llvm::CombinerHelper::matchICmpToLHSKnownBits(), matchMinMaxOfMinMax(), llvm::CombinerHelper::matchMulOBy0(), llvm::CombinerHelper::matchMulOBy2(), llvm::CombinerHelper::matchNarrowBinopFeedingAnd(), llvm::CombinerHelper::matchOrShiftToFunnelShift(), llvm::CombinerHelper::matchOverlappingAnd(), AMDGPUPostLegalizerCombinerHelper::matchRcpSqrtToRsq(), llvm::CombinerHelper::matchReassocConstantInnerLHS(), llvm::CombinerHelper::matchReassocConstantInnerRHS(), llvm::CombinerHelper::matchReassocFoldConstantsInSubTree(), llvm::CombinerHelper::matchRedundantBinOpInEquality(), llvm::CombinerHelper::matchRedundantNegOperands(), matchSelectWithOptionalNotCond(), llvm::CombinerHelper::matchSubAddSameReg(), matchUAddWithOverflowConstantEdgeCases(), llvm::maximum(), llvm::maxnum(), mayLoopAccessLocation(), memChrToCharCompare(), memoryIsNotModifiedBetween(), merge(), llvm::AttrBuilder::merge(), MergeAliasResults(), llvm::DDGBuilder::mergeNodes(), llvm::InstrProfWriter::mergeProfileKind(), llvm::jitlink::LinkGraph::mergeSections(), MergeSeqs(), mergeVectorRegsToResultRegs(), llvm::MIBundleBuilder::MIBundleBuilder(), llvm::MinAlign(), llvm::minimum(), llvm::minnum(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::moveFromOldBuckets(), moveInstrOut(), llvm::ConstantRange::multiply(), llvm::detail::DoubleAPFloat::multiply(), multiplyWithOverflow(), llvm::LegalizerHelper::narrowScalarCTLZ(), llvm::LegalizerHelper::narrowScalarCTTZ(), narrowSDivOrSRem(), narrowUDivOrURem(), nearest_common_dominatee(), nearest_common_dominator(), llvm::SimplifyCFGOptions::needCanonicalLoops(), llvm::codeview::operator!=(), llvm::operator!=(), llvm::AA::operator!=(), llvm::AttrBuilder::operator!=(), llvm::SystemZTargetStreamer::CmpMCInst::operator()(), llvm::jitlink::DWARFRecordSectionSplitter::operator()(), llvm::jitlink::SEHFrameKeepAlivePass::operator()(), llvm::ValueDFS_Compare::operator()(), llvm::jitlink::CompactUnwindSplitter::operator()(), std::equal_to< llvm::rdf::RegisterAggr >::operator()(), EarlierIssuingCycle::operator()(), llvm::codeview::operator<(), llvm::opt::operator<(), llvm::HexagonInstr::operator<(), llvm::operator<(), llvm::jitlink::operator<<(), llvm::rdf::operator<<(), llvm::codeview::operator<=(), llvm::codeview::operator==(), operator==(), llvm::operator==(), llvm::AA::operator==(), llvm::AttrBuilder::operator==(), llvm::codeview::operator>(), llvm::codeview::operator>=(), llvm::rdf::Liveness::LiveMapType::operator[](), llvm::sys::fs::operator|(), llvm::sys::fs::operator|=(), llvm::FeatureBitset::operator~(), optimizeBinaryDoubleFP(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), optimizeDoubleFP(), llvm::jitlink::i386::optimizeGOTAndStubAccesses(), llvm::jitlink::x86_64::optimizeGOTAndStubAccesses(), optimizeMemCmpConstantSize(), optimizeMemCmpVarSize(), optimizeTrigReflections(), optimizeUnaryDoubleFP(), llvm::SystemZELFFrameLowering::orderFrameObjects(), llvm::outliner::OutlinedFunction::OutlinedFunction(), llvm::IRSimilarity::IRSimilarityCandidate::overlap(), packImage16bitOpsToDwords(), parsePhysicalReg(), parseWholeProgramDevirtResolutionByArg(), llvm::parseWidenableBranch(), llvm::PeelingModuloScheduleExpander::peelPrologAndEpilogs(), PeepholePPC64ZExtGather(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), PerformSETCCCombine(), PerformVECREDUCE_ADDCombine(), performVecReduceAddCombine(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), PickMostRelevantLoop(), llvm::CallBase::populateBundleOperandInfos(), llvm::HexagonInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::PhysicalRegisterUsageInfo::print(), llvm::lowertypetests::BitSetInfo::print(), llvm::jitlink::printEdge(), printName(), processAbsIntrinsic(), processOverflowIntrinsic(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), llvm::xray::Profile::Profile(), ProfileFoldOpInit(), llvm::MachinePostDominatorTree::properlyDominates(), llvm::MachineDominatorTree::properlyDominates(), llvm::DominatorTreeBase< BasicBlock, false >::properlyDominates(), properlyDominates(), llvm::jitlink::prune(), r0(), r1(), r2(), r3(), r4(), llvm::BitTracker::reached(), llvm::SymbolRemappingReader::read(), readGSIHashBuckets(), reinsertVectorIndexAdd(), llvm::objcarc::ProvenanceAnalysis::related(), llvm::rdf::DataFlowGraph::releaseBlock(), llvm::AttributeSet::removeAttribute(), llvm::AttributeSet::removeAttributes(), llvm::jitlink::LinkGraph::removeBlock(), llvm::PPCInstrInfo::removeBranch(), llvm::MemorySSAUpdater::removeDuplicatePhiEdgesBetween(), llvm::codegen::renderBoolStringAttr(), replaceSubOverflowUses(), replaceUnaryCall(), replaceWithConstant(), llvm::rdf::Liveness::resetKills(), llvm::rdf::Liveness::resetLiveIns(), rewrite(), llvm::SSAUpdaterBulk::RewriteAllUses(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::rewriteLoopExitValues(), llvm::APIntOps::RoundingSDiv(), llvm::APIntOps::RoundingUDiv(), llvm::CostModelPrinterPass::run(), llvm::dxil::PointerTypeAnalysis::run(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::SpeculativeExecutionPass::runImpl(), llvm::RewriteStatepointsForGC::runOnFunction(), SalvageDVI(), llvm::sampleprof::SampleSorter< LocationT, SampleT >::SampleSorter(), llvm::jitlink::SectionRange::SectionRange(), llvm::FastMathFlags::setAllowContract(), llvm::FastMathFlags::setAllowReassoc(), llvm::FastMathFlags::setAllowReciprocal(), llvm::FastMathFlags::setApproxFunc(), llvm::pdb::BulkPublic::setBucketIdx(), setBufferOffsets(), llvm::pdb::DbiStreamBuilder::setBuildNumber(), llvm::CallBrInst::setDefaultDest(), llvm::msf::MSFBuilder::setDirectoryBlocksHint(), llvm::MachineFunction::setExposesReturnsTwice(), llvm::FastMathFlags::setFast(), llvm::Instruction::setFast(), llvm::SimplifyCFGOptions::setFoldTwoEntryPHINode(), llvm::DIE::setForceChildren(), llvm::codegen::setFunctionAttributes(), llvm::jitlink::COFFLinkGraphBuilder::setGraphBlock(), llvm::jitlink::ELFLinkGraphBuilder< object::ELF64LE >::setGraphBlock(), llvm::AVRMachineFunctionInfo::setHasAllocas(), llvm::Instruction::setHasAllowContract(), llvm::Instruction::setHasAllowReassoc(), llvm::Instruction::setHasAllowReciprocal(), llvm::Instruction::setHasApproxFunc(), llvm::MachineFrameInfo::setHasCopyImplyingStackAdjustment(), llvm::pdb::InfoStreamBuilder::setHashPDBContentsToGUID(), llvm::MachineFunction::setHasInlineAsm(), llvm::MachineFrameInfo::setHasMustTailInVarArgFunc(), llvm::Instruction::setHasNoInfs(), llvm::Instruction::setHasNoNaNs(), llvm::Instruction::setHasNoSignedZeros(), llvm::MachineFrameInfo::setHasOpaqueSPAdjustment(), llvm::AVRMachineFunctionInfo::setHasSpills(), llvm::AVRMachineFunctionInfo::setHasStackArgs(), llvm::MachineFrameInfo::setHasVAStart(), llvm::CallBrInst::setIndirectDest(), setInsertPointSkippingPhis(), llvm::GetElementPtrInst::setIsInBounds(), llvm::SinkAndHoistLICMFlags::setIsSink(), llvm::FastMathFlags::setNoInfs(), llvm::FastMathFlags::setNoNaNs(), llvm::InvokeInst::setNormalDest(), llvm::FastMathFlags::setNoSignedZeros(), llvm::rdf::PhiUseNode::setPredecessor(), llvm::SimplifyCFGOptions::setSimplifyCondBranch(), llvm::InvokeInst::setUnwindDest(), llvm::setWidenableBranchCond(), llvm::SignExtend32(), llvm::SignExtend64(), simplifyAssociativeBinOp(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), simplifyOrInst(), simplifyOrLogic(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifyUnsignedRangeCheck(), simplifyValueKnownNonZero(), simplifyWithOpReplaced(), simplifyXorInst(), llvm::SimplifyCFGOptions::sinkCommonInsts(), sinkInstruction(), sinkLoopInvariantInstructions(), sinkRecurrenceUsersAfterPrevious(), sinkSpillUsesAfterCoroBegin(), llvm::APIntOps::smax(), llvm::APIntOps::smin(), llvm::ConstantRange::smul_fast(), llvm::ConstantRange::smul_sat(), SolveLinEquationWithOverflow(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::sampleprof::sortFuncProfiles(), sortGlobalExprs(), llvm::DebugLocEntry::sortUniqueValues(), llvm::AMDGPURegisterBankInfo::split64BitValueForMapping(), llvm::jitlink::LinkGraph::splitBlock(), llvm::AMDGPURegisterBankInfo::splitBufferOffsets(), llvm::AMDGPULegalizerInfo::splitBufferOffsets(), llvm::VETargetLowering::splitMaskArithmetic(), splitMBB(), llvm::stable_hash_combine(), llvm::storeToSameAddress(), llvm::opt::StrCmpOptionName(), llvm::opt::StrCmpOptionNameIgnoreCase(), SwapN(), toggleSPDenormMode(), llvm::object::ELFFile< ELFT >::toMappedAddr(), llvm::jitlink::LinkGraph::transferBlock(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), tryFactorization(), llvm::InstCombinerImpl::tryFactorizationFolds(), tryToRecognizeTableBasedCttz(), tryToSimplifyOverflowMath(), tryToSimplifyUADDO(), TryToSinkInstruction(), llvm::APIntOps::umax(), llvm::APIntOps::umin(), unifyBitWidth(), llvm::MemoryPhi::unorderedDeleteIncomingBlock(), llvm::HexagonPacketizerList::unpacketizeSoloInstrs(), unpackV2S16ToS32(), llvm::UnrollRuntimeLoopRemainder(), unwrapBlock(), llvm::dxil::ValidatorVersionMD::update(), llvm::DWARFUnit::updateAddressDieMap(), llvm::MachineBasicBlock::updateTerminator(), llvm::UpgradeAttributes(), upgradeMaskedMove(), llvm::UpgradeModuleFlags(), llvm::json::Value::Value(), llvm::valueComesBefore(), llvm::AssumptionCacheTracker::verifyAnalysis(), verifyCompareConds(), llvm::LoopBase< BasicBlock, Loop >::verifyLoop(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::InstCombinerImpl::visitCallInst(), llvm::jitlink::loongarch::GOTTableManager::visitEdge(), llvm::jitlink::i386::GOTTableManager::visitEdge(), llvm::jitlink::loongarch::PLTTableManager::visitEdge(), llvm::jitlink::i386::PLTTableManager::visitEdge(), llvm::jitlink::aarch64::GOTTableManager::visitEdge(), llvm::jitlink::x86_64::GOTTableManager::visitEdge(), llvm::jitlink::aarch64::PLTTableManager::visitEdge(), llvm::jitlink::x86_64::PLTTableManager::visitEdge(), llvm::jitlink::visitEdge(), llvm::jitlink::visitExistingEdges(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitICmpInst(), visitMaskedMerge(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitXor(), llvm::widenWidenableBranch(), llvm::ScalarEvolution::willNotOverflow(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::dxil::ResourceBase::ExtendedProperties::write(), llvm::dxil::UAVResource::write(), llvm::dxil::ConstantBuffer::write(), llvm::InstrProfWriter::writeText(), llvm::DwarfUnit::~DwarfUnit(), and llvm::jitlink::Section::~Section().
C
GCRegistry::Add<ShadowStackGC> C("shadow-stack", "Very portable GC for uncooperative code generators") static
D
GCRegistry::Add<StatepointGC> D("statepoint-example", "an example strategy for statepoint") static
Referenced by llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::add(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::add(), llvm::SUnit::addPred(), addToFwdRegWorklist(), llvm::DWARFUnitVector::addUnitsForDWOSection(), llvm::DWARFUnitVector::addUnitsForSection(), llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), llvm::MCRegisterInfo::DiffListIterator::advance(), llvm::DWARFTypePrinter::appendArrayType(), appendDigit(), llvm::HexagonSubtarget::UsrOverflowMutation::apply(), llvm::DwarfCompileUnit::applyStmtList(), llvm::SPIRVGeneralDuplicatesTracker::buildDepsGraph(), llvm::HexagonPacketizerList::canPromoteToDotNew(), checkDependency(), checkDyldCommand(), checkDylibCommand(), llvm::VPCanonicalIVPHIRecipe::classof(), llvm::VPActiveLaneMaskPHIRecipe::classof(), llvm::DILocation::cloneByMultiplyingDuplicationFactor(), llvm::DILocation::cloneWithBaseDiscriminator(), combineTargetShuffle(), llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::GCNSchedStage::computeSUnitReadyCycle(), llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructVariableDIE(), llvm::object::Decompressor::create(), llvm::orc::EPCEHFrameRegistrar::Create(), llvm::InstrProfSymtab::create(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::DWARFFormValue::createFromBlockValue(), llvm::mca::InstrBuilder::createInstruction(), llvm::orc::createJITLoaderGDBRegistrar(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::createMemoryDependencyEdges(), llvm::DataDependenceGraph::DataDependenceGraph(), debugAssign(), llvm::DILocation::decodeDiscriminator(), DecodeFixedType(), llvm::GCNIterativeScheduler::detachSchedule(), llvm::diagnoseDontCall(), llvm::BlockFrequencyInfoImplBase::distributeIrrLoopHeaderMass(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::SCEVDivision::divide(), llvm::dlangDemangle(), llvm::ScaledNumberBase::dump(), dumpAttribute(), dumpExampleDependence(), llvm::MCLOHContainer::emit(), llvm::APByteStreamer::emitDIERef(), llvm::HashingByteStreamer::emitDIERef(), llvm::BufferByteStreamer::emitDIERef(), llvm::sampleprof::DefaultFunctionPruningStrategy::Erase(), factorizeMinMaxTree(), llvm::StringRef::find_insensitive(), llvm::DWARFDie::findRecursively(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), llvm::UnOpInit::Fold(), llvm::ExistsOpInit::Fold(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), foldNotXor(), llvm::format_provider< std::chrono::duration< Rep, Period > >::format(), llvm::InLineChangePrinter::generateIRRepresentation(), llvm::SignedDivisionByConstantInfo::get(), llvm::UnsignedDivisionByConstantInfo::get(), llvm::rdf::Liveness::getAllReachedUses(), llvm::json::Value::getAsInteger(), llvm::DILocation::getBaseDiscriminatorFromDiscriminator(), llvm::ScalarEvolution::getBlockDisposition(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::DILocation::getCopyIdentifierFromDiscriminator(), llvm::DependenceGraphInfo< NodeType >::getDependenceString(), llvm::DwarfUnit::getDIE(), llvm::DWARFUnit::getDIEIndex(), llvm::DILocation::getDuplicationFactorFromDiscriminator(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getEdgeAttributes(), llvm::MCLOHContainer::getEmitSize(), llvm::WebAssemblyException::getExceptionDepth(), llvm::ScaledNumber< uint64_t >::getFraction(), llvm::StatepointOpers::getGCPointerMap(), llvm::DenseMapInfo< DebugVariable >::getHashValue(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::LoopBase< BasicBlock, Loop >::getLoopDepth(), llvm::ScalarEvolution::getLoopDisposition(), llvm::DILocation::getMaskedDiscriminator(), getMaskedTypeForICmpPair(), getNextComponentInDiscriminator(), getReg(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::ScalarEvolution::getUDivCeilSCEV(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::DWARFVerifier::handleAccelTables(), llvm::IndexedReference::hasTemporalReuse(), ignoreDependence(), llvm::MCInstrInfo::InitMCInstrInfo(), llvm::DwarfUnit::insertDIE(), llvm::interpretDecimal(), isCommutableVPERMV3Instruction(), llvm::rdf::TargetOperandInfo::isFixedReg(), llvm::InductionDescriptor::isFPInductionPHI(), isHorizontalBinOp(), llvm::InductionDescriptor::isInductionPHI(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), isSafeToMove(), llvm::DwarfUnit::isShareableAcrossCUs(), isSignExtendedW(), llvm::ImutContainerInfo< T >::KeyOfValue(), llvm::ImutContainerInfo< T * >::KeyOfValue(), llvm::LexicalScope::LexicalScope(), LLVMInitializePowerPCAsmParser(), LLVMInitializePowerPCTarget(), LLVMLinkModules2(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), MapDWLangToCVLang(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), matchMinMaxOfMinMax(), llvm::microsoftDemangle(), llvm::detail::DoubleAPFloat::multiply(), narrowUDivURem(), llvm::RegisterPassParser< RegistryClass >::NotifyAdd(), llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction >::operator()(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator++(), llvm::pdb::operator<<(), llvm::object::operator<<(), llvm::operator<<(), llvm::ARM::parseHWDiv(), llvm::ProfOStream::patch(), populateDependencyMatrix(), preservesBackwardDependence(), preservesForwardDependence(), llvm::ScaledNumberBase::print(), processSDiv(), processSRem(), r0(), r1(), r2(), r3(), r4(), llvm::memprof::RecordLookupTrait::ReadData(), llvm::memprof::FrameLookupTrait::ReadData(), llvm::InstrProfLookupTrait::ReadKey(), llvm::memprof::RecordLookupTrait::ReadKey(), llvm::memprof::FrameLookupTrait::ReadKey(), llvm::InstrProfLookupTrait::ReadKeyDataLength(), llvm::memprof::RecordLookupTrait::ReadKeyDataLength(), llvm::memprof::FrameLookupTrait::ReadKeyDataLength(), llvm::SUnit::removePred(), llvm::MCContext::reportError(), llvm::MCContext::reportWarning(), resolveReferencedType(), rewriteMaterializableInstructions(), llvm::rustDemangle(), scale(), llvm::InstrProfValueSiteRecord::scale(), llvm::InstrProfRecord::scale(), llvm::AAPointerInfo::RangeList::set_difference(), llvm::DbgEntity::setDIE(), llvm::orc::SimpleRemoteEPCServer::Setup::setDispatcher(), llvm::GVNPass::ValueTable::setDomTree(), llvm::rdf::DefNode::setReachedDef(), llvm::Value::setValueSubclassData(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), SolveLinEquationWithOverflow(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::SIInstrInfo::splitFlatOffset(), llvm::stable_hash_combine(), swapAntiDependences(), llvm::swapToHostOrder(), llvm::TensorSpec::toJSON(), llvm::ScaledNumberBase::toString(), toStringAPFloat(), tryFactorization(), llvm::InstCombinerImpl::tryFactorizationFolds(), llvm::json::Value::Value(), llvm::xray::FDRTraceWriter::visit(), llvm::SCEVDivision::visitConstant(), visitMaskedMerge(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitXor(), zero(), and llvm::VPDef::~VPDef().
E
GCRegistry::Add<CoreCLRGC> E("coreclr", "CoreCLR-compatible GC") static
Referenced by llvm::OverlapStats::accumulateCounts(), llvm::OffloadEntriesInfoManager::actOnDeviceGlobalVarEntriesInfo(), llvm::AliasSetTracker::add(), llvm::LiveRangeUpdater::add(), addAllTypesFromDWP(), llvm::FunctionSummary::addCall(), llvm::SPIRV::DTSortableEntry::addDep(), llvm::DGNode< NodeType, EdgeType >::addEdge(), llvm::jitlink::Block::addEdge(), llvm::ImmutableGraphBuilder< GraphT >::addEdge(), llvm::SetTheory::addExpander(), llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::MachineBasicBlock::addLiveIn(), addLiveInRegs(), llvm::LPPassManager::addLoop(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), addMask(), llvm::MCContext::addMCGenDwarfLabelEntry(), addModuleFlags(), llvm::PressureDiff::addPressureChange(), llvm::InstrProfSummaryBuilder::addRecord(), addRegionIntoQueue(), llvm::LiveRegUnits::addRegsInMask(), llvm::LazyCallGraph::addSplitFunction(), llvm::LazyCallGraph::addSplitRefRecursiveFunctions(), llvm::WebAssemblyException::addSubException(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::GCNSubtarget::adjustSchedDependency(), advanceToMetaBlock(), llvm::AliasSet::aliasesPointer(), llvm::AliasSet::aliasesUnknownInst(), llvm::RegAllocBase::allocatePhysRegs(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::allowsMisalignedMemoryAccesses(), allPhiOperandsUndefined(), allSameBlock(), allSGPRSpillsAreDead(), allStackObjectsAreDead(), llvm::BitcodeAnalyzer::analyze(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::SIInstrInfo::analyzeBranch(), llvm::AIXCCState::AnalyzeCallOperands(), analyzeCompressibleUses(), analyzeExitPHIsForOutputUses(), llvm::InterleavedAccessInfo::analyzeInterleaving(), annotateAllFunctions(), llvm::orc::shared::TrivialSPSSequenceDeserialization< SPSElementTagT, std::vector< T > >::append(), llvm::orc::shared::TrivialSPSSequenceDeserialization< SPSElementTagT, SmallVectorImpl< T > >::append(), llvm::ErrorHandlerTraits< Error(&)(ErrT &)>::appliesTo(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::appliesTo(), llvm::ErrorHandlerTraits< Error(&)(std::unique_ptr< ErrT >)>::appliesTo(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::appliesTo(), llvm::HexagonSubtarget::UsrOverflowMutation::apply(), llvm::SampleProfileInference< BT >::apply(), llvm::BitVector::apply(), llvm::ErrorHandlerTraits< Error(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< Error(&)(std::unique_ptr< ErrT >)>::apply(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::apply(), llvm::jitlink::loongarch::applyFixup(), llvm::jitlink::i386::applyFixup(), llvm::jitlink::aarch64::applyFixup(), llvm::jitlink::x86_64::applyFixup(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::MachineFunction::assignBeginEndSections(), llvm::VarStreamArray< LineColumnEntry, LineColumnExtractor >::at(), bbHasFallthrough(), llvm::VarStreamArray< LineColumnEntry, LineColumnExtractor >::begin(), llvm::SUnit::biasCriticalPath(), llvm::rdf::DataFlowGraph::build(), llvm::objcopy::elf::ELFBuilder< ELFT >::build(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::SPIRVGeneralDuplicatesTracker::buildDepsGraph(), llvm::coro::Shape::buildFrom(), llvm::DICompositeType::buildODRType(), llvm::RISCVInstrInfo::buildOutlinedFrame(), llvm::LazyCallGraph::buildRefSCCs(), llvm::SITargetLowering::bundleInstWithWaitcnt(), llvm::ResourceManager::calculateResMII(), llvm::VirtRegAuxInfo::calculateSpillWeightsAndHints(), llvm::orc::shared::WrapperFunction< void(SPSTagTs...)>::callAsync(), llvm::Interpreter::callFunction(), canFallThroughTo(), llvm::AAResults::canInstructionRangeModRef(), llvm::RegAllocEvictionAdvisor::canReassign(), llvm::canReplaceOperandWithVariable(), llvm::cantFail(), llvm::SPIRVSubtarget::canUseExtension(), llvm::SPIRVSubtarget::canUseExtInstSet(), canUseSiblingCall(), CasesAreContiguous(), CC_AIX(), llvm::mca::ResourceManager::checkAvailability(), checkEFLAGSLive(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), checkOverlappingElement(), checkRegOnlyPHIInputs(), llvm::CallLowering::checkReturn(), llvm::HexagonMCExpr::classof(), llvm::LanaiMCExpr::classof(), llvm::CSKYMCExpr::classof(), llvm::AVRMCExpr::classof(), llvm::ARMMCExpr::classof(), llvm::X86MCExpr::classof(), llvm::RISCVMCExpr::classof(), llvm::MipsMCExpr::classof(), llvm::VEMCExpr::classof(), llvm::NVPTXFloatMCExpr::classof(), llvm::PPCMCExpr::classof(), llvm::LoongArchMCExpr::classof(), llvm::SparcMCExpr::classof(), llvm::NVPTXGenericMCSymbolRefExpr::classof(), llvm::AArch64MCExpr::classof(), llvm::MCConstantExpr::classof(), llvm::MCSymbolRefExpr::classof(), llvm::MCUnaryExpr::classof(), llvm::GVNExpression::DeadExpression::classof(), llvm::MCBinaryExpr::classof(), llvm::MCTargetExpr::classof(), llvm::vfs::RedirectingFileSystem::DirectoryEntry::classof(), llvm::vfs::RedirectingFileSystem::RemapEntry::classof(), llvm::vfs::RedirectingFileSystem::DirectoryRemapEntry::classof(), llvm::vfs::RedirectingFileSystem::FileEntry::classof(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::clear(), llvm::StringMap< uint64_t >::clear(), llvm::orc::SymbolStringPool::clearDeadEntries(), llvm::MCSubtargetInfo::ClearFeatureBitsTransitively(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::CloneAndPruneIntoFromInst(), combineCONCAT_VECTORS(), combineConcatVectorOps(), llvm::Combiner::combineMachineInstrs(), combineWeightsBySorting(), combineX86ShufflesRecursively(), llvm::pdb::InfoStreamBuilder::commit(), llvm::codeview::DebugInlineeLinesSubsection::commit(), llvm::DominanceFrontierBase< BasicBlock, false >::compare(), llvm::StringRef::compare_numeric(), compareCmp(), llvm::DominanceFrontierBase< BasicBlock, false >::compareDomSet(), llvm::ImutAVLFactory< ImutInfo >::compareTreeWithSection(), llvm::HvxSelector::completeToPerfect(), computeAddrMap(), llvm::mca::computeBlockRThroughput(), llvm::AccelTableBase::computeBucketCount(), llvm::rdf::Liveness::computeLiveIns(), llvm::computeMinimumValueSizes(), llvm::EHStreamer::computePadMap(), llvm::mca::computeProcResourceMasks(), llvm::object::computeSymbolSizes(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::computeValueLLTs(), llvm::DirectedGraph< NodeType, EdgeType >::connect(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), ConstantFold(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldVectorBinop(), constantIsDead(), ConstantPropUsersOf(), llvm::HexagonBlockRanges::IndexRange::contains(), llvm::ImmutableList< T >::contains(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::contains(), llvm::LiveRange::Segment::containsInterval(), llvm::MIRPrinter::convert(), llvm::MIRPrinter::convertStackObjects(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::GlobalObject::copyMetadata(), llvm::StackProtector::copyToMachineFrameInfo(), llvm::objcopy::xcoff::XCOFFReader::create(), llvm::symbolize::SymbolizableObjectFile::create(), llvm::objcopy::coff::COFFReader::create(), llvm::objcopy::macho::MachOReader::create(), llvm::memprof::RawMemProfReader::create(), llvm::AllocationOrder::create(), llvm::objcopy::NameOrPattern::create(), llvm::InstrProfReader::create(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::create(), llvm::object::ELFObjectFile< ELFT >::create(), llvm::InstrProfSymtab::create(), llvm::IndexedInstrProfReader::create(), llvm::object::COFFObjectFile::create(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::remarks::createBitstreamParserFromMeta(), createBSWAPShuffleMask(), createCast(), llvm::coverage::BinaryCoverageReader::createCoverageReaderFromBuffer(), llvm::DDGBuilder::createDefUseEdge(), createError(), llvm::createFileError(), llvm::pdb::DIASession::createFromPdb(), XtensaOperand::createImm(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::createMemoryDependencyEdges(), llvm::DDGBuilder::createMemoryEdge(), llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), createPtr(), XtensaOperand::createReg(), llvm::DDGBuilder::createRootedEdge(), CreateStepValue(), llvm::MDBuilder::createTBAATypeNode(), createTuple(), llvm::mca::InOrderIssueStage::cycleStart(), llvm::DCData::DCData(), llvm::RecyclingAllocator< llvm::BumpPtrAllocatorImpl, FinalizedAllocInfo >::Deallocate(), llvm::compression::zlib::decompress(), llvm::objcopy::deepWriteArchive(), llvm::DenseMap< llvm::SmallVector< llvm::VPValue *, 4 >, llvm::VPInstruction *, BundleDenseMapInfo >::DenseMap(), llvm::detail::DenseSetImpl< Instruction *, DenseMap< Instruction *, detail::DenseSetEmpty, DenseMapInfo< Instruction * >, detail::DenseSetPair< Instruction * > >, DenseMapInfo< Instruction * > >::DenseSetImpl(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::deserialize(), llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::deserialize(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::destroyAll(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::destroyEdge(), determineSVEStackObjectOffsets(), llvm::DGNode< NodeType, EdgeType >::DGNode(), llvm::PBQP::Graph< RegAllocSolverImpl >::disconnectEdge(), llvm::DistributeRange(), llvm::dlltoolDriverMain(), llvm::AsmPrinter::doFinalization(), llvm::DominatorTree::dominates(), doPromotion(), doRematerializations(), llvm::MDNode::dropAllReferences(), llvm::VPBasicBlock::dropAllReferences(), llvm::SDNode::DropOperands(), llvm::ForeachLoop::dump(), llvm::DWARFDebugPubTable::dump(), llvm::MultiClass::dump(), llvm::DbgValueHistoryMap::dump(), llvm::DWARFContext::dump(), llvm::mca::RegisterFile::dump(), llvm::coverage::CounterMappingContext::dump(), llvm::ScaledNumberBase::dump(), false::dump_node_container(), dumpEdges(), llvm::DWARFLocationTable::dumpLocationList(), dumpLoclistsSection(), dumpMachineInstrRangeWithSlotIndex(), dumpRemats(), llvm::objcopy::wasm::dumpSectionToFile(), dumpSectionToFile(), dumpSpills(), llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::edge_dest(), llvm::GraphTraits< const CallGraphNode * >::edge_dest(), llvm::GraphTraits< DotCfgDiffDisplayGraph * >::edge_dest(), llvm::GraphTraits< ValueInfo >::edge_dest(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::MCDwarfFrameEmitter::Emit(), llvm::TargetLoweringObjectFile::emitCGProfileMetadata(), llvm::EHStreamer::emitExceptionTable(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::CodeViewContext::emitLineTableForFunction(), emitLocList(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::RuntimeDyldImpl::emitSection(), emitSelectPseudo(), llvm::MCStreamer::emitWinCFIEndProc(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::WinEH::FrameInfo::empty(), llvm::LazyCallGraph::EdgeSequence::empty(), llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc(), llvm::CodeViewContext::encodeDefRange(), llvm::PPCMCCodeEmitter::encodeInstruction(), llvm::TimeTraceProfiler::end(), llvm::VarStreamArray< LineColumnEntry, LineColumnExtractor >::end(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::equal_range(), llvm::TypeFinder::erase(), llvm::sampleprof::DefaultFunctionPruningStrategy::Erase(), llvm::SmallSet< unsigned, 16 >::erase(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::erase(), llvm::TinyPtrVector< llvm::VPValue * >::erase(), llvm::SmallVectorImpl< uint64_t >::erase(), llvm::MachineBasicBlock::erase(), llvm::PriorityWorklist< llvm::LazyCallGraph::SCC *, SmallVector< llvm::LazyCallGraph::SCC *, N >, SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t > >::erase_if(), llvm::remarks::YAMLRemarkParser::error(), llvm::InstrProfReader::error(), EstimateRuntime(), llvm::coverage::CounterMappingContext::evaluate(), EvaluateCRExpr(), llvm::execMayBeModifiedBeforeUse(), llvm::mca::InstructionTables::execute(), llvm::mca::InOrderIssueStage::execute(), llvm::VPWidenGEPRecipe::execute(), llvm::objcopy::xcoff::executeObjcopyOnBinary(), llvm::objcopy::macho::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::wasm::executeObjcopyOnBinary(), llvm::objcopy::coff::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnIHex(), llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary(), llvm::objcopy::elf::executeObjcopyOnRawBinary(), llvm::ScalarEvolution::ExitLimit::ExitLimit(), llvm::expectedToOptional(), llvm::expectedToStdOptional(), llvm::ModuleSummaryIndex::exportToDot(), llvm::BitTracker::MachineEvaluator::eXTR(), llvm::DWARFListTableBase< DWARFDebugRnglist >::extract(), llvm::DWARFDebugNames::Header::extract(), llvm::BitTracker::RegisterCell::extract(), llvm::DWARFDebugNames::NameIndex::extract(), llvm::DWARFDebugNames::extract(), extractConstantWithoutWrapping(), extractValues(), fatalOpenError(), llvm::BitTracker::RegisterCell::fill(), llvm::opt::ArgList::filtered(), llvm::opt::ArgList::filtered_reverse(), llvm::DIBuilder::finalize(), llvm::AccelTableBase::finalize(), llvm::objcopy::elf::ELFWriter< ELFT >::finalize(), llvm::objcopy::elf::IHexWriter::finalize(), llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), llvm::finalizeBundle(), llvm::MCWinCOFFStreamer::finalizeCGProfile(), llvm::SITargetLowering::finalizeLowering(), llvm::SMSchedule::finalizeSchedule(), llvm::SmallPtrSetImplBase::find_imp(), findAlignmentLowerBound(), llvm::CodeExtractor::findAllocas(), findArrayDimensionsRec(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::opt::OptTable::findByPrefix(), findCommonType(), llvm::X86RegisterInfo::findDeadCallerSavedReg(), findDominatingValue(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), llvm::DGNode< NodeType, EdgeType >::findEdgesTo(), llvm::DGNode< NodeType, EdgeType >::findEdgeTo(), llvm::SSAUpdaterImpl< UpdaterT >::FindExistingPHI(), findGlueUse(), findInitTrampolineFromBB(), findIrreducibleHeaders(), FindLastAluClause(), llvm::pdb::SymbolCache::findLineNumbersByVA(), llvm::DWARFListTableBase< DWARFDebugRnglist >::findList(), llvm::MCJIT::findModuleForSymbol(), findPartitions(), llvm::findPHICopyInsertPoint(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), findPotentialBlockers(), llvm::DWARFUnit::findRnglistFromOffset(), findSafeStoreForStoreStrongContraction(), findStrip(), findUser(), first_use_of_in_block(), firstCommonClass(), llvm::MipsMCExpr::fixELFSymbolsInTLSFixups(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), llvm::SelectionDAG::FoldConstantArithmetic(), foldGEPOfGEP(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::InstCombinerImpl::foldPHIArgGEPIntoPHI(), llvm::format_provider< Enum, std::enable_if_t< dwarf::EnumTraits< Enum >::value > >::format(), llvm::format_provider< llvm::json::Value >::format(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), llvm::json::fromJSON(), gatherFileIDs(), llvm::MipsInstrInfo::genInstrWithNewOpc(), llvm::get(), llvm::ImmutableGraphBuilder< GraphT >::get(), llvm::AttributeList::get(), llvm::VarListElementInit::get(), llvm::DWARFDebugRnglist::getAbsoluteRanges(), llvm::DWARFDebugRangeList::getAbsoluteRanges(), getAccelTable(), llvm::SelectionDAG::getAddrSpaceCast(), llvm::MLInlineAdvisor::getAdviceImpl(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::SelectionDAG::getAssertAlign(), llvm::AttributeSetNode::getAsString(), llvm::SelectionDAG::getAtomic(), llvm::getAttributeBasedInliningDecision(), llvm::object::COFFObjectFile::getAuxSymbol(), llvm::SelectionDAG::getBasicBlock(), llvm::MemoryPhi::getBasicBlockIndex(), llvm::SelectionDAG::getBlockAddress(), llvm::object::ELFObjectFile< ELFT >::getBuildAttributes(), getBundledUseMI(), llvm::DebugLocStream::getBytes(), llvm::getCallsiteCost(), llvm::DebugLocStream::getComments(), llvm::ExactEqualsExpression::getComputedHash(), llvm::SelectionDAG::getConstantPool(), llvm::IntervalTree< LVAddress, LVScope * >::getContaining(), llvm::TargetRegisterInfo::getCoveringSubRegIndexes(), llvm::AArch64::getCpuSupportsMask(), llvm::DWARFContext::getDebugFrame(), llvm::AMDGPURegisterBankInfo::getDefaultMappingAllVGPR(), llvm::PPCInstrInfo::getDefMIPostRA(), llvm::object::ExportDirectoryEntryRef::getDllName(), getEarliestInsertPos(), llvm::DOTGraphTraits< MachineGadgetGraph * >::getEdgeAttributes(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::getEdgeIndex(), llvm::PBQP::Graph< RegAllocSolverImpl >::getEdgeOtherNodeId(), llvm::BranchProbabilityInfo::getEdgeProbability(), llvm::DWARFContext::getEHFrame(), getEmscriptenInvokeSymbolName(), llvm::BitstreamEntry::getEndBlock(), llvm::MachineTraceMetrics::getEnsemble(), llvm::NonRelocatableStringpool::getEntriesForEmission(), llvm::DWARFDebugNames::NameIndex::getEntry(), llvm::objcarc::getEquivalentPHIs(), llvm::BitstreamEntry::getError(), llvm::ConstantExpr::getExactLogBase2(), llvm::SystemZConstantPoolValue::getExistingMachineCPValue(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::AArch64::getExtensionFeatures(), llvm::PseudoSourceValueManager::getExternalSymbolCallEntry(), getExtractIndex(), llvm::VarStreamArray< LineColumnEntry, LineColumnExtractor >::getExtractor(), llvm::MachineBasicBlock::getFirstInstrTerminator(), llvm::MachineBasicBlock::getFirstNonPHI(), getFirstReloc(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::jitlink::Block::getFixupAddress(), llvm::SelectionDAG::getFrameIndex(), llvm::DWARFUnitIndex::getFromOffset(), llvm::IndexedInstrProfReader::getFunctionCounts(), llvm::SelectionDAG::getGatherVP(), llvm::SelectionDAG::getGlobalAddress(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::PseudoSourceValueManager::getGlobalValueCallEntry(), getHashForUdt(), llvm::IRSimilarity::IRInstructionDataTraits::getHashValue(), llvm::DenseMapInfo< const Expression * >::getHashValue(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::object::COFFObjectFile::getHintName(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForRISCV(), llvm::sys::detail::getHostCPUNameForS390x(), llvm::object::DelayImportDirectoryEntryRef::getImportAddress(), llvm::SlotIndexes::getIndexAfter(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getIndexedStoreVP(), llvm::SelectionDAG::getIndexedStridedStoreVP(), getInsertPt(), llvm::SIInstrInfo::getInstBundleSize(), getInstrBB(), llvm::SIInstrInfo::getInstrLatency(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::SIInstrInfo::getInstructionUniformity(), llvm::SIInstrInfo::getInstSizeInBytes(), llvm::SelectionDAG::getJumpTable(), llvm::SelectionDAG::getLabelNode(), getLatestInsertPos(), llvm::SelectionDAG::getLifetimeNode(), GetLinearExpression(), getLiveInRegsAt(), getLiveOutRegsAt(), llvm::getLiveRegMap(), llvm::getLiveRegs(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLoadVP(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), getMaskedTypeForICmpPair(), getMaxCalleeSavedReg(), llvm::coverage::CounterMappingContext::getMaxCounterID(), llvm::M68kRegisterInfo::getMaximalPhysRegClass(), llvm::LLVMContext::getMDKindNames(), llvm::SelectionDAG::getMDNode(), llvm::SelectionDAG::getMemIntrinsicNode(), getMemoryBufferForStream(), llvm::AAResults::getModRefInfo(), llvm::object::ImportDirectoryEntryRef::getName(), llvm::object::DelayImportDirectoryEntryRef::getName(), llvm::rdf::Liveness::getNearestAliasedRef(), getNextBlock(), getNextMachineInstrInBB(), llvm::SlotIndexes::getNextNonNullIndex(), llvm::SelectionDAG::getNode(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeAttributes(), llvm::SelectionDAG::getNodeIfExists(), getNonDebugInstr(), getNumberOfRelocations(), llvm::EquivalenceClasses< llvm::Instruction * >::getNumClasses(), llvm::MachineInstr::getNumExplicitDefs(), llvm::MachineInstr::getNumExplicitOperands(), llvm::ARMBaseInstrInfo::getNumLDMAddresses(), llvm::object::getObject(), getObject(), llvm::TargetTransformInfo::getOperandInfo(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperandsScalarizationOverhead(), llvm::DwarfExpression::getOrCreateBaseType(), llvm::DIBuilder::getOrCreateTypeArray(), llvm::vputils::getOrCreateVPValueForSCEVExpr(), llvm::FoldingSetBase::GetOrInsertNode(), getOrSelfReference(), llvm::RISCVInstrInfo::getOutliningCandidateInfo(), getOutputSegmentMap(), getPdbPathFromExe(), llvm::HvxSelector::getPerfectCompletions(), getPerfectShuffleCost(), llvm::SelectionDAG::getPseudoProbeNode(), llvm::object::XCOFFObjectFile::getRawData(), llvm::MCSubtargetInfo::getReadAdvanceCycles(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::BitstreamEntry::getRecord(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords(), llvm::SelectionDAG::getRegister(), llvm::MipsMCCodeEmitter::getRegisterListOpValue(), llvm::SelectionDAG::getRegisterMask(), llvm::RegsForValue::getRegsAndSizes(), llvm::getRegSequenceSubReg(), llvm::CCState::getRemainingRegParmsForType(), llvm::jitlink::getRISCVPCRelHi20(), getSameOpcode(), getSavedReg(), llvm::SelectionDAG::getScatterVP(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), llvm::object::XCOFFObjectFile::getSectionContents(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::XCOFFObjectFile::getSectionFileOffsetToRawData(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::getShuffleDemandedElts(), llvm::BasicBlock::getSinglePredecessor(), llvm::BasicBlock::getSingleSuccessor(), getSourceLineHash(), llvm::X86InstrInfo::getSPAdjust(), llvm::ConstantVector::getSplatValue(), llvm::SelectionDAG::getSrcValue(), llvm::InstrItineraryData::getStageLatency(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getStoreVP(), llvm::SelectionDAG::getStridedLoadVP(), llvm::SelectionDAG::getStridedStoreVP(), GetStringLengthH(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::BitstreamEntry::getSubBlock(), llvm::object::ExportDirectoryEntryRef::getSymbolName(), getSymbols(), llvm::object::ObjectFile::getSymbolValue(), llvm::IndexedInstrProfReader::getSymtab(), getTagRecordHashForUdt(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTargetIndex(), getTargetMBB(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::getTotalMemory(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getTruncStoreVP(), llvm::SelectionDAG::getTruncStridedStoreVP(), llvm::BasicBlock::getUniquePredecessor(), llvm::BasicBlock::getUniqueSuccessor(), llvm::DWARFUnitVector::getUnitForIndexEntry(), getUnmergePieces(), getUUID(), llvm::SelectionDAG::getVectorShuffle(), llvm::object::ELFFile< ELFT >::getVersionDependencies(), getWaitStatesSince(), llvm::SmallDenseMap< const llvm::RecurrenceDescriptor *, unsigned, N >::grow(), llvm::handleAllErrors(), llvm::objcopy::wasm::handleArgs(), llvm::objcopy::coff::handleArgs(), handleArgs(), handleCompressedSection(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), llvm::handleErrors(), llvm::handleExecNameEncodedBEOpts(), llvm::handleExecNameEncodedOptimizerOpts(), HandleInlinedEHPad(), HandleInlinedLandingPad(), handleMaybeNoDataFoundError(), llvm::LiveIntervals::handleMoveIntoNewBundle(), llvm::GEPOperator::hasAllConstantIndices(), llvm::GEPOperator::hasAllZeroIndices(), hasAnyUnrollPragma(), llvm::SDNode::hasAnyUseOfValue(), llvm::AttributeListImpl::hasAttrSomewhere(), llvm::MachineInstr::hasComplexRegisterTies(), llvm::BitCodeAbbrevOp::hasEncodingData(), llvm::Constant::hasExactInverseFP(), hasField(), llvm::ItaniumPartialDemangler::hasFunctionQualifiers(), hasHazard(), hasLiveThroughUse(), llvm::SITargetLowering::hasMemSDNodeUser(), llvm::coverage::InstantiationGroup::hasName(), HasNestArgument(), llvm::SDNode::hasNUsesOfValue(), hasOnlyUniformBranches(), hasProfileData(), hasReturnsTwiceAttr(), llvm::hasSingleElement(), llvm::HexagonInstrInfo::hasUncondBranch(), haveSameOperands(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), hoistAndMergeSGPRInits(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::identifyObject(), ignoreStrippedErrors(), indirectCopyToAGPR(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::initEmpty(), INITIALIZE_PASS(), llvm::DbgVariable::initializeDbgValue(), llvm::DbgVariable::initializeMMI(), llvm::mca::initializeUsedResources(), llvm::ResourceManager::initProcResourceVectors(), llvm::ScheduleDAGMI::initQueues(), llvm::InlineFunction(), llvm::json::Object::insert(), llvm::ValueMap< const Function *, FuncInfo >::insert(), llvm::json::Array::insert(), llvm::SmallSet< unsigned, 16 >::insert(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::insert(), llvm::detail::DenseSetImpl< Instruction *, DenseMap< Instruction *, detail::DenseSetEmpty, DenseMapInfo< Instruction * >, detail::DenseSetPair< Instruction * > >, DenseMapInfo< Instruction * > >::insert(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::insert(), llvm::BitTracker::RegisterCell::insert(), llvm::NodeSet::insert(), llvm::SmallPtrSetImpl< const BlockT * >::insert(), llvm::MachineBasicBlock::insert(), llvm::SmallPtrSetImplBase::insert_imp(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::LiveIntervals::InsertMachineInstrRangeInMaps(), insertNoDuplicates(), insertSpills(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), insertValues(), interChangeDependencies(), interleaveIntList(), interleaveStringList(), llvm::IntervalPartition::IntervalPartition(), llvm::MachineTraceMetrics::invalidate(), llvm::AnalysisManager< MachineFunction >::invalidate(), llvm::inversePermutation(), llvm::LazyCallGraph::SCC::isAncestorOf(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), isBlock(), isBlockValidForExtraction(), llvm::isBytewiseValue(), llvm::SITargetLowering::isCanonicalized(), isConcatMask(), isCondRelevantToAnyCallArgument(), llvm::isCriticalEdge(), isDenselyPacked(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), isEphemeralValueOf(), llvm::DGEdge< NodeType, EdgeType >::isEqualTo(), llvm::X86MCExpr::isEqualTo(), isError(), llvm::Constant::isFiniteNonZeroFP(), isFixedVectorShuffle(), isFNEG(), isIdentity(), isKnownNonNaN(), isKnownNonZero(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), llvm::ARM_MC::isLDMBaseRegInList(), llvm::R600InstrInfo::isLegalToSplitMBBAt(), isLRAvailable(), llvm::Constant::isNaN(), llvm::Constant::isNormalFP(), llvm::Constant::isNotMinSignedValue(), llvm::Constant::isNotOneValue(), isOnlyReachableViaThisEdge(), llvm::LazyCallGraph::SCC::isParentOf(), llvm::LazyCallGraph::RefSCC::isParentOf(), isPoisonShift(), llvm::ARMBaseInstrInfo::isPredicated(), isProfitableToInterleave(), llvm::VirtRegAuxInfo::isRematerializable(), isRepeatedNonIdentityClusteredMask(), IsSafeAndProfitableToMove(), isSafeAndProfitableToSinkLoad(), llvm::ReachingDefAnalysis::isSafeToDefRegAt(), llvm::isSafeToLoadUnconditionally(), isSafeToMove(), llvm::ReachingDefAnalysis::isSafeToMoveBackwards(), llvm::ReachingDefAnalysis::isSafeToMoveForwards(), isScalarToVector(), isSignExtendedW(), llvm::ShuffleVectorInst::isSpliceMask(), isSSA(), llvm::DIExpression::isValid(), llvm::BitCodeAbbrevOp::isValidEncoding(), llvm::LiveRange::join(), llvm::BitTracker::BitMask::last(), layout(), llvm::SelectionDAG::Legalize(), llvm::SIInstrInfo::legalizeOperands(), llvm::libDriverMain(), likeBitCastFromVector(), llvm::remarks::RemarkLinker::link(), LLVMGetSectionContents(), LLVMPrintModuleToFile(), LLVMRemarkParserGetNext(), llvm::LLVMRemarkSetupErrorInfo< LLVMRemarkSetupFileError >::LLVMRemarkSetupErrorInfo(), llvm::coverage::CoverageMapping::load(), loadBinaryFormat(), llvm::xray::loadInstrumentationMap(), loadObj(), llvm::xray::loadProfile(), loadTestingFormat(), llvm::xray::loadTrace(), llvm::localCache(), llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::lookup(), llvm::LazyCallGraph::EdgeSequence::lookup(), llvm::vfs::RedirectingFileSystemParser::lookupOrCreateEntry(), llvm::WebAssemblyMCInstLower::lower(), llvm::FastISel::lowerArguments(), LowerBUILD_VECTORAsVariablePermute(), LowerBUILD_VECTORvXbf16(), llvm::VETargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::FastISel::lowerCallTo(), LowerCONCAT_VECTORS_i1(), llvm::R600AsmPrinter::lowerConstant(), llvm::AMDGPUAsmPrinter::lowerConstant(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), llvm::LanaiTargetLowering::LowerMUL(), llvm::TargetLowering::LowerOperationWrapper(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), lowerToAddSubOrFMAddSub(), llvm::LegalizerHelper::lowerU64ToF32BitOps(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), llvm::codeview::make_error_code(), llvm::pdb::make_error_code(), llvm::msf::make_error_code(), llvm::coverage::make_error_code(), llvm::make_error_code(), llvm::make_fallible_end(), llvm::jitlink::makeAlignmentError(), llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::makeSafe(), llvm::jitlink::makeTargetOutOfRangeError(), mangleCoveragePath(), llvm::json::ObjectMapper::map(), llvm::json::ObjectMapper::mapOptional(), llvm::yaml::MappingTraits< ArchYAML::Archive::Child >::mapping(), llvm::yaml::MappingTraits< ELFYAML::StackSizeEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::BBAddrMapEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::BBAddrMapEntry::BBEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::GnuHashHeader >::mapping(), llvm::yaml::MappingTraits< ELFYAML::VerdefEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::VerneedEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::VernauxEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::CallGraphEntryWeight >::mapping(), llvm::yaml::MappingTraits< ELFYAML::ARMIndexTableEntry >::mapping(), markAliveBlocks(), llvm::maskIsAllOneOrUndef(), llvm::maskIsAllZeroOrUndef(), MatchDiv(), llvm::Intrinsic::matchIntrinsicSignature(), MatchMul(), MatchRem(), matchScalarInAggregate(), llvm::matchUnaryPredicate(), memOpsHaveSameBaseOperands(), llvm::InstrProfRecord::merge(), mergeConditionalStoreToAddress(), mergeInlinedArrayAllocas(), mergeOperations(), llvm::VPlanTransforms::mergeReplicateRegionsIntoSuccessors(), llvm::MIBundleBuilder::MIBundleBuilder(), llvm::LegalizerHelper::moreElementsVectorPhi(), llvm::SelectionDAG::MorphNodeTo(), llvm::IRMover::move(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::moveFromOldBuckets(), moveInstrOut(), llvm::InjectorIRStrategy::mutate(), llvm::InstDeleterIRStrategy::mutate(), llvm::InsertCFGStrategy::mutate(), llvm::InsertPHIStrategy::mutate(), llvm::SinkInstructionStrategy::mutate(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarAddSub(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarSelect(), nearest_common_dominatee(), nearest_common_dominator(), needsFP(), llvm::remarks::BitstreamRemarkParser::next(), llvm::SelectionDAG::DAGNodeDeletedListener::NodeDeleted(), llvm::mca::ExecuteStage::notifyReservedOrReleasedBuffers(), llvm::MLInlineAdvisor::onPassEntry(), llvm::vfs::OverlayFileSystem::openFileForRead(), operator delete(), llvm::DGEdge< NodeType, EdgeType >::operator!=(), llvm::BitmaskEnumDetail::operator&(), llvm::FeatureBitset::operator&=(), llvm::SmallBitVector::operator&=(), llvm::jitlink::SEHFrameKeepAlivePass::operator()(), llvm::jitlink::CompactUnwindSplitter::operator()(), llvm::ExitOnError::operator()(), llvm::LessRecordRegister::operator()(), llvm::coverage::CoverageMappingIterator::operator*(), llvm::LazyCallGraph::EdgeSequence::iterator::operator++(), llvm::coverage::CoverageMappingIterator::operator->(), llvm::FeatureBitset::operator<(), llvm::operator<<(), llvm::GVNExpression::operator<<(), llvm::rdf::operator<<(), llvm::DGEdge< NodeType, EdgeType >::operator=(), llvm::EquivalenceClasses< llvm::Instruction * >::operator=(), llvm::DDGEdge::operator=(), llvm::DGEdge< NodeType, EdgeType >::operator==(), llvm::pdb::SymbolGroupIterator::operator==(), llvm::detail::operator==(), llvm::operator==(), llvm::ConstantAggrKeyType< ConstantClass >::operator==(), llvm::ExactEqualsExpression::operator==(), llvm::ConstantExprKeyType::operator==(), llvm::SmallBitVector::operator==(), llvm::LazyCallGraph::EdgeSequence::operator[](), llvm::BitmaskEnumDetail::operator^(), llvm::FeatureBitset::operator^=(), llvm::BitVector::operator^=(), llvm::SmallBitVector::operator^=(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::OperatorInfo(), llvm::BitmaskEnumDetail::operator|(), llvm::FeatureBitset::operator|=(), llvm::BitVector::operator|=(), llvm::SmallBitVector::operator|=(), llvm::BitmaskEnumDetail::operator~(), OptimizeAwayTrappingUsesOfValue(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), optimizeDivRem(), OptimizeExtractBits(), llvm::jitlink::i386::optimizeGOTAndStubAccesses(), llvm::jitlink::x86_64::optimizeGOTAndStubAccesses(), llvm::VPlanTransforms::optimizeInductions(), llvm::SMSchedule::orderDependence(), llvm::SystemZELFFrameLowering::orderFrameObjects(), llvm::InstrProfRecord::overlap(), llvm::HexagonBlockRanges::IndexRange::overlaps(), packCmovGroup(), packSegmentMask(), llvm::BinaryStreamWriter::padToAlignment(), llvm::TargetLowering::parametersInCSRMatch(), llvm::DWARFDebugLine::Prologue::parse(), llvm::SpecialCaseList::parse(), llvm::object::WindowsResourceParser::parse(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::objcopy::elf::IHexRecord::parse(), llvm::json::parse(), llvm::vfs::RedirectingFileSystemParser::parse(), llvm::RISCVISAInfo::parseArchString(), parseBackslash(), parseBitcodeFileImpl(), parseBlock(), llvm::InlineAsm::ParseConstraints(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseConversionExpr(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseDecltype(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseExpr(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseFunctionType(), llvm::remarks::BitstreamRemarkParser::parseMeta(), parsePhysicalReg(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parsePrefixExpr(), llvm::remarks::BitstreamRemarkParser::parseRemark(), llvm::remarks::YAMLRemarkParser::parseRemark(), llvm::Pattern::parseVariable(), PerformADDVecReduce(), performCopyPropagation(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performExtractsShuffleAction(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::performOptimizedStructLayout(), PerformReduceShuffleCombine(), PerformTruncatingStoreCombine(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::ConvergingVLIWScheduler::pickNodeFromQueue(), llvm::LatencyPriorityQueue::pop(), llvm::ResourcePriorityQueue::pop(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::populateRemappings(), llvm::PrepareToSplitEntryBlock(), llvm::LiveStacks::print(), llvm::DominanceFrontierBase< BasicBlock, false >::print(), llvm::MIPrinter::print(), llvm::AliasSet::print(), llvm::print(), llvm::MachineOperand::print(), llvm::ScaledNumberBase::print(), llvm::LoopBase< BasicBlock, Loop >::print(), llvm::MachineFunction::print(), llvm::LiveRangeUpdater::print(), llvm::LoopInfoBase< BasicBlock, Loop >::print(), llvm::MachineBasicBlock::print(), llvm::VPBlendRecipe::print(), llvm::VPlanIngredient::print(), printBinaryIdsInternal(), llvm::WebAssemblyInstPrinter::printBrList(), llvm::printCompactDWARFExpr(), printCustomRegMask(), llvm::PrintDomTree(), llvm::jitlink::printEdge(), llvm::SampleProfileLoaderBaseImpl< MachineBasicBlock >::printEdgeWeight(), llvm::vfs::RedirectingFileSystem::printEntry(), llvm::WebAssemblyInstPrinter::printInst(), ParameterPackExpansion::printLeft(), printMCExpr(), printName(), printNode(), printNodeDOT(), printSpillReloadChain(), processLoadCommands(), processPSInputArgs(), llvm::xray::profileFromTrace(), promoteIndirectCalls(), promoteMemoryToRegister(), llvm::propagateMetadata(), llvm::SampleProfileLoaderBaseImpl< MachineBasicBlock >::propagateThroughEdges(), llvm::jitlink::prune(), llvm::LiveIntervals::pruneValue(), llvm::json::Array::push_back(), llvm::LiveRange::Query(), r0(), r1(), r2(), r3(), r4(), llvm::memprof::RawMemProfReader::RawMemProfReader(), llvm::support::endian::read(), llvm::support::endian::read16(), llvm::support::endian::read32(), llvm::support::endian::read64(), llvm::BitstreamCursor::ReadAbbrevRecord(), readCoverageMappingData(), llvm::AMDGPUPALMetadata::readFromIR(), llvm::IndexedInstrProfReader::readHeader(), llvm::TextInstrProfReader::readNextRecord(), llvm::RawInstrProfReader< IntPtrT >::readNextRecord(), llvm::IndexedInstrProfReader::readNextRecord(), llvm::readPGOFuncNameStrings(), llvm::R600InstrInfo::readsLDSSrcReg(), llvm::ConvergingVLIWScheduler::readyQueueVerboseDump(), llvm::PBQP::Graph< RegAllocSolverImpl >::reconnectEdge(), llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs(), llvm::LessRecordRegister::RecordParts::RecordParts(), llvm::RecursivelyDeleteTriviallyDeadInstructionsPermissive(), llvm::LegalizerHelper::reduceLoadStoreWidth(), regIsPICBase(), registerJITLoaderGDBImpl(), llvm::StringMapImpl::RehashTable(), llvm::rdf::DataFlowGraph::releaseBlock(), llvm::ConvergingVLIWScheduler::releaseBottomNode(), llvm::MachineTraceMetrics::releaseMemory(), llvm::SchedBoundary::releasePending(), llvm::pdb::PublicsStream::reload(), llvm::pdb::ModuleDebugStreamRef::reload(), llvm::pdb::GlobalsStream::reload(), llvm::object::XCOFFObjectFile::relocations(), llvm::MapVector< AssertingVH< Instruction >, AssertingVH< Value > >::remove_if(), llvm::DominanceFrontierBase< BasicBlock, false >::removeBlock(), RemoveDeadAddBetweenLEAAndJT(), llvm::FastISel::removeDeadCode(), llvm::Constant::removeDeadConstantUsers(), llvm::SIMachineFunctionInfo::removeDeadFrameIndices(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::DGNode< NodeType, EdgeType >::removeEdge(), llvm::PBQP::Graph< RegAllocSolverImpl >::removeEdge(), removeExternalCFGSuccessors(), removeGlobalCtors(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::ExecutionEngine::removeModule(), llvm::DirectedGraph< NodeType, EdgeType >::removeNode(), llvm::PMDataManager::removeNotPreservedAnalysis(), removeOldExitPreds(), llvm::CallBase::removeOperandBundle(), llvm::LiveRegUnits::removeRegsNotPreserved(), llvm::objcopy::elf::Object::removeSections(), llvm::objcopy::elf::Object::removeSymbols(), llvm::MachineFunction::RenumberBlocks(), reorderOrder(), reorderReuses(), llvm::reorderScalars(), ReplaceAddWithADDP(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::VPValue::replaceAllUsesWith(), replaceAllUsesWith(), replaceAndRemoveSections(), replaceConstantExprOp(), llvm::PPCFrameLowering::replaceFPWithRealFP(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::ConstantUniqueMap< llvm::ConstantExpr >::replaceOperandsInPlace(), llvm::objcopy::elf::Object::replaceSections(), llvm::MachineBasicBlock::replaceSuccessor(), llvm::Thumb2InstrInfo::ReplaceTailWithBranchTo(), llvm::User::replaceUsesOfWith(), rescheduleCanonically(), llvm::BitVector::reset(), llvm::SmallBitVector::reset(), llvm::SmallBitVector::resize(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::resolveForwardTemplateRefs(), llvm::ListInit::resolveReferences(), llvm::mca::ResourceManager::ResourceManager(), rewriteGEPAsOffset(), rewriteMaterializableInstructions(), RewriteUsesOfClonedInstructions(), llvm::HvxSelector::rotationDistance(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run(), llvm::InstrProfiling::run(), llvm::AMDGPUSimplifyLibCallsPass::run(), llvm::AMDGPUUseNativeCallsPass::run(), llvm::CallGraphSCCsPrinterPass::run(), llvm::IntervalPartition::runOnFunction(), llvm::InsertNOPLoad::runOnMachineFunction(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::FixAllFDIVSQRT::runOnMachineFunction(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithLoopNestPasses(), llvm::orc::shared::WrapperFunctionCall::runWithSPSRet(), scalarConstantToHexString(), llvm::R600SchedStrategy::schedNode(), llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer(), llvm::object::XCOFFObjectFile::section_rel_begin(), llvm::object::XCOFFObjectFile::section_rel_end(), llvm::LiveRange::Segment::Segment(), llvm::mca::Scheduler::select(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FastISel::selectGetElementPtr(), llvm::FastISel::selectStackmap(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > >::serialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::serialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >::serialize(), llvm::BitVector::set(), llvm::SmallBitVector::set(), llvm::set_intersect(), llvm::object::ELFObjectFileBase::setARMSubArch(), llvm::MIRProfileLoader::setBranchProbs(), llvm::IndexedInstrProf::Summary::setEntry(), llvm::opt::OptTable::setInitialOptionsFromEnvironment(), llvm::Module::setModuleFlag(), llvm::setupLLVMOptimizationRemarks(), llvm::lto::setupLLVMOptimizationRemarks(), llvm::RecordVal::setValue(), llvm::HexagonRegisterInfo::shouldCoalesce(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::simplify(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::SimplifyInstructionsInBlock(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), sinkAndCmp0Expression(), SinkCast(), sinkCmpExpression(), sinkLastInstruction(), llvm::SIRegisterInfo::SIRegisterInfo(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >::size(), llvm::rdf::DataFlowGraph::DefStack::size(), llvm::MachineBasicBlock::sizeWithoutDebugLargerThan(), skipPGO(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), llvm::MachineBasicBlock::SkipPHIsLabelsAndDebug(), llvm::SmallDenseMap< const llvm::RecurrenceDescriptor *, unsigned, N >::SmallDenseMap(), llvm::SmallPtrSet< AssumeInst *, 4 >::SmallPtrSet(), llvm::SmallVector< llvm::cl::parser::OptionInfo, 8 >::SmallVector(), sortOpts(), llvm::MachineBasicBlock::splitAt(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SplitIndirectBrCriticalEdges(), splitRetconCoroutine(), llvm::StackMapParser< Endianness >::StackMapParser(), llvm::sys::path::starts_with(), llvm::vfs::OverlayFileSystem::status(), llvm::StringMap< uint64_t >::StringMap(), stripDeadDebugInfoImpl(), llvm::opt::OptTable::suggestValueCompletions(), sumEdgeCount(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), SwitchToLookupTable(), llvm::InstrProfError::take(), llvm::SoftInstrProfErrors::takeError(), llvm::cl::TokenizeGNUCommandLine(), tokenizeWindowsCommandLineImpl(), llvm::object::ELFFile< ELFT >::toMappedAddr(), llvm::orc::shared::detail::toSPSSerializable(), llvm::AMDGPUPALMetadata::toString(), llvm::dwarf::toString(), llvm::ScaledNumberBase::toString(), llvm::detail::IEEEFloat::toString(), llvm::toString(), toStringAPFloat(), transferSRADebugInfo(), llvm::ImmutableGraphBuilder< GraphT >::trim(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), TryToShrinkGlobalToBoolean(), TryToSinkInstruction(), llvm::JumpThreadingPass::tryToUnfoldSelect(), tryToVectorizeSequence(), llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy(), llvm::SmallVectorTemplateBase< T, true >::uninitialized_copy(), llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move(), llvm::SmallVectorTemplateBase< T, true >::uninitialized_move(), llvm::MemoryPhi::unorderedDeleteIncoming(), llvm::MemoryPhi::unorderedDeleteIncomingIf(), llvm::unwrap(), UpdateCallGraphAfterInlining(), llvm::MemorySSAUpdater::updateForClonedLoop(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), llvm::MemorySSAUpdater::updatePhisWhenInsertingUniqueBackedgeBlock(), updatePhysDepsUpwards(), updatePostorderSequenceForEdgeInsertion(), upgrade(), llvm::UpgradeARCRuntime(), upgradeLoopArgument(), llvm::UpgradeModuleFlags(), llvm::SIMachineFunctionInfo::usesAGPRs(), llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::validate(), llvm::json::OStream::value(), VectorizePTXValueVTs(), llvm::LiveRange::verify(), llvm::LoopInfoBase< BasicBlock, Loop >::verify(), llvm::MachineTraceMetrics::verifyAnalysis(), llvm::SystemZInstrInfo::verifyInstruction(), llvm::SIInstrInfo::verifyInstruction(), llvm::LoopBase< BasicBlock, Loop >::verifyLoop(), llvm::LoopBase< BasicBlock, Loop >::verifyLoopNest(), llvm::mca::verifyOperands(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::MemorySSA::verifyPrevDefInPhis(), llvm::GVNPass::ValueTable::verifyRemoved(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::BlockPrinter::visit(), llvm::xray::BlockIndexer::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::DWARFLocationTable::visitAbsoluteLocationList(), llvm::SampleProfileLoaderBaseImpl< MachineBasicBlock >::visitEdge(), llvm::jitlink::loongarch::GOTTableManager::visitEdge(), llvm::jitlink::i386::GOTTableManager::visitEdge(), llvm::jitlink::loongarch::PLTTableManager::visitEdge(), llvm::jitlink::i386::PLTTableManager::visitEdge(), llvm::jitlink::aarch64::GOTTableManager::visitEdge(), llvm::jitlink::x86_64::GOTTableManager::visitEdge(), llvm::jitlink::aarch64::PLTTableManager::visitEdge(), llvm::jitlink::x86_64::PLTTableManager::visitEdge(), llvm::jitlink::visitEdge(), llvm::jitlink::visitExistingEdges(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitGEPOfGEP(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::DWARFDebugLoc::visitLocationList(), llvm::DWARFDebugLoclists::visitLocationList(), llvm::InstCombinerImpl::visitPHINode(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::LegalizerHelper::widenScalar(), llvm::coverage::CoverageMappingWriter::write(), llvm::TimeTraceProfiler::write(), llvm::objcopy::elf::ELFWriter< ELFT >::write(), llvm::support::endian::write(), llvm::support::endian::write16(), llvm::support::endian::write32(), llvm::support::endian::write64(), llvm::writeArchive(), llvm::writeArchiveToBuffer(), llvm::writeArchiveToStream(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::InstrProfWriter::writeBuffer(), writeFragment(), llvm::writeIndexTable(), writeOutput(), writePublics(), llvm::InstrProfWriter::writeText(), llvm::writeToOutput(), llvm::object::writeUniversalBinary(), llvm::object::writeWindowsResourceCOFF(), llvm::DataDependenceGraph::~DataDependenceGraph(), llvm::LLVMContextImpl::~LLVMContextImpl(), and llvm::StringMap< uint64_t >::~StringMap().