LLVM: lib/Transforms/Instrumentation/CGProfile.cpp File Reference
CGProfile.cpp File Reference
#include "llvm/Transforms/Instrumentation/CGProfile.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/LazyBlockFrequencyInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/PassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Transforms/Instrumentation.h"
#include <optional>
Functions
static bool addModuleFlags (Module &M, MapVector< std::pair< Function *, Function * >, uint64_t > &Counts)
static bool runCGProfilePass (Module &M, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, function_ref< TargetTransformInfo &(Function &)> GetTTI, bool LazyBFI)
Function Documentation
addModuleFlags()
static bool addModuleFlags (Module & M, MapVector< std::pair< Function *, Function * >, uint64_t > & Counts) static
Definition at line 26 of file CGProfile.cpp.
References llvm::Module::Append, Context, llvm::MDBuilder::createConstant(), E, llvm::ConstantInt::get(), llvm::ValueAsMetadata::get(), llvm::MDNode::get(), llvm::MDTuple::getDistinct(), llvm::Type::getInt64Ty(), and M.
Referenced by runCGProfilePass().
runCGProfilePass()
static bool runCGProfilePass (Module & M, function_ref< BlockFrequencyInfo &(Function &)> GetBFI, function_ref< TargetTransformInfo &(Function &)> GetTTI, bool LazyBFI) static
Definition at line 48 of file CGProfile.cpp.
References addModuleFlags(), BB, llvm::AMDGPUISD::BFI, llvm::InstrProfSymtab::create(), F, llvm::CallBase::getCalledFunction(), llvm::InstrProfSymtab::getFunction(), llvm::getValueProfDataFromInst(), I, llvm::CallBase::isIndirectCall(), llvm::TargetTransformInfo::isLoweredToCall(), M, llvm::SaturatingAdd(), and uint64_t.
Referenced by llvm::CGProfilePass::run().