LLVM: llvm::MSP430MachineFunctionInfo Class Reference
llvm::MSP430MachineFunctionInfo Class Reference
MSP430MachineFunctionInfo - This class is derived from MachineFunction and contains private MSP430 target-specific information for each MachineFunction.
#include "Target/MSP430/MSP430MachineFunctionInfo.h"
Public Member Functions
MSP430MachineFunctionInfo ()=default
MSP430MachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
unsigned getCalleeSavedFrameSize () const
void setCalleeSavedFrameSize (unsigned bytes)
Register getSRetReturnReg () const
void setSRetReturnReg (Register Reg)
int getRAIndex () const
void setRAIndex (int Index)
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
MSP430MachineFunctionInfo - This class is derived from MachineFunction and contains private MSP430 target-specific information for each MachineFunction.
Definition at line 22 of file MSP430MachineFunctionInfo.h.
Constructor & Destructor Documentation
MSP430MachineFunctionInfo() [1/2]
llvm::MSP430MachineFunctionInfo::MSP430MachineFunctionInfo () default
MSP430MachineFunctionInfo() [2/2]
llvm::MSP430MachineFunctionInfo::MSP430MachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline
Definition at line 43 of file MSP430MachineFunctionInfo.h.
Member Function Documentation
clone()
MachineFunctionInfo * MSP430MachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 15 of file MSP430MachineFunctionInfo.cpp.
References llvm::MachineFunction::cloneInfo().
getCalleeSavedFrameSize()
unsigned llvm::MSP430MachineFunctionInfo::getCalleeSavedFrameSize () const inline
Definition at line 51 of file MSP430MachineFunctionInfo.h.
Referenced by llvm::MSP430FrameLowering::emitEpilogue(), and llvm::MSP430FrameLowering::emitPrologue().
getRAIndex()
int llvm::MSP430MachineFunctionInfo::getRAIndex () const inline
Definition at line 57 of file MSP430MachineFunctionInfo.h.
Referenced by llvm::MSP430TargetLowering::getReturnAddressFrameIndex().
getSRetReturnReg()
Register llvm::MSP430MachineFunctionInfo::getSRetReturnReg () const inline
Definition at line 54 of file MSP430MachineFunctionInfo.h.
getVarArgsFrameIndex()
int llvm::MSP430MachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 60 of file MSP430MachineFunctionInfo.h.
Referenced by llvm::MSP430TargetLowering::LowerVASTART().
setCalleeSavedFrameSize()
void llvm::MSP430MachineFunctionInfo::setCalleeSavedFrameSize (unsigned bytes) inline
Definition at line 52 of file MSP430MachineFunctionInfo.h.
Referenced by llvm::MSP430FrameLowering::spillCalleeSavedRegisters().
setRAIndex()
void llvm::MSP430MachineFunctionInfo::setRAIndex (int Index) inline
Definition at line 58 of file MSP430MachineFunctionInfo.h.
References Index.
Referenced by llvm::MSP430TargetLowering::getReturnAddressFrameIndex().
setSRetReturnReg()
void llvm::MSP430MachineFunctionInfo::setSRetReturnReg (Register Reg) inline
Definition at line 55 of file MSP430MachineFunctionInfo.h.
setVarArgsFrameIndex()
void llvm::MSP430MachineFunctionInfo::setVarArgsFrameIndex (int Index) inline
Definition at line 61 of file MSP430MachineFunctionInfo.h.
References Index.
The documentation for this class was generated from the following files:
lib/Target/MSP430/MSP430MachineFunctionInfo.h
lib/Target/MSP430/MSP430MachineFunctionInfo.cpp