LLVM: llvm::SPIRVInstrInfo Class Reference
llvm::SPIRVInstrInfo Class Reference
#include "Target/SPIRV/SPIRVInstrInfo.h"
Public Member Functions
SPIRVInstrInfo ()
const SPIRVRegisterInfo & getRegisterInfo () const
bool isHeaderInstr (const MachineInstr &MI) const
bool isConstantInstr (const MachineInstr &MI) const
bool isTypeDeclInstr (const MachineInstr &MI) const
bool isDecorationInstr (const MachineInstr &MI) const
bool canUseFastMathFlags (const MachineInstr &MI) const
bool canUseNSW (const MachineInstr &MI) const
bool canUseNUW (const MachineInstr &MI) const
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify=false) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
bool expandPostRAPseudo (MachineInstr &MI) const override
Detailed Description
Definition at line 24 of file SPIRVInstrInfo.h.
Constructor & Destructor Documentation
SPIRVInstrInfo()
SPIRVInstrInfo::SPIRVInstrInfo ()
Definition at line 26 of file SPIRVInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool SPIRVInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify = false) const override
Definition at line 171 of file SPIRVInstrInfo.cpp.
References Cond, llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::getLastNonDebugInstr(), MBB, MI, and TBB.
canUseFastMathFlags()
bool SPIRVInstrInfo::canUseFastMathFlags (const MachineInstr & MI) const
Definition at line 94 of file SPIRVInstrInfo.cpp.
References MI.
canUseNSW()
bool SPIRVInstrInfo::canUseNSW (const MachineInstr & MI) const
Definition at line 113 of file SPIRVInstrInfo.cpp.
References MI.
canUseNUW()
bool SPIRVInstrInfo::canUseNUW (const MachineInstr & MI) const
Definition at line 130 of file SPIRVInstrInfo.cpp.
References MI.
copyPhysReg()
void SPIRVInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 230 of file SPIRVInstrInfo.cpp.
References assert(), llvm::DstOp::getReg(), llvm::SrcOp::getReg(), I, MRI, and llvm::MachineRegisterInfo::replaceRegWith().
expandPostRAPseudo()
bool SPIRVInstrInfo::expandPostRAPseudo (MachineInstr & MI) const override
Definition at line 247 of file SPIRVInstrInfo.cpp.
References MI, MRI, and llvm::MachineRegisterInfo::replaceRegWith().
getRegisterInfo()
const SPIRVRegisterInfo& llvm::SPIRVInstrInfo::getRegisterInfo () const inline
Definition at line 30 of file SPIRVInstrInfo.h.
insertBranch()
unsigned SPIRVInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 222 of file SPIRVInstrInfo.cpp.
References llvm::report_fatal_error().
isConstantInstr()
bool SPIRVInstrInfo::isConstantInstr (const MachineInstr & MI) const
Definition at line 28 of file SPIRVInstrInfo.cpp.
References MI.
Referenced by isHeaderInstr().
isDecorationInstr()
bool SPIRVInstrInfo::isDecorationInstr (const MachineInstr & MI) const
Definition at line 59 of file SPIRVInstrInfo.cpp.
References MI.
Referenced by isHeaderInstr().
isHeaderInstr()
bool SPIRVInstrInfo::isHeaderInstr (const MachineInstr & MI) const
Definition at line 72 of file SPIRVInstrInfo.cpp.
References isConstantInstr(), isDecorationInstr(), isTypeDeclInstr(), and MI.
isTypeDeclInstr()
bool SPIRVInstrInfo::isTypeDeclInstr (const MachineInstr & MI) const
Definition at line 49 of file SPIRVInstrInfo.cpp.
References llvm::TargetRegisterClass::getID(), llvm::MachineRegisterInfo::getRegClassOrNull(), MI, and MRI.
Referenced by isHeaderInstr().
removeBranch()
unsigned SPIRVInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 203 of file SPIRVInstrInfo.cpp.
References llvm::report_fatal_error().
The documentation for this class was generated from the following files:
lib/Target/SPIRV/SPIRVInstrInfo.h
lib/Target/SPIRV/SPIRVInstrInfo.cpp