LLVM: llvm::WebAssembly::SortRegionInfo Class Reference
llvm::WebAssembly::SortRegionInfo Class Reference
#include "Target/WebAssembly/WebAssemblySortRegion.h"
Public Member Functions
SortRegionInfo (const MachineLoopInfo &MLI, const WebAssemblyExceptionInfo &WEI)
const SortRegion * getRegionFor (const MachineBasicBlock *MBB)
MachineBasicBlock * getBottom (const SortRegion *R)
MachineBasicBlock * getBottom (const MachineLoop *ML)
MachineBasicBlock * getBottom (const WebAssemblyException *WE)
Friends
class ConcreteSortRegion< MachineLoopInfo >
class ConcreteSortRegion< WebAssemblyException >
Detailed Description
Definition at line 61 of file WebAssemblySortRegion.h.
Constructor & Destructor Documentation
SortRegionInfo()
llvm::WebAssembly::SortRegionInfo::SortRegionInfo (const MachineLoopInfo & MLI, const WebAssemblyExceptionInfo & WEI) inline
Definition at line 72 of file WebAssemblySortRegion.h.
Member Function Documentation
getBottom() [1/3]
MachineBasicBlock * SortRegionInfo::getBottom (const MachineLoop * ML)
Definition at line 52 of file WebAssemblySortRegion.cpp.
References getBottom(), llvm::WebAssemblyExceptionInfo::getExceptionFor(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::isEHPad(), MBB, and ML.
getBottom() [2/3]
MachineBasicBlock * SortRegionInfo::getBottom (const SortRegion * R)
Definition at line 45 of file WebAssemblySortRegion.cpp.
References llvm::WebAssemblyExceptionInfo::getExceptionFor(), and llvm::MachineLoopInfo::getLoopFor().
Referenced by getBottom().
getBottom() [3/3]
MachineBasicBlock * SortRegionInfo::getBottom (const WebAssemblyException * WE)
Definition at line 72 of file WebAssemblySortRegion.cpp.
References llvm::WebAssemblyException::blocks(), llvm::WebAssemblyException::getHeader(), llvm::MachineBasicBlock::getNumber(), and MBB.
getRegionFor()
const SortRegion * SortRegionInfo::getRegionFor (const MachineBasicBlock * MBB)
Definition at line 17 of file WebAssemblySortRegion.cpp.
References llvm::get(), llvm::WebAssemblyExceptionInfo::getExceptionFor(), llvm::MachineLoopInfo::getLoopFor(), MBB, and ML.
Friends And Related Function Documentation
ConcreteSortRegion< MachineLoopInfo >
friend class ConcreteSortRegion< MachineLoopInfo > friend
Definition at line 62 of file WebAssemblySortRegion.h.
ConcreteSortRegion< WebAssemblyException >
friend class ConcreteSortRegion< WebAssemblyException > friend
Definition at line 63 of file WebAssemblySortRegion.h.
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblySortRegion.h
lib/Target/WebAssembly/WebAssemblySortRegion.cpp