LLVM: llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy > Class Template Reference
llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy > Class Template Reference
Our iterators are iterators over the collection of objects that share a key.
#include "llvm/ADT/SparseMultiSet.h"
Public Types
using iterator_category = std::bidirectional_iterator_tag
using value_type = ValueT
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
reference operator* () const
pointer operator-> () const
bool operator== (const iterator_base &RHS) const
Comparison operators.
bool operator!= (const iterator_base &RHS) const
iterator_base & operator-- ()
Increment and decrement operators.
iterator_base & operator++ ()
iterator_base operator-- (int)
iterator_base operator++ (int)
Friends
class SparseMultiSet
Detailed Description
template<typename ValueT, typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t>
template<typename SMSPtrTy>
class llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >
Our iterators are iterators over the collection of objects that share a key.
Definition at line 219 of file SparseMultiSet.h.
Member Typedef Documentation
difference_type
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > using llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::difference_type = std::ptrdiff_t
Definition at line 225 of file SparseMultiSet.h.
iterator_category
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > using llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::iterator_category = std::bidirectional_iterator_tag
Definition at line 223 of file SparseMultiSet.h.
pointer
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > using llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::pointer = value_type *
Definition at line 226 of file SparseMultiSet.h.
reference
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > using llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::reference = value_type &
Definition at line 227 of file SparseMultiSet.h.
value_type
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > using llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::value_type = ValueT
Definition at line 224 of file SparseMultiSet.h.
Member Function Documentation
operator!=()
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > bool llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator!= (const iterator_base< SMSPtrTy > & RHS) const inline
Definition at line 276 of file SparseMultiSet.h.
References llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator==(), and RHS.
operator*()
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > reference llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator* () const inline
Definition at line 256 of file SparseMultiSet.h.
References assert().
Referenced by llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator->().
operator++() [1/2]
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > iterator_base& llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator++ () inline
Definition at line 294 of file SparseMultiSet.h.
References assert().
operator++() [2/2]
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > iterator_base llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator++ (int) inline
Definition at line 304 of file SparseMultiSet.h.
References I.
operator--() [1/2]
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > iterator_base& llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator-- () inline
Increment and decrement operators.
Definition at line 281 of file SparseMultiSet.h.
References assert().
operator--() [2/2]
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > iterator_base llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator-- (int) inline
Definition at line 299 of file SparseMultiSet.h.
References I.
operator->()
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > pointer llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator-> () const inline
Definition at line 262 of file SparseMultiSet.h.
References llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator*().
operator==()
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > bool llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator== (const iterator_base< SMSPtrTy > & RHS) const inline
Comparison operators.
Definition at line 265 of file SparseMultiSet.h.
References assert(), and RHS.
Referenced by llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator!=().
Friends And Related Function Documentation
SparseMultiSet
template<typename ValueT , typename KeyFunctorT = identity<unsigned>, typename SparseT = uint8_t> template<typename SMSPtrTy > friend class SparseMultiSet friend
Definition at line 220 of file SparseMultiSet.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/SparseMultiSet.h