LLVM: llvm::DIELabel Class Reference
llvm::DIELabel Class Reference
A label DIE.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIELabel (const MCSymbol *L)
const MCSymbol * getValue () const
Get MCSymbol.
void emitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit label value.
unsigned sizeOf (const dwarf::FormParams &FormParams, dwarf::Form Form) const
sizeOf - Determine size of label value in bytes.
void print (raw_ostream &O) const
Detailed Description
A label DIE.
Definition at line 218 of file DIE.h.
Constructor & Destructor Documentation
DIELabel()
llvm::DIELabel::DIELabel (const MCSymbol * L) inline explicit
Definition at line 222 of file DIE.h.
Member Function Documentation
emitValue()
void DIELabel::emitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit label value.
Definition at line 489 of file DIE.cpp.
References llvm::AsmPrinter::emitLabelReference(), llvm::AsmPrinter::getDwarfFormParams(), and sizeOf().
Referenced by llvm::DIEString::emitValue().
getValue()
const MCSymbol* llvm::DIELabel::getValue () const inline
Get MCSymbol.
Definition at line 225 of file DIE.h.
print()
LLVM_DUMP_METHOD void DIELabel::print (raw_ostream & O) const
Definition at line 515 of file DIE.cpp.
References llvm::MCSymbol::getName(), and llvm::RISCVFenceField::O.
sizeOf()
unsigned DIELabel::sizeOf (const dwarf::FormParams & FormParams, dwarf::Form Form) const
sizeOf - Determine size of label value in bytes.
Definition at line 497 of file DIE.cpp.
References llvm::dwarf::FormParams::AddrSize, llvm::dwarf::FormParams::getDwarfOffsetByteSize(), and llvm_unreachable.
Referenced by emitValue(), and llvm::DIEString::sizeOf().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp