LLVM: llvm::MemoryLocation Class Reference
llvm::MemoryLocation Class Reference
Representation for a specific memory location.
#include "llvm/Analysis/MemoryLocation.h"
Public Types
enum : uint64_t { UnknownSize = ~UINT64_C(0) }
UnknownSize - This is a special value which can be used with the size arguments in alias queries to indicate that the caller does not know the sizes of the potential memory references.
Public Member Functions
void print (raw_ostream &OS) const
MemoryLocation ()
MemoryLocation (const Value *Ptr, LocationSize Size, const AAMDNodes &AATags=AAMDNodes())
MemoryLocation getWithNewPtr (const Value *NewPtr) const
MemoryLocation getWithNewSize (LocationSize NewSize) const
MemoryLocation getWithoutAATags () const
bool operator== (const MemoryLocation &Other) const
Static Public Member Functions
static MemoryLocation get (const LoadInst *LI)
Return a location with information about the memory reference by the given instruction.
static MemoryLocation get (const StoreInst *SI)
static MemoryLocation get (const VAArgInst *VI)
static MemoryLocation get (const AtomicCmpXchgInst *CXI)
static MemoryLocation get (const AtomicRMWInst *RMWI)
static MemoryLocation get (const Instruction *Inst)
static std::optional< MemoryLocation > getOrNone (const Instruction *Inst)
static MemoryLocation getForSource (const MemTransferInst *MTI)
Return a location representing the source of a memory transfer.
static MemoryLocation getForSource (const AtomicMemTransferInst *MTI)
static MemoryLocation getForSource (const AnyMemTransferInst *MTI)
static MemoryLocation getForDest (const MemIntrinsic *MI)
Return a location representing the destination of a memory set or transfer.
static MemoryLocation getForDest (const AtomicMemIntrinsic *MI)
static MemoryLocation getForDest (const AnyMemIntrinsic *MI)
static std::optional< MemoryLocation > getForDest (const CallBase *CI, const TargetLibraryInfo &TLI)
static MemoryLocation getForArgument (const CallBase *Call, unsigned ArgIdx, const TargetLibraryInfo *TLI)
Return a location representing a particular argument of a call.
static MemoryLocation getForArgument (const CallBase *Call, unsigned ArgIdx, const TargetLibraryInfo &TLI)
static MemoryLocation getAfter (const Value *Ptr, const AAMDNodes &AATags=AAMDNodes())
Return a location that may access any location after Ptr, while remaining within the underlying object.
static MemoryLocation getBeforeOrAfter (const Value *Ptr, const AAMDNodes &AATags=AAMDNodes())
Return a location that may access any location before or after Ptr, while remaining within the underlying object.
static uint64_t getSizeOrUnknown (const TypeSize &T)
Public Attributes
const Value * Ptr
The address of the start of the location.
LocationSize Size
The maximum size of the location, in address-units, or UnknownSize if the size is not known.
AAMDNodes AATags
The metadata nodes which describes the aliasing of the location (each member is null if that kind of information is unavailable).
Detailed Description
Representation for a specific memory location.
This abstraction can be used to represent a specific location in memory. The goal of the location is to represent enough information to describe abstract aliasing, modification, and reference behaviors of whatever value(s) are stored in memory at the particular location.
The primary user of this interface is LLVM's Alias Analysis, but other memory analyses such as MemoryDependence can use it as well.
Definition at line 211 of file MemoryLocation.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint64_t
UnknownSize - This is a special value which can be used with the size arguments in alias queries to indicate that the caller does not know the sizes of the potential memory references.
Enumerator
UnknownSize
Definition at line 216 of file MemoryLocation.h.
Constructor & Destructor Documentation
MemoryLocation() [1/2]
llvm::MemoryLocation::MemoryLocation () inline
Definition at line 289 of file MemoryLocation.h.
Referenced by get(), getAfter(), getBeforeOrAfter(), and getForArgument().
MemoryLocation() [2/2]
llvm::MemoryLocation::MemoryLocation (const Value * Ptr, LocationSize Size, const AAMDNodes & AATags = AAMDNodes()) inline explicit
Definition at line 291 of file MemoryLocation.h.
Member Function Documentation
get() [1/6]
MemoryLocation MemoryLocation::get (const AtomicCmpXchgInst * CXI) static
Definition at line 59 of file MemoryLocation.cpp.
References DL, llvm::Instruction::getAAMetadata(), llvm::AtomicCmpXchgInst::getCompareOperand(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::AtomicCmpXchgInst::getPointerOperand(), llvm::Value::getType(), MemoryLocation(), and llvm::LocationSize::precise().
get() [2/6]
MemoryLocation MemoryLocation::get (const AtomicRMWInst * RMWI) static
Definition at line 68 of file MemoryLocation.cpp.
References DL, llvm::Instruction::getAAMetadata(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::AtomicRMWInst::getPointerOperand(), llvm::Value::getType(), llvm::AtomicRMWInst::getValOperand(), MemoryLocation(), and llvm::LocationSize::precise().
get() [3/6]
static MemoryLocation llvm::MemoryLocation::get (const Instruction * Inst) inline static
Definition at line 243 of file MemoryLocation.h.
References getOrNone().
get() [4/6]
MemoryLocation MemoryLocation::get (const LoadInst * LI) static
Return a location with information about the memory reference by the given instruction.
Definition at line 36 of file MemoryLocation.cpp.
References DL, llvm::Instruction::getAAMetadata(), llvm::Module::getDataLayout(), llvm::Instruction::getModule(), llvm::LoadInst::getPointerOperand(), llvm::Value::getType(), MemoryLocation(), and llvm::LocationSize::precise().
Referenced by llvm::AliasSetTracker::add(), canMoveAboveCall(), llvm::DependenceInfo::depends(), findArgParts(), llvm::FindAvailableLoadedValue(), findSafeStoreForStoreStrongContraction(), GetLocation(), getLocation(), llvm::AAResults::getModRefInfo(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), getOrNone(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::DependenceInfo::getSplitIteration(), llvm::hasPartialIVCondition(), llvm::AMDGPU::isClobberedInFunction(), isSafeToMove(), isUseTriviallyOptimizableToLiveOnEntry(), and memoryIsNotModifiedBetween().
get() [5/6]
MemoryLocation MemoryLocation::get (const StoreInst * SI) static
Definition at line 45 of file MemoryLocation.cpp.
References DL, MemoryLocation(), llvm::LocationSize::precise(), and SI.
get() [6/6]
MemoryLocation MemoryLocation::get (const VAArgInst * VI) static
Definition at line 54 of file MemoryLocation.cpp.
References llvm::LocationSize::afterPointer(), MemoryLocation(), and VI.
getAfter()
static MemoryLocation llvm::MemoryLocation::getAfter (const Value * Ptr, const AAMDNodes & AATags = AAMDNodes()) inline static
Return a location that may access any location after Ptr, while remaining within the underlying object.
Definition at line 271 of file MemoryLocation.h.
References AATags, llvm::LocationSize::afterPointer(), MemoryLocation(), and Ptr.
Referenced by getForArgument(), GetLocation(), and llvm::MemoryDependenceResults::getSimplePointerDependencyFrom().
getBeforeOrAfter()
static MemoryLocation llvm::MemoryLocation::getBeforeOrAfter (const Value * Ptr, const AAMDNodes & AATags = AAMDNodes()) inline static
Return a location that may access any location before or after Ptr, while remaining within the underlying object.
Definition at line 279 of file MemoryLocation.h.
References AATags, llvm::LocationSize::beforeOrAfterPointer(), MemoryLocation(), and Ptr.
Referenced by llvm::objcarc::ObjCARCAAResult::alias(), llvm::AAResults::alias(), llvm::AAResults::callCapturesBefore(), checkFunctionMemoryAccess(), getForArgument(), getForDest(), llvm::BasicAAResult::getModRefInfo(), llvm::objcarc::ObjCARCAAResult::getModRefInfoMask(), llvm::AAResults::getModRefInfoMask(), llvm::AAResults::isNoAlias(), llvm::AAResults::pointsToConstantMemory(), and underlyingObjectsAlias().
getForArgument() [1/2]
static MemoryLocation llvm::MemoryLocation::getForArgument (const CallBase * Call, unsigned ArgIdx, const TargetLibraryInfo & TLI) inline static
Definition at line 264 of file MemoryLocation.h.
References getForArgument().
getForArgument() [2/2]
MemoryLocation MemoryLocation::getForArgument (const CallBase * Call, unsigned ArgIdx, const TargetLibraryInfo * TLI) static
Return a location representing a particular argument of a call.
Definition at line 160 of file MemoryLocation.cpp.
References AATags, llvm::LocationSize::afterPointer(), Arg, assert(), DL, F, getAfter(), getBeforeOrAfter(), llvm::TargetLibraryInfo::getLibFunc(), llvm::TargetLibraryInfo::has(), LLVM_FALLTHROUGH, memcpy(), MemoryLocation(), llvm::LocationSize::precise(), Size, and llvm::LocationSize::upperBound().
Referenced by llvm::AliasSetTracker::add(), getForArgument(), getForDest(), getForSource(), GetLocation(), and llvm::AAResults::getModRefInfo().
getForDest() [1/4]
MemoryLocation MemoryLocation::getForDest (const AnyMemIntrinsic * MI) static
Definition at line 116 of file MemoryLocation.cpp.
References assert(), getForArgument(), and MI.
getForDest() [2/4]
MemoryLocation MemoryLocation::getForDest (const AtomicMemIntrinsic * MI) static
Definition at line 112 of file MemoryLocation.cpp.
References getForDest(), and MI.
getForDest() [3/4]
std::optional< MemoryLocation > MemoryLocation::getForDest (const CallBase * CI, const TargetLibraryInfo & TLI) static
Definition at line 122 of file MemoryLocation.cpp.
References llvm::CallBase::arg_size(), llvm::Instruction::getAAMetadata(), llvm::CallBase::getArgOperand(), getBeforeOrAfter(), getForArgument(), llvm::Value::getType(), llvm::CallBase::hasOperandBundles(), i, llvm::Type::isPointerTy(), llvm::CallBase::onlyAccessesArgMemory(), and llvm::CallBase::onlyReadsMemory().
getForDest() [4/4]
MemoryLocation MemoryLocation::getForDest (const MemIntrinsic * MI) static
Return a location representing the destination of a memory set or transfer.
Definition at line 108 of file MemoryLocation.cpp.
References MI.
Referenced by llvm::AliasSetTracker::add(), getForDest(), llvm::AA::isPotentiallyAffectedByBarrier(), isRemovableWrite(), memoryIsNotModifiedBetween(), and SoleWriteToDeadLocal().
getForSource() [1/3]
MemoryLocation MemoryLocation::getForSource (const AnyMemTransferInst * MTI) static
Definition at line 103 of file MemoryLocation.cpp.
References assert(), llvm::CallBase::getArgOperand(), getForArgument(), and llvm::MemTransferBase< BaseCL >::getRawSource().
getForSource() [2/3]
MemoryLocation MemoryLocation::getForSource (const AtomicMemTransferInst * MTI) static
Definition at line 99 of file MemoryLocation.cpp.
References getForSource().
getForSource() [3/3]
MemoryLocation MemoryLocation::getForSource (const MemTransferInst * MTI) static
Return a location representing the source of a memory transfer.
Definition at line 95 of file MemoryLocation.cpp.
Referenced by llvm::AliasSetTracker::add(), getForSource(), and llvm::AA::isPotentiallyAffectedByBarrier().
getOrNone()
std::optional< MemoryLocation > MemoryLocation::getOrNone (const Instruction * Inst) static
Definition at line 78 of file MemoryLocation.cpp.
References get(), llvm::Instruction::getOpcode(), llvm::SPII::Load, and llvm::SPII::Store.
Referenced by checkFunctionMemoryAccess(), get(), and llvm::AA::isPotentiallyAffectedByBarrier().
getSizeOrUnknown()
static uint64_t llvm::MemoryLocation::getSizeOrUnknown (const TypeSize & T) inline static
Definition at line 285 of file MemoryLocation.h.
References T, and UnknownSize.
Referenced by llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLoadVP(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getTruncStoreVP(), llvm::GISelAddressing::instMayAlias(), and narrowExtractedVectorLoad().
getWithNewPtr()
MemoryLocation llvm::MemoryLocation::getWithNewPtr (const Value * NewPtr) const inline
Definition at line 295 of file MemoryLocation.h.
Referenced by memoryIsNotModifiedBetween().
getWithNewSize()
MemoryLocation llvm::MemoryLocation::getWithNewSize (LocationSize NewSize) const inline
Definition at line 301 of file MemoryLocation.h.
getWithoutAATags()
MemoryLocation llvm::MemoryLocation::getWithoutAATags () const inline
Definition at line 307 of file MemoryLocation.h.
operator==()
bool llvm::MemoryLocation::operator== (const MemoryLocation & Other) const inline
Definition at line 313 of file MemoryLocation.h.
References AATags, Other, Ptr, and Size.
print()
void llvm::MemoryLocation::print (raw_ostream & OS) const inline
Definition at line 234 of file MemoryLocation.h.
References OS, Ptr, and Size.
Member Data Documentation
AATags
AAMDNodes llvm::MemoryLocation::AATags
The metadata nodes which describes the aliasing of the location (each member is null if that kind of information is unavailable).
Definition at line 232 of file MemoryLocation.h.
Referenced by llvm::SCEVAAResult::alias(), llvm::ScopedNoAliasAAResult::alias(), llvm::TypeBasedAAResult::alias(), llvm::objcarc::ObjCARCAAResult::alias(), getAfter(), llvm::AliasSetTracker::getAliasSetFor(), getBeforeOrAfter(), getForArgument(), llvm::DenseMapInfo< MemoryLocation >::getHashValue(), llvm::ScopedNoAliasAAResult::getModRefInfo(), llvm::TypeBasedAAResult::getModRefInfo(), llvm::TypeBasedAAResult::getModRefInfoMask(), llvm::objcarc::ObjCARCAAResult::getModRefInfoMask(), operator==(), and underlyingObjectsAlias().
Ptr
const Value* llvm::MemoryLocation::Ptr
The address of the start of the location.
Definition at line 219 of file MemoryLocation.h.
Referenced by llvm::SCEVAAResult::alias(), llvm::NVPTXAAResult::alias(), llvm::AMDGPUAAResult::alias(), llvm::objcarc::ObjCARCAAResult::alias(), llvm::BasicAAResult::alias(), llvm::GlobalsAAResult::alias(), llvm::AAResults::alias(), llvm::AAResults::callCapturesBefore(), checkFunctionMemoryAccess(), llvm::findAvailablePtrLoadStore(), findDominatingValue(), findSafeStoreForStoreStrongContraction(), getAfter(), llvm::AliasSetTracker::getAliasSetFor(), getBeforeOrAfter(), llvm::MemoryDependenceResults::getDependency(), llvm::DenseMapInfo< MemoryLocation >::getHashValue(), llvm::BasicAAResult::getModRefInfo(), llvm::GlobalsAAResult::getModRefInfo(), llvm::AAResults::getModRefInfo(), llvm::NVPTXAAResult::getModRefInfoMask(), llvm::AMDGPUAAResult::getModRefInfoMask(), llvm::objcarc::ObjCARCAAResult::getModRefInfoMask(), llvm::BasicAAResult::getModRefInfoMask(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), memoryIsNotModifiedBetween(), operator==(), print(), and underlyingObjectsAlias().
Size
LocationSize llvm::MemoryLocation::Size
The maximum size of the location, in address-units, or UnknownSize if the size is not known.
Note that an unknown size does not mean the pointer aliases the entire virtual address space, because there are restrictions on stepping out of one object and into another. See http://llvm.org/docs/LangRef.html#pointeraliasing
Definition at line 228 of file MemoryLocation.h.
Referenced by llvm::SCEVAAResult::alias(), llvm::objcarc::ObjCARCAAResult::alias(), llvm::BasicAAResult::alias(), llvm::AAResults::alias(), llvm::AliasSetTracker::getAliasSetFor(), getForArgument(), llvm::DenseMapInfo< MemoryLocation >::getHashValue(), llvm::objcarc::ObjCARCAAResult::getModRefInfoMask(), isPartialOverwrite(), operator==(), and print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemoryLocation.h
lib/Analysis/MemoryLocation.cpp