LLVM: llvm::objcopy::elf::BinaryELFBuilder Class Reference
llvm::objcopy::elf::BinaryELFBuilder Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
BinaryELFBuilder (MemoryBuffer *MB, uint8_t NewSymbolVisibility)
Expected< std::unique_ptr< Object > > build ()
Public Member Functions inherited from llvm::objcopy::elf::BasicELFBuilder
BasicELFBuilder ()
Additional Inherited Members
Protected Member Functions inherited from llvm::objcopy::elf::BasicELFBuilder
void initFileHeader ()
void initHeaderSegment ()
StringTableSection * addStrTab ()
SymbolTableSection * addSymTab (StringTableSection *StrTab)
Error initSections ()
Protected Attributes inherited from llvm::objcopy::elf::BasicELFBuilder
std::unique_ptr< Object > Obj
Detailed Description
Definition at line 928 of file ELFObject.h.
Constructor & Destructor Documentation
BinaryELFBuilder()
llvm::objcopy::elf::BinaryELFBuilder::BinaryELFBuilder (MemoryBuffer * MB, uint8_t NewSymbolVisibility) inline
Definition at line 934 of file ELFObject.h.
Member Function Documentation
build()
Expected< std::unique_ptr< Object > > BinaryELFBuilder::build ()
Definition at line 1291 of file ELFObject.cpp.
References llvm::objcopy::elf::BasicELFBuilder::addStrTab(), llvm::objcopy::elf::BasicELFBuilder::addSymTab(), llvm::objcopy::elf::BasicELFBuilder::initFileHeader(), and llvm::objcopy::elf::BasicELFBuilder::initHeaderSegment().
Referenced by llvm::objcopy::elf::BinaryReader::create().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp