LLVM: llvm::sampleprof::SampleProfileReaderRawBinary Class Reference
llvm::sampleprof::SampleProfileReaderRawBinary Class Reference
#include "llvm/ProfileData/SampleProfReader.h"
Public Member Functions
SampleProfileReaderRawBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_Binary)
Public Member Functions inherited from llvm::sampleprof::SampleProfileReaderBinary
SampleProfileReaderBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
std::error_code readHeader () override
Read and validate the file header.
std::error_code readImpl () override
Read sample profiles from the associated file.
std::vector< StringRef > * getNameTable () override
It includes all the names that have samples either in outline instance or inline instance.
Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
SampleProfileReader (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
virtual ~SampleProfileReader ()=default
void setDiscriminatorMaskedBitFrom (FSDiscriminatorPass P)
Set the bits for FS discriminators.
uint32_t getDiscriminatorMask () const
Get the bitmask the discriminators: For FS profiles, return the bit mask for this pass.
std::error_code read ()
The interface to read sample profiles from the associated file.
void dumpFunctionProfile (SampleContext FContext, raw_ostream &OS=dbgs())
Print the profile for FContext on stream OS.
virtual bool collectFuncsFromModule ()
Collect functions with definitions in Module M.
void dump (raw_ostream &OS=dbgs())
Print all the profiles on stream OS.
void dumpJson (raw_ostream &OS=dbgs())
Print all the profiles on stream OS in the JSON format.
FunctionSamples * getSamplesFor (const Function &F)
Return the samples collected for function F.
FunctionSamples * getOrCreateSamplesFor (const Function &F)
Return the samples collected for function F, create empty FunctionSamples if it doesn't exist.
virtual FunctionSamples * getSamplesFor (StringRef Fname)
Return the samples collected for function F.
SampleProfileMap & getProfiles ()
Return all the profiles.
void reportError (int64_t LineNumber, const Twine &Msg) const
Report a parse error message.
ProfileSummary & getSummary () const
Return the profile summary.
MemoryBuffer * getBuffer () const
SampleProfileFormat getFormat () const
Return the profile format.
bool profileIsProbeBased () const
Whether input profile is based on pseudo probes.
bool profileIsCS () const
Whether input profile is fully context-sensitive.
bool profileIsPreInlined () const
Whether input profile contains ShouldBeInlined contexts.
virtual std::unique_ptr< ProfileSymbolList > getProfileSymbolList ()
virtual bool dumpSectionInfo (raw_ostream &OS=dbgs())
virtual bool useMD5 ()
Return whether names in the profile are all MD5 numbers.
virtual void setSkipFlatProf (bool Skip)
Don't read profile without context if the flag is set.
virtual bool hasUniqSuffix ()
Return whether any name in the profile contains ".__uniq." suffix.
SampleProfileReaderItaniumRemapper * getRemapper ()
void setModule (const Module *Mod)
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &Buffer)
Return true if Buffer is in the format supported by this class.
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (const std::string Filename, LLVMContext &C, vfs::FileSystem &FS, FSDiscriminatorPass P=FSDiscriminatorPass::Base, const std::string RemapFilename="")
Create a sample profile reader appropriate to the file format.
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (std::unique_ptr< MemoryBuffer > &B, LLVMContext &C, vfs::FileSystem &FS, FSDiscriminatorPass P=FSDiscriminatorPass::Base, const std::string RemapFilename="")
Create a sample profile reader from the supplied memory buffer.
Additional Inherited Members
Protected Member Functions inherited from llvm::sampleprof::SampleProfileReaderBinary
template<typename T >
ErrorOr< T > readNumber ()
Read a numeric value of type T from the profile.
template<typename T >
ErrorOr< T > readUnencodedNumber ()
Read a numeric value of type T from the profile.
ErrorOr< StringRef > readString ()
Read a string from the profile.
template<typename T >
ErrorOr< uint32_t > readStringIndex (T &Table)
Read the string index and check whether it overflows the table.
bool at_eof () const
Return true if we've reached the end of file.
std::error_code readFuncProfile (const uint8_t *Start)
Read the next function profile instance.
std::error_code readProfile (FunctionSamples &FProfile)
Read the contents of the given profile instance.
std::error_code readMagicIdent ()
Read the contents of Magic number and Version number.
std::error_code readSummary ()
Read profile summary.
virtual std::error_code readNameTable ()
Read the whole name table.
virtual ErrorOr< StringRef > readStringFromTable ()
Read a string indirectly via the name table.
virtual ErrorOr< SampleContext > readSampleContextFromTable ()
Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
void computeSummary ()
Compute summary for this profile.
Static Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
static std::unique_ptr< ProfileSummary > takeSummary (SampleProfileReader &Reader)
Take ownership of the summary of this reader.
Protected Attributes inherited from llvm::sampleprof::SampleProfileReaderBinary
const uint8_t * Data = nullptr
Points to the current location in the buffer.
const uint8_t * End = nullptr
Points to the end of the buffer.
std::vector< StringRef > NameTable
Function name table.
Protected Attributes inherited from llvm::sampleprof::SampleProfileReader
SampleProfileMap Profiles
Map every function to its associated profile.
LLVMContext & Ctx
LLVM context used to emit diagnostics.
std::unique_ptr< MemoryBuffer > Buffer
Memory buffer holding the profile file.
std::unordered_set< std::string > MD5NameBuffer
Extra name buffer holding names created on demand.
std::unique_ptr< ProfileSummary > Summary
Profile summary information.
std::unique_ptr< SampleProfileReaderItaniumRemapper > Remapper
bool ProfileIsProbeBased = false
Whether samples are collected based on pseudo probes.
bool ProfileIsCS = false
Whether function profiles are context-sensitive flat profiles.
bool ProfileIsPreInlined = false
Whether function profile contains ShouldBeInlined contexts.
uint32_t CSProfileCount = 0
Number of context-sensitive profiles.
bool ProfileIsFS = false
Whether the function profiles use FS discriminators.
SampleProfileFormat Format = SPF_None
The format of sample.
const Module * M = nullptr
The current module being compiled if SampleProfileReader is used by compiler.
uint32_t MaskedBitFrom = 31
Zero out the discriminator bits higher than bit MaskedBitFrom (0 based).
Detailed Description
Definition at line 664 of file SampleProfReader.h.
Constructor & Destructor Documentation
SampleProfileReaderRawBinary()
llvm::sampleprof::SampleProfileReaderRawBinary::SampleProfileReaderRawBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext & C, SampleProfileFormat Format = SPF_Binary) inline
Definition at line 669 of file SampleProfReader.h.
Member Function Documentation
hasFormat()
bool SampleProfileReaderRawBinary::hasFormat (const MemoryBuffer & Buffer) static
Return true if Buffer is in the format supported by this class.
Definition at line 1534 of file SampleProfReader.cpp.
References llvm::sampleprof::SampleProfileReader::Buffer, llvm::sampleprof::SampleProfileReaderBinary::Data, llvm::decodeULEB128(), llvm::msf::Magic, llvm::sampleprof::SPMagic(), and uint64_t.
Referenced by llvm::sampleprof::SampleProfileReader::create().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfReader.h
lib/ProfileData/SampleProfReader.cpp