LLVM: llvm::WebAssemblyDebugValueManager Class Reference
llvm::WebAssemblyDebugValueManager Class Reference
#include "Target/WebAssembly/WebAssemblyDebugValueManager.h"
Public Member Functions
WebAssemblyDebugValueManager (MachineInstr *Instr)
void move (MachineInstr *Insert)
void updateReg (unsigned Reg)
void clone (MachineInstr *Insert, unsigned NewReg)
void replaceWithLocal (unsigned LocalId)
Detailed Description
Definition at line 24 of file WebAssemblyDebugValueManager.h.
Constructor & Destructor Documentation
WebAssemblyDebugValueManager()
WebAssemblyDebugValueManager::WebAssemblyDebugValueManager (MachineInstr * Instr)
Definition at line 21 of file WebAssemblyDebugValueManager.cpp.
References llvm::MachineBasicBlock::end(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), and llvm::MachineOperand::isReg().
Member Function Documentation
clone()
void WebAssemblyDebugValueManager::clone (MachineInstr * Insert, unsigned NewReg)
Definition at line 52 of file WebAssemblyDebugValueManager.cpp.
References llvm::MachineFunction::CloneMachineInstr(), llvm::MachineInstr::getDebugOperandsForReg(), llvm::MachineBasicBlock::getParent(), Insert, llvm::MachineBasicBlock::insert(), MBB, and llvm::reverse().
Referenced by moveAndTeeForMultiUse(), and rematerializeCheapDef().
move()
void WebAssemblyDebugValueManager::move (MachineInstr * Insert)
Definition at line 39 of file WebAssemblyDebugValueManager.cpp.
References Insert, MBB, llvm::reverse(), and llvm::MachineBasicBlock::splice().
Referenced by moveAndTeeForMultiUse(), moveForSingleUse(), and rematerializeCheapDef().
replaceWithLocal()
void WebAssemblyDebugValueManager::replaceWithLocal (unsigned LocalId)
Definition at line 64 of file WebAssemblyDebugValueManager.cpp.
References llvm::WebAssembly::TI_LOCAL, and llvm::WebAssembly::TI_LOCAL_INDIRECT.
updateReg()
void WebAssemblyDebugValueManager::updateReg (unsigned Reg)
Definition at line 45 of file WebAssemblyDebugValueManager.cpp.
Referenced by moveForSingleUse(), and rematerializeCheapDef().
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyDebugValueManager.h
lib/Target/WebAssembly/WebAssemblyDebugValueManager.cpp