LLVM: llvm::mca::InstrumentManager Class Reference
llvm::mca::InstrumentManager Class Reference
This class allows targets to optionally customize the logic that resolves scheduling class IDs.
#include "llvm/MCA/CustomBehaviour.h"
Public Member Functions
InstrumentManager (const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
virtual ~InstrumentManager ()=default
virtual bool shouldIgnoreInstruments () const
Returns true if llvm-mca should ignore instruments.
virtual bool supportsInstrumentType (StringRef Type) const
virtual SharedInstrument createInstrument (StringRef Desc, StringRef Data)
Allocate an Instrument, and return a shared pointer to it.
virtual unsigned getSchedClassID (const MCInstrInfo &MCII, const MCInst &MCI, const SmallVector< SharedInstrument > &IVec) const
Given an MCInst and a vector of Instrument, a target can return a SchedClassID.
Protected Attributes
const MCSubtargetInfo & STI
const MCInstrInfo & MCII
Detailed Description
This class allows targets to optionally customize the logic that resolves scheduling class IDs.
Targets can use information encoded in Instrument objects to make more informed scheduling decisions.
Definition at line 141 of file CustomBehaviour.h.
Constructor & Destructor Documentation
InstrumentManager()
llvm::mca::InstrumentManager::InstrumentManager (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) inline
Definition at line 147 of file CustomBehaviour.h.
~InstrumentManager()
virtual llvm::mca::InstrumentManager::~InstrumentManager () virtual default
Member Function Documentation
createInstrument()
SharedInstrument llvm::mca::InstrumentManager::createInstrument (llvm::StringRef Desc, llvm::StringRef Data) virtual
Allocate an Instrument, and return a shared pointer to it.
Reimplemented in llvm::mca::RISCVInstrumentManager.
Definition at line 45 of file CustomBehaviour.cpp.
References llvm::Data.
getSchedClassID()
unsigned llvm::mca::InstrumentManager::getSchedClassID (const MCInstrInfo & MCII, const MCInst & MCI, const SmallVector< SharedInstrument > & IVec) const virtual
Given an MCInst and a vector of Instrument, a target can return a SchedClassID.
This can be used by a subtarget to return a PseudoInstruction SchedClassID instead of the one that belongs to the BaseInstruction This can be useful when a BaseInstruction does not convey the correct scheduling information without additional data. By default, it returns the SchedClassID that belongs to MCI.
Reimplemented in llvm::mca::RISCVInstrumentManager.
Definition at line 50 of file CustomBehaviour.cpp.
References llvm::MCInstrInfo::get(), llvm::MCInst::getOpcode(), llvm::MCInstrDesc::getSchedClass(), and MCII.
shouldIgnoreInstruments()
virtual bool llvm::mca::InstrumentManager::shouldIgnoreInstruments () const inline virtual
Returns true if llvm-mca should ignore instruments.
Reimplemented in llvm::mca::RISCVInstrumentManager.
Definition at line 153 of file CustomBehaviour.h.
supportsInstrumentType()
virtual bool llvm::mca::InstrumentManager::supportsInstrumentType (StringRef Type) const inline virtual
Reimplemented in llvm::mca::RISCVInstrumentManager.
Definition at line 157 of file CustomBehaviour.h.
Member Data Documentation
MCII
const MCInstrInfo& llvm::mca::InstrumentManager::MCII protected
Definition at line 144 of file CustomBehaviour.h.
Referenced by llvm::mca::RISCVInstrumentManager::getSchedClassID(), and getSchedClassID().
STI
const MCSubtargetInfo& llvm::mca::InstrumentManager::STI protected
Definition at line 143 of file CustomBehaviour.h.
The documentation for this class was generated from the following files:
include/llvm/MCA/CustomBehaviour.h
lib/MCA/CustomBehaviour.cpp