LLVM: llvm::XtensaMCExpr Class Reference
llvm::XtensaMCExpr Class Reference
#include "Target/Xtensa/MCTargetDesc/XtensaMCExpr.h"
Public Types
enum VariantKind { VK_Xtensa_None, VK_Xtensa_Invalid }
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
VariantKind getKind () const
const MCExpr * getSubExpr () const
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static const XtensaMCExpr * create (const MCExpr *Expr, VariantKind Kind, MCContext &Ctx)
static VariantKind getVariantKindForName (StringRef name)
static StringRef getVariantKindName (VariantKind Kind)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Definition at line 23 of file XtensaMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::XtensaMCExpr::VariantKind
Enumerator
VK_Xtensa_None
VK_Xtensa_Invalid
Definition at line 25 of file XtensaMCExpr.h.
Member Function Documentation
create()
const XtensaMCExpr * XtensaMCExpr::create (const MCExpr * Expr, VariantKind Kind, MCContext & Ctx) static
Definition at line 29 of file XtensaMCExpr.cpp.
evaluateAsRelocatableImpl()
bool XtensaMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 43 of file XtensaMCExpr.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), Fixup, and getSubExpr().
findAssociatedFragment()
MCFragment* llvm::XtensaMCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 46 of file XtensaMCExpr.h.
References llvm::MCExpr::findAssociatedFragment(), and getSubExpr().
fixELFSymbolsInTLSFixups()
void llvm::XtensaMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 50 of file XtensaMCExpr.h.
getKind()
VariantKind llvm::XtensaMCExpr::getKind () const inline
Definition at line 38 of file XtensaMCExpr.h.
Referenced by printImpl().
getSubExpr()
const MCExpr* llvm::XtensaMCExpr::getSubExpr () const inline
Definition at line 40 of file XtensaMCExpr.h.
Referenced by evaluateAsRelocatableImpl(), findAssociatedFragment(), and visitUsedExpr().
getVariantKindForName()
XtensaMCExpr::VariantKind XtensaMCExpr::getVariantKindForName (StringRef name) static
Definition at line 53 of file XtensaMCExpr.cpp.
References llvm::StringSwitch< T, R >::Default(), name, and VK_Xtensa_Invalid.
getVariantKindName()
StringRef XtensaMCExpr::getVariantKindName (VariantKind Kind) static
Definition at line 58 of file XtensaMCExpr.cpp.
References llvm_unreachable.
Referenced by printImpl().
printImpl()
void XtensaMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 34 of file XtensaMCExpr.cpp.
References getKind(), getVariantKindName(), OS, llvm::MCExpr::print(), and VK_Xtensa_None.
visitUsedExpr()
void XtensaMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 49 of file XtensaMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
lib/Target/Xtensa/MCTargetDesc/XtensaMCExpr.h
lib/Target/Xtensa/MCTargetDesc/XtensaMCExpr.cpp