LLVM: llvm::jitlink::SectionRange Class Reference
llvm::jitlink::SectionRange Class Reference
Represents a section address range via a pair of Block pointers to the first and last Blocks in the section.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Member Functions
SectionRange ()=default
SectionRange (const Section &Sec)
Block * getFirstBlock () const
Block * getLastBlock () const
bool empty () const
orc::ExecutorAddr getStart () const
orc::ExecutorAddr getEnd () const
orc::ExecutorAddrDiff getSize () const
orc::ExecutorAddrRange getRange () const
Detailed Description
Represents a section address range via a pair of Block pointers to the first and last Blocks in the section.
Definition at line 784 of file JITLink.h.
Constructor & Destructor Documentation
SectionRange() [1/2]
llvm::jitlink::SectionRange::SectionRange () default
SectionRange() [2/2]
llvm::jitlink::SectionRange::SectionRange (const Section & Sec) inline
Definition at line 787 of file JITLink.h.
References B, llvm::jitlink::Section::blocks(), and llvm::jitlink::Addressable::getAddress().
Member Function Documentation
empty()
bool llvm::jitlink::SectionRange::empty () const inline
Definition at line 806 of file JITLink.h.
References assert().
getEnd()
orc::ExecutorAddr llvm::jitlink::SectionRange::getEnd () const inline
Definition at line 813 of file JITLink.h.
References llvm::jitlink::Addressable::getAddress(), and llvm::jitlink::Block::getSize().
Referenced by getRange(), and getSize().
getFirstBlock()
Block* llvm::jitlink::SectionRange::getFirstBlock () const inline
Definition at line 798 of file JITLink.h.
References assert().
getLastBlock()
Block* llvm::jitlink::SectionRange::getLastBlock () const inline
Definition at line 802 of file JITLink.h.
References assert().
getRange()
orc::ExecutorAddrRange llvm::jitlink::SectionRange::getRange () const inline
Definition at line 818 of file JITLink.h.
References getEnd(), and getStart().
getSize()
orc::ExecutorAddrDiff llvm::jitlink::SectionRange::getSize () const inline
Definition at line 816 of file JITLink.h.
References getEnd(), and getStart().
getStart()
orc::ExecutorAddr llvm::jitlink::SectionRange::getStart () const inline
Definition at line 810 of file JITLink.h.
References llvm::jitlink::Addressable::getAddress().
Referenced by getRange(), and getSize().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/JITLink.h