LLVM: llvm::GCOVFile Class Reference
llvm::GCOVFile Class Reference
GCOVFile - Collects coverage information for one pair of coverage file (.gcno and .gcda).
#include "llvm/ProfileData/GCOV.h"
Public Types
using iterator = pointee_iterator< SmallVectorImpl< std::unique_ptr< GCOVFunction > >::const_iterator >
Public Member Functions
GCOVFile ()=default
bool readGCNO (GCOVBuffer &Buffer)
readGCNO - Read GCNO buffer.
bool readGCDA (GCOVBuffer &Buffer)
readGCDA - Read GCDA buffer.
GCOV::GCOVVersion getVersion () const
void print (raw_ostream &OS) const
void dump () const
dump - Dump GCOVFile content to dbgs() for debugging purposes.
iterator begin () const
iterator end () const
Public Attributes
std::vector< std::string > filenames
StringMap< unsigned > filenameToIdx
bool GCNOInitialized = false
GCOV::GCOVVersion version {}
uint32_t checksum = 0
StringRef cwd
SmallVector< std::unique_ptr< GCOVFunction >, 16 > functions
std::map< uint32_t, GCOVFunction * > identToFunction
uint32_t runCount = 0
uint32_t programCount = 0
Detailed Description
GCOVFile - Collects coverage information for one pair of coverage file (.gcno and .gcda).
Definition at line 190 of file GCOV.h.
Member Typedef Documentation
iterator
using llvm::GCOVFile::iterator = pointee_iterator< SmallVectorImpl<std::unique_ptr<GCOVFunction> >::const_iterator>
Definition at line 214 of file GCOV.h.
Constructor & Destructor Documentation
GCOVFile()
llvm::GCOVFile::GCOVFile () default
Member Function Documentation
begin()
iterator llvm::GCOVFile::begin () const inline
Definition at line 215 of file GCOV.h.
References functions.
dump()
LLVM_DUMP_METHOD void GCOVFile::dump () const
dump - Dump GCOVFile content to dbgs() for debugging purposes.
Definition at line 326 of file GCOV.cpp.
References llvm::dbgs(), and print().
end()
iterator llvm::GCOVFile::end () const inline
Definition at line 216 of file GCOV.h.
References functions.
getVersion()
GCOV::GCOVVersion llvm::GCOVFile::getVersion () const inline
Definition at line 196 of file GCOV.h.
References version.
Referenced by llvm::GCOVFunction::getExitBlock().
print()
void GCOVFile::print (raw_ostream & OS) const
Definition at line 319 of file GCOV.cpp.
References f(), and OS.
Referenced by dump().
readGCDA()
bool GCOVFile::readGCDA (GCOVBuffer & buf)
readGCDA - Read GCDA buffer.
It is required that readGCDA() can only be called after readGCNO().
Definition at line 213 of file GCOV.cpp.
References llvm::GCOVBlock::addSrcEdge(), llvm::GCOVFunction::arcs, assert(), block, llvm::GCOVFunction::blocks, llvm::GCOVFunction::blocksRange(), llvm::GCOVFunction::cfgChecksum, checksum, llvm::GCOVBuffer::cursor, llvm::GCOVBuffer::de, llvm::errs(), llvm::format(), GCNOInitialized, GCOV_ARC_ON_TREE, GCOV_TAG_COUNTER_ARCS, GCOV_TAG_FUNCTION, GCOV_TAG_OBJECT_SUMMARY, GCOV_TAG_PROGRAM_SUMMARY, llvm::GCOVBuffer::getWord(), i, identToFunction, llvm::GCOVFunction::linenoChecksum, move, llvm::GCOVFunction::Name, programCount, llvm::GCOVFunction::propagateCounts(), llvm::GCOVBuffer::readGCDAFormat(), llvm::GCOVBuffer::readGCOVVersion(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readInt64(), runCount, sink, llvm::DataExtractor::skip(), llvm::DataExtractor::Cursor::tell(), llvm::GCOVFunction::treeArcs, llvm::GCOV::V1200, llvm::GCOV::V407, llvm::GCOV::V408, and version.
readGCNO()
bool GCOVFile::readGCNO (GCOVBuffer & Buffer)
readGCNO - Read GCNO buffer.
Definition at line 102 of file GCOV.cpp.
References llvm::GCOVBlock::addDstEdge(), llvm::GCOVBlock::addSrcEdge(), llvm::GCOVFunction::arcs, llvm::GCOVFunction::artificial, llvm::GCOVFunction::blocks, llvm::GCOVFunction::cfgChecksum, checksum, llvm::GCOVBuffer::cursor, cwd, llvm::GCOVBuffer::de, llvm::numbers::e, llvm::StringRef::empty(), llvm::GCOVFunction::endColumn, llvm::GCOVFunction::endLine, llvm::errs(), llvm::sys::path::filename(), filenames, filenameToIdx, functions, GCNOInitialized, GCOV_TAG_ARCS, GCOV_TAG_BLOCKS, GCOV_TAG_FUNCTION, GCOV_TAG_LINES, llvm::GCOVBuffer::getWord(), i, llvm::GCOVFunction::ident, identToFunction, llvm::GCOVFunction::linenoChecksum, move, llvm::GCOVFunction::Name, llvm::GCOVBuffer::readGCNOFormat(), llvm::GCOVBuffer::readGCOVVersion(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readString(), llvm::StringMapImpl::size(), llvm::DataExtractor::skip(), llvm::GCOVFunction::srcIdx, llvm::GCOVFunction::startColumn, llvm::GCOVFunction::startLine, llvm::DataExtractor::Cursor::tell(), llvm::GCOVFunction::treeArcs, llvm::StringMap< ValueTy, AllocatorTy >::try_emplace(), llvm::GCOV::V1200, llvm::GCOV::V407, llvm::GCOV::V800, llvm::GCOV::V900, and version.
Member Data Documentation
checksum
uint32_t llvm::GCOVFile::checksum = 0
Definition at line 206 of file GCOV.h.
Referenced by readGCDA(), and readGCNO().
cwd
StringRef llvm::GCOVFile::cwd
Definition at line 207 of file GCOV.h.
Referenced by readGCNO().
filenames
std::vector<std::string> llvm::GCOVFile::filenames
Definition at line 200 of file GCOV.h.
Referenced by llvm::GCOVFunction::getFilename(), and readGCNO().
filenameToIdx
StringMap<unsigned> llvm::GCOVFile::filenameToIdx
Definition at line 201 of file GCOV.h.
Referenced by readGCNO().
functions
SmallVector<std::unique_ptr<GCOVFunction>, 16> llvm::GCOVFile::functions
Definition at line 208 of file GCOV.h.
Referenced by begin(), end(), and readGCNO().
GCNOInitialized
bool llvm::GCOVFile::GCNOInitialized = false
Definition at line 204 of file GCOV.h.
Referenced by readGCDA(), and readGCNO().
identToFunction
std::map<uint32_t, GCOVFunction *> llvm::GCOVFile::identToFunction
Definition at line 209 of file GCOV.h.
Referenced by readGCDA(), and readGCNO().
programCount
uint32_t llvm::GCOVFile::programCount = 0
Definition at line 211 of file GCOV.h.
Referenced by readGCDA().
runCount
uint32_t llvm::GCOVFile::runCount = 0
Definition at line 210 of file GCOV.h.
Referenced by readGCDA().
version
GCOV::GCOVVersion llvm::GCOVFile::version {}
Definition at line 205 of file GCOV.h.
Referenced by getVersion(), readGCDA(), and readGCNO().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/GCOV.h
lib/ProfileData/GCOV.cpp