LLVM: llvm::RISCVInstrInfo Class Reference
llvm::RISCVInstrInfo Class Reference
#include "Target/RISCV/RISCVInstrInfo.h"
Public Member Functions
RISCVInstrInfo (RISCVSubtarget &STI)
MCInst getNop () const override
const MCInstrDesc & getBrCond (RISCVCC::CondCode CC) const
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, MCRegister DstReg, MCRegister SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, Register SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, Register DstReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg) const override
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr &MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, int FrameIndex, LiveIntervals *LIS=nullptr, VirtRegMap *VRM=nullptr) const override
void movImm (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, Register DstReg, uint64_t Val, MachineInstr::MIFlag Flag=MachineInstr::NoFlags) const
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &dl, int *BytesAdded=nullptr) const override
void insertIndirectBranch (MachineBasicBlock &MBB, MachineBasicBlock &NewDestBB, MachineBasicBlock &RestoreBB, const DebugLoc &DL, int64_t BrOffset, RegScavenger *RS) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
MachineBasicBlock * getBranchDestBlock (const MachineInstr &MI) const override
bool isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
bool analyzeSelect (const MachineInstr &MI, SmallVectorImpl< MachineOperand > &Cond, unsigned &TrueOp, unsigned &FalseOp, bool &Optimizable) const override
MachineInstr * optimizeSelect (MachineInstr &MI, SmallPtrSetImpl< MachineInstr * > &SeenMIs, bool) const override
bool isAsCheapAsAMove (const MachineInstr &MI) const override
std::optional< DestSourcePair > isCopyInstrImpl (const MachineInstr &MI) const override
bool verifyInstruction (const MachineInstr &MI, StringRef &ErrInfo) const override
bool getMemOperandWithOffsetWidth (const MachineInstr &LdSt, const MachineOperand *&BaseOp, int64_t &Offset, unsigned &Width, const TargetRegisterInfo *TRI) const
bool areMemAccessesTriviallyDisjoint (const MachineInstr &MIa, const MachineInstr &MIb) const override
std::pair< unsigned, unsigned > decomposeMachineOperandsTargetFlags (unsigned TF) const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableDirectMachineOperandTargetFlags () const override
bool isFunctionSafeToOutlineFrom (MachineFunction &MF, bool OutlineFromLinkOnceODRs) const override
bool isMBBSafeToOutlineFrom (MachineBasicBlock &MBB, unsigned &Flags) const override
bool shouldOutlineFromFunctionByDefault (MachineFunction &MF) const override
outliner::OutlinedFunction getOutliningCandidateInfo (std::vector< outliner::Candidate > &RepeatedSequenceLocs) const override
virtual outliner::InstrType getOutliningTypeImpl (MachineBasicBlock::iterator &MBBI, unsigned Flags) const override
void buildOutlinedFrame (MachineBasicBlock &MBB, MachineFunction &MF, const outliner::OutlinedFunction &OF) const override
MachineBasicBlock::iterator insertOutlinedCall (Module &M, MachineBasicBlock &MBB, MachineBasicBlock::iterator &It, MachineFunction &MF, outliner::Candidate &C) const override
bool findCommutedOpIndices (const MachineInstr &MI, unsigned &SrcOpIdx1, unsigned &SrcOpIdx2) const override
MachineInstr * commuteInstructionImpl (MachineInstr &MI, bool NewMI, unsigned OpIdx1, unsigned OpIdx2) const override
MachineInstr * convertToThreeAddress (MachineInstr &MI, LiveVariables *LV, LiveIntervals *LIS) const override
std::string createMIROperandComment (const MachineInstr &MI, const MachineOperand &Op, unsigned OpIdx, const TargetRegisterInfo *TRI) const override
void getVLENFactoredAmount (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator II, const DebugLoc &DL, Register DestReg, int64_t Amount, MachineInstr::MIFlag Flag=MachineInstr::NoFlags) const
bool useMachineCombiner () const override
void setSpecialOperandAttr (MachineInstr &OldMI1, MachineInstr &OldMI2, MachineInstr &NewMI1, MachineInstr &NewMI2) const override
bool getMachineCombinerPatterns (MachineInstr &Root, SmallVectorImpl< MachineCombinerPattern > &Patterns, bool DoRegPressureReduce) const override
void finalizeInsInstrs (MachineInstr &Root, MachineCombinerPattern &P, SmallVectorImpl< MachineInstr * > &InsInstrs) const override
void genAlternativeCodeSequence (MachineInstr &Root, MachineCombinerPattern Pattern, SmallVectorImpl< MachineInstr * > &InsInstrs, SmallVectorImpl< MachineInstr * > &DelInstrs, DenseMap< unsigned, unsigned > &InstrIdxForVirtReg) const override
bool hasReassociableSibling (const MachineInstr &Inst, bool &Commuted) const override
bool isAssociativeAndCommutative (const MachineInstr &Inst, bool Invert) const override
std::optional< unsigned > getInverseOpcode (unsigned Opcode) const override
bool hasAllNBitUsers (const MachineInstr &MI, const MachineRegisterInfo &MRI, unsigned NBits) const
bool hasAllWUsers (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr &MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, int FrameIndex, LiveIntervals *LIS=nullptr, VirtRegMap *VRM=nullptr) const
Target-dependent implementation for foldMemoryOperand.
virtual MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr &MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, MachineInstr &LoadMI, LiveIntervals *LIS=nullptr) const
Target-dependent implementation for foldMemoryOperand.
Protected Attributes
const RISCVSubtarget & STI
Detailed Description
Definition at line 44 of file RISCVInstrInfo.h.
Constructor & Destructor Documentation
RISCVInstrInfo()
RISCVInstrInfo::RISCVInstrInfo (RISCVSubtarget & STI) explicit
Definition at line 56 of file RISCVInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool RISCVInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 804 of file RISCVInstrInfo.cpp.
References Cond, llvm::MachineBasicBlock::end(), getBranchDestBlock(), llvm::HexagonMCInstrInfo::getDesc(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineInstrBundleIterator< Ty, IsReverse >::getReverse(), I, MBB, parseCondBranch(), llvm::MachineBasicBlock::rend(), and TBB.
analyzeSelect()
bool RISCVInstrInfo::analyzeSelect (const MachineInstr & MI, SmallVectorImpl< MachineOperand > & Cond, unsigned & TrueOp, unsigned & FalseOp, bool & Optimizable) const override
Definition at line 1104 of file RISCVInstrInfo.cpp.
References assert(), Cond, MI, and STI.
areMemAccessesTriviallyDisjoint()
bool RISCVInstrInfo::areMemAccessesTriviallyDisjoint (const MachineInstr & MIa, const MachineInstr & MIb) const override
Definition at line 1777 of file RISCVInstrInfo.cpp.
References assert(), getMemOperandWithOffsetWidth(), llvm::RISCVSubtarget::getRegisterInfo(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineOperand::isIdenticalTo(), llvm::max(), llvm::MachineInstr::mayLoadOrStore(), llvm::min(), STI, and TRI.
buildOutlinedFrame()
void RISCVInstrInfo::buildOutlinedFrame (MachineBasicBlock & MBB, MachineFunction & MF, const outliner::OutlinedFunction & OF) const override
Definition at line 1947 of file RISCVInstrInfo.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::RegState::Define, E, llvm::MachineBasicBlock::end(), llvm::get(), I, llvm::MachineBasicBlock::insert(), and MBB.
commuteInstructionImpl()
MachineInstr * RISCVInstrInfo::commuteInstructionImpl (MachineInstr & MI, bool NewMI, unsigned OpIdx1, unsigned OpIdx2) const override
Definition at line 2207 of file RISCVInstrInfo.cpp.
References assert(), CASE_VFMA_CHANGE_OPCODE_LMULS, CASE_VFMA_CHANGE_OPCODE_LMULS_MF4, CASE_VFMA_CHANGE_OPCODE_SPLATS, CASE_VFMA_OPCODE_LMULS, CASE_VFMA_OPCODE_LMULS_MF4, CASE_VFMA_SPLATS, CC, llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::X86ISD::FNMADD, llvm::get(), llvm::RISCVCC::getOppositeBranchCondition(), llvm_unreachable, and MI.
convertToThreeAddress()
MachineInstr * RISCVInstrInfo::convertToThreeAddress (MachineInstr & MI, LiveVariables * LV, LiveIntervals * LIS) const override
Definition at line 2352 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), assert(), llvm::BuildMI(), CASE_WIDEOP_CHANGE_OPCODE_LMULS, CASE_WIDEOP_CHANGE_OPCODE_LMULS_MF4, CASE_WIDEOP_OPCODE_LMULS, CASE_WIDEOP_OPCODE_LMULS_MF4, llvm::MachineInstrBuilder::copyImplicitOps(), llvm::get(), llvm::LiveIntervals::getInterval(), llvm::SlotIndex::getRegSlot(), llvm::LiveRange::getSegmentContaining(), llvm::RISCVII::hasVecPolicyOp(), I, llvm_unreachable, MBB, MI, llvm::LiveVariables::replaceKillInstruction(), llvm::LiveIntervals::ReplaceMachineInstrInMaps(), and S.
copyPhysReg()
void RISCVInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, MCRegister DstReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 257 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), DL, llvm::AArch64SysReg::SysReg::Encoding, llvm::get(), llvm::getKillRegState(), llvm::TargetRegisterInfo::getMatchingSuperReg(), llvm::MCRegisterInfo::getName(), llvm::RISCVSubtarget::getRegisterInfo(), llvm::RISCVII::getSEWOpNum(), llvm::RISCVII::getVLOpNum(), I, llvm::RegState::Implicit, isConvertibleToVMV_V_V(), llvm_unreachable, llvm::RISCVII::LMUL_1, llvm::RISCVII::LMUL_2, llvm::RISCVII::LMUL_4, llvm::RISCVII::LMUL_8, llvm::AArch64SysReg::lookupSysRegByName(), MBB, MBBI, STI, and TRI.
createMIROperandComment()
std::string RISCVInstrInfo::createMIROperandComment (const MachineInstr & MI, const MachineOperand & Op, unsigned OpIdx, const TargetRegisterInfo * TRI) const override
Definition at line 1988 of file RISCVInstrInfo.cpp.
References assert(), llvm::TargetInstrInfo::createMIROperandComment(), llvm::raw_ostream::flush(), llvm::RISCVII::getSEWOpNum(), llvm::RISCVII::getVecPolicyOpNum(), llvm::RISCVII::hasSEWOp(), llvm::RISCVII::hasVecPolicyOp(), llvm::RISCVMatInt::Imm, llvm::RISCVVType::isValidSEW(), Log2SEW, llvm::RISCVII::MASK_AGNOSTIC, MI, OS, llvm::RISCVVType::printVType(), SEW, llvm::RISCVII::TAIL_AGNOSTIC, TRI, TSFlags, and uint64_t.
decomposeMachineOperandsTargetFlags()
std::pair< unsigned, unsigned > RISCVInstrInfo::decomposeMachineOperandsTargetFlags (unsigned TF) const override
Definition at line 1809 of file RISCVInstrInfo.cpp.
References llvm::BitmaskEnumDetail::Mask(), and llvm::RISCVII::MO_DIRECT_FLAG_MASK.
finalizeInsInstrs()
void RISCVInstrInfo::finalizeInsInstrs (MachineInstr & Root, MachineCombinerPattern & P, SmallVectorImpl< MachineInstr * > & InsInstrs) const override
Definition at line 1269 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addUse(), llvm::all_of(), assert(), llvm::RISCVFPRndMode::DYN, llvm::MachineOperand::getImm(), llvm::MachineInstr::getMF(), llvm::RISCV::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::RegState::Implicit, and MI.
findCommutedOpIndices()
bool RISCVInstrInfo::findCommutedOpIndices (const MachineInstr & MI, unsigned & SrcOpIdx1, unsigned & SrcOpIdx2) const override
Definition at line 2062 of file RISCVInstrInfo.cpp.
References assert(), CASE_VFMA_OPCODE_LMULS, CASE_VFMA_OPCODE_LMULS_MF4, CASE_VFMA_SPLATS, llvm::TargetInstrInfo::findCommutedOpIndices(), llvm::X86ISD::FNMADD, llvm::RISCVII::hasVecPolicyOp(), llvm::MCInstrDesc::isCommutable(), and MI.
foldMemoryOperandImpl() [1/3]
virtual MachineInstr* llvm::TargetInstrInfo::foldMemoryOperandImpl inline
Target-dependent implementation for foldMemoryOperand.
Target-independent code in foldMemoryOperand will take care of adding a MachineMemOperand to the newly created instruction. The instruction and any auxiliary instructions necessary will be inserted at InsertPt.
Definition at line 1265 of file TargetInstrInfo.h.
foldMemoryOperandImpl() [2/3]
MachineInstr * RISCVInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr & MI, ArrayRef< unsigned > Ops, MachineBasicBlock::iterator InsertPt, int FrameIndex, LiveIntervals * LIS = nullptr, VirtRegMap * VRM = nullptr) const override
Definition at line 629 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), llvm::ISD::FrameIndex, llvm::get(), llvm::MachineFunction::getDataLayout(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm::DataLayout::isBigEndian(), llvm::RISCV::isSEXT_W(), llvm::RISCV::isZEXT_B(), llvm::RISCV::isZEXT_W(), MI, llvm::MachineMemOperand::MOLoad, and llvm::ArrayRef< T >::size().
foldMemoryOperandImpl() [3/3]
virtual MachineInstr* llvm::TargetInstrInfo::foldMemoryOperandImpl inline
Target-dependent implementation for foldMemoryOperand.
Target-independent code in foldMemoryOperand will take care of adding a MachineMemOperand to the newly created instruction. The instruction and any auxiliary instructions necessary will be inserted at InsertPt.
Definition at line 1278 of file TargetInstrInfo.h.
genAlternativeCodeSequence()
void RISCVInstrInfo::genAlternativeCodeSequence (MachineInstr & Root, MachineCombinerPattern Pattern, SmallVectorImpl< MachineInstr * > & InsInstrs, SmallVectorImpl< MachineInstr * > & DelInstrs, DenseMap< unsigned, unsigned > & InstrIdxForVirtReg) const override
Definition at line 1571 of file RISCVInstrInfo.cpp.
References combineFPFusedMultiply(), llvm::FMADD_AX, llvm::FMADD_XA, llvm::FMSUB, llvm::FNMSUB, llvm::TargetInstrInfo::genAlternativeCodeSequence(), llvm::MachineInstr::getMF(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::getVRegDef(), and MRI.
getBranchDestBlock()
MachineBasicBlock * RISCVInstrInfo::getBranchDestBlock (const MachineInstr & MI) const override
Definition at line 1017 of file RISCVInstrInfo.cpp.
References assert(), and MI.
Referenced by analyzeBranch().
getBrCond()
const MCInstrDesc & RISCVInstrInfo::getBrCond (RISCVCC::CondCode CC) const
Definition at line 766 of file RISCVInstrInfo.cpp.
References CC, llvm::RISCVCC::COND_EQ, llvm::RISCVCC::COND_GE, llvm::RISCVCC::COND_GEU, llvm::RISCVCC::COND_LT, llvm::RISCVCC::COND_LTU, llvm::RISCVCC::COND_NE, llvm::get(), and llvm_unreachable.
Referenced by insertBranch().
getInstSizeInBytes()
unsigned RISCVInstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
Definition at line 1193 of file RISCVInstrInfo.cpp.
References llvm::get(), llvm::MachineFunction::getTarget(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, MI, STI, and TM.
Referenced by getOutliningCandidateInfo(), insertBranch(), and removeBranch().
getInverseOpcode()
std::optional< unsigned > RISCVInstrInfo::getInverseOpcode (unsigned Opcode) const override
Definition at line 1404 of file RISCVInstrInfo.cpp.
References llvm::ISD::ADD, and llvm::ISD::SUB.
Referenced by isAssociativeAndCommutative().
getMachineCombinerPatterns()
bool RISCVInstrInfo::getMachineCombinerPatterns (MachineInstr & Root, SmallVectorImpl< MachineCombinerPattern > & Patterns, bool DoRegPressureReduce) const override
Definition at line 1488 of file RISCVInstrInfo.cpp.
References getFPPatterns(), and llvm::TargetInstrInfo::getMachineCombinerPatterns().
getMemOperandWithOffsetWidth()
bool RISCVInstrInfo::getMemOperandWithOffsetWidth (const MachineInstr & LdSt, const MachineOperand *& BaseOp, int64_t & Offset, unsigned & Width, const TargetRegisterInfo * TRI) const
Definition at line 1754 of file RISCVInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOperand(), getSize(), llvm::MachineInstr::hasOneMemOperand(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoadOrStore(), llvm::MachineInstr::memoperands_begin(), and llvm::Offset.
Referenced by areMemAccessesTriviallyDisjoint().
getNop()
MCInst RISCVInstrInfo::getNop () const override
Definition at line 60 of file RISCVInstrInfo.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::RISCVSubtarget::hasStdExtCOrZca(), and STI.
getOutliningCandidateInfo()
outliner::OutlinedFunction RISCVInstrInfo::getOutliningCandidateInfo (std::vector< outliner::Candidate > & RepeatedSequenceLocs) const override
Definition at line 1865 of file RISCVInstrInfo.cpp.
References E, llvm::erase_if(), getInstSizeInBytes(), I, MachineOutlinerDefault, and TRI.
getOutliningTypeImpl()
outliner::InstrType RISCVInstrInfo::getOutliningTypeImpl (MachineBasicBlock::iterator & MBBI, unsigned Flags) const override virtual
Definition at line 1906 of file RISCVInstrInfo.cpp.
References F, llvm::MachineBasicBlock::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::IRSimilarity::Illegal, llvm::IRSimilarity::Invisible, llvm::IRSimilarity::Legal, MBB, MBBI, MI, llvm::RISCVII::MO_PCREL_LO, and TRI.
getSerializableDirectMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > RISCVInstrInfo::getSerializableDirectMachineOperandTargetFlags () const override
Definition at line 1815 of file RISCVInstrInfo.cpp.
References llvm::ArrayRef(), llvm::LoongArchII::MO_CALL, llvm::RISCVII::MO_GOT_HI, llvm::AVRII::MO_HI, llvm::AVRII::MO_LO, llvm::LoongArchII::MO_PCREL_HI, llvm::LoongArchII::MO_PCREL_LO, llvm::M68kII::MO_PLT, llvm::RISCVII::MO_TLS_GD_HI, llvm::RISCVII::MO_TLS_GOT_HI, llvm::RISCVII::MO_TPREL_ADD, llvm::MipsII::MO_TPREL_HI, and llvm::MipsII::MO_TPREL_LO.
getVLENFactoredAmount()
void RISCVInstrInfo::getVLENFactoredAmount (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator II, const DebugLoc & DL, Register DestReg, int64_t Amount, MachineInstr::MIFlag Flag = MachineInstr::NoFlags) const
Definition at line 2428 of file RISCVInstrInfo.cpp.
References llvm::ISD::ADD, llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::LLVMContext::diagnose(), DL, llvm::get(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getRegInfo(), llvm::isPowerOf2_64(), llvm::RegState::Kill, llvm_unreachable, llvm::Log2_32(), llvm::Log2_64(), MBB, movImm(), MRI, llvm::ISD::MUL, N, llvm::MachineInstrBuilder::setMIFlag(), STI, and llvm::ISD::SUB.
hasAllNBitUsers()
bool RISCVInstrInfo::hasAllNBitUsers (const MachineInstr & MI, const MachineRegisterInfo & MRI, unsigned NBits) const
Definition at line 2520 of file RISCVInstrInfo.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::bit_width(), llvm::tgtok::Bits, llvm::RISCVISD::BREV8, llvm::RISCVISD::CLZW, llvm::RISCVISD::CTZW, llvm::RISCVISD::DIVUW, llvm::RISCVISD::DIVW, llvm::RISCVISD::FMV_H_X, llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::RISCVSubtarget::getXLen(), llvm::RISCVMatInt::Imm, llvm::SmallSet< T, N, C >::insert(), llvm::Log2_32(), MI, MRI, llvm::ISD::MUL, llvm::ISD::OR, llvm::RISCVISD::ORC_B, P, llvm::SystemZISD::PACK, PHI, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::RISCVISD::REMUW, llvm::AVRISD::ROL, llvm::RISCVISD::ROLW, llvm::AArch64_AM::ROR, llvm::RISCVISD::RORW, llvm::RISCVISD::SLLW, llvm::ISD::SRA, llvm::RISCVISD::SRAW, llvm::ISD::SRL, llvm::RISCVISD::SRLW, STI, llvm::ISD::SUB, uint64_t, llvm::MachineRegisterInfo::use_operands(), and llvm::ISD::XOR.
Referenced by hasAllWUsers().
hasAllWUsers()
bool llvm::RISCVInstrInfo::hasAllWUsers (const MachineInstr & MI, const MachineRegisterInfo & MRI) const inline
Definition at line 230 of file RISCVInstrInfo.h.
References hasAllNBitUsers(), MI, and MRI.
hasReassociableSibling()
bool RISCVInstrInfo::hasReassociableSibling (const MachineInstr & Inst, bool & Commuted) const override
Definition at line 1332 of file RISCVInstrInfo.cpp.
References llvm::MachineInstr::getMF(), llvm::RISCV::getNamedOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::getVRegDef(), llvm::RISCV::hasEqualFRM(), llvm::TargetInstrInfo::hasReassociableSibling(), and MRI.
insertBranch()
unsigned RISCVInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & dl, int * BytesAdded = nullptr) const override
Definition at line 906 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), CC, Cond, DL, llvm::get(), getBrCond(), getInstSizeInBytes(), MBB, MI, and TBB.
insertIndirectBranch()
void RISCVInstrInfo::insertIndirectBranch (MachineBasicBlock & MBB, MachineBasicBlock & NewDestBB, MachineBasicBlock & RestoreBB, const DebugLoc & DL, int64_t BrOffset, RegScavenger * RS) const override
Definition at line 943 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineBasicBlock::back(), llvm::BuildMI(), llvm::MachineRegisterInfo::clearVirtRegs(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Dead, llvm::RegState::Define, DL, llvm::TargetRegisterInfo::eliminateFrameIndex(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::RegScavenger::enterBasicBlockEnd(), llvm::ISD::FrameIndex, llvm::get(), llvm::RISCVMachineFunctionInfo::getBranchRelaxationScratchFrameIndex(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), loadRegFromStackSlot(), MBB, MI, llvm::RISCVII::MO_CALL, MRI, llvm::MachineBasicBlock::pred_size(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::report_fatal_error(), llvm::RegScavenger::scavengeRegisterBackwards(), llvm::RegScavenger::setRegUsed(), storeRegToStackSlot(), and TRI.
insertOutlinedCall()
MachineBasicBlock::iterator RISCVInstrInfo::insertOutlinedCall (Module & M, MachineBasicBlock & MBB, MachineBasicBlock::iterator & It, MachineFunction & MF, outliner::Candidate & C) const override
Definition at line 1975 of file RISCVInstrInfo.cpp.
References llvm::BuildMI(), llvm::get(), llvm::MachineFunction::getName(), llvm::MachineBasicBlock::insert(), M, MBB, and llvm::RISCVII::MO_CALL.
isAsCheapAsAMove()
bool RISCVInstrInfo::isAsCheapAsAMove (const MachineInstr & MI) const override
Definition at line 1214 of file RISCVInstrInfo.cpp.
References MI.
isAssociativeAndCommutative()
bool RISCVInstrInfo::isAssociativeAndCommutative (const MachineInstr & Inst, bool Invert) const override
Definition at line 1351 of file RISCVInstrInfo.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::MachineInstr::getFlag(), getInverseOpcode(), llvm::MachineInstr::getOpcode(), isFADD(), isFMUL(), llvm::ISD::MUL, llvm::ISD::OR, and llvm::ISD::XOR.
isBranchOffsetInRange()
bool RISCVInstrInfo::isBranchOffsetInRange (unsigned BranchOpc, int64_t BrOffset) const override
Definition at line 1024 of file RISCVInstrInfo.cpp.
References llvm::RISCVSubtarget::getXLen(), llvm::isIntN(), llvm_unreachable, llvm::SignExtend64(), and STI.
isCopyInstrImpl()
std::optional< DestSourcePair > RISCVInstrInfo::isCopyInstrImpl (const MachineInstr & MI) const override
Definition at line 1236 of file RISCVInstrInfo.cpp.
References MI.
isFunctionSafeToOutlineFrom()
bool RISCVInstrInfo::isFunctionSafeToOutlineFrom (MachineFunction & MF, bool OutlineFromLinkOnceODRs) const override
Definition at line 1832 of file RISCVInstrInfo.cpp.
References F, and llvm::MachineFunction::getFunction().
isLoadFromStackSlot()
unsigned RISCVInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 69 of file RISCVInstrInfo.cpp.
References llvm::X86ISD::FLD, llvm::ISD::FrameIndex, llvm::ARM_MB::LD, and MI.
isMBBSafeToOutlineFrom()
bool RISCVInstrInfo::isMBBSafeToOutlineFrom (MachineBasicBlock & MBB, unsigned & Flags) const override
Definition at line 1849 of file RISCVInstrInfo.cpp.
References llvm::TargetInstrInfo::isMBBSafeToOutlineFrom(), and MBB.
isStoreToStackSlot()
unsigned RISCVInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 96 of file RISCVInstrInfo.cpp.
References llvm::ISD::FrameIndex, and MI.
loadRegFromStackSlot()
void RISCVInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, Register DstReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg) const override
Definition at line 547 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::end(), llvm::X86ISD::FLD, llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterInfo::getRegSizeInBits(), I, llvm::ARM_MB::LD, llvm_unreachable, MBB, llvm::MachineMemOperand::MOLoad, llvm::TargetStackID::ScalableVector, llvm::MachineFrameInfo::setStackID(), TRI, and llvm::MemoryLocation::UnknownSize.
Referenced by insertIndirectBranch().
movImm()
void RISCVInstrInfo::movImm (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, Register DstReg, uint64_t Val, MachineInstr::MIFlag Flag = MachineInstr::NoFlags) const
Definition at line 687 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), DL, llvm::RISCVMatInt::generateInstSeq(), llvm::get(), llvm::RISCVMatInt::Imm, llvm::RISCVSubtarget::is64Bit(), llvm::RegState::Kill, MBB, MBBI, llvm::RISCVMatInt::RegImm, llvm::RISCVMatInt::RegReg, llvm::RISCVMatInt::RegX0, llvm::report_fatal_error(), llvm::MachineInstrBuilder::setMIFlag(), and STI.
Referenced by getVLENFactoredAmount().
optimizeSelect()
MachineInstr * RISCVInstrInfo::optimizeSelect (MachineInstr & MI, SmallPtrSetImpl< MachineInstr * > & SeenMIs, bool PreferFalse) const override
Definition at line 1128 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), canFoldAsPredicatedOp(), CC, llvm::MachineInstr::clearKillInfo(), llvm::MachineRegisterInfo::constrainRegClass(), DefMI, llvm::numbers::e, llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::MachineInstr::eraseFromParent(), llvm::get(), llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::RISCVCC::getOppositeBranchCondition(), llvm::MachineInstr::getParent(), getPredicatedOpcode(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), i, llvm::SmallPtrSetImpl< PtrType >::insert(), MI, MRI, and STI.
removeBranch()
unsigned RISCVInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 872 of file RISCVInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), getInstSizeInBytes(), llvm::MachineBasicBlock::getLastNonDebugInstr(), I, and MBB.
reverseBranchCondition()
bool RISCVInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 1008 of file RISCVInstrInfo.cpp.
References assert(), CC, Cond, and getOppositeBranchCondition().
setSpecialOperandAttr()
void RISCVInstrInfo::setSpecialOperandAttr (MachineInstr & OldMI1, MachineInstr & OldMI2, MachineInstr & NewMI1, MachineInstr & NewMI2) const override
Definition at line 1260 of file RISCVInstrInfo.cpp.
References llvm::MachineInstr::getFlags(), and llvm::MachineInstr::setFlags().
shouldOutlineFromFunctionByDefault()
bool RISCVInstrInfo::shouldOutlineFromFunctionByDefault (MachineFunction & MF) const override
Definition at line 1860 of file RISCVInstrInfo.cpp.
References llvm::MachineFunction::getFunction(), and llvm::Function::hasMinSize().
storeRegToStackSlot()
void RISCVInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, Register SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg) const override
Definition at line 463 of file RISCVInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::end(), llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterInfo::getRegSizeInBits(), I, llvm_unreachable, MBB, llvm::MachineMemOperand::MOStore, llvm::TargetStackID::ScalableVector, llvm::MachineFrameInfo::setStackID(), TRI, and llvm::MemoryLocation::UnknownSize.
Referenced by insertIndirectBranch().
useMachineCombiner()
bool llvm::RISCVInstrInfo::useMachineCombiner () const inline override
Definition at line 196 of file RISCVInstrInfo.h.
verifyInstruction()
bool RISCVInstrInfo::verifyInstruction (const MachineInstr & MI, StringRef & ErrInfo) const override
Definition at line 1597 of file RISCVInstrInfo.cpp.
References CASE_OPERAND_UIMM, llvm::enumerate(), llvm::MachineOperand::getImm(), llvm::RISCVII::getMergeOpNum(), llvm::MachineRegisterInfo::getRegClass(), llvm::RISCVII::getSEWOpNum(), llvm::RISCVII::getVecPolicyOpNum(), llvm::RISCVII::getVLOpNum(), llvm::RISCVII::hasMergeOp(), llvm::RISCVII::hasSEWOp(), llvm::RISCVII::hasVecPolicyOp(), llvm::RISCVII::hasVLOp(), llvm::RISCVMatInt::Imm, llvm::RISCVSubtarget::is64Bit(), llvm::MachineOperand::isImm(), llvm::RISCVVType::isValidSEW(), llvm_unreachable, Log2SEW, llvm::RISCVII::MASK_AGNOSTIC, MI, MRI, llvm::RISCVOp::OPERAND_FIRST_RISCV_IMM, llvm::RISCVOp::OPERAND_LAST_RISCV_IMM, llvm::RISCVOp::OPERAND_RVKRNUM, llvm::RISCVOp::OPERAND_SIMM10_LSB0000_NONZERO, llvm::RISCVOp::OPERAND_SIMM12, llvm::RISCVOp::OPERAND_SIMM12_LSB00000, llvm::RISCVOp::OPERAND_SIMM5, llvm::RISCVOp::OPERAND_SIMM5_PLUS1, llvm::RISCVOp::OPERAND_SIMM6, llvm::RISCVOp::OPERAND_SIMM6_NONZERO, llvm::RISCVOp::OPERAND_UIMM2_LSB0, llvm::RISCVOp::OPERAND_UIMM7_LSB00, llvm::RISCVOp::OPERAND_UIMM8_LSB00, llvm::RISCVOp::OPERAND_UIMM8_LSB000, llvm::RISCVOp::OPERAND_UIMMLOG2XLEN, llvm::RISCVOp::OPERAND_UIMMLOG2XLEN_NONZERO, llvm::RISCVOp::OPERAND_VTYPEI10, llvm::RISCVOp::OPERAND_VTYPEI11, llvm::RISCVOp::OPERAND_ZERO, llvm::MCInstrDesc::operands(), SEW, STI, llvm::RISCVII::TAIL_AGNOSTIC, llvm::MCInstrDesc::TSFlags, TSFlags, uint64_t, and UseOpIdx.
Member Data Documentation
STI
const RISCVSubtarget& llvm::RISCVInstrInfo::STI protected
Definition at line 236 of file RISCVInstrInfo.h.
Referenced by analyzeSelect(), areMemAccessesTriviallyDisjoint(), copyPhysReg(), getInstSizeInBytes(), getNop(), getVLENFactoredAmount(), hasAllNBitUsers(), isBranchOffsetInRange(), movImm(), optimizeSelect(), and verifyInstruction().
The documentation for this class was generated from the following files:
lib/Target/RISCV/RISCVInstrInfo.h
lib/Target/RISCV/RISCVInstrInfo.cpp