LLVM: llvm::MCContext Class Reference
llvm::MCContext Class Reference
Context object for machine code objects.
#include "llvm/MC/MCContext.h"
Public Types
enum Environment {
IsMachO, IsELF, IsGOFF, IsCOFF,
IsSPIRV, IsWasm, IsXCOFF, IsDXContainer
}
using SymbolTable = StringMap< MCSymbol *, BumpPtrAllocator & >
using DiagHandlerTy = std::function< void(const SMDiagnostic &, bool, const SourceMgr &, std::vector< const MDNode * > &)>
Public Member Functions
MCContext (const Triple &TheTriple, const MCAsmInfo *MAI, const MCRegisterInfo *MRI, const MCSubtargetInfo *MSTI, const SourceMgr *Mgr=nullptr, MCTargetOptions const *TargetOpts=nullptr, bool DoAutoReset=true, StringRef Swift5ReflSegmentName={})
MCContext (const MCContext &)=delete
MCContext & operator= (const MCContext &)=delete
~MCContext ()
Environment getObjectFileType () const
const StringRef & getSwift5ReflectionSegmentName () const
const Triple & getTargetTriple () const
const SourceMgr * getSourceManager () const
void initInlineSourceManager ()
SourceMgr * getInlineSourceManager ()
std::vector< const MDNode * > & getLocInfos ()
void setDiagnosticHandler (DiagHandlerTy DiagHandler)
void setObjectFileInfo (const MCObjectFileInfo *Mofi)
const MCAsmInfo * getAsmInfo () const
const MCRegisterInfo * getRegisterInfo () const
const MCObjectFileInfo * getObjectFileInfo () const
const MCSubtargetInfo * getSubtargetInfo () const
CodeViewContext & getCVContext ()
void setAllowTemporaryLabels (bool Value)
void setUseNamesOnTempLabels (bool Value)
StringRef getSecureLogFile ()
raw_fd_ostream * getSecureLog ()
void setSecureLog (std::unique_ptr< raw_fd_ostream > Value)
bool getSecureLogUsed ()
void setSecureLogUsed (bool Value)
void * allocate (unsigned Size, unsigned Align=8)
void deallocate (void *Ptr)
bool hadError ()
void diagnose (const SMDiagnostic &SMD)
void reportError (SMLoc L, const Twine &Msg)
void reportWarning (SMLoc L, const Twine &Msg)
const MCAsmMacro * lookupMacro (StringRef Name)
void defineMacro (StringRef Name, MCAsmMacro Macro)
void undefineMacro (StringRef Name)
MCPseudoProbeTable & getMCPseudoProbeTable ()
Module Lifetime Management
void reset ()
reset - return object to right after construction state to prepare to process a new module
McInst Management
MCInst * createMCInst ()
Create and return a new MC instruction.
Symbol Management
MCSymbol * createLinkerPrivateTempSymbol ()
Create and return a new linker temporary symbol with a unique but unspecified name.
MCSymbol * createTempSymbol ()
Create a temporary symbol with a unique name.
MCSymbol * createTempSymbol (const Twine &Name, bool AlwaysAddSuffix=true)
MCSymbol * createNamedTempSymbol ()
Create a temporary symbol with a unique name whose name cannot be omitted in the symbol table.
MCSymbol * createNamedTempSymbol (const Twine &Name)
MCSymbol * createDirectionalLocalSymbol (unsigned LocalLabelVal)
Create the definition of a directional local symbol for numbered label (used for "1:" definitions).
MCSymbol * getDirectionalLocalSymbol (unsigned LocalLabelVal, bool Before)
Create and return a directional local symbol for numbered label (used for "1b" or 1f" references).
MCSymbol * getOrCreateSymbol (const Twine &Name)
Lookup the symbol inside with the specified Name.
MCSymbol * getOrCreateFrameAllocSymbol (StringRef FuncName, unsigned Idx)
Gets a symbol that will be defined to the final stack offset of a local variable after codegen.
MCSymbol * getOrCreateParentFrameOffsetSymbol (StringRef FuncName)
MCSymbol * getOrCreateLSDASymbol (StringRef FuncName)
MCSymbol * lookupSymbol (const Twine &Name) const
Get the symbol for Name, or null.
void setSymbolValue (MCStreamer &Streamer, StringRef Sym, uint64_t Val)
Set value for a symbol.
const SymbolTable & getSymbols () const
getSymbols - Get a reference for the symbol table for clients that want to, for example, iterate over all symbols.
MCSymbol * getInlineAsmLabel (StringRef Name) const
isInlineAsmLabel - Return true if the name is a label referenced in inline assembly.
void registerInlineAsmLabel (MCSymbol *Sym)
registerInlineAsmLabel - Records that the name is a label referenced in inline assembly.
Dwarf Management
StringRef getCompilationDir () const
Get the compilation directory for DW_AT_comp_dir The compilation directory should be set with setCompilationDir before calling this function.
void setCompilationDir (StringRef S)
Set the compilation directory for DW_AT_comp_dir.
void addDebugPrefixMapEntry (const std::string &From, const std::string &To)
Add an entry to the debug prefix map.
void remapDebugPath (SmallVectorImpl< char > &Path)
Remap one path in-place as per the debug prefix map.
void RemapDebugPaths ()
const std::string & getMainFileName () const
Get the main file name for use in error messages and debug info.
void setMainFileName (StringRef S)
Set the main file name and override the default.
Expected< unsigned > getDwarfFile (StringRef Directory, StringRef FileName, unsigned FileNumber, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source, unsigned CUID)
Creates an entry in the dwarf file and directory tables.
bool isValidDwarfFileNumber (unsigned FileNumber, unsigned CUID=0)
isValidDwarfFileNumber - takes a dwarf file number and returns true if it currently is assigned and false otherwise.
const std::map< unsigned, MCDwarfLineTable > & getMCDwarfLineTables () const
MCDwarfLineTable & getMCDwarfLineTable (unsigned CUID)
const MCDwarfLineTable & getMCDwarfLineTable (unsigned CUID) const
const SmallVectorImpl< MCDwarfFile > & getMCDwarfFiles (unsigned CUID=0)
const SmallVectorImpl< std::string > & getMCDwarfDirs (unsigned CUID=0)
unsigned getDwarfCompileUnitID ()
void setDwarfCompileUnitID (unsigned CUIndex)
void setMCLineTableRootFile (unsigned CUID, StringRef CompilationDir, StringRef Filename, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source)
Specifies the "root" file and directory of the compilation unit.
bool isDwarfMD5UsageConsistent (unsigned CUID) const
Reports whether MD5 checksum usage is consistent (all-or-none).
void setCurrentDwarfLoc (unsigned FileNum, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator)
Saves the information from the currently parsed dwarf .loc directive and sets DwarfLocSeen.
void clearDwarfLocSeen ()
bool getDwarfLocSeen ()
const MCDwarfLoc & getCurrentDwarfLoc ()
bool getGenDwarfForAssembly ()
void setGenDwarfForAssembly (bool Value)
unsigned getGenDwarfFileNumber ()
EmitDwarfUnwindType emitDwarfUnwindInfo () const
void setGenDwarfFileNumber (unsigned FileNumber)
void setGenDwarfRootFile (StringRef FileName, StringRef Buffer)
Specifies information about the "root file" for assembler clients (e.g., llvm-mc).
const SetVector< MCSection * > & getGenDwarfSectionSyms ()
bool addGenDwarfSection (MCSection *Sec)
void finalizeDwarfSections (MCStreamer &MCOS)
Remove empty sections from SectionsForRanges, to avoid generating useless debug info for them.
const std::vector< MCGenDwarfLabelEntry > & getMCGenDwarfLabelEntries () const
void addMCGenDwarfLabelEntry (const MCGenDwarfLabelEntry &E)
void setDwarfDebugFlags (StringRef S)
StringRef getDwarfDebugFlags ()
void setDwarfDebugProducer (StringRef S)
StringRef getDwarfDebugProducer ()
void setDwarfFormat (dwarf::DwarfFormat f)
dwarf::DwarfFormat getDwarfFormat () const
void setDwarfVersion (uint16_t v)
uint16_t getDwarfVersion () const
Section Management
enum : unsigned { GenericSectionID = ~0U }
MCSectionMachO * getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, unsigned Reserved2, SectionKind K, const char *BeginSymName=nullptr)
Return the MCSection for the specified mach-o section.
MCSectionMachO * getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, SectionKind K, const char *BeginSymName=nullptr)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags, unsigned EntrySize)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine &Group, bool IsComdat)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine &Group, bool IsComdat, unsigned UniqueID, const MCSymbolELF *LinkedToSym)
MCSectionELF * getELFSection (const Twine &Section, unsigned Type, unsigned Flags, unsigned EntrySize, const MCSymbolELF *Group, bool IsComdat, unsigned UniqueID, const MCSymbolELF *LinkedToSym)
MCSectionELF * getELFNamedSection (const Twine &Prefix, const Twine &Suffix, unsigned Type, unsigned Flags, unsigned EntrySize=0)
Get a section with the provided group identifier.
MCSectionELF * createELFRelSection (const Twine &Name, unsigned Type, unsigned Flags, unsigned EntrySize, const MCSymbolELF *Group, const MCSectionELF *RelInfoSection)
MCSectionELF * createELFGroupSection (const MCSymbolELF *Group, bool IsComdat)
void recordELFMergeableSectionInfo (StringRef SectionName, unsigned Flags, unsigned UniqueID, unsigned EntrySize)
bool isELFImplicitMergeableSectionNamePrefix (StringRef Name)
bool isELFGenericMergeableSection (StringRef Name)
std::optional< unsigned > getELFUniqueIDForEntsize (StringRef SectionName, unsigned Flags, unsigned EntrySize)
Return the unique ID of the section with the given name, flags and entry size, if it exists.
MCSectionGOFF * getGOFFSection (StringRef Section, SectionKind Kind, MCSection *Parent, const MCExpr *SubsectionId)
MCSectionCOFF * getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, StringRef COMDATSymName, int Selection, unsigned UniqueID=GenericSectionID, const char *BeginSymName=nullptr)
MCSectionCOFF * getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, const char *BeginSymName=nullptr)
MCSectionCOFF * getAssociativeCOFFSection (MCSectionCOFF *Sec, const MCSymbol *KeySym, unsigned UniqueID=GenericSectionID)
Gets or creates a section equivalent to Sec that is associated with the section containing KeySym.
MCSectionSPIRV * getSPIRVSection ()
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K, unsigned Flags=0)
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K, unsigned Flags, const char *BeginSymName)
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K, unsigned Flags, const Twine &Group, unsigned UniqueID)
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K, unsigned Flags, const Twine &Group, unsigned UniqueID, const char *BeginSymName)
MCSectionWasm * getWasmSection (const Twine &Section, SectionKind K, unsigned Flags, const MCSymbolWasm *Group, unsigned UniqueID, const char *BeginSymName)
MCSectionDXContainer * getDXContainerSection (StringRef Section, SectionKind K)
Get the section for the provided Section name.
bool hasXCOFFSection (StringRef Section, XCOFF::CsectProperties CsectProp) const
MCSectionXCOFF * getXCOFFSection (StringRef Section, SectionKind K, std::optional< XCOFF::CsectProperties > CsectProp=std::nullopt, bool MultiSymbolsAllowed=false, const char *BeginSymName=nullptr, std::optional< XCOFF::DwarfSectionSubtypeFlags > DwarfSubtypeFlags=std::nullopt)
MCSubtargetInfo & getSubtargetCopy (const MCSubtargetInfo &STI)
uint8_t getBBAddrMapVersion () const
Detailed Description
Context object for machine code objects.
This class owns all of the sections that it creates.
Definition at line 76 of file MCContext.h.
Member Typedef Documentation
DiagHandlerTy
using llvm::MCContext::DiagHandlerTy = std::function<void(const SMDiagnostic &, bool, const SourceMgr &, std::vector<const MDNode *> &)>
Definition at line 81 of file MCContext.h.
SymbolTable
using llvm::MCContext::SymbolTable = StringMap<MCSymbol *, BumpPtrAllocator &>
Definition at line 78 of file MCContext.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned
Enumerator
GenericSectionID
Pass this value as the UniqueID during section creation to get the generic section with the given name and characteristics.
The usual sections such as .text use this ID.
Definition at line 542 of file MCContext.h.
Environment
enum llvm::MCContext::Environment
Enumerator
IsMachO
IsELF
IsGOFF
IsCOFF
IsSPIRV
IsWasm
IsXCOFF
IsDXContainer
Definition at line 82 of file MCContext.h.
Constructor & Destructor Documentation
MCContext() [1/2]
MCContext::MCContext (const Triple & TheTriple, const MCAsmInfo * MAI, const MCRegisterInfo * MRI, const MCSubtargetInfo * MSTI, const SourceMgr * Mgr = nullptr, MCTargetOptions const * TargetOpts = nullptr, bool DoAutoReset = true, StringRef Swift5ReflSegmentName = {}) explicit
Definition at line 67 of file MCContext.cpp.
References llvm::Triple::COFF, llvm::Triple::DXContainer, llvm::Triple::ELF, llvm::MemoryBuffer::getBufferIdentifier(), llvm::SourceMgr::getMainFileID(), llvm::SourceMgr::getMemoryBuffer(), llvm::SourceMgr::getNumBuffers(), llvm::Triple::getObjectFormat(), llvm::Triple::GOFF, IsCOFF, IsDXContainer, IsELF, IsGOFF, IsMachO, llvm::Triple::isOSWindows(), IsSPIRV, IsWasm, IsXCOFF, llvm::Triple::MachO, llvm::report_fatal_error(), llvm::Triple::SPIRV, llvm::Triple::UnknownObjectFormat, llvm::Triple::Wasm, and llvm::Triple::XCOFF.
MCContext() [2/2]
llvm::MCContext::MCContext (const MCContext &) delete
~MCContext()
MCContext::~MCContext ()
Definition at line 118 of file MCContext.cpp.
References reset().
Member Function Documentation
addDebugPrefixMapEntry()
void MCContext::addDebugPrefixMapEntry (const std::string & From, const std::string & To)
Add an entry to the debug prefix map.
Definition at line 885 of file MCContext.cpp.
References From.
addGenDwarfSection()
bool llvm::MCContext::addGenDwarfSection (MCSection * Sec) inline
Definition at line 804 of file MCContext.h.
References llvm::SetVector< T, Vector, Set >::insert().
addMCGenDwarfLabelEntry()
void llvm::MCContext::addMCGenDwarfLabelEntry (const MCGenDwarfLabelEntry & E) inline
Definition at line 814 of file MCContext.h.
References E.
Referenced by llvm::MCGenDwarfLabelEntry::Make().
allocate()
void* llvm::MCContext::allocate (unsigned Size, unsigned Align = 8) inline
Definition at line 842 of file MCContext.h.
References Allocator.
clearDwarfLocSeen()
void llvm::MCContext::clearDwarfLocSeen () inline
Definition at line 782 of file MCContext.h.
Referenced by llvm::MCObjectStreamer::changeSectionImpl(), and llvm::MCDwarfLineEntry::make().
createDirectionalLocalSymbol()
MCSymbol * MCContext::createDirectionalLocalSymbol (unsigned LocalLabelVal)
Create the definition of a directional local symbol for numbered label (used for "1:" definitions).
Definition at line 346 of file MCContext.cpp.
createELFGroupSection()
MCSectionELF * MCContext::createELFGroupSection (const MCSymbolELF * Group, bool IsComdat)
Definition at line 606 of file MCContext.cpp.
References llvm::SectionKind::getReadOnly(), llvm::MCSection::NonUniqueID, and llvm::ELF::SHT_GROUP.
createELFRelSection()
MCSectionELF * MCContext::createELFRelSection (const Twine & Name, unsigned Type, unsigned Flags, unsigned EntrySize, const MCSymbolELF * Group, const MCSectionELF * RelInfoSection)
Definition at line 501 of file MCContext.cpp.
References llvm::MCSection::getBeginSymbol(), llvm::SectionKind::getReadOnly(), I, and llvm::StringMap< ValueTy, AllocatorTy >::insert().
createLinkerPrivateTempSymbol()
MCSymbol * MCContext::createLinkerPrivateTempSymbol ()
Create and return a new linker temporary symbol with a unique but unspecified name.
Definition at line 312 of file MCContext.cpp.
References llvm::MCAsmInfo::getLinkerPrivateGlobalPrefix().
Referenced by llvm::AsmPrinter::emitKCFITrapEntry().
createMCInst()
MCInst * MCContext::createMCInst ()
Create and return a new MC instruction.
Definition at line 193 of file MCContext.cpp.
Referenced by llvm::HexagonLowerToMC().
createNamedTempSymbol() [1/2]
MCSymbol * MCContext::createNamedTempSymbol ()
Create a temporary symbol with a unique name whose name cannot be omitted in the symbol table.
This is rarely used.
Definition at line 320 of file MCContext.cpp.
createNamedTempSymbol() [2/2]
MCSymbol * MCContext::createNamedTempSymbol (const Twine & Name)
Definition at line 306 of file MCContext.cpp.
References llvm::MCAsmInfo::getPrivateGlobalPrefix().
createTempSymbol() [1/2]
MCSymbol * MCContext::createTempSymbol ()
Create a temporary symbol with a unique name.
The name will be omitted in the symbol table if UseNamesOnTempLabels is false (default except MCAsmStreamer). The overload without Name uses an unspecified name.
Definition at line 318 of file MCContext.cpp.
Referenced by llvm::MachineFunction::addLandingPad(), ARM64EmitUnwindInfoForSegment(), ARMEmitUnwindInfo(), llvm::DebugHandlerBase::beginInstruction(), llvm::AsmPrinter::createTempSymbol(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MipsELFStreamer::emitCFIEndProcImpl(), llvm::MipsELFStreamer::emitCFILabel(), llvm::MipsELFStreamer::emitCFIStartProcImpl(), llvm::MCObjectStreamer::emitCVLocDirective(), emitDirectiveRelocJalr(), llvm::CodeViewContext::emitFileChecksums(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitKCFITypeId(), llvm::CodeViewContext::emitLineTableForFunction(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), EmitNop(), llvm::AsmPrinter::emitPCSections(), llvm::AsmPrinter::emitPCSectionsLabel(), llvm::AArch64FrameLowering::emitPrologue(), llvm::HexagonAsmPrinter::EmitSled(), llvm::CodeViewContext::emitStringTable(), EmitUnwindInfo(), llvm::AsmPrinter::emitXRayTable(), llvm::DebugHandlerBase::endInstruction(), getCOFFSection(), llvm::MCSection::getEndSymbol(), getMachOSection(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::MCDwarfLineEntry::make(), and llvm::MCGenDwarfLabelEntry::Make().
createTempSymbol() [2/2]
MCSymbol * MCContext::createTempSymbol (const Twine & Name, bool AlwaysAddSuffix = true)
Definition at line 300 of file MCContext.cpp.
References llvm::MCAsmInfo::getPrivateGlobalPrefix().
deallocate()
void llvm::MCContext::deallocate (void * Ptr) inline
Definition at line 846 of file MCContext.h.
defineMacro()
void llvm::MCContext::defineMacro (StringRef Name, MCAsmMacro Macro) inline
Definition at line 858 of file MCContext.h.
References llvm::Macro, and move.
diagnose()
void MCContext::diagnose (const SMDiagnostic & SMD)
Definition at line 1010 of file MCContext.cpp.
References assert(), and llvm_unreachable.
emitDwarfUnwindInfo()
EmitDwarfUnwindType MCContext::emitDwarfUnwindInfo () const
Definition at line 925 of file MCContext.cpp.
References llvm::Default.
finalizeDwarfSections()
void MCContext::finalizeDwarfSections (MCStreamer & MCOS)
Remove empty sections from SectionsForRanges, to avoid generating useless debug info for them.
Definition at line 995 of file MCContext.cpp.
References llvm::MCStreamer::mayHaveInstructions().
Referenced by llvm::MCGenDwarfInfo::Emit().
getAsmInfo()
const MCAsmInfo* llvm::MCContext::getAsmInfo () const inline
Definition at line 446 of file MCContext.h.
Referenced by llvm::DwarfCFIException::beginFunction(), calcUniqueIDUpdateFlagsAndSize(), llvm::MCTargetStreamer::changeSection(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCObjectStreamer::emitDwarfLineEndEntry(), emitFDESymbol(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::ARMTargetStreamer::emitInst(), llvm::MCDwarfLineTable::emitOne(), EmitPersonality(), llvm::NVPTXTargetStreamer::emitRawBytes(), llvm::MCTargetStreamer::emitRawBytes(), llvm::MCTargetStreamer::emitValue(), getDataAlignmentFactor(), llvm::MachineBasicBlock::getEndSymbol(), getRelocType32(), getRelocType64(), getSizeForEncoding(), llvm::MachineBasicBlock::getSymbol(), llvm::TargetLoweringObjectFileELF::Initialize(), llvm::MCELFStreamer::initSections(), llvm::MCDwarfLineStr::MCDwarfLineStr(), llvm::RISCVAsmBackend::relaxDwarfCFA(), selectELFSectionForGlobal(), and selectExplicitSectionGlobal().
getAssociativeCOFFSection()
MCSectionCOFF * MCContext::getAssociativeCOFFSection (MCSectionCOFF * Sec, const MCSymbol * KeySym, unsigned UniqueID = GenericSectionID)
Gets or creates a section equivalent to Sec that is associated with the section containing KeySym.
For example, to create a debug info section associated with an inline function, pass the normal debug info section as Sec and the function symbol as KeySym.
Definition at line 700 of file MCContext.cpp.
References Characteristics, GenericSectionID, llvm::MCSectionCOFF::getCharacteristics(), getCOFFSection(), llvm::MCSection::getKind(), llvm::MCSection::getName(), llvm::MCSymbol::getName(), llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, and llvm::COFF::IMAGE_SCN_LNK_COMDAT.
Referenced by getCOFFStaticStructorSection().
getBBAddrMapVersion()
uint8_t llvm::MCContext::getBBAddrMapVersion () const inline
Definition at line 684 of file MCContext.h.
Referenced by llvm::MachineBasicBlock::getBBIDOrNumber().
getCOFFSection() [1/2]
MCSectionCOFF * MCContext::getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, const char * BeginSymName = nullptr)
Definition at line 692 of file MCContext.cpp.
References Characteristics, GenericSectionID, and getCOFFSection().
getCOFFSection() [2/2]
MCSectionCOFF * MCContext::getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, StringRef COMDATSymName, int Selection, unsigned UniqueID = GenericSectionID, const char * BeginSymName = nullptr)
Definition at line 660 of file MCContext.cpp.
References Characteristics, createTempSymbol(), llvm::StringRef::empty(), llvm::MCSymbol::getName(), getOrCreateSymbol(), and Selection.
Referenced by llvm::AsmPrinter::doFinalization(), getAssociativeCOFFSection(), getCOFFSection(), getCOFFStaticStructorSection(), and llvm::TargetLoweringObjectFileCOFF::Initialize().
getCompilationDir()
StringRef llvm::MCContext::getCompilationDir () const inline
Get the compilation directory for DW_AT_comp_dir The compilation directory should be set with setCompilationDir before calling this function.
If it is unset, an empty string will be returned.
Definition at line 694 of file MCContext.h.
Referenced by EmitGenDwarfAbbrev(), and setGenDwarfRootFile().
getCurrentDwarfLoc()
const MCDwarfLoc& llvm::MCContext::getCurrentDwarfLoc () inline
Definition at line 785 of file MCContext.h.
Referenced by llvm::MCDwarfLineEntry::make().
getCVContext()
CodeViewContext & MCContext::getCVContext ()
Definition at line 1000 of file MCContext.cpp.
Referenced by llvm::MCStreamer::checkCVLocSection(), llvm::MCObjectStreamer::emitCVDefRangeDirective(), llvm::MCObjectStreamer::emitCVFileChecksumOffsetDirective(), llvm::MCObjectStreamer::emitCVFileChecksumsDirective(), llvm::MCStreamer::emitCVFileDirective(), llvm::MCStreamer::emitCVFuncIdDirective(), llvm::MCObjectStreamer::emitCVInlineLinetableDirective(), llvm::MCStreamer::emitCVInlineSiteIdDirective(), llvm::MCObjectStreamer::emitCVLocDirective(), and llvm::MCObjectStreamer::emitCVStringTableDirective().
getDirectionalLocalSymbol()
MCSymbol * MCContext::getDirectionalLocalSymbol (unsigned LocalLabelVal, bool Before)
Create and return a directional local symbol for numbered label (used for "1b" or 1f" references).
Definition at line 351 of file MCContext.cpp.
getDwarfCompileUnitID()
unsigned llvm::MCContext::getDwarfCompileUnitID () inline
Definition at line 747 of file MCContext.h.
Referenced by llvm::MCDwarfLineEntry::make().
getDwarfDebugFlags()
StringRef llvm::MCContext::getDwarfDebugFlags () inline
Definition at line 819 of file MCContext.h.
Referenced by EmitGenDwarfAbbrev().
getDwarfDebugProducer()
StringRef llvm::MCContext::getDwarfDebugProducer () inline
Definition at line 822 of file MCContext.h.
getDwarfFile()
Expected< unsigned > MCContext::getDwarfFile (StringRef Directory, StringRef FileName, unsigned FileNumber, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source, unsigned CUID)
Creates an entry in the dwarf file and directory tables.
getDwarfFile - takes a file name and number to place in the dwarf file and directory tables.
If the file number has already been allocated it is an error and zero is returned and the client reports the error, else the allocated file number is returned. The file numbers may be in any order.
Definition at line 972 of file MCContext.cpp.
References llvm::Sched::Source, and llvm::MCDwarfLineTable::tryGetFile().
Referenced by llvm::MCStreamer::tryEmitDwarfFileDirective().
getDwarfFormat()
dwarf::DwarfFormat llvm::MCContext::getDwarfFormat () const inline
Definition at line 825 of file MCContext.h.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), and llvm::MCDwarfLineStr::emitRef().
getDwarfLocSeen()
bool llvm::MCContext::getDwarfLocSeen () inline
Definition at line 784 of file MCContext.h.
Referenced by llvm::MCDwarfLineEntry::make().
getDwarfVersion()
uint16_t llvm::MCContext::getDwarfVersion () const inline
Definition at line 828 of file MCContext.h.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), llvm::MCDwarfLineTable::emit(), llvm::MCGenDwarfInfo::Emit(), EmitGenDwarfAbbrev(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::MCDwarfLineTable::emitOne(), isValidDwarfFileNumber(), and setGenDwarfRootFile().
getDXContainerSection()
MCSectionDXContainer * MCContext::getDXContainerSection (StringRef Section, SectionKind K)
Get the section for the provided Section name.
Definition at line 858 of file MCContext.cpp.
References F.
getELFNamedSection()
MCSectionELF * MCContext::getELFNamedSection (const Twine & Prefix, const Twine & Suffix, unsigned Type, unsigned Flags, unsigned EntrySize = 0)
Get a section with the provided group identifier.
This section is named by concatenating Prefix with '.' then Suffix. The Type describes the type of the section and Flags are used to further configure this named section.
Definition at line 515 of file MCContext.cpp.
References getELFSection(), and llvm::cl::Prefix.
getELFSection() [1/5]
MCSectionELF* llvm::MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags) inline
Definition at line 563 of file MCContext.h.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::MCELFStreamer::emitCommonSymbol(), llvm::MCELFStreamer::emitIdent(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::X86AsmPrinter::emitStartOfAsmFile(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::AsmPrinter::emitXRayTable(), llvm::MCObjectFileInfo::getBBAddrMapSection(), getELFNamedSection(), getELFSection(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), llvm::MCObjectFileInfo::getKCFITrapSection(), llvm::MCObjectFileInfo::getPCSection(), llvm::MCObjectFileInfo::getPseudoProbeDescSection(), llvm::MCObjectFileInfo::getPseudoProbeSection(), llvm::MCObjectFileInfo::getStackSizesSection(), getStaticStructorSection(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::HexagonTargetObjectFile::Initialize(), llvm::AVRTargetObjectFile::Initialize(), llvm::RISCVELFTargetObjectFile::Initialize(), llvm::ARMElfTargetObjectFile::Initialize(), llvm::XCoreTargetObjectFile::Initialize(), llvm::LanaiTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::M68kELFTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileELF::InitializeELF(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), selectELFSectionForGlobal(), selectExplicitSectionGlobal(), and smallData().
getELFSection() [2/5]
MCSectionELF* llvm::MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags, unsigned EntrySize) inline
Definition at line 568 of file MCContext.h.
References getELFSection(), and llvm::MCSection::NonUniqueID.
getELFSection() [3/5]
MCSectionELF * MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags, unsigned EntrySize, const MCSymbolELF * Group, bool IsComdat, unsigned UniqueID, const MCSymbolELF * LinkedToSym)
Definition at line 536 of file MCContext.cpp.
References assert(), llvm::StringRef::empty(), and llvm::MCSymbol::getName().
getELFSection() [4/5]
MCSectionELF* llvm::MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine & Group, bool IsComdat) inline
Definition at line 574 of file MCContext.h.
References getELFSection(), and llvm::MCSection::NonUniqueID.
getELFSection() [5/5]
MCSectionELF * MCContext::getELFSection (const Twine & Section, unsigned Type, unsigned Flags, unsigned EntrySize, const Twine & Group, bool IsComdat, unsigned UniqueID, const MCSymbolELF * LinkedToSym)
Definition at line 523 of file MCContext.cpp.
References getELFSection(), getOrCreateSymbol(), llvm::Twine::isTriviallyEmpty(), and llvm::Twine::str().
getELFUniqueIDForEntsize()
std::optional< unsigned > MCContext::getELFUniqueIDForEntsize (StringRef SectionName, unsigned Flags, unsigned EntrySize)
Return the unique ID of the section with the given name, flags and entry size, if it exists.
Definition at line 640 of file MCContext.cpp.
References I, and llvm::AMDGPU::ElfNote::SectionName.
Referenced by calcUniqueIDUpdateFlagsAndSize().
getGenDwarfFileNumber()
unsigned llvm::MCContext::getGenDwarfFileNumber () inline
Definition at line 789 of file MCContext.h.
Referenced by llvm::MCGenDwarfLabelEntry::Make().
getGenDwarfForAssembly()
bool llvm::MCContext::getGenDwarfForAssembly () inline
Definition at line 787 of file MCContext.h.
getGenDwarfSectionSyms()
const SetVector<MCSection *>& llvm::MCContext::getGenDwarfSectionSyms () inline
Definition at line 800 of file MCContext.h.
Referenced by llvm::MCGenDwarfInfo::Emit(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), and llvm::MCGenDwarfLabelEntry::Make().
getGOFFSection()
MCSectionGOFF * MCContext::getGOFFSection (StringRef Section, SectionKind Kind, MCSection * Parent, const MCExpr * SubsectionId)
Definition at line 648 of file MCContext.cpp.
getInlineAsmLabel()
MCSymbol* llvm::MCContext::getInlineAsmLabel (StringRef Name) const inline
isInlineAsmLabel - Return true if the name is a label referenced in inline assembly.
Definition at line 529 of file MCContext.h.
getInlineSourceManager()
SourceMgr* llvm::MCContext::getInlineSourceManager () inline
Definition at line 438 of file MCContext.h.
getLocInfos()
std::vector<const MDNode *>& llvm::MCContext::getLocInfos () inline
Definition at line 439 of file MCContext.h.
getMachOSection() [1/2]
MCSectionMachO* llvm::MCContext::getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, SectionKind K, const char * BeginSymName = nullptr) inline
Definition at line 556 of file MCContext.h.
References getMachOSection().
getMachOSection() [2/2]
MCSectionMachO * MCContext::getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, unsigned Reserved2, SectionKind K, const char * BeginSymName = nullptr)
Return the MCSection for the specified mach-o section.
This requires the operands to be valid.
Definition at line 435 of file MCContext.cpp.
References assert(), and createTempSymbol().
Referenced by emitNonLazyStubs(), llvm::AsmPrinter::emitXRayTable(), getMachOSection(), and llvm::TargetLoweringObjectFileMachO::Initialize().
getMainFileName()
const std::string& llvm::MCContext::getMainFileName () const inline
Get the main file name for use in error messages and debug info.
This can be set to ensure we've got the correct file name after preprocessing or for -save-temps.
Definition at line 711 of file MCContext.h.
Referenced by setGenDwarfRootFile().
getMCDwarfDirs()
const SmallVectorImpl<std::string>& llvm::MCContext::getMCDwarfDirs (unsigned CUID = 0) inline
Definition at line 743 of file MCContext.h.
References llvm::MCDwarfLineTable::getMCDwarfDirs(), and getMCDwarfLineTable().
getMCDwarfFiles()
const SmallVectorImpl<MCDwarfFile>& llvm::MCContext::getMCDwarfFiles (unsigned CUID = 0) inline
Definition at line 739 of file MCContext.h.
References llvm::MCDwarfLineTable::getMCDwarfFiles(), and getMCDwarfLineTable().
getMCDwarfLineTable() [1/2]
MCDwarfLineTable& llvm::MCContext::getMCDwarfLineTable (unsigned CUID) inline
Definition at line 729 of file MCContext.h.
Referenced by llvm::MCStreamer::getDwarfLineTableSymbol(), getMCDwarfDirs(), getMCDwarfFiles(), isDwarfMD5UsageConsistent(), isValidDwarfFileNumber(), llvm::MCDwarfLineEntry::make(), and setMCLineTableRootFile().
getMCDwarfLineTable() [2/2]
const MCDwarfLineTable& llvm::MCContext::getMCDwarfLineTable (unsigned CUID) const inline
Definition at line 733 of file MCContext.h.
References assert(), and I.
getMCDwarfLineTables()
const std::map<unsigned, MCDwarfLineTable>& llvm::MCContext::getMCDwarfLineTables () const inline
Definition at line 725 of file MCContext.h.
Referenced by llvm::MCDwarfLineTable::emit().
getMCGenDwarfLabelEntries()
const std::vector<MCGenDwarfLabelEntry>& llvm::MCContext::getMCGenDwarfLabelEntries () const inline
Definition at line 810 of file MCContext.h.
getMCPseudoProbeTable()
MCPseudoProbeTable& llvm::MCContext::getMCPseudoProbeTable () inline
Definition at line 864 of file MCContext.h.
Referenced by llvm::MCPseudoProbeTable::emit().
getObjectFileInfo()
const MCObjectFileInfo* llvm::MCContext::getObjectFileInfo () const inline
Definition at line 450 of file MCContext.h.
Referenced by llvm::NVPTXTargetStreamer::changeSection(), llvm::MCPseudoProbeSections::emit(), llvm::MCDwarfLineTable::emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCWinCOFFStreamer::emitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::emitCommonSymbol(), llvm::SystemZTargetStreamer::emitConstantPools(), llvm::MCObjectStreamer::emitDwarfLineEndEntry(), llvm::MipsAsmPrinter::emitEndOfAsmFile(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::MCWinCOFFStreamer::emitLocalCommonSymbol(), llvm::AsmPrinter::emitRemarksSection(), llvm::MCDwarfLineStr::emitSection(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::X86FrameLowering::enableShrinkWrapping(), llvm::WinCFGuard::endModule(), llvm::WinException::endModule(), llvm::MipsTargetELFStreamer::finish(), llvm::MCELFStreamer::initSections(), llvm::MCDwarfLineStr::MCDwarfLineStr(), llvm::MipsTargetELFStreamer::MipsTargetELFStreamer(), llvm::FaultMaps::serializeToFaultMapSection(), llvm::StackMaps::serializeToStackMapSection(), and llvm::write().
getObjectFileType()
Environment llvm::MCContext::getObjectFileType () const inline
Definition at line 429 of file MCContext.h.
Referenced by llvm::MCObjectFileInfo::getBBAddrMapSection(), llvm::MCObjectFileInfo::getKCFITrapSection(), llvm::MCObjectFileInfo::getPCSection(), llvm::MCObjectFileInfo::getPseudoProbeDescSection(), llvm::MCObjectFileInfo::getPseudoProbeSection(), llvm::MCObjectFileInfo::getStackSizesSection(), and llvm::MCObjectFileInfo::initMCObjectFileInfo().
getOrCreateFrameAllocSymbol()
MCSymbol * MCContext::getOrCreateFrameAllocSymbol (StringRef FuncName, unsigned Idx)
Gets a symbol that will be defined to the final stack offset of a local variable after codegen.
Parameters
Idx - The index of a local variable passed to @llvm.localescape.
Definition at line 214 of file MCContext.cpp.
References getOrCreateSymbol(), and llvm::MCAsmInfo::getPrivateGlobalPrefix().
getOrCreateLSDASymbol()
MCSymbol * MCContext::getOrCreateLSDASymbol (StringRef FuncName)
Definition at line 225 of file MCContext.cpp.
References getOrCreateSymbol(), and llvm::MCAsmInfo::getPrivateGlobalPrefix().
getOrCreateParentFrameOffsetSymbol()
MCSymbol * MCContext::getOrCreateParentFrameOffsetSymbol (StringRef FuncName)
Definition at line 220 of file MCContext.cpp.
References getOrCreateSymbol(), and llvm::MCAsmInfo::getPrivateGlobalPrefix().
Referenced by recoverFramePointer().
getOrCreateSymbol()
MCSymbol * MCContext::getOrCreateSymbol (const Twine & Name)
Lookup the symbol inside with the specified Name.
If it exists, return it. If not, create a forward reference and return it.
Parameters
Name - The symbol name, which must be unique across all symbols.
Definition at line 201 of file MCContext.cpp.
References assert(), and llvm::StringRef::empty().
Referenced by llvm::ModuloScheduleTestAnnotater::annotate(), llvm::AVRAsmPrinter::doFinalization(), EmitCamlGlobal(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), llvm::AsmPrinter::emitGlobalVariable(), llvm::X86AsmPrinter::emitKCFITypeId(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::AVRAsmPrinter::emitStartOfAsmFile(), llvm::X86AsmPrinter::emitStartOfAsmFile(), llvm::AVRAsmPrinter::emitXXStructor(), llvm::RecordStreamer::flushSymverDirectives(), getBFLabel(), getCOFFSection(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), llvm::LanaiMCInstLower::GetConstantPoolIndexSymbol(), llvm::ARMAsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::MachineBasicBlock::getEHCatchretSymbol(), llvm::TargetLoweringObjectFileXCOFF::getEHInfoTableSymbol(), getELFSection(), llvm::MachineBasicBlock::getEndSymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::NVPTXAsmPrinter::getFunctionFrameSymbol(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::PPCFunctionInfo::getGlobalEPSymbol(), llvm::MachineFunction::getJTISymbol(), llvm::AsmPrinter::GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), llvm::LanaiMCInstLower::GetJumpTableSymbol(), llvm::PPCFunctionInfo::getLocalEPSymbol(), getMCSymbolForMBB(), getOrCreateFrameAllocSymbol(), llvm::WebAssembly::getOrCreateFuncrefCallTableSymbol(), llvm::WebAssembly::getOrCreateFunctionTableSymbol(), getOrCreateLSDASymbol(), getOrCreateParentFrameOffsetSymbol(), llvm::MachineFunction::getPICBaseSymbol(), getPICLabel(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), llvm::TargetMachine::getSymbol(), llvm::MachineBasicBlock::getSymbol(), GetSymbolFromOperand(), llvm::M68kMCInstLower::GetSymbolFromOperand(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::PPCFunctionInfo::getTOCOffsetSymbol(), getWasmSection(), llvm::FastISel::lowerCallTo(), llvm::VETargetLowering::LowerCustomJumpTableEntry(), AMDGPUMCInstLower::lowerOperand(), llvm::MCParserUtils::parseAssignmentExpression(), llvm::MCAsmParserExtension::ParseDirectiveCGProfile(), llvm::FaultMaps::serializeToFaultMapSection(), llvm::StackMaps::serializeToStackMapSection(), llvm::FastISel::CallLoweringInfo::setCallee(), setSymbolValue(), smallData(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::MCExternalSymbolizer::tryAddingSymbolicOperand().
getRegisterInfo()
const MCRegisterInfo* llvm::MCContext::getRegisterInfo () const inline
Definition at line 448 of file MCContext.h.
References MRI.
Referenced by buildDefCFAReg(), llvm::createBPFbeMCCodeEmitter(), llvm::createBPFMCCodeEmitter(), llvm::createR600MCCodeEmitter(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMovesFullCFA(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), encodeSEHRegNum(), llvm::PPCMCCodeEmitter::get_crbitm_encoding(), llvm::CSKYMCCodeEmitter::getMachineOpValue(), llvm::PPCMCCodeEmitter::getMachineOpValue(), llvm::MipsMCCodeEmitter::getMachineOpValue(), llvm::AMDGPUDisassembler::getRegClassName(), llvm::MipsMCCodeEmitter::getRegisterListOpValue(), llvm::CSKYMCCodeEmitter::getRegisterSeqOpValue(), llvm::CSKYMCCodeEmitter::getRegSeqImmOpValue(), llvm::PPCMCCodeEmitter::getTLSRegEncoding(), llvm::PPCFrameLowering::inlineStackProbe(), and llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand().
getSecureLog()
raw_fd_ostream* llvm::MCContext::getSecureLog () inline
Definition at line 833 of file MCContext.h.
getSecureLogFile()
StringRef llvm::MCContext::getSecureLogFile () inline
Definition at line 832 of file MCContext.h.
getSecureLogUsed()
bool llvm::MCContext::getSecureLogUsed () inline
Definition at line 839 of file MCContext.h.
getSourceManager()
const SourceMgr* llvm::MCContext::getSourceManager () const inline
Definition at line 435 of file MCContext.h.
References llvm::SrcMgr.
Referenced by llvm::MCObjectStreamer::emitFill(), llvm::HexagonShuffler::reportError(), llvm::HexagonMCChecker::reportNote(), and llvm::HexagonShuffler::reportResourceUsage().
getSPIRVSection()
MCSectionSPIRV * MCContext::getSPIRVSection ()
Definition at line 843 of file MCContext.cpp.
References F, llvm::SectionKind::getText(), and llvm::MCSymbol::setFragment().
getSubtargetCopy()
MCSubtargetInfo & MCContext::getSubtargetCopy (const MCSubtargetInfo & STI)
Definition at line 881 of file MCContext.cpp.
Referenced by llvm::MCTargetAsmParser::copySTI().
getSubtargetInfo()
const MCSubtargetInfo* llvm::MCContext::getSubtargetInfo () const inline
Definition at line 452 of file MCContext.h.
Referenced by llvm::RISCVMCObjectFileInfo::getTextSectionAlignment().
getSwift5ReflectionSegmentName()
const StringRef& llvm::MCContext::getSwift5ReflectionSegmentName () const inline
Definition at line 431 of file MCContext.h.
getSymbols()
const SymbolTable& llvm::MCContext::getSymbols () const inline
getSymbols - Get a reference for the symbol table for clients that want to, for example, iterate over all symbols.
'const' because we still want any modifications to the table itself to use the MCContext APIs.
Definition at line 525 of file MCContext.h.
Referenced by llvm::WebAssemblyAsmPrinter::emitDecls().
getTargetTriple()
const Triple& llvm::MCContext::getTargetTriple () const inline
Definition at line 434 of file MCContext.h.
Referenced by llvm::MCTargetStreamer::changeSection(), llvm::MCWinCOFFStreamer::emitCommonSymbol(), llvm::MCObjectFileInfo::getPseudoProbeDescSection(), llvm::MCObjectFileInfo::getStackSizesSection(), and llvm::MCObjectFileInfo::initMCObjectFileInfo().
getWasmSection() [1/5]
MCSectionWasm* llvm::MCContext::getWasmSection (const Twine & Section, SectionKind K, unsigned Flags, const char * BeginSymName) inline
Definition at line 649 of file MCContext.h.
References getWasmSection().
getWasmSection() [2/5]
MCSectionWasm * MCContext::getWasmSection (const Twine & Section, SectionKind K, unsigned Flags, const MCSymbolWasm * Group, unsigned UniqueID, const char * BeginSymName)
Definition at line 734 of file MCContext.cpp.
References llvm::MCSymbol::getName().
getWasmSection() [3/5]
MCSectionWasm* llvm::MCContext::getWasmSection (const Twine & Section, SectionKind K, unsigned Flags, const Twine & Group, unsigned UniqueID) inline
Definition at line 654 of file MCContext.h.
References getWasmSection().
getWasmSection() [4/5]
MCSectionWasm * MCContext::getWasmSection (const Twine & Section, SectionKind K, unsigned Flags, const Twine & Group, unsigned UniqueID, const char * BeginSymName)
Definition at line 721 of file MCContext.cpp.
References getOrCreateSymbol(), getWasmSection(), llvm::Twine::isTriviallyEmpty(), llvm::MCSymbolWasm::setComdat(), and llvm::Twine::str().
getWasmSection() [5/5]
MCSectionWasm* llvm::MCContext::getWasmSection (const Twine & Section, SectionKind K, unsigned Flags = 0) inline
Definition at line 644 of file MCContext.h.
Referenced by llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), getWasmSection(), and selectWasmSectionForGlobal().
getXCOFFSection()
MCSectionXCOFF * MCContext::getXCOFFSection (StringRef Section, SectionKind K, std::optional< XCOFF::CsectProperties > CsectProp = std::nullopt, bool MultiSymbolsAllowed = false, const char * BeginSymName = nullptr, std::optional< XCOFF::DwarfSectionSubtypeFlags > DwarfSubtypeFlags = std::nullopt)
Definition at line 773 of file MCContext.cpp.
References assert().
Referenced by createMCSymbolForTlsGetAddr().
hadError()
bool llvm::MCContext::hadError () inline
Definition at line 848 of file MCContext.h.
Referenced by llvm::MCAssembler::layout().
hasXCOFFSection()
bool MCContext::hasXCOFFSection (StringRef Section, XCOFF::CsectProperties CsectProp) const
Definition at line 767 of file MCContext.cpp.
References llvm::XCOFF::CsectProperties::MappingClass.
initInlineSourceManager()
void MCContext::initInlineSourceManager ()
Definition at line 126 of file MCContext.cpp.
isDwarfMD5UsageConsistent()
bool llvm::MCContext::isDwarfMD5UsageConsistent (unsigned CUID) const inline
Reports whether MD5 checksum usage is consistent (all-or-none).
Definition at line 762 of file MCContext.h.
References getMCDwarfLineTable(), and llvm::MCDwarfLineTable::isMD5UsageConsistent().
isELFGenericMergeableSection()
bool MCContext::isELFGenericMergeableSection (StringRef Name)
Definition at line 634 of file MCContext.cpp.
References isELFImplicitMergeableSectionNamePrefix().
Referenced by calcUniqueIDUpdateFlagsAndSize(), and recordELFMergeableSectionInfo().
isELFImplicitMergeableSectionNamePrefix()
bool MCContext::isELFImplicitMergeableSectionNamePrefix (StringRef Name)
Definition at line 629 of file MCContext.cpp.
Referenced by calcUniqueIDUpdateFlagsAndSize(), and isELFGenericMergeableSection().
isValidDwarfFileNumber()
bool MCContext::isValidDwarfFileNumber (unsigned FileNumber, unsigned CUID = 0)
isValidDwarfFileNumber - takes a dwarf file number and returns true if it currently is assigned and false otherwise.
Definition at line 983 of file MCContext.cpp.
References getDwarfVersion(), llvm::MCDwarfLineTable::getMCDwarfFiles(), and getMCDwarfLineTable().
lookupMacro()
const MCAsmMacro* llvm::MCContext::lookupMacro (StringRef Name) inline
Definition at line 853 of file MCContext.h.
References I.
lookupSymbol()
MCSymbol * MCContext::lookupSymbol (const Twine & Name) const
Get the symbol for Name, or null.
Definition at line 359 of file MCContext.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::lookup().
Referenced by llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::WasmException::endModule(), llvm::WebAssembly::getOrCreateFuncrefCallTableSymbol(), llvm::WebAssembly::getOrCreateFunctionTableSymbol(), and llvm::MCParserUtils::parseAssignmentExpression().
operator=()
MCContext& llvm::MCContext::operator= (const MCContext &) delete
recordELFMergeableSectionInfo()
void MCContext::recordELFMergeableSectionInfo (StringRef SectionName, unsigned Flags, unsigned UniqueID, unsigned EntrySize)
Definition at line 613 of file MCContext.cpp.
References GenericSectionID, isELFGenericMergeableSection(), llvm::AMDGPU::ElfNote::SectionName, and llvm::ELF::SHF_MERGE.
registerInlineAsmLabel()
void MCContext::registerInlineAsmLabel (MCSymbol * Sym)
registerInlineAsmLabel - Records that the name is a label referenced in inline assembly.
Definition at line 372 of file MCContext.cpp.
References llvm::MCSymbol::getName().
Referenced by EmitInlineAsmStr().
remapDebugPath()
void MCContext::remapDebugPath (SmallVectorImpl< char > & Path)
Remap one path in-place as per the debug prefix map.
Definition at line 890 of file MCContext.cpp.
References From, and llvm::sys::path::replace_path_prefix().
Referenced by RemapDebugPaths().
RemapDebugPaths()
void MCContext::RemapDebugPaths ()
Definition at line 896 of file MCContext.cpp.
References P, and remapDebugPath().
Referenced by llvm::MCObjectStreamer::finishImpl().
reportError()
void MCContext::reportError (SMLoc L, const Twine & Msg)
Definition at line 1055 of file MCContext.cpp.
References D, llvm::SourceMgr::DK_Error, llvm::SourceMgr::GetMessage(), and llvm::AMDGPU::SendMsg::Msg.
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), adjustFixupValue(), ARM64EmitUnwindInfo(), ARMEmitUnwindInfo(), llvm::MCStreamer::checkCVLocSection(), checkIs32(), checkIs64(), llvm::MCAssembler::computeFragmentSize(), llvm::MCStreamer::emitCFIStartProc(), llvm::MCStreamer::emitCVInlineSiteIdDirective(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::AsmPrinter::emitGlobalVariable(), llvm::MCObjectStreamer::emitInstruction(), llvm::MCStreamer::emitLabel(), llvm::MCELFStreamer::emitSymbolAttribute(), llvm::MCObjectStreamer::emitValueImpl(), llvm::MCStreamer::emitWinCFIAllocStack(), llvm::MCStreamer::emitWinCFIEndChained(), llvm::MCStreamer::emitWinCFIEndProc(), llvm::MCStreamer::emitWinCFIFuncletOrFuncEnd(), llvm::MCStreamer::emitWinCFIPushFrame(), llvm::MCStreamer::emitWinCFISaveReg(), llvm::MCStreamer::emitWinCFISaveXMM(), llvm::MCStreamer::emitWinCFISetFrame(), llvm::MCStreamer::emitWinCFIStartProc(), llvm::MCStreamer::emitWinEHHandler(), llvm::MCStreamer::emitWinEHHandlerData(), llvm::MCStreamer::EnsureValidWinFrameInfo(), extractBitsForFixup(), llvm::MCStreamer::finish(), llvm::MCAsmLayout::getBaseSymbol(), llvm::MipsMCCodeEmitter::getExprOpValue(), llvm::WebAssembly::getOrCreateFuncrefCallTableSymbol(), llvm::WebAssembly::getOrCreateFunctionTableSymbol(), isNonILP32reloc(), llvm::HexagonMCChecker::reportError(), llvm::HexagonShuffler::reportError(), reportOutOfRangeError(), reportWarning(), llvm::AVRTargetObjectFile::SelectSectionForGlobal(), and llvm::MCAssembler::writeSectionData().
reportWarning()
void MCContext::reportWarning (SMLoc L, const Twine & Msg)
Definition at line 1062 of file MCContext.cpp.
References D, llvm::SourceMgr::DK_Warning, llvm::SourceMgr::GetMessage(), llvm::AMDGPU::SendMsg::Msg, and reportError().
Referenced by llvm::MCELFStreamer::emitSymbolAttribute(), and llvm::HexagonMCChecker::reportWarning().
reset()
void MCContext::reset ()
reset - return object to right after construction state to prepare to process a new module
Definition at line 135 of file MCContext.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::clear(), llvm::SmallVectorImpl< T >::clear(), defaultDiagHandler(), DWARF2_FLAG_IS_STMT, and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset().
Referenced by ~MCContext().
setAllowTemporaryLabels()
void llvm::MCContext::setAllowTemporaryLabels (bool Value) inline
Definition at line 456 of file MCContext.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC().
setCompilationDir()
void llvm::MCContext::setCompilationDir (StringRef S) inline
Set the compilation directory for DW_AT_comp_dir.
Definition at line 697 of file MCContext.h.
References S.
setCurrentDwarfLoc()
void llvm::MCContext::setCurrentDwarfLoc (unsigned FileNum, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator) inline
Saves the information from the currently parsed dwarf .loc directive and sets DwarfLocSeen.
When the next instruction is assembled an entry in the line number table with this information and the address of the instruction will be created.
Definition at line 770 of file MCContext.h.
References llvm::MCDwarfLoc::setColumn(), llvm::MCDwarfLoc::setDiscriminator(), llvm::MCDwarfLoc::setFileNum(), llvm::MCDwarfLoc::setFlags(), llvm::MCDwarfLoc::setIsa(), and llvm::MCDwarfLoc::setLine().
Referenced by llvm::MCStreamer::emitDwarfLocDirective().
setDiagnosticHandler()
void llvm::MCContext::setDiagnosticHandler (DiagHandlerTy DiagHandler) inline
Definition at line 440 of file MCContext.h.
Referenced by llvm::MachineModuleInfoWrapperPass::doInitialization().
setDwarfCompileUnitID()
void llvm::MCContext::setDwarfCompileUnitID (unsigned CUIndex) inline
Definition at line 749 of file MCContext.h.
setDwarfDebugFlags()
void llvm::MCContext::setDwarfDebugFlags (StringRef S) inline
Definition at line 818 of file MCContext.h.
References S.
setDwarfDebugProducer()
void llvm::MCContext::setDwarfDebugProducer (StringRef S) inline
Definition at line 821 of file MCContext.h.
References S.
setDwarfFormat()
void llvm::MCContext::setDwarfFormat (dwarf::DwarfFormat f) inline
Definition at line 824 of file MCContext.h.
References f().
setDwarfVersion()
void llvm::MCContext::setDwarfVersion (uint16_t v) inline
Definition at line 827 of file MCContext.h.
setGenDwarfFileNumber()
void llvm::MCContext::setGenDwarfFileNumber (unsigned FileNumber) inline
Definition at line 792 of file MCContext.h.
setGenDwarfForAssembly()
void llvm::MCContext::setGenDwarfForAssembly (bool Value) inline
Definition at line 788 of file MCContext.h.
setGenDwarfRootFile()
void MCContext::setGenDwarfRootFile (StringRef FileName, StringRef Buffer)
Specifies information about the "root file" for assembler clients (e.g., llvm-mc).
Assumes compilation dir etc. have been set up.
Definition at line 931 of file MCContext.cpp.
References llvm::sys::path::append(), assert(), llvm::StringRef::consume_front(), llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::MD5::final(), llvm::StringRef::front(), getCompilationDir(), getDwarfVersion(), getMainFileName(), llvm::sys::path::is_separator(), llvm::sys::path::remove_filename(), setMCLineTableRootFile(), and llvm::MD5::update().
setMainFileName()
void llvm::MCContext::setMainFileName (StringRef S) inline
Set the main file name and override the default.
Definition at line 714 of file MCContext.h.
References S.
setMCLineTableRootFile()
void llvm::MCContext::setMCLineTableRootFile (unsigned CUID, StringRef CompilationDir, StringRef Filename, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source) inline
Specifies the "root" file and directory of the compilation unit.
These are "file 0" and "directory 0" in DWARF v5.
Definition at line 753 of file MCContext.h.
References getMCDwarfLineTable(), llvm::MCDwarfLineTable::setRootFile(), and llvm::Sched::Source.
Referenced by llvm::MCStreamer::emitDwarfFile0Directive(), and setGenDwarfRootFile().
setObjectFileInfo()
void llvm::MCContext::setObjectFileInfo (const MCObjectFileInfo * Mofi) inline
Definition at line 444 of file MCContext.h.
Referenced by llvm::MachineModuleInfo::MachineModuleInfo().
setSecureLog()
void llvm::MCContext::setSecureLog (std::unique_ptr< raw_fd_ostream > Value) inline
Definition at line 835 of file MCContext.h.
References move.
setSecureLogUsed()
void llvm::MCContext::setSecureLogUsed (bool Value) inline
Definition at line 840 of file MCContext.h.
setSymbolValue()
void MCContext::setSymbolValue (MCStreamer & Streamer, StringRef Sym, uint64_t Val)
Set value for a symbol.
Definition at line 365 of file MCContext.cpp.
References llvm::MCConstantExpr::create(), llvm::MCStreamer::emitAssignment(), and getOrCreateSymbol().
setUseNamesOnTempLabels()
void llvm::MCContext::setUseNamesOnTempLabels (bool Value) inline
Definition at line 457 of file MCContext.h.
undefineMacro()
void llvm::MCContext::undefineMacro (StringRef Name) inline
Definition at line 862 of file MCContext.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCContext.h
lib/MC/MCContext.cpp