LLVM: llvm::SSAUpdater Class Reference
llvm::SSAUpdater Class Reference
Helper class for SSA formation on a set of values defined in multiple blocks.
#include "llvm/Transforms/Utils/SSAUpdater.h"
Public Member Functions
SSAUpdater (SmallVectorImpl< PHINode * > *InsertedPHIs=nullptr)
If InsertedPHIs is specified, it will be filled in with all PHI Nodes created by rewriting.
SSAUpdater (const SSAUpdater &)=delete
SSAUpdater & operator= (const SSAUpdater &)=delete
~SSAUpdater ()
void Initialize (Type *Ty, StringRef Name)
Reset this object to get ready for a new set of SSA updates with type 'Ty'.
void AddAvailableValue (BasicBlock *BB, Value *V)
Indicate that a rewritten value is available in the specified block with the specified value.
bool HasValueForBlock (BasicBlock *BB) const
Return true if the SSAUpdater already has a value for the specified block.
Value * FindValueForBlock (BasicBlock *BB) const
Return the value for the specified block if the SSAUpdater has one, otherwise return nullptr.
Value * GetValueAtEndOfBlock (BasicBlock *BB)
Construct SSA form, materializing a value that is live at the end of the specified block.
Value * GetValueInMiddleOfBlock (BasicBlock *BB)
Construct SSA form, materializing a value that is live in the middle of the specified block.
void RewriteUse (Use &U)
Rewrite a use of the symbolic value.
void UpdateDebugValues (Instruction *I)
Rewrite debug value intrinsics to conform to a new SSA form.
void UpdateDebugValues (Instruction *I, SmallVectorImpl< DbgValueInst * > &DbgValues)
void RewriteUseAfterInsertions (Use &U)
Rewrite a use like RewriteUse but handling in-block definitions.
Friends
class SSAUpdaterTraits< SSAUpdater >
Detailed Description
Helper class for SSA formation on a set of values defined in multiple blocks.
This is used when code duplication or another unstructured transformation wants to rewrite a set of uses of one value with uses of a set of values.
Definition at line 39 of file SSAUpdater.h.
Constructor & Destructor Documentation
SSAUpdater() [1/2]
SSAUpdater::SSAUpdater (SmallVectorImpl< PHINode * > * InsertedPHIs = nullptr) explicit
If InsertedPHIs is specified, it will be filled in with all PHI Nodes created by rewriting.
Definition at line 46 of file SSAUpdater.cpp.
SSAUpdater() [2/2]
llvm::SSAUpdater::SSAUpdater (const SSAUpdater &) delete
~SSAUpdater()
SSAUpdater::~SSAUpdater ()
Definition at line 49 of file SSAUpdater.cpp.
Member Function Documentation
AddAvailableValue()
void SSAUpdater::AddAvailableValue (BasicBlock * BB, Value * V)
Indicate that a rewritten value is available in the specified block with the specified value.
Definition at line 70 of file SSAUpdater.cpp.
References assert(), BB, getAvailableVals(), and llvm::Value::getType().
Referenced by ConstructSSAForLoadSet(), llvm::formLCSSAForInstructions(), llvm::LoadAndStorePromoter::run(), and llvm::JumpThreadingPass::updateSSA().
FindValueForBlock()
Value * SSAUpdater::FindValueForBlock (BasicBlock * BB) const
Return the value for the specified block if the SSAUpdater has one, otherwise return nullptr.
Definition at line 66 of file SSAUpdater.cpp.
References BB, getAvailableVals(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
Referenced by llvm::formLCSSAForInstructions().
GetValueAtEndOfBlock()
Value * SSAUpdater::GetValueAtEndOfBlock (BasicBlock * BB)
Construct SSA form, materializing a value that is live at the end of the specified block.
Definition at line 93 of file SSAUpdater.cpp.
References BB.
Referenced by GetValueInMiddleOfBlock(), RewriteUse(), and RewriteUseAfterInsertions().
GetValueInMiddleOfBlock()
Value * SSAUpdater::GetValueInMiddleOfBlock (BasicBlock * BB)
Construct SSA form, materializing a value that is live in the middle of the specified block.
GetValueInMiddleOfBlock is the same as GetValueAtEndOfBlock except in one important case: if there is a definition of the rewritten value after the 'use' in BB. Consider code like this:
   X1 = ...
SomeBB:
   use(X)
   X2 = ...
   br Cond, SomeBB, OutBB
In this case, there are two values (X1 and X2) added to the AvailableVals set by the client of the rewriter, and those values are both live out of their respective blocks. However, the use of X happens in the middle of a block. Because of this, we need to insert a new PHI node in SomeBB to merge the appropriate values, and this value isn't live out of the block.
Definition at line 98 of file SSAUpdater.cpp.
References llvm::PHINode::addIncoming(), BB, llvm::PHINode::Create(), llvm::dbgs(), DL, llvm::numbers::e, llvm::Instruction::eraseFromParent(), llvm::UndefValue::get(), GetValueAtEndOfBlock(), HasValueForBlock(), i, I, IsEquivalentPHI(), LLVM_DEBUG, llvm::predecessors(), llvm::Instruction::setDebugLoc(), and llvm::simplifyInstruction().
Referenced by ConstructSSAForLoadSet(), RewriteUse(), and llvm::LoadAndStorePromoter::run().
HasValueForBlock()
bool SSAUpdater::HasValueForBlock (BasicBlock * BB) const
Return true if the SSAUpdater already has a value for the specified block.
Definition at line 62 of file SSAUpdater.cpp.
References BB, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), and getAvailableVals().
Referenced by ConstructSSAForLoadSet(), llvm::formLCSSAForInstructions(), and GetValueInMiddleOfBlock().
Initialize()
void SSAUpdater::Initialize (Type * Ty, StringRef Name)
Reset this object to get ready for a new set of SSA updates with type 'Ty'.
PHI nodes get a name based on 'Name'.
Definition at line 53 of file SSAUpdater.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), and getAvailableVals().
Referenced by ConstructSSAForLoadSet(), llvm::formLCSSAForInstructions(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), and llvm::JumpThreadingPass::updateSSA().
operator=()
SSAUpdater& llvm::SSAUpdater::operator= (const SSAUpdater &) delete
RewriteUse()
void SSAUpdater::RewriteUse (Use & U)
Rewrite a use of the symbolic value.
This handles PHI nodes, which use their value in the corresponding predecessor. Note that this will not work if the use is supposed to be rewritten to a value defined in the same block as the use, but above it. Any 'AddAvailableValue's added for the use's block will be considered to be below it.
Definition at line 187 of file SSAUpdater.cpp.
References llvm::Use::getUser(), GetValueAtEndOfBlock(), GetValueInMiddleOfBlock(), and llvm::Use::set().
Referenced by llvm::formLCSSAForInstructions(), and llvm::JumpThreadingPass::updateSSA().
RewriteUseAfterInsertions()
void SSAUpdater::RewriteUseAfterInsertions (Use & U)
Rewrite a use like RewriteUse but handling in-block definitions.
This version of the method can rewrite uses in the same block as a definition, because it assumes that all uses of a value are below any inserted values.
Definition at line 226 of file SSAUpdater.cpp.
References llvm::Use::getUser(), GetValueAtEndOfBlock(), and llvm::Use::set().
UpdateDebugValues() [1/2]
void SSAUpdater::UpdateDebugValues (Instruction * I)
Rewrite debug value intrinsics to conform to a new SSA form.
This will scout out all the debug value instrinsics associated with the instruction. Anything outside of its block will have its value set to the new SSA value if available, and undef if not.
Definition at line 199 of file SSAUpdater.cpp.
References llvm::findDbgValues(), and I.
Referenced by llvm::JumpThreadingPass::updateSSA().
UpdateDebugValues() [2/2]
void SSAUpdater::UpdateDebugValues (Instruction * I, SmallVectorImpl< DbgValueInst * > & DbgValues)
Definition at line 209 of file SSAUpdater.cpp.
References I.
Friends And Related Function Documentation
SSAUpdaterTraits< SSAUpdater >
friend class SSAUpdaterTraits< SSAUpdater > friend
Definition at line 40 of file SSAUpdater.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/SSAUpdater.h
lib/Transforms/Utils/SSAUpdater.cpp