LLVM: llvm::objcarc::ObjCARCAAResult Class Reference
llvm::objcarc::ObjCARCAAResult Class Reference
This is a simple alias analysis implementation that uses knowledge of ARC constructs to answer queries.
#include "llvm/Analysis/ObjCARCAliasAnalysis.h"
Public Member Functions
ObjCARCAAResult (const DataLayout &DL)
ObjCARCAAResult (ObjCARCAAResult &&Arg)
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
Handle invalidation events from the new pass manager.
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI, const Instruction *CtxI)
ModRefInfo getModRefInfoMask (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool IgnoreLocals)
MemoryEffects getMemoryEffects (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
MemoryEffects getMemoryEffects (const CallBase *Call, AAQueryInfo &AAQI)
MemoryEffects getMemoryEffects (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Public Member Functions inherited from llvm::AAResultBase
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI, const Instruction *I)
ModRefInfo getModRefInfoMask (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool IgnoreLocals)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
MemoryEffects getMemoryEffects (const CallBase *Call, AAQueryInfo &AAQI)
MemoryEffects getMemoryEffects (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
Detailed Description
This is a simple alias analysis implementation that uses knowledge of ARC constructs to answer queries.
TODO: This class could be generalized to know about other ObjC-specific tricks. Such as knowing that ivars in the non-fragile ABI are non-aliasing even though their offsets are dynamic.
Definition at line 37 of file ObjCARCAliasAnalysis.h.
Constructor & Destructor Documentation
ObjCARCAAResult() [1/2]
llvm::objcarc::ObjCARCAAResult::ObjCARCAAResult (const DataLayout & DL) inline explicit
Definition at line 41 of file ObjCARCAliasAnalysis.h.
References DL.
ObjCARCAAResult() [2/2]
llvm::objcarc::ObjCARCAAResult::ObjCARCAAResult (ObjCARCAAResult && Arg) inline
Definition at line 42 of file ObjCARCAliasAnalysis.h.
References DL.
Member Function Documentation
alias()
AliasResult ObjCARCAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI, const Instruction * CtxI)
Definition at line 37 of file ObjCARCAliasAnalysis.cpp.
References llvm::MemoryLocation::AATags, llvm::AAResultBase::alias(), llvm::objcarc::EnableARCOpts, llvm::MemoryLocation::getBeforeOrAfter(), llvm::objcarc::GetRCIdentityRoot(), llvm::objcarc::GetUnderlyingObjCPtr(), llvm::AliasResult::MayAlias, llvm::AliasResult::NoAlias, llvm::MemoryLocation::Ptr, and llvm::MemoryLocation::Size.
getMemoryEffects() [1/3]
MemoryEffects llvm::AAResultBase::getMemoryEffects inline
Definition at line 818 of file AliasAnalysis.h.
getMemoryEffects() [2/3]
MemoryEffects llvm::AAResultBase::getMemoryEffects inline
Definition at line 822 of file AliasAnalysis.h.
getMemoryEffects() [3/3]
MemoryEffects ObjCARCAAResult::getMemoryEffects (const Function * F)
Definition at line 97 of file ObjCARCAliasAnalysis.cpp.
References llvm::objcarc::EnableARCOpts, F, llvm::objcarc::GetFunctionClass(), llvm::AAResultBase::getMemoryEffects(), llvm::MemoryEffects::none(), and llvm::objcarc::NoopCast.
getModRefInfo() [1/3]
ModRefInfo llvm::AAResultBase::getModRefInfo inline
Definition at line 826 of file AliasAnalysis.h.
getModRefInfo() [2/3]
ModRefInfo ObjCARCAAResult::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI)
Definition at line 111 of file ObjCARCAliasAnalysis.cpp.
References llvm::objcarc::Autorelease, llvm::objcarc::AutoreleasepoolPush, llvm::objcarc::AutoreleaseRV, llvm::objcarc::EnableARCOpts, llvm::objcarc::FusedRetainAutorelease, llvm::objcarc::FusedRetainAutoreleaseRV, llvm::objcarc::GetBasicARCInstKind(), llvm::AAResultBase::getModRefInfo(), llvm::NoModRef, llvm::objcarc::NoopCast, llvm::objcarc::Retain, and llvm::objcarc::RetainRV.
getModRefInfo() [3/3]
ModRefInfo llvm::AAResultBase::getModRefInfo inline
Definition at line 831 of file AliasAnalysis.h.
getModRefInfoMask()
ModRefInfo ObjCARCAAResult::getModRefInfoMask (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool IgnoreLocals)
Definition at line 72 of file ObjCARCAliasAnalysis.cpp.
References llvm::MemoryLocation::AATags, llvm::objcarc::EnableARCOpts, llvm::MemoryLocation::getBeforeOrAfter(), llvm::AAResultBase::getModRefInfoMask(), llvm::objcarc::GetRCIdentityRoot(), llvm::objcarc::GetUnderlyingObjCPtr(), llvm::isNoModRef(), llvm::ModRef, llvm::NoModRef, llvm::MemoryLocation::Ptr, S, and llvm::MemoryLocation::Size.
invalidate()
bool llvm::objcarc::ObjCARCAAResult::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Handle invalidation events from the new pass manager.
By definition, this result is stateless and so remains valid.
Definition at line 48 of file ObjCARCAliasAnalysis.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/ObjCARCAliasAnalysis.h
lib/Analysis/ObjCARCAliasAnalysis.cpp