LLVM: llvm::orc::SymbolStringPtr Class Reference
llvm::orc::SymbolStringPtr Class Reference
Pointer to a pooled string representing a symbol name.
#include "llvm/ExecutionEngine/Orc/SymbolStringPool.h"
Public Member Functions
SymbolStringPtr ()=default
SymbolStringPtr (std::nullptr_t)
SymbolStringPtr (const SymbolStringPtr &Other)
SymbolStringPtr (NonOwningSymbolStringPtr Other)
SymbolStringPtr & operator= (const SymbolStringPtr &Other)
SymbolStringPtr (SymbolStringPtr &&Other)
SymbolStringPtr & operator= (SymbolStringPtr &&Other)
~SymbolStringPtr ()
Public Member Functions inherited from llvm::orc::SymbolStringPtrBase
SymbolStringPtrBase ()=default
SymbolStringPtrBase (std::nullptr_t)
operator bool () const
StringRef operator* () const
bool poolEntryIsAlive () const
Friends
class OrcV2CAPIHelper
class SymbolStringPool
struct DenseMapInfo< SymbolStringPtr >
Additional Inherited Members
Protected Types inherited from llvm::orc::SymbolStringPtrBase
using PoolEntry = SymbolStringPool::PoolMapEntry
using PoolEntryPtr = PoolEntry *
Protected Member Functions inherited from llvm::orc::SymbolStringPtrBase
SymbolStringPtrBase (PoolEntryPtr S)
size_t getRefCount () const
Static Protected Member Functions inherited from llvm::orc::SymbolStringPtrBase
static bool isRealPoolEntry (PoolEntryPtr P)
Protected Attributes inherited from llvm::orc::SymbolStringPtrBase
PoolEntryPtr S = nullptr
Static Protected Attributes inherited from llvm::orc::SymbolStringPtrBase
constexpr static uintptr_t EmptyBitPattern
constexpr static uintptr_t TombstoneBitPattern
constexpr static uintptr_t InvalidPtrMask
Detailed Description
Pointer to a pooled string representing a symbol name.
Definition at line 136 of file SymbolStringPool.h.
Constructor & Destructor Documentation
SymbolStringPtr() [1/5]
llvm::orc::SymbolStringPtr::SymbolStringPtr () default
SymbolStringPtr() [2/5]
llvm::orc::SymbolStringPtr::SymbolStringPtr (std::nullptr_t) inline
Definition at line 143 of file SymbolStringPool.h.
SymbolStringPtr() [3/5]
llvm::orc::SymbolStringPtr::SymbolStringPtr (const SymbolStringPtr & Other) inline
Definition at line 144 of file SymbolStringPool.h.
SymbolStringPtr() [4/5]
llvm::orc::SymbolStringPtr::SymbolStringPtr (NonOwningSymbolStringPtr Other) inline explicit
Definition at line 228 of file SymbolStringPool.h.
References assert(), llvm::StringMapEntryStorage< ValueTy >::getValue(), llvm::orc::SymbolStringPtrBase::isRealPoolEntry(), Other, llvm::orc::SymbolStringPtrBase::poolEntryIsAlive(), and llvm::orc::SymbolStringPtrBase::S.
SymbolStringPtr() [5/5]
llvm::orc::SymbolStringPtr::SymbolStringPtr (SymbolStringPtr && Other) inline
Definition at line 157 of file SymbolStringPool.h.
References Other, llvm::orc::SymbolStringPtrBase::S, and std::swap().
~SymbolStringPtr()
llvm::orc::SymbolStringPtr::~SymbolStringPtr () inline
Definition at line 166 of file SymbolStringPool.h.
Member Function Documentation
operator=() [1/2]
SymbolStringPtr& llvm::orc::SymbolStringPtr::operator= (const SymbolStringPtr & Other) inline
Definition at line 150 of file SymbolStringPool.h.
References Other, and llvm::orc::SymbolStringPtrBase::S.
operator=() [2/2]
SymbolStringPtr& llvm::orc::SymbolStringPtr::operator= (SymbolStringPtr && Other) inline
Definition at line 159 of file SymbolStringPool.h.
References Other, llvm::orc::SymbolStringPtrBase::S, and std::swap().
Friends And Related Function Documentation
DenseMapInfo< SymbolStringPtr >
friend struct DenseMapInfo< SymbolStringPtr > friend
Definition at line 139 of file SymbolStringPool.h.
OrcV2CAPIHelper
friend class OrcV2CAPIHelper friend
Definition at line 137 of file SymbolStringPool.h.
SymbolStringPool
friend class SymbolStringPool friend
Definition at line 138 of file SymbolStringPool.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/SymbolStringPool.h