LLVM: llvm::memtag::StackInfoBuilder Class Reference
llvm::memtag::StackInfoBuilder Class Reference
#include "llvm/Transforms/Utils/MemoryTaggingSupport.h"
Public Member Functions
StackInfoBuilder (const StackSafetyGlobalInfo *SSI)
void visit (Instruction &Inst)
bool isInterestingAlloca (const AllocaInst &AI)
StackInfo & get ()
Detailed Description
Definition at line 64 of file MemoryTaggingSupport.h.
Constructor & Destructor Documentation
StackInfoBuilder()
llvm::memtag::StackInfoBuilder::StackInfoBuilder (const StackSafetyGlobalInfo * SSI) inline
Definition at line 66 of file MemoryTaggingSupport.h.
Member Function Documentation
get()
StackInfo& llvm::memtag::StackInfoBuilder::get () inline
Definition at line 70 of file MemoryTaggingSupport.h.
isInterestingAlloca()
bool llvm::memtag::StackInfoBuilder::isInterestingAlloca (const AllocaInst & AI)
Definition at line 157 of file MemoryTaggingSupport.cpp.
References llvm::memtag::getAllocaSizeInBytes(), llvm::AllocaInst::getAllocatedType(), llvm::isAllocaPromotable(), llvm::StackSafetyGlobalInfo::isSafe(), llvm::Type::isSized(), llvm::AllocaInst::isStaticAlloca(), llvm::AllocaInst::isSwiftError(), and llvm::AllocaInst::isUsedWithInAlloca().
Referenced by visit().
visit()
void llvm::memtag::StackInfoBuilder::visit (Instruction & Inst)
Definition at line 112 of file MemoryTaggingSupport.cpp.
References llvm::memtag::StackInfo::AllocasToInstrument, llvm::memtag::StackInfo::CallsReturnTwice, llvm::memtag::AllocaInfo::DbgVariableIntrinsics, llvm::findAllocaForValue(), llvm::memtag::getUntagLocationIfFunctionExit(), isInterestingAlloca(), llvm::memtag::StackInfo::RetVec, and llvm::memtag::StackInfo::UnrecognizedLifetimes.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/MemoryTaggingSupport.h
lib/Transforms/Utils/MemoryTaggingSupport.cpp