LLVM: llvm::Instruction Class Reference
llvm::Instruction Class Reference
#include "llvm/IR/Instruction.h"
Public Types
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
SymbolTableList< Instruction >::iterator insertInto (BasicBlock *ParentBB, SymbolTableList< Instruction >::iterator It)
Inserts an unlinked instruction into ParentBB at position It and returns the iterator of the inserted instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
Instruction * getInsertionPointAfterDef ()
Get the first insertion point at which the result of this instruction is defined.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * >> &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * >> &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
AAMDNodes getAAMetadata () const
Returns the AA metadata for this instruction.
void setAAMetadata (const AAMDNodes &N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const LLVM_READONLY
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const LLVM_READONLY
Determine whether the no signed wrap flag is set.
bool hasPoisonGeneratingFlags () const LLVM_READONLY
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
bool hasPoisonGeneratingMetadata () const LLVM_READONLY
Return true if this instruction has poison-generating metadata.
void dropPoisonGeneratingMetadata ()
Drops metadata that may generate poison.
bool hasPoisonGeneratingFlagsOrMetadata () const
Return true if this instruction has poison-generating flags or metadata.
void dropPoisonGeneratingFlagsAndMetadata ()
Drops flags and metadata that may generate poison.
void dropUndefImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs={})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
bool isExact () const LLVM_READONLY
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const LLVM_READONLY
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const LLVM_READONLY
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const LLVM_READONLY
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const LLVM_READONLY
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const LLVM_READONLY
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const LLVM_READONLY
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const LLVM_READONLY
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const LLVM_READONLY
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const LLVM_READONLY
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
void updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
void dropLocation ()
Drop the instruction's debug location.
void mergeDIAssignID (ArrayRef< const Instruction * > SourceInstructions)
Merge the DIAssignID metadata from this instruction and those attached to instructions in SourceInstructions.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const LLVM_READONLY
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const LLVM_READONLY
Return true if this instruction may modify memory.
bool mayReadFromMemory () const LLVM_READONLY
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const LLVM_READONLY
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const LLVM_READONLY
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const LLVM_READONLY
Return true if this atomic instruction stores to memory.
bool isVolatile () const LLVM_READONLY
Return true if this instruction has a volatile memory access.
bool mayThrow () const LLVM_READONLY
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const LLVM_READONLY
Return true if the instruction may have side effects.
bool isSafeToRemove () const LLVM_READONLY
Return true if the instruction can be removed if the result is unused.
bool willReturn () const LLVM_READONLY
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const LLVM_READONLY
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
bool isLaunderOrStripInvariantGroup () const LLVM_READONLY
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
bool isDebugOrPseudoInst () const LLVM_READONLY
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
const Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false)
const Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false)
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const LLVM_READONLY
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const LLVM_READONLY
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const LLVM_READONLY
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const LLVM_READONLY
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const LLVM_READONLY
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const LLVM_READONLY
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
Instruction * getPrevNode ()
const Instruction * getPrevNode () const
Get the previous node, or nullptr for the list head.
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
const Instruction * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Types
using OpaqueField = Bitfield::Element< uint16_t, 0, 15 >
template<unsigned Offset>
using AlignmentBitfieldElementT = typename Bitfield::Element< unsigned, Offset, 6, Value::MaxAlignmentExponent >
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element< bool, Offset, 1 >
template<unsigned Offset>
using AtomicOrderingBitfieldElementT = typename Bitfield::Element< AtomicOrdering, Offset, 3, AtomicOrdering::LAST >
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< Instruction, Options... >::type, true, true >
Protected Member Functions
~Instruction ()
template<typename BitfieldElement >
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement >
void setSubclassData (typename BitfieldElement::Type Value)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * >> &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >
ilist_node_impl ()=default
Friends
class SymbolTableListTraits< Instruction >
class BasicBlock
Various leaf nodes.
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Definition at line 41 of file Instruction.h.
Member Typedef Documentation
AlignmentBitfieldElementT
template<unsigned Offset> using llvm::Instruction::AlignmentBitfieldElementT = typename Bitfield::Element<unsigned, Offset, 6, Value::MaxAlignmentExponent> protected
Definition at line 63 of file Instruction.h.
AtomicOrderingBitfieldElementT
template<unsigned Offset> using llvm::Instruction::AtomicOrderingBitfieldElementT = typename Bitfield::Element<AtomicOrdering, Offset, 3, AtomicOrdering::LAST> protected
Definition at line 71 of file Instruction.h.
BoolBitfieldElementT
template<unsigned Offset> using llvm::Instruction::BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1> protected
Definition at line 66 of file Instruction.h.
OpaqueField
using llvm::Instruction::OpaqueField = Bitfield::Element<uint16_t, 0, 15> protected
Definition at line 53 of file Instruction.h.
Member Enumeration Documentation
BinaryOps
enum llvm::Instruction::BinaryOps
Definition at line 809 of file Instruction.h.
CastOps
enum llvm::Instruction::CastOps
Definition at line 823 of file Instruction.h.
FuncletPadOps
enum llvm::Instruction::FuncletPadOps
Definition at line 830 of file Instruction.h.
MemoryOps
enum llvm::Instruction::MemoryOps
Definition at line 816 of file Instruction.h.
OperationEquivalenceFlags
enum llvm::Instruction::OperationEquivalenceFlags
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
Enumerator
CompareIgnoringAlignment
Check for equivalence ignoring load/store alignment.
CompareUsingScalarTypes
Check for equivalence treating a type and a vector of that type as equivalent.
Definition at line 749 of file Instruction.h.
OtherOps
enum llvm::Instruction::OtherOps
Definition at line 837 of file Instruction.h.
TermOps
enum llvm::Instruction::TermOps
Definition at line 795 of file Instruction.h.
UnaryOps
enum llvm::Instruction::UnaryOps
Definition at line 802 of file Instruction.h.
Constructor & Destructor Documentation
~Instruction()
Instruction::~Instruction () protected
Definition at line 45 of file Instruction.cpp.
References assert(), llvm::UndefValue::get(), llvm::Value::getType(), llvm::ValueAsMetadata::handleRAUW(), llvm::Value::isUsedByMetadata(), and setMetadata().
Instruction() [1/3]
llvm::Instruction::Instruction (const Instruction &) delete
Instruction() [2/3]
Instruction::Instruction (Type * Ty, unsigned iType, Use * Ops, unsigned NumOps, Instruction * InsertBefore = nullptr) protected
Definition at line 24 of file Instruction.cpp.
References assert(), BB, llvm::ilist_node_impl< OptionsT >::getIterator(), getParent(), and insertInto().
Instruction() [3/3]
Instruction::Instruction (Type * Ty, unsigned iType, Use * Ops, unsigned NumOps, BasicBlock * InsertAtEnd) protected
Definition at line 36 of file Instruction.cpp.
References assert(), llvm::BasicBlock::end(), and insertInto().
Member Function Documentation
addAnnotationMetadata()
void Instruction::addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
If this instruction already has !annotation metadata, append Annotation to the existing node.
Definition at line 1478 of file Metadata.cpp.
References llvm::MDBuilder::createString(), llvm::MDTuple::get(), llvm::Value::getContext(), getMetadata(), N, and setMetadata().
andIRFlags()
void Instruction::andIRFlags (const Value * V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
Definition at line 372 of file Instruction.cpp.
References copyFastMathFlags(), FP, getFastMathFlags(), hasNoSignedWrap(), hasNoUnsignedWrap(), isExact(), llvm::X86II::OB, setHasNoSignedWrap(), setHasNoUnsignedWrap(), and setIsExact().
Referenced by llvm::InstCombinerImpl::foldPHIArgBinOpIntoPHI(), llvm::InstCombinerImpl::foldSelectOpOp(), foldShuffleOfUnaryOps(), NegateValue(), sinkLastInstruction(), and llvm::InstCombinerImpl::visitCallInst().
applyMergedLocation()
void Instruction::applyMergedLocation (const DILocation * LocA, const DILocation * LocB)
Merge 2 debug locations and apply it to the Instruction.
If the instruction is a CallIns, we need to traverse the inline chain to find the common scope. This is not efficient for N-way merging as each time you merge 2 iterations, you need to rebuild the hashmap to find the common scope. However, we still choose this API because: 1) Simplicity: it takes 2 locations instead of a list of locations. 2) In worst case, it increases the complexity from O(N*I) to O(2*N*I), where N is # of Instructions to merge, and I is the maximum level of inline stack. So it is still linear. 3) Merging of call instructions should be extremely rare in real applications, thus the N-way merging should be in code path. The DebugLoc attached to this instruction will be overwritten by the merged DebugLoc.
Definition at line 896 of file DebugInfo.cpp.
References llvm::DILocation::getMergedLocation().
Referenced by llvm::InstCombinerImpl::PHIArgMergedDebugLoc(), sinkLastInstruction(), and updateForIncomingValueLocation().
classof()
static bool llvm::Instruction::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 788 of file Instruction.h.
clone()
Instruction * Instruction::clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
The instruction has no parent
The instruction has no name
Definition at line 903 of file Instruction.cpp.
References getOpcode(), llvm_unreachable, and llvm::Value::SubclassOptionalData.
Referenced by buildPartialInvariantUnswitchConditionalBranch(), CloneInstructionsIntoPredecessorBlockAndUpdateSSAUses(), llvm::ehAwareSplitEdge(), findOrCreatePHIInBlock(), llvm::FoldReturnIntoUncondBranch(), MergeCompatibleInvokesImpl(), rematerializeChain(), replaceGEPIdxWithZero(), llvm::InnerLoopVectorizer::scalarizeInstruction(), SplitLandingPadPredecessorsImpl(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), and llvm::versionCallSite().
comesBefore()
bool Instruction::comesBefore (const Instruction * Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
In this worst case, this takes linear time in the number of instructions in the block. The results are cached, so in common cases when the block remains unmodified, it takes constant time.
Definition at line 122 of file Instruction.cpp.
References assert(), llvm::BasicBlock::isInstrOrderValid(), Other, and llvm::BasicBlock::renumberInstructions().
Referenced by llvm::GenericSSAContext< Function >::comesBefore(), domTreeLevelBefore(), foldConsecutiveLoads(), llvm::InstructionPrecedenceTracking::isPreceededBySpecialInstruction(), llvm::isValidAssumeForContext(), and llvm::BasicBlock::validateInstrOrdering().
copyFastMathFlags() [1/2]
void Instruction::copyFastMathFlags (const Instruction * I)
Copy I's fast-math flags.
Definition at line 344 of file Instruction.cpp.
References copyFastMathFlags(), and I.
copyFastMathFlags() [2/2]
void Instruction::copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
See LangRef.html for the meaning of these flags.
Definition at line 294 of file Instruction.cpp.
References assert().
Referenced by andIRFlags(), copyFastMathFlags(), copyIRFlags(), llvm::VPWidenCallRecipe::execute(), llvm::GCNTTIImpl::instCombineIntrinsic(), modifyIntrinsicCall(), replaceWithTLIFunction(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitFPTrunc().
copyIRFlags()
void Instruction::copyIRFlags (const Value * V, bool IncludeWrapFlags = true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
Definition at line 348 of file Instruction.cpp.
References copyFastMathFlags(), FP, llvm::X86II::OB, setHasNoSignedWrap(), setHasNoUnsignedWrap(), and setIsExact().
Referenced by llvm::CmpInst::CmpInst(), llvm::UnaryOperator::CreateWithCopiedFlags(), llvm::BinaryOperator::CreateWithCopiedFlags(), llvm::InstCombinerImpl::foldPHIArgBinOpIntoPHI(), llvm::InstCombinerImpl::foldSelectIntoOp(), llvm::InstCombinerImpl::foldSelectOpOp(), foldSelectShuffleWith1Binop(), foldShuffleOfUnaryOps(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::foldVectorBinop(), and llvm::InstCombinerImpl::visitCallInst().
copyMetadata()
void Instruction::copyMetadata (const Instruction & SrcInst, ArrayRef< unsigned > WL = ArrayRef<unsigned>())
Copy metadata from SrcInst to this instruction.
WL, if not empty, specifies the list of meta data that needs to be copied. If WL is empty, all meta data will be copied.
Definition at line 882 of file Instruction.cpp.
References getAllMetadataOtherThanDebugLoc(), getDebugLoc(), hasMetadata(), M, setDebugLoc(), setMetadata(), and llvm::ARMISD::WLS.
Referenced by llvm::ConstantFoldTerminator(), llvm::SelectInst::Create(), llvm::createCallMatchingInvoke(), llvm::IRBuilderBase::CreateCondBr(), doPromotion(), instCombineSVELD1(), instCombineSVEST1(), modifyIntrinsicCall(), simplifyAMDGCNMemoryIntrinsicDemanded(), and llvm::InstCombinerImpl::visitSub().
dropLocation()
void Instruction::dropLocation ()
Drop the instruction's debug location.
This does not guarantee removal of the !dbg source location attachment, as it must set a line 0 location with scope information attached on call instructions. To guarantee removal of the !dbg attachment, use the setDebugLoc() API. Note: it is undefined behavior to call this on an instruction not currently inserted into a function.
Definition at line 932 of file DebugInfo.cpp.
References DL, llvm::MDNode::get(), getDebugLoc(), getFunction(), llvm::Function::getSubprogram(), and llvm::IntrinsicInst::mayLowerToFunctionCall().
dropPoisonGeneratingFlags()
void Instruction::dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
Definition at line 185 of file Instruction.cpp.
References llvm::MCID::Add, assert(), getOpcode(), hasPoisonGeneratingFlags(), Mul, setHasNoInfs(), setHasNoNaNs(), and setHasNoUnsignedWrap().
Referenced by clearAssumptionsOfUsers(), dropPoisonGeneratingFlagsAndMetadata(), foldSelectShuffleWith1Binop(), and llvm::InnerLoopVectorizer::scalarizeInstruction().
dropPoisonGeneratingFlagsAndMetadata()
void llvm::Instruction::dropPoisonGeneratingFlagsAndMetadata () inline
Drops flags and metadata that may generate poison.
Definition at line 398 of file Instruction.h.
References dropPoisonGeneratingFlags(), and dropPoisonGeneratingMetadata().
dropPoisonGeneratingMetadata()
void Instruction::dropPoisonGeneratingMetadata ()
Drops metadata that may generate poison.
Definition at line 220 of file Instruction.cpp.
References llvm::Value::eraseMetadata().
Referenced by dropPoisonGeneratingFlagsAndMetadata().
dropUndefImplyingAttrsAndUnknownMetadata()
void Instruction::dropUndefImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs = {})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
For calls, it also drops parameter and return attributes that can cause undefined behaviour. Both of these should be done by passes which move instructions in IR.
Definition at line 226 of file Instruction.cpp.
References llvm::AArch64CC::AL, dropUnknownNonDebugMetadata(), and llvm::AttributeFuncs::getUBImplyingAttributes().
Referenced by CloneInstructionsIntoPredecessorBlockAndUpdateSSAUses().
dropUnknownNonDebugMetadata() [1/4]
void llvm::Instruction::dropUnknownNonDebugMetadata () inline
Definition at line 326 of file Instruction.h.
Referenced by dropUndefImplyingAttrsAndUnknownMetadata(), and dropUnknownNonDebugMetadata().
dropUnknownNonDebugMetadata() [2/4]
void Instruction::dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
Passes are required to drop metadata they don't understand. This is a convenience method for passes to do so. dropUndefImplyingAttrsAndUnknownMetadata should be used instead of this API if the Instruction being modified is a call.
Definition at line 1401 of file Metadata.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::Value::clearMetadata(), llvm::SmallSet< T, N, C >::count(), llvm::ArrayRef< T >::end(), llvm::Value::getContext(), llvm::Value::hasMetadata(), I, Info, llvm::SmallSet< T, N, C >::insert(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValueMetadata.
Referenced by llvm::combineMetadata().
dropUnknownNonDebugMetadata() [3/4]
void llvm::Instruction::dropUnknownNonDebugMetadata (unsigned ID1) inline
Definition at line 329 of file Instruction.h.
References llvm::ArrayRef(), and dropUnknownNonDebugMetadata().
dropUnknownNonDebugMetadata() [4/4]
void llvm::Instruction::dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2) inline
Definition at line 332 of file Instruction.h.
References dropUnknownNonDebugMetadata().
eraseFromParent()
iplist< Instruction >::iterator Instruction::eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Returns
an iterator pointing to the element after the erased one
Definition at line 82 of file Instruction.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >::getIterator(), and getParent().
Referenced by llvm::LanaiInstrInfo::analyzeBranch(), buildClonedLoopBlocks(), BuildSubAggregate(), llvm::changeToCall(), llvm::CloneAndPruneIntoFromInst(), CloneLoopBlocks(), cloneLoopBlocks(), ConnectEpilog(), ConnectProlog(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createCopyinClauseBlocks(), createMemMoveLoop(), createMemSetLoop(), llvm::OpenMPIRBuilder::createParallel(), llvm::OpenMPIRBuilder::createReductions(), llvm::OpenMPIRBuilder::createTask(), createTblForTrunc(), createTblShuffleForZExt(), llvm::deleteDeadLoop(), despeculateCountZeros(), DoFlattenLoopPair(), doPromotion(), dropTypeTests(), EliminateDuplicatePHINodesNaiveImpl(), llvm::SITargetLowering::emitExpandAtomicRMW(), llvm::objcarc::BundledRetainClaimRVs::eraseInst(), llvm::objcarc::EraseInstruction(), EraseTerminatorAndDCECond(), llvm::expandAtomicRMWToCmpXchg(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), expandFPToI(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), expandUDivOrURem(), findPHIToPartitionLoops(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), getStrlenWithNull(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), injectPendingInvariantConditions(), llvm::InlineFunction(), inlineRetainOrClaimRVCalls(), insertBoundsCheck(), insertSpills(), insertUniqueBackedgeBlock(), llvm::lowerAtomicCmpXchgInst(), llvm::lowerAtomicRMWInst(), llvm::LowerDbgDeclare(), lowerExpectIntrinsic(), LowerFenceInst(), lowerIntrinsic(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeCleanupPad(), mergeConditionalStoreToAddress(), mergeInlinedArrayAllocas(), llvm::InstDeleterIRStrategy::mutate(), narrowSDivOrSRem(), narrowUDivOrURem(), optimizeDivRem(), OptimizeEmptyGlobalCXXDtors(), OptimizeExtractBits(), OptimizeGlobalAddressOfAllocation(), processAbsIntrinsic(), processAnd(), processAShr(), llvm::JumpThreadingPass::processBlock(), llvm::JumpThreadingPass::processBranchOnXOR(), processMinMaxIntrinsic(), processOverflowIntrinsic(), processSDiv(), processSExt(), processSRem(), promoteSingleBlockAlloca(), llvm::OutlinableRegion::reattachCandidate(), ReduceLoopStrength(), llvm::removeAllNonTerminatorAndEHPadInstructions(), llvm::LanaiInstrInfo::removeBranch(), llvm::PHINode::removeIncomingValue(), removeIntrinsicUsers(), llvm::SCCPSolver::removeNonFeasibleEdges(), RemovePreallocated(), removeUndefIntroducingPredecessor(), llvm::removeUnwindEdge(), llvm::AMDGPULibCalls::replaceCall(), replaceCalledFunction(), replaceConditionalBranchesOnConstant(), replaceFrameSizeAndAlignment(), replaceOneDbgValueForAlloca(), replaceOperation(), replacePrepare(), llvm::replaceSignedInst(), replaceSubOverflowUses(), llvm::rewriteLoopExitValues(), rewritePHIs(), rewriteSingleStoreAlloca(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), simplifyOneLoop(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), simplifySuspendPoint(), sinkAndCmp0Expression(), SinkCast(), speculatePHINodeLoads(), splitBeforeCatchSwitch(), splitCallSite(), SplitLandingPadPredecessorsImpl(), llvm::splitLoopBound(), stripDebugDeclareImpl(), llvm::PHITransAddr::translateWithInsertion(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), TryToMergeLandingPad(), TryToShrinkGlobalToBoolean(), turnToExplicitForm(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchTrivialBranch(), unswitchTrivialSwitch(), llvm::UpgradeARCRuntime(), llvm::versionCallSite(), llvm::LoopVersioning::versionLoop(), and llvm::ObjectSizeOffsetEvaluator::visitPHINode().
extractProfTotalWeight()
bool Instruction::extractProfTotalWeight (uint64_t & TotalVal) const
Retrieve total raw weight values of a branch.
Returns true on success with profile total weights filled in. Returns false if no metadata was found.
Definition at line 1539 of file Metadata.cpp.
References assert(), llvm::MCID::Call, llvm::extractProfTotalWeight(), getOpcode(), and Select.
Referenced by llvm::createCallMatchingInvoke().
getAAMetadata()
AAMDNodes Instruction::getAAMetadata () const
Returns the AA metadata for this instruction.
Definition at line 1499 of file Metadata.cpp.
References llvm::Value::getContext(), llvm::Value::hasMetadata(), Info, llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValueMetadata.
Referenced by llvm::MemoryLocation::get(), llvm::MemoryLocation::getForDest(), mergeConditionalStoreToAddress(), llvm::InstCombinerImpl::mergeStoreIntoSuccessor(), llvm::promoteLoopAccessesToScalars(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), speculatePHINodeLoads(), speculateSelectInstLoads(), and unpackLoadToAggregate().
getAllMetadata()
void llvm::Instruction::getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * >> & MDs) const inline
Get all metadata attached to this Instruction.
The first element of each pair returned is the KindID, the second element is the metadata value. This list is returned sorted by the KindID.
Definition at line 291 of file Instruction.h.
References hasMetadata().
Referenced by llvm::SITargetLowering::emitExpandAtomicRMW().
getAllMetadataOtherThanDebugLoc()
void llvm::Instruction::getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * >> & MDs) const inline
This does the same thing as getAllMetadata, except that it filters out the debug location.
Definition at line 298 of file Instruction.h.
References llvm::Value::getAllMetadata().
Referenced by llvm::combineMetadata(), copyMetadata(), and llvm::propagateMetadata().
getDebugLoc()
const DebugLoc& llvm::Instruction::getDebugLoc () const inline
Return the debug location for this node as a DebugLoc.
Definition at line 358 of file Instruction.h.
Referenced by llvm::SelectionDAGBuilder::addDanglingDebugInfo(), BreakUpSubtract(), buildFrameDebugInfo(), buildOverlapMapAndRecordDeclares(), llvm::changeToInvokeAndSplitBasicBlock(), CloneInstructionsIntoPredecessorBlockAndUpdateSSAUses(), computeCallStackHash(), ConvertShiftToMul(), copyMetadata(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::CallBrInst::Create(), createAndInstr(), llvm::createCallMatchingInvoke(), llvm::VPRecipeBuilder::createEdgeMask(), llvm::InnerLoopVectorizer::createInductionResumeValue(), despeculateCountZeros(), diagnoseInvalidFormatString(), llvm::VPWidenIntOrFpInductionRecipe::execute(), llvm::extractProbeFromDiscriminator(), findVarsWithStackSlot(), fixupDebugInfoPostExtraction(), fixupLineNumbers(), FoldCondBranchOnValueKnownInPredecessorImpl(), llvm::ReplayInlineAdvisor::getAdviceImpl(), getAggregate(), llvm::SampleContextTracker::getCalleeContextSamplesFor(), llvm::SelectionDAGBuilder::getCurDebugLoc(), llvm::getDebugValueLoc(), llvm::VNCoercion::getLoadValueForLoad(), getOrCreateDebugLoc(), llvm::hoistAllInstructionsInto(), llvm::InlineFunction(), llvm::InstCombiner::InsertNewInstWith(), LowerNegateToMultiply(), llvm::InstCombinerImpl::mergeStoreIntoSuccessor(), operandWithNewAddressSpaceOrCreateUndef(), OptimizeExtractBits(), llvm::InstCombinerImpl::PHIArgMergedDebugLoc(), processAShr(), processSDiv(), processSExt(), processSRem(), llvm::SampleContextTracker::promoteMergeContextSamplesTree(), llvm::removeUnwindEdge(), llvm::SCEVExpander::replaceCongruentIVs(), replaceOneDbgValueForAlloca(), llvm::IRTranslator::runOnMachineFunction(), llvm::InnerLoopVectorizer::scalarizeInstruction(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), llvm::FastISel::selectOperator(), llvm::VPTransformState::setDebugLocFromInst(), llvm::setProbeDistributionFactor(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), sinkAndCmp0Expression(), SinkCast(), sinkLastInstruction(), SinkShiftAndTruncate(), llvm::SplitBlockAndInsertIfThenElse(), SplitBlockAndInsertIfThenImpl(), splitCallSite(), llvm::SplitKnownCriticalEdge(), SplitLandingPadPredecessorsImpl(), TryToShrinkGlobalToBoolean(), llvm::JumpThreadingPass::unfoldSelectInstr(), updateForIncomingValueLocation(), llvm::sroa::AllocaSliceRewriter::visit(), and llvm::InstCombinerImpl::visitLoadInst().
getFastMathFlags()
FastMathFlags Instruction::getFastMathFlags () const
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
See LangRef.html for the meaning of these flags.
Definition at line 339 of file Instruction.cpp.
References assert().
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), andIRFlags(), llvm::IRBuilderBase::CreateConstrainedFPBinOp(), llvm::IRBuilderBase::CreateConstrainedFPCast(), llvm::IRBuilderBase::CreateFAddFMF(), llvm::IRBuilderBase::CreateFDivFMF(), llvm::IRBuilderBase::CreateFMulFMF(), llvm::IRBuilderBase::CreateFNegFMF(), llvm::IRBuilderBase::CreateFRemFMF(), llvm::IRBuilderBase::CreateFSubFMF(), llvm::InnerLoopVectorizer::createInductionResumeValue(), llvm::InnerLoopVectorizer::fixupIVUsers(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldSelectOpOp(), FoldTwoEntryPHINode(), getISDForVPIntrinsic(), instCombineSVEVectorBinOp(), instCombineSVEVectorFuseMulAddSub(), llvm::matchDecomposedSelectPattern(), llvm::InstModificationIRStrategy::mutate(), optimizeDoubleFP(), llvm::VPReductionRecipe::print(), replaceUnaryCall(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), and llvm::InstCombinerImpl::visitCallInst().
getFunction() [1/2]
Function* llvm::Instruction::getFunction () inline
Definition at line 109 of file Instruction.h.
References getFunction().
getFunction() [2/2]
const Function * Instruction::getFunction () const
Return the function this instruction belongs to.
Note: it is undefined behavior to call this on an instruction not currently inserted into a function.
Definition at line 74 of file Instruction.cpp.
References getParent(), and llvm::BasicBlock::getParent().
Referenced by analyzeLoopUnrollCost(), canSimplifyNullLoadOrGEP(), canTransformToMemCmp(), llvm::AArch64TargetLowering::fallBackToDAGISel(), fixupDebugInfoPostExtraction(), forwardStoredOnceStore(), llvm::InstCombinerImpl::freezeOtherUses(), llvm::ReplayInlineAdvisor::getAdviceImpl(), getFunction(), llvm::NVPTXTargetLowering::getPrototype(), llvm::coro::Shape::getRetconResultTypes(), getShape(), HandleByValArgument(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), insertSpills(), llvm::InstrumentationIRBuilder::InstrumentationIRBuilder(), IsOperandAMemoryOperand(), llvm::AA::isPotentiallyReachable(), isPotentiallyReachable(), llvm::AA::isValidAtPosition(), llvm::lowerObjectSizeCall(), llvm::LoopInfo::movementPreservesLCSSAForm(), llvm::mustSuppressSpeculation(), NegateValue(), optimizeDoubleFP(), promoteArguments(), removeTailCallAttribute(), llvm::coro::salvageDebugInfo(), llvm::VPTransformState::setDebugLocFromInst(), llvm::SITargetLowering::shouldExpandAtomicRMWInIR(), simplifyNvvmIntrinsic(), llvm::OutlinableRegion::splitCandidate(), tryToOptimizeStoreOfAllocationToGlobal(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitTrunc(), and llvm::InstCombinerImpl::visitZExt().
getInsertionPointAfterDef()
Instruction * Instruction::getInsertionPointAfterDef ()
Get the first insertion point at which the result of this instruction is defined.
This is not the directly following instruction in a number of cases, e.g. phi nodes or terminators that return values. This function may return null if the insertion after the definition is not possible, e.g. due to a catchswitch terminator.
Definition at line 131 of file Instruction.cpp.
References assert(), llvm::BasicBlock::end(), llvm::BasicBlock::getFirstInsertionPt(), llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >::getIterator(), getParent(), llvm::BasicBlock::getParent(), llvm::Value::getType(), and isTerminator().
Referenced by llvm::InstCombinerImpl::freezeOtherUses(), and NegateValue().
getMetadata() [1/2]
MDNode* llvm::Instruction::getMetadata (StringRef Kind) const inline
Get the metadata of given kind attached to this Instruction.
If the metadata is not found then return null.
Definition at line 282 of file Instruction.h.
References hasMetadata().
getMetadata() [2/2]
MDNode* llvm::Instruction::getMetadata (unsigned KindID) const inline
Get the metadata of given kind attached to this Instruction.
If the metadata is not found then return null.
Definition at line 275 of file Instruction.h.
References hasMetadata().
Referenced by AddAliasScopeMetadata(), addAnnotationMetadata(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::FunctionComparator::cmpOperations(), llvm::combineMetadata(), convertMetadataToAssumes(), llvm::IRBuilderBase::CreateSelect(), llvm::diagnoseDontCall(), emitDbgAssign(), foldCtpop(), foldCttzCtlz(), llvm::InstCombinerImpl::foldPHIArgLoadIntoPHI(), FoldTwoEntryPHINode(), llvm::at::getAssignmentMarkers(), GetBranchWeights(), getFromRangeMetadata(), llvm::BasicBlock::getIrrLoopHeaderWeight(), llvm::Loop::getLoopID(), llvm::ScopedNoAliasAAResult::getModRefInfo(), llvm::TypeBasedAAResult::getModRefInfo(), llvm::getValueProfDataFromInst(), hasMetadata(), hasOnlyUniformBranches(), llvm::DIBuilder::insertDbgAssign(), insertUniqueBackedgeBlock(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::intersectAccessGroups(), llvm::CallLowering::lowerCall(), llvm::FastISel::lowerCallTo(), llvm::makeGuardControlFlowExplicit(), performBranchToCommonDestFolding(), llvm::InstCombinerImpl::PromoteCastOfAllocation(), PropagateCallSiteMetadata(), propagateMemProfHelper(), propagateMemProfMetadata(), llvm::propagateMetadata(), shouldFoldCondBranchesToCommonDestination(), SplitBlockPredecessorsImpl(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), unswitchNontrivialInvariants(), and llvm::CallInst::updateProfWeight().
getModule() [1/2]
Module* llvm::Instruction::getModule () inline
Definition at line 99 of file Instruction.h.
References getModule().
getModule() [2/2]
const Module * Instruction::getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Note: this is undefined behavior if the instruction does not have a parent, or the parent basic block does not have a parent function.
Definition at line 70 of file Instruction.cpp.
References llvm::BasicBlock::getModule(), and getParent().
Referenced by addAssumeNonNull(), llvm::addDiffRuntimeChecks(), addMappingsFromTLI(), llvm::addRuntimeChecks(), addVariantDeclaration(), llvm::buildAssumeFromKnowledge(), llvm::VPIntrinsic::canIgnoreVectorLengthParam(), collectFrameAlloca(), computeRecurrenceType(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), createCoroSave(), CreateGCRelocates(), createTblForTrunc(), llvm::LoongArchTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::RISCVTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::LoongArchTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::RISCVTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::expandAtomicRMWToCmpXchg(), factorizeMinMaxTree(), foldCtpop(), foldCttzCtlz(), foldGuardedFunnelShift(), foldShuffleOfUnaryOps(), llvm::InstCombinerImpl::foldVectorBinop(), llvm::SCEVExpander::generateOverflowCheck(), llvm::MemoryLocation::get(), llvm::memtag::getAllocaSizeInBytes(), llvm::getAllocSize(), getAtomicOpSize(), llvm::DemandedBits::getDemandedBits(), llvm::getGEPInductionOperand(), llvm::VNCoercion::getLoadLoadClobberFullWidthSize(), getModule(), llvm::LazyValueInfo::getPredicateAt(), llvm::InstrProfIncrementInst::getStep(), llvm::VFABI::getVectorVariantNames(), inlineRetainOrClaimRVCalls(), llvm::DIBuilder::insertDbgAssign(), insertSpills(), llvm::GCNTTIImpl::instCombineIntrinsic(), instCombineLD1GatherIndex(), instCombineST1ScatterIndex(), llvm::TargetLibraryInfoImpl::isCallingConvCCompatible(), llvm::isDereferenceableAndAlignedInLoop(), llvm::InductionDescriptor::isInductionPHI(), llvm::GCNTTIImpl::isInlineAsmSourceOfDivergence(), isLoadInvariantInLoop(), isSafePHIToSpeculate(), llvm::isSafeToSpeculativelyExecuteWithOpcode(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), lowerLocalAllocas(), llvm::IntrinsicLowering::LowerToByteSwap(), modifyIntrinsicCall(), NegateValue(), llvm::LibCallSimplifier::optimizeCall(), optimizeDoubleFP(), promoteSingleBlockAlloca(), reassociateMinMaxWithConstantInOperand(), reassociateMinMaxWithConstants(), ReplaceCallWith(), replaceUnaryCall(), replaceWithCallToVeclib(), replaceWithTLIFunction(), rewriteSingleStoreAlloca(), llvm::VFABI::setVectorVariantNames(), simplifyAMDGCNMemoryIntrinsicDemanded(), simplifyNvvmIntrinsic(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), llvm::simplifyRetainedKnowledge(), simplifyTerminatorLeadingToRet(), simplifyX86immShift(), simplifyX86varShift(), upgradeAbs(), upgradeAVX512MaskToSelect(), UpgradeX86BinaryIntrinsics(), upgradeX86ConcatShift(), UpgradeX86MaskedShift(), upgradeX86Rotate(), UpgradeX86VPERMT2Intrinsics(), llvm::AMDGPULibCalls::useNative(), valueCoversEntireFragment(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InstCombinerImpl::visitAllocSite(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFPTrunc(), and visitIVCast().
getNextNonDebugInstruction() [1/2]
Instruction* llvm::Instruction::getNextNonDebugInstruction (bool SkipPseudoOp = false) inline
Definition at line 713 of file Instruction.h.
References getNextNonDebugInstruction().
getNextNonDebugInstruction() [2/2]
const Instruction * Instruction::getNextNonDebugInstruction (bool SkipPseudoOp = false) const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Skip any pseudo operations if SkipPseudoOp is true.
Definition at line 786 of file Instruction.cpp.
References llvm::ilist_node_with_parent< Instruction, BasicBlock >::getNextNode(), and I.
Referenced by findStoresToUninstrumentedArgAllocas(), getNextNonDebugInstruction(), isPotentiallyReachable(), nextIRInstructionDataMatchesNextInst(), RemovePreallocated(), rewriteDebugUsers(), llvm::OutlinableRegion::splitCandidate(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitFenceInst().
getNumSuccessors()
unsigned Instruction::getNumSuccessors () const
Return the number of successors that this instruction has.
The instruction must be a terminator.
Definition at line 823 of file Instruction.cpp.
References getOpcode(), and llvm_unreachable.
Referenced by llvm::FunctionComparator::compare(), llvm::deleteDeadLoop(), llvm::CodeExtractor::extractCodeRegion(), llvm::InstCombinerImpl::foldPHIArgLoadIntoPHI(), getBestDestForJumpOnUndef(), getBranchHint(), llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes(), getInstrBB(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), llvm::isCriticalEdge(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::isEdgeFeasible(), isSafePHIToSpeculate(), llvm::JumpThreadingPass::maybeMergeBasicBlockIntoOnlyPred(), llvm::JumpThreadingPass::processBlock(), replaceConstantExprOp(), replaceSuccessorWith(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), skipPGO(), llvm::SplitAllCriticalEdges(), llvm::SplitCriticalEdge(), llvm::SplitKnownCriticalEdge(), llvm::JumpThreadingPass::threadEdge(), llvm::JumpThreadingPass::threadThroughTwoBasicBlocks(), and llvm::JumpThreadingPass::tryToUnfoldSelectInCurrBB().
getOpcode()
unsigned llvm::Instruction::getOpcode () const inline
Returns a member of one of the enums like Instruction::Add.
Definition at line 168 of file Instruction.h.
References llvm::Value::getValueID().
Referenced by llvm::LanaiInstrInfo::analyzeBranch(), canEvaluateShiftedShift(), canPHITrans(), checkIfSafeAddSequence(), checkOrderedReduction(), clone(), llvm::FunctionComparator::cmpOperations(), llvm::CallBase::Create(), llvm::InstCombinerImpl::Descale(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), dropPoisonGeneratingFlags(), expandFPToI(), expandIToFP(), extractProfTotalWeight(), findDemandedEltsBySingleUser(), findIBRPredecessor(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpInstWithConstantNotInt(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), llvm::InstCombinerImpl::foldPHIArgBinOpIntoPHI(), llvm::InstCombinerImpl::foldSelectOpOp(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldSignedTruncationCheck(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::getConstrainedIntrinsicID(), getFromRangeMetadata(), getHashValueImpl(), llvm::SCEVExpander::getIVIncOperand(), getLoopPhiForCounter(), llvm::CallBase::getNumSubclassExtraOperands(), llvm::CallBase::getNumSubclassExtraOperandsDynamic(), getNumSuccessors(), llvm::UnaryOperator::getOpcode(), llvm::BinaryOperator::getOpcode(), llvm::CastInst::getOpcode(), llvm::CmpInst::getOpcode(), llvm::SelectInst::getOpcode(), getOpcodeName(), llvm::MemoryLocation::getOrNone(), getSuccessor(), hasAtomicLoad(), hasAtomicStore(), haveSameSpecialState(), llvm::InlineFunction(), InTreeUserNeedToExtract(), isAlternateInstruction(), isArithmeticShift(), isAssociative(), isAtomic(), isBinaryOp(), isBitwiseLogicOp(), isCast(), isCommutative(), isEHPad(), isEqualImpl(), isExceptionalTerminator(), isFenceLike(), llvm::SystemZTTIImpl::isFoldableLoad(), isFuncletPad(), isHighCostExpansion(), isIdempotent(), isIdenticalToWhenDefined(), isIntDivRem(), isLogicalShift(), isMatchingStore(), isNilpotent(), isPromotedInstructionLegal(), isReachableFromPHI(), isReturnNonNull(), llvm::isSafeToSpeculativelyExecute(), llvm::isSafeToSpeculativelyExecuteWithOpcode(), isSameOperationAs(), isShift(), isTerminator(), isUnaryOp(), isVolatile(), matchExpandedRem(), mayReadFromMemory(), mayWriteToMemory(), llvm::InstModificationIRStrategy::mutate(), needsFP(), NegateValue(), performBlockTailMerging(), llvm::VPWidenMemoryInstructionRecipe::print(), llvm::JumpThreadingPass::processBlock(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::refineInstruction(), llvm::LanaiInstrInfo::removeBranch(), llvm::replaceSignedInst(), setSuccessor(), llvm::AArch64TargetLowering::shouldSinkOperands(), llvm::InstCombinerImpl::simplifyShrShlDemandedBits(), SinkShiftAndTruncate(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), llvm::InstCombinerImpl::visitFCmpInst(), and llvm::InstCombinerImpl::visitICmpInst().
getOpcodeName() [1/2]
const char* llvm::Instruction::getOpcodeName () const inline
Definition at line 170 of file Instruction.h.
References getOpcode(), and getOpcodeName().
Referenced by checkInstructions(), llvm::VPRecipeBuilder::createReplicateRegion(), getOpcodeName(), llvm::ConstantExpr::getOpcodeName(), llvm::VPInstruction::print(), llvm::VPWidenRecipe::print(), llvm::VPReductionRecipe::print(), llvm::VPReplicateRecipe::print(), llvm::VPWidenMemoryInstructionRecipe::print(), and PrintOps().
getOpcodeName() [2/2]
const char * Instruction::getOpcodeName (unsigned OpCode) static
Definition at line 397 of file Instruction.cpp.
References llvm::And, llvm::FAdd, llvm::FMul, llvm::SPII::Load, Mul, llvm::Or, PHI, llvm::MipsISD::Ret, Select, llvm::SPII::Store, and llvm::Xor.
getParent() [1/2]
BasicBlock* llvm::Instruction::getParent () inline
Definition at line 91 of file Instruction.h.
getParent() [2/2]
const BasicBlock* llvm::Instruction::getParent () const inline
Definition at line 90 of file Instruction.h.
Referenced by Prefetch::addInstruction(), addNoRecurseAttrsTopDown(), llvm::RecurrenceDescriptor::AddReductionVar(), AddReturnAttributes(), allSameBlock(), AreEquivalentPhiNodes(), areInnerLoopLatchPHIsSupported(), areOuterLoopExitPHIsSupported(), areTwoInsertFromSameBuildVector(), BlockIsSimpleEnoughToThreadThrough(), BrPHIToSelect(), buildPartialInvariantUnswitchConditionalBranch(), llvm::PredicateInfoBuilder::buildPredicateInfo(), llvm::calculateClrEHStateNumbers(), calculateCXXStateNumbers(), calculateSEHStateNumbers(), CalculateUnswitchCostMultiplier(), canHoistIVInc(), llvm::AAResults::canInstructionRangeModRef(), CanPropagatePredecessorsForPHIs(), canSinkInstructions(), canSplitCallSite(), canSplitPredecessors(), llvm::changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), checkHoistValue(), checkIsIndPhi(), checkPHIs(), llvm::cloneAndAdaptNoAliasScopes(), llvm::CloneAndPruneIntoFromInst(), cloneInstructionInExitBlock(), llvm::InnerLoopVectorizer::collectPoisonGeneratingRecipes(), llvm::computeConstantRange(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), ConnectEpilog(), llvm::ConvertDebugDeclareToDebugValue(), llvm::objcarc::createCallInstWithColors(), createFree(), createMalloc(), llvm::createMemCpyLoopKnownSize(), createMemMoveLoop(), createMemSetLoop(), llvm::OpenMPIRBuilder::createParallel(), llvm::VPRecipeBuilder::createReplicateRegion(), createRetPHINode(), llvm::OpenMPIRBuilder::createSections(), createTileStore(), despeculateCountZeros(), diagnoseInvalidFormatString(), llvm::PostDominatorTree::dominates(), llvm::DominatorTree::dominates(), llvm::InstCombinerImpl::dominatesAllUses(), domTreeLevelBefore(), eraseFromParent(), llvm::ScalarEvolution::evaluatePredicateAt(), llvm::VPPredInstPHIRecipe::execute(), findBestNonTrivialUnswitchCandidate(), llvm::findDevirtualizableCallsForTypeTest(), findExtractedOutputToOverallOutputMapping(), findInitTrampolineFromBB(), llvm::SCEVExpander::findInsertPointAfter(), findLiveSetAtInst(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::DominatorTree::findNearestCommonDominator(), findPotentialBlockers(), llvm::AMDGPULibCalls::fold(), llvm::InstCombinerImpl::foldBinopWithPhiOperands(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnValueKnownInPredecessorImpl(), foldConsecutiveLoads(), llvm::InstCombinerImpl::foldFreezeIntoRecurrence(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpInstWithConstantNotInt(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), foldLoadsRecursive(), llvm::InstCombinerImpl::foldOpIntoPhi(), llvm::InstCombinerImpl::foldPHIArgLoadIntoPHI(), llvm::InstCombinerImpl::foldPHIArgOpIntoPHI(), llvm::InstCombinerImpl::foldPHIArgZextsIntoPHI(), FoldTwoEntryPHINode(), fpModeMatchesGlobalFPAtomicMode(), llvm::InnerLoopVectorizer::getBroadcastInstrs(), llvm::CallBase::getCaller(), llvm::LazyValueInfo::getConstant(), llvm::ScalarEvolution::getConstantMaxTripCountFromArray(), llvm::LazyValueInfo::getConstantRange(), getDefaultInlineAdvice(), llvm::MemoryDependenceResults::getDependency(), getDomPredecessorCondition(), llvm::IRSimilarity::IRSimilarityCandidate::getEndBB(), getFunction(), getFunctionTypeFromAsyncSuspend(), getGVNForPHINode(), getInsertionPointAfterDef(), getInsertPointForUses(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), getInvertibleOperands(), getIVIncrement(), getJumpThreadDuplicationCost(), llvm::VNCoercion::getLoadLoadClobberFullWidthSize(), llvm::VNCoercion::getLoadValueForLoad(), getLoopPhiForCounter(), getModule(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedPrevInstruction(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::LazyValueInfo::getPredicateAt(), llvm::IRSimilarity::IRSimilarityCandidate::getStartBB(), llvm::memtag::getUntagLocationIfFunctionExit(), getVarName(), HandleInlinedEHPad(), HandleInlinedLandingPad(), handlePhiDef(), hasCallsBetween(), hasOnlyUniformBranches(), llvm::SCEVExpander::hoistIVInc(), llvm::hoistRegion(), hoistValue(), INITIALIZE_PASS(), llvm::InlineFunction(), inlineRetainOrClaimRVCalls(), insertAfter(), insertBefore(), insertCall(), llvm::DIBuilder::insertDbgAddrIntrinsic(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), insertInto(), llvm::DIBuilder::insertLabel(), insertLifetimeMarkersSurroundingCall(), llvm::InstCombiner::InsertNewInstBefore(), insertSpills(), llvm::GCNTTIImpl::instCombineIntrinsic(), Instruction(), llvm::invertCondition(), IsAcceptableTarget(), llvm::Loop::isAuxiliaryInductionVariable(), isBlockInLCSSAForm(), isColdCallSite(), llvm::isControlFlowEquivalent(), llvm::isCriticalEdge(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::InductionDescriptor::isFPInductionPHI(), isFreeInLoop(), isGuaranteedNotToBeUndefOrPoison(), llvm::SimpleLoopSafetyInfo::isGuaranteedToExecute(), llvm::ICFLoopSafetyInfo::isGuaranteedToExecute(), isIntegerLoopHeaderPHI(), isKnownNonNullFromDominatingCondition(), llvm::ScalarEvolution::isKnownPredicateAt(), isLoadInvariantInLoop(), isLocalAlloca(), isLoopCounter(), isNonEqualPHIs(), isNotUsedOrFreeInLoop(), isPowerOfTwoRecurrence(), isPredicatedOnPHI(), llvm::isReachedBefore(), isSafeAndProfitableToSinkLoad(), isSafePHIToSpeculate(), llvm::SCEVExpander::isSafeToExpandAt(), llvm::isSafeToLoadUnconditionally(), isSafeToSinkLoad(), isSameUnderlyingObjectInLoop(), llvm::AllocaInst::isStaticAlloca(), llvm::AMDGPULibCalls::isUnsafeMath(), llvm::isValidAssumeForContext(), llvm::AA::isValidAtPosition(), isValidCandidateForColdCC(), liesBetween(), LLVMGetNextInstruction(), LLVMGetPreviousInstruction(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::makeGuardControlFlowExplicit(), llvm::Loop::makeLoopInvariant(), matchAddReduction(), llvm::SITargetLowering::mayBeEmittedAsTailCall(), memoryIsNotModifiedBetween(), mergeCleanupPad(), MergeCompatibleInvokesImpl(), mergeConditionalStores(), mergeConditionalStoreToAddress(), mergeInlinedArrayAllocas(), moveAfter(), moveBBContents(), moveBefore(), moveInstructionBefore(), llvm::LoopInfo::movementPreservesLCSSAForm(), llvm::InstDeleterIRStrategy::mutate(), NegateValue(), nextIRInstructionDataMatchesNextInst(), optimizeBranch(), optimizeDivRem(), OptimizeExtractBits(), optimizeSQRT(), performBranchToCommonDestFolding(), llvm::JumpThreadingPass::processBlock(), llvm::JumpThreadingPass::processBranchOnPHI(), llvm::JumpThreadingPass::processBranchOnXOR(), processUse(), llvm::promoteLoopAccessesToScalars(), llvm::AssumptionCache::registerAssumption(), rematerializeLiveValuesAtUses(), removeEmptyCleanup(), removeFromParent(), llvm::InstructionPrecedenceTracking::removeInstruction(), removeTriviallyEmptyRange(), replaceArgumentUses(), replaceAsyncResumeFunction(), ReplaceCallWith(), replaceConditionalBranchesOnConstant(), llvm::SCEVExpander::replaceCongruentIVs(), replaceExtractElements(), replaceSubOverflowUses(), returnEdge(), reuseTableCompare(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::rewriteLoopExitValues(), rewriteSingleStoreAlloca(), RewriteUsesOfClonedInstructions(), llvm::SyntheticCountsPropagation::run(), llvm::InstCombinerImpl::run(), safeCxtI(), SafeToMergeTerminators(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), scanPHIsAndUpdateValueMap(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::setProfMetadata(), shouldFoldCondBranchesToCommonDestination(), shouldSplitOnPHIPredicatedArgument(), shouldSplitOnPredicatedArgument(), SimplifyCondBranchToCondBranch(), simplifyICmpWithDominatingAssume(), simplifyOneLoop(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), simplifyRelocatesOffABase(), simplifySuspendPoint(), simplifyTerminatorLeadingToRet(), llvm::simplifyUsersOfIV(), simplifyUsingControlFlow(), sink(), sinkAndCmp0Expression(), SinkCast(), SinkInstruction(), sinkInstruction(), sinkLifetimeStartMarkers(), llvm::InnerLoopVectorizer::sinkScalarOperands(), SinkShiftAndTruncate(), sinkSpillUsesAfterCoroBegin(), sinkThroughTriviallyReplaceablePHI(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), splitBeforeCatchSwitch(), llvm::SplitBlockAndInsertIfThenElse(), SplitBlockAndInsertIfThenImpl(), SplitBlockImpl(), splitCallSite(), llvm::OutlinableRegion::splitCandidate(), llvm::SplitKnownCriticalEdge(), splitPredecessorsOfLoopExit(), llvm::PHITransAddr::translateValue(), llvm::tryPromoteCall(), llvm::VPRecipeBuilder::tryToCreateWidenRecipe(), llvm::FastISel::tryToFoldLoad(), tryToMoveFreeBeforeNullTest(), llvm::JumpThreadingPass::tryToUnfoldSelect(), tryUnmergingGEPsAcrossIndirectBr(), tryWidenCondBranchToCondBranch(), turnGuardIntoBranch(), turnToExplicitForm(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), updateIDTMetaData(), updateKillStatus(), updatePredecessorProfileMetadata(), llvm::CallInst::updateProfWeight(), llvm::JumpThreadingPass::updateSSA(), updateSuccessor(), llvm::UpgradeARCRuntime(), llvm::UpgradeIntrinsicCall(), valueEscapes(), llvm::versionCallSite(), llvm::InstCombinerImpl::visitAllocaInst(), llvm::InstCombinerImpl::visitAllocSite(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitGEPOfBitcast(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::ObjectSizeOffsetVisitor::visitLoadInst(), and llvm::InstCombinerImpl::visitPHINode().
getPrevNonDebugInstruction() [1/2]
Instruction* llvm::Instruction::getPrevNonDebugInstruction (bool SkipPseudoOp = false) inline
Definition at line 724 of file Instruction.h.
References getPrevNonDebugInstruction().
getPrevNonDebugInstruction() [2/2]
const Instruction * Instruction::getPrevNonDebugInstruction (bool SkipPseudoOp = false) const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Skip any pseudo operations if SkipPseudoOp is true.
Definition at line 794 of file Instruction.cpp.
References llvm::ilist_node_with_parent< Instruction, BasicBlock >::getPrevNode(), and I.
Referenced by getPrevNonDebugInstruction(), and llvm::InstCombinerImpl::visitFenceInst().
getSubclassData()
template<typename BitfieldElement > BitfieldElement::Type llvm::Instruction::getSubclassData () const inline protected
Definition at line 865 of file Instruction.h.
getSuccessor()
BasicBlock * Instruction::getSuccessor (unsigned Idx) const
Return the specified successor. This instruction must be a terminator.
Definition at line 835 of file Instruction.cpp.
References getOpcode(), and llvm_unreachable.
Referenced by canSinkInstructions(), llvm::FunctionComparator::compare(), llvm::CodeExtractor::extractCodeRegion(), findLoopComponents(), getBestDestForJumpOnUndef(), getBranchHint(), llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), injectPendingInvariantConditions(), llvm::isCriticalEdge(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::isEdgeFeasible(), llvm::InstCombinerImpl::mergeStoreIntoSuccessor(), optimizeSQRT(), llvm::JumpThreadingPass::processBlock(), replaceSuccessorWith(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), llvm::SplitCriticalEdge(), llvm::SplitKnownCriticalEdge(), llvm::JumpThreadingPass::threadEdge(), llvm::JumpThreadingPass::threadThroughTwoBasicBlocks(), and llvm::UnrollAndJamLoop().
hasAllowContract()
bool Instruction::hasAllowContract () const
Determine whether the allow-contract flag is set.
Definition at line 329 of file Instruction.cpp.
References assert().
Referenced by llvm::GCNTTIImpl::getArithmeticInstrCost(), and llvm::InstModificationIRStrategy::mutate().
hasAllowReassoc()
bool Instruction::hasAllowReassoc () const
Determine whether the allow-reassociation flag is set.
Definition at line 304 of file Instruction.cpp.
References assert().
Referenced by llvm::InductionDescriptor::getExactFPMathInst(), llvm::InstModificationIRStrategy::mutate(), simplifyUnaryIntrinsic(), and llvm::InstCombinerImpl::visitCallInst().
hasAllowReciprocal()
bool Instruction::hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
Definition at line 324 of file Instruction.cpp.
References assert().
Referenced by llvm::InstModificationIRStrategy::mutate().
hasApproxFunc()
bool Instruction::hasApproxFunc () const
Determine whether the approximate-math-functions flag is set.
Definition at line 334 of file Instruction.cpp.
References assert().
Referenced by llvm::InstModificationIRStrategy::mutate().
hasAtomicLoad()
bool Instruction::hasAtomicLoad () const
Return true if this atomic instruction loads from memory.
Definition at line 681 of file Instruction.cpp.
References assert(), getOpcode(), isAtomic(), and llvm::SPII::Load.
Referenced by llvm::PPCTargetLowering::emitTrailingFence().
hasAtomicStore()
bool Instruction::hasAtomicStore () const
Return true if this atomic instruction stores to memory.
Definition at line 693 of file Instruction.cpp.
References assert(), getOpcode(), isAtomic(), and llvm::SPII::Store.
Referenced by llvm::VETargetLowering::emitLeadingFence(), llvm::ARMTargetLowering::emitLeadingFence(), and llvm::TargetLoweringBase::emitLeadingFence().
hasMetadata() [1/3]
bool llvm::Instruction::hasMetadata () const inline
Return true if this instruction has any metadata attached to it.
Definition at line 257 of file Instruction.h.
References llvm::Value::hasMetadata().
Referenced by copyMetadata(), getAllMetadata(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), llvm::TargetLoweringBase::getLoadMemOperandFlags(), getMetadata(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), llvm::SITargetLowering::getTgtMemIntrinsic(), hasPoisonGeneratingMetadata(), IsAcceptableTarget(), shouldTryInjectBasingOnMetadata(), and updateMemprofMetadata().
hasMetadata() [2/3]
bool llvm::Instruction::hasMetadata (StringRef Kind) const inline
Return true if this instruction has the given type of metadata attached.
Definition at line 269 of file Instruction.h.
References getMetadata().
hasMetadata() [3/3]
bool llvm::Instruction::hasMetadata (unsigned KindID) const inline
Return true if this instruction has the given type of metadata attached.
Definition at line 264 of file Instruction.h.
References getMetadata().
hasMetadataOtherThanDebugLoc()
bool llvm::Instruction::hasMetadataOtherThanDebugLoc () const inline
Return true if this instruction has metadata attached to it other than a debug location.
Definition at line 261 of file Instruction.h.
References llvm::Value::hasMetadata().
hasNoInfs()
bool Instruction::hasNoInfs () const
Determine whether the no-infs flag is set.
Definition at line 314 of file Instruction.cpp.
References assert().
Referenced by foldFCmpReciprocalAndZero(), llvm::InstModificationIRStrategy::mutate(), and simplifyBinaryIntrinsic().
hasNoNaNs()
bool Instruction::hasNoNaNs () const
Determine whether the no-NaNs flag is set.
Definition at line 309 of file Instruction.cpp.
References assert().
Referenced by llvm::InstModificationIRStrategy::mutate(), and simplifyBinaryIntrinsic().
hasNoSignedWrap()
bool Instruction::hasNoSignedWrap () const
Determine whether the no signed wrap flag is set.
Definition at line 177 of file Instruction.cpp.
Referenced by andIRFlags(), buildNew(), checkNoWrapFlags(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::Descale(), detectShiftUntilZeroIdiom(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), foldIDivShl(), foldMulShl1(), isNonZeroRecurrence(), llvm::InstModificationIRStrategy::mutate(), processBinOp(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::refineInstruction(), setLimitsForBinOp(), llvm::InstCombinerImpl::simplifyShrShlDemandedBits(), llvm::InstCombinerImpl::visitLShr(), and llvm::InstCombinerImpl::visitMul().
hasNoSignedZeros()
bool Instruction::hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
Definition at line 319 of file Instruction.cpp.
References assert().
Referenced by foldSelectBinOpIdentity(), llvm::InstModificationIRStrategy::mutate(), and simplifySelectWithFCmp().
hasNoUnsignedWrap()
bool Instruction::hasNoUnsignedWrap () const
Determine whether the no unsigned wrap flag is set.
Definition at line 173 of file Instruction.cpp.
Referenced by andIRFlags(), buildNew(), checkNoWrapFlags(), llvm::InstCombinerImpl::commonIDivTransforms(), detectShiftUntilZeroIdiom(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), foldIDivShl(), foldMulShl1(), llvm::ScalarEvolution::getUDivExactExpr(), isNonZeroRecurrence(), llvm::InstModificationIRStrategy::mutate(), processBinOp(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::refineInstruction(), llvm::InstCombinerImpl::simplifyShrShlDemandedBits(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSub().
hasPoisonGeneratingFlags()
bool Instruction::hasPoisonGeneratingFlags () const
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
Definition at line 181 of file Instruction.cpp.
Referenced by dropPoisonGeneratingFlags(), and hasPoisonGeneratingFlagsOrMetadata().
hasPoisonGeneratingFlagsOrMetadata()
bool llvm::Instruction::hasPoisonGeneratingFlagsOrMetadata () const inline
Return true if this instruction has poison-generating flags or metadata.
Definition at line 393 of file Instruction.h.
References hasPoisonGeneratingFlags(), and hasPoisonGeneratingMetadata().
hasPoisonGeneratingMetadata()
bool Instruction::hasPoisonGeneratingMetadata () const
Return true if this instruction has poison-generating metadata.
Definition at line 214 of file Instruction.cpp.
References hasMetadata().
Referenced by hasPoisonGeneratingFlagsOrMetadata().
insertAfter()
void Instruction::insertAfter (Instruction * InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
Definition at line 94 of file Instruction.cpp.
References llvm::ilist_node_impl< OptionsT >::getIterator(), getParent(), and insertInto().
Referenced by addAssumeNonNull(), optimizeDivRem(), and rewritePHIsForCleanupPad().
insertBefore()
void Instruction::insertBefore (Instruction * InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
Definition at line 88 of file Instruction.cpp.
References llvm::ilist_node_impl< OptionsT >::getIterator(), getParent(), and insertInto().
Referenced by llvm::changeToCall(), findOrCreatePHIInBlock(), INITIALIZE_PASS(), insertLifetimeMarkersSurroundingCall(), llvm::BPFCoreSharedInfo::insertPassThrough(), moveLCSSAPhis(), performBranchToCommonDestFolding(), rematerializeChain(), replaceGEPIdxWithZero(), rewriteMaterializableInstructions(), sinkInstruction(), splitCallSite(), llvm::JumpThreadingPass::threadGuard(), and llvm::versionCallSite().
insertInto()
BasicBlock::iterator Instruction::insertInto (BasicBlock * ParentBB, SymbolTableList< Instruction >::iterator It)
Inserts an unlinked instruction into ParentBB at position It and returns the iterator of the inserted instruction.
Definition at line 98 of file Instruction.cpp.
References assert(), llvm::BasicBlock::end(), and getParent().
Referenced by buildPartialInvariantUnswitchConditionalBranch(), llvm::CloneBasicBlock(), CloneInstructionsIntoPredecessorBlockAndUpdateSSAUses(), llvm::UnaryOperator::Create(), llvm::BinaryOperator::Create(), createMalloc(), createWrapper(), llvm::FoldReturnIntoUncondBranch(), insertAfter(), insertBefore(), Instruction(), MergeCompatibleInvokesImpl(), performBlockTailMerging(), replaceArgumentUses(), SplitLandingPadPredecessorsImpl(), llvm::JumpThreadingPass::unfoldSelectInstr(), unswitchNontrivialInvariants(), and unswitchTrivialBranch().
isArithmeticShift()
bool llvm::Instruction::isArithmeticShift () const inline
Return true if this is an arithmetic shift right.
Definition at line 214 of file Instruction.h.
References getOpcode().
isAssociative() [1/2]
bool Instruction::isAssociative () const
Return true if the instruction is associative:
Associative operators satisfy: x op (y op z) === (x op y) op z
In LLVM, the Add, Mul, And, Or, and Xor operators are associative.
Definition at line 801 of file Instruction.cpp.
References llvm::FAdd, llvm::FMul, and getOpcode().
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::InstCombinerImpl::foldVectorBinop(), and simplifyAssociativeBinOp().
isAssociative() [2/2]
static bool llvm::Instruction::isAssociative (unsigned Opcode) inline static
Definition at line 566 of file Instruction.h.
References llvm::And, Mul, llvm::Or, and llvm::Xor.
isAtomic()
bool Instruction::isAtomic () const
Return true if this instruction has an AtomicOrdering of unordered or higher.
Definition at line 666 of file Instruction.cpp.
References getOpcode(), llvm::SPII::Load, llvm::NotAtomic, and llvm::SPII::Store.
Referenced by llvm::InstCombinerImpl::combineLoadToNewType(), llvm::InstCombinerImpl::foldPHIArgLoadIntoPHI(), hasAtomicLoad(), hasAtomicStore(), llvm::LoadInst::isSimple(), llvm::StoreInst::isSimple(), llvm::TargetLowering::lowerAtomicLoadAsLoadSDNode(), and llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad().
isBinaryOp() [1/2]
bool llvm::Instruction::isBinaryOp () const inline
Definition at line 173 of file Instruction.h.
References getOpcode(), and isBinaryOp().
Referenced by llvm::ConstantRange::binaryOp(), canCreateUndefOrPoison(), llvm::BinaryConstantExpr::classof(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldFPInstOperands(), llvm::IRBuilderBase::CreateNAryOp(), llvm::ConstantExpr::get(), llvm::ConstantExpr::getBinOpIdentity(), isBinaryOp(), llvm::isSafeToSpeculativelyExecuteWithOpcode(), llvm::ConstantRange::makeGuaranteedNoWrapRegion(), and llvm::ConstantRange::overflowingBinaryOp().
isBinaryOp() [2/2]
static bool llvm::Instruction::isBinaryOp (unsigned Opcode) inline static
Definition at line 195 of file Instruction.h.
isBitwiseLogicOp() [1/2]
bool llvm::Instruction::isBitwiseLogicOp () const inline
Return true if this is and/or/xor.
Definition at line 224 of file Instruction.h.
References getOpcode().
Referenced by llvm::PatternMatch::is_bitwiselogic_op::isOpType(), rightDistributesOverLeft(), and simplifyLogicOfAddSub().
isBitwiseLogicOp() [2/2]
static bool llvm::Instruction::isBitwiseLogicOp (unsigned Opcode) inline static
Determine if the Opcode is and/or/xor.
Definition at line 219 of file Instruction.h.
References llvm::And, llvm::Or, and llvm::Xor.
Referenced by foldBitCastBitwiseLogic(), and simplifyAssocCastAssoc().
isCast() [1/2]
bool llvm::Instruction::isCast () const inline
Definition at line 176 of file Instruction.h.
References getOpcode(), and isCast().
Referenced by llvm::CastConstantExpr::classof(), llvm::ConstantFoldCastOperand(), llvm::ConstantExprKeyType::create(), foldConstantCastPair(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::ConstantExpr::getCast(), isCast(), and llvm::ConstantExpr::isCast().
isCast() [2/2]
static bool llvm::Instruction::isCast (unsigned OpCode) inline static
Determine if the OpCode is one of the CastInst instructions.
Definition at line 229 of file Instruction.h.
isCommutative() [1/2]
bool Instruction::isCommutative () const
Return true if the instruction is commutative:
Commutative operators satisfy: (x op y) === (y op x)
In LLVM, these are the commutative operators, plus SetEQ and SetNE, when applied to any type.
Definition at line 816 of file Instruction.cpp.
References getOpcode().
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), areCommutative(), llvm::ConstantFoldBinaryInstruction(), expandBinOp(), foldOrCommuteConstant(), foldSelectBinOpIdentity(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldVectorBinop(), llvm::ConstantExpr::getBinOpIdentity(), llvm::RISCVTTIImpl::getIntImmCostInst(), rightDistributesOverLeft(), simplifyAssociativeBinOp(), llvm::BinaryOperator::swapOperands(), tryFactorization(), and llvm::InstCombinerImpl::visitShl().
isCommutative() [2/2]
static bool llvm::Instruction::isCommutative (unsigned Opcode) inline static
Definition at line 579 of file Instruction.h.
References llvm::And, llvm::FAdd, llvm::FMul, Mul, llvm::Or, and llvm::Xor.
isDebugOrPseudoInst()
bool Instruction::isDebugOrPseudoInst () const
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
Definition at line 781 of file Instruction.cpp.
Referenced by llvm::findAvailablePtrLoadStore(), and ProcessBlock().
isEHPad()
bool llvm::Instruction::isEHPad () const inline
Return true if the instruction is a variety of EH-block.
Definition at line 685 of file Instruction.h.
References getOpcode().
Referenced by llvm::BasicBlock::canSplitPredecessors(), cloneInstructionInExitBlock(), llvm::colorEHFunclets(), llvm::objcarc::createCallInstWithColors(), llvm::ehAwareSplitEdge(), getEHPadFromPredecessor(), HandleInlinedEHPad(), llvm::insertDebugValuesForPHIs(), llvm::BasicBlock::isEHPad(), isSafeToMove(), isSafeToRemove(), populateEHOperandBundle(), llvm::removeAllNonTerminatorAndEHPadInstructions(), SinkCast(), and llvm::SplitIndirectBrCriticalEdges().
isExact()
bool Instruction::isExact () const
Determine whether the exact flag is set.
Definition at line 245 of file Instruction.cpp.
Referenced by andIRFlags(), buildNew(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpShrConstant(), isNonZeroRecurrence(), llvm::InstModificationIRStrategy::mutate(), narrowSDivOrSRem(), narrowUDivOrURem(), processAShr(), processSDiv(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), and llvm::InstCombinerImpl::visitMul().
isExceptionalTerminator() [1/2]
bool llvm::Instruction::isExceptionalTerminator () const inline
Definition at line 178 of file Instruction.h.
References getOpcode().
Referenced by IsAcceptableTarget(), llvm::JumpThreadingPass::maybeMergeBasicBlockIntoOnlyPred(), and llvm::MergeBlockIntoPredecessor().
isExceptionalTerminator() [2/2]
static bool llvm::Instruction::isExceptionalTerminator (unsigned OpCode) inline static
Returns true if the OpCode is a terminator related to exception handling.
Definition at line 239 of file Instruction.h.
isFast()
bool Instruction::isFast () const
Determine whether all fast-math-flags are set.
Definition at line 299 of file Instruction.cpp.
References assert().
Referenced by llvm::LibCallSimplifier::optimizeCall(), and llvm::InstCombinerImpl::visitCallInst().
isFenceLike()
bool llvm::Instruction::isFenceLike () const inline
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
Definition at line 644 of file Instruction.h.
References llvm::MCID::Call, and getOpcode().
isFuncletPad() [1/2]
bool llvm::Instruction::isFuncletPad () const inline
Definition at line 177 of file Instruction.h.
References getOpcode(), and isFuncletPad().
Referenced by isFuncletPad().
isFuncletPad() [2/2]
static bool llvm::Instruction::isFuncletPad (unsigned OpCode) inline static
Determine if the OpCode is one of the FuncletPadInst instructions.
Definition at line 234 of file Instruction.h.
isIdempotent() [1/2]
bool llvm::Instruction::isIdempotent () const inline
Return true if the instruction is idempotent:
Idempotent operators satisfy: x op x === x
In LLVM, the And and Or operators are idempotent.
Definition at line 596 of file Instruction.h.
References getOpcode(), and isIdempotent().
Referenced by IncorporateWeight(), and isIdempotent().
isIdempotent() [2/2]
static bool llvm::Instruction::isIdempotent (unsigned Opcode) inline static
Definition at line 597 of file Instruction.h.
References llvm::And, and llvm::Or.
isIdenticalTo()
bool Instruction::isIdenticalTo (const Instruction * I) const
Return true if the specified instruction is exactly identical to the current one.
This means that all operands match and any extra information (e.g. load is volatile) agree.
Definition at line 552 of file Instruction.cpp.
References I, isIdenticalToWhenDefined(), and llvm::Value::SubclassOptionalData.
Referenced by TryToMergeLandingPad(), and llvm::InstCombinerImpl::visitFenceInst().
isIdenticalToWhenDefined()
bool Instruction::isIdenticalToWhenDefined (const Instruction * I) const
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
Definition at line 557 of file Instruction.cpp.
References llvm::PHINode::block_begin(), llvm::lltok::equal, llvm::User::getNumOperands(), getOpcode(), llvm::Value::getType(), haveSameSpecialState(), I, llvm::User::op_begin(), and llvm::User::op_end().
Referenced by EliminateDuplicatePHINodesNaiveImpl(), isEqualImpl(), isIdenticalTo(), and llvm::InstCombinerImpl::visitPHINode().
isIntDivRem() [1/2]
bool llvm::Instruction::isIntDivRem () const inline
Definition at line 174 of file Instruction.h.
References getOpcode(), and isIntDivRem().
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombinerImpl::foldVectorBinop(), generateKeySubkey(), isIntDivRem(), isValidForAlternation(), and llvm::InstCombinerImpl::SimplifyDemandedVectorElts().
isIntDivRem() [2/2]
static bool llvm::Instruction::isIntDivRem (unsigned Opcode) inline static
Definition at line 199 of file Instruction.h.
isLaunderOrStripInvariantGroup()
bool Instruction::isLaunderOrStripInvariantGroup () const
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
Definition at line 772 of file Instruction.cpp.
isLifetimeStartOrEnd()
bool Instruction::isLifetimeStartOrEnd () const
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
Definition at line 764 of file Instruction.cpp.
Referenced by llvm::CodeExtractor::findAllocas(), isIntegerWideningViableForSlice(), isUsedByLifetimeMarker(), isVectorPromotionViableForSlice(), onlyUsedByLifetimeMarkersOrDroppableInstsHelper(), and llvm::AMDGPUSimplifyLibCallsPass::run().
isLogicalShift()
bool llvm::Instruction::isLogicalShift () const inline
Return true if this is a logical shift left or a logical shift right.
Definition at line 209 of file Instruction.h.
References getOpcode().
Referenced by canEvaluateShiftedShift().
isNilpotent() [1/2]
bool llvm::Instruction::isNilpotent () const inline
Return true if the instruction is nilpotent:
Nilpotent operators satisfy: x op x === Id,
where Id is the identity for the operator, i.e. a constant such that x op Id === x and Id op x === x for all x.
In LLVM, the Xor operator is nilpotent.
Definition at line 610 of file Instruction.h.
References getOpcode(), and isNilpotent().
Referenced by IncorporateWeight(), and isNilpotent().
isNilpotent() [2/2]
static bool llvm::Instruction::isNilpotent (unsigned Opcode) inline static
Definition at line 611 of file Instruction.h.
References llvm::Xor.
isOnlyUserOfAnyOperand()
bool Instruction::isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
Definition at line 157 of file Instruction.cpp.
References llvm::any_of(), llvm::Value::hasOneUser(), and llvm::User::operands().
isSafeToRemove()
bool Instruction::isSafeToRemove () const
Return true if the instruction can be removed if the result is unused.
When constant folding some instructions cannot be removed even if their results are unused. Specifically terminator instructions and calls that may have side effects cannot be removed without semantically changing the generated program.
Definition at line 749 of file Instruction.cpp.
References isEHPad(), isTerminator(), and mayHaveSideEffects().
isSameOperationAs()
bool Instruction::isSameOperationAs (const Instruction * I, unsigned flags = 0) const
This function determines if the specified instruction executes the same operation as the current one.
This means that the opcodes, type, operand types and any other factors affecting the operation must be the same. This is similar to isIdenticalTo except the operands themselves don't have to be identical.
Returns
true if the specified instruction is the same operation as the current one. Determine if one instruction is the same operation as another.
Definition at line 584 of file Instruction.cpp.
References CompareIgnoringAlignment, CompareUsingScalarTypes, llvm::numbers::e, llvm::User::getNumOperands(), getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), haveSameSpecialState(), i, and I.
Referenced by llvm::InstCombinerImpl::foldSelectOpOp().
isShift() [1/2]
bool llvm::Instruction::isShift () const inline
Definition at line 175 of file Instruction.h.
References getOpcode(), and isShift().
Referenced by detectShiftUntilZeroIdiom(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::InstCombinerImpl::foldVectorBinop(), llvm::PatternMatch::is_shift_op::isOpType(), isShift(), rightDistributesOverLeft(), and llvm::InstCombinerImpl::SimplifyDemandedVectorElts().
isShift() [2/2]
static bool llvm::Instruction::isShift (unsigned Opcode) inline static
Determine if the Opcode is one of the shift instructions.
Definition at line 204 of file Instruction.h.
isTerminator() [1/2]
bool llvm::Instruction::isTerminator () const inline
Definition at line 171 of file Instruction.h.
References getOpcode(), and isTerminator().
Referenced by findLocationForEntrySafepoint(), getInsertionPointAfterDef(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), llvm::isCriticalEdge(), isRemovableWrite(), isSafeToMove(), isSafeToRemove(), isTerminator(), llvm::InstDeleterIRStrategy::mutate(), and llvm::OutlinableRegion::splitCandidate().
isTerminator() [2/2]
static bool llvm::Instruction::isTerminator (unsigned OpCode) inline static
Definition at line 188 of file Instruction.h.
isUnaryOp() [1/2]
bool llvm::Instruction::isUnaryOp () const inline
Definition at line 172 of file Instruction.h.
References getOpcode(), and isUnaryOp().
Referenced by llvm::ConstantFoldUnaryInstruction(), llvm::ConstantFoldUnaryOpOperand(), llvm::IRBuilderBase::CreateNAryOp(), llvm::isSafeToSpeculativelyExecuteWithOpcode(), and isUnaryOp().
isUnaryOp() [2/2]
static bool llvm::Instruction::isUnaryOp (unsigned Opcode) inline static
Definition at line 192 of file Instruction.h.
isUsedOutsideOfBlock()
bool Instruction::isUsedOutsideOfBlock (const BasicBlock * BB) const
Return true if there are any uses of this instruction in blocks other than the specified block.
Note that PHI nodes are considered to evaluate their operands in the corresponding predecessor block.
Definition at line 608 of file Instruction.cpp.
References BB, llvm::PHINode::getIncomingBlock(), I, and llvm::Value::uses().
Referenced by removeEmptyCleanup().
isVolatile()
bool Instruction::isVolatile () const
Return true if this instruction has a volatile memory access.
Definition at line 705 of file Instruction.cpp.
References llvm::MCID::Call, getOpcode(), llvm::SPII::Load, MI, and llvm::SPII::Store.
Referenced by llvm::expandAtomicMemCpyAsLoop(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), and llvm::MemoryDependenceResults::getSimplePointerDependencyFrom().
mayHaveSideEffects()
bool Instruction::mayHaveSideEffects () const
Return true if the instruction may have side effects.
Side effects are:
Writing to memory.
Unwinding.
Not returning (e.g. an infinite loop).
Note that this does not consider malloc and alloca to have side effects because the newly allocated memory is completely invisible to instructions which don't use the returned value. For cases where this matters, isSafeToSpeculativelyExecute may be more appropriate.
Definition at line 745 of file Instruction.cpp.
References mayThrow(), mayWriteToMemory(), and willReturn().
Referenced by canMoveAboveCall(), llvm::deleteDeadLoop(), hasHardUserWithinLoop(), isSafePHIToSpeculate(), isSafeToRemove(), llvm::MergeBlockIntoPredecessor(), and llvm::InstCombinerImpl::visitCallInst().
mayReadFromMemory()
bool Instruction::mayReadFromMemory () const
Return true if this instruction may read memory.
Definition at line 626 of file Instruction.cpp.
References llvm::MCID::Call, getOpcode(), llvm::SPII::Load, and llvm::SPII::Store.
Referenced by GetLocation(), IsAcceptableTarget(), llvm::Dependence::isAnti(), llvm::Dependence::isFlow(), llvm::Dependence::isInput(), and mayReadOrWriteMemory().
mayReadOrWriteMemory()
bool llvm::Instruction::mayReadOrWriteMemory () const inline
Return true if this instruction may read or write memory.
Definition at line 622 of file Instruction.h.
References mayReadFromMemory(), and mayWriteToMemory().
Referenced by llvm::AliasSetTracker::addUnknown(), llvm::AliasSet::aliasesUnknownInst(), and llvm::intersectAccessGroups().
mayThrow()
bool Instruction::mayThrow () const
Return true if this instruction may throw an exception.
Definition at line 735 of file Instruction.cpp.
Referenced by isSafeToMove(), and mayHaveSideEffects().
mayWriteToMemory()
bool Instruction::mayWriteToMemory () const
Return true if this instruction may modify memory.
Definition at line 646 of file Instruction.cpp.
References llvm::MCID::Call, getOpcode(), llvm::SPII::Load, and llvm::SPII::Store.
Referenced by llvm::findAvailablePtrLoadStore(), findInitTrampolineFromBB(), GetLocation(), llvm::Dependence::isAnti(), llvm::Dependence::isFlow(), llvm::Dependence::isOutput(), isSafeToMove(), mayHaveSideEffects(), and mayReadOrWriteMemory().
mergeDIAssignID()
void Instruction::mergeDIAssignID (ArrayRef< const Instruction * > SourceInstructions)
Merge the DIAssignID metadata from this instruction and those attached to instructions in SourceInstructions.
This process performs a RAUW on the MetadataAsValue uses of the merged DIAssignID nodes. Not every instruction in SourceInstructions needs to have DIAssignID metadata. If none of them do then nothing happens. If this instruction does not have a DIAssignID attachment but at least one in SourceInstructions does then the merged one will be attached to it. However, instructions without attachments in SourceInstructions are not modified.
Definition at line 901 of file DebugInfo.cpp.
References assert(), getFunction(), and I.
Referenced by llvm::combineMetadata(), and llvm::InstCombinerImpl::mergeStoreIntoSuccessor().
moveAfter()
void Instruction::moveAfter (Instruction * MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
Definition at line 112 of file Instruction.cpp.
References llvm::ilist_node_impl< OptionsT >::getIterator(), getParent(), and moveBefore().
Referenced by optimizeDivRem(), and rewriteDebugUsers().
moveBefore() [1/2]
void Instruction::moveBefore (BasicBlock & BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
Precondition
I is a valid iterator into BB.
Definition at line 116 of file Instruction.cpp.
References assert(), BB, llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >::getIterator(), getParent(), and I.
moveBefore() [2/2]
void Instruction::moveBefore (Instruction * MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
Definition at line 108 of file Instruction.cpp.
References llvm::ilist_node_impl< OptionsT >::getIterator(), and getParent().
Referenced by llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), llvm::CodeExtractor::extractCodeRegion(), foldConsecutiveLoads(), llvm::InstCombinerImpl::freezeOtherUses(), moveAfter(), NegateValue(), optimizeBranch(), optimizeDivRem(), removeEmptyCleanup(), llvm::coro::salvageDebugInfo(), llvm::setWidenableBranchCond(), simplifyRelocatesOffABase(), SinkInstruction(), sinkLastInstruction(), sinkSpillUsesAfterCoroBegin(), turnGuardIntoBranch(), llvm::UnrollAndJamLoop(), llvm::versionCallSite(), llvm::InstCombinerImpl::visitAllocaInst(), llvm::InstCombinerImpl::visitCallInst(), and llvm::widenWidenableBranch().
operator=()
Instruction& llvm::Instruction::operator= (const Instruction &) delete
removeFromParent()
void Instruction::removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
Definition at line 78 of file Instruction.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< Instruction, Options... >::type >::getIterator(), and getParent().
Referenced by llvm::InstCombinerImpl::matchBSwapOrBitReverse(), rewritePHIsForCleanupPad(), and llvm::JumpThreadingPass::unfoldSelectInstr().
replaceSuccessorWith()
void Instruction::replaceSuccessorWith (BasicBlock * OldBB, BasicBlock * NewBB)
Replace specified successor OldBB to point at the provided block.
This instruction must be a terminator.
Definition at line 859 of file Instruction.cpp.
References getNumSuccessors(), getSuccessor(), and setSuccessor().
Referenced by insertUniqueBackedgeBlock(), and llvm::BasicBlock::splitBasicBlockBefore().
setAAMetadata()
void Instruction::setAAMetadata (const AAMDNodes & N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
Definition at line 1513 of file Metadata.cpp.
References N, and setMetadata().
Referenced by doPromotion(), foldConsecutiveLoads(), llvm::InstCombinerImpl::mergeStoreIntoSuccessor(), llvm::promoteLoopAccessesToScalars(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), speculateSelectInstLoads(), unpackLoadToAggregate(), and unpackStoreToAggregate().
setDebugLoc()
void llvm::Instruction::setDebugLoc (DebugLoc Loc) inline
Set the debug location information for this instruction.
Definition at line 355 of file Instruction.h.
References move.
Referenced by addBoundsChecking(), llvm::changeToInvokeAndSplitBasicBlock(), CloneInstructionsIntoPredecessorBlockAndUpdateSSAUses(), llvm::InnerLoopVectorizer::completeLoopSkeleton(), ConvertShiftToMul(), copyMetadata(), llvm::createCallMatchingInvoke(), createFFSIntrinsic(), llvm::InnerLoopVectorizer::createInductionResumeValue(), createPopcntIntrinsic(), llvm::InnerLoopVectorizer::createVectorLoopSkeleton(), llvm::VPWidenIntOrFpInductionRecipe::execute(), llvm::VPCanonicalIVPHIRecipe::execute(), llvm::VPActiveLaneMaskPHIRecipe::execute(), fixupDebugInfoPostExtraction(), FoldCondBranchOnValueKnownInPredecessorImpl(), llvm::formLCSSAForInstructions(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), INITIALIZE_PASS(), llvm::InlineFunction(), insertCall(), insertUniqueBackedgeBlock(), LowerNegateToMultiply(), llvm::InstCombinerImpl::mergeStoreIntoSuccessor(), OptimizeExtractBits(), performBlockTailMerging(), llvm::InstCombinerImpl::PHIArgMergedDebugLoc(), llvm::JumpThreadingPass::processImpliedCondition(), processSaturatingInst(), llvm::promoteLoopAccessesToScalars(), llvm::removeUnwindEdge(), replaceArgumentUses(), llvm::setProbeDistributionFactor(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), sinkAndCmp0Expression(), SinkCast(), sinkCmpExpression(), SinkShiftAndTruncate(), llvm::BasicBlock::splitBasicBlock(), llvm::BasicBlock::splitBasicBlockBefore(), SplitBlockAndInsertIfThenImpl(), SplitBlockPredecessorsImpl(), splitCallSite(), llvm::SplitKnownCriticalEdge(), SplitLandingPadPredecessorsImpl(), llvm::splitLoopBound(), llvm::JumpThreadingPass::threadEdge(), tryToShorten(), TryToShrinkGlobalToBoolean(), llvm::UnrollRuntimeLoopRemainder(), and updateForIncomingValueLocation().
setFast()
void Instruction::setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 249 of file Instruction.cpp.
References assert(), and B.
Referenced by llvm::InstModificationIRStrategy::mutate().
setFastMathFlags()
void Instruction::setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
See LangRef.html for the meaning of these flags.
Definition at line 289 of file Instruction.cpp.
References assert().
Referenced by CreateAdd(), CreateMul(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InstCombinerImpl::foldSelectOpOp(), foldShuffleOfUnaryOps(), and llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative().
setHasAllowContract()
void Instruction::setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 279 of file Instruction.cpp.
References assert(), and B.
Referenced by llvm::InstModificationIRStrategy::mutate().
setHasAllowReassoc()
void Instruction::setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 254 of file Instruction.cpp.
References assert(), and B.
Referenced by llvm::InstModificationIRStrategy::mutate().
setHasAllowReciprocal()
void Instruction::setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 274 of file Instruction.cpp.
References assert(), and B.
Referenced by llvm::InstModificationIRStrategy::mutate().
setHasApproxFunc()
void Instruction::setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 284 of file Instruction.cpp.
References assert(), and B.
Referenced by llvm::InstModificationIRStrategy::mutate().
setHasNoInfs()
void Instruction::setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 264 of file Instruction.cpp.
References assert(), and B.
Referenced by dropPoisonGeneratingFlags(), foldFNegIntoConstant(), and llvm::InstModificationIRStrategy::mutate().
setHasNoNaNs()
void Instruction::setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 259 of file Instruction.cpp.
References assert(), and B.
Referenced by dropPoisonGeneratingFlags(), and llvm::InstModificationIRStrategy::mutate().
setHasNoSignedWrap()
void Instruction::setHasNoSignedWrap (bool b = true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 165 of file Instruction.cpp.
References b.
Referenced by andIRFlags(), llvm::InstCombinerImpl::commonIDivTransforms(), ConvertShiftToMul(), copyIRFlags(), llvm::BinaryOperator::CreateNSW(), llvm::InstCombinerImpl::Descale(), foldShiftedShift(), llvm::ConstantExpr::getAsInstruction(), llvm::SCEVExpander::hoistIVInc(), llvm::InstModificationIRStrategy::mutate(), NegateValue(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::refineInstruction(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSub().
setHasNoSignedZeros()
void Instruction::setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 269 of file Instruction.cpp.
References assert(), and B.
Referenced by foldFNegIntoConstant(), and llvm::InstModificationIRStrategy::mutate().
setHasNoUnsignedWrap()
void Instruction::setHasNoUnsignedWrap (bool b = true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 161 of file Instruction.cpp.
References b.
Referenced by andIRFlags(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), ConvertShiftToMul(), copyIRFlags(), llvm::BinaryOperator::CreateNUW(), dropPoisonGeneratingFlags(), foldShiftedShift(), llvm::ConstantExpr::getAsInstruction(), llvm::SCEVExpander::hoistIVInc(), llvm::InstModificationIRStrategy::mutate(), NegateValue(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::refineInstruction(), and llvm::InstCombinerImpl::visitMul().
setIsExact()
void Instruction::setIsExact (bool b = true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
See LangRef.html for the meaning of this flag.
Definition at line 169 of file Instruction.cpp.
References b.
Referenced by andIRFlags(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), copyIRFlags(), llvm::BinaryOperator::CreateExact(), foldShiftedShift(), llvm::ConstantExpr::getAsInstruction(), llvm::InstModificationIRStrategy::mutate(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitSDiv(), and llvm::InstCombinerImpl::visitUDiv().
setMetadata() [1/2]
void Instruction::setMetadata (StringRef Kind, MDNode * Node)
Definition at line 1391 of file Metadata.cpp.
setMetadata() [2/2]
void Instruction::setMetadata (unsigned KindID, MDNode * Node)
Set the metadata of the specified kind to the specified node.
This updates or replaces metadata if already present, or removes it if Node is null.
Definition at line 1455 of file Metadata.cpp.
Referenced by AddAliasScopeMetadata(), addAnnotationMetadata(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::annotateValueSite(), llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::combineMetadata(), combineStoreToNewValue(), copyMetadata(), llvm::copyMetadataForLoad(), llvm::copyNonnullMetadata(), llvm::copyRangeMetadata(), llvm::createCallMatchingInvoke(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilderBase::CreateMemSetInline(), llvm::IRBuilderBase::CreateMemTransferInst(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::IRBuilderBase::CreatePreserveStructAccessIndex(), llvm::IRBuilderBase::CreatePreserveUnionAccessIndex(), llvm::SITargetLowering::emitExpandAtomicRMW(), foldCtpop(), foldCttzCtlz(), llvm::InstCombinerImpl::foldPHIArgLoadIntoPHI(), handlePhiDef(), insertUniqueBackedgeBlock(), llvm::ARMTTIImpl::instCombineIntrinsic(), performBranchToCommonDestFolding(), llvm::promoteCall(), llvm::pgo::promoteIndirectCall(), propagateMemProfHelper(), llvm::propagateMetadata(), setAAMetadata(), llvm::setIrrLoopHeaderMetadata(), llvm::setLoopEstimatedTripCount(), llvm::setProfMetadata(), llvm::InstCombinerImpl::SimplifyAnyMemTransfer(), llvm::SplitBlockAndInsertIfThenElse(), SplitBlockAndInsertIfThenImpl(), SplitBlockPredecessorsImpl(), swapProfMetadata(), unswitchNontrivialInvariants(), updatePredecessorProfileMetadata(), llvm::CallInst::updateProfWeight(), and ~Instruction().
setSubclassData()
template<typename BitfieldElement > void llvm::Instruction::setSubclassData (typename BitfieldElement::Type Value) inline protected
Definition at line 874 of file Instruction.h.
setSuccessor()
void Instruction::setSuccessor (unsigned Idx, BasicBlock * BB)
Update the specified successor to point at the provided block.
This instruction must be a terminator.
Definition at line 847 of file Instruction.cpp.
References getOpcode(), and llvm_unreachable.
Referenced by CloneLoopBlocks(), cloneLoopBlocks(), llvm::createMemCpyLoopKnownSize(), replaceSuccessorWith(), llvm::SplitKnownCriticalEdge(), llvm::JumpThreadingPass::threadEdge(), and llvm::JumpThreadingPass::threadThroughTwoBasicBlocks().
swapProfMetadata()
void Instruction::swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
Definition at line 870 of file Instruction.cpp.
References llvm::MDNode::get(), llvm::getBranchWeightMDNode(), llvm::MDNode::getContext(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and setMetadata().
Referenced by llvm::BranchInst::swapSuccessors().
updateLocationAfterHoist()
void Instruction::updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
Note: it is undefined behavior to call this on an instruction not currently inserted into a function.
Definition at line 930 of file DebugInfo.cpp.
user_back() [1/2]
Instruction* llvm::Instruction::user_back () inline
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
Definition at line 87 of file Instruction.h.
References llvm::Value::user_begin().
Referenced by llvm::InstCombinerImpl::Descale(), foldInsSequenceIntoSplat(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::ARMTTIImpl::getCmpSelInstrCost(), isDeadPHICycle(), isNotUsedOrFreeInLoop(), OptimizeGlobalAddressOfAllocation(), promoteSingleBlockAlloca(), replaceExtractElements(), ShouldBreakUpSubtract(), shouldExpandCmpArithRMWInIR(), simplifyAMDGCNImageIntrinsic(), sinkLifetimeStartMarkers(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), llvm::FastISel::tryToFoldLoad(), llvm::InstCombinerImpl::visitPHINode(), llvm::InstCombinerImpl::visitSExt(), and llvm::InstCombinerImpl::visitZExt().
user_back() [2/2]
const Instruction* llvm::Instruction::user_back () const inline
Definition at line 88 of file Instruction.h.
References llvm::Value::user_begin().
willReturn()
bool Instruction::willReturn () const
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
Definition at line 754 of file Instruction.cpp.
References SI.
Referenced by isRemovableWrite(), isSafeToMove(), and mayHaveSideEffects().
Friends And Related Function Documentation
BasicBlock
friend class BasicBlock friend
Various leaf nodes.
Definition at line 846 of file Instruction.h.
SymbolTableListTraits< Instruction >
friend class SymbolTableListTraits< Instruction > friend
Definition at line 845 of file Instruction.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Instruction.h
lib/IR/DebugInfo.cpp
lib/IR/Instruction.cpp
lib/IR/Metadata.cpp