LLVM: llvm::RecurrenceDescriptor::InstDesc Class Reference
llvm::RecurrenceDescriptor::InstDesc Class Reference
This POD struct holds information about a potential recurrence operation.
#include "llvm/Analysis/IVDescriptors.h"
Public Member Functions
InstDesc (bool IsRecur, Instruction *I, Instruction *ExactFP=nullptr)
InstDesc (Instruction *I, RecurKind K, Instruction *ExactFP=nullptr)
bool isRecurrence () const
bool needsExactFPMath () const
Instruction * getExactFPMathInst () const
RecurKind getRecKind () const
Instruction * getPatternInst () const
Detailed Description
This POD struct holds information about a potential recurrence operation.
Definition at line 86 of file IVDescriptors.h.
Constructor & Destructor Documentation
InstDesc() [1/2]
llvm::RecurrenceDescriptor::InstDesc::InstDesc (bool IsRecur, Instruction * I, Instruction * ExactFP = nullptr) inline
Definition at line 88 of file IVDescriptors.h.
InstDesc() [2/2]
llvm::RecurrenceDescriptor::InstDesc::InstDesc (Instruction * I, RecurKind K, Instruction * ExactFP = nullptr) inline
Definition at line 92 of file IVDescriptors.h.
Member Function Documentation
getExactFPMathInst()
Instruction* llvm::RecurrenceDescriptor::InstDesc::getExactFPMathInst () const inline
Definition at line 100 of file IVDescriptors.h.
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), and llvm::RecurrenceDescriptor::isRecurrenceInstr().
getPatternInst()
Instruction* llvm::RecurrenceDescriptor::InstDesc::getPatternInst () const inline
Definition at line 104 of file IVDescriptors.h.
Referenced by llvm::RecurrenceDescriptor::AddReductionVar().
getRecKind()
RecurKind llvm::RecurrenceDescriptor::InstDesc::getRecKind () const inline
Definition at line 102 of file IVDescriptors.h.
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), llvm::RecurrenceDescriptor::isMinMaxPattern(), llvm::RecurrenceDescriptor::isRecurrenceInstr(), and llvm::RecurrenceDescriptor::isSelectCmpPattern().
isRecurrence()
bool llvm::RecurrenceDescriptor::InstDesc::isRecurrence () const inline
Definition at line 96 of file IVDescriptors.h.
Referenced by llvm::RecurrenceDescriptor::AddReductionVar().
needsExactFPMath()
bool llvm::RecurrenceDescriptor::InstDesc::needsExactFPMath () const inline
Definition at line 98 of file IVDescriptors.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/IVDescriptors.h