LLVM: llvm::orc::OrcLoongArch64 Class Reference
llvm::orc::OrcLoongArch64 Class Reference
#include "llvm/ExecutionEngine/Orc/OrcABISupport.h"
Static Public Member Functions
static void writeResolverCode (char *ResolverWorkingMem, JITTargetAddress ResolverTargetAddress, JITTargetAddress ReentryFnAddr, JITTargetAddress ReentryCtxAddr)
Write the resolver code into the given memory.
static void writeTrampolines (char *TrampolineBlockWorkingMem, JITTargetAddress TrampolineBlockTargetAddress, JITTargetAddress ResolverFnAddr, unsigned NumTrampolines)
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
static void writeIndirectStubsBlock (char *StubsBlockWorkingMem, JITTargetAddress StubsBlockTargetAddress, JITTargetAddress PointersBlockTargetAddress, unsigned NumStubs)
Write NumStubs indirect stubs to working memory at StubsBlockWorkingMem.
Static Public Attributes
static constexpr unsigned PointerSize = 8
static constexpr unsigned TrampolineSize = 16
static constexpr unsigned StubSize = 16
static constexpr unsigned StubToPointerMaxDisplacement = 1 << 31
static constexpr unsigned ResolverCodeSize = 0xc8
Detailed Description
Definition at line 375 of file OrcABISupport.h.
Member Function Documentation
writeIndirectStubsBlock()
void llvm::orc::OrcLoongArch64::writeIndirectStubsBlock (char * StubsBlockWorkingMem, JITTargetAddress StubsBlockTargetAddress, JITTargetAddress PointersBlockTargetAddress, unsigned NumStubs) static
Write NumStubs indirect stubs to working memory at StubsBlockWorkingMem.
Stubs will be written as if linked at StubsBlockTargetAddress, with the Nth stub using the Nth pointer in memory starting at PointersBlockTargetAddress.
Definition at line 1183 of file OrcABISupport.cpp.
References assert(), llvm::dbgs(), llvm::formatv(), I, LLVM_DEBUG, PointerSize, StubSize, and uint64_t.
writeResolverCode()
void llvm::orc::OrcLoongArch64::writeResolverCode (char * ResolverWorkingMem, JITTargetAddress ResolverTargetAddress, JITTargetAddress ReentryFnAddr, JITTargetAddress ReentryCtxAddr) static
Write the resolver code into the given memory.
The user is responsible for allocating the memory and setting permissions.
ReentryFnAddr should be the address of a function whose signature matches void* (*)(void *TrampolineAddr, void *ReentryCtxAddr). The ReentryCtxAddr argument of writeResolverCode will be passed as the second argument to the function at ReentryFnAddr.
Definition at line 1080 of file OrcABISupport.cpp.
References llvm::dbgs(), llvm::formatv(), LLVM_DEBUG, memcpy(), and uint64_t.
writeTrampolines()
void llvm::orc::OrcLoongArch64::writeTrampolines (char * TrampolineBlockWorkingMem, JITTargetAddress TrampolineBlockTargetAddress, JITTargetAddress ResolverFnAddr, unsigned NumTrampolines) static
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
Definition at line 1153 of file OrcABISupport.cpp.
References llvm::alignTo(), llvm::dbgs(), llvm::formatv(), I, LLVM_DEBUG, memcpy(), TrampolineSize, and uint64_t.
Member Data Documentation
PointerSize
constexpr unsigned llvm::orc::OrcLoongArch64::PointerSize = 8 static constexpr
Definition at line 377 of file OrcABISupport.h.
Referenced by writeIndirectStubsBlock().
ResolverCodeSize
constexpr unsigned llvm::orc::OrcLoongArch64::ResolverCodeSize = 0xc8 static constexpr
Definition at line 381 of file OrcABISupport.h.
StubSize
constexpr unsigned llvm::orc::OrcLoongArch64::StubSize = 16 static constexpr
Definition at line 379 of file OrcABISupport.h.
Referenced by writeIndirectStubsBlock().
StubToPointerMaxDisplacement
constexpr unsigned llvm::orc::OrcLoongArch64::StubToPointerMaxDisplacement = 1 << 31 static constexpr
Definition at line 380 of file OrcABISupport.h.
TrampolineSize
constexpr unsigned llvm::orc::OrcLoongArch64::TrampolineSize = 16 static constexpr
Definition at line 378 of file OrcABISupport.h.
Referenced by writeTrampolines().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/OrcABISupport.h
lib/ExecutionEngine/Orc/OrcABISupport.cpp