LLVM: llvm::WebAssemblyFunctionInfo Class Reference
llvm::WebAssemblyFunctionInfo Class Reference final
This class is derived from MachineFunctionInfo and contains private WebAssembly-specific information for each MachineFunction.
#include "Target/WebAssembly/WebAssemblyMachineFunctionInfo.h"
Public Member Functions
WebAssemblyFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
~WebAssemblyFunctionInfo () override
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
void initializeBaseYamlFields (MachineFunction &MF, const yaml::WebAssemblyFunctionInfo &YamlMFI)
void addParam (MVT VT)
const std::vector< MVT > & getParams () const
void addResult (MVT VT)
const std::vector< MVT > & getResults () const
void clearParamsAndResults ()
void setNumLocals (size_t NumLocals)
void setLocal (size_t i, MVT VT)
void addLocal (MVT VT)
const std::vector< MVT > & getLocals () const
unsigned getVarargBufferVreg () const
void setVarargBufferVreg (unsigned Reg)
unsigned getBasePointerVreg () const
void setFrameBaseVreg (unsigned Reg)
unsigned getFrameBaseVreg () const
void clearFrameBaseVreg ()
bool isFrameBaseVirtual () const
void setFrameBaseLocal (unsigned Local)
unsigned getFrameBaseLocal () const
void setBasePointerVreg (unsigned Reg)
void stackifyVReg (MachineRegisterInfo &MRI, unsigned VReg)
void unstackifyVReg (unsigned VReg)
bool isVRegStackified (unsigned VReg) const
void initWARegs (MachineRegisterInfo &MRI)
void setWAReg (unsigned VReg, unsigned WAReg)
unsigned getWAReg (unsigned VReg) const
bool isCFGStackified () const
void setCFGStackified (bool Value=true)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Static Public Member Functions
static unsigned getWARegStackId (unsigned Reg)
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Static Public Attributes
static const unsigned UnusedReg = -1u
Detailed Description
This class is derived from MachineFunctionInfo and contains private WebAssembly-specific information for each MachineFunction.
Definition at line 33 of file WebAssemblyMachineFunctionInfo.h.
Constructor & Destructor Documentation
WebAssemblyFunctionInfo()
llvm::WebAssemblyFunctionInfo::WebAssemblyFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline explicit
Definition at line 68 of file WebAssemblyMachineFunctionInfo.h.
~WebAssemblyFunctionInfo()
WebAssemblyFunctionInfo::~WebAssemblyFunctionInfo () override default
Member Function Documentation
addLocal()
void llvm::WebAssemblyFunctionInfo::addLocal (MVT VT) inline
Definition at line 93 of file WebAssemblyMachineFunctionInfo.h.
Referenced by llvm::WebAssemblyFrameLowering::getLocalForStackObject().
addParam()
void llvm::WebAssemblyFunctionInfo::addParam (MVT VT) inline
Definition at line 80 of file WebAssemblyMachineFunctionInfo.h.
addResult()
void llvm::WebAssemblyFunctionInfo::addResult (MVT VT) inline
Definition at line 83 of file WebAssemblyMachineFunctionInfo.h.
References Results.
clearFrameBaseVreg()
void llvm::WebAssemblyFunctionInfo::clearFrameBaseVreg () inline
Definition at line 111 of file WebAssemblyMachineFunctionInfo.h.
clearParamsAndResults()
void llvm::WebAssemblyFunctionInfo::clearParamsAndResults () inline
Definition at line 86 of file WebAssemblyMachineFunctionInfo.h.
References Results.
clone()
MachineFunctionInfo * WebAssemblyFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 27 of file WebAssemblyMachineFunctionInfo.cpp.
References llvm::MachineFunction::cloneInfo().
getBasePointerVreg()
unsigned llvm::WebAssemblyFunctionInfo::getBasePointerVreg () const inline
Definition at line 102 of file WebAssemblyMachineFunctionInfo.h.
References assert().
Referenced by llvm::WebAssemblyFrameLowering::emitEpilogue().
getFrameBaseLocal()
unsigned llvm::WebAssemblyFunctionInfo::getFrameBaseLocal () const inline
Definition at line 115 of file WebAssemblyMachineFunctionInfo.h.
References assert().
Referenced by llvm::WebAssemblyFrameLowering::getDwarfFrameBase().
getFrameBaseVreg()
unsigned llvm::WebAssemblyFunctionInfo::getFrameBaseVreg () const inline
Definition at line 107 of file WebAssemblyMachineFunctionInfo.h.
References assert().
Referenced by checkFrameBase(), and llvm::WebAssemblyRegisterInfo::getFrameRegister().
getLocals()
const std::vector<MVT>& llvm::WebAssemblyFunctionInfo::getLocals () const inline
Definition at line 94 of file WebAssemblyMachineFunctionInfo.h.
Referenced by llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), and llvm::WebAssemblyFrameLowering::getLocalForStackObject().
getParams()
const std::vector<MVT>& llvm::WebAssemblyFunctionInfo::getParams () const inline
Definition at line 81 of file WebAssemblyMachineFunctionInfo.h.
Referenced by llvm::WebAssemblyFrameLowering::getLocalForStackObject(), and llvm::yaml::WebAssemblyFunctionInfo::WebAssemblyFunctionInfo().
getResults()
const std::vector<MVT>& llvm::WebAssemblyFunctionInfo::getResults () const inline
Definition at line 84 of file WebAssemblyMachineFunctionInfo.h.
References Results.
Referenced by llvm::yaml::WebAssemblyFunctionInfo::WebAssemblyFunctionInfo().
getVarargBufferVreg()
unsigned llvm::WebAssemblyFunctionInfo::getVarargBufferVreg () const inline
Definition at line 96 of file WebAssemblyMachineFunctionInfo.h.
References assert().
getWAReg()
unsigned llvm::WebAssemblyFunctionInfo::getWAReg (unsigned VReg) const inline
Definition at line 149 of file WebAssemblyMachineFunctionInfo.h.
References assert(), I, and llvm::Register::virtReg2Index().
Referenced by llvm::WebAssemblyMCInstLower::lower(), and llvm::WebAssemblyAsmPrinter::regToString().
getWARegStackId()
static unsigned llvm::WebAssemblyFunctionInfo::getWARegStackId (unsigned Reg) inline static
Definition at line 156 of file WebAssemblyMachineFunctionInfo.h.
References assert().
Referenced by llvm::WebAssemblyInstPrinter::printOperand().
initializeBaseYamlFields()
void WebAssemblyFunctionInfo::initializeBaseYamlFields (MachineFunction & MF, const yaml::WebAssemblyFunctionInfo & YamlMFI)
Definition at line 154 of file WebAssemblyMachineFunctionInfo.cpp.
References llvm::yaml::WebAssemblyFunctionInfo::CFGStackified, llvm::MachineFunction::getBlockNumbered(), llvm::MachineFunction::getWasmEHFuncInfo(), llvm::yaml::WebAssemblyFunctionInfo::Params, llvm::WebAssembly::parseMVT(), llvm::yaml::WebAssemblyFunctionInfo::Results, and llvm::yaml::WebAssemblyFunctionInfo::SrcToUnwindDest.
initWARegs()
void WebAssemblyFunctionInfo::initWARegs (MachineRegisterInfo & MRI)
Definition at line 36 of file WebAssemblyMachineFunctionInfo.cpp.
References assert(), llvm::MachineRegisterInfo::getNumVirtRegs(), MRI, and UnusedReg.
isCFGStackified()
bool llvm::WebAssemblyFunctionInfo::isCFGStackified () const inline
Definition at line 161 of file WebAssemblyMachineFunctionInfo.h.
isFrameBaseVirtual()
bool llvm::WebAssemblyFunctionInfo::isFrameBaseVirtual () const inline
Definition at line 113 of file WebAssemblyMachineFunctionInfo.h.
Referenced by checkFrameBase(), and llvm::WebAssemblyFrameLowering::getDwarfFrameBase().
isVRegStackified()
bool llvm::WebAssemblyFunctionInfo::isVRegStackified (unsigned VReg) const inline
Definition at line 135 of file WebAssemblyMachineFunctionInfo.h.
References I, llvm::BitVector::size(), llvm::BitVector::test(), and llvm::Register::virtReg2Index().
Referenced by llvm::WebAssemblyInstrInfo::commuteInstructionImpl(), findStartOfTree(), llvm::WebAssembly::isChild(), oneUseDominatesOtherUses(), and llvm::WebAssemblyAsmPrinter::regToString().
setBasePointerVreg()
void llvm::WebAssemblyFunctionInfo::setBasePointerVreg (unsigned Reg) inline
Definition at line 119 of file WebAssemblyMachineFunctionInfo.h.
setCFGStackified()
void llvm::WebAssemblyFunctionInfo::setCFGStackified (bool Value = true) inline
Definition at line 162 of file WebAssemblyMachineFunctionInfo.h.
setFrameBaseLocal()
void llvm::WebAssemblyFunctionInfo::setFrameBaseLocal (unsigned Local) inline
Definition at line 114 of file WebAssemblyMachineFunctionInfo.h.
Referenced by checkFrameBase().
setFrameBaseVreg()
void llvm::WebAssemblyFunctionInfo::setFrameBaseVreg (unsigned Reg) inline
Definition at line 106 of file WebAssemblyMachineFunctionInfo.h.
setLocal()
void llvm::WebAssemblyFunctionInfo::setLocal (size_t i, MVT VT) inline
Definition at line 92 of file WebAssemblyMachineFunctionInfo.h.
References i.
setNumLocals()
void llvm::WebAssemblyFunctionInfo::setNumLocals (size_t NumLocals) inline
Definition at line 91 of file WebAssemblyMachineFunctionInfo.h.
References llvm::MVT::i32.
setVarargBufferVreg()
void llvm::WebAssemblyFunctionInfo::setVarargBufferVreg (unsigned Reg) inline
Definition at line 100 of file WebAssemblyMachineFunctionInfo.h.
setWAReg()
void llvm::WebAssemblyFunctionInfo::setWAReg (unsigned VReg, unsigned WAReg) inline
Definition at line 143 of file WebAssemblyMachineFunctionInfo.h.
References assert(), I, UnusedReg, and llvm::Register::virtReg2Index().
stackifyVReg()
void llvm::WebAssemblyFunctionInfo::stackifyVReg (MachineRegisterInfo & MRI, unsigned VReg) inline
Definition at line 123 of file WebAssemblyMachineFunctionInfo.h.
References assert(), I, MRI, llvm::BitVector::resize(), llvm::BitVector::set(), llvm::BitVector::size(), and llvm::Register::virtReg2Index().
Referenced by maybeRewriteToDrop(), moveAndTeeForMultiUse(), moveForSingleUse(), and rematerializeCheapDef().
unstackifyVReg()
void llvm::WebAssemblyFunctionInfo::unstackifyVReg (unsigned VReg) inline
Definition at line 130 of file WebAssemblyMachineFunctionInfo.h.
References I, llvm::BitVector::reset(), llvm::BitVector::size(), and llvm::Register::virtReg2Index().
Member Data Documentation
UnusedReg
const unsigned llvm::WebAssemblyFunctionInfo::UnusedReg = -1u static
Definition at line 121 of file WebAssemblyMachineFunctionInfo.h.
Referenced by initWARegs(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::WebAssemblyInstPrinter::printRegName(), llvm::WebAssemblyAsmPrinter::regToString(), and setWAReg().
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.h
lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.cpp