LLVM: llvm::logicalview::LVPatterns Class Reference
llvm::logicalview::LVPatterns Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVOptions.h"
Public Member Functions
LVPatterns ()
LVPatterns (const LVPatterns &)=delete
LVPatterns & operator= (const LVPatterns &)=delete
~LVPatterns ()=default
void clear ()
void addRequest (LVElementKindSet &Selection)
void addRequest (LVLineKindSet &Selection)
void addRequest (LVScopeKindSet &Selection)
void addRequest (LVSymbolKindSet &Selection)
void addRequest (LVTypeKindSelection &Selection)
void updateReportOptions ()
bool matchPattern (StringRef Input, const LVMatchInfo &MatchInfo)
bool matchGenericPattern (StringRef Input)
bool matchOffsetPattern (LVOffset Offset)
void resolvePatternMatch (LVLine *Line)
void resolvePatternMatch (LVScope *Scope)
void resolvePatternMatch (LVSymbol *Symbol)
void resolvePatternMatch (LVType *Type)
void addPatterns (StringSet<> &Patterns, LVMatchInfo &Filters)
void addGenericPatterns (StringSet<> &Patterns)
void addOffsetPatterns (const LVOffsetSet &Patterns)
bool printElement (const LVLine *Line) const
bool printObject (const LVLocation *Location) const
bool printElement (const LVScope *Scope) const
bool printElement (const LVSymbol *Symbol) const
bool printElement (const LVType *Type) const
void print (raw_ostream &OS) const
void dump () const
Static Public Member Functions
static LVPatterns * getPatterns ()
Detailed Description
Definition at line 448 of file LVOptions.h.
Constructor & Destructor Documentation
LVPatterns() [1/2]
llvm::logicalview::LVPatterns::LVPatterns () inline
Definition at line 551 of file LVOptions.h.
References llvm::logicalview::LVLine::getDispatch(), llvm::logicalview::LVType::getDispatch(), llvm::logicalview::LVSymbol::getDispatch(), llvm::logicalview::LVScope::getDispatch(), and llvm::logicalview::LVElement::getDispatch().
LVPatterns() [2/2]
llvm::logicalview::LVPatterns::LVPatterns (const LVPatterns &) delete
~LVPatterns()
llvm::logicalview::LVPatterns::~LVPatterns () default
Member Function Documentation
addGenericPatterns()
void LVPatterns::addGenericPatterns (StringSet<> & Patterns)
Definition at line 439 of file LVOptions.cpp.
References addPatterns(), and llvm::logicalview::options().
Referenced by llvm::logicalview::LVReader::doLoad().
addOffsetPatterns()
void LVPatterns::addOffsetPatterns (const LVOffsetSet & Patterns)
Definition at line 447 of file LVOptions.cpp.
Referenced by llvm::logicalview::LVReader::doLoad().
addPatterns()
void LVPatterns::addPatterns (StringSet<> & Patterns, LVMatchInfo & Filters)
Definition at line 456 of file LVOptions.cpp.
References llvm::logicalview::options().
Referenced by addGenericPatterns().
addRequest() [1/5]
void llvm::logicalview::LVPatterns::addRequest (LVElementKindSet & Selection) inline
Definition at line 577 of file LVOptions.h.
References Selection.
addRequest() [2/5]
void llvm::logicalview::LVPatterns::addRequest (LVLineKindSet & Selection) inline
Definition at line 580 of file LVOptions.h.
References Selection.
addRequest() [3/5]
void llvm::logicalview::LVPatterns::addRequest (LVScopeKindSet & Selection) inline
Definition at line 583 of file LVOptions.h.
References Selection.
addRequest() [4/5]
void llvm::logicalview::LVPatterns::addRequest (LVSymbolKindSet & Selection) inline
Definition at line 586 of file LVOptions.h.
References Selection.
addRequest() [5/5]
void llvm::logicalview::LVPatterns::addRequest (LVTypeKindSelection & Selection) inline
Definition at line 589 of file LVOptions.h.
References Selection.
clear()
void llvm::logicalview::LVPatterns::clear () inline
Definition at line 563 of file LVOptions.h.
References llvm::logicalview::options().
dump()
void llvm::logicalview::LVPatterns::dump () const inline
Definition at line 636 of file LVOptions.h.
References llvm::dbgs(), and print().
getPatterns()
LVPatterns * LVPatterns::getPatterns () static
Definition at line 403 of file LVOptions.cpp.
Referenced by llvm::logicalview::patterns().
matchGenericPattern()
bool llvm::logicalview::LVPatterns::matchGenericPattern (StringRef Input) inline
Definition at line 597 of file LVOptions.h.
References matchPattern().
matchOffsetPattern()
bool llvm::logicalview::LVPatterns::matchOffsetPattern (LVOffset Offset) inline
Definition at line 600 of file LVOptions.h.
References llvm::is_contained().
matchPattern()
bool LVPatterns::matchPattern (StringRef Input, const LVMatchInfo & MatchInfo)
Definition at line 506 of file LVOptions.cpp.
References llvm::StringRef::empty(), llvm::StringRef::equals(), llvm::StringRef::equals_insensitive(), and llvm::Match.
Referenced by matchGenericPattern().
operator=()
LVPatterns& llvm::logicalview::LVPatterns::operator= (const LVPatterns &) delete
print()
void LVPatterns::print (raw_ostream & OS) const
Definition at line 576 of file LVOptions.cpp.
References llvm::dbgs(), LLVM_DEBUG, and OS.
Referenced by dump().
printElement() [1/4]
bool LVPatterns::printElement (const LVLine * Line) const
Definition at line 533 of file LVOptions.cpp.
References llvm::logicalview::Line, and llvm::logicalview::options().
Referenced by llvm::logicalview::LVReader::doPrintLine(), llvm::logicalview::LVReader::doPrintScope(), llvm::logicalview::LVReader::doPrintSymbol(), and llvm::logicalview::LVReader::doPrintType().
printElement() [2/4]
bool LVPatterns::printElement (const LVScope * Scope) const
Definition at line 548 of file LVOptions.cpp.
References llvm::logicalview::options().
printElement() [3/4]
bool LVPatterns::printElement (const LVSymbol * Symbol) const
Definition at line 562 of file LVOptions.cpp.
References llvm::logicalview::options().
printElement() [4/4]
bool LVPatterns::printElement (const LVType * Type) const
Definition at line 569 of file LVOptions.cpp.
References llvm::logicalview::options().
printObject()
bool LVPatterns::printObject (const LVLocation * Location) const
Definition at line 538 of file LVOptions.cpp.
References llvm::logicalview::Location, and llvm::logicalview::options().
Referenced by llvm::logicalview::LVReader::doPrintLocation().
resolvePatternMatch() [1/4]
void llvm::logicalview::LVPatterns::resolvePatternMatch (LVLine * Line) inline
Definition at line 604 of file LVOptions.h.
References llvm::logicalview::Line.
Referenced by llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVType::resolveName(), llvm::logicalview::LVSymbol::resolveName(), and llvm::logicalview::LVScope::resolveName().
resolvePatternMatch() [2/4]
void llvm::logicalview::LVPatterns::resolvePatternMatch (LVScope * Scope) inline
Definition at line 608 of file LVOptions.h.
resolvePatternMatch() [3/4]
void llvm::logicalview::LVPatterns::resolvePatternMatch (LVSymbol * Symbol) inline
Definition at line 612 of file LVOptions.h.
resolvePatternMatch() [4/4]
void llvm::logicalview::LVPatterns::resolvePatternMatch (LVType * Type) inline
Definition at line 616 of file LVOptions.h.
updateReportOptions()
void LVPatterns::updateReportOptions ()
Definition at line 490 of file LVOptions.cpp.
References llvm::logicalview::options().
Referenced by llvm::logicalview::LVReader::doLoad().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVOptions.h
lib/DebugInfo/LogicalView/Core/LVOptions.cpp