LLVM: llvm::DIEAddrOffset Class Reference
llvm::DIEAddrOffset Class Reference
A BaseTypeRef DIE.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEAddrOffset (uint64_t Idx, const MCSymbol *Hi, const MCSymbol *Lo)
void emitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit label value.
unsigned sizeOf (const dwarf::FormParams &FormParams, dwarf::Form Form) const
void print (raw_ostream &O) const
Detailed Description
A BaseTypeRef DIE.
Definition at line 350 of file DIE.h.
Constructor & Destructor Documentation
DIEAddrOffset()
llvm::DIEAddrOffset::DIEAddrOffset (uint64_t Idx, const MCSymbol * Hi, const MCSymbol * Lo) inline explicit
Definition at line 355 of file DIE.h.
References Addr.
Member Function Documentation
emitValue()
void DIEAddrOffset::emitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit label value.
Definition at line 863 of file DIE.cpp.
References llvm::DIEInteger::emitValue(), and llvm::DIEDelta::emitValue().
print()
LLVM_DUMP_METHOD void DIEAddrOffset::print (raw_ostream & O) const
Definition at line 869 of file DIE.cpp.
References llvm::RISCVFenceField::O, llvm::DIEInteger::print(), and llvm::DIEDelta::print().
sizeOf()
unsigned DIEAddrOffset::sizeOf (const dwarf::FormParams & FormParams, dwarf::Form Form) const
Definition at line 855 of file DIE.cpp.
References llvm::DIEInteger::sizeOf(), and llvm::DIEDelta::sizeOf().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp