LLVM: llvm::ARMInstPrinter Class Reference
llvm::ARMInstPrinter Class Reference
#include "Target/ARM/MCTargetDesc/ARMInstPrinter.h"
Public Member Functions
ARMInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
bool applyTargetSpecificCLOption (StringRef Opt) override
Customize the printer according to a command line option.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printRegName (raw_ostream &OS, MCRegister Reg) const override
Print the assembler register name.
std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI) override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
virtual bool printAliasInstr (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
virtual void printCustomAliasOperand (const MCInst *MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printOperand (const MCInst *MI, uint64_t Address, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printSORegRegOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printSORegImmOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAddrModeTBB (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAddrModeTBH (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAddrMode2Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAM2PostIndexOp (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAM2PreOrOffsetIndexOp (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAddrMode2OffsetOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printAddrMode3Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAddrMode3OffsetOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAM3PreOrOffsetIndexOp (const MCInst *MI, unsigned Op, raw_ostream &O, bool AlwaysPrintImm0)
void printPostIdxImm8Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printPostIdxRegOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printPostIdxImm8s4Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printLdStmModeOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printAddrMode5Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printAddrMode5FP16Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAddrMode6Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAddrMode7Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printAddrMode6OffsetOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printBitfieldInvMaskImmOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printMemBOption (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printInstSyncBOption (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printTraceSyncBOption (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printShiftImmOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printPKHLSLShiftImm (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printPKHASRShiftImm (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<unsigned scale>
void printAdrLabelOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<unsigned scale>
void printAdrLabelOperand (const MCInst *MI, uint64_t, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbS4ImmOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbSRImm (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbITMask (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbAddrModeRROperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbAddrModeImm5SOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O, unsigned Scale)
void printThumbAddrModeImm5S1Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbAddrModeImm5S2Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbAddrModeImm5S4Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbAddrModeSPOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printT2SOOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printAddrModeImm12Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printT2AddrModeImm8Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<bool AlwaysPrintImm0>
void printT2AddrModeImm8s4Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printT2AddrModeImm0_1020s4Operand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printT2AddrModeImm8OffsetOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printT2AddrModeImm8s4OffsetOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printT2AddrModeSoRegOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printSetendOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printCPSIMod (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printCPSIFlag (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printMSRMaskOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printBankedRegOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printPredicateOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printMandatoryPredicateOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printMandatoryRestrictedPredicateOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printMandatoryInvertedPredicateOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printSBitModifierOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printRegisterList (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printNoHashImmediate (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printPImmediate (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printCImmediate (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printCoprocOptionImm (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printFPImmOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVMOVModImmOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printImmPlusOneOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printRotImmOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printModImmOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printGPRPairOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printPCLabel (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbLdrLabelOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printThumbLdrLabelOperand (const MCInst *MI, uint64_t, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printFBits16 (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printFBits32 (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorIndex (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListOne (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListTwo (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListTwoSpaced (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListThree (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListFour (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListOneAllLanes (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListTwoAllLanes (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListThreeAllLanes (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListFourAllLanes (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListTwoSpacedAllLanes (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListThreeSpacedAllLanes (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListFourSpacedAllLanes (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListThreeSpaced (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVectorListFourSpaced (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<unsigned NumRegs>
void printMVEVectorList (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<int64_t Angle, int64_t Remainder>
void printComplexRotationOp (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVPTPredicateOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printVPTMask (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
template<int shift>
void printMveAddrModeRQOperand (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
void printMveSaturateOp (const MCInst *MI, unsigned OpNum, const MCSubtargetInfo &STI, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg, unsigned AltIdx=ARM::NoRegAltName)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
Detailed Description
Definition at line 21 of file ARMInstPrinter.h.
Constructor & Destructor Documentation
ARMInstPrinter()
ARMInstPrinter::ARMInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI)
Definition at line 72 of file ARMInstPrinter.cpp.
Member Function Documentation
applyTargetSpecificCLOption()
bool ARMInstPrinter::applyTargetSpecificCLOption (StringRef Opt) override virtual
Customize the printer according to a command line option.
Returns
true if the option is recognized and applied.
Reimplemented from llvm::MCInstPrinter.
Definition at line 76 of file ARMInstPrinter.cpp.
getMnemonic()
std::pair<const char *, uint64_t> llvm::ARMInstPrinter::getMnemonic (const MCInst * MI) override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
getRegisterName()
static const char* llvm::ARMInstPrinter::getRegisterName (MCRegister Reg, unsigned AltIdx = ARM::NoRegAltName) static
Referenced by llvm::ARMAsmPrinter::PrintAsmMemoryOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), and printRegName().
printAddrMode2OffsetOperand()
void ARMInstPrinter::printAddrMode2OffsetOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 505 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM2Offset(), llvm::ARM_AM::getAM2Op(), llvm::ARM_AM::getAM2ShiftOpc(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, printRegImmShift(), printRegName(), and llvm::MCInstPrinter::UseMarkup.
printAddrMode2Operand()
void ARMInstPrinter::printAddrMode2Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 486 of file ARMInstPrinter.cpp.
References assert(), llvm::ARM_AM::getAM2IdxMode(), llvm::MCOperand::getImm(), llvm::ARMII::IndexModePost, llvm::MCOperand::isReg(), MI, llvm::RISCVFenceField::O, printAM2PreOrOffsetIndexOp(), and printOperand().
printAddrMode3OffsetOperand()
void ARMInstPrinter::printAddrMode3OffsetOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 575 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM3Offset(), llvm::ARM_AM::getAM3Op(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printRegName().
printAddrMode3Operand()
template<bool AlwaysPrintImm0> void ARMInstPrinter::printAddrMode3Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 560 of file ARMInstPrinter.cpp.
References assert(), llvm::ARM_AM::getAM3IdxMode(), llvm::ARMII::IndexModePost, llvm::MCOperand::isReg(), MI, llvm::RISCVFenceField::O, printAM3PreOrOffsetIndexOp(), and printOperand().
printAddrMode5FP16Operand()
template<bool AlwaysPrintImm0> void ARMInstPrinter::printAddrMode5FP16Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 673 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM5FP16Offset(), llvm::ARM_AM::getAM5FP16Op(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, printOperand(), printRegName(), and llvm::ARM_AM::sub.
printAddrMode5Operand()
template<bool AlwaysPrintImm0> void ARMInstPrinter::printAddrMode5Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 649 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM5Offset(), llvm::ARM_AM::getAM5Op(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, printOperand(), printRegName(), and llvm::ARM_AM::sub.
printAddrMode6OffsetOperand()
void ARMInstPrinter::printAddrMode6OffsetOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 723 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getReg(), MI, llvm::RISCVFenceField::O, and printRegName().
printAddrMode6Operand()
void ARMInstPrinter::printAddrMode6Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 700 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printRegName().
printAddrMode7Operand()
void ARMInstPrinter::printAddrMode7Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 714 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printRegName().
printAddrModeImm12Operand()
template<bool AlwaysPrintImm0> void ARMInstPrinter::printAddrModeImm12Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1175 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, printOperand(), and printRegName().
printAddrModeTBB()
void ARMInstPrinter::printAddrModeTBB (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 462 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printRegName().
printAddrModeTBH()
void ARMInstPrinter::printAddrModeTBH (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 474 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printRegName().
printAdrLabelOperand() [1/2]
template<unsigned scale> void llvm::ARMInstPrinter::printAdrLabelOperand (const MCInst * MI, uint64_t , unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) inline
Definition at line 116 of file ARMInstPrinter.h.
References MI, and llvm::RISCVFenceField::O.
printAdrLabelOperand() [2/2]
template<unsigned scale> void ARMInstPrinter::printAdrLabelOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1034 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::isExpr(), llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, llvm::MCExpr::print(), and scale().
printAliasInstr()
virtual bool llvm::ARMInstPrinter::printAliasInstr (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O) virtual
Referenced by printInst().
printAM2PostIndexOp()
void llvm::ARMInstPrinter::printAM2PostIndexOp (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
printAM2PreOrOffsetIndexOp()
void ARMInstPrinter::printAM2PreOrOffsetIndexOp (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 433 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM2Offset(), llvm::ARM_AM::getAM2Op(), llvm::ARM_AM::getAM2ShiftOpc(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, printRegImmShift(), printRegName(), and llvm::MCInstPrinter::UseMarkup.
Referenced by printAddrMode2Operand().
printAM3PreOrOffsetIndexOp()
void ARMInstPrinter::printAM3PreOrOffsetIndexOp (const MCInst * MI, unsigned Op, raw_ostream & O, bool AlwaysPrintImm0)
Definition at line 531 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAddrOpcStr(), llvm::ARM_AM::getAM3Offset(), llvm::ARM_AM::getAM3Op(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, op, printRegName(), and llvm::ARM_AM::sub.
Referenced by printAddrMode3Operand().
printBankedRegOperand()
void ARMInstPrinter::printBankedRegOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 944 of file ARMInstPrinter.cpp.
References assert(), MI, and llvm::RISCVFenceField::O.
printBitfieldInvMaskImmOperand()
void ARMInstPrinter::printBitfieldInvMaskImmOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 736 of file ARMInstPrinter.cpp.
References assert(), llvm::bit_width(), llvm::countr_zero(), llvm::MCOperand::getImm(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printCImmediate()
void ARMInstPrinter::printCImmediate (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1016 of file ARMInstPrinter.cpp.
References MI, and llvm::RISCVFenceField::O.
printComplexRotationOp()
template<int64_t Angle, int64_t Remainder> void ARMInstPrinter::printComplexRotationOp (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1640 of file ARMInstPrinter.cpp.
References MI, and llvm::RISCVFenceField::O.
printCoprocOptionImm()
void ARMInstPrinter::printCoprocOptionImm (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1022 of file ARMInstPrinter.cpp.
References MI, and llvm::RISCVFenceField::O.
printCPSIFlag()
void ARMInstPrinter::printCPSIFlag (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 850 of file ARMInstPrinter.cpp.
References i, llvm::ARM_PROC::IFlagsToString(), MI, and llvm::RISCVFenceField::O.
printCPSIMod()
void ARMInstPrinter::printCPSIMod (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 844 of file ARMInstPrinter.cpp.
References llvm::ARM_PROC::IModToString(), MI, and llvm::RISCVFenceField::O.
printCustomAliasOperand()
virtual void llvm::ARMInstPrinter::printCustomAliasOperand (const MCInst * MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & O) virtual
printFBits16()
void ARMInstPrinter::printFBits16 (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1406 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printFBits32()
void ARMInstPrinter::printFBits32 (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1412 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printFPImmOperand()
void ARMInstPrinter::printFPImmOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1329 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getFPImmFloat(), llvm::MCOperand::getImm(), llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printGPRPairOperand()
void ARMInstPrinter::printGPRPairOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 825 of file ARMInstPrinter.cpp.
References llvm::MCRegisterInfo::getSubReg(), MI, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, and printRegName().
printImmPlusOneOperand()
void ARMInstPrinter::printImmPlusOneOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1348 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::RISCVMatInt::Imm, llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printInst()
void ARMInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 92 of file ARMInstPrinter.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCRegisterClass::contains(), llvm::MCOperand::createReg(), llvm::MCOperand::getImm(), llvm::MCRegisterInfo::getMatchingSuperReg(), llvm::MCOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), llvm::ARM_AM::getShiftOpcStr(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), i, isStore(), llvm::MCInstPrinter::markup(), MI, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), printInstruction(), printPredicateOperand(), printRegisterList(), printRegName(), printSBitModifierOperand(), llvm::ARM_AM::rrx, llvm::MCInst::setOpcode(), and translateShiftImm().
printInstruction()
void llvm::ARMInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by printInst().
printInstSyncBOption()
void ARMInstPrinter::printInstSyncBOption (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 756 of file ARMInstPrinter.cpp.
References llvm::ARM_ISB::InstSyncBOptToString(), MI, llvm::RISCVFenceField::O, and val.
printLdStmModeOperand()
void ARMInstPrinter::printLdStmModeOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 640 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::getAM4SubMode(), llvm::ARM_AM::getAMSubModeStr(), MI, Mode, and llvm::RISCVFenceField::O.
printMandatoryInvertedPredicateOperand()
void ARMInstPrinter::printMandatoryInvertedPredicateOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 986 of file ARMInstPrinter.cpp.
References llvm::ARMCondCodeToString(), CC, llvm::ARMCC::getOppositeCondition(), MI, and llvm::RISCVFenceField::O.
printMandatoryPredicateOperand()
void ARMInstPrinter::printMandatoryPredicateOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 978 of file ARMInstPrinter.cpp.
References llvm::ARMCondCodeToString(), CC, MI, and llvm::RISCVFenceField::O.
Referenced by printMandatoryRestrictedPredicateOperand().
printMandatoryRestrictedPredicateOperand()
void ARMInstPrinter::printMandatoryRestrictedPredicateOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 969 of file ARMInstPrinter.cpp.
References llvm::ARMCC::HS, MI, llvm::RISCVFenceField::O, and printMandatoryPredicateOperand().
printMemBOption()
void ARMInstPrinter::printMemBOption (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 749 of file ARMInstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::ARM_MB::MemBOptToString(), MI, llvm::RISCVFenceField::O, and val.
printModImmOperand()
void ARMInstPrinter::printModImmOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1365 of file ARMInstPrinter.cpp.
References llvm::tgtok::Bits, llvm::ARM_AM::getSOImmVal(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printOperand().
printMSRMaskOperand()
void ARMInstPrinter::printMSRMaskOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 862 of file ARMInstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm_unreachable, llvm::ARMSysReg::lookupMClassSysRegAPSRNonDeprecated(), llvm::ARMSysReg::lookupMClassSysRegBy12bitSYSmValue(), llvm::ARMSysReg::lookupMClassSysRegBy8bitSYSmValue(), llvm::BitmaskEnumDetail::Mask(), MI, and llvm::RISCVFenceField::O.
printMveAddrModeRQOperand()
template<int shift> void ARMInstPrinter::printMveAddrModeRQOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 623 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, printRegImmShift(), printRegName(), shift, llvm::MCInstPrinter::UseMarkup, and llvm::ARM_AM::uxtw.
printMveSaturateOp()
void ARMInstPrinter::printMveSaturateOp (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1671 of file ARMInstPrinter.cpp.
References assert(), MI, and llvm::RISCVFenceField::O.
printMVEVectorList()
template<unsigned NumRegs> void ARMInstPrinter::printMVEVectorList (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1626 of file ARMInstPrinter.cpp.
References llvm::MCRegisterInfo::getSubReg(), i, MI, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, llvm::cl::Prefix, and printRegName().
printNoHashImmediate()
void ARMInstPrinter::printNoHashImmediate (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1004 of file ARMInstPrinter.cpp.
References MI, and llvm::RISCVFenceField::O.
printOperand() [1/2]
void ARMInstPrinter::printOperand (const MCInst * MI, uint64_t Address, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 352 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::CommentStream, llvm::ARM_MC::evaluateBranchTarget(), llvm::MCInstPrinter::formatHex(), llvm::MCInstPrinter::formatImm(), llvm::MCInstrInfo::get(), llvm::MCInstPrinter::getUseMarkup(), MI, llvm::MCInstPrinter::MII, llvm::RISCVFenceField::O, llvm::MCInstPrinter::PrintBranchImmAsAddress, printOperand(), and uint64_t.
printOperand() [2/2]
void ARMInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 312 of file ARMInstPrinter.cpp.
References assert(), llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCInstPrinter::formatImm(), llvm::MCExpr::getKind(), llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, llvm::MCExpr::print(), and printRegName().
Referenced by printAddrMode2Operand(), printAddrMode3Operand(), printAddrMode5FP16Operand(), printAddrMode5Operand(), printAddrModeImm12Operand(), printModImmOperand(), printOperand(), printT2AddrModeImm8s4Operand(), printThumbAddrModeImm5SOperand(), and printThumbAddrModeRROperand().
printPCLabel()
void ARMInstPrinter::printPCLabel (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1028 of file ARMInstPrinter.cpp.
References llvm_unreachable.
printPImmediate()
void ARMInstPrinter::printPImmediate (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1010 of file ARMInstPrinter.cpp.
References MI, and llvm::RISCVFenceField::O.
printPKHASRShiftImm()
void ARMInstPrinter::printPKHASRShiftImm (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 794 of file ARMInstPrinter.cpp.
References assert(), llvm::RISCVMatInt::Imm, llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printPKHLSLShiftImm()
void ARMInstPrinter::printPKHLSLShiftImm (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 784 of file ARMInstPrinter.cpp.
References assert(), llvm::RISCVMatInt::Imm, llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printPostIdxImm8Operand()
void ARMInstPrinter::printPostIdxImm8Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 594 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::RISCVMatInt::Imm, llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printPostIdxImm8s4Operand()
void ARMInstPrinter::printPostIdxImm8s4Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 613 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::RISCVMatInt::Imm, llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printPostIdxRegOperand()
void ARMInstPrinter::printPostIdxRegOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 603 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), MI, llvm::RISCVFenceField::O, and printRegName().
printPredicateOperand()
void ARMInstPrinter::printPredicateOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 958 of file ARMInstPrinter.cpp.
References llvm::ARMCC::AL, llvm::ARMCondCodeToString(), CC, MI, and llvm::RISCVFenceField::O.
Referenced by printInst().
printRegisterList()
void ARMInstPrinter::printRegisterList (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 805 of file ARMInstPrinter.cpp.
References assert(), llvm::drop_begin(), llvm::numbers::e, llvm::MCRegisterInfo::getEncodingValue(), i, llvm::is_sorted(), LHS, MI, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, printRegName(), and RHS.
Referenced by printInst().
printRegName()
void ARMInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 88 of file ARMInstPrinter.cpp.
References getRegisterName(), llvm::MCInstPrinter::markup(), and OS.
Referenced by printAddrMode2OffsetOperand(), printAddrMode3OffsetOperand(), printAddrMode5FP16Operand(), printAddrMode5Operand(), printAddrMode6OffsetOperand(), printAddrMode6Operand(), printAddrMode7Operand(), printAddrModeImm12Operand(), printAddrModeTBB(), printAddrModeTBH(), printAM2PreOrOffsetIndexOp(), printAM3PreOrOffsetIndexOp(), printGPRPairOperand(), printInst(), printMveAddrModeRQOperand(), printMVEVectorList(), printOperand(), printPostIdxRegOperand(), printRegisterList(), printSORegImmOperand(), printSORegRegOperand(), printT2AddrModeImm0_1020s4Operand(), printT2AddrModeImm8Operand(), printT2AddrModeImm8s4Operand(), printT2AddrModeSoRegOperand(), printT2SOOperand(), printThumbAddrModeImm5SOperand(), printThumbAddrModeRROperand(), printVectorListFour(), printVectorListFourAllLanes(), printVectorListFourSpaced(), printVectorListFourSpacedAllLanes(), printVectorListOne(), printVectorListOneAllLanes(), printVectorListThree(), printVectorListThreeAllLanes(), printVectorListThreeSpaced(), printVectorListThreeSpacedAllLanes(), printVectorListTwo(), printVectorListTwoAllLanes(), printVectorListTwoSpaced(), and printVectorListTwoSpacedAllLanes().
printRotImmOperand()
void ARMInstPrinter::printRotImmOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1355 of file ARMInstPrinter.cpp.
References assert(), llvm::RISCVMatInt::Imm, llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printSBitModifierOperand()
void ARMInstPrinter::printSBitModifierOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 994 of file ARMInstPrinter.cpp.
References assert(), MI, and llvm::RISCVFenceField::O.
Referenced by printInst().
printSetendOperand()
void ARMInstPrinter::printSetendOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 834 of file ARMInstPrinter.cpp.
References MI, and llvm::RISCVFenceField::O.
printShiftImmOperand()
void ARMInstPrinter::printShiftImmOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 770 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printSORegImmOperand()
void ARMInstPrinter::printSORegImmOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 416 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), MI, llvm::RISCVFenceField::O, printRegImmShift(), printRegName(), and llvm::MCInstPrinter::UseMarkup.
printSORegRegOperand()
void ARMInstPrinter::printSORegRegOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 396 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::ARM_AM::getShiftOpcStr(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), MI, llvm::RISCVFenceField::O, printRegName(), and llvm::ARM_AM::rrx.
printT2AddrModeImm0_1020s4Operand()
void ARMInstPrinter::printT2AddrModeImm0_1020s4Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1258 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printRegName().
printT2AddrModeImm8OffsetOperand()
void ARMInstPrinter::printT2AddrModeImm8OffsetOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1273 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printT2AddrModeImm8Operand()
template<bool AlwaysPrintImm0> void ARMInstPrinter::printT2AddrModeImm8Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1203 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printRegName().
printT2AddrModeImm8s4OffsetOperand()
void ARMInstPrinter::printT2AddrModeImm8s4OffsetOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1288 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and x3.
printT2AddrModeImm8s4Operand()
template<bool AlwaysPrintImm0> void ARMInstPrinter::printT2AddrModeImm8s4Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1227 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, printOperand(), printRegName(), and x3.
printT2AddrModeSoRegOperand()
void ARMInstPrinter::printT2AddrModeSoRegOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1306 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printRegName().
printT2SOOperand()
void ARMInstPrinter::printT2SOOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1159 of file ARMInstPrinter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), llvm::MCOperand::isImm(), MI, llvm::RISCVFenceField::O, printRegImmShift(), printRegName(), and llvm::MCInstPrinter::UseMarkup.
printThumbAddrModeImm5S1Operand()
void ARMInstPrinter::printThumbAddrModeImm5S1Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1128 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printThumbAddrModeImm5SOperand().
printThumbAddrModeImm5S2Operand()
void ARMInstPrinter::printThumbAddrModeImm5S2Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1135 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printThumbAddrModeImm5SOperand().
printThumbAddrModeImm5S4Operand()
void ARMInstPrinter::printThumbAddrModeImm5S4Operand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1142 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printThumbAddrModeImm5SOperand().
printThumbAddrModeImm5SOperand()
void ARMInstPrinter::printThumbAddrModeImm5SOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O, unsigned Scale)
Definition at line 1106 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, printOperand(), and printRegName().
Referenced by printThumbAddrModeImm5S1Operand(), printThumbAddrModeImm5S2Operand(), printThumbAddrModeImm5S4Operand(), and printThumbAddrModeSPOperand().
printThumbAddrModeRROperand()
void ARMInstPrinter::printThumbAddrModeRROperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1086 of file ARMInstPrinter.cpp.
References llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, printOperand(), and printRegName().
printThumbAddrModeSPOperand()
void ARMInstPrinter::printThumbAddrModeSPOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1149 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printThumbAddrModeImm5SOperand().
printThumbITMask()
void ARMInstPrinter::printThumbITMask (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1071 of file ARMInstPrinter.cpp.
References assert(), llvm::countr_zero(), llvm::numbers::e, llvm::BitmaskEnumDetail::Mask(), MI, and llvm::RISCVFenceField::O.
printThumbLdrLabelOperand() [1/2]
void llvm::ARMInstPrinter::printThumbLdrLabelOperand (const MCInst * MI, uint64_t , unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O) inline
Definition at line 218 of file ARMInstPrinter.h.
References MI, llvm::RISCVFenceField::O, and printThumbLdrLabelOperand().
printThumbLdrLabelOperand() [2/2]
void ARMInstPrinter::printThumbLdrLabelOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 366 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::isExpr(), llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and llvm::MCExpr::print().
Referenced by printThumbLdrLabelOperand().
printThumbS4ImmOperand()
void ARMInstPrinter::printThumbS4ImmOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1056 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printThumbSRImm()
void ARMInstPrinter::printThumbSRImm (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1063 of file ARMInstPrinter.cpp.
References llvm::MCInstPrinter::formatImm(), llvm::RISCVMatInt::Imm, llvm::MCInstPrinter::markup(), MI, and llvm::RISCVFenceField::O.
printTraceSyncBOption()
void ARMInstPrinter::printTraceSyncBOption (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 763 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, llvm::ARM_TSB::TraceSyncBOptToString(), and val.
printVectorIndex()
void ARMInstPrinter::printVectorIndex (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1418 of file ARMInstPrinter.cpp.
References MI, and llvm::RISCVFenceField::O.
printVectorListFour()
void ARMInstPrinter::printVectorListFour (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1473 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListFourAllLanes()
void ARMInstPrinter::printVectorListFourAllLanes (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1529 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListFourSpaced()
void ARMInstPrinter::printVectorListFourSpaced (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1608 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListFourSpacedAllLanes()
void ARMInstPrinter::printVectorListFourSpacedAllLanes (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1575 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListOne()
void ARMInstPrinter::printVectorListOne (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1424 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListOneAllLanes()
void ARMInstPrinter::printVectorListOneAllLanes (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1490 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListThree()
void ARMInstPrinter::printVectorListThree (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1458 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListThreeAllLanes()
void ARMInstPrinter::printVectorListThreeAllLanes (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1513 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListThreeSpaced()
void ARMInstPrinter::printVectorListThreeSpaced (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1592 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListThreeSpacedAllLanes()
void ARMInstPrinter::printVectorListThreeSpacedAllLanes (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1560 of file ARMInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printVectorListTwo()
void ARMInstPrinter::printVectorListTwo (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1432 of file ARMInstPrinter.cpp.
References llvm::MCRegisterInfo::getSubReg(), MI, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, and printRegName().
printVectorListTwoAllLanes()
void ARMInstPrinter::printVectorListTwoAllLanes (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1499 of file ARMInstPrinter.cpp.
References llvm::MCRegisterInfo::getSubReg(), MI, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, and printRegName().
printVectorListTwoSpaced()
void ARMInstPrinter::printVectorListTwoSpaced (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1445 of file ARMInstPrinter.cpp.
References llvm::MCRegisterInfo::getSubReg(), MI, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, and printRegName().
printVectorListTwoSpacedAllLanes()
void ARMInstPrinter::printVectorListTwoSpacedAllLanes (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1547 of file ARMInstPrinter.cpp.
References llvm::MCRegisterInfo::getSubReg(), MI, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, and printRegName().
printVMOVModImmOperand()
void ARMInstPrinter::printVMOVModImmOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1337 of file ARMInstPrinter.cpp.
References llvm::ARM_AM::decodeVMOVModImm(), llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and uint64_t.
printVPTMask()
void ARMInstPrinter::printVPTMask (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1655 of file ARMInstPrinter.cpp.
References assert(), llvm::countr_zero(), llvm::numbers::e, llvm::BitmaskEnumDetail::Mask(), MI, and llvm::RISCVFenceField::O.
printVPTPredicateOperand()
void ARMInstPrinter::printVPTPredicateOperand (const MCInst * MI, unsigned OpNum, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 1647 of file ARMInstPrinter.cpp.
References llvm::ARMVPTPredToString(), CC, MI, llvm::ARMVCC::None, and llvm::RISCVFenceField::O.
The documentation for this class was generated from the following files:
lib/Target/ARM/MCTargetDesc/ARMInstPrinter.h
lib/Target/ARM/MCTargetDesc/ARMInstPrinter.cpp