LLVM: llvm::DCData Class Reference
llvm::DCData Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
DCData (const BasicBlock &B)
StringMap< std::string >::const_iterator begin () const
StringMap< std::string >::const_iterator end () const
StringRef getSuccessorLabel (StringRef S) const
Protected Member Functions
void addSuccessorLabel (StringRef Succ, StringRef Label)
Protected Attributes
StringMap< std::string > Successors
Detailed Description
Definition at line 458 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
DCData()
llvm::DCData::DCData (const BasicBlock & B)
Definition at line 1848 of file StandardInstrumentations.cpp.
References addSuccessorLabel(), assert(), B, E, llvm::formatv(), I, llvm::succ_begin(), llvm::succ_end(), and llvm::M68kBeads::Term.
Member Function Documentation
addSuccessorLabel()
void llvm::DCData::addSuccessorLabel (StringRef Succ, StringRef Label) inline protected
Definition at line 479 of file StandardInstrumentations.h.
References llvm::StringMap< ValueTy, AllocatorTy >::insert(), llvm::X86AS::SS, llvm::StringRef::str(), and Successors.
Referenced by DCData().
begin()
StringMap<std::string>::const_iterator llvm::DCData::begin () const inline
Definition at line 464 of file StandardInstrumentations.h.
References llvm::StringMap< ValueTy, AllocatorTy >::begin(), and Successors.
end()
StringMap<std::string>::const_iterator llvm::DCData::end () const inline
Definition at line 467 of file StandardInstrumentations.h.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), and Successors.
getSuccessorLabel()
StringRef llvm::DCData::getSuccessorLabel (StringRef S) const inline
Definition at line 472 of file StandardInstrumentations.h.
References assert(), llvm::StringMap< ValueTy, AllocatorTy >::count(), llvm::StringMap< ValueTy, AllocatorTy >::find(), S, and Successors.
Member Data Documentation
Successors
StringMap<std::string> llvm::DCData::Successors protected
Definition at line 484 of file StandardInstrumentations.h.
Referenced by addSuccessorLabel(), begin(), end(), and getSuccessorLabel().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp