LLVM: llvm::FaultMapParser::FunctionFaultInfoAccessor Class Reference
llvm::FaultMapParser::FunctionFaultInfoAccessor Class Reference
#include "llvm/Object/FaultMapParser.h"
Public Member Functions
FunctionFaultInfoAccessor (const uint8_t *P, const uint8_t *E)
FaultKindType getFaultKind () const
FaultingPCOffsetType getFaultingPCOffset () const
HandlerPCOffsetType getHandlerPCOffset () const
Static Public Attributes
static const size_t Size
Detailed Description
Definition at line 56 of file FaultMapParser.h.
Constructor & Destructor Documentation
FunctionFaultInfoAccessor()
llvm::FaultMapParser::FunctionFaultInfoAccessor::FunctionFaultInfoAccessor (const uint8_t * P, const uint8_t * E) inline explicit
Definition at line 74 of file FaultMapParser.h.
References P.
Member Function Documentation
getFaultingPCOffset()
FaultingPCOffsetType llvm::FaultMapParser::FunctionFaultInfoAccessor::getFaultingPCOffset () const inline
Definition at line 81 of file FaultMapParser.h.
References P.
Referenced by llvm::operator<<().
getFaultKind()
FaultKindType llvm::FaultMapParser::FunctionFaultInfoAccessor::getFaultKind () const inline
Definition at line 77 of file FaultMapParser.h.
References P.
Referenced by llvm::operator<<().
getHandlerPCOffset()
HandlerPCOffsetType llvm::FaultMapParser::FunctionFaultInfoAccessor::getHandlerPCOffset () const inline
Definition at line 85 of file FaultMapParser.h.
References P.
Referenced by llvm::operator<<().
Member Data Documentation
Size
const size_t llvm::FaultMapParser::FunctionFaultInfoAccessor::Size static
Initial value:
=
        HandlerPCOffsetOffset + sizeof(HandlerPCOffsetType)
Definition at line 71 of file FaultMapParser.h.
Referenced by llvm::FaultMapParser::FunctionInfoAccessor::getFunctionFaultInfoAt(), and llvm::FaultMapParser::FunctionInfoAccessor::getNextFunctionInfo().
The documentation for this class was generated from the following file:
include/llvm/Object/FaultMapParser.h