LLVM: llvm::VPCanonicalIVPHIRecipe Class Reference
llvm::VPCanonicalIVPHIRecipe Class Reference
Canonical scalar induction phi of the vector loop.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPCanonicalIVPHIRecipe (VPValue *StartV, DebugLoc DL)
~VPCanonicalIVPHIRecipe () override=default
void execute (VPTransformState &State) override
Generate the canonical scalar induction phi of the vector loop.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
const Type * getScalarType () const
Returns the scalar type of the induction.
bool onlyFirstLaneUsed (const VPValue *Op) const override
Returns true if the recipe only uses the first lane of operand Op.
bool isCanonical (const InductionDescriptor &ID, Type *Ty) const
Check if the induction described by ID is canonical, i.e.
Public Member Functions inherited from llvm::VPHeaderPHIRecipe
~VPHeaderPHIRecipe () override=default
VPValue * getStartValue ()
Returns the start value of the phi, if one is set.
VPValue * getStartValue () const
void setStartValue (VPValue *V)
Update the start value of the recipe.
VPValue * getBackedgeValue ()
Returns the incoming value from the loop backedge.
VPRecipeBase & getBackedgeRecipe ()
Returns the backedge value as a recipe.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands)
template<typename IterT >
VPRecipeBase (const unsigned char SC, iterator_range< IterT > Operands)
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Instruction * getUnderlyingInstr ()
Returns the underlying instruction, if the recipe is a VPValue or nullptr otherwise.
const Instruction * getUnderlyingInstr () const
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
VPUserID getVPUserID () const
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void removeLastOperand ()
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue ()
Return the underlying Value attached to this VPValue.
const Value * getUnderlyingValue () const
VPValue (Value *UV=nullptr)
Create a live-in VPValue.
VPValue (VPDef *Def, Value *UV=nullptr)
Create a VPValue for a Def which is a subclass of VPValue.
VPValue (Value *UV, VPDef *Def)
Create a VPValue for a Def which defines multiple values.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser ()
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
Value * getLiveInIRValue ()
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
const Value * getLiveInIRValue () const
bool isDefinedOutsideVectorRegions () const
Returns true if the VPValue is defined outside any vector regions, i.e.
Static Public Member Functions
static bool classof (const VPHeaderPHIRecipe *D)
Static Public Member Functions inherited from llvm::VPHeaderPHIRecipe
static bool classof (const VPRecipeBase *B)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPValue *V)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy = enum { VPBranchOnMaskSC, VPDerivedIVSC, VPExpandSCEVSC, VPInstructionSC, VPInterleaveSC, VPReductionSC, VPReplicateSC, VPScalarIVStepsSC, VPWidenCallSC, VPWidenCanonicalIVSC, VPWidenGEPSC, VPWidenMemoryInstructionSC, VPWidenSC, VPWidenSelectSC, VPBlendSC, VPPredInstPHISC, VPCanonicalIVPHISC, VPActiveLaneMaskPHISC, VPFirstOrderRecurrencePHISC, VPWidenPHISC, VPWidenIntOrFpInductionSC, VPWidenPointerInductionSC, VPReductionPHISC, VPFirstPHISC=VPBlendSC, VPFirstHeaderPHISC=VPCanonicalIVPHISC, VPLastPHISC=VPReductionPHISC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
enum VPUserID { VPUserID::Recipe, VPUserID::LiveOut }
Subclass identifier (for isa/dyn_cast).
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum { VPValueSC, VPVRecipeSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, false, false >
using const_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, false, true >
using reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, true, false >
using const_reverse_self_iterator = ilist_iterator< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type, true, true >
Protected Member Functions inherited from llvm::VPHeaderPHIRecipe
VPHeaderPHIRecipe (unsigned char VPDefID, PHINode *Phi, VPValue *Start=nullptr)
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands, VPUserID ID)
VPUser (std::initializer_list< VPValue * > Operands, VPUserID ID)
template<typename IterT >
VPUser (iterator_range< IterT > Operands, VPUserID ID)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
void setUnderlyingValue (Value *Val)
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
Canonical scalar induction phi of the vector loop.
Starting at the specified start value (either 0 or the resume value when vectorizing the epilogue loop). VPWidenCanonicalIVRecipe represents the vector version of the canonical induction variable.
Definition at line 1764 of file VPlan.h.
Constructor & Destructor Documentation
VPCanonicalIVPHIRecipe()
llvm::VPCanonicalIVPHIRecipe::VPCanonicalIVPHIRecipe (VPValue * StartV, DebugLoc DL) inline
Definition at line 1768 of file VPlan.h.
References DL.
~VPCanonicalIVPHIRecipe()
llvm::VPCanonicalIVPHIRecipe::~VPCanonicalIVPHIRecipe () override default
Member Function Documentation
classof()
static bool llvm::VPCanonicalIVPHIRecipe::classof (const VPHeaderPHIRecipe * D) inline static
Definition at line 1775 of file VPlan.h.
References D.
execute()
void VPCanonicalIVPHIRecipe::execute (VPTransformState & State) override virtual
Generate the canonical scalar induction phi of the vector loop.
Implements llvm::VPHeaderPHIRecipe.
Definition at line 1043 of file VPlanRecipes.cpp.
References llvm::PHINode::addIncoming(), llvm::VPTransformState::CFG, llvm::PHINode::Create(), llvm::BasicBlock::getFirstInsertionPt(), llvm::VPValue::getLiveInIRValue(), llvm::VPTransformState::CFGState::getPreheaderBBFor(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::VPTransformState::CFGState::PrevBB, llvm::VPTransformState::set(), llvm::Instruction::setDebugLoc(), and llvm::VPTransformState::UF.
getScalarType()
const Type* llvm::VPCanonicalIVPHIRecipe::getScalarType () const inline
Returns the scalar type of the induction.
Definition at line 1789 of file VPlan.h.
References llvm::VPValue::getLiveInIRValue(), llvm::VPUser::getOperand(), and llvm::Value::getType().
Referenced by isCanonical().
isCanonical()
bool VPCanonicalIVPHIRecipe::isCanonical (const InductionDescriptor & ID, Type * Ty) const
Check if the induction described by ID is canonical, i.e.
has the same start, step (of 1), and type as the canonical IV.
Definition at line 1064 of file VPlanRecipes.cpp.
References llvm::VPValue::getLiveInIRValue(), getScalarType(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::InductionDescriptor::IK_IntInduction, and llvm::ConstantInt::isOne().
Referenced by llvm::VPlanTransforms::optimizeInductions().
onlyFirstLaneUsed()
bool llvm::VPCanonicalIVPHIRecipe::onlyFirstLaneUsed (const VPValue * Op) const inline override virtual
Returns true if the recipe only uses the first lane of operand Op.
Reimplemented from llvm::VPUser.
Definition at line 1794 of file VPlan.h.
References assert(), llvm::is_contained(), and llvm::VPUser::operands().
print()
void VPCanonicalIVPHIRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPHeaderPHIRecipe.
Definition at line 1056 of file VPlanRecipes.cpp.
References llvm::RISCVFenceField::O, and llvm::VPValue::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp