LLVM: llvm::MCLineSection Class Reference
llvm::MCLineSection Class Reference
Instances of this class represent the line information for a compile unit where machine instructions have been assembled after seeing .loc directives.
#include "llvm/MC/MCDwarf.h"
Public Types
using MCDwarfLineEntryCollection = std::vector< MCDwarfLineEntry >
using iterator = MCDwarfLineEntryCollection::iterator
using const_iterator = MCDwarfLineEntryCollection::const_iterator
using MCLineDivisionMap = MapVector< MCSection *, MCDwarfLineEntryCollection >
Public Member Functions
void addLineEntry (const MCDwarfLineEntry &LineEntry, MCSection *Sec)
void addEndEntry (MCSymbol *EndLabel)
const MCLineDivisionMap & getMCLineEntries () const
Detailed Description
Instances of this class represent the line information for a compile unit where machine instructions have been assembled after seeing .loc directives.
This is the information used to build the dwarf line table for a section.
Definition at line 217 of file MCDwarf.h.
Member Typedef Documentation
const_iterator
using llvm::MCLineSection::const_iterator = MCDwarfLineEntryCollection::const_iterator
Definition at line 230 of file MCDwarf.h.
iterator
using llvm::MCLineSection::iterator = MCDwarfLineEntryCollection::iterator
Definition at line 229 of file MCDwarf.h.
MCDwarfLineEntryCollection
using llvm::MCLineSection::MCDwarfLineEntryCollection = std::vector<MCDwarfLineEntry>
Definition at line 228 of file MCDwarf.h.
MCLineDivisionMap
using llvm::MCLineSection::MCLineDivisionMap = MapVector<MCSection *, MCDwarfLineEntryCollection>
Definition at line 231 of file MCDwarf.h.
Member Function Documentation
addEndEntry()
void MCLineSection::addEndEntry (MCSymbol * EndLabel)
Definition at line 144 of file MCDwarf.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), llvm::MCSymbol::getSection(), and I.
addLineEntry()
void llvm::MCLineSection::addLineEntry (const MCDwarfLineEntry & LineEntry, MCSection * Sec) inline
Definition at line 220 of file MCDwarf.h.
Referenced by llvm::MCDwarfLineEntry::make().
getMCLineEntries()
const MCLineDivisionMap& llvm::MCLineSection::getMCLineEntries () const inline
Definition at line 239 of file MCDwarf.h.
Referenced by llvm::MCDwarfLineTable::emitCU().
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp