LLVM: llvm::RAGreedy Class Reference
llvm::RAGreedy Class Reference
#include "CodeGen/RegAllocGreedy.h"
Classes
class ExtraRegInfo
Track allocation stage and eviction loop prevention during allocation.
Public Member Functions
LiveRegMatrix * getInterferenceMatrix () const
LiveIntervals * getLiveIntervals () const
VirtRegMap * getVirtRegMap () const
const RegisterClassInfo & getRegClassInfo () const
const ExtraRegInfo & getExtraInfo () const
size_t getQueueSize () const
bool getRegClassPriorityTrumpsGlobalness () const
bool getReverseLocalAssignment () const
RAGreedy (const RegClassFilterFunc F=allocateAllRegClasses)
StringRef getPassName () const override
Return the pass name.
void getAnalysisUsage (AnalysisUsage &AU) const override
RAGreedy analysis usage.
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
Spiller & spiller () override
void enqueueImpl (const LiveInterval *LI) override
enqueue - Add VirtReg to the priority queue of unassigned registers.
const LiveInterval * dequeue () override
dequeue - Return the next unassigned register, or NULL.
MCRegister selectOrSplit (const LiveInterval &, SmallVectorImpl< Register > &) override
void aboutToRemoveInterval (const LiveInterval &) override
Method called when the allocator is about to remove a LiveInterval.
bool runOnMachineFunction (MachineFunction &mf) override
Perform register allocation.
MachineFunctionProperties getRequiredProperties () const override
MachineFunctionProperties getClearedProperties () const override
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Static Public Attributes inherited from llvm::RegAllocBase
static bool VerifyEnabled = false
VerifyEnabled - True when -verify-regalloc is given.
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getSetProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Member Functions inherited from llvm::RegAllocBase
RegAllocBase (const RegClassFilterFunc F=allocateAllRegClasses)
virtual ~RegAllocBase ()=default
void init (VirtRegMap &vrm, LiveIntervals &lis, LiveRegMatrix &mat)
void allocatePhysRegs ()
virtual void postOptimization ()
void enqueue (const LiveInterval *LI)
enqueue - Add VirtReg to the priority queue of unassigned registers.
Protected Attributes inherited from llvm::RegAllocBase
const TargetRegisterInfo * TRI = nullptr
MachineRegisterInfo * MRI = nullptr
VirtRegMap * VRM = nullptr
LiveIntervals * LIS = nullptr
LiveRegMatrix * Matrix = nullptr
RegisterClassInfo RegClassInfo
const RegClassFilterFunc ShouldAllocateClass
SmallPtrSet< MachineInstr *, 32 > DeadRemats
Inst which is a def of an original reg and whose defs are already all dead after remat is saved in DeadRemats.
Static Protected Attributes inherited from llvm::RegAllocBase
static const char TimerGroupName [] = "regalloc"
static const char TimerGroupDescription [] = "Register Allocation"
Detailed Description
Definition at line 61 of file RegAllocGreedy.h.
Constructor & Destructor Documentation
RAGreedy()
RAGreedy::RAGreedy (const RegClassFilterFunc F = allocateAllRegClasses)
Definition at line 194 of file RegAllocGreedy.cpp.
Member Function Documentation
aboutToRemoveInterval()
void RAGreedy::aboutToRemoveInterval (const LiveInterval & LI) override virtual
Method called when the allocator is about to remove a LiveInterval.
Reimplemented from llvm::RegAllocBase.
Definition at line 2110 of file RegAllocGreedy.cpp.
dequeue()
const LiveInterval * RAGreedy::dequeue () override virtual
dequeue - Return the next unassigned register, or NULL.
Implements llvm::RegAllocBase.
Definition at line 379 of file RegAllocGreedy.cpp.
enqueueImpl()
void RAGreedy::enqueueImpl (const LiveInterval * LI) override virtual
enqueue - Add VirtReg to the priority queue of unassigned registers.
Implements llvm::RegAllocBase.
Definition at line 279 of file RegAllocGreedy.cpp.
getAnalysisUsage()
void RAGreedy::getAnalysisUsage (AnalysisUsage & AU) const override virtual
RAGreedy analysis usage.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 199 of file RegAllocGreedy.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesCFG().
getClearedProperties()
MachineFunctionProperties llvm::RAGreedy::getClearedProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 309 of file RegAllocGreedy.h.
References llvm::MachineFunctionProperties::IsSSA, and llvm::MachineFunctionProperties::set().
getExtraInfo()
const ExtraRegInfo& llvm::RAGreedy::getExtraInfo () const inline
Definition at line 147 of file RegAllocGreedy.h.
Referenced by llvm::MLPriorityAdvisor::getPriorityImpl().
getInterferenceMatrix()
LiveRegMatrix* llvm::RAGreedy::getInterferenceMatrix () const inline
Definition at line 143 of file RegAllocGreedy.h.
References Matrix.
getLiveIntervals()
LiveIntervals* llvm::RAGreedy::getLiveIntervals () const inline
Definition at line 144 of file RegAllocGreedy.h.
getPassName()
StringRef llvm::RAGreedy::getPassName () const inline override virtual
Return the pass name.
Reimplemented from llvm::Pass.
Definition at line 289 of file RegAllocGreedy.h.
getQueueSize()
size_t llvm::RAGreedy::getQueueSize () const inline
Definition at line 148 of file RegAllocGreedy.h.
getRegClassInfo()
const RegisterClassInfo& llvm::RAGreedy::getRegClassInfo () const inline
Definition at line 146 of file RegAllocGreedy.h.
getRegClassPriorityTrumpsGlobalness()
bool llvm::RAGreedy::getRegClassPriorityTrumpsGlobalness () const inline
Definition at line 152 of file RegAllocGreedy.h.
getRequiredProperties()
MachineFunctionProperties llvm::RAGreedy::getRequiredProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 304 of file RegAllocGreedy.h.
References llvm::MachineFunctionProperties::NoPHIs, and llvm::MachineFunctionProperties::set().
getReverseLocalAssignment()
bool llvm::RAGreedy::getReverseLocalAssignment () const inline
Definition at line 155 of file RegAllocGreedy.h.
getVirtRegMap()
VirtRegMap* llvm::RAGreedy::getVirtRegMap () const inline
Definition at line 145 of file RegAllocGreedy.h.
releaseMemory()
void RAGreedy::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 274 of file RegAllocGreedy.cpp.
References llvm::SmallVectorImpl< T >::clear().
Referenced by runOnMachineFunction().
runOnMachineFunction()
bool RAGreedy::runOnMachineFunction (MachineFunction & mf) override virtual
Perform register allocation.
Implements llvm::MachineFunctionPass.
Definition at line 2603 of file RegAllocGreedy.cpp.
References llvm::RegAllocBase::allocatePhysRegs(), llvm::createInlineSpiller(), llvm::dbgs(), llvm::Pass::dump(), llvm::LiveRegMatrix::getLiveUnions(), llvm::MachineFunction::getName(), llvm::cl::Option::getNumOccurrences(), llvm::TargetRegisterInfo::getRegisterCosts(), GreedyRegClassPriorityTrumpsGlobalness, GreedyReverseLocalAssignment, llvm::RegAllocBase::init(), llvm::InterferenceCache::init(), llvm::RegAllocBase::LIS, LLVM_DEBUG, Loops, llvm::RegAllocBase::Matrix, llvm::RegAllocBase::postOptimization(), llvm::TargetRegisterInfo::regClassPriorityTrumpsGlobalness(), releaseMemory(), llvm::SmallVectorImpl< T >::resize(), llvm::TargetRegisterInfo::reverseLocalAssignment(), llvm::RegAllocBase::TRI, llvm::RegAllocBase::VerifyEnabled, and llvm::RegAllocBase::VRM.
selectOrSplit()
MCRegister RAGreedy::selectOrSplit (const LiveInterval & VirtReg, SmallVectorImpl< Register > & NewVRegs) override virtual
Implements llvm::RegAllocBase.
Definition at line 2044 of file RegAllocGreedy.cpp.
References llvm::LLVMContext::emitError(), llvm::Function::getContext(), and llvm::MachineFunction::getFunction().
spiller()
Spiller& llvm::RAGreedy::spiller () inline override virtual
Implements llvm::RegAllocBase.
Definition at line 294 of file RegAllocGreedy.h.
Member Data Documentation
ID
char RAGreedy::ID = 0 static
Definition at line 314 of file RegAllocGreedy.h.
The documentation for this class was generated from the following files:
lib/CodeGen/RegAllocGreedy.h
lib/CodeGen/RegAllocGreedy.cpp