LLVM: llvm::logicalview::LVRange Class Reference
llvm::logicalview::LVRange Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVRange.h"
Public Member Functions
LVRange ()
LVRange (const LVRange &)=delete
LVRange & operator= (const LVRange &)=delete
~LVRange ()=default
void addEntry (LVScope *Scope, LVAddress LowerAddress, LVAddress UpperAddress)
void addEntry (LVScope *Scope)
LVScope * getEntry (LVAddress Address) const
LVScope * getEntry (LVAddress LowerAddress, LVAddress UpperAddress) const
bool hasEntry (LVAddress Low, LVAddress High) const
LVAddress getLower () const
LVAddress getUpper () const
const LVRangeEntries & getEntries () const
void clear ()
bool empty () const
void sort ()
void startSearch ()
void endSearch ()
void print (raw_ostream &OS, bool Full=true) const override
void printExtra (raw_ostream &OS, bool Full=true) const override
void dump () const override
Public Member Functions inherited from llvm::logicalview::LVObject
LVObject ()
LVObject & operator= (const LVObject &)=delete
virtual ~LVObject ()=default
PROPERTY (Property, IsLocation)
PROPERTY (Property, IsGlobalReference)
PROPERTY (Property, IsGeneratedName)
PROPERTY (Property, IsResolved)
PROPERTY (Property, IsResolvedName)
PROPERTY (Property, IsDiscarded)
PROPERTY (Property, IsOptimized)
PROPERTY (Property, IsAdded)
PROPERTY (Property, IsMatched)
PROPERTY (Property, IsMissing)
PROPERTY (Property, IsMissingLink)
PROPERTY (Property, IsInCompare)
PROPERTY (Property, IsFileFromReference)
PROPERTY (Property, IsLineFromReference)
PROPERTY (Property, HasMoved)
PROPERTY (Property, HasPattern)
PROPERTY (Property, IsFinalized)
PROPERTY (Property, IsReferenced)
PROPERTY (Property, HasCodeViewLocation)
virtual bool isNamed () const
virtual bool isTyped () const
virtual bool isFiled () const
bool isLined () const
dwarf::Tag getTag () const
void setTag (dwarf::Tag Tag)
dwarf::Attribute getAttr () const
void setAttr (dwarf::Attribute Attr)
LVSmall getOpcode () const
void setOpcode (LVSmall Opcode)
LVOffset getOffset () const
void setOffset (LVOffset DieOffset)
LVLevel getLevel () const
void setLevel (LVLevel Level)
virtual StringRef getName () const
virtual void setName (StringRef ObjectName)
LVElement * getParent () const
LVScope * getParentScope () const
LVSymbol * getParentSymbol () const
void setParent (LVScope *Scope)
void setParent (LVSymbol *Symbol)
void resetParent ()
virtual LVAddress getLowerAddress () const
virtual void setLowerAddress (LVAddress Address)
virtual LVAddress getUpperAddress () const
virtual void setUpperAddress (LVAddress Address)
uint32_t getLineNumber () const
void setLineNumber (uint32_t Number)
virtual const char * kind () const
std::string indentAsString () const
std::string indentAsString (LVLevel Level) const
virtual std::string noLineAsString (bool ShowZero) const
virtual std::string lineNumberAsString (bool ShowZero=false) const
std::string lineNumberAsStringStripped (bool ShowZero=false) const
virtual Error doPrint (bool Split, bool Match, bool Print, raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full, StringRef Name, LVObject *Parent, StringRef Value, bool UseQuotes=false, bool PrintRef=false) const
void markBranchAsMissing ()
uint64_t getID () const
Additional Inherited Members
Protected Member Functions inherited from llvm::logicalview::LVObject
std::string lineAsString (uint32_t LineNumber, LVHalf Discriminator, bool ShowZero) const
std::string referenceAsString (uint32_t LineNumber, bool Spaces) const
virtual void printFileIndex (raw_ostream &OS, bool Full=true) const
Detailed Description
Definition at line 49 of file LVRange.h.
Constructor & Destructor Documentation
LVRange() [1/2]
llvm::logicalview::LVRange::LVRange () inline
Definition at line 61 of file LVRange.h.
References Allocator.
LVRange() [2/2]
llvm::logicalview::LVRange::LVRange (const LVRange &) delete
~LVRange()
llvm::logicalview::LVRange::~LVRange () default
Member Function Documentation
addEntry() [1/2]
void LVRange::addEntry (LVScope * Scope)
Definition at line 68 of file LVRange.cpp.
References addEntry(), assert(), llvm::logicalview::LVScope::getRanges(), hasEntry(), llvm::logicalview::Location, llvm::logicalview::Locations, and llvm::logicalview::LVObject::Scope.
addEntry() [2/2]
void LVRange::addEntry (LVScope * Scope, LVAddress LowerAddress, LVAddress UpperAddress)
Definition at line 52 of file LVRange.cpp.
References llvm::logicalview::LVObject::Scope, and std::swap().
Referenced by addEntry(), llvm::logicalview::LVBinaryReader::addSectionRange(), and llvm::logicalview::LVScope::getRanges().
clear()
void llvm::logicalview::LVRange::clear () inline
Definition at line 76 of file LVRange.h.
References llvm::logicalview::MaxAddress, and llvm::Upper.
dump()
void llvm::logicalview::LVRange::dump () const inline override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 91 of file LVRange.h.
References llvm::dbgs(), and print().
empty()
bool llvm::logicalview::LVRange::empty () const inline
Definition at line 81 of file LVRange.h.
endSearch()
void llvm::logicalview::LVRange::endSearch () inline
Definition at line 85 of file LVRange.h.
Referenced by llvm::logicalview::LVBinaryReader::processLines().
getEntries()
const LVRangeEntries& llvm::logicalview::LVRange::getEntries () const inline
Definition at line 74 of file LVRange.h.
getEntry() [1/2]
LVScope * LVRange::getEntry (LVAddress Address) const
Definition at line 83 of file LVRange.cpp.
References llvm::dbgs(), llvm::IntervalTree< PointT, ValueT, DataT >::find(), llvm::format(), LLVM_DEBUG, and llvm::logicalview::LVObject::Scope.
Referenced by llvm::logicalview::LVBinaryReader::processLines().
getEntry() [2/2]
LVScope * LVRange::getEntry (LVAddress LowerAddress, LVAddress UpperAddress) const
Definition at line 109 of file LVRange.cpp.
getLower()
LVAddress llvm::logicalview::LVRange::getLower () const inline
Definition at line 71 of file LVRange.h.
getUpper()
LVAddress llvm::logicalview::LVRange::getUpper () const inline
Definition at line 72 of file LVRange.h.
References llvm::Upper.
hasEntry()
bool LVRange::hasEntry (LVAddress Low, LVAddress High) const
Definition at line 118 of file LVRange.cpp.
Referenced by addEntry().
operator=()
LVRange& llvm::logicalview::LVRange::operator= (const LVRange &) delete
print()
void LVRange::print (raw_ostream & OS, bool Full = true) const override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 145 of file LVRange.cpp.
References llvm::format(), llvm::logicalview::formattedKind(), llvm::logicalview::formattedName(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVOptions::indentationSize(), llvm::logicalview::LVScope::kind(), llvm::logicalview::options(), OS, llvm::logicalview::LVObject::printAttributes(), printExtra(), and llvm::logicalview::LVObject::Scope.
Referenced by dump().
printExtra()
void llvm::logicalview::LVRange::printExtra (raw_ostream & OS, bool Full = true) const inline override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 88 of file LVRange.h.
Referenced by print().
sort()
void LVRange::sort ()
Definition at line 127 of file LVRange.cpp.
References llvm::logicalview::LVRangeEntry::lower(), llvm::stable_sort(), and llvm::logicalview::LVRangeEntry::upper().
startSearch()
void LVRange::startSearch ()
Definition at line 22 of file LVRange.cpp.
References llvm::IntervalTree< PointT, ValueT, DataT >::clear(), llvm::IntervalTree< PointT, ValueT, DataT >::create(), llvm::dbgs(), llvm::format_decimal(), llvm::logicalview::LVObject::getLevel(), llvm::logicalview::hexValue(), llvm::IntervalTree< PointT, ValueT, DataT >::insert(), LLVM_DEBUG, llvm::IntervalTree< PointT, ValueT, DataT >::print(), and llvm::logicalview::LVObject::Scope.
Referenced by llvm::logicalview::LVBinaryReader::processLines().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVRange.h
lib/DebugInfo/LogicalView/Core/LVRange.cpp