LLVM: llvm::pdb::NativeEnumSymbols Class Reference
llvm::pdb::NativeEnumSymbols Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeEnumSymbols.h"
Public Member Functions
NativeEnumSymbols (NativeSession &Session, std::vector< SymIndexId > Symbols)
uint32_t getChildCount () const override
std::unique_ptr< PDBSymbol > getChildAtIndex (uint32_t Index) const override
std::unique_ptr< PDBSymbol > getNext () override
void reset () override
Public Member Functions inherited from llvm::pdb::IPDBEnumChildren< PDBSymbol >
virtual ~IPDBEnumChildren ()=default
virtual uint32_t getChildCount () const=0
Additional Inherited Members
Public Types inherited from llvm::pdb::IPDBEnumChildren< PDBSymbol >
using ChildTypePtr = std::unique_ptr< PDBSymbol >
using MyType = IPDBEnumChildren< PDBSymbol >
Detailed Description
Definition at line 23 of file NativeEnumSymbols.h.
Constructor & Destructor Documentation
NativeEnumSymbols()
NativeEnumSymbols::NativeEnumSymbols (NativeSession & Session, std::vector< SymIndexId > Symbols)
Definition at line 21 of file NativeEnumSymbols.cpp.
Member Function Documentation
getChildAtIndex()
std::unique_ptr< PDBSymbol > NativeEnumSymbols::getChildAtIndex (uint32_t Index) const override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 30 of file NativeEnumSymbols.cpp.
References llvm::pdb::SymbolCache::getSymbolById(), llvm::pdb::NativeSession::getSymbolCache(), and N.
Referenced by getNext().
getChildCount()
uint32_t NativeEnumSymbols::getChildCount () const override
Definition at line 25 of file NativeEnumSymbols.cpp.
getNext()
std::unique_ptr< PDBSymbol > NativeEnumSymbols::getNext () override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 37 of file NativeEnumSymbols.cpp.
References getChildAtIndex().
reset()
void NativeEnumSymbols::reset () override virtual
Implements llvm::pdb::IPDBEnumChildren< PDBSymbol >.
Definition at line 41 of file NativeEnumSymbols.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeEnumSymbols.h
lib/DebugInfo/PDB/Native/NativeEnumSymbols.cpp