LLVM: llvm::DebuginfodCollection Class Reference
llvm::DebuginfodCollection Class Reference
Tracks a collection of debuginfod artifacts on the local filesystem.
#include "llvm/Debuginfod/Debuginfod.h"
Public Member Functions
DebuginfodCollection (ArrayRef< StringRef > Paths, DebuginfodLog &Log, ThreadPool &Pool, double MinInterval)
Error update ()
Error updateForever (std::chrono::milliseconds Interval)
Expected< std::string > findDebugBinaryPath (object::BuildIDRef)
Expected< std::string > findBinaryPath (object::BuildIDRef)
Detailed Description
Tracks a collection of debuginfod artifacts on the local filesystem.
Definition at line 106 of file Debuginfod.h.
Constructor & Destructor Documentation
DebuginfodCollection()
llvm::DebuginfodCollection::DebuginfodCollection (ArrayRef< StringRef > Paths, DebuginfodLog & Log, ThreadPool & Pool, double MinInterval)
Definition at line 303 of file Debuginfod.cpp.
Member Function Documentation
findBinaryPath()
Expected< std::string > llvm::DebuginfodCollection::findBinaryPath (object::BuildIDRef)
Definition at line 453 of file Debuginfod.cpp.
References llvm::consumeError(), findDebugBinaryPath(), llvm::getCachedOrDownloadExecutable(), and llvm::Expected< T >::takeError().
findDebugBinaryPath()
Expected< std::string > llvm::DebuginfodCollection::findDebugBinaryPath (object::BuildIDRef)
Definition at line 485 of file Debuginfod.cpp.
References llvm::getCachedOrDownloadDebuginfo(), and llvm::Expected< T >::takeError().
Referenced by llvm::DebuginfodServer::DebuginfodServer(), and findBinaryPath().
update()
Error llvm::DebuginfodCollection::update ()
Definition at line 311 of file Debuginfod.cpp.
References llvm::Timer::clear(), llvm::Timer::isRunning(), llvm::DebuginfodLog::push(), and llvm::Timer::stopTimer().
updateForever()
Error llvm::DebuginfodCollection::updateForever (std::chrono::milliseconds Interval)
Definition at line 339 of file Debuginfod.cpp.
The documentation for this class was generated from the following files:
include/llvm/Debuginfod/Debuginfod.h
lib/Debuginfod/Debuginfod.cpp