LLVM: llvm::PrintModulePass Class Reference
llvm::PrintModulePass Class Reference
Pass (for the new pass manager) for printing a Module as LLVM's text IR assembly.
#include "llvm/IRPrinter/IRPrintingPasses.h"
Public Member Functions
PrintModulePass ()
PrintModulePass (raw_ostream &OS, const std::string &Banner="", bool ShouldPreserveUseListOrder=false, bool EmitSummaryIndex=false)
PreservedAnalyses run (Module &M, AnalysisManager< Module > &)
Public Member Functions inherited from llvm::PassInfoMixin< PrintModulePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< PrintModulePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass (for the new pass manager) for printing a Module as LLVM's text IR assembly.
Definition at line 32 of file IRPrintingPasses.h.
Constructor & Destructor Documentation
PrintModulePass() [1/2]
PrintModulePass::PrintModulePass ()
Definition at line 25 of file IRPrintingPasses.cpp.
PrintModulePass() [2/2]
PrintModulePass::PrintModulePass (raw_ostream & OS, const std::string & Banner = "", bool ShouldPreserveUseListOrder = false, bool EmitSummaryIndex = false)
Definition at line 26 of file IRPrintingPasses.cpp.
Member Function Documentation
isRequired()
static bool llvm::PrintModulePass::isRequired () inline static
Definition at line 45 of file IRPrintingPasses.h.
run()
PreservedAnalyses PrintModulePass::run (Module & M, AnalysisManager< Module > &)
Definition at line 33 of file IRPrintingPasses.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::isFunctionInPrintList(), and M.
The documentation for this class was generated from the following files:
include/llvm/IRPrinter/IRPrintingPasses.h
lib/IRPrinter/IRPrintingPasses.cpp