LLVM: llvm::object::symbol_iterator Class Reference
llvm::object::symbol_iterator Class Reference
#include "llvm/Object/ObjectFile.h"
Public Member Functions
symbol_iterator (SymbolRef Sym)
symbol_iterator (const basic_symbol_iterator &B)
const SymbolRef * operator-> () const
const SymbolRef & operator* () const
Public Member Functions inherited from llvm::object::content_iterator< content_type >
content_iterator (content_type symb)
const content_type * operator-> () const
const content_type & operator* () const
bool operator== (const content_iterator &other) const
bool operator!= (const content_iterator &other) const
content_iterator & operator++ ()
Additional Inherited Members
Public Types inherited from llvm::object::content_iterator< content_type >
using iterator_category = std::forward_iterator_tag
using value_type = content_type
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Detailed Description
Definition at line 207 of file ObjectFile.h.
Constructor & Destructor Documentation
symbol_iterator() [1/2]
llvm::object::symbol_iterator::symbol_iterator (SymbolRef Sym) inline
Definition at line 209 of file ObjectFile.h.
symbol_iterator() [2/2]
llvm::object::symbol_iterator::symbol_iterator (const basic_symbol_iterator & B) inline
Definition at line 210 of file ObjectFile.h.
Member Function Documentation
operator*()
const SymbolRef& llvm::object::symbol_iterator::operator* () const inline
Definition at line 219 of file ObjectFile.h.
References llvm::object::content_iterator< content_type >::operator*(), and P.
Referenced by llvm::object::elf_symbol_iterator::operator*().
operator->()
const SymbolRef* llvm::object::symbol_iterator::operator-> () const inline
Definition at line 214 of file ObjectFile.h.
References llvm::object::content_iterator< content_type >::operator*(), and P.
Referenced by llvm::object::elf_symbol_iterator::operator->().
The documentation for this class was generated from the following file:
include/llvm/Object/ObjectFile.h