LLVM: llvm::VEMCExpr Class Reference
llvm::VEMCExpr Class Reference
#include "Target/VE/MCTargetDesc/VEMCExpr.h"
Public Types
enum VariantKind {
VK_VE_None, VK_VE_REFLONG, VK_VE_HI32, VK_VE_LO32,
VK_VE_PC_HI32, VK_VE_PC_LO32, VK_VE_GOT_HI32, VK_VE_GOT_LO32,
VK_VE_GOTOFF_HI32, VK_VE_GOTOFF_LO32, VK_VE_PLT_HI32, VK_VE_PLT_LO32,
VK_VE_TLS_GD_HI32, VK_VE_TLS_GD_LO32, VK_VE_TPOFF_HI32, VK_VE_TPOFF_LO32
}
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Accessors
VariantKind getKind () const
getOpcode - Get the kind of this expression.
const MCExpr * getSubExpr () const
getSubExpr - Get the child of this expression.
VE::Fixups getFixupKind () const
getFixupKind - Get the fixup kind of this expression.
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static bool classof (const MCExpr *E)
static bool classof (const VEMCExpr *)
static VariantKind parseVariantKind (StringRef name)
static bool printVariantKind (raw_ostream &OS, VariantKind Kind)
static void printVariantKindSuffix (raw_ostream &OS, VariantKind Kind)
static VE::Fixups getFixupKind (VariantKind Kind)
Construction
static const VEMCExpr * create (VariantKind Kind, const MCExpr *Expr, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Definition at line 23 of file VEMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::VEMCExpr::VariantKind
Enumerator
VK_VE_None
VK_VE_REFLONG
VK_VE_HI32
VK_VE_LO32
VK_VE_PC_HI32
VK_VE_PC_LO32
VK_VE_GOT_HI32
VK_VE_GOT_LO32
VK_VE_GOTOFF_HI32
VK_VE_GOTOFF_LO32
VK_VE_PLT_HI32
VK_VE_PLT_LO32
VK_VE_TLS_GD_HI32
VK_VE_TLS_GD_LO32
VK_VE_TPOFF_HI32
VK_VE_TPOFF_LO32
Definition at line 25 of file VEMCExpr.h.
Member Function Documentation
classof() [1/2]
static bool llvm::VEMCExpr::classof (const MCExpr * E) inline static
Definition at line 81 of file VEMCExpr.h.
References E, and llvm::MCExpr::Target.
classof() [2/2]
static bool llvm::VEMCExpr::classof (const VEMCExpr *) inline static
Definition at line 85 of file VEMCExpr.h.
create()
const VEMCExpr * VEMCExpr::create (VariantKind Kind, const MCExpr * Expr, MCContext & Ctx) static
Definition at line 27 of file VEMCExpr.cpp.
Referenced by createGOTRelExprOp(), createVEMCOperand(), and LowerSymbolOperand().
evaluateAsRelocatableImpl()
bool VEMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 176 of file VEMCExpr.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), Fixup, llvm::MCValue::get(), llvm::MCValue::getConstant(), getKind(), getSubExpr(), llvm::MCValue::getSymA(), and llvm::MCValue::getSymB().
findAssociatedFragment()
MCFragment* llvm::VEMCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 75 of file VEMCExpr.h.
References llvm::MCExpr::findAssociatedFragment(), and getSubExpr().
fixELFSymbolsInTLSFixups()
void VEMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 222 of file VEMCExpr.cpp.
References llvm::HexStyle::Asm, fixELFSymbolsInTLSFixupsImpl(), getKind(), getSubExpr(), VK_VE_TLS_GD_HI32, VK_VE_TLS_GD_LO32, VK_VE_TPOFF_HI32, and VK_VE_TPOFF_LO32.
getFixupKind() [1/2]
VE::Fixups llvm::VEMCExpr::getFixupKind () const inline
getFixupKind - Get the fixup kind of this expression.
Definition at line 68 of file VEMCExpr.h.
References getFixupKind().
Referenced by getFixupKind().
getFixupKind() [2/2]
VE::Fixups VEMCExpr::getFixupKind (VEMCExpr::VariantKind Kind) static
Definition at line 139 of file VEMCExpr.cpp.
References llvm::VE::fixup_ve_got_hi32, llvm::VE::fixup_ve_got_lo32, llvm::VE::fixup_ve_gotoff_hi32, llvm::VE::fixup_ve_gotoff_lo32, llvm::VE::fixup_ve_hi32, llvm::VE::fixup_ve_lo32, llvm::VE::fixup_ve_pc_hi32, llvm::VE::fixup_ve_pc_lo32, llvm::VE::fixup_ve_plt_hi32, llvm::VE::fixup_ve_plt_lo32, llvm::VE::fixup_ve_reflong, llvm::VE::fixup_ve_tls_gd_hi32, llvm::VE::fixup_ve_tls_gd_lo32, llvm::VE::fixup_ve_tpoff_hi32, llvm::VE::fixup_ve_tpoff_lo32, llvm_unreachable, VK_VE_GOT_HI32, VK_VE_GOT_LO32, VK_VE_GOTOFF_HI32, VK_VE_GOTOFF_LO32, VK_VE_HI32, VK_VE_LO32, VK_VE_PC_HI32, VK_VE_PC_LO32, VK_VE_PLT_HI32, VK_VE_PLT_LO32, VK_VE_REFLONG, VK_VE_TLS_GD_HI32, VK_VE_TLS_GD_LO32, VK_VE_TPOFF_HI32, and VK_VE_TPOFF_LO32.
getKind()
VariantKind llvm::VEMCExpr::getKind () const inline
getOpcode - Get the kind of this expression.
Definition at line 62 of file VEMCExpr.h.
Referenced by evaluateAsRelocatableImpl(), and fixELFSymbolsInTLSFixups().
getSubExpr()
const MCExpr* llvm::VEMCExpr::getSubExpr () const inline
getSubExpr - Get the child of this expression.
Definition at line 65 of file VEMCExpr.h.
Referenced by evaluateAsRelocatableImpl(), findAssociatedFragment(), fixELFSymbolsInTLSFixups(), printImpl(), and visitUsedExpr().
parseVariantKind()
VEMCExpr::VariantKind VEMCExpr::parseVariantKind (StringRef name) static
Definition at line 120 of file VEMCExpr.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), name, VK_VE_GOT_HI32, VK_VE_GOT_LO32, VK_VE_GOTOFF_HI32, VK_VE_GOTOFF_LO32, VK_VE_HI32, VK_VE_LO32, VK_VE_None, VK_VE_PC_HI32, VK_VE_PC_LO32, VK_VE_PLT_HI32, VK_VE_PLT_LO32, VK_VE_TLS_GD_HI32, VK_VE_TLS_GD_LO32, VK_VE_TPOFF_HI32, and VK_VE_TPOFF_LO32.
printImpl()
void VEMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 32 of file VEMCExpr.cpp.
References getSubExpr(), OS, llvm::MCExpr::print(), printVariantKind(), and printVariantKindSuffix().
printVariantKind()
bool VEMCExpr::printVariantKind (raw_ostream & OS, VariantKind Kind) static
Definition at line 44 of file VEMCExpr.cpp.
References VK_VE_GOT_HI32, VK_VE_GOT_LO32, VK_VE_GOTOFF_HI32, VK_VE_GOTOFF_LO32, VK_VE_HI32, VK_VE_LO32, VK_VE_None, VK_VE_PC_HI32, VK_VE_PC_LO32, VK_VE_PLT_HI32, VK_VE_PLT_LO32, VK_VE_REFLONG, VK_VE_TLS_GD_HI32, VK_VE_TLS_GD_LO32, VK_VE_TPOFF_HI32, and VK_VE_TPOFF_LO32.
Referenced by printImpl().
printVariantKindSuffix()
void VEMCExpr::printVariantKindSuffix (raw_ostream & OS, VariantKind Kind) static
Definition at line 70 of file VEMCExpr.cpp.
References OS, VK_VE_GOT_HI32, VK_VE_GOT_LO32, VK_VE_GOTOFF_HI32, VK_VE_GOTOFF_LO32, VK_VE_HI32, VK_VE_LO32, VK_VE_None, VK_VE_PC_HI32, VK_VE_PC_LO32, VK_VE_PLT_HI32, VK_VE_PLT_LO32, VK_VE_REFLONG, VK_VE_TLS_GD_HI32, VK_VE_TLS_GD_LO32, VK_VE_TPOFF_HI32, and VK_VE_TPOFF_LO32.
Referenced by printImpl().
visitUsedExpr()
void VEMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 218 of file VEMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
lib/Target/VE/MCTargetDesc/VEMCExpr.h
lib/Target/VE/MCTargetDesc/VEMCExpr.cpp