LLVM: llvm::FunctionSpecializer Class Reference
llvm::FunctionSpecializer Class Reference
#include "llvm/Transforms/IPO/FunctionSpecialization.h"
Public Member Functions
FunctionSpecializer (SCCPSolver &Solver, Module &M, FunctionAnalysisManager *FAM, std::function< const TargetLibraryInfo &(Function &)> GetTLI, std::function< TargetTransformInfo &(Function &)> GetTTI, std::function< AssumptionCache &(Function &)> GetAC)
~FunctionSpecializer ()
bool isClonedFunction (Function *F)
bool run ()
Attempt to specialize functions in the module to enable constant propagation across function boundaries.
Detailed Description
Definition at line 115 of file FunctionSpecialization.h.
Constructor & Destructor Documentation
FunctionSpecializer()
llvm::FunctionSpecializer::FunctionSpecializer (SCCPSolver & Solver, Module & M, FunctionAnalysisManager * FAM, std::function< const TargetLibraryInfo &(Function &)> GetTLI, std::function< TargetTransformInfo &(Function &)> GetTTI, std::function< AssumptionCache &(Function &)> GetAC) inline
Definition at line 139 of file FunctionSpecialization.h.
References FAM, and M.
~FunctionSpecializer()
llvm::FunctionSpecializer::~FunctionSpecializer () inline
Definition at line 147 of file FunctionSpecialization.h.
Member Function Documentation
isClonedFunction()
bool llvm::FunctionSpecializer::isClonedFunction (Function * F) inline
Definition at line 153 of file FunctionSpecialization.h.
References llvm::SmallPtrSetImpl< PtrType >::count(), and F.
Referenced by runIPSCCP().
run()
bool FunctionSpecializer::run ()
Attempt to specialize functions in the module to enable constant propagation across function boundaries.
Returns
true if at least one function is specialized.
Definition at line 260 of file FunctionSpecialization.cpp.
References Arg, Cost, llvm::dbgs(), F, I, llvm::SmallVectorImpl< T >::insert(), LLVM_DEBUG, M, MaxClonesThreshold, llvm::min(), N, S, and llvm::SCCPSolver::solveWhileResolvedUndefsIn().
Referenced by runIPSCCP().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/FunctionSpecialization.h
lib/Transforms/IPO/FunctionSpecialization.cpp