LLVM: llvm::coverage::LineCoverageIterator Class Reference
llvm::coverage::LineCoverageIterator Class Reference
An iterator over the LineCoverageStats objects for lines described by a CoverageData instance.
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Member Functions
LineCoverageIterator (const CoverageData &CD)
LineCoverageIterator (const CoverageData &CD, unsigned Line)
bool operator== (const LineCoverageIterator &R) const
const LineCoverageStats & operator* () const
LineCoverageIterator & operator++ ()
LineCoverageIterator getEnd () const
Public Member Functions inherited from llvm::iterator_facade_base< LineCoverageIterator, std::forward_iterator_tag, const LineCoverageStats >
LineCoverageIterator operator+ (std::ptrdiff_t n) const
LineCoverageIterator operator- (std::ptrdiff_t n) const
LineCoverageIterator & operator++ ()
LineCoverageIterator operator++ (int)
LineCoverageIterator & operator-- ()
LineCoverageIterator operator-- (int)
bool operator!= (const LineCoverageIterator &RHS) const
bool operator> (const LineCoverageIterator &RHS) const
bool operator<= (const LineCoverageIterator &RHS) const
bool operator>= (const LineCoverageIterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< LineCoverageIterator, std::forward_iterator_tag, const LineCoverageStats >
using iterator_category = std::forward_iterator_tag
using value_type = const LineCoverageStats
using difference_type = std::ptrdiff_t
using pointer = const LineCoverageStats *
using reference = const LineCoverageStats &
Protected Types inherited from llvm::iterator_facade_base< LineCoverageIterator, std::forward_iterator_tag, const LineCoverageStats >
enum
Detailed Description
An iterator over the LineCoverageStats objects for lines described by a CoverageData instance.
Definition at line 712 of file CoverageMapping.h.
Constructor & Destructor Documentation
LineCoverageIterator() [1/2]
llvm::coverage::LineCoverageIterator::LineCoverageIterator (const CoverageData & CD) inline
Definition at line 717 of file CoverageMapping.h.
LineCoverageIterator() [2/2]
llvm::coverage::LineCoverageIterator::LineCoverageIterator (const CoverageData & CD, unsigned Line) inline
Definition at line 720 of file CoverageMapping.h.
References operator++().
Member Function Documentation
getEnd()
LineCoverageIterator llvm::coverage::LineCoverageIterator::getEnd () const inline
Definition at line 734 of file CoverageMapping.h.
References llvm::coverage::CoverageData::end().
operator*()
const LineCoverageStats& llvm::coverage::LineCoverageIterator::operator* () const inline
Definition at line 730 of file CoverageMapping.h.
operator++()
LineCoverageIterator & LineCoverageIterator::operator++ ()
Definition at line 905 of file CoverageMapping.cpp.
References llvm::coverage::CoverageData::end().
Referenced by LineCoverageIterator().
operator==()
bool llvm::coverage::LineCoverageIterator::operator== (const LineCoverageIterator & R) const inline
Definition at line 726 of file CoverageMapping.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMapping.h
lib/ProfileData/Coverage/CoverageMapping.cpp