LLVM: llvm::DebugCounter Class Reference
llvm::DebugCounter Class Reference
#include "llvm/Support/DebugCounter.h"
Public Types
typedef UniqueVector< std::string > CounterVector
Public Member Functions
void push_back (const std::string &)
LLVM_DUMP_METHOD void dump () const
void print (raw_ostream &OS) const
unsigned getCounterId (const std::string &Name) const
unsigned int getNumCounters () const
std::pair< std::string, std::string > getCounterInfo (unsigned ID) const
CounterVector::const_iterator begin () const
CounterVector::const_iterator end () const
Static Public Member Functions
static DebugCounter & instance ()
Returns a reference to the singleton instance.
static unsigned registerCounter (StringRef Name, StringRef Desc)
static bool shouldExecute (unsigned CounterName)
static bool isCounterSet (unsigned ID)
static int64_t getCounterValue (unsigned ID)
static void setCounterValue (unsigned ID, int64_t Count)
static void enableAllCounters ()
static bool isCountingEnabled ()
Detailed Description
Definition at line 56 of file DebugCounter.h.
Member Typedef Documentation
CounterVector
typedef UniqueVector<std::string> llvm::DebugCounter::CounterVector
Definition at line 137 of file DebugCounter.h.
Member Function Documentation
begin()
CounterVector::const_iterator llvm::DebugCounter::begin () const inline
Definition at line 138 of file DebugCounter.h.
References llvm::UniqueVector< T >::begin().
dump()
LLVM_DUMP_METHOD void DebugCounter::dump () const
Definition at line 150 of file DebugCounter.cpp.
References llvm::dbgs(), and print().
enableAllCounters()
static void llvm::DebugCounter::enableAllCounters () inline static
Definition at line 148 of file DebugCounter.h.
References instance().
Referenced by push_back().
end()
CounterVector::const_iterator llvm::DebugCounter::end () const inline
Definition at line 141 of file DebugCounter.h.
References llvm::UniqueVector< T >::end().
getCounterId()
unsigned llvm::DebugCounter::getCounterId (const std::string & Name) const inline
Definition at line 124 of file DebugCounter.h.
References llvm::UniqueVector< T >::idFor().
Referenced by print(), and push_back().
getCounterInfo()
std::pair<std::string, std::string> llvm::DebugCounter::getCounterInfo (unsigned ID) const inline
Definition at line 132 of file DebugCounter.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
getCounterValue()
static int64_t llvm::DebugCounter::getCounterValue (unsigned ID) inline static
Definition at line 105 of file DebugCounter.h.
References assert(), and instance().
getNumCounters()
unsigned int llvm::DebugCounter::getNumCounters () const inline
Definition at line 129 of file DebugCounter.h.
References llvm::UniqueVector< T >::size().
instance()
DebugCounter & DebugCounter::instance () static
Returns a reference to the singleton instance.
Definition at line 77 of file DebugCounter.cpp.
References llvm::RISCVFenceField::O.
Referenced by enableAllCounters(), getCounterValue(), llvm::initDebugCounterOptions(), isCounterSet(), isCountingEnabled(), print(), registerCounter(), setCounterValue(), and shouldExecute().
isCounterSet()
static bool llvm::DebugCounter::isCounterSet (unsigned ID) inline static
Definition at line 100 of file DebugCounter.h.
References instance().
isCountingEnabled()
static bool llvm::DebugCounter::isCountingEnabled () inline static
Definition at line 150 of file DebugCounter.h.
References instance().
Referenced by shouldExecute().
print()
void DebugCounter::print (raw_ostream & OS) const
Definition at line 135 of file DebugCounter.cpp.
References llvm::UniqueVector< T >::begin(), llvm::UniqueVector< T >::end(), getCounterId(), instance(), llvm::left_justify(), OS, and llvm::sort().
Referenced by dump().
push_back()
void DebugCounter::push_back (const std::string & Val)
Definition at line 84 of file DebugCounter.cpp.
References enableAllCounters(), llvm::errs(), getCounterId(), and llvm::StringRef::split().
registerCounter()
static unsigned llvm::DebugCounter::registerCounter (StringRef Name, StringRef Desc) inline static
Definition at line 69 of file DebugCounter.h.
References instance().
setCounterValue()
static void llvm::DebugCounter::setCounterValue (unsigned ID, int64_t Count) inline static
Definition at line 113 of file DebugCounter.h.
References instance().
shouldExecute()
static bool llvm::DebugCounter::shouldExecute (unsigned CounterName) inline static
Definition at line 72 of file DebugCounter.h.
References instance(), and isCountingEnabled().
Referenced by checkAndReplaceCondition(), DCEInstruction(), llvm::getKnowledgeForValue(), llvm::Negator::Negate(), optimizeDivRem(), optimizeSQRT(), and llvm::InstCombinerImpl::run().
The documentation for this class was generated from the following files:
include/llvm/Support/DebugCounter.h
lib/Support/DebugCounter.cpp