LLVM: llvm::Argument Class Reference
llvm::Argument Class Reference final
This class represents an incoming formal argument to a Function.
#include "llvm/IR/Argument.h"
Public Member Functions
Argument (Type *Ty, const Twine &Name="", Function *F=nullptr, unsigned ArgNo=0)
Argument constructor.
const Function * getParent () const
Function * getParent ()
unsigned getArgNo () const
Return the index of this formal argument in its containing function.
bool hasNonNullAttr (bool AllowUndefOrPoison=true) const
Return true if this argument has the nonnull attribute.
uint64_t getDereferenceableBytes () const
If this argument has the dereferenceable attribute, return the number of bytes known to be dereferenceable.
uint64_t getDereferenceableOrNullBytes () const
If this argument has the dereferenceable_or_null attribute, return the number of bytes known to be dereferenceable.
bool hasByValAttr () const
Return true if this argument has the byval attribute.
bool hasByRefAttr () const
Return true if this argument has the byref attribute.
bool hasSwiftSelfAttr () const
Return true if this argument has the swiftself attribute.
bool hasSwiftErrorAttr () const
Return true if this argument has the swifterror attribute.
bool hasPassPointeeByValueCopyAttr () const
Return true if this argument has the byval, inalloca, or preallocated attribute.
uint64_t getPassPointeeByValueCopySize (const DataLayout &DL) const
If this argument satisfies has hasPassPointeeByValueAttr, return the in-memory ABI size copied to the stack for the call.
bool hasPointeeInMemoryValueAttr () const
Return true if this argument has the byval, sret, inalloca, preallocated, or byref attribute.
Type * getPointeeInMemoryValueType () const
If hasPointeeInMemoryValueAttr returns true, the in-memory ABI type is returned.
uint64_t getParamAlignment () const
If this is a byval or inalloca argument, return its alignment.
MaybeAlign getParamAlign () const
If this is a byval or inalloca argument, return its alignment.
MaybeAlign getParamStackAlign () const
Type * getParamByValType () const
If this is a byval argument, return its type.
Type * getParamStructRetType () const
If this is an sret argument, return its type.
Type * getParamByRefType () const
If this is a byref argument, return its type.
Type * getParamInAllocaType () const
If this is an inalloca argument, return its type.
bool hasNestAttr () const
Return true if this argument has the nest attribute.
bool hasNoAliasAttr () const
Return true if this argument has the noalias attribute.
bool hasNoCaptureAttr () const
Return true if this argument has the nocapture attribute.
bool hasNoFreeAttr () const
Return true if this argument has the nofree attribute.
bool hasStructRetAttr () const
Return true if this argument has the sret attribute.
bool hasInRegAttr () const
Return true if this argument has the inreg attribute.
bool hasReturnedAttr () const
Return true if this argument has the returned attribute.
bool onlyReadsMemory () const
Return true if this argument has the readonly or readnone attribute.
bool hasInAllocaAttr () const
Return true if this argument has the inalloca attribute.
bool hasPreallocatedAttr () const
Return true if this argument has the preallocated attribute.
bool hasZExtAttr () const
Return true if this argument has the zext attribute.
bool hasSExtAttr () const
Return true if this argument has the sext attribute.
void addAttrs (AttrBuilder &B)
Add attributes to an argument.
void addAttr (Attribute::AttrKind Kind)
void addAttr (Attribute Attr)
void removeAttr (Attribute::AttrKind Kind)
Remove attributes from an argument.
void removeAttrs (const AttributeMask &AM)
bool hasAttribute (Attribute::AttrKind Kind) const
Check if an argument has a given attribute.
Attribute getAttribute (Attribute::AttrKind Kind) const
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static bool classof (const Value *V)
Method for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Friends
class Function
Additional Inherited Members
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * >> &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This class represents an incoming formal argument to a Function.
A formal argument, since it is `‘formal’', does not contain an actual value but instead represents the type, argument number, and attributes of an argument for a specific function. When used in the body of said function, the argument of course represents the value of the actual argument that the function was called with.
Definition at line 28 of file Argument.h.
Constructor & Destructor Documentation
Argument()
Argument::Argument (Type * Ty, const Twine & Name = "", Function * F = nullptr, unsigned ArgNo = 0) explicit
Argument constructor.
Definition at line 87 of file Function.cpp.
References llvm::Value::setName().
Member Function Documentation
addAttr() [1/2]
void Argument::addAttr (Attribute Attr)
Definition at line 289 of file Function.cpp.
References llvm::Function::addParamAttr(), getArgNo(), and getParent().
addAttr() [2/2]
void Argument::addAttr (Attribute::AttrKind Kind)
Definition at line 285 of file Function.cpp.
References llvm::Function::addParamAttr(), getArgNo(), and getParent().
addAttrs()
void Argument::addAttrs (AttrBuilder & B)
Add attributes to an argument.
Definition at line 279 of file Function.cpp.
References llvm::AArch64CC::AL, B, getArgNo(), llvm::Function::getAttributes(), llvm::Function::getContext(), getParent(), and llvm::Function::setAttributes().
classof()
static bool llvm::Argument::classof (const Value * V) inline static
Method for support type inquiry through isa, cast, and dyn_cast.
Definition at line 173 of file Argument.h.
getArgNo()
unsigned llvm::Argument::getArgNo () const inline
Return the index of this formal argument in its containing function.
For example in "void foo(int a, float b)" a is 0 and b is 1.
Definition at line 46 of file Argument.h.
References assert().
Referenced by addAttr(), addAttrs(), getAttribute(), getDereferenceableBytes(), getDereferenceableOrNullBytes(), getParamAlign(), getParamByRefType(), getParamByValType(), getParamInAllocaType(), getParamStackAlign(), getParamStructRetType(), getPassPointeeByValueCopySize(), getPointeeInMemoryValueType(), hasAttribute(), hasNonNullAttr(), hasPassPointeeByValueCopyAttr(), hasPointeeInMemoryValueAttr(), hasSwiftErrorAttr(), hasSwiftSelfAttr(), onlyReadsMemory(), removeAttr(), and removeAttrs().
getAttribute()
Attribute Argument::getAttribute (Attribute::AttrKind Kind) const
Definition at line 307 of file Function.cpp.
References getArgNo(), llvm::Function::getParamAttribute(), and getParent().
getDereferenceableBytes()
uint64_t Argument::getDereferenceableBytes () const
If this argument has the dereferenceable attribute, return the number of bytes known to be dereferenceable.
Otherwise, zero is returned.
Definition at line 220 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamDereferenceableBytes(), getParent(), and llvm::Value::getType().
Referenced by hasNonNullAttr().
getDereferenceableOrNullBytes()
uint64_t Argument::getDereferenceableOrNullBytes () const
If this argument has the dereferenceable_or_null attribute, return the number of bytes known to be dereferenceable.
Otherwise, zero is returned.
Definition at line 226 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamDereferenceableOrNullBytes(), getParent(), and llvm::Value::getType().
getParamAlign()
MaybeAlign Argument::getParamAlign () const
If this is a byval or inalloca argument, return its alignment.
Definition at line 191 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamAlign(), getParent(), and llvm::Value::getType().
getParamAlignment()
uint64_t llvm::Argument::getParamAlignment () const
If this is a byval or inalloca argument, return its alignment.
FIXME: Remove this function once transition to Align is over. Use getParamAlign() instead.
getParamByRefType()
Type * Argument::getParamByRefType () const
If this is a byref argument, return its type.
Definition at line 210 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamByRefType(), getParent(), and llvm::Value::getType().
getParamByValType()
Type * Argument::getParamByValType () const
If this is a byval argument, return its type.
Definition at line 200 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamByValType(), getParent(), and llvm::Value::getType().
getParamInAllocaType()
Type * Argument::getParamInAllocaType () const
If this is an inalloca argument, return its type.
Definition at line 215 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamInAllocaType(), getParent(), and llvm::Value::getType().
getParamStackAlign()
MaybeAlign Argument::getParamStackAlign () const
Definition at line 196 of file Function.cpp.
References getArgNo(), llvm::Function::getParamStackAlign(), and getParent().
getParamStructRetType()
Type * Argument::getParamStructRetType () const
If this is an sret argument, return its type.
Definition at line 205 of file Function.cpp.
References assert(), getArgNo(), llvm::Function::getParamStructRetType(), getParent(), and llvm::Value::getType().
getParent() [1/2]
Function* llvm::Argument::getParent () inline
Definition at line 41 of file Argument.h.
getParent() [2/2]
const Function* llvm::Argument::getParent () const inline
Definition at line 40 of file Argument.h.
Referenced by addAttr(), addAttrs(), getAttribute(), getDereferenceableBytes(), getDereferenceableOrNullBytes(), getParamAlign(), getParamByRefType(), getParamByValType(), getParamInAllocaType(), getParamStackAlign(), getParamStructRetType(), getPassPointeeByValueCopySize(), getPointeeInMemoryValueType(), hasAttribute(), hasNonNullAttr(), hasPassPointeeByValueCopyAttr(), hasPointeeInMemoryValueAttr(), hasSwiftErrorAttr(), hasSwiftSelfAttr(), onlyReadsMemory(), removeAttr(), and removeAttrs().
getPassPointeeByValueCopySize()
uint64_t Argument::getPassPointeeByValueCopySize (const DataLayout & DL) const
If this argument satisfies has hasPassPointeeByValueAttr, return the in-memory ABI size copied to the stack for the call.
Otherwise, return 0.
Definition at line 177 of file Function.cpp.
References DL, getArgNo(), llvm::Function::getAttributes(), getMemoryParamAllocType(), llvm::AttributeList::getParamAttrs(), and getParent().
getPointeeInMemoryValueType()
Type * Argument::getPointeeInMemoryValueType () const
If hasPointeeInMemoryValueAttr returns true, the in-memory ABI type is returned.
Otherwise, nullptr.
Definition at line 185 of file Function.cpp.
References getArgNo(), llvm::Function::getAttributes(), getMemoryParamAllocType(), llvm::AttributeList::getParamAttrs(), and getParent().
hasAttribute()
bool Argument::hasAttribute (Attribute::AttrKind Kind) const
Check if an argument has a given attribute.
Definition at line 303 of file Function.cpp.
References getArgNo(), getParent(), and llvm::Function::hasParamAttribute().
Referenced by hasByRefAttr(), hasByValAttr(), hasInAllocaAttr(), hasInRegAttr(), hasNestAttr(), hasNoAliasAttr(), hasNoCaptureAttr(), hasNoFreeAttr(), hasPreallocatedAttr(), hasReturnedAttr(), hasSExtAttr(), hasStructRetAttr(), and hasZExtAttr().
hasByRefAttr()
bool Argument::hasByRefAttr () const
Return true if this argument has the byref attribute.
Definition at line 114 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasByValAttr()
bool Argument::hasByValAttr () const
Return true if this argument has the byval attribute.
Definition at line 109 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasInAllocaAttr()
bool Argument::hasInAllocaAttr () const
Return true if this argument has the inalloca attribute.
Definition at line 128 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasInRegAttr()
bool Argument::hasInRegAttr () const
Return true if this argument has the inreg attribute.
Definition at line 257 of file Function.cpp.
References hasAttribute().
hasNestAttr()
bool Argument::hasNestAttr () const
Return true if this argument has the nest attribute.
Definition at line 232 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasNoAliasAttr()
bool Argument::hasNoAliasAttr () const
Return true if this argument has the noalias attribute.
Definition at line 237 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasNoCaptureAttr()
bool Argument::hasNoCaptureAttr () const
Return true if this argument has the nocapture attribute.
Definition at line 242 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasNoFreeAttr()
bool Argument::hasNoFreeAttr () const
Return true if this argument has the nofree attribute.
Definition at line 247 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasNonNullAttr()
bool Argument::hasNonNullAttr (bool AllowUndefOrPoison = true) const
Return true if this argument has the nonnull attribute.
Also returns true if at least one byte is known to be dereferenceable and the pointer is in addrspace(0). If AllowUndefOrPoison is true, respect the semantics of nonnull attribute and return true even if the argument can be undef or poison.
Definition at line 96 of file Function.cpp.
References getArgNo(), getDereferenceableBytes(), getParent(), llvm::Value::getType(), and llvm::NullPointerIsDefined().
hasPassPointeeByValueCopyAttr()
bool Argument::hasPassPointeeByValueCopyAttr () const
Return true if this argument has the byval, inalloca, or preallocated attribute.
These attributes represent arguments being passed by value, with an associated copy between the caller and callee
Definition at line 139 of file Function.cpp.
References Attrs, getArgNo(), llvm::Function::getAttributes(), getParent(), and llvm::Value::getType().
hasPointeeInMemoryValueAttr()
bool Argument::hasPointeeInMemoryValueAttr () const
Return true if this argument has the byval, sret, inalloca, preallocated, or byref attribute.
These attributes represent arguments being passed by value (which may or may not involve a stack copy)
Definition at line 147 of file Function.cpp.
References Attrs, getArgNo(), llvm::Function::getAttributes(), getParent(), and llvm::Value::getType().
hasPreallocatedAttr()
bool Argument::hasPreallocatedAttr () const
Return true if this argument has the preallocated attribute.
Definition at line 133 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasReturnedAttr()
bool Argument::hasReturnedAttr () const
Return true if this argument has the returned attribute.
Definition at line 261 of file Function.cpp.
References hasAttribute().
hasSExtAttr()
bool Argument::hasSExtAttr () const
Return true if this argument has the sext attribute.
Definition at line 269 of file Function.cpp.
References hasAttribute().
hasStructRetAttr()
bool Argument::hasStructRetAttr () const
Return true if this argument has the sret attribute.
Definition at line 252 of file Function.cpp.
References llvm::Value::getType(), and hasAttribute().
hasSwiftErrorAttr()
bool Argument::hasSwiftErrorAttr () const
Return true if this argument has the swifterror attribute.
Definition at line 124 of file Function.cpp.
References getArgNo(), getParent(), and llvm::Function::hasParamAttribute().
hasSwiftSelfAttr()
bool Argument::hasSwiftSelfAttr () const
Return true if this argument has the swiftself attribute.
Definition at line 120 of file Function.cpp.
References getArgNo(), getParent(), and llvm::Function::hasParamAttribute().
hasZExtAttr()
bool Argument::hasZExtAttr () const
Return true if this argument has the zext attribute.
Definition at line 265 of file Function.cpp.
References hasAttribute().
onlyReadsMemory()
bool Argument::onlyReadsMemory () const
Return true if this argument has the readonly or readnone attribute.
Definition at line 273 of file Function.cpp.
References Attrs, getArgNo(), llvm::Function::getAttributes(), and getParent().
removeAttr()
void Argument::removeAttr (Attribute::AttrKind Kind)
Remove attributes from an argument.
Definition at line 293 of file Function.cpp.
References getArgNo(), getParent(), and llvm::Function::removeParamAttr().
removeAttrs()
void Argument::removeAttrs (const AttributeMask & AM)
Definition at line 297 of file Function.cpp.
References llvm::AArch64CC::AL, getArgNo(), llvm::Function::getAttributes(), llvm::Function::getContext(), getParent(), and llvm::Function::setAttributes().
Friends And Related Function Documentation
Function
friend class Function friend
Definition at line 32 of file Argument.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Argument.h
lib/IR/Function.cpp