LLVM: llvm::SCEVRewriteVisitor< SC > Class Template Reference
llvm::SCEVRewriteVisitor< SC > Class Template Reference
This visitor recursively visits a SCEV expression and re-writes it.
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Member Functions
SCEVRewriteVisitor (ScalarEvolution &SE)
const SCEV * visit (const SCEV *S)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitPtrToIntExpr (const SCEVPtrToIntExpr *Expr)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitSMinExpr (const SCEVSMinExpr *Expr)
const SCEV * visitUMinExpr (const SCEVUMinExpr *Expr)
const SCEV * visitSequentialUMinExpr (const SCEVSequentialUMinExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SC, const SCEV * >
const SCEV * visit (const SCEV *S)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *S)
Protected Attributes
ScalarEvolution & SE
DenseMap< const SCEV *, const SCEV * > RewriteResults
Detailed Description
template<typename SC>
class llvm::SCEVRewriteVisitor< SC >
This visitor recursively visits a SCEV expression and re-writes it.
The result from each visit is cached, so it will return the same SCEV for the same input.
Definition at line 738 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVRewriteVisitor()
template<typename SC > llvm::SCEVRewriteVisitor< SC >::SCEVRewriteVisitor (ScalarEvolution & SE) inline
Definition at line 749 of file ScalarEvolutionExpressions.h.
Member Function Documentation
visit()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visit (const SCEV * S) inline
Definition at line 751 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitAddExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitAddRecExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitMulExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitSequentialUMinExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitSMaxExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitSMinExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitUMaxExpr(), and llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitUMinExpr().
visitAddExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitAddExpr (const SCEVAddExpr * Expr) inline
Definition at line 791 of file ScalarEvolutionExpressions.h.
visitAddRecExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitAddRecExpr (const SCEVAddRecExpr * Expr) inline
Definition at line 818 of file ScalarEvolutionExpressions.h.
visitConstant()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitConstant (const SCEVConstant * Constant) inline
Definition at line 761 of file ScalarEvolutionExpressions.h.
visitCouldNotCompute()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitCouldNotCompute (const SCEVCouldNotCompute * Expr) inline
Definition at line 882 of file ScalarEvolutionExpressions.h.
visitMulExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitMulExpr (const SCEVMulExpr * Expr) inline
Definition at line 801 of file ScalarEvolutionExpressions.h.
visitPtrToIntExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitPtrToIntExpr (const SCEVPtrToIntExpr * Expr) inline
Definition at line 763 of file ScalarEvolutionExpressions.h.
visitSequentialUMinExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitSequentialUMinExpr (const SCEVSequentialUMinExpr * Expr) inline
Definition at line 870 of file ScalarEvolutionExpressions.h.
visitSignExtendExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitSignExtendExpr (const SCEVSignExtendExpr * Expr) inline
Definition at line 784 of file ScalarEvolutionExpressions.h.
Referenced by SCEVLoopGuardRewriter::visitSignExtendExpr().
visitSMaxExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitSMaxExpr (const SCEVSMaxExpr * Expr) inline
Definition at line 830 of file ScalarEvolutionExpressions.h.
visitSMinExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitSMinExpr (const SCEVSMinExpr * Expr) inline
Definition at line 850 of file ScalarEvolutionExpressions.h.
visitTruncateExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitTruncateExpr (const SCEVTruncateExpr * Expr) inline
Definition at line 770 of file ScalarEvolutionExpressions.h.
visitUDivExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitUDivExpr (const SCEVUDivExpr * Expr) inline
Definition at line 811 of file ScalarEvolutionExpressions.h.
visitUMaxExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitUMaxExpr (const SCEVUMaxExpr * Expr) inline
Definition at line 840 of file ScalarEvolutionExpressions.h.
visitUMinExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitUMinExpr (const SCEVUMinExpr * Expr) inline
Definition at line 860 of file ScalarEvolutionExpressions.h.
visitUnknown()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitUnknown (const SCEVUnknown * Expr) inline
Definition at line 880 of file ScalarEvolutionExpressions.h.
visitZeroExtendExpr()
template<typename SC > const SCEV* llvm::SCEVRewriteVisitor< SC >::visitZeroExtendExpr (const SCEVZeroExtendExpr * Expr) inline
Definition at line 777 of file ScalarEvolutionExpressions.h.
Referenced by SCEVLoopGuardRewriter::visitZeroExtendExpr().
Member Data Documentation
RewriteResults
template<typename SC > DenseMap<const SCEV *, const SCEV *> llvm::SCEVRewriteVisitor< SC >::RewriteResults protected
Definition at line 746 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visit().
SE
template<typename SC > ScalarEvolution& llvm::SCEVRewriteVisitor< SC >::SE protected
Definition at line 740 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitAddExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitAddRecExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitMulExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitPtrToIntExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitSequentialUMinExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitSignExtendExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitSMaxExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitSMinExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitTruncateExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitUDivExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitUMaxExpr(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitUMinExpr(), and llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visitZeroExtendExpr().
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h