LLVM: llvm::PreservedCFGCheckerInstrumentation Class Reference
llvm::PreservedCFGCheckerInstrumentation Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Classes
struct BBGuard
struct CFG
Public Member Functions
void registerCallbacks (PassInstrumentationCallbacks &PIC, FunctionAnalysisManager &FAM)
Static Public Attributes
static cl::opt< bool > VerifyPreservedCFG
Detailed Description
Definition at line 110 of file StandardInstrumentations.h.
Member Function Documentation
registerCallbacks()
void PreservedCFGCheckerInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC, FunctionAnalysisManager & FAM)
Definition at line 1060 of file StandardInstrumentations.cpp.
References llvm::PreservedAnalyses::allAnalysesInSetPreserved(), assert(), llvm::dbgs(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), IR, P, Pass, PIC, llvm::PreservedCFGCheckerInstrumentation::CFG::printDiff(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::registerPass(), llvm::report_fatal_error(), and VerifyPreservedCFG.
Referenced by llvm::StandardInstrumentations::registerCallbacks().
Member Data Documentation
VerifyPreservedCFG
cl::opt< bool > PreservedCFGCheckerInstrumentation::VerifyPreservedCFG static
Definition at line 155 of file StandardInstrumentations.h.
Referenced by registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp