LLVM: llvm::VPBuilder Class Reference
llvm::VPBuilder Class Reference
VPlan-based builder utility analogous to IRBuilder.
#include "Transforms/Vectorize/LoopVectorizationPlanner.h"
Classes
class InsertPointGuard
RAII object that stores the current insertion point and restores it when the object is destroyed.
class VPInsertPoint
InsertPoint - A saved insertion point.
Public Member Functions
VPBuilder ()=default
void clearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
VPBasicBlock * getInsertBlock () const
VPBasicBlock::iterator getInsertPoint () const
void restoreIP (VPInsertPoint IP)
Sets the current insert point to a previously-saved location.
void setInsertPoint (VPBasicBlock *TheBB)
This specifies that created VPInstructions should be appended to the end of the specified block.
void setInsertPoint (VPBasicBlock *TheBB, VPBasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
VPInstruction * insert (VPInstruction *I) const
Insert and return the specified instruction.
VPValue * createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, Instruction *Inst=nullptr, const Twine &Name="")
Create an N-ary operation with Opcode, Operands and set Inst as its underlying Instruction.
VPValue * createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, DebugLoc DL, const Twine &Name="")
VPValue * createNot (VPValue *Operand, DebugLoc DL, const Twine &Name="")
VPValue * createAnd (VPValue *LHS, VPValue *RHS, DebugLoc DL, const Twine &Name="")
VPValue * createOr (VPValue *LHS, VPValue *RHS, DebugLoc DL, const Twine &Name="")
VPValue * createSelect (VPValue *Cond, VPValue *TrueVal, VPValue *FalseVal, DebugLoc DL, const Twine &Name="")
Detailed Description
VPlan-based builder utility analogous to IRBuilder.
Definition at line 43 of file LoopVectorizationPlanner.h.
Constructor & Destructor Documentation
VPBuilder()
llvm::VPBuilder::VPBuilder () default
Member Function Documentation
clearInsertionPoint()
void llvm::VPBuilder::clearInsertionPoint () inline
Clear the insertion point: created instructions will not be inserted into a block.
Definition at line 67 of file LoopVectorizationPlanner.h.
References BB.
Referenced by restoreIP().
createAnd()
VPValue* llvm::VPBuilder::createAnd (VPValue * LHS, VPValue * RHS, DebugLoc DL, const Twine & Name = "") inline
Definition at line 144 of file LoopVectorizationPlanner.h.
References DL, LHS, and RHS.
createNaryOp() [1/2]
VPValue* llvm::VPBuilder::createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, DebugLoc DL, const Twine & Name = "") inline
Definition at line 135 of file LoopVectorizationPlanner.h.
References DL, and Operands.
createNaryOp() [2/2]
VPValue* llvm::VPBuilder::createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, Instruction * Inst = nullptr, const Twine & Name = "") inline
Create an N-ary operation with Opcode, Operands and set Inst as its underlying Instruction.
Definition at line 126 of file LoopVectorizationPlanner.h.
References DL, Operands, and llvm::VPValue::setUnderlyingValue().
Referenced by createSelect().
createNot()
VPValue* llvm::VPBuilder::createNot (VPValue * Operand, DebugLoc DL, const Twine & Name = "") inline
Definition at line 140 of file LoopVectorizationPlanner.h.
References DL, and llvm::VPInstruction::Not.
createOr()
VPValue* llvm::VPBuilder::createOr (VPValue * LHS, VPValue * RHS, DebugLoc DL, const Twine & Name = "") inline
Definition at line 149 of file LoopVectorizationPlanner.h.
References DL, LHS, and RHS.
createSelect()
VPValue* llvm::VPBuilder::createSelect (VPValue * Cond, VPValue * TrueVal, VPValue * FalseVal, DebugLoc DL, const Twine & Name = "") inline
Definition at line 154 of file LoopVectorizationPlanner.h.
References Cond, createNaryOp(), DL, llvm::tgtok::FalseVal, Select, and llvm::tgtok::TrueVal.
getInsertBlock()
VPBasicBlock* llvm::VPBuilder::getInsertBlock () const inline
Definition at line 72 of file LoopVectorizationPlanner.h.
References BB.
getInsertPoint()
VPBasicBlock::iterator llvm::VPBuilder::getInsertPoint () const inline
Definition at line 73 of file LoopVectorizationPlanner.h.
insert()
VPInstruction* llvm::VPBuilder::insert (VPInstruction * I) const inline
Insert and return the specified instruction.
Definition at line 119 of file LoopVectorizationPlanner.h.
References BB, and I.
restoreIP()
void llvm::VPBuilder::restoreIP (VPInsertPoint IP) inline
Sets the current insert point to a previously-saved location.
Definition at line 96 of file LoopVectorizationPlanner.h.
References clearInsertionPoint(), llvm::VPBuilder::VPInsertPoint::getBlock(), llvm::VPBuilder::VPInsertPoint::getPoint(), llvm::VPBuilder::VPInsertPoint::isSet(), and setInsertPoint().
setInsertPoint() [1/2]
void llvm::VPBuilder::setInsertPoint (VPBasicBlock * TheBB) inline
This specifies that created VPInstructions should be appended to the end of the specified block.
Definition at line 105 of file LoopVectorizationPlanner.h.
References assert(), and BB.
Referenced by restoreIP().
setInsertPoint() [2/2]
void llvm::VPBuilder::setInsertPoint (VPBasicBlock * TheBB, VPBasicBlock::iterator IP) inline
This specifies that created instructions should be inserted at the specified point.
Definition at line 113 of file LoopVectorizationPlanner.h.
References BB.
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/LoopVectorizationPlanner.h