LLVM: llvm::LNICMPass Class Reference
llvm::LNICMPass Class Reference
Performs LoopNest Invariant Code Motion Pass.
#include "llvm/Transforms/Scalar/LICM.h"
Public Member Functions
LNICMPass (unsigned MssaOptCap, unsigned MssaNoAccForPromotionCap, bool AllowSpeculation)
LNICMPass (LICMOptions Opts)
PreservedAnalyses run (LoopNest &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< LNICMPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LNICMPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Performs LoopNest Invariant Code Motion Pass.
Definition at line 84 of file LICM.h.
Constructor & Destructor Documentation
LNICMPass() [1/2]
llvm::LNICMPass::LNICMPass (unsigned MssaOptCap, unsigned MssaNoAccForPromotionCap, bool AllowSpeculation) inline
Definition at line 88 of file LICM.h.
LNICMPass() [2/2]
llvm::LNICMPass::LNICMPass (LICMOptions Opts) inline
Definition at line 92 of file LICM.h.
Member Function Documentation
printPipeline()
void LNICMPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 332 of file LICM.cpp.
References llvm::LICMOptions::AllowSpeculation, and OS.
run()
PreservedAnalyses LNICMPass::run (LoopNest & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 301 of file LICM.cpp.
References llvm::LoopStandardAnalysisResults::AA, llvm::LoopStandardAnalysisResults::AC, llvm::PreservedAnalyses::all(), llvm::LICMOptions::AllowSpeculation, llvm::LoopStandardAnalysisResults::DT, llvm::getLoopPassPreservedAnalyses(), llvm::LoopNest::getOutermostLoop(), llvm::LoopNest::getParent(), llvm::LoopStandardAnalysisResults::LI, llvm::LoopStandardAnalysisResults::MSSA, llvm::LICMOptions::MssaNoAccForPromotionCap, llvm::LICMOptions::MssaOptCap, llvm::report_fatal_error(), llvm::LoopStandardAnalysisResults::SE, llvm::LoopStandardAnalysisResults::TLI, and llvm::LoopStandardAnalysisResults::TTI.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LICM.h
lib/Transforms/Scalar/LICM.cpp