LLVM: llvm::objcopy::elf::DecompressedSection Class Reference
llvm::objcopy::elf::DecompressedSection Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
DecompressedSection (const CompressedSection &Sec)
Error accept (SectionVisitor &Visitor) const override
Error accept (MutableSectionVisitor &Visitor) override
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual Error initialize (SectionTableRef SecTable)
virtual void finalize ()
virtual Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove)
virtual Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove)
virtual void markSymbols ()
virtual void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &)
virtual bool hasContents () const
virtual void onRemove ()
Public Attributes
uint32_t ChType
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Detailed Description
Definition at line 563 of file ELFObject.h.
Constructor & Destructor Documentation
DecompressedSection()
llvm::objcopy::elf::DecompressedSection::DecompressedSection (const CompressedSection & Sec) inline explicit
Definition at line 568 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::Flags, llvm::objcopy::elf::CompressedSection::getDecompressedAlign(), llvm::objcopy::elf::CompressedSection::getDecompressedSize(), llvm::objcopy::elf::SectionBase::OriginalFlags, llvm::ELF::SHF_COMPRESSED, and llvm::objcopy::elf::SectionBase::Size.
Member Function Documentation
accept() [1/2]
Error DecompressedSection::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 483 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error DecompressedSection::accept (SectionVisitor & Visitor) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 479 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
Member Data Documentation
ChType
uint32_t llvm::objcopy::elf::DecompressedSection::ChType
Definition at line 567 of file ELFObject.h.
Referenced by llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp