LLVM: llvm::gsym::DwarfTransformer Class Reference
llvm::gsym::DwarfTransformer Class Reference
A class that transforms the DWARF in a DWARFContext into GSYM information by populating the GsymCreator object that it is constructed with.
#include "llvm/DebugInfo/GSYM/DwarfTransformer.h"
Public Member Functions
DwarfTransformer (DWARFContext &D, raw_ostream &OS, GsymCreator &G)
Create a DWARF transformer.
llvm::Error convert (uint32_t NumThreads)
Extract the DWARF from the supplied object file and convert it into the Gsym format in the GsymCreator object that is passed in.
llvm::Error verify (StringRef GsymPath)
Friends
class DwarfTransformerTest
Detailed Description
A class that transforms the DWARF in a DWARFContext into GSYM information by populating the GsymCreator object that it is constructed with.
This class supports converting all DW_TAG_subprogram DIEs into gsym::FunctionInfo objects that includes line table information and inline function information. Creating a separate class to transform this data allows this class to be unit tested.
Definition at line 32 of file DwarfTransformer.h.
Constructor & Destructor Documentation
DwarfTransformer()
llvm::gsym::DwarfTransformer::DwarfTransformer (DWARFContext & D, raw_ostream & OS, GsymCreator & G) inline
Create a DWARF transformer.
Parameters
D The DWARF to use when converting to GSYM.
OS The stream to log warnings and non fatal issues to.
G The GSYM creator to populate with the function information from the debug info.
Definition at line 43 of file DwarfTransformer.h.
Member Function Documentation
convert()
Error DwarfTransformer::convert (uint32_t NumThreads)
Extract the DWARF from the supplied object file and convert it into the Gsym format in the GsymCreator object that is passed in.
Returns an error if something fatal is encountered.
Returns
An error indicating any fatal issues that happen when parsing the DWARF, or Error::success() if all goes well.
Definition at line 428 of file DwarfTransformer.cpp.
References llvm::DWARFContext::compile_units(), llvm::raw_ostream::flush(), llvm::gsym::GsymCreator::getNumFunctionInfos(), llvm::DWARFUnit::getUnitDIE(), llvm::hardware_concurrency(), llvm::DWARFUnit::isDWOUnit(), pool, llvm::Error::success(), and llvm::dwarf::toString().
verify()
llvm::Error DwarfTransformer::verify (StringRef GsymPath)
Definition at line 499 of file DwarfTransformer.cpp.
References llvm::DILineInfoSpecifier::AbsoluteFilePath, Addr, llvm::count(), llvm::createStringError(), llvm::DWARFContext::getInliningInfoForAddress(), llvm::DWARFContext::getLineInfoForAddress(), HEX64, I, llvm::LinkageName, llvm::gsym::GsymReader::openFile(), llvm::gsym::FunctionInfo::size(), llvm::Error::success(), and llvm::object::SectionedAddress::UndefSection.
Friends And Related Function Documentation
DwarfTransformerTest
friend class DwarfTransformerTest friend
Definition at line 85 of file DwarfTransformer.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/GSYM/DwarfTransformer.h
lib/DebugInfo/GSYM/DwarfTransformer.cpp