LLVM: llvm::ConstantFolder Class Reference
llvm::ConstantFolder Class Reference final
ConstantFolder - Create constants with minimum, target independent, folding.
#include "llvm/IR/ConstantFolder.h"
Public Member Functions
ConstantFolder ()=default
Value * FoldBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS) const override
Value * FoldExactBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool IsExact) const override
Value * FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool HasNUW, bool HasNSW) const override
Value * FoldBinOpFMF (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, FastMathFlags FMF) const override
Value * FoldUnOpFMF (Instruction::UnaryOps Opc, Value *V, FastMathFlags FMF) const override
Value * FoldICmp (CmpInst::Predicate P, Value *LHS, Value *RHS) const override
Value * FoldGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, bool IsInBounds=false) const override
Value * FoldSelect (Value *C, Value *True, Value *False) const override
Value * FoldExtractValue (Value *Agg, ArrayRef< unsigned > IdxList) const override
Value * FoldInsertValue (Value *Agg, Value *Val, ArrayRef< unsigned > IdxList) const override
Value * FoldExtractElement (Value *Vec, Value *Idx) const override
Value * FoldInsertElement (Value *Vec, Value *NewElt, Value *Idx) const override
Value * FoldShuffleVector (Value *V1, Value *V2, ArrayRef< int > Mask) const override
Constant * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const override
Constant * CreatePointerCast (Constant *C, Type *DestTy) const override
Constant * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const override
Constant * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const override
Constant * CreateFPCast (Constant *C, Type *DestTy) const override
Constant * CreateBitCast (Constant *C, Type *DestTy) const override
Constant * CreateIntToPtr (Constant *C, Type *DestTy) const override
Constant * CreatePtrToInt (Constant *C, Type *DestTy) const override
Constant * CreateZExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateSExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateTruncOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const override
Public Member Functions inherited from llvm::IRBuilderFolder
virtual ~IRBuilderFolder ()
Detailed Description
ConstantFolder - Create constants with minimum, target independent, folding.
Definition at line 30 of file ConstantFolder.h.
Constructor & Destructor Documentation
ConstantFolder()
llvm::ConstantFolder::ConstantFolder () explicit default
Member Function Documentation
CreateBitCast()
Constant* llvm::ConstantFolder::CreateBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 200 of file ConstantFolder.h.
References CreateCast().
CreateCast()
Constant* llvm::ConstantFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 177 of file ConstantFolder.h.
References llvm::ConstantExpr::getCast().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
CreateFCmp()
Constant* llvm::ConstantFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 228 of file ConstantFolder.h.
References llvm::ConstantExpr::getCompare(), LHS, P, and RHS.
CreateFPCast()
Constant* llvm::ConstantFolder::CreateFPCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 196 of file ConstantFolder.h.
References llvm::ConstantExpr::getFPCast().
CreateIntCast()
Constant* llvm::ConstantFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 191 of file ConstantFolder.h.
References llvm::ConstantExpr::getIntegerCast(), and isSigned().
CreateIntToPtr()
Constant* llvm::ConstantFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 204 of file ConstantFolder.h.
References CreateCast().
CreatePointerBitCastOrAddrSpaceCast()
Constant* llvm::ConstantFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 186 of file ConstantFolder.h.
References llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast().
CreatePointerCast()
Constant* llvm::ConstantFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 182 of file ConstantFolder.h.
References llvm::ConstantExpr::getPointerCast().
CreatePtrToInt()
Constant* llvm::ConstantFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 208 of file ConstantFolder.h.
References CreateCast().
CreateSExtOrBitCast()
Constant* llvm::ConstantFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 216 of file ConstantFolder.h.
References llvm::ConstantExpr::getSExtOrBitCast().
CreateTruncOrBitCast()
Constant* llvm::ConstantFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 220 of file ConstantFolder.h.
References llvm::ConstantExpr::getTruncOrBitCast().
CreateZExtOrBitCast()
Constant* llvm::ConstantFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 212 of file ConstantFolder.h.
References llvm::ConstantExpr::getZExtOrBitCast().
FoldBinOp()
Value* llvm::ConstantFolder::FoldBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 43 of file ConstantFolder.h.
References llvm::ConstantFoldBinaryInstruction(), llvm::ConstantExpr::get(), llvm::ConstantExpr::isDesirableBinOp(), LHS, and RHS.
Referenced by FoldBinOpFMF().
FoldBinOpFMF()
Value* llvm::ConstantFolder::FoldBinOpFMF (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, FastMathFlags FMF) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 86 of file ConstantFolder.h.
References FoldBinOp(), LHS, and RHS.
FoldExactBinOp()
Value* llvm::ConstantFolder::FoldExactBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool IsExact) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 55 of file ConstantFolder.h.
References llvm::ConstantFoldBinaryInstruction(), llvm::ConstantExpr::get(), llvm::ConstantExpr::isDesirableBinOp(), llvm::PossiblyExactOperator::IsExact, LHS, and RHS.
FoldExtractElement()
Value* llvm::ConstantFolder::FoldExtractElement (Value * Vec, Value * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 146 of file ConstantFolder.h.
References llvm::ConstantExpr::getExtractElement().
FoldExtractValue()
Value* llvm::ConstantFolder::FoldExtractValue (Value * Agg, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 130 of file ConstantFolder.h.
References llvm::ConstantFoldExtractValueInstruction().
FoldGEP()
Value* llvm::ConstantFolder::FoldGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, bool IsInBounds = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 106 of file ConstantFolder.h.
References llvm::any_of(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getInBoundsGetElementPtr(), and Ptr.
FoldICmp()
Value* llvm::ConstantFolder::FoldICmp (CmpInst::Predicate P, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 98 of file ConstantFolder.h.
References llvm::ConstantExpr::getCompare(), LHS, P, and RHS.
FoldInsertElement()
Value* llvm::ConstantFolder::FoldInsertElement (Value * Vec, Value * NewElt, Value * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 154 of file ConstantFolder.h.
References llvm::ConstantExpr::getInsertElement().
FoldInsertValue()
Value* llvm::ConstantFolder::FoldInsertValue (Value * Agg, Value * Val, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 137 of file ConstantFolder.h.
References llvm::ConstantFoldInsertValueInstruction().
FoldNoWrapBinOp()
Value* llvm::ConstantFolder::FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool HasNUW, bool HasNSW) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 68 of file ConstantFolder.h.
References llvm::ConstantFoldBinaryInstruction(), llvm::ConstantExpr::get(), llvm::ConstantExpr::isDesirableBinOp(), LHS, llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, and RHS.
FoldSelect()
Value* llvm::ConstantFolder::FoldSelect (Value * C, Value * True, Value * False) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 121 of file ConstantFolder.h.
References CC, R600_InstFlag::FC, and llvm::ConstantExpr::getSelect().
FoldShuffleVector()
Value* llvm::ConstantFolder::FoldShuffleVector (Value * V1, Value * V2, ArrayRef< int > Mask) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 164 of file ConstantFolder.h.
References C1, llvm::ConstantExpr::getShuffleVector(), llvm::BitmaskEnumDetail::Mask(), and llvm::NVPTX::PTXLdStInstCode::V2.
FoldUnOpFMF()
Value* llvm::ConstantFolder::FoldUnOpFMF (Instruction::UnaryOps Opc, Value * V, FastMathFlags FMF) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 91 of file ConstantFolder.h.
References llvm::ConstantFoldUnaryInstruction().
The documentation for this class was generated from the following files:
include/llvm/IR/ConstantFolder.h
lib/IR/IRBuilder.cpp