LLVM: llvm::HexagonDAGToDAGISel Class Reference
llvm::HexagonDAGToDAGISel Class Reference
#include "Target/Hexagon/HexagonISelDAGToDAG.h"
Public Member Functions
HexagonDAGToDAGISel ()=delete
HexagonDAGToDAGISel (HexagonTargetMachine &tm, CodeGenOpt::Level OptLevel)
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
bool ComplexPatternFuncMutatesDAG () const override
Return true if complex patterns for this target can mutate the DAG.
void PreprocessISelDAG () override
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
void emitFunctionEntryCode () override
void Select (SDNode *N) override
Main hook for targets to transform nodes into machine nodes.
bool SelectAddrGA (SDValue &N, SDValue &R)
bool SelectAddrGP (SDValue &N, SDValue &R)
bool SelectAnyImm (SDValue &N, SDValue &R)
bool SelectAnyInt (SDValue &N, SDValue &R)
bool SelectAnyImmediate (SDValue &N, SDValue &R, Align Alignment)
bool SelectGlobalAddress (SDValue &N, SDValue &R, bool UseGP, Align Alignment)
bool SelectAddrFI (SDValue &N, SDValue &R)
bool DetectUseSxtw (SDValue &N, SDValue &R)
bool SelectAnyImm0 (SDValue &N, SDValue &R)
bool SelectAnyImm1 (SDValue &N, SDValue &R)
bool SelectAnyImm2 (SDValue &N, SDValue &R)
bool SelectAnyImm3 (SDValue &N, SDValue &R)
MachineSDNode * LoadInstrForLoadIntrinsic (SDNode *IntN)
SDNode * StoreInstrForLoadIntrinsic (MachineSDNode *LoadN, SDNode *IntN)
void SelectFrameIndex (SDNode *N)
bool SelectInlineAsmMemoryOperand (const SDValue &Op, unsigned ConstraintID, std::vector< SDValue > &OutOps) override
SelectInlineAsmMemoryOperand - Implement addressing mode selection for inline asm expressions.
bool tryLoadOfLoadIntrinsic (LoadSDNode *N)
bool SelectBrevLdIntrinsic (SDNode *IntN)
bool SelectNewCircIntrinsic (SDNode *IntN)
Generate a machine instruction node for the new circular buffer intrinsics.
void SelectLoad (SDNode *N)
void SelectIndexedLoad (LoadSDNode *LD, const SDLoc &dl)
void SelectIndexedStore (StoreSDNode *ST, const SDLoc &dl)
void SelectStore (SDNode *N)
void SelectSHL (SDNode *N)
void SelectIntrinsicWChain (SDNode *N)
void SelectIntrinsicWOChain (SDNode *N)
void SelectExtractSubvector (SDNode *N)
void SelectConstant (SDNode *N)
void SelectConstantFP (SDNode *N)
void SelectV65Gather (SDNode *N)
void SelectV65GatherPred (SDNode *N)
void SelectHVXDualOutput (SDNode *N)
void SelectAddSubCarry (SDNode *N)
void SelectVAlign (SDNode *N)
void SelectVAlignAddr (SDNode *N)
void SelectTypecast (SDNode *N)
void SelectP2D (SDNode *N)
void SelectD2P (SDNode *N)
void SelectQ2V (SDNode *N)
void SelectV2Q (SDNode *N)
Public Member Functions inherited from llvm::SelectionDAGISel
SelectionDAGISel (char &ID, TargetMachine &tm, CodeGenOpt::Level OL=CodeGenOpt::Default)
~SelectionDAGISel () override
const TargetLowering * getTargetLowering () const
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual void PostprocessISelDAG ()
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
virtual bool IsProfitableToFold (SDValue N, SDNode *U, SDNode *Root) const
IsProfitableToFold - Returns true if it's profitable to fold the specific operand node N of U during instruction selection that starts at Root.
bool CheckAndMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckAndMask - The isel is trying to match something like (and X, 255).
bool CheckOrMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckOrMask - The isel is trying to match something like (or X, 255).
virtual bool CheckPatternPredicate (unsigned PredNo) const
CheckPatternPredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicate (SDNode *N, unsigned PredNo) const
CheckNodePredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicateWithOperands (SDNode *N, unsigned PredNo, const SmallVectorImpl< SDValue > &Operands) const
CheckNodePredicateWithOperands - This function is generated by tblgen in the target.
virtual bool CheckComplexPattern (SDNode *Root, SDNode *Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > &Result)
virtual SDValue RunSDNodeXForm (SDValue V, unsigned XFormNo)
void SelectCodeCommon (SDNode *NodeToMatch, const unsigned char *MatcherTable, unsigned TableSize)
bool mayRaiseFPException (SDNode *Node) const
Return whether the node may raise an FP exception.
bool isOrEquivalentToAdd (const SDNode *N) const
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Friends
struct HvxSelector
Additional Inherited Members
Public Types inherited from llvm::SelectionDAGISel
enum BuiltinOpcodes {
OPC_Scope, OPC_RecordNode, OPC_RecordChild0, OPC_RecordChild1,
OPC_RecordChild2, OPC_RecordChild3, OPC_RecordChild4, OPC_RecordChild5,
OPC_RecordChild6, OPC_RecordChild7, OPC_RecordMemRef, OPC_CaptureGlueInput,
OPC_MoveChild, OPC_MoveChild0, OPC_MoveChild1, OPC_MoveChild2,
OPC_MoveChild3, OPC_MoveChild4, OPC_MoveChild5, OPC_MoveChild6,
OPC_MoveChild7, OPC_MoveParent, OPC_CheckSame, OPC_CheckChild0Same,
OPC_CheckChild1Same, OPC_CheckChild2Same, OPC_CheckChild3Same, OPC_CheckPatternPredicate,
OPC_CheckPredicate, OPC_CheckPredicateWithOperands, OPC_CheckOpcode, OPC_SwitchOpcode,
OPC_CheckType, OPC_CheckTypeRes, OPC_SwitchType, OPC_CheckChild0Type,
OPC_CheckChild1Type, OPC_CheckChild2Type, OPC_CheckChild3Type, OPC_CheckChild4Type,
OPC_CheckChild5Type, OPC_CheckChild6Type, OPC_CheckChild7Type, OPC_CheckInteger,
OPC_CheckChild0Integer, OPC_CheckChild1Integer, OPC_CheckChild2Integer, OPC_CheckChild3Integer,
OPC_CheckChild4Integer, OPC_CheckCondCode, OPC_CheckChild2CondCode, OPC_CheckValueType,
OPC_CheckComplexPat, OPC_CheckAndImm, OPC_CheckOrImm, OPC_CheckImmAllOnesV,
OPC_CheckImmAllZerosV, OPC_CheckFoldableChainNode, OPC_EmitInteger, OPC_EmitStringInteger,
OPC_EmitRegister, OPC_EmitRegister2, OPC_EmitConvertToTarget, OPC_EmitMergeInputChains,
OPC_EmitMergeInputChains1_0, OPC_EmitMergeInputChains1_1, OPC_EmitMergeInputChains1_2, OPC_EmitCopyToReg,
OPC_EmitCopyToReg2, OPC_EmitNodeXForm, OPC_EmitNode, OPC_EmitNode0,
OPC_EmitNode1, OPC_EmitNode2, OPC_MorphNodeTo, OPC_MorphNodeTo0,
OPC_MorphNodeTo1, OPC_MorphNodeTo2, OPC_CompleteMatch, OPC_Coverage
}
enum {
OPFL_None = 0, OPFL_Chain = 1, OPFL_GlueInput = 2, OPFL_GlueOutput = 4,
OPFL_MemRefs = 8, OPFL_Variadic0 = 1<<4, OPFL_Variadic1 = 2<<4, OPFL_Variadic2 = 3<<4,
OPFL_Variadic3 = 4<<4, OPFL_Variadic4 = 5<<4, OPFL_Variadic5 = 6<<4, OPFL_Variadic6 = 7<<4,
OPFL_VariadicInfo = OPFL_Variadic6
}
Static Public Member Functions inherited from llvm::SelectionDAGISel
static bool IsLegalToFold (SDValue N, SDNode *U, SDNode *Root, CodeGenOpt::Level OptLevel, bool IgnoreChains=false)
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root.
static void InvalidateNodeId (SDNode *N)
static int getUninvalidatedNodeId (SDNode *N)
static void EnforceNodeIdInvariant (SDNode *N)
static int getNumFixedFromVariadicInfo (unsigned Flags)
getNumFixedFromVariadicInfo - Transform an EmitNode flags word into the number of fixed arity values that should be skipped when copying from the root.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::SelectionDAGISel
TargetMachine & TM
const TargetLibraryInfo * LibInfo
std::unique_ptr< FunctionLoweringInfo > FuncInfo
SwiftErrorValueTracking * SwiftError
MachineFunction * MF
MachineRegisterInfo * RegInfo
SelectionDAG * CurDAG
std::unique_ptr< SelectionDAGBuilder > SDB
AAResults * AA = nullptr
AssumptionCache * AC = nullptr
GCFunctionInfo * GFI = nullptr
CodeGenOpt::Level OptLevel
const TargetInstrInfo * TII
const TargetLowering * TLI
bool FastISelFailed
SmallPtrSet< const Instruction *, 4 > ElidedArgCopyInstrs
std::unique_ptr< OptimizationRemarkEmitter > ORE
Current optimization remark emitter.
Protected Member Functions inherited from llvm::SelectionDAGISel
void ReplaceUses (SDValue F, SDValue T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceUses (const SDValue *F, const SDValue *T, unsigned Num)
ReplaceUses - replace all uses of the old nodes F with the use of the new nodes T.
void ReplaceUses (SDNode *F, SDNode *T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceNode (SDNode *F, SDNode *T)
Replace all uses of F with T, then remove F from the DAG.
void SelectInlineAsmMemoryOperands (std::vector< SDValue > &Ops, const SDLoc &DL)
SelectInlineAsmMemoryOperands - Calls to this are automatically generated by tblgen.
virtual StringRef getPatternForIndex (unsigned index)
getPatternForIndex - Patterns selected by tablegen during ISEL
virtual StringRef getIncludePathForIndex (unsigned index)
getIncludePathForIndex - get the td source location of pattern instantiation
bool shouldOptForSize (const MachineFunction *MF) const
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes inherited from llvm::SelectionDAGISel
unsigned DAGSize = 0
DAGSize - Size of DAG being instruction selected.
Detailed Description
Definition at line 29 of file HexagonISelDAGToDAG.h.
Constructor & Destructor Documentation
HexagonDAGToDAGISel() [1/2]
llvm::HexagonDAGToDAGISel::HexagonDAGToDAGISel () delete
HexagonDAGToDAGISel() [2/2]
llvm::HexagonDAGToDAGISel::HexagonDAGToDAGISel (HexagonTargetMachine & tm, CodeGenOpt::Level OptLevel) inline explicit
Definition at line 38 of file HexagonISelDAGToDAG.h.
Member Function Documentation
ComplexPatternFuncMutatesDAG()
bool llvm::HexagonDAGToDAGISel::ComplexPatternFuncMutatesDAG () const inline override virtual
Return true if complex patterns for this target can mutate the DAG.
Reimplemented from llvm::SelectionDAGISel.
Definition at line 53 of file HexagonISelDAGToDAG.h.
DetectUseSxtw()
bool HexagonDAGToDAGISel::DetectUseSxtw (SDValue & N, SDValue & R)
Definition at line 1493 of file HexagonISelDAGToDAG.cpp.
References assert(), llvm::SelectionDAGISel::CurDAG, llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getMachineNode(), llvm::MemSDNode::getMemoryVT(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::LOAD, N, S, llvm::ISD::SEXTLOAD, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, and llvm::ISD::SRA.
emitFunctionEntryCode()
void HexagonDAGToDAGISel::emitFunctionEntryCode () override virtual
Reimplemented from llvm::SelectionDAGISel.
Definition at line 1323 of file HexagonISelDAGToDAG.cpp.
References llvm::MachineInstrBuilder::addImm(), assert(), llvm::BuildMI(), llvm::MachineFunction::front(), llvm::HexagonRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::HexagonSubtarget::getFrameLowering(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getMaxAlign(), llvm::HexagonSubtarget::getRegisterInfo(), llvm::HexagonRegisterInfo::getReservedRegs(), llvm::MachineFunction::getSubtarget(), llvm::Register::isValid(), llvm::SelectionDAGISel::MF, llvm::Reserved, and llvm::Align::value().
LoadInstrForLoadIntrinsic()
MachineSDNode * HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic (SDNode * IntN)
Definition at line 190 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetConstant(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_W_CHAIN, and llvm::MVT::Other.
Referenced by SelectIntrinsicWChain(), and tryLoadOfLoadIntrinsic().
PreprocessISelDAG()
void HexagonDAGToDAGISel::PreprocessISelDAG () override virtual
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
Reimplemented from llvm::SelectionDAGISel.
Definition at line 1263 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAG::allnodes(), llvm::SelectionDAG::allnodes_size(), llvm::SelectionDAGISel::CurDAG, llvm::dbgs(), DEBUG_WITH_TYPE, llvm::SelectionDAG::dump(), EnableAddressRebalancing, N, and llvm::HexagonSubtarget::useHVXOps().
runOnMachineFunction()
bool llvm::HexagonDAGToDAGISel::runOnMachineFunction (MachineFunction & MF) inline override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Reimplemented from llvm::SelectionDAGISel.
Definition at line 43 of file HexagonISelDAGToDAG.h.
References llvm::HexagonSubtarget::getInstrInfo(), llvm::HexagonSubtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::SelectionDAGISel::MF, and llvm::SelectionDAGISel::runOnMachineFunction().
Select()
void HexagonDAGToDAGISel::Select (SDNode * N) override virtual
Main hook for targets to transform nodes into machine nodes.
Implements llvm::SelectionDAGISel.
Definition at line 908 of file HexagonISelDAGToDAG.cpp.
References llvm::HexagonISD::ADDC, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::HexagonISD::D2P, llvm::numbers::e, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::FrameIndex, i, I, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::HexagonSubtarget::isHVXVectorType(), llvm::ISD::LOAD, N, llvm::HexagonISD::P2D, llvm::HexagonISD::Q2V, SelectAddSubCarry(), SelectConstant(), SelectConstantFP(), SelectD2P(), SelectExtractSubvector(), SelectFrameIndex(), SelectIntrinsicWChain(), SelectIntrinsicWOChain(), SelectLoad(), SelectP2D(), SelectQ2V(), SelectSHL(), SelectStore(), SelectTypecast(), SelectV2Q(), SelectVAlign(), SelectVAlignAddr(), llvm::ISD::SHL, llvm::ISD::STORE, llvm::HexagonISD::SUBC, llvm::HexagonISD::TYPECAST, llvm::HexagonSubtarget::useHVXOps(), llvm::HexagonISD::V2Q, llvm::HexagonISD::VALIGN, llvm::HexagonISD::VALIGNADDR, llvm::ISD::VECTOR_SHUFFLE, and llvm::HexagonISD::VROR.
SelectAddrFI()
bool HexagonDAGToDAGISel::SelectAddrFI (SDValue & N, SDValue & R)
Definition at line 1361 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::ISD::FrameIndex, llvm::MachineFunction::getFrameInfo(), llvm::HexagonSubtarget::getFrameLowering(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::MVT::i32, llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::SelectionDAGISel::MF, and N.
Referenced by SelectInlineAsmMemoryOperand().
SelectAddrGA()
bool HexagonDAGToDAGISel::SelectAddrGA (SDValue & N, SDValue & R) inline
Definition at line 1373 of file HexagonISelDAGToDAG.cpp.
References Align, N, and SelectGlobalAddress().
SelectAddrGP()
bool HexagonDAGToDAGISel::SelectAddrGP (SDValue & N, SDValue & R) inline
Definition at line 1377 of file HexagonISelDAGToDAG.cpp.
References Align, N, and SelectGlobalAddress().
SelectAddSubCarry()
void HexagonDAGToDAGISel::SelectAddSubCarry (SDNode * N)
Definition at line 786 of file HexagonISelDAGToDAG.cpp.
References llvm::HexagonISD::ADDC, llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
SelectAnyImm()
bool HexagonDAGToDAGISel::SelectAnyImm (SDValue & N, SDValue & R) inline
Definition at line 1381 of file HexagonISelDAGToDAG.cpp.
References Align, N, and SelectAnyImmediate().
SelectAnyImm0()
bool HexagonDAGToDAGISel::SelectAnyImm0 (SDValue & N, SDValue & R) inline
Definition at line 1385 of file HexagonISelDAGToDAG.cpp.
References Align, N, and SelectAnyImmediate().
SelectAnyImm1()
bool HexagonDAGToDAGISel::SelectAnyImm1 (SDValue & N, SDValue & R) inline
Definition at line 1388 of file HexagonISelDAGToDAG.cpp.
References Align, N, and SelectAnyImmediate().
SelectAnyImm2()
bool HexagonDAGToDAGISel::SelectAnyImm2 (SDValue & N, SDValue & R) inline
Definition at line 1391 of file HexagonISelDAGToDAG.cpp.
References Align, N, and SelectAnyImmediate().
SelectAnyImm3()
bool HexagonDAGToDAGISel::SelectAnyImm3 (SDValue & N, SDValue & R) inline
Definition at line 1394 of file HexagonISelDAGToDAG.cpp.
References Align, N, and SelectAnyImmediate().
SelectAnyImmediate()
bool HexagonDAGToDAGISel::SelectAnyImmediate (SDValue & N, SDValue & R, Align Alignment)
Definition at line 1407 of file HexagonISelDAGToDAG.cpp.
References Align, llvm::ISD::BlockAddress, llvm::ISD::Constant, llvm::HexagonISD::CP, llvm::SelectionDAGISel::CurDAG, llvm::ISD::ExternalSymbol, llvm::getOffset(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::isAligned(), llvm::HexagonISD::JT, N, and SelectGlobalAddress().
Referenced by SelectAnyImm(), SelectAnyImm0(), SelectAnyImm1(), SelectAnyImm2(), and SelectAnyImm3().
SelectAnyInt()
bool HexagonDAGToDAGISel::SelectAnyInt (SDValue & N, SDValue & R) inline
Definition at line 1398 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getTargetConstant(), and N.
SelectBrevLdIntrinsic()
bool HexagonDAGToDAGISel::SelectBrevLdIntrinsic (SDNode * IntN)
Definition at line 323 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_W_CHAIN, llvm::MVT::Other, llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAGISel::ReplaceUses(), and llvm::SelectionDAG::setNodeMemRefs().
Referenced by SelectIntrinsicWChain().
SelectConstant()
void HexagonDAGToDAGISel::SelectConstant (SDNode * N)
Definition at line 744 of file HexagonISelDAGToDAG.cpp.
References assert(), llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::MVT::i1, N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
SelectConstantFP()
void HexagonDAGToDAGISel::SelectConstantFP (SDNode * N)
Definition at line 723 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::MVT::i64, N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
SelectD2P()
void HexagonDAGToDAGISel::SelectD2P (SDNode * N)
Definition at line 872 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
SelectExtractSubvector()
void HexagonDAGToDAGISel::SelectExtractSubvector (SDNode * N)
Definition at line 701 of file HexagonISelDAGToDAG.cpp.
References assert(), llvm::SelectionDAGISel::CurDAG, llvm::MipsISD::Ext, llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SDValue::getValueType(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), N, llvm::SelectionDAGISel::ReplaceNode(), and SubReg.
Referenced by Select().
SelectFrameIndex()
void HexagonDAGToDAGISel::SelectFrameIndex (SDNode * N)
Definition at line 757 of file HexagonISelDAGToDAG.cpp.
References CH, llvm::SelectionDAGISel::CurDAG, DL, llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::HexagonSubtarget::getFrameLowering(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineNode(), llvm::MachineFrameInfo::getMaxAlign(), llvm::TargetFrameLowering::getStackAlign(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MVT::i32, llvm::SelectionDAGISel::MF, N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
SelectGlobalAddress()
bool HexagonDAGToDAGISel::SelectGlobalAddress (SDValue & N, SDValue & R, bool UseGP, Align Alignment)
Definition at line 1448 of file HexagonISelDAGToDAG.cpp.
References llvm::ISD::ADD, Addr, llvm::HexagonISD::CONST32, llvm::HexagonISD::CONST32_GP, llvm::HexagonISD::CP, llvm::SelectionDAGISel::CurDAG, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::isAligned(), llvm::HexagonISD::JT, N, llvm::ISD::TargetGlobalAddress, and uint64_t.
Referenced by SelectAddrGA(), SelectAddrGP(), and SelectAnyImmediate().
SelectHVXDualOutput()
void HexagonDAGToDAGISel::SelectHVXDualOutput (SDNode * N)
Definition at line 2935 of file HexagonISelDAGToDAGHVX.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getVTList(), llvm_unreachable, N, llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAGISel::ReplaceUses(), llvm::MVT::v128i1, llvm::MVT::v16i32, llvm::MVT::v32i32, and llvm::MVT::v64i1.
Referenced by SelectIntrinsicWOChain().
SelectIndexedLoad()
void HexagonDAGToDAGISel::SelectIndexedLoad (LoadSDNode * LD, const SDLoc & dl)
Definition at line 71 of file HexagonISelDAGToDAG.cpp.
References assert(), llvm::sampleprof::Base, llvm::ISD::EXTLOAD, llvm::MVT::f32, llvm::MVT::f64, From, llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::EVT::isSimple(), llvm::ARM_MB::LD, llvm_unreachable, N, llvm::ISD::NON_EXTLOAD, llvm::Offset, llvm::MVT::Other, llvm::ISD::SEXTLOAD, llvm::MVT::SimpleTy, llvm::MVT::v128i8, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v32i16, llvm::MVT::v32i32, llvm::MVT::v4i16, llvm::MVT::v4i8, llvm::MVT::v64i16, llvm::MVT::v64i8, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::ISD::ZEXTLOAD.
Referenced by SelectLoad().
SelectIndexedStore()
void HexagonDAGToDAGISel::SelectIndexedStore (StoreSDNode * ST, const SDLoc & dl)
Definition at line 468 of file HexagonISelDAGToDAG.cpp.
References assert(), llvm::sampleprof::Base, llvm::SelectionDAGISel::CurDAG, llvm::MVT::f32, llvm::MVT::f64, From, llvm::SelectionDAG::getMachineNode(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::EVT::isSimple(), llvm::HexagonInstrInfo::isValidAutoIncImm(), llvm_unreachable, llvm::Offset, llvm::MVT::Other, llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAGISel::ReplaceUses(), S, llvm::SelectionDAG::setNodeMemRefs(), llvm::MVT::SimpleTy, llvm::ARM_MB::ST, llvm::MVT::v128i8, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v32i16, llvm::MVT::v32i32, llvm::MVT::v4i16, llvm::MVT::v4i8, llvm::MVT::v64i16, llvm::MVT::v64i8, llvm::MVT::v8i64, and llvm::MVT::v8i8.
Referenced by SelectStore().
SelectInlineAsmMemoryOperand()
bool HexagonDAGToDAGISel::SelectInlineAsmMemoryOperand (const SDValue & Op, unsigned ConstraintID, std::vector< SDValue > & OutOps) override virtual
SelectInlineAsmMemoryOperand - Implement addressing mode selection for inline asm expressions.
Reimplemented from llvm::SelectionDAGISel.
Definition at line 959 of file HexagonISelDAGToDAG.cpp.
References llvm::InlineAsm::Constraint_m, llvm::InlineAsm::Constraint_o, llvm::InlineAsm::Constraint_v, llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, and SelectAddrFI().
SelectIntrinsicWChain()
void HexagonDAGToDAGISel::SelectIntrinsicWChain (SDNode * N)
Definition at line 630 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, LoadInstrForLoadIntrinsic(), N, llvm::SelectionDAG::RemoveDeadNode(), SelectBrevLdIntrinsic(), SelectNewCircIntrinsic(), SelectV65Gather(), SelectV65GatherPred(), and StoreInstrForLoadIntrinsic().
Referenced by Select().
SelectIntrinsicWOChain()
void HexagonDAGToDAGISel::SelectIntrinsicWOChain (SDNode * N)
Definition at line 667 of file HexagonISelDAGToDAG.cpp.
References llvm::tgtok::Bits, llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getNode(), N, llvm::SelectionDAGISel::ReplaceNode(), and SelectHVXDualOutput().
Referenced by Select().
SelectLoad()
void HexagonDAGToDAGISel::SelectLoad (SDNode * N)
Definition at line 450 of file HexagonISelDAGToDAG.cpp.
References llvm::ARM_MB::LD, N, SelectIndexedLoad(), tryLoadOfLoadIntrinsic(), and llvm::ISD::UNINDEXED.
Referenced by Select().
SelectNewCircIntrinsic()
bool HexagonDAGToDAGISel::SelectNewCircIntrinsic (SDNode * IntN)
Generate a machine instruction node for the new circular buffer intrinsics.
The new versions use a CSx register instead of the K field.
Definition at line 364 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, DL, llvm::SelectionDAG::getMachineNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetConstant(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_W_CHAIN, llvm::MVT::Other, llvm::SelectionDAG::RemoveDeadNode(), and llvm::SelectionDAGISel::ReplaceUses().
Referenced by SelectIntrinsicWChain().
SelectP2D()
void HexagonDAGToDAGISel::SelectP2D (SDNode * N)
Definition at line 865 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
SelectQ2V()
void HexagonDAGToDAGISel::SelectQ2V (SDNode * N)
Definition at line 895 of file HexagonISelDAGToDAG.cpp.
References assert(), llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::HexagonSubtarget::getVectorLength(), llvm::MVT::i32, N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
SelectSHL()
void HexagonDAGToDAGISel::SelectSHL (SDNode * N)
Definition at line 573 of file HexagonISelDAGToDAG.cpp.
References C1, llvm::ISD::Constant, llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::ISD::MUL, N, llvm::SelectionDAGISel::ReplaceNode(), llvm::ISD::SHL, and llvm::ISD::SUB.
Referenced by Select().
SelectStore()
void HexagonDAGToDAGISel::SelectStore (SDNode * N)
Definition at line 559 of file HexagonISelDAGToDAG.cpp.
References N, SelectIndexedStore(), llvm::ARM_MB::ST, and llvm::ISD::UNINDEXED.
Referenced by Select(), and StoreInstrForLoadIntrinsic().
SelectTypecast()
void HexagonDAGToDAGISel::SelectTypecast (SDNode * N)
Definition at line 857 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::MorphNodeTo(), N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
SelectV2Q()
void HexagonDAGToDAGISel::SelectV2Q (SDNode * N)
Definition at line 881 of file HexagonISelDAGToDAG.cpp.
References assert(), llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::HexagonSubtarget::getVectorLength(), llvm::MVT::i32, N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
SelectV65Gather()
void HexagonDAGToDAGISel::SelectV65Gather (SDNode * N)
Definition at line 2897 of file HexagonISelDAGToDAGHVX.cpp.
References llvm::sampleprof::Base, llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm_unreachable, N, llvm::Offset, llvm::MVT::Other, llvm::SelectionDAGISel::ReplaceNode(), and llvm::SelectionDAG::setNodeMemRefs().
Referenced by SelectIntrinsicWChain().
SelectV65GatherPred()
void HexagonDAGToDAGISel::SelectV65GatherPred (SDNode * N)
Definition at line 2857 of file HexagonISelDAGToDAGHVX.cpp.
References llvm::sampleprof::Base, llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm_unreachable, N, llvm::Offset, llvm::MVT::Other, llvm::SelectionDAGISel::ReplaceNode(), and llvm::SelectionDAG::setNodeMemRefs().
Referenced by SelectIntrinsicWChain().
SelectVAlign()
void HexagonDAGToDAGISel::SelectVAlign (SDNode * N)
Definition at line 795 of file HexagonISelDAGToDAG.cpp.
References assert(), llvm::SelectionDAGISel::CurDAG, E, llvm::SelectionDAG::getMachineNode(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::MVT::i32, llvm::MVT::i64, llvm::HexagonSubtarget::isHVXVectorType(), llvm::M0(), llvm::M1(), N, llvm::SelectionDAGISel::ReplaceNode(), S, llvm::HexagonSubtarget::useCompound(), and llvm::MVT::v8i1.
Referenced by Select().
SelectVAlignAddr()
void HexagonDAGToDAGISel::SelectVAlignAddr (SDNode * N)
Definition at line 842 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::AA, assert(), llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::isPowerOf2_32(), M, llvm::BitmaskEnumDetail::Mask(), N, and llvm::SelectionDAGISel::ReplaceNode().
Referenced by Select().
StoreInstrForLoadIntrinsic()
SDNode * HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic (MachineSDNode * LoadN, SDNode * IntN)
Definition at line 221 of file HexagonISelDAGToDAG.cpp.
References Align, llvm::SelectionDAGISel::CurDAG, F, llvm::MVT::getIntegerVT(), llvm::SDNode::getMachineOpcode(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), llvm::HandleSDNode::getValue(), llvm::HexagonII::MemAccesSizeMask, llvm::HexagonII::MemAccessSizePos, llvm::SelectionDAGISel::ReplaceUses(), SelectStore(), and uint64_t.
Referenced by SelectIntrinsicWChain(), and tryLoadOfLoadIntrinsic().
tryLoadOfLoadIntrinsic()
bool HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic (LoadSDNode * N)
Definition at line 256 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, F, llvm::SDValue::getNode(), llvm::SDNode::getOperand(), llvm::ISD::INTRINSIC_W_CHAIN, LoadInstrForLoadIntrinsic(), N, llvm::ISD::NON_EXTLOAD, llvm::SelectionDAG::RemoveDeadNode(), llvm::SelectionDAGISel::ReplaceUses(), S, llvm::ISD::SEXTLOAD, size, StoreInstrForLoadIntrinsic(), and llvm::ISD::ZEXTLOAD.
Referenced by SelectLoad().
Friends And Related Function Documentation
HvxSelector
friend struct HvxSelector friend
Definition at line 123 of file HexagonISelDAGToDAG.h.
Member Data Documentation
ID
char HexagonDAGToDAGISel::ID = 0 static
Definition at line 34 of file HexagonISelDAGToDAG.h.
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonISelDAGToDAG.h
lib/Target/Hexagon/HexagonISelDAGToDAG.cpp
lib/Target/Hexagon/HexagonISelDAGToDAGHVX.cpp