LLVM: llvm::OpenMPOptCGSCCPass Class Reference
llvm::OpenMPOptCGSCCPass Class Reference
#include "llvm/Transforms/IPO/OpenMPOpt.h"
Public Member Functions
OpenMPOptCGSCCPass ()
OpenMPOptCGSCCPass (ThinOrFullLTOPhase LTOPhase)
PreservedAnalyses run (LazyCallGraph::SCC &C, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Public Member Functions inherited from llvm::PassInfoMixin< OpenMPOptCGSCCPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< OpenMPOptCGSCCPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 49 of file OpenMPOpt.h.
Constructor & Destructor Documentation
OpenMPOptCGSCCPass() [1/2]
llvm::OpenMPOptCGSCCPass::OpenMPOptCGSCCPass () inline
Definition at line 51 of file OpenMPOpt.h.
OpenMPOptCGSCCPass() [2/2]
llvm::OpenMPOptCGSCCPass::OpenMPOptCGSCCPass (ThinOrFullLTOPhase LTOPhase) inline
Definition at line 52 of file OpenMPOpt.h.
Member Function Documentation
run()
PreservedAnalyses OpenMPOptCGSCCPass::run (LazyCallGraph::SCC & C, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Definition at line 5430 of file OpenMPOpt.cpp.
References llvm::PreservedAnalyses::all(), Allocator, llvm::SetVector< T, Vector, Set >::back(), llvm::omp::containsOpenMP(), llvm::dbgs(), DEBUG_TYPE, llvm::AttributorConfig::DefaultInitializeLiveInternals, DisableOpenMPOptimizations, F, FAM, llvm::FullLTOPostLink, llvm::omp::getDeviceKernels(), llvm::GlobalValue::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::AttributorConfig::InitializationCallback, llvm::CallGraphUpdater::initialize(), llvm::AttributorConfig::IsModulePass, llvm::omp::isOpenMPDevice(), llvm::AMDGPU::HSAMD::Key::Kernels, LLVM_DEBUG, M, llvm::AttributorConfig::MaxFixpointIterations, N, llvm::PreservedAnalyses::none(), llvm::AttributorConfig::OREGetter, llvm::AttributorConfig::PassName, PrintModuleAfterOptimizations, PrintModuleBeforeOptimizations, llvm::AttributorConfig::RewriteSignatures, llvm::AMDGPU::CPol::SCC, SetFixpointIterations, TAG, and llvm::ThinLTOPreLink.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/OpenMPOpt.h
lib/Transforms/IPO/OpenMPOpt.cpp