LLVM: llvm::DWPStringPool Class Reference
llvm::DWPStringPool Class Reference
#include "llvm/DWP/DWPStringPool.h"
Public Member Functions
DWPStringPool (MCStreamer &Out, MCSection *Sec)
uint32_t getOffset (const char *Str, unsigned Length)
Detailed Description
Definition at line 10 of file DWPStringPool.h.
Constructor & Destructor Documentation
DWPStringPool()
llvm::DWPStringPool::DWPStringPool (MCStreamer & Out, MCSection * Sec) inline
Definition at line 39 of file DWPStringPool.h.
Member Function Documentation
getOffset()
uint32_t llvm::DWPStringPool::getOffset (const char * Str, unsigned Length) inline
Definition at line 41 of file DWPStringPool.h.
References assert(), llvm::MCStreamer::emitBytes(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::Length, and llvm::MCStreamer::switchSection().
The documentation for this class was generated from the following file:
include/llvm/DWP/DWPStringPool.h