LLVM: llvm::ArrayRef< T > Class Template Reference
llvm::ArrayRef< T > Class Template Reference
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e.
#include "llvm/ADT/APInt.h"
Public Types
using value_type = T
using pointer = value_type *
using const_pointer = const value_type *
using reference = value_type &
using const_reference = const value_type &
using iterator = const_pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using size_type = size_t
using difference_type = ptrdiff_t
Public Member Functions
Constructors
ArrayRef ()=default
Construct an empty ArrayRef.
ArrayRef (std::nullopt_t)
Construct an empty ArrayRef from std::nullopt.
ArrayRef (const T &OneElt)
Construct an ArrayRef from a single element.
constexpr ArrayRef (const T *data, size_t length)
Construct an ArrayRef from a pointer and length.
constexpr ArrayRef (const T *begin, const T *end)
Construct an ArrayRef from a range.
template<typename U >
ArrayRef (const SmallVectorTemplateCommon< T, U > &Vec)
Construct an ArrayRef from a SmallVector.
template<typename A >
ArrayRef (const std::vector< T, A > &Vec)
Construct an ArrayRef from a std::vector.
template<size_t N>
constexpr ArrayRef (const std::array< T, N > &Arr)
Construct an ArrayRef from a std::array.
template<size_t N>
constexpr ArrayRef (const T(&Arr)[N])
Construct an ArrayRef from a C array.
constexpr ArrayRef (const std::initializer_list< T > &Vec)
Construct an ArrayRef from a std::initializer_list.
template<typename U >
ArrayRef (const ArrayRef< U * > &A, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > *=nullptr)
Construct an ArrayRef<const T*> from ArrayRef<T*>.
template<typename U , typename DummyT >
ArrayRef (const SmallVectorTemplateCommon< U *, DummyT > &Vec, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > *=nullptr)
Construct an ArrayRef<const T*> from a SmallVector<T*>.
template<typename U , typename A >
ArrayRef (const std::vector< U *, A > &Vec, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > *=nullptr)
Construct an ArrayRef<const T*> from std::vector<T*>.
Simple Operations
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
empty - Check if the array is empty.
const T * data () const
size_t size () const
size - Get the array size.
const T & front () const
front - Get the first element.
const T & back () const
back - Get the last element.
template<typename Allocator >
MutableArrayRef< T > copy (Allocator &A)
bool equals (ArrayRef RHS) const
equals - Check for element-wise equality.
ArrayRef< T > slice (size_t N, size_t M) const
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
ArrayRef< T > slice (size_t N) const
slice(n) - Chop off the first N elements of the array.
ArrayRef< T > drop_front (size_t N=1) const
Drop the first N elements of the array.
ArrayRef< T > drop_back (size_t N=1) const
Drop the last N elements of the array.
template<class PredicateT >
ArrayRef< T > drop_while (PredicateT Pred) const
Return a copy of *this with the first N elements satisfying the given predicate removed.
template<class PredicateT >
ArrayRef< T > drop_until (PredicateT Pred) const
Return a copy of *this with the first N elements not satisfying the given predicate removed.
ArrayRef< T > take_front (size_t N=1) const
Return a copy of *this with only the first N elements.
ArrayRef< T > take_back (size_t N=1) const
Return a copy of *this with only the last N elements.
template<class PredicateT >
ArrayRef< T > take_while (PredicateT Pred) const
Return the first N elements of this Array that satisfy the given predicate.
template<class PredicateT >
ArrayRef< T > take_until (PredicateT Pred) const
Return the first N elements of this Array that don't satisfy the given predicate.
Operator Overloads
const T & operator[] (size_t Index) const
template<typename U >
std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & operator= (U &&Temporary)=delete
Disallow accidental assignment from a temporary.
template<typename U >
std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & operator= (std::initializer_list< U >)=delete
Disallow accidental assignment from a temporary.
Expensive Operations
std::vector< T > vec () const
Conversion operators
operator std::vector< T > () const
Detailed Description
template<typename T>
class llvm::ArrayRef< T >
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e.
a start pointer and a length. It allows various APIs to take consecutive elements easily and conveniently.
This class does not own the underlying data, it is expected to be used in situations where the data resides in some other buffer, whose lifetime extends past that of the ArrayRef. For this reason, it is not in general safe to store an ArrayRef.
This is intended to be trivially copyable, so it should be passed by value.
Definition at line 33 of file APInt.h.
Member Typedef Documentation
const_iterator
template<typename T > using llvm::ArrayRef< T >::const_iterator = const_pointer
Definition at line 49 of file ArrayRef.h.
const_pointer
template<typename T > using llvm::ArrayRef< T >::const_pointer = const value_type *
Definition at line 45 of file ArrayRef.h.
const_reference
template<typename T > using llvm::ArrayRef< T >::const_reference = const value_type &
Definition at line 47 of file ArrayRef.h.
const_reverse_iterator
template<typename T > using llvm::ArrayRef< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 51 of file ArrayRef.h.
difference_type
template<typename T > using llvm::ArrayRef< T >::difference_type = ptrdiff_t
Definition at line 53 of file ArrayRef.h.
iterator
template<typename T > using llvm::ArrayRef< T >::iterator = const_pointer
Definition at line 48 of file ArrayRef.h.
pointer
template<typename T > using llvm::ArrayRef< T >::pointer = value_type *
Definition at line 44 of file ArrayRef.h.
reference
template<typename T > using llvm::ArrayRef< T >::reference = value_type &
Definition at line 46 of file ArrayRef.h.
reverse_iterator
template<typename T > using llvm::ArrayRef< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 50 of file ArrayRef.h.
size_type
template<typename T > using llvm::ArrayRef< T >::size_type = size_t
Definition at line 52 of file ArrayRef.h.
value_type
template<typename T > using llvm::ArrayRef< T >::value_type = T
Definition at line 43 of file ArrayRef.h.
Constructor & Destructor Documentation
ArrayRef() [1/13]
template<typename T > llvm::ArrayRef< T >::ArrayRef () default
Construct an empty ArrayRef.
ArrayRef() [2/13]
template<typename T > llvm::ArrayRef< T >::ArrayRef (std::nullopt_t) inline
Construct an empty ArrayRef from std::nullopt.
Definition at line 70 of file ArrayRef.h.
ArrayRef() [3/13]
template<typename T > llvm::ArrayRef< T >::ArrayRef (const T & OneElt) inline
Construct an ArrayRef from a single element.
Definition at line 73 of file ArrayRef.h.
ArrayRef() [4/13]
template<typename T > constexpr llvm::ArrayRef< T >::ArrayRef (const T * data, size_t length) inline constexpr
Construct an ArrayRef from a pointer and length.
Definition at line 77 of file ArrayRef.h.
ArrayRef() [5/13]
template<typename T > constexpr llvm::ArrayRef< T >::ArrayRef (const T * begin, const T * end) inline constexpr
Construct an ArrayRef from a range.
Definition at line 81 of file ArrayRef.h.
ArrayRef() [6/13]
template<typename T > template<typename U > llvm::ArrayRef< T >::ArrayRef (const SmallVectorTemplateCommon< T, U > & Vec) inline
Construct an ArrayRef from a SmallVector.
This is templated in order to avoid instantiating SmallVectorTemplateCommon<T> whenever we copy-construct an ArrayRef.
Definition at line 88 of file ArrayRef.h.
ArrayRef() [7/13]
template<typename T > template<typename A > llvm::ArrayRef< T >::ArrayRef (const std::vector< T, A > & Vec) inline
Construct an ArrayRef from a std::vector.
Definition at line 94 of file ArrayRef.h.
ArrayRef() [8/13]
template<typename T > template<size_t N> constexpr llvm::ArrayRef< T >::ArrayRef (const std::array< T, N > & Arr) inline constexpr
Construct an ArrayRef from a std::array.
Definition at line 99 of file ArrayRef.h.
ArrayRef() [9/13]
template<typename T > template<size_t N> constexpr llvm::ArrayRef< T >::ArrayRef (const T(&) Arr[N]) inline constexpr
Construct an ArrayRef from a C array.
Definition at line 104 of file ArrayRef.h.
ArrayRef() [10/13]
template<typename T > constexpr llvm::ArrayRef< T >::ArrayRef (const std::initializer_list< T > & Vec) inline constexpr
Construct an ArrayRef from a std::initializer_list.
Definition at line 114 of file ArrayRef.h.
ArrayRef() [11/13]
template<typename T > template<typename U > llvm::ArrayRef< T >::ArrayRef (const ArrayRef< U * > & A, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > * = nullptr) inline
Construct an ArrayRef<const T*> from ArrayRef<T*>.
This uses SFINAE to ensure that only ArrayRefs of pointers can be converted.
Definition at line 124 of file ArrayRef.h.
ArrayRef() [12/13]
template<typename T > template<typename U , typename DummyT > llvm::ArrayRef< T >::ArrayRef (const SmallVectorTemplateCommon< U *, DummyT > & Vec, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > * = nullptr) inline
Construct an ArrayRef<const T*> from a SmallVector<T*>.
This is templated in order to avoid instantiating SmallVectorTemplateCommon<T> whenever we copy-construct an ArrayRef.
Definition at line 133 of file ArrayRef.h.
ArrayRef() [13/13]
template<typename T > template<typename U , typename A > llvm::ArrayRef< T >::ArrayRef (const std::vector< U *, A > & Vec, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > * = nullptr) inline
Construct an ArrayRef<const T*> from std::vector<T*>.
This uses SFINAE to ensure that only vectors of pointers can be converted.
Definition at line 142 of file ArrayRef.h.
Member Function Documentation
back()
template<typename T > const T& llvm::ArrayRef< T >::back () const inline
back - Get the last element.
Definition at line 172 of file ArrayRef.h.
Referenced by llvm::AttributeList::addParamAttribute(), llvm::DIExpression::appendToStack(), computeBlockRuns(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::Record::getDirectSuperClasses(), isSwitchDense(), llvm::RandomIRBuilder::newSink(), llvm::recognizeBSwapOrBitReverseIdiom(), and simplifyGEPInst().
begin()
template<typename T > iterator llvm::ArrayRef< T >::begin () const inline
Definition at line 151 of file ArrayRef.h.
Referenced by llvm::lto::LTO::add(), llvm::SubtargetFeatures::addFeaturesVector(), addMask(), llvm::DebugLocEntry::addValues(), llvm::DIExpression::append(), llvm::DIExpression::appendOpsToArg(), llvm::DIExpression::appendToStack(), llvm::DominatorTreeBase< BasicBlock, false >::applyUpdates(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildBuildVectorTrunc(), llvm::MachineIRBuilder::buildConcatVectors(), buildCopyFromRegs(), buildFixItLine(), llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildMergeValues(), BuildSubAggregate(), llvm::MachineIRBuilder::buildUnmerge(), llvm::Interpreter::callFunction(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::collectPGOFuncNameStrings(), combineShuffleOfSplatVal(), combineShuffleToZeroExtendVectorInReg(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::ComputeLinearIndex(), llvm::concatenateVectors(), llvm::sys::UnicodeCharSet::contains(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), CreateGCRelocates(), llvm::VectorBuilder::createVectorInstruction(), llvm::DeleteDeadBlocks(), llvm::discoverAndMapSubloop(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::objcopy::wasm::dumpSectionToFile(), llvm::DIExpression::elements_begin(), llvm::MCDwarfFrameEmitter::Emit(), llvm::BitstreamWriter::emitBlob(), llvm::AAMDNodes::extendToTBAA(), BoUpSLP::ShuffleInstructionBuilder::finalize(), llvm::FindInsertedValue(), foldGEPOfGEP(), llvm::RecordRecTy::get(), llvm::AttributeList::get(), llvm::CondOpInit::get(), llvm::DagInit::get(), llvm::gsym::GsymReader::getAddressOffsetIndex(), getAVX512Node(), llvm::StructLayout::getElementContainingOffset(), getFauxShuffleMask(), llvm::ConstantExprKeyType::getHash(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::getShuffleMaskWithWidestElts(), llvm::ConstantExpr::getWithOperands(), llvm::CallGraphSCC::initialize(), llvm::RegPressureTracker::initLiveThru(), llvm::AppendingBinaryByteStream::insert(), llvm::sroa::AllocaSlices::insert(), insertCandidatesWithPendingInjections(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::LiveRange::isLiveAtIndexes(), isSubset(), llvm::libDriverMain(), llvm::coverage::CoverageMapping::load(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), llvm::makePostTransformationMetadata(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), mergeVectorRegsToResultRegs(), llvm::object::ExportEntry::moveNext(), llvm::object::MachORebaseEntry::moveNext(), llvm::object::MachOBindEntry::moveNext(), llvm::object::ExportEntry::nodeOffset(), llvm::opt::OptTable::ParseArgs(), ProfileCondOpInit(), ProfileDagInit(), propagateMetadata(), llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read(), llvm::BinaryStreamReader::readCString(), llvm::BinaryStreamReader::readFixedString(), removeUnusedBlocksFromParent(), llvm::SDDbgValue::SDDbgValue(), llvm::MachineFunction::setCallSiteLandingPad(), setCoroInfo(), llvm::X86MachineFunctionInfo::setPreallocatedArgOffsets(), llvm::gsym::GsymCreator::setUUID(), llvm::SmallVector< llvm::cl::parser::OptionInfo, 8 >::SmallVector(), stackFrameIncludesInlinedCallStack(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), shuffles::vdealvdd(), shuffles::vshuffvdd(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), and writeToResolutionFile().
copy()
template<typename T > template<typename Allocator > MutableArrayRef<T> llvm::ArrayRef< T >::copy (Allocator & A) inline
Definition at line 178 of file ArrayRef.h.
data()
template<typename T > const T* llvm::ArrayRef< T >::data () const inline
Definition at line 160 of file ArrayRef.h.
Referenced by analyzeHeader(), llvm::objcopy::elf::SectionTableRef::begin(), llvm::orc::SelfExecutorProcessControl::callWrapperAsync(), llvm::compression::zlib::compress(), llvm::ConstantFoldGetElementPtr(), llvm::StackMapParser< Endianness >::constants_end(), llvm::crc32(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::data(), llvm::compression::zlib::decompress(), llvm::codeview::discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), llvm::object::doesXCOFFTracebackTableBegin(), dumpLocationExpr(), llvm::object::ELFFile< ELFT >::dynamicEntries(), eat12Bytes(), eatBytes(), llvm::objcopy::elf::SectionTableRef::end(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::codeview::forEachCodeViewRecord(), llvm::codeview::detail::GuidAdapter::format(), llvm::StackMapParser< Endianness >::functions_end(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), llvm::gsym::GsymReader::getAddrOffsets(), llvm::codeview::getBytesAsCharacters(), llvm::StackMapParser< Endianness >::getConstant(), llvm::object::Elf_Note_Impl< ELFT >::getDescAsStringRef(), getExpressionFrameOffset(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::StackMapParser< Endianness >::getFunction(), llvm::ConstantExpr::getGetElementPtr(), llvm::DenseMapInfo< ArrayRef< T >, void >::getHashValue(), M68kDisassembler::getInstruction(), llvm::SimpleBitstreamCursor::getPointerToByte(), llvm::StackMapParser< Endianness >::getRecord(), llvm::object::MachOObjectFile::getSectionFinalSegmentName(), llvm::object::MachOObjectFile::getSectionName(), llvm::object::ResourceSectionRef::getTableEntry(), getUUID(), llvm::MipsTargetLowering::HandleByVal(), llvm::pdb::hashStringV2(), llvm::codeview::CVRecord< TypeLeafKind >::kind(), llvm::Function::lookupIntrinsicID(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), llvm::codeview::CodeViewRecordIO::mapGuid(), llvm::object::MachOChainedFixupEntry::moveNext(), nextLEB(), llvm::object::MinidumpFile::MemoryInfoIterator::operator*(), llvm::object::MachORebaseEntry::operator==(), llvm::object::MachOBindEntry::operator==(), parseImmediate(), llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readInteger(), llvm::BinaryStreamReader::readObject(), llvm::orc::ExecutionSession::runJITDispatchHandler(), llvm::orc::FDSimpleRemoteEPCTransport::sendMessage(), llvm::BinaryByteStream::str(), llvm::codeview::CVRecord< TypeLeafKind >::str_data(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::MutableBinaryByteStream::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::AppendingBinaryByteStream::writeBytes(), and writeWithCommas().
drop_back()
template<typename T > ArrayRef<T> llvm::ArrayRef< T >::drop_back (size_t N = 1) const inline
Drop the last N elements of the array.
Definition at line 208 of file ArrayRef.h.
Referenced by llvm::DIExpression::appendToStack(), EltsFromConsecutiveLoads(), llvm::Record::getDirectSuperClasses(), llvm::sampleprof::SampleContext::IsPrefixOf(), llvm::recognizeBSwapOrBitReverseIdiom(), and simplifyGEPInst().
drop_front()
template<typename T > ArrayRef<T> llvm::ArrayRef< T >::drop_front (size_t N = 1) const inline
Drop the first N elements of the array.
Definition at line 202 of file ArrayRef.h.
Referenced by buildCopyFromRegs(), llvm::coro::buildCoroutineFrame(), clusterSortPtrAccesses(), combineShuffleToZeroExtendVectorInReg(), computeBlockRuns(), llvm::codeview::CVRecord< TypeLeafKind >::content(), llvm::codeview::discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::codeview::forEachCodeViewRecord(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::fromCodeViewSymbol(), llvm::opt::GenericOptTable::GenericOptTable(), llvm::codeview::GloballyHashedType::hashType(), llvm::object::MinidumpFile::MemoryInfoIterator::operator++(), resolveTypeIndexReferences(), llvm::sortPtrAccesses(), llvm::pdb::typesetItemList(), and writeWithCommas().
drop_until()
template<typename T > template<class PredicateT > ArrayRef<T> llvm::ArrayRef< T >::drop_until (PredicateT Pred) const inline
Return a copy of *this with the first N elements not satisfying the given predicate removed.
Definition at line 221 of file ArrayRef.h.
drop_while()
template<typename T > template<class PredicateT > ArrayRef<T> llvm::ArrayRef< T >::drop_while (PredicateT Pred) const inline
Return a copy of *this with the first N elements satisfying the given predicate removed.
Definition at line 215 of file ArrayRef.h.
empty()
template<typename T > bool llvm::ArrayRef< T >::empty () const inline
empty - Check if the array is empty.
Definition at line 158 of file ArrayRef.h.
Referenced by llvm::orc::IRSymbolMapper::add(), addBasicBlockMetadata(), addMask(), llvm::LazyCallGraph::addSplitRefRecursiveFunctions(), llvm::pdb::DbiModuleDescriptorBuilder::addSymbolsInBulk(), llvm::pdb::TpiStreamBuilder::addTypeRecords(), llvm::RegAllocBase::allocatePhysRegs(), llvm::DIExpression::append(), llvm::DIExpression::appendToStack(), llvm::DominatorTreeBase< BasicBlock, false >::applyUpdates(), llvm::AttributeListImpl::AttributeListImpl(), buildExtractionBlockSet(), buildFixItLine(), llvm::VPlanSlp::buildGraph(), llvm::MachineIRBuilder::buildInstr(), buildShuffleEntryMask(), canClobberPhysRegDefs(), canClobberReachingPhysRegUse(), llvm::cloneAndAdaptNoAliasScopes(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::collectPGOFuncNameStrings(), llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >::CombinationGenerator(), combineX86ShuffleChain(), llvm::MDNodeOpsKey::compareOps(), computeBlockRuns(), computeCalleeSaveRegisterPairs(), computeExcessPressureDelta(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertValueInstruction(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreateLogicalOr(), llvm::IRBuilderBase::CreateOr(), llvm::objcopy::deepWriteArchive(), llvm::doesNotNeedToSchedule(), llvm::coverage::CounterMappingContext::dump(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::CodeViewContext::encodeInlineLineTable(), BoUpSLP::ShuffleInstructionBuilder::finalize(), llvm::FindInsertedValue(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), foldCONCAT_VECTORS(), llvm::codeview::forEachCodeViewRecord(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::RecordRecTy::get(), llvm::ConstantStruct::get(), getBuildDwordsVector(), llvm::Intrinsic::getDeclaration(), llvm::orc::JITDylib::getDFSLinkOrder(), llvm::Record::getDirectSuperClasses(), getExpressionFrameOffset(), getFeatures(), getFPSequenceIfElementsMatch(), getIndexedTypeInternal(), getIntrinsicNameImpl(), getIntSequenceIfElementsMatch(), getMaxCalleeSavedReg(), llvm::DILocation::getMergedLocations(), getOrSelfReference(), llvm::object::MachOObjectFile::getSegmentContents(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::codeview::VFTableShapeRecord::getSlots(), llvm::Intrinsic::getType(), llvm::ConstantStruct::getTypeForElements(), llvm::DFAPacketizer::getUsedResources(), getUUID(), llvm::CallLowering::handleAssignments(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::ScheduleDAGMILive::initRegPressure(), llvm::LanaiInstrInfo::insertBranch(), insertLifetimeMarkersSurroundingCall(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), insertUseHolderAfter(), isInBoundsIndices(), llvm::GCNTTIImpl::isInlineAsmSourceOfDivergence(), llvm::coverage::LineCoverageStats::LineCoverageStats(), llvm::coverage::CoverageMapping::load(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::MipsCallLowering::lowerReturn(), llvm::PPCCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::M68kCallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), lowerV8I16GeneralSingleInputShuffle(), llvm::fuzzerop::matchFirstType(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::fuzzerop::matchScalarOfFirstType(), llvm::raw_ostream::operator<<(), llvm::operator<<(), llvm::PrintMessage(), llvm::PrologEpilogSGPRSpillBuilder::PrologEpilogSGPRSpillBuilder(), llvm::PromoteMemToReg(), llvm::propagateMetadata(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::recognizeBSwapOrBitReverseIdiom(), resolveTypeIndexReferences(), llvm::SIRegisterInfo::restoreSGPR(), llvm::SanitizerBinaryMetadataPass::run(), llvm::MCJIT::runFunction(), llvm::MachineInstr::setMemRefs(), llvm::SelectionDAG::setNodeMemRefs(), llvm::VFABI::setVectorVariantNames(), llvm::SGPRSpillBuilder::SGPRSpillBuilder(), llvm::SIInstrInfo::shouldClusterMemOps(), simplifyGEPInst(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::LoongArchFrameLowering::spillCalleeSavedRegisters(), llvm::RISCVFrameLowering::spillCalleeSavedRegisters(), llvm::CSKYFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillSGPR(), llvm::splitCodeGen(), llvm::CodeViewYAML::toCodeViewSubsectionList(), llvm::pdb::typesetItemList(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::MutableBinaryByteStream::writeBytes(), llvm::AppendingBinaryByteStream::writeBytes(), and writeWithCommas().
end()
template<typename T > iterator llvm::ArrayRef< T >::end () const inline
Definition at line 152 of file ArrayRef.h.
Referenced by llvm::SubtargetFeatures::addFeaturesVector(), addMask(), llvm::DebugLocEntry::addValues(), llvm::DIExpression::append(), llvm::DIExpression::appendOpsToArg(), llvm::DIExpression::appendToStack(), llvm::DominatorTreeBase< BasicBlock, false >::applyUpdates(), llvm::ELFAttrs::attrTypeAsString(), llvm::ELFAttrs::attrTypeFromString(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildBuildVectorTrunc(), llvm::MachineIRBuilder::buildConcatVectors(), buildCopyFromRegs(), buildFixItLine(), llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildMergeValues(), BuildSubAggregate(), llvm::MachineIRBuilder::buildUnmerge(), llvm::Interpreter::callFunction(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::collectPGOFuncNameStrings(), combineShuffleOfSplatVal(), combineShuffleToZeroExtendVectorInReg(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::ComputeLinearIndex(), llvm::concatenateVectors(), llvm::sys::UnicodeCharSet::contains(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), CreateGCRelocates(), llvm::VectorBuilder::createVectorInstruction(), llvm::DeleteDeadBlocks(), llvm::discoverAndMapSubloop(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::objcopy::wasm::dumpSectionToFile(), llvm::DIExpression::elements_end(), llvm::MCDwarfFrameEmitter::Emit(), llvm::BitstreamWriter::emitBlob(), llvm::AAMDNodes::extendToTBAA(), BoUpSLP::ShuffleInstructionBuilder::finalize(), llvm::FindInsertedValue(), findTargetSubtable(), foldGEPOfGEP(), llvm::RecordRecTy::get(), llvm::CondOpInit::get(), llvm::DagInit::get(), getAVX512Node(), llvm::StructLayout::getElementContainingOffset(), getExpressionFrameOffset(), getFauxShuffleMask(), llvm::getFMA3Group(), llvm::ConstantExprKeyType::getHash(), llvm::SelectionDAG::getNode(), getNoopInput(), getRegLanes(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::getShuffleMaskWithWidestElts(), llvm::ConstantExpr::getWithOperands(), llvm::CallGraphSCC::initialize(), llvm::RegPressureTracker::initLiveThru(), llvm::AppendingBinaryByteStream::insert(), llvm::sroa::AllocaSlices::insert(), insertCandidatesWithPendingInjections(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::MCSubtargetInfo::isCPUStringValid(), isFixedVectorShuffle(), llvm::LiveRange::isLiveAtIndexes(), isSubset(), llvm::libDriverMain(), llvm::coverage::CoverageMapping::load(), Lookup(), lookupFoldTableImpl(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), lookupRelaxTableImpl(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), llvm::makePostTransformationMetadata(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), mergeVectorRegsToResultRegs(), llvm::object::MachORebaseEntry::moveNext(), llvm::object::MachOBindEntry::moveNext(), llvm::coverage::FunctionRecordIterator::operator++(), llvm::opt::OptTable::ParseArgs(), ProfileCondOpInit(), ProfileDagInit(), propagateMetadata(), llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read(), removeUnusedBlocksFromParent(), llvm::SDDbgValue::SDDbgValue(), llvm::MachineFunction::setCallSiteLandingPad(), setCoroInfo(), llvm::X86MachineFunctionInfo::setPreallocatedArgOffsets(), llvm::gsym::GsymCreator::setUUID(), stackFrameIncludesInlinedCallStack(), llvm::DbgValueHistoryMap::trimLocationRanges(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), shuffles::vdealvdd(), shuffles::vshuffvdd(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), and writeToResolutionFile().
equals()
template<typename T > bool llvm::ArrayRef< T >::equals (ArrayRef< T > RHS) const inline
equals - Check for element-wise equality.
Definition at line 185 of file ArrayRef.h.
Referenced by llvm::operator==().
front()
template<typename T > const T& llvm::ArrayRef< T >::front () const inline
front - Get the first element.
Definition at line 166 of file ArrayRef.h.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), buildCopyToRegs(), canSinkInstructions(), computeBlockRuns(), DecodeFixedType(), llvm::objcopy::deepWriteArchive(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), llvm::ConstantVector::get(), llvm::orc::JITDylib::getDFSLinkOrder(), llvm::DFAPacketizer::getUsedResources(), isSwitchDense(), llvm::coverage::LineCoverageStats::LineCoverageStats(), llvm::coverage::CoverageMapping::load(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), memOpsHaveSameBasePtr(), MergeCompatibleInvokesImpl(), llvm::PrintMessage(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy >::read(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::SIInstrInfo::shouldClusterMemOps(), llvm::PPCInstrInfo::shouldClusterMemOps(), and llvm::widenShuffleMaskElts().
operator std::vector< T >()
template<typename T > llvm::ArrayRef< T >::operator std::vector< T > () const inline
Definition at line 285 of file ArrayRef.h.
operator=() [1/2]
template<typename T > template<typename U > std::enable_if_t<std::is_same<U, T>::value, ArrayRef<T> >& llvm::ArrayRef< T >::operator= (std::initializer_list< U >) delete
Disallow accidental assignment from a temporary.
The declaration here is extra complicated so that "arrayRef = {}" continues to select the move assignment operator.
operator=() [2/2]
template<typename T > template<typename U > std::enable_if_t<std::is_same<U, T>::value, ArrayRef<T> >& llvm::ArrayRef< T >::operator= (U && Temporary) delete
Disallow accidental assignment from a temporary.
The declaration here is extra complicated so that "arrayRef = {}" continues to select the move assignment operator.
operator[]()
template<typename T > const T& llvm::ArrayRef< T >::operator[] (size_t Index) const inline
Definition at line 254 of file ArrayRef.h.
rbegin()
template<typename T > reverse_iterator llvm::ArrayRef< T >::rbegin () const inline
Definition at line 154 of file ArrayRef.h.
Referenced by getNoopInput(), llvm::ScheduleDAGMI::initQueues(), and rematerializeChain().
rend()
template<typename T > reverse_iterator llvm::ArrayRef< T >::rend () const inline
Definition at line 155 of file ArrayRef.h.
Referenced by getNoopInput(), llvm::ScheduleDAGMI::initQueues(), and rematerializeChain().
size()
template<typename T > size_t llvm::ArrayRef< T >::size () const inline
size - Get the array size.
Definition at line 163 of file ArrayRef.h.
Referenced by addMask(), addOperands(), llvm::gsym::GsymReader::addressForIndex(), addSaveRestoreRegs(), llvm::msf::MSFBuilder::addStream(), llvm::pdb::TpiStreamBuilder::addTypeRecords(), llvm::DbgVariableIntrinsic::addVariableLocationOps(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateRegBlock(), allocateSGPR32InputImpl(), allocateVGPR32Input(), allSameBlock(), allSameType(), llvm::analyzeArguments(), analyzeHeader(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::DomTreeUpdater::applyUpdates(), llvm::SimpleBitstreamCursor::AtEndOfStream(), llvm::MachineIRBuilder::buildBuildVectorConstant(), buildClonedLoopBlocks(), buildClonedLoops(), buildCopyFromRegs(), buildCopyToRegs(), buildFatArchList(), llvm::coro::Shape::buildFrom(), llvm::CSEMIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstr(), llvm::BuildMI(), buildNew(), buildOrChain(), buildShuffleEntryMask(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::Interpreter::callFunction(), llvm::orc::SelfExecutorProcessControl::callWrapperAsync(), llvm::SystemZInstrInfo::canInsertSelect(), llvm::SimpleBitstreamCursor::canSkipToPos(), canVectorizeLoads(), CC_AIX(), CC_ARM_AAPCS_Custom_Aggregate(), CheckForLiveRegDefMasked(), checkOperandCount(), llvm::cleanUpTempFiles(), llvm::cloneAndAdaptNoAliasScopes(), llvm::MachineInstr::cloneMergedMemRefs(), clusterSortPtrAccesses(), llvm::FunctionComparator::cmpOperations(), coerceArguments(), CollectAddOperandsWithScales(), llvm::collectPGOFuncNameStrings(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineShuffleOfSplatVal(), combineShuffleToZeroExtendVectorInReg(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), CompareSCEVComplexity(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::compression::zlib::compress(), computeCalleeSaveRegisterPairs(), computeExcessPressureDelta(), computeIndirectRegIndex(), llvm::SelectionDAG::computeKnownBits(), llvm::ComputeMappedEditDistance(), computeMaxPressureDelta(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::concatenateVectors(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantFoldGetElementPtr(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::AArch64InstrInfo::copyGPRRegTuple(), llvm::GlobalObject::copyMetadata(), llvm::SIInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysRegTuple(), llvm::crc32(), llvm::GetElementPtrConstantExpr::Create(), llvm::GetElementPtrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::CallBrInst::Create(), llvm::IRBuilderBase::CreateAnd(), llvm::MDBuilder::createBranchWeights(), CreateGCRelocates(), createIndexMap(), llvm::IRBuilderBase::CreateLogicalOr(), llvm::IRBuilderBase::CreateNAryOp(), llvm::IRBuilderBase::CreateOr(), llvm::createPHIsForSplitLoopExit(), llvm::createSanitizerCtorAndInitFunctions(), llvm::OpenMPIRBuilder::createSections(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAATypeNode(), createTuple(), llvm::VectorBuilder::createVectorInstruction(), LiveDebugValues::DbgValue::DbgValue(), DecodeIITType(), llvm::AMDGPUDisassembler::decodeKernelDescriptor(), llvm::AMDGPUDisassembler::decodeKernelDescriptorDirective(), llvm::AMDGPUDisassembler::decodeLiteralConstant(), llvm::DecodePSHUFBMask(), DecodeRegisterClass(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMV3Mask(), llvm::DecodeVPERMVMask(), llvm::DecodeVPPERMMask(), llvm::compression::zlib::decompress(), llvm::DeleteDeadBlocks(), llvm::GCNIterativeScheduler::detachSchedule(), llvm::object::doesXCOFFTracebackTableBegin(), dumpLocationExpr(), llvm::dumpRegSetPressure(), llvm::objcopy::wasm::dumpSectionToFile(), eat12Bytes(), eatBytes(), EltsFromConsecutiveLoads(), llvm::MCDwarfLineTableHeader::Emit(), llvm::BitstreamWriter::emitBlob(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::OpenMPIRBuilder::emitTargetKernel(), llvm::objcopy::elf::SectionTableRef::end(), llvm::coverage::CounterMappingContext::evaluate(), expandSGPRCopy(), llvm::SimpleBitstreamCursor::fillCurWord(), BoUpSLP::ShuffleInstructionBuilder::finalize(), findBestNonTrivialUnswitchCandidate(), llvm::FindInsertedValue(), llvm::wholeprogramdevirt::findLowestOffset(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), llvm::SelectionDAG::FoldConstantArithmetic(), foldGEPOfGEP(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldSwitchToSelect(), llvm::InstCombinerImpl::foldVectorBinop(), llvm::codeview::forEachCodeViewRecord(), llvm::codeview::detail::GuidAdapter::format(), formSplatFromShuffles(), llvm::CodeViewYAML::fromDebugH(), llvm::FunctionType::get(), llvm::ConstantStruct::get(), llvm::AttributeList::get(), llvm::ConstantVector::get(), llvm::ConstantDataArray::get(), llvm::TargetExtType::get(), llvm::ConstantDataVector::get(), llvm::CondOpInit::get(), llvm::DagInit::get(), llvm::gsym::GsymReader::getAddressInfoOffset(), llvm::gsym::GsymReader::getAddrOffsets(), llvm::RecordKeeper::getAllDerivedDefinitions(), llvm::getBitcodeFileContents(), getBuildDwordsVector(), llvm::codeview::getBytesAsCharacters(), llvm::irsymtab::Reader::getComdatTable(), llvm::SCEVUnionPredicate::getComplexity(), llvm::irsymtab::Reader::getDependentLibraries(), llvm::object::Elf_Note_Impl< ELFT >::getDescAsStringRef(), llvm::codeview::VFTableShapeRecord::getEntryCount(), getExpressionFrameOffset(), llvm::MachineFunction::getFilterIDFor(), llvm::CCState::getFirstUnallocated(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::gsym::GsymReader::getFunctionInfo(), llvm::SelectionDAG::getGatherVP(), llvm::ConstantExpr::getGetElementPtr(), llvm::AArch64Disassembler::getInstruction(), llvm::AMDGPUDisassembler::getInstruction(), llvm::HexagonTTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::BinaryByteStream::getLength(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedScatter(), getMaxCalleeSavedReg(), llvm::DILocation::getMergedLocations(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::irsymtab::Reader::getNumModules(), llvm::opt::OptTable::getNumOptions(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperandsScalarizationOverhead(), llvm::AllocationOrder::getOrderLimitEnd(), getOrSelfReference(), llvm::HvxSelector::getPerfectCompletions(), llvm::MachineTraceMetrics::Trace::getResourceDepth(), llvm::MachineTraceMetrics::Trace::getResourceLength(), getSameOpcode(), llvm::SelectionDAG::getScatterVP(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), llvm::getShuffleMaskWithWidestElts(), getStatepointArgs(), getStatepointBundles(), llvm::ConstantStruct::getTypeForElements(), llvm::RegPressureTracker::getUpwardPressureDelta(), getUUID(), llvm::SelectionDAG::getVTList(), llvm::ConstantExpr::getWithOperands(), llvm::MipsTargetLowering::HandleByVal(), llvm::Record::hasDirectSuperClass(), llvm::pdb::hashStringV2(), shuffles::hi(), IncomingValuesAreCompatible(), llvm::LanaiInstrInfo::insertBranch(), insertCandidatesWithPendingInjections(), llvm::SystemZInstrInfo::insertSelect(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), llvm::inversePermutation(), llvm::GCNTTIImpl::isAlwaysUniform(), llvm::sampleprof::SampleContext::isBaseContext(), isBigEndian(), isFixedVectorShuffle(), isInBoundsIndices(), llvm::GCNTTIImpl::isInlineAsmSourceOfDivergence(), isReplicationMaskWithParams(), isShuffleEquivalent(), llvm::SimpleBitstreamCursor::isSizePlausible(), isStrictSubset(), isSubset(), isSwitchDense(), isTargetShuffleEquivalent(), llvm::SelectionDAG::isUndef(), llvm::codeview::CVRecord< TypeLeafKind >::kind(), llvm::BinaryItemTraits< codeview::CVSymbol >::length(), llvm::codeview::CVRecord< TypeLeafKind >::length(), llvm::codeview::limitSymbolArrayToScope(), llvm::coverage::LineCoverageStats::LineCoverageStats(), shuffles::lo(), llvm::coverage::CoverageMapping::load(), llvm::object::ResourceSectionRef::load(), llvm::gsym::GsymReader::lookup(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::SPIRVCallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), llvm::SystemZTargetLowering::makeExternalCall(), llvm::orc::makeJITDylibSearchOrder(), llvm::TargetLowering::makeLibCall(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::SIInstrInfo::materializeImmediate(), memOpsHaveSameBaseOperands(), llvm::object::MinidumpFile::MemoryInfoIterator::MemoryInfoIterator(), MergeCompatibleInvokes(), MergeCompatibleInvokesImpl(), mergeVectorRegsToResultRegs(), llvm::object::MachOChainedFixupEntry::moveNext(), nextByte(), nextLEB(), llvm::object::MinidumpFile::MemoryInfoIterator::operator*(), llvm::sampleprof::SampleContext::operator<(), llvm::object::MinidumpFile::MemoryInfoIterator::operator==(), llvm::ConstantExprKeyType::operator==(), packSegmentMask(), llvm::ELFAttributeParser::parse(), parseImmediate(), llvm::ELFAttributeParser::parseStringAttribute(), peek(), performBlockTailMerging(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::prepareTempFiles(), llvm::PrintMessage(), llvm::BitcodeAnalyzer::printStats(), ProfileCondOpInit(), ProfileRecordRecTy(), llvm::PrologEpilogSGPRSpillBuilder::PrologEpilogSGPRSpillBuilder(), llvm::propagateMetadata(), llvm::detail::BCRecordCoding< ElementTy >::read(), llvm::AppendingBinaryByteStream::readBytes(), llvm::BinaryStreamReader::readCString(), llvm::BinaryStreamReader::readFixedString(), readInstruction16(), readInstruction24(), readInstruction32(), readInstruction64(), llvm::BinaryStreamReader::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::readWideAPInt(), rebuildLoopAfterUnswitch(), llvm::BuildVectorSDNode::recastRawBits(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::Attributor::registerFunctionSignatureRewrite(), relocationViaAlloca(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::orc::ExecutionSession::runJITDispatchHandler(), llvm::IRTranslator::runOnMachineFunction(), llvm::SDDbgValue::SDDbgValue(), SelectOpcodeFromVT(), llvm::orc::FDSimpleRemoteEPCTransport::sendMessage(), LiveDebugValues::DbgValue::setDbgOpIDs(), llvm::SelectionDAG::setNodeMemRefs(), llvm::SGPRSpillBuilder::SGPRSpillBuilder(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::PPCInstrInfo::shouldClusterMemOps(), simplifyExtractValueInst(), simplifyGEPInst(), llvm::simplifyInstructionWithOperands(), simplifyInstructionWithOperands(), llvm::mca::SourceMgr::size(), llvm::objcopy::elf::SectionTableRef::size(), llvm::SimpleBitstreamCursor::SizeInBytes(), llvm::SimpleBitstreamCursor::skipToEnd(), llvm::sortPtrAccesses(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillSGPR(), llvm::splitCodeGen(), llvm::BinaryByteStream::str(), llvm::codeview::CVRecord< TypeLeafKind >::str_data(), StrengthenNoWrapFlags(), llvm::ARMBaseInstrInfo::SubsumesPredicate(), llvm::PPCInstrInfo::SubsumesPredicate(), llvm::orc::SymbolLookupSet::SymbolLookupSet(), llvm::OpenMPIRBuilder::tileLoops(), llvm::pdb::typesetItemList(), unswitchNontrivialInvariants(), UpdateAnalysisInformation(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), llvm::StackMapParser< Endianness >::validateHeader(), shuffles::vdeal(), shuffles::vdealb4w(), shuffles::vdealvdd(), shuffles::vpack(), shuffles::vshuff(), shuffles::vshuffvdd(), llvm::widenShuffleMaskElts(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::coverage::CoverageFilenamesSectionWriter::write(), llvm::coverage::CoverageMappingWriter::write(), llvm::writeArchiveToStream(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::BinaryStreamWriter::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::object::writeUniversalBinaryToStream(), and writeWithCommas().
slice() [1/2]
template<typename T > ArrayRef<T> llvm::ArrayRef< T >::slice (size_t N) const inline
slice(n) - Chop off the first N elements of the array.
Definition at line 199 of file ArrayRef.h.
Referenced by llvm::ArrayRef< uint64_t >::slice().
slice() [2/2]
template<typename T > ArrayRef<T> llvm::ArrayRef< T >::slice (size_t N, size_t M) const inline
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
Definition at line 193 of file ArrayRef.h.
Referenced by buildNew(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantExprKeyType::create(), DecodeFixedType(), llvm::dlltoolDriverMain(), eat12Bytes(), eatBytes(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::FindInsertedValue(), llvm::wholeprogramdevirt::findLowestOffset(), llvm::ConstantExpr::getAsInstruction(), getIndexedTypeInternal(), llvm::AMDGPUDisassembler::getInstruction(), llvm::object::MinidumpFile::getRawStream(), llvm::VPInterleaveRecipe::getStoredValues(), llvm::jitlink::Symbol::getSymbolContent(), llvm::SelectionDAG::getTokenFactor(), llvm::ConstantExpr::getWithOperands(), llvm::pdb::hashStringV2(), llvm::codeview::GloballyHashedType::hashType(), isHorizontalBinOp(), llvm::libDriverMain(), LowerAVXCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::BinaryByteStream::readBytes(), llvm::BinaryByteStream::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::Interpreter::runFunction(), simplifyExtractValueInst(), and llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit().
take_back()
template<typename T > ArrayRef<T> llvm::ArrayRef< T >::take_back (size_t N = 1) const inline
Return a copy of *this with only the last N elements.
Definition at line 233 of file ArrayRef.h.
Referenced by shuffles::hi(), and optimizeVectorResizeWithIntegerBitCasts().
take_front()
template<typename T > ArrayRef<T> llvm::ArrayRef< T >::take_front (size_t N = 1) const inline
Return a copy of *this with only the first N elements.
Definition at line 226 of file ArrayRef.h.
Referenced by buildCopyFromRegs(), llvm::codeview::forEachCodeViewRecord(), llvm::AttributeList::get(), llvm::codeview::GloballyHashedType::hashType(), llvm::sampleprof::SampleContext::IsPrefixOf(), shuffles::lo(), optimizeVectorResizeWithIntegerBitCasts(), llvm::BinaryItemStream< T, Traits >::readBytes(), llvm::pdb::typesetItemList(), and writeWithCommas().
take_until()
template<typename T > template<class PredicateT > ArrayRef<T> llvm::ArrayRef< T >::take_until (PredicateT Pred) const inline
Return the first N elements of this Array that don't satisfy the given predicate.
Definition at line 247 of file ArrayRef.h.
take_while()
template<typename T > template<class PredicateT > ArrayRef<T> llvm::ArrayRef< T >::take_while (PredicateT Pred) const inline
Return the first N elements of this Array that satisfy the given predicate.
Definition at line 241 of file ArrayRef.h.
vec()
template<typename T > std::vector<T> llvm::ArrayRef< T >::vec () const inline
Definition at line 278 of file ArrayRef.h.
Referenced by combineDIExpressions().
The documentation for this class was generated from the following files:
include/llvm/ADT/APInt.h
include/llvm/ADT/ArrayRef.h