LLVM: llvm::SIMachineFunctionInfo Class Reference
llvm::SIMachineFunctionInfo Class Reference final
This class keeps track of the SPI_SP_INPUT_ADDR config register, which tells the hardware which interpolation parameters to load.
#include "Target/AMDGPU/SIMachineFunctionInfo.h"
Classes
struct VGPRSpillToAGPR
Public Member Functions
Register getVGPRForAGPRCopy () const
void setVGPRForAGPRCopy (Register NewVGPRForAGPRCopy)
bool isCalleeSavedReg (const MCPhysReg *CSRegs, MCPhysReg Reg) const
SIMachineFunctionInfo (const SIMachineFunctionInfo &MFI)=default
SIMachineFunctionInfo (const Function &F, const GCNSubtarget *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
bool initializeBaseYamlFields (const yaml::SIMachineFunctionInfo &YamlMFI, const MachineFunction &MF, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange)
void reserveWWMRegister (Register Reg)
AMDGPU::SIModeRegisterDefaults getMode () const
ArrayRef< SIRegisterInfo::SpilledReg > getSGPRSpillToVGPRLanes (int FrameIndex) const
ArrayRef< Register > getSGPRSpillVGPRs () const
const WWMSpillsMap & getWWMSpills () const
const ReservedRegSet & getWWMReservedRegs () const
const PrologEpilogSGPRSpillsMap & getPrologEpilogSGPRSpills () const
void addToPrologEpilogSGPRSpills (Register Reg, PrologEpilogSGPRSaveRestoreInfo SI)
bool hasPrologEpilogSGPRSpillEntry (Register Reg) const
Register getScratchSGPRCopyDstReg (Register Reg) const
void getAllScratchSGPRCopyDstRegs (SmallVectorImpl< Register > &Regs) const
bool checkIndexInPrologEpilogSGPRSpills (int FI) const
const PrologEpilogSGPRSaveRestoreInfo & getPrologEpilogSGPRSaveRestoreInfo (Register Reg) const
ArrayRef< SIRegisterInfo::SpilledReg > getPrologEpilogSGPRSpillToVGPRLanes (int FrameIndex) const
void allocateWWMSpill (MachineFunction &MF, Register VGPR, uint64_t Size=4, Align Alignment=Align(4))
void splitWWMSpillRegisters (MachineFunction &MF, SmallVectorImpl< std::pair< Register, int >> &CalleeSavedRegs, SmallVectorImpl< std::pair< Register, int >> &ScratchRegs) const
ArrayRef< MCPhysReg > getAGPRSpillVGPRs () const
ArrayRef< MCPhysReg > getVGPRSpillAGPRs () const
MCPhysReg getVGPRToAGPRSpill (int FrameIndex, unsigned Lane) const
void setVGPRToAGPRSpillDead (int FrameIndex)
bool allocateSGPRSpillToVGPRLane (MachineFunction &MF, int FI, bool IsPrologEpilog=false)
bool allocateVGPRSpillToAGPR (MachineFunction &MF, int FI, bool isAGPRtoVGPR)
Reserve AGPRs or VGPRs to support spilling for FrameIndex FI.
bool removeDeadFrameIndices (MachineFrameInfo &MFI, bool ResetSGPRSpillStackIDs)
If ResetSGPRSpillStackIDs is true, reset the stack ID from sgpr-spill to the default stack.
int getScavengeFI (MachineFrameInfo &MFI, const SIRegisterInfo &TRI)
std::optional< int > getOptionalScavengeFI () const
unsigned getBytesInStackArgArea () const
void setBytesInStackArgArea (unsigned Bytes)
Register addPrivateSegmentBuffer (const SIRegisterInfo &TRI)
Register addDispatchPtr (const SIRegisterInfo &TRI)
Register addQueuePtr (const SIRegisterInfo &TRI)
Register addKernargSegmentPtr (const SIRegisterInfo &TRI)
Register addDispatchID (const SIRegisterInfo &TRI)
Register addFlatScratchInit (const SIRegisterInfo &TRI)
Register addImplicitBufferPtr (const SIRegisterInfo &TRI)
Register addLDSKernelId ()
Register addReservedUserSGPR ()
Increment user SGPRs used for padding the argument list only.
Register addWorkGroupIDX (bool HasArchitectedSGPRs)
Register addWorkGroupIDY (bool HasArchitectedSGPRs)
Register addWorkGroupIDZ (bool HasArchitectedSGPRs)
Register addWorkGroupInfo ()
void setWorkItemIDX (ArgDescriptor Arg)
void setWorkItemIDY (ArgDescriptor Arg)
void setWorkItemIDZ (ArgDescriptor Arg)
Register addPrivateSegmentWaveByteOffset ()
void setPrivateSegmentWaveByteOffset (Register Reg)
bool hasPrivateSegmentBuffer () const
bool hasDispatchPtr () const
bool hasQueuePtr () const
bool hasKernargSegmentPtr () const
bool hasDispatchID () const
bool hasFlatScratchInit () const
bool hasWorkGroupIDX () const
bool hasWorkGroupIDY () const
bool hasWorkGroupIDZ () const
bool hasWorkGroupInfo () const
bool hasLDSKernelId () const
bool hasPrivateSegmentWaveByteOffset () const
bool hasWorkItemIDX () const
bool hasWorkItemIDY () const
bool hasWorkItemIDZ () const
bool hasImplicitArgPtr () const
bool hasImplicitBufferPtr () const
AMDGPUFunctionArgInfo & getArgInfo ()
const AMDGPUFunctionArgInfo & getArgInfo () const
std::tuple< const ArgDescriptor *, const TargetRegisterClass *, LLT > getPreloadedValue (AMDGPUFunctionArgInfo::PreloadedValue Value) const
MCRegister getPreloadedReg (AMDGPUFunctionArgInfo::PreloadedValue Value) const
unsigned getGITPtrHigh () const
Register getGITPtrLoReg (const MachineFunction &MF) const
uint32_t get32BitAddressHighBits () const
unsigned getNumUserSGPRs () const
unsigned getNumPreloadedSGPRs () const
Register getPrivateSegmentWaveByteOffsetSystemSGPR () const
Register getScratchRSrcReg () const
Returns the physical register reserved for use as the resource descriptor for scratch accesses.
void setScratchRSrcReg (Register Reg)
Register getFrameOffsetReg () const
void setFrameOffsetReg (Register Reg)
void setStackPtrOffsetReg (Register Reg)
Register getStackPtrOffsetReg () const
Register getQueuePtrUserSGPR () const
Register getImplicitBufferPtrUserSGPR () const
bool hasSpilledSGPRs () const
void setHasSpilledSGPRs (bool Spill=true)
bool hasSpilledVGPRs () const
void setHasSpilledVGPRs (bool Spill=true)
bool hasNonSpillStackObjects () const
void setHasNonSpillStackObjects (bool StackObject=true)
bool isStackRealigned () const
void setIsStackRealigned (bool Realigned=true)
unsigned getNumSpilledSGPRs () const
unsigned getNumSpilledVGPRs () const
void addToSpilledSGPRs (unsigned num)
void addToSpilledVGPRs (unsigned num)
unsigned getPSInputAddr () const
unsigned getPSInputEnable () const
bool isPSInputAllocated (unsigned Index) const
void markPSInputAllocated (unsigned Index)
void markPSInputEnabled (unsigned Index)
bool returnsVoid () const
void setIfReturnsVoid (bool Value)
std::pair< unsigned, unsigned > getFlatWorkGroupSizes () const
unsigned getMinFlatWorkGroupSize () const
unsigned getMaxFlatWorkGroupSize () const
std::pair< unsigned, unsigned > getWavesPerEU () const
unsigned getMinWavesPerEU () const
unsigned getMaxWavesPerEU () const
Register getWorkGroupIDSGPR (unsigned Dim) const
const AMDGPUGWSResourcePseudoSourceValue * getGWSPSV (const AMDGPUTargetMachine &TM)
unsigned getOccupancy () const
unsigned getMinAllowedOccupancy () const
void limitOccupancy (const MachineFunction &MF)
void limitOccupancy (unsigned Limit)
void increaseOccupancy (const MachineFunction &MF, unsigned Limit)
bool mayNeedAGPRs () const
bool mayUseAGPRs (const Function &F) const
bool usesAGPRs (const MachineFunction &MF) const
Public Member Functions inherited from llvm::AMDGPUMachineFunction
AMDGPUMachineFunction (const Function &F, const AMDGPUSubtarget &ST)
uint64_t getExplicitKernArgSize () const
Align getMaxKernArgAlign () const
uint32_t getLDSSize () const
uint32_t getGDSSize () const
bool isEntryFunction () const
bool isModuleEntryFunction () const
bool hasNoSignedZerosFPMath () const
bool isMemoryBound () const
bool needsWaveLimiter () const
unsigned allocateLDSGlobal (const DataLayout &DL, const GlobalVariable &GV)
unsigned allocateLDSGlobal (const DataLayout &DL, const GlobalVariable &GV, Align Trailing)
void allocateKnownAddressLDSGlobal (const Function &F)
Align getDynLDSAlign () const
void setDynLDSAlign (const DataLayout &DL, const GlobalVariable &GV)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Friends
class GCNTargetMachine
Additional Inherited Members
Static Public Member Functions inherited from llvm::AMDGPUMachineFunction
static const Function * getKernelLDSFunctionFromGlobal (const GlobalVariable &GV)
static const GlobalVariable * getKernelLDSGlobalFromFunction (const Function &F)
static bool isKnownAddressLDSGlobal (const GlobalVariable &GV)
static unsigned calculateKnownAddressOfLDSGlobal (const GlobalVariable &GV)
static std::optional< uint32_t > getLDSKernelIdMetadata (const Function &F)
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Protected Attributes inherited from llvm::AMDGPUMachineFunction
uint64_t ExplicitKernArgSize = 0
Align MaxKernArgAlign
uint32_t LDSSize = 0
Number of bytes in the LDS that are being used.
uint32_t GDSSize = 0
uint32_t StaticLDSSize = 0
Number of bytes in the LDS allocated statically.
uint32_t StaticGDSSize = 0
Align DynLDSAlign
Align for dynamic shared memory if any.
bool IsEntryFunction = false
bool IsModuleEntryFunction = false
bool NoSignedZerosFPMath = false
bool MemoryBound = false
bool WaveLimiter = false
Detailed Description
This class keeps track of the SPI_SP_INPUT_ADDR config register, which tells the hardware which interpolation parameters to load.
Definition at line 358 of file SIMachineFunctionInfo.h.
Constructor & Destructor Documentation
SIMachineFunctionInfo() [1/2]
llvm::SIMachineFunctionInfo::SIMachineFunctionInfo (const SIMachineFunctionInfo & MFI) default
SIMachineFunctionInfo() [2/2]
SIMachineFunctionInfo::SIMachineFunctionInfo (const Function & F, const GCNSubtarget * STI)
Definition at line 37 of file SIMachineFunctionInfo.cpp.
References llvm::CallingConv::AMDGPU_Gfx, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_PS, CC, llvm::ArgDescriptor::createRegister(), F, llvm::AMDGPUArgumentUsageInfo::FixedABIFunctionInfo, llvm::AMDGPU::getInitialPSInputAddr(), llvm::AMDGPUMachineFunction::getLDSSize(), llvm::AMDGPUSubtarget::GFX9, HasCalls, llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::AMDGPU::isGraphics(), llvm::max(), llvm::AMDGPUMachineFunction::MaxKernArgAlign, mayUseAGPRs(), S, llvm::CallingConv::SPIR_KERNEL, and llvm::ARM_MB::ST.
Member Function Documentation
addDispatchID()
Register SIMachineFunctionInfo::addDispatchID (const SIRegisterInfo & TRI)
Definition at line 251 of file SIMachineFunctionInfo.cpp.
References llvm::ArgDescriptor::createRegister(), llvm::TargetRegisterInfo::getMatchingSuperReg(), and TRI.
addDispatchPtr()
Register SIMachineFunctionInfo::addDispatchPtr (const SIRegisterInfo & TRI)
Definition at line 229 of file SIMachineFunctionInfo.cpp.
References llvm::ArgDescriptor::createRegister(), llvm::TargetRegisterInfo::getMatchingSuperReg(), and TRI.
addFlatScratchInit()
Register SIMachineFunctionInfo::addFlatScratchInit (const SIRegisterInfo & TRI)
Definition at line 258 of file SIMachineFunctionInfo.cpp.
References llvm::ArgDescriptor::createRegister(), llvm::TargetRegisterInfo::getMatchingSuperReg(), and TRI.
addImplicitBufferPtr()
Register SIMachineFunctionInfo::addImplicitBufferPtr (const SIRegisterInfo & TRI)
Definition at line 265 of file SIMachineFunctionInfo.cpp.
References llvm::ArgDescriptor::createRegister(), llvm::TargetRegisterInfo::getMatchingSuperReg(), and TRI.
addKernargSegmentPtr()
Register SIMachineFunctionInfo::addKernargSegmentPtr (const SIRegisterInfo & TRI)
Definition at line 243 of file SIMachineFunctionInfo.cpp.
References llvm::ArgDescriptor::createRegister(), llvm::TargetRegisterInfo::getMatchingSuperReg(), and TRI.
addLDSKernelId()
Register SIMachineFunctionInfo::addLDSKernelId ()
Definition at line 272 of file SIMachineFunctionInfo.cpp.
References llvm::ArgDescriptor::createRegister().
addPrivateSegmentBuffer()
Register SIMachineFunctionInfo::addPrivateSegmentBuffer (const SIRegisterInfo & TRI)
Definition at line 220 of file SIMachineFunctionInfo.cpp.
References llvm::ArgDescriptor::createRegister(), llvm::TargetRegisterInfo::getMatchingSuperReg(), and TRI.
addPrivateSegmentWaveByteOffset()
Register llvm::SIMachineFunctionInfo::addPrivateSegmentWaveByteOffset () inline
Definition at line 744 of file SIMachineFunctionInfo.h.
References llvm::ArgDescriptor::createRegister().
addQueuePtr()
Register SIMachineFunctionInfo::addQueuePtr (const SIRegisterInfo & TRI)
Definition at line 236 of file SIMachineFunctionInfo.cpp.
References llvm::ArgDescriptor::createRegister(), llvm::TargetRegisterInfo::getMatchingSuperReg(), and TRI.
addReservedUserSGPR()
Register llvm::SIMachineFunctionInfo::addReservedUserSGPR () inline
Increment user SGPRs used for padding the argument list only.
Definition at line 689 of file SIMachineFunctionInfo.h.
addToPrologEpilogSGPRSpills()
void llvm::SIMachineFunctionInfo::addToPrologEpilogSGPRSpills (Register Reg, PrologEpilogSGPRSaveRestoreInfo SI) inline
Definition at line 574 of file SIMachineFunctionInfo.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), and SI.
Referenced by getVGPRSpillLaneOrTempRegister().
addToSpilledSGPRs()
void llvm::SIMachineFunctionInfo::addToSpilledSGPRs (unsigned num) inline
Definition at line 942 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::spillEmergencySGPR(), and llvm::SIRegisterInfo::spillSGPR().
addToSpilledVGPRs()
void llvm::SIMachineFunctionInfo::addToSpilledVGPRs (unsigned num) inline
Definition at line 946 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), and llvm::SIRegisterInfo::eliminateFrameIndex().
addWorkGroupIDX()
Register llvm::SIMachineFunctionInfo::addWorkGroupIDX (bool HasArchitectedSGPRs) inline
Definition at line 696 of file SIMachineFunctionInfo.h.
References llvm::ArgDescriptor::createRegister().
addWorkGroupIDY()
Register llvm::SIMachineFunctionInfo::addWorkGroupIDY (bool HasArchitectedSGPRs) inline
Definition at line 705 of file SIMachineFunctionInfo.h.
References llvm::ArgDescriptor::createRegister(), hasWorkGroupIDZ(), and llvm::BitmaskEnumDetail::Mask().
addWorkGroupIDZ()
Register llvm::SIMachineFunctionInfo::addWorkGroupIDZ (bool HasArchitectedSGPRs) inline
Definition at line 715 of file SIMachineFunctionInfo.h.
References llvm::ArgDescriptor::createRegister(), and llvm::BitmaskEnumDetail::Mask().
addWorkGroupInfo()
Register llvm::SIMachineFunctionInfo::addWorkGroupInfo () inline
Definition at line 725 of file SIMachineFunctionInfo.h.
References llvm::ArgDescriptor::createRegister().
allocateSGPRSpillToVGPRLane()
bool SIMachineFunctionInfo::allocateSGPRSpillToVGPRLane (MachineFunction & MF, int FI, bool IsPrologEpilog = false)
Definition at line 367 of file SIMachineFunctionInfo.cpp.
References assert(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getSubtarget(), I, and llvm::ARM_MB::ST.
Referenced by getVGPRSpillLaneOrTempRegister().
allocateVGPRSpillToAGPR()
bool SIMachineFunctionInfo::allocateVGPRSpillToAGPR (MachineFunction & MF, int FI, bool isAGPRtoVGPR)
Reserve AGPRs or VGPRs to support spilling for FrameIndex FI.
Either AGPR is spilled to VGPR to vice versa. Returns true if a FI can be eliminated completely.
Definition at line 414 of file SIMachineFunctionInfo.cpp.
References assert(), llvm::find_if(), llvm::Function::getCallingConv(), llvm::TargetRegisterInfo::getCallPreservedMask(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterClass::getRegisters(), llvm::MachineFunction::getSubtarget(), I, llvm::MachineFrameInfo::isSpillSlotObjectIndex(), MRI, llvm::BitVector::push_back(), llvm::MachineRegisterInfo::reserveReg(), llvm::BitVector::resize(), llvm::BitVector::set(), llvm::BitVector::setBitsInMask(), llvm::ARM_MB::ST, and TRI.
Referenced by llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
allocateWWMSpill()
void SIMachineFunctionInfo::allocateWWMSpill (MachineFunction & MF, Register VGPR, uint64_t Size = 4, Align Alignment = Align(4))
Definition at line 278 of file SIMachineFunctionInfo.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::count(), llvm::MachineFrameInfo::CreateSpillStackObject(), llvm::MachineFunction::getFrameInfo(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::insert(), and llvm::AMDGPUMachineFunction::isEntryFunction().
Referenced by llvm::SIFrameLowering::determineCalleeSaves(), and llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
checkIndexInPrologEpilogSGPRSpills()
bool llvm::SIMachineFunctionInfo::checkIndexInPrologEpilogSGPRSpills (int FI) const inline
Definition at line 604 of file SIMachineFunctionInfo.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::find_if(), SI, and llvm::SPILL_TO_VGPR_LANE.
Referenced by allSGPRSpillsAreDead(), and removeDeadFrameIndices().
clone()
MachineFunctionInfo * SIMachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 206 of file SIMachineFunctionInfo.cpp.
References llvm::MachineFunction::cloneInfo().
get32BitAddressHighBits()
uint32_t llvm::SIMachineFunctionInfo::get32BitAddressHighBits () const inline
Definition at line 845 of file SIMachineFunctionInfo.h.
getAGPRSpillVGPRs()
ArrayRef<MCPhysReg> llvm::SIMachineFunctionInfo::getAGPRSpillVGPRs () const inline
Definition at line 638 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::getReservedRegs(), and llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
getAllScratchSGPRCopyDstRegs()
void llvm::SIMachineFunctionInfo::getAllScratchSGPRCopyDstRegs (SmallVectorImpl< Register > & Regs) const inline
Definition at line 596 of file SIMachineFunctionInfo.h.
References llvm::COPY_TO_SCRATCH_SGPR, and SI.
Referenced by llvm::SIFrameLowering::emitCSRSpillStores().
getArgInfo() [1/2]
AMDGPUFunctionArgInfo& llvm::SIMachineFunctionInfo::getArgInfo () inline
Definition at line 821 of file SIMachineFunctionInfo.h.
Referenced by llvm::AMDGPUCallLowering::passSpecialInputs().
getArgInfo() [2/2]
const AMDGPUFunctionArgInfo& llvm::SIMachineFunctionInfo::getArgInfo () const inline
Definition at line 825 of file SIMachineFunctionInfo.h.
getBytesInStackArgArea()
unsigned llvm::SIMachineFunctionInfo::getBytesInStackArgArea () const inline
Definition at line 670 of file SIMachineFunctionInfo.h.
Referenced by llvm::AMDGPUCallLowering::areCalleeOutgoingArgsTailCallable(), and llvm::SITargetLowering::isEligibleForTailCallOptimization().
getFlatWorkGroupSizes()
std::pair<unsigned, unsigned> llvm::SIMachineFunctionInfo::getFlatWorkGroupSizes () const inline
Returns
A pair of default/requested minimum/maximum flat work group sizes for this function.
Definition at line 980 of file SIMachineFunctionInfo.h.
getFrameOffsetReg()
Register llvm::SIMachineFunctionInfo::getFrameOffsetReg () const inline
Definition at line 872 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::assignCalleeSavedSpillSlots(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), llvm::SIFrameLowering::emitCSRSpillRestores(), llvm::SIFrameLowering::emitCSRSpillStores(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::SIFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), llvm::SIRegisterInfo::getFrameRegister(), llvm::SIRegisterInfo::getReservedRegs(), and llvm::SIRegisterInfo::spillSGPR().
getGITPtrHigh()
unsigned llvm::SIMachineFunctionInfo::getGITPtrHigh () const inline
Definition at line 839 of file SIMachineFunctionInfo.h.
Referenced by buildGitPtr().
getGITPtrLoReg()
Register SIMachineFunctionInfo::getGITPtrLoReg (const MachineFunction & MF) const
Definition at line 541 of file SIMachineFunctionInfo.cpp.
References llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), and llvm::ARM_MB::ST.
Referenced by buildGitPtr(), and llvm::SIFrameLowering::emitEntryFunctionPrologue().
getGWSPSV()
const AMDGPUGWSResourcePseudoSourceValue* llvm::SIMachineFunctionInfo::getGWSPSV (const AMDGPUTargetMachine & TM) inline
Definition at line 1027 of file SIMachineFunctionInfo.h.
Referenced by llvm::SITargetLowering::getTgtMemIntrinsic(), and llvm::AMDGPUMIRFormatter::parseCustomPseudoSourceValue().
getImplicitBufferPtrUserSGPR()
Register llvm::SIMachineFunctionInfo::getImplicitBufferPtrUserSGPR () const inline
Definition at line 898 of file SIMachineFunctionInfo.h.
getMaxFlatWorkGroupSize()
unsigned llvm::SIMachineFunctionInfo::getMaxFlatWorkGroupSize () const inline
Returns
Default/requested maximum flat work group size for this function.
Definition at line 990 of file SIMachineFunctionInfo.h.
getMaxWavesPerEU()
unsigned llvm::SIMachineFunctionInfo::getMaxWavesPerEU () const inline
Returns
Default/requested maximum number of waves per execution unit.
Definition at line 1006 of file SIMachineFunctionInfo.h.
Referenced by llvm::UnclusteredHighRPStage::initGCNSchedStage(), and limitOccupancy().
getMinAllowedOccupancy()
unsigned llvm::SIMachineFunctionInfo::getMinAllowedOccupancy () const inline
Definition at line 1035 of file SIMachineFunctionInfo.h.
References llvm::AMDGPUMachineFunction::isMemoryBound(), and llvm::AMDGPUMachineFunction::needsWaveLimiter().
Referenced by llvm::GCNSchedStage::checkScheduling().
getMinFlatWorkGroupSize()
unsigned llvm::SIMachineFunctionInfo::getMinFlatWorkGroupSize () const inline
Returns
Default/requested minimum flat work group size for this function.
Definition at line 985 of file SIMachineFunctionInfo.h.
getMinWavesPerEU()
unsigned llvm::SIMachineFunctionInfo::getMinWavesPerEU () const inline
Returns
Default/requested minimum number of waves per execution unit.
Definition at line 1001 of file SIMachineFunctionInfo.h.
Referenced by llvm::GCNSchedStage::mayCauseSpilling().
getMode()
AMDGPU::SIModeRegisterDefaults llvm::SIMachineFunctionInfo::getMode () const inline
Definition at line 554 of file SIMachineFunctionInfo.h.
Referenced by llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeMinNumMaxNum(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), and llvm::AMDGPUTargetLowering::LowerUDIVREM64().
getNumPreloadedSGPRs()
unsigned llvm::SIMachineFunctionInfo::getNumPreloadedSGPRs () const inline
Definition at line 853 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::emitEntryFunctionPrologue(), and llvm::GCNSubtarget::getMaxNumSGPRs().
getNumSpilledSGPRs()
unsigned llvm::SIMachineFunctionInfo::getNumSpilledSGPRs () const inline
Definition at line 934 of file SIMachineFunctionInfo.h.
getNumSpilledVGPRs()
unsigned llvm::SIMachineFunctionInfo::getNumSpilledVGPRs () const inline
Definition at line 938 of file SIMachineFunctionInfo.h.
getNumUserSGPRs()
unsigned llvm::SIMachineFunctionInfo::getNumUserSGPRs () const inline
Definition at line 849 of file SIMachineFunctionInfo.h.
getOccupancy()
unsigned llvm::SIMachineFunctionInfo::getOccupancy () const inline
Definition at line 1031 of file SIMachineFunctionInfo.h.
Referenced by llvm::GCNSchedStrategy::initialize().
getOptionalScavengeFI()
std::optional<int> llvm::SIMachineFunctionInfo::getOptionalScavengeFI () const inline
Definition at line 668 of file SIMachineFunctionInfo.h.
Referenced by llvm::yaml::SIMachineFunctionInfo::SIMachineFunctionInfo().
getPreloadedReg()
MCRegister llvm::SIMachineFunctionInfo::getPreloadedReg (AMDGPUFunctionArgInfo::PreloadedValue Value) const inline
Definition at line 834 of file SIMachineFunctionInfo.h.
References Arg.
Referenced by llvm::SIFrameLowering::emitEntryFunctionPrologue().
getPreloadedValue()
std::tuple<const ArgDescriptor *, const TargetRegisterClass *, LLT> llvm::SIMachineFunctionInfo::getPreloadedValue (AMDGPUFunctionArgInfo::PreloadedValue Value) const inline
Definition at line 830 of file SIMachineFunctionInfo.h.
Referenced by llvm::AMDGPULegalizerInfo::legalizeWorkitemIDIntrinsic(), and llvm::AMDGPULegalizerInfo::loadInputValue().
getPrivateSegmentWaveByteOffsetSystemSGPR()
Register llvm::SIMachineFunctionInfo::getPrivateSegmentWaveByteOffsetSystemSGPR () const inline
Definition at line 857 of file SIMachineFunctionInfo.h.
getPrologEpilogSGPRSaveRestoreInfo()
const PrologEpilogSGPRSaveRestoreInfo& llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSaveRestoreInfo (Register Reg) const inline
Definition at line 615 of file SIMachineFunctionInfo.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by llvm::SIFrameLowering::emitPrologue().
getPrologEpilogSGPRSpills()
const PrologEpilogSGPRSpillsMap& llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSpills () const inline
Definition at line 570 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::emitCSRSpillRestores(), and llvm::SIFrameLowering::emitCSRSpillStores().
getPrologEpilogSGPRSpillToVGPRLanes()
ArrayRef<SIRegisterInfo::SpilledReg> llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSpillToVGPRLanes (int FrameIndex) const inline
Definition at line 623 of file SIMachineFunctionInfo.h.
References llvm::ArrayRef(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::ISD::FrameIndex, and I.
Referenced by getVGPRSpillLaneOrTempRegister().
getPSInputAddr()
unsigned llvm::SIMachineFunctionInfo::getPSInputAddr () const inline
Definition at line 950 of file SIMachineFunctionInfo.h.
getPSInputEnable()
unsigned llvm::SIMachineFunctionInfo::getPSInputEnable () const inline
Definition at line 954 of file SIMachineFunctionInfo.h.
getQueuePtrUserSGPR()
Register llvm::SIMachineFunctionInfo::getQueuePtrUserSGPR () const inline
Definition at line 894 of file SIMachineFunctionInfo.h.
getScavengeFI()
int SIMachineFunctionInfo::getScavengeFI (MachineFrameInfo & MFI, const SIRegisterInfo & TRI)
Definition at line 516 of file SIMachineFunctionInfo.cpp.
References llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetRegisterInfo::getSpillAlign(), llvm::TargetRegisterInfo::getSpillSize(), llvm::AMDGPUMachineFunction::isEntryFunction(), and TRI.
Referenced by llvm::SGPRSpillBuilder::prepare(), and llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
getScratchRSrcReg()
Register llvm::SIMachineFunctionInfo::getScratchRSrcReg () const inline
Returns the physical register reserved for use as the resource descriptor for scratch accesses.
Definition at line 863 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SIRegisterInfo::getReservedRegs(), and llvm::AMDGPUCallLowering::handleImplicitCallArguments().
getScratchSGPRCopyDstReg()
Register llvm::SIMachineFunctionInfo::getScratchSGPRCopyDstReg (Register Reg) const inline
Definition at line 586 of file SIMachineFunctionInfo.h.
References llvm::COPY_TO_SCRATCH_SGPR, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by llvm::SIFrameLowering::assignCalleeSavedSpillSlots(), llvm::SIFrameLowering::emitEpilogue(), and llvm::SIFrameLowering::emitPrologue().
getSGPRSpillToVGPRLanes()
ArrayRef<SIRegisterInfo::SpilledReg> llvm::SIMachineFunctionInfo::getSGPRSpillToVGPRLanes (int FrameIndex) const inline
Definition at line 559 of file SIMachineFunctionInfo.h.
References llvm::ArrayRef(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::ISD::FrameIndex, and I.
Referenced by llvm::SIRegisterInfo::restoreSGPR(), and llvm::SIRegisterInfo::spillSGPR().
getSGPRSpillVGPRs()
ArrayRef<Register> llvm::SIMachineFunctionInfo::getSGPRSpillVGPRs () const inline
Definition at line 566 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::getReservedRegs().
getStackPtrOffsetReg()
Register llvm::SIMachineFunctionInfo::getStackPtrOffsetReg () const inline
Definition at line 890 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::SIFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitPrologue(), llvm::SIRegisterInfo::getFrameRegister(), llvm::SIRegisterInfo::getReservedRegs(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::SIRegisterInfo::spillSGPR(), and llvm::SIInstrInfo::storeRegToStackSlot().
getVGPRForAGPRCopy()
Register llvm::SIMachineFunctionInfo::getVGPRForAGPRCopy () const inline
Definition at line 528 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SIRegisterInfo::getReservedRegs(), llvm::SIFrameLowering::processFunctionBeforeFrameIndicesReplaced(), and llvm::yaml::SIMachineFunctionInfo::SIMachineFunctionInfo().
getVGPRSpillAGPRs()
ArrayRef<MCPhysReg> llvm::SIMachineFunctionInfo::getVGPRSpillAGPRs () const inline
Definition at line 642 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::getReservedRegs(), and llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
getVGPRToAGPRSpill()
MCPhysReg llvm::SIMachineFunctionInfo::getVGPRToAGPRSpill (int FrameIndex, unsigned Lane) const inline
Definition at line 646 of file SIMachineFunctionInfo.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::ISD::FrameIndex, and I.
Referenced by spillVGPRtoAGPR().
getWavesPerEU()
std::pair<unsigned, unsigned> llvm::SIMachineFunctionInfo::getWavesPerEU () const inline
Returns
A pair of default/requested minimum/maximum number of waves per execution unit.
Definition at line 996 of file SIMachineFunctionInfo.h.
Referenced by llvm::GCNSubtarget::getMaxNumSGPRs(), and llvm::GCNSubtarget::getMaxNumVGPRs().
getWorkGroupIDSGPR()
Register llvm::SIMachineFunctionInfo::getWorkGroupIDSGPR (unsigned Dim) const inline
Returns
SGPR used for Dim's work group ID.
Definition at line 1011 of file SIMachineFunctionInfo.h.
References assert(), hasWorkGroupIDX(), hasWorkGroupIDY(), hasWorkGroupIDZ(), and llvm_unreachable.
getWWMReservedRegs()
const ReservedRegSet& llvm::SIMachineFunctionInfo::getWWMReservedRegs () const inline
Definition at line 568 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::getReservedRegs(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::yaml::SIMachineFunctionInfo::SIMachineFunctionInfo().
getWWMSpills()
const WWMSpillsMap& llvm::SIMachineFunctionInfo::getWWMSpills () const inline
Definition at line 567 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::determineCalleeSaves().
hasDispatchID()
bool llvm::SIMachineFunctionInfo::hasDispatchID () const inline
Definition at line 771 of file SIMachineFunctionInfo.h.
hasDispatchPtr()
bool llvm::SIMachineFunctionInfo::hasDispatchPtr () const inline
Definition at line 759 of file SIMachineFunctionInfo.h.
hasFlatScratchInit()
bool llvm::SIMachineFunctionInfo::hasFlatScratchInit () const inline
Definition at line 775 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::emitEntryFunctionPrologue(), and llvm::GCNSubtarget::getReservedNumSGPRs().
hasImplicitArgPtr()
bool llvm::SIMachineFunctionInfo::hasImplicitArgPtr () const inline
Definition at line 813 of file SIMachineFunctionInfo.h.
hasImplicitBufferPtr()
bool llvm::SIMachineFunctionInfo::hasImplicitBufferPtr () const inline
Definition at line 817 of file SIMachineFunctionInfo.h.
hasKernargSegmentPtr()
bool llvm::SIMachineFunctionInfo::hasKernargSegmentPtr () const inline
Definition at line 767 of file SIMachineFunctionInfo.h.
hasLDSKernelId()
bool llvm::SIMachineFunctionInfo::hasLDSKernelId () const inline
Definition at line 795 of file SIMachineFunctionInfo.h.
hasNonSpillStackObjects()
bool llvm::SIMachineFunctionInfo::hasNonSpillStackObjects () const inline
Definition at line 918 of file SIMachineFunctionInfo.h.
hasPrivateSegmentBuffer()
bool llvm::SIMachineFunctionInfo::hasPrivateSegmentBuffer () const inline
Definition at line 755 of file SIMachineFunctionInfo.h.
hasPrivateSegmentWaveByteOffset()
bool llvm::SIMachineFunctionInfo::hasPrivateSegmentWaveByteOffset () const inline
Definition at line 797 of file SIMachineFunctionInfo.h.
hasPrologEpilogSGPRSpillEntry()
bool llvm::SIMachineFunctionInfo::hasPrologEpilogSGPRSpillEntry (Register Reg) const inline
Definition at line 581 of file SIMachineFunctionInfo.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), llvm::SIFrameLowering::emitEpilogue(), and llvm::SIFrameLowering::emitPrologue().
hasQueuePtr()
bool llvm::SIMachineFunctionInfo::hasQueuePtr () const inline
Definition at line 763 of file SIMachineFunctionInfo.h.
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs().
hasSpilledSGPRs()
bool llvm::SIMachineFunctionInfo::hasSpilledSGPRs () const inline
Definition at line 902 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::determineCalleeSavesSGPR().
hasSpilledVGPRs()
bool llvm::SIMachineFunctionInfo::hasSpilledVGPRs () const inline
Definition at line 910 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
hasWorkGroupIDX()
bool llvm::SIMachineFunctionInfo::hasWorkGroupIDX () const inline
Definition at line 779 of file SIMachineFunctionInfo.h.
Referenced by getWorkGroupIDSGPR().
hasWorkGroupIDY()
bool llvm::SIMachineFunctionInfo::hasWorkGroupIDY () const inline
Definition at line 783 of file SIMachineFunctionInfo.h.
Referenced by getWorkGroupIDSGPR().
hasWorkGroupIDZ()
bool llvm::SIMachineFunctionInfo::hasWorkGroupIDZ () const inline
Definition at line 787 of file SIMachineFunctionInfo.h.
Referenced by addWorkGroupIDY(), and getWorkGroupIDSGPR().
hasWorkGroupInfo()
bool llvm::SIMachineFunctionInfo::hasWorkGroupInfo () const inline
Definition at line 791 of file SIMachineFunctionInfo.h.
hasWorkItemIDX()
bool llvm::SIMachineFunctionInfo::hasWorkItemIDX () const inline
Definition at line 801 of file SIMachineFunctionInfo.h.
hasWorkItemIDY()
bool llvm::SIMachineFunctionInfo::hasWorkItemIDY () const inline
Definition at line 805 of file SIMachineFunctionInfo.h.
hasWorkItemIDZ()
bool llvm::SIMachineFunctionInfo::hasWorkItemIDZ () const inline
Definition at line 809 of file SIMachineFunctionInfo.h.
increaseOccupancy()
void llvm::SIMachineFunctionInfo::increaseOccupancy (const MachineFunction & MF, unsigned Limit) inline
Definition at line 1048 of file SIMachineFunctionInfo.h.
References limitOccupancy().
Referenced by llvm::UnclusteredHighRPStage::initGCNSchedStage().
initializeBaseYamlFields()
bool SIMachineFunctionInfo::initializeBaseYamlFields (const yaml::SIMachineFunctionInfo & YamlMFI, const MachineFunction & MF, PerFunctionMIParsingState & PFS, SMDiagnostic & Error, SMRange & SourceRange)
Definition at line 656 of file SIMachineFunctionInfo.cpp.
References llvm::yaml::SIMachineFunctionInfo::BytesInStackArgArea, llvm::SourceMgr::DK_Error, llvm::yaml::SIMachineFunctionInfo::DynLDSAlign, llvm::yaml::SIMachineFunctionInfo::ExplicitKernArgSize, llvm::yaml::SIMachineFunctionInfo::GDSSize, llvm::MemoryBuffer::getBufferIdentifier(), llvm::MachineFunction::getFrameInfo(), llvm::SourceMgr::getMainFileID(), llvm::SourceMgr::getMemoryBuffer(), llvm::yaml::SIMachineFunctionInfo::HasSpilledSGPRs, llvm::yaml::SIMachineFunctionInfo::HasSpilledVGPRs, llvm::yaml::SIMachineFunctionInfo::HighBitsOf32BitAddress, llvm::yaml::SIMachineFunctionInfo::IsEntryFunction, llvm::yaml::SIMachineFunctionInfo::LDSSize, llvm::yaml::SIMachineFunctionInfo::MaxKernArgAlign, llvm::yaml::SIMachineFunctionInfo::MemoryBound, llvm::yaml::SIMachineFunctionInfo::NoSignedZerosFPMath, llvm::yaml::SIMachineFunctionInfo::Occupancy, llvm::yaml::SIMachineFunctionInfo::ReturnsVoid, llvm::yaml::SIMachineFunctionInfo::ScavengeFI, llvm::PerFunctionMIParsingState::SM, llvm::toString(), and llvm::yaml::SIMachineFunctionInfo::WaveLimiter.
Referenced by llvm::GCNTargetMachine::parseMachineFunctionInfo().
isCalleeSavedReg()
bool SIMachineFunctionInfo::isCalleeSavedReg (const MCPhysReg * CSRegs, MCPhysReg Reg) const
Definition at line 302 of file SIMachineFunctionInfo.cpp.
References I.
Referenced by splitWWMSpillRegisters().
isPSInputAllocated()
bool llvm::SIMachineFunctionInfo::isPSInputAllocated (unsigned Index) const inline
Definition at line 958 of file SIMachineFunctionInfo.h.
References Index.
isStackRealigned()
bool llvm::SIMachineFunctionInfo::isStackRealigned () const inline
Definition at line 926 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::emitEpilogue().
limitOccupancy() [1/2]
void SIMachineFunctionInfo::limitOccupancy (const MachineFunction & MF)
Definition at line 213 of file SIMachineFunctionInfo.cpp.
References llvm::MachineFunction::getFunction(), llvm::AMDGPUMachineFunction::getLDSSize(), getMaxWavesPerEU(), llvm::MachineFunction::getSubtarget(), and llvm::ARM_MB::ST.
Referenced by llvm::GCNSchedStage::checkScheduling(), and increaseOccupancy().
limitOccupancy() [2/2]
void llvm::SIMachineFunctionInfo::limitOccupancy (unsigned Limit) inline
Definition at line 1043 of file SIMachineFunctionInfo.h.
markPSInputAllocated()
void llvm::SIMachineFunctionInfo::markPSInputAllocated (unsigned Index) inline
Definition at line 962 of file SIMachineFunctionInfo.h.
References Index.
markPSInputEnabled()
void llvm::SIMachineFunctionInfo::markPSInputEnabled (unsigned Index) inline
Definition at line 966 of file SIMachineFunctionInfo.h.
References Index.
mayNeedAGPRs()
bool llvm::SIMachineFunctionInfo::mayNeedAGPRs () const inline
Definition at line 1054 of file SIMachineFunctionInfo.h.
mayUseAGPRs()
bool SIMachineFunctionInfo::mayUseAGPRs (const Function & F) const
Definition at line 695 of file SIMachineFunctionInfo.cpp.
References BB, Callee, F, I, llvm::AArch64PACKey::IA, and llvm::Intrinsic::not_intrinsic.
Referenced by SIMachineFunctionInfo().
removeDeadFrameIndices()
bool SIMachineFunctionInfo::removeDeadFrameIndices (MachineFrameInfo & MFI, bool ResetSGPRSpillStackIDs)
If ResetSGPRSpillStackIDs is true, reset the stack ID from sgpr-spill to the default stack.
Definition at line 480 of file SIMachineFunctionInfo.cpp.
References checkIndexInPrologEpilogSGPRSpills(), llvm::TargetStackID::Default, E, llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getStackID(), I, llvm::make_early_inc_range(), llvm::MachineFrameInfo::RemoveStackObject(), llvm::MachineFrameInfo::setStackID(), and llvm::TargetStackID::SGPRSpill.
Referenced by llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
reserveWWMRegister()
void llvm::SIMachineFunctionInfo::reserveWWMRegister (Register Reg) inline
Definition at line 552 of file SIMachineFunctionInfo.h.
References llvm::SetVector< T, Vector, Set >::insert().
Referenced by llvm::GCNTargetMachine::parseMachineFunctionInfo().
returnsVoid()
bool llvm::SIMachineFunctionInfo::returnsVoid () const inline
Definition at line 970 of file SIMachineFunctionInfo.h.
Referenced by llvm::AMDGPUCallLowering::lowerReturn().
setBytesInStackArgArea()
void llvm::SIMachineFunctionInfo::setBytesInStackArgArea (unsigned Bytes) inline
Definition at line 674 of file SIMachineFunctionInfo.h.
setFrameOffsetReg()
void llvm::SIMachineFunctionInfo::setFrameOffsetReg (Register Reg) inline
Definition at line 876 of file SIMachineFunctionInfo.h.
References assert().
setHasNonSpillStackObjects()
void llvm::SIMachineFunctionInfo::setHasNonSpillStackObjects (bool StackObject = true) inline
Definition at line 922 of file SIMachineFunctionInfo.h.
setHasSpilledSGPRs()
void llvm::SIMachineFunctionInfo::setHasSpilledSGPRs (bool Spill = true) inline
Definition at line 906 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIInstrInfo::loadRegFromStackSlot(), and llvm::SIInstrInfo::storeRegToStackSlot().
setHasSpilledVGPRs()
void llvm::SIMachineFunctionInfo::setHasSpilledVGPRs (bool Spill = true) inline
Definition at line 914 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIInstrInfo::storeRegToStackSlot().
setIfReturnsVoid()
void llvm::SIMachineFunctionInfo::setIfReturnsVoid (bool Value) inline
Definition at line 974 of file SIMachineFunctionInfo.h.
Referenced by llvm::AMDGPUCallLowering::lowerReturn().
setIsStackRealigned()
void llvm::SIMachineFunctionInfo::setIsStackRealigned (bool Realigned = true) inline
Definition at line 930 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::emitPrologue().
setPrivateSegmentWaveByteOffset()
void llvm::SIMachineFunctionInfo::setPrivateSegmentWaveByteOffset (Register Reg) inline
Definition at line 751 of file SIMachineFunctionInfo.h.
References llvm::ArgDescriptor::createRegister().
setScratchRSrcReg()
void llvm::SIMachineFunctionInfo::setScratchRSrcReg (Register Reg) inline
Definition at line 867 of file SIMachineFunctionInfo.h.
References assert().
setStackPtrOffsetReg()
void llvm::SIMachineFunctionInfo::setStackPtrOffsetReg (Register Reg) inline
Definition at line 881 of file SIMachineFunctionInfo.h.
References assert().
setVGPRForAGPRCopy()
void llvm::SIMachineFunctionInfo::setVGPRForAGPRCopy (Register NewVGPRForAGPRCopy) inline
Definition at line 532 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIFrameLowering::processFunctionBeforeFrameIndicesReplaced().
setVGPRToAGPRSpillDead()
void llvm::SIMachineFunctionInfo::setVGPRToAGPRSpillDead (int FrameIndex) inline
Definition at line 652 of file SIMachineFunctionInfo.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::ISD::FrameIndex, and I.
Referenced by llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
setWorkItemIDX()
void llvm::SIMachineFunctionInfo::setWorkItemIDX (ArgDescriptor Arg) inline
Definition at line 732 of file SIMachineFunctionInfo.h.
References Arg.
setWorkItemIDY()
void llvm::SIMachineFunctionInfo::setWorkItemIDY (ArgDescriptor Arg) inline
Definition at line 736 of file SIMachineFunctionInfo.h.
References Arg.
setWorkItemIDZ()
void llvm::SIMachineFunctionInfo::setWorkItemIDZ (ArgDescriptor Arg) inline
Definition at line 740 of file SIMachineFunctionInfo.h.
References Arg.
splitWWMSpillRegisters()
void SIMachineFunctionInfo::splitWWMSpillRegisters (MachineFunction & MF, SmallVectorImpl< std::pair< Register, int >> & CalleeSavedRegs, SmallVectorImpl< std::pair< Register, int >> & ScratchRegs) const
Definition at line 289 of file SIMachineFunctionInfo.cpp.
References llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getRegInfo(), and isCalleeSavedReg().
Referenced by llvm::SIFrameLowering::emitCSRSpillRestores(), and llvm::SIFrameLowering::emitCSRSpillStores().
usesAGPRs()
bool SIMachineFunctionInfo::usesAGPRs (const MachineFunction & MF) const
Definition at line 727 of file SIMachineFunctionInfo.cpp.
References E, llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::getType(), llvm::MachineFrameInfo::hasCalls(), I, llvm::Register::index2VirtReg(), llvm::SIRegisterInfo::isAGPRClass(), llvm::AMDGPU::isEntryFunctionCC(), llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::LLT::isValid(), MRI, and llvm::MachineRegisterInfo::use_empty().
Referenced by llvm::SIRegisterInfo::getReservedRegs().
Friends And Related Function Documentation
GCNTargetMachine
friend class GCNTargetMachine friend
Definition at line 359 of file SIMachineFunctionInfo.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SIMachineFunctionInfo.h
lib/Target/AMDGPU/SIMachineFunctionInfo.cpp