LLVM: llvm::orc::AllocGroup Class Reference
llvm::orc::AllocGroup Class Reference
A pair of memory protections and allocation policies.
#include "llvm/ExecutionEngine/Orc/Shared/MemoryFlags.h"
Public Member Functions
AllocGroup ()=default
Create a default AllocGroup.
AllocGroup (MemProt MP)
Create an AllocGroup from a MemProt only – uses MemoryDeallocationPolicy::Standard.
AllocGroup (MemProt MP, MemDeallocPolicy MDP)
Create an AllocGroup from a MemProt and a MemoryDeallocationPolicy.
MemProt getMemProt () const
Returns the MemProt for this group.
MemDeallocPolicy getMemDeallocPolicy () const
Returns the MemoryDeallocationPolicy for this group.
Static Public Attributes
static constexpr unsigned NumGroups = MaxIdentifiers
Friends
struct llvm::DenseMapInfo< AllocGroup >
bool operator== (const AllocGroup &LHS, const AllocGroup &RHS)
bool operator!= (const AllocGroup &LHS, const AllocGroup &RHS)
bool operator< (const AllocGroup &LHS, const AllocGroup &RHS)
Detailed Description
A pair of memory protections and allocation policies.
Optimized for use as a small map key.
Definition at line 93 of file MemoryFlags.h.
Constructor & Destructor Documentation
AllocGroup() [1/3]
llvm::orc::AllocGroup::AllocGroup () default
Create a default AllocGroup.
No memory protections, standard deallocation policy.
AllocGroup() [2/3]
llvm::orc::AllocGroup::AllocGroup (MemProt MP) inline
Create an AllocGroup from a MemProt only – uses MemoryDeallocationPolicy::Standard.
Definition at line 111 of file MemoryFlags.h.
AllocGroup() [3/3]
llvm::orc::AllocGroup::AllocGroup (MemProt MP, MemDeallocPolicy MDP) inline
Create an AllocGroup from a MemProt and a MemoryDeallocationPolicy.
Definition at line 114 of file MemoryFlags.h.
Member Function Documentation
getMemDeallocPolicy()
MemDeallocPolicy llvm::orc::AllocGroup::getMemDeallocPolicy () const inline
Returns the MemoryDeallocationPolicy for this group.
Definition at line 124 of file MemoryFlags.h.
Referenced by llvm::orc::operator<<(), and llvm::orc::shared::SPSSerializationTraits< SPSAllocGroup, AllocGroup >::serialize().
getMemProt()
MemProt llvm::orc::AllocGroup::getMemProt () const inline
Returns the MemProt for this group.
Definition at line 119 of file MemoryFlags.h.
Referenced by llvm::orc::operator<<(), and llvm::orc::shared::SPSSerializationTraits< SPSAllocGroup, AllocGroup >::serialize().
Friends And Related Function Documentation
llvm::DenseMapInfo< AllocGroup >
friend struct llvm::DenseMapInfo< AllocGroup > friend
Definition at line 94 of file MemoryFlags.h.
operator!=
bool operator!= (const AllocGroup & LHS, const AllocGroup & RHS) friend
Definition at line 132 of file MemoryFlags.h.
operator<
bool operator< (const AllocGroup & LHS, const AllocGroup & RHS) friend
Definition at line 136 of file MemoryFlags.h.
operator==
bool operator== (const AllocGroup & LHS, const AllocGroup & RHS) friend
Definition at line 128 of file MemoryFlags.h.
Member Data Documentation
NumGroups
constexpr unsigned llvm::orc::AllocGroup::NumGroups = MaxIdentifiers static constexpr
Definition at line 103 of file MemoryFlags.h.
Referenced by llvm::jitlink::SimpleSegmentAlloc::Create().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/MemoryFlags.h