LLVM: llvm::MCAsmBackend Class Reference
llvm::MCAsmBackend Class Reference abstract
Generic interface to target specific assembler backends.
#include "llvm/MC/MCAsmBackend.h"
Public Member Functions
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void emitInstructionBegin (MCObjectStreamer &OS, const MCInst &Inst, const MCSubtargetInfo &STI)
Give the target a chance to manipulate state related to instruction alignment (e.g.
virtual void emitInstructionEnd (MCObjectStreamer &OS, const MCInst &Inst)
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const =0
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const =0
Write an (optimal) nop sequence of Count bytes to the given output.
virtual void finishLayout (MCAssembler const &Asm, MCAsmLayout &Layout) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint32_t generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction >) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool isMicroMips (const MCSymbol *Sym) const
Check whether a given symbol has been flagged with MICROMIPS flag.
Target Fixup Interfaces
virtual unsigned getNumFixupKinds () const =0
Get the number of target specific fixup kinds.
virtual std::optional< MCFixupKind > getFixupKind (StringRef Name) const
Map a relocation name used in .reloc to a fixup kind.
virtual const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const
Get information on a fixup kind.
virtual bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target)
Hook to check if a relocation is needed for some target specific reason.
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, const MCAsmLayout &Layout, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual bool evaluateTargetFixup (const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFixup &Fixup, const MCFragment *DF, const MCValue &Target, uint64_t &Value, bool &WasForced)
virtual void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const =0
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Target Relaxation Interfaces
virtual bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const
Check whether the given instruction may need relaxation.
virtual bool fixupNeedsRelaxationAdvanced (const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout, const bool WasForced) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
virtual bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout) const =0
Simple predicate for targets where !Resolved implies requiring relaxation.
virtual void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const
Relax the instruction in the given fragment to the next wider instruction.
virtual bool relaxDwarfLineAddr (MCDwarfLineAddrFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const
virtual bool relaxDwarfCFA (MCDwarfCallFrameFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const
Public Attributes
const support::endianness Endian
Protected Member Functions
MCAsmBackend (support::endianness Endian)
Detailed Description
Generic interface to target specific assembler backends.
Definition at line 41 of file MCAsmBackend.h.
Constructor & Destructor Documentation
MCAsmBackend() [1/2]
MCAsmBackend::MCAsmBackend (support::endianness Endian) protected
Definition at line 25 of file MCAsmBackend.cpp.
MCAsmBackend() [2/2]
llvm::MCAsmBackend::MCAsmBackend (const MCAsmBackend &) delete
~MCAsmBackend()
MCAsmBackend::~MCAsmBackend () virtual default
Member Function Documentation
allowAutoPadding()
virtual bool llvm::MCAsmBackend::allowAutoPadding () const inline virtual
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
Definition at line 54 of file MCAsmBackend.h.
allowEnhancedRelaxation()
virtual bool llvm::MCAsmBackend::allowEnhancedRelaxation () const inline virtual
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
Definition at line 58 of file MCAsmBackend.h.
applyFixup()
virtual void llvm::MCAsmBackend::applyFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo * STI) const pure virtual
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Errors (such as an out of range fixup value) should be reported via Ctx. The STI is present only for fragments of type MCRelaxableFragment and MCDataFragment with hasInstructions() == true.
Implemented in llvm::RISCVAsmBackend, llvm::ARMAsmBackend, llvm::MipsAsmBackend, llvm::AVRAsmBackend, llvm::XtensaMCAsmBackend, llvm::LoongArchAsmBackend, and llvm::CSKYAsmBackend.
Referenced by llvm::MCAssembler::layout().
createDwoObjectWriter()
std::unique_ptr< MCObjectWriter > MCAsmBackend::createDwoObjectWriter (raw_pwrite_stream & OS, raw_pwrite_stream & DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
This function is only supported with ELF targets.
Definition at line 60 of file MCAsmBackend.cpp.
References llvm::createELFDwoObjectWriter(), createObjectTargetWriter(), llvm::createWasmDwoObjectWriter(), llvm::Triple::ELF, Endian, llvm::support::little, move, OS, llvm::report_fatal_error(), and llvm::Triple::Wasm.
Referenced by llvm::LLVMTargetMachine::createMCStreamer().
createObjectTargetWriter()
virtual std::unique_ptr<MCObjectTargetWriter> llvm::MCAsmBackend::createObjectTargetWriter () const pure virtual
Implemented in llvm::LoongArchAsmBackend, llvm::RISCVAsmBackend, llvm::CSKYAsmBackend, llvm::XtensaMCAsmBackend, llvm::MipsAsmBackend, llvm::AVRAsmBackend, and llvm::ARMAsmBackendDarwin.
Referenced by createDwoObjectWriter(), and createObjectWriter().
createObjectWriter()
std::unique_ptr< MCObjectWriter > MCAsmBackend::createObjectWriter (raw_pwrite_stream & OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
Definition at line 30 of file MCAsmBackend.cpp.
References llvm::Triple::COFF, llvm::createDXContainerObjectWriter(), llvm::createELFObjectWriter(), llvm::createMachObjectWriter(), createObjectTargetWriter(), llvm::createSPIRVObjectWriter(), llvm::createWasmObjectWriter(), llvm::createWinCOFFObjectWriter(), llvm::createXCOFFObjectWriter(), llvm::Triple::DXContainer, llvm::Triple::ELF, Endian, llvm::support::little, llvm_unreachable, llvm::Triple::MachO, move, OS, llvm::Triple::SPIRV, llvm::Triple::Wasm, and llvm::Triple::XCOFF.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::LLVMTargetMachine::createMCStreamer(), and llvm::DwarfStreamer::init().
emitInstructionBegin()
virtual void llvm::MCAsmBackend::emitInstructionBegin (MCObjectStreamer & OS, const MCInst & Inst, const MCSubtargetInfo & STI) inline virtual
Give the target a chance to manipulate state related to instruction alignment (e.g.
padding for optimization), instruction relaxablility, etc. before and after actually emitting the instruction.
Definition at line 63 of file MCAsmBackend.h.
Referenced by llvm::MCObjectStreamer::emitInstruction().
emitInstructionEnd()
virtual void llvm::MCAsmBackend::emitInstructionEnd (MCObjectStreamer & OS, const MCInst & Inst) inline virtual
Definition at line 65 of file MCAsmBackend.h.
Referenced by llvm::MCObjectStreamer::emitInstruction().
evaluateTargetFixup()
virtual bool llvm::MCAsmBackend::evaluateTargetFixup (const MCAssembler & Asm, const MCAsmLayout & Layout, const MCFixup & Fixup, const MCFragment * DF, const MCValue & Target, uint64_t & Value, bool & WasForced) inline virtual
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 119 of file MCAsmBackend.h.
References llvm_unreachable.
finishLayout()
virtual void llvm::MCAsmBackend::finishLayout (MCAssembler const & Asm, MCAsmLayout & Layout) const inline virtual
Give backend an opportunity to finish layout after relaxation.
Definition at line 206 of file MCAsmBackend.h.
fixupNeedsRelaxation()
virtual bool llvm::MCAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout) const pure virtual
Simple predicate for targets where !Resolved implies requiring relaxation.
Implemented in llvm::XtensaMCAsmBackend, llvm::RISCVAsmBackend, llvm::ARMAsmBackend, llvm::MipsAsmBackend, llvm::AVRAsmBackend, llvm::LoongArchAsmBackend, and llvm::CSKYAsmBackend.
Referenced by fixupNeedsRelaxationAdvanced().
fixupNeedsRelaxationAdvanced()
bool MCAsmBackend::fixupNeedsRelaxationAdvanced (const MCFixup & Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout, const bool WasForced) const virtual
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Reimplemented in llvm::RISCVAsmBackend, and llvm::CSKYAsmBackend.
Definition at line 110 of file MCAsmBackend.cpp.
References DF, Fixup, and fixupNeedsRelaxation().
generateCompactUnwindEncoding()
virtual uint32_t llvm::MCAsmBackend::generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction >) const inline virtual
Generate the compact unwind encoding for the CFI instructions.
Reimplemented in llvm::ARMAsmBackendDarwin.
Definition at line 214 of file MCAsmBackend.h.
Referenced by llvm::MCStreamer::generateCompactUnwindEncodings().
getFixupKind()
std::optional< MCFixupKind > MCAsmBackend::getFixupKind (StringRef Name) const virtual
Map a relocation name used in .reloc to a fixup kind.
Reimplemented in llvm::RISCVAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, llvm::AVRAsmBackend, and llvm::ARMAsmBackend.
Definition at line 76 of file MCAsmBackend.cpp.
Referenced by llvm::MCObjectStreamer::emitRelocDirective(), and llvm::MipsAsmBackend::getFixupKind().
getFixupKindInfo()
const MCFixupKindInfo & MCAsmBackend::getFixupKindInfo (MCFixupKind Kind) const virtual
Get information on a fixup kind.
Reimplemented in llvm::RISCVAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, llvm::AVRAsmBackend, llvm::XtensaMCAsmBackend, llvm::ARMAsmBackend, and llvm::CSKYAsmBackend.
Definition at line 80 of file MCAsmBackend.cpp.
References assert(), llvm::MCFixupKindInfo::FKF_IsPCRel, and size.
Referenced by llvm::CSKYAsmBackend::getFixupKindInfo(), llvm::ARMAsmBackend::getFixupKindInfo(), llvm::XtensaMCAsmBackend::getFixupKindInfo(), llvm::AVRAsmBackend::getFixupKindInfo(), llvm::MipsAsmBackend::getFixupKindInfo(), llvm::LoongArchAsmBackend::getFixupKindInfo(), and llvm::RISCVAsmBackend::getFixupKindInfo().
getMaximumNopSize()
virtual unsigned llvm::MCAsmBackend::getMaximumNopSize (const MCSubtargetInfo & STI) const inline virtual
Returns the maximum size of a nop in bytes on this target.
Definition at line 194 of file MCAsmBackend.h.
getMinimumNopSize()
virtual unsigned llvm::MCAsmBackend::getMinimumNopSize () const inline virtual
Returns the minimum size of a nop in bytes on this target.
The assembler will use this to emit excess padding in situations where the padding required for simple alignment would be less than the minimum nop size.
Definition at line 190 of file MCAsmBackend.h.
getNumFixupKinds()
virtual unsigned llvm::MCAsmBackend::getNumFixupKinds () const pure virtual
Get the number of target specific fixup kinds.
Implemented in llvm::RISCVAsmBackend, llvm::LoongArchAsmBackend, llvm::MipsAsmBackend, llvm::AVRAsmBackend, llvm::XtensaMCAsmBackend, llvm::ARMAsmBackend, and llvm::CSKYAsmBackend.
handleAssemblerFlag()
virtual void llvm::MCAsmBackend::handleAssemblerFlag (MCAssemblerFlag Flag) inline virtual
Handle any target-specific assembler flags. By default, do nothing.
Reimplemented in llvm::ARMAsmBackend.
Definition at line 210 of file MCAsmBackend.h.
Referenced by llvm::MCWinCOFFStreamer::emitAssemblerFlag(), llvm::MCWasmStreamer::emitAssemblerFlag(), and llvm::MCELFStreamer::emitAssemblerFlag().
isMicroMips()
virtual bool llvm::MCAsmBackend::isMicroMips (const MCSymbol * Sym) const inline virtual
Check whether a given symbol has been flagged with MICROMIPS flag.
Reimplemented in llvm::MipsAsmBackend.
Definition at line 219 of file MCAsmBackend.h.
mayNeedRelaxation()
virtual bool llvm::MCAsmBackend::mayNeedRelaxation (const MCInst & Inst, const MCSubtargetInfo & STI) const inline virtual
Check whether the given instruction may need relaxation.
Parameters
Inst - The instruction to test.
STI - The MCSubtargetInfo in effect when the instruction was encoded.
Reimplemented in llvm::RISCVAsmBackend, llvm::ARMAsmBackend, llvm::CSKYAsmBackend, and llvm::XtensaMCAsmBackend.
Definition at line 148 of file MCAsmBackend.h.
operator=()
MCAsmBackend& llvm::MCAsmBackend::operator= (const MCAsmBackend &) delete
relaxDwarfCFA()
virtual bool llvm::MCAsmBackend::relaxDwarfCFA (MCDwarfCallFrameFragment & DF, MCAsmLayout & Layout, bool & WasRelaxed) const inline virtual
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 179 of file MCAsmBackend.h.
relaxDwarfLineAddr()
virtual bool llvm::MCAsmBackend::relaxDwarfLineAddr (MCDwarfLineAddrFragment & DF, MCAsmLayout & Layout, bool & WasRelaxed) const inline virtual
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 174 of file MCAsmBackend.h.
relaxInstruction()
virtual void llvm::MCAsmBackend::relaxInstruction (MCInst & Inst, const MCSubtargetInfo & STI) const inline virtual
Relax the instruction in the given fragment to the next wider instruction.
Parameters
[out] Inst The instruction to relax, which is also the relaxed instruction.
STI the subtarget information for the associated instruction.
Reimplemented in llvm::RISCVAsmBackend, llvm::ARMAsmBackend, llvm::LoongArchAsmBackend, llvm::XtensaMCAsmBackend, and llvm::CSKYAsmBackend.
Definition at line 171 of file MCAsmBackend.h.
reset()
virtual void llvm::MCAsmBackend::reset () inline virtual
lifetime management
Definition at line 68 of file MCAsmBackend.h.
Referenced by llvm::MCAssembler::reset().
shouldForceRelocation()
virtual bool llvm::MCAsmBackend::shouldForceRelocation (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target) inline virtual
Hook to check if a relocation is needed for some target specific reason.
Reimplemented in llvm::MipsAsmBackend, llvm::RISCVAsmBackend, llvm::AVRAsmBackend, llvm::CSKYAsmBackend, llvm::LoongArchAsmBackend, and llvm::ARMAsmBackend.
Definition at line 97 of file MCAsmBackend.h.
shouldInsertExtraNopBytesForCodeAlign()
virtual bool llvm::MCAsmBackend::shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment & AF, unsigned & Size) inline virtual
Hook to check if extra nop bytes must be inserted for alignment directive.
For some targets this may be necessary in order to support linker relaxation. The number of bytes to insert are returned in Size.
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 106 of file MCAsmBackend.h.
shouldInsertFixupForCodeAlign()
virtual bool llvm::MCAsmBackend::shouldInsertFixupForCodeAlign (MCAssembler & Asm, const MCAsmLayout & Layout, MCAlignFragment & AF) inline virtual
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
Reimplemented in llvm::RISCVAsmBackend.
Definition at line 113 of file MCAsmBackend.h.
Referenced by llvm::MCAssembler::layout().
writeNopData()
virtual bool llvm::MCAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const pure virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implemented in llvm::RISCVAsmBackend, llvm::ARMAsmBackend, llvm::MipsAsmBackend, llvm::LoongArchAsmBackend, llvm::AVRAsmBackend, llvm::CSKYAsmBackend, and llvm::XtensaMCAsmBackend.
Member Data Documentation
Endian
const support::endianness llvm::MCAsmBackend::Endian
Definition at line 50 of file MCAsmBackend.h.
Referenced by llvm::ARMAsmBackend::adjustFixupValue(), llvm::CSKYAsmBackend::applyFixup(), llvm::MipsAsmBackend::applyFixup(), llvm::ARMAsmBackend::applyFixup(), createDwoObjectWriter(), createObjectWriter(), llvm::ARMAsmBackend::getFixupKindInfo(), llvm::MipsAsmBackend::getFixupKindInfo(), and llvm::ARMAsmBackend::writeNopData().
The documentation for this class was generated from the following files:
include/llvm/MC/MCAsmBackend.h
lib/MC/MCAsmBackend.cpp