LLVM: llvm::jitlink::DWARFRecordSectionSplitter Class Reference
llvm::jitlink::DWARFRecordSectionSplitter Class Reference
A LinkGraph pass that splits blocks in a section that follows the DWARF Record format into sub-blocks where each header gets its own block.
#include "llvm/ExecutionEngine/JITLink/DWARFRecordSectionSplitter.h"
Public Member Functions
DWARFRecordSectionSplitter (StringRef SectionName)
Error operator() (LinkGraph &G)
Detailed Description
A LinkGraph pass that splits blocks in a section that follows the DWARF Record format into sub-blocks where each header gets its own block.
When splitting EHFrames, DWARFRecordSectionSplitter should not be run without EHFrameEdgeFixer, which is responsible for adding FDE-to-CIE edges.
Definition at line 21 of file DWARFRecordSectionSplitter.h.
Constructor & Destructor Documentation
DWARFRecordSectionSplitter()
llvm::jitlink::DWARFRecordSectionSplitter::DWARFRecordSectionSplitter (StringRef SectionName)
Definition at line 17 of file DWARFRecordSectionSplitter.cpp.
Member Function Documentation
operator()()
Error llvm::jitlink::DWARFRecordSectionSplitter::operator() (LinkGraph & G)
Definition at line 20 of file DWARFRecordSectionSplitter.cpp.
References B, llvm::jitlink::Section::blocks(), llvm::dbgs(), G, LHS, LLVM_DEBUG, RHS, llvm::sort(), llvm::Error::success(), and llvm::jitlink::Section::symbols().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/DWARFRecordSectionSplitter.h
lib/ExecutionEngine/JITLink/DWARFRecordSectionSplitter.cpp