LLVM: llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > > Class Template Reference
llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
Static Public Member Functions
static Expected< T > makeValue ()
static void makeSafe (Expected< T > &E)
static Error deserialize (Expected< T > &E, const char *ArgData, size_t ArgSize)
Detailed Description
template<typename SPSTagT, typename T>
class llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >
Definition at line 410 of file WrapperFunctionUtils.h.
Member Function Documentation
deserialize()
template<typename SPSTagT , typename T > static Error llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::deserialize (Expected< T > & E, const char * ArgData, size_t ArgSize) inline static
Definition at line 415 of file WrapperFunctionUtils.h.
References llvm::orc::shared::detail::ResultDeserializer< SPSRetTagT, RetT >::deserialize(), E, llvm::orc::shared::detail::fromSPSSerializable(), llvm::AArch64PACKey::IB, llvm::inconvertibleErrorCode(), move, and llvm::Error::success().
makeSafe()
template<typename SPSTagT , typename T > static void llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::makeSafe (Expected< T > & E) inline static
Definition at line 413 of file WrapperFunctionUtils.h.
References llvm::cantFail(), and E.
makeValue()
template<typename SPSTagT , typename T > static Expected<T> llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::makeValue () inline static
Definition at line 412 of file WrapperFunctionUtils.h.
References T.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h