LLVM: llvm::SPIRVMCInstLower Class Reference
llvm::SPIRVMCInstLower Class Reference
#include "Target/SPIRV/SPIRVMCInstLower.h"
Public Member Functions
void lower (const MachineInstr *MI, MCInst &OutMI, SPIRV::ModuleAnalysisInfo *MAI) const
Detailed Description
Definition at line 22 of file SPIRVMCInstLower.h.
Member Function Documentation
lower()
void SPIRVMCInstLower::lower (const MachineInstr * MI, MCInst & OutMI, SPIRV::ModuleAnalysisInfo * MAI) const
Definition at line 23 of file SPIRVMCInstLower.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::APFloat::convertToFloat(), llvm::MCOperand::createDFPImm(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::numbers::e, llvm::SPIRV::ModuleAnalysisInfo::getExtInstSetReg(), llvm::MachineOperand::getFPImm(), llvm::SPIRV::ModuleAnalysisInfo::getFuncReg(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::SPIRV::ModuleAnalysisInfo::getOrCreateMBBRegister(), llvm::MachineOperand::getReg(), llvm::SPIRV::ModuleAnalysisInfo::getRegisterAlias(), llvm::MachineOperand::getType(), llvm::ConstantFP::getValueAPF(), i, llvm::Register::isValid(), llvm_unreachable, MI, llvm::MachineOperand::MO_FPImmediate, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, and llvm::MCInst::setOpcode().
The documentation for this class was generated from the following files:
lib/Target/SPIRV/SPIRVMCInstLower.h
lib/Target/SPIRV/SPIRVMCInstLower.cpp