LLVM: llvm::orc::ResourceTracker Class Reference
llvm::orc::ResourceTracker Class Reference
API to remove / transfer ownership of JIT resources.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
ResourceTracker (const ResourceTracker &)=delete
ResourceTracker & operator= (const ResourceTracker &)=delete
ResourceTracker (ResourceTracker &&)=delete
ResourceTracker & operator= (ResourceTracker &&)=delete
~ResourceTracker ()
JITDylib & getJITDylib () const
Return the JITDylib targeted by this tracker.
template<typename Func >
Error withResourceKeyDo (Func &&F)
Runs the given callback under the session lock, passing in the associated ResourceKey.
Error remove ()
Remove all resources associated with this key.
void transferTo (ResourceTracker &DstRT)
Transfer all resources associated with this key to the given tracker, which must target the same JITDylib as this one.
bool isDefunct () const
Return true if this tracker has become defunct.
ResourceKey getKeyUnsafe () const
Returns the key associated with this tracker.
Public Member Functions inherited from llvm::ThreadSafeRefCountedBase< ResourceTracker >
void Retain () const
void Release () const
Friends
class ExecutionSession
class JITDylib
class MaterializationResponsibility
Additional Inherited Members
Protected Member Functions inherited from llvm::ThreadSafeRefCountedBase< ResourceTracker >
ThreadSafeRefCountedBase ()=default
ThreadSafeRefCountedBase (const ThreadSafeRefCountedBase &)
ThreadSafeRefCountedBase & operator= (const ThreadSafeRefCountedBase &)=delete
~ThreadSafeRefCountedBase ()
Detailed Description
API to remove / transfer ownership of JIT resources.
Definition at line 53 of file Core.h.
Constructor & Destructor Documentation
ResourceTracker() [1/2]
llvm::orc::ResourceTracker::ResourceTracker (const ResourceTracker &) delete
ResourceTracker() [2/2]
llvm::orc::ResourceTracker::ResourceTracker (ResourceTracker &&) delete
~ResourceTracker()
llvm::orc::ResourceTracker::~ResourceTracker ()
Definition at line 47 of file Core.cpp.
References llvm::orc::JITDylib::getExecutionSession(), getJITDylib(), and llvm::ThreadSafeRefCountedBase< Derived >::Release().
Member Function Documentation
getJITDylib()
JITDylib& llvm::orc::ResourceTracker::getJITDylib () const inline
Return the JITDylib targeted by this tracker.
Definition at line 68 of file Core.h.
Referenced by llvm::orc::COFFPlatform::notifyAdding(), llvm::orc::MachOPlatform::notifyAdding(), llvm::orc::ELFNixPlatform::notifyAdding(), remove(), transferTo(), withResourceKeyDo(), and ~ResourceTracker().
getKeyUnsafe()
ResourceKey llvm::orc::ResourceTracker::getKeyUnsafe () const inline
Returns the key associated with this tracker.
This method should not be used except for debug logging: there is no guarantee that the returned value will remain valid.
Definition at line 90 of file Core.h.
Referenced by withResourceKeyDo().
isDefunct()
bool llvm::orc::ResourceTracker::isDefunct () const inline
Return true if this tracker has become defunct.
Definition at line 85 of file Core.h.
Referenced by withResourceKeyDo().
operator=() [1/2]
ResourceTracker& llvm::orc::ResourceTracker::operator= (const ResourceTracker &) delete
operator=() [2/2]
ResourceTracker& llvm::orc::ResourceTracker::operator= (ResourceTracker &&) delete
remove()
Error llvm::orc::ResourceTracker::remove ()
Remove all resources associated with this key.
Definition at line 52 of file Core.cpp.
References llvm::orc::JITDylib::getExecutionSession(), and getJITDylib().
transferTo()
void llvm::orc::ResourceTracker::transferTo (ResourceTracker & DstRT)
Transfer all resources associated with this key to the given tracker, which must target the same JITDylib as this one.
Definition at line 56 of file Core.cpp.
References llvm::orc::JITDylib::getExecutionSession(), and getJITDylib().
withResourceKeyDo()
template<typename Func > Error llvm::orc::ResourceTracker::withResourceKeyDo (Func && F)
Runs the given callback under the session lock, passing in the associated ResourceKey.
This is the safe way to associate resources with trackers.
Definition at line 1781 of file Core.h.
References F, llvm::orc::JITDylib::getExecutionSession(), getJITDylib(), getKeyUnsafe(), isDefunct(), llvm::orc::ExecutionSession::runSessionLocked(), and llvm::Error::success().
Friends And Related Function Documentation
ExecutionSession
friend class ExecutionSession friend
Definition at line 55 of file Core.h.
JITDylib
friend class JITDylib friend
Definition at line 56 of file Core.h.
MaterializationResponsibility
friend class MaterializationResponsibility friend
Definition at line 57 of file Core.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp