LLVM: llvm::LoopFullUnrollPass Class Reference
llvm::LoopFullUnrollPass Class Reference
Loop unroll pass that only does full loop unrolling and peeling.
#include "llvm/Transforms/Scalar/LoopUnrollPass.h"
Public Member Functions
LoopFullUnrollPass (int OptLevel=2, bool OnlyWhenForced=false, bool ForgetSCEV=false)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Public Member Functions inherited from llvm::PassInfoMixin< LoopFullUnrollPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopFullUnrollPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Loop unroll pass that only does full loop unrolling and peeling.
Definition at line 26 of file LoopUnrollPass.h.
Constructor & Destructor Documentation
LoopFullUnrollPass()
llvm::LoopFullUnrollPass::LoopFullUnrollPass (int OptLevel = 2, bool OnlyWhenForced = false, bool ForgetSCEV = false) inline explicit
Definition at line 40 of file LoopUnrollPass.h.
Member Function Documentation
run()
PreservedAnalyses LoopFullUnrollPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 1478 of file LoopUnrollPass.cpp.
References llvm::LoopStandardAnalysisResults::AC, llvm::LPMUpdater::addChildLoops(), llvm::LPMUpdater::addSiblingLoops(), llvm::PreservedAnalyses::all(), llvm::SmallVectorImpl< T >::append(), llvm::LoopBase< BlockT, LoopT >::begin(), llvm::LoopInfoBase< BlockT, LoopT >::begin(), llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::LoopStandardAnalysisResults::DT, llvm::LoopBase< BlockT, LoopT >::end(), llvm::LoopInfoBase< BlockT, LoopT >::end(), llvm::erase_if(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getLoopPassPreservedAnalyses(), llvm::Loop::getName(), llvm::BasicBlock::getParent(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::LoopStandardAnalysisResults::LI, llvm::LPMUpdater::markLoopAsDeleted(), llvm::LoopStandardAnalysisResults::SE, tryToUnrollLoop(), llvm::LoopStandardAnalysisResults::TTI, llvm::Unmodified, UnrollRevisitChildLoops, and llvm::LoopBase< BlockT, LoopT >::verifyLoop().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopUnrollPass.h
lib/Transforms/Scalar/LoopUnrollPass.cpp