LLVM: llvm::object::ExportDirectoryEntryRef Class Reference
llvm::object::ExportDirectoryEntryRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
ExportDirectoryEntryRef ()=default
ExportDirectoryEntryRef (const export_directory_table_entry *Table, uint32_t I, const COFFObjectFile *Owner)
bool operator== (const ExportDirectoryEntryRef &Other) const
void moveNext ()
Error getDllName (StringRef &Result) const
Error getOrdinalBase (uint32_t &Result) const
Error getOrdinal (uint32_t &Result) const
Error getExportRVA (uint32_t &Result) const
Error getSymbolName (StringRef &Result) const
Error isForwarder (bool &Result) const
Error getForwardTo (StringRef &Result) const
Detailed Description
Definition at line 1170 of file COFF.h.
Constructor & Destructor Documentation
ExportDirectoryEntryRef() [1/2]
llvm::object::ExportDirectoryEntryRef::ExportDirectoryEntryRef () default
ExportDirectoryEntryRef() [2/2]
llvm::object::ExportDirectoryEntryRef::ExportDirectoryEntryRef (const export_directory_table_entry * Table, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 1173 of file COFF.h.
Member Function Documentation
getDllName()
Error ExportDirectoryEntryRef::getDllName (StringRef & Result) const
Definition at line 1560 of file COFFObjectFile.cpp.
References E, llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::export_directory_table_entry::NameRVA, and llvm::Error::success().
getExportRVA()
Error ExportDirectoryEntryRef::getExportRVA (uint32_t & Result) const
Definition at line 1582 of file COFFObjectFile.cpp.
References entry, llvm::object::export_directory_table_entry::ExportAddressTableRVA, llvm::object::COFFObjectFile::getRvaPtr(), and llvm::Error::success().
Referenced by getForwardTo(), and isForwarder().
getForwardTo()
Error ExportDirectoryEntryRef::getForwardTo (StringRef & Result) const
Definition at line 1638 of file COFFObjectFile.cpp.
References getExportRVA(), llvm::object::COFFObjectFile::getRvaPtr(), and llvm::Error::success().
getOrdinal()
Error ExportDirectoryEntryRef::getOrdinal (uint32_t & Result) const
Definition at line 1576 of file COFFObjectFile.cpp.
References llvm::object::export_directory_table_entry::OrdinalBase, and llvm::Error::success().
getOrdinalBase()
Error ExportDirectoryEntryRef::getOrdinalBase (uint32_t & Result) const
Definition at line 1570 of file COFFObjectFile.cpp.
References llvm::object::export_directory_table_entry::OrdinalBase, and llvm::Error::success().
getSymbolName()
Error ExportDirectoryEntryRef::getSymbolName (StringRef & Result) const
Definition at line 1596 of file COFFObjectFile.cpp.
References E, llvm::object::COFFObjectFile::getRvaPtr(), I, llvm::object::export_directory_table_entry::NamePointerRVA, llvm::object::export_directory_table_entry::NumberOfNamePointers, llvm::object::export_directory_table_entry::OrdinalTableRVA, and llvm::Error::success().
isForwarder()
Error ExportDirectoryEntryRef::isForwarder (bool & Result) const
Definition at line 1623 of file COFFObjectFile.cpp.
References llvm::createStringError(), llvm::COFF::EXPORT_TABLE, llvm::object::COFFObjectFile::getDataDirectory(), getExportRVA(), llvm::object::parse_failed, and llvm::object::data_directory::RelativeVirtualAddress.
moveNext()
void ExportDirectoryEntryRef::moveNext ()
Definition at line 1554 of file COFFObjectFile.cpp.
operator==()
bool ExportDirectoryEntryRef::operator== (const ExportDirectoryEntryRef & Other) const
Definition at line 1550 of file COFFObjectFile.cpp.
References Other.
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp