LLVM: BoUpSLP::ShuffleInstructionBuilder Class Reference
BoUpSLP::ShuffleInstructionBuilder Class Reference final
Merges shuffle masks and emits final shuffle instruction, if required.
Public Member Functions
ShuffleInstructionBuilder (IRBuilderBase &Builder, BoUpSLP &R)
void add (Value *V1, Value *V2, ArrayRef< int > Mask)
Adds 2 input vectors and the mask for their shuffling.
void add (Value *V1, ArrayRef< int > Mask)
Adds another one input vector and the mask for the shuffling.
void addOrdered (Value *V1, ArrayRef< unsigned > Order)
Adds another one input vector and the mask for the shuffling.
Value * finalize (ArrayRef< int > ExtMask=std::nullopt)
Finalize emission of the shuffles.
~ShuffleInstructionBuilder ()
Detailed Description
Merges shuffle masks and emits final shuffle instruction, if required.
It supports shuffling of 2 input vectors. It implements lazy shuffles emission, when the actual shuffle instruction is generated only if this is actually required. Otherwise, the shuffle instruction emission is delayed till the end of the process, to reduce the number of emitted instructions and further analysis/transformations. The class also will look through the previously emitted shuffle instructions and properly mark indices in mask as undef. For example, given the code
%s1 = shufflevector <2 x ty> %0, poison, <1, 0>
%s2 = shufflevector <2 x ty> %1, poison, <1, 0>
and if need to emit shuffle of s1 and s2 with mask <1, 0, 3, 2>, it will look through s1 and s2 and emit
%res = shufflevector <2 x ty> %0, %1, <0, 1, 2, 3>
instead. If 2 operands are of different size, the smallest one will be resized and the mask recalculated properly. For example, given the code
%s1 = shufflevector <2 x ty> %0, poison, <1, 0, 1, 0>
%s2 = shufflevector <2 x ty> %1, poison, <1, 0, 1, 0>
and if need to emit shuffle of s1 and s2 with mask <1, 0, 5, 4>, it will look through s1 and s2 and emit
%res = shufflevector <2 x ty> %0, %1, <0, 1, 2, 3>
instead.
Definition at line 8739 of file SLPVectorizer.cpp.
Constructor & Destructor Documentation
ShuffleInstructionBuilder()
BoUpSLP::ShuffleInstructionBuilder::ShuffleInstructionBuilder (IRBuilderBase & Builder, BoUpSLP & R) inline
Definition at line 8837 of file SLPVectorizer.cpp.
~ShuffleInstructionBuilder()
BoUpSLP::ShuffleInstructionBuilder::~ShuffleInstructionBuilder () inline
Definition at line 8957 of file SLPVectorizer.cpp.
References assert().
Member Function Documentation
add() [1/2]
void BoUpSLP::ShuffleInstructionBuilder::add (Value * V1, ArrayRef< int > Mask) inline
Adds another one input vector and the mask for the shuffling.
Definition at line 8869 of file SLPVectorizer.cpp.
References llvm::find(), llvm::Value::getType(), llvm::BitmaskEnumDetail::Mask(), and llvm::UndefMaskElem.
add() [2/2]
void BoUpSLP::ShuffleInstructionBuilder::add (Value * V1, Value * V2, ArrayRef< int > Mask) inline
Adds 2 input vectors and the mask for their shuffling.
Definition at line 8841 of file SLPVectorizer.cpp.
References assert(), llvm::Value::getType(), llvm::BitmaskEnumDetail::Mask(), llvm::UndefMaskElem, and llvm::NVPTX::PTXLdStInstCode::V2.
addOrdered()
void BoUpSLP::ShuffleInstructionBuilder::addOrdered (Value * V1, ArrayRef< unsigned > Order) inline
Adds another one input vector and the mask for the shuffling.
Definition at line 8926 of file SLPVectorizer.cpp.
References llvm::ARM_AM::add, and llvm::inversePermutation().
finalize()
Value* BoUpSLP::ShuffleInstructionBuilder::finalize (ArrayRef< int > ExtMask = std::nullopt) inline
Finalize emission of the shuffles.
Definition at line 8933 of file SLPVectorizer.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), I, llvm::ArrayRef< T >::size(), and llvm::UndefMaskElem.
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/SLPVectorizer.cpp