LLVM: llvm::orc::rt_bootstrap::SimpleExecutorDylibManager Class Reference
llvm::orc::rt_bootstrap::SimpleExecutorDylibManager Class Reference
Simple page-based allocator.
#include "llvm/ExecutionEngine/Orc/TargetProcess/SimpleExecutorDylibManager.h"
Public Member Functions
virtual ~SimpleExecutorDylibManager ()
Expected< tpctypes::DylibHandle > open (const std::string &Path, uint64_t Mode)
Expected< std::vector< ExecutorAddr > > lookup (tpctypes::DylibHandle H, const RemoteSymbolLookupSet &L)
Error shutdown () override
void addBootstrapSymbols (StringMap< ExecutorAddr > &M) override
Public Member Functions inherited from llvm::orc::ExecutorBootstrapService
virtual ~ExecutorBootstrapService ()
Detailed Description
Simple page-based allocator.
Definition at line 35 of file SimpleExecutorDylibManager.h.
Constructor & Destructor Documentation
~SimpleExecutorDylibManager()
llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::~SimpleExecutorDylibManager () virtual
Definition at line 20 of file SimpleExecutorDylibManager.cpp.
References assert(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty().
Member Function Documentation
addBootstrapSymbols()
void llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::addBootstrapSymbols (StringMap< ExecutorAddr > & M) override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 92 of file SimpleExecutorDylibManager.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), M, llvm::orc::rt::SimpleExecutorDylibManagerInstanceName, llvm::orc::rt::SimpleExecutorDylibManagerLookupWrapperName, and llvm::orc::rt::SimpleExecutorDylibManagerOpenWrapperName.
lookup()
Expected< std::vector< ExecutorAddr > > llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::lookup (tpctypes::DylibHandle H, const RemoteSymbolLookupSet & L)
Definition at line 44 of file SimpleExecutorDylibManager.cpp.
References Addr, DL, E, llvm::orc::ExecutorAddr::fromPtr(), H, and llvm::inconvertibleErrorCode().
open()
Expected< tpctypes::DylibHandle > llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::open (const std::string & Path, uint64_t Mode)
Definition at line 25 of file SimpleExecutorDylibManager.cpp.
References DL, llvm::orc::ExecutorAddr::fromPtr(), llvm::sys::DynamicLibrary::getPermanentLibrary(), H, llvm::inconvertibleErrorCode(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), Mode, and move.
shutdown()
Error llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::shutdown () override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 80 of file SimpleExecutorDylibManager.cpp.
References llvm::Error::success(), and std::swap().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/SimpleExecutorDylibManager.h
lib/ExecutionEngine/Orc/TargetProcess/SimpleExecutorDylibManager.cpp