LLVM: llvm::InstrProfLookupTrait Class Reference
llvm::InstrProfLookupTrait Class Reference
Trait for lookups into the on-disk hash table for the binary instrprof format.
#include "llvm/ProfileData/InstrProfReader.h"
Public Types
using data_type = ArrayRef< NamedInstrProfRecord >
using internal_key_type = StringRef
using external_key_type = StringRef
using hash_value_type = uint64_t
using offset_type = uint64_t
Public Member Functions
InstrProfLookupTrait (IndexedInstrProf::HashT HashType, unsigned FormatVersion)
hash_value_type ComputeHash (StringRef K)
StringRef ReadKey (const unsigned char *D, offset_type N)
bool readValueProfilingData (const unsigned char *&D, const unsigned char *const End)
data_type ReadData (StringRef K, const unsigned char *D, offset_type N)
void setValueProfDataEndianness (support::endianness Endianness)
Static Public Member Functions
static bool EqualKey (StringRef A, StringRef B)
static StringRef GetInternalKey (StringRef K)
static StringRef GetExternalKey (StringRef K)
static std::pair< offset_type, offset_type > ReadKeyDataLength (const unsigned char *&D)
Detailed Description
Trait for lookups into the on-disk hash table for the binary instrprof format.
Definition at line 438 of file InstrProfReader.h.
Member Typedef Documentation
data_type
using llvm::InstrProfLookupTrait::data_type = ArrayRef<NamedInstrProfRecord>
Definition at line 451 of file InstrProfReader.h.
external_key_type
using llvm::InstrProfLookupTrait::external_key_type = StringRef
Definition at line 454 of file InstrProfReader.h.
hash_value_type
using llvm::InstrProfLookupTrait::hash_value_type = uint64_t
Definition at line 455 of file InstrProfReader.h.
internal_key_type
using llvm::InstrProfLookupTrait::internal_key_type = StringRef
Definition at line 453 of file InstrProfReader.h.
offset_type
using llvm::InstrProfLookupTrait::offset_type = uint64_t
Definition at line 456 of file InstrProfReader.h.
Constructor & Destructor Documentation
InstrProfLookupTrait()
llvm::InstrProfLookupTrait::InstrProfLookupTrait (IndexedInstrProf::HashT HashType, unsigned FormatVersion) inline
Definition at line 448 of file InstrProfReader.h.
Member Function Documentation
ComputeHash()
InstrProfLookupTrait::hash_value_type InstrProfLookupTrait::ComputeHash (StringRef K)
Definition at line 677 of file InstrProfReader.cpp.
References llvm::IndexedInstrProf::ComputeHash().
EqualKey()
static bool llvm::InstrProfLookupTrait::EqualKey (StringRef A, StringRef B) inline static
Definition at line 458 of file InstrProfReader.h.
References B.
GetExternalKey()
static StringRef llvm::InstrProfLookupTrait::GetExternalKey (StringRef K) inline static
Definition at line 460 of file InstrProfReader.h.
GetInternalKey()
static StringRef llvm::InstrProfLookupTrait::GetInternalKey (StringRef K) inline static
Definition at line 459 of file InstrProfReader.h.
ReadData()
data_type InstrProfLookupTrait::ReadData (StringRef K, const unsigned char * D, offset_type N)
Definition at line 698 of file InstrProfReader.cpp.
References N, support(), and uint64_t.
ReadKey()
StringRef llvm::InstrProfLookupTrait::ReadKey (const unsigned char * D, offset_type N) inline
Definition at line 473 of file InstrProfReader.h.
References D, and N.
ReadKeyDataLength()
static std::pair<offset_type, offset_type> llvm::InstrProfLookupTrait::ReadKeyDataLength (const unsigned char *& D) inline static
Definition at line 465 of file InstrProfReader.h.
References D, and support().
readValueProfilingData()
bool InstrProfLookupTrait::readValueProfilingData (const unsigned char *& D, const unsigned char *const End)
Definition at line 684 of file InstrProfReader.cpp.
setValueProfDataEndianness()
void llvm::InstrProfLookupTrait::setValueProfDataEndianness (support::endianness Endianness) inline
Definition at line 482 of file InstrProfReader.h.
References llvm::msgpack::Endianness.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfReader.h
lib/ProfileData/InstrProfReader.cpp