LLVM: llvm::AMDGPUTargetAsmStreamer Class Reference
llvm::AMDGPUTargetAsmStreamer Class Reference final
#include "Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h"
Public Member Functions
AMDGPUTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS)
void finish () override
void EmitDirectiveAMDGCNTarget () override
void EmitDirectiveHSACodeObjectVersion (uint32_t Major, uint32_t Minor) override
void EmitDirectiveHSACodeObjectISAV2 (uint32_t Major, uint32_t Minor, uint32_t Stepping, StringRef VendorName, StringRef ArchName) override
void EmitAMDKernelCodeT (const amd_kernel_code_t &Header) override
void EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type) override
void emitAMDGPULDS (MCSymbol *Sym, unsigned Size, Align Alignment) override
bool EmitISAVersion () override
bool EmitHSAMetadata (msgpack::Document &HSAMetadata, bool Strict) override
bool EmitHSAMetadata (const AMDGPU::HSAMD::Metadata &HSAMetadata) override
bool EmitCodeEnd (const MCSubtargetInfo &STI) override
void EmitAmdhsaKernelDescriptor (const MCSubtargetInfo &STI, StringRef KernelName, const amdhsa::kernel_descriptor_t &KernelDescriptor, uint64_t NextVGPR, uint64_t NextSGPR, bool ReserveVCC, bool ReserveFlatScr, unsigned CodeObjectVersion) override
Public Member Functions inherited from llvm::AMDGPUTargetStreamer
AMDGPUTargetStreamer (MCStreamer &S)
AMDGPUPALMetadata * getPALMetadata ()
virtual bool EmitHSAMetadataV2 (StringRef HSAMetadataString)
virtual bool EmitHSAMetadataV3 (StringRef HSAMetadataString)
const std::optional< AMDGPU::IsaInfo::AMDGPUTargetID > & getTargetID () const
std::optional< AMDGPU::IsaInfo::AMDGPUTargetID > & getTargetID ()
void initializeTargetID (const MCSubtargetInfo &STI, unsigned CodeObjectVersion)
void initializeTargetID (const MCSubtargetInfo &STI, StringRef FeatureString, unsigned CodeObjectVersion)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::AMDGPUTargetStreamer
static StringRef getArchNameFromElfMach (unsigned ElfMach)
static unsigned getElfMach (StringRef GPU)
Protected Member Functions inherited from llvm::AMDGPUTargetStreamer
MCContext & getContext () const
Protected Attributes inherited from llvm::AMDGPUTargetStreamer
std::optional< AMDGPU::IsaInfo::AMDGPUTargetID > TargetID
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 123 of file AMDGPUTargetStreamer.h.
Constructor & Destructor Documentation
AMDGPUTargetAsmStreamer()
AMDGPUTargetAsmStreamer::AMDGPUTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS)
Definition at line 204 of file AMDGPUTargetStreamer.cpp.
Member Function Documentation
emitAMDGPULDS()
void AMDGPUTargetAsmStreamer::emitAMDGPULDS (MCSymbol * Sym, unsigned Size, Align Alignment) override virtual
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 259 of file AMDGPUTargetStreamer.cpp.
References OS, Size, llvm::ARMBuildAttrs::Symbol, and llvm::Align::value().
EmitAMDGPUSymbolType()
void AMDGPUTargetAsmStreamer::EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type) override virtual
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 249 of file AMDGPUTargetStreamer.cpp.
References llvm_unreachable, OS, llvm::ELF::STT_AMDGPU_HSA_KERNEL, and llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
EmitAmdhsaKernelDescriptor()
void AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor (const MCSubtargetInfo & STI, StringRef KernelName, const amdhsa::kernel_descriptor_t & KernelDescriptor, uint64_t NextVGPR, uint64_t NextSGPR, bool ReserveVCC, bool ReserveFlatScr, unsigned CodeObjectVersion) override virtual
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 320 of file AMDGPUTargetStreamer.cpp.
References AMDHSA_BITS_GET, llvm::AMDGPU::AMDHSA_COV2, llvm::AMDGPU::AMDHSA_COV3, llvm::AMDGPU::AMDHSA_COV4, llvm::AMDGPU::AMDHSA_COV5, llvm::amdhsa::kernel_descriptor_t::compute_pgm_rsrc3, llvm::MCSubtargetInfo::getCPU(), llvm::AMDGPU::getIsaVersion(), llvm::AMDGPUTargetStreamer::getTargetID(), llvm::amdhsa::kernel_descriptor_t::group_segment_fixed_size, llvm::AMDGPU::hasArchitectedFlatScratch(), llvm::AMDGPU::isGFX90A(), llvm::amdhsa::kernel_descriptor_t::kernarg_size, llvm::AMDGPU::IsaVersion::Major, OS, PRINT_FIELD, and llvm::amdhsa::kernel_descriptor_t::private_segment_fixed_size.
EmitAMDKernelCodeT()
void AMDGPUTargetAsmStreamer::EmitAMDKernelCodeT (const amd_kernel_code_t & Header) override virtual
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 243 of file AMDGPUTargetStreamer.cpp.
References llvm::dumpAmdKernelCode(), and OS.
EmitCodeEnd()
bool AMDGPUTargetAsmStreamer::EmitCodeEnd (const MCSubtargetInfo & STI) override virtual
Returns
True on success, false on failure.
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 298 of file AMDGPUTargetStreamer.cpp.
References CacheLineSize, llvm::AMDGPU::isGFX11Plus(), llvm::AMDGPU::isGFX90A(), and OS.
EmitDirectiveAMDGCNTarget()
void AMDGPUTargetAsmStreamer::EmitDirectiveAMDGCNTarget () override virtual
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 221 of file AMDGPUTargetStreamer.cpp.
References llvm::AMDGPUTargetStreamer::getTargetID(), and OS.
EmitDirectiveHSACodeObjectISAV2()
void AMDGPUTargetAsmStreamer::EmitDirectiveHSACodeObjectISAV2 (uint32_t Major, uint32_t Minor, uint32_t Stepping, StringRef VendorName, StringRef ArchName) override virtual
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 232 of file AMDGPUTargetStreamer.cpp.
References convertIsaVersionV2(), OS, and llvm::AMDGPUTargetStreamer::TargetID.
EmitDirectiveHSACodeObjectVersion()
void AMDGPUTargetAsmStreamer::EmitDirectiveHSACodeObjectVersion (uint32_t Major, uint32_t Minor) override virtual
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 225 of file AMDGPUTargetStreamer.cpp.
References OS.
EmitHSAMetadata() [1/2]
bool AMDGPUTargetAsmStreamer::EmitHSAMetadata (const AMDGPU::HSAMD::Metadata & HSAMetadata) override virtual
Returns
True on success, false on failure.
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 270 of file AMDGPUTargetStreamer.cpp.
References llvm::AMDGPU::HSAMD::AssemblerDirectiveBegin, llvm::AMDGPU::HSAMD::AssemblerDirectiveEnd, OS, and llvm::wasm::toString().
EmitHSAMetadata() [2/2]
bool AMDGPUTargetAsmStreamer::EmitHSAMetadata (msgpack::Document & HSAMetadata, bool Strict) override virtual
Returns
True on success, false on failure.
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 282 of file AMDGPUTargetStreamer.cpp.
References llvm::AMDGPU::HSAMD::AssemblerDirectiveBegin, llvm::AMDGPU::HSAMD::AssemblerDirectiveEnd, llvm::msgpack::Document::getRoot(), OS, llvm::raw_string_ostream::str(), llvm::FPOpFusion::Strict, llvm::msgpack::Document::toYAML(), and Verifier.
EmitISAVersion()
bool AMDGPUTargetAsmStreamer::EmitISAVersion () override virtual
Returns
True on success, false on failure.
Reimplemented from llvm::AMDGPUTargetStreamer.
Definition at line 265 of file AMDGPUTargetStreamer.cpp.
References llvm::AMDGPUTargetStreamer::getTargetID(), and OS.
finish()
void AMDGPUTargetAsmStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 211 of file AMDGPUTargetStreamer.cpp.
References llvm::AMDGPUTargetStreamer::getPALMetadata(), OS, llvm::AMDGPUPALMetadata::reset(), S, and llvm::AMDGPUPALMetadata::toString().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.cpp