LLVM: llvm::sampleprof::SampleProfileWriter Class Reference
llvm::sampleprof::SampleProfileWriter Class Reference abstract
Sample-based profile writer. Base class.
#include "llvm/ProfileData/SampleProfWriter.h"
Public Member Functions
virtual ~SampleProfileWriter ()=default
virtual std::error_code writeSample (const FunctionSamples &S)=0
Write sample profiles in S.
virtual std::error_code write (const SampleProfileMap &ProfileMap)
Write all the sample profiles in the given map of samples.
template<typename FunctionPruningStrategy = DefaultFunctionPruningStrategy>
std::error_code writeWithSizeLimit (SampleProfileMap &ProfileMap, size_t OutputSizeLimit)
Write sample profiles up to given size limit, using the pruning strategy to drop some functions if necessary.
raw_ostream & getOutputStream ()
virtual void setProfileSymbolList (ProfileSymbolList *PSL)
virtual void setToCompressAllSections ()
virtual void setUseMD5 ()
virtual void setPartialProfile ()
virtual void resetSecLayout (SectionLayout SL)
Static Public Member Functions
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory.
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Create a new stream writer based on the value of Format.
Protected Member Functions
SampleProfileWriter (std::unique_ptr< raw_ostream > &OS)
virtual std::error_code writeHeader (const SampleProfileMap &ProfileMap)=0
Write a file header for the profile file.
virtual std::error_code writeFuncProfiles (const SampleProfileMap &ProfileMap)
std::error_code writeWithSizeLimitInternal (SampleProfileMap &ProfileMap, size_t OutputSizeLimit, FunctionPruningStrategy *Strategy)
void computeSummary (const SampleProfileMap &ProfileMap)
Compute summary for this profile.
Protected Attributes
size_t LineCount
For writeWithSizeLimit in text mode, each newline takes 1 additional byte on Windows when actually written to the file, but not written to a memory buffer.
std::unique_ptr< raw_ostream > OutputStream
Output stream where to emit the profile to.
std::unique_ptr< ProfileSummary > Summary
Profile summary.
SampleProfileFormat Format = SPF_None
Profile format.
Detailed Description
Sample-based profile writer. Base class.
Definition at line 89 of file SampleProfWriter.h.
Constructor & Destructor Documentation
~SampleProfileWriter()
virtual llvm::sampleprof::SampleProfileWriter::~SampleProfileWriter () virtual default
SampleProfileWriter()
llvm::sampleprof::SampleProfileWriter::SampleProfileWriter (std::unique_ptr< raw_ostream > & OS) inline protected
Definition at line 134 of file SampleProfWriter.h.
Member Function Documentation
computeSummary()
void SampleProfileWriter::computeSummary (const SampleProfileMap & ProfileMap) protected
Compute summary for this profile.
Definition at line 1002 of file SampleProfWriter.cpp.
References Builder, llvm::ProfileSummaryBuilder::DefaultCutoffs, and Summary.
Referenced by llvm::sampleprof::SampleProfileWriterBinary::writeHeader(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeOneSection().
create() [1/2]
ErrorOr< std::unique_ptr< SampleProfileWriter > > SampleProfileWriter::create (std::unique_ptr< raw_ostream > & OS, SampleProfileFormat Format) static
Create a new stream writer based on the value of Format.
Create a sample profile stream writer based on the specified format.
For testing.
Parameters
OS The output stream to store the profile data to.
Format Encoding format for the profile file.
Returns
an error code indicating the status of the created writer.
Definition at line 972 of file SampleProfWriter.cpp.
References Format, move, OS, llvm::sampleprof::FunctionSamples::ProfileIsCS, llvm::sampleprof::FunctionSamples::ProfileIsProbeBased, llvm::sampleprof::SPF_Binary, llvm::sampleprof::SPF_Compact_Binary, llvm::sampleprof::SPF_Ext_Binary, llvm::sampleprof::SPF_GCC, llvm::sampleprof::SPF_Text, llvm::unrecognized_format, and llvm::unsupported_writing_format.
create() [2/2]
ErrorOr< std::unique_ptr< SampleProfileWriter > > SampleProfileWriter::create (StringRef Filename, SampleProfileFormat Format) static
Profile writer factory.
Create a sample profile file writer based on the specified format.
Create a new file writer based on the value of Format.
Parameters
Filename The file to create.
Format Encoding format for the profile file.
Returns
an error code indicating the status of the created writer.
Definition at line 950 of file SampleProfWriter.cpp.
References Format, llvm::sys::fs::OF_None, llvm::sys::fs::OF_TextWithCRLF, OS, llvm::sampleprof::SPF_Binary, llvm::sampleprof::SPF_Compact_Binary, and llvm::sampleprof::SPF_Ext_Binary.
getOutputStream()
raw_ostream& llvm::sampleprof::SampleProfileWriter::getOutputStream () inline
Definition at line 114 of file SampleProfWriter.h.
References OutputStream.
resetSecLayout()
virtual void llvm::sampleprof::SampleProfileWriter::resetSecLayout (SectionLayout SL) inline virtual
Reimplemented in llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 131 of file SampleProfWriter.h.
setPartialProfile()
virtual void llvm::sampleprof::SampleProfileWriter::setPartialProfile () inline virtual
Reimplemented in llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 130 of file SampleProfWriter.h.
setProfileSymbolList()
virtual void llvm::sampleprof::SampleProfileWriter::setProfileSymbolList (ProfileSymbolList * PSL) inline virtual
Reimplemented in llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 127 of file SampleProfWriter.h.
setToCompressAllSections()
virtual void llvm::sampleprof::SampleProfileWriter::setToCompressAllSections () inline virtual
Reimplemented in llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 128 of file SampleProfWriter.h.
setUseMD5()
virtual void llvm::sampleprof::SampleProfileWriter::setUseMD5 () inline virtual
Reimplemented in llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 129 of file SampleProfWriter.h.
write()
std::error_code SampleProfileWriter::write (const SampleProfileMap & ProfileMap) virtual
Write all the sample profiles in the given map of samples.
Returns
status code of the file update operation.
Reimplemented in llvm::sampleprof::SampleProfileWriterCompactBinary, and llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 155 of file SampleProfWriter.cpp.
References llvm::success, writeFuncProfiles(), and writeHeader().
Referenced by llvm::sampleprof::SampleProfileWriterCompactBinary::write(), and writeWithSizeLimitInternal().
writeFuncProfiles()
std::error_code SampleProfileWriter::writeFuncProfiles (const SampleProfileMap & ProfileMap) protected virtual
Definition at line 145 of file SampleProfWriter.cpp.
References I, llvm::sampleprof::sortFuncProfiles(), llvm::success, and writeSample().
Referenced by write(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeOneSection().
writeHeader()
virtual std::error_code llvm::sampleprof::SampleProfileWriter::writeHeader (const SampleProfileMap & ProfileMap) protected pure virtual
Write a file header for the profile file.
Implemented in llvm::sampleprof::SampleProfileWriterCompactBinary, llvm::sampleprof::SampleProfileWriterBinary, and llvm::sampleprof::SampleProfileWriterText.
Referenced by write().
writeSample()
virtual std::error_code llvm::sampleprof::SampleProfileWriter::writeSample (const FunctionSamples & S) pure virtual
Write sample profiles in S.
Returns
status code of the file update operation.
Implemented in llvm::sampleprof::SampleProfileWriterCompactBinary, llvm::sampleprof::SampleProfileWriterExtBinaryBase, llvm::sampleprof::SampleProfileWriterBinary, and llvm::sampleprof::SampleProfileWriterText.
Referenced by writeFuncProfiles().
writeWithSizeLimit()
template<typename FunctionPruningStrategy = DefaultFunctionPruningStrategy> std::error_code llvm::sampleprof::SampleProfileWriter::writeWithSizeLimit (SampleProfileMap & ProfileMap, size_t OutputSizeLimit) inline
Write sample profiles up to given size limit, using the pruning strategy to drop some functions if necessary.
Returns
status code of the file update operation.
Definition at line 108 of file SampleProfWriter.h.
References writeWithSizeLimitInternal().
writeWithSizeLimitInternal()
std::error_code SampleProfileWriter::writeWithSizeLimitInternal (SampleProfileMap & ProfileMap, size_t OutputSizeLimit, FunctionPruningStrategy * Strategy) protected
Definition at line 94 of file SampleProfWriter.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), llvm::sampleprof::FunctionPruningStrategy::Erase(), Format, LineCount, LLVM_DEBUG, OutputStream, llvm::sampleprof::SPF_Text, llvm::success, llvm::too_large, and write().
Referenced by writeWithSizeLimit().
Member Data Documentation
Format
SampleProfileFormat llvm::sampleprof::SampleProfileWriter::Format = SPF_None protected
Profile format.
Definition at line 162 of file SampleProfWriter.h.
Referenced by create(), llvm::sampleprof::SampleProfileWriterBinary::writeHeader(), llvm::sampleprof::SampleProfileWriterBinary::writeMagicIdent(), and writeWithSizeLimitInternal().
LineCount
size_t llvm::sampleprof::SampleProfileWriter::LineCount protected
For writeWithSizeLimit in text mode, each newline takes 1 additional byte on Windows when actually written to the file, but not written to a memory buffer.
This needs to be accounted for when rewriting the profile.
Definition at line 150 of file SampleProfWriter.h.
Referenced by llvm::sampleprof::SampleProfileWriterText::writeHeader(), llvm::sampleprof::SampleProfileWriterText::writeSample(), and writeWithSizeLimitInternal().
OutputStream
std::unique_ptr<raw_ostream> llvm::sampleprof::SampleProfileWriter::OutputStream protected
Output stream where to emit the profile to.
Definition at line 153 of file SampleProfWriter.h.
Referenced by getOutputStream(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::markSectionStart(), llvm::sampleprof::SampleProfileWriterBinary::writeBody(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeCSNameIdx(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeCSNameTableSection(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeFuncMetadata(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeFuncOffsetTable(), llvm::sampleprof::SampleProfileWriterCompactBinary::writeFuncOffsetTable(), llvm::sampleprof::SampleProfileWriterCompactBinary::writeHeader(), llvm::sampleprof::SampleProfileWriterBinary::writeMagicIdent(), llvm::sampleprof::SampleProfileWriterBinary::writeNameIdx(), llvm::sampleprof::SampleProfileWriterBinary::writeNameTable(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeNameTable(), llvm::sampleprof::SampleProfileWriterCompactBinary::writeNameTable(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeOneSection(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeProfileSymbolListSection(), llvm::sampleprof::SampleProfileWriterText::writeSample(), llvm::sampleprof::SampleProfileWriterBinary::writeSample(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeSample(), llvm::sampleprof::SampleProfileWriterCompactBinary::writeSample(), llvm::sampleprof::SampleProfileWriterBinary::writeSummary(), and writeWithSizeLimitInternal().
Summary
std::unique_ptr<ProfileSummary> llvm::sampleprof::SampleProfileWriter::Summary protected
Profile summary.
Definition at line 156 of file SampleProfWriter.h.
Referenced by computeSummary(), and llvm::sampleprof::SampleProfileWriterBinary::writeSummary().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfWriter.h
lib/ProfileData/SampleProfWriter.cpp