LLVM: llvm::ProfOStream Class Reference
llvm::ProfOStream Class Reference
Public Member Functions
ProfOStream (raw_fd_ostream &FD)
ProfOStream (raw_string_ostream &STR)
uint64_t tell ()
void write (uint64_t V)
void writeByte (uint8_t V)
void patch (PatchItem *P, int NItems)
Public Attributes
bool IsFDOStream
raw_ostream & OS
support::endian::Writer LE
Detailed Description
Definition at line 48 of file InstrProfWriter.cpp.
Constructor & Destructor Documentation
ProfOStream() [1/2]
llvm::ProfOStream::ProfOStream (raw_fd_ostream & FD) inline
Definition at line 50 of file InstrProfWriter.cpp.
ProfOStream() [2/2]
llvm::ProfOStream::ProfOStream (raw_string_ostream & STR) inline
Definition at line 52 of file InstrProfWriter.cpp.
Member Function Documentation
patch()
void llvm::ProfOStream::patch (PatchItem * P, int NItems) inline
Definition at line 62 of file InstrProfWriter.cpp.
References D, llvm::Data, I, IsFDOStream, OS, P, llvm::raw_fd_ostream::seek(), llvm::raw_string_ostream::str(), support(), llvm::raw_ostream::tell(), uint64_t, and write().
tell()
uint64_t llvm::ProfOStream::tell () inline
Definition at line 55 of file InstrProfWriter.cpp.
References OS, and llvm::raw_ostream::tell().
write()
void llvm::ProfOStream::write (uint64_t V) inline
Definition at line 56 of file InstrProfWriter.cpp.
References LE, uint64_t, and llvm::support::endian::Writer::write().
Referenced by patch().
writeByte()
void llvm::ProfOStream::writeByte (uint8_t V) inline
Definition at line 57 of file InstrProfWriter.cpp.
References LE, and llvm::support::endian::Writer::write().
Member Data Documentation
IsFDOStream
bool llvm::ProfOStream::IsFDOStream
Definition at line 92 of file InstrProfWriter.cpp.
Referenced by patch().
LE
support::endian::Writer llvm::ProfOStream::LE
Definition at line 94 of file InstrProfWriter.cpp.
Referenced by llvm::InstrProfRecordWriterTrait::EmitData(), llvm::InstrProfRecordWriterTrait::EmitKeyDataLength(), write(), and writeByte().
OS
raw_ostream& llvm::ProfOStream::OS
Definition at line 93 of file InstrProfWriter.cpp.
Referenced by patch(), and tell().
The documentation for this class was generated from the following file:
lib/ProfileData/InstrProfWriter.cpp