LLVM: llvm::GISelInstProfileBuilder Class Reference
llvm::GISelInstProfileBuilder Class Reference
#include "llvm/CodeGen/GlobalISel/CSEInfo.h"
Public Member Functions
GISelInstProfileBuilder (FoldingSetNodeID &ID, const MachineRegisterInfo &MRI)
const GISelInstProfileBuilder & addNodeIDOpcode (unsigned Opc) const
const GISelInstProfileBuilder & addNodeIDRegType (const LLT Ty) const
const GISelInstProfileBuilder & addNodeIDRegType (const Register) const
const GISelInstProfileBuilder & addNodeIDRegType (const TargetRegisterClass *RC) const
const GISelInstProfileBuilder & addNodeIDRegType (const RegisterBank *RB) const
const GISelInstProfileBuilder & addNodeIDRegNum (Register Reg) const
const GISelInstProfileBuilder & addNodeIDReg (Register Reg) const
const GISelInstProfileBuilder & addNodeIDImmediate (int64_t Imm) const
const GISelInstProfileBuilder & addNodeIDMBB (const MachineBasicBlock *MBB) const
const GISelInstProfileBuilder & addNodeIDMachineOperand (const MachineOperand &MO) const
const GISelInstProfileBuilder & addNodeIDFlag (unsigned Flag) const
const GISelInstProfileBuilder & addNodeID (const MachineInstr *MI) const
Detailed Description
Definition at line 167 of file CSEInfo.h.
Constructor & Destructor Documentation
GISelInstProfileBuilder()
llvm::GISelInstProfileBuilder::GISelInstProfileBuilder (FoldingSetNodeID & ID, const MachineRegisterInfo & MRI) inline
Definition at line 172 of file CSEInfo.h.
References MRI.
Member Function Documentation
addNodeID()
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeID (const MachineInstr * MI) const
Definition at line 323 of file CSEInfo.cpp.
References addNodeIDFlag(), addNodeIDMachineOperand(), addNodeIDMBB(), addNodeIDOpcode(), and MI.
Referenced by llvm::UniqueMachineInstr::Profile(), and llvm::GISelCSEInfo::verify().
addNodeIDFlag()
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDFlag (unsigned Flag) const
Definition at line 382 of file CSEInfo.cpp.
Referenced by addNodeID().
addNodeIDImmediate()
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDImmediate (int64_t Imm) const
Definition at line 358 of file CSEInfo.cpp.
References llvm::RISCVMatInt::Imm.
addNodeIDMachineOperand()
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDMachineOperand (const MachineOperand & MO) const
Definition at line 403 of file CSEInfo.cpp.
References addNodeIDReg(), addNodeIDRegNum(), assert(), llvm::MachineOperand::getCImm(), llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isCImm(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isFPImm(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isPredicate(), llvm::MachineOperand::isReg(), and llvm_unreachable.
Referenced by addNodeID(), addNodeIDRegType(), llvm::CSEMIRBuilder::buildConstant(), and llvm::CSEMIRBuilder::buildFConstant().
addNodeIDMBB()
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDMBB (const MachineBasicBlock * MBB) const
Definition at line 376 of file CSEInfo.cpp.
References MBB.
Referenced by addNodeID().
addNodeIDOpcode()
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDOpcode (unsigned Opc) const
Definition at line 333 of file CSEInfo.cpp.
Referenced by addNodeID().
addNodeIDReg()
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDReg (Register Reg) const
Definition at line 389 of file CSEInfo.cpp.
References addNodeIDRegType(), llvm::MachineRegisterInfo::getRegClassOrRegBank(), llvm::MachineRegisterInfo::getType(), and llvm::LLT::isValid().
Referenced by addNodeIDMachineOperand().
addNodeIDRegNum()
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDRegNum (Register Reg) const
Definition at line 364 of file CSEInfo.cpp.
Referenced by addNodeIDMachineOperand().
addNodeIDRegType() [1/4]
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDRegType (const LLT Ty) const
Definition at line 339 of file CSEInfo.cpp.
References llvm::LLT::getUniqueRAWLLTData(), and uint64_t.
Referenced by addNodeIDReg().
addNodeIDRegType() [2/4]
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDRegType (const Register Reg) const
Definition at line 370 of file CSEInfo.cpp.
References addNodeIDMachineOperand(), and llvm::MachineOperand::CreateReg().
addNodeIDRegType() [3/4]
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDRegType (const RegisterBank * RB) const
Definition at line 352 of file CSEInfo.cpp.
addNodeIDRegType() [4/4]
const GISelInstProfileBuilder & GISelInstProfileBuilder::addNodeIDRegType (const TargetRegisterClass * RC) const
Definition at line 346 of file CSEInfo.cpp.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/CSEInfo.h
lib/CodeGen/GlobalISel/CSEInfo.cpp