LLVM: llvm::VPLane Class Reference
llvm::VPLane Class Reference
In what follows, the term "input IR" refers to code that is fed into the vectorizer whereas the term "output IR" refers to code that is generated by the vectorizer.
#include "Transforms/Vectorize/VPlan.h"
Public Types
enum Kind : uint8_t { Kind::First, Kind::ScalableLast }
Kind describes how to interpret Lane.
Public Member Functions
VPLane (unsigned Lane, Kind LaneKind)
unsigned getKnownLane () const
Returns a compile-time known value for the lane index and asserts if the lane can only be calculated at runtime.
Value * getAsRuntimeExpr (IRBuilderBase &Builder, const ElementCount &VF) const
Returns an expression describing the lane index that can be used at runtime.
Kind getKind () const
Returns the Kind of lane offset.
bool isFirstLane () const
Returns true if this is the first lane of the whole vector.
unsigned mapToCacheIndex (const ElementCount &VF) const
Maps the lane to a cache index based on VF.
Static Public Member Functions
static VPLane getFirstLane ()
static VPLane getLastLaneForVF (const ElementCount &VF)
static unsigned getNumCachedLanes (const ElementCount &VF)
Returns the maxmimum number of lanes that we are able to consider caching for VF.
Detailed Description
In what follows, the term "input IR" refers to code that is fed into the vectorizer whereas the term "output IR" refers to code that is generated by the vectorizer.
VPLane provides a way to access lanes in both fixed width and scalable vectors, where for the latter the lane index sometimes needs calculating as a runtime expression.
Definition at line 113 of file VPlan.h.
Member Enumeration Documentation
Kind
enum llvm::VPLane::Kind : uint8_t strong
Kind describes how to interpret Lane.
Enumerator
First
For First, Lane is the index into the first N elements of a fixed-vector <N x <ElTy>> or a scalable vector <vscale x N x <ElTy>>.
ScalableLast
For ScalableLast, Lane is the offset from the start of the last N-element subvector in a scalable vector <vscale x N x <ElTy>>.
For example, a Lane of 0 corresponds to lane (vscale - 1) * N, a Lane of 1 corresponds to ((vscale - 1) * N) + 1, etc.
Definition at line 116 of file VPlan.h.
Constructor & Destructor Documentation
VPLane()
llvm::VPLane::VPLane (unsigned Lane, Kind LaneKind) inline
Definition at line 135 of file VPlan.h.
Referenced by getFirstLane(), and getLastLaneForVF().
Member Function Documentation
getAsRuntimeExpr()
Value * VPLane::getAsRuntimeExpr (IRBuilderBase & Builder, const ElementCount & VF) const
Returns an expression describing the lane index that can be used at runtime.
Definition at line 66 of file VPlan.cpp.
References Builder, First, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::getRuntimeVF(), llvm_unreachable, and ScalableLast.
Referenced by llvm::InnerLoopVectorizer::packScalarIntoVectorValue().
getFirstLane()
static VPLane llvm::VPLane::getFirstLane () inline static
Definition at line 137 of file VPlan.h.
References First, and VPLane().
Referenced by llvm::VPLiveOut::fixPhi(), and llvm::InnerLoopVectorizer::scalarizeInstruction().
getKind()
Kind llvm::VPLane::getKind () const inline
Returns the Kind of lane offset.
Definition at line 163 of file VPlan.h.
getKnownLane()
unsigned llvm::VPLane::getKnownLane () const inline
Returns a compile-time known value for the lane index and asserts if the lane can only be calculated at runtime.
Definition at line 153 of file VPlan.h.
References assert(), and First.
getLastLaneForVF()
static VPLane llvm::VPLane::getLastLaneForVF (const ElementCount & VF) inline static
Definition at line 139 of file VPlan.h.
References First, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), ScalableLast, and VPLane().
Referenced by llvm::VPReplicateRecipe::execute(), and llvm::VPLiveOut::fixPhi().
getNumCachedLanes()
static unsigned llvm::VPLane::getNumCachedLanes (const ElementCount & VF) inline static
Returns the maxmimum number of lanes that we are able to consider caching for VF.
Definition at line 182 of file VPlan.h.
References llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
isFirstLane()
bool llvm::VPLane::isFirstLane () const inline
Returns true if this is the first lane of the whole vector.
Definition at line 166 of file VPlan.h.
References First.
Referenced by llvm::VPIteration::isFirstIteration().
mapToCacheIndex()
unsigned llvm::VPLane::mapToCacheIndex (const ElementCount & VF) const inline
Maps the lane to a cache index based on VF.
Definition at line 169 of file VPlan.h.
References assert(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), and ScalableLast.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp