LLVM: llvm::AttributeSet Class Reference
llvm::AttributeSet Class Reference
#include "llvm/IR/Attributes.h"
Public Types
using iterator = const Attribute *
Public Member Functions
AttributeSet ()=default
AttributeSet is a trivially copyable value type.
AttributeSet (const AttributeSet &)=default
~AttributeSet ()=default
bool operator== (const AttributeSet &O) const
bool operator!= (const AttributeSet &O) const
AttributeSet addAttribute (LLVMContext &C, Attribute::AttrKind Kind) const
Add an argument attribute.
AttributeSet addAttribute (LLVMContext &C, StringRef Kind, StringRef Value=StringRef()) const
Add a target-dependent attribute.
AttributeSet addAttributes (LLVMContext &C, AttributeSet AS) const
Add attributes to the attribute set.
AttributeSet removeAttribute (LLVMContext &C, Attribute::AttrKind Kind) const
Remove the specified attribute from this set.
AttributeSet removeAttribute (LLVMContext &C, StringRef Kind) const
Remove the specified attribute from this set.
AttributeSet removeAttributes (LLVMContext &C, const AttributeMask &AttrsToRemove) const
Remove the specified attributes from this set.
unsigned getNumAttributes () const
Return the number of attributes in this set.
bool hasAttributes () const
Return true if attributes exists in this set.
bool hasAttribute (Attribute::AttrKind Kind) const
Return true if the attribute exists in this set.
bool hasAttribute (StringRef Kind) const
Return true if the attribute exists in this set.
Attribute getAttribute (Attribute::AttrKind Kind) const
Return the attribute object.
Attribute getAttribute (StringRef Kind) const
Return the target-dependent attribute object.
MaybeAlign getAlignment () const
MaybeAlign getStackAlignment () const
uint64_t getDereferenceableBytes () const
uint64_t getDereferenceableOrNullBytes () const
Type * getByValType () const
Type * getStructRetType () const
Type * getByRefType () const
Type * getPreallocatedType () const
Type * getInAllocaType () const
Type * getElementType () const
std::optional< std::pair< unsigned, std::optional< unsigned > > > getAllocSizeArgs () const
unsigned getVScaleRangeMin () const
std::optional< unsigned > getVScaleRangeMax () const
UWTableKind getUWTableKind () const
AllocFnKind getAllocKind () const
MemoryEffects getMemoryEffects () const
std::string getAsString (bool InAttrGrp=false) const
bool hasParentContext (LLVMContext &C) const
Return true if this attribute set belongs to the LLVMContext.
iterator begin () const
iterator end () const
void dump () const
Static Public Member Functions
static AttributeSet get (LLVMContext &C, const AttrBuilder &B)
static AttributeSet get (LLVMContext &C, ArrayRef< Attribute > Attrs)
Friends
template<typename Ty , typename Enable >
struct DenseMapInfo
Detailed Description
Definition at line 295 of file Attributes.h.
Member Typedef Documentation
iterator
using llvm::AttributeSet::iterator = const Attribute *
Definition at line 391 of file Attributes.h.
Constructor & Destructor Documentation
AttributeSet() [1/2]
llvm::AttributeSet::AttributeSet () default
AttributeSet is a trivially copyable value type.
Referenced by get().
AttributeSet() [2/2]
llvm::AttributeSet::AttributeSet (const AttributeSet &) default
~AttributeSet()
llvm::AttributeSet::~AttributeSet () default
Member Function Documentation
addAttribute() [1/2]
AttributeSet AttributeSet::addAttribute (LLVMContext & C, Attribute::AttrKind Kind) const
Add an argument attribute.
Returns a new set because attribute sets are immutable.
Definition at line 701 of file Attributes.cpp.
References addAttributes(), B, get(), and hasAttribute().
Referenced by llvm::OpenMPIRBuilder::addAttributes().
addAttribute() [2/2]
AttributeSet AttributeSet::addAttribute (LLVMContext & C, StringRef Kind, StringRef Value = StringRef()) const
Add a target-dependent attribute.
Returns a new set because attribute sets are immutable.
Definition at line 709 of file Attributes.cpp.
References addAttributes(), B, and get().
addAttributes()
AttributeSet AttributeSet::addAttributes (LLVMContext & C, AttributeSet AS) const
Add attributes to the attribute set.
Returns a new set because attribute sets are immutable.
Definition at line 716 of file Attributes.cpp.
References B, get(), and hasAttributes().
Referenced by addAttribute(), and llvm::OpenMPIRBuilder::addAttributes().
begin()
AttributeSet::iterator AttributeSet::begin () const
Definition at line 855 of file Attributes.cpp.
References llvm::AttributeSetNode::begin().
dump()
LLVM_DUMP_METHOD void AttributeSet::dump () const
Definition at line 864 of file Attributes.cpp.
References llvm::dbgs(), and getAsString().
end()
AttributeSet::iterator AttributeSet::end () const
Definition at line 859 of file Attributes.cpp.
References llvm::AttributeSetNode::end().
get() [1/2]
AttributeSet AttributeSet::get (LLVMContext & C, ArrayRef< Attribute > Attrs) static
Definition at line 697 of file Attributes.cpp.
References AttributeSet(), Attrs, and llvm::AttributeSetNode::get().
get() [2/2]
AttributeSet AttributeSet::get (LLVMContext & C, const AttrBuilder & B) static
Definition at line 693 of file Attributes.cpp.
References AttributeSet(), B, and llvm::AttributeSetNode::get().
Referenced by addAttribute(), llvm::AttributeList::addAttributeAtIndex(), addAttributes(), llvm::AttributeList::addAttributesAtIndex(), llvm::AttributeList::addParamAttribute(), llvm::AttributeList::get(), llvm::promoteCall(), removeAttribute(), and removeAttributes().
getAlignment()
MaybeAlign AttributeSet::getAlignment () const
Definition at line 776 of file Attributes.cpp.
References llvm::AttributeSetNode::getAlignment().
Referenced by llvm::AttributeList::getParamAlignment(), and llvm::AttributeList::getRetAlignment().
getAllocKind()
AllocFnKind AttributeSet::getAllocKind () const
Definition at line 835 of file Attributes.cpp.
References llvm::AttributeSetNode::getAllocKind(), and llvm::Unknown.
Referenced by llvm::AttributeList::getAllocKind().
getAllocSizeArgs()
std::optional< std::pair< unsigned, std::optional< unsigned > > > AttributeSet::getAllocSizeArgs () const
Definition at line 817 of file Attributes.cpp.
References llvm::AttributeSetNode::getAllocSizeArgs().
getAsString()
std::string AttributeSet::getAsString (bool InAttrGrp = false) const
Definition at line 843 of file Attributes.cpp.
References llvm::AttributeSetNode::getAsString().
Referenced by dump(), and llvm::AttributeList::getAsString().
getAttribute() [1/2]
Attribute AttributeSet::getAttribute (Attribute::AttrKind Kind) const
Return the attribute object.
Definition at line 768 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttribute().
Referenced by llvm::AttributeList::getAttributeAtIndex().
getAttribute() [2/2]
Attribute AttributeSet::getAttribute (StringRef Kind) const
Return the target-dependent attribute object.
Definition at line 772 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttribute().
getByRefType()
Type * AttributeSet::getByRefType () const
Definition at line 792 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by getMemoryParamAllocType(), and llvm::AttributeList::getParamByRefType().
getByValType()
Type * AttributeSet::getByValType () const
Definition at line 796 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by getMemoryParamAllocType(), and llvm::AttributeList::getParamByValType().
getDereferenceableBytes()
uint64_t AttributeSet::getDereferenceableBytes () const
Definition at line 784 of file Attributes.cpp.
References llvm::AttributeSetNode::getDereferenceableBytes().
Referenced by llvm::AttributeList::getParamDereferenceableBytes(), and llvm::AttributeList::getRetDereferenceableBytes().
getDereferenceableOrNullBytes()
uint64_t AttributeSet::getDereferenceableOrNullBytes () const
Definition at line 788 of file Attributes.cpp.
References llvm::AttributeSetNode::getDereferenceableOrNullBytes().
Referenced by llvm::AttributeList::getParamDereferenceableOrNullBytes(), and llvm::AttributeList::getRetDereferenceableOrNullBytes().
getElementType()
Type * AttributeSet::getElementType () const
Definition at line 812 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by llvm::AttributeList::getParamElementType().
getInAllocaType()
Type * AttributeSet::getInAllocaType () const
Definition at line 808 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by getMemoryParamAllocType(), and llvm::AttributeList::getParamInAllocaType().
getMemoryEffects()
MemoryEffects AttributeSet::getMemoryEffects () const
Definition at line 839 of file Attributes.cpp.
References llvm::AttributeSetNode::getMemoryEffects(), and llvm::MemoryEffects::unknown().
Referenced by llvm::AttributeList::getMemoryEffects().
getNumAttributes()
unsigned AttributeSet::getNumAttributes () const
Return the number of attributes in this set.
Definition at line 756 of file Attributes.cpp.
References llvm::AttributeSetNode::getNumAttributes().
getPreallocatedType()
Type * AttributeSet::getPreallocatedType () const
Definition at line 804 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by getMemoryParamAllocType(), and llvm::AttributeList::getParamPreallocatedType().
getStackAlignment()
MaybeAlign AttributeSet::getStackAlignment () const
Definition at line 780 of file Attributes.cpp.
References llvm::AttributeSetNode::getStackAlignment().
Referenced by llvm::AttributeList::getFnStackAlignment(), llvm::AttributeList::getParamStackAlignment(), and llvm::AttributeList::getRetStackAlignment().
getStructRetType()
Type * AttributeSet::getStructRetType () const
Definition at line 800 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by getMemoryParamAllocType(), and llvm::AttributeList::getParamStructRetType().
getUWTableKind()
UWTableKind AttributeSet::getUWTableKind () const
Definition at line 831 of file Attributes.cpp.
References llvm::AttributeSetNode::getUWTableKind(), and llvm::None.
Referenced by llvm::AttributeList::getUWTableKind().
getVScaleRangeMax()
std::optional< unsigned > AttributeSet::getVScaleRangeMax () const
Definition at line 827 of file Attributes.cpp.
References llvm::AttributeSetNode::getVScaleRangeMax().
getVScaleRangeMin()
unsigned AttributeSet::getVScaleRangeMin () const
Definition at line 823 of file Attributes.cpp.
References llvm::AttributeSetNode::getVScaleRangeMin().
hasAttribute() [1/2]
bool AttributeSet::hasAttribute (Attribute::AttrKind Kind) const
Return true if the attribute exists in this set.
Definition at line 760 of file Attributes.cpp.
References llvm::AttributeSetNode::hasAttribute().
Referenced by addAttribute(), llvm::AttributeList::hasAttributeAtIndex(), llvm::GlobalVariable::hasImplicitSection(), and removeAttribute().
hasAttribute() [2/2]
bool AttributeSet::hasAttribute (StringRef Kind) const
Return true if the attribute exists in this set.
Definition at line 764 of file Attributes.cpp.
References llvm::AttributeSetNode::hasAttribute().
hasAttributes()
bool llvm::AttributeSet::hasAttributes () const inline
Return true if attributes exists in this set.
Definition at line 355 of file Attributes.h.
Referenced by addAttributes(), llvm::AttributeList::get(), llvm::AttributeList::hasAttributesAtIndex(), and hasParentContext().
hasParentContext()
bool AttributeSet::hasParentContext (LLVMContext & C) const
Return true if this attribute set belongs to the LLVMContext.
Definition at line 847 of file Attributes.cpp.
References assert(), hasAttributes(), and llvm::AttributeSetNode::Profile().
operator!=()
bool llvm::AttributeSet::operator!= (const AttributeSet & O) const inline
Definition at line 319 of file Attributes.h.
References llvm::RISCVFenceField::O.
operator==()
bool llvm::AttributeSet::operator== (const AttributeSet & O) const inline
Definition at line 318 of file Attributes.h.
References llvm::RISCVFenceField::O.
removeAttribute() [1/2]
AttributeSet AttributeSet::removeAttribute (LLVMContext & C, Attribute::AttrKind Kind) const
Remove the specified attribute from this set.
Returns a new set because attribute sets are immutable.
Definition at line 729 of file Attributes.cpp.
References B, get(), and hasAttribute().
removeAttribute() [2/2]
AttributeSet AttributeSet::removeAttribute (LLVMContext & C, StringRef Kind) const
Remove the specified attribute from this set.
Returns a new set because attribute sets are immutable.
Definition at line 737 of file Attributes.cpp.
References B, get(), and hasAttribute().
removeAttributes()
AttributeSet AttributeSet::removeAttributes (LLVMContext & C, const AttributeMask & AttrsToRemove) const
Remove the specified attributes from this set.
Returns a new set because attribute sets are immutable.
Definition at line 745 of file Attributes.cpp.
References Attrs, B, and get().
Friends And Related Function Documentation
DenseMapInfo
template<typename Ty , typename Enable > friend struct DenseMapInfo friend
Definition at line 297 of file Attributes.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Attributes.h
lib/IR/Attributes.cpp