LLVM: llvm::AttributeBitSet Class Reference
llvm::AttributeBitSet Class Reference
#include "IR/AttributeImpl.h"
Public Member Functions
bool hasAttribute (Attribute::AttrKind Kind) const
void addAttribute (Attribute::AttrKind Kind)
Detailed Description
Definition at line 199 of file AttributeImpl.h.
Member Function Documentation
addAttribute()
void llvm::AttributeBitSet::addAttribute (Attribute::AttrKind Kind) inline
Definition at line 210 of file AttributeImpl.h.
Referenced by llvm::AttributeListImpl::AttributeListImpl().
hasAttribute()
bool llvm::AttributeBitSet::hasAttribute (Attribute::AttrKind Kind) const inline
Definition at line 206 of file AttributeImpl.h.
Referenced by llvm::AttributeSetNode::hasAttribute(), llvm::AttributeListImpl::hasAttrSomewhere(), and llvm::AttributeListImpl::hasFnAttribute().
The documentation for this class was generated from the following file:
lib/IR/AttributeImpl.h