LLVM: llvm::AArch64TargetWinCOFFStreamer Class Reference
llvm::AArch64TargetWinCOFFStreamer Class Reference
#include "Target/AArch64/MCTargetDesc/AArch64TargetStreamer.h"
Public Member Functions
AArch64TargetWinCOFFStreamer (llvm::MCStreamer &S)
void emitARM64WinCFIAllocStack (unsigned Size) override
void emitARM64WinCFISaveR19R20X (int Offset) override
void emitARM64WinCFISaveFPLR (int Offset) override
void emitARM64WinCFISaveFPLRX (int Offset) override
void emitARM64WinCFISaveReg (unsigned Reg, int Offset) override
void emitARM64WinCFISaveRegX (unsigned Reg, int Offset) override
void emitARM64WinCFISaveRegP (unsigned Reg, int Offset) override
void emitARM64WinCFISaveRegPX (unsigned Reg, int Offset) override
void emitARM64WinCFISaveLRPair (unsigned Reg, int Offset) override
void emitARM64WinCFISaveFReg (unsigned Reg, int Offset) override
void emitARM64WinCFISaveFRegX (unsigned Reg, int Offset) override
void emitARM64WinCFISaveFRegP (unsigned Reg, int Offset) override
void emitARM64WinCFISaveFRegPX (unsigned Reg, int Offset) override
void emitARM64WinCFISetFP () override
void emitARM64WinCFIAddFP (unsigned Size) override
void emitARM64WinCFINop () override
void emitARM64WinCFISaveNext () override
void emitARM64WinCFIPrologEnd () override
void emitARM64WinCFIEpilogStart () override
void emitARM64WinCFIEpilogEnd () override
void emitARM64WinCFITrapFrame () override
void emitARM64WinCFIMachineFrame () override
void emitARM64WinCFIContext () override
void emitARM64WinCFIClearUnwoundToCall () override
void emitARM64WinCFIPACSignLR () override
void emitARM64WinCFISaveAnyRegI (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegIP (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegD (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegDP (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegQ (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegQP (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegIX (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegIPX (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegDX (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegDPX (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegQX (unsigned Reg, int Offset) override
void emitARM64WinCFISaveAnyRegQPX (unsigned Reg, int Offset) override
Public Member Functions inherited from llvm::AArch64TargetStreamer
AArch64TargetStreamer (MCStreamer &S)
~AArch64TargetStreamer () override
void finish () override
void emitConstantPools () override
const MCExpr * addConstantPoolEntry (const MCExpr *, unsigned Size, SMLoc Loc)
Callback used to implement the ldr= pseudo.
void emitCurrentConstantPool ()
Callback used to implement the .ltorg directive.
void emitNoteSection (unsigned Flags)
Callback used to implement the .note.gnu.property section.
virtual void emitInst (uint32_t Inst)
Callback used to implement the .inst directive.
virtual void emitDirectiveVariantPCS (MCSymbol *Symbol)
Callback used to implement the .variant_pcs directive.
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 99 of file AArch64TargetStreamer.h.
Constructor & Destructor Documentation
AArch64TargetWinCOFFStreamer()
llvm::AArch64TargetWinCOFFStreamer::AArch64TargetWinCOFFStreamer (llvm::MCStreamer & S) inline
Definition at line 107 of file AArch64TargetStreamer.h.
Member Function Documentation
emitARM64WinCFIAddFP()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFIAddFP (unsigned Size) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 156 of file AArch64WinCOFFStreamer.cpp.
References assert(), llvm::Offset, and llvm::Win64EH::UOP_AddFP.
emitARM64WinCFIAllocStack()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFIAllocStack (unsigned Size) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 82 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_AllocLarge, llvm::Win64EH::UOP_AllocMedium, and llvm::Win64EH::UOP_AllocSmall.
emitARM64WinCFIClearUnwoundToCall()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFIClearUnwoundToCall () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 222 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_ClearUnwoundToCall.
emitARM64WinCFIContext()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFIContext () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 218 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_Context.
emitARM64WinCFIEpilogEnd()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFIEpilogEnd () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 195 of file AArch64WinCOFFStreamer.cpp.
References llvm::WinEH::FrameInfo::EpilogMap, llvm::MCTargetStreamer::getStreamer(), S, and llvm::Win64EH::UOP_End.
emitARM64WinCFIEpilogStart()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFIEpilogStart () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 185 of file AArch64WinCOFFStreamer.cpp.
References llvm::MCTargetStreamer::getStreamer(), and S.
emitARM64WinCFIMachineFrame()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFIMachineFrame () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 214 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_PushMachFrame.
emitARM64WinCFINop()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFINop () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 161 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_Nop.
emitARM64WinCFIPACSignLR()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFIPACSignLR () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 226 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_PACSignLR.
emitARM64WinCFIPrologEnd()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFIPrologEnd () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 171 of file AArch64WinCOFFStreamer.cpp.
References llvm::MCTargetStreamer::getStreamer(), llvm::WinEH::FrameInfo::Instructions, it, llvm::WinEH::FrameInfo::PrologEnd, S, and llvm::Win64EH::UOP_End.
emitARM64WinCFISaveAnyRegD()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegD (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 240 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegD.
emitARM64WinCFISaveAnyRegDP()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegDP (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 245 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegDP.
emitARM64WinCFISaveAnyRegDPX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegDPX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 275 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegDPX.
emitARM64WinCFISaveAnyRegDX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegDX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 270 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegDX.
emitARM64WinCFISaveAnyRegI()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegI (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 230 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegI.
emitARM64WinCFISaveAnyRegIP()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegIP (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 235 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegIP.
emitARM64WinCFISaveAnyRegIPX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegIPX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 265 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegIPX.
emitARM64WinCFISaveAnyRegIX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegIX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 260 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegIX.
emitARM64WinCFISaveAnyRegQ()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegQ (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 250 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegQ.
emitARM64WinCFISaveAnyRegQP()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegQP (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 255 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegQP.
emitARM64WinCFISaveAnyRegQPX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegQPX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 285 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegQPX.
emitARM64WinCFISaveAnyRegQX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveAnyRegQX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 280 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveAnyRegQX.
emitARM64WinCFISaveFPLR()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveFPLR (int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 95 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveFPLR.
emitARM64WinCFISaveFPLRX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveFPLRX (int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 99 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveFPLRX.
emitARM64WinCFISaveFReg()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveFReg (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 130 of file AArch64WinCOFFStreamer.cpp.
References assert(), llvm::Offset, and llvm::Win64EH::UOP_SaveFReg.
emitARM64WinCFISaveFRegP()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveFRegP (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 142 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveFRegP.
emitARM64WinCFISaveFRegPX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveFRegPX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 147 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveFRegPX.
emitARM64WinCFISaveFRegX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveFRegX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 137 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveFRegX.
emitARM64WinCFISaveLRPair()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveLRPair (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 125 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveLRPair.
emitARM64WinCFISaveNext()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveNext () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 165 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_SaveNext.
emitARM64WinCFISaveR19R20X()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveR19R20X (int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 91 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveR19R20X.
emitARM64WinCFISaveReg()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveReg (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 103 of file AArch64WinCOFFStreamer.cpp.
References assert(), llvm::Offset, and llvm::Win64EH::UOP_SaveReg.
emitARM64WinCFISaveRegP()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveRegP (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 115 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveRegP.
emitARM64WinCFISaveRegPX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveRegPX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 120 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveRegPX.
emitARM64WinCFISaveRegX()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveRegX (unsigned Reg, int Offset) override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 110 of file AArch64WinCOFFStreamer.cpp.
References llvm::Offset, and llvm::Win64EH::UOP_SaveRegX.
emitARM64WinCFISetFP()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFISetFP () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 152 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_SetFP.
emitARM64WinCFITrapFrame()
void AArch64TargetWinCOFFStreamer::emitARM64WinCFITrapFrame () override virtual
Reimplemented from llvm::AArch64TargetStreamer.
Definition at line 210 of file AArch64WinCOFFStreamer.cpp.
References llvm::Win64EH::UOP_TrapFrame.
The documentation for this class was generated from the following files:
lib/Target/AArch64/MCTargetDesc/AArch64TargetStreamer.h
lib/Target/AArch64/MCTargetDesc/AArch64WinCOFFStreamer.cpp