LLVM: llvm::VEInstrInfo Class Reference
llvm::VEInstrInfo Class Reference
#include "Target/VE/VEInstrInfo.h"
Public Member Functions
VEInstrInfo (VESubtarget &ST)
const VERegisterInfo & getRegisterInfo () const
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify=false) const override
Branch Analysis & Modification {.
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
} Branch Analysis & Modification
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
Stack Spill & Reload {.
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
isStoreToStackSlot - If the specified machine instruction is a direct store to a stack slot, return the virtual or physical register number of the source reg along with the FrameIndex of the loaded stack slot.
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, Register SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, Register DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg) const override
bool FoldImmediate (MachineInstr &UseMI, MachineInstr &DefMI, Register Reg, MachineRegisterInfo *MRI) const override
} Stack Spill & Reload
Register getGlobalBaseReg (MachineFunction *MF) const
} Optimization
bool expandPostRAPseudo (MachineInstr &MI) const override
bool expandExtendStackPseudo (MachineInstr &MI) const
bool expandGetStackTopPseudo (MachineInstr &MI) const
Detailed Description
Definition at line 51 of file VEInstrInfo.h.
Constructor & Destructor Documentation
VEInstrInfo()
VEInstrInfo::VEInstrInfo (VESubtarget & ST) explicit
Definition at line 38 of file VEInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool VEInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify = false) const override
Branch Analysis & Modification {.
Definition at line 145 of file VEInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), Cond, llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), I, llvm::isCondBranchOpcode(), llvm::isIndirectBranchOpcode(), llvm::isUncondBranchOpcode(), MBB, parseCondBranch(), and TBB.
copyPhysReg()
void VEInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
} Branch Analysis & Modification
Definition at line 359 of file VEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstr::addRegisterKilled(), llvm::BuildMI(), contains(), copyPhysSubRegs(), llvm::dbgs(), DL, llvm::get(), llvm::MachineInstrBuilder::getInstr(), llvm::getKillRegState(), getRegisterInfo(), llvm::TargetRegisterInfo::getSubReg(), I, IsAliasOfSX(), llvm_unreachable, llvm::M1(), MBB, llvm::printReg(), and TRI.
expandExtendStackPseudo()
bool VEInstrInfo::expandExtendStackPseudo (MachineInstr & MI) const
Definition at line 997 of file VEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), BB, llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::VECC::CC_IGE, llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineBasicBlock::findDebugLoc(), llvm::VESubtarget::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::insert(), MBB, MI, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by expandPostRAPseudo().
expandGetStackTopPseudo()
bool VEInstrInfo::expandGetStackTopPseudo (MachineInstr & MI) const
Definition at line 1081 of file VEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineFrameInfo::adjustsStack(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::findDebugLoc(), llvm::VESubtarget::getAdjustedFrameSize(), llvm::MachineFunction::getFrameInfo(), llvm::VESubtarget::getFrameLowering(), llvm::VESubtarget::getInstrInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::VEFrameLowering::hasReservedCallFrame(), MBB, MI, and TII.
Referenced by expandPostRAPseudo().
expandPostRAPseudo()
bool VEInstrInfo::expandPostRAPseudo (MachineInstr & MI) const override
Definition at line 876 of file VEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstr::addRegisterKilled(), assert(), llvm::BuildMI(), DL, expandExtendStackPseudo(), expandGetStackTopPseudo(), expandPseudoLogM(), expandPseudoVFMK(), llvm::get(), llvm::MachineInstrBuilder::getInstr(), llvm::getKillRegState(), getRegisterInfo(), llvm::VEISD::GETSTACKTOP, getVM512Lower(), getVM512Upper(), llvm::RISCVMatInt::Imm, MBB, MI, and TRI.
FoldImmediate()
bool VEInstrInfo::FoldImmediate (MachineInstr & UseMI, MachineInstr & DefMI, Register Reg, MachineRegisterInfo * MRI) const override
} Stack Spill & Reload
Optimization {
Definition at line 578 of file VEInstrInfo.cpp.
References llvm::ISD::AND, assert(), llvm::dbgs(), DefMI, llvm::get(), llvm::MachineInstrBuilder::getReg(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), INSTRKIND, llvm::isMImmVal(), LLVM_DEBUG, llvm::mimm2Val(), MRI, NCINSTRKIND, llvm::ISD::OR, UseMI, llvm::val2MImm(), and llvm::ISD::XOR.
getGlobalBaseReg()
Register VEInstrInfo::getGlobalBaseReg (MachineFunction * MF) const
} Optimization
Definition at line 756 of file VEInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineFunction::front(), llvm::get(), llvm::VEMachineFunctionInfo::getGlobalBaseReg(), llvm::MachineFunction::getInfo(), llvm::PPCISD::GlobalBaseReg, MBBI, and llvm::VEMachineFunctionInfo::setGlobalBaseReg().
Referenced by llvm::VETargetLowering::LowerCall(), and llvm::VETargetLowering::lowerToTLSGeneralDynamicModel().
getRegisterInfo()
const VERegisterInfo& llvm::VEInstrInfo::getRegisterInfo () const inline
getRegisterInfo - TargetInstrInfo is a superset of MRegister info.
As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 62 of file VEInstrInfo.h.
Referenced by copyPhysReg(), expandPostRAPseudo(), and insertBranch().
insertBranch()
unsigned VEInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 226 of file VEInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), Cond, DL, llvm::get(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getRegisterInfo(), llvm::TargetRegisterInfo::getRegSizeInBits(), isImm(), IsIntegerCC(), isReg(), MBB, MRI, TBB, and TRI.
isLoadFromStackSlot()
unsigned VEInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Stack Spill & Reload {.
isLoadFromStackSlot - If the specified machine instruction is a direct load from a stack slot, return the virtual or physical register number of the destination along with the FrameIndex of the loaded stack slot.
If not, return 0. This predicate must return 0 if the instruction has any side effects other than loading from the stack slot.
Definition at line 416 of file VEInstrInfo.cpp.
References llvm::ISD::FrameIndex, and MI.
isStoreToStackSlot()
unsigned VEInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
isStoreToStackSlot - If the specified machine instruction is a direct store to a stack slot, return the virtual or physical register number of the source reg along with the FrameIndex of the loaded stack slot.
If not, return 0. This predicate must return 0 if the instruction has any side effects other than storing to the stack slot.
Definition at line 440 of file VEInstrInfo.cpp.
References llvm::ISD::FrameIndex, and MI.
loadRegFromStackSlot()
void VEInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, Register DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg) const override
Definition at line 522 of file VEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::end(), llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), I, MBB, llvm::MachineMemOperand::MOLoad, and llvm::report_fatal_error().
removeBranch()
unsigned VEInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 291 of file VEInstrInfo.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), I, llvm::isCondBranchOpcode(), llvm::isUncondBranchOpcode(), and MBB.
reverseBranchCondition()
bool VEInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 314 of file VEInstrInfo.cpp.
References CC, Cond, and GetOppositeBranchCondition().
storeRegToStackSlot()
void VEInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, Register SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg) const override
Definition at line 459 of file VEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::end(), llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), I, MBB, llvm::MachineMemOperand::MOStore, and llvm::report_fatal_error().
The documentation for this class was generated from the following files:
lib/Target/VE/VEInstrInfo.h
lib/Target/VE/VEInstrInfo.cpp