LLVM: llvm::SystemZELFRegisters Class Reference
llvm::SystemZELFRegisters Class Reference
ELF calling convention specific use registers Particular when on zLinux in 64 bit mode.
#include "Target/SystemZ/SystemZRegisterInfo.h"
Public Member Functions
int getReturnFunctionAddressRegister () final
int getStackPointerRegister () final
int getFramePointerRegister () final
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const final
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const final
int getCallFrameSize () final
int getStackPointerBias () final
~SystemZELFRegisters ()=default
Destroys the object. Bogus destructor overriding base class destructor.
Public Member Functions inherited from llvm::SystemZCallingConventionRegisters
virtual ~SystemZCallingConventionRegisters ()=default
Destroys the object.
Detailed Description
ELF calling convention specific use registers Particular when on zLinux in 64 bit mode.
Definition at line 107 of file SystemZRegisterInfo.h.
Constructor & Destructor Documentation
~SystemZELFRegisters()
llvm::SystemZELFRegisters::~SystemZELFRegisters () default
Destroys the object. Bogus destructor overriding base class destructor.
Member Function Documentation
getCalleeSavedRegs()
const MCPhysReg * SystemZELFRegisters::getCalleeSavedRegs (const MachineFunction * MF) const final virtual
Returns
an array of all the callee saved registers.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 198 of file SystemZRegisterInfo.cpp.
References llvm::CallingConv::AnyReg, llvm::Function::getAttributes(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::CallingConv::GHC, llvm::AttributeList::hasAttrSomewhere(), and llvm::TargetLowering::supportSwiftError().
getCallFrameSize()
int llvm::SystemZELFRegisters::getCallFrameSize () inline final virtual
Returns
the offset to the locals area.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 120 of file SystemZRegisterInfo.h.
References llvm::SystemZMC::ELFCallFrameSize.
getCallPreservedMask()
const uint32_t * SystemZELFRegisters::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const final virtual
Returns
the mask of all the call preserved registers.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 221 of file SystemZRegisterInfo.cpp.
References llvm::CallingConv::AnyReg, CC, llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::CallingConv::GHC, llvm::AttributeList::hasAttrSomewhere(), and llvm::TargetLowering::supportSwiftError().
getFramePointerRegister()
int llvm::SystemZELFRegisters::getFramePointerRegister () inline final virtual
Returns
the register that keeps the frame pointer address.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 113 of file SystemZRegisterInfo.h.
getReturnFunctionAddressRegister()
int llvm::SystemZELFRegisters::getReturnFunctionAddressRegister () inline final virtual
Returns
the register that keeps the return function address.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 109 of file SystemZRegisterInfo.h.
getStackPointerBias()
int llvm::SystemZELFRegisters::getStackPointerBias () inline final virtual
Returns
the stack pointer bias.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 122 of file SystemZRegisterInfo.h.
getStackPointerRegister()
int llvm::SystemZELFRegisters::getStackPointerRegister () inline final virtual
Returns
the register that keeps the stack pointer address.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 111 of file SystemZRegisterInfo.h.
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZRegisterInfo.h
lib/Target/SystemZ/SystemZRegisterInfo.cpp