LLVM: llvm::PrologEpilogSGPRSpillBuilder Class Reference
llvm::PrologEpilogSGPRSpillBuilder Class Reference
Public Member Functions
PrologEpilogSGPRSpillBuilder (Register Reg, const PrologEpilogSGPRSaveRestoreInfo SI, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, const SIInstrInfo *TII, const SIRegisterInfo &TRI, LivePhysRegs &LiveRegs, Register FrameReg)
void save ()
void restore ()
Detailed Description
Definition at line 214 of file SIFrameLowering.cpp.
Constructor & Destructor Documentation
PrologEpilogSGPRSpillBuilder()
llvm::PrologEpilogSGPRSpillBuilder::PrologEpilogSGPRSpillBuilder (Register Reg, const PrologEpilogSGPRSaveRestoreInfo SI, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, const SIInstrInfo * TII, const SIRegisterInfo & TRI, LivePhysRegs & LiveRegs, Register FrameReg) inline
Definition at line 326 of file SIFrameLowering.cpp.
References assert(), DL, llvm::ArrayRef< T >::empty(), llvm::TargetRegisterInfo::getPhysRegBaseClass(), llvm::M0(), MBB, MI, SI, llvm::ArrayRef< T >::size(), TII, and TRI.
Member Function Documentation
restore()
void llvm::PrologEpilogSGPRSpillBuilder::restore () inline
Definition at line 355 of file SIFrameLowering.cpp.
References llvm::COPY_TO_SCRATCH_SGPR, SI, llvm::SPILL_TO_MEM, and llvm::SPILL_TO_VGPR_LANE.
Referenced by llvm::SIFrameLowering::emitCSRSpillRestores().
save()
void llvm::PrologEpilogSGPRSpillBuilder::save () inline
Definition at line 344 of file SIFrameLowering.cpp.
References llvm::COPY_TO_SCRATCH_SGPR, SI, llvm::SPILL_TO_MEM, and llvm::SPILL_TO_VGPR_LANE.
Referenced by llvm::SIFrameLowering::emitCSRSpillStores(), and llvm::SIFrameLowering::emitPrologue().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/SIFrameLowering.cpp