LLVM: LiveDebugValues::LocIdx Class Reference
LiveDebugValues::LocIdx Class Reference
Handle-class for a particular "location".
#include "CodeGen/LiveDebugValues/InstrRefBasedImpl.h"
Public Member Functions
LocIdx (unsigned L)
bool isIllegal () const
uint64_t asU64 () const
bool operator== (unsigned L) const
bool operator== (const LocIdx &L) const
bool operator!= (unsigned L) const
bool operator!= (const LocIdx &L) const
bool operator< (const LocIdx &Other) const
Static Public Member Functions
static LocIdx MakeIllegalLoc ()
static LocIdx MakeTombstoneLoc ()
Detailed Description
Handle-class for a particular "location".
This value-type uniquely symbolises a register or stack location, allowing manipulation of locations without concern for where that location is. Practically, this allows us to treat the state of the machine at a particular point as an array of values, rather than a map of values.
Definition at line 43 of file InstrRefBasedImpl.h.
Constructor & Destructor Documentation
LocIdx()
LiveDebugValues::LocIdx::LocIdx (unsigned L) inline
Definition at line 52 of file InstrRefBasedImpl.h.
References assert(), and NUM_LOC_BITS.
Member Function Documentation
asU64()
uint64_t LiveDebugValues::LocIdx::asU64 () const inline
Definition at line 65 of file InstrRefBasedImpl.h.
Referenced by TransferTracker::clobberMloc(), llvm::DenseMapInfo< LocIdx >::getHashValue(), TransferTracker::loadInlocs(), LiveDebugValues::LocIdxToIndexFunctor::operator()(), LiveDebugValues::MLocTracker::MLocIterator::operator++(), LiveDebugValues::MLocTracker::readMLoc(), TransferTracker::redefVar(), LiveDebugValues::MLocTracker::setMLoc(), and LiveDebugValues::ValueIDNum::ValueIDNum().
isIllegal()
bool LiveDebugValues::LocIdx::isIllegal () const inline
Definition at line 63 of file InstrRefBasedImpl.h.
Referenced by TransferTracker::checkInstForNewValues(), TransferTracker::getLocQualityIfBetter(), and LiveDebugValues::MLocTracker::isRegisterTracked().
MakeIllegalLoc()
static LocIdx LiveDebugValues::LocIdx::MakeIllegalLoc () inline static
Definition at line 56 of file InstrRefBasedImpl.h.
Referenced by LiveDebugValues::MLocTracker::clear(), TransferTracker::clobberMloc(), llvm::DenseMapInfo< LocIdx >::getEmptyKey(), TransferTracker::LocationAndQuality::getLoc(), and LiveDebugValues::MLocTracker::MLocTracker().
MakeTombstoneLoc()
static LocIdx LiveDebugValues::LocIdx::MakeTombstoneLoc () inline static
Definition at line 57 of file InstrRefBasedImpl.h.
Referenced by llvm::DenseMapInfo< LocIdx >::getTombstoneKey().
operator!=() [1/2]
bool LiveDebugValues::LocIdx::operator!= (const LocIdx & L) const inline
Definition at line 73 of file InstrRefBasedImpl.h.
operator!=() [2/2]
bool LiveDebugValues::LocIdx::operator!= (unsigned L) const inline
Definition at line 71 of file InstrRefBasedImpl.h.
operator<()
bool LiveDebugValues::LocIdx::operator< (const LocIdx & Other) const inline
Definition at line 75 of file InstrRefBasedImpl.h.
References Other.
operator==() [1/2]
bool LiveDebugValues::LocIdx::operator== (const LocIdx & L) const inline
Definition at line 69 of file InstrRefBasedImpl.h.
operator==() [2/2]
bool LiveDebugValues::LocIdx::operator== (unsigned L) const inline
Definition at line 67 of file InstrRefBasedImpl.h.
The documentation for this class was generated from the following file:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.h