LLVM: llvm::TernOpInit Class Reference
llvm::TernOpInit Class Reference
!op (X, Y, Z) - Combine two inits.
#include "llvm/TableGen/Record.h"
Public Types
enum TernaryOp : uint8_t {
SUBST, FOREACH, FILTER, IF,
DAG, SUBSTR, FIND
}
Public Member Functions
TernOpInit (const TernOpInit &)=delete
TernOpInit & operator= (const TernOpInit &)=delete
void Profile (FoldingSetNodeID &ID) const
OpInit * clone (ArrayRef< Init * > Operands) const override
unsigned getNumOperands () const override
Init * getOperand (unsigned i) const override
TernaryOp getOpcode () const
Init * getLHS () const
Init * getMHS () const
Init * getRHS () const
Init * Fold (Record *CurRec) const
bool isComplete () const override
Is this a complete value with no unset (uninitialized) subvalues?
Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
std::string getAsString () const override
Convert this value to a literal form.
Public Member Functions inherited from llvm::OpInit
OpInit (const OpInit &)=delete
OpInit & operator= (OpInit &)=delete
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This function is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static TernOpInit * get (TernaryOp opc, Init *lhs, Init *mhs, Init *rhs, RecTy *Type)
Static Public Member Functions inherited from llvm::OpInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First, IK_FirstTypedInit, IK_BitInit, IK_BitsInit,
IK_DagInit, IK_DefInit, IK_FieldInit, IK_IntInit,
IK_ListInit, IK_FirstOpInit, IK_BinOpInit, IK_TernOpInit,
IK_UnOpInit, IK_LastOpInit, IK_CondOpInit, IK_FoldOpInit,
IK_IsAOpInit, IK_ExistsOpInit, IK_AnonymousNameInit, IK_StringInit,
IK_VarInit, IK_VarListElementInit, IK_VarBitInit, IK_VarDefInit,
IK_LastTypedInit, IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::OpInit
OpInit (InitKind K, RecTy *Type, uint8_t Opc)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
!op (X, Y, Z) - Combine two inits.
Definition at line 916 of file Record.h.
Member Enumeration Documentation
TernaryOp
enum llvm::TernOpInit::TernaryOp : uint8_t
Enumerator
SUBST
FOREACH
FILTER
IF
DAG
SUBSTR
FIND
Definition at line 918 of file Record.h.
Constructor & Destructor Documentation
TernOpInit()
llvm::TernOpInit::TernOpInit (const TernOpInit &) delete
Member Function Documentation
classof()
static bool llvm::TernOpInit::classof (const Init * I) inline static
Definition at line 931 of file Record.h.
References I, and llvm::Init::IK_TernOpInit.
clone()
OpInit* llvm::TernOpInit::clone (ArrayRef< Init * > Operands) const inline override virtual
Implements llvm::OpInit.
Definition at line 942 of file Record.h.
References assert(), get(), getOpcode(), llvm::TypedInit::getType(), and Operands.
Fold()
Init * TernOpInit::Fold (Record * CurRec) const
Definition at line 1433 of file Record.cpp.
References llvm::Init::convertInitializerTo(), DAG, FILTER, FilterHelper(), llvm::StringRef::find(), FIND, FOREACH, ForeachHelper(), llvm::IntRecTy::get(), llvm::UnsetInit::get(), llvm::IntInit::get(), llvm::StringInit::get(), llvm::VarInit::get(), llvm::DefInit::get(), llvm::DagInit::get(), llvm::VarInit::getAsString(), llvm::DefInit::getAsString(), llvm::DefInit::getDef(), llvm::ListInit::getElement(), llvm::StringInit::getFormat(), llvm::Record::getLoc(), llvm::VarInit::getName(), getOpcode(), llvm::TypedInit::getRecordKeeper(), llvm::TypedInit::getType(), llvm::IntInit::getValue(), llvm::StringInit::getValue(), i, I, IF, llvm::Length, llvm::FoldingSetBase::Node::Node(), llvm::PrintError(), llvm::StringRef::size(), llvm::ListInit::size(), SUBST, llvm::StringRef::substr(), SUBSTR, and llvm::to_string().
get()
TernOpInit * TernOpInit::get (TernaryOp opc, Init * lhs, Init * mhs, Init * rhs, RecTy * Type) static
Definition at line 1334 of file Record.cpp.
References llvm::detail::RecordKeeperImpl::Allocator, I, LHS, llvm::Init::Opc, ProfileTernOpInit(), RHS, and llvm::detail::RecordKeeperImpl::TheTernOpInitPool.
Referenced by clone(), and resolveReferences().
getAsString()
std::string TernOpInit::getAsString () const override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 1601 of file Record.cpp.
References DAG, FILTER, FIND, FOREACH, llvm::Init::getAsString(), llvm::Init::getAsUnquotedString(), getOpcode(), IF, SUBST, and SUBSTR.
getLHS()
Init* llvm::TernOpInit::getLHS () const inline
Definition at line 960 of file Record.h.
References LHS.
Referenced by getOperand(), and Profile().
getMHS()
Init* llvm::TernOpInit::getMHS () const inline
Definition at line 961 of file Record.h.
Referenced by getOperand(), and Profile().
getNumOperands()
unsigned llvm::TernOpInit::getNumOperands () const inline override virtual
Implements llvm::OpInit.
Definition at line 949 of file Record.h.
getOpcode()
TernaryOp llvm::TernOpInit::getOpcode () const inline
Definition at line 959 of file Record.h.
References llvm::Init::Opc.
Referenced by clone(), Fold(), getAsString(), Profile(), and resolveReferences().
getOperand()
Init* llvm::TernOpInit::getOperand (unsigned i) const inline override virtual
Implements llvm::OpInit.
Definition at line 950 of file Record.h.
References getLHS(), getMHS(), getRHS(), i, and llvm_unreachable.
getRHS()
Init* llvm::TernOpInit::getRHS () const inline
Definition at line 962 of file Record.h.
References RHS.
Referenced by getOperand(), and Profile().
isComplete()
bool llvm::TernOpInit::isComplete () const inline override virtual
Is this a complete value with no unset (uninitialized) subvalues?
Reimplemented from llvm::Init.
Definition at line 968 of file Record.h.
References llvm::Init::isComplete(), LHS, and RHS.
operator=()
TernOpInit& llvm::TernOpInit::operator= (const TernOpInit &) delete
Profile()
void TernOpInit::Profile (FoldingSetNodeID & ID) const
Definition at line 1349 of file Record.cpp.
References getLHS(), getMHS(), getOpcode(), getRHS(), llvm::TypedInit::getType(), and ProfileTernOpInit().
resolveReferences()
Init * TernOpInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1571 of file Record.cpp.
References llvm::ShadowResolver::addShadow(), llvm::Init::convertInitializerTo(), FILTER, FOREACH, llvm::IntRecTy::get(), get(), getOpcode(), llvm::TypedInit::getRecordKeeper(), llvm::TypedInit::getType(), IF, and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp