LLVM: llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize > Class Template Reference
llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize > Class Template Reference
#include "llvm/ADT/CombinationGenerator.h"
Public Member Functions
CombinationGenerator (ArrayRef< choices_storage_type > VariablesChoices_)
size_t numCombinations () const
void generate (const function_ref< bool(ArrayRef< choice_type >)> Callback)
Detailed Description
template<typename choice_type, typename choices_storage_type, int variable_smallsize>
class llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >
Definition at line 40 of file CombinationGenerator.h.
Constructor & Destructor Documentation
CombinationGenerator()
template<typename choice_type , typename choices_storage_type , int variable_smallsize> llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >::CombinationGenerator (ArrayRef< choices_storage_type > VariablesChoices_) inline
Definition at line 117 of file CombinationGenerator.h.
References assert(), llvm::ArrayRef< T >::empty(), and llvm::for_each().
Member Function Documentation
generate()
template<typename choice_type , typename choices_storage_type , int variable_smallsize> void llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >::generate (const function_ref< bool(ArrayRef< choice_type >)> Callback) inline
Definition at line 141 of file CombinationGenerator.h.
numCombinations()
template<typename choice_type , typename choices_storage_type , int variable_smallsize> size_t llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >::numCombinations () const inline
Definition at line 130 of file CombinationGenerator.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/ADT/CombinationGenerator.h