LLVM: llvm::objcopy::elf::MutableSectionVisitor Class Reference
llvm::objcopy::elf::MutableSectionVisitor Class Reference abstract
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
virtual ~MutableSectionVisitor ()=default
virtual Error visit (Section &Sec)=0
virtual Error visit (OwnedDataSection &Sec)=0
virtual Error visit (StringTableSection &Sec)=0
virtual Error visit (SymbolTableSection &Sec)=0
virtual Error visit (RelocationSection &Sec)=0
virtual Error visit (DynamicRelocationSection &Sec)=0
virtual Error visit (GnuDebugLinkSection &Sec)=0
virtual Error visit (GroupSection &Sec)=0
virtual Error visit (SectionIndexSection &Sec)=0
virtual Error visit (CompressedSection &Sec)=0
virtual Error visit (DecompressedSection &Sec)=0
Detailed Description
Definition at line 90 of file ELFObject.h.
Constructor & Destructor Documentation
~MutableSectionVisitor()
virtual llvm::objcopy::elf::MutableSectionVisitor::~MutableSectionVisitor () virtual default
Member Function Documentation
visit() [1/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (CompressedSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
visit() [2/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (DecompressedSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
visit() [3/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (DynamicRelocationSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
visit() [4/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (GnuDebugLinkSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
visit() [5/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (GroupSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
visit() [6/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (OwnedDataSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
visit() [7/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (RelocationSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
visit() [8/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (Section & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
Referenced by llvm::objcopy::elf::Section::accept(), llvm::objcopy::elf::OwnedDataSection::accept(), llvm::objcopy::elf::CompressedSection::accept(), llvm::objcopy::elf::DecompressedSection::accept(), llvm::objcopy::elf::StringTableSection::accept(), llvm::objcopy::elf::SectionIndexSection::accept(), llvm::objcopy::elf::SymbolTableSection::accept(), llvm::objcopy::elf::RelocationSection::accept(), llvm::objcopy::elf::GroupSection::accept(), llvm::objcopy::elf::DynamicRelocationSection::accept(), and llvm::objcopy::elf::GnuDebugLinkSection::accept().
visit() [9/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (SectionIndexSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
visit() [10/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (StringTableSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
visit() [11/11]
virtual Error llvm::objcopy::elf::MutableSectionVisitor::visit (SymbolTableSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::ELFSectionSizer< ELFT >.
The documentation for this class was generated from the following file:
lib/ObjCopy/ELF/ELFObject.h