LLVM: llvm::pdb::SymbolGroup Class Reference
llvm::pdb::SymbolGroup Class Reference
#include "llvm/DebugInfo/PDB/Native/InputFile.h"
Public Member Functions
SymbolGroup (InputFile *File, uint32_t GroupIndex=0)
Expected< StringRef > getNameFromStringTable (uint32_t Offset) const
Expected< StringRef > getNameFromChecksums (uint32_t Offset) const
void formatFromFileName (LinePrinter &Printer, StringRef File, bool Append=false) const
void formatFromChecksumsOffset (LinePrinter &Printer, uint32_t Offset, bool Append=false) const
StringRef name () const
codeview::DebugSubsectionArray getDebugSubsections () const
const ModuleDebugStreamRef & getPdbModuleStream () const
const InputFile & getFile () const
InputFile & getFile ()
bool hasDebugStream () const
Friends
class SymbolGroupIterator
Detailed Description
Definition at line 90 of file InputFile.h.
Constructor & Destructor Documentation
SymbolGroup()
SymbolGroup::SymbolGroup (InputFile * File, uint32_t GroupIndex = 0) explicit
Definition at line 156 of file InputFile.cpp.
References llvm::codeview::StringsAndChecksumsRef::hasChecksums(), llvm::codeview::StringsAndChecksumsRef::hasStrings(), I, llvm::codeview::StringsAndChecksumsRef::initialize(), isDebugSSection(), S, and llvm::X86AS::SS.
Member Function Documentation
formatFromChecksumsOffset()
void SymbolGroup::formatFromChecksumsOffset (LinePrinter & Printer, uint32_t Offset, bool Append = false) const
Definition at line 271 of file InputFile.cpp.
References llvm::VarStreamArray< ValueType, Extractor >::at(), llvm::codeview::StringsAndChecksumsRef::checksums(), llvm::consumeError(), llvm::VarStreamArray< ValueType, Extractor >::end(), formatChecksumKind(), formatInternal(), llvm::codeview::DebugChecksumsSubsectionRef::getArray(), getNameFromStringTable(), llvm::codeview::StringsAndChecksumsRef::hasChecksums(), llvm::None, Printer, and llvm::symbolize::toHex().
formatFromFileName()
void SymbolGroup::formatFromFileName (LinePrinter & Printer, StringRef File, bool Append = false) const
Definition at line 258 of file InputFile.cpp.
References R600_InstFlag::FC, formatChecksumKind(), formatInternal(), Printer, and llvm::symbolize::toHex().
getDebugSubsections()
codeview::DebugSubsectionArray llvm::pdb::SymbolGroup::getDebugSubsections () const inline
Definition at line 107 of file InputFile.h.
Referenced by llvm::pdb::iterateModuleSubsections().
getFile() [1/2]
InputFile& llvm::pdb::SymbolGroup::getFile () inline
Definition at line 113 of file InputFile.h.
References llvm::ARMBuildAttrs::File.
getFile() [2/2]
const InputFile& llvm::pdb::SymbolGroup::getFile () const inline
Definition at line 112 of file InputFile.h.
References llvm::ARMBuildAttrs::File.
Referenced by isMyCode().
getNameFromChecksums()
Expected< StringRef > SymbolGroup::getNameFromChecksums (uint32_t Offset) const
Definition at line 238 of file InputFile.cpp.
References llvm::VarStreamArray< ValueType, Extractor >::at(), llvm::codeview::StringsAndChecksumsRef::checksums(), llvm::VarStreamArray< ValueType, Extractor >::end(), llvm::codeview::DebugChecksumsSubsectionRef::getArray(), getNameFromStringTable(), llvm::codeview::StringsAndChecksumsRef::hasChecksums(), and move.
getNameFromStringTable()
Expected< StringRef > SymbolGroup::getNameFromStringTable (uint32_t Offset) const
Definition at line 234 of file InputFile.cpp.
References llvm::codeview::DebugStringTableSubsectionRef::getString(), and llvm::codeview::StringsAndChecksumsRef::strings().
Referenced by formatFromChecksumsOffset(), and getNameFromChecksums().
getPdbModuleStream()
const ModuleDebugStreamRef & SymbolGroup::getPdbModuleStream () const
Definition at line 229 of file InputFile.cpp.
References assert(), and llvm::pdb::InputFile::isPdb().
hasDebugStream()
bool llvm::pdb::SymbolGroup::hasDebugStream () const inline
Definition at line 115 of file InputFile.h.
name()
StringRef SymbolGroup::name () const
Definition at line 183 of file InputFile.cpp.
Referenced by isMyCode(), and llvm::pdb::iterateOneModule().
Friends And Related Function Documentation
SymbolGroupIterator
friend class SymbolGroupIterator friend
Definition at line 91 of file InputFile.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/InputFile.h
lib/DebugInfo/PDB/Native/InputFile.cpp