LLVM: llvm::SanitizerCoveragePass Class Reference
llvm::SanitizerCoveragePass Class Reference
This is the ModuleSanitizerCoverage pass used in the new pass manager.
#include "llvm/Transforms/Instrumentation/SanitizerCoverage.h"
Public Member Functions
SanitizerCoveragePass (SanitizerCoverageOptions Options=SanitizerCoverageOptions(), const std::vector< std::string > &AllowlistFiles=std::vector< std::string >(), const std::vector< std::string > &BlocklistFiles=std::vector< std::string >())
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< SanitizerCoveragePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< SanitizerCoveragePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
This is the ModuleSanitizerCoverage pass used in the new pass manager.
The pass instruments functions for coverage, adds initialization calls to the module for trace PC guards and 8bit counters if they are requested, and appends globals to llvm.compiler.used.
Definition at line 30 of file SanitizerCoverage.h.
Constructor & Destructor Documentation
SanitizerCoveragePass()
llvm::SanitizerCoveragePass::SanitizerCoveragePass (SanitizerCoverageOptions Options = SanitizerCoverageOptions(), const std::vector< std::string > & AllowlistFiles = std::vector<std::string>(), const std::vector< std::string > & BlocklistFiles = std::vector<std::string>()) inline explicit
Definition at line 32 of file SanitizerCoverage.h.
References llvm::SpecialCaseList::createOrDie(), and llvm::vfs::getRealFileSystem().
Member Function Documentation
isRequired()
static bool llvm::SanitizerCoveragePass::isRequired () inline static
Definition at line 47 of file SanitizerCoverage.h.
run()
PreservedAnalyses SanitizerCoveragePass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 294 of file SanitizerCoverage.cpp.
References llvm::PreservedAnalyses::abandon(), llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), M, MAM, llvm::PreservedAnalyses::none(), and Options.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/SanitizerCoverage.h
lib/Transforms/Instrumentation/SanitizerCoverage.cpp