LLVM: llvm::MachineModuleSlotTracker Class Reference
llvm::MachineModuleSlotTracker Class Reference
#include "llvm/CodeGen/MachineModuleSlotTracker.h"
Public Member Functions
MachineModuleSlotTracker (const MachineFunction *MF, bool ShouldInitializeAllMetadata=true)
~MachineModuleSlotTracker ()
void collectMachineMDNodes (MachineMDNodeListType &L) const
Public Member Functions inherited from llvm::ModuleSlotTracker
ModuleSlotTracker (SlotTracker &Machine, const Module *M, const Function *F=nullptr)
Wrap a preinitialized SlotTracker.
ModuleSlotTracker (const Module *M, bool ShouldInitializeAllMetadata=true)
Construct a slot tracker from a module.
virtual ~ModuleSlotTracker ()
Destructor to clean up storage.
SlotTracker * getMachine ()
Lazily creates a slot tracker.
const Module * getModule () const
const Function * getCurrentFunction () const
void incorporateFunction (const Function &F)
Incorporate the given function.
int getLocalSlot (const Value *V)
Return the slot number of the specified local value.
void setProcessHook (std::function< void(AbstractSlotTrackerStorage *, const Module *, bool)>)
void setProcessHook (std::function< void(AbstractSlotTrackerStorage *, const Function *, bool)>)
void collectMDNodes (MachineMDNodeListType &L, unsigned LB, unsigned UB) const
Additional Inherited Members
Public Types inherited from llvm::ModuleSlotTracker
using MachineMDNodeListType = std::vector< std::pair< unsigned, const MDNode * > >
Detailed Description
Definition at line 22 of file MachineModuleSlotTracker.h.
Constructor & Destructor Documentation
MachineModuleSlotTracker()
MachineModuleSlotTracker::MachineModuleSlotTracker (const MachineFunction * MF, bool ShouldInitializeAllMetadata = true)
Definition at line 65 of file MachineModuleSlotTracker.cpp.
References F, M, and llvm::ModuleSlotTracker::setProcessHook().
~MachineModuleSlotTracker()
MachineModuleSlotTracker::~MachineModuleSlotTracker () default
Member Function Documentation
collectMachineMDNodes()
void MachineModuleSlotTracker::collectMachineMDNodes (MachineMDNodeListType & L) const
Definition at line 60 of file MachineModuleSlotTracker.cpp.
References llvm::ModuleSlotTracker::collectMDNodes().
Referenced by llvm::MIRPrinter::convertMachineMetadataNodes().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleSlotTracker.h
lib/CodeGen/MachineModuleSlotTracker.cpp