LLVM: FunctionVarLocsBuilder Class Reference
FunctionVarLocsBuilder Class Reference
Helper class to build FunctionVarLocs, since that class isn't easy to modify.
Public Member Functions
VariableID insertVariable (DebugVariable V)
Find or insert V and return the ID.
const DebugVariable & getVariable (VariableID ID) const
Get a variable from its ID.
const SmallVectorImpl< VarLocInfo > * getWedge (const Instruction *Before) const
Return ptr to wedge of defs or nullptr if no defs come just before /p Before.
void setWedge (const Instruction *Before, SmallVector< VarLocInfo > &&Wedge)
Replace the defs that come just before /p Before with /p Wedge.
void addSingleLocVar (DebugVariable Var, DIExpression *Expr, DebugLoc DL, Value *V)
Add a def for a variable that is valid for its lifetime.
void addVarLoc (Instruction *Before, DebugVariable Var, DIExpression *Expr, DebugLoc DL, Value *V)
Add a def to the wedge of defs just before /p Before.
Detailed Description
Helper class to build FunctionVarLocs, since that class isn't easy to modify.
TODO: There's not a great deal of value in the split, it could be worth merging the two classes.
Definition at line 71 of file AssignmentTrackingAnalysis.cpp.
Member Function Documentation
addSingleLocVar()
void FunctionVarLocsBuilder::addSingleLocVar (DebugVariable Var, DIExpression * Expr, DebugLoc DL, Value * V) inline
Add a def for a variable that is valid for its lifetime.
Definition at line 107 of file AssignmentTrackingAnalysis.cpp.
References llvm::VarLocInfo::DL, DL, llvm::SmallVectorImpl< T >::emplace_back(), llvm::VarLocInfo::Expr, llvm::VarLocInfo::V, and llvm::VarLocInfo::VariableID.
Referenced by buildOverlapMapAndRecordDeclares().
addVarLoc()
void FunctionVarLocsBuilder::addVarLoc (Instruction * Before, DebugVariable Var, DIExpression * Expr, DebugLoc DL, Value * V) inline
Add a def to the wedge of defs just before /p Before.
Definition at line 118 of file AssignmentTrackingAnalysis.cpp.
References llvm::VarLocInfo::DL, DL, llvm::VarLocInfo::Expr, llvm::VarLocInfo::V, and llvm::VarLocInfo::VariableID.
getVariable()
const DebugVariable& FunctionVarLocsBuilder::getVariable (VariableID ID) const inline
Get a variable from its ID.
Definition at line 88 of file AssignmentTrackingAnalysis.cpp.
Referenced by removeRedundantDbgLocsUsingBackwardScan(), removeRedundantDbgLocsUsingForwardScan(), and removeUndefDbgLocsFromEntryBlock().
getWedge()
const SmallVectorImpl<VarLocInfo>* FunctionVarLocsBuilder::getWedge (const Instruction * Before) const inline
Return ptr to wedge of defs or nullptr if no defs come just before /p Before.
Definition at line 94 of file AssignmentTrackingAnalysis.cpp.
Referenced by removeRedundantDbgLocsUsingBackwardScan(), removeRedundantDbgLocsUsingForwardScan(), and removeUndefDbgLocsFromEntryBlock().
insertVariable()
VariableID FunctionVarLocsBuilder::insertVariable (DebugVariable V) inline
Find or insert V and return the ID.
Definition at line 83 of file AssignmentTrackingAnalysis.cpp.
References llvm::UniqueVector< T >::insert().
Referenced by buildOverlapMapAndRecordDeclares().
setWedge()
void FunctionVarLocsBuilder::setWedge (const Instruction * Before, SmallVector< VarLocInfo > && Wedge) inline
Replace the defs that come just before /p Before with /p Wedge.
Definition at line 102 of file AssignmentTrackingAnalysis.cpp.
References move.
Referenced by removeRedundantDbgLocsUsingBackwardScan(), removeRedundantDbgLocsUsingForwardScan(), and removeUndefDbgLocsFromEntryBlock().
The documentation for this class was generated from the following file:
lib/CodeGen/AssignmentTrackingAnalysis.cpp