LLVM: llvm::ImutAVLTreeGenericIterator< ImutInfo > Class Template Reference
llvm::ImutAVLTreeGenericIterator< ImutInfo > Class Template Reference
#include "llvm/ADT/ImmutableSet.h"
Public Types
enum VisitFlag { VisitedNone =0x0, VisitedLeft =0x1, VisitedRight =0x3, Flags =0x3 }
using iterator_category = std::bidirectional_iterator_tag
using value_type = ImutAVLTree< ImutInfo >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
using TreeTy = ImutAVLTree< ImutInfo >
Public Member Functions
ImutAVLTreeGenericIterator ()=default
ImutAVLTreeGenericIterator (const TreeTy *Root)
TreeTy & operator* () const
TreeTy * operator-> () const
uintptr_t getVisitState () const
bool atEnd () const
bool atBeginning () const
void skipToParent ()
bool operator== (const ImutAVLTreeGenericIterator &x) const
bool operator!= (const ImutAVLTreeGenericIterator &x) const
ImutAVLTreeGenericIterator & operator++ ()
ImutAVLTreeGenericIterator & operator-- ()
Detailed Description
template<typename ImutInfo>
class llvm::ImutAVLTreeGenericIterator< ImutInfo >
Definition at line 40 of file ImmutableSet.h.
Member Typedef Documentation
difference_type
template<typename ImutInfo > using llvm::ImutAVLTreeGenericIterator< ImutInfo >::difference_type = std::ptrdiff_t
Definition at line 647 of file ImmutableSet.h.
iterator_category
template<typename ImutInfo > using llvm::ImutAVLTreeGenericIterator< ImutInfo >::iterator_category = std::bidirectional_iterator_tag
Definition at line 645 of file ImmutableSet.h.
pointer
template<typename ImutInfo > using llvm::ImutAVLTreeGenericIterator< ImutInfo >::pointer = value_type *
Definition at line 648 of file ImmutableSet.h.
reference
template<typename ImutInfo > using llvm::ImutAVLTreeGenericIterator< ImutInfo >::reference = value_type &
Definition at line 649 of file ImmutableSet.h.
TreeTy
template<typename ImutInfo > using llvm::ImutAVLTreeGenericIterator< ImutInfo >::TreeTy = ImutAVLTree<ImutInfo>
Definition at line 654 of file ImmutableSet.h.
value_type
template<typename ImutInfo > using llvm::ImutAVLTreeGenericIterator< ImutInfo >::value_type = ImutAVLTree<ImutInfo>
Definition at line 646 of file ImmutableSet.h.
Member Enumeration Documentation
VisitFlag
template<typename ImutInfo > enum llvm::ImutAVLTreeGenericIterator::VisitFlag
Enumerator
VisitedNone
VisitedLeft
VisitedRight
Flags
Definition at line 651 of file ImmutableSet.h.
Constructor & Destructor Documentation
ImutAVLTreeGenericIterator() [1/2]
template<typename ImutInfo > llvm::ImutAVLTreeGenericIterator< ImutInfo >::ImutAVLTreeGenericIterator () default
ImutAVLTreeGenericIterator() [2/2]
template<typename ImutInfo > llvm::ImutAVLTreeGenericIterator< ImutInfo >::ImutAVLTreeGenericIterator (const TreeTy * Root) inline
Definition at line 657 of file ImmutableSet.h.
References stack.
Member Function Documentation
atBeginning()
template<typename ImutInfo > bool llvm::ImutAVLTreeGenericIterator< ImutInfo >::atBeginning () const inline
Definition at line 674 of file ImmutableSet.h.
References llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), stack, and llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedNone.
atEnd()
template<typename ImutInfo > bool llvm::ImutAVLTreeGenericIterator< ImutInfo >::atEnd () const inline
Definition at line 672 of file ImmutableSet.h.
References stack.
getVisitState()
template<typename ImutInfo > uintptr_t llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState () const inline
Definition at line 667 of file ImmutableSet.h.
References assert(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::Flags, and stack.
Referenced by llvm::ImutAVLTreeGenericIterator< ImutInfo >::atBeginning(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), and llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent().
operator!=()
template<typename ImutInfo > bool llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator!= (const ImutAVLTreeGenericIterator< ImutInfo > & x) const inline
Definition at line 699 of file ImmutableSet.h.
References x.
operator*()
template<typename ImutInfo > TreeTy& llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator* () const inline
Definition at line 661 of file ImmutableSet.h.
References assert(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::Flags, and stack.
operator++()
template<typename ImutInfo > ImutAVLTreeGenericIterator& llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++ () inline
Definition at line 703 of file ImmutableSet.h.
References assert(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::Flags, llvm::ImutAVLTree< ImutInfo >::getLeft(), llvm::ImutAVLTree< ImutInfo >::getRight(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm_unreachable, llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), stack, llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedLeft, llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedNone, and llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedRight.
operator--()
template<typename ImutInfo > ImutAVLTreeGenericIterator& llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator-- () inline
Definition at line 729 of file ImmutableSet.h.
References assert(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::Flags, llvm::ImutAVLTree< ImutInfo >::getLeft(), llvm::ImutAVLTree< ImutInfo >::getRight(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm_unreachable, stack, llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedLeft, llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedNone, and llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedRight.
operator->()
template<typename ImutInfo > TreeTy* llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator-> () const inline
Definition at line 665 of file ImmutableSet.h.
operator==()
template<typename ImutInfo > bool llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator== (const ImutAVLTreeGenericIterator< ImutInfo > & x) const inline
Definition at line 695 of file ImmutableSet.h.
References stack, and x.
skipToParent()
template<typename ImutInfo > void llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent () inline
Definition at line 678 of file ImmutableSet.h.
References assert(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm_unreachable, stack, llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedLeft, llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedNone, and llvm::ImutAVLTreeGenericIterator< ImutInfo >::VisitedRight.
Referenced by llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++().
The documentation for this class was generated from the following file:
include/llvm/ADT/ImmutableSet.h