LLVM: llvm::orc::shared::SPSSerializationTraits< SPSWrapperFunctionCall, WrapperFunctionCall > Class Reference
llvm::orc::shared::SPSSerializationTraits< SPSWrapperFunctionCall, WrapperFunctionCall > Class Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
Static Public Member Functions
static size_t size (const WrapperFunctionCall &WFC)
static bool serialize (SPSOutputBuffer &OB, const WrapperFunctionCall &WFC)
static bool deserialize (SPSInputBuffer &IB, WrapperFunctionCall &WFC)
Detailed Description
Definition at line 711 of file WrapperFunctionUtils.h.
Member Function Documentation
deserialize()
static bool llvm::orc::shared::SPSSerializationTraits< SPSWrapperFunctionCall, WrapperFunctionCall >::deserialize (SPSInputBuffer & IB, WrapperFunctionCall & WFC) inline static
Definition at line 723 of file WrapperFunctionUtils.h.
References llvm::AArch64PACKey::IB, and move.
serialize()
static bool llvm::orc::shared::SPSSerializationTraits< SPSWrapperFunctionCall, WrapperFunctionCall >::serialize (SPSOutputBuffer & OB, const WrapperFunctionCall & WFC) inline static
Definition at line 718 of file WrapperFunctionUtils.h.
References llvm::orc::shared::WrapperFunctionCall::getArgData(), llvm::orc::shared::WrapperFunctionCall::getCallee(), and llvm::X86II::OB.
size()
static size_t llvm::orc::shared::SPSSerializationTraits< SPSWrapperFunctionCall, WrapperFunctionCall >::size (const WrapperFunctionCall & WFC) inline static
Definition at line 713 of file WrapperFunctionUtils.h.
References llvm::orc::shared::WrapperFunctionCall::getArgData(), llvm::orc::shared::WrapperFunctionCall::getCallee(), and size.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h