LLVM: llvm::NVPTXRegisterInfo Class Reference
llvm::NVPTXRegisterInfo Class Reference
#include "Target/NVPTX/NVPTXRegisterInfo.h"
Public Member Functions
NVPTXRegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
NVPTX Callee Saved Registers.
BitVector getReservedRegs (const MachineFunction &MF) const override
bool eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
Register getFrameLocalRegister (const MachineFunction &MF) const
UniqueStringSaver & getStrPool () const
const char * getName (unsigned RegNo) const
Detailed Description
Definition at line 24 of file NVPTXRegisterInfo.h.
Constructor & Destructor Documentation
NVPTXRegisterInfo()
NVPTXRegisterInfo::NVPTXRegisterInfo ()
Definition at line 96 of file NVPTXRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
bool NVPTXRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 122 of file NVPTXRegisterInfo.cpp.
References assert(), llvm::ISD::FrameIndex, llvm::MachineFunction::getFrameInfo(), getFrameRegister(), llvm::MachineFrameInfo::getObjectOffset(), MI, and llvm::Offset.
getCalleeSavedRegs()
const MCPhysReg * NVPTXRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
NVPTX Callee Saved Registers.
Definition at line 104 of file NVPTXRegisterInfo.cpp.
getFrameLocalRegister()
Register NVPTXRegisterInfo::getFrameLocalRegister (const MachineFunction & MF) const
Definition at line 147 of file NVPTXRegisterInfo.cpp.
References llvm::MachineFunction::getTarget(), and TM.
Referenced by CombineCVTAToLocal(), and llvm::NVPTXFrameLowering::emitPrologue().
getFrameRegister()
Register NVPTXRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 140 of file NVPTXRegisterInfo.cpp.
References llvm::MachineFunction::getTarget(), and TM.
Referenced by eliminateFrameIndex(), llvm::NVPTXFrameLowering::emitPrologue(), and isCVTAToLocalCombinationCandidate().
getName()
const char* llvm::NVPTXRegisterInfo::getName (unsigned RegNo) const inline
Definition at line 53 of file NVPTXRegisterInfo.h.
References llvm::StringRef::data(), getStrPool(), llvm::RISCVFenceField::O, and llvm::UniqueStringSaver::save().
getReservedRegs()
BitVector NVPTXRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 109 of file NVPTXRegisterInfo.cpp.
References llvm::Reserved.
getStrPool()
UniqueStringSaver& llvm::NVPTXRegisterInfo::getStrPool () const inline
Definition at line 49 of file NVPTXRegisterInfo.h.
Referenced by getName().
The documentation for this class was generated from the following files:
lib/Target/NVPTX/NVPTXRegisterInfo.h
lib/Target/NVPTX/NVPTXRegisterInfo.cpp