LLVM: llvm::BTFKindVar Class Reference
llvm::BTFKindVar Class Reference
Handle variable instances.
#include "Target/BPF/BTFDebug.h"
Public Member Functions
BTFKindVar (StringRef VarName, uint32_t TypeId, uint32_t VarInfo)
uint32_t getSize () override
Get the size of this BTF type entry.
void completeType (BTFDebug &BDebug) override
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
void emitType (MCStreamer &OS) override
Emit types for this BTF type entry.
Public Member Functions inherited from llvm::BTFTypeBase
BTFTypeBase ()
virtual ~BTFTypeBase ()=default
void setId (uint32_t Id)
uint32_t getId ()
uint32_t roundupToBytes (uint32_t NumBits)
Additional Inherited Members
Protected Attributes inherited from llvm::BTFTypeBase
uint8_t Kind
bool IsCompleted
uint32_t Id
struct BTF::CommonType BTFType
Detailed Description
Handle variable instances.
Definition at line 170 of file BTFDebug.h.
Constructor & Destructor Documentation
BTFKindVar()
BTFKindVar::BTFKindVar (StringRef VarName, uint32_t TypeId, uint32_t VarInfo)
Definition at line 389 of file BTFDebug.cpp.
References llvm::BTFTypeBase::BTFType, Info, llvm::BTF::CommonType::Info, llvm::BTFTypeBase::Kind, and llvm::BTF::CommonType::Type.
Member Function Documentation
completeType()
void BTFKindVar::completeType (BTFDebug & BDebug) override virtual
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
Reimplemented from llvm::BTFTypeBase.
Definition at line 397 of file BTFDebug.cpp.
References llvm::BTFDebug::addString(), llvm::BTFTypeBase::BTFType, and llvm::BTF::CommonType::NameOff.
emitType()
void BTFKindVar::emitType (MCStreamer & OS) override virtual
Emit types for this BTF type entry.
Emit a BTF common type.
Reimplemented from llvm::BTFTypeBase.
Definition at line 401 of file BTFDebug.cpp.
References llvm::BTFTypeBase::emitType(), Info, and OS.
getSize()
uint32_t llvm::BTFKindVar::getSize () inline override virtual
Get the size of this BTF type entry.
Reimplemented from llvm::BTFTypeBase.
Definition at line 176 of file BTFDebug.h.
References llvm::BTFTypeBase::getSize().
The documentation for this class was generated from the following files:
lib/Target/BPF/BTFDebug.h
lib/Target/BPF/BTFDebug.cpp