LLVM: llvm::DOTMachineFuncInfo Class Reference
llvm::DOTMachineFuncInfo Class Reference
#include "llvm/CodeGen/MachineCFGPrinter.h"
Public Member Functions
DOTMachineFuncInfo (const MachineFunction *F)
const MachineFunction * getFunction () const
Detailed Description
Definition at line 20 of file MachineCFGPrinter.h.
Constructor & Destructor Documentation
DOTMachineFuncInfo()
llvm::DOTMachineFuncInfo::DOTMachineFuncInfo (const MachineFunction * F) inline
Definition at line 25 of file MachineCFGPrinter.h.
References F.
Member Function Documentation
getFunction()
const MachineFunction* llvm::DOTMachineFuncInfo::getFunction () const inline
Definition at line 27 of file MachineCFGPrinter.h.
Referenced by llvm::GraphTraits< DOTMachineFuncInfo * >::getEntryNode(), llvm::DOTGraphTraits< DOTMachineFuncInfo * >::getGraphName(), llvm::GraphTraits< DOTMachineFuncInfo * >::nodes_begin(), llvm::GraphTraits< DOTMachineFuncInfo * >::nodes_end(), and llvm::GraphTraits< DOTMachineFuncInfo * >::size().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineCFGPrinter.h