LLVM: llvm::vfs::RedirectingFileSystemParser Class Reference
llvm::vfs::RedirectingFileSystemParser Class Reference
A helper class to hold the common YAML parsing state.
Public Member Functions
RedirectingFileSystemParser (yaml::Stream &S)
bool parse (yaml::Node *Root, RedirectingFileSystem *FS)
Static Public Member Functions
static RedirectingFileSystem::Entry * lookupOrCreateEntry (RedirectingFileSystem *FS, StringRef Name, RedirectingFileSystem::Entry *ParentEntry=nullptr)
Detailed Description
A helper class to hold the common YAML parsing state.
Definition at line 1583 of file VirtualFileSystem.cpp.
Constructor & Destructor Documentation
RedirectingFileSystemParser()
llvm::vfs::RedirectingFileSystemParser::RedirectingFileSystemParser (yaml::Stream & S) inline
Definition at line 1997 of file VirtualFileSystem.cpp.
Member Function Documentation
lookupOrCreateEntry()
static RedirectingFileSystem::Entry* llvm::vfs::RedirectingFileSystemParser::lookupOrCreateEntry (RedirectingFileSystem * FS, StringRef Name, RedirectingFileSystem::Entry * ParentEntry = nullptr) inline static
Definition at line 1692 of file VirtualFileSystem.cpp.
References llvm::sys::fs::all_all, Content, E, llvm::X86AS::FS, llvm::vfs::getNextVirtualUniqueID(), llvm::make_range(), move, and now().
parse()
bool llvm::vfs::RedirectingFileSystemParser::parse (yaml::Node * Root, RedirectingFileSystem * FS) inline
Definition at line 2000 of file VirtualFileSystem.cpp.
References llvm::sys::path::begin(), E, llvm::sys::path::end(), llvm::yaml::Stream::failed(), llvm::vfs::RedirectingFileSystem::Fallthrough, llvm::X86AS::FS, llvm::StringRef::getAsInteger(), I, llvm_unreachable, move, llvm::vfs::RedirectingFileSystem::RedirectOnly, and llvm::IndexedInstrProf::Version.
The documentation for this class was generated from the following file:
lib/Support/VirtualFileSystem.cpp