LLVM: llvm::CSKYAsmBackend Class Reference
llvm::CSKYAsmBackend Class Reference
#include "Target/CSKY/MCTargetDesc/CSKYAsmBackend.h"
Public Member Functions
CSKYAsmBackend (const MCSubtargetInfo &STI, const MCTargetOptions &OP)
unsigned int getNumFixupKinds () const override
Get the number of target specific fixup kinds.
void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const override
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout) const override
Simple predicate for targets where !Resolved implies requiring relaxation.
void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const override
Relax the instruction in the given fragment to the next wider instruction.
bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const override
Check whether the given instruction may need relaxation.
bool fixupNeedsRelaxationAdvanced (const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout, const bool WasForced) const override
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const override
Write an (optimal) nop sequence of Count bytes to the given output.
bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target) override
Hook to check if a relocation is needed for some target specific reason.
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void emitInstructionBegin (MCObjectStreamer &OS, const MCInst &Inst, const MCSubtargetInfo &STI)
Give the target a chance to manipulate state related to instruction alignment (e.g.
virtual void emitInstructionEnd (MCObjectStreamer &OS, const MCInst &Inst)
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual void finishLayout (MCAssembler const &Asm, MCAsmLayout &Layout) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint32_t generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction >) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool isMicroMips (const MCSymbol *Sym) const
Check whether a given symbol has been flagged with MICROMIPS flag.
virtual std::optional< MCFixupKind > getFixupKind (StringRef Name) const
Map a relocation name used in .reloc to a fixup kind.
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, const MCAsmLayout &Layout, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual bool evaluateTargetFixup (const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFixup &Fixup, const MCFragment *DF, const MCValue &Target, uint64_t &Value, bool &WasForced)
virtual bool relaxDwarfLineAddr (MCDwarfLineAddrFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const
virtual bool relaxDwarfCFA (MCDwarfCallFrameFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const
Additional Inherited Members
Public Attributes inherited from llvm::MCAsmBackend
const support::endianness Endian
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (support::endianness Endian)
Detailed Description
Definition at line 19 of file CSKYAsmBackend.h.
Constructor & Destructor Documentation
CSKYAsmBackend()
llvm::CSKYAsmBackend::CSKYAsmBackend (const MCSubtargetInfo & STI, const MCTargetOptions & OP) inline
Definition at line 22 of file CSKYAsmBackend.h.
Member Function Documentation
applyFixup()
void CSKYAsmBackend::applyFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo * STI) const override virtual
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Errors (such as an out of range fixup value) should be reported via Ctx. The STI is present only for fragments of type MCRelaxableFragment and MCDataFragment with hasInstructions() == true.
Implements llvm::MCAsmBackend.
Definition at line 201 of file CSKYAsmBackend.cpp.
References adjustFixupValue(), llvm::alignTo(), llvm::HexStyle::Asm, assert(), llvm::Data, llvm::MCAsmBackend::Endian, llvm::FirstLiteralRelocationKind, llvm::FirstTargetFixupKind, Fixup, getFixupKindInfo(), I, Info, llvm::support::little, and llvm::Offset.
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > CSKYAsmBackend::createObjectTargetWriter () const override virtual
Implements llvm::MCAsmBackend.
Definition at line 24 of file CSKYAsmBackend.cpp.
References llvm::createCSKYELFObjectWriter().
fixupNeedsRelaxation()
bool CSKYAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout) const override virtual
Simple predicate for targets where !Resolved implies requiring relaxation.
Implements llvm::MCAsmBackend.
Definition at line 286 of file CSKYAsmBackend.cpp.
fixupNeedsRelaxationAdvanced()
bool CSKYAsmBackend::fixupNeedsRelaxationAdvanced (const MCFixup & Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout, const bool WasForced) const override virtual
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Reimplemented from llvm::MCAsmBackend.
Definition at line 174 of file CSKYAsmBackend.cpp.
References Fixup, llvm::CSKY::fixup_csky_pcrel_imm10_scale2, llvm::CSKY::fixup_csky_pcrel_imm16_scale2, llvm::CSKY::fixup_csky_pcrel_imm26_scale2, llvm::CSKY::fixup_csky_pcrel_uimm7_scale4, and llvm::Offset.
getFixupKindInfo()
const MCFixupKindInfo & CSKYAsmBackend::getFixupKindInfo (MCFixupKind Kind) const override virtual
Get information on a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 29 of file CSKYAsmBackend.cpp.
References assert(), llvm::FirstLiteralRelocationKind, llvm::FirstTargetFixupKind, llvm::CSKY::fixup_csky_addr32, llvm::CSKY::fixup_csky_addr_hi16, llvm::CSKY::fixup_csky_addr_lo16, llvm::CSKY::fixup_csky_doffset_imm18, llvm::CSKY::fixup_csky_doffset_imm18_scale2, llvm::CSKY::fixup_csky_doffset_imm18_scale4, llvm::CSKY::fixup_csky_got32, llvm::CSKY::fixup_csky_got_imm18_scale4, llvm::CSKY::fixup_csky_gotoff, llvm::CSKY::fixup_csky_gotpc, llvm::CSKY::fixup_csky_pcrel_imm10_scale2, llvm::CSKY::fixup_csky_pcrel_imm16_scale2, llvm::CSKY::fixup_csky_pcrel_imm18_scale2, llvm::CSKY::fixup_csky_pcrel_imm26_scale2, llvm::CSKY::fixup_csky_pcrel_uimm16_scale4, llvm::CSKY::fixup_csky_pcrel_uimm7_scale4, llvm::CSKY::fixup_csky_pcrel_uimm8_scale4, llvm::CSKY::fixup_csky_plt32, llvm::CSKY::fixup_csky_plt_imm18_scale4, llvm::FK_NONE, llvm::MCFixupKindInfo::FKF_IsAlignedDownTo32Bits, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), getNumFixupKinds(), llvm::CSKY::NumTargetFixupKinds, and llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::size().
Referenced by applyFixup().
getNumFixupKinds()
unsigned int llvm::CSKYAsmBackend::getNumFixupKinds () const inline override virtual
Get the number of target specific fixup kinds.
Implements llvm::MCAsmBackend.
Definition at line 25 of file CSKYAsmBackend.h.
References llvm::CSKY::NumTargetFixupKinds.
Referenced by getFixupKindInfo().
mayNeedRelaxation()
bool CSKYAsmBackend::mayNeedRelaxation (const MCInst & Inst, const MCSubtargetInfo & STI) const override virtual
Check whether the given instruction may need relaxation.
Parameters
Inst - The instruction to test.
STI - The MCSubtargetInfo in effect when the instruction was encoded.
Reimplemented from llvm::MCAsmBackend.
Definition at line 242 of file CSKYAsmBackend.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), and llvm::MCInst::getOpcode().
relaxInstruction()
void CSKYAsmBackend::relaxInstruction (MCInst & Inst, const MCSubtargetInfo & STI) const override virtual
Relax the instruction in the given fragment to the next wider instruction.
Parameters
[out] Inst The instruction to relax, which is also the relaxed instruction.
STI the subtarget information for the associated instruction.
Reimplemented from llvm::MCAsmBackend.
Definition at line 292 of file CSKYAsmBackend.cpp.
References llvm::MCInst::addOperand(), llvm::MCInst::dump(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), LLVM_DEBUG, llvm_unreachable, move, and llvm::MCInst::setOpcode().
shouldForceRelocation()
bool CSKYAsmBackend::shouldForceRelocation (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target) override virtual
Hook to check if a relocation is needed for some target specific reason.
Reimplemented from llvm::MCAsmBackend.
Definition at line 263 of file CSKYAsmBackend.cpp.
References llvm::FirstLiteralRelocationKind, Fixup, llvm::CSKY::fixup_csky_doffset_imm18, llvm::CSKY::fixup_csky_doffset_imm18_scale2, llvm::CSKY::fixup_csky_doffset_imm18_scale4, llvm::CSKY::fixup_csky_got32, llvm::CSKY::fixup_csky_got_imm18_scale4, llvm::CSKY::fixup_csky_gotoff, llvm::CSKY::fixup_csky_gotpc, llvm::CSKY::fixup_csky_plt32, and llvm::CSKY::fixup_csky_plt_imm18_scale4.
writeNopData()
bool CSKYAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const override virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implements llvm::MCAsmBackend.
Definition at line 347 of file CSKYAsmBackend.cpp.
References OS, and llvm::raw_ostream::write_zeros().
The documentation for this class was generated from the following files:
lib/Target/CSKY/MCTargetDesc/CSKYAsmBackend.h
lib/Target/CSKY/MCTargetDesc/CSKYAsmBackend.cpp