LLVM: llvm::ImmutableGraphBuilder< GraphT > Class Template Reference
llvm::ImmutableGraphBuilder< GraphT > Class Template Reference
#include "Target/X86/ImmutableGraph.h"
Public Types
using BuilderNodeRef = size_type
Public Member Functions
BuilderNodeRef addVertex (const node_value_type &V)
void addEdge (const edge_value_type &E, BuilderNodeRef From, BuilderNodeRef To)
bool empty () const
template<typename... ArgT>
std::unique_ptr< GraphT > get (ArgT &&... Args)
Static Public Member Functions
template<typename... ArgT>
static std::unique_ptr< GraphT > trim (const GraphT &G, const NodeSet &TrimNodes, const EdgeSet &TrimEdges, ArgT &&... Args)
Detailed Description
template<typename GraphT>
class llvm::ImmutableGraphBuilder< GraphT >
Definition at line 294 of file ImmutableGraph.h.
Member Typedef Documentation
BuilderNodeRef
template<typename GraphT > using llvm::ImmutableGraphBuilder< GraphT >::BuilderNodeRef = size_type
Definition at line 313 of file ImmutableGraph.h.
Member Function Documentation
addEdge()
template<typename GraphT > void llvm::ImmutableGraphBuilder< GraphT >::addEdge (const edge_value_type & E, BuilderNodeRef From, BuilderNodeRef To) inline
Definition at line 320 of file ImmutableGraph.h.
References E, and From.
addVertex()
template<typename GraphT > BuilderNodeRef llvm::ImmutableGraphBuilder< GraphT >::addVertex (const node_value_type & V) inline
Definition at line 315 of file ImmutableGraph.h.
References I.
empty()
template<typename GraphT > bool llvm::ImmutableGraphBuilder< GraphT >::empty () const inline
Definition at line 325 of file ImmutableGraph.h.
get()
template<typename GraphT > template<typename... ArgT> std::unique_ptr<GraphT> llvm::ImmutableGraphBuilder< GraphT >::get (ArgT &&... Args) inline
Definition at line 327 of file ImmutableGraph.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), E, move, llvm::BitVector::size(), and VI.
trim()
template<typename GraphT > template<typename... ArgT> static std::unique_ptr<GraphT> llvm::ImmutableGraphBuilder< GraphT >::trim (const GraphT & G, const NodeSet & TrimNodes, const EdgeSet & TrimEdges, ArgT &&... Args) inline static
Definition at line 354 of file ImmutableGraph.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), E, G, move, and N.
The documentation for this class was generated from the following file:
lib/Target/X86/ImmutableGraph.h