LLVM: llvm::object::ELFFile< ELFT > Class Template Reference
llvm::object::ELFFile< ELFT > Class Template Reference
#include "llvm/Object/ELF.h"
Public Types
using WarningHandler = llvm::function_ref< Error(const Twine &Msg)>
Public Member Functions
const uint8_t * base () const
const uint8_t * end () const
size_t getBufSize () const
const Elf_Ehdr & getHeader () const
template<typename T >
Expected< const T * > getEntry (uint32_t Section, uint32_t Entry) const
template<typename T >
Expected< const T * > getEntry (const Elf_Shdr &Section, uint32_t Entry) const
Expected< std::vector< VerDef > > getVersionDefinitions (const Elf_Shdr &Sec) const
Expected< std::vector< VerNeed > > getVersionDependencies (const Elf_Shdr &Sec, WarningHandler WarnHandler=&defaultWarningHandler) const
Expected< StringRef > getSymbolVersionByIndex (uint32_t SymbolVersionIndex, bool &IsDefault, SmallVector< std::optional< VersionEntry >, 0 > &VersionMap, std::optional< bool > IsSymHidden) const
Expected< StringRef > getStringTable (const Elf_Shdr &Section, WarningHandler WarnHandler=&defaultWarningHandler) const
Expected< StringRef > getStringTableForSymtab (const Elf_Shdr &Section) const
Expected< StringRef > getStringTableForSymtab (const Elf_Shdr &Section, Elf_Shdr_Range Sections) const
Expected< StringRef > getLinkAsStrtab (const typename ELFT::Shdr &Sec) const
Expected< ArrayRef< Elf_Word > > getSHNDXTable (const Elf_Shdr &Section) const
Expected< ArrayRef< Elf_Word > > getSHNDXTable (const Elf_Shdr &Section, Elf_Shdr_Range Sections) const
Expected< uint64_t > getDynSymtabSize () const
This function determines the number of dynamic symbols.
StringRef getRelocationTypeName (uint32_t Type) const
void getRelocationTypeName (uint32_t Type, SmallVectorImpl< char > &Result) const
uint32_t getRelativeRelocationType () const
std::string getDynamicTagAsString (unsigned Arch, uint64_t Type) const
std::string getDynamicTagAsString (uint64_t Type) const
Expected< const Elf_Sym * > getRelocationSymbol (const Elf_Rel &Rel, const Elf_Shdr *SymTab) const
Get the symbol for a given relocation.
Expected< SmallVector< std::optional< VersionEntry >, 0 > > loadVersionMap (const Elf_Shdr *VerNeedSec, const Elf_Shdr *VerDefSec) const
bool isLE () const
bool isMipsELF64 () const
bool isMips64EL () const
Expected< Elf_Shdr_Range > sections () const
Expected< Elf_Dyn_Range > dynamicEntries () const
Expected< const uint8_t * > toMappedAddr (uint64_t VAddr, WarningHandler WarnHandler=&defaultWarningHandler) const
Expected< Elf_Sym_Range > symbols (const Elf_Shdr *Sec) const
Expected< Elf_Rela_Range > relas (const Elf_Shdr &Sec) const
Expected< Elf_Rel_Range > rels (const Elf_Shdr &Sec) const
Expected< Elf_Relr_Range > relrs (const Elf_Shdr &Sec) const
std::vector< Elf_Rel > decode_relrs (Elf_Relr_Range relrs) const
Expected< std::vector< Elf_Rela > > android_relas (const Elf_Shdr &Sec) const
Expected< Elf_Phdr_Range > program_headers () const
Iterate over program header table.
Elf_Note_Iterator notes_begin (const Elf_Phdr &Phdr, Error &Err) const
Get an iterator over notes in a program header.
Elf_Note_Iterator notes_begin (const Elf_Shdr &Shdr, Error &Err) const
Get an iterator over notes in a section.
Elf_Note_Iterator notes_end () const
Get the end iterator for notes.
iterator_range< Elf_Note_Iterator > notes (const Elf_Phdr &Phdr, Error &Err) const
Get an iterator range over notes of a program header.
iterator_range< Elf_Note_Iterator > notes (const Elf_Shdr &Shdr, Error &Err) const
Get an iterator range over notes of a section.
Expected< StringRef > getSectionStringTable (Elf_Shdr_Range Sections, WarningHandler WarnHandler=&defaultWarningHandler) const
Expected< uint32_t > getSectionIndex (const Elf_Sym &Sym, Elf_Sym_Range Syms, DataRegion< Elf_Word > ShndxTable) const
Expected< const Elf_Shdr * > getSection (const Elf_Sym &Sym, const Elf_Shdr *SymTab, DataRegion< Elf_Word > ShndxTable) const
Expected< const Elf_Shdr * > getSection (const Elf_Sym &Sym, Elf_Sym_Range Symtab, DataRegion< Elf_Word > ShndxTable) const
Expected< const Elf_Shdr * > getSection (uint32_t Index) const
Expected< const Elf_Sym * > getSymbol (const Elf_Shdr *Sec, uint32_t Index) const
Expected< StringRef > getSectionName (const Elf_Shdr &Section, WarningHandler WarnHandler=&defaultWarningHandler) const
Expected< StringRef > getSectionName (const Elf_Shdr &Section, StringRef DotShstrtab) const
template<typename T >
Expected< ArrayRef< T > > getSectionContentsAsArray (const Elf_Shdr &Sec) const
Expected< ArrayRef< uint8_t > > getSectionContents (const Elf_Shdr &Sec) const
Expected< ArrayRef< uint8_t > > getSegmentContents (const Elf_Phdr &Phdr) const
Expected< std::vector< BBAddrMap > > decodeBBAddrMap (const Elf_Shdr &Sec) const
void createFakeSections ()
Used by llvm-objdump -d (which needs sections for disassembly) to disassemble objects without a section header table (e.g.
Static Public Member Functions
static Expected< ELFFile > create (StringRef Object)
Detailed Description
template<class ELFT>
class llvm::object::ELFFile< ELFT >
Definition at line 95 of file ELF.h.
Member Typedef Documentation
WarningHandler
template<class ELFT > using llvm::object::ELFFile< ELFT >::WarningHandler = llvm::function_ref<Error(const Twine &Msg)>
Definition at line 176 of file ELF.h.
Member Function Documentation
android_relas()
template<class ELFT > Expected< std::vector< typename ELFT::Rela > > ELFFile::android_relas (const Elf_Shdr & Sec) const
Definition at line 386 of file ELF.cpp.
References Content, llvm::object::createError(), llvm::Data, I, move, llvm::ELF::RELOCATION_GROUP_HAS_ADDEND_FLAG, llvm::ELF::RELOCATION_GROUPED_BY_ADDEND_FLAG, llvm::ELF::RELOCATION_GROUPED_BY_INFO_FLAG, llvm::ELF::RELOCATION_GROUPED_BY_OFFSET_DELTA_FLAG, llvm::DataExtractor::Cursor::takeError(), llvm::Expected< T >::takeError(), and uint64_t.
base()
template<class ELFT > const uint8_t* llvm::object::ELFFile< ELFT >::base () const inline
Definition at line 178 of file ELF.h.
References llvm::StringRef::bytes_begin().
Referenced by llvm::object::ELFFile< ELFT >::end(), llvm::object::ELFFile< ELFT >::getHeader(), and llvm::object::ELFFile< ELFT >::program_headers().
create()
template<class ELFT > Expected< ELFFile< ELFT > > llvm::object::ELFFile< ELFT >::create (StringRef Object) static
Definition at line 760 of file ELF.h.
References llvm::object::createError(), and llvm::Object.
Referenced by llvm::objcopy::elf::ELFBuilder< ELFT >::build(), llvm::object::ELFObjectFile< ELFT >::create(), and llvm::jitlink::readTargetMachineArch().
createFakeSections()
template<class ELFT > void llvm::object::ELFFile< ELFT >::createFakeSections
Used by llvm-objdump -d (which needs sections for disassembly) to disassemble objects without a section header table (e.g.
ET_CORE objects analyzed by linux perf or ET_EXEC with llvm-strip –strip-sections).
Definition at line 771 of file ELF.h.
References llvm::enumerate(), llvm::ELF::PF_X, llvm::ELF::PT_LOAD, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXECINSTR, and llvm::ELF::SHT_PROGBITS.
decode_relrs()
template<class ELFT > std::vector< typename ELFT::Rel > ELFFile::decode_relrs (Elf_Relr_Range relrs) const
Definition at line 322 of file ELF.cpp.
References Addr, llvm::sampleprof::Base, and uint.
decodeBBAddrMap()
template<class ELFT > Expected< std::vector< BBAddrMap > > ELFFile::decodeBBAddrMap (const Elf_Shdr & Sec) const
Definition at line 643 of file ELF.cpp.
References Content, llvm::object::createError(), llvm::Data, llvm::joinErrors(), move, llvm::ELF::SHT_LLVM_BB_ADDR_MAP, llvm::Error::success(), llvm::Expected< T >::takeError(), uint64_t, llvm::Twine::utohexstr(), and llvm::IndexedInstrProf::Version.
dynamicEntries()
template<class ELFT > Expected< typename ELFT::DynRange > ELFFile::dynamicEntries () const
Definition at line 543 of file ELF.cpp.
References llvm::ArrayRef(), llvm::ArrayRef< T >::back(), base, llvm::object::createError(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::empty(), llvm::ELF::PT_DYNAMIC, llvm::ELF::SHT_DYNAMIC, and llvm::Expected< T >::takeError().
end()
template<class ELFT > const uint8_t* llvm::object::ELFFile< ELFT >::end () const inline
Definition at line 179 of file ELF.h.
References llvm::object::ELFFile< ELFT >::base(), and llvm::object::ELFFile< ELFT >::getBufSize().
getBufSize()
template<class ELFT > size_t llvm::object::ELFFile< ELFT >::getBufSize () const inline
Definition at line 181 of file ELF.h.
References llvm::StringRef::size().
Referenced by llvm::object::ELFFile< ELFT >::end(), and llvm::object::ELFFile< ELFT >::program_headers().
getDynamicTagAsString() [1/2]
template<class ELFT > std::string ELFFile::getDynamicTagAsString (uint64_t Type) const
Definition at line 538 of file ELF.cpp.
getDynamicTagAsString() [2/2]
template<class ELFT > std::string ELFFile::getDynamicTagAsString (unsigned Arch, uint64_t Type) const
Definition at line 454 of file ELF.cpp.
References llvm::ELF::EM_AARCH64, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_MIPS, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, and llvm::ELF::EM_RISCV.
getDynSymtabSize()
template<class ELFT > Expected< uint64_t > llvm::object::ELFFile< ELFT >::getDynSymtabSize
This function determines the number of dynamic symbols.
It reads section headers first. If section headers are not available, the number of symbols will be inferred by parsing dynamic hash tables.
Definition at line 697 of file ELF.h.
References llvm::createStringError(), llvm::object::parse_failed, llvm::ELF::SHT_DYNSYM, and llvm::Expected< T >::takeError().
getEntry() [1/2]
template<class ELFT > template<typename T > Expected< const T * > llvm::object::ELFFile< ELFT >::getEntry (const Elf_Shdr & Section, uint32_t Entry) const
Definition at line 860 of file ELF.h.
getEntry() [2/2]
template<class ELFT > template<typename T > Expected< const T * > llvm::object::ELFFile< ELFT >::getEntry (uint32_t Section, uint32_t Entry) const
Definition at line 850 of file ELF.h.
getHeader()
template<class ELFT > const Elf_Ehdr& llvm::object::ELFFile< ELFT >::getHeader () const inline
Definition at line 191 of file ELF.h.
References llvm::object::ELFFile< ELFT >::base().
Referenced by llvm::object::describe(), llvm::object::ELFFile< ELFT >::isLE(), llvm::object::ELFFile< ELFT >::isMipsELF64(), llvm::jitlink::ELFLinkGraphBuilder< object::ELF64LE >::isRelocatable(), and llvm::object::ELFFile< ELFT >::program_headers().
getLinkAsStrtab()
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getLinkAsStrtab (const typename ELFT::Shdr & Sec) const
Definition at line 1178 of file ELF.h.
References llvm::object::createError(), llvm::object::describe(), llvm::object::getSection(), llvm::Expected< T >::takeError(), and llvm::toString().
getRelativeRelocationType()
template<class ELFT > uint32_t llvm::object::ELFFile< ELFT >::getRelativeRelocationType
Definition at line 585 of file ELF.h.
References llvm::object::getELFRelativeRelocationType().
getRelocationSymbol()
template<class ELFT > Expected< const typename ELFT::Sym * > llvm::object::ELFFile< ELFT >::getRelocationSymbol (const Elf_Rel & Rel, const Elf_Shdr * SymTab) const
Get the symbol for a given relocation.
Definition at line 628 of file ELF.h.
References isMips64EL().
getRelocationTypeName() [1/2]
template<class ELFT > StringRef llvm::object::ELFFile< ELFT >::getRelocationTypeName (uint32_t Type) const
Definition at line 549 of file ELF.h.
References llvm::object::getELFRelocationTypeName().
getRelocationTypeName() [2/2]
template<class ELFT > void llvm::object::ELFFile< ELFT >::getRelocationTypeName (uint32_t Type, SmallVectorImpl< char > & Result) const
Definition at line 554 of file ELF.h.
References Type2, and Type3.
getSection() [1/3]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (const Elf_Sym & Sym, const Elf_Shdr * SymTab, DataRegion< Elf_Word > ShndxTable) const
Definition at line 449 of file ELF.h.
References llvm::object::getSection(), and symbols.
getSection() [2/3]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (const Elf_Sym & Sym, Elf_Sym_Range Symtab, DataRegion< Elf_Word > ShndxTable) const
Definition at line 459 of file ELF.h.
References llvm::object::getSection().
getSection() [3/3]
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::ELFFile< ELFT >::getSection (uint32_t Index) const
Definition at line 1081 of file ELF.h.
getSectionContents()
template<class ELFT > Expected< ArrayRef< uint8_t > > llvm::object::ELFFile< ELFT >::getSectionContents (const Elf_Shdr & Sec) const
Definition at line 544 of file ELF.h.
getSectionContentsAsArray()
template<class ELFT > template<typename T > Expected< ArrayRef< T > > llvm::object::ELFFile< ELFT >::getSectionContentsAsArray (const Elf_Shdr & Sec) const
Definition at line 488 of file ELF.h.
References llvm::ArrayRef(), base, llvm::object::createError(), llvm::object::getSecIndexForError(), llvm::max(), T, and llvm::Twine::utohexstr().
getSectionIndex()
template<class ELFT > Expected< uint32_t > llvm::object::ELFFile< ELFT >::getSectionIndex (const Elf_Sym & Sym, Elf_Sym_Range Syms, DataRegion< Elf_Word > ShndxTable) const
Definition at line 432 of file ELF.h.
References Index, llvm::ELF::SHN_LORESERVE, llvm::ELF::SHN_UNDEF, llvm::ELF::SHN_XINDEX, and llvm::Expected< T >::takeError().
getSectionName() [1/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSectionName (const Elf_Shdr & Section, StringRef DotShstrtab) const
Definition at line 1207 of file ELF.h.
References llvm::object::createError(), llvm::StringRef::data(), llvm::object::getSecIndexForError(), llvm::StringRef::size(), and llvm::Twine::utohexstr().
getSectionName() [2/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSectionName (const Elf_Shdr & Section, WarningHandler WarnHandler = &defaultWarningHandler) const
Definition at line 1195 of file ELF.h.
getSectionStringTable()
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSectionStringTable (Elf_Shdr_Range Sections, WarningHandler WarnHandler = &defaultWarningHandler) const
Definition at line 638 of file ELF.h.
References llvm::object::createError(), and llvm::ELF::SHN_XINDEX.
getSegmentContents()
template<class ELFT > Expected< ArrayRef< uint8_t > > llvm::object::ELFFile< ELFT >::getSegmentContents (const Elf_Phdr & Phdr) const
Definition at line 524 of file ELF.h.
References llvm::ArrayRef(), base, llvm::object::createError(), llvm::object::getPhdrIndexForError(), llvm::max(), and llvm::Twine::utohexstr().
getSHNDXTable() [1/2]
template<class ELFT > Expected< ArrayRef< typename ELFT::Word > > llvm::object::ELFFile< ELFT >::getSHNDXTable (const Elf_Shdr & Section) const
Definition at line 1116 of file ELF.h.
getSHNDXTable() [2/2]
template<class ELFT > Expected< ArrayRef< typename ELFT::Word > > llvm::object::ELFFile< ELFT >::getSHNDXTable (const Elf_Shdr & Section, Elf_Shdr_Range Sections) const
Definition at line 1125 of file ELF.h.
References assert(), llvm::object::createError(), llvm::object::getELFSectionTypeName(), llvm::ELF::SHT_DYNSYM, llvm::ELF::SHT_SYMTAB, llvm::ELF::SHT_SYMTAB_SHNDX, llvm::ArrayRef< T >::size(), and uint64_t.
getStringTable()
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getStringTable (const Elf_Shdr & Section, WarningHandler WarnHandler = &defaultWarningHandler) const
Definition at line 1090 of file ELF.h.
References llvm::object::createError(), llvm::Data, E, llvm::object::getELFSectionTypeName(), llvm::object::getSecIndexForError(), move, and llvm::ELF::SHT_STRTAB.
getStringTableForSymtab() [1/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getStringTableForSymtab (const Elf_Shdr & Section) const
Definition at line 1154 of file ELF.h.
getStringTableForSymtab() [2/2]
template<class ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getStringTableForSymtab (const Elf_Shdr & Section, Elf_Shdr_Range Sections) const
Definition at line 1163 of file ELF.h.
References llvm::object::createError(), llvm::ELF::SHT_DYNSYM, llvm::ELF::SHT_SYMTAB, and llvm::Expected< T >::takeError().
getSymbol()
template<class ELFT > Expected< const typename ELFT::Sym * > llvm::object::ELFFile< ELFT >::getSymbol (const Elf_Shdr * Sec, uint32_t Index) const
Definition at line 472 of file ELF.h.
References llvm::object::createError(), llvm::object::getSecIndexForError(), Index, and symbols.
getSymbolVersionByIndex()
template<typename ELFT > Expected< StringRef > llvm::object::ELFFile< ELFT >::getSymbolVersionByIndex (uint32_t SymbolVersionIndex, bool & IsDefault, SmallVector< std::optional< VersionEntry >, 0 > & VersionMap, std::optional< bool > IsSymHidden) const
Definition at line 877 of file ELF.h.
References llvm::object::createError(), llvm::ELF::VER_NDX_GLOBAL, llvm::ELF::VER_NDX_LOCAL, and llvm::ELF::VERSYM_VERSION.
getVersionDefinitions()
template<class ELFT > Expected< std::vector< VerDef > > llvm::object::ELFFile< ELFT >::getVersionDefinitions (const Elf_Shdr & Sec) const
Definition at line 906 of file ELF.h.
References llvm::object::createError(), llvm::object::describe(), llvm::Expected< T >::takeError(), and llvm::toString().
getVersionDependencies()
template<class ELFT > Expected< std::vector< VerNeed > > llvm::object::ELFFile< ELFT >::getVersionDependencies (const Elf_Shdr & Sec, WarningHandler WarnHandler = &defaultWarningHandler) const
Definition at line 993 of file ELF.h.
References llvm::object::createError(), llvm::object::describe(), E, move, llvm::Expected< T >::takeError(), and llvm::toString().
isLE()
template<class ELFT > bool llvm::object::ELFFile< ELFT >::isLE () const inline
Definition at line 241 of file ELF.h.
References llvm::ELF::ELFDATA2LSB, and llvm::object::ELFFile< ELFT >::getHeader().
Referenced by llvm::object::ELFFile< ELFT >::isMips64EL().
isMips64EL()
template<class ELFT > bool llvm::object::ELFFile< ELFT >::isMips64EL () const inline
Definition at line 250 of file ELF.h.
References llvm::object::ELFFile< ELFT >::isLE(), and llvm::object::ELFFile< ELFT >::isMipsELF64().
isMipsELF64()
template<class ELFT > bool llvm::object::ELFFile< ELFT >::isMipsELF64 () const inline
Definition at line 245 of file ELF.h.
References llvm::ELF::ELFCLASS64, llvm::ELF::EM_MIPS, and llvm::object::ELFFile< ELFT >::getHeader().
Referenced by llvm::object::ELFFile< ELFT >::isMips64EL().
loadVersionMap()
template<class ELFT > Expected< SmallVector< std::optional< VersionEntry >, 0 > > llvm::object::ELFFile< ELFT >::loadVersionMap (const Elf_Shdr * VerNeedSec, const Elf_Shdr * VerDefSec) const
Definition at line 591 of file ELF.h.
References llvm::tgtok::Def, N, llvm::object::VernAux::Name, llvm::object::VernAux::Other, llvm::SmallVectorImpl< T >::resize(), llvm::Expected< T >::takeError(), llvm::IndexedInstrProf::Version, and llvm::ELF::VERSYM_VERSION.
notes() [1/2]
template<class ELFT > iterator_range<Elf_Note_Iterator> llvm::object::ELFFile< ELFT >::notes (const Elf_Phdr & Phdr, Error & Err) const inline
Get an iterator range over notes of a program header.
The program header must be of type PT_NOTE.
Parameters
Phdr the program header to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 352 of file ELF.h.
notes() [2/2]
template<class ELFT > iterator_range<Elf_Note_Iterator> llvm::object::ELFFile< ELFT >::notes (const Elf_Shdr & Shdr, Error & Err) const inline
Get an iterator range over notes of a section.
The section must be of type SHT_NOTE.
Parameters
Shdr the section to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 364 of file ELF.h.
notes_begin() [1/2]
template<class ELFT > Elf_Note_Iterator llvm::object::ELFFile< ELFT >::notes_begin (const Elf_Phdr & Phdr, Error & Err) const inline
Get an iterator over notes in a program header.
The program header must be of type PT_NOTE.
Parameters
Phdr the program header to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 309 of file ELF.h.
notes_begin() [2/2]
template<class ELFT > Elf_Note_Iterator llvm::object::ELFFile< ELFT >::notes_begin (const Elf_Shdr & Shdr, Error & Err) const inline
Get an iterator over notes in a section.
The section must be of type SHT_NOTE.
Parameters
Shdr the section to iterate over.
Err [out] an error to support fallible iteration, which should be checked after iteration ends.
Definition at line 328 of file ELF.h.
notes_end()
template<class ELFT > Elf_Note_Iterator llvm::object::ELFFile< ELFT >::notes_end () const inline
Get the end iterator for notes.
Definition at line 341 of file ELF.h.
program_headers()
template<class ELFT > Expected<Elf_Phdr_Range> llvm::object::ELFFile< ELFT >::program_headers () const inline
Iterate over program header table.
Definition at line 283 of file ELF.h.
References llvm::ArrayRef(), llvm::object::ELFFile< ELFT >::base(), llvm::object::createError(), llvm::object::ELFFile< ELFT >::getBufSize(), llvm::object::ELFFile< ELFT >::getHeader(), uint64_t, and llvm::Twine::utohexstr().
Referenced by llvm::object::getPhdrIndexForError().
relas()
template<class ELFT > Expected<Elf_Rela_Range> llvm::object::ELFFile< ELFT >::relas (const Elf_Shdr & Sec) const inline
Definition at line 266 of file ELF.h.
relrs()
template<class ELFT > Expected<Elf_Relr_Range> llvm::object::ELFFile< ELFT >::relrs (const Elf_Shdr & Sec) const inline
Definition at line 274 of file ELF.h.
rels()
template<class ELFT > Expected<Elf_Rel_Range> llvm::object::ELFFile< ELFT >::rels (const Elf_Shdr & Sec) const inline
Definition at line 270 of file ELF.h.
sections()
template<class ELFT > Expected< typename ELFT::ShdrRange > llvm::object::ELFFile< ELFT >::sections
Definition at line 797 of file ELF.h.
References llvm::ArrayRef(), base, llvm::object::createError(), First, UINT64_MAX, uint64_t, and llvm::Twine::utohexstr().
Referenced by llvm::object::describe(), and llvm::object::getSecIndexForError().
symbols()
template<class ELFT > Expected<Elf_Sym_Range> llvm::object::ELFFile< ELFT >::symbols (const Elf_Shdr * Sec) const inline
Definition at line 260 of file ELF.h.
toMappedAddr()
template<class ELFT > Expected< const uint8_t * > ELFFile::toMappedAddr (uint64_t VAddr, WarningHandler WarnHandler = &defaultWarningHandler) const
Definition at line 591 of file ELF.cpp.
References B, base, llvm::object::createError(), E, I, llvm::is_sorted(), move, llvm::ELF::PT_LOAD, llvm::stable_sort(), uint64_t, llvm::upper_bound(), and llvm::Twine::utohexstr().
The documentation for this class was generated from the following files:
include/llvm/Object/ELF.h
lib/Object/ELF.cpp