LLVM: llvm::RAGreedy::ExtraRegInfo Class Reference
llvm::RAGreedy::ExtraRegInfo Class Reference final
Track allocation stage and eviction loop prevention during allocation.
#include "CodeGen/RegAllocGreedy.h"
Public Member Functions
ExtraRegInfo ()
ExtraRegInfo (const ExtraRegInfo &)=delete
LiveRangeStage getStage (Register Reg) const
LiveRangeStage getStage (const LiveInterval &VirtReg) const
void setStage (Register Reg, LiveRangeStage Stage)
void setStage (const LiveInterval &VirtReg, LiveRangeStage Stage)
LiveRangeStage getOrInitStage (Register Reg)
Return the current stage of the register, if present, otherwise initialize it and return that.
unsigned getCascade (Register Reg) const
void setCascade (Register Reg, unsigned Cascade)
unsigned getOrAssignNewCascade (Register Reg)
unsigned getCascadeOrCurrentNext (Register Reg) const
template<typename Iterator >
void setStage (Iterator Begin, Iterator End, LiveRangeStage NewStage)
void LRE_DidCloneVirtReg (Register New, Register Old)
Detailed Description
Track allocation stage and eviction loop prevention during allocation.
Definition at line 67 of file RegAllocGreedy.h.
Constructor & Destructor Documentation
ExtraRegInfo() [1/2]
llvm::RAGreedy::ExtraRegInfo::ExtraRegInfo () inline
Definition at line 83 of file RegAllocGreedy.h.
ExtraRegInfo() [2/2]
llvm::RAGreedy::ExtraRegInfo::ExtraRegInfo (const ExtraRegInfo &) delete
Member Function Documentation
getCascade()
unsigned llvm::RAGreedy::ExtraRegInfo::getCascade (Register Reg) const inline
Definition at line 108 of file RegAllocGreedy.h.
References Info.
getCascadeOrCurrentNext()
unsigned llvm::RAGreedy::ExtraRegInfo::getCascadeOrCurrentNext (Register Reg) const inline
Definition at line 124 of file RegAllocGreedy.h.
getOrAssignNewCascade()
unsigned llvm::RAGreedy::ExtraRegInfo::getOrAssignNewCascade (Register Reg) inline
Definition at line 115 of file RegAllocGreedy.h.
getOrInitStage()
LiveRangeStage llvm::RAGreedy::ExtraRegInfo::getOrInitStage (Register Reg) inline
Return the current stage of the register, if present, otherwise initialize it and return that.
Definition at line 103 of file RegAllocGreedy.h.
References Info.
getStage() [1/2]
LiveRangeStage llvm::RAGreedy::ExtraRegInfo::getStage (const LiveInterval & VirtReg) const inline
Definition at line 88 of file RegAllocGreedy.h.
References llvm::LiveInterval::reg().
getStage() [2/2]
LiveRangeStage llvm::RAGreedy::ExtraRegInfo::getStage (Register Reg) const inline
Definition at line 86 of file RegAllocGreedy.h.
References Info.
Referenced by llvm::MLPriorityAdvisor::getPriorityImpl().
LRE_DidCloneVirtReg()
void RAGreedy::ExtraRegInfo::LRE_DidCloneVirtReg (Register New, Register Old)
Definition at line 260 of file RegAllocGreedy.cpp.
References llvm::RS_Assign.
setCascade()
void llvm::RAGreedy::ExtraRegInfo::setCascade (Register Reg, unsigned Cascade) inline
Definition at line 110 of file RegAllocGreedy.h.
References Info.
setStage() [1/3]
void llvm::RAGreedy::ExtraRegInfo::setStage (const LiveInterval & VirtReg, LiveRangeStage Stage) inline
Definition at line 97 of file RegAllocGreedy.h.
References llvm::LiveInterval::reg().
setStage() [2/3]
template<typename Iterator > void llvm::RAGreedy::ExtraRegInfo::setStage (Iterator Begin, Iterator End, LiveRangeStage NewStage) inline
Definition at line 132 of file RegAllocGreedy.h.
setStage() [3/3]
void llvm::RAGreedy::ExtraRegInfo::setStage (Register Reg, LiveRangeStage Stage) inline
Definition at line 92 of file RegAllocGreedy.h.
References Info.
The documentation for this class was generated from the following files:
lib/CodeGen/RegAllocGreedy.h
lib/CodeGen/RegAllocGreedy.cpp