LLVM: llvm::DeadLaneDetector Class Reference
llvm::DeadLaneDetector Class Reference
#include "llvm/CodeGen/DetectDeadLanes.h"
Classes
struct VRegInfo
Contains a bitmask of which lanes of a given virtual register are defined and which ones are actually used.
Public Member Functions
DeadLaneDetector (const MachineRegisterInfo *MRI, const TargetRegisterInfo *TRI)
void computeSubRegisterLaneBitInfo ()
Update the DefinedLanes and the UsedLanes for all virtual registers.
const VRegInfo & getVRegInfo (unsigned RegIdx) const
bool isDefinedByCopy (unsigned RegIdx) const
LaneBitmask transferDefinedLanes (const MachineOperand &Def, unsigned OpNum, LaneBitmask DefinedLanes) const
Given a mask DefinedLanes of lanes defined at operand OpNum of COPY-like instruction, determine which lanes are defined at the output operand Def.
LaneBitmask transferUsedLanes (const MachineInstr &MI, LaneBitmask UsedLanes, const MachineOperand &MO) const
Given a mask UsedLanes used from the output of instruction MI determine which lanes are used from operand MO of this instruction.
Detailed Description
Definition at line 42 of file DetectDeadLanes.h.
Constructor & Destructor Documentation
DeadLaneDetector()
DeadLaneDetector::DeadLaneDetector (const MachineRegisterInfo * MRI, const TargetRegisterInfo * TRI)
Definition at line 41 of file DetectDeadLanes.cpp.
References llvm::MachineRegisterInfo::getNumVirtRegs(), MRI, and llvm::BitVector::resize().
Member Function Documentation
computeSubRegisterLaneBitInfo()
void DeadLaneDetector::computeSubRegisterLaneBitInfo ()
Update the DefinedLanes and the UsedLanes for all virtual registers.
Definition at line 453 of file DetectDeadLanes.cpp.
References llvm::dbgs(), llvm::tgtok::Def, llvm::MachineRegisterInfo::def_begin(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::Register::index2VirtReg(), Info, LLVM_DEBUG, MI, llvm::PrintLaneMask(), llvm::printReg(), llvm::BitVector::reset(), and llvm::MachineRegisterInfo::use_nodbg_operands().
getVRegInfo()
const VRegInfo& llvm::DeadLaneDetector::getVRegInfo (unsigned RegIdx) const inline
Definition at line 57 of file DetectDeadLanes.h.
isDefinedByCopy()
bool llvm::DeadLaneDetector::isDefinedByCopy (unsigned RegIdx) const inline
Definition at line 61 of file DetectDeadLanes.h.
References llvm::BitVector::test().
transferDefinedLanes()
LaneBitmask DeadLaneDetector::transferDefinedLanes (const MachineOperand & Def, unsigned OpNum, LaneBitmask DefinedLanes) const
Given a mask DefinedLanes of lanes defined at operand OpNum of COPY-like instruction, determine which lanes are defined at the output operand Def.
Definition at line 226 of file DetectDeadLanes.cpp.
References assert(), llvm::TargetRegisterInfo::composeSubRegIndexLaneMask(), llvm::tgtok::Def, llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm_unreachable, MI, PHI, and llvm::TargetRegisterInfo::reverseComposeSubRegIndexLaneMask().
transferUsedLanes()
LaneBitmask DeadLaneDetector::transferUsedLanes (const MachineInstr & MI, LaneBitmask UsedLanes, const MachineOperand & MO) const
Given a mask UsedLanes used from the output of instruction MI determine which lanes are used from operand MO of this instruction.
Definition at line 145 of file DetectDeadLanes.cpp.
References assert(), llvm::TargetRegisterInfo::composeSubRegIndexLaneMask(), llvm::TargetRegisterClass::CoveredBySubRegs, llvm::tgtok::Def, llvm::MachineOperand::getOperandNo(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::TargetRegisterClass::LaneMask, llvm_unreachable, lowersToCopies(), MI, PHI, llvm::TargetRegisterInfo::reverseComposeSubRegIndexLaneMask(), and llvm::Register::virtReg2Index().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DetectDeadLanes.h
lib/CodeGen/DetectDeadLanes.cpp