LLVM: llvm::DIDerivedType Class Reference
llvm::DIDerivedType Class Reference
Derived types.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DEFINE_MDNODE_GET (DIDerivedType,(unsigned Tag, MDString *Name, Metadata *File, unsigned Line, Metadata *Scope, Metadata *BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, std::optional< unsigned > DWARFAddressSpace, DIFlags Flags, Metadata *ExtraData=nullptr, Metadata *Annotations=nullptr),(Tag, Name, File, Line, Scope, BaseType, SizeInBits, AlignInBits, OffsetInBits, DWARFAddressSpace, Flags, ExtraData, Annotations)) DEFINE_MDNODE_GET(DIDerivedType
DIObjCProperty * getObjCProperty () const
uint32_t getVBPtrOffset () const
Constant * getStorageOffsetInBits () const
Constant * getConstant () const
Constant * getDiscriminantValue () const
Public Member Functions inherited from llvm::DIType
TempDIType clone () const
unsigned getLine () const
uint64_t getSizeInBits () const
uint32_t getAlignInBits () const
uint32_t getAlignInBytes () const
uint64_t getOffsetInBits () const
DIFlags getFlags () const
DIScope * getScope () const
StringRef getName () const
Metadata * getRawScope () const
MDString * getRawName () const
TempDIType cloneWithFlags (DIFlags NewFlags) const
Returns a new temporary DIType with updated Flags.
bool isPrivate () const
bool isProtected () const
bool isPublic () const
bool isForwardDecl () const
bool isAppleBlockExtension () const
bool isVirtual () const
bool isArtificial () const
bool isObjectPointer () const
bool isObjcClassComplete () const
bool isVector () const
bool isBitField () const
bool isStaticMember () const
bool isLValueReference () const
bool isRValueReference () const
bool isTypePassByValue () const
bool isTypePassByReference () const
bool isBigEndian () const
bool isLittleEndian () const
bool getExportSymbols () const
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
StringRef getName () const
DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIType
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
unsigned Tag
unsigned StringRef Name
unsigned StringRef DIFile * File
unsigned StringRef DIFile unsigned Line
unsigned StringRef DIFile unsigned DIScope * Scope
unsigned StringRef DIFile unsigned DIScope DIType * BaseType
unsigned StringRef DIFile unsigned DIScope DIType uint64_t SizeInBits
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t AlignInBits
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t OffsetInBits
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t std::optional< unsigned > DWARFAddressSpace
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t std::optional< unsigned > DIFlags Flags
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t std::optional< unsigned > DIFlags Metadata * ExtraData = nullptr
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t std::optional< unsigned > DIFlags Metadata DINodeArray Annotations
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic, FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIType
DIType (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags, ArrayRef< Metadata * > Ops)
~DIType ()=default
void init (unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags)
void mutate (unsigned Tag, unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags)
Change fields in place.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Derived types.
This includes qualified types, pointers, references, friends, typedefs, and class members.
TODO: Split out members (inheritance, fields, methods, etc.).
Definition at line 963 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DIDerivedType::classof (const Metadata * MD) inline static
Definition at line 1074 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
DEFINE_MDNODE_GET()
llvm::DIDerivedType::DEFINE_MDNODE_GET (DIDerivedType , (unsigned Tag, MDString *Name, Metadata *File, unsigned Line, Metadata *Scope, Metadata *BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, std::optional< unsigned > DWARFAddressSpace, DIFlags Flags, Metadata *ExtraData=nullptr, Metadata *Annotations=nullptr) , (Tag, Name, File, Line, Scope, BaseType, SizeInBits, AlignInBits, OffsetInBits, DWARFAddressSpace, Flags, ExtraData, Annotations))
getConstant()
Constant * DIDerivedType::getConstant () const
Definition at line 652 of file DebugInfoMetadata.cpp.
References assert(), llvm::DINode::getTag(), and llvm::DIType::isStaticMember().
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE().
getDiscriminantValue()
Constant * DIDerivedType::getDiscriminantValue () const
Definition at line 658 of file DebugInfoMetadata.cpp.
References assert(), llvm::DINode::getTag(), and llvm::DIType::isStaticMember().
getObjCProperty()
DIObjCProperty* llvm::DIDerivedType::getObjCProperty () const inline
Definition at line 1061 of file DebugInfoMetadata.h.
getStorageOffsetInBits()
Constant * DIDerivedType::getStorageOffsetInBits () const
Definition at line 645 of file DebugInfoMetadata.cpp.
References assert(), llvm::DINode::getTag(), and llvm::DIType::isBitField().
getVBPtrOffset()
uint32_t DIDerivedType::getVBPtrOffset () const
Definition at line 638 of file DebugInfoMetadata.cpp.
References assert(), and llvm::DINode::getTag().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 964 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 965 of file DebugInfoMetadata.h.
Member Data Documentation
AlignInBits
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t llvm::DIDerivedType::AlignInBits
Definition at line 1020 of file DebugInfoMetadata.h.
Annotations
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t std::optional<unsigned> DIFlags Metadata DINodeArray llvm::DIDerivedType::Annotations
Initial value:
= nullptr),
                    (Tag, Name, File, Line, Scope, BaseType, SizeInBits,
                     AlignInBits, OffsetInBits, DWARFAddressSpace, Flags,
                     ExtraData, Annotations))
  TempDIDerivedType clone() const { return cloneImpl(); }
  DIType *getBaseType() const { return cast_or_null<DIType>(getRawBaseType()); }
  Metadata *getRawBaseType() const { return getOperand(3); }
  std::optional<unsigned> getDWARFAddressSpace() const {
    return DWARFAddressSpace;
  }
  Metadata *getExtraData() const { return getRawExtraData(); }
  Metadata *getRawExtraData() const { return getOperand(4); }
  DINodeArray getAnnotations() const {
    return cast_or_null<MDTuple>(getRawAnnotations());
  }
  Metadata *getRawAnnotations() const { return getOperand(5); }
  DIType *getClassType() const
Definition at line 1023 of file DebugInfoMetadata.h.
BaseType
unsigned StringRef DIFile unsigned DIScope DIType* llvm::DIDerivedType::BaseType
Definition at line 1019 of file DebugInfoMetadata.h.
DWARFAddressSpace
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t std::optional<unsigned> llvm::DIDerivedType::DWARFAddressSpace
Definition at line 1021 of file DebugInfoMetadata.h.
ExtraData
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t std::optional<unsigned> DIFlags Metadata* llvm::DIDerivedType::ExtraData = nullptr
Definition at line 1022 of file DebugInfoMetadata.h.
File
unsigned StringRef DIFile* llvm::DIDerivedType::File
Definition at line 1018 of file DebugInfoMetadata.h.
Flags
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t std::optional<unsigned> DIFlags llvm::DIDerivedType::Flags
Definition at line 1021 of file DebugInfoMetadata.h.
Line
unsigned StringRef DIFile unsigned llvm::DIDerivedType::Line
Definition at line 1018 of file DebugInfoMetadata.h.
Name
unsigned StringRef llvm::DIDerivedType::Name
Definition at line 1018 of file DebugInfoMetadata.h.
OffsetInBits
unsigned StringRef DIFile unsigned DIScope DIType uint64_t uint32_t uint64_t llvm::DIDerivedType::OffsetInBits
Definition at line 1020 of file DebugInfoMetadata.h.
Scope
unsigned StringRef DIFile unsigned DIScope* llvm::DIDerivedType::Scope
Definition at line 1019 of file DebugInfoMetadata.h.
SizeInBits
unsigned StringRef DIFile unsigned DIScope DIType uint64_t llvm::DIDerivedType::SizeInBits
Definition at line 1019 of file DebugInfoMetadata.h.
Tag
unsigned llvm::DIDerivedType::Tag
Definition at line 1018 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp