LLVM: llvm::IntegerType Class Reference
llvm::IntegerType Class Reference
Class to represent integer types.
#include "llvm/IR/DerivedTypes.h"
Public Types
enum { MIN_INT_BITS = 1, MAX_INT_BITS = (1<<23) }
This enum is just used to hold constants we need for IntegerType.
Public Types inherited from llvm::Type
enum TypeID {
HalfTyID = 0, BFloatTyID, FloatTyID, DoubleTyID,
X86_FP80TyID, FP128TyID, PPC_FP128TyID, VoidTyID,
LabelTyID, MetadataTyID, X86_MMXTyID, X86_AMXTyID,
TokenTyID, IntegerTyID, FunctionTyID, PointerTyID,
StructTyID, ArrayTyID, FixedVectorTyID, ScalableVectorTyID,
TypedPointerTyID, TargetExtTyID
}
Definitions of all of the base types for the Type system.
using subtype_iterator = Type *const *
using subtype_reverse_iterator = std::reverse_iterator< subtype_iterator >
Public Member Functions
IntegerType * getExtendedType () const
Returns type twice as wide the input type.
unsigned getBitWidth () const
Get the number of bits in this IntegerType.
uint64_t getBitMask () const
Return a bitmask with ones set for all of the bits that can be set by an unsigned version of this type.
uint64_t getSignBit () const
Return a uint64_t with just the most significant bit set (the sign bit, if the value is treated as a signed number).
APInt getMask () const
For example, this is 0xFF for an 8 bit integer, 0xFFFF for i16, etc.
Public Member Functions inherited from llvm::Type
void print (raw_ostream &O, bool IsForDebug=false, bool NoDetails=false) const
Print the current type.
void dump () const
LLVMContext & getContext () const
Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
Return the type id for the type.
bool isVoidTy () const
Return true if this is 'void'.
bool isHalfTy () const
Return true if this is 'half', a 16-bit IEEE fp type.
bool isBFloatTy () const
Return true if this is 'bfloat', a 16-bit bfloat type.
bool is16bitFPTy () const
Return true if this is a 16-bit float type.
bool isFloatTy () const
Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
Return true if this is x86 long double.
bool isFP128Ty () const
Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
Return true if this is powerpc long double.
bool isIEEELikeFPTy () const
Return true if this is a well-behaved IEEE-like type, which has a IEEE compatible layout as defined by isIEEE(), and does not have unnormal values.
bool isFloatingPointTy () const
Return true if this is one of the floating-point types.
bool isMultiUnitFPType () const
Returns true if this is a floating-point type that is an unevaluated sum of multiple floating-point units.
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
Return true if this is X86 MMX.
bool isX86_AMXTy () const
Return true if this is X86 AMX.
bool isTargetExtTy () const
Return true if this is a target extension type.
bool isFPOrFPVectorTy () const
Return true if this is a FP type or a vector of FP.
bool isLabelTy () const
Return true if this is 'label'.
bool isMetadataTy () const
Return true if this is 'metadata'.
bool isTokenTy () const
Return true if this is 'token'.
bool isIntegerTy () const
True if this is an instance of IntegerType.
bool isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
Return true if this is an integer type or a vector of integer types.
bool isIntOrIntVectorTy (unsigned BitWidth) const
Return true if this is an integer type or a vector of integer types of the given width.
bool isIntOrPtrTy () const
Return true if this is an integer type or a pointer type.
bool isFunctionTy () const
True if this is an instance of FunctionType.
bool isStructTy () const
True if this is an instance of StructType.
bool isArrayTy () const
True if this is an instance of ArrayType.
bool isPointerTy () const
True if this is an instance of PointerType.
bool isOpaquePointerTy () const
True if this is an instance of an opaque PointerType.
bool isPtrOrPtrVectorTy () const
Return true if this is a pointer type or a vector of pointer types.
bool isVectorTy () const
True if this is an instance of VectorType.
bool canLosslesslyBitCastTo (Type *Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
bool isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
bool isFirstClassType () const
Return true if the type is "first class", meaning it is a valid type for a Value.
bool isSingleValueType () const
Return true if the type is a valid type for a register in codegen.
bool isAggregateType () const
Return true if the type is an aggregate type.
bool isSized (SmallPtrSetImpl< Type * > *Visited=nullptr) const
Return true if it makes sense to take the size of this type.
TypeSize getPrimitiveSizeInBits () const LLVM_READONLY
Return the basic size of this type if it is a primitive type.
unsigned getScalarSizeInBits () const LLVM_READONLY
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
int getFPMantissaWidth () const
Return the width of the mantissa of this type.
bool isIEEE () const
Return whether the type is IEEE compatible, as defined by the eponymous method in APFloat.
Type * getScalarType () const
If this is a vector type, return the element type, otherwise return 'this'.
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
This method is used to implement the type iterator (defined at the end of the file).
unsigned getNumContainedTypes () const
Return the number of types in the derived type.
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
StringRef getTargetExtName () const
Type * getPointerElementType () const
This method is deprecated without replacement.
Type * getNonOpaquePointerElementType () const
Only use this method in code that is not reachable with opaque pointers, or part of deprecated methods that will be removed as part of the opaque pointers transition.
Type * getWithNewType (Type *EltTy) const
Given vector type, change the element type, whilst keeping the old number of elements.
Type * getWithNewBitWidth (unsigned NewBitWidth) const
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
Type * getExtendedType () const
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0) const
Return a pointer to the current type.
Static Public Member Functions
static IntegerType * get (LLVMContext &C, unsigned NumBits)
This static method is the primary way of constructing an IntegerType.
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getBFloatTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static Type * getX86_AMXTy (LLVMContext &C)
static Type * getTokenTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static IntegerType * getInt128Ty (LLVMContext &C)
template<typename ScalarTy >
static Type * getScalarTy (LLVMContext &C)
static Type * getFloatingPointTy (LLVMContext &C, const fltSemantics &S)
static PointerType * getHalfPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getBFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getDoublePtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_FP80PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getPPC_FP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_MMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_AMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getIntNPtrTy (LLVMContext &C, unsigned N, unsigned AS=0)
static PointerType * getInt1PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt8PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt16PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt32PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt64PtrTy (LLVMContext &C, unsigned AS=0)
Protected Member Functions
IntegerType (LLVMContext &C, unsigned NumBits)
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()=default
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Friends
class LLVMContextImpl
Additional Inherited Members
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys = 0
Keeps track of how many Type*'s there are in the ContainedTys list.
Type *const * ContainedTys = nullptr
A pointer to the array of Types contained by this Type.
Detailed Description
Class to represent integer types.
Note that this class is also used to represent the built-in integer types: Int1Ty, Int8Ty, Int16Ty, Int32Ty and Int64Ty. Integer representation type
Definition at line 40 of file DerivedTypes.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
This enum is just used to hold constants we need for IntegerType.
Enumerator
MIN_INT_BITS
Minimum number of bits that can be specified.
MAX_INT_BITS
Maximum number of bits that can be specified.
Note that bit width is stored in the Type classes SubclassData field which has 24 bits. SelectionDAG type legalization can require a power of 2 IntegerType, so limit to the largest representable power of 2, 8388608.
Definition at line 50 of file DerivedTypes.h.
Constructor & Destructor Documentation
IntegerType()
llvm::IntegerType::IntegerType (LLVMContext & C, unsigned NumBits) inline explicit protected
Definition at line 44 of file DerivedTypes.h.
References llvm::Type::setSubclassData().
Member Function Documentation
classof()
static bool llvm::IntegerType::classof (const Type * T) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 92 of file DerivedTypes.h.
References llvm::Type::IntegerTyID, and T.
get()
IntegerType * IntegerType::get (LLVMContext & C, unsigned NumBits) static
This static method is the primary way of constructing an IntegerType.
If an IntegerType with the same NumBits value was previously instantiated, that instance will be returned. Otherwise a new one will be created. Only one instance with a given NumBits value is ever created. Get or create an IntegerType instance.
Definition at line 313 of file Type.cpp.
References assert(), llvm::Type::getInt128Ty(), llvm::Type::getInt16Ty(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), MAX_INT_BITS, and MIN_INT_BITS.
Referenced by BinomialCoefficient(), BitCastConstantVector(), llvm::MachineIRBuilder::buildConstant(), buildScalarSteps(), CanShareConstantPoolEntry(), llvm::VNCoercion::coerceAvailableValueToLoadType(), collectInsertionElements(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ConstantFoldUnaryInstruction(), createAccessTag(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::DIBuilder::createBitFieldMemberType(), llvm::MatrixBuilder::CreateIndex(), llvm::DIBuilder::createInheritance(), llvm::createMemLibcall(), llvm::MDBuilder::createRange(), DecodeFixedType(), emitGlobalConstantVector(), ExtractConstantBytes(), llvm::FastISel::fastEmit_ri_(), foldConsecutiveLoads(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::generateEnqueueInst(), llvm::SCEVExpander::generateOverflowCheck(), llvm::ConstantInt::get(), getAccessType(), getAsConstantIndexedAddress(), llvm::DataLayout::getIndexType(), llvm::VectorType::getInteger(), llvm::Type::getIntNTy(), llvm::DataLayout::getIntPtrType(), llvm::VNCoercion::getLoadValueForLoad(), llvm::VNCoercion::getMemInstValueForLoad(), llvm::X86TTIImpl::getMemoryOpCost(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType(), getPreStartForExtend(), llvm::getRuntimeVFAsFloat(), llvm::ScalarEvolution::getSignExtendExprImpl(), getStepVector(), llvm::VNCoercion::getStoreValueForLoadHelper(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTreeReductionCost(), llvm::VectorType::getTruncatedElementVectorType(), llvm::EVT::getTypeForEVT(), getTypeForLLT(), llvm::ScalarEvolution::getUDivExpr(), llvm::ScalarEvolution::getURemExpr(), llvm::ScalarEvolution::getZeroExtendExprImpl(), isAddRecSExtable(), isAddSExtable(), IsIncrementNSW(), IsIncrementNUW(), isLoadCombineCandidateImpl(), isMulSExtable(), llvm::SPIRVLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), LLVMIntTypeInContext(), lookThroughAnd(), matchIntrinsicType(), optimizeMemCmpConstantSize(), llvm::TargetLowering::ParseConstraints(), processSwitches(), processUGT_ADDCST_ADD(), rewriteGEPAsOffset(), llvm::InstCombinerImpl::SimplifyAnyMemSet(), llvm::InstCombinerImpl::SimplifyAnyMemTransfer(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), tryToFPToSat(), llvm::InstCombinerImpl::visitSwitchInst(), and llvm::ScalarEvolution::willNotOverflow().
getBitMask()
uint64_t llvm::IntegerType::getBitMask () const inline
Return a bitmask with ones set for all of the bits that can be set by an unsigned version of this type.
This is 0xFF for i8, 0xFFFF for i16, etc.
Definition at line 76 of file DerivedTypes.h.
References getBitWidth(), and uint64_t.
getBitWidth()
unsigned llvm::IntegerType::getBitWidth () const inline
Get the number of bits in this IntegerType.
Definition at line 72 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by llvm::SanitizerStatReport::create(), llvm::IRBuilderBase::CreateExtractInteger(), DecodeFixedType(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::X86TargetLowering::ExpandInlineAsm(), extractInteger(), findCommonType(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), generateUnsignedDivisionCode(), llvm::ConstantInt::get(), getBitMask(), getMask(), getOverloadKind(), getPreferredVectorIndex(), getSignBit(), insertInteger(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::HardwareLoopInfo::isHardwareLoopCandidate(), llvm::PPCInstrInfo::isSignOrZeroExtended(), LLVMConstIntOfArbitraryPrecision(), llvm::InsertCFGStrategy::mutate(), and llvm::PtrUseVisitor< SliceBuilder >::visitPtr().
getExtendedType()
IntegerType* llvm::IntegerType::getExtendedType () const inline
Returns type twice as wide the input type.
Definition at line 67 of file DerivedTypes.h.
References llvm::Type::getContext(), llvm::Type::getIntNTy(), and llvm::Type::getScalarSizeInBits().
getMask()
APInt IntegerType::getMask () const
For example, this is 0xFF for an 8 bit integer, 0xFFFF for i16, etc.
Returns
a bit mask with ones set for all the bits of this type. Get a bit mask for this type.
Definition at line 337 of file Type.cpp.
References llvm::APInt::getAllOnes(), and getBitWidth().
Referenced by insertInteger().
getSignBit()
uint64_t llvm::IntegerType::getSignBit () const inline
Return a uint64_t with just the most significant bit set (the sign bit, if the value is treated as a signed number).
Definition at line 82 of file DerivedTypes.h.
References getBitWidth().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 41 of file DerivedTypes.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DerivedTypes.h
lib/IR/Type.cpp