LLVM: llvm::IPSCCPPass Class Reference
llvm::IPSCCPPass Class Reference
Pass to perform interprocedural constant propagation.
#include "llvm/Transforms/IPO/SCCP.h"
Public Member Functions
IPSCCPPass ()=default
IPSCCPPass (IPSCCPOptions Options)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
bool isFuncSpecEnabled () const
Public Member Functions inherited from llvm::PassInfoMixin< IPSCCPPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< IPSCCPPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass to perform interprocedural constant propagation.
Definition at line 48 of file SCCP.h.
Constructor & Destructor Documentation
IPSCCPPass() [1/2]
llvm::IPSCCPPass::IPSCCPPass () default
IPSCCPPass() [2/2]
llvm::IPSCCPPass::IPSCCPPass (IPSCCPOptions Options) inline
Definition at line 54 of file SCCP.h.
References Options.
Member Function Documentation
isFuncSpecEnabled()
bool llvm::IPSCCPPass::isFuncSpecEnabled () const inline
Definition at line 58 of file SCCP.h.
References Options.
Referenced by run().
run()
PreservedAnalyses IPSCCPPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 380 of file SCCP.cpp.
References llvm::PreservedAnalyses::all(), DL, F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), isFuncSpecEnabled(), M, llvm::PreservedAnalyses::preserve(), and runIPSCCP().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SCCP.h
lib/Transforms/IPO/SCCP.cpp