LLVM: llvm::LiveRangeEdit::Delegate Class Reference
llvm::LiveRangeEdit::Delegate Class Reference
Callback methods for LiveRangeEdit owners.
#include "llvm/CodeGen/LiveRangeEdit.h"
Public Member Functions
virtual ~Delegate ()=default
virtual void LRE_WillEraseInstruction (MachineInstr *MI)
Called immediately before erasing a dead machine instruction.
virtual bool LRE_CanEraseVirtReg (Register)
Called when a virtual register is no longer used.
virtual void LRE_WillShrinkVirtReg (Register)
Called before shrinking the live range of a virtual register.
virtual void LRE_DidCloneVirtReg (Register New, Register Old)
Called after cloning a virtual register.
Detailed Description
Callback methods for LiveRangeEdit owners.
Definition at line 45 of file LiveRangeEdit.h.
Constructor & Destructor Documentation
~Delegate()
virtual llvm::LiveRangeEdit::Delegate::~Delegate () virtual default
Member Function Documentation
LRE_CanEraseVirtReg()
virtual bool llvm::LiveRangeEdit::Delegate::LRE_CanEraseVirtReg (Register) inline virtual
Called when a virtual register is no longer used.
Return false to defer its deletion from LiveIntervals.
Definition at line 56 of file LiveRangeEdit.h.
Referenced by llvm::LiveRangeEdit::eraseVirtReg().
LRE_DidCloneVirtReg()
virtual void llvm::LiveRangeEdit::Delegate::LRE_DidCloneVirtReg (Register New, Register Old) inline virtual
Called after cloning a virtual register.
This is used for new registers representing connected components of Old.
Definition at line 63 of file LiveRangeEdit.h.
Referenced by llvm::LiveRangeEdit::eliminateDeadDefs().
LRE_WillEraseInstruction()
virtual void llvm::LiveRangeEdit::Delegate::LRE_WillEraseInstruction (MachineInstr * MI) inline virtual
Called immediately before erasing a dead machine instruction.
Definition at line 52 of file LiveRangeEdit.h.
LRE_WillShrinkVirtReg()
virtual void llvm::LiveRangeEdit::Delegate::LRE_WillShrinkVirtReg (Register) inline virtual
Called before shrinking the live range of a virtual register.
Definition at line 59 of file LiveRangeEdit.h.
Referenced by llvm::LiveRangeEdit::eliminateDeadDefs().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveRangeEdit.h
lib/CodeGen/LiveRangeEdit.cpp