LLVM: llvm::MIMetadata Class Reference
llvm::MIMetadata Class Reference
Set of metadata that should be preserved when using BuildMI().
#include "llvm/CodeGen/MachineInstrBuilder.h"
Public Member Functions
MIMetadata ()=default
MIMetadata (DebugLoc DL, MDNode *PCSections=nullptr)
MIMetadata (const DILocation *DI, MDNode *PCSections=nullptr)
MIMetadata (const Instruction &From)
MIMetadata (const MachineInstr &From)
const DebugLoc & getDL () const
MDNode * getPCSections () const
Detailed Description
Set of metadata that should be preserved when using BuildMI().
This provides a more convenient way of preserving DebugLoc and PCSections.
Definition at line 335 of file MachineInstrBuilder.h.
Constructor & Destructor Documentation
MIMetadata() [1/5]
llvm::MIMetadata::MIMetadata () default
MIMetadata() [2/5]
llvm::MIMetadata::MIMetadata (DebugLoc DL, MDNode * PCSections = nullptr) inline
Definition at line 338 of file MachineInstrBuilder.h.
References DL.
MIMetadata() [3/5]
llvm::MIMetadata::MIMetadata (const DILocation * DI, MDNode * PCSections = nullptr) inline
Definition at line 340 of file MachineInstrBuilder.h.
MIMetadata() [4/5]
llvm::MIMetadata::MIMetadata (const Instruction & From) inline explicit
Definition at line 342 of file MachineInstrBuilder.h.
MIMetadata() [5/5]
llvm::MIMetadata::MIMetadata (const MachineInstr & From) inline explicit
Definition at line 345 of file MachineInstrBuilder.h.
Member Function Documentation
getDL()
const DebugLoc& llvm::MIMetadata::getDL () const inline
Definition at line 348 of file MachineInstrBuilder.h.
Referenced by llvm::BuildMI(), and llvm::FastISel::getCurDebugLoc().
getPCSections()
MDNode* llvm::MIMetadata::getPCSections () const inline
Definition at line 349 of file MachineInstrBuilder.h.
Referenced by llvm::BuildMI().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineInstrBuilder.h