LLVM: llvm::SimpleLoopUnswitchPass Class Reference
llvm::SimpleLoopUnswitchPass Class Reference
This pass transforms loops that contain branches or switches on loop- invariant conditions to have multiple loops.
#include "llvm/Transforms/Scalar/SimpleLoopUnswitch.h"
Public Member Functions
SimpleLoopUnswitchPass (bool NonTrivial=false, bool Trivial=true)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< SimpleLoopUnswitchPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SimpleLoopUnswitchPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
This pass transforms loops that contain branches or switches on loop- invariant conditions to have multiple loops.
For example, it turns the left into the right code:
for (...) if (lic) A for (...) if (lic) A; B; C B else C for (...) A; C
This can increase the size of the code exponentially (doubling it every time a loop is unswitched) so we only unswitch if the resultant code will be smaller than a threshold.
This pass expects LICM to be run before it to hoist invariant conditions out of the loop, to make the unswitching opportunity obvious.
There is a taxonomy of unswitching that we use to classify different forms of this transformaiton:
Trival unswitching: this is when the condition can be unswitched without cloning any code from inside the loop. A non-trivial unswitch requires code duplication.
Full unswitching: this is when the branch or switch is completely moved from inside the loop to outside the loop. Partial unswitching removes the branch from the clone of the loop but must leave a (somewhat simplified) branch in the original loop. While theoretically partial unswitching can be done for switches, the requirements are extreme - we need the loop invariant input to the switch to be sufficient to collapse to a single successor in each clone.
This pass always does trivial, full unswitching for both branches and switches. For branches, it also always does trivial, partial unswitching.
If enabled (via the constructor's NonTrivial parameter), this pass will additionally do non-trivial, full unswitching for branches and switches, and will do non-trivial, partial unswitching for branches.
Because partial unswitching of switches is extremely unlikely to be possible in practice and significantly complicates the implementation, this pass does not currently implement that in any mode.
Definition at line 67 of file SimpleLoopUnswitch.h.
Constructor & Destructor Documentation
SimpleLoopUnswitchPass()
llvm::SimpleLoopUnswitchPass::SimpleLoopUnswitchPass (bool NonTrivial = false, bool Trivial = true) inline
Definition at line 72 of file SimpleLoopUnswitch.h.
Member Function Documentation
printPipeline()
void SimpleLoopUnswitchPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 3581 of file SimpleLoopUnswitch.cpp.
References OS.
run()
PreservedAnalyses SimpleLoopUnswitchPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 3509 of file SimpleLoopUnswitch.cpp.
References llvm::LoopStandardAnalysisResults::AA, llvm::LoopStandardAnalysisResults::AC, llvm::PreservedAnalyses::all(), assert(), llvm::LoopStandardAnalysisResults::BFI, Context, llvm::dbgs(), llvm::LoopStandardAnalysisResults::DT, F, llvm::Sched::Fast, llvm::MDString::get(), llvm::MDNode::get(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Loop::getLoopID(), llvm::getLoopPassPreservedAnalyses(), llvm::Loop::getName(), llvm::BasicBlock::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::LoopStandardAnalysisResults::LI, LLVM_DEBUG, llvm::makePostTransformationMetadata(), llvm::LoopStandardAnalysisResults::MSSA, llvm::LoopStandardAnalysisResults::SE, llvm::Loop::setLoopID(), llvm::LoopStandardAnalysisResults::TTI, unswitchLoop(), llvm::DominatorTreeBase< NodeT, IsPostDom >::verify(), llvm::MemorySSA::verifyMemorySSA(), and llvm::VerifyMemorySSA.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/SimpleLoopUnswitch.h
lib/Transforms/Scalar/SimpleLoopUnswitch.cpp