LLVM: llvm::ConvergingVLIWScheduler Class Reference
llvm::ConvergingVLIWScheduler Class Reference
#include "llvm/CodeGen/VLIWMachineScheduler.h"
Classes
struct SchedCandidate
Store the state used by ConvergingVLIWScheduler heuristics, required for the lifetime of one invocation of pickNode().
struct VLIWSchedBoundary
Each Scheduling boundary is associated with ready queues.
Public Types
enum { TopQID = 1, BotQID = 2, LogMaxQID = 2 }
SUnit::NodeQueueId: 0 (none), 1 (top), 2 (bot), 3 (both)
Public Member Functions
ConvergingVLIWScheduler ()
virtual ~ConvergingVLIWScheduler ()=default
void initialize (ScheduleDAGMI *dag) override
Initialize the strategy after building the DAG for a new region.
SUnit * pickNode (bool &IsTopNode) override
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
void schedNode (SUnit *SU, bool IsTopNode) override
Update the scheduler's state after scheduling a node.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
unsigned reportPackets ()
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual void dumpPolicy () const
virtual bool shouldTrackPressure () const
Check if pressure tracking is needed before building the DAG and initializing this strategy.
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
virtual void registerRoots ()
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
Protected Types
enum CandResult {
NoCand, NodeOrder, SingleExcess, SingleCritical,
SingleMax, MultiPressure, BestCost, Weak
}
Represent the type of SchedCandidate found within a single queue.
Protected Member Functions
virtual VLIWResourceModel * createVLIWResourceModel (const TargetSubtargetInfo &STI, const TargetSchedModel *SchedModel) const
SUnit * pickNodeBidrectional (bool &IsTopNode)
Pick the best candidate node from either the top or bottom queue.
int pressureChange (const SUnit *SU, bool isBotUp)
Check if the instruction changes the register pressure of a register in the high pressure set.
virtual int SchedulingCost (ReadyQueue &Q, SUnit *SU, SchedCandidate &Candidate, RegPressureDelta &Delta, bool verbose)
Single point to compute overall scheduling cost.
CandResult pickNodeFromQueue (VLIWSchedBoundary &Zone, const RegPressureTracker &RPTracker, SchedCandidate &Candidate)
Pick the best candidate from the top queue.
void traceCandidate (const char *Label, const ReadyQueue &Q, SUnit *SU, int Cost, PressureChange P=PressureChange())
void readyQueueVerboseDump (const RegPressureTracker &RPTracker, SchedCandidate &Candidate, ReadyQueue &Q)
Protected Attributes
VLIWMachineScheduler * DAG = nullptr
const TargetSchedModel * SchedModel = nullptr
VLIWSchedBoundary Top
VLIWSchedBoundary Bot
SmallVector< bool > HighPressureSets
List of pressure sets that have a high pressure level in the region.
Static Protected Attributes
static constexpr unsigned PriorityOne = 200
static constexpr unsigned PriorityTwo = 50
static constexpr unsigned PriorityThree = 75
static constexpr unsigned ScaleTwo = 10
Detailed Description
Definition at line 88 of file VLIWMachineScheduler.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
SUnit::NodeQueueId: 0 (none), 1 (top), 2 (bot), 3 (both)
Enumerator
TopQID
BotQID
LogMaxQID
Definition at line 219 of file VLIWMachineScheduler.h.
CandResult
enum llvm::ConvergingVLIWScheduler::CandResult protected
Represent the type of SchedCandidate found within a single queue.
Enumerator
NoCand
NodeOrder
SingleExcess
SingleCritical
SingleMax
MultiPressure
BestCost
Weak
Definition at line 105 of file VLIWMachineScheduler.h.
Constructor & Destructor Documentation
ConvergingVLIWScheduler()
llvm::ConvergingVLIWScheduler::ConvergingVLIWScheduler () inline
Definition at line 221 of file VLIWMachineScheduler.h.
~ConvergingVLIWScheduler()
virtual llvm::ConvergingVLIWScheduler::~ConvergingVLIWScheduler () virtual default
Member Function Documentation
createVLIWResourceModel()
VLIWResourceModel * ConvergingVLIWScheduler::createVLIWResourceModel (const TargetSubtargetInfo & STI, const TargetSchedModel * SchedModel) const protected virtual
Reimplemented in llvm::HexagonConvergingVLIWScheduler.
Definition at line 305 of file VLIWMachineScheduler.cpp.
References SchedModel.
Referenced by initialize().
initialize()
void ConvergingVLIWScheduler::initialize (ScheduleDAGMI * DAG) override virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Definition at line 270 of file VLIWMachineScheduler.cpp.
References assert(), llvm::SmallVectorImpl< T >::assign(), Bot, createVLIWResourceModel(), DAG, llvm::numbers::e, llvm::ForceBottomUp, llvm::ForceTopDown, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetSchedModel::getInstrItineraries(), llvm::VLIWMachineScheduler::getRegClassInfo(), llvm::ScheduleDAGMILive::getRegPressure(), llvm::RegisterClassInfo::getRegPressureSetLimit(), llvm::ScheduleDAGInstrs::getSchedModel(), llvm::MachineFunction::getSubtarget(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::HazardRec, HighPressureSets, i, llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::init(), llvm::RegisterPressure::MaxSetPressure, llvm::ScheduleDAG::MF, llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::ResourceModel, RPThreshold, SchedModel, TII, and Top.
pickNode()
SUnit * ConvergingVLIWScheduler::pickNode (bool & IsTopNode) override virtual
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
Implements llvm::MachineSchedStrategy.
Definition at line 950 of file VLIWMachineScheduler.cpp.
References assert(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::Available, Bot, llvm::ScheduleDAGMI::bottom(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::CurrCycle, DAG, llvm::dbgs(), llvm::ScheduleDAGInstrs::dumpNode(), llvm::ReadyQueue::empty(), llvm::ForceBottomUp, llvm::ForceTopDown, llvm::ScheduleDAGMILive::getBotRPTracker(), llvm::ScheduleDAGMILive::getTopRPTracker(), llvm::SUnit::isBottomReady(), llvm::SUnit::isTopReady(), LLVM_DEBUG, NoCand, llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::Pending, pickNodeBidrectional(), pickNodeFromQueue(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::pickOnlyChoice(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::removeReady(), reportPackets(), llvm::ConvergingVLIWScheduler::SchedCandidate::SU, Top, and llvm::ScheduleDAGMI::top().
pickNodeBidrectional()
SUnit * ConvergingVLIWScheduler::pickNodeBidrectional (bool & IsTopNode) protected
Pick the best candidate node from either the top or bottom queue.
Definition at line 884 of file VLIWMachineScheduler.cpp.
References assert(), Bot, DAG, llvm::dbgs(), llvm::ScheduleDAGMILive::getBotRPTracker(), llvm::ScheduleDAGMILive::getTopRPTracker(), LLVM_DEBUG, NoCand, pickNodeFromQueue(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::pickOnlyChoice(), llvm::ConvergingVLIWScheduler::SchedCandidate::SCost, SingleCritical, SingleExcess, SingleMax, llvm::ConvergingVLIWScheduler::SchedCandidate::SU, and Top.
Referenced by pickNode().
pickNodeFromQueue()
ConvergingVLIWScheduler::CandResult ConvergingVLIWScheduler::pickNodeFromQueue (VLIWSchedBoundary & Zone, const RegPressureTracker & RPTracker, SchedCandidate & Candidate) protected
Pick the best candidate from the top queue.
TODO: getMaxPressureDelta results can be mostly cached for each SUnit during DAG building. To adjust for the current scheduling location we need to maintain the number of vreg uses remaining to be top-scheduled.
Definition at line 769 of file VLIWMachineScheduler.cpp.
References llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::Available, llvm::ReadyQueue::begin(), BestCost, BotQID, DAG, llvm::ReadyQueue::dump(), E, llvm::ReadyQueue::end(), llvm::ReadyQueue::getID(), llvm::ScheduleDAGMILive::getRegionCriticalPSets(), llvm::ScheduleDAGMILive::getRegPressure(), llvm::getWeakLeft(), I, llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::isLatencyBound(), LLVM_DEBUG, llvm::RegisterPressure::MaxSetPressure, NoCand, llvm::SUnit::NodeNum, NodeOrder, llvm::SUnit::Preds, readyQueueVerboseDump(), llvm::ConvergingVLIWScheduler::SchedCandidate::RPDelta, SchedDebugVerboseLevel, SchedulingCost(), llvm::ConvergingVLIWScheduler::SchedCandidate::SCost, llvm::ConvergingVLIWScheduler::SchedCandidate::SU, llvm::SUnit::Succs, TopQID, traceCandidate(), UseNewerCandidate, and Weak.
Referenced by pickNode(), and pickNodeBidrectional().
pressureChange()
int ConvergingVLIWScheduler::pressureChange (const SUnit * SU, bool isBotUp) protected
Check if the instruction changes the register pressure of a register in the high pressure set.
The function returns a negative value if the pressure decreases and a positive value is the pressure increases. If the instruction doesn't use a high pressure register or doesn't change the register pressure, then return 0.
Definition at line 580 of file VLIWMachineScheduler.cpp.
References DAG, llvm::ScheduleDAGMILive::getPressureDiff(), HighPressureSets, P, and llvm::X86II::PD.
Referenced by SchedulingCost().
readyQueueVerboseDump()
void ConvergingVLIWScheduler::readyQueueVerboseDump (const RegPressureTracker & RPTracker, SchedCandidate & Candidate, ReadyQueue & Q) protected
Definition at line 524 of file VLIWMachineScheduler.cpp.
References llvm::ReadyQueue::begin(), DAG, llvm::dbgs(), E, llvm::ReadyQueue::end(), llvm::RegPressureTracker::getMaxPressureDelta(), llvm::ReadyQueue::getName(), llvm::ScheduleDAGMILive::getRegionCriticalPSets(), llvm::ScheduleDAGMILive::getRegPressure(), I, llvm::RegisterPressure::MaxSetPressure, and SchedulingCost().
Referenced by pickNodeFromQueue().
releaseBottomNode()
void ConvergingVLIWScheduler::releaseBottomNode (SUnit * SU) override virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 325 of file VLIWMachineScheduler.cpp.
References assert(), Bot, llvm::SUnit::BotReadyCycle, E, llvm::SUnit::getInstr(), I, llvm::SUnit::isScheduled, llvm::max(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::MaxMinLatency, llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::releaseNode(), and llvm::SUnit::Succs.
releaseTopNode()
void ConvergingVLIWScheduler::releaseTopNode (SUnit * SU) override virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 310 of file VLIWMachineScheduler.cpp.
References llvm::SDep::getLatency(), llvm::SDep::getSUnit(), llvm::SUnit::isScheduled, llvm::max(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::MaxMinLatency, llvm::SUnit::Preds, llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::releaseNode(), Top, and llvm::SUnit::TopReadyCycle.
reportPackets()
unsigned llvm::ConvergingVLIWScheduler::reportPackets () inline
Definition at line 234 of file VLIWMachineScheduler.h.
References Bot, llvm::VLIWResourceModel::getTotalPackets(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::ResourceModel, and Top.
Referenced by pickNode().
schedNode()
void ConvergingVLIWScheduler::schedNode (SUnit * SU, bool IsTopNode) override virtual
Update the scheduler's state after scheduling a node.
This is the same node that was just returned by pickNode(). However, VLIWMachineScheduler needs to update it's state based on the current cycle before MachineSchedStrategy does.
Implements llvm::MachineSchedStrategy.
Definition at line 999 of file VLIWMachineScheduler.cpp.
References Bot, llvm::SUnit::BotReadyCycle, llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::bumpNode(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::CurrCycle, Top, and llvm::SUnit::TopReadyCycle.
SchedulingCost()
int ConvergingVLIWScheduler::SchedulingCost (ReadyQueue & Q, SUnit * SU, SchedCandidate & Candidate, RegPressureDelta & Delta, bool verbose) protected virtual
Single point to compute overall scheduling cost.
TODO: More heuristics will be used soon.
Reimplemented in llvm::HexagonConvergingVLIWScheduler.
Definition at line 596 of file VLIWMachineScheduler.cpp.
References Bot, BotQID, CheckEarlyAvail, llvm::RegPressureDelta::CriticalMax, llvm::RegPressureDelta::CurrentMax, llvm::dbgs(), llvm::RegPressureDelta::Excess, llvm::SUnit::getDepth(), llvm::SUnit::getHeight(), llvm::ReadyQueue::getID(), llvm::SUnit::getInstr(), llvm::SDep::getLatency(), llvm::SDep::getSUnit(), llvm::PressureChange::getUnitInc(), llvm::getWeakLeft(), IgnoreBBRegPressure, llvm::SDep::isAssignedRegDep(), llvm::VLIWResourceModel::isInPacket(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::isLatencyBound(), llvm::MachineInstr::isPseudo(), llvm::VLIWResourceModel::isResourceAvailable(), llvm::SUnit::isScheduled, llvm::SUnit::isScheduleHigh, isSingleUnscheduledPred(), isSingleUnscheduledSucc(), LLVM_DEBUG, llvm::SUnit::Preds, pressureChange(), PriorityOne, PriorityThree, PriorityTwo, llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::ResourceModel, ScaleTwo, SI, llvm::SUnit::Succs, Top, and TopQID.
Referenced by pickNodeFromQueue(), readyQueueVerboseDump(), and llvm::HexagonConvergingVLIWScheduler::SchedulingCost().
traceCandidate()
void ConvergingVLIWScheduler::traceCandidate (const char * Label, const ReadyQueue & Q, SUnit * SU, int Cost, PressureChange P = PressureChange()) protected
Definition at line 510 of file VLIWMachineScheduler.cpp.
References Cost, DAG, llvm::dbgs(), llvm::ScheduleDAGInstrs::dumpNode(), llvm::ReadyQueue::getName(), llvm::TargetRegisterInfo::getRegPressureSetName(), P, and llvm::ScheduleDAG::TRI.
Referenced by pickNodeFromQueue().
Member Data Documentation
Bot
VLIWSchedBoundary llvm::ConvergingVLIWScheduler::Bot protected
Definition at line 212 of file VLIWMachineScheduler.h.
Referenced by initialize(), pickNode(), pickNodeBidrectional(), releaseBottomNode(), reportPackets(), schedNode(), llvm::HexagonConvergingVLIWScheduler::SchedulingCost(), and SchedulingCost().
DAG
VLIWMachineScheduler* llvm::ConvergingVLIWScheduler::DAG = nullptr protected
Definition at line 207 of file VLIWMachineScheduler.h.
Referenced by initialize(), pickNode(), pickNodeBidrectional(), pickNodeFromQueue(), pressureChange(), readyQueueVerboseDump(), llvm::HexagonConvergingVLIWScheduler::SchedulingCost(), and traceCandidate().
HighPressureSets
SmallVector<bool> llvm::ConvergingVLIWScheduler::HighPressureSets protected
List of pressure sets that have a high pressure level in the region.
Definition at line 215 of file VLIWMachineScheduler.h.
Referenced by initialize(), and pressureChange().
PriorityOne
constexpr unsigned llvm::ConvergingVLIWScheduler::PriorityOne = 200 static constexpr protected
Definition at line 118 of file VLIWMachineScheduler.h.
Referenced by SchedulingCost().
PriorityThree
constexpr unsigned llvm::ConvergingVLIWScheduler::PriorityThree = 75 static constexpr protected
Definition at line 120 of file VLIWMachineScheduler.h.
Referenced by SchedulingCost().
PriorityTwo
constexpr unsigned llvm::ConvergingVLIWScheduler::PriorityTwo = 50 static constexpr protected
Definition at line 119 of file VLIWMachineScheduler.h.
Referenced by llvm::HexagonConvergingVLIWScheduler::SchedulingCost(), and SchedulingCost().
ScaleTwo
constexpr unsigned llvm::ConvergingVLIWScheduler::ScaleTwo = 10 static constexpr protected
Definition at line 121 of file VLIWMachineScheduler.h.
Referenced by SchedulingCost().
SchedModel
const TargetSchedModel* llvm::ConvergingVLIWScheduler::SchedModel = nullptr protected
Definition at line 208 of file VLIWMachineScheduler.h.
Referenced by llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::bumpCycle(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::bumpNode(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::checkHazard(), llvm::HexagonConvergingVLIWScheduler::createVLIWResourceModel(), createVLIWResourceModel(), and initialize().
Top
VLIWSchedBoundary llvm::ConvergingVLIWScheduler::Top protected
Definition at line 211 of file VLIWMachineScheduler.h.
Referenced by initialize(), pickNode(), pickNodeBidrectional(), releaseTopNode(), reportPackets(), schedNode(), llvm::HexagonConvergingVLIWScheduler::SchedulingCost(), and SchedulingCost().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/VLIWMachineScheduler.h
lib/CodeGen/VLIWMachineScheduler.cpp