LLVM: llvm::DebuginfodLog Class Reference
llvm::DebuginfodLog Class Reference
#include "llvm/Debuginfod/Debuginfod.h"
Public Member Functions
void push (DebuginfodLogEntry Entry)
void push (const Twine &Message)
DebuginfodLogEntry pop ()
Detailed Description
Definition at line 90 of file Debuginfod.h.
Member Function Documentation
pop()
DebuginfodLogEntry llvm::DebuginfodLog::pop ()
Definition at line 288 of file Debuginfod.cpp.
References llvm_unreachable.
push() [1/2]
void llvm::DebuginfodLog::push (const Twine & Message)
Definition at line 276 of file Debuginfod.cpp.
References push().
push() [2/2]
void llvm::DebuginfodLog::push (DebuginfodLogEntry Entry)
Definition at line 280 of file Debuginfod.cpp.
Referenced by push(), and llvm::DebuginfodCollection::update().
The documentation for this class was generated from the following files:
include/llvm/Debuginfod/Debuginfod.h
lib/Debuginfod/Debuginfod.cpp