LLVM: llvm::LegacyDivergenceAnalysisPass Class Reference
llvm::LegacyDivergenceAnalysisPass Class Reference
#include "llvm/Analysis/LegacyDivergenceAnalysis.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< LegacyDivergenceAnalysisPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::LegacyDivergenceAnalysisImpl
bool isDivergent (const Value *V) const
bool isDivergentUse (const Use *U) const
bool isUniform (const Value *V) const
bool isUniformUse (const Use *U) const
void removeValue (const Value *V)
void print (raw_ostream &OS, const Module *) const
bool shouldUseGPUDivergenceAnalysis (const Function &F, const TargetTransformInfo &TTI, const LoopInfo &LI)
void run (Function &F, TargetTransformInfo &TTI, DominatorTree &DT, PostDominatorTree &PDT, const LoopInfo &LI)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LegacyDivergenceAnalysisPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Protected Attributes inherited from llvm::LegacyDivergenceAnalysisImpl
std::unique_ptr< DivergenceInfo > gpuDA
DenseSet< const Value * > DivergentValues
DenseSet< const Use * > DivergentUses
Detailed Description
Definition at line 84 of file LegacyDivergenceAnalysis.h.
Member Function Documentation
run()
PreservedAnalyses LegacyDivergenceAnalysisPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 418 of file LegacyDivergenceAnalysis.cpp.
References llvm::PreservedAnalyses::all(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::clear(), llvm::dbgs(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::TargetTransformInfo::hasBranchDivergence(), LLVM_DEBUG, llvm::LegacyDivergenceAnalysisImpl::print(), and llvm::LegacyDivergenceAnalysisImpl::run().
The documentation for this class was generated from the following files:
include/llvm/Analysis/LegacyDivergenceAnalysis.h
lib/Analysis/LegacyDivergenceAnalysis.cpp