LLVM: llvm::ScaledNumberBase Class Reference
llvm::ScaledNumberBase Class Reference
#include "llvm/Support/ScaledNumber.h"
Static Public Member Functions
static void dump (uint64_t D, int16_t E, int Width)
static raw_ostream & print (raw_ostream &OS, uint64_t D, int16_t E, int Width, unsigned Precision)
static std::string toString (uint64_t D, int16_t E, int Width, unsigned Precision)
static int countLeadingZeros32 (uint32_t N)
static int countLeadingZeros64 (uint64_t N)
static uint64_t getHalf (uint64_t N)
static std::pair< uint64_t, bool > splitSigned (int64_t N)
static int64_t joinSigned (uint64_t U, bool IsNeg)
Static Public Attributes
static constexpr int DefaultPrecision = 10
Detailed Description
Definition at line 420 of file ScaledNumber.h.
Member Function Documentation
countLeadingZeros32()
static int llvm::ScaledNumberBase::countLeadingZeros32 (uint32_t N) inline static
Definition at line 429 of file ScaledNumber.h.
References llvm::countl_zero(), and N.
countLeadingZeros64()
static int llvm::ScaledNumberBase::countLeadingZeros64 (uint64_t N) inline static
Definition at line 430 of file ScaledNumber.h.
References llvm::countl_zero(), and N.
Referenced by toStringAPFloat().
dump()
void ScaledNumberBase::dump (uint64_t D, int16_t E, int Width) static
Definition at line 320 of file ScaledNumber.cpp.
References D, llvm::dbgs(), E, and llvm::print().
Referenced by llvm::ScaledNumber< uint64_t >::dump().
getHalf()
static uint64_t llvm::ScaledNumberBase::getHalf (uint64_t N) inline static
Definition at line 431 of file ScaledNumber.h.
References N.
joinSigned()
static int64_t llvm::ScaledNumberBase::joinSigned (uint64_t U, bool IsNeg) inline static
Definition at line 439 of file ScaledNumber.h.
References INT64_MAX, INT64_MIN, and uint64_t.
Referenced by llvm::ScaledNumber< uint64_t >::scale(), and llvm::ScaledNumber< uint64_t >::scaleByInverse().
print()
raw_ostream & ScaledNumberBase::print (raw_ostream & OS, uint64_t D, int16_t E, int Width, unsigned Precision) static
Definition at line 315 of file ScaledNumber.cpp.
References D, E, OS, and llvm::toString().
Referenced by llvm::ScaledNumber< uint64_t >::print().
splitSigned()
static std::pair<uint64_t, bool> llvm::ScaledNumberBase::splitSigned (int64_t N) inline static
Definition at line 433 of file ScaledNumber.h.
References INT64_MIN, N, uint64_t, and Unsigned.
Referenced by llvm::ScaledNumber< uint64_t >::scale(), and llvm::ScaledNumber< uint64_t >::scaleByInverse().
toString()
std::string ScaledNumberBase::toString (uint64_t D, int16_t E, int Width, unsigned Precision) static
Definition at line 201 of file ScaledNumber.cpp.
References appendDigit(), appendNumber(), D, doesRoundUp(), E, I, llvm::max(), llvm::min(), llvm::reverse(), Shift, stripTrailingZeros(), toStringAPFloat(), UINT64_MAX, and uint64_t.
Referenced by llvm::ScaledNumber< uint64_t >::toString().
Member Data Documentation
DefaultPrecision
constexpr int llvm::ScaledNumberBase::DefaultPrecision = 10 static constexpr
Definition at line 422 of file ScaledNumber.h.
The documentation for this class was generated from the following files:
include/llvm/Support/ScaledNumber.h
lib/Support/ScaledNumber.cpp