LLVM: llvm::StackSafetyGlobalInfo Class Reference
llvm::StackSafetyGlobalInfo Class Reference
#include "llvm/Analysis/StackSafetyAnalysis.h"
Classes
struct InfoTy
Public Member Functions
StackSafetyGlobalInfo ()
StackSafetyGlobalInfo (Module *M, std::function< const StackSafetyInfo &(Function &F)> GetSSI, const ModuleSummaryIndex *Index)
StackSafetyGlobalInfo (StackSafetyGlobalInfo &&)
StackSafetyGlobalInfo & operator= (StackSafetyGlobalInfo &&)
~StackSafetyGlobalInfo ()
bool isSafe (const AllocaInst &AI) const
bool stackAccessIsSafe (const Instruction &I) const
void print (raw_ostream &O) const
void dump () const
Detailed Description
Definition at line 58 of file StackSafetyAnalysis.h.
Constructor & Destructor Documentation
StackSafetyGlobalInfo() [1/3]
StackSafetyGlobalInfo::StackSafetyGlobalInfo () default
StackSafetyGlobalInfo() [2/3]
StackSafetyGlobalInfo::StackSafetyGlobalInfo (Module * M, std::function< const StackSafetyInfo &(Function &F)> GetSSI, const ModuleSummaryIndex * Index)
Definition at line 950 of file StackSafetyAnalysis.cpp.
References M, and StackSafetyRun.
StackSafetyGlobalInfo() [3/3]
StackSafetyGlobalInfo::StackSafetyGlobalInfo (StackSafetyGlobalInfo &&) default
~StackSafetyGlobalInfo()
StackSafetyGlobalInfo::~StackSafetyGlobalInfo () default
Member Function Documentation
dump()
LLVM_DUMP_METHOD void StackSafetyGlobalInfo::dump () const
Definition at line 999 of file StackSafetyAnalysis.cpp.
References llvm::dbgs(), and print().
isSafe()
bool StackSafetyGlobalInfo::isSafe (const AllocaInst & AI) const
Definition at line 966 of file StackSafetyAnalysis.cpp.
References Info.
Referenced by llvm::memtag::StackInfoBuilder::isInterestingAlloca().
operator=()
StackSafetyGlobalInfo & StackSafetyGlobalInfo::operator= (StackSafetyGlobalInfo &&) default
print()
void StackSafetyGlobalInfo::print (raw_ostream & O) const
Definition at line 976 of file StackSafetyAnalysis.cpp.
References F, I, llvm::StackSafetyGlobalInfo::InfoTy::Info, llvm::instructions(), M, llvm::RISCVFenceField::O, and stackAccessIsSafe().
Referenced by dump(), and llvm::StackSafetyGlobalInfoWrapperPass::print().
stackAccessIsSafe()
bool StackSafetyGlobalInfo::stackAccessIsSafe (const Instruction & I) const
Definition at line 971 of file StackSafetyAnalysis.cpp.
References I, and Info.
Referenced by print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/StackSafetyAnalysis.h
lib/Analysis/StackSafetyAnalysis.cpp