LLVM: llvm::StringSwitch< T, R > Class Template Reference
llvm::StringSwitch< T, R > Class Template Reference
A switch()-like statement whose cases are string literals.
#include "llvm/ADT/StringSwitch.h"
Public Member Functions
StringSwitch (StringRef S)
StringSwitch (const StringSwitch &)=delete
void operator= (const StringSwitch &)=delete
void operator= (StringSwitch &&other)=delete
StringSwitch (StringSwitch &&other)
~StringSwitch ()=default
StringSwitch & Case (StringLiteral S, T Value)
StringSwitch & EndsWith (StringLiteral S, T Value)
StringSwitch & StartsWith (StringLiteral S, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, T Value)
StringSwitch & Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, StringLiteral S9, T Value)
StringSwitch & CaseLower (StringLiteral S, T Value)
StringSwitch & EndsWithLower (StringLiteral S, T Value)
StringSwitch & StartsWithLower (StringLiteral S, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value)
StringSwitch & CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value)
R Default (T Value)
operator R ()
Detailed Description
template<typename T, typename R = T>
class llvm::StringSwitch< T, R >
A switch()-like statement whose cases are string literals.
The StringSwitch class is a simple form of a switch() statement that determines whether the given string matches one of the given string literals. The template type parameter T is the type of the value that will be returned from the string-switch expression. For example, the following code switches on the name of a color in argv[i]:
Color color = StringSwitch<Color>(argv[i])
  .Case("red", Red)
  .Case("orange", Orange)
  .Case("yellow", Yellow)
  .Case("green", Green)
  .Case("blue", Blue)
  .Case("indigo", Indigo)
  .Cases("violet", "purple", Violet)
  .Default(UnknownColor);
Definition at line 44 of file StringSwitch.h.
Constructor & Destructor Documentation
StringSwitch() [1/3]
template<typename T , typename R = T> llvm::StringSwitch< T, R >::StringSwitch (StringRef S) inline explicit
Definition at line 53 of file StringSwitch.h.
StringSwitch() [2/3]
template<typename T , typename R = T> llvm::StringSwitch< T, R >::StringSwitch (const StringSwitch< T, R > &) delete
StringSwitch() [3/3]
template<typename T , typename R = T> llvm::StringSwitch< T, R >::StringSwitch (StringSwitch< T, R > && other) inline
Definition at line 63 of file StringSwitch.h.
~StringSwitch()
template<typename T , typename R = T> llvm::StringSwitch< T, R >::~StringSwitch () default
Member Function Documentation
Case()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Case (StringLiteral S, T Value) inline
Definition at line 69 of file StringSwitch.h.
References move, and S.
Referenced by llvm::AArch64StringToVectorLayout(), llvm::ARMCondCodeFromString(), llvm::ARMVectorCondCodeFromString(), llvm::StringSwitch< T, R >::Cases(), llvm::classifyEHPersonality(), llvm::ELF::convertArchNameToEMachine(), llvm::convertStrToExceptionBehavior(), llvm::convertStrToRoundingMode(), llvm::MachO::Target::create(), llvm::DwarfStreamer::emitSectionContents(), llvm::ARM::getArchSynonym(), llvm::Triple::getArchTypeForLLVMName(), llvm::DIFile::getChecksumKind(), llvm::Hexagon::getCpu(), llvm::Hexagon_MC::GetELFFlags(), llvm::DICompileUnit::getEmissionKind(), llvm::AVRAsmBackend::getFixupKind(), llvm::MipsAsmBackend::getFixupKind(), llvm::LoongArchAsmBackend::getFixupKind(), llvm::RISCVAsmBackend::getFixupKind(), getFPPredicateFromMD(), llvm::ARM::getFPUSynonym(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForPowerPC(), llvm::sys::detail::getHostCPUNameForRISCV(), getHWDivSynonym(), getIdentifierKind(), llvm::object::getImageKind(), getIntPredicateFromMD(), llvm::mca::RISCVLMULInstrument::getLMUL(), llvm::getMachineType(), llvm::dwarf::getMacinfo(), getMClassFlagsMask(), getMetadataKeywordKind(), llvm::DICompileUnit::getNameTableKind(), llvm::object::getOffloadKind(), llvm::dwarf::getOperationEncoding(), llvm::MachO::getPlatformFromName(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::VETargetLowering::getRegisterByName(), llvm::LanaiTargetLowering::getRegisterByName(), llvm::SparcTargetLowering::getRegisterByName(), llvm::AVRTargetLowering::getRegisterByName(), llvm::HexagonTargetLowering::getRegisterByName(), llvm::MipsTargetLowering::getRegisterByName(), llvm::SITargetLowering::getRegisterByName(), llvm::SystemZTargetLowering::getRegisterByName(), llvm::PPCTargetLowering::getRegisterByName(), llvm::X86TargetLowering::getRegisterByName(), llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath(), getSpecialRegForName(), llvm::RISCVABI::getTargetABI(), llvm::LoongArchABI::getTargetABI(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getValueKind(), llvm::RISCVMCExpr::getVariantKindForName(), llvm::LoongArchMCExpr::getVariantKindForName(), llvm::VFABI::getVFParamKindFromString(), llvm::yaml::ScalarTraits< IFSEndiannessType >::input(), llvm::yaml::ScalarTraits< SwiftVersion >::input(), llvm::yaml::ScalarTraits< IFSBitWidthType >::input(), isSpecialLLVMGlobalArrayToSkip(), llvm::object::XCOFFObjectFile::mapDebugSectionName(), llvm::object::MachOObjectFile::mapDebugSectionName(), llvm::object::COFFObjectFile::mapDebugSectionName(), MCAttrForString(), llvm::HexagonMCInstrInfo::packetSize(), llvm::dxil::parameterTypeNameToKind(), parseArch(), llvm::WebAssembly::parseBlockType(), parseConstraintCode(), llvm::parseDenormalFPAttributeComponent(), llvm::remarks::parseFormat(), llvm::WebAssembly::parseMVT(), parseNamePrefix(), llvm::VEMCExpr::parseVariantKind(), llvm::SparcMCExpr::parseVariantKind(), parseVendor(), llvm::SymbolRemappingReader::read(), llvm::LPAC::stringToLanaiAluCode(), llvm::RISCVFPRndMode::stringToRoundingMode(), llvm::stringToVEFCondCode(), llvm::stringToVEICondCode(), llvm::stringToVERD(), and UpgradeIntrinsicFunction1().
CaseLower()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CaseLower (StringLiteral S, T Value) inline
Definition at line 142 of file StringSwitch.h.
References move, and S.
Referenced by llvm::StringSwitch< T, R >::CasesLower().
Cases() [1/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, StringLiteral S9, T Value) inline
Definition at line 134 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [2/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, StringLiteral S8, T Value) inline
Definition at line 127 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [3/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, StringLiteral S7, T Value) inline
Definition at line 121 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [4/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, StringLiteral S6, T Value) inline
Definition at line 115 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [5/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, StringLiteral S5, T Value) inline
Definition at line 109 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [6/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value) inline
Definition at line 104 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [7/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value) inline
Definition at line 99 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [8/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value) inline
Definition at line 94 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Cases().
Cases() [9/9]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::Cases (StringLiteral S0, StringLiteral S1, T Value) inline
Definition at line 90 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::Case().
Referenced by llvm::StringSwitch< T, R >::Cases(), llvm::ARM::getArchSynonym(), llvm::ARM::getFPUSynonym(), llvm::getMachineType(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::mca::RISCVLMULInstrument::isDataValid(), isSpecialLLVMGlobalArrayForStaticInit(), MCAttrForString(), parseArch(), llvm::parseDenormalFPAttributeComponent(), llvm::remarks::parseFormat(), llvm::Triple::Triple(), and UpgradeIntrinsicFunction1().
CasesLower() [1/4]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, StringLiteral S4, T Value) inline
Definition at line 177 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::CaseLower(), and llvm::StringSwitch< T, R >::CasesLower().
CasesLower() [2/4]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, StringLiteral S3, T Value) inline
Definition at line 172 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::CaseLower(), and llvm::StringSwitch< T, R >::CasesLower().
CasesLower() [3/4]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, StringLiteral S2, T Value) inline
Definition at line 167 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::CaseLower(), and llvm::StringSwitch< T, R >::CasesLower().
CasesLower() [4/4]
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::CasesLower (StringLiteral S0, StringLiteral S1, T Value) inline
Definition at line 163 of file StringSwitch.h.
References llvm::StringSwitch< T, R >::CaseLower().
Referenced by llvm::StringSwitch< T, R >::CasesLower().
Default()
template<typename T , typename R = T> R llvm::StringSwitch< T, R >::Default (T Value) inline
Definition at line 182 of file StringSwitch.h.
References move.
Referenced by llvm::AArch64StringToVectorLayout(), llvm::ARMCondCodeFromString(), llvm::ARMVectorCondCodeFromString(), llvm::classifyEHPersonality(), llvm::ELF::convertArchNameToEMachine(), llvm::convertStrToExceptionBehavior(), llvm::convertStrToRoundingMode(), llvm::MachO::Target::create(), llvm::DwarfStreamer::emitSectionContents(), llvm::MachO::getArchitectureFromName(), llvm::ARM::getArchSynonym(), llvm::Triple::getArchTypeForLLVMName(), llvm::dwarf::getAttributeEncoding(), llvm::Attribute::getAttrKindFromName(), llvm::dwarf::getCallingConvention(), llvm::DIFile::getChecksumKind(), llvm::Hexagon::getCpu(), llvm::CSKY::getDefaultExtensions(), llvm::ARM::getDefaultExtensions(), llvm::ARM::getDefaultFPU(), llvm::DICompileUnit::getEmissionKind(), llvm::AVRAsmBackend::getFixupKind(), llvm::MipsAsmBackend::getFixupKind(), llvm::LoongArchAsmBackend::getFixupKind(), llvm::RISCVAsmBackend::getFixupKind(), llvm::DINode::getFlag(), llvm::DISubprogram::getFlag(), getFPPredicateFromMD(), llvm::ARM::getFPUSynonym(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForPowerPC(), llvm::sys::detail::getHostCPUNameForRISCV(), getHWDivSynonym(), getIdentifierKind(), llvm::object::getImageKind(), getIntPredicateFromMD(), llvm::dwarf::getLanguage(), llvm::getMachineType(), llvm::dwarf::getMacinfo(), llvm::dwarf::getMacro(), getMClassFlagsMask(), getMetadataKeywordKind(), llvm::DICompileUnit::getNameTableKind(), llvm::object::getOffloadKind(), llvm::omp::getOpenMPContextTraitPropertyForSelector(), llvm::omp::getOpenMPContextTraitSelectorKind(), llvm::omp::getOpenMPContextTraitSetKind(), llvm::dwarf::getOperationEncoding(), llvm::MachO::getPlatformFromName(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::VETargetLowering::getRegisterByName(), llvm::LanaiTargetLowering::getRegisterByName(), llvm::SparcTargetLowering::getRegisterByName(), llvm::AVRTargetLowering::getRegisterByName(), llvm::HexagonTargetLowering::getRegisterByName(), llvm::MipsTargetLowering::getRegisterByName(), llvm::SITargetLowering::getRegisterByName(), llvm::SystemZTargetLowering::getRegisterByName(), llvm::PPCTargetLowering::getRegisterByName(), llvm::X86TargetLowering::getRegisterByName(), llvm::pdb::PDBSymbolCompiland::getSourceFileFullPath(), getSpecialRegForName(), llvm::dwarf::getTag(), llvm::RISCVABI::getTargetABI(), llvm::LoongArchABI::getTargetABI(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getValueKind(), llvm::XtensaMCExpr::getVariantKindForName(), llvm::RISCVMCExpr::getVariantKindForName(), llvm::LoongArchMCExpr::getVariantKindForName(), llvm::VFABI::getVFParamKindFromString(), llvm::dwarf::getVirtuality(), llvm::yaml::ScalarTraits< IFSEndiannessType >::input(), llvm::yaml::ScalarTraits< SwiftVersion >::input(), llvm::yaml::ScalarTraits< IFSBitWidthType >::input(), llvm::mca::RISCVLMULInstrument::isDataValid(), llvm::Attribute::isExistingAttribute(), isSpecialLLVMGlobalArrayForStaticInit(), isSpecialLLVMGlobalArrayToSkip(), llvm::remarks::magicToFormat(), llvm::object::XCOFFObjectFile::mapDebugSectionName(), llvm::object::MachOObjectFile::mapDebugSectionName(), llvm::object::COFFObjectFile::mapDebugSectionName(), llvm::object::MachOObjectFile::mapReflectionSectionNameToEnumValue(), MaybePredicatedInst(), MCAttrForString(), llvm::HexagonMCInstrInfo::packetSize(), llvm::dxil::parameterTypeNameToKind(), parseArch(), llvm::ARM::parseArchISA(), llvm::WebAssembly::parseBlockType(), parseConstraintCode(), llvm::RISCV::parseCPUKind(), llvm::parseDenormalFPAttributeComponent(), parseEnvironment(), llvm::remarks::parseFormat(), parseFormat(), llvm::WebAssembly::parseMVT(), parseNamePrefix(), parseOS(), llvm::dxbc::parsePartType(), parseSubArch(), llvm::RISCV::parseTuneCPUKind(), llvm::VEMCExpr::parseVariantKind(), llvm::SparcMCExpr::parseVariantKind(), parseVendor(), llvm::SymbolRemappingReader::read(), SizeForSuffix(), llvm::LPAC::stringToLanaiAluCode(), llvm::RISCVFPRndMode::stringToRoundingMode(), llvm::stringToVEFCondCode(), llvm::stringToVEICondCode(), llvm::stringToVERD(), llvm::LPCC::suffixToLanaiCondCode(), llvm::Triple::Triple(), and UpgradeIntrinsicFunction1().
EndsWith()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::EndsWith (StringLiteral S, T Value) inline
Definition at line 76 of file StringSwitch.h.
References move, and S.
Referenced by parseFormat(), parseSubArch(), SizeForSuffix(), and llvm::LPCC::suffixToLanaiCondCode().
EndsWithLower()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::EndsWithLower (StringLiteral S, T Value) inline
Definition at line 149 of file StringSwitch.h.
References S.
operator R()
template<typename T , typename R = T> llvm::StringSwitch< T, R >::operator R () inline
Definition at line 188 of file StringSwitch.h.
References assert(), and move.
operator=() [1/2]
template<typename T , typename R = T> void llvm::StringSwitch< T, R >::operator= (const StringSwitch< T, R > &) delete
operator=() [2/2]
template<typename T , typename R = T> void llvm::StringSwitch< T, R >::operator= (StringSwitch< T, R > && other) delete
StartsWith()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::StartsWith (StringLiteral S, T Value) inline
Definition at line 83 of file StringSwitch.h.
References move, and S.
Referenced by llvm::Triple::getArchTypeForLLVMName(), llvm::remarks::magicToFormat(), MaybePredicatedInst(), parseArch(), llvm::ARM::parseArchISA(), parseEnvironment(), parseOS(), llvm::Triple::Triple(), and UpgradeIntrinsicFunction1().
StartsWithLower()
template<typename T , typename R = T> StringSwitch& llvm::StringSwitch< T, R >::StartsWithLower (StringLiteral S, T Value) inline
Definition at line 156 of file StringSwitch.h.
References move, and S.
The documentation for this class was generated from the following file:
include/llvm/ADT/StringSwitch.h