LLVM: llvm::RegAllocScore Class Reference
llvm::RegAllocScore Class Reference final
Regalloc score.
#include "CodeGen/RegAllocScore.h"
Public Member Functions
RegAllocScore ()=default
RegAllocScore (const RegAllocScore &)=default
double copyCounts () const
double loadCounts () const
double storeCounts () const
double loadStoreCounts () const
double expensiveRematCounts () const
double cheapRematCounts () const
void onCopy (double Freq)
void onLoad (double Freq)
void onStore (double Freq)
void onLoadStore (double Freq)
void onExpensiveRemat (double Freq)
void onCheapRemat (double Freq)
RegAllocScore & operator+= (const RegAllocScore &Other)
bool operator== (const RegAllocScore &Other) const
bool operator!= (const RegAllocScore &Other) const
double getScore () const
Detailed Description
Regalloc score.
Definition at line 28 of file RegAllocScore.h.
Constructor & Destructor Documentation
RegAllocScore() [1/2]
llvm::RegAllocScore::RegAllocScore () default
RegAllocScore() [2/2]
llvm::RegAllocScore::RegAllocScore (const RegAllocScore &) default
Member Function Documentation
cheapRematCounts()
double llvm::RegAllocScore::cheapRematCounts () const inline
Definition at line 45 of file RegAllocScore.h.
Referenced by getScore(), and operator==().
copyCounts()
double llvm::RegAllocScore::copyCounts () const inline
Definition at line 40 of file RegAllocScore.h.
Referenced by getScore(), and operator==().
expensiveRematCounts()
double llvm::RegAllocScore::expensiveRematCounts () const inline
Definition at line 44 of file RegAllocScore.h.
Referenced by getScore(), and operator==().
getScore()
double RegAllocScore::getScore () const
Definition at line 61 of file RegAllocScore.cpp.
References cheapRematCounts(), CheapRematWeight, copyCounts(), CopyWeight, expensiveRematCounts(), ExpensiveRematWeight, loadCounts(), loadStoreCounts(), LoadWeight, llvm::MipsISD::Ret, storeCounts(), and StoreWeight.
loadCounts()
double llvm::RegAllocScore::loadCounts () const inline
Definition at line 41 of file RegAllocScore.h.
Referenced by getScore(), and operator==().
loadStoreCounts()
double llvm::RegAllocScore::loadStoreCounts () const inline
Definition at line 43 of file RegAllocScore.h.
Referenced by getScore(), and operator==().
onCheapRemat()
void llvm::RegAllocScore::onCheapRemat (double Freq) inline
Definition at line 52 of file RegAllocScore.h.
Referenced by llvm::calculateRegAllocScore().
onCopy()
void llvm::RegAllocScore::onCopy (double Freq) inline
Definition at line 47 of file RegAllocScore.h.
Referenced by llvm::calculateRegAllocScore().
onExpensiveRemat()
void llvm::RegAllocScore::onExpensiveRemat (double Freq) inline
Definition at line 51 of file RegAllocScore.h.
Referenced by llvm::calculateRegAllocScore().
onLoad()
void llvm::RegAllocScore::onLoad (double Freq) inline
Definition at line 48 of file RegAllocScore.h.
Referenced by llvm::calculateRegAllocScore().
onLoadStore()
void llvm::RegAllocScore::onLoadStore (double Freq) inline
Definition at line 50 of file RegAllocScore.h.
Referenced by llvm::calculateRegAllocScore().
onStore()
void llvm::RegAllocScore::onStore (double Freq) inline
Definition at line 49 of file RegAllocScore.h.
Referenced by llvm::calculateRegAllocScore().
operator!=()
bool RegAllocScore::operator!= (const RegAllocScore & Other) const
Definition at line 57 of file RegAllocScore.cpp.
References Other.
operator+=()
RegAllocScore & RegAllocScore::operator+= (const RegAllocScore & Other)
Definition at line 38 of file RegAllocScore.cpp.
References Other.
operator==()
bool RegAllocScore::operator== (const RegAllocScore & Other) const
Definition at line 48 of file RegAllocScore.cpp.
References cheapRematCounts(), copyCounts(), expensiveRematCounts(), loadCounts(), loadStoreCounts(), Other, and storeCounts().
storeCounts()
double llvm::RegAllocScore::storeCounts () const inline
Definition at line 42 of file RegAllocScore.h.
Referenced by getScore(), and operator==().
The documentation for this class was generated from the following files:
lib/CodeGen/RegAllocScore.h
lib/CodeGen/RegAllocScore.cpp