LLVM: llvm::IRBuilderFolder Class Reference
llvm::IRBuilderFolder Class Reference abstract
IRBuilderFolder - Interface for constant folding in IRBuilder.
#include "llvm/IR/IRBuilderFolder.h"
Public Member Functions
virtual ~IRBuilderFolder ()
virtual Value * FoldBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS) const =0
virtual Value * FoldExactBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool IsExact) const =0
virtual Value * FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool HasNUW, bool HasNSW) const =0
virtual Value * FoldBinOpFMF (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, FastMathFlags FMF) const =0
virtual Value * FoldUnOpFMF (Instruction::UnaryOps Opc, Value *V, FastMathFlags FMF) const =0
virtual Value * FoldICmp (CmpInst::Predicate P, Value *LHS, Value *RHS) const =0
virtual Value * FoldGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, bool IsInBounds=false) const =0
virtual Value * FoldSelect (Value *C, Value *True, Value *False) const =0
virtual Value * FoldExtractValue (Value *Agg, ArrayRef< unsigned > IdxList) const =0
virtual Value * FoldInsertValue (Value *Agg, Value *Val, ArrayRef< unsigned > IdxList) const =0
virtual Value * FoldExtractElement (Value *Vec, Value *Idx) const =0
virtual Value * FoldInsertElement (Value *Vec, Value *NewElt, Value *Idx) const =0
virtual Value * FoldShuffleVector (Value *V1, Value *V2, ArrayRef< int > Mask) const =0
virtual Value * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const =0
virtual Value * CreatePointerCast (Constant *C, Type *DestTy) const =0
virtual Value * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const =0
virtual Value * CreateFPCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateBitCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateIntToPtr (Constant *C, Type *DestTy) const =0
virtual Value * CreatePtrToInt (Constant *C, Type *DestTy) const =0
virtual Value * CreateZExtOrBitCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateSExtOrBitCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateTruncOrBitCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const =0
Detailed Description
IRBuilderFolder - Interface for constant folding in IRBuilder.
Definition at line 24 of file IRBuilderFolder.h.
Constructor & Destructor Documentation
~IRBuilderFolder()
IRBuilderFolder::~IRBuilderFolder () virtual default
Member Function Documentation
CreateBitCast()
virtual Value* llvm::IRBuilderFolder::CreateBitCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
CreateCast()
virtual Value* llvm::IRBuilderFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateCast().
CreateFCmp()
virtual Value* llvm::IRBuilderFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
CreateFPCast()
virtual Value* llvm::IRBuilderFolder::CreateFPCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateFPCast().
CreateIntCast()
virtual Value* llvm::IRBuilderFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::NoFolder, and llvm::InstSimplifyFolder.
Referenced by llvm::IRBuilderBase::CreateIntCast().
CreateIntToPtr()
virtual Value* llvm::IRBuilderFolder::CreateIntToPtr (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
CreatePointerBitCastOrAddrSpaceCast()
virtual Value* llvm::IRBuilderFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreatePointerBitCastOrAddrSpaceCast().
CreatePointerCast()
virtual Value* llvm::IRBuilderFolder::CreatePointerCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreatePointerCast().
CreatePtrToInt()
virtual Value* llvm::IRBuilderFolder::CreatePtrToInt (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
CreateSExtOrBitCast()
virtual Value* llvm::IRBuilderFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateSExtOrBitCast().
CreateTruncOrBitCast()
virtual Value* llvm::IRBuilderFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateTruncOrBitCast().
CreateZExtOrBitCast()
virtual Value* llvm::IRBuilderFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateZExtOrBitCast().
FoldBinOp()
virtual Value* llvm::IRBuilderFolder::FoldBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::InstSimplifyFolder, llvm::NoFolder, and llvm::ConstantFolder.
Referenced by llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateBinOp(), llvm::IRBuilderBase::CreateOr(), llvm::IRBuilderBase::CreateSRem(), llvm::IRBuilderBase::CreateURem(), and llvm::IRBuilderBase::CreateXor().
FoldBinOpFMF()
virtual Value* llvm::IRBuilderFolder::FoldBinOpFMF (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, FastMathFlags FMF) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateFAdd(), llvm::IRBuilderBase::CreateFAddFMF(), llvm::IRBuilderBase::CreateFDiv(), llvm::IRBuilderBase::CreateFDivFMF(), llvm::IRBuilderBase::CreateFMul(), llvm::IRBuilderBase::CreateFMulFMF(), llvm::IRBuilderBase::CreateFRem(), llvm::IRBuilderBase::CreateFRemFMF(), llvm::IRBuilderBase::CreateFSub(), and llvm::IRBuilderBase::CreateFSubFMF().
FoldExactBinOp()
virtual Value* llvm::IRBuilderFolder::FoldExactBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool IsExact) const pure virtual
Implemented in llvm::TargetFolder, llvm::InstSimplifyFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateAShr(), llvm::IRBuilderBase::CreateLShr(), llvm::IRBuilderBase::CreateSDiv(), and llvm::IRBuilderBase::CreateUDiv().
FoldExtractElement()
virtual Value* llvm::IRBuilderFolder::FoldExtractElement (Value * Vec, Value * Idx) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateExtractElement().
FoldExtractValue()
virtual Value* llvm::IRBuilderFolder::FoldExtractValue (Value * Agg, ArrayRef< unsigned > IdxList) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateExtractValue().
FoldGEP()
virtual Value* llvm::IRBuilderFolder::FoldGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, bool IsInBounds = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateConstGEP1_32(), llvm::IRBuilderBase::CreateConstGEP1_64(), llvm::IRBuilderBase::CreateConstGEP2_32(), llvm::IRBuilderBase::CreateConstGEP2_64(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_64(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_64(), and llvm::IRBuilderBase::CreateGEP().
FoldICmp()
virtual Value* llvm::IRBuilderFolder::FoldICmp (CmpInst::Predicate P, Value * LHS, Value * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateICmp().
FoldInsertElement()
virtual Value* llvm::IRBuilderFolder::FoldInsertElement (Value * Vec, Value * NewElt, Value * Idx) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateInsertElement().
FoldInsertValue()
virtual Value* llvm::IRBuilderFolder::FoldInsertValue (Value * Agg, Value * Val, ArrayRef< unsigned > IdxList) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateInsertValue().
FoldNoWrapBinOp()
virtual Value* llvm::IRBuilderFolder::FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool HasNUW, bool HasNSW) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateMul(), llvm::IRBuilderBase::CreateShl(), and llvm::IRBuilderBase::CreateSub().
FoldSelect()
virtual Value* llvm::IRBuilderFolder::FoldSelect (Value * C, Value * True, Value * False) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateSelect().
FoldShuffleVector()
virtual Value* llvm::IRBuilderFolder::FoldShuffleVector (Value * V1, Value * V2, ArrayRef< int > Mask) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateShuffleVector().
FoldUnOpFMF()
virtual Value* llvm::IRBuilderFolder::FoldUnOpFMF (Instruction::UnaryOps Opc, Value * V, FastMathFlags FMF) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, llvm::InstSimplifyFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateFNeg(), llvm::IRBuilderBase::CreateFNegFMF(), and llvm::IRBuilderBase::CreateUnOp().
The documentation for this class was generated from the following files:
include/llvm/IR/IRBuilderFolder.h
lib/IR/IRBuilder.cpp