LLVM: llvm::OrderedChangedData< T > Class Template Reference
llvm::OrderedChangedData< T > Class Template Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
std::vector< std::string > & getOrder ()
const std::vector< std::string > & getOrder () const
StringMap< T > & getData ()
const StringMap< T > & getData () const
bool operator== (const OrderedChangedData< T > &That) const
Static Public Member Functions
static void report (const OrderedChangedData &Before, const OrderedChangedData &After, function_ref< void(const T *, const T *)> HandlePair)
Protected Attributes
std::vector< std::string > Order
StringMap< T > Data
Detailed Description
template<typename T>
class llvm::OrderedChangedData< T >
Definition at line 319 of file StandardInstrumentations.h.
Member Function Documentation
getData() [1/2]
template<typename T > StringMap<T>& llvm::OrderedChangedData< T >::getData () inline
Definition at line 326 of file StandardInstrumentations.h.
Referenced by llvm::OrderedChangedData< FuncDataT< T > >::operator==(), and llvm::OrderedChangedData< FuncDataT< T > >::report().
getData() [2/2]
template<typename T > const StringMap<T>& llvm::OrderedChangedData< T >::getData () const inline
Definition at line 327 of file StandardInstrumentations.h.
getOrder() [1/2]
template<typename T > std::vector<std::string>& llvm::OrderedChangedData< T >::getOrder () inline
Definition at line 322 of file StandardInstrumentations.h.
Referenced by llvm::OrderedChangedData< FuncDataT< T > >::report().
getOrder() [2/2]
template<typename T > const std::vector<std::string>& llvm::OrderedChangedData< T >::getOrder () const inline
Definition at line 323 of file StandardInstrumentations.h.
operator==()
template<typename T > bool llvm::OrderedChangedData< T >::operator== (const OrderedChangedData< T > & That) const inline
Definition at line 329 of file StandardInstrumentations.h.
report()
template<typename T > void OrderedChangedData::report (const OrderedChangedData< T > & Before, const OrderedChangedData< T > & After, function_ref< void(const T *, const T *)> HandlePair) static
Definition at line 529 of file StandardInstrumentations.cpp.
Member Data Documentation
Data
template<typename T > StringMap<T> llvm::OrderedChangedData< T >::Data protected
Definition at line 344 of file StandardInstrumentations.h.
Referenced by llvm::OrderedChangedData< FuncDataT< T > >::getData(), and llvm::OrderedChangedData< FuncDataT< T > >::operator==().
Order
template<typename T > std::vector<std::string> llvm::OrderedChangedData< T >::Order protected
Definition at line 343 of file StandardInstrumentations.h.
Referenced by llvm::OrderedChangedData< FuncDataT< T > >::getOrder().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp