LLVM: llvm::orc::StaticLibraryDefinitionGenerator Class Reference
llvm::orc::StaticLibraryDefinitionGenerator Class Reference
A utility class to expose symbols from a static library.
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
Public Types
using GetObjectFileInterface = unique_function< Expected< MaterializationUnit::Interface >(ExecutionSession &ES, MemoryBufferRef ObjBuffer)>
Public Member Functions
const std::set< std::string > & getImportedDynamicLibraries () const
Returns a list of filenames of dynamic libraries that this archive has imported.
Error tryToGenerate (LookupState &LS, LookupKind K, JITDylib &JD, JITDylibLookupFlags JDLookupFlags, const SymbolLookupSet &Symbols) override
DefinitionGenerators should override this method to insert new definitions into the parent JITDylib.
Public Member Functions inherited from llvm::orc::DefinitionGenerator
virtual ~DefinitionGenerator ()
Static Public Member Functions
static Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > Load (ObjectLayer &L, const char *FileName, GetObjectFileInterface GetObjFileInterface=GetObjectFileInterface())
Try to create a StaticLibraryDefinitionGenerator from the given path.
static Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > Load (ObjectLayer &L, const char *FileName, const Triple &TT, GetObjectFileInterface GetObjFileInterface=GetObjectFileInterface())
Try to create a StaticLibraryDefinitionGenerator from the given path.
static Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > Create (ObjectLayer &L, std::unique_ptr< MemoryBuffer > ArchiveBuffer, std::unique_ptr< object::Archive > Archive, GetObjectFileInterface GetObjFileInterface=GetObjectFileInterface())
Try to create a StaticLibrarySearchGenerator from the given memory buffer and Archive object.
static Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > Create (ObjectLayer &L, std::unique_ptr< MemoryBuffer > ArchiveBuffer, GetObjectFileInterface GetObjFileInterface=GetObjectFileInterface())
Try to create a StaticLibrarySearchGenerator from the given memory buffer.
static Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > Create (ObjectLayer &L, std::unique_ptr< MemoryBuffer > ArchiveBuffer, const Triple &TT, GetObjectFileInterface GetObjFileInterface=GetObjectFileInterface())
Try to create a StaticLibrarySearchGenerator from the given memory buffer.
Detailed Description
A utility class to expose symbols from a static library.
If an instance of this class is attached to a JITDylib as a fallback definition generator, then any symbol found in the archive will result in the containing object being added to the JITDylib.
Definition at line 264 of file ExecutionUtils.h.
Member Typedef Documentation
GetObjectFileInterface
using llvm::orc::StaticLibraryDefinitionGenerator::GetObjectFileInterface = unique_function<Expected<MaterializationUnit::Interface>(ExecutionSession &ES, MemoryBufferRef ObjBuffer)>
Definition at line 269 of file ExecutionUtils.h.
Member Function Documentation
Create() [1/3]
Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > llvm::orc::StaticLibraryDefinitionGenerator::Create (ObjectLayer & L, std::unique_ptr< MemoryBuffer > ArchiveBuffer, const Triple & TT, GetObjectFileInterface GetObjFileInterface = GetObjectFileInterface()) static
Try to create a StaticLibrarySearchGenerator from the given memory buffer.
This call will succeed if the buffer contains a valid static library or a MachO universal binary containing a static library that is compatible with the given triple. Otherwise it will return an error.
Definition at line 358 of file ExecutionUtils.cpp.
References B, Create(), llvm::object::Archive::create(), llvm::object::createBinary(), llvm::inconvertibleErrorCode(), and move.
Create() [2/3]
Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > llvm::orc::StaticLibraryDefinitionGenerator::Create (ObjectLayer & L, std::unique_ptr< MemoryBuffer > ArchiveBuffer, GetObjectFileInterface GetObjFileInterface = GetObjectFileInterface()) static
Try to create a StaticLibrarySearchGenerator from the given memory buffer.
This call will succeed if the buffer contains a valid archive, otherwise it will return an error.
Definition at line 345 of file ExecutionUtils.cpp.
References Create(), llvm::object::Archive::create(), and move.
Create() [3/3]
Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > llvm::orc::StaticLibraryDefinitionGenerator::Create (ObjectLayer & L, std::unique_ptr< MemoryBuffer > ArchiveBuffer, std::unique_ptr< object::Archive > Archive, GetObjectFileInterface GetObjFileInterface = GetObjectFileInterface()) static
Try to create a StaticLibrarySearchGenerator from the given memory buffer and Archive object.
Definition at line 326 of file ExecutionUtils.cpp.
Referenced by Create(), and Load().
getImportedDynamicLibraries()
const std::set<std::string>& llvm::orc::StaticLibraryDefinitionGenerator::getImportedDynamicLibraries () const inline
Returns a list of filenames of dynamic libraries that this archive has imported.
This class does not load these libraries by itself. User is responsible for making sure these libraries are avaliable to the JITDylib.
Definition at line 315 of file ExecutionUtils.h.
Load() [1/2]
Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > llvm::orc::StaticLibraryDefinitionGenerator::Load (ObjectLayer & L, const char * FileName, const Triple & TT, GetObjectFileInterface GetObjFileInterface = GetObjectFileInterface()) static
Try to create a StaticLibraryDefinitionGenerator from the given path.
This call will succeed if the file at the given path is a static library or a MachO universal binary containing a static library that is compatible with the given triple. Otherwise it will return an error.
Definition at line 286 of file ExecutionUtils.cpp.
References B, Create(), llvm::object::createBinary(), llvm::createFileError(), llvm::formatv(), llvm::MemoryBuffer::getFileSlice(), llvm::inconvertibleErrorCode(), and move.
Load() [2/2]
Expected< std::unique_ptr< StaticLibraryDefinitionGenerator > > llvm::orc::StaticLibraryDefinitionGenerator::Load (ObjectLayer & L, const char * FileName, GetObjectFileInterface GetObjFileInterface = GetObjectFileInterface()) static
Try to create a StaticLibraryDefinitionGenerator from the given path.
This call will succeed if the file at the given path is a static library is a valid archive, otherwise it will return an error.
Definition at line 274 of file ExecutionUtils.cpp.
References Create(), llvm::createFileError(), llvm::MemoryBuffer::getFile(), and move.
Referenced by llvm::orc::MachOPlatform::Create(), llvm::orc::ELFNixPlatform::Create(), and LLVMOrcCreateStaticLibrarySearchGeneratorForPath().
tryToGenerate()
Error llvm::orc::StaticLibraryDefinitionGenerator::tryToGenerate (LookupState & LS, LookupKind K, JITDylib & JD, JITDylibLookupFlags JDLookupFlags, const SymbolLookupSet & LookupSet) override virtual
DefinitionGenerators should override this method to insert new definitions into the parent JITDylib.
K specifies the kind of this lookup. JD specifies the target JITDylib being searched, and JDLookupFlags specifies whether the search should match against hidden symbols. Finally, Symbols describes the set of unresolved symbols and their associated lookup flags.
Implements llvm::orc::DefinitionGenerator.
Definition at line 395 of file ExecutionUtils.cpp.
References llvm::orc::ObjectLayer::getExecutionSession(), I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::orc::Static, and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ExecutionUtils.h
lib/ExecutionEngine/Orc/ExecutionUtils.cpp