LLVM: llvm::AMDGPUPALMetadata Class Reference
llvm::AMDGPUPALMetadata Class Reference
#include "Target/AMDGPU/Utils/AMDGPUPALMetadata.h"
Public Member Functions
void readFromIR (Module &M)
bool setFromBlob (unsigned Type, StringRef Blob)
void setRsrc1 (unsigned CC, unsigned Val)
void setRsrc2 (unsigned CC, unsigned Val)
void setSpiPsInputEna (unsigned Val)
void setSpiPsInputAddr (unsigned Val)
unsigned getRegister (unsigned Reg)
void setRegister (unsigned Reg, unsigned Val)
void setEntryPoint (unsigned CC, StringRef Name)
void setNumUsedVgprs (unsigned CC, unsigned Val)
void setNumUsedAgprs (unsigned CC, unsigned Val)
void setNumUsedSgprs (unsigned CC, unsigned Val)
void setScratchSize (unsigned CC, unsigned Val)
void setFunctionScratchSize (const MachineFunction &MF, unsigned Val)
void setFunctionLdsSize (const MachineFunction &MF, unsigned Val)
void setFunctionNumUsedVgprs (const MachineFunction &MF, unsigned Val)
void setFunctionNumUsedSgprs (const MachineFunction &MF, unsigned Val)
void setWave32 (unsigned CC)
void toString (std::string &S)
bool setFromString (StringRef S)
const char * getVendor () const
unsigned getType () const
void toBlob (unsigned Type, std::string &S)
msgpack::Document * getMsgPackDoc ()
void setLegacy ()
void reset ()
Detailed Description
Definition at line 24 of file AMDGPUPALMetadata.h.
Member Function Documentation
getMsgPackDoc()
msgpack::Document* llvm::AMDGPUPALMetadata::getMsgPackDoc () inline
Definition at line 127 of file AMDGPUPALMetadata.h.
getRegister()
unsigned AMDGPUPALMetadata::getRegister (unsigned Reg)
Definition at line 161 of file AMDGPUPALMetadata.cpp.
References N, and llvm::msgpack::UInt.
getType()
unsigned AMDGPUPALMetadata::getType () const
Definition at line 857 of file AMDGPUPALMetadata.cpp.
Referenced by llvm::AMDGPUTargetELFStreamer::finish().
getVendor()
const char * AMDGPUPALMetadata::getVendor () const
Definition at line 849 of file AMDGPUPALMetadata.cpp.
References llvm::AMDGPU::ElfNote::NoteNameV2, and llvm::AMDGPU::ElfNote::NoteNameV3.
Referenced by llvm::AMDGPUTargetELFStreamer::finish().
readFromIR()
void AMDGPUPALMetadata::readFromIR (Module & M)
Definition at line 31 of file AMDGPUPALMetadata.cpp.
References E, I, M, llvm::ELF::NT_AMD_PAL_METADATA, and llvm::ELF::NT_AMDGPU_METADATA.
reset()
void AMDGPUPALMetadata::reset ()
Definition at line 872 of file AMDGPUPALMetadata.cpp.
References Registers.
Referenced by llvm::AMDGPUTargetAsmStreamer::finish(), and llvm::AMDGPUTargetELFStreamer::finish().
setEntryPoint()
void AMDGPUPALMetadata::setEntryPoint (unsigned CC, StringRef Name)
Definition at line 188 of file AMDGPUPALMetadata.cpp.
References CC.
setFromBlob()
bool AMDGPUPALMetadata::setFromBlob (unsigned Type, StringRef Blob)
Definition at line 70 of file AMDGPUPALMetadata.cpp.
References llvm::ELF::NT_AMD_PAL_METADATA.
setFromString()
bool AMDGPUPALMetadata::setFromString (StringRef S)
Definition at line 742 of file AMDGPUPALMetadata.cpp.
References llvm::errs(), I, llvm::ELF::NT_AMDGPU_METADATA, Registers, S, llvm::msgpack::String, and uint64_t.
setFunctionLdsSize()
void AMDGPUPALMetadata::setFunctionLdsSize (const MachineFunction & MF, unsigned Val)
Definition at line 252 of file AMDGPUPALMetadata.cpp.
setFunctionNumUsedSgprs()
void AMDGPUPALMetadata::setFunctionNumUsedSgprs (const MachineFunction & MF, unsigned Val)
Definition at line 266 of file AMDGPUPALMetadata.cpp.
setFunctionNumUsedVgprs()
void AMDGPUPALMetadata::setFunctionNumUsedVgprs (const MachineFunction & MF, unsigned Val)
Definition at line 259 of file AMDGPUPALMetadata.cpp.
setFunctionScratchSize()
void AMDGPUPALMetadata::setFunctionScratchSize (const MachineFunction & MF, unsigned Val)
Definition at line 245 of file AMDGPUPALMetadata.cpp.
setLegacy()
void AMDGPUPALMetadata::setLegacy ()
Definition at line 867 of file AMDGPUPALMetadata.cpp.
References llvm::ELF::NT_AMD_PAL_METADATA.
setNumUsedAgprs()
void AMDGPUPALMetadata::setNumUsedAgprs (unsigned CC, unsigned Val)
Definition at line 213 of file AMDGPUPALMetadata.cpp.
References CC.
setNumUsedSgprs()
void AMDGPUPALMetadata::setNumUsedSgprs (unsigned CC, unsigned Val)
Definition at line 220 of file AMDGPUPALMetadata.cpp.
References CC, getScratchSizeKey(), llvm::AMDGPU::PALMD::VS_NUM_USED_SGPRS, and llvm::AMDGPU::PALMD::VS_SCRATCH_SIZE.
setNumUsedVgprs()
void AMDGPUPALMetadata::setNumUsedVgprs (unsigned CC, unsigned Val)
Definition at line 199 of file AMDGPUPALMetadata.cpp.
References CC, getScratchSizeKey(), llvm::AMDGPU::PALMD::VS_NUM_USED_VGPRS, and llvm::AMDGPU::PALMD::VS_SCRATCH_SIZE.
setRegister()
void AMDGPUPALMetadata::setRegister (unsigned Reg, unsigned Val)
Definition at line 174 of file AMDGPUPALMetadata.cpp.
References N, and llvm::msgpack::UInt.
setRsrc1()
void AMDGPUPALMetadata::setRsrc1 (unsigned CC, unsigned Val)
Definition at line 138 of file AMDGPUPALMetadata.cpp.
References CC, and getRsrc1Reg().
setRsrc2()
void AMDGPUPALMetadata::setRsrc2 (unsigned CC, unsigned Val)
Definition at line 144 of file AMDGPUPALMetadata.cpp.
References CC, and getRsrc1Reg().
setScratchSize()
void AMDGPUPALMetadata::setScratchSize (unsigned CC, unsigned Val)
Definition at line 234 of file AMDGPUPALMetadata.cpp.
References CC, and getScratchSizeKey().
setSpiPsInputAddr()
void AMDGPUPALMetadata::setSpiPsInputAddr (unsigned Val)
Definition at line 156 of file AMDGPUPALMetadata.cpp.
References llvm::AMDGPU::PALMD::R_A1B4_SPI_PS_INPUT_ADDR.
setSpiPsInputEna()
void AMDGPUPALMetadata::setSpiPsInputEna (unsigned Val)
Definition at line 150 of file AMDGPUPALMetadata.cpp.
References llvm::AMDGPU::PALMD::R_A1B3_SPI_PS_INPUT_ENA.
setWave32()
void AMDGPUPALMetadata::setWave32 (unsigned CC)
Definition at line 274 of file AMDGPUPALMetadata.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, CC, llvm::AMDGPU::PALMD::R_2E00_COMPUTE_DISPATCH_INITIATOR, llvm::AMDGPU::PALMD::R_A1B6_SPI_PS_IN_CONTROL, llvm::AMDGPU::PALMD::R_A2D5_VGT_SHADER_STAGES_EN, S_00B800_CS_W32_EN, S_0286D8_PS_W32_EN, S_028B54_GS_W32_EN, S_028B54_HS_W32_EN, and S_028B54_VS_W32_EN.
toBlob()
void AMDGPUPALMetadata::toBlob (unsigned Type, std::string & S)
Definition at line 716 of file AMDGPUPALMetadata.cpp.
References llvm::ELF::NT_AMD_PAL_METADATA.
Referenced by llvm::AMDGPUTargetELFStreamer::finish().
toString()
void AMDGPUPALMetadata::toString (std::string & S)
Definition at line 664 of file AMDGPUPALMetadata.cpp.
References llvm::AMDGPU::PALMD::AssemblerDirective, llvm::AMDGPU::PALMD::AssemblerDirectiveBegin, llvm::AMDGPU::PALMD::AssemblerDirectiveEnd, E, getRegisterName(), I, llvm::msgpack::Nil, RegName, and llvm::Twine::utohexstr().
Referenced by llvm::AMDGPUTargetAsmStreamer::finish().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUPALMetadata.h
lib/Target/AMDGPU/Utils/AMDGPUPALMetadata.cpp