LLVM: llvm::CSKYInstrInfo Class Reference
llvm::CSKYInstrInfo Class Reference
#include "Target/CSKY/CSKYInstrInfo.h"
Public Member Functions
CSKYInstrInfo (CSKYSubtarget &STI)
unsigned isLoadFromStackSlot (const MachineInstr &MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr &MI, int &FrameIndex) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, Register SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, Register DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify=false) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
MachineBasicBlock * getBranchDestBlock (const MachineInstr &MI) const override
unsigned getInstSizeInBytes (const MachineInstr &MI) const override
Register getGlobalBaseReg (MachineFunction &MF) const
Register movImm (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, uint64_t Val, MachineInstr::MIFlag Flag=MachineInstr::NoFlags) const
Protected Attributes
const CSKYSubtarget & STI
Detailed Description
Definition at line 26 of file CSKYInstrInfo.h.
Constructor & Destructor Documentation
CSKYInstrInfo()
CSKYInstrInfo::CSKYInstrInfo (CSKYSubtarget & STI) explicit
Definition at line 27 of file CSKYInstrInfo.cpp.
References llvm::CSKYSubtarget::hasFPUv2DoubleFloat(), llvm::CSKYSubtarget::hasFPUv2SingleFloat(), llvm::CSKYSubtarget::hasFPUv3DoubleFloat(), llvm::CSKYSubtarget::hasFPUv3SingleFloat(), and STI.
Member Function Documentation
analyzeBranch()
bool CSKYInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify = false) const override
Definition at line 45 of file CSKYInstrInfo.cpp.
References Cond, llvm::MachineBasicBlock::end(), getBranchDestBlock(), llvm::HexagonMCInstrInfo::getDesc(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineInstrBundleIterator< Ty, IsReverse >::getReverse(), I, MBB, parseCondBranch(), llvm::MachineBasicBlock::rend(), and TBB.
copyPhysReg()
void CSKYInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 478 of file CSKYInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), contains(), llvm::dbgs(), llvm::RegState::Define, DL, llvm::get(), llvm::getDeadRegState(), llvm::getKillRegState(), llvm::CSKYSubtarget::hasE2(), I, LLVM_DEBUG, llvm_unreachable, MBB, and STI.
getBranchDestBlock()
MachineBasicBlock * CSKYInstrInfo::getBranchDestBlock (const MachineInstr & MI) const override
Definition at line 146 of file CSKYInstrInfo.cpp.
References assert(), and MI.
Referenced by analyzeBranch().
getGlobalBaseReg()
Register CSKYInstrInfo::getGlobalBaseReg (MachineFunction & MF) const
Definition at line 566 of file CSKYInstrInfo.cpp.
References llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addMemOperand(), llvm::CSKYCP::ADDR, llvm::MachineInstrBuilder::addReg(), Align, llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::CSKYConstantPoolSymbol::Create(), llvm::MachineRegisterInfo::createVirtualRegister(), DL, llvm::MachineFunction::front(), llvm::get(), llvm::MachinePointerInfo::getConstantPool(), llvm::MachineFunction::getConstantPool(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::CSKYMachineFunctionInfo::getGlobalBaseReg(), llvm::MachineFunction::getInfo(), llvm::Type::getInt32Ty(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFunction::getRegInfo(), llvm::PPCISD::GlobalBaseReg, MBBI, llvm::MachineMemOperand::MOLoad, MRI, and llvm::CSKYMachineFunctionInfo::setGlobalBaseReg().
getInstSizeInBytes()
unsigned CSKYInstrInfo::getInstSizeInBytes (const MachineInstr & MI) const override
Definition at line 602 of file CSKYInstrInfo.cpp.
References llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getTarget(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, and MI.
Referenced by insertBranch(), and removeBranch().
insertBranch()
unsigned CSKYInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 154 of file CSKYInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), Cond, DL, llvm::get(), getInstSizeInBytes(), MBB, MI, and TBB.
isLoadFromStackSlot()
unsigned CSKYInstrInfo::isLoadFromStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 333 of file CSKYInstrInfo.cpp.
References llvm::ISD::FrameIndex, and MI.
isStoreToStackSlot()
unsigned CSKYInstrInfo::isStoreToStackSlot (const MachineInstr & MI, int & FrameIndex) const override
Definition at line 363 of file CSKYInstrInfo.cpp.
References llvm::ISD::FrameIndex, and MI.
loadRegFromStackSlot()
void CSKYInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, Register DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg) const override
Definition at line 435 of file CSKYInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::end(), llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineBasicBlock::getParent(), I, llvm_unreachable, MBB, llvm::MachineMemOperand::MOLoad, and llvm::CSKYMachineFunctionInfo::setSpillsCR().
movImm()
Register CSKYInstrInfo::movImm (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, uint64_t Val, MachineInstr::MIFlag Flag = MachineInstr::NoFlags) const
Definition at line 224 of file CSKYInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), DL, llvm::get(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::CSKYSubtarget::hasE2(), MBB, MBBI, MRI, llvm::report_fatal_error(), llvm::MachineInstrBuilder::setMIFlags(), and STI.
removeBranch()
unsigned CSKYInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 113 of file CSKYInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), getInstSizeInBytes(), llvm::MachineBasicBlock::getLastNonDebugInstr(), I, and MBB.
reverseBranchCondition()
bool CSKYInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 217 of file CSKYInstrInfo.cpp.
References assert(), Cond, and getOppositeBranchOpc().
storeRegToStackSlot()
void CSKYInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, Register SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg) const override
Definition at line 391 of file CSKYInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::end(), llvm::get(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineBasicBlock::getParent(), I, llvm_unreachable, MBB, llvm::MachineMemOperand::MOStore, and llvm::CSKYMachineFunctionInfo::setSpillsCR().
Member Data Documentation
STI
const CSKYSubtarget& llvm::CSKYInstrInfo::STI protected
Definition at line 33 of file CSKYInstrInfo.h.
Referenced by copyPhysReg(), CSKYInstrInfo(), and movImm().
The documentation for this class was generated from the following files:
lib/Target/CSKY/CSKYInstrInfo.h
lib/Target/CSKY/CSKYInstrInfo.cpp