LLVM: llvm::GCNMaxILPSchedStrategy Class Reference
llvm::GCNMaxILPSchedStrategy Class Reference final
The goal of this scheduling strategy is to maximize ILP for a single wave (i.e.
#include "Target/AMDGPU/GCNSchedStrategy.h"
Public Member Functions
GCNMaxILPSchedStrategy (const MachineSchedContext *C)
Public Member Functions inherited from llvm::GCNSchedStrategy
GCNSchedStrategy (const MachineSchedContext *C)
SUnit * pickNode (bool &IsTopNode) override
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
void initialize (ScheduleDAGMI *DAG) override
Initialize the strategy after building the DAG for a new region.
unsigned getTargetOccupancy ()
void setTargetOccupancy (unsigned Occ)
GCNSchedStageID getCurrentStage ()
bool advanceStage ()
bool hasNextStage () const
GCNSchedStageID getNextStage () const
Public Member Functions inherited from llvm::GenericScheduler
GenericScheduler (const MachineSchedContext *C)
void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) override
Initialize the per-region scheduling policy.
void dumpPolicy () const override
bool shouldTrackPressure () const override
Check if pressure tracking is needed before building the DAG and initializing this strategy.
bool shouldTrackLaneMasks () const override
Returns true if lanemasks should be tracked.
void schedNode (SUnit *SU, bool IsTopNode) override
Update the scheduler's state after scheduling a node.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
void registerRoots () override
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual bool doMBBSchedRegionsTopDown () const
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
Protected Member Functions
bool tryCandidate (SchedCandidate &Cand, SchedCandidate &TryCand, SchedBoundary *Zone) const override
Apply a set of heuristics to a new candidate.
Protected Member Functions inherited from llvm::GCNSchedStrategy
SUnit * pickNodeBidirectional (bool &IsTopNode)
void pickNodeFromQueue (SchedBoundary &Zone, const CandPolicy &ZonePolicy, const RegPressureTracker &RPTracker, SchedCandidate &Cand)
void initCandidate (SchedCandidate &Cand, SUnit *SU, bool AtTop, const RegPressureTracker &RPTracker, const SIRegisterInfo *SRI, unsigned SGPRPressure, unsigned VGPRPressure)
Protected Member Functions inherited from llvm::GenericScheduler
void checkAcyclicLatency ()
Set IsAcyclicLatencyLimited if the acyclic path is longer than the cyclic critical path by more cycles than it takes to drain the instruction buffer.
void initCandidate (SchedCandidate &Cand, SUnit *SU, bool AtTop, const RegPressureTracker &RPTracker, RegPressureTracker &TempTracker)
SUnit * pickNodeBidirectional (bool &IsTopNode)
Pick the best candidate node from either the top or bottom queue.
void pickNodeFromQueue (SchedBoundary &Zone, const CandPolicy &ZonePolicy, const RegPressureTracker &RPTracker, SchedCandidate &Candidate)
Pick the best candidate from the queue.
void reschedulePhysReg (SUnit *SU, bool isTop)
Protected Member Functions inherited from llvm::GenericSchedulerBase
GenericSchedulerBase (const MachineSchedContext *C)
void setPolicy (CandPolicy &Policy, bool IsPostRA, SchedBoundary &CurrZone, SchedBoundary *OtherZone)
Set the CandPolicy given a scheduling zone given the current resources and latencies inside and outside the zone.
void traceCandidate (const SchedCandidate &Cand)
Additional Inherited Members
Public Types inherited from llvm::GenericSchedulerBase
enum CandReason : uint8_t {
NoCand, Only1, PhysReg, RegExcess,
RegCritical, Stall, Cluster, Weak,
RegMax, ResourceReduce, ResourceDemand, BotHeightReduce,
BotPathReduce, TopDepthReduce, TopPathReduce, NextDefUse,
NodeOrder
}
Represent the type of SchedCandidate found within a single queue.
Static Public Member Functions inherited from llvm::GenericSchedulerBase
static const char * getReasonStr (GenericSchedulerBase::CandReason Reason)
Public Attributes inherited from llvm::GCNSchedStrategy
bool HasHighPressure
bool KnownExcessRP = false
unsigned ErrorMargin = 3
const unsigned HighRPSGPRBias = 7
const unsigned HighRPVGPRBias = 7
unsigned SGPRCriticalLimit
unsigned VGPRCriticalLimit
unsigned SGPRLimitBias = 0
unsigned VGPRLimitBias = 0
Protected Attributes inherited from llvm::GCNSchedStrategy
std::vector< unsigned > Pressure
std::vector< unsigned > MaxPressure
unsigned SGPRExcessLimit
unsigned VGPRExcessLimit
unsigned TargetOccupancy
MachineFunction * MF
SmallVector< GCNSchedStageID, 4 > SchedStages
SmallVectorImpl< GCNSchedStageID >::iterator CurrentStage = nullptr
Protected Attributes inherited from llvm::GenericScheduler
ScheduleDAGMILive * DAG = nullptr
MachineSchedPolicy RegionPolicy
SchedBoundary Top
SchedBoundary Bot
SchedCandidate TopCand
Candidate last picked from Top boundary.
SchedCandidate BotCand
Candidate last picked from Bot boundary.
Protected Attributes inherited from llvm::GenericSchedulerBase
const MachineSchedContext * Context
const TargetSchedModel * SchedModel = nullptr
const TargetRegisterInfo * TRI = nullptr
SchedRemainder Rem
Detailed Description
The goal of this scheduling strategy is to maximize ILP for a single wave (i.e.
latency hiding).
Definition at line 130 of file GCNSchedStrategy.h.
Constructor & Destructor Documentation
GCNMaxILPSchedStrategy()
GCNMaxILPSchedStrategy::GCNMaxILPSchedStrategy (const MachineSchedContext * C)
Definition at line 378 of file GCNSchedStrategy.cpp.
References llvm::ILPInitialSchedule, and llvm::GCNSchedStrategy::SchedStages.
Member Function Documentation
tryCandidate()
bool GCNMaxILPSchedStrategy::tryCandidate (SchedCandidate & Cand, SchedCandidate & TryCand, SchedBoundary * Zone) const override protected virtual
Apply a set of heuristics to a new candidate.
Heuristics are currently hierarchical. This may be more efficient than a graduated cost model because we don't need to evaluate all aspects of the model for each node in the queue. But it's really done to make the heuristics easier to debug and statistically analyze.
Parameters
Cand provides the policy and current best candidate.
TryCand refers to the next SUnit candidate, otherwise uninitialized.
Zone describes the scheduled zone that we are extending, or nullptr if Cand is from a different zone than TryCand.
Returns
true if TryCand is better than Cand (Reason is NOT NoCand)
Reimplemented from llvm::GenericScheduler.
Definition at line 383 of file GCNSchedStrategy.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, llvm::biasPhysReg(), llvm::GenericSchedulerBase::Cluster, llvm::RegPressureDelta::CriticalMax, llvm::GenericSchedulerBase::SchedResourceDelta::CritResources, llvm::RegPressureDelta::CurrentMax, llvm::GenericScheduler::DAG, llvm::GenericSchedulerBase::SchedResourceDelta::DemandedResources, llvm::RegPressureDelta::Excess, llvm::SchedBoundary::getLatencyStallCycles(), llvm::ScheduleDAGMI::getNextClusterPred(), llvm::ScheduleDAGMI::getNextClusterSucc(), llvm::getWeakLeft(), llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), llvm::SchedBoundary::isTop(), llvm::ScheduleDAGMILive::isTrackingPressure(), llvm::GenericSchedulerBase::SchedCandidate::isValid(), llvm::ScheduleDAG::MF, llvm::GenericSchedulerBase::NoCand, llvm::SUnit::NodeNum, llvm::GenericSchedulerBase::NodeOrder, llvm::GenericSchedulerBase::PhysReg, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::RegCritical, llvm::GenericSchedulerBase::RegExcess, llvm::GenericSchedulerBase::RegMax, llvm::GenericSchedulerBase::SchedCandidate::ResDelta, llvm::GenericSchedulerBase::ResourceDemand, llvm::GenericSchedulerBase::ResourceReduce, llvm::GenericSchedulerBase::SchedCandidate::RPDelta, llvm::GenericSchedulerBase::SchedModel, llvm::GenericSchedulerBase::Stall, llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::GenericSchedulerBase::TRI, llvm::tryGreater(), llvm::tryLatency(), llvm::tryLess(), llvm::tryPressure(), and llvm::GenericSchedulerBase::Weak.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSchedStrategy.h
lib/Target/AMDGPU/GCNSchedStrategy.cpp