LLVM: llvm::BCFixed< Width > Class Template Reference
llvm::BCFixed< Width > Class Template Reference
Represents a fixed-width value in a bitcode record.
#include "llvm/Bitcode/BitcodeConvenience.h"
Static Public Member Functions
static void emitOp (llvm::BitCodeAbbrev &abbrev)
static void assertValid (const bool &data)
template<typename T >
static void assertValid (const T &data)
Static Public Member Functions inherited from llvm::detail::BCField<>
static void assertValid (const T &data)
Asserts that the given data is a valid value for this field.
static T convert (T rawValue)
Converts a raw numeric representation of this value to its preferred type.
Additional Inherited Members
Static Public Attributes inherited from llvm::detail::BCField<>
static const bool IsCompound
Detailed Description
template<unsigned Width>
class llvm::BCFixed< Width >
Represents a fixed-width value in a bitcode record.
Note that the LLVM bitcode format only supports unsigned values.
Definition at line 78 of file BitcodeConvenience.h.
Member Function Documentation
assertValid() [1/2]
template<unsigned Width> static void llvm::BCFixed< Width >::assertValid (const bool & data) inline static
Definition at line 86 of file BitcodeConvenience.h.
References assert().
assertValid() [2/2]
template<unsigned Width> template<typename T > static void llvm::BCFixed< Width >::assertValid (const T & data) inline static
Definition at line 91 of file BitcodeConvenience.h.
References assert().
emitOp()
template<unsigned Width> static void llvm::BCFixed< Width >::emitOp (llvm::BitCodeAbbrev & abbrev) inline static
Definition at line 82 of file BitcodeConvenience.h.
References llvm::BitCodeAbbrev::Add(), and llvm::BitCodeAbbrevOp::Fixed.
The documentation for this class was generated from the following file:
include/llvm/Bitcode/BitcodeConvenience.h