LLVM: llvm::AppleAcceleratorTable::Entry Class Reference
llvm::AppleAcceleratorTable::Entry Class Reference final
Apple-specific implementation of an Accelerator Entry.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Member Functions
std::optional< uint64_t > getCUOffset () const override
Returns the Offset of the Compilation Unit associated with this Accelerator Entry or std::nullopt if the Compilation Unit offset is not recorded in this Accelerator Entry.
std::optional< uint64_t > getDIESectionOffset () const
Returns the Section Offset of the Debug Info Entry associated with this Accelerator Entry or std::nullopt if the DIE offset is not recorded in this Accelerator Entry.
std::optional< dwarf::Tag > getTag () const override
Returns the Tag of the Debug Info Entry associated with this Accelerator Entry or std::nullopt if the Tag is not recorded in this Accelerator Entry.
std::optional< DWARFFormValue > lookup (HeaderData::AtomType Atom) const
Returns the value of the Atom in this Accelerator Entry, if the Entry contains such Atom.
Public Member Functions inherited from llvm::DWARFAcceleratorTable::Entry
ArrayRef< DWARFFormValue > getValues () const
Returns the raw values of fields in the Accelerator Entry.
Friends
class AppleAcceleratorTable
class ValueIterator
Additional Inherited Members
Protected Member Functions inherited from llvm::DWARFAcceleratorTable::Entry
Entry ()=default
Entry (const Entry &)=default
Entry (Entry &&)=default
Entry & operator= (const Entry &)=default
Entry & operator= (Entry &&)=default
~Entry ()=default
Protected Attributes inherited from llvm::DWARFAcceleratorTable::Entry
SmallVector< DWARFFormValue, 3 > Values
Detailed Description
Apple-specific implementation of an Accelerator Entry.
Definition at line 117 of file DWARFAcceleratorTable.h.
Member Function Documentation
getCUOffset()
std::optional< uint64_t > AppleAcceleratorTable::Entry::getCUOffset () const override virtual
Returns the Offset of the Compilation Unit associated with this Accelerator Entry or std::nullopt if the Compilation Unit offset is not recorded in this Accelerator Entry.
Implements llvm::DWARFAcceleratorTable::Entry.
Definition at line 291 of file DWARFAcceleratorTable.cpp.
References llvm::dwarf::DW_ATOM_cu_offset, and lookup().
getDIESectionOffset()
std::optional< uint64_t > AppleAcceleratorTable::Entry::getDIESectionOffset () const
Returns the Section Offset of the Debug Info Entry associated with this Accelerator Entry or std::nullopt if the DIE offset is not recorded in this Accelerator Entry.
The returned offset is relative to the start of the Section containing the DIE.
Definition at line 287 of file DWARFAcceleratorTable.cpp.
References llvm::dwarf::DW_ATOM_die_offset, and lookup().
getTag()
std::optional< dwarf::Tag > AppleAcceleratorTable::Entry::getTag () const override virtual
Returns the Tag of the Debug Info Entry associated with this Accelerator Entry or std::nullopt if the Tag is not recorded in this Accelerator Entry.
Implements llvm::DWARFAcceleratorTable::Entry.
Definition at line 295 of file DWARFAcceleratorTable.cpp.
References llvm::dwarf::DW_ATOM_die_tag, and lookup().
lookup()
std::optional< DWARFFormValue > AppleAcceleratorTable::Entry::lookup (HeaderData::AtomType Atom) const
Returns the value of the Atom in this Accelerator Entry, if the Entry contains such Atom.
Definition at line 276 of file DWARFAcceleratorTable.cpp.
References assert(), and llvm::zip_first().
Friends And Related Function Documentation
AppleAcceleratorTable
friend class AppleAcceleratorTable friend
Definition at line 140 of file DWARFAcceleratorTable.h.
ValueIterator
friend class ValueIterator friend
Definition at line 141 of file DWARFAcceleratorTable.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp