LLVM: llvm::dwarf::FDE Class Reference
llvm::dwarf::FDE Class Reference
DWARF Frame Description Entry (FDE)
#include "llvm/DebugInfo/DWARF/DWARFDebugFrame.h"
Public Member Functions
FDE (bool IsDWARF64, uint64_t Offset, uint64_t Length, uint64_t CIEPointer, uint64_t InitialLocation, uint64_t AddressRange, CIE *Cie, std::optional< uint64_t > LSDAAddress, Triple::ArchType Arch)
~FDE () override=default
const CIE * getLinkedCIE () const
uint64_t getCIEPointer () const
uint64_t getInitialLocation () const
uint64_t getAddressRange () const
std::optional< uint64_t > getLSDAAddress () const
void dump (raw_ostream &OS, DIDumpOptions DumpOpts) const override
Dump the instructions in this CFI fragment.
Public Member Functions inherited from llvm::dwarf::FrameEntry
FrameEntry (FrameKind K, bool IsDWARF64, uint64_t Offset, uint64_t Length, uint64_t CodeAlign, int64_t DataAlign, Triple::ArchType Arch)
virtual ~FrameEntry ()=default
FrameKind getKind () const
uint64_t getOffset () const
uint64_t getLength () const
const CFIProgram & cfis () const
CFIProgram & cfis ()
Static Public Member Functions
static bool classof (const FrameEntry *FE)
Additional Inherited Members
Public Types inherited from llvm::dwarf::FrameEntry
enum FrameKind { FK_CIE, FK_FDE }
Protected Attributes inherited from llvm::dwarf::FrameEntry
const FrameKind Kind
const bool IsDWARF64
const uint64_t Offset
Offset of this entry in the section.
const uint64_t Length
Entry length as specified in DWARF.
CFIProgram CFIs
Detailed Description
DWARF Frame Description Entry (FDE)
Definition at line 629 of file DWARFDebugFrame.h.
Constructor & Destructor Documentation
FDE()
llvm::dwarf::FDE::FDE (bool IsDWARF64, uint64_t Offset, uint64_t Length, uint64_t CIEPointer, uint64_t InitialLocation, uint64_t AddressRange, CIE * Cie, std::optional< uint64_t > LSDAAddress, Triple::ArchType Arch) inline
Definition at line 631 of file DWARFDebugFrame.h.
~FDE()
llvm::dwarf::FDE::~FDE () override default
Member Function Documentation
classof()
static bool llvm::dwarf::FDE::classof (const FrameEntry * FE) inline static
Definition at line 650 of file DWARFDebugFrame.h.
References llvm::dwarf::FrameEntry::FK_FDE, and llvm::dwarf::FrameEntry::getKind().
dump()
void FDE::dump (raw_ostream & OS, DIDumpOptions DumpOpts) const override virtual
Dump the instructions in this CFI fragment.
Implements llvm::dwarf::FrameEntry.
Definition at line 992 of file DWARFDebugFrame.cpp.
References llvm::dwarf::UnwindTable::create(), llvm::createStringError(), llvm::format(), llvm::dwarf::FormatString(), llvm::invalid_argument, llvm::DIDumpOptions::IsEH, llvm::joinErrors(), llvm::Length, OS, and llvm::DIDumpOptions::RecoverableErrorHandler.
getAddressRange()
uint64_t llvm::dwarf::FDE::getAddressRange () const inline
Definition at line 645 of file DWARFDebugFrame.h.
Referenced by llvm::dwarf::UnwindTable::create().
getCIEPointer()
uint64_t llvm::dwarf::FDE::getCIEPointer () const inline
Definition at line 643 of file DWARFDebugFrame.h.
getInitialLocation()
uint64_t llvm::dwarf::FDE::getInitialLocation () const inline
Definition at line 644 of file DWARFDebugFrame.h.
Referenced by llvm::dwarf::UnwindTable::create().
getLinkedCIE()
const CIE* llvm::dwarf::FDE::getLinkedCIE () const inline
Definition at line 642 of file DWARFDebugFrame.h.
Referenced by llvm::dwarf::UnwindTable::create().
getLSDAAddress()
std::optional<uint64_t> llvm::dwarf::FDE::getLSDAAddress () const inline
Definition at line 646 of file DWARFDebugFrame.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugFrame.h
lib/DebugInfo/DWARF/DWARFDebugFrame.cpp