LLVM: llvm::memprof::FrameLookupTrait Class Reference
llvm::memprof::FrameLookupTrait Class Reference
#include "llvm/ProfileData/MemProf.h"
Public Types
using data_type = const Frame
using internal_key_type = FrameId
using external_key_type = FrameId
using hash_value_type = FrameId
using offset_type = uint64_t
Public Member Functions
hash_value_type ComputeHash (internal_key_type K)
uint64_t ReadKey (const unsigned char *D, offset_type)
data_type ReadData (uint64_t K, const unsigned char *D, offset_type)
Static Public Member Functions
static bool EqualKey (internal_key_type A, internal_key_type B)
static uint64_t GetInternalKey (internal_key_type K)
static uint64_t GetExternalKey (external_key_type K)
static std::pair< offset_type, offset_type > ReadKeyDataLength (const unsigned char *&D)
Detailed Description
Definition at line 576 of file MemProf.h.
Member Typedef Documentation
data_type
using llvm::memprof::FrameLookupTrait::data_type = const Frame
Definition at line 578 of file MemProf.h.
external_key_type
using llvm::memprof::FrameLookupTrait::external_key_type = FrameId
Definition at line 580 of file MemProf.h.
hash_value_type
using llvm::memprof::FrameLookupTrait::hash_value_type = FrameId
Definition at line 581 of file MemProf.h.
internal_key_type
using llvm::memprof::FrameLookupTrait::internal_key_type = FrameId
Definition at line 579 of file MemProf.h.
offset_type
using llvm::memprof::FrameLookupTrait::offset_type = uint64_t
Definition at line 582 of file MemProf.h.
Member Function Documentation
ComputeHash()
hash_value_type llvm::memprof::FrameLookupTrait::ComputeHash (internal_key_type K) inline
Definition at line 590 of file MemProf.h.
EqualKey()
static bool llvm::memprof::FrameLookupTrait::EqualKey (internal_key_type A, internal_key_type B) inline static
Definition at line 584 of file MemProf.h.
References B.
GetExternalKey()
static uint64_t llvm::memprof::FrameLookupTrait::GetExternalKey (external_key_type K) inline static
Definition at line 588 of file MemProf.h.
GetInternalKey()
static uint64_t llvm::memprof::FrameLookupTrait::GetInternalKey (internal_key_type K) inline static
Definition at line 587 of file MemProf.h.
ReadData()
data_type llvm::memprof::FrameLookupTrait::ReadData (uint64_t K, const unsigned char * D, offset_type) inline
Definition at line 606 of file MemProf.h.
References D, and llvm::memprof::Frame::deserialize().
ReadKey()
uint64_t llvm::memprof::FrameLookupTrait::ReadKey (const unsigned char * D, offset_type) inline
Definition at line 601 of file MemProf.h.
References D, and support().
ReadKeyDataLength()
static std::pair<offset_type, offset_type> llvm::memprof::FrameLookupTrait::ReadKeyDataLength (const unsigned char *& D) inline static
Definition at line 593 of file MemProf.h.
References D, and support().
The documentation for this class was generated from the following file:
include/llvm/ProfileData/MemProf.h