LLVM: llvm::OpenMPIRBuilder Class Reference
llvm::OpenMPIRBuilder Class Reference
An interface to create LLVM-IR for OpenMP directives.
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
Classes
struct AtomicOpValue
a struct to pack relevant information while generating atomic Ops
struct DependData
A struct to pack the relevant information for an OpenMP depend clause.
struct FinalizationInfo
struct LocationDescription
Description of a LLVM-IR insertion point (IP) and a debug/source location (filename, line, column, ...).
struct MapperAllocas
struct OutlineInfo
Helper that contains information about regions we need to outline during finalization.
struct ReductionInfo
Information about an OpenMP reduction.
class TargetDataInfo
Struct that keeps the information that should be kept throughout a 'target data' region.
struct TargetDataRTArgs
Container for the arguments used to pass data to the runtime library.
Public Types
enum EmitMetadataErrorKind { EMIT_MD_TARGET_REGION_ERROR, EMIT_MD_DECLARE_TARGET_ERROR, EMIT_MD_GLOBAL_VAR_LINK_ERROR }
The kind of errors that can occur when emitting the offload entries and metadata.
using InsertPointTy = IRBuilder<>::InsertPoint
Type used throughout for insertion points.
using FinalizeCallbackTy = std::function< void(InsertPointTy CodeGenIP)>
Callback type for variable finalization (think destructors).
using BodyGenCallbackTy = function_ref< void(InsertPointTy AllocaIP, InsertPointTy CodeGenIP)>
Callback type for body (=inner region) code generation.
using StorableBodyGenCallbackTy = std::function< void(InsertPointTy AllocaIP, InsertPointTy CodeGenIP)>
using LoopBodyGenCallbackTy = function_ref< void(InsertPointTy CodeGenIP, Value *IndVar)>
Callback type for loop body code generation.
using PrivatizeCallbackTy = function_ref< InsertPointTy(InsertPointTy AllocaIP, InsertPointTy CodeGenIP, Value &Original, Value &Inner, Value *&ReplVal)>
Callback type for variable privatization (think copy & default constructor).
using ReductionGenTy = function_ref< InsertPointTy(InsertPointTy, Value *, Value *, Value *&)>
Functions used to generate reductions.
using AtomicReductionGenTy = function_ref< InsertPointTy(InsertPointTy, Type *, Value *, Value *)>
Functions used to generate atomic reductions.
using EmitMetadataErrorReportFunctionTy = std::function< void(EmitMetadataErrorKind, TargetRegionEntryInfo)>
Callback function type.
using FunctionGenCallback = std::function< Function *(StringRef FunctionName)>
Functions used to generate a function with the given name.
Public Member Functions
OpenMPIRBuilder (Module &M)
Create a new OpenMPIRBuilder operating on the given module M.
~OpenMPIRBuilder ()
void initialize ()
Initialize the internal state, this will put structures types and potentially other helpers into the underlying module.
void setConfig (OpenMPIRBuilderConfig C)
void finalize (Function *Fn=nullptr)
Finalize the underlying module, e.g., by outlining regions.
void addAttributes (omp::RuntimeFunction FnID, Function &Fn)
Add attributes known for FnID to Fn.
std::string createPlatformSpecificName (ArrayRef< StringRef > Parts) const
Get the create a name using the platform specific separators.
void pushFinalizationCB (const FinalizationInfo &FI)
Push a finalization callback on the finalization stack.
void popFinalizationCB ()
Pop the last finalization callback from the finalization stack.
InsertPointTy createBarrier (const LocationDescription &Loc, omp::Directive DK, bool ForceSimpleCall=false, bool CheckCancelFlag=true)
Emitter methods for OpenMP directives.
InsertPointTy createCancel (const LocationDescription &Loc, Value *IfCondition, omp::Directive CanceledDirective)
Generator for '#omp cancel'.
IRBuilder ::InsertPoint createParallel (const LocationDescription &Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB, PrivatizeCallbackTy PrivCB, FinalizeCallbackTy FiniCB, Value *IfCondition, Value *NumThreads, omp::ProcBindKind ProcBind, bool IsCancellable)
Generator for '#omp parallel'.
CanonicalLoopInfo * createCanonicalLoop (const LocationDescription &Loc, LoopBodyGenCallbackTy BodyGenCB, Value *TripCount, const Twine &Name="loop")
Generator for the control flow structure of an OpenMP canonical loop.
CanonicalLoopInfo * createCanonicalLoop (const LocationDescription &Loc, LoopBodyGenCallbackTy BodyGenCB, Value *Start, Value *Stop, Value *Step, bool IsSigned, bool InclusiveStop, InsertPointTy ComputeIP={}, const Twine &Name="loop")
Generator for the control flow structure of an OpenMP canonical loop.
CanonicalLoopInfo * collapseLoops (DebugLoc DL, ArrayRef< CanonicalLoopInfo * > Loops, InsertPointTy ComputeIP)
Collapse a loop nest into a single loop.
InsertPointTy applyWorkshareLoop (DebugLoc DL, CanonicalLoopInfo *CLI, InsertPointTy AllocaIP, bool NeedsBarrier, llvm::omp::ScheduleKind SchedKind=llvm::omp::OMP_SCHEDULE_Default, Value *ChunkSize=nullptr, bool HasSimdModifier=false, bool HasMonotonicModifier=false, bool HasNonmonotonicModifier=false, bool HasOrderedClause=false)
Modifies the canonical loop to be a workshare loop.
std::vector< CanonicalLoopInfo * > tileLoops (DebugLoc DL, ArrayRef< CanonicalLoopInfo * > Loops, ArrayRef< Value * > TileSizes)
Tile a loop nest.
void unrollLoopFull (DebugLoc DL, CanonicalLoopInfo *Loop)
Fully unroll a loop.
void unrollLoopHeuristic (DebugLoc DL, CanonicalLoopInfo *Loop)
Fully or partially unroll a loop.
void unrollLoopPartial (DebugLoc DL, CanonicalLoopInfo *Loop, int32_t Factor, CanonicalLoopInfo **UnrolledCLI)
Partially unroll a loop.
void applySimd (CanonicalLoopInfo *Loop, MapVector< Value *, Value * > AlignedVars, Value *IfCond, omp::OrderKind Order, ConstantInt *Simdlen, ConstantInt *Safelen)
Add metadata to simd-ize a loop.
void createFlush (const LocationDescription &Loc)
Generator for '#omp flush'.
void createTaskwait (const LocationDescription &Loc)
Generator for '#omp taskwait'.
void createTaskyield (const LocationDescription &Loc)
Generator for '#omp taskyield'.
InsertPointTy createTask (const LocationDescription &Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB, bool Tied=true, Value *Final=nullptr, Value *IfCondition=nullptr, SmallVector< DependData > Dependencies={})
Generator for #omp task
InsertPointTy createTaskgroup (const LocationDescription &Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB)
Generator for the taskgroup construct.
InsertPointTy createReductions (const LocationDescription &Loc, InsertPointTy AllocaIP, ArrayRef< ReductionInfo > ReductionInfos, bool IsNoWait=false)
Generator for '#omp reduction'.
InsertPointTy getInsertionPoint ()
}
bool updateToLocation (const LocationDescription &Loc)
Update the internal location to Loc.
FunctionCallee getOrCreateRuntimeFunction (Module &M, omp::RuntimeFunction FnID)
Return the function declaration for the runtime function with FnID.
Function * getOrCreateRuntimeFunctionPtr (omp::RuntimeFunction FnID)
Constant * getOrCreateSrcLocStr (StringRef LocStr, uint32_t &SrcLocStrSize)
Return the (LLVM-IR) string describing the source location LocStr.
Constant * getOrCreateDefaultSrcLocStr (uint32_t &SrcLocStrSize)
Return the (LLVM-IR) string describing the default source location.
Constant * getOrCreateSrcLocStr (StringRef FunctionName, StringRef FileName, unsigned Line, unsigned Column, uint32_t &SrcLocStrSize)
Return the (LLVM-IR) string describing the source location identified by the arguments.
Constant * getOrCreateSrcLocStr (DebugLoc DL, uint32_t &SrcLocStrSize, Function *F=nullptr)
Return the (LLVM-IR) string describing the DebugLoc DL.
Constant * getOrCreateSrcLocStr (const LocationDescription &Loc, uint32_t &SrcLocStrSize)
Return the (LLVM-IR) string describing the source location Loc.
Constant * getOrCreateIdent (Constant *SrcLocStr, uint32_t SrcLocStrSize, omp::IdentFlag Flags=omp::IdentFlag(0), unsigned Reserve2Flags=0)
Return an ident_t* encoding the source location SrcLocStr and Flags.
GlobalValue * createGlobalFlag (unsigned Value, StringRef Name)
Create a hidden global flag Name in the module with initial value Value.
void emitOffloadingEntry (Constant *Addr, StringRef Name, uint64_t Size, int32_t Flags, StringRef SectionName="omp_offloading_entries")
Create an offloading section struct used to register this global at runtime.
void emitCancelationCheckImpl (Value *CancelFlag, omp::Directive CanceledDirective, FinalizeCallbackTy ExitCB={})
Generate control flow and cleanup for cancellation.
InsertPointTy emitTargetKernel (const LocationDescription &Loc, Value *&Return, Value *Ident, Value *DeviceID, Value *NumTeams, Value *NumThreads, Value *HostPtr, ArrayRef< Value * > KernelArgs)
Generate a target region entry call.
InsertPointTy emitBarrierImpl (const LocationDescription &Loc, omp::Directive DK, bool ForceSimpleCall, bool CheckCancelFlag)
Generate a barrier runtime call.
void emitFlush (const LocationDescription &Loc)
Generate a flush runtime call.
bool isLastFinalizationInfoCancellable (omp::Directive DK)
Return true if the last entry in the finalization stack is of kind DK and cancellable.
void emitTaskwaitImpl (const LocationDescription &Loc)
Generate a taskwait runtime call.
void emitTaskyieldImpl (const LocationDescription &Loc)
Generate a taskyield runtime call.
Value * getOrCreateThreadID (Value *Ident)
Return the current thread ID.
void addOutlineInfo (OutlineInfo &&OI)
Add a new region that will be outlined later.
GlobalVariable * createOffloadMaptypes (SmallVectorImpl< uint64_t > &Mappings, std::string VarName)
Create the global variable holding the offload mappings information.
GlobalVariable * createOffloadMapnames (SmallVectorImpl< llvm::Constant * > &Names, std::string VarName)
Create the global variable holding the offload names information.
void createMapperAllocas (const LocationDescription &Loc, InsertPointTy AllocaIP, unsigned NumOperands, struct MapperAllocas &MapperAllocas)
Create the allocas instruction used in call to mapper functions.
void emitMapperCall (const LocationDescription &Loc, Function *MapperFunc, Value *SrcLocInfo, Value *MaptypesArg, Value *MapnamesArg, struct MapperAllocas &MapperAllocas, int64_t DeviceID, unsigned NumOperands)
Create the call for the target mapper function.
void emitOffloadingArraysArgument (IRBuilderBase &Builder, OpenMPIRBuilder::TargetDataRTArgs &RTArgs, OpenMPIRBuilder::TargetDataInfo &Info, bool EmitDebug=false, bool ForEndCall=false)
Emit the arguments to be passed to the runtime library based on the arrays of base pointers, pointers, sizes, map types, and mappers.
void createOffloadEntry (Constant *ID, Constant *Addr, uint64_t Size, int32_t Flags, GlobalValue::LinkageTypes)
Creates offloading entry for the provided entry ID ID, address Addr, size Size, and flags Flags.
void createOffloadEntriesAndInfoMetadata (OffloadEntriesInfoManager &OffloadEntriesInfoManager, EmitMetadataErrorReportFunctionTy &ErrorReportFunction)
InsertPointTy createCopyPrivate (const LocationDescription &Loc, llvm::Value *BufSize, llvm::Value *CpyBuf, llvm::Value *CpyFn, llvm::Value *DidIt)
Generator for __kmpc_copyprivate.
InsertPointTy createSingle (const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, bool IsNowait, llvm::Value *DidIt)
Generator for '#omp single'.
InsertPointTy createMaster (const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB)
Generator for '#omp master'.
InsertPointTy createMasked (const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, Value *Filter)
Generator for '#omp masked'.
InsertPointTy createCritical (const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, StringRef CriticalName, Value *HintInst)
Generator for '#omp critical'.
InsertPointTy createOrderedDepend (const LocationDescription &Loc, InsertPointTy AllocaIP, unsigned NumLoops, ArrayRef< llvm::Value * > StoreValues, const Twine &Name, bool IsDependSource)
Generator for '#omp ordered depend (source | sink)'.
InsertPointTy createOrderedThreadsSimd (const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, bool IsThreads)
Generator for '#omp ordered [threads | simd]'.
InsertPointTy createSections (const LocationDescription &Loc, InsertPointTy AllocaIP, ArrayRef< StorableBodyGenCallbackTy > SectionCBs, PrivatizeCallbackTy PrivCB, FinalizeCallbackTy FiniCB, bool IsCancellable, bool IsNowait)
Generator for '#omp sections'.
InsertPointTy createSection (const LocationDescription &Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB)
Generator for '#omp section'.
InsertPointTy createCopyinClauseBlocks (InsertPointTy IP, Value *MasterAddr, Value *PrivateAddr, llvm::IntegerType *IntPtrTy, bool BranchtoEnd=true)
Generate conditional branch and relevant BasicBlocks through which private threads copy the 'copyin' variables from Master copy to threadprivate copies.
CallInst * createOMPAlloc (const LocationDescription &Loc, Value *Size, Value *Allocator, std::string Name="")
Create a runtime call for kmpc_Alloc.
CallInst * createOMPFree (const LocationDescription &Loc, Value *Addr, Value *Allocator, std::string Name="")
Create a runtime call for kmpc_free.
CallInst * createCachedThreadPrivate (const LocationDescription &Loc, llvm::Value *Pointer, llvm::ConstantInt *Size, const llvm::Twine &Name=Twine(""))
Create a runtime call for kmpc_threadprivate_cached.
CallInst * createOMPInteropInit (const LocationDescription &Loc, Value *InteropVar, omp::OMPInteropType InteropType, Value *Device, Value *NumDependences, Value *DependenceAddress, bool HaveNowaitClause)
Create a runtime call for __tgt_interop_init.
CallInst * createOMPInteropDestroy (const LocationDescription &Loc, Value *InteropVar, Value *Device, Value *NumDependences, Value *DependenceAddress, bool HaveNowaitClause)
Create a runtime call for __tgt_interop_destroy.
CallInst * createOMPInteropUse (const LocationDescription &Loc, Value *InteropVar, Value *Device, Value *NumDependences, Value *DependenceAddress, bool HaveNowaitClause)
Create a runtime call for __tgt_interop_use.
InsertPointTy createTargetInit (const LocationDescription &Loc, bool IsSPMD)
The omp target interface.
void createTargetDeinit (const LocationDescription &Loc, bool IsSPMD)
Create a runtime call for kmpc_target_deinit.
void emitTargetRegionFunction (OffloadEntriesInfoManager &InfoManager, TargetRegionEntryInfo &EntryInfo, FunctionGenCallback &GenerateFunctionCallback, int32_t NumTeams, int32_t NumThreads, bool IsOffloadEntry, Function *&OutlinedFn, Constant *&OutlinedFnID)
Create a unique name for the entry function using the source location information of the current target region.
Constant * registerTargetRegionFunction (OffloadEntriesInfoManager &InfoManager, TargetRegionEntryInfo &EntryInfo, Function *OutlinedFunction, StringRef EntryFnName, StringRef EntryFnIDName, int32_t NumTeams, int32_t NumThreads)
Registers the given function and sets up the attribtues of the function Returns the FunctionID.
InsertPointTy createAtomicRead (const LocationDescription &Loc, AtomicOpValue &X, AtomicOpValue &V, AtomicOrdering AO)
Emit atomic Read for : V = X — Only Scalar data types.
InsertPointTy createAtomicWrite (const LocationDescription &Loc, AtomicOpValue &X, Value *Expr, AtomicOrdering AO)
Emit atomic write for : X = Expr — Only Scalar data types.
InsertPointTy createAtomicUpdate (const LocationDescription &Loc, InsertPointTy AllocaIP, AtomicOpValue &X, Value *Expr, AtomicOrdering AO, AtomicRMWInst::BinOp RMWOp, AtomicUpdateCallbackTy &UpdateOp, bool IsXBinopExpr)
Emit atomic update for constructs: X = X BinOp Expr ,or X = Expr BinOp X For complex Operations: X = UpdateOp(X) => CmpExch X, old_X, UpdateOp(X) Only Scalar data types.
InsertPointTy createAtomicCapture (const LocationDescription &Loc, InsertPointTy AllocaIP, AtomicOpValue &X, AtomicOpValue &V, Value *Expr, AtomicOrdering AO, AtomicRMWInst::BinOp RMWOp, AtomicUpdateCallbackTy &UpdateOp, bool UpdateExpr, bool IsPostfixUpdate, bool IsXBinopExpr)
Emit atomic update for constructs: — Only Scalar data types V = X; X = X BinOp Expr , X = X BinOp Expr; V = X, V = X; X = Expr BinOp X, X = Expr BinOp X; V = X, V = X; X = UpdateOp(X), X = UpdateOp(X); V = X,.
InsertPointTy createAtomicCompare (const LocationDescription &Loc, AtomicOpValue &X, AtomicOpValue &V, AtomicOpValue &R, Value *E, Value *D, AtomicOrdering AO, omp::OMPAtomicCompareOp Op, bool IsXBinopExpr, bool IsPostfixUpdate, bool IsFailOnly)
Emit atomic compare for constructs: — Only scalar data types cond-expr-stmt: x = x ordop expr ? expr : x; x = expr ordop x ? expr : x; x = x == e ? d : x; x = e == x ? d : x; (this one is not in the spec) cond-update-stmt: if (x ordop expr) { x = expr; } if (expr ordop x) { x = expr; } if (x == e) { x = d; } if (e == x) { x = d; } (this one is not in the spec) conditional-update-capture-atomic: v = x; cond-update-stmt; (IsPostfixUpdate=true, IsFailOnly=false) cond-update-stmt; v = x; (IsPostfixUpdate=false, IsFailOnly=false) if (x == e) { x = d; } else { v = x; } (IsPostfixUpdate=false, IsFailOnly=true) r = x == e; if (r) { x = d; } (IsPostfixUpdate=false, IsFailOnly=false) r = x == e; if (r) { x = d; } else { v = x; } (IsPostfixUpdate=false, IsFailOnly=true)
CanonicalLoopInfo * createLoopSkeleton (DebugLoc DL, Value *TripCount, Function *F, BasicBlock *PreInsertBefore, BasicBlock *PostInsertBefore, const Twine &Name={})
Create the control flow structure of a canonical OpenMP loop.
void loadOffloadInfoMetadata (Module &M, OffloadEntriesInfoManager &OffloadEntriesInfoManager)
Loads all the offload entries information from the host IR metadata.
GlobalVariable * getOrCreateInternalVariable (Type *Ty, const StringRef &Name, unsigned AddressSpace=0)
Gets (if variable with the given name already exist) or creates internal global variable with the specified Name.
Static Public Member Functions
static unsigned getOpenMPDefaultSimdAlign (const Triple &TargetTriple, const StringMap< bool > &Features)
Get the default alignment value for given target.
Public Attributes
SmallVector< FinalizationInfo, 8 > FinalizationStack
The finalization stack made up of finalize callbacks currently in-flight, wrapped into FinalizationInfo objects that reference also the finalization target block and the kind of cancellable directive.
OpenMPIRBuilderConfig Config
The OpenMPIRBuilder Configuration.
Module & M
The underlying LLVM-IR module.
IRBuilder Builder
The LLVM-IR Builder used to create IR.
StringMap< Constant * > SrcLocStrMap
Map to remember source location strings.
DenseMap< std::pair< Constant *, uint64_t >, Constant * > IdentMap
Map to remember existing ident_t*.
SmallVector< OutlineInfo, 16 > OutlineInfos
Collection of regions that need to be outlined during finalization.
std::forward_list< CanonicalLoopInfo > LoopInfos
Collection of owned canonical loop objects that eventually need to be free'd.
StringMap< Constant *, BumpPtrAllocator > InternalVars
An ordered map of auto-generated variables to their unique names.
const std::string ompOffloadInfoName = "omp_offload.info"
OMP Offload Info Metadata name string.
Detailed Description
An interface to create LLVM-IR for OpenMP directives.
Each OpenMP directive has a corresponding public generator method.
Definition at line 166 of file OMPIRBuilder.h.
Member Typedef Documentation
AtomicReductionGenTy
using llvm::OpenMPIRBuilder::AtomicReductionGenTy = function_ref<InsertPointTy(InsertPointTy, Type *, Value *, Value *)>
Functions used to generate atomic reductions.
Such functions take two Values representing pointers to LHS and RHS of the reduction, as well as the element type of these pointers. They are expected to atomically update the LHS to the reduced value.
Definition at line 808 of file OMPIRBuilder.h.
BodyGenCallbackTy
using llvm::OpenMPIRBuilder::BodyGenCallbackTy = function_ref<void(InsertPointTy AllocaIP, InsertPointTy CodeGenIP)>
Callback type for body (=inner region) code generation.
The callback takes code locations as arguments, each describing a location where additional instructions can be inserted.
The CodeGenIP may be in the middle of a basic block or point to the end of it. The basic block may have a terminator or be degenerate. The callback function may just insert instructions at that position, but also split the block (without the Before argument of BasicBlock::splitBasicBlock such that the identify of the split predecessor block is preserved) and insert additional control flow, including branches that do not lead back to what follows the CodeGenIP. Note that since the callback is allowed to split the block, callers must assume that InsertPoints to positions in the BasicBlock after CodeGenIP including CodeGenIP itself are invalidated. If such InsertPoints need to be preserved, it can split the block itself before calling the callback.
AllocaIP and CodeGenIP must not point to the same position.
Parameters
AllocaIP is the insertion point at which new alloca instructions should be placed. The BasicBlock it is pointing to must not be split.
CodeGenIP is the insertion point at which the body code should be placed.
Definition at line 261 of file OMPIRBuilder.h.
EmitMetadataErrorReportFunctionTy
using llvm::OpenMPIRBuilder::EmitMetadataErrorReportFunctionTy = std::function<void(EmitMetadataErrorKind, TargetRegionEntryInfo)>
Callback function type.
Definition at line 1219 of file OMPIRBuilder.h.
FinalizeCallbackTy
using llvm::OpenMPIRBuilder::FinalizeCallbackTy = std::function<void(InsertPointTy CodeGenIP)>
Callback type for variable finalization (think destructors).
Parameters
CodeGenIP is the insertion point at which the finalization code should be placed.
A finalize callback knows about all objects that need finalization, e.g. destruction, when the scope of the currently generated construct is left at the time, and location, the callback is invoked.
Definition at line 209 of file OMPIRBuilder.h.
FunctionGenCallback
using llvm::OpenMPIRBuilder::FunctionGenCallback = std::function<Function *(StringRef FunctionName)>
Functions used to generate a function with the given name.
Definition at line 1494 of file OMPIRBuilder.h.
InsertPointTy
using llvm::OpenMPIRBuilder::InsertPointTy = IRBuilder<>::InsertPoint
Type used throughout for insertion points.
Definition at line 189 of file OMPIRBuilder.h.
LoopBodyGenCallbackTy
using llvm::OpenMPIRBuilder::LoopBodyGenCallbackTy = function_ref<void(InsertPointTy CodeGenIP, Value *IndVar)>
Callback type for loop body code generation.
Parameters
CodeGenIP is the insertion point where the loop's body code must be placed. This will be a dedicated BasicBlock with a conditional branch from the loop condition check and terminated with an unconditional branch to the loop latch.
IndVar is the induction variable usable at the insertion point.
Definition at line 279 of file OMPIRBuilder.h.
PrivatizeCallbackTy
using llvm::OpenMPIRBuilder::PrivatizeCallbackTy = function_ref<InsertPointTy(InsertPointTy AllocaIP, InsertPointTy CodeGenIP, Value &Original, Value &Inner, Value *&ReplVal)>
Callback type for variable privatization (think copy & default constructor).
Parameters
AllocaIP is the insertion point at which new alloca instructions should be placed.
CodeGenIP is the insertion point at which the privatization code should be placed.
Original The value being copied/created, should not be used in the generated IR.
Inner The equivalent of Original that should be used in the generated IR; this is equal to Original if the value is a pointer and can thus be passed directly, otherwise it is an equivalent but different value.
ReplVal The replacement value, thus a copy or new created version of Inner.
Returns
The new insertion point where code generation continues and ReplVal the replacement value.
Definition at line 301 of file OMPIRBuilder.h.
ReductionGenTy
using llvm::OpenMPIRBuilder::ReductionGenTy = function_ref<InsertPointTy(InsertPointTy, Value *, Value *, Value *&)>
Functions used to generate reductions.
Such functions take two Values representing LHS and RHS of the reduction, respectively, and a reference to the value that is updated to refer to the reduction result.
Definition at line 801 of file OMPIRBuilder.h.
StorableBodyGenCallbackTy
using llvm::OpenMPIRBuilder::StorableBodyGenCallbackTy = std::function<void(InsertPointTy AllocaIP, InsertPointTy CodeGenIP)>
Definition at line 268 of file OMPIRBuilder.h.
Member Enumeration Documentation
EmitMetadataErrorKind
enum llvm::OpenMPIRBuilder::EmitMetadataErrorKind
The kind of errors that can occur when emitting the offload entries and metadata.
Enumerator
EMIT_MD_TARGET_REGION_ERROR
EMIT_MD_DECLARE_TARGET_ERROR
EMIT_MD_GLOBAL_VAR_LINK_ERROR
Definition at line 1211 of file OMPIRBuilder.h.
Constructor & Destructor Documentation
OpenMPIRBuilder()
llvm::OpenMPIRBuilder::OpenMPIRBuilder (Module & M) inline
Create a new OpenMPIRBuilder operating on the given module M.
This will not have an effect on M (see initialize)
Definition at line 170 of file OMPIRBuilder.h.
~OpenMPIRBuilder()
OpenMPIRBuilder::~OpenMPIRBuilder ()
Definition at line 539 of file OMPIRBuilder.cpp.
References assert().
Member Function Documentation
addAttributes()
void OpenMPIRBuilder::addAttributes (omp::RuntimeFunction FnID, Function & Fn)
Add attributes known for FnID to Fn.
Definition at line 331 of file OMPIRBuilder.cpp.
References llvm::AttributeSet::addAttribute(), llvm::AttributeSet::addAttributes(), llvm::Function::arg_size(), assert(), Attrs, llvm::SmallVectorImpl< T >::emplace_back(), llvm::Function::getAttributes(), llvm::Function::getContext(), and M.
addOutlineInfo()
void llvm::OpenMPIRBuilder::addOutlineInfo (OutlineInfo && OI) inline
Add a new region that will be outlined later.
Definition at line 1089 of file OMPIRBuilder.h.
References OutlineInfos.
applySimd()
void OpenMPIRBuilder::applySimd (CanonicalLoopInfo * Loop, MapVector< Value *, Value * > AlignedVars, Value * IfCond, omp::OrderKind Order, ConstantInt * Simdlen, ConstantInt * Safelen)
Add metadata to simd-ize a loop.
If IfCond is not nullptr, the loop is cloned. The metadata which prevents vectorization is added to to the cloned loop. The cloned loop is executed when ifCond is evaluated to false.
Parameters
Loop The loop to simd-ize.
AlignedVars The map which containts pairs of the pointer and its corresponding alignment.
IfCond The value which corresponds to the if clause condition.
Order The enum to map order clause.
Simdlen The Simdlen length to apply to the simd loop.
Safelen The Safelen length to apply to the simd loop.
Definition at line 3073 of file OMPIRBuilder.cpp.
References addBasicBlockMetadata(), addLoopMetadata(), addSimdMetadata(), assert(), BB, Builder, F, FAM, llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDNode::get(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::CanonicalLoopInfo::getCond(), llvm::MDNode::getDistinct(), llvm::ConstantInt::getFalse(), llvm::CanonicalLoopInfo::getFunction(), llvm::CanonicalLoopInfo::getHeader(), llvm::Type::getInt1Ty(), llvm::CanonicalLoopInfo::getLatch(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::CanonicalLoopInfo::getPreheader(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getTrue(), llvm::SmallSet< T, N, C >::insert(), llvm::ValueMap< KeyT, ValueT, Config >::lookup(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::registerPass(), llvm::LoopAnalysis::run(), and llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size().
applyWorkshareLoop()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::applyWorkshareLoop (DebugLoc DL, CanonicalLoopInfo * CLI, InsertPointTy AllocaIP, bool NeedsBarrier, llvm::omp::ScheduleKind SchedKind = llvm::omp::OMP_SCHEDULE_Default, llvm::Value * ChunkSize = nullptr, bool HasSimdModifier = false, bool HasMonotonicModifier = false, bool HasNonmonotonicModifier = false, bool HasOrderedClause = false)
Modifies the canonical loop to be a workshare loop.
This takes a LoopInfo representing a canonical loop, such as the one created by createCanonicalLoop and emits additional instructions to turn it into a workshare loop. In particular, it calls to an OpenMP runtime function in the preheader to obtain the loop bounds to be used in the current thread, updates the relevant instructions in the canonical loop and calls to an OpenMP runtime finalization function after the loop.
The concrete transformation is done by applyStaticWorkshareLoop, applyStaticChunkedWorkshareLoop, or applyDynamicWorkshareLoop, depending on the value of SchedKind and ChunkSize.
Parameters
DL Debug location for instructions added for the workshare-loop construct itself.
CLI A descriptor of the canonical loop to workshare.
AllocaIP An insertion point for Alloca instructions usable in the preheader of the loop.
NeedsBarrier Indicates whether a barrier must be insterted after the loop.
SchedKind Scheduling algorithm to use.
ChunkSize The chunk size for the inner loop.
HasSimdModifier Whether the simd modifier is present in the schedule clause.
HasMonotonicModifier Whether the monotonic modifier is present in the schedule clause.
HasNonmonotonicModifier Whether the nonmonotonic modifier is present in the schedule clause.
HasOrderedClause Whether the (parameterless) ordered clause is present.
Returns
Point where to insert code after the workshare construct.
Definition at line 2347 of file OMPIRBuilder.cpp.
References assert(), llvm::omp::BaseAuto, llvm::omp::BaseBalanced, llvm::omp::BaseDynamicChunked, llvm::omp::BaseGreedy, llvm::omp::BaseGuidedAnalyticalChunked, llvm::omp::BaseGuidedChunked, llvm::omp::BaseGuidedIterativeChunked, llvm::omp::BaseGuidedSimd, llvm::omp::BaseRuntime, llvm::omp::BaseRuntimeSimd, llvm::omp::BaseStatic, llvm::omp::BaseStaticBalancedChunked, llvm::omp::BaseStaticChunked, llvm::omp::BaseSteal, computeOpenMPScheduleType(), DL, LLVM_FALLTHROUGH, llvm_unreachable, llvm::omp::ModifierMask, and llvm::omp::ModifierOrdered.
collapseLoops()
CanonicalLoopInfo * OpenMPIRBuilder::collapseLoops (DebugLoc DL, ArrayRef< CanonicalLoopInfo * > Loops, InsertPointTy ComputeIP)
Collapse a loop nest into a single loop.
Merges loops of a loop nest into a single CanonicalLoopNest representation that has the same number of innermost loop iterations as the origin loop nest. The induction variables of the input loops are derived from the collapsed loop's induction variable. This is intended to be used to implement OpenMP's collapse clause. Before applying a directive, collapseLoops normalizes a loop nest to contain only a single loop and the directive's implementation does not need to handle multiple loops itself. This does not remove the need to handle all loop nest handling by directives, such as the ordered(<n>) clause or the simd schedule-clause modifier of the worksharing-loop directive.
Example:
for (int i = 0; i < 7; ++i) // Canonical loop "i"
  for (int j = 0; j < 9; ++j) // Canonical loop "j"
    body(i, j);
After collapsing with Loops={i,j}, the loop is changed to
for (int ij = 0; ij < 63; ++ij) {
  int i = ij / 9;
  int j = ij % 9;
  body(i, j);
}
In the current implementation, the following limitations apply:
All input loops have an induction variable of the same type.
The collapsed loop will have the same trip count integer type as the input loops. Therefore it is possible that the collapsed loop cannot represent all iterations of the input loops. For instance, assuming a 32 bit integer type, and two input loops both iterating 2^16 times, the theoretical trip count of the collapsed loop would be 2^32 iteration, which cannot be represented in an 32-bit integer. Behavior is undefined in this case.
The trip counts of every input loop must be available at ComputeIP. Non-rectangular loops are not yet supported.
At each nest level, code between a surrounding loop and its nested loop is hoisted into the loop body, and such code will be executed more often than before collapsing (or not at all if any inner loop iteration has a trip count of 0). This is permitted by the OpenMP specification.
Parameters
DL Debug location for instructions added for collapsing, such as instructions to compute/derive the input loop's induction variables.
Loops Loops in the loop nest to collapse. Loops are specified from outermost-to-innermost and every control flow of a loop's body must pass through its directly nested loop.
ComputeIP Where additional instruction that compute the collapsed trip count. If not set, defaults to before the generated loop.
Returns
The CanonicalLoopInfo object representing the collapsed loop.
Definition at line 2613 of file OMPIRBuilder.cpp.
References assert(), Builder, DL, F, llvm::CanonicalLoopInfo::getAfter(), llvm::CanonicalLoopInfo::getBody(), llvm::CanonicalLoopInfo::getLatch(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::BasicBlock::getParent(), llvm::CanonicalLoopInfo::getPreheader(), llvm::CanonicalLoopInfo::getPreheaderIP(), i, Loops, redirectAllPredecessorsTo(), redirectTo(), removeUnusedBlocksFromParent(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SmallVectorImpl< T >::resize().
createAtomicCapture()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createAtomicCapture (const LocationDescription & Loc, InsertPointTy AllocaIP, AtomicOpValue & X, AtomicOpValue & V, Value * Expr, AtomicOrdering AO, AtomicRMWInst::BinOp RMWOp, AtomicUpdateCallbackTy & UpdateOp, bool UpdateExpr, bool IsPostfixUpdate, bool IsXBinopExpr)
Emit atomic update for constructs: — Only Scalar data types V = X; X = X BinOp Expr , X = X BinOp Expr; V = X, V = X; X = Expr BinOp X, X = Expr BinOp X; V = X, V = X; X = UpdateOp(X), X = UpdateOp(X); V = X,.
Parameters
Loc The insert and source location description.
AllocaIP The insertion point to be used for alloca instructions.
X The target atomic pointer to be updated
V Memory address where to store captured value
Expr The value to update X with.
AO Atomic ordering of the generated atomic instructions
RMWOp The binary operation used for update. If operation is not supported by atomicRMW, or belong to {FADD, FSUB, BAD_BINOP}. Then a cmpExch based atomic will be generated.
UpdateOp Code generator for complex expressions that cannot be expressed through atomicrmw instruction.
UpdateExpr true if X is an in place update of the form X = X BinOp Expr or X = Expr BinOp X
IsXBinopExpr true if X is Left H.S. in Right H.S. part of the update expression, false otherwise. (e.g. true for X = X BinOp Expr)
IsPostfixUpdate true if original value of 'x' must be stored in 'v', not an updated one.
Returns
Insertion point after generated atomic capture IR.
Definition at line 4515 of file OMPIRBuilder.cpp.
References assert(), Builder, llvm::OpenMPIRBuilder::LocationDescription::IP, llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::OpenMPIRBuilder::AtomicOpValue::IsVolatile, LLVM_DEBUG, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::OpenMPIRBuilder::AtomicOpValue::Var, X, and llvm::AtomicRMWInst::Xchg.
createAtomicCompare()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createAtomicCompare (const LocationDescription & Loc, AtomicOpValue & X, AtomicOpValue & V, AtomicOpValue & R, Value * E, Value * D, AtomicOrdering AO, omp::OMPAtomicCompareOp Op, bool IsXBinopExpr, bool IsPostfixUpdate, bool IsFailOnly)
Emit atomic compare for constructs: — Only scalar data types cond-expr-stmt: x = x ordop expr ? expr : x; x = expr ordop x ? expr : x; x = x == e ? d : x; x = e == x ? d : x; (this one is not in the spec) cond-update-stmt: if (x ordop expr) { x = expr; } if (expr ordop x) { x = expr; } if (x == e) { x = d; } if (e == x) { x = d; } (this one is not in the spec) conditional-update-capture-atomic: v = x; cond-update-stmt; (IsPostfixUpdate=true, IsFailOnly=false) cond-update-stmt; v = x; (IsPostfixUpdate=false, IsFailOnly=false) if (x == e) { x = d; } else { v = x; } (IsPostfixUpdate=false, IsFailOnly=true) r = x == e; if (r) { x = d; } (IsPostfixUpdate=false, IsFailOnly=false) r = x == e; if (r) { x = d; } else { v = x; } (IsPostfixUpdate=false, IsFailOnly=true)
Parameters
Loc The insert and source location description.
X The target atomic pointer to be updated.
V Memory address where to store captured value (for compare capture only).
R Memory address where to store comparison result (for compare capture with '==' only).
E The expected value ('e') for forms that use an equality comparison or an expression ('expr') for forms that use 'ordop' (logically an atomic maximum or minimum).
D The desired value for forms that use an equality comparison. If forms that use 'ordop', it should be nullptr.
AO Atomic ordering of the generated atomic instructions.
Op Atomic compare operation. It can only be ==, <, or >.
IsXBinopExpr True if the conditional statement is in the form where x is on LHS. It only matters for < or >.
IsPostfixUpdate True if original value of 'x' must be stored in 'v', not an updated one (for compare capture only).
IsFailOnly True if the original value of 'x' is stored to 'v' only when the comparison fails. This is only valid for the case the comparison is '=='.
Returns
Insertion point after generated atomic capture IR.
Definition at line 4549 of file OMPIRBuilder.cpp.
References assert(), Builder, Compare, D, E, llvm::OpenMPIRBuilder::AtomicOpValue::ElemTy, llvm::omp::EQ, llvm::Instruction::eraseFromParent(), llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLT, llvm::AtomicRMWInst::FMax, llvm::AtomicRMWInst::FMin, llvm::IntegerType::get(), llvm::Type::getPointerTo(), llvm::AtomicCmpXchgInst::getStrongestFailureOrdering(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::OpenMPIRBuilder::LocationDescription::IP, llvm::Type::isPointerTy(), llvm::OpenMPIRBuilder::AtomicOpValue::IsVolatile, llvm_unreachable, M, llvm::omp::MAX, llvm::AtomicRMWInst::Max, llvm::omp::MIN, llvm::AtomicRMWInst::Min, llvm::BasicBlock::splitBasicBlock(), llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::OpenMPIRBuilder::AtomicOpValue::Var, and X.
createAtomicRead()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createAtomicRead (const LocationDescription & Loc, AtomicOpValue & X, AtomicOpValue & V, AtomicOrdering AO)
Emit atomic Read for : V = X — Only Scalar data types.
Parameters
Loc The insert and source location description.
X The target pointer to be atomically read
V Memory address where to store atomically read value
AO Atomic ordering of the generated atomic instructions.
Returns
Insertion point after generated atomic read IR.
Definition at line 4266 of file OMPIRBuilder.cpp.
References assert(), Builder, llvm::IntegerType::get(), llvm::Type::getPointerTo(), llvm::Type::getScalarSizeInBits(), llvm::OpenMPIRBuilder::LocationDescription::IP, llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::OpenMPIRBuilder::AtomicOpValue::IsVolatile, M, llvm::LoadInst::setAtomic(), llvm::OpenMPIRBuilder::AtomicOpValue::Var, and X.
createAtomicUpdate()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createAtomicUpdate (const LocationDescription & Loc, InsertPointTy AllocaIP, AtomicOpValue & X, Value * Expr, AtomicOrdering AO, AtomicRMWInst::BinOp RMWOp, AtomicUpdateCallbackTy & UpdateOp, bool IsXBinopExpr)
Emit atomic update for constructs: X = X BinOp Expr ,or X = Expr BinOp X For complex Operations: X = UpdateOp(X) => CmpExch X, old_X, UpdateOp(X) Only Scalar data types.
Parameters
Loc The insert and source location description.
AllocaIP The insertion point to be used for alloca instructions.
X The target atomic pointer to be updated
Expr The value to update X with.
AO Atomic ordering of the generated atomic instructions.
RMWOp The binary operation used for update. If operation is not supported by atomicRMW, or belong to {FADD, FSUB, BAD_BINOP}. Then a cmpExch based atomic will be generated.
UpdateOp Code generator for complex expressions that cannot be expressed through atomicrmw instruction.
IsXBinopExpr true if X is Left H.S. in Right H.S. part of the update expression, false otherwise. (e.g. true for X = X BinOp Expr)
Returns
Insertion point after generated atomic update IR.
Definition at line 4341 of file OMPIRBuilder.cpp.
References assert(), Builder, llvm::OpenMPIRBuilder::LocationDescription::IP, isConflictIP(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), LLVM_DEBUG, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, and X.
createAtomicWrite()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createAtomicWrite (const LocationDescription & Loc, AtomicOpValue & X, Value * Expr, AtomicOrdering AO)
Emit atomic write for : X = Expr — Only Scalar data types.
Parameters
Loc The insert and source location description.
X The target pointer to be atomically written to
Expr The value to store.
AO Atomic ordering of the generated atomic instructions.
Returns
Insertion point after generated atomic Write IR.
Definition at line 4308 of file OMPIRBuilder.cpp.
References assert(), Builder, llvm::IntegerType::get(), llvm::Type::getPointerTo(), llvm::Type::getScalarSizeInBits(), llvm::OpenMPIRBuilder::LocationDescription::IP, llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), M, llvm::StoreInst::setAtomic(), and X.
createBarrier()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createBarrier (const LocationDescription & Loc, omp::Directive DK, bool ForceSimpleCall = false, bool CheckCancelFlag = true)
Emitter methods for OpenMP directives.
{ Generator for '#omp barrier'
Parameters
Loc The location where the barrier directive was encountered.
DK The kind of directive that caused the barrier.
ForceSimpleCall Flag to force a simple (=non-cancellation) barrier.
CheckCancelFlag Flag to indicate a cancel barrier return value should be checked and acted upon.
Returns
The insertion point after the barrier.
Definition at line 669 of file OMPIRBuilder.cpp.
References llvm::OpenMPIRBuilder::LocationDescription::IP.
createCachedThreadPrivate()
CallInst * OpenMPIRBuilder::createCachedThreadPrivate (const LocationDescription & Loc, llvm::Value * Pointer, llvm::ConstantInt * Size, const llvm::Twine & Name = Twine(""))
Create a runtime call for kmpc_threadprivate_cached.
Parameters
Loc The insert and source location description.
Pointer pointer to data to be cached
Size size of data to be cached
Name Name of call Instruction for callinst
Returns
CallInst to the thread private cache call.
Definition at line 3867 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, and llvm::OpenMPIRBuilder::LocationDescription::IP.
createCancel()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createCancel (const LocationDescription & Loc, Value * IfCondition, omp::Directive CanceledDirective)
Generator for '#omp cancel'.
Parameters
Loc The location where the directive was encountered.
IfCondition The evaluated 'if' clause expression, if any.
CanceledDirective The kind of directive that is cancled.
Returns
The insertion point after the barrier.
Definition at line 726 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, llvm::OpenMPIRBuilder::LocationDescription::DL, llvm::OpenMPIRBuilder::LocationDescription::IP, llvm_unreachable, and llvm::SplitBlockAndInsertIfThenElse().
createCanonicalLoop() [1/2]
CanonicalLoopInfo * OpenMPIRBuilder::createCanonicalLoop (const LocationDescription & Loc, LoopBodyGenCallbackTy BodyGenCB, Value * Start, Value * Stop, Value * Step, bool IsSigned, bool InclusiveStop, InsertPointTy ComputeIP = {}, const Twine & Name = "loop")
Generator for the control flow structure of an OpenMP canonical loop.
Instead of a logical iteration space, this allows specifying user-defined loop counter values using increment, upper- and lower bounds. To disambiguate the terminology when counting downwards, instead of lower bounds we use Start for the loop counter value in the first body iteration.
Consider the following limitations:
A loop counter space over all integer values of its bit-width cannot be represented. E.g using uint8_t, its loop trip count of 256 cannot be stored into an 8 bit integer):
DO I = 0, 255, 1
Unsigned wrapping is only supported when wrapping only "once"; E.g. effectively counting downwards:
for (uint8_t i = 100u; i > 0; i += 127u)
TODO: May need to add additional parameters to represent:
Allow representing downcounting with unsigned integers.
Sign of the step and the comparison operator might disagree:
for (int i = 0; i < 42; i -= 1u)
Parameters
Loc The insert and source location description.
BodyGenCB Callback that will generate the loop body code.
Start Value of the loop counter for the first iterations.
Stop Loop counter values past this will stop the loop.
Step Loop counter increment after each iteration; negative means counting down.
IsSigned Whether Start, Stop and Step are signed integers.
InclusiveStop Whether Stop itself is a valid value for the loop counter.
ComputeIP Insertion point for instructions computing the trip count. Can be used to ensure the trip count is available at the outermost loop of a loop nest. If not set, defaults to the preheader of the generated loop.
Name Base name used to derive BB and instruction names.
Returns
An object representing the created control flow structure which can be used for loop-associated directives.
A Step of INT_MIN cannot not be normalized to a positive direction:
Definition at line 2029 of file OMPIRBuilder.cpp.
createCanonicalLoop() [2/2]
CanonicalLoopInfo * OpenMPIRBuilder::createCanonicalLoop (const LocationDescription & Loc, LoopBodyGenCallbackTy BodyGenCB, Value * TripCount, const Twine & Name = "loop")
Generator for the control flow structure of an OpenMP canonical loop.
This generator operates on the logical iteration space of the loop, i.e. the caller only has to provide a loop trip count of the loop as defined by base language semantics. The trip count is interpreted as an unsigned integer. The induction variable passed to BodyGenCB will be of the same type and run from 0 to TripCount - 1. It is up to the callback to convert the logical iteration variable to the loop counter variable in the loop body.
Parameters
Loc The insert and source location description. The insert location can be between two instructions or the end of a degenerate block (e.g. a BB under construction).
BodyGenCB Callback that will generate the loop body code.
TripCount Number of iterations the loop body is executed.
Name Base name used to derive BB and instruction names.
Returns
An object representing the created control flow structure which can be used for loop-associated directives.
Definition at line 2000 of file OMPIRBuilder.cpp.
References llvm::CanonicalLoopInfo::assertOK(), BB, Builder, llvm::OpenMPIRBuilder::LocationDescription::DL, llvm::CanonicalLoopInfo::getAfter(), llvm::CanonicalLoopInfo::getBodyIP(), llvm::CanonicalLoopInfo::getIndVar(), llvm::CanonicalLoopInfo::getPreheader(), llvm::OpenMPIRBuilder::LocationDescription::IP, and llvm::spliceBB().
createCopyinClauseBlocks()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createCopyinClauseBlocks (InsertPointTy IP, Value * MasterAddr, Value * PrivateAddr, llvm::IntegerType * IntPtrTy, bool BranchtoEnd = true)
Generate conditional branch and relevant BasicBlocks through which private threads copy the 'copyin' variables from Master copy to threadprivate copies.
Parameters
IP insertion block for copyin conditional
MasterVarPtr a pointer to the master variable
PrivateVarPtr a pointer to the threadprivate variable
IntPtrTy Pointer size type
BranchtoEnd Create a branch between the copyin.not.master blocks
Returns
The insertion point where copying operation to be emitted.
Definition at line 3701 of file OMPIRBuilder.cpp.
References Builder, cmp, llvm::BasicBlock::Create(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), M, and llvm::BasicBlock::splitBasicBlock().
createCopyPrivate()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createCopyPrivate (const LocationDescription & Loc, llvm::Value * BufSize, llvm::Value * CpyBuf, llvm::Value * CpyFn, llvm::Value * DidIt)
Generator for __kmpc_copyprivate.
Parameters
Loc The source location description.
BufSize Number of elements in the buffer.
CpyBuf List of pointers to data to be copied.
CpyFn function to call for copying data.
DidIt flag variable; 1 for 'single' thread, 0 otherwise.
Returns
The insertion position after the CopyPrivate call.
Definition at line 3415 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, and llvm::OpenMPIRBuilder::LocationDescription::IP.
createCritical()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createCritical (const LocationDescription & Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, StringRef CriticalName, Value * HintInst)
Generator for '#omp critical'.
Parameters
Loc The insert and source location description.
BodyGenCB Callback that will generate the region body code.
FiniCB Callback to finalize variable copies.
CriticalName name of the lock used by the critical directive
HintInst Hint Instruction for hint clause associated with critical
Returns
The insertion position after the critical.
Definition at line 3478 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::sys::path::begin(), Builder, llvm::sys::path::end(), and llvm::OpenMPIRBuilder::LocationDescription::IP.
createFlush()
void OpenMPIRBuilder::createFlush (const LocationDescription & Loc)
Generator for '#omp flush'.
Parameters
Loc The location where the flush directive was encountered
Definition at line 1239 of file OMPIRBuilder.cpp.
createGlobalFlag()
GlobalValue * OpenMPIRBuilder::createGlobalFlag (unsigned Value, StringRef Name)
Create a hidden global flag Name in the module with initial value Value.
Definition at line 543 of file OMPIRBuilder.cpp.
References llvm::ConstantInt::get(), llvm::Type::getInt32Ty(), llvm::GlobalValue::HiddenVisibility, M, and llvm::GlobalValue::WeakODRLinkage.
createLoopSkeleton()
CanonicalLoopInfo * OpenMPIRBuilder::createLoopSkeleton (DebugLoc DL, Value * TripCount, Function * F, BasicBlock * PreInsertBefore, BasicBlock * PostInsertBefore, const Twine & Name = {})
Create the control flow structure of a canonical OpenMP loop.
The emitted loop will be disconnected, i.e. no edge to the loop's preheader and no terminator in the AfterBB. The OpenMPIRBuilder's IRBuilder location is not preserved.
Parameters
DL DebugLoc used for the instructions in the skeleton.
TripCount Value to be used for the trip count.
F Function in which to insert the BasicBlocks.
PreInsertBefore Where to insert BBs that execute before the body, typically the body itself.
PostInsertBefore Where to insert BBs that execute after the body.
Name Base name used to derive BB and instruction names.
Returns
The CanonicalLoopInfo that represents the emitted loop.
Definition at line 1933 of file OMPIRBuilder.cpp.
References llvm::PHINode::addIncoming(), llvm::CanonicalLoopInfo::assertOK(), Builder, Cond, llvm::BasicBlock::Create(), DL, F, llvm::ConstantInt::get(), llvm::Value::getType(), and M.
createMapperAllocas()
void OpenMPIRBuilder::createMapperAllocas (const LocationDescription & Loc, InsertPointTy AllocaIP, unsigned NumOperands, struct MapperAllocas & MapperAllocas)
Create the allocas instruction used in call to mapper functions.
Definition at line 4101 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::OpenMPIRBuilder::MapperAllocas::Args, llvm::OpenMPIRBuilder::MapperAllocas::ArgsBase, llvm::OpenMPIRBuilder::MapperAllocas::ArgSizes, Builder, llvm::ArrayType::get(), and llvm::OpenMPIRBuilder::LocationDescription::IP.
createMasked()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createMasked (const LocationDescription & Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, Value * Filter)
Generator for '#omp masked'.
Parameters
Loc The insert and source location description.
BodyGenCB Callback that will generate the region code.
FiniCB Callback to finialize variable copies.
Returns
The insertion position after the masked.
Definition at line 1909 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, llvm::Filter, and llvm::OpenMPIRBuilder::LocationDescription::IP.
createMaster()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createMaster (const LocationDescription & Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB)
Generator for '#omp master'.
Parameters
Loc The insert and source location description.
BodyGenCB Callback that will generate the region code.
FiniCB Callback to finalize variable copies.
Returns
The insertion position after the master.
Definition at line 1884 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, and llvm::OpenMPIRBuilder::LocationDescription::IP.
createOffloadEntriesAndInfoMetadata()
void OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata (OffloadEntriesInfoManager & OffloadEntriesInfoManager, EmitMetadataErrorReportFunctionTy & ErrorReportFunction)
Definition at line 4813 of file OMPIRBuilder.cpp.
References llvm::OffloadEntriesInfoManager::actOnDeviceGlobalVarEntriesInfo(), llvm::OffloadEntriesInfoManager::actOnTargetRegionEntriesInfo(), assert(), Builder, llvm::dyn_cast(), E, llvm::OffloadEntriesInfoManager::empty(), llvm::omp::Flags, llvm::ConstantInt::get(), llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDNode::get(), llvm_unreachable, M, llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryLink, llvm::OffloadEntriesInfoManager::OMPTargetGlobalVarEntryTo, llvm::TargetRegionEntryInfo::ParentName, llvm::OffloadEntriesInfoManager::size(), and llvm::GlobalValue::WeakAnyLinkage.
createOffloadEntry()
void OpenMPIRBuilder::createOffloadEntry (Constant * ID, Constant * Addr, uint64_t Size, int32_t Flags, GlobalValue::LinkageTypes)
Creates offloading entry for the provided entry ID ID, address Addr, size Size, and flags Flags.
Definition at line 4783 of file OMPIRBuilder.cpp.
References llvm::Function::addFnAttr(), llvm::NamedMDNode::addOperand(), Addr, llvm::omp::Flags, llvm::ConstantInt::get(), llvm::Attribute::get(), llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDNode::get(), llvm::Type::getInt32Ty(), llvm::GlobalValue::getParent(), and M.
createOffloadMapnames()
GlobalVariable * OpenMPIRBuilder::createOffloadMapnames (SmallVectorImpl< llvm::Constant * > & Names, std::string VarName)
Create the global variable holding the offload names information.
Definition at line 4732 of file OMPIRBuilder.cpp.
References llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::Type::getInt8Ty(), llvm::Type::getPointerTo(), llvm::Value::getType(), M, llvm::GlobalValue::PrivateLinkage, and llvm::tgtok::VarName.
createOffloadMaptypes()
GlobalVariable * OpenMPIRBuilder::createOffloadMaptypes (SmallVectorImpl< uint64_t > & Mappings, std::string VarName)
Create the global variable holding the offload mappings information.
Definition at line 4089 of file OMPIRBuilder.cpp.
References llvm::ConstantDataArray::get(), llvm::Value::getType(), llvm::GlobalValue::Global, M, Mappings, llvm::GlobalValue::PrivateLinkage, and llvm::tgtok::VarName.
createOMPAlloc()
CallInst * OpenMPIRBuilder::createOMPAlloc (const LocationDescription & Loc, Value * Size, Value * Allocator, std::string Name = "")
Create a runtime call for kmpc_Alloc.
Parameters
Loc The insert and source location description.
Size Size of allocated memory space
Allocator Allocator information instruction
Name Name of call Instruction for OMP_alloc
Returns
CallInst to the OMP_Alloc call
Definition at line 3751 of file OMPIRBuilder.cpp.
References Allocator, llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, and llvm::OpenMPIRBuilder::LocationDescription::IP.
createOMPFree()
CallInst * OpenMPIRBuilder::createOMPFree (const LocationDescription & Loc, Value * Addr, Value * Allocator, std::string Name = "")
Create a runtime call for kmpc_free.
Parameters
Loc The insert and source location description.
Addr Address of memory space to be freed
Allocator Allocator information instruction
Name Name of call Instruction for OMP_Free
Returns
CallInst to the OMP_Free call
Definition at line 3768 of file OMPIRBuilder.cpp.
References Addr, Allocator, llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, and llvm::OpenMPIRBuilder::LocationDescription::IP.
createOMPInteropDestroy()
CallInst * OpenMPIRBuilder::createOMPInteropDestroy (const LocationDescription & Loc, Value * InteropVar, Value * Device, Value * NumDependences, Value * DependenceAddress, bool HaveNowaitClause)
Create a runtime call for __tgt_interop_destroy.
Parameters
Loc The insert and source location description.
InteropVar variable to be allocated
Device devide to which offloading will occur
NumDependences number of dependence variables
DependenceAddress pointer to dependence variables
HaveNowaitClause does nowait clause exist
Returns
CallInst to the __tgt_interop_destroy call
Definition at line 3812 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, llvm::ConstantInt::get(), llvm::ConstantPointerNull::get(), llvm::Type::getInt8PtrTy(), llvm::OpenMPIRBuilder::LocationDescription::IP, and M.
createOMPInteropInit()
CallInst * OpenMPIRBuilder::createOMPInteropInit (const LocationDescription & Loc, Value * InteropVar, omp::OMPInteropType InteropType, Value * Device, Value * NumDependences, Value * DependenceAddress, bool HaveNowaitClause)
Create a runtime call for __tgt_interop_init.
Parameters
Loc The insert and source location description.
InteropVar variable to be allocated
InteropType type of interop operation
Device devide to which offloading will occur
NumDependences number of dependence variables
DependenceAddress pointer to dependence variables
HaveNowaitClause does nowait clause exist
Returns
CallInst to the __tgt_interop_init call
Definition at line 3783 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, llvm::ConstantInt::get(), llvm::ConstantPointerNull::get(), llvm::Type::getInt8PtrTy(), llvm::OpenMPIRBuilder::LocationDescription::IP, and M.
createOMPInteropUse()
CallInst * OpenMPIRBuilder::createOMPInteropUse (const LocationDescription & Loc, Value * InteropVar, Value * Device, Value * NumDependences, Value * DependenceAddress, bool HaveNowaitClause)
Create a runtime call for __tgt_interop_use.
Parameters
Loc The insert and source location description.
InteropVar variable to be allocated
Device devide to which offloading will occur
NumDependences number of dependence variables
DependenceAddress pointer to dependence variables
HaveNowaitClause does nowait clause exist
Returns
CallInst to the __tgt_interop_use call
Definition at line 3839 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, llvm::ConstantInt::get(), llvm::ConstantPointerNull::get(), llvm::Type::getInt8PtrTy(), llvm::OpenMPIRBuilder::LocationDescription::IP, and M.
createOrderedDepend()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createOrderedDepend (const LocationDescription & Loc, InsertPointTy AllocaIP, unsigned NumLoops, ArrayRef< llvm::Value * > StoreValues, const Twine & Name, bool IsDependSource)
Generator for '#omp ordered depend (source | sink)'.
Parameters
Loc The insert and source location description.
AllocaIP The insertion point to be used for alloca instructions.
NumLoops The number of loops in depend clause.
StoreValues The value will be stored in vector address.
Name The name of alloca instruction.
IsDependSource If true, depend source; otherwise, depend sink.
Returns
The insertion position after the ordered.
Definition at line 3513 of file OMPIRBuilder.cpp.
References Align, llvm::all_of(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), Builder, llvm::ArrayType::get(), llvm::Value::getType(), I, llvm::OpenMPIRBuilder::LocationDescription::IP, llvm::AllocaInst::setAlignment(), and llvm::StoreInst::setAlignment().
createOrderedThreadsSimd()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createOrderedThreadsSimd (const LocationDescription & Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, bool IsThreads)
Generator for '#omp ordered [threads | simd]'.
Parameters
Loc The insert and source location description.
BodyGenCB Callback that will generate the region code.
FiniCB Callback to finalize variable copies.
IsThreads If true, with threads clause or without clause; otherwise, with simd clause;
Returns
The insertion position after the ordered.
Definition at line 3559 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, and llvm::OpenMPIRBuilder::LocationDescription::IP.
createParallel()
IRBuilder::InsertPoint OpenMPIRBuilder::createParallel (const LocationDescription & Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB, PrivatizeCallbackTy PrivCB, FinalizeCallbackTy FiniCB, Value * IfCondition, Value * NumThreads, omp::ProcBindKind ProcBind, bool IsCancellable)
Generator for '#omp parallel'.
Parameters
Loc The insert and source location description.
AllocaIP The insertion points to be used for alloca instructions.
BodyGenCB Callback that will generate the region code.
PrivCB Callback to copy a given variable (think copy constructor).
FiniCB Callback to finalize variable copies.
IfCondition The evaluated 'if' clause expression, if any.
NumThreads The evaluated 'num_threads' clause expression, if any.
ProcBind The value of the 'proc_bind' clause (see ProcBindKind).
IsCancellable Flag to indicate a cancellable parallel region.
Returns
The insertion position after the parallel.
Definition at line 881 of file OMPIRBuilder.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::CallBase::arg_begin(), llvm::CallBase::arg_end(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), BB, llvm::sys::path::begin(), llvm::BasicBlock::begin(), Builder, llvm::OpenMPIRBuilder::OutlineInfo::collectBlocks(), Cond, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::MDBuilder::createCallbackEncoding(), llvm::dbgs(), llvm::SetVector< T, Vector, Set >::empty(), llvm::sys::path::end(), llvm::BasicBlock::end(), llvm::OpenMPIRBuilder::OutlineInfo::EntryBB, llvm::Instruction::eraseFromParent(), llvm::OpenMPIRBuilder::OutlineInfo::ExcludeArgsFromAggregate, llvm::OpenMPIRBuilder::OutlineInfo::ExitBB, F, llvm::CodeExtractor::findAllocas(), llvm::CodeExtractor::findInputsOutputs(), llvm::ConstantInt::get(), llvm::ConstantPointerNull::get(), llvm::MDNode::get(), llvm::CallBase::getCalledFunction(), llvm::FunctionCallee::getCallee(), llvm::BasicBlock::getFirstInsertionPt(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), I, llvm::OpenMPIRBuilder::LocationDescription::IP, isConflictIP(), LLVM_DEBUG, M, move, llvm::OpenMPIRBuilder::OutlineInfo::OuterAllocaBB, llvm::OpenMPIRBuilder::OutlineInfo::PostOutlineCB, Ptr, llvm::Value::setName(), llvm::BasicBlock::splitBasicBlock(), llvm::SplitBlock(), Uses, and Void.
createPlatformSpecificName()
std::string OpenMPIRBuilder::createPlatformSpecificName (ArrayRef< StringRef > Parts) const
Get the create a name using the platform specific separators.
Parameters
Parts parts of the final name that needs separation The created name has a first separator between the first and second part and a second separator between all other parts. E.g. with FirstSeparator "$" and Separator "." and parts: "p1", "p2", "p3", "p4" The resulting name is "p1$p2.p3.p4" The separators are retrieved from the OpenMPIRBuilderConfig.
Definition at line 4055 of file OMPIRBuilder.cpp.
createReductions()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createReductions (const LocationDescription & Loc, InsertPointTy AllocaIP, ArrayRef< ReductionInfo > ReductionInfos, bool IsNoWait = false)
Generator for '#omp reduction'.
Emits the IR instructing the runtime to perform the specific kind of reductions. Expects reduction variables to have been privatized and initialized to reduction-neutral values separately. Emits the calls to runtime functions as well as the reduction function and the basic blocks performing the reduction atomically and non-atomically.
The code emitted for the following:
type var_1;
type var_2;
#pragma omp <directive> reduction(reduction-op:var_1,var_2)
/* body */;
corresponds to the following sketch.
void _outlined_par() {
  // N is the number of different reductions.
  void *red_array[] = {privatized_var_1, privatized_var_2, ...};
  switch(__kmpc_reduce(..., N, /*size of data in red array*/, red_array,
                       _omp_reduction_func,
                       _gomp_critical_user.reduction.var)) {
  case 1: {
    var_1 = var_1 <reduction-op> privatized_var_1;
    var_2 = var_2 <reduction-op> privatized_var_2;
    // ...
   __kmpc_end_reduce(...);
    break;
  }
  case 2: {
    _Atomic<ReductionOp>(var_1, privatized_var_1);
    _Atomic<ReductionOp>(var_2, privatized_var_2);
    // ...
    break;
  }
  default: break;
  }
}
void _omp_reduction_func(void **lhs, void **rhs) {
  *(type *)lhs[0] = *(type *)lhs[0] <reduction-op> *(type *)rhs[0];
  *(type *)lhs[1] = *(type *)lhs[1] <reduction-op> *(type *)rhs[1];
  // ...
}
Parameters
Loc The location where the reduction was encountered. Must be within the associate directive and after the last local access to the reduction variables.
AllocaIP An insertion point suitable for allocas usable in reductions.
ReductionInfos A list of info on each reduction variable.
IsNoWait A flag set if the reduction is marked as nowait.
Definition at line 1720 of file OMPIRBuilder.cpp.
References llvm::all_of(), assert(), llvm::OpenMPIRBuilder::ReductionInfo::AtomicReductionGen, Builder, llvm::BasicBlock::Create(), DL, llvm::OpenMPIRBuilder::ReductionInfo::ElementType, llvm::BasicBlock::end(), llvm::enumerate(), llvm::Instruction::eraseFromParent(), llvm::ArrayType::get(), llvm::Function::getArg(), llvm::Module::getContext(), llvm::Module::getDataLayout(), getFreshReductionFunc(), llvm::Type::getPointerTo(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::OpenMPIRBuilder::LocationDescription::IP, LHS, llvm::OpenMPIRBuilder::ReductionInfo::PrivateVariable, llvm::OpenMPIRBuilder::ReductionInfo::ReductionGen, RHS, llvm::BasicBlock::splitBasicBlock(), and llvm::OpenMPIRBuilder::ReductionInfo::Variable.
createSection()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createSection (const LocationDescription & Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB)
Generator for '#omp section'.
Parameters
Loc The insert and source location description.
BodyGenCB Callback that will generate the region body code.
FiniCB Callback to finalize variable copies.
Returns
The insertion position after the section.
Definition at line 1674 of file OMPIRBuilder.cpp.
References Builder, I, and llvm::OpenMPIRBuilder::LocationDescription::IP.
createSections()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createSections (const LocationDescription & Loc, InsertPointTy AllocaIP, ArrayRef< StorableBodyGenCallbackTy > SectionCBs, PrivatizeCallbackTy PrivCB, FinalizeCallbackTy FiniCB, bool IsCancellable, bool IsNowait)
Generator for '#omp sections'.
Parameters
Loc The insert and source location description.
AllocaIP The insertion points to be used for alloca instructions.
SectionCBs Callbacks that will generate body of each section.
PrivCB Callback to copy a given variable (think copy constructor).
FiniCB Callback to finalize variable copies.
IsCancellable Flag to indicate a cancellable parallel region.
IsNowait If true, barrier - to ensure all sections are executed before moving forward will not be generated.
Returns
The insertion position after the sections.
Definition at line 1579 of file OMPIRBuilder.cpp.
References llvm::SwitchInst::addCase(), assert(), llvm::BasicBlock::begin(), Builder, llvm::BasicBlock::Create(), llvm::OpenMPIRBuilder::LocationDescription::DL, llvm::ConstantInt::get(), llvm::Type::getInt32Ty(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), I, llvm::OpenMPIRBuilder::LocationDescription::IP, isConflictIP(), M, llvm::ArrayRef< T >::size(), llvm::splitBBWithSuffix(), and llvm::ARM_MB::ST.
createSingle()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createSingle (const LocationDescription & Loc, BodyGenCallbackTy BodyGenCB, FinalizeCallbackTy FiniCB, bool IsNowait, llvm::Value * DidIt)
Generator for '#omp single'.
Parameters
Loc The source location description.
BodyGenCB Callback that will generate the region code.
FiniCB Callback to finalize variable copies.
IsNowait If false, a barrier is emitted.
DidIt Local variable used as a flag to indicate 'single' thread
Returns
The insertion position after the single call.
Definition at line 3436 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, llvm::OpenMPIRBuilder::LocationDescription::DL, and llvm::OpenMPIRBuilder::LocationDescription::IP.
createTargetDeinit()
void OpenMPIRBuilder::createTargetDeinit (const LocationDescription & Loc, bool IsSPMD)
Create a runtime call for kmpc_target_deinit.
Parameters
Loc The insert and source location description.
IsSPMD Flag to indicate if the kernel is an SPMD kernel or not.
Definition at line 3938 of file OMPIRBuilder.cpp.
References Builder, llvm::Type::getInt8Ty(), llvm::ConstantInt::getSigned(), llvm::pdb::Int8, llvm::omp::OMP_TGT_EXEC_MODE_GENERIC, and llvm::omp::OMP_TGT_EXEC_MODE_SPMD.
createTargetInit()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createTargetInit (const LocationDescription & Loc, bool IsSPMD)
The omp target interface.
For more information about the usage of this interface,
See also
openmp/libomptarget/deviceRTLs/common/include/target.h
{ Create a runtime call for kmpc_target_init
Parameters
Loc The insert and source location description.
IsSPMD Flag to indicate if the kernel is an SPMD kernel or not.
Definition at line 3888 of file OMPIRBuilder.cpp.
References Builder, llvm::BasicBlock::Create(), llvm::ConstantInt::get(), llvm::ConstantInt::getBool(), llvm::BasicBlock::getContext(), llvm::BasicBlock::getFirstInsertionPt(), llvm::Type::getInt8Ty(), llvm::BasicBlock::getParent(), llvm::ConstantInt::getSigned(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::pdb::Int8, llvm::OpenMPIRBuilder::LocationDescription::IP, llvm::omp::OMP_TGT_EXEC_MODE_GENERIC, llvm::omp::OMP_TGT_EXEC_MODE_SPMD, and llvm::BasicBlock::splitBasicBlock().
createTask()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createTask (const LocationDescription & Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB, bool Tied = true, Value * Final = nullptr, Value * IfCondition = nullptr, SmallVector< DependData > Dependencies = {})
Generator for #omp task
Parameters
Loc The location where the task construct was encountered.
AllocaIP The insertion point to be used for alloca instructions.
BodyGenCB Callback that will generate the region code.
Tied True if the task is tied, false if the task is untied.
Final i1 value which is true if the task is final, false if the task is not final.
IfCondition i1 value. If it evaluates to false, an undeferred task is generated, and the encountering thread must suspend the current task region, for which execution cannot be resumed until execution of the structured block that is associated with the generated task is completed.
Definition at line 1283 of file OMPIRBuilder.cpp.
References Addr, llvm::CallBase::arg_size(), assert(), llvm::sampleprof::Base, llvm::omp::BaseAddr, llvm::BasicBlock::begin(), Builder, llvm::BasicBlock::Create(), llvm::OpenMPIRBuilder::OutlineInfo::EntryBB, llvm::Instruction::eraseFromParent(), llvm::OpenMPIRBuilder::OutlineInfo::ExitBB, llvm::omp::Flags, llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::ArrayType::get(), llvm::ConstantPointerNull::get(), llvm::AllocaInst::getAllocatedType(), llvm::Function::getArg(), llvm::CallBase::getArgOperand(), llvm::ConstantExpr::getBitCast(), llvm::FunctionCallee::getCallee(), llvm::Type::getInt8PtrTy(), llvm::Value::getPointerAlignment(), llvm::Type::getPointerTo(), llvm::BasicBlock::getSinglePredecessor(), llvm::BasicBlock::getTerminator(), llvm::omp::Len, M, move, llvm::OpenMPIRBuilder::OutlineInfo::OuterAllocaBB, P, llvm::OpenMPIRBuilder::OutlineInfo::PostOutlineCB, llvm::splitBB(), and llvm::SplitBlockAndInsertIfThenElse().
createTaskgroup()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::createTaskgroup (const LocationDescription & Loc, InsertPointTy AllocaIP, BodyGenCallbackTy BodyGenCB)
Generator for the taskgroup construct.
Parameters
Loc The location where the taskgroup construct was encountered.
AllocaIP The insertion point to be used for alloca instructions.
BodyGenCB Callback that will generate the region code.
Definition at line 1551 of file OMPIRBuilder.cpp.
References Builder, and llvm::splitBB().
createTaskwait()
void OpenMPIRBuilder::createTaskwait (const LocationDescription & Loc)
Generator for '#omp taskwait'.
Parameters
Loc The location where the taskwait directive was encountered.
Definition at line 1258 of file OMPIRBuilder.cpp.
createTaskyield()
void OpenMPIRBuilder::createTaskyield (const LocationDescription & Loc)
Generator for '#omp taskyield'.
Parameters
Loc The location where the taskyield directive was encountered.
Definition at line 1276 of file OMPIRBuilder.cpp.
emitBarrierImpl()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::emitBarrierImpl (const LocationDescription & Loc, omp::Directive DK, bool ForceSimpleCall, bool CheckCancelFlag)
Generate a barrier runtime call.
Parameters
Loc The location at which the request originated and is fulfilled.
DK The directive which caused the barrier
ForceSimpleCall Flag to force a simple (=non-cancellation) barrier.
CheckCancelFlag Flag to indicate a cancel barrier return value should be checked and acted upon.
Returns
The insertion point after the barrier.
Definition at line 677 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and Builder.
emitCancelationCheckImpl()
void OpenMPIRBuilder::emitCancelationCheckImpl (Value * CancelFlag, omp::Directive CanceledDirective, FinalizeCallbackTy ExitCB = {})
Generate control flow and cleanup for cancellation.
Parameters
CancelFlag Flag indicating if the cancellation is performed.
CanceledDirective The kind of directive that is cancled.
ExitCB Extra code to be generated in the exit block.
Definition at line 842 of file OMPIRBuilder.cpp.
References assert(), BB, llvm::BasicBlock::begin(), Builder, llvm::BasicBlock::Create(), and llvm::SplitBlock().
emitFlush()
void OpenMPIRBuilder::emitFlush (const LocationDescription & Loc)
Generate a flush runtime call.
Parameters
Loc The location at which the request originated and is fulfilled.
Definition at line 1230 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and Builder.
emitMapperCall()
void OpenMPIRBuilder::emitMapperCall (const LocationDescription & Loc, Function * MapperFunc, Value * SrcLocInfo, Value * MaptypesArg, Value * MapnamesArg, struct MapperAllocas & MapperAllocas, int64_t DeviceID, unsigned NumOperands)
Create the call for the target mapper function.
Parameters
Loc The source location description.
MapperFunc Function to be called.
SrcLocInfo Source location information global.
MaptypesArg The argument types.
MapnamesArg The argument names.
MapperAllocas The AllocaInst used for the call.
DeviceID Device ID for the call.
NumOperands Number of operands in the call.
Definition at line 4120 of file OMPIRBuilder.cpp.
References llvm::OpenMPIRBuilder::MapperAllocas::Args, llvm::OpenMPIRBuilder::MapperAllocas::ArgsBase, llvm::OpenMPIRBuilder::MapperAllocas::ArgSizes, Builder, llvm::ArrayType::get(), and llvm::Constant::getNullValue().
emitOffloadingArraysArgument()
void OpenMPIRBuilder::emitOffloadingArraysArgument (IRBuilderBase & Builder, OpenMPIRBuilder::TargetDataRTArgs & RTArgs, OpenMPIRBuilder::TargetDataInfo & Info, bool EmitDebug = false, bool ForEndCall = false)
Emit the arguments to be passed to the runtime library based on the arrays of base pointers, pointers, sizes, map types, and mappers.
If ForEndCall, emit map types to be passed for the end of the region instead of the beginning.
Definition at line 4146 of file OMPIRBuilder.cpp.
References assert(), llvm::OpenMPIRBuilder::TargetDataRTArgs::BasePointersArray, Builder, llvm::ArrayType::get(), llvm::ConstantPointerNull::get(), llvm::Type::getInt64PtrTy(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), Info, M, llvm::OpenMPIRBuilder::TargetDataRTArgs::MapNamesArray, llvm::OpenMPIRBuilder::TargetDataRTArgs::MappersArray, llvm::OpenMPIRBuilder::TargetDataRTArgs::MapTypesArray, llvm::OpenMPIRBuilder::TargetDataRTArgs::PointersArray, and llvm::OpenMPIRBuilder::TargetDataRTArgs::SizesArray.
emitOffloadingEntry()
void OpenMPIRBuilder::emitOffloadingEntry (Constant * Addr, StringRef Name, uint64_t Size, int32_t Flags, StringRef SectionName = "omp_offloading_entries")
Create an offloading section struct used to register this global at runtime.
Type struct __tgt_offload_entry{ void *addr; // Pointer to the offload entry info. // (function or global) char *name; // Name of the function or global. size_t size; // Size of the entry info (0 if it a function). int32_t flags; int32_t reserved; };
Parameters
Addr The pointer to the global being registered.
Name The symbol name associated with the global.
Size The size in bytes of the global (0 for functions).
Flags Flags associated with the entry.
SectionName The section this entry will be placed at.
Definition at line 777 of file OMPIRBuilder.cpp.
References Addr, llvm::omp::Flags, llvm::ConstantInt::get(), llvm::ConstantStruct::get(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantDataArray::getString(), llvm::Value::getType(), llvm::GlobalValue::Global, Int32Ty, llvm::GlobalValue::InternalLinkage, and M.
emitTargetKernel()
OpenMPIRBuilder::InsertPointTy OpenMPIRBuilder::emitTargetKernel (const LocationDescription & Loc, Value *& Return, Value * Ident, Value * DeviceID, Value * NumTeams, Value * NumThreads, Value * HostPtr, ArrayRef< Value * > KernelArgs)
Generate a target region entry call.
Parameters
Loc The location at which the request originated and is fulfilled.
Return Return value of the created function returned by reference.
DeviceID Identifier for the device via the 'device' clause.
NumTeams Numer of teams for the region via the 'num_teams' clause or 0 if unspecified and -1 if there is no 'teams' clause.
NumThreads Number of threads via the 'thread_limit' clause.
HostPtr Pointer to the host-side pointer of the target kernel.
KernelArgs Array of arguments to the kernel.
Definition at line 815 of file OMPIRBuilder.cpp.
References Arg, Builder, I, llvm::OpenMPIRBuilder::LocationDescription::IP, M, and llvm::ArrayRef< T >::size().
emitTargetRegionFunction()
void OpenMPIRBuilder::emitTargetRegionFunction (OffloadEntriesInfoManager & InfoManager, TargetRegionEntryInfo & EntryInfo, FunctionGenCallback & GenerateFunctionCallback, int32_t NumTeams, int32_t NumThreads, bool IsOffloadEntry, Function *& OutlinedFn, Constant *& OutlinedFnID)
Create a unique name for the entry function using the source location information of the current target region.
The name will be something like:
__omp_offloading_DD_FFFF_PP_lBB[_CC]
where DD_FFFF is an ID unique to the file (device and file IDs), PP is the mangled name of the function that encloses the target region and BB is the line number of the target region. CC is a count added when more than one region is located at the same location.
If this target outline function is not an offload entry, we don't need to register it. This may happen if it is guarded by an if clause that is false at compile time, or no target archs have been specified.
The created target region ID is used by the runtime library to identify the current target region, so it only has to be unique and not necessarily point to anything. It could be the pointer to the outlined function that implements the target region, but we aren't using that so that the compiler doesn't need to keep that, and could therefore inline the host function if proven worthwhile during optimization. In the other hand, if emitting code for the device, the ID has to be the function address so that it can retrieved from the offloading entry and launched by the runtime library. We also mark the outlined function to have external linkage in case we are emitting code for the device, because these functions will be entry points to the device.
Parameters
InfoManager The info manager keeping track of the offload entries
EntryInfo The entry information about the function
GenerateFunctionCallback The callback function to generate the code
NumTeams Number default teams
NumThreads Number default threads
OutlinedFunction Pointer to the outlined function
EntryFnIDName Name of the ID o be created
Definition at line 3998 of file OMPIRBuilder.cpp.
References llvm::OffloadEntriesInfoManager::getTargetRegionEntryFnName().
emitTaskwaitImpl()
void OpenMPIRBuilder::emitTaskwaitImpl (const LocationDescription & Loc)
Generate a taskwait runtime call.
Parameters
Loc The location at which the request originated and is fulfilled.
Definition at line 1245 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and Builder.
emitTaskyieldImpl()
void OpenMPIRBuilder::emitTaskyieldImpl (const LocationDescription & Loc)
Generate a taskyield runtime call.
Parameters
Loc The location at which the request originated and is fulfilled.
Definition at line 1264 of file OMPIRBuilder.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, and llvm::Constant::getNullValue().
finalize()
void OpenMPIRBuilder::finalize (Function * Fn = nullptr)
Finalize the underlying module, e.g., by outlining regions.
Parameters
Fn The function to be finalized. If not used, all functions are finalized.
Definition at line 450 of file OMPIRBuilder.cpp.
References assert(), llvm::SmallPtrSetImplBase::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), llvm::BasicBlock::empty(), llvm::CodeExtractor::excludeArgFromAggregate(), llvm::CodeExtractor::extractCodeRegion(), llvm::Function::getEntryBlock(), llvm::Function::getFunction(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Function::getReturnType(), llvm::BasicBlock::getUniqueSuccessor(), llvm::CodeExtractor::isEligible(), llvm::Type::isVoidTy(), LLVM_DEBUG, M, llvm::BasicBlock::rbegin(), and llvm::Function::removeFromParent().
getInsertionPoint()
InsertPointTy llvm::OpenMPIRBuilder::getInsertionPoint () inline
}
Return the insertion point used by the underlying IRBuilder.
Definition at line 912 of file OMPIRBuilder.h.
References Builder, and llvm::IRBuilderBase::saveIP().
getOpenMPDefaultSimdAlign()
unsigned OpenMPIRBuilder::getOpenMPDefaultSimdAlign (const Triple & TargetTriple, const StringMap< bool > & Features) static
Get the default alignment value for given target.
Parameters
TargetTriple Target triple
Features StringMap which describes extra CPU features
Definition at line 3057 of file OMPIRBuilder.cpp.
References llvm::Triple::isPPC(), llvm::Triple::isWasm(), llvm::Triple::isX86(), and llvm::StringMap< ValueTy, AllocatorTy >::lookup().
getOrCreateDefaultSrcLocStr()
Constant * OpenMPIRBuilder::getOrCreateDefaultSrcLocStr (uint32_t & SrcLocStrSize)
Return the (LLVM-IR) string describing the default source location.
Definition at line 634 of file OMPIRBuilder.cpp.
getOrCreateIdent()
Constant * OpenMPIRBuilder::getOrCreateIdent (Constant * SrcLocStr, uint32_t SrcLocStrSize, omp::IdentFlag Flags = omp::IdentFlag(0), unsigned Reserve2Flags = 0)
Return an ident_t* encoding the source location SrcLocStr and Flags.
TODO: Create a enum class for the Reserve2Flags
Definition at line 554 of file OMPIRBuilder.cpp.
References Align, llvm::ConstantInt::get(), llvm::ConstantStruct::get(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::GlobalValue::Global, M, llvm::GlobalValue::NotThreadLocal, llvm::GlobalValue::PrivateLinkage, and uint64_t.
getOrCreateInternalVariable()
GlobalVariable * OpenMPIRBuilder::getOrCreateInternalVariable (Type * Ty, const StringRef & Name, unsigned AddressSpace = 0)
Gets (if variable with the given name already exist) or creates internal global variable with the specified Name.
The created variable has linkage CommonLinkage by default and is initialized by null value.
Parameters
Ty Type of the global variable. If it is exist already the type must be the same.
Name Name of the variable.
Definition at line 4061 of file OMPIRBuilder.cpp.
References assert(), llvm::GlobalValue::CommonLinkage, llvm::Constant::getNullValue(), M, and llvm::GlobalValue::NotThreadLocal.
getOrCreateRuntimeFunction()
FunctionCallee OpenMPIRBuilder::getOrCreateRuntimeFunction (Module & M, omp::RuntimeFunction FnID)
Return the function declaration for the runtime function with FnID.
Definition at line 383 of file OMPIRBuilder.cpp.
References llvm::GlobalObject::addMetadata(), assert(), llvm::MDBuilder::createCallbackEncoding(), llvm::dbgs(), llvm::MDNode::get(), llvm::ConstantExpr::getBitCast(), llvm::Function::getContext(), llvm::Function::getFunctionType(), llvm::Value::getName(), llvm::Type::getPointerTo(), llvm::GlobalObject::hasMetadata(), and LLVM_DEBUG.
Referenced by getKmpcForDynamicFiniForType(), getKmpcForDynamicInitForType(), getKmpcForDynamicNextForType(), and getKmpcForStaticInitForType().
getOrCreateRuntimeFunctionPtr()
Function * OpenMPIRBuilder::getOrCreateRuntimeFunctionPtr (omp::RuntimeFunction FnID)
Definition at line 441 of file OMPIRBuilder.cpp.
References assert(), llvm::FunctionCallee::getCallee(), and M.
getOrCreateSrcLocStr() [1/4]
Constant * OpenMPIRBuilder::getOrCreateSrcLocStr (const LocationDescription & Loc, uint32_t & SrcLocStrSize)
Return the (LLVM-IR) string describing the source location Loc.
Definition at line 656 of file OMPIRBuilder.cpp.
References llvm::OpenMPIRBuilder::LocationDescription::DL, and llvm::OpenMPIRBuilder::LocationDescription::IP.
getOrCreateSrcLocStr() [2/4]
Constant * OpenMPIRBuilder::getOrCreateSrcLocStr (DebugLoc DL, uint32_t & SrcLocStrSize, Function * F = nullptr)
Return the (LLVM-IR) string describing the DebugLoc DL.
Use F as fallback if DL does not specify the function name.
Definition at line 639 of file OMPIRBuilder.cpp.
References DL, llvm::Function::empty(), F, M, and llvm::Sched::Source.
getOrCreateSrcLocStr() [3/4]
Constant * OpenMPIRBuilder::getOrCreateSrcLocStr (StringRef FunctionName, StringRef FileName, unsigned Line, unsigned Column, uint32_t & SrcLocStrSize)
Return the (LLVM-IR) string describing the source location identified by the arguments.
Definition at line 615 of file OMPIRBuilder.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::SmallString< InternalLen >::str(), and llvm::to_string().
getOrCreateSrcLocStr() [4/4]
Constant * OpenMPIRBuilder::getOrCreateSrcLocStr (StringRef LocStr, uint32_t & SrcLocStrSize)
Return the (LLVM-IR) string describing the source location LocStr.
Definition at line 594 of file OMPIRBuilder.cpp.
References Builder, llvm::ConstantExpr::getPointerCast(), llvm::ConstantDataArray::getString(), M, and llvm::StringRef::size().
getOrCreateThreadID()
Value * OpenMPIRBuilder::getOrCreateThreadID (Value * Ident)
Return the current thread ID.
Parameters
Ident The ident (ident_t*) describing the query origin.
Definition at line 662 of file OMPIRBuilder.cpp.
References Builder.
initialize()
void OpenMPIRBuilder::initialize ()
Initialize the internal state, this will put structures types and potentially other helpers into the underlying module.
Must be called before any other method and only once!
Definition at line 448 of file OMPIRBuilder.cpp.
References M.
isLastFinalizationInfoCancellable()
bool llvm::OpenMPIRBuilder::isLastFinalizationInfoCancellable (omp::Directive DK) inline
Return true if the last entry in the finalization stack is of kind DK and cancellable.
Definition at line 1028 of file OMPIRBuilder.h.
References FinalizationStack.
loadOffloadInfoMetadata()
void OpenMPIRBuilder::loadOffloadInfoMetadata (Module & M, OffloadEntriesInfoManager & OffloadEntriesInfoManager)
Loads all the offload entries information from the host IR metadata.
This function is only meant to be used with device code generation.
Parameters
M Module to load Metadata info from. Module passed maybe loaded from bitcode file, i.e, different from OpenMPIRBuilder::M module.
OffloadEntriesInfoManager Initialize Offload Entry information.
Definition at line 4978 of file OMPIRBuilder.cpp.
References llvm::OffloadEntriesInfoManager::initializeDeviceGlobalVarEntryInfo(), llvm::OffloadEntriesInfoManager::initializeTargetRegionEntryInfo(), llvm_unreachable, M, llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadingEntryInfoDeviceGlobalVar, llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadingEntryInfoTargetRegion, and llvm::NamedMDNode::operands().
popFinalizationCB()
void llvm::OpenMPIRBuilder::popFinalizationCB () inline
Pop the last finalization callback from the finalization stack.
NOTE: Temporary solution until Clang CG is gone.
Definition at line 234 of file OMPIRBuilder.h.
References FinalizationStack.
pushFinalizationCB()
void llvm::OpenMPIRBuilder::pushFinalizationCB (const FinalizationInfo & FI) inline
Push a finalization callback on the finalization stack.
NOTE: Temporary solution until Clang CG is gone.
Definition at line 227 of file OMPIRBuilder.h.
References FinalizationStack.
registerTargetRegionFunction()
Constant * OpenMPIRBuilder::registerTargetRegionFunction (OffloadEntriesInfoManager & InfoManager, TargetRegionEntryInfo & EntryInfo, Function * OutlinedFunction, StringRef EntryFnName, StringRef EntryFnIDName, int32_t NumTeams, int32_t NumThreads)
Registers the given function and sets up the attribtues of the function Returns the FunctionID.
Parameters
InfoManager The info manager keeping track of the offload entries
EntryInfo The entry information about the function
OutlinedFunction Pointer to the outlined function
EntryFnName Name of the outlined function
EntryFnIDName Name of the ID o be created
NumTeams Number default teams
NumThreads Number default threads
Definition at line 4027 of file OMPIRBuilder.cpp.
References llvm::OffloadEntriesInfoManager::OMPTargetRegionEntryTargetRegion, and llvm::OffloadEntriesInfoManager::registerTargetRegionEntryInfo().
setConfig()
void llvm::OpenMPIRBuilder::setConfig (OpenMPIRBuilderConfig C) inline
Definition at line 178 of file OMPIRBuilder.h.
References Config.
tileLoops()
std::vector< CanonicalLoopInfo * > OpenMPIRBuilder::tileLoops (DebugLoc DL, ArrayRef< CanonicalLoopInfo * > Loops, ArrayRef< Value * > TileSizes)
Tile a loop nest.
Tiles the loops of Loops by the tile sizes in TileSizes. Loops in / Loops must be perfectly nested, from outermost to innermost loop (i.e. Loops.front() is the outermost loop). The trip count llvm::Value of every loop and every tile sizes must be usable in the outermost loop's preheader. This implies that the loop nest is rectangular.
Example:
for (int i = 0; i < 15; ++i) // Canonical loop "i"
  for (int j = 0; j < 14; ++j) // Canonical loop "j"
      body(i, j);
After tiling with Loops={i,j} and TileSizes={5,7}, the loop is changed to
for (int i1 = 0; i1 < 3; ++i1)
  for (int j1 = 0; j1 < 2; ++j1)
    for (int i2 = 0; i2 < 5; ++i2)
      for (int j2 = 0; j2 < 7; ++j2)
        body(i1*3+i2, j1*3+j2);
The returned vector are the loops {i1,j1,i2,j2}. The loops i1 and j1 are referred to the floor, and the loops i2 and j2 are the tiles. Tiling also handles non-constant trip counts, non-constant tile sizes and trip counts that are not multiples of the tile size. In the latter case the tile loop of the last floor-loop iteration will have fewer iterations than specified as its tile size.
Parameters
DL Debug location for instructions added by tiling, for instance the floor- and tile trip count computation.
Loops Loops to tile. The CanonicalLoopInfo objects are invalidated by this method, i.e. should not used after tiling.
TileSizes For each loop in Loops, the tile size for that dimensions.
Returns
A list of generated loops. Contains twice as many loops as the input loop nest; the first half are the floor loops and the second half are the tile loops.
Definition at line 2741 of file OMPIRBuilder.cpp.
References assert(), Builder, DL, llvm::SmallVectorImpl< T >::emplace_back(), llvm::enumerate(), F, llvm::ConstantInt::get(), llvm::CanonicalLoopInfo::getAfter(), llvm::CanonicalLoopInfo::getBody(), llvm::CanonicalLoopInfo::getExit(), llvm::CanonicalLoopInfo::getIndVar(), llvm::CanonicalLoopInfo::getLatch(), llvm::BasicBlock::getParent(), llvm::CanonicalLoopInfo::getPreheader(), llvm::CanonicalLoopInfo::getPreheaderIP(), llvm::Value::getType(), i, Loops, P, redirectAllPredecessorsTo(), redirectTo(), removeUnusedBlocksFromParent(), llvm::Value::replaceAllUsesWith(), llvm::SmallVectorImpl< T >::reserve(), Shift, llvm::ArrayRef< T >::size(), and TileSize.
unrollLoopFull()
void OpenMPIRBuilder::unrollLoopFull (DebugLoc DL, CanonicalLoopInfo * Loop)
Fully unroll a loop.
Instead of unrolling the loop immediately (and duplicating its body instructions), it is deferred to LLVM's LoopUnrollPass by adding loop metadata.
Parameters
DL Debug location for instructions added by unrolling.
Loop The loop to unroll. The loop will be invalidated.
Definition at line 2980 of file OMPIRBuilder.cpp.
References addLoopMetadata(), Builder, llvm::MDString::get(), and llvm::MDNode::get().
unrollLoopHeuristic()
void OpenMPIRBuilder::unrollLoopHeuristic (DebugLoc DL, CanonicalLoopInfo * Loop)
Fully or partially unroll a loop.
How the loop is unrolled is determined using LLVM's LoopUnrollPass.
Parameters
DL Debug location for instructions added by unrolling.
Loop The loop to unroll. The loop will be invalidated.
Definition at line 2987 of file OMPIRBuilder.cpp.
References addLoopMetadata(), Builder, llvm::MDString::get(), and llvm::MDNode::get().
unrollLoopPartial()
void OpenMPIRBuilder::unrollLoopPartial (DebugLoc DL, CanonicalLoopInfo * Loop, int32_t Factor, CanonicalLoopInfo ** UnrolledCLI)
Partially unroll a loop.
The CanonicalLoopInfo of the unrolled loop for use with chained loop-associated directive can be requested using UnrolledCLI. Not needing the CanonicalLoopInfo allows more efficient code generation by deferring the actual unrolling to the LoopUnrollPass using loop metadata. A loop-associated directive applied to the unrolled loop needs to know the new trip count which means that if using a heuristically determined unroll factor (Factor == 0), that factor must be computed immediately. We are using the same logic as the LoopUnrollPass to derived the unroll factor, but which assumes that some canonicalization has taken place (e.g. Mem2Reg, LICM, GVN, Inlining, etc.). That is, the heuristic will perform better when the unrolled loop's CanonicalLoopInfo is not needed.
Parameters
DL Debug location for instructions added by unrolling.
Loop The loop to unroll. The loop will be invalidated.
Factor The factor to unroll the loop by. A factor of 0 indicates that a heuristic should be used to determine the unroll-factor.
UnrolledCLI If non-null, receives the CanonicalLoopInfo of the partially unrolled loop. Otherwise, uses loop metadata to defer unrolling to the LoopUnrollPass.
Definition at line 3346 of file OMPIRBuilder.cpp.
References addLoopMetadata(), assert(), computeHeuristicUnrollFactor(), DL, F, llvm::ConstantInt::get(), llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDNode::get(), llvm::Type::getInt32Ty(), and llvm::Type::getIntegerBitWidth().
updateToLocation()
bool llvm::OpenMPIRBuilder::updateToLocation (const LocationDescription & Loc) inline
Update the internal location to Loc.
Definition at line 915 of file OMPIRBuilder.h.
References Builder, llvm::OpenMPIRBuilder::LocationDescription::DL, llvm::OpenMPIRBuilder::LocationDescription::IP, llvm::IRBuilderBase::restoreIP(), and llvm::IRBuilderBase::SetCurrentDebugLocation().
Member Data Documentation
Builder
IRBuilder llvm::OpenMPIRBuilder::Builder
The LLVM-IR Builder used to create IR.
Definition at line 1056 of file OMPIRBuilder.h.
Referenced by getInsertionPoint(), and updateToLocation().
Config
OpenMPIRBuilderConfig llvm::OpenMPIRBuilder::Config
The OpenMPIRBuilder Configuration.
Definition at line 1050 of file OMPIRBuilder.h.
Referenced by setConfig().
FinalizationStack
SmallVector<FinalizationInfo, 8> llvm::OpenMPIRBuilder::FinalizationStack
The finalization stack made up of finalize callbacks currently in-flight, wrapped into FinalizationInfo objects that reference also the finalization target block and the kind of cancellable directive.
Definition at line 1024 of file OMPIRBuilder.h.
Referenced by isLastFinalizationInfoCancellable(), popFinalizationCB(), and pushFinalizationCB().
IdentMap
DenseMap<std::pair<Constant *, uint64_t>, Constant *> llvm::OpenMPIRBuilder::IdentMap
Map to remember existing ident_t*.
Definition at line 1062 of file OMPIRBuilder.h.
InternalVars
StringMap<Constant*, BumpPtrAllocator> llvm::OpenMPIRBuilder::InternalVars
An ordered map of auto-generated variables to their unique names.
It stores variables with the following names: 1) ".gomp_critical_user_" + <critical_section_name> + ".var" for "omp critical" directives; 2) <mangled_name_for_global_var> + ".cache." for cache for threadprivate variables.
Definition at line 1096 of file OMPIRBuilder.h.
LoopInfos
std::forward_list<CanonicalLoopInfo> llvm::OpenMPIRBuilder::LoopInfos
Collection of owned canonical loop objects that eventually need to be free'd.
Definition at line 1086 of file OMPIRBuilder.h.
M
Module& llvm::OpenMPIRBuilder::M
The underlying LLVM-IR module.
Definition at line 1053 of file OMPIRBuilder.h.
ompOffloadInfoName
const std::string llvm::OpenMPIRBuilder::ompOffloadInfoName = "omp_offload.info"
OMP Offload Info Metadata name string.
Definition at line 1885 of file OMPIRBuilder.h.
OutlineInfos
SmallVector<OutlineInfo, 16> llvm::OpenMPIRBuilder::OutlineInfos
Collection of regions that need to be outlined during finalization.
Definition at line 1082 of file OMPIRBuilder.h.
Referenced by addOutlineInfo().
SrcLocStrMap
StringMap<Constant *> llvm::OpenMPIRBuilder::SrcLocStrMap
Map to remember source location strings.
Definition at line 1059 of file OMPIRBuilder.h.
The documentation for this class was generated from the following files:
include/llvm/Frontend/OpenMP/OMPIRBuilder.h
lib/Frontend/OpenMP/OMPIRBuilder.cpp