LLVM: llvm::GraphDiff< NodePtr, InverseGraph > Class Template Reference
llvm::GraphDiff< NodePtr, InverseGraph > Class Template Reference
#include "llvm/Support/CFGDiff.h"
Public Types
using VectRet = SmallVector< NodePtr, 8 >
Public Member Functions
GraphDiff ()
GraphDiff (ArrayRef< cfg::Update< NodePtr >> Updates, bool ReverseApplyUpdates=false)
auto getLegalizedUpdates () const
unsigned getNumLegalizedUpdates () const
cfg::Update< NodePtr > popUpdateForIncrementalUpdates ()
template<bool InverseEdge>
VectRet getChildren (NodePtr N) const
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
template<typename NodePtr, bool InverseGraph = false>
class llvm::GraphDiff< NodePtr, InverseGraph >
Definition at line 57 of file CFGDiff.h.
Member Typedef Documentation
VectRet
template<typename NodePtr , bool InverseGraph = false> using llvm::GraphDiff< NodePtr, InverseGraph >::VectRet = SmallVector<NodePtr, 8>
Definition at line 134 of file CFGDiff.h.
Constructor & Destructor Documentation
GraphDiff() [1/2]
template<typename NodePtr , bool InverseGraph = false> llvm::GraphDiff< NodePtr, InverseGraph >::GraphDiff () inline
Definition at line 94 of file CFGDiff.h.
GraphDiff() [2/2]
template<typename NodePtr , bool InverseGraph = false> llvm::GraphDiff< NodePtr, InverseGraph >::GraphDiff (ArrayRef< cfg::Update< NodePtr >> Updates, bool ReverseApplyUpdates = false) inline
Definition at line 95 of file CFGDiff.h.
References llvm::cfg::Insert.
Member Function Documentation
dump()
template<typename NodePtr , bool InverseGraph = false> LLVM_DUMP_METHOD void llvm::GraphDiff< NodePtr, InverseGraph >::dump () const inline
Definition at line 172 of file CFGDiff.h.
References llvm::dbgs(), and llvm::GraphDiff< NodePtr, InverseGraph >::print().
getChildren()
template<typename NodePtr , bool InverseGraph = false> template<bool InverseEdge> VectRet llvm::GraphDiff< NodePtr, InverseGraph >::getChildren (NodePtr N) const inline
Definition at line 135 of file CFGDiff.h.
References llvm::append_range(), llvm::erase_value(), and N.
getLegalizedUpdates()
template<typename NodePtr , bool InverseGraph = false> auto llvm::GraphDiff< NodePtr, InverseGraph >::getLegalizedUpdates () const inline
Definition at line 107 of file CFGDiff.h.
References llvm::make_range().
getNumLegalizedUpdates()
template<typename NodePtr , bool InverseGraph = false> unsigned llvm::GraphDiff< NodePtr, InverseGraph >::getNumLegalizedUpdates () const inline
Definition at line 111 of file CFGDiff.h.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates().
popUpdateForIncrementalUpdates()
template<typename NodePtr , bool InverseGraph = false> cfg::Update<NodePtr> llvm::GraphDiff< NodePtr, InverseGraph >::popUpdateForIncrementalUpdates () inline
Definition at line 113 of file CFGDiff.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::cfg::Insert, and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyNextUpdate(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates().
print()
template<typename NodePtr , bool InverseGraph = false> void llvm::GraphDiff< NodePtr, InverseGraph >::print (raw_ostream & OS) const inline
Definition at line 160 of file CFGDiff.h.
References OS.
Referenced by llvm::GraphDiff< NodePtr, InverseGraph >::dump().
The documentation for this class was generated from the following file:
include/llvm/Support/CFGDiff.h