LLVM: llvm::objcopy::elf::Writer Class Reference
llvm::objcopy::elf::Writer Class Reference abstract
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
virtual ~Writer ()
virtual Error finalize ()=0
virtual Error write ()=0
Writer (Object &O, raw_ostream &Out)
Protected Attributes
Object & Obj
std::unique_ptr< WritableMemoryBuffer > Buf
raw_ostream & Out
Detailed Description
Definition at line 307 of file ELFObject.h.
Constructor & Destructor Documentation
~Writer()
Writer::~Writer () virtual default
Writer()
llvm::objcopy::elf::Writer::Writer (Object & O, raw_ostream & Out) inline
Definition at line 318 of file ELFObject.h.
Referenced by llvm::objcopy::elf::IHexWriter::write().
Member Function Documentation
finalize()
virtual Error llvm::objcopy::elf::Writer::finalize () pure virtual
Implemented in llvm::objcopy::elf::IHexWriter, llvm::objcopy::elf::BinaryWriter, and llvm::objcopy::elf::ELFWriter< ELFT >.
Referenced by writeOutput().
write()
virtual Error llvm::objcopy::elf::Writer::write () pure virtual
Implemented in llvm::objcopy::elf::IHexWriter, llvm::objcopy::elf::BinaryWriter, and llvm::objcopy::elf::ELFWriter< ELFT >.
Referenced by writeOutput().
Member Data Documentation
Buf
std::unique_ptr<WritableMemoryBuffer> llvm::objcopy::elf::Writer::Buf protected
Definition at line 310 of file ELFObject.h.
Referenced by llvm::objcopy::elf::BinaryWriter::finalize(), and llvm::objcopy::elf::IHexWriter::write().
Obj
Object& llvm::objcopy::elf::Writer::Obj protected
Definition at line 309 of file ELFObject.h.
Referenced by llvm::objcopy::elf::BinaryWriter::finalize(), llvm::objcopy::elf::IHexWriter::finalize(), and llvm::objcopy::elf::BinaryWriter::write().
Out
raw_ostream& llvm::objcopy::elf::Writer::Out protected
Definition at line 311 of file ELFObject.h.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp