LLVM: llvm::AttrBuilder Class Reference
llvm::AttrBuilder Class Reference
#include "llvm/IR/Attributes.h"
Public Member Functions
AttrBuilder (LLVMContext &Ctx)
AttrBuilder (const AttrBuilder &)=delete
AttrBuilder (AttrBuilder &&)=default
AttrBuilder (LLVMContext &Ctx, const Attribute &A)
AttrBuilder (LLVMContext &Ctx, AttributeSet AS)
void clear ()
AttrBuilder & addAttribute (Attribute::AttrKind Val)
Add an attribute to the builder.
AttrBuilder & addAttribute (Attribute A)
Add the Attribute object to the builder.
AttrBuilder & addAttribute (StringRef A, StringRef V=StringRef())
Add the target-dependent attribute to the builder.
AttrBuilder & removeAttribute (Attribute::AttrKind Val)
Remove an attribute from the builder.
AttrBuilder & removeAttribute (StringRef A)
Remove the target-dependent attribute from the builder.
AttrBuilder & removeAttribute (Attribute A)
Remove the target-dependent attribute from the builder.
AttrBuilder & merge (const AttrBuilder &B)
Add the attributes from the builder.
AttrBuilder & remove (const AttributeMask &AM)
Remove the attributes from the builder.
bool overlaps (const AttributeMask &AM) const
Return true if the builder has any attribute that's in the specified builder.
bool contains (Attribute::AttrKind A) const
Return true if the builder has the specified attribute.
bool contains (StringRef A) const
Return true if the builder has the specified target-dependent attribute.
bool hasAttributes () const
Return true if the builder has IR-level attributes.
Attribute getAttribute (Attribute::AttrKind Kind) const
Return Attribute with the given Kind.
Attribute getAttribute (StringRef Kind) const
Return Attribute with the given Kind.
std::optional< uint64_t > getRawIntAttr (Attribute::AttrKind Kind) const
Return raw (possibly packed/encoded) value of integer attribute or std::nullopt if not set.
MaybeAlign getAlignment () const
Retrieve the alignment attribute, if it exists.
MaybeAlign getStackAlignment () const
Retrieve the stack alignment attribute, if it exists.
uint64_t getDereferenceableBytes () const
Retrieve the number of dereferenceable bytes, if the dereferenceable attribute exists (zero is returned otherwise).
uint64_t getDereferenceableOrNullBytes () const
Retrieve the number of dereferenceable_or_null bytes, if the dereferenceable_or_null attribute exists (zero is returned otherwise).
Type * getTypeAttr (Attribute::AttrKind Kind) const
Retrieve type for the given type attribute.
Type * getByValType () const
Retrieve the byval type.
Type * getStructRetType () const
Retrieve the sret type.
Type * getByRefType () const
Retrieve the byref type.
Type * getPreallocatedType () const
Retrieve the preallocated type.
Type * getInAllocaType () const
Retrieve the inalloca type.
std::optional< std::pair< unsigned, std::optional< unsigned > > > getAllocSizeArgs () const
Retrieve the allocsize args, or std::nullopt if the attribute does not exist.
AttrBuilder & addRawIntAttr (Attribute::AttrKind Kind, uint64_t Value)
Add integer attribute with raw value (packed/encoded if necessary).
AttrBuilder & addAlignmentAttr (MaybeAlign Align)
This turns an alignment into the form used internally in Attribute.
AttrBuilder & addAlignmentAttr (unsigned Align)
This turns an int alignment (which must be a power of 2) into the form used internally in Attribute.
AttrBuilder & addStackAlignmentAttr (MaybeAlign Align)
This turns a stack alignment into the form used internally in Attribute.
AttrBuilder & addStackAlignmentAttr (unsigned Align)
This turns an int stack alignment (which must be a power of 2) into the form used internally in Attribute.
AttrBuilder & addDereferenceableAttr (uint64_t Bytes)
This turns the number of dereferenceable bytes into the form used internally in Attribute.
AttrBuilder & addDereferenceableOrNullAttr (uint64_t Bytes)
This turns the number of dereferenceable_or_null bytes into the form used internally in Attribute.
AttrBuilder & addAllocSizeAttr (unsigned ElemSizeArg, const std::optional< unsigned > &NumElemsArg)
This turns one (or two) ints into the form used internally in Attribute.
AttrBuilder & addVScaleRangeAttr (unsigned MinValue, std::optional< unsigned > MaxValue)
This turns two ints into the form used internally in Attribute.
AttrBuilder & addTypeAttr (Attribute::AttrKind Kind, Type *Ty)
Add a type attribute with the given type.
AttrBuilder & addByValAttr (Type *Ty)
This turns a byval type into the form used internally in Attribute.
AttrBuilder & addStructRetAttr (Type *Ty)
This turns a sret type into the form used internally in Attribute.
AttrBuilder & addByRefAttr (Type *Ty)
This turns a byref type into the form used internally in Attribute.
AttrBuilder & addPreallocatedAttr (Type *Ty)
This turns a preallocated type into the form used internally in Attribute.
AttrBuilder & addInAllocaAttr (Type *Ty)
This turns an inalloca type into the form used internally in Attribute.
AttrBuilder & addAllocSizeAttrFromRawRepr (uint64_t RawAllocSizeRepr)
Add an allocsize attribute, using the representation returned by Attribute.getIntValue().
AttrBuilder & addVScaleRangeAttrFromRawRepr (uint64_t RawVScaleRangeRepr)
Add a vscale_range attribute, using the representation returned by Attribute.getIntValue().
AttrBuilder & addUWTableAttr (UWTableKind Kind)
This turns the unwind table kind into the form used internally in Attribute.
AttrBuilder & addAllocKindAttr (AllocFnKind Kind)
AttrBuilder & addMemoryAttr (MemoryEffects ME)
Add memory effect attribute.
ArrayRef< Attribute > attrs () const
bool operator== (const AttrBuilder &B) const
bool operator!= (const AttrBuilder &B) const
Detailed Description
Definition at line 1040 of file Attributes.h.
Constructor & Destructor Documentation
AttrBuilder() [1/5]
llvm::AttrBuilder::AttrBuilder (LLVMContext & Ctx) inline
Definition at line 1045 of file Attributes.h.
AttrBuilder() [2/5]
llvm::AttrBuilder::AttrBuilder (const AttrBuilder &) delete
AttrBuilder() [3/5]
llvm::AttrBuilder::AttrBuilder (AttrBuilder &&) default
AttrBuilder() [4/5]
llvm::AttrBuilder::AttrBuilder (LLVMContext & Ctx, const Attribute & A) inline
Definition at line 1049 of file Attributes.h.
References addAttribute().
AttrBuilder() [5/5]
AttrBuilder::AttrBuilder (LLVMContext & Ctx, AttributeSet AS)
Definition at line 1641 of file Attributes.cpp.
References llvm::append_range(), assert(), Attrs, and llvm::is_sorted().
Member Function Documentation
addAlignmentAttr() [1/2]
AttrBuilder & AttrBuilder::addAlignmentAttr (MaybeAlign Align)
This turns an alignment into the form used internally in Attribute.
This call has no effect if Align is not set.
Definition at line 1741 of file Attributes.cpp.
References addRawIntAttr(), assert(), llvm::Value::MaximumAlignment, and llvm::Align::value().
Referenced by addAlignmentAttr(), and addFramePointerAttrs().
addAlignmentAttr() [2/2]
AttrBuilder& llvm::AttrBuilder::addAlignmentAttr (unsigned Align) inline
This turns an int alignment (which must be a power of 2) into the form used internally in Attribute.
This call has no effect if Align is 0. Deprecated, use the version using a MaybeAlign.
Definition at line 1171 of file Attributes.h.
References addAlignmentAttr().
addAllocKindAttr()
AttrBuilder & AttrBuilder::addAllocKindAttr (AllocFnKind Kind)
Definition at line 1806 of file Attributes.cpp.
References addRawIntAttr(), and uint64_t.
addAllocSizeAttr()
AttrBuilder & AttrBuilder::addAllocSizeAttr (unsigned ElemSizeArg, const std::optional< unsigned > & NumElemsArg)
This turns one (or two) ints into the form used internally in Attribute.
Definition at line 1772 of file Attributes.cpp.
References addAllocSizeAttrFromRawRepr(), and packAllocSizeArgs().
addAllocSizeAttrFromRawRepr()
AttrBuilder & AttrBuilder::addAllocSizeAttrFromRawRepr (uint64_t RawAllocSizeRepr)
Add an allocsize attribute, using the representation returned by Attribute.getIntValue().
Definition at line 1777 of file Attributes.cpp.
References addRawIntAttr(), and assert().
Referenced by addAllocSizeAttr().
addAttribute() [1/3]
AttrBuilder & AttrBuilder::addAttribute (Attribute A)
Add the Attribute object to the builder.
Definition at line 1686 of file Attributes.cpp.
References addAttributeImpl(), llvm::Attribute::getKindAsEnum(), llvm::Attribute::getKindAsString(), and llvm::Attribute::isStringAttribute().
addAttribute() [2/3]
AttrBuilder & AttrBuilder::addAttribute (Attribute::AttrKind Val)
Add an attribute to the builder.
Definition at line 1694 of file Attributes.cpp.
References addAttributeImpl(), and llvm::Attribute::get().
Referenced by addAsyncContextAttrs(), addFramePointerAttrs(), addRawIntAttr(), addSwiftSelfAttrs(), addTypeAttr(), AttrBuilder(), IdentifyValidAttributes(), merge(), and llvm::codegen::setFunctionAttributes().
addAttribute() [3/3]
AttrBuilder & AttrBuilder::addAttribute (StringRef A, StringRef V = StringRef())
Add the target-dependent attribute to the builder.
Definition at line 1699 of file Attributes.cpp.
References addAttributeImpl(), and llvm::Attribute::get().
addByRefAttr()
AttrBuilder & AttrBuilder::addByRefAttr (Type * Ty)
This turns a byref type into the form used internally in Attribute.
Definition at line 1828 of file Attributes.cpp.
References addTypeAttr().
addByValAttr()
AttrBuilder & AttrBuilder::addByValAttr (Type * Ty)
This turns a byval type into the form used internally in Attribute.
Definition at line 1820 of file Attributes.cpp.
References addTypeAttr().
Referenced by llvm::promoteCall().
addDereferenceableAttr()
AttrBuilder & AttrBuilder::addDereferenceableAttr (uint64_t Bytes)
This turns the number of dereferenceable bytes into the form used internally in Attribute.
Definition at line 1758 of file Attributes.cpp.
References addRawIntAttr().
Referenced by addFramePointerAttrs(), and IdentifyValidAttributes().
addDereferenceableOrNullAttr()
AttrBuilder & AttrBuilder::addDereferenceableOrNullAttr (uint64_t Bytes)
This turns the number of dereferenceable_or_null bytes into the form used internally in Attribute.
Definition at line 1764 of file Attributes.cpp.
References addRawIntAttr().
Referenced by IdentifyValidAttributes().
addInAllocaAttr()
AttrBuilder & AttrBuilder::addInAllocaAttr (Type * Ty)
This turns an inalloca type into the form used internally in Attribute.
Definition at line 1836 of file Attributes.cpp.
References addTypeAttr().
Referenced by llvm::promoteCall().
addMemoryAttr()
AttrBuilder & AttrBuilder::addMemoryAttr (MemoryEffects ME)
Add memory effect attribute.
Definition at line 1802 of file Attributes.cpp.
References addRawIntAttr(), and llvm::MemoryEffects::toIntValue().
addPreallocatedAttr()
AttrBuilder & AttrBuilder::addPreallocatedAttr (Type * Ty)
This turns a preallocated type into the form used internally in Attribute.
Definition at line 1832 of file Attributes.cpp.
References addTypeAttr().
addRawIntAttr()
AttrBuilder & AttrBuilder::addRawIntAttr (Attribute::AttrKind Kind, uint64_t Value)
Add integer attribute with raw value (packed/encoded if necessary).
Definition at line 1728 of file Attributes.cpp.
References addAttribute(), and llvm::Attribute::get().
Referenced by addAlignmentAttr(), addAllocKindAttr(), addAllocSizeAttrFromRawRepr(), addDereferenceableAttr(), addDereferenceableOrNullAttr(), addMemoryAttr(), addStackAlignmentAttr(), addUWTableAttr(), and addVScaleRangeAttrFromRawRepr().
addStackAlignmentAttr() [1/2]
AttrBuilder & AttrBuilder::addStackAlignmentAttr (MaybeAlign Align)
This turns a stack alignment into the form used internally in Attribute.
This call has no effect if Align is not set.
Definition at line 1749 of file Attributes.cpp.
References addRawIntAttr(), assert(), and llvm::Align::value().
Referenced by addStackAlignmentAttr().
addStackAlignmentAttr() [2/2]
AttrBuilder& llvm::AttrBuilder::addStackAlignmentAttr (unsigned Align) inline
This turns an int stack alignment (which must be a power of 2) into the form used internally in Attribute.
This call has no effect if Align is 0. Deprecated, use the version using a MaybeAlign.
Definition at line 1183 of file Attributes.h.
References addStackAlignmentAttr().
addStructRetAttr()
AttrBuilder & AttrBuilder::addStructRetAttr (Type * Ty)
This turns a sret type into the form used internally in Attribute.
Definition at line 1824 of file Attributes.cpp.
References addTypeAttr().
addTypeAttr()
AttrBuilder & AttrBuilder::addTypeAttr (Attribute::AttrKind Kind, Type * Ty)
Add a type attribute with the given type.
Definition at line 1816 of file Attributes.cpp.
References addAttribute(), and llvm::Attribute::get().
Referenced by addByRefAttr(), addByValAttr(), addInAllocaAttr(), addPreallocatedAttr(), and addStructRetAttr().
addUWTableAttr()
AttrBuilder & AttrBuilder::addUWTableAttr (UWTableKind Kind)
This turns the unwind table kind into the form used internally in Attribute.
Definition at line 1796 of file Attributes.cpp.
References addRawIntAttr(), llvm::None, and uint64_t.
addVScaleRangeAttr()
AttrBuilder & AttrBuilder::addVScaleRangeAttr (unsigned MinValue, std::optional< unsigned > MaxValue)
This turns two ints into the form used internally in Attribute.
Definition at line 1783 of file Attributes.cpp.
References addVScaleRangeAttrFromRawRepr(), and packVScaleRangeArgs().
addVScaleRangeAttrFromRawRepr()
AttrBuilder & AttrBuilder::addVScaleRangeAttrFromRawRepr (uint64_t RawVScaleRangeRepr)
Add a vscale_range attribute, using the representation returned by Attribute.getIntValue().
Definition at line 1788 of file Attributes.cpp.
References addRawIntAttr().
Referenced by addVScaleRangeAttr().
attrs()
ArrayRef<Attribute> llvm::AttrBuilder::attrs () const inline
Definition at line 1239 of file Attributes.h.
clear()
void AttrBuilder::clear ()
Definition at line 1646 of file Attributes.cpp.
References Attrs.
contains() [1/2]
bool AttrBuilder::contains (Attribute::AttrKind A) const
Return true if the builder has the specified attribute.
Definition at line 1872 of file Attributes.cpp.
References getAttribute(), and llvm::Attribute::isValid().
Referenced by llvm::attributesPermitTailCall().
contains() [2/2]
bool AttrBuilder::contains (StringRef A) const
Return true if the builder has the specified target-dependent attribute.
Definition at line 1876 of file Attributes.cpp.
References getAttribute(), and llvm::Attribute::isValid().
getAlignment()
MaybeAlign llvm::AttrBuilder::getAlignment () const inline
Retrieve the alignment attribute, if it exists.
Definition at line 1114 of file Attributes.h.
References getRawIntAttr().
getAllocSizeArgs()
std::optional< std::pair< unsigned, std::optional< unsigned > > > AttrBuilder::getAllocSizeArgs () const
Retrieve the allocsize args, or std::nullopt if the attribute does not exist.
Definition at line 1734 of file Attributes.cpp.
References getAttribute().
getAttribute() [1/2]
Attribute AttrBuilder::getAttribute (Attribute::AttrKind Kind) const
Return Attribute with the given Kind.
The returned attribute will be invalid if the Kind is not present in the builder.
Definition at line 1857 of file Attributes.cpp.
References assert(), llvm::Attribute::EndAttrKinds, and llvm::lower_bound().
Referenced by contains(), getAllocSizeArgs(), getRawIntAttr(), and getTypeAttr().
getAttribute() [2/2]
Attribute AttrBuilder::getAttribute (StringRef Kind) const
Return Attribute with the given Kind.
The returned attribute will be invalid if the Kind is not present in the builder.
Definition at line 1865 of file Attributes.cpp.
References llvm::lower_bound().
getByRefType()
Type* llvm::AttrBuilder::getByRefType () const inline
Retrieve the byref type.
Definition at line 1145 of file Attributes.h.
References getTypeAttr().
getByValType()
Type* llvm::AttrBuilder::getByValType () const inline
Retrieve the byval type.
Definition at line 1139 of file Attributes.h.
References getTypeAttr().
Referenced by llvm::promoteCall().
getDereferenceableBytes()
uint64_t llvm::AttrBuilder::getDereferenceableBytes () const inline
Retrieve the number of dereferenceable bytes, if the dereferenceable attribute exists (zero is returned otherwise).
Definition at line 1125 of file Attributes.h.
References getRawIntAttr().
getDereferenceableOrNullBytes()
uint64_t llvm::AttrBuilder::getDereferenceableOrNullBytes () const inline
Retrieve the number of dereferenceable_or_null bytes, if the dereferenceable_or_null attribute exists (zero is returned otherwise).
Definition at line 1131 of file Attributes.h.
References getRawIntAttr().
getInAllocaType()
Type* llvm::AttrBuilder::getInAllocaType () const inline
Retrieve the inalloca type.
Definition at line 1153 of file Attributes.h.
References getTypeAttr().
Referenced by llvm::promoteCall().
getPreallocatedType()
Type* llvm::AttrBuilder::getPreallocatedType () const inline
Retrieve the preallocated type.
Definition at line 1148 of file Attributes.h.
References getTypeAttr().
getRawIntAttr()
std::optional< uint64_t > AttrBuilder::getRawIntAttr (Attribute::AttrKind Kind) const
Return raw (possibly packed/encoded) value of integer attribute or std::nullopt if not set.
Definition at line 1720 of file Attributes.cpp.
References assert(), getAttribute(), and llvm::Attribute::isIntAttrKind().
Referenced by getAlignment(), getDereferenceableBytes(), getDereferenceableOrNullBytes(), and getStackAlignment().
getStackAlignment()
MaybeAlign llvm::AttrBuilder::getStackAlignment () const inline
Retrieve the stack alignment attribute, if it exists.
Definition at line 1119 of file Attributes.h.
References getRawIntAttr().
getStructRetType()
Type* llvm::AttrBuilder::getStructRetType () const inline
Retrieve the sret type.
Definition at line 1142 of file Attributes.h.
References getTypeAttr().
getTypeAttr()
Type * AttrBuilder::getTypeAttr (Attribute::AttrKind Kind) const
Retrieve type for the given type attribute.
Definition at line 1810 of file Attributes.cpp.
References assert(), getAttribute(), and llvm::Attribute::isTypeAttrKind().
Referenced by getByRefType(), getByValType(), getInAllocaType(), getPreallocatedType(), and getStructRetType().
hasAttributes()
bool llvm::AttrBuilder::hasAttributes () const inline
Return true if the builder has IR-level attributes.
Definition at line 1099 of file Attributes.h.
Referenced by AddReturnAttributes(), and isLibCallInTailPosition().
merge()
AttrBuilder & AttrBuilder::merge (const AttrBuilder & B)
Add the attributes from the builder.
Attributes in the passed builder overwrite attributes in this builder if they have the same key.
Definition at line 1840 of file Attributes.cpp.
References addAttribute(), B, and I.
Referenced by llvm::AttributeList::get().
operator!=()
bool llvm::AttrBuilder::operator!= (const AttrBuilder & B) const inline
Definition at line 1242 of file Attributes.h.
References B.
operator==()
bool AttrBuilder::operator== (const AttrBuilder & B) const
Definition at line 1880 of file Attributes.cpp.
References B.
overlaps()
bool AttrBuilder::overlaps (const AttributeMask & AM) const
Return true if the builder has any attribute that's in the specified builder.
Definition at line 1853 of file Attributes.cpp.
References llvm::any_of(), and llvm::AttributeMask::contains().
remove()
AttrBuilder & AttrBuilder::remove (const AttributeMask & AM)
Remove the attributes from the builder.
Definition at line 1848 of file Attributes.cpp.
References llvm::AttributeMask::contains(), and llvm::erase_if().
Referenced by llvm::promoteCall().
removeAttribute() [1/3]
AttrBuilder& llvm::AttrBuilder::removeAttribute (Attribute A) inline
Remove the target-dependent attribute from the builder.
Definition at line 1073 of file Attributes.h.
References removeAttribute().
removeAttribute() [2/3]
AttrBuilder & AttrBuilder::removeAttribute (Attribute::AttrKind Val)
Remove an attribute from the builder.
Definition at line 1704 of file Attributes.cpp.
References assert(), llvm::Attribute::EndAttrKinds, and llvm::lower_bound().
Referenced by llvm::attributesPermitTailCall(), isLibCallInTailPosition(), legalizeCallAttributes(), and removeAttribute().
removeAttribute() [3/3]
AttrBuilder & AttrBuilder::removeAttribute (StringRef A)
Remove the target-dependent attribute from the builder.
Definition at line 1712 of file Attributes.cpp.
References llvm::lower_bound().
The documentation for this class was generated from the following files:
include/llvm/IR/Attributes.h
lib/IR/Attributes.cpp