LLVM: llvm::MachineRegisterInfo Class Reference
llvm::MachineRegisterInfo Class Reference
MachineRegisterInfo - Keep track of information for virtual and physical registers, including vreg register classes, use/def chains for registers, etc.
#include "llvm/CodeGen/MachineRegisterInfo.h"
Classes
class defusechain_instr_iterator
defusechain_iterator - This class provides iterator support for machine operands in the function that use or define a specific register.
class defusechain_iterator
reg_begin/reg_end - Provide iteration support to walk over all definitions and uses of a register within the MachineFunction that corresponds to this MachineRegisterInfo object.
class Delegate
Public Types
using reg_iterator = defusechain_iterator< true, true, false, true, false, false >
reg_iterator/reg_begin/reg_end - Walk all defs and uses of the specified register.
using reg_instr_iterator = defusechain_instr_iterator< true, true, false, false, true, false >
reg_instr_iterator/reg_instr_begin/reg_instr_end - Walk all defs and uses of the specified register, stepping by MachineInstr.
using reg_bundle_iterator = defusechain_instr_iterator< true, true, false, false, false, true >
reg_bundle_iterator/reg_bundle_begin/reg_bundle_end - Walk all defs and uses of the specified register, stepping by bundle.
using reg_nodbg_iterator = defusechain_iterator< true, true, true, true, false, false >
reg_nodbg_iterator/reg_nodbg_begin/reg_nodbg_end - Walk all defs and uses of the specified register, skipping those marked as Debug.
using reg_instr_nodbg_iterator = defusechain_instr_iterator< true, true, true, false, true, false >
reg_instr_nodbg_iterator/reg_instr_nodbg_begin/reg_instr_nodbg_end - Walk all defs and uses of the specified register, stepping by MachineInstr, skipping those marked as Debug.
using reg_bundle_nodbg_iterator = defusechain_instr_iterator< true, true, true, false, false, true >
reg_bundle_nodbg_iterator/reg_bundle_nodbg_begin/reg_bundle_nodbg_end - Walk all defs and uses of the specified register, stepping by bundle, skipping those marked as Debug.
using def_iterator = defusechain_iterator< false, true, false, true, false, false >
def_iterator/def_begin/def_end - Walk all defs of the specified register.
using def_instr_iterator = defusechain_instr_iterator< false, true, false, false, true, false >
def_instr_iterator/def_instr_begin/def_instr_end - Walk all defs of the specified register, stepping by MachineInst.
using def_bundle_iterator = defusechain_instr_iterator< false, true, false, false, false, true >
def_bundle_iterator/def_bundle_begin/def_bundle_end - Walk all defs of the specified register, stepping by bundle.
using use_iterator = defusechain_iterator< true, false, false, true, false, false >
use_iterator/use_begin/use_end - Walk all uses of the specified register.
using use_instr_iterator = defusechain_instr_iterator< true, false, false, false, true, false >
use_instr_iterator/use_instr_begin/use_instr_end - Walk all uses of the specified register, stepping by MachineInstr.
using use_bundle_iterator = defusechain_instr_iterator< true, false, false, false, false, true >
use_bundle_iterator/use_bundle_begin/use_bundle_end - Walk all uses of the specified register, stepping by bundle.
using use_nodbg_iterator = defusechain_iterator< true, false, true, true, false, false >
use_nodbg_iterator/use_nodbg_begin/use_nodbg_end - Walk all uses of the specified register, skipping those marked as Debug.
using use_instr_nodbg_iterator = defusechain_instr_iterator< true, false, true, false, true, false >
use_instr_nodbg_iterator/use_instr_nodbg_begin/use_instr_nodbg_end - Walk all uses of the specified register, stepping by MachineInstr, skipping those marked as Debug.
using use_bundle_nodbg_iterator = defusechain_instr_iterator< true, false, true, false, false, true >
use_bundle_nodbg_iterator/use_bundle_nodbg_begin/use_bundle_nodbg_end - Walk all uses of the specified register, stepping by bundle, skipping those marked as Debug.
using livein_iterator = std::vector< std::pair< MCRegister, Register > >::const_iterator
Public Member Functions
MachineRegisterInfo (MachineFunction *MF)
MachineRegisterInfo (const MachineRegisterInfo &)=delete
MachineRegisterInfo & operator= (const MachineRegisterInfo &)=delete
const TargetRegisterInfo * getTargetRegisterInfo () const
void resetDelegate (Delegate *delegate)
void addDelegate (Delegate *delegate)
void noteNewVirtualRegister (Register Reg)
void noteCloneVirtualRegister (Register NewReg, Register SrcReg)
bool isSSA () const
void leaveSSA ()
bool tracksLiveness () const
tracksLiveness - Returns true when tracking register liveness accurately.
void invalidateLiveness ()
invalidateLiveness - Indicates that register liveness is no longer being tracked accurately.
bool shouldTrackSubRegLiveness (const TargetRegisterClass &RC) const
Returns true if liveness for register class RC should be tracked at the subregister level.
bool shouldTrackSubRegLiveness (Register VReg) const
bool subRegLivenessEnabled () const
bool isUpdatedCSRsInitialized () const
Returns true if the updated CSR list was initialized and false otherwise.
bool isArgumentRegister (const MachineFunction &MF, MCRegister Reg) const
Returns true if a register can be used as an argument to a function.
bool isFixedRegister (const MachineFunction &MF, MCRegister Reg) const
Returns true if a register is a fixed register.
bool isGeneralPurposeRegister (const MachineFunction &MF, MCRegister Reg) const
Returns true if a register is a general purpose register.
void disableCalleeSavedRegister (MCRegister Reg)
Disables the register from the list of CSRs.
const MCPhysReg * getCalleeSavedRegs () const
Returns list of callee saved registers.
void setCalleeSavedRegs (ArrayRef< MCPhysReg > CSRs)
Sets the updated Callee Saved Registers list.
void addRegOperandToUseList (MachineOperand *MO)
Add MO to the linked list of operands for its register.
void removeRegOperandFromUseList (MachineOperand *MO)
Remove MO from its use-def list.
void moveOperands (MachineOperand *Dst, MachineOperand *Src, unsigned NumOps)
Move NumOps operands from Src to Dst, updating use-def lists as needed.
void verifyUseList (Register Reg) const
Verify the sanity of the use list for Reg.
void verifyUseLists () const
Verify the use list of all registers.
reg_iterator reg_begin (Register RegNo) const
iterator_range< reg_iterator > reg_operands (Register Reg) const
reg_instr_iterator reg_instr_begin (Register RegNo) const
iterator_range< reg_instr_iterator > reg_instructions (Register Reg) const
reg_bundle_iterator reg_bundle_begin (Register RegNo) const
iterator_range< reg_bundle_iterator > reg_bundles (Register Reg) const
bool reg_empty (Register RegNo) const
reg_empty - Return true if there are no instructions using or defining the specified register (it may be live-in).
reg_nodbg_iterator reg_nodbg_begin (Register RegNo) const
iterator_range< reg_nodbg_iterator > reg_nodbg_operands (Register Reg) const
reg_instr_nodbg_iterator reg_instr_nodbg_begin (Register RegNo) const
iterator_range< reg_instr_nodbg_iterator > reg_nodbg_instructions (Register Reg) const
reg_bundle_nodbg_iterator reg_bundle_nodbg_begin (Register RegNo) const
iterator_range< reg_bundle_nodbg_iterator > reg_nodbg_bundles (Register Reg) const
bool reg_nodbg_empty (Register RegNo) const
reg_nodbg_empty - Return true if the only instructions using or defining Reg are Debug instructions.
def_iterator def_begin (Register RegNo) const
iterator_range< def_iterator > def_operands (Register Reg) const
def_instr_iterator def_instr_begin (Register RegNo) const
iterator_range< def_instr_iterator > def_instructions (Register Reg) const
def_bundle_iterator def_bundle_begin (Register RegNo) const
iterator_range< def_bundle_iterator > def_bundles (Register Reg) const
bool def_empty (Register RegNo) const
def_empty - Return true if there are no instructions defining the specified register (it may be live-in).
StringRef getVRegName (Register Reg) const
void insertVRegByName (StringRef Name, Register Reg)
bool hasOneDef (Register RegNo) const
Return true if there is exactly one operand defining the specified register.
MachineOperand * getOneDef (Register Reg) const
Returns the defining operand if there is exactly one operand defining the specified register, otherwise nullptr.
use_iterator use_begin (Register RegNo) const
iterator_range< use_iterator > use_operands (Register Reg) const
use_instr_iterator use_instr_begin (Register RegNo) const
iterator_range< use_instr_iterator > use_instructions (Register Reg) const
use_bundle_iterator use_bundle_begin (Register RegNo) const
iterator_range< use_bundle_iterator > use_bundles (Register Reg) const
bool use_empty (Register RegNo) const
use_empty - Return true if there are no instructions using the specified register.
bool hasOneUse (Register RegNo) const
hasOneUse - Return true if there is exactly one instruction using the specified register.
use_nodbg_iterator use_nodbg_begin (Register RegNo) const
iterator_range< use_nodbg_iterator > use_nodbg_operands (Register Reg) const
use_instr_nodbg_iterator use_instr_nodbg_begin (Register RegNo) const
iterator_range< use_instr_nodbg_iterator > use_nodbg_instructions (Register Reg) const
use_bundle_nodbg_iterator use_bundle_nodbg_begin (Register RegNo) const
iterator_range< use_bundle_nodbg_iterator > use_nodbg_bundles (Register Reg) const
bool use_nodbg_empty (Register RegNo) const
use_nodbg_empty - Return true if there are no non-Debug instructions using the specified register.
bool hasOneNonDBGUse (Register RegNo) const
hasOneNonDBGUse - Return true if there is exactly one non-Debug use of the specified register.
bool hasOneNonDBGUser (Register RegNo) const
hasOneNonDBGUse - Return true if there is exactly one non-Debug instruction using the specified register.
bool hasAtMostUserInstrs (Register Reg, unsigned MaxUsers) const
hasAtMostUses - Return true if the given register has at most MaxUsers non-debug user instructions.
void replaceRegWith (Register FromReg, Register ToReg)
replaceRegWith - Replace all instances of FromReg with ToReg in the machine function.
MachineInstr * getVRegDef (Register Reg) const
getVRegDef - Return the machine instr that defines the specified virtual register or null if none is found.
MachineInstr * getUniqueVRegDef (Register Reg) const
getUniqueVRegDef - Return the unique machine instr that defines the specified virtual register or null if none is found.
void clearKillFlags (Register Reg) const
clearKillFlags - Iterate over all the uses of the given register and clear the kill flag from the MachineOperand.
void dumpUses (Register RegNo) const
bool isConstantPhysReg (MCRegister PhysReg) const
Returns true if PhysReg is unallocatable and constant throughout the function.
PSetIterator getPressureSets (Register RegUnit) const
Get an iterator over the pressure sets affected by the given physical or virtual register.
const TargetRegisterClass * getRegClass (Register Reg) const
Return the register class of the specified virtual register.
const TargetRegisterClass * getRegClassOrNull (Register Reg) const
Return the register class of Reg, or null if Reg has not been assigned a register class yet.
const RegisterBank * getRegBankOrNull (Register Reg) const
Return the register bank of Reg, or null if Reg has not been assigned a register bank or has been assigned a register class.
const RegClassOrRegBank & getRegClassOrRegBank (Register Reg) const
Return the register bank or register class of Reg.
void setRegClass (Register Reg, const TargetRegisterClass *RC)
setRegClass - Set the register class of the specified virtual register.
void setRegBank (Register Reg, const RegisterBank &RegBank)
Set the register bank to RegBank for Reg.
void setRegClassOrRegBank (Register Reg, const RegClassOrRegBank &RCOrRB)
const TargetRegisterClass * constrainRegClass (Register Reg, const TargetRegisterClass *RC, unsigned MinNumRegs=0)
constrainRegClass - Constrain the register class of the specified virtual register to be a common subclass of RC and the current register class, but only if the new class has at least MinNumRegs registers.
bool constrainRegAttrs (Register Reg, Register ConstrainingReg, unsigned MinNumRegs=0)
Constrain the register class or the register bank of the virtual register Reg (and low-level type) to be a common subclass or a common bank of both registers provided respectively (and a common low-level type).
bool recomputeRegClass (Register Reg)
recomputeRegClass - Try to find a legal super-class of Reg's register class that still satisfies the constraints from the instructions using Reg.
Register createVirtualRegister (const TargetRegisterClass *RegClass, StringRef Name="")
createVirtualRegister - Create and return a new virtual register in the function with the specified register class.
Register cloneVirtualRegister (Register VReg, StringRef Name="")
Create and return a new virtual register in the function with the same attributes as the given register.
LLT getType (Register Reg) const
Get the low-level type of Reg or LLT{} if Reg is not a generic (target independent) virtual register.
void setType (Register VReg, LLT Ty)
Set the low-level type of VReg to Ty.
Register createGenericVirtualRegister (LLT Ty, StringRef Name="")
Create and return a new generic virtual register with low-level type Ty.
void clearVirtRegTypes ()
Remove all types associated to virtual registers (after instruction selection and constraining of all generic virtual registers).
Register createIncompleteVirtualRegister (StringRef Name="")
Creates a new virtual register that has no register class, register bank or size assigned yet.
unsigned getNumVirtRegs () const
getNumVirtRegs - Return the number of virtual registers created.
void clearVirtRegs ()
clearVirtRegs - Remove all virtual registers (after physreg assignment).
void setRegAllocationHint (Register VReg, unsigned Type, Register PrefReg)
setRegAllocationHint - Specify a register allocation hint for the specified virtual register.
void addRegAllocationHint (Register VReg, Register PrefReg)
addRegAllocationHint - Add a register allocation hint to the hints vector for VReg.
void setSimpleHint (Register VReg, Register PrefReg)
Specify the preferred (target independent) register allocation hint for the specified virtual register.
void clearSimpleHint (Register VReg)
std::pair< Register, Register > getRegAllocationHint (Register VReg) const
getRegAllocationHint - Return the register allocation hint for the specified virtual register.
Register getSimpleHint (Register VReg) const
getSimpleHint - same as getRegAllocationHint except it will only return a target independent hint.
const std::pair< Register, SmallVector< Register, 4 > > & getRegAllocationHints (Register VReg) const
getRegAllocationHints - Return a reference to the vector of all register allocation hints for VReg.
void markUsesInDebugValueAsUndef (Register Reg) const
markUsesInDebugValueAsUndef - Mark every DBG_VALUE referencing the specified register as undefined which causes the DBG_VALUE to be deleted during LiveDebugVariables analysis.
void updateDbgUsersToReg (MCRegister OldReg, MCRegister NewReg, ArrayRef< MachineInstr * > Users) const
updateDbgUsersToReg - Update a collection of debug instructions to refer to the designated register.
bool isPhysRegModified (MCRegister PhysReg, bool SkipNoReturnDef=false) const
Return true if the specified register is modified in this function.
bool isPhysRegUsed (MCRegister PhysReg, bool SkipRegMaskTest=false) const
Return true if the specified register is modified or read in this function.
void addPhysRegsUsedFromRegMask (const uint32_t *RegMask)
addPhysRegsUsedFromRegMask - Mark any registers not in RegMask as used.
const BitVector & getUsedPhysRegsMask () const
void freezeReservedRegs (const MachineFunction &)
freezeReservedRegs - Called by the register allocator to freeze the set of reserved registers before allocation begins.
void reserveReg (MCRegister PhysReg, const TargetRegisterInfo *TRI)
reserveReg – Mark a register as reserved so checks like isAllocatable will not suggest using it.
bool reservedRegsFrozen () const
reservedRegsFrozen - Returns true after freezeReservedRegs() was called to ensure the set of reserved registers stays constant.
bool canReserveReg (MCRegister PhysReg) const
canReserveReg - Returns true if PhysReg can be used as a reserved register.
const BitVector & getReservedRegs () const
getReservedRegs - Returns a reference to the frozen set of reserved registers.
bool isReserved (MCRegister PhysReg) const
isReserved - Returns true when PhysReg is a reserved register.
bool isReservedRegUnit (unsigned Unit) const
Returns true when the given register unit is considered reserved.
bool isAllocatable (MCRegister PhysReg) const
isAllocatable - Returns true when PhysReg belongs to an allocatable register class and it hasn't been reserved.
void addLiveIn (MCRegister Reg, Register vreg=Register())
addLiveIn - Add the specified register as a live-in.
livein_iterator livein_begin () const
livein_iterator livein_end () const
bool livein_empty () const
ArrayRef< std::pair< MCRegister, Register > > liveins () const
bool isLiveIn (Register Reg) const
MCRegister getLiveInPhysReg (Register VReg) const
getLiveInPhysReg - If VReg is a live-in virtual register, return the corresponding live-in physical register.
Register getLiveInVirtReg (MCRegister PReg) const
getLiveInVirtReg - If PReg is a live-in physical register, return the corresponding live-in virtual register.
void EmitLiveInCopies (MachineBasicBlock *EntryMBB, const TargetRegisterInfo &TRI, const TargetInstrInfo &TII)
EmitLiveInCopies - Emit copies to initialize livein virtual registers into the given entry block.
LaneBitmask getMaxLaneMaskForVReg (Register Reg) const
Returns a mask covering all bits that can appear in lane masks of subregisters of the virtual register Reg.
Static Public Member Functions
static reg_iterator reg_end ()
static reg_instr_iterator reg_instr_end ()
static reg_bundle_iterator reg_bundle_end ()
static reg_nodbg_iterator reg_nodbg_end ()
static reg_instr_nodbg_iterator reg_instr_nodbg_end ()
static reg_bundle_nodbg_iterator reg_bundle_nodbg_end ()
static def_iterator def_end ()
static def_instr_iterator def_instr_end ()
static def_bundle_iterator def_bundle_end ()
static use_iterator use_end ()
static use_instr_iterator use_instr_end ()
static use_bundle_iterator use_bundle_end ()
static use_nodbg_iterator use_nodbg_end ()
static use_instr_nodbg_iterator use_instr_nodbg_end ()
static use_bundle_nodbg_iterator use_bundle_nodbg_end ()
Friends
template<bool , bool , bool , bool , bool , bool >
class defusechain_iterator
template<bool , bool , bool , bool , bool , bool >
class defusechain_instr_iterator
Detailed Description
MachineRegisterInfo - Keep track of information for virtual and physical registers, including vreg register classes, use/def chains for registers, etc.
Definition at line 51 of file MachineRegisterInfo.h.
Member Typedef Documentation
def_bundle_iterator
using llvm::MachineRegisterInfo::def_bundle_iterator = defusechain_instr_iterator<false, true, false, false, false, true>
def_bundle_iterator/def_bundle_begin/def_bundle_end - Walk all defs of the specified register, stepping by bundle.
Definition at line 434 of file MachineRegisterInfo.h.
def_instr_iterator
using llvm::MachineRegisterInfo::def_instr_iterator = defusechain_instr_iterator<false, true, false, false, true, false>
def_instr_iterator/def_instr_begin/def_instr_end - Walk all defs of the specified register, stepping by MachineInst.
Definition at line 418 of file MachineRegisterInfo.h.
def_iterator
using llvm::MachineRegisterInfo::def_iterator = defusechain_iterator<false, true, false, true, false, false>
def_iterator/def_begin/def_end - Walk all defs of the specified register.
Definition at line 405 of file MachineRegisterInfo.h.
livein_iterator
using llvm::MachineRegisterInfo::livein_iterator = std::vector<std::pair<MCRegister,Register> >::const_iterator
Definition at line 992 of file MachineRegisterInfo.h.
reg_bundle_iterator
using llvm::MachineRegisterInfo::reg_bundle_iterator = defusechain_instr_iterator<true, true, false, false, false, true>
reg_bundle_iterator/reg_bundle_begin/reg_bundle_end - Walk all defs and uses of the specified register, stepping by bundle.
Definition at line 331 of file MachineRegisterInfo.h.
reg_bundle_nodbg_iterator
using llvm::MachineRegisterInfo::reg_bundle_nodbg_iterator = defusechain_instr_iterator<true, true, true, false, false, true>
reg_bundle_nodbg_iterator/reg_bundle_nodbg_begin/reg_bundle_nodbg_end - Walk all defs and uses of the specified register, stepping by bundle, skipping those marked as Debug.
Definition at line 384 of file MachineRegisterInfo.h.
reg_instr_iterator
using llvm::MachineRegisterInfo::reg_instr_iterator = defusechain_instr_iterator<true, true, false, false, true, false>
reg_instr_iterator/reg_instr_begin/reg_instr_end - Walk all defs and uses of the specified register, stepping by MachineInstr.
Definition at line 315 of file MachineRegisterInfo.h.
reg_instr_nodbg_iterator
using llvm::MachineRegisterInfo::reg_instr_nodbg_iterator = defusechain_instr_iterator<true, true, true, false, true, false>
reg_instr_nodbg_iterator/reg_instr_nodbg_begin/reg_instr_nodbg_end - Walk all defs and uses of the specified register, stepping by MachineInstr, skipping those marked as Debug.
Definition at line 367 of file MachineRegisterInfo.h.
reg_iterator
using llvm::MachineRegisterInfo::reg_iterator = defusechain_iterator<true, true, false, true, false, false>
reg_iterator/reg_begin/reg_end - Walk all defs and uses of the specified register.
Definition at line 302 of file MachineRegisterInfo.h.
reg_nodbg_iterator
using llvm::MachineRegisterInfo::reg_nodbg_iterator = defusechain_iterator<true, true, true, true, false, false>
reg_nodbg_iterator/reg_nodbg_begin/reg_nodbg_end - Walk all defs and uses of the specified register, skipping those marked as Debug.
Definition at line 350 of file MachineRegisterInfo.h.
use_bundle_iterator
using llvm::MachineRegisterInfo::use_bundle_iterator = defusechain_instr_iterator<true, false, false, false, false, true>
use_bundle_iterator/use_bundle_begin/use_bundle_end - Walk all uses of the specified register, stepping by bundle.
Definition at line 514 of file MachineRegisterInfo.h.
use_bundle_nodbg_iterator
using llvm::MachineRegisterInfo::use_bundle_nodbg_iterator = defusechain_instr_iterator<true, false, true, false, false, true>
use_bundle_nodbg_iterator/use_bundle_nodbg_begin/use_bundle_nodbg_end - Walk all uses of the specified register, stepping by bundle, skipping those marked as Debug.
Definition at line 573 of file MachineRegisterInfo.h.
use_instr_iterator
using llvm::MachineRegisterInfo::use_instr_iterator = defusechain_instr_iterator<true, false, false, false, true, false>
use_instr_iterator/use_instr_begin/use_instr_end - Walk all uses of the specified register, stepping by MachineInstr.
Definition at line 498 of file MachineRegisterInfo.h.
use_instr_nodbg_iterator
using llvm::MachineRegisterInfo::use_instr_nodbg_iterator = defusechain_instr_iterator<true, false, true, false, true, false>
use_instr_nodbg_iterator/use_instr_nodbg_begin/use_instr_nodbg_end - Walk all uses of the specified register, stepping by MachineInstr, skipping those marked as Debug.
Definition at line 556 of file MachineRegisterInfo.h.
use_iterator
using llvm::MachineRegisterInfo::use_iterator = defusechain_iterator<true, false, false, true, false, false>
use_iterator/use_begin/use_end - Walk all uses of the specified register.
Definition at line 485 of file MachineRegisterInfo.h.
use_nodbg_iterator
using llvm::MachineRegisterInfo::use_nodbg_iterator = defusechain_iterator<true, false, true, true, false, false>
use_nodbg_iterator/use_nodbg_begin/use_nodbg_end - Walk all uses of the specified register, skipping those marked as Debug.
Definition at line 539 of file MachineRegisterInfo.h.
Constructor & Destructor Documentation
MachineRegisterInfo() [1/2]
MachineRegisterInfo::MachineRegisterInfo (MachineFunction * MF) explicit
Definition at line 43 of file MachineRegisterInfo.cpp.
References llvm::MCRegisterInfo::getNumRegs(), getTargetRegisterInfo(), and llvm::BitVector::resize().
MachineRegisterInfo() [2/2]
llvm::MachineRegisterInfo::MachineRegisterInfo (const MachineRegisterInfo &) delete
Member Function Documentation
addDelegate()
void llvm::MachineRegisterInfo::addDelegate (Delegate * delegate) inline
Definition at line 168 of file MachineRegisterInfo.h.
References assert(), llvm::SmallPtrSetImpl< PtrType >::count(), and llvm::SmallPtrSetImpl< PtrType >::insert().
addLiveIn()
void llvm::MachineRegisterInfo::addLiveIn (MCRegister Reg, Register vreg = Register()) inline
addLiveIn - Add the specified register as a live-in.
Note that it is an error to add the same register to the same set more than once.
Definition at line 985 of file MachineRegisterInfo.h.
Referenced by llvm::MachineFunction::addLiveIn(), addLiveIn(), allocateHSAUserSGPRs(), buildGitPtr(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::MIRParserImpl::parseRegisterInfo(), unpack64(), unpackF64OnRV32DSoftABI(), and unpackFromRegLoc().
addPhysRegsUsedFromRegMask()
void llvm::MachineRegisterInfo::addPhysRegsUsedFromRegMask (const uint32_t * RegMask) inline
addPhysRegsUsedFromRegMask - Mark any registers not in RegMask as used.
This corresponds to the bit mask attached to register mask operands.
Definition at line 895 of file MachineRegisterInfo.h.
Referenced by llvm::MIRParserImpl::setupRegisterInfo().
addRegAllocationHint()
void llvm::MachineRegisterInfo::addRegAllocationHint (Register VReg, Register PrefReg) inline
addRegAllocationHint - Add a register allocation hint to the hints vector for VReg.
Definition at line 801 of file MachineRegisterInfo.h.
References assert(), and llvm::Register::isVirtual().
addRegOperandToUseList()
void MachineRegisterInfo::addRegOperandToUseList (MachineOperand * MO)
Add MO to the linked list of operands for its register.
Definition at line 265 of file MachineRegisterInfo.cpp.
References assert(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), and llvm::Last.
Referenced by llvm::MachineInstr::addOperand(), llvm::MachineOperand::ChangeToRegister(), llvm::SIInstrInfo::moveFlatAddrToVGPR(), llvm::MachineOperand::setIsDef(), and llvm::MachineOperand::setReg().
canReserveReg()
bool llvm::MachineRegisterInfo::canReserveReg (MCRegister PhysReg) const inline
canReserveReg - Returns true if PhysReg can be used as a reserved register.
Any register can be reserved before freezeReservedRegs() is called.
Definition at line 938 of file MachineRegisterInfo.h.
References reservedRegsFrozen().
Referenced by llvm::MipsRegisterInfo::canRealignStack(), llvm::M68kRegisterInfo::canRealignStack(), llvm::X86RegisterInfo::canRealignStack(), and llvm::ARMBaseRegisterInfo::canRealignStack().
clearKillFlags()
void MachineRegisterInfo::clearKillFlags (Register Reg) const
clearKillFlags - Iterate over all the uses of the given register and clear the kill flag from the MachineOperand.
This function is used by optimization passes which extend register lifetimes and need only preserve conservative kill flag information.
Definition at line 435 of file MachineRegisterInfo.cpp.
References use_operands().
Referenced by emitIndirectDst(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), genIndexedMultiply(), hoistAndMergeSGPRInits(), INITIALIZE_PASS(), insertPHI(), llvm::AArch64InstrInfo::insertSelect(), llvm::SIInstrInfo::moveToVALU(), llvm::HexagonInstrInfo::PredicateInstruction(), and llvm::SelectionDAGISel::runOnMachineFunction().
clearSimpleHint()
void llvm::MachineRegisterInfo::clearSimpleHint (Register VReg) inline
Definition at line 812 of file MachineRegisterInfo.h.
References assert(), and llvm::IndexedMap< T, ToIndexT >::clear().
clearVirtRegs()
void MachineRegisterInfo::clearVirtRegs ()
clearVirtRegs - Remove all virtual registers (after physreg assignment).
Definition at line 198 of file MachineRegisterInfo.cpp.
References abort(), llvm::numbers::e, llvm::errs(), getNumVirtRegs(), getTargetRegisterInfo(), i, I, llvm::Register::index2VirtReg(), MI, llvm::printReg(), reg_instructions(), and verifyUseList().
Referenced by llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), and llvm::scavengeFrameVirtualRegs().
clearVirtRegTypes()
void MachineRegisterInfo::clearVirtRegTypes ()
Remove all types associated to virtual registers (after instruction selection and constraining of all generic virtual registers).
Definition at line 195 of file MachineRegisterInfo.cpp.
References llvm::IndexedMap< T, ToIndexT >::clear().
Referenced by llvm::InstructionSelect::runOnMachineFunction().
cloneVirtualRegister()
Register MachineRegisterInfo::cloneVirtualRegister (Register VReg, StringRef Name = "")
Create and return a new virtual register in the function with the same attributes as the given register.
Definition at line 170 of file MachineRegisterInfo.cpp.
References createIncompleteVirtualRegister(), getType(), noteCloneVirtualRegister(), and setType().
Referenced by applyAdjustICmpImmAndPred(), llvm::CombinerHelper::applyCombineConcatVectors(), llvm::CombinerHelper::applyCombineExtendingLoads(), llvm::CombinerHelper::applyCombineShuffleVector(), applyFoldGlobalOffset(), llvm::CallLowering::IncomingValueHandler::buildExtensionHint(), llvm::LiveRangeEdit::createFrom(), llvm::CallLowering::lowerCall(), llvm::CombinerHelper::matchLoadOrCombine(), llvm::LiveIntervals::splitSeparateComponents(), and tryToSimplifyUADDO().
constrainRegAttrs()
bool MachineRegisterInfo::constrainRegAttrs (Register Reg, Register ConstrainingReg, unsigned MinNumRegs = 0)
Constrain the register class or the register bank of the virtual register Reg (and low-level type) to be a common subclass or a common bank of both registers provided respectively (and a common low-level type).
Do nothing if any of the attributes (classes, banks, or low-level types) of the registers are deemed incompatible, or if the resulting register will have a class smaller than before and of size less than MinNumRegs. Return true if such register attributes exist, false otherwise.
Note
Use this method instead of constrainRegClass and RegisterBankInfo::constrainGenericRegister everywhere but SelectionDAG ISel / FastISel and GlobalISel's InstructionSelect pass respectively.
Definition at line 91 of file MachineRegisterInfo.cpp.
References constrainRegClass(), getRegClassOrRegBank(), getType(), llvm::LLT::isValid(), setRegClassOrRegBank(), and setType().
Referenced by llvm::CombinerHelper::replaceRegWith().
constrainRegClass()
const TargetRegisterClass * MachineRegisterInfo::constrainRegClass (Register Reg, const TargetRegisterClass * RC, unsigned MinNumRegs = 0)
constrainRegClass - Constrain the register class of the specified virtual register to be a common subclass of RC and the current register class, but only if the new class has at least MinNumRegs registers.
Return the new register class, or NULL if no such class exists. This should only be used when the constraint is known to be trivial, like GR32 -> GR32_NOSP. Beware of increasing register pressure.
Note
Assumes that the register has a register class assigned. Use RegisterBankInfo::constrainGenericRegister in GlobalISel's InstructionSelect pass and constrainRegAttrs in every other pass, including non-select passes of GlobalISel, instead.
Definition at line 83 of file MachineRegisterInfo.cpp.
References constrainRegClass(), and getRegClass().
Referenced by llvm::MachineBasicBlock::addLiveIn(), AdjustBaseAndOffset(), llvm::X86InstrInfo::classifyLEAReg(), llvm::RegisterBankInfo::constrainGenericRegister(), llvm::FastISel::constrainOperandRegClass(), constrainRegAttrs(), llvm::X86InstrInfo::convertToThreeAddress(), createPostIncLoadStore(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SIInstrInfo::foldMemoryOperandImpl(), genFusedMultiply(), genIndexedMultiply(), genMaddR(), llvm::AArch64InstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::SIInstrInfo::moveToVALU(), llvm::RISCVInstrInfo::optimizeSelect(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::PeelSingleBlockLoop(), llvm::TargetInstrInfo::reassociateOps(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::rewriteT2FrameIndex(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::TailDuplicator::tailDuplicateAndUpdate(), UpdateOperandRegClass(), and updateOperandRegConstraints().
createGenericVirtualRegister()
Register MachineRegisterInfo::createGenericVirtualRegister (LLT Ty, StringRef Name = "")
Create and return a new generic virtual register with low-level type Ty.
Definition at line 185 of file MachineRegisterInfo.cpp.
References createIncompleteVirtualRegister(), noteNewVirtualRegister(), and setType().
Referenced by allocateHSAUserSGPRs(), AMDGPUCombinerHelper::applyFoldableFneg(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), llvm::LegalizerHelper::bitcastDst(), llvm::buildBoolRegister(), llvm::MachineIRBuilder::buildMaskLowPtrBits(), convertPtrToInt(), createNewIdReg(), createTypeVReg(), llvm::RegisterBankInfo::OperandsMapper::createVRegs(), llvm::CallLowering::ValueHandler::extendRegister(), extractParts(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::generateImageSizeQueryInst(), llvm::AMDGPULegalizerInfo::getImplicitArgPtr(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), llvm::SPIRVGlobalRegistry::getOrCreateUndef(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::CallLowering::handleAssignments(), llvm::insertAssignInstr(), llvm::CallLowering::insertSRetIncomingArgument(), llvm::AMDGPULegalizerInfo::legalizeBVHIntrinsic(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeMul(), llvm::AMDGPULegalizerInfo::legalizeSignedDIV_REM(), llvm::AMDGPULegalizerInfo::legalizeTrapHsaQueuePtr(), llvm::AMDGPULegalizerInfo::legalizeWorkitemIDIntrinsic(), llvm::LegalizerHelper::lower(), llvm::MipsCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::LegalizerHelper::lowerLoad(), llvm::LegalizerHelper::lowerMergeValues(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), llvm::MachineIRBuilder::materializePtrAdd(), mergeVectorRegsToResultRegs(), llvm::LegalizerHelper::moreElementsVectorDst(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarAddSub(), llvm::LegalizerHelper::narrowScalarDst(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarShift(), llvm::LegalizerHelper::narrowScalarShiftByConstant(), llvm::AMDGPUCallLowering::passSpecialInputs(), llvm::LegalizerHelper::reduceLoadStoreWidth(), llvm::AMDGPURegisterBankInfo::split64BitValueForMapping(), llvm::LegalizerHelper::widenScalar(), and llvm::LegalizerHelper::widenScalarDst().
createIncompleteVirtualRegister()
Register MachineRegisterInfo::createIncompleteVirtualRegister (StringRef Name = "")
Creates a new virtual register that has no register class, register bank or size assigned yet.
This is only allowed to be used temporarily while constructing machine instructions. Most operations are undefined on an incomplete register until one of setRegClass(), setRegBank() or setSize() has been called on it.
Definition at line 145 of file MachineRegisterInfo.cpp.
References getNumVirtRegs(), llvm::Register::index2VirtReg(), and insertVRegByName().
Referenced by cloneVirtualRegister(), createGenericVirtualRegister(), createVirtualRegister(), llvm::PerFunctionMIParsingState::getVRegInfo(), and llvm::PerFunctionMIParsingState::getVRegInfoNamed().
createVirtualRegister()
Register MachineRegisterInfo::createVirtualRegister (const TargetRegisterClass * RegClass, StringRef Name = "")
createVirtualRegister - Create and return a new virtual register in the function with the specified register class.
Definition at line 157 of file MachineRegisterInfo.cpp.
References assert(), createIncompleteVirtualRegister(), llvm::TargetRegisterClass::isAllocatable(), and noteNewVirtualRegister().
Referenced by llvm::SITargetLowering::AddIMGInit(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::addLiveIn(), addLiveIn(), llvm::RISCVRegisterInfo::adjustReg(), llvm::buildBuiltinVariableLoad(), llvm::SPIRVGlobalRegistry::buildConstantSampler(), llvm::buildEnqueueKernel(), llvm::SIInstrInfo::buildExtractSubReg(), llvm::AMDGPURegisterBankInfo::buildReadFirstLane(), buildRSRC(), llvm::AMDGPURegisterBankInfo::buildVCopy(), llvm::X86InstrInfo::classifyLEAReg(), llvm::constrainRegToClass(), llvm::SIInstrInfo::convertNonUniformIfRegion(), llvm::SIInstrInfo::convertNonUniformLoopRegion(), createBBSelectReg(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), createLaneMaskReg(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::FunctionLoweringInfo::CreateReg(), llvm::FastISel::createResultReg(), llvm::HexagonInstrInfo::createVR(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::WebAssemblyFrameLowering::emitEpilogue(), emitFrameOffsetAdj(), emitFROUND(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), emitIndirectDst(), emitIndirectSrc(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), emitLoadM0FromVGPRLoop(), emitLoadSRsrcFromVGPRLoop(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), emitQuietFCMP(), emitReadCycleWidePseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::VETargetLowering::emitSjLjDispatchBlock(), emitThumbRegPlusImmInReg(), emitVFCVT_RM_MASK(), emitVFROUND_NOEXCEPT_MASK(), emitXBegin(), llvm::SIInstrInfo::enforceOperandRCAlignment(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::SIInstrInfo::expandMovDPP64(), extractRsrcPtr(), llvm::ARMBaseInstrInfo::FoldImmediate(), foldVGPRCopyIntoRegSequence(), forceReg(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::generateSampleImageInst(), genNeg(), genSubAdd2SubSub(), genTPEntry(), genTPLoopBody(), llvm::SIInstrInfo::getAddNoCarry(), llvm::FunctionLoweringInfo::getCatchPadExceptionPointerVReg(), llvm::MipsFunctionInfo::getGlobalBaseReg(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::M68kInstrInfo::getGlobalBaseReg(), llvm::X86InstrInfo::getGlobalBaseReg(), getIndirectSGPRIdx(), llvm::SwiftErrorValueTracking::getOrCreateVReg(), llvm::SwiftErrorValueTracking::getOrCreateVRegDefAt(), getRegistersForValue(), llvm::RISCVInstrInfo::getVLENFactoredAmount(), llvm::MipsFunctionInfo::initGlobalBaseReg(), INITIALIZE_PASS(), llvm::SIInstrInfo::insertEQ(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), llvm::insertMultibyteShift(), llvm::SIInstrInfo::insertNE(), InsertNewDef(), insertPHI(), llvm::SystemZInstrInfo::insertSelect(), llvm::SIInstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::SIInstrInfo::insertVectorSelect(), llvm::SIInstrInfo::legalizeGenericOperand(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::SIInstrInfo::legalizeOperandsVOP3(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), loadM0FromVGPR(), llvm::X86InstrInfo::loadStoreTileReg(), llvm::SPIRV::lowerBuiltin(), llvm::SPIRVCallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResults(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), LowerFPToInt(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), llvm::PPCRegisterInfo::lowerWACCRestore(), llvm::PPCRegisterInfo::lowerWACCSpilling(), llvm::RISCVRegisterInfo::materializeFrameBaseRegister(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::SIRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), maybeRewriteToDrop(), moveAndTeeForMultiUse(), moveForSingleUse(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::SIInstrInfo::moveToVALU(), llvm::CSKYInstrInfo::movImm(), llvm::PeelSingleBlockLoop(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::VETargetLowering::prepareMBB(), llvm::VETargetLowering::prepareSymbol(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), llvm::TargetInstrInfo::reassociateOps(), rematerializeCheapDef(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), selectCopy(), unpack64(), unpackF64OnRV32DSoftABI(), and unpackFromRegLoc().
def_begin()
def_iterator llvm::MachineRegisterInfo::def_begin (Register RegNo) const inline
Definition at line 406 of file MachineRegisterInfo.h.
Referenced by llvm::DeadLaneDetector::computeSubRegisterLaneBitInfo(), def_empty(), def_operands(), getOneDef(), getTileShape(), isKilled(), isPhysRegModified(), MustSaveLR(), and llvm::MachineFunction::salvageCopySSAImpl().
def_bundle_begin()
def_bundle_iterator llvm::MachineRegisterInfo::def_bundle_begin (Register RegNo) const inline
Definition at line 435 of file MachineRegisterInfo.h.
Referenced by def_bundles().
def_bundle_end()
static def_bundle_iterator llvm::MachineRegisterInfo::def_bundle_end () inline static
Definition at line 438 of file MachineRegisterInfo.h.
Referenced by def_bundles().
def_bundles()
iterator_range<def_bundle_iterator> llvm::MachineRegisterInfo::def_bundles (Register Reg) const inline
Definition at line 442 of file MachineRegisterInfo.h.
References def_bundle_begin(), def_bundle_end(), and llvm::make_range().
def_empty()
bool llvm::MachineRegisterInfo::def_empty (Register RegNo) const inline
def_empty - Return true if there are no instructions defining the specified register (it may be live-in).
Definition at line 448 of file MachineRegisterInfo.h.
References def_begin(), and def_end().
Referenced by getUniqueVRegDef(), isConstantPhysReg(), isSSA(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::MachineOperand::print(), and llvm::InstructionSelect::runOnMachineFunction().
def_end()
static def_iterator llvm::MachineRegisterInfo::def_end () inline static
Definition at line 409 of file MachineRegisterInfo.h.
Referenced by def_empty(), def_operands(), getOneDef(), isKilled(), isPhysRegModified(), MustSaveLR(), and scavengeVReg().
def_instr_begin()
def_instr_iterator llvm::MachineRegisterInfo::def_instr_begin (Register RegNo) const inline
Definition at line 419 of file MachineRegisterInfo.h.
Referenced by def_instructions(), llvm::InstrEmitter::EmitDbgInstrRef(), llvm::MachineFunction::finalizeDebugInstrRefs(), getUniqueVRegDef(), getVRegDef(), isDefBetween(), regIsPICBase(), and llvm::InstructionSelect::runOnMachineFunction().
def_instr_end()
static def_instr_iterator llvm::MachineRegisterInfo::def_instr_end () inline static
Definition at line 422 of file MachineRegisterInfo.h.
Referenced by def_instructions(), getUniqueVRegDef(), getVRegDef(), isDefBetween(), and regIsPICBase().
def_instructions()
iterator_range<def_instr_iterator> llvm::MachineRegisterInfo::def_instructions (Register Reg) const inline
Definition at line 427 of file MachineRegisterInfo.h.
References def_instr_begin(), def_instr_end(), and llvm::make_range().
Referenced by llvm::findPHICopyInsertPoint(), llvm::SystemZRegisterInfo::getRegAllocationHints(), getSingleDef(), hasArgumentDef(), hoistAndMergeSGPRInits(), isImplicitlyDefined(), and llvm::stableHashValue().
def_operands()
iterator_range<def_iterator> llvm::MachineRegisterInfo::def_operands (Register Reg) const inline
Definition at line 411 of file MachineRegisterInfo.h.
References def_begin(), def_end(), and llvm::make_range().
Referenced by llvm::LiveInterval::computeSubRangeUndefs(), llvm::LiveIntervalCalc::createDeadDefs(), hasOneDef(), hasTiedDef(), and scavengeVReg().
disableCalleeSavedRegister()
void MachineRegisterInfo::disableCalleeSavedRegister (MCRegister Reg)
Disables the register from the list of CSRs.
I.e. the register will not appear as part of the CSR mask.
See also
UpdatedCalleeSavedRegs.
Definition at line 602 of file MachineRegisterInfo.cpp.
References assert(), llvm::erase_value(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), getTargetRegisterInfo(), I, llvm::MCRegAliasIterator::isValid(), and TRI.
dumpUses()
LLVM_DUMP_METHOD void MachineRegisterInfo::dumpUses (Register RegNo) const
Definition at line 505 of file MachineRegisterInfo.cpp.
References I, and use_instructions().
EmitLiveInCopies()
void MachineRegisterInfo::EmitLiveInCopies (MachineBasicBlock * EntryMBB, const TargetRegisterInfo & TRI, const TargetInstrInfo & TII)
EmitLiveInCopies - Emit copies to initialize livein virtual registers into the given entry block.
Definition at line 468 of file MachineRegisterInfo.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::numbers::e, i, TII, and use_nodbg_empty().
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
freezeReservedRegs()
void MachineRegisterInfo::freezeReservedRegs (const MachineFunction & MF)
freezeReservedRegs - Called by the register allocator to freeze the set of reserved registers before allocation begins.
Definition at line 511 of file MachineRegisterInfo.cpp.
References assert(), llvm::TargetRegisterInfo::getReservedRegs(), getTargetRegisterInfo(), and llvm::BitVector::size().
Referenced by createFrameHelperMachineFunction(), llvm::TargetLoweringBase::finalizeLowering(), llvm::RegAllocBase::init(), llvm::MIRParserImpl::initializeMachineFunction(), and llvm::SIFrameLowering::processFunctionBeforeFrameIndicesReplaced().
getCalleeSavedRegs()
const MCPhysReg * MachineRegisterInfo::getCalleeSavedRegs () const
Returns list of callee saved registers.
The function returns the updated CSR list (after taking into account registers that are disabled from the CSR list).
Definition at line 625 of file MachineRegisterInfo.cpp.
References llvm::TargetRegisterInfo::getCalleeSavedRegs(), and getTargetRegisterInfo().
Referenced by addCalleeSavedRegs(), llvm::MIRPrinter::convert(), llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::CSKYFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), findScratchNonCalleeSaveRegister(), llvm::MachineFrameInfo::getPristineRegs(), isACalleeSavedRegister(), llvm::RISCVRegisterInfo::needsFrameBaseReg(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::X86MachineFunctionInfo::setRestoreBasePointer(), llvm::SIMachineFunctionInfo::splitWWMSpillRegisters(), llvm::CriticalAntiDepBreaker::StartBlock(), and llvm::AggressiveAntiDepBreaker::StartBlock().
getLiveInPhysReg()
MCRegister MachineRegisterInfo::getLiveInPhysReg (Register VReg) const
getLiveInPhysReg - If VReg is a live-in virtual register, return the corresponding live-in physical register.
Definition at line 449 of file MachineRegisterInfo.cpp.
References liveins().
Referenced by llvm::TargetLowering::parametersInCSRMatch().
getLiveInVirtReg()
Register MachineRegisterInfo::getLiveInVirtReg (MCRegister PReg) const
getLiveInVirtReg - If PReg is a live-in physical register, return the corresponding live-in virtual register.
getLiveInVirtReg - If PReg is a live-in physical register, return the corresponding live-in physical register.
Definition at line 458 of file MachineRegisterInfo.cpp.
References liveins().
Referenced by llvm::MachineFunction::addLiveIn(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), and llvm::getFunctionLiveInPhysReg().
getMaxLaneMaskForVReg()
LaneBitmask MachineRegisterInfo::getMaxLaneMaskForVReg (Register Reg) const
Returns a mask covering all bits that can appear in lane masks of subregisters of the virtual register Reg.
Definition at line 497 of file MachineRegisterInfo.cpp.
References assert(), llvm::TargetRegisterClass::getLaneMask(), and getRegClass().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::LiveRangeEdit::allUsesAvailableAt(), llvm::LiveIntervalCalc::calculate(), llvm::LiveInterval::computeSubRangeUndefs(), llvm::SIRegisterInfo::findReachingDef(), getDefRegMask(), getInstReadLaneMask(), getLanesWithProperty(), llvm::getLiveLaneMask(), llvm::getLiveRegMap(), getUsedRegMask(), llvm::DeadLaneDetector::transferDefinedLanes(), llvm::LiveIntervals::HMEditor::updateAllRanges(), and llvm::LiveInterval::verify().
getNumVirtRegs()
unsigned llvm::MachineRegisterInfo::getNumVirtRegs () const inline
getNumVirtRegs - Return the number of virtual registers created.
Definition at line 784 of file MachineRegisterInfo.h.
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::LiveVariables::addNewBlock(), attemptDebugCopyProp(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::VirtRegAuxInfo::calculateSpillWeightsAndHints(), clearVirtRegs(), llvm::DeadLaneDetector::computeSubRegisterLaneBitInfo(), llvm::MIRPrinter::convert(), createIncompleteVirtualRegister(), llvm::DeadLaneDetector::DeadLaneDetector(), llvm::SITargetLowering::finalizeLowering(), llvm::getLiveRegMap(), llvm::getLiveRegs(), llvm::VirtRegMap::grow(), llvm::LiveRegSet::init(), llvm::RegPressureTracker::init(), llvm::ScheduleDAGMILive::initRegPressure(), llvm::WebAssemblyFunctionInfo::initWARegs(), isSSA(), llvm::SPIRV::lowerBuiltinType(), llvm::VirtRegMap::print(), llvm::print(), llvm::LiveIntervals::print(), llvm::InstructionSelect::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::scavengeFrameVirtualRegs(), scavengeFrameVirtualRegsInBlock(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SIMachineFunctionInfo::usesAGPRs(), and verifyUseLists().
getOneDef()
MachineOperand* llvm::MachineRegisterInfo::getOneDef (Register Reg) const inline
Returns the defining operand if there is exactly one operand defining the specified register, otherwise nullptr.
Definition at line 472 of file MachineRegisterInfo.h.
References def_begin(), and def_end().
Referenced by isSSA(), and tryToSimplifyUADDO().
getPressureSets()
PSetIterator llvm::MachineRegisterInfo::getPressureSets (Register RegUnit) const inline
Get an iterator over the pressure sets affected by the given physical or virtual register.
If RegUnit is physical, it must be a register unit (from MCRegUnitIterator).
Definition at line 1269 of file MachineRegisterInfo.h.
Referenced by llvm::PressureDiff::addPressureChange(), decreaseSetPressure(), llvm::GCNRegPressure::inc(), llvm::RegPressureTracker::increaseRegPressure(), and increaseSetPressure().
getRegAllocationHint()
std::pair<Register, Register> llvm::MachineRegisterInfo::getRegAllocationHint (Register VReg) const inline
getRegAllocationHint - Return the register allocation hint for the specified virtual register.
If there are many hints, this returns the one with the greatest weight.
Definition at line 822 of file MachineRegisterInfo.h.
References assert(), llvm::Register::id(), llvm::Register::isVirtual(), Register, and llvm::IndexedMap< T, ToIndexT >::size().
Referenced by llvm::ARMBaseRegisterInfo::getRegAllocationHints(), getSimpleHint(), llvm::VirtRegMap::hasKnownPreference(), and llvm::ARMBaseRegisterInfo::updateRegAllocHint().
getRegAllocationHints()
const std::pair<Register, SmallVector<Register, 4> >& llvm::MachineRegisterInfo::getRegAllocationHints (Register VReg) const inline
getRegAllocationHints - Return a reference to the vector of all register allocation hints for VReg.
Definition at line 841 of file MachineRegisterInfo.h.
References assert(), and llvm::Register::isVirtual().
Referenced by llvm::TargetRegisterInfo::getRegAllocationHints().
getRegBankOrNull()
const RegisterBank* llvm::MachineRegisterInfo::getRegBankOrNull (Register Reg) const inline
Return the register bank of Reg, or null if Reg has not been assigned a register bank or has been assigned a register class.
Note
It is possible to get the register bank from the register class via RegisterBankInfo::getRegBankFromRegClass.
Definition at line 687 of file MachineRegisterInfo.h.
References llvm::PointerUnion< PTs >::dyn_cast().
Referenced by llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingMAD_64_32(), constrainRegToBank(), fixupPHIOpBanks(), and llvm::printRegClassOrBank().
getRegClass()
const TargetRegisterClass* llvm::MachineRegisterInfo::getRegClass (Register Reg) const inline
Return the register class of the specified virtual register.
This shouldn't be used directly unless Reg has a register class.
See also
getRegClassOrNull when this might happen.
Definition at line 661 of file MachineRegisterInfo.h.
References assert().
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), llvm::MachineFunction::addLiveIn(), llvm::RegAllocBase::allocatePhysRegs(), llvm::VirtRegMap::assignVirt2StackSlot(), llvm::LiveRangeEdit::calculateRegClassAndHint(), canFoldCopy(), canFoldIntoCSel(), llvm::AArch64InstrInfo::canInsertSelect(), llvm::SystemZInstrInfo::canInsertSelect(), llvm::SIInstrInfo::canInsertSelect(), llvm::X86InstrInfo::canInsertSelect(), llvm::PPCInstrInfo::canInsertSelect(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), constrainRegClass(), convertImplicitDefToConstZero(), llvm::VirtRegAuxInfo::copyHint(), llvm::WebAssemblyInstrInfo::copyPhysReg(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::AllocationOrder::create(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::HexagonFrameLowering::determineCalleeSaves(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), emitIndirectDst(), emitIndirectSrc(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), emitLoadSRsrcFromVGPRLoop(), emitXBegin(), llvm::RegAllocBase::enqueue(), llvm::HexagonEvaluator::evaluate(), llvm::HexagonBlockRanges::expandToSubRegs(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SIInstrInfo::FoldImmediate(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::SIInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), foldVGPRCopyIntoRegSequence(), genSubAdd2SubSub(), llvm::BitTracker::MachineEvaluator::getCell(), getCopyRegClasses(), llvm::ScheduleDAGInstrs::getLaneMaskForMO(), getMaxLaneMaskForVReg(), llvm::PPCInstrInfo::getOperandLatency(), llvm::SIInstrInfo::getOpRegClass(), llvm::RegAllocEvictionAdvisor::getOrderLimit(), getRC32(), llvm::PPCRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), llvm::SIRegisterInfo::getRegClassForReg(), llvm::TargetRegisterInfo::getRegSizeInBits(), getRegTy(), llvm::WebAssemblyAsmPrinter::getRegType(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::MachineSSAUpdater::Initialize(), INITIALIZE_PASS(), insertPHI(), llvm::SystemZInstrInfo::insertSelect(), llvm::SIInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::SIInstrInfo::insertVectorSelect(), IsAGPROperand(), isCrossCopy(), isFPR64(), llvm::SIInstrInfo::isLegalRegOperand(), isNonFoldablePartialRegisterLoad(), llvm::isOfRegClass(), llvm::HexagonMCInstrInfo::isPredReg(), llvm::SIRegisterInfo::isSGPRReg(), isTileDef(), isTileRegDef(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOperandsFLAT(), llvm::SIInstrInfo::legalizeOperandsSMRD(), llvm::SIInstrInfo::legalizeOperandsVOP3(), llvm::WebAssemblyMCInstLower::lower(), LowerCallResults(), LowerFPToInt(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::HexagonEvaluator::mask(), matchAliasCondition(), llvm::SIInstrInfo::materializeImmediate(), maybeRewriteToDrop(), moveAndTeeForMultiUse(), moveForSingleUse(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::SIInstrInfo::moveToVALU(), optimizeCall(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::RISCVInstrInfo::optimizeSelect(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::PeelSingleBlockLoop(), llvm::VirtRegMap::print(), PrintNodeInfo(), llvm::printRegClassOrBank(), propagateLocalCopies(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), recomputeRegClass(), rematerializeCheapDef(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), scavengeVReg(), llvm::CoalescerPair::setRegisters(), shouldTrackSubRegLiveness(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::DeadLaneDetector::transferUsedLanes(), tryChangeVGPRtoSGPRinCopy(), unstackifyVRegsUsedInSplitBB(), UpdateOperandRegClass(), llvm::SIInstrInfo::usesConstantBus(), llvm::RISCVInstrInfo::verifyInstruction(), and llvm::SIInstrInfo::verifyInstruction().
getRegClassOrNull()
const TargetRegisterClass* llvm::MachineRegisterInfo::getRegClassOrNull (Register Reg) const inline
Return the register class of Reg, or null if Reg has not been assigned a register class yet.
Note
A null register class can only happen when these two conditions are met:
Generic virtual registers are created.
The machine function has not completely been through the instruction selection process. None of this condition is possible without GlobalISel for now. In other words, if GlobalISel is not used or if the query happens after the select pass, using getRegClass is safe.
Definition at line 678 of file MachineRegisterInfo.h.
References llvm::PointerUnion< PTs >::dyn_cast().
Referenced by llvm::constrainOperandRegClass(), llvm::SITargetLowering::finalizeLowering(), llvm::AArch64RegisterBankInfo::getInstrMapping(), getRegClass(), llvm::insertAssignInstr(), llvm::SPIRVInstrInfo::isTypeDeclInstr(), IsWritingToVCCR(), llvm::GenericUniformityAnalysisImpl< ContextT >::markDefsDivergent(), llvm::printRegClassOrBank(), propagateLocalCopies(), propagateSPIRVType(), llvm::InstructionSelect::runOnMachineFunction(), and llvm::SIMachineFunctionInfo::usesAGPRs().
getRegClassOrRegBank()
const RegClassOrRegBank& llvm::MachineRegisterInfo::getRegClassOrRegBank (Register Reg) const inline
Return the register bank or register class of Reg.
Note
Before the register bank gets assigned (i.e., before the RegBankSelect pass) Reg may not have either.
Definition at line 695 of file MachineRegisterInfo.h.
Referenced by llvm::GISelInstProfileBuilder::addNodeIDReg(), llvm::CombinerHelper::applyCombineUnmergeMergeToPlainValues(), llvm::canReplaceReg(), llvm::RegisterBankInfo::constrainGenericRegister(), constrainRegAttrs(), llvm::SIRegisterInfo::getConstrainedRegClassForOperand(), llvm::RegisterBankInfo::getRegBank(), and selectDebugInstr().
getReservedRegs()
const BitVector& llvm::MachineRegisterInfo::getReservedRegs () const inline
getReservedRegs - Returns a reference to the frozen set of reserved registers.
This method should always be preferred to calling TRI::getReservedRegs() when possible.
Definition at line 945 of file MachineRegisterInfo.h.
References assert(), and reservedRegsFrozen().
Referenced by llvm::TargetRegisterInfo::getAllocatableSet(), isReserved(), and llvm::RegisterClassInfo::runOnMachineFunction().
getSimpleHint()
Register llvm::MachineRegisterInfo::getSimpleHint (Register VReg) const inline
getSimpleHint - same as getRegAllocationHint except it will only return a target independent hint.
Definition at line 832 of file MachineRegisterInfo.h.
References assert(), getRegAllocationHint(), llvm::Register::isVirtual(), and Register.
Referenced by llvm::MIRPrinter::convert(), and llvm::VirtRegMap::hasPreferredPhys().
getTargetRegisterInfo()
const TargetRegisterInfo* llvm::MachineRegisterInfo::getTargetRegisterInfo () const inline
Definition at line 156 of file MachineRegisterInfo.h.
References llvm::TargetSubtargetInfo::getRegisterInfo(), and llvm::MachineFunction::getSubtarget().
Referenced by llvm::addLiveIns(), llvm::LiveRangeEdit::allUsesAvailableAt(), llvm::LiveIntervalCalc::calculate(), clearVirtRegs(), llvm::computeLiveIns(), llvm::LiveInterval::computeSubRangeUndefs(), constrainRegClass(), llvm::WebAssemblyInstrInfo::copyPhysReg(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), disableCalleeSavedRegister(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::execMayBeModifiedBeforeAnyUse(), llvm::execMayBeModifiedBeforeUse(), llvm::PeelingModuloScheduleExpander::filterInstructions(), findSurvivorBackwards(), findUseBetween(), freezeReservedRegs(), getCalleeSavedRegs(), getDefRegMask(), llvm::RegisterBankInfo::getRegBankFromConstraints(), getUsedRegMask(), llvm::LiveRegSet::init(), llvm::X86InstrInfo::insertSelect(), isAllocatable(), isArgumentRegister(), isConstantPhysReg(), isCrossCopy(), isFixedRegister(), isGeneralPurposeRegister(), llvm::isOfRegClass(), isPhysRegModified(), isPhysRegUsed(), isReservedRegUnit(), llvm::GCNUpwardRPTracker::isValid(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), MachineRegisterInfo(), llvm::GenericUniformityAnalysisImpl< ContextT >::markDefsDivergent(), llvm::GenericSSAContext< MachineFunction >::print(), llvm::MIPrinter::print(), llvm::print(), PrintNodeInfo(), llvm::recomputeLivenessFlags(), recomputeRegClass(), replaceRegWith(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), llvm::MachineFunction::salvageCopySSAImpl(), scavengeFrameVirtualRegsInBlock(), scavengeVReg(), llvm::ARMBaseRegisterInfo::shouldCoalesce(), spillVGPRtoAGPR(), llvm::tryFoldSPUpdateIntoPushPop(), updateDbgUsersToReg(), updateOperandRegConstraints(), llvm::SIInstrInfo::verifyInstruction(), verifyUseList(), and verifyUseLists().
getType()
LLT llvm::MachineRegisterInfo::getType (Register Reg) const inline
Get the low-level type of Reg or LLT{} if Reg is not a generic (target independent) virtual register.
Definition at line 759 of file MachineRegisterInfo.h.
Referenced by llvm::GISelInstProfileBuilder::addNodeIDReg(), llvm::CombinerHelper::applyAshShlToSextInreg(), llvm::CombinerHelper::applyCombineAddP2IToPtrAdd(), llvm::CombinerHelper::applyCombineExtendingLoads(), llvm::CombinerHelper::applyCombineInsertVecElts(), llvm::CombinerHelper::applyCombineMulByNegativeOne(), llvm::CombinerHelper::applyCombineMulToShl(), llvm::CombinerHelper::applyCombineShiftToUnmerge(), llvm::CombinerHelper::applyCombineShlOfExtend(), llvm::CombinerHelper::applyCombineTruncOfExt(), llvm::CombinerHelper::applyCombineTruncOfShift(), llvm::CombinerHelper::applyCombineUnmergeMergeToPlainValues(), llvm::CombinerHelper::applyCombineUnmergeWithDeadLanesToTrunc(), llvm::CombinerHelper::applyCombineUnmergeZExtToZExt(), AMDGPUPostLegalizerCombinerHelper::applyCvtF32UByteN(), llvm::RegisterBankInfo::applyDefaultMapping(), applyDupLane(), llvm::CombinerHelper::applyExtendThroughPhis(), llvm::CombinerHelper::applyExtractVecEltBuildVec(), AMDGPUCombinerHelper::applyFoldableFneg(), llvm::CombinerHelper::applyFoldBinOpIntoSelect(), llvm::CombinerHelper::applyFsubToFneg(), applyICmpRedundantTrunc(), applyINS(), llvm::AMDGPURegisterBankInfo::applyMappingBFE(), llvm::AMDGPURegisterBankInfo::applyMappingDynStackAlloc(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), llvm::CombinerHelper::applyOptBrCondByInvertingCond(), llvm::CombinerHelper::applyPtrAddImmedChain(), llvm::CombinerHelper::applyRotateOutOfRange(), llvm::CombinerHelper::applyShiftImmedChain(), llvm::CombinerHelper::applyShiftOfShiftedLogic(), llvm::CombinerHelper::applySimplifyURemByPow2(), applySplitStoreZero128(), llvm::CombinerHelper::applyTruncStoreMerge(), AMDGPUPostLegalizerCombinerHelper::applyUCharToFloat(), llvm::CombinerHelper::applyUMulHToLShr(), llvm::CombinerHelper::applyXorOfAndWithSameReg(), llvm::CallLowering::IncomingValueHandler::assignValueToReg(), llvm::LegalizerHelper::bitcast(), llvm::LegalizerHelper::bitcastExtractVectorElt(), llvm::LegalizerHelper::bitcastInsertVectorElt(), buildAnyextOrCopy(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), buildCopyFromRegs(), buildCopyToRegs(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), buildLogBase2(), llvm::AMDGPURegisterBankInfo::buildReadFirstLane(), llvm::CombinerHelper::buildSDivUsingMul(), llvm::CombinerHelper::buildUDivUsingMul(), llvm::AMDGPURegisterBankInfo::buildVCopy(), llvm::CombinerHelper::canCombineFMadOrFMA(), llvm::canReplaceReg(), cloneVirtualRegister(), llvm::LegalizerHelper::coerceToScalar(), llvm::SITargetLowering::computeKnownBitsForTargetInstr(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::RegBankSelect::computeMapping(), llvm::GISelKnownBits::computeNumSignBits(), llvm::ConstantFoldCTLZ(), llvm::ConstantFoldExtOp(), constrainRegAttrs(), constrainRegToBank(), llvm::CallLowering::ValueHandler::copyArgumentMemory(), llvm::createMemLibcall(), createNewIdReg(), equalizeVectorShuffleLengths(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::CallLowering::ValueHandler::extendRegister(), llvm::LegalizerHelper::fewerElementsVector(), llvm::LegalizerHelper::fewerElementsVectorExtractInsertVectorElt(), llvm::LegalizerHelper::fewerElementsVectorMerge(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::LegalizerHelper::fewerElementsVectorReductions(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), llvm::LegalizerHelper::fewerElementsVectorUnmergeValues(), llvm::AMDGPULegalizerInfo::fixStoreSourceType(), fixupPHIOpBanks(), AMDGPURegBankCombinerHelper::getAsVgpr(), getCmpOperandFoldingProfit(), llvm::SIRegisterInfo::getConstrainedRegClassForOperand(), llvm::getDefSrcRegIgnoringCopies(), llvm::AMDGPULegalizerInfo::getImplicitArgPtr(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::PPCRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), llvm::GISelKnownBits::getKnownBits(), llvm::RegisterBankInfo::getRegBank(), llvm::RegisterBankInfo::getRegBankFromConstraints(), llvm::TargetRegisterInfo::getRegSizeInBits(), getSalvageOpsForTrunc(), getTestBitReg(), getTruncStoreByteOffset(), getTypeFromTypeIdx(), llvm::MachineInstr::getTypeToPrint(), llvm::AMDGPURegisterBankInfo::getValueMappingForPtr(), llvm::LegalizerHelper::getVectorElementPointer(), getVectorFCMP(), getVectorShiftImm(), llvm::CallLowering::handleAssignments(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), hasSameNumEltsOnAllVectorOperands(), llvm::insertAssignInstr(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), llvm::SITargetLowering::isCanonicalized(), llvm::isConstantOrConstantSplatVector(), isExtractHiElt(), llvm::isKnownToBeAPowerOfTwo(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::AMDGPULegalizerInfo::legalizeBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeBufferStore(), llvm::AMDGPULegalizerInfo::legalizeBuildVector(), llvm::AMDGPULegalizerInfo::legalizeBVHIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeCTLZ_CTTZ(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::SPIRVLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFceil(), llvm::AMDGPULegalizerInfo::legalizeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeFPTOI(), llvm::AMDGPULegalizerInfo::legalizeFrem(), llvm::AMDGPULegalizerInfo::legalizeFrint(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeLoad(), llvm::AMDGPULegalizerInfo::legalizeMul(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeSignedDIV_REM(), llvm::AMDGPULegalizerInfo::legalizeSinCos(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM(), llvm::LegalizerHelper::libcall(), llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerAbsToAddXor(), llvm::LegalizerHelper::lowerAbsToMaxNeg(), llvm::LegalizerHelper::lowerAddSubSatToAddoSubo(), llvm::LegalizerHelper::lowerAddSubSatToMinMax(), llvm::LegalizerHelper::lowerBitcast(), llvm::LegalizerHelper::lowerBitCount(), llvm::LegalizerHelper::lowerBitreverse(), llvm::LegalizerHelper::lowerBswap(), llvm::AArch64CallLowering::lowerCall(), llvm::LegalizerHelper::lowerDynStackAlloc(), llvm::LegalizerHelper::lowerExtract(), llvm::LegalizerHelper::lowerExtractInsertVectorElt(), llvm::LegalizerHelper::lowerFConstant(), llvm::LegalizerHelper::lowerFCopySign(), llvm::LegalizerHelper::lowerFFloor(), llvm::LegalizerHelper::lowerFMad(), llvm::LegalizerHelper::lowerFMinNumMaxNum(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::LegalizerHelper::lowerFPOWI(), llvm::LegalizerHelper::lowerFPTOSI(), llvm::LegalizerHelper::lowerFPTOUI(), llvm::LegalizerHelper::lowerFPTRUNC(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), llvm::LegalizerHelper::lowerFunnelShift(), llvm::LegalizerHelper::lowerFunnelShiftAsShifts(), llvm::LegalizerHelper::lowerFunnelShiftWithInverse(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::LegalizerHelper::lowerInsert(), llvm::LegalizerHelper::lowerIntrinsicRound(), llvm::LegalizerHelper::lowerISFPCLASS(), llvm::LegalizerHelper::lowerLoad(), llvm::LegalizerHelper::lowerMergeValues(), llvm::LegalizerHelper::lowerMinMax(), llvm::LegalizerHelper::lowerReadWriteRegister(), llvm::AArch64CallLowering::lowerReturn(), llvm::LegalizerHelper::lowerRotate(), llvm::LegalizerHelper::lowerRotateWithReverseRotate(), llvm::LegalizerHelper::lowerSADDO_SSUBO(), llvm::LegalizerHelper::lowerSelect(), llvm::LegalizerHelper::lowerShlSat(), llvm::LegalizerHelper::lowerShuffleVector(), llvm::LegalizerHelper::lowerSITOFP(), llvm::LegalizerHelper::lowerSMULH_UMULH(), llvm::LegalizerHelper::lowerStore(), llvm::LegalizerHelper::lowerU64ToF32BitOps(), llvm::LegalizerHelper::lowerUITOFP(), llvm::LegalizerHelper::lowerUnmergeValues(), lowerVectorFCMP(), llvm::LegalizerHelper::lowerVectorReduction(), matchAArch64MulConstCombine(), llvm::CombinerHelper::matchAddOBy0(), llvm::CombinerHelper::matchAndOrDisjointMask(), llvm::CombinerHelper::matchAshrShlToSextInreg(), llvm::CombinerHelper::matchBitfieldExtractFromAnd(), llvm::CombinerHelper::matchBitfieldExtractFromSExtInReg(), llvm::CombinerHelper::matchBitfieldExtractFromShr(), llvm::CombinerHelper::matchBitfieldExtractFromShrAnd(), llvm::CombinerHelper::matchBuildVectorIdentityFold(), AMDGPUPreLegalizerCombinerHelper::matchClampI64ToI16(), llvm::CombinerHelper::matchCombineAddP2IToPtrAdd(), llvm::CombinerHelper::matchCombineAnyExtTrunc(), llvm::CombinerHelper::matchCombineConcatVectors(), llvm::CombinerHelper::matchCombineConstantFoldFpUnary(), llvm::CombinerHelper::matchCombineConstPtrAddToI2P(), llvm::CombinerHelper::matchCombineDivRem(), llvm::CombinerHelper::matchCombineExtendingLoads(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineI2PToP2I(), llvm::CombinerHelper::matchCombineInsertVecElts(), llvm::CombinerHelper::matchCombineLoadWithAndMask(), llvm::CombinerHelper::matchCombineShiftToUnmerge(), llvm::CombinerHelper::matchCombineShlOfExtend(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::CombinerHelper::matchCombineTruncOfShift(), llvm::CombinerHelper::matchCombineUnmergeConstant(), llvm::CombinerHelper::matchCombineUnmergeMergeToPlainValues(), llvm::CombinerHelper::matchCombineUnmergeZExtToZExt(), llvm::CombinerHelper::matchCombineZextTrunc(), matchDupLane(), matchEXT(), llvm::CombinerHelper::matchExtendThroughPhis(), llvm::CombinerHelper::matchExtractAllEltsFromBuildVector(), llvm::CombinerHelper::matchExtractVecEltBuildVec(), matchExtractVecEltPairwiseAdd(), matchFConstantToConstant(), AMDGPUPostLegalizerCombinerHelper::matchFMinFMaxLegacy(), matchFoldMergeToZext(), matchFormTruncstore(), AMDGPURegBankCombinerHelper::matchFPMinMaxToMed3(), llvm::CombinerHelper::matchFsubToFneg(), llvm::CombinerHelper::matchFunnelShiftToRotate(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), matchICmpRedundantTrunc(), llvm::CombinerHelper::matchICmpToLHSKnownBits(), llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), matchINS(), llvm::CombinerHelper::matchInsertExtractVecEltOutOfBounds(), AMDGPURegBankCombinerHelper::matchIntMinMaxToMed3(), llvm::CombinerHelper::matchLoadOrCombine(), llvm::CombinerHelper::matchMulOBy0(), matchMutateAnyExtToZExt(), llvm::CombinerHelper::matchNarrowBinopFeedingAnd(), llvm::CombinerHelper::matchNotCmp(), llvm::CombinerHelper::matchOrShiftToFunnelShift(), llvm::CombinerHelper::matchOverlappingAnd(), llvm::CombinerHelper::matchPtrAddImmedChain(), llvm::CombinerHelper::matchPtrAddZero(), llvm::CombinerHelper::matchReassocConstantInnerLHS(), llvm::CombinerHelper::matchReassocConstantInnerRHS(), llvm::CombinerHelper::matchReassocFoldConstantsInSubTree(), llvm::CombinerHelper::matchRedundantBinOpInEquality(), llvm::CombinerHelper::matchRedundantNegOperands(), llvm::CombinerHelper::matchRedundantSExtInReg(), matchREV(), llvm::CombinerHelper::matchRotateOutOfRange(), llvm::CombinerHelper::matchSDivByConst(), llvm::CombinerHelper::matchSelectToLogical(), llvm::CombinerHelper::matchSextInRegOfLoad(), llvm::CombinerHelper::matchSextTruncSextLoad(), llvm::CombinerHelper::matchShiftImmedChain(), llvm::CombinerHelper::matchShiftOfShiftedLogic(), matchSplitStoreZero128(), llvm::CombinerHelper::matchSubAddSameReg(), matchTRN(), llvm::CombinerHelper::matchTruncBuildVectorFold(), llvm::CombinerHelper::matchTruncLshrBuildVectorFold(), llvm::CombinerHelper::matchTruncStoreMerge(), AMDGPUPostLegalizerCombinerHelper::matchUCharToFloat(), llvm::CombinerHelper::matchUDivByConst(), llvm::CombinerHelper::matchUMulHToLShr(), matchUZP(), matchVAshrLshrImm(), matchVectorSextInReg(), matchZeroExtendFromS32(), matchZip(), mergeVectorRegsToResultRegs(), llvm::LegalizerHelper::moreElementsVector(), llvm::LegalizerHelper::moreElementsVectorShuffle(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarAddSub(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarCTLZ(), llvm::LegalizerHelper::narrowScalarCTPOP(), llvm::LegalizerHelper::narrowScalarCTTZ(), llvm::LegalizerHelper::narrowScalarExt(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarFPTOI(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarMul(), llvm::LegalizerHelper::narrowScalarSelect(), llvm::LegalizerHelper::narrowScalarShift(), opMustUseVOP3Encoding(), processInstrsWithTypeFolding(), llvm::LegalizerHelper::reduceLoadStoreWidth(), llvm::RegBankSelect::repairReg(), llvm::InstructionSelect::runOnMachineFunction(), selectCopy(), selectDebugInstr(), selectMergeValues(), selectUnmergeValues(), llvm::MipsRegisterBankInfo::setRegBank(), setRegsToType(), llvm::GISelKnownBits::signBitIsZero(), llvm::AMDGPULegalizerInfo::splitBufferOffsets(), tryAdjustICmpImmAndPred(), tryToSimplifyUADDO(), unsupportedBinOp(), llvm::SIMachineFunctionInfo::usesAGPRs(), llvm::RegisterBankInfo::InstructionMapping::verify(), llvm::LegalizerHelper::widenScalar(), and X86SelectAddress().
getUniqueVRegDef()
MachineInstr * MachineRegisterInfo::getUniqueVRegDef (Register Reg) const
getUniqueVRegDef - Return the unique machine instr that defines the specified virtual register or null if none is found.
If there are multiple definitions or no definition, return null.
Definition at line 409 of file MachineRegisterInfo.cpp.
References def_empty(), def_instr_begin(), def_instr_end(), and I.
Referenced by llvm::ARMBaseInstrInfo::analyzeLoopForPipelining(), llvm::PPCInstrInfo::analyzeLoopForPipelining(), llvm::CombinerHelper::applyCombineIndexedLoadStore(), llvm::SPIRVGeneralDuplicatesTracker::buildDepsGraph(), canCombine(), CombineCVTAToLocal(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), findSingleRegDef(), llvm::SIInstrInfo::FoldImmediate(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), genFusedMultiply(), genIndexedMultiply(), genMaddR(), genSubAdd2SubSub(), getDynAllocaAmount(), llvm::PeelingModuloScheduleExpander::getEquivalentRegisterIn(), llvm::PPCInstrInfo::getFMAPatterns(), getFMULPatterns(), getFoldableImm(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeByOpcode(), getVRegDef(), llvm::X86InstrInfo::hasCommutePreference(), llvm::TargetInstrInfo::hasReassociableOperands(), llvm::TargetInstrInfo::hasReassociableSibling(), hasSameValue(), isCVTAToLocalCombinationCandidate(), isImplicitlyDef(), isVCmpResult(), llvm::SIInstrInfo::legalizeGenericOperand(), llvm::CombinerHelper::matchShiftImmedChain(), llvm::CombinerHelper::matchShiftOfShiftedLogic(), llvm::SIInstrInfo::moveFlatAddrToVGPR(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::PeelingModuloScheduleExpander::peelPrologAndEpilogs(), llvm::GenericSSAContext< MachineFunction >::print(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), shouldPreventUndefRegUpdateMemFold(), llvm::TargetRegisterInfo::shouldRegionSplitForVirtReg(), and unstackifyVRegsUsedInSplitBB().
getUsedPhysRegsMask()
const BitVector& llvm::MachineRegisterInfo::getUsedPhysRegsMask () const inline
Definition at line 899 of file MachineRegisterInfo.h.
getVRegDef()
MachineInstr * MachineRegisterInfo::getVRegDef (Register Reg) const
getVRegDef - Return the machine instr that defines the specified virtual register or null if none is found.
This assumes that the code is in SSA form, so there should only be one definition.
Definition at line 398 of file MachineRegisterInfo.cpp.
References assert(), def_instr_begin(), def_instr_end(), and I.
Referenced by addConstantsToTrack(), llvm::CombinerHelper::applyCombineUnmergeZExtToZExt(), llvm::CombinerHelper::applyExtendThroughPhis(), llvm::CombinerHelper::applyFoldBinOpIntoSelect(), llvm::CombinerHelper::applyNotCmp(), llvm::CombinerHelper::applySextInRegOfLoad(), llvm::SPIRVGeneralDuplicatesTracker::buildDepsGraph(), canCombineFPFusedMultiply(), canCompareBeNewValueJump(), canEmitConjunction(), canFoldAsPredicatedOp(), canFoldIntoCSel(), canFoldIntoSelect(), llvm::PPCInstrInfo::combineRLWINM(), llvm::SITargetLowering::computeKnownAlignForTargetInstr(), llvm::GISelKnownBits::computeKnownAlignment(), llvm::SITargetLowering::computeKnownBitsForTargetInstr(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::GISelKnownBits::computeNumSignBits(), llvm::AMDGPUTargetLowering::computeNumSignBitsForTargetInstr(), llvm::constrainOperandRegClass(), definedBySignExtendingOp(), definedByZeroExtendingOp(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCInstrInfo::finalizeInsInstrs(), findLoopComponents(), findRedundantFlagInstr(), findStartOfTree(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), fixupPHIOpBanks(), foldConstantsIntoIntrinsics(), foldImm(), llvm::RISCVInstrInfo::genAlternativeCodeSequence(), generateAssignInstrs(), llvm::getConstantFPVRegVal(), llvm::PPCInstrInfo::getConstantFromConstantPool(), llvm::getDefInstrMaybeConstant(), llvm::getDefSrcRegIgnoringCopies(), llvm::PPCInstrInfo::getFMAPatterns(), llvm::getFunctionLiveInPhysReg(), llvm::PPCRegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage(), llvm::PeelingModuloScheduleExpander::getPhiCanonicalReg(), getShape(), getVectorShiftImm(), llvm::getVRegSubRegDef(), llvm::LiveVariables::HandleVirtRegUse(), llvm::RISCVInstrInfo::hasReassociableSibling(), if(), INITIALIZE_PASS(), llvm::insertAssignInstr(), llvm::InstructionSelector::isBaseWithConstantOffset(), llvm::SITargetLowering::isCanonicalized(), llvm::isConstantOrConstantVector(), llvm::isCycleInvariant(), isImm(), llvm::isKnownNeverNaN(), isKnownNonNull(), llvm::LiveVariables::VarInfo::isLiveIn(), llvm::SMSchedule::isLoopCarried(), llvm::SMSchedule::isLoopCarriedDefOfUse(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), llvm::MachineLoop::isLoopInvariant(), isSignExtended(), isSignExtendedW(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isVShiftRImm(), isZeroExtended(), llvm::SIInstrInfo::legalizeGenericOperand(), LookThroughCOPY(), llvm::TargetRegisterInfo::lookThruCopyLike(), llvm::TargetRegisterInfo::lookThruSingleUseCopyChain(), lowerVectorFCMP(), llvm::CombinerHelper::matchCombineConcatVectors(), llvm::CombinerHelper::matchCombineExtOfExt(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineLoadWithAndMask(), llvm::CombinerHelper::matchCombineTruncOfExt(), llvm::CombinerHelper::matchCombineUnmergeConstant(), llvm::CombinerHelper::matchCombineUnmergeUndef(), llvm::CombinerHelper::matchConstantOp(), llvm::CombinerHelper::matchConstantSelectCmp(), llvm::CombinerHelper::matchExtractVecEltBuildVec(), matchExtractVecEltPairwiseAdd(), AMDGPUCombinerHelper::matchFoldableFneg(), llvm::CombinerHelper::matchFoldBinOpIntoSelect(), MatchingStackOffset(), llvm::CombinerHelper::matchNotCmp(), llvm::CombinerHelper::matchPtrAddImmedChain(), llvm::CombinerHelper::matchPtrAddZero(), AMDGPUPostLegalizerCombinerHelper::matchRcpSqrtToRsq(), llvm::CombinerHelper::matchReassocPtrAdd(), matchSplitStoreZero128(), llvm::CombinerHelper::matchUDivByConst(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::X86InstrInfo::optimizeLoadInstr(), processInstrsWithTypeFolding(), llvm::ARMBaseInstrInfo::produceSameValue(), propagateSPIRVType(), removeCopies(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::saveUsesAndErase(), llvm::TailDuplicator::tailDuplicateAndUpdate(), tryToSimplifyUADDO(), updatePHIs(), and llvm::SSAUpdaterTraits< MachineSSAUpdater >::ValueIsPHI().
getVRegName()
StringRef llvm::MachineRegisterInfo::getVRegName (Register Reg) const inline
Definition at line 450 of file MachineRegisterInfo.h.
References llvm::IndexedMap< T, ToIndexT >::inBounds().
Referenced by llvm::MIRPrinter::convert().
hasAtMostUserInstrs()
bool MachineRegisterInfo::hasAtMostUserInstrs (Register Reg, unsigned MaxUsers) const
hasAtMostUses - Return true if the given register has at most MaxUsers non-debug user instructions.
Definition at line 425 of file MachineRegisterInfo.cpp.
References llvm::hasNItemsOrLess(), use_instr_nodbg_begin(), and use_instr_nodbg_end().
Referenced by llvm::TargetLoweringBase::shouldLocalize().
hasOneDef()
bool llvm::MachineRegisterInfo::hasOneDef (Register RegNo) const inline
Return true if there is exactly one operand defining the specified register.
Definition at line 466 of file MachineRegisterInfo.h.
References def_operands(), and llvm::hasSingleElement().
Referenced by llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::InstrEmitter::EmitDbgInstrRef(), llvm::MachineFunction::finalizeDebugInstrRefs(), isSafeToMove(), isSSA(), moveForSingleUse(), llvm::AArch64InstrInfo::optimizeCondBranch(), processSwitches(), and llvm::MachineFunction::salvageCopySSAImpl().
hasOneNonDBGUse()
bool MachineRegisterInfo::hasOneNonDBGUse (Register RegNo) const
hasOneNonDBGUse - Return true if there is exactly one non-Debug use of the specified register.
Definition at line 417 of file MachineRegisterInfo.cpp.
References llvm::hasSingleElement(), and use_nodbg_operands().
Referenced by AMDGPUCombinerHelper::applyFoldableFneg(), canCombine(), canCombineFPFusedMultiply(), canEmitConjunction(), canFoldAsPredicatedOp(), canFoldIntoSelect(), CombineCVTAToLocal(), combineFPFusedMultiply(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::VEInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::FoldImmediate(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SIInstrInfo::FoldImmediate(), getCmpOperandFoldingProfit(), llvm::PPCInstrInfo::getFMAPatterns(), getTestBitReg(), llvm::TargetInstrInfo::hasReassociableSibling(), llvm::AArch64InstrInfo::isExtendLikelyToBeFolded(), isLUIADDI(), isOperandKill(), llvm::TargetRegisterInfo::lookThruSingleUseCopyChain(), matchAArch64MulConstCombine(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineLoadWithAndMask(), llvm::CombinerHelper::matchCombineTruncOfShift(), llvm::CombinerHelper::matchExtendThroughPhis(), llvm::CombinerHelper::matchExtractVecEltBuildVec(), AMDGPUPostLegalizerCombinerHelper::matchFMinFMaxLegacy(), AMDGPUCombinerHelper::matchFoldableFneg(), llvm::CombinerHelper::matchFoldBinOpIntoSelect(), AMDGPURegBankCombinerHelper::matchFPMinMaxToMed3(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), matchLoadAndBytePosition(), llvm::CombinerHelper::matchNarrowBinopFeedingAnd(), llvm::CombinerHelper::matchNotCmp(), llvm::CombinerHelper::matchSextInRegOfLoad(), llvm::CombinerHelper::matchShiftOfShiftedLogic(), matchSplitStoreZero128(), llvm::CombinerHelper::matchXorOfAndWithSameReg(), oneUseDominatesOtherUses(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::TailDuplicator::tailDuplicateAndUpdate(), tryToSimplifyUADDO(), and verifyCFIntrinsic().
hasOneNonDBGUser()
bool MachineRegisterInfo::hasOneNonDBGUser (Register RegNo) const
hasOneNonDBGUse - Return true if there is exactly one non-Debug instruction using the specified register.
Said instruction may have multiple uses.
Definition at line 421 of file MachineRegisterInfo.cpp.
References llvm::hasSingleElement(), and use_nodbg_instructions().
hasOneUse()
bool llvm::MachineRegisterInfo::hasOneUse (Register RegNo) const inline
hasOneUse - Return true if there is exactly one instruction using the specified register.
Definition at line 532 of file MachineRegisterInfo.h.
References llvm::hasSingleElement(), and use_operands().
Referenced by llvm::SIInstrInfo::FoldImmediate(), foldVGPRCopyIntoRegSequence(), generateAssignInstrs(), hasOneUse(), INITIALIZE_PASS(), isKilled(), llvm::CombinerHelper::matchCombineInsertVecElts(), moveForSingleUse(), llvm::PPCInstrInfo::optimizeCompareInstr(), processInstr(), processInstrsWithTypeFolding(), processSwitches(), and llvm::FastISel::tryToFoldLoad().
insertVRegByName()
void llvm::MachineRegisterInfo::insertVRegByName (StringRef Name, Register Reg) inline
Definition at line 454 of file MachineRegisterInfo.h.
References assert(), llvm::StringMap< std::nullopt_t, MallocAllocator >::end(), llvm::StringMap< std::nullopt_t, MallocAllocator >::find(), llvm::IndexedMap< T, ToIndexT >::grow(), and llvm::StringSet< AllocatorTy >::insert().
Referenced by createIncompleteVirtualRegister().
invalidateLiveness()
void llvm::MachineRegisterInfo::invalidateLiveness () inline
invalidateLiveness - Indicates that register liveness is no longer being tracked accurately.
This should be called by late passes that invalidate the liveness information.
Definition at line 219 of file MachineRegisterInfo.h.
References llvm::MachineFunction::getProperties(), llvm::MachineFunctionProperties::reset(), and llvm::MachineFunctionProperties::TracksLiveness.
Referenced by llvm::BranchFolder::OptimizeFunction(), and llvm::MIRParserImpl::parseRegisterInfo().
isAllocatable()
bool llvm::MachineRegisterInfo::isAllocatable (MCRegister PhysReg) const inline
isAllocatable - Returns true when PhysReg belongs to an allocatable register class and it hasn't been reserved.
Allocatable registers may show up in the allocation order of some virtual register, so a register allocator needs to track its liveness and availability.
Definition at line 974 of file MachineRegisterInfo.h.
References getTargetRegisterInfo(), llvm::TargetRegisterInfo::isInAllocatableClass(), and isReserved().
Referenced by computeLiveOuts(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::SIRegisterInfo::findUnusedRegister(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), and isConstantPhysReg().
isArgumentRegister()
bool MachineRegisterInfo::isArgumentRegister (const MachineFunction & MF, MCRegister Reg) const
Returns true if a register can be used as an argument to a function.
Definition at line 662 of file MachineRegisterInfo.cpp.
References getTargetRegisterInfo(), and llvm::TargetRegisterInfo::isArgumentRegister().
isConstantPhysReg()
bool MachineRegisterInfo::isConstantPhysReg (MCRegister PhysReg) const
Returns true if PhysReg is unallocatable and constant throughout the function.
Writing to a constant register has no effect.
Definition at line 517 of file MachineRegisterInfo.cpp.
References assert(), def_empty(), getTargetRegisterInfo(), isAllocatable(), llvm::TargetRegisterInfo::isConstantPhysReg(), llvm::Register::isPhysicalRegister(), llvm::MCRegAliasIterator::isValid(), and TRI.
Referenced by llvm::ScheduleDAGInstrs::addPhysRegDeps(), llvm::LiveRangeEdit::allUsesAvailableAt(), canFoldAsPredicatedOp(), isCallerPreservedOrConstPhysReg(), llvm::isCycleInvariant(), and llvm::MachineLoop::isLoopInvariant().
isFixedRegister()
bool MachineRegisterInfo::isFixedRegister (const MachineFunction & MF, MCRegister Reg) const
Returns true if a register is a fixed register.
Definition at line 667 of file MachineRegisterInfo.cpp.
References getTargetRegisterInfo(), and llvm::TargetRegisterInfo::isFixedRegister().
isGeneralPurposeRegister()
bool MachineRegisterInfo::isGeneralPurposeRegister (const MachineFunction & MF, MCRegister Reg) const
Returns true if a register is a general purpose register.
Definition at line 672 of file MachineRegisterInfo.cpp.
References getTargetRegisterInfo(), and llvm::TargetRegisterInfo::isGeneralPurposeRegister().
isLiveIn()
bool MachineRegisterInfo::isLiveIn (Register Reg) const
Definition at line 440 of file MachineRegisterInfo.cpp.
References liveins().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::ARMFrameLowering::determineCalleeSaves(), getPrologueDeath(), insertCSRSaves(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), isSignExtendedW(), llvm::PPCInstrInfo::isSignOrZeroExtended(), pushRegsToStack(), reservePrivateMemoryRegs(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::M68kFrameLowering::spillCalleeSavedRegisters(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
isPhysRegModified()
bool MachineRegisterInfo::isPhysRegModified (MCRegister PhysReg, bool SkipNoReturnDef = false) const
Return true if the specified register is modified in this function.
This checks that no defining machine operands exist for the register or any of its aliases. Definitions found on functions marked noreturn are ignored, to consider them pass 'true' for optional parameter SkipNoReturnDef. The register is also considered modified when it is set in the UsedPhysRegMask.
Definition at line 574 of file MachineRegisterInfo.cpp.
References def_begin(), def_end(), getTargetRegisterInfo(), isNoReturnDef(), llvm::MCRegAliasIterator::isValid(), llvm::make_range(), llvm::BitVector::test(), and TRI.
Referenced by llvm::XCoreFrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), isSafeToMove(), and isXPLeafCandidate().
isPhysRegUsed()
bool MachineRegisterInfo::isPhysRegUsed (MCRegister PhysReg, bool SkipRegMaskTest = false) const
Return true if the specified register is modified or read in this function.
This checks that no machine operands exist for the register or any of its aliases. If SkipRegMaskTest is false, the register is considered used when it is set in the UsedPhysRegMask.
Definition at line 589 of file MachineRegisterInfo.cpp.
References getTargetRegisterInfo(), llvm::MCRegAliasIterator::isValid(), reg_nodbg_empty(), llvm::BitVector::test(), and TRI.
Referenced by llvm::PPCFrameLowering::assignCalleeSavedSpillSlots(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), findUnusedRegister(), llvm::SIRegisterInfo::findUnusedRegister(), llvm::GCNHazardRecognizer::GCNHazardRecognizer(), needToReserveScavengingSpillSlots(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::SIMachineFunctionInfo::usesAGPRs(), and verifyLeafProcRegUse().
isReserved()
bool llvm::MachineRegisterInfo::isReserved (MCRegister PhysReg) const inline
isReserved - Returns true when PhysReg is a reserved register.
Reserved registers may belong to an allocatable register class, but the target has explicitly requested that they are not used.
Definition at line 956 of file MachineRegisterInfo.h.
References getReservedRegs(), llvm::MCRegister::id(), and llvm::BitVector::test().
Referenced by addHints(), llvm::addLiveIns(), llvm::LivePhysRegs::available(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::X86FrameLowering::emitPrologue(), findSurvivorBackwards(), llvm::RISCVRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), indirectCopyToAGPR(), INITIALIZE_PASS(), isAllocatable(), llvm::SIRegisterInfo::isAsmClobberable(), isBackwardPropagatableCopy(), isReservedRegUnit(), pushRegsToStack(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), and tryToFindRegisterToRename().
isReservedRegUnit()
bool MachineRegisterInfo::isReservedRegUnit (unsigned Unit) const
Returns true when the given register unit is considered reserved.
Register units are considered reserved when for at least one of their root registers, the root register and all super registers are reserved. This currently iterates the register hierarchy and may be slower than expected.
Definition at line 644 of file MachineRegisterInfo.cpp.
References getTargetRegisterInfo(), isReserved(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegUnitRootIterator::isValid(), and TRI.
Referenced by llvm::LiveIntervals::HMEditor::getRegUnitLI().
isSSA()
bool llvm::MachineRegisterInfo::isSSA () const inline
Definition at line 197 of file MachineRegisterInfo.h.
References llvm::MachineFunction::getProperties(), llvm::MachineFunctionProperties::hasProperty(), and llvm::MachineFunctionProperties::IsSSA.
Referenced by llvm::PPCInstrInfo::convertToImmediateForm(), llvm::execMayBeModifiedBeforeAnyUse(), llvm::execMayBeModifiedBeforeUse(), llvm::SIInstrInfo::expandMovDPP64(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), llvm::PPCInstrInfo::foldFrameOffset(), llvm::getVRegSubRegDef(), llvm::SystemZInstrInfo::loadImmediate(), llvm::PPCInstrInfo::materializeImmPostRA(), llvm::PPCInstrInfo::optimizeCmpPostRA(), llvm::LiveVariables::runOnMachineFunction(), and splitMBB().
isUpdatedCSRsInitialized()
bool llvm::MachineRegisterInfo::isUpdatedCSRsInitialized () const inline
Returns true if the updated CSR list was initialized and false otherwise.
Definition at line 242 of file MachineRegisterInfo.h.
Referenced by llvm::MIRPrinter::convert().
leaveSSA()
void llvm::MachineRegisterInfo::leaveSSA () inline
Definition at line 203 of file MachineRegisterInfo.h.
References llvm::MachineFunction::getProperties(), llvm::MachineFunctionProperties::IsSSA, and llvm::MachineFunctionProperties::reset().
livein_begin()
livein_iterator llvm::MachineRegisterInfo::livein_begin () const inline
Definition at line 993 of file MachineRegisterInfo.h.
Referenced by llvm::MachineFunction::print().
livein_empty()
bool llvm::MachineRegisterInfo::livein_empty () const inline
Definition at line 995 of file MachineRegisterInfo.h.
Referenced by llvm::R600InstrInfo::getIndirectIndexBegin(), and llvm::MachineFunction::print().
livein_end()
livein_iterator llvm::MachineRegisterInfo::livein_end () const inline
Definition at line 994 of file MachineRegisterInfo.h.
Referenced by llvm::MachineFunction::print().
liveins()
ArrayRef<std::pair<MCRegister, Register> > llvm::MachineRegisterInfo::liveins () const inline
Definition at line 997 of file MachineRegisterInfo.h.
Referenced by llvm::rdf::DataFlowGraph::build(), checkFnHasLiveInYmmOrZmm(), llvm::MIRPrinter::convert(), llvm::R600InstrInfo::getIndirectIndexBegin(), getLiveInPhysReg(), getLiveInVirtReg(), isLiveIn(), and llvm::SelectionDAGISel::runOnMachineFunction().
markUsesInDebugValueAsUndef()
void MachineRegisterInfo::markUsesInDebugValueAsUndef (Register Reg) const
markUsesInDebugValueAsUndef - Mark every DBG_VALUE referencing the specified register as undefined which causes the DBG_VALUE to be deleted during LiveDebugVariables analysis.
Definition at line 536 of file MachineRegisterInfo.cpp.
References llvm::make_early_inc_range(), use_instructions(), and UseMI.
moveOperands()
void MachineRegisterInfo::moveOperands (MachineOperand * Dst, MachineOperand * Src, unsigned NumOps)
Move NumOps operands from Src to Dst, updating use-def lists as needed.
The Dst range is assumed to be uninitialized memory. (Or it may contain operands that won't be destroyed, which is OK because the MO destructor is trivial anyway).
The Src and Dst ranges may overlap.
Definition at line 333 of file MachineRegisterInfo.cpp.
References assert().
Referenced by llvm::SIInstrInfo::moveFlatAddrToVGPR(), and moveOperands().
noteCloneVirtualRegister()
void llvm::MachineRegisterInfo::noteCloneVirtualRegister (Register NewReg, Register SrcReg) inline
Definition at line 181 of file MachineRegisterInfo.h.
Referenced by cloneVirtualRegister().
noteNewVirtualRegister()
void llvm::MachineRegisterInfo::noteNewVirtualRegister (Register Reg) inline
Definition at line 176 of file MachineRegisterInfo.h.
Referenced by createGenericVirtualRegister(), and createVirtualRegister().
operator=()
MachineRegisterInfo& llvm::MachineRegisterInfo::operator= (const MachineRegisterInfo &) delete
recomputeRegClass()
bool MachineRegisterInfo::recomputeRegClass (Register Reg)
recomputeRegClass - Try to find a legal super-class of Reg's register class that still satisfies the constraints from the instructions using Reg.
Returns true if Reg was upgraded.
This method can be used after constraints have been removed from a virtual register, for example after removing instructions or splitting the live range.
Definition at line 121 of file MachineRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetRegisterInfo::getLargestLegalSuperClass(), getRegClass(), llvm::MachineFunction::getSubtarget(), getTargetRegisterInfo(), MI, reg_nodbg_operands(), setRegClass(), and TII.
Referenced by llvm::LiveRangeEdit::calculateRegClassAndHint().
reg_begin()
reg_iterator llvm::MachineRegisterInfo::reg_begin (Register RegNo) const inline
Definition at line 303 of file MachineRegisterInfo.h.
Referenced by reg_empty(), reg_operands(), and llvm::FastISel::tryToFoldLoad().
reg_bundle_begin()
reg_bundle_iterator llvm::MachineRegisterInfo::reg_bundle_begin (Register RegNo) const inline
Definition at line 332 of file MachineRegisterInfo.h.
Referenced by reg_bundles().
reg_bundle_end()
static reg_bundle_iterator llvm::MachineRegisterInfo::reg_bundle_end () inline static
Definition at line 335 of file MachineRegisterInfo.h.
Referenced by reg_bundles().
reg_bundle_nodbg_begin()
reg_bundle_nodbg_iterator llvm::MachineRegisterInfo::reg_bundle_nodbg_begin (Register RegNo) const inline
Definition at line 385 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_bundles().
reg_bundle_nodbg_end()
static reg_bundle_nodbg_iterator llvm::MachineRegisterInfo::reg_bundle_nodbg_end () inline static
Definition at line 388 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_bundles().
reg_bundles()
iterator_range<reg_bundle_iterator> llvm::MachineRegisterInfo::reg_bundles (Register Reg) const inline
Definition at line 339 of file MachineRegisterInfo.h.
References llvm::make_range(), reg_bundle_begin(), and reg_bundle_end().
reg_empty()
bool llvm::MachineRegisterInfo::reg_empty (Register RegNo) const inline
reg_empty - Return true if there are no instructions using or defining the specified register (it may be live-in).
Definition at line 345 of file MachineRegisterInfo.h.
References reg_begin(), and reg_end().
Referenced by llvm::restoreStatusRegister().
reg_end()
static reg_iterator llvm::MachineRegisterInfo::reg_end () inline static
Definition at line 306 of file MachineRegisterInfo.h.
Referenced by reg_empty(), and reg_operands().
reg_instr_begin()
reg_instr_iterator llvm::MachineRegisterInfo::reg_instr_begin (Register RegNo) const inline
Definition at line 316 of file MachineRegisterInfo.h.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), and reg_instructions().
reg_instr_end()
static reg_instr_iterator llvm::MachineRegisterInfo::reg_instr_end () inline static
Definition at line 319 of file MachineRegisterInfo.h.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), and reg_instructions().
reg_instr_nodbg_begin()
reg_instr_nodbg_iterator llvm::MachineRegisterInfo::reg_instr_nodbg_begin (Register RegNo) const inline
Definition at line 368 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_instructions().
reg_instr_nodbg_end()
static reg_instr_nodbg_iterator llvm::MachineRegisterInfo::reg_instr_nodbg_end () inline static
Definition at line 371 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_instructions().
reg_instructions()
iterator_range<reg_instr_iterator> llvm::MachineRegisterInfo::reg_instructions (Register Reg) const inline
Definition at line 324 of file MachineRegisterInfo.h.
References llvm::make_range(), reg_instr_begin(), and reg_instr_end().
Referenced by clearVirtRegs(), llvm::SystemZRegisterInfo::getRegAllocationHints(), and llvm::LiveIntervals::shrinkToUses().
reg_nodbg_begin()
reg_nodbg_iterator llvm::MachineRegisterInfo::reg_nodbg_begin (Register RegNo) const inline
Definition at line 351 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_empty(), and reg_nodbg_operands().
reg_nodbg_bundles()
iterator_range<reg_bundle_nodbg_iterator> llvm::MachineRegisterInfo::reg_nodbg_bundles (Register Reg) const inline
Definition at line 393 of file MachineRegisterInfo.h.
References llvm::make_range(), reg_bundle_nodbg_begin(), and reg_bundle_nodbg_end().
reg_nodbg_empty()
bool llvm::MachineRegisterInfo::reg_nodbg_empty (Register RegNo) const inline
reg_nodbg_empty - Return true if the only instructions using or defining Reg are Debug instructions.
Definition at line 399 of file MachineRegisterInfo.h.
References reg_nodbg_begin(), and reg_nodbg_end().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::RegAllocBase::allocatePhysRegs(), llvm::VirtRegAuxInfo::calculateSpillWeightsAndHints(), and isPhysRegUsed().
reg_nodbg_end()
static reg_nodbg_iterator llvm::MachineRegisterInfo::reg_nodbg_end () inline static
Definition at line 354 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_empty(), and reg_nodbg_operands().
reg_nodbg_instructions()
iterator_range<reg_instr_nodbg_iterator> llvm::MachineRegisterInfo::reg_nodbg_instructions (Register Reg) const inline
Definition at line 376 of file MachineRegisterInfo.h.
References llvm::make_range(), reg_instr_nodbg_begin(), and reg_instr_nodbg_end().
Referenced by llvm::PPCRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), and isTerminalReg().
reg_nodbg_operands()
iterator_range<reg_nodbg_iterator> llvm::MachineRegisterInfo::reg_nodbg_operands (Register Reg) const inline
Definition at line 359 of file MachineRegisterInfo.h.
References llvm::make_range(), reg_nodbg_begin(), and reg_nodbg_end().
Referenced by llvm::LiveIntervalCalc::calculate(), computeWeight(), llvm::RISCVRegisterInfo::getRegAllocationHints(), recomputeRegClass(), scavengeVReg(), and tryChangeVGPRtoSGPRinCopy().
reg_operands()
iterator_range<reg_iterator> llvm::MachineRegisterInfo::reg_operands (Register Reg) const inline
Definition at line 308 of file MachineRegisterInfo.h.
References llvm::make_range(), reg_begin(), and reg_end().
Referenced by llvm::ConnectedVNInfoEqClasses::Distribute(), hasAnyNonFlatUseOfReg(), replaceRegWith(), and verifyUseList().
removeRegOperandFromUseList()
void MachineRegisterInfo::removeRegOperandFromUseList (MachineOperand * MO)
Remove MO from its use-def list.
Definition at line 304 of file MachineRegisterInfo.cpp.
References assert(), and llvm::MachineOperand::getReg().
Referenced by llvm::MachineOperand::ChangeToRegister(), llvm::SIInstrInfo::moveFlatAddrToVGPR(), llvm::MachineInstr::removeOperand(), llvm::MachineOperand::setIsDef(), and llvm::MachineOperand::setReg().
replaceRegWith()
void MachineRegisterInfo::replaceRegWith (Register FromReg, Register ToReg)
replaceRegWith - Replace all instances of FromReg with ToReg in the machine function.
This is like llvm-level X->replaceAllUsesWith(Y), except that it also changes any definitions of the register as well.
Note that it is usually necessary to first constrain ToReg's register class and register bank to match the FromReg constraints using one of the methods:
constrainRegClass(ToReg, getRegClass(FromReg)) constrainRegAttrs(ToReg, FromReg) RegisterBankInfo::constrainGenericRegister(ToReg, *MRI.getRegClass(FromReg), MRI)
These functions will return a falsy result if the virtual registers have incompatible constraints.
Note that if ToReg is a physical register the function will replace and apply sub registers to ToReg in order to obtain a final/proper physical register.
This is like llvm-level X->replaceAllUsesWith(Y), except that it also changes any definitions of the register as well. If ToReg is a physical register we apply the sub register to obtain the final/proper physical register.
Definition at line 380 of file MachineRegisterInfo.cpp.
References assert(), getTargetRegisterInfo(), llvm::Register::isPhysical(), llvm::make_early_inc_range(), llvm::RISCVFenceField::O, reg_operands(), and TRI.
Referenced by addConstantsToTrack(), llvm::SPIRVInstrInfo::copyPhysReg(), llvm::SPIRVInstrInfo::expandPostRAPseudo(), llvm::SITargetLowering::finalizeLowering(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), lowerVectorFCMP(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::SIInstrInfo::moveToVALU(), llvm::CombinerHelper::replaceRegWith(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), scavengeVReg(), and llvm::TailDuplicator::tailDuplicateAndUpdate().
reservedRegsFrozen()
bool llvm::MachineRegisterInfo::reservedRegsFrozen () const inline
reservedRegsFrozen - Returns true after freezeReservedRegs() was called to ensure the set of reserved registers stays constant.
Definition at line 931 of file MachineRegisterInfo.h.
Referenced by adjustAllocatableRegClass(), canReserveReg(), getReservedRegs(), isCallerPreservedOrConstPhysReg(), llvm::SIInstrInfo::isOperandLegal(), and reserveReg().
reserveReg()
void llvm::MachineRegisterInfo::reserveReg (MCRegister PhysReg, const TargetRegisterInfo * TRI) inline
reserveReg – Mark a register as reserved so checks like isAllocatable will not suggest using it.
This should not be used during the middle of a function walk, or when liveness info is available.
Definition at line 920 of file MachineRegisterInfo.h.
References assert(), llvm::RISCVFenceField::R, reservedRegsFrozen(), and TRI.
Referenced by llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR().
resetDelegate()
void llvm::MachineRegisterInfo::resetDelegate (Delegate * delegate) inline
Definition at line 160 of file MachineRegisterInfo.h.
References assert(), llvm::SmallPtrSetImpl< PtrType >::count(), and llvm::SmallPtrSetImpl< PtrType >::erase().
setCalleeSavedRegs()
void MachineRegisterInfo::setCalleeSavedRegs (ArrayRef< MCPhysReg > CSRs)
Sets the updated Callee Saved Registers list.
Notice that it will override ant previously disabled/saved CSRs.
Definition at line 632 of file MachineRegisterInfo.cpp.
References llvm::append_range().
Referenced by llvm::MIRParserImpl::parseRegisterInfo(), and llvm::AArch64RegisterInfo::UpdateCustomCalleeSavedRegs().
setRegAllocationHint()
void llvm::MachineRegisterInfo::setRegAllocationHint (Register VReg, unsigned Type, Register PrefReg) inline
setRegAllocationHint - Specify a register allocation hint for the specified virtual register.
This is typically used by target, and in case of an earlier hint it will be overwritten.
Definition at line 792 of file MachineRegisterInfo.h.
References assert(), llvm::IndexedMap< T, ToIndexT >::clear(), llvm::Register::isVirtual(), and Type.
Referenced by llvm::SIInstrInfo::getAddNoCarry(), setSimpleHint(), and llvm::ARMBaseRegisterInfo::updateRegAllocHint().
setRegBank()
void MachineRegisterInfo::setRegBank (Register Reg, const RegisterBank & RegBank)
Set the register bank to RegBank for Reg.
Definition at line 62 of file MachineRegisterInfo.cpp.
Referenced by llvm::RegBankSelect::applyMapping(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::AMDGPURegisterBankInfo::applyMappingMAD_64_32(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), llvm::RegBankSelect::assignInstr(), llvm::AMDGPURegisterBankInfo::buildReadFirstLane(), constrainRegToBank(), llvm::RegisterBankInfo::OperandsMapper::createVRegs(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), fixupPHIOpBanks(), AMDGPURegBankCombinerHelper::getAsVgpr(), reinsertVectorIndexAdd(), llvm::MipsRegisterBankInfo::setRegBank(), llvm::CombinerHelper::setRegBank(), llvm::MIRParserImpl::setupRegisterInfo(), and llvm::AMDGPURegisterBankInfo::split64BitValueForMapping().
setRegClass()
void MachineRegisterInfo::setRegClass (Register Reg, const TargetRegisterClass * RC)
setRegClass - Set the register class of the specified virtual register.
Definition at line 57 of file MachineRegisterInfo.cpp.
References assert(), and llvm::TargetRegisterClass::isAllocatable().
Referenced by llvm::RegisterBankInfo::constrainGenericRegister(), constrainRegClass(), createNewIdReg(), createTypeVReg(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::SITargetLowering::finalizeLowering(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldVGPRCopyIntoRegSequence(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::insertAssignInstr(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), processInstrsWithTypeFolding(), processSwitches(), propagateSPIRVType(), recomputeRegClass(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), llvm::InstructionSelect::runOnMachineFunction(), llvm::MIRParserImpl::setupRegisterInfo(), and tryChangeVGPRtoSGPRinCopy().
setRegClassOrRegBank()
void llvm::MachineRegisterInfo::setRegClassOrRegBank (Register Reg, const RegClassOrRegBank & RCOrRB) inline
Definition at line 705 of file MachineRegisterInfo.h.
Referenced by llvm::CombinerHelper::applyCombineUnmergeMergeToPlainValues(), and constrainRegAttrs().
setSimpleHint()
void llvm::MachineRegisterInfo::setSimpleHint (Register VReg, Register PrefReg) inline
Specify the preferred (target independent) register allocation hint for the specified virtual register.
Definition at line 808 of file MachineRegisterInfo.h.
References setRegAllocationHint().
Referenced by emitLoadM0FromVGPRLoop(), emitLoadSRsrcFromVGPRLoop(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), and llvm::MIRParserImpl::setupRegisterInfo().
setType()
void MachineRegisterInfo::setType (Register VReg, LLT Ty)
Set the low-level type of VReg to Ty.
Definition at line 179 of file MachineRegisterInfo.cpp.
References llvm::IndexedMap< T, ToIndexT >::grow().
Referenced by llvm::SITargetLowering::allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), allocateVGPR32Input(), llvm::RegisterBankInfo::applyDefaultMapping(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::buildBuiltinVariableLoad(), buildCopyFromRegs(), llvm::buildEnqueueKernel(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::AMDGPURegisterBankInfo::buildReadFirstLane(), cloneVirtualRegister(), constrainRegAttrs(), createGenericVirtualRegister(), llvm::getFunctionLiveInPhysReg(), llvm::SPIRV::lowerBuiltin(), processInstrsWithTypeFolding(), and setRegsToType().
shouldTrackSubRegLiveness() [1/2]
bool llvm::MachineRegisterInfo::shouldTrackSubRegLiveness (const TargetRegisterClass & RC) const inline
Returns true if liveness for register class RC should be tracked at the subregister level.
Definition at line 226 of file MachineRegisterInfo.h.
References llvm::TargetRegisterClass::HasDisjunctSubRegs, and subRegLivenessEnabled().
Referenced by shouldTrackSubRegLiveness().
shouldTrackSubRegLiveness() [2/2]
bool llvm::MachineRegisterInfo::shouldTrackSubRegLiveness (Register VReg) const inline
Definition at line 229 of file MachineRegisterInfo.h.
References assert(), getRegClass(), llvm::Register::isVirtual(), and shouldTrackSubRegLiveness().
subRegLivenessEnabled()
bool llvm::MachineRegisterInfo::subRegLivenessEnabled () const inline
Definition at line 233 of file MachineRegisterInfo.h.
Referenced by llvm::LiveIntervals::addKillFlags(), and shouldTrackSubRegLiveness().
tracksLiveness()
bool llvm::MachineRegisterInfo::tracksLiveness () const inline
tracksLiveness - Returns true when tracking register liveness accurately.
(see MachineFUnctionProperties::Property description for details)
Definition at line 209 of file MachineRegisterInfo.h.
References llvm::MachineFunction::getProperties(), llvm::MachineFunctionProperties::hasProperty(), and llvm::MachineFunctionProperties::TracksLiveness.
Referenced by llvm::rdf::DataFlowGraph::build(), canRenameUpToDef(), llvm::MIRPrinter::convert(), llvm::AArch64InstrInfo::getOutlinableRanges(), INITIALIZE_PASS(), llvm::ARMBaseInstrInfo::isMBBSafeToOutlineFrom(), llvm::BranchFolder::OptimizeFunction(), llvm::MIRParserImpl::parseRegisterInfo(), and llvm::MachineBasicBlock::print().
updateDbgUsersToReg()
void llvm::MachineRegisterInfo::updateDbgUsersToReg (MCRegister OldReg, MCRegister NewReg, ArrayRef< MachineInstr * > Users) const inline
updateDbgUsersToReg - Update a collection of debug instructions to refer to the designated register.
Definition at line 853 of file MachineRegisterInfo.h.
References assert(), getTargetRegisterInfo(), llvm_unreachable, MI, llvm::TargetRegisterInfo::regsOverlap(), and Users.
use_begin()
use_iterator llvm::MachineRegisterInfo::use_begin (Register RegNo) const inline
Definition at line 486 of file MachineRegisterInfo.h.
Referenced by processSwitches(), use_empty(), and use_operands().
use_bundle_begin()
use_bundle_iterator llvm::MachineRegisterInfo::use_bundle_begin (Register RegNo) const inline
Definition at line 515 of file MachineRegisterInfo.h.
Referenced by use_bundles().
use_bundle_end()
static use_bundle_iterator llvm::MachineRegisterInfo::use_bundle_end () inline static
Definition at line 518 of file MachineRegisterInfo.h.
Referenced by use_bundles().
use_bundle_nodbg_begin()
use_bundle_nodbg_iterator llvm::MachineRegisterInfo::use_bundle_nodbg_begin (Register RegNo) const inline
Definition at line 574 of file MachineRegisterInfo.h.
Referenced by use_nodbg_bundles().
use_bundle_nodbg_end()
static use_bundle_nodbg_iterator llvm::MachineRegisterInfo::use_bundle_nodbg_end () inline static
Definition at line 577 of file MachineRegisterInfo.h.
Referenced by use_nodbg_bundles().
use_bundles()
iterator_range<use_bundle_iterator> llvm::MachineRegisterInfo::use_bundles (Register Reg) const inline
Definition at line 522 of file MachineRegisterInfo.h.
References llvm::make_range(), use_bundle_begin(), and use_bundle_end().
use_empty()
bool llvm::MachineRegisterInfo::use_empty (Register RegNo) const inline
use_empty - Return true if there are no instructions using the specified register.
Definition at line 528 of file MachineRegisterInfo.h.
References use_begin(), and use_end().
Referenced by llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::NVPTXFrameLowering::emitPrologue(), foldConstantsIntoIntrinsics(), GetInitialOffset(), llvm::PPCInstrInfo::optimizeCompareInstr(), rematerializeCheapDef(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), and llvm::SIMachineFunctionInfo::usesAGPRs().
use_end()
static use_iterator llvm::MachineRegisterInfo::use_end () inline static
Definition at line 489 of file MachineRegisterInfo.h.
Referenced by use_empty(), and use_operands().
use_instr_begin()
use_instr_iterator llvm::MachineRegisterInfo::use_instr_begin (Register RegNo) const inline
Definition at line 499 of file MachineRegisterInfo.h.
Referenced by foldVGPRCopyIntoRegSequence(), generateAssignInstrs(), INITIALIZE_PASS(), matchAArch64MulConstCombine(), llvm::CombinerHelper::matchCombineInsertVecElts(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), processInstr(), processInstrsWithTypeFolding(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), and use_instructions().
use_instr_end()
static use_instr_iterator llvm::MachineRegisterInfo::use_instr_end () inline static
Definition at line 502 of file MachineRegisterInfo.h.
Referenced by llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::SelectionDAGISel::runOnMachineFunction(), and use_instructions().
use_instr_nodbg_begin()
use_instr_nodbg_iterator llvm::MachineRegisterInfo::use_instr_nodbg_begin (Register RegNo) const inline
Definition at line 557 of file MachineRegisterInfo.h.
Referenced by hasAtMostUserInstrs(), hasMoreUses(), llvm::AArch64InstrInfo::isExtendLikelyToBeFolded(), isSimpleIf(), llvm::CombinerHelper::matchExtendThroughPhis(), tryToSimplifyUADDO(), use_nodbg_instructions(), and verifyCFIntrinsic().
use_instr_nodbg_end()
static use_instr_nodbg_iterator llvm::MachineRegisterInfo::use_instr_nodbg_end () inline static
Definition at line 560 of file MachineRegisterInfo.h.
Referenced by hasAtMostUserInstrs(), hasMoreUses(), isSimpleIf(), and use_nodbg_instructions().
use_instructions()
iterator_range<use_instr_iterator> llvm::MachineRegisterInfo::use_instructions (Register Reg) const inline
Definition at line 507 of file MachineRegisterInfo.h.
References llvm::make_range(), use_instr_begin(), and use_instr_end().
Referenced by llvm::GISelChangeObserver::changingAllUsesOfReg(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), dumpUses(), llvm::PeelingModuloScheduleExpander::filterInstructions(), AMDGPURegBankCombinerHelper::getAsVgpr(), isCopyFeedingInvariantStore(), isDefLiveOut(), markUsesInDebugValueAsUndef(), llvm::CombinerHelper::matchCombineTruncOfShift(), and llvm::PeelingModuloScheduleExpander::rewriteUsesOf().
use_nodbg_begin()
use_nodbg_iterator llvm::MachineRegisterInfo::use_nodbg_begin (Register RegNo) const inline
Definition at line 540 of file MachineRegisterInfo.h.
Referenced by oneUseDominatesOtherUses(), use_nodbg_empty(), and use_nodbg_operands().
use_nodbg_bundles()
iterator_range<use_bundle_nodbg_iterator> llvm::MachineRegisterInfo::use_nodbg_bundles (Register Reg) const inline
Definition at line 582 of file MachineRegisterInfo.h.
References llvm::make_range(), use_bundle_nodbg_begin(), and use_bundle_nodbg_end().
use_nodbg_empty()
bool llvm::MachineRegisterInfo::use_nodbg_empty (Register RegNo) const inline
use_nodbg_empty - Return true if there are no non-Debug instructions using the specified register.
Definition at line 588 of file MachineRegisterInfo.h.
References use_nodbg_begin(), and use_nodbg_end().
Referenced by llvm::PPCInstrInfo::combineRLWINM(), EmitLiveInCopies(), llvm::SIInstrInfo::FoldImmediate(), llvm::PPCInstrInfo::FoldImmediate(), llvm::isTriviallyDead(), llvm::CombinerHelper::matchCombineUnmergeWithDeadLanesToTrunc(), llvm::SIInstrInfo::moveFlatAddrToVGPR(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), and llvm::LiveVariables::recomputeForSingleDefVirtReg().
use_nodbg_end()
static use_nodbg_iterator llvm::MachineRegisterInfo::use_nodbg_end () inline static
Definition at line 543 of file MachineRegisterInfo.h.
Referenced by use_nodbg_empty(), and use_nodbg_operands().
use_nodbg_instructions()
iterator_range<use_instr_nodbg_iterator> llvm::MachineRegisterInfo::use_nodbg_instructions (Register Reg) const inline
Definition at line 565 of file MachineRegisterInfo.h.
References llvm::make_range(), use_instr_nodbg_begin(), and use_instr_nodbg_end().
Referenced by allUsesHaveSourceMods(), llvm::PPCRegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), hasOneNonDBGUser(), INITIALIZE_PASS(), llvm::CombinerHelper::matchCombineDivRem(), llvm::CombinerHelper::matchCombineExtendingLoads(), llvm::CombinerHelper::matchExtractAllEltsFromBuildVector(), matchFConstantToConstant(), matchFoldGlobalOffset(), llvm::CombinerHelper::matchPtrAddImmedChain(), resultDependsOnExec(), and tryToSimplifyUADDO().
use_nodbg_operands()
iterator_range<use_nodbg_iterator> llvm::MachineRegisterInfo::use_nodbg_operands (Register Reg) const inline
Definition at line 548 of file MachineRegisterInfo.h.
References llvm::make_range(), use_nodbg_begin(), and use_nodbg_end().
Referenced by llvm::DeadLaneDetector::computeSubRegisterLaneBitInfo(), dominatesAllUsesOf(), llvm::execMayBeModifiedBeforeAnyUse(), findOnlyInterestingUse(), findSingleRegUse(), findUseBetween(), hasOneNonDBGUse(), hasOneUse(), INITIALIZE_PASS(), oneUseDominatesOtherUses(), llvm::SystemZELFFrameLowering::processFunctionBeforeFrameFinalized(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), replaceDominatedUses(), rescheduleCanonically(), and llvm::LiveIntervals::shrinkToUses().
use_operands()
iterator_range<use_iterator> llvm::MachineRegisterInfo::use_operands (Register Reg) const inline
Definition at line 491 of file MachineRegisterInfo.h.
References llvm::make_range(), use_begin(), and use_end().
Referenced by llvm::CombinerHelper::applyCombineExtendingLoads(), llvm::MachineInstr::changeDebugValuesDefReg(), clearKillFlags(), llvm::ModuloScheduleExpander::expand(), llvm::RISCVInstrInfo::hasAllNBitUsers(), hasOneUse(), hasUseAfterLoop(), llvm::PeelSingleBlockLoop(), propagateLocalCopies(), replaceRegUsesAfterLoop(), llvm::salvageDebugInfo(), llvm::TailDuplicator::tailDuplicateAndUpdate(), and tryToSimplifyUADDO().
verifyUseList()
void MachineRegisterInfo::verifyUseList (Register Reg) const
Verify the sanity of the use list for Reg.
Definition at line 217 of file MachineRegisterInfo.cpp.
References assert(), llvm::errs(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), getTargetRegisterInfo(), llvm::MachineOperand::isReg(), M, MI, llvm::printReg(), and reg_operands().
Referenced by clearVirtRegs(), and verifyUseLists().
verifyUseLists()
void MachineRegisterInfo::verifyUseLists () const
Verify the use list of all registers.
Definition at line 255 of file MachineRegisterInfo.cpp.
References llvm::numbers::e, getNumVirtRegs(), getTargetRegisterInfo(), i, llvm::Register::index2VirtReg(), and verifyUseList().
Friends And Related Function Documentation
defusechain_instr_iterator
template<bool , bool , bool , bool , bool , bool > friend class defusechain_instr_iterator friend
Definition at line 297 of file MachineRegisterInfo.h.
defusechain_iterator
template<bool , bool , bool , bool , bool , bool > friend class defusechain_iterator friend
Definition at line 291 of file MachineRegisterInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineRegisterInfo.h
lib/CodeGen/MachineRegisterInfo.cpp