LLVM: llvm::detail::BCRecordCoding< BCArray< ElementTy > > Class Template Reference
llvm::detail::BCRecordCoding< BCArray< ElementTy > > Class Template Reference
Helper class for dealing with an array at the end of a record.
#include "llvm/Bitcode/BitcodeConvenience.h"
Static Public Member Functions
template<typename BufferTy >
static void emit (llvm::BitstreamWriter &Stream, BufferTy &buffer, unsigned code, StringRef data)
template<typename BufferTy , typename ArrayTy >
static void emit (llvm::BitstreamWriter &Stream, BufferTy &buffer, unsigned code, const ArrayTy &array)
template<typename BufferTy , typename ElementDataTy , typename... DataTy>
static void emit (llvm::BitstreamWriter &Stream, BufferTy &buffer, unsigned code, ElementDataTy element, DataTy... data)
template<typename BufferTy >
static void emit (llvm::BitstreamWriter &Stream, BufferTy &Buffer, unsigned code, std::nullopt_t)
template<typename T >
static void read (ArrayRef< T > Buffer, ArrayRef< T > &rawData)
template<typename T , typename ArrayTy >
static void read (ArrayRef< T > buffer, ArrayTy &array)
template<typename T >
static void read (ArrayRef< T > buffer, std::nullopt_t)
template<typename T >
static void read (ArrayRef< T > buffer)=delete
Detailed Description
template<typename ElementTy>
class llvm::detail::BCRecordCoding< BCArray< ElementTy > >
Helper class for dealing with an array at the end of a record.
See also
BCRecordLayout::emitRecord
Definition at line 252 of file BitcodeConvenience.h.
Member Function Documentation
emit() [1/4]
template<typename ElementTy > template<typename BufferTy , typename ArrayTy > static void llvm::detail::BCRecordCoding< BCArray< ElementTy > >::emit (llvm::BitstreamWriter & Stream, BufferTy & buffer, unsigned code, const ArrayTy & array) inline static
Definition at line 262 of file BitcodeConvenience.h.
References code, copy, and llvm::BitstreamWriter::EmitRecordWithAbbrev().
emit() [2/4]
template<typename ElementTy > template<typename BufferTy , typename ElementDataTy , typename... DataTy> static void llvm::detail::BCRecordCoding< BCArray< ElementTy > >::emit (llvm::BitstreamWriter & Stream, BufferTy & buffer, unsigned code, ElementDataTy element, DataTy... data) inline static
Definition at line 274 of file BitcodeConvenience.h.
References code, and llvm::detail::BCRecordCoding< ElementTy, Fields >::emit().
emit() [3/4]
template<typename ElementTy > template<typename BufferTy > static void llvm::detail::BCRecordCoding< BCArray< ElementTy > >::emit (llvm::BitstreamWriter & Stream, BufferTy & Buffer, unsigned code, std::nullopt_t) inline static
Definition at line 281 of file BitcodeConvenience.h.
References code, and llvm::BitstreamWriter::EmitRecordWithAbbrev().
emit() [4/4]
template<typename ElementTy > template<typename BufferTy > static void llvm::detail::BCRecordCoding< BCArray< ElementTy > >::emit (llvm::BitstreamWriter & Stream, BufferTy & buffer, unsigned code, StringRef data) inline static
Definition at line 255 of file BitcodeConvenience.h.
References code, and llvm::BitstreamWriter::EmitRecordWithArray().
read() [1/4]
template<typename ElementTy > template<typename T > static void llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read (ArrayRef< T > buffer) static delete
read() [2/4]
template<typename ElementTy > template<typename T > static void llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read (ArrayRef< T > Buffer, ArrayRef< T > & rawData) inline static
Definition at line 287 of file BitcodeConvenience.h.
read() [3/4]
template<typename ElementTy > template<typename T , typename ArrayTy > static void llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read (ArrayRef< T > buffer, ArrayTy & array) inline static
Definition at line 292 of file BitcodeConvenience.h.
References llvm::ArrayRef< T >::begin(), convert, llvm::ArrayRef< T >::end(), and llvm::map_iterator().
read() [4/4]
template<typename ElementTy > template<typename T > static void llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read (ArrayRef< T > buffer, std::nullopt_t) inline static
Definition at line 297 of file BitcodeConvenience.h.
The documentation for this class was generated from the following file:
include/llvm/Bitcode/BitcodeConvenience.h