LLVM: llvm::object::content_iterator< content_type > Class Template Reference
llvm::object::content_iterator< content_type > Class Template Reference
#include "llvm/Object/SymbolicFile.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = content_type
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
content_iterator (content_type symb)
const content_type * operator-> () const
const content_type & operator* () const
bool operator== (const content_iterator &other) const
bool operator!= (const content_iterator &other) const
content_iterator & operator++ ()
Detailed Description
template<class content_type>
class llvm::object::content_iterator< content_type >
Definition at line 69 of file SymbolicFile.h.
Member Typedef Documentation
difference_type
template<class content_type > using llvm::object::content_iterator< content_type >::difference_type = std::ptrdiff_t
Definition at line 75 of file SymbolicFile.h.
iterator_category
template<class content_type > using llvm::object::content_iterator< content_type >::iterator_category = std::forward_iterator_tag
Definition at line 73 of file SymbolicFile.h.
pointer
template<class content_type > using llvm::object::content_iterator< content_type >::pointer = value_type *
Definition at line 76 of file SymbolicFile.h.
reference
template<class content_type > using llvm::object::content_iterator< content_type >::reference = value_type &
Definition at line 77 of file SymbolicFile.h.
value_type
template<class content_type > using llvm::object::content_iterator< content_type >::value_type = content_type
Definition at line 74 of file SymbolicFile.h.
Constructor & Destructor Documentation
content_iterator()
template<class content_type > llvm::object::content_iterator< content_type >::content_iterator (content_type symb) inline
Definition at line 79 of file SymbolicFile.h.
Member Function Documentation
operator!=()
template<class content_type > bool llvm::object::content_iterator< content_type >::operator!= (const content_iterator< content_type > & other) const inline
Definition at line 89 of file SymbolicFile.h.
operator*()
template<class content_type > const content_type& llvm::object::content_iterator< content_type >::operator* () const inline
Definition at line 83 of file SymbolicFile.h.
Referenced by llvm::object::elf_section_iterator::operator*(), llvm::object::symbol_iterator::operator*(), llvm::object::elf_relocation_iterator::operator*(), and llvm::object::symbol_iterator::operator->().
operator++()
template<class content_type > content_iterator& llvm::object::content_iterator< content_type >::operator++ () inline
Definition at line 93 of file SymbolicFile.h.
operator->()
template<class content_type > const content_type* llvm::object::content_iterator< content_type >::operator-> () const inline
Definition at line 81 of file SymbolicFile.h.
Referenced by llvm::object::elf_section_iterator::operator->(), and llvm::object::elf_relocation_iterator::operator->().
operator==()
template<class content_type > bool llvm::object::content_iterator< content_type >::operator== (const content_iterator< content_type > & other) const inline
Definition at line 85 of file SymbolicFile.h.
The documentation for this class was generated from the following file:
include/llvm/Object/SymbolicFile.h