LLVM: llvm::VECustomDAG Class Reference
llvm::VECustomDAG Class Reference
#include "Target/VE/VECustomDAG.h"
Public Member Functions
SelectionDAG * getDAG () const
VECustomDAG (SelectionDAG &DAG, SDLoc DL)
VECustomDAG (SelectionDAG &DAG, SDValue WhereOp)
VECustomDAG (SelectionDAG &DAG, const SDNode *WhereN)
SDValue getNode (unsigned OC, SDVTList VTL, ArrayRef< SDValue > OpV, std::optional< SDNodeFlags > Flags=std::nullopt) const
getNode {
SDValue getNode (unsigned OC, ArrayRef< EVT > ResVT, ArrayRef< SDValue > OpV, std::optional< SDNodeFlags > Flags=std::nullopt) const
SDValue getNode (unsigned OC, EVT ResVT, ArrayRef< SDValue > OpV, std::optional< SDNodeFlags > Flags=std::nullopt) const
SDValue getUNDEF (EVT VT) const
SDValue getLegalReductionOpVVP (unsigned VVPOpcode, EVT ResVT, SDValue StartV, SDValue VectorV, SDValue Mask, SDValue AVL, SDNodeFlags Flags) const
} getNode
SDValue getUnpack (EVT DestVT, SDValue Vec, PackElem Part, SDValue AVL) const
} Legalizing getNode
SDValue getPack (EVT DestVT, SDValue LoVec, SDValue HiVec, SDValue AVL) const
SDValue getMergeValues (ArrayRef< SDValue > Values) const
} Packing
SDValue getConstant (uint64_t Val, EVT VT, bool IsTarget=false, bool IsOpaque=false) const
SDValue getConstantMask (Packing Packing, bool AllTrue) const
SDValue getMaskBroadcast (EVT ResultVT, SDValue Scalar, SDValue AVL) const
SDValue getBroadcast (EVT ResultVT, SDValue Scalar, SDValue AVL) const
SDValue annotateLegalAVL (SDValue AVL) const
VETargetMasks getTargetSplitMask (SDValue RawMask, SDValue RawAVL, PackElem Part) const
SDValue getSplitPtrOffset (SDValue Ptr, SDValue ByteStride, PackElem Part) const
SDValue getSplitPtrStride (SDValue PackStride) const
SDValue getGatherScatterAddress (SDValue BasePtr, SDValue Scale, SDValue Index, SDValue Mask, SDValue AVL) const
EVT getVectorVT (EVT ElemVT, unsigned NumElems) const
Detailed Description
Definition at line 142 of file VECustomDAG.h.
Constructor & Destructor Documentation
VECustomDAG() [1/3]
llvm::VECustomDAG::VECustomDAG (SelectionDAG & DAG, SDLoc DL) inline
Definition at line 149 of file VECustomDAG.h.
References DL.
VECustomDAG() [2/3]
llvm::VECustomDAG::VECustomDAG (SelectionDAG & DAG, SDValue WhereOp) inline
Definition at line 151 of file VECustomDAG.h.
References DL.
VECustomDAG() [3/3]
llvm::VECustomDAG::VECustomDAG (SelectionDAG & DAG, const SDNode * WhereN) inline
Definition at line 153 of file VECustomDAG.h.
References DL.
Member Function Documentation
annotateLegalAVL()
SDValue llvm::VECustomDAG::annotateLegalAVL (SDValue AVL) const
Definition at line 474 of file VECustomDAG.cpp.
References getNode(), llvm::SDValue::getValueType(), llvm::isLegalAVL(), and llvm::VEISD::LEGALAVL.
Referenced by getTargetSplitMask(), and llvm::VETargetLowering::legalizePackedAVL().
getBroadcast()
SDValue llvm::VECustomDAG::getBroadcast (EVT ResultVT, SDValue Scalar, SDValue AVL) const
Definition at line 451 of file VECustomDAG.cpp.
References assert(), llvm::MVT::f32, getMaskBroadcast(), getNode(), llvm::MVT::i32, llvm::MVT::i64, llvm::isMaskType(), llvm::isPackedVectorType(), llvm::EVT::isVector(), llvm::VEISD::REPL_F32, llvm::VEISD::REPL_I32, and llvm::VEISD::VEC_BROADCAST.
Referenced by getGatherScatterAddress(), getMaskBroadcast(), and llvm::VETargetLowering::lowerBUILD_VECTOR().
getConstant()
SDValue llvm::VECustomDAG::getConstant (uint64_t Val, EVT VT, bool IsTarget = false, bool IsOpaque = false) const
Definition at line 404 of file VECustomDAG.cpp.
References llvm::SelectionDAG::getConstant().
Referenced by getConstantMask(), llvm::getLoadStoreStride(), getSplitPtrStride(), getTargetSplitMask(), llvm::VETargetLowering::legalizePackedAVL(), llvm::VETargetLowering::lowerBUILD_VECTOR(), llvm::VETargetLowering::lowerToVVP(), llvm::VETargetLowering::lowerVVP_GATHER_SCATTER(), llvm::VETargetLowering::lowerVVP_LOAD_STORE(), and llvm::VETargetLowering::splitMaskArithmetic().
getConstantMask()
SDValue llvm::VECustomDAG::getConstantMask (Packing Packing, bool AllTrue) const
Definition at line 409 of file VECustomDAG.cpp.
References getConstant(), llvm::SelectionDAG::getConstant(), llvm::getLegalVectorType(), getNode(), llvm::SelectionDAG::getNOT(), llvm::MVT::i1, llvm::MVT::i32, llvm::tgtok::TrueVal, and llvm::VEISD::VEC_BROADCAST.
Referenced by getMaskBroadcast(), getTargetSplitMask(), llvm::VETargetLowering::lowerToVVP(), llvm::VETargetLowering::lowerVVP_GATHER_SCATTER(), and llvm::VETargetLowering::lowerVVP_LOAD_STORE().
getDAG()
SelectionDAG* llvm::VECustomDAG::getDAG () const inline
Definition at line 147 of file VECustomDAG.h.
getGatherScatterAddress()
SDValue llvm::VECustomDAG::getGatherScatterAddress (SDValue BasePtr, SDValue Scale, SDValue Index, SDValue Mask, SDValue AVL) const
Definition at line 536 of file VECustomDAG.cpp.
References getBroadcast(), getNode(), Index, llvm::isNullConstant(), llvm::isOneConstant(), and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::VETargetLowering::lowerVVP_GATHER_SCATTER().
getLegalReductionOpVVP()
SDValue llvm::VECustomDAG::getLegalReductionOpVVP (unsigned VVPOpcode, EVT ResVT, SDValue StartV, SDValue VectorV, SDValue Mask, SDValue AVL, SDNodeFlags Flags) const
} getNode
Legalizing getNode {
Definition at line 562 of file VECustomDAG.cpp.
References assert(), getNode(), llvm::getScalarReductionOpcode(), llvm::SDValue::getValueType(), llvm::hasReductionStartParam(), llvm::isMaskType(), and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::VETargetLowering::lowerToVVP().
getMaskBroadcast()
SDValue llvm::VECustomDAG::getMaskBroadcast (EVT ResultVT, SDValue Scalar, SDValue AVL) const
Definition at line 422 of file VECustomDAG.cpp.
References assert(), getBroadcast(), llvm::SelectionDAG::getConstant(), getConstantMask(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::getTypePacking(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::i1, llvm::MVT::i32, llvm::ISD::SETNE, and llvm::VEISD::VEC_BROADCAST.
Referenced by getBroadcast().
getMergeValues()
SDValue llvm::VECustomDAG::getMergeValues (ArrayRef< SDValue > Values) const inline
} Packing
Definition at line 194 of file VECustomDAG.h.
References DL, and llvm::SelectionDAG::getMergeValues().
Referenced by llvm::VETargetLowering::lowerVVP_GATHER_SCATTER(), and llvm::VETargetLowering::lowerVVP_LOAD_STORE().
getNode() [1/3]
SDValue llvm::VECustomDAG::getNode (unsigned OC, ArrayRef< EVT > ResVT, ArrayRef< SDValue > OpV, std::optional< SDNodeFlags > Flags = std::nullopt) const inline
Definition at line 164 of file VECustomDAG.h.
References DL, llvm::SelectionDAG::getNode(), N, and llvm::SystemZISD::OC.
getNode() [2/3]
SDValue llvm::VECustomDAG::getNode (unsigned OC, EVT ResVT, ArrayRef< SDValue > OpV, std::optional< SDNodeFlags > Flags = std::nullopt) const inline
Definition at line 172 of file VECustomDAG.h.
References DL, llvm::SelectionDAG::getNode(), N, and llvm::SystemZISD::OC.
getNode() [3/3]
SDValue llvm::VECustomDAG::getNode (unsigned OC, SDVTList VTL, ArrayRef< SDValue > OpV, std::optional< SDNodeFlags > Flags = std::nullopt) const inline
getNode {
Definition at line 156 of file VECustomDAG.h.
References DL, llvm::SelectionDAG::getNode(), N, and llvm::SystemZISD::OC.
Referenced by annotateLegalAVL(), getBroadcast(), getConstantMask(), getGatherScatterAddress(), getLegalReductionOpVVP(), getSplitPtrOffset(), getSplitPtrStride(), getTargetSplitMask(), llvm::VETargetLowering::legalizePackedAVL(), llvm::VETargetLowering::lowerBUILD_VECTOR(), llvm::VETargetLowering::lowerToVVP(), llvm::VETargetLowering::lowerVVP_GATHER_SCATTER(), llvm::VETargetLowering::lowerVVP_LOAD_STORE(), llvm::VETargetLowering::splitMaskArithmetic(), llvm::VETargetLowering::splitPackedLoadStore(), and llvm::VETargetLowering::splitVectorOp().
getPack()
SDValue llvm::VECustomDAG::getPack (EVT DestVT, SDValue LoVec, SDValue HiVec, SDValue AVL) const
Definition at line 490 of file VECustomDAG.cpp.
References assert(), llvm::getAnnotatedNodeAVL(), llvm::SelectionDAG::getNode(), and llvm::VEISD::VEC_PACK.
Referenced by llvm::VETargetLowering::splitMaskArithmetic(), and llvm::VETargetLowering::splitVectorOp().
getSplitPtrOffset()
SDValue llvm::VECustomDAG::getSplitPtrOffset (SDValue Ptr, SDValue ByteStride, PackElem Part) const
Definition at line 521 of file VECustomDAG.cpp.
References llvm::ISD::ADD, getNode(), llvm::Hi, llvm::MVT::i64, and Ptr.
Referenced by llvm::VETargetLowering::splitPackedLoadStore().
getSplitPtrStride()
SDValue llvm::VECustomDAG::getSplitPtrStride (SDValue PackStride) const
Definition at line 530 of file VECustomDAG.cpp.
References getConstant(), getNode(), llvm::MVT::i32, llvm::MVT::i64, and llvm::ISD::SHL.
Referenced by llvm::VETargetLowering::splitPackedLoadStore().
getTargetSplitMask()
VETargetMasks llvm::VECustomDAG::getTargetSplitMask (SDValue RawMask, SDValue RawAVL, PackElem Part) const
Definition at line 498 of file VECustomDAG.cpp.
References llvm::ISD::ADD, annotateLegalAVL(), getConstant(), getConstantMask(), getNode(), getUnpack(), llvm::Hi, llvm::MVT::i32, llvm::Normal, llvm::ISD::SRL, and llvm::MVT::v256i1.
Referenced by llvm::VETargetLowering::splitPackedLoadStore(), and llvm::VETargetLowering::splitVectorOp().
getUNDEF()
SDValue llvm::VECustomDAG::getUNDEF (EVT VT) const inline
Definition at line 180 of file VECustomDAG.h.
References llvm::SelectionDAG::getUNDEF().
Referenced by llvm::VETargetLowering::lowerBUILD_VECTOR().
getUnpack()
SDValue llvm::VECustomDAG::getUnpack (EVT DestVT, SDValue Vec, PackElem Part, SDValue AVL) const
} Legalizing getNode
Packing {
Definition at line 480 of file VECustomDAG.cpp.
References assert(), llvm::getAnnotatedNodeAVL(), llvm::SelectionDAG::getNode(), llvm::Lo, llvm::SystemZISD::OC, llvm::VEISD::VEC_UNPACK_HI, and llvm::VEISD::VEC_UNPACK_LO.
Referenced by getTargetSplitMask(), llvm::VETargetLowering::splitMaskArithmetic(), llvm::VETargetLowering::splitPackedLoadStore(), and llvm::VETargetLowering::splitVectorOp().
getVectorVT()
EVT llvm::VECustomDAG::getVectorVT (EVT ElemVT, unsigned NumElems) const inline
Definition at line 216 of file VECustomDAG.h.
References llvm::SelectionDAG::getContext(), and llvm::EVT::getVectorVT().
The documentation for this class was generated from the following files:
lib/Target/VE/VECustomDAG.h
lib/Target/VE/VECustomDAG.cpp