LLVM: llvm::RegBankSelect Class Reference
llvm::RegBankSelect Class Reference
This pass implements the reg bank selector pass used in the GlobalISel pipeline.
#include "llvm/CodeGen/GlobalISel/RegBankSelect.h"
Classes
class EdgeInsertPoint
Insertion point on an edge.
class InsertPoint
Abstract class used to represent an insertion point in a CFG.
class InstrInsertPoint
Insertion point before or after an instruction.
class MappingCost
Helper class used to represent the cost for mapping an instruction.
class MBBInsertPoint
Insertion point at the beginning or end of a basic block.
class RepairingPlacement
Struct used to represent the placement of a repairing point for a given operand.
Public Types
enum Mode { Fast, Greedy }
List of the modes supported by the RegBankSelect pass.
Public Member Functions
RegBankSelect (char &PassID=ID, Mode RunningMode=Fast)
Create a RegBankSelect pass with the specified RunningMode.
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
MachineFunctionProperties getRequiredProperties () const override
MachineFunctionProperties getSetProperties () const override
MachineFunctionProperties getClearedProperties () const override
bool checkFunctionIsLegal (MachineFunction &MF) const
Check that our input is fully legal: we require the function to have the Legalized property, so it should be.
bool assignRegisterBanks (MachineFunction &MF)
Walk through MF and assign a register bank to every virtual register that are still mapped to nothing.
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Protected Member Functions
bool assignInstr (MachineInstr &MI)
Assign the register bank of each operand of MI.
void init (MachineFunction &MF)
Initialize the field members using MF.
bool assignmentMatch (Register Reg, const RegisterBankInfo::ValueMapping &ValMapping, bool &OnlyAssign) const
Check if Reg is already assigned what is described by ValMapping.
bool repairReg (MachineOperand &MO, const RegisterBankInfo::ValueMapping &ValMapping, RegBankSelect::RepairingPlacement &RepairPt, const iterator_range< SmallVectorImpl< Register >::const_iterator > &NewVRegs)
Insert repairing code for Reg as specified by ValMapping.
uint64_t getRepairCost (const MachineOperand &MO, const RegisterBankInfo::ValueMapping &ValMapping) const
Return the cost of the instruction needed to map MO to ValMapping.
const RegisterBankInfo::InstructionMapping & findBestMapping (MachineInstr &MI, RegisterBankInfo::InstructionMappings &PossibleMappings, SmallVectorImpl< RepairingPlacement > &RepairPts)
Find the best mapping for MI from PossibleMappings.
MappingCost computeMapping (MachineInstr &MI, const RegisterBankInfo::InstructionMapping &InstrMapping, SmallVectorImpl< RepairingPlacement > &RepairPts, const MappingCost *BestCost=nullptr)
Compute the cost of mapping MI with InstrMapping and compute the repairing placement for such mapping in RepairPts.
void tryAvoidingSplit (RegBankSelect::RepairingPlacement &RepairPt, const MachineOperand &MO, const RegisterBankInfo::ValueMapping &ValMapping) const
When RepairPt involves splitting to repair MO for the given ValMapping, try to change the way we repair such that the splitting is not required anymore.
bool applyMapping (MachineInstr &MI, const RegisterBankInfo::InstructionMapping &InstrMapping, SmallVectorImpl< RepairingPlacement > &RepairPts)
Apply Mapping to MI.
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes
const RegisterBankInfo * RBI = nullptr
Interface to the target lowering info related to register banks.
MachineRegisterInfo * MRI = nullptr
MRI contains all the register class/bank information that this pass uses and updates.
const TargetRegisterInfo * TRI = nullptr
Information on the register classes for the current function.
MachineBlockFrequencyInfo * MBFI = nullptr
Get the frequency of blocks.
MachineBranchProbabilityInfo * MBPI = nullptr
Get the frequency of the edges.
std::unique_ptr< MachineOptimizationRemarkEmitter > MORE
Current optimization remark emitter. Used to report failures.
MachineIRBuilder MIRBuilder
Helper class used for every code morphing.
Mode OptMode
Optimization mode of the pass.
const TargetPassConfig * TPC
Current target configuration. Controls how the pass handles errors.
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
This pass implements the reg bank selector pass used in the GlobalISel pipeline.
At the end of this pass, all register operands have been assigned
Definition at line 91 of file RegBankSelect.h.
Member Enumeration Documentation
Mode
enum llvm::RegBankSelect::Mode
List of the modes supported by the RegBankSelect pass.
Enumerator
Fast
Assign the register banks as fast as possible (default).
Greedy
Greedily minimize the cost of assigning register banks.
This should produce code of greater quality, but will require more compile time.
Definition at line 96 of file RegBankSelect.h.
Constructor & Destructor Documentation
RegBankSelect()
llvm::RegBankSelect::RegBankSelect (char & PassID = ID, Mode RunningMode = Fast)
Create a RegBankSelect pass with the specified RunningMode.
Member Function Documentation
applyMapping()
bool RegBankSelect::applyMapping (MachineInstr & MI, const RegisterBankInfo::InstructionMapping & InstrMapping, SmallVectorImpl< RepairingPlacement > & RepairPts) protected
Apply Mapping to MI.
RepairPts represents the different mapping action that need to happen for the mapping to be applied.
Returns
True if the mapping was applied sucessfully, false otherwise.
Definition at line 586 of file RegBankSelect.cpp.
References llvm::RegisterBankInfo::applyMapping(), assert(), llvm::RegisterBankInfo::ValueMapping::BreakDown, llvm::RegisterBankInfo::OperandsMapper::createVRegs(), llvm::dbgs(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::OperandsMapper::getVRegs(), llvm::RegBankSelect::RepairingPlacement::Impossible, llvm::RegBankSelect::RepairingPlacement::Insert, LLVM_DEBUG, llvm_unreachable, MI, MRI, llvm::RegBankSelect::RepairingPlacement::None, llvm::RegisterBankInfo::ValueMapping::NumBreakDowns, RBI, llvm::RegBankSelect::RepairingPlacement::Reassign, llvm::RegisterBankInfo::PartialMapping::RegBank, repairReg(), and llvm::MachineRegisterInfo::setRegBank().
Referenced by assignInstr().
assignInstr()
bool RegBankSelect::assignInstr (MachineInstr & MI) protected
Assign the register bank of each operand of MI.
Returns
True on success, false otherwise.
Definition at line 631 of file RegBankSelect.cpp.
References applyMapping(), assert(), computeMapping(), llvm::dbgs(), llvm::Sched::Fast, findBestMapping(), llvm::RegisterBankInfo::getInstrMapping(), llvm::RegisterBankInfo::getInstrPossibleMappings(), llvm::RegisterBankInfo::getRegBank(), llvm::RegBankSelect::MappingCost::ImpossibleCost(), llvm::isPreISelGenericOptimizationHint(), LLVM_DEBUG, MI, MRI, OptMode, RBI, llvm::MachineRegisterInfo::setRegBank(), TRI, and llvm::RegisterBankInfo::InstructionMapping::verify().
Referenced by assignRegisterBanks().
assignmentMatch()
bool RegBankSelect::assignmentMatch (Register Reg, const RegisterBankInfo::ValueMapping & ValMapping, bool & OnlyAssign) const protected
Check if Reg is already assigned what is described by ValMapping.
OnlyAssign == true means that Reg just needs to be assigned a register bank. I.e., no repairing is necessary to have the assignment match.
Definition at line 110 of file RegBankSelect.cpp.
References assert(), llvm::RegisterBankInfo::ValueMapping::BreakDown, llvm::dbgs(), llvm::RegisterBankInfo::getRegBank(), LLVM_DEBUG, MRI, llvm::RegisterBankInfo::ValueMapping::NumBreakDowns, RBI, llvm::RegisterBankInfo::PartialMapping::RegBank, and TRI.
Referenced by computeMapping().
assignRegisterBanks()
bool RegBankSelect::assignRegisterBanks (MachineFunction & MF)
Walk through MF and assign a register bank to every virtual register that are still mapped to nothing.
The target needs to provide a RegisterBankInfo and in particular override RegisterBankInfo::getInstrMapping.
Simplified algo:
RBI = MF.subtarget.getRegBankInfo()
MIRBuilder.setMF(MF)
for each bb in MF
  for each inst in bb
    MIRBuilder.setInstr(inst)
    MappingCosts = RBI.getMapping(inst);
    Idx = findIdxOfMinCost(MappingCosts)
    CurRegBank = MappingCosts[Idx].RegBank
    MRI.setRegBank(inst.getOperand(0).getReg(), CurRegBank)
    for each argument in inst
      if (CurRegBank != argument.RegBank)
        ArgReg = argument.getReg()
        Tmp = MRI.createNewVirtual(MRI.getSize(ArgReg), CurRegBank)
        MIRBuilder.buildInstr(COPY, Tmp, ArgReg)
        inst.getOperand(argument.getOperandNo()).setReg(Tmp)
Definition at line 679 of file RegBankSelect.cpp.
References assignInstr(), llvm::MachineBasicBlock::instrs(), llvm::isTargetSpecificOpcode(), llvm::make_pointer_range(), MBB, MI, MIRBuilder, MORE, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::reportGISelFailure(), llvm::reverse(), llvm::MachineIRBuilder::setMBB(), and TPC.
Referenced by runOnMachineFunction().
checkFunctionIsLegal()
bool RegBankSelect::checkFunctionIsLegal (MachineFunction & MF) const
Check that our input is fully legal: we require the function to have the Legalized property, so it should be.
FIXME: This should be in the MachineVerifier.
Definition at line 719 of file RegBankSelect.cpp.
References llvm::DisableGISelLegalityCheck, llvm::machineFunctionIsIllegal(), MI, MORE, llvm::reportGISelFailure(), and TPC.
Referenced by runOnMachineFunction().
computeMapping()
RegBankSelect::MappingCost RegBankSelect::computeMapping (MachineInstr & MI, const RegisterBankInfo::InstructionMapping & InstrMapping, SmallVectorImpl< RepairingPlacement > & RepairPts, const MappingCost * BestCost = nullptr) protected
Compute the cost of mapping MI with InstrMapping and compute the repairing placement for such mapping in RepairPts.
BestCost is used to specify when the cost becomes too high and thus it is not worth computing the RepairPts. Moreover if BestCost == nullptr, the mapping cost is actually not computed.
Definition at line 442 of file RegBankSelect.cpp.
References assert(), assignmentMatch(), llvm::RegBankSelect::RepairingPlacement::canMaterialize(), llvm::SmallVectorImpl< T >::clear(), Cost, llvm::dbgs(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::MachineBlockFrequencyInfo::getBlockFreq(), llvm::RegisterBankInfo::InstructionMapping::getCost(), llvm::RegisterBankInfo::InstructionMapping::getNumOperands(), llvm::MachineOperand::getReg(), getRepairCost(), llvm::MachineRegisterInfo::getType(), llvm::RegBankSelect::RepairingPlacement::hasSplit(), llvm::RegBankSelect::MappingCost::ImpossibleCost(), llvm::RegBankSelect::RepairingPlacement::Insert, llvm::MachineOperand::isReg(), llvm::LLT::isValid(), llvm::RegisterBankInfo::InstructionMapping::isValid(), LLVM_DEBUG, llvm::max(), MBFI, MBPI, MI, MRI, llvm::RegBankSelect::RepairingPlacement::Reassign, TRI, tryAvoidingSplit(), and uint64_t.
Referenced by assignInstr(), and findBestMapping().
findBestMapping()
const RegisterBankInfo::InstructionMapping & RegBankSelect::findBestMapping (MachineInstr & MI, RegisterBankInfo::InstructionMappings & PossibleMappings, SmallVectorImpl< RepairingPlacement > & RepairPts) protected
Find the best mapping for MI from PossibleMappings.
Returns
a reference on the best mapping in PossibleMappings.
Definition at line 289 of file RegBankSelect.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), computeMapping(), Cost, llvm::dbgs(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::RegBankSelect::RepairingPlacement::Impossible, llvm::RegBankSelect::MappingCost::ImpossibleCost(), llvm::TargetPassConfig::isGlobalISelAbortEnabled(), LLVM_DEBUG, MI, move, TPC, and TRI.
Referenced by assignInstr().
getAnalysisUsage()
void RegBankSelect::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Reimplemented in llvm::AMDGPURegBankSelect.
Definition at line 98 of file RegBankSelect.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::Sched::Fast, llvm::MachineFunctionPass::getAnalysisUsage(), llvm::getSelectionDAGFallbackAnalysisUsage(), and OptMode.
Referenced by llvm::AMDGPURegBankSelect::getAnalysisUsage().
getClearedProperties()
MachineFunctionProperties llvm::RegBankSelect::getClearedProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 637 of file RegBankSelect.h.
References llvm::MachineFunctionProperties::NoPHIs, and llvm::MachineFunctionProperties::set().
getPassName()
StringRef llvm::RegBankSelect::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Reimplemented in llvm::AMDGPURegBankSelect.
Definition at line 622 of file RegBankSelect.h.
getRepairCost()
uint64_t RegBankSelect::getRepairCost (const MachineOperand & MO, const RegisterBankInfo::ValueMapping & ValMapping) const protected
Return the cost of the instruction needed to map MO to ValMapping.
The cost is free of basic block frequencies.
Precondition
MO.isReg()
MO is assigned to a register bank.
ValMapping is a valid mapping for MO.
Definition at line 237 of file RegBankSelect.cpp.
References assert(), llvm::RegisterBankInfo::ValueMapping::BreakDown, llvm::RegisterBankInfo::copyCost(), Cost, llvm::RegisterBankInfo::getBreakDownCost(), llvm::MachineOperand::getReg(), llvm::RegisterBankInfo::getRegBank(), llvm::RegisterBankInfo::getSizeInBits(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::max(), MRI, llvm::RegisterBankInfo::ValueMapping::NumBreakDowns, RBI, llvm::RegisterBankInfo::PartialMapping::RegBank, std::swap(), and TRI.
Referenced by computeMapping().
getRequiredProperties()
MachineFunctionProperties llvm::RegBankSelect::getRequiredProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 626 of file RegBankSelect.h.
References llvm::MachineFunctionProperties::IsSSA, llvm::MachineFunctionProperties::Legalized, and llvm::MachineFunctionProperties::set().
getSetProperties()
MachineFunctionProperties llvm::RegBankSelect::getSetProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 632 of file RegBankSelect.h.
References llvm::MachineFunctionProperties::RegBankSelected, and llvm::MachineFunctionProperties::set().
init()
void RegBankSelect::init (MachineFunction & MF) protected
Initialize the field members using MF.
Definition at line 81 of file RegBankSelect.cpp.
References assert(), llvm::Sched::Fast, llvm::TargetSubtargetInfo::getRegBankInfo(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), MBFI, MBPI, MIRBuilder, MORE, MRI, OptMode, RBI, llvm::MachineIRBuilder::setMF(), TPC, and TRI.
Referenced by runOnMachineFunction().
repairReg()
bool RegBankSelect::repairReg (MachineOperand & MO, const RegisterBankInfo::ValueMapping & ValMapping, RegBankSelect::RepairingPlacement & RepairPt, const iterator_range< SmallVectorImpl< Register >::const_iterator > & NewVRegs) protected
Insert repairing code for Reg as specified by ValMapping.
The repairing placement is specified by RepairPt. NewVRegs contains all the registers required to remap Reg. In other words, the number of registers in NewVRegs must be equal to ValMapping.BreakDown.size().
The transformation could be sketched as:
... = op Reg
Becomes
<NewRegs> = COPY or extract Reg
... = op Reg
and
Reg = op ...
Becomes
Reg = op ...
Reg = COPY or build_sequence <NewRegs>
Precondition
NewVRegs.size() == ValMapping.BreakDown.size()
Note
The caller is supposed to do the rewriting of op if need be. I.e., Reg = op ... => <NewRegs> = NewOp ...
Returns
True if the repairing worked, false otherwise.
Definition at line 133 of file RegBankSelect.cpp.
References llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::RegisterBankInfo::ValueMapping::BreakDown, llvm::MachineIRBuilder::buildInstrNoInsert(), llvm::MachineFunction::CloneMachineInstr(), llvm::dbgs(), llvm::MachineIRBuilder::getMF(), llvm::LLT::getNumElements(), llvm::RegBankSelect::RepairingPlacement::getNumInsertPoints(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineOperand::isDef(), llvm::LLT::isVector(), llvm::RegisterBankInfo::PartialMapping::Length, LLVM_DEBUG, MI, MIRBuilder, MRI, llvm::RegisterBankInfo::ValueMapping::NumBreakDowns, llvm::RegisterBankInfo::ValueMapping::partsAllUniform(), llvm::printReg(), llvm::printRegClassOrBank(), llvm::report_fatal_error(), llvm::size(), std::swap(), and TRI.
Referenced by applyMapping().
runOnMachineFunction()
bool RegBankSelect::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Reimplemented in llvm::AMDGPURegBankSelect.
Definition at line 732 of file RegBankSelect.cpp.
References assignRegisterBanks(), checkFunctionIsLegal(), llvm::dbgs(), F, llvm::MachineFunctionProperties::FailedISel, llvm::Sched::Fast, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getName(), llvm::MachineFunction::getProperties(), llvm::MachineFunctionProperties::hasProperty(), init(), LLVM_DEBUG, and OptMode.
tryAvoidingSplit()
void RegBankSelect::tryAvoidingSplit (RegBankSelect::RepairingPlacement & RepairPt, const MachineOperand & MO, const RegisterBankInfo::ValueMapping & ValMapping) const protected
When RepairPt involves splitting to repair MO for the given ValMapping, try to change the way we repair such that the splitting is not required anymore.
Precondition
RepairPt.hasSplit()
MO == MO.getParent()->getOperand(RepairPt.getOpIdx())
ValMapping is the mapping of MO for MO.getParent() that implied RepairPt.
Definition at line 323 of file RegBankSelect.cpp.
References assert(), llvm::RegBankSelect::RepairingPlacement::getOpIdx(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::RegBankSelect::RepairingPlacement::hasSplit(), llvm::MachineOperand::isDef(), llvm::MachineInstr::isUnconditionalBranch(), MI, llvm::RegisterBankInfo::ValueMapping::NumBreakDowns, llvm::MachineInstr::readsRegister(), Reassign, and llvm::RegBankSelect::RepairingPlacement::switchTo().
Referenced by computeMapping().
Member Data Documentation
ID
char RegBankSelect::ID = 0 static
Definition at line 93 of file RegBankSelect.h.
MBFI
MachineBlockFrequencyInfo* llvm::RegBankSelect::MBFI = nullptr protected
Get the frequency of blocks.
This is required for non-fast mode.
Definition at line 498 of file RegBankSelect.h.
Referenced by computeMapping(), llvm::RegBankSelect::InstrInsertPoint::frequency(), llvm::RegBankSelect::MBBInsertPoint::frequency(), llvm::RegBankSelect::EdgeInsertPoint::frequency(), and init().
MBPI
MachineBranchProbabilityInfo* llvm::RegBankSelect::MBPI = nullptr protected
Get the frequency of the edges.
This is required for non-fast mode.
Definition at line 502 of file RegBankSelect.h.
Referenced by computeMapping(), llvm::RegBankSelect::EdgeInsertPoint::frequency(), and init().
MIRBuilder
MachineIRBuilder llvm::RegBankSelect::MIRBuilder protected
Helper class used for every code morphing.
Definition at line 508 of file RegBankSelect.h.
Referenced by assignRegisterBanks(), init(), and repairReg().
MORE
std::unique_ptr<MachineOptimizationRemarkEmitter> llvm::RegBankSelect::MORE protected
Current optimization remark emitter. Used to report failures.
Definition at line 505 of file RegBankSelect.h.
Referenced by assignRegisterBanks(), checkFunctionIsLegal(), and init().
MRI
MachineRegisterInfo* llvm::RegBankSelect::MRI = nullptr protected
MRI contains all the register class/bank information that this pass uses and updates.
Definition at line 491 of file RegBankSelect.h.
Referenced by applyMapping(), assignInstr(), assignmentMatch(), computeMapping(), getRepairCost(), init(), and repairReg().
OptMode
Mode llvm::RegBankSelect::OptMode protected
Optimization mode of the pass.
Definition at line 511 of file RegBankSelect.h.
Referenced by assignInstr(), getAnalysisUsage(), init(), and runOnMachineFunction().
RBI
const RegisterBankInfo* llvm::RegBankSelect::RBI = nullptr protected
Interface to the target lowering info related to register banks.
Definition at line 487 of file RegBankSelect.h.
Referenced by applyMapping(), assignInstr(), assignmentMatch(), getRepairCost(), and init().
TPC
const TargetPassConfig* llvm::RegBankSelect::TPC protected
Current target configuration. Controls how the pass handles errors.
Definition at line 514 of file RegBankSelect.h.
Referenced by assignRegisterBanks(), checkFunctionIsLegal(), findBestMapping(), and init().
TRI
const TargetRegisterInfo* llvm::RegBankSelect::TRI = nullptr protected
Information on the register classes for the current function.
Definition at line 494 of file RegBankSelect.h.
Referenced by assignInstr(), assignmentMatch(), computeMapping(), findBestMapping(), getRepairCost(), init(), llvm::RegBankSelect::RepairingPlacement::RepairingPlacement(), and repairReg().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/RegBankSelect.h
lib/CodeGen/GlobalISel/RegBankSelect.cpp