LLVM: llvm::CrashRecoveryContext Class Reference
llvm::CrashRecoveryContext Class Reference
Crash recovery helper object.
#include "llvm/Support/CrashRecoveryContext.h"
Public Member Functions
CrashRecoveryContext ()
~CrashRecoveryContext ()
void registerCleanup (CrashRecoveryContextCleanup *cleanup)
Register cleanup handler, which is used when the recovery context is finished.
void unregisterCleanup (CrashRecoveryContextCleanup *cleanup)
bool RunSafely (function_ref< void()> Fn)
Execute the provided callback function (with the given arguments) in a protected context.
bool RunSafely (void(*Fn)(void *), void *UserData)
bool RunSafelyOnThread (function_ref< void()>, unsigned RequestedStackSize=0)
Execute the provide callback function (with the given arguments) in a protected context which is run in another thread (optionally with a requested stack size).
bool RunSafelyOnThread (void(*Fn)(void *), void *UserData, unsigned RequestedStackSize=0)
void HandleExit (int RetCode)
Explicitly trigger a crash recovery in the current process, and return failure from RunSafely().
Static Public Member Functions
static void Enable ()
Enable crash recovery.
static void Disable ()
Disable crash recovery.
static CrashRecoveryContext * GetCurrent ()
Return the active context, if the code is currently executing in a thread which is in a protected context.
static bool isRecoveringFromCrash ()
Return true if the current thread is recovering from a crash.
static bool isCrash (int RetCode)
Return true if RetCode indicates that a signal or an exception occurred.
static bool throwIfCrash (int RetCode)
Throw again a signal or an exception, after it was catched once by a CrashRecoveryContext.
Public Attributes
int RetCode = 0
In case of a crash, this is the crash identifier.
bool DumpStackAndCleanupOnFailure = false
Selects whether handling of failures should be done in the same way as for regular crashes.
Detailed Description
Crash recovery helper object.
This class implements support for running operations in a safe context so that crashes (memory errors, stack overflow, assertion violations) can be detected and control restored to the crashing thread. Crash detection is purely "best effort", the exact set of failures which can be recovered from is platform dependent.
Clients make use of this code by first calling CrashRecoveryContext::Enable(), and then executing unsafe operations via a CrashRecoveryContext object. For example:
void actual_work(void *);
void foo() {
  CrashRecoveryContext CRC;
  if (!CRC.RunSafely(actual_work, 0)) {
     ... a crash was detected, report error to user ...
  }
  ... no crash was detected ...
}
To assist recovery the class allows specifying set of actions that will be executed in any case, whether crash occurs or not. These actions may be used to reclaim resources in the case of crash.
Definition at line 46 of file CrashRecoveryContext.h.
Constructor & Destructor Documentation
CrashRecoveryContext()
CrashRecoveryContext::CrashRecoveryContext ()
Definition at line 100 of file CrashRecoveryContext.cpp.
References llvm::sys::DisableSystemDialogsOnCrash().
~CrashRecoveryContext()
CrashRecoveryContext::~CrashRecoveryContext ()
Definition at line 107 of file CrashRecoveryContext.cpp.
References i.
Member Function Documentation
Disable()
void CrashRecoveryContext::Disable () static
Disable crash recovery.
Definition at line 149 of file CrashRecoveryContext.cpp.
References uninstallExceptionOrSignalHandlers().
Referenced by CrashRecoverySignalHandler().
Enable()
void CrashRecoveryContext::Enable () static
Enable crash recovery.
Definition at line 140 of file CrashRecoveryContext.cpp.
References installExceptionOrSignalHandlers().
GetCurrent()
CrashRecoveryContext * CrashRecoveryContext::GetCurrent () static
Return the active context, if the code is currently executing in a thread which is in a protected context.
Definition at line 129 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDestructorCleanup< T >, T >::create(), and llvm::sys::Process::Exit().
HandleExit()
void CrashRecoveryContext::HandleExit (int RetCode)
Explicitly trigger a crash recovery in the current process, and return failure from RunSafely().
This function does not return.
Definition at line 432 of file CrashRecoveryContext.cpp.
References assert(), llvm_unreachable, and RetCode.
isCrash()
bool CrashRecoveryContext::isCrash (int RetCode) static
Return true if RetCode indicates that a signal or an exception occurred.
Definition at line 449 of file CrashRecoveryContext.cpp.
References llvm::tgtok::Code, RetCode, and unsigned.
Referenced by throwIfCrash().
isRecoveringFromCrash()
bool CrashRecoveryContext::isRecoveringFromCrash () static
Return true if the current thread is recovering from a crash.
Definition at line 125 of file CrashRecoveryContext.cpp.
registerCleanup()
void CrashRecoveryContext::registerCleanup (CrashRecoveryContextCleanup * cleanup)
Register cleanup handler, which is used when the recovery context is finished.
The recovery context owns the handler.
Definition at line 157 of file CrashRecoveryContext.cpp.
References cleanup().
Referenced by llvm::CrashRecoveryContextCleanupRegistrar< T, Cleanup >::CrashRecoveryContextCleanupRegistrar().
RunSafely() [1/2]
bool CrashRecoveryContext::RunSafely (function_ref< void()> Fn)
Execute the provided callback function (with the given arguments) in a protected context.
Returns
True if the function completed successfully, and false if the function crashed (or HandleCrash was called explicitly). Clients should make as little assumptions as possible about the program state when RunSafely has returned false.
Definition at line 413 of file CrashRecoveryContext.cpp.
References assert().
Referenced by RunSafely().
RunSafely() [2/2]
bool llvm::CrashRecoveryContext::RunSafely (void(*)(void *) Fn, void * UserData) inline
Definition at line 82 of file CrashRecoveryContext.h.
References RunSafely().
RunSafelyOnThread() [1/2]
bool CrashRecoveryContext::RunSafelyOnThread (function_ref< void()> Fn, unsigned RequestedStackSize = 0)
Execute the provide callback function (with the given arguments) in a protected context which is run in another thread (optionally with a requested stack size).
See RunSafely().
On Darwin, if PRIO_DARWIN_BG is set on the calling thread, it will be propagated to the new thread as well.
Definition at line 512 of file CrashRecoveryContext.cpp.
References hasThreadBackgroundPriority(), Info, RunSafelyOnThread_Dispatch(), and Thread.
Referenced by RunSafelyOnThread().
RunSafelyOnThread() [2/2]
bool llvm::CrashRecoveryContext::RunSafelyOnThread (void(*)(void *) Fn, void * UserData, unsigned RequestedStackSize = 0) inline
Definition at line 95 of file CrashRecoveryContext.h.
References RunSafelyOnThread().
throwIfCrash()
bool CrashRecoveryContext::throwIfCrash (int RetCode) static
Throw again a signal or an exception, after it was catched once by a CrashRecoveryContext.
Definition at line 467 of file CrashRecoveryContext.cpp.
References isCrash(), RetCode, and llvm::sys::unregisterHandlers().
unregisterCleanup()
void CrashRecoveryContext::unregisterCleanup (CrashRecoveryContextCleanup * cleanup)
Definition at line 168 of file CrashRecoveryContext.cpp.
References cleanup().
Referenced by llvm::CrashRecoveryContextCleanupRegistrar< T, Cleanup >::unregister().
Member Data Documentation
DumpStackAndCleanupOnFailure
bool llvm::CrashRecoveryContext::DumpStackAndCleanupOnFailure = false
Selects whether handling of failures should be done in the same way as for regular crashes.
When this is active, a crash would print the callstack, clean-up any temporary files and create a coredump/minidump.
Definition at line 117 of file CrashRecoveryContext.h.
RetCode
int llvm::CrashRecoveryContext::RetCode = 0
In case of a crash, this is the crash identifier.
Definition at line 112 of file CrashRecoveryContext.h.
Referenced by HandleExit(), isCrash(), and throwIfCrash().
The documentation for this class was generated from the following files:
include/llvm/Support/CrashRecoveryContext.h
lib/Support/CrashRecoveryContext.cpp