LLVM: llvm::CSKYInstPrinter Class Reference
llvm::CSKYInstPrinter Class Reference
#include "Target/CSKY/MCTargetDesc/CSKYInstPrinter.h"
Public Member Functions
CSKYInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
bool applyTargetSpecificCLOption (StringRef Opt) override
Customize the printer according to a command line option.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printRegName (raw_ostream &O, MCRegister Reg) const override
Print the assembler register name.
void printOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O, const char *Modifier=nullptr)
void printFPRRegName (raw_ostream &O, unsigned RegNo) const
std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI) override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
void printCustomAliasOperand (const MCInst *MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &O)
void printDataSymbol (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printConstpool (const MCInst *MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printPSRFlag (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printRegisterSeq (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printRegisterList (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printCSKYSymbolOperand (const MCInst *MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printSPAddr (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printFPR (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg)
static const char * getRegisterName (MCRegister Reg, unsigned AltIdx)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
Detailed Description
Definition at line 21 of file CSKYInstPrinter.h.
Constructor & Destructor Documentation
CSKYInstPrinter()
llvm::CSKYInstPrinter::CSKYInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 26 of file CSKYInstPrinter.h.
Member Function Documentation
applyTargetSpecificCLOption()
bool CSKYInstPrinter::applyTargetSpecificCLOption (StringRef Opt) override virtual
Customize the printer according to a command line option.
Returns
true if the option is recognized and applied.
Reimplemented from llvm::MCInstPrinter.
Definition at line 54 of file CSKYInstPrinter.cpp.
References ArchRegNames, llvm::DebugFlag, and NoAliases.
getMnemonic()
std::pair<const char *, uint64_t> llvm::CSKYInstPrinter::getMnemonic (const MCInst * MI) override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
getRegisterName() [1/2]
const char * CSKYInstPrinter::getRegisterName (MCRegister Reg) static
Definition at line 263 of file CSKYInstPrinter.cpp.
References ArchRegNames.
Referenced by llvm::CSKYAsmPrinter::PrintAsmMemoryOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), printFPRRegName(), and printRegName().
getRegisterName() [2/2]
static const char* llvm::CSKYInstPrinter::getRegisterName (MCRegister Reg, unsigned AltIdx) static
printAliasInstr()
bool llvm::CSKYInstPrinter::printAliasInstr (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by printInst().
printConstpool()
void CSKYInstPrinter::printConstpool (const MCInst * MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 159 of file CSKYInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatHex(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, MI, llvm::RISCVFenceField::O, llvm::MCExpr::print(), llvm::MCInstPrinter::PrintBranchImmAsAddress, and uint64_t.
printCSKYSymbolOperand()
void CSKYInstPrinter::printCSKYSymbolOperand (const MCInst * MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 182 of file CSKYInstPrinter.cpp.
References llvm::MCInstPrinter::formatHex(), llvm::MCOperand::getImm(), llvm::MCOperand::isImm(), MI, llvm::RISCVFenceField::O, llvm::MCInstPrinter::PrintBranchImmAsAddress, printOperand(), and uint64_t.
printCustomAliasOperand()
void llvm::CSKYInstPrinter::printCustomAliasOperand (const MCInst * MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & O)
printDataSymbol()
void CSKYInstPrinter::printDataSymbol (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 146 of file CSKYInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::isImm(), llvm::MCInstPrinter::MAI, MI, llvm::RISCVFenceField::O, and llvm::MCExpr::print().
printFPR()
void CSKYInstPrinter::printFPR (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 268 of file CSKYInstPrinter.cpp.
References assert(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), MI, llvm::RISCVFenceField::O, and printFPRRegName().
printFPRRegName()
void CSKYInstPrinter::printFPRRegName (raw_ostream & O, unsigned RegNo) const
Definition at line 93 of file CSKYInstPrinter.cpp.
References getRegisterName(), llvm::RISCVFenceField::O, and llvm::MCInstPrinter::PrintBranchImmAsAddress.
Referenced by printFPR().
printInst()
void CSKYInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 75 of file CSKYInstPrinter.cpp.
References MI, NoAliases, llvm::RISCVFenceField::O, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
printInstruction()
void llvm::CSKYInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by printInst().
printOperand()
void CSKYInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 100 of file CSKYInstPrinter.cpp.
References llvm::CSKYII::AddrModeMask, llvm::CSKYII::AddrModeNone, ArchRegNames, assert(), llvm::MCInstPrinter::formatHex(), llvm::MCInstrInfo::get(), llvm::MCOperand::getExpr(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, MI, llvm::MCInstPrinter::MII, llvm::RISCVFenceField::O, llvm::MCExpr::print(), llvm::MCInstPrinter::PrintBranchImmAsAddress, printRegName(), llvm::MCInstrDesc::TSFlags, TSFlags, and uint64_t.
Referenced by printCSKYSymbolOperand().
printPSRFlag()
void CSKYInstPrinter::printPSRFlag (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 200 of file CSKYInstPrinter.cpp.
References llvm::AArch64CC::LS, MI, and llvm::RISCVFenceField::O.
printRegisterList()
void CSKYInstPrinter::printRegisterList (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 224 of file CSKYInstPrinter.cpp.
References llvm::AArch64CC::LS, MI, llvm::RISCVFenceField::O, llvm::Offset, printRegName(), and R4.
printRegisterSeq()
void CSKYInstPrinter::printRegisterSeq (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 216 of file CSKYInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printRegName().
printRegName()
void CSKYInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 85 of file CSKYInstPrinter.cpp.
References getRegisterName(), llvm::RISCVFenceField::O, and llvm::MCInstPrinter::PrintBranchImmAsAddress.
Referenced by printOperand(), printRegisterList(), and printRegisterSeq().
printSPAddr()
void llvm::CSKYInstPrinter::printSPAddr (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
The documentation for this class was generated from the following files:
lib/Target/CSKY/MCTargetDesc/CSKYInstPrinter.h
lib/Target/CSKY/MCTargetDesc/CSKYInstPrinter.cpp