LLVM: llvm::StackMaps Class Reference
llvm::StackMaps Class Reference
#include "llvm/CodeGen/StackMaps.h"
Classes
struct CallsiteInfo
struct FunctionInfo
struct LiveOutReg
struct Location
Public Types
using OpType = enum { DirectMemRefOp, IndirectMemRefOp, ConstantOp }
using LocationVec = SmallVector< Location, 8 >
using LiveOutVec = SmallVector< LiveOutReg, 8 >
using ConstantPool = MapVector< uint64_t, uint64_t >
using FnInfoMap = MapVector< const MCSymbol *, FunctionInfo >
using CallsiteInfoList = std::vector< CallsiteInfo >
Public Member Functions
StackMaps (AsmPrinter &AP)
void reset ()
void recordStackMap (const MCSymbol &L, const MachineInstr &MI)
Generate a stackmap record for a stackmap instruction.
void recordPatchPoint (const MCSymbol &L, const MachineInstr &MI)
Generate a stackmap record for a patchpoint instruction.
void recordStatepoint (const MCSymbol &L, const MachineInstr &MI)
Generate a stackmap record for a statepoint instruction.
void serializeToStackMapSection ()
If there is any stack map data, create a stack map section and serialize the map info into it.
CallsiteInfoList & getCSInfos ()
Get call site info.
FnInfoMap & getFnInfos ()
Get function info.
Static Public Member Functions
static unsigned getNextMetaArgIdx (const MachineInstr *MI, unsigned CurIdx)
Get index of next meta operand.
Detailed Description
Definition at line 259 of file StackMaps.h.
Member Typedef Documentation
CallsiteInfoList
using llvm::StackMaps::CallsiteInfoList = std::vector<CallsiteInfo>
Definition at line 334 of file StackMaps.h.
ConstantPool
using llvm::StackMaps::ConstantPool = MapVector<uint64_t, uint64_t>
Definition at line 310 of file StackMaps.h.
FnInfoMap
using llvm::StackMaps::FnInfoMap = MapVector<const MCSymbol *, FunctionInfo>
Definition at line 333 of file StackMaps.h.
LiveOutVec
using llvm::StackMaps::LiveOutVec = SmallVector<LiveOutReg, 8>
Definition at line 309 of file StackMaps.h.
LocationVec
using llvm::StackMaps::LocationVec = SmallVector<Location, 8>
Definition at line 308 of file StackMaps.h.
OpType
using llvm::StackMaps::OpType = enum { DirectMemRefOp, IndirectMemRefOp, ConstantOp }
Definition at line 294 of file StackMaps.h.
Constructor & Destructor Documentation
StackMaps()
StackMaps::StackMaps (AsmPrinter & AP)
Definition at line 166 of file StackMaps.cpp.
References llvm_unreachable, and StackMapVersion.
Member Function Documentation
getCSInfos()
CallsiteInfoList& llvm::StackMaps::getCSInfos () inline
Get call site info.
Definition at line 356 of file StackMaps.h.
getFnInfos()
FnInfoMap& llvm::StackMaps::getFnInfos () inline
Get function info.
Definition at line 359 of file StackMaps.h.
getNextMetaArgIdx()
unsigned StackMaps::getNextMetaArgIdx (const MachineInstr * MI, unsigned CurIdx) static
Get index of next meta operand.
Similar to parseOperand, but does not actually parses operand meaning.
Definition at line 171 of file StackMaps.cpp.
References assert(), llvm_unreachable, and MI.
Referenced by llvm::MachineInstr::findTiedOperandIdx(), llvm::StatepointOpers::getNumAllocaIdx(), llvm::StatepointOpers::getNumGcMapEntriesIdx(), and llvm::StatepointOpers::getNumGCPtrIdx().
recordPatchPoint()
void StackMaps::recordPatchPoint (const MCSymbol & L, const MachineInstr & MI)
Generate a stackmap record for a patchpoint instruction.
Definition at line 551 of file StackMaps.cpp.
References assert(), llvm::numbers::e, llvm::PatchPointOpers::getID(), llvm::PatchPointOpers::getNumCallArgs(), llvm::PatchPointOpers::getStackMapStartIdx(), llvm::PatchPointOpers::hasDef(), i, llvm::PatchPointOpers::isAnyReg(), MI, llvm::ISD::PATCHPOINT, and llvm::StackMaps::Location::Register.
recordStackMap()
void StackMaps::recordStackMap (const MCSymbol & L, const MachineInstr & MI)
Generate a stackmap record for a stackmap instruction.
MI must be a raw STACKMAP, not a PATCHPOINT.
Definition at line 541 of file StackMaps.cpp.
References assert(), llvm::StackMapOpers::getVarIdx(), llvm::PatchPointOpers::IDPos, MI, and llvm::ISD::STACKMAP.
recordStatepoint()
void StackMaps::recordStatepoint (const MCSymbol & L, const MachineInstr & MI)
Generate a stackmap record for a statepoint instruction.
Definition at line 572 of file StackMaps.cpp.
References assert(), llvm::StatepointOpers::getID(), llvm::StatepointOpers::getVarIdx(), and MI.
reset()
void llvm::StackMaps::reset () inline
Definition at line 302 of file StackMaps.h.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear().
serializeToStackMapSection()
void StackMaps::serializeToStackMapSection ()
If there is any stack map data, create a stack map section and serialize the map info into it.
Serialize the stackmap data.
This clears the stack map data structures afterwards.
Definition at line 725 of file StackMaps.cpp.
References assert(), llvm::dbgs(), llvm::MCContext::getObjectFileInfo(), llvm::MCContext::getOrCreateSymbol(), llvm::MCObjectFileInfo::getStackMapSection(), LLVM_DEBUG, OS, and llvm::AsmPrinter::OutStreamer.
Referenced by llvm::AsmPrinter::emitStackMaps().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/StackMaps.h
lib/CodeGen/StackMaps.cpp