LLVM: llvm::X86Subtarget Class Reference
llvm::X86Subtarget Class Reference final
#include "Target/X86/X86Subtarget.h"
Public Member Functions
X86Subtarget (const Triple &TT, StringRef CPU, StringRef TuneCPU, StringRef FS, const X86TargetMachine &TM, MaybeAlign StackAlignOverride, unsigned PreferVectorWidthOverride, unsigned RequiredVectorWidth)
This constructor initializes the data members to match that of the specified triple.
const X86TargetLowering * getTargetLowering () const override
const X86InstrInfo * getInstrInfo () const override
const X86FrameLowering * getFrameLowering () const override
const X86SelectionDAGInfo * getSelectionDAGInfo () const override
const X86RegisterInfo * getRegisterInfo () const override
unsigned getTileConfigSize () const
Align getTileConfigAlignment () const
Align getStackAlignment () const
Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
unsigned getMaxInlineSizeThreshold () const
Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
const CallLowering * getCallLowering () const override
Methods used by Global ISel.
InstructionSelector * getInstructionSelector () const override
const LegalizerInfo * getLegalizerInfo () const override
const RegisterBankInfo * getRegBankInfo () const override
bool isTarget64BitILP32 () const
Is this x86_64 with the ILP32 programming model (x32 ABI)?
bool isTarget64BitLP64 () const
Is this x86_64 with the LP64 programming model (standard AMD64, no x32)?
PICStyles::Style getPICStyle () const
void setPICStyle (PICStyles::Style Style)
bool canUseCMPXCHG8B () const
bool canUseCMPXCHG16B () const
bool canUseCMOV () const
bool hasSSE1 () const
bool hasSSE2 () const
bool hasSSE3 () const
bool hasSSSE3 () const
bool hasSSE41 () const
bool hasSSE42 () const
bool hasAVX () const
bool hasAVX2 () const
bool hasAVX512 () const
bool hasInt256 () const
bool hasMMX () const
bool hasThreeDNow () const
bool hasThreeDNowA () const
bool hasAnyFMA () const
bool hasPrefetchW () const
bool hasSSEPrefetch () const
bool canUseLAHFSAHF () const
bool useIndirectThunkCalls () const
bool useIndirectThunkBranches () const
unsigned getPreferVectorWidth () const
unsigned getRequiredVectorWidth () const
bool canExtendTo512DQ () const
bool canExtendTo512BW () const
bool useAVX512Regs () const
bool useLight256BitInstructions () const
bool useBWIRegs () const
bool isXRaySupported () const override
bool hasCLFLUSH () const
Use clflush if we have SSE2 or we're on x86-64 (even if we asked for no-sse2).
bool hasMFence () const
Use mfence if we have SSE2 or we're on x86-64 (even if we asked for no-sse2).
const Triple & getTargetTriple () const
bool isTargetDarwin () const
bool isTargetFreeBSD () const
bool isTargetDragonFly () const
bool isTargetSolaris () const
bool isTargetPS () const
bool isTargetELF () const
bool isTargetCOFF () const
bool isTargetMachO () const
bool isTargetLinux () const
bool isTargetKFreeBSD () const
bool isTargetGlibc () const
bool isTargetAndroid () const
bool isTargetNaCl () const
bool isTargetNaCl32 () const
bool isTargetNaCl64 () const
bool isTargetMCU () const
bool isTargetFuchsia () const
bool isTargetWindowsMSVC () const
bool isTargetWindowsCoreCLR () const
bool isTargetWindowsCygwin () const
bool isTargetWindowsGNU () const
bool isTargetWindowsItanium () const
bool isTargetCygMing () const
bool isOSWindows () const
bool isTargetWin64 () const
bool isTargetWin32 () const
bool isPICStyleGOT () const
bool isPICStyleRIPRel () const
bool isPICStyleStubPIC () const
bool isPositionIndependent () const
bool isCallingConvWin64 (CallingConv::ID CC) const
unsigned char classifyLocalReference (const GlobalValue *GV) const
Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
unsigned char classifyGlobalReference (const GlobalValue *GV, const Module &M) const
unsigned char classifyGlobalReference (const GlobalValue *GV) const
Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
unsigned char classifyGlobalFunctionReference (const GlobalValue *GV, const Module &M) const
Classify a global function reference for the current subtarget.
unsigned char classifyGlobalFunctionReference (const GlobalValue *GV) const override
unsigned char classifyBlockAddressReference () const
Classify a blockaddress reference for the current subtarget according to how we should reference it in a non-pcrel context.
bool isLegalToCallImmediateAddr () const
Return true if the subtarget allows calls to immediate address.
bool swiftAsyncContextIsDynamicallySet () const
Return whether FrameLowering should always set the "extended frame present" bit in FP, or set it based on a symbol in the runtime.
bool enableIndirectBrExpand () const override
If we are using indirect thunks, we need to expand indirectbr to avoid it lowering to an actual indirect jump.
bool enableMachineScheduler () const override
Enable the MachineScheduler pass for all X86 subtargets.
bool enableEarlyIfConversion () const override
void getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> &Mutations) const override
AntiDepBreakMode getAntiDepBreakMode () const override
Detailed Description
Definition at line 52 of file X86Subtarget.h.
Constructor & Destructor Documentation
X86Subtarget()
X86Subtarget::X86Subtarget (const Triple & TT, StringRef CPU, StringRef TuneCPU, StringRef FS, const X86TargetMachine & TM, MaybeAlign StackAlignOverride, unsigned PreferVectorWidthOverride, unsigned RequiredVectorWidth)
This constructor initializes the data members to match that of the specified triple.
Definition at line 313 of file X86Subtarget.cpp.
References llvm::createX86InstructionSelector(), getRegisterInfo(), getTargetLowering(), llvm::PICStyles::GOT, is64Bit(), isPositionIndependent(), isTargetCOFF(), isTargetDarwin(), isTargetELF(), llvm::PICStyles::None, llvm::PICStyles::RIPRel, setPICStyle(), llvm::PICStyles::StubPIC, and TM.
Member Function Documentation
canExtendTo512BW()
bool llvm::X86Subtarget::canExtendTo512BW () const inline
Definition at line 248 of file X86Subtarget.h.
References canExtendTo512DQ().
Referenced by lower1BitShuffle(), LowerMUL(), LowerMULH(), LowerMULO(), LowerShift(), and LowerShiftByScalarVariable().
canExtendTo512DQ()
bool llvm::X86Subtarget::canExtendTo512DQ () const inline
Definition at line 245 of file X86Subtarget.h.
References getPreferVectorWidth(), and hasAVX512().
Referenced by canExtendTo512BW(), lower1BitShuffle(), LowerMULO(), LowerShift(), LowerShiftByScalarVariable(), LowerSIGN_EXTEND_Mask(), LowerTruncateVecI1(), LowerVectorCTLZ(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTPOP(), LowerZERO_EXTEND_Mask(), useAVX512Regs(), and useVPTERNLOG().
canUseCMOV()
bool llvm::X86Subtarget::canUseCMOV () const inline
Definition at line 198 of file X86Subtarget.h.
References hasSSE1(), and is64Bit().
Referenced by llvm::X86InstrInfo::canInsertSelect(), combineCMov(), enableEarlyIfConversion(), and llvm::X86TargetLowering::X86TargetLowering().
canUseCMPXCHG16B()
bool llvm::X86Subtarget::canUseCMPXCHG16B () const inline
Definition at line 192 of file X86Subtarget.h.
References is64Bit().
Referenced by llvm::X86TargetLowering::ReplaceNodeResults(), and llvm::X86TargetLowering::X86TargetLowering().
canUseCMPXCHG8B()
bool llvm::X86Subtarget::canUseCMPXCHG8B () const inline
Definition at line 191 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::X86TargetLowering().
canUseLAHFSAHF()
bool llvm::X86Subtarget::canUseLAHFSAHF () const inline
Definition at line 227 of file X86Subtarget.h.
References is64Bit().
classifyBlockAddressReference()
unsigned char X86Subtarget::classifyBlockAddressReference () const
Classify a blockaddress reference for the current subtarget according to how we should reference it in a non-pcrel context.
Definition at line 59 of file X86Subtarget.cpp.
References classifyLocalReference().
classifyGlobalFunctionReference() [1/2]
unsigned char X86Subtarget::classifyGlobalFunctionReference (const GlobalValue * GV) const override
Definition at line 194 of file X86Subtarget.cpp.
References classifyGlobalFunctionReference(), and llvm::GlobalValue::getParent().
classifyGlobalFunctionReference() [2/2]
unsigned char X86Subtarget::classifyGlobalFunctionReference (const GlobalValue * GV, const Module & M) const
Classify a global function reference for the current subtarget.
Definition at line 199 of file X86Subtarget.cpp.
References F, llvm::TargetMachine::getRelocationModel(), llvm::GlobalValue::hasDLLImportStorageClass(), is64Bit(), isTargetCOFF(), isTargetELF(), M, llvm::X86II::MO_COFFSTUB, llvm::X86II::MO_DLLIMPORT, llvm::X86II::MO_GOTPCREL, llvm::X86II::MO_NO_FLAG, llvm::X86II::MO_PLT, llvm::TargetMachine::shouldAssumeDSOLocal(), llvm::Reloc::Static, and llvm::CallingConv::X86_RegCall.
Referenced by classifyGlobalFunctionReference().
classifyGlobalReference() [1/2]
unsigned char X86Subtarget::classifyGlobalReference (const GlobalValue * GV) const
Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
Definition at line 66 of file X86Subtarget.cpp.
References classifyGlobalReference(), and llvm::GlobalValue::getParent().
classifyGlobalReference() [2/2]
unsigned char X86Subtarget::classifyGlobalReference (const GlobalValue * GV, const Module & M) const
Definition at line 132 of file X86Subtarget.cpp.
References classifyLocalReference(), llvm::GlobalValue::getAbsoluteSymbolRange(), llvm::TargetMachine::getCodeModel(), llvm::TargetMachine::getRelocationModel(), llvm::GlobalValue::hasDLLImportStorageClass(), is64Bit(), isOSWindows(), isPositionIndependent(), isTargetCOFF(), isTargetDarwin(), isTargetELF(), llvm::CodeModel::Large, M, llvm::X86II::MO_ABS8, llvm::X86II::MO_COFFSTUB, llvm::X86II::MO_DARWIN_NONLAZY, llvm::X86II::MO_DARWIN_NONLAZY_PIC_BASE, llvm::X86II::MO_DLLIMPORT, llvm::X86II::MO_GOT, llvm::X86II::MO_GOTPCREL, llvm::X86II::MO_GOTPCREL_NORELAX, llvm::X86II::MO_NO_FLAG, llvm::TargetMachine::shouldAssumeDSOLocal(), and llvm::Reloc::Static.
Referenced by classifyGlobalReference(), llvm::X86TargetLowering::isLegalAddressingMode(), and llvm::X86TargetLowering::LowerAsmOperandForConstraint().
classifyLocalReference()
unsigned char X86Subtarget::classifyLocalReference (const GlobalValue * GV) const
Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
Definition at line 71 of file X86Subtarget.cpp.
References llvm::TargetMachine::getCodeModel(), llvm::GlobalValue::hasCommonLinkage(), is64Bit(), llvm::GlobalValue::isDeclarationForLinker(), isPositionIndependent(), isTargetCOFF(), isTargetDarwin(), isTargetELF(), llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm_unreachable, llvm::CodeModel::Medium, llvm::X86II::MO_DARWIN_NONLAZY_PIC_BASE, llvm::X86II::MO_GOTOFF, llvm::X86II::MO_GOTPCREL_NORELAX, llvm::X86II::MO_NO_FLAG, llvm::X86II::MO_PIC_BASE_OFFSET, llvm::CodeModel::Small, and llvm::CodeModel::Tiny.
Referenced by classifyBlockAddressReference(), and classifyGlobalReference().
enableEarlyIfConversion()
bool X86Subtarget::enableEarlyIfConversion () const override
Definition at line 361 of file X86Subtarget.cpp.
References canUseCMOV(), and X86EarlyIfConv.
enableIndirectBrExpand()
bool llvm::X86Subtarget::enableIndirectBrExpand () const inline override
If we are using indirect thunks, we need to expand indirectbr to avoid it lowering to an actual indirect jump.
Definition at line 410 of file X86Subtarget.h.
References useIndirectThunkBranches().
enableMachineScheduler()
bool llvm::X86Subtarget::enableMachineScheduler () const inline override
Enable the MachineScheduler pass for all X86 subtargets.
Definition at line 415 of file X86Subtarget.h.
getAntiDepBreakMode()
AntiDepBreakMode llvm::X86Subtarget::getAntiDepBreakMode () const inline override
Definition at line 422 of file X86Subtarget.h.
getCallLowering()
const CallLowering * X86Subtarget::getCallLowering () const override
Methods used by Global ISel.
Definition at line 345 of file X86Subtarget.cpp.
getFrameLowering()
const X86FrameLowering* llvm::X86Subtarget::getFrameLowering () const inline override
Definition at line 130 of file X86Subtarget.h.
Referenced by emitLockedStackOp(), ExpandMOVImmSExti8(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86TargetLowering::getRegisterByName(), llvm::X86InstrInfo::isFunctionSafeToOutlineFrom(), llvm::X86InstrInfo::loadRegFromStackSlot(), and llvm::X86InstrInfo::storeRegToStackSlot().
getInstrInfo()
const X86InstrInfo* llvm::X86Subtarget::getInstrInfo () const inline override
Definition at line 128 of file X86Subtarget.h.
References InstrInfo.
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter(), getRegisterInfo(), llvm::X86CallLowering::lowerCall(), llvm::X86AsmPrinter::runOnMachineFunction(), and llvm::X86LegalizerInfo::X86LegalizerInfo().
getInstructionSelector()
InstructionSelector * X86Subtarget::getInstructionSelector () const override
Definition at line 349 of file X86Subtarget.cpp.
getLegalizerInfo()
const LegalizerInfo * X86Subtarget::getLegalizerInfo () const override
Definition at line 353 of file X86Subtarget.cpp.
getMaxInlineSizeThreshold()
unsigned llvm::X86Subtarget::getMaxInlineSizeThreshold () const inline
Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
Definition at line 152 of file X86Subtarget.h.
Referenced by emitConstantSizeRepmov(), and llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset().
getPICStyle()
PICStyles::Style llvm::X86Subtarget::getPICStyle () const inline
Definition at line 188 of file X86Subtarget.h.
getPostRAMutations()
void X86Subtarget::getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> & Mutations) const override
Definition at line 365 of file X86Subtarget.cpp.
References llvm::createX86MacroFusionDAGMutation().
getPreferVectorWidth()
unsigned llvm::X86Subtarget::getPreferVectorWidth () const inline
Definition at line 238 of file X86Subtarget.h.
Referenced by canExtendTo512DQ(), llvm::X86TargetLowering::canMergeStoresTo(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TTIImpl::getRegisterBitWidth(), and useLight256BitInstructions().
getRegBankInfo()
const RegisterBankInfo * X86Subtarget::getRegBankInfo () const override
Definition at line 357 of file X86Subtarget.cpp.
getRegisterInfo()
const X86RegisterInfo* llvm::X86Subtarget::getRegisterInfo () const inline override
Definition at line 138 of file X86Subtarget.h.
References getInstrInfo(), and llvm::X86InstrInfo::getRegisterInfo().
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter(), expandXorFP(), getBroadcastOpcode(), getLoadStoreRegOpcode(), llvm::X86TargetLowering::getRegisterByName(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::X86CallLowering::lowerCall(), X86Subtarget(), and llvm::X86TargetLowering::X86TargetLowering().
getRequiredVectorWidth()
unsigned llvm::X86Subtarget::getRequiredVectorWidth () const inline
Definition at line 239 of file X86Subtarget.h.
getSelectionDAGInfo()
const X86SelectionDAGInfo* llvm::X86Subtarget::getSelectionDAGInfo () const inline override
Definition at line 134 of file X86Subtarget.h.
getStackAlignment()
Align llvm::X86Subtarget::getStackAlignment () const inline
Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
Definition at line 148 of file X86Subtarget.h.
getTargetLowering()
const X86TargetLowering* llvm::X86Subtarget::getTargetLowering () const inline override
Definition at line 124 of file X86Subtarget.h.
Referenced by llvm::X86FrameLowering::canUseAsPrologue(), combineConcatVectorOps(), combineOrCmpEqZeroToCtlzSrl(), combineSIntToFP(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitSPUpdate(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), and X86Subtarget().
getTargetTriple()
const Triple& llvm::X86Subtarget::getTargetTriple () const inline
Definition at line 278 of file X86Subtarget.h.
Referenced by computeBytesPoppedByCalleeForSRet(), llvm::X86TargetLowering::getIRStackGuard(), llvm::X86TargetLowering::getSafeStackPointerLocation(), llvm::X86TargetLowering::getSDagStackGuard(), llvm::X86TargetLowering::getSSPStackGuardCheck(), hasCalleePopSRet(), llvm::X86TargetLowering::insertSSPDeclarations(), swiftAsyncContextIsDynamicallySet(), llvm::X86TargetLowering::useStackGuardXorFP(), and llvm::X86TargetLowering::X86TargetLowering().
getTileConfigAlignment()
Align llvm::X86Subtarget::getTileConfigAlignment () const inline
Definition at line 143 of file X86Subtarget.h.
getTileConfigSize()
unsigned llvm::X86Subtarget::getTileConfigSize () const inline
Definition at line 142 of file X86Subtarget.h.
hasAnyFMA()
bool llvm::X86Subtarget::hasAnyFMA () const inline
Definition at line 212 of file X86Subtarget.h.
Referenced by combineFMA(), combineFneg(), combineShuffleToFMAddSub(), llvm::X86TargetLowering::getNegatedExpression(), isFMAddSubOrFMSubAdd(), llvm::X86TargetLowering::isFMAFasterThanFMulAndFAdd(), and llvm::X86TargetLowering::X86TargetLowering().
hasAVX()
bool llvm::X86Subtarget::hasAVX () const inline
Definition at line 205 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::allowsMemoryAccess(), llvm::X86InstrInfo::breakPartialRegDependency(), combineAndShuffleNot(), combineBitcastvxi1(), combineCONCAT_VECTORS(), combineConcatVectorOps(), combineEXTRACT_SUBVECTOR(), combineLoad(), combinePredicateReduction(), combinePTESTCC(), combineSelect(), combineToHorizontalAddSub(), combineVectorSizedSetCCEquality(), combineX86ShuffleChain(), convertIntLogicToFPLogic(), llvm::X86InstrInfo::copyPhysReg(), CopyToFromAsymmetricReg(), createVariablePermute(), EltsFromConsecutiveLoads(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::X86TTIImpl::getCmpSelInstrCost(), getLoadStoreOpcodeForFP16(), getLoadStoreRegOpcode(), llvm::X86TTIImpl::getMaxInterleaveFactor(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TTIImpl::getRegisterBitWidth(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), isLegalConversion(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::X86TTIImpl::isLegalNTStore(), LowerANY_EXTEND(), lowerBuildVectorAsBroadcast(), LowerEXTEND_VECTOR_INREG(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), LowerToHorizontalOp(), lowerUINT_TO_FP_vXi32(), lowerV2F64Shuffle(), lowerV4F32Shuffle(), LowerVectorAllZero(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowerZERO_EXTEND(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), llvm::X86::mayFoldLoad(), llvm::X86::mayFoldLoadIntoBroadcastFromMem(), llvm::X86TargetLowering::reduceSelectOfFPConstantLoads(), useVectorCast(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
hasAVX2()
bool llvm::X86Subtarget::hasAVX2 () const inline
Definition at line 206 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::allowsMemoryAccess(), combineBitcastvxi1(), combineConcatVectorOps(), combineEXTRACT_SUBVECTOR(), combineSelect(), combineShuffleOfConcatUndef(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineVSelectToBLENDV(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), convertShiftLeftToScale(), EltsFromConsecutiveLoads(), expandFP_TO_UINT_SSE(), foldVectorXorShiftIntoCmp(), llvm::X86TTIImpl::getAddressComputationCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86InstrInfo::getExecutionDomain(), llvm::X86InstrInfo::getExecutionDomainCustom(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::X86TTIImpl::getScalarizationOverhead(), hasInt256(), isHorizontalBinOp(), llvm::X86TTIImpl::isLegalNTLoad(), llvm::X86TargetLowering::isVectorClearMaskLegal(), llvm::X86TargetLowering::isVectorShiftByScalarCheap(), lower256BitShuffle(), lowerBuildVectorAsBroadcast(), LowerFunnelShift(), LowerMGATHER(), LowerRotate(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsTruncBroadcast(), lowerShuffleWithPSHUFB(), lowerShuffleWithUndefHalf(), LowerToHorizontalOp(), lowerV16I16Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV32I8Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8F32Shuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchUnaryPermuteShuffle(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), llvm::X86TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), and SplitOpsAndApply().
hasAVX512()
bool llvm::X86Subtarget::hasAVX512 () const inline
Definition at line 207 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::allowsMemoryAccess(), canCombineAsMaskOperation(), canExtendTo512DQ(), combineArithReduction(), combineBitcast(), combineBitcastvxi1(), combineCastedMaskArithmetic(), combineCompareEqual(), combineConcatVectorOps(), combineExtSetcc(), combineLoad(), combineMaskedLoad(), combineMulToPMADDWD(), combinePMULH(), combineSelect(), combineSetCC(), combineStore(), combineToExtendBoolVectorInReg(), combineTruncateWithSat(), combineVectorPack(), combineVectorSignBitsTruncation(), combineVectorTruncation(), combineX86ShuffleChain(), llvm::X86TargetLowering::convertSelectOfConstantsToMath(), convertShiftLeftToScale(), CopyToFromAsymmetricReg(), EmitAVX512Test(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::X86TTIImpl::forceScalarizeMaskedGather(), getAVX512Node(), getBroadcastOpcode(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::X86RegisterInfo::getLargestLegalSuperClass(), getLoadStoreOpcodeForFP16(), getLoadStoreRegOpcode(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::X86TTIImpl::getNumberOfRegisters(), llvm::X86TargetLowering::getNumRegistersForCallingConv(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getPreferredVectorAction(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TTIImpl::getRegisterBitWidth(), llvm::X86TargetLowering::getRegisterTypeForCallingConv(), llvm::X86TTIImpl::getReplicationShuffleCost(), llvm::X86RegisterInfo::getReservedRegs(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::X86TargetLowering::getSetCCResultType(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getVectorTypeBreakdownForCallingConv(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedScatter(), llvm::X86TargetLowering::isLoadBitCastBeneficial(), lower1BitShuffle(), lower512BitShuffle(), LowerBITCAST(), LowerEXTEND_VECTOR_INREG(), LowerFunnelShift(), LowerLoad(), LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), LowerMSTORE(), LowerMULH(), LowerRotate(), LowerShift(), lowerShuffleAsBitRotate(), lowerShuffleAsVTRUNC(), lowerShuffleWithUndefHalf(), lowerShuffleWithVPMOV(), LowerStore(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerV16I16Shuffle(), lowerV2X128Shuffle(), lowerV32I8Shuffle(), lowerV8F32Shuffle(), lowerV8I32Shuffle(), LowerVSETCC(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsBitRotate(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86TargetLowering::shouldFoldSelectWithIdentityConstant(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), supportedVectorShiftWithImm(), supportedVectorVarShift(), useAVX512Regs(), useVectorCast(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
hasCLFLUSH()
bool llvm::X86Subtarget::hasCLFLUSH () const inline
Use clflush if we have SSE2 or we're on x86-64 (even if we asked for no-sse2).
There isn't any reason to disable it if the target processor supports it.
Definition at line 271 of file X86Subtarget.h.
References hasSSE2(), and is64Bit().
hasInt256()
bool llvm::X86Subtarget::hasInt256 () const inline
Definition at line 208 of file X86Subtarget.h.
References hasAVX2().
Referenced by combineConcatVectorOps(), combineHorizOpWithShuffle(), combineLoad(), combineLogicBlendIntoPBLENDV(), combinePMULH(), combinePredicateReduction(), combineSetCCMOVMSK(), combineSignExtendInReg(), combineVectorTruncation(), convertShiftLeftToScale(), EltsFromConsecutiveLoads(), getPMOVMSKB(), LowerABD(), LowerABS(), LowerADDSAT_SUBSAT(), LowerAVG(), LowerAVXExtend(), LowerBITREVERSE(), lowerBuildVectorAsBroadcast(), LowerEXTEND_VECTOR_INREG(), LowerMINMAX(), LowerMUL(), LowerMULH(), LowerMULO(), LowerShift(), LowerShiftByScalarImmediate(), LowerSIGN_EXTEND(), LowerVectorCTLZ(), LowerVectorCTPOP(), LowerVSETCC(), matchBinaryShuffle(), matchUnaryShuffle(), supportedVectorShiftWithImm(), supportedVectorVarShift(), truncateVectorWithPACK(), and llvm::X86TargetLowering::X86TargetLowering().
hasMFence()
bool llvm::X86Subtarget::hasMFence () const inline
Use mfence if we have SSE2 or we're on x86-64 (even if we asked for no-sse2).
There isn't any reason to disable it if the target processor supports it.
Definition at line 276 of file X86Subtarget.h.
References hasSSE2(), and is64Bit().
Referenced by LowerATOMIC_FENCE().
hasMMX()
bool llvm::X86Subtarget::hasMMX () const inline
Definition at line 209 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), and llvm::X86TargetLowering::X86TargetLowering().
hasPrefetchW()
bool llvm::X86Subtarget::hasPrefetchW () const inline
Definition at line 213 of file X86Subtarget.h.
References hasThreeDNow().
hasSSE1()
bool llvm::X86Subtarget::hasSSE1 () const inline
Definition at line 199 of file X86Subtarget.h.
Referenced by canUseCMOV(), combineAnd(), combineBitcast(), combineBitcastvxi1(), combineCMov(), combineFAndFNotToFAndn(), combineFMinNumFMaxNum(), combineOr(), combineSelect(), combineSetCC(), combineXor(), convertIntLogicToFPLogic(), createMMXBuildVector(), get64BitArgumentXMMs(), llvm::X86TargetLowering::getByValTypeAlignment(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::X86TTIImpl::getNumberOfRegisters(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TTIImpl::getRegisterBitWidth(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::hasAndNot(), hasSSEPrefetch(), llvm::X86TTIImpl::isLegalNTLoad(), llvm::X86TTIImpl::isLegalNTStore(), llvm::X86TargetLowering::isSafeMemOpType(), llvm::X86TargetLowering::isScalarFPTypeInSSEReg(), LowerStore(), llvm::X86TargetLowering::LowerXConstraint(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
hasSSE2()
bool llvm::X86Subtarget::hasSSE2 () const inline
Definition at line 200 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::allowsMemoryAccess(), combineAnd(), combineAndShuffleNot(), combineArithReduction(), combineBasicSADPattern(), combineBitcast(), combineBitcastvxi1(), combineCMov(), combineCompareEqual(), combineExtractWithShuffle(), combineFAndFNotToFAndn(), combineFMinNumFMaxNum(), combineLogicBlendIntoPBLENDV(), combineMOVMSK(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineOr(), combinePMULH(), combinePredicateReduction(), combineSelect(), combineSetCC(), combineShiftToPMULH(), combineStore(), combineToExtendBoolVectorInReg(), combineTruncateWithSat(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineVectorTruncation(), combineX86ShuffleChain(), combineXor(), llvm::X86InstrInfo::commuteInstructionImpl(), convertIntLogicToFPLogic(), detectAVGPattern(), EltsFromConsecutiveLoads(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::X86InstrInfo::findCommutedOpIndices(), foldVectorXorShiftIntoCmp(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TTIImpl::getVectorInstrCost(), getZeroVector(), llvm::X86TargetLowering::hasAndNot(), hasCLFLUSH(), hasMFence(), isLegalConversion(), llvm::X86TargetLowering::isSafeMemOpType(), llvm::X86TargetLowering::isScalarFPTypeInSSEReg(), LowerBITCAST(), LowerBuildVectorAsInsert(), LowerEXTEND_VECTOR_INREG(), lowerFPToIntToFP(), LowerMUL(), LowerMULH(), LowerShift(), LowerStore(), lowerV4F32Shuffle(), LowerVSETCC(), LowerVSETCCWithSUBUS(), lowerX86FPLogicOp(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchPMADDWD(), matchPMADDWD_2(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), MatchVectorAllZeroTest(), materializeVectorConstant(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ShouldShrinkFPConstant(), llvm::X86TargetLowering::shouldSinkOperands(), SplitOpsAndApply(), supportedVectorShiftWithImm(), truncateVectorWithPACK(), useVectorCast(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
hasSSE3()
bool llvm::X86Subtarget::hasSSE3 () const inline
Definition at line 201 of file X86Subtarget.h.
Referenced by combineArithReduction(), combineToHorizontalAddSub(), isAddSubOrSubAdd(), llvm::X86TTIImpl::isLegalAltInstr(), llvm::X86TTIImpl::isLegalBroadcastLoad(), lowerAddSubToHorizontalOp(), LowerBuildVectorv4x32(), lowerShuffleAsBitRotate(), lowerShuffleAsBroadcast(), LowerToHorizontalOp(), LowerUINT_TO_FP_i64(), lowerV4F32Shuffle(), and matchUnaryShuffle().
hasSSE41()
bool llvm::X86Subtarget::hasSSE41 () const inline
Definition at line 203 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::allowsMemoryAccess(), llvm::X86TargetLowering::allowsMisalignedMemoryAccesses(), combineArithReduction(), combineEXTEND_VECTOR_INREG(), combineExtractWithShuffle(), combineLogicBlendIntoPBLENDV(), combineMinMaxReduction(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineSetCCMOVMSK(), combineTruncateWithSat(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineVectorTruncation(), combineVSelectToBLENDV(), combineX86ShuffleChain(), llvm::X86InstrInfo::commuteInstructionImpl(), convertShiftLeftToScale(), createVariablePermute(), llvm::X86InstrInfo::findCommutedOpIndices(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), getPack(), llvm::X86TTIImpl::getScalarizationOverhead(), getTargetVShiftNode(), llvm::X86TTIImpl::getVectorInstrCost(), LowerABS(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), LowerBuildVectorv8i16(), LowerMUL(), LowerMULH(), LowerRotate(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerUINT_TO_FP_vXi32(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV4F32Shuffle(), lowerV4I32Shuffle(), lowerV8I16Shuffle(), LowerVectorAllZero(), LowerVSETCC(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleWithPACK(), matchShuffleWithUNPCK(), matchUnaryShuffle(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::shouldSinkOperands(), truncateVectorWithPACK(), and llvm::X86TargetLowering::X86TargetLowering().
hasSSE42()
bool llvm::X86Subtarget::hasSSE42 () const inline
Definition at line 204 of file X86Subtarget.h.
Referenced by LowerShiftByScalarImmediate(), LowerVSETCC(), and llvm::X86TargetLowering::X86TargetLowering().
hasSSEPrefetch()
bool llvm::X86Subtarget::hasSSEPrefetch () const inline
Definition at line 220 of file X86Subtarget.h.
References hasSSE1(), and hasThreeDNow().
Referenced by llvm::X86TargetLowering::X86TargetLowering().
hasSSSE3()
bool llvm::X86Subtarget::hasSSSE3 () const inline
Definition at line 202 of file X86Subtarget.h.
Referenced by combineArithReduction(), combineToHorizontalAddSub(), combineVectorTruncation(), combineX86ShuffleChain(), createVariablePermute(), detectPMADDUBSW(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::X86TTIImpl::getShuffleCost(), lowerAddSubToHorizontalOp(), LowerBITREVERSE(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithPSHUFB(), LowerToHorizontalOp(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerV8I16Shuffle(), LowerVectorCTLZ(), LowerVectorCTPOP(), matchBinaryPermuteShuffle(), and llvm::X86TargetLowering::X86TargetLowering().
hasThreeDNow()
bool llvm::X86Subtarget::hasThreeDNow () const inline
Definition at line 210 of file X86Subtarget.h.
Referenced by hasPrefetchW(), hasSSEPrefetch(), and llvm::X86TargetLowering::X86TargetLowering().
hasThreeDNowA()
bool llvm::X86Subtarget::hasThreeDNowA () const inline
Definition at line 211 of file X86Subtarget.h.
isCallingConvWin64()
bool llvm::X86Subtarget::isCallingConvWin64 (CallingConv::ID CC) const inline
Definition at line 337 of file X86Subtarget.h.
References llvm::CallingConv::C, CC, llvm::CallingConv::Fast, llvm::CallingConv::Intel_OCL_BI, isTargetWin64(), llvm::CallingConv::Swift, llvm::CallingConv::SwiftTail, llvm::CallingConv::Tail, llvm::CallingConv::Win64, llvm::CallingConv::X86_64_SysV, llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_StdCall, llvm::CallingConv::X86_ThisCall, and llvm::CallingConv::X86_VectorCall.
Referenced by get64BitArgumentGPRs(), get64BitArgumentXMMs(), llvm::X86FrameLowering::has128ByteRedZone(), llvm::X86CallLowering::lowerCall(), and LowerVACOPY().
isLegalToCallImmediateAddr()
bool X86Subtarget::isLegalToCallImmediateAddr () const
Return true if the subtarget allows calls to immediate address.
Definition at line 248 of file X86Subtarget.cpp.
References llvm::TargetMachine::getRelocationModel(), isTargetELF(), isTargetWin32(), and llvm::Reloc::Static.
isOSWindows()
bool llvm::X86Subtarget::isOSWindows () const inline
Definition at line 322 of file X86Subtarget.h.
References llvm::Triple::isOSWindows().
Referenced by classifyGlobalReference(), llvm::X86TargetLowering::getStackProbeSymbolName(), llvm::X86TargetLowering::hasInlineStackProbe(), isTargetWin32(), isTargetWin64(), llvm::X86TargetLowering::preferredShiftLegalizationStrategy(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), and llvm::X86FrameLowering::stackProbeFunctionModifiesSP().
isPICStyleGOT()
bool llvm::X86Subtarget::isPICStyleGOT () const inline
Definition at line 328 of file X86Subtarget.h.
References llvm::PICStyles::GOT.
Referenced by llvm::X86TargetLowering::getJumpTableEncoding(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), and llvm::X86TargetLowering::LowerCustomJumpTableEntry().
isPICStyleRIPRel()
bool llvm::X86Subtarget::isPICStyleRIPRel () const inline
Definition at line 329 of file X86Subtarget.h.
References llvm::PICStyles::RIPRel.
Referenced by llvm::X86TargetLowering::getPICJumpTableRelocBaseExpr(), and llvm::X86AsmPrinter::PrintAsmOperand().
isPICStyleStubPIC()
bool llvm::X86Subtarget::isPICStyleStubPIC () const inline
Definition at line 331 of file X86Subtarget.h.
References llvm::PICStyles::StubPIC.
Referenced by llvm::X86TargetLowering::LowerAsmOperandForConstraint().
isPositionIndependent()
bool X86Subtarget::isPositionIndependent () const
Definition at line 370 of file X86Subtarget.cpp.
References llvm::TargetMachine::isPositionIndependent().
Referenced by classifyGlobalReference(), classifyLocalReference(), and X86Subtarget().
isTarget64BitILP32()
bool llvm::X86Subtarget::isTarget64BitILP32 () const inline
Is this x86_64 with the ILP32 programming model (x32 ABI)?
Definition at line 179 of file X86Subtarget.h.
References llvm::Triple::isOSNaCl(), and llvm::Triple::isX32().
Referenced by llvm::X86FrameLowering::determineCalleeSaves(), llvm::X86FrameLowering::emitCalleeSavedFrameMovesFullCFA(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), getLeaOP(), llvm::X86RegisterInfo::getPtrSizedFrameRegister(), and llvm::X86RegisterInfo::getPtrSizedStackRegister().
isTarget64BitLP64()
bool llvm::X86Subtarget::isTarget64BitLP64 () const inline
Is this x86_64 with the LP64 programming model (standard AMD64, no x32)?
Definition at line 184 of file X86Subtarget.h.
References llvm::Triple::isOSNaCl(), and llvm::Triple::isX32().
Referenced by emitRepmovs(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86TargetLowering::getExceptionPointerRegister(), llvm::X86TargetLowering::getExceptionSelectorRegister(), llvm::X86RegisterInfo::getPointerRegClass(), LowerVACOPY(), llvm::X86TargetLowering::reduceSelectOfFPConstantLoads(), and llvm::X86FrameLowering::X86FrameLowering().
isTargetAndroid()
bool llvm::X86Subtarget::isTargetAndroid () const inline
Definition at line 293 of file X86Subtarget.h.
References llvm::Triple::isAndroid().
Referenced by llvm::X86TargetLowering::getSafeStackPointerLocation().
isTargetCOFF()
bool llvm::X86Subtarget::isTargetCOFF () const inline
Definition at line 287 of file X86Subtarget.h.
References llvm::Triple::isOSBinFormatCOFF().
Referenced by classifyGlobalFunctionReference(), classifyGlobalReference(), classifyLocalReference(), llvm::X86AsmPrinter::runOnMachineFunction(), and X86Subtarget().
isTargetCygMing()
bool llvm::X86Subtarget::isTargetCygMing () const inline
Definition at line 320 of file X86Subtarget.h.
References llvm::Triple::isOSCygMing().
Referenced by llvm::X86TargetLowering::getStackProbeSymbolName(), and llvm::X86TargetLowering::X86TargetLowering().
isTargetDarwin()
bool llvm::X86Subtarget::isTargetDarwin () const inline
Definition at line 280 of file X86Subtarget.h.
References llvm::Triple::isOSDarwin().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), classifyGlobalReference(), classifyLocalReference(), LowerFSINCOS(), X86Subtarget(), and llvm::X86TargetLowering::X86TargetLowering().
isTargetDragonFly()
bool llvm::X86Subtarget::isTargetDragonFly () const inline
Definition at line 282 of file X86Subtarget.h.
References llvm::Triple::isOSDragonFly().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
isTargetELF()
bool llvm::X86Subtarget::isTargetELF () const inline
Definition at line 286 of file X86Subtarget.h.
References llvm::Triple::isOSBinFormatELF().
Referenced by classifyGlobalFunctionReference(), classifyGlobalReference(), classifyLocalReference(), isLegalToCallImmediateAddr(), X86Subtarget(), and llvm::X86TargetLowering::X86TargetLowering().
isTargetFreeBSD()
bool llvm::X86Subtarget::isTargetFreeBSD () const inline
Definition at line 281 of file X86Subtarget.h.
References llvm::Triple::isOSFreeBSD().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
isTargetFuchsia()
bool llvm::X86Subtarget::isTargetFuchsia () const inline
Definition at line 298 of file X86Subtarget.h.
References llvm::Triple::isOSFuchsia().
Referenced by llvm::X86TargetLowering::getIRStackGuard(), and llvm::X86TargetLowering::getSafeStackPointerLocation().
isTargetGlibc()
bool llvm::X86Subtarget::isTargetGlibc () const inline
Definition at line 292 of file X86Subtarget.h.
References llvm::Triple::isOSGlibc().
isTargetKFreeBSD()
bool llvm::X86Subtarget::isTargetKFreeBSD () const inline
Definition at line 291 of file X86Subtarget.h.
References llvm::Triple::isOSKFreeBSD().
isTargetLinux()
bool llvm::X86Subtarget::isTargetLinux () const inline
Definition at line 290 of file X86Subtarget.h.
References llvm::Triple::isOSLinux().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), and llvm::X86CallLowering::lowerCall().
isTargetMachO()
bool llvm::X86Subtarget::isTargetMachO () const inline
Definition at line 288 of file X86Subtarget.h.
References llvm::Triple::isOSBinFormatMachO().
Referenced by llvm::X86TargetLowering::getStackProbeSymbolName(), llvm::X86TargetLowering::useLoadStackGuardNode(), and llvm::X86TargetLowering::useStackGuardXorFP().
isTargetMCU()
bool llvm::X86Subtarget::isTargetMCU () const inline
Definition at line 297 of file X86Subtarget.h.
References llvm::Triple::isOSIAMCU().
Referenced by computeBytesPoppedByCalleeForSRet(), and hasCalleePopSRet().
isTargetNaCl()
bool llvm::X86Subtarget::isTargetNaCl () const inline
Definition at line 294 of file X86Subtarget.h.
References llvm::Triple::isOSNaCl().
Referenced by isTargetNaCl32(), and isTargetNaCl64().
isTargetNaCl32()
bool llvm::X86Subtarget::isTargetNaCl32 () const inline
Definition at line 295 of file X86Subtarget.h.
References is64Bit(), and isTargetNaCl().
isTargetNaCl64()
bool llvm::X86Subtarget::isTargetNaCl64 () const inline
Definition at line 296 of file X86Subtarget.h.
References is64Bit(), and isTargetNaCl().
Referenced by llvm::X86FrameLowering::X86FrameLowering().
isTargetPS()
bool llvm::X86Subtarget::isTargetPS () const inline
Definition at line 284 of file X86Subtarget.h.
References llvm::Triple::isPS().
Referenced by llvm::X86TargetLowering::X86TargetLowering().
isTargetSolaris()
bool llvm::X86Subtarget::isTargetSolaris () const inline
Definition at line 283 of file X86Subtarget.h.
References llvm::Triple::isOSSolaris().
isTargetWin32()
bool llvm::X86Subtarget::isTargetWin32 () const inline
Definition at line 326 of file X86Subtarget.h.
References isOSWindows().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::emitPrologue(), isLegalToCallImmediateAddr(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), and llvm::X86AsmPrinter::runOnMachineFunction().
isTargetWin64()
bool llvm::X86Subtarget::isTargetWin64 () const inline
Definition at line 324 of file X86Subtarget.h.
References isOSWindows().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::X86FrameLowering::canUseAsEpilogue(), llvm::X86FrameLowering::getFrameIndexReferencePreferSP(), isCallingConvWin64(), llvm::X86TargetLowering::needsFixedCatchObjects(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86FrameLowering::stackProbeFunctionModifiesSP(), and llvm::X86TargetLowering::X86TargetLowering().
isTargetWindowsCoreCLR()
bool llvm::X86Subtarget::isTargetWindowsCoreCLR () const inline
Definition at line 304 of file X86Subtarget.h.
References llvm::Triple::isWindowsCoreCLREnvironment().
Referenced by llvm::X86FrameLowering::emitStackProbe().
isTargetWindowsCygwin()
bool llvm::X86Subtarget::isTargetWindowsCygwin () const inline
Definition at line 308 of file X86Subtarget.h.
References llvm::Triple::isWindowsCygwinEnvironment().
isTargetWindowsGNU()
bool llvm::X86Subtarget::isTargetWindowsGNU () const inline
Definition at line 312 of file X86Subtarget.h.
References llvm::Triple::isWindowsGNUEnvironment().
isTargetWindowsItanium()
bool llvm::X86Subtarget::isTargetWindowsItanium () const inline
Definition at line 316 of file X86Subtarget.h.
References llvm::Triple::isWindowsItaniumEnvironment().
Referenced by llvm::X86TargetLowering::X86TargetLowering().
isTargetWindowsMSVC()
bool llvm::X86Subtarget::isTargetWindowsMSVC () const inline
Definition at line 300 of file X86Subtarget.h.
References llvm::Triple::isWindowsMSVCEnvironment().
Referenced by llvm::X86FrameLowering::restoreWin32EHStackPointers(), and llvm::X86TargetLowering::X86TargetLowering().
isXRaySupported()
bool llvm::X86Subtarget::isXRaySupported () const inline override
Definition at line 266 of file X86Subtarget.h.
References is64Bit().
ParseSubtargetFeatures()
void llvm::X86Subtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
setPICStyle()
void llvm::X86Subtarget::setPICStyle (PICStyles::Style Style) inline
Definition at line 189 of file X86Subtarget.h.
Referenced by X86Subtarget().
swiftAsyncContextIsDynamicallySet()
bool llvm::X86Subtarget::swiftAsyncContextIsDynamicallySet () const inline
Return whether FrameLowering should always set the "extended frame present" bit in FP, or set it based on a symbol in the runtime.
Definition at line 386 of file X86Subtarget.h.
References llvm::Triple::Darwin, getTargetTriple(), llvm::Triple::IOS, llvm::Triple::MacOSX, llvm::Triple::TvOS, and llvm::Triple::WatchOS.
Referenced by llvm::X86FrameLowering::emitPrologue().
useAVX512Regs()
bool llvm::X86Subtarget::useAVX512Regs () const inline
Definition at line 254 of file X86Subtarget.h.
References canExtendTo512DQ(), and hasAVX512().
Referenced by llvm::X86TTIImpl::areTypesABICompatible(), combineAndShuffleNot(), combineConcatVectorOps(), combineExtSetcc(), combineTruncateWithSat(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineX86ShuffleChain(), llvm::X86TTIImpl::getCastInstrCost(), llvm::X86TargetLowering::getVectorTypeBreakdownForCallingConv(), handleMaskRegisterForCallingConv(), isLegalConversion(), SplitOpsAndApply(), supportedVectorShiftWithImm(), supportedVectorVarShift(), useBWIRegs(), and llvm::X86TargetLowering::X86TargetLowering().
useBWIRegs()
bool llvm::X86Subtarget::useBWIRegs () const inline
Definition at line 262 of file X86Subtarget.h.
References useAVX512Regs().
Referenced by combineConcatVectorOps(), lower1BitShuffle(), LowerABD(), LowerFunnelShift(), LowerRotate(), and SplitOpsAndApply().
useIndirectThunkBranches()
bool llvm::X86Subtarget::useIndirectThunkBranches () const inline
Definition at line 234 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::areJTsAllowed(), and enableIndirectBrExpand().
useIndirectThunkCalls()
bool llvm::X86Subtarget::useIndirectThunkCalls () const inline
Definition at line 231 of file X86Subtarget.h.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
useLight256BitInstructions()
bool llvm::X86Subtarget::useLight256BitInstructions () const inline
Definition at line 258 of file X86Subtarget.h.
References getPreferVectorWidth().
Referenced by llvm::X86TargetLowering::getOptimalMemOpType().
The documentation for this class was generated from the following files:
lib/Target/X86/X86Subtarget.h
lib/Target/X86/X86Subtarget.cpp