LLVM: llvm::VPlanPrinter Class Reference
llvm::VPlanPrinter Class Reference
VPlanPrinter prints a given VPlan to a given output stream.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPlanPrinter (raw_ostream &O, const VPlan &P)
LLVM_DUMP_METHOD void dump ()
Detailed Description
VPlanPrinter prints a given VPlan to a given output stream.
The printing is indented and follows the dot format.
Definition at line 2408 of file VPlan.h.
Constructor & Destructor Documentation
VPlanPrinter()
llvm::VPlanPrinter::VPlanPrinter (raw_ostream & O, const VPlan & P) inline
Definition at line 2449 of file VPlan.h.
References OS.
Member Function Documentation
dump()
void VPlanPrinter::dump ()
Definition at line 871 of file VPlan.cpp.
References llvm::Depth, llvm::DOT::EscapeString(), llvm::VPlan::getEntry(), llvm::VPlan::getName(), OS, llvm::VPTransformState::Plan, llvm::VPValue::print(), and llvm::vp_depth_first_shallow().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp