LLVM: llvm::DIEString Class Reference
llvm::DIEString Class Reference
A container for string pool string values.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEString (DwarfStringPoolEntryRef S)
StringRef getString () const
Grab the string out of the object.
void emitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit string value.
unsigned sizeOf (const dwarf::FormParams &FormParams, dwarf::Form Form) const
sizeOf - Determine size of delta value in bytes.
void print (raw_ostream &O) const
Detailed Description
A container for string pool string values.
This class is used with the DW_FORM_strp and DW_FORM_GNU_str_index forms.
Definition at line 273 of file DIE.h.
Constructor & Destructor Documentation
DIEString()
llvm::DIEString::DIEString (DwarfStringPoolEntryRef S) inline
Definition at line 277 of file DIE.h.
References S.
Member Function Documentation
emitValue()
void DIEString::emitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit string value.
Definition at line 572 of file DIE.cpp.
References llvm::AsmPrinter::doesDwarfUseRelocationsAcrossSections(), llvm::DIEInteger::emitValue(), llvm::DIELabel::emitValue(), llvm::DwarfStringPoolEntryRef::getIndex(), llvm::DwarfStringPoolEntryRef::getOffset(), llvm::DwarfStringPoolEntryRef::getSymbol(), and llvm_unreachable.
getString()
StringRef llvm::DIEString::getString () const inline
Grab the string out of the object.
Definition at line 280 of file DIE.h.
References S.
print()
LLVM_DUMP_METHOD void DIEString::print (raw_ostream & O) const
Definition at line 617 of file DIE.cpp.
References llvm::DwarfStringPoolEntryRef::getString(), and llvm::RISCVFenceField::O.
sizeOf()
unsigned DIEString::sizeOf (const dwarf::FormParams & FormParams, dwarf::Form Form) const
sizeOf - Determine size of delta value in bytes.
Definition at line 596 of file DIE.cpp.
References llvm::dwarf::FormParams::DwarfUsesRelocationsAcrossSections, llvm::DwarfStringPoolEntryRef::getIndex(), llvm::DwarfStringPoolEntryRef::getOffset(), llvm::DwarfStringPoolEntryRef::getSymbol(), llvm_unreachable, llvm::DIEInteger::sizeOf(), and llvm::DIELabel::sizeOf().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp