LLVM: llvm::M68kInstrInfo Class Reference
llvm::M68kInstrInfo Class Reference
#include "Target/M68k/M68kInstrInfo.h"
Public Member Functions
M68kInstrInfo (const M68kSubtarget &STI)
const M68kRegisterInfo & getRegisterInfo () const
TargetInstrInfo is a superset of MRegister info.
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
bool AnalyzeBranchImpl (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
bool getStackSlotRange (const TargetRegisterClass *RC, unsigned SubIdx, unsigned &Size, unsigned &Offset, const MachineFunction &MF) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, Register SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, Register DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, Register VReg) const override
bool expandPostRAPseudo (MachineInstr &MI) const override
bool isPCRelRegisterOperandLegal (const MachineOperand &MO) const override
void AddSExt (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned Reg, MVT From, MVT To) const
Add appropriate SExt nodes.
void AddZExt (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned Reg, MVT From, MVT To) const
Add appropriate ZExt nodes.
bool ExpandMOVX_RR (MachineInstrBuilder &MIB, MVT MVTDst, MVT MVTSrc) const
Move across register classes without extension.
bool ExpandMOVSZX_RR (MachineInstrBuilder &MIB, bool IsSigned, MVT MVTDst, MVT MVTSrc) const
Move from register and extend.
bool ExpandMOVSZX_RM (MachineInstrBuilder &MIB, bool IsSigned, const MCInstrDesc &Desc, MVT MVTDst, MVT MVTSrc) const
Move from memory and extend.
bool ExpandPUSH_POP (MachineInstrBuilder &MIB, const MCInstrDesc &Desc, bool IsPush) const
Push/Pop to/from stack.
bool ExpandCCR (MachineInstrBuilder &MIB, bool IsToCCR) const
Moves to/from CCR.
bool ExpandMOVEM (MachineInstrBuilder &MIB, const MCInstrDesc &Desc, bool IsRM) const
Expand all MOVEM pseudos into real MOVEMs.
unsigned getGlobalBaseReg (MachineFunction *MF) const
Return a virtual register initialized with the the global base register value.
std::pair< unsigned, unsigned > decomposeMachineOperandsTargetFlags (unsigned TF) const override
ArrayRef< std::pair< unsigned, const char * > > getSerializableDirectMachineOperandTargetFlags () const override
Static Public Member Functions
static const M68kInstrInfo * create (M68kSubtarget &STI)
Protected Attributes
const M68kSubtarget & Subtarget
const M68kRegisterInfo RI
Detailed Description
Definition at line 237 of file M68kInstrInfo.h.
Constructor & Destructor Documentation
M68kInstrInfo()
M68kInstrInfo::M68kInstrInfo (const M68kSubtarget & STI) explicit
Definition at line 43 of file M68kInstrInfo.cpp.
Member Function Documentation
AddSExt()
void M68kInstrInfo::AddSExt (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned Reg, MVT From, MVT To) const
Add appropriate SExt nodes.
Definition at line 313 of file M68kInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), DL, From, llvm::get(), I, llvm::MVT::i32, llvm::MVT::i8, MBB, and RI.
Referenced by ExpandMOVSZX_RM(), and ExpandMOVSZX_RR().
AddZExt()
void M68kInstrInfo::AddZExt (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned Reg, MVT From, MVT To) const
Add appropriate ZExt nodes.
Definition at line 330 of file M68kInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::And, llvm::BuildMI(), DL, From, llvm::get(), I, llvm::MVT::i16, llvm::MVT::i8, llvm::BitmaskEnumDetail::Mask(), and MBB.
Referenced by ExpandMOVSZX_RM(), and ExpandMOVSZX_RR().
analyzeBranch()
bool M68kInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 249 of file M68kInstrInfo.cpp.
References AnalyzeBranchImpl(), Cond, MBB, and TBB.
AnalyzeBranchImpl()
bool M68kInstrInfo::AnalyzeBranchImpl (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const
Definition at line 83 of file M68kInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), Cond, llvm::M68k::COND_INVALID, llvm::MachineOperand::CreateImm(), llvm::for_each(), llvm::get(), GetCondBranchFromCond(), llvm::M68k::GetCondFromBranchOpc(), llvm::M68k::GetOppositeBranchCondition(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::make_scope_exit(), MBB, llvm::MachineBasicBlock::push_back(), llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::rend(), llvm::MachineBasicBlock::rfindDebugLoc(), and TBB.
Referenced by analyzeBranch().
copyPhysReg()
void M68kInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 627 of file M68kInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), contains(), llvm::dbgs(), DL, llvm::get(), llvm::getKillRegState(), llvm::MachineBasicBlock::getParent(), LLVM_DEBUG, llvm_unreachable, MBB, MI, and RI.
create()
static const M68kInstrInfo* llvm::M68kInstrInfo::create (M68kSubtarget & STI) static
decomposeMachineOperandsTargetFlags()
std::pair< unsigned, unsigned > M68kInstrInfo::decomposeMachineOperandsTargetFlags (unsigned TF) const override
Definition at line 799 of file M68kInstrInfo.cpp.
ExpandCCR()
bool M68kInstrInfo::ExpandCCR (MachineInstrBuilder & MIB, bool IsToCCR) const
Moves to/from CCR.
Definition at line 489 of file M68kInstrInfo.cpp.
References llvm::get(), llvm::MachineInstr::getOperand(), getRegisterInfo(), llvm::MachineInstr::setDesc(), and llvm::MachineOperand::setReg().
ExpandMOVEM()
bool M68kInstrInfo::ExpandMOVEM (MachineInstrBuilder & MIB, const MCInstrDesc & Desc, bool IsRM) const
Expand all MOVEM pseudos into real MOVEMs.
Definition at line 506 of file M68kInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::sampleprof::Base, llvm::BuildMI(), llvm::MachineInstrBuilder::copyImplicitOps(), DL, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineInstrBuilder::getInstr(), llvm::M68kRegisterInfo::getMatchingMegaReg(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::M68kRegisterInfo::getSpillRegisterOrder(), llvm::RegState::Implicit, llvm::RegState::ImplicitDefine, llvm::BitmaskEnumDetail::Mask(), MBB, MI, llvm::Offset, and RI.
ExpandMOVSZX_RM()
bool M68kInstrInfo::ExpandMOVSZX_RM (MachineInstrBuilder & MIB, bool IsSigned, const MCInstrDesc & Desc, MVT MVTDst, MVT MVTSrc) const
Move from memory and extend.
Definition at line 436 of file M68kInstrInfo.cpp.
References AddSExt(), AddZExt(), assert(), llvm::dbgs(), DL, llvm::MachineInstr::getDebugLoc(), llvm::MachineInstrBuilder::getInstr(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), I, llvm::MVT::i8, LLVM_DEBUG, MBB, RI, llvm::MachineInstr::setDesc(), and llvm::MachineOperand::setReg().
ExpandMOVSZX_RR()
bool M68kInstrInfo::ExpandMOVSZX_RR (MachineInstrBuilder & MIB, bool IsSigned, MVT MVTDst, MVT MVTSrc) const
Move from register and extend.
Expand SExt MOVE pseudos into a MOV and a EXT if the operands are two different registers or just EXT if it is the same register.
Definition at line 387 of file M68kInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), AddSExt(), AddZExt(), assert(), llvm::BuildMI(), llvm::dbgs(), DL, llvm::MachineInstr::eraseFromParent(), llvm::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstrBuilder::getInstr(), llvm::M68kRegisterInfo::getMatchingMegaReg(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getRegisterInfo(), llvm::MVT::i16, LLVM_DEBUG, MBB, RI, and TRI.
ExpandMOVX_RR()
bool M68kInstrInfo::ExpandMOVX_RR (MachineInstrBuilder & MIB, MVT MVTDst, MVT MVTSrc) const
Move across register classes without extension.
Definition at line 349 of file M68kInstrInfo.cpp.
References assert(), llvm::dbgs(), DL, llvm::MachineInstr::eraseFromParent(), llvm::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstrBuilder::getInstr(), llvm::M68kRegisterInfo::getMatchingMegaReg(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getRegisterInfo(), llvm::MVT::i16, LLVM_DEBUG, RI, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), and TRI.
expandPostRAPseudo()
bool M68kInstrInfo::expandPostRAPseudo (MachineInstr & MI) const override
Definition at line 575 of file M68kInstrInfo.cpp.
References Expand2AddrUndef(), ExpandPUSH_POP(), llvm::get(), and MI.
ExpandPUSH_POP()
bool M68kInstrInfo::ExpandPUSH_POP (MachineInstrBuilder & MIB, const MCInstrDesc & Desc, bool IsPush) const
Push/Pop to/from stack.
Definition at line 473 of file M68kInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstrBuilder::getInstr(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::M68kRegisterInfo::getStackRegister(), I, MBB, and RI.
Referenced by expandPostRAPseudo().
getGlobalBaseReg()
unsigned M68kInstrInfo::getGlobalBaseReg (MachineFunction * MF) const
Return a virtual register initialized with the the global base register value.
Output instructions required to initialize the register in the function entry block, if necessary.
Output instructions required to initialize the register in the function entry block, if necessary.
TODO Move this function to M68kMachineFunctionInfo.
Definition at line 777 of file M68kInstrInfo.cpp.
References llvm::MachineRegisterInfo::createVirtualRegister(), llvm::M68kMachineFunctionInfo::getGlobalBaseReg(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::PPCISD::GlobalBaseReg, and llvm::M68kMachineFunctionInfo::setGlobalBaseReg().
getRegisterInfo()
const M68kRegisterInfo& llvm::M68kInstrInfo::getRegisterInfo () const inline
TargetInstrInfo is a superset of MRegister info.
As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 252 of file M68kInstrInfo.h.
References RI.
Referenced by ExpandCCR(), ExpandMOVSZX_RR(), ExpandMOVX_RR(), and llvm::M68kSubtarget::getRegisterInfo().
getSerializableDirectMachineOperandTargetFlags()
ArrayRef< std::pair< unsigned, const char * > > M68kInstrInfo::getSerializableDirectMachineOperandTargetFlags () const override
Definition at line 804 of file M68kInstrInfo.cpp.
References llvm::ArrayRef(), llvm::M68kII::MO_ABSOLUTE_ADDRESS, llvm::AArch64II::MO_GOT, llvm::CSKYII::MO_GOTOFF, llvm::M68kII::MO_GOTPCREL, llvm::M68kII::MO_PC_RELATIVE_ADDRESS, and llvm::M68kII::MO_PLT.
getStackSlotRange()
bool M68kInstrInfo::getStackSlotRange (const TargetRegisterClass * RC, unsigned SubIdx, unsigned & Size, unsigned & Offset, const MachineFunction & MF) const override
Definition at line 732 of file M68kInstrInfo.cpp.
References llvm::Offset.
insertBranch()
unsigned M68kInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 280 of file M68kInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), assert(), llvm::BuildMI(), CC, Cond, DL, llvm::get(), GetCondBranchFromCond(), MBB, and TBB.
isPCRelRegisterOperandLegal()
bool M68kInstrInfo::isPCRelRegisterOperandLegal (const MachineOperand & MO) const override
Definition at line 602 of file M68kInstrInfo.cpp.
References assert(), llvm::MachineOperand::getOperandNo(), llvm::MachineOperand::getParent(), llvm::MachineOperand::isReg(), llvm::Regex::match(), and MI.
loadRegFromStackSlot()
void M68kInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, Register DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg) const override
Definition at line 757 of file M68kInstrInfo.cpp.
References llvm::M68k::addFrameReference(), assert(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::findDebugLoc(), llvm::ISD::FrameIndex, llvm::get(), llvm::MachineFunction::getFrameInfo(), getLoadRegOpcode(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterInfo::getSpillSize(), MBB, MI, Subtarget, and TRI.
removeBranch()
unsigned M68kInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 257 of file M68kInstrInfo.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::M68k::COND_INVALID, llvm::MachineBasicBlock::end(), getCondFromBranchOpc(), I, and MBB.
storeRegToStackSlot()
void M68kInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, Register SrcReg, bool IsKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, Register VReg) const override
Definition at line 742 of file M68kInstrInfo.cpp.
References llvm::M68k::addFrameReference(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::findDebugLoc(), llvm::ISD::FrameIndex, llvm::get(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterInfo::getSpillSize(), getStoreRegOpcode(), MBB, MI, Subtarget, and TRI.
Member Data Documentation
RI
const M68kRegisterInfo llvm::M68kInstrInfo::RI protected
Definition at line 242 of file M68kInstrInfo.h.
Referenced by AddSExt(), copyPhysReg(), ExpandMOVEM(), ExpandMOVSZX_RM(), ExpandMOVSZX_RR(), ExpandMOVX_RR(), ExpandPUSH_POP(), and getRegisterInfo().
Subtarget
const M68kSubtarget& llvm::M68kInstrInfo::Subtarget protected
Definition at line 241 of file M68kInstrInfo.h.
Referenced by loadRegFromStackSlot(), and storeRegToStackSlot().
The documentation for this class was generated from the following files:
lib/Target/M68k/M68kInstrInfo.h
lib/Target/M68k/M68kInstrInfo.cpp