LLVM: llvm::codeview::CodeViewRecordIO Class Reference
llvm::codeview::CodeViewRecordIO Class Reference
#include "llvm/DebugInfo/CodeView/CodeViewRecordIO.h"
Public Member Functions
CodeViewRecordIO (BinaryStreamReader &Reader)
CodeViewRecordIO (BinaryStreamWriter &Writer)
CodeViewRecordIO (CodeViewRecordStreamer &Streamer)
Error beginRecord (std::optional< uint32_t > MaxLength)
Error endRecord ()
Error mapInteger (TypeIndex &TypeInd, const Twine &Comment="")
bool isStreaming () const
bool isReading () const
bool isWriting () const
uint32_t maxFieldLength () const
template<typename T >
Error mapObject (T &Value)
template<typename T >
Error mapInteger (T &Value, const Twine &Comment="")
template<typename T >
Error mapEnum (T &Value, const Twine &Comment="")
Error mapEncodedInteger (int64_t &Value, const Twine &Comment="")
Error mapEncodedInteger (uint64_t &Value, const Twine &Comment="")
Error mapEncodedInteger (APSInt &Value, const Twine &Comment="")
Error mapStringZ (StringRef &Value, const Twine &Comment="")
Error mapGuid (GUID &Guid, const Twine &Comment="")
Error mapStringZVectorZ (std::vector< StringRef > &Value, const Twine &Comment="")
template<typename SizeType , typename T , typename ElementMapper >
Error mapVectorN (T &Items, const ElementMapper &Mapper, const Twine &Comment="")
template<typename T , typename ElementMapper >
Error mapVectorTail (T &Items, const ElementMapper &Mapper, const Twine &Comment="")
Error mapByteVectorTail (ArrayRef< uint8_t > &Bytes, const Twine &Comment="")
Error mapByteVectorTail (std::vector< uint8_t > &Bytes, const Twine &Comment="")
Error padToAlignment (uint32_t Align)
Error skipPadding ()
uint64_t getStreamedLen ()
void emitRawComment (const Twine &T)
Detailed Description
Definition at line 43 of file CodeViewRecordIO.h.
Constructor & Destructor Documentation
CodeViewRecordIO() [1/3]
llvm::codeview::CodeViewRecordIO::CodeViewRecordIO (BinaryStreamReader & Reader) inline explicit
Definition at line 55 of file CodeViewRecordIO.h.
CodeViewRecordIO() [2/3]
llvm::codeview::CodeViewRecordIO::CodeViewRecordIO (BinaryStreamWriter & Writer) inline explicit
Definition at line 58 of file CodeViewRecordIO.h.
CodeViewRecordIO() [3/3]
llvm::codeview::CodeViewRecordIO::CodeViewRecordIO (CodeViewRecordStreamer & Streamer) inline explicit
Definition at line 61 of file CodeViewRecordIO.h.
Member Function Documentation
beginRecord()
Error CodeViewRecordIO::beginRecord (std::optional< uint32_t > MaxLength)
Definition at line 20 of file CodeViewRecordIO.cpp.
References llvm::Error::success().
Referenced by llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::SymbolRecordMapping::visitSymbolBegin(), and llvm::codeview::TypeRecordMapping::visitTypeBegin().
emitRawComment()
void llvm::codeview::CodeViewRecordIO::emitRawComment (const Twine & T) inline
Definition at line 213 of file CodeViewRecordIO.h.
References llvm::codeview::CodeViewRecordStreamer::AddRawComment(), isStreaming(), llvm::codeview::CodeViewRecordStreamer::isVerboseAsm(), and T.
Referenced by llvm::codeview::TypeRecordMapping::visitTypeBegin().
endRecord()
Error CodeViewRecordIO::endRecord ()
Definition at line 28 of file CodeViewRecordIO.cpp.
References Align, assert(), llvm::codeview::CodeViewRecordStreamer::emitBytes(), getStreamedLen(), isStreaming(), and llvm::Error::success().
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::codeview::SymbolRecordMapping::visitSymbolEnd(), and llvm::codeview::TypeRecordMapping::visitTypeEnd().
getStreamedLen()
uint64_t llvm::codeview::CodeViewRecordIO::getStreamedLen () inline
Definition at line 207 of file CodeViewRecordIO.h.
References isStreaming().
Referenced by endRecord().
isReading()
bool llvm::codeview::CodeViewRecordIO::isReading () const inline
Definition at line 72 of file CodeViewRecordIO.h.
Referenced by mapEnum(), mapStringZVectorZ(), padToAlignment(), and llvm::codeview::TypeRecordMapping::visitMemberEnd().
isStreaming()
bool llvm::codeview::CodeViewRecordIO::isStreaming () const inline
Definition at line 69 of file CodeViewRecordIO.h.
Referenced by emitRawComment(), endRecord(), getStreamedLen(), mapByteVectorTail(), mapEncodedInteger(), mapEnum(), mapGuid(), mapInteger(), mapObject(), mapStringZ(), mapVectorN(), mapVectorTail(), maxFieldLength(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), and llvm::codeview::TypeRecordMapping::visitTypeBegin().
isWriting()
bool llvm::codeview::CodeViewRecordIO::isWriting () const inline
Definition at line 75 of file CodeViewRecordIO.h.
Referenced by mapByteVectorTail(), mapEncodedInteger(), mapEnum(), mapGuid(), mapInteger(), mapNameAndUniqueName(), mapObject(), mapStringZ(), mapVectorN(), mapVectorTail(), and skipPadding().
mapByteVectorTail() [1/2]
Error CodeViewRecordIO::mapByteVectorTail (ArrayRef< uint8_t > & Bytes, const Twine & Comment = "")
Definition at line 102 of file CodeViewRecordIO.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::codeview::EC, llvm::codeview::CodeViewRecordStreamer::emitBinaryData(), isStreaming(), isWriting(), llvm::BinaryStreamReader::readBytes(), llvm::ArrayRef< T >::size(), llvm::Error::success(), llvm::dwarf::toStringRef(), and llvm::BinaryStreamWriter::writeBytes().
Referenced by mapByteVectorTail().
mapByteVectorTail() [2/2]
Error CodeViewRecordIO::mapByteVectorTail (std::vector< uint8_t > & Bytes, const Twine & Comment = "")
Definition at line 118 of file CodeViewRecordIO.cpp.
References llvm::ArrayRef< T >::begin(), llvm::codeview::EC, llvm::ArrayRef< T >::end(), isWriting(), mapByteVectorTail(), and llvm::Error::success().
mapEncodedInteger() [1/3]
Error CodeViewRecordIO::mapEncodedInteger (APSInt & Value, const Twine & Comment = "")
Definition at line 191 of file CodeViewRecordIO.cpp.
References llvm::codeview::consume(), INT64_MIN, isStreaming(), isWriting(), and llvm::Error::success().
mapEncodedInteger() [2/3]
Error CodeViewRecordIO::mapEncodedInteger (int64_t & Value, const Twine & Comment = "")
Definition at line 150 of file CodeViewRecordIO.cpp.
References llvm::codeview::consume(), llvm::codeview::EC, isStreaming(), isWriting(), N, llvm::Error::success(), and uint64_t.
mapEncodedInteger() [3/3]
Error CodeViewRecordIO::mapEncodedInteger (uint64_t & Value, const Twine & Comment = "")
Definition at line 175 of file CodeViewRecordIO.cpp.
References llvm::codeview::consume(), llvm::codeview::EC, isStreaming(), isWriting(), N, and llvm::Error::success().
mapEnum()
template<typename T > Error llvm::codeview::CodeViewRecordIO::mapEnum (T & Value, const Twine & Comment = "") inline
Definition at line 114 of file CodeViewRecordIO.h.
References llvm::codeview::EC, llvm::codeview::insufficient_buffer, isReading(), isStreaming(), isWriting(), mapInteger(), maxFieldLength(), llvm::Error::success(), T, and X.
Referenced by llvm::codeview::TypeRecordMapping::visitMemberBegin(), and llvm::codeview::TypeRecordMapping::visitTypeBegin().
mapGuid()
Error CodeViewRecordIO::mapGuid (GUID & Guid, const Twine & Comment = "")
Definition at line 227 of file CodeViewRecordIO.cpp.
References llvm::ArrayRef< T >::data(), llvm::codeview::EC, llvm::codeview::CodeViewRecordStreamer::emitBytes(), llvm::codeview::GUID::Guid, llvm::codeview::insufficient_buffer, isStreaming(), isWriting(), maxFieldLength(), memcpy(), llvm::BinaryStreamReader::readBytes(), llvm::Error::success(), and llvm::BinaryStreamWriter::writeBytes().
mapInteger() [1/2]
template<typename T > Error llvm::codeview::CodeViewRecordIO::mapInteger (T & Value, const Twine & Comment = "") inline
Definition at line 100 of file CodeViewRecordIO.h.
References llvm::codeview::CodeViewRecordStreamer::emitIntValue(), isStreaming(), isWriting(), llvm::BinaryStreamReader::readInteger(), llvm::Error::success(), T, and llvm::BinaryStreamWriter::writeInteger().
mapInteger() [2/2]
Error CodeViewRecordIO::mapInteger (TypeIndex & TypeInd, const Twine & Comment = "")
Definition at line 129 of file CodeViewRecordIO.cpp.
References llvm::codeview::EC, llvm::codeview::CodeViewRecordStreamer::emitIntValue(), llvm::codeview::TypeIndex::getIndex(), llvm::codeview::CodeViewRecordStreamer::getTypeName(), I, isStreaming(), isWriting(), llvm::BinaryStreamReader::readInteger(), llvm::codeview::TypeIndex::setIndex(), llvm::Error::success(), and llvm::BinaryStreamWriter::writeInteger().
Referenced by mapEnum(), mapLocalVariableAddrRange(), mapStringZVectorZ(), and llvm::codeview::TypeRecordMapping::visitTypeBegin().
mapObject()
template<typename T > Error llvm::codeview::CodeViewRecordIO::mapObject (T & Value) inline
Definition at line 81 of file CodeViewRecordIO.h.
References llvm::codeview::EC, llvm::codeview::CodeViewRecordStreamer::emitBytes(), isStreaming(), isWriting(), llvm::BinaryStreamReader::readObject(), llvm::Error::success(), T, and llvm::BinaryStreamWriter::writeObject().
mapStringZ()
Error CodeViewRecordIO::mapStringZ (StringRef & Value, const Twine & Comment = "")
Definition at line 209 of file CodeViewRecordIO.cpp.
References llvm::codeview::EC, llvm::codeview::CodeViewRecordStreamer::emitBytes(), isStreaming(), isWriting(), maxFieldLength(), llvm::BinaryStreamReader::readCString(), S, llvm::Error::success(), and llvm::BinaryStreamWriter::writeCString().
Referenced by mapNameAndUniqueName(), and mapStringZVectorZ().
mapStringZVectorZ()
Error CodeViewRecordIO::mapStringZVectorZ (std::vector< StringRef > & Value, const Twine & Comment = "")
Definition at line 254 of file CodeViewRecordIO.cpp.
References llvm::codeview::EC, isReading(), mapInteger(), mapStringZ(), S, and llvm::Error::success().
mapVectorN()
template<typename SizeType , typename T , typename ElementMapper > Error llvm::codeview::CodeViewRecordIO::mapVectorN (T & Items, const ElementMapper & Mapper, const Twine & Comment = "") inline
Definition at line 143 of file CodeViewRecordIO.h.
References llvm::codeview::EC, llvm::codeview::CodeViewRecordStreamer::emitIntValue(), I, isStreaming(), isWriting(), llvm::BinaryStreamReader::readInteger(), llvm::Error::success(), llvm::BinaryStreamWriter::writeInteger(), and X.
mapVectorTail()
template<typename T , typename ElementMapper > Error llvm::codeview::CodeViewRecordIO::mapVectorTail (T & Items, const ElementMapper & Mapper, const Twine & Comment = "") inline
Definition at line 180 of file CodeViewRecordIO.h.
References llvm::codeview::EC, llvm::BinaryStreamReader::empty(), isStreaming(), isWriting(), llvm::BinaryStreamReader::peek(), and llvm::Error::success().
maxFieldLength()
uint32_t CodeViewRecordIO::maxFieldLength () const
Definition at line 59 of file CodeViewRecordIO.cpp.
References llvm::ArrayRef(), assert(), isStreaming(), llvm::min(), and X.
Referenced by mapEnum(), mapGuid(), mapNameAndUniqueName(), and mapStringZ().
padToAlignment()
Error CodeViewRecordIO::padToAlignment (uint32_t Align)
Definition at line 81 of file CodeViewRecordIO.cpp.
References isReading(), llvm::BinaryStreamWriter::padToAlignment(), and llvm::BinaryStreamReader::padToAlignment().
Referenced by llvm::codeview::SymbolRecordMapping::visitSymbolEnd().
skipPadding()
Error CodeViewRecordIO::skipPadding ()
Definition at line 87 of file CodeViewRecordIO.cpp.
References assert(), llvm::BinaryStreamReader::bytesRemaining(), isWriting(), llvm::BinaryStreamReader::peek(), llvm::BinaryStreamReader::skip(), and llvm::Error::success().
Referenced by llvm::codeview::TypeRecordMapping::visitMemberEnd().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/CodeViewRecordIO.h
lib/DebugInfo/CodeView/CodeViewRecordIO.cpp