LLVM: llvm::TruncInstCombine Class Reference
llvm::TruncInstCombine Class Reference
#include "Transforms/AggressiveInstCombine/AggressiveInstCombineInternal.h"
Public Member Functions
TruncInstCombine (AssumptionCache &AC, TargetLibraryInfo &TLI, const DataLayout &DL, const DominatorTree &DT)
bool run (Function &F)
Perform TruncInst pattern optimization on given function.
Detailed Description
Definition at line 54 of file AggressiveInstCombineInternal.h.
Constructor & Destructor Documentation
TruncInstCombine()
llvm::TruncInstCombine::TruncInstCombine (AssumptionCache & AC, TargetLibraryInfo & TLI, const DataLayout & DL, const DominatorTree & DT) inline
Definition at line 82 of file AggressiveInstCombineInternal.h.
References DL.
Member Function Documentation
run()
bool TruncInstCombine::run (Function & F)
Perform TruncInst pattern optimization on given function.
Definition at line 525 of file TruncInstCombine.cpp.
References BB, llvm::dbgs(), F, I, llvm::DominatorTree::isReachableFromEntry(), LLVM_DEBUG, and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by runImpl().
The documentation for this class was generated from the following files:
lib/Transforms/AggressiveInstCombine/AggressiveInstCombineInternal.h
lib/Transforms/AggressiveInstCombine/TruncInstCombine.cpp