LLVM: llvm::LegalizationArtifactCombiner::ArtifactValueFinder Class Reference
llvm::LegalizationArtifactCombiner::ArtifactValueFinder Class Reference
This class provides utilities for finding source registers of specific bit ranges in an artifact.
#include "llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h"
Public Member Functions
ArtifactValueFinder (MachineRegisterInfo &Mri, MachineIRBuilder &Builder, const LegalizerInfo &Info)
Register findValueFromDef (Register DefReg, unsigned StartBit, unsigned Size)
Try to find a source of the value defined in the def DefReg, starting at position StartBit with size Size.
bool tryCombineUnmergeDefs (GUnmerge &MI, GISelChangeObserver &Observer, SmallVectorImpl< Register > &UpdatedDefs)
Try to combine the defs of an unmerge MI by attempting to find values that provides the bits for each def reg.
GUnmerge * findUnmergeThatDefinesReg (Register Reg, unsigned Size, unsigned &DefOperandIdx)
bool isSequenceFromUnmerge (GMergeLikeInstr &MI, unsigned MergeStartIdx, GUnmerge *Unmerge, unsigned UnmergeIdxStart, unsigned NumElts, unsigned EltSize)
bool tryCombineMergeLike (GMergeLikeInstr &MI, SmallVectorImpl< MachineInstr * > &DeadInsts, SmallVectorImpl< Register > &UpdatedDefs, GISelChangeObserver &Observer)
Detailed Description
This class provides utilities for finding source registers of specific bit ranges in an artifact.
The routines can look through the source registers if they're other artifacts to try to find a non-artifact source of a value.
Definition at line 556 of file LegalizationArtifactCombiner.h.
Constructor & Destructor Documentation
ArtifactValueFinder()
llvm::LegalizationArtifactCombiner::ArtifactValueFinder::ArtifactValueFinder (MachineRegisterInfo & Mri, MachineIRBuilder & Builder, const LegalizerInfo & Info) inline
Definition at line 768 of file LegalizationArtifactCombiner.h.
References Builder, and MRI.
Member Function Documentation
findUnmergeThatDefinesReg()
GUnmerge* llvm::LegalizationArtifactCombiner::ArtifactValueFinder::findUnmergeThatDefinesReg (Register Reg, unsigned Size, unsigned & DefOperandIdx) inline
Definition at line 815 of file LegalizationArtifactCombiner.h.
References llvm::tgtok::Def, llvm::MachineInstr::findRegisterDefOperandIdx(), and MRI.
Referenced by isSequenceFromUnmerge(), and tryCombineMergeLike().
findValueFromDef()
Register llvm::LegalizationArtifactCombiner::ArtifactValueFinder::findValueFromDef (Register DefReg, unsigned StartBit, unsigned Size) inline
Try to find a source of the value defined in the def DefReg, starting at position StartBit with size Size.
Returns
a register with the requested size, or an empty Register if no better value could be found.
Definition at line 776 of file LegalizationArtifactCombiner.h.
Referenced by tryCombineUnmergeDefs().
isSequenceFromUnmerge()
bool llvm::LegalizationArtifactCombiner::ArtifactValueFinder::isSequenceFromUnmerge (GMergeLikeInstr & MI, unsigned MergeStartIdx, GUnmerge * Unmerge, unsigned UnmergeIdxStart, unsigned NumElts, unsigned EltSize) inline
Definition at line 829 of file LegalizationArtifactCombiner.h.
References assert(), findUnmergeThatDefinesReg(), i, and MI.
Referenced by tryCombineMergeLike().
tryCombineMergeLike()
bool llvm::LegalizationArtifactCombiner::ArtifactValueFinder::tryCombineMergeLike (GMergeLikeInstr & MI, SmallVectorImpl< MachineInstr * > & DeadInsts, SmallVectorImpl< Register > & UpdatedDefs, GISelChangeObserver & Observer) inline
Definition at line 847 of file LegalizationArtifactCombiner.h.
References llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildUnmerge(), findUnmergeThatDefinesReg(), llvm::getCoverTy(), llvm::LLT::getSizeInBits(), i, isSequenceFromUnmerge(), llvm::LLT::isVector(), MI, MRI, llvm::LegalizationArtifactCombiner::replaceRegOrBuildCopy(), and llvm::MachineIRBuilder::setInstrAndDebugLoc().
Referenced by llvm::LegalizationArtifactCombiner::tryCombineInstruction().
tryCombineUnmergeDefs()
bool llvm::LegalizationArtifactCombiner::ArtifactValueFinder::tryCombineUnmergeDefs (GUnmerge & MI, GISelChangeObserver & Observer, SmallVectorImpl< Register > & UpdatedDefs) inline
Try to combine the defs of an unmerge MI by attempting to find values that provides the bits for each def reg.
Returns
true if all the defs of the unmerge have been made dead.
Definition at line 786 of file LegalizationArtifactCombiner.h.
References llvm::SmallBitVector::all(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), findValueFromDef(), llvm::LLT::getSizeInBits(), MI, MRI, and llvm::LegalizationArtifactCombiner::replaceRegOrBuildCopy().
Referenced by llvm::LegalizationArtifactCombiner::tryCombineUnmergeValues().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h