LLVM: llvm::FunctionVarLocs Class Reference
llvm::FunctionVarLocs Class Reference
Data structure describing the variable locations in a function.
#include "llvm/CodeGen/AssignmentTrackingAnalysis.h"
Public Member Functions
DILocalVariable * getDILocalVariable (const VarLocInfo *Loc) const
Return the DILocalVariable for the location definition represented by ID.
DILocalVariable * getDILocalVariable (VariableID ID) const
Return the DILocalVariable of the variable represented by ID.
const DebugVariable & getVariable (VariableID ID) const
Return the DebugVariable represented by ID.
void print (raw_ostream &OS, const Function &Fn) const
iterators
First single-location variable location definition.
const VarLocInfo * single_locs_begin () const
const VarLocInfo * single_locs_end () const
One past the last single-location variable location definition.
const VarLocInfo * locs_begin (const Instruction *Before) const
First variable location definition that comes before Before.
const VarLocInfo * locs_end (const Instruction *Before) const
One past the last variable location definition that comes before Before.
void init (FunctionVarLocsBuilder &Builder)
void clear ()
Detailed Description
Data structure describing the variable locations in a function.
Used as the result of the AssignmentTrackingAnalysis pass. Essentially read-only outside of AssignmentTrackingAnalysis where it is built.
Definition at line 30 of file AssignmentTrackingAnalysis.h.
Member Function Documentation
clear()
void FunctionVarLocs::clear ()
Definition at line 202 of file AssignmentTrackingAnalysis.cpp.
References llvm::SmallVectorImpl< T >::clear().
getDILocalVariable() [1/2]
DILocalVariable* llvm::FunctionVarLocs::getDILocalVariable (const VarLocInfo * Loc) const inline
Return the DILocalVariable for the location definition represented by ID.
Definition at line 47 of file AssignmentTrackingAnalysis.h.
References llvm::VarLocInfo::VariableID.
getDILocalVariable() [2/2]
DILocalVariable* llvm::FunctionVarLocs::getDILocalVariable (VariableID ID) const inline
Return the DILocalVariable of the variable represented by ID.
Definition at line 52 of file AssignmentTrackingAnalysis.h.
References getVariable(), and llvm::DebugVariable::getVariable().
getVariable()
const DebugVariable& llvm::FunctionVarLocs::getVariable (VariableID ID) const inline
Return the DebugVariable represented by ID.
Definition at line 56 of file AssignmentTrackingAnalysis.h.
Referenced by getDILocalVariable().
init()
void FunctionVarLocs::init (FunctionVarLocsBuilder & Builder)
Non-const methods used by AssignmentTrackingAnalysis (which invalidate analysis results if called incorrectly).
Definition at line 174 of file AssignmentTrackingAnalysis.cpp.
References assert(), Builder, llvm::SmallVectorImpl< T >::emplace_back(), and P.
locs_begin()
const VarLocInfo* llvm::FunctionVarLocs::locs_begin (const Instruction * Before) const inline
First variable location definition that comes before Before.
Definition at line 71 of file AssignmentTrackingAnalysis.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::lookup().
locs_end()
const VarLocInfo* llvm::FunctionVarLocs::locs_end (const Instruction * Before) const inline
One past the last variable location definition that comes before Before.
Definition at line 79 of file AssignmentTrackingAnalysis.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::lookup().
print()
void FunctionVarLocs::print (raw_ostream & OS, const Function & Fn) const
Definition at line 129 of file AssignmentTrackingAnalysis.cpp.
References F, llvm::AArch64PACKey::IA, OS, single_locs_begin(), and unsigned.
single_locs_begin()
const VarLocInfo* llvm::FunctionVarLocs::single_locs_begin () const inline
Definition at line 63 of file AssignmentTrackingAnalysis.h.
Referenced by print(), and processSingleLocVars().
single_locs_end()
const VarLocInfo* llvm::FunctionVarLocs::single_locs_end () const inline
One past the last single-location variable location definition.
Definition at line 65 of file AssignmentTrackingAnalysis.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AssignmentTrackingAnalysis.h
lib/CodeGen/AssignmentTrackingAnalysis.cpp