LLVM: llvm::DIGlobalVariable Class Reference
llvm::DIGlobalVariable Class Reference
Global variables.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DEFINE_MDNODE_GET (DIGlobalVariable,(DIScope *Scope, StringRef Name, StringRef LinkageName, DIFile *File, unsigned Line, DIType *Type, bool IsLocalToUnit, bool IsDefinition, DIDerivedType *StaticDataMemberDeclaration, MDTuple *TemplateParams, uint32_t AlignInBits, DINodeArray Annotations),(Scope, Name, LinkageName, File, Line, Type, IsLocalToUnit, IsDefinition, StaticDataMemberDeclaration, TemplateParams, AlignInBits, Annotations)) DEFINE_MDNODE_GET(DIGlobalVariable
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata Annotations TempDIGlobalVariable clone () const
bool isLocalToUnit () const
bool isDefinition () const
StringRef getDisplayName () const
StringRef getLinkageName () const
DIDerivedType * getStaticDataMemberDeclaration () const
DINodeArray getAnnotations () const
MDString * getRawLinkageName () const
Metadata * getRawStaticDataMemberDeclaration () const
Metadata * getRawTemplateParams () const
MDTuple * getTemplateParams () const
Metadata * getRawAnnotations () const
Public Member Functions inherited from llvm::DIVariable
unsigned getLine () const
DIScope * getScope () const
StringRef getName () const
DIFile * getFile () const
DIType * getType () const
uint32_t getAlignInBits () const
uint32_t getAlignInBytes () const
std::optional< uint64_t > getSizeInBits () const
Determines the size of the variable's type.
std::optional< DIBasicType::Signedness > getSignedness () const
Return the signedness of this variable's type, or std::nullopt if this type is neither signed nor unsigned.
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
Metadata * getRawScope () const
MDString * getRawName () const
Metadata * getRawFile () const
Metadata * getRawType () const
Public Member Functions inherited from llvm::DINode
dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIVariable
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
Metadata * Scope
Metadata MDString * Name
Metadata MDString MDString * LinkageName
Metadata MDString MDString Metadata * File
Metadata MDString MDString Metadata unsigned Line
Metadata MDString MDString Metadata unsigned Metadata * Type
Metadata MDString MDString Metadata unsigned Metadata bool IsLocalToUnit
Metadata MDString MDString Metadata unsigned Metadata bool bool IsDefinition
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata * StaticDataMemberDeclaration
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata * TemplateParams
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t AlignInBits
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata * Annotations
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata Scope
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata Name
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata LinkageName
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata File
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata Line
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata Type
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata IsLocalToUnit
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata IsDefinition
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata StaticDataMemberDeclaration
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata TemplateParams
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata AlignInBits
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic, FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIVariable
DIVariable (LLVMContext &C, unsigned ID, StorageType Storage, signed Line, ArrayRef< Metadata * > Ops, uint32_t AlignInBits=0)
~DIVariable ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Global variables.
TODO: Remove DisplayName. It's always equal to Name.
Definition at line 3026 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DIGlobalVariable::classof (const Metadata * MD) inline static
Definition at line 3106 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata Annotations TempDIGlobalVariable llvm::DIGlobalVariable::clone () const inline
Definition at line 3087 of file DebugInfoMetadata.h.
DEFINE_MDNODE_GET()
llvm::DIGlobalVariable::DEFINE_MDNODE_GET (DIGlobalVariable , (DIScope *Scope, StringRef Name, StringRef LinkageName, DIFile *File, unsigned Line, DIType *Type, bool IsLocalToUnit, bool IsDefinition, DIDerivedType *StaticDataMemberDeclaration, MDTuple *TemplateParams, uint32_t AlignInBits, DINodeArray Annotations) , (Scope, Name, LinkageName, File, Line, Type, IsLocalToUnit, IsDefinition, StaticDataMemberDeclaration, TemplateParams, AlignInBits, Annotations))
getAnnotations()
DINodeArray llvm::DIGlobalVariable::getAnnotations () const inline
Definition at line 3096 of file DebugInfoMetadata.h.
References getRawAnnotations().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
getDisplayName()
StringRef llvm::DIGlobalVariable::getDisplayName () const inline
Definition at line 3091 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
getLinkageName()
StringRef llvm::DIGlobalVariable::getLinkageName () const inline
Definition at line 3092 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by llvm::DwarfCompileUnit::addLocationAttribute().
getRawAnnotations()
Metadata* llvm::DIGlobalVariable::getRawAnnotations () const inline
Definition at line 3104 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getAnnotations().
getRawLinkageName()
MDString* llvm::DIGlobalVariable::getRawLinkageName () const inline
Definition at line 3100 of file DebugInfoMetadata.h.
getRawStaticDataMemberDeclaration()
Metadata* llvm::DIGlobalVariable::getRawStaticDataMemberDeclaration () const inline
Definition at line 3101 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getStaticDataMemberDeclaration().
getRawTemplateParams()
Metadata* llvm::DIGlobalVariable::getRawTemplateParams () const inline
Definition at line 3102 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
getStaticDataMemberDeclaration()
DIDerivedType* llvm::DIGlobalVariable::getStaticDataMemberDeclaration () const inline
Definition at line 3093 of file DebugInfoMetadata.h.
References getRawStaticDataMemberDeclaration().
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
getTemplateParams()
MDTuple* llvm::DIGlobalVariable::getTemplateParams () const inline
Definition at line 3103 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
isDefinition()
bool llvm::DIGlobalVariable::isDefinition () const inline
Definition at line 3090 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
isLocalToUnit()
bool llvm::DIGlobalVariable::isLocalToUnit () const inline
Definition at line 3089 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 3027 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 3028 of file DebugInfoMetadata.h.
Member Data Documentation
AlignInBits [1/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t llvm::DIGlobalVariable::AlignInBits
Definition at line 3083 of file DebugInfoMetadata.h.
AlignInBits [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::AlignInBits
Definition at line 3085 of file DebugInfoMetadata.h.
Annotations
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata* llvm::DIGlobalVariable::Annotations
Definition at line 3083 of file DebugInfoMetadata.h.
File [1/2]
Metadata MDString MDString Metadata* llvm::DIGlobalVariable::File
Definition at line 3080 of file DebugInfoMetadata.h.
File [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::File
Definition at line 3084 of file DebugInfoMetadata.h.
IsDefinition [1/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool llvm::DIGlobalVariable::IsDefinition
Definition at line 3081 of file DebugInfoMetadata.h.
IsDefinition [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::IsDefinition
Definition at line 3084 of file DebugInfoMetadata.h.
IsLocalToUnit [1/2]
Metadata MDString MDString Metadata unsigned Metadata bool llvm::DIGlobalVariable::IsLocalToUnit
Definition at line 3081 of file DebugInfoMetadata.h.
IsLocalToUnit [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::IsLocalToUnit
Definition at line 3084 of file DebugInfoMetadata.h.
Line [1/2]
Metadata MDString MDString Metadata unsigned llvm::DIGlobalVariable::Line
Definition at line 3081 of file DebugInfoMetadata.h.
Line [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::Line
Definition at line 3084 of file DebugInfoMetadata.h.
LinkageName [1/2]
Metadata MDString MDString* llvm::DIGlobalVariable::LinkageName
Definition at line 3080 of file DebugInfoMetadata.h.
LinkageName [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::LinkageName
Definition at line 3084 of file DebugInfoMetadata.h.
Name [1/2]
Metadata MDString* llvm::DIGlobalVariable::Name
Definition at line 3080 of file DebugInfoMetadata.h.
Name [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::Name
Definition at line 3084 of file DebugInfoMetadata.h.
Scope [1/2]
Metadata* llvm::DIGlobalVariable::Scope
Definition at line 3080 of file DebugInfoMetadata.h.
Scope [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::Scope
Definition at line 3084 of file DebugInfoMetadata.h.
StaticDataMemberDeclaration [1/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata* llvm::DIGlobalVariable::StaticDataMemberDeclaration
Definition at line 3082 of file DebugInfoMetadata.h.
StaticDataMemberDeclaration [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::StaticDataMemberDeclaration
Definition at line 3085 of file DebugInfoMetadata.h.
TemplateParams [1/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata* llvm::DIGlobalVariable::TemplateParams
Definition at line 3082 of file DebugInfoMetadata.h.
TemplateParams [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::TemplateParams
Definition at line 3085 of file DebugInfoMetadata.h.
Type [1/2]
Metadata MDString MDString Metadata unsigned Metadata* llvm::DIGlobalVariable::Type
Definition at line 3081 of file DebugInfoMetadata.h.
Type [2/2]
Metadata MDString MDString Metadata unsigned Metadata bool bool Metadata Metadata uint32_t Metadata llvm::DIGlobalVariable::Type
Definition at line 3084 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp