LLVM: llvm::RegOrConstant Class Reference
llvm::RegOrConstant Class Reference
Represents a value which can be a Register or a constant.
#include "llvm/CodeGen/GlobalISel/Utils.h"
Public Member Functions
RegOrConstant (Register Reg)
RegOrConstant (int64_t Cst)
bool isReg () const
bool isCst () const
Register getReg () const
int64_t getCst () const
Detailed Description
Represents a value which can be a Register or a constant.
This is useful in situations where an instruction may have an interesting register operand or interesting constant operand. For a concrete example,
See also
getVectorSplat.
Definition at line 352 of file Utils.h.
Constructor & Destructor Documentation
RegOrConstant() [1/2]
llvm::RegOrConstant::RegOrConstant (Register Reg) inline explicit
Definition at line 358 of file Utils.h.
RegOrConstant() [2/2]
llvm::RegOrConstant::RegOrConstant (int64_t Cst) inline explicit
Definition at line 359 of file Utils.h.
Member Function Documentation
getCst()
int64_t llvm::RegOrConstant::getCst () const inline
Definition at line 366 of file Utils.h.
References assert(), and isCst().
getReg()
Register llvm::RegOrConstant::getReg () const inline
Definition at line 362 of file Utils.h.
References assert(), and isReg().
isCst()
bool llvm::RegOrConstant::isCst () const inline
Definition at line 361 of file Utils.h.
Referenced by getCst().
isReg()
bool llvm::RegOrConstant::isReg () const inline
Definition at line 360 of file Utils.h.
Referenced by getReg().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/Utils.h