LLVM: llvm::SelectionDAG Class Reference
llvm::SelectionDAG Class Reference
This is used to represent a portion of an LLVM function in a low-level Data Dependence DAG representation suitable for instruction selection.
#include "llvm/CodeGen/SelectionDAG.h"
Classes
struct DAGNodeDeletedListener
struct DAGNodeInsertedListener
struct DAGUpdateListener
Clients of various APIs that cause global effects on the DAG can optionally implement this interface.
class FlagInserter
Help to insert SDNodeFlags automatically in transforming.
Public Types
enum OverflowKind { OFK_Never, OFK_Sometime, OFK_Always }
Used to represent the possible overflow behavior of an operation.
using allnodes_const_iterator = ilist< SDNode >::const_iterator
using allnodes_iterator = ilist< SDNode >::iterator
Public Member Functions
SelectionDAG (const TargetMachine &TM, CodeGenOpt::Level)
SelectionDAG (const SelectionDAG &)=delete
SelectionDAG & operator= (const SelectionDAG &)=delete
~SelectionDAG ()
void init (MachineFunction &NewMF, OptimizationRemarkEmitter &NewORE, Pass *PassPtr, const TargetLibraryInfo *LibraryInfo, LegacyDivergenceAnalysis *Divergence, ProfileSummaryInfo *PSIin, BlockFrequencyInfo *BFIin, FunctionVarLocs const *FnVarLocs)
Prepare this SelectionDAG to process code in the given MachineFunction.
void setFunctionLoweringInfo (FunctionLoweringInfo *FuncInfo)
void clear ()
Clear state and free memory necessary to make this SelectionDAG ready to process a new block.
MachineFunction & getMachineFunction () const
const Pass * getPass () const
const DataLayout & getDataLayout () const
const TargetMachine & getTarget () const
const TargetSubtargetInfo & getSubtarget () const
template<typename STC >
const STC & getSubtarget () const
const TargetLowering & getTargetLoweringInfo () const
const TargetLibraryInfo & getLibInfo () const
const SelectionDAGTargetInfo & getSelectionDAGInfo () const
const LegacyDivergenceAnalysis * getDivergenceAnalysis () const
const FunctionVarLocs * getFunctionVarLocs () const
Returns the result of the AssignmentTrackingAnalysis pass if it's available, otherwise return nullptr.
LLVMContext * getContext () const
OptimizationRemarkEmitter & getORE () const
ProfileSummaryInfo * getPSI () const
BlockFrequencyInfo * getBFI () const
FlagInserter * getFlagInserter ()
void setFlagInserter (FlagInserter *FI)
LLVM_DUMP_METHOD void dumpDotGraph (const Twine &FileName, const Twine &Title)
Just dump dot graph to a user-provided path and title.
void viewGraph (const std::string &Title)
Pop up a GraphViz/gv window with the DAG rendered using 'dot'.
void viewGraph ()
void clearGraphAttrs ()
Clear all previously defined node graph attributes.
void setGraphAttrs (const SDNode *N, const char *Attrs)
Set graph attributes for a node. (eg. "color=red".)
std::string getGraphAttrs (const SDNode *N) const
Get graph attributes for a node.
void setGraphColor (const SDNode *N, const char *Color)
Convenience for setting node color attribute.
void setSubgraphColor (SDNode *N, const char *Color)
Convenience for setting subgraph color attribute.
allnodes_const_iterator allnodes_begin () const
allnodes_const_iterator allnodes_end () const
allnodes_iterator allnodes_begin ()
allnodes_iterator allnodes_end ()
ilist< SDNode >::size_type allnodes_size () const
iterator_range< allnodes_iterator > allnodes ()
iterator_range< allnodes_const_iterator > allnodes () const
const SDValue & getRoot () const
Return the root tag of the SelectionDAG.
SDValue getEntryNode () const
Return the token chain corresponding to the entry of the function.
const SDValue & setRoot (SDValue N)
Set the current root tag of the SelectionDAG.
void VerifyDAGDivergence ()
void Combine (CombineLevel Level, AAResults *AA, CodeGenOpt::Level OptLevel)
This iterates over the nodes in the SelectionDAG, folding certain types of nodes together, or eliminating superfluous nodes.
bool LegalizeTypes ()
This transforms the SelectionDAG into a SelectionDAG that only uses types natively supported by the target.
void Legalize ()
This transforms the SelectionDAG into a SelectionDAG that is compatible with the target instruction selector, as indicated by the TargetLowering object.
bool LegalizeOp (SDNode *N, SmallSetVector< SDNode *, 16 > &UpdatedNodes)
Transforms a SelectionDAG node and any operands to it into a node that is compatible with the target instruction selector, as indicated by the TargetLowering object.
bool LegalizeVectors ()
This transforms the SelectionDAG into a SelectionDAG that only uses vector math operations supported by the target.
void RemoveDeadNodes ()
This method deletes all unreachable nodes in the SelectionDAG.
void DeleteNode (SDNode *N)
Remove the specified node from the system.
SDVTList getVTList (EVT VT)
Return an SDVTList that represents the list of values specified.
SDVTList getVTList (EVT VT1, EVT VT2)
SDVTList getVTList (EVT VT1, EVT VT2, EVT VT3)
SDVTList getVTList (EVT VT1, EVT VT2, EVT VT3, EVT VT4)
SDVTList getVTList (ArrayRef< EVT > VTs)
SDValue getGlobalAddress (const GlobalValue *GV, const SDLoc &DL, EVT VT, int64_t offset=0, bool isTargetGA=false, unsigned TargetFlags=0)
SDValue getTargetGlobalAddress (const GlobalValue *GV, const SDLoc &DL, EVT VT, int64_t offset=0, unsigned TargetFlags=0)
SDValue getFrameIndex (int FI, EVT VT, bool isTarget=false)
SDValue getTargetFrameIndex (int FI, EVT VT)
SDValue getJumpTable (int JTI, EVT VT, bool isTarget=false, unsigned TargetFlags=0)
SDValue getTargetJumpTable (int JTI, EVT VT, unsigned TargetFlags=0)
SDValue getConstantPool (const Constant *C, EVT VT, MaybeAlign Align=std::nullopt, int Offs=0, bool isT=false, unsigned TargetFlags=0)
SDValue getTargetConstantPool (const Constant *C, EVT VT, MaybeAlign Align=std::nullopt, int Offset=0, unsigned TargetFlags=0)
SDValue getConstantPool (MachineConstantPoolValue *C, EVT VT, MaybeAlign Align=std::nullopt, int Offs=0, bool isT=false, unsigned TargetFlags=0)
SDValue getTargetConstantPool (MachineConstantPoolValue *C, EVT VT, MaybeAlign Align=std::nullopt, int Offset=0, unsigned TargetFlags=0)
SDValue getTargetIndex (int Index, EVT VT, int64_t Offset=0, unsigned TargetFlags=0)
SDValue getBasicBlock (MachineBasicBlock *MBB)
SDValue getExternalSymbol (const char *Sym, EVT VT)
SDValue getTargetExternalSymbol (const char *Sym, EVT VT, unsigned TargetFlags=0)
SDValue getMCSymbol (MCSymbol *Sym, EVT VT)
SDValue getValueType (EVT)
SDValue getRegister (unsigned Reg, EVT VT)
SDValue getRegisterMask (const uint32_t *RegMask)
SDValue getEHLabel (const SDLoc &dl, SDValue Root, MCSymbol *Label)
SDValue getLabelNode (unsigned Opcode, const SDLoc &dl, SDValue Root, MCSymbol *Label)
SDValue getBlockAddress (const BlockAddress *BA, EVT VT, int64_t Offset=0, bool isTarget=false, unsigned TargetFlags=0)
SDValue getTargetBlockAddress (const BlockAddress *BA, EVT VT, int64_t Offset=0, unsigned TargetFlags=0)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, unsigned Reg, SDValue N)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, unsigned Reg, SDValue N, SDValue Glue)
SDValue getCopyToReg (SDValue Chain, const SDLoc &dl, SDValue Reg, SDValue N, SDValue Glue)
SDValue getCopyFromReg (SDValue Chain, const SDLoc &dl, unsigned Reg, EVT VT)
SDValue getCopyFromReg (SDValue Chain, const SDLoc &dl, unsigned Reg, EVT VT, SDValue Glue)
SDValue getCondCode (ISD::CondCode Cond)
SDValue getVectorShuffle (EVT VT, const SDLoc &dl, SDValue N1, SDValue N2, ArrayRef< int > Mask)
Return an ISD::VECTOR_SHUFFLE node.
SDValue getBuildVector (EVT VT, const SDLoc &DL, ArrayRef< SDValue > Ops)
Return an ISD::BUILD_VECTOR node.
SDValue getBuildVector (EVT VT, const SDLoc &DL, ArrayRef< SDUse > Ops)
Return an ISD::BUILD_VECTOR node.
SDValue getSplatBuildVector (EVT VT, const SDLoc &DL, SDValue Op)
Return a splat ISD::BUILD_VECTOR node, consisting of Op splatted to all elements.
SDValue getSplatVector (EVT VT, const SDLoc &DL, SDValue Op)
SDValue getSplat (EVT VT, const SDLoc &DL, SDValue Op)
Returns a node representing a splat of one value into all lanes of the provided vector type.
SDValue getStepVector (const SDLoc &DL, EVT ResVT, APInt StepVal)
Returns a vector of type ResVT whose elements contain the linear sequence <0, Step, Step * 2, Step * 3, ...>
SDValue getStepVector (const SDLoc &DL, EVT ResVT)
Returns a vector of type ResVT whose elements contain the linear sequence <0, 1, 2, 3, ...>
SDValue getCommutedVectorShuffle (const ShuffleVectorSDNode &SV)
Returns an ISD::VECTOR_SHUFFLE node semantically equivalent to the shuffle node in input but with swapped operands.
SDValue getFPExtendOrRound (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of float type, to the float type VT, by either extending or rounding (by truncation).
std::pair< SDValue, SDValue > getStrictFPExtendOrRound (SDValue Op, SDValue Chain, const SDLoc &DL, EVT VT)
Convert Op, which must be a STRICT operation of float type, to the float type VT, by either extending or rounding (by truncation).
SDValue getAnyExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either any-extending or truncating it.
SDValue getSExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either sign-extending or truncating it.
SDValue getZExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either zero-extending or truncating it.
SDValue getZeroExtendInReg (SDValue Op, const SDLoc &DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
SDValue getPtrExtOrTrunc (SDValue Op, const SDLoc &DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either truncating it or performing either zero or sign extension as appropriate extension for the pointer's semantics.
SDValue getPtrExtendInReg (SDValue Op, const SDLoc &DL, EVT VT)
Return the expression required to extend the Op as a pointer value assuming it was the smaller SrcTy value.
SDValue getBoolExtOrTrunc (SDValue Op, const SDLoc &SL, EVT VT, EVT OpVT)
Convert Op, which must be of integer type, to the integer type VT, by using an extension appropriate for the target's BooleanContent for type OpVT or truncating it.
SDValue getNegative (SDValue Val, const SDLoc &DL, EVT VT)
Create negative operation as (SUB 0, Val).
SDValue getNOT (const SDLoc &DL, SDValue Val, EVT VT)
Create a bitwise NOT operation as (XOR Val, -1).
SDValue getLogicalNOT (const SDLoc &DL, SDValue Val, EVT VT)
Create a logical NOT operation as (XOR Val, BooleanOne).
SDValue getVPLogicalNOT (const SDLoc &DL, SDValue Val, SDValue Mask, SDValue EVL, EVT VT)
Create a vector-predicated logical NOT operation as (VP_XOR Val, BooleanOne, Mask, EVL).
SDValue getVPZExtOrTrunc (const SDLoc &DL, EVT VT, SDValue Op, SDValue Mask, SDValue EVL)
Convert a vector-predicated Op, which must be an integer vector, to the vector-type VT, by performing either vector-predicated zext or truncating it.
SDValue getVPPtrExtOrTrunc (const SDLoc &DL, EVT VT, SDValue Op, SDValue Mask, SDValue EVL)
Convert a vector-predicated Op, which must be of integer type, to the vector-type integer type VT, by either truncating it or performing either vector-predicated zero or sign extension as appropriate extension for the pointer's semantics.
SDValue getMemBasePlusOffset (SDValue Base, TypeSize Offset, const SDLoc &DL, const SDNodeFlags Flags=SDNodeFlags())
Returns sum of the base pointer and offset.
SDValue getMemBasePlusOffset (SDValue Base, SDValue Offset, const SDLoc &DL, const SDNodeFlags Flags=SDNodeFlags())
SDValue getObjectPtrOffset (const SDLoc &SL, SDValue Ptr, TypeSize Offset)
Create an add instruction with appropriate flags when used for addressing some offset of an object.
SDValue getObjectPtrOffset (const SDLoc &SL, SDValue Ptr, SDValue Offset)
SDValue getCALLSEQ_START (SDValue Chain, uint64_t InSize, uint64_t OutSize, const SDLoc &DL)
Return a new CALLSEQ_START node, that starts new call frame, in which InSize bytes are set up inside CALLSEQ_START..CALLSEQ_END sequence and OutSize specifies part of the frame set up prior to the sequence.
SDValue getCALLSEQ_END (SDValue Chain, SDValue Op1, SDValue Op2, SDValue InGlue, const SDLoc &DL)
Return a new CALLSEQ_END node, which always must have a glue result (to ensure it's not CSE'd).
SDValue getCALLSEQ_END (SDValue Chain, uint64_t Size1, uint64_t Size2, SDValue Glue, const SDLoc &DL)
bool isUndef (unsigned Opcode, ArrayRef< SDValue > Ops)
Return true if the result of this operation is always undefined.
SDValue getUNDEF (EVT VT)
Return an UNDEF node. UNDEF does not have a useful SDLoc.
SDValue getVScale (const SDLoc &DL, EVT VT, APInt MulImm)
Return a node that represents the runtime scaling 'MulImm * RuntimeVL'.
SDValue getGLOBAL_OFFSET_TABLE (EVT VT)
Return a GLOBAL_OFFSET_TABLE node. This does not have a useful SDLoc.
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDUse > Ops)
Gets or creates the specified node.
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, ArrayRef< SDValue > Ops)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue Operand)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT)
Gets or creates the specified node.
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue Operand, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, const SDNodeFlags Flags)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
SDValue getNode (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
SDValue getNode (unsigned Opcode, const SDLoc &DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
SDValue getStackArgumentTokenFactor (SDValue Chain)
Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
SDValue getMemcpy (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, const AAMDNodes &AAInfo=AAMDNodes(), AAResults *AA=nullptr)
SDValue getMemmove (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, const AAMDNodes &AAInfo=AAMDNodes(), AAResults *AA=nullptr)
SDValue getMemset (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getAtomicMemcpy (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
SDValue getAtomicMemmove (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Src, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
SDValue getAtomicMemset (SDValue Chain, const SDLoc &dl, SDValue Dst, SDValue Value, SDValue Size, Type *SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo)
SDValue getSetCC (const SDLoc &DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Chain=SDValue(), bool IsSignaling=false)
Helper function to make it easier to build SetCC's if you just have an ISD::CondCode instead of an SDValue.
SDValue getSetCCVP (const SDLoc &DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Mask, SDValue EVL)
Helper function to make it easier to build VP_SETCCs if you just have an ISD::CondCode instead of an SDValue.
SDValue getSelect (const SDLoc &DL, EVT VT, SDValue Cond, SDValue LHS, SDValue RHS)
Helper function to make it easier to build Select's if you just have operands and don't want to check for vector.
SDValue getSelectCC (const SDLoc &DL, SDValue LHS, SDValue RHS, SDValue True, SDValue False, ISD::CondCode Cond)
Helper function to make it easier to build SelectCC's if you just have an ISD::CondCode instead of an SDValue.
SDValue simplifySelect (SDValue Cond, SDValue TVal, SDValue FVal)
Try to simplify a select/vselect into 1 of its operands or a constant.
SDValue simplifyShift (SDValue X, SDValue Y)
Try to simplify a shift into 1 of its operands or a constant.
SDValue simplifyFPBinop (unsigned Opcode, SDValue X, SDValue Y, SDNodeFlags Flags)
Try to simplify a floating-point binary operation into 1 of its operands or a constant.
SDValue getVAArg (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue SV, unsigned Align)
VAArg produces a result and token chain, and takes a pointer and a source value as input.
SDValue getAtomicCmpSwap (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDVTList VTs, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand *MMO)
Gets a node for an atomic cmpxchg op.
SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result (if relevant) and chain and takes 2 operands.
SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, EVT VT, SDValue Chain, SDValue Ptr, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result and chain and takes 1 operand.
SDValue getAtomic (unsigned Opcode, const SDLoc &dl, EVT MemVT, SDVTList VTList, ArrayRef< SDValue > Ops, MachineMemOperand *MMO)
Gets a node for an atomic op, produces result and chain and takes N operands.
SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags Flags=MachineMemOperand::MOLoad|MachineMemOperand::MOStore, uint64_t Size=0, const AAMDNodes &AAInfo=AAMDNodes())
Creates a MemIntrinsicNode that may produce a result and takes a list of operands.
SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, MaybeAlign Alignment=std::nullopt, MachineMemOperand::Flags Flags=MachineMemOperand::MOLoad|MachineMemOperand::MOStore, uint64_t Size=0, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getMemIntrinsicNode (unsigned Opcode, const SDLoc &dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachineMemOperand *MMO)
SDValue getLifetimeNode (bool IsStart, const SDLoc &dl, SDValue Chain, int FrameIndex, int64_t Size, int64_t Offset=-1)
Creates a LifetimeSDNode that starts (IsStart==true) or ends (IsStart==false) the lifetime of the portion of FrameIndex between offsets Offset and Offset + Size.
SDValue getPseudoProbeNode (const SDLoc &Dl, SDValue Chain, uint64_t Guid, uint64_t Index, uint32_t Attr)
Creates a PseudoProbeSDNode with function GUID Guid and the index of the block Index it is probing, as well as the attributes attr of the probe.
SDValue getMergeValues (ArrayRef< SDValue > Ops, const SDLoc &dl)
Create a MERGE_VALUES node from the given operands.
SDValue getLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
Loads are not normal binary operators: their result type is not determined by their operands, and they produce a value AND a token chain.
LLVM_DEPRECATED ("Use the getLoad function that takes a MaybeAlign instead", "") inline SDValue getLoad(EVT VT
FIXME: Remove once transition to Align is over.
SDValue getExtLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getExtLoad (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, EVT MemVT, MachineMemOperand *MMO)
SDValue getIndexedLoad (SDValue OrigLoad, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
LLVM_DEPRECATED ("Use the getLoad function that takes a MaybeAlign instead", "") inline SDValue getLoad(ISD
FIXME: Remove once transition to Align is over.
SDValue getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, EVT MemVT, MachineMemOperand *MMO)
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
Helper function to build ISD::STORE nodes.
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
FIXME: Remove once transition to Align is over.
SDValue getStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachineMemOperand *MMO)
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, unsigned Alignment, MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes())
FIXME: Remove once transition to Align is over.
SDValue getTruncStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, EVT SVT, MachineMemOperand *MMO)
SDValue getIndexedStore (SDValue OrigStore, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, const MDNode *Ranges=nullptr, bool IsExpanding=false)
SDValue getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr, bool IsExpanding=false)
SDValue getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, bool IsExpanding=false)
SDValue getLoadVP (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, const MDNode *Ranges=nullptr, bool IsExpanding=false)
SDValue getLoadVP (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachineMemOperand *MMO, bool IsExpanding=false)
SDValue getExtLoadVP (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, bool IsExpanding=false)
SDValue getExtLoadVP (ISD::LoadExtType ExtType, const SDLoc &dl, EVT VT, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, bool IsExpanding=false)
SDValue getIndexedLoadVP (SDValue OrigLoad, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getStoreVP (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, bool IsTruncating=false, bool IsCompressing=false)
SDValue getTruncStoreVP (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, bool IsCompressing=false)
SDValue getTruncStoreVP (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Ptr, SDValue Mask, SDValue EVL, EVT SVT, MachineMemOperand *MMO, bool IsCompressing=false)
SDValue getIndexedStoreVP (SDValue OrigStore, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getStridedLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &DL, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, const MDNode *Ranges=nullptr, bool IsExpanding=false)
SDValue getStridedLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &DL, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment=MaybeAlign(), MachineMemOperand::Flags MMOFlags=MachineMemOperand::MONone, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr, bool IsExpanding=false)
SDValue getStridedLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc &DL, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, bool IsExpanding=false)
SDValue getStridedLoadVP (EVT VT, const SDLoc &DL, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, const MDNode *Ranges=nullptr, bool IsExpanding=false)
SDValue getStridedLoadVP (EVT VT, const SDLoc &DL, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachineMemOperand *MMO, bool IsExpanding=false)
SDValue getExtStridedLoadVP (ISD::LoadExtType ExtType, const SDLoc &DL, EVT VT, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, bool IsExpanding=false)
SDValue getExtStridedLoadVP (ISD::LoadExtType ExtType, const SDLoc &DL, EVT VT, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, bool IsExpanding=false)
SDValue getIndexedStridedLoadVP (SDValue OrigLoad, const SDLoc &DL, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getStridedStoreVP (SDValue Chain, const SDLoc &DL, SDValue Val, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, bool IsTruncating=false, bool IsCompressing=false)
SDValue getTruncStridedStoreVP (SDValue Chain, const SDLoc &DL, SDValue Val, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes &AAInfo, bool IsCompressing=false)
SDValue getTruncStridedStoreVP (SDValue Chain, const SDLoc &DL, SDValue Val, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, EVT SVT, MachineMemOperand *MMO, bool IsCompressing=false)
SDValue getIndexedStridedStoreVP (SDValue OrigStore, const SDLoc &DL, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getGatherVP (SDVTList VTs, EVT VT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType)
SDValue getScatterVP (SDVTList VTs, EVT VT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType)
SDValue getMaskedLoad (EVT VT, const SDLoc &dl, SDValue Chain, SDValue Base, SDValue Offset, SDValue Mask, SDValue Src0, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, ISD::LoadExtType, bool IsExpanding=false)
SDValue getIndexedMaskedLoad (SDValue OrigLoad, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getMaskedStore (SDValue Chain, const SDLoc &dl, SDValue Val, SDValue Base, SDValue Offset, SDValue Mask, EVT MemVT, MachineMemOperand *MMO, ISD::MemIndexedMode AM, bool IsTruncating=false, bool IsCompressing=false)
SDValue getIndexedMaskedStore (SDValue OrigStore, const SDLoc &dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
SDValue getMaskedGather (SDVTList VTs, EVT MemVT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType, ISD::LoadExtType ExtTy)
SDValue getMaskedScatter (SDVTList VTs, EVT MemVT, const SDLoc &dl, ArrayRef< SDValue > Ops, MachineMemOperand *MMO, ISD::MemIndexType IndexType, bool IsTruncating=false)
SDValue getSrcValue (const Value *v)
Construct a node to track a Value* through the backend.
SDValue getMDNode (const MDNode *MD)
Return an MDNodeSDNode which holds an MDNode.
SDValue getBitcast (EVT VT, SDValue V)
Return a bitcast using the SDLoc of the value operand, and casting to the provided type.
SDValue getAddrSpaceCast (const SDLoc &dl, EVT VT, SDValue Ptr, unsigned SrcAS, unsigned DestAS)
Return an AddrSpaceCastSDNode.
SDValue getFreeze (SDValue V)
Return a freeze using the SDLoc of the value operand.
SDValue getAssertAlign (const SDLoc &DL, SDValue V, Align A)
Return an AssertAlignSDNode.
void canonicalizeCommutativeBinop (unsigned Opcode, SDValue &N1, SDValue &N2) const
Swap N1 and N2 if Opcode is a commutative binary opcode and the canonical form expects the opposite order.
SDValue getShiftAmountOperand (EVT LHSTy, SDValue Op)
Return the specified value casted to the target's desired shift amount type.
SDValue expandVAArg (SDNode *Node)
Expand the specified ISD::VAARG node as the Legalize pass would.
SDValue expandVACopy (SDNode *Node)
Expand the specified ISD::VACOPY node as the Legalize pass would.
SDValue getSymbolFunctionGlobalAddress (SDValue Op, Function **TargetFunction=nullptr)
Returs an GlobalAddress of the function from the current module with name matching the given ExternalSymbol.
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op)
Mutate the specified node in-place to have the specified operands.
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2)
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3)
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4)
SDNode * UpdateNodeOperands (SDNode *N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4, SDValue Op5)
SDNode * UpdateNodeOperands (SDNode *N, ArrayRef< SDValue > Ops)
SDValue getTokenFactor (const SDLoc &DL, SmallVectorImpl< SDValue > &Vals)
Creates a new TokenFactor containing Vals.
void setNodeMemRefs (MachineSDNode *N, ArrayRef< MachineMemOperand * > NewMemRefs)
Mutate the specified machine node's memory references to the provided list.
bool calculateDivergence (SDNode *N)
void updateDivergence (SDNode *N)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT)
These are used for target selectors to mutate the specified node to have the specified return type, Target opcode, and operands.
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT, ArrayRef< SDValue > Ops)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
SDNode * SelectNodeTo (SDNode *N, unsigned MachineOpc, SDVTList VTs, ArrayRef< SDValue > Ops)
SDNode * MorphNodeTo (SDNode *N, unsigned Opc, SDVTList VTs, ArrayRef< SDValue > Ops)
This mutates the specified node to have the specified return type, opcode, and operands.
SDNode * mutateStrictFPToFP (SDNode *Node)
Mutate the specified strict FP node to its non-strict equivalent, unlinking the node from its chain and dropping the metadata arguments.
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT)
These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1, SDValue Op2)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2, SDValue Op3)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2, SDValue Op3)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
MachineSDNode * getMachineNode (unsigned Opcode, const SDLoc &dl, SDVTList VTs, ArrayRef< SDValue > Ops)
SDValue getTargetExtractSubreg (int SRIdx, const SDLoc &DL, EVT VT, SDValue Operand)
A convenience function for creating TargetInstrInfo::EXTRACT_SUBREG nodes.
SDValue getTargetInsertSubreg (int SRIdx, const SDLoc &DL, EVT VT, SDValue Operand, SDValue Subreg)
A convenience function for creating TargetInstrInfo::INSERT_SUBREG nodes.
SDNode * getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Get the specified node if it's already available, or else return NULL.
SDNode * getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
getNodeIfExists - Get the specified node if it's already available, or else return NULL.
bool doesNodeExist (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
Check if a node exists without modifying its flags.
SDDbgValue * getDbgValue (DIVariable *Var, DIExpression *Expr, SDNode *N, unsigned R, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a SDDbgValue node.
SDDbgValue * getConstantDbgValue (DIVariable *Var, DIExpression *Expr, const Value *C, const DebugLoc &DL, unsigned O)
Creates a constant SDDbgValue node.
SDDbgValue * getFrameIndexDbgValue (DIVariable *Var, DIExpression *Expr, unsigned FI, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
SDDbgValue * getFrameIndexDbgValue (DIVariable *Var, DIExpression *Expr, unsigned FI, ArrayRef< SDNode * > Dependencies, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
SDDbgValue * getVRegDbgValue (DIVariable *Var, DIExpression *Expr, unsigned VReg, bool IsIndirect, const DebugLoc &DL, unsigned O)
Creates a VReg SDDbgValue node.
SDDbgValue * getDbgValueList (DIVariable *Var, DIExpression *Expr, ArrayRef< SDDbgOperand > Locs, ArrayRef< SDNode * > Dependencies, bool IsIndirect, const DebugLoc &DL, unsigned O, bool IsVariadic)
Creates a SDDbgValue node from a list of locations.
SDDbgLabel * getDbgLabel (DILabel *Label, const DebugLoc &DL, unsigned O)
Creates a SDDbgLabel node.
void transferDbgValues (SDValue From, SDValue To, unsigned OffsetInBits=0, unsigned SizeInBits=0, bool InvalidateDbg=true)
Transfer debug values from one node to another, while optionally generating fragment expressions for split-up values.
void RemoveDeadNode (SDNode *N)
Remove the specified node from the system.
void RemoveDeadNodes (SmallVectorImpl< SDNode * > &DeadNodes)
This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
void ReplaceAllUsesWith (SDValue From, SDValue To)
Modify anything using 'From' to use 'To' instead.
void ReplaceAllUsesWith (SDNode *From, SDNode *To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
void ReplaceAllUsesWith (SDNode *From, const SDValue *To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
void ReplaceAllUsesOfValueWith (SDValue From, SDValue To)
Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
void ReplaceAllUsesOfValuesWith (const SDValue *From, const SDValue *To, unsigned Num)
Like ReplaceAllUsesOfValueWith, but for multiple values at once.
SDValue makeEquivalentMemoryOrdering (SDValue OldChain, SDValue NewMemOpChain)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
SDValue makeEquivalentMemoryOrdering (LoadSDNode *OldLoad, SDValue NewMemOp)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
unsigned AssignTopologicalOrder ()
Topological-sort the AllNodes list and a assign a unique node id for each node in the DAG based on their topological order.
void RepositionNode (allnodes_iterator Position, SDNode *N)
Move node N in the AllNodes list to be immediately before the given iterator Position.
void AddDbgValue (SDDbgValue *DB, bool isParameter)
Add a dbg_value SDNode.
void AddDbgLabel (SDDbgLabel *DB)
Add a dbg_label SDNode.
ArrayRef< SDDbgValue * > GetDbgValues (const SDNode *SD) const
Get the debug values which reference the given SDNode.
bool hasDebugValues () const
Return true if there are any SDDbgValue nodes associated with this SelectionDAG.
SDDbgInfo::DbgIterator DbgBegin () const
SDDbgInfo::DbgIterator DbgEnd () const
SDDbgInfo::DbgIterator ByvalParmDbgBegin () const
SDDbgInfo::DbgIterator ByvalParmDbgEnd () const
SDDbgInfo::DbgLabelIterator DbgLabelBegin () const
SDDbgInfo::DbgLabelIterator DbgLabelEnd () const
void salvageDebugInfo (SDNode &N)
To be invoked on an SDNode that is slated to be erased.
void dump () const
Align getReducedAlign (EVT VT, bool UseABI)
In most cases this function returns the ABI alignment for a given type, except for illegal vector types where the alignment exceeds that of the stack.
SDValue CreateStackTemporary (TypeSize Bytes, Align Alignment)
Create a stack temporary based on the size in bytes and the alignment.
SDValue CreateStackTemporary (EVT VT, unsigned minAlign=1)
Create a stack temporary, suitable for holding the specified value type.
SDValue CreateStackTemporary (EVT VT1, EVT VT2)
Create a stack temporary suitable for holding either of the specified value types.
SDValue FoldSymbolOffset (unsigned Opcode, EVT VT, const GlobalAddressSDNode *GA, const SDNode *N2)
SDValue FoldConstantArithmetic (unsigned Opcode, const SDLoc &DL, EVT VT, ArrayRef< SDValue > Ops)
SDValue foldConstantFPMath (unsigned Opcode, const SDLoc &DL, EVT VT, SDValue N1, SDValue N2)
Fold floating-point operations with 2 operands when both operands are constants and/or undefined.
SDValue FoldSetCC (EVT VT, SDValue N1, SDValue N2, ISD::CondCode Cond, const SDLoc &dl)
Constant fold a setcc to true or false.
bool SignBitIsZero (SDValue Op, unsigned Depth=0) const
Return true if the sign bit of Op is known to be zero.
bool MaskedValueIsZero (SDValue Op, const APInt &Mask, unsigned Depth=0) const
Return true if 'Op & Mask' is known to be zero.
bool MaskedValueIsZero (SDValue Op, const APInt &Mask, const APInt &DemandedElts, unsigned Depth=0) const
Return true if 'Op & Mask' is known to be zero in DemandedElts.
bool MaskedVectorIsZero (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Return true if 'Op' is known to be zero in DemandedElts.
bool MaskedValueIsAllOnes (SDValue Op, const APInt &Mask, unsigned Depth=0) const
Return true if '(Op & Mask) == Mask'.
APInt computeVectorKnownZeroElements (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
For each demanded element of a vector, see if it is known to be zero.
KnownBits computeKnownBits (SDValue Op, unsigned Depth=0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
KnownBits computeKnownBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
OverflowKind computeOverflowKind (SDValue N0, SDValue N1) const
Determine if the result of the addition of 2 node can overflow.
bool isKnownToBeAPowerOfTwo (SDValue Val) const
Test if the given value is known to have exactly one bit set.
unsigned ComputeNumSignBits (SDValue Op, unsigned Depth=0) const
Return the number of times the sign bit of the register is replicated into the other bits.
unsigned ComputeNumSignBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Return the number of times the sign bit of the register is replicated into the other bits.
unsigned ComputeMaxSignificantBits (SDValue Op, unsigned Depth=0) const
Get the upper bound on bit size for this Value Op as a signed integer.
unsigned ComputeMaxSignificantBits (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Get the upper bound on bit size for this Value Op as a signed integer.
bool isGuaranteedNotToBeUndefOrPoison (SDValue Op, bool PoisonOnly=false, unsigned Depth=0) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
bool isGuaranteedNotToBeUndefOrPoison (SDValue Op, const APInt &DemandedElts, bool PoisonOnly=false, unsigned Depth=0) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
bool isGuaranteedNotToBePoison (SDValue Op, unsigned Depth=0) const
Return true if this function can prove that Op is never poison.
bool isGuaranteedNotToBePoison (SDValue Op, const APInt &DemandedElts, unsigned Depth=0) const
Return true if this function can prove that Op is never poison.
bool canCreateUndefOrPoison (SDValue Op, const APInt &DemandedElts, bool PoisonOnly=false, bool ConsiderFlags=true, unsigned Depth=0) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
bool canCreateUndefOrPoison (SDValue Op, bool PoisonOnly=false, bool ConsiderFlags=true, unsigned Depth=0) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
bool isBaseWithConstantOffset (SDValue Op) const
Return true if the specified operand is an ISD::ADD with a ConstantSDNode on the right-hand side, or if it is an ISD::OR with a ConstantSDNode that is guaranteed to have the same semantics as an ADD.
bool isKnownNeverNaN (SDValue Op, bool SNaN=false, unsigned Depth=0) const
Test whether the given SDValue (or all elements of it, if it is a vector) is known to never be NaN.
bool isKnownNeverSNaN (SDValue Op, unsigned Depth=0) const
bool isKnownNeverZeroFloat (SDValue Op) const
Test whether the given floating point SDValue is known to never be positive or negative zero.
bool isKnownNeverZero (SDValue Op) const
Test whether the given SDValue is known to contain non-zero value(s).
bool isEqualTo (SDValue A, SDValue B) const
Test whether two SDValues are known to compare equal.
bool haveNoCommonBitsSet (SDValue A, SDValue B) const
Return true if A and B have no common bits set.
bool isSplatValue (SDValue V, const APInt &DemandedElts, APInt &UndefElts, unsigned Depth=0) const
Test whether V has a splatted value for all the demanded elements.
bool isSplatValue (SDValue V, bool AllowUndefs=false) const
Test whether V has a splatted value.
SDValue getSplatSourceVector (SDValue V, int &SplatIndex)
If V is a splatted value, return the source vector and its splat index.
SDValue getSplatValue (SDValue V, bool LegalTypes=false)
If V is a splat vector, return its scalar source operand by extracting that element from the source vector.
const APInt * getValidShiftAmountConstant (SDValue V, const APInt &DemandedElts) const
If a SHL/SRA/SRL node V has a constant or splat constant shift amount that is less than the element bit-width of the shift node, return it.
const APInt * getValidMinimumShiftAmountConstant (SDValue V, const APInt &DemandedElts) const
If a SHL/SRA/SRL node V has constant shift amounts that are all less than the element bit-width of the shift node, return the minimum value.
const APInt * getValidMaximumShiftAmountConstant (SDValue V, const APInt &DemandedElts) const
If a SHL/SRA/SRL node V has constant shift amounts that are all less than the element bit-width of the shift node, return the maximum value.
SDValue matchBinOpReduction (SDNode *Extract, ISD::NodeType &BinOp, ArrayRef< ISD::NodeType > CandidateBinOps, bool AllowPartials=false)
Match a binop + shuffle pyramid that represents a horizontal reduction over the elements of a vector starting from the EXTRACT_VECTOR_ELT node /p Extract.
SDValue UnrollVectorOp (SDNode *N, unsigned ResNE=0)
Utility function used by legalize and lowering to "unroll" a vector operation by splitting out the scalars and operating on each element individually.
std::pair< SDValue, SDValue > UnrollVectorOverflowOp (SDNode *N, unsigned ResNE=0)
Like UnrollVectorOp(), but for the [US](ADD|SUB|MUL)O family of opcodes.
bool areNonVolatileConsecutiveLoads (LoadSDNode *LD, LoadSDNode *Base, unsigned Bytes, int Dist) const
Return true if loads are next to each other and can be merged.
MaybeAlign InferPtrAlign (SDValue Ptr) const
Infer alignment of a load / store address.
std::pair< EVT, EVT > GetSplitDestVTs (const EVT &VT) const
Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
std::pair< EVT, EVT > GetDependentSplitDestVTs (const EVT &VT, const EVT &EnvVT, bool *HiIsEmpty) const
Compute the VTs needed for the low/hi parts of a type, dependent on an enveloping VT that has been split into two identical pieces.
std::pair< SDValue, SDValue > SplitVector (const SDValue &N, const SDLoc &DL, const EVT &LoVT, const EVT &HiVT)
Split the vector with EXTRACT_SUBVECTOR using the provides VTs and return the low/high part.
std::pair< SDValue, SDValue > SplitVector (const SDValue &N, const SDLoc &DL)
Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
std::pair< SDValue, SDValue > SplitEVL (SDValue N, EVT VecVT, const SDLoc &DL)
Split the explicit vector length parameter of a VP operation.
std::pair< SDValue, SDValue > SplitVectorOperand (const SDNode *N, unsigned OpNo)
Split the node's operand with EXTRACT_SUBVECTOR and return the low/high part.
SDValue WidenVector (const SDValue &N, const SDLoc &DL)
Widen the vector up to the next power of two using INSERT_SUBVECTOR.
void ExtractVectorElements (SDValue Op, SmallVectorImpl< SDValue > &Args, unsigned Start=0, unsigned Count=0, EVT EltVT=EVT())
Append the extracted elements from Start to Count out of the vector Op in Args.
Align getEVTAlign (EVT MemoryVT) const
Compute the default alignment value for the given type.
SDNode * isConstantIntBuildVectorOrConstantInt (SDValue N) const
Test whether the given value is a constant int or similar node.
SDNode * isConstantFPBuildVectorOrConstantFP (SDValue N) const
Test whether the given value is a constant FP or similar node.
bool isConstantValueOfAnyType (SDValue N) const
void addCallSiteInfo (const SDNode *Node, CallSiteInfoImpl &&CallInfo)
Set CallSiteInfo to be associated with Node.
CallSiteInfo getCallSiteInfo (const SDNode *Node)
Return CallSiteInfo associated with Node, or a default if none exists.
void addHeapAllocSite (const SDNode *Node, MDNode *MD)
Set HeapAllocSite to be associated with Node.
MDNode * getHeapAllocSite (const SDNode *Node) const
Return HeapAllocSite associated with Node, or nullptr if none exists.
void addPCSections (const SDNode *Node, MDNode *MD)
Set PCSections to be associated with Node.
MDNode * getPCSections (const SDNode *Node) const
Return PCSections associated with Node, or nullptr if none exists.
void addNoMergeSiteInfo (const SDNode *Node, bool NoMerge)
Set NoMergeSiteInfo to be associated with Node if NoMerge is true.
bool getNoMergeSiteInfo (const SDNode *Node) const
Return NoMerge info associated with Node.
void copyExtraInfo (SDNode *From, SDNode *To)
Copy extra info associated with one node to another.
DenormalMode getDenormalMode (EVT VT) const
Return the current function's default denormal handling kind for the given floating point type.
bool shouldOptForSize () const
SDValue getNeutralElement (unsigned Opcode, const SDLoc &DL, EVT VT, SDNodeFlags Flags)
Get the (commutative) neutral element for the given opcode, if it exists.
bool isSafeToSpeculativelyExecute (unsigned Opcode) const
Some opcodes may create immediate undefined behavior when used with some values (integer division-by-zero for example).
SDValue getConstant (uint64_t Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
Create a ConstantSDNode wrapping a constant value.
SDValue getConstant (const APInt &Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
SDValue getAllOnesConstant (const SDLoc &DL, EVT VT, bool IsTarget=false, bool IsOpaque=false)
SDValue getConstant (const ConstantInt &Val, const SDLoc &DL, EVT VT, bool isTarget=false, bool isOpaque=false)
SDValue getIntPtrConstant (uint64_t Val, const SDLoc &DL, bool isTarget=false)
SDValue getShiftAmountConstant (uint64_t Val, EVT VT, const SDLoc &DL, bool LegalTypes=true)
SDValue getVectorIdxConstant (uint64_t Val, const SDLoc &DL, bool isTarget=false)
SDValue getTargetConstant (uint64_t Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getTargetConstant (const APInt &Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getTargetConstant (const ConstantInt &Val, const SDLoc &DL, EVT VT, bool isOpaque=false)
SDValue getBoolConstant (bool V, const SDLoc &DL, EVT VT, EVT OpVT)
Create a true or false constant of type VT using the target's BooleanContent for type OpVT.
SDValue getConstantFP (double Val, const SDLoc &DL, EVT VT, bool isTarget=false)
Create a ConstantFPSDNode wrapping a constant value.
SDValue getConstantFP (const APFloat &Val, const SDLoc &DL, EVT VT, bool isTarget=false)
SDValue getConstantFP (const ConstantFP &V, const SDLoc &DL, EVT VT, bool isTarget=false)
SDValue getTargetConstantFP (double Val, const SDLoc &DL, EVT VT)
SDValue getTargetConstantFP (const APFloat &Val, const SDLoc &DL, EVT VT)
SDValue getTargetConstantFP (const ConstantFP &Val, const SDLoc &DL, EVT VT)
Static Public Member Functions
static unsigned getOpcode_EXTEND (unsigned Opcode)
Convert *_EXTEND_VECTOR_INREG to *_EXTEND opcode.
static unsigned getOpcode_EXTEND_VECTOR_INREG (unsigned Opcode)
Convert *_EXTEND to *_EXTEND_VECTOR_INREG opcode.
static const fltSemantics & EVTToAPFloatSemantics (EVT VT)
Returns an APFloat semantics tag appropriate for the given type.
Public Attributes
bool NewNodesMustHaveLegalTypes = false
When true, additional steps are taken to ensure that getConstant() and similar functions return DAG nodes that have legal types.
const SDLoc & dl
const SDLoc SDValue Chain
const SDLoc SDValue SDValue Ptr
const SDLoc SDValue SDValue MachinePointerInfo PtrInfo
const SDLoc SDValue SDValue MachinePointerInfo unsigned Alignment
const SDLoc SDValue SDValue MachinePointerInfo unsigned MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone
const SDLoc SDValue SDValue MachinePointerInfo unsigned MachineMemOperand::Flags const AAMDNodes & AAInfo = AAMDNodes()
const SDLoc SDValue SDValue MachinePointerInfo unsigned MachineMemOperand::Flags const AAMDNodes const MDNode * Ranges
Static Public Attributes
static constexpr unsigned MaxRecursionDepth = 6
Friends
struct DAGUpdateListener
DAGUpdateListener is a friend so it can manipulate the listener stack.
Detailed Description
This is used to represent a portion of an LLVM function in a low-level Data Dependence DAG representation suitable for instruction selection.
This DAG is constructed as the first step of instruction selection in order to allow implementation of machine specific optimizations and code simplifications.
The representation used by the SelectionDAG is a target-independent representation, which has some similarities to the GCC RTL representation, but is significantly more simple, powerful, and is a graph form instead of a linear form.
Definition at line 221 of file SelectionDAG.h.
Member Typedef Documentation
allnodes_const_iterator
using llvm::SelectionDAG::allnodes_const_iterator = ilist<SDNode>::const_iterator
Definition at line 525 of file SelectionDAG.h.
allnodes_iterator
using llvm::SelectionDAG::allnodes_iterator = ilist<SDNode>::iterator
Definition at line 530 of file SelectionDAG.h.
Member Enumeration Documentation
OverflowKind
enum llvm::SelectionDAG::OverflowKind
Used to represent the possible overflow behavior of an operation.
Never: the operation cannot overflow. Always: the operation will always overflow. Sometime: the operation may or may not overflow.
Enumerator
OFK_Never
OFK_Sometime
OFK_Always
Definition at line 1981 of file SelectionDAG.h.
Constructor & Destructor Documentation
SelectionDAG() [1/2]
SelectionDAG::SelectionDAG (const TargetMachine & TM, CodeGenOpt::Level OL) explicit
Definition at line 1302 of file SelectionDAG.cpp.
References Other.
SelectionDAG() [2/2]
llvm::SelectionDAG::SelectionDAG (const SelectionDAG &) delete
~SelectionDAG()
SelectionDAG::~SelectionDAG ()
Definition at line 1329 of file SelectionDAG.cpp.
References assert().
Member Function Documentation
addCallSiteInfo()
void llvm::SelectionDAG::addCallSiteInfo (const SDNode * Node, CallSiteInfoImpl && CallInfo) inline
Set CallSiteInfo to be associated with Node.
Definition at line 2247 of file SelectionDAG.h.
AddDbgLabel()
void SelectionDAG::AddDbgLabel (SDDbgLabel * DB)
Add a dbg_label SDNode.
Definition at line 10862 of file SelectionDAG.cpp.
References llvm::SDDbgInfo::add(), and llvm::AArch64PACKey::DB.
AddDbgValue()
void SelectionDAG::AddDbgValue (SDDbgValue * DB, bool isParameter)
Add a dbg_value SDNode.
AddDbgValue - Add a dbg_value SDNode.
If SD is non-null that means the value is produced by SD.
Definition at line 10852 of file SelectionDAG.cpp.
References llvm::SDDbgInfo::add(), assert(), llvm::AArch64PACKey::DB, and llvm::SDDbgInfo::getSDDbgValues().
Referenced by llvm::SelectionDAGBuilder::addDanglingDebugInfo(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), salvageDebugInfo(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), and transferDbgValues().
addHeapAllocSite()
void llvm::SelectionDAG::addHeapAllocSite (const SDNode * Node, MDNode * MD) inline
Set HeapAllocSite to be associated with Node.
Definition at line 2256 of file SelectionDAG.h.
addNoMergeSiteInfo()
void llvm::SelectionDAG::addNoMergeSiteInfo (const SDNode * Node, bool NoMerge) inline
Set NoMergeSiteInfo to be associated with Node if NoMerge is true.
Definition at line 2274 of file SelectionDAG.h.
Referenced by llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), and llvm::SystemZTargetLowering::LowerCall().
addPCSections()
void llvm::SelectionDAG::addPCSections (const SDNode * Node, MDNode * MD) inline
Set PCSections to be associated with Node.
Definition at line 2265 of file SelectionDAG.h.
allnodes() [1/2]
iterator_range<allnodes_iterator> llvm::SelectionDAG::allnodes () inline
Definition at line 539 of file SelectionDAG.h.
References allnodes_begin(), allnodes_end(), and llvm::make_range().
Referenced by AssignTopologicalOrder(), and llvm::HexagonDAGToDAGISel::PreprocessISelDAG().
allnodes() [2/2]
iterator_range<allnodes_const_iterator> llvm::SelectionDAG::allnodes () const inline
Definition at line 542 of file SelectionDAG.h.
References allnodes_begin(), allnodes_end(), and llvm::make_range().
allnodes_begin() [1/2]
allnodes_iterator llvm::SelectionDAG::allnodes_begin () inline
Definition at line 532 of file SelectionDAG.h.
allnodes_begin() [2/2]
allnodes_const_iterator llvm::SelectionDAG::allnodes_begin () const inline
Definition at line 527 of file SelectionDAG.h.
Referenced by allnodes(), AssignTopologicalOrder(), Legalize(), llvm::RISCVDAGToDAGISel::PostprocessISelDAG(), AMDGPUDAGToDAGISel::PostprocessISelDAG(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), and AMDGPUDAGToDAGISel::PreprocessISelDAG().
allnodes_end() [1/2]
allnodes_iterator llvm::SelectionDAG::allnodes_end () inline
Definition at line 533 of file SelectionDAG.h.
allnodes_end() [2/2]
allnodes_const_iterator llvm::SelectionDAG::allnodes_end () const inline
Definition at line 528 of file SelectionDAG.h.
Referenced by allnodes(), Legalize(), llvm::RISCVDAGToDAGISel::PostprocessISelDAG(), AMDGPUDAGToDAGISel::PostprocessISelDAG(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), and AMDGPUDAGToDAGISel::PreprocessISelDAG().
allnodes_size()
ilist<SDNode>::size_type llvm::SelectionDAG::allnodes_size () const inline
Definition at line 535 of file SelectionDAG.h.
Referenced by llvm::HexagonDAGToDAGISel::PreprocessISelDAG().
areNonVolatileConsecutiveLoads()
bool SelectionDAG::areNonVolatileConsecutiveLoads (LoadSDNode * LD, LoadSDNode * Base, unsigned Bytes, int Dist) const
Return true if loads are next to each other and can be merged.
Check that both are nonvolatile and if LD is loading 'Bytes' bytes from a location that is 'Dist' units away from the location that the 'Base' load is loading from.
Definition at line 11557 of file SelectionDAG.cpp.
References llvm::sampleprof::Base, llvm::EVT::getSizeInBits(), llvm::ARM_MB::LD, llvm::PatternMatch::match(), and llvm::Offset.
Referenced by combineBVOfConsecutiveLoads(), combineINSERT_SUBVECTOR(), EltsFromConsecutiveLoads(), and lowerShuffleAsVTRUNC().
AssignTopologicalOrder()
unsigned SelectionDAG::AssignTopologicalOrder ()
Topological-sort the AllNodes list and a assign a unique node id for each node in the DAG based on their topological order.
AssignTopologicalOrder - Assign a unique node id for each node in the DAG based on their topological order.
Returns the number of nodes.
It returns the maximum id and a vector of the SDNodes* in assigned order by reference.
Definition at line 10766 of file SelectionDAG.cpp.
References allnodes(), allnodes_begin(), assert(), llvm::checkForCycles(), llvm::make_early_inc_range(), and N.
Referenced by Legalize().
ByvalParmDbgBegin()
SDDbgInfo::DbgIterator llvm::SelectionDAG::ByvalParmDbgBegin () const inline
Definition at line 1879 of file SelectionDAG.h.
References llvm::SDDbgInfo::ByvalParmDbgBegin().
ByvalParmDbgEnd()
SDDbgInfo::DbgIterator llvm::SelectionDAG::ByvalParmDbgEnd () const inline
Definition at line 1882 of file SelectionDAG.h.
References llvm::SDDbgInfo::ByvalParmDbgEnd().
calculateDivergence()
bool SelectionDAG::calculateDivergence (SDNode * N)
Definition at line 10638 of file SelectionDAG.cpp.
References assert(), llvm::TargetLowering::isSDNodeAlwaysUniform(), llvm::TargetLowering::isSDNodeSourceOfDivergence(), N, and llvm::MVT::Other.
Referenced by updateDivergence(), and VerifyDAGDivergence().
canCreateUndefOrPoison() [1/2]
bool SelectionDAG::canCreateUndefOrPoison (SDValue Op, bool PoisonOnly = false, bool ConsiderFlags = true, unsigned Depth = 0) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
ConsiderFlags controls whether poison producing flags on the instruction are considered. This can be used to see if the instruction could still introduce undef or poison even without poison generating flags which might be on the instruction. (i.e. could the result of Op->dropPoisonGeneratingFlags() still create poison or undef)
Definition at line 4733 of file SelectionDAG.cpp.
References canCreateUndefOrPoison(), llvm::Depth, llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), and llvm::EVT::isVector().
canCreateUndefOrPoison() [2/2]
bool SelectionDAG::canCreateUndefOrPoison (SDValue Op, const APInt & DemandedElts, bool PoisonOnly = false, bool ConsiderFlags = true, unsigned Depth = 0) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
The DemandedElts argument limits the check to the requested vector elements.
ConsiderFlags controls whether poison producing flags on the instruction are considered. This can be used to see if the instruction could still introduce undef or poison even without poison generating flags which might be on the instruction. (i.e. could the result of Op->dropPoisonGeneratingFlags() still create poison or undef)
Definition at line 4748 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::TargetLowering::canCreateUndefOrPoisonForTargetNode(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::CTPOP, llvm::Depth, llvm::ISD::FREEZE, llvm::ISD::FSHL, llvm::ISD::FSHR, getValidMaximumShiftAmountConstant(), llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::isScalableVector(), llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::PARITY, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SUB, llvm::ISD::TRUNCATE, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by canCreateUndefOrPoison(), and isGuaranteedNotToBeUndefOrPoison().
canonicalizeCommutativeBinop()
void SelectionDAG::canonicalizeCommutativeBinop (unsigned Opcode, SDValue & N1, SDValue & N2) const
Swap N1 and N2 if Opcode is a commutative binary opcode and the canonical form expects the opposite order.
Definition at line 6142 of file SelectionDAG.cpp.
References llvm::SDValue::getOpcode(), llvm::TargetLoweringBase::isCommutativeBinOp(), isConstantFPBuildVectorOrConstantFP(), isConstantIntBuildVectorOrConstantInt(), llvm::ISD::SPLAT_VECTOR, llvm::ISD::STEP_VECTOR, and std::swap().
Referenced by getNode().
clear()
void SelectionDAG::clear ()
Clear state and free memory necessary to make this SelectionDAG ready to process a new block.
Definition at line 1391 of file SelectionDAG.cpp.
References llvm::SDDbgInfo::clear(), getEntryNode(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset().
clearGraphAttrs()
void SelectionDAG::clearGraphAttrs ()
Clear all previously defined node graph attributes.
clearGraphAttrs - Clear all previously defined node graph attributes.
Intended to be used from a debugging tool (eg. gdb).
Definition at line 179 of file SelectionDAGPrinter.cpp.
References llvm::errs().
Combine()
void SelectionDAG::Combine (CombineLevel Level, AAResults * AA, CodeGenOpt::Level OptLevel)
This iterates over the nodes in the SelectionDAG, folding certain types of nodes together, or eliminating superfluous nodes.
This is the entry point for the file.
The Level argument controls whether Combine is allowed to produce nodes and types that are illegal on the target.
This is the main entry point to this class.
Definition at line 26963 of file DAGCombiner.cpp.
computeKnownBits() [1/2]
KnownBits SelectionDAG::computeKnownBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
The DemandedElts argument allows us to only collect the known bits that are shared by the requested vector elements. Targets can implement the computeKnownBitsForTargetNode method in the TargetLowering class to allow target nodes to be understood.
The DemandedElts argument allows us to only collect the known bits that are shared by the requested vector elements.
Definition at line 2973 of file SelectionDAG.cpp.
References llvm::KnownBits::abs(), llvm::ISD::ABS, llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDCARRY, llvm::ISD::ADDE, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::KnownBits::anyext(), llvm::KnownBits::ashr(), assert(), llvm::ISD::AssertAlign, llvm::ISD::AssertZext, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_SWAP, llvm::ISD::AVGCEILU, llvm::bit_width(), llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::BitWidth, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::KnownBits::byteSwap(), llvm::APInt::clearAllBits(), llvm::APInt::clearBit(), llvm::APInt::clearLowBits(), llvm::KnownBits::commonBits(), llvm::KnownBits::computeForAddCarry(), llvm::KnownBits::computeForAddSub(), computeKnownBits(), llvm::TargetLowering::computeKnownBitsForFrameIndex(), llvm::TargetLowering::computeKnownBitsForTargetNode(), llvm::computeKnownBitsFromRangeMetadata(), ComputeNumSignBits(), llvm::KnownBits::concat(), llvm::ISD::CONCAT_VECTORS, llvm::KnownBits::countMaxLeadingZeros(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMaxTrailingZeros(), llvm::KnownBits::countMinLeadingZeros(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::Depth, llvm::numbers::e, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::KnownBits::extractBits(), llvm::APInt::extractBits(), llvm::ISD::FGETSIGN, llvm::ISD::FP_TO_UINT_SAT, llvm::ISD::FrameIndex, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::Constant::getAggregateElement(), llvm::getAlign(), llvm::APInt::getAllOnes(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBitsSetFrom(), llvm::KnownBits::getBitWidth(), llvm::APInt::getBitWidth(), llvm::TargetLoweringBase::getBooleanContents(), getDataLayout(), llvm::TargetLoweringBase::getExtendForAtomicOps(), llvm::APInt::getHiBits(), llvm::APInt::getLowBitsSet(), getMachineFunction(), llvm::ShuffleVectorSDNode::getMask(), llvm::APInt::getNumSignBits(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::EVT::getScalarSizeInBits(), llvm::getShuffleDemandedElts(), llvm::EVT::getSizeInBits(), llvm::Constant::getSplatValue(), llvm::TargetLowering::getTargetConstantFromLoad(), llvm::Value::getType(), getValidMinimumShiftAmountConstant(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::APInt::getZero(), llvm::KnownBits::hasConflict(), i, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::KnownBits::insertBits(), llvm::APInt::insertBits(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isConstOrConstSplat(), llvm::EVT::isFloatingPoint(), isGuaranteedNotToBeUndefOrPoison(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::KnownBits::isNegative(), llvm::APInt::isNegative(), llvm::ISD::isNON_EXTLoad(), llvm::APInt::isNonNegative(), llvm::EVT::isScalableVector(), llvm::KnownBits::isUnknown(), llvm::EVT::isVector(), llvm::Type::isVectorTy(), llvm::ISD::isZEXTLoad(), llvm::ARM_MB::LD, LHS, llvm::ISD::LOAD, llvm::Log2(), llvm::KnownBits::lshr(), llvm::APInt::lshrInPlace(), llvm::KnownBits::makeConstant(), llvm::KnownBits::makeNonNegative(), MaxRecursionDepth, llvm::ISD::MERGE_VALUES, llvm::min(), llvm::ISD::MUL, llvm::KnownBits::mul(), llvm::KnownBits::mulhs(), llvm::ISD::MULHS, llvm::KnownBits::mulhu(), llvm::ISD::MULHU, llvm::ISD::NON_EXTLOAD, llvm::Offset, llvm::KnownBits::One, llvm::ISD::OR, llvm::ISD::PARITY, Ranges, llvm::KnownBits::resetAll(), llvm::KnownBits::reverseBits(), RHS, llvm::ISD::SADDO, llvm::ISD::SADDO_CARRY, llvm::ISD::SCALAR_TO_VECTOR, llvm::APIntOps::ScaleBitMask(), llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::APInt::setAllBits(), llvm::KnownBits::setAllZero(), llvm::APInt::setBit(), llvm::APInt::setBitsFrom(), llvm::ISD::SETCC, llvm::ISD::SETCCCARRY, llvm::APInt::setHighBits(), llvm::APInt::setLowBits(), llvm::KnownBits::sext(), llvm::KnownBits::sextInReg(), llvm::KnownBits::shl(), llvm::ISD::SHL, llvm::APInt::shl(), llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ArrayRef< T >::size(), llvm::APInt::sle(), llvm::KnownBits::smax(), llvm::ISD::SMAX, llvm::KnownBits::smin(), llvm::ISD::SMIN, llvm::ISD::SMUL_LOHI, llvm::ISD::SMULO, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::KnownBits::srem(), llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::SSUBO, llvm::ISD::SSUBO_CARRY, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::SUB, llvm::ISD::SUBC, llvm::ISD::SUBCARRY, std::swap(), llvm::ISD::TargetFrameIndex, llvm::KnownBits::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UDIV, llvm::KnownBits::udiv(), uint64_t, llvm::KnownBits::umax(), llvm::ISD::UMAX, llvm::KnownBits::umin(), llvm::ISD::UMIN, llvm::ISD::UMUL_LOHI, llvm::ISD::UMULO, llvm::ISD::UREM, llvm::KnownBits::urem(), llvm::ISD::USUBO, llvm::ISD::USUBSAT, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::KnownBits::Zero, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, llvm::KnownBits::zext(), llvm::APInt::zext(), and llvm::KnownBits::zextOrTrunc().
computeKnownBits() [2/2]
KnownBits SelectionDAG::computeKnownBits (SDValue Op, unsigned Depth = 0) const
Determine which bits of Op are known to be either zero or one and return them in Known.
For vectors, the known bits are those that are shared by every vector element. Targets can implement the computeKnownBitsForTargetNode method in the TargetLowering class to allow target nodes to be understood.
For vectors, the known bits are those that are shared by every vector element.
Definition at line 2958 of file SelectionDAG.cpp.
References llvm::Depth, llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isFixedLengthVector().
Referenced by adjustForRedundantAnd(), llvm::TargetLowering::BuildUDIV(), llvm::SelectionDAGISel::CheckOrMask(), checkZExtBool(), combineArithReduction(), combineMOVMSK(), combinePMULH(), combineScalarToVector(), combineShiftToAVG(), combineVectorSignBitsTruncation(), computeKnownBits(), computeKnownBitsBinOp(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), ComputeNumSignBits(), computeOverflowKind(), detectAVGPattern(), detectExtMul(), llvm::TargetLowering::expandFixedPointDiv(), foldMaskAndShiftToScale(), getPack(), haveNoCommonBitsSet(), isBitfieldPositioningOp(), isKnownToBeAPowerOfTwo(), isTruncateOf(), isWordAligned(), LowerAndToBT(), LowerAndToBTST(), LowerMUL(), lowerShuffleWithVPMOV(), MaskedValueIsAllOnes(), MaskedValueIsZero(), MaskedVectorIsZero(), matchBinaryShuffle(), llvm::AMDGPUTargetLowering::numBitsUnsigned(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performORCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), provablyDisjointOr(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::PPCTargetLowering::SelectAddressRegReg(), llvm::LoongArchDAGToDAGISel::selectShiftMask(), llvm::RISCVDAGToDAGISel::selectShiftMask(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifySetCC(), tryBitfieldInsertOpFromOr(), and tryBitfieldInsertOpFromOrAndImm().
ComputeMaxSignificantBits() [1/2]
unsigned SelectionDAG::ComputeMaxSignificantBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Get the upper bound on bit size for this Value Op as a signed integer.
i.e. x == sext(trunc(x to MaxSignedBits) to bitwidth(x)). Similar to the APInt::getSignificantBits function. Helper wrapper to ComputeNumSignBits.
Definition at line 4648 of file SelectionDAG.cpp.
References ComputeNumSignBits(), and llvm::Depth.
ComputeMaxSignificantBits() [2/2]
unsigned SelectionDAG::ComputeMaxSignificantBits (SDValue Op, unsigned Depth = 0) const
Get the upper bound on bit size for this Value Op as a signed integer.
i.e. x == sext(trunc(x to MaxSignedBits) to bitwidth(x)). Similar to the APInt::getSignificantBits function. Helper wrapper to ComputeNumSignBits.
Definition at line 4642 of file SelectionDAG.cpp.
References ComputeNumSignBits(), and llvm::Depth.
Referenced by combineMulToPMADDWD(), combinePMULH(), detectExtMul(), EmitCmp(), llvm::TargetLowering::expandMUL_LOHI(), getPack(), llvm::AMDGPUTargetLowering::numBitsSigned(), and llvm::TargetLowering::SimplifyDemandedBits().
ComputeNumSignBits() [1/2]
unsigned SelectionDAG::ComputeNumSignBits (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
Return the number of times the sign bit of the register is replicated into the other bits.
We know that at least 1 bit is always equal to the sign bit (itself), but other cases can give us information. For example, immediately after an "SRA X, 2", we know that the top 3 bits are all equal to each other, so we return 3. The DemandedElts argument allows us to only collect the minimum sign bits of the requested vector elements. Targets can implement the ComputeNumSignBitsForTarget method in the TargetLowering class to allow target nodes to be understood.
Definition at line 4021 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDCARRY, llvm::ISD::AND, assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BITCAST, llvm::BitWidth, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::APInt::clearBit(), computeKnownBits(), ComputeNumSignBits(), llvm::TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::ISD::CONCAT_VECTORS, llvm::KnownBits::countMinSignBits(), llvm::Depth, llvm::numbers::e, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::ISD::FP_TO_SINT_SAT, llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnes(), llvm::ConstantSDNode::getAPIntValue(), llvm::ConstantRange::getBitWidth(), llvm::APInt::getBitWidth(), llvm::TargetLoweringBase::getBooleanContents(), llvm::getConstantRangeFromMetadata(), getDataLayout(), llvm::TargetLoweringBase::getExtendForAtomicOps(), llvm::ShuffleVectorSDNode::getMask(), llvm::APInt::getNumSignBits(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::EVT::getScalarSizeInBits(), llvm::SDValue::getScalarValueSizeInBits(), llvm::getShuffleDemandedElts(), llvm::ConstantRange::getSignedMax(), llvm::ConstantRange::getSignedMin(), llvm::TargetLowering::getTargetConstantFromLoad(), getValidMaximumShiftAmountConstant(), getValidMinimumShiftAmountConstant(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::APInt::getZero(), i, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::APInt::insertBits(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isConstOrConstSplat(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::KnownBits::isNonNegative(), llvm::EVT::isScalableVector(), llvm::EVT::isVector(), llvm::Type::isVectorTy(), llvm::ARM_MB::LD, llvm::ISD::LOAD, llvm::max(), MaxRecursionDepth, llvm::ISD::MERGE_VALUES, llvm::min(), llvm::ISD::MUL, llvm::ISD::NON_EXTLOAD, llvm::ISD::OR, Ranges, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SADDO_CARRY, llvm::APIntOps::ScaleBitMask(), llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETCCCARRY, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ConstantRange::signExtend(), llvm::ArrayRef< T >::size(), llvm::APInt::sle(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMULO, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SSUBO, llvm::ISD::SSUBO_CARRY, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::SUB, llvm::ISD::SUBCARRY, std::swap(), llvm::ISD::TRUNCATE, llvm::ISD::UADDO, uint64_t, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMULO, llvm::ISD::USUBO, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::KnownBits::Zero, llvm::ISD::ZERO_EXTEND, llvm::ConstantRange::zeroExtend(), llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::APInt::zext(), and llvm::ISD::ZEXTLOAD.
ComputeNumSignBits() [2/2]
unsigned SelectionDAG::ComputeNumSignBits (SDValue Op, unsigned Depth = 0) const
Return the number of times the sign bit of the register is replicated into the other bits.
We know that at least 1 bit is always equal to the sign bit (itself), but other cases can give us information. For example, immediately after an "SRA X, 2", we know that the top 3 bits are all equal to each other, so we return 3. Targets can implement the ComputeNumSignBitsForTarget method in the TargetLowering class to allow target nodes to be understood.
Definition at line 4009 of file SelectionDAG.cpp.
References llvm::Depth, llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), and llvm::EVT::isFixedLengthVector().
Referenced by canReduceVMulWidth(), combineAnd(), combineAndMaskToShift(), combineGatherScatter(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMulToPMULDQ(), combinePredicateReduction(), combinePTESTCC(), combineSelect(), combineSetCCMOVMSK(), combineShiftToAVG(), combineSIntToFP(), combineVectorCompareAndMaskUnaryOp(), combineVectorPack(), combineVectorSignBitsTruncation(), combineVSelectWithAllOnesOrZeros(), computeKnownBits(), ComputeMaxSignificantBits(), ComputeNumSignBits(), computeNumSignBitsBinOp(), llvm::AMDGPUTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::RISCVTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::SystemZTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::TargetLowering::expandFixedPointDiv(), foldAddSubMasked1(), getFauxShuffleMask(), isS16(), LowerADDSAT_SUBSAT(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), lowerShuffleWithVPMOV(), LowerTruncateVecI1(), lowerVectorIntrinsicScalars(), matchShuffleWithPACK(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::RISCVDAGToDAGISel::selectSExtBits(), llvm::LoongArchDAGToDAGISel::selectSExti32(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), and llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode().
computeOverflowKind()
SelectionDAG::OverflowKind SelectionDAG::computeOverflowKind (SDValue N0, SDValue N1) const
Determine if the result of the addition of 2 node can overflow.
Definition at line 3925 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::APInt::getBoolValue(), llvm::KnownBits::getMaxValue(), llvm::SDValue::getOpcode(), llvm::SDValue::getResNo(), llvm::isNullConstant(), OFK_Never, OFK_Sometime, llvm::APInt::uadd_ov(), llvm::ISD::UMUL_LOHI, and llvm::KnownBits::Zero.
computeVectorKnownZeroElements()
APInt SelectionDAG::computeVectorKnownZeroElements (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const
For each demanded element of a vector, see if it is known to be zero.
Definition at line 2586 of file SelectionDAG.cpp.
References assert(), llvm::Depth, llvm::APInt::getBitWidth(), llvm::APInt::getNullValue(), llvm::APInt::getOneBitSet(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), llvm::EVT::isVector(), llvm::BitmaskEnumDetail::Mask(), MaskedVectorIsZero(), and llvm::APInt::setBit().
Referenced by combineShuffleToZeroExtendVectorInReg().
copyExtraInfo()
void SelectionDAG::copyExtraInfo (SDNode * From, SDNode * To)
Copy extra info associated with one node to another.
Definition at line 12196 of file SelectionDAG.cpp.
References assert(), From, I, and move.
Referenced by ReplaceAllUsesOfValuesWith(), ReplaceAllUsesOfValueWith(), and ReplaceAllUsesWith().
CreateStackTemporary() [1/3]
SDValue SelectionDAG::CreateStackTemporary (EVT VT, unsigned minAlign = 1)
Create a stack temporary, suitable for holding the specified value type.
If minAlign is specified, the slot size will have at least that alignment.
Definition at line 2381 of file SelectionDAG.cpp.
References Align, CreateStackTemporary(), getContext(), getDataLayout(), getPrefTypeAlign(), llvm::EVT::getStoreSize(), llvm::EVT::getTypeForEVT(), and llvm::max().
CreateStackTemporary() [2/3]
SDValue SelectionDAG::CreateStackTemporary (EVT VT1, EVT VT2)
Create a stack temporary suitable for holding either of the specified value types.
Definition at line 2388 of file SelectionDAG.cpp.
References assert(), CreateStackTemporary(), DL, getContext(), getDataLayout(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::EVT::getStoreSize(), llvm::EVT::getTypeForEVT(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), and llvm::max().
CreateStackTemporary() [3/3]
SDValue SelectionDAG::CreateStackTemporary (TypeSize Bytes, Align Alignment)
Create a stack temporary based on the size in bytes and the alignment.
Definition at line 2368 of file SelectionDAG.cpp.
References Alignment, llvm::MachineFrameInfo::CreateStackObject(), getDataLayout(), getFrameIndex(), llvm::TargetLoweringBase::getFrameIndexTy(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::TargetFrameLowering::getStackIDForScalableVectors(), llvm::MachineFunction::getSubtarget(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
Referenced by CreateStackTemporary(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::ARMTargetLowering::PerformMVEExtCombine(), and llvm::ARMTargetLowering::PerformMVETruncCombine().
DbgBegin()
SDDbgInfo::DbgIterator llvm::SelectionDAG::DbgBegin () const inline
Definition at line 1876 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgBegin().
DbgEnd()
SDDbgInfo::DbgIterator llvm::SelectionDAG::DbgEnd () const inline
Definition at line 1877 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgEnd().
DbgLabelBegin()
SDDbgInfo::DbgLabelIterator llvm::SelectionDAG::DbgLabelBegin () const inline
Definition at line 1886 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgLabelBegin().
DbgLabelEnd()
SDDbgInfo::DbgLabelIterator llvm::SelectionDAG::DbgLabelEnd () const inline
Definition at line 1889 of file SelectionDAG.h.
References llvm::SDDbgInfo::DbgLabelEnd().
DeleteNode()
void SelectionDAG::DeleteNode (SDNode * N)
Remove the specified node from the system.
This node must have no referrers.
Definition at line 1033 of file SelectionDAG.cpp.
References N.
Referenced by Legalize(), and llvm::SelectionDAGBuilder::LowerAsSTATEPOINT().
doesNodeExist()
bool SelectionDAG::doesNodeExist (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
Check if a node exists without modifying its flags.
doesNodeExist - Check if a node exists without modifying its flags.
Definition at line 10108 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::MVT::Glue, llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
Referenced by foldAndOrOfSETCC(), and llvm::TargetLowering::SimplifySetCC().
dump()
LLVM_DUMP_METHOD void SelectionDAG::dump () const
Definition at line 930 of file SelectionDAGDumper.cpp.
Referenced by NewSDValueDbgMsg(), llvm::HexagonDAGToDAGISel::PreprocessISelDAG(), and AMDGPUDAGToDAGISel::PreprocessISelDAG().
dumpDotGraph()
LLVM_DUMP_METHOD void SelectionDAG::dumpDotGraph (const Twine & FileName, const Twine & Title)
Just dump dot graph to a user-provided path and title.
This doesn't open the dot viewer program and helps visualization when outside debugging session. FileName expects absolute path. If provided without any path separators then the file will be created in the current directory. Error will be emitted if the path is insane.
Definition at line 171 of file SelectionDAGPrinter.cpp.
References llvm::dumpDotGraphToFile().
EVTToAPFloatSemantics()
static const fltSemantics& llvm::SelectionDAG::EVTToAPFloatSemantics (EVT VT) inline static
Returns an APFloat semantics tag appropriate for the given type.
If VT is a vector type, the element semantics are returned.
Definition at line 1846 of file SelectionDAG.h.
References llvm::MVT::bf16, llvm::APFloatBase::BFloat(), llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm_unreachable, llvm::APFloatBase::PPCDoubleDouble(), llvm::MVT::ppcf128, llvm::MVT::SimpleTy, and llvm::APFloatBase::x87DoubleExtended().
Referenced by foldConstantFPMath(), FoldIntToFPToInt(), getConstantFP(), getDenormalMode(), getMemsetValue(), getNeutralElement(), getNode(), llvm::TargetLowering::getSqrtInputTest(), llvm::isNeutralConstant(), llvm::ConstantFPSDNode::isValueValidForType(), LowerFABSorFNEG(), LowerFCOPYSIGN(), LowerFROUND(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), lowerShuffleAsBitMask(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), and llvm::TargetLowering::SimplifyDemandedBits().
expandVAArg()
SDValue SelectionDAG::expandVAArg (SDNode * Node)
Expand the specified ISD::VAARG node as the Legalize pass would.
Definition at line 2292 of file SelectionDAG.cpp.
expandVACopy()
SDValue SelectionDAG::expandVACopy (SDNode * Node)
Expand the specified ISD::VACOPY node as the Legalize pass would.
Definition at line 2326 of file SelectionDAG.cpp.
Referenced by LowerVACOPY().
ExtractVectorElements()
void SelectionDAG::ExtractVectorElements (SDValue Op, SmallVectorImpl< SDValue > & Args, unsigned Start = 0, unsigned Count = 0, EVT EltVT = EVT())
Append the extracted elements from Start to Count out of the vector Op in Args.
If Count is 0, all of the elements will be extracted. The extracted elements will have type EVT if it is provided, and otherwise their type will be Op's element type.
Definition at line 11713 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::numbers::e, llvm::ISD::EXTRACT_VECTOR_ELT, getNode(), llvm::EVT::getVectorElementType(), getVectorIdxConstant(), llvm::EVT::getVectorNumElements(), and i.
Referenced by adjustLoadValueTypeImpl(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), padEltsToUndef(), UnrollVectorOverflowOp(), unrollVectorShift(), and widenVectorToPartType().
FoldConstantArithmetic()
SDValue SelectionDAG::FoldConstantArithmetic (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 5821 of file SelectionDAG.cpp.
References llvm::all_of(), assert(), llvm::ISD::BITCAST, llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, C1, llvm::ISD::CONCAT_VECTORS, llvm::ISD::CONDCODE, llvm::ISD::Constant, llvm::ISD::ConstantFP, DL, E, foldConstantFPMath(), FoldSymbolOffset(), FoldValue(), FoldValueWithUndef(), getBitcast(), llvm::TargetLoweringBase::getBooleanContents(), getBuildVector(), getConstant(), getContext(), getDataLayout(), llvm::TargetLoweringBase::getExtendForContent(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), getNode(), getOpcode(), llvm::SDValue::getOpcode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), getSplatVector(), getStepVector(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeToTransformTo(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), I, llvm::MVT::i1, llvm::TargetLoweringBase::isCommutativeBinOp(), llvm::ISD::isConstantSplatVector(), llvm::EVT::isFixedLengthVector(), llvm::EVT::isInteger(), llvm::DataLayout::isLittleEndian(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::SDValue::isUndef(), isUndef(), llvm::EVT::isVector(), llvm::ISD::MUL, NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), llvm::peekThroughBitcasts(), llvm::BuildVectorSDNode::recastRawBits(), llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ArrayRef< T >::size(), llvm::ISD::SPLAT_VECTOR, llvm::ISD::STEP_VECTOR, llvm::ISD::TRUNCATE, and llvm::TargetLoweringBase::TypeLegal.
Referenced by foldAddSubOfSignBit(), getNode(), getTargetVShiftByConstNode(), getTargetVShiftNode(), LowerRotate(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifyDemandedVectorElts().
foldConstantFPMath()
SDValue SelectionDAG::foldConstantFPMath (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2)
Fold floating-point operations with 2 operands when both operands are constants and/or undefined.
Definition at line 6033 of file SelectionDAG.cpp.
References C1, DL, EVTToAPFloatSemantics(), llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, llvm::ISD::FP_ROUND, llvm::ISD::FREM, llvm::ISD::FSUB, getConstantFP(), llvm::APFloat::getNaN(), getUNDEF(), llvm::ConstantFPSDNode::getValueAPF(), llvm::isConstOrConstSplatFP(), llvm::SDValue::isUndef(), llvm::maximum(), llvm::maxnum(), llvm::minimum(), llvm::minnum(), and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by FoldConstantArithmetic().
FoldSetCC()
SDValue SelectionDAG::FoldSetCC (EVT VT, SDValue N1, SDValue N2, ISD::CondCode Cond, const SDLoc & dl)
Constant fold a setcc to true or false.
Definition at line 2405 of file SelectionDAG.cpp.
References assert(), C1, llvm::APFloatBase::cmpEqual, llvm::APFloatBase::cmpGreaterThan, llvm::APFloatBase::cmpLessThan, llvm::APFloatBase::cmpUnordered, llvm::ICmpInst::compare(), Cond, dl, getBoolConstant(), llvm::getICmpCondCode(), getSetCC(), llvm::ISD::getSetCCSwappedOperands(), llvm::EVT::getSimpleVT(), getUNDEF(), llvm::ISD::getUnorderedFlavor(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::isCondCodeLegal(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::ISD::isTrueWhenEqual(), llvm::SDValue::isUndef(), llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETFALSE, llvm::ISD::SETFALSE2, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETTRUE, llvm::ISD::SETTRUE2, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, and llvm::ISD::SETUO.
Referenced by getNode(), and llvm::TargetLowering::SimplifySetCC().
FoldSymbolOffset()
SDValue SelectionDAG::FoldSymbolOffset (unsigned Opcode, EVT VT, const GlobalAddressSDNode * GA, const SDNode * N2)
Definition at line 5776 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::GlobalAddressSDNode::getGlobal(), getGlobalAddress(), llvm::GlobalAddressSDNode::getOffset(), llvm::SDNode::getOpcode(), llvm::ISD::GlobalAddress, llvm::TargetLowering::isOffsetFoldingLegal(), llvm::Offset, llvm::ISD::SUB, and uint64_t.
Referenced by FoldConstantArithmetic().
getAddrSpaceCast()
SDValue SelectionDAG::getAddrSpaceCast (const SDLoc & dl, EVT VT, SDValue Ptr, unsigned SrcAS, unsigned DestAS)
Return an AddrSpaceCastSDNode.
Definition at line 2257 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::ADDRSPACECAST, dl, E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), N, and Ptr.
Referenced by combineLoad(), combineStore(), and llvm::SITargetLowering::LowerFormalArguments().
getAllOnesConstant()
SDValue llvm::SelectionDAG::getAllOnesConstant (const SDLoc & DL, EVT VT, bool IsTarget = false, bool IsOpaque = false) inline
Definition at line 656 of file SelectionDAG.h.
References DL, llvm::APInt::getAllOnes(), getConstant(), and llvm::EVT::getScalarSizeInBits().
Referenced by combineMinMaxReduction(), getBoolConstant(), getNeutralElement(), getNode(), getNOT(), getTargetVShiftNode(), isConditionalZeroOrAllOnes(), LowerADDSUBCARRY(), LowerBUILD_VECTORvXi1(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerVECTOR_SHUFFLE(), performAddCSelIntoCSinc(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifySetCC(), and simplifySetCCWithCTPOP().
getAnyExtOrTrunc()
SDValue SelectionDAG::getAnyExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either any-extending or truncating it.
Definition at line 1434 of file SelectionDAG.cpp.
References llvm::ISD::ANY_EXTEND, llvm::EVT::bitsGT(), DL, getNode(), and llvm::ISD::TRUNCATE.
Referenced by combineBitcast(), combineScalarToVector(), combineToExtendBoolVectorInReg(), createGPRPairNode(), createMMXBuildVector(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), getCopyFromPartsVector(), getCopyToPartsVector(), getNode(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerFunnelShift(), LowerMUL(), LowervXi8MulWithUNPCK(), performBuildShuffleExtendCombine(), performSVESpliceCombine(), and llvm::HexagonTargetLowering::ReplaceNodeResults().
getAssertAlign()
SDValue SelectionDAG::getAssertAlign (const SDLoc & DL, SDValue V, Align A)
Return an AssertAlignSDNode.
Definition at line 6106 of file SelectionDAG.cpp.
References AddNodeIDNode(), Align, assert(), llvm::ISD::AssertAlign, DL, E, llvm::SDValue::getValueType(), getVTList(), llvm::EVT::isInteger(), N, and NewSDValueDbgMsg().
getAtomic() [1/3]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, EVT VT, SDValue Chain, SDValue Ptr, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result and chain and takes 1 operand.
Definition at line 7871 of file SelectionDAG.cpp.
References assert(), llvm::ISD::ATOMIC_LOAD, Chain, dl, getAtomic(), getVTList(), llvm::MVT::Other, and Ptr.
getAtomic() [2/3]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDValue Chain, SDValue Ptr, SDValue Val, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result (if relevant) and chain and takes 2 operands.
Definition at line 7839 of file SelectionDAG.cpp.
References assert(), llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_CLR, llvm::ISD::ATOMIC_LOAD_FADD, llvm::ISD::ATOMIC_LOAD_FMAX, llvm::ISD::ATOMIC_LOAD_FMIN, llvm::ISD::ATOMIC_LOAD_FSUB, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UDEC_WRAP, llvm::ISD::ATOMIC_LOAD_UINC_WRAP, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, Chain, dl, llvm::SDValue::getValueType(), getVTList(), llvm::MVT::Other, and Ptr.
Referenced by combineSetCCAtomicArith(), getAtomic(), getAtomicCmpSwap(), llvm::VETargetLowering::lowerATOMIC_SWAP(), and lowerAtomicArith().
getAtomic() [3/3]
SDValue SelectionDAG::getAtomic (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDVTList VTList, ArrayRef< SDValue > Ops, MachineMemOperand * MMO)
Gets a node for an atomic op, produces result and chain and takes N operands.
Definition at line 7804 of file SelectionDAG.cpp.
References llvm::FoldingSetNodeID::AddInteger(), AddNodeIDNode(), dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), and N.
getAtomicCmpSwap()
SDValue SelectionDAG::getAtomicCmpSwap (unsigned Opcode, const SDLoc & dl, EVT MemVT, SDVTList VTs, SDValue Chain, SDValue Ptr, SDValue Cmp, SDValue Swp, MachineMemOperand * MMO)
Gets a node for an atomic cmpxchg op.
There are two valid Opcodes. ISD::ATOMIC_CMO_SWAP produces the value loaded and a chain result. ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS produces the value loaded, a success flag (initially i1), and a chain.
Definition at line 7827 of file SelectionDAG.cpp.
References assert(), llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, Chain, dl, getAtomic(), llvm::SDValue::getValueType(), and Ptr.
getAtomicMemcpy()
SDValue SelectionDAG::getAtomicMemcpy (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 7532 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
getAtomicMemmove()
SDValue SelectionDAG::getAtomicMemmove (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo)
Definition at line 7634 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
getAtomicMemset()
SDValue SelectionDAG::getAtomicMemset (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Value, SDValue Size, Type * SizeTy, unsigned ElemSz, bool isTailCall, MachinePointerInfo DstPtrInfo)
Definition at line 7764 of file SelectionDAG.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args.
getBasicBlock()
SDValue SelectionDAG::getBasicBlock (MachineBasicBlock * MBB)
Definition at line 1870 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::BasicBlock, E, getVTList(), MBB, N, and llvm::MVT::Other.
Referenced by AddNodeIDCustom(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getBFI()
BlockFrequencyInfo* llvm::SelectionDAG::getBFI () const inline
Definition at line 484 of file SelectionDAG.h.
References llvm::AMDGPUISD::BFI.
getBitcast()
SDValue SelectionDAG::getBitcast (EVT VT, SDValue V)
Return a bitcast using the SDLoc of the value operand, and casting to the provided type.
Use getNode to set a custom SDLoc.
Definition at line 2250 of file SelectionDAG.cpp.
References llvm::ISD::BITCAST, getNode(), and llvm::SDValue::getValueType().
Referenced by addShuffleForVecExtend(), adjustBitcastSrcVectorSSE1(), canonicalizeBitSelect(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeShuffleMaskWithHorizOp(), canonicalizeShuffleWithBinOps(), combineAnd(), combineAndMaskToShift(), combineAndNotIntoANDNP(), combineAndnp(), combineAndShuffleNot(), combineArithReduction(), combineBasicSADPattern(), combineBitcast(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineBitOpWithMOVMSK(), combineBitOpWithShift(), combineBROADCAST_LOAD(), combineCastedMaskArithmetic(), combineCompareEqual(), combineCONCAT_VECTORS(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineCVTPH2PS(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFaddCFmul(), combineFMulcFCMulc(), combineFneg(), combineFP_EXTEND(), combineFP_ROUND(), combineHorizOpWithShuffle(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMinMaxReduction(), combineMOVMSK(), combineMulToPMADDWD(), combineOr(), combinePMULDQ(), combinePMULH(), combinePredicateReduction(), combinePTESTCC(), combineRedundantDWordShuffle(), combineScalarAndWithMaskSetcc(), combineScalarToVector(), combineSelect(), combineSetCCMOVMSK(), combineShuffleOfBitcast(), combineShuffleToAnyExtendVectorInreg(), combineShuffleToZeroExtendVectorInReg(), combineSIntToFP(), combineStore(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToFPTruncExtElt(), combineTruncationShuffle(), combineVectorCompareAndMaskUnaryOp(), combineVectorHADDSUB(), combineVectorSizedSetCCEquality(), combineVPDPBUSDPattern(), combineVSelectWithAllOnesOrZeros(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), combineXor(), constructDup(), convertIntLogicToFPLogic(), convertShiftLeftToScale(), createMMXBuildVector(), EltsFromConsecutiveLoads(), llvm::TargetLowering::expandIS_FPCLASS(), FoldConstantArithmetic(), FoldIntToFPToInt(), GeneratePerfectShuffle(), getAVX2GatherNode(), getBuildDwordsVector(), getCanonicalConstSplat(), getConstVector(), getCopyFromPartsVector(), getCopyToPartsVector(), getMaskNode(), getMemsetValue(), llvm::X86TargetLowering::getNegatedExpression(), getOnesVector(), getPack(), getScalarMaskingNode(), getScalarValueForVectorElement(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getv64i1Argument(), getVShift(), getZeroVector(), llvm::TargetLowering::IncrementMemoryAddress(), isHorizontalBinOp(), IsNOT(), lower256BitShuffle(), lower512BitShuffle(), LowerAVXExtend(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), lowerBUILD_VECTOR(), LowerBUILD_VECTORvXbf16(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::HexagonTargetLowering::LowerCall(), LowerCTPOP(), LowerEXTEND_VECTOR_INREG(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerFunnelShift(), LowerHorizontalByteSum(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerLoad(), lowerMasksToReg(), LowerMUL(), LowerMULH(), llvm::RISCVTargetLowering::LowerOperation(), lowerRegToMasks(), llvm::HexagonTargetLowering::LowerReturn(), LowerRotate(), LowerSCALAR_TO_VECTOR(), LowerShift(), LowerShiftByScalarImmediate(), LowerShiftByScalarVariable(), lowerShuffleAsBitMask(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsVTRUNC(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerShuffleWithPSHUFB(), lowerShuffleWithUNPCK256(), lowerShuffleWithVPMOV(), LowerStore(), LowerTruncateVecI1(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8F16Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLEAsVNSRL(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVectorAllZero(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), lowerVectorIntrinsicScalars(), LowerVSETCC(), LowervXi8MulWithUNPCK(), lowerX86FPLogicOp(), narrowExtractedVectorBinOp(), narrowExtractedVectorSelect(), packImage16bitOpsToDwords(), Passv64i1ArgInRegs(), performConcatVectorsCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performSVESpliceCombine(), performUzpCombine(), performVECTOR_SHUFFLECombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceBuildVecToShuffleWithZero(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), reduceVMULWidth(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeVectorStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), splitAndLowerShuffle(), truncateVectorWithNARROW(), truncateVectorWithPACK(), and tryWidenMaskForShuffle().
getBlockAddress()
SDValue SelectionDAG::getBlockAddress (const BlockAddress * BA, EVT VT, int64_t Offset = 0, bool isTarget = false, unsigned TargetFlags = 0)
Definition at line 2200 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::BlockAddress, E, getVTList(), N, llvm::Offset, and llvm::ISD::TargetBlockAddress.
Referenced by getTargetBlockAddress(), llvm::SelectionDAGBuilder::getValueImpl(), and llvm::LanaiTargetLowering::LowerBlockAddress().
getBoolConstant()
SDValue SelectionDAG::getBoolConstant (bool V, const SDLoc & DL, EVT VT, EVT OpVT)
Create a true or false constant of type VT using the target's BooleanContent for type OpVT.
Definition at line 1525 of file SelectionDAG.cpp.
References DL, getAllOnesConstant(), llvm::TargetLoweringBase::getBooleanContents(), getConstant(), llvm_unreachable, llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
Referenced by llvm::TargetLowering::expandIS_FPCLASS(), FoldSetCC(), getLogicalNOT(), getVPLogicalNOT(), performSETCCCombine(), llvm::TargetLowering::SimplifySetCC(), and UnrollVectorOverflowOp().
getBoolExtOrTrunc()
SDValue SelectionDAG::getBoolExtOrTrunc (SDValue Op, const SDLoc & SL, EVT VT, EVT OpVT)
Convert Op, which must be of integer type, to the integer type VT, by using an extension appropriate for the target's BooleanContent for type OpVT or truncating it.
Definition at line 1452 of file SelectionDAG.cpp.
References llvm::EVT::bitsLE(), llvm::TargetLoweringBase::getBooleanContents(), llvm::TargetLoweringBase::getExtendForContent(), getNode(), and llvm::ISD::TRUNCATE.
Referenced by llvm::TargetLowering::SimplifySetCC().
getBuildVector() [1/2]
SDValue llvm::SelectionDAG::getBuildVector (EVT VT, const SDLoc & DL, ArrayRef< SDUse > Ops) inline
Return an ISD::BUILD_VECTOR node.
The number of elements in VT, which must be a vector type, must match the number of operands in Ops. The operands must have the same type as (or, for integers, a type wider than) VT's element type.
Definition at line 833 of file SelectionDAG.h.
References llvm::ISD::BUILD_VECTOR, DL, and getNode().
getBuildVector() [2/2]
SDValue llvm::SelectionDAG::getBuildVector (EVT VT, const SDLoc & DL, ArrayRef< SDValue > Ops) inline
Return an ISD::BUILD_VECTOR node.
The number of elements in VT, which must be a vector type, must match the number of operands in Ops. The operands must have the same type as (or, for integers, a type wider than) VT's element type.
Definition at line 824 of file SelectionDAG.h.
References llvm::ISD::BUILD_VECTOR, DL, and getNode().
Referenced by adjustLoadValueTypeImpl(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), BuildExactSDIV(), buildScalarToVector(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), combineConcatVectorOfScalars(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineShuffleOfScalars(), combineStore(), combineToExtendBoolVectorInReg(), combineX86ShuffleChain(), CompactSwizzlableVector(), convertLocVTToValVT(), convertShiftLeftToScale(), detectAVGPattern(), ExtendToType(), extractSubVector(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), GenerateTBL(), getBuildDwordsVector(), getBuildVectorSplat(), getConstant(), getConstVector(), getCopyFromPartsVector(), getGeneralPermuteNode(), llvm::TargetLowering::getNegatedExpression(), getNode(), getStepVector(), getTargetVShiftNode(), llvm::SelectionDAGBuilder::getValueImpl(), getVectorShuffle(), incDecVectorConstant(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), lowerBUILD_VECTOR(), lowerBuildVectorToBitOp(), LowerBuildVectorv4x32(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::AMDGPUTargetLowering::LowerEXTRACT_SUBVECTOR(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerINT_TO_FP_vXi64(), lowerMSABinaryBitImmIntr(), lowerMSASplatZExt(), LowerMUL(), LowerShift(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithPSHUFB(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerTruncateVectorStore(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerV16I8Shuffle(), lowerV8I16Shuffle(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), LowervXi8MulWithUNPCK(), NormalizeBuildVector(), packImage16bitOpsToDwords(), padEltsToUndef(), PerformBUILD_VECTORCombine(), performConcatVectorsCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performSraCombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), performVSelectCombine(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReorganizeVector(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::SimplifyDemandedVectorElts(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), tryBuildVectorShuffle(), tryToConvertShuffleOfTbl2ToTbl4(), tryToFoldExtendOfConstant(), UnrollVectorOp(), UnrollVectorOverflowOp(), unrollVectorShift(), and widenVectorToPartType().
getCALLSEQ_END() [1/2]
SDValue llvm::SelectionDAG::getCALLSEQ_END (SDValue Chain, SDValue Op1, SDValue Op2, SDValue InGlue, const SDLoc & DL) inline
Return a new CALLSEQ_END node, which always must have a glue result (to ensure it's not CSE'd).
CALLSEQ_END does not have a useful SDLoc.
Definition at line 1034 of file SelectionDAG.h.
References llvm::ISD::CALLSEQ_END, Chain, DL, llvm::SDValue::getNode(), getNode(), getVTList(), llvm::MVT::Glue, and llvm::MVT::Other.
Referenced by getCALLSEQ_END(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), and PrepareTailCall().
getCALLSEQ_END() [2/2]
SDValue llvm::SelectionDAG::getCALLSEQ_END (SDValue Chain, uint64_t Size1, uint64_t Size2, SDValue Glue, const SDLoc & DL) inline
Definition at line 1046 of file SelectionDAG.h.
References Chain, DL, getCALLSEQ_END(), and getIntPtrConstant().
getCALLSEQ_START()
SDValue llvm::SelectionDAG::getCALLSEQ_START (SDValue Chain, uint64_t InSize, uint64_t OutSize, const SDLoc & DL) inline
Return a new CALLSEQ_START node, that starts new call frame, in which InSize bytes are set up inside CALLSEQ_START..CALLSEQ_END sequence and OutSize specifies part of the frame set up prior to the sequence.
Definition at line 1022 of file SelectionDAG.h.
References llvm::ISD::CALLSEQ_START, Chain, DL, getIntPtrConstant(), getNode(), getVTList(), llvm::MVT::Glue, and llvm::MVT::Other.
Referenced by llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), and llvm::VETargetLowering::lowerToTLSGeneralDynamicModel().
getCallSiteInfo()
CallSiteInfo llvm::SelectionDAG::getCallSiteInfo (const SDNode * Node) inline
Return CallSiteInfo associated with Node, or a default if none exists.
Definition at line 2251 of file SelectionDAG.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), I, and move.
getCommutedVectorShuffle()
SDValue SelectionDAG::getCommutedVectorShuffle (const ShuffleVectorSDNode & SV)
Returns an ISD::VECTOR_SHUFFLE node semantically equivalent to the shuffle node in input but with swapped operands.
Example: shuffle A, B, <0,5,2,7> -> shuffle B, A, <4,1,6,3>
Definition at line 2137 of file SelectionDAG.cpp.
References llvm::ShuffleVectorSDNode::commuteMask(), llvm::ShuffleVectorSDNode::getMask(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), and getVectorShuffle().
Referenced by lowerVECTOR_SHUFFLE().
getCondCode()
SDValue SelectionDAG::getCondCode (ISD::CondCode Cond)
Definition at line 1925 of file SelectionDAG.cpp.
References Cond, and N.
Referenced by combine_CC(), getSelectCC(), getSetCC(), getSetCCVP(), llvm::TargetLowering::LegalizeSetCCCondCode(), lowerBALLOTIntrinsic(), lowerFCMPIntrinsic(), lowerICMPIntrinsic(), LowerTruncatei1(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), LowerVSETCC(), performIntrinsicCombine(), performVSelectCombine(), splitIntVSETCC(), and tryConvertSVEWideCompare().
getConstant() [1/3]
SDValue SelectionDAG::getConstant (const APInt & Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Definition at line 1549 of file SelectionDAG.cpp.
References DL, llvm::ConstantInt::get(), and getConstant().
getConstant() [2/3]
SDValue SelectionDAG::getConstant (const ConstantInt & Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Definition at line 1554 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::append_range(), assert(), llvm::ISD::BITCAST, llvm::ISD::Constant, DL, llvm::numbers::e, llvm::APInt::extractBits(), llvm::ConstantInt::get(), llvm::ConstantInt::getBitWidth(), getBuildVector(), getConstant(), getContext(), getDataLayout(), getNode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), getSplat(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::ConstantInt::getValue(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), getVTList(), i, isBigEndian(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::EVT::isVector(), N, NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), llvm::reverse(), llvm::ISD::SPLAT_VECTOR_PARTS, llvm::ISD::TargetConstant, llvm::TargetLoweringBase::TypeExpandInteger, llvm::TargetLoweringBase::TypePromoteInteger, and llvm::APInt::zextOrTrunc().
getConstant() [3/3]
SDValue SelectionDAG::getConstant (uint64_t Val, const SDLoc & DL, EVT VT, bool isTarget = false, bool isOpaque = false)
Create a ConstantSDNode wrapping a constant value.
If VT is a vector type, the constant is splatted into a BUILD_VECTOR.
If only legal types can be produced, this does the necessary transformations (e.g., if the vector element type is illegal).
Definition at line 1540 of file SelectionDAG.cpp.
References assert(), DL, llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), and uint64_t.
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addIPMSequence(), adjustForSubtraction(), adjustForTestUnderMask(), adjustICmpTruncate(), adjustSubwordCmp(), adjustZeroCmp(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), bitcastf32Toi32(), buildCallOperands(), BuildExactSDIV(), BuildIntrinsicOp(), llvm::SITargetLowering::buildRSRC(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildUDIV(), carryFlagToValue(), clampDynamicVectorIndex(), combine_CC(), combineAcrossLanesIntrinsic(), combineADC(), combineADDCARRYDiamond(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineAnd(), combineAndnp(), CombineANDShift(), combineArithReduction(), CombineBaseUpdate(), combineBinOpToReduce(), combineBitcast(), combineBitcastToBoolVector(), combineCarryDiamond(), combineCarryThroughADD(), combineCMov(), combineCMP(), combineCompareEqual(), combineCONCAT_VECTORS(), combineDeMorganOfBoolean(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineExtractVectorElt(), combineFP_EXTEND(), combineGatherScatter(), combineKSHIFT(), combineM68kBrCond(), combineMinMaxReduction(), combineMOVMSK(), combineMul(), combineMulSpecial(), combineMulToPMADDWD(), combineOr(), combinePMULDQ(), combinePredicateReduction(), combinePTESTCC(), combineScalarAndWithMaskSetcc(), llvm::VETargetLowering::combineSelect(), combineSelect(), llvm::VETargetLowering::combineSelectCC(), combineSelectOfTwoConstants(), combineSetCC(), combineSetCCAtomicArith(), combineSetCCMOVMSK(), combineShiftAnd1ToBitTest(), combineShiftLeft(), combineShiftOfShiftedLogic(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineShiftToMULH(), combineStore(), combineSub(), combineSubOfBoolean(), combineSVEPrefetchVecBaseImmOff(), combineSVEReductionFP(), combineSVEReductionInt(), combineSVEReductionOrderedFP(), combineToExtendBoolVectorInReg(), combineVectorCompare(), combineVectorShiftImm(), combineVectorShiftVar(), combineVectorSizedSetCCEquality(), combineVectorTruncationWithPACKUS(), CombineVMOVDRRCandidateWithVecOp(), combineVPMADD(), combineVSelectWithAllOnesOrZeros(), combinevXi1ConstantToInteger(), combineX86AddSub(), combineX86ShuffleChain(), constantFoldBFE(), constructDup(), constructRetValue(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), convertFixedMaskToScalableVector(), convertFromScalableVector(), convertShiftLeftToScale(), convertToScalableVector(), convertValVTToLocVT(), CreateCopyOfByValArgument(), createFPCmp(), createGPRPairNode(), createLoadLR(), createPSADBW(), createStoreLR(), createVariablePermute(), createVPDPBUSD(), detectAVGPattern(), EltsFromConsecutiveLoads(), EmitCMP(), emitConditionalComparison(), emitConstantSizeRepmov(), emitMemMemImm(), emitMemMemReg(), emitSETCC(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrlen(), EmitTest(), Expand64BitShift(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandBITREVERSE(), llvm::TargetLowering::expandBSWAP(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), expandf64Toi32(), llvm::TargetLowering::expandFixedPointDiv(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandIS_FPCLASS(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::TargetLowering::expandVPBITREVERSE(), llvm::TargetLowering::expandVPBSWAP(), ExtendToType(), extractF64Exponent(), extractShiftForRotate(), finalizeTS1AM(), foldADCToCINC(), foldAddSubBoolOfMaskedVal(), foldAndOrOfSETCC(), foldAndToUsubsat(), FoldConstantArithmetic(), foldCSELOfCSEL(), foldCSELofCTTZ(), foldExtendedSignBitTest(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldSelectOfConstantsUsingSra(), foldSetCCWithFunnelShift(), FoldSTEP_VECTOR(), foldVSelectToSignBitSplatMask(), foldXorTruncShiftIntoCmp(), genConstMult(), generateEquivalentSub(), GeneratePerfectShuffle(), GenerateTBL(), getAArch64Cmp(), getAArch64XALUOOp(), getAbsolute(), llvm::MipsTargetLowering::getAddrNonPICSym64(), getAllOnesConstant(), getARMIndexedAddressParts(), getAVX512Node(), getBitTestCondition(), getBoolConstant(), getBuildVectorSplat(), getCanonicalConstSplat(), getCCResult(), llvm::VECustomDAG::getConstant(), getConstant(), llvm::VECustomDAG::getConstantMask(), getConstVector(), getCopyFromParts(), llvm::RegsForValue::getCopyFromRegs(), GetExponent(), getGeneralPermuteNode(), llvm::AMDGPUTargetLowering::getHiHalf64(), getIntPtrConstant(), getLimitedPrecisionExp2(), llvm::AMDGPUTargetLowering::getLoHalf64(), llvm::VECustomDAG::getMaskBroadcast(), getMaskNode(), getMemBasePlusOffset(), getMemsetStringVal(), getMemsetValue(), getMVEIndexedAddressParts(), getNegatedInteger(), getNegative(), getNeutralElement(), getNode(), getOnesVector(), getPack(), getPMOVMSKB(), llvm::AVRTargetLowering::getPostIndexedAddressParts(), llvm::AVRTargetLowering::getPreIndexedAddressParts(), getPTest(), getPTrue(), getReductionSDNode(), getScaledOffsetForBitWidth(), getSETCC(), getShiftAmountConstant(), getShuffleScalarElt(), GetSignificand(), llvm::NVPTXTargetLowering::getSqrtEstimate(), getStepVector(), getSVEPredicateBitCast(), getT2IndexedAddressParts(), getTargetConstant(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getTruncatedUSUBSAT(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), getVectorIdxConstant(), llvm::TargetLowering::getVectorSubVecPointer(), getVLOp(), getVScale(), getZeroExtendInReg(), getZeroVector(), incDecVectorConstant(), llvm::TargetLowering::IncrementMemoryAddress(), initAccumulator(), insert1BitVector(), IntCondCCodeToICC(), isBLACompatibleAddress(), isConditionalZeroOrAllOnes(), IsSingleInstrConstant(), llvm::AMDGPUTargetLowering::loadInputValue(), lower1BitShuffle(), LowerABS(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSAT_SUBSAT(), LowerADDSUBCARRY(), LowerAndToBT(), LowerAndToBTST(), LowerAsSplatVectorLoad(), LowerATOMIC_FENCE(), lowerAtomicArith(), LowerAVXExtend(), lowerBALLOTIntrinsic(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), llvm::LanaiTargetLowering::LowerBR_CC(), LowerBR_CC(), LowerBRCOND(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), lowerBUILD_VECTOR(), LowerBUILD_VECTOR_i1(), LowerBUILD_VECTORToVIDUP(), LowerBUILD_VECTORvXi1(), LowerBuildVectorOfFPExt(), LowerBuildVectorOfFPTrunc(), LowerBuildVectorv16i8(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), LowerCallResult(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), LowerCTLZ(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), LowerCTPOP(), LowerCTTZ(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_i1(), llvm::SparcTargetLowering::LowerF128Compare(), LowerF128Load(), LowerF128Store(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), LowerFGETSIGN(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFP16_TO_FP(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), lowerFP_TO_INT_SAT(), LowerFP_TO_INT_SAT(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), LowerFunnelShift(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), LowerHorizontalByteSum(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINSERT_VECTOR_ELT_i1(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP64(), lowerINT_TO_FP_vXi64(), LowerInterruptReturn(), llvm::HexagonTargetLowering::LowerINTRINSIC_VOID(), LowerINTRINSIC_W_CHAIN(), LowerLabelRef(), llvm::MipsTargetLowering::lowerLOAD(), lowerLoadF128(), lowerLoadI1(), LowerMemOpCallTo(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSASplatImm(), lowerMSASplatZExt(), llvm::LanaiTargetLowering::LowerMUL(), LowerMUL(), lowerMUL_LOHI32(), LowerMULH(), LowerMULO(), llvm::R600TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), llvm::AArch64TargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerPARITY(), LowerPredicateLoad(), LowerPredicateStore(), llvm::HexagonTargetLowering::LowerPREFETCH(), LowerPREFETCH(), lowerReductionSeq(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::MSP430TargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), lowerRETURNADDR(), LowerRotate(), LowerSaturatingConditional(), lowerScalarInsert(), lowerScalarSplat(), LowerSDIV_v4i16(), LowerSDIV_v4i8(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), llvm::LanaiTargetLowering::LowerSETCC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShiftByScalarImmediate(), LowerShiftByScalarVariable(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsTruncBroadcast(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleToEXPAND(), lowerShuffleWithPSHUFB(), LowerSIGN_EXTEND_Mask(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), lowerStoreF128(), lowerStoreI1(), LowerSVEIntrinsicEXT(), LowerTruncatei1(), LowerTruncateVecI1(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16I8Shuffle(), lowerV8I16Shuffle(), LowerVecReduce(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLEAsVNSRL(), lowerVECTOR_SHUFFLEAsVSlidedown(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZero(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), lowerVectorIntrinsicScalars(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowervXi8MulWithUNPCK(), LowerWRITE_REGISTER(), lowerX86CmpEqZeroToCtlzSrl(), LowerXALUO(), LowerZERO_EXTEND_Mask(), llvm::SparcTargetLowering::makeAddress(), matchBSwapHWordOrAndAnd(), memsetStore(), NormalizeBuildVector(), optimizeLogicalImm(), overflowFlagToValue(), llvm::SITargetLowering::passSpecialInputs(), Passv64i1ArgInRegs(), performAddCSelIntoCSinc(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), performAddUADDVCombine(), PerformADDVecReduce(), performANDCombine(), performANDORCSELCombine(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), PerformCSETCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDSPShiftCombine(), performDUPCombine(), PerformExtractEltCombine(), PerformExtractEltToVMOVRRD(), performExtractVectorEltCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFDivCombine(), performFlagSettingCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFP_TO_INT_SATCombine(), performFpToIntCombine(), performGlobalAddressCombine(), llvm::ARMTargetLowering::PerformIntrinsicCombine(), performIntrinsicCombine(), performLDNT1Combine(), PerformLongShiftCombine(), PerformMinMaxCombine(), PerformMinMaxToSatCombine(), PerformMULCombine(), performMulCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), performORCombine(), PerformORCombineToBFI(), PerformPREDICATE_CASTCombine(), performSetccAddFolding(), performSETCCCombine(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSHLCombine(), PerformSHLSimplify(), PerformShuffleVMOVNCombine(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performSraCombine(), performSRACombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), performSRLCombine(), PerformSTORECombine(), PerformSUBCombine(), performSubsToAndsCombine(), performSVEAndCombine(), performTBZCombine(), performTruncateCombine(), PerformTruncatingStoreCombine(), performUnpackCombine(), PerformVCMPCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPCombine(), performVecReduceAddCombine(), performVecReduceAddCombineWithUADDLP(), PerformVMOVrhCombine(), PerformVMOVRRDCombine(), performVSelectCombine(), PerformVSetCCToVCTPCombine(), performXORCombine(), PerformXORCombine(), prepareTS1AM(), promoteExtBeforeAdd(), llvm::AArch64TargetLowering::ReconstructShuffle(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), ReplaceATOMIC_LOAD_128Results(), ReplaceLongIntrinsic(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), SaturateWidenedDIVFIX(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::TargetLowering::ShrinkDemandedConstant(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::ARMTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyDivRem(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), simplifyShift(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), splatSplitI64WithVL(), llvm::AMDGPUTargetLowering::split64BitValue(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), SplitEVL(), splitInt128(), splitStores(), splitStoreSplat(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::AMDGPUTargetLowering::storeStackInputValue(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), transformAddImmMulImm(), transformAddShlImm(), TranslateM68kCC(), translateSetCCForBranch(), TranslateX86CC(), truncateVecElts(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryAdvSIMDModImm321s(), tryAdvSIMDModImm64(), tryAdvSIMDModImm8(), tryAdvSIMDModImmFP(), TryCombineBaseUpdate(), tryCombineShiftImm(), tryCombineToEXTR(), tryConvertSVEWideCompare(), tryDemorganOfBooleanCondition(), tryExtendDUPToExtractHigh(), tryFoldSelectIntoOp(), tryFoldToZero(), tryFormConcatFromShuffle(), TryMULWIDECombine(), tryToConvertShuffleOfTbl2ToTbl4(), tryToFoldExtendOfConstant(), UnpackFromArgumentSlot(), UnrollVectorOverflowOp(), unrollVectorShift(), valueToCarryFlag(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSwitchCase(), WidenVector(), and WinDBZCheckDenominator().
getConstantDbgValue()
SDDbgValue * SelectionDAG::getConstantDbgValue (DIVariable * Var, DIExpression * Expr, const Value * C, const DebugLoc & DL, unsigned O)
Creates a constant SDDbgValue node.
Constant.
Definition at line 10135 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgOperand::fromConst(), llvm::SDDbgInfo::getAlloc(), and llvm::RISCVFenceField::O.
Referenced by llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue().
getConstantFP() [1/3]
SDValue SelectionDAG::getConstantFP (const APFloat & Val, const SDLoc & DL, EVT VT, bool isTarget = false)
Definition at line 1677 of file SelectionDAG.cpp.
References DL, llvm::ConstantFP::get(), getConstantFP(), and getContext().
getConstantFP() [2/3]
SDValue SelectionDAG::getConstantFP (const ConstantFP & V, const SDLoc & DL, EVT VT, bool isTarget = false)
Definition at line 1682 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::ConstantFP, DL, llvm::EVT::getScalarType(), getSplat(), getVTList(), llvm::EVT::isFloatingPoint(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), and llvm::ISD::TargetConstantFP.
getConstantFP() [3/3]
SDValue SelectionDAG::getConstantFP (double Val, const SDLoc & DL, EVT VT, bool isTarget = false)
Create a ConstantFPSDNode wrapping a constant value.
If VT is a vector type, the constant is splatted into a BUILD_VECTOR.
If only legal types can be produced, this does the necessary transformations (e.g., if the vector element type is illegal). The forms that take a double should only be used for simple constants that can be exactly represented in VT. No checks are made.
Definition at line 1714 of file SelectionDAG.cpp.
References llvm::lltok::APFloat, llvm::MVT::bf16, llvm::APFloat::convert(), DL, EVTToAPFloatSemantics(), llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::EVT::getScalarType(), llvm_unreachable, llvm::MVT::ppcf128, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by combineBitcast(), combineFneg(), combineFP_ROUND(), combineVSelectWithAllOnesOrZeros(), EltsFromConsecutiveLoads(), expandExp(), expandFP_TO_UINT_SSE(), llvm::TargetLowering::expandIS_FPCLASS(), expandLog(), ExpandPowI(), foldConstantFPMath(), getConstantFP(), getConstVector(), getF32Constant(), getMemsetStringVal(), getMemsetValue(), llvm::TargetLowering::getNegatedExpression(), getNeutralElement(), getNode(), getRVVFPReductionOpAndOperands(), getShuffleScalarElt(), llvm::TargetLowering::getSqrtInputTest(), llvm::TargetLowering::getSqrtResultForDenormInput(), getTargetConstantFP(), llvm::SelectionDAGBuilder::getValueImpl(), getZeroVector(), LowerFABSorFNEG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), LowerFCOPYSIGN(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::AMDGPUTargetLowering::LowerFLOG(), LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND(), LowerFROUND(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), lowerShuffleAsBitMask(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i32(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), llvm::AMDGPUTargetLowering::performRcpCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedBits(), and simplifyFPBinop().
getConstantPool() [1/2]
SDValue SelectionDAG::getConstantPool (const Constant * C, EVT VT, MaybeAlign Align = std::nullopt, int Offs = 0, bool isT = false, unsigned TargetFlags = 0)
Definition at line 1799 of file SelectionDAG.cpp.
References AddNodeIDNode(), Alignment, assert(), llvm::ISD::ConstantPool, E, llvm::DataLayout::getABITypeAlign(), getDataLayout(), llvm::DataLayout::getPrefTypeAlign(), getVTList(), N, NewSDValueDbgMsg(), llvm::Offset, shouldOptForSize(), and llvm::ISD::TargetConstantPool.
Referenced by combineTargetShuffle(), getAddressForMemoryInput(), getTargetConstantPool(), lowerBuildVectorAsBroadcast(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle().
getConstantPool() [2/2]
SDValue SelectionDAG::getConstantPool (MachineConstantPoolValue * C, EVT VT, MaybeAlign Align = std::nullopt, int Offs = 0, bool isT = false, unsigned TargetFlags = 0)
Definition at line 1828 of file SelectionDAG.cpp.
References AddNodeIDNode(), Alignment, assert(), llvm::ISD::ConstantPool, E, getDataLayout(), llvm::DataLayout::getPrefTypeAlign(), getVTList(), N, llvm::Offset, and llvm::ISD::TargetConstantPool.
getContext()
LLVMContext* llvm::SelectionDAG::getContext () const inline
Definition at line 481 of file SelectionDAG.h.
References Context.
Referenced by AddCombineVUZPToVPADDL(), llvm::RegsForValue::AddInlineAsmOperands(), addShuffleForVecExtend(), adjustLoadValueTypeImpl(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), canCombineShuffleToExtendVectorInreg(), canFoldInAddressingMode(), CollectOpsToWiden(), combineAnd(), combineArithReduction(), combineBasicSADPattern(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineCONCAT_VECTORS(), combineConcatVectorOfCasts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineExtractVectorElt(), combineFMinNumFMaxNum(), combineFP_EXTEND(), combineFP_ROUND(), combineLoad(), combineMinNumMaxNumImpl(), combineOr(), combinePMULH(), combinePredicateReduction(), combineScalarAndWithMaskSetcc(), combineSelect(), combineShiftAnd1ToBitTest(), combineShiftToAVG(), combineShuffleToZeroExtendVectorInReg(), combineSIntToFP(), combineStore(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToFPTruncExtElt(), combineTruncateWithSat(), combineUIntToFP(), CombineVMOVDRRCandidateWithVecOp(), combineVPDPBUSDPattern(), combineVSelectWithAllOnesOrZeros(), combinevXi1ConstantToInteger(), concatSubVectors(), constructRetValue(), convertIntLogicToFPLogic(), CreateStackTemporary(), detectAVGPattern(), detectPMADDUBSW(), earlyExpandDIVFIX(), EltsFromConsecutiveLoads(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), emitIntrinsicErrorMessage(), emitIntrinsicWithChainErrorMessage(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), errorUnsupported(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandIS_FPCLASS(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), extractSubVector(), fail(), findMemType(), FoldConstantArithmetic(), foldExtendVectorInregToExtendOfSubvector(), foldShuffleOfConcatUndefs(), foldXorTruncShiftIntoCmp(), getConstant(), getConstantFP(), getCopyFromParts(), getCopyFromPartsVector(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), llvm::RegsForValue::getCopyToRegs(), GetDependentSplitDestVTs(), getEVTAlign(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemset(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), getPrefTypeAlign(), getPTest(), getReducedAlign(), getRegistersForValue(), getSplatValue(), llvm::AMDGPUTargetLowering::getSplitDestVTs(), GetSplitDestVTs(), llvm::TargetLowering::getSqrtInputTest(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::TargetLowering::getVectorElementPointer(), llvm::VECustomDAG::getVectorVT(), llvm::TargetLowering::IncrementMemoryAddress(), llvm::SelectionDAGBuilder::init(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), llvm::TargetLoweringBase::isLoadBitCastBeneficial(), isSaturatingMinMax(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), LowerABD(), LowerADDSAT_SUBSAT(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerAsSplatVectorLoad(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerBuildVectorAsBroadcast(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::AMDGPUTargetLowering::LowerFCEIL(), lowerFCMPIntrinsic(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND(), LowerFSINCOS(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerICMPIntrinsic(), LowerMSCATTER(), LowerMULO(), llvm::RISCVTargetLowering::LowerOperation(), LowerPredicateLoad(), LowerPredicateStore(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::VETargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerSVEIntrinsicEXT(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), llvm::VETargetLowering::lowerToVVP(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVECTOR_SHUFFLE(), LowerVectorAllZero(), LowerVectorExtend(), LowerVSETCC(), matchBinOpReduction(), matchPMADDWD(), matchPMADDWD_2(), narrowExtractedVectorBinOp(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), performConcatVectorsCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDUPCombine(), PerformExtractFpToIntStores(), PerformInsertEltCombine(), performIntrinsicCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), performLOADCombine(), PerformMinMaxFpToSatCombine(), performMSTORECombine(), performMulVectorCmpZeroCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), performSelectCombine(), performSignExtendInRegCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), performSunpkloCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformTruncatingStoreCombine(), PerformUMinFpToSatCombine(), performVecReduceAddCombine(), performVectorAddSubExtCombine(), llvm::TargetLoweringBase::promoteTargetBoolean(), promoteToConstantPool(), llvm::AArch64TargetLowering::ReconstructShuffle(), reduceVMULWidth(), ReplaceLoadVector(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::TargetLowering::SimplifySetCC(), llvm::TargetLowering::softenSetCCOperands(), splitStores(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), truncateVectorWithNARROW(), truncateVectorWithPACK(), tryFormConcatFromShuffle(), UnrollVectorOp(), UnrollVectorOverflowOp(), llvm::TargetLowering::verifyReturnAddressArgumentIsConstant(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSwitchCase(), widenAbs(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), widenVec(), and WidenVector().
getCopyFromReg() [1/2]
SDValue llvm::SelectionDAG::getCopyFromReg (SDValue Chain, const SDLoc & dl, unsigned Reg, EVT VT) inline
Definition at line 795 of file SelectionDAG.h.
References Chain, llvm::ISD::CopyFromReg, dl, getNode(), getRegister(), getVTList(), and llvm::MVT::Other.
Referenced by llvm::AMDGPUTargetLowering::CreateLiveInRegister(), expandIntrinsicWChainHelper(), llvm::RegsForValue::getCopyFromRegs(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFRAMEADDR(), getReadTimeStampCounter(), GetTLSADDR(), getv64i1Argument(), llvm::X86TargetLowering::LowerAsmOutputForConstraint(), lowerBALLOTIntrinsic(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SITargetLowering::LowerCallResult(), lowerCallResult(), LowerCallResult(), LowerCMP_SWAP(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerSETCC(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), performDivRemCombine(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), replaceZeroVectorStore(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::LoongArchDAGToDAGISel::selectShiftMask(), llvm::AMDGPUTargetLowering::storeStackInputValue(), unpack64(), unpackF64OnRV32DSoftABI(), unpackFromRegLoc(), llvm::SelectionDAGBuilder::visitBitTestCase(), and llvm::SelectionDAGBuilder::visitJumpTable().
getCopyFromReg() [2/2]
SDValue llvm::SelectionDAG::getCopyFromReg (SDValue Chain, const SDLoc & dl, unsigned Reg, EVT VT, SDValue Glue) inline
Definition at line 804 of file SelectionDAG.h.
References llvm::ArrayRef(), Chain, llvm::ISD::CopyFromReg, dl, llvm::SDValue::getNode(), getNode(), getRegister(), getVTList(), llvm::MVT::Glue, and llvm::MVT::Other.
getCopyToReg() [1/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, SDValue Reg, SDValue N, SDValue Glue) inline
Definition at line 787 of file SelectionDAG.h.
References llvm::ArrayRef(), Chain, llvm::ISD::CopyToReg, dl, llvm::SDValue::getNode(), getNode(), getVTList(), llvm::MVT::Glue, N, and llvm::MVT::Other.
getCopyToReg() [2/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, unsigned Reg, SDValue N) inline
Definition at line 769 of file SelectionDAG.h.
References Chain, llvm::ISD::CopyToReg, dl, getNode(), getRegister(), N, and llvm::MVT::Other.
Referenced by emitRepmovs(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), expandIntrinsicWChainHelper(), llvm::RegsForValue::getCopyToRegs(), llvm::MipsTargetLowering::getOpndList(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCMP_SWAP(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerSETCCCARRY(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerToTLSGeneralDynamicModel32(), LowerToTLSLocalDynamicModel(), llvm::ARMTargetLowering::PerformCMOVCombine(), prepareDescriptorIndirectCall(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::SelectionDAGBuilder::visitBitTestHeader(), and llvm::SelectionDAGBuilder::visitJumpTableHeader().
getCopyToReg() [3/3]
SDValue llvm::SelectionDAG::getCopyToReg (SDValue Chain, const SDLoc & dl, unsigned Reg, SDValue N, SDValue Glue) inline
Definition at line 778 of file SelectionDAG.h.
References llvm::ArrayRef(), Chain, llvm::ISD::CopyToReg, dl, llvm::SDValue::getNode(), getNode(), getRegister(), getVTList(), llvm::MVT::Glue, N, and llvm::MVT::Other.
getDataLayout()
const DataLayout& llvm::SelectionDAG::getDataLayout () const inline
Definition at line 468 of file SelectionDAG.h.
References llvm::MachineFunction::getDataLayout().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addShuffleForVecExtend(), analyzeCallOperands(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), BuildExactSDIV(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), canCombineShuffleToExtendVectorInreg(), canFoldInAddressingMode(), combineBVOfVecSExt(), combineConcatVectorOps(), combineFMinNumFMaxNum(), combineGatherScatter(), combineLoad(), combinePredicateReduction(), combineShiftAnd1ToBitTest(), combineShuffleToAnyExtendVectorInreg(), combineShuffleToZeroExtendVectorInReg(), combineStore(), combineTargetShuffle(), combineTruncationShuffle(), combineVSelectWithAllOnesOrZeros(), computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), ComputeNumSignBits(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), createGPRPairNode(), createMMXBuildVector(), CreateStackTemporary(), EltsFromConsecutiveLoads(), llvm::X86TargetLowering::emitStackGuardXorFP(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandBITREVERSE(), llvm::TargetLowering::expandBSWAP(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandMUL_LOHI(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::TargetLowering::expandVPBITREVERSE(), llvm::TargetLowering::expandVPBSWAP(), FoldConstantArithmetic(), foldXorTruncShiftIntoCmp(), getAddressForMemoryInput(), getAVX2GatherNode(), getConstant(), getConstantPool(), getCopyFromParts(), llvm::SelectionDAGBuilder::getCopyFromRegs(), getCopyToParts(), getEVTAlign(), GetExponent(), llvm::SelectionDAGBuilder::getFrameIndexTy(), getGatherNode(), getGlobalAddress(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), getIntPtrConstant(), getLifetimeNode(), getLimitedPrecisionExp2(), getLoadStackGuard(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemset(), getMemsetStores(), getMemsetStringVal(), getNode(), llvm::VETargetLowering::getPICJumpTableRelocBase(), llvm::M68kTargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::TargetLowering::getPICJumpTableRelocBase(), getPPCf128HiElementSelector(), getPrefetchNode(), getPrefTypeAlign(), getReducedAlign(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getScatterNode(), getShiftAmountConstant(), getShiftAmountOperand(), llvm::PPC::getSplatIdxForPPCMnemonics(), llvm::TargetLowering::getSqrtInputTest(), getSymbolFunctionGlobalAddress(), getTagSymNode(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), getVectorIdxConstant(), llvm::SelectionDAGBuilder::handleDebugValue(), InferPtrAlign(), llvm::SelectionDAGBuilder::init(), isBLACompatibleAddress(), isExtendedBUILD_VECTOR(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), llvm::TargetLoweringBase::isLoadBitCastBeneficial(), IsPredicateKnownToFail(), isVMOVModifiedImm(), llvm::PPC::isVMRGEOShuffleMask(), llvm::PPC::isVMRGHShuffleMask(), llvm::PPC::isVMRGLShuffleMask(), llvm::PPC::isVPKUDUMShuffleMask(), llvm::PPC::isVPKUHUMShuffleMask(), llvm::PPC::isVPKUWUMShuffleMask(), llvm::PPC::isVSLDOIShuffleMask(), LowerABD(), LowerADDSAT_SUBSAT(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::HexagonTargetLowering::LowerBlockAddress(), lowerBuildVectorAsBroadcast(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::LanaiTargetLowering::LowerConstantPool(), LowerCTPOP(), llvm::SelectionDAGBuilder::LowerDeoptimizeCall(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerF64Op(), llvm::AMDGPUTargetLowering::LowerFCEIL(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), LowerFNEGorFABS(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), LowerMemOpCallTo(), LowerMULO(), llvm::R600TargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), LowerPredicateLoad(), LowerPredicateStore(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), LowerRETURNADDR(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerSTORE(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), llvm::SparcTargetLowering::makeAddress(), narrowExtractedVectorLoad(), PerformBITCASTCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performMULCombine(), PerformSTORECombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformTruncatingStoreCombine(), performUzpCombine(), PerformVMOVRRDCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::TargetLoweringBase::promoteTargetBoolean(), promoteToConstantPool(), recoverFramePointer(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), ReplaceLoadVector(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::TargetLowering::SimplifySetCC(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), transformCallee(), unpackFromMemLoc(), UnrollVectorOverflowOp(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), and llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad().
getDbgLabel()
SDDbgLabel * SelectionDAG::getDbgLabel (DILabel * Label, const DebugLoc & DL, unsigned O)
Creates a SDDbgLabel node.
Definition at line 10343 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgInfo::getAlloc(), and llvm::RISCVFenceField::O.
getDbgValue()
SDDbgValue * SelectionDAG::getDbgValue (DIVariable * Var, DIExpression * Expr, SDNode * N, unsigned R, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a SDDbgValue node.
getDbgValue - Creates a SDDbgValue node.
SDNode
Definition at line 10123 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgOperand::fromNode(), llvm::SDDbgInfo::getAlloc(), N, and llvm::RISCVFenceField::O.
getDbgValueList()
SDDbgValue * SelectionDAG::getDbgValueList (DIVariable * Var, DIExpression * Expr, ArrayRef< SDDbgOperand > Locs, ArrayRef< SDNode * > Dependencies, bool IsIndirect, const DebugLoc & DL, unsigned O, bool IsVariadic)
Creates a SDDbgValue node from a list of locations.
Definition at line 10185 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgInfo::getAlloc(), and llvm::RISCVFenceField::O.
Referenced by llvm::SelectionDAGBuilder::addDanglingDebugInfo(), llvm::SelectionDAGBuilder::handleDebugValue(), salvageDebugInfo(), and transferDbgValues().
GetDbgValues()
ArrayRef<SDDbgValue*> llvm::SelectionDAG::GetDbgValues (const SDNode * SD) const inline
Get the debug values which reference the given SDNode.
Definition at line 1867 of file SelectionDAG.h.
References llvm::SDDbgInfo::getSDDbgValues().
Referenced by ProcessSDDbgValues(), salvageDebugInfo(), and transferDbgValues().
getDenormalMode()
DenormalMode llvm::SelectionDAG::getDenormalMode (EVT VT) const inline
Return the current function's default denormal handling kind for the given floating point type.
Definition at line 2289 of file SelectionDAG.h.
References EVTToAPFloatSemantics(), and llvm::MachineFunction::getDenormalMode().
GetDependentSplitDestVTs()
std::pair< EVT, EVT > SelectionDAG::GetDependentSplitDestVTs (const EVT & VT, const EVT & EnvVT, bool * HiIsEmpty) const
Compute the VTs needed for the low/hi parts of a type, dependent on an enveloping VT that has been split into two identical pieces.
GetDependentSplitDestVTs - Compute the VTs needed for the low/hi parts of a type, dependent on an enveloping VT that has been split into two identical pieces.
Sets the HisIsEmpty flag when hi type has zero storage size.
Sets the HiIsEmpty flag when hi type has zero storage size.
Definition at line 11636 of file SelectionDAG.cpp.
References assert(), getContext(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorVT(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
getDivergenceAnalysis()
const LegacyDivergenceAnalysis* llvm::SelectionDAG::getDivergenceAnalysis () const inline
Definition at line 477 of file SelectionDAG.h.
References llvm::AArch64PACKey::DA.
Referenced by llvm::FunctionLoweringInfo::set().
getEHLabel()
SDValue SelectionDAG::getEHLabel (const SDLoc & dl, SDValue Root, MCSymbol * Label)
Definition at line 2176 of file SelectionDAG.cpp.
References dl, llvm::ISD::EH_LABEL, and getLabelNode().
getEntryNode()
SDValue llvm::SelectionDAG::getEntryNode () const inline
Return the token chain corresponding to the entry of the function.
Definition at line 550 of file SelectionDAG.h.
Referenced by llvm::AMDGPUTargetLowering::addTokenForArgument(), clear(), combineTargetShuffle(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::AMDGPUTargetLowering::CreateLiveInRegisterRaw(), llvm::MipsTargetLowering::getAddrLocal(), llvm::SelectionDAGBuilder::getCopyFromRegs(), getFLUSHW(), getFRAMEADDR(), getStackArgumentTokenFactor(), llvm::SelectionDAGBuilder::getValueImpl(), HandleMergeInputChains(), llvm::AMDGPUTargetLowering::loadStackInputValue(), lowerBALLOTIntrinsic(), lowerBuildVectorAsBroadcast(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), lowerRETURNADDR(), LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerToTLSExecModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerToTLSGeneralDynamicModel32(), LowerToTLSGeneralDynamicModel64(), LowerToTLSGeneralDynamicModelX32(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), llvm::TargetLowering::makeLibCall(), llvm::ARMTargetLowering::PerformCMOVCombine(), performDivRemCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), promoteXINT_TO_FP(), replaceZeroVectorStore(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::LoongArchDAGToDAGISel::selectShiftMask(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getEVTAlign()
Align SelectionDAG::getEVTAlign (EVT MemoryVT) const
Compute the default alignment value for the given type.
Definition at line 1293 of file SelectionDAG.cpp.
References llvm::PointerType::get(), llvm::DataLayout::getABITypeAlign(), getContext(), getDataLayout(), llvm::Type::getInt8Ty(), llvm::EVT::getTypeForEVT(), and llvm::MVT::iPTR.
Referenced by getLoad(), getLoadVP(), getMemIntrinsicNode(), getStore(), getStridedLoadVP(), and getTruncStore().
getExternalSymbol()
SDValue SelectionDAG::getExternalSymbol (const char * Sym, EVT VT)
Definition at line 1898 of file SelectionDAG.cpp.
References N.
Referenced by llvm::SelectionDAGBuilder::LowerDeoptimizeCall(), llvm::SparcTargetLowering::LowerF128Compare(), and llvm::SparcTargetLowering::LowerF128Op().
getExtLoad() [1/2]
SDValue SelectionDAG::getExtLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, EVT MemVT, MachineMemOperand * MMO)
Definition at line 8146 of file SelectionDAG.cpp.
References Chain, dl, getLoad(), getUNDEF(), Ptr, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getExtLoad() [2/2]
SDValue SelectionDAG::getExtLoad (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 8135 of file SelectionDAG.cpp.
References AAInfo, Alignment, Chain, dl, getLoad(), getUNDEF(), MMOFlags, Ptr, PtrInfo, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
Referenced by adjustSubwordCmp(), combineEXTEND_VECTOR_INREG(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getMemcpyLoadsAndStores(), LowerPredicateLoad(), lowerVECTOR_SHUFFLE(), performFPExtendCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), PerformVMOVrhCombine(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::TargetLowering::scalarizeVectorLoad(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), tryToFoldExtOfExtload(), tryToFoldExtOfLoad(), unpackFromMemLoc(), and llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad().
getExtLoadVP() [1/2]
SDValue SelectionDAG::getExtLoadVP (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 8408 of file SelectionDAG.cpp.
References Chain, dl, getLoadVP(), getUNDEF(), llvm::BitmaskEnumDetail::Mask(), Ptr, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getExtLoadVP() [2/2]
SDValue SelectionDAG::getExtLoadVP (ISD::LoadExtType ExtType, const SDLoc & dl, EVT VT, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, bool IsExpanding = false)
Definition at line 8395 of file SelectionDAG.cpp.
References AAInfo, Alignment, Chain, dl, getLoadVP(), getUNDEF(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, Ptr, PtrInfo, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getExtStridedLoadVP() [1/2]
SDValue SelectionDAG::getExtStridedLoadVP (ISD::LoadExtType ExtType, const SDLoc & DL, EVT VT, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 8659 of file SelectionDAG.cpp.
References Chain, DL, getStridedLoadVP(), getUNDEF(), llvm::BitmaskEnumDetail::Mask(), Ptr, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getExtStridedLoadVP() [2/2]
SDValue SelectionDAG::getExtStridedLoadVP (ISD::LoadExtType ExtType, const SDLoc & DL, EVT VT, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, bool IsExpanding = false)
Definition at line 8647 of file SelectionDAG.cpp.
References AAInfo, Alignment, Chain, DL, getStridedLoadVP(), getUNDEF(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, Ptr, PtrInfo, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getFlagInserter()
FlagInserter* llvm::SelectionDAG::getFlagInserter () inline
Definition at line 486 of file SelectionDAG.h.
getFPExtendOrRound()
SDValue SelectionDAG::getFPExtendOrRound (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of float type, to the float type VT, by either extending or rounding (by truncation).
Definition at line 1413 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), DL, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, getIntPtrConstant(), and getNode().
Referenced by getCopyFromPartsVector(), getNode(), llvm::RISCVTargetLowering::LowerOperation(), LowerUINT_TO_FP_i32(), and llvm::RISCVTargetLowering::PerformDAGCombine().
getFrameIndex()
SDValue SelectionDAG::getFrameIndex (int FI, EVT VT, bool isTarget = false)
Definition at line 1765 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::ISD::FrameIndex, getVTList(), N, and llvm::ISD::TargetFrameIndex.
Referenced by llvm::X86TargetLowering::BuildFILD(), CalculateTailCallArgDest(), CreateStackTemporary(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), getAddressForMemoryInput(), getLifetimeNode(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getTargetFrameIndex(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::AMDGPUTargetLowering::loadStackInputValue(), llvm::LoongArchTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::LowerCallTo(), llvm::VETargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerINTRINSIC_W_CHAIN(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), unpack64(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getFrameIndexDbgValue() [1/2]
SDDbgValue * SelectionDAG::getFrameIndexDbgValue (DIVariable * Var, DIExpression * Expr, unsigned FI, ArrayRef< SDNode * > Dependencies, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
FrameIndex with dependencies.
Definition at line 10159 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgOperand::fromFrameIdx(), llvm::SDDbgInfo::getAlloc(), and llvm::RISCVFenceField::O.
getFrameIndexDbgValue() [2/2]
SDDbgValue * SelectionDAG::getFrameIndexDbgValue (DIVariable * Var, DIExpression * Expr, unsigned FI, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a FrameIndex SDDbgValue node.
FrameIndex.
Definition at line 10148 of file SelectionDAG.cpp.
References assert(), DL, and llvm::RISCVFenceField::O.
getFreeze()
SDValue SelectionDAG::getFreeze (SDValue V)
Return a freeze using the SDLoc of the value operand.
Definition at line 2278 of file SelectionDAG.cpp.
References llvm::ISD::FREEZE, getNode(), and llvm::SDValue::getValueType().
Referenced by combinePredicateReduction(), llvm::TargetLowering::expandABS(), foldSelectWithIdentityConstant(), LowerABD(), LowerAVXCONCAT_VECTORS(), LowerShiftByScalarImmediate(), lowerVECTOR_SHUFFLE(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), and llvm::RISCVTargetLowering::ReplaceNodeResults().
getFunctionVarLocs()
const FunctionVarLocs* llvm::SelectionDAG::getFunctionVarLocs () const inline
Returns the result of the AssignmentTrackingAnalysis pass if it's available, otherwise return nullptr.
Definition at line 480 of file SelectionDAG.h.
Referenced by llvm::SelectionDAGBuilder::dropDanglingDebugInfo(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), and llvm::SelectionDAGBuilder::visit().
getGatherVP()
SDValue SelectionDAG::getGatherVP (SDVTList VTs, EVT VT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType)
Definition at line 8822 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGE(), N, NewSDValueDbgMsg(), and llvm::ArrayRef< T >::size().
Referenced by llvm::RISCVTargetLowering::PerformDAGCombine().
getGLOBAL_OFFSET_TABLE()
SDValue llvm::SelectionDAG::getGLOBAL_OFFSET_TABLE (EVT VT) inline
Return a GLOBAL_OFFSET_TABLE node. This does not have a useful SDLoc.
Definition at line 1070 of file SelectionDAG.h.
References getNode(), and llvm::ISD::GLOBAL_OFFSET_TABLE.
Referenced by llvm::TargetLowering::getPICJumpTableRelocBase(), and llvm::HexagonTargetLowering::LowerGLOBALADDRESS().
getGlobalAddress()
SDValue SelectionDAG::getGlobalAddress (const GlobalValue * GV, const SDLoc & DL, EVT VT, int64_t offset = 0, bool isTargetGA = false, unsigned TargetFlags = 0)
Definition at line 1732 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::BitWidth, DL, E, getDataLayout(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::GlobalValue::getType(), getVTList(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::GlobalValue::isThreadLocal(), N, llvm::Offset, llvm::SignExtend64(), llvm::ISD::TargetGlobalAddress, and llvm::ISD::TargetGlobalTLSAddress.
Referenced by FoldSymbolOffset(), llvm::VETargetLowering::getPICJumpTableRelocBase(), getSymbolFunctionGlobalAddress(), getTargetGlobalAddress(), llvm::SelectionDAGBuilder::getValueImpl(), and performGlobalAddressCombine().
getGraphAttrs()
std::string SelectionDAG::getGraphAttrs (const SDNode * N) const
Get graph attributes for a node.
getGraphAttrs - Get graph attributes for a node.
(eg. "color=red".) Used from getNodeAttributes.
Definition at line 203 of file SelectionDAGPrinter.cpp.
References llvm::errs(), I, and N.
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::getNodeAttributes().
getHeapAllocSite()
MDNode* llvm::SelectionDAG::getHeapAllocSite (const SDNode * Node) const inline
Return HeapAllocSite associated with Node, or nullptr if none exists.
Definition at line 2260 of file SelectionDAG.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), and I.
getIndexedLoad()
SDValue SelectionDAG::getIndexedLoad (SDValue OrigLoad, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 8154 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, dl, getLoad(), llvm::SDValue::getValueType(), llvm::ARM_MB::LD, MMOFlags, llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, and llvm::Offset.
getIndexedLoadVP()
SDValue SelectionDAG::getIndexedLoadVP (SDValue OrigLoad, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 8417 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, dl, getLoadVP(), llvm::SDValue::getValueType(), llvm::ARM_MB::LD, MMOFlags, llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, and llvm::Offset.
getIndexedMaskedLoad()
SDValue SelectionDAG::getIndexedMaskedLoad (SDValue OrigLoad, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 8944 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, dl, getMaskedLoad(), llvm::SDValue::getValueType(), llvm::ARM_MB::LD, and llvm::Offset.
getIndexedMaskedStore()
SDValue SelectionDAG::getIndexedMaskedStore (SDValue OrigStore, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 8993 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, dl, getMaskedStore(), llvm::Offset, and llvm::ARM_MB::ST.
getIndexedStore()
SDValue SelectionDAG::getIndexedStore (SDValue OrigStore, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 8287 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::sampleprof::Base, dl, E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), N, NewSDValueDbgMsg(), llvm::Offset, llvm::MVT::Other, llvm::ARM_MB::ST, and llvm::ISD::STORE.
Referenced by llvm::HexagonTargetLowering::LowerStore().
getIndexedStoreVP()
SDValue SelectionDAG::getIndexedStoreVP (SDValue OrigStore, const SDLoc & dl, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 8539 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::sampleprof::Base, dl, E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), N, NewSDValueDbgMsg(), llvm::Offset, llvm::MVT::Other, and llvm::ARM_MB::ST.
getIndexedStridedLoadVP()
SDValue SelectionDAG::getIndexedStridedLoadVP (SDValue OrigLoad, const SDLoc & DL, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 8668 of file SelectionDAG.cpp.
References assert(), llvm::sampleprof::Base, DL, getStridedLoadVP(), llvm::SDValue::getValueType(), MMOFlags, llvm::MachineMemOperand::MODereferenceable, llvm::MachineMemOperand::MOInvariant, and llvm::Offset.
getIndexedStridedStoreVP()
SDValue SelectionDAG::getIndexedStridedStoreVP (SDValue OrigStore, const SDLoc & DL, SDValue Base, SDValue Offset, ISD::MemIndexedMode AM)
Definition at line 8790 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::sampleprof::Base, DL, E, getVTList(), N, NewSDValueDbgMsg(), llvm::Offset, and llvm::MVT::Other.
getIntPtrConstant()
SDValue SelectionDAG::getIntPtrConstant (uint64_t Val, const SDLoc & DL, bool isTarget = false)
Definition at line 1660 of file SelectionDAG.cpp.
References DL, getConstant(), getDataLayout(), and llvm::TargetLoweringBase::getPointerTy().
Referenced by buildCallOperands(), buildFromShuffleMostly(), combineArithReduction(), combineBitcast(), combineBitcastToBoolVector(), combineBVZEXTLOAD(), combineCompareEqual(), combineConcatVectorOps(), combineExtractVectorElt(), combineFP16_TO_FP(), combineFP_EXTEND(), combineFP_ROUND(), combineINSERT_SUBVECTOR(), combineMinMaxReduction(), combineSelect(), combineTargetShuffle(), combineTruncateWithSat(), CompactSwizzlableVector(), CreateCopyOfByValArgument(), detectAVGPattern(), EltsFromConsecutiveLoads(), emitConstantSizeRepmov(), emitRepmovsB(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::TargetLowering::expandDIVREMByConstant(), ExtendToType(), ExtractBitFromMaskVector(), extractSubVector(), getCALLSEQ_END(), getCALLSEQ_START(), getCopyToParts(), getFPExtendOrRound(), getFRAMEADDR(), getMaskNode(), getParamsForOneTrueMaskedElt(), getScalarMaskingNode(), getShuffleHalfVectors(), getStrictFPExtendOrRound(), insert1BitVector(), insertSubVector(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), lowerAddSubToHorizontalOp(), LowerAVXCONCAT_VECTORS(), LowerBITCAST(), LowerBITREVERSE_XOP(), LowerBUILD_VECTORvXi1(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), llvm::HexagonTargetLowering::LowerEH_RETURN(), LowerEXTRACT_SUBVECTOR(), LowerFABSorFNEG(), LowerFCOPYSIGN(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), LowerFP16_TO_FP(), LowerFP_TO_FP16(), lowerFPToIntToFP(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), lowerI128ToGR128(), LowerI64IntToFP16(), LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), LowerLoad(), lowerMasksToReg(), LowerMGATHER(), LowerMLOAD(), llvm::RISCVTargetLowering::LowerOperation(), llvm::LanaiTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerSDIV(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUndefHalf(), LowerSIGN_EXTEND_Mask(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerToTLSExecModel(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), llvm::HexagonTargetLowering::LowerVACOPY(), LowerVACOPY(), llvm::VETargetLowering::lowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), LowerZERO_EXTEND_Mask(), matchPMADDWD_2(), llvm::PPCTargetLowering::PerformDAGCombine(), performFPExtendCombine(), performMADD_MSUBCombine(), PerformTruncatingStoreCombine(), prepareDescriptorIndirectCall(), promoteXINT_TO_FP(), ReorganizeVector(), ReplaceLoadVector(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeVectorStore(), SplitAndExtendv16i1(), vectorizeExtractedCast(), and widenSubVector().
getJumpTable()
SDValue SelectionDAG::getJumpTable (int JTI, EVT VT, bool isTarget = false, unsigned TargetFlags = 0)
Definition at line 1780 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), E, getVTList(), llvm::ISD::JumpTable, N, and llvm::ISD::TargetJumpTable.
Referenced by getTargetJumpTable(), and llvm::SelectionDAGBuilder::visitJumpTable().
getLabelNode()
SDValue SelectionDAG::getLabelNode (unsigned Opcode, const SDLoc & dl, SDValue Root, MCSymbol * Label)
Definition at line 2181 of file SelectionDAG.cpp.
References AddNodeIDNode(), dl, E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), N, and llvm::MVT::Other.
Referenced by getEHLabel().
getLibInfo()
const TargetLibraryInfo& llvm::SelectionDAG::getLibInfo () const inline
Definition at line 475 of file SelectionDAG.h.
getLifetimeNode()
SDValue SelectionDAG::getLifetimeNode (bool IsStart, const SDLoc & dl, SDValue Chain, int FrameIndex, int64_t Size, int64_t Offset = -1)
Creates a LifetimeSDNode that starts (IsStart==true) or ends (IsStart==false) the lifetime of the portion of FrameIndex between offsets Offset and Offset + Size.
Definition at line 7951 of file SelectionDAG.cpp.
References AddNodeIDNode(), Chain, dl, E, llvm::ISD::FrameIndex, getDataLayout(), llvm::SDLoc::getDebugLoc(), getFrameIndex(), llvm::SDLoc::getIROrder(), getTargetLoweringInfo(), getVTList(), llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, N, NewSDValueDbgMsg(), llvm::Offset, and llvm::MVT::Other.
getLoad() [1/4]
SDValue SelectionDAG::getLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
Loads are not normal binary operators: their result type is not determined by their operands, and they produce a value AND a token chain.
This function will set the MOLoad flag on MMOFlags, but you can set it if you want. The MOStore flag must not be set.
Definition at line 8118 of file SelectionDAG.cpp.
References AAInfo, Alignment, Chain, dl, getUNDEF(), MMOFlags, llvm::ISD::NON_EXTLOAD, Ptr, PtrInfo, Ranges, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
Referenced by bitcastf32Toi32(), llvm::X86TargetLowering::BuildFILD(), combineBVOfConsecutiveLoads(), combineExtractVectorElt(), combineExtractWithShuffle(), combineLoad(), combineMaskedLoadConstantMask(), combineMOVDQ2Q(), combineStore(), combineTargetShuffle(), EltsFromConsecutiveLoads(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), expandf64Toi32(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::MipsTargetLowering::getAddrGlobal(), llvm::MipsTargetLowering::getAddrGlobalLargeGOT(), llvm::MipsTargetLowering::getAddrLocal(), getExtLoad(), getFRAMEADDR(), getIndexedLoad(), getLoad(), getMemmoveLoadsAndStores(), LLVM_DEPRECATED(), llvm::AMDGPUTargetLowering::loadStackInputValue(), LowerAsSplatVectorLoad(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), LowerF128Load(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerLoad(), LowerLoad(), lowerLoadF128(), lowerLoadI1(), lowerMSALoadIntr(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), lowerRETURNADDR(), LowerRETURNADDR(), lowerShuffleAsBroadcast(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerUINT_TO_FP_i64(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerVECTOR_SHUFFLE(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), narrowExtractedVectorLoad(), performConcatVectorsCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performIntToFpCombine(), llvm::AMDGPUTargetLowering::performLoadCombine(), performLOADCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingToWideningLoad(), PerformVMOVhrCombine(), PerformVMOVRRDCombine(), prepareDescriptorIndirectCall(), reduceMaskedLoadToScalarLoad(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), unpack64(), unpackF64OnRV32DSoftABI(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getLoad() [2/4]
SDValue SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, EVT MemVT, MachineMemOperand * MMO)
Definition at line 8068 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), Chain, dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), llvm::EVT::getVectorElementCount(), getVTList(), Indexed, llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::ISD::LOAD, N, NewSDValueDbgMsg(), llvm::ISD::NON_EXTLOAD, llvm::Offset, llvm::MVT::Other, Ptr, and llvm::ISD::UNINDEXED.
getLoad() [3/4]
SDValue SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
Definition at line 8044 of file SelectionDAG.cpp.
References AAInfo, Alignment, assert(), Chain, dl, getLoad(), getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemoryLocation::getSizeOrUnknown(), llvm::EVT::getStoreSize(), InferPointerInfo(), MMOFlags, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::Offset, llvm::MVT::Other, Ptr, PtrInfo, Ranges, and uint64_t.
getLoad() [4/4]
SDValue llvm::SelectionDAG::getLoad (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr) inline
Definition at line 1337 of file SelectionDAG.h.
References AAInfo, Alignment, Chain, dl, getEVTAlign(), getLoad(), MMOFlags, llvm::Offset, Ptr, PtrInfo, and Ranges.
getLoadVP() [1/5]
SDValue SelectionDAG::getLoadVP (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 8387 of file SelectionDAG.cpp.
References Chain, dl, getLoadVP(), getUNDEF(), llvm::BitmaskEnumDetail::Mask(), llvm::ISD::NON_EXTLOAD, Ptr, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getLoadVP() [2/5]
SDValue SelectionDAG::getLoadVP (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, const MDNode * Ranges = nullptr, bool IsExpanding = false)
Definition at line 8374 of file SelectionDAG.cpp.
References AAInfo, Alignment, Chain, dl, getLoadVP(), getUNDEF(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, llvm::ISD::NON_EXTLOAD, Ptr, PtrInfo, Ranges, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getLoadVP() [3/5]
SDValue SelectionDAG::getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 8339 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), Chain, dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getVTList(), Indexed, llvm::BitmaskEnumDetail::Mask(), N, NewSDValueDbgMsg(), llvm::Offset, llvm::MVT::Other, Ptr, and llvm::ISD::UNINDEXED.
getLoadVP() [4/5]
SDValue SelectionDAG::getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, const MDNode * Ranges = nullptr, bool IsExpanding = false)
Definition at line 8316 of file SelectionDAG.cpp.
References AAInfo, Alignment, assert(), Chain, dl, getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemoryLocation::getSizeOrUnknown(), llvm::EVT::getStoreSize(), InferPointerInfo(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::Offset, llvm::MVT::Other, Ptr, PtrInfo, Ranges, and uint64_t.
Referenced by getExtLoadVP(), getIndexedLoadVP(), and getLoadVP().
getLoadVP() [5/5]
SDValue llvm::SelectionDAG::getLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr, bool IsExpanding = false) inline
Definition at line 1433 of file SelectionDAG.h.
References AAInfo, Alignment, Chain, dl, getEVTAlign(), getLoadVP(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, llvm::Offset, Ptr, PtrInfo, and Ranges.
getLogicalNOT()
SDValue SelectionDAG::getLogicalNOT (const SDLoc & DL, SDValue Val, EVT VT)
Create a logical NOT operation as (XOR Val, BooleanOne).
Definition at line 1500 of file SelectionDAG.cpp.
References DL, getBoolConstant(), getNode(), and llvm::ISD::XOR.
Referenced by extractBooleanFlip(), llvm::HexagonTargetLowering::LowerAddSubCarry(), llvm::RISCVTargetLowering::LowerOperation(), and PerformORCombine_i1().
getMachineFunction()
MachineFunction& llvm::SelectionDAG::getMachineFunction () const inline
Definition at line 465 of file SelectionDAG.h.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), buildCallOperands(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildSREMPow2(), CalculateTailCallSPDiff(), combineFMA(), combineFMADDSUB(), combineFMinNumFMaxNum(), combineFneg(), combineMul(), combineStore(), combineTargetShuffle(), combineVectorSizedSetCCEquality(), llvm::BaseIndexOffset::computeAliasing(), computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::SITargetLowering::denormalsEnabledForType(), EmitCmp(), emitConstantSizeRepmov(), emitLockedStackOp(), llvm::AArch64SelectionDAGInfo::EmitMOPS(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemmove(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), EmitUnrolledSetTag(), llvm::BaseIndexOffset::equalBaseIndex(), errorUnsupported(), llvm::X86TargetLowering::expandIndirectJTBranch(), llvm::TargetLowering::expandIS_FPCLASS(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), fail(), llvm::SelectionDAGBuilder::FindMergedConditions(), fixupFuncForFI(), getAddressForMemoryInput(), llvm::MipsTargetLowering::getAddrLocal(), getBROADCAST_LOAD(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFRAMEADDR(), llvm::MipsTargetLowering::getGlobalReg(), getLoad(), getLoadStackGuard(), getLoadVP(), getMemcpyLoadsAndStores(), getMemIntrinsicNode(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::MipsTargetLowering::getOpndList(), llvm::VETargetLowering::getPICJumpTableRelocBase(), getRegistersForValue(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), getSPDenormModeValue(), llvm::NVPTXTargetLowering::getSqrtEstimate(), getStore(), getStridedLoadVP(), getTagSymNode(), GetTLSADDR(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), getv64i1Argument(), hasReturnsTwiceAttr(), InferPointerInfo(), InferPtrAlign(), isConsecutiveLSLoc(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::SITargetLowering::isFMADLegal(), llvm::SITargetLowering::isFPExtFoldable(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), IsWebAssemblyLocal(), llvm::AMDGPUTargetLowering::loadStackInputValue(), LowerAsSplatVectorLoad(), lowerBuildVectorAsBroadcast(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerInterruptReturn(), LowerINTRINSIC_W_CHAIN(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::VETargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), lowerRETURNADDR(), LowerRETURNADDR(), lowerShuffleAsBroadcast(), LowerToTLSExecModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), LowerToTLSLocalDynamicModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVACOPY(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), lowerVECTOR_SHUFFLE(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), MarkEHGuard(), MarkEHRegistrationNode(), narrowExtractedVectorLoad(), llvm::SITargetLowering::passSpecialInputs(), PerformADDCombineWithOperands(), performBRCONDCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), llvm::RISCVTargetLowering::preferredShiftLegalizationStrategy(), llvm::AArch64TargetLowering::preferredShiftLegalizationStrategy(), llvm::X86TargetLowering::preferredShiftLegalizationStrategy(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), promoteToConstantPool(), recoverFramePointer(), reduceVMULWidth(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), selectI64Imm(), setAlignFlagsForFI(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), setUsesTOCBasePtr(), shouldGenerateInlineTPLoop(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), llvm::TargetLowering::SimplifySetCC(), splitStores(), llvm::AMDGPUTargetLowering::storeStackInputValue(), StoreTailCallArgumentsToStackSlot(), transformCallee(), llvm::X86InstrInfo::unfoldMemoryOperand(), unpack64(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), unpackFromRegLoc(), viewGraph(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getMachineNode() [1/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
Definition at line 10027 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [2/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT)
These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
getMachineNode - These are used for target selectors to create a new node with specified return type(s), MachineInstr opcode, and operands.
Note that getMachineNode returns the resultant node. If there is already a node of the specified opcode and operands, it returns that node instead of the current one.
Definition at line 9946 of file SelectionDAG.cpp.
References dl, and getVTList().
Referenced by llvm::SITargetLowering::buildRSRC(), buildSMovImm32(), llvm::VETargetLowering::combineTRUNCATE(), llvm::SITargetLowering::copyToM0(), createGPRPairNode(), createTuple(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), emitLockedStackOp(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), expandIntrinsicWChainHelper(), getLeftShift(), getMachineNode(), getPrefetchNode(), getTargetExtractSubreg(), getTargetInsertSubreg(), InvertCarryFlag(), isWorthFoldingIntoOrrWithShift(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::VETargetLowering::lowerATOMIC_FENCE(), llvm::VETargetLowering::LowerCall(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerF128Load(), LowerF128Store(), LowerF64Op(), LowerFNEGorFABS(), llvm::VETargetLowering::LowerFormalArguments(), lowerI128ToGR128(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINTRINSIC_W_CHAIN(), lowerLoadF128(), lowerLoadI1(), llvm::SystemZTargetLowering::LowerOperationWrapper(), llvm::VETargetLowering::LowerReturn(), lowerStoreF128(), lowerStoreI1(), optimizeLogicalImm(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), AMDGPUDAGToDAGISel::Select(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), AMDGPUDAGToDAGISel::SelectBuildVector(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstant(), selectConstantAddr(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), selectI64Imm(), selectI64ImmDirect(), selectI64ImmDirectPrefix(), selectImmSeq(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), llvm::HexagonDAGToDAGISel::SelectP2D(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HvxSelector::selectRor(), SelectSAddrFI(), llvm::LoongArchDAGToDAGISel::selectShiftMask(), llvm::RISCVDAGToDAGISel::selectShiftMask(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::RISCVDAGToDAGISel::selectSHXADD_UWOp(), llvm::RISCVDAGToDAGISel::selectSHXADDOp(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HvxSelector::selectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), llvm::X86InstrInfo::unfoldMemoryOperand(), Widen(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getMachineNode() [3/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 9974 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [4/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1)
Definition at line 9952 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [5/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1, SDValue Op2)
Definition at line 9959 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [6/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 9966 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [7/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
Definition at line 9996 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [8/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
Definition at line 10020 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [9/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2)
Definition at line 10003 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [10/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, EVT VT3, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 10011 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [11/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
Definition at line 9980 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [12/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 9988 of file SelectionDAG.cpp.
References dl, getMachineNode(), and getVTList().
getMachineNode() [13/13]
MachineSDNode * SelectionDAG::getMachineNode (unsigned Opcode, const SDLoc & dl, SDVTList VTs, ArrayRef< SDValue > Ops)
Definition at line 10034 of file SelectionDAG.cpp.
References AddNodeIDNode(), DL, E, llvm::MVT::Glue, N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
getMaskedGather()
SDValue SelectionDAG::getMaskedGather (SDVTList VTs, EVT MemVT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType, ISD::LoadExtType ExtTy)
Definition at line 9004 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGE(), llvm::ISD::MGATHER, N, NewSDValueDbgMsg(), and llvm::ArrayRef< T >::size().
Referenced by llvm::RISCVTargetLowering::PerformDAGCombine(), performMaskedGatherScatterCombine(), and rebuildGatherScatter().
getMaskedLoad()
SDValue SelectionDAG::getMaskedLoad (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Base, SDValue Offset, SDValue Mask, SDValue Src0, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, ISD::LoadExtType ExtTy, bool IsExpanding = false)
Definition at line 8909 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::sampleprof::Base, Chain, dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getVTList(), Indexed, llvm::BitmaskEnumDetail::Mask(), llvm::ISD::MLOAD, N, NewSDValueDbgMsg(), llvm::Offset, llvm::MVT::Other, and llvm::ISD::UNINDEXED.
Referenced by combineMaskedLoad(), combineMaskedLoadConstantMask(), getIndexedMaskedLoad(), LowerMLOAD(), performLDNT1Combine(), performUnpackCombine(), and tryToFoldExtOfMaskedLoad().
getMaskedScatter()
SDValue SelectionDAG::getMaskedScatter (SDVTList VTs, EVT MemVT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType, bool IsTruncating = false)
Definition at line 9051 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGE(), llvm::ISD::MSCATTER, N, NewSDValueDbgMsg(), and llvm::ArrayRef< T >::size().
Referenced by llvm::RISCVTargetLowering::PerformDAGCombine(), performMaskedGatherScatterCombine(), and rebuildGatherScatter().
getMaskedStore()
SDValue SelectionDAG::getMaskedStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Base, SDValue Offset, SDValue Mask, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, bool IsTruncating = false, bool IsCompressing = false)
Definition at line 8955 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::sampleprof::Base, Chain, dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getVTList(), Indexed, llvm::BitmaskEnumDetail::Mask(), llvm::ISD::MSTORE, N, NewSDValueDbgMsg(), llvm::Offset, llvm::MVT::Other, and llvm::ISD::UNINDEXED.
Referenced by combineMaskedStore(), getIndexedMaskedStore(), LowerINTRINSIC_W_CHAIN(), LowerMSTORE(), performMSTORECombine(), and performSTNT1Combine().
getMCSymbol()
SDValue SelectionDAG::getMCSymbol (MCSymbol * Sym, EVT VT)
Definition at line 1906 of file SelectionDAG.cpp.
References N.
Referenced by recoverFramePointer(), and transformCallee().
getMDNode()
SDValue SelectionDAG::getMDNode (const MDNode * MD)
Return an MDNodeSDNode which holds an MDNode.
Definition at line 2235 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), llvm::ISD::MDNODE_SDNODE, N, and llvm::MVT::Other.
Referenced by llvm::PPCTargetLowering::CollectTargetIntrinsicOperands(), and llvm::SelectionDAGBuilder::getValueImpl().
getMemBasePlusOffset() [1/2]
SDValue SelectionDAG::getMemBasePlusOffset (SDValue Base, SDValue Offset, const SDLoc & DL, const SDNodeFlags Flags = SDNodeFlags())
Definition at line 6957 of file SelectionDAG.cpp.
References llvm::ISD::ADD, assert(), DL, getNode(), llvm::Offset, and Ptr.
getMemBasePlusOffset() [2/2]
SDValue SelectionDAG::getMemBasePlusOffset (SDValue Base, TypeSize Offset, const SDLoc & DL, const SDNodeFlags Flags = SDNodeFlags())
Returns sum of the base pointer and offset.
Unlike getObjectPtrOffset this does not set NoUnsignedWrap by default.
Definition at line 6941 of file SelectionDAG.cpp.
References llvm::sampleprof::Base, DL, getConstant(), getVScale(), Index, and llvm::Offset.
Referenced by combineLoad(), combineStore(), combineTargetShuffle(), EmitUnrolledSetTag(), getBROADCAST_LOAD(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getObjectPtrOffset(), getParamsForOneTrueMaskedElt(), llvm::TargetLowering::getVectorSubVecPointer(), lowerShuffleAsBroadcast(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerVECTOR_SHUFFLE(), narrowExtractedVectorLoad(), performLOADCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), and splitVectorStore().
getMemcpy()
SDValue SelectionDAG::getMemcpy (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, const AAMDNodes & AAInfo = AAMDNodes(), AAResults * AA = nullptr)
Definition at line 7458 of file SelectionDAG.cpp.
References AAInfo, Alignment, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), Chain, checkAddrSpaceIsValidForLibcall(), dl, llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemcpy(), llvm::MachinePointerInfo::getAddrSpace(), getMemcpyLoadsAndStores(), llvm::ConstantSDNode::getZExtValue(), and llvm::ConstantSDNode::isZero().
Referenced by CreateCopyOfByValArgument(), emitConstantSizeRepmov(), llvm::LoongArchTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::HexagonTargetLowering::LowerVACOPY(), and LowerVACOPY().
getMemIntrinsicNode() [1/3]
SDValue SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachineMemOperand * MMO)
Definition at line 7909 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), dl, E, llvm::ISD::FIRST_TARGET_MEMORY_OPCODE, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::MVT::Glue, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::max(), N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, llvm::ISD::PREFETCH, and llvm::SDVTList::VTs.
getMemIntrinsicNode() [2/3]
SDValue SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags Flags = MachineMemOperand::MOLoad | MachineMemOperand::MOStore, uint64_t Size = 0, const AAMDNodes & AAInfo = AAMDNodes())
Creates a MemIntrinsicNode that may produce a result and takes a list of operands.
Opcode may be INTRINSIC_VOID, INTRINSIC_W_CHAIN, or a target-specific opcode with a value not less than FIRST_TARGET_MEMORY_OPCODE.
Definition at line 7893 of file SelectionDAG.cpp.
References AAInfo, Alignment, dl, getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::EVT::getStoreSize(), llvm::EVT::isScalableVector(), PtrInfo, and llvm::MemoryLocation::UnknownSize.
Referenced by llvm::X86TargetLowering::BuildFILD(), combineBitcast(), combineBVZEXTLOAD(), combineINSERT_SUBVECTOR(), combineTargetShuffle(), CombineVLDDUP(), createLoadLR(), createStoreLR(), EltsFromConsecutiveLoads(), EmitMaskedTruncSStore(), EmitTruncSStore(), EmitUnrolledSetTag(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), getAVX2GatherNode(), getBROADCAST_LOAD(), getGatherNode(), getMemIntrinsicNode(), getScatterNode(), lowerAtomicArithWithLOCK(), lowerBuildVectorAsBroadcast(), llvm::NVPTXTargetLowering::LowerCall(), LowerCMP_SWAP(), LowerINTRINSIC_W_CHAIN(), LowerMGATHER(), LowerMSCATTER(), llvm::SystemZTargetLowering::LowerOperationWrapper(), llvm::NVPTXTargetLowering::LowerReturn(), lowerShuffleAsBroadcast(), LowerSTORE(), LowerStore(), lowerUINT_TO_FP_vXi32(), lowerVECTOR_SHUFFLE(), AMDGPUDAGToDAGISel::matchLoadD16FromBuildVector(), narrowLoadToVZLoad(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformMVEVLDCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformVDUPCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), and TryCombineBaseUpdate().
getMemIntrinsicNode() [3/3]
SDValue llvm::SelectionDAG::getMemIntrinsicNode (unsigned Opcode, const SDLoc & dl, SDVTList VTList, ArrayRef< SDValue > Ops, EVT MemVT, MachinePointerInfo PtrInfo, MaybeAlign Alignment = std::nullopt, MachineMemOperand::Flags Flags = MachineMemOperand::MOLoad | MachineMemOperand::MOStore, uint64_t Size = 0, const AAMDNodes & AAInfo = AAMDNodes()) inline
Definition at line 1263 of file SelectionDAG.h.
References AAInfo, Alignment, dl, getEVTAlign(), getMemIntrinsicNode(), PtrInfo, and Size.
getMemmove()
SDValue SelectionDAG::getMemmove (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool isTailCall, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo, const AAMDNodes & AAInfo = AAMDNodes(), AAResults * AA = nullptr)
Definition at line 7572 of file SelectionDAG.cpp.
References AAInfo, Alignment, llvm::AMDGPU::HSAMD::Kernel::Key::Args, Chain, checkAddrSpaceIsValidForLibcall(), dl, llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemmove(), llvm::MachinePointerInfo::getAddrSpace(), getMemmoveLoadsAndStores(), llvm::ConstantSDNode::getZExtValue(), and llvm::ConstantSDNode::isZero().
getMemset()
SDValue SelectionDAG::getMemset (SDValue Chain, const SDLoc & dl, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool isVol, bool AlwaysInline, bool isTailCall, MachinePointerInfo DstPtrInfo, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 7674 of file SelectionDAG.cpp.
References AAInfo, Alignment, assert(), Chain, checkAddrSpaceIsValidForLibcall(), DL, dl, llvm::SelectionDAGTargetInfo::EmitTargetCodeForMemset(), llvm::MachinePointerInfo::getAddrSpace(), getContext(), getDataLayout(), llvm::TargetLoweringBase::getLibcallName(), getMemsetStores(), getTargetLoweringInfo(), llvm::ConstantSDNode::getZExtValue(), llvm::ConstantSDNode::isZero(), llvm::TargetLowering::CallLoweringInfo::setChain(), and llvm::TargetLowering::CallLoweringInfo::setDebugLoc().
Referenced by llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset().
getMergeValues()
SDValue SelectionDAG::getMergeValues (ArrayRef< SDValue > Ops, const SDLoc & dl)
Create a MERGE_VALUES node from the given operands.
getMergeValues - Create a MERGE_VALUES node from the given operands.
Definition at line 7882 of file SelectionDAG.cpp.
References dl, getNode(), getVTList(), llvm::ISD::MERGE_VALUES, llvm::SmallVectorImpl< T >::reserve(), and llvm::ArrayRef< T >::size().
Referenced by combineFP_EXTEND(), combineFP_ROUND(), combineVectorCompareAndMaskUnaryOp(), combineX86AddSub(), constructRetValue(), emitIntrinsicWithChainErrorMessage(), getAVX2GatherNode(), getGatherNode(), llvm::VECustomDAG::getMergeValues(), llvm::SelectionDAGBuilder::getValueImpl(), LowerADDC_ADDE_SUBC_SUBE(), llvm::HexagonTargetLowering::LowerAddSubCarry(), llvm::VETargetLowering::lowerATOMIC_SWAP(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), LowerF128Load(), LowerFP16_TO_FP(), LowerFP_TO_FP16(), LowerI64IntToFP16(), LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), LowerINTRINSIC_W_CHAIN(), llvm::HexagonTargetLowering::LowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), LowerLoad(), lowerLoadF128(), lowerLoadI1(), LowerMGATHER(), LowerMLOAD(), LowerMULO(), LowerPredicateLoad(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), LowerREADCYCLECOUNTER(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), LowerShiftParts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), LowerUINT_TO_FP_i32(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), LowerVSETCC(), llvm::AArch64TargetLowering::PerformDAGCombine(), performFlagSettingCombine(), performGatherLoadCombine(), performLD1Combine(), performLD1ReplicateCombine(), performLDNT1Combine(), llvm::AMDGPUTargetLowering::performLoadCombine(), performLOADCombine(), PerformLongShiftCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformVMOVRRDCombine(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad().
getNegative()
SDValue SelectionDAG::getNegative (SDValue Val, const SDLoc & DL, EVT VT)
Create negative operation as (SUB 0, Val).
Definition at line 1491 of file SelectionDAG.cpp.
References DL, getConstant(), getNode(), and llvm::ISD::SUB.
Referenced by llvm::RISCVTargetLowering::PerformDAGCombine().
getNeutralElement()
SDValue SelectionDAG::getNeutralElement (unsigned Opcode, const SDLoc & DL, EVT VT, SDNodeFlags Flags)
Get the (commutative) neutral element for the given opcode, if it exists.
Definition at line 12158 of file SelectionDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::APFloat::changeSign(), DL, EVTToAPFloatSemantics(), llvm::ISD::FADD, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, getAllOnesConstant(), getConstant(), getConstantFP(), llvm::APFloat::getInf(), llvm::APFloat::getLargest(), llvm::APFloat::getQNaN(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::EVT::getSizeInBits(), llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::UMAX, llvm::ISD::UMIN, and llvm::ISD::XOR.
Referenced by getRVVFPReductionOpAndOperands().
getNode() [1/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, ArrayRef< EVT > ResultTys, ArrayRef< SDValue > Ops)
Definition at line 9338 of file SelectionDAG.cpp.
References DL, getNode(), and getVTList().
getNode() [2/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT)
Gets or creates the specified node.
Definition at line 5183 of file SelectionDAG.cpp.
References AddNodeIDNode(), DL, E, getVTList(), N, and NewSDValueDbgMsg().
getNode() [3/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDUse > Ops)
Gets or creates the specified node.
Definition at line 9202 of file SelectionDAG.cpp.
References llvm::ArrayRef< T >::begin(), DL, llvm::ArrayRef< T >::end(), and llvm::ArrayRef< T >::size().
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), addIPMSequence(), addRequiredExtensionForVectorMULL(), AddRequiredExtensionForVMULL(), addShuffleForVecExtend(), llvm::AMDGPUTargetLowering::addTokenForArgument(), adjustBitcastSrcVectorSSE1(), adjustLoadValueTypeImpl(), buildCallOperands(), BuildExactSDIV(), buildFromShuffleMostly(), BuildIntrinsicOp(), buildMergeScalars(), buildPCRelGlobalAddress(), buildScalarToVector(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildUDIV(), BuildVSLDOI(), canonicalizeBitSelect(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeShuffleMaskWithHorizOp(), canonicalizeShuffleWithBinOps(), carryFlagToValue(), chainLoadsAndStoresForMemcpy(), clampDynamicVectorIndex(), CollectOpsToWiden(), combine_CC(), combineAcrossLanesIntrinsic(), combineADC(), combineAdd(), combineADDCARRYDiamond(), combineAddOfPMADDWD(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineADDToMAT_PCREL_ADDR(), combineADDX(), combineAnd(), combineAndMaskToShift(), combineAndNotIntoANDNP(), combineAndnp(), CombineANDShift(), combineAndShuffleNot(), combineArithReduction(), combineBasicSADPattern(), combineBinOpToReduce(), combineBitcast(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineBitOpWithMOVMSK(), combineBitOpWithShift(), combineBrCond(), combineCarryDiamond(), combineCarryThroughADD(), combineCastedMaskArithmetic(), combineCMov(), combineCMP(), combineCmpOp(), combineCommutableSHUFP(), combineCompareEqual(), combineConcatVectorOfCasts(), combineConcatVectorOfConcatVectors(), combineConcatVectorOfScalars(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineCVTPH2PS(), combineDeMorganOfBoolean(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFaddCFmul(), combineFAndFNotToFAndn(), combineFMA(), combineFMADDSUB(), combineFMinFMax(), llvm::AMDGPUTargetLowering::combineFMinMaxLegacy(), llvm::AMDGPUTargetLowering::combineFMinMaxLegacyImpl(), combineFMinNumFMaxNum(), combineFMulcFCMulc(), combineFneg(), combineFP16_TO_FP(), combineFP_EXTEND(), combineFP_ROUND(), combineGatherScatter(), combineHorizOpWithShuffle(), combineINSERT_SUBVECTOR(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineM68kBrCond(), combineMinMaxReduction(), combineMinNumMaxNumImpl(), combineMOVMSK(), combineMul(), combineMulSpecial(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineOr(), combineOrCmpEqZeroToCtlzSrl(), combinePMULDQ(), combinePMULH(), combinePredicateReduction(), combinePTESTCC(), combineRedundantDWordShuffle(), combineSBB(), combineScalarAndWithMaskSetcc(), combineScalarToVector(), llvm::VETargetLowering::combineSelect(), combineSelect(), combineSelectAndUse(), llvm::VETargetLowering::combineSelectCC(), combineSelectOfTwoConstants(), combineSetCC(), combineSetCCMOVMSK(), combineSext(), combineSextInRegCmov(), combineShiftAnd1ToBitTest(), combineShiftLeft(), combineShiftOfShiftedLogic(), combineShiftRightArithmetic(), combineShiftRightLogical(), combineShiftToAVG(), combineShiftToMULH(), combineShiftToPMULH(), combineShuffleOfConcatUndef(), combineShuffleToAddSubOrFMAddSub(), combineShuffleToAnyExtendVectorInreg(), combineShuffleToFMAddSub(), combineShuffleToZeroExtendVectorInReg(), combineSignExtendInReg(), combineSIntToFP(), combineStore(), combineSub(), combineSubABS(), combineSubOfBoolean(), combineSUBX(), combineSVEPrefetchVecBaseImmOff(), combineSVEReductionFP(), combineSVEReductionInt(), combineSVEReductionOrderedFP(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineToExtendCMOV(), combineToFPTruncExtElt(), combineToHorizontalAddSub(), combineTruncate(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineUIntToFP(), combineVectorCompareAndMaskUnaryOp(), combineVectorHADDSUB(), combineVectorInsert(), combineVectorPack(), combineVectorShiftImm(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineVectorTruncationWithPACKSS(), combineVectorTruncationWithPACKUS(), CombineVMOVDRRCandidateWithVecOp(), combineVPDPBUSDPattern(), combineVSelectToBLENDV(), combineVSelectWithAllOnesOrZeros(), combineVTRUNC(), combineX86AddSub(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineXor(), combineXorSubCTLZ(), combineZext(), CompactSwizzlableVector(), constructDup(), constructRetValue(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), convertFixedMaskToScalableVector(), convertFPToInt(), convertFromScalableVector(), convertIntLogicToFPLogic(), convertIntToFP(), convertLocVTToValVT(), convertMergedOpToPredOp(), ConvertSelectToConcatVector(), convertShiftLeftToScale(), convertToScalableVector(), convertValVTToLocVT(), createCMovFP(), createFPCmp(), createGPRPairNode(), createLoadLR(), createMemMemNode(), createMMXBuildVector(), createPSADBW(), createStoreLR(), createVariablePermute(), createVPDPBUSD(), customLegalizeToWOp(), customLegalizeToWOpWithSExt(), detectAVGPattern(), detectPMADDUBSW(), detectUSatPattern(), distributeOpThroughSelect(), EltsFromConsecutiveLoads(), EmitAVX512Test(), EmitCMP(), EmitCmp(), emitComparison(), emitConditionalComparison(), emitConstantSizeRepmov(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), emitMemMemReg(), llvm::AArch64SelectionDAGInfo::EmitMOPS(), emitOrXorXorTree(), emitRepmovs(), emitSETCC(), emitStrictFPComparison(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen(), EmitTest(), EmitUnrolledSetTag(), EmitVectorComparison(), Expand64BitShift(), llvm::TargetLowering::expandABS(), llvm::TargetLowering::expandBITREVERSE(), llvm::TargetLowering::expandBSWAP(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), expandExp(), expandExp2(), expandf64Toi32(), llvm::TargetLowering::expandFixedPointDiv(), expandFP_TO_UINT_SSE(), ExpandHorizontalBinOp(), llvm::X86TargetLowering::expandIndirectJTBranch(), llvm::TargetLowering::expandIndirectJTBranch(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandIS_FPCLASS(), expandLog(), expandLog10(), expandLog2(), llvm::TargetLowering::expandMUL_LOHI(), expandPow(), ExpandPowI(), ExpandREAD_REGISTER(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), expandV4F32ToV2F64(), llvm::TargetLowering::expandVPBITREVERSE(), llvm::TargetLowering::expandVPBSWAP(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendToType(), ExtractBitFromMaskVector(), extractF64Exponent(), extractLOHI(), extractShiftForRotate(), extractSubVector(), ExtractVectorElements(), finalizeTS1AM(), findMoreOptimalIndexType(), foldADCToCINC(), foldAddSubBoolOfMaskedVal(), foldAddSubMasked1(), foldAddSubOfSignBit(), foldAndOrOfSETCC(), foldAndToUsubsat(), foldBoolSelectToLogic(), FoldConstantArithmetic(), foldCSELOfCSEL(), foldCSELofCTTZ(), foldExtendedSignBitTest(), foldExtendVectorInregToExtendOfSubvector(), foldExtractSubvectorFromShuffleVector(), foldFPToIntToFP(), foldFreeOpFromSelect(), foldIndexIntoBase(), FoldIntToFPToInt(), foldLogicOfShifts(), foldLogicTreeOfShifts(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedMergeImpl(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldOverflowCheck(), foldSelectOfConstantsUsingSra(), foldSelectWithIdentityConstant(), foldSetCCWithFunnelShift(), foldSetCCWithRotate(), foldShuffleOfConcatUndefs(), foldVectorXorShiftIntoCmp(), foldVSelectToSignBitSplatMask(), foldXorTruncShiftIntoCmp(), genConstMult(), generateComparison(), generateEquivalentSub(), GeneratePerfectShuffle(), GenerateTBL(), getAArch64Cmp(), getAArch64XALUOOp(), getAbsolute(), llvm::MipsTargetLowering::getAddrGlobal(), llvm::MipsTargetLowering::getAddrGlobalLargeGOT(), llvm::MipsTargetLowering::getAddrGPRel(), llvm::MipsTargetLowering::getAddrLocal(), llvm::MipsTargetLowering::getAddrNonPIC(), llvm::MipsTargetLowering::getAddrNonPICSym64(), getAllOnesMask(), getAnyExtOrTrunc(), getAVX512Node(), getAVX512TruncNode(), getBitcast(), getBitTestCondition(), getBMIMatchingOp(), getBoolExtOrTrunc(), getBT(), getBuildVector(), getBuildVectorSplat(), getCALLSEQ_END(), getCALLSEQ_START(), getCCResult(), getConstant(), getCopyFromParts(), getCopyFromPartsVector(), getCopyFromReg(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), getCopyToReg(), llvm::RegsForValue::getCopyToRegs(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getEstimate(), GetExponent(), getEXTEND_VECTOR_INREG(), getFLUSHW(), getFPBinOp(), getFPExtendOrRound(), getFPTernOp(), getFRAMEADDR(), getFreeze(), getGeneralPermuteNode(), getGLOBAL_OFFSET_TABLE(), llvm::AMDGPUTargetLowering::getHiHalf64(), getHopForBuildVector(), getKnownUndefForVectorBinop(), getLimitedPrecisionExp2(), getLoadExtOrTrunc(), getLogicalNOT(), llvm::AMDGPUTargetLowering::getLoHalf64(), getMad64_32(), llvm::VECustomDAG::getMaskBroadcast(), getMaskNode(), getMemBasePlusOffset(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), getMergeValues(), getMul24(), llvm::AMDGPUTargetLowering::getNegatedExpression(), llvm::PPCTargetLowering::getNegatedExpression(), llvm::X86TargetLowering::getNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), getNegatedInteger(), getNegative(), llvm::VECustomDAG::getNode(), getNode(), getNOT(), llvm::VECustomDAG::getPack(), getPack(), getPermuteNode(), llvm::VETargetLowering::getPICJumpTableRelocBase(), llvm::M68kTargetLowering::getPICJumpTableRelocBase(), llvm::HexagonTargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), getPMOVMSKB(), getPTest(), getPTrue(), llvm::AMDGPUTargetLowering::getRecipEstimate(), getReductionSDNode(), getRegistersForValue(), getScalarMaskingNode(), getScaledOffsetForBitWidth(), getSelect(), getSelectCC(), getSetCC(), getSETCC(), getSetCCVP(), getSExtOrTrunc(), getShuffleHalfVectors(), GetSignificand(), getSplatBuildVector(), getSplatValue(), getSplatVector(), llvm::AMDGPUTargetLowering::getSqrtEstimate(), llvm::NVPTXTargetLowering::getSqrtEstimate(), llvm::TargetLowering::getSqrtInputTest(), getStackArgumentTokenFactor(), getStepVector(), getSToVPermuted(), getStrictFPExtendOrRound(), getSVEPredicateBitCast(), getTargetVShiftByConstNode(), getTargetVShiftNode(), GetTLSADDR(), getTokenFactor(), getTruncatedUSUBSAT(), getUNDEF(), llvm::VECustomDAG::getUnpack(), getv64i1Argument(), getVAArg(), getVectorMaskingNode(), getVectorShuffle(), llvm::TargetLowering::getVectorSubVecPointer(), getVPLogicalNOT(), getVPZExtOrTrunc(), getVScale(), getVShift(), getVSlidedown(), getVSlideup(), getX86XALUOOp(), getZeroExtendInReg(), getZeroVector(), getZExtOrTrunc(), HandleMergeInputChains(), llvm::TargetLowering::IncrementMemoryAddress(), initAccumulator(), insert1BitVector(), InsertBitToMaskVector(), insertSubVector(), isFNEG(), isFusableLoadOpStorePattern(), IsNOT(), joinDwords(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), Legalize(), llvm::TargetLowering::LegalizeSetCCCondCode(), legalizeSVEGatherPrefetchOffsVec(), llvm::AMDGPUTargetLowering::loadInputValue(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), LowerABD(), LowerABS(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDRSPACECAST(), LowerADDSAT_SUBSAT(), llvm::HexagonTargetLowering::LowerAddSubCarry(), lowerADDSUBCARRY(), LowerADDSUBCARRY(), LowerADDSUBSAT(), lowerAddSubToHorizontalOp(), llvm::X86TargetLowering::LowerAsmOutputForConstraint(), LowerAsSplatVectorLoad(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::VETargetLowering::lowerATOMIC_FENCE(), llvm::HexagonTargetLowering::LowerATOMIC_FENCE(), LowerATOMIC_FENCE(), llvm::VETargetLowering::lowerATOMIC_SWAP(), lowerAtomicArith(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), lowerBALLOTIntrinsic(), LowerBITCAST(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), llvm::LanaiTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::LanaiTargetLowering::LowerBR_CC(), llvm::MSP430TargetLowering::LowerBR_CC(), LowerBR_CC(), LowerBRCOND(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), lowerBUILD_VECTOR(), LowerBUILD_VECTOR_i1(), LowerBUILD_VECTORToVIDUP(), LowerBUILD_VECTORvXbf16(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), LowerBuildVectorOfFPExt(), LowerBuildVectorOfFPTrunc(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), lowerCallResult(), LowerCallResult(), LowerCMP_SWAP(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::AMDGPUTargetLowering::LowerCONCAT_VECTORS(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::HexagonTargetLowering::LowerConstantPool(), LowerConvertLow(), LowerCTLZ(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), LowerCTPOP(), LowerCTTZ(), LowerCVTPS2PH(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), llvm::LanaiTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::VETargetLowering::lowerEH_SJLJ_LONGJMP(), llvm::VETargetLowering::lowerEH_SJLJ_SETJMP(), llvm::VETargetLowering::lowerEH_SJLJ_SETUP_DISPATCH(), LowerEXTEND_VECTOR_INREG(), llvm::MSP430TargetLowering::LowerExternalSymbol(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_i1(), LowerEXTRACT_VECTOR_ELT_SSE4(), llvm::SparcTargetLowering::LowerF128Compare(), LowerF128Load(), LowerF128Store(), LowerF64Op(), LowerFABSorFNEG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), lowerFCMPIntrinsic(), LowerFCOPYSIGN(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), LowerFGETSIGN(), llvm::AMDGPUTargetLowering::LowerFLOG(), llvm::AMDGPUTargetLowering::LowerFNEARBYINT(), LowerFNEGorFABS(), llvm::VETargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFP16_TO_FP(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), lowerFP_TO_INT_SAT(), LowerFP_TO_INT_SAT(), LowerFP_TO_SINT(), lowerFP_TO_SINT_STORE(), lowerFPToIntToFP(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerFREM(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND(), LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFROUNDEVEN(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), LowerFunnelShift(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerGR128Binary(), lowerGR128ToI128(), LowerHorizontalByteSum(), lowerI128ToGR128(), LowerI64IntToFP16(), LowerI64IntToFP_AVX512DQ(), lowerICMPIntrinsic(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINSERT_VECTOR_ELT_i1(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP64(), lowerINT_TO_FP_vXi64(), LowerInterruptReturn(), llvm::HexagonTargetLowering::LowerINTRINSIC_VOID(), LowerINTRINSIC_W_CHAIN(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), llvm::HexagonTargetLowering::LowerJumpTable(), LowerLabelRef(), llvm::MipsTargetLowering::lowerLOAD(), LowerLoad(), lowerLoadF128(), lowerLoadI1(), lowerMasksToReg(), LowerMemOpCallTo(), LowerMGATHER(), LowerMLOAD(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSACopyIntr(), lowerMSALoadIntr(), lowerMSASplatZExt(), lowerMSAStoreIntr(), LowerMSCATTER(), llvm::LanaiTargetLowering::LowerMUL(), LowerMUL(), lowerMUL_LOHI32(), LowerMULH(), LowerMULO(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), llvm::AArch64TargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerPARITY(), LowerPredicateLoad(), LowerPredicateStore(), llvm::HexagonTargetLowering::LowerPREFETCH(), LowerPREFETCH(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::HexagonTargetLowering::LowerREADCYCLECOUNTER(), lowerReductionSeq(), lowerRegToMasks(), llvm::VETargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::AMDGPUTargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), lowerRETURNADDR(), LowerRETURNADDR(), LowerReverse_VECTOR_SHUFFLE(), LowerRotate(), LowerSaturatingConditional(), LowerSCALAR_TO_VECTOR(), lowerScalarInsert(), lowerScalarSplat(), LowerSDIV(), LowerSDIV_v4i16(), LowerSDIV_v4i8(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), llvm::MSP430TargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), llvm::LanaiTargetLowering::LowerSETCC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShiftByScalarImmediate(), LowerShiftByScalarVariable(), llvm::MSP430TargetLowering::LowerShifts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsTruncBroadcast(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVALIGN(), lowerShuffleAsVTRUNC(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleOfExtractsAsVperm(), lowerShufflePairAsUNPCKAndPermute(), lowerShuffleToEXPAND(), lowerShuffleWithPACK(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), lowerShuffleWithSHUFPD(), lowerShuffleWithSHUFPS(), lowerShuffleWithSSE4A(), lowerShuffleWithUndefHalf(), lowerShuffleWithUNPCK(), lowerShuffleWithUNPCK256(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerSIGN_EXTEND_Mask(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), LowerSINT_TO_FP(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerSTORE(), LowerStore(), lowerStoreF128(), lowerStoreI1(), LowerSVEIntrinsicDUP(), LowerSVEIntrinsicEXT(), LowerSVEIntrinsicIndex(), lowerToAddSubOrFMAddSub(), LowerToTLSExecModel(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerToTLSGeneralDynamicModel32(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), LowerTruncate(), LowerTruncatei1(), LowerTruncateVecI1(), LowerTruncateVectorStore(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerUINT_TO_FP_i32(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV4X128Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), llvm::VETargetLowering::lowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), LowerVecReduce(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VSHF(), lowerVECTOR_SHUFFLEAsVNSRL(), lowerVECTOR_SHUFFLEAsVSlidedown(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVECTOR_SHUFFLEUsingOneOff(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZero(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOP(), LowerVectorCTPOPInRegLUT(), LowerVectorExtend(), LowerVectorFP_TO_INT(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), LowerVectorINT_TO_FP(), lowerVectorIntrinsicScalars(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowervXi8MulWithUNPCK(), LowerWRITE_REGISTER(), lowerX86CmpEqZeroToCtlzSrl(), lowerX86FPLogicOp(), LowerXALUO(), LowerZERO_EXTEND_Mask(), llvm::SparcTargetLowering::makeAddress(), llvm::VETargetLowering::makeAddress(), makeEquivalentMemoryOrdering(), llvm::SparcTargetLowering::makeHiLoPair(), llvm::VETargetLowering::makeHiLoPair(), matchBinOpReduction(), matchBSwapHWordOrAndAnd(), AMDGPUDAGToDAGISel::matchLoadD16FromBuildVector(), matchPMADDWD(), matchPMADDWD_2(), matchSplatAsGather(), MatchVectorAllZeroTest(), moveBelowOrigChain(), narrowExtractedVectorBinOp(), narrowInsertExtractVectorBinOp(), narrowVectorSelect(), optimizeLogicalImm(), overflowFlagToValue(), packImage16bitOpsToDwords(), partitionShuffleOfConcats(), llvm::SITargetLowering::passSpecialInputs(), Passv64i1ArgInRegs(), performADDCombine(), performAddCombineForShiftedOperands(), performAddCombineSubShift(), PerformADDCombineWithOperands(), performAddCSelIntoCSinc(), PerformAddcSubcCombine(), performAddDotCombine(), PerformAddeSubeCombine(), performAddSubLongCombine(), performAddUADDVCombine(), PerformADDVecReduce(), performANDCombine(), PerformANDCombine(), performANDORCSELCombine(), PerformARMBUILD_VECTORCombine(), llvm::AMDGPUTargetLowering::performAssertSZExtCombine(), PerformBFICombine(), PerformBITCASTCombine(), performBITREV_WCombine(), performBITREVERSECombine(), llvm::ARMTargetLowering::PerformBRCONDCombine(), performBRCONDCombine(), performBSPExpandForSVE(), PerformBUILD_VECTORCombine(), performBuildShuffleExtendCombine(), performBuildVectorCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCMovFPCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), performCONDCombine(), PerformCSETCombine(), performCTLZCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDivRemCombine(), performDSPShiftCombine(), performDUPCombine(), performDupLane128Combine(), PerformExtendCombine(), performExtendCombine(), PerformExtractEltCombine(), PerformExtractEltToVMOVRRD(), performExtractSubvectorCombine(), performExtractVectorEltCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), PerformFAddVSelectCombine(), performFDivCombine(), performFlagSettingCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), performFP_TO_INT_SATCombine(), performFP_TO_INTCombine(), performFPExtendCombine(), performFpToIntCombine(), performGatherLoadCombine(), performGLD1Combine(), performGlobalAddressCombine(), PerformHWLoopCombine(), PerformInsertEltCombine(), PerformInsertSubvectorCombine(), performInsertSubvectorCombine(), llvm::ARMTargetLowering::PerformIntrinsicCombine(), performIntrinsicCombine(), performIntToFpCombine(), performLD1Combine(), performLD1ReplicateCombine(), performLDNT1Combine(), llvm::AMDGPUTargetLowering::performLoadCombine(), performLOADCombine(), PerformLongShiftCombine(), performMADD_MSUBCombine(), PerformMinMaxCombine(), PerformMinMaxFpToSatCombine(), PerformMinMaxToSatCombine(), PerformMULCombine(), performMulCombine(), llvm::AMDGPUTargetLowering::performMulhsCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), llvm::AMDGPUTargetLowering::performMulLoHiCombine(), performMulVectorCmpZeroCombine(), performMulVectorExtendCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformMVEVMULLCombine(), performNegCSelCombine(), performORCombine(), PerformORCombine(), PerformORCombine_i1(), PerformORCombineToBFI(), PerformORCombineToSMULWBT(), performOrXorChainCombine(), PerformPREDICATE_CASTCombine(), PerformReduceShuffleCombine(), PerformREMCombine(), performScatterStoreCombine(), llvm::AMDGPUTargetLowering::performSelectCombine(), performSELECTCombine(), PerformSELECTCombine(), performSelectCombine(), performSetccAddFolding(), PerformSETCCCombine(), performSETCCCombine(), performSetccMergeZeroCombine(), PerformShiftCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), performSHLCombine(), PerformSHLSimplify(), PerformShuffleVMOVNCombine(), performSIGN_EXTEND_INREGCombine(), PerformSignExtendInregCombine(), performSignExtendInRegCombine(), performSignExtendSetCCCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performSraCombine(), performSRACombine(), llvm::AMDGPUTargetLowering::performSrlCombine(), performSRLCombine(), performST1Combine(), performSTNT1Combine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), performSubAddMULCombine(), PerformSUBCombine(), PerformSubCSINCCombine(), performSubsToAndsCombine(), performSunpkloCombine(), performSVEAndCombine(), performSVESpliceCombine(), performTBZCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), performTRUNCATECombine(), performTruncateCombine(), PerformTruncatingStoreCombine(), performUADDVAddCombine(), performUADDVCombine(), PerformUMinFpToSatCombine(), PerformUMLALCombine(), performUzpCombine(), PerformVCMPCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPCombine(), PerformVDUPLANECombine(), PerformVECREDUCE_ADDCombine(), performVecReduceAddCombine(), performVecReduceAddCombineWithUADDLP(), PerformVECTOR_REG_CASTCombine(), PerformVECTOR_SHUFFLECombine(), performVectorAddSubExtCombine(), performVectorCompareAndMaskUnaryOpCombine(), performVectorExtendCombine(), performVectorExtendToFPCombine(), performVectorTruncZeroCombine(), PerformVMOVDRRCombine(), PerformVMOVhrCombine(), PerformVMOVNCombine(), PerformVMOVrhCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), PerformVQDMULHCombine(), performVSELECTCombine(), PerformVSELECTCombine(), performVSelectCombine(), PerformVSetCCToVCTPCombine(), performXORCombine(), PerformXORCombine(), prepareDescriptorIndirectCall(), prepareIndirectCall(), PrepareTailCall(), prepareTS1AM(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), promoteExtBeforeAdd(), PromoteMaskArithmetic(), PromoteMVEPredVector(), llvm::TargetLoweringBase::promoteTargetBoolean(), promoteToConstantPool(), promoteXINT_TO_FP(), pushAddIntoCmovOfConsts(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReconstructTruncateFromBuildVector(), recoverFramePointer(), reduceMaskedLoadToScalarLoad(), reduceMaskedStoreToScalarStore(), reduceVMULWidth(), refineUniformBase(), ReorganizeVector(), ReplaceAddWithADDP(), ReplaceAllUsesWith(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), ReplaceLongIntrinsic(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), ReplaceReductionResults(), replaceShuffleOfInsert(), SaturateWidenedDIVFIX(), scalarizeBinOpOfSplats(), scalarizeExtEltFP(), scalarizeExtractedBinop(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWOChain(), selectUmullSmull(), llvm::TargetLowering::ShrinkDemandedConstant(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), signExtendBitcastSrcVector(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::ARMTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyMul24(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), SkipExtensionForVMULL(), llvm::TargetLowering::softenSetCCOperands(), splatPartsI64WithVL(), splatSplitI64WithVL(), llvm::AMDGPUTargetLowering::split64BitValue(), SplitAndExtendv16i1(), splitAndLowerShuffle(), llvm::AMDGPUTargetLowering::splitBinaryBitConstantOpImpl(), llvm::SITargetLowering::splitBinaryVectorOp(), SplitEVL(), splitInt128(), splitIntVSETCC(), SplitOpsAndApply(), splitStores(), splitStoreSplat(), llvm::SITargetLowering::splitTernaryVectorOp(), llvm::SITargetLowering::splitUnaryVectorOp(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::PPCTargetLowering::splitValueIntoRegisterParts(), llvm::AMDGPUTargetLowering::splitVector(), SplitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), splitVectorOp(), llvm::AMDGPUTargetLowering::SplitVectorStore(), splitVectorStore(), llvm::AMDGPUTargetLowering::storeStackInputValue(), stripModuloOnShift(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), transformAddImmMulImm(), transformAddShlImm(), translateSetCCForBranch(), truncateScalarIntegerArg(), truncateVecElts(), truncateVectorWithNARROW(), truncateVectorWithPACK(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), tryAdvSIMDModImm321s(), tryAdvSIMDModImm64(), tryAdvSIMDModImm8(), tryAdvSIMDModImmFP(), TryCombineBaseUpdate(), tryCombineCRC32(), tryCombineFixedPointConvert(), tryCombineLongOpWithDup(), tryCombineShiftImm(), tryCombineToBSL(), tryCombineToEXTR(), tryConvertSVEWideCompare(), tryDemorganOfBooleanCondition(), TryDistrubutionADDVecReduce(), tryExtendDUPToExtractHigh(), tryFoldSelectIntoOp(), tryFormConcatFromShuffle(), tryLowerToSLI(), TryMULWIDECombine(), trySwapVSelectOperands(), tryToConvertShuffleOfTbl2ToTbl4(), tryToFoldExtendOfConstant(), tryToFoldExtendSelectLoad(), tryToFoldExtOfLoad(), tryToFoldExtOfMaskedLoad(), tryToWidenSetCCOperands(), unpack64(), unpackF64OnRV32DSoftABI(), UnpackFromArgumentSlot(), UnrollVectorOp(), UnrollVectorOverflowOp(), unrollVectorShift(), valueToCarryFlag(), vectorizeExtractedCast(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), visitORCommutative(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), llvm::SelectionDAGBuilder::visitSwitchCase(), widenAbs(), widenCtPop(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), widenSubVector(), widenVec(), WidenVector(), WidenVector(), widenVectorToPartType(), and WinDBZCheckDenominator().
getNode() [4/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 9218 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [5/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Definition at line 9226 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::BR_CC, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::ISD::DELETED_NODE, DL, E, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), getNode(), getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), getVTList(), llvm::MVT::Glue, llvm::MVT::i1, llvm::EVT::isVector(), llvm::LegalityPredicates::isVector(), N, NewSDValueDbgMsg(), llvm::ISD::SELECT_CC, and llvm::ArrayRef< T >::size().
getNode() [6/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2)
Definition at line 6134 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [7/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, const SDNodeFlags Flags)
Definition at line 6163 of file SelectionDAG.cpp.
References llvm::ISD::ABDS, llvm::ISD::ABDU, llvm::ISD::ADD, AddNodeIDNode(), llvm::ISD::AND, llvm::APInt::ashrInPlace(), assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::EVT::bitsLE(), llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, canonicalizeCommutativeBinop(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::DELETED_NODE, DL, llvm::numbers::e, E, llvm::ISD::EntryToken, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::APInt::extractBits(), llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FMUL, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT_SAT, llvm::ISD::FP_TO_UINT_SAT, llvm::ISD::FREM, llvm::ISD::FSUB, getAllOnesConstant(), getAnyExtOrTrunc(), llvm::APInt::getBitWidth(), getBuildVector(), getConstant(), llvm::SDNode::getConstantOperandAPInt(), getDataLayout(), getFPExtendOrRound(), llvm::SDValue::getNode(), getNode(), getNOT(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), getSExtOrTrunc(), llvm::EVT::getSizeInBits(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), getVectorIdxConstant(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorMinNumElements(), llvm::EVT::getVectorNumElements(), getVScale(), getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, i, llvm::MVT::i1, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ConstantSDNode::isAllOnes(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::TargetLoweringBase::isCommutativeBinOp(), llvm::isConstOrConstSplat(), llvm::EVT::isFixedLengthVector(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::LegalityPredicates::isVector(), llvm::ConstantSDNode::isZero(), llvm::Log2_32_Ceil(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, N, NewSDValueDbgMsg(), llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDSAT, llvm::ISD::SDIV, Shift, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, simplifyFPBinop(), simplifyShift(), llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SSUBSAT, llvm::ISD::SUB, std::swap(), llvm::ISD::TokenFactor, llvm::ISD::UADDSAT, llvm::ISD::UDIV, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UREM, llvm::ISD::USUBSAT, llvm::ISD::VSCALE, and llvm::ISD::XOR.
getNode() [8/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3)
Definition at line 6650 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [9/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, const SDNodeFlags Flags)
Definition at line 6658 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::ISD::DELETED_NODE, DL, E, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::FMA, FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), FoldSetCC(), llvm::APFloat::fusedMultiplyAdd(), llvm::get(), getBitWidth(), getConstantFP(), getDataLayout(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getUNDEF(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorMinNumElements(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::EVT::isFixedLengthVector(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm_unreachable, N, NewSDValueDbgMsg(), llvm::APFloatBase::rmNearestTiesToEven, llvm::ISD::SELECT, llvm::ISD::SETCC, simplifySelect(), llvm::NVPTX::PTXLdStInstCode::V2, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VECTOR_SPLICE, and llvm::ISD::VSELECT.
getNode() [10/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
Definition at line 6821 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [11/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
Definition at line 6827 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [12/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue Operand)
Definition at line 5200 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [13/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, EVT VT, SDValue Operand, const SDNodeFlags Flags)
Definition at line 5208 of file SelectionDAG.cpp.
References llvm::ISD::ABS, llvm::APInt::abs(), AddNodeIDNode(), llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::lltok::APFloat, assert(), llvm::MVT::bf16, llvm::ISD::BF16_TO_FP, llvm::APFloatBase::BFloat(), llvm::ISD::BITCAST, llvm::APFloat::bitcastToAPInt(), llvm::ISD::BITREVERSE, llvm::EVT::bitsGT(), llvm::EVT::bitsLE(), llvm::EVT::bitsLT(), llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::APInt::byteSwap(), llvm::APFloat::changeSign(), llvm::APFloat::clearSign(), llvm::ISD::CONCAT_VECTORS, llvm::APFloat::convert(), llvm::APFloat::convertFromAPInt(), llvm::APFloat::convertToInteger(), llvm::APInt::countLeadingZeros(), llvm::APInt::countPopulation(), llvm::APInt::countTrailingZeros(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::DELETED_NODE, DL, E, EVTToAPFloatSemantics(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FCEIL, llvm::ISD::FFLOOR, llvm::ISD::FNEG, FoldBUILD_VECTOR(), FoldConstantArithmetic(), FoldSTEP_VECTOR(), llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_BF16, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FREEZE, llvm::ISD::FTRUNC, llvm::APInt::getBitWidth(), getConstant(), getConstantFP(), llvm::SDValue::getConstantOperandAPInt(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), getNode(), getNOT(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorMinNumElements(), getVScale(), getVTList(), llvm::APInt::getZero(), llvm::APInt::getZExtValue(), llvm::MVT::Glue, llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm::tgtok::IntVal, llvm::EVT::isFloatingPoint(), isGuaranteedNotToBeUndefOrPoison(), llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::TargetLoweringBase::isSExtCheaperThanZExt(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm_unreachable, llvm::ISD::MERGE_VALUES, N, NewNodesMustHaveLegalTypes, NewSDValueDbgMsg(), llvm::APFloatBase::opInexact, llvm::APFloatBase::opInvalidOp, llvm::APFloatBase::opOK, llvm::APInt::reverseBits(), llvm::APFloatBase::rmNearestTiesToEven, llvm::APFloatBase::rmTowardNegative, llvm::APFloatBase::rmTowardPositive, llvm::APFloatBase::rmTowardZero, llvm::APFloat::roundToIntegral(), s, llvm::ISD::SCALAR_TO_VECTOR, llvm::APInt::sextOrTrunc(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::STEP_VECTOR, llvm::ISD::TargetConstant, llvm::ISD::TokenFactor, transferDbgValues(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::ISD::UNDEF, llvm::ISD::VECREDUCE_ADD, llvm::ISD::VECREDUCE_AND, llvm::ISD::VECREDUCE_OR, llvm::ISD::VECREDUCE_SMAX, llvm::ISD::VECREDUCE_SMIN, llvm::ISD::VECREDUCE_UMAX, llvm::ISD::VECREDUCE_UMIN, llvm::ISD::VECREDUCE_XOR, llvm::ISD::VSCALE, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, and llvm::APInt::zextOrTrunc().
getNode() [14/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList)
Definition at line 9472 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [15/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, ArrayRef< SDValue > Ops)
Definition at line 9343 of file SelectionDAG.cpp.
References DL, llvm::SelectionDAG::FlagInserter::getFlags(), and getNode().
getNode() [16/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Definition at line 9351 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::ISD::AND, assert(), llvm::EVT::bitsLT(), canonicalizeCommutativeBinop(), llvm::ISD::DELETED_NODE, DL, E, getConstant(), getNode(), llvm::EVT::getScalarSizeInBits(), getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::Glue, llvm::MVT::i1, llvm::isConstOrConstSplat(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::ConstantSDNode::isZero(), llvm::ISD::MERGE_VALUES, N, NewSDValueDbgMsg(), llvm::SDVTList::NumVTs, llvm::ISD::SADDO, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SMUL_LOHI, llvm::ISD::SRA_PARTS, llvm::ISD::SRL_PARTS, llvm::ISD::SSUBO, llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::UADDO, llvm::ISD::UMUL_LOHI, llvm::ISD::USUBO, and llvm::SDVTList::VTs.
getNode() [17/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N)
Definition at line 9477 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [18/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2)
Definition at line 9483 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [19/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3)
Definition at line 9489 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [20/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4)
Definition at line 9495 of file SelectionDAG.cpp.
References DL, and getNode().
getNode() [21/21]
SDValue SelectionDAG::getNode (unsigned Opcode, const SDLoc & DL, SDVTList VTList, SDValue N1, SDValue N2, SDValue N3, SDValue N4, SDValue N5)
Definition at line 9501 of file SelectionDAG.cpp.
References DL, and getNode().
getNodeIfExists() [1/2]
SDNode * SelectionDAG::getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops)
getNodeIfExists - Get the specified node if it's already available, or else return NULL.
Definition at line 10084 of file SelectionDAG.cpp.
References llvm::SelectionDAG::FlagInserter::getFlags(), and getNodeIfExists().
getNodeIfExists() [2/2]
SDNode * SelectionDAG::getNodeIfExists (unsigned Opcode, SDVTList VTList, ArrayRef< SDValue > Ops, const SDNodeFlags Flags)
Get the specified node if it's already available, or else return NULL.
Definition at line 10092 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::MVT::Glue, llvm::SDVTList::NumVTs, and llvm::SDVTList::VTs.
Referenced by combineSelect(), combineSetCC(), combineX86AddSub(), getNodeIfExists(), performDUPCombine(), PerformExtractFpToIntStores(), performFlagSettingCombine(), and tryToWidenSetCCOperands().
getNoMergeSiteInfo()
bool llvm::SelectionDAG::getNoMergeSiteInfo (const SDNode * Node) const inline
Return NoMerge info associated with Node.
Definition at line 2279 of file SelectionDAG.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), and I.
getNOT()
SDValue SelectionDAG::getNOT (const SDLoc & DL, SDValue Val, EVT VT)
Create a bitwise NOT operation as (XOR Val, -1).
getNOT - Create a bitwise NOT operation as (XOR Val, -1).
Definition at line 1496 of file SelectionDAG.cpp.
References DL, getAllOnesConstant(), getNode(), and llvm::ISD::XOR.
Referenced by combineMOVMSK(), combineSelect(), combineSelectOfTwoConstants(), combineSetCC(), combineSub(), combineVSelectWithAllOnesOrZeros(), combineXor(), EmitVectorComparison(), foldBoolSelectToLogic(), foldExtendedSignBitTest(), foldVSelectToSignBitSplatMask(), llvm::VECustomDAG::getConstantMask(), getNode(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerMSABitClear(), LowerVSETCC(), performBSPExpandForSVE(), performConcatVectorsCombine(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifySetCC().
getObjectPtrOffset() [1/2]
SDValue llvm::SelectionDAG::getObjectPtrOffset (const SDLoc & SL, SDValue Ptr, SDValue Offset) inline
Definition at line 1011 of file SelectionDAG.h.
References getMemBasePlusOffset(), llvm::Offset, and Ptr.
getObjectPtrOffset() [2/2]
SDValue llvm::SelectionDAG::getObjectPtrOffset (const SDLoc & SL, SDValue Ptr, TypeSize Offset) inline
Create an add instruction with appropriate flags when used for addressing some offset of an object.
i.e. if a load is split into multiple components, create an add nuw from the base pointer to the offset.
Definition at line 1005 of file SelectionDAG.h.
References getMemBasePlusOffset(), llvm::Offset, and Ptr.
Referenced by llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
getOpcode_EXTEND()
static unsigned llvm::SelectionDAG::getOpcode_EXTEND (unsigned Opcode) inline static
Convert *_EXTEND_VECTOR_INREG to *_EXTEND opcode.
Definition at line 904 of file SelectionDAG.h.
References llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm_unreachable, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by combineEXTEND_VECTOR_INREG(), and foldExtendVectorInregToExtendOfSubvector().
getOpcode_EXTEND_VECTOR_INREG()
static unsigned llvm::SelectionDAG::getOpcode_EXTEND_VECTOR_INREG (unsigned Opcode) inline static
Convert *_EXTEND to *_EXTEND_VECTOR_INREG opcode.
Definition at line 920 of file SelectionDAG.h.
References llvm::ISD::ANY_EXTEND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm_unreachable, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by combineEXTRACT_SUBVECTOR(), getEXTEND_VECTOR_INREG(), LowerAVXExtend(), and matchUnaryShuffle().
getORE()
OptimizationRemarkEmitter& llvm::SelectionDAG::getORE () const inline
Definition at line 482 of file SelectionDAG.h.
getPass()
const Pass* llvm::SelectionDAG::getPass () const inline
Definition at line 466 of file SelectionDAG.h.
Referenced by llvm::SITargetLowering::LowerFormalArguments(), and llvm::SITargetLowering::passSpecialInputs().
getPCSections()
MDNode* llvm::SelectionDAG::getPCSections (const SDNode * Node) const inline
Return PCSections associated with Node, or nullptr if none exists.
Definition at line 2269 of file SelectionDAG.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find().
getPseudoProbeNode()
SDValue SelectionDAG::getPseudoProbeNode (const SDLoc & Dl, SDValue Chain, uint64_t Guid, uint64_t Index, uint32_t Attr)
Creates a PseudoProbeSDNode with function GUID Guid and the index of the block Index it is probing, as well as the attributes attr of the probe.
Definition at line 7981 of file SelectionDAG.cpp.
References AddNodeIDNode(), Chain, E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getVTList(), N, NewSDValueDbgMsg(), llvm::MVT::Other, and llvm::ISD::PSEUDO_PROBE.
getPSI()
ProfileSummaryInfo* llvm::SelectionDAG::getPSI () const inline
Definition at line 483 of file SelectionDAG.h.
getPtrExtendInReg()
SDValue SelectionDAG::getPtrExtendInReg (SDValue Op, const SDLoc & DL, EVT VT)
Return the expression required to extend the Op as a pointer value assuming it was the smaller SrcTy value.
This may be either a zero extend or a sign extend.
Definition at line 1485 of file SelectionDAG.cpp.
References DL, and getZeroExtendInReg().
getPtrExtOrTrunc()
SDValue SelectionDAG::getPtrExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either truncating it or performing either zero or sign extension as appropriate extension for the pointer's semantics.
Definition at line 1479 of file SelectionDAG.cpp.
References DL, and getZExtOrTrunc().
Referenced by llvm::SelectionDAGBuilder::visitSwitchCase().
getReducedAlign()
Align SelectionDAG::getReducedAlign (EVT VT, bool UseABI)
In most cases this function returns the ABI alignment for a given type, except for illegal vector types where the alignment exceeds that of the stack.
In such cases we attempt to break the vector down to a legal type and return the ABI alignment for that instead.
Definition at line 2340 of file SelectionDAG.cpp.
References DL, getContext(), getDataLayout(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetFrameLowering::getStackAlign(), llvm::MachineFunction::getSubtarget(), llvm::EVT::getTypeForEVT(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), llvm::TargetLoweringBase::isTypeLegal(), and llvm::EVT::isVector().
getRegister()
SDValue SelectionDAG::getRegister (unsigned Reg, EVT VT)
Definition at line 2147 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), llvm::TargetLowering::isSDNodeSourceOfDivergence(), N, and llvm::ISD::Register.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), buildCallOperands(), createCMovFP(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), emitLockedStackOp(), EmitUnrolledSetTag(), llvm::MipsTargetLowering::getAddrGPRel(), getCopyFromReg(), getCopyToReg(), getDefaultVLOps(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::MipsTargetLowering::getGlobalReg(), llvm::MipsTargetLowering::getOpndList(), getPrefetchNode(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::LowerINTRINSIC_WO_CHAIN(), llvm::LanaiTargetLowering::LowerJumpTable(), LowerMemOpCallTo(), llvm::VETargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerSETCCCARRY(), llvm::VETargetLowering::lowerVASTART(), LowerVASTART(), lowerVECTOR_SHUFFLE(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::LoongArchDAGToDAGISel::SelectAddrConstant(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::PPCTargetLowering::SelectAddressRegRegOnly(), llvm::SelectionDAGISel::SelectCodeCommon(), selectConstantAddr(), llvm::PPCTargetLowering::SelectForceXFormMode(), selectImmSeq(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), llvm::RISCVDAGToDAGISel::selectShiftMask(), and splatPartsI64WithVL().
getRegisterMask()
SDValue SelectionDAG::getRegisterMask (const uint32_t * RegMask)
Definition at line 2162 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), N, llvm::ISD::RegisterMask, and llvm::MVT::Untyped.
Referenced by buildCallOperands(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::MipsTargetLowering::getOpndList(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), and llvm::VETargetLowering::lowerToTLSGeneralDynamicModel().
getRoot()
const SDValue& llvm::SelectionDAG::getRoot () const inline
Return the root tag of the SelectionDAG.
Definition at line 547 of file SelectionDAG.h.
Referenced by llvm::checkForCycles(), llvm::ScheduleDAGSDNodes::getCustomGraphFeatures(), Legalize(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::RISCVDAGToDAGISel::PostprocessISelDAG(), RemoveDeadNode(), RemoveDeadNodes(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), and llvm::DAGTypeLegalizer::run().
getScatterVP()
SDValue SelectionDAG::getScatterVP (SDVTList VTs, EVT VT, const SDLoc & dl, ArrayRef< SDValue > Ops, MachineMemOperand * MMO, ISD::MemIndexType IndexType)
Definition at line 8865 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGE(), N, NewSDValueDbgMsg(), and llvm::ArrayRef< T >::size().
Referenced by llvm::RISCVTargetLowering::PerformDAGCombine().
getSelect()
SDValue llvm::SelectionDAG::getSelect (const SDLoc & DL, EVT VT, SDValue Cond, SDValue LHS, SDValue RHS) inline
Helper function to make it easier to build Select's if you just have operands and don't want to check for vector.
Definition at line 1196 of file SelectionDAG.h.
References assert(), Cond, DL, getNode(), LHS, RHS, llvm::ISD::SELECT, and llvm::ISD::VSELECT.
Referenced by llvm::TargetLowering::BuildUDIV(), combineFMinNumFMaxNum(), combineLogicBlendIntoPBLENDV(), combineMaskedLoadConstantMask(), combineSelect(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), foldSelectWithIdentityConstant(), llvm::TargetLowering::getNegatedExpression(), LowerABD(), LowerADDSAT_SUBSAT(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), llvm::AMDGPUTargetLowering::LowerFRINT(), lowerINT_TO_FP_vXi64(), llvm::RISCVTargetLowering::LowerOperation(), LowerRotate(), LowerShift(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), lowerShuffleAsBlend(), LowerSIGN_EXTEND_Mask(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerZERO_EXTEND_Mask(), narrowExtractedVectorSelect(), performSelectCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), signExtendBitcastSrcVector(), tryFoldSelectIntoOp(), tryToFoldExtendOfConstant(), tryToFoldExtendSelectLoad(), and UnrollVectorOverflowOp().
getSelectCC()
SDValue llvm::SelectionDAG::getSelectCC (const SDLoc & DL, SDValue LHS, SDValue RHS, SDValue True, SDValue False, ISD::CondCode Cond) inline
Helper function to make it easier to build SelectCC's if you just have an ISD::CondCode instead of an SDValue.
Definition at line 1206 of file SelectionDAG.h.
References Cond, DL, getCondCode(), getNode(), llvm::SDValue::getValueType(), LHS, RHS, and llvm::ISD::SELECT_CC.
Referenced by createVariablePermute(), llvm::TargetLowering::expandMUL_LOHI(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), lowerFP_TO_INT_SAT(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::R600TargetLowering::PerformDAGCombine(), and performFP_TO_INT_SATCombine().
getSelectionDAGInfo()
const SelectionDAGTargetInfo& llvm::SelectionDAG::getSelectionDAGInfo () const inline
Definition at line 476 of file SelectionDAG.h.
getSetCC()
SDValue llvm::SelectionDAG::getSetCC (const SDLoc & DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Chain = SDValue(), bool IsSignaling = false) inline
Helper function to make it easier to build SetCC's if you just have an ISD::CondCode instead of an SDValue.
Definition at line 1167 of file SelectionDAG.h.
References assert(), Chain, Cond, DL, getCondCode(), getNode(), llvm::EVT::isVector(), LHS, llvm::MVT::Other, RHS, llvm::ISD::SETCC, llvm::ISD::SETCC_INVALID, llvm::ISD::STRICT_FSETCC, and llvm::ISD::STRICT_FSETCCS.
Referenced by llvm::TargetLowering::BuildUDIV(), combineAnd(), combineBitcast(), combineCmpOp(), combineExtractVectorElt(), combineExtSetcc(), combineFMinNumFMaxNum(), combineOr(), combinePredicateReduction(), combineSelect(), combineSetCC(), combineShiftAnd1ToBitTest(), combineSubOfBoolean(), combineToExtendBoolVectorInReg(), combineVectorSizedSetCCEquality(), combineVSelectWithAllOnesOrZeros(), convertIntLogicToFPLogic(), emitOrXorXorTree(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), llvm::TargetLowering::expandIS_FPCLASS(), FoldSetCC(), foldSetCCWithFunnelShift(), foldSetCCWithRotate(), foldVectorXorShiftIntoCmp(), foldXorTruncShiftIntoCmp(), llvm::VECustomDAG::getMaskBroadcast(), llvm::TargetLowering::getSqrtInputTest(), llvm::TargetLowering::LegalizeSetCCCondCode(), lower1BitShuffle(), LowerABD(), LowerADDSAT_SUBSAT(), lowerBUILD_VECTOR(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), LowerEXTEND_VECTOR_INREG(), llvm::AMDGPUTargetLowering::LowerFCEIL(), llvm::AMDGPUTargetLowering::LowerFFLOOR(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), lowerINT_TO_FP_vXi64(), LowerIntVSETCC_AVX512(), LowerMULH(), LowerMULO(), llvm::RISCVTargetLowering::LowerOperation(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), LowerShiftByScalarImmediate(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LanaiTargetLowering::LowerSRL_PARTS(), LowerTruncateVecI1(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), LowerUMULO_SMULO(), LowerVectorCTLZInRegLUT(), LowerVSETCC(), llvm::RISCVTargetLowering::PerformDAGCombine(), performOrXorChainCombine(), llvm::AMDGPUTargetLowering::performSelectCombine(), performSELECTCombine(), performSETCCCombine(), performSignExtendSetCCCombine(), performVSelectCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), llvm::TargetLowering::softenSetCCOperands(), tryDemorganOfBooleanCondition(), trySwapVSelectOperands(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getSetCCVP()
SDValue llvm::SelectionDAG::getSetCCVP (const SDLoc & DL, EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode Cond, SDValue Mask, SDValue EVL) inline
Helper function to make it easier to build VP_SETCCs if you just have an ISD::CondCode instead of an SDValue.
Definition at line 1184 of file SelectionDAG.h.
References assert(), Cond, DL, getCondCode(), getNode(), LHS, llvm::BitmaskEnumDetail::Mask(), RHS, and llvm::ISD::SETCC_INVALID.
Referenced by llvm::TargetLowering::LegalizeSetCCCondCode().
getSExtOrTrunc()
SDValue SelectionDAG::getSExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either sign-extending or truncating it.
Definition at line 1440 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), DL, getNode(), llvm::ISD::SIGN_EXTEND, and llvm::ISD::TRUNCATE.
Referenced by combineGatherScatter(), combineShiftToMULH(), combineShuffleOfScalars(), combineToExtendBoolVectorInReg(), createVPDPBUSD(), earlyExpandDIVFIX(), expandDivFix(), foldCONCAT_VECTORS(), llvm::VECustomDAG::getMaskBroadcast(), getNode(), LowerADDSUBSAT(), LowerBITCAST(), llvm::HexagonTargetLowering::LowerLoad(), LowerMULO(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerVSETCC(), PerformMinMaxFpToSatCombine(), llvm::AMDGPUTargetLowering::performMulCombine(), llvm::AMDGPUTargetLowering::performMulhsCombine(), llvm::AMDGPUTargetLowering::performMulLoHiCombine(), and selectUmullSmull().
getShiftAmountConstant()
SDValue SelectionDAG::getShiftAmountConstant (uint64_t Val, EVT VT, const SDLoc & DL, bool LegalTypes = true)
Definition at line 1665 of file SelectionDAG.cpp.
References assert(), DL, getConstant(), getDataLayout(), llvm::TargetLoweringBase::getShiftAmountTy(), and llvm::EVT::isInteger().
Referenced by llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), combineExtractWithShuffle(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandMUL_LOHI(), extractShiftForRotate(), getCopyToParts(), llvm::AMDGPUTargetLowering::loadInputValue(), LowerINTRINSIC_W_CHAIN(), llvm::SITargetLowering::passSpecialInputs(), and llvm::TargetLowering::scalarizeVectorLoad().
getShiftAmountOperand()
SDValue SelectionDAG::getShiftAmountOperand (EVT LHSTy, SDValue Op)
Return the specified value casted to the target's desired shift amount type.
getShiftAmountOperand - Return the specified value casted to the target's desired shift amount type.
Definition at line 2284 of file SelectionDAG.cpp.
References getDataLayout(), llvm::TargetLoweringBase::getShiftAmountTy(), getZExtOrTrunc(), and llvm::EVT::isVector().
Referenced by UnrollVectorOp().
getSplat()
SDValue llvm::SelectionDAG::getSplat (EVT VT, const SDLoc & DL, SDValue Op) inline
Returns a node representing a splat of one value into all lanes of the provided vector type.
This is a utility which returns either a BUILD_VECTOR or SPLAT_VECTOR depending on the scalability of the desired vector type.
Definition at line 874 of file SelectionDAG.h.
References assert(), DL, getSplatBuildVector(), getSplatVector(), llvm::EVT::isScalableVector(), and llvm::EVT::isVector().
Referenced by getConstant(), getConstantFP(), llvm::SelectionDAGBuilder::getValueImpl(), and scalarizeBinOpOfSplats().
getSplatBuildVector()
SDValue llvm::SelectionDAG::getSplatBuildVector (EVT VT, const SDLoc & DL, SDValue Op) inline
Return a splat ISD::BUILD_VECTOR node, consisting of Op splatted to all elements.
VT must be a vector type. Op's type must be the same as (or, for integers, a type wider than) VT's element type.
Definition at line 841 of file SelectionDAG.h.
References assert(), llvm::EVT::bitsLE(), llvm::ISD::BUILD_VECTOR, DL, getNode(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isInteger(), and llvm::ISD::UNDEF.
Referenced by combineGatherScatter(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), getMemsetValue(), getSplat(), getVectorShuffle(), and lowerBUILD_VECTOR().
getSplatSourceVector()
SDValue SelectionDAG::getSplatSourceVector (SDValue V, int & SplatIndex)
If V is a splatted value, return the source vector and its splat index.
Definition at line 2811 of file SelectionDAG.cpp.
References assert(), llvm::countTrailingOnes(), llvm::APInt::getAllOnes(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), isSplatValue(), llvm::APInt::isSubsetOf(), llvm::peekThroughExtractSubvectors(), llvm::ISD::SPLAT_VECTOR, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by getSplatValue(), LowerFunnelShift(), LowerRotate(), LowerShiftByScalarVariable(), and scalarizeBinOpOfSplats().
getSplatValue()
SDValue SelectionDAG::getSplatValue (SDValue V, bool LegalTypes = false)
If V is a splat vector, return its scalar source operand by extracting that element from the source vector.
If LegalTypes is true, this method may only return a legally-typed splat value. If it cannot legalize the splatted value it will return SDValue().
Definition at line 2863 of file SelectionDAG.cpp.
References llvm::EVT::bitsLT(), llvm::ISD::EXTRACT_VECTOR_ELT, getContext(), getNode(), llvm::EVT::getScalarType(), getSplatSourceVector(), llvm::TargetLoweringBase::getTypeToTransformTo(), getVectorIdxConstant(), llvm::EVT::isInteger(), and llvm::TargetLoweringBase::isTypeLegal().
Referenced by findMoreOptimalIndexType(), foldIndexIntoBase(), lowerVECTOR_SHUFFLE(), PerformVSetCCToVCTPCombine(), and refineUniformBase().
getSplatVector()
SDValue llvm::SelectionDAG::getSplatVector (EVT VT, const SDLoc & DL, SDValue Op) inline
Definition at line 858 of file SelectionDAG.h.
References assert(), llvm::EVT::bitsLE(), DL, getNode(), llvm::EVT::getVectorElementType(), llvm::EVT::isInteger(), llvm::ISD::SPLAT_VECTOR, and llvm::ISD::UNDEF.
Referenced by BuildExactSDIV(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), FoldConstantArithmetic(), and getSplat().
GetSplitDestVTs()
std::pair< EVT, EVT > SelectionDAG::GetSplitDestVTs (const EVT & VT) const
Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
GetSplitDestVTs - Compute the VTs needed for the low/hi parts of a type which is split (or expanded) into two not necessarily identical pieces.
Definition at line 11621 of file SelectionDAG.cpp.
References getContext(), llvm::EVT::getHalfNumVectorElementsVT(), llvm::TargetLoweringBase::getTypeToTransformTo(), and llvm::EVT::isVector().
Referenced by LowerCVTPS2PH(), LowerMULO(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceReductionResults(), splitIntVSETCC(), llvm::SITargetLowering::splitTernaryVectorOp(), SplitVector(), and splitVectorOp().
getSrcValue()
SDValue SelectionDAG::getSrcValue (const Value * v)
Construct a node to track a Value* through the backend.
Definition at line 2220 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), N, llvm::MVT::Other, and llvm::ISD::SRCVALUE.
Referenced by llvm::SelectionDAGBuilder::LowerAsSTATEPOINT().
getStackArgumentTokenFactor()
SDValue SelectionDAG::getStackArgumentTokenFactor (SDValue Chain)
Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
getStackArgumentTokenFactor - Compute a TokenFactor to force all the incoming stack arguments to be loaded from the stack.
This is used in tail call lowering to protect stack arguments from being clobbered.
Definition at line 6836 of file SelectionDAG.cpp.
References Chain, getEntryNode(), getNode(), llvm::MVT::Other, llvm::ISD::TokenFactor, and uses.
getStepVector() [1/2]
SDValue SelectionDAG::getStepVector (const SDLoc & DL, EVT ResVT)
Returns a vector of type ResVT whose elements contain the linear sequence <0, 1, 2, 3, ...>
Definition at line 1938 of file SelectionDAG.cpp.
References DL, llvm::EVT::getScalarSizeInBits(), and getStepVector().
getStepVector() [2/2]
SDValue SelectionDAG::getStepVector (const SDLoc & DL, EVT ResVT, APInt StepVal)
Returns a vector of type ResVT whose elements contain the linear sequence <0, Step, Step * 2, Step * 3, ...>
Definition at line 1943 of file SelectionDAG.cpp.
References assert(), DL, llvm::APInt::getBitWidth(), getBuildVector(), getConstant(), getNode(), llvm::EVT::getScalarSizeInBits(), getTargetConstant(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), i, llvm::EVT::isScalableVector(), llvm::ISD::STEP_VECTOR, and uint64_t.
Referenced by findMoreOptimalIndexType(), FoldConstantArithmetic(), getStepVector(), and LowerSVEIntrinsicIndex().
getStore() [1/4]
SDValue SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachineMemOperand * MMO)
Definition at line 8189 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), Chain, dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getUNDEF(), llvm::SDValue::getValueType(), getVTList(), N, NewSDValueDbgMsg(), llvm::MVT::Other, Ptr, llvm::ISD::STORE, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getStore() [2/4]
SDValue SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, Align Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Helper function to build ISD::STORE nodes.
This function will set the MOStore flag on MMOFlags, but you can set it if you want. The MOLoad and MOInvariant flags must not be set.
Definition at line 8168 of file SelectionDAG.cpp.
References AAInfo, Alignment, assert(), Chain, dl, getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemoryLocation::getSizeOrUnknown(), llvm::EVT::getStoreSize(), llvm::SDValue::getValueType(), InferPointerInfo(), MMOFlags, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MVT::Other, Ptr, PtrInfo, and uint64_t.
Referenced by combineStore(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), foldTruncStoreOfExt(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getStore(), getTruncStore(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerEH_RETURN(), LowerF128Store(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerFP_TO_SINT_STORE(), LowerMemOpCallTo(), lowerMSAStoreIntr(), LowerSTORE(), LowerStore(), lowerStoreF128(), lowerStoreI1(), LowerTruncateVectorStore(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), memsetStore(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::AMDGPUTargetLowering::performStoreCombine(), PerformSTORECombine(), PerformTruncatingStoreCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), reduceMaskedStoreToScalarStore(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), splitStores(), splitStoreSplat(), splitVectorStore(), llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic(), llvm::AMDGPUTargetLowering::storeStackInputValue(), and StoreTailCallArgumentsToStackSlot().
getStore() [3/4]
SDValue llvm::SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
Definition at line 1376 of file SelectionDAG.h.
References AAInfo, Alignment, Chain, dl, getEVTAlign(), getStore(), llvm::SDValue::getValueType(), MMOFlags, Ptr, and PtrInfo.
getStore() [4/4]
SDValue llvm::SelectionDAG::getStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, unsigned Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
FIXME: Remove once transition to Align is over.
Definition at line 1387 of file SelectionDAG.h.
References AAInfo, Alignment, Chain, dl, getStore(), MMOFlags, Ptr, and PtrInfo.
getStoreVP()
SDValue SelectionDAG::getStoreVP (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, SDValue Offset, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, bool IsTruncating = false, bool IsCompressing = false)
Definition at line 8433 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), Chain, dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getVTList(), Indexed, llvm::BitmaskEnumDetail::Mask(), N, NewSDValueDbgMsg(), llvm::Offset, llvm::MVT::Other, Ptr, and llvm::ISD::UNINDEXED.
Referenced by getTruncStoreVP(), and llvm::RISCVTargetLowering::PerformDAGCombine().
getStrictFPExtendOrRound()
std::pair< SDValue, SDValue > SelectionDAG::getStrictFPExtendOrRound (SDValue Op, SDValue Chain, const SDLoc & DL, EVT VT)
Convert Op, which must be a STRICT operation of float type, to the float type VT, by either extending or rounding (by truncation).
Definition at line 1421 of file SelectionDAG.cpp.
References assert(), llvm::EVT::bitsEq(), llvm::EVT::bitsGT(), Chain, DL, getIntPtrConstant(), llvm::SDValue::getNode(), getNode(), llvm::MVT::Other, llvm::ISD::STRICT_FP_EXTEND, and llvm::ISD::STRICT_FP_ROUND.
Referenced by LowerUINT_TO_FP_i32().
getStridedLoadVP() [1/5]
SDValue SelectionDAG::getStridedLoadVP (EVT VT, const SDLoc & DL, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 8637 of file SelectionDAG.cpp.
References Chain, DL, getStridedLoadVP(), getUNDEF(), llvm::BitmaskEnumDetail::Mask(), llvm::ISD::NON_EXTLOAD, Ptr, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getStridedLoadVP() [2/5]
SDValue SelectionDAG::getStridedLoadVP (EVT VT, const SDLoc & DL, SDValue Chain, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, MaybeAlign Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, const MDNode * Ranges = nullptr, bool IsExpanding = false)
Definition at line 8626 of file SelectionDAG.cpp.
References AAInfo, Alignment, Chain, DL, getStridedLoadVP(), getUNDEF(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, llvm::ISD::NON_EXTLOAD, Ptr, PtrInfo, Ranges, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getStridedLoadVP() [3/5]
SDValue SelectionDAG::getStridedLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & DL, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, bool IsExpanding = false)
Definition at line 8592 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), Chain, DL, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getVTList(), Indexed, llvm::BitmaskEnumDetail::Mask(), N, NewSDValueDbgMsg(), llvm::Offset, llvm::MVT::Other, Ptr, and llvm::ISD::UNINDEXED.
getStridedLoadVP() [4/5]
SDValue SelectionDAG::getStridedLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & DL, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, const MDNode * Ranges = nullptr, bool IsExpanding = false)
Definition at line 8569 of file SelectionDAG.cpp.
References AAInfo, Alignment, assert(), Chain, DL, getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), InferPointerInfo(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::Offset, llvm::MVT::Other, Ptr, PtrInfo, Ranges, uint64_t, and llvm::MemoryLocation::UnknownSize.
Referenced by getExtStridedLoadVP(), getIndexedStridedLoadVP(), and getStridedLoadVP().
getStridedLoadVP() [5/5]
SDValue llvm::SelectionDAG::getStridedLoadVP (ISD::MemIndexedMode AM, ISD::LoadExtType ExtType, EVT VT, const SDLoc & DL, SDValue Chain, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT MemVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr, bool IsExpanding = false) inline
Definition at line 1491 of file SelectionDAG.h.
References AAInfo, Alignment, Chain, DL, getEVTAlign(), getStridedLoadVP(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, llvm::Offset, Ptr, PtrInfo, and Ranges.
getStridedStoreVP()
SDValue SelectionDAG::getStridedStoreVP (SDValue Chain, const SDLoc & DL, SDValue Val, SDValue Ptr, SDValue Offset, SDValue Stride, SDValue Mask, SDValue EVL, EVT MemVT, MachineMemOperand * MMO, ISD::MemIndexedMode AM, bool IsTruncating = false, bool IsCompressing = false)
Definition at line 8685 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), Chain, DL, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), getVTList(), Indexed, llvm::BitmaskEnumDetail::Mask(), N, NewSDValueDbgMsg(), llvm::Offset, llvm::MVT::Other, Ptr, and llvm::ISD::UNINDEXED.
Referenced by getTruncStridedStoreVP().
getSubtarget() [1/2]
const TargetSubtargetInfo& llvm::SelectionDAG::getSubtarget () const inline
Definition at line 470 of file SelectionDAG.h.
References llvm::MachineFunction::getSubtarget().
Referenced by combineCommutableSHUFP(), emitComparison(), emitConditionalComparison(), emitStrictFPComparison(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), findMoreOptimalIndexType(), getPredicateForFixedLengthVector(), init(), isAllActivePredicate(), llvm::PPC::isVPKUDUMShuffleMask(), lowerMSASplatZExt(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), optimizeWhile(), patchMatchingInput(), performExtractVectorEltCombine(), recoverFramePointer(), AMDGPUDAGToDAGISel::SelectBuildVector(), truncateVecElts(), tryAdvSIMDModImm16(), tryAdvSIMDModImm32(), and tryCombineToBSL().
getSubtarget() [2/2]
template<typename STC > const STC& llvm::SelectionDAG::getSubtarget () const inline
Definition at line 471 of file SelectionDAG.h.
References llvm::MachineFunction::getSubtarget().
getSymbolFunctionGlobalAddress()
SDValue SelectionDAG::getSymbolFunctionGlobalAddress (SDValue Op, Function ** TargetFunction = nullptr)
Returs an GlobalAddress of the function from the current module with name matching the given ExternalSymbol.
Additionally can provide the matched function. Panics the function doesn't exists.
Definition at line 10890 of file SelectionDAG.cpp.
References assert(), llvm::GlobalValue::getAddressSpace(), getDataLayout(), llvm::Module::getFunction(), llvm::MachineFunction::getFunction(), getGlobalAddress(), llvm::GlobalValue::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::report_fatal_error(), and llvm::raw_string_ostream::str().
Referenced by llvm::NVPTXTargetLowering::LowerCall().
getTarget()
const TargetMachine& llvm::SelectionDAG::getTarget () const inline
Definition at line 469 of file SelectionDAG.h.
References TM.
Referenced by combineFaddCFmul(), combineFMinFMax(), combineFMinNumFMaxNum(), combineSelect(), llvm::ScheduleDAGSDNodes::EmitSchedule(), foldFPToIntToFP(), llvm::TargetLowering::getNegatedExpression(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), isFMAddSubOrFMSubAdd(), isKnownNeverNaN(), isLegalToCombineMinNumMaxNum(), llvm::VETargetLowering::LowerCall(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), and transformCallee().
getTargetBlockAddress()
SDValue llvm::SelectionDAG::getTargetBlockAddress (const BlockAddress * BA, EVT VT, int64_t Offset = 0, unsigned TargetFlags = 0) inline
Definition at line 764 of file SelectionDAG.h.
References getBlockAddress(), and llvm::Offset.
Referenced by getTargetNode(), llvm::RISCVTargetLowering::LowerAsmOperandForConstraint(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::MSP430TargetLowering::LowerBlockAddress(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetConstant() [1/3]
SDValue llvm::SelectionDAG::getTargetConstant (const APInt & Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 675 of file SelectionDAG.h.
References DL, and getConstant().
getTargetConstant() [2/3]
SDValue llvm::SelectionDAG::getTargetConstant (const ConstantInt & Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 679 of file SelectionDAG.h.
References DL, and getConstant().
getTargetConstant() [3/3]
SDValue llvm::SelectionDAG::getTargetConstant (uint64_t Val, const SDLoc & DL, EVT VT, bool isOpaque = false) inline
Definition at line 671 of file SelectionDAG.h.
References DL, and getConstant().
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), buildPCRelGlobalAddress(), llvm::SITargetLowering::buildRSRC(), buildSMovImm32(), canonicalizeBitSelect(), combineADC(), combineAddOrSubToADCOrSBB(), combineAndMaskToShift(), combineBitcastToBoolVector(), combineBrCond(), combineCMov(), combineCommutableSHUFP(), combineCompareEqual(), combineConcatVectorOps(), combineFP16_TO_FP(), combineFP_ROUND(), combineTargetShuffle(), llvm::VETargetLowering::combineTRUNCATE(), combineVectorShiftImm(), combineX86GatherScatter(), combineX86ShuffleChain(), createGPRPairNode(), createMMXBuildVector(), createTuple(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), EmitAVX512Test(), emitLockedStackOp(), emitSETCC(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), expandFP_TO_UINT_SSE(), ExtractBitFromMaskVector(), llvm::PPC::get_VSPLTI_elt(), getAL(), getAVX2GatherNode(), getCopyFromParts(), getGatherNode(), getGeneralPermuteNode(), getIntOperandsFromRegisterString(), getLeftShift(), getPack(), getPermuteNode(), getPrefetchNode(), getPTrue(), getScatterNode(), getSETCC(), getSPDenormModeValue(), getStepVector(), getTargetExtractSubreg(), getTargetInsertSubreg(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getUniformBase(), getV4X86ShuffleImm8ForMask(), getVAArg(), getVShift(), getVSlidedown(), getVSlideup(), getZeroVector(), insert1BitVector(), InvertCarryFlag(), isVMOVModifiedImm(), isWorthFoldingIntoOrrWithShift(), llvm::HexagonDAGToDAGISel::LoadInstrForLoadIntrinsic(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), LowerABS(), llvm::SparcTargetLowering::LowerAsmOperandForConstraint(), llvm::LanaiTargetLowering::LowerAsmOperandForConstraint(), llvm::AVRTargetLowering::LowerAsmOperandForConstraint(), llvm::M68kTargetLowering::LowerAsmOperandForConstraint(), llvm::SITargetLowering::LowerAsmOperandForConstraint(), llvm::RISCVTargetLowering::LowerAsmOperandForConstraint(), llvm::SystemZTargetLowering::LowerAsmOperandForConstraint(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::PPCTargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::VETargetLowering::lowerATOMIC_FENCE(), LowerBITREVERSE(), llvm::VETargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), LowerCMP_SWAP(), LowerCONCAT_VECTORSvXi1(), LowerCTLZ(), LowerCTTZ(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerF128Load(), LowerF128Store(), llvm::VETargetLowering::LowerFormalArguments(), LowerFP_TO_FP16(), lowerFP_TO_INT_SAT(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), LowerFunnelShift(), LowerINTRINSIC_W_CHAIN(), lowerLoadF128(), lowerLoadI1(), LowerMLOAD(), LowerPREFETCH(), llvm::VETargetLowering::LowerReturn(), LowerRotate(), LowerShift(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsVALIGN(), lowerShuffleAsVTRUNC(), lowerShufflePairAsUNPCKAndPermute(), lowerShuffleWithSHUFPD(), lowerShuffleWithSSE4A(), LowerSTORE(), lowerStoreF128(), lowerStoreI1(), lowerUINT_TO_FP_vXi32(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2X128Shuffle(), lowerV4F64Shuffle(), lowerV4X128Shuffle(), lowerV8F64Shuffle(), lowerV8I16Shuffle(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VSHF(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorIntrinsicScalars(), LowerVSETCC(), MatchVectorAllZeroTest(), narrowIfNeeded(), optimizeLogicalImm(), parseTexFail(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performFP_TO_INT_SATCombine(), performFP_TO_INTCombine(), PerformHWLoopCombine(), performIntrinsicCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), PromoteMVEPredVector(), llvm::RISCVTargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), AMDGPUDAGToDAGISel::Select(), llvm::LoongArchDAGToDAGISel::SelectAddrConstant(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::RISCVDAGToDAGISel::SelectAddrFrameIndex(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), llvm::HexagonDAGToDAGISel::SelectAnyImmediate(), llvm::HexagonDAGToDAGISel::SelectAnyInt(), AMDGPUDAGToDAGISel::SelectBuildVector(), llvm::SelectionDAGISel::SelectCodeCommon(), selectConstantAddr(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectD2P(), llvm::RISCVDAGToDAGISel::SelectFrameAddrRegImm(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), selectI64Imm(), selectI64ImmDirect(), selectI64ImmDirectPrefix(), selectImmSeq(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::LoongArchDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::NVPTXDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::HexagonDAGToDAGISel::SelectInlineAsmMemoryOperand(), llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::RISCVDAGToDAGISel::selectRVVSimm5(), llvm::RISCVDAGToDAGISel::selectShiftMask(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::RISCVDAGToDAGISel::selectSHXADD_UWOp(), llvm::RISCVDAGToDAGISel::selectSHXADDOp(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::RISCVDAGToDAGISel::selectVLOp(), selectVSplatSimmHelper(), llvm::RISCVDAGToDAGISel::selectVSplatUimm5(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), tryOrrWithShift(), tryToConvertShuffleOfTbl2ToTbl4(), Widen(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getTargetConstantFP() [1/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (const APFloat & Val, const SDLoc & DL, EVT VT) inline
Definition at line 706 of file SelectionDAG.h.
References DL, and getConstantFP().
getTargetConstantFP() [2/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (const ConstantFP & Val, const SDLoc & DL, EVT VT) inline
Definition at line 709 of file SelectionDAG.h.
References DL, and getConstantFP().
getTargetConstantFP() [3/3]
SDValue llvm::SelectionDAG::getTargetConstantFP (double Val, const SDLoc & DL, EVT VT) inline
Definition at line 703 of file SelectionDAG.h.
References DL, and getConstantFP().
Referenced by llvm::SelectionDAGISel::SelectCodeCommon().
getTargetConstantPool() [1/2]
SDValue llvm::SelectionDAG::getTargetConstantPool (const Constant * C, EVT VT, MaybeAlign Align = std::nullopt, int Offset = 0, unsigned TargetFlags = 0) inline
Definition at line 733 of file SelectionDAG.h.
References getConstantPool(), and llvm::Offset.
Referenced by getTargetNode(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::HexagonTargetLowering::LowerConstantPool(), promoteToConstantPool(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetConstantPool() [2/2]
SDValue llvm::SelectionDAG::getTargetConstantPool (MachineConstantPoolValue * C, EVT VT, MaybeAlign Align = std::nullopt, int Offset = 0, unsigned TargetFlags = 0) inline
Definition at line 741 of file SelectionDAG.h.
References getConstantPool(), and llvm::Offset.
getTargetExternalSymbol()
SDValue SelectionDAG::getTargetExternalSymbol (const char * Sym, EVT VT, unsigned TargetFlags = 0)
Definition at line 1915 of file SelectionDAG.cpp.
References N.
Referenced by getTagSymNode(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::MSP430TargetLowering::LowerExternalSymbol(), llvm::HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN(), transformCallee(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetExtractSubreg()
SDValue SelectionDAG::getTargetExtractSubreg (int SRIdx, const SDLoc & DL, EVT VT, SDValue Operand)
A convenience function for creating TargetInstrInfo::EXTRACT_SUBREG nodes.
getTargetExtractSubreg - A convenience function for creating TargetOpcode::EXTRACT_SUBREG nodes.
Definition at line 10064 of file SelectionDAG.cpp.
References DL, getMachineNode(), getTargetConstant(), and llvm::MVT::i32.
Referenced by llvm::SITargetLowering::buildRSRC(), LowerF64Op(), LowerFNEGorFABS(), lowerGR128Binary(), lowerGR128ToI128(), llvm::SystemZTargetLowering::LowerOperationWrapper(), NarrowVector(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), llvm::HexagonDAGToDAGISel::SelectExtractSubvector(), llvm::HvxSelector::selectExtractSubvector(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), and llvm::HexagonDAGToDAGISel::SelectVAlign().
getTargetFrameIndex()
SDValue llvm::SelectionDAG::getTargetFrameIndex (int FI, EVT VT) inline
Definition at line 722 of file SelectionDAG.h.
References getFrameIndex().
Referenced by addStackMapLiveVars(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), EmitUnrolledSetTag(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), llvm::RISCVDAGToDAGISel::SelectAddrFrameIndex(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), llvm::LoongArchDAGToDAGISel::SelectBaseAddr(), llvm::RISCVDAGToDAGISel::SelectFrameAddrRegImm(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), and SelectSAddrFI().
getTargetGlobalAddress()
SDValue llvm::SelectionDAG::getTargetGlobalAddress (const GlobalValue * GV, const SDLoc & DL, EVT VT, int64_t offset = 0, unsigned TargetFlags = 0) inline
Definition at line 717 of file SelectionDAG.h.
References DL, and getGlobalAddress().
Referenced by buildPCRelGlobalAddress(), combineADDToMAT_PCREL_ADDR(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getTargetNode(), GetTLSADDR(), llvm::RISCVTargetLowering::LowerAsmOperandForConstraint(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::LanaiTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), LowerToTLSExecModel(), llvm::HexagonTargetLowering::LowerToTLSGeneralDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSInitialExecModel(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerToTLSLocalExecModel(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), llvm::HexagonDAGToDAGISel::SelectGlobalAddress(), transformCallee(), llvm::SparcTargetLowering::withTargetFlags(), and llvm::VETargetLowering::withTargetFlags().
getTargetIndex()
SDValue SelectionDAG::getTargetIndex (int Index, EVT VT, int64_t Offset = 0, unsigned TargetFlags = 0)
Definition at line 1853 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, getVTList(), N, llvm::Offset, and llvm::ISD::TargetIndex.
getTargetInsertSubreg()
SDValue SelectionDAG::getTargetInsertSubreg (int SRIdx, const SDLoc & DL, EVT VT, SDValue Operand, SDValue Subreg)
A convenience function for creating TargetInstrInfo::INSERT_SUBREG nodes.
getTargetInsertSubreg - A convenience function for creating TargetOpcode::INSERT_SUBREG nodes.
Definition at line 10074 of file SelectionDAG.cpp.
References DL, getMachineNode(), getTargetConstant(), and llvm::MVT::i32.
Referenced by LowerF64Op(), and LowerFNEGorFABS().
getTargetJumpTable()
SDValue llvm::SelectionDAG::getTargetJumpTable (int JTI, EVT VT, unsigned TargetFlags = 0) inline
Definition at line 727 of file SelectionDAG.h.
References getJumpTable().
Referenced by llvm::HexagonTargetLowering::getPICJumpTableRelocBase(), getTargetNode(), llvm::LanaiTargetLowering::LowerJumpTable(), llvm::MSP430TargetLowering::LowerJumpTable(), llvm::HexagonTargetLowering::LowerJumpTable(), and llvm::VETargetLowering::withTargetFlags().
getTargetLoweringInfo()
const TargetLowering& llvm::SelectionDAG::getTargetLoweringInfo () const inline
Definition at line 474 of file SelectionDAG.h.
Referenced by AddCombineBUILD_VECTORToVPADDL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), llvm::RegsForValue::AddInlineAsmOperands(), buildFromShuffleMostly(), llvm::TargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildSREMPow2(), canonicalizeShuffleWithBinOps(), combineAdd(), combineAddOrSubToADCOrSBB(), combineAnd(), combineAndnp(), combineBEXTR(), combineBitcast(), combineBitcastToBoolVector(), combineBT(), combineCMP(), combineCONCAT_VECTORS(), combineConcatVectorOfCasts(), combineConcatVectorOfConcatVectors(), combineConcatVectorOfExtracts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineCVTPH2PS(), combineEXTEND_VECTOR_INREG(), combineEXTRACT_SUBVECTOR(), combineExtractVectorElt(), combineFMA(), combineFMADDSUB(), combineFMinNumFMaxNum(), combineFneg(), combineGatherScatter(), combineKSHIFT(), combineLoad(), combineLogicBlendIntoConditionalNegate(), combineMaskedLoad(), combineMaskedStore(), combineMOVMSK(), combineOr(), combinePDEP(), combinePMULDQ(), combinePredicateReduction(), combinePTESTCC(), combineScalarAndWithMaskSetcc(), combineSelect(), combineSelectOfTwoConstants(), combineSetCC(), combineShiftAnd1ToBitTest(), combineShuffle(), combineShuffleToFMAddSub(), combineStore(), combineTargetShuffle(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineVectorInsert(), combineVectorShiftImm(), combineVectorShiftVar(), combineVEXTRACT_STORE(), combineVPMADD(), combineVSelectToBLENDV(), combineVSelectWithAllOnesOrZeros(), combineVTRUNC(), combineX86GatherScatter(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), combineXor(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), createMMXBuildVector(), EltsFromConsecutiveLoads(), ExpandPowI(), foldAndOrOfSETCC(), foldCONCAT_VECTORS(), foldExtendedSignBitTest(), foldShuffleOfConcatUndefs(), foldVSelectToSignBitSplatMask(), foldXorTruncShiftIntoCmp(), formSplatFromShuffles(), getAddressForMemoryInput(), getAVX2GatherNode(), getAVX512Node(), getAVX512TruncNode(), getBT(), getConstVector(), getContainerForFixedLengthVector(), getCopyFromParts(), getCopyFromPartsVector(), llvm::SelectionDAGBuilder::getCopyFromRegs(), llvm::RegsForValue::getCopyFromRegs(), getCopyToParts(), getCopyToPartsVector(), llvm::RegsForValue::getCopyToRegs(), llvm::SelectionDAGBuilder::getFrameIndexTy(), getGatherNode(), getKnownUndefForVectorBinop(), getLifetimeNode(), getLimitedPrecisionExp2(), getLoadStackGuard(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemset(), getMemsetStores(), getMemsetValue(), getPredicateForFixedLengthVector(), getPredicateForScalableVector(), getPrefetchNode(), getPTest(), getRegistersForValue(), getScatterNode(), getSVEPredicateBitCast(), getTagSymNode(), getUniformBase(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::SelectionDAGBuilder::init(), isAddSubOrSubAdd(), isBLACompatibleAddress(), isConsecutiveLSLoc(), isKnownToBeAPowerOfTwo(), isPackedVectorType(), llvm::TargetLowering::LegalizeSetCCCondCode(), LowerABD(), LowerADDSAT_SUBSAT(), LowerADDSUBCARRY(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerBuildVectorAsBroadcast(), lowerBuildVectorToBitOp(), llvm::SelectionDAGBuilder::LowerCallTo(), LowerCTPOP(), llvm::SelectionDAGBuilder::LowerDeoptimizeCall(), LowerFABSorFNEG(), LowerFCOPYSIGN(), llvm::SelectionDAGBuilder::lowerInvokable(), LowerMemOpCallTo(), LowerMSCATTER(), LowerMULO(), LowerShiftParts(), lowerShuffleAsElementInsertion(), lowerShuffleAsShift(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), LowerVASTART(), lowerVECTOR_SHUFFLE(), LowerVectorAllZero(), LowerVSETCC(), LowerXALUO(), matchLSNode(), matchRotateSub(), narrowExtractedVectorBinOp(), narrowExtractedVectorLoad(), narrowInsertExtractVectorBinOp(), llvm::ScheduleDAGSDNodes::newSUnit(), patchMatchingInput(), PerformABSCombine(), PerformADDCombineWithOperands(), performAddCSelIntoCSinc(), PerformANDCombine(), performANDCombine(), PerformARMBUILD_VECTORCombine(), performBuildVectorCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), PerformExtendCombine(), PerformExtractEltToVMOVRRD(), performFP_TO_INT_SATCombine(), performFP_TO_INTCombine(), performFpToIntCombine(), performGatherLoadCombine(), PerformInsertSubvectorCombine(), performInsertSubvectorCombine(), PerformLOADCombine(), PerformMinMaxFpToSatCombine(), PerformORCombine(), performORCombine(), PerformPREDICATE_CASTCombine(), performScatterStoreCombine(), performSelectCombine(), PerformShiftCombine(), PerformSTORECombine(), performTBISimplification(), PerformTruncatingStoreCombine(), PerformUMinFpToSatCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), PerformVMOVhrCombine(), PerformVMOVNCombine(), PerformVQMOVNCombine(), PerformVSetCCToVCTPCombine(), performXORCombine(), PerformXORCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), PromoteMaskArithmetic(), recoverFramePointer(), reduceBuildVecToShuffleWithZero(), refineIndexType(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), scalarizeExtractedBinop(), llvm::TargetLowering::CallLoweringInfo::setLibCallee(), llvm::TargetLowering::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), simplifyMul24(), llvm::TargetLowering::SimplifySetCC(), transformCallee(), tryWidenMaskForShuffle(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), widenAbs(), and widenCtPop().
getTokenFactor()
SDValue SelectionDAG::getTokenFactor (const SDLoc & DL, SmallVectorImpl< SDValue > & Vals)
Creates a new TokenFactor containing Vals.
If Vals contains 64k values or more, move values into new TokenFactors in 64k-1 blocks, until the final TokenFactor has less than 64k operands.
Definition at line 12145 of file SelectionDAG.cpp.
References DL, llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorImpl< T >::erase(), llvm::SDNode::getMaxNumOperands(), getNode(), llvm::MVT::Other, llvm::ArrayRef< T >::slice(), and llvm::ISD::TokenFactor.
Referenced by llvm::SITargetLowering::LowerCall().
getTruncStore() [1/4]
SDValue SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, EVT SVT, MachineMemOperand * MMO)
Definition at line 8241 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), Chain, dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), getStore(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), llvm::EVT::isInteger(), llvm::EVT::isVector(), N, NewSDValueDbgMsg(), llvm::MVT::Other, Ptr, llvm::ISD::STORE, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getTruncStore() [2/4]
SDValue SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes())
Definition at line 8220 of file SelectionDAG.cpp.
References AAInfo, Alignment, assert(), Chain, dl, getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemoryLocation::getSizeOrUnknown(), llvm::EVT::getStoreSize(), InferPointerInfo(), MMOFlags, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MVT::Other, Ptr, and PtrInfo.
Referenced by chainLoadsAndStoresForMemcpy(), combineStore(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), getAddressForMemoryInput(), getMemcpyLoadsAndStores(), getTruncStore(), LowerINTRINSIC_W_CHAIN(), LowerPredicateStore(), llvm::HexagonTargetLowering::LowerStore(), PerformExtractFpToIntStores(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), performSTORECombine(), llvm::TargetLowering::scalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), llvm::AMDGPUTargetLowering::SplitVectorStore(), and llvm::HexagonDAGToDAGISel::StoreInstrForLoadIntrinsic().
getTruncStore() [3/4]
SDValue llvm::SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, MaybeAlign Alignment = MaybeAlign(), MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
Definition at line 1402 of file SelectionDAG.h.
References AAInfo, Alignment, Chain, dl, getEVTAlign(), getTruncStore(), MMOFlags, Ptr, and PtrInfo.
getTruncStore() [4/4]
SDValue llvm::SelectionDAG::getTruncStore (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, MachinePointerInfo PtrInfo, EVT SVT, unsigned Alignment, MachineMemOperand::Flags MMOFlags = MachineMemOperand::MONone, const AAMDNodes & AAInfo = AAMDNodes()) inline
FIXME: Remove once transition to Align is over.
Definition at line 1414 of file SelectionDAG.h.
References AAInfo, Alignment, Chain, dl, getTruncStore(), MMOFlags, Ptr, and PtrInfo.
getTruncStoreVP() [1/2]
SDValue SelectionDAG::getTruncStoreVP (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, SDValue Mask, SDValue EVL, EVT SVT, MachineMemOperand * MMO, bool IsCompressing = false)
Definition at line 8490 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), Chain, dl, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDLoc::getDebugLoc(), llvm::MachineMemOperand::getFlags(), llvm::SDLoc::getIROrder(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), getStoreVP(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::BitmaskEnumDetail::Mask(), N, NewSDValueDbgMsg(), llvm::MVT::Other, Ptr, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getTruncStoreVP() [2/2]
SDValue SelectionDAG::getTruncStoreVP (SDValue Chain, const SDLoc & dl, SDValue Val, SDValue Ptr, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, bool IsCompressing = false)
Definition at line 8467 of file SelectionDAG.cpp.
References AAInfo, Alignment, assert(), Chain, dl, getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MemoryLocation::getSizeOrUnknown(), llvm::EVT::getStoreSize(), InferPointerInfo(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MVT::Other, Ptr, and PtrInfo.
getTruncStridedStoreVP() [1/2]
SDValue SelectionDAG::getTruncStridedStoreVP (SDValue Chain, const SDLoc & DL, SDValue Val, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, EVT SVT, MachineMemOperand * MMO, bool IsCompressing = false)
Definition at line 8741 of file SelectionDAG.cpp.
References AddNodeIDNode(), assert(), llvm::EVT::bitsLT(), Chain, DL, E, llvm::MachinePointerInfo::getAddrSpace(), llvm::MachineMemOperand::getPointerInfo(), llvm::EVT::getRawBits(), llvm::EVT::getScalarType(), getStridedStoreVP(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementCount(), getVTList(), llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::BitmaskEnumDetail::Mask(), N, NewSDValueDbgMsg(), llvm::MVT::Other, Ptr, llvm::RegState::Undef, and llvm::ISD::UNINDEXED.
getTruncStridedStoreVP() [2/2]
SDValue SelectionDAG::getTruncStridedStoreVP (SDValue Chain, const SDLoc & DL, SDValue Val, SDValue Ptr, SDValue Stride, SDValue Mask, SDValue EVL, MachinePointerInfo PtrInfo, EVT SVT, Align Alignment, MachineMemOperand::Flags MMOFlags, const AAMDNodes & AAInfo, bool IsCompressing = false)
Definition at line 8721 of file SelectionDAG.cpp.
References AAInfo, Alignment, assert(), Chain, DL, getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), InferPointerInfo(), llvm::BitmaskEnumDetail::Mask(), MMOFlags, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MVT::Other, Ptr, PtrInfo, and llvm::MemoryLocation::UnknownSize.
getUNDEF()
SDValue llvm::SelectionDAG::getUNDEF (EVT VT) inline
Return an UNDEF node. UNDEF does not have a useful SDLoc.
Definition at line 1057 of file SelectionDAG.h.
References getNode(), and llvm::ISD::UNDEF.
Referenced by addShuffleForVecExtend(), adjustLoadValueTypeImpl(), buildFromShuffleMostly(), buildMergeScalars(), buildScalarToVector(), llvm::TargetLowering::BuildUDIV(), canonicalizeShuffleMaskWithHorizOp(), collectConcatOps(), CollectOpsToWiden(), combineArithReduction(), combineBasicSADPattern(), combineBinOpToReduce(), combineBitcast(), combineBitcastToBoolVector(), combineBitcastvxi1(), combineBVOfConsecutiveLoads(), combineConcatVectorOfConcatVectors(), combineConcatVectorOfExtracts(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineEXTRACT_SUBVECTOR(), combineExtractVectorElt(), combineFP_EXTEND(), combineINSERT_SUBVECTOR(), combineMaskedLoadConstantMask(), combineSelect(), combineSetCCAtomicArith(), combineShuffleOfBitcast(), combineShuffleOfConcatUndef(), combineShuffleOfScalars(), combineShuffleOfSplatVal(), combineSVEReductionOrderedFP(), combineTargetShuffle(), combineToHorizontalAddSub(), combineTruncateWithSat(), combineVectorPack(), combineVPDPBUSDPattern(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), CompactSwizzlableVector(), concatSubVectors(), convertLocVTToValVT(), convertShiftLeftToScale(), convertToScalableVector(), createMMXBuildVector(), detectAVGPattern(), EltsFromConsecutiveLoads(), emitIntrinsicWithChainErrorMessage(), emitNonHSAIntrinsicError(), emitRemovedIntrinsicError(), EmitTruncSStore(), ExpandHorizontalBinOp(), expandV4F32ToV2F64(), ExtendToType(), ExtractBitFromMaskVector(), FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), FoldConstantArithmetic(), foldConstantFPMath(), foldExtractSubvectorFromShuffleVector(), FoldSetCC(), getBuildDwordsVector(), getConstVector(), getCopyFromPartsVector(), getExtLoad(), getExtLoadVP(), getExtStridedLoadVP(), getGeneralPermuteNode(), getHopForBuildVector(), getKnownUndefForVectorBinop(), getLoad(), getLoadVP(), getNode(), getShuffleHalfVectors(), getShuffleScalarElt(), getShuffleVectorZeroOrUndef(), getSplatSourceVector(), getStore(), getStridedLoadVP(), getTargetVShiftNode(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), llvm::VECustomDAG::getUNDEF(), llvm::SelectionDAGBuilder::getValueImpl(), getVectorShuffle(), getVectorShuffle(), insert1BitVector(), isAddSubOrSubAdd(), isFNEG(), isHopBuildVector(), isHorizontalBinOpPart(), joinDwords(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), LowerAsSplatVectorLoad(), lowerAtomicArith(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), LowerBITCAST(), LowerBITREVERSE_XOP(), lowerBUILD_VECTOR(), LowerBUILD_VECTORvXi1(), LowerBuildVectorOfFPTrunc(), LowerBuildVectorv4x32(), llvm::SITargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), lowerFCMPIntrinsic(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), lowerFP_TO_INT_SAT(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerICMPIntrinsic(), lowerINT_TO_FP_vXi64(), LowerINTRINSIC_W_CHAIN(), llvm::MipsTargetLowering::lowerLOAD(), LowerMSCATTER(), LowerMUL(), llvm::RISCVTargetLowering::LowerOperation(), LowerPredicateStore(), lowerReductionSeq(), LowerSCALAR_TO_VECTOR(), lowerScalarInsert(), lowerScalarSplat(), LowerShift(), LowerShiftByScalarImmediate(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithPSHUFB(), lowerShuffleWithSSE4A(), lowerShuffleWithUndefHalf(), lowerShuffleWithUNPCK256(), LowerSIGN_EXTEND_Mask(), llvm::SelectionDAGBuilder::LowerStatepoint(), LowerStore(), LowerTruncateVectorStore(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2X128Shuffle(), lowerV4X128Shuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLEAsVNSRL(), lowerVECTOR_SHUFFLEAsVSlidedown(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorIntrinsicScalars(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsInsertPS(), matchShuffleWithUNPCK(), matchSplatAsGather(), NormalizeBuildVector(), padEltsToUndef(), partitionShuffleOfConcats(), llvm::SITargetLowering::passSpecialInputs(), PerformARMBUILD_VECTORCombine(), performBuildShuffleExtendCombine(), performConcatVectorsCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performDupLane128Combine(), performLDNT1Combine(), performLOADCombine(), PerformMinMaxCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), performSTNT1Combine(), PerformTruncatingStoreCombine(), performUnpackCombine(), performUzpCombine(), PerformVECTOR_REG_CASTCombine(), performVECTOR_SHUFFLECombine(), PerformVECTOR_SHUFFLECombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReplaceAddWithADDP(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), scalarizeBinOpOfSplats(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), simplifyDivRem(), simplifyFPBinop(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), simplifyShift(), splatPartsI64WithVL(), splitAndLowerShuffle(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), truncateVectorWithPACK(), tryBuildVectorShuffle(), tryToFoldExtendOfConstant(), UnrollVectorOp(), UnrollVectorOverflowOp(), vectorizeExtractedCast(), widenSubVector(), widenVec(), WidenVector(), WidenVector(), and widenVectorToPartType().
getVAArg()
SDValue SelectionDAG::getVAArg (EVT VT, const SDLoc & dl, SDValue Chain, SDValue Ptr, SDValue SV, unsigned Align)
VAArg produces a result and token chain, and takes a pointer and a source value as input.
Definition at line 9196 of file SelectionDAG.cpp.
References Chain, dl, getNode(), getTargetConstant(), getVTList(), llvm::MVT::i32, llvm::MVT::Other, Ptr, and llvm::ISD::VAARG.
getValidMaximumShiftAmountConstant()
const APInt * SelectionDAG::getValidMaximumShiftAmountConstant (SDValue V, const APInt & DemandedElts) const
If a SHL/SRA/SRL node V has constant shift amounts that are all less than the element bit-width of the shift node, return the maximum value.
Definition at line 2926 of file SelectionDAG.cpp.
References assert(), llvm::BitWidth, llvm::numbers::e, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), getValidShiftAmountConstant(), i, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::APInt::uge().
Referenced by canCreateUndefOrPoison(), ComputeNumSignBits(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifyMultipleUseDemandedBits().
getValidMinimumShiftAmountConstant()
const APInt * SelectionDAG::getValidMinimumShiftAmountConstant (SDValue V, const APInt & DemandedElts) const
If a SHL/SRA/SRL node V has constant shift amounts that are all less than the element bit-width of the shift node, return the minimum value.
Definition at line 2897 of file SelectionDAG.cpp.
References assert(), llvm::BitWidth, llvm::numbers::e, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), getValidShiftAmountConstant(), i, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::APInt::uge(), and llvm::APInt::ule().
Referenced by computeKnownBits(), and ComputeNumSignBits().
getValidShiftAmountConstant()
const APInt * SelectionDAG::getValidShiftAmountConstant (SDValue V, const APInt & DemandedElts) const
If a SHL/SRA/SRL node V has a constant or splat constant shift amount that is less than the element bit-width of the shift node, return it.
Definition at line 2882 of file SelectionDAG.cpp.
References assert(), llvm::BitWidth, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getScalarValueSizeInBits(), llvm::isConstOrConstSplat(), llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::APInt::ult().
Referenced by combineVectorSignBitsTruncation(), getValidMaximumShiftAmountConstant(), getValidMinimumShiftAmountConstant(), and llvm::TargetLowering::SimplifyDemandedBits().
getValueType()
SDValue SelectionDAG::getValueType (EVT VT)
Definition at line 1884 of file SelectionDAG.cpp.
References llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), llvm::EVT::isSimple(), N, and llvm::MVT::SimpleTy.
Referenced by addShuffleForVecExtend(), combineShiftRightArithmetic(), combineVectorTruncationWithPACKSS(), convertLocVTToValVT(), customLegalizeToWOpWithSExt(), emitRepmovs(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), getAArch64Cmp(), getCopyFromParts(), llvm::RegsForValue::getCopyFromRegs(), getNode(), LowerBUILD_VECTOR_i1(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerCallResult(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFP_TO_INT_SAT(), LowerINSERT_VECTOR_ELT_i1(), lowerMSACopyIntr(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::MSP430TargetLowering::LowerShifts(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performGatherLoadCombine(), performLD1Combine(), PerformMinMaxCombine(), PerformMinMaxFpToSatCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), performScatterStoreCombine(), performSETCCCombine(), performSignExtendInRegCombine(), performSRACombine(), performST1Combine(), PerformUMinFpToSatCombine(), PromoteMaskArithmetic(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), truncateScalarIntegerArg(), UnpackFromArgumentSlot(), UnrollVectorOp(), and unrollVectorShift().
getVectorIdxConstant()
SDValue SelectionDAG::getVectorIdxConstant (uint64_t Val, const SDLoc & DL, bool isTarget = false)
Definition at line 1672 of file SelectionDAG.cpp.
References DL, getConstant(), getDataLayout(), and llvm::TargetLoweringBase::getVectorIdxTy().
Referenced by CollectOpsToWiden(), combineEXTRACT_SUBVECTOR(), combineVectorSizedSetCCEquality(), convertIntLogicToFPLogic(), ExtractVectorElements(), foldExtractSubvectorFromShuffleVector(), GeneratePerfectShuffle(), getCopyFromPartsVector(), getCopyToPartsVector(), getNode(), getSplatValue(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), LowerVECTOR_SHUFFLEUsingOneOff(), matchBinOpReduction(), narrowExtractedVectorBinOp(), performBuildVectorCombine(), PerformInsertSubvectorCombine(), performInsertSubvectorCombine(), performLOADCombine(), performSunpkloCombine(), PerformVQDMULHCombine(), replaceShuffleOfInsert(), scalarizeBinOpOfSplats(), llvm::TargetLowering::scalarizeVectorStore(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::AMDGPUTargetLowering::splitVector(), SplitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), UnrollVectorOp(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), WidenVector(), and widenVectorToPartType().
getVectorShuffle()
SDValue SelectionDAG::getVectorShuffle (EVT VT, const SDLoc & dl, SDValue N1, SDValue N2, ArrayRef< int > Mask)
Return an ISD::VECTOR_SHUFFLE node.
The number of elements in VT, which must be a vector type, must match the number of mask elements NumElts. An integer mask element equal to -1 is treated as undefined.
Definition at line 1964 of file SelectionDAG.cpp.
References AddNodeIDNode(), llvm::all_of(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), assert(), llvm::ISD::BITCAST, commuteShuffle(), llvm::copy(), dl, E, llvm::SDLoc::getDebugLoc(), llvm::SDLoc::getIROrder(), getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), getSplatBuildVector(), llvm::BuildVectorSDNode::getSplatValue(), getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), getVTList(), llvm::TargetLoweringBase::hasVectorBlend(), i, llvm::SDValue::isUndef(), M, llvm::BitmaskEnumDetail::Mask(), N, NewSDValueDbgMsg(), llvm::BitVector::none(), llvm::Offset, and llvm::ISD::VECTOR_SHUFFLE.
Referenced by addShuffleForVecExtend(), buildFromShuffleMostly(), llvm::TargetLowering::buildLegalVectorShuffle(), BuildVSLDOI(), combineAddOfPMADDWD(), combineAndShuffleNot(), combineArithReduction(), combineBasicSADPattern(), combineBVOfConsecutiveLoads(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineFP_ROUND(), combineHorizOpWithShuffle(), combineINSERT_SUBVECTOR(), combineMinMaxReduction(), combinePMULDQ(), combineSelect(), combineShuffleOfBitcast(), combineShuffleOfConcatUndef(), combineShuffleOfSplatVal(), combineSIntToFP(), combineToExtendBoolVectorInReg(), combineToHorizontalAddSub(), combineVPDPBUSDPattern(), createVariablePermute(), EltsFromConsecutiveLoads(), expandV4F32ToV2F64(), foldExtractSubvectorFromShuffleVector(), foldShuffleOfConcatUndefs(), formSplatFromShuffles(), GeneratePerfectShuffle(), getCommutedVectorShuffle(), getMOVL(), getPack(), getShuffleHalfVectors(), getShuffleVectorZeroOrUndef(), getSToVPermuted(), getTargetVShiftNode(), getVectorShuffle(), isFNEG(), lower1BitShuffle(), lower256BitShuffle(), lower512BitShuffle(), LowerAsSplatVectorLoad(), LowerBuildVectorv4x32(), LowerConvertLow(), LowerEXTEND_VECTOR_INREG(), LowerMUL(), LowerMULH(), LowerReverse_VECTOR_SHUFFLE(), LowerRotate(), LowerShift(), LowerShiftByScalarImmediate(), LowerShiftByScalarVariable(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleOfExtractsAsVperm(), lowerShuffleWithUNPCK256(), LowerSIGN_EXTEND(), lowerToAddSubOrFMAddSub(), LowerTruncateVecI1(), LowerUINT_TO_FP_i64(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerV8F16Shuffle(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), LowerVECTOR_SHUFFLEUsingMovs(), lowerVSELECTtoVectorShuffle(), LowerVSETCC(), partitionShuffleOfConcats(), performBuildShuffleExtendCombine(), performConcatVectorsCombine(), performSelectCombine(), PerformTruncatingStoreCombine(), performVECTOR_SHUFFLECombine(), PerformVECTOR_SHUFFLECombine(), PerformVQDMULHCombine(), reduceVMULWidth(), ReplaceAddWithADDP(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifyDemandedBits(), splitAndLowerShuffle(), truncateVectorWithPACK(), tryWidenMaskForShuffle(), and vectorizeExtractedCast().
getVPLogicalNOT()
SDValue SelectionDAG::getVPLogicalNOT (const SDLoc & DL, SDValue Val, SDValue Mask, SDValue EVL, EVT VT)
Create a vector-predicated logical NOT operation as (VP_XOR Val, BooleanOne, Mask, EVL).
Definition at line 1505 of file SelectionDAG.cpp.
References DL, getBoolConstant(), getNode(), and llvm::BitmaskEnumDetail::Mask().
getVPPtrExtOrTrunc()
SDValue SelectionDAG::getVPPtrExtOrTrunc (const SDLoc & DL, EVT VT, SDValue Op, SDValue Mask, SDValue EVL)
Convert a vector-predicated Op, which must be of integer type, to the vector-type integer type VT, by either truncating it or performing either vector-predicated zero or sign extension as appropriate extension for the pointer's semantics.
This function just redirects to getVPZExtOrTrunc right now.
Definition at line 1511 of file SelectionDAG.cpp.
References DL, getVPZExtOrTrunc(), and llvm::BitmaskEnumDetail::Mask().
getVPZExtOrTrunc()
SDValue SelectionDAG::getVPZExtOrTrunc (const SDLoc & DL, EVT VT, SDValue Op, SDValue Mask, SDValue EVL)
Convert a vector-predicated Op, which must be an integer vector, to the vector-type VT, by performing either vector-predicated zext or truncating it.
The Op will be returned as-is if Op and VT are vectors containing integer with same width.
Definition at line 1516 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), DL, getNode(), and llvm::BitmaskEnumDetail::Mask().
Referenced by getVPPtrExtOrTrunc().
getVRegDbgValue()
SDDbgValue * SelectionDAG::getVRegDbgValue (DIVariable * Var, DIExpression * Expr, unsigned VReg, bool IsIndirect, const DebugLoc & DL, unsigned O)
Creates a VReg SDDbgValue node.
VReg.
Definition at line 10174 of file SelectionDAG.cpp.
References assert(), DL, llvm::SDDbgOperand::fromVReg(), llvm::SDDbgInfo::getAlloc(), and llvm::RISCVFenceField::O.
Referenced by llvm::SelectionDAGBuilder::handleDebugValue().
getVScale()
SDValue llvm::SelectionDAG::getVScale (const SDLoc & DL, EVT VT, APInt MulImm) inline
Return a node that represents the runtime scaling 'MulImm * RuntimeVL'.
Definition at line 1062 of file SelectionDAG.h.
References assert(), DL, getConstant(), llvm::APInt::getMinSignedBits(), getNode(), llvm::EVT::getSizeInBits(), llvm::APInt::sextOrTrunc(), and llvm::ISD::VSCALE.
Referenced by clampDynamicVectorIndex(), getMemBasePlusOffset(), getNode(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::TargetLowering::getVectorSubVecPointer(), llvm::TargetLowering::IncrementMemoryAddress(), and SplitEVL().
getVTList() [1/5]
SDVTList SelectionDAG::getVTList (ArrayRef< EVT > VTs)
Definition at line 9572 of file SelectionDAG.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::copy(), index, and llvm::ArrayRef< T >::size().
getVTList() [2/5]
SDVTList SelectionDAG::getVTList (EVT VT)
Return an SDVTList that represents the list of values specified.
Definition at line 9508 of file SelectionDAG.cpp.
References makeVTList().
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), CloneNodeWithValues(), combineADC(), combineAddOrSubToADCOrSBB(), combineADDToADDZE(), combineADDX(), combineBitcast(), combineBVZEXTLOAD(), combineCMP(), combineINSERT_SUBVECTOR(), combineSBB(), combineSelect(), combineSetCC(), combineSUBX(), combineSVEPrefetchVecBaseImmOff(), combineTargetShuffle(), CombineVLDDUP(), combineX86AddSub(), combineXorSubCTLZ(), ConvertBooleanCarryToCarryFlag(), ConvertCarryFlagToBooleanCarry(), convertFPToInt(), convertIntToFP(), createLoadLR(), createMemMemNode(), createStoreLR(), EltsFromConsecutiveLoads(), EmitCmp(), emitComparison(), emitIntrinsicWithCCAndChain(), EmitMaskedTruncSStore(), emitRepmovs(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::BPFSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), EmitTest(), EmitTruncSStore(), EmitUnrolledSetTag(), Expand64BitShift(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandMUL_LOHI(), ExpandREAD_REGISTER(), expandV4F32ToV2F64(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), foldAndOrOfSETCC(), GeneratePerfectShuffle(), getAArch64XALUOOp(), llvm::MipsTargetLowering::getAddrGPRel(), getAddrSpaceCast(), getAssertAlign(), getAtomic(), getAVX2GatherNode(), getBasicBlock(), getBlockAddress(), getBoundedStrlen(), getBROADCAST_LOAD(), getCALLSEQ_END(), getCALLSEQ_START(), getConstant(), getConstantFP(), getConstantPool(), getCopyFromReg(), llvm::RegsForValue::getCopyFromRegs(), getCopyToReg(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getFPBinOp(), getFPTernOp(), getFrameIndex(), getGatherNode(), getGlobalAddress(), getIndexedStore(), getIndexedStoreVP(), getIndexedStridedStoreVP(), getJumpTable(), getLabelNode(), getLifetimeNode(), getLoad(), getLoadVP(), getMachineNode(), getMad64_32(), getMaskedLoad(), getMaskedStore(), getMDNode(), getMergeValues(), getNode(), getPseudoProbeNode(), getRegister(), getRegisterMask(), getScatterNode(), getSrcValue(), getStore(), getStoreVP(), getStridedLoadVP(), getStridedStoreVP(), getTargetIndex(), GetTLSADDR(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), getVAArg(), getVectorShuffle(), getX86XALUOOp(), legalizeSVEGatherPrefetchOffsVec(), LowerABS(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDSAT_SUBSAT(), lowerADDSUBCARRY(), LowerADDSUBCARRY(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::VETargetLowering::lowerATOMIC_SWAP(), lowerAtomicArithWithLOCK(), LowerBUILD_VECTORToVIDUP(), lowerBuildVectorAsBroadcast(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), LowerCMP_SWAP(), LowerCTLZ(), LowerCTTZ(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::VETargetLowering::lowerEH_SJLJ_SETJMP(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), LowerMGATHER(), LowerMSCATTER(), LowerMULO(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerPARITY(), llvm::HexagonTargetLowering::LowerREADCYCLECOUNTER(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::LanaiTargetLowering::LowerSELECT_CC(), LowerSETCCCARRY(), lowerShuffleAsBroadcast(), LowerSTORE(), LowerStore(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerUINT_TO_FP_vXi32(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), LowerVectorExtend(), LowerXALUO(), AMDGPUDAGToDAGISel::matchLoadD16FromBuildVector(), narrowLoadToVZLoad(), PerformADDVecReduce(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCONDCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDUPCombine(), PerformExtractFpToIntStores(), performFlagSettingCombine(), performGatherLoadCombine(), PerformHWLoopCombine(), performLD1Combine(), performMaskedGatherScatterCombine(), PerformMVEVLDCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), performScatterStoreCombine(), PerformSETCCCombine(), performSignExtendInRegCombine(), PerformUMLALCombine(), PerformVDUPCombine(), PerformVECREDUCE_ADDCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), ReplaceLongIntrinsic(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), AMDGPUDAGToDAGISel::Select(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), SelectNodeTo(), llvm::HexagonDAGToDAGISel::SelectTypecast(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::TargetLowering::SimplifySetCC(), TryCombineBaseUpdate(), tryToWidenSetCCOperands(), UnrollVectorOverflowOp(), and valueToCarryFlag().
getVTList() [3/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2)
Definition at line 9512 of file SelectionDAG.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), and llvm::EVT::getRawBits().
getVTList() [4/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2, EVT VT3)
Definition at line 9530 of file SelectionDAG.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), and llvm::EVT::getRawBits().
getVTList() [5/5]
SDVTList SelectionDAG::getVTList (EVT VT1, EVT VT2, EVT VT3, EVT VT4)
Definition at line 9550 of file SelectionDAG.cpp.
References llvm::FoldingSetNodeID::AddInteger(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), and llvm::EVT::getRawBits().
getZeroExtendInReg()
SDValue SelectionDAG::getZeroExtendInReg (SDValue Op, const SDLoc & DL, EVT VT)
Return the expression required to zero extend the Op value assuming it was the smaller SrcTy value.
Definition at line 1461 of file SelectionDAG.cpp.
References llvm::ISD::AND, assert(), llvm::EVT::bitsLE(), DL, getConstant(), llvm::APInt::getLowBitsSet(), getNode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorElementCount(), llvm::RISCVMatInt::Imm, llvm::EVT::isInteger(), and llvm::EVT::isVector().
Referenced by combineExtSetcc(), combineStore(), getPtrExtendInReg(), lowerFP_TO_INT_SAT(), llvm::MSP430TargetLowering::LowerShifts(), LowerStore(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), performFP_TO_INT_SATCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), PromoteMaskArithmetic(), and llvm::TargetLowering::SimplifyDemandedBits().
getZExtOrTrunc()
SDValue SelectionDAG::getZExtOrTrunc (SDValue Op, const SDLoc & DL, EVT VT)
Convert Op, which must be of integer type, to the integer type VT, by either zero-extending or truncating it.
Definition at line 1446 of file SelectionDAG.cpp.
References llvm::EVT::bitsGT(), DL, getNode(), llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by combineAnd(), combineBitcast(), combineBitcastvxi1(), combineCompareEqual(), combineExtractVectorElt(), combineExtractWithShuffle(), combineOr(), combinePredicateReduction(), combineScalarAndWithMaskSetcc(), combineScalarToVector(), combineSelect(), combineSetCCMOVMSK(), combineShiftAnd1ToBitTest(), combineShiftToMULH(), combineShuffleOfScalars(), combineXor(), createVariablePermute(), createVPDPBUSD(), earlyExpandDIVFIX(), emitMemMemReg(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen(), Expand64BitShift(), expandDivFix(), llvm::TargetLowering::expandDIVREMByConstant(), foldAddSubBoolOfMaskedVal(), foldCONCAT_VECTORS(), getPTest(), getPtrExtOrTrunc(), getShiftAmountOperand(), getTargetVShiftNode(), llvm::TargetLowering::getVectorSubVecPointer(), llvm::TargetLowering::IncrementMemoryAddress(), lowerBALLOTIntrinsic(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), lowerBuildVectorToBitOp(), LowerBuildVectorv16i8(), lowerFCMPIntrinsic(), LowerFGETSIGN(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), LowerFunnelShift(), lowerICMPIntrinsic(), LowerINTRINSIC_W_CHAIN(), llvm::HexagonTargetLowering::LowerLoad(), llvm::SystemZTargetLowering::LowerOperationWrapper(), LowerShift(), LowervXi8MulWithUNPCK(), lowerX86CmpEqZeroToCtlzSrl(), llvm::HexagonTargetLowering::PerformDAGCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), performExtractVectorEltCombine(), PerformMinMaxFpToSatCombine(), llvm::AMDGPUTargetLowering::performMulCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), llvm::AMDGPUTargetLowering::performMulLoHiCombine(), performSETCCCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::AMDGPUTargetLowering::performTruncateCombine(), PerformUMinFpToSatCombine(), PerformVSetCCToVCTPCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), selectUmullSmull(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), widenAbs(), and widenCtPop().
hasDebugValues()
bool llvm::SelectionDAG::hasDebugValues () const inline
Return true if there are any SDDbgValue nodes associated with this SelectionDAG.
Definition at line 1874 of file SelectionDAG.h.
References llvm::SDDbgInfo::empty().
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
haveNoCommonBitsSet()
bool SelectionDAG::haveNoCommonBitsSet (SDValue A, SDValue B) const
Return true if A and B have no common bits set.
As an example, this can allow an 'add' to be transformed into an 'or'.
Definition at line 5043 of file SelectionDAG.cpp.
References assert(), B, computeKnownBits(), llvm::KnownBits::haveNoCommonBitsSet(), and haveNoCommonBitsSetCommutative().
Referenced by detectAVGPattern(), getPointerConstIncrement(), and isADDLike().
InferPtrAlign()
MaybeAlign SelectionDAG::InferPtrAlign (SDValue Ptr) const
Infer alignment of a load / store address.
InferPtrAlignment - Infer alignment of a load / store address.
Return std::nullopt if it cannot be inferred.
Definition at line 11585 of file SelectionDAG.cpp.
References Align, llvm::commonAlignment(), llvm::computeKnownBits(), llvm::KnownBits::countMinTrailingZeros(), getDataLayout(), llvm::MachineFunction::getFrameInfo(), getMachineFunction(), llvm::MachineFrameInfo::getObjectAlign(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::GlobalValue::getType(), isBaseWithConstantOffset(), llvm::TargetLowering::isGAPlusOffset(), llvm::min(), and Ptr.
Referenced by getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), and LowerAsSplatVectorLoad().
init()
void SelectionDAG::init (MachineFunction & NewMF, OptimizationRemarkEmitter & NewORE, Pass * PassPtr, const TargetLibraryInfo * LibraryInfo, LegacyDivergenceAnalysis * Divergence, ProfileSummaryInfo * PSIin, BlockFrequencyInfo * BFIin, FunctionVarLocs const * FnVarLocs)
Prepare this SelectionDAG to process code in the given MachineFunction.
Definition at line 1310 of file SelectionDAG.cpp.
References llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getSelectionDAGInfo(), getSubtarget(), and llvm::TargetSubtargetInfo::getTargetLowering().
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
isBaseWithConstantOffset()
bool SelectionDAG::isBaseWithConstantOffset (SDValue Op) const
Return true if the specified operand is an ISD::ADD with a ConstantSDNode on the right-hand side, or if it is an ISD::OR with a ConstantSDNode that is guaranteed to have the same semantics as an ADD.
This handles the equivalence: X|Cst == X+Cst iff X&Cst = 0.
Definition at line 4814 of file SelectionDAG.cpp.
References llvm::ISD::ADD, MaskedValueIsZero(), and llvm::ISD::OR.
Referenced by getBaseWithConstantOffset(), getBaseWithOffsetUsingSplitOR(), InferPtrAlign(), llvm::SITargetLowering::isReassocProfitable(), LowerAsSplatVectorLoad(), replaceZeroVectorStore(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), llvm::RISCVDAGToDAGISel::SelectFrameAddrRegImm(), and llvm::LoongArchDAGToDAGISel::SelectInlineAsmMemoryOperand().
isConstantFPBuildVectorOrConstantFP()
SDNode * SelectionDAG::isConstantFPBuildVectorOrConstantFP (SDValue N) const
Test whether the given value is a constant FP or similar node.
Definition at line 12108 of file SelectionDAG.cpp.
References llvm::ISD::isBuildVectorOfConstantFPSDNodes(), N, and llvm::ISD::SPLAT_VECTOR.
Referenced by canonicalizeCommutativeBinop(), and isConstantValueOfAnyType().
isConstantIntBuildVectorOrConstantInt()
SDNode * SelectionDAG::isConstantIntBuildVectorOrConstantInt (SDValue N) const
Test whether the given value is a constant int or similar node.
Definition at line 12089 of file SelectionDAG.cpp.
References llvm::ISD::GlobalAddress, llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::TargetLowering::isOffsetFoldingLegal(), N, and llvm::ISD::SPLAT_VECTOR.
Referenced by canonicalizeCommutativeBinop(), combinePMULDQ(), combineSub(), foldAddSubOfSignBit(), isConstantValueOfAnyType(), performSubAddMULCombine(), salvageDebugInfo(), and stripConstantMask().
isConstantValueOfAnyType()
bool llvm::SelectionDAG::isConstantValueOfAnyType (SDValue N) const inline
Returns
true if N is any kind of constant or build_vector of constants, int or float. If a vector, it may not necessarily be a splat.
Definition at line 2241 of file SelectionDAG.h.
References isConstantFPBuildVectorOrConstantFP(), isConstantIntBuildVectorOrConstantInt(), and N.
Referenced by llvm::AMDGPUTargetLowering::performSelectCombine(), and simplifySelect().
isEqualTo()
bool SelectionDAG::isEqualTo (SDValue A, SDValue B) const
Test whether two SDValues are known to compare equal.
This is true if they are the same value, or if one is negative zero and the other positive zero.
Definition at line 4988 of file SelectionDAG.cpp.
References B.
Referenced by combineSelect().
isGuaranteedNotToBePoison() [1/2]
bool llvm::SelectionDAG::isGuaranteedNotToBePoison (SDValue Op, const APInt & DemandedElts, unsigned Depth = 0) const inline
Return true if this function can prove that Op is never poison.
The DemandedElts argument limits the check to the requested vector elements.
Definition at line 2047 of file SelectionDAG.h.
References llvm::Depth, and isGuaranteedNotToBeUndefOrPoison().
isGuaranteedNotToBePoison() [2/2]
bool llvm::SelectionDAG::isGuaranteedNotToBePoison (SDValue Op, unsigned Depth = 0) const inline
Return true if this function can prove that Op is never poison.
Definition at line 2041 of file SelectionDAG.h.
References llvm::Depth, and isGuaranteedNotToBeUndefOrPoison().
isGuaranteedNotToBeUndefOrPoison() [1/2]
bool SelectionDAG::isGuaranteedNotToBeUndefOrPoison (SDValue Op, bool PoisonOnly = false, unsigned Depth = 0) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
Definition at line 4655 of file SelectionDAG.cpp.
References llvm::Depth, llvm::ISD::FREEZE, llvm::APInt::getAllOnes(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), and llvm::EVT::isVector().
Referenced by computeKnownBits(), getNode(), isGuaranteedNotToBePoison(), isGuaranteedNotToBeUndefOrPoison(), and llvm::X86TargetLowering::isGuaranteedNotToBeUndefOrPoisonForTargetNode().
isGuaranteedNotToBeUndefOrPoison() [2/2]
bool SelectionDAG::isGuaranteedNotToBeUndefOrPoison (SDValue Op, const APInt & DemandedElts, bool PoisonOnly = false, unsigned Depth = 0) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
The DemandedElts argument limits the check to the requested vector elements.
Definition at line 4672 of file SelectionDAG.cpp.
References llvm::all_of(), llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, canCreateUndefOrPoison(), llvm::Depth, llvm::numbers::e, llvm::ISD::FrameIndex, llvm::ISD::FREEZE, i, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, isGuaranteedNotToBeUndefOrPoison(), llvm::TargetLowering::isGuaranteedNotToBeUndefOrPoisonForTargetNode(), llvm::isIntOrFPConstant(), MaxRecursionDepth, llvm::ISD::TargetFrameIndex, llvm::ISD::UNDEF, and llvm::ISD::VALUETYPE.
isKnownNeverNaN()
bool SelectionDAG::isKnownNeverNaN (SDValue Op, bool SNaN = false, unsigned Depth = 0) const
Test whether the given SDValue (or all elements of it, if it is a vector) is known to never be NaN.
If SNaN is true, returns if Op is known to never be a signaling NaN (it may still be a qNaN).
Definition at line 4826 of file SelectionDAG.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::Depth, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::ISD::FMAXIMUM, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::ISD::FMINIMUM, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FROUNDEVEN, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, getTarget(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLowering::isKnownNeverNaNForTargetNode(), isKnownNeverSNaN(), MaxRecursionDepth, Options, llvm::ISD::SELECT, llvm::ISD::SINT_TO_FP, and llvm::ISD::UINT_TO_FP.
Referenced by combineFMinNumFMaxNum(), combineSelect(), llvm::AMDGPUTargetLowering::isKnownNeverNaNForTargetNode(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), isKnownNeverSNaN(), and isLegalToCombineMinNumMaxNum().
isKnownNeverSNaN()
bool llvm::SelectionDAG::isKnownNeverSNaN (SDValue Op, unsigned Depth = 0) const inline
Returns
true if Op is known to never be a signaling NaN.
Definition at line 2092 of file SelectionDAG.h.
References llvm::Depth, and isKnownNeverNaN().
Referenced by llvm::SITargetLowering::isCanonicalized(), and isKnownNeverNaN().
isKnownNeverZero()
bool SelectionDAG::isKnownNeverZero (SDValue Op) const
Test whether the given SDValue is known to contain non-zero value(s).
Definition at line 4966 of file SelectionDAG.cpp.
References assert(), llvm::ISD::matchUnaryPredicate(), and llvm::ISD::OR.
Referenced by LowerCTTZ(), and LowerShift().
isKnownNeverZeroFloat()
bool SelectionDAG::isKnownNeverZeroFloat (SDValue Op) const
Test whether the given floating point SDValue is known to never be positive or negative zero.
Definition at line 4943 of file SelectionDAG.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, and llvm::ISD::SPLAT_VECTOR.
Referenced by combineSelect().
isKnownToBeAPowerOfTwo()
bool SelectionDAG::isKnownToBeAPowerOfTwo (SDValue Val) const
Test if the given value is known to have exactly one bit set.
This differs from computeKnownBits in that it doesn't necessarily determine which bit is set.
Definition at line 3956 of file SelectionDAG.cpp.
References llvm::all_of(), llvm::BitWidth, llvm::ISD::BUILD_VECTOR, computeKnownBits(), llvm::KnownBits::countMaxPopulation(), llvm::KnownBits::countMinPopulation(), E, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarSizeInBits(), getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::isConstOrConstSplat(), llvm::SDNode::ops(), llvm::ISD::SHL, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRL, and llvm::ISD::VSCALE.
isSafeToSpeculativelyExecute()
bool llvm::SelectionDAG::isSafeToSpeculativelyExecute (unsigned Opcode) const inline
Some opcodes may create immediate undefined behavior when used with some values (integer division-by-zero for example).
Therefore, these operations are not generally safe to move around or change.
Definition at line 2302 of file SelectionDAG.h.
References llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SREM, llvm::ISD::UDIV, llvm::ISD::UDIVREM, and llvm::ISD::UREM.
Referenced by foldSelectWithIdentityConstant().
isSplatValue() [1/2]
bool SelectionDAG::isSplatValue (SDValue V, bool AllowUndefs = false) const
Test whether V has a splatted value.
Helper wrapper to main isSplatValue function.
Definition at line 2797 of file SelectionDAG.cpp.
References assert(), llvm::APInt::getAllOnes(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::isScalableVector(), isSplatValue(), and llvm::EVT::isVector().
isSplatValue() [2/2]
bool SelectionDAG::isSplatValue (SDValue V, const APInt & DemandedElts, APInt & UndefElts, unsigned Depth = 0) const
Test whether V has a splatted value for all the demanded elements.
isSplatValue - Return true if the vector V has the same value across all DemandedElts.
On success UndefElts will indicate the elements that have UNDEF values instead of the splat value, this is only guaranteed to be correct for DemandedElts.
NOTE: The function will return true for a demanded splat of UNDEF values.
For scalable vectors, we don't know the number of lanes at compile time. Instead, we use a 1 bit APInt to represent a conservative value for all lanes; that is, that one bit value is implicitly splatted across all lanes.
Definition at line 2611 of file SelectionDAG.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND_VECTOR_INREG, assert(), llvm::ISD::BITCAST, llvm::BitWidth, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::Depth, llvm::ISD::EXTRACT_SUBVECTOR, llvm::APInt::extractBits(), llvm::APInt::getAllOnes(), llvm::APInt::getBitWidth(), llvm::SDValue::getConstantOperandVal(), llvm::APInt::getNullValue(), llvm::APInt::getOneBitSet(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::APInt::getSplat(), llvm::SDValue::getValueType(), llvm::EVT::getVectorNumElements(), llvm::APInt::getZero(), i, I, int, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::isInteger(), llvm::EVT::isScalableVector(), llvm::TargetLowering::isSplatValueForTargetNode(), llvm::SDValue::isUndef(), llvm::EVT::isVector(), llvm::APInt::isZero(), isZero(), LHS, M, llvm::BitmaskEnumDetail::Mask(), MaxRecursionDepth, llvm::ISD::OR, RHS, llvm::APIntOps::ScaleBitMask(), llvm::APInt::setBit(), llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SUB, llvm::APInt::trunc(), llvm::ISD::TRUNCATE, uint64_t, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZERO_EXTEND_VECTOR_INREG, and llvm::APInt::zext().
Referenced by canonicalizeShuffleWithBinOps(), combineEXTRACT_SUBVECTOR(), combineShuffleOfSplatVal(), combineX86ShuffleChain(), getSplatSourceVector(), isOnlyUsedByStores(), isSplatValue(), LowerRotate(), lowerVECTOR_SHUFFLE(), llvm::X86TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), and splitVector().
isUndef()
bool SelectionDAG::isUndef (unsigned Opcode, ArrayRef< SDValue > Ops)
Return true if the result of this operation is always undefined.
Definition at line 5796 of file SelectionDAG.cpp.
References llvm::any_of(), assert(), llvm::SDValue::getNode(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::isNullConstant(), llvm::SDValue::isUndef(), llvm::SDNode::op_values(), llvm::ISD::SDIV, llvm::ArrayRef< T >::size(), llvm::ISD::SREM, llvm::ISD::UDIV, and llvm::ISD::UREM.
Referenced by FoldConstantArithmetic(), and simplifyDivRem().
Legalize()
void SelectionDAG::Legalize ()
This transforms the SelectionDAG into a SelectionDAG that is compatible with the target instruction selector, as indicated by the TargetLowering object.
This is the entry point for the file.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 5096 of file LegalizeDAG.cpp.
References allnodes_begin(), allnodes_end(), AssignTopologicalOrder(), DeleteNode(), E, llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::SDValue::getNode(), getNode(), getRoot(), llvm::SmallPtrSetImpl< PtrType >::insert(), N, and RemoveDeadNodes().
LegalizeOp()
bool SelectionDAG::LegalizeOp (SDNode * N, SmallSetVector< SDNode *, 16 > & UpdatedNodes)
Transforms a SelectionDAG node and any operands to it into a node that is compatible with the target instruction selector, as indicated by the TargetLowering object.
Returns
true if N is a valid, legal node after calling this.
This essentially runs a single recursive walk of the Legalize process over the given node (and its operands). This can be used to incrementally legalize the DAG. All of the nodes which are directly replaced, potentially including N, are added to the output parameter UpdatedNodes so that the delta to the DAG can be understood by the caller.
When this returns false, N has been legalized in a way that make the pointer passed in no longer valid. It may have even been deleted from the DAG, and so it shouldn't be used further. When this returns true, the N passed in is a legal node, and can be immediately processed as such. This may still have done some work on the DAG, and will still populate UpdatedNodes with any new nodes replacing those originally in the DAG.
Definition at line 5145 of file LegalizeDAG.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallPtrSetImpl< PtrType >::insert(), and N.
LegalizeTypes()
bool SelectionDAG::LegalizeTypes ()
This transforms the SelectionDAG into a SelectionDAG that only uses types natively supported by the target.
Returns "true" if it made any changes.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 1062 of file LegalizeTypes.cpp.
References llvm::DAGTypeLegalizer::run().
LegalizeVectors()
bool SelectionDAG::LegalizeVectors ()
This transforms the SelectionDAG into a SelectionDAG that only uses vector math operations supported by the target.
This is necessary as a separate step from Legalize because unrolling a vector operation can introduce illegal types, which requires running LegalizeTypes again.
This returns true if it made any changes; in that case, LegalizeTypes is called again before Legalize.
Note that this is an involved process that may invalidate pointers into the graph.
Definition at line 1720 of file LegalizeVectorOps.cpp.
LLVM_DEPRECATED() [1/2]
llvm::SelectionDAG::LLVM_DEPRECATED ("Use the getLoad function that takes a MaybeAlign instead" , "")
FIXME: Remove once transition to Align is over.
LLVM_DEPRECATED() [2/2]
llvm::SelectionDAG::LLVM_DEPRECATED ("Use the getLoad function that takes a MaybeAlign instead" , "") inline
FIXME: Remove once transition to Align is over.
Definition at line 1349 of file SelectionDAG.h.
References AAInfo, Alignment, Chain, dl, getLoad(), MMOFlags, llvm::Offset, Ptr, PtrInfo, and Ranges.
makeEquivalentMemoryOrdering() [1/2]
SDValue SelectionDAG::makeEquivalentMemoryOrdering (LoadSDNode * OldLoad, SDValue NewMemOp)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
This ensures that the new memory node will have the same relative memory dependency position as the old load. Returns the new merged load chain.
Definition at line 10882 of file SelectionDAG.cpp.
References assert(), llvm::SDValue::getNode(), llvm::SDValue::getValue(), and makeEquivalentMemoryOrdering().
makeEquivalentMemoryOrdering() [2/2]
SDValue SelectionDAG::makeEquivalentMemoryOrdering (SDValue OldChain, SDValue NewMemOpChain)
If an existing load has uses of its chain, create a token factor node with that chain and the new memory node's chain and update users of the old chain to the token factor.
This ensures that the new memory node will have the same relative memory dependency position as the old load. Returns the new merged load chain.
Definition at line 10864 of file SelectionDAG.cpp.
References assert(), getNode(), llvm::SDValue::getValueType(), llvm::MVT::Other, ReplaceAllUsesOfValueWith(), llvm::ISD::TokenFactor, UpdateNodeOperands(), and llvm::SDValue::use_empty().
Referenced by combineBVOfConsecutiveLoads(), combineExtractVectorElt(), combineStore(), EltsFromConsecutiveLoads(), getBROADCAST_LOAD(), lowerShuffleAsBroadcast(), lowerVECTOR_SHUFFLE(), makeEquivalentMemoryOrdering(), narrowExtractedVectorLoad(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
MaskedValueIsAllOnes()
bool SelectionDAG::MaskedValueIsAllOnes (SDValue Op, const APInt & Mask, unsigned Depth = 0) const
Return true if '(Op & Mask) == Mask'.
MaskedValueIsAllOnes - Return true if '(Op & Mask) == Mask'.
Op and Mask are known to be the same type.
Definition at line 2581 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, and llvm::BitmaskEnumDetail::Mask().
MaskedValueIsZero() [1/2]
bool SelectionDAG::MaskedValueIsZero (SDValue V, const APInt & Mask, const APInt & DemandedElts, unsigned Depth = 0) const
Return true if 'Op & Mask' is known to be zero in DemandedElts.
MaskedValueIsZero - Return true if 'V & Mask' is known to be zero in DemandedElts.
We use this predicate to simplify operations downstream. Op and Mask are known to be the same type.
We use this predicate to simplify operations downstream. Mask is known to be zero for bits that V cannot have.
Definition at line 2567 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, and llvm::BitmaskEnumDetail::Mask().
MaskedValueIsZero() [2/2]
bool SelectionDAG::MaskedValueIsZero (SDValue V, const APInt & Mask, unsigned Depth = 0) const
Return true if 'Op & Mask' is known to be zero.
MaskedValueIsZero - Return true if 'V & Mask' is known to be zero.
We use this predicate to simplify operations downstream. Op and Mask are known to be the same type.
We use this predicate to simplify operations downstream. Mask is known to be zero for bits that V cannot have.
Definition at line 2559 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::SelectionDAGISel::CheckAndMask(), combine_CC(), combineAddOfPMADDWD(), combineAnd(), combineCMP(), combineDeMorganOfBoolean(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineSetCC(), combineTargetShuffle(), combineVectorPack(), combineZext(), EmitCmp(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetLowering::expandMUL_LOHI(), getBT(), getFauxShuffleMask(), getTruncatedUSUBSAT(), isBaseWithConstantOffset(), isTruncWithZeroHighBitsInput(), LowerPARITY(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), matchLSNode(), matchShuffleWithPACK(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformORCombineToBFI(), performSETCCCombine(), llvm::RISCVTargetLowering::ReplaceNodeResults(), selectUmullSmull(), llvm::RISCVDAGToDAGISel::selectZExtBits(), llvm::LoongArchDAGToDAGISel::selectZExti32(), ShrinkLoadReplaceStoreWithStore(), SignBitIsZero(), llvm::TargetLowering::SimplifySetCC(), and tryDemorganOfBooleanCondition().
MaskedVectorIsZero()
bool SelectionDAG::MaskedVectorIsZero (SDValue V, const APInt & DemandedElts, unsigned Depth = 0) const
Return true if 'Op' is known to be zero in DemandedElts.
MaskedVectorIsZero - Return true if 'Op' is known to be zero in DemandedElts.
We use this predicate to simplify operations downstream.
Definition at line 2575 of file SelectionDAG.cpp.
References computeKnownBits(), llvm::Depth, and llvm::KnownBits::isZero().
Referenced by combineOr(), computeVectorKnownZeroElements(), isTargetShuffleEquivalent(), matchBinaryShuffle(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode().
matchBinOpReduction()
SDValue SelectionDAG::matchBinOpReduction (SDNode * Extract, ISD::NodeType & BinOp, ArrayRef< ISD::NodeType > CandidateBinOps, bool AllowPartials = false)
Match a binop + shuffle pyramid that represents a horizontal reduction over the elements of a vector starting from the EXTRACT_VECTOR_ELT node /p Extract.
The reduction must use one of the opcodes listed in /p CandidateBinOps and on success /p BinOp will contain the matching opcode. Returns the vector that is being reduced on, or SDValue() if a reduction was not matched. If AllowPartials is set then in the case of a reduction pattern that only matches the first few stages, the extracted subvector of the start of the reduction is returned.
Definition at line 11323 of file SelectionDAG.cpp.
References llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::SDValue::getConstantOperandAPInt(), getContext(), getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), getVectorIdxConstant(), llvm::EVT::getVectorVT(), i, Index, int, llvm::TargetLoweringBase::isExtractSubvectorCheap(), llvm::isNullConstant(), llvm_unreachable, llvm::Log2_32(), llvm::none_of(), and llvm::Shuffle.
Referenced by combineArithReduction(), combineBasicSADPattern(), combineMinMaxReduction(), combinePredicateReduction(), combineVPDPBUSDPattern(), and MatchVectorAllZeroTest().
MorphNodeTo()
SDNode * SelectionDAG::MorphNodeTo (SDNode * N, unsigned Opc, SDVTList VTs, ArrayRef< SDValue > Ops)
This mutates the specified node to have the specified return type, opcode, and operands.
MorphNodeTo - This mutates the specified node to have the specified return type, opcode, and operands.
Note that MorphNodeTo returns the resultant node. If there is already a node of the specified opcode and operands, it returns that node instead of the current one. Note that the SDLoc need not be the same.
Using MorphNodeTo is faster than creating a new node and swapping it in with ReplaceAllUsesWith both because it often avoids allocating a new node, and because it doesn't require CSE recalculation for any of the node's users.
However, note that MorphNodeTo recursively deletes dead nodes from the DAG. As a consequence it isn't appropriate to use from within the DAG combiner or the legalizer which maintain worklists that would need to be updated when deleting things.
Definition at line 9845 of file SelectionDAG.cpp.
References AddNodeIDNode(), E, llvm::SmallPtrSetImplBase::empty(), llvm::MVT::Glue, I, llvm::SmallPtrSetImpl< PtrType >::insert(), N, llvm::SDVTList::NumVTs, RemoveDeadNodes(), llvm::Use::set(), and llvm::SDVTList::VTs.
Referenced by CloneNodeWithValues(), llvm::NVPTXTargetLowering::LowerCall(), AMDGPUDAGToDAGISel::Select(), SelectNodeTo(), and llvm::HexagonDAGToDAGISel::SelectTypecast().
mutateStrictFPToFP()
SDNode * SelectionDAG::mutateStrictFPToFP (SDNode * Node)
Mutate the specified strict FP node to its non-strict equivalent, unlinking the node from its chain and dropping the metadata arguments.
The node must be a strict FP node.
Definition at line 9898 of file SelectionDAG.cpp.
operator=()
SelectionDAG& llvm::SelectionDAG::operator= (const SelectionDAG &) delete
RemoveDeadNode()
void SelectionDAG::RemoveDeadNode (SDNode * N)
Remove the specified node from the system.
If any of its operands then becomes dead, remove them as well. Inform UpdateListener for each node deleted.
Definition at line 1022 of file SelectionDAG.cpp.
References llvm::NVPTXISD::Dummy, getRoot(), N, and RemoveDeadNodes().
Referenced by foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), llvm::TargetLowering::getCheaperOrNeutralNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), llvm::SelectionDAGISel::ReplaceNode(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectHVXDualOutput(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectIntrinsicWChain(), llvm::HexagonDAGToDAGISel::SelectNewCircIntrinsic(), SelectNodeTo(), llvm::HvxSelector::selectVAlign(), and llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic().
RemoveDeadNodes() [1/2]
void SelectionDAG::RemoveDeadNodes ()
This method deletes all unreachable nodes in the SelectionDAG.
RemoveDeadNodes - This method deletes all unreachable nodes in the SelectionDAG.
Definition at line 968 of file SelectionDAG.cpp.
References llvm::NVPTXISD::Dummy, and getRoot().
Referenced by Legalize(), MorphNodeTo(), llvm::RISCVDAGToDAGISel::PostprocessISelDAG(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), AMDGPUDAGToDAGISel::PreprocessISelDAG(), and RemoveDeadNode().
RemoveDeadNodes() [2/2]
void SelectionDAG::RemoveDeadNodes (SmallVectorImpl< SDNode * > & DeadNodes)
This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
RemoveDeadNodes - This method deletes the unreachable nodes in the given list, and any nodes that become unreachable as a result.
Definition at line 988 of file SelectionDAG.cpp.
References llvm::ISD::DELETED_NODE, E, I, N, llvm::SelectionDAG::DAGUpdateListener::Next, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::Use::set(), and llvm::SDNode::use_empty().
ReplaceAllUsesOfValuesWith()
void SelectionDAG::ReplaceAllUsesOfValuesWith (const SDValue * From, const SDValue * To, unsigned Num)
Like ReplaceAllUsesOfValueWith, but for multiple values at once.
ReplaceAllUsesOfValuesWith - Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
This correctly handles the case where there is an overlap between the From values and the To values.
The same value may appear in both the From and To list. The Deleted vector is handled the same way as for ReplaceAllUsesWith.
Definition at line 10699 of file SelectionDAG.cpp.
References copyExtraInfo(), E, From, i, ReplaceAllUsesOfValueWith(), llvm::Use::set(), llvm::sort(), transferDbgValues(), llvm::SDNode::use_begin(), llvm::SDNode::use_end(), and Uses.
Referenced by llvm::SelectionDAGISel::ReplaceUses().
ReplaceAllUsesOfValueWith()
void SelectionDAG::ReplaceAllUsesOfValueWith (SDValue From, SDValue To)
Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
ReplaceAllUsesOfValueWith - Replace any uses of From with To, leaving uses of other values produced by From.getNode() alone.
The Deleted vector is handled the same way as for ReplaceAllUsesWith.
Definition at line 10541 of file SelectionDAG.cpp.
References copyExtraInfo(), From, llvm::SDValue::getNode(), getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::isDivergent(), ReplaceAllUsesWith(), llvm::Use::set(), setRoot(), transferDbgValues(), and updateDivergence().
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64BitSMLAL16(), AddCombineTo64bitUMAAL(), adjustSubwordCmp(), combineBinOp_VLToVWBinOp_VL(), combineBitcast(), combineCarryDiamond(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineCVTPH2PS(), combineEXTEND_VECTOR_INREG(), combineExtractWithShuffle(), combineINSERT_SUBVECTOR(), combineMOVDQ2Q(), combineSetCCAtomicArith(), combineSIntToFP(), combineTargetShuffle(), combineVSelectToBLENDV(), combineX86INT_TO_FP(), emitIntrinsicWithCCAndChain(), EmitTest(), lowerBuildVectorAsBroadcast(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), makeEquivalentMemoryOrdering(), AMDGPUDAGToDAGISel::matchLoadD16FromBuildVector(), performConcatVectorsCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDivRemCombine(), performExtractVectorEltCombine(), PerformHWLoopCombine(), performIntToFpCombine(), PerformORCombineToSMULWBT(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingToWideningLoad(), llvm::AMDGPUTargetLowering::performStoreCombine(), performUnpackCombine(), PerformVDUPCombine(), PerformVMOVhrCombine(), PerformVMOVrhCombine(), PerformVMOVRRDCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), reduceVSXSwap(), ReplaceAllUsesOfValuesWith(), llvm::SelectionDAGISel::ReplaceUses(), SkipExtensionForVMULL(), tryToFoldExtOfExtload(), tryToFoldExtOfLoad(), and tryToFoldExtOfMaskedLoad().
ReplaceAllUsesWith() [1/3]
void SelectionDAG::ReplaceAllUsesWith (SDNode * From, const SDValue * To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG.
This version can replace From with any result values. To must match the number and types of values returned by From.
Definition at line 10491 of file SelectionDAG.cpp.
References copyExtraInfo(), llvm::numbers::e, From, getNode(), getRoot(), llvm::SDNode::use_iterator::getUse(), i, llvm::SDNode::isDivergent(), ReplaceAllUsesWith(), llvm::Use::set(), setRoot(), transferDbgValues(), and updateDivergence().
ReplaceAllUsesWith() [2/3]
void SelectionDAG::ReplaceAllUsesWith (SDNode * From, SDNode * To)
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG.
This version assumes that for each value of From, there is a corresponding value in To in the same position with the same type.
Definition at line 10433 of file SelectionDAG.cpp.
References assert(), copyExtraInfo(), llvm::numbers::e, From, getNode(), getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::getValueType(), i, llvm::SDNode::isDivergent(), setRoot(), transferDbgValues(), and updateDivergence().
ReplaceAllUsesWith() [3/3]
void SelectionDAG::ReplaceAllUsesWith (SDValue FromN, SDValue To)
Modify anything using 'From' to use 'To' instead.
ReplaceAllUsesWith - Modify anything using 'From' to use 'To' instead.
This can cause recursive merging of nodes in the DAG. Use the first version if 'From' is known to have a single result, use the second if you have two nodes with identical results (or if 'To' has a superset of the results of 'From'), use the third otherwise.
These methods all take an optional UpdateListener, which (if not null) is informed about nodes that are deleted and modified due to recursive changes in the dag.
These functions only replace all existing uses. It's possible that as these replacements are being performed, CSE may cause the From node to be given new uses. These new uses of From are left in place, and not automatically transferred to To.
This can cause recursive merging of nodes in the DAG.
This version assumes From has a single result value.
Definition at line 10380 of file SelectionDAG.cpp.
References assert(), copyExtraInfo(), From, llvm::SDValue::getNode(), llvm::SDValue::getResNo(), getRoot(), llvm::SDNode::use_iterator::getUse(), llvm::SDNode::isDivergent(), llvm::Use::set(), setRoot(), transferDbgValues(), and updateDivergence().
Referenced by emitComparison(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerShufflePairAsUNPCKAndPermute(), performCONDCombine(), llvm::AMDGPUTargetLowering::performFNegCombine(), PerformHWLoopCombine(), PerformLongShiftCombine(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), llvm::SelectionDAGISel::ReplaceNode(), llvm::SelectionDAGISel::ReplaceUses(), and SelectNodeTo().
RepositionNode()
void llvm::SelectionDAG::RepositionNode (allnodes_iterator Position, SDNode * N) inline
Move node N in the AllNodes list to be immediately before the given iterator Position.
This may be used to update the topological ordering when the list of nodes is modified.
Definition at line 1840 of file SelectionDAG.h.
References llvm::iplist_impl< simple_ilist< T, Options... >, ilist_traits< T > >::insert(), N, and llvm::iplist_impl< simple_ilist< T, Options... >, ilist_traits< T > >::remove().
Referenced by insertDAGNode().
salvageDebugInfo()
void SelectionDAG::salvageDebugInfo (SDNode & N)
To be invoked on an SDNode that is slated to be erased.
This function mirrors llvm::salvageDebugInfo.
Definition at line 10279 of file SelectionDAG.cpp.
References llvm::ISD::ADD, AddDbgValue(), llvm::DIExpression::appendOffset(), llvm::DIExpression::appendOpsToArg(), assert(), llvm::dbgs(), llvm::SDDbgOperand::fromNode(), getDbgValueList(), GetDbgValues(), llvm::SDValue::getNode(), llvm::SDValue::getResNo(), i, isConstantIntBuildVectorOrConstantInt(), LLVM_DEBUG, N, llvm::Offset, llvm::SDDbgOperand::SDNODE, and uint64_t.
Referenced by llvm::SelectionDAGISel::SelectCodeCommon().
SelectNodeTo() [1/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT)
These are used for target selectors to mutate the specified node to have the specified return type, Target opcode, and operands.
SelectNodeTo - These are wrappers around MorphNodeTo that accept a machine opcode.
Note that target opcodes are stored as ~TargetOpcode in the node opcode field. The resultant node is returned.
Definition at line 9738 of file SelectionDAG.cpp.
References getVTList(), and N.
Referenced by AMDGPUDAGToDAGISel::SelectBuildVector(), SelectNodeTo(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), and tryOrrWithShift().
SelectNodeTo() [2/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, ArrayRef< SDValue > Ops)
Definition at line 9767 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [3/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1)
Definition at line 9744 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [4/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2)
Definition at line 9751 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [5/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 9759 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [6/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2)
Definition at line 9779 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [7/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, ArrayRef< SDValue > Ops)
Definition at line 9773 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [8/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, EVT VT3, ArrayRef< SDValue > Ops)
Definition at line 9785 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [9/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, EVT VT1, EVT VT2, SDValue Op1, SDValue Op2)
Definition at line 9792 of file SelectionDAG.cpp.
References getVTList(), N, and SelectNodeTo().
SelectNodeTo() [10/10]
SDNode * SelectionDAG::SelectNodeTo (SDNode * N, unsigned MachineOpc, SDVTList VTs, ArrayRef< SDValue > Ops)
Definition at line 9800 of file SelectionDAG.cpp.
References MorphNodeTo(), N, RemoveDeadNode(), and ReplaceAllUsesWith().
setFlagInserter()
void llvm::SelectionDAG::setFlagInserter (FlagInserter * FI) inline
Definition at line 487 of file SelectionDAG.h.
Referenced by llvm::SelectionDAG::FlagInserter::~FlagInserter().
setFunctionLoweringInfo()
void llvm::SelectionDAG::setFunctionLoweringInfo (FunctionLoweringInfo * FuncInfo) inline
Definition at line 457 of file SelectionDAG.h.
setGraphAttrs()
void SelectionDAG::setGraphAttrs (const SDNode * N, const char * Attrs)
Set graph attributes for a node. (eg. "color=red".)
setGraphAttrs - Set graph attributes for a node.
(eg. "color=red".)
Definition at line 191 of file SelectionDAGPrinter.cpp.
References Attrs, llvm::errs(), and N.
setGraphColor()
void SelectionDAG::setGraphColor (const SDNode * N, const char * Color)
Convenience for setting node color attribute.
setGraphColor - Convenience for setting node color attribute.
Definition at line 221 of file SelectionDAGPrinter.cpp.
References llvm::errs(), and N.
setNodeMemRefs()
void SelectionDAG::setNodeMemRefs (MachineSDNode * N, ArrayRef< MachineMemOperand * > NewMemRefs)
Mutate the specified machine node's memory references to the provided list.
Definition at line 9714 of file SelectionDAG.cpp.
References llvm::copy(), llvm::ArrayRef< T >::empty(), N, and llvm::ArrayRef< T >::size().
Referenced by CloneNodeWithValues(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), ReplaceATOMIC_LOAD_128Results(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), llvm::HexagonDAGToDAGISel::SelectBrevLdIntrinsic(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectV65Gather(), llvm::HexagonDAGToDAGISel::SelectV65GatherPred(), and llvm::X86InstrInfo::unfoldMemoryOperand().
setRoot()
const SDValue& llvm::SelectionDAG::setRoot (SDValue N) inline
Set the current root tag of the SelectionDAG.
Definition at line 556 of file SelectionDAG.h.
References assert(), llvm::checkForCycles(), N, and llvm::MVT::Other.
Referenced by llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SelectionDAGBuilder::lowerInvokable(), llvm::RISCVDAGToDAGISel::PostprocessISelDAG(), ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), and llvm::SelectionDAGBuilder::visitSwitchCase().
setSubgraphColor()
void SelectionDAG::setSubgraphColor (SDNode * N, const char * Color)
Convenience for setting subgraph color attribute.
setSubgraphColor - Convenience for setting subgraph color attribute.
Definition at line 265 of file SelectionDAGPrinter.cpp.
References llvm::errs(), and N.
shouldOptForSize()
bool SelectionDAG::shouldOptForSize () const
Definition at line 1336 of file SelectionDAG.cpp.
References llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineFunction::getFunction(), llvm::Function::hasOptSize(), llvm::FunctionLoweringInfo::MBB, and llvm::shouldOptimizeForSize().
Referenced by combineX86ShuffleChain(), combineX86ShufflesConstants(), llvm::TargetLowering::expandDIVREMByConstant(), ExpandPowI(), getConstantPool(), LowerAndToBT(), lowerBUILD_VECTOR(), lowerBuildVectorAsBroadcast(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), LowerFunnelShift(), lowerShuffleAsBlend(), shouldLowerMemFuncForSize(), llvm::SelectionDAGISel::shouldOptForSize(), and shouldUseHorizontalOp().
SignBitIsZero()
bool SelectionDAG::SignBitIsZero (SDValue Op, unsigned Depth = 0) const
Return true if the sign bit of Op is known to be zero.
SignBitIsZero - Return true if the sign bit of Op is known to be zero.
We use this predicate to simplify operations downstream.
Definition at line 2551 of file SelectionDAG.cpp.
References llvm::BitWidth, llvm::Depth, llvm::APInt::getSignMask(), and MaskedValueIsZero().
Referenced by canReduceVMulWidth(), combineUIntToFP(), getCmp(), LowerVSETCC(), and selectUmullSmull().
simplifyFPBinop()
SDValue SelectionDAG::simplifyFPBinop (unsigned Opcode, SDValue X, SDValue Y, SDNodeFlags Flags)
Try to simplify a floating-point binary operation into 1 of its operands or a constant.
Definition at line 9151 of file SelectionDAG.cpp.
References llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FSUB, getConstantFP(), getUNDEF(), llvm::ConstantFPSDNode::getValueAPF(), llvm::isConstOrConstSplatFP(), llvm::APFloat::isExactlyValue(), llvm::APFloat::isInfinity(), llvm::APFloat::isNaN(), llvm::APFloat::isNegZero(), llvm::APFloat::isPosZero(), llvm::APFloat::isZero(), X, llvm::SystemZISD::XC, and Y.
Referenced by getNode().
simplifySelect()
SDValue SelectionDAG::simplifySelect (SDValue Cond, SDValue TVal, SDValue FVal)
Try to simplify a select/vselect into 1 of its operands or a constant.
Definition at line 9097 of file SelectionDAG.cpp.
References Cond, F, isConstantValueOfAnyType(), and llvm::isConstOrConstSplat().
Referenced by combineSelect(), and getNode().
simplifyShift()
SDValue SelectionDAG::simplifyShift (SDValue X, SDValue Y)
Try to simplify a shift into 1 of its operands or a constant.
Definition at line 9127 of file SelectionDAG.cpp.
References getConstant(), getUNDEF(), llvm::isNullOrNullSplat(), llvm::ISD::matchUnaryPredicate(), X, and Y.
Referenced by getNode().
SplitEVL()
std::pair< SDValue, SDValue > SelectionDAG::SplitEVL (SDValue N, EVT VecVT, const SDLoc & DL)
Split the explicit vector length parameter of a VP operation.
Definition at line 11687 of file SelectionDAG.cpp.
References assert(), DL, getConstant(), getNode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorElementCount(), llvm::EVT::getVectorMinNumElements(), getVScale(), llvm::EVT::isFixedLengthVector(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isKnownEven(), N, llvm::ISD::UMIN, and llvm::ISD::USUBSAT.
SplitVector() [1/2]
std::pair<SDValue, SDValue> llvm::SelectionDAG::SplitVector (const SDValue & N, const SDLoc & DL) inline
Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 2203 of file SelectionDAG.h.
References DL, GetSplitDestVTs(), N, and SplitVector().
SplitVector() [2/2]
std::pair< SDValue, SDValue > SelectionDAG::SplitVector (const SDValue & N, const SDLoc & DL, const EVT & LoVT, const EVT & HiVT)
Split the vector with EXTRACT_SUBVECTOR using the provides VTs and return the low/high part.
SplitVector - Split the vector with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 11666 of file SelectionDAG.cpp.
References assert(), DL, llvm::ISD::EXTRACT_SUBVECTOR, getNode(), getVectorIdxConstant(), llvm::EVT::getVectorMinNumElements(), llvm::EVT::isScalableVector(), and N.
Referenced by combineHorizOpWithShuffle(), combinePredicateReduction(), getPMOVMSKB(), isHorizontalBinOp(), LowerVectorAllZero(), ReplaceAddWithADDP(), llvm::X86TargetLowering::ReplaceNodeResults(), SplitVector(), and SplitVectorOperand().
SplitVectorOperand()
std::pair<SDValue, SDValue> llvm::SelectionDAG::SplitVectorOperand (const SDNode * N, unsigned OpNo) inline
Split the node's operand with EXTRACT_SUBVECTOR and return the low/high part.
Definition at line 2214 of file SelectionDAG.h.
References N, and SplitVector().
Referenced by LowerCVTPS2PH(), LowerTruncate(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceReductionResults(), llvm::SITargetLowering::splitBinaryVectorOp(), llvm::SITargetLowering::splitTernaryVectorOp(), and llvm::SITargetLowering::splitUnaryVectorOp().
transferDbgValues()
void SelectionDAG::transferDbgValues (SDValue From, SDValue To, unsigned OffsetInBits = 0, unsigned SizeInBits = 0, bool InvalidateDbg = true)
Transfer debug values from one node to another, while optionally generating fragment expressions for split-up values.
If InvalidateDbg is set, debug values are invalidated after they are transferred.
Definition at line 10197 of file SelectionDAG.cpp.
References AddDbgValue(), assert(), llvm::DIExpression::createFragmentExpression(), From, llvm::SDDbgOperand::fromNode(), getDbgValueList(), GetDbgValues(), llvm::SDNode::getHasDebugValue(), llvm::SDNode::getIROrder(), llvm::SDValue::getNode(), llvm::SDValue::getResNo(), llvm::is_contained(), and llvm::max().
Referenced by getNode(), ReplaceAllUsesOfValuesWith(), ReplaceAllUsesOfValueWith(), and ReplaceAllUsesWith().
UnrollVectorOp()
SDValue SelectionDAG::UnrollVectorOp (SDNode * N, unsigned ResNE = 0)
Utility function used by legalize and lowering to "unroll" a vector operation by splitting out the scalars and operating on each element individually.
If the ResNE is 0, fully unroll the vector op. If ResNE is less than the width of the vector op, unroll up to ResNE. If the ResNE is greater than the width of the vector op, unroll the vector op and fill the end of the resulting vector with UNDEFS.
Definition at line 11439 of file SelectionDAG.cpp.
References assert(), dl, llvm::numbers::e, llvm::ISD::EXTRACT_VECTOR_ELT, getBuildVector(), getContext(), getNode(), getShiftAmountOperand(), getUNDEF(), llvm::SDValue::getValueType(), getValueType(), llvm::EVT::getVectorElementType(), getVectorIdxConstant(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), i, llvm::EVT::isVector(), j(), N, llvm::AArch64CC::NE, Operands, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SELECT, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::ISD::VSELECT.
Referenced by LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), and unrollVectorShift().
UnrollVectorOverflowOp()
std::pair< SDValue, SDValue > SelectionDAG::UnrollVectorOverflowOp (SDNode * N, unsigned ResNE = 0)
Like UnrollVectorOp(), but for the [US](ADD|SUB|MUL)O family of opcodes.
This is a separate function because those opcodes have two results.
Definition at line 11507 of file SelectionDAG.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), dl, ExtractVectorElements(), getBoolConstant(), getBuildVector(), getConstant(), getContext(), getDataLayout(), getNode(), getSelect(), llvm::TargetLoweringBase::getSetCCResultType(), getUNDEF(), llvm::SDValue::getValue(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), getVTList(), i, N, llvm::AArch64CC::NE, llvm::ISD::SADDO, llvm::ISD::SMULO, llvm::ISD::SSUBO, llvm::ISD::UADDO, llvm::ISD::UMULO, and llvm::ISD::USUBO.
updateDivergence()
void SelectionDAG::updateDivergence (SDNode * N)
Definition at line 10653 of file SelectionDAG.cpp.
References llvm::append_range(), calculateDivergence(), N, and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by ReplaceAllUsesOfValueWith(), ReplaceAllUsesWith(), and UpdateNodeOperands().
UpdateNodeOperands() [1/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, ArrayRef< SDValue > Ops)
Definition at line 9673 of file SelectionDAG.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::lltok::equal, i, N, llvm::ArrayRef< T >::size(), and updateDivergence().
UpdateNodeOperands() [2/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op)
Mutate the specified node in-place to have the specified operands.
UpdateNodeOperands - Mutate the specified node in-place to have the specified operands.
If the resultant node already exists in the DAG, this does not modify the specified node, instead it returns the node that already exists. If the resultant node does not exist in the DAG, the input node is returned. As a degenerate case, if you specify the same input operands as the node already has, the input node is returned.
Definition at line 9598 of file SelectionDAG.cpp.
References assert(), N, and updateDivergence().
Referenced by makeEquivalentMemoryOrdering(), moveBelowOrigChain(), llvm::PPCTargetLowering::PerformDAGCombine(), and UpdateNodeOperands().
UpdateNodeOperands() [3/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2)
Definition at line 9623 of file SelectionDAG.cpp.
References assert(), N, and updateDivergence().
UpdateNodeOperands() [4/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3)
Definition at line 9653 of file SelectionDAG.cpp.
References N, and UpdateNodeOperands().
UpdateNodeOperands() [5/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4)
Definition at line 9659 of file SelectionDAG.cpp.
References N, and UpdateNodeOperands().
UpdateNodeOperands() [6/6]
SDNode * SelectionDAG::UpdateNodeOperands (SDNode * N, SDValue Op1, SDValue Op2, SDValue Op3, SDValue Op4, SDValue Op5)
Definition at line 9666 of file SelectionDAG.cpp.
References N, and UpdateNodeOperands().
VerifyDAGDivergence()
void SelectionDAG::VerifyDAGDivergence ()
Definition at line 10685 of file SelectionDAG.cpp.
References assert(), calculateDivergence(), and N.
viewGraph() [1/2]
void SelectionDAG::viewGraph ()
Definition at line 159 of file SelectionDAGPrinter.cpp.
viewGraph() [2/2]
void SelectionDAG::viewGraph (const std::string & Title)
Pop up a GraphViz/gv window with the DAG rendered using 'dot'.
viewGraph - Pop up a ghostview window with the reachable parts of the DAG rendered using 'dot'.
Definition at line 146 of file SelectionDAGPrinter.cpp.
References llvm::errs(), getMachineFunction(), getName(), and llvm::ViewGraph().
WidenVector()
SDValue SelectionDAG::WidenVector (const SDValue & N, const SDLoc & DL)
Widen the vector up to the next power of two using INSERT_SUBVECTOR.
Definition at line 11705 of file SelectionDAG.cpp.
References DL, getContext(), getNode(), getUNDEF(), llvm::EVT::getVectorElementType(), getVectorIdxConstant(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::ISD::INSERT_SUBVECTOR, N, and llvm::NextPowerOf2().
Friends And Related Function Documentation
DAGUpdateListener
friend struct DAGUpdateListener friend
DAGUpdateListener is a friend so it can manipulate the listener stack.
Definition at line 387 of file SelectionDAG.h.
Member Data Documentation
AAInfo
const SDLoc SDValue SDValue MachinePointerInfo unsigned MachineMemOperand::Flags const AAMDNodes& llvm::SelectionDAG::AAInfo = AAMDNodes()
Definition at line 1313 of file SelectionDAG.h.
Referenced by getExtLoad(), getExtLoadVP(), getExtStridedLoadVP(), getLoad(), getLoadVP(), getMemcpy(), getMemIntrinsicNode(), getMemmove(), getMemset(), getStore(), getStridedLoadVP(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), and LLVM_DEPRECATED().
Alignment
const SDLoc SDValue SDValue MachinePointerInfo unsigned llvm::SelectionDAG::Alignment
Definition at line 1311 of file SelectionDAG.h.
Referenced by CreateStackTemporary(), getConstantPool(), getExtLoad(), getExtLoadVP(), getExtStridedLoadVP(), getLoad(), getLoadVP(), getMemcpy(), getMemIntrinsicNode(), getMemmove(), getMemset(), getStore(), getStridedLoadVP(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), and LLVM_DEPRECATED().
Chain
const SDLoc SDValue llvm::SelectionDAG::Chain
Definition at line 1310 of file SelectionDAG.h.
Referenced by getAtomic(), getAtomicCmpSwap(), getCALLSEQ_END(), getCALLSEQ_START(), getCopyFromReg(), getCopyToReg(), getExtLoad(), getExtLoadVP(), getExtStridedLoadVP(), getLifetimeNode(), getLoad(), getLoadVP(), getMaskedLoad(), getMaskedStore(), getMemcpy(), getMemmove(), getMemset(), getPseudoProbeNode(), getSetCC(), getStackArgumentTokenFactor(), getStore(), getStoreVP(), getStrictFPExtendOrRound(), getStridedLoadVP(), getStridedStoreVP(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), getVAArg(), and LLVM_DEPRECATED().
dl
const SDLoc& llvm::SelectionDAG::dl
Definition at line 1310 of file SelectionDAG.h.
Referenced by FoldSetCC(), getAddrSpaceCast(), getAtomic(), getAtomicCmpSwap(), getCopyFromReg(), getCopyToReg(), getEHLabel(), getExtLoad(), getExtLoadVP(), getGatherVP(), getIndexedLoad(), getIndexedLoadVP(), getIndexedMaskedLoad(), getIndexedMaskedStore(), getIndexedStore(), getIndexedStoreVP(), getLabelNode(), getLifetimeNode(), getLoad(), getLoadVP(), getMachineNode(), getMaskedGather(), getMaskedLoad(), getMaskedScatter(), getMaskedStore(), getMemcpy(), getMemIntrinsicNode(), getMemmove(), getMemset(), getMergeValues(), getScatterVP(), getStore(), getStoreVP(), getTruncStore(), getTruncStoreVP(), getVAArg(), getVectorShuffle(), LLVM_DEPRECATED(), UnrollVectorOp(), and UnrollVectorOverflowOp().
MaxRecursionDepth
constexpr unsigned llvm::SelectionDAG::MaxRecursionDepth = 6 static constexpr
Definition at line 444 of file SelectionDAG.h.
Referenced by computeKnownBits(), ComputeNumSignBits(), llvm::PPCTargetLowering::getNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), getShuffleScalarElt(), getTargetShuffleInputs(), getUsefulBits(), isFNEG(), isGuaranteedNotToBeUndefOrPoison(), isKnownNeverNaN(), isSplatValue(), PromoteMaskArithmetic(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifyDemandedVectorElts(), and llvm::TargetLowering::SimplifyMultipleUseDemandedBits().
MMOFlags
const SDLoc SDValue SDValue MachinePointerInfo unsigned MachineMemOperand::Flags llvm::SelectionDAG::MMOFlags = MachineMemOperand::MONone
Definition at line 1312 of file SelectionDAG.h.
Referenced by getExtLoad(), getExtLoadVP(), getExtStridedLoadVP(), getIndexedLoad(), getIndexedLoadVP(), getIndexedStridedLoadVP(), getLoad(), getLoadVP(), getStore(), getStridedLoadVP(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), and LLVM_DEPRECATED().
NewNodesMustHaveLegalTypes
bool llvm::SelectionDAG::NewNodesMustHaveLegalTypes = false
When true, additional steps are taken to ensure that getConstant() and similar functions return DAG nodes that have legal types.
This is important after type legalization since any illegally typed nodes generated after this point will not experience type legalization.
Definition at line 383 of file SelectionDAG.h.
Referenced by FoldConstantArithmetic(), getConstant(), and getNode().
Ptr
const SDLoc SDValue SDValue llvm::SelectionDAG::Ptr
Definition at line 1310 of file SelectionDAG.h.
Referenced by getAddrSpaceCast(), getAtomic(), getAtomicCmpSwap(), getExtLoad(), getExtLoadVP(), getExtStridedLoadVP(), getLoad(), getLoadVP(), getMemBasePlusOffset(), getObjectPtrOffset(), getStore(), getStoreVP(), getStridedLoadVP(), getStridedStoreVP(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), getVAArg(), InferPtrAlign(), and LLVM_DEPRECATED().
PtrInfo
const SDLoc SDValue SDValue MachinePointerInfo llvm::SelectionDAG::PtrInfo
Definition at line 1311 of file SelectionDAG.h.
Referenced by getExtLoad(), getExtLoadVP(), getExtStridedLoadVP(), getLoad(), getLoadVP(), getMemIntrinsicNode(), getStore(), getStridedLoadVP(), getTruncStore(), getTruncStoreVP(), getTruncStridedStoreVP(), and LLVM_DEPRECATED().
Ranges
const SDLoc SDValue SDValue MachinePointerInfo unsigned MachineMemOperand::Flags const AAMDNodes const MDNode* llvm::SelectionDAG::Ranges
Initial value:
= nullptr) {
    return getLoad(VT, dl, Chain, Ptr, PtrInfo, MaybeAlign(Alignment), MMOFlags,
                   AAInfo, Ranges);
  }
  SDValue getLoad(EVT VT, const SDLoc &dl, SDValue Chain, SDValue Ptr,
                  MachineMemOperand *MMO)
Definition at line 1314 of file SelectionDAG.h.
Referenced by computeKnownBits(), ComputeNumSignBits(), getLoad(), getLoadVP(), getStridedLoadVP(), and LLVM_DEPRECATED().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SelectionDAG.h
lib/CodeGen/SelectionDAG/DAGCombiner.cpp
lib/CodeGen/SelectionDAG/LegalizeDAG.cpp
lib/CodeGen/SelectionDAG/LegalizeTypes.cpp
lib/CodeGen/SelectionDAG/LegalizeVectorOps.cpp
lib/CodeGen/SelectionDAG/SelectionDAG.cpp
lib/CodeGen/SelectionDAG/SelectionDAGDumper.cpp
lib/CodeGen/SelectionDAG/SelectionDAGPrinter.cpp