LLVM: llvm::memprof::RecordWriterTrait Class Reference
llvm::memprof::RecordWriterTrait Class Reference
#include "llvm/ProfileData/MemProf.h"
Public Types
using key_type = uint64_t
using key_type_ref = uint64_t
using data_type = IndexedMemProfRecord
using data_type_ref = IndexedMemProfRecord &
using hash_value_type = uint64_t
using offset_type = uint64_t
Public Member Functions
RecordWriterTrait ()=default
void EmitKey (raw_ostream &Out, key_type_ref K, offset_type)
void EmitData (raw_ostream &Out, key_type_ref, data_type_ref V, offset_type)
Static Public Member Functions
static hash_value_type ComputeHash (key_type_ref K)
static std::pair< offset_type, offset_type > EmitKeyDataLength (raw_ostream &Out, key_type_ref K, data_type_ref V)
Public Attributes
MemProfSchema * Schema = nullptr
Detailed Description
Definition at line 493 of file MemProf.h.
Member Typedef Documentation
data_type
using llvm::memprof::RecordWriterTrait::data_type = IndexedMemProfRecord
Definition at line 498 of file MemProf.h.
data_type_ref
using llvm::memprof::RecordWriterTrait::data_type_ref = IndexedMemProfRecord &
Definition at line 499 of file MemProf.h.
hash_value_type
using llvm::memprof::RecordWriterTrait::hash_value_type = uint64_t
Definition at line 501 of file MemProf.h.
key_type
using llvm::memprof::RecordWriterTrait::key_type = uint64_t
Definition at line 495 of file MemProf.h.
key_type_ref
using llvm::memprof::RecordWriterTrait::key_type_ref = uint64_t
Definition at line 496 of file MemProf.h.
offset_type
using llvm::memprof::RecordWriterTrait::offset_type = uint64_t
Definition at line 502 of file MemProf.h.
Constructor & Destructor Documentation
RecordWriterTrait()
llvm::memprof::RecordWriterTrait::RecordWriterTrait () default
Member Function Documentation
ComputeHash()
static hash_value_type llvm::memprof::RecordWriterTrait::ComputeHash (key_type_ref K) inline static
Definition at line 511 of file MemProf.h.
EmitData()
void llvm::memprof::RecordWriterTrait::EmitData (raw_ostream & Out, key_type_ref , data_type_ref V, offset_type) inline
Definition at line 531 of file MemProf.h.
References assert(), and llvm::memprof::IndexedMemProfRecord::serialize().
EmitKey()
void llvm::memprof::RecordWriterTrait::EmitKey (raw_ostream & Out, key_type_ref K, offset_type) inline
Definition at line 525 of file MemProf.h.
References llvm::AArch64CC::LE, llvm::support::little, support(), and uint64_t.
EmitKeyDataLength()
static std::pair<offset_type, offset_type> llvm::memprof::RecordWriterTrait::EmitKeyDataLength (raw_ostream & Out, key_type_ref K, data_type_ref V) inline static
Definition at line 514 of file MemProf.h.
References llvm::AArch64CC::LE, llvm::support::little, M, N, llvm::memprof::IndexedMemProfRecord::serializedSize(), and support().
Member Data Documentation
Schema
MemProfSchema* llvm::memprof::RecordWriterTrait::Schema = nullptr
Definition at line 507 of file MemProf.h.
The documentation for this class was generated from the following file:
include/llvm/ProfileData/MemProf.h