LLVM: llvm::mca::CycleSegment Class Reference
llvm::mca::CycleSegment Class Reference
A sequence of cycles.
#include "llvm/MCA/Instruction.h"
Public Member Functions
CycleSegment (unsigned StartCycle, unsigned EndCycle, bool IsReserved=false)
bool contains (unsigned Cycle) const
bool startsAfter (const CycleSegment &CS) const
bool endsBefore (const CycleSegment &CS) const
bool overlaps (const CycleSegment &CS) const
bool isExecuting () const
bool isExecuted () const
bool operator< (const CycleSegment &Other) const
CycleSegment & operator-- ()
bool isValid () const
unsigned size () const
void subtract (unsigned Cycles)
unsigned begin () const
unsigned end () const
void setEnd (unsigned NewEnd)
bool isReserved () const
void setReserved ()
Detailed Description
A sequence of cycles.
This class can be used as a building block to construct ranges of cycles.
Definition at line 389 of file Instruction.h.
Constructor & Destructor Documentation
CycleSegment()
llvm::mca::CycleSegment::CycleSegment (unsigned StartCycle, unsigned EndCycle, bool IsReserved = false) inline
Definition at line 395 of file Instruction.h.
References llvm::Reserved.
Member Function Documentation
begin()
unsigned llvm::mca::CycleSegment::begin () const inline
Definition at line 424 of file Instruction.h.
Referenced by llvm::mca::ResourceManager::issueInstruction().
contains()
bool llvm::mca::CycleSegment::contains (unsigned Cycle) const inline
Definition at line 398 of file Instruction.h.
end()
unsigned llvm::mca::CycleSegment::end () const inline
Definition at line 425 of file Instruction.h.
endsBefore()
bool llvm::mca::CycleSegment::endsBefore (const CycleSegment & CS) const inline
Definition at line 400 of file Instruction.h.
Referenced by overlaps().
isExecuted()
bool llvm::mca::CycleSegment::isExecuted () const inline
Definition at line 405 of file Instruction.h.
isExecuting()
bool llvm::mca::CycleSegment::isExecuting () const inline
Definition at line 404 of file Instruction.h.
isReserved()
bool llvm::mca::CycleSegment::isReserved () const inline
Definition at line 427 of file Instruction.h.
References llvm::Reserved.
Referenced by llvm::mca::ResourceUsage::isReserved().
isValid()
bool llvm::mca::CycleSegment::isValid () const inline
Definition at line 417 of file Instruction.h.
operator--()
CycleSegment& llvm::mca::CycleSegment::operator-- () inline
Definition at line 409 of file Instruction.h.
operator<()
bool llvm::mca::CycleSegment::operator< (const CycleSegment & Other) const inline
Definition at line 406 of file Instruction.h.
References Other.
overlaps()
bool llvm::mca::CycleSegment::overlaps (const CycleSegment & CS) const inline
Definition at line 401 of file Instruction.h.
References endsBefore(), and startsAfter().
setEnd()
void llvm::mca::CycleSegment::setEnd (unsigned NewEnd) inline
Definition at line 426 of file Instruction.h.
setReserved()
void llvm::mca::CycleSegment::setReserved () inline
Definition at line 428 of file Instruction.h.
References llvm::Reserved.
Referenced by llvm::mca::ResourceUsage::setReserved().
size()
unsigned llvm::mca::CycleSegment::size () const inline
Definition at line 418 of file Instruction.h.
Referenced by llvm::mca::ResourceManager::issueInstruction(), and llvm::mca::ResourceUsage::size().
startsAfter()
bool llvm::mca::CycleSegment::startsAfter (const CycleSegment & CS) const inline
Definition at line 399 of file Instruction.h.
Referenced by overlaps().
subtract()
void llvm::mca::CycleSegment::subtract (unsigned Cycles) inline
Definition at line 419 of file Instruction.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/MCA/Instruction.h