LLVM: llvm::MDNode Class Reference
llvm::MDNode Class Reference
Metadata node.
#include "llvm/IR/Metadata.h"
Classes
struct HasCachedHash
Public Types
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Protected Types
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Friends
class ReplaceableMetadataImpl
class LLVMContextImpl
class DIArgList
Additional Inherited Members
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Metadata node.
Metadata nodes can be uniqued, like constants, or distinct. Temporary metadata nodes (with full support for RAUW) can be used to delay uniquing until forward references are known. The basic metadata node is an MDTuple.
There is limited support for RAUW at construction time. At construction time, if any operand is a temporary node (or an unresolved uniqued node, which indicates a transitive temporary operand), the node itself will be unresolved. As soon as all operands become resolved, it will drop RAUW support permanently.
If an unresolved node is part of a cycle, resolveCycles() needs to be called on some member of the cycle once all temporary nodes have been replaced.
MDNodes can be large or small, as well as resizable or non-resizable. Large MDNodes' operands are allocated in a separate storage vector, whereas small MDNodes' operands are co-allocated. Distinct and temporary MDnodes are resizable, but only MDTuples support this capability.
Clients can add operands to resizable MDNodes using push_back().
Definition at line 943 of file Metadata.h.
Member Typedef Documentation
mutable_op_range
using llvm::MDNode::mutable_op_range = iterator_range<MDOperand *> protected
Definition at line 1079 of file Metadata.h.
op_iterator
using llvm::MDNode::op_iterator = const MDOperand *
Definition at line 1278 of file Metadata.h.
op_range
using llvm::MDNode::op_range = iterator_range<op_iterator>
Definition at line 1279 of file Metadata.h.
Constructor & Destructor Documentation
MDNode() [1/2]
MDNode::MDNode (LLVMContext & Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2 = std::nullopt) protected
Definition at line 541 of file Metadata.cpp.
References isUniqued(), and setOperand().
~MDNode()
llvm::MDNode::~MDNode () protected default
MDNode() [2/2]
llvm::MDNode::MDNode (const MDNode &) delete
Member Function Documentation
classof()
static bool llvm::MDNode::classof (const Metadata * MD) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 1300 of file Metadata.h.
References llvm::Metadata::getMetadataID().
clone()
TempMDNode MDNode::clone () const
Create a (temporary) clone of this.
Definition at line 558 of file Metadata.cpp.
References llvm::Metadata::getMetadataID(), and llvm_unreachable.
Referenced by llvm::DIType::clone(), and llvm::DILocalScope::cloneScopeForSubprogram().
concatenate()
MDNode * MDNode::concatenate (MDNode * A, MDNode * B) static
Methods for metadata merging.
Definition at line 1005 of file Metadata.cpp.
References B, llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::getArrayRef(), getOrSelfReference(), and llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert().
Referenced by AddAliasScopeMetadata(), llvm::LoopVersioning::annotateInstWithNoAlias(), PropagateCallSiteMetadata(), and propagateMemProfHelper().
deleteTemporary()
void MDNode::deleteTemporary (MDNode * N) static
Deallocate a node created by getTemporary.
Calls replaceAllUsesWith(nullptr) before deleting, so any remaining references will be reset.
Definition at line 940 of file Metadata.cpp.
References assert(), and N.
Referenced by LLVMDisposeTemporaryMDNode(), and llvm::TempMDNodeDeleter::operator()().
dropAllReferences()
void MDNode::dropAllReferences () protected
Definition at line 798 of file Metadata.cpp.
References Context, E, getNumOperands(), I, and setOperand().
dumpTree() [1/2]
LLVM_DUMP_METHOD void MDNode::dumpTree () const
User-friendly dump in tree shape.
If M is provided, metadata nodes will be numbered canonically; otherwise, pointer addresses are substituted.
Note: this uses an explicit overload instead of default arguments so that the nullptr version is easy to call from a debugger.
Definition at line 4973 of file AsmWriter.cpp.
dumpTree() [2/2]
LLVM_DUMP_METHOD void MDNode::dumpTree (const Module * M) const
Definition at line 4976 of file AsmWriter.cpp.
References llvm::dbgs(), M, and printTree().
get()
MDTuple * llvm::MDNode::get (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 1399 of file Metadata.h.
References Context, and llvm::MDTuple::get().
Referenced by llvm::adaptNoAliasScopes(), AddAliasScopeMetadata(), llvm::Module::addModuleFlag(), addModuleFlags(), AddRuntimeUnrollDisableMetaData(), llvm::DbgVariableIntrinsic::addVariableLocationOps(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::annotateValueSite(), llvm::DIExpression::append(), llvm::DIExpression::appendOpsToArg(), llvm::OpenMPIRBuilder::applySimd(), llvm::avoidZeroOffsetLandingPad(), llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata(), llvm::memprof::buildCallstackMetadata(), canonicalizeMetadataForValue(), llvm::DILocation::cloneWithDiscriminator(), collectCallSiteParameters(), llvm::DIExpression::constantFold(), llvm::DIExpression::convertToNonVariadicExpression(), llvm::DIExpression::convertToUndefExpression(), llvm::DIExpression::convertToVariadicExpression(), llvm::GlobalObject::copyMetadata(), llvm::copyRangeMetadata(), createAccessTag(), llvm::MDBuilder::createAliasScope(), llvm::MDBuilder::createAliasScopeDomain(), llvm::DIBuilder::createArrayType(), llvm::DIBuilder::createBasicType(), llvm::DIBuilder::createBitFieldMemberType(), llvm::MDBuilder::createBranchWeights(), llvm::MDBuilder::createCallbackEncoding(), llvm::MDBuilder::createCallees(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCommonBlock(), llvm::DIBuilder::createConstantValueExpression(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createExpression(), llvm::DIBuilder::createFile(), llvm::DIBuilder::createForwardDecl(), llvm::MDBuilder::createFPMath(), llvm::DIExpression::createFragmentExpression(), llvm::DIBuilder::createFriend(), llvm::MDBuilder::createFunctionEntryCount(), llvm::MDBuilder::createFunctionSectionPrefix(), llvm::DIBuilder::createGlobalVariableExpression(), createImportedModule(), llvm::DIBuilder::createInheritance(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::DIBuilder::createLexicalBlockFile(), llvm::MDBuilder::createLLVMStats(), llvm::DIBuilder::createMacro(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::createMemCpyLoopKnownSize(), createMIBNode(), llvm::DIBuilder::createModule(), llvm::DIBuilder::createNameSpace(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createObjCProperty(), llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), llvm::OpenMPIRBuilder::createOffloadEntry(), llvm::OpenMPIRBuilder::createParallel(), llvm::createPGOFuncNameMetadata(), llvm::DIBuilder::createPointerType(), llvm::MDBuilder::createPseudoProbeDesc(), llvm::DIBuilder::createQualifiedType(), llvm::MDBuilder::createRange(), llvm::DIBuilder::createReferenceType(), llvm::MDBuilder::createRTTIPointerPrologue(), llvm::DIBuilder::createSetType(), llvm::DIBuilder::createStaticMemberType(), createStringMetadata(), llvm::DIBuilder::createStringType(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createSubroutineType(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAARoot(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), llvm::DIBuilder::createTemplateParameterPack(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::MDBuilder::createUnpredictable(), llvm::DIBuilder::createUnspecifiedType(), llvm::DIBuilder::createVariantMemberType(), llvm::DIBuilder::createVariantPart(), llvm::DIBuilder::createVectorType(), llvm::MipsInstrInfo::describeLoadedValue(), llvm::X86InstrInfo::describeLoadedValue(), llvm::TargetInstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), describeORRLoadedValue(), DisableAllLoopOptsOnLoop(), llvm::Instruction::dropLocation(), llvm::embedBufferInModule(), emitDbgAssign(), TransferTracker::emitMOLoc(), llvm::InstrumentationIRBuilder::ensureDebugInfo(), llvm::AAMDNodes::extendToTBAA(), llvm::DIExpression::extractAddressClass(), extractMDNode(), llvm::DIBuilder::finalize(), llvm::DIBuilder::finalizeSubprogram(), fixupDebugInfoPostExtraction(), foldCtpop(), foldCttzCtlz(), llvm::hlsl::FrontendResource::FrontendResource(), llvm::getDebugValueLoc(), llvm::DebugLoc::getFnDebugLoc(), llvm::DILocation::getMergedLocation(), getMostGenericRange(), getOrCreateDebugLoc(), llvm::DIBuilder::getOrCreateGenericSubrange(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), llvm::DIBuilder::getOrCreateSubrange(), llvm::DIBuilder::getOrCreateTypeArray(), getOrSelfReference(), getSubprogram(), INITIALIZE_PASS(), injectPendingInvariantConditions(), inlineDebugLoc(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::SampleProfileProber::instrumentOneFunc(), interpretValues(), LLVMDIBuilderCreateDebugLocation(), LLVMMDNodeInContext(), LLVMMDNodeInContext2(), llvm::makeFollowupLoopID(), llvm::MDBuilder::mergeCallbackEncodings(), moveFunctionData(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::DIExpression::prependOpcodes(), llvm::DIExpression::replaceArg(), llvm::DebugLoc::replaceInlinedAtSubprogram(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), restorePreTransformState(), llvm::SimpleLoopUnswitchPass::run(), runOnFunction(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::setKCFIType(), llvm::Loop::setLoopAlreadyUnrolled(), llvm::Loop::setLoopMustProgress(), llvm::GlobalObject::setVCallVisibilityMetadata(), llvm::AAMDNodes::shiftTBAAStruct(), shortenAssignment(), splitGlobal(), stripLoopMDLoc(), llvm::Instruction::swapProfMetadata(), transferSRADebugInfo(), TryToShrinkGlobalToBoolean(), llvm::uniteAccessGroups(), llvm::OpenMPIRBuilder::unrollLoopFull(), llvm::OpenMPIRBuilder::unrollLoopHeuristic(), llvm::OpenMPIRBuilder::unrollLoopPartial(), llvm::dxil::ValidatorVersionMD::update(), updateDVIWithLocations(), llvm::CallInst::updateProfWeight(), llvm::InstCombinerImpl::visitCallInst(), and llvm::dxil::Resources::write().
getContext()
LLVMContext& llvm::MDNode::getContext () const inline
Definition at line 1107 of file Metadata.h.
References Context.
Referenced by llvm::DIExpression::append(), llvm::DIExpression::appendOpsToArg(), llvm::DILocation::cloneWithDiscriminator(), llvm::DIExpression::constantFold(), llvm::DIExpression::convertToNonVariadicExpression(), llvm::DIExpression::convertToUndefExpression(), llvm::DIExpression::convertToVariadicExpression(), createAccessTag(), llvm::DIExpression::createFragmentExpression(), LiveDebugValues::MLocTracker::emitLoc(), TransferTracker::emitMOLoc(), llvm::AAMDNodes::extendToTBAA(), llvm::DIExpression::extractAddressClass(), llvm::DILocation::getMergedLocation(), getOrCreateDebugLoc(), llvm::makeFollowupLoopID(), llvm::DIExpression::prependOpcodes(), llvm::at::RAUW(), llvm::DIExpression::replaceArg(), llvm::DbgVariableIntrinsic::setVariable(), llvm::AAMDNodes::shiftTBAAStruct(), storeDistinctInContext(), llvm::Instruction::swapProfMetadata(), transferSRADebugInfo(), llvm::uniteAccessGroups(), updateLoopMetadataDebugLocationsImpl(), and llvm::UpgradeTBAANode().
getDistinct()
MDTuple * llvm::MDNode::getDistinct (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 1407 of file Metadata.h.
References Context, and llvm::MDTuple::getDistinct().
Referenced by addBasicBlockMetadata(), llvm::DebugLoc::appendInlinedAt(), llvm::OpenMPIRBuilder::applySimd(), llvm::DICompositeType::buildODRType(), llvm::MDBuilder::createAnonymousAARoot(), llvm::DIBuilder::createCompileUnit(), llvm::DIBuilder::createGlobalVariableExpression(), llvm::DIBuilder::createLexicalBlock(), fixupLineNumbers(), getSubprogram(), llvm::makePostTransformationMetadata(), stripLoopMDLoc(), and updateLoopMetadataDebugLocationsImpl().
getIfExists()
MDTuple * llvm::MDNode::getIfExists (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 1403 of file Metadata.h.
References Context, and llvm::MDTuple::getIfExists().
getMostGenericAliasScope()
MDNode * MDNode::getMostGenericAliasScope (MDNode * A, MDNode * B) static
Definition at line 1032 of file Metadata.cpp.
References B, llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::empty(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::getArrayRef(), getDomain(), getOrSelfReference(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by llvm::combineMetadata(), llvm::AAMDNodes::concat(), llvm::AAMDNodes::merge(), and llvm::propagateMetadata().
getMostGenericAlignmentOrDereferenceable()
MDNode * MDNode::getMostGenericAlignmentOrDereferenceable (MDNode * A, MDNode * B) static
Definition at line 1184 of file Metadata.cpp.
References B, and llvm::ConstantInt::getZExtValue().
Referenced by llvm::combineMetadata().
getMostGenericFPMath()
MDNode * MDNode::getMostGenericFPMath (MDNode * A, MDNode * B) static
Definition at line 1064 of file Metadata.cpp.
References B.
Referenced by llvm::combineMetadata(), and llvm::propagateMetadata().
getMostGenericRange()
MDNode * MDNode::getMostGenericRange (MDNode * A, MDNode * B) static
Definition at line 1112 of file Metadata.cpp.
References addRange(), B, llvm::ConstantAsMetadata::get(), get(), llvm::ConstantInt::getValue(), i, I, llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorImpl< T >::resize(), llvm::APInt::slt(), and tryMergeRange().
Referenced by llvm::combineMetadata().
getMostGenericTBAA()
MDNode * MDNode::getMostGenericTBAA (MDNode * A, MDNode * B) static
Definition at line 477 of file TypeBasedAliasAnalysis.cpp.
References B, and matchAccessTags().
Referenced by llvm::combineMetadata(), llvm::AAMDNodes::merge(), and llvm::propagateMetadata().
getNumOperands()
unsigned llvm::MDNode::getNumOperands () const inline
Return number of MDNode operands.
Definition at line 1297 of file Metadata.h.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), llvm::memprof::CallStackTrie::addCallStack(), AddRuntimeUnrollDisableMetaData(), llvm::addStringMetadataToLoop(), addToAccessGroupList(), llvm::cacheAnnotationFromMD(), createAccessTag(), dropAllReferences(), llvm::MachineInstr::emitError(), llvm::extractProfTotalWeight(), llvm::findOptionMDForLoopID(), llvm::findStringMetadataForLoop(), GetBranchWeights(), getConstInt(), llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes(), llvm::ProfileSummary::getFromMD(), getLocCookie(), llvm::Loop::getLoopID(), llvm::memprof::getMIBAllocType(), llvm::memprof::getMIBStackNode(), llvm::GenericDINode::getNumDwarfOperands(), getOperand(), llvm::getOptionalBoolLoopAttribute(), getOptionalVal(), llvm::DILocation::getRawInlinedAt(), getSummaryFromMD(), llvm::GetUnrollMetadata(), llvm::getValidBranchWeightMDNode(), getValMD(), llvm::getValueProfDataFromInst(), haveCommonPrefix(), llvm::SwitchInstProfUpdateWrapper::init(), llvm::intersectAccessGroups(), isKeyValuePair(), AliasScopeTracker::isNoAliasScopeDeclDead(), IsRootTBAANode(), IsScalarTBAANodeImpl(), isStructPathTBAA(), isTBAAVtableAccess(), llvm::Module::isValidModuleFlag(), llvm::makeFollowupLoopID(), llvm::makePostTransformationMetadata(), llvm::MDBuilder::mergeCallbackEncodings(), llvm::MDTuple::pop_back(), propagateMemProfHelper(), llvm::MDTuple::push_back(), llvm::Loop::setLoopID(), setOperand(), llvm::AAMDNodes::shiftTBAAStruct(), llvm::Instruction::swapProfMetadata(), unrollAndJamCountPragmaValue(), unrollCountPragmaValue(), updateLoopMetadataDebugLocationsImpl(), llvm::UpgradeTBAANode(), and llvm::TBAAVerifier::visitTBAAMetadata().
getNumUnresolved()
unsigned llvm::MDNode::getNumUnresolved () const inline protected
Definition at line 1217 of file Metadata.h.
Referenced by isResolved(), and storeDistinctInContext().
getOperand()
const MDOperand& llvm::MDNode::getOperand (unsigned I) const inline
Definition at line 1291 of file Metadata.h.
References assert(), getNumOperands(), and I.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), AccessQualFromMD(), llvm::DwarfUnit::addAnnotation(), AddRuntimeUnrollDisableMetaData(), ArgTypeFromMD(), llvm::cacheAnnotationFromMD(), llvm::MDBuilder::createMutableTBAAAccessTag(), llvm::MachineInstr::emitError(), llvm::AsmPrinter::emitPCSections(), llvm::extractProfTotalWeight(), llvm::findOptionMDForLoopID(), llvm::findStringMetadataForLoop(), GetBranchWeights(), llvm::AbstractCallSite::getCallbackUses(), getConstInt(), llvm::GenericDINode::getDwarfOperand(), llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes(), llvm::Function::getEntryCount(), llvm::FPMathOperator::getFPAccuracy(), llvm::ProfileSummary::getFromMD(), llvm::hlsl::FrontendResource::getGlobalVariable(), getLinkedToSymbol(), getLocCookie(), llvm::Loop::getLoopID(), llvm::memprof::getMIBAllocType(), llvm::memprof::getMIBStackNode(), llvm::DINode::getOperandAs(), llvm::DIMacroNode::getOperandAs(), llvm::getOptionalBoolLoopAttribute(), getOptionalVal(), getOriginalFunctionType(), llvm::DICompositeType::getRawAllocated(), llvm::DICompositeType::getRawAnnotations(), llvm::DIGlobalVariable::getRawAnnotations(), llvm::DILocalVariable::getRawAnnotations(), llvm::DICompositeType::getRawAssociated(), llvm::DICompositeType::getRawBaseType(), llvm::DIGenericSubrange::getRawCountNode(), llvm::DICompositeType::getRawDataLocation(), llvm::DICommonBlock::getRawDecl(), llvm::DICompositeType::getRawDiscriminator(), llvm::DICompositeType::getRawElements(), llvm::DIMacroFile::getRawElements(), llvm::DICompileUnit::getRawEnumTypes(), llvm::DIGlobalVariableExpression::getRawExpression(), llvm::DIScope::getRawFile(), llvm::DIVariable::getRawFile(), llvm::DICommonBlock::getRawFile(), llvm::DILabel::getRawFile(), llvm::DIObjCProperty::getRawFile(), llvm::DIMacroFile::getRawFile(), llvm::DICompileUnit::getRawGlobalVariables(), llvm::DICompileUnit::getRawImportedEntities(), llvm::DILocation::getRawInlinedAt(), llvm::DIGenericSubrange::getRawLowerBound(), llvm::DICompileUnit::getRawMacros(), llvm::DICompositeType::getRawRank(), llvm::DICompileUnit::getRawRetainedTypes(), llvm::DIType::getRawScope(), llvm::DILocation::getRawScope(), llvm::DILexicalBlockBase::getRawScope(), llvm::DINamespace::getRawScope(), llvm::DIVariable::getRawScope(), llvm::DICommonBlock::getRawScope(), llvm::DILabel::getRawScope(), llvm::DIGlobalVariable::getRawStaticDataMemberDeclaration(), llvm::DIGenericSubrange::getRawStride(), llvm::DIStringType::getRawStringLength(), llvm::DIStringType::getRawStringLengthExp(), llvm::DIStringType::getRawStringLocationExp(), llvm::DICompositeType::getRawTemplateParams(), llvm::DIGlobalVariable::getRawTemplateParams(), llvm::DITemplateParameter::getRawType(), llvm::DIVariable::getRawType(), llvm::DIObjCProperty::getRawType(), llvm::DISubroutineType::getRawTypeArray(), llvm::DIGenericSubrange::getRawUpperBound(), llvm::DIGlobalVariableExpression::getRawVariable(), llvm::DICompositeType::getRawVTableHolder(), llvm::hlsl::FrontendResource::getResourceIndex(), llvm::hlsl::FrontendResource::getSourceType(), llvm::hlsl::FrontendResource::getSpace(), getSummaryFromMD(), llvm::GetUnrollMetadata(), getValMD(), llvm::DITemplateValueParameter::getValue(), llvm::getValueProfDataFromInst(), hasAnyUnrollPragma(), isKeyValuePair(), AliasScopeTracker::isNoAliasScopeDeclDead(), IsScalarTBAANodeImpl(), isStructPathTBAA(), isTBAAVtableAccess(), llvm::Module::isValidModuleFlag(), llvm::makeFollowupLoopID(), llvm::makePostTransformationMetadata(), llvm::MDBuilder::mergeCallbackEncodings(), replaceOperandWith(), llvm::Loop::setLoopID(), llvm::AAMDNodes::shiftTBAAStruct(), llvm::Instruction::swapProfMetadata(), unrollAndJamCountPragmaValue(), unrollCountPragmaValue(), updateLoopMetadataDebugLocationsImpl(), llvm::UpgradeTBAANode(), and llvm::TBAAVerifier::visitTBAAMetadata().
getTemporary()
TempMDTuple llvm::MDNode::getTemporary (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 1411 of file Metadata.h.
References Context, and llvm::MDTuple::getTemporary().
Referenced by llvm::DIBuilder::createReplaceableCompositeType(), llvm::DIBuilder::createTempFunctionFwdDecl(), llvm::DIBuilder::createTempGlobalVariableFwdDecl(), and llvm::DIBuilder::createTempMacroFile().
intersect()
MDNode * MDNode::intersect (MDNode * A, MDNode * B) static
Definition at line 1019 of file Metadata.cpp.
References B, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::getArrayRef(), getOrSelfReference(), and llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::remove_if().
Referenced by llvm::combineMetadata(), llvm::AAMDNodes::concat(), llvm::AAMDNodes::merge(), and llvm::propagateMetadata().
isDistinct()
bool llvm::MDNode::isDistinct () const inline
Definition at line 1126 of file Metadata.h.
References llvm::Metadata::Distinct, and llvm::Metadata::Storage.
Referenced by llvm::DIType::mutate().
isResolved()
bool llvm::MDNode::isResolved () const inline
Check if node is fully resolved.
If isTemporary(), this always returns false; if isDistinct(), this always returns true.
If isUniqued(), returns true if this has already dropped RAUW support (because all operands are resolved).
As forward declarations are resolved, their containers should get resolved automatically. However, if this (or one of its operands) is involved in a cycle, resolveCycles() needs to be called explicitly.
Definition at line 1123 of file Metadata.h.
References getNumUnresolved(), and isTemporary().
Referenced by resolve(), resolveCycles(), and storeDistinctInContext().
isTBAAVtableAccess()
bool MDNode::isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Definition at line 454 of file TypeBasedAliasAnalysis.cpp.
References getNumOperands(), getOperand(), and isStructPathTBAA().
isTemporary()
bool llvm::MDNode::isTemporary () const inline
Definition at line 1127 of file Metadata.h.
References llvm::Metadata::Storage, and llvm::Metadata::Temporary.
Referenced by llvm::DIBuilder::finalizeSubprogram(), isResolved(), and replaceAllUsesWith().
isUniqued()
bool llvm::MDNode::isUniqued () const inline
Definition at line 1125 of file Metadata.h.
References llvm::Metadata::Storage, and llvm::Metadata::Uniqued.
Referenced by llvm::DIArgList::handleChangedOperand(), MDNode(), replaceOperandWith(), llvm::DILexicalBlockBase::replaceScope(), resize(), resolve(), and setOperand().
mutable_begin()
MDOperand* llvm::MDNode::mutable_begin () inline protected
Definition at line 1076 of file Metadata.h.
Referenced by mutable_operands(), op_begin(), replaceOperandWith(), and setOperand().
mutable_end()
MDOperand* llvm::MDNode::mutable_end () inline protected
Definition at line 1077 of file Metadata.h.
Referenced by mutable_operands(), and op_end().
mutable_operands()
mutable_op_range llvm::MDNode::mutable_operands () inline protected
Definition at line 1081 of file Metadata.h.
References mutable_begin(), and mutable_end().
op_begin()
op_iterator llvm::MDNode::op_begin () const inline
Definition at line 1281 of file Metadata.h.
References mutable_begin().
Referenced by llvm::GenericDINode::dwarf_op_begin(), and haveCommonPrefix().
op_end()
op_iterator llvm::MDNode::op_end () const inline
Definition at line 1285 of file Metadata.h.
References mutable_end().
Referenced by llvm::GenericDINode::dwarf_op_end(), and haveCommonPrefix().
operands()
ArrayRef<MDOperand> llvm::MDNode::operands () const inline
Definition at line 1289 of file Metadata.h.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), addBasicBlockMetadata(), llvm::memprof::CallStackTrie::addCallStack(), addOpsFromMDNode(), addToAccessGroupList(), annotateFunctionWithHashMismatch(), llvm::TargetLoweringObjectFile::emitCGProfileMetadata(), llvm::AsmPrinter::emitPCSections(), llvm::AAMDNodes::extendToTBAA(), llvm::AbstractCallSite::getCallbackUses(), getSummaryFromMD(), hasInstrProfHashMismatch(), llvm::Loop::isAnnotatedParallel(), llvm::makeFollowupLoopID(), propagateMemProfHelper(), and resolveCycles().
operator delete() [1/3]
void llvm::MDNode::operator delete (void * , unsigned) inline protected
Required by std, but never called.
Definition at line 1065 of file Metadata.h.
References llvm_unreachable.
operator delete() [2/3]
void llvm::MDNode::operator delete (void * , unsigned , bool) inline protected
Required by std, but never called.
Definition at line 1070 of file Metadata.h.
References llvm_unreachable.
operator delete() [3/3]
void MDNode::operator delete (void * Mem) protected
Definition at line 534 of file Metadata.cpp.
References H, and N.
operator new() [1/2]
void * MDNode::operator new (size_t Size, size_t NumOps, StorageType Storage) protected
Definition at line 524 of file Metadata.cpp.
References llvm::alignTo(), llvm::getAllocSize(), H, and uint64_t.
operator new() [2/2]
void* llvm::MDNode::operator new (size_t) delete
operator=()
void llvm::MDNode::operator= (const MDNode &) delete
printTree() [1/2]
void MDNode::printTree (raw_ostream & OS, const Module * M = nullptr) const
Print in tree shape.
Prints definition of this in tree shape.
If M is provided, metadata nodes will be numbered canonically; otherwise, pointer addresses are substituted.
Definition at line 4909 of file AsmWriter.cpp.
References M, OS, and printMetadataImpl().
Referenced by dumpTree().
printTree() [2/2]
void MDNode::printTree (raw_ostream & OS, ModuleSlotTracker & MST, const Module * M = nullptr) const
Definition at line 4915 of file AsmWriter.cpp.
References M, OS, and printMetadataImpl().
replaceAllUsesWith()
void llvm::MDNode::replaceAllUsesWith (Metadata * MD) inline
RAUW a temporary.
Precondition
isTemporary() must be true.
Definition at line 1132 of file Metadata.h.
References assert(), Context, and isTemporary().
replaceOperandWith()
void MDNode::replaceOperandWith (unsigned I, Metadata * New)
Replace a specific operand.
Definition at line 968 of file Metadata.cpp.
References getOperand(), I, isUniqued(), mutable_begin(), and setOperand().
Referenced by addBasicBlockMetadata(), AddRuntimeUnrollDisableMetaData(), llvm::MDBuilder::createAnonymousAARoot(), DisableAllLoopOptsOnLoop(), llvm::makeFollowupLoopID(), llvm::makePostTransformationMetadata(), llvm::GenericDINode::replaceDwarfOperandWith(), llvm::DICompositeType::replaceElements(), llvm::DIMacroFile::replaceElements(), llvm::DICompileUnit::replaceEnumTypes(), llvm::DICompileUnit::replaceGlobalVariables(), llvm::DICompileUnit::replaceImportedEntities(), llvm::DICompileUnit::replaceMacros(), llvm::DICompileUnit::replaceRetainedTypes(), llvm::DICompositeType::replaceTemplateParams(), llvm::DICompositeType::replaceVTableHolder(), stripLoopMDLoc(), and updateLoopMetadataDebugLocationsImpl().
replaceWithDistinct()
template<class T > static std::enable_if_t<std::is_base_of<MDNode, T>::value, T *> llvm::MDNode::replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N) inline static
Replace a temporary node with a distinct one.
Create a distinct version of N – in place, if possible – and return it. Takes ownership of the temporary node.
Definition at line 1177 of file Metadata.h.
References N.
Referenced by llvm::DIBuilder::createArtificialSubprogram().
replaceWithPermanent()
template<class T > static std::enable_if_t<std::is_base_of<MDNode, T>::value, T *> llvm::MDNode::replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N) inline static
Replace a temporary node with a permanent one.
Try to create a uniqued version of N – in place, if possible – and return it. If N cannot be uniqued, return a distinct node instead.
Definition at line 1155 of file Metadata.h.
References N.
replaceWithUniqued()
template<class T > static std::enable_if_t<std::is_base_of<MDNode, T>::value, T *> llvm::MDNode::replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N) inline static
Replace a temporary node with a uniqued one.
Create a uniqued version of N – in place, if possible – and return it. Takes ownership of the temporary node.
Precondition
N does not self-reference.
Definition at line 1167 of file Metadata.h.
References N.
Referenced by llvm::DILocalScope::cloneScopeForSubprogram(), createTypeWithFlags(), and llvm::DIBuilder::replaceTemporary().
resize()
void llvm::MDNode::resize (size_t NumOps) inline protected
Resize the node to hold NumOps operands.
Precondition
isTemporary() or isDistinct()
MetadataID == MDTupleKind
Definition at line 1229 of file Metadata.h.
References assert(), llvm::Metadata::getMetadataID(), and isUniqued().
Referenced by llvm::MDTuple::pop_back(), and llvm::MDTuple::push_back().
resolve()
void MDNode::resolve ()
Resolve a unique, unresolved node.
Definition at line 686 of file Metadata.cpp.
References assert(), isResolved(), isUniqued(), and setNumUnresolved().
Referenced by resolveCycles().
resolveCycles()
void MDNode::resolveCycles ()
Resolve cycles.
Once all forward declarations have been resolved, force cycles to be resolved.
Precondition
No operands (or operands' operands, etc.) have isTemporary().
Definition at line 732 of file Metadata.cpp.
References assert(), isResolved(), N, operands(), and resolve().
setNumUnresolved()
void llvm::MDNode::setNumUnresolved (unsigned N) inline protected
Definition at line 1219 of file Metadata.h.
References N.
Referenced by resolve().
setOperand()
void MDNode::setOperand (unsigned I, Metadata * New) protected
Set an operand.
Sets the operand directly, without worrying about uniquing.
Definition at line 980 of file Metadata.cpp.
References assert(), getNumOperands(), I, isUniqued(), mutable_begin(), and llvm::MDOperand::reset().
Referenced by dropAllReferences(), MDNode(), llvm::MDTuple::push_back(), replaceOperandWith(), and llvm::DILexicalBlockBase::replaceScope().
storeDistinctInContext()
void MDNode::storeDistinctInContext () protected
Definition at line 946 of file Metadata.cpp.
References assert(), Context, llvm::Metadata::Distinct, llvm::LLVMContextImpl::DistinctMDNodes, getContext(), llvm::Metadata::getMetadataID(), getNumUnresolved(), isResolved(), llvm_unreachable, llvm::LLVMContext::pImpl, and llvm::Metadata::Storage.
Referenced by llvm::DIArgList::handleChangedOperand().
storeImpl() [1/2]
template<class T > T * llvm::MDNode::storeImpl (T * N, StorageType Storage) static protected
Definition at line 28 of file MetadataImpl.h.
References llvm::Metadata::Distinct, llvm_unreachable, N, llvm::Metadata::Storage, T, llvm::Metadata::Temporary, and llvm::Metadata::Uniqued.
storeImpl() [2/2]
template<class T , class StoreT > T * llvm::MDNode::storeImpl (T * N, StorageType Storage, StoreT & Store) static protected
Definition at line 42 of file MetadataImpl.h.
References llvm::Metadata::Distinct, N, llvm::Metadata::Storage, llvm::SPII::Store, T, llvm::Metadata::Temporary, and llvm::Metadata::Uniqued.
Friends And Related Function Documentation
DIArgList
friend class DIArgList friend
Definition at line 946 of file Metadata.h.
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 945 of file Metadata.h.
ReplaceableMetadataImpl
friend class ReplaceableMetadataImpl friend
Definition at line 944 of file Metadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Metadata.h
lib/Analysis/TypeBasedAliasAnalysis.cpp
lib/IR/AsmWriter.cpp
lib/IR/Metadata.cpp
lib/IR/MetadataImpl.h