LLVM: llvm::ScalarEvolution::FoldID Class Reference
llvm::ScalarEvolution::FoldID Class Reference
#include "llvm/Analysis/ScalarEvolution.h"
Public Member Functions
void addInteger (unsigned long I)
void addInteger (unsigned I)
void addInteger (int I)
void addInteger (unsigned long long I)
void addPointer (const void *Ptr)
unsigned computeHash () const
bool operator== (const FoldID &RHS) const
Detailed Description
Definition at line 1299 of file ScalarEvolution.h.
Member Function Documentation
addInteger() [1/4]
void llvm::ScalarEvolution::FoldID::addInteger (int I) inline
Definition at line 1305 of file ScalarEvolution.h.
References I.
addInteger() [2/4]
void llvm::ScalarEvolution::FoldID::addInteger (unsigned I) inline
Definition at line 1304 of file ScalarEvolution.h.
References I.
addInteger() [3/4]
void llvm::ScalarEvolution::FoldID::addInteger (unsigned long I) inline
Definition at line 1303 of file ScalarEvolution.h.
References I.
Referenced by addInteger(), addPointer(), llvm::DenseMapInfo< ScalarEvolution::FoldID >::getEmptyKey(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::DenseMapInfo< ScalarEvolution::FoldID >::getTombstoneKey(), and llvm::ScalarEvolution::getZeroExtendExpr().
addInteger() [4/4]
void llvm::ScalarEvolution::FoldID::addInteger (unsigned long long I) inline
Definition at line 1307 of file ScalarEvolution.h.
References addInteger(), and I.
addPointer()
void llvm::ScalarEvolution::FoldID::addPointer (const void * Ptr) inline
Definition at line 1312 of file ScalarEvolution.h.
References addInteger(), and Ptr.
computeHash()
unsigned llvm::ScalarEvolution::FoldID::computeHash () const inline
Definition at line 1322 of file ScalarEvolution.h.
References llvm::detail::combineHashValue(), and I.
Referenced by llvm::DenseMapInfo< ScalarEvolution::FoldID >::getHashValue().
operator==()
bool llvm::ScalarEvolution::FoldID::operator== (const FoldID & RHS) const inline
Definition at line 1328 of file ScalarEvolution.h.
References I, and RHS.
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolution.h