LLVM: llvm::InlineAdvisor Class Reference
llvm::InlineAdvisor Class Reference abstract
Interface for deciding whether to inline a call site or not.
#include "llvm/Analysis/InlineAdvisor.h"
Public Member Functions
InlineAdvisor (InlineAdvisor &&)=delete
virtual ~InlineAdvisor ()
std::unique_ptr< InlineAdvice > getAdvice (CallBase &CB, bool MandatoryOnly=false)
Get an InlineAdvice containing a recommendation on whether to inline or not.
virtual void onPassEntry (LazyCallGraph::SCC *SCC=nullptr)
This must be called when the Inliner pass is entered, to allow the InlineAdvisor update internal state, as result of function passes run between Inliner pass runs (for the same module).
virtual void onPassExit (LazyCallGraph::SCC *SCC=nullptr)
This must be called when the Inliner pass is exited, as function passes may be run subsequently.
virtual void print (raw_ostream &OS) const
Support for printer pass.
const char * getAnnotatedInlinePassName () const
NOTE pass name is annotated only when inline advisor constructor provides InlineContext.
Protected Types
enum MandatoryInliningKind { MandatoryInliningKind::NotMandatory, MandatoryInliningKind::Always, MandatoryInliningKind::Never }
Protected Member Functions
InlineAdvisor (Module &M, FunctionAnalysisManager &FAM, std::optional< InlineContext > IC=std::nullopt)
virtual std::unique_ptr< InlineAdvice > getAdviceImpl (CallBase &CB)=0
virtual std::unique_ptr< InlineAdvice > getMandatoryAdvice (CallBase &CB, bool Advice)
OptimizationRemarkEmitter & getCallerORE (CallBase &CB)
Static Protected Member Functions
static MandatoryInliningKind getMandatoryKind (CallBase &CB, FunctionAnalysisManager &FAM, OptimizationRemarkEmitter &ORE)
Protected Attributes
Module & M
FunctionAnalysisManager & FAM
const std::optional< InlineContext > IC
const std::string AnnotatedInlinePassName
std::unique_ptr< ImportedFunctionsInliningStatistics > ImportedFunctionsStats
Friends
class InlineAdvice
Detailed Description
Interface for deciding whether to inline a call site or not.
Definition at line 165 of file InlineAdvisor.h.
Member Enumeration Documentation
MandatoryInliningKind
enum llvm::InlineAdvisor::MandatoryInliningKind strong protected
Enumerator
NotMandatory
Always
Never
Definition at line 216 of file InlineAdvisor.h.
Constructor & Destructor Documentation
InlineAdvisor() [1/2]
llvm::InlineAdvisor::InlineAdvisor (InlineAdvisor &&) delete
~InlineAdvisor()
InlineAdvisor::~InlineAdvisor () virtual
Definition at line 534 of file InlineAdvisor.cpp.
References assert(), ImportedFunctionsStats, llvm::InlinerFunctionImportStats, llvm::No, and llvm::Verbose.
InlineAdvisor() [2/2]
InlineAdvisor::InlineAdvisor (Module & M, FunctionAnalysisManager & FAM, std::optional< InlineContext > IC = std::nullopt) protected
Definition at line 521 of file InlineAdvisor.cpp.
References ImportedFunctionsStats, llvm::InlinerFunctionImportStats, M, M, and llvm::No.
Member Function Documentation
getAdvice()
std::unique_ptr< InlineAdvice > InlineAdvisor::getAdvice (CallBase & CB, bool MandatoryOnly = false)
Get an InlineAdvice containing a recommendation on whether to inline or not.
CB is assumed to be a direct call. FAM is assumed to be up-to-date wrt previous inlining decisions. MandatoryOnly indicates only mandatory (always-inline) call sites should be recommended - this allows the InlineAdvisor track such inlininings. Returns:
An InlineAdvice with the inlining recommendation.
Null when no recommendation is made (https://reviews.llvm.org/D110658). TODO: Consider removing the Null return scenario by incorporating the SampleProfile inliner into an InlineAdvisor
Definition at line 613 of file InlineAdvisor.cpp.
References Always, FAM, getAdviceImpl(), llvm::CallBase::getCalledFunction(), llvm::CallBase::getCaller(), getCallerORE(), getMandatoryAdvice(), and getMandatoryKind().
getAdviceImpl()
virtual std::unique_ptr<InlineAdvice> llvm::InlineAdvisor::getAdviceImpl (CallBase & CB) protected pure virtual
Implemented in llvm::ReplayInlineAdvisor, and llvm::MLInlineAdvisor.
Referenced by getAdvice().
getAnnotatedInlinePassName()
const char* llvm::InlineAdvisor::getAnnotatedInlinePassName () const inline
NOTE pass name is annotated only when inline advisor constructor provides InlineContext.
Definition at line 199 of file InlineAdvisor.h.
References AnnotatedInlinePassName.
getCallerORE()
OptimizationRemarkEmitter & InlineAdvisor::getCallerORE (CallBase & CB) protected
Definition at line 623 of file InlineAdvisor.cpp.
References FAM, llvm::CallBase::getCaller(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult().
Referenced by getAdvice(), llvm::MLInlineAdvisor::getMandatoryAdvice(), getMandatoryAdvice(), and llvm::MLInlineAdvisor::getMandatoryAdviceImpl().
getMandatoryAdvice()
std::unique_ptr< InlineAdvice > InlineAdvisor::getMandatoryAdvice (CallBase & CB, bool Advice) protected virtual
Reimplemented in llvm::MLInlineAdvisor.
Definition at line 542 of file InlineAdvisor.cpp.
References getCallerORE().
Referenced by getAdvice().
getMandatoryKind()
InlineAdvisor::MandatoryInliningKind InlineAdvisor::getMandatoryKind (CallBase & CB, FunctionAnalysisManager & FAM, OptimizationRemarkEmitter & ORE) static protected
Definition at line 591 of file InlineAdvisor.cpp.
References Always, Callee, F, FAM, llvm::getAttributeBasedInliningDecision(), llvm::CallBase::getCalledFunction(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), Never, and NotMandatory.
Referenced by getAdvice(), and llvm::MLInlineAdvisor::getAdviceImpl().
onPassEntry()
virtual void llvm::InlineAdvisor::onPassEntry (LazyCallGraph::SCC * SCC = nullptr) inline virtual
This must be called when the Inliner pass is entered, to allow the InlineAdvisor update internal state, as result of function passes run between Inliner pass runs (for the same module).
Reimplemented in llvm::MLInlineAdvisor.
Definition at line 186 of file InlineAdvisor.h.
Referenced by llvm::ModuleInlinerPass::run(), and llvm::InlinerPass::run().
onPassExit()
virtual void llvm::InlineAdvisor::onPassExit (LazyCallGraph::SCC * SCC = nullptr) inline virtual
This must be called when the Inliner pass is exited, as function passes may be run subsequently.
This allows an implementation of InlineAdvisor to prepare for a partial update, based on the optional SCC.
Reimplemented in llvm::MLInlineAdvisor.
Definition at line 191 of file InlineAdvisor.h.
Referenced by llvm::ModuleInlinerPass::run(), and llvm::InlinerPass::run().
print()
virtual void llvm::InlineAdvisor::print (raw_ostream & OS) const inline virtual
Support for printer pass.
Definition at line 194 of file InlineAdvisor.h.
References OS.
Friends And Related Function Documentation
InlineAdvice
friend class InlineAdvice friend
Definition at line 225 of file InlineAdvisor.h.
Member Data Documentation
AnnotatedInlinePassName
const std::string llvm::InlineAdvisor::AnnotatedInlinePassName protected
Definition at line 213 of file InlineAdvisor.h.
Referenced by getAnnotatedInlinePassName().
FAM
FunctionAnalysisManager& llvm::InlineAdvisor::FAM protected
Definition at line 211 of file InlineAdvisor.h.
Referenced by getAdvice(), llvm::MLInlineAdvisor::getAdviceImpl(), llvm::ReplayInlineAdvisor::getAdviceImpl(), llvm::MLInlineAdvisor::getCachedFPI(), getCallerORE(), getMandatoryKind(), and llvm::MLInlineAdvisor::onSuccessfulInlining().
IC
const std::optional<InlineContext> llvm::InlineAdvisor::IC protected
Definition at line 212 of file InlineAdvisor.h.
ImportedFunctionsStats
std::unique_ptr<ImportedFunctionsInliningStatistics> llvm::InlineAdvisor::ImportedFunctionsStats protected
Definition at line 214 of file InlineAdvisor.h.
Referenced by InlineAdvisor(), and ~InlineAdvisor().
M
Module& llvm::InlineAdvisor::M protected
Definition at line 210 of file InlineAdvisor.h.
Referenced by InlineAdvisor(), and llvm::MLInlineAdvisor::MLInlineAdvisor().
The documentation for this class was generated from the following files:
include/llvm/Analysis/InlineAdvisor.h
lib/Analysis/InlineAdvisor.cpp