LLVM: llvm::PrintPassInstrumentation Class Reference
llvm::PrintPassInstrumentation Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
PrintPassInstrumentation (bool Enabled, PrintPassOptions Opts)
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Detailed Description
Definition at line 96 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
PrintPassInstrumentation()
llvm::PrintPassInstrumentation::PrintPassInstrumentation (bool Enabled, PrintPassOptions Opts) inline
Definition at line 100 of file StandardInstrumentations.h.
Member Function Documentation
registerCallbacks()
void PrintPassInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 850 of file StandardInstrumentations.cpp.
References assert(), F, IR, llvm::isSpecialPass(), OS, PIC, llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerAnalysesClearedCallback(), llvm::PassInstrumentationCallbacks::registerAnalysisInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerBeforeAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback(), llvm::PassInstrumentationCallbacks::registerBeforeSkippedPassCallback(), llvm::PrintPassOptions::SkipAnalyses, and llvm::PrintPassOptions::Verbose.
Referenced by llvm::StandardInstrumentations::registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp