LLVM: llvm::jitlink::JITLinkContext Class Reference
llvm::jitlink::JITLinkContext Class Reference abstract
Holds context for a single jitLink invocation.
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Public Types
using LookupMap = DenseMap< StringRef, SymbolLookupFlags >
Public Member Functions
JITLinkContext (const JITLinkDylib *JD)
Create a JITLinkContext.
virtual ~JITLinkContext ()
Destroy a JITLinkContext.
const JITLinkDylib * getJITLinkDylib () const
Return the JITLinkDylib that this link is targeting, if any.
virtual JITLinkMemoryManager & getMemoryManager ()=0
Return the MemoryManager to be used for this link.
virtual void notifyFailed (Error Err)=0
Notify this context that linking failed.
virtual void lookup (const LookupMap &Symbols, std::unique_ptr< JITLinkAsyncLookupContinuation > LC)=0
Called by JITLink to resolve external symbols.
virtual Error notifyResolved (LinkGraph &G)=0
Called by JITLink once all defined symbols in the graph have been assigned their final memory locations in the target process.
virtual void notifyFinalized (JITLinkMemoryManager::FinalizedAlloc Alloc)=0
Called by JITLink to notify the context that the object has been finalized (i.e.
virtual bool shouldAddDefaultTargetPasses (const Triple &TT) const
Called by JITLink prior to linking to determine whether default passes for the target should be added.
virtual LinkGraphPassFunction getMarkLivePass (const Triple &TT) const
Returns the mark-live pass to be used for this link.
virtual Error modifyPassConfig (LinkGraph &G, PassConfiguration &Config)
Called by JITLink to modify the pass pipeline prior to linking.
Detailed Description
Holds context for a single jitLink invocation.
Definition at line 1731 of file JITLink.h.
Member Typedef Documentation
LookupMap
using llvm::jitlink::JITLinkContext::LookupMap = DenseMap<StringRef, SymbolLookupFlags>
Definition at line 1733 of file JITLink.h.
Constructor & Destructor Documentation
JITLinkContext()
llvm::jitlink::JITLinkContext::JITLinkContext (const JITLinkDylib * JD) inline
Create a JITLinkContext.
Definition at line 1736 of file JITLink.h.
~JITLinkContext()
llvm::jitlink::JITLinkContext::~JITLinkContext () virtual default
Destroy a JITLinkContext.
Member Function Documentation
getJITLinkDylib()
const JITLinkDylib* llvm::jitlink::JITLinkContext::getJITLinkDylib () const inline
Return the JITLinkDylib that this link is targeting, if any.
Definition at line 1742 of file JITLink.h.
Referenced by llvm::orc::ELFDebugObject::Create().
getMarkLivePass()
LinkGraphPassFunction llvm::jitlink::JITLinkContext::getMarkLivePass (const Triple & TT) const virtual
Returns the mark-live pass to be used for this link.
If no pass is returned (the default) then the target-specific linker implementation will choose a conservative default (usually marking all symbols live). This function is only called if shouldAddDefaultTargetPasses returns true, otherwise the JITContext is responsible for adding a mark-live pass in modifyPassConfig.
Reimplemented in llvm::orc::ObjectLinkingLayerJITLinkContext.
Definition at line 359 of file JITLink.cpp.
getMemoryManager()
virtual JITLinkMemoryManager& llvm::jitlink::JITLinkContext::getMemoryManager () pure virtual
Return the MemoryManager to be used for this link.
Implemented in llvm::orc::ObjectLinkingLayerJITLinkContext.
Referenced by llvm::orc::ELFDebugObject::Create().
lookup()
virtual void llvm::jitlink::JITLinkContext::lookup (const LookupMap & Symbols, std::unique_ptr< JITLinkAsyncLookupContinuation > LC) pure virtual
Called by JITLink to resolve external symbols.
This method is passed a lookup continutation which it must call with a result to continue the linking process.
Implemented in llvm::orc::ObjectLinkingLayerJITLinkContext.
modifyPassConfig()
Error llvm::jitlink::JITLinkContext::modifyPassConfig (LinkGraph & G, PassConfiguration & Config) virtual
Called by JITLink to modify the pass pipeline prior to linking.
The default version performs no modification.
Reimplemented in llvm::orc::ObjectLinkingLayerJITLinkContext.
Definition at line 363 of file JITLink.cpp.
References llvm::Error::success().
notifyFailed()
virtual void llvm::jitlink::JITLinkContext::notifyFailed (Error Err) pure virtual
Notify this context that linking failed.
Called by JITLink if linking cannot be completed.
Implemented in llvm::orc::ObjectLinkingLayerJITLinkContext.
notifyFinalized()
virtual void llvm::jitlink::JITLinkContext::notifyFinalized (JITLinkMemoryManager::FinalizedAlloc Alloc) pure virtual
Called by JITLink to notify the context that the object has been finalized (i.e.
emitted to memory and memory permissions set). If all of this objects dependencies have also been finalized then the code is ready to run.
Implemented in llvm::orc::ObjectLinkingLayerJITLinkContext.
notifyResolved()
virtual Error llvm::jitlink::JITLinkContext::notifyResolved (LinkGraph & G) pure virtual
Called by JITLink once all defined symbols in the graph have been assigned their final memory locations in the target process.
At this point the LinkGraph can be inspected to build a symbol table, however the block content will not generally have been copied to the target location yet.
If the client detects an error in the LinkGraph state (e.g. unexpected or missing symbols) they may return an error here. The error will be propagated to notifyFailed and the linker will bail out.
Implemented in llvm::orc::ObjectLinkingLayerJITLinkContext.
shouldAddDefaultTargetPasses()
bool llvm::jitlink::JITLinkContext::shouldAddDefaultTargetPasses (const Triple & TT) const virtual
Called by JITLink prior to linking to determine whether default passes for the target should be added.
The default implementation returns true. If subclasses override this method to return false for any target then they are required to fully configure the pass pipeline for that target.
Definition at line 355 of file JITLink.cpp.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLink.h
lib/ExecutionEngine/JITLink/JITLink.cpp