LLVM: llvm::StandardInstrumentations Class Reference
llvm::StandardInstrumentations Class Reference
This class provides an interface to register all the standard pass instrumentations and manages their state (if any).
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
StandardInstrumentations (LLVMContext &Context, bool DebugLogging, bool VerifyEach=false, PrintPassOptions PrintPassOpts=PrintPassOptions())
void registerCallbacks (PassInstrumentationCallbacks &PIC, FunctionAnalysisManager *FAM=nullptr)
TimePassesHandler & getTimePasses ()
Detailed Description
This class provides an interface to register all the standard pass instrumentations and manages their state (if any).
Definition at line 552 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
StandardInstrumentations()
llvm::StandardInstrumentations::StandardInstrumentations (LLVMContext & Context, bool DebugLogging, bool VerifyEach = false, PrintPassOptions PrintPassOpts = PrintPassOptions())
Definition at line 2092 of file StandardInstrumentations.cpp.
References llvm::ColourDiffQuiet, llvm::ColourDiffVerbose, llvm::DiffVerbose, llvm::DotCfgVerbose, and llvm::Verbose.
Member Function Documentation
getTimePasses()
TimePassesHandler& llvm::StandardInstrumentations::getTimePasses () inline
Definition at line 580 of file StandardInstrumentations.h.
registerCallbacks()
void llvm::StandardInstrumentations::registerCallbacks (PassInstrumentationCallbacks & PIC, FunctionAnalysisManager * FAM = nullptr)
Definition at line 2152 of file StandardInstrumentations.cpp.
References FAM, PIC, llvm::PrintIRInstrumentation::registerCallbacks(), llvm::PseudoProbeVerifier::registerCallbacks(), llvm::OptNoneInstrumentation::registerCallbacks(), llvm::TimePassesHandler::registerCallbacks(), llvm::PrintPassInstrumentation::registerCallbacks(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::IRChangedPrinter::registerCallbacks(), llvm::IRChangedTester::registerCallbacks(), llvm::InLineChangePrinter::registerCallbacks(), llvm::VerifyInstrumentation::registerCallbacks(), llvm::TimeProfilingPassesHandler::registerCallbacks(), llvm::DotCfgChangeReporter::registerCallbacks(), and llvm::PrintCrashIRInstrumentation::registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp