LLVM: llvm::object::BuildIDFetcher Class Reference
llvm::object::BuildIDFetcher Class Reference
BuildIDFetcher searches local cache directories for debug info.
#include "llvm/Object/BuildID.h"
Public Member Functions
BuildIDFetcher (std::vector< std::string > DebugFileDirectories)
virtual ~BuildIDFetcher ()=default
virtual std::optional< std::string > fetch (BuildIDRef BuildID) const
Returns the path to the debug file with the given build ID.
Detailed Description
BuildIDFetcher searches local cache directories for debug info.
Definition at line 36 of file BuildID.h.
Constructor & Destructor Documentation
BuildIDFetcher()
llvm::object::BuildIDFetcher::BuildIDFetcher (std::vector< std::string > DebugFileDirectories) inline
Definition at line 38 of file BuildID.h.
~BuildIDFetcher()
virtual llvm::object::BuildIDFetcher::~BuildIDFetcher () virtual default
Member Function Documentation
fetch()
std::optional< std::string > llvm::object::BuildIDFetcher::fetch (BuildIDRef BuildID) const virtual
Returns the path to the debug file with the given build ID.
Reimplemented in llvm::DebuginfodFetcher.
Definition at line 60 of file BuildID.cpp.
References llvm::sys::path::append(), endif(), llvm::sys::fs::exists(), and llvm::symbolize::toHex().
Referenced by llvm::coverage::CoverageMapping::load().
The documentation for this class was generated from the following files:
include/llvm/Object/BuildID.h
lib/Object/BuildID.cpp