LLVM: std::reverse_iterator< llvm::DWARFDie::iterator > Class Reference
std::reverse_iterator< llvm::DWARFDie::iterator > Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
Public Member Functions
reverse_iterator (llvm::DWARFDie::iterator It)
llvm::DWARFDie::iterator base () const
reverse_iterator< llvm::DWARFDie::iterator > & operator++ ()
reverse_iterator< llvm::DWARFDie::iterator > & operator-- ()
const llvm::DWARFDie & operator* () const
bool equals (const reverse_iterator< llvm::DWARFDie::iterator > &RHS) const
Public Member Functions inherited from llvm::iterator_facade_base< reverse_iterator< llvm::DWARFDie::iterator >, bidirectional_iterator_tag, const llvm::DWARFDie >
reverse_iterator< llvm::DWARFDie::iterator > operator+ (std::ptrdiff_t n) const
reverse_iterator< llvm::DWARFDie::iterator > operator- (std::ptrdiff_t n) const
reverse_iterator< llvm::DWARFDie::iterator > & operator++ ()
reverse_iterator< llvm::DWARFDie::iterator > operator++ (int)
reverse_iterator< llvm::DWARFDie::iterator > & operator-- ()
reverse_iterator< llvm::DWARFDie::iterator > operator-- (int)
bool operator!= (const reverse_iterator< llvm::DWARFDie::iterator > &RHS) const
bool operator> (const reverse_iterator< llvm::DWARFDie::iterator > &RHS) const
bool operator<= (const reverse_iterator< llvm::DWARFDie::iterator > &RHS) const
bool operator>= (const reverse_iterator< llvm::DWARFDie::iterator > &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< reverse_iterator< llvm::DWARFDie::iterator >, bidirectional_iterator_tag, const llvm::DWARFDie >
using iterator_category = bidirectional_iterator_tag
using value_type = const llvm::DWARFDie
using difference_type = std::ptrdiff_t
using pointer = const llvm::DWARFDie *
using reference = const llvm::DWARFDie &
Protected Types inherited from llvm::iterator_facade_base< reverse_iterator< llvm::DWARFDie::iterator >, bidirectional_iterator_tag, const llvm::DWARFDie >
enum
Detailed Description
Definition at line 404 of file DWARFDie.h.
Constructor & Destructor Documentation
reverse_iterator()
std::reverse_iterator< llvm::DWARFDie::iterator >::reverse_iterator (llvm::DWARFDie::iterator It) inline
Definition at line 414 of file DWARFDie.h.
References llvm::DWARFDie::getPreviousSibling().
Member Function Documentation
base()
llvm::DWARFDie::iterator std::reverse_iterator< llvm::DWARFDie::iterator >::base () const inline
Definition at line 420 of file DWARFDie.h.
References llvm::DWARFDie::getSibling().
equals()
bool std::reverse_iterator< llvm::DWARFDie::iterator >::equals (const reverse_iterator< llvm::DWARFDie::iterator > & RHS) const inline
Definition at line 452 of file DWARFDie.h.
References RHS.
operator*()
const llvm::DWARFDie& std::reverse_iterator< llvm::DWARFDie::iterator >::operator* () const inline
Definition at line 444 of file DWARFDie.h.
References assert(), and llvm::DWARFDie::isValid().
operator++()
reverse_iterator<llvm::DWARFDie::iterator>& std::reverse_iterator< llvm::DWARFDie::iterator >::operator++ () inline
Definition at line 424 of file DWARFDie.h.
References assert(), D, and llvm::DWARFDie::getPreviousSibling().
operator--()
reverse_iterator<llvm::DWARFDie::iterator>& std::reverse_iterator< llvm::DWARFDie::iterator >::operator-- () inline
Definition at line 434 of file DWARFDie.h.
References assert(), llvm::DWARFDie::getSibling(), and llvm::DWARFDie::isNULL().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/DWARF/DWARFDie.h