LLVM: llvm::MCSymbolELF Class Reference
llvm::MCSymbolELF Class Reference
#include "llvm/MC/MCSymbolELF.h"
Public Member Functions
MCSymbolELF (const StringMapEntry< bool > *Name, bool isTemporary)
void setSize (const MCExpr *SS)
const MCExpr * getSize () const
void setVisibility (unsigned Visibility)
unsigned getVisibility () const
void setOther (unsigned Other)
unsigned getOther () const
void setType (unsigned Type) const
unsigned getType () const
void setBinding (unsigned Binding) const
unsigned getBinding () const
bool isBindingSet () const
void setIsWeakrefUsedInReloc () const
bool isWeakrefUsedInReloc () const
void setIsSignature () const
bool isSignature () const
void setMemtag (bool Tagged)
bool isMemtag () const
Public Member Functions inherited from llvm::MCSymbol
MCSymbol (const MCSymbol &)=delete
MCSymbol & operator= (const MCSymbol &)=delete
StringRef getName () const
getName - Get the symbol name.
bool isRegistered () const
void setIsRegistered (bool Value) const
void setUsedInReloc () const
bool isUsedInReloc () const
uint32_t getIndex () const
Get the (implementation defined) index.
void setIndex (uint32_t Value) const
Set the (implementation defined) index.
bool isUnset () const
uint64_t getOffset () const
void setOffset (uint64_t Value)
uint64_t getCommonSize () const
Return the size of a 'common' symbol.
void setCommon (uint64_t Size, Align Alignment, bool Target=false)
Mark this symbol as being 'common'.
MaybeAlign getCommonAlignment () const
Return the alignment of a 'common' symbol.
bool declareCommon (uint64_t Size, Align Alignment, bool Target=false)
Declare this symbol as being 'common'.
bool isCommon () const
Is this a 'common' symbol.
bool isTargetCommon () const
Is this a target-specific common-like symbol.
MCFragment * getFragment (bool SetUsed=true) const
bool isExternal () const
void setExternal (bool Value) const
bool isPrivateExtern () const
void setPrivateExtern (bool Value)
void print (raw_ostream &OS, const MCAsmInfo *MAI) const
print - Print the value to the stream OS.
void dump () const
dump - Print the value to stderr.
bool isTemporary () const
isTemporary - Check if this is an assembler temporary symbol.
bool isUsed () const
isUsed - Check if this is used.
bool isRedefinable () const
Check if this symbol is redefinable.
void setRedefinable (bool Value)
Mark this symbol as redefinable.
void redefineIfPossible ()
Prepare this symbol to be redefined.
bool isDefined () const
isDefined - Check if this symbol is defined (i.e., it has an address).
bool isInSection () const
isInSection - Check if this symbol is defined in some section (i.e., it is defined but not absolute).
bool isUndefined (bool SetUsed=true) const
isUndefined - Check if this symbol undefined (i.e., implicitly defined).
bool isAbsolute () const
isAbsolute - Check if this is an absolute symbol.
MCSection & getSection () const
Get the section associated with a defined, non-absolute symbol.
void setFragment (MCFragment *F) const
Mark the symbol as defined in the fragment F.
void setUndefined ()
Mark the symbol as undefined.
bool isELF () const
bool isCOFF () const
bool isGOFF () const
bool isMachO () const
bool isWasm () const
bool isXCOFF () const
bool isVariable () const
isVariable - Check if this is a variable symbol.
const MCExpr * getVariableValue (bool SetUsed=true) const
getVariableValue - Get the value for variable symbols.
void setVariableValue (const MCExpr *Value)
Static Public Member Functions
static bool classof (const MCSymbol *S)
Additional Inherited Members
Protected Types inherited from llvm::MCSymbol
enum SymbolKind {
SymbolKindUnset, SymbolKindCOFF, SymbolKindELF, SymbolKindGOFF,
SymbolKindMachO, SymbolKindWasm, SymbolKindXCOFF
}
The kind of the symbol.
enum Contents : uint8_t {
SymContentsUnset, SymContentsOffset, SymContentsVariable, SymContentsCommon,
SymContentsTargetCommon
}
A symbol can contain an Offset, or Value, or be Common, but never more than one of these.
enum : unsigned { NumCommonAlignmentBits = 5 }
The alignment of the symbol if it is 'common'.
enum : unsigned { NumFlagsBits = 16 }
The Flags field is used by object file implementations to store additional per symbol information which is not easily classified.
using NameEntryStorageTy = union { const StringMapEntry< bool > *NameEntry
The name for a symbol.
Protected Member Functions inherited from llvm::MCSymbol
MCSymbol (SymbolKind Kind, const StringMapEntry< bool > *Name, bool isTemporary)
void * operator new (size_t s, const StringMapEntry< bool > *Name, MCContext &Ctx)
uint32_t getFlags () const
Get the (implementation defined) symbol flags.
void setFlags (uint32_t Value) const
Set the (implementation defined) symbol flags.
void modifyFlags (uint32_t Value, uint32_t Mask) const
Modify the flags via a mask.
Protected Attributes inherited from llvm::MCSymbol
PointerIntPair< MCFragment *, 1 > FragmentAndHasName
If a symbol has a Fragment, the section is implied, so we only need one pointer.
unsigned IsTemporary: 1
IsTemporary - True if this is an assembler temporary label, which typically does not survive in the .o file's symbol table.
unsigned IsRedefinable: 1
True if this symbol can be redefined.
unsigned IsUsed: 1
IsUsed - True if this symbol has been used.
unsigned IsRegistered: 1
unsigned IsExternal: 1
True if this symbol is visible outside this translation unit.
unsigned IsPrivateExtern: 1
This symbol is private extern.
unsigned Kind: 3
LLVM RTTI discriminator.
unsigned IsUsedInReloc: 1
True if we have created a relocation that uses this symbol.
unsigned SymbolContents: 3
This is actually a Contents enumerator, but is unsigned to avoid sign extension and achieve better bitpacking with MSVC.
unsigned CommonAlignLog2: NumCommonAlignmentBits
uint32_t Flags: NumFlagsBits
uint32_t Index = 0
Index field, for use by the object file implementation.
union {
uint64_t Offset
The offset to apply to the fragment address to form this symbol's value.
uint64_t CommonSize
The size of the symbol, if it is 'common'.
const MCExpr * Value
If non-null, the value for a variable symbol.
};
uint64_t AlignmentPadding
Static Protected Attributes inherited from llvm::MCSymbol
static MCFragment * AbsolutePseudoFragment = &SentinelFragment
Detailed Description
Definition at line 14 of file MCSymbolELF.h.
Constructor & Destructor Documentation
MCSymbolELF()
llvm::MCSymbolELF::MCSymbolELF (const StringMapEntry< bool > * Name, bool isTemporary) inline
Definition at line 20 of file MCSymbolELF.h.
Member Function Documentation
classof()
static bool llvm::MCSymbolELF::classof (const MCSymbol * S) inline static
Definition at line 49 of file MCSymbolELF.h.
References S.
getBinding()
unsigned llvm::MCSymbolELF::getBinding () const
Definition at line 66 of file MCSymbolELF.cpp.
References llvm::MCSymbol::Flags, isBindingSet(), llvm::MCSymbol::isDefined(), isSignature(), llvm::MCSymbol::isUsedInReloc(), isWeakrefUsedInReloc(), llvm_unreachable, llvm::ELF::STB_GLOBAL, llvm::ELF::STB_GNU_UNIQUE, llvm::ELF::STB_LOCAL, and llvm::ELF::STB_WEAK.
Referenced by llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), and getMatchingLoType().
getOther()
unsigned llvm::MCSymbolELF::getOther () const
Definition at line 168 of file MCSymbolELF.cpp.
References llvm::MCSymbol::Flags, and Other.
Referenced by llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor().
getSize()
const MCExpr* llvm::MCSymbolELF::getSize () const inline
Definition at line 24 of file MCSymbolELF.h.
getType()
unsigned llvm::MCSymbolELF::getType () const
Definition at line 125 of file MCSymbolELF.cpp.
References llvm::MCSymbol::Flags, llvm_unreachable, llvm::ELF::STT_COMMON, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, and llvm::ELF::STT_TLS.
getVisibility()
unsigned llvm::MCSymbolELF::getVisibility () const
Definition at line 155 of file MCSymbolELF.cpp.
References llvm::MCSymbol::Flags.
Referenced by llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor().
isBindingSet()
bool llvm::MCSymbolELF::isBindingSet () const
Definition at line 196 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags().
Referenced by llvm::AMDGPUTargetELFStreamer::emitAMDGPULDS(), and getBinding().
isMemtag()
bool llvm::MCSymbolELF::isMemtag () const
Definition at line 200 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags().
isSignature()
bool llvm::MCSymbolELF::isSignature () const
Definition at line 187 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags().
Referenced by getBinding().
isWeakrefUsedInReloc()
bool llvm::MCSymbolELF::isWeakrefUsedInReloc () const
Definition at line 178 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags().
Referenced by getBinding().
setBinding()
void llvm::MCSymbolELF::setBinding (unsigned Binding) const
Definition at line 43 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), llvm_unreachable, llvm::MCSymbol::setFlags(), llvm::ELF::STB_GLOBAL, llvm::ELF::STB_GNU_UNIQUE, llvm::ELF::STB_LOCAL, and llvm::ELF::STB_WEAK.
Referenced by llvm::AMDGPUTargetELFStreamer::emitAMDGPULDS(), and llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor().
setIsSignature()
void llvm::MCSymbolELF::setIsSignature () const
Definition at line 182 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), and llvm::MCSymbol::setFlags().
setIsWeakrefUsedInReloc()
void llvm::MCSymbolELF::setIsWeakrefUsedInReloc () const
Definition at line 173 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), and llvm::MCSymbol::setFlags().
setMemtag()
void llvm::MCSymbolELF::setMemtag (bool Tagged)
Definition at line 204 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), and llvm::MCSymbol::setFlags().
setOther()
void llvm::MCSymbolELF::setOther (unsigned Other)
Definition at line 160 of file MCSymbolELF.cpp.
References assert(), llvm::MCSymbol::getFlags(), Other, and llvm::MCSymbol::setFlags().
Referenced by llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor().
setSize()
void llvm::MCSymbolELF::setSize (const MCExpr * SS) inline
Definition at line 22 of file MCSymbolELF.h.
References llvm::X86AS::SS.
Referenced by llvm::AMDGPUTargetELFStreamer::emitAMDGPULDS(), and llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor().
setType()
void llvm::MCSymbolELF::setType (unsigned Type) const
Definition at line 94 of file MCSymbolELF.cpp.
References llvm::MCSymbol::getFlags(), llvm_unreachable, llvm::MCSymbol::setFlags(), llvm::ELF::STT_COMMON, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, and llvm::ELF::STT_TLS.
Referenced by llvm::AMDGPUTargetELFStreamer::emitAMDGPULDS(), and llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor().
setVisibility()
void llvm::MCSymbolELF::setVisibility (unsigned Visibility)
Definition at line 147 of file MCSymbolELF.cpp.
References assert(), llvm::MCSymbol::getFlags(), llvm::MCSymbol::setFlags(), llvm::ELF::STV_DEFAULT, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, and llvm::ELF::STV_PROTECTED.
Referenced by llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor().
The documentation for this class was generated from the following files:
include/llvm/MC/MCSymbolELF.h
lib/MC/MCSymbolELF.cpp