LLVM: llvm::Error Class Reference
llvm::Error Class Reference
Lightweight error class with error context and mandatory checking.
#include "llvm/Support/Error.h"
Public Member Functions
Error (const Error &Other)=delete
Error (Error &&Other)
Move-construct an error value.
Error (std::unique_ptr< ErrorInfoBase > Payload)
Create an error value.
Error & operator= (const Error &Other)=delete
Error & operator= (Error &&Other)
Move-assign an error value.
~Error ()
Destroy a Error.
operator bool ()
Bool conversion.
template<typename ErrT >
bool isA () const
Check whether one error is a subclass of another.
const void * dynamicClassID () const
Returns the dynamic class id of this error, or null if this is a success value.
Static Public Member Functions
static ErrorSuccess success ()
Create a success value.
Protected Member Functions
Error ()
Create a success value. Prefer using 'Error::success()' for readability.
Friends
class ErrorList
template<typename T >
class Expected
template<typename... HandlerTs>
Error handleErrors (Error E, HandlerTs &&... Handlers)
Pass the ErrorInfo(s) contained in E to their respective handlers.
LLVMErrorRef wrap (Error)
Conversion from Error to LLVMErrorRef for C error bindings.
raw_ostream & operator<< (raw_ostream &OS, const Error &E)
Detailed Description
Lightweight error class with error context and mandatory checking.
Instances of this class wrap a ErrorInfoBase pointer. Failure states are represented by setting the pointer to a ErrorInfoBase subclass instance containing information describing the failure. Success is represented by a null pointer value.
Instances of Error also contains a 'Checked' flag, which must be set before the destructor is called, otherwise the destructor will trigger a runtime error. This enforces at runtime the requirement that all Error instances be checked or returned to the caller.
There are two ways to set the checked flag, depending on what state the Error instance is in. For Error instances indicating success, it is sufficient to invoke the boolean conversion operator. E.g.:
Error foo(<...>);
if (auto E = foo(<...>))
  return E; // <- Return E if it is in the error state.
// We have verified that E was in the success state. It can now be safely
// destroyed.
A success value can not be dropped. For example, just calling 'foo(<...>)' without testing the return value will raise a runtime error, even if foo returns success.
For Error instances representing failure, you must use either the handleErrors or handleAllErrors function with a typed handler. E.g.:
class MyErrorInfo : public ErrorInfo<MyErrorInfo> {
  // Custom error info.
};
Error foo(<...>) { return make_error<MyErrorInfo>(...); }
auto E = foo(<...>); // <- foo returns failure with MyErrorInfo.
auto NewE =
  handleErrors(E,
    [](const MyErrorInfo &M) {
      // Deal with the error.
    },
    [](std::unique_ptr<OtherError> M) -> Error {
      if (canHandle(*M)) {
        // handle error.
        return Error::success();
      }
      // Couldn't handle this error instance. Pass it up the stack.
      return Error(std::move(M));
    );
// Note - we must check or return NewE in case any of the handlers
// returned a new error.
The handleAllErrors function is identical to handleErrors, except that it has a void return type, and requires all errors to be handled and no new errors be returned. It prevents errors (assuming they can all be handled) from having to be bubbled all the way to the top-level.
All Error instances must be checked before destruction, even if they're moved-assigned or constructed from Success values that have already been checked. This enforces checking through all levels of the call stack.
Definition at line 156 of file Error.h.
Constructor & Destructor Documentation
Error() [1/4]
llvm::Error::Error () inline protected
Create a success value. Prefer using 'Error::success()' for readability.
Definition at line 175 of file Error.h.
Error() [2/4]
llvm::Error::Error (const Error & Other) delete
Error() [3/4]
llvm::Error::Error (Error && Other) inline
Move-construct an error value.
The newly constructed error is considered unchecked, even if the source error had been checked. The original error becomes a checked Success value, regardless of its original state.
Definition at line 190 of file Error.h.
References move, and Other.
Error() [4/4]
llvm::Error::Error (std::unique_ptr< ErrorInfoBase > Payload) inline
Create an error value.
Prefer using the 'make_error' function, but this constructor can be useful when "re-throwing" errors from handlers.
Definition at line 197 of file Error.h.
~Error()
llvm::Error::~Error () inline
Destroy a Error.
Fails with a call to abort() if the error is unchecked.
Definition at line 226 of file Error.h.
References getPtr().
Referenced by llvm::JITSymbol::~JITSymbol().
Member Function Documentation
dynamicClassID()
const void* llvm::Error::dynamicClassID () const inline
Returns the dynamic class id of this error, or null if this is a success value.
Definition at line 246 of file Error.h.
References getPtr().
isA()
template<typename ErrT > bool llvm::Error::isA () const inline
Check whether one error is a subclass of another.
Definition at line 240 of file Error.h.
References getPtr().
operator bool()
llvm::Error::operator bool () inline explicit
Bool conversion.
Returns true if this Error is in a failure state, and false if it is in an accept state. If the error is in a Success state it will be considered checked.
Definition at line 234 of file Error.h.
References getPtr().
operator=() [1/2]
Error& llvm::Error::operator= (const Error & Other) delete
Referenced by llvm::MSVCPError::operator=().
operator=() [2/2]
Error& llvm::Error::operator= (Error && Other) inline
Move-assign an error value.
The current error must represent success, you you cannot overwrite an unhandled error. The current error is then considered unchecked. The source error becomes a checked success value, regardless of its original state.
Definition at line 209 of file Error.h.
References Other.
success()
ErrorSuccess llvm::Error::success () inline static
Create a success value.
Definition at line 330 of file Error.h.
Referenced by llvm::OverlapStats::accumulateCounts(), llvm::xray::Profile::addBlock(), llvm::jitlink::BlockAddressMap::addBlock(), llvm::pdb::DbiStreamBuilder::addDbgStream(), llvm::InstrProfSymtab::addFuncName(), llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::objcopy::coff::addGnuDebugLink(), llvm::objcopy::NameMatcher::addMatcher(), llvm::pdb::DbiStreamBuilder::addModuleSourceFile(), llvm::pdb::PDBFileBuilder::addNamedStream(), llvm::CodeGenPassBuilder< DerivedT >::addRegAssignmentFast(), llvm::CodeGenPassBuilder< DerivedT >::addRegAssignmentOptimized(), llvm::lto::Config::addSaveTemps(), addSection(), advanceToMetaBlock(), llvm::FilePermissionsApplier::apply(), llvm::jitlink::BasicLayout::apply(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::apply(), llvm::orc::LLJIT::applyDataLayout(), llvm::jitlink::loongarch::applyFixup(), llvm::jitlink::i386::applyFixup(), llvm::jitlink::aarch64::applyFixup(), llvm::jitlink::x86_64::applyFixup(), llvm::BitcodeReaderValueList::assignValue(), llvm::lto::backend(), llvm::codeview::CodeViewRecordIO::beginRecord(), llvm::jitlink::buildTables_MachO_arm64(), llvm::DWARFContext::checkAddressSizeSupported(), checkChars(), checkDyldCommand(), checkDylibCommand(), checkEncryptCommand(), llvm::gsym::Header::checkForError(), checkHashHdrVersion(), checkLinkerOptCommand(), llvm::object::Binary::checkOffset(), llvm::BinaryStream::checkOffsetForRead(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::checkOffsetForRead(), llvm::WritableBinaryStream::checkOffsetForWrite(), checkOperandCount(), checkOverlappingElement(), checkRecord(), checkRpathCommand(), checkSubCommand(), llvm::object::MachOObjectFile::checkSymbolTable(), checkThreadCommand(), checkVersCommand(), llvm::collectPGOFuncNameStrings(), llvm::pdb::SymbolStream::commit(), llvm::pdb::NamedStreamMap::commit(), llvm::codeview::DebugSymbolsSubsection::commit(), llvm::pdb::InfoStreamBuilder::commit(), llvm::codeview::DebugFrameDataSubsection::commit(), llvm::pdb::GSIHashStreamBuilder::commit(), llvm::pdb::TpiStreamBuilder::commit(), llvm::pdb::GSIStreamBuilder::commit(), llvm::codeview::DebugCrossModuleExportsSubsection::commit(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::pdb::ModuleDebugStreamRef::commit(), llvm::pdb::TpiStream::commit(), llvm::pdb::DbiStreamBuilder::commit(), llvm::codeview::DebugCrossModuleImportsSubsection::commit(), llvm::codeview::DebugChecksumsSubsection::commit(), llvm::codeview::DebugInlineeLinesSubsection::commit(), llvm::MutableBinaryByteStream::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commit(), llvm::codeview::DebugLinesSubsection::commit(), llvm::AppendingBinaryByteStream::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commitSymbolStream(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::xray::LogBuilderConsumer::consume(), llvm::codeview::consume(), llvm::xray::PipelineConsumer::consume(), llvm::codeview::consume_numeric(), llvm::gsym::ObjectFileTransformer::convert(), llvm::gsym::DwarfTransformer::convert(), llvm::InstrProfSymtab::create(), llvm::jitlink::createEHFrameRecorderPass(), llvm::pdb::DIASession::createFromExe(), llvm::pdb::NativeSession::createFromExe(), llvm::pdb::DIASession::createFromPdb(), llvm::pdb::NativeSession::createFromPdb(), llvm::pdb::NativeSession::createFromPdbPath(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVReader::createScopes(), llvm::logicalview::LVSplitContext::createSplitFolder(), llvm::jitlink::InProcessMemoryManager::deallocate(), llvm::object::ELFFile< ELFT >::decodeBBAddrMap(), llvm::compression::zlib::decompress(), llvm::objcopy::deepWriteArchive(), llvm::orc::JITDylib::define(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::deinitialize(), llvm::orc::InProcessMemoryMapper::deinitialize(), llvm::orc::deregisterFrameWrapper(), llvm::codeview::serialize_conditional_impl< T, U >::deserialize(), llvm::codeview::serialize_vector_tail_impl< T >::deserialize(), llvm::orc::shared::detail::ResultDeserializer< SPSRetTagT, RetT >::deserialize(), llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::deserialize(), llvm::codeview::SymbolDeserializer::deserializeAs(), llvm::codeview::TypeDeserializer::deserializeAs(), llvm::orc::UnsupportedExecutorProcessControl::disconnect(), llvm::orc::SelfExecutorProcessControl::disconnect(), llvm::logicalview::LVObject::doPrint(), llvm::logicalview::LVScopeRoot::doPrintMatches(), llvm::objcopy::wasm::dumpSectionToFile(), dumpSectionToFile(), llvm::RuntimeDyldImpl::emitCommonSymbols(), llvm::DWARFYAML::emitDebugAbbrev(), llvm::DWARFYAML::emitDebugInfo(), llvm::DWARFYAML::emitDebugLine(), llvm::DWARFYAML::emitDebugStr(), llvm::DWARFYAML::emitDebugStrOffsets(), llvm::lto::ThinBackendProc::emitFiles(), llvm::codeview::CodeViewRecordIO::endRecord(), llvm::BitstreamCursor::EnterSubBlock(), llvm::remarks::YAMLRemarkParser::error(), llvm::objcopy::xcoff::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::wasm::executeObjcopyOnBinary(), llvm::objcopy::coff::executeObjcopyOnBinary(), llvm::RangeListEntry::extract(), llvm::DWARFListTableBase< DWARFDebugRnglist >::extract(), llvm::AppleAcceleratorTable::extract(), llvm::DWARFDebugNames::NameIndex::extract(), llvm::DWARFDebugNames::extract(), llvm::object::extractOffloadBinaries(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::ifs::filterIFSSyms(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::finalize(), llvm::objcopy::elf::BinaryWriter::finalize(), llvm::RuntimeDyldImpl::finalizeAsync(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldCOFFX86_64::finalizeLoad(), llvm::RuntimeDyldImpl::finalizeLoad(), llvm::orc::EPCGenericRTDyldMemoryManager::finalizeMemory(), llvm::pdb::InfoStreamBuilder::finalizeMsfLayout(), llvm::pdb::TpiStreamBuilder::finalizeMsfLayout(), llvm::pdb::GSIStreamBuilder::finalizeMsfLayout(), llvm::pdb::DbiStreamBuilder::finalizeMsfLayout(), llvm::pdb::DbiModuleDescriptorBuilder::finalizeMsfLayout(), llvm::lto::finalizeOptimizationRemarks(), llvm::RuntimeDyldMachOX86_64::finalizeSection(), llvm::RuntimeDyldMachOI386::finalizeSection(), llvm::RuntimeDyldMachOARM::finalizeSection(), llvm::RuntimeDyldMachOAArch64::finalizeSection(), llvm::DWARFUnit::findLoclistFromOffset(), finishVisitation(), llvm::xray::TraceExpander::flush(), llvm::xray::BlockIndexer::flush(), llvm::codeview::forEachCodeViewRecord(), llvm::orc::SymbolLookupSet::forEachWithRemoval(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::fromCodeViewSymbol(), llvm::orc::shared::detail::fromSPSSerializable(), llvm::object::COFFObjectFile::getAuxSymbol(), llvm::orc::ExecutorProcessControl::getBootstrapSymbols(), llvm::object::ELFObjectFile< ELFT >::getBuildAttributes(), llvm::object::DelayImportDirectoryEntryRef::getDelayImportTable(), llvm::object::ExportDirectoryEntryRef::getDllName(), llvm::InstrProfReader::getError(), llvm::object::ExportDirectoryEntryRef::getExportRVA(), getExtensionVersion(), llvm::object::ExportDirectoryEntryRef::getForwardTo(), llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getFuncName(), llvm::coverage::accessors::getFuncNameViaRef(), llvm::object::COFFObjectFile::getHintName(), llvm::object::ImportedSymbolRef::getHintNameRVA(), llvm::object::DelayImportDirectoryEntryRef::getImportAddress(), llvm::object::ImportDirectoryEntryRef::getImportAddressTableRVA(), llvm::object::ImportDirectoryEntryRef::getImportLookupTableRVA(), getInt(), llvm::object::ImportDirectoryEntryRef::getName(), llvm::object::DelayImportDirectoryEntryRef::getName(), getObject(), llvm::getOffset(), llvm::object::ExportDirectoryEntryRef::getOrdinal(), llvm::object::ImportedSymbolRef::getOrdinal(), llvm::object::ExportDirectoryEntryRef::getOrdinalBase(), llvm::InstrProfReaderIndex< HashTableImpl >::getRecords(), llvm::object::COFFObjectFile::getRvaAndSizeAsBytes(), llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::ExportDirectoryEntryRef::getSymbolName(), llvm::object::ImportedSymbolRef::getSymbolName(), llvm::objcopy::xcoff::handleArgs(), llvm::objcopy::wasm::handleArgs(), handleArgs(), handleCompressedSection(), llvm::handleErrors(), handleMaybeNoDataFoundError(), llvm::handleSection(), hasInvalidBitcodeHeader(), ignoreStrippedErrors(), llvm::object::Archive::ChildFallibleIterator::inc(), llvm::object::Binary::initContent(), llvm::object::ELFObjectFile< ELFT >::initContent(), llvm::pdb::DbiModuleDescriptor::initialize(), llvm::codeview::DebugFrameDataSubsectionRef::initialize(), llvm::codeview::DebugStringTableSubsectionRef::initialize(), llvm::codeview::DebugSubsectionRecord::initialize(), llvm::pdb::PDBFileBuilder::initialize(), llvm::codeview::DebugChecksumsSubsectionRef::initialize(), llvm::codeview::DebugInlineeLinesSubsectionRef::initialize(), llvm::pdb::DbiModuleList::initialize(), llvm::codeview::DebugLinesSubsectionRef::initialize(), llvm::objcopy::elf::SectionBase::initialize(), llvm::objcopy::elf::Section::initialize(), llvm::objcopy::elf::SectionIndexSection::initialize(), llvm::objcopy::elf::SymbolTableSection::initialize(), llvm::objcopy::elf::RelocSectionWithSymtabBase< DynamicSymbolTableSection >::initialize(), initRelocations(), llvm::ELFAttributeParser::integerAttribute(), llvm::interpretDecimal(), llvm::object::ImportedSymbolRef::isOrdinal(), isValidMachOCannonicalName(), llvm::pdb::iterateModuleSubsections(), llvm::SimpleBitstreamCursor::JumpToBit(), llvm::sys::fs::TempFile::keep(), llvm::remarks::RemarkLinker::link(), llvm_orc_registerJITLoaderGDBAllocAction(), llvm_orc_registerJITLoaderGDBWrapper(), llvm::pdb::HashTable< llvm::support::detail::packed_endian_specific_integral >::load(), llvm::object::ResourceSectionRef::load(), LoadDIA(), llvm::logicalview::LVBinaryReader::loadGenericTargetInfo(), loadSectionContribs(), loadYAML(), llvm::localCache(), llvm::orc::ExecutionSession::lookup(), llvm::orc::lookupAndRecordAddrs(), llvm::orc::ExecutionSession::lookupFlags(), llvm::orc::Platform::lookupInitSymbols(), llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::makeValue(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), llvm::codeview::CodeViewRecordIO::mapEncodedInteger(), llvm::codeview::CodeViewRecordIO::mapEnum(), llvm::codeview::CodeViewRecordIO::mapGuid(), llvm::codeview::CodeViewRecordIO::mapInteger(), mapLocalVariableAddrRange(), mapNameAndUniqueName(), llvm::codeview::CodeViewRecordIO::mapObject(), llvm::codeview::CodeViewRecordIO::mapStringZ(), llvm::codeview::CodeViewRecordIO::mapStringZVectorZ(), llvm::codeview::CodeViewRecordIO::mapVectorN(), llvm::codeview::CodeViewRecordIO::mapVectorTail(), llvm::jitlink::markAllSymbolsLive(), llvm::objcopy::coff::Object::markSymbols(), llvm::Module::materialize(), llvm::Module::materializeAll(), llvm::Module::materializeMetadata(), llvm::InstrProfWriter::mergeProfileKind(), llvm::orc::DebugObjectManagerPlugin::modifyPassConfig(), llvm::orc::ObjectLinkingLayerJITLinkContext::modifyPassConfig(), llvm::jitlink::JITLinkContext::modifyPassConfig(), llvm::orc::COFFPlatform::notifyAdding(), llvm::orc::MachOPlatform::notifyAdding(), llvm::orc::ELFNixPlatform::notifyAdding(), llvm::orc::DebugObjectManagerPlugin::notifyEmitted(), llvm::orc::ObjectLinkingLayer::Plugin::notifyEmitted(), llvm::orc::EHFrameRegistrationPlugin::notifyEmitted(), llvm::orc::GDBJITDebugInfoRegistrationPlugin::notifyFailed(), llvm::orc::DebugObjectManagerPlugin::notifyFailed(), llvm::orc::EHFrameRegistrationPlugin::notifyFailed(), llvm::orc::GDBJITDebugInfoRegistrationPlugin::notifyRemovingResources(), llvm::orc::DebugObjectManagerPlugin::notifyRemovingResources(), llvm::orc::LazyCallThroughManager::notifyResolved(), llvm::jitlink::DWARFRecordSectionSplitter::operator()(), llvm::jitlink::SEHFrameKeepAlivePass::operator()(), llvm::jitlink::EHFrameEdgeFixer::operator()(), llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction >::operator()(), llvm::VarStreamArrayExtractor< InlineeSourceLine >::operator()(), llvm::VarStreamArrayExtractor< pdb::DbiModuleDescriptor >::operator()(), llvm::codeview::LineColumnExtractor::operator()(), llvm::VarStreamArrayExtractor< codeview::DebugSubsectionRecord >::operator()(), llvm::VarStreamArrayExtractor< codeview::CVRecord< Kind > >::operator()(), llvm::jitlink::EHFrameNullTerminator::operator()(), llvm::jitlink::CompactUnwindSplitter::operator()(), llvm::jitlink::i386::optimizeGOTAndStubAccesses(), llvm::jitlink::x86_64::optimizeGOTAndStubAccesses(), llvm::ifs::overrideIFSTarget(), llvm::BinaryStreamWriter::padToAlignment(), llvm::parallelForEachError(), parse(), llvm::DWARFDebugLine::Prologue::parse(), llvm::object::WindowsResourceParser::parse(), llvm::PassBuilder::parseAAPipeline(), llvm::ELFAttributeParser::parseAttributeList(), parseBlock(), llvm::remarks::BitstreamParserHelper::parseBlockInfoBlock(), llvm::pdb::PDBFile::parseFileHeaders(), llvm::PassBuilder::parsePassPipeline(), parseRecord(), llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::pdb::PDBFile::parseStreamData(), llvm::ELFAttributeParser::parseStringAttribute(), llvm::ELFAttributeParser::parseSubsection(), parseV5DirFileTables(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), llvm::InstrProfReaderRemapper::populateRemappings(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::populateRemappings(), llvm::orc::LLJITBuilderState::prepareForConstruction(), printBinaryIdsInternal(), llvm::object::COFFImportFile::printSymbolName(), llvm::object::ObjectFile::printSymbolName(), processLoadCommands(), processRemarkVersion(), processStrTab(), llvm::pdb::GSIHashTable::read(), llvm::SymbolRemappingReader::read(), llvm::BitstreamCursor::ReadAbbrevRecord(), llvm::BinaryStreamReader::readArray(), readBinaryIdsInternal(), llvm::BinaryByteStream::readBytes(), llvm::BinaryItemStream< T, Traits >::readBytes(), llvm::BinaryStreamReader::readBytes(), llvm::msf::MappedBlockStream::readBytes(), llvm::AppendingBinaryByteStream::readBytes(), readCoverageMappingData(), llvm::BinaryStreamReader::readCString(), llvm::BinaryStreamReader::readEnum(), llvm::BinaryStreamReader::readFixedString(), readGSIHashBuckets(), readGSIHashHeader(), readGSIHashRecords(), readInteger(), llvm::BinaryStreamReader::readInteger(), llvm::BinaryByteStream::readLongestContiguousChunk(), llvm::BinaryStreamReader::readLongestContiguousChunk(), llvm::BinaryItemStream< T, Traits >::readLongestContiguousChunk(), llvm::msf::MappedBlockStream::readLongestContiguousChunk(), llvm::AppendingBinaryByteStream::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::sys::fs::readNativeFileToEOF(), llvm::memprof::RawMemProfReader::readNextRecord(), llvm::BinaryStreamReader::readObject(), llvm::readPGOFuncNameStrings(), readSection(), ReadSignature(), llvm::pdb::readSparseBitVector(), llvm::BinaryStreamReader::readStreamRef(), llvm::object::readStringOrId(), readStruct(), llvm::coverage::RawCoverageReader::readULEB128(), llvm::BinaryStreamReader::readWideString(), llvm::orc::registerFrameWrapper(), llvm::orc::ExecutionSession::registerJITDispatchHandlers(), llvm::pdb::SymbolStream::reload(), llvm::pdb::PublicsStream::reload(), llvm::pdb::PDBStringTable::reload(), llvm::pdb::TpiStream::reload(), llvm::pdb::ModuleDebugStreamRef::reload(), llvm::pdb::DbiStream::reload(), llvm::pdb::GlobalsStream::reload(), llvm::objcopy::macho::Object::removeLoadCommands(), llvm::objcopy::elf::SectionBase::removeSectionReferences(), llvm::objcopy::elf::Section::removeSectionReferences(), llvm::objcopy::elf::RelocationSection::removeSectionReferences(), llvm::objcopy::elf::GroupSection::removeSectionReferences(), llvm::objcopy::elf::DynamicRelocationSection::removeSectionReferences(), llvm::objcopy::elf::Object::removeSections(), llvm::objcopy::coff::Object::removeSymbols(), llvm::objcopy::elf::SectionBase::removeSymbols(), llvm::objcopy::elf::SymbolTableSection::removeSymbols(), llvm::objcopy::elf::RelocationSection::removeSymbols(), llvm::objcopy::elf::GroupSection::removeSymbols(), llvm::objcopy::elf::Object::removeSymbols(), removeUnneededSections(), llvm::objcopy::elf::Object::replaceSections(), llvm::ErrorReported::reportedOrSuccess(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run(), llvm::orc::CtorDtorRunner::run(), llvm::orc::shared::WrapperFunctionCall::runWithSPSRet(), llvm::orc::FDSimpleRemoteEPCTransport::sendMessage(), llvm::remarks::RemarkLinker::serialize(), llvm::msf::MSFBuilder::setBlockMapAddr(), llvm::msf::MSFBuilder::setDirectoryBlocksHint(), llvm::remarks::RemarkStreamer::setFilter(), llvm::msf::MSFBuilder::setStreamSize(), llvm::DWARFLinker::setTargetDWARFVersion(), llvm::orc::setUpInactivePlatform(), llvm::setupLLVMOptimizationRemarks(), llvm::orc::setUpOrcPlatform(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::shutdown(), llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::shutdown(), llvm::BinaryStreamReader::skip(), llvm::BitstreamCursor::SkipBlock(), llvm::codeview::CodeViewRecordIO::skipPadding(), split(), llvm::orc::FDSimpleRemoteEPCTransport::start(), llvm::ELFAttributeParser::stringAttribute(), llvm::JITSymbol::takeError(), llvm::SoftInstrProfErrors::takeError(), llvm::Expected< ExpressionValue >::takeError(), llvm::orc::COFFPlatform::teardownJITDylib(), llvm::orc::MachOPlatform::teardownJITDylib(), llvm::orc::ELFNixPlatform::teardownJITDylib(), llvm::timeTraceProfilerWrite(), llvm::DWARFUnit::tryExtractDIEsIfNeeded(), llvm::orc::EPCDynamicLibrarySearchGenerator::tryToGenerate(), llvm::orc::DynamicLibrarySearchGenerator::tryToGenerate(), llvm::orc::StaticLibraryDefinitionGenerator::tryToGenerate(), llvm::orc::ReexportsGenerator::tryToGenerate(), updateAndRemoveSymbols(), llvm::orc::LocalIndirectStubsManager< TargetT >::updatePointer(), updateSection(), llvm::objcopy::elf::Object::updateSection(), llvm::StackMapParser< Endianness >::validateHeader(), llvm::ifs::validateIFSTarget(), validateMagicNumber(), llvm::InstrProfWriter::validateRecord(), llvm::msf::validateSuperBlock(), llvm::gsym::DwarfTransformer::verify(), llvm::xray::BlockVerifier::verify(), llvm::InlineAsm::verify(), llvm::GISelCSEInfo::verify(), llvm::xray::RecordPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::TraceExpander::visit(), llvm::xray::BlockIndexer::visit(), llvm::objcopy::elf::SectionWriter::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit(), llvm::objcopy::elf::IHexSectionWriterBase::visit(), llvm::objcopy::elf::IHexSectionWriter::visit(), llvm::xray::RecordInitializer::visit(), llvm::codeview::detail::visitDebugSubsections(), visitKnownMember(), visitKnownRecord(), llvm::DWARFDebugLoc::visitLocationList(), llvm::DWARFDebugLoclists::visitLocationList(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeVisitorCallbacks::visitMemberBegin(), llvm::codeview::TypeDumpVisitor::visitMemberBegin(), llvm::codeview::TypeVisitorCallbackPipeline::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::codeview::TypeVisitorCallbacks::visitMemberEnd(), llvm::codeview::TypeDumpVisitor::visitMemberEnd(), llvm::codeview::TypeVisitorCallbackPipeline::visitMemberEnd(), llvm::codeview::FieldListDeserializer::visitMemberEnd(), visitMemberRecord(), llvm::codeview::SymbolRecordMapping::visitSymbolBegin(), llvm::codeview::SymbolVisitorCallbacks::visitSymbolBegin(), llvm::codeview::SymbolVisitorCallbackPipeline::visitSymbolBegin(), llvm::codeview::SymbolSerializer::visitSymbolBegin(), llvm::codeview::SymbolRecordMapping::visitSymbolEnd(), llvm::codeview::SymbolVisitorCallbacks::visitSymbolEnd(), llvm::codeview::SymbolVisitorCallbackPipeline::visitSymbolEnd(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), llvm::codeview::CVSymbolVisitor::visitSymbolStream(), llvm::codeview::TypeVisitorCallbacks::visitTypeBegin(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), llvm::codeview::TypeVisitorCallbackPipeline::visitTypeBegin(), llvm::codeview::TypeDumpVisitor::visitTypeBegin(), llvm::codeview::TypeRecordMapping::visitTypeEnd(), llvm::codeview::TypeVisitorCallbacks::visitTypeEnd(), llvm::codeview::TypeDumpVisitor::visitTypeEnd(), llvm::codeview::TypeVisitorCallbackPipeline::visitTypeEnd(), llvm::codeview::DebugSubsectionVisitor::visitUnknown(), llvm::codeview::TypeVisitorCallbackPipeline::visitUnknownMember(), llvm::codeview::TypeVisitorCallbacks::visitUnknownMember(), llvm::codeview::TypeDumpVisitor::visitUnknownMember(), llvm::codeview::SymbolVisitorCallbackPipeline::visitUnknownSymbol(), llvm::codeview::SymbolVisitorCallbacks::visitUnknownSymbol(), llvm::codeview::TypeVisitorCallbacks::visitUnknownType(), llvm::codeview::TypeVisitorCallbackPipeline::visitUnknownType(), llvm::codeview::TypeDumpVisitor::visitUnknownType(), llvm::orc::ResourceTracker::withResourceKeyDo(), llvm::objcopy::wasm::Writer::write(), llvm::objcopy::xcoff::XCOFFWriter::write(), llvm::objcopy::macho::MachOWriter::write(), llvm::objcopy::elf::ELFWriter< ELFT >::write(), llvm::writeArchiveToStream(), llvm::BinaryStreamWriter::writeArray(), llvm::BinaryStreamWriter::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::BinaryStreamWriter::writeCString(), llvm::ifs::writeELFBinaryToFile(), llvm::writeFileAtomically(), llvm::ifs::writeIFSToOutputStream(), writePublics(), llvm::pdb::writeSparseBitVector(), llvm::BinaryStreamWriter::writeStreamRef(), llvm::InstrProfWriter::writeText(), llvm::MachO::TextAPIWriter::writeToStream(), llvm::object::writeUniversalBinaryToStream(), writeVariableSizedInteger(), llvm::object::writeWindowsResourceCOFF(), and llvm::ErrorAsOutParameter::~ErrorAsOutParameter().
Friends And Related Function Documentation
ErrorList
friend class ErrorList friend
Definition at line 160 of file Error.h.
Expected
template<typename T > friend class Expected friend
Definition at line 168 of file Error.h.
handleErrors
template<typename... HandlerTs> Error handleErrors (Error E, HandlerTs &&... Handlers) friend
Pass the ErrorInfo(s) contained in E to their respective handlers.
Any unhandled errors (or Errors returned by handlers) are re-concatenated and returned. Because this function returns an error, its result must also be checked or returned. If you intend to handle all errors use handleAllErrors (which returns void, and will abort() on unhandled errors) instead.
Definition at line 943 of file Error.h.
operator<<
raw_ostream& operator<< (raw_ostream & OS, const Error & E) friend
Definition at line 314 of file Error.h.
wrap
LLVMErrorRef wrap (Error Err) friend
Conversion from Error to LLVMErrorRef for C error bindings.
Definition at line 1401 of file Error.h.
The documentation for this class was generated from the following file:
include/llvm/Support/Error.h