LLVM: llvm::XtensaMCAsmBackend Class Reference
llvm::XtensaMCAsmBackend Class Reference
Public Member Functions
XtensaMCAsmBackend (uint8_t osABI, bool isLE)
unsigned getNumFixupKinds () const override
Get the number of target specific fixup kinds.
const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const override
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const override
Check whether the given instruction may need relaxation.
bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value, const MCRelaxableFragment *Fragment, const MCAsmLayout &Layout) const override
Simple predicate for targets where !Resolved implies requiring relaxation.
void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const override
Relax the instruction in the given fragment to the next wider instruction.
bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const override
Write an (optimal) nop sequence of Count bytes to the given output.
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void emitInstructionBegin (MCObjectStreamer &OS, const MCInst &Inst, const MCSubtargetInfo &STI)
Give the target a chance to manipulate state related to instruction alignment (e.g.
virtual void emitInstructionEnd (MCObjectStreamer &OS, const MCInst &Inst)
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual void finishLayout (MCAssembler const &Asm, MCAsmLayout &Layout) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint32_t generateCompactUnwindEncoding (ArrayRef< MCCFIInstruction >) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool isMicroMips (const MCSymbol *Sym) const
Check whether a given symbol has been flagged with MICROMIPS flag.
virtual std::optional< MCFixupKind > getFixupKind (StringRef Name) const
Map a relocation name used in .reloc to a fixup kind.
virtual bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target)
Hook to check if a relocation is needed for some target specific reason.
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, const MCAsmLayout &Layout, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual bool evaluateTargetFixup (const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFixup &Fixup, const MCFragment *DF, const MCValue &Target, uint64_t &Value, bool &WasForced)
virtual bool fixupNeedsRelaxationAdvanced (const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout, const bool WasForced) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
virtual bool relaxDwarfLineAddr (MCDwarfLineAddrFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const
virtual bool relaxDwarfCFA (MCDwarfCallFrameFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const
Additional Inherited Members
Public Attributes inherited from llvm::MCAsmBackend
const support::endianness Endian
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (support::endianness Endian)
Detailed Description
Definition at line 27 of file XtensaAsmBackend.cpp.
Constructor & Destructor Documentation
XtensaMCAsmBackend()
llvm::XtensaMCAsmBackend::XtensaMCAsmBackend (uint8_t osABI, bool isLE) inline
Definition at line 32 of file XtensaAsmBackend.cpp.
Member Function Documentation
applyFixup()
void XtensaMCAsmBackend::applyFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo * STI) const override virtual
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Errors (such as an out of range fixup value) should be reported via Ctx. The STI is present only for fragments of type MCRelaxableFragment and MCDataFragment with hasInstructions() == true.
Implements llvm::MCAsmBackend.
Definition at line 145 of file XtensaAsmBackend.cpp.
References adjustFixupValue(), llvm::HexStyle::Asm, llvm::Data, Fixup, getFixupKindInfo(), getSize(), i, Info, and llvm::Offset.
createObjectTargetWriter()
std::unique_ptr<MCObjectTargetWriter> llvm::XtensaMCAsmBackend::createObjectTargetWriter () const inline override virtual
Implements llvm::MCAsmBackend.
Definition at line 53 of file XtensaAsmBackend.cpp.
References llvm::createXtensaObjectWriter().
fixupNeedsRelaxation()
bool XtensaMCAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout) const override virtual
Simple predicate for targets where !Resolved implies requiring relaxation.
Implements llvm::MCAsmBackend.
Definition at line 174 of file XtensaAsmBackend.cpp.
getFixupKindInfo()
const MCFixupKindInfo & XtensaMCAsmBackend::getFixupKindInfo (MCFixupKind Kind) const override virtual
Get information on a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 60 of file XtensaAsmBackend.cpp.
References assert(), llvm::FirstTargetFixupKind, llvm::MCFixupKindInfo::FKF_IsAlignedDownTo32Bits, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), getNumFixupKinds(), and llvm::Xtensa::NumTargetFixupKinds.
Referenced by applyFixup().
getNumFixupKinds()
unsigned llvm::XtensaMCAsmBackend::getNumFixupKinds () const inline override virtual
Get the number of target specific fixup kinds.
Implements llvm::MCAsmBackend.
Definition at line 35 of file XtensaAsmBackend.cpp.
References llvm::Xtensa::NumTargetFixupKinds.
Referenced by getFixupKindInfo().
mayNeedRelaxation()
bool XtensaMCAsmBackend::mayNeedRelaxation (const MCInst & Inst, const MCSubtargetInfo & STI) const override virtual
Check whether the given instruction may need relaxation.
Parameters
Inst - The instruction to test.
STI - The MCSubtargetInfo in effect when the instruction was encoded.
Reimplemented from llvm::MCAsmBackend.
Definition at line 169 of file XtensaAsmBackend.cpp.
relaxInstruction()
void XtensaMCAsmBackend::relaxInstruction (MCInst & Inst, const MCSubtargetInfo & STI) const override virtual
Relax the instruction in the given fragment to the next wider instruction.
Parameters
[out] Inst The instruction to relax, which is also the relaxed instruction.
STI the subtarget information for the associated instruction.
Reimplemented from llvm::MCAsmBackend.
Definition at line 180 of file XtensaAsmBackend.cpp.
writeNopData()
bool XtensaMCAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const override virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implements llvm::MCAsmBackend.
Definition at line 183 of file XtensaAsmBackend.cpp.
References i, OS, llvm::report_fatal_error(), uint64_t, and llvm::raw_ostream::write().
The documentation for this class was generated from the following file:
lib/Target/Xtensa/MCTargetDesc/XtensaAsmBackend.cpp