LLVM: llvm::DWARFDebugInfoEntry Class Reference
llvm::DWARFDebugInfoEntry Class Reference
DWARFDebugInfoEntry - A DIE with only the minimum required data.
#include "llvm/DebugInfo/DWARF/DWARFDebugInfoEntry.h"
Public Member Functions
DWARFDebugInfoEntry ()=default
bool extractFast (const DWARFUnit &U, uint64_t *OffsetPtr, const DWARFDataExtractor &DebugInfoData, uint64_t UEndOffset, uint32_t ParentIdx)
Extracts a debug info entry, which is a child of a given unit, starting at a given offset.
uint64_t getOffset () const
std::optional< uint32_t > getParentIdx () const
Returns index of the parent die.
std::optional< uint32_t > getSiblingIdx () const
Returns index of the sibling die.
void setSiblingIdx (uint32_t Idx)
Set index of sibling.
dwarf::Tag getTag () const
bool hasChildren () const
const DWARFAbbreviationDeclaration * getAbbreviationDeclarationPtr () const
Detailed Description
DWARFDebugInfoEntry - A DIE with only the minimum required data.
Definition at line 22 of file DWARFDebugInfoEntry.h.
Constructor & Destructor Documentation
DWARFDebugInfoEntry()
llvm::DWARFDebugInfoEntry::DWARFDebugInfoEntry () default
Member Function Documentation
extractFast()
bool DWARFDebugInfoEntry::extractFast (const DWARFUnit & U, uint64_t * OffsetPtr, const DWARFDataExtractor & DebugInfoData, uint64_t UEndOffset, uint32_t ParentIdx)
Extracts a debug info entry, which is a child of a given unit, starting at a given offset.
If DIE can't be extracted, returns false and doesn't change OffsetPtr. High performance extraction should use this call.
Definition at line 22 of file DWARFDebugInfoEntry.cpp.
References assert(), llvm::createStringError(), llvm::DWARFUnit::getAbbreviations(), llvm::DWARFUnit::getAbbreviationsOffset(), llvm::DWARFUnit::getContext(), llvm::DWARFUnit::getFormParams(), llvm::DWARFUnit::getNextUnitOffset(), llvm::DWARFUnit::getOffset(), llvm::DataExtractor::getULEB128(), llvm::DWARFContext::getWarningHandler(), llvm::invalid_argument, llvm::DataExtractor::isValidOffset(), llvm::DWARFFormValue::skipValue(), and uint64_t.
getAbbreviationDeclarationPtr()
const DWARFAbbreviationDeclaration* llvm::DWARFDebugInfoEntry::getAbbreviationDeclarationPtr () const inline
Definition at line 72 of file DWARFDebugInfoEntry.h.
Referenced by llvm::DWARFDie::getAbbreviationDeclarationPtr(), and llvm::DWARFDie::attribute_iterator::operator++().
getOffset()
uint64_t llvm::DWARFDebugInfoEntry::getOffset () const inline
Definition at line 45 of file DWARFDebugInfoEntry.h.
Referenced by llvm::DWARFDie::getOffset().
getParentIdx()
std::optional<uint32_t> llvm::DWARFDebugInfoEntry::getParentIdx () const inline
Returns index of the parent die.
Definition at line 48 of file DWARFDebugInfoEntry.h.
Referenced by llvm::DWARFUnit::getParentEntry(), and llvm::DWARFUnit::getPreviousSiblingEntry().
getSiblingIdx()
std::optional<uint32_t> llvm::DWARFDebugInfoEntry::getSiblingIdx () const inline
Returns index of the sibling die.
Definition at line 56 of file DWARFDebugInfoEntry.h.
Referenced by llvm::DWARFUnit::getLastChildEntry(), and llvm::DWARFUnit::getSiblingEntry().
getTag()
dwarf::Tag llvm::DWARFDebugInfoEntry::getTag () const inline
Definition at line 66 of file DWARFDebugInfoEntry.h.
References llvm::DWARFAbbreviationDeclaration::getTag().
hasChildren()
bool llvm::DWARFDebugInfoEntry::hasChildren () const inline
Definition at line 70 of file DWARFDebugInfoEntry.h.
References llvm::DWARFAbbreviationDeclaration::hasChildren().
Referenced by llvm::DWARFUnit::getFirstChildEntry(), llvm::DWARFUnit::getLastChildEntry(), and llvm::DWARFDie::hasChildren().
setSiblingIdx()
void llvm::DWARFDebugInfoEntry::setSiblingIdx (uint32_t Idx) inline
Set index of sibling.
Definition at line 64 of file DWARFDebugInfoEntry.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugInfoEntry.h
lib/DebugInfo/DWARF/DWARFDebugInfoEntry.cpp