LLVM: llvm::jitlink::i386::PLTTableManager Class Reference
llvm::jitlink::i386::PLTTableManager Class Reference
Procedure Linkage Table Builder.
#include "llvm/ExecutionEngine/JITLink/i386.h"
Public Member Functions
PLTTableManager (GOTTableManager &GOT)
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Section & getStubsSection (LinkGraph &G)
Public Member Functions inherited from llvm::jitlink::TableManager< PLTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
Static Public Member Functions
static StringRef getSectionName ()
Public Attributes
GOTTableManager & GOT
Section * PLTSection = nullptr
Detailed Description
Procedure Linkage Table Builder.
Definition at line 402 of file i386.h.
Constructor & Destructor Documentation
PLTTableManager()
llvm::jitlink::i386::PLTTableManager::PLTTableManager (GOTTableManager & GOT) inline
Definition at line 404 of file i386.h.
Member Function Documentation
createEntry()
Symbol& llvm::jitlink::i386::PLTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 424 of file i386.h.
References llvm::jitlink::i386::createAnonymousPointerJumpStub(), and G.
getSectionName()
static StringRef llvm::jitlink::i386::PLTTableManager::getSectionName () inline static
Definition at line 406 of file i386.h.
getStubsSection()
Section& llvm::jitlink::i386::PLTTableManager::getStubsSection (LinkGraph & G) inline
Definition at line 430 of file i386.h.
References llvm::orc::Exec, G, and llvm::orc::Read.
visitEdge()
bool llvm::jitlink::i386::PLTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 408 of file i386.h.
References B, llvm::jitlink::i386::BranchPCRel32, llvm::jitlink::i386::BranchPCRel32ToPtrJumpStubBypassable, llvm::dbgs(), DEBUG_WITH_TYPE, E, llvm::formatv(), and G.
Member Data Documentation
GOT
GOTTableManager& llvm::jitlink::i386::PLTTableManager::GOT
Definition at line 437 of file i386.h.
PLTSection
Section* llvm::jitlink::i386::PLTTableManager::PLTSection = nullptr
Definition at line 438 of file i386.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/i386.h