LLVM: llvm::ThunkInserter< Derived, InsertedThunksTy > Class Template Reference
llvm::ThunkInserter< Derived, InsertedThunksTy > Class Template Reference
#include "llvm/CodeGen/IndirectThunks.h"
Public Member Functions
void init (Module &M)
bool run (MachineModuleInfo &MMI, MachineFunction &MF)
Protected Member Functions
void doInitialization (Module &M)
void createThunkFunction (MachineModuleInfo &MMI, StringRef Name, bool Comdat=true)
Protected Attributes
InsertedThunksTy InsertedThunks
Detailed Description
template<typename Derived, typename InsertedThunksTy = bool>
class llvm::ThunkInserter< Derived, InsertedThunksTy >
Definition at line 25 of file IndirectThunks.h.
Member Function Documentation
createThunkFunction()
template<typename Derived , typename InsertedThunksTy > void llvm::ThunkInserter< Derived, InsertedThunksTy >::createThunkFunction (MachineModuleInfo & MMI, StringRef Name, bool Comdat = true) protected
Definition at line 48 of file IndirectThunks.h.
References assert(), B, llvm::Function::Create(), F, llvm::FunctionType::get(), llvm::MachineModuleInfo::getModule(), llvm::Type::getVoidTy(), llvm::GlobalValue::HiddenVisibility, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceODRLinkage, and M.
doInitialization()
template<typename Derived , typename InsertedThunksTy = bool> void llvm::ThunkInserter< Derived, InsertedThunksTy >::doInitialization (Module & M) inline protected
Definition at line 34 of file IndirectThunks.h.
init()
template<typename Derived , typename InsertedThunksTy = bool> void llvm::ThunkInserter< Derived, InsertedThunksTy >::init (Module & M) inline
Definition at line 39 of file IndirectThunks.h.
References llvm::ThunkInserter< Derived, InsertedThunksTy >::InsertedThunks, and M.
run()
template<typename Derived , typename InsertedThunksTy > bool llvm::ThunkInserter< Derived, InsertedThunksTy >::run (MachineModuleInfo & MMI, MachineFunction & MF)
Definition at line 91 of file IndirectThunks.h.
References llvm::MachineFunction::getName(), and llvm::StringRef::startswith().
Member Data Documentation
InsertedThunks
template<typename Derived , typename InsertedThunksTy = bool> InsertedThunksTy llvm::ThunkInserter< Derived, InsertedThunksTy >::InsertedThunks protected
Definition at line 33 of file IndirectThunks.h.
Referenced by llvm::ThunkInserter< Derived, InsertedThunksTy >::init().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/IndirectThunks.h