LLVM: llvm::objcopy::NameMatcher Class Reference
llvm::objcopy::NameMatcher Class Reference
#include "llvm/ObjCopy/CommonConfig.h"
Public Member Functions
Error addMatcher (Expected< NameOrPattern > Matcher)
bool matches (StringRef S) const
bool empty () const
Detailed Description
Definition at line 131 of file CommonConfig.h.
Member Function Documentation
addMatcher()
Error llvm::objcopy::NameMatcher::addMatcher (Expected< NameOrPattern > Matcher) inline
Definition at line 137 of file CommonConfig.h.
References llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), move, llvm::Error::success(), and llvm::Expected< T >::takeError().
empty()
bool llvm::objcopy::NameMatcher::empty () const inline
Definition at line 155 of file CommonConfig.h.
References llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::empty().
Referenced by llvm::objcopy::ConfigManager::getCOFFConfig(), llvm::objcopy::ConfigManager::getMachOConfig(), llvm::objcopy::ConfigManager::getWasmConfig(), llvm::objcopy::ConfigManager::getXCOFFConfig(), llvm::objcopy::coff::handleArgs(), removeSections(), llvm::objcopy::wasm::removeSections(), replaceAndRemoveSections(), and updateAndRemoveSymbols().
matches()
bool llvm::objcopy::NameMatcher::matches (StringRef S) const inline
Definition at line 150 of file CommonConfig.h.
References llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::contains(), llvm::is_contained(), and S.
Referenced by llvm::objcopy::coff::handleArgs(), removeSections(), llvm::objcopy::wasm::removeSections(), replaceAndRemoveSections(), and updateAndRemoveSymbols().
The documentation for this class was generated from the following file:
include/llvm/ObjCopy/CommonConfig.h