LLVM: llvm::LiveRegSet Class Reference
llvm::LiveRegSet Class Reference
A set of live virtual registers and physical register units.
#include "llvm/CodeGen/RegisterPressure.h"
Public Member Functions
void clear ()
void init (const MachineRegisterInfo &MRI)
LaneBitmask contains (Register Reg) const
LaneBitmask insert (RegisterMaskPair Pair)
Mark the Pair.LaneMask lanes of Pair.Reg as live.
LaneBitmask erase (RegisterMaskPair Pair)
Clears the Pair.LaneMask lanes of Pair.Reg (mark them as dead).
size_t size () const
template<typename ContainerT >
void appendTo (ContainerT &To) const
Detailed Description
A set of live virtual registers and physical register units.
This is a wrapper around a SparseSet which deals with mapping register unit and virtual register indexes to an index usable by the sparse set.
Definition at line 259 of file RegisterPressure.h.
Member Function Documentation
appendTo()
template<typename ContainerT > void llvm::LiveRegSet::appendTo (ContainerT & To) const inline
Definition at line 332 of file RegisterPressure.h.
References P.
Referenced by llvm::RegPressureTracker::closeBottom(), and llvm::RegPressureTracker::closeTop().
clear()
void LiveRegSet::clear ()
Definition at line 233 of file RegisterPressure.cpp.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::clear().
Referenced by llvm::RegPressureTracker::reset().
contains()
LaneBitmask llvm::LiveRegSet::contains (Register Reg) const inline
Definition at line 294 of file RegisterPressure.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::find(), llvm::LaneBitmask::getNone(), and I.
Referenced by llvm::RegPressureTracker::advance(), llvm::RegPressureTracker::bumpDeadDefs(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), and llvm::RegPressureTracker::recede().
erase()
LaneBitmask llvm::LiveRegSet::erase (RegisterMaskPair Pair) inline
Clears the Pair.LaneMask lanes of Pair.Reg (mark them as dead).
Returns the previously live lanes of Pair.Reg.
Definition at line 317 of file RegisterPressure.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::find(), llvm::LaneBitmask::getNone(), I, llvm::RegisterMaskPair::LaneMask, and llvm::RegisterMaskPair::RegUnit.
Referenced by llvm::RegPressureTracker::advance(), and llvm::RegPressureTracker::recede().
init()
void LiveRegSet::init (const MachineRegisterInfo & MRI)
Definition at line 225 of file RegisterPressure.cpp.
References llvm::MCRegisterInfo::getNumRegs(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), MRI, llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::setUniverse(), and TRI.
Referenced by llvm::RegPressureTracker::init().
insert()
LaneBitmask llvm::LiveRegSet::insert (RegisterMaskPair Pair) inline
Mark the Pair.LaneMask lanes of Pair.Reg as live.
Returns the previously live lanes of Pair.Reg.
Definition at line 304 of file RegisterPressure.h.
References llvm::LaneBitmask::getNone(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::insert(), llvm::RegisterMaskPair::LaneMask, and llvm::RegisterMaskPair::RegUnit.
Referenced by llvm::RegPressureTracker::addLiveRegs(), llvm::RegPressureTracker::advance(), and llvm::RegPressureTracker::recede().
size()
size_t llvm::LiveRegSet::size () const inline
Definition at line 327 of file RegisterPressure.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::size().
Referenced by llvm::RegPressureTracker::closeBottom(), llvm::RegPressureTracker::closeRegion(), and llvm::RegPressureTracker::closeTop().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/RegisterPressure.h
lib/CodeGen/RegisterPressure.cpp