LLVM: llvm::legacy::PassManager Class Reference
llvm::legacy::PassManager Class Reference
PassManager manages ModulePassManagers.
#include "llvm/IR/LegacyPassManager.h"
Public Member Functions
PassManager ()
Create new pass manager.
~PassManager () override
void add (Pass *P) override
Add a pass to the queue of passes to run.
bool run (Module &M)
run - Execute all of the passes scheduled for execution.
Public Member Functions inherited from llvm::legacy::PassManagerBase
virtual ~PassManagerBase ()
Detailed Description
PassManager manages ModulePassManagers.
Definition at line 52 of file LegacyPassManager.h.
Constructor & Destructor Documentation
PassManager()
llvm::legacy::PassManager::PassManager ()
Create new pass manager.
Definition at line 1655 of file LegacyPassManager.cpp.
References llvm::PMDataManager::setTopLevelManager().
~PassManager()
llvm::legacy::PassManager::~PassManager () override
Definition at line 1661 of file LegacyPassManager.cpp.
Member Function Documentation
add()
void llvm::legacy::PassManager::add (Pass * P) override virtual
Add a pass to the queue of passes to run.
This passes ownership of the Pass to the PassManager. When the PassManager is destroyed, the pass will be destroyed as well, so there is no need to delete the pass. This may even destroy the pass right away if it is found to be redundant. This implies that all passes MUST be allocated with 'new'.
Implements llvm::legacy::PassManagerBase.
Reimplemented in llvm::DebugifyCustomPassManager.
Definition at line 1665 of file LegacyPassManager.cpp.
References llvm::legacy::PassManagerImpl::add(), and P.
Referenced by llvm::DebugifyCustomPassManager::add(), and llvm::lintModule().
run()
bool llvm::legacy::PassManager::run (Module & M)
run - Execute all of the passes scheduled for execution.
Keep track of whether any of the passes modifies the module, and if so, return true.
Definition at line 1671 of file LegacyPassManager.cpp.
References M, and llvm::legacy::PassManagerImpl::run().
Referenced by codegen(), llvm::MCJIT::emitObject(), llvm::lintModule(), and llvm::orc::SimpleCompiler::operator()().
The documentation for this class was generated from the following files:
include/llvm/IR/LegacyPassManager.h
lib/IR/LegacyPassManager.cpp