LLVM: llvm::HexagonSubtarget Class Reference
llvm::HexagonSubtarget Class Reference
#include "Target/Hexagon/HexagonSubtarget.h"
Classes
struct BankConflictMutation
struct CallMutation
struct HVXMemLatencyMutation
struct UsrOverflowMutation
Public Member Functions
HexagonSubtarget (const Triple &TT, StringRef CPU, StringRef FS, const TargetMachine &TM)
const Triple & getTargetTriple () const
bool isEnvironmentMusl () const
const InstrItineraryData * getInstrItineraryData () const override
getInstrItins - Return the instruction itineraries based on subtarget selection.
const HexagonInstrInfo * getInstrInfo () const override
const HexagonRegisterInfo * getRegisterInfo () const override
const HexagonTargetLowering * getTargetLowering () const override
const HexagonFrameLowering * getFrameLowering () const override
const HexagonSelectionDAGInfo * getSelectionDAGInfo () const override
HexagonSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
bool isXRaySupported () const override
bool hasV5Ops () const
bool hasV5OpsOnly () const
bool hasV55Ops () const
bool hasV55OpsOnly () const
bool hasV60Ops () const
bool hasV60OpsOnly () const
bool hasV62Ops () const
bool hasV62OpsOnly () const
bool hasV65Ops () const
bool hasV65OpsOnly () const
bool hasV66Ops () const
bool hasV66OpsOnly () const
bool hasV67Ops () const
bool hasV67OpsOnly () const
bool hasV68Ops () const
bool hasV68OpsOnly () const
bool hasV69Ops () const
bool hasV69OpsOnly () const
bool hasV71Ops () const
bool hasV71OpsOnly () const
bool hasV73Ops () const
bool hasV73OpsOnly () const
bool useAudioOps () const
bool useCompound () const
bool useLongCalls () const
bool useMemops () const
bool usePackets () const
bool useNewValueJumps () const
bool useNewValueStores () const
bool useSmallData () const
bool useUnsafeMath () const
bool useZRegOps () const
bool useCabac () const
bool isTinyCore () const
bool isTinyCoreWithDuplex () const
bool useHVXIEEEFPOps () const
bool useHVXQFloatOps () const
bool useHVXFloatingPoint () const
bool useHVXOps () const
bool useHVXV60Ops () const
bool useHVXV62Ops () const
bool useHVXV65Ops () const
bool useHVXV66Ops () const
bool useHVXV67Ops () const
bool useHVXV68Ops () const
bool useHVXV69Ops () const
bool useHVXV71Ops () const
bool useHVXV73Ops () const
bool useHVX128BOps () const
bool useHVX64BOps () const
bool hasMemNoShuf () const
bool hasReservedR19 () const
bool usePredicatedCalls () const
bool noreturnStackElim () const
bool useBSBScheduling () const
bool enableMachineScheduler () const override
bool enableMachineSchedDefaultSched () const override
AntiDepBreakMode getAntiDepBreakMode () const override
bool enablePostRAScheduler () const override
True if the subtarget should run a scheduler after register allocation.
bool enableSubRegLiveness () const override
const std::string & getCPUString () const
const Hexagon::ArchEnum & getHexagonArchVersion () const
void getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> &Mutations) const override
void getSMSMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> &Mutations) const override
bool useAA () const override
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
void adjustSchedDependency (SUnit *Def, int DefOpIdx, SUnit *Use, int UseOpIdx, SDep &Dep) const override
Perform target specific adjustments to the latency of a schedule dependency.
unsigned getVectorLength () const
ArrayRef< MVT > getHVXElementTypes () const
bool isHVXElementType (MVT Ty, bool IncludeBool=false) const
bool isHVXVectorType (EVT VecTy, bool IncludeBool=false) const
bool isTypeForHVX (Type *VecTy, bool IncludeBool=false) const
Align getTypeAlignment (MVT Ty) const
unsigned getL1CacheLineSize () const
unsigned getL1PrefetchDistance () const
Intrinsic::ID getIntrinsicId (unsigned Opc) const
Public Attributes
Hexagon::ArchEnum HexagonArchVersion
Hexagon::ArchEnum HexagonHVXVersion = Hexagon::ArchEnum::NoArch
CodeGenOpt::Level OptLevel
bool UseBSBScheduling
True if the target should use Back-Skip-Back scheduling.
Detailed Description
Definition at line 43 of file HexagonSubtarget.h.
Constructor & Destructor Documentation
HexagonSubtarget()
HexagonSubtarget::HexagonSubtarget (const Triple & TT, StringRef CPU, StringRef FS, const TargetMachine & TM)
Definition at line 80 of file HexagonSubtarget.cpp.
References llvm::Hexagon_MC::addArchSubtarget(), assert(), llvm::X86AS::FS, llvm::InstrItineraryData::Itineraries, and string.
Member Function Documentation
adjustSchedDependency()
void HexagonSubtarget::adjustSchedDependency (SUnit * Def, int DefOpIdx, SUnit * Use, int UseOpIdx, SDep & Dep) const override
Perform target specific adjustments to the latency of a schedule dependency.
Definition at line 439 of file HexagonSubtarget.cpp.
References llvm::HexagonInstrInfo::canExecuteInBundle(), llvm::SmallSet< T, N, C >::clear(), llvm::M68kBeads::DReg, EnableDotCurSched, getInstrInfo(), llvm::SDep::getLatency(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::HexagonInstrInfo::getOperandLatency(), llvm::MachineOperand::getReg(), llvm::SDep::isArtificial(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegSequence(), llvm::HexagonInstrInfo::isToBeScheduledASAP(), llvm::MachineOperand::isUse(), llvm::Latency, llvm::max(), and llvm::SDep::setLatency().
enableMachineSchedDefaultSched()
bool llvm::HexagonSubtarget::enableMachineSchedDefaultSched () const inline override
Definition at line 279 of file HexagonSubtarget.h.
enableMachineScheduler()
bool HexagonSubtarget::enableMachineScheduler () const override
Definition at line 532 of file HexagonSubtarget.cpp.
References DisableHexagonMISched, and llvm::cl::Option::getNumOccurrences().
enablePostRAScheduler()
bool llvm::HexagonSubtarget::enablePostRAScheduler () const inline override
True if the subtarget should run a scheduler after register allocation.
Definition at line 286 of file HexagonSubtarget.h.
enableSubRegLiveness()
bool HexagonSubtarget::enableSubRegLiveness () const override
Definition at line 727 of file HexagonSubtarget.cpp.
References EnableSubregLiveness.
getAntiDepBreakMode()
AntiDepBreakMode llvm::HexagonSubtarget::getAntiDepBreakMode () const inline override
Definition at line 283 of file HexagonSubtarget.h.
getCPUString()
const std::string& llvm::HexagonSubtarget::getCPUString () const inline
Definition at line 290 of file HexagonSubtarget.h.
getFrameLowering()
const HexagonFrameLowering* llvm::HexagonSubtarget::getFrameLowering () const inline override
Definition at line 131 of file HexagonSubtarget.h.
Referenced by llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), and llvm::HexagonDAGToDAGISel::SelectFrameIndex().
getHexagonArchVersion()
const Hexagon::ArchEnum& llvm::HexagonSubtarget::getHexagonArchVersion () const inline
Definition at line 292 of file HexagonSubtarget.h.
References HexagonArchVersion.
Referenced by hasV55Ops(), hasV55OpsOnly(), hasV5Ops(), hasV5OpsOnly(), hasV60Ops(), hasV60OpsOnly(), hasV62Ops(), hasV62OpsOnly(), hasV65Ops(), hasV65OpsOnly(), hasV66Ops(), hasV66OpsOnly(), hasV67Ops(), hasV67OpsOnly(), hasV68Ops(), hasV68OpsOnly(), hasV69Ops(), hasV69OpsOnly(), hasV71Ops(), hasV71OpsOnly(), hasV73Ops(), and hasV73OpsOnly().
getHVXElementTypes()
ArrayRef<MVT> llvm::HexagonSubtarget::getHVXElementTypes () const inline
Definition at line 322 of file HexagonSubtarget.h.
References llvm::ArrayRef(), llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, useHVXFloatingPoint(), and useHVXV68Ops().
Referenced by isHVXElementType(), and isHVXVectorType().
getInstrInfo()
const HexagonInstrInfo* llvm::HexagonSubtarget::getInstrInfo () const inline override
Definition at line 124 of file HexagonSubtarget.h.
References InstrInfo.
Referenced by adjustSchedDependency(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::HexagonTargetLowering::getPostIndexedAddressParts(), llvm::HexagonDAGToDAGISel::runOnMachineFunction(), and llvm::HexagonConvergingVLIWScheduler::SchedulingCost().
getInstrItineraryData()
const InstrItineraryData* llvm::HexagonSubtarget::getInstrItineraryData () const inline override
getInstrItins - Return the instruction itineraries based on subtarget selection.
Definition at line 121 of file HexagonSubtarget.h.
Referenced by llvm::HexagonInstrInfo::getUnits().
getIntrinsicId()
Intrinsic::ID HexagonSubtarget::getIntrinsicId (unsigned Opc) const
Definition at line 731 of file HexagonSubtarget.cpp.
References B, llvm::sys::path::begin(), BH, llvm::sys::path::end(), error, getVectorLength(), llvm_unreachable, llvm::lower_bound(), llvm::NVPTX::PTXLdStInstCode::Scalar, llvm::sort(), and llvm::to_string().
getL1CacheLineSize()
unsigned HexagonSubtarget::getL1CacheLineSize () const
Definition at line 719 of file HexagonSubtarget.cpp.
Referenced by llvm::HexagonTTIImpl::getCacheLineSize().
getL1PrefetchDistance()
unsigned HexagonSubtarget::getL1PrefetchDistance () const
Definition at line 723 of file HexagonSubtarget.cpp.
Referenced by llvm::HexagonTTIImpl::getPrefetchDistance().
getPostRAMutations()
void HexagonSubtarget::getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> & Mutations) const override
Definition at line 516 of file HexagonSubtarget.cpp.
getRegisterInfo()
const HexagonRegisterInfo* llvm::HexagonSubtarget::getRegisterInfo () const inline override
Definition at line 125 of file HexagonSubtarget.h.
Referenced by llvm::HexagonInstrInfo::ClobbersPredicate(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::getDuplexCandidateGroup(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::HexagonInstrInfo::getOperandLatency(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::HexagonInstrInfo::isDependent(), llvm::HexagonTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerINLINEASM(), llvm::HexagonTargetLowering::LowerRETURNADDR(), and llvm::HexagonDAGToDAGISel::runOnMachineFunction().
getSelectionDAGInfo()
const HexagonSelectionDAGInfo* llvm::HexagonSubtarget::getSelectionDAGInfo () const inline override
Definition at line 134 of file HexagonSubtarget.h.
getSMSMutations()
void HexagonSubtarget::getSMSMutations (std::vector< std::unique_ptr< ScheduleDAGMutation >> & Mutations) const override
Definition at line 523 of file HexagonSubtarget.cpp.
getTargetLowering()
const HexagonTargetLowering* llvm::HexagonSubtarget::getTargetLowering () const inline override
Definition at line 128 of file HexagonSubtarget.h.
Referenced by isTypeForHVX().
getTargetTriple()
const Triple& llvm::HexagonSubtarget::getTargetTriple () const inline
Definition at line 114 of file HexagonSubtarget.h.
getTypeAlignment()
Align llvm::HexagonSubtarget::getTypeAlignment (MVT Ty) const inline
Definition at line 335 of file HexagonSubtarget.h.
References Align, llvm::MVT::getSizeInBits(), getVectorLength(), and isHVXVectorType().
Referenced by llvm::HexagonTargetLowering::LowerStore(), and llvm::HexagonTargetLowering::LowerUnalignedLoad().
getVectorLength()
unsigned llvm::HexagonSubtarget::getVectorLength () const inline
Definition at line 313 of file HexagonSubtarget.h.
References assert(), llvm_unreachable, useHVX128BOps(), useHVX64BOps(), and useHVXOps().
Referenced by getIntrinsicId(), llvm::HexagonTTIImpl::getMinimumVF(), llvm::HexagonTTIImpl::getMinVectorRegisterBitWidth(), getTypeAlignment(), isHVXVectorType(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::HvxSelector::selectRor(), and llvm::HexagonDAGToDAGISel::SelectV2Q().
hasMemNoShuf()
bool llvm::HexagonSubtarget::hasMemNoShuf () const inline
Definition at line 267 of file HexagonSubtarget.h.
hasReservedR19()
bool llvm::HexagonSubtarget::hasReservedR19 () const inline
Definition at line 268 of file HexagonSubtarget.h.
Referenced by llvm::HexagonRegisterInfo::getReservedRegs().
hasV55Ops()
bool llvm::HexagonSubtarget::hasV55Ops () const inline
Definition at line 153 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V55.
hasV55OpsOnly()
bool llvm::HexagonSubtarget::hasV55OpsOnly () const inline
Definition at line 156 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V55.
hasV5Ops()
bool llvm::HexagonSubtarget::hasV5Ops () const inline
Definition at line 147 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V5.
hasV5OpsOnly()
bool llvm::HexagonSubtarget::hasV5OpsOnly () const inline
Definition at line 150 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V5.
hasV60Ops()
bool llvm::HexagonSubtarget::hasV60Ops () const inline
Definition at line 159 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V60.
Referenced by llvm::HexagonInstrInfo::getDotOldOp(), llvm::HexagonTargetLowering::getRegForInlineAsmConstraint(), llvm::HexagonTargetLowering::HexagonTargetLowering(), initializeSubtargetDependencies(), llvm::HexagonTargetLowering::LowerCall(), and llvm::HexagonInstrInfo::mayBeCurLoad().
hasV60OpsOnly()
bool llvm::HexagonSubtarget::hasV60OpsOnly () const inline
Definition at line 162 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V60.
Referenced by cannotCoexistAsymm().
hasV62Ops()
bool llvm::HexagonSubtarget::hasV62Ops () const inline
Definition at line 165 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V62.
Referenced by llvm::HexagonInstrInfo::isPredicable().
hasV62OpsOnly()
bool llvm::HexagonSubtarget::hasV62OpsOnly () const inline
Definition at line 168 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V62.
hasV65Ops()
bool llvm::HexagonSubtarget::hasV65Ops () const inline
Definition at line 171 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V65.
Referenced by llvm::HexagonPacketizerList::isLegalToPacketizeTogether().
hasV65OpsOnly()
bool llvm::HexagonSubtarget::hasV65OpsOnly () const inline
Definition at line 174 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V65.
hasV66Ops()
bool llvm::HexagonSubtarget::hasV66Ops () const inline
Definition at line 177 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V66.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().
hasV66OpsOnly()
bool llvm::HexagonSubtarget::hasV66OpsOnly () const inline
Definition at line 180 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V66.
hasV67Ops()
bool llvm::HexagonSubtarget::hasV67Ops () const inline
Definition at line 183 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V67.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().
hasV67OpsOnly()
bool llvm::HexagonSubtarget::hasV67OpsOnly () const inline
Definition at line 186 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V67.
hasV68Ops()
bool llvm::HexagonSubtarget::hasV68Ops () const inline
Definition at line 189 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V68.
Referenced by initializeSubtargetDependencies().
hasV68OpsOnly()
bool llvm::HexagonSubtarget::hasV68OpsOnly () const inline
Definition at line 192 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V68.
hasV69Ops()
bool llvm::HexagonSubtarget::hasV69Ops () const inline
Definition at line 195 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V69.
hasV69OpsOnly()
bool llvm::HexagonSubtarget::hasV69OpsOnly () const inline
Definition at line 198 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V69.
hasV71Ops()
bool llvm::HexagonSubtarget::hasV71Ops () const inline
Definition at line 201 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V71.
hasV71OpsOnly()
bool llvm::HexagonSubtarget::hasV71OpsOnly () const inline
Definition at line 204 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V71.
hasV73Ops()
bool llvm::HexagonSubtarget::hasV73Ops () const inline
Definition at line 207 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V73.
hasV73OpsOnly()
bool llvm::HexagonSubtarget::hasV73OpsOnly () const inline
Definition at line 210 of file HexagonSubtarget.h.
References getHexagonArchVersion(), and llvm::Hexagon::V73.
initializeSubtargetDependencies()
HexagonSubtarget & HexagonSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 95 of file HexagonSubtarget.cpp.
References llvm::SubtargetFeatures::AddFeature(), llvm::Hexagon_MC::completeHVXFeatures(), llvm::StringRef::consumeInteger(), llvm::count_if(), llvm::dbgs(), llvm::StringRef::drop_front(), EnableBSBSched, F, llvm::X86AS::FS, llvm::Hexagon::getCpu(), llvm::SubtargetFeatures::getFeatures(), llvm::cl::Option::getPosition(), llvm::SubtargetFeatures::getString(), hasV60Ops(), hasV68Ops(), HexagonArchVersion, llvm::HexagonDisableDuplex, isTinyCore(), LLVM_DEBUG, llvm_unreachable, OverrideLongCalls, ParseSubtargetFeatures(), llvm::FeatureBitset::reset(), llvm::reverse(), llvm::StringRef::startswith(), UseBSBScheduling, and useHVXV68Ops().
isEnvironmentMusl()
bool llvm::HexagonSubtarget::isEnvironmentMusl () const inline
Definition at line 115 of file HexagonSubtarget.h.
References llvm::Triple::getEnvironment(), and llvm::Triple::Musl.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::HexagonTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerVACOPY(), and llvm::HexagonTargetLowering::LowerVASTART().
isHVXElementType()
bool HexagonSubtarget::isHVXElementType (MVT Ty, bool IncludeBool = false) const
Definition at line 176 of file HexagonSubtarget.cpp.
References getHVXElementTypes(), llvm::MVT::getVectorElementType(), llvm::MVT::i1, llvm::is_contained(), llvm::MVT::isVector(), and useHVXOps().
isHVXVectorType()
bool HexagonSubtarget::isHVXVectorType (EVT VecTy, bool IncludeBool = false) const
Definition at line 187 of file HexagonSubtarget.cpp.
References getHVXElementTypes(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::getVectorElementType(), getVectorLength(), llvm::EVT::getVectorNumElements(), llvm::MVT::i1, llvm::is_contained(), llvm::EVT::isScalableVector(), llvm::EVT::isSimple(), llvm::EVT::isVector(), and useHVXOps().
Referenced by llvm::HexagonTargetLowering::allowsMemoryAccess(), llvm::HexagonTargetLowering::allowsMisalignedMemoryAccesses(), llvm::HexagonTargetLowering::getPostIndexedAddressParts(), getTypeAlignment(), isTypeForHVX(), llvm::HexagonTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), llvm::HexagonDAGToDAGISel::Select(), and llvm::HexagonDAGToDAGISel::SelectVAlign().
isTinyCore()
bool llvm::HexagonSubtarget::isTinyCore () const inline
Definition at line 226 of file HexagonSubtarget.h.
Referenced by initializeSubtargetDependencies(), and isTinyCoreWithDuplex().
isTinyCoreWithDuplex()
bool llvm::HexagonSubtarget::isTinyCoreWithDuplex () const inline
Definition at line 227 of file HexagonSubtarget.h.
References isTinyCore().
isTypeForHVX()
bool HexagonSubtarget::isTypeForHVX (Type * VecTy, bool IncludeBool = false) const
Definition at line 215 of file HexagonSubtarget.cpp.
References llvm::EVT::getEVT(), llvm::HexagonTargetLowering::getPreferredVectorAction(), llvm::Type::getScalarType(), llvm::EVT::getSimpleVT(), getTargetLowering(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::Type::isFloatingPointTy(), isHVXVectorType(), llvm::Type::isIntegerTy(), llvm::EVT::isSimple(), llvm::MVT::isValid(), llvm::Type::isVectorTy(), llvm::PowerOf2Ceil(), llvm::TargetLoweringBase::TypeWidenVector, and useHVXFloatingPoint().
Referenced by llvm::HexagonTTIImpl::isLegalMaskedLoad(), and llvm::HexagonTTIImpl::isLegalMaskedStore().
isXRaySupported()
bool llvm::HexagonSubtarget::isXRaySupported () const inline override
Definition at line 145 of file HexagonSubtarget.h.
noreturnStackElim()
bool llvm::HexagonSubtarget::noreturnStackElim () const inline
Definition at line 271 of file HexagonSubtarget.h.
ParseSubtargetFeatures()
void llvm::HexagonSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
Referenced by initializeSubtargetDependencies().
useAA()
bool HexagonSubtarget::useAA () const override
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
Definition at line 431 of file HexagonSubtarget.cpp.
References llvm::CodeGenOpt::None, and OptLevel.
useAudioOps()
bool llvm::HexagonSubtarget::useAudioOps () const inline
Definition at line 214 of file HexagonSubtarget.h.
useBSBScheduling()
bool llvm::HexagonSubtarget::useBSBScheduling () const inline
Definition at line 273 of file HexagonSubtarget.h.
References UseBSBScheduling.
useCabac()
bool llvm::HexagonSubtarget::useCabac () const inline
Definition at line 224 of file HexagonSubtarget.h.
useCompound()
bool llvm::HexagonSubtarget::useCompound () const inline
Definition at line 215 of file HexagonSubtarget.h.
Referenced by llvm::HexagonDAGToDAGISel::SelectVAlign().
useHVX128BOps()
bool llvm::HexagonSubtarget::useHVX128BOps () const inline
Definition at line 264 of file HexagonSubtarget.h.
References useHVXOps().
Referenced by llvm::HexagonTargetLowering::getRegForInlineAsmConstraint(), and getVectorLength().
useHVX64BOps()
bool llvm::HexagonSubtarget::useHVX64BOps () const inline
Definition at line 265 of file HexagonSubtarget.h.
References useHVXOps().
Referenced by getVectorLength().
useHVXFloatingPoint()
bool llvm::HexagonSubtarget::useHVXFloatingPoint () const inline
Definition at line 233 of file HexagonSubtarget.h.
Referenced by getHVXElementTypes(), and isTypeForHVX().
useHVXIEEEFPOps()
bool llvm::HexagonSubtarget::useHVXIEEEFPOps () const inline
Definition at line 229 of file HexagonSubtarget.h.
References useHVXOps().
useHVXOps()
bool llvm::HexagonSubtarget::useHVXOps () const inline
Definition at line 234 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::NoArch.
Referenced by llvm::HexagonTargetLowering::CanLowerReturn(), llvm::HexagonTargetLowering::getConstraintType(), llvm::HexagonTargetLowering::getCustomOperationAction(), llvm::HexagonTargetLowering::getPreferredVectorAction(), getVectorLength(), llvm::HexagonTargetLowering::HexagonTargetLowering(), isHVXElementType(), isHVXVectorType(), llvm::HexagonTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerReturn(), llvm::HexagonDAGToDAGISel::PreprocessISelDAG(), llvm::HexagonDAGToDAGISel::Select(), llvm::HexagonRegisterInfo::shouldCoalesce(), useHVX128BOps(), useHVX64BOps(), and useHVXIEEEFPOps().
useHVXQFloatOps()
bool llvm::HexagonSubtarget::useHVXQFloatOps () const inline
Definition at line 230 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V68.
useHVXV60Ops()
bool llvm::HexagonSubtarget::useHVXV60Ops () const inline
Definition at line 237 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V60.
useHVXV62Ops()
bool llvm::HexagonSubtarget::useHVXV62Ops () const inline
Definition at line 240 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V62.
useHVXV65Ops()
bool llvm::HexagonSubtarget::useHVXV65Ops () const inline
Definition at line 243 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V65.
useHVXV66Ops()
bool llvm::HexagonSubtarget::useHVXV66Ops () const inline
Definition at line 246 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V66.
useHVXV67Ops()
bool llvm::HexagonSubtarget::useHVXV67Ops () const inline
Definition at line 249 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V67.
useHVXV68Ops()
bool llvm::HexagonSubtarget::useHVXV68Ops () const inline
Definition at line 252 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V68.
Referenced by getHVXElementTypes(), and initializeSubtargetDependencies().
useHVXV69Ops()
bool llvm::HexagonSubtarget::useHVXV69Ops () const inline
Definition at line 255 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V69.
useHVXV71Ops()
bool llvm::HexagonSubtarget::useHVXV71Ops () const inline
Definition at line 258 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V71.
useHVXV73Ops()
bool llvm::HexagonSubtarget::useHVXV73Ops () const inline
Definition at line 261 of file HexagonSubtarget.h.
References HexagonHVXVersion, and llvm::Hexagon::V73.
useLongCalls()
bool llvm::HexagonSubtarget::useLongCalls () const inline
Definition at line 216 of file HexagonSubtarget.h.
useMemops()
bool llvm::HexagonSubtarget::useMemops () const inline
Definition at line 217 of file HexagonSubtarget.h.
useNewValueJumps()
bool llvm::HexagonSubtarget::useNewValueJumps () const inline
Definition at line 219 of file HexagonSubtarget.h.
useNewValueStores()
bool llvm::HexagonSubtarget::useNewValueStores () const inline
Definition at line 220 of file HexagonSubtarget.h.
Referenced by llvm::HexagonInstrInfo::mayBeNewStore().
usePackets()
bool llvm::HexagonSubtarget::usePackets () const inline
Definition at line 218 of file HexagonSubtarget.h.
usePredicatedCalls()
bool HexagonSubtarget::usePredicatedCalls () const
Definition at line 538 of file HexagonSubtarget.cpp.
References EnablePredicatedCalls.
Referenced by llvm::HexagonInstrInfo::isPredicable().
useSmallData()
bool llvm::HexagonSubtarget::useSmallData () const inline
Definition at line 221 of file HexagonSubtarget.h.
Referenced by llvm::HexagonTargetLowering::LowerGLOBALADDRESS().
useUnsafeMath()
bool llvm::HexagonSubtarget::useUnsafeMath () const inline
Definition at line 222 of file HexagonSubtarget.h.
useZRegOps()
bool llvm::HexagonSubtarget::useZRegOps () const inline
Definition at line 223 of file HexagonSubtarget.h.
Member Data Documentation
HexagonArchVersion
Hexagon::ArchEnum llvm::HexagonSubtarget::HexagonArchVersion
Definition at line 71 of file HexagonSubtarget.h.
Referenced by getHexagonArchVersion(), and initializeSubtargetDependencies().
HexagonHVXVersion
Hexagon::ArchEnum llvm::HexagonSubtarget::HexagonHVXVersion = Hexagon::ArchEnum::NoArch
Definition at line 72 of file HexagonSubtarget.h.
Referenced by useHVXOps(), useHVXQFloatOps(), useHVXV60Ops(), useHVXV62Ops(), useHVXV65Ops(), useHVXV66Ops(), useHVXV67Ops(), useHVXV68Ops(), useHVXV69Ops(), useHVXV71Ops(), and useHVXV73Ops().
OptLevel
CodeGenOpt::Level llvm::HexagonSubtarget::OptLevel
Definition at line 73 of file HexagonSubtarget.h.
Referenced by useAA().
UseBSBScheduling
bool llvm::HexagonSubtarget::UseBSBScheduling
True if the target should use Back-Skip-Back scheduling.
This is the default for V60.
Definition at line 76 of file HexagonSubtarget.h.
Referenced by initializeSubtargetDependencies(), and useBSBScheduling().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonSubtarget.h
lib/Target/Hexagon/HexagonSubtarget.cpp