LLVM: llvm::dxil::ValidatorVersionMD Class Reference
llvm::dxil::ValidatorVersionMD Class Reference
#include "Target/DirectX/DXILMetadata.h"
Public Member Functions
ValidatorVersionMD (Module &M)
void update (VersionTuple ValidatorVer)
bool isEmpty ()
Detailed Description
Definition at line 24 of file DXILMetadata.h.
Constructor & Destructor Documentation
ValidatorVersionMD()
ValidatorVersionMD::ValidatorVersionMD (Module & M)
Definition at line 24 of file DXILMetadata.cpp.
Member Function Documentation
isEmpty()
bool ValidatorVersionMD::isEmpty ()
Definition at line 41 of file DXILMetadata.cpp.
References llvm::NamedMDNode::getNumOperands().
Referenced by update().
update()
void ValidatorVersionMD::update (VersionTuple ValidatorVer)
Definition at line 27 of file DXILMetadata.cpp.
References llvm::NamedMDNode::addOperand(), B, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::Module::getContext(), llvm::VersionTuple::getMajor(), llvm::VersionTuple::getMinor(), llvm::NamedMDNode::getParent(), isEmpty(), and llvm::NamedMDNode::setOperand().
The documentation for this class was generated from the following files:
lib/Target/DirectX/DXILMetadata.h
lib/Target/DirectX/DXILMetadata.cpp