LLVM: llvm::jitlink::LinkGraph Class Reference
llvm::jitlink::LinkGraph Class Reference
#include "llvm/ExecutionEngine/JITLink/JITLink.h"
Classes
class nested_collection_iterator
Public Types
using external_symbol_iterator = ExternalSymbolSet::iterator
using section_iterator = pointee_iterator< SectionList::iterator >
using const_section_iterator = pointee_iterator< SectionList::const_iterator >
using defined_symbol_iterator = nested_collection_iterator< const_section_iterator, Section::symbol_iterator, Symbol *, getSectionSymbols >
using const_defined_symbol_iterator = nested_collection_iterator< const_section_iterator, Section::const_symbol_iterator, const Symbol *, getSectionConstSymbols >
using block_iterator = nested_collection_iterator< const_section_iterator, Section::block_iterator, Block *, getSectionBlocks >
using const_block_iterator = nested_collection_iterator< const_section_iterator, Section::const_block_iterator, const Block *, getSectionConstBlocks >
using GetEdgeKindNameFunction = const char *(*)(Edge::Kind)
using SplitBlockCache = std::optional< SmallVector< Symbol *, 8 > >
Cache type for the splitBlock function.
Public Member Functions
LinkGraph (std::string Name, const Triple &TT, unsigned PointerSize, support::endianness Endianness, GetEdgeKindNameFunction GetEdgeKindName)
LinkGraph (const LinkGraph &)=delete
LinkGraph & operator= (const LinkGraph &)=delete
LinkGraph (LinkGraph &&)=delete
LinkGraph & operator= (LinkGraph &&)=delete
const std::string & getName () const
Returns the name of this graph (usually the name of the original underlying MemoryBuffer).
const Triple & getTargetTriple () const
Returns the target triple for this Graph.
unsigned getPointerSize () const
Returns the pointer size for use in this graph.
support::endianness getEndianness () const
Returns the endianness of content in this graph.
const char * getEdgeKindName (Edge::Kind K) const
MutableArrayRef< char > allocateBuffer (size_t Size)
Allocate a mutable buffer of the given size using the LinkGraph's allocator.
MutableArrayRef< char > allocateContent (ArrayRef< char > Source)
Allocate a copy of the given string using the LinkGraph's allocator.
MutableArrayRef< char > allocateContent (Twine Source)
Allocate a copy of the given string using the LinkGraph's allocator.
MutableArrayRef< char > allocateCString (StringRef Source)
Allocate a copy of the given string using the LinkGraph's allocator.
MutableArrayRef< char > allocateCString (Twine Source)
Allocate a copy of the given string using the LinkGraph's allocator.
Section & createSection (StringRef Name, orc::MemProt Prot)
Create a section with the given name, protection flags, and alignment.
Block & createContentBlock (Section &Parent, ArrayRef< char > Content, orc::ExecutorAddr Address, uint64_t Alignment, uint64_t AlignmentOffset)
Create a content block.
Block & createMutableContentBlock (Section &Parent, MutableArrayRef< char > MutableContent, orc::ExecutorAddr Address, uint64_t Alignment, uint64_t AlignmentOffset)
Create a content block with initially mutable data.
Block & createMutableContentBlock (Section &Parent, size_t ContentSize, orc::ExecutorAddr Address, uint64_t Alignment, uint64_t AlignmentOffset, bool ZeroInitialize=true)
Create a content block with initially mutable data of the given size.
Block & createZeroFillBlock (Section &Parent, orc::ExecutorAddrDiff Size, orc::ExecutorAddr Address, uint64_t Alignment, uint64_t AlignmentOffset)
Create a zero-fill block.
BinaryStreamReader getBlockContentReader (Block &B)
Returns a BinaryStreamReader for the given block.
BinaryStreamWriter getBlockContentWriter (Block &B)
Returns a BinaryStreamWriter for the given block.
Block & splitBlock (Block &B, size_t SplitIndex, SplitBlockCache *Cache=nullptr)
Splits block B at the given index which must be greater than zero.
Symbol & addExternalSymbol (StringRef Name, orc::ExecutorAddrDiff Size, bool IsWeaklyReferenced)
Add an external symbol.
Symbol & addAbsoluteSymbol (StringRef Name, orc::ExecutorAddr Address, orc::ExecutorAddrDiff Size, Linkage L, Scope S, bool IsLive)
Add an absolute symbol.
Symbol & addAnonymousSymbol (Block &Content, orc::ExecutorAddrDiff Offset, orc::ExecutorAddrDiff Size, bool IsCallable, bool IsLive)
Add an anonymous symbol.
Symbol & addDefinedSymbol (Block &Content, orc::ExecutorAddrDiff Offset, StringRef Name, orc::ExecutorAddrDiff Size, Linkage L, Scope S, bool IsCallable, bool IsLive)
Add a named symbol.
iterator_range< section_iterator > sections ()
SectionList::size_type sections_size () const
Section * findSectionByName (StringRef Name)
Returns the section with the given name if it exists, otherwise returns null.
iterator_range< block_iterator > blocks ()
iterator_range< const_block_iterator > blocks () const
iterator_range< external_symbol_iterator > external_symbols ()
iterator_range< external_symbol_iterator > absolute_symbols ()
iterator_range< defined_symbol_iterator > defined_symbols ()
iterator_range< const_defined_symbol_iterator > defined_symbols () const
void makeExternal (Symbol &Sym)
Make the given symbol external (must not already be external).
void makeAbsolute (Symbol &Sym, orc::ExecutorAddr Address)
Make the given symbol an absolute with the given address (must not already be absolute).
void makeDefined (Symbol &Sym, Block &Content, orc::ExecutorAddrDiff Offset, orc::ExecutorAddrDiff Size, Linkage L, Scope S, bool IsLive)
Turn an absolute or external symbol into a defined one by attaching it to a block.
void transferDefinedSymbol (Symbol &Sym, Block &DestBlock, orc::ExecutorAddrDiff NewOffset, std::optional< orc::ExecutorAddrDiff > ExplicitNewSize)
Transfer a defined symbol from one block to another.
void transferBlock (Block &B, Section &NewSection)
Transfers the given Block and all Symbols pointing to it to the given Section.
void mergeSections (Section &DstSection, Section &SrcSection, bool PreserveSrcSection=false)
Move all blocks and symbols from the source section to the destination section.
void removeExternalSymbol (Symbol &Sym)
Removes an external symbol. Also removes the underlying Addressable.
void removeAbsoluteSymbol (Symbol &Sym)
Remove an absolute symbol. Also removes the underlying Addressable.
void removeDefinedSymbol (Symbol &Sym)
Removes defined symbols. Does not remove the underlying block.
void removeBlock (Block &B)
Remove a block.
void removeSection (Section &Sec)
Remove a section.
orc::shared::AllocActions & allocActions ()
Accessor for the AllocActions object for this graph.
void dump (raw_ostream &OS)
Dump the graph.
Detailed Description
Definition at line 827 of file JITLink.h.
Member Typedef Documentation
block_iterator
using llvm::jitlink::LinkGraph::block_iterator = nested_collection_iterator<const_section_iterator, Section::block_iterator, Block *, getSectionBlocks>
Definition at line 947 of file JITLink.h.
const_block_iterator
using llvm::jitlink::LinkGraph::const_block_iterator = nested_collection_iterator<const_section_iterator, Section::const_block_iterator, const Block *, getSectionConstBlocks>
Definition at line 952 of file JITLink.h.
const_defined_symbol_iterator
using llvm::jitlink::LinkGraph::const_defined_symbol_iterator = nested_collection_iterator<const_section_iterator, Section::const_symbol_iterator, const Symbol *, getSectionConstSymbols>
Definition at line 943 of file JITLink.h.
const_section_iterator
using llvm::jitlink::LinkGraph::const_section_iterator = pointee_iterator<SectionList::const_iterator>
Definition at line 886 of file JITLink.h.
defined_symbol_iterator
using llvm::jitlink::LinkGraph::defined_symbol_iterator = nested_collection_iterator<const_section_iterator, Section::symbol_iterator, Symbol *, getSectionSymbols>
Definition at line 938 of file JITLink.h.
external_symbol_iterator
using llvm::jitlink::LinkGraph::external_symbol_iterator = ExternalSymbolSet::iterator
Definition at line 883 of file JITLink.h.
GetEdgeKindNameFunction
using llvm::jitlink::LinkGraph::GetEdgeKindNameFunction = const char *(*)(Edge::Kind)
Definition at line 954 of file JITLink.h.
section_iterator
using llvm::jitlink::LinkGraph::section_iterator = pointee_iterator<SectionList::iterator>
Definition at line 885 of file JITLink.h.
SplitBlockCache
using llvm::jitlink::LinkGraph::SplitBlockCache = std::optional<SmallVector<Symbol *, 8> >
Cache type for the splitBlock function.
Definition at line 1109 of file JITLink.h.
Constructor & Destructor Documentation
LinkGraph() [1/3]
llvm::jitlink::LinkGraph::LinkGraph (std::string Name, const Triple & TT, unsigned PointerSize, support::endianness Endianness, GetEdgeKindNameFunction GetEdgeKindName) inline
Definition at line 956 of file JITLink.h.
LinkGraph() [2/3]
llvm::jitlink::LinkGraph::LinkGraph (const LinkGraph &) delete
LinkGraph() [3/3]
llvm::jitlink::LinkGraph::LinkGraph (LinkGraph &&) delete
Member Function Documentation
absolute_symbols()
iterator_range<external_symbol_iterator> llvm::jitlink::LinkGraph::absolute_symbols () inline
Definition at line 1239 of file JITLink.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), and llvm::make_range().
addAbsoluteSymbol()
Symbol& llvm::jitlink::LinkGraph::addAbsoluteSymbol (StringRef Name, orc::ExecutorAddr Address, orc::ExecutorAddrDiff Size, Linkage L, Scope S, bool IsLive) inline
Add an absolute symbol.
Definition at line 1170 of file JITLink.h.
References Allocator, assert(), llvm::count_if(), llvm::jitlink::Symbol::getName(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::jitlink::Local, and S.
addAnonymousSymbol()
Symbol& llvm::jitlink::LinkGraph::addAnonymousSymbol (Block & Content, orc::ExecutorAddrDiff Offset, orc::ExecutorAddrDiff Size, bool IsCallable, bool IsLive) inline
Add an anonymous symbol.
Definition at line 1185 of file JITLink.h.
References Allocator, and Content.
addDefinedSymbol()
Symbol& llvm::jitlink::LinkGraph::addDefinedSymbol (Block & Content, orc::ExecutorAddrDiff Offset, StringRef Name, orc::ExecutorAddrDiff Size, Linkage L, Scope S, bool IsCallable, bool IsLive) inline
Add a named symbol.
Definition at line 1195 of file JITLink.h.
References Allocator, assert(), Content, llvm::count_if(), defined_symbols(), llvm::jitlink::Symbol::getName(), llvm::jitlink::Local, and S.
addExternalSymbol()
Symbol& llvm::jitlink::LinkGraph::addExternalSymbol (StringRef Name, orc::ExecutorAddrDiff Size, bool IsWeaklyReferenced) inline
Add an external symbol.
Some formats (e.g. ELF) allow Symbols to have sizes. For Symbols whose size is not known, you should substitute '0'. The IsWeaklyReferenced argument determines whether the symbol must be present during lookup: Externals that are strongly referenced must be found or an error will be emitted. Externals that are weakly referenced are permitted to be undefined, in which case they are assigned an address of 0.
Definition at line 1155 of file JITLink.h.
References Allocator, assert(), llvm::count_if(), llvm::jitlink::Symbol::getName(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and llvm::jitlink::Strong.
allocActions()
orc::shared::AllocActions& llvm::jitlink::LinkGraph::allocActions () inline
Accessor for the AllocActions object for this graph.
This can be used to register allocation action calls prior to finalization.
Accessing this object after finalization will result in undefined behavior.
Definition at line 1462 of file JITLink.h.
Referenced by llvm::jitlink::BasicLayout::graphAllocActions().
allocateBuffer()
MutableArrayRef<char> llvm::jitlink::LinkGraph::allocateBuffer (size_t Size) inline
Allocate a mutable buffer of the given size using the LinkGraph's allocator.
Definition at line 984 of file JITLink.h.
References Allocator.
allocateContent() [1/2]
MutableArrayRef<char> llvm::jitlink::LinkGraph::allocateContent (ArrayRef< char > Source) inline
Allocate a copy of the given string using the LinkGraph's allocator.
This can be useful when renaming symbols or adding new content to the graph.
Definition at line 991 of file JITLink.h.
References Allocator, llvm::copy(), and llvm::Sched::Source.
Referenced by createMutableContentBlock().
allocateContent() [2/2]
MutableArrayRef<char> llvm::jitlink::LinkGraph::allocateContent (Twine Source) inline
Allocate a copy of the given string using the LinkGraph's allocator.
This can be useful when renaming symbols or adding new content to the graph.
Note: This Twine-based overload requires an extra string copy and an extra heap allocation for large strings. The ArrayRef<char> overload should be preferred where possible.
Definition at line 1004 of file JITLink.h.
References Allocator, llvm::copy(), and llvm::Sched::Source.
allocateCString() [1/2]
MutableArrayRef<char> llvm::jitlink::LinkGraph::allocateCString (StringRef Source) inline
Allocate a copy of the given string using the LinkGraph's allocator.
The allocated string will be terminated with a null character, and the returned MutableArrayRef will include this null character in the last position.
Definition at line 1017 of file JITLink.h.
References Allocator, llvm::copy(), and llvm::Sched::Source.
allocateCString() [2/2]
MutableArrayRef<char> llvm::jitlink::LinkGraph::allocateCString (Twine Source) inline
Allocate a copy of the given string using the LinkGraph's allocator.
The allocated string will be terminated with a null character, and the returned MutableArrayRef will include this null character in the last position.
Note: This Twine-based overload requires an extra string copy and an extra heap allocation for large strings. The ArrayRef<char> overload should be preferred where possible.
Definition at line 1033 of file JITLink.h.
References Allocator, llvm::copy(), and llvm::Sched::Source.
blocks() [1/2]
iterator_range<block_iterator> llvm::jitlink::LinkGraph::blocks () inline
Definition at line 1225 of file JITLink.h.
References llvm::make_range().
Referenced by llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run().
blocks() [2/2]
iterator_range<const_block_iterator> llvm::jitlink::LinkGraph::blocks () const inline
Definition at line 1230 of file JITLink.h.
References llvm::make_range().
createContentBlock()
Block& llvm::jitlink::LinkGraph::createContentBlock (Section & Parent, ArrayRef< char > Content, orc::ExecutorAddr Address, uint64_t Alignment, uint64_t AlignmentOffset) inline
Create a content block.
Definition at line 1055 of file JITLink.h.
References Content.
createMutableContentBlock() [1/2]
Block& llvm::jitlink::LinkGraph::createMutableContentBlock (Section & Parent, MutableArrayRef< char > MutableContent, orc::ExecutorAddr Address, uint64_t Alignment, uint64_t AlignmentOffset) inline
Create a content block with initially mutable data.
Definition at line 1062 of file JITLink.h.
createMutableContentBlock() [2/2]
Block& llvm::jitlink::LinkGraph::createMutableContentBlock (Section & Parent, size_t ContentSize, orc::ExecutorAddr Address, uint64_t Alignment, uint64_t AlignmentOffset, bool ZeroInitialize = true) inline
Create a content block with initially mutable data of the given size.
Content will be allocated via the LinkGraph's allocateBuffer method. By default the memory will be zero-initialized. Passing false for ZeroInitialize will prevent this.
Definition at line 1075 of file JITLink.h.
References allocateContent(), and Content.
createSection()
Section& llvm::jitlink::LinkGraph::createSection (StringRef Name, orc::MemProt Prot) inline
Create a section with the given name, protection flags, and alignment.
Definition at line 1043 of file JITLink.h.
References assert(), move, and llvm::none_of().
createZeroFillBlock()
Block& llvm::jitlink::LinkGraph::createZeroFillBlock (Section & Parent, orc::ExecutorAddrDiff Size, orc::ExecutorAddr Address, uint64_t Alignment, uint64_t AlignmentOffset) inline
Create a zero-fill block.
Definition at line 1086 of file JITLink.h.
defined_symbols() [1/2]
iterator_range<defined_symbol_iterator> llvm::jitlink::LinkGraph::defined_symbols () inline
Definition at line 1243 of file JITLink.h.
References llvm::make_range().
Referenced by addDefinedSymbol().
defined_symbols() [2/2]
iterator_range<const_defined_symbol_iterator> llvm::jitlink::LinkGraph::defined_symbols () const inline
Definition at line 1248 of file JITLink.h.
References llvm::make_range().
dump()
void llvm::jitlink::LinkGraph::dump (raw_ostream & OS)
Dump the graph.
Definition at line 245 of file JITLink.cpp.
References LHS, RHS, and llvm::sort().
external_symbols()
iterator_range<external_symbol_iterator> llvm::jitlink::LinkGraph::external_symbols () inline
Definition at line 1235 of file JITLink.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end(), and llvm::make_range().
findSectionByName()
Section* llvm::jitlink::LinkGraph::findSectionByName (StringRef Name) inline
Returns the section with the given name if it exists, otherwise returns null.
Definition at line 1218 of file JITLink.h.
References S, and sections().
getBlockContentReader()
BinaryStreamReader llvm::jitlink::LinkGraph::getBlockContentReader (Block & B) inline
Returns a BinaryStreamReader for the given block.
Definition at line 1093 of file JITLink.h.
References B, and getEndianness().
getBlockContentWriter()
BinaryStreamWriter llvm::jitlink::LinkGraph::getBlockContentWriter (Block & B) inline
Returns a BinaryStreamWriter for the given block.
This will call getMutableContent to obtain mutable content for the block.
Definition at line 1101 of file JITLink.h.
References B, and getEndianness().
getEdgeKindName()
const char* llvm::jitlink::LinkGraph::getEdgeKindName (Edge::Kind K) const inline
Definition at line 980 of file JITLink.h.
Referenced by llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run().
getEndianness()
support::endianness llvm::jitlink::LinkGraph::getEndianness () const inline
Returns the endianness of content in this graph.
Definition at line 978 of file JITLink.h.
Referenced by getBlockContentReader(), and getBlockContentWriter().
getName()
const std::string& llvm::jitlink::LinkGraph::getName () const inline
Returns the name of this graph (usually the name of the original underlying MemoryBuffer).
Definition at line 969 of file JITLink.h.
Referenced by llvm::orc::GDBJITDebugInfoRegistrationPlugin::modifyPassConfig().
getPointerSize()
unsigned llvm::jitlink::LinkGraph::getPointerSize () const inline
Returns the pointer size for use in this graph.
Definition at line 975 of file JITLink.h.
getTargetTriple()
const Triple& llvm::jitlink::LinkGraph::getTargetTriple () const inline
Returns the target triple for this Graph.
Definition at line 972 of file JITLink.h.
Referenced by llvm::orc::GDBJITDebugInfoRegistrationPlugin::modifyPassConfig().
makeAbsolute()
void llvm::jitlink::LinkGraph::makeAbsolute (Symbol & Sym, orc::ExecutorAddr Address) inline
Make the given symbol an absolute with the given address (must not already be absolute).
The symbol's size, linkage, and callability, and liveness will be left unchanged, and its offset will be reset to 0.
If the symbol was external then its scope will be set to local, otherwise it will be left unchanged.
Definition at line 1285 of file JITLink.h.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::jitlink::Symbol::getAddressable(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Symbol::getOffset(), llvm::jitlink::Block::getSection(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isDefined(), llvm::jitlink::Symbol::isExternal(), llvm::jitlink::Local, and llvm::jitlink::Symbol::setScope().
makeDefined()
void llvm::jitlink::LinkGraph::makeDefined (Symbol & Sym, Block & Content, orc::ExecutorAddrDiff Offset, orc::ExecutorAddrDiff Size, Linkage L, Scope S, bool IsLive) inline
Turn an absolute or external symbol into a defined one by attaching it to a block.
Symbol must not already be defined.
Definition at line 1307 of file JITLink.h.
References assert(), Content, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isDefined(), S, llvm::jitlink::Symbol::setLinkage(), llvm::jitlink::Symbol::setLive(), llvm::jitlink::Symbol::setScope(), and llvm::jitlink::Symbol::setSize().
makeExternal()
void llvm::jitlink::LinkGraph::makeExternal (Symbol & Sym) inline
Make the given symbol external (must not already be external).
Symbol size, linkage and callability will be left unchanged. Symbol scope will be set to Default, and offset will be reset to 0.
Definition at line 1258 of file JITLink.h.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::jitlink::Symbol::getAddressable(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Symbol::getOffset(), llvm::jitlink::Block::getSection(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isDefined(), and llvm::jitlink::Symbol::isExternal().
mergeSections()
void llvm::jitlink::LinkGraph::mergeSections (Section & DstSection, Section & SrcSection, bool PreserveSrcSection = false) inline
Move all blocks and symbols from the source section to the destination section.
If PreserveSrcSection is true (or SrcSection and DstSection are the same) then SrcSection is preserved, otherwise it is removed (the default).
Definition at line 1388 of file JITLink.h.
References B, llvm::jitlink::Section::blocks(), and removeSection().
operator=() [1/2]
LinkGraph& llvm::jitlink::LinkGraph::operator= (const LinkGraph &) delete
operator=() [2/2]
LinkGraph& llvm::jitlink::LinkGraph::operator= (LinkGraph &&) delete
removeAbsoluteSymbol()
void llvm::jitlink::LinkGraph::removeAbsoluteSymbol (Symbol & Sym) inline
Remove an absolute symbol. Also removes the underlying Addressable.
Definition at line 1414 of file JITLink.h.
References assert(), llvm::sampleprof::Base, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isDefined(), and llvm::none_of().
removeBlock()
void llvm::jitlink::LinkGraph::removeBlock (Block & B) inline
Remove a block.
The block reference is defunct after calling this function and should no longer be used.
Definition at line 1437 of file JITLink.h.
References assert(), B, and llvm::none_of().
removeDefinedSymbol()
void llvm::jitlink::LinkGraph::removeDefinedSymbol (Symbol & Sym) inline
Removes defined symbols. Does not remove the underlying block.
Definition at line 1429 of file JITLink.h.
References assert(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Block::getSection(), and llvm::jitlink::Symbol::isDefined().
removeExternalSymbol()
void llvm::jitlink::LinkGraph::removeExternalSymbol (Symbol & Sym) inline
Removes an external symbol. Also removes the underlying Addressable.
Definition at line 1400 of file JITLink.h.
References assert(), llvm::sampleprof::Base, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::jitlink::Symbol::isAbsolute(), llvm::jitlink::Symbol::isDefined(), and llvm::none_of().
removeSection()
void llvm::jitlink::LinkGraph::removeSection (Section & Sec) inline
Remove a section.
The section reference is defunct after calling this function and should no longer be used.
Definition at line 1449 of file JITLink.h.
References assert(), llvm::find_if(), I, and S.
Referenced by mergeSections().
sections()
iterator_range<section_iterator> llvm::jitlink::LinkGraph::sections () inline
Definition at line 1209 of file JITLink.h.
References llvm::make_range().
Referenced by findSectionByName(), and llvm::orc::DebugObjectManagerPlugin::modifyPassConfig().
sections_size()
SectionList::size_type llvm::jitlink::LinkGraph::sections_size () const inline
Definition at line 1214 of file JITLink.h.
splitBlock()
Block & llvm::jitlink::LinkGraph::splitBlock (Block & B, size_t SplitIndex, SplitBlockCache * Cache = nullptr)
Splits block B at the given index which must be greater than zero.
If SplitIndex == B.getSize() then this function is a no-op and returns B. If SplitIndex < B.getSize() then this function returns a new block covering the range [ 0, SplitIndex), and B is modified to cover the range [ SplitIndex, B.size()).
The optional Cache parameter can be used to speed up repeated calls to splitBlock for a single block. If the value is None the cache will be treated as uninitialized and splitBlock will populate it. Otherwise it is assumed to contain the list of Symbols pointing at B, sorted in descending order of offset.
Notes:
splitBlock must be used with care. Splitting a block may cause incoming edges to become invalid if the edge target subexpression points outside the bounds of the newly split target block (E.g. an edge 'S + 10 : Pointer64' where S points to a newly split block whose size is less than 10). No attempt is made to detect invalidation of incoming edges, as in general this requires context that the LinkGraph does not have. Clients are responsible for ensuring that splitBlock is not used in a way that invalidates edges.
The newly introduced block will have a new ordinal which will be higher than any other ordinals in the section. Clients are responsible for re-assigning block ordinals to restore a compatible order if needed.
The cache is not automatically updated if new symbols are introduced between calls to splitBlock. Any newly introduced symbols may be added to the cache manually (descending offset order must be preserved), or the cache can be set to None and rebuilt by splitBlock on the next call.
Definition at line 165 of file JITLink.cpp.
References assert(), B, I, LHS, RHS, and llvm::sort().
transferBlock()
void llvm::jitlink::LinkGraph::transferBlock (Block & B, Section & NewSection) inline
Transfers the given Block and all Symbols pointing to it to the given Section.
No attempt is made to check compatibility of the source and destination sections. Blocks may be moved between sections with incompatible permissions (e.g. from data to text). The client is responsible for ensuring that this is safe.
Definition at line 1367 of file JITLink.h.
References B, and S.
transferDefinedSymbol()
void llvm::jitlink::LinkGraph::transferDefinedSymbol (Symbol & Sym, Block & DestBlock, orc::ExecutorAddrDiff NewOffset, std::optional< orc::ExecutorAddrDiff > ExplicitNewSize) inline
Transfer a defined symbol from one block to another.
The symbol's offset within DestBlock is set to NewOffset.
If ExplicitNewSize is given as None then the size of the symbol will be checked and auto-truncated to at most the size of the remainder (from the given offset) of the size of the new block.
All other symbol attributes are unchanged.
Definition at line 1341 of file JITLink.h.
References llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Block::getSection(), llvm::jitlink::Block::getSize(), llvm::jitlink::Symbol::getSize(), and llvm::jitlink::Symbol::setSize().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/JITLink.h
lib/ExecutionEngine/JITLink/JITLink.cpp