LLVM: llvm::orc::IRCompileLayer Class Reference
llvm::orc::IRCompileLayer Class Reference
#include "llvm/ExecutionEngine/Orc/IRCompileLayer.h"
Classes
class IRCompiler
Public Types
using NotifyCompiledFunction = std::function< void(MaterializationResponsibility &R, ThreadSafeModule TSM)>
Public Member Functions
IRCompileLayer (ExecutionSession &ES, ObjectLayer &BaseLayer, std::unique_ptr< IRCompiler > Compile)
IRCompiler & getCompiler ()
void setNotifyCompiled (NotifyCompiledFunction NotifyCompiled)
void emit (std::unique_ptr< MaterializationResponsibility > R, ThreadSafeModule TSM) override
Emit should materialize the given IR.
Public Member Functions inherited from llvm::orc::IRLayer
IRLayer (ExecutionSession &ES, const IRSymbolMapper::ManglingOptions *&MO)
virtual ~IRLayer ()
ExecutionSession & getExecutionSession ()
Returns the ExecutionSession for this layer.
const IRSymbolMapper::ManglingOptions *& getManglingOptions () const
Get the mangling options for this layer.
void setCloneToNewContextOnEmit (bool CloneToNewContextOnEmit)
Sets the CloneToNewContextOnEmit flag (false by default).
bool getCloneToNewContextOnEmit () const
Returns the current value of the CloneToNewContextOnEmit flag.
virtual Error add (ResourceTrackerSP RT, ThreadSafeModule TSM)
Add a MaterializatinoUnit representing the given IR to the JITDylib targeted by the given tracker.
Error add (JITDylib &JD, ThreadSafeModule TSM)
Adds a MaterializationUnit representing the given IR to the given JITDylib.
Detailed Description
Definition at line 31 of file IRCompileLayer.h.
Member Typedef Documentation
NotifyCompiledFunction
using llvm::orc::IRCompileLayer::NotifyCompiledFunction = std::function<void(MaterializationResponsibility &R, ThreadSafeModule TSM)>
Definition at line 50 of file IRCompileLayer.h.
Constructor & Destructor Documentation
IRCompileLayer()
llvm::orc::IRCompileLayer::IRCompileLayer (ExecutionSession & ES, ObjectLayer & BaseLayer, std::unique_ptr< IRCompiler > Compile)
Definition at line 16 of file IRCompileLayer.cpp.
Member Function Documentation
emit()
void llvm::orc::IRCompileLayer::emit (std::unique_ptr< MaterializationResponsibility > R, ThreadSafeModule TSM) override virtual
Emit should materialize the given IR.
Implements llvm::orc::IRLayer.
Definition at line 28 of file IRCompileLayer.cpp.
References assert(), llvm::orc::ObjectLayer::emit(), llvm::orc::IRLayer::getExecutionSession(), move, llvm::orc::ExecutionSession::reportError(), and llvm::orc::ThreadSafeModule::withModuleDo().
getCompiler()
IRCompiler& llvm::orc::IRCompileLayer::getCompiler () inline
Definition at line 55 of file IRCompileLayer.h.
setNotifyCompiled()
void llvm::orc::IRCompileLayer::setNotifyCompiled (NotifyCompiledFunction NotifyCompiled)
Definition at line 23 of file IRCompileLayer.cpp.
References move.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/IRCompileLayer.h
lib/ExecutionEngine/Orc/IRCompileLayer.cpp