LLVM: llvm::orc::AsynchronousSymbolQuery Class Reference
llvm::orc::AsynchronousSymbolQuery Class Reference
A symbol query that returns results via a callback when results are ready.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
AsynchronousSymbolQuery (const SymbolLookupSet &Symbols, SymbolState RequiredState, SymbolsResolvedCallback NotifyComplete)
Create a query for the given symbols.
void notifySymbolMetRequiredState (const SymbolStringPtr &Name, JITEvaluatedSymbol Sym)
Notify the query that a requested symbol has reached the required state.
bool isComplete () const
Returns true if all symbols covered by this query have been resolved.
Friends
class ExecutionSession
class InProgressFullLookupState
class JITDylib
class JITSymbolResolverAdapter
class MaterializationResponsibility
Detailed Description
A symbol query that returns results via a callback when results are ready.
makes a callback when all symbols are available.
Definition at line 852 of file Core.h.
Constructor & Destructor Documentation
AsynchronousSymbolQuery()
llvm::orc::AsynchronousSymbolQuery::AsynchronousSymbolQuery (const SymbolLookupSet & Symbols, SymbolState RequiredState, SymbolsResolvedCallback NotifyComplete)
Create a query for the given symbols.
The NotifyComplete callback will be called once all queried symbols reach the given minimum state.
Definition at line 159 of file Core.cpp.
References assert(), and llvm::orc::Resolved.
Member Function Documentation
isComplete()
bool llvm::orc::AsynchronousSymbolQuery::isComplete () const inline
Returns true if all symbols covered by this query have been resolved.
Definition at line 873 of file Core.h.
notifySymbolMetRequiredState()
void llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState (const SymbolStringPtr & Name, JITEvaluatedSymbol Sym)
Notify the query that a requested symbol has reached the required state.
Definition at line 173 of file Core.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::JITEvaluatedSymbol::getFlags(), llvm::JITSymbolFlags::hasMaterializationSideEffectsOnly(), I, and move.
Friends And Related Function Documentation
ExecutionSession
friend class ExecutionSession friend
Definition at line 853 of file Core.h.
InProgressFullLookupState
friend class InProgressFullLookupState friend
Definition at line 854 of file Core.h.
JITDylib
friend class JITDylib friend
Definition at line 855 of file Core.h.
JITSymbolResolverAdapter
friend class JITSymbolResolverAdapter friend
Definition at line 856 of file Core.h.
MaterializationResponsibility
friend class MaterializationResponsibility friend
Definition at line 857 of file Core.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp