LLVM: llvm::BCChar6 Class Reference
llvm::BCChar6 Class Reference
Represents a character encoded in LLVM's Char6 encoding.
#include "llvm/Bitcode/BitcodeConvenience.h"
Public Member Functions
template<typename T >
char convert (T rawValue)
Static Public Member Functions
static void emitOp (llvm::BitCodeAbbrev &abbrev)
template<typename T >
static void assertValid (const T &data)
Static Public Member Functions inherited from llvm::detail::BCField<>
static void assertValid (const T &data)
Asserts that the given data is a valid value for this field.
static T convert (T rawValue)
Converts a raw numeric representation of this value to its preferred type.
Additional Inherited Members
Static Public Attributes inherited from llvm::detail::BCField<>
static const bool IsCompound
Detailed Description
Represents a character encoded in LLVM's Char6 encoding.
This format is suitable for encoding decimal numbers (without signs or exponents) and C identifiers (without dollar signs), but not much else.
See also
http://llvm.org/docs/BitCodeFormat.html#char6-encoded-value
Definition at line 122 of file BitcodeConvenience.h.
Member Function Documentation
assertValid()
template<typename T > static void llvm::BCChar6::assertValid (const T & data) inline static
Definition at line 128 of file BitcodeConvenience.h.
References assert(), and llvm::BitCodeAbbrevOp::isChar6().
convert()
template<typename T > char llvm::BCChar6::convert (T rawValue) inline
Definition at line 132 of file BitcodeConvenience.h.
emitOp()
static void llvm::BCChar6::emitOp (llvm::BitCodeAbbrev & abbrev) inline static
Definition at line 124 of file BitcodeConvenience.h.
References llvm::BitCodeAbbrev::Add(), and llvm::BitCodeAbbrevOp::Char6.
The documentation for this class was generated from the following file:
include/llvm/Bitcode/BitcodeConvenience.h