LLVM: llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State > Class Template Reference
llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State > Class Template Reference
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Member Functions
SetterImpl & setExecutorProcessControl (std::unique_ptr< ExecutorProcessControl > EPC)
Set a ExecutorProcessControl for this instance.
SetterImpl & setExecutionSession (std::unique_ptr< ExecutionSession > ES)
Set an ExecutionSession for this instance.
SetterImpl & setJITTargetMachineBuilder (JITTargetMachineBuilder JTMB)
Set the JITTargetMachineBuilder for this instance.
std::optional< JITTargetMachineBuilder > & getJITTargetMachineBuilder ()
Return a reference to the JITTargetMachineBuilder.
SetterImpl & setDataLayout (std::optional< DataLayout > DL)
Set a DataLayout for this instance.
SetterImpl & setObjectLinkingLayerCreator (LLJITBuilderState::ObjectLinkingLayerCreator CreateObjectLinkingLayer)
Set an ObjectLinkingLayer creation function.
SetterImpl & setCompileFunctionCreator (LLJITBuilderState::CompileFunctionCreator CreateCompileFunction)
Set a CompileFunctionCreator.
SetterImpl & setPlatformSetUp (LLJITBuilderState::PlatformSetupFunction SetUpPlatform)
Set up an PlatformSetupFunction.
SetterImpl & setNumCompileThreads (unsigned NumCompileThreads)
Set the number of compile threads to use.
SetterImpl & setExecutorProcessControl (ExecutorProcessControl &EPC)
Set an ExecutorProcessControl object.
Expected< std::unique_ptr< JITType > > create ()
Create an instance of the JIT.
Protected Member Functions
SetterImpl & impl ()
Detailed Description
template<typename JITType, typename SetterImpl, typename State>
class llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >
Definition at line 277 of file LLJIT.h.
Member Function Documentation
create()
template<typename JITType , typename SetterImpl , typename State > Expected<std::unique_ptr<JITType> > llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::create () inline
Create an instance of the JIT.
Definition at line 376 of file LLJIT.h.
getJITTargetMachineBuilder()
template<typename JITType , typename SetterImpl , typename State > std::optional<JITTargetMachineBuilder>& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::getJITTargetMachineBuilder () inline
Return a reference to the JITTargetMachineBuilder.
Definition at line 308 of file LLJIT.h.
impl()
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl () inline protected
Definition at line 388 of file LLJIT.h.
Referenced by llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::getJITTargetMachineBuilder(), llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setCompileFunctionCreator(), llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setDataLayout(), llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setExecutionSession(), llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setExecutorProcessControl(), llvm::orc::LLLazyJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setIndirectStubsManagerBuilder(), llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setJITTargetMachineBuilder(), llvm::orc::LLLazyJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setLazyCallthroughManager(), llvm::orc::LLLazyJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setLazyCompileFailureAddr(), llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setNumCompileThreads(), llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setObjectLinkingLayerCreator(), and llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setPlatformSetUp().
setCompileFunctionCreator()
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setCompileFunctionCreator (LLJITBuilderState::CompileFunctionCreator CreateCompileFunction) inline
Set a CompileFunctionCreator.
If this method is not called, a default creation function wil be used that will construct a basic IR compile function that is compatible with the selected number of threads (SimpleCompiler for '0' compile threads, ConcurrentIRCompiler otherwise).
Definition at line 335 of file LLJIT.h.
setDataLayout()
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setDataLayout (std::optional< DataLayout > DL) inline
Set a DataLayout for this instance.
If no data layout is specified then the target's default data layout will be used.
Definition at line 314 of file LLJIT.h.
setExecutionSession()
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setExecutionSession (std::unique_ptr< ExecutionSession > ES) inline
Set an ExecutionSession for this instance.
Definition at line 292 of file LLJIT.h.
setExecutorProcessControl() [1/2]
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setExecutorProcessControl (ExecutorProcessControl & EPC) inline
Set an ExecutorProcessControl object.
If the platform uses ObjectLinkingLayer by default and no ObjectLinkingLayerCreator has been set then the ExecutorProcessControl object will be used to supply the memory manager for the ObjectLinkingLayer.
Definition at line 370 of file LLJIT.h.
setExecutorProcessControl() [2/2]
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setExecutorProcessControl (std::unique_ptr< ExecutorProcessControl > EPC) inline
Set a ExecutorProcessControl for this instance.
This should not be called if ExecutionSession has already been set.
Definition at line 282 of file LLJIT.h.
setJITTargetMachineBuilder()
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setJITTargetMachineBuilder (JITTargetMachineBuilder JTMB) inline
Set the JITTargetMachineBuilder for this instance.
If this method is not called, JITTargetMachineBuilder::detectHost will be used to construct a default target machine builder for the host platform.
Definition at line 301 of file LLJIT.h.
setNumCompileThreads()
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setNumCompileThreads (unsigned NumCompileThreads) inline
Set the number of compile threads to use.
If set to zero, compilation will be performed on the execution thread when JITing in-process. If set to any other number N, a thread pool of N threads will be created for compilation.
If this method is not called, behavior will be as if it were called with a zero argument.
Definition at line 359 of file LLJIT.h.
setObjectLinkingLayerCreator()
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setObjectLinkingLayerCreator (LLJITBuilderState::ObjectLinkingLayerCreator CreateObjectLinkingLayer) inline
Set an ObjectLinkingLayer creation function.
If this method is not called, a default creation function will be used that will construct an RTDyldObjectLinkingLayer.
Definition at line 323 of file LLJIT.h.
setPlatformSetUp()
template<typename JITType , typename SetterImpl , typename State > SetterImpl& llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::setPlatformSetUp (LLJITBuilderState::PlatformSetupFunction SetUpPlatform) inline
Set up an PlatformSetupFunction.
If this method is not called then setUpGenericLLVMIRPlatform will be used to configure the JIT's platform support.
Definition at line 346 of file LLJIT.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/LLJIT.h