LLVM: llvm::dxil::ConstantBuffer Class Reference
llvm::dxil::ConstantBuffer Class Reference
#include "Target/DirectX/DXILResource.h"
Public Member Functions
ConstantBuffer (uint32_t I, hlsl::FrontendResource R)
void setSize (CBufferDataLayout &DL)
MDNode * write () const
void print (raw_ostream &O) const
Additional Inherited Members
Protected Types inherited from llvm::dxil::ResourceBase
enum ComponentType : uint32_t {
ComponentType::Invalid = 0, ComponentType::I1, ComponentType::I16, ComponentType::U16,
ComponentType::I32, ComponentType::U32, ComponentType::I64, ComponentType::U64,
ComponentType::F16, ComponentType::F32, ComponentType::F64, ComponentType::SNormF16,
ComponentType::UNormF16, ComponentType::SNormF32, ComponentType::UNormF32, ComponentType::SNormF64,
ComponentType::UNormF64, ComponentType::PackedS8x32, ComponentType::PackedU8x32, ComponentType::LastEntry
}
using Kinds = hlsl::ResourceKind
Protected Member Functions inherited from llvm::dxil::ResourceBase
ResourceBase (uint32_t I, hlsl::FrontendResource R)
void write (LLVMContext &Ctx, MutableArrayRef< Metadata * > Entries) const
void print (raw_ostream &O, StringRef IDPrefix, StringRef BindingPrefix) const
Static Protected Member Functions inherited from llvm::dxil::ResourceBase
static StringRef getKindName (Kinds Kind)
static void printKind (Kinds Kind, unsigned Alignment, raw_ostream &OS, bool SRV=false, bool HasCounter=false, uint32_t SampleCount=0)
static StringRef getComponentTypeName (ComponentType CompType)
static void printComponentType (Kinds Kind, ComponentType CompType, unsigned Alignment, raw_ostream &OS)
Protected Attributes inherited from llvm::dxil::ResourceBase
uint32_t ID
GlobalVariable * GV
StringRef Name
uint32_t Space
uint32_t LowerBound
uint32_t RangeSize
Detailed Description
Definition at line 111 of file DXILResource.h.
Constructor & Destructor Documentation
ConstantBuffer()
ConstantBuffer::ConstantBuffer (uint32_t I, hlsl::FrontendResource R)
Definition at line 300 of file DXILResource.cpp.
Member Function Documentation
print()
void ConstantBuffer::print (raw_ostream & O) const
Definition at line 307 of file DXILResource.cpp.
References llvm::dxil::ResourceBase::Invalid, llvm::left_justify(), llvm::dxil::ResourceBase::Name, OS, llvm::dxil::ResourceBase::print(), llvm::dxil::ResourceBase::printComponentType(), llvm::dxil::ResourceBase::printKind(), and llvm::right_justify().
setSize()
void ConstantBuffer::setSize (CBufferDataLayout & DL)
Definition at line 303 of file DXILResource.cpp.
References DL, llvm::GlobalValue::getValueType(), and llvm::dxil::ResourceBase::GV.
write()
MDNode * ConstantBuffer::write () const
Definition at line 363 of file DXILResource.cpp.
References B, llvm::Value::getContext(), and llvm::dxil::ResourceBase::GV.
The documentation for this class was generated from the following files:
lib/Target/DirectX/DXILResource.h
lib/Target/DirectX/DXILResource.cpp