LLVM: llvm::EarliestEscapeInfo Class Reference
llvm::EarliestEscapeInfo Class Reference final
Context-sensitive CaptureInfo provider, which computes and caches the earliest common dominator closure of all captures.
#include "llvm/Analysis/AliasAnalysis.h"
Public Member Functions
EarliestEscapeInfo (DominatorTree &DT, const LoopInfo &LI, const SmallPtrSetImpl< const Value * > &EphValues)
bool isNotCapturedBeforeOrAt (const Value *Object, const Instruction *I) override
void removeInstruction (Instruction *I)
Public Member Functions inherited from llvm::CaptureInfo
virtual ~CaptureInfo ()=0
Detailed Description
Context-sensitive CaptureInfo provider, which computes and caches the earliest common dominator closure of all captures.
It provides a good approximation to a precise "captures before" analysis.
Definition at line 165 of file AliasAnalysis.h.
Constructor & Destructor Documentation
EarliestEscapeInfo()
llvm::EarliestEscapeInfo::EarliestEscapeInfo (DominatorTree & DT, const LoopInfo & LI, const SmallPtrSetImpl< const Value * > & EphValues) inline
Definition at line 182 of file AliasAnalysis.h.
Member Function Documentation
isNotCapturedBeforeOrAt()
bool EarliestEscapeInfo::isNotCapturedBeforeOrAt (const Value * Object, const Instruction * I) override virtual
Implements llvm::CaptureInfo.
Definition at line 200 of file BasicAliasAnalysis.cpp.
References llvm::FindEarliestCapture(), I, llvm::MipsISD::Ins, llvm::isIdentifiedFunctionLocal(), llvm::isPotentiallyReachable(), and llvm::Object.
removeInstruction()
void EarliestEscapeInfo::removeInstruction (Instruction * I)
Definition at line 225 of file BasicAliasAnalysis.cpp.
References I.
The documentation for this class was generated from the following files:
include/llvm/Analysis/AliasAnalysis.h
lib/Analysis/BasicAliasAnalysis.cpp