LLVM: llvm::orc::SequenceBBQuery Class Reference
llvm::orc::SequenceBBQuery Class Reference
#include "llvm/ExecutionEngine/Orc/SpeculateAnalyses.h"
Public Types
using VisitedBlocksInfoTy = DenseMap< const BasicBlock *, WalkDirection >
using BlockListTy = SmallVector< const BasicBlock *, 8 >
using BackEdgesInfoTy = SmallVector< std::pair< const BasicBlock *, const BasicBlock * >, 8 >
using BlockFreqInfoTy = SmallVector< std::pair< const BasicBlock *, uint64_t >, 8 >
Public Types inherited from llvm::orc::SpeculateQuery
using ResultTy = std::optional< DenseMap< StringRef, DenseSet< StringRef > >>
Public Member Functions
ResultTy operator() (Function &F)
Additional Inherited Members
Protected Member Functions inherited from llvm::orc::SpeculateQuery
void findCalles (const BasicBlock *, DenseSet< StringRef > &)
bool isStraightLine (const Function &F)
Detailed Description
Definition at line 49 of file SpeculateAnalyses.h.
Member Typedef Documentation
BackEdgesInfoTy
using llvm::orc::SequenceBBQuery::BackEdgesInfoTy = SmallVector<std::pair<const BasicBlock *, const BasicBlock *>, 8>
Definition at line 60 of file SpeculateAnalyses.h.
BlockFreqInfoTy
using llvm::orc::SequenceBBQuery::BlockFreqInfoTy = SmallVector<std::pair<const BasicBlock *, uint64_t>, 8>
Definition at line 62 of file SpeculateAnalyses.h.
BlockListTy
using llvm::orc::SequenceBBQuery::BlockListTy = SmallVector<const BasicBlock *, 8>
Definition at line 58 of file SpeculateAnalyses.h.
VisitedBlocksInfoTy
using llvm::orc::SequenceBBQuery::VisitedBlocksInfoTy = DenseMap<const BasicBlock *, WalkDirection>
Definition at line 57 of file SpeculateAnalyses.h.
Member Function Documentation
operator()()
SpeculateQuery::ResultTy llvm::orc::SequenceBBQuery::operator() (Function & F)
Definition at line 282 of file SpeculateAnalyses.cpp.
References BB, F, llvm::orc::SpeculateQuery::findCalles(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), llvm::orc::SpeculateQuery::isStraightLine(), and move.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/SpeculateAnalyses.h
lib/ExecutionEngine/Orc/SpeculateAnalyses.cpp