LLVM: llvm::ms_demangle::ArenaAllocator Class Reference
llvm::ms_demangle::ArenaAllocator Class Reference
#include "llvm/Demangle/MicrosoftDemangle.h"
Public Member Functions
ArenaAllocator ()
~ArenaAllocator ()
char * allocUnalignedBuffer (size_t Size)
template<typename T , typename... Args>
T * allocArray (size_t Count)
template<typename T , typename... Args>
T * alloc (Args &&... ConstructorArgs)
Detailed Description
Definition at line 26 of file MicrosoftDemangle.h.
Constructor & Destructor Documentation
ArenaAllocator()
llvm::ms_demangle::ArenaAllocator::ArenaAllocator () inline
Definition at line 44 of file MicrosoftDemangle.h.
References llvm::ms_demangle::AllocUnit.
~ArenaAllocator()
llvm::ms_demangle::ArenaAllocator::~ArenaAllocator () inline
Definition at line 46 of file MicrosoftDemangle.h.
References assert().
Member Function Documentation
alloc()
template<typename T , typename... Args> T* llvm::ms_demangle::ArenaAllocator::alloc (Args &&... ConstructorArgs) inline
Definition at line 89 of file MicrosoftDemangle.h.
References llvm::ms_demangle::AllocUnit, assert(), P, and T.
Referenced by nodeListToNodeArray(), synthesizeNamedIdentifier(), synthesizeQualifiedName(), and synthesizeVariable().
allocArray()
template<typename T , typename... Args> T* llvm::ms_demangle::ArenaAllocator::allocArray (size_t Count) inline
Definition at line 70 of file MicrosoftDemangle.h.
References llvm::ms_demangle::AllocUnit, assert(), llvm::max(), P, and T.
Referenced by nodeListToNodeArray(), and synthesizeQualifiedName().
allocUnalignedBuffer()
char* llvm::ms_demangle::ArenaAllocator::allocUnalignedBuffer (size_t Size) inline
Definition at line 56 of file MicrosoftDemangle.h.
References llvm::ms_demangle::AllocUnit, assert(), llvm::max(), and P.
The documentation for this class was generated from the following file:
include/llvm/Demangle/MicrosoftDemangle.h