LLVM: llvm::ResourceManager Class Reference
llvm::ResourceManager Class Reference
#include "llvm/CodeGen/MachinePipeliner.h"
Public Member Functions
ResourceManager (const TargetSubtargetInfo *ST, SwingSchedulerDAG *DAG)
void initProcResourceVectors (const MCSchedModel &SM, SmallVectorImpl< uint64_t > &Masks)
bool canReserveResources (SUnit &SU, int Cycle)
Check if the resources occupied by a machine instruction are available in the current state.
void reserveResources (SUnit &SU, int Cycle)
Reserve the resources occupied by a machine instruction and change the current state to reflect that change.
int calculateResMII () const
void init (int II)
Initialize resources with the initiation interval II.
Detailed Description
Definition at line 445 of file MachinePipeliner.h.
Constructor & Destructor Documentation
ResourceManager()
llvm::ResourceManager::ResourceManager (const TargetSubtargetInfo * ST, SwingSchedulerDAG * DAG) inline
Definition at line 495 of file MachinePipeliner.h.
References initProcResourceVectors(), llvm::SwpForceIssueWidth, and TII.
Member Function Documentation
calculateResMII()
int ResourceManager::calculateResMII () const
Definition at line 3197 of file MachinePipeliner.cpp.
References llvm::dbgs(), llvm::ScheduleDAGInstrs::dumpNode(), E, llvm::SUnit::getInstr(), llvm::MCSchedModel::getNumProcResourceKinds(), llvm::MachineInstr::getOpcode(), llvm::MCSchedModel::getProcResource(), llvm::ScheduleDAGInstrs::getSchedClass(), llvm::MCSubtargetInfo::getWriteProcResBegin(), llvm::MCSubtargetInfo::getWriteProcResEnd(), I, llvm::MCSchedClassDesc::isValid(), llvm::TargetInstrInfo::isZeroCost(), LLVM_DEBUG, llvm::make_range(), llvm::MCProcResourceDesc::Name, llvm::MCSchedClassDesc::NumMicroOps, llvm::MCProcResourceDesc::NumUnits, llvm::X86AS::SS, llvm::ScheduleDAG::SUnits, and SwpDebugResource.
canReserveResources()
bool ResourceManager::canReserveResources (SUnit & SU, int Cycle)
Check if the resources occupied by a machine instruction are available in the current state.
Definition at line 3042 of file MachinePipeliner.cpp.
References llvm::dbgs(), llvm::MachineInstr::getDesc(), llvm::SUnit::getInstr(), llvm::ScheduleDAGInstrs::getSchedClass(), llvm::MachineInstr::isPseudo(), llvm::MCSchedClassDesc::isValid(), LLVM_DEBUG, and SwpDebugResource.
Referenced by llvm::SMSchedule::insert().
init()
void ResourceManager::init (int II)
Initialize resources with the initiation interval II.
Definition at line 3272 of file MachinePipeliner.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::MCSchedModel::getNumProcResourceKinds(), I, and llvm::SmallVectorImpl< T >::resize().
Referenced by llvm::SMSchedule::setInitiationInterval().
initProcResourceVectors()
void ResourceManager::initProcResourceVectors (const MCSchedModel & SM, SmallVectorImpl< uint64_t > & Masks)
Definition at line 3000 of file MachinePipeliner.cpp.
References assert(), llvm::dbgs(), E, llvm::format(), llvm::MCSchedModel::getNumProcResourceKinds(), llvm::MCSchedModel::getProcResource(), I, LLVM_DEBUG, llvm::MCProcResourceDesc::Name, llvm::MCProcResourceDesc::NumUnits, llvm::SmallVectorImpl< T >::resize(), llvm::MCProcResourceDesc::SubUnitsIdxBegin, and SwpShowResMask.
Referenced by ResourceManager().
reserveResources()
void ResourceManager::reserveResources (SUnit & SU, int Cycle)
Reserve the resources occupied by a machine instruction and change the current state to reflect that change.
Definition at line 3068 of file MachinePipeliner.cpp.
References llvm::dbgs(), llvm::MachineInstr::getDesc(), llvm::SUnit::getInstr(), llvm::ScheduleDAGInstrs::getSchedClass(), llvm::MachineInstr::isPseudo(), llvm::MCSchedClassDesc::isValid(), LLVM_DEBUG, and SwpDebugResource.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachinePipeliner.h
lib/CodeGen/MachinePipeliner.cpp