LLVM: llvm::RepeatedPass< PassT > Class Template Reference
llvm::RepeatedPass< PassT > Class Template Reference
A utility pass template that simply runs another pass multiple times.
#include "llvm/IR/PassManager.h"
Public Member Functions
RepeatedPass (int Count, PassT &&P)
template<typename IRUnitT , typename AnalysisManagerT , typename... Ts>
PreservedAnalyses run (IRUnitT &IR, AnalysisManagerT &AM, Ts &&... Args)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< RepeatedPass< PassT > >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< RepeatedPass< PassT > >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
template<typename PassT>
class llvm::RepeatedPass< PassT >
A utility pass template that simply runs another pass multiple times.
This can be useful when debugging or testing passes. It also serves as an example of how to extend the pass manager in ways beyond composition.
Definition at line 1310 of file PassManager.h.
Constructor & Destructor Documentation
RepeatedPass()
template<typename PassT > llvm::RepeatedPass< PassT >::RepeatedPass (int Count, PassT && P) inline
Definition at line 1312 of file PassManager.h.
Member Function Documentation
printPipeline()
template<typename PassT > void llvm::RepeatedPass< PassT >::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName) inline
Definition at line 1340 of file PassManager.h.
References OS.
run()
template<typename PassT > template<typename IRUnitT , typename AnalysisManagerT , typename... Ts> PreservedAnalyses llvm::RepeatedPass< PassT >::run (IRUnitT & IR, AnalysisManagerT & AM, Ts &&... Args) inline
Definition at line 1316 of file PassManager.h.
References llvm::PreservedAnalyses::all(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, i, llvm::PreservedAnalyses::intersect(), IR, llvm::PassInstrumentation::runAfterPass(), and llvm::PassInstrumentation::runBeforePass().
The documentation for this class was generated from the following file:
include/llvm/IR/PassManager.h