LLVM: llvm::TensorSpec Class Reference
llvm::TensorSpec Class Reference final
#include "llvm/Analysis/TensorSpec.h"
Public Member Functions
const std::string & name () const
int port () const
TensorType type () const
const std::vector< int64_t > & shape () const
bool operator== (const TensorSpec &Other) const
bool operator!= (const TensorSpec &Other) const
size_t getElementCount () const
Get the number of elements in a tensor with this shape.
size_t getElementByteSize () const
Get the size, in bytes, of one element.
size_t getTotalTensorBufferSize () const
Get the total size of a memory buffer needed to store the whole tensor.
template<typename T >
bool isElementType () const
TensorSpec (const std::string &NewName, const TensorSpec &Other)
void toJSON (json::OStream &OS) const
Static Public Member Functions
template<typename T >
static TensorSpec createSpec (const std::string &Name, const std::vector< int64_t > &Shape, int Port=0)
Detailed Description
Definition at line 54 of file TensorSpec.h.
Constructor & Destructor Documentation
TensorSpec()
llvm::TensorSpec::TensorSpec (const std::string & NewName, const TensorSpec & Other) inline
Definition at line 86 of file TensorSpec.h.
References Other.
Referenced by createSpec().
Member Function Documentation
createSpec()
template<typename T > static TensorSpec llvm::TensorSpec::createSpec (const std::string & Name, const std::vector< int64_t > & Shape, int Port = 0) inline static
Definition at line 57 of file TensorSpec.h.
References T, and TensorSpec().
getElementByteSize()
size_t llvm::TensorSpec::getElementByteSize () const inline
Get the size, in bytes, of one element.
Definition at line 78 of file TensorSpec.h.
getElementCount()
size_t llvm::TensorSpec::getElementCount () const inline
Get the number of elements in a tensor with this shape.
Definition at line 76 of file TensorSpec.h.
getTotalTensorBufferSize()
size_t llvm::TensorSpec::getTotalTensorBufferSize () const inline
Get the total size of a memory buffer needed to store the whole tensor.
Definition at line 80 of file TensorSpec.h.
isElementType()
template<typename T > bool llvm::TensorSpec::isElementType () const inline
Definition at line 82 of file TensorSpec.h.
name()
const std::string& llvm::TensorSpec::name () const inline
Definition at line 63 of file TensorSpec.h.
Referenced by toJSON().
operator!=()
bool llvm::TensorSpec::operator!= (const TensorSpec & Other) const inline
Definition at line 73 of file TensorSpec.h.
References Other.
operator==()
bool llvm::TensorSpec::operator== (const TensorSpec & Other) const inline
Definition at line 68 of file TensorSpec.h.
References Other.
port()
int llvm::TensorSpec::port () const inline
Definition at line 64 of file TensorSpec.h.
Referenced by toJSON().
shape()
const std::vector<int64_t>& llvm::TensorSpec::shape () const inline
Definition at line 66 of file TensorSpec.h.
Referenced by toJSON().
toJSON()
void llvm::TensorSpec::toJSON (json::OStream & OS) const
Definition at line 50 of file TensorSpec.cpp.
References D, name(), OS, port(), shape(), llvm::toString(), and type().
type()
TensorType llvm::TensorSpec::type () const inline
Definition at line 65 of file TensorSpec.h.
Referenced by toJSON().
The documentation for this class was generated from the following files:
include/llvm/Analysis/TensorSpec.h
lib/Analysis/TensorSpec.cpp