LLVM: llvm::DWARFUnitIndex Class Reference
llvm::DWARFUnitIndex Class Reference
#include "llvm/DebugInfo/DWARF/DWARFUnitIndex.h"
Classes
class Entry
Public Member Functions
DWARFUnitIndex (DWARFSectionKind InfoColumnKind)
operator bool () const
bool parse (DataExtractor IndexData)
void dump (raw_ostream &OS) const
uint32_t getVersion () const
const Entry * getFromOffset (uint64_t Offset) const
const Entry * getFromHash (uint64_t Offset) const
ArrayRef< DWARFSectionKind > getColumnKinds () const
ArrayRef< Entry > getRows () const
MutableArrayRef< Entry > getMutableRows ()
Detailed Description
Definition at line 99 of file DWARFUnitIndex.h.
Constructor & Destructor Documentation
DWARFUnitIndex()
llvm::DWARFUnitIndex::DWARFUnitIndex (DWARFSectionKind InfoColumnKind) inline
Definition at line 168 of file DWARFUnitIndex.h.
Member Function Documentation
dump()
void DWARFUnitIndex::dump (raw_ostream & OS) const
Definition at line 215 of file DWARFUnitIndex.cpp.
References llvm::DW_SECT_EXT_TYPES, llvm::format(), i, llvm::left_justify(), and OS.
getColumnKinds()
ArrayRef<DWARFSectionKind> llvm::DWARFUnitIndex::getColumnKinds () const inline
Definition at line 181 of file DWARFUnitIndex.h.
References llvm::ArrayRef().
getFromHash()
const DWARFUnitIndex::Entry * DWARFUnitIndex::getFromHash (uint64_t Offset) const
Definition at line 306 of file DWARFUnitIndex.cpp.
References getSignature(), H, llvm::BitmaskEnumDetail::Mask(), S, and uint64_t.
getFromOffset()
const DWARFUnitIndex::Entry * DWARFUnitIndex::getFromOffset (uint64_t Offset) const
Definition at line 283 of file DWARFUnitIndex.cpp.
References E, i, I, llvm::Offset, llvm::partition_point(), and llvm::sort().
getMutableRows()
MutableArrayRef<Entry> llvm::DWARFUnitIndex::getMutableRows () inline
Definition at line 189 of file DWARFUnitIndex.h.
References llvm::MutableArrayRef().
getRows()
ArrayRef<Entry> llvm::DWARFUnitIndex::getRows () const inline
Definition at line 185 of file DWARFUnitIndex.h.
References llvm::ArrayRef().
Referenced by addAllTypesFromDWP().
getVersion()
uint32_t llvm::DWARFUnitIndex::getVersion () const inline
Definition at line 176 of file DWARFUnitIndex.h.
operator bool()
llvm::DWARFUnitIndex::operator bool () const inline explicit
Definition at line 171 of file DWARFUnitIndex.h.
parse()
bool DWARFUnitIndex::parse (DataExtractor IndexData)
Definition at line 119 of file DWARFUnitIndex.cpp.
References b.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFUnitIndex.h
lib/DebugInfo/DWARF/DWARFUnitIndex.cpp