LLVM: llvm::jitlink::CompactUnwindSplitter Class Reference
llvm::jitlink::CompactUnwindSplitter Class Reference
A pass to split up __LD,__compact_unwind sections.
#include "ExecutionEngine/JITLink/MachOLinkGraphBuilder.h"
Public Member Functions
CompactUnwindSplitter (StringRef CompactUnwindSectionName)
Error operator() (LinkGraph &G)
Detailed Description
A pass to split up __LD,__compact_unwind sections.
Definition at line 239 of file MachOLinkGraphBuilder.h.
Constructor & Destructor Documentation
CompactUnwindSplitter()
llvm::jitlink::CompactUnwindSplitter::CompactUnwindSplitter (StringRef CompactUnwindSectionName) inline
Definition at line 241 of file MachOLinkGraphBuilder.h.
Member Function Documentation
operator()()
Error llvm::jitlink::CompactUnwindSplitter::operator() (LinkGraph & G)
Definition at line 739 of file MachOLinkGraphBuilder.cpp.
References llvm::Triple::aarch64, B, llvm::dbgs(), E, llvm::formatv(), G, I, llvm::jitlink::Edge::KeepAlive, LLVM_DEBUG, llvm::StringRef::size(), llvm::Error::success(), and llvm::Triple::x86_64.
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.h
lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp