LLVM: llvm::DivergencePropagator< ContextT > Class Template Reference
llvm::DivergencePropagator< ContextT > Class Template Reference
Compute divergence starting with a divergent branch.
#include "llvm/ADT/GenericUniformityImpl.h"
Public Types
using BlockT = typename ContextT::BlockT
using DominatorTreeT = typename ContextT::DominatorTreeT
using FunctionT = typename ContextT::FunctionT
using ValueRefT = typename ContextT::ValueRefT
using CycleInfoT = GenericCycleInfo< ContextT >
using CycleT = typename CycleInfoT::CycleT
using ModifiedPO = ModifiedPostOrder< ContextT >
using SyncDependenceAnalysisT = GenericSyncDependenceAnalysis< ContextT >
using DivergenceDescriptorT = typename SyncDependenceAnalysisT::DivergenceDescriptor
using BlockLabelMapT = typename SyncDependenceAnalysisT::BlockLabelMap
Public Member Functions
DivergencePropagator (const ModifiedPO &CyclePOT, const DominatorTreeT &DT, const CycleInfoT &CI, const BlockT &DivTermBlock)
void printDefs (raw_ostream &Out)
bool computeJoin (const BlockT &SuccBlock, const BlockT &PushedLabel)
bool visitCycleExitEdge (const BlockT &ExitBlock, const BlockT &Label)
bool visitEdge (const BlockT &SuccBlock, const BlockT &Label)
std::unique_ptr< DivergenceDescriptorT > computeJoinPoints ()
Public Attributes
const ModifiedPO & CyclePOT
const DominatorTreeT & DT
const CycleInfoT & CI
const BlockT & DivTermBlock
const ContextT & Context
SparseBitVector FreshLabels
std::unique_ptr< DivergenceDescriptorT > DivDesc
BlockLabelMapT & BlockLabels
Detailed Description
template<typename ContextT>
class llvm::DivergencePropagator< ContextT >
Compute divergence starting with a divergent branch.
Definition at line 139 of file GenericUniformityImpl.h.
Member Typedef Documentation
BlockLabelMapT
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::BlockLabelMapT = typename SyncDependenceAnalysisT::BlockLabelMap
Definition at line 490 of file GenericUniformityImpl.h.
BlockT
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::BlockT = typename ContextT::BlockT
Definition at line 478 of file GenericUniformityImpl.h.
CycleInfoT
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::CycleInfoT = GenericCycleInfo<ContextT>
Definition at line 483 of file GenericUniformityImpl.h.
CycleT
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::CycleT = typename CycleInfoT::CycleT
Definition at line 484 of file GenericUniformityImpl.h.
DivergenceDescriptorT
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::DivergenceDescriptorT = typename SyncDependenceAnalysisT::DivergenceDescriptor
Definition at line 489 of file GenericUniformityImpl.h.
DominatorTreeT
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::DominatorTreeT = typename ContextT::DominatorTreeT
Definition at line 479 of file GenericUniformityImpl.h.
FunctionT
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::FunctionT = typename ContextT::FunctionT
Definition at line 480 of file GenericUniformityImpl.h.
ModifiedPO
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::ModifiedPO = ModifiedPostOrder<ContextT>
Definition at line 486 of file GenericUniformityImpl.h.
SyncDependenceAnalysisT
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::SyncDependenceAnalysisT = GenericSyncDependenceAnalysis<ContextT>
Definition at line 487 of file GenericUniformityImpl.h.
ValueRefT
template<typename ContextT > using llvm::DivergencePropagator< ContextT >::ValueRefT = typename ContextT::ValueRefT
Definition at line 481 of file GenericUniformityImpl.h.
Constructor & Destructor Documentation
DivergencePropagator()
template<typename ContextT > llvm::DivergencePropagator< ContextT >::DivergencePropagator (const ModifiedPO & CyclePOT, const DominatorTreeT & DT, const CycleInfoT & CI, const BlockT & DivTermBlock) inline
Definition at line 508 of file GenericUniformityImpl.h.
Member Function Documentation
computeJoin()
template<typename ContextT > bool llvm::DivergencePropagator< ContextT >::computeJoin (const BlockT & SuccBlock, const BlockT & PushedLabel) inline
Definition at line 531 of file GenericUniformityImpl.h.
References llvm::DivergencePropagator< ContextT >::BlockLabels, llvm::DivergencePropagator< ContextT >::Context, llvm::DivergencePropagator< ContextT >::CyclePOT, llvm::dbgs(), llvm::DivergencePropagator< ContextT >::FreshLabels, LLVM_DEBUG, and llvm::SparseBitVector< ElementSize >::set().
Referenced by llvm::DivergencePropagator< ContextT >::visitCycleExitEdge(), and llvm::DivergencePropagator< ContextT >::visitEdge().
computeJoinPoints()
template<typename ContextT > std::unique_ptr<DivergenceDescriptorT> llvm::DivergencePropagator< ContextT >::computeJoinPoints () inline
Definition at line 591 of file GenericUniformityImpl.h.
References assert(), llvm::DivergencePropagator< ContextT >::BlockLabels, llvm::DivergencePropagator< ContextT >::CI, llvm::DivergencePropagator< ContextT >::Context, llvm::DivergencePropagator< ContextT >::CyclePOT, llvm::dbgs(), llvm::DivergencePropagator< ContextT >::DivDesc, llvm::DivergencePropagator< ContextT >::DivTermBlock, llvm::SparseBitVector< ElementSize >::find_last(), llvm::DivergencePropagator< ContextT >::FreshLabels, llvm::GenericCycleInfo< ContextT >::getCycle(), llvm::GenericCycle< ContextT >::getExitBlocks(), llvm::GenericCycle< ContextT >::getHeader(), llvm::GenericCycle< ContextT >::getParentCycle(), llvm::GenericCycle< ContextT >::isReducible(), LLVM_DEBUG, move, llvm::DivergencePropagator< ContextT >::printDefs(), llvm::SparseBitVector< ElementSize >::reset(), llvm::successors(), llvm::DivergencePropagator< ContextT >::visitCycleExitEdge(), and llvm::DivergencePropagator< ContextT >::visitEdge().
Referenced by llvm::SyncDependenceAnalysis::getJoinBlocks(), and llvm::GenericSyncDependenceAnalysis< ContextT >::getJoinBlocks().
printDefs()
template<typename ContextT > void llvm::DivergencePropagator< ContextT >::printDefs (raw_ostream & Out) inline
Definition at line 514 of file GenericUniformityImpl.h.
References llvm::DivergencePropagator< ContextT >::BlockLabels, llvm::DivergencePropagator< ContextT >::Context, and llvm::DivergencePropagator< ContextT >::CyclePOT.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoinPoints().
visitCycleExitEdge()
template<typename ContextT > bool llvm::DivergencePropagator< ContextT >::visitCycleExitEdge (const BlockT & ExitBlock, const BlockT & Label) inline
Definition at line 568 of file GenericUniformityImpl.h.
References llvm::DivergencePropagator< ContextT >::computeJoin(), llvm::DivergencePropagator< ContextT >::Context, llvm::dbgs(), llvm::DivergencePropagator< ContextT >::DivDesc, and LLVM_DEBUG.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoinPoints().
visitEdge()
template<typename ContextT > bool llvm::DivergencePropagator< ContextT >::visitEdge (const BlockT & SuccBlock, const BlockT & Label) inline
Definition at line 580 of file GenericUniformityImpl.h.
References llvm::DivergencePropagator< ContextT >::computeJoin(), llvm::DivergencePropagator< ContextT >::Context, llvm::dbgs(), llvm::DivergencePropagator< ContextT >::DivDesc, and LLVM_DEBUG.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoinPoints().
Member Data Documentation
BlockLabels
template<typename ContextT > BlockLabelMapT& llvm::DivergencePropagator< ContextT >::BlockLabels
Definition at line 506 of file GenericUniformityImpl.h.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoin(), llvm::DivergencePropagator< ContextT >::computeJoinPoints(), and llvm::DivergencePropagator< ContextT >::printDefs().
CI
template<typename ContextT > const CycleInfoT& llvm::DivergencePropagator< ContextT >::CI
Definition at line 494 of file GenericUniformityImpl.h.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoinPoints().
Context
template<typename ContextT > const ContextT& llvm::DivergencePropagator< ContextT >::Context
Definition at line 496 of file GenericUniformityImpl.h.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoin(), llvm::DivergencePropagator< ContextT >::computeJoinPoints(), llvm::DivergencePropagator< ContextT >::printDefs(), llvm::DivergencePropagator< ContextT >::visitCycleExitEdge(), and llvm::DivergencePropagator< ContextT >::visitEdge().
CyclePOT
template<typename ContextT > const ModifiedPO& llvm::DivergencePropagator< ContextT >::CyclePOT
Definition at line 492 of file GenericUniformityImpl.h.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoin(), llvm::DivergencePropagator< ContextT >::computeJoinPoints(), and llvm::DivergencePropagator< ContextT >::printDefs().
DivDesc
template<typename ContextT > std::unique_ptr<DivergenceDescriptorT> llvm::DivergencePropagator< ContextT >::DivDesc
Definition at line 505 of file GenericUniformityImpl.h.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoinPoints(), llvm::DivergencePropagator< ContextT >::visitCycleExitEdge(), and llvm::DivergencePropagator< ContextT >::visitEdge().
DivTermBlock
template<typename ContextT > const BlockT& llvm::DivergencePropagator< ContextT >::DivTermBlock
Definition at line 495 of file GenericUniformityImpl.h.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoinPoints().
DT
template<typename ContextT > const DominatorTreeT& llvm::DivergencePropagator< ContextT >::DT
Definition at line 493 of file GenericUniformityImpl.h.
FreshLabels
template<typename ContextT > SparseBitVector llvm::DivergencePropagator< ContextT >::FreshLabels
Definition at line 502 of file GenericUniformityImpl.h.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoin(), and llvm::DivergencePropagator< ContextT >::computeJoinPoints().
The documentation for this class was generated from the following file:
include/llvm/ADT/GenericUniformityImpl.h