LLVM: llvm::CSKYMCExpr Class Reference
llvm::CSKYMCExpr Class Reference
#include "Target/CSKY/MCTargetDesc/CSKYMCExpr.h"
Public Types
enum VariantKind {
VK_CSKY_None, VK_CSKY_ADDR, VK_CSKY_ADDR_HI16, VK_CSKY_ADDR_LO16,
VK_CSKY_PCREL, VK_CSKY_GOT, VK_CSKY_GOT_IMM18_BY4, VK_CSKY_GOTPC,
VK_CSKY_GOTOFF, VK_CSKY_PLT, VK_CSKY_PLT_IMM18_BY4, VK_CSKY_TLSIE,
VK_CSKY_TLSLE, VK_CSKY_TLSGD, VK_CSKY_TLSLDO, VK_CSKY_TLSLDM,
VK_CSKY_Invalid
}
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
VariantKind getKind () const
const MCExpr * getSubExpr () const
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static const CSKYMCExpr * create (const MCExpr *Expr, VariantKind Kind, MCContext &Ctx)
static bool classof (const MCExpr *E)
static StringRef getVariantKindName (VariantKind Kind)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Definition at line 17 of file CSKYMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::CSKYMCExpr::VariantKind
Enumerator
VK_CSKY_None
VK_CSKY_ADDR
VK_CSKY_ADDR_HI16
VK_CSKY_ADDR_LO16
VK_CSKY_PCREL
VK_CSKY_GOT
VK_CSKY_GOT_IMM18_BY4
VK_CSKY_GOTPC
VK_CSKY_GOTOFF
VK_CSKY_PLT
VK_CSKY_PLT_IMM18_BY4
VK_CSKY_TLSIE
VK_CSKY_TLSLE
VK_CSKY_TLSGD
VK_CSKY_TLSLDO
VK_CSKY_TLSLDM
VK_CSKY_Invalid
Definition at line 19 of file CSKYMCExpr.h.
Member Function Documentation
classof()
static bool llvm::CSKYMCExpr::classof (const MCExpr * E) inline static
Definition at line 68 of file CSKYMCExpr.h.
References E, and llvm::MCExpr::Target.
create()
const CSKYMCExpr * CSKYMCExpr::create (const MCExpr * Expr, VariantKind Kind, MCContext & Ctx) static
Definition at line 22 of file CSKYMCExpr.cpp.
Referenced by llvm::CSKYConstantPool::addEntry(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), and llvm::CSKYMCInstLower::lowerSymbolOperand().
evaluateAsRelocatableImpl()
bool CSKYMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 112 of file CSKYMCExpr.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), Fixup, getKind(), getSubExpr(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), VK_CSKY_GOT, VK_CSKY_GOT_IMM18_BY4, VK_CSKY_GOTOFF, VK_CSKY_GOTPC, VK_CSKY_PLT, VK_CSKY_PLT_IMM18_BY4, VK_CSKY_TLSGD, VK_CSKY_TLSIE, VK_CSKY_TLSLDM, VK_CSKY_TLSLDO, and VK_CSKY_TLSLE.
findAssociatedFragment()
MCFragment* llvm::CSKYMCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 62 of file CSKYMCExpr.h.
References llvm::MCExpr::findAssociatedFragment(), and getSubExpr().
fixELFSymbolsInTLSFixups()
void CSKYMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 99 of file CSKYMCExpr.cpp.
References llvm::HexStyle::Asm, fixELFSymbolsInTLSFixupsImpl(), getKind(), getSubExpr(), VK_CSKY_TLSGD, VK_CSKY_TLSIE, and VK_CSKY_TLSLE.
getKind()
VariantKind llvm::CSKYMCExpr::getKind () const inline
Definition at line 51 of file CSKYMCExpr.h.
Referenced by llvm::CSKYConstantPool::addEntry(), evaluateAsRelocatableImpl(), fixELFSymbolsInTLSFixups(), llvm::CSKYMCCodeEmitter::getTargetFixup(), and printImpl().
getSubExpr()
const MCExpr* llvm::CSKYMCExpr::getSubExpr () const inline
Definition at line 54 of file CSKYMCExpr.h.
Referenced by llvm::CSKYConstantPool::addEntry(), evaluateAsRelocatableImpl(), findAssociatedFragment(), fixELFSymbolsInTLSFixups(), and visitUsedExpr().
getVariantKindName()
StringRef CSKYMCExpr::getVariantKindName (VariantKind Kind) static
Definition at line 27 of file CSKYMCExpr.cpp.
References llvm_unreachable, VK_CSKY_ADDR, VK_CSKY_ADDR_HI16, VK_CSKY_ADDR_LO16, VK_CSKY_GOT, VK_CSKY_GOT_IMM18_BY4, VK_CSKY_GOTOFF, VK_CSKY_GOTPC, VK_CSKY_None, VK_CSKY_PLT, VK_CSKY_PLT_IMM18_BY4, VK_CSKY_TLSGD, VK_CSKY_TLSIE, VK_CSKY_TLSLDM, VK_CSKY_TLSLDO, and VK_CSKY_TLSLE.
Referenced by printImpl().
printImpl()
void CSKYMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 65 of file CSKYMCExpr.cpp.
References getKind(), getVariantKindName(), OS, and llvm::MCExpr::print().
visitUsedExpr()
void CSKYMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 61 of file CSKYMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
lib/Target/CSKY/MCTargetDesc/CSKYMCExpr.h
lib/Target/CSKY/MCTargetDesc/CSKYMCExpr.cpp