LLVM: llvm::TGLexer Class Reference
llvm::TGLexer Class Reference
TGLexer - TableGen Lexer class.
#include "TableGen/TGLexer.h"
Public Types
typedef std::set< std::string > DependenciesSetTy
Public Member Functions
TGLexer (SourceMgr &SrcMgr, ArrayRef< std::string > Macros)
tgtok::TokKind Lex ()
const DependenciesSetTy & getDependencies () const
tgtok::TokKind getCode () const
const std::string & getCurStrVal () const
int64_t getCurIntVal () const
std::pair< int64_t, unsigned > getCurBinaryIntVal () const
SMLoc getLoc () const
SMRange getLocRange () const
Detailed Description
TGLexer - TableGen Lexer class.
Definition at line 81 of file TGLexer.h.
Member Typedef Documentation
DependenciesSetTy
typedef std::set<std::string> llvm::TGLexer::DependenciesSetTy
Definition at line 98 of file TGLexer.h.
Constructor & Destructor Documentation
TGLexer()
TGLexer::TGLexer (SourceMgr & SrcMgr, ArrayRef< std::string > Macros)
Definition at line 47 of file TGLexer.cpp.
References llvm::StringRef::begin(), llvm::MemoryBuffer::getBuffer(), llvm::SourceMgr::getMainFileID(), llvm::SourceMgr::getMemoryBuffer(), and llvm::StringSet< AllocatorTy >::insert().
Member Function Documentation
getCode()
tgtok::TokKind llvm::TGLexer::getCode () const inline
Definition at line 115 of file TGLexer.h.
Referenced by llvm::TGParser::ParseFile().
getCurBinaryIntVal()
std::pair<int64_t, unsigned> llvm::TGLexer::getCurBinaryIntVal () const inline
Definition at line 127 of file TGLexer.h.
References assert(), and llvm::tgtok::BinaryIntVal.
getCurIntVal()
int64_t llvm::TGLexer::getCurIntVal () const inline
Definition at line 123 of file TGLexer.h.
References assert(), and llvm::tgtok::IntVal.
getCurStrVal()
const std::string& llvm::TGLexer::getCurStrVal () const inline
Definition at line 117 of file TGLexer.h.
References assert(), llvm::tgtok::CodeFragment, llvm::tgtok::Id, llvm::tgtok::StrVal, and llvm::tgtok::VarName.
getDependencies()
const DependenciesSetTy& llvm::TGLexer::getDependencies () const inline
Definition at line 111 of file TGLexer.h.
Referenced by llvm::TGParser::getDependencies().
getLoc()
SMLoc TGLexer::getLoc () const
Definition at line 62 of file TGLexer.cpp.
References llvm::SMLoc::getFromPointer().
Referenced by getLocRange(), and llvm::TGParser::TokError().
getLocRange()
SMRange TGLexer::getLocRange () const
Definition at line 66 of file TGLexer.cpp.
References llvm::SMLoc::getFromPointer(), and getLoc().
Lex()
tgtok::TokKind llvm::TGLexer::Lex () inline
Definition at line 107 of file TGLexer.h.
References llvm::StringRef::begin().
Referenced by llvm::TGParser::ParseFile().
The documentation for this class was generated from the following files:
lib/TableGen/TGLexer.h
lib/TableGen/TGLexer.cpp