LLVM: llvm::PrintFunctionPass Class Reference
llvm::PrintFunctionPass Class Reference
Pass (for the new pass manager) for printing a Function as LLVM's text IR assembly.
#include "llvm/IRPrinter/IRPrintingPasses.h"
Public Member Functions
PrintFunctionPass ()
PrintFunctionPass (raw_ostream &OS, const std::string &Banner="")
PreservedAnalyses run (Function &F, AnalysisManager< Function > &)
Public Member Functions inherited from llvm::PassInfoMixin< PrintFunctionPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< PrintFunctionPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass (for the new pass manager) for printing a Function as LLVM's text IR assembly.
Definition at line 50 of file IRPrintingPasses.h.
Constructor & Destructor Documentation
PrintFunctionPass() [1/2]
PrintFunctionPass::PrintFunctionPass ()
Definition at line 63 of file IRPrintingPasses.cpp.
PrintFunctionPass() [2/2]
PrintFunctionPass::PrintFunctionPass (raw_ostream & OS, const std::string & Banner = "")
Definition at line 64 of file IRPrintingPasses.cpp.
Member Function Documentation
isRequired()
static bool llvm::PrintFunctionPass::isRequired () inline static
Definition at line 59 of file IRPrintingPasses.h.
run()
PreservedAnalyses PrintFunctionPass::run (Function & F, AnalysisManager< Function > &)
Definition at line 67 of file IRPrintingPasses.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::forcePrintModuleIR(), and llvm::isFunctionInPrintList().
The documentation for this class was generated from the following files:
include/llvm/IRPrinter/IRPrintingPasses.h
lib/IRPrinter/IRPrintingPasses.cpp