LLVM: llvm::VPValue Class Reference
llvm::VPValue Class Reference
#include "Transforms/Vectorize/VPlanValue.h"
Public Types
enum { VPValueSC, VPVRecipeSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Public Member Functions
Value * getUnderlyingValue ()
Return the underlying Value attached to this VPValue.
const Value * getUnderlyingValue () const
VPValue (Value *UV=nullptr)
Create a live-in VPValue.
VPValue (VPDef *Def, Value *UV=nullptr)
Create a VPValue for a Def which is a subclass of VPValue.
VPValue (Value *UV, VPDef *Def)
Create a VPValue for a Def which defines multiple values.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser ()
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
Value * getLiveInIRValue ()
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
const Value * getLiveInIRValue () const
bool isDefinedOutsideVectorRegions () const
Returns true if the VPValue is defined outside any vector regions, i.e.
Protected Member Functions
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
void setUnderlyingValue (Value *Val)
Protected Attributes
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Friends
class VPBuilder
class VPDef
class VPInstruction
struct VPlanTransforms
class VPBasicBlock
class VPInterleavedAccessInfo
class VPSlotTracker
class VPRecipeBase
class VPWidenMemoryInstructionRecipe
Detailed Description
Definition at line 44 of file VPlanValue.h.
Member Typedef Documentation
const_user_iterator
typedef SmallVectorImpl<VPUser *>::const_iterator llvm::VPValue::const_user_iterator
Definition at line 139 of file VPlanValue.h.
const_user_range
typedef iterator_range<const_user_iterator> llvm::VPValue::const_user_range
Definition at line 141 of file VPlanValue.h.
user_iterator
typedef SmallVectorImpl<VPUser *>::iterator llvm::VPValue::user_iterator
Definition at line 138 of file VPlanValue.h.
user_range
typedef iterator_range<user_iterator> llvm::VPValue::user_range
Definition at line 140 of file VPlanValue.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
Enumerator
VPValueSC
VPVRecipeSC
A generic VPValue, like live-in values or defined by a recipe that defines multiple values.
A VPValue sub-class that is a VPRecipeBase.
Definition at line 89 of file VPlanValue.h.
Constructor & Destructor Documentation
VPValue() [1/5]
VPValue::VPValue (const unsigned char SC, Value * UV = nullptr, VPDef * Def = nullptr) protected
Definition at line 79 of file VPlan.cpp.
References Def.
VPValue() [2/5]
llvm::VPValue::VPValue (Value * UV = nullptr) inline
Create a live-in VPValue.
Definition at line 96 of file VPlanValue.h.
VPValue() [3/5]
llvm::VPValue::VPValue (VPDef * Def, Value * UV = nullptr) inline
Create a VPValue for a Def which is a subclass of VPValue.
Definition at line 98 of file VPlanValue.h.
VPValue() [4/5]
llvm::VPValue::VPValue (Value * UV, VPDef * Def) inline
Create a VPValue for a Def which defines multiple values.
Definition at line 100 of file VPlanValue.h.
VPValue() [5/5]
llvm::VPValue::VPValue (const VPValue &) delete
~VPValue()
VPValue::~VPValue () virtual
Definition at line 85 of file VPlan.cpp.
References assert(), and Def.
Member Function Documentation
addUser()
void llvm::VPValue::addUser (VPUser & User) inline
Definition at line 120 of file VPlanValue.h.
References Users.
Referenced by llvm::VPUser::addOperand().
dump()
void VPValue::dump () const
Dump the value to stderr (for debugging).
Definition at line 99 of file VPlan.cpp.
References llvm::dbgs(), Def, llvm::VPRecipeBase::getParent(), llvm::VPBlockBase::getPlan(), and print().
getDefiningRecipe() [1/2]
const VPRecipeBase * VPValue::getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
is a live-in.
Definition at line 116 of file VPlan.cpp.
References Def.
Referenced by llvm::VPHeaderPHIRecipe::classof(), llvm::VPHeaderPHIRecipe::getBackedgeRecipe(), llvm::VPWidenCanonicalIVRecipe::getScalarType(), hasDefiningRecipe(), llvm::vputils::isUniformAfterVectorization(), and llvm::VPlanTransforms::optimizeInductions().
getDefiningRecipe() [2/2]
const VPRecipeBase* llvm::VPValue::getDefiningRecipe () const
getLiveInIRValue() [1/2]
Value* llvm::VPValue::getLiveInIRValue () inline
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
Returns nullptr if the VPValue is defined by a VPDef inside a VPlan.
Definition at line 177 of file VPlanValue.h.
References assert(), getUnderlyingValue(), and hasDefiningRecipe().
Referenced by llvm::VPFirstOrderRecurrencePHIRecipe::execute(), llvm::VPReductionPHIRecipe::execute(), llvm::VPCanonicalIVPHIRecipe::execute(), llvm::InnerLoopVectorizer::fixFixedOrderRecurrence(), llvm::VPCanonicalIVPHIRecipe::getScalarType(), llvm::VPWidenIntOrFpInductionRecipe::isCanonical(), llvm::VPCanonicalIVPHIRecipe::isCanonical(), and llvm::VPlanTransforms::optimizeForVFAndUF().
getLiveInIRValue() [2/2]
const Value* llvm::VPValue::getLiveInIRValue () const inline
Definition at line 182 of file VPlanValue.h.
References assert(), getUnderlyingValue(), and hasDefiningRecipe().
getNumUsers()
unsigned llvm::VPValue::getNumUsers () const inline
Definition at line 119 of file VPlanValue.h.
References Users.
Referenced by hasMoreThanOneUniqueUser().
getUnderlyingValue() [1/2]
Value* llvm::VPValue::getUnderlyingValue () inline
Return the underlying Value attached to this VPValue.
Definition at line 84 of file VPlanValue.h.
References UnderlyingVal.
Referenced by llvm::VPWidenRecipe::execute(), llvm::VPReductionPHIRecipe::execute(), llvm::VPPredInstPHIRecipe::execute(), llvm::InnerLoopVectorizer::fixFixedOrderRecurrence(), llvm::InnerLoopVectorizer::fixReduction(), getLiveInIRValue(), llvm::VPWidenIntOrFpInductionRecipe::getTruncInst(), llvm::VPWidenPHIRecipe::print(), and llvm::VPlanTransforms::VPInstructionsToVPRecipes().
getUnderlyingValue() [2/2]
const Value* llvm::VPValue::getUnderlyingValue () const inline
Definition at line 85 of file VPlanValue.h.
References UnderlyingVal.
getVPValueID()
unsigned llvm::VPValue::getVPValueID () const inline
Returns
an ID for the concrete type of this object. This is used to implement the classof checks. This should not be used for any other purpose, as the values may change as LLVM evolves.
Definition at line 109 of file VPlanValue.h.
hasDefiningRecipe()
bool llvm::VPValue::hasDefiningRecipe () const inline
Returns true if this VPValue is defined by a recipe.
Definition at line 172 of file VPlanValue.h.
References getDefiningRecipe().
Referenced by getLiveInIRValue(), and isDefinedOutsideVectorRegions().
hasMoreThanOneUniqueUser()
bool llvm::VPValue::hasMoreThanOneUniqueUser () inline
Returns true if the value has more than one unique user.
Definition at line 153 of file VPlanValue.h.
References getNumUsers(), user_begin(), and user_end().
isDefinedOutsideVectorRegions()
bool llvm::VPValue::isDefinedOutsideVectorRegions () const inline
Returns true if the VPValue is defined outside any vector regions, i.e.
it is a live-in value. TODO: Also handle recipes defined in pre-header blocks.
Definition at line 191 of file VPlanValue.h.
References hasDefiningRecipe().
Referenced by llvm::vputils::isUniformAfterVectorization().
operator=()
VPValue& llvm::VPValue::operator= (const VPValue &) delete
print()
void VPValue::print (raw_ostream & OS, VPSlotTracker & Tracker) const
Definition at line 92 of file VPlan.cpp.
References Def, OS, and printAsOperand().
Referenced by dump(), llvm::VPlanPrinter::dump(), and llvm::operator<<().
printAsOperand()
void VPValue::printAsOperand (raw_ostream & OS, VPSlotTracker & Tracker) const
Definition at line 1017 of file VPlan.cpp.
References llvm::VPSlotTracker::getSlot(), and OS.
Referenced by print(), llvm::VPInstruction::print(), llvm::VPWidenRecipe::print(), llvm::VPWidenCallRecipe::print(), llvm::VPWidenSelectRecipe::print(), llvm::VPWidenGEPRecipe::print(), llvm::VPWidenIntOrFpInductionRecipe::print(), llvm::VPWidenPointerInductionRecipe::print(), llvm::VPWidenPHIRecipe::print(), llvm::VPFirstOrderRecurrencePHIRecipe::print(), llvm::VPReductionPHIRecipe::print(), llvm::VPBlendRecipe::print(), llvm::VPReductionRecipe::print(), llvm::VPReplicateRecipe::print(), llvm::VPPredInstPHIRecipe::print(), llvm::VPWidenMemoryInstructionRecipe::print(), llvm::VPExpandSCEVRecipe::print(), llvm::VPCanonicalIVPHIRecipe::print(), llvm::VPActiveLaneMaskPHIRecipe::print(), llvm::VPWidenCanonicalIVRecipe::print(), llvm::VPDerivedIVRecipe::print(), and llvm::VPScalarIVStepsRecipe::print().
removeUser()
void llvm::VPValue::removeUser (VPUser & User) inline
Remove a single User from the list of users.
Definition at line 123 of file VPlanValue.h.
References llvm::erase_if(), Other, and Users.
replaceAllUsesWith()
void VPValue::replaceAllUsesWith (VPValue * New)
Definition at line 1001 of file VPlan.cpp.
References E, llvm::User::getNumOperands(), llvm::User::getOperand(), I, llvm::User::setOperand(), and Users.
Referenced by llvm::VPlanTransforms::removeRedundantCanonicalIVs(), llvm::VPlanTransforms::removeRedundantInductionCasts(), and llvm::VPlanTransforms::VPInstructionsToVPRecipes().
setUnderlyingValue()
void llvm::VPValue::setUnderlyingValue (Value * Val) inline protected
Definition at line 77 of file VPlanValue.h.
References assert(), and UnderlyingVal.
Referenced by llvm::VPBuilder::createNaryOp(), and llvm::VPInstruction::setUnderlyingInstr().
user_begin() [1/2]
user_iterator llvm::VPValue::user_begin () inline
Definition at line 143 of file VPlanValue.h.
References Users.
Referenced by llvm::VPlanSlp::buildGraph(), hasMoreThanOneUniqueUser(), and users().
user_begin() [2/2]
const_user_iterator llvm::VPValue::user_begin () const inline
Definition at line 144 of file VPlanValue.h.
References Users.
user_end() [1/2]
user_iterator llvm::VPValue::user_end () inline
Definition at line 145 of file VPlanValue.h.
References Users.
Referenced by llvm::VPlanSlp::buildGraph(), hasMoreThanOneUniqueUser(), and users().
user_end() [2/2]
const_user_iterator llvm::VPValue::user_end () const inline
Definition at line 146 of file VPlanValue.h.
References Users.
users() [1/2]
user_range llvm::VPValue::users () inline
Definition at line 147 of file VPlanValue.h.
References user_begin(), and user_end().
Referenced by llvm::InnerLoopVectorizer::clearReductionWrapFlags(), llvm::VPlanTransforms::mergeReplicateRegionsIntoSuccessors(), llvm::VPBlendRecipe::onlyFirstLaneUsed(), llvm::VPlanTransforms::removeRedundantCanonicalIVs(), llvm::VPlanTransforms::removeRedundantInductionCasts(), sinkRecurrenceUsersAfterPrevious(), and llvm::VPlanTransforms::sinkScalarOperands().
users() [2/2]
const_user_range llvm::VPValue::users () const inline
Definition at line 148 of file VPlanValue.h.
References user_begin(), and user_end().
Friends And Related Function Documentation
VPBasicBlock
friend class VPBasicBlock friend
Definition at line 49 of file VPlanValue.h.
VPBuilder
friend class VPBuilder friend
Definition at line 45 of file VPlanValue.h.
VPDef
friend class VPDef friend
Definition at line 46 of file VPlanValue.h.
VPInstruction
friend class VPInstruction friend
Definition at line 47 of file VPlanValue.h.
Referenced by llvm::VPInstruction::clone().
VPInterleavedAccessInfo
friend class VPInterleavedAccessInfo friend
Definition at line 50 of file VPlanValue.h.
VPlanTransforms
friend struct VPlanTransforms friend
Definition at line 48 of file VPlanValue.h.
VPRecipeBase
friend class VPRecipeBase friend
Definition at line 52 of file VPlanValue.h.
VPSlotTracker
friend class VPSlotTracker friend
Definition at line 51 of file VPlanValue.h.
VPWidenMemoryInstructionRecipe
friend class VPWidenMemoryInstructionRecipe friend
Definition at line 53 of file VPlanValue.h.
Member Data Documentation
Def
VPDef* llvm::VPValue::Def protected
Pointer to the VPDef that defines this VPValue.
If it is nullptr, the VPValue is not defined by any recipe modeled in VPlan.
Definition at line 65 of file VPlanValue.h.
Referenced by dump(), getDefiningRecipe(), print(), VPValue(), and ~VPValue().
UnderlyingVal
Value* llvm::VPValue::UnderlyingVal protected
Definition at line 61 of file VPlanValue.h.
Referenced by getUnderlyingValue(), and setUnderlyingValue().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanValue.h
lib/Transforms/Vectorize/VPlan.cpp