LLVM: llvm::PPCSubtarget Class Reference
llvm::PPCSubtarget Class Reference
#include "Target/PowerPC/PPCSubtarget.h"
Public Types
enum POPCNTDKind { POPCNTD_Unavailable, POPCNTD_Slow, POPCNTD_Fast }
Public Member Functions
PPCSubtarget (const Triple &TT, const std::string &CPU, const std::string &TuneCPU, const std::string &FS, const PPCTargetMachine &TM)
This constructor initializes the data members to match that of the specified triple.
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Align getStackAlignment () const
getStackAlignment - Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
unsigned getCPUDirective () const
getCPUDirective - Returns the -m directive specified for the cpu.
const InstrItineraryData * getInstrItineraryData () const override
getInstrItins - Return the instruction itineraries based on subtarget selection.
const PPCFrameLowering * getFrameLowering () const override
const PPCInstrInfo * getInstrInfo () const override
const PPCTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
const PPCRegisterInfo * getRegisterInfo () const override
const PPCTargetMachine & getTargetMachine () const
PPCSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef TuneCPU, StringRef FS)
initializeSubtargetDependencies - Initializes using a CPU, a TuneCPU, and feature string so that we can use initializer lists for subtarget initialization.
bool isPPC64 () const
isPPC64 - Return true if we are generating code for 64-bit pointer mode.
bool useSoftFloat () const
bool isLittleEndian () const
Align getPlatformStackAlignment () const
unsigned getRedZoneSize () const
bool needsSwapsForVSXMemOps () const
POPCNTDKind hasPOPCNTD () const
const Triple & getTargetTriple () const
bool isTargetELF () const
bool isTargetMachO () const
bool isTargetLinux () const
bool isAIXABI () const
bool isSVR4ABI () const
bool isELFv2ABI () const
bool is64BitELFABI () const
bool is32BitELFABI () const
bool isUsingPCRelativeCalls () const
bool enableEarlyIfConversion () const override
Originally, this function return hasISEL().
bool enableMachineScheduler () const override
Scheduling customization.
bool enableMachinePipeliner () const override
Pipeliner customization.
bool useDFAforSMS () const override
Machine Pipeliner customization.
bool enablePostRAScheduler () const override
This overrides the PostRAScheduler bit in the SchedModel for each CPU.
AntiDepBreakMode getAntiDepBreakMode () const override
void getCriticalPathRCs (RegClassVector &CriticalPathRCs) const override
void overrideSchedPolicy (MachineSchedPolicy &Policy, unsigned NumRegionInstrs) const override
bool useAA () const override
bool enableSubRegLiveness () const override
bool enableSpillageCopyElimination () const override
bool isGVIndirectSymbol (const GlobalValue *GV) const
True if the GV will be accessed via an indirect symbol.
bool usesFunctionDescriptors () const
True if the ABI is descriptor based.
unsigned descriptorTOCAnchorOffset () const
unsigned descriptorEnvironmentPointerOffset () const
MCRegister getEnvironmentPointerRegister () const
MCRegister getTOCPointerRegister () const
MCRegister getStackPointerRegister () const
bool isXRaySupported () const override
bool isPredictableSelectIsExpensive () const
unsigned getGPRAllocationOrderIdx () const
const CallLowering * getCallLowering () const override
const RegisterBankInfo * getRegBankInfo () const override
const LegalizerInfo * getLegalizerInfo () const override
InstructionSelector * getInstructionSelector () const override
Protected Attributes
Triple TargetTriple
TargetTriple - What processor and OS we're targeting.
Align StackAlignment
stackAlignment - The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
InstrItineraryData InstrItins
Selected instruction itineraries (one entry per itinerary class.)
unsigned CPUDirective
Which cpu directive was used.
bool IsPPC64
bool IsLittleEndian
POPCNTDKind HasPOPCNTD
const PPCTargetMachine & TM
PPCFrameLowering FrameLowering
PPCInstrInfo InstrInfo
PPCTargetLowering TLInfo
SelectionDAGTargetInfo TSInfo
std::unique_ptr< CallLowering > CallLoweringInfo
GlobalISel related APIs.
std::unique_ptr< LegalizerInfo > Legalizer
std::unique_ptr< RegisterBankInfo > RegBankInfo
std::unique_ptr< InstructionSelector > InstSelector
Detailed Description
Definition at line 71 of file PPCSubtarget.h.
Member Enumeration Documentation
POPCNTDKind
enum llvm::PPCSubtarget::POPCNTDKind
Enumerator
POPCNTD_Unavailable
POPCNTD_Slow
POPCNTD_Fast
Definition at line 73 of file PPCSubtarget.h.
Constructor & Destructor Documentation
PPCSubtarget()
PPCSubtarget::PPCSubtarget (const Triple & TT, const std::string & CPU, const std::string & TuneCPU, const std::string & FS, const PPCTargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 58 of file PPCSubtarget.cpp.
References CallLoweringInfo, llvm::createPPCInstructionSelector(), getRegisterInfo(), getTargetLowering(), InstSelector, RegBankInfo, and TM.
Member Function Documentation
descriptorEnvironmentPointerOffset()
unsigned llvm::PPCSubtarget::descriptorEnvironmentPointerOffset () const inline
Definition at line 261 of file PPCSubtarget.h.
References assert(), IsPPC64, and usesFunctionDescriptors().
Referenced by prepareDescriptorIndirectCall().
descriptorTOCAnchorOffset()
unsigned llvm::PPCSubtarget::descriptorTOCAnchorOffset () const inline
Definition at line 255 of file PPCSubtarget.h.
References assert(), IsPPC64, and usesFunctionDescriptors().
Referenced by prepareDescriptorIndirectCall().
enableEarlyIfConversion()
bool llvm::PPCSubtarget::enableEarlyIfConversion () const inline override
Originally, this function return hasISEL().
Now we always enable it, but may expand the ISEL instruction later.
Definition at line 224 of file PPCSubtarget.h.
enableMachinePipeliner()
bool PPCSubtarget::enableMachinePipeliner () const override
Pipeliner customization.
Definition at line 132 of file PPCSubtarget.cpp.
References EnableMachinePipeliner.
enableMachineScheduler()
bool PPCSubtarget::enableMachineScheduler () const override
Scheduling customization.
Definition at line 130 of file PPCSubtarget.cpp.
Referenced by llvm::PPCTargetLowering::getSchedulingPreference(), and llvm::PPCTargetLowering::PPCTargetLowering().
enablePostRAScheduler()
bool PPCSubtarget::enablePostRAScheduler () const override
This overrides the PostRAScheduler bit in the SchedModel for each CPU.
Definition at line 139 of file PPCSubtarget.cpp.
enableSpillageCopyElimination()
bool llvm::PPCSubtarget::enableSpillageCopyElimination () const inline override
Definition at line 243 of file PPCSubtarget.h.
enableSubRegLiveness()
bool PPCSubtarget::enableSubRegLiveness () const override
Definition at line 168 of file PPCSubtarget.cpp.
References UseSubRegLiveness.
getAntiDepBreakMode()
PPCGenSubtargetInfo::AntiDepBreakMode PPCSubtarget::getAntiDepBreakMode () const override
Definition at line 141 of file PPCSubtarget.cpp.
getCallLowering()
const CallLowering * PPCSubtarget::getCallLowering () const override
Definition at line 190 of file PPCSubtarget.cpp.
References CallLoweringInfo.
getCPUDirective()
unsigned llvm::PPCSubtarget::getCPUDirective () const inline
getCPUDirective - Returns the -m directive specified for the cpu.
Definition at line 134 of file PPCSubtarget.h.
References CPUDirective.
Referenced by llvm::PPCTTIImpl::enableAggressiveInterleaving(), llvm::PPCTTIImpl::getCacheLineSize(), llvm::PPCTTIImpl::getMaxInterleaveFactor(), llvm::PPCInstrInfo::getOperandLatency(), llvm::PPCTargetLowering::getPrefLoopAlignment(), llvm::PPCTTIImpl::getUnrollingPreferences(), llvm::PPCTTIImpl::getVPMemoryOpCost(), llvm::PPCInstrInfo::insertNoop(), and llvm::PPCTargetLowering::PPCTargetLowering().
getCriticalPathRCs()
void PPCSubtarget::getCriticalPathRCs (RegClassVector & CriticalPathRCs) const override
Definition at line 145 of file PPCSubtarget.cpp.
References isPPC64().
getEnvironmentPointerRegister()
MCRegister llvm::PPCSubtarget::getEnvironmentPointerRegister () const inline
Definition at line 267 of file PPCSubtarget.h.
References assert(), IsPPC64, and usesFunctionDescriptors().
Referenced by buildCallOperands(), and prepareDescriptorIndirectCall().
getFrameLowering()
const PPCFrameLowering* llvm::PPCSubtarget::getFrameLowering () const inline override
Definition at line 142 of file PPCSubtarget.h.
References FrameLowering.
Referenced by buildCallOperands(), EmitTailCallStoreFPAndRetAddr(), llvm::PPCTargetLowering::getStackProbeSize(), llvm::PPCInstrInfo::isTOCSaveMI(), and needStackSlotPassParameters().
getGPRAllocationOrderIdx()
unsigned llvm::PPCSubtarget::getGPRAllocationOrderIdx () const inline
Definition at line 291 of file PPCSubtarget.h.
References is64BitELFABI(), and isAIXABI().
getInstrInfo()
const PPCInstrInfo* llvm::PPCSubtarget::getInstrInfo () const inline override
Definition at line 145 of file PPCSubtarget.h.
References InstrInfo.
Referenced by llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCTargetLowering::getPrefLoopAlignment(), getRegisterInfo(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCRegisterInfo::lowerACCRestore(), llvm::PPCRegisterInfo::lowerACCSpilling(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), llvm::PPCRegisterInfo::lowerOctWordSpilling(), llvm::PPCRegisterInfo::lowerPrepareProbedAlloca(), llvm::PPCRegisterInfo::lowerQuadwordRestore(), llvm::PPCRegisterInfo::lowerQuadwordSpilling(), llvm::PPCRegisterInfo::lowerWACCRestore(), llvm::PPCRegisterInfo::lowerWACCSpilling(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::PPCRegisterInfo::requiresFrameIndexScavenging(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
getInstrItineraryData()
const InstrItineraryData* llvm::PPCSubtarget::getInstrItineraryData () const inline override
getInstrItins - Return the instruction itineraries based on subtarget selection.
Definition at line 138 of file PPCSubtarget.h.
References InstrItins.
getInstructionSelector()
InstructionSelector * PPCSubtarget::getInstructionSelector () const override
Definition at line 202 of file PPCSubtarget.cpp.
References InstSelector.
getLegalizerInfo()
const LegalizerInfo * PPCSubtarget::getLegalizerInfo () const override
Definition at line 198 of file PPCSubtarget.cpp.
getPlatformStackAlignment()
Align llvm::PPCSubtarget::getPlatformStackAlignment () const inline
Definition at line 188 of file PPCSubtarget.h.
References Align.
getRedZoneSize()
unsigned llvm::PPCSubtarget::getRedZoneSize () const inline
Definition at line 192 of file PPCSubtarget.h.
References isAIXABI(), and isPPC64().
Referenced by llvm::PPCFrameLowering::determineFrameLayout(), and llvm::PPCFrameLowering::inlineStackProbe().
getRegBankInfo()
const RegisterBankInfo * PPCSubtarget::getRegBankInfo () const override
Definition at line 194 of file PPCSubtarget.cpp.
References RegBankInfo.
getRegisterInfo()
const PPCRegisterInfo* llvm::PPCSubtarget::getRegisterInfo () const inline override
Definition at line 152 of file PPCSubtarget.h.
References getInstrInfo(), and llvm::PPCInstrInfo::getRegisterInfo().
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::PPCFrameLowering::assignCalleeSavedSpillSlots(), buildCallOperands(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), PPCSubtarget(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::PPCFrameLowering::replaceFPWithRealFP().
getSelectionDAGInfo()
const SelectionDAGTargetInfo* llvm::PPCSubtarget::getSelectionDAGInfo () const inline override
Definition at line 149 of file PPCSubtarget.h.
References TSInfo.
getStackAlignment()
Align llvm::PPCSubtarget::getStackAlignment () const inline
getStackAlignment - Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
Definition at line 130 of file PPCSubtarget.h.
References StackAlignment.
getStackPointerRegister()
MCRegister llvm::PPCSubtarget::getStackPointerRegister () const inline
Definition at line 279 of file PPCSubtarget.h.
References IsPPC64.
Referenced by buildCallOperands(), and llvm::PPCRegisterInfo::isCallerPreservedPhysReg().
getTargetLowering()
const PPCTargetLowering* llvm::PPCSubtarget::getTargetLowering () const inline override
Definition at line 146 of file PPCSubtarget.h.
References TLInfo.
Referenced by llvm::PPCFrameLowering::emitPrologue(), llvm::PPCFrameLowering::inlineStackProbe(), and PPCSubtarget().
getTargetMachine()
const PPCTargetMachine& llvm::PPCSubtarget::getTargetMachine () const inline
Definition at line 155 of file PPCSubtarget.h.
References TM.
Referenced by computeBasePointerSaveOffset(), llvm::PPCInstrInfo::getMachineCombinerPatterns(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), isUsingPCRelativeCalls(), llvm::PPCTTIImpl::shouldBuildRelLookupTables(), llvm::PPCInstrInfo::shouldReduceRegisterPressure(), llvm::PPCTTIImpl::supportsTailCallFor(), and transformCallee().
getTargetTriple()
const Triple& llvm::PPCSubtarget::getTargetTriple () const inline
Definition at line 208 of file PPCSubtarget.h.
References TargetTriple.
Referenced by llvm::PPCTargetLowering::shouldInlineQuadwordAtomics().
getTOCPointerRegister()
MCRegister llvm::PPCSubtarget::getTOCPointerRegister () const inline
Definition at line 273 of file PPCSubtarget.h.
References assert(), is64BitELFABI(), isAIXABI(), IsPPC64, and R2.
Referenced by buildCallOperands(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), and prepareDescriptorIndirectCall().
hasPOPCNTD()
POPCNTDKind llvm::PPCSubtarget::hasPOPCNTD () const inline
Definition at line 206 of file PPCSubtarget.h.
References HasPOPCNTD.
Referenced by llvm::PPCTTIImpl::getPopcntSupport(), and llvm::PPCTargetLowering::PPCTargetLowering().
initializeSubtargetDependencies()
PPCSubtarget & PPCSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef TuneCPU, StringRef FS)
initializeSubtargetDependencies - Initializes using a CPU, a TuneCPU, and feature string so that we can use initializer lists for subtarget initialization.
Definition at line 50 of file PPCSubtarget.cpp.
References llvm::X86AS::FS.
is32BitELFABI()
bool llvm::PPCSubtarget::is32BitELFABI () const inline
Definition at line 219 of file PPCSubtarget.h.
References isPPC64(), and isSVR4ABI().
Referenced by buildCallOperands(), computeBasePointerSaveOffset(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCTargetLowering::isAccessedAsGotIndirect(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), and transformCallee().
is64BitELFABI()
bool llvm::PPCSubtarget::is64BitELFABI () const inline
Definition at line 218 of file PPCSubtarget.h.
References isPPC64(), and isSVR4ABI().
Referenced by buildCallOperands(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), getCallOpcode(), getGPRAllocationOrderIdx(), getTOCPointerRegister(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), isTOCSaveRestoreRequired(), needStackSlotPassParameters(), llvm::PPCTargetLowering::PPCTargetLowering(), and usesFunctionDescriptors().
isAIXABI()
bool llvm::PPCSubtarget::isAIXABI () const inline
Definition at line 214 of file PPCSubtarget.h.
References llvm::Triple::isOSAIX(), and TargetTriple.
Referenced by buildCallOperands(), computeCRSaveOffset(), computeLinkageSize(), computeReturnSaveOffset(), computeTOCSaveOffset(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), getCallOpcode(), llvm::PPCRegisterInfo::getCallPreservedMask(), getGPRAllocationOrderIdx(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), getRedZoneSize(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCRegisterInfo::getRegPressureLimit(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCTargetLowering::getSDagStackGuard(), getTOCPointerRegister(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCTargetLowering::insertSSPDeclarations(), llvm::PPCTargetLowering::isAccessedAsGotIndirect(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), llvm::PPCTargetLowering::isJumpTableRelative(), isSVR4ABI(), isTOCSaveRestoreRequired(), prepareDescriptorIndirectCall(), transformCallee(), usesFunctionDescriptors(), and useSoftFloat().
isELFv2ABI()
bool PPCSubtarget::isELFv2ABI () const
Definition at line 181 of file PPCSubtarget.cpp.
References llvm::PPCTargetMachine::isELFv2ABI(), and TM.
Referenced by computeLinkageSize(), computeTOCSaveOffset(), llvm::PPCFrameLowering::emitPrologue(), GetInitialOffset(), isIndirectCall(), isUsingPCRelativeCalls(), transformCallee(), and usesFunctionDescriptors().
isGVIndirectSymbol()
bool PPCSubtarget::isGVIndirectSymbol (const GlobalValue * GV) const
True if the GV will be accessed via an indirect symbol.
Definition at line 172 of file PPCSubtarget.cpp.
References llvm::TargetMachine::getCodeModel(), llvm::GlobalValue::getParent(), llvm::CodeModel::Large, llvm::TargetMachine::shouldAssumeDSOLocal(), and TM.
Referenced by llvm::PPCTargetLowering::isAccessedAsGotIndirect().
isLittleEndian()
bool llvm::PPCSubtarget::isLittleEndian () const inline
Definition at line 181 of file PPCSubtarget.h.
References IsLittleEndian.
Referenced by llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), fixupShuffleMaskForPermutedSToV(), getSToVPermuted(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::PPCRegisterInfo::lowerACCRestore(), llvm::PPCRegisterInfo::lowerACCSpilling(), llvm::PPCRegisterInfo::lowerOctWordSpilling(), llvm::PPCRegisterInfo::lowerQuadwordRestore(), llvm::PPCRegisterInfo::lowerQuadwordSpilling(), llvm::PPCRegisterInfo::lowerWACCRestore(), llvm::PPCRegisterInfo::lowerWACCSpilling(), needsSwapsForVSXMemOps(), and llvm::PPCTargetLowering::PerformDAGCombine().
isPPC64()
bool PPCSubtarget::isPPC64 () const
isPPC64 - Return true if we are generating code for 64-bit pointer mode.
Definition at line 182 of file PPCSubtarget.cpp.
References llvm::PPCTargetMachine::isPPC64(), and TM.
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::PPCInstrInfo::analyzeBranch(), buildCallOperands(), llvm::PPCTargetLowering::BuildSDIVPow2(), CC_AIX(), combineADDToADDZE(), computeBasePointerSaveOffset(), computeCRSaveOffset(), computeFramePointerSaveOffset(), computeLinkageSize(), computeReturnSaveOffset(), computeTOCSaveOffset(), llvm::PPC::createFastISel(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::PPCFrameLowering::emitPrologue(), EmitTailCallStoreFPAndRetAddr(), llvm::PPCTargetLowering::emitTrailingFence(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::findLoopInstr(), llvm::PPCTargetLowering::getByValTypeAlignment(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), getCriticalPathRCs(), llvm::PPCTargetLowering::getExceptionPointerRegister(), llvm::PPCTargetLowering::getExceptionSelectorRegister(), llvm::PPCTTIImpl::getIntImmCostInst(), llvm::PPCTargetLowering::getOptimalMemOpType(), llvm::PPCTargetLowering::getPICJumpTableRelocBase(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), getRedZoneSize(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTTIImpl::getRegisterBitWidth(), llvm::PPCTargetLowering::getRegisterByName(), llvm::PPCTTIImpl::hasActiveVectorLength(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::PPCInstrInfo::insertBranch(), is32BitELFABI(), is64BitELFABI(), llvm::PPCInstrInfo::isBDNZ(), llvm::PPCTargetLowering::isJumpTableRelative(), llvm::PPCInstrInfo::isTOCSaveMI(), isUsingPCRelativeCalls(), llvm::PPCTargetLowering::isZExtFree(), llvm::PPCInstrInfo::materializeImmPostRA(), llvm::PPCInstrInfo::onlyFoldImmediate(), llvm::PPCInstrInfo::optimizeCmpPostRA(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCInstrInfo::PredicateInstruction(), prepareDescriptorIndirectCall(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegRegOnly(), llvm::PPCTargetLowering::SelectForceXFormMode(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), llvm::PPCTargetLowering::shouldInlineQuadwordAtomics(), and llvm::PPCInstrInfo::shouldReduceRegisterPressure().
isPredictableSelectIsExpensive()
bool llvm::PPCSubtarget::isPredictableSelectIsExpensive () const inline
Definition at line 285 of file PPCSubtarget.h.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
isSVR4ABI()
bool llvm::PPCSubtarget::isSVR4ABI () const inline
Definition at line 215 of file PPCSubtarget.h.
References isAIXABI().
Referenced by llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::PPCFrameLowering::inlineStackProbe(), is32BitELFABI(), is64BitELFABI(), llvm::PPCInstrInfo::isSignOrZeroExtended(), and llvm::PPCTargetLowering::ReplaceNodeResults().
isTargetELF()
bool llvm::PPCSubtarget::isTargetELF () const inline
Definition at line 210 of file PPCSubtarget.h.
References llvm::Triple::isOSBinFormatELF(), and TargetTriple.
isTargetLinux()
bool llvm::PPCSubtarget::isTargetLinux () const inline
Definition at line 212 of file PPCSubtarget.h.
References llvm::Triple::isOSLinux(), and TargetTriple.
Referenced by llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::PPCTargetLowering::insertSSPDeclarations(), and llvm::PPCTargetLowering::useLoadStackGuardNode().
isTargetMachO()
bool llvm::PPCSubtarget::isTargetMachO () const inline
Definition at line 211 of file PPCSubtarget.h.
References llvm::Triple::isOSBinFormatMachO(), and TargetTriple.
isUsingPCRelativeCalls()
bool PPCSubtarget::isUsingPCRelativeCalls () const
Definition at line 184 of file PPCSubtarget.cpp.
References llvm::TargetMachine::getCodeModel(), getTargetMachine(), isELFv2ABI(), isPPC64(), and llvm::CodeModel::Medium.
Referenced by buildCallOperands(), callsShareTOCBase(), combineADDToMAT_PCREL_ADDR(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), getCallOpcode(), GetSymbolRef(), isTOCSaveRestoreRequired(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), and llvm::PPCTTIImpl::supportsTailCallFor().
isXRaySupported()
bool llvm::PPCSubtarget::isXRaySupported () const inline override
Definition at line 283 of file PPCSubtarget.h.
References IsLittleEndian, and IsPPC64.
needsSwapsForVSXMemOps()
bool llvm::PPCSubtarget::needsSwapsForVSXMemOps () const inline
Definition at line 202 of file PPCSubtarget.h.
References isLittleEndian().
Referenced by llvm::PPCTargetLowering::PerformDAGCombine(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), and llvm::PPCFrameLowering::spillCalleeSavedRegisters().
overrideSchedPolicy()
void PPCSubtarget::overrideSchedPolicy (MachineSchedPolicy & Policy, unsigned NumRegionInstrs) const override
Definition at line 151 of file PPCSubtarget.cpp.
References llvm::MachineSchedPolicy::OnlyBottomUp, and llvm::MachineSchedPolicy::ShouldTrackPressure.
ParseSubtargetFeatures()
void llvm::PPCSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
useAA()
bool PPCSubtarget::useAA () const override
Definition at line 164 of file PPCSubtarget.cpp.
useDFAforSMS()
bool PPCSubtarget::useDFAforSMS () const override
Machine Pipeliner customization.
Definition at line 136 of file PPCSubtarget.cpp.
usesFunctionDescriptors()
bool llvm::PPCSubtarget::usesFunctionDescriptors () const inline
True if the ABI is descriptor based.
Definition at line 249 of file PPCSubtarget.h.
References is64BitELFABI(), isAIXABI(), and isELFv2ABI().
Referenced by buildCallOperands(), descriptorEnvironmentPointerOffset(), descriptorTOCAnchorOffset(), getEnvironmentPointerRegister(), isIndirectCall(), and transformCallee().
useSoftFloat()
bool llvm::PPCSubtarget::useSoftFloat () const inline
Definition at line 174 of file PPCSubtarget.h.
References isAIXABI(), and llvm::report_fatal_error().
Referenced by llvm::PPCTargetLowering::useSoftFloat().
Member Data Documentation
CallLoweringInfo
std::unique_ptr<CallLowering> llvm::PPCSubtarget::CallLoweringInfo protected
GlobalISel related APIs.
Definition at line 110 of file PPCSubtarget.h.
Referenced by getCallLowering(), and PPCSubtarget().
CPUDirective
unsigned llvm::PPCSubtarget::CPUDirective protected
Which cpu directive was used.
Definition at line 96 of file PPCSubtarget.h.
Referenced by getCPUDirective().
FrameLowering
PPCFrameLowering llvm::PPCSubtarget::FrameLowering protected
Definition at line 104 of file PPCSubtarget.h.
Referenced by getFrameLowering().
HasPOPCNTD
POPCNTDKind llvm::PPCSubtarget::HasPOPCNTD protected
Definition at line 101 of file PPCSubtarget.h.
Referenced by hasPOPCNTD().
InstrInfo
PPCInstrInfo llvm::PPCSubtarget::InstrInfo protected
Definition at line 105 of file PPCSubtarget.h.
Referenced by getInstrInfo().
InstrItins
InstrItineraryData llvm::PPCSubtarget::InstrItins protected
Selected instruction itineraries (one entry per itinerary class.)
Definition at line 88 of file PPCSubtarget.h.
Referenced by getInstrItineraryData().
InstSelector
std::unique_ptr<InstructionSelector> llvm::PPCSubtarget::InstSelector protected
Definition at line 113 of file PPCSubtarget.h.
Referenced by getInstructionSelector(), and PPCSubtarget().
IsLittleEndian
bool llvm::PPCSubtarget::IsLittleEndian protected
Definition at line 99 of file PPCSubtarget.h.
Referenced by isLittleEndian(), and isXRaySupported().
IsPPC64
bool llvm::PPCSubtarget::IsPPC64 protected
Definition at line 98 of file PPCSubtarget.h.
Referenced by descriptorEnvironmentPointerOffset(), descriptorTOCAnchorOffset(), getEnvironmentPointerRegister(), getStackPointerRegister(), getTOCPointerRegister(), and isXRaySupported().
Legalizer
std::unique_ptr<LegalizerInfo> llvm::PPCSubtarget::Legalizer protected
Definition at line 111 of file PPCSubtarget.h.
RegBankInfo
std::unique_ptr<RegisterBankInfo> llvm::PPCSubtarget::RegBankInfo protected
Definition at line 112 of file PPCSubtarget.h.
Referenced by getRegBankInfo(), and PPCSubtarget().
StackAlignment
Align llvm::PPCSubtarget::StackAlignment protected
stackAlignment - The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
Definition at line 85 of file PPCSubtarget.h.
Referenced by getStackAlignment().
TargetTriple
Triple llvm::PPCSubtarget::TargetTriple protected
TargetTriple - What processor and OS we're targeting.
Definition at line 81 of file PPCSubtarget.h.
Referenced by getTargetTriple(), isAIXABI(), isTargetELF(), isTargetLinux(), and isTargetMachO().
TLInfo
PPCTargetLowering llvm::PPCSubtarget::TLInfo protected
Definition at line 106 of file PPCSubtarget.h.
Referenced by getTargetLowering().
TM
const PPCTargetMachine& llvm::PPCSubtarget::TM protected
Definition at line 103 of file PPCSubtarget.h.
Referenced by getTargetMachine(), isELFv2ABI(), isGVIndirectSymbol(), isPPC64(), and PPCSubtarget().
TSInfo
SelectionDAGTargetInfo llvm::PPCSubtarget::TSInfo protected
Definition at line 107 of file PPCSubtarget.h.
Referenced by getSelectionDAGInfo().
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCSubtarget.h
lib/Target/PowerPC/PPCSubtarget.cpp