LLVM: llvm::InstructionSelect Class Reference
llvm::InstructionSelect Class Reference
This pass is responsible for selecting generic machine instructions to target-specific instructions.
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
Public Member Functions
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
MachineFunctionProperties getRequiredProperties () const override
MachineFunctionProperties getSetProperties () const override
InstructionSelect (CodeGenOpt::Level OL)
InstructionSelect ()
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Protected Attributes
BlockFrequencyInfo * BFI = nullptr
ProfileSummaryInfo * PSI = nullptr
CodeGenOpt::Level OptLevel = CodeGenOpt::None
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
This pass is responsible for selecting generic machine instructions to target-specific instructions.
It relies on the InstructionSelector provided by the target. Selection is done by examining blocks in post-order, and instructions in reverse order.
Postcondition
for all inst in MF: not isPreISelGenericOpcode(inst.opcode)
Definition at line 33 of file InstructionSelect.h.
Constructor & Destructor Documentation
InstructionSelect() [1/2]
Select target instructions out of generic false InstructionSelect::InstructionSelect (CodeGenOpt::Level OL)
Definition at line 60 of file InstructionSelect.cpp.
InstructionSelect() [2/2]
InstructionSelect::InstructionSelect ()
Definition at line 66 of file InstructionSelect.cpp.
Member Function Documentation
getAnalysisUsage()
void InstructionSelect::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 69 of file InstructionSelect.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::LazyBlockFrequencyInfoPass::getLazyBFIAnalysisUsage(), llvm::getSelectionDAGFallbackAnalysisUsage(), llvm::CodeGenOpt::None, and OptLevel.
getPassName()
StringRef llvm::InstructionSelect::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 36 of file InstructionSelect.h.
getRequiredProperties()
MachineFunctionProperties llvm::InstructionSelect::getRequiredProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 40 of file InstructionSelect.h.
References llvm::MachineFunctionProperties::IsSSA, llvm::MachineFunctionProperties::Legalized, llvm::MachineFunctionProperties::RegBankSelected, and llvm::MachineFunctionProperties::set().
getSetProperties()
MachineFunctionProperties llvm::InstructionSelect::getSetProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 47 of file InstructionSelect.h.
References llvm::MachineFunctionProperties::Selected, and llvm::MachineFunctionProperties::set().
runOnMachineFunction()
bool InstructionSelect::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 82 of file InstructionSelect.cpp.
References assert(), llvm::MachineBasicBlock::begin(), BFI, llvm::canReplaceReg(), llvm::MachineBasicBlock::clear(), llvm::MachineRegisterInfo::clearVirtRegTypes(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::contains(), CoveragePrefix, llvm::CodeGenCoverage::covered(), llvm::InstructionSelector::CurMBB, llvm::dbgs(), llvm::MachineRegisterInfo::def_empty(), llvm::MachineRegisterInfo::def_instr_begin(), llvm::DisableGISelLegalityCheck, E, llvm::CodeGenCoverage::emit(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineFunctionProperties::FailedISel, llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstructionSelector(), llvm::MachineFunction::getName(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::TargetMachine::getOptLevel(), llvm::MachineFunction::getProperties(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineRegisterInfo::getRegClassOrNull(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineRegisterInfo::getType(), llvm::MachineFrameInfo::hasCalls(), llvm::Function::hasOptNone(), llvm::ProfileSummaryInfo::hasProfileSummary(), llvm::MachineFunctionProperties::hasProperty(), I, llvm::Register::index2VirtReg(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::isPreISelGenericOptimizationHint(), llvm::isTriviallyDead(), llvm::LLT::isValid(), llvm::Register::isVirtual(), LLVM_DEBUG, llvm::machineFunctionIsIllegal(), llvm::make_range(), llvm::make_scope_exit(), MBB, MI, MORE, MRI, llvm::CodeGenOpt::None, OptLevel, llvm::post_order(), PSI, llvm::MachineRegisterInfo::replaceRegWith(), llvm::reportGISelFailure(), llvm::salvageDebugInfo(), llvm::InstructionSelector::select(), llvm::MachineFrameInfo::setHasCalls(), llvm::MachineRegisterInfo::setRegClass(), llvm::InstructionSelector::setupMF(), llvm::MachineFunction::size(), TRI, llvm::MachineRegisterInfo::use_empty(), and llvm::MachineRegisterInfo::use_instr_begin().
Member Data Documentation
BFI
BlockFrequencyInfo* llvm::InstructionSelect::BFI = nullptr protected
Definition at line 58 of file InstructionSelect.h.
Referenced by runOnMachineFunction().
ID
char InstructionSelect::ID = 0 static
Definition at line 35 of file InstructionSelect.h.
OptLevel
CodeGenOpt::Level llvm::InstructionSelect::OptLevel = CodeGenOpt::None protected
Definition at line 61 of file InstructionSelect.h.
Referenced by getAnalysisUsage(), and runOnMachineFunction().
PSI
ProfileSummaryInfo* llvm::InstructionSelect::PSI = nullptr protected
Definition at line 59 of file InstructionSelect.h.
Referenced by runOnMachineFunction().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/InstructionSelect.h
lib/CodeGen/GlobalISel/InstructionSelect.cpp