LLVM: llvm::BitcodeReaderValueList Class Reference
llvm::BitcodeReaderValueList Class Reference
#include "Bitcode/Reader/ValueList.h"
Public Member Functions
BitcodeReaderValueList (size_t RefsUpperBound, MaterializeValueFnTy MaterializeValueFn)
unsigned size () const
void resize (unsigned N)
void push_back (Value *V, unsigned TypeID)
void clear ()
Value * operator[] (unsigned i) const
unsigned getTypeID (unsigned ValNo) const
Value * back () const
void pop_back ()
bool empty () const
void shrinkTo (unsigned N)
void replaceValueWithoutRAUW (unsigned ValNo, Value *NewV)
Value * getValueFwdRef (unsigned Idx, Type *Ty, unsigned TyID, BasicBlock *ConstExprInsertBB)
Error assignValue (unsigned Idx, Value *V, unsigned TypeID)
Detailed Description
Definition at line 28 of file ValueList.h.
Constructor & Destructor Documentation
BitcodeReaderValueList()
llvm::BitcodeReaderValueList::BitcodeReaderValueList (size_t RefsUpperBound, MaterializeValueFnTy MaterializeValueFn) inline
Definition at line 41 of file ValueList.h.
Member Function Documentation
assignValue()
Error BitcodeReaderValueList::assignValue (unsigned Idx, Value * V, unsigned TypeID)
Definition at line 26 of file ValueList.cpp.
References assert(), llvm::createStringError(), llvm::Value::deleteValue(), llvm::Value::getType(), push_back(), resize(), size(), and llvm::Error::success().
back()
Value* llvm::BitcodeReaderValueList::back () const inline
Definition at line 70 of file ValueList.h.
clear()
void llvm::BitcodeReaderValueList::clear () inline
Definition at line 56 of file ValueList.h.
empty()
bool llvm::BitcodeReaderValueList::empty () const inline
Definition at line 74 of file ValueList.h.
getTypeID()
unsigned llvm::BitcodeReaderValueList::getTypeID (unsigned ValNo) const inline
Definition at line 65 of file ValueList.h.
References assert().
getValueFwdRef()
Value * BitcodeReaderValueList::getValueFwdRef (unsigned Idx, Type * Ty, unsigned TyID, BasicBlock * ConstExprInsertBB)
Definition at line 55 of file ValueList.cpp.
References llvm::consumeError(), llvm::Expected< T >::get(), resize(), size(), and llvm::Expected< T >::takeError().
operator[]()
Value* llvm::BitcodeReaderValueList::operator[] (unsigned i) const inline
Definition at line 60 of file ValueList.h.
References assert(), and i.
pop_back()
void llvm::BitcodeReaderValueList::pop_back () inline
Definition at line 71 of file ValueList.h.
push_back()
void llvm::BitcodeReaderValueList::push_back (Value * V, unsigned TypeID) inline
Definition at line 52 of file ValueList.h.
Referenced by assignValue().
replaceValueWithoutRAUW()
void llvm::BitcodeReaderValueList::replaceValueWithoutRAUW (unsigned ValNo, Value * NewV) inline
Definition at line 81 of file ValueList.h.
References assert().
resize()
void llvm::BitcodeReaderValueList::resize (unsigned N) inline
Definition at line 49 of file ValueList.h.
References N.
Referenced by assignValue(), and getValueFwdRef().
shrinkTo()
void llvm::BitcodeReaderValueList::shrinkTo (unsigned N) inline
Definition at line 76 of file ValueList.h.
References assert(), N, and size().
size()
unsigned llvm::BitcodeReaderValueList::size () const inline
Definition at line 48 of file ValueList.h.
Referenced by assignValue(), getValueFwdRef(), and shrinkTo().
The documentation for this class was generated from the following files:
lib/Bitcode/Reader/ValueList.h
lib/Bitcode/Reader/ValueList.cpp