LLVM: llvm::RISCVTargetStreamer Class Reference
llvm::RISCVTargetStreamer Class Reference
#include "Target/RISCV/MCTargetDesc/RISCVTargetStreamer.h"
Public Member Functions
RISCVTargetStreamer (MCStreamer &S)
void finish () override
virtual void reset ()
virtual void emitDirectiveOptionPush ()
virtual void emitDirectiveOptionPop ()
virtual void emitDirectiveOptionPIC ()
virtual void emitDirectiveOptionNoPIC ()
virtual void emitDirectiveOptionRVC ()
virtual void emitDirectiveOptionNoRVC ()
virtual void emitDirectiveOptionRelax ()
virtual void emitDirectiveOptionNoRelax ()
virtual void emitDirectiveVariantCC (MCSymbol &Symbol)
virtual void emitAttribute (unsigned Attribute, unsigned Value)
virtual void finishAttributeSection ()
virtual void emitTextAttribute (unsigned Attribute, StringRef String)
virtual void emitIntTextAttribute (unsigned Attribute, unsigned IntValue, StringRef StringValue)
void emitTargetAttributes (const MCSubtargetInfo &STI)
void setTargetABI (RISCVABI::ABI ABI)
RISCVABI::ABI getTargetABI () const
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 20 of file RISCVTargetStreamer.h.
Constructor & Destructor Documentation
RISCVTargetStreamer()
RISCVTargetStreamer::RISCVTargetStreamer (MCStreamer & S)
Definition at line 23 of file RISCVTargetStreamer.cpp.
Member Function Documentation
emitAttribute()
void RISCVTargetStreamer::emitAttribute (unsigned Attribute, unsigned Value) virtual
Definition at line 37 of file RISCVTargetStreamer.cpp.
Referenced by emitTargetAttributes().
emitDirectiveOptionNoPIC()
void RISCVTargetStreamer::emitDirectiveOptionNoPIC () virtual
Reimplemented in llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetAsmStreamer.
Definition at line 31 of file RISCVTargetStreamer.cpp.
emitDirectiveOptionNoRelax()
void RISCVTargetStreamer::emitDirectiveOptionNoRelax () virtual
Reimplemented in llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetAsmStreamer.
Definition at line 35 of file RISCVTargetStreamer.cpp.
emitDirectiveOptionNoRVC()
void RISCVTargetStreamer::emitDirectiveOptionNoRVC () virtual
Reimplemented in llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetAsmStreamer.
Definition at line 33 of file RISCVTargetStreamer.cpp.
emitDirectiveOptionPIC()
void RISCVTargetStreamer::emitDirectiveOptionPIC () virtual
Reimplemented in llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetAsmStreamer.
Definition at line 30 of file RISCVTargetStreamer.cpp.
emitDirectiveOptionPop()
void RISCVTargetStreamer::emitDirectiveOptionPop () virtual
Reimplemented in llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetAsmStreamer.
Definition at line 29 of file RISCVTargetStreamer.cpp.
emitDirectiveOptionPush()
void RISCVTargetStreamer::emitDirectiveOptionPush () virtual
Reimplemented in llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetAsmStreamer.
Definition at line 28 of file RISCVTargetStreamer.cpp.
emitDirectiveOptionRelax()
void RISCVTargetStreamer::emitDirectiveOptionRelax () virtual
Reimplemented in llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetAsmStreamer.
Definition at line 34 of file RISCVTargetStreamer.cpp.
emitDirectiveOptionRVC()
void RISCVTargetStreamer::emitDirectiveOptionRVC () virtual
Reimplemented in llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetAsmStreamer.
Definition at line 32 of file RISCVTargetStreamer.cpp.
emitDirectiveVariantCC()
void RISCVTargetStreamer::emitDirectiveVariantCC (MCSymbol & Symbol) virtual
Reimplemented in llvm::RISCVTargetELFStreamer, and llvm::RISCVTargetAsmStreamer.
Definition at line 36 of file RISCVTargetStreamer.cpp.
emitIntTextAttribute()
void RISCVTargetStreamer::emitIntTextAttribute (unsigned Attribute, unsigned IntValue, StringRef StringValue) virtual
Definition at line 41 of file RISCVTargetStreamer.cpp.
emitTargetAttributes()
void RISCVTargetStreamer::emitTargetAttributes (const MCSubtargetInfo & STI)
Definition at line 49 of file RISCVTargetStreamer.cpp.
References llvm::RISCVAttrs::ALIGN_16, llvm::RISCVAttrs::ALIGN_4, llvm::RISCVAttrs::ARCH, emitAttribute(), emitTextAttribute(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCSubtargetInfo::hasFeature(), llvm::RISCVFeatures::parseFeatureBits(), llvm::report_fatal_error(), and llvm::RISCVAttrs::STACK_ALIGN.
emitTextAttribute()
void RISCVTargetStreamer::emitTextAttribute (unsigned Attribute, StringRef String) virtual
Definition at line 39 of file RISCVTargetStreamer.cpp.
Referenced by emitTargetAttributes().
finish()
void RISCVTargetStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 25 of file RISCVTargetStreamer.cpp.
References finishAttributeSection().
Referenced by llvm::RISCVTargetELFStreamer::finish().
finishAttributeSection()
void RISCVTargetStreamer::finishAttributeSection () virtual
Definition at line 38 of file RISCVTargetStreamer.cpp.
Referenced by finish().
getTargetABI()
RISCVABI::ABI llvm::RISCVTargetStreamer::getTargetABI () const inline
Definition at line 45 of file RISCVTargetStreamer.h.
Referenced by llvm::RISCVTargetELFStreamer::finish().
reset()
void RISCVTargetStreamer::reset () virtual
Definition at line 26 of file RISCVTargetStreamer.cpp.
setTargetABI()
void RISCVTargetStreamer::setTargetABI (RISCVABI::ABI ABI)
Definition at line 44 of file RISCVTargetStreamer.cpp.
References ABI, llvm::RISCVABI::ABI_Unknown, and assert().
Referenced by llvm::RISCVTargetELFStreamer::RISCVTargetELFStreamer().
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.h
lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp