LLVM: llvm::LoopFlattenPass Class Reference
llvm::LoopFlattenPass Class Reference
#include "llvm/Transforms/Scalar/LoopFlatten.h"
Public Member Functions
LoopFlattenPass ()=default
PreservedAnalyses run (LoopNest &LN, LoopAnalysisManager &LAM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Public Member Functions inherited from llvm::PassInfoMixin< LoopFlattenPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopFlattenPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 23 of file LoopFlatten.h.
Constructor & Destructor Documentation
LoopFlattenPass()
llvm::LoopFlattenPass::LoopFlattenPass () default
Member Function Documentation
run()
PreservedAnalyses LoopFlattenPass::run (LoopNest & LN, LoopAnalysisManager & LAM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 921 of file LoopFlatten.cpp.
References llvm::LoopStandardAnalysisResults::AC, llvm::PreservedAnalyses::all(), llvm::LoopStandardAnalysisResults::DT, FlattenLoopPair(), llvm::getLoopPassPreservedAnalyses(), llvm::LoopNest::getLoops(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::LoopStandardAnalysisResults::LI, llvm::LoopStandardAnalysisResults::MSSA, llvm::LoopStandardAnalysisResults::SE, llvm::LoopStandardAnalysisResults::TTI, llvm::MemorySSA::verifyMemorySSA(), and llvm::VerifyMemorySSA.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopFlatten.h
lib/Transforms/Scalar/LoopFlatten.cpp