LLVM: llvm::logicalview::LVTypeSubrange Class Reference
llvm::logicalview::LVTypeSubrange Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVType.h"
Public Member Functions
LVTypeSubrange ()
LVTypeSubrange (const LVTypeSubrange &)=delete
LVTypeSubrange & operator= (const LVTypeSubrange &)=delete
~LVTypeSubrange ()=default
int64_t getCount () const override
void setCount (int64_t Value) override
int64_t getLowerBound () const override
void setLowerBound (int64_t Value) override
int64_t getUpperBound () const override
void setUpperBound (int64_t Value) override
std::pair< unsigned, unsigned > getBounds () const override
void setBounds (unsigned Lower, unsigned Upper) override
void resolveExtra () override
bool equals (const LVType *Type) const override
void printExtra (raw_ostream &OS, bool Full=true) const override
Public Member Functions inherited from llvm::logicalview::LVType
LVType ()
LVType (const LVType &)=delete
LVType & operator= (const LVType &)=delete
virtual ~LVType ()=default
KIND (LVTypeKind, IsBase)
KIND (LVTypeKind, IsConst)
KIND (LVTypeKind, IsEnumerator)
KIND (LVTypeKind, IsImport)
KIND_1 (LVTypeKind, IsImportDeclaration, IsImport)
KIND_1 (LVTypeKind, IsImportModule, IsImport)
KIND (LVTypeKind, IsPointer)
KIND (LVTypeKind, IsPointerMember)
KIND (LVTypeKind, IsReference)
KIND (LVTypeKind, IsRestrict)
KIND (LVTypeKind, IsRvalueReference)
KIND (LVTypeKind, IsSubrange)
KIND (LVTypeKind, IsTemplateParam)
KIND_1 (LVTypeKind, IsTemplateTemplateParam, IsTemplateParam)
KIND_1 (LVTypeKind, IsTemplateTypeParam, IsTemplateParam)
KIND_1 (LVTypeKind, IsTemplateValueParam, IsTemplateParam)
KIND (LVTypeKind, IsTypedef)
KIND (LVTypeKind, IsUnaligned)
KIND (LVTypeKind, IsUnspecified)
KIND (LVTypeKind, IsVolatile)
KIND (LVTypeKind, IsModifier)
PROPERTY (Property, IsSubrangeCount)
const char * kind () const override
StringRef resolveReferencesChain ()
bool isBase () const override
bool isTemplateParam () const override
virtual void encodeTemplateArgument (std::string &Name) const
virtual LVElement * getUnderlyingType ()
virtual void setUnderlyingType (LVElement *Element)
void resolveName () override
void resolveReferences () override
void report (LVComparePass Pass) override
void print (raw_ostream &OS, bool Full=true) const override
void dump () const override
Public Member Functions inherited from llvm::logicalview::LVElement
LVElement (LVSubclassID ID)
LVElement (const LVElement &)=delete
LVElement & operator= (const LVElement &)=delete
virtual ~LVElement ()=default
LVSubclassID getSubclassID () const
PROPERTY (Property, IsLine)
PROPERTY (Property, IsScope)
PROPERTY (Property, IsSymbol)
PROPERTY (Property, IsType)
PROPERTY (Property, IsEnumClass)
PROPERTY (Property, IsExternal)
PROPERTY (Property, HasType)
PROPERTY (Property, HasAugmentedName)
PROPERTY (Property, IsTypedefReduced)
PROPERTY (Property, IsArrayResolved)
PROPERTY (Property, IsMemberPointerResolved)
PROPERTY (Property, IsTemplateResolved)
PROPERTY (Property, IsInlined)
PROPERTY (Property, IsInlinedAbstract)
PROPERTY (Property, InvalidFilename)
PROPERTY (Property, HasReference)
PROPERTY (Property, HasReferenceAbstract)
PROPERTY (Property, HasReferenceExtension)
PROPERTY (Property, HasReferenceSpecification)
PROPERTY (Property, QualifiedResolved)
PROPERTY (Property, IncludeInPrint)
PROPERTY (Property, IsStatic)
PROPERTY (Property, TransformName)
PROPERTY (Property, IsScoped)
PROPERTY (Property, IsNested)
PROPERTY (Property, IsScopedAlready)
PROPERTY (Property, IsArtificial)
PROPERTY (Property, IsReferencedType)
PROPERTY (Property, IsSystem)
PROPERTY (Property, OffsetFromTypeIndex)
PROPERTY (Property, IsAnonymous)
bool isNamed () const override
bool isTyped () const override
bool isFiled () const override
bool getIsKindType () const
bool getIsKindScope () const
StringRef getName () const override
void setName (StringRef ElementName) override
StringRef getPathname () const
void setFilename (StringRef Filename)
void setQualifiedName (StringRef Name)
StringRef getQualifiedName () const
size_t getNameIndex () const
size_t getQualifiedNameIndex () const
StringRef getTypeName () const
virtual StringRef getProducer () const
virtual void setProducer (StringRef ProducerName)
virtual bool isCompileUnit () const
virtual bool isRoot () const
virtual void setReference (LVElement *Element)
virtual void setReference (LVScope *Scope)
virtual void setReference (LVSymbol *Symbol)
virtual void setReference (LVType *Type)
virtual void setLinkageName (StringRef LinkageName)
virtual StringRef getLinkageName () const
virtual size_t getLinkageNameIndex () const
virtual uint32_t getCallLineNumber () const
virtual void setCallLineNumber (uint32_t Number)
virtual size_t getCallFilenameIndex () const
virtual void setCallFilenameIndex (size_t Index)
size_t getFilenameIndex () const
void setFilenameIndex (size_t Index)
void setFile (LVElement *Reference=nullptr)
virtual uint32_t getBitSize () const
virtual void setBitSize (uint32_t Size)
virtual uint32_t getDiscriminator () const
virtual void setDiscriminator (uint32_t Value)
virtual std::string getValue () const
virtual void setValue (StringRef Value)
virtual size_t getValueIndex () const
uint32_t getAccessibilityCode () const
void setAccessibilityCode (uint32_t Access)
StringRef accessibilityString (uint32_t Access=dwarf::DW_ACCESS_private) const
uint32_t getInlineCode () const
void setInlineCode (uint32_t Code)
StringRef inlineCodeString (uint32_t Code) const
uint32_t getVirtualityCode () const
void setVirtualityCode (uint32_t Virtuality)
StringRef virtualityString (uint32_t Virtuality=dwarf::DW_VIRTUALITY_none) const
StringRef externalString () const
LVElement * getType () const
LVType * getTypeAsType () const
LVScope * getTypeAsScope () const
void setType (LVElement *Element=nullptr)
void setGenericType (LVElement *Element)
StringRef getTypeQualifiedName () const
StringRef typeAsString () const
std::string typeOffsetAsString () const
std::string discriminatorAsString () const
LVScope * traverseParents (LVScopeGetFunction GetFunction) const
LVScope * getFunctionParent () const
virtual LVScope * getCompileUnitParent () const
void printReference (raw_ostream &OS, bool Full, LVElement *Parent) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent, LVScope *Scope) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent) const
void resolveFullname (LVElement *BaseType, StringRef Name=emptyString())
void generateName (std::string &Prefix) const
void generateName ()
virtual bool removeElement (LVElement *Element)
virtual void updateLevel (LVScope *Parent, bool Moved=false)
virtual void resolve ()
void resolveParents ()
bool referenceMatch (const LVElement *Element) const
bool equals (const LVElement *Element) const
Public Member Functions inherited from llvm::logicalview::LVObject
LVObject ()
LVObject & operator= (const LVObject &)=delete
virtual ~LVObject ()=default
PROPERTY (Property, IsLocation)
PROPERTY (Property, IsGlobalReference)
PROPERTY (Property, IsGeneratedName)
PROPERTY (Property, IsResolved)
PROPERTY (Property, IsResolvedName)
PROPERTY (Property, IsDiscarded)
PROPERTY (Property, IsOptimized)
PROPERTY (Property, IsAdded)
PROPERTY (Property, IsMatched)
PROPERTY (Property, IsMissing)
PROPERTY (Property, IsMissingLink)
PROPERTY (Property, IsInCompare)
PROPERTY (Property, IsFileFromReference)
PROPERTY (Property, IsLineFromReference)
PROPERTY (Property, HasMoved)
PROPERTY (Property, HasPattern)
PROPERTY (Property, IsFinalized)
PROPERTY (Property, IsReferenced)
PROPERTY (Property, HasCodeViewLocation)
bool isLined () const
dwarf::Tag getTag () const
void setTag (dwarf::Tag Tag)
dwarf::Attribute getAttr () const
void setAttr (dwarf::Attribute Attr)
LVSmall getOpcode () const
void setOpcode (LVSmall Opcode)
LVOffset getOffset () const
void setOffset (LVOffset DieOffset)
LVLevel getLevel () const
void setLevel (LVLevel Level)
LVElement * getParent () const
LVScope * getParentScope () const
LVSymbol * getParentSymbol () const
void setParent (LVScope *Scope)
void setParent (LVSymbol *Symbol)
void resetParent ()
virtual LVAddress getLowerAddress () const
virtual void setLowerAddress (LVAddress Address)
virtual LVAddress getUpperAddress () const
virtual void setUpperAddress (LVAddress Address)
uint32_t getLineNumber () const
void setLineNumber (uint32_t Number)
std::string indentAsString () const
std::string indentAsString (LVLevel Level) const
virtual std::string noLineAsString (bool ShowZero) const
virtual std::string lineNumberAsString (bool ShowZero=false) const
std::string lineNumberAsStringStripped (bool ShowZero=false) const
virtual Error doPrint (bool Split, bool Match, bool Print, raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full, StringRef Name, LVObject *Parent, StringRef Value, bool UseQuotes=false, bool PrintRef=false) const
void markBranchAsMissing ()
uint64_t getID () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::logicalview::LVType
static bool classof (const LVElement *Element)
static LVTypeDispatch & getDispatch ()
static bool parametersMatch (const LVTypes *References, const LVTypes *Targets)
static void getParameters (const LVTypes *Types, LVTypes *TypesParam, LVScopes *ScopesParam)
static void markMissingParents (const LVTypes *References, const LVTypes *Targets)
static bool equals (const LVTypes *References, const LVTypes *Targets)
Static Public Member Functions inherited from llvm::logicalview::LVElement
static LVElementDispatch & getDispatch ()
Protected Member Functions inherited from llvm::logicalview::LVElement
void printFileIndex (raw_ostream &OS, bool Full=true) const override
Protected Member Functions inherited from llvm::logicalview::LVObject
std::string lineAsString (uint32_t LineNumber, LVHalf Discriminator, bool ShowZero) const
std::string referenceAsString (uint32_t LineNumber, bool Spaces) const
Protected Attributes inherited from llvm::logicalview::LVElement
LVElement * ElementType = nullptr
Detailed Description
Definition at line 243 of file LVType.h.
Constructor & Destructor Documentation
LVTypeSubrange() [1/2]
llvm::logicalview::LVTypeSubrange::LVTypeSubrange () inline
Definition at line 249 of file LVType.h.
LVTypeSubrange() [2/2]
llvm::logicalview::LVTypeSubrange::LVTypeSubrange (const LVTypeSubrange &) delete
~LVTypeSubrange()
llvm::logicalview::LVTypeSubrange::~LVTypeSubrange () default
Member Function Documentation
equals()
bool LVTypeSubrange::equals (const LVType * Type) const override virtual
Reimplemented from llvm::logicalview::LVType.
Definition at line 508 of file LVType.cpp.
References llvm::logicalview::LVType::equals(), llvm::logicalview::LVElement::getName(), and llvm::logicalview::LVElement::getTypeName().
getBounds()
std::pair<unsigned, unsigned> llvm::logicalview::LVTypeSubrange::getBounds () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 271 of file LVType.h.
getCount()
int64_t llvm::logicalview::LVTypeSubrange::getCount () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 257 of file LVType.h.
Referenced by resolveExtra().
getLowerBound()
int64_t llvm::logicalview::LVTypeSubrange::getLowerBound () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 265 of file LVType.h.
Referenced by resolveExtra().
getUpperBound()
int64_t llvm::logicalview::LVTypeSubrange::getUpperBound () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 268 of file LVType.h.
Referenced by resolveExtra().
operator=()
LVTypeSubrange& llvm::logicalview::LVTypeSubrange::operator= (const LVTypeSubrange &) delete
printExtra()
void LVTypeSubrange::printExtra (raw_ostream & OS, bool Full = true) const override virtual
Reimplemented from llvm::logicalview::LVType.
Definition at line 515 of file LVType.cpp.
References llvm::logicalview::formattedKind(), llvm::logicalview::formattedName(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVElement::getTypeName(), llvm::logicalview::LVType::kind(), OS, and llvm::logicalview::LVElement::typeOffsetAsString().
resolveExtra()
void LVTypeSubrange::resolveExtra () override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 480 of file LVType.cpp.
References getCount(), getLowerBound(), getUpperBound(), and llvm::logicalview::LVElement::setName().
setBounds()
void llvm::logicalview::LVTypeSubrange::setBounds (unsigned Lower, unsigned Upper) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 274 of file LVType.h.
References llvm::Upper.
setCount()
void llvm::logicalview::LVTypeSubrange::setCount (int64_t Value) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 260 of file LVType.h.
setLowerBound()
void llvm::logicalview::LVTypeSubrange::setLowerBound (int64_t Value) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 266 of file LVType.h.
setUpperBound()
void llvm::logicalview::LVTypeSubrange::setUpperBound (int64_t Value) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 269 of file LVType.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVType.h
lib/DebugInfo/LogicalView/Core/LVType.cpp