LLVM: llvm::objcopy::elf::SymbolTableSection Class Reference
llvm::objcopy::elf::SymbolTableSection Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
SymbolTableSection ()
void addSymbol (Twine Name, uint8_t Bind, uint8_t Type, SectionBase *DefinedIn, uint64_t Value, uint8_t Visibility, uint16_t Shndx, uint64_t SymbolSize)
void prepareForLayout ()
bool empty () const
void setShndxTable (SectionIndexSection *ShndxTable)
const SectionIndexSection * getShndxTable () const
void fillShndxTable ()
const SectionBase * getStrTab () const
Expected< const Symbol * > getSymbolByIndex (uint32_t Index) const
Expected< Symbol * > getSymbolByIndex (uint32_t Index)
void updateSymbols (function_ref< void(Symbol &)> Callable)
Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override
Error initialize (SectionTableRef SecTable) override
void finalize () override
Error accept (SectionVisitor &Visitor) const override
Error accept (MutableSectionVisitor &Visitor) override
Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove) override
void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &FromTo) override
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual void markSymbols ()
virtual bool hasContents () const
virtual void onRemove ()
Static Public Member Functions
static bool classof (const SectionBase *S)
Protected Types
using SymPtr = std::unique_ptr< Symbol >
Protected Attributes
std::vector< std::unique_ptr< Symbol > > Symbols
StringTableSection * SymbolNames = nullptr
SectionIndexSection * SectionIndexTable = nullptr
Additional Inherited Members
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Detailed Description
Definition at line 684 of file ELFObject.h.
Member Typedef Documentation
SymPtr
using llvm::objcopy::elf::SymbolTableSection::SymPtr = std::unique_ptr<Symbol> protected
Definition at line 695 of file ELFObject.h.
Constructor & Destructor Documentation
SymbolTableSection()
llvm::objcopy::elf::SymbolTableSection::SymbolTableSection () inline
Definition at line 698 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::OriginalType, and llvm::ELF::SHT_SYMTAB.
Member Function Documentation
accept() [1/2]
Error SymbolTableSection::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 852 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error SymbolTableSection::accept (SectionVisitor & Visitor) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 848 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
addSymbol()
void SymbolTableSection::addSymbol (Twine Name, uint8_t Bind, uint8_t Type, SectionBase * DefinedIn, uint64_t Value, uint8_t Visibility, uint16_t Shndx, uint64_t SymbolSize)
Definition at line 687 of file ELFObject.cpp.
References llvm::objcopy::elf::Symbol::Binding, llvm::objcopy::elf::Symbol::DefinedIn, llvm::objcopy::elf::SectionBase::EntrySize, llvm::objcopy::elf::SectionBase::HasSymbol, llvm::objcopy::elf::Symbol::Index, llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::elf::Symbol::Name, llvm::ELF::SHN_LORESERVE, llvm::objcopy::elf::Symbol::ShndxType, llvm::objcopy::elf::SectionBase::Size, llvm::objcopy::elf::Symbol::Size, llvm::objcopy::elf::SYMBOL_SIMPLE_INDEX, Symbols, llvm::objcopy::elf::SectionBase::Type, llvm::objcopy::elf::Symbol::Type, llvm::objcopy::elf::Symbol::Value, and llvm::objcopy::elf::Symbol::Visibility.
Referenced by addSymbol().
classof()
static bool llvm::objcopy::elf::SymbolTableSection::classof (const SectionBase * S) inline static
Definition at line 727 of file ELFObject.h.
References S, and llvm::ELF::SHT_SYMTAB.
empty()
bool llvm::objcopy::elf::SymbolTableSection::empty () const inline
Definition at line 705 of file ELFObject.h.
References Symbols.
Referenced by removeUnneededSections(), and replaceAndRemoveSections().
fillShndxTable()
void SymbolTableSection::fillShndxTable ()
Definition at line 801 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionIndexSection::addIndex(), SectionIndexTable, llvm::ELF::SHN_LORESERVE, llvm::ELF::SHN_UNDEF, and Symbols.
finalize()
void SymbolTableSection::finalize () override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 772 of file ELFObject.cpp.
References llvm::objcopy::elf::StringTableSection::findIndex(), llvm::objcopy::elf::SectionBase::Index, llvm::objcopy::elf::SectionBase::Info, llvm::objcopy::elf::SectionBase::Link, llvm::max(), llvm::ELF::STB_LOCAL, SymbolNames, and Symbols.
getShndxTable()
const SectionIndexSection* llvm::objcopy::elf::SymbolTableSection::getShndxTable () const inline
Definition at line 709 of file ELFObject.h.
References SectionIndexTable.
getStrTab()
const SectionBase* llvm::objcopy::elf::SymbolTableSection::getStrTab () const inline
Definition at line 711 of file ELFObject.h.
References SymbolNames.
Referenced by removeUnneededSections(), and replaceAndRemoveSections().
getSymbolByIndex() [1/2]
Expected< Symbol * > SymbolTableSection::getSymbolByIndex (uint32_t Index)
Definition at line 822 of file ELFObject.cpp.
References getSymbolByIndex(), and llvm::Expected< T >::takeError().
getSymbolByIndex() [2/2]
Expected< const Symbol * > SymbolTableSection::getSymbolByIndex (uint32_t Index) const
Definition at line 815 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::SectionBase::Index, llvm::invalid_argument, and Symbols.
Referenced by getSymbolByIndex(), and initRelocations().
initialize()
Error SymbolTableSection::initialize (SectionTableRef SecTable) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 756 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionTableRef::getSectionOfType(), llvm::objcopy::elf::SectionBase::Link, llvm::objcopy::elf::SectionBase::Size, llvm::Error::success(), and llvm::Expected< T >::takeError().
prepareForLayout()
void SymbolTableSection::prepareForLayout ()
Definition at line 785 of file ELFObject.cpp.
References llvm::objcopy::elf::StringTableSection::addString(), llvm::objcopy::elf::SectionIndexSection::reserve(), SectionIndexTable, SymbolNames, and Symbols.
removeSectionReferences()
Error SymbolTableSection::removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 712 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::Symbol::DefinedIn, llvm::invalid_argument, llvm::objcopy::elf::SectionBase::Name, removeSymbols(), SectionIndexTable, SymbolNames, this, and ToRemove.
removeSymbols()
Error SymbolTableSection::removeSymbols (function_ref< bool(const Symbol &)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 738 of file ELFObject.cpp.
References llvm::sys::path::begin(), llvm::sys::path::end(), llvm::objcopy::elf::SectionBase::EntrySize, llvm::remove_if(), llvm::objcopy::elf::SectionBase::Size, llvm::Error::success(), Symbols, and ToRemove.
Referenced by removeSectionReferences().
replaceSectionReferences()
void SymbolTableSection::replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > & FromTo) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 749 of file ELFObject.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::lookup(), and Symbols.
setShndxTable()
void llvm::objcopy::elf::SymbolTableSection::setShndxTable (SectionIndexSection * ShndxTable) inline
Definition at line 706 of file ELFObject.h.
References SectionIndexTable.
Referenced by llvm::objcopy::elf::SectionIndexSection::initialize().
updateSymbols()
void SymbolTableSection::updateSymbols (function_ref< void(Symbol &)> Callable)
Definition at line 729 of file ELFObject.cpp.
References llvm::sys::path::begin(), llvm::drop_begin(), llvm::sys::path::end(), llvm::ELF::STB_LOCAL, and Symbols.
Referenced by updateAndRemoveSymbols().
Member Data Documentation
SectionIndexTable
SectionIndexSection* llvm::objcopy::elf::SymbolTableSection::SectionIndexTable = nullptr protected
Definition at line 693 of file ELFObject.h.
Referenced by fillShndxTable(), getShndxTable(), prepareForLayout(), removeSectionReferences(), and setShndxTable().
SymbolNames
StringTableSection* llvm::objcopy::elf::SymbolTableSection::SymbolNames = nullptr protected
Definition at line 692 of file ELFObject.h.
Referenced by finalize(), getStrTab(), prepareForLayout(), and removeSectionReferences().
Symbols
std::vector<std::unique_ptr<Symbol> > llvm::objcopy::elf::SymbolTableSection::Symbols protected
Definition at line 691 of file ELFObject.h.
Referenced by addSymbol(), empty(), fillShndxTable(), finalize(), getSymbolByIndex(), prepareForLayout(), removeSymbols(), replaceSectionReferences(), updateSymbols(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), and llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp