LLVM: llvm::TextInstrProfReader Class Reference
llvm::TextInstrProfReader Class Reference
Reader for the simple text based instrprof format.
#include "llvm/ProfileData/InstrProfReader.h"
Public Member Functions
TextInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer_)
TextInstrProfReader (const TextInstrProfReader &)=delete
TextInstrProfReader & operator= (const TextInstrProfReader &)=delete
uint64_t getVersion () const override
Return the profile version.
bool isIRLevelProfile () const override
bool hasCSIRLevelProfile () const override
bool instrEntryBBEnabled () const override
bool hasSingleByteCoverage () const override
Return true if the profile has single byte counters representing coverage.
bool functionEntryOnly () const override
Return true if the profile only instruments function entries.
bool hasMemoryProfile () const override
Return true if profile includes a memory profile.
InstrProfKind getProfileKind () const override
Returns a BitsetEnum describing the attributes of the profile.
Error readHeader () override
Read the header.
Error readNextRecord (NamedInstrProfRecord &Record) override
Read a single record.
InstrProfSymtab & getSymtab () override
Return the PGO symtab.
Public Member Functions inherited from llvm::InstrProfReader
InstrProfReader ()=default
virtual ~InstrProfReader ()=default
virtual Error readBinaryIds (std::vector< llvm::object::BuildID > &BinaryIds)
Read a list of binary ids.
virtual Error printBinaryIds (raw_ostream &OS)
Print binary ids.
InstrProfIterator begin ()
Iterator over profile data.
InstrProfIterator end ()
virtual bool useDebugInfoCorrelate () const
Return true if we must provide debug info to create PGO profiles.
void accumulateCounts (CountSumOrPercent &Sum, bool IsCS)
Compute the sum of counts and return in Sum.
bool isEOF ()
Return true if the reader has finished reading the profile data.
bool hasError ()
Return true if the reader encountered an error reading profiling data.
Error getError ()
Get the current error.
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &Buffer)
Return true if the given buffer is in text instrprof format.
Static Public Member Functions inherited from llvm::InstrProfReader
static Expected< std::unique_ptr< InstrProfReader > > create (const Twine &Path, vfs::FileSystem &FS, const InstrProfCorrelator *Correlator=nullptr)
Factory method to create an appropriately typed reader for the given instrprof file.
static Expected< std::unique_ptr< InstrProfReader > > create (std::unique_ptr< MemoryBuffer > Buffer, const InstrProfCorrelator *Correlator=nullptr)
Additional Inherited Members
Protected Member Functions inherited from llvm::InstrProfReader
Error error (instrprof_error Err, const std::string &ErrMsg="")
Set the current error and return same.
Error error (Error &&E)
Error success ()
Clear the current error and return a successful one.
Protected Attributes inherited from llvm::InstrProfReader
std::unique_ptr< InstrProfSymtab > Symtab
Detailed Description
Reader for the simple text based instrprof format.
This format is a simple text format that's suitable for test data. Records are separated by one or more blank lines, and record fields are separated by new lines.
Each record consists of a function name, a function hash, a number of counters, and then each counter value, in that order.
Definition at line 213 of file InstrProfReader.h.
Constructor & Destructor Documentation
TextInstrProfReader() [1/2]
llvm::TextInstrProfReader::TextInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer_) inline
Definition at line 225 of file InstrProfReader.h.
TextInstrProfReader() [2/2]
llvm::TextInstrProfReader::TextInstrProfReader (const TextInstrProfReader &) delete
Member Function Documentation
functionEntryOnly()
bool llvm::TextInstrProfReader::functionEntryOnly () const inline override virtual
Return true if the profile only instruments function entries.
Implements llvm::InstrProfReader.
Definition at line 253 of file InstrProfReader.h.
References llvm::FunctionEntryOnly.
getProfileKind()
InstrProfKind llvm::TextInstrProfReader::getProfileKind () const inline override virtual
Returns a BitsetEnum describing the attributes of the profile.
To check individual attributes prefer using the helpers above.
Implements llvm::InstrProfReader.
Definition at line 262 of file InstrProfReader.h.
getSymtab()
InstrProfSymtab& llvm::TextInstrProfReader::getSymtab () inline override virtual
Return the PGO symtab.
There are three different readers: Raw, Text, and Indexed profile readers. The first two types of readers are used only by llvm-profdata tool, while the indexed profile reader is also used by llvm-cov tool and the compiler (backend or frontend). Since creating PGO symtab can create significant runtime and memory overhead (as it touches data for the whole program), InstrProfSymtab for the indexed profile reader should be created on demand and it is recommended to be only used for dumping purpose with llvm-proftool, not with the compiler.
Implements llvm::InstrProfReader.
Definition at line 270 of file InstrProfReader.h.
References assert(), and llvm::InstrProfReader::Symtab.
getVersion()
uint64_t llvm::TextInstrProfReader::getVersion () const inline override virtual
Return the profile version.
Implements llvm::InstrProfReader.
Definition at line 234 of file InstrProfReader.h.
hasCSIRLevelProfile()
bool llvm::TextInstrProfReader::hasCSIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 240 of file InstrProfReader.h.
References llvm::ContextSensitive.
hasFormat()
bool TextInstrProfReader::hasFormat (const MemoryBuffer & Buffer) static
Return true if the given buffer is in text instrprof format.
Definition at line 238 of file InstrProfReader.cpp.
References llvm::all_of(), llvm::StringRef::begin(), c, llvm::count(), llvm::MemoryBuffer::getBufferSize(), llvm::MemoryBuffer::getBufferStart(), llvm::min(), and uint64_t.
Referenced by llvm::InstrProfReader::create().
hasMemoryProfile()
bool llvm::TextInstrProfReader::hasMemoryProfile () const inline override virtual
Return true if profile includes a memory profile.
Implements llvm::InstrProfReader.
Definition at line 257 of file InstrProfReader.h.
hasSingleByteCoverage()
bool llvm::TextInstrProfReader::hasSingleByteCoverage () const inline override virtual
Return true if the profile has single byte counters representing coverage.
Implements llvm::InstrProfReader.
Definition at line 249 of file InstrProfReader.h.
References llvm::SingleByteCoverage.
instrEntryBBEnabled()
bool llvm::TextInstrProfReader::instrEntryBBEnabled () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 244 of file InstrProfReader.h.
References llvm::FunctionEntryInstrumentation.
isIRLevelProfile()
bool llvm::TextInstrProfReader::isIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 236 of file InstrProfReader.h.
References llvm::IRInstrumentation.
operator=()
TextInstrProfReader& llvm::TextInstrProfReader::operator= (const TextInstrProfReader &) delete
readHeader()
Error TextInstrProfReader::readHeader () override virtual
Read the header.
Implements llvm::InstrProfReader.
Definition at line 251 of file InstrProfReader.cpp.
References llvm::bad_header, llvm::ContextSensitive, llvm::InstrProfReader::error(), llvm::FrontendInstrumentation, llvm::FunctionEntryInstrumentation, llvm::IRInstrumentation, llvm::StringRef::startswith(), llvm::StringRef::substr(), llvm::InstrProfReader::success(), and llvm::InstrProfReader::Symtab.
readNextRecord()
Error TextInstrProfReader::readNextRecord (NamedInstrProfRecord & Record) override virtual
Read a single record.
Implements llvm::InstrProfReader.
Definition at line 346 of file InstrProfReader.cpp.
References E, llvm::StringRef::empty(), llvm::eof, llvm::InstrProfReader::error(), I, llvm::line_iterator::is_at_end(), llvm::malformed, move, llvm::StringRef::startswith(), llvm::InstrProfReader::success(), llvm::InstrProfReader::Symtab, llvm::truncated, and uint64_t.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfReader.h
lib/ProfileData/InstrProfReader.cpp