LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3 Class Reference
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerMsgPackV3 ()=default
~MetadataStreamerMsgPackV3 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void begin (const Module &Mod, const IsaInfo::AMDGPUTargetID &TargetID) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()=default
Protected Member Functions
void dump (StringRef HSAMetadataString) const
void verify (StringRef HSAMetadataString) const
std::optional< StringRef > getAccessQualifier (StringRef AccQual) const
std::optional< StringRef > getAddressSpaceQualifier (unsigned AddressSpace) const
StringRef getValueKind (Type *Ty, StringRef TypeQual, StringRef BaseTypeName) const
std::string getTypeName (Type *Ty, bool Signed) const
msgpack::ArrayDocNode getWorkGroupDimensions (MDNode *Node) const
msgpack::MapDocNode getHSAKernelProps (const MachineFunction &MF, const SIProgramInfo &ProgramInfo, unsigned CodeObjectVersion) const
void emitVersion () override
void emitPrintf (const Module &Mod)
void emitKernelLanguage (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelAttrs (const Function &Func, msgpack::MapDocNode Kern) override
void emitKernelArgs (const MachineFunction &MF, msgpack::MapDocNode Kern)
void emitKernelArg (const Argument &Arg, unsigned &Offset, msgpack::ArrayDocNode Args)
void emitKernelArg (const DataLayout &DL, Type *Ty, Align Alignment, StringRef ValueKind, unsigned &Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign=std::nullopt, StringRef Name="", StringRef TypeName="", StringRef BaseTypeName="", StringRef AccQual="", StringRef TypeQual="")
void emitHiddenKernelArgs (const MachineFunction &MF, unsigned &Offset, msgpack::ArrayDocNode Args) override
msgpack::DocNode & getRootMetadata (StringRef Key)
msgpack::DocNode & getHSAMetadataRoot ()
Protected Attributes
std::unique_ptr< msgpack::Document > HSAMetadataDoc
Detailed Description
Definition at line 65 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerMsgPackV3()
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::MetadataStreamerMsgPackV3 () default
~MetadataStreamerMsgPackV3()
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::~MetadataStreamerMsgPackV3 () default
Member Function Documentation
begin()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::begin (const Module & Mod, const IsaInfo::AMDGPUTargetID & TargetID) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4.
Definition at line 929 of file AMDGPUHSAMetadataStreamer.cpp.
References emitPrintf(), emitVersion(), getRootMetadata(), HSAMetadataDoc, and Mod.
dump()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::dump (StringRef HSAMetadataString) const protected
Definition at line 486 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::errs().
Referenced by end().
emitHiddenKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitHiddenKernelArgs (const MachineFunction & MF, unsigned & Offset, msgpack::ArrayDocNode Args) override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5.
Definition at line 803 of file AMDGPUHSAMetadataStreamer.cpp.
References Align, llvm::alignTo(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, DL, emitKernelArg(), llvm::MachineFunction::getFunction(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUAS::GLOBAL_ADDRESS, M, and llvm::ARM_MB::ST.
Referenced by emitKernelArgs().
emitKernel()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernel (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 947 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, assert(), emitKernelArgs(), emitKernelAttrs(), emitKernelLanguage(), llvm::msgpack::DocNode::getArray(), llvm::AMDGPU::getCodeObjectVersion(), llvm::msgpack::DocNode::getDocument(), llvm::MachineFunction::getFunction(), getHSAKernelProps(), llvm::msgpack::Document::getNode(), getRootMetadata(), llvm::AMDGPU::HSAMD::Key::Kernels, and llvm::CallingConv::SPIR_KERNEL.
emitKernelArg() [1/2]
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernelArg (const Argument & Arg, unsigned & Offset, msgpack::ArrayDocNode Args) protected
Definition at line 695 of file AMDGPUHSAMetadataStreamer.cpp.
References Arg.
Referenced by emitHiddenKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), and emitKernelArgs().
emitKernelArg() [2/2]
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernelArg (const DataLayout & DL, Type * Ty, Align Alignment, StringRef ValueKind, unsigned & Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign = std::nullopt, StringRef Name = "", StringRef TypeName = "", StringRef BaseTypeName = "", StringRef AccQual = "", StringRef TypeQual = "") protected
Definition at line 755 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::AccQual, llvm::alignTo(), Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, DL, getAccessQualifier(), getAddressSpaceQualifier(), llvm::AMDGPU::HSAMD::Kernel::Arg::Key::PointeeAlign, llvm::StringRef::split(), and llvm::AMDGPU::HSAMD::Kernel::Arg::Key::TypeName.
emitKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernelArgs (const MachineFunction & MF, msgpack::MapDocNode Kern) protected
Definition at line 682 of file AMDGPUHSAMetadataStreamer.cpp.
References Arg, llvm::AMDGPU::HSAMD::Kernel::Key::Args, emitHiddenKernelArgs(), emitKernelArg(), llvm::MachineFunction::getFunction(), and HSAMetadataDoc.
Referenced by emitKernel().
emitKernelAttrs()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernelAttrs (const Function & Func, msgpack::MapDocNode Kern) override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5.
Definition at line 657 of file AMDGPUHSAMetadataStreamer.cpp.
Referenced by emitKernel(), and llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitKernelAttrs().
emitKernelLanguage()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernelLanguage (const Function & Func, msgpack::MapDocNode Kern) protected
Definition at line 638 of file AMDGPUHSAMetadataStreamer.cpp.
Referenced by emitKernel().
emitPrintf()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitPrintf (const Module & Mod) protected
Definition at line 625 of file AMDGPUHSAMetadataStreamer.cpp.
Referenced by begin(), and llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::begin().
emitTo()
bool llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitTo (AMDGPUTargetStreamer & TargetStreamer) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 925 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUTargetStreamer::EmitHSAMetadata(), and HSAMetadataDoc.
emitVersion()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitVersion () override protected virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5, and llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4.
Definition at line 618 of file AMDGPUHSAMetadataStreamer.cpp.
References getRootMetadata(), HSAMetadataDoc, llvm::IndexedInstrProf::Version, llvm::AMDGPU::HSAMD::VersionMajorV3, and llvm::AMDGPU::HSAMD::VersionMinorV3.
Referenced by begin().
end()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::end () override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 936 of file AMDGPUHSAMetadataStreamer.cpp.
References dump(), llvm::DumpHSAMetadata, HSAMetadataDoc, llvm::raw_string_ostream::str(), verify(), and llvm::VerifyHSAMetadata.
getAccessQualifier()
std::optional< StringRef > llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getAccessQualifier (StringRef AccQual) const protected
Definition at line 512 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Arg::Key::AccQual.
Referenced by emitKernelArg().
getAddressSpaceQualifier()
std::optional< StringRef > llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getAddressSpaceQualifier (unsigned AddressSpace) const protected
Definition at line 520 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::AMDGPUAS::FLAT_ADDRESS, llvm::AMDGPUAS::GLOBAL_ADDRESS, llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::AMDGPUAS::PRIVATE_ADDRESS, and llvm::AMDGPUAS::REGION_ADDRESS.
Referenced by emitKernelArg().
getHSAKernelProps()
msgpack::MapDocNode llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getHSAKernelProps (const MachineFunction & MF, const SIProgramInfo & ProgramInfo, unsigned CodeObjectVersion) const protected
Definition at line 878 of file AMDGPUHSAMetadataStreamer.cpp.
References Align, llvm::AMDGPU::AMDHSA_COV5, llvm::SIProgramInfo::DynamicCallStack, F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AMDGPUSubtarget::getKernArgSegmentSize(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::GCNSubtarget::hasMAIInsts(), HSAMetadataDoc, llvm::SIProgramInfo::LDSSize, llvm::max(), llvm::SIProgramInfo::NumAccVGPR, llvm::SIProgramInfo::NumSGPR, llvm::SIProgramInfo::NumVGPR, llvm::SIProgramInfo::ScratchSize, llvm::GCNSubtarget::supportsWGP(), and llvm::SIProgramInfo::WgpMode.
Referenced by emitKernel().
getHSAMetadataRoot()
msgpack::DocNode& llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getHSAMetadataRoot () inline protected
Definition at line 118 of file AMDGPUHSAMetadataStreamer.h.
References HSAMetadataDoc.
getRootMetadata()
msgpack::DocNode& llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getRootMetadata (StringRef Key) inline protected
Definition at line 114 of file AMDGPUHSAMetadataStreamer.h.
References HSAMetadataDoc.
Referenced by begin(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::begin(), emitKernel(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitTargetID(), emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitVersion(), and llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitVersion().
getTypeName()
std::string llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getTypeName (Type * Ty, bool Signed) const protected
Definition at line 568 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::BitWidth, llvm::Type::DoubleTyID, llvm::Type::FixedVectorTyID, llvm::Type::FloatTyID, llvm::Type::getIntegerBitWidth(), llvm::Type::getTypeID(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, and Signed.
getValueKind()
StringRef llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getValueKind (Type * Ty, StringRef TypeQual, StringRef BaseTypeName) const protected
Definition at line 541 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringRef::contains(), llvm::StringSwitch< T, R >::Default(), llvm::Type::getPointerAddressSpace(), and llvm::AMDGPUAS::LOCAL_ADDRESS.
getWorkGroupDimensions()
msgpack::ArrayDocNode llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getWorkGroupDimensions (MDNode * Node) const protected
Definition at line 607 of file AMDGPUHSAMetadataStreamer.cpp.
verify()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::verify (StringRef HSAMetadataString) const protected
Definition at line 490 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::errs(), llvm::msgpack::Document::fromYAML(), llvm::raw_string_ostream::str(), and llvm::msgpack::Document::toYAML().
Referenced by end().
Member Data Documentation
HSAMetadataDoc
std::unique_ptr<msgpack::Document> llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::HSAMetadataDoc protected
Initial value:
=
      std::make_unique<msgpack::Document>()
Definition at line 67 of file AMDGPUHSAMetadataStreamer.h.
Referenced by begin(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::begin(), emitKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitTargetID(), emitTo(), emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitVersion(), end(), getHSAKernelProps(), getHSAMetadataRoot(), and getRootMetadata().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp