LLVM: llvm::TimeProfilingPassesHandler Class Reference
llvm::TimeProfilingPassesHandler Class Reference
This class implements –time-trace functionality for new pass manager.
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
TimeProfilingPassesHandler ()
TimeProfilingPassesHandler (const TimeProfilingPassesHandler &)=delete
void operator= (const TimeProfilingPassesHandler &)=delete
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Detailed Description
This class implements –time-trace functionality for new pass manager.
It provides the pass-instrumentation callbacks that measure the pass execution time. They collect time tracing info by TimeProfiler.
Definition at line 441 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
TimeProfilingPassesHandler() [1/2]
TimeProfilingPassesHandler::TimeProfilingPassesHandler ()
Definition at line 1220 of file StandardInstrumentations.cpp.
TimeProfilingPassesHandler() [2/2]
llvm::TimeProfilingPassesHandler::TimeProfilingPassesHandler (const TimeProfilingPassesHandler &) delete
Member Function Documentation
operator=()
void llvm::TimeProfilingPassesHandler::operator= (const TimeProfilingPassesHandler &) delete
registerCallbacks()
void TimeProfilingPassesHandler::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 1222 of file StandardInstrumentations.cpp.
References llvm::getTimeTraceProfilerInstance(), IR, P, PIC, llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerBeforeAnalysisCallback(), and llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback().
Referenced by llvm::StandardInstrumentations::registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp