LLVM: llvm::objcopy::elf::SectionVisitor Class Reference
llvm::objcopy::elf::SectionVisitor Class Reference abstract
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
virtual ~SectionVisitor ()=default
virtual Error visit (const Section &Sec)=0
virtual Error visit (const OwnedDataSection &Sec)=0
virtual Error visit (const StringTableSection &Sec)=0
virtual Error visit (const SymbolTableSection &Sec)=0
virtual Error visit (const RelocationSection &Sec)=0
virtual Error visit (const DynamicRelocationSection &Sec)=0
virtual Error visit (const GnuDebugLinkSection &Sec)=0
virtual Error visit (const GroupSection &Sec)=0
virtual Error visit (const SectionIndexSection &Sec)=0
virtual Error visit (const CompressedSection &Sec)=0
virtual Error visit (const DecompressedSection &Sec)=0
Detailed Description
Definition at line 73 of file ELFObject.h.
Constructor & Destructor Documentation
~SectionVisitor()
virtual llvm::objcopy::elf::SectionVisitor::~SectionVisitor () virtual default
Member Function Documentation
visit() [1/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const CompressedSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::ELFSectionWriter< ELFT >.
visit() [2/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const DecompressedSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::ELFSectionWriter< ELFT >.
visit() [3/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const DynamicRelocationSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
visit() [4/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const GnuDebugLinkSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::ELFSectionWriter< ELFT >.
visit() [5/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const GroupSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::ELFSectionWriter< ELFT >.
visit() [6/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const OwnedDataSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
visit() [7/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const RelocationSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::ELFSectionWriter< ELFT >.
visit() [8/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const Section & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
Referenced by llvm::objcopy::elf::Section::accept(), llvm::objcopy::elf::OwnedDataSection::accept(), llvm::objcopy::elf::CompressedSection::accept(), llvm::objcopy::elf::DecompressedSection::accept(), llvm::objcopy::elf::StringTableSection::accept(), llvm::objcopy::elf::SectionIndexSection::accept(), llvm::objcopy::elf::SymbolTableSection::accept(), llvm::objcopy::elf::RelocationSection::accept(), llvm::objcopy::elf::GroupSection::accept(), llvm::objcopy::elf::DynamicRelocationSection::accept(), and llvm::objcopy::elf::GnuDebugLinkSection::accept().
visit() [9/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const SectionIndexSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::ELFSectionWriter< ELFT >.
visit() [10/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const StringTableSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::IHexSectionWriter, llvm::objcopy::elf::IHexSectionWriterBase, and llvm::objcopy::elf::SectionWriter.
visit() [11/11]
virtual Error llvm::objcopy::elf::SectionVisitor::visit (const SymbolTableSection & Sec) pure virtual
Implemented in llvm::objcopy::elf::SectionWriter, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::ELFSectionWriter< ELFT >.
The documentation for this class was generated from the following file:
lib/ObjCopy/ELF/ELFObject.h