LLVM: llvm::DataFlowSanitizerPass Class Reference
llvm::DataFlowSanitizerPass Class Reference
#include "llvm/Transforms/Instrumentation/DataFlowSanitizer.h"
Public Member Functions
DataFlowSanitizerPass (const std::vector< std::string > &ABIListFiles=std::vector< std::string >())
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< DataFlowSanitizerPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< DataFlowSanitizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 18 of file DataFlowSanitizer.h.
Constructor & Destructor Documentation
DataFlowSanitizerPass()
llvm::DataFlowSanitizerPass::DataFlowSanitizerPass (const std::vector< std::string > & ABIListFiles = std::vector<std::string>()) inline
Definition at line 23 of file DataFlowSanitizer.h.
Member Function Documentation
isRequired()
static bool llvm::DataFlowSanitizerPass::isRequired () inline static
Definition at line 27 of file DataFlowSanitizer.h.
run()
PreservedAnalyses DataFlowSanitizerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 3470 of file DataFlowSanitizer.cpp.
References llvm::PreservedAnalyses::abandon(), llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), M, and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/DataFlowSanitizer.h
lib/Transforms/Instrumentation/DataFlowSanitizer.cpp