LLVM: llvm::ARMBlockPlacement Class Reference
llvm::ARMBlockPlacement Class Reference
Public Member Functions
ARMBlockPlacement ()
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void moveBasicBlock (MachineBasicBlock *BB, MachineBasicBlock *Before)
bool blockIsBefore (MachineBasicBlock *BB, MachineBasicBlock *Other)
bool fixBackwardsWLS (MachineLoop *ML)
Checks if loop has a backwards branching WLS, and if possible, fixes it.
bool processPostOrderLoops (MachineLoop *ML)
Updates ordering (of WLS BB and their loopExits) in inner loops first Returns true if any change was made in any of the loops.
bool revertWhileToDoLoop (MachineInstr *WLS)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 30 of file ARMBlockPlacement.cpp.
Constructor & Destructor Documentation
ARMBlockPlacement()
llvm::ARMBlockPlacement::ARMBlockPlacement () inline
Definition at line 40 of file ARMBlockPlacement.cpp.
Member Function Documentation
blockIsBefore()
bool ARMBlockPlacement::blockIsBefore (MachineBasicBlock * BB, MachineBasicBlock * Other)
Definition at line 240 of file ARMBlockPlacement.cpp.
References BB, and Other.
Referenced by fixBackwardsWLS().
fixBackwardsWLS()
bool ARMBlockPlacement::fixBackwardsWLS (MachineLoop * ML)
Checks if loop has a backwards branching WLS, and if possible, fixes it.
This requires checking the predecessor (ie. preheader or it's predecessor) for a WLS and if its loopExit/target is before it. If moving the predecessor won't convert a WLS (to the predecessor) from a forward to a backward branching WLS, then move the predecessor block to before the loopExit/target.
Definition at line 154 of file ARMBlockPlacement.cpp.
References blockIsBefore(), llvm::dbgs(), DEBUG_PREFIX, findWLS(), llvm::MachineBasicBlock::getFullName(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getParent(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::getWhileLoopStartTargetBB(), llvm::isWhileLoopStart(), LLVM_DEBUG, MBB, ML, moveBasicBlock(), llvm::MCID::Terminator, and llvm::MachineBasicBlock::terminators().
Referenced by processPostOrderLoops().
getAnalysisUsage()
void llvm::ARMBlockPlacement::getAnalysisUsage (AnalysisUsage & AU) const inline override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 49 of file ARMBlockPlacement.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::MachineFunctionPass::getAnalysisUsage().
moveBasicBlock()
void ARMBlockPlacement::moveBasicBlock (MachineBasicBlock * BB, MachineBasicBlock * Before)
Definition at line 246 of file ARMBlockPlacement.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::AArch64CC::AL, assert(), BB, llvm::BuildMI(), llvm::dbgs(), DEBUG_PREFIX, F, From, llvm::MachineInstrBuilder::getInstr(), llvm::MachineBasicBlock::getName(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::isIndirectBranchOpcode(), llvm::isJumpTableBranchOpcode(), llvm::ARMBaseInstrInfo::isPredicated(), llvm::MachineBasicBlock::isSuccessor(), llvm::isUncondBranchOpcode(), LLVM_DEBUG, and llvm::MCID::Terminator.
Referenced by fixBackwardsWLS().
processPostOrderLoops()
bool ARMBlockPlacement::processPostOrderLoops (MachineLoop * ML)
Updates ordering (of WLS BB and their loopExits) in inner loops first Returns true if any change was made in any of the loops.
Definition at line 206 of file ARMBlockPlacement.cpp.
References fixBackwardsWLS(), and ML.
Referenced by runOnMachineFunction().
revertWhileToDoLoop()
bool ARMBlockPlacement::revertWhileToDoLoop (MachineInstr * WLS)
Definition at line 90 of file ARMBlockPlacement.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::MachineBasicBlock::back(), llvm::BuildMI(), llvm::computeAndAddLiveIns(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::dbgs(), DEBUG_PREFIX, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineOperand::getImm(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::insert(), llvm::MachineBasicBlock::insert(), LLVM_DEBUG, llvm::MachineInstr::removeFromParent(), llvm::MachineFunction::RenumberBlocks(), llvm::MachineBasicBlock::replaceSuccessor(), llvm::RevertWhileLoopStartLR(), and llvm::ARMISD::WLS.
Referenced by runOnMachineFunction().
runOnMachineFunction()
bool ARMBlockPlacement::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 213 of file ARMBlockPlacement.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), DEBUG_PREFIX, llvm::MachineFunction::front(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getName(), llvm::MachineFunction::getSubtarget(), LLVM_DEBUG, ML, processPostOrderLoops(), llvm::MachineFunction::RenumberBlocks(), revertWhileToDoLoop(), llvm::FunctionPass::skipFunction(), and llvm::ARM_MB::ST.
Member Data Documentation
ID
char ARMBlockPlacement::ID = 0 static
Definition at line 39 of file ARMBlockPlacement.cpp.
The documentation for this class was generated from the following file:
lib/Target/ARM/ARMBlockPlacement.cpp