LLVM: QualType Class Reference
QualType Class Reference final
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
QualType (const Node *Child_, Qualifiers Quals_)
Qualifiers getQuals () const
const Node * getChild () const
template<typename Fn >
void match (Fn F) const
bool hasRHSComponentSlow (OutputBuffer &OB) const override
bool hasArraySlow (OutputBuffer &OB) const override
bool hasFunctionSlow (OutputBuffer &OB) const override
void printLeft (OutputBuffer &OB) const override
void printRight (OutputBuffer &OB) const override
Public Member Functions inherited from Node
Node (Kind K_, Prec Precedence_=Prec::Primary, Cache RHSComponentCache_=Cache::No, Cache ArrayCache_=Cache::No, Cache FunctionCache_=Cache::No)
Node (Kind K_, Cache RHSComponentCache_, Cache ArrayCache_=Cache::No, Cache FunctionCache_=Cache::No)
template<typename Fn >
void visit (Fn F) const
Visit the most-derived object corresponding to this object.
bool hasRHSComponent (OutputBuffer &OB) const
bool hasArray (OutputBuffer &OB) const
bool hasFunction (OutputBuffer &OB) const
Kind getKind () const
Prec getPrecedence () const
virtual const Node * getSyntaxNode (OutputBuffer &) const
void printAsOperand (OutputBuffer &OB, Prec P=Prec::Default, bool StrictlyWorse=false) const
void print (OutputBuffer &OB) const
virtual StringView getBaseName () const
virtual ~Node ()=default
DEMANGLE_DUMP_METHOD void dump () const
Protected Member Functions
void printQuals (OutputBuffer &OB) const
Protected Attributes
const Qualifiers Quals
const Node * Child
Additional Inherited Members
Public Types inherited from Node
enum Kind : unsigned char
enum Cache : unsigned char { Cache::Yes, Cache::No, Cache::Unknown }
Three-way bool to track a cached value.
enum Prec {
Prec::Primary, Prec::Postfix, Prec::Unary, Prec::Cast,
Prec::PtrMem, Prec::Multiplicative, Prec::Additive, Prec::Shift,
Prec::Spaceship, Prec::Relational, Prec::Equality, Prec::And,
Prec::Xor, Prec::Ior, Prec::AndIf, Prec::OrIf,
Prec::Conditional, Prec::Assign, Prec::Comma, Prec::Default
}
Operator precedence for expression nodes.
Public Attributes inherited from Node
Cache RHSComponentCache: 2
Tracks if this node has a component on its right side, in which case we need to call printRight.
Cache ArrayCache: 2
Track if this node is a (possibly qualified) array type.
Cache FunctionCache: 2
Track if this node is a (possibly qualified) function type.
Detailed Description
Definition at line 405 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
QualType()
QualType::QualType (const Node * Child_, Qualifiers Quals_) inline
Definition at line 420 of file ItaniumDemangle.h.
Member Function Documentation
getChild()
const Node* QualType::getChild () const inline
Definition at line 426 of file ItaniumDemangle.h.
References Child.
getQuals()
Qualifiers QualType::getQuals () const inline
Definition at line 425 of file ItaniumDemangle.h.
References Quals.
hasArraySlow()
bool QualType::hasArraySlow (OutputBuffer & OB) const inline override virtual
Reimplemented from Node.
Definition at line 433 of file ItaniumDemangle.h.
References Child, Node::hasArray(), and llvm::X86II::OB.
hasFunctionSlow()
bool QualType::hasFunctionSlow (OutputBuffer & OB) const inline override virtual
Reimplemented from Node.
Definition at line 436 of file ItaniumDemangle.h.
References Child, Node::hasFunction(), and llvm::X86II::OB.
hasRHSComponentSlow()
bool QualType::hasRHSComponentSlow (OutputBuffer & OB) const inline override virtual
Reimplemented from Node.
Definition at line 430 of file ItaniumDemangle.h.
References Child, Node::hasRHSComponent(), and llvm::X86II::OB.
match()
template<typename Fn > void QualType::match (Fn F) const inline
Definition at line 428 of file ItaniumDemangle.h.
References Child, F, and Quals.
printLeft()
void QualType::printLeft (OutputBuffer & OB) const inline override virtual
Implements Node.
Definition at line 440 of file ItaniumDemangle.h.
References Child, llvm::X86II::OB, Node::printLeft(), and printQuals().
printQuals()
void QualType::printQuals (OutputBuffer & OB) const inline protected
Definition at line 410 of file ItaniumDemangle.h.
References llvm::X86II::OB, QualConst, QualRestrict, Quals, and QualVolatile.
Referenced by printLeft().
printRight()
void QualType::printRight (OutputBuffer & OB) const inline override virtual
Reimplemented from Node.
Definition at line 445 of file ItaniumDemangle.h.
References Child, llvm::X86II::OB, and Node::printRight().
Member Data Documentation
Child
const Node* QualType::Child protected
Definition at line 408 of file ItaniumDemangle.h.
Referenced by getChild(), hasArraySlow(), hasFunctionSlow(), hasRHSComponentSlow(), match(), printLeft(), and printRight().
Quals
const Qualifiers QualType::Quals protected
Definition at line 407 of file ItaniumDemangle.h.
Referenced by getQuals(), match(), and printQuals().
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h