LLVM: llvm::VPBasicBlock Class Reference
llvm::VPBasicBlock Class Reference
VPBasicBlock serves as the leaf of the Hierarchical Control-Flow Graph.
#include "Transforms/Vectorize/VPlan.h"
Public Types
using RecipeListTy = iplist< VPRecipeBase >
using iterator = RecipeListTy::iterator
Instruction iterators...
using const_iterator = RecipeListTy::const_iterator
using reverse_iterator = RecipeListTy::reverse_iterator
using const_reverse_iterator = RecipeListTy::const_reverse_iterator
Public Types inherited from llvm::VPBlockBase
using VPBlockTy = enum { VPBasicBlockSC, VPRegionBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
using VPBlocksTy = SmallVectorImpl< VPBlockBase * >
Public Member Functions
VPBasicBlock (const Twine &Name="", VPRecipeBase *Recipe=nullptr)
~VPBasicBlock () override
iterator begin ()
Recipe iterator methods.
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
const VPRecipeBase & front () const
VPRecipeBase & front ()
const VPRecipeBase & back () const
VPRecipeBase & back ()
RecipeListTy & getRecipeList ()
Returns a reference to the list of recipes.
void insert (VPRecipeBase *Recipe, iterator InsertPt)
void appendRecipe (VPRecipeBase *Recipe)
Augment the existing recipes of a VPBasicBlock with an additional Recipe as the last recipe.
void execute (VPTransformState *State) override
The method which generates the output IR instructions that correspond to this VPBasicBlock, thereby "executing" the VPlan.
iterator getFirstNonPhi ()
Return the position of the first non-phi node recipe in the block.
iterator_range< iterator > phis ()
Returns an iterator range over the PHI-like recipes in the block.
void dropAllReferences (VPValue *NewValue) override
Replace all operands of VPUsers in the block with NewValue and also replaces all uses of VPValues defined in the block with NewValue.
VPBasicBlock * splitAt (iterator SplitAt)
Split current block at SplitAt by inserting a new block between the current block and its successors and moving all recipes starting at SplitAt to the new block.
VPRegionBlock * getEnclosingLoopRegion ()
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print this VPBsicBlock to O, prefixing all lines with Indent.
VPRecipeBase * getTerminator ()
If the block has multiple successors, return the branch recipe terminating the block.
const VPRecipeBase * getTerminator () const
bool isExiting () const
Returns true if the block is exiting it's parent region.
virtual void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const=0
Print plain-text dump of this VPBlockBase to O, prefixing all lines with Indent.
void print (raw_ostream &O) const
Print plain-text dump of this VPlan to O.
Public Member Functions inherited from llvm::VPBlockBase
virtual ~VPBlockBase ()=default
const std::string & getName () const
void setName (const Twine &newName)
unsigned getVPBlockID () const
VPRegionBlock * getParent ()
const VPRegionBlock * getParent () const
VPlan * getPlan ()
const VPlan * getPlan () const
void setPlan (VPlan *ParentPlan)
Sets the pointer of the plan containing the block.
void setParent (VPRegionBlock *P)
const VPBasicBlock * getEntryBasicBlock () const
VPBasicBlock * getEntryBasicBlock ()
const VPBasicBlock * getExitingBasicBlock () const
VPBasicBlock * getExitingBasicBlock ()
const VPBlocksTy & getSuccessors () const
VPBlocksTy & getSuccessors ()
iterator_range< VPBlockBase ** > successors ()
const VPBlocksTy & getPredecessors () const
VPBlocksTy & getPredecessors ()
VPBlockBase * getSingleSuccessor () const
VPBlockBase * getSinglePredecessor () const
size_t getNumSuccessors () const
size_t getNumPredecessors () const
VPBlockBase * getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
VPBlockBase * getEnclosingBlockWithPredecessors ()
const VPBlocksTy & getHierarchicalSuccessors ()
VPBlockBase * getSingleHierarchicalSuccessor ()
const VPBlocksTy & getHierarchicalPredecessors ()
VPBlockBase * getSingleHierarchicalPredecessor ()
void setOneSuccessor (VPBlockBase *Successor)
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
void setTwoSuccessors (VPBlockBase *IfTrue, VPBlockBase *IfFalse)
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
void setPredecessors (ArrayRef< VPBlockBase * > NewPreds)
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
void clearPredecessors ()
Remove all the predecessor of this block.
void clearSuccessors ()
Remove all the successors of this block.
bool isLegalToHoistInto ()
Return true if it is legal to hoist instructions into this block.
void printAsOperand (raw_ostream &OS, bool PrintType) const
void print (raw_ostream &O) const
Print plain-text dump of this VPlan to O.
void printSuccessors (raw_ostream &O, const Twine &Indent) const
Print the successors of this block to O, prefixing all lines with Indent.
LLVM_DUMP_METHOD void dump () const
Dump this VPBlockBase to dbgs().
Static Public Member Functions
static RecipeListTy VPBasicBlock::* getSublistAccess (VPRecipeBase *)
Returns a pointer to a member of the recipe list.
static bool classof (const VPBlockBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::VPBlockBase
static void deleteCFG (VPBlockBase *Entry)
Delete all blocks reachable from a given VPBlockBase, inclusive.
Additional Inherited Members
Protected Member Functions inherited from llvm::VPBlockBase
VPBlockBase (const unsigned char SC, const std::string &N)
Detailed Description
VPBasicBlock serves as the leaf of the Hierarchical Control-Flow Graph.
It holds a sequence of zero or more VPRecipe's each representing a sequence of output IR instructions. All PHI-like recipes must come before any non-PHI recipes.
Definition at line 1945 of file VPlan.h.
Member Typedef Documentation
const_iterator
using llvm::VPBasicBlock::const_iterator = RecipeListTy::const_iterator
Definition at line 1967 of file VPlan.h.
const_reverse_iterator
using llvm::VPBasicBlock::const_reverse_iterator = RecipeListTy::const_reverse_iterator
Definition at line 1969 of file VPlan.h.
iterator
using llvm::VPBasicBlock::iterator = RecipeListTy::iterator
Instruction iterators...
Definition at line 1966 of file VPlan.h.
RecipeListTy
using llvm::VPBasicBlock::RecipeListTy = iplist<VPRecipeBase>
Definition at line 1947 of file VPlan.h.
reverse_iterator
using llvm::VPBasicBlock::reverse_iterator = RecipeListTy::reverse_iterator
Definition at line 1968 of file VPlan.h.
Constructor & Destructor Documentation
VPBasicBlock()
llvm::VPBasicBlock::VPBasicBlock (const Twine & Name = "", VPRecipeBase * Recipe = nullptr) inline
Definition at line 1954 of file VPlan.h.
References appendRecipe().
~VPBasicBlock()
llvm::VPBasicBlock::~VPBasicBlock () inline override
Definition at line 1960 of file VPlan.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::pop_back().
Member Function Documentation
appendRecipe()
void llvm::VPBasicBlock::appendRecipe (VPRecipeBase * Recipe) inline
Augment the existing recipes of a VPBasicBlock with an additional Recipe as the last recipe.
Definition at line 2013 of file VPlan.h.
References end(), and insert().
Referenced by addCanonicalIVRecipes(), llvm::vputils::getOrCreateVPValueForSCEVExpr(), llvm::VPRecipeBuilder::handleReplication(), llvm::VPlanTransforms::optimizeForVFAndUF(), and VPBasicBlock().
back() [1/2]
VPRecipeBase& llvm::VPBasicBlock::back () inline
Definition at line 1989 of file VPlan.h.
back() [2/2]
const VPRecipeBase& llvm::VPBasicBlock::back () const inline
Definition at line 1988 of file VPlan.h.
Referenced by hasConditionalTerminator(), and llvm::VPlanTransforms::optimizeForVFAndUF().
begin() [1/2]
iterator llvm::VPBasicBlock::begin () inline
Recipe iterator methods.
Definition at line 1974 of file VPlan.h.
Referenced by llvm::VPlan::getCanonicalIV(), getFirstNonPhi(), phis(), and verifyPhiRecipes().
begin() [2/2]
const_iterator llvm::VPBasicBlock::begin () const inline
Definition at line 1975 of file VPlan.h.
classof()
static bool llvm::VPBasicBlock::classof (const VPBlockBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 2000 of file VPlan.h.
References llvm::VPBlockBase::getVPBlockID().
dropAllReferences()
void VPBasicBlock::dropAllReferences (VPValue * NewValue) override virtual
Replace all operands of VPUsers in the block with NewValue and also replaces all uses of VPValues defined in the block with NewValue.
Implements llvm::VPBlockBase.
Definition at line 392 of file VPlan.cpp.
References llvm::tgtok::Def, E, and I.
empty()
bool llvm::VPBasicBlock::empty () const inline
Definition at line 1985 of file VPlan.h.
Referenced by llvm::VPlan::getCanonicalIV(), and hasConditionalTerminator().
end() [1/2]
iterator llvm::VPBasicBlock::end () inline
Definition at line 1976 of file VPlan.h.
Referenced by appendRecipe(), getFirstNonPhi(), and llvm::VPlanTransforms::mergeBlocksIntoPredecessors().
end() [2/2]
const_iterator llvm::VPBasicBlock::end () const inline
Definition at line 1977 of file VPlan.h.
execute()
void VPBasicBlock::execute (VPTransformState * State) override virtual
The method which generates the output IR instructions that correspond to this VPBasicBlock, thereby "executing" the VPlan.
Implements llvm::VPBlockBase.
Definition at line 325 of file VPlan.cpp.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), assert(), BB, llvm::VPTransformState::Builder, llvm::VPTransformState::CFG, llvm::IRBuilderBase::CreateUnreachable(), llvm::VPTransformState::CurrentVectorLoop, llvm::dbgs(), execute(), llvm::VPTransformState::CFGState::ExitBB, llvm::VPBlockBase::getExitingBasicBlock(), getName(), llvm::Value::getName(), llvm::VPBlockBase::getParent(), llvm::VPBlockBase::getSingleHierarchicalSuccessor(), llvm::VPBlockBase::getSingleSuccessor(), llvm::BasicBlock::getTerminator(), llvm::VPTransformState::Instance, llvm::VPTransformState::LI, LLVM_DEBUG, llvm::VPTransformState::CFGState::PrevBB, llvm::VPTransformState::CFGState::PrevVPBB, llvm::IRBuilderBase::SetInsertPoint(), llvm::MCID::Terminator, and llvm::VPTransformState::CFGState::VPBB2IRBB.
Referenced by execute().
front() [1/2]
VPRecipeBase& llvm::VPBasicBlock::front () inline
Definition at line 1987 of file VPlan.h.
front() [2/2]
const VPRecipeBase& llvm::VPBasicBlock::front () const inline
Definition at line 1986 of file VPlan.h.
getEnclosingLoopRegion()
VPRegionBlock * VPBasicBlock::getEnclosingLoopRegion ()
Definition at line 427 of file VPlan.cpp.
References assert(), getParent(), and P.
Referenced by llvm::VPWidenPHIRecipe::execute(), and llvm::InnerLoopVectorizer::fixReduction().
getFirstNonPhi()
VPBasicBlock::iterator VPBasicBlock::getFirstNonPhi ()
Return the position of the first non-phi node recipe in the block.
Definition at line 207 of file VPlan.cpp.
References begin(), and end().
Referenced by llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::VPlanTransforms::mergeReplicateRegionsIntoSuccessors(), llvm::VPlanTransforms::optimizeInductions(), phis(), sinkRecurrenceUsersAfterPrevious(), and llvm::VPlanTransforms::sinkScalarOperands().
getRecipeList()
RecipeListTy& llvm::VPBasicBlock::getRecipeList () inline
Returns a reference to the list of recipes.
Definition at line 1992 of file VPlan.h.
Referenced by llvm::VPRecipeBase::eraseFromParent(), llvm::VPRecipeBase::insertAfter(), llvm::VPRecipeBase::insertBefore(), and llvm::VPRecipeBase::removeFromParent().
getSublistAccess()
static RecipeListTy VPBasicBlock::* llvm::VPBasicBlock::getSublistAccess (VPRecipeBase *) inline static
Returns a pointer to a member of the recipe list.
Definition at line 1995 of file VPlan.h.
getTerminator() [1/2]
const VPRecipeBase * VPBasicBlock::getTerminator ()
If the block has multiple successors, return the branch recipe terminating the block.
If there are no or only a single successor, return nullptr;
Definition at line 466 of file VPlan.cpp.
References hasConditionalTerminator().
getTerminator() [2/2]
const VPRecipeBase* llvm::VPBasicBlock::getTerminator () const
insert()
void llvm::VPBasicBlock::insert (VPRecipeBase * Recipe, iterator InsertPt) inline
Definition at line 2004 of file VPlan.h.
References assert(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
Referenced by appendRecipe(), llvm::VPRecipeBuilder::createBlockInMask(), and llvm::VPlanTransforms::optimizeInductions().
isExiting()
bool VPBasicBlock::isExiting () const
Returns true if the block is exiting it's parent region.
Definition at line 478 of file VPlan.cpp.
References getParent().
Referenced by hasConditionalTerminator().
phis()
iterator_range<iterator> llvm::VPBasicBlock::phis () inline
Returns an iterator range over the PHI-like recipes in the block.
Definition at line 2023 of file VPlan.h.
References begin(), getFirstNonPhi(), and llvm::make_range().
Referenced by llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPlanTransforms::optimizeInductions(), llvm::VPlanTransforms::removeRedundantCanonicalIVs(), and llvm::VPlanTransforms::removeRedundantInductionCasts().
print() [1/3]
void llvm::VPBlockBase::print inline
Print plain-text dump of this VPlan to O.
Definition at line 619 of file VPlan.h.
print() [2/3]
void VPBasicBlock::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print this VPBsicBlock to O, prefixing all lines with Indent.
SlotTracker is used to print unnamed VPValue's using consequtive numbers.
Note that the numbering is applied to the whole VPlan, so printing individual blocks is consistent with the whole VPlan printing.
Implements llvm::VPBlockBase.
Definition at line 495 of file VPlan.cpp.
References getName(), llvm::RISCVFenceField::O, and llvm::VPDef::print().
print() [3/3]
virtual void llvm::VPBlockBase::print
Print plain-text dump of this VPBlockBase to O, prefixing all lines with Indent.
SlotTracker is used to print unnamed VPValue's using consequtive numbers.
Note that the numbering is applied to the whole VPlan, so printing individual blocks is consistent with the whole VPlan printing.
rbegin() [1/2]
reverse_iterator llvm::VPBasicBlock::rbegin () inline
Definition at line 1979 of file VPlan.h.
rbegin() [2/2]
const_reverse_iterator llvm::VPBasicBlock::rbegin () const inline
Definition at line 1980 of file VPlan.h.
rend() [1/2]
reverse_iterator llvm::VPBasicBlock::rend () inline
Definition at line 1981 of file VPlan.h.
rend() [2/2]
const_reverse_iterator llvm::VPBasicBlock::rend () const inline
Definition at line 1982 of file VPlan.h.
size()
size_t llvm::VPBasicBlock::size () const inline
Definition at line 1984 of file VPlan.h.
splitAt()
VPBasicBlock * VPBasicBlock::splitAt (iterator SplitAt)
Split current block at SplitAt by inserting a new block between the current block and its successors and moving all recipes starting at SplitAt to the new block.
Returns the new block.
Definition at line 402 of file VPlan.cpp.
References assert(), llvm::VPBlockUtils::connectBlocks(), llvm::VPBlockUtils::disconnectBlocks(), llvm::sys::path::end(), llvm::BasicBlock::end(), getName(), llvm::VPBlockUtils::insertBlockAfter(), llvm::make_early_inc_range(), llvm::make_range(), llvm::SplitBlock(), and llvm::successors().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp