LLVM: llvm::memprof::RawMemProfReader Class Reference
llvm::memprof::RawMemProfReader Class Reference
#include "llvm/ProfileData/RawMemProfReader.h"
Public Types
using GuidMemProfRecordPair = std::pair< GlobalValue::GUID, MemProfRecord >
using Iterator = InstrProfIterator< GuidMemProfRecordPair, RawMemProfReader >
Public Member Functions
RawMemProfReader (const RawMemProfReader &)=delete
RawMemProfReader & operator= (const RawMemProfReader &)=delete
void printYAML (raw_ostream &OS)
Iterator end ()
Iterator begin ()
Error readNextRecord (GuidMemProfRecordPair &GuidRecord)
InstrProfKind getProfileKind () const
RawMemProfReader (std::unique_ptr< llvm::symbolize::SymbolizableModule > Sym, llvm::SmallVectorImpl< SegmentEntry > &Seg, llvm::MapVector< uint64_t, MemInfoBlock > &Prof, CallStackMap &SM, bool KeepName=false)
const llvm::DenseMap< FrameId, Frame > & getFrameMapping () const
const llvm::MapVector< GlobalValue::GUID, IndexedMemProfRecord > & getProfileData () const
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &DataBuffer)
static bool hasFormat (const StringRef Path)
static Expected< std::unique_ptr< RawMemProfReader > > create (const Twine &Path, const StringRef ProfiledBinary, bool KeepName=false)
Detailed Description
Definition at line 38 of file RawMemProfReader.h.
Member Typedef Documentation
GuidMemProfRecordPair
using llvm::memprof::RawMemProfReader::GuidMemProfRecordPair = std::pair<GlobalValue::GUID, MemProfRecord>
Definition at line 60 of file RawMemProfReader.h.
Iterator
using llvm::memprof::RawMemProfReader::Iterator = InstrProfIterator<GuidMemProfRecordPair, RawMemProfReader>
Definition at line 61 of file RawMemProfReader.h.
Constructor & Destructor Documentation
RawMemProfReader() [1/2]
llvm::memprof::RawMemProfReader::RawMemProfReader (const RawMemProfReader &) delete
Referenced by create().
RawMemProfReader() [2/2]
llvm::memprof::RawMemProfReader::RawMemProfReader (std::unique_ptr< llvm::symbolize::SymbolizableModule > Sym, llvm::SmallVectorImpl< SegmentEntry > & Seg, llvm::MapVector< uint64_t, MemInfoBlock > & Prof, CallStackMap & SM, bool KeepName = false) inline
Definition at line 74 of file RawMemProfReader.h.
References E, move, and llvm::report_fatal_error().
Member Function Documentation
begin()
Iterator llvm::memprof::RawMemProfReader::begin () inline
Definition at line 63 of file RawMemProfReader.h.
create()
Expected< std::unique_ptr< RawMemProfReader > > llvm::memprof::RawMemProfReader::create (const Twine & Path, const StringRef ProfiledBinary, bool KeepName = false) static
Definition at line 173 of file RawMemProfReader.cpp.
References llvm::object::createBinary(), E, llvm::StringRef::empty(), llvm::errorCodeToError(), llvm::MemoryBuffer::getFileOrSTDIN(), llvm::make_error_code(), move, and RawMemProfReader().
end()
Iterator llvm::memprof::RawMemProfReader::end () inline
Definition at line 62 of file RawMemProfReader.h.
getFrameMapping()
const llvm::DenseMap<FrameId, Frame>& llvm::memprof::RawMemProfReader::getFrameMapping () const inline
Definition at line 92 of file RawMemProfReader.h.
getProfileData()
const llvm::MapVector<GlobalValue::GUID, IndexedMemProfRecord>& llvm::memprof::RawMemProfReader::getProfileData () const inline
Definition at line 98 of file RawMemProfReader.h.
getProfileKind()
InstrProfKind llvm::memprof::RawMemProfReader::getProfileKind () const inline
Definition at line 71 of file RawMemProfReader.h.
References llvm::MemProf.
hasFormat() [1/2]
bool llvm::memprof::RawMemProfReader::hasFormat (const MemoryBuffer & DataBuffer) static
Definition at line 211 of file RawMemProfReader.cpp.
References llvm::MemoryBuffer::getBufferSize(), llvm::MemoryBuffer::getBufferStart(), llvm::msf::Magic, and uint64_t.
Referenced by hasFormat().
hasFormat() [2/2]
bool llvm::memprof::RawMemProfReader::hasFormat (const StringRef Path) static
Definition at line 202 of file RawMemProfReader.cpp.
References llvm::MemoryBuffer::getFileOrSTDIN(), and hasFormat().
operator=()
RawMemProfReader& llvm::memprof::RawMemProfReader::operator= (const RawMemProfReader &) delete
printYAML()
void llvm::memprof::RawMemProfReader::printYAML (raw_ostream & OS)
Definition at line 220 of file RawMemProfReader.cpp.
References OS, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), and uint64_t.
readNextRecord()
Error llvm::memprof::RawMemProfReader::readNextRecord (GuidMemProfRecordPair & GuidRecord)
Definition at line 534 of file RawMemProfReader.cpp.
References assert(), llvm::empty_raw_profile, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::eof, F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/RawMemProfReader.h
lib/ProfileData/RawMemProfReader.cpp