LLVM: llvm::VPSlotTracker Class Reference
llvm::VPSlotTracker Class Reference
This class can be used to assign consecutive numbers to all VPValues in a VPlan and allows querying the numbering for printing, similar to the ModuleSlotTracker for IR values.
#include "Transforms/Vectorize/VPlanValue.h"
Public Member Functions
VPSlotTracker (const VPlan *Plan=nullptr)
unsigned getSlot (const VPValue *V) const
Detailed Description
This class can be used to assign consecutive numbers to all VPValues in a VPlan and allows querying the numbering for printing, similar to the ModuleSlotTracker for IR values.
Definition at line 431 of file VPlanValue.h.
Constructor & Destructor Documentation
VPSlotTracker()
llvm::VPSlotTracker::VPSlotTracker (const VPlan * Plan = nullptr) inline
Definition at line 439 of file VPlanValue.h.
Member Function Documentation
getSlot()
unsigned llvm::VPSlotTracker::getSlot (const VPValue * V) const inline
Definition at line 444 of file VPlanValue.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), and I.
Referenced by llvm::VPValue::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlanValue.h
lib/Transforms/Vectorize/VPlan.cpp