LLVM: llvm::CSKYConstantPoolValue Class Reference
llvm::CSKYConstantPoolValue Class Reference
CSKYConstantPoolValue - CSKY specific constantpool value.
#include "Target/CSKY/CSKYConstantPoolValue.h"
Public Member Functions
const char * getModifierText () const
unsigned getPCAdjustment () const
bool mustAddCurrentAddress () const
CSKYCP::CSKYCPModifier getModifier () const
unsigned getLabelID () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJT () const
bool isConstPool () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const CSKYConstantPoolValue *A) const
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Protected Member Functions
CSKYConstantPoolValue (Type *Ty, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID=0)
Protected Attributes
CSKYCP::CSKYCPKind Kind
unsigned PCAdjust
CSKYCP::CSKYCPModifier Modifier
bool AddCurrentAddress
unsigned LabelId = 0
Detailed Description
CSKYConstantPoolValue - CSKY specific constantpool value.
This is used to represent PC-relative displacement between the address of the load instruction and the constant being loaded, i.e. (&GV-(LPIC+8)).
Definition at line 46 of file CSKYConstantPoolValue.h.
Constructor & Destructor Documentation
CSKYConstantPoolValue()
CSKYConstantPoolValue::CSKYConstantPoolValue (Type * Ty, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID = 0) protected
Definition at line 27 of file CSKYConstantPoolValue.cpp.
Member Function Documentation
addSelectionDAGCSEId()
void CSKYConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Reimplemented in llvm::CSKYConstantPoolJT, llvm::CSKYConstantPoolMBB, llvm::CSKYConstantPoolSymbol, and llvm::CSKYConstantPoolConstant.
Definition at line 62 of file CSKYConstantPoolValue.cpp.
References LabelId, Modifier, and PCAdjust.
Referenced by llvm::CSKYConstantPoolConstant::addSelectionDAGCSEId(), llvm::CSKYConstantPoolSymbol::addSelectionDAGCSEId(), llvm::CSKYConstantPoolMBB::addSelectionDAGCSEId(), and llvm::CSKYConstantPoolJT::addSelectionDAGCSEId().
equals()
bool llvm::CSKYConstantPoolValue::equals (const CSKYConstantPoolValue * A) const inline
Definition at line 82 of file CSKYConstantPoolValue.h.
Referenced by llvm::CSKYConstantPoolConstant::equals(), llvm::CSKYConstantPoolSymbol::equals(), llvm::CSKYConstantPoolMBB::equals(), and llvm::CSKYConstantPoolJT::equals().
getExistingMachineCPValue()
int CSKYConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Reimplemented in llvm::CSKYConstantPoolJT, llvm::CSKYConstantPoolMBB, llvm::CSKYConstantPoolSymbol, and llvm::CSKYConstantPoolConstant.
Definition at line 57 of file CSKYConstantPoolValue.cpp.
References llvm_unreachable.
getExistingMachineCPValueImpl()
template<typename Derived > int llvm::CSKYConstantPoolValue::getExistingMachineCPValueImpl (MachineConstantPool * CP, Align Alignment) inline
Definition at line 88 of file CSKYConstantPoolValue.h.
References llvm::HexagonISD::CP, llvm::numbers::e, llvm::getAlign(), and i.
getLabelID()
unsigned llvm::CSKYConstantPoolValue::getLabelID () const inline
Definition at line 64 of file CSKYConstantPoolValue.h.
References LabelId.
Referenced by llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
getModifier()
CSKYCP::CSKYCPModifier llvm::CSKYConstantPoolValue::getModifier () const inline
Definition at line 63 of file CSKYConstantPoolValue.h.
References Modifier.
Referenced by llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
getModifierText()
const char * CSKYConstantPoolValue::getModifierText () const
Definition at line 35 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYCP::ADDR, llvm::CSKYCP::GOT, llvm::CSKYCP::GOTOFF, llvm_unreachable, Modifier, llvm::CSKYCP::NO_MOD, llvm::CSKYCP::PLT, llvm::CSKYCP::TLSGD, llvm::CSKYCP::TLSIE, and llvm::CSKYCP::TLSLE.
Referenced by print().
getPCAdjustment()
unsigned llvm::CSKYConstantPoolValue::getPCAdjustment () const inline
Definition at line 61 of file CSKYConstantPoolValue.h.
References PCAdjust.
Referenced by llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
isBlockAddress()
bool llvm::CSKYConstantPoolValue::isBlockAddress () const inline
Definition at line 68 of file CSKYConstantPoolValue.h.
References llvm::CSKYCP::CPBlockAddress, and Kind.
Referenced by llvm::CSKYConstantPoolConstant::classof(), and llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
isConstPool()
bool llvm::CSKYConstantPoolValue::isConstPool () const inline
Definition at line 73 of file CSKYConstantPoolValue.h.
References llvm::CSKYCP::CPConstPool, and Kind.
Referenced by llvm::CSKYConstantPoolConstant::classof(), and llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
isExtSymbol()
bool llvm::CSKYConstantPoolValue::isExtSymbol () const inline
Definition at line 67 of file CSKYConstantPoolValue.h.
References llvm::CSKYCP::CPExtSymbol, and Kind.
Referenced by llvm::CSKYConstantPoolSymbol::classof(), and llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
isGlobalValue()
bool llvm::CSKYConstantPoolValue::isGlobalValue () const inline
Definition at line 66 of file CSKYConstantPoolValue.h.
References llvm::CSKYCP::CPValue, and Kind.
Referenced by llvm::CSKYConstantPoolConstant::classof(), and llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
isJT()
bool llvm::CSKYConstantPoolValue::isJT () const inline
Definition at line 72 of file CSKYConstantPoolValue.h.
References llvm::CSKYCP::CPJT, and Kind.
Referenced by llvm::CSKYConstantPoolJT::classof(), and llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
isMachineBasicBlock()
bool llvm::CSKYConstantPoolValue::isMachineBasicBlock () const inline
Definition at line 69 of file CSKYConstantPoolValue.h.
References llvm::CSKYCP::CPMachineBasicBlock, and Kind.
Referenced by llvm::CSKYConstantPoolMBB::classof(), and llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
mustAddCurrentAddress()
bool llvm::CSKYConstantPoolValue::mustAddCurrentAddress () const inline
Definition at line 62 of file CSKYConstantPoolValue.h.
References AddCurrentAddress.
Referenced by llvm::CSKYAsmPrinter::emitMachineConstantPoolValue().
print()
void CSKYConstantPoolValue::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Reimplemented in llvm::CSKYConstantPoolJT, llvm::CSKYConstantPoolMBB, llvm::CSKYConstantPoolSymbol, and llvm::CSKYConstantPoolConstant.
Definition at line 68 of file CSKYConstantPoolValue.cpp.
References getModifierText(), Modifier, llvm::RISCVFenceField::O, and PCAdjust.
Referenced by llvm::CSKYConstantPoolConstant::print(), llvm::CSKYConstantPoolSymbol::print(), llvm::CSKYConstantPoolMBB::print(), and llvm::CSKYConstantPoolJT::print().
Member Data Documentation
AddCurrentAddress
bool llvm::CSKYConstantPoolValue::AddCurrentAddress protected
Definition at line 51 of file CSKYConstantPoolValue.h.
Referenced by llvm::CSKYConstantPoolConstant::Create(), and mustAddCurrentAddress().
Kind
CSKYCP::CSKYCPKind llvm::CSKYConstantPoolValue::Kind protected
Definition at line 48 of file CSKYConstantPoolValue.h.
Referenced by llvm::CSKYConstantPoolConstant::Create(), isBlockAddress(), isConstPool(), isExtSymbol(), isGlobalValue(), isJT(), and isMachineBasicBlock().
LabelId
unsigned llvm::CSKYConstantPoolValue::LabelId = 0 protected
Definition at line 53 of file CSKYConstantPoolValue.h.
Referenced by addSelectionDAGCSEId(), and getLabelID().
Modifier
CSKYCP::CSKYCPModifier llvm::CSKYConstantPoolValue::Modifier protected
Definition at line 50 of file CSKYConstantPoolValue.h.
Referenced by addSelectionDAGCSEId(), llvm::CSKYConstantPoolConstant::Create(), llvm::CSKYConstantPoolSymbol::Create(), llvm::CSKYConstantPoolJT::Create(), getModifier(), getModifierText(), and print().
PCAdjust
unsigned llvm::CSKYConstantPoolValue::PCAdjust protected
Definition at line 49 of file CSKYConstantPoolValue.h.
Referenced by addSelectionDAGCSEId(), llvm::CSKYConstantPoolConstant::Create(), llvm::CSKYConstantPoolSymbol::Create(), llvm::CSKYConstantPoolMBB::Create(), getPCAdjustment(), and print().
The documentation for this class was generated from the following files:
lib/Target/CSKY/CSKYConstantPoolValue.h
lib/Target/CSKY/CSKYConstantPoolValue.cpp