LLVM: llvm::MCXCOFFStreamer Class Reference
llvm::MCXCOFFStreamer Class Reference
#include "llvm/MC/MCXCOFFStreamer.h"
Public Member Functions
MCXCOFFStreamer (MCContext &Context, std::unique_ptr< MCAsmBackend > MAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter)
bool emitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute) override
Add the given Attribute to Symbol.
void emitCommonSymbol (MCSymbol *Symbol, uint64_t Size, Align ByteAlignment) override
Emit a common symbol.
void emitZerofill (MCSection *Section, MCSymbol *Symbol=nullptr, uint64_t Size=0, Align ByteAlignment=Align(1), SMLoc Loc=SMLoc()) override
Emit the zerofill section and an optional symbol.
void emitInstToData (const MCInst &Inst, const MCSubtargetInfo &) override
void emitXCOFFLocalCommonSymbol (MCSymbol *LabelSym, uint64_t Size, MCSymbol *CsectSym, Align Alignment) override
Emits an lcomm directive with XCOFF csect information.
void emitXCOFFSymbolLinkageWithVisibility (MCSymbol *Symbol, MCSymbolAttr Linkage, MCSymbolAttr Visibility) override
Emit a symbol's linkage and visibility with a linkage directive for XCOFF.
void emitXCOFFRefDirective (StringRef Name) override
Emit a XCOFF .ref directive which creates R_REF type entry in the relocation table for one or more symbols.
void emitXCOFFRenameDirective (const MCSymbol *Name, StringRef Rename) override
Emit a XCOFF .rename directive which creates a synonym for an illegal or undesirable name.
void emitXCOFFExceptDirective (const MCSymbol *Symbol, const MCSymbol *Trap, unsigned Lang, unsigned Reason, unsigned FunctionSize, bool hasDebug) override
Emit an XCOFF .except directive which adds information about a trap instruction to the object file exception section.
Public Member Functions inherited from llvm::MCObjectStreamer
void reset () override
state management
bool isIntegratedAssemblerRequired () const override
Object streamers require the integrated assembler.
void emitFrames (MCAsmBackend *MAB)
void emitCFISections (bool EH, bool Debug) override
MCFragment * getCurrentFragment () const
void insert (MCFragment *F)
MCDataFragment * getOrCreateDataFragment (const MCSubtargetInfo *STI=nullptr)
Get a data fragment to write into, creating a new one if the current fragment is not a data fragment.
void visitUsedSymbol (const MCSymbol &Sym) override
void flushPendingLabels ()
Create a data fragment for any pending labels across all Sections and Subsections.
MCAssembler & getAssembler ()
MCAssembler * getAssemblerPtr () override
void emitLabel (MCSymbol *Symbol, SMLoc Loc=SMLoc()) override
Emit a label for Symbol into the current section.
virtual void emitLabelAtPos (MCSymbol *Symbol, SMLoc Loc, MCFragment *F, uint64_t Offset)
void emitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
Emit an assignment of Value to Symbol.
void emitConditionalAssignment (MCSymbol *Symbol, const MCExpr *Value) override
Emit an assignment of Value to Symbol, but only if Value is also emitted.
void emitValueImpl (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc()) override
Emit the expression Value into the output as a native integer of the given Size bytes.
void emitULEB128Value (const MCExpr *Value) override
void emitSLEB128Value (const MCExpr *Value) override
void emitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
Emit an weak reference from Alias to Symbol.
void changeSection (MCSection *Section, const MCExpr *Subsection) override
Update streamer for a new active section.
void emitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI) override
Emit the given Instruction into the current section.
virtual void emitInstToFragment (const MCInst &Inst, const MCSubtargetInfo &)
Emit an instruction to a special fragment, because this instruction can change its size during relaxation.
void emitBundleAlignMode (Align Alignment) override
Set the bundle alignment mode from now on in the section.
void emitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void emitBundleUnlock () override
Ends a bundle-locked group.
void emitBytes (StringRef Data) override
Emit the bytes in Data into the output.
void emitValueToAlignment (Align Alignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0) override
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
void emitCodeAlignment (Align ByteAlignment, const MCSubtargetInfo *STI, unsigned MaxBytesToEmit=0) override
Emit nops until the byte alignment ByteAlignment is reached.
void emitValueToOffset (const MCExpr *Offset, unsigned char Value, SMLoc Loc) override
Emit some number of copies of Value until the byte offset Offset is reached.
void emitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override
This implements the DWARF2 '.loc fileno lineno ...' assembler directive.
void emitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol *LastLabel, const MCSymbol *Label, unsigned PointerSize) override
If targets does not support representing debug line section by .loc/.file directives in assembly output, we need to populate debug line section with raw debug line contents.
void emitDwarfLineEndEntry (MCSection *Section, MCSymbol *LastLabel) override
Emit the debug line end entry.
void emitDwarfAdvanceFrameAddr (const MCSymbol *LastLabel, const MCSymbol *Label)
void emitCVLocDirective (unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt, StringRef FileName, SMLoc Loc) override
This implements the CodeView '.cv_loc' assembler directive.
void emitCVLinetableDirective (unsigned FunctionId, const MCSymbol *Begin, const MCSymbol *End) override
This implements the CodeView '.cv_linetable' assembler directive.
void emitCVInlineLinetableDirective (unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol *FnStartSym, const MCSymbol *FnEndSym) override
This implements the CodeView '.cv_inline_linetable' assembler directive.
void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, StringRef FixedSizePortion) override
This implements the CodeView '.cv_def_range' assembler directive.
void emitCVStringTableDirective () override
This implements the CodeView '.cv_stringtable' assembler directive.
void emitCVFileChecksumsDirective () override
This implements the CodeView '.cv_filechecksums' assembler directive.
void emitCVFileChecksumOffsetDirective (unsigned FileNo) override
This implements the CodeView '.cv_filechecksumoffset' assembler directive.
void emitDTPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a dtprel (32-bit DTP relative) value.
void emitDTPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a dtprel (64-bit DTP relative) value.
void emitTPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a tprel (32-bit TP relative) value.
void emitTPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a tprel (64-bit TP relative) value.
void emitGPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
void emitGPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
std::optional< std::pair< bool, std::string > > emitRelocDirective (const MCExpr &Offset, StringRef Name, const MCExpr *Expr, SMLoc Loc, const MCSubtargetInfo &STI) override
Record a relocation described by the .reloc directive.
void emitFill (const MCExpr &NumBytes, uint64_t FillValue, SMLoc Loc=SMLoc()) override
Emit Size bytes worth of the value specified by FillValue.
void emitFill (const MCExpr &NumValues, int64_t Size, int64_t Expr, SMLoc Loc=SMLoc()) override
Emit NumValues copies of Size bytes.
void emitNops (int64_t NumBytes, int64_t ControlledNopLength, SMLoc Loc, const MCSubtargetInfo &STI) override
void emitFileDirective (StringRef Filename) override
Switch to a new logical file.
void emitFileDirective (StringRef Filename, StringRef CompilerVerion, StringRef TimeStamp, StringRef Description) override
Emit ".file assembler diretive with additioal info.
void emitAddrsig () override
void emitAddrsigSym (const MCSymbol *Sym) override
void finishImpl () override
Streamer specific finalization.
void emitAbsoluteSymbolDiff (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) override
Emit the absolute difference between two symbols if possible.
void emitAbsoluteSymbolDiffAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) override
Emit the absolute difference between two symbols encoded with ULEB128.
bool mayHaveInstructions (MCSection &Sec) const override
void emitPendingAssignments (MCSymbol *Symbol)
Emits pending conditional assignments that depend on Symbol being emitted.
void emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumBytes, uint64_t FillValue, SMLoc Loc=SMLoc())
Emit Size bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumValues, int64_t Size, int64_t Expr, SMLoc Loc=SMLoc())
Emit NumValues copies of Size bytes.
Public Member Functions inherited from llvm::MCStreamer
MCStreamer (const MCStreamer &)=delete
MCStreamer & operator= (const MCStreamer &)=delete
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
void setTargetStreamer (MCTargetStreamer *TS)
void setStartTokLocPtr (const SMLoc *Loc)
SMLoc getStartTokLoc () const
MCContext & getContext () const
void setUseAssemblerInfoForParsing (bool v)
bool getUseAssemblerInfoForParsing ()
MCTargetStreamer * getTargetStreamer ()
void setAllowAutoPadding (bool v)
bool getAllowAutoPadding () const
WinEH::FrameInfo * EnsureValidWinFrameInfo (SMLoc Loc)
Retrieve the current frame info if one is available and it is not yet closed.
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
bool hasUnfinishedDwarfFrameInfo ()
unsigned getNumWinFrameInfos ()
ArrayRef< std::unique_ptr< WinEH::FrameInfo > > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
virtual void emitIdent (StringRef IdentString)
Emit the "identifiers" directive.
unsigned emitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, std::optional< MD5::MD5Result > Checksum=std::nullopt, std::optional< StringRef > Source=std::nullopt, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual Expected< unsigned > tryEmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, std::optional< MD5::MD5Result > Checksum=std::nullopt, std::optional< StringRef > Source=std::nullopt, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual void emitDwarfFile0Directive (StringRef Directory, StringRef Filename, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source, unsigned CUID=0)
Specify the "root" file of the compilation, using the ".file 0" extension.
virtual void emitCFIBKeyFrame ()
virtual void emitCFIMTETaggedFrame ()
virtual bool emitCVFileDirective (unsigned FileNo, StringRef Filename, ArrayRef< uint8_t > Checksum, unsigned ChecksumKind)
Associate a filename with a specified logical file number, and also specify that file's checksum information.
virtual bool emitCVFuncIdDirective (unsigned FunctionId)
Introduces a function id for use with .cv_loc.
virtual bool emitCVInlineSiteIdDirective (unsigned FunctionId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol, SMLoc Loc)
Introduces an inline call site id for use with .cv_loc.
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeRegisterRelHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeSubfieldRegisterHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeRegisterHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeFramePointerRelHeader DRHdr)
virtual void emitCVFPOData (const MCSymbol *ProcSym, SMLoc Loc={})
This implements the CodeView '.cv_fpo_data' assembler directive.
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
void emitCFIStartProc (bool IsSimple, SMLoc Loc=SMLoc())
void emitCFIEndProc ()
virtual void emitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void emitCFIDefCfaOffset (int64_t Offset)
virtual void emitCFIDefCfaRegister (int64_t Register)
virtual void emitCFILLVMDefAspaceCfa (int64_t Register, int64_t Offset, int64_t AddressSpace)
virtual void emitCFIOffset (int64_t Register, int64_t Offset)
virtual void emitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void emitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void emitCFIRememberState ()
virtual void emitCFIRestoreState ()
virtual void emitCFISameValue (int64_t Register)
virtual void emitCFIRestore (int64_t Register)
virtual void emitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void emitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void emitCFIEscape (StringRef Values)
virtual void emitCFIReturnColumn (int64_t Register)
virtual void emitCFIGnuArgsSize (int64_t Size)
virtual void emitCFISignalFrame ()
virtual void emitCFIUndefined (int64_t Register)
virtual void emitCFIRegister (int64_t Register1, int64_t Register2)
virtual void emitCFIWindowSave ()
virtual void emitCFINegateRAState ()
virtual void emitWinCFIStartProc (const MCSymbol *Symbol, SMLoc Loc=SMLoc())
virtual void emitWinCFIEndProc (SMLoc Loc=SMLoc())
virtual void emitWinCFIFuncletOrFuncEnd (SMLoc Loc=SMLoc())
This is used on platforms, such as Windows on ARM64, that require function or funclet sizes to be emitted in .xdata before the End marker is emitted for the frame.
virtual void emitWinCFIStartChained (SMLoc Loc=SMLoc())
virtual void emitWinCFIEndChained (SMLoc Loc=SMLoc())
virtual void emitWinCFIPushReg (MCRegister Register, SMLoc Loc=SMLoc())
virtual void emitWinCFISetFrame (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void emitWinCFIAllocStack (unsigned Size, SMLoc Loc=SMLoc())
virtual void emitWinCFISaveReg (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void emitWinCFISaveXMM (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void emitWinCFIPushFrame (bool Code, SMLoc Loc=SMLoc())
virtual void emitWinCFIEndProlog (SMLoc Loc=SMLoc())
virtual void emitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except, SMLoc Loc=SMLoc())
virtual void emitWinEHHandlerData (SMLoc Loc=SMLoc())
virtual void emitCGProfileEntry (const MCSymbolRefExpr *From, const MCSymbolRefExpr *To, uint64_t Count)
MCSection * getAssociatedPDataSection (const MCSection *TextSec)
Get the .pdata section used for the given section.
MCSection * getAssociatedXDataSection (const MCSection *TextSec)
Get the .xdata section used for the given section.
virtual void emitSyntaxDirective ()
virtual void emitPseudoProbe (uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attr, const MCPseudoProbeInlineStack &InlineStack, MCSymbol *FnSym)
Emit the a pseudo probe into the current section.
void emitRawText (const Twine &String)
If this file is backed by a assembly streamer, this dumps the specified string in the output .s file.
void finish (SMLoc EndLoc=SMLoc())
Finish emission of machine code.
void maybeEmitDwarf64Mark ()
Emit a special value of 0xffffffff if producing 64-bit debugging info.
virtual void emitDwarfUnitLength (uint64_t Length, const Twine &Comment)
Emit a unit length field.
virtual MCSymbol * emitDwarfUnitLength (const Twine &Prefix, const Twine &Comment)
Emit a unit length field.
virtual void emitDwarfLineStartLabel (MCSymbol *StartSym)
Emit the debug line start label.
virtual void doFinalizationAtSectionEnd (MCSection *Section)
Do finalization for the streamer at the end of a section.
virtual bool isVerboseAsm () const
Return true if this streamer supports verbose assembly and if it is enabled.
virtual bool hasRawTextSupport () const
Return true if this asm streamer supports emitting unformatted text to the .s file with EmitRawText.
virtual void AddComment (const Twine &T, bool EOL=true)
Add a textual comment.
virtual raw_ostream & getCommentOS ()
Return a raw_ostream that comments can be written to.
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
Print T and prefix it with the comment string (normally #) and optionally a tab.
virtual void addExplicitComment (const Twine &T)
Add explicit comment T.
virtual void emitExplicitComments ()
Emit added explicit comments.
virtual void addBlankLine ()
Emit a blank line to a .s file to pretty it up.
MCSectionSubPair getCurrentSection () const
Return the current section that the streamer is emitting code to.
MCSection * getCurrentSectionOnly () const
MCSectionSubPair getPreviousSection () const
Return the previous section that the streamer is emitting code to.
unsigned getSymbolOrder (const MCSymbol *Sym) const
Returns an index to represent the order a symbol was emitted in.
void pushSection ()
Save the current and previous section on the section stack.
bool popSection ()
Restore the current and previous section from the section stack.
bool subSection (const MCExpr *Subsection)
virtual void switchSection (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
void switchSectionNoChange (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
virtual void initSections (bool NoExecStack, const MCSubtargetInfo &STI)
Create the default sections and set the initial one.
MCSymbol * endSection (MCSection *Section)
void assignFragment (MCSymbol *Symbol, MCFragment *Fragment)
Sets the symbol's section.
virtual StringRef getMnemonic (MCInst &MI)
Returns the mnemonic for MI, if the streamer has access to a instruction printer and returns an empty string otherwise.
virtual void emitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void emitAssemblerFlag (MCAssemblerFlag Flag)
Note in the output the specified Flag.
virtual void emitLinkerOptions (ArrayRef< std::string > Kind)
Emit the given list Options of strings as linker options into the output.
virtual void emitDataRegion (MCDataRegionType Kind)
Note in the output the specified region Kind.
virtual void emitVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Specify the Mach-O minimum deployment target version.
virtual void emitBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Emit/Specify Mach-O build version command.
virtual void emitDarwinTargetVariantBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
void emitVersionForTarget (const Triple &Target, const VersionTuple &SDKVersion, const Triple *DarwinTargetVariantTriple, const VersionTuple &DarwinTargetVariantSDKVersion)
virtual void emitThumbFunc (MCSymbol *Func)
Note in the output that the specified Func is a Thumb mode function (ARM target only).
virtual void emitSymbolDesc (MCSymbol *Symbol, unsigned DescValue)
Set the DescValue for the Symbol.
virtual void beginCOFFSymbolDef (const MCSymbol *Symbol)
Start emitting COFF symbol definition.
virtual void emitCOFFSymbolStorageClass (int StorageClass)
Emit the storage class of the symbol.
virtual void emitCOFFSymbolType (int Type)
Emit the type of the symbol.
virtual void endCOFFSymbolDef ()
Marks the end of the symbol definition.
virtual void emitCOFFSafeSEH (MCSymbol const *Symbol)
virtual void emitCOFFSymbolIndex (MCSymbol const *Symbol)
Emits the symbol table index of a Symbol into the current section.
virtual void emitCOFFSectionIndex (MCSymbol const *Symbol)
Emits a COFF section index.
virtual void emitCOFFSecRel32 (MCSymbol const *Symbol, uint64_t Offset)
Emits a COFF section relative relocation.
virtual void emitCOFFImgRel32 (MCSymbol const *Symbol, int64_t Offset)
Emits a COFF image relative relocation.
virtual void emitELFSize (MCSymbol *Symbol, const MCExpr *Value)
Emit an ELF .size directive.
virtual void emitELFSymverDirective (const MCSymbol *OriginalSym, StringRef Name, bool KeepOriginalSym)
Emit an ELF .symver directive.
virtual void emitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
virtual void emitGNUAttribute (unsigned Tag, unsigned Value)
Emit a .gnu_attribute directive.
virtual void emitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, Align ByteAlignment)
Emit a local common (.lcomm) symbol.
virtual void emitTBSSSymbol (MCSection *Section, MCSymbol *Symbol, uint64_t Size, Align ByteAlignment=Align(1))
Emit a thread local bss (.tbss) symbol.
virtual void emitBinaryData (StringRef Data)
Functionally identical to EmitBytes.
void emitValue (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc())
virtual void emitIntValue (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
virtual void emitIntValue (APInt Value)
virtual void emitIntValueInHex (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes.
void emitInt8 (uint64_t Value)
void emitInt16 (uint64_t Value)
void emitInt32 (uint64_t Value)
void emitInt64 (uint64_t Value)
virtual void emitIntValueInHexWithPadding (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes, pads the field with leading zeros to Size width.
unsigned emitULEB128IntValue (uint64_t Value, unsigned PadTo=0)
Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
unsigned emitSLEB128IntValue (int64_t Value)
Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void emitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
Special case of EmitValue that avoids the client having to pass in a MCExpr for MCSymbols.
void emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
void emitZeros (uint64_t NumBytes)
Emit NumBytes worth of zeros.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCObjectStreamer
MCObjectStreamer (MCContext &Context, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter)
~MCObjectStreamer ()
bool changeSectionImpl (MCSection *Section, const MCExpr *Subsection)
void addPendingLabel (MCSymbol *label)
Assign a label to the current Section and Subsection even though a fragment is not yet present.
void flushPendingLabels (MCFragment *F, uint64_t FOffset=0)
If any labels have been emitted but not assigned fragments in the current Section and Subsection, ensure that they get assigned, either to fragment F if possible or to a new data fragment.
Protected Member Functions inherited from llvm::MCStreamer
MCStreamer (MCContext &Ctx)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void emitWindowsUnwindTables (WinEH::FrameInfo *Frame)
virtual void emitWindowsUnwindTables ()
virtual void emitRawTextImpl (StringRef String)
EmitRawText - If this file is backed by an assembly streamer, this dumps the specified string in the output .s file.
bool checkCVLocSection (unsigned FuncId, unsigned FileNo, SMLoc Loc)
Returns true if the the .cv_loc directive is in the right section.
Detailed Description
Definition at line 16 of file MCXCOFFStreamer.h.
Constructor & Destructor Documentation
MCXCOFFStreamer()
MCXCOFFStreamer::MCXCOFFStreamer (MCContext & Context, std::unique_ptr< MCAsmBackend > MAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter)
Definition at line 27 of file MCXCOFFStreamer.cpp.
Member Function Documentation
emitCommonSymbol()
void MCXCOFFStreamer::emitCommonSymbol (MCSymbol * Symbol, uint64_t Size, Align ByteAlignment) override virtual
Emit a common symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the symbol.
Implements llvm::MCStreamer.
Definition at line 93 of file MCXCOFFStreamer.cpp.
References llvm::LCOMM::ByteAlignment, llvm::XCOFF::C_HIDEXT, llvm::MCObjectStreamer::emitValueToAlignment(), llvm::MCStreamer::emitZeros(), llvm::MCObjectStreamer::getAssembler(), and llvm::MCAssembler::registerSymbol().
Referenced by emitXCOFFLocalCommonSymbol().
emitInstToData()
void MCXCOFFStreamer::emitInstToData (const MCInst & Inst, const MCSubtargetInfo & STI) override virtual
Implements llvm::MCObjectStreamer.
Definition at line 116 of file MCXCOFFStreamer.cpp.
References DF, llvm::MCCodeEmitter::encodeInstruction(), Fixup, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getEmitter(), and llvm::MCObjectStreamer::getOrCreateDataFragment().
emitSymbolAttribute()
bool MCXCOFFStreamer::emitSymbolAttribute (MCSymbol * Symbol, MCSymbolAttr Attribute) override virtual
Add the given Attribute to Symbol.
Implements llvm::MCStreamer.
Definition at line 34 of file MCXCOFFStreamer.cpp.
References llvm::XCOFF::C_EXT, llvm::XCOFF::C_HIDEXT, llvm::XCOFF::C_WEAKEXT, llvm::MCObjectStreamer::getAssembler(), llvm::MCSA_Cold, llvm::MCSA_Exported, llvm::MCSA_Extern, llvm::MCSA_Global, llvm::MCSA_Hidden, llvm::MCSA_LGlobal, llvm::MCSA_Protected, llvm::MCSA_Weak, llvm::MCAssembler::registerSymbol(), llvm::report_fatal_error(), llvm::XCOFF::SYM_V_EXPORTED, llvm::XCOFF::SYM_V_HIDDEN, and llvm::XCOFF::SYM_V_PROTECTED.
Referenced by emitXCOFFSymbolLinkageWithVisibility().
emitXCOFFExceptDirective()
void MCXCOFFStreamer::emitXCOFFExceptDirective (const MCSymbol * Symbol, const MCSymbol * Trap, unsigned Lang, unsigned Reason, unsigned FunctionSize, bool hasDebug) override virtual
Emit an XCOFF .except directive which adds information about a trap instruction to the object file exception section.
Parameters
Symbol - The function containing the trap.
Lang - The language code for the exception entry.
Reason - The reason code for the exception entry.
Reimplemented from llvm::MCStreamer.
Definition at line 84 of file MCXCOFFStreamer.cpp.
References llvm::MCObjectWriter::addExceptionEntry(), llvm::MCObjectStreamer::getAssembler(), and llvm::MCAssembler::getWriter().
emitXCOFFLocalCommonSymbol()
void MCXCOFFStreamer::emitXCOFFLocalCommonSymbol (MCSymbol * LabelSym, uint64_t Size, MCSymbol * CsectSym, Align Alignment) override virtual
Emits an lcomm directive with XCOFF csect information.
Parameters
LabelSym - Label on the block of storage.
Size - The size of the block of storage.
CsectSym - Csect name for the block of storage.
Alignment - The alignment of the symbol in bytes.
Reimplemented from llvm::MCStreamer.
Definition at line 149 of file MCXCOFFStreamer.cpp.
References emitCommonSymbol().
emitXCOFFRefDirective()
void llvm::MCXCOFFStreamer::emitXCOFFRefDirective (StringRef Sym) inline override virtual
Emit a XCOFF .ref directive which creates R_REF type entry in the relocation table for one or more symbols.
Parameters
Sym - The symbol on the .ref directive.
Reimplemented from llvm::MCStreamer.
Definition at line 34 of file MCXCOFFStreamer.h.
References llvm::report_fatal_error().
emitXCOFFRenameDirective()
void llvm::MCXCOFFStreamer::emitXCOFFRenameDirective (const MCSymbol * Name, StringRef Rename) inline override virtual
Emit a XCOFF .rename directive which creates a synonym for an illegal or undesirable name.
Parameters
Name - The name used internally in the assembly for references to the symbol.
Rename - The value to which the Name parameter is changed at the end of assembly.
Reimplemented from llvm::MCStreamer.
Definition at line 38 of file MCXCOFFStreamer.h.
References llvm::report_fatal_error().
emitXCOFFSymbolLinkageWithVisibility()
void MCXCOFFStreamer::emitXCOFFSymbolLinkageWithVisibility (MCSymbol * Symbol, MCSymbolAttr Linkage, MCSymbolAttr Visibility) override virtual
Emit a symbol's linkage and visibility with a linkage directive for XCOFF.
Parameters
Symbol - The symbol to emit.
Linkage - The linkage of the symbol to emit.
Visibility - The visibility of the symbol to emit or MCSA_Invalid if the symbol does not have an explicit visibility.
Reimplemented from llvm::MCStreamer.
Definition at line 72 of file MCXCOFFStreamer.cpp.
References emitSymbolAttribute(), and llvm::MCSA_Invalid.
emitZerofill()
void MCXCOFFStreamer::emitZerofill (MCSection * Section, MCSymbol * Symbol = nullptr, uint64_t Size = 0, Align ByteAlignment = Align(1), SMLoc Loc = SMLoc()) override virtual
Emit the zerofill section and an optional symbol.
Parameters
Section - The zerofill section to create and or to put the symbol
Symbol - The zerofill symbol to emit, if non-NULL.
Size - The size of the zerofill symbol.
ByteAlignment - The alignment of the zerofill symbol.
Implements llvm::MCStreamer.
Definition at line 110 of file MCXCOFFStreamer.cpp.
References llvm::report_fatal_error().
The documentation for this class was generated from the following files:
include/llvm/MC/MCXCOFFStreamer.h
lib/MC/MCXCOFFStreamer.cpp