LLVM: llvm::HexagonRegisterInfo Class Reference
llvm::HexagonRegisterInfo Class Reference
#include "Target/Hexagon/HexagonRegisterInfo.h"
Public Member Functions
HexagonRegisterInfo (unsigned HwMode)
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
Returns true since we may need scavenging for a temporary register when generating hardware loop instructions.
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
Returns true.
bool useFPForScavengingIndex (const MachineFunction &MF) const override
Returns true if the frame pointer is valid.
bool shouldCoalesce (MachineInstr *MI, const TargetRegisterClass *SrcRC, unsigned SubReg, const TargetRegisterClass *DstRC, unsigned DstSubReg, const TargetRegisterClass *NewRC, LiveIntervals &LIS) const override
Register getFrameRegister (const MachineFunction &MF) const override
Register getFrameRegister () const
Register getStackRegister () const
unsigned getHexagonSubRegIndex (const TargetRegisterClass &RC, unsigned GenIdx) const
const MCPhysReg * getCallerSavedRegs (const MachineFunction *MF, const TargetRegisterClass *RC) const
Register getFirstCallerSavedNonParamReg () const
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
bool isEHReturnCalleeSaveReg (Register Reg) const
Detailed Description
Definition at line 29 of file HexagonRegisterInfo.h.
Constructor & Destructor Documentation
HexagonRegisterInfo()
HexagonRegisterInfo::HexagonRegisterInfo (unsigned HwMode)
Definition at line 56 of file HexagonRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
bool HexagonRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 208 of file HexagonRegisterInfo.cpp.
References llvm::LiveRegUnits::accumulateUsedDefed(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), DL, E, FrameIndexReuseLimit, FrameIndexSearchRange, llvm::HexagonSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineInstrBundleIterator< Ty, IsReverse >::getReverse(), llvm::MachineFunction::getSubtarget(), I, llvm::SmallSet< T, N, C >::insert(), llvm::MachineInstr::isCall(), MI, MRI, llvm::Offset, llvm::MachineInstr::operands(), llvm::MachineBasicBlock::rend(), llvm::SmallSet< T, N, C >::size(), and Uses.
getCalleeSavedRegs()
const MCPhysReg * HexagonRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Code Generation virtual methods...
Definition at line 119 of file HexagonRegisterInfo.cpp.
References llvm::MachineFunction::getInfo(), and R2.
Referenced by llvm::HexagonFrameLowering::determineCalleeSaves(), and llvm::HexagonDAGToDAGISel::emitFunctionEntryCode().
getCallerSavedRegs()
const MCPhysReg * HexagonRegisterInfo::getCallerSavedRegs (const MachineFunction * MF, const TargetRegisterClass * RC) const
Definition at line 67 of file HexagonRegisterInfo.cpp.
References llvm::dbgs(), llvm::TargetRegisterClass::getID(), llvm_unreachable, P2, R2, R4, R6, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::NVPTX::PTXLdStInstCode::V4.
Referenced by needToReserveScavengingSpillSlots().
getCallPreservedMask()
const uint32_t * HexagonRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID) const override
Definition at line 141 of file HexagonRegisterInfo.cpp.
Referenced by llvm::HexagonTargetLowering::LowerCall().
getFirstCallerSavedNonParamReg()
Register HexagonRegisterInfo::getFirstCallerSavedNonParamReg () const
Definition at line 456 of file HexagonRegisterInfo.cpp.
References R6.
getFrameRegister() [1/2]
Register HexagonRegisterInfo::getFrameRegister () const
Definition at line 411 of file HexagonRegisterInfo.cpp.
Referenced by getFrameRegister().
getFrameRegister() [2/2]
Register HexagonRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 402 of file HexagonRegisterInfo.cpp.
References getFrameRegister(), getStackRegister(), and llvm::HexagonFrameLowering::hasFP().
Referenced by llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::HexagonPacketizerList::isCallDependent(), and llvm::HexagonTargetLowering::LowerFRAMEADDR().
getHexagonSubRegIndex()
unsigned HexagonRegisterInfo::getHexagonSubRegIndex (const TargetRegisterClass & RC, unsigned GenIdx) const
Definition at line 421 of file HexagonRegisterInfo.cpp.
References assert(), llvm::TargetRegisterClass::getID(), llvm::TargetRegisterClass::getSuperClasses(), llvm_unreachable, llvm::Hexagon::ps_sub_hi, and llvm::Hexagon::ps_sub_lo.
getPointerRegClass()
const TargetRegisterClass * HexagonRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
Definition at line 451 of file HexagonRegisterInfo.cpp.
getReservedRegs()
BitVector HexagonRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 147 of file HexagonRegisterInfo.cpp.
References llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::Hexagon_MC::GetVectRegRev(), llvm::HexagonSubtarget::hasReservedR19(), llvm::Register::isValid(), LC0, llvm::Reserved, and x.
Referenced by llvm::HexagonDAGToDAGISel::emitFunctionEntryCode().
getStackRegister()
Register HexagonRegisterInfo::getStackRegister () const
Definition at line 416 of file HexagonRegisterInfo.cpp.
Referenced by llvm::HexagonInstrInfo::getDuplexCandidateGroup(), getFrameRegister(), llvm::HexagonPacketizerList::isCallDependent(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), and llvm::HexagonTargetLowering::LowerCall().
isEHReturnCalleeSaveReg()
bool HexagonRegisterInfo::isEHReturnCalleeSaveReg (Register Reg) const
Definition at line 61 of file HexagonRegisterInfo.cpp.
References R2.
requiresFrameIndexScavenging()
bool llvm::HexagonRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline override
Returns true.
Spill code for predicate registers might need an extra register.
Definition at line 52 of file HexagonRegisterInfo.h.
requiresRegisterScavenging()
bool llvm::HexagonRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
Returns true since we may need scavenging for a temporary register when generating hardware loop instructions.
Definition at line 46 of file HexagonRegisterInfo.h.
shouldCoalesce()
bool HexagonRegisterInfo::shouldCoalesce (MachineInstr * MI, const TargetRegisterClass * SrcRC, unsigned SubReg, const TargetRegisterClass * DstRC, unsigned DstSubReg, const TargetRegisterClass * NewRC, LiveIntervals & LIS) const override
Definition at line 353 of file HexagonRegisterInfo.cpp.
References llvm::any_of(), E, llvm::TargetRegisterClass::getID(), llvm::SlotIndexes::getInstructionFromIndex(), llvm::LiveIntervals::getInterval(), llvm::LiveIntervals::getSlotIndexes(), llvm::MachineFunction::getSubtarget(), I, MI, S, and llvm::HexagonSubtarget::useHVXOps().
useFPForScavengingIndex()
bool HexagonRegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const override
Returns true if the frame pointer is valid.
Definition at line 445 of file HexagonRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonRegisterInfo.h
lib/Target/Hexagon/HexagonRegisterInfo.cpp