LLVM: llvm::object::XCOFFObjectFile Class Reference
llvm::object::XCOFFObjectFile Class Reference
#include "llvm/Object/XCOFFObjectFile.h"
Public Member Functions
void moveSymbolNext (DataRefImpl &Symb) const override
Expected< uint32_t > getSymbolFlags (DataRefImpl Symb) const override
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
bool is64Bit () const override
Expected< StringRef > getSymbolName (DataRefImpl Symb) const override
Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const override
uint64_t getSymbolValueImpl (DataRefImpl Symb) const override
uint32_t getSymbolAlignment (DataRefImpl Symb) const override
uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const override
Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const override
Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const override
void moveSectionNext (DataRefImpl &Sec) const override
Expected< StringRef > getSectionName (DataRefImpl Sec) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionIndex (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
bool isSectionCompressed (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isDebugSection (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
void moveRelocationNext (DataRefImpl &Rel) const override
uint64_t getRelocationOffset (DataRefImpl Rel) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
uint64_t getRelocationType (DataRefImpl Rel) const override
void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
section_iterator section_begin () const override
section_iterator section_end () const override
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
Triple::ArchType getArch () const override
Expected< SubtargetFeatures > getFeatures () const override
Expected< uint64_t > getStartAddress () const override
StringRef mapDebugSectionName (StringRef Name) const override
Maps a debug section name to a standard DWARF section name.
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
Expected< StringRef > getRawData (const char *Start, uint64_t Size, StringRef Name) const
const XCOFFAuxiliaryHeader32 * auxiliaryHeader32 () const
const XCOFFAuxiliaryHeader64 * auxiliaryHeader64 () const
const void * getPointerToSymbolTable () const
Expected< StringRef > getSymbolSectionName (XCOFFSymbolRef Ref) const
unsigned getSymbolSectionID (SymbolRef Sym) const
XCOFFSymbolRef toSymbolRef (DataRefImpl Ref) const
const XCOFFFileHeader32 * fileHeader32 () const
const XCOFFFileHeader64 * fileHeader64 () const
uint16_t getMagic () const
uint16_t getNumberOfSections () const
int32_t getTimeStamp () const
uint32_t getSymbolTableOffset32 () const
uint64_t getSymbolTableOffset64 () const
int32_t getRawNumberOfSymbolTableEntries32 () const
uint32_t getLogicalNumberOfSymbolTableEntries32 () const
uint32_t getNumberOfSymbolTableEntries64 () const
uint32_t getNumberOfSymbolTableEntries () const
uint32_t getSymbolIndex (uintptr_t SymEntPtr) const
uint64_t getSymbolSize (DataRefImpl Symb) const
uintptr_t getSymbolByIndex (uint32_t Idx) const
uintptr_t getSymbolEntryAddressByIndex (uint32_t SymbolTableIndex) const
Expected< StringRef > getSymbolNameByIndex (uint32_t SymbolTableIndex) const
Expected< StringRef > getCFileName (const XCOFFFileAuxEnt *CFileEntPtr) const
uint16_t getOptionalHeaderSize () const
uint16_t getFlags () const
ArrayRef< XCOFFSectionHeader32 > sections32 () const
ArrayRef< XCOFFSectionHeader64 > sections64 () const
int32_t getSectionFlags (DataRefImpl Sec) const
Expected< DataRefImpl > getSectionByNum (int16_t Num) const
Expected< uintptr_t > getSectionFileOffsetToRawData (XCOFF::SectionTypeFlags SectType) const
void checkSymbolEntryPointer (uintptr_t SymbolEntPtr) const
template<typename T >
Expected< uint32_t > getNumberOfRelocationEntries (const XCOFFSectionHeader< T > &Sec) const
template<typename Shdr , typename Reloc >
Expected< ArrayRef< Reloc > > relocations (const Shdr &Sec) const
Expected< StringRef > getImportFileTable () const
template<typename ExceptEnt >
Expected< ArrayRef< ExceptEnt > > getExceptionEntries () const
Expected< StringRef > getStringTableEntry (uint32_t Offset) const
StringRef getStringTable () const
const XCOFF::SymbolAuxType * getSymbolAuxType (uintptr_t AuxEntryAddress) const
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
section_iterator_range sections () const
virtual bool hasDebugInfo () const
virtual std::optional< StringRef > tryGetCPUName () const
virtual void setARMSubArch (Triple &TheTriple) const
Triple makeTriple () const
Create a triple from the data in this object file.
bool isReflectionSectionStrippable (llvm::binaryformat::Swift5ReflectionSectionKind ReflectionSectionKind) const
True if the reflection section can be stripped by the linker.
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
virtual Error initContent ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isOffloadFile () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static uintptr_t getAdvancedSymbolEntryAddress (uintptr_t CurrentAddress, uint32_t Distance)
static bool classof (const Binary *B)
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type, bool InitContent=true)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object, bool InitContent=true)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context, bool InitContent=true)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static bool isSymbolicFile (file_magic Type, const LLVMContext *Context)
Static Public Member Functions inherited from llvm::object::Binary
static Error checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Static Public Attributes
static constexpr uint64_t InvalidRelocOffset
Friends
Expected< std::unique_ptr< ObjectFile > > ObjectFile::createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
Additional Inherited Members
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_COFFImportFile, ID_IR,
ID_TapiUniversal, ID_TapiFile, ID_Minidump, ID_WinRes,
ID_Offload, ID_StartObjects, ID_COFF, ID_XCOFF32,
ID_XCOFF64, ID_ELF32L, ID_ELF32B, ID_ELF64L,
ID_ELF64B, ID_MachO32L, ID_MachO32B, ID_MachO64L,
ID_MachO64B, ID_Wasm, ID_EndObjects
}
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual Expected< section_iterator > getRelocatedSection (DataRefImpl Sec) const
virtual llvm::binaryformat::Swift5ReflectionSectionKind mapReflectionSectionNameToEnumValue (StringRef SectionName) const
Expected< uint64_t > getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 521 of file XCOFFObjectFile.h.
Member Function Documentation
auxiliaryHeader32()
const XCOFFAuxiliaryHeader32 * llvm::object::XCOFFObjectFile::auxiliaryHeader32 () const
Definition at line 183 of file XCOFFObjectFile.cpp.
References assert(), and is64Bit().
auxiliaryHeader64()
const XCOFFAuxiliaryHeader64 * llvm::object::XCOFFObjectFile::auxiliaryHeader64 () const
Definition at line 188 of file XCOFFObjectFile.cpp.
References assert(), and is64Bit().
checkSymbolEntryPointer()
void llvm::object::XCOFFObjectFile::checkSymbolEntryPointer (uintptr_t SymbolEntPtr) const
Definition at line 884 of file XCOFFObjectFile.cpp.
References llvm::report_fatal_error(), and llvm::XCOFF::SymbolTableEntrySize.
classof()
static bool llvm::object::XCOFFObjectFile::classof (const Binary * B) inline static
Definition at line 717 of file XCOFFObjectFile.h.
References B.
fileHeader32()
const XCOFFFileHeader32 * llvm::object::XCOFFObjectFile::fileHeader32 () const
Definition at line 173 of file XCOFFObjectFile.cpp.
References assert(), and is64Bit().
fileHeader64()
const XCOFFFileHeader64 * llvm::object::XCOFFObjectFile::fileHeader64 () const
Definition at line 178 of file XCOFFObjectFile.cpp.
References assert(), and is64Bit().
getAdvancedSymbolEntryAddress()
uintptr_t llvm::object::XCOFFObjectFile::getAdvancedSymbolEntryAddress (uintptr_t CurrentAddress, uint32_t Distance) static
Definition at line 121 of file XCOFFObjectFile.cpp.
References llvm::object::getWithOffset(), and llvm::XCOFF::SymbolTableEntrySize.
getArch()
Triple::ArchType llvm::object::XCOFFObjectFile::getArch () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 711 of file XCOFFObjectFile.cpp.
References is64Bit(), llvm::Triple::ppc, and llvm::Triple::ppc64.
getBytesInAddress()
uint8_t llvm::object::XCOFFObjectFile::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 705 of file XCOFFObjectFile.cpp.
References is64Bit().
getCFileName()
Expected< StringRef > llvm::object::XCOFFObjectFile::getCFileName (const XCOFFFileAuxEnt * CFileEntPtr) const
Definition at line 247 of file XCOFFObjectFile.cpp.
References llvm::object::generateXCOFFFixedNameStringRef(), llvm::object::XCOFFFileAuxEnt::NameInStrTblType::Magic, llvm::object::XCOFFFileAuxEnt::Name, llvm::object::XCOFFFileAuxEnt::NameInStrTbl, and llvm::object::XCOFFFileAuxEnt::NameInStrTblType::Offset.
getCommonSymbolSizeImpl()
uint64_t llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 280 of file XCOFFObjectFile.cpp.
References assert(), llvm::consumeError(), llvm::Expected< T >::get(), llvm::object::XCOFFCsectAuxRef::getSectionOrLength(), llvm::object::XCOFFCsectAuxRef::getSymbolType(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef(), llvm::object::XCOFFSymbolRef::isCsectSymbol(), llvm::Expected< T >::takeError(), uint64_t, and llvm::XCOFF::XTY_CM.
getExceptionEntries()
template<typename ExceptEnt > template Expected< ArrayRef< ExceptionSectionEntry64 > > llvm::object::XCOFFObjectFile::getExceptionEntries () const
Definition at line 1028 of file XCOFFObjectFile.cpp.
References assert(), getSectionSize(), is64Bit(), llvm::object::DataRefImpl::p, llvm::XCOFF::STYP_EXCEPT, and llvm::Expected< T >::takeError().
getFeatures()
Expected< SubtargetFeatures > llvm::object::XCOFFObjectFile::getFeatures () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 715 of file XCOFFObjectFile.cpp.
getFileFormatName()
StringRef llvm::object::XCOFFObjectFile::getFileFormatName () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 707 of file XCOFFObjectFile.cpp.
References is64Bit().
getFlags()
uint16_t llvm::object::XCOFFObjectFile::getFlags () const
Definition at line 943 of file XCOFFObjectFile.cpp.
References is64Bit().
getImportFileTable()
Expected< StringRef > llvm::object::XCOFFObjectFile::getImportFileTable () const
Definition at line 1088 of file XCOFFObjectFile.cpp.
References llvm::object::createError(), llvm::object::Binary::Data, llvm::Expected< T >::get(), is64Bit(), llvm::object::LoaderSectionHeader32::LengthOfImpidStrTbl, llvm::object::LoaderSectionHeader64::LengthOfImpidStrTbl, llvm::object::LoaderSectionHeader32::OffsetToImpid, llvm::object::LoaderSectionHeader64::OffsetToImpid, llvm::XCOFF::STYP_LOADER, llvm::Expected< T >::takeError(), llvm::toString(), uint64_t, and llvm::Twine::utohexstr().
getLogicalNumberOfSymbolTableEntries32()
uint32_t llvm::object::XCOFFObjectFile::getLogicalNumberOfSymbolTableEntries32 () const
Definition at line 859 of file XCOFFObjectFile.cpp.
getMagic()
uint16_t llvm::object::XCOFFObjectFile::getMagic () const
Definition at line 773 of file XCOFFObjectFile.cpp.
References is64Bit().
getNumberOfRelocationEntries()
template<typename T > Expected< uint32_t > llvm::object::XCOFFObjectFile::getNumberOfRelocationEntries (const XCOFFSectionHeader< T > & Sec) const
Definition at line 983 of file XCOFFObjectFile.cpp.
References llvm::errorCodeToError(), is64Bit(), llvm::object::parse_failed, llvm::XCOFF::RelocOverflow, sections32(), llvm::XCOFF::STYP_OVRFLO, and T.
Referenced by relocations().
getNumberOfSections()
uint16_t llvm::object::XCOFFObjectFile::getNumberOfSections () const
Definition at line 834 of file XCOFFObjectFile.cpp.
References is64Bit().
Referenced by sections32(), and sections64().
getNumberOfSymbolTableEntries()
uint32_t llvm::object::XCOFFObjectFile::getNumberOfSymbolTableEntries () const
Definition at line 873 of file XCOFFObjectFile.cpp.
References is64Bit().
getNumberOfSymbolTableEntries64()
uint32_t llvm::object::XCOFFObjectFile::getNumberOfSymbolTableEntries64 () const
Definition at line 869 of file XCOFFObjectFile.cpp.
getOptionalHeaderSize()
uint16_t llvm::object::XCOFFObjectFile::getOptionalHeaderSize () const
Definition at line 843 of file XCOFFObjectFile.cpp.
References is64Bit().
getPointerToSymbolTable()
const void* llvm::object::XCOFFObjectFile::getPointerToSymbolTable () const inline
Definition at line 635 of file XCOFFObjectFile.h.
getRawData()
Expected< StringRef > llvm::object::XCOFFObjectFile::getRawData (const char * Start, uint64_t Size, StringRef Name) const
Definition at line 760 of file XCOFFObjectFile.cpp.
References llvm::createError(), llvm::Data, E, move, llvm::toString(), and llvm::Twine::utohexstr().
getRawNumberOfSymbolTableEntries32()
int32_t llvm::object::XCOFFObjectFile::getRawNumberOfSymbolTableEntries32 () const
Definition at line 852 of file XCOFFObjectFile.cpp.
getRelocationOffset()
uint64_t llvm::object::XCOFFObjectFile::getRelocationOffset (DataRefImpl Rel) const override virtual
Returns
the relocation offset with the base address of the containing section as zero, or InvalidRelocOffset on errors (such as a relocation that does not refer to an address in any section).
Implements llvm::object::ObjectFile.
Definition at line 567 of file XCOFFObjectFile.cpp.
References I, is64Bit(), llvm::object::DataRefImpl::p, llvm::object::XCOFFSectionHeader32::SectionSize, llvm::object::XCOFFSectionHeader64::SectionSize, uint64_t, llvm::object::XCOFFSectionHeader32::VirtualAddress, llvm::object::XCOFFSectionHeader64::VirtualAddress, and llvm::object::XCOFFRelocation< AddressType >::VirtualAddress.
getRelocationSymbol()
symbol_iterator llvm::object::XCOFFObjectFile::getRelocationSymbol (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 600 of file XCOFFObjectFile.cpp.
References Index, is64Bit(), llvm::object::DataRefImpl::p, and llvm::object::XCOFFRelocation< AddressType >::SymbolIndex.
getRelocationType()
uint64_t llvm::object::XCOFFObjectFile::getRelocationType (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 620 of file XCOFFObjectFile.cpp.
References is64Bit(), and llvm::object::DataRefImpl::p.
getRelocationTypeName()
void llvm::object::XCOFFObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 626 of file XCOFFObjectFile.cpp.
References llvm::StringRef::begin(), llvm::StringRef::end(), llvm::XCOFF::getRelocationTypeString(), is64Bit(), llvm::object::DataRefImpl::p, and llvm::object::XCOFFRelocation< AddressType >::Type.
getSectionAddress()
uint64_t llvm::object::XCOFFObjectFile::getSectionAddress (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 370 of file XCOFFObjectFile.cpp.
References is64Bit().
getSectionAlignment()
uint64_t llvm::object::XCOFFObjectFile::getSectionAlignment (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 420 of file XCOFFObjectFile.cpp.
References llvm_unreachable, and uint64_t.
getSectionByNum()
Expected< DataRefImpl > llvm::object::XCOFFObjectFile::getSectionByNum (int16_t Num) const
Definition at line 777 of file XCOFFObjectFile.cpp.
References llvm::createStringError(), llvm::object::getWithOffset(), and llvm::object::DataRefImpl::p.
Referenced by llvm::object::XCOFFSymbolRef::isFunction().
getSectionContents()
Expected< ArrayRef< uint8_t > > llvm::object::XCOFFObjectFile::getSectionContents (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 398 of file XCOFFObjectFile.cpp.
References llvm::ArrayRef(), base, llvm::createError(), llvm::Data, E, is64Bit(), move, llvm::COFF::SectionSize, llvm::toString(), uint64_t, and llvm::Twine::utohexstr().
getSectionFileOffsetToRawData()
Expected< uintptr_t > llvm::object::XCOFFObjectFile::getSectionFileOffsetToRawData (XCOFF::SectionTypeFlags SectType) const
Definition at line 433 of file XCOFFObjectFile.cpp.
References base, llvm::SmallString< InternalLen >::c_str(), llvm::createError(), llvm::Data, E, ECASE, move, llvm::object::DataRefImpl::p, llvm::XCOFF::STYP_BSS, llvm::XCOFF::STYP_DATA, llvm::XCOFF::STYP_DEBUG, llvm::XCOFF::STYP_DWARF, llvm::XCOFF::STYP_EXCEPT, llvm::XCOFF::STYP_INFO, llvm::XCOFF::STYP_LOADER, llvm::XCOFF::STYP_OVRFLO, llvm::XCOFF::STYP_PAD, llvm::XCOFF::STYP_TBSS, llvm::XCOFF::STYP_TDATA, llvm::XCOFF::STYP_TEXT, llvm::XCOFF::STYP_TYPCHK, llvm::toString(), llvm::Twine::toVector(), uint64_t, and llvm::Twine::utohexstr().
getSectionFlags()
int32_t llvm::object::XCOFFObjectFile::getSectionFlags (DataRefImpl Sec) const
Definition at line 955 of file XCOFFObjectFile.cpp.
References is64Bit().
Referenced by llvm::object::XCOFFSymbolRef::isFunction().
getSectionIndex()
uint64_t llvm::object::XCOFFObjectFile::getSectionIndex (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 379 of file XCOFFObjectFile.cpp.
References is64Bit().
getSectionName()
Expected< StringRef > llvm::object::XCOFFObjectFile::getSectionName (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 366 of file XCOFFObjectFile.cpp.
References llvm::object::generateXCOFFFixedNameStringRef().
getSectionSize()
uint64_t llvm::object::XCOFFObjectFile::getSectionSize (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 388 of file XCOFFObjectFile.cpp.
References is64Bit().
Referenced by getExceptionEntries().
getStartAddress()
Expected< uint64_t > llvm::object::XCOFFObjectFile::getStartAddress () const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 725 of file XCOFFObjectFile.cpp.
getStringTable()
StringRef llvm::object::XCOFFObjectFile::getStringTable () const
Definition at line 239 of file XCOFFObjectFile.cpp.
getStringTableEntry()
Expected< StringRef > llvm::object::XCOFFObjectFile::getStringTableEntry (uint32_t Offset) const
Definition at line 222 of file XCOFFObjectFile.cpp.
References llvm::createError(), and llvm::Twine::utohexstr().
Referenced by llvm::object::XCOFFSymbolRef::getName().
getSymbolAddress()
Expected< uint64_t > llvm::object::XCOFFObjectFile::getSymbolAddress (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 257 of file XCOFFObjectFile.cpp.
getSymbolAlignment()
uint32_t llvm::object::XCOFFObjectFile::getSymbolAlignment (DataRefImpl Symb) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 265 of file XCOFFObjectFile.cpp.
References llvm::consumeError(), llvm::Expected< T >::get(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef(), llvm::object::XCOFFSymbolRef::isCsectSymbol(), llvm::Expected< T >::takeError(), and uint64_t.
getSymbolAuxType()
const XCOFF::SymbolAuxType * llvm::object::XCOFFObjectFile::getSymbolAuxType (uintptr_t AuxEntryAddress) const
Definition at line 127 of file XCOFFObjectFile.cpp.
References assert(), llvm::object::getWithOffset(), is64Bit(), and llvm::object::SymbolAuxTypeOffset.
getSymbolByIndex()
uintptr_t llvm::object::XCOFFObjectFile::getSymbolByIndex (uint32_t Idx) const inline
Definition at line 668 of file XCOFFObjectFile.h.
References llvm::XCOFF::SymbolTableEntrySize.
getSymbolEntryAddressByIndex()
uintptr_t llvm::object::XCOFFObjectFile::getSymbolEntryAddressByIndex (uint32_t SymbolTableIndex) const
Definition at line 924 of file XCOFFObjectFile.cpp.
getSymbolFlags()
Expected< uint32_t > llvm::object::XCOFFObjectFile::getSymbolFlags (DataRefImpl Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 639 of file XCOFFObjectFile.cpp.
References llvm::XCOFF::C_EXT, llvm::XCOFF::C_WEAKEXT, llvm::Expected< T >::get(), llvm::object::XCOFFSymbolRef::getSectionNumber(), llvm::object::XCOFFSymbolRef::getStorageClass(), llvm::object::XCOFFSymbolRef::getSymbolType(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef(), is64Bit(), llvm::object::XCOFFSymbolRef::isCsectSymbol(), llvm::XCOFF::N_ABS, llvm::XCOFF::N_UNDEF, llvm::XCOFF::NEW_XCOFF_INTERPRET, llvm::PPCISD::SC, llvm::XCOFF::SYM_V_EXPORTED, llvm::XCOFF::SYM_V_HIDDEN, llvm::Expected< T >::takeError(), llvm::XCOFF::VISIBILITY_MASK, and llvm::XCOFF::XTY_CM.
getSymbolIndex()
uint32_t llvm::object::XCOFFObjectFile::getSymbolIndex (uintptr_t SymEntPtr) const
Definition at line 899 of file XCOFFObjectFile.cpp.
References llvm::XCOFF::SymbolTableEntrySize.
getSymbolName()
Expected< StringRef > llvm::object::XCOFFObjectFile::getSymbolName (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 253 of file XCOFFObjectFile.cpp.
getSymbolNameByIndex()
Expected< StringRef > llvm::object::XCOFFObjectFile::getSymbolNameByIndex (uint32_t SymbolTableIndex) const
Definition at line 930 of file XCOFFObjectFile.cpp.
References llvm::createError(), getSymbolName(), and llvm::object::DataRefImpl::p.
getSymbolSection()
Expected< section_iterator > llvm::object::XCOFFObjectFile::getSymbolSection (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 348 of file XCOFFObjectFile.cpp.
References llvm::Expected< T >::get(), llvm::COFF::isReservedSectionNumber(), and llvm::Expected< T >::takeError().
getSymbolSectionID()
unsigned llvm::object::XCOFFObjectFile::getSymbolSectionID (SymbolRef Sym) const
Definition at line 825 of file XCOFFObjectFile.cpp.
References llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::XCOFFSymbolRef::getSectionNumber().
getSymbolSectionName()
Expected< StringRef > llvm::object::XCOFFObjectFile::getSymbolSectionName (XCOFFSymbolRef Ref) const
Definition at line 806 of file XCOFFObjectFile.cpp.
References llvm::object::generateXCOFFFixedNameStringRef(), llvm::Expected< T >::get(), llvm::object::XCOFFSymbolRef::getSectionNumber(), llvm::XCOFF::N_ABS, llvm::XCOFF::N_DEBUG, llvm::XCOFF::N_UNDEF, and llvm::Expected< T >::takeError().
getSymbolSize()
uint64_t llvm::object::XCOFFObjectFile::getSymbolSize (DataRefImpl Symb) const
Definition at line 905 of file XCOFFObjectFile.cpp.
References llvm::consumeError(), llvm::Expected< T >::get(), llvm::object::XCOFFCsectAuxRef::getSectionOrLength(), llvm::object::XCOFFCsectAuxRef::getSymbolType(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef(), llvm::object::XCOFFSymbolRef::isCsectSymbol(), llvm::Expected< T >::takeError(), uint64_t, llvm::XCOFF::XTY_CM, and llvm::XCOFF::XTY_SD.
getSymbolTableOffset32()
uint32_t llvm::object::XCOFFObjectFile::getSymbolTableOffset32 () const
Definition at line 848 of file XCOFFObjectFile.cpp.
getSymbolTableOffset64()
uint64_t llvm::object::XCOFFObjectFile::getSymbolTableOffset64 () const
Definition at line 865 of file XCOFFObjectFile.cpp.
getSymbolType()
Expected< SymbolRef::Type > llvm::object::XCOFFObjectFile::getSymbolType (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 299 of file XCOFFObjectFile.cpp.
References llvm::XCOFF::C_FILE, llvm::Expected< T >::get(), llvm::object::XCOFFSymbolRef::getName(), llvm::object::XCOFFSymbolRef::getSectionNumber(), llvm::object::XCOFFSymbolRef::getStorageClass(), is64Bit(), isDebugSection(), llvm::object::XCOFFSymbolRef::isFunction(), and llvm::Expected< T >::takeError().
getSymbolValueImpl()
uint64_t llvm::object::XCOFFObjectFile::getSymbolValueImpl (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 261 of file XCOFFObjectFile.cpp.
getTimeStamp()
int32_t llvm::object::XCOFFObjectFile::getTimeStamp () const
Definition at line 839 of file XCOFFObjectFile.cpp.
References is64Bit().
is64Bit()
bool llvm::object::XCOFFObjectFile::is64Bit () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 756 of file XCOFFObjectFile.cpp.
References getType().
Referenced by getExceptionEntries(), getImportFileTable(), getNumberOfRelocationEntries(), sections32(), sections64(), and llvm::object::XCOFFSymbolRef::XCOFFSymbolRef().
isDebugSection()
bool llvm::object::XCOFFObjectFile::isDebugSection (DataRefImpl Sec) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 498 of file XCOFFObjectFile.cpp.
References getSectionFlags(), llvm::XCOFF::STYP_DEBUG, and llvm::XCOFF::STYP_DWARF.
isRelocatableObject()
bool llvm::object::XCOFFObjectFile::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 719 of file XCOFFObjectFile.cpp.
References is64Bit(), and llvm::object::NoRelMask.
isSectionBSS()
bool llvm::object::XCOFFObjectFile::isSectionBSS (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 493 of file XCOFFObjectFile.cpp.
References getSectionFlags(), llvm::XCOFF::STYP_BSS, and llvm::XCOFF::STYP_TBSS.
isSectionCompressed()
bool llvm::object::XCOFFObjectFile::isSectionCompressed (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 480 of file XCOFFObjectFile.cpp.
isSectionData()
bool llvm::object::XCOFFObjectFile::isSectionData (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 488 of file XCOFFObjectFile.cpp.
References getSectionFlags(), llvm::XCOFF::STYP_DATA, and llvm::XCOFF::STYP_TDATA.
isSectionText()
bool llvm::object::XCOFFObjectFile::isSectionText (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 484 of file XCOFFObjectFile.cpp.
References getSectionFlags(), and llvm::XCOFF::STYP_TEXT.
isSectionVirtual()
bool llvm::object::XCOFFObjectFile::isSectionVirtual (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 503 of file XCOFFObjectFile.cpp.
References is64Bit().
mapDebugSectionName()
StringRef llvm::object::XCOFFObjectFile::mapDebugSectionName (StringRef Name) const override virtual
Maps a debug section name to a standard DWARF section name.
Reimplemented from llvm::object::ObjectFile.
Definition at line 731 of file XCOFFObjectFile.cpp.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
moveRelocationNext()
void llvm::object::XCOFFObjectFile::moveRelocationNext (DataRefImpl & Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 560 of file XCOFFObjectFile.cpp.
References is64Bit(), and llvm::object::DataRefImpl::p.
moveSectionNext()
void llvm::object::XCOFFObjectFile::moveSectionNext (DataRefImpl & Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 361 of file XCOFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, and Ptr.
moveSymbolNext()
void llvm::object::XCOFFObjectFile::moveSymbolNext (DataRefImpl & Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 209 of file XCOFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
relocations()
template<typename Shdr , typename Reloc > Expected< ArrayRef< Reloc > > llvm::object::XCOFFObjectFile::relocations (const Shdr & Sec) const
Definition at line 1001 of file XCOFFObjectFile.cpp.
References llvm::object::createError(), llvm::object::Binary::Data, E, getNumberOfRelocationEntries(), llvm::object::getWithOffset(), move, llvm::XCOFF::RelocationSerializationSize32, llvm::XCOFF::RelocationSerializationSize64, llvm::toString(), and llvm::Twine::utohexstr().
section_begin()
section_iterator llvm::object::XCOFFObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 692 of file XCOFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
section_end()
section_iterator llvm::object::XCOFFObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 698 of file XCOFFObjectFile.cpp.
References llvm::object::getWithOffset(), and llvm::object::DataRefImpl::p.
section_rel_begin()
relocation_iterator llvm::object::XCOFFObjectFile::section_rel_begin (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 508 of file XCOFFObjectFile.cpp.
References llvm::consumeError(), E, is64Bit(), move, and llvm::MipsISD::Ret.
section_rel_end()
relocation_iterator llvm::object::XCOFFObjectFile::section_rel_end (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 534 of file XCOFFObjectFile.cpp.
References llvm::consumeError(), E, is64Bit(), move, and llvm::MipsISD::Ret.
sections32()
ArrayRef< XCOFFSectionHeader32 > llvm::object::XCOFFObjectFile::sections32 () const
Definition at line 971 of file XCOFFObjectFile.cpp.
References assert(), getNumberOfSections(), and is64Bit().
Referenced by getNumberOfRelocationEntries().
sections64()
ArrayRef< XCOFFSectionHeader64 > llvm::object::XCOFFObjectFile::sections64 () const
Definition at line 964 of file XCOFFObjectFile.cpp.
References assert(), getNumberOfSections(), and is64Bit().
symbol_begin()
basic_symbol_iterator llvm::object::XCOFFObjectFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 679 of file XCOFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
symbol_end()
basic_symbol_iterator llvm::object::XCOFFObjectFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 685 of file XCOFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
toSymbolRef()
XCOFFSymbolRef llvm::object::XCOFFObjectFile::toSymbolRef (DataRefImpl Ref) const
Definition at line 165 of file XCOFFObjectFile.cpp.
References assert(), and llvm::Ref.
Friends And Related Function Documentation
ObjectFile::createXCOFFObjectFile
Expected<std::unique_ptr<ObjectFile> > ObjectFile::createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType) friend
Member Data Documentation
InvalidRelocOffset
constexpr uint64_t llvm::object::XCOFFObjectFile::InvalidRelocOffset static constexpr
Initial value:
=
      std::numeric_limits<uint64_t>::max()
Definition at line 571 of file XCOFFObjectFile.h.
The documentation for this class was generated from the following files:
include/llvm/Object/XCOFFObjectFile.h
lib/Object/XCOFFObjectFile.cpp