LLVM: llvm::VPRecipeBuilder Class Reference
llvm::VPRecipeBuilder Class Reference
Helper class to create VPRecipies from IR instructions.
#include "Transforms/Vectorize/VPRecipeBuilder.h"
Public Member Functions
VPRecipeBuilder (Loop *OrigLoop, const TargetLibraryInfo *TLI, LoopVectorizationLegality *Legal, LoopVectorizationCostModel &CM, PredicatedScalarEvolution &PSE, VPBuilder &Builder)
VPRecipeOrVPValueTy tryToCreateWidenRecipe (Instruction *Instr, ArrayRef< VPValue * > Operands, VFRange &Range, VPBasicBlock *VPBB, VPlanPtr &Plan)
Check if an existing VPValue can be used for Instr or a recipe can be create for I withing the given VF Range.
void setRecipe (Instruction *I, VPRecipeBase *R)
Set the recipe created for given ingredient.
VPValue * createBlockInMask (BasicBlock *BB, VPlan &Plan)
A helper function that computes the predicate of the block BB, assuming that the header block of the loop is set to True.
VPValue * createEdgeMask (BasicBlock *Src, BasicBlock *Dst, VPlan &Plan)
A helper function that computes the predicate of the edge between SRC and DST.
void recordRecipeOf (Instruction *I)
Mark given ingredient for recording its recipe once one is created for it.
VPRecipeBase * getRecipe (Instruction *I)
Return the recipe created for given ingredient.
VPRegionBlock * createReplicateRegion (VPReplicateRecipe *PredRecipe, VPlan &Plan)
Create a replicating region for PredRecipe.
VPBasicBlock * handleReplication (Instruction *I, VFRange &Range, VPBasicBlock *VPBB, VPlan &Plan)
Build a VPReplicationRecipe for I and enclose it within a Region if it is predicated.
void fixHeaderPhis ()
Add the incoming values from the backedge to reduction & first-order recurrence cross-iteration phis.
Detailed Description
Helper class to create VPRecipies from IR instructions.
Definition at line 27 of file VPRecipeBuilder.h.
Constructor & Destructor Documentation
VPRecipeBuilder()
llvm::VPRecipeBuilder::VPRecipeBuilder (Loop * OrigLoop, const TargetLibraryInfo * TLI, LoopVectorizationLegality * Legal, LoopVectorizationCostModel & CM, PredicatedScalarEvolution & PSE, VPBuilder & Builder) inline
Definition at line 110 of file VPRecipeBuilder.h.
References Builder, and llvm::IRSimilarity::Legal.
Member Function Documentation
createBlockInMask()
VPValue * VPRecipeBuilder::createBlockInMask (BasicBlock * BB, VPlan & Plan)
A helper function that computes the predicate of the block BB, assuming that the header block of the loop is set to True.
It returns the entry mask for the block BB.
Definition at line 8122 of file LoopVectorize.cpp.
References llvm::VPInstruction::ActiveLaneMask, assert(), BB, llvm::InnerLoopVectorizer::Builder, llvm::LoopBase< BlockT, LoopT >::contains(), llvm::DataAndControlFlow, llvm::DataWithoutLaneMask, llvm::VPlan::getActiveLaneMaskPhi(), llvm::VPlan::getCanonicalIV(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBasicBlock::getFirstNonPhi(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::VPlan::getOrCreateBackedgeTakenCount(), llvm::VPlan::getOrCreateTripCount(), llvm::VPlan::getVectorLoopRegion(), llvm::VPInstruction::ICmpULE, llvm::VPBasicBlock::insert(), IV, llvm::None, llvm::InnerLoopVectorizer::OrigLoop, and llvm::predecessors().
createEdgeMask()
VPValue * VPRecipeBuilder::createEdgeMask (BasicBlock * Src, BasicBlock * Dst, VPlan & Plan)
A helper function that computes the predicate of the edge between SRC and DST.
Definition at line 8077 of file LoopVectorize.cpp.
References assert(), llvm::InnerLoopVectorizer::Builder, llvm::BranchInst::getCondition(), llvm::Instruction::getDebugLoc(), llvm::ConstantInt::getFalse(), llvm::VPlan::getOrAddVPValue(), llvm::BranchInst::getSuccessor(), llvm::Value::getType(), llvm::is_contained(), llvm::BranchInst::isConditional(), llvm::LoopBase< BlockT, LoopT >::isLoopExiting(), llvm::InnerLoopVectorizer::OrigLoop, and llvm::predecessors().
createReplicateRegion()
VPRegionBlock * VPRecipeBuilder::createReplicateRegion (VPReplicateRecipe * PredRecipe, VPlan & Plan)
Create a replicating region for PredRecipe.
Definition at line 8625 of file LoopVectorize.cpp.
References assert(), llvm::Instruction::getOpcodeName(), llvm::Instruction::getParent(), and llvm::VPRecipeBase::getUnderlyingInstr().
fixHeaderPhis()
void VPRecipeBuilder::fixHeaderPhis ()
Add the incoming values from the backedge to reduction & first-order recurrence cross-iteration phis.
Definition at line 8533 of file LoopVectorize.cpp.
References llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::VPDef::getVPSingleValue(), and llvm::InnerLoopVectorizer::OrigLoop.
getRecipe()
VPRecipeBase* llvm::VPRecipeBuilder::getRecipe (Instruction * I) inline
Return the recipe created for given ingredient.
Definition at line 154 of file VPRecipeBuilder.h.
References assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::count(), and I.
handleReplication()
VPBasicBlock * VPRecipeBuilder::handleReplication (Instruction * I, VFRange & Range, VPBasicBlock * VPBB, VPlan & Plan)
Build a VPReplicationRecipe for I and enclose it within a Region if it is predicated.
Returns
VPBB augmented with this new recipe if I is not predicated, otherwise
a new VPBasicBlock that succeeds the new Region. Update the packing decision of predicated instructions if they feed I. Range.End may be decreased to ensure same recipe behavior from Range.Start to Range.End.
Definition at line 8543 of file LoopVectorize.cpp.
References llvm::VPlan::addVPValue(), llvm::VPBasicBlock::appendRecipe(), assert(), llvm::VPBlockUtils::connectBlocks(), llvm::dbgs(), llvm::VPBlockUtils::disconnectBlocks(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), getIntrinsicID(), llvm::VPBlockBase::getSingleSuccessor(), I, llvm::VPBlockUtils::insertBlockAfter(), LLVM_DEBUG, llvm::VPlan::mapToVPValues(), and llvm::InnerLoopVectorizer::VF.
recordRecipeOf()
void llvm::VPRecipeBuilder::recordRecipeOf (Instruction * I) inline
Mark given ingredient for recording its recipe once one is created for it.
Definition at line 147 of file VPRecipeBuilder.h.
References assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::count(), and I.
setRecipe()
void llvm::VPRecipeBuilder::setRecipe (Instruction * I, VPRecipeBase * R) inline
Set the recipe created for given ingredient.
This operation is a no-op for ingredients that were not marked using a nullptr entry in the map.
Definition at line 128 of file VPRecipeBuilder.h.
References assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::count(), and I.
tryToCreateWidenRecipe()
VPRecipeOrVPValueTy VPRecipeBuilder::tryToCreateWidenRecipe (Instruction * Instr, ArrayRef< VPValue * > Operands, VFRange & Range, VPBasicBlock * VPBB, VPlanPtr & Plan)
Check if an existing VPValue can be used for Instr or a recipe can be create for I withing the given VF Range.
If an existing VPValue can be used or if a recipe can be created, return it. Otherwise return a VPRecipeOrVPValueTy with nullptr.
Definition at line 8662 of file LoopVectorize.cpp.
References assert(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), GEP, llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::Instruction::getParent(), llvm::RecurrenceDescriptor::getRecurrenceStartValue(), llvm::LoopVectorizationLegality::getReductionVars(), llvm::PredicatedScalarEvolution::getSCEV(), llvm::PredicatedScalarEvolution::getSE(), llvm::LoopVectorizationLegality::isFixedOrderRecurrence(), llvm::ScalarEvolution::isLoopInvariant(), llvm::LoopVectorizationLegality::isReductionVariable(), llvm::ElementCount::isScalar(), llvm::InnerLoopVectorizer::Legal, llvm::make_range(), Operands, llvm::InnerLoopVectorizer::OrigLoop, llvm::InnerLoopVectorizer::PSE, SI, and llvm::InnerLoopVectorizer::VF.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPRecipeBuilder.h
lib/Transforms/Vectorize/LoopVectorize.cpp