LLVM: llvm::RewriteSymbolPass Class Reference
llvm::RewriteSymbolPass Class Reference
#include "llvm/Transforms/Utils/SymbolRewriter.h"
Public Member Functions
RewriteSymbolPass ()
RewriteSymbolPass (SymbolRewriter::RewriteDescriptorList &DL)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
bool runImpl (Module &M)
Public Member Functions inherited from llvm::PassInfoMixin< RewriteSymbolPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< RewriteSymbolPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 120 of file SymbolRewriter.h.
Constructor & Destructor Documentation
RewriteSymbolPass() [1/2]
llvm::RewriteSymbolPass::RewriteSymbolPass () inline
Definition at line 122 of file SymbolRewriter.h.
RewriteSymbolPass() [2/2]
llvm::RewriteSymbolPass::RewriteSymbolPass (SymbolRewriter::RewriteDescriptorList & DL) inline
Definition at line 124 of file SymbolRewriter.h.
References DL.
Member Function Documentation
run()
PreservedAnalyses RewriteSymbolPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 551 of file SymbolRewriter.cpp.
References llvm::PreservedAnalyses::all(), M, llvm::PreservedAnalyses::none(), and runImpl().
runImpl()
bool RewriteSymbolPass::runImpl (Module & M)
Definition at line 558 of file SymbolRewriter.cpp.
References M.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/SymbolRewriter.h
lib/Transforms/Utils/SymbolRewriter.cpp