LLVM: llvm::SampleContextTracker Class Reference
llvm::SampleContextTracker Class Reference
#include "llvm/Transforms/IPO/SampleContextTracker.h"
Classes
class Iterator
Public Types
using ContextSamplesTy = std::vector< FunctionSamples * >
Public Member Functions
SampleContextTracker ()=default
SampleContextTracker (SampleProfileMap &Profiles, const DenseMap< uint64_t, StringRef > *GUIDToFuncNameMap)
void populateFuncToCtxtMap ()
FunctionSamples * getCalleeContextSamplesFor (const CallBase &Inst, StringRef CalleeName)
std::vector< const FunctionSamples * > getIndirectCalleeContextSamplesFor (const DILocation *DIL)
FunctionSamples * getContextSamplesFor (const DILocation *DIL)
FunctionSamples * getContextSamplesFor (const SampleContext &Context)
ContextSamplesTy & getAllContextSamplesFor (const Function &Func)
ContextSamplesTy & getAllContextSamplesFor (StringRef Name)
ContextTrieNode * getOrCreateContextPath (const SampleContext &Context, bool AllowCreate)
FunctionSamples * getBaseSamplesFor (const Function &Func, bool MergeContext=true)
FunctionSamples * getBaseSamplesFor (StringRef Name, bool MergeContext=true)
ContextTrieNode * getContextFor (const SampleContext &Context)
StringRef getFuncNameFor (ContextTrieNode *Node) const
void markContextSamplesInlined (const FunctionSamples *InlinedSamples)
ContextTrieNode & getRootContext ()
void promoteMergeContextSamplesTree (const Instruction &Inst, StringRef CalleeName)
void createContextLessProfileMap (SampleProfileMap &ContextLessProfiles)
ContextTrieNode * getContextNodeForProfile (const FunctionSamples *FSamples) const
StringMap< ContextSamplesTy > & getFuncToCtxtProfiles ()
Iterator begin ()
Iterator end ()
std::string getContextString (const FunctionSamples &FSamples) const
std::string getContextString (ContextTrieNode *Node) const
void dump ()
Detailed Description
Definition at line 90 of file SampleContextTracker.h.
Member Typedef Documentation
ContextSamplesTy
using llvm::SampleContextTracker::ContextSamplesTy = std::vector<FunctionSamples *>
Definition at line 92 of file SampleContextTracker.h.
Constructor & Destructor Documentation
SampleContextTracker() [1/2]
llvm::SampleContextTracker::SampleContextTracker () default
SampleContextTracker() [2/2]
llvm::SampleContextTracker::SampleContextTracker (SampleProfileMap & Profiles, const DenseMap< uint64_t, StringRef > * GUIDToFuncNameMap)
Definition at line 198 of file SampleContextTracker.cpp.
References assert(), Context, llvm::dbgs(), llvm::ContextTrieNode::getFunctionSamples(), getOrCreateContextPath(), LLVM_DEBUG, populateFuncToCtxtMap(), and llvm::ContextTrieNode::setFunctionSamples().
Member Function Documentation
begin()
Iterator llvm::SampleContextTracker::begin () inline
Definition at line 178 of file SampleContextTracker.h.
createContextLessProfileMap()
void llvm::SampleContextTracker::createContextLessProfileMap (SampleProfileMap & ContextLessProfiles)
Definition at line 635 of file SampleContextTracker.cpp.
dump()
void llvm::SampleContextTracker::dump ()
Definition at line 457 of file SampleContextTracker.cpp.
References llvm::ContextTrieNode::dumpTree().
end()
Iterator llvm::SampleContextTracker::end () inline
Definition at line 179 of file SampleContextTracker.h.
getAllContextSamplesFor() [1/2]
SampleContextTracker::ContextSamplesTy & llvm::SampleContextTracker::getAllContextSamplesFor (const Function & Func)
Definition at line 306 of file SampleContextTracker.cpp.
References llvm::sampleprof::FunctionSamples::getCanonicalFnName().
getAllContextSamplesFor() [2/2]
SampleContextTracker::ContextSamplesTy & llvm::SampleContextTracker::getAllContextSamplesFor (StringRef Name)
Definition at line 312 of file SampleContextTracker.cpp.
getBaseSamplesFor() [1/2]
FunctionSamples * llvm::SampleContextTracker::getBaseSamplesFor (const Function & Func, bool MergeContext = true)
Definition at line 316 of file SampleContextTracker.cpp.
References llvm::sampleprof::FunctionSamples::getCanonicalFnName().
getBaseSamplesFor() [2/2]
FunctionSamples * llvm::SampleContextTracker::getBaseSamplesFor (StringRef Name, bool MergeContext = true)
Definition at line 322 of file SampleContextTracker.cpp.
References llvm::dbgs(), llvm::sampleprof::getRepInFormat(), LLVM_DEBUG, and llvm::sampleprof::FunctionSamples::UseMD5.
getCalleeContextSamplesFor()
FunctionSamples * llvm::SampleContextTracker::getCalleeContextSamplesFor (const CallBase & Inst, StringRef CalleeName)
Definition at line 227 of file SampleContextTracker.cpp.
References llvm::dbgs(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), getContextString(), llvm::Instruction::getDebugLoc(), llvm::ContextTrieNode::getFunctionSamples(), llvm::sampleprof::getRepInFormat(), LLVM_DEBUG, and llvm::sampleprof::FunctionSamples::UseMD5.
getContextFor()
ContextTrieNode * llvm::SampleContextTracker::getContextFor (const SampleContext & Context)
Definition at line 467 of file SampleContextTracker.cpp.
References Context, and getOrCreateContextPath().
Referenced by getContextSamplesFor(), getIndirectCalleeContextSamplesFor(), and promoteMergeContextSamplesTree().
getContextNodeForProfile()
ContextTrieNode* llvm::SampleContextTracker::getContextNodeForProfile (const FunctionSamples * FSamples) const inline
Definition at line 137 of file SampleContextTracker.h.
References I.
Referenced by getContextString().
getContextSamplesFor() [1/2]
FunctionSamples * llvm::SampleContextTracker::getContextSamplesFor (const DILocation * DIL)
Definition at line 276 of file SampleContextTracker.cpp.
References assert(), llvm::sampleprof::FunctionSamples::getContext(), getContextFor(), llvm::ContextTrieNode::getFunctionSamples(), llvm::ContextTrieNode::getParentContext(), llvm::sampleprof::InlinedContext, and llvm::sampleprof::SampleContext::setState().
getContextSamplesFor() [2/2]
FunctionSamples * llvm::SampleContextTracker::getContextSamplesFor (const SampleContext & Context)
Definition at line 297 of file SampleContextTracker.cpp.
getContextString() [1/2]
std::string llvm::SampleContextTracker::getContextString (const FunctionSamples & FSamples) const
Definition at line 432 of file SampleContextTracker.cpp.
References getContextNodeForProfile().
Referenced by getCalleeContextSamplesFor(), and markContextSamplesInlined().
getContextString() [2/2]
std::string llvm::SampleContextTracker::getContextString (ContextTrieNode * Node) const
Definition at line 437 of file SampleContextTracker.cpp.
getFuncNameFor()
StringRef llvm::SampleContextTracker::getFuncNameFor (ContextTrieNode * Node) const
Definition at line 459 of file SampleContextTracker.cpp.
Referenced by llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph().
getFuncToCtxtProfiles()
StringMap<ContextSamplesTy>& llvm::SampleContextTracker::getFuncToCtxtProfiles () inline
Definition at line 143 of file SampleContextTracker.h.
getIndirectCalleeContextSamplesFor()
std::vector< const FunctionSamples * > llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor (const DILocation * DIL)
Definition at line 256 of file SampleContextTracker.cpp.
References llvm::ContextTrieNode::getAllChildContext(), llvm::sampleprof::FunctionSamples::getCallSiteIdentifier(), llvm::ContextTrieNode::getCallSiteLoc(), getContextFor(), and llvm::ContextTrieNode::getFunctionSamples().
getOrCreateContextPath()
ContextTrieNode * llvm::SampleContextTracker::getOrCreateContextPath (const SampleContext & Context, bool AllowCreate)
Definition at line 534 of file SampleContextTracker.cpp.
References assert(), Context, llvm::ContextTrieNode::getChildContext(), and llvm::ContextTrieNode::getOrCreateChildContext().
Referenced by getContextFor(), and SampleContextTracker().
getRootContext()
ContextTrieNode & llvm::SampleContextTracker::getRootContext ()
Definition at line 373 of file SampleContextTracker.cpp.
Referenced by llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph().
markContextSamplesInlined()
void llvm::SampleContextTracker::markContextSamplesInlined (const FunctionSamples * InlinedSamples)
Definition at line 365 of file SampleContextTracker.cpp.
References assert(), llvm::dbgs(), llvm::sampleprof::FunctionSamples::getContext(), getContextString(), llvm::sampleprof::InlinedContext, LLVM_DEBUG, and llvm::sampleprof::SampleContext::setState().
populateFuncToCtxtMap()
void llvm::SampleContextTracker::populateFuncToCtxtMap ()
Definition at line 215 of file SampleContextTracker.cpp.
Referenced by SampleContextTracker().
promoteMergeContextSamplesTree()
void llvm::SampleContextTracker::promoteMergeContextSamplesTree (const Instruction & Inst, StringRef CalleeName)
Definition at line 375 of file SampleContextTracker.cpp.
References llvm::dbgs(), llvm::StringRef::empty(), llvm::ContextTrieNode::getAllChildContext(), llvm::sampleprof::FunctionSamples::getCallSiteIdentifier(), llvm::ContextTrieNode::getCallSiteLoc(), llvm::ContextTrieNode::getChildContext(), llvm::sampleprof::FunctionSamples::getContext(), getContextFor(), llvm::Instruction::getDebugLoc(), llvm::ContextTrieNode::getFunctionSamples(), llvm::sampleprof::SampleContext::hasState(), llvm::sampleprof::InlinedContext, and LLVM_DEBUG.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SampleContextTracker.h
lib/Transforms/IPO/SampleContextTracker.cpp