LLVM: llvm::InlineResult Class Reference
llvm::InlineResult Class Reference
InlineResult is basically true or false.
#include "llvm/Analysis/InlineCost.h"
Public Member Functions
bool isSuccess () const
const char * getFailureReason () const
Static Public Member Functions
static InlineResult success ()
static InlineResult failure (const char *Reason)
Detailed Description
InlineResult is basically true or false.
For false results the message describes a reason.
Definition at line 179 of file InlineCost.h.
Member Function Documentation
failure()
static InlineResult llvm::InlineResult::failure (const char * Reason) inline static
Definition at line 185 of file InlineCost.h.
Referenced by llvm::getAttributeBasedInliningDecision(), llvm::InlineFunction(), and llvm::isInlineViable().
getFailureReason()
const char* llvm::InlineResult::getFailureReason () const inline
Definition at line 189 of file InlineCost.h.
References assert(), and isSuccess().
Referenced by llvm::getInlineCost(), and llvm::AlwaysInlinerPass::run().
isSuccess()
bool llvm::InlineResult::isSuccess () const inline
Definition at line 188 of file InlineCost.h.
Referenced by getFailureReason(), llvm::getInlineCost(), InsertSafepointPoll(), and llvm::AlwaysInlinerPass::run().
success()
static InlineResult llvm::InlineResult::success () inline static
Definition at line 184 of file InlineCost.h.
Referenced by llvm::getAttributeBasedInliningDecision(), llvm::InlineFunction(), and llvm::isInlineViable().
The documentation for this class was generated from the following file:
include/llvm/Analysis/InlineCost.h