LLVM: llvm::object::DelayImportDirectoryEntryRef Class Reference
llvm::object::DelayImportDirectoryEntryRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
DelayImportDirectoryEntryRef ()=default
DelayImportDirectoryEntryRef (const delay_import_directory_table_entry *T, uint32_t I, const COFFObjectFile *Owner)
bool operator== (const DelayImportDirectoryEntryRef &Other) const
void moveNext ()
imported_symbol_iterator imported_symbol_begin () const
imported_symbol_iterator imported_symbol_end () const
iterator_range< imported_symbol_iterator > imported_symbols () const
Error getName (StringRef &Result) const
Error getDelayImportTable (const delay_import_directory_table_entry *&Result) const
Error getImportAddress (int AddrIndex, uint64_t &Result) const
Detailed Description
Definition at line 1144 of file COFF.h.
Constructor & Destructor Documentation
DelayImportDirectoryEntryRef() [1/2]
llvm::object::DelayImportDirectoryEntryRef::DelayImportDirectoryEntryRef () default
DelayImportDirectoryEntryRef() [2/2]
llvm::object::DelayImportDirectoryEntryRef::DelayImportDirectoryEntryRef (const delay_import_directory_table_entry * T, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 1147 of file COFF.h.
References T.
Member Function Documentation
getDelayImportTable()
Error DelayImportDirectoryEntryRef::getDelayImportTable (const delay_import_directory_table_entry *& Result) const
Definition at line 1529 of file COFFObjectFile.cpp.
References llvm::Error::success().
getImportAddress()
Error DelayImportDirectoryEntryRef::getImportAddress (int AddrIndex, uint64_t & Result) const
Definition at line 1535 of file COFFObjectFile.cpp.
References llvm::object::delay_import_directory_table_entry::DelayImportAddressTable, E, llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::COFFObjectFile::is64(), and llvm::Error::success().
getName()
Error DelayImportDirectoryEntryRef::getName (StringRef & Result) const
Definition at line 1520 of file COFFObjectFile.cpp.
References E, llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::delay_import_directory_table_entry::Name, and llvm::Error::success().
imported_symbol_begin()
imported_symbol_iterator DelayImportDirectoryEntryRef::imported_symbol_begin () const
Definition at line 1504 of file COFFObjectFile.cpp.
References importedSymbolBegin().
Referenced by imported_symbols().
imported_symbol_end()
imported_symbol_iterator DelayImportDirectoryEntryRef::imported_symbol_end () const
Definition at line 1510 of file COFFObjectFile.cpp.
References importedSymbolEnd().
Referenced by imported_symbols().
imported_symbols()
iterator_range< imported_symbol_iterator > DelayImportDirectoryEntryRef::imported_symbols () const
Definition at line 1516 of file COFFObjectFile.cpp.
References imported_symbol_begin(), imported_symbol_end(), and llvm::make_range().
moveNext()
void DelayImportDirectoryEntryRef::moveNext ()
Definition at line 1499 of file COFFObjectFile.cpp.
operator==()
bool DelayImportDirectoryEntryRef::operator== (const DelayImportDirectoryEntryRef & Other) const
Definition at line 1495 of file COFFObjectFile.cpp.
References Other.
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp