LLVM: llvm::dxil::DXILBitcodeWriter Class Reference
llvm::dxil::DXILBitcodeWriter Class Reference
Public Member Functions
DXILBitcodeWriter (const Module &M, SmallVectorImpl< char > &Buffer, StringTableBuilder &StrtabBuilder, BitstreamWriter &Stream)
Constructs a ModuleBitcodeWriter object for the given Module, writing to the provided Buffer.
void write ()
Emit the current module to the bitstream.
Static Public Member Functions
static uint64_t getAttrKindEncoding (Attribute::AttrKind Kind)
static void writeStringRecord (BitstreamWriter &Stream, unsigned Code, StringRef Str, unsigned AbbrevToUse)
static void writeIdentificationBlock (BitstreamWriter &Stream)
static void emitSignedInt64 (SmallVectorImpl< uint64_t > &Vals, uint64_t V)
static void emitWideAPInt (SmallVectorImpl< uint64_t > &Vals, const APInt &A)
static unsigned getEncodedComdatSelectionKind (const Comdat &C)
static unsigned getEncodedLinkage (const GlobalValue::LinkageTypes Linkage)
static unsigned getEncodedLinkage (const GlobalValue &GV)
static unsigned getEncodedVisibility (const GlobalValue &GV)
static unsigned getEncodedThreadLocalMode (const GlobalValue &GV)
static unsigned getEncodedDLLStorageClass (const GlobalValue &GV)
static unsigned getEncodedCastOpcode (unsigned Opcode)
Begin dxil::BitcodeWriterBase Implementation.
static unsigned getEncodedUnaryOpcode (unsigned Opcode)
static unsigned getEncodedBinaryOpcode (unsigned Opcode)
static unsigned getEncodedRMWOperation (AtomicRMWInst::BinOp Op)
static unsigned getEncodedOrdering (AtomicOrdering Ordering)
static uint64_t getOptimizationFlags (const Value *V)
Detailed Description
Definition at line 65 of file DXILBitcodeWriter.cpp.
Constructor & Destructor Documentation
DXILBitcodeWriter()
llvm::dxil::DXILBitcodeWriter::DXILBitcodeWriter (const Module & M, SmallVectorImpl< char > & Buffer, StringTableBuilder & StrtabBuilder, BitstreamWriter & Stream) inline
Constructs a ModuleBitcodeWriter object for the given Module, writing to the provided Buffer.
Definition at line 133 of file DXILBitcodeWriter.cpp.
References llvm::dxil::ValueEnumerator::EnumerateType(), llvm::dxil::ValueEnumerator::getValues(), and M.
Member Function Documentation
emitSignedInt64()
void DXILBitcodeWriter::emitSignedInt64 (SmallVectorImpl< uint64_t > & Vals, uint64_t V) static
Definition at line 721 of file DXILBitcodeWriter.cpp.
Referenced by emitWideAPInt().
emitWideAPInt()
void DXILBitcodeWriter::emitWideAPInt (SmallVectorImpl< uint64_t > & Vals, const APInt & A) static
Definition at line 729 of file DXILBitcodeWriter.cpp.
References emitSignedInt64(), i, and uint64_t.
getAttrKindEncoding()
uint64_t DXILBitcodeWriter::getAttrKindEncoding (Attribute::AttrKind Kind) static
Definition at line 616 of file DXILBitcodeWriter.cpp.
References llvm::bitc::ATTR_KIND_ALIGNMENT, llvm::bitc::ATTR_KIND_ALWAYS_INLINE, llvm::bitc::ATTR_KIND_BUILTIN, llvm::bitc::ATTR_KIND_BY_VAL, llvm::bitc::ATTR_KIND_COLD, llvm::bitc::ATTR_KIND_CONVERGENT, llvm::bitc::ATTR_KIND_DEREFERENCEABLE, llvm::bitc::ATTR_KIND_DEREFERENCEABLE_OR_NULL, llvm::bitc::ATTR_KIND_IN_ALLOCA, llvm::bitc::ATTR_KIND_IN_REG, llvm::bitc::ATTR_KIND_INLINE_HINT, llvm::bitc::ATTR_KIND_JUMP_TABLE, llvm::bitc::ATTR_KIND_MIN_SIZE, llvm::bitc::ATTR_KIND_NAKED, llvm::bitc::ATTR_KIND_NEST, llvm::bitc::ATTR_KIND_NO_ALIAS, llvm::bitc::ATTR_KIND_NO_BUILTIN, llvm::bitc::ATTR_KIND_NO_CAPTURE, llvm::bitc::ATTR_KIND_NO_DUPLICATE, llvm::bitc::ATTR_KIND_NO_IMPLICIT_FLOAT, llvm::bitc::ATTR_KIND_NO_INLINE, llvm::bitc::ATTR_KIND_NO_RED_ZONE, llvm::bitc::ATTR_KIND_NO_RETURN, llvm::bitc::ATTR_KIND_NO_UNWIND, llvm::bitc::ATTR_KIND_NON_LAZY_BIND, llvm::bitc::ATTR_KIND_NON_NULL, llvm::bitc::ATTR_KIND_OPTIMIZE_FOR_SIZE, llvm::bitc::ATTR_KIND_OPTIMIZE_NONE, llvm::bitc::ATTR_KIND_READ_NONE, llvm::bitc::ATTR_KIND_READ_ONLY, llvm::bitc::ATTR_KIND_RETURNED, llvm::bitc::ATTR_KIND_RETURNS_TWICE, llvm::bitc::ATTR_KIND_S_EXT, llvm::bitc::ATTR_KIND_SAFESTACK, llvm::bitc::ATTR_KIND_SANITIZE_ADDRESS, llvm::bitc::ATTR_KIND_SANITIZE_MEMORY, llvm::bitc::ATTR_KIND_SANITIZE_THREAD, llvm::bitc::ATTR_KIND_STACK_ALIGNMENT, llvm::bitc::ATTR_KIND_STACK_PROTECT, llvm::bitc::ATTR_KIND_STACK_PROTECT_REQ, llvm::bitc::ATTR_KIND_STACK_PROTECT_STRONG, llvm::bitc::ATTR_KIND_STRUCT_RET, llvm::bitc::ATTR_KIND_UW_TABLE, llvm::bitc::ATTR_KIND_Z_EXT, llvm::CallingConv::Cold, llvm::MCID::Convergent, llvm::Attribute::EmptyKey, llvm::Attribute::EndAttrKinds, JumpTable, llvm_unreachable, llvm::Attribute::None, and llvm::Attribute::TombstoneKey.
getEncodedBinaryOpcode()
unsigned DXILBitcodeWriter::getEncodedBinaryOpcode (unsigned Opcode) static
Definition at line 477 of file DXILBitcodeWriter.cpp.
References llvm::MCID::Add, llvm::bitc::BINOP_ADD, llvm::bitc::BINOP_AND, llvm::bitc::BINOP_ASHR, llvm::bitc::BINOP_LSHR, llvm::bitc::BINOP_MUL, llvm::bitc::BINOP_OR, llvm::bitc::BINOP_SDIV, llvm::bitc::BINOP_SHL, llvm::bitc::BINOP_SREM, llvm::bitc::BINOP_SUB, llvm::bitc::BINOP_UDIV, llvm::bitc::BINOP_UREM, llvm::bitc::BINOP_XOR, llvm_unreachable, and Mul.
getEncodedCastOpcode()
unsigned DXILBitcodeWriter::getEncodedCastOpcode (unsigned Opcode) static
Begin dxil::BitcodeWriterBase Implementation.
Definition at line 435 of file DXILBitcodeWriter.cpp.
References llvm::bitc::CAST_ADDRSPACECAST, llvm::bitc::CAST_BITCAST, llvm::bitc::CAST_FPEXT, llvm::bitc::CAST_FPTOSI, llvm::bitc::CAST_FPTOUI, llvm::bitc::CAST_FPTRUNC, llvm::bitc::CAST_INTTOPTR, llvm::bitc::CAST_PTRTOINT, llvm::bitc::CAST_SEXT, llvm::bitc::CAST_SITOFP, llvm::bitc::CAST_TRUNC, llvm::bitc::CAST_UITOFP, llvm::bitc::CAST_ZEXT, and llvm_unreachable.
getEncodedComdatSelectionKind()
unsigned DXILBitcodeWriter::getEncodedComdatSelectionKind (const Comdat & C) static
Definition at line 845 of file DXILBitcodeWriter.cpp.
References llvm::Comdat::Any, llvm::bitc::COMDAT_SELECTION_KIND_ANY, llvm::bitc::COMDAT_SELECTION_KIND_EXACT_MATCH, llvm::bitc::COMDAT_SELECTION_KIND_LARGEST, llvm::bitc::COMDAT_SELECTION_KIND_NO_DUPLICATES, llvm::bitc::COMDAT_SELECTION_KIND_SAME_SIZE, llvm::Comdat::ExactMatch, llvm::Comdat::Largest, llvm_unreachable, llvm::Comdat::NoDeduplicate, and llvm::Comdat::SameSize.
getEncodedDLLStorageClass()
unsigned DXILBitcodeWriter::getEncodedDLLStorageClass (const GlobalValue & GV) static
Definition at line 817 of file DXILBitcodeWriter.cpp.
References llvm::GlobalValue::DefaultStorageClass, llvm::GlobalValue::DLLExportStorageClass, llvm::GlobalValue::DLLImportStorageClass, llvm::GlobalValue::getDLLStorageClass(), and llvm_unreachable.
getEncodedLinkage() [1/2]
unsigned DXILBitcodeWriter::getEncodedLinkage (const GlobalValue & GV) static
Definition at line 801 of file DXILBitcodeWriter.cpp.
References getEncodedLinkage(), and llvm::GlobalValue::getLinkage().
getEncodedLinkage() [2/2]
unsigned DXILBitcodeWriter::getEncodedLinkage (const GlobalValue::LinkageTypes Linkage) static
Definition at line 773 of file DXILBitcodeWriter.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
Referenced by getEncodedLinkage().
getEncodedOrdering()
unsigned DXILBitcodeWriter::getEncodedOrdering (AtomicOrdering Ordering) static
Definition at line 580 of file DXILBitcodeWriter.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm_unreachable, llvm::Monotonic, llvm::NotAtomic, llvm::bitc::ORDERING_ACQREL, llvm::bitc::ORDERING_ACQUIRE, llvm::bitc::ORDERING_MONOTONIC, llvm::bitc::ORDERING_NOTATOMIC, llvm::bitc::ORDERING_RELEASE, llvm::bitc::ORDERING_SEQCST, llvm::bitc::ORDERING_UNORDERED, llvm::Release, llvm::SequentiallyConsistent, and llvm::Unordered.
getEncodedRMWOperation()
unsigned DXILBitcodeWriter::getEncodedRMWOperation (AtomicRMWInst::BinOp Op) static
Definition at line 543 of file DXILBitcodeWriter.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FMax, llvm::AtomicRMWInst::FMin, llvm::AtomicRMWInst::FSub, llvm_unreachable, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::bitc::RMW_ADD, llvm::bitc::RMW_AND, llvm::bitc::RMW_FADD, llvm::bitc::RMW_FMAX, llvm::bitc::RMW_FMIN, llvm::bitc::RMW_FSUB, llvm::bitc::RMW_MAX, llvm::bitc::RMW_MIN, llvm::bitc::RMW_NAND, llvm::bitc::RMW_OR, llvm::bitc::RMW_SUB, llvm::bitc::RMW_UMAX, llvm::bitc::RMW_UMIN, llvm::bitc::RMW_XCHG, llvm::bitc::RMW_XOR, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
getEncodedThreadLocalMode()
unsigned DXILBitcodeWriter::getEncodedThreadLocalMode (const GlobalValue & GV) static
Definition at line 829 of file DXILBitcodeWriter.cpp.
References llvm::GlobalValue::GeneralDynamicTLSModel, llvm::GlobalValue::getThreadLocalMode(), llvm::GlobalValue::InitialExecTLSModel, llvm_unreachable, llvm::GlobalValue::LocalDynamicTLSModel, llvm::GlobalValue::LocalExecTLSModel, and llvm::GlobalValue::NotThreadLocal.
getEncodedUnaryOpcode()
unsigned DXILBitcodeWriter::getEncodedUnaryOpcode (unsigned Opcode) static
Definition at line 468 of file DXILBitcodeWriter.cpp.
References llvm_unreachable, and llvm::bitc::UNOP_FNEG.
getEncodedVisibility()
unsigned DXILBitcodeWriter::getEncodedVisibility (const GlobalValue & GV) static
Definition at line 805 of file DXILBitcodeWriter.cpp.
References llvm::GlobalValue::DefaultVisibility, llvm::GlobalValue::getVisibility(), llvm::GlobalValue::HiddenVisibility, llvm_unreachable, and llvm::GlobalValue::ProtectedVisibility.
getOptimizationFlags()
uint64_t DXILBitcodeWriter::getOptimizationFlags (const Value * V) static
Definition at line 741 of file DXILBitcodeWriter.cpp.
References llvm::bitc::AllowContract, llvm::bitc::AllowReassoc, llvm::bitc::AllowReciprocal, llvm::bitc::ApproxFunc, llvm::bitc::NoInfs, llvm::bitc::NoNaNs, llvm::bitc::NoSignedZeros, llvm::bitc::OBO_NO_SIGNED_WRAP, llvm::bitc::OBO_NO_UNSIGNED_WRAP, llvm::bitc::PEO_EXACT, and uint64_t.
write()
void DXILBitcodeWriter::write ()
Emit the current module to the bitstream.
WriteModule - Emit the specified module to the bitstream.
Definition at line 2877 of file DXILBitcodeWriter.cpp.
References llvm::BitstreamWriter::EnterSubblock(), llvm::BitstreamWriter::ExitBlock(), F, M, and llvm::bitc::MODULE_BLOCK_ID.
Referenced by llvm::dxil::BitcodeWriter::writeModule().
writeIdentificationBlock()
static void llvm::dxil::DXILBitcodeWriter::writeIdentificationBlock (BitstreamWriter & Stream) static
writeStringRecord()
void DXILBitcodeWriter::writeStringRecord (BitstreamWriter & Stream, unsigned Code, StringRef Str, unsigned AbbrevToUse) static
Definition at line 600 of file DXILBitcodeWriter.cpp.
References llvm::BitstreamWriter::EmitRecord(), and llvm::BitCodeAbbrevOp::isChar6().
The documentation for this class was generated from the following file:
lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp