LLVM: llvm::MCRegisterInfo Class Reference
llvm::MCRegisterInfo Class Reference
MCRegisterInfo base class - We assume that the target defines a static array of MCRegisterDesc objects that represent all of the machine registers that the target has.
#include "llvm/MC/MCRegisterInfo.h"
Classes
class DiffListIterator
DiffListIterator - Base iterator class that can traverse the differentially encoded register and regunit lists in DiffLists.
struct DwarfLLVMRegPair
DwarfLLVMRegPair - Emitted by tablegen so Dwarf<->LLVM reg mappings can be performed with a binary search.
class mc_difflist_iterator
Forward iterator using DiffListIterator.
class mc_subreg_iterator
Forward iterator over all sub-registers.
class mc_superreg_iterator
Forward iterator over all super-registers.
struct SubRegCoveredBits
SubRegCoveredBits - Emitted by tablegen: bit range covered by a subreg index, -1 in any being invalid.
Public Types
using regclass_iterator = const MCRegisterClass *
Public Member Functions
iterator_range< mc_subreg_iterator > subregs (MCRegister Reg) const
Return an iterator range over all sub-registers of Reg, excluding Reg.
iterator_range< mc_subreg_iterator > subregs_inclusive (MCRegister Reg) const
Return an iterator range over all sub-registers of Reg, including Reg.
iterator_range< mc_superreg_iterator > superregs (MCRegister Reg) const
Return an iterator range over all super-registers of Reg, excluding Reg.
iterator_range< mc_superreg_iterator > superregs_inclusive (MCRegister Reg) const
Return an iterator range over all super-registers of Reg, including Reg.
detail::concat_range< const MCPhysReg, iterator_range< mc_subreg_iterator >, iterator_range< mc_superreg_iterator > > sub_and_superregs_inclusive (MCRegister Reg) const
Return an iterator range over all sub- and super-registers of Reg, including Reg.
void InitMCRegisterInfo (const MCRegisterDesc *D, unsigned NR, unsigned RA, unsigned PC, const MCRegisterClass *C, unsigned NC, const MCPhysReg(*RURoots)[2], unsigned NRU, const MCPhysReg *DL, const LaneBitmask *RUMS, const char *Strings, const char *ClassStrings, const uint16_t *SubIndices, unsigned NumIndices, const SubRegCoveredBits *SubIdxRanges, const uint16_t *RET)
Initialize MCRegisterInfo, called by TableGen auto-generated routines.
void mapLLVMRegsToDwarfRegs (const DwarfLLVMRegPair *Map, unsigned Size, bool isEH)
Used to initialize LLVM register to Dwarf register number mapping.
void mapDwarfRegsToLLVMRegs (const DwarfLLVMRegPair *Map, unsigned Size, bool isEH)
Used to initialize Dwarf register to LLVM register number mapping.
void mapLLVMRegToSEHReg (MCRegister LLVMReg, int SEHReg)
mapLLVMRegToSEHReg - Used to initialize LLVM register to SEH register number mapping.
void mapLLVMRegToCVReg (MCRegister LLVMReg, int CVReg)
MCRegister getRARegister () const
This method should return the register where the return address can be found.
MCRegister getProgramCounter () const
Return the register which is the program counter.
const MCRegisterDesc & operator[] (MCRegister RegNo) const
const MCRegisterDesc & get (MCRegister RegNo) const
Provide a get method, equivalent to [], but more useful with a pointer to this object.
MCRegister getSubReg (MCRegister Reg, unsigned Idx) const
Returns the physical register number of sub-register "Index" for physical register RegNo.
MCRegister getMatchingSuperReg (MCRegister Reg, unsigned SubIdx, const MCRegisterClass *RC) const
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
unsigned getSubRegIndex (MCRegister RegNo, MCRegister SubRegNo) const
For a given register pair, return the sub-register index if the second register is a sub-register of the first.
unsigned getSubRegIdxSize (unsigned Idx) const
Get the size of the bit range covered by a sub-register index.
unsigned getSubRegIdxOffset (unsigned Idx) const
Get the offset of the bit range covered by a sub-register index.
const char * getName (MCRegister RegNo) const
Return the human-readable symbolic target-specific name for the specified physical register.
unsigned getNumRegs () const
Return the number of registers this target has (useful for sizing arrays holding per register information)
unsigned getNumSubRegIndices () const
Return the number of sub-register indices understood by the target.
unsigned getNumRegUnits () const
Return the number of (native) register units in the target.
int getDwarfRegNum (MCRegister RegNum, bool isEH) const
Map a target register to an equivalent dwarf register number.
std::optional< unsigned > getLLVMRegNum (unsigned RegNum, bool isEH) const
Map a dwarf register back to a target register.
int getDwarfRegNumFromDwarfEHRegNum (unsigned RegNum) const
Map a target EH register number to an equivalent DWARF register number.
int getSEHRegNum (MCRegister RegNum) const
Map a target register to an equivalent SEH register number.
int getCodeViewRegNum (MCRegister RegNum) const
Map a target register to an equivalent CodeView register number.
regclass_iterator regclass_begin () const
regclass_iterator regclass_end () const
iterator_range< regclass_iterator > regclasses () const
unsigned getNumRegClasses () const
const MCRegisterClass & getRegClass (unsigned i) const
Returns the register class associated with the enumeration value.
const char * getRegClassName (const MCRegisterClass *Class) const
uint16_t getEncodingValue (MCRegister RegNo) const
Returns the encoding for RegNo.
bool isSubRegister (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a sub-register of RegA.
bool isSuperRegister (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a super-register of RegA.
bool isSubRegisterEq (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a sub-register of RegA or if RegB == RegA.
bool isSuperRegisterEq (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a super-register of RegA or if RegB == RegA.
bool isSuperOrSubRegisterEq (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a super-register or sub-register of RegA or if RegB == RegA.
bool regsOverlap (MCRegister RegA, MCRegister RegB) const
Returns true if the two registers are equal or alias each other.
Friends
class MCSubRegIterator
class MCSubRegIndexIterator
class MCSuperRegIterator
class MCRegUnitIterator
class MCRegUnitMaskIterator
class MCRegUnitRootIterator
Detailed Description
MCRegisterInfo base class - We assume that the target defines a static array of MCRegisterDesc objects that represent all of the machine registers that the target has.
As such, we simply have to track a pointer to this array so that we can turn register number into a register descriptor.
Note this class is designed to be a base class of TargetRegisterInfo, which is the interface used by codegen. However, specific targets should never specialize this class. MCRegisterInfo should only contain getters to access TableGen generated physical register data. It must not be extended with virtual methods.
Definition at line 135 of file MCRegisterInfo.h.
Member Typedef Documentation
regclass_iterator
using llvm::MCRegisterInfo::regclass_iterator = const MCRegisterClass *
Definition at line 137 of file MCRegisterInfo.h.
Member Function Documentation
get()
const MCRegisterDesc& llvm::MCRegisterInfo::get (MCRegister RegNo) const inline
Provide a get method, equivalent to [], but more useful with a pointer to this object.
Definition at line 454 of file MCRegisterInfo.h.
References operator[]().
Referenced by getName(), getSubReg(), getSubRegIndex(), llvm::MCRegUnitIterator::MCRegUnitIterator(), llvm::MCRegUnitMaskIterator::MCRegUnitMaskIterator(), llvm::MCSubRegIndexIterator::MCSubRegIndexIterator(), llvm::MCSubRegIterator::MCSubRegIterator(), and llvm::MCSuperRegIterator::MCSuperRegIterator().
getCodeViewRegNum()
int MCRegisterInfo::getCodeViewRegNum (MCRegister RegNum) const
Map a target register to an equivalent CodeView register number.
Definition at line 115 of file MCRegisterInfo.cpp.
References getName(), getNumRegs(), I, and llvm::report_fatal_error().
getDwarfRegNum()
int MCRegisterInfo::getDwarfRegNum (MCRegister RegNum, bool isEH) const
Map a target register to an equivalent dwarf register number.
Returns -1 if there is no equivalent value. The second parameter allows targets to use different numberings for EH info and debugging info.
Definition at line 68 of file MCRegisterInfo.cpp.
References I, llvm::lower_bound(), and M.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfExpression::addMachineReg(), llvm::createCFAOffset(), llvm::createDefCFA(), createDefCFAExpression(), llvm::X86InstrInfo::describeLoadedValue(), emitCalleeSavedRestores(), getDwarfRegNum(), getDwarfRegNumFromDwarfEHRegNum(), and llvm::AArch64FrameLowering::resetCFIToInitialState().
getDwarfRegNumFromDwarfEHRegNum()
int MCRegisterInfo::getDwarfRegNumFromDwarfEHRegNum (unsigned RegNum) const
Map a target EH register number to an equivalent DWARF register number.
Definition at line 95 of file MCRegisterInfo.cpp.
References getDwarfRegNum(), and getLLVMRegNum().
getEncodingValue()
uint16_t llvm::MCRegisterInfo::getEncodingValue (MCRegister RegNo) const inline
Returns the encoding for RegNo.
Definition at line 553 of file MCRegisterInfo.h.
References assert().
Referenced by llvm::AArch64InstrInfo::copyGPRRegTuple(), llvm::PPCInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysRegTuple(), llvm::AMDGPUDisassembler::decodeVOPDDstYOp(), llvm::MipsTargetELFStreamer::emitFrame(), expandNOVLXLoad(), expandNOVLXStore(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::PPCMCCodeEmitter::get_crbitm_encoding(), llvm::CSKYMCCodeEmitter::getMachineOpValue(), llvm::PPCMCCodeEmitter::getMachineOpValue(), llvm::MipsMCCodeEmitter::getMachineOpValue(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::MipsMCCodeEmitter::getRegisterListOpValue(), llvm::CSKYMCCodeEmitter::getRegisterSeqOpValue(), llvm::CSKYMCCodeEmitter::getRegSeqImmOpValue(), getTag(), llvm::PPCMCCodeEmitter::getTLSRegEncoding(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), invalidateWindowsRegisterPairing(), llvm::PPCInstPrinter::printOperand(), llvm::ARMInstPrinter::printRegisterList(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::MipsRegInfoRecord::SetPhysRegUsed(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::tryFoldSPUpdateIntoPushPop().
getLLVMRegNum()
std::optional< unsigned > MCRegisterInfo::getLLVMRegNum (unsigned RegNum, bool isEH) const
Map a dwarf register back to a target register.
Returns std::nullopt is there is no mapping.
Definition at line 81 of file MCRegisterInfo.cpp.
References I, llvm::lower_bound(), and M.
Referenced by llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), getDwarfRegNumFromDwarfEHRegNum(), and printCFIRegister().
getMatchingSuperReg()
MCRegister MCRegisterInfo::getMatchingSuperReg (MCRegister Reg, unsigned SubIdx, const MCRegisterClass * RC) const
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
Definition at line 24 of file MCRegisterInfo.cpp.
References llvm::MCRegisterClass::contains(), getSubReg(), and llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), DecodeVRM2RegisterClass(), DecodeVRM4RegisterClass(), DecodeVRM8RegisterClass(), llvm::TargetRegisterInfo::getMatchingSuperReg(), llvm::ARMInstPrinter::printInst(), llvm::AArch64InstPrinter::printRangePrefetchAlias(), and llvm::AArch64InstPrinter::printVectorList().
getName()
const char* llvm::MCRegisterInfo::getName (MCRegister RegNo) const inline
Return the human-readable symbolic target-specific name for the specified physical register.
Definition at line 485 of file MCRegisterInfo.h.
References get(), and llvm::MCRegisterDesc::Name.
Referenced by llvm::AArch64Subtarget::AArch64Subtarget(), llvm::mca::RegisterFile::addRegisterWrite(), llvm::mca::RegisterFile::collectWrites(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::mca::RegisterFile::dump(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), getCodeViewRegNum(), llvm::HexagonEvaluator::getPhysRegBitWidth(), llvm::TargetRegisterInfo::getRegAsmName(), getRegisterName(), llvm::rdf::operator<<(), llvm::MCOperand::print(), llvm::printReg(), llvm::printRegUnit(), llvm::HexagonMCChecker::reportErrorNewValue(), and llvm::HexagonMCChecker::reportErrorRegisters().
getNumRegClasses()
unsigned llvm::MCRegisterInfo::getNumRegClasses () const inline
Definition at line 537 of file MCRegisterInfo.h.
References regclass_begin(), and regclass_end().
Referenced by getRegClass().
getNumRegs()
unsigned llvm::MCRegisterInfo::getNumRegs () const inline
Return the number of registers this target has (useful for sizing arrays holding per register information)
Definition at line 491 of file MCRegisterInfo.h.
Referenced by llvm::MachineFunction::allocateRegMask(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::PPCFrameLowering::assignCalleeSavedSpillSlots(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::CCState::CCState(), llvm::TargetRegisterInfo::checkAllSuperRegsMarked(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::HexagonBlockRanges::computeDeadMap(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::mca::RegisterFile::dump(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::TargetRegisterInfo::getAllocatableSet(), llvm::TargetFrameLowering::getCalleeSaves(), getCodeViewRegNum(), llvm::MachineFrameInfo::getPristineRegs(), llvm::TargetRegisterInfo::getRegisterCosts(), llvm::RegScavenger::getRegsAvailable(), getSubRegIndex(), llvm::hash_value(), llvm::LiveRegSet::init(), llvm::MachineOperand::isIdenticalTo(), llvm::MachineRegisterInfo::MachineRegisterInfo(), LiveDebugValues::MLocTracker::MLocTracker(), llvm::CriticalAntiDepBreaker::Observe(), llvm::AggressiveAntiDepBreaker::Observe(), llvm::rdf::operator<<(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::PhysicalRegisterUsageInfo::print(), llvm::MachineOperand::print(), printCustomRegMask(), llvm::TargetRegisterInfo::regmaskSubsetEqual(), llvm::InterferenceCache::reinitPhysRegEntries(), llvm::rdf::Liveness::resetKills(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::stableHashValue(), llvm::CriticalAntiDepBreaker::StartBlock(), llvm::AggressiveAntiDepBreaker::StartBlock(), and UpdatePredRedefs().
getNumRegUnits()
unsigned llvm::MCRegisterInfo::getNumRegUnits () const inline
Return the number of (native) register units in the target.
Register units are numbered from 0 to getNumRegUnits() - 1. They can be accessed through MCRegUnitIterator defined below.
Definition at line 505 of file MCRegisterInfo.h.
Referenced by llvm::LiveRegUnits::addRegsInMask(), llvm::ReachingDefAnalysis::init(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::printRegUnit(), llvm::LiveRegUnits::removeRegsNotPreserved(), and llvm::LiveIntervals::runOnMachineFunction().
getNumSubRegIndices()
unsigned llvm::MCRegisterInfo::getNumSubRegIndices () const inline
Return the number of sub-register indices understood by the target.
Index 0 is reserved for the no-op sub-register, while 1 to getNumSubRegIndices() - 1 represent real sub-registers.
Definition at line 498 of file MCRegisterInfo.h.
Referenced by llvm::TargetRegisterInfo::getCoveringSubRegIndexes(), llvm::AVRInstPrinter::getPrettyRegisterName(), getSubReg(), getSubRegIdxOffset(), getSubRegIdxSize(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::TargetRegisterInfo::getSubRegIndexName(), and LiveDebugValues::MLocTracker::MLocTracker().
getProgramCounter()
MCRegister llvm::MCRegisterInfo::getProgramCounter () const inline
Return the register which is the program counter.
Definition at line 442 of file MCRegisterInfo.h.
Referenced by llvm::MCInstrDesc::mayAffectControlFlow().
getRARegister()
MCRegister llvm::MCRegisterInfo::getRARegister () const inline
This method should return the register where the return address can be found.
Definition at line 437 of file MCRegisterInfo.h.
Referenced by llvm::MipsAsmPrinter::emitFrameDirective().
getRegClass()
const MCRegisterClass& llvm::MCRegisterInfo::getRegClass (unsigned i) const inline
Returns the register class associated with the enumeration value.
See class MCOperandInfo.
Definition at line 543 of file MCRegisterInfo.h.
References assert(), getNumRegClasses(), and i.
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), getReg(), llvm::ARMInstPrinter::printInst(), llvm::AArch64InstPrinter::printRangePrefetchAlias(), llvm::VEInstPrinter::printRegName(), and llvm::AArch64InstPrinter::printVectorList().
getRegClassName()
const char* llvm::MCRegisterInfo::getRegClassName (const MCRegisterClass * Class) const inline
Definition at line 548 of file MCRegisterInfo.h.
References llvm::tgtok::Class.
Referenced by llvm::TargetRegisterInfo::getRegClassName().
getSEHRegNum()
int MCRegisterInfo::getSEHRegNum (MCRegister RegNum) const
Map a target register to an equivalent SEH register number.
Returns LLVM register number if there is no equivalent value.
Definition at line 109 of file MCRegisterInfo.cpp.
References I.
Referenced by encodeSEHRegNum().
getSubReg()
MCRegister MCRegisterInfo::getSubReg (MCRegister Reg, unsigned Idx) const
Returns the physical register number of sub-register "Index" for physical register RegNo.
Return zero if the sub-register does not exist.
Definition at line 32 of file MCRegisterInfo.cpp.
References assert(), get(), getNumSubRegIndices(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::MCRegisterDesc::SubRegIndices.
Referenced by llvm::AMDGPUDisassembler::convertMIMGInst(), getMatchingSuperReg(), getPairedGPR(), llvm::AVRInstPrinter::getPrettyRegisterName(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::AArch64InstPrinter::printGPR64x8(), llvm::ARMInstPrinter::printGPRPairOperand(), llvm::AArch64InstPrinter::printGPRSeqPairsClassOperand(), llvm::ARMInstPrinter::printMVEVectorList(), llvm::AArch64InstPrinter::printVectorList(), llvm::ARMInstPrinter::printVectorListTwo(), llvm::ARMInstPrinter::printVectorListTwoAllLanes(), llvm::ARMInstPrinter::printVectorListTwoSpaced(), and llvm::ARMInstPrinter::printVectorListTwoSpacedAllLanes().
getSubRegIdxOffset()
unsigned MCRegisterInfo::getSubRegIdxOffset (unsigned Idx) const
Get the offset of the bit range covered by a sub-register index.
If an Offset doesn't make sense (the index isn't continuous, or is used to access sub-registers at different offsets), return -1.
Definition at line 62 of file MCRegisterInfo.cpp.
References assert(), getNumSubRegIndices(), and llvm::MCRegisterInfo::SubRegCoveredBits::Offset.
Referenced by llvm::DwarfExpression::addMachineReg(), LiveDebugValues::MLocTracker::getLocID(), llvm::TargetInstrInfo::getStackSlotRange(), and LiveDebugValues::MLocTracker::MLocTracker().
getSubRegIdxSize()
unsigned MCRegisterInfo::getSubRegIdxSize (unsigned Idx) const
Get the size of the bit range covered by a sub-register index.
If the index isn't continuous, return the sum of the sizes of its parts. If the index is used to access subregisters of different sizes, return -1.
Definition at line 56 of file MCRegisterInfo.cpp.
References assert(), getNumSubRegIndices(), and llvm::MCRegisterInfo::SubRegCoveredBits::Size.
Referenced by llvm::DwarfExpression::addMachineReg(), llvm::TargetInstrInfo::foldMemoryOperand(), LiveDebugValues::MLocTracker::getLocID(), llvm::TargetInstrInfo::getStackSlotRange(), and LiveDebugValues::MLocTracker::MLocTracker().
getSubRegIndex()
unsigned MCRegisterInfo::getSubRegIndex (MCRegister RegNo, MCRegister SubRegNo) const
For a given register pair, return the sub-register index if the second register is a sub-register of the first.
Return zero otherwise.
Definition at line 44 of file MCRegisterInfo.cpp.
References assert(), get(), getNumRegs(), llvm::MCRegisterInfo::DiffListIterator::isValid(), SubReg, and llvm::MCRegisterDesc::SubRegIndices.
Referenced by llvm::DwarfExpression::addMachineReg(), describeMOVrrLoadedValue(), isNopCopy(), and llvm::rdf::PhysicalRegisterInfo::mapTo().
InitMCRegisterInfo()
void llvm::MCRegisterInfo::InitMCRegisterInfo (const MCRegisterDesc * D, unsigned NR, unsigned RA, unsigned PC, const MCRegisterClass * C, unsigned NC, const MCPhysReg(*) RURoots[2], unsigned NRU, const MCPhysReg * DL, const LaneBitmask * RUMS, const char * Strings, const char * ClassStrings, const uint16_t * SubIndices, unsigned NumIndices, const SubRegCoveredBits * SubIdxRanges, const uint16_t * RET) inline
Initialize MCRegisterInfo, called by TableGen auto-generated routines.
DO NOT USE.
Definition at line 353 of file MCRegisterInfo.h.
isSubRegister()
bool llvm::MCRegisterInfo::isSubRegister (MCRegister RegA, MCRegister RegB) const inline
Returns true if RegB is a sub-register of RegA.
Definition at line 560 of file MCRegisterInfo.h.
References isSuperRegister().
Referenced by llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::MipsInstrInfo::describeLoadedValue(), describeORRLoadedValue(), llvm::SITargetLowering::finalizeLowering(), llvm::MachineInstr::findRegisterDefOperandIdx(), isNopCopy(), and isSubRegOf().
isSubRegisterEq()
bool llvm::MCRegisterInfo::isSubRegisterEq (MCRegister RegA, MCRegister RegB) const inline
Returns true if RegB is a sub-register of RegA or if RegB == RegA.
Definition at line 568 of file MCRegisterInfo.h.
References isSuperRegisterEq().
Referenced by llvm::X86InstrInfo::describeLoadedValue(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::MCInstrDesc::hasDefOfPhysReg(), isConvertibleToVMV_V_V(), and isSuperOrSubRegisterEq().
isSuperOrSubRegisterEq()
bool llvm::MCRegisterInfo::isSuperOrSubRegisterEq (MCRegister RegA, MCRegister RegB) const inline
Returns true if RegB is a super-register or sub-register of RegA or if RegB == RegA.
Definition at line 580 of file MCRegisterInfo.h.
References isSubRegisterEq(), and isSuperRegister().
Referenced by llvm::TargetInstrInfo::describeLoadedValue(), describeORRLoadedValue(), llvm::X86RegisterInfo::isArgumentRegister(), and llvm::X86RegisterInfo::isFixedRegister().
isSuperRegister()
bool llvm::MCRegisterInfo::isSuperRegister (MCRegister RegA, MCRegister RegB) const inline
Returns true if RegB is a super-register of RegA.
Definition at line 659 of file MCRegisterInfo.h.
References I.
Referenced by llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::MipsInstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), describeORRLoadedValue(), isSubRegister(), isSuperOrSubRegisterEq(), and isSuperRegisterEq().
isSuperRegisterEq()
bool llvm::MCRegisterInfo::isSuperRegisterEq (MCRegister RegA, MCRegister RegB) const inline
Returns true if RegB is a super-register of RegA or if RegB == RegA.
Definition at line 574 of file MCRegisterInfo.h.
References isSuperRegister().
Referenced by llvm::AnalyzePhysRegInBundle(), llvm::AArch64InstrInfo::describeLoadedValue(), llvm::X86InstrInfo::describeLoadedValue(), and isSubRegisterEq().
mapDwarfRegsToLLVMRegs()
void llvm::MCRegisterInfo::mapDwarfRegsToLLVMRegs (const DwarfLLVMRegPair * Map, unsigned Size, bool isEH) inline
Used to initialize Dwarf register to LLVM register number mapping.
Called by TableGen auto-generated routines. DO NOT USE.
Definition at line 411 of file MCRegisterInfo.h.
References Size.
mapLLVMRegsToDwarfRegs()
void llvm::MCRegisterInfo::mapLLVMRegsToDwarfRegs (const DwarfLLVMRegPair * Map, unsigned Size, bool isEH) inline
Used to initialize LLVM register to Dwarf register number mapping.
Called by TableGen auto-generated routines. DO NOT USE.
Definition at line 397 of file MCRegisterInfo.h.
References Size.
mapLLVMRegToCVReg()
void llvm::MCRegisterInfo::mapLLVMRegToCVReg (MCRegister LLVMReg, int CVReg) inline
Definition at line 431 of file MCRegisterInfo.h.
mapLLVMRegToSEHReg()
void llvm::MCRegisterInfo::mapLLVMRegToSEHReg (MCRegister LLVMReg, int SEHReg) inline
mapLLVMRegToSEHReg - Used to initialize LLVM register to SEH register number mapping.
By default the SEH register number is just the same as the LLVM register number. FIXME: TableGen these numbers. Currently this requires target specific initialization code.
Definition at line 427 of file MCRegisterInfo.h.
operator[]()
const MCRegisterDesc& llvm::MCRegisterInfo::operator[] (MCRegister RegNo) const inline
Definition at line 446 of file MCRegisterInfo.h.
References assert().
Referenced by get().
regclass_begin()
regclass_iterator llvm::MCRegisterInfo::regclass_begin () const inline
Definition at line 531 of file MCRegisterInfo.h.
Referenced by getNumRegClasses(), and regclasses().
regclass_end()
regclass_iterator llvm::MCRegisterInfo::regclass_end () const inline
Definition at line 532 of file MCRegisterInfo.h.
Referenced by getNumRegClasses(), and regclasses().
regclasses()
iterator_range<regclass_iterator> llvm::MCRegisterInfo::regclasses () const inline
Definition at line 533 of file MCRegisterInfo.h.
References llvm::make_range(), regclass_begin(), and regclass_end().
regsOverlap()
bool MCRegisterInfo::regsOverlap (MCRegister RegA, MCRegister RegB) const
Returns true if the two registers are equal or alias each other.
Definition at line 126 of file MCRegisterInfo.cpp.
References isValid().
Referenced by llvm::AArch64RegisterInfo::explainReservedReg(), llvm::AArch64RegisterInfo::isAsmClobberable(), and llvm::TargetRegisterInfo::regsOverlap().
sub_and_superregs_inclusive()
detail::concat_range<const MCPhysReg, iterator_range<mc_subreg_iterator>, iterator_range<mc_superreg_iterator> > llvm::MCRegisterInfo::sub_and_superregs_inclusive (MCRegister Reg) const inline
Return an iterator range over all sub- and super-registers of Reg, including Reg.
Definition at line 338 of file MCRegisterInfo.h.
References subregs_inclusive(), and superregs().
Referenced by tryToFindRegisterToRename().
subregs()
iterator_range<mc_subreg_iterator> llvm::MCRegisterInfo::subregs (MCRegister Reg) const inline
Return an iterator range over all sub-registers of Reg, excluding Reg.
Definition at line 309 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::mc_difflist_iterator< mc_subreg_iterator >::end(), and llvm::make_range().
Referenced by llvm::RegScavenger::forward().
subregs_inclusive()
iterator_range<mc_subreg_iterator> llvm::MCRegisterInfo::subregs_inclusive (MCRegister Reg) const inline
Return an iterator range over all sub-registers of Reg, including Reg.
Definition at line 316 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::mc_difflist_iterator< mc_subreg_iterator >::end(), and llvm::make_range().
Referenced by llvm::MipsRegInfoRecord::SetPhysRegUsed(), and sub_and_superregs_inclusive().
superregs()
iterator_range<mc_superreg_iterator> llvm::MCRegisterInfo::superregs (MCRegister Reg) const inline
Return an iterator range over all super-registers of Reg, excluding Reg.
Definition at line 322 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::mc_difflist_iterator< mc_superreg_iterator >::end(), and llvm::make_range().
Referenced by assignCalleeSavedSpillSlots(), and sub_and_superregs_inclusive().
superregs_inclusive()
iterator_range<mc_superreg_iterator> llvm::MCRegisterInfo::superregs_inclusive (MCRegister Reg) const inline
Return an iterator range over all super-registers of Reg, including Reg.
Definition at line 330 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::mc_difflist_iterator< mc_superreg_iterator >::end(), and llvm::make_range().
Friends And Related Function Documentation
MCRegUnitIterator
friend class MCRegUnitIterator friend
Definition at line 347 of file MCRegisterInfo.h.
MCRegUnitMaskIterator
friend class MCRegUnitMaskIterator friend
Definition at line 348 of file MCRegisterInfo.h.
MCRegUnitRootIterator
friend class MCRegUnitRootIterator friend
Definition at line 349 of file MCRegisterInfo.h.
MCSubRegIndexIterator
friend class MCSubRegIndexIterator friend
Definition at line 345 of file MCRegisterInfo.h.
MCSubRegIterator
friend class MCSubRegIterator friend
Definition at line 344 of file MCRegisterInfo.h.
MCSuperRegIterator
friend class MCSuperRegIterator friend
Definition at line 346 of file MCRegisterInfo.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCRegisterInfo.h
lib/MC/MCRegisterInfo.cpp