LLVM: llvm::MCDwarfLineStr Class Reference
llvm::MCDwarfLineStr Class Reference
Manage the .debug_line_str section contents, if we use it.
#include "llvm/MC/MCDwarf.h"
Public Member Functions
MCDwarfLineStr (MCContext &Ctx)
Construct an instance that can emit .debug_line_str (for use in a normal v5 line table).
StringSaver & getSaver ()
void emitRef (MCStreamer *MCOS, StringRef Path)
Emit a reference to the string.
void emitSection (MCStreamer *MCOS)
Emit the .debug_line_str section if appropriate.
SmallString< 0 > getFinalizedData ()
Returns finalized section.
Detailed Description
Manage the .debug_line_str section contents, if we use it.
Definition at line 51 of file MCDwarf.h.
Constructor & Destructor Documentation
MCDwarfLineStr()
MCDwarfLineStr::MCDwarfLineStr (MCContext & Ctx) explicit
Construct an instance that can emit .debug_line_str (for use in a normal v5 line table).
Definition at line 79 of file MCDwarf.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::MCContext::getAsmInfo(), llvm::MCSection::getBeginSymbol(), llvm::MCObjectFileInfo::getDwarfLineStrSection(), and llvm::MCContext::getObjectFileInfo().
Member Function Documentation
emitRef()
void MCDwarfLineStr::emitRef (MCStreamer * MCOS, StringRef Path)
Emit a reference to the string.
Definition at line 350 of file MCDwarf.cpp.
References llvm::StringTableBuilder::add(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::getContext(), llvm::MCContext::getDwarfFormat(), llvm::dwarf::getDwarfOffsetByteSize(), makeStartPlusIntExpr(), and llvm::Offset.
emitSection()
void MCDwarfLineStr::emitSection (MCStreamer * MCOS)
Emit the .debug_line_str section if appropriate.
Definition at line 332 of file MCDwarf.cpp.
References llvm::Data, llvm::MCStreamer::emitBinaryData(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfLineStrSection(), getFinalizedData(), llvm::MCContext::getObjectFileInfo(), and llvm::MCStreamer::switchSection().
getFinalizedData()
SmallString< 0 > MCDwarfLineStr::getFinalizedData ()
Returns finalized section.
Definition at line 340 of file MCDwarf.cpp.
References llvm::Data, llvm::StringTableBuilder::finalizeInOrder(), llvm::StringTableBuilder::getSize(), llvm::StringTableBuilder::isFinalized(), and llvm::StringTableBuilder::write().
Referenced by emitSection().
getSaver()
StringSaver& llvm::MCDwarfLineStr::getSaver () inline
Definition at line 63 of file MCDwarf.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp