LLVM: llvm::ConstantInt Class Reference
llvm::ConstantInt Class Reference final
This is the shared class of boolean and integer constants.
#include "llvm/IR/Constants.h"
Public Member Functions
ConstantInt (const ConstantInt &)=delete
const APInt & getValue () const
Return the constant as an APInt value reference.
unsigned getBitWidth () const
getBitWidth - Return the bitwidth of this constant.
uint64_t getZExtValue () const
Return the constant as a 64-bit unsigned integer value after it has been zero extended as appropriate for the type of this constant.
int64_t getSExtValue () const
Return the constant as a 64-bit integer value after it has been sign extended as appropriate for the type of this constant.
MaybeAlign getMaybeAlignValue () const
Return the constant as an llvm::MaybeAlign.
Align getAlignValue () const
Return the constant as an llvm::Align, interpreting 0 as Align(1).
bool equalsInt (uint64_t V) const
A helper method that can be used to determine if the constant contained within is equal to a constant.
IntegerType * getType () const
getType - Specialize the getType() method to always return an IntegerType, which reduces the amount of casting needed in parts of the compiler.
bool isNegative () const
bool isZero () const
This is just a convenience method to make client code smaller for a common code.
bool isOne () const
This is just a convenience method to make client code smaller for a common case.
bool isMinusOne () const
This function will return true iff every bit in this constant is set to true.
bool isMaxValue (bool IsSigned) const
This function will return true iff this constant represents the largest value that may be represented by the constant's type.
bool isMinValue (bool IsSigned) const
This function will return true iff this constant represents the smallest value that may be represented by this constant's type.
bool uge (uint64_t Num) const
This function will return true iff this constant represents a value with active bits bigger than 64 bits or a value greater than the given uint64_t value.
uint64_t getLimitedValue (uint64_t Limit=~0ULL) const
getLimitedValue - If the value is smaller than the specified limit, return it, otherwise return the limit value.
Public Member Functions inherited from llvm::ConstantData
void operator delete (void *Ptr)
ConstantData (const ConstantData &)=delete
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a fixed width vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal, infinity, nan, or zero) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefOrPoisonElement () const
Return true if this is a vector constant that includes any undef or poison elements.
bool containsPoisonElement () const
Return true if this is a vector constant that includes any poison elements.
bool containsUndefElement () const
Return true if this is a vector constant that includes any strictly undef (not poison) elements.
bool containsConstantExpression () const
Return true if this is a fixed width vector constant that includes any constant expressions.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry (either static or dynamic).
bool needsDynamicRelocation () const
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
bool hasOneLiveUse () const
Return true if the constant has exactly one live use.
bool hasZeroLiveUses () const
Return true if the constant has no live uses.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
bool isManifestConstant () const
Return true if a constant is ConstantData or a ConstantAggregate or ConstantExpr that contain only ConstantData.
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static ConstantInt * getTrue (LLVMContext &Context)
static ConstantInt * getFalse (LLVMContext &Context)
static ConstantInt * getBool (LLVMContext &Context, bool V)
static Constant * getTrue (Type *Ty)
static Constant * getFalse (Type *Ty)
static Constant * getBool (Type *Ty, bool V)
static Constant * get (Type *Ty, uint64_t V, bool IsSigned=false)
If Ty is a vector type, return a Constant with a splat of the given value.
static ConstantInt * get (IntegerType *Ty, uint64_t V, bool IsSigned=false)
Return a ConstantInt with the specified integer value for the specified type.
static ConstantInt * getSigned (IntegerType *Ty, int64_t V)
Return a ConstantInt with the specified value for the specified type.
static Constant * getSigned (Type *Ty, int64_t V)
static ConstantInt * get (LLVMContext &Context, const APInt &V)
Return a ConstantInt with the specified value and an implied Type.
static ConstantInt * get (IntegerType *Ty, StringRef Str, uint8_t Radix)
Return a ConstantInt constructed from the string strStart with the given radix.
static Constant * get (Type *Ty, const APInt &V)
If Ty is a vector type, return a Constant with a splat of the given value.
static bool isValueValidForType (Type *Ty, uint64_t V)
This static method returns true if the type Ty is big enough to represent the value V.
static bool isValueValidForType (Type *Ty, int64_t V)
static bool classof (const Value *V)
Methods to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::ConstantData
static bool classof (const Value *V)
Methods to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
static Constant * mergeUndefsWith (Constant *C, Constant *Other)
Merges undefs of a Constant with another Constant, along with the undefs already present.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Friends
class Constant
Additional Inherited Members
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Member Functions inherited from llvm::ConstantData
ConstantData (Type *Ty, ValueTy VT)
void * operator new (size_t S)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
~Constant ()=default
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * >> &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This is the shared class of boolean and integer constants.
This class represents both boolean and integral constants. Class for constant integers.
Definition at line 78 of file Constants.h.
Constructor & Destructor Documentation
ConstantInt()
llvm::ConstantInt::ConstantInt (const ConstantInt &) delete
Member Function Documentation
classof()
static bool llvm::ConstantInt::classof (const Value * V) inline static
Methods to support type inquiry through isa, cast, and dyn_cast.
Definition at line 248 of file Constants.h.
References llvm::Value::getValueID().
equalsInt()
bool llvm::ConstantInt::equalsInt (uint64_t V) const inline
A helper method that can be used to determine if the constant contained within is equal to a constant.
This only works for very small values, because this is all that can be represented with all types. Determine if this constant's value is same as an unsigned char.
Definition at line 167 of file Constants.h.
Referenced by llvm::InstructionSelector::executeMatchTable(), and llvm::AAMDNodes::extendToTBAA().
get() [1/5]
ConstantInt * ConstantInt::get (IntegerType * Ty, StringRef Str, uint8_t Radix) static
Return a ConstantInt constructed from the string strStart with the given radix.
Definition at line 921 of file Constants.cpp.
References get(), llvm::IntegerType::getBitWidth(), and llvm::Type::getContext().
get() [2/5]
ConstantInt * ConstantInt::get (IntegerType * Ty, uint64_t V, bool IsSigned = false) static
Return a ConstantInt with the specified integer value for the specified type.
If the type is wider than 64 bits, the value will be zero-extended to fit the type, unless IsSigned is true, in which case the value will be interpreted as a 64-bit signed integer and sign-extended to fit the type. Get a ConstantInt for a specific value.
Definition at line 897 of file Constants.cpp.
References get(), llvm::IntegerType::getBitWidth(), llvm::Type::getContext(), and isSigned().
get() [3/5]
ConstantInt * ConstantInt::get (LLVMContext & Context, const APInt & V) static
Return a ConstantInt with the specified value and an implied Type.
The type is the integer type that corresponds to the bit width of the value.
Definition at line 874 of file Constants.cpp.
References assert(), Context, llvm::IntegerType::get(), llvm::APInt::getBitWidth(), llvm::LLVMContextImpl::IntConstants, and llvm::LLVMContext::pImpl.
get() [4/5]
Constant * ConstantInt::get (Type * Ty, const APInt & V) static
If Ty is a vector type, return a Constant with a splat of the given value.
Otherwise return a ConstantInt for the given value.
Definition at line 909 of file Constants.cpp.
References assert(), get(), llvm::Type::getContext(), llvm::Type::getScalarType(), and llvm::ConstantVector::getSplat().
get() [5/5]
Constant * ConstantInt::get (Type * Ty, uint64_t V, bool IsSigned = false) static
If Ty is a vector type, return a Constant with a splat of the given value.
Otherwise return a ConstantInt for the given value.
Definition at line 887 of file Constants.cpp.
References llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), and isSigned().
Referenced by addCanonicalIVRecipes(), llvm::addDiffRuntimeChecks(), llvm::Module::addModuleFlag(), addModuleFlags(), llvm::InstCombiner::AddOne(), llvm::GlobalObject::addTypeMetadata(), llvm::annotateValueSite(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), BitCastConstantVector(), bitTrackingDCE(), llvm::buildAtomicRMWValue(), llvm::memprof::buildCallstackMetadata(), llvm::MachineIRBuilder::buildConstant(), llvm::SPIRVGlobalRegistry::buildConstantInt(), calcPredicateUsingInteger(), canonicalizeForInvariantConditionInjection(), canonicalizeLogicFirst(), canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), CloneLoopBlocks(), llvm::VNCoercion::coerceAvailableValueToLoadType(), collectInsertionElements(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::ObjectSizeOffsetEvaluator::compute(), computePointerDifference(), computePointerICmp(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), ConnectProlog(), llvm::DIExpression::constantFold(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCastOperand(), constantFoldCmp(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ConstantFoldUnaryInstruction(), ConvertShiftToMul(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), convertStrToInt(), convertToRelLookupTable(), llvm::GlobalObject::copyMetadata(), llvm::copyNonnullMetadata(), llvm::SanitizerStatReport::create(), createAccessTag(), llvm::IRBuilderBase::CreateAlignmentAssumption(), llvm::IRBuilderBase::CreateAnd(), createAndInstr(), llvm::IRBuilderBase::CreateAShr(), llvm::DIBuilder::createBitFieldMemberType(), llvm::MDBuilder::createBranchWeights(), llvm::MDBuilder::createCallbackEncoding(), llvm::ARMTargetLowering::createComplexDeinterleavingIR(), llvm::IRBuilderBase::CreateConstGEP1_32(), llvm::IRBuilderBase::CreateConstGEP1_64(), llvm::IRBuilderBase::CreateConstGEP2_32(), llvm::IRBuilderBase::CreateConstGEP2_64(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_64(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_64(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), createFoldedExitCond(), llvm::MDBuilder::createFunctionEntryCount(), llvm::OpenMPIRBuilder::createGlobalFlag(), llvm::IRBuilderBase::CreateGlobalStringPtr(), llvm::DIBuilder::createInheritance(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::orc::createIRTypedAddress(), llvm::MDBuilder::createLLVMStats(), llvm::OpenMPIRBuilder::createLoopSkeleton(), llvm::IRBuilderBase::CreateLShr(), createMalloc(), createMaskedBitTest(), createMaskInstrs(), llvm::MatrixBuilder::CreateMatrixInsert(), llvm::createMemCpyLoopKnownSize(), createMemMoveLoop(), createMemSetLoop(), llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), llvm::OpenMPIRBuilder::createOffloadEntry(), llvm::OpenMPIRBuilder::createOMPInteropDestroy(), llvm::OpenMPIRBuilder::createOMPInteropInit(), llvm::OpenMPIRBuilder::createOMPInteropUse(), llvm::IRBuilderBase::CreateOr(), llvm::OpenMPIRBuilder::createParallel(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::IRBuilderBase::CreatePreserveStructAccessIndex(), llvm::MDBuilder::createPseudoProbeDesc(), llvm::MDBuilder::createRange(), llvm::OpenMPIRBuilder::createSections(), llvm::IRBuilderBase::CreateShl(), llvm::createStepForVF(), llvm::IRBuilderBase::CreateStepVector(), createStringMetadata(), createSwitchStatement(), llvm::OpenMPIRBuilder::createTargetInit(), llvm::OpenMPIRBuilder::createTask(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), CreateTripRemainder(), llvm::IRBuilderBase::CreateXor(), decompose(), decomposeBitTestICmp(), decomposeGEP(), decomposeSimpleLinearExpr(), llvm::InstCombinerImpl::Descale(), detectShiftUntilBitTestIdiom(), DisableAllLoopOptsOnLoop(), dropRedundantMaskingOfLeftShiftInput(), llvm::orc::IRSpeculationLayer::emit(), llvm::emitFWrite(), llvm::emitGEPOffset(), llvm::InnerLoopVectorizer::emitIterationCountCheck(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::PPCTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::PPCTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::OpenMPIRBuilder::emitOffloadingEntry(), llvm::emitStrChr(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), evaluateInDifferentElementOrder(), llvm::VPWidenPointerInductionRecipe::execute(), llvm::VPFirstOrderRecurrencePHIRecipe::execute(), llvm::VPWidenMemoryInstructionRecipe::execute(), llvm::AAMDNodes::extendToTBAA(), ExtractConstantBytes(), FactorOutConstant(), llvm::FastISel::fastEmit_ri_(), findElementAtOffset(), llvm::SanitizerStatReport::finish(), llvm::InnerLoopVectorizer::fixFixedOrderRecurrence(), llvm::InnerLoopVectorizer::fixupIVUsers(), foldAddToAshr(), llvm::InstCombinerImpl::foldAddWithConstant(), llvm::InstCombinerImpl::foldAllocaCmp(), foldAnyOrAllBitsSet(), FoldBitCast(), foldClampRangeOfTwo(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), foldCtpop(), foldCttzCtlz(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAddOpConst(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpAndShift(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpEqIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpOrConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpShlConstConst(), foldICmpShlOne(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpShrConstConst(), llvm::InstCombinerImpl::foldICmpSRemConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUDivConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpXorConstant(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), foldIDivShl(), foldInsSequenceIntoSplat(), foldIsPowerOf2(), foldIsPowerOf2OrZero(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldNoWrapAdd(), llvm::InstCombinerImpl::foldSelectICmp(), foldSelectICmpAnd(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), foldSetClearBits(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftedShift(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldToUnsignedSaturatedAdd(), for(), generateCreationChecks(), generateCreationChecksForBinOp(), llvm::SCEVExpander::generateOverflowCheck(), generateUnsignedDivisionCode(), GEPToVectorIndex(), get(), getAISize(), llvm::ConstantExpr::getAlignOf(), llvm::Constant::getAllOnesValue(), getAlternateBinop(), getAnyNonZeroConstInt(), llvm::AAValueConstantRange::getAssumedConstant(), llvm::AAPotentialConstantValues::getAssumedConstant(), getAvailableLoadStore(), llvm::ConstantExpr::getBinOpIdentity(), getBinOpsForFactorization(), getBoundsCheckCond(), llvm::LazyValueInfo::getConstant(), llvm::ScalarEvolution::getConstant(), llvm::SelectionDAG::getConstant(), llvm::SCCPInstVisitor::getConstant(), GetConstantInt(), llvm::VNCoercion::getConstantMemInstValueForLoad(), llvm::LazyValueInfo::getConstantOnEdge(), getEdgeValueLocal(), llvm::ConstantDataSequential::getElementAsConstant(), llvm::ConstantExpr::getExactLogBase2(), getFalse(), llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(), llvm::coro::Shape::getIndex(), llvm::IRBuilderBase::getInt(), llvm::IRBuilderBase::getInt1(), llvm::IRBuilderBase::getInt16(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt64(), llvm::IRBuilderBase::getInt8(), llvm::Constant::getIntegerValue(), llvm::IRBuilderBase::getIntN(), getKeyValMD(), llvm::VNCoercion::getMemInstValueForLoad(), llvm::ScalarEvolution::getMinMaxExpr(), getNotValue(), llvm::Constant::getNullValue(), getOffsetFromIndices(), llvm::ConstantExpr::getOffsetOf(), llvm::SPIRVGlobalRegistry::getOrCreateConsIntArray(), llvm::SPIRVGlobalRegistry::getOrCreateConsIntVector(), llvm::OpenMPIRBuilder::getOrCreateIdent(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::getPredForFCmpCode(), llvm::getPredForICmpCode(), getPreferredVectorIndex(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), llvm::getRuntimeVF(), getSafeDivisor(), llvm::InstCombiner::getSafeVectorConstantForBinop(), getShiftedValue(), getSigned(), llvm::ConstantExpr::getSizeOf(), llvm::ScalarEvolution::getSizeOfScalableVectorExpr(), llvm::ConstantVector::getSplat(), llvm::InstrProfIncrementInst::getStep(), llvm::VNCoercion::getStoreValueForLoadHelper(), getTrue(), INITIALIZE_PASS(), llvm::InlineFunction(), insertCall(), llvm::BPFCoreSharedInfo::insertPassThrough(), llvm::InstCombinerImpl::insertRangeTest(), insertSinCosCall(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::GCNTTIImpl::instCombineIntrinsic(), instCombineRDFFR(), instCombineSVECmpNE(), instCombineSVECntElts(), instCombineSVEDup(), instCombineSVEDupqLane(), instCombineSVELast(), instCombineSVESDIV(), instrumentMaskedLoadOrStore(), instrumentOneFunc(), llvm::isBytewiseValue(), isDivZero(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::ARMLegalizerInfo::legalizeCustom(), LLVMConstInt(), LLVMConstIntOfArbitraryPrecision(), LLVMConstIntOfString(), LLVMConstIntOfStringAndSize(), llvm::XCoreInstrInfo::loadImmediate(), LowerBSWAP(), llvm::AMDGPUAsmPrinter::lowerConstant(), LowerCTLZ(), LowerCTPOP(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::lowerObjectSizeCall(), llvm::fuzzerop::makeConstantsWithType(), llvm::coro::LowererBase::makeSubFnCall(), MatchBinaryOp(), matchFunnelShift(), matchStridedConstant(), matchStridedStart(), matchUAddWithOverflowConstantEdgeCases(), memChrToCharCompare(), llvm::MergeBasicBlockIntoOnlyPred(), moveAddAfterMinMax(), llvm::InsertCFGStrategy::mutate(), optimizeMemCmpVarSize(), llvm::VPlan::prepareToExecute(), processAbsIntrinsic(), llvm::InstCombinerImpl::PromoteCastOfAllocation(), llvm::recognizeBSwapOrBitReverseIdiom(), replaceCalledFunction(), replaceFrameSizeAndAlignment(), replaceGEPIdxWithZero(), llvm::replaceRelativePointerUsersWithZero(), llvm::KCFIPass::run(), SegmentOffset(), llvm::LoopVectorizeHints::setAlreadyVectorized(), setAssignmentTrackingModuleFlag(), llvm::setKCFIType(), llvm::GlobalObject::setVCallVisibilityMetadata(), llvm::AAMDNodes::shiftTBAAStruct(), ShrinkDemandedConstant(), llvm::InstCombinerImpl::SimplifyAddWithRemainder(), simplifyAMDGCNMemoryIntrinsicDemanded(), llvm::InstCombinerImpl::SimplifyAnyMemSet(), simplifyBinaryIntrinsic(), SimplifyBSwap(), simplifyByDomEq(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyDivRem(), simplifyFCmpInst(), simplifyGEPInst(), simplifyICmpInst(), simplifyICmpWithConstant(), simplifyICmpWithDominatingAssume(), simplifyIntrinsic(), simplifyOneLoop(), simplifyRelativeLoad(), llvm::InstCombinerImpl::simplifyShrShlDemandedBits(), simplifyUnaryIntrinsic(), simplifyX86extrq(), simplifyX86immShift(), simplifyX86varShift(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), splitGlobal(), llvm::InstCombiner::SubOne(), llvm::OpenMPIRBuilder::tileLoops(), tryMergeRange(), tryToMergePartialOverlappingStores(), tryToRecognizeTableBasedCttz(), tryToShorten(), TryToShrinkGlobalToBoolean(), tryToSimplifyOverflowMath(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::OpenMPIRBuilder::unrollLoopPartial(), llvm::UnrollRuntimeLoopRemainder(), updateAsyncFuncPointerContextSize(), llvm::CallInst::updateProfWeight(), validExtractValueIndex(), validInsertValueIndex(), verifyTripCount(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombinerImpl::visitAllocSite(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitAtomicRMWInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitGEPOfGEP(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitURem(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), llvm::LegalizerHelper::widenScalar(), and llvm::BasicBlock::~BasicBlock().
getAlignValue()
Align llvm::ConstantInt::getAlignValue () const inline
Return the constant as an llvm::Align, interpreting 0 as Align(1).
Note that this method can assert if the value does not fit in 64 bits or is not a power of two.
Definition at line 159 of file Constants.h.
References getMaybeAlignValue(), and llvm::MaybeAlign::valueOrOne().
getBitWidth()
unsigned llvm::ConstantInt::getBitWidth () const inline
getBitWidth - Return the bitwidth of this constant.
Definition at line 135 of file Constants.h.
References llvm::APInt::getBitWidth().
Referenced by llvm::MachineIRBuilder::buildConstant(), emitGlobalConstantLargeInt(), llvm::InstCombinerImpl::foldICmpEquality(), foldSwitchToSelect(), llvm::SelectionDAG::getConstant(), handleBrSelExpect(), processUGT_ADDCST_ADD(), and processUMulZExtIdiom().
getBool() [1/2]
ConstantInt * ConstantInt::getBool (LLVMContext & Context, bool V) static
Definition at line 849 of file Constants.cpp.
References Context, getFalse(), and getTrue().
Referenced by llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::OpenMPIRBuilder::createTargetInit(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), OptimizeGlobalAddressOfAllocation(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitMul().
getBool() [2/2]
Constant * ConstantInt::getBool (Type * Ty, bool V) static
Definition at line 869 of file Constants.cpp.
References getFalse(), and getTrue().
getFalse() [1/2]
ConstantInt * ConstantInt::getFalse (LLVMContext & Context) static
Definition at line 842 of file Constants.cpp.
References Context, get(), llvm::Type::getInt1Ty(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::TheFalseVal.
Referenced by llvm::OpenMPIRBuilder::applySimd(), calcPredicateUsingBooleans(), checkAndReplaceCondition(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), constantFoldCompareGlobalToNull(), llvm::VPRecipeBuilder::createEdgeMask(), llvm::SCEVExpander::expandUnionPredicate(), llvm::SCEVExpander::expandWrapPredicate(), llvm::InstCombinerImpl::foldICmpAndShift(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::SCEVExpander::generateOverflowCheck(), getBool(), getBoundsCheckCond(), llvm::ValueLatticeElement::getCompare(), getConstantAt(), llvm::PredicateBase::getConstraint(), getFalse(), getFalse(), llvm::IRBuilderBase::getFalse(), getPoisonFor(), llvm::hasPartialIVCondition(), llvm::GCNTTIImpl::instCombineIntrinsic(), lowerIsConstantIntrinsic(), OptimizeGlobalAddressOfAllocation(), llvm::JumpThreadingPass::processBlock(), llvm::JumpThreadingPass::processBranchOnXOR(), processOverflowIntrinsic(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), simplifyAndInst(), llvm::InstCombinerImpl::simplifyDivRemOfSelectWithZeroOp(), simplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), simplifySelectInst(), simplifyUnsignedRangeCheck(), simplifyUsingControlFlow(), llvm::splitLoopBound(), TryToShrinkGlobalToBoolean(), turnGuardIntoBranch(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), llvm::InstCombinerImpl::visitBranchInst(), llvm::InstCombinerImpl::visitFCmpInst(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getFalse() [2/2]
Constant * ConstantInt::getFalse (Type * Ty) static
Definition at line 861 of file Constants.cpp.
References assert(), llvm::Type::getContext(), getFalse(), llvm::ConstantVector::getSplat(), and llvm::Type::isIntOrIntVectorTy().
getLimitedValue()
uint64_t llvm::ConstantInt::getLimitedValue (uint64_t Limit = ~0ULL) const inline
getLimitedValue - If the value is smaller than the specified limit, return it, otherwise return the limit value.
This causes the value to saturate to the limit.
Returns
the min of the value of the constant and the specified value Get the constant's value with a saturation limit
Definition at line 243 of file Constants.h.
References llvm::APInt::getLimitedValue().
Referenced by canEvaluateShuffled(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::Value::getPointerAlignment(), llvm::Value::getPointerDereferenceableBytes(), getSortedConstantKeys(), llvm::AsmPrinter::preprocessXXStructorList(), ShouldUseSwitchConditionAsTableIndex(), llvm::InstCombinerImpl::SimplifyAnyMemSet(), llvm::InstCombinerImpl::SimplifyAnyMemTransfer(), and SwitchToLookupTable().
getMaybeAlignValue()
MaybeAlign llvm::ConstantInt::getMaybeAlignValue () const inline
Return the constant as an llvm::MaybeAlign.
Note that this method can assert if the value does not fit in 64 bits or is not a power of two.
Definition at line 152 of file Constants.h.
References getZExtValue().
Referenced by getAlignValue().
getSExtValue()
int64_t llvm::ConstantInt::getSExtValue () const inline
Return the constant as a 64-bit integer value after it has been sign extended as appropriate for the type of this constant.
Note that this method can assert if the value does not fit in 64 bits. Return the sign extended value.
Definition at line 147 of file Constants.h.
References llvm::APInt::getSExtValue().
Referenced by canFoldIVIncExpr(), checkOffsetSize(), decompose(), getOffsetFromIndex(), llvm::getOptionalIntLoopAttribute(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::IndexedReference::hasSpacialReuse(), llvm::IndexedReference::hasTemporalReuse(), INITIALIZE_PASS(), isIndexInRangeOfArrayType(), llvm::InductionDescriptor::isInductionPHI(), llvm::MDNodeKeyImpl< DISubrange >::isKeyOf(), isKnownNonNull(), isLoadInvariantInLoop(), and X86ChooseCmpImmediateOpcode().
getSigned() [1/2]
ConstantInt * ConstantInt::getSigned (IntegerType * Ty, int64_t V) static
Return a ConstantInt with the specified value for the specified type.
The value V will be canonicalized to a an unsigned APInt. Accessing it with either getSExtValue() or getZExtValue() will yield a correctly sized and signed value for the type Ty. Get a ConstantInt for a specific signed value.
Definition at line 901 of file Constants.cpp.
References get().
Referenced by llvm::OpenMPIRBuilder::createTargetDeinit(), llvm::OpenMPIRBuilder::createTargetInit(), expandFPToI(), generateUnsignedDivisionCode(), llvm::DIBuilder::getOrCreateSubrange(), getSignedIntOrFpConstant(), insertLifetimeMarkersSurroundingCall(), and llvm::InstCombinerImpl::visitLShr().
getSigned() [2/2]
Constant * ConstantInt::getSigned (Type * Ty, int64_t V) static
Definition at line 905 of file Constants.cpp.
References get().
getTrue() [1/2]
ConstantInt * ConstantInt::getTrue (LLVMContext & Context) static
Definition at line 835 of file Constants.cpp.
References Context, get(), llvm::Type::getInt1Ty(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::TheTrueVal.
Referenced by llvm::OpenMPIRBuilder::applySimd(), calcPredicateUsingBooleans(), checkAndReplaceCondition(), computeKnownBitsFromOperator(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), constantFoldCompareGlobalToNull(), llvm::sampleprofutil::createFSDiscriminatorVariable(), llvm::InstCombinerImpl::CreateNonTerminatorUnreachable(), llvm::Value::dropDroppableUse(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), llvm::InstCombinerImpl::foldICmpAndShift(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), getBool(), llvm::ValueLatticeElement::getCompare(), getConstantAt(), llvm::PredicateBase::getConstraint(), getTrue(), getTrue(), llvm::IRBuilderBase::getTrue(), llvm::hasPartialIVCondition(), lowerIsConstantIntrinsic(), lowerWidenableCondition(), llvm::VPlanTransforms::optimizeForVFAndUF(), OptimizeGlobalAddressOfAllocation(), llvm::parseWidenableBranch(), processAbsIntrinsic(), llvm::JumpThreadingPass::processBlock(), llvm::JumpThreadingPass::processBranchOnXOR(), processUse(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::InstCombinerImpl::simplifyDivRemOfSelectWithZeroOp(), simplifyICmpInst(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), simplifyOrInst(), simplifySelectInst(), simplifyUnsignedRangeCheck(), simplifyUsingControlFlow(), llvm::splitLoopBound(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), llvm::updatePublicTypeTestCalls(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFreeze(), and llvm::SelectionDAGBuilder::visitSwitchCase().
getTrue() [2/2]
Constant * ConstantInt::getTrue (Type * Ty) static
Definition at line 853 of file Constants.cpp.
References assert(), llvm::Type::getContext(), llvm::ConstantVector::getSplat(), getTrue(), and llvm::Type::isIntOrIntVectorTy().
getType()
IntegerType* llvm::ConstantInt::getType () const inline
getType - Specialize the getType() method to always return an IntegerType, which reduces the amount of casting needed in parts of the compiler.
Definition at line 172 of file Constants.h.
References llvm::Value::getType().
Referenced by llvm::createMemCpyLoopKnownSize(), emitGlobalConstantLargeInt(), llvm::AAMDNodes::extendToTBAA(), llvm::InstCombinerImpl::foldICmpEquality(), generateAssignInstrs(), getAvailableLoadStore(), GetConstantInt(), getPreferredVectorIndex(), llvm::SCEVConstant::getType(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::InductionDescriptor::isInductionPHI(), llvm::AAMDNodes::shiftTBAAStruct(), llvm::RISCVTargetLowering::signExtendConstant(), simplifyAMDGCNMemoryIntrinsicDemanded(), llvm::InstCombinerImpl::SimplifyAnyMemSet(), llvm::InstCombinerImpl::SimplifyAnyMemTransfer(), SwitchToLookupTable(), tryUnmergingGEPsAcrossIndirectBr(), updatePredecessorProfileMetadata(), and verifyTripCount().
getValue()
const APInt& llvm::ConstantInt::getValue () const inline
Return the constant as an APInt value reference.
This allows clients to obtain a full-precision copy of the value. Return the constant's value.
Definition at line 132 of file Constants.h.
Referenced by llvm::DwarfUnit::addConstantValue(), canScalarizeAccess(), canUseSExt(), cheapToScalarize(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::DIExpression::constantFold(), llvm::BitTracker::MachineEvaluator::eIMM(), emitGlobalConstantLargeInt(), ExtractConstantBytes(), findDemandedEltsBySingleUser(), llvm::InstCombinerImpl::foldICmpEquality(), foldSwitchToSelect(), llvm::generateSpecConstantInst(), llvm::SCEVConstant::getAPInt(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), getBoundsCheckCond(), GetBranchWeights(), llvm::SelectionDAG::getConstant(), getConstantTripCount(), llvm::getConstFromIntrinsic(), llvm::Function::getEntryCount(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::ScalarEvolution::getGEPExpr(), llvm::MDNode::getMostGenericRange(), getPredicateResult(), getPreferredVectorIndex(), handlePhiDef(), llvm::hasProcessableCondition(), instCombineSVESDIV(), isIndexInRangeOfArrayType(), llvm::isKnownToBeAPowerOfTwo(), isNonZeroModBitWidthOrUndef(), isObjectSizeLessThanOrEq(), isOperandOfVmullHighP64(), isSSATMinMaxPattern(), llvm::CombinerHelper::matchCombineUnmergeConstant(), matchStridedConstant(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), rotateSign(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyDiv(), simplifyX86extrq(), SolveQuadraticAddRecRange(), llvm::SwitchCG::sortAndRangeify(), llvm::stableHashValue(), SwitchToLookupTable(), tryUnmergingGEPsAcrossIndirectBr(), verifyTripCount(), llvm::InstCombinerImpl::visitXor(), and llvm::LegalizerHelper::widenScalar().
getZExtValue()
uint64_t llvm::ConstantInt::getZExtValue () const inline
Return the constant as a 64-bit unsigned integer value after it has been zero extended as appropriate for the type of this constant.
Note that this method can assert if the value does not fit in 64 bits. Return the zero extended value.
Definition at line 141 of file Constants.h.
References llvm::APInt::getZExtValue().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), llvm::cacheAnnotationFromMD(), CheckAndCreateOffsetAdd(), collectInsertionElements(), llvm::ConstantFoldInsertElementInstruction(), llvm::createMemCpyLoopKnownSize(), findDemandedEltsBySingleUser(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), FoldCondBranchOnValueKnownInPredecessorImpl(), foldConstantsIntoIntrinsics(), foldImm(), foldVecTruncToExtElt(), getConstantTripCount(), llvm::DOTGraphTraits< DOTFuncInfo * >::getEdgeAttributes(), llvm::AtomicMemIntrinsic::getElementSizeInBytes(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), getImmedFromMO(), llvm::AMDGPUMachineFunction::getLDSKernelIdMetadata(), llvm::GEPOperator::getMaxPreservedAlignment(), getMaybeAlignValue(), llvm::MDNode::getMostGenericAlignmentOrDereferenceable(), getOffsetFromIndex(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::getValueProfDataFromInst(), getVarName(), handleBrSelExpect(), llvm::GCNTTIImpl::instCombineIntrinsic(), isGEPKnownNonNull(), mayLoopAccessLocation(), llvm::FunctionLoweringInfo::set(), llvm::AAMDNodes::shiftTBAAStruct(), llvm::AArch64TargetLowering::shouldSinkOperands(), simplifyAMDGCNMemoryIntrinsicDemanded(), llvm::InstCombinerImpl::SimplifyAnyMemSet(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyShuffleVectorInst(), tryPromoteAllocaToVector(), and llvm::InstCombinerImpl::visitTrunc().
isMaxValue()
bool llvm::ConstantInt::isMaxValue (bool IsSigned) const inline
This function will return true iff this constant represents the largest value that may be represented by the constant's type.
Returns
true iff this is the largest value that may be represented by this type. Determine if the value is maximal.
Definition at line 212 of file Constants.h.
References llvm::APInt::isMaxSignedValue(), and llvm::APInt::isMaxValue().
isMinusOne()
bool llvm::ConstantInt::isMinusOne () const inline
This function will return true iff every bit in this constant is set to true.
Returns
true iff this constant's bits are all set to true. Determine if the value is all ones.
Definition at line 205 of file Constants.h.
References llvm::APInt::isAllOnes().
Referenced by detectPopcountIdiom(), detectShiftUntilZeroIdiom(), getBranchCondString(), and llvm::InstCombinerImpl::simplifyRangeCheck().
isMinValue()
bool llvm::ConstantInt::isMinValue (bool IsSigned) const inline
This function will return true iff this constant represents the smallest value that may be represented by this constant's type.
Returns
true if this is the smallest value that may be represented by this type. Determine if the value is minimal.
Definition at line 224 of file Constants.h.
References llvm::APInt::isMinSignedValue(), and llvm::APInt::isMinValue().
isNegative()
bool llvm::ConstantInt::isNegative () const inline
Definition at line 188 of file Constants.h.
References llvm::APInt::isNegative().
Referenced by decompose(), llvm::hasProcessableCondition(), isLoadInvariantInLoop(), and ShouldUseSwitchConditionAsTableIndex().
isOne()
bool llvm::ConstantInt::isOne () const inline
This is just a convenience method to make client code smaller for a common case.
It also correctly performs the comparison without the potential for an assertion from getZExtValue(). Determine if the value is one.
Definition at line 199 of file Constants.h.
References llvm::APInt::isOne().
Referenced by buildMul(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), getBranchCondString(), llvm::Loop::isCanonical(), llvm::VPCanonicalIVPHIRecipe::isCanonical(), IsConstantOne(), processSelect(), and updatePredecessorProfileMetadata().
isValueValidForType() [1/2]
bool ConstantInt::isValueValidForType (Type * Ty, int64_t V) static
Definition at line 1527 of file Constants.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::isIntegerTy(), and llvm::isIntN().
isValueValidForType() [2/2]
bool ConstantInt::isValueValidForType (Type * Ty, uint64_t V) static
This static method returns true if the type Ty is big enough to represent the value V.
This can be used to avoid having the get method assert when V is larger than Ty can represent. Note that there are two versions of this method, one for unsigned and one for signed integers. Although ConstantInt canonicalizes everything to an unsigned integer, the signed version avoids callers having to convert a signed quantity to the appropriate unsigned type before calling the method.
Returns
true if V is a valid value for type Ty Determine if the value is in range for the given type.
Definition at line 1520 of file Constants.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::isIntegerTy(), and llvm::isUIntN().
Referenced by llvm::X86TargetLowering::LowerAsmOperandForConstraint().
isZero()
bool llvm::ConstantInt::isZero () const inline
This is just a convenience method to make client code smaller for a common code.
It also correctly performs the comparison without the potential for an assertion from getZExtValue().
Definition at line 193 of file Constants.h.
References llvm::APInt::isZero().
Referenced by llvm::createMemCpyLoopKnownSize(), FactorOutConstant(), llvm::InstCombinerImpl::foldSelectICmp(), getBranchCondString(), getOffsetFromIndex(), llvm::SITargetLowering::getTgtMemIntrinsic(), hasOnlyOneNonZeroIndex(), llvm::hasProcessableCondition(), llvm::IndexedReference::hasTemporalReuse(), llvm::isGEPBasedOnPointerToString(), llvm::MemIntrinsic::isVolatile(), matchCondition(), llvm::JumpThreadingPass::processBranchOnXOR(), llvm::InstCombinerImpl::simplifyRangeCheck(), and SolveQuadraticAddRecExact().
uge()
bool llvm::ConstantInt::uge (uint64_t Num) const inline
This function will return true iff this constant represents a value with active bits bigger than 64 bits or a value greater than the given uint64_t value.
Returns
true iff this constant is greater or equal to the given number. Determine if the value is greater or equal to the given number.
Definition at line 236 of file Constants.h.
References llvm::APInt::uge().
Referenced by llvm::ConstantFoldInsertElementInstruction().
Friends And Related Function Documentation
Constant
friend class Constant friend
Definition at line 79 of file Constants.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Constants.h
lib/IR/Constants.cpp