LLVM: llvm::orc::SimpleRemoteEPC Class Reference
llvm::orc::SimpleRemoteEPC Class Reference
#include "llvm/ExecutionEngine/Orc/SimpleRemoteEPC.h"
Classes
struct Setup
A setup object containing callbacks to construct a memory manager and memory access object.
Public Member Functions
SimpleRemoteEPC (const SimpleRemoteEPC &)=delete
SimpleRemoteEPC & operator= (const SimpleRemoteEPC &)=delete
SimpleRemoteEPC (SimpleRemoteEPC &&)=delete
SimpleRemoteEPC & operator= (SimpleRemoteEPC &&)=delete
~SimpleRemoteEPC ()
Expected< tpctypes::DylibHandle > loadDylib (const char *DylibPath) override
Load the dynamic library at the given path and return a handle to it.
Expected< std::vector< tpctypes::LookupResult > > lookupSymbols (ArrayRef< LookupRequest > Request) override
Search for symbols in the target process.
Expected< int32_t > runAsMain (ExecutorAddr MainFnAddr, ArrayRef< std::string > Args) override
Run function with a main-like signature.
Expected< int32_t > runAsVoidFunction (ExecutorAddr VoidFnAddr) override
Run function with a int (*)(void) signature.
Expected< int32_t > runAsIntFunction (ExecutorAddr IntFnAddr, int Arg) override
Run function with a int (*)(int) signature.
void callWrapperAsync (ExecutorAddr WrapperFnAddr, IncomingWFRHandler OnComplete, ArrayRef< char > ArgBuffer) override
Run a wrapper function in the executor.
Error disconnect () override
Disconnect from the target process.
Expected< HandleMessageAction > handleMessage (SimpleRemoteEPCOpcode OpC, uint64_t SeqNo, ExecutorAddr TagAddr, SimpleRemoteEPCArgBytesVector ArgBytes) override
Handle receipt of a message.
void handleDisconnect (Error Err) override
Handle a disconnection from the underlying transport.
Public Member Functions inherited from llvm::orc::ExecutorProcessControl
ExecutorProcessControl (std::shared_ptr< SymbolStringPool > SSP, std::unique_ptr< TaskDispatcher > D)
virtual ~ExecutorProcessControl ()
ExecutionSession & getExecutionSession ()
Return the ExecutionSession associated with this instance.
SymbolStringPtr intern (StringRef SymName)
Intern a symbol name in the SymbolStringPool.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Return a shared pointer to the SymbolStringPool for this instance.
TaskDispatcher & getDispatcher ()
const Triple & getTargetTriple () const
Return the Triple for the target process.
unsigned getPageSize () const
Get the page size for the target process.
const JITDispatchInfo & getJITDispatchInfo () const
Get the JIT dispatch function and context address for the executor.
MemoryAccess & getMemoryAccess () const
Return a MemoryAccess object for the target process.
jitlink::JITLinkMemoryManager & getMemMgr () const
Return a JITLinkMemoryManager for the target process.
const StringMap< ExecutorAddr > & getBootstrapSymbolsMap () const
Returns the bootstrap symbol map.
Error getBootstrapSymbols (ArrayRef< std::pair< ExecutorAddr &, StringRef >> Pairs) const
For each (ExecutorAddr&, StringRef) pair, looks up the string in the bootstrap symbols map and writes its address to the ExecutorAddr if found.
template<typename RunPolicyT , typename FnT >
void callWrapperAsync (RunPolicyT &&Runner, ExecutorAddr WrapperFnAddr, FnT &&OnComplete, ArrayRef< char > ArgBuffer)
Run a wrapper function in the executor using the given Runner to dispatch OnComplete when the result is ready.
template<typename FnT >
void callWrapperAsync (ExecutorAddr WrapperFnAddr, FnT &&OnComplete, ArrayRef< char > ArgBuffer)
Run a wrapper function in the executor.
shared::WrapperFunctionResult callWrapper (ExecutorAddr WrapperFnAddr, ArrayRef< char > ArgBuffer)
Run a wrapper function in the executor.
template<typename SPSSignature , typename RunPolicyT , typename SendResultT , typename... ArgTs>
void callSPSWrapperAsync (RunPolicyT &&Runner, ExecutorAddr WrapperFnAddr, SendResultT &&SendResult, const ArgTs &...Args)
Run a wrapper function using SPS to serialize the arguments and deserialize the results.
template<typename SPSSignature , typename SendResultT , typename... ArgTs>
void callSPSWrapperAsync (ExecutorAddr WrapperFnAddr, SendResultT &&SendResult, const ArgTs &...Args)
Run a wrapper function using SPS to serialize the arguments and deserialize the results.
template<typename SPSSignature , typename... WrapperCallArgTs>
Error callSPSWrapper (ExecutorAddr WrapperFnAddr, WrapperCallArgTs &&...WrapperCallArgs)
Run a wrapper function using SPS to serialize the arguments and deserialize the results.
Public Member Functions inherited from llvm::orc::SimpleRemoteEPCTransportClient
virtual ~SimpleRemoteEPCTransportClient ()
Static Public Member Functions
template<typename TransportT , typename... TransportTCtorArgTs>
static Expected< std::unique_ptr< SimpleRemoteEPC > > Create (std::unique_ptr< TaskDispatcher > D, Setup S, TransportTCtorArgTs &&...TransportTCtorArgs)
Create a SimpleRemoteEPC using the given transport type and args.
Additional Inherited Members
Public Types inherited from llvm::orc::SimpleRemoteEPCTransportClient
enum HandleMessageAction { ContinueSession, EndSession }
Protected Attributes inherited from llvm::orc::ExecutorProcessControl
std::shared_ptr< SymbolStringPool > SSP
std::unique_ptr< TaskDispatcher > D
ExecutionSession * ES = nullptr
Triple TargetTriple
unsigned PageSize = 0
JITDispatchInfo JDI
MemoryAccess * MemAccess = nullptr
jitlink::JITLinkMemoryManager * MemMgr = nullptr
StringMap< ExecutorAddr > BootstrapSymbols
Detailed Description
Definition at line 31 of file SimpleRemoteEPC.h.
Constructor & Destructor Documentation
SimpleRemoteEPC() [1/2]
llvm::orc::SimpleRemoteEPC::SimpleRemoteEPC (const SimpleRemoteEPC &) delete
Referenced by Create().
SimpleRemoteEPC() [2/2]
llvm::orc::SimpleRemoteEPC::SimpleRemoteEPC (SimpleRemoteEPC &&) delete
~SimpleRemoteEPC()
llvm::orc::SimpleRemoteEPC::~SimpleRemoteEPC ()
Definition at line 20 of file SimpleRemoteEPC.cpp.
References assert().
Member Function Documentation
callWrapperAsync()
void llvm::orc::SimpleRemoteEPC::callWrapperAsync (ExecutorAddr WrapperFnAddr, IncomingWFRHandler OnComplete, ArrayRef< char > ArgBuffer) override virtual
Run a wrapper function in the executor.
The given WFRHandler will be called on the result when it is returned.
The wrapper function should be callable as:
CWrapperFunctionResult fn(uint8_t *Data, uint64_t Size);
{.cpp}
Implements llvm::orc::ExecutorProcessControl.
Definition at line 74 of file SimpleRemoteEPC.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), move, and uint64_t.
Create()
template<typename TransportT , typename... TransportTCtorArgTs> static Expected<std::unique_ptr<SimpleRemoteEPC> > llvm::orc::SimpleRemoteEPC::Create (std::unique_ptr< TaskDispatcher > D, Setup S, TransportTCtorArgTs &&... TransportTCtorArgs) inline static
Create a SimpleRemoteEPC using the given transport type and args.
Definition at line 51 of file SimpleRemoteEPC.h.
References llvm::orc::ExecutorProcessControl::D, move, and SimpleRemoteEPC().
disconnect()
Error llvm::orc::SimpleRemoteEPC::disconnect () override virtual
Disconnect from the target process.
This should be called after the JIT session is shut down.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 110 of file SimpleRemoteEPC.cpp.
References llvm::orc::ExecutorProcessControl::D, and move.
handleDisconnect()
void llvm::orc::SimpleRemoteEPC::handleDisconnect (Error Err) override virtual
Handle a disconnection from the underlying transport.
No further messages should be sent to handleMessage after this is called. Err may contain an Error value indicating unexpected disconnection. This allows clients to log such errors, but no attempt should be made at recovery (which should be handled inside the transport class, if it is supported at all).
Implements llvm::orc::SimpleRemoteEPCTransportClient.
Definition at line 176 of file SimpleRemoteEPC.cpp.
handleMessage()
Expected< SimpleRemoteEPCTransportClient::HandleMessageAction > llvm::orc::SimpleRemoteEPC::handleMessage (SimpleRemoteEPCOpcode OpC, uint64_t SeqNo, ExecutorAddr TagAddr, SimpleRemoteEPCArgBytesVector ArgBytes) override virtual
Handle receipt of a message.
Returns an Error if the message cannot be handled, 'EndSession' if the client will not accept any further messages, and 'ContinueSession' otherwise.
Implements llvm::orc::SimpleRemoteEPCTransportClient.
Definition at line 119 of file SimpleRemoteEPC.cpp.
References assert(), llvm::orc::CallWrapper, llvm::dbgs(), llvm::formatv(), llvm::orc::ExecutorAddr::getValue(), llvm::orc::Hangup, llvm::inconvertibleErrorCode(), llvm::orc::LastOpC, LLVM_DEBUG, llvm::orc::Result, and llvm::orc::Setup.
loadDylib()
Expected< tpctypes::DylibHandle > llvm::orc::SimpleRemoteEPC::loadDylib (const char * DylibPath) override virtual
Load the dynamic library at the given path and return a handle to it.
If LibraryPath is null this function will return the global handle for the target process.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 28 of file SimpleRemoteEPC.cpp.
lookupSymbols()
Expected< std::vector< tpctypes::LookupResult > > llvm::orc::SimpleRemoteEPC::lookupSymbols (ArrayRef< LookupRequest > Request) override virtual
Search for symbols in the target process.
The result of the lookup is a 2-dimentional array of target addresses that correspond to the lookup order. If a required symbol is not found then this method will return an error. If a weakly referenced symbol is not found then it be assigned a '0' value.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 33 of file SimpleRemoteEPC.cpp.
References Addr, and move.
operator=() [1/2]
SimpleRemoteEPC& llvm::orc::SimpleRemoteEPC::operator= (const SimpleRemoteEPC &) delete
operator=() [2/2]
SimpleRemoteEPC& llvm::orc::SimpleRemoteEPC::operator= (SimpleRemoteEPC &&) delete
runAsIntFunction()
Expected< int32_t > llvm::orc::SimpleRemoteEPC::runAsIntFunction (ExecutorAddr IntFnAddr, int Arg) override virtual
Run function with a int (*)(int) signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 65 of file SimpleRemoteEPC.cpp.
runAsMain()
Expected< int32_t > llvm::orc::SimpleRemoteEPC::runAsMain (ExecutorAddr MainFnAddr, ArrayRef< std::string > Args) override virtual
Run function with a main-like signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 48 of file SimpleRemoteEPC.cpp.
runAsVoidFunction()
Expected< int32_t > llvm::orc::SimpleRemoteEPC::runAsVoidFunction (ExecutorAddr VoidFnAddr) override virtual
Run function with a int (*)(void) signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 57 of file SimpleRemoteEPC.cpp.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/SimpleRemoteEPC.h
lib/ExecutionEngine/Orc/SimpleRemoteEPC.cpp