LLVM: llvm::StackSafetyInfo Class Reference
llvm::StackSafetyInfo Class Reference
Interface to access stack safety analysis results for single function.
#include "llvm/Analysis/StackSafetyAnalysis.h"
Classes
struct InfoTy
Public Member Functions
StackSafetyInfo ()
StackSafetyInfo (Function *F, std::function< ScalarEvolution &()> GetSE)
StackSafetyInfo (StackSafetyInfo &&)
StackSafetyInfo & operator= (StackSafetyInfo &&)
~StackSafetyInfo ()
const InfoTy & getInfo () const
void print (raw_ostream &O) const
std::vector< FunctionSummary::ParamAccess > getParamAccesses (ModuleSummaryIndex &Index) const
Parameters use for a FunctionSummary.
Detailed Description
Interface to access stack safety analysis results for single function.
Definition at line 26 of file StackSafetyAnalysis.h.
Constructor & Destructor Documentation
StackSafetyInfo() [1/3]
StackSafetyInfo::StackSafetyInfo () default
StackSafetyInfo() [2/3]
StackSafetyInfo::StackSafetyInfo (Function * F, std::function< ScalarEvolution &()> GetSE)
Definition at line 853 of file StackSafetyAnalysis.cpp.
StackSafetyInfo() [3/3]
StackSafetyInfo::StackSafetyInfo (StackSafetyInfo &&) default
~StackSafetyInfo()
StackSafetyInfo::~StackSafetyInfo () default
Member Function Documentation
getInfo()
const StackSafetyInfo::InfoTy & StackSafetyInfo::getInfo () const
Definition at line 863 of file StackSafetyAnalysis.cpp.
References F, and Info.
Referenced by getParamAccesses(), and print().
getParamAccesses()
std::vector< FunctionSummary::ParamAccess > StackSafetyInfo::getParamAccesses (ModuleSummaryIndex & Index) const
Parameters use for a FunctionSummary.
Function collects access information of all pointer parameters. Information includes a range of direct access of parameters by the functions and all call sites accepting the parameter. StackSafety assumes that missing parameter information means possibility of access to the parameter with any offset, so we can correctly link code without StackSafety information, e.g. non-ThinLTO.
Definition at line 909 of file StackSafetyAnalysis.cpp.
References getInfo(), Info, and llvm::sort().
operator=()
StackSafetyInfo & StackSafetyInfo::operator= (StackSafetyInfo &&) default
print()
void StackSafetyInfo::print (raw_ostream & O) const
Definition at line 871 of file StackSafetyAnalysis.cpp.
References F, getInfo(), llvm::StackSafetyInfo::InfoTy::Info, and llvm::RISCVFenceField::O.
The documentation for this class was generated from the following files:
include/llvm/Analysis/StackSafetyAnalysis.h
lib/Analysis/StackSafetyAnalysis.cpp