LLVM: llvm::MCPseudoProbeDecoder Class Reference
llvm::MCPseudoProbeDecoder Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Types
using Uint64Set = DenseSet< uint64_t >
using Uint64Map = DenseMap< uint64_t, uint64_t >
Public Member Functions
bool buildGUID2FuncDescMap (const uint8_t *Start, std::size_t Size)
bool buildAddress2ProbeMap (const uint8_t *Start, std::size_t Size, const Uint64Set &GuildFilter, const Uint64Map &FuncStartAddrs)
bool buildAddress2ProbeMap (MCDecodedPseudoProbeInlineTree *Cur, uint64_t &LastAddr, const Uint64Set &GuildFilter, const Uint64Map &FuncStartAddrs)
void printGUID2FuncDescMap (raw_ostream &OS)
void printProbeForAddress (raw_ostream &OS, uint64_t Address)
void printProbesForAllAddresses (raw_ostream &OS)
const MCDecodedPseudoProbe * getCallProbeForAddr (uint64_t Address) const
const MCPseudoProbeFuncDesc * getFuncDescForGUID (uint64_t GUID) const
void getInlineContextForProbe (const MCDecodedPseudoProbe *Probe, SmallVectorImpl< MCPseduoProbeFrameLocation > &InlineContextStack, bool IncludeLeaf) const
const AddressProbesMap & getAddress2ProbesMap () const
AddressProbesMap & getAddress2ProbesMap ()
const GUIDProbeFunctionMap & getGUID2FuncDescMap () const
const MCPseudoProbeFuncDesc * getInlinerDescForProbe (const MCDecodedPseudoProbe *Probe) const
const MCDecodedPseudoProbeInlineTree & getDummyInlineRoot () const
Detailed Description
Definition at line 329 of file MCPseudoProbe.h.
Member Typedef Documentation
Uint64Map
using llvm::MCPseudoProbeDecoder::Uint64Map = DenseMap<uint64_t, uint64_t>
Definition at line 359 of file MCPseudoProbe.h.
Uint64Set
using llvm::MCPseudoProbeDecoder::Uint64Set = DenseSet<uint64_t>
Definition at line 358 of file MCPseudoProbe.h.
Member Function Documentation
buildAddress2ProbeMap() [1/2]
bool MCPseudoProbeDecoder::buildAddress2ProbeMap (const uint8_t * Start, std::size_t Size, const Uint64Set & GuildFilter, const Uint64Map & FuncStartAddrs)
Definition at line 512 of file MCPseudoProbe.cpp.
References llvm::Data.
buildAddress2ProbeMap() [2/2]
bool MCPseudoProbeDecoder::buildAddress2ProbeMap (MCDecodedPseudoProbeInlineTree * Cur, uint64_t & LastAddr, const Uint64Set & GuildFilter, const Uint64Map & FuncStartAddrs)
Definition at line 404 of file MCPseudoProbe.cpp.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::addProbes(), Addr, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getChildren(), llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getOrAddNode(), llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Guid, I, llvm::isSentinelProbe(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), move, and uint64_t.
buildGUID2FuncDescMap()
bool MCPseudoProbeDecoder::buildGUID2FuncDescMap (const uint8_t * Start, std::size_t Size)
Definition at line 359 of file MCPseudoProbe.cpp.
References llvm::Data.
getAddress2ProbesMap() [1/2]
AddressProbesMap& llvm::MCPseudoProbeDecoder::getAddress2ProbesMap () inline
Definition at line 404 of file MCPseudoProbe.h.
getAddress2ProbesMap() [2/2]
const AddressProbesMap& llvm::MCPseudoProbeDecoder::getAddress2ProbesMap () const inline
Definition at line 400 of file MCPseudoProbe.h.
getCallProbeForAddr()
const MCDecodedPseudoProbe * MCPseudoProbeDecoder::getCallProbeForAddr (uint64_t Address) const
Definition at line 560 of file MCPseudoProbe.cpp.
References assert().
getDummyInlineRoot()
const MCDecodedPseudoProbeInlineTree& llvm::MCPseudoProbeDecoder::getDummyInlineRoot () const inline
Definition at line 413 of file MCPseudoProbe.h.
getFuncDescForGUID()
const MCPseudoProbeFuncDesc * MCPseudoProbeDecoder::getFuncDescForGUID (uint64_t GUID) const
Definition at line 579 of file MCPseudoProbe.cpp.
References assert().
getGUID2FuncDescMap()
const GUIDProbeFunctionMap& llvm::MCPseudoProbeDecoder::getGUID2FuncDescMap () const inline
Definition at line 406 of file MCPseudoProbe.h.
getInlineContextForProbe()
void MCPseudoProbeDecoder::getInlineContextForProbe (const MCDecodedPseudoProbe * Probe, SmallVectorImpl< MCPseduoProbeFrameLocation > & InlineContextStack, bool IncludeLeaf) const
Definition at line 585 of file MCPseudoProbe.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::MCPseudoProbeBase::getGuid(), llvm::MCPseudoProbeBase::getIndex(), and llvm::MCDecodedPseudoProbe::getInlineContext().
getInlinerDescForProbe()
const MCPseudoProbeFuncDesc * MCPseudoProbeDecoder::getInlinerDescForProbe (const MCDecodedPseudoProbe * Probe) const
Definition at line 599 of file MCPseudoProbe.cpp.
References llvm::MCDecodedPseudoProbe::getInlineTreeNode(), llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Guid, llvm::MCDecodedPseudoProbeInlineTree::hasInlineSite(), and llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Parent.
printGUID2FuncDescMap()
void MCPseudoProbeDecoder::printGUID2FuncDescMap (raw_ostream & OS)
Definition at line 525 of file MCPseudoProbe.cpp.
References I, and OS.
printProbeForAddress()
void MCPseudoProbeDecoder::printProbeForAddress (raw_ostream & OS, uint64_t Address)
Definition at line 535 of file MCPseudoProbe.cpp.
References OS.
printProbesForAllAddresses()
void MCPseudoProbeDecoder::printProbesForAllAddresses (raw_ostream & OS)
Definition at line 546 of file MCPseudoProbe.cpp.
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp