LLVM: llvm::orc::shared::WrapperFunctionResult Class Reference
llvm::orc::shared::WrapperFunctionResult Class Reference
C++ wrapper function result: Same as CWrapperFunctionResult but auto-releases memory.
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
Public Member Functions
WrapperFunctionResult ()
Create a default WrapperFunctionResult.
WrapperFunctionResult (CWrapperFunctionResult R)
Create a WrapperFunctionResult by taking ownership of a CWrapperFunctionResult.
WrapperFunctionResult (const WrapperFunctionResult &)=delete
WrapperFunctionResult & operator= (const WrapperFunctionResult &)=delete
WrapperFunctionResult (WrapperFunctionResult &&Other)
WrapperFunctionResult & operator= (WrapperFunctionResult &&Other)
~WrapperFunctionResult ()
CWrapperFunctionResult release ()
Release ownership of the contained CWrapperFunctionResult.
char * data ()
Get a pointer to the data contained in this instance.
const char * data () const
Get a const pointer to the data contained in this instance.
size_t size () const
Returns the size of the data contained in this instance.
bool empty () const
Returns true if this value is equivalent to a default-constructed WrapperFunctionResult.
const char * getOutOfBandError () const
If this value is an out-of-band error then this returns the error message, otherwise returns nullptr.
Static Public Member Functions
static WrapperFunctionResult allocate (size_t Size)
Create a WrapperFunctionResult with the given size and return a pointer to the underlying memory.
static WrapperFunctionResult copyFrom (const char *Source, size_t Size)
Copy from the given char range.
static WrapperFunctionResult copyFrom (const char *Source)
Copy from the given null-terminated string (includes the null-terminator).
static WrapperFunctionResult copyFrom (const std::string &Source)
Copy from the given std::string (includes the null terminator).
static WrapperFunctionResult createOutOfBandError (const char *Msg)
Create an out-of-band error by copying the given string.
static WrapperFunctionResult createOutOfBandError (const std::string &Msg)
Create an out-of-band error by copying the given string.
Detailed Description
C++ wrapper function result: Same as CWrapperFunctionResult but auto-releases memory.
Definition at line 40 of file WrapperFunctionUtils.h.
Constructor & Destructor Documentation
WrapperFunctionResult() [1/4]
llvm::orc::shared::WrapperFunctionResult::WrapperFunctionResult () inline
Create a default WrapperFunctionResult.
Definition at line 43 of file WrapperFunctionUtils.h.
WrapperFunctionResult() [2/4]
llvm::orc::shared::WrapperFunctionResult::WrapperFunctionResult (CWrapperFunctionResult R) inline
Create a WrapperFunctionResult by taking ownership of a CWrapperFunctionResult.
Warning: This should only be used by clients writing wrapper-function caller utilities (like TargetProcessControl).
Definition at line 50 of file WrapperFunctionUtils.h.
WrapperFunctionResult() [3/4]
llvm::orc::shared::WrapperFunctionResult::WrapperFunctionResult (const WrapperFunctionResult &) delete
WrapperFunctionResult() [4/4]
llvm::orc::shared::WrapperFunctionResult::WrapperFunctionResult (WrapperFunctionResult && Other) inline
Definition at line 58 of file WrapperFunctionUtils.h.
References Other, and std::swap().
~WrapperFunctionResult()
llvm::orc::shared::WrapperFunctionResult::~WrapperFunctionResult () inline
Definition at line 69 of file WrapperFunctionUtils.h.
References llvm::orc::shared::CWrapperFunctionResult::Data, llvm::orc::shared::CWrapperFunctionResult::Size, llvm::orc::shared::CWrapperFunctionResultDataUnion::Value, and llvm::orc::shared::CWrapperFunctionResultDataUnion::ValuePtr.
Member Function Documentation
allocate()
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::allocate (size_t Size) inline static
Create a WrapperFunctionResult with the given size and return a pointer to the underlying memory.
Definition at line 113 of file WrapperFunctionUtils.h.
References llvm::orc::shared::CWrapperFunctionResult::Data, llvm::orc::shared::CWrapperFunctionResult::Size, llvm::orc::shared::CWrapperFunctionResultDataUnion::Value, and llvm::orc::shared::CWrapperFunctionResultDataUnion::ValuePtr.
Referenced by copyFrom(), and llvm::orc::shared::detail::serializeViaSPSToWrapperFunctionResult().
copyFrom() [1/3]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::copyFrom (const char * Source) inline static
Copy from the given null-terminated string (includes the null-terminator).
Definition at line 130 of file WrapperFunctionUtils.h.
References copyFrom(), and llvm::Sched::Source.
copyFrom() [2/3]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::copyFrom (const char * Source, size_t Size) inline static
Copy from the given char range.
Definition at line 123 of file WrapperFunctionUtils.h.
References allocate(), memcpy(), and llvm::Sched::Source.
Referenced by copyFrom().
copyFrom() [3/3]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::copyFrom (const std::string & Source) inline static
Copy from the given std::string (includes the null terminator).
Definition at line 135 of file WrapperFunctionUtils.h.
References copyFrom(), and llvm::Sched::Source.
createOutOfBandError() [1/2]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::createOutOfBandError (const char * Msg) inline static
Create an out-of-band error by copying the given string.
Definition at line 140 of file WrapperFunctionUtils.h.
References llvm::orc::shared::CWrapperFunctionResult::Data, llvm::AMDGPU::SendMsg::Msg, and llvm::orc::shared::CWrapperFunctionResultDataUnion::ValuePtr.
Referenced by llvm::orc::shared::detail::WrapperFunctionHandlerHelper< RetT(ArgTs...), ResultSerializer, SPSTagTs... >::apply(), llvm::orc::shared::detail::WrapperFunctionAsyncHandlerHelper< RetT(SendResultT, ArgTs...), ResultSerializer, SPSTagTs... >::applyAsync(), createOutOfBandError(), llvm::orc::ExecutionSession::runJITDispatchHandler(), and llvm::orc::shared::detail::serializeViaSPSToWrapperFunctionResult().
createOutOfBandError() [2/2]
static WrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::createOutOfBandError (const std::string & Msg) inline static
Create an out-of-band error by copying the given string.
Definition at line 150 of file WrapperFunctionUtils.h.
References createOutOfBandError(), and llvm::AMDGPU::SendMsg::Msg.
data() [1/2]
char* llvm::orc::shared::WrapperFunctionResult::data () inline
Get a pointer to the data contained in this instance.
Definition at line 87 of file WrapperFunctionUtils.h.
References assert(), llvm::orc::shared::CWrapperFunctionResult::Data, llvm::orc::shared::CWrapperFunctionResult::Size, llvm::orc::shared::CWrapperFunctionResultDataUnion::Value, and llvm::orc::shared::CWrapperFunctionResultDataUnion::ValuePtr.
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call().
data() [2/2]
const char* llvm::orc::shared::WrapperFunctionResult::data () const inline
Get a const pointer to the data contained in this instance.
Definition at line 94 of file WrapperFunctionUtils.h.
References assert(), llvm::orc::shared::CWrapperFunctionResult::Data, llvm::orc::shared::CWrapperFunctionResult::Size, llvm::orc::shared::CWrapperFunctionResultDataUnion::Value, and llvm::orc::shared::CWrapperFunctionResultDataUnion::ValuePtr.
empty()
bool llvm::orc::shared::WrapperFunctionResult::empty () const inline
Returns true if this value is equivalent to a default-constructed WrapperFunctionResult.
Definition at line 109 of file WrapperFunctionUtils.h.
References llvm::orc::shared::CWrapperFunctionResult::Data, llvm::orc::shared::CWrapperFunctionResult::Size, and llvm::orc::shared::CWrapperFunctionResultDataUnion::ValuePtr.
getOutOfBandError()
const char* llvm::orc::shared::WrapperFunctionResult::getOutOfBandError () const inline
If this value is an out-of-band error then this returns the error message, otherwise returns nullptr.
Definition at line 156 of file WrapperFunctionUtils.h.
References llvm::orc::shared::CWrapperFunctionResult::Data, llvm::orc::shared::CWrapperFunctionResult::Size, and llvm::orc::shared::CWrapperFunctionResultDataUnion::ValuePtr.
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call().
operator=() [1/2]
WrapperFunctionResult& llvm::orc::shared::WrapperFunctionResult::operator= (const WrapperFunctionResult &) delete
operator=() [2/2]
WrapperFunctionResult& llvm::orc::shared::WrapperFunctionResult::operator= (WrapperFunctionResult && Other) inline
Definition at line 63 of file WrapperFunctionUtils.h.
References move, Other, and std::swap().
release()
CWrapperFunctionResult llvm::orc::shared::WrapperFunctionResult::release () inline
Release ownership of the contained CWrapperFunctionResult.
Warning: Do not use – this method will be removed in the future. It only exists to temporarily support some code that will eventually be moved to the ORC runtime.
Definition at line 79 of file WrapperFunctionUtils.h.
References std::swap().
size()
size_t llvm::orc::shared::WrapperFunctionResult::size () const inline
Returns the size of the data contained in this instance.
Definition at line 101 of file WrapperFunctionUtils.h.
References assert(), llvm::orc::shared::CWrapperFunctionResult::Data, llvm::orc::shared::CWrapperFunctionResult::Size, and llvm::orc::shared::CWrapperFunctionResultDataUnion::ValuePtr.
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h