LLVM: llvm::jitlink::InProcessEHFrameRegistrar Class Reference
llvm::jitlink::InProcessEHFrameRegistrar Class Reference final
Registers / Deregisters EH-frames in the current process.
#include "llvm/ExecutionEngine/JITLink/EHFrameSupport.h"
Public Member Functions
Error registerEHFrames (orc::ExecutorAddrRange EHFrameSection) override
Error deregisterEHFrames (orc::ExecutorAddrRange EHFrameSection) override
Public Member Functions inherited from llvm::jitlink::EHFrameRegistrar
virtual ~EHFrameRegistrar ()
Detailed Description
Registers / Deregisters EH-frames in the current process.
Definition at line 95 of file EHFrameSupport.h.
Member Function Documentation
deregisterEHFrames()
Error llvm::jitlink::InProcessEHFrameRegistrar::deregisterEHFrames (orc::ExecutorAddrRange EHFrameSection) override virtual
Implements llvm::jitlink::EHFrameRegistrar.
Definition at line 660 of file EHFrameSupport.cpp.
References llvm::orc::deregisterEHFrameSection(), llvm::orc::ExecutorAddrRange::size(), llvm::orc::ExecutorAddrRange::Start, and llvm::orc::ExecutorAddr::toPtr().
registerEHFrames()
Error llvm::jitlink::InProcessEHFrameRegistrar::registerEHFrames (orc::ExecutorAddrRange EHFrameSection) override virtual
Implements llvm::jitlink::EHFrameRegistrar.
Definition at line 654 of file EHFrameSupport.cpp.
References llvm::orc::registerEHFrameSection(), llvm::orc::ExecutorAddrRange::size(), llvm::orc::ExecutorAddrRange::Start, and llvm::orc::ExecutorAddr::toPtr().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/EHFrameSupport.h
lib/ExecutionEngine/JITLink/EHFrameSupport.cpp