LLVM: llvm::DiagnosticInfoDebugMetadataVersion Class Reference
llvm::DiagnosticInfoDebugMetadataVersion Class Reference
Diagnostic information for debug metadata version reporting.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoDebugMetadataVersion (const Module &M, unsigned MetadataVersion, DiagnosticSeverity Severity=DS_Warning)
The module that is concerned by this debug metadata version diagnostic.
const Module & getModule () const
unsigned getMetadataVersion () const
void print (DiagnosticPrinter &DP) const override
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for debug metadata version reporting.
This is basically a module and a version.
Definition at line 186 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoDebugMetadataVersion()
llvm::DiagnosticInfoDebugMetadataVersion::DiagnosticInfoDebugMetadataVersion (const Module & M, unsigned MetadataVersion, DiagnosticSeverity Severity = DS_Warning) inline
The module that is concerned by this debug metadata version diagnostic.
The actual metadata version.
Definition at line 196 of file DiagnosticInfo.h.
References M.
Member Function Documentation
classof()
static bool llvm::DiagnosticInfoDebugMetadataVersion::classof (const DiagnosticInfo * DI) inline static
Definition at line 207 of file DiagnosticInfo.h.
References llvm::DK_DebugMetadataVersion, and llvm::DiagnosticInfo::getKind().
getMetadataVersion()
unsigned llvm::DiagnosticInfoDebugMetadataVersion::getMetadataVersion () const inline
Definition at line 202 of file DiagnosticInfo.h.
Referenced by print().
getModule()
const Module& llvm::DiagnosticInfoDebugMetadataVersion::getModule () const inline
Definition at line 201 of file DiagnosticInfo.h.
References M.
Referenced by print().
print()
void DiagnosticInfoDebugMetadataVersion::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 82 of file DiagnosticInfo.cpp.
References DP, getMetadataVersion(), and getModule().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp