LLVM: llvm::RNSuccIterator< NodeRef, BlockT, RegionT > Class Template Reference
llvm::RNSuccIterator< NodeRef, BlockT, RegionT > Class Template Reference
Hierarchical RegionNode successor iterator.
#include "llvm/Analysis/RegionIterator.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = NodeRef
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
using Self = RNSuccIterator< NodeRef, BlockT, RegionT >
Public Member Functions
RNSuccIterator (NodeRef node)
Create begin iterator of a RegionNode.
RNSuccIterator (NodeRef node, bool)
Create an end iterator.
bool operator== (const Self &x) const
bool operator!= (const Self &x) const
value_type operator* () const
Self & operator++ ()
Self operator++ (int)
Detailed Description
template<class NodeRef, class BlockT, class RegionT>
class llvm::RNSuccIterator< NodeRef, BlockT, RegionT >
Hierarchical RegionNode successor iterator.
This iterator iterates over all successors of a RegionNode.
For a BasicBlock RegionNode it skips all BasicBlocks that are not part of the parent Region. Furthermore for BasicBlocks that start a subregion, a RegionNode representing the subregion is returned.
For a subregion RegionNode there is just one successor. The RegionNode representing the exit of the subregion.
Definition at line 38 of file RegionIterator.h.
Member Typedef Documentation
difference_type
template<class NodeRef , class BlockT , class RegionT > using llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::difference_type = std::ptrdiff_t
Definition at line 42 of file RegionIterator.h.
iterator_category
template<class NodeRef , class BlockT , class RegionT > using llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::iterator_category = std::forward_iterator_tag
Definition at line 40 of file RegionIterator.h.
pointer
template<class NodeRef , class BlockT , class RegionT > using llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::pointer = value_type *
Definition at line 43 of file RegionIterator.h.
reference
template<class NodeRef , class BlockT , class RegionT > using llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::reference = value_type &
Definition at line 44 of file RegionIterator.h.
Self
template<class NodeRef , class BlockT , class RegionT > using llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::Self = RNSuccIterator<NodeRef, BlockT, RegionT>
Definition at line 106 of file RegionIterator.h.
value_type
template<class NodeRef , class BlockT , class RegionT > using llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::value_type = NodeRef
Definition at line 41 of file RegionIterator.h.
Constructor & Destructor Documentation
RNSuccIterator() [1/2]
template<class NodeRef , class BlockT , class RegionT > llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::RNSuccIterator (NodeRef node) inline
Create begin iterator of a RegionNode.
Definition at line 109 of file RegionIterator.h.
References node.
RNSuccIterator() [2/2]
template<class NodeRef , class BlockT , class RegionT > llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::RNSuccIterator (NodeRef node, bool) inline
Create an end iterator.
Definition at line 122 of file RegionIterator.h.
Member Function Documentation
operator!=()
template<class NodeRef , class BlockT , class RegionT > bool llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator!= (const Self & x) const inline
Definition at line 134 of file RegionIterator.h.
References llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator==(), and x.
operator*()
template<class NodeRef , class BlockT , class RegionT > value_type llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator* () const inline
Definition at line 136 of file RegionIterator.h.
References assert(), and BB.
operator++() [1/2]
template<class NodeRef , class BlockT , class RegionT > Self& llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator++ () inline
Definition at line 142 of file RegionIterator.h.
operator++() [2/2]
template<class NodeRef , class BlockT , class RegionT > Self llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator++ (int) inline
Definition at line 156 of file RegionIterator.h.
operator==()
template<class NodeRef , class BlockT , class RegionT > bool llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator== (const Self & x) const inline
Definition at line 126 of file RegionIterator.h.
References assert(), and x.
Referenced by llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator!=(), and llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::operator!=().
The documentation for this class was generated from the following file:
include/llvm/Analysis/RegionIterator.h