LLVM: llvm::WebAssemblySubtarget Class Reference
llvm::WebAssemblySubtarget Class Reference final
#include "Target/WebAssembly/WebAssemblySubtarget.h"
Public Member Functions
WebAssemblySubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
This constructor initializes the data members to match that of the specified triple.
const WebAssemblySelectionDAGInfo * getSelectionDAGInfo () const override
const WebAssemblyFrameLowering * getFrameLowering () const override
const WebAssemblyTargetLowering * getTargetLowering () const override
const WebAssemblyInstrInfo * getInstrInfo () const override
const WebAssemblyRegisterInfo * getRegisterInfo () const override
const Triple & getTargetTriple () const
bool enableAtomicExpand () const override
bool enableIndirectBrExpand () const override
bool enableMachineScheduler () const override
bool useAA () const override
bool hasAddr64 () const
bool hasSIMD128 () const
bool hasRelaxedSIMD () const
bool hasAtomics () const
bool hasNontrappingFPToInt () const
bool hasSignExt () const
bool hasExceptionHandling () const
bool hasBulkMemory () const
bool hasMultivalue () const
bool hasMutableGlobals () const
bool hasTailCall () const
bool hasReferenceTypes () const
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Parses features string setting specified subtarget options.
Detailed Description
Definition at line 35 of file WebAssemblySubtarget.h.
Constructor & Destructor Documentation
WebAssemblySubtarget()
WebAssemblySubtarget::WebAssemblySubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 40 of file WebAssemblySubtarget.cpp.
Member Function Documentation
enableAtomicExpand()
bool WebAssemblySubtarget::enableAtomicExpand () const override
Definition at line 48 of file WebAssemblySubtarget.cpp.
References hasAtomics().
enableIndirectBrExpand()
bool llvm::WebAssemblySubtarget::enableIndirectBrExpand () const inline override
Definition at line 87 of file WebAssemblySubtarget.h.
enableMachineScheduler()
bool WebAssemblySubtarget::enableMachineScheduler () const override
Definition at line 53 of file WebAssemblySubtarget.cpp.
getFrameLowering()
const WebAssemblyFrameLowering* llvm::WebAssemblySubtarget::getFrameLowering () const inline override
Definition at line 73 of file WebAssemblySubtarget.h.
getInstrInfo()
const WebAssemblyInstrInfo* llvm::WebAssemblySubtarget::getInstrInfo () const inline override
Definition at line 79 of file WebAssemblySubtarget.h.
References InstrInfo.
Referenced by getRegisterInfo().
getRegisterInfo()
const WebAssemblyRegisterInfo* llvm::WebAssemblySubtarget::getRegisterInfo () const inline override
Definition at line 82 of file WebAssemblySubtarget.h.
References getInstrInfo(), and llvm::WebAssemblyInstrInfo::getRegisterInfo().
Referenced by llvm::WebAssemblyAsmPrinter::getRegType(), replaceDominatedUses(), and llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering().
getSelectionDAGInfo()
const WebAssemblySelectionDAGInfo* llvm::WebAssemblySubtarget::getSelectionDAGInfo () const inline override
Definition at line 70 of file WebAssemblySubtarget.h.
getTargetLowering()
const WebAssemblyTargetLowering* llvm::WebAssemblySubtarget::getTargetLowering () const inline override
Definition at line 76 of file WebAssemblySubtarget.h.
Referenced by llvm::WebAssemblyAsmPrinter::emitGlobalVariable().
getTargetTriple()
const Triple& llvm::WebAssemblySubtarget::getTargetTriple () const inline
Definition at line 85 of file WebAssemblySubtarget.h.
hasAddr64()
bool llvm::WebAssemblySubtarget::hasAddr64 () const inline
Definition at line 92 of file WebAssemblySubtarget.h.
References llvm::Triple::isArch64Bit().
Referenced by llvm::getLibcallSignature(), llvm::WebAssemblyAsmPrinter::getOrCreateWasmSymbol(), llvm::WebAssemblyRegisterInfo::getPointerRegClass(), LowerCallResults(), and llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering().
hasAtomics()
bool llvm::WebAssemblySubtarget::hasAtomics () const inline
Definition at line 95 of file WebAssemblySubtarget.h.
Referenced by enableAtomicExpand().
hasBulkMemory()
bool llvm::WebAssemblySubtarget::hasBulkMemory () const inline
Definition at line 99 of file WebAssemblySubtarget.h.
hasExceptionHandling()
bool llvm::WebAssemblySubtarget::hasExceptionHandling () const inline
Definition at line 98 of file WebAssemblySubtarget.h.
hasMultivalue()
bool llvm::WebAssemblySubtarget::hasMultivalue () const inline
Definition at line 100 of file WebAssemblySubtarget.h.
Referenced by llvm::computeSignatureVTs().
hasMutableGlobals()
bool llvm::WebAssemblySubtarget::hasMutableGlobals () const inline
Definition at line 101 of file WebAssemblySubtarget.h.
hasNontrappingFPToInt()
bool llvm::WebAssemblySubtarget::hasNontrappingFPToInt () const inline
Definition at line 96 of file WebAssemblySubtarget.h.
Referenced by llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering().
hasReferenceTypes()
bool llvm::WebAssemblySubtarget::hasReferenceTypes () const inline
Definition at line 103 of file WebAssemblySubtarget.h.
Referenced by llvm::WebAssembly::getOrCreateFuncrefCallTableSymbol(), llvm::WebAssembly::getOrCreateFunctionTableSymbol(), LowerCallResults(), and llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering().
hasRelaxedSIMD()
bool llvm::WebAssemblySubtarget::hasRelaxedSIMD () const inline
Definition at line 94 of file WebAssemblySubtarget.h.
hasSignExt()
bool llvm::WebAssemblySubtarget::hasSignExt () const inline
Definition at line 97 of file WebAssemblySubtarget.h.
Referenced by llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering().
hasSIMD128()
bool llvm::WebAssemblySubtarget::hasSIMD128 () const inline
Definition at line 93 of file WebAssemblySubtarget.h.
Referenced by llvm::WebAssemblyTargetLowering::WebAssemblyTargetLowering().
hasTailCall()
bool llvm::WebAssemblySubtarget::hasTailCall () const inline
Definition at line 102 of file WebAssemblySubtarget.h.
Referenced by llvm::WebAssemblyTTIImpl::supportsTailCalls().
ParseSubtargetFeatures()
void llvm::WebAssemblySubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
useAA()
bool WebAssemblySubtarget::useAA () const override
Definition at line 60 of file WebAssemblySubtarget.cpp.
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblySubtarget.h
lib/Target/WebAssembly/WebAssemblySubtarget.cpp