LLVM: llvm::PPCInstPrinter Class Reference
llvm::PPCInstPrinter Class Reference
#include "Target/PowerPC/MCTargetDesc/PPCInstPrinter.h"
Public Member Functions
PPCInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, Triple T)
void printRegName (raw_ostream &OS, MCRegister Reg) const override
Print the assembler register name.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI) override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &OS)
void printCustomAliasOperand (const MCInst *MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &OS)
void printOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printPredicateOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O, const char *Modifier=nullptr)
void printATBitsAsHint (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU1ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU2ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU3ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU4ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printS5ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU5ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU6ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU7ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU8ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU10ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU12ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printS16ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printS34ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printU16ImmOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printImmZeroOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printBranchOperand (const MCInst *MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printAbsBranchOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printTLSCall (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printcrbitm (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printMemRegImm (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printMemRegImmHash (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printMemRegImm34PCRel (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printMemRegImm34 (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printMemRegReg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
Detailed Description
Definition at line 21 of file PPCInstPrinter.h.
Constructor & Destructor Documentation
PPCInstPrinter()
llvm::PPCInstPrinter::PPCInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, Triple T) inline
Definition at line 30 of file PPCInstPrinter.h.
References T.
Member Function Documentation
getMnemonic()
std::pair<const char *, uint64_t> llvm::PPCInstPrinter::getMnemonic (const MCInst * MI) override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
getRegisterName()
static const char* llvm::PPCInstPrinter::getRegisterName (MCRegister Reg) static
Referenced by printOperand(), and printRegName().
printAbsBranchOperand()
void PPCInstPrinter::printAbsBranchOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 481 of file PPCInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printOperand().
printAliasInstr()
bool llvm::PPCInstPrinter::printAliasInstr (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & OS)
Referenced by printInst().
printATBitsAsHint()
void PPCInstPrinter::printATBitsAsHint (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 316 of file PPCInstPrinter.cpp.
References MI, and llvm::RISCVFenceField::O.
printBranchOperand()
void PPCInstPrinter::printBranchOperand (const MCInst * MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 454 of file PPCInstPrinter.cpp.
References llvm::MCInstPrinter::formatHex(), llvm::RISCVMatInt::Imm, llvm::Triple::isOSAIX(), llvm::Triple::isPPC64(), MI, llvm::RISCVFenceField::O, llvm::MCInstPrinter::PrintBranchImmAsAddress, printOperand(), and uint64_t.
printcrbitm()
void PPCInstPrinter::printcrbitm (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 490 of file PPCInstPrinter.cpp.
References llvm_unreachable, MI, and llvm::RISCVFenceField::O.
printCustomAliasOperand()
void llvm::PPCInstPrinter::printCustomAliasOperand (const MCInst * MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & OS)
printImmZeroOperand()
void PPCInstPrinter::printImmZeroOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 366 of file PPCInstPrinter.cpp.
References assert(), int, MI, and llvm::RISCVFenceField::O.
Referenced by printMemRegImm34PCRel().
printInst()
void PPCInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 55 of file PPCInstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCSymbolRefExpr::getKind(), llvm::MCSymbolRefExpr::getSymbol(), int, llvm::MCOperand::isExpr(), llvm::Triple::isOSAIX(), llvm::MCInstPrinter::MAI, MI, llvm::RISCVFenceField::O, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), printInstruction(), printOperand(), and llvm::MCSymbolRefExpr::VK_PPC_PCREL_OPT.
printInstruction()
void llvm::PPCInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by printInst().
printMemRegImm()
void PPCInstPrinter::printMemRegImm (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 508 of file PPCInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, printOperand(), and printS16ImmOperand().
printMemRegImm34()
void PPCInstPrinter::printMemRegImm34 (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 538 of file PPCInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, printOperand(), and printS34ImmOperand().
printMemRegImm34PCRel()
void PPCInstPrinter::printMemRegImm34PCRel (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 529 of file PPCInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, printImmZeroOperand(), and printS34ImmOperand().
printMemRegImmHash()
void PPCInstPrinter::printMemRegImmHash (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 520 of file PPCInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printOperand().
printMemRegReg()
void PPCInstPrinter::printMemRegReg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 547 of file PPCInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printOperand().
printOperand()
void PPCInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 637 of file PPCInstPrinter.cpp.
References assert(), llvm::MCInstrInfo::get(), llvm::MCRegisterInfo::getEncodingValue(), getRegisterName(), llvm::PPCInstrInfo::getRegNumForOperand(), llvm::MCInstPrinter::MAI, MI, llvm::MCInstPrinter::MII, llvm::MCInstPrinter::MRI, llvm::RISCVFenceField::O, RegName, ShowVSRNumsAsVR, and llvm::PPCRegisterInfo::stripRegisterPrefix().
Referenced by printAbsBranchOperand(), printBranchOperand(), printInst(), printMemRegImm(), printMemRegImm34(), printMemRegImmHash(), printMemRegReg(), printPredicateOperand(), printS16ImmOperand(), printS34ImmOperand(), printTLSCall(), and printU16ImmOperand().
printPredicateOperand()
void PPCInstPrinter::printPredicateOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 218 of file PPCInstPrinter.cpp.
References assert(), llvm_unreachable, MI, llvm::RISCVFenceField::O, llvm::PPC::PRED_BIT_SET, llvm::PPC::PRED_BIT_UNSET, llvm::PPC::PRED_EQ, llvm::PPC::PRED_EQ_MINUS, llvm::PPC::PRED_EQ_PLUS, llvm::PPC::PRED_GE, llvm::PPC::PRED_GE_MINUS, llvm::PPC::PRED_GE_PLUS, llvm::PPC::PRED_GT, llvm::PPC::PRED_GT_MINUS, llvm::PPC::PRED_GT_PLUS, llvm::PPC::PRED_LE, llvm::PPC::PRED_LE_MINUS, llvm::PPC::PRED_LE_PLUS, llvm::PPC::PRED_LT, llvm::PPC::PRED_LT_MINUS, llvm::PPC::PRED_LT_PLUS, llvm::PPC::PRED_NE, llvm::PPC::PRED_NE_MINUS, llvm::PPC::PRED_NE_PLUS, llvm::PPC::PRED_NU, llvm::PPC::PRED_NU_MINUS, llvm::PPC::PRED_NU_PLUS, llvm::PPC::PRED_UN, llvm::PPC::PRED_UN_MINUS, llvm::PPC::PRED_UN_PLUS, and printOperand().
printRegName()
void PPCInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 50 of file PPCInstPrinter.cpp.
References getRegisterName(), OS, and RegName.
printS16ImmOperand()
void PPCInstPrinter::printS16ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 424 of file PPCInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printOperand().
Referenced by printMemRegImm().
printS34ImmOperand()
void PPCInstPrinter::printS34ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 433 of file PPCInstPrinter.cpp.
References assert(), MI, llvm::RISCVFenceField::O, and printOperand().
Referenced by printMemRegImm34(), and printMemRegImm34PCRel().
printS5ImmOperand()
void PPCInstPrinter::printS5ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 358 of file PPCInstPrinter.cpp.
References int, MI, and llvm::RISCVFenceField::O.
printTLSCall()
void PPCInstPrinter::printTLSCall (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 561 of file PPCInstPrinter.cpp.
References llvm::MCSymbolRefExpr::getKind(), llvm::MCSymbol::getName(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCConstantExpr::getValue(), llvm::MCSymbolRefExpr::getVariantKindName(), MI, llvm::RISCVFenceField::O, printOperand(), llvm::MCSymbolRefExpr::VK_None, and llvm::MCSymbolRefExpr::VK_PPC_NOTOC.
printU10ImmOperand()
void PPCInstPrinter::printU10ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 408 of file PPCInstPrinter.cpp.
References assert(), MI, and llvm::RISCVFenceField::O.
printU12ImmOperand()
void PPCInstPrinter::printU12ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 416 of file PPCInstPrinter.cpp.
References assert(), MI, and llvm::RISCVFenceField::O.
printU16ImmOperand()
void PPCInstPrinter::printU16ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 445 of file PPCInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printOperand().
printU1ImmOperand()
void PPCInstPrinter::printU1ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 326 of file PPCInstPrinter.cpp.
References assert(), int, MI, and llvm::RISCVFenceField::O.
printU2ImmOperand()
void PPCInstPrinter::printU2ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 334 of file PPCInstPrinter.cpp.
References assert(), int, MI, and llvm::RISCVFenceField::O.
printU3ImmOperand()
void PPCInstPrinter::printU3ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 342 of file PPCInstPrinter.cpp.
References assert(), int, MI, and llvm::RISCVFenceField::O.
printU4ImmOperand()
void PPCInstPrinter::printU4ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 350 of file PPCInstPrinter.cpp.
References assert(), int, MI, and llvm::RISCVFenceField::O.
printU5ImmOperand()
void PPCInstPrinter::printU5ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 374 of file PPCInstPrinter.cpp.
References assert(), int, MI, and llvm::RISCVFenceField::O.
printU6ImmOperand()
void PPCInstPrinter::printU6ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 382 of file PPCInstPrinter.cpp.
References assert(), int, MI, and llvm::RISCVFenceField::O.
printU7ImmOperand()
void PPCInstPrinter::printU7ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 390 of file PPCInstPrinter.cpp.
References assert(), int, MI, and llvm::RISCVFenceField::O.
printU8ImmOperand()
void PPCInstPrinter::printU8ImmOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 401 of file PPCInstPrinter.cpp.
References int, MI, and llvm::RISCVFenceField::O.
The documentation for this class was generated from the following files:
lib/Target/PowerPC/MCTargetDesc/PPCInstPrinter.h
lib/Target/PowerPC/MCTargetDesc/PPCInstPrinter.cpp