LLVM: llvm::AsmPrinter Class Reference
llvm::AsmPrinter Class Reference
This class is intended to be used as a driving class for all asm writers.
#include "llvm/CodeGen/AsmPrinter.h"
Classes
struct HandlerInfo
struct HandlerInfo and Handlers permit users or target extended AsmPrinter to add their own handlers.
struct MBBSectionRange
Map a basic block section ID to the begin and end symbols of that section which determine the section's range.
struct Structor
llvm.global_ctors and llvm.global_dtors are arrays of Structor structs.
struct XRayFunctionEntry
Public Types
enum CFISection : unsigned { CFISection::None = 0, CFISection::EH = 1, CFISection::Debug = 2 }
enum SledKind : uint8_t {
SledKind::FUNCTION_ENTER = 0, SledKind::FUNCTION_EXIT = 1, SledKind::TAIL_CALL = 2, SledKind::LOG_ARGS_ENTER = 3,
SledKind::CUSTOM_EVENT = 4, SledKind::TYPED_EVENT = 5
}
using GOTEquivUsePair = std::pair< const GlobalVariable *, unsigned >
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
using AliasMapTy = DenseMap< uint64_t, SmallVector< const GlobalAlias *, 1 > >
Print a general LLVM constant to the .s file.
Public Member Functions
~AsmPrinter () override
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
uint16_t getDwarfVersion () const
void setDwarfVersion (uint16_t Version)
bool isDwarf64 () const
unsigned int getDwarfOffsetByteSize () const
Returns 4 for DWARF32 and 8 for DWARF64.
unsigned int getUnitLengthFieldByteSize () const
Returns 4 for DWARF32 and 12 for DWARF64.
dwarf::FormParams getDwarfFormParams () const
Returns information about the byte size of DW_FORM values.
bool isPositionIndependent () const
bool isVerbose () const
Return true if assembly output should contain comments.
unsigned getFunctionNumber () const
Return a unique ID for the current function.
virtual const MCSymbol * getFunctionFrameSymbol () const
Return symbol for the function pseudo stack if the stack frame is not a register based.
MCSymbol * getFunctionBegin () const
MCSymbol * getFunctionEnd () const
MCSymbol * getMBBExceptionSym (const MachineBasicBlock &MBB)
MCSymbol * getAddrLabelSymbol (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
ArrayRef< MCSymbol * > getAddrLabelSymbolToEmit (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
void takeDeletedSymbolsForFunction (const Function *F, std::vector< MCSymbol * > &Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
unsigned getPointerSize () const
Return the pointer size from the TargetMachine.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
void emitInitialRawDwarfLocDirective (const MachineFunction &MF)
Emits inital debug location directive.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
MCSymbol * getSymbolPreferLocal (const GlobalValue &GV) const
Similar to getSymbol() but preferred for references.
bool doesDwarfUseRelocationsAcrossSections () const
void setDwarfUsesRelocationsAcrossSections (bool Enable)
void recordSled (MCSymbol *Sled, const MachineInstr &MI, SledKind Kind, uint8_t Version=0)
void emitXRayTable ()
Emit a table with all XRay instrumentation points.
void emitPatchableFunctionEntries ()
void getAnalysisUsage (AnalysisUsage &AU) const override
Record analysis usage.
bool doInitialization (Module &M) override
Set up the AsmPrinter when we are working on a new module.
bool doFinalization (Module &M) override
Shut down the asmprinter.
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
virtual void SetupMachineFunction (MachineFunction &MF)
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
void emitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
void emitStackSizeSection (const MachineFunction &MF)
void emitStackUsage (const MachineFunction &MF)
void emitBBAddrMapSection (const MachineFunction &MF)
void emitKCFITrapEntry (const MachineFunction &MF, const MCSymbol *Symbol)
virtual void emitKCFITypeId (const MachineFunction &MF)
void emitPseudoProbe (const MachineInstr &MI)
void emitRemarksSection (remarks::RemarkStreamer &RS)
void emitPCSectionsLabel (const MachineFunction &MF, const MDNode &MD)
Emits a label as reference for PC sections.
void emitPCSections (const MachineFunction &MF)
Emits the PC sections collected from instructions.
CFISection getFunctionCFISectionType (const Function &F) const
Get the CFISection type for a function.
CFISection getFunctionCFISectionType (const MachineFunction &MF) const
Get the CFISection type for a function.
CFISection getModuleCFISectionType () const
Get the CFISection type for the module.
bool needsSEHMoves ()
bool needsCFIForDebug () const
Since emitting CFI unwind information is entangled with supporting the exceptions, this returns true for platforms which use CFI unwind information for debugging purpose when MCAsmInfo::ExceptionsType == ExceptionHandling::None.
virtual void emitConstantPool ()
Print to the current output stream assembly representations of the constants in the constant pool MCP.
virtual void emitJumpTableInfo ()
Print assembly representations of the jump tables used by the current function to the current output stream.
virtual void emitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool emitSpecialLLVMGlobal (const GlobalVariable *GV)
Check to see if the specified global is a special global used by LLVM.
void preprocessXXStructorList (const DataLayout &DL, const Constant *List, SmallVector< Structor, 8 > &Structors)
This method gathers an array of Structors and then sorts them out by Priority.
virtual void emitXXStructorList (const DataLayout &DL, const Constant *List, bool IsCtor)
This method emits llvm.global_ctors or llvm.global_dtors list.
void emitAlignment (Align Alignment, const GlobalObject *GV=nullptr, unsigned MaxBytesToEmit=0) const
Emit an alignment directive to the specified power of two boundary.
virtual const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void emitGlobalConstant (const DataLayout &DL, const Constant *CV, AliasMapTy *AliasList=nullptr)
EmitGlobalConstant - Print a general LLVM constant to the .s file.
void computeGlobalGOTEquivs (Module &M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
void emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
void emitStackMaps ()
Emit the stack maps.
void addAsmPrinterHandler (HandlerInfo Handler)
virtual void emitStartOfAsmFile (Module &)
This virtual method can be overridden by targets that want to emit something at the start of their file.
virtual void emitEndOfAsmFile (Module &)
This virtual method can be overridden by targets that want to emit something at the end of their file.
virtual void emitFunctionBodyStart ()
Targets can override this to emit stuff before the first basic block in the function.
virtual void emitFunctionBodyEnd ()
Targets can override this to emit stuff after the last basic block in the function.
virtual void emitBasicBlockStart (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the start of a basic block.
virtual void emitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual void emitInstruction (const MachineInstr *)
Targets should implement this to emit instructions.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void emitFunctionEntryLabel ()
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
virtual void emitFunctionDescriptor ()
virtual void emitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void emitXXStructor (const DataLayout &DL, const Constant *CV)
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
virtual void emitImplicitDef (const MachineInstr *MI) const
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
void emitNops (unsigned N)
Emit N NOP instructions.
MCSymbol * createTempSymbol (const Twine &Name) const
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void emitInt8 (int Value) const
Emit a byte directive and value.
void emitInt16 (int Value) const
Emit a short directive and value.
void emitInt32 (int Value) const
Emit a long directive and value.
void emitInt64 (uint64_t Value) const
Emit a long long directive and value.
void emitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void emitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void emitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
void emitLabelDifferenceAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) const
Emit something like ".uleb128 Hi-Lo".
void emitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitEncodingByte (unsigned Val, const char *Desc=nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
virtual void emitTTypeReference (const GlobalValue *GV, unsigned Encoding)
Emit reference to a ttype global with a specified encoding.
void emitDwarfSymbolReference (const MCSymbol *Label, bool ForceOffset=false) const
Emit a reference to a symbol for use in dwarf.
void emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4- or 8-byte offset of a string from the start of its section.
void emitDwarfStringOffset (DwarfStringPoolEntryRef S) const
Emit the 4-or 8-byte offset of a string from the start of its section.
void emitDwarfOffset (const MCSymbol *Label, uint64_t Offset) const
Emit something like ".long Label + Offset" or ".quad Label + Offset" depending on the DWARF format.
void emitDwarfLengthOrOffset (uint64_t Value) const
Emit 32- or 64-bit value depending on the DWARF format.
void emitDwarfUnitLength (uint64_t Length, const Twine &Comment) const
Emit a unit length field.
MCSymbol * emitDwarfUnitLength (const Twine &Prefix, const Twine &Comment) const
Emit a unit length field.
void emitCallSiteOffset (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
void emitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
virtual void emitDebugValue (const MCExpr *Value, unsigned Size) const
Emit the directive and value for debug thread local expression.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
template<typename T >
void emitDwarfAbbrevs (const T &Abbrevs) const
Emit Dwarf abbreviation table.
void emitDwarfAbbrev (const DIEAbbrev &Abbrev) const
void emitDwarfDIE (const DIE &Die) const
Recursively emit Dwarf DIE tree.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, StringRef Code) const
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
virtual void PrintSymbolOperand (const MachineOperand &MO, raw_ostream &OS)
Print the MachineOperand as a symbol.
virtual bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &OS)
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
virtual bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &OS)
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
virtual void emitInlineAsmStart () const
Let the target do anything it needs to do before emitting inlineasm.
virtual void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const
Let the target do anything it needs to do after emitting inlineasm.
void emitVisibility (MCSymbol *Sym, unsigned Visibility, bool IsDefinition=true) const
This emits visibility information about symbol, if this is supported by the target.
virtual void emitLinkage (const GlobalValue *GV, MCSymbol *GVSym) const
This emits linkage information about GVSym based on GV, if this is supported by the target.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Member Functions
static Align getGVAlignment (const GlobalObject *GV, const DataLayout &DL, Align InAlign=Align(1))
Return the alignment for the specified GV.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes
TargetMachine & TM
Target machine description.
const MCAsmInfo * MAI
Target Asm Printer information.
MCContext & OutContext
This is the context for the output file that we are streaming.
std::unique_ptr< MCStreamer > OutStreamer
This is the MCStreamer object for the file we are generating.
MachineFunction * MF = nullptr
The current machine function.
MachineModuleInfo * MMI = nullptr
This is a pointer to the current MachineModuleInfo.
MachineDominatorTree * MDT = nullptr
This is a pointer to the current MachineDominatorTree.
MachineLoopInfo * MLI = nullptr
This is a pointer to the current MachineLoopInfo.
MachineOptimizationRemarkEmitter * ORE
Optimization remark emitter.
MCSymbol * CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
MCSymbol * CurrentFnSym = nullptr
The symbol for the current function.
MCSymbol * CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
MCSymbol * CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
MapVector< unsigned, MBBSectionRange > MBBSectionRanges
MapVector< const MCSymbol *, GOTEquivUsePair > GlobalGOTEquivs
SmallVector< XRayFunctionEntry, 4 > Sleds
Protected Member Functions
AsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
virtual bool shouldEmitWeakSwiftAsyncExtendedFramePointerFlags () const
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes
MCSymbol * CurrentFnBegin = nullptr
MCSymbol * CurrentFnBeginLocal = nullptr
For dso_local functions, the current $local alias for the function.
std::vector< HandlerInfo > Handlers
A vector of all debug/EH info emitters we should use.
size_t NumUserHandlers = 0
StackMaps SM
Detailed Description
This class is intended to be used as a driving class for all asm writers.
Definition at line 84 of file AsmPrinter.h.
Member Typedef Documentation
AliasMapTy
using llvm::AsmPrinter::AliasMapTy = DenseMap<uint64_t, SmallVector<const GlobalAlias *, 1> >
Print a general LLVM constant to the .s file.
On AIX, when an alias refers to a sub-element of a global variable, the label of that alias needs to be emitted before the corresponding element.
Definition at line 511 of file AsmPrinter.h.
GOTEquivUsePair
using llvm::AsmPrinter::GOTEquivUsePair = std::pair<const GlobalVariable *, unsigned>
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
Definition at line 142 of file AsmPrinter.h.
Member Enumeration Documentation
CFISection
enum llvm::AsmPrinter::CFISection : unsigned strong
Enumerator
None
Do not emit either .eh_frame or .debug_frame.
EH
Emit .eh_frame.
Debug
Emit .debug_frame.
Definition at line 163 of file AsmPrinter.h.
SledKind
enum llvm::AsmPrinter::SledKind : uint8_t strong
Enumerator
FUNCTION_ENTER
FUNCTION_EXIT
TAIL_CALL
LOG_ARGS_ENTER
CUSTOM_EVENT
TYPED_EVENT
Definition at line 347 of file AsmPrinter.h.
Constructor & Destructor Documentation
AsmPrinter()
AsmPrinter::AsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) explicit protected
Definition at line 356 of file AsmPrinter.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), MAI, and OutStreamer.
~AsmPrinter()
AsmPrinter::~AsmPrinter () override
Definition at line 365 of file AsmPrinter.cpp.
References assert(), Handlers, and NumUserHandlers.
Member Function Documentation
addAsmPrinterHandler()
void llvm::AsmPrinter::addAsmPrinterHandler (HandlerInfo Handler) inline
Definition at line 537 of file AsmPrinter.h.
References Handlers, move, and NumUserHandlers.
computeGlobalGOTEquivs()
void AsmPrinter::computeGlobalGOTEquivs (Module & M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
Unnamed constant global variables solely contaning a pointer to another globals variable is equivalent to a GOT table entry; it contains the the address of another symbol.
One optimization is to replace accesses to these proxies by using the GOT entry for the final global instead. Hence, we select GOT equivalent candidates among all the module global variables, avoid emitting them unnecessarily and finally replace references to them by pc relative accesses to GOT entries.
Optimize it and replace accesses to these "GOT equivalents" by using the GOT entry for the final global instead. Compute GOT equivalent candidates among all global variables to avoid emitting them if possible later on, after it use is replaced by a GOT entry access.
Definition at line 1969 of file AsmPrinter.cpp.
References G, getObjFileLowering(), getSymbol(), GlobalGOTEquivs, isGOTEquivalentCandidate(), and M.
Referenced by doFinalization().
createTempSymbol()
MCSymbol * AsmPrinter::createTempSymbol (const Twine & Name) const
Definition at line 3617 of file AsmPrinter.cpp.
References llvm::MCContext::createTempSymbol(), and OutContext.
Referenced by llvm::DwarfFile::addRange(), llvm::DwarfDebug::beginModule(), llvm::EHStreamer::emitExceptionTable(), emitFunctionBody(), llvm::SystemZAsmPrinter::emitFunctionBodyEnd(), llvm::DwarfCompileUnit::emitHeader(), llvm::X86AsmPrinter::emitInstruction(), llvm::WasmException::endFunction(), getMBBExceptionSym(), and SetupMachineFunction().
doesDwarfUseRelocationsAcrossSections()
bool llvm::AsmPrinter::doesDwarfUseRelocationsAcrossSections () const inline
Definition at line 334 of file AsmPrinter.h.
Referenced by llvm::DwarfUnit::addSectionLabel(), emitDwarfStringOffset(), emitDwarfSymbolReference(), llvm::DIEString::emitValue(), and getDwarfFormParams().
doFinalization()
bool AsmPrinter::doFinalization (Module & M) override virtual
Shut down the asmprinter.
If you override this in your pass, you must make sure to call it explicitly.
Reimplemented from llvm::Pass.
Reimplemented in llvm::NVPTXAsmPrinter, llvm::AMDGPUAsmPrinter, and llvm::AVRAsmPrinter.
Definition at line 2133 of file AsmPrinter.cpp.
References Align, assert(), llvm::SmallVectorImpl< T >::clear(), computeGlobalGOTEquivs(), llvm::MCSymbolRefExpr::create(), llvm::GlobalValue::DefaultVisibility, DL, E, llvm::TargetOptions::EmitAddrsig, emitAlignment(), emitEndOfAsmFile(), emitGlobalGOTEquivs(), emitGlobalVariable(), emitLinkage(), llvm::TargetLoweringObjectFile::emitModuleMetadata(), emitRemarksSection(), emitStackMaps(), emitVisibility(), llvm::GlobalValue::ExternalWeakLinkage, F, G, llvm::MCAsmInfo::getCodePointerSize(), llvm::MCContext::getCOFFSection(), llvm::MCObjectFileInfo::getDataSection(), llvm::MCContext::getELFSection(), llvm::TargetLoweringObjectFile::getFunctionEntryPointSymbol(), llvm::MachineModuleInfoELF::GetGVStubList(), llvm::MachineModuleInfoCOFF::GetGVStubList(), llvm::Type::getInt8PtrTy(), llvm::MCAsmInfo::getNonexecutableStackSection(), llvm::MachineModuleInfo::getObjFileInfo(), getObjFileLowering(), llvm::SectionKind::getReadOnly(), getSymbol(), llvm::TargetMachine::getTargetTriple(), llvm::MCAsmInfo::getWeakRefDirective(), Handlers, llvm::AArch64CC::HI, I, llvm::COFF::IMAGE_COMDAT_SELECT_ANY, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_LNK_COMDAT, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Triple::isOSBinFormatCOFF(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isOSBinFormatXCOFF(), M, MAI, llvm::MCSA_Global, llvm::MCSA_WeakReference, MF, MI, MMI, NumUserHandlers, llvm::TargetMachine::Options, OutContext, OutStreamer, llvm::reverse(), S, shouldEmitWeakSwiftAsyncExtendedFramePointerFlags(), llvm::ELF::SHT_LLVM_SYMPART, llvm::ELF::SHT_PROGBITS, llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName, llvm::TimePassesIsEnabled, TM, and llvm::Value::use_empty().
Referenced by llvm::AVRAsmPrinter::doFinalization(), llvm::AMDGPUAsmPrinter::doFinalization(), and llvm::NVPTXAsmPrinter::doFinalization().
doInitialization()
bool AsmPrinter::doInitialization (Module & M) override virtual
Set up the AsmPrinter when we are working on a new module.
If your pass overrides this, it must make sure to explicitly call this implementation.
Reimplemented from llvm::Pass.
Reimplemented in llvm::NVPTXAsmPrinter, llvm::X86AsmPrinter, llvm::AMDGPUAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 428 of file AsmPrinter.cpp.
References llvm::AIX, llvm::ARM, assert(), BasicBlockProfileDump, CFGuardDescription, CFGuardName, CodeViewLineTablesGroupDescription, CodeViewLineTablesGroupName, DbgTimerDescription, DbgTimerName, llvm::MCAsmInfo::doesSupportDebugInformation(), llvm::DwarfCFI, DWARFGroupDescription, DWARFGroupName, EH, EHTimerDescription, EHTimerName, emitStartOfAsmFile(), F, llvm::sys::path::filename(), llvm::MCAsmInfo::getExceptionHandlingType(), getFunctionCFISectionType(), llvm::TargetMachine::getMCSubtargetInfo(), getObjFileLowering(), llvm::TargetMachine::getTargetTriple(), llvm::MCAsmInfo::getWinEHEncodingType(), Handlers, llvm::MCAsmInfo::hasBasenameOnlyForFileDirective(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::MCAsmInfo::hasFourStringsDotFile(), llvm::MCAsmInfo::hasSingleParameterDotFile(), llvm::AArch64CC::HI, I, llvm::WinEH::Invalid, llvm::Triple::isOSWindows(), llvm::WinEH::Itanium, llvm_unreachable, M, MAI, llvm::TargetOptions::MCOptions, MI, MMI, needsCFIForDebug(), llvm::None, None, llvm::TargetMachine::Options, OutContext, OutStreamer, PPGroupDescription, PPGroupName, PPTimerDescription, PPTimerName, llvm::PseudoProbeDescMetadataName, llvm::SjLj, llvm::TimePassesIsEnabled, TM, llvm::Wasm, llvm::WinEH, and llvm::WinEH::X86.
Referenced by llvm::SystemZAsmPrinter::doInitialization(), llvm::AMDGPUAsmPrinter::doInitialization(), llvm::X86AsmPrinter::doInitialization(), and llvm::NVPTXAsmPrinter::doInitialization().
emitAlignment()
void AsmPrinter::emitAlignment (Align Alignment, const GlobalObject * GV = nullptr, unsigned MaxBytesToEmit = 0) const
Emit an alignment directive to the specified power of two boundary.
If a global value is specified, and if that global has an explicit alignment requested, it will override the alignment request if required for correctness.
Definition at line 2911 of file AsmPrinter.cpp.
References Align, getCurrentSection(), llvm::Module::getDataLayout(), getGVAlignment(), llvm::TargetMachine::getMCSubtargetInfo(), llvm::GlobalValue::getParent(), getSubtargetInfo(), MF, OutStreamer, and TM.
Referenced by llvm::WinException::beginFunclet(), doFinalization(), emitBasicBlockStart(), emitConstantPool(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), llvm::MipsAsmPrinter::emitFunctionEntryLabel(), emitGlobalVariable(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), emitPatchableFunctionEntries(), llvm::X86AsmPrinter::emitStartOfAsmFile(), emitXXStructorList(), and llvm::ARMAsmPrinter::runOnMachineFunction().
emitBasicBlockEnd()
void AsmPrinter::emitBasicBlockEnd (const MachineBasicBlock & MBB) virtual
Targets can override this to emit stuff at the end of a basic block.
Reimplemented in llvm::MipsAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 3830 of file AsmPrinter.cpp.
References Handlers, llvm::AArch64CC::HI, llvm::MachineBasicBlock::isEndSection(), and MBB.
Referenced by llvm::X86AsmPrinter::emitBasicBlockEnd(), llvm::MipsAsmPrinter::emitBasicBlockEnd(), and emitFunctionBody().
emitBasicBlockStart()
void AsmPrinter::emitBasicBlockStart (const MachineBasicBlock & MBB) virtual
Targets can override this to emit stuff at the start of a basic block.
emitBasicBlockStart - This method prints the label for the specified MachineBasicBlock, an alignment (if present) and a comment describing it if appropriate.
By default, this method prints the label for the specified MachineBasicBlock, an alignment (if present) and a comment describing it if appropriate.
Reimplemented in llvm::AMDGPUAsmPrinter.
Definition at line 3750 of file AsmPrinter.cpp.
References Align, assert(), BB, emitAlignment(), emitBasicBlockLoopComments(), llvm::MachineBasicBlock::getAddressTakenIRBlock(), getAddrLabelSymbolToEmit(), llvm::MachineBasicBlock::getAlignment(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineBasicBlock::getEHCatchretSymbol(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineFunction::getFunction(), llvm::MachineBasicBlock::getMaxBytesForAlignment(), llvm::MachineBasicBlock::getNumber(), getObjFileLowering(), llvm::MachineBasicBlock::getSymbol(), Handlers, llvm::MachineBasicBlock::hasLabelMustBeEmitted(), llvm::AArch64CC::HI, llvm::MachineBasicBlock::isBeginSection(), llvm::MachineBasicBlock::isEHCatchretTarget(), llvm::MachineBasicBlock::isEHFuncletEntry(), llvm::MachineBasicBlock::isEntryBlock(), llvm::MachineBasicBlock::isIRBlockAddressTaken(), llvm::MachineBasicBlock::isMachineBlockAddressTaken(), isVerbose(), MAI, MBB, MF, MLI, OutStreamer, TM, and llvm::WinEH.
Referenced by llvm::AMDGPUAsmPrinter::emitBasicBlockStart(), and emitFunctionBody().
emitBBAddrMapSection()
void AsmPrinter::emitBBAddrMapSection (const MachineFunction & MF)
Definition at line 1349 of file AsmPrinter.cpp.
References assert(), emitLabelDifferenceAsULEB128(), getBBAddrMapMetadata(), llvm::MCObjectFileInfo::getBBAddrMapSection(), llvm::MachineBasicBlock::getBBID(), llvm::MachineBasicBlock::getEndSymbol(), getFunctionBegin(), getObjFileLowering(), getPointerSize(), llvm::MachineFunction::getSection(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineBasicBlock::isEntryBlock(), MBB, MF, OutStreamer, and llvm::MachineFunction::size().
Referenced by emitFunctionBody().
emitCallSiteOffset()
void AsmPrinter::emitCallSiteOffset (const MCSymbol * Hi, const MCSymbol * Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
Definition at line 185 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::DW_EH_PE_uleb128, emitLabelDifference(), emitLabelDifferenceAsULEB128(), and GetSizeOfEncodedValue().
emitCallSiteValue()
void AsmPrinter::emitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
Definition at line 194 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::DW_EH_PE_uleb128, emitULEB128(), GetSizeOfEncodedValue(), and OutStreamer.
emitCFIInstruction() [1/2]
void AsmPrinter::emitCFIInstruction (const MachineInstr & MI)
Definition at line 1296 of file AsmPrinter.cpp.
References llvm::ARM, llvm::DwarfCFI, llvm::MachineBasicBlock::end(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineFunction::getFrameInstructions(), getFunctionCFISectionType(), llvm::MachineBasicBlock::getParent(), llvm::ilist_node_impl< OptionsT >::getReverseIterator(), I, llvm::MachineBasicBlock::instr_end(), MAI, MBB, MF, MI, needsCFIForDebug(), None, and llvm::MachineFunction::rbegin().
Referenced by emitFunctionBody().
emitCFIInstruction() [2/2]
void AsmPrinter::emitCFIInstruction (const MCCFIInstruction & Inst) const
Emit frame instruction to describe the layout of the frame.
Definition at line 206 of file AsmPrinterDwarf.cpp.
References llvm::MCCFIInstruction::getAddressSpace(), llvm::MCCFIInstruction::getComment(), llvm::MCCFIInstruction::getOffset(), llvm::MCCFIInstruction::getOperation(), llvm::MCCFIInstruction::getRegister(), llvm::MCCFIInstruction::getRegister2(), llvm::MCCFIInstruction::getValues(), llvm_unreachable, llvm::MCCFIInstruction::OpAdjustCfaOffset, llvm::MCCFIInstruction::OpDefCfa, llvm::MCCFIInstruction::OpDefCfaOffset, llvm::MCCFIInstruction::OpDefCfaRegister, llvm::MCCFIInstruction::OpEscape, llvm::MCCFIInstruction::OpGnuArgsSize, llvm::MCCFIInstruction::OpLLVMDefAspaceCfa, llvm::MCCFIInstruction::OpNegateRAState, llvm::MCCFIInstruction::OpOffset, llvm::MCCFIInstruction::OpRegister, llvm::MCCFIInstruction::OpRememberState, llvm::MCCFIInstruction::OpRestore, llvm::MCCFIInstruction::OpRestoreState, llvm::MCCFIInstruction::OpSameValue, llvm::MCCFIInstruction::OpUndefined, llvm::MCCFIInstruction::OpWindowSave, and OutStreamer.
emitConstantPool()
void AsmPrinter::emitConstantPool () virtual
Print to the current output stream assembly representations of the constants in the constant pool MCP.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP.
This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented in llvm::MipsAsmPrinter, llvm::ARMAsmPrinter, llvm::WebAssemblyAsmPrinter, and llvm::CSKYAsmPrinter.
Definition at line 2458 of file AsmPrinter.cpp.
References Align, llvm::alignTo(), llvm::MachineConstantPoolEntry::ConstVal, llvm::HexagonISD::CP, llvm::numbers::e, emitAlignment(), emitGlobalConstant(), emitMachineConstantPoolValue(), llvm::MachineConstantPoolEntry::getAlign(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), GetCPISymbol(), getDataLayout(), getObjFileLowering(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::MachineConstantPoolEntry::getSectionKind(), llvm::MachineConstantPoolEntry::getSizeInBytes(), i, llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::MCSymbol::isUndefined(), j(), llvm::MachineConstantPoolEntry::MachineCPVal, MF, llvm::Offset, OutStreamer, S, and llvm::MachineConstantPoolEntry::Val.
Referenced by llvm::MipsAsmPrinter::emitConstantPool().
emitDebugValue()
void AsmPrinter::emitDebugValue (const MCExpr * Value, unsigned Size) const virtual
Emit the directive and value for debug thread local expression.
Value - The value to emit. Size - The size of the integer (in bytes) to emit.
Reimplemented in llvm::MipsAsmPrinter.
Definition at line 886 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by llvm::MipsAsmPrinter::emitDebugValue(), and llvm::DIEExpr::emitValue().
emitDwarfAbbrev()
void AsmPrinter::emitDwarfAbbrev (const DIEAbbrev & Abbrev) const
Definition at line 298 of file AsmPrinterDwarf.cpp.
References llvm::DIEAbbrev::Emit(), emitULEB128(), and llvm::DIEAbbrev::getNumber().
Referenced by emitDwarfAbbrevs().
emitDwarfAbbrevs()
template<typename T > void llvm::AsmPrinter::emitDwarfAbbrevs (const T & Abbrevs) const inline
Emit Dwarf abbreviation table.
Definition at line 755 of file AsmPrinter.h.
References emitDwarfAbbrev(), and emitULEB128().
Referenced by llvm::DIEAbbrevSet::Emit().
emitDwarfDIE()
void AsmPrinter::emitDwarfDIE (const DIE & Die) const
Recursively emit Dwarf DIE tree.
Definition at line 263 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::AccessibilityString(), assert(), llvm::dwarf::AttributeString(), llvm::DIE::children(), emitInt8(), emitULEB128(), llvm::DIE::getAbbrevNumber(), llvm::DIE::getOffset(), llvm::DIE::getSize(), llvm::DIE::getTag(), llvm::DIE::hasChildren(), isVerbose(), OutStreamer, llvm::dwarf::TagString(), llvm::Twine::utohexstr(), and llvm::DIEValueList::values().
Referenced by llvm::DwarfFile::emitUnit().
emitDwarfLengthOrOffset()
void AsmPrinter::emitDwarfLengthOrOffset (uint64_t Value) const
Emit 32- or 64-bit value depending on the DWARF format.
Definition at line 170 of file AsmPrinterDwarf.cpp.
References assert(), getDwarfOffsetByteSize(), isDwarf64(), and OutStreamer.
Referenced by llvm::DwarfUnit::emitCommonHeader(), and llvm::DwarfTypeUnit::emitHeader().
emitDwarfOffset()
void AsmPrinter::emitDwarfOffset (const MCSymbol * Label, uint64_t Offset) const
Emit something like ".long Label + Offset" or ".quad Label + Offset" depending on the DWARF format.
Definition at line 166 of file AsmPrinterDwarf.cpp.
References emitLabelPlusOffset(), getDwarfOffsetByteSize(), and llvm::Offset.
emitDwarfStringOffset() [1/2]
void AsmPrinter::emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4- or 8-byte offset of a string from the start of its section.
When possible, emit a DwarfStringPool section offset without any relocations, and without using the symbol. Otherwise, defers to emitDwarfSymbolReference().
The length of the emitted value depends on the DWARF format.
Definition at line 155 of file AsmPrinterDwarf.cpp.
References assert(), doesDwarfUseRelocationsAcrossSections(), emitDwarfSymbolReference(), getDwarfOffsetByteSize(), OutStreamer, and S.
Referenced by emitDwarfStringOffset().
emitDwarfStringOffset() [2/2]
void llvm::AsmPrinter::emitDwarfStringOffset (DwarfStringPoolEntryRef S) const inline
Emit the 4-or 8-byte offset of a string from the start of its section.
Definition at line 711 of file AsmPrinter.h.
References emitDwarfStringOffset(), and S.
emitDwarfSymbolReference()
void AsmPrinter::emitDwarfSymbolReference (const MCSymbol * Label, bool ForceOffset = false) const
Emit a reference to a symbol for use in dwarf.
Different object formats represent this in different ways. Some use a relocation others encode the label offset in its section.
Definition at line 132 of file AsmPrinterDwarf.cpp.
References assert(), doesDwarfUseRelocationsAcrossSections(), emitLabelDifference(), getDwarfOffsetByteSize(), isDwarf64(), MAI, llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), and OutStreamer.
Referenced by llvm::DwarfUnit::emitCommonHeader(), emitDwarfStringOffset(), and llvm::DIELocList::emitValue().
emitDwarfUnitLength() [1/2]
MCSymbol * AsmPrinter::emitDwarfUnitLength (const Twine & Prefix, const Twine & Comment) const
Emit a unit length field.
The actual format, DWARF32 or DWARF64, is chosen according to the settings. Return the end symbol generated inside, the caller needs to emit it.
Definition at line 180 of file AsmPrinterDwarf.cpp.
References OutStreamer, and llvm::cl::Prefix.
emitDwarfUnitLength() [2/2]
void AsmPrinter::emitDwarfUnitLength (uint64_t Length, const Twine & Comment) const
Emit a unit length field.
The actual format, DWARF32 or DWARF64, is chosen according to the settings.
Definition at line 175 of file AsmPrinterDwarf.cpp.
References llvm::Length, and OutStreamer.
Referenced by llvm::DwarfUnit::emitCommonHeader().
emitEncodingByte()
void AsmPrinter::emitEncodingByte (unsigned Val, const char * Desc = nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
EmitEncodingByte - Emit a .byte 42 directive that corresponds to an encoding.
If verbose assembly output is enabled, we output comments describing the encoding. Desc is a string saying what the encoding is specifying (e.g. "LSDA").
If verbose assembly output is enabled, we output comments describing the encoding. Desc is an optional string saying what the encoding is specifying (e.g. "LSDA").
Definition at line 90 of file AsmPrinterDwarf.cpp.
References DecodeDWARFEncoding(), isVerbose(), and OutStreamer.
Referenced by llvm::EHStreamer::emitExceptionTable().
emitEndOfAsmFile()
virtual void llvm::AsmPrinter::emitEndOfAsmFile (Module &) inline virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::M68kAsmPrinter, llvm::SystemZAsmPrinter, and llvm::CSKYAsmPrinter.
Definition at line 551 of file AsmPrinter.h.
Referenced by doFinalization().
emitFrameAlloc()
void AsmPrinter::emitFrameAlloc (const MachineInstr & MI)
Definition at line 1322 of file AsmPrinter.cpp.
References llvm::MCConstantExpr::create(), MI, OutContext, and OutStreamer.
Referenced by emitFunctionBody().
emitFunctionBody()
void AsmPrinter::emitFunctionBody ()
This method emits the body and trailer for a function.
EmitFunctionBody - This method emits the body and trailer for a function.
Definition at line 1603 of file AsmPrinter.cpp.
References llvm::MachineOptimizationRemarkEmitter::allowExtraAnalysis(), llvm::ISD::ANNOTATION_LABEL, llvm::ISD::ARITH_FENCE, B, llvm::MachineFunction::back(), BB, llvm::MachineBasicBlock::begin(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), createTempSymbol(), CurrentFnBegin, CurrentFnBeginLocal, CurrentFnSym, CurrentFnSymForSize, DEBUG_TYPE, llvm::ISD::EH_LABEL, llvm::MachineOptimizationRemarkEmitter::emit(), emitBasicBlockEnd(), emitBasicBlockStart(), emitBBAddrMapSection(), emitCFIInstruction(), emitComments(), emitDebugLabelComment(), emitDebugValueComment(), emitFrameAlloc(), emitFunctionBodyEnd(), emitFunctionBodyStart(), emitImplicitDef(), emitInstruction(), emitJumpTableInfo(), emitKill(), emitNops(), emitPatchableFunctionEntries(), emitPCSections(), emitPCSectionsLabel(), emitPseudoProbe(), emitStackSizeSection(), emitStackUsage(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::MachineBasicBlock::empty(), F, llvm::MachineFunction::front(), llvm::MachineDominatorTree::getBase(), GetBlockAddressSymbol(), llvm::MachineBlockFrequencyInfo::getBlockFreqRelativeToEntryBlock(), llvm::MachineBasicBlock::getEndSymbol(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getName(), llvm::MachineFunction::getName(), llvm::TargetInstrInfo::getNop(), llvm::MachineBasicBlock::getNumber(), llvm::MCInst::getOpcode(), llvm::MachineFunction::getSection(), llvm::MachineBasicBlock::getSectionIDNum(), llvm::Function::getSubprogram(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getTargetTriple(), Handlers, llvm::MachineFunction::hasBBLabels(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::MCAsmInfo::hasSubsectionsViaSymbols(), llvm::AArch64CC::HI, I, if(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MCSymbol::isDefined(), llvm::MachineBasicBlock::isEndSection(), isVerbose(), MAI, MBB, MBBSectionRanges, MDT, llvm::ISD::MEMBARRIER, MF, MI, MLI, needFuncLabels(), ORE, OutContext, OutStreamer, llvm::ISD::PSEUDO_PROBE, S, llvm::MachineBasicBlock::sameSection(), llvm::MCInst::setOpcode(), llvm::sort(), llvm::TimePassesIsEnabled, and TM.
Referenced by llvm::R600AsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and runOnMachineFunction().
emitFunctionBodyEnd()
virtual void llvm::AsmPrinter::emitFunctionBodyEnd () inline virtual
Targets can override this to emit stuff after the last basic block in the function.
Reimplemented in llvm::X86AsmPrinter, llvm::MipsAsmPrinter, llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::SystemZAsmPrinter, llvm::M68kAsmPrinter, and llvm::CSKYAsmPrinter.
Definition at line 559 of file AsmPrinter.h.
Referenced by emitFunctionBody().
emitFunctionBodyStart()
virtual void llvm::AsmPrinter::emitFunctionBodyStart () inline virtual
Targets can override this to emit stuff before the first basic block in the function.
Reimplemented in llvm::X86AsmPrinter, llvm::MipsAsmPrinter, llvm::AMDGPUAsmPrinter, llvm::WebAssemblyAsmPrinter, and llvm::M68kAsmPrinter.
Definition at line 555 of file AsmPrinter.h.
Referenced by emitFunctionBody(), and llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart().
emitFunctionDescriptor()
virtual void llvm::AsmPrinter::emitFunctionDescriptor () inline virtual
Definition at line 580 of file AsmPrinter.h.
References llvm_unreachable.
emitFunctionEntryLabel()
void AsmPrinter::emitFunctionEntryLabel () virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
This can be overridden by targets as required to do custom stuff.
Reimplemented in llvm::MipsAsmPrinter, llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 1049 of file AsmPrinter.cpp.
References CurrentFnBeginLocal, CurrentFnSym, llvm::MachineFunction::getFunction(), llvm::MCSymbol::getName(), getSymbolPreferLocal(), llvm::TargetMachine::getTargetTriple(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::Triple::isOSBinFormatELF(), llvm::MCSymbol::isVariable(), MAI, llvm::MCSA_ELF_TypeFunction, MF, OutStreamer, llvm::MCSymbol::redefineIfPossible(), llvm::report_fatal_error(), llvm::ELF::STT_FUNC, and TM.
Referenced by llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), and llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel().
emitGlobalConstant()
void AsmPrinter::emitGlobalConstant (const DataLayout & DL, const Constant * CV, AliasMapTy * AliasList = nullptr)
EmitGlobalConstant - Print a general LLVM constant to the .s file.
Definition at line 3575 of file AsmPrinter.cpp.
References DL, emitGlobalConstantImpl(), getSymbol(), llvm::Value::getType(), llvm::MCAsmInfo::hasSubsectionsViaSymbols(), MAI, OutStreamer, and uint64_t.
Referenced by emitConstantPool(), emitGlobalVariable(), llvm::ARMAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), emitKCFITypeId(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), emitPCSections(), and emitXXStructor().
emitGlobalGOTEquivs()
void AsmPrinter::emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit such globals we previously omitted in EmitGlobalVariable.
Definition at line 1986 of file AsmPrinter.cpp.
References emitGlobalVariable(), getObjFileLowering(), GlobalGOTEquivs, and I.
Referenced by doFinalization().
emitGlobalVariable()
void AsmPrinter::emitGlobalVariable (const GlobalVariable * GV) virtual
Emit the specified global variable to the .s file.
EmitGlobalVariable - Emit the specified global variable to the .s file.
Reimplemented in llvm::NVPTXAsmPrinter, llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, and llvm::WebAssemblyAsmPrinter.
Definition at line 684 of file AsmPrinter.cpp.
References llvm::Triple::aarch64, assert(), llvm::MCConstantExpr::create(), DL, emitAlignment(), emitGlobalConstant(), emitLinkage(), emitSpecialLLVMGlobal(), emitVisibility(), llvm::Module::getDataLayout(), GetExternalSymbolSymbol(), getGVAlignment(), llvm::GlobalVariable::getInitializer(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MCAsmInfo::getLCOMMDirectiveAlignmentType(), llvm::MCAsmInfo::getMemtagAttr(), llvm::MCSymbol::getName(), getObjFileLowering(), llvm::MCContext::getOrCreateSymbol(), llvm::GlobalValue::getParent(), getSymbol(), getSymbolPreferLocal(), llvm::TargetMachine::getTargetTriple(), llvm::MCObjectFileInfo::getTLSBSSSection(), llvm::MCObjectFileInfo::getTLSExtraDataSection(), llvm::GlobalValue::getType(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::getVisibility(), GlobalGOTEquivs, Handlers, llvm::GlobalValue::hasCommonLinkage(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::GlobalVariable::hasInitializer(), llvm::MCAsmInfo::hasMachoTBSSDirective(), llvm::MCAsmInfo::hasMachoZeroFillDirective(), llvm::AArch64CC::HI, llvm::SectionKind::isBSS(), llvm::SectionKind::isBSSLocal(), llvm::SectionKind::isCommon(), llvm::GlobalValue::isDeclaration(), llvm::MCSymbol::isDefined(), llvm::GlobalValue::isTagged(), llvm::SectionKind::isThreadBSS(), llvm::SectionKind::isThreadData(), llvm::SectionKind::isThreadLocal(), llvm::GlobalValue::isThreadLocal(), llvm::MCSymbol::isVariable(), isVerbose(), llvm::MCSection::isVirtualSection(), MAI, llvm::MCSA_ELF_TypeObject, llvm::MCSA_Local, llvm::LCOMM::NoAlignment, OutContext, OutStreamer, llvm::Value::printAsOperand(), llvm::MCSymbol::redefineIfPossible(), llvm::MCContext::reportError(), llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::TimePassesIsEnabled, TM, uint64_t, and llvm::TargetMachine::useEmulatedTLS().
Referenced by doFinalization(), emitGlobalGOTEquivs(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::ARMAsmPrinter::emitGlobalVariable(), and llvm::AMDGPUAsmPrinter::emitGlobalVariable().
emitImplicitDef()
void AsmPrinter::emitImplicitDef (const MachineInstr * MI) const virtual
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
emitImplicitDef - This method emits the specified machine instruction that is an implicit def.
Definition at line 1109 of file AsmPrinter.cpp.
References llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), MF, MI, OS, OutStreamer, and llvm::printReg().
Referenced by emitFunctionBody().
emitInitialRawDwarfLocDirective()
void AsmPrinter::emitInitialRawDwarfLocDirective (const MachineFunction & MF)
Emits inital debug location directive.
Definition at line 402 of file AsmPrinter.cpp.
References assert(), llvm::DwarfDebug::emitInitialLocDirective(), llvm::MachineFunction::getFunction(), llvm::Function::getSubprogram(), MF, and OutStreamer.
emitInlineAsmEnd()
void AsmPrinter::emitInlineAsmEnd (const MCSubtargetInfo & StartInfo, const MCSubtargetInfo * EndInfo) const virtual
Let the target do anything it needs to do after emitting inlineasm.
This callback can be used restore the original mode in case the inlineasm contains directives to switch modes. StartInfo - the original subtarget info before inline asm EndInfo - the final subtarget info after parsing the inline asm, or NULL if the value is unknown.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 517 of file AsmPrinterInlineAsm.cpp.
emitInlineAsmStart()
void AsmPrinter::emitInlineAsmStart () const virtual
Let the target do anything it needs to do before emitting inlineasm.
StartInfo - the subtarget info before parsing inline asm
Definition at line 515 of file AsmPrinterInlineAsm.cpp.
emitInstruction()
virtual void llvm::AsmPrinter::emitInstruction (const MachineInstr *) inline virtual
Targets should implement this to emit instructions.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::M68kAsmPrinter, llvm::AVRAsmPrinter, llvm::SystemZAsmPrinter, llvm::CSKYAsmPrinter, llvm::HexagonAsmPrinter, llvm::LoongArchAsmPrinter, and llvm::R600AsmPrinter.
Definition at line 571 of file AsmPrinter.h.
References llvm_unreachable.
Referenced by emitFunctionBody().
emitInt16()
void AsmPrinter::emitInt16 (int Value) const
Emit a short directive and value.
Definition at line 2843 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by llvm::DwarfUnit::emitCommonHeader().
emitInt32()
void AsmPrinter::emitInt32 (int Value) const
Emit a long directive and value.
Definition at line 2846 of file AsmPrinter.cpp.
References OutStreamer.
emitInt64()
void AsmPrinter::emitInt64 (uint64_t Value) const
Emit a long long directive and value.
Definition at line 2865 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by llvm::DwarfCompileUnit::emitHeader().
emitInt8()
void AsmPrinter::emitInt8 (int Value) const
Emit a byte directive and value.
Definition at line 2840 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by llvm::DwarfUnit::emitCommonHeader(), emitDwarfDIE(), llvm::APByteStreamer::emitInt8(), and llvm::DIEInlineString::emitValue().
emitJumpTableInfo()
void AsmPrinter::emitJumpTableInfo () virtual
Print assembly representations of the jump tables used by the current function to the current output stream.
emit a .set directive for each unique entry.
Reimplemented in llvm::WebAssemblyAsmPrinter.
Definition at line 2535 of file AsmPrinter.cpp.
References Align, llvm::sampleprof::Base, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), DL, llvm::MCAsmInfo::doesSetDirectiveSuppressReloc(), llvm::numbers::e, llvm::MachineJumpTableInfo::EK_Inline, llvm::MachineJumpTableInfo::EK_LabelDifference32, emitAlignment(), F, llvm::MachineFunction::getDataLayout(), llvm::MachineJumpTableInfo::getEntryAlignment(), llvm::MachineJumpTableInfo::getEntryKind(), llvm::MachineFunction::getFunction(), GetJTISymbol(), GetJTSetSymbol(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineBasicBlock::getNumber(), getObjFileLowering(), llvm::TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::TargetLoweringObjectFile::getSectionForJumpTable(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::getSymbol(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::HexagonISD::JT, LHS, MAI, MBB, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT32, MF, OutContext, OutStreamer, llvm::TargetLoweringObjectFile::shouldPutJumpTableInFunctionSection(), and TM.
Referenced by emitFunctionBody().
emitKCFITrapEntry()
void AsmPrinter::emitKCFITrapEntry (const MachineFunction & MF, const MCSymbol * Symbol)
Definition at line 1391 of file AsmPrinter.cpp.
References llvm::MCContext::createLinkerPrivateTempSymbol(), llvm::MCObjectFileInfo::getKCFITrapSection(), getObjFileLowering(), llvm::MachineFunction::getSection(), MF, OutContext, and OutStreamer.
emitKCFITypeId()
void AsmPrinter::emitKCFITypeId (const MachineFunction & MF) virtual
Reimplemented in llvm::X86AsmPrinter.
Definition at line 1408 of file AsmPrinter.cpp.
References emitGlobalConstant(), F, llvm::MachineFunction::getFunction(), and MF.
emitLabelDifference()
void AsmPrinter::emitLabelDifference (const MCSymbol * Hi, const MCSymbol * Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
This implicitly uses .set if it is available.
This implicitly uses .set if it avoids relocations.
Definition at line 2872 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by emitCallSiteOffset(), emitDwarfSymbolReference(), emitPCSections(), and llvm::DIEDelta::emitValue().
emitLabelDifferenceAsULEB128()
void AsmPrinter::emitLabelDifferenceAsULEB128 (const MCSymbol * Hi, const MCSymbol * Lo) const
Emit something like ".uleb128 Hi-Lo".
Definition at line 2878 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by emitBBAddrMapSection(), emitCallSiteOffset(), llvm::EHStreamer::emitExceptionTable(), and emitPCSections().
emitLabelPlusOffset()
void AsmPrinter::emitLabelPlusOffset (const MCSymbol * Label, uint64_t Offset, unsigned Size, bool IsSectionRelative = false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
EmitLabelPlusOffset - Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
This implicitly uses .set if it is available.
Definition at line 2886 of file AsmPrinter.cpp.
References llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), MAI, llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), llvm::Offset, OutContext, and OutStreamer.
Referenced by emitDwarfOffset(), emitLabelReference(), and llvm::DIEEntry::emitValue().
emitLabelReference()
void llvm::AsmPrinter::emitLabelReference (const MCSymbol * Label, unsigned Size, bool IsSectionRelative = false) const inline
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
Definition at line 675 of file AsmPrinter.h.
References emitLabelPlusOffset().
Referenced by llvm::DIELabel::emitValue().
emitLinkage()
void AsmPrinter::emitLinkage (const GlobalValue * GV, MCSymbol * GVSym) const virtual
This emits linkage information about GVSym based on GV, if this is supported by the target.
Definition at line 617 of file AsmPrinter.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::MCAsmInfo::avoidWeakIfComdat(), canBeHidden(), llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::getLinkage(), llvm::GlobalValue::hasComdat(), llvm::MCAsmInfo::hasWeakDefDirective(), llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, MAI, llvm::MCSA_Global, llvm::MCSA_Weak, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, OutStreamer, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
Referenced by doFinalization(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), and llvm::X86AsmPrinter::emitKCFITypeId().
emitMachineConstantPoolValue()
void AsmPrinter::emitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) virtual
Reimplemented in llvm::ARMAsmPrinter, llvm::SystemZAsmPrinter, and llvm::CSKYAsmPrinter.
Definition at line 3595 of file AsmPrinter.cpp.
References llvm_unreachable.
Referenced by emitConstantPool(), and llvm::MipsAsmPrinter::emitInstruction().
emitNops()
void AsmPrinter::emitNops (unsigned N)
Emit N NOP instructions.
Definition at line 3607 of file AsmPrinter.cpp.
References EmitToStreamer(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetInstrInfo::getNop(), llvm::MachineFunction::getSubtarget(), MF, N, llvm::WebAssembly::Nop, and OutStreamer.
Referenced by emitFunctionBody(), llvm::HexagonAsmPrinter::EmitSled(), and llvm::lowerRISCVMachineInstrToMCInst().
emitPatchableFunctionEntries()
void AsmPrinter::emitPatchableFunctionEntries ()
Definition at line 4072 of file AsmPrinter.cpp.
References Align, llvm::MCAsmInfo::binutilsIsAtLeast(), CurrentFnSym, CurrentPatchableFunctionEntrySym, emitAlignment(), F, llvm::MCContext::getELFSection(), llvm::MachineFunction::getFunction(), getPointerSize(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isOSBinFormatELF(), MAI, MF, llvm::MCSection::NonUniqueID, OutContext, OutStreamer, llvm::jitlink::aarch64::PointerSize, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_PROGBITS, TM, and llvm::MCAsmInfo::useIntegratedAssembler().
Referenced by emitFunctionBody().
emitPCSections()
void AsmPrinter::emitPCSections (const MachineFunction & MF)
Emits the PC sections collected from instructions.
Definition at line 1491 of file AsmPrinter.cpp.
References assert(), llvm::sampleprof::Base, llvm::MCContext::createTempSymbol(), DL, emitGlobalConstant(), emitLabelDifference(), emitLabelDifferenceAsULEB128(), emitULEB128(), F, llvm::StringRef::find(), llvm::TargetMachine::getCodeModel(), llvm::MachineFunction::getContext(), llvm::MachineFunction::getFunction(), getFunctionBegin(), getFunctionEnd(), getObjFileLowering(), llvm::MDNode::getOperand(), llvm::MCObjectFileInfo::getPCSection(), getPointerSize(), llvm::MachineFunction::getSection(), llvm::MachineFunction::getTarget(), llvm::CodeModel::Large, llvm::CodeModel::Medium, MF, llvm::StringRef::npos, llvm::RISCVFenceField::O, llvm::MDNode::operands(), OutStreamer, S, llvm::StringRef::substr(), and uint64_t.
Referenced by emitFunctionBody().
emitPCSectionsLabel()
void AsmPrinter::emitPCSectionsLabel (const MachineFunction & MF, const MDNode & MD)
Emits a label as reference for PC sections.
Definition at line 1484 of file AsmPrinter.cpp.
References llvm::MCContext::createTempSymbol(), llvm::MachineFunction::getContext(), MF, OutStreamer, and S.
Referenced by emitFunctionBody().
emitPseudoProbe()
void AsmPrinter::emitPseudoProbe (const MachineInstr & MI)
Definition at line 1415 of file AsmPrinter.cpp.
References llvm::PseudoProbeHandler::emitPseudoProbe(), and MI.
Referenced by emitFunctionBody().
emitRemarksSection()
void AsmPrinter::emitRemarksSection (remarks::RemarkStreamer & RS)
Definition at line 2105 of file AsmPrinter.cpp.
References assert(), llvm::remarks::RemarkStreamer::getFilename(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getRemarksSection(), llvm::remarks::RemarkStreamer::getSerializer(), llvm::sys::fs::make_absolute(), llvm::remarks::RemarkSerializer::metaSerializer(), llvm::remarks::RemarkStreamer::needsSection(), OS, OutContext, and OutStreamer.
Referenced by doFinalization().
emitSLEB128()
void AsmPrinter::emitSLEB128 (int64_t Value, const char * Desc = nullptr) const
Emit the specified signed leb128 value.
EmitSLEB128 - emit the specified signed leb128 value.
Definition at line 2849 of file AsmPrinter.cpp.
References isVerbose(), and OutStreamer.
Referenced by llvm::DIEAbbrev::Emit(), and llvm::APByteStreamer::emitSLEB128().
emitSpecialLLVMGlobal()
bool AsmPrinter::emitSpecialLLVMGlobal (const GlobalVariable * GV)
Check to see if the specified global is a special global used by LLVM.
EmitSpecialLLVMGlobal - Check to see if the specified global is a special global used by LLVM.
If so, emit it and return true, otherwise do nothing and return false.
Definition at line 2676 of file AsmPrinter.cpp.
References assert(), emitXXStructorList(), llvm::Module::getDataLayout(), llvm::GlobalVariable::getInitializer(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::GlobalObject::getSection(), llvm::GlobalValue::hasAppendingLinkage(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalVariable::hasInitializer(), llvm::MCAsmInfo::hasNoDeadStrip(), MAI, and llvm::report_fatal_error().
Referenced by emitGlobalVariable().
emitStackMaps()
void AsmPrinter::emitStackMaps ()
Emit the stack maps.
Definition at line 3939 of file AsmPrinter.cpp.
References assert(), I, MI, llvm::StackMaps::serializeToStackMapSection(), and SM.
Referenced by doFinalization().
emitStackSizeSection()
void AsmPrinter::emitStackSizeSection (const MachineFunction & MF)
Definition at line 1426 of file AsmPrinter.cpp.
References llvm::TargetOptions::EmitStackSizeSection, getCurrentSection(), llvm::MachineFunction::getFrameInfo(), getFunctionBegin(), getObjFileLowering(), llvm::TargetMachine::getProgramPointerSize(), llvm::MachineFrameInfo::getStackSize(), llvm::MCObjectFileInfo::getStackSizesSection(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::getUnsafeStackSize(), llvm::MachineFrameInfo::hasVarSizedObjects(), MF, llvm::TargetMachine::Options, OutStreamer, TM, and uint64_t.
Referenced by emitFunctionBody().
emitStackUsage()
void AsmPrinter::emitStackUsage (const MachineFunction & MF)
Definition at line 1452 of file AsmPrinter.cpp.
References llvm::errs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::Module::getName(), llvm::MachineFunction::getName(), llvm::GlobalValue::getParent(), llvm::MachineFrameInfo::getStackSize(), llvm::Function::getSubprogram(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::getUnsafeStackSize(), llvm::MachineFrameInfo::hasVarSizedObjects(), MF, llvm::sys::fs::OF_Text, llvm::TargetMachine::Options, OutputFilename, llvm::TargetOptions::StackUsageOutput, and uint64_t.
Referenced by emitFunctionBody().
emitStartOfAsmFile()
virtual void llvm::AsmPrinter::emitStartOfAsmFile (Module &) inline virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::AVRAsmPrinter, llvm::M68kAsmPrinter, and llvm::CSKYAsmPrinter.
Definition at line 547 of file AsmPrinter.h.
Referenced by doInitialization().
EmitToStreamer()
void AsmPrinter::EmitToStreamer (MCStreamer & S, const MCInst & Inst)
Definition at line 398 of file AsmPrinter.cpp.
References getSubtargetInfo(), and S.
Referenced by llvm::X86AsmPrinter::emitBasicBlockEnd(), llvm::LoongArchAsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::AVRAsmPrinter::emitInstruction(), llvm::WebAssemblyAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitJumpTableInsts(), emitNops(), llvm::HexagonAsmPrinter::EmitSled(), llvm::CSKYAsmPrinter::EmitToStreamer(), and llvm::ARMAsmPrinter::runOnMachineFunction().
emitTTypeReference()
void AsmPrinter::emitTTypeReference (const GlobalValue * GV, unsigned Encoding) virtual
Emit reference to a ttype global with a specified encoding.
Definition at line 121 of file AsmPrinterDwarf.cpp.
References getObjFileLowering(), GetSizeOfEncodedValue(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), MMI, OutStreamer, and TM.
emitULEB128()
void AsmPrinter::emitULEB128 (uint64_t Value, const char * Desc = nullptr, unsigned PadTo = 0) const
Emit the specified unsigned leb128 value.
Definition at line 2856 of file AsmPrinter.cpp.
References isVerbose(), and OutStreamer.
Referenced by llvm::DIEAbbrev::Emit(), emitCallSiteValue(), emitDwarfAbbrev(), emitDwarfAbbrevs(), emitDwarfDIE(), llvm::EHStreamer::emitExceptionTable(), emitPCSections(), llvm::APByteStreamer::emitULEB128(), llvm::DIEBaseTypeRef::emitValue(), llvm::DIEEntry::emitValue(), and llvm::DIELocList::emitValue().
emitVisibility()
void AsmPrinter::emitVisibility (MCSymbol * Sym, unsigned Visibility, bool IsDefinition = true) const
This emits visibility information about symbol, if this is supported by the target.
Definition at line 3838 of file AsmPrinter.cpp.
References llvm::MCAsmInfo::getHiddenDeclarationVisibilityAttr(), llvm::MCAsmInfo::getHiddenVisibilityAttr(), llvm::MCAsmInfo::getProtectedVisibilityAttr(), llvm::GlobalValue::HiddenVisibility, MAI, llvm::MCSA_Invalid, OutStreamer, and llvm::GlobalValue::ProtectedVisibility.
Referenced by doFinalization(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), and emitGlobalVariable().
emitXRayTable()
void AsmPrinter::emitXRayTable ()
Emit a table with all XRay instrumentation points.
Definition at line 3979 of file AsmPrinter.cpp.
References Align, llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::MCContext::createTempSymbol(), CurrentFnBegin, CurrentFnSym, F, llvm::MCAsmInfo::getCodePointerSize(), llvm::MCContext::getELFSection(), llvm::MachineFunction::getFunction(), llvm::MCContext::getMachOSection(), llvm::SectionKind::getReadOnlyWithRel(), llvm::MachineFunction::getSubtarget(), getSubtargetInfo(), llvm::MCSubtargetInfo::getTargetTriple(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isOSBinFormatMachO(), llvm_unreachable, MAI, MF, llvm::MCSection::NonUniqueID, llvm::TargetMachine::Options, OutContext, OutStreamer, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_PROGBITS, Sleds, TM, and llvm::TargetOptions::XRayOmitFunctionIndex.
Referenced by llvm::HexagonAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), and llvm::X86AsmPrinter::runOnMachineFunction().
emitXXStructor()
virtual void llvm::AsmPrinter::emitXXStructor (const DataLayout & DL, const Constant * CV) inline virtual
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
Reimplemented in llvm::ARMAsmPrinter, and llvm::AVRAsmPrinter.
Definition at line 588 of file AsmPrinter.h.
References DL, and emitGlobalConstant().
Referenced by llvm::AVRAsmPrinter::emitXXStructor(), and emitXXStructorList().
emitXXStructorList()
void AsmPrinter::emitXXStructorList (const DataLayout & DL, const Constant * List, bool IsCtor) virtual
This method emits llvm.global_ctors or llvm.global_dtors list.
EmitXXStructorList - Emit the ctor or dtor list taking into account the init priority.
Definition at line 2758 of file AsmPrinter.cpp.
References DL, emitAlignment(), emitXXStructor(), getObjFileLowering(), llvm::TargetLoweringObjectFile::getStaticCtorSection(), llvm::TargetLoweringObjectFile::getStaticDtorSection(), getSymbol(), llvm::GlobalValue::isDeclarationForLinker(), List, llvm::TargetMachine::Options, OutStreamer, preprocessXXStructorList(), llvm::reverse(), S, TM, and llvm::TargetOptions::UseInitArray.
Referenced by emitSpecialLLVMGlobal().
getAddrLabelSymbol()
MCSymbol* llvm::AsmPrinter::getAddrLabelSymbol (const BasicBlock * BB) inline
Return the symbol to be used for the specified basic block when its address is taken.
This cannot be its normal LBB label because the block may be accessed outside its containing function.
Definition at line 288 of file AsmPrinter.h.
References BB, and getAddrLabelSymbolToEmit().
Referenced by GetBlockAddressSymbol().
getAddrLabelSymbolToEmit()
ArrayRef< MCSymbol * > AsmPrinter::getAddrLabelSymbolToEmit (const BasicBlock * BB)
Return the symbol to be used for the specified basic block when its address is taken.
If other blocks were RAUW'd to this one, we may have to emit them as well, return the whole set.
Definition at line 257 of file AsmPrinter.cpp.
References BB, and OutContext.
Referenced by emitBasicBlockStart(), and getAddrLabelSymbol().
getAnalysisUsage()
void AsmPrinter::getAnalysisUsage (AnalysisUsage & AU) const override virtual
Record analysis usage.
Reimplemented from llvm::Pass.
Reimplemented in llvm::NVPTXAsmPrinter, and llvm::AMDGPUAsmPrinter.
Definition at line 420 of file AsmPrinter.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
Referenced by llvm::AMDGPUAsmPrinter::getAnalysisUsage(), and llvm::NVPTXAsmPrinter::getAnalysisUsage().
GetBlockAddressSymbol() [1/2]
MCSymbol * AsmPrinter::GetBlockAddressSymbol (const BasicBlock * BB) const
Definition at line 3626 of file AsmPrinter.cpp.
References BB, and getAddrLabelSymbol().
GetBlockAddressSymbol() [2/2]
MCSymbol * AsmPrinter::GetBlockAddressSymbol (const BlockAddress * BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
Definition at line 3621 of file AsmPrinter.cpp.
References getAddrLabelSymbol(), and llvm::BlockAddress::getBasicBlock().
Referenced by emitFunctionBody(), EmitInlineAsmStr(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::LanaiMCInstLower::GetBlockAddressSymbol(), llvm::MSP430MCInstLower::GetBlockAddressSymbol(), llvm::SystemZMCInstLower::getExpr(), getMCSymbolForTOCPseudoMO(), llvm::HexagonLowerToMC(), lowerConstant(), llvm::AVRMCInstLower::lowerInstruction(), llvm::lowerLoongArchMachineOperandToMCOperand(), llvm::CSKYMCInstLower::lowerOperand(), llvm::AArch64MCInstLower::lowerOperand(), LowerOperand(), llvm::M68kMCInstLower::LowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineOperandToMCOperand(), llvm::lowerRISCVMachineOperandToMCOperand(), LowerSymbolOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), and llvm::MipsAsmPrinter::printOperand().
GetCPISymbol()
MCSymbol * AsmPrinter::GetCPISymbol (unsigned CPID) const virtual
Return the symbol for the specified constant pool entry.
GetCPISymbol - Return the symbol for the specified constant pool entry.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 3631 of file AsmPrinter.cpp.
References llvm::MachineConstantPoolEntry::Alignment, llvm::MachineConstantPoolEntry::ConstVal, DL, llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), getDataLayout(), llvm::MachineFunction::getDataLayout(), getFunctionNumber(), getObjFileLowering(), llvm::MCContext::getOrCreateSymbol(), llvm::MachineConstantPoolEntry::getSectionKind(), getSubtargetInfo(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::MCSA_Global, MF, OutContext, OutStreamer, S, and llvm::MachineConstantPoolEntry::Val.
Referenced by emitConstantPool(), llvm::MipsAsmPrinter::emitInstruction(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZMCInstLower::getExpr(), getMCSymbolForTOCPseudoMO(), llvm::HexagonLowerToMC(), llvm::AVRMCInstLower::lowerInstruction(), llvm::lowerLoongArchMachineOperandToMCOperand(), llvm::CSKYMCInstLower::lowerOperand(), llvm::AArch64MCInstLower::lowerOperand(), LowerOperand(), llvm::M68kMCInstLower::LowerOperand(), llvm::LowerPPCMachineOperandToMCOperand(), llvm::lowerRISCVMachineOperandToMCOperand(), LowerSymbolOperand(), llvm::HexagonAsmPrinter::printOperand(), and smallData().
getCurrentSection()
const MCSection * AsmPrinter::getCurrentSection () const
Return the current section we are emitting to.
getCurrentSection() - Return the current section we are emitting to.
Definition at line 416 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by emitAlignment(), and emitStackSizeSection().
getDataLayout()
const DataLayout & AsmPrinter::getDataLayout () const
Return information about data layout.
Definition at line 383 of file AsmPrinter.cpp.
References llvm::Module::getDataLayout(), llvm::MachineModuleInfo::getModule(), and MMI.
Referenced by llvm::DwarfExpression::addConstantFP(), llvm::DwarfUnit::addConstantValue(), llvm::DwarfCompileUnit::addLocationAttribute(), emitConstantPool(), llvm::X86AsmPrinter::emitEndOfAsmFile(), emitGlobalConstantFP(), emitGlobalConstantLargeInt(), llvm::ARMAsmPrinter::emitInstruction(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::WasmException::endModule(), llvm::DwarfCFIException::endModule(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), llvm::ARMAsmPrinter::GetCPISymbol(), GetCPISymbol(), GetExternalSymbolSymbol(), GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), GetSymbolFromOperand(), lowerConstant(), and llvm::MipsAsmPrinter::printOperand().
getDwarfDebug() [1/2]
DwarfDebug* llvm::AsmPrinter::getDwarfDebug () inline
Definition at line 249 of file AsmPrinter.h.
Referenced by llvm::DIELocList::emitValue().
getDwarfDebug() [2/2]
DwarfDebug* llvm::AsmPrinter::getDwarfDebug () const inline
Definition at line 250 of file AsmPrinter.h.
getDwarfFormParams()
dwarf::FormParams AsmPrinter::getDwarfFormParams () const
Returns information about the byte size of DW_FORM values.
Definition at line 4124 of file AsmPrinter.cpp.
References doesDwarfUseRelocationsAcrossSections(), getDwarfVersion(), getPointerSize(), and OutStreamer.
Referenced by llvm::DwarfUnit::addBlock(), llvm::DwarfFile::computeSizeAndOffset(), llvm::DIEExpr::emitValue(), llvm::DIELabel::emitValue(), llvm::DIEDelta::emitValue(), and llvm::DIEEntry::emitValue().
getDwarfOffsetByteSize()
unsigned int AsmPrinter::getDwarfOffsetByteSize () const
Returns 4 for DWARF32 and 8 for DWARF64.
Definition at line 4119 of file AsmPrinter.cpp.
References llvm::dwarf::getDwarfOffsetByteSize(), and OutStreamer.
Referenced by emitDwarfLengthOrOffset(), emitDwarfOffset(), emitDwarfStringOffset(), emitDwarfSymbolReference(), llvm::DwarfUnit::getHeaderSize(), and llvm::DwarfTypeUnit::getHeaderSize().
getDwarfVersion()
uint16_t AsmPrinter::getDwarfVersion () const
Definition at line 4107 of file AsmPrinter.cpp.
References OutStreamer.
Referenced by llvm::DIEAbbrev::Emit(), getDwarfFormParams(), and llvm::DwarfDebug::getDwarfSectionOffsetForm().
GetExternalSymbolSymbol()
MCSymbol * AsmPrinter::GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
Definition at line 3678 of file AsmPrinter.cpp.
References getDataLayout(), llvm::Mangler::getNameWithPrefix(), llvm::MCContext::getOrCreateSymbol(), and OutContext.
Referenced by llvm::X86AsmPrinter::emitEndOfAsmFile(), emitGlobalVariable(), llvm::ARMAsmPrinter::emitInstruction(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::WasmException::endModule(), llvm::SystemZMCInstLower::getExpr(), llvm::MSP430MCInstLower::GetExternalSymbolSymbol(), llvm::BPFMCInstLower::GetExternalSymbolSymbol(), llvm::LanaiMCInstLower::GetExternalSymbolSymbol(), llvm::AArch64MCInstLower::GetExternalSymbolSymbol(), llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction(), llvm::WebAssemblyAsmPrinter::getOrCreateWasmSymbol(), llvm::HexagonLowerToMC(), llvm::AVRMCInstLower::lowerInstruction(), llvm::lowerLoongArchMachineOperandToMCOperand(), llvm::CSKYMCInstLower::lowerOperand(), LowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::lowerRISCVMachineOperandToMCOperand(), LowerSymbolOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::AVRAsmPrinter::printOperand(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIEImpl().
getFunctionBegin()
MCSymbol* llvm::AsmPrinter::getFunctionBegin () const inline
Definition at line 278 of file AsmPrinter.h.
References CurrentFnBegin.
Referenced by llvm::BTFDebug::beginFunctionImpl(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::BTFDebug::beginInstruction(), llvm::EHStreamer::computeCallSiteTable(), emitBBAddrMapSection(), emitPCSections(), and emitStackSizeSection().
getFunctionCFISectionType() [1/2]
AsmPrinter::CFISection AsmPrinter::getFunctionCFISectionType (const Function & F) const
Get the CFISection type for a function.
Definition at line 1267 of file AsmPrinter.cpp.
References Debug, llvm::DwarfCFI, EH, F, llvm::TargetOptions::ForceDwarfFrameSection, llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineModuleInfo::hasDebugInfo(), MAI, MMI, None, llvm::TargetMachine::Options, and TM.
Referenced by llvm::DwarfCFIException::beginFunction(), llvm::ARMException::beginFunction(), doInitialization(), emitCFIInstruction(), and getFunctionCFISectionType().
getFunctionCFISectionType() [2/2]
AsmPrinter::CFISection AsmPrinter::getFunctionCFISectionType (const MachineFunction & MF) const
Get the CFISection type for a function.
Definition at line 1283 of file AsmPrinter.cpp.
References llvm::MachineFunction::getFunction(), getFunctionCFISectionType(), and MF.
getFunctionEnd()
MCSymbol* llvm::AsmPrinter::getFunctionEnd () const inline
Definition at line 279 of file AsmPrinter.h.
Referenced by emitPCSections(), and llvm::CodeViewDebug::endFunctionImpl().
getFunctionFrameSymbol()
virtual const MCSymbol* llvm::AsmPrinter::getFunctionFrameSymbol () const inline virtual
Return symbol for the function pseudo stack if the stack frame is not a register based.
Reimplemented in llvm::NVPTXAsmPrinter.
Definition at line 276 of file AsmPrinter.h.
getFunctionNumber()
unsigned AsmPrinter::getFunctionNumber () const
Return a unique ID for the current function.
getFunctionNumber - Return a unique ID for the current function.
Definition at line 375 of file AsmPrinter.cpp.
References llvm::MachineFunction::getFunctionNumber(), and MF.
Referenced by emitBasicBlockLoopComments(), llvm::AMDGPUAsmPrinter::emitBasicBlockStart(), llvm::EHStreamer::emitExceptionTable(), llvm::ARMAsmPrinter::emitInstruction(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), llvm::LanaiMCInstLower::GetConstantPoolIndexSymbol(), llvm::ARMAsmPrinter::GetCPISymbol(), GetCPISymbol(), llvm::NVPTXAsmPrinter::getFunctionFrameSymbol(), GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), llvm::LanaiMCInstLower::GetJumpTableSymbol(), llvm::MipsAsmPrinter::printOperand(), and PrintSpecial().
getGVAlignment()
Align AsmPrinter::getGVAlignment (const GlobalObject * GV, const DataLayout & DL, Align InAlign = Align(1)) static
Return the alignment for the specified GV.
getGVAlignment - Return the alignment to use for the specified global value.
This rounds up to the preferred alignment if possible and legal.
Definition at line 332 of file AsmPrinter.cpp.
References assert(), DL, llvm::GlobalObject::getAlign(), and llvm::GlobalObject::hasSection().
Referenced by emitAlignment(), and emitGlobalVariable().
getISAEncoding()
virtual unsigned llvm::AsmPrinter::getISAEncoding () inline virtual
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 739 of file AsmPrinter.h.
Referenced by llvm::DwarfUnit::applySubprogramAttributes().
GetJTISymbol()
MCSymbol * AsmPrinter::GetJTISymbol (unsigned JTID, bool isLinkerPrivate = false) const
Return the symbol for the specified jump table entry.
GetJTISymbol - Return the symbol for the specified jump table entry.
Definition at line 3659 of file AsmPrinter.cpp.
References llvm::MachineFunction::getJTISymbol(), MF, and OutContext.
Referenced by emitJumpTableInfo(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZMCInstLower::getExpr(), getMCSymbolForTOCPseudoMO(), llvm::HexagonLowerToMC(), llvm::AVRMCInstLower::lowerInstruction(), llvm::lowerLoongArchMachineOperandToMCOperand(), llvm::CSKYMCInstLower::lowerOperand(), llvm::AArch64MCInstLower::lowerOperand(), LowerOperand(), llvm::M68kMCInstLower::LowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineOperandToMCOperand(), llvm::lowerRISCVMachineOperandToMCOperand(), and smallData().
GetJTSetSymbol()
MCSymbol * AsmPrinter::GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
GetJTSetSymbol - Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
Definition at line 3665 of file AsmPrinter.cpp.
References DL, getDataLayout(), getFunctionNumber(), llvm::MCContext::getOrCreateSymbol(), and OutContext.
Referenced by emitJumpTableInfo().
getMBBExceptionSym()
MCSymbol * AsmPrinter::getMBBExceptionSym (const MachineBasicBlock & MBB)
Definition at line 2384 of file AsmPrinter.cpp.
References createTempSymbol(), llvm::MachineBasicBlock::getSectionIDNum(), and MBB.
Referenced by llvm::DwarfCFIException::beginBasicBlockSection(), llvm::EHStreamer::computeCallSiteTable(), llvm::EHStreamer::emitExceptionTable(), and llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
getModuleCFISectionType()
CFISection llvm::AsmPrinter::getModuleCFISectionType () const inline
Get the CFISection type for the module.
Definition at line 446 of file AsmPrinter.h.
Referenced by llvm::DwarfCFIException::beginBasicBlockSection(), and llvm::ARMException::beginFunction().
getNameWithPrefix()
void AsmPrinter::getNameWithPrefix (SmallVectorImpl< char > & Name, const GlobalValue * GV) const
Definition at line 657 of file AsmPrinter.cpp.
References llvm::TargetMachine::getNameWithPrefix(), getObjFileLowering(), and TM.
Referenced by llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::M68kMCInstLower::GetSymbolFromOperand(), and AMDGPUMCInstLower::lowerOperand().
getObjFileLowering()
const TargetLoweringObjectFile & AsmPrinter::getObjFileLowering () const
Return information about object file lowering.
Definition at line 379 of file AsmPrinter.cpp.
References llvm::TargetMachine::getObjFileLowering(), and TM.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), llvm::DwarfDebug::addDwarfTypeUnitType(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfUnit::addRnglistsBase(), llvm::DwarfCompileUnit::addScopeRangeList(), llvm::DwarfUnit::addStringOffsetsStart(), llvm::DwarfCompileUnit::applyStmtList(), llvm::DwarfCFIException::beginBasicBlockSection(), llvm::WinException::beginFunclet(), llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::CodeViewDebug::beginModule(), computeGlobalGOTEquivs(), llvm::AVRAsmPrinter::doFinalization(), llvm::AMDGPUAsmPrinter::doFinalization(), doFinalization(), doInitialization(), emitBasicBlockStart(), emitBBAddrMapSection(), llvm::DwarfUnit::emitCommonHeader(), emitConstantPool(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), llvm::SystemZAsmPrinter::emitFunctionBodyEnd(), emitGlobalConstantImpl(), emitGlobalGOTEquivs(), emitGlobalVariable(), emitJumpTableInfo(), emitKCFITrapEntry(), emitPCSections(), emitStackSizeSection(), llvm::X86AsmPrinter::emitStartOfAsmFile(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), emitTTypeReference(), emitXXStructorList(), llvm::DwarfCFIException::endModule(), GetCPISymbol(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), getNameWithPrefix(), getSymbolWithGlobalValueBase(), handleIndirectSymViaGOTPCRel(), llvm::DwarfCompileUnit::initStmtList(), lowerConstant(), llvm::R600AsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and SetupMachineFunction().
getPointerSize()
unsigned AsmPrinter::getPointerSize () const
Return the pointer size from the TargetMachine.
Definition at line 389 of file AsmPrinter.cpp.
References llvm::TargetMachine::getPointerSize(), and TM.
Referenced by emitBBAddrMapSection(), emitPatchableFunctionEntries(), emitPCSections(), and getDwarfFormParams().
GetSizeOfEncodedValue()
unsigned AsmPrinter::GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
GetSizeOfEncodedValue - Return the size of the encoding in bytes.
Definition at line 103 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_omit, llvm::dwarf::DW_EH_PE_udata2, llvm::dwarf::DW_EH_PE_udata4, llvm::dwarf::DW_EH_PE_udata8, llvm::MachineFunction::getDataLayout(), llvm::DataLayout::getPointerSize(), llvm_unreachable, and MF.
Referenced by emitCallSiteOffset(), emitCallSiteValue(), llvm::EHStreamer::emitExceptionTable(), and emitTTypeReference().
getSubtargetInfo()
const MCSubtargetInfo & AsmPrinter::getSubtargetInfo () const
Return information about subtarget.
Definition at line 393 of file AsmPrinter.cpp.
References assert(), llvm::MachineFunction::getSubtarget(), and MF.
Referenced by emitAlignment(), llvm::X86AsmPrinter::emitBasicBlockEnd(), llvm::R600AsmPrinter::emitInstruction(), llvm::LoongArchAsmPrinter::emitInstruction(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::CSKYAsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::M68kAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), EmitToStreamer(), emitXRayTable(), GetCPISymbol(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIEImpl().
getSymbol()
MCSymbol * AsmPrinter::getSymbol (const GlobalValue * GV) const
Definition at line 662 of file AsmPrinter.cpp.
References llvm::TargetMachine::getSymbol(), and TM.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), computeGlobalGOTEquivs(), doFinalization(), llvm::WebAssemblyAsmPrinter::emitDecls(), llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), emitGlobalAliasInline(), emitGlobalConstant(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), emitXXStructorList(), llvm::ARMException::endFunction(), llvm::WinCFGuard::endModule(), llvm::DwarfCFIException::endModule(), llvm::WinException::endModule(), llvm::SystemZMCInstLower::getExpr(), llvm::MSP430MCInstLower::GetGlobalAddressSymbol(), llvm::BPFMCInstLower::GetGlobalAddressSymbol(), llvm::LanaiMCInstLower::GetGlobalAddressSymbol(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction(), getMCSymbolForTOCPseudoMO(), handleIndirectSymViaGOTPCRel(), llvm::HexagonLowerToMC(), llvm::AVRAsmPrinter::lowerConstant(), lowerConstant(), llvm::AVRMCInstLower::lowerInstruction(), llvm::CSKYMCInstLower::lowerOperand(), LowerOperand(), LowerSymbolOperand(), llvm::AVRAsmPrinter::printOperand(), SetupMachineFunction(), and smallData().
getSymbolPreferLocal()
MCSymbol * AsmPrinter::getSymbolPreferLocal (const GlobalValue & GV) const
Similar to getSymbol() but preferred for references.
On ELF, this uses a local symbol if a reference to GV is guaranteed to be resolved to the definition in the same module.
Definition at line 666 of file AsmPrinter.cpp.
References llvm::GlobalValue::canBenefitFromLocalAlias(), llvm::PIELevel::Default, llvm::GlobalValue::getParent(), llvm::TargetMachine::getRelocationModel(), llvm::TargetMachine::getSymbol(), getSymbolWithGlobalValueBase(), llvm::TargetMachine::getTargetTriple(), llvm::GlobalValue::isDSOLocal(), llvm::Triple::isOSBinFormatELF(), M, llvm::Reloc::Static, and TM.
Referenced by emitFunctionEntryLabel(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::M68kMCInstLower::GetSymbolFromOperand(), llvm::lowerLoongArchMachineOperandToMCOperand(), llvm::lowerRISCVMachineOperandToMCOperand(), and PrintSymbolOperand().
getSymbolWithGlobalValueBase()
MCSymbol * AsmPrinter::getSymbolWithGlobalValueBase (const GlobalValue * GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
Definition at line 3672 of file AsmPrinter.cpp.
References getObjFileLowering(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), and TM.
Referenced by getSymbolPreferLocal().
getUnitLengthFieldByteSize()
unsigned int AsmPrinter::getUnitLengthFieldByteSize () const
Returns 4 for DWARF32 and 12 for DWARF64.
Definition at line 4130 of file AsmPrinter.cpp.
References llvm::dwarf::getUnitLengthFieldByteSize(), and OutStreamer.
Referenced by llvm::DwarfFile::computeSizeAndOffsetsForUnit(), and llvm::DwarfCompileUnit::getLength().
isBlockOnlyReachableByFallthrough()
bool AsmPrinter::isBlockOnlyReachableByFallthrough (const MachineBasicBlock * MBB) const virtual
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
Reimplemented in llvm::MipsAsmPrinter, llvm::AMDGPUAsmPrinter, and llvm::HexagonAsmPrinter.
Definition at line 3878 of file AsmPrinter.cpp.
References llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::isEHPad(), llvm::MachineBasicBlock::isLayoutSuccessor(), MBB, MI, OP, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::pred_size(), and llvm::MachineBasicBlock::terminators().
Referenced by llvm::HexagonAsmPrinter::isBlockOnlyReachableByFallthrough(), and llvm::AMDGPUAsmPrinter::isBlockOnlyReachableByFallthrough().
isDwarf64()
bool AsmPrinter::isDwarf64 () const
Definition at line 4115 of file AsmPrinter.cpp.
References llvm::dwarf::DWARF64, and OutStreamer.
Referenced by llvm::DwarfFile::computeSizeAndOffsets(), emitDwarfLengthOrOffset(), emitDwarfSymbolReference(), and llvm::DwarfDebug::getDwarfSectionOffsetForm().
isPositionIndependent()
bool AsmPrinter::isPositionIndependent () const
Definition at line 370 of file AsmPrinter.cpp.
References llvm::TargetMachine::isPositionIndependent(), and TM.
Referenced by llvm::ARMAsmPrinter::emitJumpTableAddrs(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::WasmException::endModule(), and llvm::WebAssemblyAsmPrinter::getOrCreateWasmSymbol().
isVerbose()
bool llvm::AsmPrinter::isVerbose () const inline
Return true if assembly output should contain comments.
Definition at line 269 of file AsmPrinter.h.
Referenced by emitBasicBlockStart(), emitDwarfDIE(), emitEncodingByte(), emitFunctionBody(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitInstruction(), emitSLEB128(), emitULEB128(), llvm::R600AsmPrinter::runOnMachineFunction(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
lowerConstant()
const MCExpr * AsmPrinter::lowerConstant (const Constant * CV) virtual
Lower the specified LLVM Constant to an MCExpr.
Reimplemented in llvm::AMDGPUAsmPrinter, llvm::AVRAsmPrinter, and llvm::R600AsmPrinter.
Definition at line 2934 of file AsmPrinter.cpp.
References llvm::MCID::Add, llvm::sampleprof::Base, llvm::ConstantFoldConstant(), llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), DL, GetBlockAddressSymbol(), getDataLayout(), llvm::MachineFunction::getFunction(), llvm::ConstantExpr::getIntegerCast(), getObjFileLowering(), llvm::GlobalValue::getParent(), llvm::APInt::getSExtValue(), getSymbol(), llvm::Value::getType(), llvm::IsConstantOffsetFromGlobal(), llvm::TargetMachine::isNoopAddrSpaceCast(), llvm::Constant::isNullValue(), LHS, llvm_unreachable, llvm::TargetLoweringObjectFile::lowerDSOLocalEquivalent(), llvm::TargetLoweringObjectFile::lowerRelativeReference(), MF, NC, llvm::Offset, OS, OutContext, llvm::report_fatal_error(), RHS, S, and TM.
Referenced by llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), emitGlobalConstantImpl(), llvm::R600AsmPrinter::lowerConstant(), llvm::AVRAsmPrinter::lowerConstant(), and llvm::AMDGPUAsmPrinter::lowerConstant().
needsCFIForDebug()
bool AsmPrinter::needsCFIForDebug () const
Since emitting CFI unwind information is entangled with supporting the exceptions, this returns true for platforms which use CFI unwind information for debugging purpose when MCAsmInfo::ExceptionsType == ExceptionHandling::None.
Definition at line 1291 of file AsmPrinter.cpp.
References Debug, llvm::MCAsmInfo::doesUseCFIForDebug(), llvm::MCAsmInfo::getExceptionHandlingType(), MAI, and llvm::None.
Referenced by llvm::DwarfCFIException::beginFunction(), doInitialization(), and emitCFIInstruction().
needsSEHMoves()
bool AsmPrinter::needsSEHMoves ()
Definition at line 1287 of file AsmPrinter.cpp.
References llvm::MachineFunction::getFunction(), MAI, MF, llvm::Function::needsUnwindTableEntry(), and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by llvm::WinException::beginFunction().
preprocessXXStructorList()
void AsmPrinter::preprocessXXStructorList (const DataLayout & DL, const Constant * List, SmallVector< Structor, 8 > & Structors)
This method gathers an array of Structors and then sorts them out by Priority.
Parameters
List The initializer of llvm.global_ctors or llvm.global_dtors array.
[out] Structors Sorted Structor structs by Priority.
Definition at line 2721 of file AsmPrinter.cpp.
References llvm::ConstantInt::getLimitedValue(), llvm::TargetMachine::getTargetTriple(), llvm::Triple::isOSAIX(), List, llvm::RISCVFenceField::O, llvm::AsmPrinter::Structor::Priority, llvm::report_fatal_error(), S, llvm::stable_sort(), and TM.
Referenced by emitXXStructorList().
PrintAsmMemoryOperand()
bool AsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & OS) virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented in llvm::MipsAsmPrinter, llvm::ARMAsmPrinter, llvm::AVRAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::HexagonAsmPrinter, llvm::CSKYAsmPrinter, llvm::SystemZAsmPrinter, llvm::LoongArchAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 509 of file AsmPrinterInlineAsm.cpp.
Referenced by EmitInlineAsmStr(), llvm::CSKYAsmPrinter::PrintAsmMemoryOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmMemoryOperand(), and PrintAsmOperand().
PrintAsmOperand()
bool AsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & O) virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate for machine specific ExtraCodes or when the arch-independent handling would be too complex otherwise.
Reimplemented in llvm::ARMAsmPrinter, llvm::AVRAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::HexagonAsmPrinter, llvm::CSKYAsmPrinter, llvm::SystemZAsmPrinter, llvm::M68kAsmPrinter, llvm::LoongArchAsmPrinter, llvm::MipsAsmPrinter, llvm::X86AsmPrinter, and llvm::AMDGPUAsmPrinter.
Definition at line 467 of file AsmPrinterInlineAsm.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), MI, llvm::RISCVFenceField::O, PrintAsmMemoryOperand(), and PrintSymbolOperand().
Referenced by EmitInlineAsmStr(), llvm::LoongArchAsmPrinter::PrintAsmOperand(), llvm::AVRAsmPrinter::PrintAsmOperand(), llvm::M68kAsmPrinter::PrintAsmOperand(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::AMDGPUAsmPrinter::PrintAsmOperand(), llvm::X86AsmPrinter::PrintAsmOperand(), and llvm::MipsAsmPrinter::PrintAsmOperand().
printOffset()
void AsmPrinter::printOffset (int64_t Offset, raw_ostream & OS) const
This is just convenient handler for printing offsets.
Definition at line 3600 of file AsmPrinter.cpp.
References llvm::Offset, and OS.
Referenced by llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintSymbolOperand(), and PrintSymbolOperand().
PrintSpecial()
void AsmPrinter::PrintSpecial (const MachineInstr * MI, raw_ostream & OS, StringRef Code) const virtual
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
PrintSpecial - Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
This can be useful for portably encoding the comment character or other bits of target-specific knowledge into the asmstrings. The syntax used is ${:comment}. Targets can override this to add support for their own strange codes.
Definition at line 430 of file AsmPrinterInlineAsm.cpp.
References DL, llvm::MCAsmInfo::getCommentString(), llvm::MachineFunction::getDataLayout(), getFunctionNumber(), MAI, MF, MI, llvm::AMDGPU::SendMsg::Msg, OS, and llvm::report_fatal_error().
Referenced by EmitInlineAsmStr().
PrintSymbolOperand()
void AsmPrinter::PrintSymbolOperand (const MachineOperand & MO, raw_ostream & OS) virtual
Print the MachineOperand as a symbol.
Targets with complex handling of symbol references should override the base implementation.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 457 of file AsmPrinterInlineAsm.cpp.
References assert(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getOffset(), getSymbolPreferLocal(), llvm::MachineOperand::isGlobal(), MAI, OS, llvm::MCSymbol::print(), and printOffset().
Referenced by llvm::LoongArchAsmPrinter::PrintAsmOperand(), llvm::AVRAsmPrinter::PrintAsmOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), PrintAsmOperand(), llvm::HexagonAsmPrinter::printOperand(), and llvm::MipsAsmPrinter::printOperand().
recordSled()
void AsmPrinter::recordSled (MCSymbol * Sled, const MachineInstr & MI, SledKind Kind, uint8_t Version = 0)
Definition at line 4059 of file AsmPrinter.cpp.
References CurrentFnSym, F, FUNCTION_ENTER, LOG_ARGS_ENTER, MI, Sleds, and llvm::IndexedInstrProf::Version.
Referenced by llvm::HexagonAsmPrinter::EmitSled().
runOnMachineFunction()
bool llvm::AsmPrinter::runOnMachineFunction (MachineFunction & MF) inline override virtual
Emit the specified function out to the OutStreamer.
Implements llvm::MachineFunctionPass.
Reimplemented in llvm::X86AsmPrinter, llvm::MipsAsmPrinter, llvm::AMDGPUAsmPrinter, llvm::CSKYAsmPrinter, llvm::M68kAsmPrinter, llvm::WebAssemblyAsmPrinter, llvm::LoongArchAsmPrinter, llvm::R600AsmPrinter, llvm::HexagonAsmPrinter, llvm::NVPTXAsmPrinter, and llvm::ARMAsmPrinter.
Definition at line 399 of file AsmPrinter.h.
References emitFunctionBody(), MF, and SetupMachineFunction().
Referenced by llvm::LoongArchAsmPrinter::runOnMachineFunction(), llvm::HexagonAsmPrinter::runOnMachineFunction(), llvm::WebAssemblyAsmPrinter::runOnMachineFunction(), llvm::M68kAsmPrinter::runOnMachineFunction(), llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), and llvm::NVPTXAsmPrinter::runOnMachineFunction().
setDwarfUsesRelocationsAcrossSections()
void llvm::AsmPrinter::setDwarfUsesRelocationsAcrossSections (bool Enable) inline
Definition at line 338 of file AsmPrinter.h.
References Enable.
setDwarfVersion()
void AsmPrinter::setDwarfVersion (uint16_t Version)
Definition at line 4111 of file AsmPrinter.cpp.
References OutStreamer, and llvm::IndexedInstrProf::Version.
SetupMachineFunction()
void AsmPrinter::SetupMachineFunction (MachineFunction & MF) virtual
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
Definition at line 2391 of file AsmPrinter.cpp.
References assert(), createTempSymbol(), CurrentFnBegin, CurrentFnBeginLocal, CurrentFnDescSym, CurrentFnSym, CurrentFnSymForSize, llvm::TargetOptions::EmitStackSizeSection, F, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::TargetLoweringObjectFile::getFunctionEntryPointSymbol(), getObjFileLowering(), getSymbol(), llvm::MachineFunction::getTarget(), llvm::TargetMachine::getTargetTriple(), llvm::MachineFunction::hasBBLabels(), llvm::Triple::isOSAIX(), MAI, MBBSectionRanges, MF, needFuncLabels(), llvm::MCAsmInfo::needsFunctionDescriptors(), llvm::MCAsmInfo::needsLocalForSize(), llvm::MachineFrameInfo::needsSplitStackProlog(), llvm::TargetMachine::Options, ORE, llvm::MachineFunction::shouldSplitStack(), and TM.
Referenced by llvm::R600AsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and runOnMachineFunction().
shouldEmitWeakSwiftAsyncExtendedFramePointerFlags()
virtual bool llvm::AsmPrinter::shouldEmitWeakSwiftAsyncExtendedFramePointerFlags () const inline protected virtual
Reimplemented in llvm::X86AsmPrinter.
Definition at line 879 of file AsmPrinter.h.
Referenced by doFinalization().
takeDeletedSymbolsForFunction()
void AsmPrinter::takeDeletedSymbolsForFunction (const Function * F, std::vector< MCSymbol * > & Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
This prevents emitting a reference to a symbol that has no definition.
Definition at line 265 of file AsmPrinter.cpp.
References F.
Member Data Documentation
CurrentFnBegin
MCSymbol* llvm::AsmPrinter::CurrentFnBegin = nullptr protected
Definition at line 200 of file AsmPrinter.h.
Referenced by emitFunctionBody(), llvm::X86AsmPrinter::emitInstruction(), emitXRayTable(), getFunctionBegin(), and SetupMachineFunction().
CurrentFnBeginLocal
MCSymbol* llvm::AsmPrinter::CurrentFnBeginLocal = nullptr protected
For dso_local functions, the current $local alias for the function.
Definition at line 203 of file AsmPrinter.h.
Referenced by emitFunctionBody(), emitFunctionEntryLabel(), and SetupMachineFunction().
CurrentFnDescSym
MCSymbol* llvm::AsmPrinter::CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
This is created at the beginning of each call to SetupMachineFunction().
Definition at line 125 of file AsmPrinter.h.
Referenced by SetupMachineFunction().
CurrentFnSym
MCSymbol* llvm::AsmPrinter::CurrentFnSym = nullptr
The symbol for the current function.
This is recalculated at the beginning of each call to runOnMachineFunction().
Definition at line 121 of file AsmPrinter.h.
Referenced by llvm::WinException::beginFunction(), llvm::EHStreamer::emitExceptionTable(), emitFunctionBody(), llvm::MipsAsmPrinter::emitFunctionBodyEnd(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::X86AsmPrinter::emitFunctionBodyStart(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), llvm::MipsAsmPrinter::emitFunctionEntryLabel(), emitFunctionEntryLabel(), emitPatchableFunctionEntries(), llvm::PseudoProbeHandler::emitPseudoProbe(), emitXRayTable(), llvm::FaultMaps::recordFaultingOp(), recordSled(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and SetupMachineFunction().
CurrentFnSymForSize
MCSymbol* llvm::AsmPrinter::CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
using the .size directive). By default, this is equal to CurrentFnSym.
Definition at line 130 of file AsmPrinter.h.
Referenced by emitFunctionBody(), llvm::FaultMaps::recordFaultingOp(), and SetupMachineFunction().
CurrentPatchableFunctionEntrySym
MCSymbol* llvm::AsmPrinter::CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
Definition at line 117 of file AsmPrinter.h.
Referenced by llvm::X86AsmPrinter::emitInstruction(), and emitPatchableFunctionEntries().
GlobalGOTEquivs
MapVector<const MCSymbol *, GOTEquivUsePair> llvm::AsmPrinter::GlobalGOTEquivs
Definition at line 143 of file AsmPrinter.h.
Referenced by computeGlobalGOTEquivs(), emitGlobalGOTEquivs(), emitGlobalVariable(), and handleIndirectSymViaGOTPCRel().
Handlers
std::vector<HandlerInfo> llvm::AsmPrinter::Handlers protected
A vector of all debug/EH info emitters we should use.
This vector maintains ownership of the emitters.
Definition at line 207 of file AsmPrinter.h.
Referenced by addAsmPrinterHandler(), doFinalization(), doInitialization(), emitBasicBlockEnd(), emitBasicBlockStart(), emitFunctionBody(), emitGlobalVariable(), and ~AsmPrinter().
MAI
const MCAsmInfo* llvm::AsmPrinter::MAI
Target Asm Printer information.
Definition at line 90 of file AsmPrinter.h.
Referenced by AsmPrinter(), llvm::ARMException::beginFunction(), llvm::WinException::beginFunction(), llvm::EHStreamer::computeCallSiteTable(), doFinalization(), doInitialization(), emitBasicBlockStart(), emitCFIInstruction(), llvm::DwarfUnit::emitCommonHeader(), emitDwarfSymbolReference(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), emitFunctionBody(), emitFunctionEntryLabel(), emitGlobalConstant(), emitGlobalVariable(), EmitInlineAsmStr(), emitJumpTableInfo(), llvm::X86AsmPrinter::emitKCFITypeId(), emitLabelPlusOffset(), emitLinkage(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), emitPatchableFunctionEntries(), emitSpecialLLVMGlobal(), emitVisibility(), emitXRayTable(), llvm::ARMException::endFunction(), llvm::DwarfCFIException::endModule(), llvm::LanaiMCInstLower::GetConstantPoolIndexSymbol(), getFunctionCFISectionType(), llvm::LanaiMCInstLower::GetJumpTableSymbol(), needsCFIForDebug(), needsSEHMoves(), llvm::SystemZAsmPrinter::PrintAsmMemoryOperand(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::CSKYAsmPrinter::PrintAsmOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printOperand(), PrintSpecial(), llvm::ARMAsmPrinter::PrintSymbolOperand(), PrintSymbolOperand(), and SetupMachineFunction().
MBBSectionRanges
MapVector<unsigned, MBBSectionRange> llvm::AsmPrinter::MBBSectionRanges
Definition at line 138 of file AsmPrinter.h.
Referenced by llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::EHStreamer::computeCallSiteTable(), emitFunctionBody(), llvm::DwarfDebug::endFunctionImpl(), SetupMachineFunction(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIEImpl().
MDT
MachineDominatorTree* llvm::AsmPrinter::MDT = nullptr
This is a pointer to the current MachineDominatorTree.
Definition at line 108 of file AsmPrinter.h.
Referenced by emitFunctionBody().
MF
MachineFunction* llvm::AsmPrinter::MF = nullptr
The current machine function.
Definition at line 102 of file AsmPrinter.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfCompileUnit::addComplexAddress(), llvm::WinException::beginFunclet(), llvm::DebugHandlerBase::beginFunction(), llvm::CodeViewDebug::beginInstruction(), llvm::EHStreamer::computeActionsTable(), llvm::WasmException::computeCallSiteTable(), llvm::EHStreamer::computeCallSiteTable(), doFinalization(), emitAlignment(), emitBasicBlockStart(), emitBBAddrMapSection(), emitCFIInstruction(), llvm::WebAssemblyAsmPrinter::emitConstantPool(), emitConstantPool(), llvm::DwarfDebug::emitDebugLocValue(), emitDebugValueComment(), llvm::EHStreamer::emitExceptionTable(), llvm::MipsAsmPrinter::emitFrameDirective(), emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::MipsAsmPrinter::emitFunctionBodyStart(), llvm::X86AsmPrinter::emitFunctionBodyStart(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::MipsAsmPrinter::emitFunctionEntryLabel(), emitFunctionEntryLabel(), emitImplicitDef(), emitInitialRawDwarfLocDirective(), llvm::R600AsmPrinter::emitInstruction(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), emitKCFITrapEntry(), llvm::X86AsmPrinter::emitKCFITypeId(), emitKCFITypeId(), emitKill(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), emitNops(), emitPatchableFunctionEntries(), emitPCSections(), emitPCSectionsLabel(), emitStackSizeSection(), emitStackUsage(), llvm::EHStreamer::emitTypeInfos(), emitXRayTable(), llvm::ARMException::endFunction(), GetCPISymbol(), getFunctionCFISectionType(), getFunctionNumber(), GetJTISymbol(), GetSizeOfEncodedValue(), getSubtargetInfo(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), lowerConstant(), llvm::AMDGPUAsmPrinter::lowerOperand(), needsSEHMoves(), llvm::AVRAsmPrinter::PrintAsmOperand(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::AMDGPUAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), PrintSpecial(), llvm::R600AsmPrinter::runOnMachineFunction(), llvm::LoongArchAsmPrinter::runOnMachineFunction(), llvm::M68kAsmPrinter::runOnMachineFunction(), llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), runOnMachineFunction(), SetupMachineFunction(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIEImpl().
MLI
MachineLoopInfo* llvm::AsmPrinter::MLI = nullptr
This is a pointer to the current MachineLoopInfo.
Definition at line 111 of file AsmPrinter.h.
Referenced by emitBasicBlockStart(), and emitFunctionBody().
MMI
MachineModuleInfo* llvm::AsmPrinter::MMI = nullptr
This is a pointer to the current MachineModuleInfo.
Definition at line 105 of file AsmPrinter.h.
Referenced by llvm::AVRAsmPrinter::doFinalization(), llvm::NVPTXAsmPrinter::doFinalization(), doFinalization(), doInitialization(), llvm::WebAssemblyAsmPrinter::emitConstantPool(), llvm::WebAssemblyAsmPrinter::emitDecls(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::AVRAsmPrinter::emitStartOfAsmFile(), llvm::X86AsmPrinter::emitStartOfAsmFile(), emitTTypeReference(), llvm::WinCFGuard::endModule(), getDataLayout(), getFunctionCFISectionType(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), and handleIndirectSymViaGOTPCRel().
NumUserHandlers
size_t llvm::AsmPrinter::NumUserHandlers = 0 protected
Definition at line 208 of file AsmPrinter.h.
Referenced by addAsmPrinterHandler(), doFinalization(), and ~AsmPrinter().
ORE
MachineOptimizationRemarkEmitter* llvm::AsmPrinter::ORE
Optimization remark emitter.
Definition at line 114 of file AsmPrinter.h.
Referenced by emitFunctionBody(), and SetupMachineFunction().
OutContext
MCContext& llvm::AsmPrinter::OutContext
This is the context for the output file that we are streaming.
This owns all of the global MC-related objects for the generated translation unit.
Definition at line 94 of file AsmPrinter.h.
Referenced by createTempSymbol(), llvm::AVRAsmPrinter::doFinalization(), doFinalization(), doInitialization(), EmitCamlGlobal(), llvm::WebAssemblyAsmPrinter::emitDecls(), llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::MipsAsmPrinter::emitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), emitFrameAlloc(), emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), llvm::R600AsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::AVRAsmPrinter::emitInstruction(), llvm::WebAssemblyAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), emitKCFITrapEntry(), llvm::X86AsmPrinter::emitKCFITypeId(), emitLabelPlusOffset(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), emitPatchableFunctionEntries(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), emitRemarksSection(), llvm::HexagonAsmPrinter::EmitSled(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), emitXRayTable(), llvm::AVRAsmPrinter::emitXXStructor(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::WasmException::endModule(), llvm::WinCFGuard::endModule(), llvm::WinException::endModule(), getAddrLabelSymbolToEmit(), llvm::ARMAsmPrinter::GetCPISymbol(), GetCPISymbol(), GetExternalSymbolSymbol(), llvm::NVPTXAsmPrinter::getFunctionFrameSymbol(), GetJTISymbol(), GetJTSetSymbol(), GetSymbolFromOperand(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::R600AsmPrinter::lowerConstant(), llvm::AVRAsmPrinter::lowerConstant(), llvm::AMDGPUAsmPrinter::lowerConstant(), lowerConstant(), llvm::AMDGPUAsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineOperandToMCOperand(), lowerSymbolOperand(), LowerSymbolOperand(), llvm::CSKYMCInstLower::lowerSymbolOperand(), and smallData().
OutStreamer
std::unique_ptr<MCStreamer> llvm::AsmPrinter::OutStreamer
This is the MCStreamer object for the file we are generating.
This contains the transient state for the current translation unit that we are generating (such as the current section etc).
Definition at line 99 of file AsmPrinter.h.
Referenced by llvm::AMDGPUAsmPrinter::AMDGPUAsmPrinter(), AsmPrinter(), llvm::DwarfCFIException::beginBasicBlockSection(), llvm::WinException::beginFunclet(), llvm::ARMException::beginFunction(), llvm::DwarfDebug::beginFunctionImpl(), llvm::DebugHandlerBase::beginInstruction(), llvm::DwarfDebug::beginInstruction(), llvm::AVRAsmPrinter::doFinalization(), llvm::AMDGPUAsmPrinter::doFinalization(), llvm::NVPTXAsmPrinter::doFinalization(), doFinalization(), doInitialization(), llvm::DwarfDebug::DwarfDebug(), llvm::DIEAbbrevSet::Emit(), emitAlignment(), llvm::X86AsmPrinter::emitBasicBlockEnd(), emitBasicBlockLoopComments(), emitBasicBlockStart(), emitBBAddrMapSection(), emitCallSiteValue(), EmitCamlGlobal(), emitCFIInstruction(), llvm::DwarfUnit::emitCommonHeader(), emitConstantPool(), emitDebugLabelComment(), llvm::MipsAsmPrinter::emitDebugValue(), emitDebugValue(), emitDebugValueComment(), emitDwarfDIE(), emitDwarfLengthOrOffset(), emitDwarfStringOffset(), emitDwarfSymbolReference(), emitDwarfUnitLength(), emitEncodingByte(), llvm::CSKYAsmPrinter::emitEndOfAsmFile(), llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::MipsAsmPrinter::emitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), emitFrameAlloc(), emitFunctionBody(), llvm::SystemZAsmPrinter::emitFunctionBodyEnd(), llvm::ARMAsmPrinter::emitFunctionBodyEnd(), llvm::MipsAsmPrinter::emitFunctionBodyEnd(), llvm::X86AsmPrinter::emitFunctionBodyEnd(), llvm::X86AsmPrinter::emitFunctionBodyStart(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), llvm::MipsAsmPrinter::emitFunctionEntryLabel(), emitFunctionEntryLabel(), emitGlobalAliasInline(), emitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), llvm::DwarfCompileUnit::emitHeader(), llvm::DwarfTypeUnit::emitHeader(), emitImplicitDef(), emitInitialRawDwarfLocDirective(), llvm::ARMAsmPrinter::emitInlineAsmEnd(), llvm::LoongArchAsmPrinter::emitInstruction(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::CSKYAsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::AVRAsmPrinter::emitInstruction(), llvm::M68kAsmPrinter::emitInstruction(), llvm::WebAssemblyAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), emitInt16(), emitInt32(), emitInt64(), llvm::APByteStreamer::emitInt8(), emitInt8(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), emitKCFITrapEntry(), llvm::X86AsmPrinter::emitKCFITypeId(), emitKill(), emitLabelDifference(), emitLabelDifferenceAsULEB128(), emitLabelPlusOffset(), emitLinkage(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), emitNops(), emitPatchableFunctionEntries(), emitPCSections(), emitPCSectionsLabel(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::PseudoProbeHandler::emitPseudoProbe(), emitRemarksSection(), llvm::APByteStreamer::emitSLEB128(), emitSLEB128(), llvm::HexagonAsmPrinter::EmitSled(), emitStackSizeSection(), llvm::M68kAsmPrinter::emitStartOfAsmFile(), llvm::AVRAsmPrinter::emitStartOfAsmFile(), llvm::ARMAsmPrinter::emitStartOfAsmFile(), llvm::X86AsmPrinter::emitStartOfAsmFile(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::CSKYAsmPrinter::EmitToStreamer(), emitTTypeReference(), llvm::EHStreamer::emitTypeInfos(), llvm::APByteStreamer::emitULEB128(), emitULEB128(), llvm::DwarfFile::emitUnit(), llvm::DIEInlineString::emitValue(), llvm::DIEEntry::emitValue(), emitVisibility(), emitXRayTable(), llvm::AVRAsmPrinter::emitXXStructor(), llvm::ARMAsmPrinter::emitXXStructor(), emitXXStructorList(), llvm::DwarfCFIException::endBasicBlockSection(), llvm::WinException::endFunclet(), llvm::WasmException::endFunction(), llvm::WinException::endFunction(), llvm::DwarfDebug::endFunctionImpl(), llvm::DebugHandlerBase::endInstruction(), llvm::WasmException::endModule(), llvm::WinCFGuard::endModule(), llvm::DwarfCFIException::endModule(), llvm::WinException::endModule(), GetCPISymbol(), getCurrentSection(), llvm::DwarfDebug::getDwarfCompileUnitIDForLineTable(), getDwarfFormParams(), getDwarfOffsetByteSize(), getDwarfVersion(), llvm::DwarfDebug::getDwarfVersion(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::DwarfCompileUnit::getOrCreateSourceID(), llvm::WebAssemblyAsmPrinter::getTargetStreamer(), llvm::AMDGPUAsmPrinter::getTargetStreamer(), getUnitLengthFieldByteSize(), handleIndirectSymViaGOTPCRel(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::DwarfCompileUnit::initStmtList(), isDwarf64(), llvm::ARMException::markFunctionEnd(), llvm::WinException::markFunctionEnd(), llvm::FaultMaps::recordFaultingOp(), llvm::R600AsmPrinter::runOnMachineFunction(), llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), llvm::NVPTXAsmPrinter::runOnMachineFunction(), llvm::FaultMaps::serializeToFaultMapSection(), llvm::StackMaps::serializeToStackMapSection(), setDwarfVersion(), and llvm::DwarfDebug::terminateLineTable().
Sleds
SmallVector<XRayFunctionEntry, 4> llvm::AsmPrinter::Sleds
Definition at line 372 of file AsmPrinter.h.
Referenced by emitXRayTable(), and recordSled().
SM
StackMaps llvm::AsmPrinter::SM protected
Definition at line 210 of file AsmPrinter.h.
Referenced by emitStackMaps().
TM
TargetMachine& llvm::AsmPrinter::TM
Target machine description.
Definition at line 87 of file AsmPrinter.h.
Referenced by llvm::DwarfUnit::addAttribute(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfCFIException::beginBasicBlockSection(), llvm::WinException::beginFunclet(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::DwarfUnit::constructTypeDIE(), llvm::AVRAsmPrinter::doFinalization(), doFinalization(), llvm::AMDGPUAsmPrinter::doInitialization(), doInitialization(), llvm::DwarfDebug::DwarfDebug(), emitAlignment(), emitBasicBlockStart(), llvm::WebAssemblyAsmPrinter::emitDecls(), llvm::CSKYAsmPrinter::emitEndOfAsmFile(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::AMDGPUAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::EHStreamer::emitExceptionTable(), emitFunctionBody(), llvm::SystemZAsmPrinter::emitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), emitFunctionEntryLabel(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), emitGlobalVariable(), llvm::X86AsmPrinter::emitInstruction(), llvm::MipsAsmPrinter::emitInstruction(), emitJumpTableInfo(), emitPatchableFunctionEntries(), emitStackSizeSection(), llvm::CSKYAsmPrinter::emitStartOfAsmFile(), llvm::AVRAsmPrinter::emitStartOfAsmFile(), llvm::ARMAsmPrinter::emitStartOfAsmFile(), llvm::X86AsmPrinter::emitStartOfAsmFile(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), emitTTypeReference(), emitXRayTable(), emitXXStructorList(), llvm::AIXException::endFunction(), llvm::MipsAsmPrinter::getCurrentABIString(), getFunctionCFISectionType(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::AMDGPUAsmPrinter::getGlobalSTI(), getNameWithPrefix(), getObjFileLowering(), getPointerSize(), getSymbol(), GetSymbolFromOperand(), getSymbolPreferLocal(), getSymbolWithGlobalValueBase(), isPositionIndependent(), llvm::R600AsmPrinter::lowerConstant(), llvm::AMDGPUAsmPrinter::lowerConstant(), lowerConstant(), llvm::AArch64MCInstLower::LowerSymbolOperand(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), preprocessXXStructorList(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), SetupMachineFunction(), and llvm::WinException::WinException().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AsmPrinter.h
lib/CodeGen/AsmPrinter/AsmPrinter.cpp
lib/CodeGen/AsmPrinter/AsmPrinterDwarf.cpp
lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp