LLVM: llvm::object::TapiFile Class Reference
llvm::object::TapiFile Class Reference
#include "llvm/Object/TapiFile.h"
Public Member Functions
TapiFile (MemoryBufferRef Source, const MachO::InterfaceFile &interface, MachO::Architecture Arch)
~TapiFile () override
void moveSymbolNext (DataRefImpl &DRI) const override
Error printSymbolName (raw_ostream &OS, DataRefImpl DRI) const override
Expected< uint32_t > getSymbolFlags (DataRefImpl DRI) const override
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
bool is64Bit () const override
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
virtual Error initContent ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isOffloadFile () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context, bool InitContent=true)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static bool isSymbolicFile (file_magic Type, const LLVMContext *Context)
Static Public Member Functions inherited from llvm::object::Binary
static Error checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Additional Inherited Members
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_COFFImportFile, ID_IR,
ID_TapiUniversal, ID_TapiFile, ID_Minidump, ID_WinRes,
ID_Offload, ID_StartObjects, ID_COFF, ID_XCOFF32,
ID_XCOFF64, ID_ELF32L, ID_ELF32B, ID_ELF64L,
ID_ELF64B, ID_MachO32L, ID_MachO32B, ID_MachO64L,
ID_MachO64B, ID_Wasm, ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 35 of file TapiFile.h.
Constructor & Destructor Documentation
TapiFile()
TapiFile::TapiFile (MemoryBufferRef Source, const MachO::InterfaceFile & interface, MachO::Architecture Arch)
Definition at line 40 of file TapiFile.cpp.
References llvm::ARMBuildAttrs::Symbol, and llvm::MachO::InterfaceFile::symbols().
~TapiFile()
TapiFile::~TapiFile () override default
Member Function Documentation
classof()
static bool llvm::object::TapiFile::classof (const Binary * v) inline static
Definition at line 51 of file TapiFile.h.
References llvm::object::Binary::isTapiFile().
getSymbolFlags()
Expected< uint32_t > TapiFile::getSymbolFlags (DataRefImpl DRI) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 85 of file TapiFile.cpp.
References llvm::object::DataRefImpl::a, assert(), and llvm::object::DataRefImpl::d.
is64Bit()
bool llvm::object::TapiFile::is64Bit () const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 53 of file TapiFile.h.
References llvm::MachO::is64Bit().
moveSymbolNext()
void TapiFile::moveSymbolNext (DataRefImpl & DRI) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 76 of file TapiFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
printSymbolName()
Error TapiFile::printSymbolName (raw_ostream & OS, DataRefImpl DRI) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 78 of file TapiFile.cpp.
References llvm::object::DataRefImpl::a, assert(), and llvm::object::DataRefImpl::d.
symbol_begin()
basic_symbol_iterator TapiFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 90 of file TapiFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
symbol_end()
basic_symbol_iterator TapiFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 96 of file TapiFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
The documentation for this class was generated from the following files:
include/llvm/Object/TapiFile.h
lib/Object/TapiFile.cpp