LLVM: llvm::SPIRVLegalizerInfo Class Reference
llvm::SPIRVLegalizerInfo Class Reference
#include "Target/SPIRV/SPIRVLegalizerInfo.h"
Public Member Functions
bool legalizeCustom (LegalizerHelper &Helper, MachineInstr &MI) const override
Called for instructions with the Custom LegalizationAction.
SPIRVLegalizerInfo (const SPIRVSubtarget &ST)
Public Member Functions inherited from llvm::LegalizerInfo
virtual ~LegalizerInfo ()=default
const LegacyLegalizerInfo & getLegacyLegalizerInfo () const
LegacyLegalizerInfo & getLegacyLegalizerInfo ()
unsigned getOpcodeIdxForOpcode (unsigned Opcode) const
unsigned getActionDefinitionsIdx (unsigned Opcode) const
void verify (const MCInstrInfo &MII) const
Perform simple self-diagnostic and assert if there is anything obviously wrong with the actions set up.
const LegalizeRuleSet & getActionDefinitions (unsigned Opcode) const
Get the action definitions for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (unsigned Opcode)
Get the action definition builder for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (std::initializer_list< unsigned > Opcodes)
Get the action definition builder for the given set of opcodes.
void aliasActionDefinitions (unsigned OpcodeTo, unsigned OpcodeFrom)
LegalizeActionStep getAction (const LegalityQuery &Query) const
Determine what action should be taken to legalize the described instruction.
LegalizeActionStep getAction (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
Determine what action should be taken to legalize the given generic instruction.
bool isLegal (const LegalityQuery &Query) const
bool isLegalOrCustom (const LegalityQuery &Query) const
bool isLegal (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isLegalOrCustom (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual bool legalizeIntrinsic (LegalizerHelper &Helper, MachineInstr &MI) const
virtual unsigned getExtOpcodeForWideningConstant (LLT SmallTy) const
Return the opcode (SEXT/ZEXT/ANYEXT) that should be performed while widening a constant of type SmallTy which targets can override.
Detailed Description
Definition at line 27 of file SPIRVLegalizerInfo.h.
Constructor & Destructor Documentation
SPIRVLegalizerInfo()
SPIRVLegalizerInfo::SPIRVLegalizerInfo (const SPIRVSubtarget & ST)
Definition at line 57 of file SPIRVLegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), llvm::LLT::fixed_vector(), llvm::LLT::pointer(), s1, llvm::LLT::scalar(), llvm::ARM_MB::ST, TypeFoldingSupportingOpcs, llvm::LegalityPredicates::typeInSet(), llvm::LegalityQuery::Types, and verify.
Member Function Documentation
legalizeCustom()
bool SPIRVLegalizerInfo::legalizeCustom (LegalizerHelper & Helper, MachineInstr & MI) const override virtual
Called for instructions with the Custom LegalizationAction.
Reimplemented from llvm::LegalizerInfo.
Definition at line 289 of file SPIRVLegalizerInfo.cpp.
References assert(), Cond, convertPtrToInt(), llvm::IntegerType::get(), llvm::MachineRegisterInfo::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::LLT::isPointer(), isTypeFoldingSupported(), MI, llvm::LegalizerHelper::MIRBuilder, MRI, llvm::LLT::scalar(), and llvm::ARM_MB::ST.
The documentation for this class was generated from the following files:
lib/Target/SPIRV/SPIRVLegalizerInfo.h
lib/Target/SPIRV/SPIRVLegalizerInfo.cpp