LLVM: llvm::objcopy::NameOrPattern Class Reference
llvm::objcopy::NameOrPattern Class Reference
#include "llvm/ObjCopy/CommonConfig.h"
Public Member Functions
bool isPositiveMatch () const
std::optional< StringRef > getName () const
bool operator== (StringRef S) const
bool operator!= (StringRef S) const
Static Public Member Functions
static Expected< NameOrPattern > create (StringRef Pattern, MatchStyle MS, llvm::function_ref< Error(Error)> ErrorCallback)
Detailed Description
Definition at line 98 of file CommonConfig.h.
Member Function Documentation
create()
Expected< NameOrPattern > llvm::objcopy::NameOrPattern::create (StringRef Pattern, MatchStyle MS, llvm::function_ref< Error(Error)> ErrorCallback) static
Definition at line 15 of file CommonConfig.cpp.
References llvm::GlobPattern::create(), llvm::Data, E, llvm::objcopy::Literal, llvm_unreachable, move, llvm::objcopy::Regex, llvm::Expected< T >::takeError(), and llvm::objcopy::Wildcard.
getName()
std::optional<StringRef> llvm::objcopy::NameOrPattern::getName () const inline
Definition at line 118 of file CommonConfig.h.
References G.
isPositiveMatch()
bool llvm::objcopy::NameOrPattern::isPositiveMatch () const inline
Definition at line 117 of file CommonConfig.h.
operator!=()
bool llvm::objcopy::NameOrPattern::operator!= (StringRef S) const inline
Definition at line 126 of file CommonConfig.h.
References operator==(), and S.
operator==()
bool llvm::objcopy::NameOrPattern::operator== (StringRef S) const inline
Definition at line 123 of file CommonConfig.h.
References G, and S.
Referenced by operator!=().
The documentation for this class was generated from the following files:
include/llvm/ObjCopy/CommonConfig.h
lib/ObjCopy/CommonConfig.cpp