LLVM: llvm::pdb::LinePrinter Class Reference
llvm::pdb::LinePrinter Class Reference
#include "llvm/DebugInfo/PDB/Native/LinePrinter.h"
Public Member Functions
LinePrinter (int Indent, bool UseColor, raw_ostream &Stream, const FilterOptions &Filters)
void Indent (uint32_t Amount=0)
void Unindent (uint32_t Amount=0)
void NewLine ()
void printLine (const Twine &T)
void print (const Twine &T)
template<typename... Ts>
void formatLine (const char *Fmt, Ts &&...Items)
template<typename... Ts>
void format (const char *Fmt, Ts &&...Items)
void formatBinary (StringRef Label, ArrayRef< uint8_t > Data, uint64_t StartOffset)
void formatBinary (StringRef Label, ArrayRef< uint8_t > Data, uint64_t BaseAddr, uint64_t StartOffset)
void formatMsfStreamData (StringRef Label, PDBFile &File, uint32_t StreamIdx, StringRef StreamPurpose, uint64_t Offset, uint64_t Size)
void formatMsfStreamData (StringRef Label, PDBFile &File, const msf::MSFStreamLayout &Stream, BinarySubstreamRef Substream)
void formatMsfStreamBlocks (PDBFile &File, const msf::MSFStreamLayout &Stream)
bool hasColor () const
raw_ostream & getStream ()
int getIndentLevel () const
bool IsClassExcluded (const ClassLayout &Class)
bool IsTypeExcluded (llvm::StringRef TypeName, uint64_t Size)
bool IsSymbolExcluded (llvm::StringRef SymbolName)
bool IsCompilandExcluded (llvm::StringRef CompilandName)
const FilterOptions & getFilters () const
Friends
class WithColor
Detailed Description
Definition at line 50 of file LinePrinter.h.
Constructor & Destructor Documentation
LinePrinter()
LinePrinter::LinePrinter (int Indent, bool UseColor, llvm::raw_ostream & Stream, const FilterOptions & Filters)
Definition at line 56 of file LinePrinter.cpp.
References FilterOptions::ExcludeCompilands, FilterOptions::ExcludeSymbols, FilterOptions::ExcludeTypes, FilterOptions::IncludeCompilands, FilterOptions::IncludeSymbols, and FilterOptions::IncludeTypes.
Member Function Documentation
format()
template<typename... Ts> void llvm::pdb::LinePrinter::format (const char * Fmt, Ts &&... Items) inline
Definition at line 66 of file LinePrinter.h.
References llvm::formatv(), and print().
formatBinary() [1/2]
void LinePrinter::formatBinary (StringRef Label, ArrayRef< uint8_t > Data, uint64_t BaseAddr, uint64_t StartOffset)
Definition at line 120 of file LinePrinter.cpp.
References llvm::sampleprof::Base, llvm::Data, llvm::format_bytes_with_ascii(), llvm::pdb::Label, and NewLine().
formatBinary() [2/2]
void LinePrinter::formatBinary (StringRef Label, ArrayRef< uint8_t > Data, uint64_t StartOffset)
Definition at line 107 of file LinePrinter.cpp.
References llvm::Data, llvm::format_bytes_with_ascii(), llvm::pdb::Label, and NewLine().
formatLine()
template<typename... Ts> void llvm::pdb::LinePrinter::formatLine (const char * Fmt, Ts &&... Items) inline
Definition at line 63 of file LinePrinter.h.
References llvm::formatv(), and printLine().
Referenced by formatMsfStreamData(), and llvm::pdb::iterateOneModule().
formatMsfStreamBlocks()
void LinePrinter::formatMsfStreamBlocks (PDBFile & File, const msf::MSFStreamLayout & Stream)
Definition at line 252 of file LinePrinter.cpp.
References llvm::ArrayRef(), assert(), llvm::msf::MSFStreamLayout::Blocks, llvm::cantFail(), llvm::format_bytes_with_ascii(), llvm::formatv(), llvm::msf::MSFStreamLayout::Length, llvm::min(), NewLine(), and uint64_t.
formatMsfStreamData() [1/2]
void LinePrinter::formatMsfStreamData (StringRef Label, PDBFile & File, const msf::MSFStreamLayout & Stream, BinarySubstreamRef Substream)
Definition at line 218 of file LinePrinter.cpp.
References assert(), llvm::sampleprof::Base, llvm::BinaryStreamReader::bytesRemaining(), llvm::Center, computeBlockRuns(), llvm::consumeError(), llvm::Data, findRun(), llvm::fmt_align(), llvm::format_bytes_with_ascii(), llvm::formatv(), llvm::pdb::Label, llvm::min(), NewLine(), llvm::BinarySubstreamRef::Offset, llvm::BinaryStreamReader::readBytes(), llvm::BinarySubstreamRef::StreamData, and uint64_t.
formatMsfStreamData() [2/2]
void LinePrinter::formatMsfStreamData (StringRef Label, PDBFile & File, uint32_t StreamIdx, StringRef StreamPurpose, uint64_t Offset, uint64_t Size)
Definition at line 180 of file LinePrinter.cpp.
References formatLine(), NewLine(), S, and uint64_t.
getFilters()
const FilterOptions& llvm::pdb::LinePrinter::getFilters () const inline
Definition at line 92 of file LinePrinter.h.
Referenced by llvm::pdb::iterateSymbolGroups().
getIndentLevel()
int llvm::pdb::LinePrinter::getIndentLevel () const inline
Definition at line 85 of file LinePrinter.h.
getStream()
raw_ostream& llvm::pdb::LinePrinter::getStream () inline
Definition at line 84 of file LinePrinter.h.
References OS.
hasColor()
bool llvm::pdb::LinePrinter::hasColor () const inline
Definition at line 83 of file LinePrinter.h.
References UseColor.
Indent()
void LinePrinter::Indent (uint32_t Amount = 0)
Definition at line 75 of file LinePrinter.cpp.
Referenced by llvm::pdb::AutoIndent::AutoIndent().
IsClassExcluded()
bool LinePrinter::IsClassExcluded (const ClassLayout & Class)
Definition at line 99 of file LinePrinter.cpp.
References IsTypeExcluded(), and FilterOptions::PaddingThreshold.
IsCompilandExcluded()
bool LinePrinter::IsCompilandExcluded (llvm::StringRef CompilandName)
Definition at line 289 of file LinePrinter.cpp.
IsSymbolExcluded()
bool LinePrinter::IsSymbolExcluded (llvm::StringRef SymbolName)
Definition at line 285 of file LinePrinter.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
IsTypeExcluded()
bool LinePrinter::IsTypeExcluded (llvm::StringRef TypeName, uint64_t Size)
Definition at line 277 of file LinePrinter.cpp.
References FilterOptions::SizeThreshold, and llvm::AMDGPU::HSAMD::Kernel::Arg::Key::TypeName.
Referenced by IsClassExcluded().
NewLine()
void LinePrinter::NewLine ()
Definition at line 87 of file LinePrinter.cpp.
References llvm::raw_ostream::indent().
Referenced by formatBinary(), formatMsfStreamBlocks(), formatMsfStreamData(), and printLine().
print()
void LinePrinter::print (const Twine & T)
Definition at line 92 of file LinePrinter.cpp.
Referenced by format().
printLine()
void LinePrinter::printLine (const Twine & T)
Definition at line 94 of file LinePrinter.cpp.
References NewLine().
Referenced by formatLine().
Unindent()
void LinePrinter::Unindent (uint32_t Amount = 0)
Definition at line 81 of file LinePrinter.cpp.
Referenced by llvm::pdb::AutoIndent::~AutoIndent().
Friends And Related Function Documentation
WithColor
friend class WithColor friend
Definition at line 51 of file LinePrinter.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/LinePrinter.h
lib/DebugInfo/PDB/Native/LinePrinter.cpp