LLVM: llvm::ShapeT Class Reference
llvm::ShapeT Class Reference
#include "llvm/CodeGen/TileShapeInfo.h"
Public Member Functions
ShapeT (MachineOperand *Row, MachineOperand *Col, const MachineRegisterInfo *MRI=nullptr)
ShapeT ()
bool operator== (const ShapeT &Shape) const
bool operator!= (const ShapeT &Shape) const
MachineOperand * getRow () const
MachineOperand * getCol () const
int64_t getRowImm () const
int64_t getColImm () const
bool isValid ()
void deduceImm (const MachineRegisterInfo *MRI)
Detailed Description
Definition at line 30 of file TileShapeInfo.h.
Constructor & Destructor Documentation
ShapeT() [1/2]
llvm::ShapeT::ShapeT (MachineOperand * Row, MachineOperand * Col, const MachineRegisterInfo * MRI = nullptr) inline
Definition at line 32 of file TileShapeInfo.h.
References deduceImm(), and MRI.
ShapeT() [2/2]
llvm::ShapeT::ShapeT () inline
Definition at line 38 of file TileShapeInfo.h.
Member Function Documentation
deduceImm()
void llvm::ShapeT::deduceImm (const MachineRegisterInfo * MRI) inline
Definition at line 67 of file TileShapeInfo.h.
References GetImm(), llvm::MachineOperand::getReg(), llvm::RISCVMatInt::Imm, MI, and MRI.
Referenced by ShapeT().
getCol()
MachineOperand* llvm::ShapeT::getCol () const inline
Definition at line 59 of file TileShapeInfo.h.
getColImm()
int64_t llvm::ShapeT::getColImm () const inline
Definition at line 63 of file TileShapeInfo.h.
Referenced by operator==().
getRow()
MachineOperand* llvm::ShapeT::getRow () const inline
Definition at line 57 of file TileShapeInfo.h.
getRowImm()
int64_t llvm::ShapeT::getRowImm () const inline
Definition at line 61 of file TileShapeInfo.h.
Referenced by operator==().
isValid()
bool llvm::ShapeT::isValid () inline
Definition at line 65 of file TileShapeInfo.h.
Referenced by llvm::VirtRegMap::hasShape().
operator!=()
bool llvm::ShapeT::operator!= (const ShapeT & Shape) const inline
Definition at line 55 of file TileShapeInfo.h.
operator==()
bool llvm::ShapeT::operator== (const ShapeT & Shape) const inline
Definition at line 41 of file TileShapeInfo.h.
References getColImm(), llvm::MachineOperand::getReg(), and getRowImm().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/TileShapeInfo.h