LLVM: llvm::StringSaver Class Reference
llvm::StringSaver Class Reference final
Saves strings in the provided stable storage and returns a StringRef with a stable character pointer.
#include "llvm/Support/StringSaver.h"
Public Member Functions
StringSaver (BumpPtrAllocator &Alloc)
BumpPtrAllocator & getAllocator () const
StringRef save (const char *S)
StringRef save (StringRef S)
StringRef save (const Twine &S)
StringRef save (const std::string &S)
Detailed Description
Saves strings in the provided stable storage and returns a StringRef with a stable character pointer.
Definition at line 21 of file StringSaver.h.
Constructor & Destructor Documentation
StringSaver()
llvm::StringSaver::StringSaver (BumpPtrAllocator & Alloc) inline
Definition at line 25 of file StringSaver.h.
Member Function Documentation
getAllocator()
BumpPtrAllocator& llvm::StringSaver::getAllocator () const inline
Definition at line 27 of file StringSaver.h.
Referenced by llvm::cl::ExpandResponseFiles(), and llvm::cl::expandResponseFiles().
save() [1/4]
StringRef llvm::StringSaver::save (const char * S) inline
Definition at line 30 of file StringSaver.h.
References S, and save().
Referenced by addSection(), ExpandBasePaths(), getSearchPaths(), llvm::codeview::TypeTableCollection::getTypeName(), llvm::codeview::LazyRandomTypeCollection::getTypeName(), llvm::libDriverMain(), llvm::jitlink::COFFDirectiveParser::parse(), save(), llvm::UniqueStringSaver::save(), llvm::ModuleSummaryIndex::saveString(), llvm::cl::TokenizeGNUCommandLine(), and tokenizeWindowsCommandLineImpl().
save() [2/4]
StringRef llvm::StringSaver::save (const std::string & S) inline
Definition at line 33 of file StringSaver.h.
References S, and save().
Referenced by save().
save() [3/4]
StringRef llvm::StringSaver::save (const Twine & S) inline
Definition at line 32 of file StringSaver.h.
References S, and save().
Referenced by save().
save() [4/4]
StringRef StringSaver::save (StringRef S)
Definition at line 13 of file StringSaver.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), memcpy(), P, and S.
The documentation for this class was generated from the following files:
include/llvm/Support/StringSaver.h
lib/Support/StringSaver.cpp