LLVM: llvm::ConstantExpr Class Reference
llvm::ConstantExpr Class Reference
A constant value that is initialized with an expression using other constant values.
#include "llvm/IR/Constants.h"
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Transparently provide more efficient getOperand methods.
bool isCast () const
Return true if this is a convert constant expression.
bool isCompare () const
Return true if this is a compare constant expression.
unsigned getOpcode () const
Return the opcode at the root of this constant expression.
unsigned getPredicate () const
Return the ICMP or FCMP predicate value.
ArrayRef< int > getShuffleMask () const
Assert that this is a shufflevector and return the mask.
Constant * getShuffleMaskForBitcode () const
Assert that this is a shufflevector and return the mask.
const char * getOpcodeName () const
Return a string representation for an opcode.
Constant * getWithOperands (ArrayRef< Constant * > Ops) const
This returns the current constant expression with the operands replaced with the specified values.
Constant * getWithOperands (ArrayRef< Constant * > Ops, Type *Ty, bool OnlyIfReduced=false, Type *SrcTy=nullptr) const
Get the current expression with the operands replaced.
Instruction * getAsInstruction (Instruction *InsertBefore=nullptr) const
Returns an Instruction which implements the same operation as this ConstantExpr.
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a fixed width vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal, infinity, nan, or zero) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefOrPoisonElement () const
Return true if this is a vector constant that includes any undef or poison elements.
bool containsPoisonElement () const
Return true if this is a vector constant that includes any poison elements.
bool containsUndefElement () const
Return true if this is a vector constant that includes any strictly undef (not poison) elements.
bool containsConstantExpression () const
Return true if this is a fixed width vector constant that includes any constant expressions.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry (either static or dynamic).
bool needsDynamicRelocation () const
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
bool hasOneLiveUse () const
Return true if the constant has exactly one live use.
bool hasZeroLiveUses () const
Return true if the constant has no live uses.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
bool isManifestConstant () const
Return true if a constant is ConstantData or a ConstantAggregate or ConstantExpr that contain only ConstantData.
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static Constant * getAlignOf (Type *Ty)
getAlignOf constant expr - computes the alignment of a type in a target independent way (Note: the return type is an i64).
static Constant * getSizeOf (Type *Ty)
getSizeOf constant expr - computes the (alloc) size of a type (in address-units, not bits) in a target independent way (Note: the return type is an i64).
static Constant * getOffsetOf (StructType *STy, unsigned FieldNo)
getOffsetOf constant expr - computes the offset of a struct field in a target independent way (Note: the return type is an i64).
static Constant * getOffsetOf (Type *Ty, Constant *FieldNo)
getOffsetOf constant expr - This is a generalized form of getOffsetOf, which supports any aggregate type, and any Constant index.
static Constant * getNeg (Constant *C, bool HasNUW=false, bool HasNSW=false)
static Constant * getNot (Constant *C)
static Constant * getAdd (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getSub (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getMul (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getAnd (Constant *C1, Constant *C2)
static Constant * getOr (Constant *C1, Constant *C2)
static Constant * getXor (Constant *C1, Constant *C2)
static Constant * getUMin (Constant *C1, Constant *C2)
static Constant * getShl (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getLShr (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getAShr (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getTrunc (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getSExt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getZExt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPTrunc (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPExtend (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getUIToFP (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getSIToFP (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPToUI (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPToSI (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getPtrToInt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getIntToPtr (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getBitCast (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getAddrSpaceCast (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getNSWNeg (Constant *C)
static Constant * getNUWNeg (Constant *C)
static Constant * getNSWAdd (Constant *C1, Constant *C2)
static Constant * getNUWAdd (Constant *C1, Constant *C2)
static Constant * getNSWSub (Constant *C1, Constant *C2)
static Constant * getNUWSub (Constant *C1, Constant *C2)
static Constant * getNSWMul (Constant *C1, Constant *C2)
static Constant * getNUWMul (Constant *C1, Constant *C2)
static Constant * getNSWShl (Constant *C1, Constant *C2)
static Constant * getNUWShl (Constant *C1, Constant *C2)
static Constant * getExactAShr (Constant *C1, Constant *C2)
static Constant * getExactLShr (Constant *C1, Constant *C2)
static Constant * getExactLogBase2 (Constant *C)
If C is a scalar/fixed width vector of known powers of 2, then this function returns a new scalar/fixed width vector obtained from logBase2 of C.
static Constant * getBinOpIdentity (unsigned Opcode, Type *Ty, bool AllowRHSConstant=false, bool NSZ=false)
Return the identity constant for a binary opcode.
static Constant * getBinOpAbsorber (unsigned Opcode, Type *Ty)
Return the absorbing element for the given binary operation, i.e.
static Constant * getCast (unsigned ops, Constant *C, Type *Ty, bool OnlyIfReduced=false)
Convenience function for getting a Cast operation.
static Constant * getZExtOrBitCast (Constant *C, Type *Ty)
static Constant * getSExtOrBitCast (Constant *C, Type *Ty)
static Constant * getTruncOrBitCast (Constant *C, Type *Ty)
static Constant * getSExtOrTrunc (Constant *C, Type *Ty)
Create either an sext, trunc or nothing, depending on whether Ty is wider, narrower or the same as C->getType().
static Constant * getPointerCast (Constant *C, Type *Ty)
Create a BitCast, AddrSpaceCast, or a PtrToInt cast constant expression.
static Constant * getPointerBitCastOrAddrSpaceCast (Constant *C, Type *Ty)
Create a BitCast or AddrSpaceCast for a pointer type depending on the address space.
static Constant * getIntegerCast (Constant *C, Type *Ty, bool IsSigned)
Create a ZExt, Bitcast or Trunc for integer -> integer casts.
static Constant * getFPCast (Constant *C, Type *Ty)
Create a FPExt, Bitcast or FPTrunc for fp -> fp casts.
static Constant * getSelect (Constant *C, Constant *V1, Constant *V2, Type *OnlyIfReducedTy=nullptr)
Select constant expr.
static Constant * get (unsigned Opcode, Constant *C1, Constant *C2, unsigned Flags=0, Type *OnlyIfReducedTy=nullptr)
get - Return a binary or shift operator constant expression, folding if possible.
static Constant * getCompare (unsigned short pred, Constant *C1, Constant *C2, bool OnlyIfReduced=false)
Return an ICmp or FCmp comparison operator constant expression.
static Constant * getICmp (unsigned short pred, Constant *LHS, Constant *RHS, bool OnlyIfReduced=false)
get* - Return some common constants without having to specify the full Instruction::OPCODE identifier.
static Constant * getFCmp (unsigned short pred, Constant *LHS, Constant *RHS, bool OnlyIfReduced=false)
static Constant * getGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList, bool InBounds=false, std::optional< unsigned > InRangeIndex=std::nullopt, Type *OnlyIfReducedTy=nullptr)
Getelementptr form.
static Constant * getGetElementPtr (Type *Ty, Constant *C, Constant *Idx, bool InBounds=false, std::optional< unsigned > InRangeIndex=std::nullopt, Type *OnlyIfReducedTy=nullptr)
static Constant * getGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList, bool InBounds=false, std::optional< unsigned > InRangeIndex=std::nullopt, Type *OnlyIfReducedTy=nullptr)
static Constant * getInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList)
Create an "inbounds" getelementptr.
static Constant * getInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx)
static Constant * getInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList)
static Constant * getExtractElement (Constant *Vec, Constant *Idx, Type *OnlyIfReducedTy=nullptr)
static Constant * getInsertElement (Constant *Vec, Constant *Elt, Constant *Idx, Type *OnlyIfReducedTy=nullptr)
static Constant * getShuffleVector (Constant *V1, Constant *V2, ArrayRef< int > Mask, Type *OnlyIfReducedTy=nullptr)
static bool isDesirableBinOp (unsigned Opcode)
Whether creating a constant expression for this binary operator is desirable.
static bool isSupportedBinOp (unsigned Opcode)
Whether creating a constant expression for this binary operator is supported.
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
static Constant * mergeUndefsWith (Constant *C, Constant *Other)
Merges undefs of a Constant with another Constant, along with the undefs already present.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
ConstantExpr (Type *ty, unsigned Opcode, Use *Ops, unsigned NumOps)
~ConstantExpr ()=default
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
~Constant ()=default
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * >> &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Friends
struct ConstantExprKeyType
class Constant
Additional Inherited Members
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
A constant value that is initialized with an expression using other constant values.
This class uses the standard Instruction opcodes to define the various constant expressions. The Opcode field for the ConstantExpr class is maintained in the Value::SubclassData field.
Definition at line 998 of file Constants.h.
Constructor & Destructor Documentation
ConstantExpr()
llvm::ConstantExpr::ConstantExpr (Type * ty, unsigned Opcode, Use * Ops, unsigned NumOps) inline protected
Definition at line 1006 of file Constants.h.
~ConstantExpr()
llvm::ConstantExpr::~ConstantExpr () protected default
Member Function Documentation
classof()
static bool llvm::ConstantExpr::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 1354 of file Constants.h.
References llvm::Value::getValueID().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::ConstantExpr::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Transparently provide more efficient getOperand methods.
get()
Constant * ConstantExpr::get (unsigned Opcode, Constant * C1, Constant * C2, unsigned Flags = 0, Type * OnlyIfReducedTy = nullptr) static
get - Return a binary or shift operator constant expression, folding if possible.
Parameters
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 2263 of file Constants.cpp.
References llvm::MCID::Add, assert(), C1, llvm::ConstantFoldBinaryInstruction(), llvm::LLVMContextImpl::ExprConstants, R600_InstFlag::FC, llvm::Value::getType(), llvm::Instruction::isBinaryOp(), isSupportedBinOp(), and Mul.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFolder::FoldBinOp(), llvm::TargetFolder::FoldBinOp(), llvm::ConstantFolder::FoldExactBinOp(), llvm::TargetFolder::FoldExactBinOp(), foldGEPOfGEP(), llvm::ConstantFolder::FoldNoWrapBinOp(), llvm::TargetFolder::FoldNoWrapBinOp(), getAdd(), getAnd(), getAShr(), getLShr(), getMul(), getNot(), getOr(), getShl(), getSub(), getWithOperands(), getXor(), and simplifyAssocCastAssoc().
getAdd()
Constant * ConstantExpr::getAdd (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2657 of file Constants.cpp.
References llvm::MCID::Add, C1, get(), llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by llvm::InstCombiner::AddOne(), BuildConstantFromSCEV(), llvm::ConstantFoldGetElementPtr(), llvm::copyNonnullMetadata(), llvm::InstCombinerImpl::foldAddWithConstant(), foldNoWrapAdd(), foldShiftOfShiftedBinOp(), getAsConstantIndexedAddress(), llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(), LLVMConstAdd(), matchFunnelShift(), llvm::InstCombinerImpl::visitAdd(), and llvm::InstCombinerImpl::visitAnd().
getAddrSpaceCast()
Constant * ConstantExpr::getAddrSpaceCast (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2241 of file Constants.cpp.
References assert(), llvm::CastInst::castIsValid(), llvm::FixedVectorType::get(), llvm::PointerType::getAddressSpace(), getBitCast(), getFoldedCast(), llvm::Type::getScalarType(), llvm::PointerType::getWithSamePointeeType(), and llvm::PointerType::hasSameElementTypeAs().
Referenced by cloneConstantExprWithNewAddressSpace(), getCast(), getPointerBitCastOrAddrSpaceCast(), getPointerCast(), LLVMConstAddrSpaceCast(), and operandWithNewAddressSpaceOrCreateUndef().
getAlignOf()
Constant * ConstantExpr::getAlignOf (Type * Ty) static
getAlignOf constant expr - computes the alignment of a type in a target independent way (Note: the return type is an i64).
Definition at line 2388 of file Constants.cpp.
References GEP, llvm::ConstantInt::get(), llvm::StructType::get(), llvm::Type::getContext(), getGetElementPtr(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Constant::getNullValue(), llvm::Type::getPointerTo(), and getPtrToInt().
Referenced by LLVMAlignOf().
getAnd()
Constant * ConstantExpr::getAnd (Constant * C1, Constant * C2) static
Definition at line 2678 of file Constants.cpp.
References C1, and get().
Referenced by llvm::ConstantFoldBinaryInstruction(), ExtractConstantBytes(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), and LLVMConstAnd().
getAShr()
Constant * ConstantExpr::getAShr (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2707 of file Constants.cpp.
References C1, get(), and llvm::PossiblyExactOperator::IsExact.
Referenced by LLVMConstAShr().
getAsInstruction()
Instruction * ConstantExpr::getAsInstruction (Instruction * InsertBefore = nullptr) const
Returns an Instruction which implements the same operation as this ConstantExpr.
If InsertBefore is not null, the new instruction is inserted before it, otherwise it is not inserted into any basic block.
A better approach to this could be to have a constructor for Instruction which would take a ConstantExpr parameter, but that would have spread implementation details of ConstantExpr outside of Constants.cpp, which would make it harder to remove ConstantExprs altogether.
Definition at line 3423 of file Constants.cpp.
References assert(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::CmpInst::Create(), llvm::GetElementPtrInst::Create(), llvm::SelectInst::Create(), llvm::ExtractElementInst::Create(), llvm::InsertElementInst::Create(), llvm::GetElementPtrInst::CreateInBounds(), llvm::User::getNumOperands(), getOpcode(), getPredicate(), getShuffleMask(), llvm::Value::getType(), llvm::PossiblyExactOperator::IsExact, llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, llvm::User::operands(), Select, llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::Instruction::setIsExact(), llvm::ArrayRef< T >::slice(), and llvm::Value::SubclassOptionalData.
getBinOpAbsorber()
Constant * ConstantExpr::getBinOpAbsorber (unsigned Opcode, Type * Ty) static
Return the absorbing element for the given binary operation, i.e.
a constant C such that X op C = C and C op X = C for every X. For example, this returns zero for integer multiplication. It returns null if the operator doesn't have an absorbing element.
Definition at line 2786 of file Constants.cpp.
References llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), and Mul.
getBinOpIdentity()
Constant * ConstantExpr::getBinOpIdentity (unsigned Opcode, Type * Ty, bool AllowRHSConstant = false, bool NSZ = false) static
Return the identity constant for a binary opcode.
The identity constant C is defined as X op C = X and C op X = X for every X when the binary operation is commutative. If the binop is not commutative, callers can acquire the operand 1 identity constant by setting AllowRHSConstant to true. For example, any shift has a zero identity constant for operand 1: X shift 0 = X. If this is a fadd/fsub operation and we don't care about signed zeros, then setting NSZ to true returns the identity +0.0 instead of -0.0. Return nullptr if the operator does not have an identity constant.
Definition at line 2741 of file Constants.cpp.
References llvm::MCID::Add, assert(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), llvm::ConstantFP::getZero(), llvm::Instruction::isBinaryOp(), llvm::Instruction::isCommutative(), llvm_unreachable, and Mul.
Referenced by llvm::ConstantFoldBinaryInstruction(), foldSelectBinOpIdentity(), llvm::InstCombinerImpl::foldSelectIntoOp(), foldSelectShuffleWith1Binop(), llvm::InstCombinerImpl::foldUsingDistributiveLaws(), getIdentityValue(), llvm::InstCombiner::getSafeVectorConstantForBinop(), LinearizeExprTree(), and simplifyWithOpReplaced().
getBitCast()
Constant * ConstantExpr::getBitCast (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2229 of file Constants.cpp.
References assert(), llvm::CastInst::castIsValid(), and getFoldedCast().
Referenced by BitCastConstantVector(), BuildConstantFromSCEV(), cloneConstantExprWithNewAddressSpace(), collectInsertionElements(), llvm::ConstantFoldCompareInstruction(), llvm::SanitizerStatReport::create(), llvm::OpenMPIRBuilder::createTask(), emitGlobalConstantVector(), llvm::SanitizerStatReport::finish(), FoldBitCast(), getAddrSpaceCast(), getCast(), getFuncAddrForProfData(), getMemCmpLoad(), getNegativeIsTrueBoolVec(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), llvm::Module::getOrInsertFunction(), llvm::Module::getOrInsertGlobal(), getPointerBitCastOrAddrSpaceCast(), getPointerCast(), getSExtOrBitCast(), getTruncOrBitCast(), getZExtOrBitCast(), insertCall(), instrumentOneFunc(), llvm::isBytewiseValue(), llvm::Constant::isElementWiseEqual(), LLVMConstBitCast(), OptimizeGlobalAddressOfAllocation(), OptimizeGlobalAliases(), optimizeMemCmpConstantSize(), optimizeOnceStoredGlobal(), processInternalGlobal(), removeGlobalCtors(), replaceAliasWithAliasee(), replaceWithConstant(), llvm::CoroIdInst::setCoroutineSelf(), and simplifyRelativeLoad().
getCast()
Constant * ConstantExpr::getCast (unsigned ops, Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Convenience function for getting a Cast operation.
Parameters
ops The opcode for the conversion
C The constant to be converted
Ty The type to which the constant is converted
OnlyIfReduced see getWithOperands() docs.
Definition at line 1973 of file Constants.cpp.
References assert(), llvm::CastInst::castIsValid(), getAddrSpaceCast(), getBitCast(), getFPExtend(), getFPToSI(), getFPToUI(), getFPTrunc(), getIntToPtr(), getPtrToInt(), getSExt(), getSIToFP(), getTrunc(), getUIToFP(), getZExt(), llvm::Instruction::isCast(), and llvm_unreachable.
Referenced by llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadThroughBitcast(), llvm::ConstantFolder::CreateCast(), llvm::TargetFolder::CreateCast(), llvm::orc::createIRTypedAddress(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), getFPCast(), getIntegerCast(), getWithOperands(), lookThroughCast(), OptimizeAwayTrappingUsesOfValue(), simplifyAndOrOfCmps(), simplifyAssocCastAssoc(), and simplifyICmpInst().
getCompare()
Constant * ConstantExpr::getCompare (unsigned short pred, Constant * C1, Constant * C2, bool OnlyIfReduced = false) static
Return an ICmp or FCmp comparison operator constant expression.
Parameters
OnlyIfReduced see getWithOperands() docs.
Definition at line 2419 of file Constants.cpp.
References assert(), C1, llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, getFCmp(), getICmp(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
Referenced by computeUnlikelySuccessors(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFolder::CreateFCmp(), llvm::TargetFolder::CreateFCmp(), llvm::JumpThreadingPass::evaluateOnPredecessorEdge(), llvm::ConstantFolder::FoldICmp(), llvm::TargetFolder::FoldICmp(), llvm::InstCombinerImpl::foldICmpSelectConstant(), llvm::InstCombinerImpl::foldICmpWithConstant(), llvm::InstCombinerImpl::FoldOpIntoSelect(), getWithOperands(), llvm::GCNTTIImpl::instCombineIntrinsic(), and llvm::InstCombinerImpl::visitAnd().
getExactAShr()
static Constant* llvm::ConstantExpr::getExactAShr (Constant * C1, Constant * C2) inline static
Definition at line 1112 of file Constants.h.
References C1.
getExactLogBase2()
Constant * ConstantExpr::getExactLogBase2 (Constant * C) static
If C is a scalar/fixed width vector of known powers of 2, then this function returns a new scalar/fixed width vector obtained from logBase2 of C.
Undef vector elements are set to zero. Return a null pointer otherwise.
Definition at line 2712 of file Constants.cpp.
References E, llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::Constant::getAggregateElement(), llvm::Constant::getNullValue(), llvm::Type::getScalarType(), I, llvm::APInt::isPowerOf2(), llvm::APInt::logBase2(), llvm::PatternMatch::m_APInt(), and llvm::PatternMatch::match().
Referenced by detectShiftUntilBitTestIdiom(), takeLog2(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSDiv().
getExactLShr()
static Constant* llvm::ConstantExpr::getExactLShr (Constant * C1, Constant * C2) inline static
Definition at line 1116 of file Constants.h.
References C1.
getExtractElement()
Constant * ConstantExpr::getExtractElement (Constant * Vec, Constant * Idx, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2573 of file Constants.cpp.
References assert(), llvm::ConstantFoldExtractElementInstruction(), llvm::LLVMContextImpl::ExprConstants, R600_InstFlag::FC, llvm::Value::getContext(), llvm::Value::getType(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), and llvm::LLVMContext::pImpl.
Referenced by BitCastConstantVector(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldExtractElementInstruction(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ConstantFoldUnaryInstruction(), llvm::ConstantFolder::FoldExtractElement(), llvm::TargetFolder::FoldExtractElement(), getWithOperands(), LLVMConstExtractElement(), and simplifyExtractElementInst().
getFCmp()
Constant * ConstantExpr::getFCmp (unsigned short pred, Constant * LHS, Constant * RHS, bool OnlyIfReduced = false) static
Definition at line 2548 of file Constants.cpp.
References assert(), llvm::ConstantFoldCompareInstruction(), llvm::LLVMContextImpl::ExprConstants, R600_InstFlag::FC, llvm::VectorType::get(), llvm::Type::getContext(), llvm::Value::getContext(), llvm::Type::getInt1Ty(), llvm::Value::getType(), llvm::CmpInst::isFPPredicate(), LHS, llvm::LLVMContext::pImpl, pred, and RHS.
Referenced by evaluateFCmpRelation(), getCompare(), and LLVMConstFCmp().
getFPCast()
Constant * ConstantExpr::getFPCast (Constant * C, Type * Ty) static
Create a FPExt, Bitcast or FPTrunc for fp -> fp casts.
Parameters
C The integer constant to be casted
Ty The integer type to cast to
Definition at line 2079 of file Constants.cpp.
References assert(), getCast(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isFPOrFPVectorTy().
Referenced by llvm::ConstantFolder::CreateFPCast(), llvm::TargetFolder::CreateFPCast(), and LLVMConstFPCast().
getFPExtend()
Constant * ConstantExpr::getFPExtend (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2145 of file Constants.cpp.
References assert(), getFoldedCast(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isFPOrFPVectorTy().
Referenced by getCast(), LLVMConstFPExt(), and lookThroughCast().
getFPToSI()
Constant * ConstantExpr::getFPToSI (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2190 of file Constants.cpp.
References assert(), getFoldedCast(), and llvm::Type::isIntOrIntVectorTy().
Referenced by llvm::InstCombinerImpl::foldFCmpIntToFPConst(), getCast(), LLVMConstFPToSI(), lookThroughCast(), and llvm::InstCombinerImpl::visitFAdd().
getFPToUI()
Constant * ConstantExpr::getFPToUI (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2179 of file Constants.cpp.
References assert(), getFoldedCast(), and llvm::Type::isIntOrIntVectorTy().
Referenced by llvm::InstCombinerImpl::foldFCmpIntToFPConst(), getCast(), LLVMConstFPToUI(), and lookThroughCast().
getFPTrunc()
Constant * ConstantExpr::getFPTrunc (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2133 of file Constants.cpp.
References assert(), getFoldedCast(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isFPOrFPVectorTy().
Referenced by getCast(), llvm::AA::getWithType(), LLVMConstFPTrunc(), and lookThroughCast().
getGetElementPtr() [1/3]
static Constant* llvm::ConstantExpr::getGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList, bool InBounds = false, std::optional< unsigned > InRangeIndex = std::nullopt, Type * OnlyIfReducedTy = nullptr) inline static
Getelementptr form.
Value* is only accepted for convenience; all elements must be Constants.
Parameters
InRangeIndex the inrange index if present or std::nullopt.
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 1245 of file Constants.h.
References llvm::ArrayRef(), llvm::ArrayRef< T >::data(), and llvm::ArrayRef< T >::size().
Referenced by BuildConstantFromSCEV(), llvm::ConstantFoldGetElementPtr(), llvm::SanitizerStatReport::create(), llvm::ConstantFolder::FoldGEP(), llvm::TargetFolder::FoldGEP(), foldGEPOfGEP(), getAlignOf(), getOffsetOf(), getSizeOf(), llvm::ScalarEvolution::getSizeOfScalableVectorExpr(), getWithOperands(), LLVMConstGEP2(), OptimizeAwayTrappingUsesOfValue(), simplifyGEPInst(), simplifyRelativeLoad(), and splitGlobal().
getGetElementPtr() [2/3]
Constant * ConstantExpr::getGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList, bool InBounds = false, std::optional< unsigned > InRangeIndex = std::nullopt, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2458 of file Constants.cpp.
References assert(), llvm::ConstantFoldGetElementPtr(), llvm::LLVMContextImpl::ExprConstants, R600_InstFlag::FC, llvm::gep_type_begin(), llvm::gep_type_end(), llvm::VectorType::get(), llvm::PointerType::get(), llvm::PointerType::getAddressSpace(), llvm::Type::getContext(), llvm::ElementCount::getFixed(), llvm::GetElementPtrInst::getIndexedType(), llvm::Type::getPointerTo(), llvm::ConstantVector::getSplat(), llvm::PointerType::isOpaque(), and llvm::PointerType::isOpaqueOrPointeeTypeMatches().
getGetElementPtr() [3/3]
static Constant* llvm::ConstantExpr::getGetElementPtr (Type * Ty, Constant * C, Constant * Idx, bool InBounds = false, std::optional< unsigned > InRangeIndex = std::nullopt, Type * OnlyIfReducedTy = nullptr) inline static
Definition at line 1254 of file Constants.h.
getICmp()
Constant * ConstantExpr::getICmp (unsigned short pred, Constant * LHS, Constant * RHS, bool OnlyIfReduced = false) static
get* - Return some common constants without having to specify the full Instruction::OPCODE identifier.
Definition at line 2523 of file Constants.cpp.
References assert(), llvm::ConstantFoldCompareInstruction(), llvm::LLVMContextImpl::ExprConstants, R600_InstFlag::FC, llvm::VectorType::get(), llvm::Type::getContext(), llvm::Value::getContext(), llvm::Type::getInt1Ty(), llvm::Value::getType(), llvm::CmpInst::isIntPredicate(), LHS, llvm::LLVMContext::pImpl, pred, and RHS.
Referenced by llvm::ConstantFoldCompareInstruction(), evaluateICmpRelation(), getCompare(), getNegativeIsTrueBoolVec(), getUMin(), llvm::Constant::isElementWiseEqual(), LLVMConstICmp(), reassociateMinMaxWithConstants(), llvm::ScalarEvolution::SimplifyICmpOperands(), and llvm::InstCombinerImpl::visitCallInst().
getInBoundsGetElementPtr() [1/3]
static Constant* llvm::ConstantExpr::getInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) inline static
Create an "inbounds" getelementptr.
See the documentation for the "inbounds" flag in LangRef.html for details.
Definition at line 1271 of file Constants.h.
Referenced by llvm::IRBuilderBase::CreateGlobalStringPtr(), FoldBitCast(), llvm::ConstantFolder::FoldGEP(), llvm::TargetFolder::FoldGEP(), and LLVMConstInBoundsGEP2().
getInBoundsGetElementPtr() [2/3]
static Constant* llvm::ConstantExpr::getInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) inline static
Definition at line 1282 of file Constants.h.
getInBoundsGetElementPtr() [3/3]
static Constant* llvm::ConstantExpr::getInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) inline static
Definition at line 1275 of file Constants.h.
getInsertElement()
Constant * ConstantExpr::getInsertElement (Constant * Vec, Constant * Elt, Constant * Idx, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2595 of file Constants.cpp.
References assert(), llvm::ConstantFoldInsertElementInstruction(), llvm::LLVMContextImpl::ExprConstants, R600_InstFlag::FC, llvm::Value::getContext(), llvm::Value::getType(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), and llvm::LLVMContext::pImpl.
Referenced by llvm::ConstantFolder::FoldInsertElement(), llvm::TargetFolder::FoldInsertElement(), llvm::ConstantVector::getSplat(), getWithOperands(), LLVMConstInsertElement(), and llvm::simplifyInsertElementInst().
getIntegerCast()
Constant * ConstantExpr::getIntegerCast (Constant * C, Type * Ty, bool IsSigned) static
Create a ZExt, Bitcast or Trunc for integer -> integer casts.
Parameters
C The integer constant to be casted
Ty The integer type to cast to
IsSigned Whether C should be treated as signed or not
Definition at line 2067 of file Constants.cpp.
References assert(), getCast(), llvm::Type::getScalarSizeInBits(), llvm::Type::isIntOrIntVectorTy(), and isSigned().
Referenced by llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFolder::CreateIntCast(), llvm::TargetFolder::CreateIntCast(), createMalloc(), llvm::emitGEPOffset(), llvm::InstCombinerImpl::EvaluateInDifferentType(), GetConstantInt(), llvm::isBytewiseValue(), LLVMConstIntCast(), lookThroughCast(), llvm::AsmPrinter::lowerConstant(), processUse(), simplifySubInst(), and llvm::InstCombinerImpl::visitCallInst().
getIntToPtr()
Constant * ConstantExpr::getIntToPtr (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2215 of file Constants.cpp.
References assert(), getFoldedCast(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by llvm::SanitizerStatReport::create(), llvm::InstCombinerImpl::foldICmpWithCastOp(), getCast(), llvm::Constant::getIntegerValue(), LLVMConstIntToPtr(), llvm::MergeBasicBlockIntoOnlyPred(), SegmentOffset(), simplifyGEPInst(), simplifyICmpInst(), and llvm::BasicBlock::~BasicBlock().
getLShr()
Constant * ConstantExpr::getLShr (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2702 of file Constants.cpp.
References C1, get(), and llvm::PossiblyExactOperator::IsExact.
Referenced by collectInsertionElements(), llvm::ConstantFoldBinaryInstruction(), dropRedundantMaskingOfLeftShiftInput(), ExtractConstantBytes(), LLVMConstLShr(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
getMul()
Constant * ConstantExpr::getMul (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2671 of file Constants.cpp.
References C1, get(), Mul, llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by BuildConstantFromSCEV(), createMalloc(), llvm::emitGEPOffset(), LLVMConstMul(), and llvm::InstCombinerImpl::visitCallInst().
getNeg()
Constant * ConstantExpr::getNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2644 of file Constants.cpp.
References assert(), getSub(), and llvm::ConstantFP::getZeroValueForNegation().
Referenced by llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::ScalarEvolution::getNegativeSCEV(), LLVMConstNeg(), matchIncrement(), NegateValue(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitSDiv(), and llvm::InstCombinerImpl::visitSRem().
getNot()
Constant * ConstantExpr::getNot (Constant * C) static
Definition at line 2651 of file Constants.cpp.
References assert(), get(), and llvm::Constant::getAllOnesValue().
Referenced by llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCompareInstruction(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::ScalarEvolution::getNotSCEV(), llvm::invertCondition(), LLVMConstNot(), simplifyLogicOfAddSub(), simplifyUsingControlFlow(), llvm::InstCombinerImpl::sinkNotIntoLogicalOp(), llvm::InstCombinerImpl::sinkNotIntoOtherHandOfLogicalOp(), and llvm::InstCombinerImpl::visitXor().
getNSWAdd()
static Constant* llvm::ConstantExpr::getNSWAdd (Constant * C1, Constant * C2) inline static
Definition at line 1080 of file Constants.h.
References C1.
Referenced by LLVMConstNSWAdd().
getNSWMul()
static Constant* llvm::ConstantExpr::getNSWMul (Constant * C1, Constant * C2) inline static
Definition at line 1096 of file Constants.h.
References C1.
Referenced by LLVMConstNSWMul().
getNSWNeg()
static Constant* llvm::ConstantExpr::getNSWNeg (Constant * C) inline static
Definition at line 1077 of file Constants.h.
Referenced by LLVMConstNSWNeg().
getNSWShl()
static Constant* llvm::ConstantExpr::getNSWShl (Constant * C1, Constant * C2) inline static
Definition at line 1104 of file Constants.h.
References C1.
getNSWSub()
static Constant* llvm::ConstantExpr::getNSWSub (Constant * C1, Constant * C2) inline static
Definition at line 1088 of file Constants.h.
References C1.
Referenced by LLVMConstNSWSub().
getNUWAdd()
static Constant* llvm::ConstantExpr::getNUWAdd (Constant * C1, Constant * C2) inline static
Definition at line 1084 of file Constants.h.
References C1.
Referenced by LLVMConstNUWAdd().
getNUWMul()
static Constant* llvm::ConstantExpr::getNUWMul (Constant * C1, Constant * C2) inline static
Definition at line 1100 of file Constants.h.
References C1.
Referenced by LLVMConstNUWMul().
getNUWNeg()
static Constant* llvm::ConstantExpr::getNUWNeg (Constant * C) inline static
Definition at line 1078 of file Constants.h.
Referenced by LLVMConstNUWNeg().
getNUWShl()
static Constant* llvm::ConstantExpr::getNUWShl (Constant * C1, Constant * C2) inline static
Definition at line 1108 of file Constants.h.
References C1.
Referenced by llvm::InstCombinerImpl::foldICmpAndConstConst().
getNUWSub()
static Constant* llvm::ConstantExpr::getNUWSub (Constant * C1, Constant * C2) inline static
Definition at line 1092 of file Constants.h.
References C1.
Referenced by LLVMConstNUWSub().
getOffsetOf() [1/2]
Constant * ConstantExpr::getOffsetOf (StructType * STy, unsigned FieldNo) static
getOffsetOf constant expr - computes the offset of a struct field in a target independent way (Note: the return type is an i64).
Definition at line 2401 of file Constants.cpp.
References llvm::ConstantInt::get(), llvm::Type::getContext(), and llvm::Type::getInt32Ty().
getOffsetOf() [2/2]
Constant * ConstantExpr::getOffsetOf (Type * Ty, Constant * FieldNo) static
getOffsetOf constant expr - This is a generalized form of getOffsetOf, which supports any aggregate type, and any Constant index.
Definition at line 2406 of file Constants.cpp.
References GEP, llvm::ConstantInt::get(), llvm::Type::getContext(), getGetElementPtr(), llvm::Type::getInt64Ty(), llvm::Constant::getNullValue(), getPtrToInt(), and llvm::PointerType::getUnqual().
getOpcode()
unsigned llvm::ConstantExpr::getOpcode () const inline
Return the opcode at the root of this constant expression.
Definition at line 1296 of file Constants.h.
Referenced by evaluateFCmpRelation(), evaluateICmpRelation(), getAsInstruction(), getOpcodeName(), getWithOperands(), isCast(), and isCompare().
getOpcodeName()
const char * ConstantExpr::getOpcodeName () const
Return a string representation for an opcode.
Definition at line 2806 of file Constants.cpp.
References getOpcode(), and llvm::Instruction::getOpcodeName().
getOr()
Constant * ConstantExpr::getOr (Constant * C1, Constant * C2) static
Definition at line 2682 of file Constants.cpp.
References C1, and get().
Referenced by ExtractConstantBytes(), llvm::InstCombinerImpl::foldICmpAndConstConst(), LLVMConstOr(), and llvm::InstCombinerImpl::visitTrunc().
getPointerBitCastOrAddrSpaceCast()
Constant * ConstantExpr::getPointerBitCastOrAddrSpaceCast (Constant * C, Type * Ty) static
Create a BitCast or AddrSpaceCast for a pointer type depending on the address space.
Parameters
C The constant to addrspacecast or bitcast
Ty The type to bitcast or addrspacecast C to
Definition at line 2056 of file Constants.cpp.
References assert(), getAddrSpaceCast(), getBitCast(), llvm::Type::getPointerAddressSpace(), llvm::Type::isPtrOrPtrVectorTy(), and S.
Referenced by appendToUsedList(), llvm::ConstantFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::embedBitcodeInModule(), llvm::OpenMPIRBuilder::emitOffloadingEntry(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::OpenMPIRBuilder::getOrCreateIdent(), and setUsedInitializer().
getPointerCast()
Constant * ConstantExpr::getPointerCast (Constant * C, Type * Ty) static
Create a BitCast, AddrSpaceCast, or a PtrToInt cast constant expression.
Parameters
C The pointer value to be casted (operand 0)
Ty The type to which cast should be made
Definition at line 2041 of file Constants.cpp.
References assert(), getAddrSpaceCast(), getBitCast(), llvm::Type::getPointerAddressSpace(), getPtrToInt(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::isPtrOrPtrVectorTy(), and S.
Referenced by appendToGlobalArray(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFolder::CreatePointerCast(), llvm::TargetFolder::CreatePointerCast(), llvm::OpenMPIRBuilder::getOrCreateSrcLocStr(), llvm::AA::getWithType(), INITIALIZE_PASS(), LLVMConstPointerCast(), and setCoroInfo().
getPredicate()
unsigned ConstantExpr::getPredicate () const
Return the ICMP or FCMP predicate value.
Assert if this is not an ICMP or FCMP constant expression.
Definition at line 1452 of file Constants.cpp.
Referenced by getAsInstruction(), and getWithOperands().
getPtrToInt()
Constant * ConstantExpr::getPtrToInt (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2201 of file Constants.cpp.
References assert(), getFoldedCast(), and llvm::Type::isIntOrIntVectorTy().
Referenced by BuildConstantFromSCEV(), llvm::ConstantFoldCastOperand(), llvm::copyNonnullMetadata(), createRelLookupTable(), getAlignOf(), getCast(), getOffsetOf(), llvm::Value::getPointerAlignment(), getPointerCast(), getSizeOf(), llvm::ScalarEvolution::getSizeOfScalableVectorExpr(), and LLVMConstPtrToInt().
getSelect()
Constant * ConstantExpr::getSelect (Constant * C, Constant * V1, Constant * V2, Type * OnlyIfReducedTy = nullptr) static
Select constant expr.
Parameters
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 2441 of file Constants.cpp.
References llvm::SelectInst::areInvalidOperands(), assert(), llvm::ConstantFoldSelectInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::Value::getType(), llvm::PPCISD::SC, Select, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by cloneConstantExprWithNewAddressSpace(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFolder::FoldSelect(), llvm::TargetFolder::FoldSelect(), getUMin(), getWithOperands(), LLVMConstSelect(), and reassociateMinMaxWithConstants().
getSExt()
Constant * ConstantExpr::getSExt (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2105 of file Constants.cpp.
References assert(), getFoldedCast(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isIntOrIntVectorTy().
Referenced by BuildConstantFromSCEV(), llvm::ConstantFoldGetElementPtr(), foldLogicCastConstant(), foldNoWrapAdd(), getCast(), getSExtOrBitCast(), getSExtOrTrunc(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::GCNTTIImpl::instCombineIntrinsic(), LLVMConstSExt(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitSExt().
getSExtOrBitCast()
Constant * ConstantExpr::getSExtOrBitCast (Constant * C, Type * Ty) static
Parameters
C The constant to sext or bitcast
Ty The type to sext or bitcast C to
Definition at line 2018 of file Constants.cpp.
References getBitCast(), llvm::Type::getScalarSizeInBits(), and getSExt().
Referenced by llvm::ConstantFolder::CreateSExtOrBitCast(), llvm::TargetFolder::CreateSExtOrBitCast(), foldGEPOfGEP(), and LLVMConstSExtOrBitCast().
getSExtOrTrunc()
Constant * ConstantExpr::getSExtOrTrunc (Constant * C, Type * Ty) static
Create either an sext, trunc or nothing, depending on whether Ty is wider, narrower or the same as C->getType().
This only works with integer or vector of integer types.
Definition at line 2030 of file Constants.cpp.
References assert(), llvm::Type::getScalarSizeInBits(), getSExt(), getTrunc(), and llvm::Type::isIntOrIntVectorTy().
Referenced by getAsConstantIndexedAddress().
getShl()
Constant * ConstantExpr::getShl (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2695 of file Constants.cpp.
References C1, get(), llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by ConvertShiftToMul(), dropRedundantMaskingOfLeftShiftInput(), getAlternateBinop(), getBinOpsForFactorization(), LLVMConstShl(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitShl(), and llvm::InstCombinerImpl::visitTrunc().
getShuffleMask()
ArrayRef< int > ConstantExpr::getShuffleMask () const
Assert that this is a shufflevector and return the mask.
See class ShuffleVectorInst for a description of the mask representation.
Definition at line 1456 of file Constants.cpp.
Referenced by getAsInstruction(), and getWithOperands().
getShuffleMaskForBitcode()
Constant * ConstantExpr::getShuffleMaskForBitcode () const
Assert that this is a shufflevector and return the mask.
TODO: This is a temporary hack until we update the bitcode format for shufflevector.
Definition at line 1460 of file Constants.cpp.
getShuffleVector()
Constant * ConstantExpr::getShuffleVector (Constant * V1, Constant * V2, ArrayRef< int > Mask, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2618 of file Constants.cpp.
References assert(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::LLVMContextImpl::ExprConstants, R600_InstFlag::FC, llvm::VectorType::get(), llvm::Type::getContext(), llvm::Value::getType(), llvm::ShuffleVectorInst::isValidOperands(), llvm::BitmaskEnumDetail::Mask(), llvm::LLVMContext::pImpl, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by evaluateInDifferentElementOrder(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::ConstantFolder::FoldShuffleVector(), llvm::TargetFolder::FoldShuffleVector(), llvm::ConstantVector::getSplat(), getWithOperands(), LLVMConstShuffleVector(), and simplifyShuffleVectorInst().
getSIToFP()
Constant * ConstantExpr::getSIToFP (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2168 of file Constants.cpp.
References assert(), getFoldedCast(), and llvm::Type::isFPOrFPVectorTy().
Referenced by llvm::InstCombinerImpl::foldFCmpIntToFPConst(), getCast(), LLVMConstSIToFP(), lookThroughCast(), and llvm::InstCombinerImpl::visitFAdd().
getSizeOf()
Constant * ConstantExpr::getSizeOf (Type * Ty) static
getSizeOf constant expr - computes the (alloc) size of a type (in address-units, not bits) in a target independent way (Note: the return type is an i64).
Definition at line 2378 of file Constants.cpp.
References GEP, llvm::ConstantInt::get(), llvm::Type::getContext(), getGetElementPtr(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Constant::getNullValue(), getPtrToInt(), and llvm::PointerType::getUnqual().
Referenced by llvm::IRBuilderBase::CreatePtrDiff(), LLVMBuildArrayMalloc(), LLVMBuildMalloc(), and LLVMSizeOf().
getSub()
Constant * ConstantExpr::getSub (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2664 of file Constants.cpp.
References C1, get(), llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by llvm::InstCombinerImpl::commonShiftTransforms(), llvm::ConstantFoldCastOperand(), createRelLookupTable(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), getNeg(), LLVMConstSub(), llvm::InstCombiner::SubOne(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitSub(), and llvm::InstCombinerImpl::visitSwitchInst().
getTrunc()
Constant * ConstantExpr::getTrunc (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2091 of file Constants.cpp.
References assert(), getFoldedCast(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isIntOrIntVectorTy().
Referenced by BuildConstantFromSCEV(), collectInsertionElements(), llvm::ConstantFoldCompareInstruction(), createRelLookupTable(), dropRedundantMaskingOfLeftShiftInput(), ExtractConstantBytes(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldLogicCastConstant(), llvm::InstCombinerImpl::foldPHIArgZextsIntoPHI(), getCast(), getSExtOrTrunc(), llvm::ScalarEvolution::getTruncateExpr(), getTruncOrBitCast(), llvm::AA::getWithType(), LLVMConstTrunc(), lookThroughCast(), narrowUDivURem(), simplifyICmpInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitSDiv(), and llvm::InstCombinerImpl::visitTrunc().
getTruncOrBitCast()
Constant * ConstantExpr::getTruncOrBitCast (Constant * C, Type * Ty) static
Parameters
C The constant to trunc or bitcast
Ty The type to trunc or bitcast C to
Definition at line 2024 of file Constants.cpp.
References getBitCast(), llvm::Type::getScalarSizeInBits(), and getTrunc().
Referenced by llvm::ConstantFolder::CreateTruncOrBitCast(), llvm::TargetFolder::CreateTruncOrBitCast(), LLVMBuildArrayMalloc(), LLVMBuildMalloc(), and LLVMConstTruncOrBitCast().
getUIToFP()
Constant * ConstantExpr::getUIToFP (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2157 of file Constants.cpp.
References assert(), getFoldedCast(), and llvm::Type::isFPOrFPVectorTy().
Referenced by llvm::InstCombinerImpl::foldFCmpIntToFPConst(), getCast(), LLVMConstUIToFP(), and lookThroughCast().
getUMin()
Constant * ConstantExpr::getUMin (Constant * C1, Constant * C2) static
Definition at line 2690 of file Constants.cpp.
References C1, getICmp(), getSelect(), and llvm::CmpInst::ICMP_ULT.
Referenced by llvm::InstCombinerImpl::visitTrunc().
getWithOperands() [1/2]
Constant* llvm::ConstantExpr::getWithOperands (ArrayRef< Constant * > Ops) const inline
This returns the current constant expression with the operands replaced with the specified values.
The specified array must have the same number of operands as our current one.
Definition at line 1318 of file Constants.h.
References getType().
getWithOperands() [2/2]
Constant * ConstantExpr::getWithOperands (ArrayRef< Constant * > Ops, Type * Ty, bool OnlyIfReduced = false, Type * SrcTy = nullptr) const
Get the current expression with the operands replaced.
Return the current constant expression with the operands replaced with Ops and the type with Ty. The new operands must have the same number as the current ones.
If OnlyIfReduced is true, nullptr will be returned unless something gets constant-folded, the type changes, or the expression is otherwise canonicalized. This parameter should almost always be false.
Definition at line 1464 of file Constants.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::lltok::equal, get(), getCast(), getCompare(), getExtractElement(), getGetElementPtr(), getInsertElement(), llvm::User::getNumOperands(), getOpcode(), llvm::User::getOperand(), getPredicate(), getSelect(), getShuffleMask(), getShuffleVector(), llvm::Value::getType(), llvm::User::op_begin(), Select, llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), and llvm::Value::SubclassOptionalData.
getXor()
Constant * ConstantExpr::getXor (Constant * C1, Constant * C2) static
Definition at line 2686 of file Constants.cpp.
References C1, and get().
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), LLVMConstXor(), and llvm::InstCombinerImpl::visitXor().
getZExt()
Constant * ConstantExpr::getZExt (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2119 of file Constants.cpp.
References assert(), getFoldedCast(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isIntOrIntVectorTy().
Referenced by BuildConstantFromSCEV(), dropRedundantMaskingOfLeftShiftInput(), foldLogicCastConstant(), foldNoWrapAdd(), llvm::InstCombinerImpl::foldPHIArgZextsIntoPHI(), getCast(), llvm::ScalarEvolution::getZeroExtendExprImpl(), getZExtOrBitCast(), LLVMConstZExt(), narrowUDivURem(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitZExt().
getZExtOrBitCast()
Constant * ConstantExpr::getZExtOrBitCast (Constant * C, Type * Ty) static
Parameters
C The constant to zext or bitcast
Ty The type to zext or bitcast C to
Definition at line 2012 of file Constants.cpp.
References getBitCast(), llvm::Type::getScalarSizeInBits(), and getZExt().
Referenced by llvm::ConstantFolder::CreateZExtOrBitCast(), llvm::TargetFolder::CreateZExtOrBitCast(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), LLVMConstZExtOrBitCast(), and llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts().
isCast()
bool ConstantExpr::isCast () const
Return true if this is a convert constant expression.
Definition at line 1444 of file Constants.cpp.
References getOpcode(), and llvm::Instruction::isCast().
isCompare()
bool ConstantExpr::isCompare () const
Return true if this is a compare constant expression.
Definition at line 1448 of file Constants.cpp.
References getOpcode().
isDesirableBinOp()
bool ConstantExpr::isDesirableBinOp (unsigned Opcode) static
Whether creating a constant expression for this binary operator is desirable.
Definition at line 2324 of file Constants.cpp.
References llvm::MCID::Add, llvm_unreachable, and Mul.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFolder::FoldBinOp(), llvm::TargetFolder::FoldBinOp(), llvm::ConstantFolder::FoldExactBinOp(), llvm::TargetFolder::FoldExactBinOp(), llvm::ConstantFolder::FoldNoWrapBinOp(), and llvm::TargetFolder::FoldNoWrapBinOp().
isSupportedBinOp()
bool ConstantExpr::isSupportedBinOp (unsigned Opcode) static
Whether creating a constant expression for this binary operator is supported.
Definition at line 2351 of file Constants.cpp.
References llvm::MCID::Add, llvm_unreachable, and Mul.
Referenced by get().
Friends And Related Function Documentation
Constant
friend class Constant friend
Definition at line 1000 of file Constants.h.
ConstantExprKeyType
friend struct ConstantExprKeyType friend
Definition at line 999 of file Constants.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Constants.h
lib/IR/Constants.cpp