LLVM: llvm::Type Class Reference
llvm::Type Class Reference
The instances of the Type class are immutable: once they are created, they are never changed.
#include "llvm/IR/Type.h"
Public Types
enum TypeID {
HalfTyID = 0, BFloatTyID, FloatTyID, DoubleTyID,
X86_FP80TyID, FP128TyID, PPC_FP128TyID, VoidTyID,
LabelTyID, MetadataTyID, X86_MMXTyID, X86_AMXTyID,
TokenTyID, IntegerTyID, FunctionTyID, PointerTyID,
StructTyID, ArrayTyID, FixedVectorTyID, ScalableVectorTyID,
TypedPointerTyID, TargetExtTyID
}
Definitions of all of the base types for the Type system.
using subtype_iterator = Type *const *
using subtype_reverse_iterator = std::reverse_iterator< subtype_iterator >
Public Member Functions
void print (raw_ostream &O, bool IsForDebug=false, bool NoDetails=false) const
Print the current type.
void dump () const
LLVMContext & getContext () const
Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
Return the type id for the type.
bool isVoidTy () const
Return true if this is 'void'.
bool isHalfTy () const
Return true if this is 'half', a 16-bit IEEE fp type.
bool isBFloatTy () const
Return true if this is 'bfloat', a 16-bit bfloat type.
bool is16bitFPTy () const
Return true if this is a 16-bit float type.
bool isFloatTy () const
Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
Return true if this is x86 long double.
bool isFP128Ty () const
Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
Return true if this is powerpc long double.
bool isIEEELikeFPTy () const
Return true if this is a well-behaved IEEE-like type, which has a IEEE compatible layout as defined by isIEEE(), and does not have unnormal values.
bool isFloatingPointTy () const
Return true if this is one of the floating-point types.
bool isMultiUnitFPType () const
Returns true if this is a floating-point type that is an unevaluated sum of multiple floating-point units.
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
Return true if this is X86 MMX.
bool isX86_AMXTy () const
Return true if this is X86 AMX.
bool isTargetExtTy () const
Return true if this is a target extension type.
bool isFPOrFPVectorTy () const
Return true if this is a FP type or a vector of FP.
bool isLabelTy () const
Return true if this is 'label'.
bool isMetadataTy () const
Return true if this is 'metadata'.
bool isTokenTy () const
Return true if this is 'token'.
bool isIntegerTy () const
True if this is an instance of IntegerType.
bool isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
Return true if this is an integer type or a vector of integer types.
bool isIntOrIntVectorTy (unsigned BitWidth) const
Return true if this is an integer type or a vector of integer types of the given width.
bool isIntOrPtrTy () const
Return true if this is an integer type or a pointer type.
bool isFunctionTy () const
True if this is an instance of FunctionType.
bool isStructTy () const
True if this is an instance of StructType.
bool isArrayTy () const
True if this is an instance of ArrayType.
bool isPointerTy () const
True if this is an instance of PointerType.
bool isOpaquePointerTy () const
True if this is an instance of an opaque PointerType.
bool isPtrOrPtrVectorTy () const
Return true if this is a pointer type or a vector of pointer types.
bool isVectorTy () const
True if this is an instance of VectorType.
bool canLosslesslyBitCastTo (Type *Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
bool isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
bool isFirstClassType () const
Return true if the type is "first class", meaning it is a valid type for a Value.
bool isSingleValueType () const
Return true if the type is a valid type for a register in codegen.
bool isAggregateType () const
Return true if the type is an aggregate type.
bool isSized (SmallPtrSetImpl< Type * > *Visited=nullptr) const
Return true if it makes sense to take the size of this type.
TypeSize getPrimitiveSizeInBits () const LLVM_READONLY
Return the basic size of this type if it is a primitive type.
unsigned getScalarSizeInBits () const LLVM_READONLY
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
int getFPMantissaWidth () const
Return the width of the mantissa of this type.
bool isIEEE () const
Return whether the type is IEEE compatible, as defined by the eponymous method in APFloat.
Type * getScalarType () const
If this is a vector type, return the element type, otherwise return 'this'.
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
This method is used to implement the type iterator (defined at the end of the file).
unsigned getNumContainedTypes () const
Return the number of types in the derived type.
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
StringRef getTargetExtName () const
Type * getPointerElementType () const
This method is deprecated without replacement.
Type * getNonOpaquePointerElementType () const
Only use this method in code that is not reachable with opaque pointers, or part of deprecated methods that will be removed as part of the opaque pointers transition.
Type * getWithNewType (Type *EltTy) const
Given vector type, change the element type, whilst keeping the old number of elements.
Type * getWithNewBitWidth (unsigned NewBitWidth) const
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
Type * getExtendedType () const
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0) const
Return a pointer to the current type.
Static Public Member Functions
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getBFloatTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static Type * getX86_AMXTy (LLVMContext &C)
static Type * getTokenTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static IntegerType * getInt128Ty (LLVMContext &C)
template<typename ScalarTy >
static Type * getScalarTy (LLVMContext &C)
static Type * getFloatingPointTy (LLVMContext &C, const fltSemantics &S)
static PointerType * getHalfPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getBFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getDoublePtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_FP80PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getPPC_FP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_MMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_AMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getIntNPtrTy (LLVMContext &C, unsigned N, unsigned AS=0)
static PointerType * getInt1PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt8PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt16PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt32PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt64PtrTy (LLVMContext &C, unsigned AS=0)
Protected Member Functions
Type (LLVMContext &C, TypeID tid)
~Type ()=default
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Protected Attributes
unsigned NumContainedTys = 0
Keeps track of how many Type*'s there are in the ContainedTys list.
Type *const * ContainedTys = nullptr
A pointer to the array of Types contained by this Type.
Friends
class LLVMContextImpl
Detailed Description
The instances of the Type class are immutable: once they are created, they are never changed.
Also note that only one instance of a particular type is ever created. Thus seeing if two types are equal is a matter of doing a trivial pointer comparison. To enforce that no two equal instances are created, Type instances can only be created via static factory methods in class Type and in derived classes. Once allocated, Types are never free'd.
Definition at line 45 of file Type.h.
Member Typedef Documentation
subtype_iterator
using llvm::Type::subtype_iterator = Type * const *
Definition at line 350 of file Type.h.
subtype_reverse_iterator
using llvm::Type::subtype_reverse_iterator = std::reverse_iterator<subtype_iterator>
Definition at line 358 of file Type.h.
Member Enumeration Documentation
TypeID
enum llvm::Type::TypeID
Definitions of all of the base types for the Type system.
Based on this value, you can cast to a class defined in DerivedTypes.h. Note: If you add an element to this, you need to add an element to the Type::getPrimitiveType function, or else things will break! Also update LLVMTypeKind and LLVMGetTypeKind () in the C binding.
Enumerator
HalfTyID
16-bit floating point type
BFloatTyID
16-bit floating point type (7-bit significand)
FloatTyID
32-bit floating point type
DoubleTyID
64-bit floating point type
X86_FP80TyID
80-bit floating point type (X87)
FP128TyID
128-bit floating point type (112-bit significand)
PPC_FP128TyID
128-bit floating point type (two 64-bits, PowerPC)
VoidTyID
type with no size
LabelTyID
Labels.
MetadataTyID
Metadata.
X86_MMXTyID
MMX vectors (64 bits, X86 specific)
X86_AMXTyID
AMX vectors (8192 bits, X86 specific)
TokenTyID
Tokens.
IntegerTyID
Arbitrary bit width integers.
FunctionTyID
Functions.
PointerTyID
Pointers.
StructTyID
Structures.
ArrayTyID
Arrays.
FixedVectorTyID
Fixed width SIMD vector type.
ScalableVectorTyID
Scalable SIMD vector type.
TypedPointerTyID
Typed pointer used by some GPU targets.
TargetExtTyID
Target extension type.
Definition at line 54 of file Type.h.
Constructor & Destructor Documentation
Type()
llvm::Type::Type (LLVMContext & C, TypeID tid) inline explicit protected
Definition at line 94 of file Type.h.
Referenced by llvm::object::MinidumpFile::create().
~Type()
llvm::Type::~Type () protected default
Member Function Documentation
canLosslesslyBitCastTo()
bool Type::canLosslesslyBitCastTo (Type * Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
For example, i8* to i32*. BitCasts are valid for types of the same size only where no re-interpretation of the bits is done. Determine if this type could be losslessly bitcast to Ty
Definition at line 104 of file Type.cpp.
References llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), getPrimitiveSizeInBits(), isFirstClassType(), isX86_AMXTy(), and isX86_MMXTy().
dump()
LLVM_DUMP_METHOD void Type::dump () const
Definition at line 4946 of file AsmWriter.cpp.
References llvm::dbgs(), and print().
Referenced by llvm::coro::Shape::buildFrom(), and llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters().
getArrayElementType()
Type* llvm::Type::getArrayElementType () const inline
Definition at line 397 of file Type.h.
References ArrayTyID, assert(), ContainedTys, and getTypeID().
Referenced by llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters(), isConstantUsingVectorTy(), llvm::InstCombinerImpl::visitGEPOfBitcast(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and llvm::WebAssembly::wasmSymbolSetType().
getArrayNumElements()
uint64_t llvm::Type::getArrayNumElements () const inline
Definition at line 384 of file DerivedTypes.h.
Referenced by llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), llvm::getConstantDataArrayInfo(), scalarConstantToHexString(), and llvm::InstCombinerImpl::visitGEPOfBitcast().
getBFloatPtrTy()
PointerType * Type::getBFloatPtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 253 of file Type.cpp.
References getBFloatTy(), and getPointerTo().
getBFloatTy()
Type * Type::getBFloatTy (LLVMContext & C) static
Definition at line 227 of file Type.cpp.
Referenced by DecodeFixedType(), getBFloatPtrTy(), llvm::IRBuilderBase::getBFloatTy(), getFloatingPointTy(), getPrimitiveType(), getSVEContainerIRType(), llvm::EVT::getTypeForEVT(), LLVMBFloatTypeInContext(), and UpgradeIntrinsicFunction1().
getContainedType()
Type* llvm::Type::getContainedType (unsigned i) const inline
This method is used to implement the type iterator (defined at the end of the file).
For derived types, this returns the types 'contained' in the derived type.
Definition at line 370 of file Type.h.
References assert(), ContainedTys, i, and NumContainedTys.
Referenced by llvm::X86TTIImpl::getIntrinsicInstrCost(), getScalarType(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), and llvm::TargetExtType::getTypeParameter().
getContext()
LLVMContext& llvm::Type::getContext () const inline
Return the LLVMContext in which this type was uniqued.
Definition at line 129 of file Type.h.
References Context.
Referenced by llvm::SPIRVGlobalRegistry::buildConstantFP(), buildScalarSteps(), llvm::VNCoercion::coerceAvailableValueToLoadType(), llvm::convertPointerToIntegerType(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), llvm::StructType::create(), llvm::MatrixBuilder::CreateIndex(), llvm::orc::createIRTypedAddress(), llvm::FunctionLoweringInfo::CreateRegs(), findElementAtOffset(), llvm::FlushFPConstant(), FoldBitCast(), foldConstantCastPair(), foldGEPOfGEP(), llvm::TypedPointerType::get(), llvm::InlineAsm::get(), llvm::ConstantInt::get(), llvm::StructType::get(), llvm::ConstantFP::get(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantVector::get(), llvm::FixedVectorType::get(), llvm::ScalableVectorType::get(), llvm::PointerType::get(), llvm::ConstantExpr::getAlignOf(), llvm::Constant::getAllOnesValue(), llvm::AArch64TTIImpl::getArithmeticReductionCostSVE(), llvm::AAValueConstantRange::getAssumedConstant(), llvm::AAPotentialConstantValues::getAssumedConstant(), llvm::VNCoercion::getConstantMemInstValueForLoad(), llvm::BasicBlock::getContext(), llvm::Function::getContext(), llvm::Value::getContext(), llvm::EVT::getEVT(), llvm::IntegerType::getExtendedType(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFCmp(), getFoldedCast(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::ConstantDataSequential::getImpl(), llvm::DataLayout::getIndexType(), llvm::ConstantFP::getInfinity(), llvm::VectorType::getInteger(), llvm::Constant::getIntegerValue(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::DataLayout::getIntPtrType(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::VNCoercion::getLoadValueForLoad(), llvm::VNCoercion::getMemInstValueForLoad(), llvm::TargetLoweringBase::getMemValueType(), llvm::AArch64TTIImpl::getMinMaxReductionCost(), llvm::ConstantFP::getNaN(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getOffsetOf(), llvm::dxil::DXILOpBuilder::getOverloadTy(), getPromotedType(), llvm::ConstantFP::getQNaN(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getRegUsageForType(), llvm::X86TTIImpl::getReplicationShuffleCost(), llvm::coro::Shape::getResumeFunctionType(), getReturnAttrs(), llvm::CallLowering::getReturnInfo(), llvm::getRuntimeVFAsFloat(), llvm::ConstantExpr::getShuffleVector(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantFP::getSNaN(), llvm::ConstantVector::getSplat(), llvm::AArch64TTIImpl::getSpliceCost(), getStepVector(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getStoreMinimumVF(), llvm::VNCoercion::getStoreValueForLoadHelper(), getSVEContainerIRType(), getTargetTypeInfo(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTreeReductionCost(), llvm::ConstantInt::getTrue(), llvm::VectorType::getTruncatedElementVectorType(), getTypeFromParameterKind(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeLegalizationCost(), getTypePartition(), llvm::TargetLoweringBase::getValueType(), llvm::LoopVectorizationCostModel::getVectorCallCost(), getWithNewBitWidth(), llvm::PointerType::getWithSamePointeeType(), llvm::ConstantFP::getZero(), llvm::ValueAsMetadata::handleDeletion(), hasLifetimeMarkers(), llvm::CallLowering::insertSRetIncomingArgument(), IsIncrementNSW(), IsIncrementNUW(), llvm::InductionDescriptor::isInductionPHI(), isIntegerWideningViable(), llvm::X86TTIImpl::isLegalBroadcastLoad(), isVectorPromotionViableForSlice(), LLVMConstIntOfArbitraryPrecision(), llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::AArch64CallLowering::lowerReturn(), llvm::CmpInst::makeCmpResultType(), memVTFromLoadIntrData(), llvm::TargetLowering::ParseConstraints(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::StructType::setBody(), setInfoSVEStN(), llvm::StructType::setName(), llvm::ARMTargetLowering::shouldConvertSplatType(), simplifyGEPInst(), solveTypeName(), llvm::CallLowering::splitToValueTypes(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), tryToFPToSat(), and llvm::MetadataAsValue::~MetadataAsValue().
getDoublePtrTy()
PointerType * Type::getDoublePtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 261 of file Type.cpp.
References getDoubleTy(), and getPointerTo().
getDoubleTy()
Type * Type::getDoubleTy (LLVMContext & C) static
Definition at line 229 of file Type.cpp.
Referenced by convertImplicitDefToConstZero(), DecodeFixedType(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ConstantDataVector::get(), getDoublePtrTy(), llvm::IRBuilderBase::getDoubleTy(), getFloatingPointTy(), getFloatTypeForLLT(), getIntrinsicParamType(), getKeyFPValMD(), llvm::dxil::DXILOpBuilder::getOverloadTy(), getPrimitiveType(), getScalarTy(), getSVEContainerIRType(), llvm::EVT::getTypeForEVT(), getTypeFromParameterKind(), llvm::X86TTIImpl::isLegalBroadcastLoad(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), LLVMDoubleTypeInContext(), LowerFPToInt(), ReplaceFPIntrinsicWithCall(), and shrinkFPConstant().
getExtendedType()
Type * llvm::Type::getExtendedType () const inline
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
For vectors, preserves element count.
Definition at line 706 of file DerivedTypes.h.
References assert(), llvm::VectorType::getExtendedElementVectorType(), and isIntOrIntVectorTy().
Referenced by dropRedundantMaskingOfLeftShiftInput().
getFloatingPointTy()
Type * Type::getFloatingPointTy (LLVMContext & C, const fltSemantics & S) static
Definition at line 83 of file Type.cpp.
References assert(), llvm::APFloatBase::BFloat(), getBFloatTy(), getDoubleTy(), getFloatTy(), getFP128Ty(), getHalfTy(), getPPC_FP128Ty(), getX86_FP80Ty(), llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm::APFloatBase::PPCDoubleDouble(), S, and llvm::APFloatBase::x87DoubleExtended().
Referenced by llvm::ConstantFP::get().
getFloatPtrTy()
PointerType * Type::getFloatPtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 257 of file Type.cpp.
References getFloatTy(), and getPointerTo().
getFloatTy()
Type * Type::getFloatTy (LLVMContext & C) static
Definition at line 228 of file Type.cpp.
Referenced by llvm::SPIRVGlobalRegistry::buildConstantFP(), convertImplicitDefToConstZero(), llvm::MDBuilder::createFPMath(), DecodeFixedType(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ConstantDataVector::get(), getFloatingPointTy(), getFloatPtrTy(), llvm::IRBuilderBase::getFloatTy(), getFloatTypeForLLT(), getIntrinsicParamType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVTypeByName(), llvm::dxil::DXILOpBuilder::getOverloadTy(), getPrimitiveType(), getScalarTy(), getSVEContainerIRType(), llvm::VectorType::getTruncatedElementVectorType(), llvm::EVT::getTypeForEVT(), getTypeFromParameterKind(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), LLVMFloatTypeInContext(), LowerFPToInt(), ReplaceFPIntrinsicWithCall(), shrinkFPConstant(), and UpgradePTESTIntrinsic().
getFltSemantics()
const fltSemantics & Type::getFltSemantics () const
Definition at line 66 of file Type.cpp.
References llvm::APFloatBase::BFloat(), BFloatTyID, DoubleTyID, FloatTyID, FP128TyID, getTypeID(), HalfTyID, llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), llvm::APFloatBase::IEEEquad(), llvm::APFloatBase::IEEEsingle(), llvm_unreachable, PPC_FP128TyID, llvm::APFloatBase::PPCDoubleDouble(), X86_FP80TyID, and llvm::APFloatBase::x87DoubleExtended().
Referenced by canEvaluateTruncated(), llvm::ConstantFoldCastInstruction(), llvm::TargetLowering::expandIS_FPCLASS(), llvm::FlushFPConstant(), FoldBitCast(), fpModeMatchesGlobalFPAtomicMode(), llvm::ConstantFP::get(), llvm::Constant::getAllOnesValue(), llvm::ConstantFP::getInfinity(), llvm::ConstantFP::getNaN(), llvm::Constant::getNullValue(), llvm::ConstantFP::getQNaN(), llvm::ConstantFP::getSNaN(), llvm::ConstantFP::getZero(), llvm::GCNTTIImpl::instCombineIntrinsic(), isIEEE(), llvm::isKnownNeverInfinity(), isSaturatingMinMax(), and llvm::InstCombinerImpl::visitFAdd().
getFP128PtrTy()
PointerType * Type::getFP128PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 269 of file Type.cpp.
References getFP128Ty(), and getPointerTo().
getFP128Ty()
Type * Type::getFP128Ty (LLVMContext & C) static
Definition at line 233 of file Type.cpp.
Referenced by DecodeFixedType(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getFloatingPointTy(), getFloatTypeForLLT(), getFP128PtrTy(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), and LLVMFP128TypeInContext().
getFPMantissaWidth()
int Type::getFPMantissaWidth () const
Return the width of the mantissa of this type.
This is only valid on floating-point types. If the FP type does not have a stable mantissa (e.g. ppc long double), this method returns -1.
Definition at line 193 of file Type.cpp.
References assert(), BFloatTyID, DoubleTyID, FloatTyID, FP128TyID, getTypeID(), HalfTyID, isFloatingPointTy(), PPC_FP128TyID, and X86_FP80TyID.
Referenced by expandIToFP(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), isKnownExactCastIntToFP(), shrinkFPConstantVector(), and llvm::InstCombinerImpl::visitFPTrunc().
getFunctionNumParams()
unsigned llvm::Type::getFunctionNumParams () const inline
Definition at line 157 of file DerivedTypes.h.
getFunctionParamType()
Type * llvm::Type::getFunctionParamType (unsigned i) const inline
Definition at line 153 of file DerivedTypes.h.
References i.
Referenced by llvm::isLegalToPromote().
getHalfPtrTy()
PointerType * Type::getHalfPtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 249 of file Type.cpp.
References getHalfTy(), and getPointerTo().
getHalfTy()
Type * Type::getHalfTy (LLVMContext & C) static
Definition at line 226 of file Type.cpp.
Referenced by convertTo16Bit(), DecodeFixedType(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getFloatingPointTy(), getFloatTypeForLLT(), getHalfPtrTy(), llvm::IRBuilderBase::getHalfTy(), getIntrinsicParamType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVTypeByName(), llvm::dxil::DXILOpBuilder::getOverloadTy(), getPrimitiveType(), getSVEContainerIRType(), llvm::VectorType::getTruncatedElementVectorType(), llvm::EVT::getTypeForEVT(), getTypeFromParameterKind(), LLVMHalfTypeInContext(), shrinkFPConstant(), and simplifyAMDGCNImageIntrinsic().
getInt128Ty()
IntegerType * Type::getInt128Ty (LLVMContext & C) static
Definition at line 243 of file Type.cpp.
Referenced by llvm::IntegerType::get(), llvm::IRBuilderBase::getInt128Ty(), llvm::EVT::getTypeForEVT(), and LLVMInt128TypeInContext().
getInt16PtrTy()
PointerType * Type::getInt16PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 297 of file Type.cpp.
References getInt16Ty(), and getPointerTo().
getInt16Ty()
IntegerType * Type::getInt16Ty (LLVMContext & C) static
Definition at line 240 of file Type.cpp.
Referenced by convertTo16Bit(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), getInt16PtrTy(), llvm::IRBuilderBase::getInt16Ty(), getIntrinsicParamType(), llvm::GCNTTIImpl::getMemcpyLoopLoweringType(), llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType(), llvm::dxil::DXILOpBuilder::getOverloadTy(), getSVEContainerIRType(), llvm::EVT::getTypeForEVT(), getTypeFromParameterKind(), llvm::isBytewiseValue(), LLVMInt16TypeInContext(), llvm::ARMTargetLowering::shouldConvertSplatType(), and simplifyAMDGCNImageIntrinsic().
getInt1PtrTy()
PointerType * Type::getInt1PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 289 of file Type.cpp.
References getInt1Ty(), and getPointerTo().
Referenced by llvm::InstCombinerImpl::CreateNonTerminatorUnreachable(), and llvm::SCEVExpander::getIVIncOperand().
getInt1Ty()
IntegerType * Type::getInt1Ty (LLVMContext & C) static
Definition at line 238 of file Type.cpp.
Referenced by llvm::OpenMPIRBuilder::applySimd(), llvm::SelectInst::areInvalidOperands(), calcPredicateUsingBooleans(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCompareInstruction(), CreateAssert(), llvm::MDBuilder::createCallbackEncoding(), llvm::sampleprofutil::createFSDiscriminatorVariable(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedScatter(), DisableAllLoopOptsOnLoop(), llvm::IntegerType::get(), llvm::ConstantExpr::getAlignOf(), llvm::LoopVectorizationCostModel::getDivRemSpeculationCost(), getEdgeValueLocal(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFCmp(), llvm::ConstantExpr::getICmp(), getInt1PtrTy(), llvm::IRBuilderBase::getInt1Ty(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::dxil::DXILOpBuilder::getOverloadTy(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTreeReductionCost(), llvm::ConstantInt::getTrue(), llvm::EVT::getTypeForEVT(), getTypeFromParameterKind(), llvm::LoopVectorizationCostModel::getVectorCallCost(), instCombineSVECmpNE(), LLVMInt1TypeInContext(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::CmpInst::makeCmpResultType(), llvm::InsertCFGStrategy::mutate(), OptimizeGlobalAddressOfAllocation(), rewrite(), setAssignmentTrackingModuleFlag(), TryToShrinkGlobalToBoolean(), UpgradeIntrinsicFunction1(), and llvm::InstCombinerImpl::visitAllocSite().
getInt32PtrTy()
PointerType * Type::getInt32PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 301 of file Type.cpp.
References getInt32Ty(), and getPointerTo().
getInt32Ty()
IntegerType * Type::getInt32Ty (LLVMContext & C) static
Definition at line 241 of file Type.cpp.
Referenced by llvm::Module::addModuleFlag(), adjustInliningThresholdUsingCallee(), llvm::annotateValueSite(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::SPIRVGlobalRegistry::buildConstantInt(), calcPredicateUsingInteger(), calculateVectorIndex(), OutlinableGroup::collectGVNStoreSets(), llvm::ConstantFoldInsertElementInstruction(), llvm::convertPointerToIntegerType(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), llvm::ARMConstantPoolConstant::Create(), llvm::MDBuilder::createBranchWeights(), llvm::ARMTargetLowering::createComplexDeinterleavingIR(), llvm::IRBuilderBase::CreateConstGEP1_32(), llvm::IRBuilderBase::CreateConstGEP2_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_32(), llvm::OpenMPIRBuilder::createGlobalFlag(), llvm::IRBuilderBase::CreateGlobalStringPtr(), llvm::OpenMPIRBuilder::createOffloadEntry(), llvm::OpenMPIRBuilder::createParallel(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::IRBuilderBase::CreatePreserveStructAccessIndex(), createRelLookupTable(), llvm::OpenMPIRBuilder::createSections(), createStringMetadata(), createSwitchStatement(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::OpenMPIRBuilder::emitOffloadingEntry(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), evaluateInDifferentElementOrder(), findCostForOutputBlocks(), llvm::SanitizerStatReport::finish(), FoldBitCast(), foldInsSequenceIntoSplat(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), getAISize(), llvm::ConstantExpr::getAlignOf(), getDefaultPersonalityFn(), llvm::CSKYInstrInfo::getGlobalBaseReg(), getInt32PtrTy(), llvm::IRBuilderBase::getInt32Ty(), getIntrinsicParamType(), llvm::X86TargetLowering::getIRStackGuard(), llvm::GCNTTIImpl::getMemcpyLoopLoweringType(), llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType(), getOffsetFromIndices(), llvm::ConstantExpr::getOffsetOf(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVTypeByName(), llvm::dxil::DXILOpBuilder::getOverloadTy(), getPromotedType(), getResRetType(), llvm::ConstantExpr::getSizeOf(), getSVEContainerIRType(), llvm::EVT::getTypeForEVT(), getTypeFromParameterKind(), INITIALIZE_PASS(), insertCall(), llvm::BPFCoreSharedInfo::insertPassThrough(), llvm::ARMTTIImpl::instCombineIntrinsic(), instCombineRDFFR(), instCombineSVECmpNE(), llvm::isBytewiseValue(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::libcall(), LLVMBuildArrayMalloc(), LLVMBuildMalloc(), LLVMInt32TypeInContext(), llvm::XCoreInstrInfo::loadImmediate(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerLoadRelative(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::EscapeEnumerator::Next(), replaceCalledFunction(), llvm::KCFIPass::run(), runImpl(), runPass(), SegmentOffset(), llvm::setKCFIType(), llvm::ARMTargetLowering::shouldConvertSplatType(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyRelativeLoad(), splitGlobal(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::OpenMPIRBuilder::unrollLoopPartial(), llvm::CallInst::updateProfWeight(), validExtractValueIndex(), validInsertValueIndex(), validShuffleVectorIndex(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitGEPOfGEP(), llvm::InstCombinerImpl::visitShuffleVectorInst(), and llvm::BasicBlock::~BasicBlock().
getInt64PtrTy()
PointerType * Type::getInt64PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 305 of file Type.cpp.
References getInt64Ty(), and getPointerTo().
Referenced by llvm::OpenMPIRBuilder::emitOffloadingArraysArgument().
getInt64Ty()
IntegerType * Type::getInt64Ty (LLVMContext & C) static
Definition at line 242 of file Type.cpp.
Referenced by addModuleFlags(), llvm::GlobalObject::addTypeMetadata(), llvm::annotateValueSite(), llvm::memprof::buildCallstackMetadata(), llvm::MDBuilder::createCallbackEncoding(), llvm::IRBuilderBase::CreateConstGEP1_64(), llvm::IRBuilderBase::CreateConstGEP2_64(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_64(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_64(), llvm::MDBuilder::createFunctionEntryCount(), createIRLevelProfileFlagVar(), llvm::MDBuilder::createIrrLoopHeaderWeight(), llvm::orc::createIRTypedAddress(), llvm::MDBuilder::createLLVMStats(), llvm::MDBuilder::createPseudoProbeDesc(), llvm::IRBuilderBase::CreatePtrDiff(), llvm::MDBuilder::createTBAAAccessTag(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::MDBuilder::createTBAATypeNode(), llvm::orc::IRSpeculationLayer::emit(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitHiddenKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), llvm::PPCTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::PPCTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::OpenMPIRBuilder::emitOffloadingArraysArgument(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), foldConstantCastPair(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), llvm::ConstantExpr::getAlignOf(), getInt64PtrTy(), llvm::IRBuilderBase::getInt64Ty(), getIntrinsicParamType(), llvm::X86TargetLowering::getIRStackGuard(), getKeyValMD(), llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType(), llvm::ConstantExpr::getOffsetOf(), llvm::DIBuilder::getOrCreateSubrange(), llvm::dxil::DXILOpBuilder::getOverloadTy(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantVector::getSplat(), llvm::InstrProfIncrementInst::getStep(), getSVEContainerIRType(), llvm::EVT::getTypeForEVT(), getTypeFromParameterKind(), llvm::InlineFunction(), insertLifetimeMarkersSurroundingCall(), instCombineSVEDup(), instCombineSVELast(), instrumentOneFunc(), llvm::isBytewiseValue(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::LegalizerHelper::libcall(), LLVMInt64TypeInContext(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::GlobalObject::setVCallVisibilityMetadata(), llvm::AArch64TTIImpl::shouldConsiderAddressTypePromotion(), simplifyRelativeLoad(), simplifyX86extrq(), unpackLoadToAggregate(), unpackStoreToAggregate(), llvm::CallInst::updateProfWeight(), and llvm::InstCombinerImpl::visitCallInst().
getInt8PtrTy()
PointerType * Type::getInt8PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 293 of file Type.cpp.
References getInt8Ty(), and getPointerTo().
Referenced by llvm::addRuntimeChecks(), appendToUsedList(), BuildConstantFromSCEV(), llvm::coro::Shape::buildFrom(), llvm::CoroIdInst::clearPromise(), createFree(), CreateGCRelocates(), createMalloc(), llvm::createMemLibcall(), llvm::OpenMPIRBuilder::createOMPInteropDestroy(), llvm::OpenMPIRBuilder::createOMPInteropInit(), llvm::OpenMPIRBuilder::createOMPInteropUse(), llvm::OpenMPIRBuilder::createParallel(), CreatePrologue(), llvm::OpenMPIRBuilder::createTask(), llvm::AsmPrinter::doFinalization(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitHiddenKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::PPCTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::PPCTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::OpenMPIRBuilder::emitOffloadingArraysArgument(), llvm::OpenMPIRBuilder::emitOffloadingEntry(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), expandBounds(), llvm::CodeExtractor::findAllocas(), llvm::SanitizerStatReport::finish(), llvm::TargetLoweringBase::getDefaultSafeStackPointerLocation(), getFreshReductionFunc(), getFuncAddrForProfData(), getHandleType(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::TargetLoweringBase::getIRStackGuard(), llvm::SCEVExpander::getIVIncOperand(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), getTargetTypeInfo(), hasLifetimeMarkers(), insertCall(), insertLifetimeMarkersSurroundingCall(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::PPCTargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), llvm::TargetLoweringBase::insertSSPDeclarations(), instrumentOneFunc(), llvm::TargetLowering::LowerToTLSEmulatedModel(), LowerToTLSExecModel(), llvm::EscapeEnumerator::Next(), RemovePreallocated(), replaceAsyncResumeFunction(), llvm::coro::replaceCoroFree(), llvm::ExecutionEngine::runFunctionAsMain(), runImpl(), llvm::SanitizerStatReport::SanitizerStatReport(), SegmentOffset(), setCoroInfo(), llvm::CoroIdInst::setCoroutineSelf(), setUsedInitializer(), simplifyRelativeLoad(), splitAsyncCoroutine(), tryToShorten(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getInt8Ty()
IntegerType * Type::getInt8Ty (LLVMContext & C) static
Definition at line 239 of file Type.cpp.
Referenced by llvm::memtag::alignAndPadAlloca(), BuildConstantFromSCEV(), checkAsyncContextProjectFunction(), classifyConstantWithOpaquePtr(), createGlobalFwdRef(), llvm::OpenMPIRBuilder::createOffloadMapnames(), llvm::OpenMPIRBuilder::createTargetDeinit(), llvm::OpenMPIRBuilder::createTargetInit(), llvm::embedBitcodeInModule(), llvm::orc::IRSpeculationLayer::emit(), llvm::IntegerType::get(), llvm::ConstantDataVector::get(), llvm::SelectionDAG::getEVTAlign(), getInt8PtrTy(), llvm::IRBuilderBase::getInt8Ty(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), getIntrinsicParamType(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::TargetTransformInfoImplBase::getMemcpyLoopLoweringType(), llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType(), llvm::dxil::DXILOpBuilder::getOverloadTy(), getPointerOperandAndType(), getSVEContainerIRType(), llvm::EVT::getTypeForEVT(), getTypeFromParameterKind(), getValueOrUndef(), INITIALIZE_PASS(), llvm::isBytewiseValue(), llvm::InductionDescriptor::isInductionPHI(), LLVMInt8TypeInContext(), llvm::AArch64CallLowering::lowerCall(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), lowerLoadRelative(), llvm::coro::LowererBase::makeSubFnCall(), OptimizeGlobalAddressOfAllocation(), runImpl(), llvm::AtomicMemIntrinsic::setElementSizeInBytes(), splitAsyncCoroutine(), tryToOptimizeStoreOfAllocationToGlobal(), and tryToShorten().
getIntegerBitWidth()
unsigned llvm::Type::getIntegerBitWidth () const inline
Definition at line 97 of file DerivedTypes.h.
Referenced by canBeCheaplyTransformed(), canonicalizeForInvariantConditionInjection(), checkOverflow(), ConvertShiftToMul(), llvm::emitGEPOffset(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), expandFPToI(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), foldGEPOfGEP(), llvm::InstCombinerImpl::foldICmpWithCastOp(), generateSignedDivisionCode(), generateSignedRemainderCode(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), getEdgeValueLocal(), llvm::ARMTTIImpl::getIntImmCostInst(), getKmpcForDynamicFiniForType(), getKmpcForDynamicInitForType(), getKmpcForDynamicNextForType(), getKmpcForStaticInitForType(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getTypeName(), llvm::DataLayout::getTypeSizeInBits(), getValueFromSimpleICmpCondition(), llvm::PPCTTIImpl::hasActiveVectorLength(), hasSameExtUse(), llvm::HexagonEvaluator::HexagonEvaluator(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), isLoadCombineCandidateImpl(), llvm::ConstantInt::isValueValidForType(), lowerFunnelShifts(), narrowSDivOrSRem(), narrowUDivOrURem(), processAShr(), llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm(), simplifyX86varShift(), unpackFromRegLoc(), llvm::OpenMPIRBuilder::unrollLoopPartial(), llvm::InstCombinerImpl::visitExtractElementInst(), and llvm::InstCombinerImpl::visitFAdd().
getIntNPtrTy()
PointerType * Type::getIntNPtrTy (LLVMContext & C, unsigned N, unsigned AS = 0) static
Definition at line 285 of file Type.cpp.
References getIntNTy(), getPointerTo(), and N.
Referenced by getAddrPtrType().
getIntNTy()
IntegerType * Type::getIntNTy (LLVMContext & C, unsigned N) static
Definition at line 245 of file Type.cpp.
References llvm::IntegerType::get(), and N.
Referenced by computeRecurrenceType(), llvm::ConstantFoldGetElementPtr(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), createMaskInstrs(), foldGEPOfGEP(), getConstantVector(), llvm::IntegerType::getExtendedType(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), getIntNPtrTy(), llvm::IRBuilderBase::getIntNTy(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::DataLayout::getLargestLegalIntType(), getMemCmpLoad(), llvm::GCNTTIImpl::getMemcpyLoopLoweringType(), llvm::TargetTransformInfoImplBase::getMemcpyLoopLoweringType(), llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType(), llvm::X86TTIImpl::getReplicationShuffleCost(), getScalarTy(), llvm::DataLayout::getSmallestLegalIntType(), llvm::ScalarEvolution::getTripCountFromExitCount(), llvm::EVT::getTypeForEVT(), getWithNewBitWidth(), inlineGetBaseAndOffset(), llvm::isBytewiseValue(), lowerBuildVectorAsBroadcast(), makeStatepointExplicitImpl(), narrowSDivOrSRem(), narrowUDivOrURem(), and llvm::recognizeBSwapOrBitReverseIdiom().
getLabelTy()
Type * Type::getLabelTy (LLVMContext & C) static
Definition at line 225 of file Type.cpp.
Referenced by getPrimitiveType(), and LLVMLabelTypeInContext().
getMetadataTy()
Type * Type::getMetadataTy (LLVMContext & C) static
Definition at line 230 of file Type.cpp.
Referenced by DecodeFixedType(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), LLVMMetadataTypeInContext(), llvm::ValueEnumerator::ValueEnumerator(), and llvm::dxil::ValueEnumerator::ValueEnumerator().
getNonOpaquePointerElementType()
Type* llvm::Type::getNonOpaquePointerElementType () const inline
Only use this method in code that is not reachable with opaque pointers, or part of deprecated methods that will be removed as part of the opaque pointers transition.
Definition at line 416 of file Type.h.
References assert(), ContainedTys, getTypeID(), NumContainedTys, and PointerTyID.
Referenced by llvm::ConstantFoldGetElementPtr(), convertBitCastToGEP(), createGlobalFwdRef(), findElementAtOffset(), llvm::RandomIRBuilder::findPointer(), FoldBitCast(), getPointerElementType(), llvm::getTypedPtrEltType(), llvm::InductionDescriptor::isInductionPHI(), isSafeToEliminateVarargsCast(), matchIntrinsicType(), llvm::InstCombinerImpl::PromoteCastOfAllocation(), solveTypeName(), llvm::InstCombinerImpl::visitGEPOfBitcast(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
getNumContainedTypes()
unsigned llvm::Type::getNumContainedTypes () const inline
Return the number of types in the derived type.
Definition at line 376 of file Type.h.
References NumContainedTys.
Referenced by llvm::TargetExtType::getNumTypeParameters().
getPointerAddressSpace()
unsigned llvm::Type::getPointerAddressSpace () const inline
Get the address space of this pointer or pointer vector type.
Definition at line 729 of file DerivedTypes.h.
References getScalarType().
Referenced by llvm::NVPTXAAResult::alias(), llvm::AMDGPUAAResult::alias(), annotateDereferenceableBytes(), annotateNonNullNoUndefBasedOnAccess(), llvm::VNCoercion::canCoerceMustAliasedValueToLoad(), canConvertValue(), llvm::castToCStr(), classifyConstantWithOpaquePtr(), classifyGlobalCtorPointerType(), cloneConstantExprWithNewAddressSpace(), llvm::orc::cloneGlobalAliasDecl(), llvm::ConstantFoldCastOperand(), convertValue(), createMemMoveLoop(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::InstCombinerImpl::foldICmpWithCastOp(), getAccessType(), llvm::IntToPtrInst::getAddressSpace(), llvm::AMDGPUTargetMachine::getAssumedAddrSpace(), llvm::CastInst::getCastOpcode(), llvm::AddrSpaceCastOperator::getDestAddressSpace(), llvm::AddrSpaceCastInst::getDestAddressSpace(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionCost(), llvm::VNCoercion::getLoadValueForLoad(), llvm::NVPTXAAResult::getModRefInfoMask(), llvm::AMDGPUAAResult::getModRefInfoMask(), llvm::Module::getOrInsertGlobal(), llvm::LoadInst::getPointerAddressSpace(), llvm::StoreInst::getPointerAddressSpace(), llvm::GEPOperator::getPointerAddressSpace(), llvm::AtomicCmpXchgInst::getPointerAddressSpace(), llvm::AtomicRMWInst::getPointerAddressSpace(), llvm::GetElementPtrInst::getPointerAddressSpace(), llvm::PtrToIntInst::getPointerAddressSpace(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), llvm::getPointersDiff(), llvm::getPtrStride(), llvm::AddrSpaceCastOperator::getSrcAddressSpace(), llvm::AddrSpaceCastInst::getSrcAddressSpace(), llvm::DataLayout::getTypeSizeInBits(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getValueKind(), hasLifetimeMarkers(), inlineGetBaseAndOffset(), llvm::AA::isAssumedThreadLocalObject(), isCompatibleIVType(), llvm::CastInst::isEliminableCastPair(), llvm::WebAssembly::isExternrefType(), llvm::WebAssembly::isFuncrefType(), isKnownNonNullFromDominatingCondition(), isKnownNonZeroFromAssume(), llvm::AMDGPU::isLDSVariableToLower(), isUnsupportedAMDGPUAddrspace(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileCOFF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), llvm::MachinePointerInfo::MachinePointerInfo(), maybePrintCallAddrSpace(), optimizeMemCmpConstantSize(), optimizeOnceStoredGlobal(), PrintResults(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::CallLowering::setArgFlags(), shouldBeMustTail(), shouldInstrumentReadWriteFromAddress(), simplifyInvariantGroupIntrinsic(), tryToShorten(), llvm::UpgradeBitCastExpr(), llvm::UpgradeBitCastInst(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::InstCombinerImpl::visitAllocaInst(), llvm::InstCombinerImpl::visitGEPOfBitcast(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
getPointerElementType()
Type* llvm::Type::getPointerElementType () const inline
This method is deprecated without replacement.
Pointer element types are not available with opaque pointers.
Definition at line 409 of file Type.h.
References getNonOpaquePointerElementType().
getPointerTo()
PointerType * Type::getPointerTo (unsigned AddrSpace = 0) const
Return a pointer to the current type.
This is equivalent to PointerType::get(Foo, AddrSpace). TODO: Remove this after opaque pointer transition is complete.
Definition at line 776 of file Type.cpp.
References llvm::PointerType::get().
Referenced by buildFrameType(), llvm::InstCombinerImpl::combineLoadToNewType(), combineStoreToNewValue(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicWrite(), createByteGEP(), createCmpXchgInstFun(), createFramePtr(), llvm::OpenMPIRBuilder::createOffloadMapnames(), llvm::OpenMPIRBuilder::createReductions(), llvm::OpenMPIRBuilder::createTask(), llvm::embedBitcodeInModule(), llvm::orc::IRSpeculationLayer::emit(), emitSetSwiftErrorValue(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::VPWidenMemoryInstructionRecipe::execute(), foldConsecutiveLoads(), llvm::ConstantExpr::getAlignOf(), getBFloatPtrTy(), getDoublePtrTy(), getFloatPtrTy(), getFP128PtrTy(), llvm::ConstantExpr::getGetElementPtr(), getHalfPtrTy(), getInt16PtrTy(), getInt1PtrTy(), getInt32PtrTy(), getInt64PtrTy(), getInt8PtrTy(), getIntNPtrTy(), getIntrinsicParamType(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), getPPC_FP128PtrTy(), llvm::GlobalIFunc::getResolverFunctionType(), llvm::coro::Shape::getResumeFunctionType(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), llvm::ScalarEvolution::getSizeOfScalableVectorExpr(), getX86_AMXPtrTy(), getX86_FP80PtrTy(), getX86_MMXPtrTy(), insertCall(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), instCombineSVELD1(), instCombineSVEST1(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedStore(), lowerLoadRelative(), lowerSubFn(), optimizeMemCmpConstantSize(), rewriteGEPAsOffset(), llvm::ExecutionEngine::runFunctionAsMain(), scalarizeMaskedLoad(), scalarizeMaskedStore(), SegmentOffset(), simplifyRelativeLoad(), splitMergedValStore(), splitRetconCoroutine(), tryPromoteAllocaToVector(), UseTlsOffset(), useTpOffset(), and llvm::InnerLoopVectorizer::vectorizeInterleaveGroup().
getPPC_FP128PtrTy()
PointerType * Type::getPPC_FP128PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 273 of file Type.cpp.
References getPointerTo(), and getPPC_FP128Ty().
getPPC_FP128Ty()
Type * Type::getPPC_FP128Ty (LLVMContext & C) static
Definition at line 234 of file Type.cpp.
Referenced by DecodeFixedType(), getFloatingPointTy(), getPPC_FP128PtrTy(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), LLVMPPCFP128TypeInContext(), and shrinkFPConstant().
getPrimitiveSizeInBits()
TypeSize Type::getPrimitiveSizeInBits () const
Return the basic size of this type if it is a primitive type.
These are fixed by LLVM and are not target-dependent. This will return zero if the type does not have a size or is not a primitive type.
If this is a scalable vector type, the scalable property will be set and the runtime size will be a positive integer multiple of the base size.
Note that this may not reflect the size of memory allocated for an instance of the type or the number of bytes that are written when an instance of the type is stored to memory. The DataLayout class provides additional query functions to provide this information.
Definition at line 163 of file Type.cpp.
References assert(), BFloatTyID, DoubleTyID, llvm::TypeSize::Fixed(), FixedVectorTyID, FloatTyID, FP128TyID, getBitWidth(), llvm::VectorType::getElementCount(), llvm::VectorType::getElementType(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), getPrimitiveSizeInBits(), getTypeID(), HalfTyID, IntegerTyID, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), PPC_FP128TyID, ScalableVectorTyID, X86_AMXTyID, X86_FP80TyID, and X86_MMXTyID.
Referenced by llvm::HexagonTargetLowering::allowTruncateForTailCall(), llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), areExtractShuffleVectors(), llvm::PPCTTIImpl::areTypesABICompatible(), llvm::ARMTargetLowering::canCombineStoreAndExtract(), canLosslesslyBitCastTo(), canWidenLoad(), llvm::CastInst::castIsValid(), CheckAndCreateOffsetAdd(), collectInsertionElements(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::ConstantFoldCastInstruction(), convertStrToInt(), createCmpXchgInstFun(), llvm::createTripCountSCEV(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPPERMMask(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::PPCTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::PPCTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::extractConstantMask(), FoldBitCast(), foldCastShuffle(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::InstCombinerImpl::foldICmpEquality(), foldIdentityExtractShuffle(), foldLoadsRecursive(), foldVecTruncToExtElt(), llvm::AArch64TargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::CastInst::getCastOpcode(), llvm::ExecutionEngine::getConstantValue(), llvm::ConstantDataSequential::getElementByteSize(), llvm::VectorType::getInteger(), llvm::SystemZTTIImpl::getIntImmCost(), llvm::PPCTTIImpl::getIntImmCost(), llvm::LanaiTTIImpl::getIntImmCost(), llvm::AArch64TTIImpl::getIntImmCost(), llvm::ARMTTIImpl::getIntImmCost(), llvm::X86TTIImpl::getIntImmCost(), llvm::SystemZTTIImpl::getIntImmCostInst(), llvm::PPCTTIImpl::getIntImmCostInst(), llvm::AArch64TTIImpl::getIntImmCostInst(), llvm::X86TTIImpl::getIntImmCostInst(), llvm::SystemZTTIImpl::getIntImmCostIntrin(), llvm::PPCTTIImpl::getIntImmCostIntrin(), llvm::AArch64TTIImpl::getIntImmCostIntrin(), llvm::X86TTIImpl::getIntImmCostIntrin(), llvm::VNCoercion::getLoadLoadClobberFullWidthSize(), llvm::HexagonTTIImpl::getMemoryOpCost(), getPrimitiveSizeInBits(), llvm::NVPTXTargetLowering::getPrototype(), getScalarSizeInBits(), llvm::X86TTIImpl::getShuffleCost(), getTargetConstantBitsFromNode(), llvm::VectorType::getTruncatedElementVectorType(), getTypeSizeIndex(), llvm::SystemZTTIImpl::getVectorTruncCost(), llvm::AA::getWithType(), hasTocDataAttr(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::CastInst::isBitCastable(), llvm::ARMTTIImpl::isLegalMaskedLoad(), isMMAType(), isMultipleOfTypeSize(), llvm::MSP430TargetLowering::isTruncateFree(), llvm::RISCVTargetLowering::isTruncateFree(), llvm::ARMTargetLowering::isTruncateFree(), llvm::SystemZTargetLowering::isTruncateFree(), llvm::NVPTXTargetLowering::isTruncateFree(), llvm::AArch64TargetLowering::isTruncateFree(), llvm::PPCTargetLowering::isTruncateFree(), llvm::X86TargetLowering::isTruncateFree(), llvm::AArch64TargetLowering::isZExtFree(), LowerCTLZ(), LowerCTPOP(), matchType(), optimizeVectorResizeWithIntegerBitCasts(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), llvm::replaceAllDbgUsesWith(), llvm::SCEVExpander::replaceCongruentIVs(), scalarConstantToHexString(), scalarizeMaskedLoad(), scalarizeMaskedStore(), llvm::ARMTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::AArch64TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::PPCTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::X86TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::LoongArchTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::RISCVTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::ARMTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::PPCTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::HexagonTargetLowering::shouldExpandAtomicLoadInIR(), llvm::ARMTargetLowering::shouldExpandAtomicLoadInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicLoadInIR(), llvm::LoongArchTargetLowering::shouldExpandAtomicRMWInIR(), llvm::SparcTargetLowering::shouldExpandAtomicRMWInIR(), llvm::RISCVTargetLowering::shouldExpandAtomicRMWInIR(), llvm::ARMTargetLowering::shouldExpandAtomicRMWInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicRMWInIR(), llvm::PPCTargetLowering::shouldExpandAtomicRMWInIR(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), simplifyICmpInst(), simplifyX86immShift(), simplifyX86pack(), SwitchToLookupTable(), upgradeAVX512MaskToSelect(), UpgradeMaskedLoad(), UpgradeX86VPERMT2Intrinsics(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and llvm::InstCombinerImpl::visitPHINode().
getPrimitiveType()
Type * Type::getPrimitiveType (LLVMContext & C, TypeID IDNumber) static
Return a type based on an identifier.
Definition at line 36 of file Type.cpp.
References BFloatTyID, DoubleTyID, FloatTyID, FP128TyID, getBFloatTy(), getDoubleTy(), getFloatTy(), getFP128Ty(), getHalfTy(), getLabelTy(), getMetadataTy(), getPPC_FP128Ty(), getTokenTy(), getVoidTy(), getX86_AMXTy(), getX86_FP80Ty(), getX86_MMXTy(), HalfTyID, LabelTyID, MetadataTyID, PPC_FP128TyID, TokenTyID, VoidTyID, X86_AMXTyID, X86_FP80TyID, and X86_MMXTyID.
getScalarSizeInBits()
unsigned Type::getScalarSizeInBits () const
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
Otherwise return the getPrimitiveSizeInBits value for this type.
Definition at line 188 of file Type.cpp.
References llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), getPrimitiveSizeInBits(), and getScalarType().
Referenced by llvm::addDiffRuntimeChecks(), buildScalarSteps(), canEvaluateSExtd(), canEvaluateShiftedShift(), canEvaluateTruncated(), canEvaluateZExtd(), canonicalizeAbs(), canonicalizeLogicFirst(), canScalarizeAccess(), canTryToConstantAddTwoShiftAmounts(), llvm::CastInst::castIsValid(), CheckAndCreateOffsetAdd(), collectBitParts(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::computeConstantRange(), llvm::SelectionDAG::computeKnownBits(), llvm::ComputeMaxSignificantBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::computeOverflowForSignedMul(), llvm::ConstantFoldGetElementPtr(), llvm::convertPointerToIntegerType(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::ARMTargetLowering::createComplexDeinterleavingIR(), llvm::AArch64TargetLowering::createComplexDeinterleavingIR(), llvm::CastInst::CreateFPCast(), llvm::MatrixBuilder::CreateIndex(), llvm::MatrixBuilder::CreateIndexAssumption(), llvm::CastInst::CreateIntegerCast(), llvm::CastInst::CreateSExtOrBitCast(), llvm::IRBuilderBase::CreateSExtOrTrunc(), llvm::IRBuilderBase::CreateStepVector(), llvm::CastInst::CreateTruncOrBitCast(), llvm::CastInst::CreateZExtOrBitCast(), llvm::IRBuilderBase::CreateZExtOrTrunc(), despeculateCountZeros(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::foldAddWithConstant(), foldCtpop(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpSRemConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithTrunc(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), llvm::InstCombinerImpl::foldItoFPtoI(), foldSelectICmpAndAnd(), foldSelectICmpAndOr(), foldSelectICmpLshrAshr(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), llvm::InstCombinerImpl::foldSignBitTest(), foldSignedTruncationCheck(), foldTruncInsEltPair(), foldTruncShuffle(), generateCreationChecksForBinOp(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::RISCVTTIImpl::getArithmeticInstrCost(), llvm::RISCVTTIImpl::getArithmeticReductionCost(), getBitWidth(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::RISCVTTIImpl::getCmpSelInstrCost(), getConstantRange(), llvm::ExecutionEngine::getConstantValue(), getElSizeLog2Diff(), llvm::RISCVTTIImpl::getExtendedReductionCost(), llvm::IntegerType::getExtendedType(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), llvm::ConstantExpr::getFPTrunc(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionCost(), llvm::ConstantExpr::getIntegerCast(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::GCNTTIImpl::getLoadVectorFactor(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::RISCVTTIImpl::getMinMaxReductionCost(), llvm::getRuntimeVFAsFloat(), llvm::MinMaxIntrinsic::getSaturationPoint(), llvm::X86TTIImpl::getScalarizationOverhead(), getScalarSizeInBits(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSExtOrBitCast(), llvm::ConstantExpr::getSExtOrTrunc(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes(), getStepVector(), getTargetConstantBitsFromNode(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::ConstantExpr::getTrunc(), llvm::ConstantExpr::getTruncOrBitCast(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), getValueFromICmpCondition(), llvm::SystemZTTIImpl::getVectorBitmaskConversionCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::RISCVTTIImpl::getVectorInstrCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::SystemZTTIImpl::getVectorTruncCost(), llvm::getWiderType(), llvm::ConstantExpr::getZExt(), llvm::ConstantExpr::getZExtOrBitCast(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::X86TargetLowering::isCheapToSpeculateCttz(), llvm::CastInst::isEliminableCastPair(), llvm::SystemZTTIImpl::isFoldableLoad(), isKnownExactCastIntToFP(), isKnownToBeAPowerOfTwo(), llvm::AArch64TTIImpl::isLegalBroadcastLoad(), llvm::ARMTTIImpl::isLegalMaskedGather(), llvm::ARMTTIImpl::isLegalMaskedLoad(), isMaskedStoreOverwrite(), isMMAType(), llvm::CastInst::isNoopCast(), llvm::AMDGPUTargetLowering::isTruncateFree(), isVectorLaneType(), llvm::X86TargetLowering::isVectorShiftByScalarCheap(), llvm::AMDGPUTargetLowering::isZExtFree(), LowerBSWAP(), matchIntPart(), matchOrConcat(), llvm::TargetTransformInfoImplBase::minRequiredElementSize(), llvm::ARMTTIImpl::preferInLoopReduction(), processAbsIntrinsic(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::salvageDebugInfoImpl(), simplifyAndInst(), simplifyAShrInst(), llvm::InstCombinerImpl::SimplifyDemandedInstructionBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::simplifyShrShlDemandedBits(), simplifyUnaryIntrinsic(), simplifyX86pack(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), tryToRecognizePopCount(), tryToRecognizeTableBasedCttz(), UpgradeARMIntrinsicCall(), upgradeAVX512MaskToSelect(), UpgradeX86VPERMT2Intrinsics(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitIntToPtr(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitPtrToInt(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), and llvm::reassociate::XorOpnd::XorOpnd().
getScalarTy()
template<typename ScalarTy > static Type* llvm::Type::getScalarTy (LLVMContext & C) inline static
Definition at line 470 of file Type.h.
References getDoubleTy(), getFloatTy(), getIntNTy(), and llvm_unreachable.
getScalarType()
Type* llvm::Type::getScalarType () const inline
If this is a vector type, return the element type, otherwise return 'this'.
Definition at line 341 of file Type.h.
References getContainedType(), and isVectorTy().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), buildScalarSteps(), llvm::VNCoercion::canCoerceMustAliasedValueToLoad(), canConvertValue(), llvm::CastInst::castIsValid(), checkType(), computeKnownBits(), computeKnownBitsFromOperator(), ComputeNumSignBitsImpl(), concatenateTwoVectors(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::IRBuilderBase::CreateStepVector(), llvm::emitGEPOffset(), evaluateInDifferentElementOrder(), llvm::VPReductionPHIRecipe::execute(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldVectorBinop(), fpModeMatchesGlobalFPAtomicMode(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::TargetTransformInfoImplBase::getArithmeticInstrCost(), getCmpOpsType(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCmpSelInstrCost(), llvm::ConstantExpr::getExactLogBase2(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::ConstantFP::getInfinity(), llvm::Constant::getIntegerValue(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::AArch64TTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::ConstantFP::getNaN(), getPointerAddressSpace(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::ConstantFP::getQNaN(), llvm::PPCTTIImpl::getRegisterClassForType(), llvm::RISCVTTIImpl::getRegisterClassForType(), getScalarSizeInBits(), llvm::VPWidenCanonicalIVRecipe::getScalarType(), llvm::SystemZTTIImpl::getShuffleCost(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::ConstantFP::getSNaN(), getStepVector(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::RISCVTTIImpl::getVectorInstrCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getVectorInstrCost(), llvm::ConstantFP::getZero(), hasSameExtUse(), llvm::haveNoCommonBitsSet(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::CastInst::isEliminableCastPair(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), isFPOrFPVectorTy(), isIntOrIntVectorTy(), llvm::isKnownNeverInfinity(), isKnownNonZero(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::RISCVTTIImpl::isLegalMaskedGatherScatter(), llvm::AArch64TTIImpl::isLegalMaskedGatherScatter(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::RISCVTTIImpl::isLegalMaskedLoadStore(), llvm::AArch64TTIImpl::isLegalMaskedLoadStore(), isPtrOrPtrVectorTy(), llvm::HexagonSubtarget::isTypeForHVX(), optimizeCallInst(), llvm::ARMTargetLowering::shouldConvertSplatType(), shrinkInsertElt(), simplifyAMDGCNImageIntrinsic(), upgradeX86ConcatShift(), upgradeX86Rotate(), llvm::InstCombinerImpl::visitAddrSpaceCast(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitFAdd(), visitMaskedMerge(), llvm::InstCombinerImpl::visitPtrToInt(), and llvm::InstCombinerImpl::visitXor().
getStructElementType()
Type * llvm::Type::getStructElementType (unsigned N) const inline
Definition at line 352 of file DerivedTypes.h.
References N.
Referenced by createCast(), isConstantUsingVectorTy(), llvm::MipsCCState::originalTypeIsF128(), and simplifyX86addcarry().
getStructName()
StringRef llvm::Type::getStructName () const inline
Definition at line 344 of file DerivedTypes.h.
Referenced by false::operator<<(), and solveTypeName().
getStructNumElements()
unsigned llvm::Type::getStructNumElements () const inline
Definition at line 348 of file DerivedTypes.h.
Referenced by createCast(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), llvm::ConstantAggregateZero::getElementCount(), llvm::UndefValue::getNumElements(), isConstantUsingVectorTy(), and llvm::MipsCCState::originalTypeIsF128().
getSubclassData()
unsigned llvm::Type::getSubclassData () const inline protected
Definition at line 98 of file Type.h.
Referenced by llvm::TypedPointerType::getAddressSpace(), llvm::PointerType::getAddressSpace(), llvm::IntegerType::getBitWidth(), llvm::TargetExtType::getNumIntParameters(), llvm::StructType::isLiteral(), llvm::StructType::isOpaque(), llvm::StructType::isPacked(), llvm::StructType::isSized(), llvm::FunctionType::isVarArg(), llvm::StructType::setBody(), and setSubclassData().
getTargetExtName()
StringRef llvm::Type::getTargetExtName () const inline
Definition at line 806 of file DerivedTypes.h.
getTokenTy()
Type * Type::getTokenTy (LLVMContext & C) static
Definition at line 231 of file Type.cpp.
Referenced by DecodeFixedType(), getPrimitiveType(), LLVMBuildCatchSwitch(), LLVMBuildCleanupPad(), and LLVMTokenTypeInContext().
getTypeID()
TypeID llvm::Type::getTypeID () const inline
Return the type id for the type.
This will return one of the TypeID enum elements defined above.
Definition at line 137 of file Type.h.
Referenced by llvm::FunctionComparator::cmpTypes(), compareCmp(), llvm::isa_impl< PointerType, Type >::doit(), executeFAddInst(), executeFCMP_OEQ(), executeFCMP_OGE(), executeFCMP_OGT(), executeFCMP_OLE(), executeFCMP_OLT(), executeFCMP_ONE(), executeFDivInst(), executeFMulInst(), executeFNegInst(), executeFRemInst(), executeFSubInst(), executeICMP_EQ(), executeICMP_NE(), executeICMP_SGE(), executeICMP_SGT(), executeICMP_SLE(), executeICMP_SLT(), executeICMP_UGE(), executeICMP_UGT(), executeICMP_ULE(), executeICMP_ULT(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), getArrayElementType(), llvm::ExecutionEngine::getConstantValue(), llvm::EVT::getEVT(), llvm::getFloatFn(), getFltSemantics(), getFPMantissaWidth(), getMangledTypeStr(), getNonOpaquePointerElementType(), llvm::Constant::getNullValue(), getOverloadKind(), getPrimitiveSizeInBits(), llvm::NVPTXTargetLowering::getPrototype(), llvm::VectorType::getTruncatedElementVectorType(), getTypeID(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getTypeName(), llvm::DataLayout::getTypeSizeInBits(), llvm::MVT::getVT(), llvm::hasFloatFn(), is16bitFPTy(), isAggregateType(), isArrayTy(), isBFloatTy(), isDoubleTy(), isFirstClassType(), isFloatingPointTy(), isFloatTy(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), isFP128Ty(), isFunctionTy(), isHalfTy(), isIEEELikeFPTy(), isIntegerTy(), isLabelTy(), isLeakCheckerRoot(), llvm::XCoreTargetLowering::isLegalAddressingMode(), isMetadataTy(), isMultiUnitFPType(), isPointerTy(), isPPC_FP128Ty(), isSized(), isStructTy(), isTargetExtTy(), isTokenTy(), llvm::VectorType::isValidElementType(), llvm::ConstantFP::isValueValidForType(), isVectorTy(), isVoidTy(), isX86_AMXTy(), isX86_FP80Ty(), isX86_MMXTy(), llvm::ExecutionEngine::LoadValueFromMemory(), needsFPFromSig(), needsFPStubFromParams(), ReplaceFPIntrinsicWithCall(), llvm::MCJIT::runFunction(), llvm::ExecutionEngine::StoreValueToMemory(), llvm::Interpreter::visitExtractElementInst(), llvm::Interpreter::visitExtractValueInst(), llvm::Interpreter::visitInsertElementInst(), llvm::Interpreter::visitInsertValueInst(), llvm::Interpreter::visitShuffleVectorInst(), and llvm::Interpreter::visitVAArgInst().
getVoidTy()
Type * Type::getVoidTy (LLVMContext & C) static
Definition at line 224 of file Type.cpp.
Referenced by CreateAssert(), llvm::MIRParserImpl::createDummyFunction(), createEmptyFunction(), createFrameHelperMachineFunction(), createFree(), llvm::createMemLibcall(), llvm::createSanitizerCtor(), llvm::ThunkInserter< Derived, InsertedThunksTy >::createThunkFunction(), llvm::declareSanitizerInitFunction(), DecodeFixedType(), llvm::orc::IRSpeculationLayer::emit(), emitInlineAsm(), llvm::SanitizerStatReport::finish(), fixupFPReturnAndCall(), getFreshReductionFunc(), getFunctionTypeFromAsyncSuspend(), llvm::getOrCreateSanitizerCtorAndInitFunctions(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVTypeByName(), getOrInsertValueProfilingCall(), llvm::dxil::DXILOpBuilder::getOverloadTy(), getPrimitiveType(), llvm::coro::Shape::getResumeFunctionType(), getTargetTypeInfo(), llvm::EVT::getTypeForEVT(), getTypeFromParameterKind(), llvm::IRBuilderBase::getVoidTy(), insertCall(), InsertSafepointPoll(), llvm::ARMTargetLowering::insertSSPDeclarations(), llvm::AArch64TargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::insertSSPDeclarations(), insertUseHolderAfter(), LLVMVoidTypeInContext(), llvm::SelectionDAGBuilder::LowerCallSiteWithDeoptBundleImpl(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), makeStatepointExplicitImpl(), llvm::SinkInstructionStrategy::mutate(), runImpl(), and llvm::Interpreter::visitReturnInst().
getWithNewBitWidth()
Type * llvm::Type::getWithNewBitWidth (unsigned NewBitWidth) const inline
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
Definition at line 722 of file DerivedTypes.h.
References assert(), getContext(), getIntNTy(), getWithNewType(), and isIntOrIntVectorTy().
Referenced by extractIntPart(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), and llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost().
getWithNewType()
Type * llvm::Type::getWithNewType (Type * EltTy) const inline
Given vector type, change the element type, whilst keeping the old number of elements.
For non-vectors simply returns EltTy.
Definition at line 716 of file DerivedTypes.h.
References llvm::VectorType::get().
Referenced by getWithNewBitWidth(), llvm::InstCombinerImpl::visitIntToPtr(), and llvm::InstCombinerImpl::visitPtrToInt().
getX86_AMXPtrTy()
PointerType * Type::getX86_AMXPtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 281 of file Type.cpp.
References getPointerTo(), and getX86_AMXTy().
getX86_AMXTy()
Type * Type::getX86_AMXTy (LLVMContext & C) static
Definition at line 236 of file Type.cpp.
Referenced by createAllocaInstAtEntry(), DecodeFixedType(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), getX86_AMXPtrTy(), and LLVMX86AMXTypeInContext().
getX86_FP80PtrTy()
PointerType * Type::getX86_FP80PtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 265 of file Type.cpp.
References getPointerTo(), and getX86_FP80Ty().
getX86_FP80Ty()
Type * Type::getX86_FP80Ty (LLVMContext & C) static
Definition at line 232 of file Type.cpp.
Referenced by getFloatingPointTy(), getFloatTypeForLLT(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), getX86_FP80PtrTy(), and LLVMX86FP80TypeInContext().
getX86_MMXPtrTy()
PointerType * Type::getX86_MMXPtrTy (LLVMContext & C, unsigned AS = 0) static
Definition at line 277 of file Type.cpp.
References getPointerTo(), and getX86_MMXTy().
getX86_MMXTy()
Type * Type::getX86_MMXTy (LLVMContext & C) static
Definition at line 235 of file Type.cpp.
Referenced by DecodeFixedType(), getPrimitiveType(), llvm::EVT::getTypeForEVT(), getX86_MMXPtrTy(), and LLVMX86MMXTypeInContext().
is16bitFPTy()
bool llvm::Type::is16bitFPTy () const inline
Return true if this is a 16-bit float type.
Definition at line 149 of file Type.h.
References BFloatTyID, getTypeID(), and HalfTyID.
isAggregateType()
bool llvm::Type::isAggregateType () const inline
Return true if the type is an aggregate type.
This means it is valid as the first operand of an insertvalue or extractvalue instruction. This includes struct and array types, but does not include vector types.
Definition at line 288 of file Type.h.
References ArrayTyID, getTypeID(), and StructTyID.
Referenced by advanceToNextLeafType(), llvm::CastInst::castIsValid(), llvm::ConstantFoldLoadThroughBitcast(), firstRealType(), llvm::ExecutionEngine::getConstantValue(), llvm::NVPTXTargetLowering::getPrototype(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), nextRealType(), and llvm::InnerLoopVectorizer::scalarizeInstruction().
isArrayTy()
bool llvm::Type::isArrayTy () const inline
True if this is an instance of ArrayType.
Definition at line 246 of file Type.h.
References ArrayTyID, and getTypeID().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingLoad(), llvm::FindInsertedValue(), llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::AArch64TargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters(), llvm::ConstantAggregateZero::get(), llvm::SPIRVGlobalRegistry::getOrCreateConsIntArray(), hasTocDataAttr(), isArray(), isConstantUsingVectorTy(), llvm::VNCoercion::isFirstClassAggregateOrScalableType(), llvm::SCEVUnknown::isOffsetOf(), llvm::InstCombinerImpl::visitGEPOfBitcast(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and llvm::WebAssembly::wasmSymbolSetType().
isBFloatTy()
bool llvm::Type::isBFloatTy () const inline
Return true if this is 'bfloat', a 16-bit bfloat type.
Definition at line 146 of file Type.h.
References BFloatTyID, and getTypeID().
Referenced by emitDebugValueComment(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataSequential::isElementTypeCompatible(), llvm::AArch64TTIImpl::isElementTypeLegalForScalableVector(), llvm::AArch64TTIImpl::isLegalToVectorizeReduction(), LLVMConstRealGetDouble(), and matchIntrinsicType().
isDoubleTy()
bool llvm::Type::isDoubleTy () const inline
Return true if this is 'double', a 64-bit IEEE fp type.
Definition at line 157 of file Type.h.
References DoubleTyID, and getTypeID().
Referenced by emitDebugValueComment(), encodeVecTypeHint(), llvm::ExecutionEngine::getConstantValue(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::PPCTTIImpl::getRegisterClassForType(), llvm::RISCVTTIImpl::getRegisterClassForType(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::PPCTTIImpl::hasActiveVectorLength(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::ConstantDataSequential::isElementTypeCompatible(), llvm::AArch64TTIImpl::isElementTypeLegalForScalableVector(), isHomogeneousAggregate(), llvm::InductionDescriptor::isInductionPHI(), llvm::X86TTIImpl::isLegalAltInstr(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::isMathLibCallNoop(), isVectorLaneType(), LLVMConstRealGetDouble(), llvm::ExecutionEngine::LoadValueFromMemory(), matchIntrinsicType(), matchType(), optimizeDoubleFP(), llvm::SITargetLowering::shouldExpandAtomicRMWInIR(), llvm::NVPTXTargetLowering::shouldExpandAtomicRMWInIR(), shrinkFPConstant(), solveTypeName(), and updateFlags().
isEmptyTy()
bool Type::isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
Definition at line 146 of file Type.cpp.
References i.
Referenced by areGlobalsPotentiallyEqual(), llvm::CallLowering::ArgInfo::ArgInfo(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::FastISel::lowerCallTo(), and llvm::SelectionDAGBuilder::populateCallLoweringInfo().
isFirstClassType()
bool llvm::Type::isFirstClassType () const inline
Return true if the type is "first class", meaning it is a valid type for a Value.
Definition at line 274 of file Type.h.
References FunctionTyID, getTypeID(), and VoidTyID.
Referenced by canLosslesslyBitCastTo(), llvm::CastInst::castIsValid(), llvm::FunctionComparator::cmpConstants(), llvm::RandomIRBuilder::findPointer(), foldConstantCastPair(), llvm::CastInst::getCastOpcode(), getFoldedCast(), llvm::CastInst::isBitCastable(), llvm::FunctionType::isValidArgumentType(), and llvm::Value::Value().
isFloatingPointTy()
bool llvm::Type::isFloatingPointTy () const inline
Return true if this is one of the floating-point types.
Definition at line 185 of file Type.h.
References getTypeID(), isIEEELikeFPTy(), PPC_FP128TyID, and X86_FP80TyID.
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), llvm::SPIRVGlobalRegistry::buildConstantFP(), buildScalarSteps(), convertTo16Bit(), llvm::OpenMPIRBuilder::createAtomicCapture(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicUpdate(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), createCmpXchgInstFun(), emitTransformedIndex(), llvm::VPWidenIntOrFpInductionRecipe::execute(), FoldBitCast(), llvm::Constant::getAllOnesValue(), llvm::TargetTransformInfoImplBase::getArithmeticInstrCost(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::CastInst::getCastOpcode(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::ExecutionEngine::getConstantValue(), getFPMantissaWidth(), llvm::HexagonTTIImpl::getMemoryOpCost(), llvm::NVPTXTargetLowering::getPrototype(), llvm::getRuntimeVFAsFloat(), getStepVector(), llvm::VectorType::getTruncatedElementVectorType(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::AA::getWithType(), llvm::CastInst::isEliminableCastPair(), llvm::InductionDescriptor::isFPInductionPHI(), isFPOrFPVectorTy(), llvm::InductionDescriptor::isInductionPHI(), isSingleValueType(), isSized(), isSupportedAtomicType(), llvm::HexagonSubtarget::isTypeForHVX(), llvm::VectorType::isValidElementType(), llvm::NVPTXTargetLowering::LowerCall(), matchType(), MaybeVectorizeType(), llvm::MipsCCState::PreAnalyzeCallOperand(), llvm::MipsCCState::PreAnalyzeCallResult(), llvm::MipsCCState::PreAnalyzeFormalArgument(), llvm::TargetLoweringBase::shouldCastAtomicLoadInIR(), llvm::TargetLoweringBase::shouldCastAtomicRMWIInIR(), llvm::TargetLoweringBase::shouldConvertPhiType(), simplifyAMDGCNImageIntrinsic(), solveDIType(), solveTypeName(), supportedAddressingMode(), TryToShrinkGlobalToBoolean(), UpgradeIntrinsicFunction1(), llvm::InstCombinerImpl::visitAtomicRMWInst(), and llvm::InstCombinerImpl::visitInsertElementInst().
isFloatTy()
bool llvm::Type::isFloatTy () const inline
Return true if this is 'float', a 32-bit IEEE fp type.
Definition at line 154 of file Type.h.
References FloatTyID, and getTypeID().
Referenced by emitDebugValueComment(), llvm::SITargetLowering::emitExpandAtomicRMW(), encodeVecTypeHint(), executeFCMP_ORD(), executeFCMP_UNO(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::ExecutionEngine::getConstantValue(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::PPCTTIImpl::getRegisterClassForType(), llvm::RISCVTTIImpl::getRegisterClassForType(), llvm::PPCTTIImpl::hasActiveVectorLength(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::ConstantDataSequential::isElementTypeCompatible(), llvm::AArch64TTIImpl::isElementTypeLegalForScalableVector(), isHomogeneousAggregate(), llvm::InductionDescriptor::isInductionPHI(), llvm::X86TTIImpl::isLegalAltInstr(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::isMathLibCallNoop(), isVectorLaneType(), LLVMConstRealGetDouble(), llvm::ExecutionEngine::LoadValueFromMemory(), matchIntrinsicType(), matchType(), optimizeDoubleFP(), optimizeWithFDivFast(), llvm::ARMTargetLowering::shouldConvertSplatType(), llvm::SITargetLowering::shouldExpandAtomicRMWInIR(), llvm::NVPTXTargetLowering::shouldExpandAtomicRMWInIR(), and solveTypeName().
isFP128Ty()
bool llvm::Type::isFP128Ty () const inline
Return true if this is 'fp128'.
Definition at line 163 of file Type.h.
References FP128TyID, and getTypeID().
Referenced by llvm::PPCTTIImpl::getRegisterClassForType(), llvm::SystemZTTIImpl::getShuffleCost(), llvm::SparcTargetLowering::LowerF128Op(), matchIntrinsicType(), and llvm::MipsCCState::originalTypeIsF128().
isFPOrFPVectorTy()
bool llvm::Type::isFPOrFPVectorTy () const inline
Return true if this is a FP type or a vector of FP.
Definition at line 210 of file Type.h.
References getScalarType(), and isFloatingPointTy().
Referenced by llvm::ARMTargetLowering::canCombineStoreAndExtract(), llvm::CastInst::castIsValid(), llvm::FPMathOperator::classof(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadFromUniformValue(), llvm::CastInst::CreateFPCast(), evaluateICmpRelation(), foldBitCastBitwiseLogic(), llvm::HexagonTTIImpl::getArithmeticInstrCost(), llvm::HexagonTTIImpl::getCastInstrCost(), llvm::HexagonTTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), getDecodedBinaryOpcode(), getDecodedUnaryOpcode(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), llvm::ConstantExpr::getFPTrunc(), llvm::X86TTIImpl::getMinMaxCost(), llvm::AArch64TTIImpl::getMinMaxReductionCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperandsScalarizationOverhead(), llvm::ConstantExpr::getSIToFP(), llvm::ConstantExpr::getUIToFP(), llvm::ConstantFP::getZeroValueForNegation(), instCombineSVEVectorFuseMulAddSub(), llvm::isKnownNeverInfinity(), llvm::isKnownNeverNaN(), matchIntrinsicType(), NegateValue(), llvm::MipsCCState::originalTypeIsVectorFloat(), upgradeAVX512MaskToSelect(), and UpgradeX86VPERMT2Intrinsics().
isFunctionTy()
bool llvm::Type::isFunctionTy () const inline
True if this is an instance of FunctionType.
Definition at line 240 of file Type.h.
References FunctionTyID, and getTypeID().
Referenced by llvm::AArch64Subtarget::classifyGlobalFunctionReference(), llvm::AArch64Subtarget::ClassifyGlobalReference(), llvm::convertToDeclaration(), llvm::emitLinkerFlagsForGlobalCOFF(), llvm::GlobalVariable::GlobalVariable(), llvm::PointerType::isLoadableOrStorableType(), llvm::SystemZSubtarget::isPC32DBLSymbol(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::FunctionType::isValidReturnType(), and llvm::SITargetLowering::shouldEmitGOTReloc().
isFunctionVarArg()
bool llvm::Type::isFunctionVarArg () const inline
Definition at line 149 of file DerivedTypes.h.
isHalfTy()
bool llvm::Type::isHalfTy () const inline
Return true if this is 'half', a 16-bit IEEE fp type.
Definition at line 143 of file Type.h.
References getTypeID(), and HalfTyID.
Referenced by canSafelyConvertTo16Bit(), emitDebugValueComment(), encodeVecTypeHint(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::NVPTXTargetLowering::getPrototype(), llvm::PPCTTIImpl::getRegisterClassForType(), llvm::RISCVTTIImpl::getRegisterClassForType(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::ConstantDataSequential::isElementTypeCompatible(), llvm::AArch64TTIImpl::isElementTypeLegalForScalableVector(), llvm::InductionDescriptor::isInductionPHI(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), llvm::ARMTargetLowering::isLegalInterleavedAccessType(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::isMathLibCallNoop(), LLVMConstRealGetDouble(), matchIntrinsicType(), llvm::ARMTargetLowering::shouldConvertSplatType(), llvm::SITargetLowering::shouldExpandAtomicRMWInIR(), and simplifyAMDGCNImageIntrinsic().
isIEEE()
bool Type::isIEEE () const
Return whether the type is IEEE compatible, as defined by the eponymous method in APFloat.
Definition at line 79 of file Type.cpp.
References getFltSemantics(), llvm::APFloat::getZero(), and llvm::APFloat::isIEEE().
isIEEELikeFPTy()
bool llvm::Type::isIEEELikeFPTy () const inline
Return true if this is a well-behaved IEEE-like type, which has a IEEE compatible layout as defined by isIEEE(), and does not have unnormal values.
Definition at line 171 of file Type.h.
References BFloatTyID, DoubleTyID, FloatTyID, FP128TyID, getTypeID(), and HalfTyID.
Referenced by isFloatingPointTy().
isIntegerTy() [1/2]
bool llvm::Type::isIntegerTy () const inline
True if this is an instance of IntegerType.
Definition at line 222 of file Type.h.
References getTypeID(), and IntegerTyID.
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), llvm::HexagonTargetLowering::allowTruncateForTailCall(), llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), llvm::VNCoercion::analyzeLoadFromClobberingLoad(), askForAssumedConstant(), buildScalarSteps(), canConvertValue(), canHoistIVInc(), canSafelyConvertTo16Bit(), llvm::VNCoercion::coerceAvailableValueToLoadType(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), ComputePTXValueVTs(), llvm::ConstantFoldLoadThroughBitcast(), convertTo16Bit(), llvm::OpenMPIRBuilder::createAtomicCapture(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicUpdate(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::CastInst::CreateBitOrPointerCast(), createCast(), createNodeForSelectViaUMinSeq(), llvm::createStepForVF(), emitTransformedIndex(), llvm::VPWidenIntOrFpInductionRecipe::execute(), llvm::VPDerivedIVRecipe::execute(), llvm::X86TargetLowering::ExpandInlineAsm(), llvm::extractConstantMask(), FindLoopCounter(), FoldBitCast(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::InstCombinerImpl::foldPHIArgOpIntoPHI(), FoldTwoEntryPHINode(), llvm::ARMTargetLowering::functionArgumentNeedsConsecutiveRegisters(), getAISize(), getAllocationDataForFunction(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::RISCVTTIImpl::getArithmeticReductionCost(), llvm::AArch64TargetLowering::getAsmOperandValueType(), llvm::CastInst::getCastOpcode(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::getConstantDataArrayInfo(), llvm::LazyValueInfo::getConstantRange(), llvm::ExecutionEngine::getConstantValue(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::ConstantExpr::getExtractElement(), llvm::DataLayout::getIndexedOffsetInType(), llvm::ConstantExpr::getInsertElement(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::SystemZTTIImpl::getIntImmCost(), llvm::LanaiTTIImpl::getIntImmCost(), llvm::PPCTTIImpl::getIntImmCost(), llvm::RISCVTTIImpl::getIntImmCost(), llvm::AArch64TTIImpl::getIntImmCost(), llvm::ARMTTIImpl::getIntImmCost(), llvm::X86TTIImpl::getIntImmCost(), llvm::SystemZTTIImpl::getIntImmCostInst(), llvm::PPCTTIImpl::getIntImmCostInst(), llvm::RISCVTTIImpl::getIntImmCostInst(), llvm::AArch64TTIImpl::getIntImmCostInst(), llvm::X86TTIImpl::getIntImmCostInst(), llvm::SystemZTTIImpl::getIntImmCostIntrin(), llvm::PPCTTIImpl::getIntImmCostIntrin(), llvm::AArch64TTIImpl::getIntImmCostIntrin(), llvm::X86TTIImpl::getIntImmCostIntrin(), getLoadStoreAddrMode(), llvm::VNCoercion::getLoadValueForLoad(), llvm::ScalarEvolution::getLosslessPtrToIntExpr(), llvm::RISCVTTIImpl::getMinMaxReductionCost(), llvm::NVPTXTargetLowering::getPrototype(), llvm::ScalarEvolution::getPtrToIntExpr(), llvm::RISCVTTIImpl::getShuffleCost(), getSignedIntOrFpConstant(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::TargetLowering::getSingleConstraintMatchWeight(), getStepVector(), llvm::VNCoercion::getStoreValueForLoadHelper(), getUnderlyingObjectFromInt(), getValueFromICmpCondition(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::HexagonTTIImpl::getVectorInstrCost(), llvm::RISCVTTIImpl::getVectorInstrCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::AA::getWithType(), llvm::PPCTTIImpl::hasActiveVectorLength(), llvm::hasIterationCountInvariantInParent(), llvm::HexagonEvaluator::HexagonEvaluator(), llvm::GCNTTIImpl::instCombineIntrinsic(), instCombineSVECondLast(), llvm::isBytewiseValue(), isCallingConvCCompatible(), isConstantFalse(), llvm::AArch64TTIImpl::isElementTypeLegalForScalableVector(), llvm::CastInst::isEliminableCastPair(), llvm::isGEPBasedOnPointerToString(), llvm::InductionDescriptor::isInductionPHI(), llvm::CastInst::isIntegerCast(), isIntegerLoopHeaderPHI(), isIntegerTy(), isIntOrIntVectorTy(), isIntOrPtrTy(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), isSingleValueType(), llvm::ConstantDataSequential::isString(), llvm::MSP430TargetLowering::isTruncateFree(), llvm::RISCVTargetLowering::isTruncateFree(), llvm::ARMTargetLowering::isTruncateFree(), llvm::SystemZTargetLowering::isTruncateFree(), llvm::NVPTXTargetLowering::isTruncateFree(), llvm::AArch64TargetLowering::isTruncateFree(), llvm::PPCTargetLowering::isTruncateFree(), llvm::X86TargetLowering::isTruncateFree(), llvm::HexagonSubtarget::isTypeForHVX(), llvm::VectorType::isValidElementType(), llvm::ConstantInt::isValueValidForType(), isVectorLaneType(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), llvm::MSP430TargetLowering::isZExtFree(), llvm::AArch64TargetLowering::isZExtFree(), llvm::X86TargetLowering::isZExtFree(), llvm::ExecutionEngine::LoadValueFromMemory(), llvm::NVPTXTargetLowering::LowerCall(), LowerCTPOP(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::IntrinsicLowering::LowerToByteSwap(), MatchBinaryOp(), matchIntrinsicType(), matchType(), llvm::MipsCCState::originalTypeIsF128(), llvm::replaceAllDbgUsesWith(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::MCJIT::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::ARMTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::AArch64TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::PPCTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::X86TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::TargetLoweringBase::shouldConvertPhiType(), llvm::NVPTXTargetLowering::shouldExpandAtomicRMWInIR(), llvm::X86TargetLowering::shouldSinkOperands(), llvm::RISCVTargetLowering::signExtendConstant(), simplifyAllocaArraySize(), llvm::InstCombinerImpl::SimplifyAnyMemSet(), simplifyX86addcarry(), simplifyX86immShift(), solveDIType(), solveTypeName(), splitMergedValStore(), tryToRecognizeTableBasedCttz(), llvm::AttributeFuncs::typeIncompatible(), unpackFromRegLoc(), updatePredecessorProfileMetadata(), UpgradeX86IntrinsicsWith8BitMask(), llvm::InstCombinerImpl::visitAtomicRMWInst(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitInsertElementInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitPHINode(), llvm::InstCombinerImpl::visitReturnInst(), and llvm::InstCombinerImpl::visitTrunc().
isIntegerTy() [2/2]
bool Type::isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
Definition at line 56 of file Type.cpp.
References isIntegerTy().
isIntOrIntVectorTy() [1/2]
bool llvm::Type::isIntOrIntVectorTy () const inline
Return true if this is an integer type or a vector of integer types.
Definition at line 228 of file Type.h.
References getScalarType(), and isIntegerTy().
Referenced by llvm::PPCTTIImpl::areTypesABICompatible(), buildMultiplyTree(), llvm::CastInst::castIsValid(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::computeConstantRange(), computeKnownBits(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadFromUniformValue(), convertValue(), CreateAdd(), llvm::IRBuilderBase::CreateBitOrPointerCast(), llvm::CastInst::CreateIntegerCast(), llvm::IRBuilderBase::CreateLogicalAnd(), llvm::IRBuilderBase::CreateLogicalOr(), CreateMul(), CreateNeg(), llvm::CastInst::CreatePointerCast(), llvm::IRBuilderBase::CreateSExtOrTrunc(), llvm::IRBuilderBase::CreateZExtOrTrunc(), foldAndOrOfICmpEqZeroAndICmp(), foldBitCastBitwiseLogic(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), foldSelectICmpLshrAshr(), foldTruncShuffle(), getBoolVecFromMask(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), getConstantRange(), getDecodedBinaryOpcode(), getDecodedUnaryOpcode(), llvm::VectorType::getExtendedElementVectorType(), getExtendedType(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getIntegerCast(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), getMaskedTypeForICmpPair(), llvm::X86TTIImpl::getMinMaxCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperandsScalarizationOverhead(), llvm::ConstantExpr::getPointerCast(), llvm::ConstantExpr::getPtrToInt(), getSafeDivisor(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSExtOrTrunc(), llvm::ConstantInt::getTrue(), llvm::ConstantExpr::getTrunc(), llvm::GetElementPtrInst::getTypeAtIndex(), llvm::SystemZTTIImpl::getVectorInstrCost(), getWithNewBitWidth(), llvm::ConstantExpr::getZExt(), llvm::haveNoCommonBitsSet(), llvm::StructType::indexValid(), llvm::CastInst::isEliminableCastPair(), llvm::isImpliedCondition(), isKnownNonEqual(), isNeutralValue(), llvm::DemandedBits::isUseDead(), LowerBSWAP(), LowerNegateToMultiply(), matchIntrinsicType(), llvm::recognizeBSwapOrBitReverseIdiom(), simplifyAddInst(), simplifyAndInst(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyDivRem(), simplifyICmpOfBools(), simplifyMulInst(), simplifyOrInst(), simplifySubInst(), tryToRecognizePopCount(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitOr().
isIntOrIntVectorTy() [2/2]
bool llvm::Type::isIntOrIntVectorTy (unsigned BitWidth) const inline
Return true if this is an integer type or a vector of integer types of the given width.
Definition at line 232 of file Type.h.
References llvm::BitWidth, getScalarType(), and isIntegerTy().
isIntOrPtrTy()
bool llvm::Type::isIntOrPtrTy () const inline
Return true if this is an integer type or a pointer type.
Definition at line 237 of file Type.h.
References isIntegerTy(), and isPointerTy().
Referenced by computeKnownBitsFromOperator(), evaluateICmpRelation(), llvm::ScalarEvolution::getNoopOrAnyExtend(), llvm::ScalarEvolution::getNoopOrSignExtend(), llvm::ScalarEvolution::getNoopOrZeroExtend(), llvm::ScalarEvolution::getTruncateOrNoop(), llvm::ScalarEvolution::getTruncateOrSignExtend(), llvm::ScalarEvolution::getTruncateOrZeroExtend(), isBitCastSemanticsPreserving(), llvm::ScalarEvolution::isSCEVable(), isSupportedAtomicType(), and MaybeVectorizeType().
isLabelTy()
bool llvm::Type::isLabelTy () const inline
Return true if this is 'label'.
Definition at line 213 of file Type.h.
References getTypeID(), and LabelTyID.
Referenced by llvm::TypedPointerType::isValidElementType(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::PointerType::isValidElementType(), and llvm::FunctionType::isValidReturnType().
isMetadataTy()
bool llvm::Type::isMetadataTy () const inline
Return true if this is 'metadata'.
Definition at line 216 of file Type.h.
References getTypeID(), and MetadataTyID.
Referenced by llvm::TypedPointerType::isValidElementType(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::PointerType::isValidElementType(), llvm::FunctionType::isValidReturnType(), and matchIntrinsicType().
isMultiUnitFPType()
bool llvm::Type::isMultiUnitFPType () const inline
Returns true if this is a floating-point type that is an unevaluated sum of multiple floating-point units.
An example of such a type is ppc_fp128, also known as double-double, which consists of two IEEE 754 doubles.
Definition at line 194 of file Type.h.
References getTypeID(), and PPC_FP128TyID.
Referenced by llvm::isKnownNeverInfinity().
isOpaquePointerTy()
bool Type::isOpaquePointerTy () const
True if this is an instance of an opaque PointerType.
Definition at line 60 of file Type.cpp.
Referenced by speculateSelectInstLoads(), and llvm::InstCombinerImpl::visitGEPOfGEP().
isPointerTy()
bool llvm::Type::isPointerTy () const inline
True if this is an instance of PointerType.
Definition at line 249 of file Type.h.
References getTypeID(), and PointerTyID.
Referenced by addConditions(), llvm::ScalarEvolution::applyLoopGuards(), canBeCheaplyTransformed(), canConvertValue(), llvm::canReplacePointersIfEqual(), CompareValueComplexity(), computeKnownBits(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), ComputeNumSignBitsImpl(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldLoadThroughBitcast(), llvm::convertPointerToIntegerType(), llvm::copyMetadataForLoad(), llvm::OpenMPIRBuilder::createAtomicCapture(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicUpdate(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::CastInst::CreateBitOrPointerCast(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), createCast(), createCmpXchgInstFun(), llvm::ScalarEvolution::ExitLimit::ExitLimit(), FindLoopCounter(), llvm::InstCombinerImpl::foldICmpBitCast(), genLoopLimit(), getAllocationDataForFunction(), llvm::AMDGPUTargetMachine::getAssumedAddrSpace(), llvm::CastInst::getCastOpcode(), GetConstantInt(), llvm::ExecutionEngine::getConstantValue(), llvm::ScalarEvolution::getEffectiveSCEVType(), getExactSDiv(), llvm::MemoryLocation::getForDest(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::ScalarEvolution::getLosslessPtrToIntExpr(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getMulExpr(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::ScalarEvolution::getNotSCEV(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::getOrEnforceKnownAlignment(), llvm::AMDGPULibFunc::getOrInsertFunction(), llvm::ScalarEvolution::getPointerBase(), llvm::LazyValueInfo::getPredicateAt(), llvm::getPtrStride(), llvm::VNCoercion::getStoreValueForLoadHelper(), llvm::GetStringLength(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ScalarEvolution::getUDivExpr(), llvm::getUnderlyingObject(), llvm::AA::getWithType(), llvm::PPCTTIImpl::hasActiveVectorLength(), llvm::HexagonEvaluator::HexagonEvaluator(), isCallingConvCCompatible(), isCompatibleIVType(), isDereferenceableAndAlignedPointer(), llvm::AArch64TTIImpl::isElementTypeLegalForScalableVector(), llvm::InductionDescriptor::isInductionPHI(), isIntOrPtrTy(), isKnownNonZeroFromAssume(), llvm::RISCVTargetLowering::isLegalElementTypeForRVV(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::isLibFreeFunction(), llvm::CastInst::isLosslessCast(), isMinMaxWithLoads(), isNoopBitcast(), isPointerOperand(), isPtrOrPtrVectorTy(), isSingleValueType(), llvm::VectorType::isValidElementType(), isVectorLaneType(), isVectorPromotionViable(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::NVPTXTargetLowering::LowerCall(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), matchType(), optimizeOnceStoredGlobal(), llvm::PointerMayBeCaptured(), llvm::SCEVExpander::replaceCongruentIVs(), replaceWithConstant(), llvm::MCJIT::runFunction(), llvm::salvageDebugInfoImpl(), llvm::DbgAssignIntrinsic::setAddress(), shouldBeMustTail(), llvm::TargetLoweringBase::shouldCastAtomicRMWIInIR(), shouldConvertToRelLookupTable(), simplifyICmpInst(), solveDIType(), StripPointerGEPsAndCasts(), swapMayExposeCSEOpportunities(), TryToShrinkGlobalToBoolean(), llvm::AttributeFuncs::typeIncompatible(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitICmpInst(), and llvm::InstCombinerImpl::visitPHINode().
isPPC_FP128Ty()
bool llvm::Type::isPPC_FP128Ty () const inline
Return true if this is powerpc long double.
Definition at line 166 of file Type.h.
References getTypeID(), and PPC_FP128TyID.
Referenced by emitGlobalConstantFP(), FoldBitCast(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::PPCTTIImpl::getRegisterClassForType(), isValidElementType(), and matchIntrinsicType().
isPtrOrPtrVectorTy()
bool llvm::Type::isPtrOrPtrVectorTy () const inline
Return true if this is a pointer type or a vector of pointer types.
Definition at line 255 of file Type.h.
References getScalarType(), and isPointerTy().
Referenced by llvm::CastInst::castIsValid(), llvm::VNCoercion::coerceAvailableValueToLoadType(), combineLoadToOperationType(), computeKnownBits(), convertValue(), llvm::IRBuilderBase::CreateBitOrPointerCast(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerCast(), llvm::DataLayout::getIndexType(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::DataLayout::getIntPtrType(), llvm::ConstantExpr::getIntToPtr(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperandsScalarizationOverhead(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), llvm::DataLayout::getPointerTypeSizeInBits(), getScalarSizeInBits(), llvm::VNCoercion::getStoreValueForLoadHelper(), llvm::CastInst::isEliminableCastPair(), simplifyCastInst(), stripAndComputeConstantOffsets(), llvm::AttributeFuncs::typeIncompatible(), llvm::UpgradeBitCastExpr(), and llvm::UpgradeBitCastInst().
isSingleValueType()
bool llvm::Type::isSingleValueType () const inline
Return true if the type is a valid type for a register in codegen.
This includes all first-class types except struct and array types.
Definition at line 280 of file Type.h.
References isFloatingPointTy(), isIntegerTy(), isPointerTy(), isTargetExtTy(), isVectorTy(), isX86_AMXTy(), and isX86_MMXTy().
Referenced by canConvertValue(), getAggregateSize(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::TargetLowering::ParseConstraints(), processInternalGlobal(), stripAggregateTypeWrapping(), and llvm::SCCPInstVisitor::trackValueOfGlobalVariable().
isSized()
bool llvm::Type::isSized (SmallPtrSetImpl< Type * > * Visited = nullptr) const inline
Return true if it makes sense to take the size of this type.
To get the actual size for a particular target, it is reasonable to use the DataLayout subsystem to do this.
Definition at line 295 of file Type.h.
References ArrayTyID, getTypeID(), IntegerTyID, isFloatingPointTy(), isVectorTy(), PointerTyID, StructTyID, TargetExtTyID, X86_AMXTyID, and X86_MMXTyID.
Referenced by areGlobalsPotentiallyEqual(), llvm::PPCTTIImpl::areTypesABICompatible(), buildFrameDebugInfo(), canReplaceGEPIdxWithZero(), computeKnownBitsFromOperator(), convertBitCastToGEP(), createByteGEP(), findElementAtOffset(), llvm::RandomIRBuilder::findPointer(), llvm::DataLayout::getGEPIndicesForOffset(), llvm::getLLTForType(), llvm::Value::getPointerAlignment(), llvm::DataLayout::getTypeSizeInBits(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), hasTocDataAttr(), isDenselyPacked(), llvm::isDereferenceableAndAlignedPointer(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), llvm::InductionDescriptor::isInductionPHI(), llvm::memtag::StackInfoBuilder::isInterestingAlloca(), llvm::SITargetLowering::isLegalAddressingMode(), llvm::HexagonTargetLowering::isLegalAddressingMode(), llvm::AArch64TargetLowering::isLegalAddressingMode(), isSafeToEliminateVarargsCast(), IsSmallObject(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::TargetLowering::ParseConstraints(), llvm::InstCombinerImpl::PromoteCastOfAllocation(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), simplifyGEPInst(), valueEscapes(), llvm::InstCombinerImpl::visitAllocaInst(), llvm::ObjectSizeOffsetVisitor::visitArgument(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
isStructTy()
bool llvm::Type::isStructTy () const inline
True if this is an instance of StructType.
Definition at line 243 of file Type.h.
References getTypeID(), and StructTyID.
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingLoad(), llvm::ConstantFoldLoadThroughBitcast(), createCast(), createWrapper(), llvm::FindInsertedValue(), llvm::ConstantAggregateZero::get(), llvm::SCCPInstVisitor::getLatticeValueFor(), hasTocDataAttr(), insertSinCosCall(), isConstantUsingVectorTy(), llvm::VNCoercion::isFirstClassAggregateOrScalableType(), llvm::SCEVUnknown::isOffsetOf(), isStructure(), isVectorPromotionViableForSlice(), matchType(), false::operator<<(), llvm::MipsCCState::originalTypeIsF128(), solveDIType(), solveTypeName(), llvm::SCCPSolver::tryToReplaceWithConstant(), llvm::Value::Value(), llvm::InlineAsm::verify(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
isTargetExtTy()
bool llvm::Type::isTargetExtTy () const inline
Return true if this is a target extension type.
Definition at line 207 of file Type.h.
References getTypeID(), and TargetExtTyID.
Referenced by llvm::VNCoercion::canCoerceMustAliasedValueToLoad(), canConvertValue(), and isSingleValueType().
isTokenTy()
bool llvm::Type::isTokenTy () const inline
Return true if this is 'token'.
Definition at line 219 of file Type.h.
References getTypeID(), and TokenTyID.
Referenced by llvm::SelectInst::areInvalidOperands(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::FunctionLoweringInfo::InitializeRegForValue(), llvm::TypedPointerType::isValidElementType(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::PointerType::isValidElementType(), matchIntrinsicType(), llvm::removeAllNonTerminatorAndEHPadInstructions(), SplitLandingPadPredecessorsImpl(), and llvm::LoopInfo::wouldBeOutOfLoopUseRequiringLCSSA().
isVectorTy()
bool llvm::Type::isVectorTy () const inline
True if this is an instance of VectorType.
Definition at line 258 of file Type.h.
References FixedVectorTyID, getTypeID(), and ScalableVectorTyID.
Referenced by llvm::ARMTargetLowering::canCombineStoreAndExtract(), canEvaluateShuffled(), canonicalizeBitCastExtElt(), collectShuffleElements(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::IRBuilderBase::CreateMaskedCompressStore(), llvm::IRBuilderBase::CreateMaskedExpandLoad(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::createMemCpyLoopKnownSize(), llvm::CastInst::CreatePointerCast(), despeculateCountZeros(), llvm::emitGEPOffset(), evaluateInDifferentElementOrder(), llvm::VPBranchOnMaskRecipe::execute(), executeFCMP_BOOL(), executeFCMP_ONE(), executeFCMP_ORD(), executeFCMP_UNO(), executeSelectInst(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), expandUDivOrURem(), findForkedSCEVs(), llvm::findScalarElement(), foldBitCastBitwiseLogic(), foldBitCastSelect(), llvm::InstCombinerImpl::foldGEPICmp(), foldGEPOfGEP(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpTruncConstant(), foldSelectICmpAnd(), foldSelectICmpAndOr(), llvm::InstCombinerImpl::foldSelectOpOp(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldTruncShuffle(), llvm::ConstantAggregateZero::get(), llvm::MipsTargetLowering::getABIAlignmentForCallingConv(), llvm::ARMTargetLowering::getABIAlignmentForCallingConv(), llvm::X86TTIImpl::getAddressComputationCost(), llvm::AArch64TTIImpl::getAddressComputationCost(), llvm::ARMTTIImpl::getAddressComputationCost(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::HexagonTTIImpl::getArithmeticInstrCost(), llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::HexagonTTIImpl::getCastInstrCost(), llvm::CastInst::getCastOpcode(), getCmpOpsType(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::HexagonTTIImpl::getCmpSelInstrCost(), llvm::RISCVTTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCmpSelInstrCost(), llvm::ConstantExpr::getExtractElement(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getGatherScatterOpCost(), llvm::ConstantExpr::getInsertElement(), llvm::PPCTTIImpl::getInstructionCost(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::SPIRVGlobalRegistry::getOrCreateConsIntVector(), llvm::NVPTXTargetLowering::getPrototype(), getReducedType(), llvm::RISCVTTIImpl::getRegUsageForType(), getScalarType(), getTargetConstantBitsFromNode(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), getUniformBase(), getValueOnEdge(), llvm::SystemZTTIImpl::getVectorBitmaskConversionCost(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::HexagonTTIImpl::getVectorInstrCost(), llvm::RISCVTTIImpl::getVectorInstrCost(), llvm::ARMTTIImpl::getVectorInstrCost(), getVectorIntrinsicInstrCost(), llvm::SystemZTTIImpl::getVectorTruncCost(), hasTocDataAttr(), llvm::StructType::indexValid(), insertValues(), llvm::X86TTIImpl::instCombineIntrinsic(), isAggrToReplace(), llvm::X86TargetLowering::isCheapToSpeculateCttz(), isConstantUsingVectorTy(), llvm::CastInst::isEliminableCastPair(), llvm::isImpliedCondition(), llvm::SystemZTargetLowering::isLegalAddressingMode(), llvm::PPCTargetLowering::isLegalAddressingMode(), isMMAType(), isSingleValueType(), isSized(), llvm::HexagonSubtarget::isTypeForHVX(), llvm::ExtractElementInst::isValidOperands(), llvm::InsertElementInst::isValidOperands(), llvm::ShuffleVectorInst::isValidOperands(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), narrowSDivOrSRem(), narrowUDivOrURem(), llvm::MipsCCState::originalTypeIsVectorFloat(), llvm::MipsCCState::PreAnalyzeCallOperand(), llvm::MipsCCState::PreAnalyzeFormalArgument(), processAnd(), processAShr(), processBinOp(), processCallSite(), processSDiv(), processSDivOrSRem(), processSExt(), processSRem(), processUDivOrURem(), llvm::salvageDebugInfoImpl(), shouldConvertImpl(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), simplifyX86immShift(), supportedAddressingMode(), threadCmpOverSelect(), transformToIndexedCompare(), TryToShrinkGlobalToBoolean(), llvm::PPCTTIImpl::vectorCostAdjustmentFactor(), llvm::InstCombinerImpl::visitAShr(), llvm::Interpreter::visitAShr(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitInsertElementInst(), llvm::Interpreter::visitLShr(), llvm::Interpreter::visitShl(), llvm::InstCombinerImpl::visitTrunc(), and llvm::Interpreter::visitUnaryOperator().
isVoidTy()
bool llvm::Type::isVoidTy () const inline
Return true if this is 'void'.
Definition at line 140 of file Type.h.
References getTypeID(), and VoidTyID.
Referenced by llvm::AllocaInst::AllocaInst(), llvm::CallLowering::ArgInfo::ArgInfo(), llvm::coro::Shape::buildFrom(), llvm::computeValueLLTs(), llvm::ComputeValueVTs(), copyMustTailReturn(), createMalloc(), createRetPHINode(), llvm::Attributor::createShallowWrapper(), createWrapper(), llvm::Evaluator::EvaluateFunction(), llvm::OpenMPIRBuilder::finalize(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), getRetComponentType(), llvm::SITargetLowering::getTgtMemIntrinsic(), llvm::objcarc::hasAttachedCallOpBundle(), llvm::InlineFunction(), isCallingConvCCompatible(), llvm::isLibFreeFunction(), llvm::TypedPointerType::isValidElementType(), llvm::StructType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::PointerType::isValidElementType(), llvm::SPIRV::lowerBuiltin(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::makeGuardControlFlowExplicit(), matchIntrinsicType(), matchType(), modifyIntrinsicCall(), llvm::InstDeleterIRStrategy::mutate(), numRetVals(), llvm::VPReplicateRecipe::print(), llvm::promoteCall(), llvm::MCJIT::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::InnerLoopVectorizer::scalarizeInstruction(), shouldBeMustTail(), llvm::AttributeFuncs::typeIncompatible(), llvm::Value::Value(), and llvm::InlineAsm::verify().
isX86_AMXTy()
bool llvm::Type::isX86_AMXTy () const inline
Return true if this is X86 AMX.
Definition at line 204 of file Type.h.
References getTypeID(), and X86_AMXTyID.
Referenced by canLosslesslyBitCastTo(), combineLoadToOperationType(), combineStoreToValueType(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldLoadFromUniformValue(), createTileStore(), isAMXIntrinsic(), isSingleValueType(), llvm::TypedPointerType::isValidElementType(), llvm::ArrayType::isValidElementType(), llvm::PointerType::isValidElementType(), matchIntrinsicType(), onlyTileDef(), and replaceWithTileLoad().
isX86_FP80Ty()
bool llvm::Type::isX86_FP80Ty () const inline
Return true if this is x86 long double.
Definition at line 160 of file Type.h.
References getTypeID(), and X86_FP80TyID.
Referenced by llvm::ExecutionEngine::getConstantValue(), and isValidElementType().
isX86_MMXTy()
bool llvm::Type::isX86_MMXTy () const inline
Return true if this is X86 MMX.
Definition at line 201 of file Type.h.
References getTypeID(), and X86_MMXTyID.
Referenced by canLosslesslyBitCastTo(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldLoadFromUniformValue(), llvm::CastInst::getCastOpcode(), llvm::CastInst::isBitCastable(), isSingleValueType(), matchIntrinsicType(), and llvm::InstCombinerImpl::visitBitCast().
print()
void Type::print (raw_ostream & O, bool IsForDebug = false, bool NoDetails = false) const
Print the current type.
Omit the type details if NoDetails == true. E.g., let st = type { i32, i16 } When NoDetails is true, we only print st. Put differently, NoDetails prints the type as if inlined with the operands when printing an instruction.
Definition at line 4673 of file AsmWriter.cpp.
References llvm::StructType::isLiteral(), and OS.
Referenced by dump(), emitGlobalConstantFP(), llvm::Attribute::getAsString(), getBranchCondString(), getTypeName(), and PrintResults().
setSubclassData()
void llvm::Type::setSubclassData (unsigned val) inline protected
Definition at line 100 of file Type.h.
References assert(), getSubclassData(), and val.
Referenced by llvm::IntegerType::IntegerType(), llvm::StructType::isSized(), and llvm::StructType::setBody().
subtype_begin()
subtype_iterator llvm::Type::subtype_begin () const inline
Definition at line 352 of file Type.h.
References ContainedTys.
Referenced by subtype_rend(), and subtypes().
subtype_end()
subtype_iterator llvm::Type::subtype_end () const inline
Definition at line 353 of file Type.h.
References ContainedTys, and NumContainedTys.
Referenced by subtype_rbegin(), and subtypes().
subtype_rbegin()
subtype_reverse_iterator llvm::Type::subtype_rbegin () const inline
Definition at line 360 of file Type.h.
References subtype_end().
subtype_rend()
subtype_reverse_iterator llvm::Type::subtype_rend () const inline
Definition at line 363 of file Type.h.
References subtype_begin().
subtypes()
ArrayRef<Type*> llvm::Type::subtypes () const inline
Definition at line 354 of file Type.h.
References llvm::ArrayRef(), subtype_begin(), and subtype_end().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 92 of file Type.h.
Member Data Documentation
ContainedTys
Type* const * llvm::Type::ContainedTys = nullptr protected
A pointer to the array of Types contained by this Type.
For example, this includes the arguments of a function type, the elements of a structure, the pointee of a pointer, the element type of an array, etc. This pointer may be 0 for types that don't contain other types (Integer, Double, Float).
Definition at line 114 of file Type.h.
Referenced by llvm::StructType::element_begin(), llvm::StructType::element_end(), getArrayElementType(), getContainedType(), llvm::StructType::getElementType(), getNonOpaquePointerElementType(), llvm::FunctionType::getParamType(), llvm::FunctionType::getReturnType(), llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), llvm::StructType::setBody(), subtype_begin(), subtype_end(), llvm::TargetExtType::type_param_begin(), llvm::TargetExtType::type_param_end(), and llvm::VectorType::VectorType().
NumContainedTys
unsigned llvm::Type::NumContainedTys = 0 protected
Keeps track of how many Type*'s there are in the ContainedTys list.
Definition at line 107 of file Type.h.
Referenced by llvm::StructType::element_end(), getContainedType(), llvm::StructType::getElementType(), getNonOpaquePointerElementType(), getNumContainedTypes(), llvm::StructType::getNumElements(), llvm::FunctionType::getNumParams(), llvm::FunctionType::param_end(), llvm::StructType::setBody(), subtype_end(), llvm::TargetExtType::type_param_end(), and llvm::VectorType::VectorType().
The documentation for this class was generated from the following files:
include/llvm/IR/Type.h
include/llvm/IR/DerivedTypes.h
lib/IR/AsmWriter.cpp
lib/IR/Type.cpp