LLVM: llvm::Target Class Reference
llvm::Target Class Reference
Target - Wrapper for Target specific information.
#include "llvm/MC/TargetRegistry.h"
Public Types
using ArchMatchFnTy = bool(*)(Triple::ArchType Arch)
using MCAsmInfoCtorFnTy = MCAsmInfo *(*)(const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
using MCObjectFileInfoCtorFnTy = MCObjectFileInfo *(*)(MCContext &Ctx, bool PIC, bool LargeCodeModel)
using MCInstrInfoCtorFnTy = MCInstrInfo *(*)()
using MCInstrAnalysisCtorFnTy = MCInstrAnalysis *(*)(const MCInstrInfo *Info)
using MCRegInfoCtorFnTy = MCRegisterInfo *(*)(const Triple &TT)
using MCSubtargetInfoCtorFnTy = MCSubtargetInfo *(*)(const Triple &TT, StringRef CPU, StringRef Features)
using TargetMachineCtorTy = TargetMachine *(*)(const Target &T, const Triple &TT, StringRef CPU, StringRef Features, const TargetOptions &Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
using AsmPrinterCtorTy = AsmPrinter *(*)(TargetMachine &TM, std::unique_ptr< MCStreamer > &&Streamer)
using MCAsmBackendCtorTy = MCAsmBackend *(*)(const Target &T, const MCSubtargetInfo &STI, const MCRegisterInfo &MRI, const MCTargetOptions &Options)
using MCAsmParserCtorTy = MCTargetAsmParser *(*)(const MCSubtargetInfo &STI, MCAsmParser &P, const MCInstrInfo &MII, const MCTargetOptions &Options)
using MCDisassemblerCtorTy = MCDisassembler *(*)(const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
using MCInstPrinterCtorTy = MCInstPrinter *(*)(const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
using MCCodeEmitterCtorTy = MCCodeEmitter *(*)(const MCInstrInfo &II, MCContext &Ctx)
using ELFStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
using MachOStreamerCtorTy = MCStreamer *(*)(MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd)
using COFFStreamerCtorTy = MCStreamer *(*)(MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll, bool IncrementalLinkerCompatible)
using WasmStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
using XCOFFStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
using SPIRVStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
using DXContainerStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
using NullTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S)
using AsmTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool IsVerboseAsm)
using ObjectTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S, const MCSubtargetInfo &STI)
using MCRelocationInfoCtorTy = MCRelocationInfo *(*)(const Triple &TT, MCContext &Ctx)
using MCSymbolizerCtorTy = MCSymbolizer *(*)(const Triple &TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo)
using CustomBehaviourCtorTy = mca::CustomBehaviour *(*)(const MCSubtargetInfo &STI, const mca::SourceMgr &SrcMgr, const MCInstrInfo &MCII)
using InstrPostProcessCtorTy = mca::InstrPostProcess *(*)(const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
using InstrumentManagerCtorTy = mca::InstrumentManager *(*)(const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
Public Member Functions
Target ()=default
Target Information
const Target * getNext () const
const char * getName () const
getName - Get the target name.
const char * getShortDescription () const
getShortDescription - Get a short description of the target.
const char * getBackendName () const
getBackendName - Get the backend name.
Feature Predicates
bool hasJIT () const
hasJIT - Check if this targets supports the just-in-time compilation.
bool hasTargetMachine () const
hasTargetMachine - Check if this target supports code generation.
bool hasMCAsmBackend () const
hasMCAsmBackend - Check if this target supports .o generation.
bool hasMCAsmParser () const
hasMCAsmParser - Check if this target supports assembly parsing.
Feature Constructors
MCAsmInfo * createMCAsmInfo (const MCRegisterInfo &MRI, StringRef TheTriple, const MCTargetOptions &Options) const
createMCAsmInfo - Create a MCAsmInfo implementation for the specified target triple.
MCObjectFileInfo * createMCObjectFileInfo (MCContext &Ctx, bool PIC, bool LargeCodeModel=false) const
Create a MCObjectFileInfo implementation for the specified target triple.
MCInstrInfo * createMCInstrInfo () const
createMCInstrInfo - Create a MCInstrInfo implementation.
MCInstrAnalysis * createMCInstrAnalysis (const MCInstrInfo *Info) const
createMCInstrAnalysis - Create a MCInstrAnalysis implementation.
MCRegisterInfo * createMCRegInfo (StringRef TT) const
createMCRegInfo - Create a MCRegisterInfo implementation.
MCSubtargetInfo * createMCSubtargetInfo (StringRef TheTriple, StringRef CPU, StringRef Features) const
createMCSubtargetInfo - Create a MCSubtargetInfo implementation.
TargetMachine * createTargetMachine (StringRef TT, StringRef CPU, StringRef Features, const TargetOptions &Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM=std::nullopt, CodeGenOpt::Level OL=CodeGenOpt::Default, bool JIT=false) const
createTargetMachine - Create a target specific machine implementation for the specified Triple.
MCAsmBackend * createMCAsmBackend (const MCSubtargetInfo &STI, const MCRegisterInfo &MRI, const MCTargetOptions &Options) const
createMCAsmBackend - Create a target specific assembly parser.
MCTargetAsmParser * createMCAsmParser (const MCSubtargetInfo &STI, MCAsmParser &Parser, const MCInstrInfo &MII, const MCTargetOptions &Options) const
createMCAsmParser - Create a target specific assembly parser.
AsmPrinter * createAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > &&Streamer) const
createAsmPrinter - Create a target specific assembly printer pass.
MCDisassembler * createMCDisassembler (const MCSubtargetInfo &STI, MCContext &Ctx) const
MCInstPrinter * createMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI) const
MCCodeEmitter * createMCCodeEmitter (const MCInstrInfo &II, MCContext &Ctx) const
createMCCodeEmitter - Create a target specific code emitter.
MCStreamer * createMCObjectStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, const MCSubtargetInfo &STI, bool RelaxAll, bool IncrementalLinkerCompatible, bool DWARFMustBeAtTheEnd) const
Create a target specific MCStreamer.
MCStreamer * createAsmStreamer (MCContext &Ctx, std::unique_ptr< formatted_raw_ostream > OS, bool IsVerboseAsm, bool UseDwarfDirectory, MCInstPrinter *InstPrint, std::unique_ptr< MCCodeEmitter > &&CE, std::unique_ptr< MCAsmBackend > &&TAB, bool ShowInst) const
MCTargetStreamer * createAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool IsVerboseAsm) const
MCStreamer * createNullStreamer (MCContext &Ctx) const
MCTargetStreamer * createNullTargetStreamer (MCStreamer &S) const
MCRelocationInfo * createMCRelocationInfo (StringRef TT, MCContext &Ctx) const
createMCRelocationInfo - Create a target specific MCRelocationInfo.
MCSymbolizer * createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo) const
createMCSymbolizer - Create a target specific MCSymbolizer.
mca::CustomBehaviour * createCustomBehaviour (const MCSubtargetInfo &STI, const mca::SourceMgr &SrcMgr, const MCInstrInfo &MCII) const
createCustomBehaviour - Create a target specific CustomBehaviour.
mca::InstrPostProcess * createInstrPostProcess (const MCSubtargetInfo &STI, const MCInstrInfo &MCII) const
createInstrPostProcess - Create a target specific InstrPostProcess.
mca::InstrumentManager * createInstrumentManager (const MCSubtargetInfo &STI, const MCInstrInfo &MCII) const
createInstrumentManager - Create a target specific InstrumentManager.
Friends
struct TargetRegistry
Detailed Description
Target - Wrapper for Target specific information.
For registration purposes, this is a POD type so that targets can be registered without the use of static constructors.
Targets should implement a single global instance of this class (which will be zero initialized), and pass that instance to the TargetRegistry as part of their initialization.
Definition at line 149 of file TargetRegistry.h.
Member Typedef Documentation
ArchMatchFnTy
using llvm::Target::ArchMatchFnTy = bool (*)(Triple::ArchType Arch)
Definition at line 153 of file TargetRegistry.h.
AsmPrinterCtorTy
using llvm::Target::AsmPrinterCtorTy = AsmPrinter *(*)(TargetMachine &TM, std::unique_ptr<MCStreamer> &&Streamer)
Definition at line 175 of file TargetRegistry.h.
AsmTargetStreamerCtorTy
using llvm::Target::AsmTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool IsVerboseAsm)
Definition at line 233 of file TargetRegistry.h.
COFFStreamerCtorTy
using llvm::Target::COFFStreamerCtorTy = MCStreamer *(*)(MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll, bool IncrementalLinkerCompatible)
Definition at line 207 of file TargetRegistry.h.
CustomBehaviourCtorTy
using llvm::Target::CustomBehaviourCtorTy = mca::CustomBehaviour *(*)(const MCSubtargetInfo &STI, const mca::SourceMgr &SrcMgr, const MCInstrInfo &MCII)
Definition at line 246 of file TargetRegistry.h.
DXContainerStreamerCtorTy
using llvm::Target::DXContainerStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll)
Definition at line 228 of file TargetRegistry.h.
ELFStreamerCtorTy
using llvm::Target::ELFStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll)
Definition at line 197 of file TargetRegistry.h.
InstrPostProcessCtorTy
using llvm::Target::InstrPostProcessCtorTy = mca::InstrPostProcess *(*)(const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
Definition at line 250 of file TargetRegistry.h.
InstrumentManagerCtorTy
using llvm::Target::InstrumentManagerCtorTy = mca::InstrumentManager *(*)(const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
Definition at line 254 of file TargetRegistry.h.
MachOStreamerCtorTy
using llvm::Target::MachOStreamerCtorTy = MCStreamer *(*)(MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd)
Definition at line 202 of file TargetRegistry.h.
MCAsmBackendCtorTy
using llvm::Target::MCAsmBackendCtorTy = MCAsmBackend *(*)(const Target &T, const MCSubtargetInfo &STI, const MCRegisterInfo &MRI, const MCTargetOptions &Options)
Definition at line 179 of file TargetRegistry.h.
MCAsmInfoCtorFnTy
using llvm::Target::MCAsmInfoCtorFnTy = MCAsmInfo *(*)(const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
Definition at line 157 of file TargetRegistry.h.
MCAsmParserCtorTy
using llvm::Target::MCAsmParserCtorTy = MCTargetAsmParser *(*)(const MCSubtargetInfo &STI, MCAsmParser &P, const MCInstrInfo &MII, const MCTargetOptions &Options)
Definition at line 182 of file TargetRegistry.h.
MCCodeEmitterCtorTy
using llvm::Target::MCCodeEmitterCtorTy = MCCodeEmitter *(*)(const MCInstrInfo &II, MCContext &Ctx)
Definition at line 192 of file TargetRegistry.h.
MCDisassemblerCtorTy
using llvm::Target::MCDisassemblerCtorTy = MCDisassembler *(*)(const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
Definition at line 185 of file TargetRegistry.h.
MCInstPrinterCtorTy
using llvm::Target::MCInstPrinterCtorTy = MCInstPrinter *(*)(const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
Definition at line 190 of file TargetRegistry.h.
MCInstrAnalysisCtorFnTy
using llvm::Target::MCInstrAnalysisCtorFnTy = MCInstrAnalysis *(*)(const MCInstrInfo *Info)
Definition at line 162 of file TargetRegistry.h.
MCInstrInfoCtorFnTy
using llvm::Target::MCInstrInfoCtorFnTy = MCInstrInfo *(*)()
Definition at line 161 of file TargetRegistry.h.
MCObjectFileInfoCtorFnTy
using llvm::Target::MCObjectFileInfoCtorFnTy = MCObjectFileInfo *(*)(MCContext &Ctx, bool PIC, bool LargeCodeModel)
Definition at line 160 of file TargetRegistry.h.
MCRegInfoCtorFnTy
using llvm::Target::MCRegInfoCtorFnTy = MCRegisterInfo *(*)(const Triple &TT)
Definition at line 163 of file TargetRegistry.h.
MCRelocationInfoCtorTy
using llvm::Target::MCRelocationInfoCtorTy = MCRelocationInfo *(*)(const Triple &TT, MCContext &Ctx)
Definition at line 237 of file TargetRegistry.h.
MCSubtargetInfoCtorFnTy
using llvm::Target::MCSubtargetInfoCtorFnTy = MCSubtargetInfo *(*)(const Triple &TT, StringRef CPU, StringRef Features)
Definition at line 166 of file TargetRegistry.h.
MCSymbolizerCtorTy
using llvm::Target::MCSymbolizerCtorTy = MCSymbolizer *(*)(const Triple &TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr<MCRelocationInfo> &&RelInfo)
Definition at line 241 of file TargetRegistry.h.
NullTargetStreamerCtorTy
using llvm::Target::NullTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S)
Definition at line 230 of file TargetRegistry.h.
ObjectTargetStreamerCtorTy
using llvm::Target::ObjectTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S, const MCSubtargetInfo &STI)
Definition at line 235 of file TargetRegistry.h.
SPIRVStreamerCtorTy
using llvm::Target::SPIRVStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll)
Definition at line 222 of file TargetRegistry.h.
TargetMachineCtorTy
using llvm::Target::TargetMachineCtorTy = TargetMachine *(*)(const Target &T, const Triple &TT, StringRef CPU, StringRef Features, const TargetOptions &Options, std::optional<Reloc::Model> RM, std::optional<CodeModel::Model> CM, CodeGenOpt::Level OL, bool JIT)
Definition at line 170 of file TargetRegistry.h.
WasmStreamerCtorTy
using llvm::Target::WasmStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll)
Definition at line 212 of file TargetRegistry.h.
XCOFFStreamerCtorTy
using llvm::Target::XCOFFStreamerCtorTy = MCStreamer *(*)(const Triple &T, MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB, std::unique_ptr<MCObjectWriter> &&OW, std::unique_ptr<MCCodeEmitter> &&Emitter, bool RelaxAll)
Definition at line 217 of file TargetRegistry.h.
Constructor & Destructor Documentation
Target()
llvm::Target::Target () default
Member Function Documentation
createAsmPrinter()
AsmPrinter* llvm::Target::createAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > && Streamer) const inline
createAsmPrinter - Create a target specific assembly printer pass.
This takes ownership of the MCStreamer object.
Definition at line 516 of file TargetRegistry.h.
References move, and TM.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), and llvm::DwarfStreamer::init().
createAsmStreamer()
MCStreamer* llvm::Target::createAsmStreamer (MCContext & Ctx, std::unique_ptr< formatted_raw_ostream > OS, bool IsVerboseAsm, bool UseDwarfDirectory, MCInstPrinter * InstPrint, std::unique_ptr< MCCodeEmitter > && CE, std::unique_ptr< MCAsmBackend > && TAB, bool ShowInst) const inline
Definition at line 630 of file TargetRegistry.h.
References llvm::createAsmStreamer(), createAsmTargetStreamer(), move, OS, and S.
Referenced by llvm::LLVMTargetMachine::createMCStreamer(), and llvm::DwarfStreamer::init().
createAsmTargetStreamer()
MCTargetStreamer* llvm::Target::createAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint, bool IsVerboseAsm) const inline
Definition at line 645 of file TargetRegistry.h.
References OS, and S.
Referenced by createAsmStreamer().
createCustomBehaviour()
mca::CustomBehaviour* llvm::Target::createCustomBehaviour (const MCSubtargetInfo & STI, const mca::SourceMgr & SrcMgr, const MCInstrInfo & MCII) const inline
createCustomBehaviour - Create a target specific CustomBehaviour.
This class is used by llvm-mca and requires backend functionality.
Definition at line 702 of file TargetRegistry.h.
References llvm::SrcMgr.
createInstrPostProcess()
mca::InstrPostProcess* llvm::Target::createInstrPostProcess (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) const inline
createInstrPostProcess - Create a target specific InstrPostProcess.
This class is used by llvm-mca and requires backend functionality.
Definition at line 712 of file TargetRegistry.h.
createInstrumentManager()
mca::InstrumentManager* llvm::Target::createInstrumentManager (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) const inline
createInstrumentManager - Create a target specific InstrumentManager.
This class is used by llvm-mca and requires backend functionality.
Definition at line 723 of file TargetRegistry.h.
createMCAsmBackend()
MCAsmBackend* llvm::Target::createMCAsmBackend (const MCSubtargetInfo & STI, const MCRegisterInfo & MRI, const MCTargetOptions & Options) const inline
createMCAsmBackend - Create a target specific assembly parser.
Definition at line 493 of file TargetRegistry.h.
References MRI, and Options.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::LLVMTargetMachine::createMCStreamer(), and llvm::DwarfStreamer::init().
createMCAsmInfo()
MCAsmInfo* llvm::Target::createMCAsmInfo (const MCRegisterInfo & MRI, StringRef TheTriple, const MCTargetOptions & Options) const inline
createMCAsmInfo - Create a MCAsmInfo implementation for the specified target triple.
Parameters
TheTriple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 414 of file TargetRegistry.h.
References MRI, and Options.
Referenced by llvm::DwarfStreamer::init(), llvm::LLVMTargetMachine::initAsmInfo(), LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCAsmParser()
MCTargetAsmParser* llvm::Target::createMCAsmParser (const MCSubtargetInfo & STI, MCAsmParser & Parser, const MCInstrInfo & MII, const MCTargetOptions & Options) const inline
createMCAsmParser - Create a target specific assembly parser.
Parameters
Parser The target independent parser implementation to use for parsing and lexing.
Definition at line 505 of file TargetRegistry.h.
References Options.
createMCCodeEmitter()
MCCodeEmitter* llvm::Target::createMCCodeEmitter (const MCInstrInfo & II, MCContext & Ctx) const inline
createMCCodeEmitter - Create a target specific code emitter.
Definition at line 540 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::LLVMTargetMachine::createMCStreamer(), llvm::DwarfStreamer::init(), and llvm::X86AsmPrinter::runOnMachineFunction().
createMCDisassembler()
MCDisassembler* llvm::Target::createMCDisassembler (const MCSubtargetInfo & STI, MCContext & Ctx) const inline
Definition at line 523 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCInstPrinter()
MCInstPrinter* llvm::Target::createMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) const inline
Definition at line 530 of file TargetRegistry.h.
References MRI, and T.
Referenced by llvm::LLVMTargetMachine::createMCStreamer(), llvm::DwarfStreamer::init(), LLVMCreateDisasmCPUFeatures(), LLVMSetDisasmOptions(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCInstrAnalysis()
MCInstrAnalysis* llvm::Target::createMCInstrAnalysis (const MCInstrInfo * Info) const inline
createMCInstrAnalysis - Create a MCInstrAnalysis implementation.
Definition at line 444 of file TargetRegistry.h.
References Info.
createMCInstrInfo()
MCInstrInfo* llvm::Target::createMCInstrInfo () const inline
createMCInstrInfo - Create a MCInstrInfo implementation.
Definition at line 436 of file TargetRegistry.h.
Referenced by llvm::DwarfStreamer::init(), llvm::LLVMTargetMachine::initAsmInfo(), LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCObjectFileInfo()
MCObjectFileInfo* llvm::Target::createMCObjectFileInfo (MCContext & Ctx, bool PIC, bool LargeCodeModel = false) const inline
Create a MCObjectFileInfo implementation for the specified target triple.
Definition at line 424 of file TargetRegistry.h.
References llvm::MCObjectFileInfo::initMCObjectFileInfo(), and PIC.
Referenced by llvm::DwarfStreamer::init().
createMCObjectStreamer()
MCStreamer* llvm::Target::createMCObjectStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > && TAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, const MCSubtargetInfo & STI, bool RelaxAll, bool IncrementalLinkerCompatible, bool DWARFMustBeAtTheEnd) const inline
Create a target specific MCStreamer.
Parameters
T The target triple.
Ctx The target context.
TAB The target assembler backend object. Takes ownership.
OW The stream object.
Emitter The target independent assembler object.Takes ownership.
RelaxAll Relax all fixups?
Definition at line 555 of file TargetRegistry.h.
References assert(), llvm::Triple::COFF, llvm::createDXContainerStreamer(), llvm::createELFStreamer(), llvm::createMachOStreamer(), llvm::createSPIRVStreamer(), llvm::createWasmStreamer(), llvm::createXCOFFStreamer(), llvm::Triple::DXContainer, llvm::Triple::ELF, Emitter, llvm::Triple::GOFF, llvm_unreachable, llvm::Triple::MachO, move, llvm::report_fatal_error(), S, llvm::Triple::SPIRV, T, llvm::Triple::UnknownObjectFormat, llvm::Triple::Wasm, and llvm::Triple::XCOFF.
Referenced by llvm::DwarfStreamer::init().
createMCRegInfo()
MCRegisterInfo* llvm::Target::createMCRegInfo (StringRef TT) const inline
createMCRegInfo - Create a MCRegisterInfo implementation.
Definition at line 452 of file TargetRegistry.h.
Referenced by llvm::DwarfStreamer::init(), llvm::LLVMTargetMachine::initAsmInfo(), LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCRelocationInfo()
MCRelocationInfo* llvm::Target::createMCRelocationInfo (StringRef TT, MCContext & Ctx) const inline
createMCRelocationInfo - Create a target specific MCRelocationInfo.
Parameters
TT The target triple.
Ctx The target context.
Definition at line 670 of file TargetRegistry.h.
References llvm::createMCRelocationInfo().
Referenced by LLVMCreateDisasmCPUFeatures().
createMCSubtargetInfo()
MCSubtargetInfo* llvm::Target::createMCSubtargetInfo (StringRef TheTriple, StringRef CPU, StringRef Features) const inline
createMCSubtargetInfo - Create a MCSubtargetInfo implementation.
Parameters
TheTriple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
CPU This specifies the name of the target CPU.
Features This specifies the string representation of the additional target features.
Definition at line 467 of file TargetRegistry.h.
Referenced by llvm::DwarfStreamer::init(), llvm::LLVMTargetMachine::initAsmInfo(), LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCSymbolizer()
MCSymbolizer* llvm::Target::createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void * DisInfo, MCContext * Ctx, std::unique_ptr< MCRelocationInfo > && RelInfo) const inline
createMCSymbolizer - Create a target specific MCSymbolizer.
Parameters
TT The target triple.
GetOpInfo The function to get the symbolic information for operands.
SymbolLookUp The function to lookup a symbol name.
DisInfo The pointer to the block of symbolic information for above call back.
Ctx The target context.
RelInfo The relocation information for this target. Takes ownership.
Definition at line 690 of file TargetRegistry.h.
References llvm::createMCSymbolizer(), and move.
Referenced by LLVMCreateDisasmCPUFeatures().
createNullStreamer()
MCStreamer* llvm::Target::createNullStreamer (MCContext & Ctx) const inline
Definition at line 654 of file TargetRegistry.h.
References llvm::createNullStreamer(), createNullTargetStreamer(), and S.
createNullTargetStreamer()
MCTargetStreamer* llvm::Target::createNullTargetStreamer (MCStreamer & S) const inline
Definition at line 660 of file TargetRegistry.h.
References S.
Referenced by createNullStreamer().
createTargetMachine()
TargetMachine* llvm::Target::createTargetMachine (StringRef TT, StringRef CPU, StringRef Features, const TargetOptions & Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM = std::nullopt, CodeGenOpt::Level OL = CodeGenOpt::Default, bool JIT = false) const inline
createTargetMachine - Create a target specific machine implementation for the specified Triple.
Parameters
TT This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 481 of file TargetRegistry.h.
References llvm::EngineKind::JIT, Options, and llvm::AArch64::RM.
Referenced by llvm::TargetMachineBuilder::create(), createTargetMachine(), llvm::DwarfStreamer::init(), and llvm::EngineBuilder::selectTarget().
getBackendName()
const char* llvm::Target::getBackendName () const inline
getBackendName - Get the backend name.
Definition at line 385 of file TargetRegistry.h.
getName()
const char* llvm::Target::getName () const inline
getName - Get the target name.
Definition at line 379 of file TargetRegistry.h.
Referenced by llvm::jitlink::TableManager< PLTTableManager >::getEntryForTarget(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::getGOTEntry(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::getPLTStub(), llvm::MachObjectWriter::getSymbolAddress(), llvm::logicalview::LVType::markMissingParents(), llvm::logicalview::LVSymbol::markMissingParents(), and llvm::logicalview::LVScope::markMissingParents().
getNext()
const Target* llvm::Target::getNext () const inline
Definition at line 376 of file TargetRegistry.h.
Referenced by llvm::TargetRegistry::iterator::operator++().
getShortDescription()
const char* llvm::Target::getShortDescription () const inline
getShortDescription - Get a short description of the target.
Definition at line 382 of file TargetRegistry.h.
Referenced by llvm::TargetRegistry::printRegisteredTargetsForVersion().
hasJIT()
bool llvm::Target::hasJIT () const inline
hasJIT - Check if this targets supports the just-in-time compilation.
Definition at line 392 of file TargetRegistry.h.
hasMCAsmBackend()
bool llvm::Target::hasMCAsmBackend () const inline
hasMCAsmBackend - Check if this target supports .o generation.
Definition at line 398 of file TargetRegistry.h.
hasMCAsmParser()
bool llvm::Target::hasMCAsmParser () const inline
hasMCAsmParser - Check if this target supports assembly parsing.
Definition at line 401 of file TargetRegistry.h.
hasTargetMachine()
bool llvm::Target::hasTargetMachine () const inline
hasTargetMachine - Check if this target supports code generation.
Definition at line 395 of file TargetRegistry.h.
Friends And Related Function Documentation
TargetRegistry
friend struct TargetRegistry friend
Definition at line 151 of file TargetRegistry.h.
The documentation for this class was generated from the following file:
include/llvm/MC/TargetRegistry.h