LLVM: llvm::PGOInstrumentationUse Class Reference
llvm::PGOInstrumentationUse Class Reference
The profile annotation (profile-instr-use) pass for IR based PGO.
#include "llvm/Transforms/Instrumentation/PGOInstrumentation.h"
Public Member Functions
PGOInstrumentationUse (std::string Filename="", std::string RemappingFilename="", bool IsCS=false, IntrusiveRefCntPtr< vfs::FileSystem > FS=nullptr)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< PGOInstrumentationUse >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< PGOInstrumentationUse >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The profile annotation (profile-instr-use) pass for IR based PGO.
Definition at line 63 of file PGOInstrumentation.h.
Constructor & Destructor Documentation
PGOInstrumentationUse()
PGOInstrumentationUse::PGOInstrumentationUse (std::string Filename = "", std::string RemappingFilename = "", bool IsCS = false, IntrusiveRefCntPtr< vfs::FileSystem > FS = nullptr)
Definition at line 2254 of file PGOInstrumentation.cpp.
References llvm::vfs::getRealFileSystem(), PGOTestProfileFile, and PGOTestProfileRemappingFile.
Member Function Documentation
run()
PreservedAnalyses PGOInstrumentationUse::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 2268 of file PGOInstrumentation.cpp.
References llvm::PreservedAnalyses::all(), annotateAllFunctions(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), M, and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/PGOInstrumentation.h
lib/Transforms/Instrumentation/PGOInstrumentation.cpp