LLVM: llvm::AddrLabelMap Class Reference
llvm::AddrLabelMap Class Reference
Public Member Functions
AddrLabelMap (MCContext &context)
~AddrLabelMap ()
ArrayRef< MCSymbol * > getAddrLabelSymbolToEmit (BasicBlock *BB)
void takeDeletedSymbolsForFunction (Function *F, std::vector< MCSymbol * > &Result)
If we have any deleted symbols for F, return them.
void UpdateForDeletedBlock (BasicBlock *BB)
void UpdateForRAUWBlock (BasicBlock *Old, BasicBlock *New)
Detailed Description
Definition at line 177 of file AsmPrinter.cpp.
Constructor & Destructor Documentation
AddrLabelMap()
llvm::AddrLabelMap::AddrLabelMap (MCContext & context) inline
Definition at line 200 of file AsmPrinter.cpp.
References Context.
~AddrLabelMap()
llvm::AddrLabelMap::~AddrLabelMap () inline
Definition at line 202 of file AsmPrinter.cpp.
References assert(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::empty().
Member Function Documentation
getAddrLabelSymbolToEmit()
ArrayRef< MCSymbol * > AddrLabelMap::getAddrLabelSymbolToEmit (BasicBlock * BB)
Definition at line 216 of file AsmPrinter.cpp.
References assert(), and BB.
takeDeletedSymbolsForFunction()
void AddrLabelMap::takeDeletedSymbolsForFunction (Function * F, std::vector< MCSymbol * > & Result)
If we have any deleted symbols for F, return them.
Definition at line 240 of file AsmPrinter.cpp.
References F, I, and std::swap().
UpdateForDeletedBlock()
void AddrLabelMap::UpdateForDeletedBlock (BasicBlock * BB)
Definition at line 274 of file AsmPrinter.cpp.
UpdateForRAUWBlock()
void AddrLabelMap::UpdateForRAUWBlock (BasicBlock * Old, BasicBlock * New)
Definition at line 301 of file AsmPrinter.cpp.
References llvm::append_range(), assert(), and move.
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/AsmPrinter.cpp