LLVM: llvm::LazyCallGraphPrinterPass Class Reference
llvm::LazyCallGraphPrinterPass Class Reference
A pass which prints the call graph to a raw_ostream.
#include "llvm/Analysis/LazyCallGraph.h"
Public Member Functions
LazyCallGraphPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< LazyCallGraphPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LazyCallGraphPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A pass which prints the call graph to a raw_ostream.
This is primarily useful for testing the analysis.
Definition at line 1283 of file LazyCallGraph.h.
Constructor & Destructor Documentation
LazyCallGraphPrinterPass()
LazyCallGraphPrinterPass::LazyCallGraphPrinterPass (raw_ostream & OS) explicit
Definition at line 1985 of file LazyCallGraph.cpp.
Member Function Documentation
run()
PreservedAnalyses LazyCallGraphPrinterPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 2012 of file LazyCallGraph.cpp.
References llvm::PreservedAnalyses::all(), F, G, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), M, printNode(), and printRefSCC().
The documentation for this class was generated from the following files:
include/llvm/Analysis/LazyCallGraph.h
lib/Analysis/LazyCallGraph.cpp