LLVM: llvm::object::ImportedSymbolRef Class Reference
llvm::object::ImportedSymbolRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
ImportedSymbolRef ()=default
ImportedSymbolRef (const import_lookup_table_entry32 *Entry, uint32_t I, const COFFObjectFile *Owner)
ImportedSymbolRef (const import_lookup_table_entry64 *Entry, uint32_t I, const COFFObjectFile *Owner)
bool operator== (const ImportedSymbolRef &Other) const
void moveNext ()
Error getSymbolName (StringRef &Result) const
Error isOrdinal (bool &Result) const
Error getOrdinal (uint16_t &Result) const
Error getHintNameRVA (uint32_t &Result) const
Detailed Description
Definition at line 1195 of file COFF.h.
Constructor & Destructor Documentation
ImportedSymbolRef() [1/3]
llvm::object::ImportedSymbolRef::ImportedSymbolRef () default
ImportedSymbolRef() [2/3]
llvm::object::ImportedSymbolRef::ImportedSymbolRef (const import_lookup_table_entry32 * Entry, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 1198 of file COFF.h.
ImportedSymbolRef() [3/3]
llvm::object::ImportedSymbolRef::ImportedSymbolRef (const import_lookup_table_entry64 * Entry, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 1201 of file COFF.h.
Member Function Documentation
getHintNameRVA()
Error ImportedSymbolRef::getHintNameRVA (uint32_t & Result) const
Definition at line 1687 of file COFFObjectFile.cpp.
References llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), and llvm::Error::success().
getOrdinal()
Error ImportedSymbolRef::getOrdinal (uint16_t & Result) const
Definition at line 1695 of file COFFObjectFile.cpp.
References llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), llvm::object::import_lookup_table_entry< IntTy >::getOrdinal(), llvm::object::COFFObjectFile::getRvaPtr(), isOrdinal(), and llvm::Error::success().
getSymbolName()
Error ImportedSymbolRef::getSymbolName (StringRef & Result) const
Definition at line 1659 of file COFFObjectFile.cpp.
References llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), llvm::object::COFFObjectFile::getRvaPtr(), isOrdinal(), and llvm::Error::success().
isOrdinal()
Error ImportedSymbolRef::isOrdinal (bool & Result) const
Definition at line 1679 of file COFFObjectFile.cpp.
References llvm::object::import_lookup_table_entry< IntTy >::isOrdinal(), and llvm::Error::success().
Referenced by getOrdinal(), and getSymbolName().
moveNext()
void ImportedSymbolRef::moveNext ()
Definition at line 1655 of file COFFObjectFile.cpp.
operator==()
bool ImportedSymbolRef::operator== (const ImportedSymbolRef & Other) const
Definition at line 1650 of file COFFObjectFile.cpp.
References Other.
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp