LLVM: llvm::dxil::Resources Class Reference
llvm::dxil::Resources Class Reference
#include "Target/DirectX/DXILResource.h"
Public Member Functions
void collect (Module &M)
void write (Module &M) const
void print (raw_ostream &O) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
Definition at line 136 of file DXILResource.h.
Member Function Documentation
collect()
void Resources::collect (Module & M)
Definition at line 54 of file DXILResource.cpp.
References M.
dump()
void Resources::dump () const
Definition at line 420 of file DXILResource.cpp.
References llvm::dbgs(), and llvm::dxil::ResourceBase::print().
print()
void Resources::print (raw_ostream & O) const
Definition at line 407 of file DXILResource.cpp.
References llvm::RISCVFenceField::O.
Referenced by llvm::DXILResourceWrapper::print(), and llvm::DXILResourcePrinterPass::run().
write()
void Resources::write (Module & M) const
Definition at line 387 of file DXILResource.cpp.
References llvm::NamedMDNode::addOperand(), llvm::MDNode::get(), and M.
The documentation for this class was generated from the following files:
lib/Target/DirectX/DXILResource.h
lib/Target/DirectX/DXILResource.cpp