LLVM: llvm::LLVMRemarkStreamer Class Reference
llvm::LLVMRemarkStreamer Class Reference
Streamer for LLVM remarks which has logic for dealing with DiagnosticInfo objects.
#include "llvm/IR/LLVMRemarkStreamer.h"
Public Member Functions
LLVMRemarkStreamer (remarks::RemarkStreamer &RS)
void emit (const DiagnosticInfoOptimizationBase &Diag)
Emit a diagnostic through the streamer.
Detailed Description
Streamer for LLVM remarks which has logic for dealing with DiagnosticInfo objects.
Definition at line 34 of file LLVMRemarkStreamer.h.
Constructor & Destructor Documentation
LLVMRemarkStreamer()
llvm::LLVMRemarkStreamer::LLVMRemarkStreamer (remarks::RemarkStreamer & RS) inline
Definition at line 42 of file LLVMRemarkStreamer.h.
Member Function Documentation
emit()
void LLVMRemarkStreamer::emit (const DiagnosticInfoOptimizationBase & Diag)
Emit a diagnostic through the streamer.
Definition at line 81 of file LLVMRemarkStreamer.cpp.
References llvm::remarks::RemarkSerializer::emit(), llvm::DiagnosticInfoOptimizationBase::getPassName(), llvm::remarks::RemarkStreamer::getSerializer(), and llvm::remarks::RemarkStreamer::matchesFilter().
The documentation for this class was generated from the following files:
include/llvm/IR/LLVMRemarkStreamer.h
lib/IR/LLVMRemarkStreamer.cpp