LLVM: llvm::IntervalData< PointT, ValueT > Class Template Reference
llvm::IntervalData< PointT, ValueT > Class Template Reference
An interval data composed by a Left and Right points and an associated Value.
#include "llvm/ADT/IntervalTree.h"
Public Member Functions
IntervalData ()=delete
IntervalData (PointType Left, PointType Right, ValueType Value)
virtual ~IntervalData ()=default
PointType left () const
PointType right () const
ValueType value () const
bool left (const PointType &Point) const
Return true if Point is inside the left bound of closed interval [Left;Right].
bool right (const PointType &Point) const
Return true if Point is inside the right bound of closed interval [Left;Right].
bool contains (const PointType &Point) const
Return true when Point is contained in interval [Left;Right].
Protected Types
using PointType = PointT
using ValueType = ValueT
Detailed Description
template<typename PointT, typename ValueT>
class llvm::IntervalData< PointT, ValueT >
An interval data composed by a Left and Right points and an associated Value.
PointT corresponds to the interval endpoints type. ValueT corresponds to the interval value type.
Definition at line 199 of file IntervalTree.h.
Member Typedef Documentation
PointType
template<typename PointT , typename ValueT > using llvm::IntervalData< PointT, ValueT >::PointType = PointT protected
Definition at line 201 of file IntervalTree.h.
ValueType
template<typename PointT , typename ValueT > using llvm::IntervalData< PointT, ValueT >::ValueType = ValueT protected
Definition at line 202 of file IntervalTree.h.
Constructor & Destructor Documentation
IntervalData() [1/2]
template<typename PointT , typename ValueT > llvm::IntervalData< PointT, ValueT >::IntervalData () delete
IntervalData() [2/2]
template<typename PointT , typename ValueT > llvm::IntervalData< PointT, ValueT >::IntervalData (PointType Left, PointType Right, ValueType Value) inline
Definition at line 211 of file IntervalTree.h.
References assert(), llvm::Left, and Right.
~IntervalData()
template<typename PointT , typename ValueT > virtual llvm::IntervalData< PointT, ValueT >::~IntervalData () virtual default
Member Function Documentation
contains()
template<typename PointT , typename ValueT > bool llvm::IntervalData< PointT, ValueT >::contains (const PointType & Point) const inline
Return true when Point is contained in interval [Left;Right].
This is Left <= Point <= Right for closed intervals.
Definition at line 230 of file IntervalTree.h.
References llvm::IntervalData< PointT, ValueT >::left(), and llvm::IntervalData< PointT, ValueT >::right().
left() [1/2]
template<typename PointT , typename ValueT > PointType llvm::IntervalData< PointT, ValueT >::left () const inline
Definition at line 216 of file IntervalTree.h.
References llvm::Left.
Referenced by llvm::IntervalData< PointT, ValueT >::contains().
left() [2/2]
template<typename PointT , typename ValueT > bool llvm::IntervalData< PointT, ValueT >::left (const PointType & Point) const inline
Return true if Point is inside the left bound of closed interval [Left;Right].
This is Left <= Point for closed intervals.
Definition at line 222 of file IntervalTree.h.
References llvm::IntervalData< PointT, ValueT >::left().
Referenced by llvm::IntervalData< PointT, ValueT >::left().
right() [1/2]
template<typename PointT , typename ValueT > PointType llvm::IntervalData< PointT, ValueT >::right () const inline
Definition at line 217 of file IntervalTree.h.
References Right.
Referenced by llvm::IntervalData< PointT, ValueT >::contains().
right() [2/2]
template<typename PointT , typename ValueT > bool llvm::IntervalData< PointT, ValueT >::right (const PointType & Point) const inline
Return true if Point is inside the right bound of closed interval [Left;Right].
This is Point <= Right for closed intervals.
Definition at line 226 of file IntervalTree.h.
References llvm::IntervalData< PointT, ValueT >::right().
Referenced by llvm::IntervalData< PointT, ValueT >::right().
value()
template<typename PointT , typename ValueT > ValueType llvm::IntervalData< PointT, ValueT >::value () const inline
Definition at line 218 of file IntervalTree.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/IntervalTree.h