LLVM: llvm::MachineInstrBuilder Class Reference
llvm::MachineInstrBuilder Class Reference
#include "llvm/CodeGen/MachineInstrBuilder.h"
Public Member Functions
MachineInstrBuilder ()=default
MachineInstrBuilder (MachineFunction &F, MachineInstr *I)
Create a MachineInstrBuilder for manipulating an existing instruction.
MachineInstrBuilder (MachineFunction &F, MachineBasicBlock::iterator I)
operator MachineInstr * () const
Allow automatic conversion to the machine instruction we are working on.
MachineInstr * operator-> () const
operator MachineBasicBlock::iterator () const
MachineInstr * getInstr () const
If conversion operators fail, use this method to get the MachineInstr explicitly.
Register getReg (unsigned Idx) const
Get the register for the operand index.
const MachineInstrBuilder & addReg (Register RegNo, unsigned flags=0, unsigned SubReg=0) const
Add a new virtual register operand.
const MachineInstrBuilder & addDef (Register RegNo, unsigned Flags=0, unsigned SubReg=0) const
Add a virtual register definition operand.
const MachineInstrBuilder & addUse (Register RegNo, unsigned Flags=0, unsigned SubReg=0) const
Add a virtual register use operand.
const MachineInstrBuilder & addImm (int64_t Val) const
Add a new immediate operand.
const MachineInstrBuilder & addCImm (const ConstantInt *Val) const
const MachineInstrBuilder & addFPImm (const ConstantFP *Val) const
const MachineInstrBuilder & addMBB (MachineBasicBlock *MBB, unsigned TargetFlags=0) const
const MachineInstrBuilder & addFrameIndex (int Idx) const
const MachineInstrBuilder & addConstantPoolIndex (unsigned Idx, int Offset=0, unsigned TargetFlags=0) const
const MachineInstrBuilder & addTargetIndex (unsigned Idx, int64_t Offset=0, unsigned TargetFlags=0) const
const MachineInstrBuilder & addJumpTableIndex (unsigned Idx, unsigned TargetFlags=0) const
const MachineInstrBuilder & addGlobalAddress (const GlobalValue *GV, int64_t Offset=0, unsigned TargetFlags=0) const
const MachineInstrBuilder & addExternalSymbol (const char *FnName, unsigned TargetFlags=0) const
const MachineInstrBuilder & addBlockAddress (const BlockAddress *BA, int64_t Offset=0, unsigned TargetFlags=0) const
const MachineInstrBuilder & addRegMask (const uint32_t *Mask) const
const MachineInstrBuilder & addMemOperand (MachineMemOperand *MMO) const
const MachineInstrBuilder & setMemRefs (ArrayRef< MachineMemOperand * > MMOs) const
const MachineInstrBuilder & cloneMemRefs (const MachineInstr &OtherMI) const
const MachineInstrBuilder & cloneMergedMemRefs (ArrayRef< const MachineInstr * > OtherMIs) const
const MachineInstrBuilder & add (const MachineOperand &MO) const
const MachineInstrBuilder & add (ArrayRef< MachineOperand > MOs) const
const MachineInstrBuilder & addMetadata (const MDNode *MD) const
const MachineInstrBuilder & addCFIIndex (unsigned CFIIndex) const
const MachineInstrBuilder & addIntrinsicID (Intrinsic::ID ID) const
const MachineInstrBuilder & addPredicate (CmpInst::Predicate Pred) const
const MachineInstrBuilder & addShuffleMask (ArrayRef< int > Val) const
const MachineInstrBuilder & addSym (MCSymbol *Sym, unsigned char TargetFlags=0) const
const MachineInstrBuilder & setMIFlags (unsigned Flags) const
const MachineInstrBuilder & setMIFlag (MachineInstr::MIFlag Flag) const
const MachineInstrBuilder & addDisp (const MachineOperand &Disp, int64_t off, unsigned char TargetFlags=0) const
const MachineInstrBuilder & setPCSections (MDNode *MD) const
const MachineInstrBuilder & copyImplicitOps (const MachineInstr &OtherMI) const
Copy all the implicit operands from OtherMI onto this one.
bool constrainAllUses (const TargetInstrInfo &TII, const TargetRegisterInfo &TRI, const RegisterBankInfo &RBI) const
Detailed Description
Definition at line 69 of file MachineInstrBuilder.h.
Constructor & Destructor Documentation
MachineInstrBuilder() [1/3]
llvm::MachineInstrBuilder::MachineInstrBuilder () default
MachineInstrBuilder() [2/3]
llvm::MachineInstrBuilder::MachineInstrBuilder (MachineFunction & F, MachineInstr * I) inline
Create a MachineInstrBuilder for manipulating an existing instruction.
F must be the machine function that was used to allocate I.
Definition at line 78 of file MachineInstrBuilder.h.
References MI.
MachineInstrBuilder() [3/3]
llvm::MachineInstrBuilder::MachineInstrBuilder (MachineFunction & F, MachineBasicBlock::iterator I) inline
Definition at line 79 of file MachineInstrBuilder.h.
References MI.
Member Function Documentation
add() [1/2]
const MachineInstrBuilder& llvm::MachineInstrBuilder::add (ArrayRef< MachineOperand > MOs) const inline
Definition at line 229 of file MachineInstrBuilder.h.
References MI.
add() [2/2]
const MachineInstrBuilder& llvm::MachineInstrBuilder::add (const MachineOperand & MO) const inline
Definition at line 224 of file MachineInstrBuilder.h.
References MI.
Referenced by llvm::InstrEmitter::AddDbgValueLocationOps(), llvm::addOffset(), addOperands(), AdjustBaseAndOffset(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::buildDbgValueForSpill(), llvm::BuildMI(), buildMUBUFOffsetLoadStore(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::ARMBaseInstrInfo::buildOutlinedFrame(), llvm::SIInstrInfo::buildShrunkInst(), CMSEPopCalleeSaves(), CMSEPushCalleeSaves(), CombineCVTAToLocal(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::SIInstrInfo::convertNonUniformIfRegion(), llvm::SIInstrInfo::convertNonUniformLoopRegion(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::RISCVInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::Thumb2InstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyToCPSR(), createPostIncLoadStore(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::emitARMRegPlusImmediate(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitFill(), emitIndirectDst(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostLd(), emitPostSt(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), llvm::emitT2RegPlusImmediate(), emitThumb2LoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::AArch64TargetLowering::EmitTileLoad(), emitVFCVT_RM_MASK(), emitVFROUND_NOEXCEPT_MASK(), llvm::AArch64TargetLowering::EmitZAInstr(), llvm::AArch64TargetLowering::EmitZero(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::M68kInstrInfo::ExpandPUSH_POP(), llvm::HexagonInstrInfo::expandVGatherPseudo(), llvm::RISCVInstrInfo::finalizeInsInstrs(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), foldVGPRCopyIntoRegSequence(), for(), forceReg(), FuseInst(), FuseTwoAddrInst(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), genIndexedMultiply(), llvm::MipsInstrInfo::genInstrWithNewOpc(), genNeg(), genTPEntry(), genTPLoopBody(), getIndirectSGPRIdx(), indirectCopyToAGPR(), INITIALIZE_PASS(), llvm::ARCInstrInfo::insertBranch(), llvm::CSKYInstrInfo::insertBranch(), llvm::WebAssemblyInstrInfo::insertBranch(), llvm::NVPTXInstrInfo::insertBranch(), llvm::LoongArchInstrInfo::insertBranch(), llvm::VEInstrInfo::insertBranch(), llvm::RISCVInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), insertSEH(), llvm::SIInstrInfo::insertVectorSelect(), llvm::SIInstrInfo::legalizeGenericOperand(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::SIInstrInfo::legalizeOperandsVOP2(), llvm::SIInstrInfo::legalizeOperandsVOP3(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), LowerCallResults(), llvm::ARMCallLowering::lowerReturn(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::SIInstrInfo::moveToVALU(), MSA2OpIntrinsicToGeneric(), MSA3OpIntrinsicToGeneric(), llvm::LegalizerHelper::narrowScalar(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::Thumb2InstrInfo::optimizeSelect(), llvm::RISCVInstrInfo::optimizeSelect(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), popRegsFromStack(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), pushRegsToStack(), llvm::X86InstrInfo::reMaterialize(), llvm::RevertDoLoopStart(), llvm::RevertLoopDec(), llvm::RevertLoopEnd(), RevertWhileLoopSetup(), llvm::RevertWhileLoopStartLR(), llvm::ARMBlockPlacement::revertWhileToDoLoop(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteT2FrameIndex(), selectMergeValues(), SelectMSA3OpIntrinsic(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), selectUnmergeValues(), llvm::FastISel::selectXRayCustomEvent(), llvm::FastISel::selectXRayTypedEvent(), llvm::ARMBaseInstrInfo::setExecutionDomain(), setM0ToIndexFromSGPR(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::tryFoldSPUpdateIntoPushPop(), and llvm::X86InstrInfo::unfoldMemoryOperand().
addBlockAddress()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addBlockAddress (const BlockAddress * BA, int64_t Offset = 0, unsigned TargetFlags = 0) const inline
Definition at line 190 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateBA(), MI, and llvm::Offset.
Referenced by addDisp(), and llvm::MachineIRBuilder::buildBlockAddress().
addCFIIndex()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addCFIIndex (unsigned CFIIndex) const inline
Definition at line 247 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateCFIIndex(), and MI.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), buildCFAOffs(), llvm::X86FrameLowering::BuildCFI(), buildDefCFAReg(), llvm::AArch64InstrInfo::buildOutlinedFrame(), convertCalleeSaveRestoreToSPPrePostIncDec(), emitCalleeSavedRestores(), EmitCfiOffset(), EmitDefCfaOffset(), EmitDefCfaRegister(), llvm::AArch64FrameLowering::emitEpilogue(), emitFrameOffsetAdj(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), emitShadowCallStackEpilogue(), emitShadowCallStackPrologue(), llvm::PPCFrameLowering::inlineStackProbe(), insertCFISameValue(), InsertReturnAddressAuth(), llvm::AArch64FrameLowering::resetCFIToInitialState(), llvm::CFIFixup::runOnMachineFunction(), and signOutlinedFunction().
addCImm()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addCImm (const ConstantInt * Val) const inline
Definition at line 136 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateCImm(), and MI.
Referenced by llvm::MachineIRBuilder::buildConstant(), and llvm::FastISel::selectIntrinsicCall().
addConstantPoolIndex()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addConstantPoolIndex (unsigned Idx, int Offset = 0, unsigned TargetFlags = 0) const inline
Definition at line 158 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateCPI(), MI, and llvm::Offset.
Referenced by llvm::addConstantPoolReference(), addDisp(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::XCoreInstrInfo::loadImmediate(), and llvm::ARMBaseInstrInfo::reMaterialize().
addDef()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addDef (Register RegNo, unsigned Flags = 0, unsigned SubReg = 0) const inline
Add a virtual register definition operand.
Definition at line 116 of file MachineInstrBuilder.h.
References addReg(), llvm::RegState::Define, and SubReg.
Referenced by llvm::DstOp::addDefToMIB(), llvm::CombinerHelper::applyCombineIndexedLoadStore(), llvm::CombinerHelper::applyExtendThroughPhis(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::buildAtomicCompareExchangeInst(), llvm::buildAtomicFlagInst(), llvm::buildAtomicLoadInst(), llvm::buildAtomicRMWInst(), llvm::MachineIRBuilder::buildBlockAddress(), llvm::MachineIRBuilder::buildConstant(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::SPIRVGlobalRegistry::buildConstantSampler(), llvm::buildEnqueueKernel(), llvm::MachineIRBuilder::buildFConstant(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), convertPtrToInt(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), emitLoad(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), emitStore(), llvm::AArch64TargetLowering::EmitZero(), llvm::VEInstrInfo::expandGetStackTopPseudo(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), expandPseudoLogM(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::LegalizerHelper::fewerElementsVectorUnmergeValues(), llvm::generateAsyncCopy(), llvm::generateConvertInst(), llvm::generateDotOrFMulInst(), llvm::generateEnqueueInst(), llvm::generateExtInst(), llvm::generateGroupInst(), llvm::generateImageMiscQueryInst(), llvm::generateImageSizeQueryInst(), llvm::generateLoadStoreInst(), llvm::generateReadImageInst(), llvm::generateRelationalInst(), llvm::generateSampleImageInst(), llvm::generateSpecConstantInst(), llvm::generateVectorLoadStoreInst(), genTPLoopBody(), llvm::SPIRVGlobalRegistry::getOrCreateConstInt(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), getOrCreateFrameHelper(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeByOpcode(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeDeviceEvent(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeImage(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypePipe(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampler(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVArrayType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getOrCreateUndef(), llvm::insertAssignInstr(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::AMDGPUCallLowering::lowerCall(), llvm::PPCRegisterInfo::lowerWACCSpilling(), llvm::LegalizerHelper::narrowScalar(), processInstr(), and llvm::RegBankSelect::repairReg().
addDisp()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addDisp (const MachineOperand & Disp, int64_t off, unsigned char TargetFlags = 0) const inline
Definition at line 284 of file MachineInstrBuilder.h.
References addBlockAddress(), addConstantPoolIndex(), addGlobalAddress(), addImm(), addJumpTableIndex(), assert(), llvm::MachineOperand::getBlockAddress(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, and llvm::MachineOperand::MO_JumpTableIndex.
Referenced by addOperands().
addExternalSymbol()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addExternalSymbol (const char * FnName, unsigned TargetFlags = 0) const inline
Definition at line 184 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateES(), and MI.
Referenced by addAsmInstr(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::ARCFrameLowering::emitEpilogue(), emitGPDisp(), llvm::ARMFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::VETargetLowering::prepareSymbol(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::FastISel::selectCall(), llvm::RISCVFrameLowering::spillCalleeSavedRegisters(), and llvm::WebAssemblyFrameLowering::writeSPToGlobal().
addFPImm()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addFPImm (const ConstantFP * Val) const inline
Definition at line 141 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateFPImm(), and MI.
Referenced by llvm::MachineIRBuilder::buildFConstant(), llvm::FastISel::fastEmitInst_f(), LowerFPToInt(), and llvm::FastISel::selectIntrinsicCall().
addFrameIndex()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addFrameIndex (int Idx) const inline
Definition at line 152 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateFI(), and MI.
Referenced by llvm::InstrEmitter::AddDbgValueLocationOps(), llvm::addFrameReference(), llvm::M68k::addFrameReference(), llvm::addFullAddress(), llvm::buildDbgValueForSpill(), llvm::MachineIRBuilder::buildFIDbgValue(), emitAlignedDPRCS2Restores(), emitBuildPairF64Pseudo(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), emitSplitF64Pseudo(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::LoongArchInstrInfo::loadRegFromStackSlot(), llvm::BPFInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::LanaiInstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), loadRegPairFromStackSlot(), llvm::RISCVRegisterInfo::materializeFrameBaseRegister(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::SIRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), storeRegPairToStackSlot(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::BPFInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::LanaiInstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), and llvm::SIInstrInfo::storeRegToStackSlot().
addGlobalAddress()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addGlobalAddress (const GlobalValue * GV, int64_t Offset = 0, unsigned TargetFlags = 0) const inline
Definition at line 177 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateGA(), MI, and llvm::Offset.
Referenced by addDisp(), llvm::addFullAddress(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::MipsFunctionInfo::initGlobalBaseReg(), INITIALIZE_PASS(), and llvm::ARMBaseInstrInfo::insertOutlinedCall().
addImm()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addImm (int64_t Val) const inline
Add a new immediate operand.
Definition at line 131 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateImm(), and MI.
Referenced by addAsmInstr(), llvm::addConstantPoolReference(), llvm::addDirectMem(), addDisp(), llvm::addFrameReference(), llvm::M68k::addFrameReference(), llvm::addFullAddress(), llvm::SITargetLowering::AddIMGInit(), addMemoryOperands(), llvm::addNumImm(), llvm::M68k::addOffset(), llvm::addOffset(), addOperandsForVFMK(), llvm::addPredicatedMveVpredNOp(), llvm::M68k::addRegIndirectWithDisp(), llvm::addRegReg(), llvm::SrcOp::addSrcToMIB(), llvm::addStringImm(), llvm::addUnpredicatedMveVpredNOp(), addZeroImm(), llvm::M68kInstrInfo::AddZExt(), AdjustBaseAndOffset(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::RISCVRegisterInfo::adjustReg(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::CombinerHelper::applyCombineIndexedLoadStore(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::Mips16InstrInfo::BuildAddiuSpImm(), llvm::MachineIRBuilder::buildAssertInstr(), llvm::SPIRVGlobalRegistry::buildConstantSampler(), llvm::buildDbgValueForSpill(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::buildEnqueueKernel(), llvm::MachineIRBuilder::buildFence(), llvm::MachineIRBuilder::buildFIDbgValue(), buildGitPtr(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::BuildMI(), buildMUBUFOffsetLoadStore(), llvm::buildOpDecorate(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), buildScratchExecCopy(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SITargetLowering::bundleInstWithWaitcnt(), llvm::PPCInstrInfo::commuteInstructionImpl(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::AArch64InstrInfo::copyGPRRegTuple(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::LanaiInstrInfo::copyPhysReg(), llvm::CSKYInstrInfo::copyPhysReg(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), llvm::VEInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), copyPhysSubRegs(), llvm::ARMBaseInstrInfo::copyToCPSR(), createPostIncLoadStore(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::AVRFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::emitARMRegPlusImmediate(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBuildPairF64Pseudo(), llvm::SIFrameLowering::emitCSRSpillRestores(), llvm::SIFrameLowering::emitCSRSpillStores(), llvm::InstrEmitter::EmitDbgValueFromSingleOp(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::LanaiFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogueInsns(), llvm::AArch64TargetLowering::EmitF128CSEL(), emitFrameOffsetAdj(), emitFROUND(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), emitIncrement(), emitIndirectDst(), emitIndirectSrc(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), emitLoad(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitLoadM0FromVGPRLoop(), emitLoadSRsrcFromVGPRLoop(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostLd(), emitPostSt(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::AVRFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), llvm::VEFrameLowering::emitPrologueInsns(), emitReadCycleWidePseudo(), emitRegUpdate(), emitSCSEpilogue(), emitSCSPrologue(), emitShadowCallStackEpilogue(), emitShadowCallStackPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::VETargetLowering::emitSjLjDispatchBlock(), emitSplitF64Pseudo(), llvm::X86FrameLowering::emitSPUpdate(), llvm::M68kFrameLowering::emitSPUpdate(), llvm::X86FrameLowering::emitStackProbe(), emitStore(), llvm::emitT2RegPlusImmediate(), emitThumb1LoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), emitVFCVT_RM_MASK(), emitXBegin(), llvm::SIInstrInfo::enforceOperandRCAlignment(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::VEInstrInfo::expandGetStackTopPseudo(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::SIInstrInfo::expandMovDPP64(), llvm::M68kInstrInfo::ExpandMOVEM(), ExpandMOVImmSExti8(), expandNOVLXStore(), llvm::SparcInstrInfo::expandPostRAPseudo(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), expandSHXDROT(), llvm::HexagonInstrInfo::expandVGatherPseudo(), extractRsrcPtr(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rri(), llvm::finishBuildOpDecorate(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), forceReg(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), generateEndPgm(), llvm::generateExtInst(), llvm::generateGroupInst(), llvm::generateImageSizeQueryInst(), llvm::generateReadImageInst(), llvm::generateSampleImageInst(), generateStackAdjustment(), llvm::generateVectorLoadStoreInst(), genFusedMultiply(), genIndexedMultiply(), llvm::MipsInstrInfo::genInstrWithNewOpc(), genTPEntry(), genTPLoopBody(), getIndirectSGPRIdx(), getOrCreateFrameHelper(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeImage(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypePipe(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SITargetLowering::getPrefLoopAlignment(), llvm::RISCVInstrInfo::getVLENFactoredAmount(), IfNeededExtSP(), IfNeededLDAWSP(), INITIALIZE_PASS(), llvm::SystemZELFFrameLowering::inlineStackProbe(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::SystemZXPLINKFrameLowering::inlineStackProbe(), llvm::MSP430InstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::LanaiInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::SystemZInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), insertDivByZeroTrap(), llvm::SIInstrInfo::insertEQ(), InsertFPImmInst(), llvm::LoongArchInstrInfo::insertIndirectBranch(), InsertLDR_STR(), llvm::insertMultibyteShift(), llvm::SIInstrInfo::insertNE(), llvm::SIInstrInfo::insertNoops(), insertNoopsInBundle(), llvm::MipsInstrInfo::insertNop(), insertNopBeforeInstruction(), llvm::AArch64InstrInfo::insertOutlinedCall(), llvm::SIInstrInfo::insertReturn(), insertSEH(), InsertSEH(), llvm::AArch64InstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::SIInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), InsertSPConstInst(), InsertSPImmInst(), llvm::SIInstrInfo::insertVectorSelect(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::XCoreInstrInfo::loadImmediate(), llvm::Mips16InstrInfo::loadImmediate(), llvm::ARCInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::LoongArchInstrInfo::loadRegFromStackSlot(), llvm::BPFInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::LanaiInstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), loadRegPairFromStackSlot(), llvm::X86InstrInfo::loadStoreTileReg(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::AMDGPUCallLowering::lowerCall(), LowerCallResults(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), LowerFPToInt(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::X86CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerTailCall(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), llvm::Mips16InstrInfo::makeFrame(), MakeM0Inst(), llvm::RISCVRegisterInfo::materializeFrameBaseRegister(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::SIRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::SIInstrInfo::materializeImmediate(), llvm::PPCInstrInfo::materializeImmPostRA(), llvm::ARMBlockPlacement::moveBasicBlock(), llvm::SIInstrInfo::moveToVALU(), llvm::LoongArchInstrInfo::movImm(), llvm::RISCVInstrInfo::movImm(), llvm::CSKYInstrInfo::movImm(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::RISCVInstrInfo::optimizeSelect(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::SGPRSpillBuilder::prepare(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::VETargetLowering::prepareMBB(), llvm::VETargetLowering::prepareSymbol(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), llvm::ARMBaseInstrInfo::reMaterialize(), llvm::X86InstrInfo::reMaterialize(), llvm::X86InstrInfo::replaceBranchWithTailCall(), replaceFI(), replaceFrameIndex(), llvm::PPCInstrInfo::replaceInstrWithLI(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::M68kFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), llvm::Mips16InstrInfo::restoreFrame(), llvm::SIRegisterInfo::restoreSGPR(), RestoreSpillList(), llvm::restoreStatusRegister(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), llvm::RevertLoopDec(), llvm::RevertLoopEnd(), RevertWhileLoopSetup(), llvm::RevertWhileLoopStartLR(), llvm::FastISel::selectCall(), selectCopy(), llvm::FastISel::selectIntrinsicCall(), llvm::FastISel::selectStackmap(), llvm::ARMBaseInstrInfo::setExecutionDomain(), setM0ToIndexFromSGPR(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::M68kFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillEmergencySGPR(), llvm::SIRegisterInfo::spillSGPR(), storeRegPairToStackSlot(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::BPFInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::LanaiInstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), and llvm::SIInstrInfo::storeRegToStackSlot().
addIntrinsicID()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addIntrinsicID (Intrinsic::ID ID) const inline
Definition at line 252 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateIntrinsicID(), and MI.
addJumpTableIndex()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addJumpTableIndex (unsigned Idx, unsigned TargetFlags = 0) const inline
Definition at line 171 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateJTI(), and MI.
Referenced by addDisp(), llvm::MachineIRBuilder::buildBrJT(), and llvm::VETargetLowering::emitSjLjDispatchBlock().
addMBB()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addMBB (MachineBasicBlock * MBB, unsigned TargetFlags = 0) const inline
Definition at line 146 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateMBB(), MBB, and MI.
Referenced by addIncomingValuesToPHIs(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::AddPHIOperand(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::AVRInstrInfo::analyzeBranch(), llvm::M68kInstrInfo::AnalyzeBranchImpl(), llvm::CombinerHelper::applyExtendThroughPhis(), llvm::MachineIRBuilder::buildBr(), llvm::SIInstrInfo::convertNonUniformLoopRegion(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), emitFROUND(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), emitLoadM0FromVGPRLoop(), emitLoadSRsrcFromVGPRLoop(), EmitLoweredCascadedSelect(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCTargetLowering::emitProbedAlloca(), emitReadCycleWidePseudo(), emitSelectPseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::VETargetLowering::emitSjLjDispatchBlock(), emitXBegin(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), genTPEntry(), genTPLoopBody(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), INITIALIZE_PASS(), llvm::SystemZELFFrameLowering::inlineStackProbe(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::SystemZXPLINKFrameLowering::inlineStackProbe(), llvm::XCoreInstrInfo::insertBranch(), llvm::BPFInstrInfo::insertBranch(), llvm::ARCInstrInfo::insertBranch(), llvm::CSKYInstrInfo::insertBranch(), llvm::WebAssemblyInstrInfo::insertBranch(), llvm::NVPTXInstrInfo::insertBranch(), llvm::MSP430InstrInfo::insertBranch(), llvm::LoongArchInstrInfo::insertBranch(), llvm::MipsInstrInfo::insertBranch(), llvm::VEInstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::RISCVInstrInfo::insertBranch(), llvm::AVRInstrInfo::insertBranch(), llvm::HexagonInstrInfo::insertBranch(), llvm::LanaiInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::R600InstrInfo::insertBranch(), llvm::AArch64InstrInfo::insertBranch(), llvm::SystemZInstrInfo::insertBranch(), llvm::M68kInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), insertDivByZeroTrap(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::AVRInstrInfo::insertIndirectBranch(), insertPHI(), LowerFPToInt(), llvm::ARMBlockPlacement::moveBasicBlock(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::VETargetLowering::prepareMBB(), llvm::RevertWhileLoopStartLR(), splitEdge(), and splitMBB().
addMemOperand()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addMemOperand (MachineMemOperand * MMO) const inline
Definition at line 202 of file MachineInstrBuilder.h.
References MI.
Referenced by llvm::addFrameReference(), llvm::M68k::addFrameReference(), llvm::M68k::addMemOperand(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::MachineIRBuilder::buildMemTransferInst(), emitBuildPairF64Pseudo(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), emitSplitF64Pseudo(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::SystemZELFFrameLowering::inlineStackProbe(), InsertFPConstInst(), InsertFPImmInst(), InsertSPConstInst(), InsertSPImmInst(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::LoongArchInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), loadRegPairFromStackSlot(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), replaceFrameIndex(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), RestoreSpillList(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), storeRegPairToStackSlot(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), and llvm::AArch64GISelUtils::tryEmitBZero().
addMetadata()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addMetadata (const MDNode * MD) const inline
Definition at line 236 of file MachineInstrBuilder.h.
References assert(), llvm::MachineOperand::CreateMetadata(), and MI.
Referenced by llvm::buildDbgValueForSpill(), llvm::MachineIRBuilder::buildFIDbgValue(), llvm::BuildMI(), llvm::InstrEmitter::EmitDbgLabel(), llvm::InstrEmitter::EmitDbgValueFromSingleOp(), llvm::InstrEmitter::EmitDbgValueList(), llvm::FastISel::selectCall(), and llvm::FastISel::selectIntrinsicCall().
addPredicate()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addPredicate (CmpInst::Predicate Pred) const inline
Definition at line 257 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreatePredicate(), and MI.
Referenced by llvm::SrcOp::addSrcToMIB().
addReg()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addReg (Register RegNo, unsigned flags = 0, unsigned SubReg = 0) const inline
Add a new virtual register operand.
Definition at line 97 of file MachineInstrBuilder.h.
References assert(), llvm::MachineOperand::CreateReg(), llvm::RegState::Dead, llvm::RegState::Debug, llvm::RegState::Define, llvm::RegState::EarlyClobber, llvm::RegState::Implicit, llvm::RegState::InternalRead, llvm::RegState::Kill, MI, llvm::RegState::Renamable, SubReg, and llvm::RegState::Undef.
Referenced by llvm::addConstantPoolReference(), llvm::InstrEmitter::AddDbgValueLocationOps(), addDef(), llvm::addDirectMem(), llvm::ARMBaseInstrInfo::AddDReg(), addExclusiveRegPair(), llvm::addFrameReference(), llvm::addFullAddress(), llvm::SITargetLowering::AddIMGInit(), addIncomingValuesToPHIs(), llvm::MachineBasicBlock::addLiveIn(), llvm::addOffset(), addOperandsForVFMK(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::AddPHIOperand(), llvm::addPredicatedMveVpredNOp(), llvm::addPredicatedMveVpredROp(), llvm::M68k::addRegIndirectWithDisp(), llvm::addRegOffset(), llvm::addRegReg(), addSavedGPR(), addSaveRestoreRegs(), llvm::M68kInstrInfo::AddSExt(), AddSubReg(), llvm::addUnpredicatedMveVpredNOp(), llvm::addUnpredicatedMveVpredROp(), addUse(), llvm::M68kInstrInfo::AddZExt(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::RISCVRegisterInfo::adjustReg(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::SIInstrInfo::buildExtractSubReg(), buildGitPtr(), llvm::BuildMI(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::X86InstrInfo::classifyLEAReg(), CMSEPopCalleeSaves(), CMSEPushCalleeSaves(), CombineCVTAToLocal(), combineFPFusedMultiply(), llvm::PPCInstrInfo::commuteInstructionImpl(), llvm::constrainOperandRegClass(), llvm::FastISel::constrainOperandRegClass(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::SIInstrInfo::convertNonUniformIfRegion(), llvm::SIInstrInfo::convertNonUniformLoopRegion(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::AArch64InstrInfo::copyGPRRegTuple(), llvm::LoongArchInstrInfo::copyPhysReg(), llvm::BPFInstrInfo::copyPhysReg(), llvm::MSP430InstrInfo::copyPhysReg(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::Thumb2InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::WebAssemblyInstrInfo::copyPhysReg(), llvm::LanaiInstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::CSKYInstrInfo::copyPhysReg(), llvm::RISCVInstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), llvm::ARCInstrInfo::copyPhysReg(), llvm::R600InstrInfo::copyPhysReg(), llvm::AVRInstrInfo::copyPhysReg(), llvm::VEInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::M68kInstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), copyPhysSubRegs(), llvm::ARMBaseInstrInfo::copyToCPSR(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::SIInstrInfo::createPHIDestinationCopy(), llvm::TargetInstrInfo::createPHIDestinationCopy(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::SIInstrInfo::createPHISourceCopy(), llvm::TargetInstrInfo::createPHISourceCopy(), createPostIncLoadStore(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::AVRFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::emitARMRegPlusImmediate(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBuildPairF64Pseudo(), llvm::SIFrameLowering::emitCSRSpillRestores(), llvm::SIFrameLowering::emitCSRSpillStores(), llvm::InstrEmitter::EmitDbgValueFromSingleOp(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::LanaiFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogueInsns(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AArch64TargetLowering::EmitFill(), emitFrameOffsetAdj(), emitFROUND(), emitGPDisp(), llvm::SITargetLowering::emitGWSMemViolTestLoop(), emitIncrement(), emitIndirectDst(), emitIndirectSrc(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::MachineRegisterInfo::EmitLiveInCopies(), emitLoad(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitLoadM0FromVGPRLoop(), emitLoadSRsrcFromVGPRLoop(), EmitLoweredCascadedSelect(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), emitPostLd(), emitPostSt(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::AVRFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), llvm::VEFrameLowering::emitPrologueInsns(), emitQuietFCMP(), emitReadCycleWidePseudo(), emitRegUpdate(), emitSCSEpilogue(), emitSCSPrologue(), emitSelectPseudo(), emitShadowCallStackEpilogue(), emitShadowCallStackPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::X86FrameLowering::emitSPUpdate(), llvm::M68kFrameLowering::emitSPUpdate(), emitStore(), llvm::emitT2RegPlusImmediate(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::AArch64TargetLowering::EmitTileLoad(), emitVFCVT_RM_MASK(), emitVFROUND_NOEXCEPT_MASK(), emitXBegin(), llvm::AArch64TargetLowering::EmitZAInstr(), llvm::SIInstrInfo::enforceOperandRCAlignment(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), Expand2AddrKreg(), Expand2AddrUndef(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::VEInstrInfo::expandGetStackTopPseudo(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), expandMOV32r1(), llvm::SIInstrInfo::expandMovDPP64(), llvm::M68kInstrInfo::ExpandMOVEM(), llvm::M68kInstrInfo::ExpandMOVSZX_RR(), llvm::SparcInstrInfo::expandPostRAPseudo(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::M68kInstrInfo::ExpandPUSH_POP(), llvm::SparcTargetLowering::expandSelectCC(), expandSGPRCopy(), expandSHXDROT(), llvm::HexagonInstrInfo::expandVGatherPseudo(), expandXorFP(), extractRsrcPtr(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::FastISel::fastEmitInst_f(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_r(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rr(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrr(), llvm::finalizeBundle(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldVGPRCopyIntoRegSequence(), forceReg(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), generateEndPgm(), generateStackAdjustment(), genFusedMultiply(), genIndexedMultiply(), genMaddR(), genSubAdd2SubSub(), genTPEntry(), genTPLoopBody(), llvm::SIInstrInfo::getAddNoCarry(), llvm::getFunctionLiveInPhysReg(), llvm::CSKYInstrInfo::getGlobalBaseReg(), getOrCreateFrameHelper(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::RISCVInstrInfo::getVLENFactoredAmount(), indirectCopyToAGPR(), llvm::MipsFunctionInfo::initGlobalBaseReg(), INITIALIZE_PASS(), llvm::SystemZELFFrameLowering::inlineStackProbe(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::SystemZXPLINKFrameLowering::inlineStackProbe(), llvm::XCoreInstrInfo::insertBranch(), llvm::HexagonInstrInfo::insertBranch(), llvm::R600InstrInfo::insertBranch(), insertCopy(), insertCSRRestores(), insertCSRSaves(), insertDivByZeroTrap(), llvm::SIInstrInfo::insertEQ(), InsertFPConstInst(), InsertFPImmInst(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), InsertLDR_STR(), llvm::insertMultibyteShift(), llvm::SIInstrInfo::insertNE(), llvm::MipsInstrInfo::insertNop(), llvm::AArch64InstrInfo::insertOutlinedCall(), insertPHI(), llvm::AArch64InstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::SIInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), InsertSPConstInst(), InsertSPImmInst(), llvm::SIInstrInfo::insertVectorSelect(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::Mips16InstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), loadM0FromVGPR(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), loadRegPairFromStackSlot(), llvm::X86InstrInfo::loadStoreTileReg(), llvm::PPCRegisterInfo::lowerACCRestore(), llvm::PPCRegisterInfo::lowerACCSpilling(), LowerCallResults(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), LowerFPToInt(), llvm::PPCRegisterInfo::lowerPrepareProbedAlloca(), llvm::PPCRegisterInfo::lowerQuadwordSpilling(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), llvm::PPCRegisterInfo::lowerWACCRestore(), llvm::PPCRegisterInfo::lowerWACCSpilling(), llvm::Mips16InstrInfo::makeFrame(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), llvm::SIRegisterInfo::materializeFrameBaseRegister(), llvm::PPCInstrInfo::materializeImmPostRA(), moveAndTeeForMultiUse(), llvm::ARMBlockPlacement::moveBasicBlock(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::SIInstrInfo::moveToVALU(), llvm::LoongArchInstrInfo::movImm(), llvm::CSKYInstrInfo::movImm(), llvm::RISCVInstrInfo::movImm(), llvm::PPCInstrInfo::optimizeCmpPostRA(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), popRegsFromStack(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::SGPRSpillBuilder::prepare(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::VETargetLowering::prepareMBB(), llvm::VETargetLowering::prepareSymbol(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::SwiftErrorValueTracking::propagateVRegs(), pushRegsToStack(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), llvm::SGPRSpillBuilder::readWriteTmpVGPR(), llvm::TargetInstrInfo::reassociateOps(), llvm::X86InstrInfo::replaceBranchWithTailCall(), replaceFI(), replaceFrameIndex(), llvm::PPCInstrInfo::replaceInstrWithLI(), reportIllegalCopy(), llvm::SGPRSpillBuilder::restore(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), restoreCRs(), llvm::Mips16InstrInfo::restoreFrame(), llvm::SIRegisterInfo::restoreSGPR(), llvm::restoreStatusRegister(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), llvm::RevertLoopDec(), llvm::RevertLoopEnd(), RevertWhileLoopSetup(), llvm::RevertWhileLoopStartLR(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::FastISel::selectFreeze(), setCallTargetReg(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::VETargetLowering::setupEntryBlockForSjLj(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillEmergencySGPR(), spillRegPairs(), llvm::SIRegisterInfo::spillSGPR(), spillVGPRtoAGPR(), splitMBB(), storeRegPairToStackSlot(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::BPFInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::LanaiInstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::M68kInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::unfoldMemoryOperand(), unstackifyVRegsUsedInSplitBB(), UpdatePredRedefs(), and llvm::WebAssemblyFrameLowering::writeSPToGlobal().
addRegMask()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addRegMask (const uint32_t * Mask) const inline
Definition at line 197 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateRegMask(), llvm::BitmaskEnumDetail::Mask(), and MI.
Referenced by llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), and llvm::SystemZInstrInfo::PredicateInstruction().
addShuffleMask()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addShuffleMask (ArrayRef< int > Val) const inline
Definition at line 262 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateShuffleMask(), and MI.
addSym()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addSym (MCSymbol * Sym, unsigned char TargetFlags = 0) const inline
Definition at line 267 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateMCSymbol(), and MI.
Referenced by llvm::MipsInstrInfo::genInstrWithNewOpc(), llvm::SIInstrInfo::insertIndirectBranch(), and LowerCallResults().
addTargetIndex()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addTargetIndex (unsigned Idx, int64_t Offset = 0, unsigned TargetFlags = 0) const inline
Definition at line 164 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateTargetIndex(), MI, and llvm::Offset.
addUse()
const MachineInstrBuilder& llvm::MachineInstrBuilder::addUse (Register RegNo, unsigned Flags = 0, unsigned SubReg = 0) const inline
Add a virtual register use operand.
It is an error for Flags to contain RegState::Define when calling this function.
Definition at line 123 of file MachineInstrBuilder.h.
References addReg(), assert(), llvm::RegState::Define, and SubReg.
Referenced by llvm::SrcOp::addSrcToMIB(), llvm::CombinerHelper::applyCombineIndexedLoadStore(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::buildAtomicCompareExchangeInst(), llvm::buildAtomicFlagInst(), llvm::buildAtomicInitInst(), llvm::buildAtomicLoadInst(), llvm::buildAtomicRMWInst(), llvm::buildAtomicStoreInst(), llvm::buildBarrierInst(), llvm::MachineIRBuilder::buildBrIndirect(), llvm::MachineIRBuilder::buildBrJT(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::SPIRVGlobalRegistry::buildConstantSampler(), llvm::buildEnqueueKernel(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::buildOpDecorate(), llvm::buildOpName(), convertPtrToInt(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), expandPseudoLogM(), llvm::LegalizerHelper::fewerElementsVectorUnmergeValues(), llvm::RISCVInstrInfo::finalizeInsInstrs(), llvm::generateAsyncCopy(), llvm::generateConvertInst(), llvm::generateDotOrFMulInst(), llvm::generateEnqueueInst(), llvm::generateExtInst(), llvm::generateGroupInst(), llvm::generateImageMiscQueryInst(), llvm::generateImageSizeQueryInst(), llvm::generateLoadStoreInst(), llvm::generateReadImageInst(), llvm::generateRelationalInst(), llvm::generateSampleImageInst(), llvm::generateSpecConstantInst(), llvm::generateVectorLoadStoreInst(), llvm::generateWriteImageInst(), genTPEntry(), genTPLoopBody(), llvm::genWorkgroupQuery(), llvm::SPIRVGlobalRegistry::getOrCreateConstInt(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), getOrCreateFrameHelper(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeImage(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVArrayType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getOrCreateUndef(), llvm::insertAssignInstr(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerReturn(), llvm::LegalizerHelper::narrowScalar(), processInstr(), llvm::RegBankSelect::repairReg(), and selectCopy().
cloneMemRefs()
const MachineInstrBuilder& llvm::MachineInstrBuilder::cloneMemRefs (const MachineInstr & OtherMI) const inline
Definition at line 213 of file MachineInstrBuilder.h.
References MI.
Referenced by AdjustBaseAndOffset(), buildMUBUFOffsetLoadStore(), createPostIncLoadStore(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::MipsInstrInfo::genInstrWithNewOpc(), InsertLDR_STR(), and llvm::ARMBaseInstrInfo::reMaterialize().
cloneMergedMemRefs()
const MachineInstrBuilder& llvm::MachineInstrBuilder::cloneMergedMemRefs (ArrayRef< const MachineInstr * > OtherMIs) const inline
Definition at line 219 of file MachineInstrBuilder.h.
References MI.
constrainAllUses()
bool llvm::MachineInstrBuilder::constrainAllUses (const TargetInstrInfo & TII, const TargetRegisterInfo & TRI, const RegisterBankInfo & RBI) const inline
Definition at line 326 of file MachineInstrBuilder.h.
References llvm::constrainSelectedInstRegOperands(), MI, TII, and TRI.
Referenced by llvm::MipsCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerReturn(), and SelectMSA3OpIntrinsic().
copyImplicitOps()
const MachineInstrBuilder& llvm::MachineInstrBuilder::copyImplicitOps (const MachineInstr & OtherMI) const inline
Copy all the implicit operands from OtherMI onto this one.
Definition at line 321 of file MachineInstrBuilder.h.
References MI.
Referenced by llvm::RISCVInstrInfo::convertToThreeAddress(), llvm::M68kInstrInfo::ExpandMOVEM(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::MipsInstrInfo::genInstrWithNewOpc(), InsertReturnAddressAuth(), llvm::LanaiInstrInfo::optimizeSelect(), popRegsFromStack(), llvm::X86InstrInfo::replaceBranchWithTailCall(), and signOutlinedFunction().
getInstr()
MachineInstr* llvm::MachineInstrBuilder::getInstr () const inline
If conversion operators fail, use this method to get the MachineInstr explicitly.
Definition at line 89 of file MachineInstrBuilder.h.
References MI.
Referenced by buildMUBUFOffsetLoadStore(), llvm::VEInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), copyPhysSubRegs(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), expandLoadStackGuard(), expandMOV32r1(), llvm::M68kInstrInfo::ExpandMOVEM(), ExpandMOVImmSExti8(), llvm::M68kInstrInfo::ExpandMOVSZX_RM(), llvm::M68kInstrInfo::ExpandMOVSZX_RR(), llvm::M68kInstrInfo::ExpandMOVX_RR(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::M68kInstrInfo::ExpandPUSH_POP(), llvm::XCoreInstrInfo::loadImmediate(), llvm::ARCInstrInfo::loadImmediate(), LowerCallResults(), and llvm::ARMBlockPlacement::moveBasicBlock().
getReg()
Register llvm::MachineInstrBuilder::getReg (unsigned Idx) const inline
Get the register for the operand index.
The operand at the index should be a register (asserted by MachineOperand).
Definition at line 94 of file MachineInstrBuilder.h.
References MI.
Referenced by llvm::CombinerHelper::applyCombineShiftToUnmerge(), llvm::CombinerHelper::applyCombineTruncOfShift(), llvm::CombinerHelper::applyCombineUnmergeMergeToPlainValues(), llvm::CombinerHelper::applyCombineUnmergeWithDeadLanesToTrunc(), llvm::CombinerHelper::applyCombineUnmergeZExtToZExt(), llvm::CombinerHelper::applyFsubToFneg(), llvm::CombinerHelper::applyRotateOutOfRange(), llvm::CombinerHelper::applyShiftImmedChain(), llvm::CombinerHelper::applyShiftOfShiftedLogic(), llvm::CombinerHelper::applyTruncStoreMerge(), llvm::LegalizerHelper::bitcastExtractVectorElt(), llvm::LegalizerHelper::bitcastInsertVectorElt(), llvm::LegalizerHelper::bitcastSrc(), buildAnyextOrCopy(), llvm::CallLowering::IncomingValueHandler::buildExtensionHint(), llvm::CSEMIRBuilder::buildInstr(), buildLogBase2(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), llvm::LegalizerHelper::coerceToScalar(), llvm::SIRegisterInfo::eliminateFrameIndex(), equalizeVectorShuffleLengths(), Expand2AddrUndef(), expandLoadStackGuard(), expandMOV32r1(), ExpandMOVImmSExti8(), expandNOVLXLoad(), expandNOVLXStore(), llvm::X86InstrInfo::expandPostRAPseudo(), expandSHXDROT(), llvm::CallLowering::ValueHandler::extendRegister(), llvm::LegalizerHelper::fewerElementsVectorMerge(), llvm::LegalizerHelper::fewerElementsVectorReductions(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), llvm::PeelingModuloScheduleExpander::filterInstructions(), llvm::VEInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::FoldImmediate(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SIInstrInfo::FoldImmediate(), getMemsetValue(), getPHIDeps(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::LegalizerHelper::getVectorElementPointer(), llvm::CallLowering::insertSRetOutgoingArgument(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::LegalizerHelper::lowerAbsToMaxNeg(), llvm::LegalizerHelper::lowerAddSubSatToMinMax(), llvm::LegalizerHelper::lowerBitcast(), llvm::AArch64CallLowering::lowerCall(), llvm::LegalizerHelper::lowerExtract(), llvm::LegalizerHelper::lowerFCopySign(), llvm::LegalizerHelper::lowerFMinNumMaxNum(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::LegalizerHelper::lowerFunnelShiftAsShifts(), llvm::LegalizerHelper::lowerFunnelShiftWithInverse(), llvm::LegalizerHelper::lowerInsert(), llvm::LegalizerHelper::lowerMergeValues(), llvm::AArch64CallLowering::lowerReturn(), llvm::LegalizerHelper::lowerSelect(), llvm::LegalizerHelper::lowerShuffleVector(), llvm::LegalizerHelper::lowerStore(), lowerVectorFCMP(), llvm::CombinerHelper::matchCombineExtendingLoads(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::LegalizerHelper::moreElementsVectorSrc(), llvm::LegalizerHelper::narrowScalar(), llvm::PPCInstrInfo::onlyFoldImmediate(), llvm::AMDGPUCallLowering::passSpecialInputs(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), selectMergeValues(), and selectUnmergeValues().
operator MachineBasicBlock::iterator()
llvm::MachineInstrBuilder::operator MachineBasicBlock::iterator () const inline
Definition at line 85 of file MachineInstrBuilder.h.
References MI.
operator MachineInstr *()
llvm::MachineInstrBuilder::operator MachineInstr * () const inline
Allow automatic conversion to the machine instruction we are working on.
Definition at line 83 of file MachineInstrBuilder.h.
References MI.
operator->()
MachineInstr* llvm::MachineInstrBuilder::operator-> () const inline
Definition at line 84 of file MachineInstrBuilder.h.
References MI.
setMemRefs()
const MachineInstrBuilder& llvm::MachineInstrBuilder::setMemRefs (ArrayRef< MachineMemOperand * > MMOs) const inline
Definition at line 208 of file MachineInstrBuilder.h.
References MI.
Referenced by convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), INITIALIZE_PASS(), and llvm::X86InstrInfo::unfoldMemoryOperand().
setMIFlag()
const MachineInstrBuilder& llvm::MachineInstrBuilder::setMIFlag (MachineInstr::MIFlag Flag) const inline
Definition at line 278 of file MachineInstrBuilder.h.
References MI.
Referenced by llvm::RISCVRegisterInfo::adjustReg(), llvm::X86FrameLowering::BuildCFI(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitEpilogue(), emitFrameOffsetAdj(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), emitLoad(), llvm::AVRFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), emitSCSEpilogue(), emitSCSPrologue(), emitShadowCallStackEpilogue(), emitShadowCallStackPrologue(), llvm::X86FrameLowering::emitSPUpdate(), emitStore(), llvm::finalizeBundle(), getOrCreateFrameHelper(), llvm::RISCVInstrInfo::getVLENFactoredAmount(), InsertReturnAddressAuth(), InsertSEH(), llvm::LoongArchInstrInfo::movImm(), llvm::RISCVInstrInfo::movImm(), popRegsFromStack(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::M68kFrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), signOutlinedFunction(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::RISCVFrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), and llvm::M68kFrameLowering::spillCalleeSavedRegisters().
setMIFlags()
const MachineInstrBuilder& llvm::MachineInstrBuilder::setMIFlags (unsigned Flags) const inline
Definition at line 273 of file MachineInstrBuilder.h.
References MI.
Referenced by llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::SIInstrInfo::buildShrunkInst(), combineFPFusedMultiply(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::emitARMRegPlusImmediate(), emitCalleeSavedRestores(), llvm::AArch64FrameLowering::emitEpilogue(), emitFrameOffsetAdj(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), emitShadowCallStackEpilogue(), llvm::emitT2RegPlusImmediate(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::insertAssignInstr(), InsertReturnAddressAuth(), insertSEH(), llvm::SIInstrInfo::moveToVALU(), llvm::CSKYInstrInfo::movImm(), pushRegsToStack(), llvm::TargetInstrInfo::reassociateOps(), signOutlinedFunction(), and llvm::ARMFrameLowering::spillCalleeSavedRegisters().
setPCSections()
const MachineInstrBuilder& llvm::MachineInstrBuilder::setPCSections (MDNode * MD) const inline
Definition at line 313 of file MachineInstrBuilder.h.
References MI.
Referenced by llvm::BuildMI().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineInstrBuilder.h