LLVM: llvm::MemorySSA Class Reference
llvm::MemorySSA Class Reference
Encapsulates MemorySSA, including all data associated with memory accesses.
#include "llvm/Analysis/MemorySSA.h"
Classes
class CachingWalker
A MemorySSAWalker that does AA walks to disambiguate accesses.
class ClobberWalkerBase
class OptimizeUses
This class is a batch walker of all MemoryUse's in the program, and points their defining access at the thing that actually clobbers them.
class SkipSelfWalker
Public Types
enum VerificationLevel { VerificationLevel::Fast, VerificationLevel::Full }
enum InsertionPlace { Beginning, End, BeforeTerminator }
Used in various insertion functions to specify whether we are talking about the beginning or end of a block.
using AccessList = iplist< MemoryAccess, ilist_tag< MSSAHelpers::AllAccessTag > >
using DefsList = simple_ilist< MemoryAccess, ilist_tag< MSSAHelpers::DefsOnlyTag > >
Public Member Functions
MemorySSA (Function &, AliasAnalysis *, DominatorTree *)
MemorySSA (MemorySSA &&)=delete
~MemorySSA ()
MemorySSAWalker * getWalker ()
MemorySSAWalker * getSkipSelfWalker ()
MemoryUseOrDef * getMemoryAccess (const Instruction *I) const
Given a memory Mod/Ref'ing instruction, get the MemorySSA access associated with it.
MemoryPhi * getMemoryAccess (const BasicBlock *BB) const
DominatorTree & getDomTree () const
void dump () const
void print (raw_ostream &) const
bool isLiveOnEntryDef (const MemoryAccess *MA) const
Return true if MA represents the live on entry value.
MemoryAccess * getLiveOnEntryDef () const
const AccessList * getBlockAccesses (const BasicBlock *BB) const
Return the list of MemoryAccess's for a given basic block.
const DefsList * getBlockDefs (const BasicBlock *BB) const
Return the list of MemoryDef's and MemoryPhi's for a given basic block.
bool locallyDominates (const MemoryAccess *A, const MemoryAccess *B) const
Given two memory accesses in the same basic block, determine whether MemoryAccess A dominates MemoryAccess B.
bool dominates (const MemoryAccess *A, const MemoryAccess *B) const
Given two memory accesses in potentially different blocks, determine whether MemoryAccess A dominates MemoryAccess B.
bool dominates (const MemoryAccess *A, const Use &B) const
Given a MemoryAccess and a Use, determine whether MemoryAccess A dominates Use B.
void verifyMemorySSA (VerificationLevel=VerificationLevel::Fast) const
Verify that MemorySSA is self consistent (IE definitions dominate all uses, uses appear in the right places).
void ensureOptimizedUses ()
By default, uses are not optimized during MemorySSA construction.
AliasAnalysis & getAA ()
Protected Member Functions
void verifyOrderingDominationAndDefUses (Function &F, VerificationLevel=VerificationLevel::Fast) const
Verify ordering: the order and existence of MemoryAccesses matches the order and existence of memory affecting instructions.
void verifyDominationNumbers (const Function &F) const
Verify that all of the blocks we believe to have valid domination numbers actually have valid domination numbers.
void verifyPrevDefInPhis (Function &F) const
AccessList * getWritableBlockAccesses (const BasicBlock *BB) const
DefsList * getWritableBlockDefs (const BasicBlock *BB) const
void moveTo (MemoryUseOrDef *What, BasicBlock *BB, AccessList::iterator Where)
void moveTo (MemoryAccess *What, BasicBlock *BB, InsertionPlace Point)
void renamePass (BasicBlock *BB, MemoryAccess *IncomingVal, SmallPtrSetImpl< BasicBlock * > &Visited)
void removeFromLookups (MemoryAccess *)
Properly remove MA from all of MemorySSA's lookup tables.
void removeFromLists (MemoryAccess *, bool ShouldDelete=true)
Properly remove MA from all of MemorySSA's lists.
void insertIntoListsForBlock (MemoryAccess *, const BasicBlock *, InsertionPlace)
void insertIntoListsBefore (MemoryAccess *, const BasicBlock *, AccessList::iterator)
MemoryUseOrDef * createDefinedAccess (Instruction *, MemoryAccess *, const MemoryUseOrDef *Template=nullptr, bool CreationMustSucceed=true)
Friends
class MemorySSAPrinterLegacyPass
class MemorySSAUpdater
Detailed Description
Encapsulates MemorySSA, including all data associated with memory accesses.
Definition at line 700 of file MemorySSA.h.
Member Typedef Documentation
AccessList
using llvm::MemorySSA::AccessList = iplist<MemoryAccess, ilist_tag<MSSAHelpers::AllAccessTag> >
Definition at line 750 of file MemorySSA.h.
DefsList
using llvm::MemorySSA::DefsList = simple_ilist<MemoryAccess, ilist_tag<MSSAHelpers::DefsOnlyTag> >
Definition at line 752 of file MemorySSA.h.
Member Enumeration Documentation
InsertionPlace
enum llvm::MemorySSA::InsertionPlace
Used in various insertion functions to specify whether we are talking about the beginning or end of a block.
Enumerator
Beginning
End
BeforeTerminator
Definition at line 788 of file MemorySSA.h.
VerificationLevel
enum llvm::MemorySSA::VerificationLevel strong
Enumerator
Fast
Full
Definition at line 781 of file MemorySSA.h.
Constructor & Destructor Documentation
MemorySSA() [1/2]
MemorySSA::MemorySSA (Function & Func, AliasAnalysis * AA, DominatorTree * DT)
Definition at line 1236 of file MemorySSA.cpp.
References assert(), and getWalker().
MemorySSA() [2/2]
llvm::MemorySSA::MemorySSA (MemorySSA &&) delete
~MemorySSA()
MemorySSA::~MemorySSA ()
Definition at line 1254 of file MemorySSA.cpp.
References llvm::User::dropAllReferences().
Member Function Documentation
createDefinedAccess()
MemoryUseOrDef * MemorySSA::createDefinedAccess (Instruction * I, MemoryAccess * Definition, const MemoryUseOrDef * Template = nullptr, bool CreationMustSucceed = true) protected
Definition at line 1693 of file MemorySSA.cpp.
References assert(), I, llvm::MemoryUseOrDef::setDefiningAccess(), and Template.
Referenced by llvm::MemorySSAUpdater::createMemoryAccessAfter(), llvm::MemorySSAUpdater::createMemoryAccessBefore(), and llvm::MemorySSAUpdater::createMemoryAccessInBB().
dominates() [1/2]
bool MemorySSA::dominates (const MemoryAccess * A, const MemoryAccess * B) const
Given two memory accesses in potentially different blocks, determine whether MemoryAccess A dominates MemoryAccess B.
Definition at line 2116 of file MemorySSA.cpp.
References llvm::DominatorTree::dominates(), llvm::MemoryAccess::getBlock(), isLiveOnEntryDef(), and locallyDominates().
Referenced by llvm::canSinkOrHoistInst(), checkClobberSanity(), dominates(), and verifyOrderingDominationAndDefUses().
dominates() [2/2]
bool MemorySSA::dominates (const MemoryAccess * A, const Use & B) const
Given a MemoryAccess and a Use, determine whether MemoryAccess A dominates Use B.
Definition at line 2129 of file MemorySSA.cpp.
References llvm::DominatorTree::dominates(), dominates(), llvm::MemoryAccess::getBlock(), llvm::Use::getUser(), and locallyDominates().
dump()
LLVM_DUMP_METHOD void MemorySSA::dump () const
Definition at line 1860 of file MemorySSA.cpp.
References llvm::dbgs(), and print().
ensureOptimizedUses()
void MemorySSA::ensureOptimizedUses ()
By default, uses are not optimized during MemorySSA construction.
Calling this method will attempt to optimize all MemoryUses, if this has not happened yet for this MemorySSA instance. This should be done if you plan to query the clobbering access for most uses, or if you walk the def-use chain of uses.
Definition at line 2143 of file MemorySSA.cpp.
References llvm::MemorySSA::OptimizeUses::optimizeUses().
Referenced by llvm::GVNHoist::GVNHoist(), llvm::MemorySSAPrinterPass::run(), and llvm::MemorySSAPrinterLegacyPass::runOnFunction().
getAA()
AliasAnalysis& llvm::MemorySSA::getAA () inline
Definition at line 797 of file MemorySSA.h.
Referenced by llvm::MemorySSAWalker::getClobberingMemoryAccess().
getBlockAccesses()
const AccessList* llvm::MemorySSA::getBlockAccesses (const BasicBlock * BB) const inline
Return the list of MemoryAccess's for a given basic block.
This list is not modifiable by the user.
Definition at line 757 of file MemorySSA.h.
References BB.
Referenced by llvm::canSinkOrHoistInst(), foreachMemoryAccess(), llvm::MemorySSAUpdater::moveAllAfterSpliceBlocks(), llvm::SinkAndHoistLICMFlags::SinkAndHoistLICMFlags(), verifyDominationNumbers(), and verifyOrderingDominationAndDefUses().
getBlockDefs()
const DefsList* llvm::MemorySSA::getBlockDefs (const BasicBlock * BB) const inline
Return the list of MemoryDef's and MemoryPhi's for a given basic block.
This list is not modifiable by the user.
Definition at line 765 of file MemorySSA.h.
References BB.
Referenced by getNewDefiningAccessForClone(), llvm::MemorySSAUpdater::insertUse(), pointerInvalidatedByBlock(), unswitchAllTrivialConditions(), verifyOrderingDominationAndDefUses(), and verifyPrevDefInPhis().
getDomTree()
DominatorTree& llvm::MemorySSA::getDomTree () const inline
Definition at line 725 of file MemorySSA.h.
Referenced by checkClobberSanity(), and llvm::MemorySSA::ClobberWalkerBase::getClobberingMemoryAccessBase().
getLiveOnEntryDef()
MemoryAccess* llvm::MemorySSA::getLiveOnEntryDef () const inline
Definition at line 741 of file MemorySSA.h.
Referenced by llvm::MemorySSA::ClobberWalkerBase::getClobberingMemoryAccessBase(), llvm::MemorySSAUpdater::insertDef(), and llvm::MemorySSA::OptimizeUses::optimizeUses().
getMemoryAccess() [1/2]
MemoryPhi* llvm::MemorySSA::getMemoryAccess (const BasicBlock * BB) const inline
Definition at line 721 of file MemorySSA.h.
References BB.
getMemoryAccess() [2/2]
MemoryUseOrDef* llvm::MemorySSA::getMemoryAccess (const Instruction * I) const inline
Given a memory Mod/Ref'ing instruction, get the MemorySSA access associated with it.
If passed a basic block gets the memory phi node that exists for that block, if there is one. Otherwise, this will get a MemoryUseOrDef.
Definition at line 717 of file MemorySSA.h.
References I.
Referenced by buildPartialInvariantUnswitchConditionalBranch(), llvm::canSinkOrHoistInst(), llvm::MemorySSAUpdater::changeToUnreachable(), cloneInstructionInExitBlock(), llvm::MemorySSAWalker::getClobberingMemoryAccess(), llvm::MemorySSA::ClobberWalkerBase::getClobberingMemoryAccessBase(), getNewDefiningAccessForClone(), llvm::hasPartialIVCondition(), llvm::MemorySSAUpdater::insertDef(), llvm::Loop::makeLoopInvariant(), llvm::MergeBlockIntoPredecessor(), llvm::MemorySSAUpdater::moveAllAfterMergeBlocks(), llvm::MemorySSAUpdater::moveAllAfterSpliceBlocks(), moveInstructionBefore(), llvm::MemorySSAUpdater::moveToPlace(), llvm::MemorySSAUpdater::removeBlocks(), llvm::MemorySSAUpdater::removeDuplicatePhiEdgesBetween(), llvm::MemorySSAUpdater::removeEdge(), llvm::MemorySSAUpdater::removeMemoryAccess(), simplifyLoopInst(), sinkInstruction(), turnGuardIntoBranch(), llvm::MemorySSAUpdater::updateForClonedBlockIntoPred(), llvm::MemorySSAUpdater::updateForClonedLoop(), llvm::MemorySSAUpdater::updatePhisWhenInsertingUniqueBackedgeBlock(), verifyOrderingDominationAndDefUses(), verifyPrevDefInPhis(), and llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor().
getSkipSelfWalker()
MemorySSAWalker * MemorySSA::getSkipSelfWalker ()
Definition at line 1571 of file MemorySSA.cpp.
Referenced by llvm::canSinkOrHoistInst(), and pointerInvalidatedByLoop().
getWalker()
MemorySSAWalker * MemorySSA::getWalker ()
Definition at line 1558 of file MemorySSA.cpp.
Referenced by llvm::AMDGPU::isClobberedInFunction(), MemorySSA(), and removeFromLookups().
getWritableBlockAccesses()
AccessList* llvm::MemorySSA::getWritableBlockAccesses (const BasicBlock * BB) const inline protected
Definition at line 810 of file MemorySSA.h.
References BB.
Referenced by insertIntoListsBefore(), llvm::MemorySSAUpdater::removeBlocks(), llvm::MemorySSAUpdater::updateForClonedLoop(), and llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor().
getWritableBlockDefs()
DefsList* llvm::MemorySSA::getWritableBlockDefs (const BasicBlock * BB) const inline protected
Definition at line 816 of file MemorySSA.h.
References BB, and llvm::simple_ilist< T, Options >::end().
Referenced by llvm::MemorySSAUpdater::insertDef(), and llvm::MemorySSAUpdater::insertUse().
insertIntoListsBefore()
void MemorySSA::insertIntoListsBefore (MemoryAccess * What, const BasicBlock * BB, AccessList::iterator InsertPt) protected
Definition at line 1618 of file MemorySSA.cpp.
References BB, and getWritableBlockAccesses().
Referenced by llvm::MemorySSAUpdater::createMemoryAccessAfter(), llvm::MemorySSAUpdater::createMemoryAccessBefore(), and moveTo().
insertIntoListsForBlock()
void MemorySSA::insertIntoListsForBlock (MemoryAccess * NewAccess, const BasicBlock * BB, InsertionPlace Point) protected
Definition at line 1586 of file MemorySSA.cpp.
References BB, Beginning, and llvm::find_if_not().
Referenced by llvm::MemorySSAUpdater::createMemoryAccessInBB(), and moveTo().
isLiveOnEntryDef()
bool llvm::MemorySSA::isLiveOnEntryDef (const MemoryAccess * MA) const inline
Return true if MA represents the live on entry value.
Loads and stores from pointer arguments and other global values may be defined by memory operations that do not occur in the current function, so they may be live on entry to the function. MemorySSA represents such memory state by the live on entry definition, which is guaranteed to occur before any other memory access in the function.
Definition at line 737 of file MemorySSA.h.
Referenced by llvm::canSinkOrHoistInst(), checkClobberSanity(), dominates(), llvm::MemorySSA::ClobberWalkerBase::getClobberingMemoryAccessBase(), getNewDefiningAccessForClone(), hasUndefContents(), llvm::AMDGPU::isClobberedInFunction(), locallyDominates(), pointerInvalidatedByLoop(), llvm::MemorySSAUpdater::removeMemoryAccess(), and llvm::MemorySSAUpdater::updateForClonedLoop().
locallyDominates()
bool MemorySSA::locallyDominates (const MemoryAccess * Dominator, const MemoryAccess * Dominatee) const
Given two memory accesses in the same basic block, determine whether MemoryAccess A dominates MemoryAccess B.
Determine, for two memory accesses in the same block, whether Dominator dominates Dominatee.
Returns
True if Dominator dominates Dominatee.
Definition at line 2085 of file MemorySSA.cpp.
References assert(), llvm::MemoryAccess::getBlock(), and isLiveOnEntryDef().
Referenced by dominates(), and pointerInvalidatedByBlock().
moveTo() [1/2]
void MemorySSA::moveTo (MemoryAccess * What, BasicBlock * BB, InsertionPlace Point) protected
Definition at line 1668 of file MemorySSA.cpp.
References assert(), BB, Beginning, llvm::MemoryAccess::getBlock(), and insertIntoListsForBlock().
moveTo() [2/2]
void MemorySSA::moveTo (MemoryUseOrDef * What, BasicBlock * BB, AccessList::iterator Where) protected
Definition at line 1662 of file MemorySSA.cpp.
References BB, and insertIntoListsBefore().
Referenced by llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor().
print()
void MemorySSA::print (raw_ostream & OS) const
Definition at line 1854 of file MemorySSA.cpp.
References F, and OS.
Referenced by llvm::MemoryAccess::dump(), dump(), llvm::MemoryAccess::print(), llvm::MemorySSAWrapperPass::print(), llvm::MemorySSAPrinterPass::run(), and llvm::MemorySSAPrinterLegacyPass::runOnFunction().
removeFromLists()
void MemorySSA::removeFromLists (MemoryAccess * MA, bool ShouldDelete = true) protected
Properly remove MA from all of MemorySSA's lists.
Because of the way the intrusive list and use lists work, it is important to do removal in the right order. ShouldDelete defaults to true, and will cause the memory access to also be deleted, not just removed.
Definition at line 1827 of file MemorySSA.cpp.
References BB, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::MemoryAccess::getBlock().
Referenced by llvm::MemorySSAUpdater::removeBlocks(), and llvm::MemorySSAUpdater::removeMemoryAccess().
removeFromLookups()
void MemorySSA::removeFromLookups (MemoryAccess * MA) protected
Properly remove MA from all of MemorySSA's lookup tables.
Definition at line 1800 of file MemorySSA.cpp.
References assert(), llvm::MemoryAccess::getBlock(), llvm::MemoryUseOrDef::getMemoryInst(), getWalker(), llvm::MemorySSAWalker::invalidateInfo(), llvm::MemoryUseOrDef::setDefiningAccess(), and llvm::Value::use_empty().
Referenced by llvm::MemorySSAUpdater::removeBlocks(), and llvm::MemorySSAUpdater::removeMemoryAccess().
renamePass()
void llvm::MemorySSA::renamePass (BasicBlock * BB, MemoryAccess * IncomingVal, SmallPtrSetImpl< BasicBlock * > & Visited) inline protected
Definition at line 829 of file MemorySSA.h.
References BB.
Referenced by llvm::MemorySSAUpdater::insertDef(), and llvm::MemorySSAUpdater::insertUse().
verifyDominationNumbers()
void MemorySSA::verifyDominationNumbers (const Function & F) const protected
Verify that all of the blocks we believe to have valid domination numbers actually have valid domination numbers.
Definition at line 1922 of file MemorySSA.cpp.
References assert(), BB, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallPtrSetImplBase::empty(), llvm::SmallPtrSetImpl< PtrType >::erase(), F, and getBlockAccesses().
Referenced by verifyMemorySSA().
verifyMemorySSA()
void MemorySSA::verifyMemorySSA (VerificationLevel VL = VerificationLevel::Fast) const
Verify that MemorySSA is self consistent (IE definitions dominate all uses, uses appear in the right places).
This is used by unit tests.
Definition at line 1863 of file MemorySSA.cpp.
References F, Full, verifyDominationNumbers(), verifyOrderingDominationAndDefUses(), and verifyPrevDefInPhis().
Referenced by llvm::deleteDeadLoop(), llvm::hoistRegion(), injectPendingInvariantConditions(), mergeBlocksIntoPredecessors(), llvm::LoopFlattenPass::run(), llvm::LoopInstSimplifyPass::run(), llvm::LoopRotatePass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::FunctionToLoopPassAdaptor::run(), llvm::MemCpyOptPass::runImpl(), llvm::MemorySSAPrinterLegacyPass::runOnFunction(), simplifyLoopInst(), simplifyOneLoop(), llvm::sinkRegion(), llvm::splitBlockBefore(), turnGuardIntoBranch(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), and llvm::MemorySSAWrapperPass::verifyAnalysis().
verifyOrderingDominationAndDefUses()
void MemorySSA::verifyOrderingDominationAndDefUses (Function & F, VerificationLevel VL = VerificationLevel::Fast) const protected
Verify ordering: the order and existence of MemoryAccesses matches the order and existence of memory affecting instructions.
Verify domination: each definition dominates all of its uses. Verify def-uses: the immediate use information - walk all the memory accesses and verifying that, for each use, it appears in the appropriate def's use list
Definition at line 1963 of file MemorySSA.cpp.
References llvm::AArch64CC::AL, assert(), B, llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), DL, dominates(), E, llvm::MachineBasicBlock::end(), F, Full, getBlockAccesses(), getBlockDefs(), llvm::MemoryUseOrDef::getDefiningAccess(), llvm::MemoryPhi::getIncomingBlock(), llvm::MemoryPhi::getIncomingValue(), getMemoryAccess(), llvm::MemoryPhi::getNumIncomingValues(), llvm::User::getNumOperands(), I, llvm::is_contained(), llvm::pred_begin(), llvm::pred_end(), llvm::predecessors(), llvm::MachineBasicBlock::size(), and llvm::Value::uses().
Referenced by verifyMemorySSA().
verifyPrevDefInPhis()
void MemorySSA::verifyPrevDefInPhis (Function & F) const protected
Definition at line 1886 of file MemorySSA.cpp.
References assert(), BB, E, F, getBlockDefs(), llvm::MemoryPhi::getIncomingBlock(), llvm::MemoryPhi::getIncomingValue(), getMemoryAccess(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::MemoryPhi::getNumIncomingValues(), and I.
Referenced by verifyMemorySSA().
Friends And Related Function Documentation
MemorySSAPrinterLegacyPass
friend class MemorySSAPrinterLegacyPass friend
Definition at line 801 of file MemorySSA.h.
MemorySSAUpdater
friend class MemorySSAUpdater friend
Definition at line 802 of file MemorySSA.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemorySSA.h
lib/Analysis/MemorySSA.cpp