LLVM: llvm::object::WindowsResourceParser Class Reference
llvm::object::WindowsResourceParser Class Reference
#include "llvm/Object/WindowsResource.h"
Classes
struct StringOrID
class TreeNode
Public Member Functions
WindowsResourceParser (bool MinGW=false)
Error parse (WindowsResource *WR, std::vector< std::string > &Duplicates)
Error parse (ResourceSectionRef &RSR, StringRef Filename, std::vector< std::string > &Duplicates)
void cleanUpManifests (std::vector< std::string > &Duplicates)
void printTree (raw_ostream &OS) const
const TreeNode & getTree () const
ArrayRef< std::vector< uint8_t > > getData () const
ArrayRef< std::vector< UTF16 > > getStringTable () const
Detailed Description
Definition at line 153 of file WindowsResource.h.
Constructor & Destructor Documentation
WindowsResourceParser()
llvm::object::WindowsResourceParser::WindowsResourceParser (bool MinGW = false)
Definition at line 138 of file WindowsResource.cpp.
Member Function Documentation
cleanUpManifests()
void llvm::object::WindowsResourceParser::cleanUpManifests (std::vector< std::string > & Duplicates)
Definition at line 261 of file WindowsResource.cpp.
getData()
ArrayRef<std::vector<uint8_t> > llvm::object::WindowsResourceParser::getData () const inline
Definition at line 163 of file WindowsResource.h.
References llvm::Data.
getStringTable()
ArrayRef<std::vector<UTF16> > llvm::object::WindowsResourceParser::getStringTable () const inline
Definition at line 164 of file WindowsResource.h.
getTree()
const TreeNode& llvm::object::WindowsResourceParser::getTree () const inline
Definition at line 162 of file WindowsResource.h.
parse() [1/2]
Error llvm::object::WindowsResourceParser::parse (ResourceSectionRef & RSR, StringRef Filename, std::vector< std::string > & Duplicates)
Definition at line 365 of file WindowsResource.cpp.
References Context, llvm::object::ResourceSectionRef::getBaseTable(), and UNWRAP_REF_OR_RETURN.
parse() [2/2]
Error llvm::object::WindowsResourceParser::parse (WindowsResource * WR, std::vector< std::string > & Duplicates)
Definition at line 327 of file WindowsResource.cpp.
References llvm::consumeError(), E, llvm::object::WindowsResource::getHeadEntry(), move, and llvm::Error::success().
printTree()
void llvm::object::WindowsResourceParser::printTree (raw_ostream & OS) const
Definition at line 374 of file WindowsResource.cpp.
References OS, and llvm::object::WindowsResourceParser::TreeNode::print().
The documentation for this class was generated from the following files:
include/llvm/Object/WindowsResource.h
lib/Object/WindowsResource.cpp