LLVM: llvm::TargetRegistry::iterator Class Reference
llvm::TargetRegistry::iterator Class Reference
#include "llvm/MC/TargetRegistry.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = Target
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
iterator ()=default
bool operator== (const iterator &x) const
bool operator!= (const iterator &x) const
iterator & operator++ ()
iterator operator++ (int)
const Target & operator* () const
const Target * operator-> () const
Friends
struct TargetRegistry
Detailed Description
Definition at line 741 of file TargetRegistry.h.
Member Typedef Documentation
difference_type
using llvm::TargetRegistry::iterator::difference_type = std::ptrdiff_t
Definition at line 751 of file TargetRegistry.h.
iterator_category
using llvm::TargetRegistry::iterator::iterator_category = std::forward_iterator_tag
Definition at line 749 of file TargetRegistry.h.
pointer
using llvm::TargetRegistry::iterator::pointer = value_type *
Definition at line 752 of file TargetRegistry.h.
reference
using llvm::TargetRegistry::iterator::reference = value_type &
Definition at line 753 of file TargetRegistry.h.
value_type
using llvm::TargetRegistry::iterator::value_type = Target
Definition at line 750 of file TargetRegistry.h.
Constructor & Destructor Documentation
iterator()
llvm::TargetRegistry::iterator::iterator () default
Member Function Documentation
operator!=()
bool llvm::TargetRegistry::iterator::operator!= (const iterator & x) const inline
Definition at line 758 of file TargetRegistry.h.
References operator==(), and x.
operator*()
const Target& llvm::TargetRegistry::iterator::operator* () const inline
Definition at line 772 of file TargetRegistry.h.
References assert().
Referenced by operator->().
operator++() [1/2]
iterator& llvm::TargetRegistry::iterator::operator++ () inline
Definition at line 761 of file TargetRegistry.h.
References assert(), and llvm::Target::getNext().
operator++() [2/2]
iterator llvm::TargetRegistry::iterator::operator++ (int) inline
Definition at line 766 of file TargetRegistry.h.
operator->()
const Target* llvm::TargetRegistry::iterator::operator-> () const inline
Definition at line 777 of file TargetRegistry.h.
References operator*().
operator==()
bool llvm::TargetRegistry::iterator::operator== (const iterator & x) const inline
Definition at line 757 of file TargetRegistry.h.
References x.
Referenced by operator!=().
Friends And Related Function Documentation
TargetRegistry
friend struct TargetRegistry friend
Definition at line 742 of file TargetRegistry.h.
The documentation for this class was generated from the following file:
include/llvm/MC/TargetRegistry.h