LLVM: llvm::gsym::ObjectFileTransformer Class Reference
llvm::gsym::ObjectFileTransformer Class Reference
#include "llvm/DebugInfo/GSYM/ObjectFileTransformer.h"
Static Public Member Functions
static llvm::Error convert (const object::ObjectFile &Obj, raw_ostream &Log, GsymCreator &Gsym)
Extract any object file data that is needed by the GsymCreator.
Detailed Description
Definition at line 26 of file ObjectFileTransformer.h.
Member Function Documentation
convert()
llvm::Error ObjectFileTransformer::convert (const object::ObjectFile & Obj, raw_ostream & Log, GsymCreator & Gsym) static
Extract any object file data that is needed by the GsymCreator.
The extracted information includes the UUID of the binary and converting all function symbols from any symbol tables into FunctionInfo objects.
Parameters
Obj The object file that contains the DWARF debug info.
Log The stream to log warnings and non fatal issues to.
Gsym The GSYM creator to populate with the function information from the debug info.
Returns
An error indicating any fatal issues that happen when parsing the DWARF, or Error::success() if all goes well.
Definition at line 70 of file ObjectFileTransformer.cpp.
References llvm::gsym::GsymCreator::addFunctionInfo(), llvm::consumeError(), llvm::Expected< T >::get(), llvm::gsym::GsymCreator::getNumFunctionInfos(), llvm::object::ELFSymbolRef::getSize(), getUUID(), llvm::gsym::GsymCreator::hasFunctionInfoForAddress(), llvm::gsym::GsymCreator::insertString(), llvm::gsym::GsymCreator::IsValidTextAddress(), llvm::logAllUnhandledErrors(), llvm::gsym::GsymCreator::setUUID(), llvm::size(), llvm::Error::success(), llvm::object::ObjectFile::symbols(), llvm::Expected< T >::takeError(), and uint64_t.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/GSYM/ObjectFileTransformer.h
lib/DebugInfo/GSYM/ObjectFileTransformer.cpp