LLVM: llvm::orc::Platform Class Reference
llvm::orc::Platform Class Reference abstract
Platforms set up standard symbols and mediate interactions between dynamic initializers (e.g.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
virtual ~Platform ()
virtual Error setupJITDylib (JITDylib &JD)=0
This method will be called outside the session lock each time a JITDylib is created (unless it is created with EmptyJITDylib set) to allow the Platform to install any JITDylib specific standard symbols (e.g __dso_handle).
virtual Error teardownJITDylib (JITDylib &JD)=0
This method will be called outside the session lock each time a JITDylib is removed to allow the Platform to remove any JITDylib-specific data.
virtual Error notifyAdding (ResourceTracker &RT, const MaterializationUnit &MU)=0
This method will be called under the ExecutionSession lock each time a MaterializationUnit is added to a JITDylib.
virtual Error notifyRemoving (ResourceTracker &RT)=0
This method will be called under the ExecutionSession lock when a ResourceTracker is removed.
Static Public Member Functions
static Expected< DenseMap< JITDylib *, SymbolMap > > lookupInitSymbols (ExecutionSession &ES, const DenseMap< JITDylib *, SymbolLookupSet > &InitSyms)
A utility function for looking up initializer symbols.
static void lookupInitSymbolsAsync (unique_function< void(Error)> OnComplete, ExecutionSession &ES, const DenseMap< JITDylib *, SymbolLookupSet > &InitSyms)
Performs an async lookup for the given symbols in each of the given JITDylibs, calling the given handler once all lookups have completed.
Detailed Description
Platforms set up standard symbols and mediate interactions between dynamic initializers (e.g.
C++ static constructors) and ExecutionSession state. Note that Platforms do not automatically run initializers: clients are still responsible for doing this.
Definition at line 1317 of file Core.h.
Constructor & Destructor Documentation
~Platform()
llvm::orc::Platform::~Platform () virtual default
Member Function Documentation
lookupInitSymbols()
Expected< DenseMap< JITDylib *, SymbolMap > > llvm::orc::Platform::lookupInitSymbols (ExecutionSession & ES, const DenseMap< JITDylib *, SymbolLookupSet > & InitSyms) static
A utility function for looking up initializer symbols.
Performs a blocking lookup for the given symbols in each of the given JITDylibs.
Note: This function is deprecated and will be removed in the near future.
Definition at line 1785 of file Core.cpp.
References assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::count(), llvm::dbgs(), llvm::joinErrors(), LLVM_DEBUG, llvm::orc::ExecutionSession::lookup(), llvm::orc::MatchAllSymbols, move, llvm::orc::NoDependenciesToRegister, llvm::orc::Ready, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::size(), llvm::orc::Static, llvm::Error::success(), and uint64_t.
lookupInitSymbolsAsync()
void llvm::orc::Platform::lookupInitSymbolsAsync (unique_function< void(Error)> OnComplete, ExecutionSession & ES, const DenseMap< JITDylib *, SymbolLookupSet > & InitSyms) static
Performs an async lookup for the given symbols in each of the given JITDylibs, calling the given handler once all lookups have completed.
Definition at line 1834 of file Core.cpp.
References move.
notifyAdding()
virtual Error llvm::orc::Platform::notifyAdding (ResourceTracker & RT, const MaterializationUnit & MU) pure virtual
This method will be called under the ExecutionSession lock each time a MaterializationUnit is added to a JITDylib.
Implemented in llvm::orc::ELFNixPlatform, llvm::orc::MachOPlatform, and llvm::orc::COFFPlatform.
notifyRemoving()
virtual Error llvm::orc::Platform::notifyRemoving (ResourceTracker & RT) pure virtual
This method will be called under the ExecutionSession lock when a ResourceTracker is removed.
Implemented in llvm::orc::ELFNixPlatform, llvm::orc::MachOPlatform, and llvm::orc::COFFPlatform.
setupJITDylib()
virtual Error llvm::orc::Platform::setupJITDylib (JITDylib & JD) pure virtual
This method will be called outside the session lock each time a JITDylib is created (unless it is created with EmptyJITDylib set) to allow the Platform to install any JITDylib specific standard symbols (e.g __dso_handle).
Implemented in llvm::orc::ELFNixPlatform, llvm::orc::MachOPlatform, and llvm::orc::COFFPlatform.
teardownJITDylib()
virtual Error llvm::orc::Platform::teardownJITDylib (JITDylib & JD) pure virtual
This method will be called outside the session lock each time a JITDylib is removed to allow the Platform to remove any JITDylib-specific data.
Implemented in llvm::orc::ELFNixPlatform, llvm::orc::MachOPlatform, and llvm::orc::COFFPlatform.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp