LLVM: llvm::jitlink::TableManager< TableManagerImplT > Class Template Reference
llvm::jitlink::TableManager< TableManagerImplT > Class Template Reference
A CRTP base for tables that are built on demand, e.g.
#include "llvm/ExecutionEngine/JITLink/TableManager.h"
Public Member Functions
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
Detailed Description
template<typename TableManagerImplT>
class llvm::jitlink::TableManager< TableManagerImplT >
A CRTP base for tables that are built on demand, e.g.
Global Offset Tables and Procedure Linkage Tables. The getEntyrForTarget function returns the table entry corresponding to the given target, calling down to the implementation class to build an entry if one does not already exist.
Definition at line 27 of file TableManager.h.
Member Function Documentation
getEntryForTarget()
template<typename TableManagerImplT > Symbol& llvm::jitlink::TableManager< TableManagerImplT >::getEntryForTarget (LinkGraph & G, Symbol & Target) inline
Return the constructed entry.
Use parameter G to construct the entry for target symbol
Definition at line 32 of file TableManager.h.
Referenced by llvm::jitlink::loongarch::PLTTableManager::createEntry(), llvm::jitlink::aarch64::PLTTableManager::createEntry(), and llvm::jitlink::x86_64::PLTTableManager::createEntry().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/TableManager.h