LLVM: llvm::DIEBlock Class Reference
llvm::DIEBlock Class Reference
DIEBlock - Represents a block of values.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEBlock ()=default
unsigned computeSize (const dwarf::FormParams &FormParams) const
Calculate the size of the location expression.
void setSize (unsigned size)
dwarf::Form BestForm () const
BestForm - Choose the best form for data.
void emitValue (const AsmPrinter *Asm, dwarf::Form Form) const
EmitValue - Emit block data.
unsigned sizeOf (const dwarf::FormParams &, dwarf::Form Form) const
sizeOf - Determine size of block data in bytes.
void print (raw_ostream &O) const
Public Member Functions inherited from llvm::DIEValueList
value_iterator addValue (BumpPtrAllocator &Alloc, const DIEValue &V)
template<class T >
value_iterator addValue (BumpPtrAllocator &Alloc, dwarf::Attribute Attribute, dwarf::Form Form, T &&Value)
void takeValues (DIEValueList &Other)
Take ownership of the nodes in Other, and append them to the back of the list.
value_range values ()
const_value_range values () const
Additional Inherited Members
Public Types inherited from llvm::DIEValueList
using value_range = iterator_range< value_iterator >
using const_value_range = iterator_range< const_value_iterator >
Detailed Description
DIEBlock - Represents a block of values.
Definition at line 966 of file DIE.h.
Constructor & Destructor Documentation
DIEBlock()
llvm::DIEBlock::DIEBlock () default
Member Function Documentation
BestForm()
dwarf::Form llvm::DIEBlock::BestForm () const inline
BestForm - Choose the best form for data.
Definition at line 980 of file DIE.h.
computeSize()
unsigned DIEBlock::computeSize (const dwarf::FormParams & FormParams) const
Calculate the size of the location expression.
Definition at line 762 of file DIE.cpp.
References llvm::DIEValueList::values().
emitValue()
void DIEBlock::emitValue (const AsmPrinter * Asm, dwarf::Form Form) const
EmitValue - Emit block data.
Definition at line 773 of file DIE.cpp.
References llvm::HexStyle::Asm, llvm_unreachable, and llvm::DIEValueList::values().
print()
LLVM_DUMP_METHOD void DIEBlock::print (raw_ostream & O) const
Definition at line 806 of file DIE.cpp.
References llvm::RISCVFenceField::O, and printValues().
setSize()
void llvm::DIEBlock::setSize (unsigned size) inline
Definition at line 976 of file DIE.h.
References llvm::size().
sizeOf()
unsigned DIEBlock::sizeOf (const dwarf::FormParams & , dwarf::Form Form) const
sizeOf - Determine size of block data in bytes.
Definition at line 793 of file DIE.cpp.
References llvm::getULEB128Size(), and llvm_unreachable.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp