LLVM: llvm::objcopy::elf::SectionTableRef Class Reference
llvm::objcopy::elf::SectionTableRef Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Types
using iterator = pointee_iterator< const std::unique_ptr< SectionBase > * >
Public Member Functions
SectionTableRef (ArrayRef< std::unique_ptr< SectionBase >> Secs)
SectionTableRef (const SectionTableRef &)=default
iterator begin () const
iterator end () const
size_t size () const
Expected< SectionBase * > getSection (uint32_t Index, Twine ErrMsg)
template<class T >
Expected< T * > getSectionOfType (uint32_t Index, Twine IndexErrMsg, Twine TypeErrMsg)
Detailed Description
Definition at line 50 of file ELFObject.h.
Member Typedef Documentation
iterator
using llvm::objcopy::elf::SectionTableRef::iterator = pointee_iterator<const std::unique_ptr<SectionBase> *>
Definition at line 54 of file ELFObject.h.
Constructor & Destructor Documentation
SectionTableRef() [1/2]
llvm::objcopy::elf::SectionTableRef::SectionTableRef (ArrayRef< std::unique_ptr< SectionBase >> Secs) inline explicit
Definition at line 56 of file ELFObject.h.
SectionTableRef() [2/2]
llvm::objcopy::elf::SectionTableRef::SectionTableRef (const SectionTableRef &) default
Member Function Documentation
begin()
iterator llvm::objcopy::elf::SectionTableRef::begin () const inline
Definition at line 60 of file ELFObject.h.
References llvm::ArrayRef< T >::data().
end()
iterator llvm::objcopy::elf::SectionTableRef::end () const inline
Definition at line 61 of file ELFObject.h.
References llvm::ArrayRef< T >::data(), and llvm::ArrayRef< T >::size().
getSection()
Expected< SectionBase * > SectionTableRef::getSection (uint32_t Index, Twine ErrMsg)
Definition at line 1639 of file ELFObject.cpp.
References llvm::createStringError(), llvm::invalid_argument, and llvm::ELF::SHN_UNDEF.
Referenced by getSectionOfType(), llvm::objcopy::elf::Section::initialize(), and llvm::objcopy::elf::RelocSectionWithSymtabBase< DynamicSymbolTableSection >::initialize().
getSectionOfType()
template<class T > Expected< T * > SectionTableRef::getSectionOfType (uint32_t Index, Twine IndexErrMsg, Twine TypeErrMsg)
Definition at line 1647 of file ELFObject.cpp.
References llvm::createStringError(), getSection(), llvm::invalid_argument, and llvm::Expected< T >::takeError().
Referenced by llvm::objcopy::elf::SectionIndexSection::initialize(), llvm::objcopy::elf::SymbolTableSection::initialize(), and llvm::objcopy::elf::RelocSectionWithSymtabBase< DynamicSymbolTableSection >::initialize().
size()
size_t llvm::objcopy::elf::SectionTableRef::size () const inline
Definition at line 62 of file ELFObject.h.
References llvm::ArrayRef< T >::size().
Referenced by layoutSectionsForOnlyKeepDebug().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp