LLVM: llvm::MCDwarfDwoLineTable Class Reference
llvm::MCDwarfDwoLineTable Class Reference
#include "llvm/MC/MCDwarf.h"
Public Member Functions
void maybeSetRootFile (StringRef Directory, StringRef FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source)
unsigned getFile (StringRef Directory, StringRef FileName, std::optional< MD5::MD5Result > Checksum, uint16_t DwarfVersion, std::optional< StringRef > Source)
void Emit (MCStreamer &MCOS, MCDwarfLineTableParams Params, MCSection *Section) const
Detailed Description
Definition at line 321 of file MCDwarf.h.
Member Function Documentation
Emit()
void MCDwarfDwoLineTable::Emit (MCStreamer & MCOS, MCDwarfLineTableParams Params, MCSection * Section) const
Definition at line 283 of file MCDwarf.cpp.
References llvm::MCDwarfLineTableHeader::Emit(), llvm::MCStreamer::emitLabel(), and llvm::MCStreamer::switchSection().
getFile()
unsigned llvm::MCDwarfDwoLineTable::getFile (StringRef Directory, StringRef FileName, std::optional< MD5::MD5Result > Checksum, uint16_t DwarfVersion, std::optional< StringRef > Source) inline
Definition at line 334 of file MCDwarf.h.
References llvm::cantFail(), and llvm::Sched::Source.
maybeSetRootFile()
void llvm::MCDwarfDwoLineTable::maybeSetRootFile (StringRef Directory, StringRef FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source) inline
Definition at line 326 of file MCDwarf.h.
References llvm::Sched::Source.
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp