LLVM: llvm::orc::SymbolStringPool Class Reference
llvm::orc::SymbolStringPool Class Reference
String pool for symbol names used by the JIT.
#include "llvm/ExecutionEngine/Orc/SymbolStringPool.h"
Public Member Functions
~SymbolStringPool ()
Destroy a SymbolStringPool.
SymbolStringPtr intern (StringRef S)
Create a symbol string pointer from the given string.
void clearDeadEntries ()
Remove from the pool any entries that are no longer referenced.
bool empty () const
Returns true if the pool is empty.
Friends
class SymbolStringPoolTest
class SymbolStringPtrBase
raw_ostream & operator<< (raw_ostream &OS, const SymbolStringPool &SSP)
Dump a SymbolStringPool. Useful for debugging dangling-pointer crashes.
Detailed Description
String pool for symbol names used by the JIT.
Definition at line 32 of file SymbolStringPool.h.
Constructor & Destructor Documentation
~SymbolStringPool()
llvm::orc::SymbolStringPool::~SymbolStringPool () inline
Destroy a SymbolStringPool.
Definition at line 237 of file SymbolStringPool.h.
References assert(), clearDeadEntries(), and llvm::StringMapImpl::empty().
Member Function Documentation
clearDeadEntries()
void llvm::orc::SymbolStringPool::clearDeadEntries () inline
Remove from the pool any entries that are no longer referenced.
Definition at line 252 of file SymbolStringPool.h.
References llvm::StringMap< ValueTy, AllocatorTy >::begin(), E, llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::erase(), and I.
Referenced by ~SymbolStringPool().
empty()
bool llvm::orc::SymbolStringPool::empty () const inline
Returns true if the pool is empty.
Definition at line 261 of file SymbolStringPool.h.
References llvm::StringMapImpl::empty().
intern()
SymbolStringPtr llvm::orc::SymbolStringPool::intern (StringRef S) inline
Create a symbol string pointer from the given string.
Definition at line 244 of file SymbolStringPool.h.
References I, S, and llvm::StringMap< ValueTy, AllocatorTy >::try_emplace().
Friends And Related Function Documentation
operator<<
raw_ostream& operator<< (raw_ostream & OS, const SymbolStringPool & SSP) friend
Dump a SymbolStringPool. Useful for debugging dangling-pointer crashes.
Definition at line 300 of file DebugUtils.cpp.
SymbolStringPoolTest
friend class SymbolStringPoolTest friend
Definition at line 33 of file SymbolStringPool.h.
SymbolStringPtrBase
friend class SymbolStringPtrBase friend
Definition at line 34 of file SymbolStringPool.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/SymbolStringPool.h