LLVM: llvm::logicalview::LVSymbolTable Class Reference
llvm::logicalview::LVSymbolTable Class Reference final
#include "llvm/DebugInfo/LogicalView/Readers/LVBinaryReader.h"
Public Member Functions
LVSymbolTable ()=default
void add (StringRef Name, LVScope *Function, LVSectionIndex SectionIndex=0)
void add (StringRef Name, LVAddress Address, LVSectionIndex SectionIndex, bool IsComdat)
LVSectionIndex update (LVScope *Function)
const LVSymbolTableEntry & getEntry (StringRef Name)
LVAddress getAddress (StringRef Name)
LVSectionIndex getIndex (StringRef Name)
bool getIsComdat (StringRef Name)
void print (raw_ostream &OS)
Detailed Description
Definition at line 48 of file LVBinaryReader.h.
Constructor & Destructor Documentation
LVSymbolTable()
llvm::logicalview::LVSymbolTable::LVSymbolTable () default
Member Function Documentation
add() [1/2]
void LVSymbolTable::add (StringRef Name, LVAddress Address, LVSectionIndex SectionIndex, bool IsComdat)
Definition at line 44 of file LVBinaryReader.cpp.
References llvm::dbgs(), LLVM_DEBUG, print(), and llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
add() [2/2]
void LVSymbolTable::add (StringRef Name, LVScope * Function, LVSectionIndex SectionIndex = 0)
Definition at line 24 of file LVBinaryReader.cpp.
References llvm::dbgs(), LLVM_DEBUG, print(), and llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
Referenced by llvm::logicalview::LVBinaryReader::addToSymbolTable().
getAddress()
LVAddress LVSymbolTable::getAddress (StringRef Name)
Definition at line 93 of file LVBinaryReader.cpp.
Referenced by llvm::logicalview::LVBinaryReader::getSymbolTableAddress().
getEntry()
const LVSymbolTableEntry & LVSymbolTable::getEntry (StringRef Name)
Definition at line 88 of file LVBinaryReader.cpp.
Referenced by llvm::logicalview::LVBinaryReader::getSymbolTableEntry().
getIndex()
LVSectionIndex LVSymbolTable::getIndex (StringRef Name)
Definition at line 97 of file LVBinaryReader.cpp.
References llvm::logicalview::LVReader::getDotTextSectionIndex(), and llvm::logicalview::getReader().
Referenced by llvm::logicalview::LVBinaryReader::getSymbolTableIndex().
getIsComdat()
bool LVSymbolTable::getIsComdat (StringRef Name)
Definition at line 102 of file LVBinaryReader.cpp.
Referenced by llvm::logicalview::LVBinaryReader::getSymbolTableIsComdat().
print()
void LVSymbolTable::print (raw_ostream & OS)
Definition at line 107 of file LVBinaryReader.cpp.
References OS.
Referenced by add(), and update().
update()
LVSectionIndex LVSymbolTable::update (LVScope * Function)
Definition at line 61 of file LVBinaryReader.cpp.
References llvm::dbgs(), llvm::logicalview::LVReader::getDotTextSectionIndex(), llvm::Value::getName(), llvm::logicalview::getReader(), LLVM_DEBUG, print(), llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName, and llvm::logicalview::UndefinedSectionIndex.
Referenced by llvm::logicalview::LVBinaryReader::updateSymbolTable().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Readers/LVBinaryReader.h
lib/DebugInfo/LogicalView/Readers/LVBinaryReader.cpp