LLVM: llvm::TGParser Class Reference
llvm::TGParser Class Reference
#include "TableGen/TGParser.h"
Public Member Functions
TGParser (SourceMgr &SM, ArrayRef< std::string > Macros, RecordKeeper &records, const bool NoWarnOnUnusedTemplateArgs=false, const bool TrackReferenceLocs=false)
bool ParseFile ()
ParseFile - Main entrypoint for parsing a tblgen file.
bool Error (SMLoc L, const Twine &Msg) const
bool TokError (const Twine &Msg) const
const TGLexer::DependenciesSetTy & getDependencies () const
TGLocalVarScope * PushLocalScope ()
void PopLocalScope (TGLocalVarScope *ExpectedStackTop)
Detailed Description
Definition at line 130 of file TGParser.h.
Constructor & Destructor Documentation
TGParser()
llvm::TGParser::TGParser (SourceMgr & SM, ArrayRef< std::string > Macros, RecordKeeper & records, const bool NoWarnOnUnusedTemplateArgs = false, const bool TrackReferenceLocs = false) inline
Definition at line 167 of file TGParser.h.
Member Function Documentation
Error()
bool llvm::TGParser::Error (SMLoc L, const Twine & Msg) const inline
Definition at line 178 of file TGParser.h.
References llvm::AMDGPU::SendMsg::Msg, and llvm::PrintError().
Referenced by TokError().
getDependencies()
const TGLexer::DependenciesSetTy& llvm::TGParser::getDependencies () const inline
Definition at line 185 of file TGParser.h.
References llvm::TGLexer::getDependencies().
Referenced by createDependencyFile().
ParseFile()
bool TGParser::ParseFile ()
ParseFile - Main entrypoint for parsing a tblgen file.
These parser routines return true on error, or false on success.
Definition at line 3859 of file TGParser.cpp.
References llvm::tgtok::Eof, llvm::TGLexer::getCode(), llvm::TGLexer::Lex(), and TokError().
Referenced by llvm::TableGenMain(), and llvm::TableGenParseFile().
PopLocalScope()
void llvm::TGParser::PopLocalScope (TGLocalVarScope * ExpectedStackTop) inline
Definition at line 196 of file TGParser.h.
References assert().
PushLocalScope()
TGLocalVarScope* llvm::TGParser::PushLocalScope () inline
Definition at line 189 of file TGParser.h.
References move.
TokError()
bool llvm::TGParser::TokError (const Twine & Msg) const inline
Definition at line 182 of file TGParser.h.
References Error(), llvm::TGLexer::getLoc(), and llvm::AMDGPU::SendMsg::Msg.
Referenced by ParseFile().
The documentation for this class was generated from the following files:
lib/TableGen/TGParser.h
lib/TableGen/TGParser.cpp