LLVM: llvm::RISCVInstPrinter Class Reference
llvm::RISCVInstPrinter Class Reference
#include "Target/RISCV/MCTargetDesc/RISCVInstPrinter.h"
Public Member Functions
RISCVInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
bool applyTargetSpecificCLOption (StringRef Opt) override
Customize the printer according to a command line option.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
void printRegName (raw_ostream &O, MCRegister Reg) const override
Print the assembler register name.
void printOperand (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O, const char *Modifier=nullptr)
void printBranchOperand (const MCInst *MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printCSRSystemRegister (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printFenceArg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printFRMArg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printZeroOffsetMemOp (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printVTypeI (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
void printVMaskReg (const MCInst *MI, unsigned OpNo, const MCSubtargetInfo &STI, raw_ostream &O)
std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI) override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
bool printAliasInstr (const MCInst *MI, uint64_t Address, const MCSubtargetInfo &STI, raw_ostream &O)
void printCustomAliasOperand (const MCInst *MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo &STI, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg)
static const char * getRegisterName (MCRegister Reg, unsigned AltIdx)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
Detailed Description
Definition at line 21 of file RISCVInstPrinter.h.
Constructor & Destructor Documentation
RISCVInstPrinter()
llvm::RISCVInstPrinter::RISCVInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 23 of file RISCVInstPrinter.h.
Member Function Documentation
applyTargetSpecificCLOption()
bool RISCVInstPrinter::applyTargetSpecificCLOption (StringRef Opt) override virtual
Customize the printer according to a command line option.
Returns
true if the option is recognized and applied.
Reimplemented from llvm::MCInstPrinter.
Definition at line 49 of file RISCVInstPrinter.cpp.
References ArchRegNames, and llvm::MCInstPrinter::PrintAliases.
getMnemonic()
std::pair<const char *, uint64_t> llvm::RISCVInstPrinter::getMnemonic (const MCInst * MI) override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
getRegisterName() [1/2]
const char * RISCVInstPrinter::getRegisterName (MCRegister Reg) static
Definition at line 195 of file RISCVInstPrinter.cpp.
References ArchRegNames.
Referenced by printRegName().
getRegisterName() [2/2]
static const char* llvm::RISCVInstPrinter::getRegisterName (MCRegister Reg, unsigned AltIdx) static
printAliasInstr()
bool llvm::RISCVInstPrinter::printAliasInstr (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by printInst().
printBranchOperand()
void RISCVInstPrinter::printBranchOperand (const MCInst * MI, uint64_t Address, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 101 of file RISCVInstPrinter.cpp.
References llvm::MCInstPrinter::formatHex(), llvm::MCOperand::getImm(), llvm::MCSubtargetInfo::hasFeature(), llvm::MCOperand::isImm(), MI, llvm::RISCVFenceField::O, llvm::MCInstPrinter::PrintBranchImmAsAddress, printOperand(), and uint64_t.
printCSRSystemRegister()
void RISCVInstPrinter::printCSRSystemRegister (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 119 of file RISCVInstPrinter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::RISCVMatInt::Imm, llvm::AArch64SysReg::lookupSysRegByEncoding(), MI, and llvm::RISCVFenceField::O.
printCustomAliasOperand()
void llvm::RISCVInstPrinter::printCustomAliasOperand (const MCInst * MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, const MCSubtargetInfo & STI, raw_ostream & O)
printFenceArg()
void RISCVInstPrinter::printFenceArg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 130 of file RISCVInstPrinter.cpp.
References assert(), llvm::RISCVFenceField::I, MI, llvm::RISCVFenceField::O, llvm::RISCVFenceField::R, and llvm::RISCVFenceField::W.
printFRMArg()
void RISCVInstPrinter::printFRMArg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 148 of file RISCVInstPrinter.cpp.
References llvm::RISCVFPRndMode::DYN, MI, NoAliases, llvm::RISCVFenceField::O, llvm::MCInstPrinter::PrintAliases, and llvm::RISCVFPRndMode::roundingModeToString().
printInst()
void RISCVInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 62 of file RISCVInstPrinter.cpp.
References MI, NoAliases, llvm::RISCVFenceField::O, llvm::MCInstPrinter::PrintAliases, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), printInstruction(), and llvm::RISCVRVC::uncompress().
printInstruction()
void llvm::RISCVInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, const MCSubtargetInfo & STI, raw_ostream & O)
Referenced by printInst().
printOperand()
void RISCVInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 81 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, MI, llvm::RISCVFenceField::O, llvm::MCExpr::print(), and printRegName().
Referenced by printBranchOperand().
printRegName()
void RISCVInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 77 of file RISCVInstPrinter.cpp.
References getRegisterName(), and llvm::RISCVFenceField::O.
Referenced by printOperand(), printVMaskReg(), and printZeroOffsetMemOp().
printVMaskReg()
void RISCVInstPrinter::printVMaskReg (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 182 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), MI, llvm::RISCVFenceField::O, and printRegName().
printVTypeI()
void RISCVInstPrinter::printVTypeI (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 168 of file RISCVInstPrinter.cpp.
References llvm::RISCVVType::getSEW(), llvm::RISCVVType::getVLMUL(), llvm::RISCVMatInt::Imm, llvm::RISCVII::LMUL_RESERVED, MI, llvm::RISCVFenceField::O, and llvm::RISCVVType::printVType().
printZeroOffsetMemOp()
void RISCVInstPrinter::printZeroOffsetMemOp (const MCInst * MI, unsigned OpNo, const MCSubtargetInfo & STI, raw_ostream & O)
Definition at line 157 of file RISCVInstPrinter.cpp.
References assert(), llvm::MCOperand::getReg(), llvm::MCOperand::isReg(), MI, llvm::RISCVFenceField::O, and printRegName().
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCTargetDesc/RISCVInstPrinter.h
lib/Target/RISCV/MCTargetDesc/RISCVInstPrinter.cpp