LLVM: llvm::WebAssemblyInstrInfo Class Reference
llvm::WebAssemblyInstrInfo Class Reference final
#include "Target/WebAssembly/WebAssemblyInstrInfo.h"
Public Member Functions
WebAssemblyInstrInfo (const WebAssemblySubtarget &STI)
const WebAssemblyRegisterInfo & getRegisterInfo () const
bool isReallyTriviallyReMaterializable (const MachineInstr &MI) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
MachineInstr * commuteInstructionImpl (MachineInstr &MI, bool NewMI, unsigned OpIdx1, unsigned OpIdx2) const override
bool analyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify=false) const override
unsigned removeBranch (MachineBasicBlock &MBB, int *BytesRemoved=nullptr) const override
unsigned insertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, ArrayRef< MachineOperand > Cond, const DebugLoc &DL, int *BytesAdded=nullptr) const override
bool reverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
ArrayRef< std::pair< int, const char * > > getSerializableTargetIndices () const override
const MachineOperand & getCalleeOperand (const MachineInstr &MI) const override
bool isExplicitTargetIndexDef (const MachineInstr &MI, int &Index, int64_t &Offset) const override
Detailed Description
Definition at line 38 of file WebAssemblyInstrInfo.h.
Constructor & Destructor Documentation
WebAssemblyInstrInfo()
WebAssemblyInstrInfo::WebAssemblyInstrInfo (const WebAssemblySubtarget & STI) explicit
Definition at line 36 of file WebAssemblyInstrInfo.cpp.
Member Function Documentation
analyzeBranch()
bool WebAssemblyInstrInfo::analyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify = false) const override
Definition at line 89 of file WebAssemblyInstrInfo.cpp.
References llvm::ISD::BR, Cond, llvm::MachineOperand::CreateImm(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), MBB, MI, TBB, and llvm::MachineBasicBlock::terminators().
commuteInstructionImpl()
MachineInstr * WebAssemblyInstrInfo::commuteInstructionImpl (MachineInstr & MI, bool NewMI, unsigned OpIdx1, unsigned OpIdx2) const override
Definition at line 75 of file WebAssemblyInstrInfo.cpp.
References llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::WebAssemblyFunctionInfo::isVRegStackified(), and MI.
copyPhysReg()
void WebAssemblyInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, MCRegister DestReg, MCRegister SrcReg, bool KillSrc) const override
Definition at line 57 of file WebAssemblyInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::get(), llvm::WebAssembly::getCopyOpcodeForRegClass(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), I, llvm::Register::isVirtualRegister(), llvm::RegState::Kill, MBB, and MRI.
getCalleeOperand()
const MachineOperand & WebAssemblyInstrInfo::getCalleeOperand (const MachineInstr & MI) const override
Definition at line 204 of file WebAssemblyInstrInfo.cpp.
References llvm::WebAssembly::getCalleeOp(), and MI.
getRegisterInfo()
const WebAssemblyRegisterInfo& llvm::WebAssemblyInstrInfo::getRegisterInfo () const inline
Definition at line 44 of file WebAssemblyInstrInfo.h.
Referenced by llvm::WebAssemblySubtarget::getRegisterInfo().
getSerializableTargetIndices()
ArrayRef< std::pair< int, const char * > > WebAssemblyInstrInfo::getSerializableTargetIndices () const override
Definition at line 193 of file WebAssemblyInstrInfo.cpp.
References llvm::ArrayRef(), llvm::WebAssembly::TI_GLOBAL_FIXED, llvm::WebAssembly::TI_GLOBAL_RELOC, llvm::WebAssembly::TI_LOCAL, llvm::WebAssembly::TI_LOCAL_INDIRECT, and llvm::WebAssembly::TI_OPERAND_STACK.
insertBranch()
unsigned WebAssemblyInstrInfo::insertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, ArrayRef< MachineOperand > Cond, const DebugLoc & DL, int * BytesAdded = nullptr) const override
Definition at line 159 of file WebAssemblyInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addMBB(), assert(), llvm::ISD::BR, llvm::BuildMI(), Cond, DL, llvm::get(), MBB, and TBB.
isExplicitTargetIndexDef()
bool WebAssemblyInstrInfo::isExplicitTargetIndexDef (const MachineInstr & MI, int & Index, int64_t & Offset) const override
Definition at line 223 of file WebAssemblyInstrInfo.cpp.
References llvm::WebAssembly::isLocalSet(), llvm::WebAssembly::isLocalTee(), MI, llvm::Offset, and llvm::WebAssembly::TI_LOCAL.
isReallyTriviallyReMaterializable()
bool WebAssemblyInstrInfo::isReallyTriviallyReMaterializable (const MachineInstr & MI) const override
Definition at line 42 of file WebAssemblyInstrInfo.cpp.
References MI.
removeBranch()
unsigned WebAssemblyInstrInfo::removeBranch (MachineBasicBlock & MBB, int * BytesRemoved = nullptr) const override
Definition at line 137 of file WebAssemblyInstrInfo.cpp.
References assert(), I, llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), and MBB.
reverseBranchCondition()
bool WebAssemblyInstrInfo::reverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 185 of file WebAssemblyInstrInfo.cpp.
References assert(), Cond, and llvm::MachineOperand::CreateImm().
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyInstrInfo.h
lib/Target/WebAssembly/WebAssemblyInstrInfo.cpp