LLVM: llvm::LoopAccessInfoManager Class Reference
llvm::LoopAccessInfoManager Class Reference
#include "llvm/Analysis/LoopAccessAnalysis.h"
Public Member Functions
LoopAccessInfoManager (ScalarEvolution &SE, AAResults &AA, DominatorTree &DT, LoopInfo &LI, const TargetLibraryInfo *TLI)
const LoopAccessInfo & getInfo (Loop &L)
void clear ()
Detailed Description
Definition at line 769 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
LoopAccessInfoManager()
llvm::LoopAccessInfoManager::LoopAccessInfoManager (ScalarEvolution & SE, AAResults & AA, DominatorTree & DT, LoopInfo & LI, const TargetLibraryInfo * TLI) inline
Definition at line 781 of file LoopAccessAnalysis.h.
Member Function Documentation
clear()
void llvm::LoopAccessInfoManager::clear () inline
Definition at line 787 of file LoopAccessAnalysis.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::clear().
Referenced by eliminateLoadsAcrossLoops(), and llvm::LoopVectorizePass::runImpl().
getInfo()
const LoopAccessInfo & LoopAccessInfoManager::getInfo (Loop & L)
Definition at line 2673 of file LoopAccessAnalysis.cpp.
References I.
Referenced by eliminateLoadsAcrossLoops().
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopAccessAnalysis.h
lib/Analysis/LoopAccessAnalysis.cpp