LLVM: llvm::DICompositeType Class Reference
llvm::DICompositeType Class Reference
Composite types.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DEFINE_MDNODE_GET (DICompositeType,(unsigned Tag, StringRef Name, DIFile *File, unsigned Line, DIScope *Scope, DIType *BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags, DINodeArray Elements, unsigned RuntimeLang, DIType *VTableHolder, DITemplateParameterArray TemplateParams=nullptr, StringRef Identifier="", DIDerivedType *Discriminator=nullptr, Metadata *DataLocation=nullptr, Metadata *Associated=nullptr, Metadata *Allocated=nullptr, Metadata *Rank=nullptr, DINodeArray Annotations=nullptr),(Tag, Name, File, Line, Scope, BaseType, SizeInBits, AlignInBits, OffsetInBits, Flags, Elements, RuntimeLang, VTableHolder, TemplateParams, Identifier, Discriminator, DataLocation, Associated, Allocated, Rank, Annotations)) DEFINE_MDNODE_GET(DICompositeType
DIType * getBaseType () const
DINodeArray getElements () const
DIType * getVTableHolder () const
DITemplateParameterArray getTemplateParams () const
StringRef getIdentifier () const
unsigned getRuntimeLang () const
Metadata * getRawBaseType () const
Metadata * getRawElements () const
Metadata * getRawVTableHolder () const
Metadata * getRawTemplateParams () const
MDString * getRawIdentifier () const
Metadata * getRawDiscriminator () const
DIDerivedType * getDiscriminator () const
Metadata * getRawDataLocation () const
DIVariable * getDataLocation () const
DIExpression * getDataLocationExp () const
Metadata * getRawAssociated () const
DIVariable * getAssociated () const
DIExpression * getAssociatedExp () const
Metadata * getRawAllocated () const
DIVariable * getAllocated () const
DIExpression * getAllocatedExp () const
Metadata * getRawRank () const
ConstantInt * getRankConst () const
DIExpression * getRankExp () const
Metadata * getRawAnnotations () const
DINodeArray getAnnotations () const
void replaceElements (DINodeArray Elements)
Replace operands.
void replaceVTableHolder (DIType *VTableHolder)
void replaceTemplateParams (DITemplateParameterArray TemplateParams)
Public Member Functions inherited from llvm::DIType
TempDIType clone () const
unsigned getLine () const
uint64_t getSizeInBits () const
uint32_t getAlignInBits () const
uint32_t getAlignInBytes () const
uint64_t getOffsetInBits () const
DIFlags getFlags () const
DIScope * getScope () const
StringRef getName () const
Metadata * getRawScope () const
MDString * getRawName () const
TempDIType cloneWithFlags (DIFlags NewFlags) const
Returns a new temporary DIType with updated Flags.
bool isPrivate () const
bool isProtected () const
bool isPublic () const
bool isForwardDecl () const
bool isAppleBlockExtension () const
bool isVirtual () const
bool isArtificial () const
bool isObjectPointer () const
bool isObjcClassComplete () const
bool isVector () const
bool isBitField () const
bool isStaticMember () const
bool isLValueReference () const
bool isRValueReference () const
bool isTypePassByValue () const
bool isTypePassByReference () const
bool isBigEndian () const
bool isLittleEndian () const
bool getExportSymbols () const
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
StringRef getName () const
DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static DICompositeType * getODRTypeIfExists (LLVMContext &Context, MDString &Identifier)
static DICompositeType * buildODRType (LLVMContext &Context, MDString &Identifier, unsigned Tag, MDString *Name, Metadata *File, unsigned Line, Metadata *Scope, Metadata *BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags, Metadata *Elements, unsigned RuntimeLang, Metadata *VTableHolder, Metadata *TemplateParams, Metadata *Discriminator, Metadata *DataLocation, Metadata *Associated, Metadata *Allocated, Metadata *Rank, Metadata *Annotations)
Build a DICompositeType with the given ODR identifier.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIType
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
unsigned Tag
unsigned MDString * Name
unsigned MDString Metadata * File
unsigned MDString Metadata unsigned Line
unsigned MDString Metadata unsigned Metadata * Scope
unsigned MDString Metadata unsigned Metadata Metadata * BaseType
unsigned MDString Metadata unsigned Metadata Metadata uint64_t SizeInBits
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t AlignInBits
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t OffsetInBits
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Flags
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata * Elements
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned RuntimeLang
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata * VTableHolder
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata * TemplateParams = nullptr
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString * Identifier = nullptr
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata * Discriminator = nullptr
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata * DataLocation = nullptr
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata Metadata * Associated = nullptr
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata Metadata Metadata * Allocated = nullptr
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata Metadata Metadata Metadata * Rank = nullptr
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata Metadata Metadata Metadata Metadata * Annotations
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic, FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIType
DIType (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags, ArrayRef< Metadata * > Ops)
~DIType ()=default
void init (unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags)
void mutate (unsigned Tag, unsigned Line, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags)
Change fields in place.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Composite types.
TODO: Detach from DerivedTypeBase (split out MDEnumType?). TODO: Create a custom, unrelated node for DW_TAG_array_type.
Definition at line 1083 of file DebugInfoMetadata.h.
Member Function Documentation
buildODRType()
DICompositeType * DICompositeType::buildODRType (LLVMContext & Context, MDString & Identifier, unsigned Tag, MDString * Name, Metadata * File, unsigned Line, Metadata * Scope, Metadata * BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags, Metadata * Elements, unsigned RuntimeLang, Metadata * VTableHolder, Metadata * TemplateParams, Metadata * Discriminator, Metadata * DataLocation, Metadata * Associated, Metadata * Allocated, Metadata * Rank, Metadata * Annotations) static
Build a DICompositeType with the given ODR identifier.
Looks up the mapped DICompositeType for the given ODR Identifier. If it doesn't exist, creates a new one. If it does exist and isForwardDecl(), and the new arguments would be a definition, mutates the the type in place. In either case, returns the type.
If not LLVMContext::isODRUniquingDebugTypes(), this function returns nullptr.
Definition at line 713 of file DebugInfoMetadata.cpp.
References AlignInBits, Allocated, assert(), Associated, BaseType, llvm::sys::path::begin(), Context, DataLocation, Discriminator, llvm::LLVMContextImpl::DITypeMap, E, Elements, llvm::StringRef::empty(), llvm::sys::path::end(), File, Flags, llvm::MDNode::getDistinct(), llvm::MDString::getString(), I, Identifier, llvm::LLVMContext::isODRUniquingDebugTypes(), Line, Name, OffsetInBits, llvm::LLVMContext::pImpl, Rank, Scope, SizeInBits, TemplateParams, and VTableHolder.
classof()
static bool llvm::DICompositeType::classof (const Metadata * MD) inline static
Definition at line 1298 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
DEFINE_MDNODE_GET()
llvm::DICompositeType::DEFINE_MDNODE_GET (DICompositeType , (unsigned Tag, StringRef Name, DIFile *File, unsigned Line, DIScope *Scope, DIType *BaseType, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, DIFlags Flags, DINodeArray Elements, unsigned RuntimeLang, DIType *VTableHolder, DITemplateParameterArray TemplateParams=nullptr, StringRef Identifier="", DIDerivedType *Discriminator=nullptr, Metadata *DataLocation=nullptr, Metadata *Associated=nullptr, Metadata *Allocated=nullptr, Metadata *Rank=nullptr, DINodeArray Annotations=nullptr) , (Tag, Name, File, Line, Scope, BaseType, SizeInBits, AlignInBits, OffsetInBits, Flags, Elements, RuntimeLang, VTableHolder, TemplateParams, Identifier, Discriminator, DataLocation, Associated, Allocated, Rank, Annotations))
getAllocated()
DIVariable* llvm::DICompositeType::getAllocated () const inline
Definition at line 1253 of file DebugInfoMetadata.h.
References getRawAllocated().
getAllocatedExp()
DIExpression* llvm::DICompositeType::getAllocatedExp () const inline
Definition at line 1256 of file DebugInfoMetadata.h.
References getRawAllocated().
getAnnotations()
DINodeArray llvm::DICompositeType::getAnnotations () const inline
Definition at line 1270 of file DebugInfoMetadata.h.
References getRawAnnotations().
Referenced by llvm::DwarfUnit::constructTypeDIE().
getAssociated()
DIVariable* llvm::DICompositeType::getAssociated () const inline
Definition at line 1246 of file DebugInfoMetadata.h.
References getRawAssociated().
getAssociatedExp()
DIExpression* llvm::DICompositeType::getAssociatedExp () const inline
Definition at line 1249 of file DebugInfoMetadata.h.
References getRawAssociated().
getBaseType()
DIType* llvm::DICompositeType::getBaseType () const inline
Definition at line 1216 of file DebugInfoMetadata.h.
References getRawBaseType().
Referenced by hasVectorBeenPadded().
getDataLocation()
DIVariable* llvm::DICompositeType::getDataLocation () const inline
Definition at line 1239 of file DebugInfoMetadata.h.
References getRawDataLocation().
getDataLocationExp()
DIExpression* llvm::DICompositeType::getDataLocationExp () const inline
Definition at line 1242 of file DebugInfoMetadata.h.
References getRawDataLocation().
getDiscriminator()
DIDerivedType* llvm::DICompositeType::getDiscriminator () const inline
Definition at line 1235 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::constructTypeDIE().
getElements()
DINodeArray llvm::DICompositeType::getElements () const inline
Definition at line 1217 of file DebugInfoMetadata.h.
References getRawElements().
Referenced by calcArraySize(), llvm::BTFTypeEnum::completeType(), llvm::BTFTypeStruct::completeType(), llvm::BTFTypeEnum64::completeType(), llvm::DwarfUnit::constructTypeDIE(), hasVectorBeenPadded(), and replaceElements().
getIdentifier()
StringRef llvm::DICompositeType::getIdentifier () const inline
Definition at line 1226 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
Referenced by getCommonClassOptions(), and shouldAlwaysEmitCompleteClassType().
getODRTypeIfExists()
DICompositeType * DICompositeType::getODRTypeIfExists (LLVMContext & Context, MDString & Identifier) static
Definition at line 780 of file DebugInfoMetadata.cpp.
References assert(), Context, llvm::LLVMContextImpl::DITypeMap, llvm::StringRef::empty(), llvm::MDString::getString(), Identifier, llvm::LLVMContext::isODRUniquingDebugTypes(), and llvm::LLVMContext::pImpl.
getRankConst()
ConstantInt* llvm::DICompositeType::getRankConst () const inline
Definition at line 1260 of file DebugInfoMetadata.h.
References getRawRank().
getRankExp()
DIExpression* llvm::DICompositeType::getRankExp () const inline
Definition at line 1265 of file DebugInfoMetadata.h.
References getRawRank().
getRawAllocated()
Metadata* llvm::DICompositeType::getRawAllocated () const inline
Definition at line 1252 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getAllocated(), and getAllocatedExp().
getRawAnnotations()
Metadata* llvm::DICompositeType::getRawAnnotations () const inline
Definition at line 1269 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getAnnotations().
getRawAssociated()
Metadata* llvm::DICompositeType::getRawAssociated () const inline
Definition at line 1245 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getAssociated(), and getAssociatedExp().
getRawBaseType()
Metadata* llvm::DICompositeType::getRawBaseType () const inline
Definition at line 1229 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getBaseType().
getRawDataLocation()
Metadata* llvm::DICompositeType::getRawDataLocation () const inline
Definition at line 1238 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getDataLocation(), and getDataLocationExp().
getRawDiscriminator()
Metadata* llvm::DICompositeType::getRawDiscriminator () const inline
Definition at line 1234 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
getRawElements()
Metadata* llvm::DICompositeType::getRawElements () const inline
Definition at line 1230 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getElements().
getRawIdentifier()
MDString* llvm::DICompositeType::getRawIdentifier () const inline
Definition at line 1233 of file DebugInfoMetadata.h.
getRawRank()
Metadata* llvm::DICompositeType::getRawRank () const inline
Definition at line 1259 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getRankConst(), and getRankExp().
getRawTemplateParams()
Metadata* llvm::DICompositeType::getRawTemplateParams () const inline
Definition at line 1232 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getTemplateParams().
getRawVTableHolder()
Metadata* llvm::DICompositeType::getRawVTableHolder () const inline
Definition at line 1231 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getVTableHolder().
getRuntimeLang()
unsigned llvm::DICompositeType::getRuntimeLang () const inline
Definition at line 1227 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::constructTypeDIE().
getTemplateParams()
DITemplateParameterArray llvm::DICompositeType::getTemplateParams () const inline
Definition at line 1223 of file DebugInfoMetadata.h.
References getRawTemplateParams().
Referenced by llvm::DwarfUnit::constructTypeDIE().
getVTableHolder()
DIType* llvm::DICompositeType::getVTableHolder () const inline
Definition at line 1220 of file DebugInfoMetadata.h.
References getRawVTableHolder().
Referenced by llvm::DwarfUnit::constructTypeDIE().
replaceElements()
void llvm::DICompositeType::replaceElements (DINodeArray Elements) inline
Replace operands.
If this isUniqued() and not isResolved(), on a uniquing collision this will be RAUW'ed and deleted. Use a TrackingMDRef to keep track of its movement if necessary.
Definition at line 1280 of file DebugInfoMetadata.h.
References assert(), Elements, llvm::MDString::get(), getElements(), llvm::is_contained(), and llvm::MDNode::replaceOperandWith().
replaceTemplateParams()
void llvm::DICompositeType::replaceTemplateParams (DITemplateParameterArray TemplateParams) inline
Definition at line 1293 of file DebugInfoMetadata.h.
References llvm::MDString::get(), llvm::MDNode::replaceOperandWith(), and TemplateParams.
replaceVTableHolder()
void llvm::DICompositeType::replaceVTableHolder (DIType * VTableHolder) inline
Definition at line 1289 of file DebugInfoMetadata.h.
References llvm::MDNode::replaceOperandWith(), and VTableHolder.
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 1084 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 1085 of file DebugInfoMetadata.h.
Member Data Documentation
AlignInBits
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t llvm::DICompositeType::AlignInBits
Definition at line 1165 of file DebugInfoMetadata.h.
Referenced by buildODRType().
Allocated
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata Metadata Metadata* llvm::DICompositeType::Allocated = nullptr
Definition at line 1169 of file DebugInfoMetadata.h.
Referenced by buildODRType().
Annotations
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata Metadata Metadata Metadata Metadata* llvm::DICompositeType::Annotations
Initial value:
= nullptr),
      (Tag, Name, File, Line, Scope, BaseType, SizeInBits, AlignInBits,
       OffsetInBits, Flags, Elements, RuntimeLang, VTableHolder, TemplateParams,
       Identifier, Discriminator, DataLocation, Associated, Allocated, Rank,
       Annotations))
  TempDICompositeType clone() const { return cloneImpl(); }
  static DICompositeType *
  getODRType(LLVMContext &Context, MDString &Identifier, unsigned Tag,
             MDString *Name, Metadata *File, unsigned Line, Metadata *Scope,
             Metadata *BaseType, uint64_t SizeInBits, uint32_t AlignInBits,
             uint64_t OffsetInBits, DIFlags Flags, Metadata *Elements,
             unsigned RuntimeLang, Metadata *VTableHolder,
             Metadata *TemplateParams, Metadata *Discriminator,
             Metadata *DataLocation, Metadata *Associated, Metadata *Allocated,
             Metadata *Rank, Metadata *Annotations)
Definition at line 1170 of file DebugInfoMetadata.h.
Associated
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata Metadata* llvm::DICompositeType::Associated = nullptr
Definition at line 1169 of file DebugInfoMetadata.h.
Referenced by buildODRType().
BaseType
unsigned MDString Metadata unsigned Metadata Metadata* llvm::DICompositeType::BaseType
Definition at line 1164 of file DebugInfoMetadata.h.
Referenced by buildODRType().
DataLocation
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata* llvm::DICompositeType::DataLocation = nullptr
Definition at line 1168 of file DebugInfoMetadata.h.
Referenced by buildODRType().
Discriminator
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata* llvm::DICompositeType::Discriminator = nullptr
Definition at line 1168 of file DebugInfoMetadata.h.
Referenced by buildODRType().
Elements
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata* llvm::DICompositeType::Elements
Definition at line 1166 of file DebugInfoMetadata.h.
Referenced by buildODRType(), and replaceElements().
File
unsigned MDString Metadata* llvm::DICompositeType::File
Definition at line 1163 of file DebugInfoMetadata.h.
Referenced by buildODRType().
Flags
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags llvm::DICompositeType::Flags
Definition at line 1165 of file DebugInfoMetadata.h.
Referenced by buildODRType().
Identifier
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString* llvm::DICompositeType::Identifier = nullptr
Definition at line 1167 of file DebugInfoMetadata.h.
Referenced by buildODRType(), and getODRTypeIfExists().
Line
unsigned MDString Metadata unsigned llvm::DICompositeType::Line
Definition at line 1163 of file DebugInfoMetadata.h.
Referenced by buildODRType().
Name
unsigned MDString* llvm::DICompositeType::Name
Definition at line 1163 of file DebugInfoMetadata.h.
Referenced by buildODRType().
OffsetInBits
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t llvm::DICompositeType::OffsetInBits
Definition at line 1165 of file DebugInfoMetadata.h.
Referenced by buildODRType().
Rank
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata MDString Metadata Metadata Metadata Metadata Metadata* llvm::DICompositeType::Rank = nullptr
Definition at line 1170 of file DebugInfoMetadata.h.
Referenced by buildODRType().
RuntimeLang
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned llvm::DICompositeType::RuntimeLang
Definition at line 1166 of file DebugInfoMetadata.h.
Scope
unsigned MDString Metadata unsigned Metadata* llvm::DICompositeType::Scope
Definition at line 1164 of file DebugInfoMetadata.h.
Referenced by buildODRType().
SizeInBits
unsigned MDString Metadata unsigned Metadata Metadata uint64_t llvm::DICompositeType::SizeInBits
Definition at line 1164 of file DebugInfoMetadata.h.
Referenced by buildODRType().
Tag
unsigned llvm::DICompositeType::Tag
Definition at line 1163 of file DebugInfoMetadata.h.
TemplateParams
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata Metadata* llvm::DICompositeType::TemplateParams = nullptr
Definition at line 1167 of file DebugInfoMetadata.h.
Referenced by buildODRType(), and replaceTemplateParams().
VTableHolder
unsigned MDString Metadata unsigned Metadata Metadata uint64_t uint32_t uint64_t DIFlags Metadata unsigned Metadata* llvm::DICompositeType::VTableHolder
Definition at line 1166 of file DebugInfoMetadata.h.
Referenced by buildODRType(), and replaceVTableHolder().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp