LLVM: llvm::MCStreamer Class Reference
llvm::MCStreamer Class Reference abstract
Streaming machine code generation interface.
#include "llvm/MC/MCStreamer.h"
Public Member Functions
MCStreamer (const MCStreamer &)=delete
MCStreamer & operator= (const MCStreamer &)=delete
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
virtual void visitUsedSymbol (const MCSymbol &Sym)
void setTargetStreamer (MCTargetStreamer *TS)
void setStartTokLocPtr (const SMLoc *Loc)
SMLoc getStartTokLoc () const
virtual void reset ()
State management.
MCContext & getContext () const
virtual MCAssembler * getAssemblerPtr ()
void setUseAssemblerInfoForParsing (bool v)
bool getUseAssemblerInfoForParsing ()
MCTargetStreamer * getTargetStreamer ()
void setAllowAutoPadding (bool v)
bool getAllowAutoPadding () const
virtual MCSymbol * emitCFILabel ()
When emitting an object file, create and emit a real label.
WinEH::FrameInfo * EnsureValidWinFrameInfo (SMLoc Loc)
Retrieve the current frame info if one is available and it is not yet closed.
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
bool hasUnfinishedDwarfFrameInfo ()
unsigned getNumWinFrameInfos ()
ArrayRef< std::unique_ptr< WinEH::FrameInfo > > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
virtual void emitFileDirective (StringRef Filename)
Switch to a new logical file.
virtual void emitFileDirective (StringRef Filename, StringRef CompilerVerion, StringRef TimeStamp, StringRef Description)
Emit ".file assembler diretive with additioal info.
virtual void emitIdent (StringRef IdentString)
Emit the "identifiers" directive.
unsigned emitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, std::optional< MD5::MD5Result > Checksum=std::nullopt, std::optional< StringRef > Source=std::nullopt, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual Expected< unsigned > tryEmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, std::optional< MD5::MD5Result > Checksum=std::nullopt, std::optional< StringRef > Source=std::nullopt, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual void emitDwarfFile0Directive (StringRef Directory, StringRef Filename, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source, unsigned CUID=0)
Specify the "root" file of the compilation, using the ".file 0" extension.
virtual void emitCFIBKeyFrame ()
virtual void emitCFIMTETaggedFrame ()
virtual void emitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName)
This implements the DWARF2 '.loc fileno lineno ...' assembler directive.
virtual bool emitCVFileDirective (unsigned FileNo, StringRef Filename, ArrayRef< uint8_t > Checksum, unsigned ChecksumKind)
Associate a filename with a specified logical file number, and also specify that file's checksum information.
virtual bool emitCVFuncIdDirective (unsigned FunctionId)
Introduces a function id for use with .cv_loc.
virtual bool emitCVInlineSiteIdDirective (unsigned FunctionId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol, SMLoc Loc)
Introduces an inline call site id for use with .cv_loc.
virtual void emitCVLocDirective (unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt, StringRef FileName, SMLoc Loc)
This implements the CodeView '.cv_loc' assembler directive.
virtual void emitCVLinetableDirective (unsigned FunctionId, const MCSymbol *FnStart, const MCSymbol *FnEnd)
This implements the CodeView '.cv_linetable' assembler directive.
virtual void emitCVInlineLinetableDirective (unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol *FnStartSym, const MCSymbol *FnEndSym)
This implements the CodeView '.cv_inline_linetable' assembler directive.
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, StringRef FixedSizePortion)
This implements the CodeView '.cv_def_range' assembler directive.
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeRegisterRelHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeSubfieldRegisterHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeRegisterHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeFramePointerRelHeader DRHdr)
virtual void emitCVStringTableDirective ()
This implements the CodeView '.cv_stringtable' assembler directive.
virtual void emitCVFileChecksumsDirective ()
This implements the CodeView '.cv_filechecksums' assembler directive.
virtual void emitCVFileChecksumOffsetDirective (unsigned FileNo)
This implements the CodeView '.cv_filechecksumoffset' assembler directive.
virtual void emitCVFPOData (const MCSymbol *ProcSym, SMLoc Loc={})
This implements the CodeView '.cv_fpo_data' assembler directive.
virtual void emitAbsoluteSymbolDiff (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size)
Emit the absolute difference between two symbols.
virtual void emitAbsoluteSymbolDiffAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo)
Emit the absolute difference between two symbols encoded with ULEB128.
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
virtual void emitCFISections (bool EH, bool Debug)
void emitCFIStartProc (bool IsSimple, SMLoc Loc=SMLoc())
void emitCFIEndProc ()
virtual void emitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void emitCFIDefCfaOffset (int64_t Offset)
virtual void emitCFIDefCfaRegister (int64_t Register)
virtual void emitCFILLVMDefAspaceCfa (int64_t Register, int64_t Offset, int64_t AddressSpace)
virtual void emitCFIOffset (int64_t Register, int64_t Offset)
virtual void emitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void emitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void emitCFIRememberState ()
virtual void emitCFIRestoreState ()
virtual void emitCFISameValue (int64_t Register)
virtual void emitCFIRestore (int64_t Register)
virtual void emitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void emitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void emitCFIEscape (StringRef Values)
virtual void emitCFIReturnColumn (int64_t Register)
virtual void emitCFIGnuArgsSize (int64_t Size)
virtual void emitCFISignalFrame ()
virtual void emitCFIUndefined (int64_t Register)
virtual void emitCFIRegister (int64_t Register1, int64_t Register2)
virtual void emitCFIWindowSave ()
virtual void emitCFINegateRAState ()
virtual void emitWinCFIStartProc (const MCSymbol *Symbol, SMLoc Loc=SMLoc())
virtual void emitWinCFIEndProc (SMLoc Loc=SMLoc())
virtual void emitWinCFIFuncletOrFuncEnd (SMLoc Loc=SMLoc())
This is used on platforms, such as Windows on ARM64, that require function or funclet sizes to be emitted in .xdata before the End marker is emitted for the frame.
virtual void emitWinCFIStartChained (SMLoc Loc=SMLoc())
virtual void emitWinCFIEndChained (SMLoc Loc=SMLoc())
virtual void emitWinCFIPushReg (MCRegister Register, SMLoc Loc=SMLoc())
virtual void emitWinCFISetFrame (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void emitWinCFIAllocStack (unsigned Size, SMLoc Loc=SMLoc())
virtual void emitWinCFISaveReg (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void emitWinCFISaveXMM (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void emitWinCFIPushFrame (bool Code, SMLoc Loc=SMLoc())
virtual void emitWinCFIEndProlog (SMLoc Loc=SMLoc())
virtual void emitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except, SMLoc Loc=SMLoc())
virtual void emitWinEHHandlerData (SMLoc Loc=SMLoc())
virtual void emitCGProfileEntry (const MCSymbolRefExpr *From, const MCSymbolRefExpr *To, uint64_t Count)
MCSection * getAssociatedPDataSection (const MCSection *TextSec)
Get the .pdata section used for the given section.
MCSection * getAssociatedXDataSection (const MCSection *TextSec)
Get the .xdata section used for the given section.
virtual void emitSyntaxDirective ()
virtual std::optional< std::pair< bool, std::string > > emitRelocDirective (const MCExpr &Offset, StringRef Name, const MCExpr *Expr, SMLoc Loc, const MCSubtargetInfo &STI)
Record a relocation described by the .reloc directive.
virtual void emitAddrsig ()
virtual void emitAddrsigSym (const MCSymbol *Sym)
virtual void emitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI)
Emit the given Instruction into the current section.
virtual void emitPseudoProbe (uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attr, const MCPseudoProbeInlineStack &InlineStack, MCSymbol *FnSym)
Emit the a pseudo probe into the current section.
virtual void emitBundleAlignMode (Align Alignment)
Set the bundle alignment mode from now on in the section.
virtual void emitBundleLock (bool AlignToEnd)
The following instructions are a bundle-locked group.
virtual void emitBundleUnlock ()
Ends a bundle-locked group.
void emitRawText (const Twine &String)
If this file is backed by a assembly streamer, this dumps the specified string in the output .s file.
virtual void finishImpl ()
Streamer specific finalization.
void finish (SMLoc EndLoc=SMLoc())
Finish emission of machine code.
virtual bool mayHaveInstructions (MCSection &Sec) const
void maybeEmitDwarf64Mark ()
Emit a special value of 0xffffffff if producing 64-bit debugging info.
virtual void emitDwarfUnitLength (uint64_t Length, const Twine &Comment)
Emit a unit length field.
virtual MCSymbol * emitDwarfUnitLength (const Twine &Prefix, const Twine &Comment)
Emit a unit length field.
virtual void emitDwarfLineStartLabel (MCSymbol *StartSym)
Emit the debug line start label.
virtual void emitDwarfLineEndEntry (MCSection *Section, MCSymbol *LastLabel)
Emit the debug line end entry.
virtual void emitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol *LastLabel, const MCSymbol *Label, unsigned PointerSize)
If targets does not support representing debug line section by .loc/.file directives in assembly output, we need to populate debug line section with raw debug line contents.
virtual void doFinalizationAtSectionEnd (MCSection *Section)
Do finalization for the streamer at the end of a section.
Assembly File Formatting.
virtual bool isVerboseAsm () const
Return true if this streamer supports verbose assembly and if it is enabled.
virtual bool hasRawTextSupport () const
Return true if this asm streamer supports emitting unformatted text to the .s file with EmitRawText.
virtual bool isIntegratedAssemblerRequired () const
Is the integrated assembler required for this streamer to function correctly?
virtual void AddComment (const Twine &T, bool EOL=true)
Add a textual comment.
virtual raw_ostream & getCommentOS ()
Return a raw_ostream that comments can be written to.
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
Print T and prefix it with the comment string (normally #) and optionally a tab.
virtual void addExplicitComment (const Twine &T)
Add explicit comment T.
virtual void emitExplicitComments ()
Emit added explicit comments.
virtual void addBlankLine ()
Emit a blank line to a .s file to pretty it up.
Symbol & Section Management
MCSectionSubPair getCurrentSection () const
Return the current section that the streamer is emitting code to.
MCSection * getCurrentSectionOnly () const
MCSectionSubPair getPreviousSection () const
Return the previous section that the streamer is emitting code to.
unsigned getSymbolOrder (const MCSymbol *Sym) const
Returns an index to represent the order a symbol was emitted in.
virtual void changeSection (MCSection *, const MCExpr *)
Update streamer for a new active section.
void pushSection ()
Save the current and previous section on the section stack.
bool popSection ()
Restore the current and previous section from the section stack.
bool subSection (const MCExpr *Subsection)
virtual void switchSection (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
void switchSectionNoChange (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
virtual void initSections (bool NoExecStack, const MCSubtargetInfo &STI)
Create the default sections and set the initial one.
MCSymbol * endSection (MCSection *Section)
void assignFragment (MCSymbol *Symbol, MCFragment *Fragment)
Sets the symbol's section.
virtual StringRef getMnemonic (MCInst &MI)
Returns the mnemonic for MI, if the streamer has access to a instruction printer and returns an empty string otherwise.
virtual void emitLabel (MCSymbol *Symbol, SMLoc Loc=SMLoc())
Emit a label for Symbol into the current section.
virtual void emitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void emitAssemblerFlag (MCAssemblerFlag Flag)
Note in the output the specified Flag.
virtual void emitLinkerOptions (ArrayRef< std::string > Kind)
Emit the given list Options of strings as linker options into the output.
virtual void emitDataRegion (MCDataRegionType Kind)
Note in the output the specified region Kind.
virtual void emitVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Specify the Mach-O minimum deployment target version.
virtual void emitBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Emit/Specify Mach-O build version command.
virtual void emitDarwinTargetVariantBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
void emitVersionForTarget (const Triple &Target, const VersionTuple &SDKVersion, const Triple *DarwinTargetVariantTriple, const VersionTuple &DarwinTargetVariantSDKVersion)
virtual void emitThumbFunc (MCSymbol *Func)
Note in the output that the specified Func is a Thumb mode function (ARM target only).
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
Emit an assignment of Value to Symbol.
virtual void emitConditionalAssignment (MCSymbol *Symbol, const MCExpr *Value)
Emit an assignment of Value to Symbol, but only if Value is also emitted.
virtual void emitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol)
Emit an weak reference from Alias to Symbol.
virtual bool emitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute)=0
Add the given Attribute to Symbol.
virtual void emitSymbolDesc (MCSymbol *Symbol, unsigned DescValue)
Set the DescValue for the Symbol.
virtual void beginCOFFSymbolDef (const MCSymbol *Symbol)
Start emitting COFF symbol definition.
virtual void emitCOFFSymbolStorageClass (int StorageClass)
Emit the storage class of the symbol.
virtual void emitCOFFSymbolType (int Type)
Emit the type of the symbol.
virtual void endCOFFSymbolDef ()
Marks the end of the symbol definition.
virtual void emitCOFFSafeSEH (MCSymbol const *Symbol)
virtual void emitCOFFSymbolIndex (MCSymbol const *Symbol)
Emits the symbol table index of a Symbol into the current section.
virtual void emitCOFFSectionIndex (MCSymbol const *Symbol)
Emits a COFF section index.
virtual void emitCOFFSecRel32 (MCSymbol const *Symbol, uint64_t Offset)
Emits a COFF section relative relocation.
virtual void emitCOFFImgRel32 (MCSymbol const *Symbol, int64_t Offset)
Emits a COFF image relative relocation.
virtual void emitXCOFFLocalCommonSymbol (MCSymbol *LabelSym, uint64_t Size, MCSymbol *CsectSym, Align Alignment)
Emits an lcomm directive with XCOFF csect information.
virtual void emitXCOFFSymbolLinkageWithVisibility (MCSymbol *Symbol, MCSymbolAttr Linkage, MCSymbolAttr Visibility)
Emit a symbol's linkage and visibility with a linkage directive for XCOFF.
virtual void emitXCOFFRenameDirective (const MCSymbol *Name, StringRef Rename)
Emit a XCOFF .rename directive which creates a synonym for an illegal or undesirable name.
virtual void emitXCOFFExceptDirective (const MCSymbol *Symbol, const MCSymbol *Trap, unsigned Lang, unsigned Reason, unsigned FunctionSize, bool hasDebug)
Emit an XCOFF .except directive which adds information about a trap instruction to the object file exception section.
virtual void emitXCOFFRefDirective (StringRef Sym)
Emit a XCOFF .ref directive which creates R_REF type entry in the relocation table for one or more symbols.
virtual void emitELFSize (MCSymbol *Symbol, const MCExpr *Value)
Emit an ELF .size directive.
virtual void emitELFSymverDirective (const MCSymbol *OriginalSym, StringRef Name, bool KeepOriginalSym)
Emit an ELF .symver directive.
virtual void emitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
virtual void emitGNUAttribute (unsigned Tag, unsigned Value)
Emit a .gnu_attribute directive.
virtual void emitCommonSymbol (MCSymbol *Symbol, uint64_t Size, Align ByteAlignment)=0
Emit a common symbol.
virtual void emitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, Align ByteAlignment)
Emit a local common (.lcomm) symbol.
virtual void emitZerofill (MCSection *Section, MCSymbol *Symbol=nullptr, uint64_t Size=0, Align ByteAlignment=Align(1), SMLoc Loc=SMLoc())=0
Emit the zerofill section and an optional symbol.
virtual void emitTBSSSymbol (MCSection *Section, MCSymbol *Symbol, uint64_t Size, Align ByteAlignment=Align(1))
Emit a thread local bss (.tbss) symbol.
Generating Data
virtual void emitBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitBinaryData (StringRef Data)
Functionally identical to EmitBytes.
virtual void emitValueImpl (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc())
Emit the expression Value into the output as a native integer of the given Size bytes.
void emitValue (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc())
virtual void emitIntValue (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
virtual void emitIntValue (APInt Value)
virtual void emitIntValueInHex (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes.
void emitInt8 (uint64_t Value)
void emitInt16 (uint64_t Value)
void emitInt32 (uint64_t Value)
void emitInt64 (uint64_t Value)
virtual void emitIntValueInHexWithPadding (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes, pads the field with leading zeros to Size width.
virtual void emitULEB128Value (const MCExpr *Value)
virtual void emitSLEB128Value (const MCExpr *Value)
unsigned emitULEB128IntValue (uint64_t Value, unsigned PadTo=0)
Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
unsigned emitSLEB128IntValue (int64_t Value)
Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void emitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
Special case of EmitValue that avoids the client having to pass in a MCExpr for MCSymbols.
virtual void emitDTPRel64Value (const MCExpr *Value)
Emit the expression Value into the output as a dtprel (64-bit DTP relative) value.
virtual void emitDTPRel32Value (const MCExpr *Value)
Emit the expression Value into the output as a dtprel (32-bit DTP relative) value.
virtual void emitTPRel64Value (const MCExpr *Value)
Emit the expression Value into the output as a tprel (64-bit TP relative) value.
virtual void emitTPRel32Value (const MCExpr *Value)
Emit the expression Value into the output as a tprel (32-bit TP relative) value.
virtual void emitGPRel64Value (const MCExpr *Value)
Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
virtual void emitGPRel32Value (const MCExpr *Value)
Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
void emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumBytes, uint64_t FillValue, SMLoc Loc=SMLoc())
Emit Size bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumValues, int64_t Size, int64_t Expr, SMLoc Loc=SMLoc())
Emit NumValues copies of Size bytes.
virtual void emitNops (int64_t NumBytes, int64_t ControlledNopLength, SMLoc Loc, const MCSubtargetInfo &STI)
void emitZeros (uint64_t NumBytes)
Emit NumBytes worth of zeros.
virtual void emitValueToAlignment (Align Alignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0)
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
virtual void emitCodeAlignment (Align Alignment, const MCSubtargetInfo *STI, unsigned MaxBytesToEmit=0)
Emit nops until the byte alignment ByteAlignment is reached.
virtual void emitValueToOffset (const MCExpr *Offset, unsigned char Value, SMLoc Loc)
Emit some number of copies of Value until the byte offset Offset is reached.
Protected Member Functions
MCStreamer (MCContext &Ctx)
virtual void emitCFIStartProcImpl (MCDwarfFrameInfo &Frame)
virtual void emitCFIEndProcImpl (MCDwarfFrameInfo &CurFrame)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void emitWindowsUnwindTables (WinEH::FrameInfo *Frame)
virtual void emitWindowsUnwindTables ()
virtual void emitRawTextImpl (StringRef String)
EmitRawText - If this file is backed by an assembly streamer, this dumps the specified string in the output .s file.
bool checkCVLocSection (unsigned FuncId, unsigned FileNo, SMLoc Loc)
Returns true if the the .cv_loc directive is in the right section.
Detailed Description
Streaming machine code generation interface.
This interface is intended to provide a programmatic interface that is very similar to the level that an assembler .s file provides. It has callbacks to emit bytes, handle directives, etc. The implementation of this interface retains state to know what the current section is etc.
There are multiple implementations of this interface: one for writing out a .s file, and implementations that write out .o files of various formats.
Definition at line 212 of file MCStreamer.h.
Constructor & Destructor Documentation
MCStreamer() [1/2]
MCStreamer::MCStreamer (MCContext & Ctx) protected
Definition at line 94 of file MCStreamer.cpp.
MCStreamer() [2/2]
llvm::MCStreamer::MCStreamer (const MCStreamer &) delete
~MCStreamer()
MCStreamer::~MCStreamer () virtual default
Member Function Documentation
addBlankLine()
virtual void llvm::MCStreamer::addBlankLine () inline virtual
Emit a blank line to a .s file to pretty it up.
Definition at line 380 of file MCStreamer.h.
Referenced by llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), and emitNonLazyStubs().
AddComment()
virtual void llvm::MCStreamer::AddComment (const Twine & T, bool EOL = true) inline virtual
Add a textual comment.
Typically for comments that can be emitted to the generated .s file if applicable as a QoI issue to make the output of the compiler more readable. This only affects the MCAsmStreamer, and only when verbose assembly output is enabled.
If the comment includes embedded
's, they will each get the comment prefix as appropriate. The added comment should not end with a
. By default, each comment is terminated with an end of line, i.e. the EOL param is set to true by default. If one prefers not to end the comment with a new line then the EOL param should be passed with a false value.
Definition at line 359 of file MCStreamer.h.
Referenced by addConstantComments(), emitDwarfUnitLength(), emitGenDwarfRanges(), and maybeEmitDwarf64Mark().
addExplicitComment()
void MCStreamer::addExplicitComment (const Twine & T) virtual
Add explicit comment T.
T is required to be a valid comment in the output and does not need to be escaped.
Definition at line 123 of file MCStreamer.cpp.
assignFragment()
void MCStreamer::assignFragment (MCSymbol * Symbol, MCFragment * Fragment)
Sets the symbol's section.
Each emitted symbol will be tracked in the ordering table, so we can sort on them later.
Definition at line 414 of file MCStreamer.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), and llvm::ARMBuildAttrs::Symbol.
beginCOFFSymbolDef()
void MCStreamer::beginCOFFSymbolDef (const MCSymbol * Symbol) virtual
Start emitting COFF symbol definition.
Parameters
Symbol - The symbol to have its External & Type fields set.
Reimplemented in llvm::MCWinCOFFStreamer, and llvm::RecordStreamer.
Definition at line 1158 of file MCStreamer.cpp.
References llvm_unreachable.
changeSection()
void MCStreamer::changeSection (MCSection * , const MCExpr *) virtual
Update streamer for a new active section.
This is called by popSection and switchSection, if the current section changes.
Reimplemented in llvm::MCObjectStreamer, llvm::MCELFStreamer, and llvm::MCWasmStreamer.
Definition at line 1213 of file MCStreamer.cpp.
Referenced by popSection(), and switchSection().
checkCVLocSection()
bool MCStreamer::checkCVLocSection (unsigned FuncId, unsigned FileNo, SMLoc Loc) protected
Returns true if the the .cv_loc directive is in the right section.
Definition at line 324 of file MCStreamer.cpp.
References FuncId, getContext(), getCurrentSectionOnly(), llvm::MCContext::getCVContext(), llvm::CodeViewContext::getCVFunctionInfo(), llvm::MCContext::reportError(), and llvm::MCCVFunctionInfo::Section.
Referenced by llvm::MCObjectStreamer::emitCVLocDirective().
doFinalizationAtSectionEnd()
virtual void llvm::MCStreamer::doFinalizationAtSectionEnd (MCSection * Section) inline virtual
Do finalization for the streamer at the end of a section.
Definition at line 1160 of file MCStreamer.h.
emitAbsoluteSymbolDiff()
void MCStreamer::emitAbsoluteSymbolDiff (const MCSymbol * Hi, const MCSymbol * Lo, unsigned Size) virtual
Emit the absolute difference between two symbols.
Precondition
Offset of Hi is greater than the offset Lo.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1126 of file MCStreamer.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCAsmInfo::doesSetDirectiveSuppressReloc(), emitAssignment(), emitSymbolValue(), emitValue(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, and Size.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), and emitDwarfUnitLength().
emitAbsoluteSymbolDiffAsULEB128()
void MCStreamer::emitAbsoluteSymbolDiffAsULEB128 (const MCSymbol * Hi, const MCSymbol * Lo) virtual
Emit the absolute difference between two symbols encoded with ULEB128.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1145 of file MCStreamer.cpp.
References Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), emitULEB128Value(), llvm::MipsISD::Hi, and llvm::MipsISD::Lo.
Referenced by llvm::MCObjectStreamer::emitAbsoluteSymbolDiffAsULEB128().
emitAddrsig()
virtual void llvm::MCStreamer::emitAddrsig () inline virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1095 of file MCStreamer.h.
emitAddrsigSym()
virtual void llvm::MCStreamer::emitAddrsigSym (const MCSymbol * Sym) inline virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1096 of file MCStreamer.h.
emitAssemblerFlag()
void MCStreamer::emitAssemblerFlag (MCAssemblerFlag Flag) virtual
Note in the output the specified Flag.
Reimplemented in llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1155 of file MCStreamer.cpp.
emitAssignment()
void MCStreamer::emitAssignment (MCSymbol * Symbol, const MCExpr * Value) virtual
Emit an assignment of Value to Symbol.
This corresponds to an assembler statement such as: symbol = value
The assignment generates no code, but has the side effect of binding the value in the current context. For the assembly streamer, this prints the binding into the .s file.
Parameters
Symbol - The symbol being assigned to.
Value - The value for the symbol.
Reimplemented in llvm::MCObjectStreamer, and llvm::RecordStreamer.
Definition at line 1054 of file MCStreamer.cpp.
References llvm::MCTargetStreamer::emitAssignment(), getTargetStreamer(), llvm::ARMBuildAttrs::Symbol, and visitUsedExpr().
Referenced by emitAbsoluteSymbolDiff(), llvm::RecordStreamer::emitAssignment(), llvm::MCObjectStreamer::emitAssignment(), llvm::RecordStreamer::flushSymverDirectives(), and llvm::MCContext::setSymbolValue().
emitBinaryData()
void MCStreamer::emitBinaryData (StringRef Data) virtual
Functionally identical to EmitBytes.
When emitting textual assembly, this method uses .byte directives instead of .ascii or .asciz for readability.
Definition at line 1216 of file MCStreamer.cpp.
References llvm::Data, and emitBytes().
Referenced by llvm::AsmPrinter::XRayFunctionEntry::emit(), emitOneV5FileEntry(), and llvm::MCDwarfLineStr::emitSection().
emitBuildVersion()
virtual void llvm::MCStreamer::emitBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion) inline virtual
Emit/Specify Mach-O build version command.
Platform should be one of MachO::PlatformType.
Definition at line 512 of file MCStreamer.h.
Referenced by emitVersionForTarget().
emitBundleAlignMode()
void MCStreamer::emitBundleAlignMode (Align Alignment) virtual
Set the bundle alignment mode from now on in the section.
The value 1 means turn the bundle alignment off.
Reimplemented in llvm::MCObjectStreamer, and llvm::MCELFStreamer.
Definition at line 1232 of file MCStreamer.cpp.
emitBundleLock()
void MCStreamer::emitBundleLock (bool AlignToEnd) virtual
The following instructions are a bundle-locked group.
Parameters
AlignToEnd - If true, the bundle-locked group will be aligned to the end of a bundle.
Reimplemented in llvm::MCObjectStreamer, and llvm::MCELFStreamer.
Definition at line 1233 of file MCStreamer.cpp.
emitBundleUnlock()
void MCStreamer::emitBundleUnlock () virtual
Ends a bundle-locked group.
Reimplemented in llvm::MCObjectStreamer, and llvm::MCELFStreamer.
Definition at line 1235 of file MCStreamer.cpp.
emitBytes()
void MCStreamer::emitBytes (StringRef Data) virtual
Emit the bytes in Data into the output.
This is used to implement assembler directives such as .byte, .ascii, etc.
Reimplemented in llvm::MCObjectStreamer, and llvm::CSKYELFStreamer.
Definition at line 1215 of file MCStreamer.cpp.
Referenced by llvm::MCDwarfLineAddr::Emit(), emitBinaryData(), llvm::DwarfStreamer::emitCIE(), llvm::DwarfStreamer::emitFDE(), llvm::AArch64TargetStreamer::emitInst(), llvm::ARMTargetStreamer::emitInst(), emitIntValue(), llvm::DwarfStreamer::emitLineTableForUnit(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::AArch64TargetStreamer::emitNoteSection(), emitOneV5FileEntry(), llvm::DwarfStreamer::emitSectionContents(), emitSLEB128IntValue(), llvm::DwarfStreamer::emitSwiftAST(), llvm::DwarfStreamer::emitSwiftReflectionSection(), emitULEB128IntValue(), llvm::DWPStringPool::getOffset(), and llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer().
emitCFIAdjustCfaOffset()
void MCStreamer::emitCFIAdjustCfaOffset (int64_t Adjustment) virtual
Definition at line 516 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createAdjustCfaOffset(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCFIBKeyFrame()
void MCStreamer::emitCFIBKeyFrame () virtual
Definition at line 248 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::IsBKeyFrame.
emitCFIDefCfa()
void MCStreamer::emitCFIDefCfa (int64_t Register, int64_t Offset) virtual
Definition at line 495 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::cfiDefCfa(), llvm::MCDwarfFrameInfo::CurrentCfaRegister, emitCFILabel(), llvm::MCDwarfFrameInfo::Instructions, llvm::Offset, and Register.
emitCFIDefCfaOffset()
void MCStreamer::emitCFIDefCfaOffset (int64_t Offset) virtual
Definition at line 506 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::cfiDefCfaOffset(), emitCFILabel(), llvm::MCDwarfFrameInfo::Instructions, and llvm::Offset.
emitCFIDefCfaRegister()
void MCStreamer::emitCFIDefCfaRegister (int64_t Register) virtual
Definition at line 526 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCDwarfFrameInfo::CurrentCfaRegister, emitCFILabel(), llvm::MCDwarfFrameInfo::Instructions, and Register.
emitCFIEndProc()
void MCStreamer::emitCFIEndProc ()
Definition at line 475 of file MCStreamer.cpp.
References emitCFIEndProcImpl().
emitCFIEndProcImpl()
void MCStreamer::emitCFIEndProcImpl (MCDwarfFrameInfo & CurFrame) protected virtual
Reimplemented in llvm::MipsELFStreamer.
Definition at line 483 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::End.
Referenced by emitCFIEndProc().
emitCFIEscape()
void MCStreamer::emitCFIEscape (StringRef Values) virtual
Definition at line 625 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createEscape(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCFIGnuArgsSize()
void MCStreamer::emitCFIGnuArgsSize (int64_t Size) virtual
Definition at line 634 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createGnuArgsSize(), emitCFILabel(), llvm::MCDwarfFrameInfo::Instructions, and Size.
emitCFILabel()
MCSymbol * MCStreamer::emitCFILabel () virtual
When emitting an object file, create and emit a real label.
When emitting textual assembly, this should do nothing to avoid polluting our output.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 489 of file MCStreamer.cpp.
Referenced by emitCFIAdjustCfaOffset(), emitCFIDefCfa(), emitCFIDefCfaOffset(), emitCFIDefCfaRegister(), emitCFIEscape(), emitCFIGnuArgsSize(), emitCFILLVMDefAspaceCfa(), emitCFINegateRAState(), emitCFIOffset(), emitCFIRegister(), emitCFIRelOffset(), emitCFIRememberState(), emitCFIRestore(), emitCFIRestoreState(), emitCFISameValue(), emitCFIUndefined(), emitCFIWindowSave(), llvm::Win64EH::ARMUnwindEmitter::EmitUnwindInfo(), llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo(), emitWinCFIAllocStack(), emitWinCFIEndChained(), emitWinCFIEndProc(), emitWinCFIEndProlog(), emitWinCFIFuncletOrFuncEnd(), emitWinCFIPushFrame(), emitWinCFIPushReg(), emitWinCFISaveReg(), emitWinCFISaveXMM(), emitWinCFISetFrame(), emitWinCFIStartChained(), and emitWinCFIStartProc().
emitCFILLVMDefAspaceCfa()
void MCStreamer::emitCFILLVMDefAspaceCfa (int64_t Register, int64_t Offset, int64_t AddressSpace) virtual
Definition at line 537 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createLLVMDefAspaceCfa(), llvm::MCDwarfFrameInfo::CurrentCfaRegister, emitCFILabel(), llvm::MCDwarfFrameInfo::Instructions, llvm::Offset, and Register.
emitCFILsda()
void MCStreamer::emitCFILsda (const MCSymbol * Sym, unsigned Encoding) virtual
Definition at line 578 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::Lsda, and llvm::MCDwarfFrameInfo::LsdaEncoding.
emitCFIMTETaggedFrame()
void MCStreamer::emitCFIMTETaggedFrame () virtual
Definition at line 255 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::IsMTETaggedFrame.
emitCFINegateRAState()
void MCStreamer::emitCFINegateRAState () virtual
Definition at line 681 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createNegateRAState(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCFIOffset()
void MCStreamer::emitCFIOffset (int64_t Register, int64_t Offset) virtual
Definition at line 549 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createOffset(), emitCFILabel(), llvm::MCDwarfFrameInfo::Instructions, and llvm::Offset.
emitCFIPersonality()
void MCStreamer::emitCFIPersonality (const MCSymbol * Sym, unsigned Encoding) virtual
Definition at line 569 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::Personality, and llvm::MCDwarfFrameInfo::PersonalityEncoding.
emitCFIRegister()
void MCStreamer::emitCFIRegister (int64_t Register1, int64_t Register2) virtual
Definition at line 661 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRegister(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCFIRelOffset()
void MCStreamer::emitCFIRelOffset (int64_t Register, int64_t Offset) virtual
Definition at line 559 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRelOffset(), emitCFILabel(), llvm::MCDwarfFrameInfo::Instructions, and llvm::Offset.
emitCFIRememberState()
void MCStreamer::emitCFIRememberState () virtual
Definition at line 586 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRememberState(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCFIRestore()
void MCStreamer::emitCFIRestore (int64_t Register) virtual
Definition at line 615 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRestore(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCFIRestoreState()
void MCStreamer::emitCFIRestoreState () virtual
Definition at line 595 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createRestoreState(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCFIReturnColumn()
void MCStreamer::emitCFIReturnColumn (int64_t Register) virtual
Definition at line 690 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::RAReg, and Register.
emitCFISameValue()
void MCStreamer::emitCFISameValue (int64_t Register) virtual
Definition at line 605 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createSameValue(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCFISections()
void MCStreamer::emitCFISections (bool EH, bool Debug) virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 445 of file MCStreamer.cpp.
Referenced by llvm::MCObjectStreamer::emitCFISections().
emitCFISignalFrame()
void MCStreamer::emitCFISignalFrame () virtual
Definition at line 644 of file MCStreamer.cpp.
References llvm::MCDwarfFrameInfo::IsSignalFrame.
emitCFIStartProc()
void MCStreamer::emitCFIStartProc (bool IsSimple, SMLoc Loc = SMLoc())
Definition at line 447 of file MCStreamer.cpp.
References Context, llvm::MCDwarfFrameInfo::CurrentCfaRegister, emitCFIStartProcImpl(), getContext(), getCurrentSectionOnly(), llvm::MCAsmInfo::getInitialFrameState(), llvm::MCDwarfFrameInfo::IsSimple, llvm::MCCFIInstruction::OpDefCfa, llvm::MCCFIInstruction::OpDefCfaRegister, llvm::MCCFIInstruction::OpLLVMDefAspaceCfa, and llvm::MCContext::reportError().
emitCFIStartProcImpl()
void MCStreamer::emitCFIStartProcImpl (MCDwarfFrameInfo & Frame) protected virtual
Reimplemented in llvm::MipsELFStreamer.
Definition at line 472 of file MCStreamer.cpp.
Referenced by emitCFIStartProc().
emitCFIUndefined()
void MCStreamer::emitCFIUndefined (int64_t Register) virtual
Definition at line 651 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createUndefined(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCFIWindowSave()
void MCStreamer::emitCFIWindowSave () virtual
Definition at line 671 of file MCStreamer.cpp.
References llvm::MCCFIInstruction::createWindowSave(), emitCFILabel(), and llvm::MCDwarfFrameInfo::Instructions.
emitCGProfileEntry()
void MCStreamer::emitCGProfileEntry (const MCSymbolRefExpr * From, const MCSymbolRefExpr * To, uint64_t Count) virtual
Reimplemented in llvm::MCELFStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 811 of file MCStreamer.cpp.
Referenced by llvm::TargetLoweringObjectFile::emitCGProfileMetadata(), and llvm::MCAsmParserExtension::ParseDirectiveCGProfile().
emitCodeAlignment()
void MCStreamer::emitCodeAlignment (Align Alignment, const MCSubtargetInfo * STI, unsigned MaxBytesToEmit = 0) virtual
Emit nops until the byte alignment ByteAlignment is reached.
This used to align code where the alignment bytes may be executed. This can emit different bytes for different sizes to optimize execution.
Parameters
Alignment - The alignment to reach.
STI - The MCSubtargetInfo in operation when padding is emitted.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1228 of file MCStreamer.cpp.
Referenced by smallData().
emitCOFFImgRel32()
void MCStreamer::emitCOFFImgRel32 (MCSymbol const * Symbol, int64_t Offset) virtual
Emits a COFF image relative relocation.
Parameters
Symbol - Symbol the image relative relocation should point to.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 982 of file MCStreamer.cpp.
emitCOFFSafeSEH()
void MCStreamer::emitCOFFSafeSEH (MCSymbol const * Symbol) virtual
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 974 of file MCStreamer.cpp.
emitCOFFSecRel32()
void MCStreamer::emitCOFFSecRel32 (MCSymbol const * Symbol, uint64_t Offset) virtual
Emits a COFF section relative relocation.
Parameters
Symbol - Symbol the section relative relocation should point to.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 980 of file MCStreamer.cpp.
Referenced by emitSymbolValue().
emitCOFFSectionIndex()
void MCStreamer::emitCOFFSectionIndex (MCSymbol const * Symbol) virtual
Emits a COFF section index.
Parameters
Symbol - Symbol the section number relocation should point to.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 978 of file MCStreamer.cpp.
emitCOFFSymbolIndex()
void MCStreamer::emitCOFFSymbolIndex (MCSymbol const * Symbol) virtual
Emits the symbol table index of a Symbol into the current section.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 976 of file MCStreamer.cpp.
emitCOFFSymbolStorageClass()
void MCStreamer::emitCOFFSymbolStorageClass (int StorageClass) virtual
Emit the storage class of the symbol.
Parameters
StorageClass - The storage class the symbol should have.
Reimplemented in llvm::RecordStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1168 of file MCStreamer.cpp.
References llvm_unreachable.
emitCOFFSymbolType()
void MCStreamer::emitCOFFSymbolType (int Type) virtual
Emit the type of the symbol.
Parameters
Type - A COFF type identifier (see COFF::SymbolType in X86COFF.h)
Reimplemented in llvm::RecordStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1171 of file MCStreamer.cpp.
References llvm_unreachable.
emitCommonSymbol()
virtual void llvm::MCStreamer::emitCommonSymbol (MCSymbol * Symbol, uint64_t Size, Align ByteAlignment) pure virtual
Emit a common symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the symbol.
Implemented in llvm::MCELFStreamer, llvm::MCWinCOFFStreamer, llvm::RecordStreamer, llvm::MCWasmStreamer, llvm::MCSPIRVStreamer, llvm::MCXCOFFStreamer, and llvm::MCDXContainerStreamer.
emitConditionalAssignment()
void MCStreamer::emitConditionalAssignment (MCSymbol * Symbol, const MCExpr * Value) virtual
Emit an assignment of Value to Symbol, but only if Value is also emitted.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 442 of file MCStreamer.cpp.
emitCVDefRangeDirective() [1/5]
void MCStreamer::emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeFramePointerRelHeader DRHdr) virtual
Definition at line 397 of file MCStreamer.cpp.
References copyBytesForDefRange(), and emitCVDefRangeDirective().
emitCVDefRangeDirective() [2/5]
void MCStreamer::emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeRegisterHeader DRHdr) virtual
Definition at line 389 of file MCStreamer.cpp.
References copyBytesForDefRange(), and emitCVDefRangeDirective().
emitCVDefRangeDirective() [3/5]
void MCStreamer::emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeRegisterRelHeader DRHdr) virtual
Definition at line 372 of file MCStreamer.cpp.
References copyBytesForDefRange(), and emitCVDefRangeDirective().
emitCVDefRangeDirective() [4/5]
void MCStreamer::emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, codeview::DefRangeSubfieldRegisterHeader DRHdr) virtual
Definition at line 380 of file MCStreamer.cpp.
References copyBytesForDefRange(), and emitCVDefRangeDirective().
emitCVDefRangeDirective() [5/5]
void MCStreamer::emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * >> Ranges, StringRef FixedSizePortion) virtual
This implements the CodeView '.cv_def_range' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 368 of file MCStreamer.cpp.
Referenced by llvm::MCObjectStreamer::emitCVDefRangeDirective(), and emitCVDefRangeDirective().
emitCVFileChecksumOffsetDirective()
virtual void llvm::MCStreamer::emitCVFileChecksumOffsetDirective (unsigned FileNo) inline virtual
This implements the CodeView '.cv_filechecksumoffset' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1009 of file MCStreamer.h.
emitCVFileChecksumsDirective()
virtual void llvm::MCStreamer::emitCVFileChecksumsDirective () inline virtual
This implements the CodeView '.cv_filechecksums' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1005 of file MCStreamer.h.
emitCVFileDirective()
bool MCStreamer::emitCVFileDirective (unsigned FileNo, StringRef Filename, ArrayRef< uint8_t > Checksum, unsigned ChecksumKind) virtual
Associate a filename with a specified logical file number, and also specify that file's checksum information.
This implements the '.cv_file 4 "foo.c"' assembler directive. Returns true on success.
Definition at line 294 of file MCStreamer.cpp.
References llvm::CodeViewContext::addFile(), llvm::lltok::ChecksumKind, getContext(), and llvm::MCContext::getCVContext().
emitCVFPOData()
virtual void llvm::MCStreamer::emitCVFPOData (const MCSymbol * ProcSym, SMLoc Loc = {}) inline virtual
This implements the CodeView '.cv_fpo_data' assembler directive.
Definition at line 1012 of file MCStreamer.h.
emitCVFuncIdDirective()
bool MCStreamer::emitCVFuncIdDirective (unsigned FunctionId) virtual
Introduces a function id for use with .cv_loc.
Definition at line 301 of file MCStreamer.cpp.
References getContext(), llvm::MCContext::getCVContext(), and llvm::CodeViewContext::recordFunctionId().
Referenced by llvm::CodeViewDebug::beginFunctionImpl().
emitCVInlineLinetableDirective()
void MCStreamer::emitCVInlineLinetableDirective (unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol * FnStartSym, const MCSymbol * FnEndSym) virtual
This implements the CodeView '.cv_inline_linetable' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 350 of file MCStreamer.cpp.
Referenced by llvm::MCObjectStreamer::emitCVInlineLinetableDirective().
emitCVInlineSiteIdDirective()
bool MCStreamer::emitCVInlineSiteIdDirective (unsigned FunctionId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol, SMLoc Loc) virtual
Introduces an inline call site id for use with .cv_loc.
Includes extra information for inline line table generation.
Definition at line 305 of file MCStreamer.cpp.
References getContext(), llvm::MCContext::getCVContext(), llvm::CodeViewContext::recordInlinedCallSiteId(), and llvm::MCContext::reportError().
emitCVLinetableDirective()
void MCStreamer::emitCVLinetableDirective (unsigned FunctionId, const MCSymbol * FnStart, const MCSymbol * FnEnd) virtual
This implements the CodeView '.cv_linetable' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 346 of file MCStreamer.cpp.
emitCVLocDirective()
void MCStreamer::emitCVLocDirective (unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt, StringRef FileName, SMLoc Loc) virtual
This implements the CodeView '.cv_loc' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 319 of file MCStreamer.cpp.
emitCVStringTableDirective()
virtual void llvm::MCStreamer::emitCVStringTableDirective () inline virtual
This implements the CodeView '.cv_stringtable' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1002 of file MCStreamer.h.
emitDarwinTargetVariantBuildVersion()
virtual void llvm::MCStreamer::emitDarwinTargetVariantBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion) inline virtual
Definition at line 516 of file MCStreamer.h.
Referenced by emitVersionForTarget().
emitDataRegion()
virtual void llvm::MCStreamer::emitDataRegion (MCDataRegionType Kind) inline virtual
Note in the output the specified region Kind.
Definition at line 503 of file MCStreamer.h.
Referenced by llvm::ConstantPool::emitEntries().
emitDTPRel32Value()
void MCStreamer::emitDTPRel32Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a dtprel (32-bit DTP relative) value.
This is used to implement assembler directives such as .dtprelword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 199 of file MCStreamer.cpp.
References llvm::report_fatal_error().
emitDTPRel64Value()
void MCStreamer::emitDTPRel64Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a dtprel (64-bit DTP relative) value.
This is used to implement assembler directives such as .dtpreldword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 195 of file MCStreamer.cpp.
References llvm::report_fatal_error().
emitDwarfAdvanceLineAddr()
virtual void llvm::MCStreamer::emitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol * LastLabel, const MCSymbol * Label, unsigned PointerSize) inline virtual
If targets does not support representing debug line section by .loc/.file directives in assembly output, we need to populate debug line section with raw debug line contents.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1154 of file MCStreamer.h.
Referenced by llvm::MCDwarfLineTable::emitOne().
emitDwarfFile0Directive()
void MCStreamer::emitDwarfFile0Directive (StringRef Directory, StringRef Filename, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source, unsigned CUID = 0) virtual
Specify the "root" file of the compilation, using the ".file 0" extension.
Definition at line 239 of file MCStreamer.cpp.
References getContext(), llvm::MCContext::setMCLineTableRootFile(), and llvm::Sched::Source.
emitDwarfFileDirective()
unsigned llvm::MCStreamer::emitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, std::optional< MD5::MD5Result > Checksum = std::nullopt, std::optional< StringRef > Source = std::nullopt, unsigned CUID = 0) inline
Associate a filename with a specified logical file number.
This implements the DWARF2 '.file 4 "foo.c"' assembler directive.
Definition at line 909 of file MCStreamer.h.
References llvm::cantFail(), llvm::Sched::Source, and tryEmitDwarfFileDirective().
emitDwarfLineEndEntry()
virtual void llvm::MCStreamer::emitDwarfLineEndEntry (MCSection * Section, MCSymbol * LastLabel) inline virtual
Emit the debug line end entry.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1149 of file MCStreamer.h.
Referenced by llvm::MCDwarfLineTable::emitOne().
emitDwarfLineStartLabel()
void MCStreamer::emitDwarfLineStartLabel (MCSymbol * StartSym) virtual
Emit the debug line start label.
Definition at line 1049 of file MCStreamer.cpp.
References emitLabel().
Referenced by llvm::MCDwarfLineTableHeader::Emit().
emitDwarfLocDirective()
void MCStreamer::emitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) virtual
This implements the DWARF2 '.loc fileno lineno ...' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 262 of file MCStreamer.cpp.
References getContext(), and llvm::MCContext::setCurrentDwarfLoc().
Referenced by llvm::MCObjectStreamer::emitDwarfLocDirective().
emitDwarfUnitLength() [1/2]
MCSymbol * MCStreamer::emitDwarfUnitLength (const Twine & Prefix, const Twine & Comment) virtual
Emit a unit length field.
The actual format, DWARF32 or DWARF64, is chosen according to the settings. Return the end symbol generated inside, the caller needs to emit it.
Definition at line 1034 of file MCStreamer.cpp.
References AddComment(), Context, emitAbsoluteSymbolDiff(), emitLabel(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, maybeEmitDwarf64Mark(), and llvm::cl::Prefix.
emitDwarfUnitLength() [2/2]
void MCStreamer::emitDwarfUnitLength (uint64_t Length, const Twine & Comment) virtual
Emit a unit length field.
The actual format, DWARF32 or DWARF64, is chosen according to the settings.
Definition at line 1026 of file MCStreamer.cpp.
References AddComment(), assert(), Context, llvm::dwarf::DW_LENGTH_lo_reserved, llvm::dwarf::DWARF64, emitIntValue(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::Length, and maybeEmitDwarf64Mark().
Referenced by llvm::MCDwarfLineTableHeader::Emit().
emitEHSymAttributes()
void MCStreamer::emitEHSymAttributes (const MCSymbol * Symbol, MCSymbol * EHSymbol) virtual
Definition at line 406 of file MCStreamer.cpp.
emitELFSize()
void MCStreamer::emitELFSize (MCSymbol * Symbol, const MCExpr * Value) virtual
Emit an ELF .size directive.
This corresponds to an assembler statement such as: .size symbol, expression
Reimplemented in llvm::MCELFStreamer, and llvm::MCWasmStreamer.
Definition at line 1206 of file MCStreamer.cpp.
Referenced by llvm::TargetLoweringObjectFileELF::emitPersonalityValue().
emitELFSymverDirective()
void MCStreamer::emitELFSymverDirective (const MCSymbol * OriginalSym, StringRef Name, bool KeepOriginalSym) virtual
Emit an ELF .symver directive.
This corresponds to an assembler statement such as: .symver _start, foo@SOME_VERSION
Reimplemented in llvm::RecordStreamer, and llvm::MCELFStreamer.
Definition at line 1207 of file MCStreamer.cpp.
emitExplicitComments()
void MCStreamer::emitExplicitComments () virtual
Emit added explicit comments.
Definition at line 124 of file MCStreamer.cpp.
emitFileDirective() [1/2]
void MCStreamer::emitFileDirective (StringRef Filename) virtual
Switch to a new logical file.
This is used to implement the '.file "foo.c"' assembler directive.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1164 of file MCStreamer.cpp.
emitFileDirective() [2/2]
void MCStreamer::emitFileDirective (StringRef Filename, StringRef CompilerVerion, StringRef TimeStamp, StringRef Description) virtual
Emit ".file assembler diretive with additioal info.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1165 of file MCStreamer.cpp.
emitFill() [1/3]
void MCStreamer::emitFill (const MCExpr & NumBytes, uint64_t FillValue, SMLoc Loc = SMLoc()) virtual
Emit Size bytes worth of the value specified by FillValue.
This is used to implement assembler directives such as .space or .skip.
Parameters
NumBytes - The number of bytes to emit.
FillValue - The value to use when filling bytes.
Loc - The location of the expression for error reporting.
Reimplemented in llvm::MCObjectStreamer, and llvm::CSKYELFStreamer.
Definition at line 1222 of file MCStreamer.cpp.
emitFill() [2/3]
void MCStreamer::emitFill (const MCExpr & NumValues, int64_t Size, int64_t Expr, SMLoc Loc = SMLoc()) virtual
Emit NumValues copies of Size bytes.
Each Size bytes is taken from the lowest order 4 bytes of Expr expression.
This is used to implement assembler directives such as .fill.
Parameters
NumValues - The number of copies of Size bytes to emit.
Size - The size (in bytes) of each repeated value.
Expr - The expression from which Size bytes are used.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1223 of file MCStreamer.cpp.
emitFill() [3/3]
void MCStreamer::emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
This implements directives such as '.space'.
Definition at line 221 of file MCStreamer.cpp.
References llvm::MCConstantExpr::create(), and getContext().
Referenced by emitGenDwarfRanges(), and emitZeros().
emitGNUAttribute()
virtual void llvm::MCStreamer::emitGNUAttribute (unsigned Tag, unsigned Value) inline virtual
Emit a .gnu_attribute directive.
Reimplemented in llvm::MCELFStreamer.
Definition at line 668 of file MCStreamer.h.
emitGPRel32Value()
void MCStreamer::emitGPRel32Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
This is used to implement assembler directives such as .gprel32 on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 215 of file MCStreamer.cpp.
References llvm::report_fatal_error().
emitGPRel64Value()
void MCStreamer::emitGPRel64Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
This is used to implement assembler directives such as .gpdword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 211 of file MCStreamer.cpp.
References llvm::report_fatal_error().
emitIdent()
virtual void llvm::MCStreamer::emitIdent (StringRef IdentString) inline virtual
Emit the "identifiers" directive.
This implements the '.ident "version foo"' assembler directive.
Reimplemented in llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 905 of file MCStreamer.h.
emitInstruction()
void MCStreamer::emitInstruction (const MCInst & Inst, const MCSubtargetInfo & STI) virtual
Emit the given Instruction into the current section.
Reimplemented in llvm::MCObjectStreamer, llvm::CSKYELFStreamer, llvm::RecordStreamer, llvm::MipsELFStreamer, llvm::PPCELFStreamer, llvm::HexagonMCELFStreamer, and llvm::PPCXCOFFStreamer.
Definition at line 1099 of file MCStreamer.cpp.
References llvm::MCOperand::getExpr(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), i, llvm::MCOperand::isExpr(), and visitUsedExpr().
Referenced by EmitBinary(), emitBinary(), emitBSIC(), EmitCall(), llvm::SystemZTargetStreamer::emitConstantPools(), llvm::MipsTargetStreamer::emitII(), llvm::RecordStreamer::emitInstruction(), emitLEASLrri(), emitLEASLzzi(), emitLEAzii(), emitLEAzzi(), EmitNop(), llvm::MipsTargetStreamer::emitR(), llvm::MipsTargetStreamer::emitRRIII(), llvm::MipsTargetStreamer::emitRRRX(), llvm::MipsTargetStreamer::emitRRX(), llvm::MipsTargetStreamer::emitRX(), EmitSETHI(), and emitSIC().
emitInt16()
void llvm::MCStreamer::emitInt16 (uint64_t Value) inline
Definition at line 747 of file MCStreamer.h.
References emitIntValue().
Referenced by llvm::MCDwarfLineTableHeader::Emit(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), EmitUnwindCode(), and EmitUnwindInfo().
emitInt32()
void llvm::MCStreamer::emitInt32 (uint64_t Value) inline
Definition at line 748 of file MCStreamer.h.
References emitIntValue().
Referenced by ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfoForSegment(), ARMEmitRuntimeFunction(), ARMEmitUnwindInfo(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), EmitUnwindInfo(), maybeEmitDwarf64Mark(), and llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer().
emitInt64()
void llvm::MCStreamer::emitInt64 (uint64_t Value) inline
Definition at line 749 of file MCStreamer.h.
References emitIntValue().
Referenced by llvm::MCPseudoProbe::emit(), llvm::MCPseudoProbeInlineTree::emit(), and llvm::TargetLoweringObjectFileELF::emitModuleMetadata().
emitInt8()
void llvm::MCStreamer::emitInt8 (uint64_t Value) inline
Definition at line 746 of file MCStreamer.h.
References emitIntValue().
Referenced by ARM64EmitUnwindCode(), ARM64EmitUnwindInfoForSegment(), ARMEmitUnwindCode(), ARMEmitUnwindInfo(), llvm::MCPseudoProbe::emit(), llvm::MCDwarfLineTableHeader::Emit(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), emitEncodingByte(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::MCELFStreamer::emitIdent(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::MCDwarfLineTable::emitOne(), EmitUnwindCode(), EmitUnwindInfo(), and llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer().
emitIntValue() [1/2]
void MCStreamer::emitIntValue (APInt Value) virtual
Definition at line 144 of file MCStreamer.cpp.
References Context, emitBytes(), emitIntValue(), llvm::sys::IsLittleEndianHost, llvm::SmallVectorImpl< char >::resize(), Size, llvm::StoreIntToMemory(), and llvm::SmallString< InternalLen >::str().
emitIntValue() [2/2]
void MCStreamer::emitIntValue (uint64_t Value, unsigned Size) virtual
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
EmitIntValue - Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 134 of file MCStreamer.cpp.
References assert(), llvm::support::big, llvm::support::endian::byte_swap(), Context, emitBytes(), llvm::isIntN(), llvm::isUIntN(), llvm::support::little, Size, and uint64_t.
Referenced by llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), llvm::DwarfStreamer::emitDwarfDebugRangesTableFragment(), emitDwarfUnitLength(), llvm::DwarfStreamer::emitFDE(), llvm::MCObjectStreamer::emitFill(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), emitInt16(), emitInt32(), emitInt64(), emitInt8(), llvm::MipsELFStreamer::emitIntValue(), emitIntValue(), emitIntValueInHex(), emitIntValueInHexWithPadding(), llvm::DwarfStreamer::emitLineTableForUnit(), emitNonLazySymbolPointer(), llvm::AArch64TargetStreamer::emitNoteSection(), llvm::MCDwarfLineStr::emitRef(), llvm::MCObjectStreamer::emitValueImpl(), llvm::WebAssemblyTargetStreamer::emitValueType(), smallData(), llvm::writeIndex(), and llvm::writeIndexTable().
emitIntValueInHex()
virtual void llvm::MCStreamer::emitIntValueInHex (uint64_t Value, unsigned Size) inline virtual
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes.
Definition at line 742 of file MCStreamer.h.
References emitIntValue().
emitIntValueInHexWithPadding()
virtual void llvm::MCStreamer::emitIntValueInHexWithPadding (uint64_t Value, unsigned Size) inline virtual
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes, pads the field with leading zeros to Size width.
Definition at line 754 of file MCStreamer.h.
References emitIntValue().
emitLabel()
void MCStreamer::emitLabel (MCSymbol * Symbol, SMLoc Loc = SMLoc()) virtual
Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented in llvm::MCObjectStreamer, llvm::MCELFStreamer, llvm::RecordStreamer, llvm::MipsELFStreamer, llvm::MCWasmStreamer, llvm::MCWinCOFFStreamer, and llvm::PPCELFStreamer.
Definition at line 423 of file MCStreamer.cpp.
References assert(), llvm::MCTargetStreamer::emitLabel(), getContext(), getCurrentSectionOnly(), getTargetStreamer(), llvm::MCContext::reportError(), and llvm::ARMBuildAttrs::Symbol.
Referenced by ARM64EmitUnwindInfoForSegment(), ARMEmitUnwindInfo(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCDwarfDwoLineTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::SystemZTargetStreamer::emitConstantPools(), llvm::MCDwarfLineTable::emitCU(), emitDirectiveRelocJalr(), emitDwarfLineStartLabel(), emitDwarfUnitLength(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::RecordStreamer::emitLabel(), llvm::MCObjectStreamer::emitLabel(), llvm::MCObjectStreamer::emitLabelAtPos(), llvm::DwarfStreamer::emitLineTableForUnit(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), emitNonLazySymbolPointer(), EmitNop(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), emitPseudoProbe(), EmitUnwindInfo(), endSection(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::MCDwarfLineEntry::make(), llvm::MCGenDwarfLabelEntry::Make(), smallData(), and switchSection().
emitLinkerOptions()
virtual void llvm::MCStreamer::emitLinkerOptions (ArrayRef< std::string > Kind) inline virtual
Emit the given list Options of strings as linker options into the output.
Definition at line 500 of file MCStreamer.h.
Referenced by llvm::TargetLoweringObjectFileMachO::emitModuleMetadata().
emitLocalCommonSymbol()
void MCStreamer::emitLocalCommonSymbol (MCSymbol * Symbol, uint64_t Size, Align ByteAlignment) virtual
Emit a local common (.lcomm) symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the common symbol in bytes.
Reimplemented in llvm::MCELFStreamer, llvm::MCWinCOFFStreamer, and llvm::MCWasmStreamer.
Definition at line 1209 of file MCStreamer.cpp.
emitLOHDirective()
virtual void llvm::MCStreamer::emitLOHDirective (MCLOHType Kind, const MCLOHArgs & Args) inline virtual
Emit a Linker Optimization Hint (LOH) directive.
Parameters
Args - Arguments of the LOH.
Definition at line 665 of file MCStreamer.h.
emitNops()
void llvm::MCStreamer::emitNops (int64_t NumBytes, int64_t ControlledNopLength, llvm::SMLoc Loc, const MCSubtargetInfo & STI) virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 225 of file MCStreamer.cpp.
emitPseudoProbe()
void MCStreamer::emitPseudoProbe (uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attr, const MCPseudoProbeInlineStack & InlineStack, MCSymbol * FnSym) virtual
Emit the a pseudo probe into the current section.
Definition at line 1106 of file MCStreamer.cpp.
References Context, emitLabel(), and getContext().
emitRawComment()
void MCStreamer::emitRawComment (const Twine & T, bool TabPrefix = true) virtual
Print T and prefix it with the comment string (normally #) and optionally a tab.
This prints the comment immediately, not at the end of the current line. It is basically a safe version of EmitRawText: since it only prints comments, the object streamer ignores it instead of asserting.
Definition at line 121 of file MCStreamer.cpp.
emitRawText()
void MCStreamer::emitRawText (const Twine & String)
If this file is backed by a assembly streamer, this dumps the specified string in the output .s file.
This capability is indicated by the hasRawTextSupport() predicate. By default this aborts.
Definition at line 996 of file MCStreamer.cpp.
References emitRawTextImpl().
Referenced by llvm::NVPTXTargetStreamer::closeLastSection(), llvm::MCTargetStreamer::emitDwarfFileDirective(), llvm::MCTargetStreamer::emitRawBytes(), llvm::MCTargetStreamer::emitValue(), and llvm::NVPTXTargetStreamer::outputDwarfFileDirectives().
emitRawTextImpl()
void MCStreamer::emitRawTextImpl (StringRef String) protected virtual
EmitRawText - If this file is backed by an assembly streamer, this dumps the specified string in the output .s file.
This capability is indicated by the hasRawTextSupport() predicate.
Definition at line 987 of file MCStreamer.cpp.
References llvm::report_fatal_error().
Referenced by emitRawText().
emitRelocDirective()
virtual std::optional<std::pair<bool, std::string> > llvm::MCStreamer::emitRelocDirective (const MCExpr & Offset, StringRef Name, const MCExpr * Expr, SMLoc Loc, const MCSubtargetInfo & STI) inline virtual
Record a relocation described by the .reloc directive.
Return std::nullopt if succeeded. Otherwise, return a pair (Name is invalid, error message).
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1090 of file MCStreamer.h.
Referenced by emitDirectiveRelocJalr().
emitSLEB128IntValue()
unsigned MCStreamer::emitSLEB128IntValue (int64_t Value)
Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
EmitSLEB128IntValue - Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
Definition at line 172 of file MCStreamer.cpp.
References emitBytes(), llvm::encodeSLEB128(), and llvm::raw_svector_ostream::str().
Referenced by llvm::MCPseudoProbe::emit(), llvm::DwarfStreamer::emitLineTableForUnit(), and llvm::MCObjectStreamer::emitSLEB128Value().
emitSLEB128Value()
void MCStreamer::emitSLEB128Value (const MCExpr * Value) virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1221 of file MCStreamer.cpp.
emitSymbolAttribute()
virtual bool llvm::MCStreamer::emitSymbolAttribute (MCSymbol * Symbol, MCSymbolAttr Attribute) pure virtual
Add the given Attribute to Symbol.
Implemented in llvm::MCELFStreamer, llvm::RecordStreamer, llvm::MCWasmStreamer, llvm::MCWinCOFFStreamer, llvm::MCSPIRVStreamer, llvm::MCXCOFFStreamer, and llvm::MCDXContainerStreamer.
Referenced by emitNonLazySymbolPointer(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), and smallData().
emitSymbolDesc()
void MCStreamer::emitSymbolDesc (MCSymbol * Symbol, unsigned DescValue) virtual
Set the DescValue for the Symbol.
Parameters
Symbol - The symbol to have its n_desc field set.
DescValue - The value to set into the n_desc field.
Reimplemented in llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1157 of file MCStreamer.cpp.
emitSymbolValue()
void MCStreamer::emitSymbolValue (const MCSymbol * Sym, unsigned Size, bool IsSectionRelative = false)
Special case of EmitValue that avoids the client having to pass in a MCExpr for MCSymbols.
Definition at line 184 of file MCStreamer.cpp.
References assert(), llvm::MCSymbolRefExpr::create(), emitCOFFSecRel32(), emitValueImpl(), getContext(), and Size.
Referenced by emitAbsoluteSymbolDiff(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), and llvm::TargetLoweringObjectFileELF::emitPersonalityValue().
emitSyntaxDirective()
void MCStreamer::emitSyntaxDirective () virtual
Definition at line 861 of file MCStreamer.cpp.
emitTBSSSymbol()
void MCStreamer::emitTBSSSymbol (MCSection * Section, MCSymbol * Symbol, uint64_t Size, Align ByteAlignment = Align(1)) virtual
Emit a thread local bss (.tbss) symbol.
Parameters
Section - The thread local common section.
Symbol - The thread local common symbol to emit.
Size - The size of the symbol.
ByteAlignment - The alignment of the thread local common symbol.
Reimplemented in llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1211 of file MCStreamer.cpp.
emitThumbFunc()
void MCStreamer::emitThumbFunc (MCSymbol * Func) virtual
Note in the output that the specified Func is a Thumb mode function (ARM target only).
Reimplemented in llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1156 of file MCStreamer.cpp.
emitTPRel32Value()
void MCStreamer::emitTPRel32Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a tprel (32-bit TP relative) value.
This is used to implement assembler directives such as .tprelword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 207 of file MCStreamer.cpp.
References llvm::report_fatal_error().
emitTPRel64Value()
void MCStreamer::emitTPRel64Value (const MCExpr * Value) virtual
Emit the expression Value into the output as a tprel (64-bit TP relative) value.
This is used to implement assembler directives such as .tpreldword on targets that support them.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 203 of file MCStreamer.cpp.
References llvm::report_fatal_error().
emitULEB128IntValue()
unsigned MCStreamer::emitULEB128IntValue (uint64_t Value, unsigned PadTo = 0)
Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
EmitULEB128IntValue - Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
Definition at line 162 of file MCStreamer.cpp.
References emitBytes(), llvm::encodeULEB128(), and llvm::raw_svector_ostream::str().
Referenced by llvm::MCPseudoProbe::emit(), llvm::MCPseudoProbeInlineTree::emit(), EmitAbbrev(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiffAsULEB128(), EmitGenDwarfAbbrev(), EmitGenDwarfInfo(), llvm::DwarfStreamer::emitLineTableForUnit(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::MCDwarfLineTable::emitOne(), emitOneV5FileEntry(), and llvm::MCObjectStreamer::emitULEB128Value().
emitULEB128Value()
void MCStreamer::emitULEB128Value (const MCExpr * Value) virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1220 of file MCStreamer.cpp.
Referenced by emitAbsoluteSymbolDiffAsULEB128(), and emitGenDwarfRanges().
emitValue()
void MCStreamer::emitValue (const MCExpr * Value, unsigned Size, SMLoc Loc = SMLoc())
Definition at line 180 of file MCStreamer.cpp.
References emitValueImpl(), and Size.
Referenced by ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfoForSegment(), ARMEmitRuntimeFunction(), ARMEmitUnwindInfo(), EmitAbsDifference(), emitAbsoluteSymbolDiff(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), emitFDESymbol(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), emitNonLazySymbolPointer(), EmitPersonality(), llvm::MCDwarfLineStr::emitRef(), EmitRuntimeFunction(), EmitSymbolRefWithOfs(), EmitUnwindInfo(), llvm::AVRMCELFStreamer::emitValueForModiferKind(), and smallData().
emitValueImpl()
void MCStreamer::emitValueImpl (const MCExpr * Value, unsigned Size, SMLoc Loc = SMLoc()) virtual
Emit the expression Value into the output as a native integer of the given Size bytes.
This is used to implement assembler directives such as .word, .quad, etc.
Parameters
Value - The value to emit.
Size - The size of the integer (in bytes) to emit. This must match a native machine width.
Loc - The location of the expression for error reporting.
Reimplemented in llvm::MCObjectStreamer, llvm::MCELFStreamer, llvm::CSKYELFStreamer, llvm::MipsELFStreamer, and RISCVELFStreamer.
Definition at line 1217 of file MCStreamer.cpp.
References visitUsedExpr().
Referenced by emitSymbolValue(), emitValue(), RISCVELFStreamer::emitValueImpl(), and llvm::MCObjectStreamer::emitValueImpl().
emitValueToAlignment()
void MCStreamer::emitValueToAlignment (Align Alignment, int64_t Value = 0, unsigned ValueSize = 1, unsigned MaxBytesToEmit = 0) virtual
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
If the number of bytes need to emit for the alignment is not a multiple of ValueSize, then the contents of the emitted fill bytes is undefined.
This used to implement the .align assembler directive.
Parameters
Alignment - The alignment to reach.
Value - The value to use when filling bytes.
ValueSize - The size of the integer (in bytes) to emit for Value. This must match a native machine width.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented in llvm::MCELFStreamer, and llvm::MCObjectStreamer.
Definition at line 1225 of file MCStreamer.cpp.
Referenced by ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfoForSegment(), ARMEmitRuntimeFunction(), ARMEmitUnwindInfo(), llvm::AArch64TargetStreamer::emitNoteSection(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), EmitRuntimeFunction(), and EmitUnwindInfo().
emitValueToOffset()
void MCStreamer::emitValueToOffset (const MCExpr * Offset, unsigned char Value, SMLoc Loc) virtual
Emit some number of copies of Value until the byte offset Offset is reached.
This is used to implement assembler directives such as .org.
Parameters
Offset - The offset to reach. This may be an expression, but the expression must be associated with the current section.
Value - The value to use when filling bytes.
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1230 of file MCStreamer.cpp.
Referenced by llvm::MCParserUtils::parseAssignmentExpression().
emitVersionForTarget()
void MCStreamer::emitVersionForTarget (const Triple & Target, const VersionTuple & SDKVersion, const Triple * DarwinTargetVariantTriple, const VersionTuple & DarwinTargetVariantSDKVersion)
Definition at line 1341 of file MCStreamer.cpp.
References assert(), llvm::Triple::Darwin, llvm::Triple::DriverKit, emitBuildVersion(), emitDarwinTargetVariantBuildVersion(), emitVersionMin(), getMachoBuildVersionPlatformType(), getMachoBuildVersionSupportedOS(), getMachoVersionMinLoadCommandType(), llvm::Triple::IOS, llvm::Triple::isMacOSX(), llvm_unreachable, llvm::Triple::MacOSX, targetVersionOrMinimumSupportedOSVersion(), llvm::Triple::TvOS, llvm::IndexedInstrProf::Version, and llvm::Triple::WatchOS.
emitVersionMin()
virtual void llvm::MCStreamer::emitVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion) inline virtual
Specify the Mach-O minimum deployment target version.
Definition at line 506 of file MCStreamer.h.
Referenced by emitVersionForTarget().
emitWeakReference()
void MCStreamer::emitWeakReference (MCSymbol * Alias, const MCSymbol * Symbol) virtual
Emit an weak reference from Alias to Symbol.
This corresponds to an assembler statement such as: .weakref alias, symbol
Parameters
Alias - The alias that is being created.
Symbol - The symbol being aliased.
Reimplemented in llvm::MCObjectStreamer, llvm::MCWinCOFFStreamer, llvm::MCELFStreamer, and llvm::MCWasmStreamer.
Definition at line 1214 of file MCStreamer.cpp.
emitWinCFIAllocStack()
void MCStreamer::emitWinCFIAllocStack (unsigned Size, SMLoc Loc = SMLoc()) virtual
Definition at line 901 of file MCStreamer.cpp.
References llvm::Win64EH::Instruction::Alloc(), emitCFILabel(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, llvm::MCContext::reportError(), and Size.
emitWinCFIEndChained()
void MCStreamer::emitWinCFIEndChained (SMLoc Loc = SMLoc()) virtual
Definition at line 772 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, emitCFILabel(), llvm::WinEH::FrameInfo::End, EnsureValidWinFrameInfo(), getContext(), and llvm::MCContext::reportError().
emitWinCFIEndProc()
void MCStreamer::emitWinCFIEndProc (SMLoc Loc = SMLoc()) virtual
Definition at line 730 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, E, emitCFILabel(), emitWindowsUnwindTables(), llvm::WinEH::FrameInfo::End, EnsureValidWinFrameInfo(), llvm::WinEH::FrameInfo::FuncletOrFuncEnd, llvm::get(), getContext(), I, llvm::MCContext::reportError(), switchSection(), and llvm::WinEH::FrameInfo::TextSection.
emitWinCFIEndProlog()
void MCStreamer::emitWinCFIEndProlog (SMLoc Loc = SMLoc()) virtual
Definition at line 964 of file MCStreamer.cpp.
References emitCFILabel(), EnsureValidWinFrameInfo(), and llvm::WinEH::FrameInfo::PrologEnd.
emitWinCFIFuncletOrFuncEnd()
void MCStreamer::emitWinCFIFuncletOrFuncEnd (SMLoc Loc = SMLoc()) virtual
This is used on platforms, such as Windows on ARM64, that require function or funclet sizes to be emitted in .xdata before the End marker is emitted for the frame.
We cannot use the End marker, as it is not set at the point of emitting .xdata, in order to indicate that the frame is active.
Definition at line 748 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, emitCFILabel(), EnsureValidWinFrameInfo(), llvm::WinEH::FrameInfo::FuncletOrFuncEnd, getContext(), and llvm::MCContext::reportError().
emitWinCFIPushFrame()
void MCStreamer::emitWinCFIPushFrame (bool Code, SMLoc Loc = SMLoc()) virtual
Definition at line 950 of file MCStreamer.cpp.
References llvm::tgtok::Code, emitCFILabel(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, llvm::Win64EH::Instruction::PushMachFrame(), and llvm::MCContext::reportError().
emitWinCFIPushReg()
void MCStreamer::emitWinCFIPushReg (MCRegister Register, SMLoc Loc = SMLoc()) virtual
Definition at line 867 of file MCStreamer.cpp.
References Context, emitCFILabel(), encodeSEHRegNum(), EnsureValidWinFrameInfo(), llvm::WinEH::FrameInfo::Instructions, and llvm::Win64EH::Instruction::PushNonVol().
emitWinCFISaveReg()
void MCStreamer::emitWinCFISaveReg (MCRegister Register, unsigned Offset, SMLoc Loc = SMLoc()) virtual
Definition at line 918 of file MCStreamer.cpp.
References Context, emitCFILabel(), encodeSEHRegNum(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, llvm::Offset, llvm::MCContext::reportError(), and llvm::Win64EH::Instruction::SaveNonVol().
emitWinCFISaveXMM()
void MCStreamer::emitWinCFISaveXMM (MCRegister Register, unsigned Offset, SMLoc Loc = SMLoc()) virtual
Definition at line 935 of file MCStreamer.cpp.
References Context, emitCFILabel(), encodeSEHRegNum(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, llvm::Offset, llvm::MCContext::reportError(), and llvm::Win64EH::Instruction::SaveXMM().
emitWinCFISetFrame()
void MCStreamer::emitWinCFISetFrame (MCRegister Register, unsigned Offset, SMLoc Loc = SMLoc()) virtual
Definition at line 879 of file MCStreamer.cpp.
References emitCFILabel(), encodeSEHRegNum(), EnsureValidWinFrameInfo(), getContext(), llvm::WinEH::FrameInfo::Instructions, llvm::WinEH::FrameInfo::LastFrameInst, llvm::Offset, llvm::MCContext::reportError(), and llvm::Win64EH::Instruction::SetFPReg().
emitWinCFIStartChained()
void MCStreamer::emitWinCFIStartChained (SMLoc Loc = SMLoc()) virtual
Definition at line 759 of file MCStreamer.cpp.
References emitCFILabel(), EnsureValidWinFrameInfo(), llvm::WinEH::FrameInfo::Function, getCurrentSectionOnly(), and llvm::WinEH::FrameInfo::TextSection.
emitWinCFIStartProc()
void MCStreamer::emitWinCFIStartProc (const MCSymbol * Symbol, SMLoc Loc = SMLoc()) virtual
Definition at line 712 of file MCStreamer.cpp.
References Context, emitCFILabel(), llvm::WinEH::FrameInfo::End, getContext(), getCurrentSectionOnly(), llvm::MCContext::reportError(), llvm::ARMBuildAttrs::Symbol, llvm::WinEH::FrameInfo::TextSection, and llvm::MCAsmInfo::usesWindowsCFI().
emitWindowsUnwindTables() [1/2]
void MCStreamer::emitWindowsUnwindTables () protected virtual
Definition at line 1001 of file MCStreamer.cpp.
Referenced by emitWinCFIEndProc().
emitWindowsUnwindTables() [2/2]
void MCStreamer::emitWindowsUnwindTables (WinEH::FrameInfo * Frame) protected virtual
Definition at line 1003 of file MCStreamer.cpp.
emitWinEHHandler()
void MCStreamer::emitWinEHHandler (const MCSymbol * Sym, bool Unwind, bool Except, SMLoc Loc = SMLoc()) virtual
Definition at line 786 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, EnsureValidWinFrameInfo(), llvm::WinEH::FrameInfo::ExceptionHandler, getContext(), llvm::WinEH::FrameInfo::HandlesExceptions, llvm::WinEH::FrameInfo::HandlesUnwind, and llvm::MCContext::reportError().
emitWinEHHandlerData()
void MCStreamer::emitWinEHHandlerData (SMLoc Loc = SMLoc()) virtual
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 803 of file MCStreamer.cpp.
References llvm::WinEH::FrameInfo::ChainedParent, EnsureValidWinFrameInfo(), getContext(), and llvm::MCContext::reportError().
emitXCOFFExceptDirective()
void MCStreamer::emitXCOFFExceptDirective (const MCSymbol * Symbol, const MCSymbol * Trap, unsigned Lang, unsigned Reason, unsigned FunctionSize, bool hasDebug) virtual
Emit an XCOFF .except directive which adds information about a trap instruction to the object file exception section.
Parameters
Symbol - The function containing the trap.
Lang - The language code for the exception entry.
Reason - The reason code for the exception entry.
Reimplemented in llvm::MCXCOFFStreamer.
Definition at line 1197 of file MCStreamer.cpp.
References llvm::report_fatal_error().
emitXCOFFLocalCommonSymbol()
void MCStreamer::emitXCOFFLocalCommonSymbol (MCSymbol * LabelSym, uint64_t Size, MCSymbol * CsectSym, Align Alignment) virtual
Emits an lcomm directive with XCOFF csect information.
Parameters
LabelSym - Label on the block of storage.
Size - The size of the block of storage.
CsectSym - Csect name for the block of storage.
Alignment - The alignment of the symbol in bytes.
Reimplemented in llvm::MCXCOFFStreamer.
Definition at line 1174 of file MCStreamer.cpp.
References llvm_unreachable.
emitXCOFFRefDirective()
void MCStreamer::emitXCOFFRefDirective (StringRef Sym) virtual
Emit a XCOFF .ref directive which creates R_REF type entry in the relocation table for one or more symbols.
Parameters
Sym - The symbol on the .ref directive.
Reimplemented in llvm::MCXCOFFStreamer.
Definition at line 1193 of file MCStreamer.cpp.
References llvm_unreachable.
emitXCOFFRenameDirective()
void MCStreamer::emitXCOFFRenameDirective (const MCSymbol * Name, StringRef Rename) virtual
Emit a XCOFF .rename directive which creates a synonym for an illegal or undesirable name.
Parameters
Name - The name used internally in the assembly for references to the symbol.
Rename - The value to which the Name parameter is changed at the end of assembly.
Reimplemented in llvm::MCXCOFFStreamer.
Definition at line 1187 of file MCStreamer.cpp.
References llvm_unreachable.
emitXCOFFSymbolLinkageWithVisibility()
void MCStreamer::emitXCOFFSymbolLinkageWithVisibility (MCSymbol * Symbol, MCSymbolAttr Linkage, MCSymbolAttr Visibility) virtual
Emit a symbol's linkage and visibility with a linkage directive for XCOFF.
Parameters
Symbol - The symbol to emit.
Linkage - The linkage of the symbol to emit.
Visibility - The visibility of the symbol to emit or MCSA_Invalid if the symbol does not have an explicit visibility.
Reimplemented in llvm::MCXCOFFStreamer.
Definition at line 1180 of file MCStreamer.cpp.
References llvm_unreachable.
emitZerofill()
virtual void llvm::MCStreamer::emitZerofill (MCSection * Section, MCSymbol * Symbol = nullptr, uint64_t Size = 0, Align ByteAlignment = Align(1), SMLoc Loc = SMLoc()) pure virtual
Emit the zerofill section and an optional symbol.
Parameters
Section - The zerofill section to create and or to put the symbol
Symbol - The zerofill symbol to emit, if non-NULL.
Size - The size of the zerofill symbol.
ByteAlignment - The alignment of the zerofill symbol.
Implemented in llvm::MCWasmStreamer, llvm::MCSPIRVStreamer, llvm::MCXCOFFStreamer, llvm::MCELFStreamer, llvm::MCWinCOFFStreamer, llvm::RecordStreamer, and llvm::MCDXContainerStreamer.
emitZeros()
void MCStreamer::emitZeros (uint64_t NumBytes)
Emit NumBytes worth of zeros.
The implementation in this class just redirects to emitFill.
This function properly handles data in virtual sections.
Definition at line 229 of file MCStreamer.cpp.
References emitFill().
Referenced by llvm::AsmPrinter::XRayFunctionEntry::emit(), llvm::MCXCOFFStreamer::emitCommonSymbol(), llvm::MCELFStreamer::emitCommonSymbol(), llvm::MCWinCOFFStreamer::emitLocalCommonSymbol(), and llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol().
endCOFFSymbolDef()
void MCStreamer::endCOFFSymbolDef () virtual
Marks the end of the symbol definition.
Reimplemented in llvm::RecordStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 1161 of file MCStreamer.cpp.
References llvm_unreachable.
endSection()
MCSymbol * MCStreamer::endSection (MCSection * Section)
Definition at line 1251 of file MCStreamer.cpp.
References Context, emitLabel(), llvm::MCSymbol::isInSection(), llvm::ARMBuildAttrs::Section, and switchSection().
Referenced by llvm::MCObjectStreamer::emitDwarfLineEndEntry(), and llvm::AArch64TargetStreamer::emitNoteSection().
EnsureValidWinFrameInfo()
WinEH::FrameInfo * MCStreamer::EnsureValidWinFrameInfo (SMLoc Loc)
Retrieve the current frame info if one is available and it is not yet closed.
Otherwise, issue an error and return null.
Definition at line 697 of file MCStreamer.cpp.
References Context, llvm::WinEH::FrameInfo::End, getContext(), llvm::MCContext::reportError(), and llvm::MCAsmInfo::usesWindowsCFI().
Referenced by emitWinCFIAllocStack(), emitWinCFIEndChained(), emitWinCFIEndProc(), emitWinCFIEndProlog(), emitWinCFIFuncletOrFuncEnd(), emitWinCFIPushFrame(), emitWinCFIPushReg(), emitWinCFISaveReg(), emitWinCFISaveXMM(), emitWinCFISetFrame(), emitWinCFIStartChained(), emitWinEHHandler(), and emitWinEHHandlerData().
finish()
void MCStreamer::finish (SMLoc EndLoc = SMLoc())
Finish emission of machine code.
Definition at line 1005 of file MCStreamer.cpp.
References llvm::MCTargetStreamer::finish(), finishImpl(), getContext(), getTargetStreamer(), and llvm::MCContext::reportError().
Referenced by llvm::DwarfStreamer::finish().
finishImpl()
void MCStreamer::finishImpl () virtual
Streamer specific finalization.
Reimplemented in llvm::MCObjectStreamer, llvm::MCELFStreamer, llvm::MCWinCOFFStreamer, and llvm::MCWasmStreamer.
Definition at line 1234 of file MCStreamer.cpp.
Referenced by finish().
generateCompactUnwindEncodings()
void MCStreamer::generateCompactUnwindEncodings (MCAsmBackend * MAB)
Definition at line 126 of file MCStreamer.cpp.
References llvm::MCAsmBackend::generateCompactUnwindEncoding().
Referenced by llvm::MCDwarfFrameEmitter::Emit().
getAllowAutoPadding()
bool llvm::MCStreamer::getAllowAutoPadding () const inline
Definition at line 309 of file MCStreamer.h.
getAssemblerPtr()
virtual MCAssembler* llvm::MCStreamer::getAssemblerPtr () inline virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 299 of file MCStreamer.h.
getAssociatedPDataSection()
MCSection * MCStreamer::getAssociatedPDataSection (const MCSection * TextSec)
Get the .pdata section used for the given section.
Typically the given section is either the main .text section or some other COMDAT .text section, but it may be any section containing code.
Definition at line 849 of file MCStreamer.cpp.
References getContext(), and getWinCFISection().
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), llvm::Win64EH::ARMUnwindEmitter::Emit(), and llvm::Win64EH::ARM64UnwindEmitter::Emit().
getAssociatedXDataSection()
MCSection * MCStreamer::getAssociatedXDataSection (const MCSection * TextSec)
Get the .xdata section used for the given section.
Definition at line 855 of file MCStreamer.cpp.
References getContext(), and getWinCFISection().
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), llvm::Win64EH::ARMUnwindEmitter::Emit(), llvm::Win64EH::ARM64UnwindEmitter::Emit(), llvm::Win64EH::UnwindEmitter::EmitUnwindInfo(), llvm::Win64EH::ARMUnwindEmitter::EmitUnwindInfo(), and llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo().
getCommentOS()
raw_ostream & MCStreamer::getCommentOS () virtual
Return a raw_ostream that comments can be written to.
Unlike AddComment, you are required to terminate comments with
if you use this method.
Definition at line 111 of file MCStreamer.cpp.
References llvm::nulls().
getContext()
MCContext& llvm::MCStreamer::getContext () const inline
Definition at line 297 of file MCStreamer.h.
References Context.
Referenced by llvm::CSKYConstantPool::addEntry(), llvm::AssemblerConstantPools::addEntry(), ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfo(), ARM64EmitUnwindInfoForSegment(), ARMEmitRuntimeFunction(), ARMEmitUnwindInfo(), buildSymbolDiff(), llvm::NVPTXTargetStreamer::changeSection(), llvm::MCTargetStreamer::changeSection(), llvm::MCObjectStreamer::changeSectionImpl(), checkCVLocSection(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MCPseudoProbeSections::emit(), llvm::MCPseudoProbeTable::emit(), llvm::MCDwarfLineTable::emit(), llvm::MCDwarfLineAddr::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), EmitAbsDifference(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiff(), llvm::MCObjectStreamer::emitAbsoluteSymbolDiffAsULEB128(), llvm::MCDwarfFrameEmitter::EmitAdvanceLoc(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::MipsELFStreamer::emitCFIEndProcImpl(), llvm::MipsELFStreamer::emitCFILabel(), emitCFIStartProc(), llvm::MipsELFStreamer::emitCFIStartProcImpl(), llvm::MCWinCOFFStreamer::emitCOFFImgRel32(), llvm::MCWinCOFFStreamer::emitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::emitCOFFSecRel32(), llvm::MCWinCOFFStreamer::emitCOFFSectionIndex(), llvm::MCWinCOFFStreamer::emitCommonSymbol(), llvm::MCELFStreamer::emitCommonSymbol(), llvm::SystemZTargetStreamer::emitConstantPools(), llvm::MCObjectStreamer::emitCVDefRangeDirective(), llvm::MCObjectStreamer::emitCVFileChecksumOffsetDirective(), llvm::MCObjectStreamer::emitCVFileChecksumsDirective(), emitCVFileDirective(), emitCVFuncIdDirective(), llvm::MCObjectStreamer::emitCVInlineLinetableDirective(), emitCVInlineSiteIdDirective(), llvm::MCObjectStreamer::emitCVLocDirective(), llvm::MCObjectStreamer::emitCVStringTableDirective(), emitDwarfFile0Directive(), llvm::MCObjectStreamer::emitDwarfLineEndEntry(), emitDwarfLocDirective(), emitFDESymbol(), llvm::MCObjectStreamer::emitFill(), emitFill(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::ARMTargetStreamer::emitInst(), llvm::MipsELFStreamer::emitInstruction(), llvm::MCObjectStreamer::emitInstruction(), emitLabel(), llvm::MCWinCOFFStreamer::emitLocalCommonSymbol(), emitNonLazySymbolPointer(), llvm::AArch64TargetStreamer::emitNoteSection(), llvm::MCDwarfLineTable::emitOne(), EmitPersonality(), emitPseudoProbe(), llvm::NVPTXTargetStreamer::emitRawBytes(), llvm::MCTargetStreamer::emitRawBytes(), llvm::MCDwarfLineStr::emitRef(), llvm::MCObjectStreamer::emitRelocDirective(), EmitRuntimeFunction(), llvm::MCDwarfLineStr::emitSection(), llvm::MCELFStreamer::emitSymbolAttribute(), EmitSymbolRefWithOfs(), emitSymbolValue(), EmitUnwindInfo(), llvm::MCTargetStreamer::emitValue(), llvm::AVRMCELFStreamer::emitValueForModiferKind(), llvm::MCObjectStreamer::emitValueImpl(), llvm::MCWasmStreamer::emitWeakReference(), llvm::MCELFStreamer::emitWeakReference(), llvm::MCWinCOFFStreamer::emitWeakReference(), emitWinCFIAllocStack(), emitWinCFIEndChained(), emitWinCFIEndProc(), emitWinCFIFuncletOrFuncEnd(), emitWinCFIPushFrame(), emitWinCFISaveReg(), emitWinCFISaveXMM(), emitWinCFISetFrame(), emitWinCFIStartProc(), emitWinEHHandler(), emitWinEHHandlerData(), EnsureValidWinFrameInfo(), finish(), llvm::MCObjectStreamer::finishImpl(), llvm::RecordStreamer::flushSymverDirectives(), getAssociatedPDataSection(), getAssociatedXDataSection(), llvm::AMDGPUTargetStreamer::getContext(), getDataAlignmentFactor(), getDwarfLineTableSymbol(), llvm::RISCVMCAsmInfo::getExprForFDESymbol(), llvm::SparcELFMCAsmInfo::getExprForFDESymbol(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::SparcELFMCAsmInfo::getExprForPersonalitySymbol(), llvm::X86_64MCAsmInfoDarwin::getExprForPersonalitySymbol(), GetOptionalAbsDifference(), getSizeForEncoding(), GetSubDivExpr(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::MCWinCOFFStreamer::initSections(), llvm::MCELFStreamer::initSections(), initSections(), llvm::MCDwarfLineEntry::make(), llvm::MCGenDwarfLabelEntry::Make(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), smallData(), tryEmitDwarfFileDirective(), and llvm::write().
getCurrentSection()
MCSectionSubPair llvm::MCStreamer::getCurrentSection () const inline
Return the current section that the streamer is emitting code to.
Definition at line 388 of file MCStreamer.h.
Referenced by llvm::MCELFStreamer::emitCommonSymbol(), getCurrentSectionOnly(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), and pushSection().
getCurrentSectionOnly()
MCSection* llvm::MCStreamer::getCurrentSectionOnly () const inline
Definition at line 393 of file MCStreamer.h.
References getCurrentSection().
Referenced by llvm::CSKYConstantPool::addEntry(), llvm::AssemblerConstantPools::addEntry(), llvm::MCObjectStreamer::addPendingLabel(), llvm::MCELFStreamer::changeSection(), checkCVLocSection(), llvm::AssemblerConstantPools::clearCacheForCurrentSection(), llvm::MCELFStreamer::emitBundleLock(), llvm::MCELFStreamer::emitBundleUnlock(), llvm::MCObjectStreamer::emitBytes(), emitCFIStartProc(), llvm::MCWinCOFFStreamer::emitCOFFSymbolIndex(), llvm::MCObjectStreamer::emitDwarfLocDirective(), llvm::MCObjectStreamer::emitFill(), llvm::AssemblerConstantPools::emitForCurrentSection(), llvm::MCObjectStreamer::emitInstruction(), llvm::MCWasmStreamer::emitLabel(), llvm::MCELFStreamer::emitLabel(), emitLabel(), llvm::MCWasmStreamer::emitLabelAtPos(), llvm::MCELFStreamer::emitLabelAtPos(), llvm::MCObjectStreamer::emitLabelAtPos(), llvm::MCObjectStreamer::emitNops(), llvm::AArch64TargetStreamer::emitNoteSection(), llvm::MCObjectStreamer::emitValueImpl(), llvm::MCObjectStreamer::emitValueToAlignment(), emitWinCFIStartChained(), emitWinCFIStartProc(), llvm::MCELFStreamer::finishImpl(), llvm::MCObjectStreamer::flushPendingLabels(), llvm::MCObjectStreamer::getCurrentFragment(), llvm::MCObjectStreamer::insert(), and llvm::MCGenDwarfLabelEntry::Make().
getCurrentWinFrameInfo()
WinEH::FrameInfo* llvm::MCStreamer::getCurrentWinFrameInfo () inline protected
Definition at line 263 of file MCStreamer.h.
getDwarfFrameInfos()
ArrayRef< MCDwarfFrameInfo > MCStreamer::getDwarfFrameInfos () const
Definition at line 117 of file MCStreamer.cpp.
Referenced by llvm::MCDwarfFrameEmitter::Emit().
getDwarfLineTableSymbol()
MCSymbol * MCStreamer::getDwarfLineTableSymbol (unsigned CUID) virtual
Definition at line 270 of file MCStreamer.cpp.
References Context, getContext(), llvm::MCDwarfLineTable::getLabel(), llvm::MCContext::getMCDwarfLineTable(), llvm::cl::Prefix, and llvm::MCDwarfLineTable::setLabel().
Referenced by llvm::MCGenDwarfInfo::Emit().
getMnemonic()
virtual StringRef llvm::MCStreamer::getMnemonic (MCInst & MI) inline virtual
Returns the mnemonic for MI, if the streamer has access to a instruction printer and returns an empty string otherwise.
Definition at line 479 of file MCStreamer.h.
getNumFrameInfos()
unsigned MCStreamer::getNumFrameInfos ()
Definition at line 116 of file MCStreamer.cpp.
Referenced by llvm::MCObjectStreamer::emitFrames().
getNumWinFrameInfos()
unsigned llvm::MCStreamer::getNumWinFrameInfos () inline
Definition at line 324 of file MCStreamer.h.
getPreviousSection()
MCSectionSubPair llvm::MCStreamer::getPreviousSection () const inline
Return the previous section that the streamer is emitting code to.
Definition at line 396 of file MCStreamer.h.
Referenced by pushSection().
getStartTokLoc()
SMLoc llvm::MCStreamer::getStartTokLoc () const inline
Definition at line 289 of file MCStreamer.h.
Referenced by llvm::MCELFStreamer::emitELFSymverDirective(), and llvm::MCELFStreamer::emitSymbolAttribute().
getSymbolOrder()
unsigned llvm::MCStreamer::getSymbolOrder (const MCSymbol * Sym) const inline
Returns an index to represent the order a symbol was emitted in.
(zero if we did not emit that symbol)
Definition at line 404 of file MCStreamer.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
getTargetStreamer()
MCTargetStreamer* llvm::MCStreamer::getTargetStreamer () inline
Definition at line 304 of file MCStreamer.h.
Referenced by llvm::MipsELFStreamer::createPendingLabelRelocs(), emitAssignment(), emitLabel(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), and finish().
getUseAssemblerInfoForParsing()
bool llvm::MCStreamer::getUseAssemblerInfoForParsing () inline
Definition at line 302 of file MCStreamer.h.
Referenced by llvm::MCObjectStreamer::getAssemblerPtr().
getWinFrameInfos()
ArrayRef<std::unique_ptr<WinEH::FrameInfo> > llvm::MCStreamer::getWinFrameInfos () const inline
Definition at line 325 of file MCStreamer.h.
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), llvm::Win64EH::ARMUnwindEmitter::Emit(), and llvm::Win64EH::ARM64UnwindEmitter::Emit().
hasRawTextSupport()
virtual bool llvm::MCStreamer::hasRawTextSupport () const inline virtual
Return true if this asm streamer supports emitting unformatted text to the .s file with EmitRawText.
Definition at line 340 of file MCStreamer.h.
hasUnfinishedDwarfFrameInfo()
bool MCStreamer::hasUnfinishedDwarfFrameInfo ()
Definition at line 280 of file MCStreamer.cpp.
initSections()
void MCStreamer::initSections (bool NoExecStack, const MCSubtargetInfo & STI) virtual
Create the default sections and set the initial one.
Reimplemented in llvm::MCELFStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 410 of file MCStreamer.cpp.
References getContext(), and switchSection().
isIntegratedAssemblerRequired()
virtual bool llvm::MCStreamer::isIntegratedAssemblerRequired () const inline virtual
Is the integrated assembler required for this streamer to function correctly?
Reimplemented in llvm::MCObjectStreamer.
Definition at line 344 of file MCStreamer.h.
isVerboseAsm()
virtual bool llvm::MCStreamer::isVerboseAsm () const inline virtual
Return true if this streamer supports verbose assembly and if it is enabled.
Definition at line 336 of file MCStreamer.h.
maybeEmitDwarf64Mark()
void MCStreamer::maybeEmitDwarf64Mark ()
Emit a special value of 0xffffffff if producing 64-bit debugging info.
Definition at line 1019 of file MCStreamer.cpp.
References AddComment(), Context, llvm::dwarf::DW_LENGTH_DWARF64, llvm::dwarf::DWARF64, and emitInt32().
Referenced by emitDwarfUnitLength().
mayHaveInstructions()
virtual bool llvm::MCStreamer::mayHaveInstructions (MCSection & Sec) const inline virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1130 of file MCStreamer.h.
Referenced by llvm::MCContext::finalizeDwarfSections().
operator=()
MCStreamer& llvm::MCStreamer::operator= (const MCStreamer &) delete
popSection()
bool llvm::MCStreamer::popSection () inline
Restore the current and previous section from the section stack.
Calls changeSection as needed.
Returns false if the stack was empty.
Definition at line 424 of file MCStreamer.h.
References changeSection(), and I.
Referenced by llvm::MCWinCOFFStreamer::emitCommonSymbol(), llvm::MCELFStreamer::emitIdent(), llvm::MCWinCOFFStreamer::emitLocalCommonSymbol(), and llvm::MipsRegInfoRecord::EmitMipsOptionRecord().
pushSection()
void llvm::MCStreamer::pushSection () inline
Save the current and previous section on the section stack.
Definition at line 415 of file MCStreamer.h.
References getCurrentSection(), and getPreviousSection().
Referenced by llvm::MCWinCOFFStreamer::emitCommonSymbol(), llvm::MCELFStreamer::emitIdent(), llvm::MCWinCOFFStreamer::emitLocalCommonSymbol(), and llvm::MipsRegInfoRecord::EmitMipsOptionRecord().
reset()
void MCStreamer::reset () virtual
State management.
Reimplemented in llvm::CSKYELFStreamer, llvm::MCObjectStreamer, llvm::MCELFStreamer, llvm::MCWasmStreamer, and llvm::MCWinCOFFStreamer.
Definition at line 102 of file MCStreamer.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), and llvm::SmallVectorImpl< T >::clear().
Referenced by llvm::LLVMTargetMachine::createMCStreamer(), and llvm::MCObjectStreamer::reset().
setAllowAutoPadding()
void llvm::MCStreamer::setAllowAutoPadding (bool v) inline
Definition at line 308 of file MCStreamer.h.
Referenced by llvm::MCObjectStreamer::MCObjectStreamer().
setStartTokLocPtr()
void llvm::MCStreamer::setStartTokLocPtr (const SMLoc * Loc) inline
Definition at line 288 of file MCStreamer.h.
setTargetStreamer()
void llvm::MCStreamer::setTargetStreamer (MCTargetStreamer * TS) inline
Definition at line 284 of file MCStreamer.h.
setUseAssemblerInfoForParsing()
void llvm::MCStreamer::setUseAssemblerInfoForParsing (bool v) inline
Definition at line 301 of file MCStreamer.h.
subSection()
bool llvm::MCStreamer::subSection (const MCExpr * Subsection) inline
Definition at line 439 of file MCStreamer.h.
References switchSection().
switchSection()
void MCStreamer::switchSection (MCSection * Section, const MCExpr * Subsection = nullptr) virtual
Set the current section where code is being emitted to Section.
This is required to update CurSection.
This corresponds to assembler directives like .section, .text, etc.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 1237 of file MCStreamer.cpp.
References assert(), changeSection(), emitLabel(), llvm::MCSymbol::isInSection(), and llvm::ARMBuildAttrs::Section.
Referenced by addAllTypesFromDWP(), addAllTypesFromTypesSection(), llvm::Win64EH::UnwindEmitter::Emit(), llvm::Win64EH::ARMUnwindEmitter::Emit(), llvm::Win64EH::ARM64UnwindEmitter::Emit(), llvm::MCPseudoProbeSections::emit(), llvm::MCDwarfDwoLineTable::Emit(), llvm::MCDwarfLineTable::emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), llvm::DwarfStreamer::emitAbbrevs(), llvm::DwarfStreamer::emitCIE(), llvm::MCWinCOFFStreamer::emitCommonSymbol(), llvm::MCELFStreamer::emitCommonSymbol(), emitConstantPool(), llvm::SystemZTargetStreamer::emitConstantPools(), llvm::DwarfStreamer::emitDIE(), llvm::DwarfStreamer::emitDwarfDebugRangesTableFragment(), llvm::MCObjectStreamer::emitDwarfLineEndEntry(), llvm::DwarfStreamer::emitFDE(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::MCELFStreamer::emitIdent(), llvm::DwarfStreamer::emitLineTableForUnit(), llvm::MCWinCOFFStreamer::emitLocalCommonSymbol(), llvm::DwarfStreamer::emitLocationsForUnit(), llvm::DwarfStreamer::emitMacroTables(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), emitNonLazyStubs(), llvm::AArch64TargetStreamer::emitNoteSection(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::MCDwarfLineStr::emitSection(), llvm::DwarfStreamer::emitSectionContents(), llvm::DwarfStreamer::emitSwiftAST(), llvm::DwarfStreamer::emitSwiftReflectionSection(), llvm::Win64EH::UnwindEmitter::EmitUnwindInfo(), llvm::Win64EH::ARMUnwindEmitter::EmitUnwindInfo(), llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo(), emitWinCFIEndProc(), endSection(), llvm::DWPStringPool::getOffset(), llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol(), llvm::MCWinCOFFStreamer::initSections(), llvm::MCELFStreamer::initSections(), initSections(), llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer(), smallData(), subSection(), llvm::MipsELFStreamer::switchSection(), llvm::DwarfStreamer::switchToDebugInfoSection(), llvm::DwarfStreamer::translateLineTable(), and llvm::writeIndex().
switchSectionNoChange()
void llvm::MCStreamer::switchSectionNoChange (MCSection * Section, const MCExpr * Subsection = nullptr) inline
Set the current section where code is being emitted to Section.
This is required to update CurSection. This version does not call changeSection.
Definition at line 457 of file MCStreamer.h.
References assert().
tryEmitDwarfFileDirective()
Expected< unsigned > MCStreamer::tryEmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, std::optional< MD5::MD5Result > Checksum = std::nullopt, std::optional< StringRef > Source = std::nullopt, unsigned CUID = 0) virtual
Associate a filename with a specified logical file number.
Also associate a directory, optional checksum, and optional source text with the logical file. This implements the DWARF2 '.file 4 "dir/foo.c"' assembler directive, and the DWARF5 '.file 4 "dir/foo.c" md5 "..." source "..."' assembler directive.
Definition at line 231 of file MCStreamer.cpp.
References getContext(), llvm::MCContext::getDwarfFile(), and llvm::Sched::Source.
Referenced by emitDwarfFileDirective().
visitUsedExpr()
void MCStreamer::visitUsedExpr (const MCExpr & Expr)
Definition at line 1073 of file MCStreamer.cpp.
References llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, llvm::MCExpr::Unary, and visitUsedSymbol().
Referenced by emitAssignment(), emitInstruction(), llvm::HexagonMCELFStreamer::EmitSymbol(), emitValueImpl(), llvm::HexagonMCExpr::visitUsedExpr(), llvm::LanaiMCExpr::visitUsedExpr(), llvm::XtensaMCExpr::visitUsedExpr(), llvm::CSKYMCExpr::visitUsedExpr(), llvm::AVRMCExpr::visitUsedExpr(), llvm::ARMMCExpr::visitUsedExpr(), llvm::RISCVMCExpr::visitUsedExpr(), llvm::MipsMCExpr::visitUsedExpr(), llvm::VEMCExpr::visitUsedExpr(), llvm::PPCMCExpr::visitUsedExpr(), llvm::LoongArchMCExpr::visitUsedExpr(), llvm::SparcMCExpr::visitUsedExpr(), and llvm::AArch64MCExpr::visitUsedExpr().
visitUsedSymbol()
void MCStreamer::visitUsedSymbol (const MCSymbol & Sym) virtual
Reimplemented in llvm::MCObjectStreamer.
Definition at line 1070 of file MCStreamer.cpp.
Referenced by visitUsedExpr().
The documentation for this class was generated from the following files:
include/llvm/MC/MCStreamer.h
lib/MC/MCStreamer.cpp