LLVM: llvm::mca::RegisterFile Class Reference
llvm::mca::RegisterFile Class Reference
Manages hardware register files, and tracks register definitions for register renaming purposes.
#include "llvm/MCA/HardwareUnits/RegisterFile.h"
Classes
struct RAWHazard
Public Member Functions
RegisterFile (const MCSchedModel &SM, const MCRegisterInfo &mri, unsigned NumRegs=0)
void collectWrites (const MCSubtargetInfo &STI, const ReadState &RS, SmallVectorImpl< WriteRef > &Writes, SmallVectorImpl< WriteRef > &CommittedWrites) const
RAWHazard checkRAWHazards (const MCSubtargetInfo &STI, const ReadState &RS) const
void addRegisterWrite (WriteRef Write, MutableArrayRef< unsigned > UsedPhysRegs)
void addRegisterRead (ReadState &RS, const MCSubtargetInfo &STI) const
void removeRegisterWrite (const WriteState &WS, MutableArrayRef< unsigned > FreedPhysRegs)
bool canEliminateMove (const WriteState &WS, const ReadState &RS, unsigned PRFIndex) const
bool tryEliminateMoveOrSwap (MutableArrayRef< WriteState > Writes, MutableArrayRef< ReadState > Reads)
unsigned isAvailable (ArrayRef< MCPhysReg > Regs) const
unsigned getNumRegisterFiles () const
unsigned getElapsedCyclesFromWriteBack (const WriteRef &WR) const
void onInstructionExecuted (Instruction *IS)
void cycleStart ()
void cycleEnd ()
void dump () const
Public Member Functions inherited from llvm::mca::HardwareUnit
HardwareUnit ()=default
virtual ~HardwareUnit ()
Detailed Description
Manages hardware register files, and tracks register definitions for register renaming purposes.
Definition at line 83 of file RegisterFile.h.
Constructor & Destructor Documentation
RegisterFile()
llvm::mca::RegisterFile::RegisterFile (const MCSchedModel & SM, const MCRegisterInfo & mri, unsigned NumRegs = 0)
Definition at line 64 of file RegisterFile.cpp.
Member Function Documentation
addRegisterRead()
void llvm::mca::RegisterFile::addRegisterRead (ReadState & RS, const MCSubtargetInfo & STI) const
Definition at line 618 of file RegisterFile.cpp.
References llvm::mca::WriteState::addUser(), assert(), collectWrites(), llvm::mca::ReadState::getDescriptor(), getElapsedCyclesFromWriteBack(), llvm::MCSubtargetInfo::getReadAdvanceCycles(), llvm::mca::ReadState::getRegisterID(), llvm::MCSchedModel::getSchedClassDesc(), llvm::MCSubtargetInfo::getSchedModel(), llvm::mca::ReadState::isIndependentFromDef(), llvm::PPCISD::SC, llvm::mca::ReadDescriptor::SchedClassID, llvm::mca::ReadState::setDependentWrites(), llvm::mca::ReadState::setPRF(), llvm::mca::ReadState::setReadZero(), llvm::mca::ReadDescriptor::UseIndex, and llvm::mca::ReadState::writeStartEvent().
Referenced by llvm::mca::addRegisterReadWrite().
addRegisterWrite()
void llvm::mca::RegisterFile::addRegisterWrite (WriteRef Write, MutableArrayRef< unsigned > UsedPhysRegs)
Definition at line 228 of file RegisterFile.cpp.
References llvm::mca::WriteState::addUser(), assert(), llvm::mca::WriteState::clearsSuperRegisters(), llvm::dbgs(), llvm::mca::WriteState::getLatency(), llvm::MCRegisterInfo::getName(), llvm::mca::WriteState::getRegisterID(), llvm::mca::WriteRef::getSourceIndex(), llvm::mca::WriteRef::getWriteState(), I, llvm::mca::WriteState::isEliminated(), llvm::mca::WriteState::isWriteZero(), LLVM_DEBUG, llvm::APInt::setBitVal(), and llvm::mca::WriteState::setPRF().
Referenced by llvm::mca::addRegisterReadWrite().
canEliminateMove()
bool llvm::mca::RegisterFile::canEliminateMove (const WriteState & WS, const ReadState & RS, unsigned PRFIndex) const
Definition at line 384 of file RegisterFile.cpp.
References llvm::mca::WriteState::clearsSuperRegisters(), llvm::mca::WriteState::getRegisterID(), and llvm::mca::ReadState::getRegisterID().
Referenced by tryEliminateMoveOrSwap().
checkRAWHazards()
RegisterFile::RAWHazard llvm::mca::RegisterFile::checkRAWHazards (const MCSubtargetInfo & STI, const ReadState & RS) const
Definition at line 568 of file RegisterFile.cpp.
References assert(), collectWrites(), llvm::mca::RegisterFile::RAWHazard::CyclesLeft, llvm::mca::WriteState::getCyclesLeft(), llvm::mca::ReadState::getDescriptor(), getElapsedCyclesFromWriteBack(), llvm::MCSubtargetInfo::getReadAdvanceCycles(), llvm::MCSchedModel::getSchedClassDesc(), llvm::MCSubtargetInfo::getSchedModel(), llvm::mca::WriteState::getWriteResourceID(), llvm::mca::RegisterFile::RAWHazard::isValid(), llvm::mca::RegisterFile::RAWHazard::RegisterID, llvm::PPCISD::SC, llvm::mca::ReadDescriptor::SchedClassID, llvm::mca::UNKNOWN_CYCLES, and llvm::mca::ReadDescriptor::UseIndex.
Referenced by llvm::mca::checkRegisterHazard().
collectWrites()
void llvm::mca::RegisterFile::collectWrites (const MCSubtargetInfo & STI, const ReadState & RS, SmallVectorImpl< WriteRef > & Writes, SmallVectorImpl< WriteRef > & CommittedWrites) const
Definition at line 502 of file RegisterFile.cpp.
References assert(), llvm::dbgs(), llvm::mca::ReadState::getDescriptor(), getElapsedCyclesFromWriteBack(), llvm::MCRegisterInfo::getName(), llvm::MCSubtargetInfo::getReadAdvanceCycles(), llvm::mca::WriteState::getRegisterID(), llvm::mca::ReadState::getRegisterID(), llvm::MCSchedModel::getSchedClassDesc(), llvm::MCSubtargetInfo::getSchedModel(), llvm::mca::WriteRef::getSourceIndex(), llvm::mca::WriteRef::getWriteResourceID(), llvm::mca::WriteRef::getWriteState(), llvm::mca::WriteRef::hasKnownWriteBackCycle(), I, LLVM_DEBUG, llvm::SmallVectorImpl< T >::resize(), llvm::PPCISD::SC, llvm::mca::ReadDescriptor::SchedClassID, llvm::sort(), llvm::unique(), and llvm::mca::ReadDescriptor::UseIndex.
Referenced by addRegisterRead(), and checkRAWHazards().
cycleEnd()
void llvm::mca::RegisterFile::cycleEnd () inline
Definition at line 302 of file RegisterFile.h.
Referenced by llvm::mca::RetireStage::cycleEnd(), and llvm::mca::InOrderIssueStage::cycleEnd().
cycleStart()
void llvm::mca::RegisterFile::cycleStart ()
Definition at line 100 of file RegisterFile.cpp.
Referenced by llvm::mca::RetireStage::cycleStart(), and llvm::mca::InOrderIssueStage::cycleStart().
dump()
void llvm::mca::RegisterFile::dump () const
Definition at line 717 of file RegisterFile.cpp.
References llvm::dbgs(), E, llvm::MCRegisterInfo::getName(), getNumRegisterFiles(), llvm::MCRegisterInfo::getNumRegs(), I, and llvm::AArch64::RM.
Referenced by llvm::mca::DispatchStage::dump().
getElapsedCyclesFromWriteBack()
unsigned llvm::mca::RegisterFile::getElapsedCyclesFromWriteBack (const WriteRef & WR) const
Definition at line 497 of file RegisterFile.cpp.
References assert(), llvm::mca::WriteRef::getWriteBackCycle(), and llvm::mca::WriteRef::hasKnownWriteBackCycle().
Referenced by addRegisterRead(), checkRAWHazards(), and collectWrites().
getNumRegisterFiles()
unsigned llvm::mca::RegisterFile::getNumRegisterFiles () const inline
Definition at line 293 of file RegisterFile.h.
Referenced by llvm::mca::DispatchStage::cycleStart(), dump(), isAvailable(), and llvm::mca::RetireStage::notifyInstructionRetired().
isAvailable()
unsigned llvm::mca::RegisterFile::isAvailable (ArrayRef< MCPhysReg > Regs) const
Definition at line 660 of file RegisterFile.cpp.
References getNumRegisterFiles().
onInstructionExecuted()
void llvm::mca::RegisterFile::onInstructionExecuted (Instruction * IS)
Definition at line 105 of file RegisterFile.cpp.
References assert(), llvm::mca::InstructionBase::getDefs(), llvm::mca::WriteRef::getWriteState(), I, llvm::mca::Instruction::isExecuted(), llvm::mca::WriteRef::notifyExecuted(), and llvm::mca::UNKNOWN_CYCLES.
Referenced by llvm::mca::RetireStage::execute().
removeRegisterWrite()
void llvm::mca::RegisterFile::removeRegisterWrite (const WriteState & WS, MutableArrayRef< unsigned > FreedPhysRegs)
Definition at line 332 of file RegisterFile.cpp.
References assert(), llvm::mca::WriteState::clearsSuperRegisters(), llvm::mca::WriteRef::commit(), llvm::mca::WriteState::getCyclesLeft(), llvm::mca::WriteState::getRegisterID(), llvm::mca::WriteRef::getWriteState(), I, llvm::mca::WriteState::isEliminated(), llvm::mca::WriteState::isWriteZero(), and llvm::mca::UNKNOWN_CYCLES.
Referenced by llvm::mca::RetireStage::notifyInstructionRetired().
tryEliminateMoveOrSwap()
bool llvm::mca::RegisterFile::tryEliminateMoveOrSwap (MutableArrayRef< WriteState > Writes, MutableArrayRef< ReadState > Reads)
Definition at line 426 of file RegisterFile.cpp.
References canEliminateMove(), E, llvm::mca::WriteState::getRegisterID(), llvm::mca::ReadState::getRegisterID(), I, if(), llvm::mca::WriteState::setEliminated(), llvm::mca::ReadState::setReadZero(), and llvm::mca::WriteState::setWriteZero().
The documentation for this class was generated from the following files:
include/llvm/MCA/HardwareUnits/RegisterFile.h
lib/MCA/HardwareUnits/RegisterFile.cpp