LLVM: llvm::InlineAdvisorAnalysisPrinterPass Class Reference
llvm::InlineAdvisorAnalysisPrinterPass Class Reference
Printer pass for the FunctionPropertiesAnalysis results.
#include "llvm/Analysis/InlineAdvisor.h"
Public Member Functions
InlineAdvisorAnalysisPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
PreservedAnalyses run (LazyCallGraph::SCC &InitialC, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Public Member Functions inherited from llvm::PassInfoMixin< InlineAdvisorAnalysisPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< InlineAdvisorAnalysisPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the FunctionPropertiesAnalysis results.
Definition at line 346 of file InlineAdvisor.h.
Constructor & Destructor Documentation
InlineAdvisorAnalysisPrinterPass()
llvm::InlineAdvisorAnalysisPrinterPass::InlineAdvisorAnalysisPrinterPass (raw_ostream & OS) inline explicit
Definition at line 351 of file InlineAdvisor.h.
References OS.
Member Function Documentation
run() [1/2]
PreservedAnalyses InlineAdvisorAnalysisPrinterPass::run (LazyCallGraph::SCC & InitialC, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Definition at line 637 of file InlineAdvisor.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::AArch64PACKey::IA, and M.
run() [2/2]
PreservedAnalyses InlineAdvisorAnalysisPrinterPass::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 628 of file InlineAdvisor.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AArch64PACKey::IA, M, and MAM.
The documentation for this class was generated from the following files:
include/llvm/Analysis/InlineAdvisor.h
lib/Analysis/InlineAdvisor.cpp