LLVM: llvm::DevirtSCCRepeatedPass Class Reference
llvm::DevirtSCCRepeatedPass Class Reference
A helper that repeats an SCC pass each time an indirect call is refined to a direct call by that pass.
#include "llvm/Analysis/CGSCCPassManager.h"
Public Types
using PassConceptT = detail::PassConcept< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >
Public Member Functions
DevirtSCCRepeatedPass (std::unique_ptr< PassConceptT > Pass, int MaxIterations)
PreservedAnalyses run (LazyCallGraph::SCC &InitialC, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Runs the wrapped pass up to MaxIterations on the SCC, iterating whenever an indirect call is refined.
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< DevirtSCCRepeatedPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< DevirtSCCRepeatedPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A helper that repeats an SCC pass each time an indirect call is refined to a direct call by that pass.
While the CGSCC pass manager works to re-visit SCCs and RefSCCs as they change shape, we may also want to repeat an SCC pass if it simply refines an indirect call to a direct call, even if doing so does not alter the shape of the graph. Note that this only pertains to direct calls to functions where IPO across the SCC may be able to compute more precise results. For intrinsics, we assume scalar optimizations already can fully reason about them.
This repetition has the potential to be very large however, as each one might refine a single call site. As a consequence, in practice we use an upper bound on the number of repetitions to limit things.
Definition at line 551 of file CGSCCPassManager.h.
Member Typedef Documentation
PassConceptT
using llvm::DevirtSCCRepeatedPass::PassConceptT = detail::PassConcept<LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult &>
Definition at line 555 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
DevirtSCCRepeatedPass()
llvm::DevirtSCCRepeatedPass::DevirtSCCRepeatedPass (std::unique_ptr< PassConceptT > Pass, int MaxIterations) inline explicit
Definition at line 557 of file CGSCCPassManager.h.
Member Function Documentation
printPipeline()
void llvm::DevirtSCCRepeatedPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName) inline
Definition at line 566 of file CGSCCPassManager.h.
References OS.
run()
PreservedAnalyses llvm::DevirtSCCRepeatedPass::run (LazyCallGraph::SCC & InitialC, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Runs the wrapped pass up to MaxIterations on the SCC, iterating whenever an indirect call is refined.
Definition at line 356 of file CGSCCPassManager.cpp.
References llvm::AbortOnMaxDevirtIterationsReached, llvm::PreservedAnalyses::all(), llvm::any_of(), assert(), llvm::dbgs(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), I, llvm::CGSCCUpdateResult::IndirectVHs, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), llvm::instructions(), llvm::PreservedAnalyses::intersect(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::CGSCCUpdateResult::InvalidatedSCCs, LLVM_DEBUG, move, N, P, llvm::report_fatal_error(), llvm::PassInstrumentation::runAfterPass(), llvm::PassInstrumentation::runAfterPassInvalidated(), llvm::PassInstrumentation::runBeforePass(), and llvm::CGSCCUpdateResult::UpdatedC.
The documentation for this class was generated from the following files:
include/llvm/Analysis/CGSCCPassManager.h
lib/Analysis/CGSCCPassManager.cpp