LLVM: llvm::TargetRegisterClass Class Reference
llvm::TargetRegisterClass Class Reference
#include "llvm/CodeGen/TargetRegisterInfo.h"
Public Types
using iterator = const MCPhysReg *
using const_iterator = const MCPhysReg *
using sc_iterator = const TargetRegisterClass *const *
Public Member Functions
unsigned getID () const
Return the register class ID number.
iterator begin () const
begin/end - Return all of the registers in this class.
iterator end () const
unsigned getNumRegs () const
Return the number of registers in this class.
iterator_range< SmallVectorImpl< MCPhysReg >::const_iterator > getRegisters () const
MCRegister getRegister (unsigned i) const
Return the specified register in the class.
bool contains (Register Reg) const
Return true if the specified register is included in this register class.
bool contains (Register Reg1, Register Reg2) const
Return true if both registers are in this class.
int getCopyCost () const
Return the cost of copying a value between two registers in this class.
bool isAllocatable () const
Return true if this register class may be used to create virtual registers.
bool hasSubClass (const TargetRegisterClass *RC) const
Return true if the specified TargetRegisterClass is a proper sub-class of this TargetRegisterClass.
bool hasSubClassEq (const TargetRegisterClass *RC) const
Returns true if RC is a sub-class of or equal to this class.
bool hasSuperClass (const TargetRegisterClass *RC) const
Return true if the specified TargetRegisterClass is a proper super-class of this TargetRegisterClass.
bool hasSuperClassEq (const TargetRegisterClass *RC) const
Returns true if RC is a super-class of or equal to this class.
const uint32_t * getSubClassMask () const
Returns a bit vector of subclasses, including this one.
const uint16_t * getSuperRegIndices () const
Returns a 0-terminated list of sub-register indices that project some super-register class into this register class.
sc_iterator getSuperClasses () const
Returns a NULL-terminated list of super-classes.
bool isASubClass () const
Return true if this TargetRegisterClass is a subset class of at least one other TargetRegisterClass.
ArrayRef< MCPhysReg > getRawAllocationOrder (const MachineFunction &MF) const
Returns the preferred order for allocating registers from this register class in MF.
LaneBitmask getLaneMask () const
Returns the combination of all lane masks of register in this class.
Public Attributes
const MCRegisterClass * MC
const uint32_t * SubClassMask
const uint16_t * SuperRegIndices
const LaneBitmask LaneMask
const uint8_t AllocationPriority
Classes with a higher priority value are assigned first by register allocators using a greedy heuristic.
const bool GlobalPriority
const uint8_t TSFlags
Configurable target specific flags.
const bool HasDisjunctSubRegs
Whether the class supports two (or more) disjunct subregister indices.
const bool CoveredBySubRegs
Whether a combination of subregisters can cover every register in the class.
const sc_iterator SuperClasses
ArrayRef< MCPhysReg >(* OrderFunc)(const MachineFunction &)
Detailed Description
Definition at line 45 of file TargetRegisterInfo.h.
Member Typedef Documentation
const_iterator
using llvm::TargetRegisterClass::const_iterator = const MCPhysReg *
Definition at line 48 of file TargetRegisterInfo.h.
iterator
using llvm::TargetRegisterClass::iterator = const MCPhysReg *
Definition at line 47 of file TargetRegisterInfo.h.
sc_iterator
using llvm::TargetRegisterClass::sc_iterator = const TargetRegisterClass* const *
Definition at line 49 of file TargetRegisterInfo.h.
Member Function Documentation
begin()
iterator llvm::TargetRegisterClass::begin () const inline
begin/end - Return all of the registers in this class.
Definition at line 78 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::begin(), and MC.
Referenced by allocateSGPR32InputImpl(), llvm::HexagonBlockRanges::expandToSubRegs(), getRawAllocationOrder(), and getRegistersForValue().
contains() [1/2]
bool llvm::TargetRegisterClass::contains (Register Reg) const inline
Return true if the specified register is included in this register class.
This does not include virtual registers.
FIXME: Historically this function has returned false when given vregs but it should probably only receive physical registers
Definition at line 96 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::contains(), and MC.
Referenced by addHints(), llvm::MachineFunction::addLiveIn(), canFoldCopy(), llvm::PPCInstrInfo::ClobbersPredicate(), llvm::VirtRegAuxInfo::copyHint(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), estimateRSStackSizeLimit(), llvm::R600InstrInfo::getIndirectIndexBegin(), llvm::M68kRegisterInfo::getMatchingMegaReg(), llvm::M68kRegisterInfo::getMaximalPhysRegClass(), llvm::PPCRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::PPCInstrInfo::insertSelect(), llvm::SIInstrInfo::isLegalRegOperand(), llvm::HexagonMCInstrInfo::isPredReg(), matchAliasCondition(), llvm::rewriteT2FrameIndex(), llvm::CoalescerPair::setRegisters(), llvm::SystemZRegisterInfo::shouldCoalesce(), UpdateOperandRegClass(), and llvm::SIInstrInfo::verifyInstruction().
contains() [2/2]
bool llvm::TargetRegisterClass::contains (Register Reg1, Register Reg2) const inline
Return true if both registers are in this class.
FIXME: Historically this function has returned false when given a vregs but it should probably only receive physical registers
Definition at line 105 of file TargetRegisterInfo.h.
References llvm::Register::asMCReg(), llvm::MCRegisterClass::contains(), llvm::Register::isPhysical(), and MC.
end()
iterator llvm::TargetRegisterClass::end () const inline
Definition at line 79 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::end(), and MC.
Referenced by getRegistersForValue().
getCopyCost()
int llvm::TargetRegisterClass::getCopyCost () const inline
Return the cost of copying a value between two registers in this class.
A negative number means the register class is very expensive to copy e.g. status flag register classes.
Definition at line 116 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getCopyCost(), and MC.
Referenced by CheckForPhysRegDependency(), and llvm::SITargetLowering::checkForPhysRegDependency().
getID()
unsigned llvm::TargetRegisterClass::getID () const inline
Return the register class ID number.
Definition at line 74 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getID(), and MC.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SIInstrInfo::canInsertSelect(), llvm::HexagonEvaluator::composeWithSubRegIndex(), llvm::RegisterBank::covers(), llvm::HexagonFrameLowering::determineCalleeSaves(), llvm::SITargetLowering::finalizeLowering(), llvm::HexagonRegisterInfo::getCallerSavedRegs(), llvm::WebAssembly::getCopyOpcodeForRegClass(), llvm::HexagonRegisterInfo::getHexagonSubRegIndex(), llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::SPIRVRegisterBankInfo::getRegBankFromRegClass(), llvm::ARMRegisterBankInfo::getRegBankFromRegClass(), llvm::MipsRegisterBankInfo::getRegBankFromRegClass(), llvm::PPCRegisterBankInfo::getRegBankFromRegClass(), llvm::AArch64RegisterBankInfo::getRegBankFromRegClass(), llvm::TargetRegisterInfo::getRegClassInfo(), llvm::MipsRegisterInfo::getRegPressureLimit(), llvm::PPCRegisterInfo::getRegPressureLimit(), llvm::X86RegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::ARMBaseRegisterInfo::getRegPressureLimit(), llvm::SIRegisterInfo::getRegPressureLimit(), hasSubClassEq(), INITIALIZE_PASS(), isTileDef(), isTileRegDef(), llvm::X86RegisterInfo::isTileRegisterClass(), llvm::SPIRVInstrInfo::isTypeDeclInstr(), IsWritingToVCCR(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::HexagonEvaluator::mask(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::WebAssembly::regClassToValType(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::HexagonRegisterInfo::shouldCoalesce(), and llvm::AArch64RegisterInfo::shouldCoalesce().
getLaneMask()
LaneBitmask llvm::TargetRegisterClass::getLaneMask () const inline
Returns the combination of all lane masks of register in this class.
The lane masks of the registers are the combination of all lane masks of their subregisters. Returns 1 if there are no subregisters.
Definition at line 209 of file TargetRegisterInfo.h.
References LaneMask.
Referenced by llvm::ScheduleDAGInstrs::getLaneMaskForMO(), and llvm::MachineRegisterInfo::getMaxLaneMaskForVReg().
getNumRegs()
unsigned llvm::TargetRegisterClass::getNumRegs () const inline
Return the number of registers in this class.
Definition at line 82 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getNumRegs(), and MC.
Referenced by llvm::RegisterClassInfo::computePSetLimit(), constrainRegClass(), llvm::R600InstrInfo::getIndirectIndexBegin(), llvm::M68kRegisterInfo::getMaximalPhysRegClass(), getRawAllocationOrder(), llvm::M68kRegisterInfo::getRegisterOrder(), llvm::ExecutionDomainFix::runOnMachineFunction(), and llvm::SystemZRegisterInfo::shouldCoalesce().
getRawAllocationOrder()
ArrayRef<MCPhysReg> llvm::TargetRegisterClass::getRawAllocationOrder (const MachineFunction & MF) const inline
Returns the preferred order for allocating registers from this register class in MF.
The raw order comes directly from the .td file and may include reserved registers that are not allocatable. Register allocators should also make sure to allocate callee-saved registers only after all the volatiles are used. The RegisterClassInfo class provides filtered allocation orders with callee-saved registers moved to the end.
The MachineFunction argument can be used to tune the allocatable registers based on the characteristics of the function, subtarget, or other criteria.
By default, this method returns all registers in the class.
Definition at line 202 of file TargetRegisterInfo.h.
References llvm::ArrayRef(), begin(), getNumRegs(), and OrderFunc.
Referenced by getAllocatableSetForRC(), and llvm::RegScavenger::scavengeRegisterBackwards().
getRegister()
MCRegister llvm::TargetRegisterClass::getRegister (unsigned i) const inline
Return the specified register in the class.
Definition at line 90 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::getRegister(), i, and MC.
Referenced by llvm::R600InstrInfo::getIndirectIndexBegin(), llvm::M68kRegisterInfo::getRegisterOrder(), and llvm::tryFoldSPUpdateIntoPushPop().
getRegisters()
iterator_range<SmallVectorImpl<MCPhysReg>::const_iterator> llvm::TargetRegisterClass::getRegisters () const inline
Definition at line 85 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::begin(), llvm::MCRegisterClass::end(), llvm::make_range(), and MC.
Referenced by llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR().
getSubClassMask()
const uint32_t* llvm::TargetRegisterClass::getSubClassMask () const inline
Returns a bit vector of subclasses, including this one.
The vector is indexed by class IDs.
To use it, consider the returned array as a chunk of memory that contains an array of bits of size NumRegClasses. Each 32-bit chunk contains a bitset of the ID of the subclasses in big-endian style. I.e., the representation of the memory from left to right at the bit level looks like: [31 30 ... 1 0] [ 63 62 ... 33 32] ... [ XXX NumRegClasses NumRegClasses - 1 ... ] Where the number represents the class ID and XXX bits that should be ignored.
See the implementation of hasSubClassEq for an example of how it can be used.
Definition at line 161 of file TargetRegisterInfo.h.
References SubClassMask.
Referenced by llvm::TargetRegisterInfo::getAllocatableClass().
getSuperClasses()
sc_iterator llvm::TargetRegisterClass::getSuperClasses () const inline
Returns a NULL-terminated list of super-classes.
The classes are ordered by ID which is also a topological ordering from large to small classes. The list does NOT include the current class.
Definition at line 179 of file TargetRegisterInfo.h.
References SuperClasses.
Referenced by llvm::HexagonRegisterInfo::getHexagonSubRegIndex(), llvm::X86RegisterInfo::getLargestLegalSuperClass(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), and llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass().
getSuperRegIndices()
const uint16_t* llvm::TargetRegisterClass::getSuperRegIndices () const inline
Returns a 0-terminated list of sub-register indices that project some super-register class into this register class.
The list has an entry for each Idx such that:
There exists SuperRC where: For all Reg in SuperRC: this->contains(Reg:Idx)
Definition at line 172 of file TargetRegisterInfo.h.
References SuperRegIndices.
hasSubClass()
bool llvm::TargetRegisterClass::hasSubClass (const TargetRegisterClass * RC) const inline
Return true if the specified TargetRegisterClass is a proper sub-class of this TargetRegisterClass.
Definition at line 124 of file TargetRegisterInfo.h.
References hasSubClassEq().
Referenced by llvm::M68kRegisterInfo::getMaximalPhysRegClass(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::TargetRegisterInfo::getMinimalPhysRegClassLLT(), and hasSuperClass().
hasSubClassEq()
bool llvm::TargetRegisterClass::hasSubClassEq (const TargetRegisterClass * RC) const inline
Returns true if RC is a sub-class of or equal to this class.
Definition at line 129 of file TargetRegisterInfo.h.
References getID(), and SubClassMask.
Referenced by llvm::MachineFunction::addLiveIn(), canFoldCopy(), llvm::SIRegisterInfo::getCompatibleSubRegClass(), hasSubClass(), hasSuperClassEq(), llvm::SIInstrInfo::isBufferSMRD(), and UpdateOperandRegClass().
hasSuperClass()
bool llvm::TargetRegisterClass::hasSuperClass (const TargetRegisterClass * RC) const inline
Return true if the specified TargetRegisterClass is a proper super-class of this TargetRegisterClass.
Definition at line 136 of file TargetRegisterInfo.h.
References hasSubClass().
hasSuperClassEq()
bool llvm::TargetRegisterClass::hasSuperClassEq (const TargetRegisterClass * RC) const inline
Returns true if RC is a super-class of or equal to this class.
Definition at line 141 of file TargetRegisterInfo.h.
References hasSubClassEq().
Referenced by llvm::SIInstrInfo::foldMemoryOperandImpl(), llvm::PPCInstrInfo::getOperandLatency(), isFPR64(), isFRClass(), isGRClass(), llvm::SIInstrInfo::isLegalRegOperand(), llvm::SIRegisterInfo::isProperlyAlignedRC(), isVKClass(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::materializeImmediate(), llvm::SystemZRegisterInfo::shouldCoalesce(), and llvm::X86RegisterInfo::shouldRewriteCopySrc().
isAllocatable()
bool llvm::TargetRegisterClass::isAllocatable () const inline
Return true if this register class may be used to create virtual registers.
Definition at line 120 of file TargetRegisterInfo.h.
References llvm::MCRegisterClass::isAllocatable(), and MC.
Referenced by llvm::MachineRegisterInfo::createVirtualRegister(), llvm::TargetRegisterInfo::getAllocatableClass(), getAllocatableSetForRC(), and llvm::MachineRegisterInfo::setRegClass().
isASubClass()
bool llvm::TargetRegisterClass::isASubClass () const inline
Return true if this TargetRegisterClass is a subset class of at least one other TargetRegisterClass.
Definition at line 185 of file TargetRegisterInfo.h.
References SuperClasses.
Member Data Documentation
AllocationPriority
const uint8_t llvm::TargetRegisterClass::AllocationPriority
Classes with a higher priority value are assigned first by register allocators using a greedy heuristic.
The value is in the range [0,31].
Definition at line 58 of file TargetRegisterInfo.h.
CoveredBySubRegs
const bool llvm::TargetRegisterClass::CoveredBySubRegs
Whether a combination of subregisters can cover every register in the class.
See also the CoveredBySubRegs description in Target.td.
Definition at line 69 of file TargetRegisterInfo.h.
Referenced by llvm::DeadLaneDetector::transferUsedLanes().
GlobalPriority
const bool llvm::TargetRegisterClass::GlobalPriority
Definition at line 61 of file TargetRegisterInfo.h.
HasDisjunctSubRegs
const bool llvm::TargetRegisterClass::HasDisjunctSubRegs
Whether the class supports two (or more) disjunct subregister indices.
Definition at line 66 of file TargetRegisterInfo.h.
Referenced by llvm::ScheduleDAGInstrs::getLaneMaskForMO(), and llvm::MachineRegisterInfo::shouldTrackSubRegLiveness().
LaneMask
const LaneBitmask llvm::TargetRegisterClass::LaneMask
Definition at line 55 of file TargetRegisterInfo.h.
Referenced by getLaneMask(), llvm::rdf::CopyPropagation::run(), and llvm::DeadLaneDetector::transferUsedLanes().
MC
const MCRegisterClass* llvm::TargetRegisterClass::MC
Definition at line 52 of file TargetRegisterInfo.h.
Referenced by begin(), contains(), end(), getCopyCost(), getID(), llvm::TargetRegisterInfo::getMatchingSuperReg(), getNumRegs(), getRegister(), getRegisters(), llvm::SIRegisterInfo::getRegSplitParts(), and isAllocatable().
OrderFunc
ArrayRef<MCPhysReg>(* llvm::TargetRegisterClass::OrderFunc) (const MachineFunction &)
Definition at line 71 of file TargetRegisterInfo.h.
Referenced by getRawAllocationOrder().
SubClassMask
const uint32_t* llvm::TargetRegisterClass::SubClassMask
Definition at line 53 of file TargetRegisterInfo.h.
Referenced by getSubClassMask(), and hasSubClassEq().
SuperClasses
const sc_iterator llvm::TargetRegisterClass::SuperClasses
Definition at line 70 of file TargetRegisterInfo.h.
Referenced by getSuperClasses(), and isASubClass().
SuperRegIndices
const uint16_t* llvm::TargetRegisterClass::SuperRegIndices
Definition at line 54 of file TargetRegisterInfo.h.
Referenced by getSuperRegIndices().
TSFlags
const uint8_t llvm::TargetRegisterClass::TSFlags
Configurable target specific flags.
Definition at line 64 of file TargetRegisterInfo.h.
Referenced by llvm::SIRegisterInfo::hasAGPRs(), llvm::SIRegisterInfo::hasSGPRs(), and llvm::SIRegisterInfo::hasVGPRs().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/TargetRegisterInfo.h