LLVM: llvm::MDString Class Reference
llvm::MDString Class Reference
A single uniqued string.
#include "llvm/IR/Metadata.h"
Public Types
using iterator = StringRef::iterator
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
MDString (const MDString &)=delete
MDString & operator= (MDString &&)=delete
MDString & operator= (const MDString &)=delete
StringRef getString () const
unsigned getLength () const
iterator begin () const
Pointer to the first byte of the string.
iterator end () const
Pointer to one byte past the end of the string.
const unsigned char * bytes_begin () const
const unsigned char * bytes_end () const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static MDString * get (LLVMContext &Context, StringRef Str)
static MDString * get (LLVMContext &Context, const char *Str)
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast.
Friends
class StringMapEntryStorage< MDString >
Additional Inherited Members
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
A single uniqued string.
These are used to efficiently contain a byte sequence for metadata. MDString is always unnamed.
Definition at line 611 of file Metadata.h.
Member Typedef Documentation
iterator
using llvm::MDString::iterator = StringRef::iterator
Definition at line 632 of file Metadata.h.
Constructor & Destructor Documentation
MDString()
llvm::MDString::MDString (const MDString &) delete
Member Function Documentation
begin()
iterator llvm::MDString::begin () const inline
Pointer to the first byte of the string.
Definition at line 635 of file Metadata.h.
References llvm::StringRef::begin(), and getString().
bytes_begin()
const unsigned char* llvm::MDString::bytes_begin () const inline
Definition at line 640 of file Metadata.h.
References llvm::StringRef::bytes_begin(), and getString().
bytes_end()
const unsigned char* llvm::MDString::bytes_end () const inline
Definition at line 641 of file Metadata.h.
References llvm::StringRef::bytes_end(), and getString().
classof()
static bool llvm::MDString::classof (const Metadata * MD) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 644 of file Metadata.h.
References llvm::Metadata::getMetadataID().
end()
iterator llvm::MDString::end () const inline
Pointer to one byte past the end of the string.
Definition at line 638 of file Metadata.h.
References llvm::StringRef::end(), and getString().
get() [1/2]
static MDString* llvm::MDString::get (LLVMContext & Context, const char * Str) inline static
Definition at line 624 of file Metadata.h.
References Context, and get().
get() [2/2]
MDString * MDString::get (LLVMContext & Context, StringRef Str) static
Definition at line 497 of file Metadata.cpp.
References Context, I, llvm::LLVMContextImpl::MDStringCache, llvm::LLVMContext::pImpl, and llvm::SPII::Store.
Referenced by llvm::Module::addModuleFlag(), AddRuntimeUnrollDisableMetaData(), llvm::OpenMPIRBuilder::applySimd(), createMIBNode(), llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), llvm::OpenMPIRBuilder::createOffloadEntry(), llvm::createPGOFuncNameMetadata(), llvm::MDBuilder::createString(), createStringMetadata(), llvm::DIBuilder::createTemplateTemplateParameter(), DisableAllLoopOptsOnLoop(), llvm::embedBufferInModule(), llvm::hlsl::FrontendResource::FrontendResource(), get(), llvm::DINode::getCanonicalMDString(), llvm::DIMacroNode::getCanonicalMDString(), getKeyFPValMD(), getKeyValMD(), INITIALIZE_PASS(), llvm::GCNTTIImpl::instCombineIntrinsic(), LLVMMDStringInContext(), LLVMMDStringInContext2(), llvm::LLParser::parseMDField(), llvm::DICompositeType::replaceElements(), llvm::DICompositeType::replaceTemplateParams(), llvm::SimpleLoopUnswitchPass::run(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::Module::setDarwinTargetVariantTriple(), llvm::Loop::setLoopAlreadyUnrolled(), llvm::Loop::setLoopMustProgress(), llvm::Module::setStackProtectorGuard(), llvm::Module::setStackProtectorGuardReg(), llvm::Module::setStackProtectorGuardSymbol(), llvm::OpenMPIRBuilder::unrollLoopFull(), llvm::OpenMPIRBuilder::unrollLoopHeuristic(), and llvm::OpenMPIRBuilder::unrollLoopPartial().
getLength()
unsigned llvm::MDString::getLength () const inline
Definition at line 630 of file Metadata.h.
References getString(), and llvm::StringRef::size().
getString()
StringRef MDString::getString () const
Definition at line 507 of file Metadata.cpp.
References assert().
Referenced by begin(), llvm::DICompositeType::buildODRType(), bytes_begin(), bytes_end(), llvm::cacheAnnotationFromMD(), createProfileFileNameVar(), llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), end(), getArgAccessQual(), getArgType(), llvm::omp::getDeviceKernels(), llvm::BasicBlock::getIrrLoopHeaderWeight(), getKernelArgTypeQual(), getLength(), llvm::DICompositeType::getODRTypeIfExists(), getSummaryFromMD(), getValMD(), isKeyValuePair(), llvm::LegalizerHelper::lowerReadWriteRegister(), and llvm::Module::setModuleFlag().
operator=() [1/2]
MDString& llvm::MDString::operator= (const MDString &) delete
operator=() [2/2]
MDString& llvm::MDString::operator= (MDString &&) delete
Friends And Related Function Documentation
StringMapEntryStorage< MDString >
friend class StringMapEntryStorage< MDString > friend
Definition at line 612 of file Metadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Metadata.h
lib/IR/Metadata.cpp