LLVM: llvm::ConstantHoistingPass Class Reference
llvm::ConstantHoistingPass Class Reference
#include "llvm/Transforms/Scalar/ConstantHoisting.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
bool runImpl (Function &F, TargetTransformInfo &TTI, DominatorTree &DT, BlockFrequencyInfo *BFI, BasicBlock &Entry, ProfileSummaryInfo *PSI)
Optimize expensive integer constants in the given function.
void cleanup ()
Public Member Functions inherited from llvm::PassInfoMixin< ConstantHoistingPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< ConstantHoistingPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 123 of file ConstantHoisting.h.
Member Function Documentation
cleanup()
void llvm::ConstantHoistingPass::cleanup () inline
Definition at line 132 of file ConstantHoisting.h.
References llvm::SmallVectorImpl< T >::clear().
run()
PreservedAnalyses ConstantHoistingPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 988 of file ConstantHoisting.cpp.
References llvm::PreservedAnalyses::all(), llvm::AMDGPUISD::BFI, ConstHoistWithBlockFrequency, F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserveSet(), and runImpl().
runImpl()
bool ConstantHoistingPass::runImpl (Function & F, TargetTransformInfo & TTI, DominatorTree & DT, BlockFrequencyInfo * BFI, BasicBlock & Entry, ProfileSummaryInfo * PSI)
Optimize expensive integer constants in the given function.
Definition at line 949 of file ConstantHoisting.cpp.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/ConstantHoisting.h
lib/Transforms/Scalar/ConstantHoisting.cpp