LLVM: llvm::orc::ELFDebugObject Class Reference
llvm::orc::ELFDebugObject Class Reference
The current implementation of ELFDebugObject replicates the approach used in RuntimeDyld: It patches executable and data section headers in the given object buffer with load-addresses of their corresponding sections in target memory.
Public Member Functions
void reportSectionTargetMemoryRange (StringRef Name, SectionRange TargetMem) override
StringRef getBuffer () const
Public Member Functions inherited from llvm::orc::DebugObject
DebugObject (JITLinkMemoryManager &MemMgr, const JITLinkDylib *JD, ExecutionSession &ES)
void set (Requirement Req)
bool has (Requirement Req) const
void finalizeAsync (FinalizeContinuation OnFinalize)
virtual ~DebugObject ()
Static Public Member Functions
static Expected< std::unique_ptr< DebugObject > > Create (MemoryBufferRef Buffer, JITLinkContext &Ctx, ExecutionSession &ES)
Protected Member Functions
Expected< SimpleSegmentAlloc > finalizeWorkingMemory () override
template<typename ELFT >
Error recordSection (StringRef Name, std::unique_ptr< ELFDebugObjectSection< ELFT >> Section)
DebugObjectSection * getSection (StringRef Name)
Additional Inherited Members
Public Types inherited from llvm::orc::DebugObject
using FinalizeContinuation = std::function< void(Expected< ExecutorAddrRange >)>
Protected Types inherited from llvm::orc::DebugObject
using InFlightAlloc = JITLinkMemoryManager::InFlightAlloc
using FinalizedAlloc = JITLinkMemoryManager::FinalizedAlloc
Protected Attributes inherited from llvm::orc::DebugObject
JITLinkMemoryManager & MemMgr
const JITLinkDylib * JD = nullptr
Detailed Description
The current implementation of ELFDebugObject replicates the approach used in RuntimeDyld: It patches executable and data section headers in the given object buffer with load-addresses of their corresponding sections in target memory.
Definition at line 194 of file DebugObjectManagerPlugin.cpp.
Member Function Documentation
Create()
Expected< std::unique_ptr< DebugObject > > llvm::orc::ELFDebugObject::Create (MemoryBufferRef Buffer, JITLinkContext & Ctx, ExecutionSession & ES) static
Definition at line 311 of file DebugObjectManagerPlugin.cpp.
References llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, llvm::ELF::ELFDATA2MSB, Endian, llvm::MemoryBufferRef::getBuffer(), llvm::object::getElfArchType(), llvm::jitlink::JITLinkContext::getJITLinkDylib(), and llvm::jitlink::JITLinkContext::getMemoryManager().
finalizeWorkingMemory()
Expected< SimpleSegmentAlloc > llvm::orc::ELFDebugObject::finalizeWorkingMemory () override protected virtual
Implements llvm::orc::DebugObject.
Definition at line 337 of file DebugObjectManagerPlugin.cpp.
References Align, llvm::jitlink::SimpleSegmentAlloc::Create(), llvm::dbgs(), llvm::sys::Process::getPageSizeEstimate(), LLVM_DEBUG, memcpy(), and PageSize.
getBuffer()
StringRef llvm::orc::ELFDebugObject::getBuffer () const inline
Definition at line 202 of file DebugObjectManagerPlugin.cpp.
References llvm::MemoryBufferRef::getBuffer().
getSection()
DebugObjectSection * llvm::orc::ELFDebugObject::getSection (StringRef Name) protected
Definition at line 383 of file DebugObjectManagerPlugin.cpp.
recordSection()
template<typename ELFT > Error llvm::orc::ELFDebugObject::recordSection (StringRef Name, std::unique_ptr< ELFDebugObjectSection< ELFT >> Section) protected
Definition at line 370 of file DebugObjectManagerPlugin.cpp.
reportSectionTargetMemoryRange()
void llvm::orc::ELFDebugObject::reportSectionTargetMemoryRange (StringRef Name, SectionRange TargetMem) override virtual
Reimplemented from llvm::orc::DebugObject.
Definition at line 363 of file DebugObjectManagerPlugin.cpp.
References llvm::object::getSection().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/DebugObjectManagerPlugin.cpp