LLVM: llvm::MCSymbolRefExpr Class Reference
llvm::MCSymbolRefExpr Class Reference
Represent a reference to a symbol from inside an expression.
#include "llvm/MC/MCExpr.h"
Public Types
enum VariantKind : uint16_t {
VK_None, VK_Invalid, VK_GOT, VK_GOTOFF,
VK_GOTREL, VK_PCREL, VK_GOTPCREL, VK_GOTPCREL_NORELAX,
VK_GOTTPOFF, VK_INDNTPOFF, VK_NTPOFF, VK_GOTNTPOFF,
VK_PLT, VK_TLSGD, VK_TLSLD, VK_TLSLDM,
VK_TPOFF, VK_DTPOFF, VK_TLSCALL, VK_TLSDESC,
VK_TLVP, VK_TLVPPAGE, VK_TLVPPAGEOFF, VK_PAGE,
VK_PAGEOFF, VK_GOTPAGE, VK_GOTPAGEOFF, VK_SECREL,
VK_SIZE, VK_WEAKREF, VK_X86_ABS8, VK_X86_PLTOFF,
VK_ARM_NONE, VK_ARM_GOT_PREL, VK_ARM_TARGET1, VK_ARM_TARGET2,
VK_ARM_PREL31, VK_ARM_SBREL, VK_ARM_TLSLDO, VK_ARM_TLSDESCSEQ,
VK_AVR_NONE, VK_AVR_LO8, VK_AVR_HI8, VK_AVR_HLO8,
VK_AVR_DIFF8, VK_AVR_DIFF16, VK_AVR_DIFF32, VK_AVR_PM,
VK_PPC_LO, VK_PPC_HI, VK_PPC_HA, VK_PPC_HIGH,
VK_PPC_HIGHA, VK_PPC_HIGHER, VK_PPC_HIGHERA, VK_PPC_HIGHEST,
VK_PPC_HIGHESTA, VK_PPC_GOT_LO, VK_PPC_GOT_HI, VK_PPC_GOT_HA,
VK_PPC_TOCBASE, VK_PPC_TOC, VK_PPC_TOC_LO, VK_PPC_TOC_HI,
VK_PPC_TOC_HA, VK_PPC_U, VK_PPC_L, VK_PPC_DTPMOD,
VK_PPC_TPREL_LO, VK_PPC_TPREL_HI, VK_PPC_TPREL_HA, VK_PPC_TPREL_HIGH,
VK_PPC_TPREL_HIGHA, VK_PPC_TPREL_HIGHER, VK_PPC_TPREL_HIGHERA, VK_PPC_TPREL_HIGHEST,
VK_PPC_TPREL_HIGHESTA, VK_PPC_DTPREL_LO, VK_PPC_DTPREL_HI, VK_PPC_DTPREL_HA,
VK_PPC_DTPREL_HIGH, VK_PPC_DTPREL_HIGHA, VK_PPC_DTPREL_HIGHER, VK_PPC_DTPREL_HIGHERA,
VK_PPC_DTPREL_HIGHEST, VK_PPC_DTPREL_HIGHESTA, VK_PPC_GOT_TPREL, VK_PPC_GOT_TPREL_LO,
VK_PPC_GOT_TPREL_HI, VK_PPC_GOT_TPREL_HA, VK_PPC_GOT_DTPREL, VK_PPC_GOT_DTPREL_LO,
VK_PPC_GOT_DTPREL_HI, VK_PPC_GOT_DTPREL_HA, VK_PPC_TLS, VK_PPC_GOT_TLSGD,
VK_PPC_GOT_TLSGD_LO, VK_PPC_GOT_TLSGD_HI, VK_PPC_GOT_TLSGD_HA, VK_PPC_TLSGD,
VK_PPC_AIX_TLSGD, VK_PPC_AIX_TLSGDM, VK_PPC_GOT_TLSLD, VK_PPC_GOT_TLSLD_LO,
VK_PPC_GOT_TLSLD_HI, VK_PPC_GOT_TLSLD_HA, VK_PPC_GOT_PCREL, VK_PPC_GOT_TLSGD_PCREL,
VK_PPC_GOT_TLSLD_PCREL, VK_PPC_GOT_TPREL_PCREL, VK_PPC_TLS_PCREL, VK_PPC_TLSLD,
VK_PPC_LOCAL, VK_PPC_NOTOC, VK_PPC_PCREL_OPT, VK_COFF_IMGREL32,
VK_Hexagon_LO16, VK_Hexagon_HI16, VK_Hexagon_GPREL, VK_Hexagon_GD_GOT,
VK_Hexagon_LD_GOT, VK_Hexagon_GD_PLT, VK_Hexagon_LD_PLT, VK_Hexagon_IE,
VK_Hexagon_IE_GOT, VK_WASM_TYPEINDEX, VK_WASM_TLSREL, VK_WASM_MBREL,
VK_WASM_TBREL, VK_WASM_GOT_TLS, VK_AMDGPU_GOTPCREL32_LO, VK_AMDGPU_GOTPCREL32_HI,
VK_AMDGPU_REL32_LO, VK_AMDGPU_REL32_HI, VK_AMDGPU_REL64, VK_AMDGPU_ABS32_LO,
VK_AMDGPU_ABS32_HI, VK_VE_HI32, VK_VE_LO32, VK_VE_PC_HI32,
VK_VE_PC_LO32, VK_VE_GOT_HI32, VK_VE_GOT_LO32, VK_VE_GOTOFF_HI32,
VK_VE_GOTOFF_LO32, VK_VE_PLT_HI32, VK_VE_PLT_LO32, VK_VE_TLS_GD_HI32,
VK_VE_TLS_GD_LO32, VK_VE_TPOFF_HI32, VK_VE_TPOFF_LO32, VK_TPREL,
VK_DTPREL
}
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
Accessors
const MCSymbol & getSymbol () const
VariantKind getKind () const
bool hasSubsectionsViaSymbols () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const MCSymbolRefExpr * create (const MCSymbol *Symbol, MCContext &Ctx)
static const MCSymbolRefExpr * create (const MCSymbol *Symbol, VariantKind Kind, MCContext &Ctx, SMLoc Loc=SMLoc())
static const MCSymbolRefExpr * create (StringRef Name, VariantKind Kind, MCContext &Ctx)
Static Utility Functions
static StringRef getVariantKindName (VariantKind Kind)
static VariantKind getVariantKindForName (StringRef Name)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Represent a reference to a symbol from inside an expression.
A symbol reference in an expression may be a use of a label, a use of an assembler variable (defined constant), or constitute an implicit definition of the symbol as external.
Definition at line 192 of file MCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::MCSymbolRefExpr::VariantKind : uint16_t
Enumerator
VK_None
VK_Invalid
VK_GOT
VK_GOTOFF
VK_GOTREL
VK_PCREL
VK_GOTPCREL
VK_GOTPCREL_NORELAX
VK_GOTTPOFF
VK_INDNTPOFF
VK_NTPOFF
VK_GOTNTPOFF
VK_PLT
VK_TLSGD
VK_TLSLD
VK_TLSLDM
VK_TPOFF
VK_DTPOFF
VK_TLSCALL
VK_TLSDESC
VK_TLVP
VK_TLVPPAGE
VK_TLVPPAGEOFF
VK_PAGE
VK_PAGEOFF
VK_GOTPAGE
VK_GOTPAGEOFF
VK_SECREL
VK_SIZE
VK_WEAKREF
VK_X86_ABS8
VK_X86_PLTOFF
VK_ARM_NONE
VK_ARM_GOT_PREL
VK_ARM_TARGET1
VK_ARM_TARGET2
VK_ARM_PREL31
VK_ARM_SBREL
VK_ARM_TLSLDO
VK_ARM_TLSDESCSEQ
VK_AVR_NONE
VK_AVR_LO8
VK_AVR_HI8
VK_AVR_HLO8
VK_AVR_DIFF8
VK_AVR_DIFF16
VK_AVR_DIFF32
VK_AVR_PM
VK_PPC_LO
VK_PPC_HI
VK_PPC_HA
VK_PPC_HIGH
VK_PPC_HIGHA
VK_PPC_HIGHER
VK_PPC_HIGHERA
VK_PPC_HIGHEST
VK_PPC_HIGHESTA
VK_PPC_GOT_LO
VK_PPC_GOT_HI
VK_PPC_GOT_HA
VK_PPC_TOCBASE
VK_PPC_TOC
VK_PPC_TOC_LO
VK_PPC_TOC_HI
VK_PPC_TOC_HA
VK_PPC_U
VK_PPC_L
VK_PPC_DTPMOD
VK_PPC_TPREL_LO
VK_PPC_TPREL_HI
VK_PPC_TPREL_HA
VK_PPC_TPREL_HIGH
VK_PPC_TPREL_HIGHA
VK_PPC_TPREL_HIGHER
VK_PPC_TPREL_HIGHERA
VK_PPC_TPREL_HIGHEST
VK_PPC_TPREL_HIGHESTA
VK_PPC_DTPREL_LO
VK_PPC_DTPREL_HI
VK_PPC_DTPREL_HA
VK_PPC_DTPREL_HIGH
VK_PPC_DTPREL_HIGHA
VK_PPC_DTPREL_HIGHER
VK_PPC_DTPREL_HIGHERA
VK_PPC_DTPREL_HIGHEST
VK_PPC_DTPREL_HIGHESTA
VK_PPC_GOT_TPREL
VK_PPC_GOT_TPREL_LO
VK_PPC_GOT_TPREL_HI
VK_PPC_GOT_TPREL_HA
VK_PPC_GOT_DTPREL
VK_PPC_GOT_DTPREL_LO
VK_PPC_GOT_DTPREL_HI
VK_PPC_GOT_DTPREL_HA
VK_PPC_TLS
VK_PPC_GOT_TLSGD
VK_PPC_GOT_TLSGD_LO
VK_PPC_GOT_TLSGD_HI
VK_PPC_GOT_TLSGD_HA
VK_PPC_TLSGD
VK_PPC_AIX_TLSGD
VK_PPC_AIX_TLSGDM
VK_PPC_GOT_TLSLD
VK_PPC_GOT_TLSLD_LO
VK_PPC_GOT_TLSLD_HI
VK_PPC_GOT_TLSLD_HA
VK_PPC_GOT_PCREL
VK_PPC_GOT_TLSGD_PCREL
VK_PPC_GOT_TLSLD_PCREL
VK_PPC_GOT_TPREL_PCREL
VK_PPC_TLS_PCREL
VK_PPC_TLSLD
VK_PPC_LOCAL
VK_PPC_NOTOC
VK_PPC_PCREL_OPT
VK_COFF_IMGREL32
VK_Hexagon_LO16
VK_Hexagon_HI16
VK_Hexagon_GPREL
VK_Hexagon_GD_GOT
VK_Hexagon_LD_GOT
VK_Hexagon_GD_PLT
VK_Hexagon_LD_PLT
VK_Hexagon_IE
VK_Hexagon_IE_GOT
VK_WASM_TYPEINDEX
VK_WASM_TLSREL
VK_WASM_MBREL
VK_WASM_TBREL
VK_WASM_GOT_TLS
VK_AMDGPU_GOTPCREL32_LO
VK_AMDGPU_GOTPCREL32_HI
VK_AMDGPU_REL32_LO
VK_AMDGPU_REL32_HI
VK_AMDGPU_REL64
VK_AMDGPU_ABS32_LO
VK_AMDGPU_ABS32_HI
VK_VE_HI32
VK_VE_LO32
VK_VE_PC_HI32
VK_VE_PC_LO32
VK_VE_GOT_HI32
VK_VE_GOT_LO32
VK_VE_GOTOFF_HI32
VK_VE_GOTOFF_LO32
VK_VE_PLT_HI32
VK_VE_PLT_LO32
VK_VE_TLS_GD_HI32
VK_VE_TLS_GD_LO32
VK_VE_TPOFF_HI32
VK_VE_TPOFF_LO32
VK_TPREL
VK_DTPREL
Definition at line 194 of file MCExpr.h.
Member Function Documentation
classof()
static bool llvm::MCSymbolRefExpr::classof (const MCExpr * E) inline static
Definition at line 419 of file MCExpr.h.
References E, and llvm::MCExpr::SymbolRef.
create() [1/3]
static const MCSymbolRefExpr* llvm::MCSymbolRefExpr::create (const MCSymbol * Symbol, MCContext & Ctx) inline static
Definition at line 386 of file MCExpr.h.
References VK_None.
Referenced by llvm::CSKYConstantPool::addEntry(), llvm::ConstantPool::addEntry(), ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfoForSegment(), ARMEmitRuntimeFunction(), ARMEmitUnwindInfo(), buildSymbolDiff(), createGOTRelExprOp(), createPCXRelExprOp(), createSparcMCOperand(), createVEMCOperand(), llvm::AsmPrinter::doFinalization(), EmitAbsDifference(), llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitAbsoluteSymbolDiffAsULEB128(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::TargetLoweringObjectFile::emitCGProfileMetadata(), llvm::MCWinCOFFStreamer::emitCOFFImgRel32(), llvm::MCWinCOFFStreamer::emitCOFFSecRel32(), llvm::MCWinCOFFStreamer::emitCOFFSectionIndex(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), emitDirectiveRelocJalr(), llvm::CodeViewContext::emitFileChecksumOffset(), llvm::AsmPrinter::emitFunctionBody(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGenDwarfRanges(), llvm::AMDGPUTargetELFStreamer::EmitHSAMetadata(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::AMDGPUTargetELFStreamer::EmitISAVersion(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), llvm::AsmPrinter::emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), llvm::X86AsmPrinter::emitKCFITypeId(), llvm::AsmPrinter::emitLabelPlusOffset(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), emitNonLazySymbolPointer(), EmitNop(), llvm::MCObjectStreamer::emitRelocDirective(), EmitRuntimeFunction(), llvm::HexagonAsmPrinter::EmitSled(), EmitSymbolRefWithOfs(), llvm::MCStreamer::emitSymbolValue(), EmitUnwindInfo(), llvm::AVRMCELFStreamer::emitValueForModiferKind(), llvm::MCWasmStreamer::emitWeakReference(), llvm::MCELFStreamer::emitWeakReference(), llvm::MCWinCOFFStreamer::emitWeakReference(), llvm::AsmPrinter::emitXRayTable(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::CodeViewContext::encodeDefRange(), llvm::WasmException::endFunction(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::RecordStreamer::flushSymverDirectives(), forceExpAbs(), llvm::ARMElfTargetObjectFile::getDebugThreadLocalSymbol(), llvm::MipsTargetObjectFile::getDebugThreadLocalSymbol(), llvm::X86ELFTargetObjectFile::getDebugThreadLocalSymbol(), llvm::TargetLoweringObjectFile::getDebugThreadLocalSymbol(), llvm::SystemZMCInstLower::getExpr(), llvm::RISCVMCAsmInfo::getExprForFDESymbol(), llvm::SparcELFMCAsmInfo::getExprForFDESymbol(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::SparcELFMCAsmInfo::getExprForPersonalitySymbol(), llvm::X86_64MCAsmInfoDarwin::getExprForPersonalitySymbol(), getGlobalOffsetTable(), llvm::X86_64MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::ARMElfTargetObjectFile::getIndirectSymViaRWPI(), GetOptionalAbsDifference(), llvm::M68kTargetLowering::getPICJumpTableRelocBaseExpr(), llvm::X86TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), llvm::TargetLowering::getPICJumpTableRelocBaseExpr(), GetSubDivExpr(), GetSymbolRef(), getTLSGetOffset(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::SIInstrInfo::insertIndirectBranch(), llvm::MSP430MCInstLower::Lower(), llvm::BPFMCInstLower::Lower(), llvm::LanaiMCInstLower::Lower(), llvm::AVRAsmPrinter::lowerConstant(), llvm::AsmPrinter::lowerConstant(), llvm::VETargetLowering::LowerCustomJumpTableEntry(), llvm::M68kTargetLowering::LowerCustomJumpTableEntry(), llvm::RISCVTargetLowering::LowerCustomJumpTableEntry(), llvm::X86TargetLowering::LowerCustomJumpTableEntry(), llvm::TargetLoweringObjectFileELF::lowerDSOLocalEquivalent(), llvm::AVRMCInstLower::lowerInstruction(), llvm::CSKYMCInstLower::lowerOperand(), llvm::AArch64MCInstLower::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineOperandToMCOperand(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileCOFF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), lowerSymbolOperand(), LowerSymbolOperand(), llvm::CSKYMCInstLower::lowerSymbolOperand(), llvm::AVRMCInstLower::lowerSymbolOperand(), llvm::BPFMCInstLower::LowerSymbolOperand(), llvm::LanaiMCInstLower::LowerSymbolOperand(), llvm::MSP430MCInstLower::LowerSymbolOperand(), llvm::M68kMCInstLower::LowerSymbolOperand(), llvm::AArch64MCInstLower::lowerSymbolOperandCOFF(), llvm::AArch64MCInstLower::lowerSymbolOperandDarwin(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), makeStartPlusIntExpr(), llvm::MCAsmParserExtension::ParseDirectiveCGProfile(), llvm::FaultMaps::recordFaultingOp(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), llvm::MCExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::AMDGPUSymbolizer::tryAddingSymbolicOperand().
create() [2/3]
const MCSymbolRefExpr * MCSymbolRefExpr::create (const MCSymbol * Symbol, VariantKind Kind, MCContext & Ctx, SMLoc Loc = SMLoc()) static
Definition at line 210 of file MCExpr.cpp.
create() [3/3]
const MCSymbolRefExpr * MCSymbolRefExpr::create (StringRef Name, VariantKind Kind, MCContext & Ctx) static
Definition at line 216 of file MCExpr.cpp.
getKind()
VariantKind llvm::MCSymbolRefExpr::getKind () const inline
Definition at line 401 of file MCExpr.h.
References llvm::MCExpr::getSubclassData().
Referenced by llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), fixELFSymbolsInTLSFixupsImpl(), llvm::PPCMCCodeEmitter::getDispRI34PCRelEncoding(), llvm::PPCMCCodeEmitter::getTLSRegEncoding(), llvm::isPartOfGOTToPCRelPair(), needsExpandMemInst(), llvm::MCExpr::print(), printExpr(), llvm::PPCInstPrinter::printInst(), llvm::PPCInstPrinter::printTLSCall(), and shouldBeSls().
getSymbol()
const MCSymbol& llvm::MCSymbolRefExpr::getSymbol () const inline
Definition at line 399 of file MCExpr.h.
Referenced by llvm::MCWinCOFFStreamer::emitCGProfileEntry(), llvm::MCObjectStreamer::emitRelocDirective(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::MCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), EvaluateCRExpr(), llvm::MCWinCOFFStreamer::finalizeCGProfileEntry(), llvm::MCExpr::findAssociatedFragment(), fixELFSymbolsInTLSFixupsImpl(), llvm::MCAsmLayout::getBaseSymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), getOffsetAndDataFragment(), llvm::RISCVMCExpr::getPCRelHiFixup(), handleIndirectSymViaGOTPCRel(), hasGOTReference(), llvm::MCExpr::print(), printExpr(), llvm::PPCInstPrinter::printInst(), llvm::PPCInstPrinter::printTLSCall(), llvm::WebAssemblyAsmTypeCheck::typeCheck(), and llvm::MachObjectWriter::writeObject().
getVariantKindForName()
MCSymbolRefExpr::VariantKind MCSymbolRefExpr::getVariantKindForName (StringRef Name) static
Definition at line 389 of file MCExpr.cpp.
getVariantKindName()
StringRef MCSymbolRefExpr::getVariantKindName (VariantKind Kind) static
Definition at line 221 of file MCExpr.cpp.
Referenced by llvm::MCExpr::print(), and llvm::PPCInstPrinter::printTLSCall().
hasSubsectionsViaSymbols()
bool llvm::MCSymbolRefExpr::hasSubsectionsViaSymbols () const inline
Definition at line 405 of file MCExpr.h.
References llvm::MCExpr::getSubclassData().
Referenced by llvm::MCExpr::evaluateAsRelocatableImpl().
The documentation for this class was generated from the following files:
include/llvm/MC/MCExpr.h
lib/MC/MCExpr.cpp