LLVM: llvm::SymbolTableListTraits< ValueSubClass > Class Template Reference
llvm::SymbolTableListTraits< ValueSubClass > Class Template Reference
#include "llvm/IR/GlobalAlias.h"
Public Member Functions
SymbolTableListTraits ()=default
void addNodeToList (ValueSubClass *V)
void removeNodeFromList (ValueSubClass *V)
void transferNodesFromList (SymbolTableListTraits &L2, iterator first, iterator last)
template<typename TPtr >
void setSymTabObject (TPtr *, TPtr)
setSymTabObject - This is called when (f.e.) the parent of a basic block changes.
Static Public Member Functions
static ValueSymbolTable * toPtr (ValueSymbolTable *P)
static ValueSymbolTable * toPtr (ValueSymbolTable &R)
Detailed Description
template<typename ValueSubClass>
class llvm::SymbolTableListTraits< ValueSubClass >
Definition at line 26 of file GlobalAlias.h.
Constructor & Destructor Documentation
SymbolTableListTraits()
template<typename ValueSubClass > llvm::SymbolTableListTraits< ValueSubClass >::SymbolTableListTraits () default
Member Function Documentation
addNodeToList()
template<typename ValueSubClass > void llvm::SymbolTableListTraits< ValueSubClass >::addNodeToList (ValueSubClass * V)
Definition at line 68 of file SymbolTableListTraitsImpl.h.
References assert(), getSymTab(), llvm::invalidateParentIListOrdering(), and llvm::ARM_MB::ST.
removeNodeFromList()
template<typename ValueSubClass > void llvm::SymbolTableListTraits< ValueSubClass >::removeNodeFromList (ValueSubClass * V)
Definition at line 79 of file SymbolTableListTraitsImpl.h.
References getSymTab(), and llvm::ARM_MB::ST.
setSymTabObject()
template<typename ValueSubClass > template<typename TPtr > void llvm::SymbolTableListTraits< ValueSubClass >::setSymTabObject (TPtr * Dest, TPtr Src)
setSymTabObject - This is called when (f.e.) the parent of a basic block changes.
This requires us to remove all the instruction symtab entries from the current function and reinsert them into the new function.
Definition at line 33 of file SymbolTableListTraitsImpl.h.
References getSymTab(), and I.
toPtr() [1/2]
template<typename ValueSubClass > static ValueSymbolTable* llvm::SymbolTableListTraits< ValueSubClass >::toPtr (ValueSymbolTable & R) inline static
Definition at line 105 of file SymbolTableListTraits.h.
toPtr() [2/2]
template<typename ValueSubClass > static ValueSymbolTable* llvm::SymbolTableListTraits< ValueSubClass >::toPtr (ValueSymbolTable * P) inline static
Definition at line 104 of file SymbolTableListTraits.h.
References P.
transferNodesFromList()
template<typename ValueSubClass > void llvm::SymbolTableListTraits< ValueSubClass >::transferNodesFromList (SymbolTableListTraits< ValueSubClass > & L2, iterator first, iterator last)
Definition at line 88 of file SymbolTableListTraitsImpl.h.
References getSymTab(), llvm::invalidateParentIListOrdering(), L2, and llvm::binaryformat::last.
The documentation for this class was generated from the following files:
include/llvm/IR/GlobalAlias.h
include/llvm/IR/SymbolTableListTraits.h
lib/IR/SymbolTableListTraitsImpl.h