LLVM: llvm::mca::InOrderIssueStage Class Reference
llvm::mca::InOrderIssueStage Class Reference final
#include "llvm/MCA/Stages/InOrderIssueStage.h"
Public Member Functions
InOrderIssueStage (const MCSubtargetInfo &STI, RegisterFile &PRF, CustomBehaviour &CB, LSUnit &LSU)
unsigned getIssueWidth () const
bool isAvailable (const InstRef &) const override
Returns true if it can execute IR during this cycle.
bool hasWorkToComplete () const override
Returns true if some instructions are still executing this stage.
Error execute (InstRef &IR) override
The primary action that this stage performs on instruction IR.
Error cycleStart () override
Called once at the start of each cycle.
Error cycleEnd () override
Called once at the end of each cycle.
Public Member Functions inherited from llvm::mca::Stage
Stage ()
virtual ~Stage ()
virtual Error cycleResume ()
Called after the pipeline is resumed from pausing state.
void setNextInSequence (Stage *NextStage)
bool checkNextStage (const InstRef &IR) const
Error moveToTheNextStage (InstRef &IR)
Called when an instruction is ready to move the next pipeline stage.
void addListener (HWEventListener *Listener)
Add a listener to receive callbacks during the execution of this stage.
template<typename EventT >
void notifyEvent (const EventT &Event) const
Notify listeners of a particular hardware event.
Additional Inherited Members
Protected Member Functions inherited from llvm::mca::Stage
const std::set< HWEventListener * > & getListeners () const
Detailed Description
Definition at line 54 of file InOrderIssueStage.h.
Constructor & Destructor Documentation
InOrderIssueStage()
llvm::mca::InOrderIssueStage::InOrderIssueStage (const MCSubtargetInfo & STI, RegisterFile & PRF, CustomBehaviour & CB, LSUnit & LSU)
Definition at line 46 of file InOrderIssueStage.cpp.
Member Function Documentation
cycleEnd()
llvm::Error llvm::mca::InOrderIssueStage::cycleEnd () override virtual
Called once at the end of each cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 423 of file InOrderIssueStage.cpp.
References llvm::mca::StallInfo::cycleEnd(), and llvm::mca::RegisterFile::cycleEnd().
cycleStart()
llvm::Error llvm::mca::InOrderIssueStage::cycleStart () override virtual
Called once at the start of each cycle.
This can be used as a setup phase to prepare for the executions during the cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 381 of file InOrderIssueStage.cpp.
References assert(), llvm::mca::StallInfo::clear(), llvm::mca::LSUnitBase::cycleEvent(), llvm::mca::ResourceManager::cycleEvent(), llvm::mca::RegisterFile::cycleStart(), E, llvm::mca::StallInfo::getCyclesLeft(), llvm::mca::StallInfo::getInstruction(), getIssueWidth(), IR, and llvm::mca::StallInfo::isValid().
execute()
llvm::Error llvm::mca::InOrderIssueStage::execute (InstRef & IR) override virtual
The primary action that this stage performs on instruction IR.
Implements llvm::mca::Stage.
Definition at line 198 of file InOrderIssueStage.cpp.
References llvm::mca::LSUnit::dispatch(), E, IR, llvm::mca::InstructionBase::isMemOp(), llvm::mca::StallInfo::isValid(), and llvm::mca::Instruction::setLSUTokenID().
getIssueWidth()
unsigned llvm::mca::InOrderIssueStage::getIssueWidth () const
Definition at line 52 of file InOrderIssueStage.cpp.
References llvm::MCSubtargetInfo::getSchedModel(), and llvm::MCSchedModel::IssueWidth.
Referenced by cycleStart(), and isAvailable().
hasWorkToComplete()
bool llvm::mca::InOrderIssueStage::hasWorkToComplete () const override virtual
Returns true if some instructions are still executing this stage.
Implements llvm::mca::Stage.
Definition at line 56 of file InOrderIssueStage.cpp.
References llvm::mca::StallInfo::isValid().
isAvailable()
bool llvm::mca::InOrderIssueStage::isAvailable (const InstRef & IR) const override virtual
Returns true if it can execute IR during this cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 60 of file InOrderIssueStage.cpp.
References llvm::mca::InstructionBase::getBeginGroup(), getIssueWidth(), llvm::mca::InstructionBase::getNumMicroOps(), IR, and llvm::mca::StallInfo::isValid().
The documentation for this class was generated from the following files:
include/llvm/MCA/Stages/InOrderIssueStage.h
lib/MCA/Stages/InOrderIssueStage.cpp