LLVM: LiveDebugValues::SpillLocationNo Class Reference
LiveDebugValues::SpillLocationNo Class Reference
Thin wrapper around an integer – designed to give more type safety to spill location numbers.
#include "CodeGen/LiveDebugValues/InstrRefBasedImpl.h"
Public Member Functions
SpillLocationNo (unsigned SpillNo)
unsigned id () const
bool operator< (const SpillLocationNo &Other) const
bool operator== (const SpillLocationNo &Other) const
bool operator!= (const SpillLocationNo &Other) const
Public Attributes
unsigned SpillNo
Detailed Description
Thin wrapper around an integer – designed to give more type safety to spill location numbers.
Definition at line 216 of file InstrRefBasedImpl.h.
Constructor & Destructor Documentation
SpillLocationNo()
LiveDebugValues::SpillLocationNo::SpillLocationNo (unsigned SpillNo) inline explicit
Definition at line 218 of file InstrRefBasedImpl.h.
Member Function Documentation
id()
unsigned LiveDebugValues::SpillLocationNo::id () const inline
Definition at line 220 of file InstrRefBasedImpl.h.
Referenced by LiveDebugValues::MLocTracker::emitLoc(), LiveDebugValues::MLocTracker::getLocID(), LiveDebugValues::MLocTracker::getOrTrackSpillLoc(), and LiveDebugValues::MLocTracker::getSpillIDWithIdx().
operator!=()
bool LiveDebugValues::SpillLocationNo::operator!= (const SpillLocationNo & Other) const inline
Definition at line 229 of file InstrRefBasedImpl.h.
References Other.
operator<()
bool LiveDebugValues::SpillLocationNo::operator< (const SpillLocationNo & Other) const inline
Definition at line 222 of file InstrRefBasedImpl.h.
References Other.
operator==()
bool LiveDebugValues::SpillLocationNo::operator== (const SpillLocationNo & Other) const inline
Definition at line 226 of file InstrRefBasedImpl.h.
References Other.
Member Data Documentation
SpillNo
unsigned LiveDebugValues::SpillLocationNo::SpillNo
Definition at line 219 of file InstrRefBasedImpl.h.
The documentation for this class was generated from the following file:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.h