LLVM: llvm::objcopy::elf::OwnedDataSection Class Reference
llvm::objcopy::elf::OwnedDataSection Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
OwnedDataSection (StringRef SecName, ArrayRef< uint8_t > Data)
OwnedDataSection (const Twine &SecName, uint64_t SecAddr, uint64_t SecFlags, uint64_t SecOff)
OwnedDataSection (SectionBase &S, ArrayRef< uint8_t > Data)
void appendHexData (StringRef HexData)
Error accept (SectionVisitor &Sec) const override
Error accept (MutableSectionVisitor &Visitor) override
bool hasContents () const override
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual Error initialize (SectionTableRef SecTable)
virtual void finalize ()
virtual Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove)
virtual Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove)
virtual void markSymbols ()
virtual void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &)
virtual void onRemove ()
Additional Inherited Members
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Detailed Description
Definition at line 502 of file ELFObject.h.
Constructor & Destructor Documentation
OwnedDataSection() [1/3]
llvm::objcopy::elf::OwnedDataSection::OwnedDataSection (StringRef SecName, ArrayRef< uint8_t > Data) inline
Definition at line 508 of file ELFObject.h.
References llvm::Data, llvm::max(), llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::elf::SectionBase::OriginalOffset, llvm::objcopy::elf::SectionBase::OriginalType, llvm::ELF::SHT_PROGBITS, llvm::objcopy::elf::SectionBase::Size, and llvm::StringRef::str().
OwnedDataSection() [2/3]
llvm::objcopy::elf::OwnedDataSection::OwnedDataSection (const Twine & SecName, uint64_t SecAddr, uint64_t SecFlags, uint64_t SecOff) inline
Definition at line 516 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::Addr, llvm::objcopy::elf::SectionBase::Flags, llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::elf::SectionBase::OriginalFlags, llvm::objcopy::elf::SectionBase::OriginalOffset, llvm::objcopy::elf::SectionBase::OriginalType, llvm::ELF::SHT_PROGBITS, and llvm::Twine::str().
OwnedDataSection() [3/3]
llvm::objcopy::elf::OwnedDataSection::OwnedDataSection (SectionBase & S, ArrayRef< uint8_t > Data) inline
Definition at line 525 of file ELFObject.h.
References llvm::Data, and llvm::objcopy::elf::SectionBase::Size.
Member Function Documentation
accept() [1/2]
Error OwnedDataSection::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 491 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error OwnedDataSection::accept (SectionVisitor & Sec) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 487 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
appendHexData()
void OwnedDataSection::appendHexData (StringRef HexData)
Definition at line 495 of file ELFObject.cpp.
References assert(), llvm::Data, llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::StringRef::size(), and llvm::StringRef::take_front().
hasContents()
bool llvm::objcopy::elf::OwnedDataSection::hasContents () const inline override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 533 of file ELFObject.h.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp