LLVM: llvm::memprof::FrameWriterTrait Class Reference
llvm::memprof::FrameWriterTrait Class Reference
#include "llvm/ProfileData/MemProf.h"
Public Types
using key_type = FrameId
using key_type_ref = FrameId
using data_type = Frame
using data_type_ref = Frame &
using hash_value_type = FrameId
using offset_type = uint64_t
Public Member Functions
void EmitKey (raw_ostream &Out, key_type_ref K, offset_type)
void EmitData (raw_ostream &Out, key_type_ref, data_type_ref V, offset_type)
Static Public Member Functions
static hash_value_type ComputeHash (key_type_ref K)
static std::pair< offset_type, offset_type > EmitKeyDataLength (raw_ostream &Out, key_type_ref K, data_type_ref V)
Detailed Description
Definition at line 539 of file MemProf.h.
Member Typedef Documentation
data_type
using llvm::memprof::FrameWriterTrait::data_type = Frame
Definition at line 544 of file MemProf.h.
data_type_ref
using llvm::memprof::FrameWriterTrait::data_type_ref = Frame &
Definition at line 545 of file MemProf.h.
hash_value_type
using llvm::memprof::FrameWriterTrait::hash_value_type = FrameId
Definition at line 547 of file MemProf.h.
key_type
using llvm::memprof::FrameWriterTrait::key_type = FrameId
Definition at line 541 of file MemProf.h.
key_type_ref
using llvm::memprof::FrameWriterTrait::key_type_ref = FrameId
Definition at line 542 of file MemProf.h.
offset_type
using llvm::memprof::FrameWriterTrait::offset_type = uint64_t
Definition at line 548 of file MemProf.h.
Member Function Documentation
ComputeHash()
static hash_value_type llvm::memprof::FrameWriterTrait::ComputeHash (key_type_ref K) inline static
Definition at line 550 of file MemProf.h.
EmitData()
void llvm::memprof::FrameWriterTrait::EmitData (raw_ostream & Out, key_type_ref , data_type_ref V, offset_type) inline
Definition at line 569 of file MemProf.h.
References llvm::memprof::Frame::serialize().
EmitKey()
void llvm::memprof::FrameWriterTrait::EmitKey (raw_ostream & Out, key_type_ref K, offset_type) inline
Definition at line 563 of file MemProf.h.
References llvm::AArch64CC::LE, llvm::support::little, and support().
EmitKeyDataLength()
static std::pair<offset_type, offset_type> llvm::memprof::FrameWriterTrait::EmitKeyDataLength (raw_ostream & Out, key_type_ref K, data_type_ref V) inline static
Definition at line 553 of file MemProf.h.
References llvm::AArch64CC::LE, llvm::support::little, M, N, llvm::memprof::Frame::serializedSize(), and support().
The documentation for this class was generated from the following file:
include/llvm/ProfileData/MemProf.h