LLVM: llvm::vfs::FileSystem Class Reference
llvm::vfs::FileSystem Class Reference abstract
The virtual file system interface.
#include "llvm/Support/VirtualFileSystem.h"
Public Types
enum PrintType { PrintType::Summary, PrintType::Contents, PrintType::RecursiveContents }
Public Member Functions
virtual ~FileSystem ()
virtual llvm::ErrorOr< Status > status (const Twine &Path)=0
Get the status of the entry at Path, if one exists.
virtual llvm::ErrorOr< std::unique_ptr< File > > openFileForRead (const Twine &Path)=0
Get a File object for the file at Path, if one exists.
llvm::ErrorOr< std::unique_ptr< llvm::MemoryBuffer > > getBufferForFile (const Twine &Name, int64_t FileSize=-1, bool RequiresNullTerminator=true, bool IsVolatile=false)
This is a convenience method that opens a file, gets its content and then closes the file.
virtual directory_iterator dir_begin (const Twine &Dir, std::error_code &EC)=0
Get a directory_iterator for Dir.
virtual std::error_code setCurrentWorkingDirectory (const Twine &Path)=0
Set the working directory.
virtual llvm::ErrorOr< std::string > getCurrentWorkingDirectory () const =0
Get the working directory of this file system.
virtual std::error_code getRealPath (const Twine &Path, SmallVectorImpl< char > &Output) const
Gets real path of Path e.g.
bool exists (const Twine &Path)
Check whether a file exists. Provided for convenience.
virtual std::error_code isLocal (const Twine &Path, bool &Result)
Is the file mounted on a local filesystem?
virtual std::error_code makeAbsolute (SmallVectorImpl< char > &Path) const
Make Path an absolute path.
void print (raw_ostream &OS, PrintType Type=PrintType::Contents, unsigned IndentLevel=0) const
LLVM_DUMP_METHOD void dump () const
Public Member Functions inherited from llvm::ThreadSafeRefCountedBase< FileSystem >
void Retain () const
void Release () const
Protected Member Functions
virtual void printImpl (raw_ostream &OS, PrintType Type, unsigned IndentLevel) const
void printIndent (raw_ostream &OS, unsigned IndentLevel) const
Protected Member Functions inherited from llvm::ThreadSafeRefCountedBase< FileSystem >
ThreadSafeRefCountedBase ()=default
ThreadSafeRefCountedBase (const ThreadSafeRefCountedBase &)
ThreadSafeRefCountedBase & operator= (const ThreadSafeRefCountedBase &)=delete
~ThreadSafeRefCountedBase ()
Detailed Description
The virtual file system interface.
Definition at line 267 of file VirtualFileSystem.h.
Member Enumeration Documentation
PrintType
enum llvm::vfs::FileSystem::PrintType strong
Enumerator
Summary
Contents
RecursiveContents
Definition at line 321 of file VirtualFileSystem.h.
Constructor & Destructor Documentation
~FileSystem()
FileSystem::~FileSystem () virtual default
Member Function Documentation
dir_begin()
virtual directory_iterator llvm::vfs::FileSystem::dir_begin (const Twine & Dir, std::error_code & EC) pure virtual
Get a directory_iterator for Dir.
Note
The 'end' iterator is directory_iterator().
Implemented in llvm::vfs::RedirectingFileSystem, llvm::vfs::InMemoryFileSystem, llvm::vfs::ProxyFileSystem, llvm::vfs::OverlayFileSystem, and llvm::FileCollectorFileSystem.
Referenced by getHighestNumericTupleInDirectory().
dump()
void FileSystem::dump () const
Definition at line 154 of file VirtualFileSystem.cpp.
References llvm::dbgs(), print(), and RecursiveContents.
exists()
bool FileSystem::exists (const Twine & Path)
Check whether a file exists. Provided for convenience.
Definition at line 148 of file VirtualFileSystem.cpp.
References llvm::vfs::Status::exists(), and status().
Referenced by llvm::findVCToolChainViaEnvironment(), llvm::getWindowsSDKDir(), llvm::vfs::RedirectingFileSystem::setCurrentWorkingDirectory(), and llvm::useUniversalCRT().
getBufferForFile()
ErrorOr< std::unique_ptr< MemoryBuffer > > FileSystem::getBufferForFile (const Twine & Name, int64_t FileSize = -1, bool RequiresNullTerminator = true, bool IsVolatile = false)
This is a convenience method that opens a file, gets its content and then closes the file.
Definition at line 118 of file VirtualFileSystem.cpp.
References F, and openFileForRead().
Referenced by llvm::SpecialCaseList::createInternal().
getCurrentWorkingDirectory()
virtual llvm::ErrorOr<std::string> llvm::vfs::FileSystem::getCurrentWorkingDirectory () const pure virtual
Get the working directory of this file system.
Implemented in llvm::vfs::RedirectingFileSystem, llvm::vfs::InMemoryFileSystem, llvm::vfs::ProxyFileSystem, llvm::vfs::OverlayFileSystem, and llvm::FileCollectorFileSystem.
Referenced by makeAbsolute().
getRealPath()
std::error_code FileSystem::getRealPath (const Twine & Path, SmallVectorImpl< char > & Output) const virtual
Gets real path of Path e.g.
collapse all . and .. patterns, resolve symlinks. For real file system, this uses llvm::sys::fs::real_path. This returns errc::operation_not_permitted if not implemented by subclass.
Reimplemented in llvm::vfs::RedirectingFileSystem, llvm::vfs::InMemoryFileSystem, llvm::vfs::ProxyFileSystem, llvm::vfs::OverlayFileSystem, and llvm::FileCollectorFileSystem.
Definition at line 139 of file VirtualFileSystem.cpp.
References llvm::operation_not_permitted.
isLocal()
std::error_code FileSystem::isLocal (const Twine & Path, bool & Result) virtual
Is the file mounted on a local filesystem?
Reimplemented in llvm::vfs::RedirectingFileSystem, llvm::vfs::InMemoryFileSystem, llvm::vfs::ProxyFileSystem, llvm::vfs::OverlayFileSystem, and llvm::FileCollectorFileSystem.
Definition at line 144 of file VirtualFileSystem.cpp.
References llvm::operation_not_permitted.
makeAbsolute()
std::error_code FileSystem::makeAbsolute (SmallVectorImpl< char > & Path) const virtual
Make Path an absolute path.
Makes Path absolute using the current directory if it is not already. An empty Path will result in the current directory.
/absolute/path => /absolute/path relative/../path => <current-directory>/relative/../path
Parameters
Path A path that is modified to be an absolute path.
Returns
success if path has been made absolute, otherwise a platform-specific error_code.
Reimplemented in llvm::vfs::RedirectingFileSystem.
Definition at line 127 of file VirtualFileSystem.cpp.
References getCurrentWorkingDirectory(), llvm::sys::path::is_absolute(), and llvm::sys::fs::make_absolute().
Referenced by llvm::cl::ExpansionContext::findConfigFile(), llvm::vfs::InMemoryFileSystem::getRealPath(), llvm::cl::ExpansionContext::readConfigFile(), and llvm::vfs::InMemoryFileSystem::setCurrentWorkingDirectory().
openFileForRead()
virtual llvm::ErrorOr<std::unique_ptr<File> > llvm::vfs::FileSystem::openFileForRead (const Twine & Path) pure virtual
Get a File object for the file at Path, if one exists.
Implemented in llvm::vfs::RedirectingFileSystem, llvm::vfs::InMemoryFileSystem, llvm::vfs::ProxyFileSystem, llvm::vfs::OverlayFileSystem, and llvm::FileCollectorFileSystem.
Referenced by getBufferForFile().
print()
void llvm::vfs::FileSystem::print (raw_ostream & OS, PrintType Type = PrintType::Contents, unsigned IndentLevel = 0) const inline
Definition at line 322 of file VirtualFileSystem.h.
References OS, and printImpl().
Referenced by dump().
printImpl()
virtual void llvm::vfs::FileSystem::printImpl (raw_ostream & OS, PrintType Type, unsigned IndentLevel) const inline protected virtual
Reimplemented in llvm::vfs::RedirectingFileSystem, llvm::vfs::InMemoryFileSystem, and llvm::vfs::OverlayFileSystem.
Definition at line 332 of file VirtualFileSystem.h.
References OS, and printIndent().
Referenced by print().
printIndent()
void llvm::vfs::FileSystem::printIndent (raw_ostream & OS, unsigned IndentLevel) const inline protected
Definition at line 338 of file VirtualFileSystem.h.
References i, and OS.
Referenced by llvm::vfs::RedirectingFileSystem::printEntry(), printImpl(), llvm::vfs::OverlayFileSystem::printImpl(), llvm::vfs::InMemoryFileSystem::printImpl(), and llvm::vfs::RedirectingFileSystem::printImpl().
setCurrentWorkingDirectory()
virtual std::error_code llvm::vfs::FileSystem::setCurrentWorkingDirectory (const Twine & Path) pure virtual
Set the working directory.
This will affect all following operations on this file system and may propagate down for nested file systems.
Implemented in llvm::vfs::RedirectingFileSystem, llvm::vfs::InMemoryFileSystem, llvm::vfs::ProxyFileSystem, llvm::vfs::OverlayFileSystem, and llvm::FileCollectorFileSystem.
status()
virtual llvm::ErrorOr<Status> llvm::vfs::FileSystem::status (const Twine & Path) pure virtual
Get the status of the entry at Path, if one exists.
Implemented in llvm::vfs::RedirectingFileSystem, llvm::vfs::InMemoryFileSystem, llvm::vfs::ProxyFileSystem, llvm::vfs::OverlayFileSystem, and llvm::FileCollectorFileSystem.
Referenced by exists(), llvm::cl::ExpansionContext::findConfigFile(), llvm::findVCToolChainViaSetupConfig(), and getHighestNumericTupleInDirectory().
The documentation for this class was generated from the following files:
include/llvm/Support/VirtualFileSystem.h
lib/Support/VirtualFileSystem.cpp