LLVM: llvm::LoopPrinterPass Class Reference
llvm::LoopPrinterPass Class Reference
Printer pass for the LoopAnalysis results.
#include "llvm/Analysis/LoopInfo.h"
Public Member Functions
LoopPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< LoopPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the LoopAnalysis results.
Definition at line 1279 of file LoopInfo.h.
Constructor & Destructor Documentation
LoopPrinterPass()
llvm::LoopPrinterPass::LoopPrinterPass (raw_ostream & OS) inline explicit
Definition at line 1283 of file LoopInfo.h.
Member Function Documentation
run()
PreservedAnalyses LoopPrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 971 of file LoopInfo.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), OS, and llvm::LoopBase< BasicBlock, Loop >::print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopInfo.h
lib/Analysis/LoopInfo.cpp