LLVM: llvm::OpenMPOptPass Class Reference
llvm::OpenMPOptPass Class Reference
OpenMP optimizations pass.
#include "llvm/Transforms/IPO/OpenMPOpt.h"
Public Member Functions
OpenMPOptPass ()
OpenMPOptPass (ThinOrFullLTOPhase LTOPhase)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< OpenMPOptPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< OpenMPOptPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
OpenMP optimizations pass.
Definition at line 38 of file OpenMPOpt.h.
Constructor & Destructor Documentation
OpenMPOptPass() [1/2]
llvm::OpenMPOptPass::OpenMPOptPass () inline
Definition at line 40 of file OpenMPOpt.h.
OpenMPOptPass() [2/2]
llvm::OpenMPOptPass::OpenMPOptPass (ThinOrFullLTOPhase LTOPhase) inline
Definition at line 41 of file OpenMPOpt.h.
Member Function Documentation
run()
PreservedAnalyses OpenMPOptPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 5322 of file OpenMPOpt.cpp.
References llvm::PreservedAnalyses::all(), Allocator, AlwaysInlineDeviceFunctions, llvm::CallingConv::Cold, llvm::omp::containsOpenMP(), llvm::dbgs(), DEBUG_TYPE, llvm::AttributorConfig::DefaultInitializeLiveInternals, DisableInternalization, DisableOpenMPOptimizations, F, FAM, llvm::FullLTOPostLink, llvm::omp::getDeviceKernels(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::AttributorConfig::InitializationCallback, llvm::SetVector< T, Vector, Set >::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::Attributor::internalizeFunctions(), llvm::Attributor::isInternalizable(), llvm::AttributorConfig::IsModulePass, llvm::omp::isOpenMPDevice(), llvm::AMDGPU::HSAMD::Key::Kernels, LLVM_DEBUG, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::lookup(), M, llvm::AttributorConfig::MaxFixpointIterations, llvm::PreservedAnalyses::none(), llvm::AttributorConfig::OREGetter, llvm::AttributorConfig::PassName, PrintModuleAfterOptimizations, PrintModuleBeforeOptimizations, llvm::AttributorConfig::RewriteSignatures, llvm::AMDGPU::CPol::SCC, SetFixpointIterations, TAG, and llvm::ThinLTOPreLink.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/OpenMPOpt.h
lib/Transforms/IPO/OpenMPOpt.cpp