LLVM: llvm::LoopSimplifyCFGPass Class Reference
llvm::LoopSimplifyCFGPass Class Reference
Performs basic CFG simplifications to assist other loop passes.
#include "llvm/Transforms/Scalar/LoopSimplifyCFG.h"
Public Member Functions
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Public Member Functions inherited from llvm::PassInfoMixin< LoopSimplifyCFGPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopSimplifyCFGPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Performs basic CFG simplifications to assist other loop passes.
Definition at line 28 of file LoopSimplifyCFG.h.
Member Function Documentation
run()
PreservedAnalyses LoopSimplifyCFGPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 718 of file LoopSimplifyCFG.cpp.
References llvm::PreservedAnalyses::all(), llvm::LoopStandardAnalysisResults::DT, llvm::getLoopPassPreservedAnalyses(), llvm::LoopStandardAnalysisResults::LI, llvm::LPMUpdater::markLoopAsDeleted(), llvm::LoopStandardAnalysisResults::MSSA, llvm::LoopStandardAnalysisResults::SE, and simplifyLoopCFG().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopSimplifyCFG.h
lib/Transforms/Scalar/LoopSimplifyCFG.cpp