LLVM: llvm::msgpack::DocNode Class Reference
llvm::msgpack::DocNode Class Reference
A node in a MsgPack Document.
#include "llvm/BinaryFormat/MsgPackDocument.h"
Public Types
typedef std::map< DocNode, DocNode > MapTy
typedef std::vector< DocNode > ArrayTy
Public Member Functions
DocNode ()
bool isMap () const
bool isArray () const
bool isScalar () const
bool isString () const
bool isEmpty () const
Type getKind () const
Document * getDocument () const
int64_t & getInt ()
uint64_t & getUInt ()
bool & getBool ()
double & getFloat ()
int64_t getInt () const
uint64_t getUInt () const
bool getBool () const
double getFloat () const
StringRef getString () const
ArrayDocNode & getArray (bool Convert=false)
Get an ArrayDocNode for an array node.
MapDocNode & getMap (bool Convert=false)
Get a MapDocNode for a map node.
std::string toString () const
Convert this node to a string, assuming it is scalar.
StringRef fromString (StringRef S, StringRef Tag="")
Convert the StringRef and use it to set this DocNode (assuming scalar).
DocNode & operator= (const char *Val)
Convenience assignment operators.
DocNode & operator= (StringRef Val)
DocNode & operator= (bool Val)
DocNode & operator= (int Val)
DocNode & operator= (unsigned Val)
DocNode & operator= (int64_t Val)
DocNode & operator= (uint64_t Val)
Protected Attributes
union {
int64_t Int
uint64_t UInt
bool Bool
double Float
StringRef Raw
ArrayTy * Array
MapTy * Map
};
Friends
bool operator< (const DocNode &Lhs, const DocNode &Rhs)
Comparison operator, used for map keys.
bool operator== (const DocNode &Lhs, const DocNode &Rhs)
Equality operator.
bool operator!= (const DocNode &Lhs, const DocNode &Rhs)
Inequality operator.
Detailed Description
A node in a MsgPack Document.
This is a simple copyable and passable-by-value type that does not own any memory.
Definition at line 38 of file MsgPackDocument.h.
Member Typedef Documentation
ArrayTy
typedef std::vector<DocNode> llvm::msgpack::DocNode::ArrayTy
Definition at line 43 of file MsgPackDocument.h.
MapTy
typedef std::map<DocNode, DocNode> llvm::msgpack::DocNode::MapTy
Definition at line 42 of file MsgPackDocument.h.
Constructor & Destructor Documentation
DocNode()
llvm::msgpack::DocNode::DocNode () inline
Definition at line 67 of file MsgPackDocument.h.
Member Function Documentation
fromString()
StringRef DocNode::fromString (StringRef S, StringRef Tag = "")
Convert the StringRef and use it to set this DocNode (assuming scalar).
If it is a string, copy the string into the Document's strings list so we do not rely on S having a lifetime beyond this call. Tag is "" or a YAML tag.
Definition at line 69 of file MsgPackDocumentYAML.cpp.
References getDocument(), llvm::msgpack::Document::getNode(), and uint64_t.
getArray()
ArrayDocNode& llvm::msgpack::DocNode::getArray (bool Convert = false) inline
Get an ArrayDocNode for an array node.
If Convert, convert the node to an array node if necessary.
Definition at line 129 of file MsgPackDocument.h.
References llvm::msgpack::Array, assert(), and getKind().
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernel().
getBool() [1/2]
bool& llvm::msgpack::DocNode::getBool () inline
Definition at line 92 of file MsgPackDocument.h.
References assert(), Bool, llvm::msgpack::Boolean, and getKind().
getBool() [2/2]
bool llvm::msgpack::DocNode::getBool () const inline
Definition at line 112 of file MsgPackDocument.h.
References assert(), Bool, llvm::msgpack::Boolean, and getKind().
getDocument()
Document* llvm::msgpack::DocNode::getDocument () const inline
Definition at line 80 of file MsgPackDocument.h.
References llvm::msgpack::KindAndDocument::Doc.
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernel(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitKernelAttrs(), llvm::msgpack::MapDocNode::find(), fromString(), operator=(), llvm::msgpack::MapDocNode::operator[](), llvm::msgpack::ArrayDocNode::operator[](), llvm::msgpack::ArrayDocNode::push_back(), and toString().
getFloat() [1/2]
double& llvm::msgpack::DocNode::getFloat () inline
Definition at line 97 of file MsgPackDocument.h.
References assert(), llvm::msgpack::Float, Float, and getKind().
getFloat() [2/2]
double llvm::msgpack::DocNode::getFloat () const inline
Definition at line 117 of file MsgPackDocument.h.
References assert(), llvm::msgpack::Float, Float, and getKind().
getInt() [1/2]
int64_t& llvm::msgpack::DocNode::getInt () inline
Definition at line 82 of file MsgPackDocument.h.
References assert(), getKind(), llvm::msgpack::Int, and Int.
getInt() [2/2]
int64_t llvm::msgpack::DocNode::getInt () const inline
Definition at line 102 of file MsgPackDocument.h.
References assert(), getKind(), llvm::msgpack::Int, and Int.
getKind()
Type llvm::msgpack::DocNode::getKind () const inline
Definition at line 79 of file MsgPackDocument.h.
References llvm::msgpack::KindAndDocument::Kind.
Referenced by llvm::msgpack::ArrayDocNode::ArrayDocNode(), getArray(), getBool(), getFloat(), getInt(), getMap(), getString(), getUInt(), isArray(), isEmpty(), isMap(), isString(), llvm::msgpack::MapDocNode::MapDocNode(), and toString().
getMap()
MapDocNode& llvm::msgpack::DocNode::getMap (bool Convert = false) inline
Get a MapDocNode for a map node.
If Convert, convert the node to a map node if necessary.
Definition at line 140 of file MsgPackDocument.h.
References assert(), getKind(), and llvm::msgpack::Map.
Referenced by llvm::AMDGPU::HSAMD::V3::MetadataVerifier::verify().
getString()
StringRef llvm::msgpack::DocNode::getString () const inline
Definition at line 122 of file MsgPackDocument.h.
References assert(), getKind(), Raw, and llvm::msgpack::String.
getUInt() [1/2]
uint64_t& llvm::msgpack::DocNode::getUInt () inline
Definition at line 87 of file MsgPackDocument.h.
References assert(), getKind(), llvm::msgpack::UInt, and UInt.
getUInt() [2/2]
uint64_t llvm::msgpack::DocNode::getUInt () const inline
Definition at line 107 of file MsgPackDocument.h.
References assert(), getKind(), llvm::msgpack::UInt, and UInt.
isArray()
bool llvm::msgpack::DocNode::isArray () const inline
Definition at line 71 of file MsgPackDocument.h.
References llvm::msgpack::Array, and getKind().
Referenced by isScalar().
isEmpty()
bool llvm::msgpack::DocNode::isEmpty () const inline
Definition at line 78 of file MsgPackDocument.h.
References llvm::msgpack::Empty, and getKind().
isMap()
bool llvm::msgpack::DocNode::isMap () const inline
Definition at line 70 of file MsgPackDocument.h.
References getKind(), and llvm::msgpack::Map.
Referenced by isScalar(), and llvm::AMDGPU::HSAMD::V3::MetadataVerifier::verify().
isScalar()
bool llvm::msgpack::DocNode::isScalar () const inline
Definition at line 72 of file MsgPackDocument.h.
References isArray(), and isMap().
isString()
bool llvm::msgpack::DocNode::isString () const inline
Definition at line 73 of file MsgPackDocument.h.
References getKind(), and llvm::msgpack::String.
operator=() [1/7]
DocNode & DocNode::operator= (bool Val)
Definition at line 83 of file MsgPackDocument.cpp.
References getDocument(), and llvm::msgpack::Document::getNode().
operator=() [2/7]
DocNode& llvm::msgpack::DocNode::operator= (const char * Val) inline
Convenience assignment operators.
This only works if the destination DocNode has an associated Document, i.e. it was not constructed using the default constructor. The string one does not copy, so the string must remain valid for the lifetime of the Document. Use fromString to avoid that restriction.
Definition at line 202 of file MsgPackDocument.h.
operator=() [3/7]
DocNode & DocNode::operator= (int Val)
Definition at line 87 of file MsgPackDocument.cpp.
References getDocument(), and llvm::msgpack::Document::getNode().
operator=() [4/7]
DocNode & DocNode::operator= (int64_t Val)
Definition at line 95 of file MsgPackDocument.cpp.
References getDocument(), and llvm::msgpack::Document::getNode().
operator=() [5/7]
DocNode & DocNode::operator= (StringRef Val)
Definition at line 79 of file MsgPackDocument.cpp.
References getDocument(), and llvm::msgpack::Document::getNode().
operator=() [6/7]
DocNode & DocNode::operator= (uint64_t Val)
Definition at line 99 of file MsgPackDocument.cpp.
References getDocument(), and llvm::msgpack::Document::getNode().
operator=() [7/7]
DocNode & DocNode::operator= (unsigned Val)
Definition at line 91 of file MsgPackDocument.cpp.
References getDocument(), and llvm::msgpack::Document::getNode().
toString()
std::string DocNode::toString () const
Convert this node to a string, assuming it is scalar.
Convert this DocNode to a string, assuming it is scalar.
Definition at line 35 of file MsgPackDocumentYAML.cpp.
References Bool, llvm::msgpack::Boolean, llvm::msgpack::Float, Float, llvm::format(), getDocument(), llvm::msgpack::Document::getHexMode(), getKind(), llvm::msgpack::Int, Int, llvm_unreachable, llvm::msgpack::Nil, OS, Raw, S, llvm::msgpack::String, llvm::msgpack::UInt, and UInt.
Friends And Related Function Documentation
operator!=
bool operator!= (const DocNode & Lhs, const DocNode & Rhs) friend
Inequality operator.
Definition at line 185 of file MsgPackDocument.h.
operator<
bool operator< (const DocNode & Lhs, const DocNode & Rhs) friend
Comparison operator, used for map keys.
Definition at line 150 of file MsgPackDocument.h.
operator==
bool operator== (const DocNode & Lhs, const DocNode & Rhs) friend
Equality operator.
Definition at line 180 of file MsgPackDocument.h.
Member Data Documentation
@157
union { ... }
Array
ArrayTy* llvm::msgpack::DocNode::Array
Definition at line 60 of file MsgPackDocument.h.
Referenced by llvm::msgpack::ArrayDocNode::back(), llvm::msgpack::ArrayDocNode::begin(), llvm::msgpack::ArrayDocNode::end(), llvm::msgpack::ArrayDocNode::operator[](), llvm::msgpack::ArrayDocNode::push_back(), and llvm::msgpack::ArrayDocNode::size().
Bool
bool llvm::msgpack::DocNode::Bool
Definition at line 57 of file MsgPackDocument.h.
Referenced by getBool(), and toString().
Float
double llvm::msgpack::DocNode::Float
Definition at line 58 of file MsgPackDocument.h.
Referenced by getFloat(), and toString().
Int
int64_t llvm::msgpack::DocNode::Int
Definition at line 55 of file MsgPackDocument.h.
Referenced by getInt(), and toString().
Map
MapTy* llvm::msgpack::DocNode::Map
Definition at line 61 of file MsgPackDocument.h.
Referenced by llvm::msgpack::MapDocNode::begin(), llvm::msgpack::MapDocNode::end(), llvm::msgpack::MapDocNode::erase(), llvm::msgpack::MapDocNode::find(), and llvm::msgpack::MapDocNode::size().
Raw
StringRef llvm::msgpack::DocNode::Raw
Definition at line 59 of file MsgPackDocument.h.
Referenced by getString(), and toString().
UInt
uint64_t llvm::msgpack::DocNode::UInt
Definition at line 56 of file MsgPackDocument.h.
Referenced by getUInt(), and toString().
The documentation for this class was generated from the following files:
include/llvm/BinaryFormat/MsgPackDocument.h
lib/BinaryFormat/MsgPackDocument.cpp
lib/BinaryFormat/MsgPackDocumentYAML.cpp