LLVM: llvm::TargetFolder Class Reference
llvm::TargetFolder Class Reference final
TargetFolder - Create constants with target dependent folding.
#include "llvm/Analysis/TargetFolder.h"
Public Member Functions
TargetFolder (const DataLayout &DL)
Value * FoldBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS) const override
Value * FoldExactBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool IsExact) const override
Value * FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, bool HasNUW, bool HasNSW) const override
Value * FoldBinOpFMF (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, FastMathFlags FMF) const override
Value * FoldICmp (CmpInst::Predicate P, Value *LHS, Value *RHS) const override
Value * FoldUnOpFMF (Instruction::UnaryOps Opc, Value *V, FastMathFlags FMF) const override
Value * FoldGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, bool IsInBounds=false) const override
Value * FoldSelect (Value *C, Value *True, Value *False) const override
Value * FoldExtractValue (Value *Agg, ArrayRef< unsigned > IdxList) const override
Value * FoldInsertValue (Value *Agg, Value *Val, ArrayRef< unsigned > IdxList) const override
Value * FoldExtractElement (Value *Vec, Value *Idx) const override
Value * FoldInsertElement (Value *Vec, Value *NewElt, Value *Idx) const override
Value * FoldShuffleVector (Value *V1, Value *V2, ArrayRef< int > Mask) const override
Constant * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const override
Constant * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const override
Constant * CreatePointerCast (Constant *C, Type *DestTy) const override
Constant * CreateFPCast (Constant *C, Type *DestTy) const override
Constant * CreateBitCast (Constant *C, Type *DestTy) const override
Constant * CreateIntToPtr (Constant *C, Type *DestTy) const override
Constant * CreatePtrToInt (Constant *C, Type *DestTy) const override
Constant * CreateZExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateSExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateTruncOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const override
Constant * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const override
Public Member Functions inherited from llvm::IRBuilderFolder
virtual ~IRBuilderFolder ()
Detailed Description
TargetFolder - Create constants with target dependent folding.
Definition at line 34 of file TargetFolder.h.
Constructor & Destructor Documentation
TargetFolder()
llvm::TargetFolder::TargetFolder (const DataLayout & DL) inline explicit
Definition at line 45 of file TargetFolder.h.
References DL.
Member Function Documentation
CreateBitCast()
Constant* llvm::TargetFolder::CreateBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 210 of file TargetFolder.h.
References CreateCast().
CreateCast()
Constant* llvm::TargetFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 188 of file TargetFolder.h.
References llvm::ConstantExpr::getCast().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
CreateFCmp()
Constant* llvm::TargetFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 246 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare(), LHS, P, and RHS.
CreateFPCast()
Constant* llvm::TargetFolder::CreateFPCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 205 of file TargetFolder.h.
References llvm::ConstantExpr::getFPCast().
CreateIntCast()
Constant* llvm::TargetFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 194 of file TargetFolder.h.
References llvm::ConstantExpr::getIntegerCast(), and isSigned().
CreateIntToPtr()
Constant* llvm::TargetFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 213 of file TargetFolder.h.
References CreateCast().
CreatePointerBitCastOrAddrSpaceCast()
Constant* llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 235 of file TargetFolder.h.
References llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast().
CreatePointerCast()
Constant* llvm::TargetFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 200 of file TargetFolder.h.
References llvm::ConstantExpr::getPointerCast().
CreatePtrToInt()
Constant* llvm::TargetFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 216 of file TargetFolder.h.
References CreateCast().
CreateSExtOrBitCast()
Constant* llvm::TargetFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 224 of file TargetFolder.h.
References llvm::ConstantExpr::getSExtOrBitCast().
CreateTruncOrBitCast()
Constant* llvm::TargetFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 229 of file TargetFolder.h.
References llvm::ConstantExpr::getTruncOrBitCast().
CreateZExtOrBitCast()
Constant* llvm::TargetFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 219 of file TargetFolder.h.
References llvm::ConstantExpr::getZExtOrBitCast().
FoldBinOp()
Value* llvm::TargetFolder::FoldBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 54 of file TargetFolder.h.
References llvm::ConstantFoldBinaryOpOperands(), DL, llvm::ConstantExpr::get(), llvm::ConstantExpr::isDesirableBinOp(), LHS, and RHS.
Referenced by FoldBinOpFMF().
FoldBinOpFMF()
Value* llvm::TargetFolder::FoldBinOpFMF (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, FastMathFlags FMF) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 97 of file TargetFolder.h.
References FoldBinOp(), LHS, and RHS.
FoldExactBinOp()
Value* llvm::TargetFolder::FoldExactBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool IsExact) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 66 of file TargetFolder.h.
References llvm::ConstantFoldBinaryOpOperands(), DL, llvm::ConstantExpr::get(), llvm::ConstantExpr::isDesirableBinOp(), llvm::PossiblyExactOperator::IsExact, LHS, and RHS.
FoldExtractElement()
Value* llvm::TargetFolder::FoldExtractElement (Value * Vec, Value * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 157 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractElement().
FoldExtractValue()
Value* llvm::TargetFolder::FoldExtractValue (Value * Agg, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 141 of file TargetFolder.h.
References llvm::ConstantFoldExtractValueInstruction().
FoldGEP()
Value* llvm::TargetFolder::FoldGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, bool IsInBounds = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 117 of file TargetFolder.h.
References llvm::any_of(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getInBoundsGetElementPtr(), and Ptr.
FoldICmp()
Value* llvm::TargetFolder::FoldICmp (CmpInst::Predicate P, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 102 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare(), LHS, P, and RHS.
FoldInsertElement()
Value* llvm::TargetFolder::FoldInsertElement (Value * Vec, Value * NewElt, Value * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 165 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertElement().
FoldInsertValue()
Value* llvm::TargetFolder::FoldInsertValue (Value * Agg, Value * Val, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 148 of file TargetFolder.h.
References llvm::ConstantFoldInsertValueInstruction().
FoldNoWrapBinOp()
Value* llvm::TargetFolder::FoldNoWrapBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, bool HasNUW, bool HasNSW) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 79 of file TargetFolder.h.
References llvm::ConstantFoldBinaryOpOperands(), DL, llvm::ConstantExpr::get(), llvm::ConstantExpr::isDesirableBinOp(), LHS, llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, and RHS.
FoldSelect()
Value* llvm::TargetFolder::FoldSelect (Value * C, Value * True, Value * False) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 131 of file TargetFolder.h.
References CC, R600_InstFlag::FC, and llvm::ConstantExpr::getSelect().
FoldShuffleVector()
Value* llvm::TargetFolder::FoldShuffleVector (Value * V1, Value * V2, ArrayRef< int > Mask) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 175 of file TargetFolder.h.
References C1, llvm::ConstantExpr::getShuffleVector(), llvm::BitmaskEnumDetail::Mask(), and llvm::NVPTX::PTXLdStInstCode::V2.
FoldUnOpFMF()
Value* llvm::TargetFolder::FoldUnOpFMF (Instruction::UnaryOps Opc, Value * V, FastMathFlags FMF) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 110 of file TargetFolder.h.
References llvm::ConstantFoldUnaryOpOperand(), and DL.
The documentation for this class was generated from the following files:
include/llvm/Analysis/TargetFolder.h
lib/Analysis/ConstantFolding.cpp