LLVM: llvm::sampleprof::SampleProfileWriterBinary Class Reference
llvm::sampleprof::SampleProfileWriterBinary Class Reference
Sample-based profile writer (binary format).
#include "llvm/ProfileData/SampleProfWriter.h"
Public Member Functions
SampleProfileWriterBinary (std::unique_ptr< raw_ostream > &OS)
std::error_code writeSample (const FunctionSamples &S) override
Write samples of a top-level function to a binary file.
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
virtual ~SampleProfileWriter ()=default
virtual std::error_code write (const SampleProfileMap &ProfileMap)
Write all the sample profiles in the given map of samples.
template<typename FunctionPruningStrategy = DefaultFunctionPruningStrategy>
std::error_code writeWithSizeLimit (SampleProfileMap &ProfileMap, size_t OutputSizeLimit)
Write sample profiles up to given size limit, using the pruning strategy to drop some functions if necessary.
raw_ostream & getOutputStream ()
virtual void setProfileSymbolList (ProfileSymbolList *PSL)
virtual void setToCompressAllSections ()
virtual void setUseMD5 ()
virtual void setPartialProfile ()
virtual void resetSecLayout (SectionLayout SL)
Protected Member Functions
virtual MapVector< StringRef, uint32_t > & getNameTable ()
virtual std::error_code writeMagicIdent (SampleProfileFormat Format)
virtual std::error_code writeNameTable ()
std::error_code writeHeader (const SampleProfileMap &ProfileMap) override
Write a file header for the profile file.
std::error_code writeSummary ()
virtual std::error_code writeContextIdx (const SampleContext &Context)
std::error_code writeNameIdx (StringRef FName)
std::error_code writeBody (const FunctionSamples &S)
void stablizeNameTable (MapVector< StringRef, uint32_t > &NameTable, std::set< StringRef > &V)
void addName (StringRef FName)
virtual void addContext (const SampleContext &Context)
void addNames (const FunctionSamples &S)
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriter
SampleProfileWriter (std::unique_ptr< raw_ostream > &OS)
virtual std::error_code writeFuncProfiles (const SampleProfileMap &ProfileMap)
std::error_code writeWithSizeLimitInternal (SampleProfileMap &ProfileMap, size_t OutputSizeLimit, FunctionPruningStrategy *Strategy)
void computeSummary (const SampleProfileMap &ProfileMap)
Compute summary for this profile.
Protected Attributes
MapVector< StringRef, uint32_t > NameTable
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriter
size_t LineCount
For writeWithSizeLimit in text mode, each newline takes 1 additional byte on Windows when actually written to the file, but not written to a memory buffer.
std::unique_ptr< raw_ostream > OutputStream
Output stream where to emit the profile to.
std::unique_ptr< ProfileSummary > Summary
Profile summary.
SampleProfileFormat Format = SPF_None
Profile format.
Friends
ErrorOr< std::unique_ptr< SampleProfileWriter > > SampleProfileWriter::create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Additional Inherited Members
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory.
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Create a new stream writer based on the value of Format.
Detailed Description
Sample-based profile writer (binary format).
Definition at line 191 of file SampleProfWriter.h.
Constructor & Destructor Documentation
SampleProfileWriterBinary()
llvm::sampleprof::SampleProfileWriterBinary::SampleProfileWriterBinary (std::unique_ptr< raw_ostream > & OS) inline
Definition at line 193 of file SampleProfWriter.h.
Member Function Documentation
addContext()
void SampleProfileWriterBinary::addContext (const SampleContext & Context) protected virtual
Reimplemented in llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 659 of file SampleProfWriter.cpp.
References addName(), and Context.
Referenced by writeHeader().
addName()
void SampleProfileWriterBinary::addName (StringRef FName) protected
Definition at line 654 of file SampleProfWriter.cpp.
References getNameTable().
Referenced by addContext(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::addContext(), and addNames().
addNames()
void SampleProfileWriterBinary::addNames (const FunctionSamples & S) protected
Definition at line 663 of file SampleProfWriter.cpp.
References addName(), llvm::X86AS::FS, llvm::sampleprof::SampleRecord::getCallTargets(), llvm::sampleprof::FunctionSamples::getName(), I, and S.
Referenced by writeHeader(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeNameTableSection().
getNameTable()
virtual MapVector<StringRef, uint32_t>& llvm::sampleprof::SampleProfileWriterBinary::getNameTable () inline protected virtual
Definition at line 199 of file SampleProfWriter.h.
References NameTable.
Referenced by addName(), and writeNameIdx().
stablizeNameTable()
void SampleProfileWriterBinary::stablizeNameTable (MapVector< StringRef, uint32_t > & NameTable, std::set< StringRef > & V) inline protected
Definition at line 691 of file SampleProfWriter.cpp.
References i, I, N, and NameTable.
Referenced by writeNameTable(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeNameTable(), and llvm::sampleprof::SampleProfileWriterCompactBinary::writeNameTable().
writeBody()
std::error_code SampleProfileWriterBinary::writeBody (const FunctionSamples & S) protected
Definition at line 881 of file SampleProfWriter.cpp.
References Callee, llvm::sampleprof::LineLocation::Discriminator, llvm::encodeULEB128(), llvm::X86AS::FS, llvm::sampleprof::SampleRecord::getCallTargets(), llvm::sampleprof::SampleRecord::getSamples(), llvm::sampleprof::SampleRecord::getSortedCallTargets(), I, llvm::sampleprof::LineLocation::LineOffset, OS, llvm::sampleprof::SampleProfileWriter::OutputStream, S, llvm::StringMapImpl::size(), llvm::success, uint64_t, writeContextIdx(), and writeNameIdx().
Referenced by writeSample(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeSample(), and llvm::sampleprof::SampleProfileWriterCompactBinary::writeSample().
writeContextIdx()
std::error_code SampleProfileWriterBinary::writeContextIdx (const SampleContext & Context) protected virtual
Reimplemented in llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 640 of file SampleProfWriter.cpp.
References assert(), Context, and writeNameIdx().
Referenced by writeBody().
writeHeader()
std::error_code SampleProfileWriterBinary::writeHeader (const SampleProfileMap & ProfileMap) override protected virtual
Write a file header for the profile file.
Implements llvm::sampleprof::SampleProfileWriter.
Reimplemented in llvm::sampleprof::SampleProfileWriterCompactBinary.
Definition at line 760 of file SampleProfWriter.cpp.
References addContext(), addNames(), assert(), llvm::sampleprof::SampleProfileWriter::computeSummary(), llvm::sampleprof::SampleProfileWriter::Format, I, NameTable, llvm::success, writeMagicIdent(), writeNameTable(), and writeSummary().
Referenced by llvm::sampleprof::SampleProfileWriterCompactBinary::writeHeader().
writeMagicIdent()
std::error_code SampleProfileWriterBinary::writeMagicIdent (SampleProfileFormat Format) protected virtual
Definition at line 751 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::sampleprof::SampleProfileWriter::Format, OS, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::SPMagic(), llvm::sampleprof::SPVersion(), and llvm::success.
Referenced by writeHeader().
writeNameIdx()
std::error_code SampleProfileWriterBinary::writeNameIdx (StringRef FName) protected
Definition at line 645 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), getNameTable(), llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::MipsISD::Ret, llvm::success, and llvm::truncated_name_table.
Referenced by writeBody(), writeContextIdx(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeContextIdx(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeCSNameTableSection().
writeNameTable()
std::error_code SampleProfileWriterBinary::writeNameTable () protected virtual
Reimplemented in llvm::sampleprof::SampleProfileWriterCompactBinary, and llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 701 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), N, NameTable, OS, llvm::sampleprof::SampleProfileWriter::OutputStream, stablizeNameTable(), and llvm::success.
Referenced by writeHeader(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeNameTable().
writeSample()
std::error_code SampleProfileWriterBinary::writeSample (const FunctionSamples & S) override virtual
Write samples of a top-level function to a binary file.
Returns
true if the samples were written successfully, false otherwise.
Implements llvm::sampleprof::SampleProfileWriter.
Reimplemented in llvm::sampleprof::SampleProfileWriterCompactBinary, and llvm::sampleprof::SampleProfileWriterExtBinaryBase.
Definition at line 928 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), llvm::sampleprof::SampleProfileWriter::OutputStream, S, and writeBody().
writeSummary()
std::error_code SampleProfileWriterBinary::writeSummary () protected
Definition at line 864 of file SampleProfWriter.cpp.
References llvm::encodeULEB128(), OS, llvm::sampleprof::SampleProfileWriter::OutputStream, and llvm::sampleprof::SampleProfileWriter::Summary.
Referenced by writeHeader(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeOneSection().
Friends And Related Function Documentation
SampleProfileWriter::create
ErrorOr<std::unique_ptr<SampleProfileWriter> > SampleProfileWriter::create (std::unique_ptr< raw_ostream > & OS, SampleProfileFormat Format) friend
Member Data Documentation
NameTable
MapVector<StringRef, uint32_t> llvm::sampleprof::SampleProfileWriterBinary::NameTable protected
Definition at line 210 of file SampleProfWriter.h.
Referenced by getNameTable(), stablizeNameTable(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::write(), writeHeader(), writeNameTable(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeNameTable(), llvm::sampleprof::SampleProfileWriterCompactBinary::writeNameTable(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeNameTableSection().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfWriter.h
lib/ProfileData/SampleProfWriter.cpp