LLVM: llvm::IndVarSimplifyPass Class Reference
llvm::IndVarSimplifyPass Class Reference
#include "llvm/Transforms/Scalar/IndVarSimplify.h"
Public Member Functions
IndVarSimplifyPass (bool WidenIndVars=true)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Public Member Functions inherited from llvm::PassInfoMixin< IndVarSimplifyPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< IndVarSimplifyPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 25 of file IndVarSimplify.h.
Constructor & Destructor Documentation
IndVarSimplifyPass()
llvm::IndVarSimplifyPass::IndVarSimplifyPass (bool WidenIndVars = true) inline
Definition at line 30 of file IndVarSimplify.h.
Member Function Documentation
run()
PreservedAnalyses IndVarSimplifyPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 2209 of file IndVarSimplify.cpp.
References llvm::PreservedAnalyses::all(), AllowIVWidening, DL, llvm::LoopStandardAnalysisResults::DT, F, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getLoopPassPreservedAnalyses(), llvm::BasicBlock::getParent(), llvm::LoopStandardAnalysisResults::LI, llvm::LoopStandardAnalysisResults::MSSA, llvm::LoopStandardAnalysisResults::SE, llvm::LoopStandardAnalysisResults::TLI, and llvm::LoopStandardAnalysisResults::TTI.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/IndVarSimplify.h
lib/Transforms/Scalar/IndVarSimplify.cpp