LLVM: llvm::StringInit Class Reference
llvm::StringInit Class Reference
"foo" - Represent an initialization by a string value.
#include "llvm/TableGen/Record.h"
Public Types
enum StringFormat { SF_String, SF_Code }
Public Member Functions
StringInit (const StringInit &)=delete
StringInit & operator= (const StringInit &)=delete
StringRef getValue () const
StringFormat getFormat () const
bool hasCodeFormat () const
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
std::string getAsString () const override
Convert this value to a literal form.
std::string getAsUnquotedString () const override
Convert this value to a literal form, without adding quotes around a string.
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This function is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
Is this a complete value with no unset (uninitialized) subvalues?
void print (raw_ostream &OS) const
Print this value.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
virtual Init * resolveReferences (Resolver &R) const
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Static Public Member Functions
static bool classof (const Init *I)
static StringInit * get (RecordKeeper &RK, StringRef, StringFormat Fmt=SF_String)
static StringFormat determineFormat (StringFormat Fmt1, StringFormat Fmt2)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First, IK_FirstTypedInit, IK_BitInit, IK_BitsInit,
IK_DagInit, IK_DefInit, IK_FieldInit, IK_IntInit,
IK_ListInit, IK_FirstOpInit, IK_BinOpInit, IK_TernOpInit,
IK_UnOpInit, IK_LastOpInit, IK_CondOpInit, IK_FoldOpInit,
IK_IsAOpInit, IK_ExistsOpInit, IK_AnonymousNameInit, IK_StringInit,
IK_VarInit, IK_VarListElementInit, IK_VarBitInit, IK_VarDefInit,
IK_LastTypedInit, IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
"foo" - Represent an initialization by a string value.
Definition at line 639 of file Record.h.
Member Enumeration Documentation
StringFormat
enum llvm::StringInit::StringFormat
Enumerator
SF_String
SF_Code
Definition at line 641 of file Record.h.
Constructor & Destructor Documentation
StringInit()
llvm::StringInit::StringInit (const StringInit &) delete
Member Function Documentation
classof()
static bool llvm::StringInit::classof (const Init * I) inline static
Definition at line 657 of file Record.h.
References I, and llvm::Init::IK_StringInit.
convertInitializerTo()
Init * StringInit::convertInitializerTo (RecTy * Ty) const override virtual
Convert to a value whose type is Ty, or return null if this is not possible.
This can happen if the value's type is convertible to Ty, but there are unresolved references.
Reimplemented from llvm::TypedInit.
Definition at line 607 of file Record.cpp.
determineFormat()
static StringFormat llvm::StringInit::determineFormat (StringFormat Fmt1, StringFormat Fmt2) inline static
Definition at line 664 of file Record.h.
References SF_Code, and SF_String.
Referenced by ConcatStringInits(), and interleaveStringList().
get()
StringInit * StringInit::get (RecordKeeper & RK, StringRef V, StringFormat Fmt = SF_String) static
Definition at line 597 of file Record.cpp.
References llvm::RecordKeeper::getImpl(), SF_String, llvm::detail::RecordKeeperImpl::StringInitCodePool, and llvm::detail::RecordKeeperImpl::StringInitStringPool.
Referenced by ConcatStringInits(), llvm::UnOpInit::Fold(), llvm::TernOpInit::Fold(), llvm::VarInit::get(), llvm::AnonymousNameInit::getNameInit(), llvm::Record::getValue(), interleaveIntList(), interleaveStringList(), and llvm::Record::removeValue().
getAsString()
std::string llvm::StringInit::getAsString () const inline override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 676 of file Record.h.
References SF_String.
getAsUnquotedString()
std::string llvm::StringInit::getAsUnquotedString () const inline override virtual
Convert this value to a literal form, without adding quotes around a string.
Reimplemented from llvm::Init.
Definition at line 683 of file Record.h.
Referenced by llvm::FieldInit::Fold(), and llvm::DagInit::getAsString().
getBit()
Init* llvm::StringInit::getBit (unsigned Bit) const inline override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 687 of file Record.h.
References llvm_unreachable.
getFormat()
StringFormat llvm::StringInit::getFormat () const inline
Definition at line 669 of file Record.h.
Referenced by ConcatStringInits(), llvm::TernOpInit::Fold(), and interleaveStringList().
getValue()
StringRef llvm::StringInit::getValue () const inline
Definition at line 668 of file Record.h.
Referenced by llvm::BinOpInit::CompareInit(), ConcatStringInits(), llvm::TernOpInit::Fold(), llvm::FieldInit::getAsString(), llvm::VarInit::getName(), llvm::DagInit::getNameStr(), interleaveIntList(), and interleaveStringList().
hasCodeFormat()
bool llvm::StringInit::hasCodeFormat () const inline
Definition at line 670 of file Record.h.
References SF_Code.
isConcrete()
bool llvm::StringInit::isConcrete () const inline override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 674 of file Record.h.
operator=()
StringInit& llvm::StringInit::operator= (const StringInit &) delete
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp