LLVM: llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > Class Reference
llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > Class Reference
#include "llvm/Transforms/Scalar/LoopPassManager.h"
Public Member Functions
PassManager ()=default
PassManager (PassManager &&Arg)
PassManager & operator= (PassManager &&RHS)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Add either a loop pass or a loop-nest pass to the pass manager.
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
template<typename PassT >
LLVM_ATTRIBUTE_MINSIZE std::enable_if_t< is_detected< HasRunOnLoopT, PassT >::value > addPass (PassT &&Pass)
template<typename PassT >
LLVM_ATTRIBUTE_MINSIZE std::enable_if_t<!is_detected< HasRunOnLoopT, PassT >::value > addPass (PassT &&Pass)
template<typename PassT >
LLVM_ATTRIBUTE_MINSIZE std::enable_if_t< is_detected< HasRunOnLoopT, PassT >::value > addPass (RepeatedPass< PassT > &&Pass)
template<typename PassT >
LLVM_ATTRIBUTE_MINSIZE std::enable_if_t<!is_detected< HasRunOnLoopT, PassT >::value > addPass (RepeatedPass< PassT > &&Pass)
bool isEmpty () const
size_t getNumLoopPasses () const
size_t getNumLoopNestPasses () const
Public Member Functions inherited from llvm::PassInfoMixin< PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > >
static StringRef name ()
Gets the name of the pass we are mixed into.
Protected Types
using LoopPassConceptT = detail::PassConcept< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >
using LoopNestPassConceptT = detail::PassConcept< LoopNest, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >
Protected Member Functions
template<typename IRUnitT , typename PassT >
std::optional< PreservedAnalyses > runSinglePass (IRUnitT &IR, PassT &Pass, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U, PassInstrumentation &PI)
Run either a loop pass or a loop-nest pass.
PreservedAnalyses runWithLoopNestPasses (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
PreservedAnalyses runWithoutLoopNestPasses (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Protected Attributes
BitVector IsLoopNestPass
std::vector< std::unique_ptr< LoopPassConceptT > > LoopPasses
std::vector< std::unique_ptr< LoopNestPassConceptT > > LoopNestPasses
Detailed Description
Definition at line 69 of file LoopPassManager.h.
Member Typedef Documentation
LoopNestPassConceptT
using llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::LoopNestPassConceptT = detail::PassConcept<LoopNest, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater &> protected
Definition at line 179 of file LoopPassManager.h.
LoopPassConceptT
using llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::LoopPassConceptT = detail::PassConcept<Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater &> protected
Definition at line 176 of file LoopPassManager.h.
Constructor & Destructor Documentation
PassManager() [1/2]
llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::PassManager () explicit default
PassManager() [2/2]
llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::PassManager (PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > && Arg) inline
Definition at line 81 of file LoopPassManager.h.
Member Function Documentation
addPass() [1/4]
template<typename PassT > LLVM_ATTRIBUTE_MINSIZE std::enable_if_t<is_detected<HasRunOnLoopT, PassT>::value> llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::addPass (PassT && Pass) inline
Definition at line 107 of file LoopPassManager.h.
Referenced by llvm::PassBuilder::buildFunctionSimplificationPipeline(), llvm::PassBuilder::buildLTODefaultPipeline(), llvm::PassBuilder::buildModuleOptimizationPipeline(), llvm::createFunctionToLoopPassAdaptor(), and llvm::HexagonTargetMachine::registerPassBuilderCallbacks().
addPass() [2/4]
template<typename PassT > LLVM_ATTRIBUTE_MINSIZE std::enable_if_t<!is_detected<HasRunOnLoopT, PassT>::value> llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::addPass (PassT && Pass) inline
Definition at line 121 of file LoopPassManager.h.
addPass() [3/4]
template<typename PassT > LLVM_ATTRIBUTE_MINSIZE std::enable_if_t<is_detected<HasRunOnLoopT, PassT>::value> llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::addPass (RepeatedPass< PassT > && Pass) inline
Definition at line 139 of file LoopPassManager.h.
References move.
addPass() [4/4]
template<typename PassT > LLVM_ATTRIBUTE_MINSIZE std::enable_if_t<!is_detected<HasRunOnLoopT, PassT>::value> llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::addPass (RepeatedPass< PassT > && Pass) inline
Definition at line 154 of file LoopPassManager.h.
References move.
getNumLoopNestPasses()
size_t llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::getNumLoopNestPasses () const inline
Definition at line 171 of file LoopPassManager.h.
getNumLoopPasses()
size_t llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::getNumLoopPasses () const inline
Definition at line 170 of file LoopPassManager.h.
isEmpty()
bool llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::isEmpty () const inline
Definition at line 166 of file LoopPassManager.h.
Referenced by llvm::PassBuilder::buildO0DefaultPipeline().
isRequired()
static bool llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::isRequired () inline static
Definition at line 168 of file LoopPassManager.h.
operator=()
PassManager& llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::operator= (PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > && RHS) inline
Definition at line 86 of file LoopPassManager.h.
References move, and RHS.
printPipeline()
void llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 47 of file LoopPassManager.cpp.
References assert(), OS, and P.
run()
PreservedAnalyses llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Add either a loop pass or a loop-nest pass to the pass manager.
Explicitly specialize the pass manager's run method to handle loop nest structure updates.
Append Pass to the list of loop passes if it has a dedicated loops and to the list of loop-nest passes if the
loop-nests instead. Also append whether Pass is loop-nest pass or not to the end of
Definition at line 27 of file LoopPassManager.cpp.
References llvm::LoopBase< BlockT, LoopT >::isOutermost(), and llvm::PreservedAnalyses::preserveSet().
runSinglePass()
template<typename IRUnitT , typename PassT > std::optional< PreservedAnalyses > llvm::LoopPassManager::runSinglePass (IRUnitT & IR, PassT & Pass, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U, PassInstrumentation & PI) protected
Run either a loop pass or a loop-nest pass.
Returns std::nullopt if PassInstrumentation's BeforePass returns false. Otherwise, returns the preserved analyses of the pass.
Definition at line 397 of file LoopPassManager.h.
References IR, Pass, and llvm::LPMUpdater::skipCurrentLoop().
runWithLoopNestPasses()
PreservedAnalyses llvm::LoopPassManager::runWithLoopNestPasses (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U) protected
Definition at line 68 of file LoopPassManager.cpp.
References llvm::PreservedAnalyses::all(), assert(), E, llvm::LoopNest::getLoopNest(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), I, llvm::PreservedAnalyses::intersect(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::LPMUpdater::isLoopNestChanged(), llvm::LoopBase< BlockT, LoopT >::isOutermost(), llvm::LPMUpdater::markLoopNestChanged(), move, llvm::LoopStandardAnalysisResults::SE, llvm::LPMUpdater::setParentLoop(), and llvm::LPMUpdater::skipCurrentLoop().
runWithoutLoopNestPasses()
PreservedAnalyses llvm::LoopPassManager::runWithoutLoopNestPasses (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U) protected
Definition at line 151 of file LoopPassManager.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::intersect(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), move, llvm::LPMUpdater::setParentLoop(), and llvm::LPMUpdater::skipCurrentLoop().
Member Data Documentation
IsLoopNestPass
BitVector llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::IsLoopNestPass protected
Definition at line 183 of file LoopPassManager.h.
LoopNestPasses
std::vector<std::unique_ptr<LoopNestPassConceptT> > llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::LoopNestPasses protected
Definition at line 185 of file LoopPassManager.h.
LoopPasses
std::vector<std::unique_ptr<LoopPassConceptT> > llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::LoopPasses protected
Definition at line 184 of file LoopPassManager.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopPassManager.h
lib/Transforms/Scalar/LoopPassManager.cpp