LLVM: llvm::dxil::ResourceBase Class Reference
llvm::dxil::ResourceBase Class Reference
#include "Target/DirectX/DXILResource.h"
Classes
struct ExtendedProperties
Protected Types
enum ComponentType : uint32_t {
ComponentType::Invalid = 0, ComponentType::I1, ComponentType::I16, ComponentType::U16,
ComponentType::I32, ComponentType::U32, ComponentType::I64, ComponentType::U64,
ComponentType::F16, ComponentType::F32, ComponentType::F64, ComponentType::SNormF16,
ComponentType::UNormF16, ComponentType::SNormF32, ComponentType::UNormF32, ComponentType::SNormF64,
ComponentType::UNormF64, ComponentType::PackedS8x32, ComponentType::PackedU8x32, ComponentType::LastEntry
}
using Kinds = hlsl::ResourceKind
Protected Member Functions
ResourceBase (uint32_t I, hlsl::FrontendResource R)
void write (LLVMContext &Ctx, MutableArrayRef< Metadata * > Entries) const
void print (raw_ostream &O, StringRef IDPrefix, StringRef BindingPrefix) const
Static Protected Member Functions
static StringRef getKindName (Kinds Kind)
static void printKind (Kinds Kind, unsigned Alignment, raw_ostream &OS, bool SRV=false, bool HasCounter=false, uint32_t SampleCount=0)
static StringRef getComponentTypeName (ComponentType CompType)
static void printComponentType (Kinds Kind, ComponentType CompType, unsigned Alignment, raw_ostream &OS)
Protected Attributes
uint32_t ID
GlobalVariable * GV
StringRef Name
uint32_t Space
uint32_t LowerBound
uint32_t RangeSize
Detailed Description
Definition at line 30 of file DXILResource.h.
Member Typedef Documentation
Kinds
using llvm::dxil::ResourceBase::Kinds = hlsl::ResourceKind protected
Definition at line 43 of file DXILResource.h.
Member Enumeration Documentation
ComponentType
enum llvm::dxil::ResourceBase::ComponentType : uint32_t strong protected
Enumerator
Invalid
I1
I16
U16
I32
U32
I64
U64
F16
F32
F64
SNormF16
UNormF16
SNormF32
UNormF32
SNormF64
UNormF64
PackedS8x32
PackedU8x32
LastEntry
Definition at line 51 of file DXILResource.h.
Constructor & Destructor Documentation
ResourceBase()
ResourceBase::ResourceBase (uint32_t I, hlsl::FrontendResource R) protected
Definition at line 59 of file DXILResource.cpp.
References llvm::GlobalValue::getValueType(), GV, and RangeSize.
Member Function Documentation
getComponentTypeName()
StringRef ResourceBase::getComponentTypeName (ComponentType CompType) static protected
Definition at line 66 of file DXILResource.cpp.
References F16, F32, F64, I1, I16, I32, I64, Invalid, LastEntry, PackedS8x32, PackedU8x32, SNormF16, SNormF32, SNormF64, U16, U32, U64, UNormF16, UNormF32, and UNormF64.
Referenced by printComponentType().
getKindName()
StringRef ResourceBase::getKindName (Kinds Kind) static protected
Definition at line 133 of file DXILResource.cpp.
References llvm::hlsl::Invalid, llvm::hlsl::NumEntries, and llvm::hlsl::Sampler.
Referenced by printKind().
print()
void ResourceBase::print (raw_ostream & O, StringRef IDPrefix, StringRef BindingPrefix) const protected
Definition at line 215 of file DXILResource.cpp.
References LowerBound, OS, RangeSize, llvm::right_justify(), Space, llvm::StringRef::str(), and llvm::to_string().
Referenced by llvm::dxil::Resources::dump(), llvm::dxil::UAVResource::print(), and llvm::dxil::ConstantBuffer::print().
printComponentType()
void ResourceBase::printComponentType (Kinds Kind, ComponentType CompType, unsigned Alignment, raw_ostream & OS) static protected
Definition at line 110 of file DXILResource.cpp.
References getComponentTypeName(), llvm::hlsl::Invalid, llvm::hlsl::NumEntries, OS, llvm::right_justify(), and llvm::hlsl::Sampler.
Referenced by llvm::dxil::UAVResource::print(), and llvm::dxil::ConstantBuffer::print().
printKind()
void ResourceBase::printKind (Kinds Kind, unsigned Alignment, raw_ostream & OS, bool SRV = false, bool HasCounter = false, uint32_t SampleCount = 0) static protected
Definition at line 177 of file DXILResource.cpp.
References getKindName(), llvm::hlsl::Invalid, llvm::hlsl::NumEntries, OS, llvm::right_justify(), llvm::hlsl::Sampler, llvm::hlsl::SRV, llvm::StringRef::str(), and llvm::to_string().
Referenced by llvm::dxil::UAVResource::print(), and llvm::dxil::ConstantBuffer::print().
write()
void ResourceBase::write (LLVMContext & Ctx, MutableArrayRef< Metadata * > Entries) const protected
Definition at line 338 of file DXILResource.cpp.
Member Data Documentation
GV
GlobalVariable* llvm::dxil::ResourceBase::GV protected
Definition at line 33 of file DXILResource.h.
Referenced by ResourceBase(), llvm::dxil::ConstantBuffer::setSize(), llvm::dxil::UAVResource::write(), and llvm::dxil::ConstantBuffer::write().
ID
uint32_t llvm::dxil::ResourceBase::ID protected
Definition at line 32 of file DXILResource.h.
LowerBound
uint32_t llvm::dxil::ResourceBase::LowerBound protected
Definition at line 36 of file DXILResource.h.
Referenced by print().
Name
StringRef llvm::dxil::ResourceBase::Name protected
Definition at line 34 of file DXILResource.h.
Referenced by llvm::dxil::UAVResource::print(), and llvm::dxil::ConstantBuffer::print().
RangeSize
uint32_t llvm::dxil::ResourceBase::RangeSize protected
Definition at line 37 of file DXILResource.h.
Referenced by print(), and ResourceBase().
Space
uint32_t llvm::dxil::ResourceBase::Space protected
Definition at line 35 of file DXILResource.h.
Referenced by print().
The documentation for this class was generated from the following files:
lib/Target/DirectX/DXILResource.h
lib/Target/DirectX/DXILResource.cpp