LLVM: llvm::X86TTIImpl Class Reference
llvm::X86TTIImpl Class Reference
#include "Target/X86/X86TargetTransformInfo.h"
Public Member Functions
X86TTIImpl (const X86TargetMachine *TM, const Function &F)
Scalar TTI Implementations
TTI::PopcntSupportKind getPopcntSupport (unsigned TyWidth)
Cache TTI Implementation
std::optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const override
std::optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const override
Public Member Functions inherited from llvm::BasicTTIImplBase< X86TTIImpl >
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned *Fast) const
bool hasBranchDivergence ()
bool useGPUDivergenceAnalysis ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool isNoopAddrSpaceCast (unsigned FromAS, unsigned ToAS) const
unsigned getAssumedAddrSpace (const Value *V) const
bool isSingleThreaded () const
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLegalAddImmediate (int64_t imm)
bool isLegalICmpImmediate (int64_t imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
unsigned getStoreMinimumVF (unsigned VF, Type *ScalarMemTy, Type *ScalarValTy) const
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2)
bool isNumRegsMajorCostOfLSR ()
bool isProfitableLSRChainElement (Instruction *I)
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA () const
bool isTypeLegal (Type *Ty)
unsigned getRegUsageForType (Type *Ty)
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI)
bool shouldBuildLookupTables ()
bool shouldBuildRelLookupTables () const
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
InstructionCost getFPOpCost (Type *Ty)
unsigned getInliningThresholdMultiplier ()
unsigned adjustInliningThreshold (const CallBase *CB)
int getInlinerVectorBonusPercent ()
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP, OptimizationRemarkEmitter *ORE)
void getPeelingPreferences (Loop *L, ScalarEvolution &SE, TTI::PeelingPreferences &PP)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, LoopVectorizationLegality *LVL, InterleavedAccessInfo *IAI)
TailFoldingStyle getPreferredTailFoldingStyle ()
std::optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II)
std::optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed)
std::optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp)
virtual unsigned getCacheLineSize () const
virtual unsigned getPrefetchDistance () const
virtual unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const
virtual unsigned getMaxPrefetchIterationsAhead () const
virtual bool enableWritePrefetching () const
virtual bool shouldPrefetchAddressSpace (unsigned AS) const
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
std::optional< unsigned > getMaxVScale () const
std::optional< unsigned > getVScaleForTuning () const
InstructionCost getScalarizationOverhead (VectorType *InTy, const APInt &DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind)
Estimate the overhead of scalarizing an instruction.
InstructionCost getScalarizationOverhead (VectorType *InTy, bool Insert, bool Extract, TTI::TargetCostKind CostKind)
Helper wrapper for the DemandedElts variant of getScalarizationOverhead.
InstructionCost getScalarizationOverhead (VectorType *RetTy, ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind)
Estimate the overhead of scalarizing the inputs and outputs of an instruction, with return type RetTy and arguments Args of type Tys.
InstructionCost getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind)
Estimate the overhead of scalarizing an instructions unique non-constant operands.
std::pair< InstructionCost, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
unsigned getMaxInterleaveFactor (unsigned VF)
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info={TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Opd2Info={TTI::OK_AnyValue, TTI::OP_None}, ArrayRef< const Value * > Args=ArrayRef< const Value * >(), const Instruction *CxtI=nullptr)
TTI::ShuffleKind improveShuffleKindFromMask (TTI::ShuffleKind Kind, ArrayRef< int > Mask) const
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *Tp, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType *SubTp, ArrayRef< const Value * > Args=std::nullopt)
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, Value *Op0, Value *Op1)
InstructionCost getVectorInstrCost (const Instruction &I, Type *Val, TTI::TargetCostKind CostKind, unsigned Index)
InstructionCost getReplicationShuffleCost (Type *EltTy, int ReplicationFactor, int VF, const APInt &DemandedDstElts, TTI::TargetCostKind CostKind)
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo={TTI::OK_AnyValue, TTI::OP_None}, const Instruction *I=nullptr)
InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *DataTy, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind)
InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond=false, bool UseMaskForGaps=false)
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind)
Get intrinsic cost based on arguments.
InstructionCost getTypeBasedIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind)
Get intrinsic cost based on argument types.
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind)
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp)
InstructionCost getAddressComputationCost (Type *Ty, ScalarEvolution *, const SCEV *)
InstructionCost getTreeReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind)
Try to calculate arithmetic and shuffle op costs for reduction intrinsics.
InstructionCost getOrderedReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind)
Try to calculate the cost of performing strict (in-order) reductions, which involves doing a sequence of floating point additions in lane order, starting with an initial value.
InstructionCost getArithmeticReductionCost (unsigned Opcode, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind)
InstructionCost getMinMaxReductionCost (VectorType *Ty, VectorType *CondTy, bool IsUnsigned, TTI::TargetCostKind CostKind)
Try to calculate op costs for min/max reduction operations.
InstructionCost getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type *ResTy, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind)
InstructionCost getMulAccReductionCost (bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind)
InstructionCost getVectorSplitCost ()
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< X86TTIImpl >
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind)
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind) const
InstructionCost getInstructionCost (const User *U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind)
bool isExpensiveToSpeculativelyExecute (const Instruction *I)
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)=default
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind) const
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
unsigned getInliningThresholdMultiplier () const
unsigned adjustInliningThreshold (const CallBase *CB) const
int getInlinerVectorBonusPercent () const
InstructionCost getMemcpyCost (const Instruction *I) const
BranchProbability getPredictableBranchThreshold () const
bool hasBranchDivergence () const
bool useGPUDivergenceAnalysis () const
bool isSourceOfDivergence (const Value *V) const
bool isAlwaysUniform (const Value *V) const
unsigned getFlatAddressSpace () const
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool isNoopAddrSpaceCast (unsigned, unsigned) const
bool canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const
unsigned getAssumedAddrSpace (const Value *V) const
bool isSingleThreaded () const
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLoweredToCall (const Function *F) const
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo) const
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, LoopVectorizationLegality *LVL, InterleavedAccessInfo *IAI) const
TailFoldingStyle getPreferredTailFoldingStyle () const
std::optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const
std::optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const
std::optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &, OptimizationRemarkEmitter *) const
void getPeelingPreferences (Loop *, ScalarEvolution &, TTI::PeelingPreferences &) const
bool isLegalAddImmediate (int64_t Imm) const
bool isLegalICmpImmediate (int64_t Imm) const
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr) const
bool isLSRCostLess (const TTI::LSRCost &C1, const TTI::LSRCost &C2) const
bool isNumRegsMajorCostOfLSR () const
bool isProfitableLSRChainElement (Instruction *I) const
bool canMacroFuseCmp () const
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo) const
TTI::AddressingModeKind getPreferredAddressingMode (const Loop *L, ScalarEvolution *SE) const
bool isLegalMaskedStore (Type *DataType, Align Alignment) const
bool isLegalMaskedLoad (Type *DataType, Align Alignment) const
bool isLegalNTStore (Type *DataType, Align Alignment) const
bool isLegalNTLoad (Type *DataType, Align Alignment) const
bool isLegalBroadcastLoad (Type *ElementTy, ElementCount NumElements) const
bool isLegalMaskedScatter (Type *DataType, Align Alignment) const
bool isLegalMaskedGather (Type *DataType, Align Alignment) const
bool forceScalarizeMaskedGather (VectorType *DataType, Align Alignment) const
bool forceScalarizeMaskedScatter (VectorType *DataType, Align Alignment) const
bool isLegalMaskedCompressStore (Type *DataType) const
bool isLegalAltInstr (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask) const
bool isLegalMaskedExpandLoad (Type *DataType) const
bool enableOrderedReductions () const
bool hasDivRemOp (Type *DataType, bool IsSigned) const
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace) const
bool prefersVectorizedAddressing () const
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const
bool LSRWithInstrQueries () const
bool isTruncateFree (Type *Ty1, Type *Ty2) const
bool isProfitableToHoist (Instruction *I) const
bool useAA () const
bool isTypeLegal (Type *Ty) const
unsigned getRegUsageForType (Type *Ty) const
bool shouldBuildLookupTables () const
bool shouldBuildLookupTablesForConstant (Constant *C) const
bool shouldBuildRelLookupTables () const
bool useColdCCForColdCall (Function &F) const
InstructionCost getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind) const
InstructionCost getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
bool supportsEfficientVectorElementLoadStore () const
bool supportsTailCalls () const
bool supportsTailCallFor (const CallBase *CB) const
bool enableAggressiveInterleaving (bool LoopHasReductions) const
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableSelectOptimize () const
bool enableInterleavedAccessVectorization () const
bool enableMaskedInterleavedAccessVectorization () const
bool isFPVectorizationPotentiallyUnsafe () const
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned *Fast) const
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) const
bool haveFastSqrt (Type *Ty) const
bool isExpensiveToSpeculativelyExecute (const Instruction *I)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty) const
InstructionCost getFPOpCost (Type *Ty) const
InstructionCost getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty) const
InstructionCost getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
InstructionCost getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr) const
InstructionCost getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
unsigned getNumberOfRegisters (unsigned ClassID) const
unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
const char * getRegisterClassName (unsigned ClassID) const
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
unsigned getMinVectorRegisterBitWidth () const
std::optional< unsigned > getMaxVScale () const
std::optional< unsigned > getVScaleForTuning () const
bool shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const
ElementCount getMinimumVF (unsigned ElemWidth, bool IsScalable) const
unsigned getMaximumVF (unsigned ElemWidth, unsigned Opcode) const
unsigned getStoreMinimumVF (unsigned VF, Type *, Type *) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader) const
unsigned getCacheLineSize () const
std::optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
std::optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
unsigned getPrefetchDistance () const
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const
unsigned getMaxPrefetchIterationsAhead () const
bool enableWritePrefetching () const
bool shouldPrefetchAddressSpace (unsigned AS) const
unsigned getMaxInterleaveFactor (unsigned VF) const
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info, TTI::OperandValueInfo Opd2Info, ArrayRef< const Value * > Args, const Instruction *CxtI=nullptr) const
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *Ty, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType *SubTp, ArrayRef< const Value * > Args=std::nullopt) const
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index) const
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, Value *Op0, Value *Op1) const
InstructionCost getVectorInstrCost (const Instruction &I, Type *Val, TTI::TargetCostKind CostKind, unsigned Index) const
unsigned getReplicationShuffleCost (Type *EltTy, int ReplicationFactor, int VF, const APInt &DemandedDstElts, TTI::TargetCostKind CostKind)
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo, const Instruction *I) const
InstructionCost getVPMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const
InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond, bool UseMaskForGaps) const
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
unsigned getNumberOfParts (Type *Tp) const
InstructionCost getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *) const
InstructionCost getArithmeticReductionCost (unsigned, VectorType *, std::optional< FastMathFlags > FMF, TTI::TargetCostKind) const
InstructionCost getMinMaxReductionCost (VectorType *, VectorType *, bool, TTI::TargetCostKind) const
InstructionCost getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type *ResTy, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const
InstructionCost getMulAccReductionCost (bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind) const
InstructionCost getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) const
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType) const
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign, std::optional< uint32_t > AtomicElementSize) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign, std::optional< uint32_t > AtomicCpySize) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areTypesABICompatible (const Function *Caller, const Function *Callee, const ArrayRef< Type * > &Types) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeReduction (const RecurrenceDescriptor &RdxDesc, ElementCount VF) const
bool isElementTypeLegalForScalableVector (Type *Ty) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool preferInLoopReduction (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool preferPredicatedReductionSelect (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool preferEpilogueVectorization () const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
unsigned getMinTripCountTailFoldingThreshold () const
bool supportsScalableVectors () const
bool enableScalableVectorization () const
bool hasActiveVectorLength (unsigned Opcode, Type *DataType, Align Alignment) const
TargetTransformInfo::VPLegalization getVPLegalizationStrategy (const VPIntrinsic &PI) const
Vector TTI Implementations
unsigned getNumberOfRegisters (unsigned ClassID) const
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
unsigned getLoadStoreVecRegBitWidth (unsigned AS) const
unsigned getMaxInterleaveFactor (unsigned VF)
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info={TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info={TTI::OK_AnyValue, TTI::OP_None}, ArrayRef< const Value * > Args=ArrayRef< const Value * >(), const Instruction *CxtI=nullptr)
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *Tp, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType *SubTp, ArrayRef< const Value * > Args=std::nullopt)
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, Value *Op0, Value *Op1)
InstructionCost getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind)
InstructionCost getReplicationShuffleCost (Type *EltTy, int ReplicationFactor, int VF, const APInt &DemandedDstElts, TTI::TargetCostKind CostKind)
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo={TTI::OK_AnyValue, TTI::OP_None}, const Instruction *I=nullptr)
InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind)
InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I)
Calculate the cost of Gather / Scatter operation.
InstructionCost getAddressComputationCost (Type *PtrTy, ScalarEvolution *SE, const SCEV *Ptr)
std::optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const
std::optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const
std::optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const
unsigned getAtomicMemIntrinsicMaxElementSize () const
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind)
InstructionCost getArithmeticReductionCost (unsigned Opcode, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind)
InstructionCost getMinMaxCost (Type *Ty, Type *CondTy, bool IsUnsigned)
InstructionCost getMinMaxReductionCost (VectorType *Ty, VectorType *CondTy, bool IsUnsigned, TTI::TargetCostKind CostKind)
InstructionCost getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond=false, bool UseMaskForGaps=false)
InstructionCost getInterleavedMemoryOpCostAVX512 (unsigned Opcode, FixedVectorType *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond=false, bool UseMaskForGaps=false)
InstructionCost getIntImmCost (int64_t)
Calculate the cost of materializing a 64-bit value.
InstructionCost getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind)
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr)
InstructionCost getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind)
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
bool isLSRCostLess (const TargetTransformInfo::LSRCost &C1, const TargetTransformInfo::LSRCost &C2)
bool canMacroFuseCmp ()
bool isLegalMaskedLoad (Type *DataType, Align Alignment)
bool isLegalMaskedStore (Type *DataType, Align Alignment)
bool isLegalNTLoad (Type *DataType, Align Alignment)
bool isLegalNTStore (Type *DataType, Align Alignment)
bool isLegalBroadcastLoad (Type *ElementTy, ElementCount NumElements) const
bool forceScalarizeMaskedGather (VectorType *VTy, Align Alignment)
bool forceScalarizeMaskedScatter (VectorType *VTy, Align Alignment)
bool isLegalMaskedGather (Type *DataType, Align Alignment)
bool isLegalMaskedScatter (Type *DataType, Align Alignment)
bool isLegalMaskedExpandLoad (Type *DataType)
bool isLegalMaskedCompressStore (Type *DataType)
bool isLegalAltInstr (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask) const
bool hasDivRemOp (Type *DataType, bool IsSigned)
bool isExpensiveToSpeculativelyExecute (const Instruction *I)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areTypesABICompatible (const Function *Caller, const Function *Callee, const ArrayRef< Type * > &Type) const
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool prefersVectorizedAddressing () const
bool supportsEfficientVectorElementLoadStore () const
bool enableInterleavedAccessVectorization ()
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Protected Member Functions inherited from llvm::BasicTTIImplBase< X86TTIImpl >
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
virtual ~BasicTTIImplBase ()=default
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< X86TTIImpl >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned) const
bool isStridedAccess (const SCEV *Ptr) const
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr) const
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance) const
Protected Attributes inherited from llvm::BasicTTIImplBase< X86TTIImpl >
const DataLayout & DL
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Detailed Description
Definition at line 28 of file X86TargetTransformInfo.h.
Constructor & Destructor Documentation
X86TTIImpl()
llvm::X86TTIImpl::X86TTIImpl (const X86TargetMachine * TM, const Function & F) inline explicit
Definition at line 106 of file X86TargetTransformInfo.h.
Member Function Documentation
areInlineCompatible()
bool X86TTIImpl::areInlineCompatible (const Function * Caller, const Function * Callee) const
Definition at line 6063 of file X86TargetTransformInfo.cpp.
References llvm::all_of(), areTypesABICompatible(), Arg, Callee, llvm::TargetLoweringBase::getTargetMachine(), I, llvm::instructions(), and TM.
areTypesABICompatible()
bool X86TTIImpl::areTypesABICompatible (const Function * Caller, const Function * Callee, const ArrayRef< Type * > & Type) const
Definition at line 6117 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfoImplBase::areTypesABICompatible(), Callee, llvm::TargetLoweringBase::getTargetMachine(), llvm::none_of(), TM, and llvm::X86Subtarget::useAVX512Regs().
Referenced by areInlineCompatible().
canMacroFuseCmp()
bool X86TTIImpl::canMacroFuseCmp ()
Definition at line 5863 of file X86TargetTransformInfo.cpp.
enableInterleavedAccessVectorization()
bool X86TTIImpl::enableInterleavedAccessVectorization ()
Definition at line 6171 of file X86TargetTransformInfo.cpp.
enableMemCmpExpansion()
X86TTIImpl::TTI::MemCmpExpansionOptions X86TTIImpl::enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
Definition at line 6140 of file X86TargetTransformInfo.cpp.
References llvm::TargetLoweringBase::getMaxExpandSizeMemcmp(), llvm::X86Subtarget::getPreferVectorWidth(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), and Options.
forceScalarizeMaskedGather()
bool X86TTIImpl::forceScalarizeMaskedGather (VectorType * VTy, Align Alignment)
Definition at line 5976 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::hasAVX512().
Referenced by forceScalarizeMaskedScatter(), and getGatherScatterOpCost().
forceScalarizeMaskedScatter()
bool llvm::X86TTIImpl::forceScalarizeMaskedScatter (VectorType * VTy, Align Alignment) inline
Definition at line 248 of file X86TargetTransformInfo.h.
References forceScalarizeMaskedGather().
Referenced by getGatherScatterOpCost().
getAddressComputationCost()
InstructionCost X86TTIImpl::getAddressComputationCost (Type * PtrTy, ScalarEvolution * SE, const SCEV * Ptr)
Definition at line 4902 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::getAddressComputationCost(), llvm::TargetTransformInfoImplBase::getConstantStrideStep(), llvm::X86Subtarget::hasAVX2(), llvm::TargetTransformInfoImplBase::isStridedAccess(), llvm::Type::isVectorTy(), and Ptr.
getArithmeticInstrCost()
InstructionCost X86TTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Op1Info = {TTI::OK_AnyValue, TTI::OP_None}, TTI::OperandValueInfo Op2Info = {TTI::OK_AnyValue, TTI::OP_None}, ArrayRef< const Value * > Args = ArrayRef<const Value *>(), const Instruction * CxtI = nullptr)
Definition at line 220 of file X86TargetTransformInfo.cpp.
References llvm::MCID::Add, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), Cost, CostKind, getCastInstrCost(), llvm::VectorType::getExtendedElementVectorType(), llvm::TargetTransformInfo::OperandValueInfo::getNoProps(), llvm::Type::getScalarSizeInBits(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::MVT::getVectorVT(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::TargetTransformInfo::OperandValueInfo::isConstant(), llvm::TargetTransformInfo::OperandValueInfo::isNegatedPowerOf2(), llvm::TargetTransformInfo::OperandValueInfo::isPowerOf2(), llvm::TargetTransformInfo::OperandValueInfo::isUniform(), llvm::Type::isVectorTy(), llvm::AArch64CC::LT, llvm::max(), llvm::TargetTransformInfoImplBase::minRequiredElementSize(), Mul, llvm::ISD::MUL, llvm::TargetTransformInfo::None, llvm::ISD::SDIV, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::UDIV, llvm::ISD::UREM, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4i32, and llvm::MVT::v64i8.
Referenced by getCmpSelInstrCost(), and getInterleavedMemoryOpCostAVX512().
getArithmeticReductionCost()
InstructionCost X86TTIImpl::getArithmeticReductionCost (unsigned Opcode, VectorType * Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind)
Definition at line 4931 of file X86TargetTransformInfo.cpp.
References llvm::ISD::ADD, assert(), CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::ISD::FADD, llvm::BasicTTIImplBase< X86TTIImpl >::getArithmeticReductionCost(), llvm::EVT::getSimpleVT(), llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::EVT::isSimple(), llvm::TargetTransformInfo::requiresOrderedReduction(), llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v8f32, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i8.
getAtomicMemIntrinsicMaxElementSize()
unsigned X86TTIImpl::getAtomicMemIntrinsicMaxElementSize () const
Definition at line 3320 of file X86TargetTransformInfo.cpp.
getCacheAssociativity()
std::optional< unsigned > X86TTIImpl::getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 142 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
getCacheSize()
std::optional< unsigned > X86TTIImpl::getCacheSize (TargetTransformInfo::CacheLevel Level) const override virtual
Reimplemented from llvm::BasicTTIImplBase< X86TTIImpl >.
Definition at line 112 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
getCastInstrCost()
InstructionCost X86TTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction * I = nullptr)
Definition at line 2058 of file X86TargetTransformInfo.cpp.
References assert(), Cost, CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::EVT::getSimpleVT(), llvm::TargetLoweringBase::getValueType(), llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::EVT::isSimple(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::TargetTransformInfo::TCK_RecipThroughput, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::X86Subtarget::useAVX512Regs(), llvm::MVT::v16f32, llvm::MVT::v16f64, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v16i8, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32f32, llvm::MVT::v32f64, llvm::MVT::v32i1, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v64f32, llvm::MVT::v64f64, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::ISD::ZERO_EXTEND.
Referenced by getArithmeticInstrCost(), and getReplicationShuffleCost().
getCFInstrCost()
InstructionCost X86TTIImpl::getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction * I = nullptr)
Definition at line 5665 of file X86TargetTransformInfo.cpp.
References CostKind, PHI, and llvm::TargetTransformInfo::TCK_RecipThroughput.
Referenced by getMaskedMemoryOpCost().
getCmpSelInstrCost()
InstructionCost X86TTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction * I = nullptr)
Definition at line 3028 of file X86TargetTransformInfo.cpp.
References assert(), llvm::CmpInst::BAD_FCMP_PREDICATE, llvm::CmpInst::BAD_ICMP_PREDICATE, CostKind, llvm::MVT::f32, llvm::MVT::f64, getArithmeticInstrCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getCmpSelInstrCost(), llvm::MVT::getScalarSizeInBits(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), I, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::MVT::is128BitVector(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntOrIntVectorTy(), llvm::MVT::isVector(), llvm::AArch64CC::LT, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
Referenced by getMaskedMemoryOpCost().
getGatherScatterOpCost()
InstructionCost X86TTIImpl::getGatherScatterOpCost (unsigned Opcode, Type * DataTy, const Value * Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction * I = nullptr)
Calculate the cost of Gather / Scatter operation.
Definition at line 5812 of file X86TargetTransformInfo.cpp.
References Align, assert(), CostKind, forceScalarizeMaskedGather(), forceScalarizeMaskedScatter(), llvm::PointerType::getAddressSpace(), llvm::BasicTTIImplBase< X86TTIImpl >::getGatherScatterOpCost(), I, isLegalMaskedGather(), isLegalMaskedScatter(), llvm::Type::isVectorTy(), llvm::SPII::Load, Ptr, llvm::SPII::Store, and llvm::TargetTransformInfo::TCK_RecipThroughput.
getInterleavedMemoryOpCost()
InstructionCost X86TTIImpl::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond = false, bool UseMaskForGaps = false)
Definition at line 6335 of file X86TargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::FixedVectorType::get(), llvm::Type::getContext(), llvm::BasicTTIImplBase< X86TTIImpl >::getInterleavedMemoryOpCost(), getInterleavedMemoryOpCostAVX512(), llvm::Type::getIntNTy(), getMemoryOpCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::DataLayout::getTypeSizeInBits(), llvm::TargetLoweringBase::getValueType(), llvm::X86Subtarget::hasAVX512(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::EVT::isSimple(), llvm::MVT::isVector(), llvm::SPII::Load, llvm::ArrayRef< T >::size(), llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v16i8, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32i16, llvm::MVT::v32i32, llvm::MVT::v32i64, llvm::MVT::v32i8, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, and llvm::MVT::v8i8.
getInterleavedMemoryOpCostAVX512()
InstructionCost X86TTIImpl::getInterleavedMemoryOpCostAVX512 (unsigned Opcode, FixedVectorType * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond = false, bool UseMaskForGaps = false)
Definition at line 6182 of file X86TargetTransformInfo.cpp.
References assert(), CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::FixedVectorType::get(), llvm::APInt::getAllOnes(), getArithmeticInstrCost(), llvm::Type::getContext(), llvm::VectorType::getElementType(), llvm::Type::getInt1Ty(), getMaskedMemoryOpCost(), getMemoryOpCost(), llvm::FixedVectorType::getNumElements(), getReplicationShuffleCost(), llvm::Type::getScalarType(), llvm::MVT::getStoreSize(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::DataLayout::getTypeStoreSize(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::getVT(), llvm::APInt::getZero(), llvm::SPII::Load, llvm::APInt::setBit(), llvm::MVT::v16i8, llvm::MVT::v32i8, and llvm::MVT::v64i8.
Referenced by getInterleavedMemoryOpCost().
getIntImmCost() [1/2]
InstructionCost X86TTIImpl::getIntImmCost (const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind)
Definition at line 5495 of file X86TargetTransformInfo.cpp.
References llvm::alignTo(), llvm::APInt::ashr(), assert(), Cost, getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSExtValue(), llvm::RISCVMatInt::Imm, llvm::Type::isIntegerTy(), llvm::APInt::sextOrTrunc(), and llvm::TargetTransformInfo::TCC_Free.
getIntImmCost() [2/2]
InstructionCost X86TTIImpl::getIntImmCost (int64_t Val)
Calculate the cost of materializing a 64-bit value.
This helper method might only calculate a fraction of a larger immediate. Therefore it is valid to return a cost of ZERO.
Definition at line 5485 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::TCC_Basic, and llvm::TargetTransformInfo::TCC_Free.
Referenced by getIntImmCost(), getIntImmCostInst(), and getIntImmCostIntrin().
getIntImmCostInst()
InstructionCost X86TTIImpl::getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind, Instruction * Inst = nullptr)
Definition at line 5530 of file X86TargetTransformInfo.cpp.
References llvm::MCID::Add, assert(), llvm::MCID::Call, Cost, CostKind, llvm::divideCeil(), getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::RISCVMatInt::Imm, llvm::Type::isIntegerTy(), llvm::SPII::Load, Mul, PHI, llvm::MipsISD::Ret, Select, llvm::SPII::Store, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCC_Free, and uint64_t.
getIntImmCostIntrin()
InstructionCost X86TTIImpl::getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind)
Definition at line 5629 of file X86TargetTransformInfo.cpp.
References assert(), CostKind, getIntImmCost(), llvm::Type::getPrimitiveSizeInBits(), llvm::RISCVMatInt::Imm, llvm::Type::isIntegerTy(), and llvm::TargetTransformInfo::TCC_Free.
getIntrinsicInstrCost()
InstructionCost X86TTIImpl::getIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind)
Definition at line 3323 of file X86TargetTransformInfo.cpp.
References llvm::ISD::ABS, llvm::abs(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::ISD::BITREVERSE, llvm::ISD::BSWAP, Cost, CostKind, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::DELETED_NODE, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FSHL, llvm::ISD::FSQRT, llvm::IntrinsicCostAttributes::getArgs(), llvm::Type::getContainedType(), llvm::IntrinsicCostAttributes::getID(), llvm::IntrinsicCostAttributes::getReturnType(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::MVT::getVectorElementType(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasSSSE3(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, int, llvm::MVT::is128BitVector(), llvm::MVT::is256BitVector(), llvm::MVT::is512BitVector(), llvm::IntrinsicCostAttributes::isTypeBasedOnly(), llvm::MVT::isVector(), llvm::AArch64CC::LT, llvm::maxnum(), llvm::minnum(), llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SADDSAT, llvm::ISD::SMAX, llvm::APIntOps::smax(), llvm::ISD::SMIN, llvm::APIntOps::smin(), llvm::ISD::SSUBSAT, llvm::TargetTransformInfo::TCK_CodeSize, llvm::ISD::UADDO, llvm::ISD::UADDSAT, llvm::ISD::UMAX, llvm::APIntOps::umax(), llvm::ISD::UMIN, llvm::APIntOps::umin(), llvm::ISD::UMULO, llvm::ISD::USUBSAT, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
getLoadStoreVecRegBitWidth()
unsigned X86TTIImpl::getLoadStoreVecRegBitWidth (unsigned AS) const
Definition at line 197 of file X86TargetTransformInfo.cpp.
References llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), getRegisterBitWidth(), and llvm::TargetTransformInfo::RGK_FixedWidthVector.
getMaskedMemoryOpCost()
InstructionCost X86TTIImpl::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind)
Definition at line 4841 of file X86TargetTransformInfo.cpp.
References llvm::CmpInst::BAD_ICMP_PREDICATE, Cost, CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::FixedVectorType::get(), llvm::APInt::getAllOnes(), getCFInstrCost(), getCmpSelInstrCost(), llvm::Type::getInt8Ty(), getMemoryOpCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getMemoryOpCost(), getScalarizationOverhead(), getShuffleCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::X86Subtarget::hasAVX512(), isLegalMaskedLoad(), isLegalMaskedStore(), llvm::SPII::Load, llvm::AArch64CC::LT, llvm::TargetTransformInfo::SK_InsertSubvector, llvm::TargetTransformInfo::SK_PermuteTwoSrc, and llvm::SPII::Store.
Referenced by getInterleavedMemoryOpCostAVX512().
getMaxInterleaveFactor()
unsigned X86TTIImpl::getMaxInterleaveFactor (unsigned VF)
Definition at line 202 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::hasAVX().
getMemoryOpCost()
InstructionCost X86TTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, MaybeAlign Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo = {TTI::OK_AnyValue, TTI::OP_None}, const Instruction * I = nullptr)
Definition at line 4678 of file X86TargetTransformInfo.cpp.
References llvm::all_of(), assert(), llvm::commonAlignment(), Cost, CostKind, llvm::APInt::countPopulation(), llvm::divideCeil(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, GEP, llvm::IntegerType::get(), llvm::FixedVectorType::get(), llvm::DataLayout::getABITypeAlign(), llvm::APInt::getBitsSet(), llvm::BasicTTIImplBase< X86TTIImpl >::getMemoryOpCost(), getScalarizationOverhead(), getShuffleCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::DataLayout::getTypeSizeInBits(), llvm::TargetLoweringBase::getValueType(), I, llvm::TargetTransformInfo::OperandValueInfo::isConstant(), llvm::SPII::Load, llvm::AArch64CC::LT, llvm::MVT::Other, SI, llvm::SPII::Store, llvm::TargetTransformInfo::TCC_Basic, llvm::TargetTransformInfo::TCK_RecipThroughput, and llvm::MaybeAlign::valueOrOne().
Referenced by getInterleavedMemoryOpCost(), getInterleavedMemoryOpCostAVX512(), getMaskedMemoryOpCost(), and getVectorInstrCost().
getMinMaxCost()
InstructionCost X86TTIImpl::getMinMaxCost (Type * Ty, Type * CondTy, bool IsUnsigned)
Definition at line 5181 of file X86TargetTransformInfo.cpp.
References assert(), llvm::ISD::FMINNUM, llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntOrIntVectorTy(), llvm::AArch64CC::LT, llvm::ISD::SMIN, llvm::ISD::UMIN, llvm::MVT::v16f32, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v64i8, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i16, llvm::MVT::v8i32, and llvm::MVT::v8i64.
getMinMaxReductionCost()
InstructionCost X86TTIImpl::getMinMaxReductionCost (VectorType * Ty, VectorType * CondTy, bool IsUnsigned, TTI::TargetCostKind CostKind)
Definition at line 5310 of file X86TargetTransformInfo.cpp.
References assert(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::ISD::FMINNUM, llvm::EVT::getSimpleVT(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isIntOrIntVectorTy(), llvm::EVT::isSimple(), llvm::AArch64CC::LT, llvm::ISD::SMIN, llvm::ISD::UMIN, llvm::MVT::v16i16, llvm::MVT::v16i8, llvm::MVT::v2i16, llvm::MVT::v2i8, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4i16, llvm::MVT::v4i8, llvm::MVT::v64i8, llvm::MVT::v8i16, and llvm::MVT::v8i8.
getNumberOfRegisters()
unsigned X86TTIImpl::getNumberOfRegisters (unsigned ClassID) const
Definition at line 163 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE1(), and Vector.
getPopcntSupport()
TargetTransformInfo::PopcntSupportKind X86TTIImpl::getPopcntSupport (unsigned TyWidth)
Definition at line 104 of file X86TargetTransformInfo.cpp.
References assert(), llvm::isPowerOf2_32(), llvm::TargetTransformInfo::PSK_FastHardware, and llvm::TargetTransformInfo::PSK_Software.
getRegisterBitWidth()
TypeSize X86TTIImpl::getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
Definition at line 177 of file X86TargetTransformInfo.cpp.
References llvm::TypeSize::getFixed(), llvm::X86Subtarget::getPreferVectorWidth(), llvm::TypeSize::getScalable(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE1(), llvm_unreachable, llvm::TargetTransformInfo::RGK_FixedWidthVector, llvm::TargetTransformInfo::RGK_ScalableVector, and llvm::TargetTransformInfo::RGK_Scalar.
Referenced by getLoadStoreVecRegBitWidth().
getReplicationShuffleCost()
InstructionCost X86TTIImpl::getReplicationShuffleCost (Type * EltTy, int ReplicationFactor, int VF, const APInt & DemandedDstElts, TTI::TargetCostKind CostKind)
Definition at line 4573 of file X86TargetTransformInfo.cpp.
References assert(), CostKind, llvm::APInt::countPopulation(), llvm::divideCeil(), llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::FixedVectorType::get(), getCastInstrCost(), llvm::Type::getContext(), llvm::Type::getIntNTy(), llvm::BasicTTIImplBase< X86TTIImpl >::getReplicationShuffleCost(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), getShuffleCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::DataLayout::getTypeSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::X86Subtarget::hasAVX512(), llvm::MVT::isVector(), llvm::TargetTransformInfo::None, llvm::APIntOps::ScaleBitMask(), llvm::TargetTransformInfo::SK_PermuteSingleSrc, and llvm::APInt::zext().
Referenced by getInterleavedMemoryOpCostAVX512().
getScalarizationOverhead()
InstructionCost X86TTIImpl::getScalarizationOverhead (VectorType * Ty, const APInt & DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind)
Definition at line 4409 of file X86TargetTransformInfo.cpp.
References assert(), Cost, CostKind, llvm::APInt::countPopulation(), llvm::APInt::extractBits(), llvm::MVT::f32, llvm::FixedVectorType::get(), llvm::APInt::getBitWidth(), llvm::VectorType::getElementType(), llvm::BasicTTIImplBase< X86TTIImpl >::getScalarizationOverhead(), llvm::Type::getScalarSizeInBits(), getShuffleCost(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), I, llvm::MVT::i16, Insert, llvm::APInt::isAllOnes(), llvm::MVT::isInteger(), llvm::Type::isIntOrIntVectorTy(), llvm::APInt::isNullValue(), llvm::AArch64CC::LT, llvm::PowerOf2Ceil(), llvm::APIntOps::ScaleBitMask(), llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_InsertSubvector, and llvm::APInt::zext().
Referenced by getMaskedMemoryOpCost(), and getMemoryOpCost().
getScalingFactorCost()
InstructionCost X86TTIImpl::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
If the AM is supported, the return value must be >= 0. If the AM is not supported, it returns a negative value.
Definition at line 6648 of file X86TargetTransformInfo.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::TargetLoweringBase::AddrMode::HasBaseReg, llvm::BasicTTIImplBase< X86TTIImpl >::isLegalAddressingMode(), and llvm::TargetLoweringBase::AddrMode::Scale.
getShuffleCost()
InstructionCost X86TTIImpl::getShuffleCost (TTI::ShuffleKind Kind, VectorType * Tp, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType * SubTp, ArrayRef< const Value * > Args = std::nullopt)
Definition at line 1437 of file X86TargetTransformInfo.cpp.
References llvm::alignDown(), assert(), CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::FixedVectorType::get(), llvm::VectorType::getElementType(), llvm::Type::getPrimitiveSizeInBits(), llvm::EVT::getSizeInBits(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::TargetLoweringBase::getValueType(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSSE3(), llvm::BasicTTIImplBase< X86TTIImpl >::improveShuffleKindFromMask(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm::AArch64CC::LT, llvm::BitmaskEnumDetail::Mask(), llvm::TargetTransformInfo::SK_Broadcast, llvm::TargetTransformInfo::SK_ExtractSubvector, llvm::TargetTransformInfo::SK_InsertSubvector, llvm::TargetTransformInfo::SK_PermuteSingleSrc, llvm::TargetTransformInfo::SK_PermuteTwoSrc, llvm::TargetTransformInfo::SK_Reverse, llvm::TargetTransformInfo::SK_Splice, llvm::TargetTransformInfo::SK_Transpose, llvm::MVT::v2i16, llvm::MVT::v2i8, llvm::MVT::v4i16, llvm::MVT::v4i8, and llvm::MVT::v8i8.
Referenced by getMaskedMemoryOpCost(), getMemoryOpCost(), getReplicationShuffleCost(), and getScalarizationOverhead().
getVectorInstrCost()
InstructionCost X86TTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, Value * Op0, Value * Op1)
Definition at line 4259 of file X86TargetTransformInfo.cpp.
References assert(), CostKind, llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, getMemoryOpCost(), llvm::DataLayout::getPrefTypeAlign(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::BasicTTIImplBase< X86TTIImpl >::getTypeLegalizationCost(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::Type::isFloatingPointTy(), llvm::MVT::isInteger(), llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), llvm::SPII::Load, llvm::AArch64CC::LT, and llvm::SPII::Store.
hasDivRemOp()
bool X86TTIImpl::hasDivRemOp (Type * DataType, bool IsSigned)
Definition at line 6045 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::isOperationLegal(), llvm::ISD::SDIVREM, and llvm::ISD::UDIVREM.
instCombineIntrinsic()
std::optional< Instruction * > X86TTIImpl::instCombineIntrinsic (InstCombiner & IC, IntrinsicInst & II) const
Definition at line 929 of file X86InstCombineIntrinsic.cpp.
References Arg, assert(), llvm::BitWidth, llvm::InstCombiner::Builder, C1, llvm::SelectInst::Create(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateExtractElement(), llvm::IRBuilderBase::CreateFAdd(), llvm::IRBuilderBase::CreateFDiv(), llvm::IRBuilderBase::CreateFMul(), llvm::IRBuilderBase::CreateFSub(), llvm::IRBuilderBase::CreateInsertElement(), llvm::IRBuilderBase::CreateLShr(), llvm::IRBuilderBase::CreateSelect(), llvm::IRBuilderBase::CreateShl(), llvm::ConstantInt::get(), llvm::ConstantAggregateZero::get(), llvm::FixedVectorType::get(), llvm::CallBase::getArgOperand(), llvm::IntegerType::getBitWidth(), llvm::IRBuilderBase::getInt1Ty(), llvm::Type::getIntegerBitWidth(), llvm::IntrinsicInst::getIntrinsicID(), llvm::APInt::getLowBitsSet(), getNegativeIsTrueBoolVec(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSplat(), llvm::Value::getType(), llvm::APInt::getZExtValue(), I, llvm::RISCVMatInt::Imm, llvm::APInt::isSubsetOf(), llvm::Type::isVectorTy(), llvm::Length, LHS, llvm_unreachable, llvm::APInt::lshr(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), llvm::InstCombiner::peekThroughBitcast(), llvm::InstCombiner::replaceInstUsesWith(), llvm::InstCombiner::replaceOperand(), RHS, Shift, llvm::InstCombiner::SimplifyDemandedVectorElts(), simplifyX86addcarry(), simplifyX86extrq(), simplifyX86immShift(), simplifyX86insertps(), simplifyX86insertq(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), simplifyX86movmsk(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86vpermv(), uint64_t, and llvm::APInt::zextOrTrunc().
isExpensiveToSpeculativelyExecute()
bool X86TTIImpl::isExpensiveToSpeculativelyExecute (const Instruction * I)
Definition at line 6050 of file X86TargetTransformInfo.cpp.
References I, and llvm::TargetTransformInfoImplCRTPBase< X86TTIImpl >::isExpensiveToSpeculativelyExecute().
isFCmpOrdCheaperThanFCmpZero()
bool X86TTIImpl::isFCmpOrdCheaperThanFCmpZero (Type * Ty)
Definition at line 6059 of file X86TargetTransformInfo.cpp.
isLegalAltInstr()
bool X86TTIImpl::isLegalAltInstr (VectorType * VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector & OpcodeMask) const
Definition at line 6005 of file X86TargetTransformInfo.cpp.
References assert(), llvm::X86Subtarget::hasSSE3(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::isPowerOf2_32(), llvm::SmallBitVector::size(), and llvm::SmallBitVector::test().
isLegalBroadcastLoad()
bool X86TTIImpl::isLegalBroadcastLoad (Type * ElementTy, ElementCount NumElements) const
Definition at line 5933 of file X86TargetTransformInfo.cpp.
References llvm::Type::getContext(), llvm::Type::getDoubleTy(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::X86Subtarget::hasSSE3(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
isLegalMaskedCompressStore()
bool X86TTIImpl::isLegalMaskedCompressStore (Type * DataType)
Definition at line 5965 of file X86TargetTransformInfo.cpp.
References isLegalMaskedExpandLoad().
isLegalMaskedExpandLoad()
bool X86TTIImpl::isLegalMaskedExpandLoad (Type * DataType)
Definition at line 5941 of file X86TargetTransformInfo.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::X86Subtarget::hasAVX512(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), and llvm::Type::isIntegerTy().
Referenced by isLegalMaskedCompressStore().
isLegalMaskedGather()
bool X86TTIImpl::isLegalMaskedGather (Type * DataType, Align Alignment)
Definition at line 5988 of file X86TargetTransformInfo.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::getScalarType(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by getGatherScatterOpCost(), and isLegalMaskedScatter().
isLegalMaskedLoad()
bool X86TTIImpl::isLegalMaskedLoad (Type * DataType, Align Alignment)
Definition at line 5867 of file X86TargetTransformInfo.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::getScalarType(), llvm::X86Subtarget::hasAVX(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by getMaskedMemoryOpCost(), and isLegalMaskedStore().
isLegalMaskedScatter()
bool X86TTIImpl::isLegalMaskedScatter (Type * DataType, Align Alignment)
Definition at line 6038 of file X86TargetTransformInfo.cpp.
References llvm::X86Subtarget::hasAVX512(), and isLegalMaskedGather().
Referenced by getGatherScatterOpCost().
isLegalMaskedStore()
bool X86TTIImpl::isLegalMaskedStore (Type * DataType, Align Alignment)
Definition at line 5894 of file X86TargetTransformInfo.cpp.
References isLegalMaskedLoad().
Referenced by getMaskedMemoryOpCost().
isLegalNTLoad()
bool X86TTIImpl::isLegalNTLoad (Type * DataType, Align Alignment)
Definition at line 5898 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::DataLayout::getTypeStoreSize(), llvm::X86Subtarget::hasAVX2(), and llvm::X86Subtarget::hasSSE1().
isLegalNTStore()
bool X86TTIImpl::isLegalNTStore (Type * DataType, Align Alignment)
Definition at line 5909 of file X86TargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< X86TTIImpl >::DL, llvm::DataLayout::getTypeStoreSize(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasSSE1(), and llvm::isPowerOf2_32().
isLSRCostLess()
bool X86TTIImpl::isLSRCostLess (const TargetTransformInfo::LSRCost & C1, const TargetTransformInfo::LSRCost & C2)
Definition at line 5852 of file X86TargetTransformInfo.cpp.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, C1, llvm::TargetTransformInfo::LSRCost::ImmCost, llvm::TargetTransformInfo::LSRCost::Insns, llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
prefersVectorizedAddressing()
bool X86TTIImpl::prefersVectorizedAddressing () const
Definition at line 6163 of file X86TargetTransformInfo.cpp.
simplifyDemandedUseBitsIntrinsic()
std::optional< Value * > X86TTIImpl::simplifyDemandedUseBitsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedMask, KnownBits & Known, bool & KnownBitsComputed) const
Definition at line 1737 of file X86InstCombineIntrinsic.cpp.
References llvm::CallBase::getArgOperand(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::APInt::isZero(), llvm::APInt::setBitsFrom(), llvm::KnownBits::Zero, and llvm::APInt::zextOrTrunc().
simplifyDemandedVectorEltsIntrinsic()
std::optional< Value * > X86TTIImpl::simplifyDemandedVectorEltsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedElts, APInt & UndefElts, APInt & UndefElts2, APInt & UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const
Definition at line 1777 of file X86InstCombineIntrinsic.cpp.
References llvm::InstCombiner::addToWorklist(), assert(), llvm::InstCombiner::Builder, llvm::APInt::clearBit(), llvm::IRBuilderBase::CreateBinOp(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::IntrinsicInst::getIntrinsicID(), llvm::APInt::getLoBits(), llvm::APInt::getSplat(), llvm::Value::getType(), llvm::APInt::isSubsetOf(), llvm::APInt::lshr(), llvm::APInt::setBit(), llvm::APInt::setHighBits(), llvm::IRBuilderBase::SetInsertPoint(), x2(), and llvm::APInt::zext().
supportsEfficientVectorElementLoadStore()
bool X86TTIImpl::supportsEfficientVectorElementLoadStore () const
Definition at line 6167 of file X86TargetTransformInfo.cpp.
The documentation for this class was generated from the following files:
lib/Target/X86/X86TargetTransformInfo.h
lib/Target/X86/X86InstCombineIntrinsic.cpp
lib/Target/X86/X86TargetTransformInfo.cpp