LLVM: llvm::MLInlineAdvice Class Reference
llvm::MLInlineAdvice Class Reference
InlineAdvice that tracks changes post inlining.
#include "llvm/Analysis/MLInlineAdvisor.h"
Public Member Functions
MLInlineAdvice (MLInlineAdvisor *Advisor, CallBase &CB, OptimizationRemarkEmitter &ORE, bool Recommendation)
virtual ~MLInlineAdvice ()=default
void recordInliningImpl () override
void recordInliningWithCalleeDeletedImpl () override
void recordUnsuccessfulInliningImpl (const InlineResult &Result) override
void recordUnattemptedInliningImpl () override
Function * getCaller () const
Function * getCallee () const
void updateCachedCallerFPI (FunctionAnalysisManager &FAM) const
Public Member Functions inherited from llvm::InlineAdvice
InlineAdvice (InlineAdvisor *Advisor, CallBase &CB, OptimizationRemarkEmitter &ORE, bool IsInliningRecommended)
InlineAdvice (InlineAdvice &&)=delete
InlineAdvice (const InlineAdvice &)=delete
virtual ~InlineAdvice ()
void recordInlining ()
Exactly one of the record* APIs must be called.
void recordInliningWithCalleeDeleted ()
Call after inlining succeeded, and results in the callee being delete-able, meaning, it has no more users, and will be cleaned up subsequently.
void recordUnsuccessfulInlining (const InlineResult &Result)
Call after the decision for a call site was to not inline.
void recordUnattemptedInlining ()
Call to indicate inlining was not attempted.
bool isInliningRecommended () const
Get the inlining recommendation.
const DebugLoc & getOriginalCallSiteDebugLoc () const
const BasicBlock * getOriginalCallSiteBasicBlock () const
Public Attributes
const int64_t CallerIRSize
const int64_t CalleeIRSize
const int64_t CallerAndCalleeEdges
Additional Inherited Members
Protected Attributes inherited from llvm::InlineAdvice
InlineAdvisor *const Advisor
Function *const Caller
Caller and Callee are pre-inlining.
Function *const Callee
const DebugLoc DLoc
const BasicBlock *const Block
OptimizationRemarkEmitter & ORE
const bool IsInliningRecommended
Detailed Description
InlineAdvice that tracks changes post inlining.
For that reason, it only overrides the "successful inlining" extension points.
Definition at line 94 of file MLInlineAdvisor.h.
Constructor & Destructor Documentation
MLInlineAdvice()
MLInlineAdvice::MLInlineAdvice (MLInlineAdvisor * Advisor, CallBase & CB, OptimizationRemarkEmitter & ORE, bool Recommendation)
Definition at line 447 of file MLInlineAdvisor.cpp.
References llvm::InlineAdvice::Advisor, Callee, and getCaller().
~MLInlineAdvice()
virtual llvm::MLInlineAdvice::~MLInlineAdvice () virtual default
Member Function Documentation
getCallee()
Function* llvm::MLInlineAdvice::getCallee () const inline
Definition at line 106 of file MLInlineAdvisor.h.
References llvm::InlineAdvice::Callee.
Referenced by llvm::MLInlineAdvisor::onSuccessfulInlining().
getCaller()
Function* llvm::MLInlineAdvice::getCaller () const inline
Definition at line 105 of file MLInlineAdvisor.h.
References llvm::InlineAdvice::Caller.
Referenced by MLInlineAdvice(), and llvm::MLInlineAdvisor::onSuccessfulInlining().
recordInliningImpl()
void MLInlineAdvice::recordInliningImpl () override virtual
Reimplemented from llvm::InlineAdvice.
Definition at line 476 of file MLInlineAdvisor.cpp.
References llvm::InlineAdvice::Block, DEBUG_TYPE, llvm::InlineAdvice::DLoc, llvm::OptimizationRemarkEmitter::emit(), llvm::MLInlineAdvisor::onSuccessfulInlining(), and llvm::InlineAdvice::ORE.
recordInliningWithCalleeDeletedImpl()
void MLInlineAdvice::recordInliningWithCalleeDeletedImpl () override virtual
Reimplemented from llvm::InlineAdvice.
Definition at line 485 of file MLInlineAdvisor.cpp.
References llvm::InlineAdvice::Block, DEBUG_TYPE, llvm::InlineAdvice::DLoc, llvm::OptimizationRemarkEmitter::emit(), llvm::MLInlineAdvisor::onSuccessfulInlining(), and llvm::InlineAdvice::ORE.
recordUnattemptedInliningImpl()
void MLInlineAdvice::recordUnattemptedInliningImpl () override virtual
Reimplemented from llvm::InlineAdvice.
Definition at line 505 of file MLInlineAdvisor.cpp.
References assert(), llvm::InlineAdvice::Block, DEBUG_TYPE, llvm::InlineAdvice::DLoc, llvm::OptimizationRemarkEmitter::emit(), and llvm::InlineAdvice::ORE.
recordUnsuccessfulInliningImpl()
void MLInlineAdvice::recordUnsuccessfulInliningImpl (const InlineResult & Result) override virtual
Reimplemented from llvm::InlineAdvice.
Definition at line 495 of file MLInlineAdvisor.cpp.
References llvm::InlineAdvice::Block, llvm::InlineAdvice::Caller, DEBUG_TYPE, llvm::InlineAdvice::DLoc, llvm::OptimizationRemarkEmitter::emit(), llvm::MLInlineAdvisor::getCachedFPI(), and llvm::InlineAdvice::ORE.
updateCachedCallerFPI()
void MLInlineAdvice::updateCachedCallerFPI (FunctionAnalysisManager & FAM) const
Definition at line 472 of file MLInlineAdvisor.cpp.
References FAM.
Referenced by llvm::MLInlineAdvisor::onSuccessfulInlining().
Member Data Documentation
CalleeIRSize
const int64_t llvm::MLInlineAdvice::CalleeIRSize
Definition at line 109 of file MLInlineAdvisor.h.
Referenced by llvm::MLInlineAdvisor::onSuccessfulInlining().
CallerAndCalleeEdges
const int64_t llvm::MLInlineAdvice::CallerAndCalleeEdges
Definition at line 110 of file MLInlineAdvisor.h.
Referenced by llvm::MLInlineAdvisor::onSuccessfulInlining().
CallerIRSize
const int64_t llvm::MLInlineAdvice::CallerIRSize
Definition at line 108 of file MLInlineAdvisor.h.
Referenced by llvm::MLInlineAdvisor::onSuccessfulInlining().
The documentation for this class was generated from the following files:
include/llvm/Analysis/MLInlineAdvisor.h
lib/Analysis/MLInlineAdvisor.cpp