LLVM: llvm::ContextTrieNode Class Reference
llvm::ContextTrieNode Class Reference
#include "llvm/Transforms/IPO/SampleContextTracker.h"
Public Member Functions
ContextTrieNode (ContextTrieNode *Parent=nullptr, StringRef FName=StringRef(), FunctionSamples *FSamples=nullptr, LineLocation CallLoc={0, 0})
ContextTrieNode * getChildContext (const LineLocation &CallSite, StringRef ChildName)
ContextTrieNode * getHottestChildContext (const LineLocation &CallSite)
ContextTrieNode * getOrCreateChildContext (const LineLocation &CallSite, StringRef ChildName, bool AllowCreate=true)
void removeChildContext (const LineLocation &CallSite, StringRef ChildName)
std::map< uint64_t, ContextTrieNode > & getAllChildContext ()
StringRef getFuncName () const
FunctionSamples * getFunctionSamples () const
void setFunctionSamples (FunctionSamples *FSamples)
std::optional< uint32_t > getFunctionSize () const
void addFunctionSize (uint32_t FSize)
LineLocation getCallSiteLoc () const
ContextTrieNode * getParentContext () const
void setParentContext (ContextTrieNode *Parent)
void setCallSiteLoc (const LineLocation &Loc)
void dumpNode ()
void dumpTree ()
Detailed Description
Definition at line 35 of file SampleContextTracker.h.
Constructor & Destructor Documentation
ContextTrieNode()
llvm::ContextTrieNode::ContextTrieNode (ContextTrieNode * Parent = nullptr, StringRef FName = StringRef(), FunctionSamples * FSamples = nullptr, LineLocation CallLoc = {0, 0}) inline
Definition at line 37 of file SampleContextTracker.h.
Member Function Documentation
addFunctionSize()
void llvm::ContextTrieNode::addFunctionSize (uint32_t FSize)
Definition at line 131 of file SampleContextTracker.cpp.
dumpNode()
void llvm::ContextTrieNode::dumpNode ()
Definition at line 152 of file SampleContextTracker.cpp.
References llvm::dbgs().
dumpTree()
void llvm::ContextTrieNode::dumpTree ()
Definition at line 163 of file SampleContextTracker.cpp.
References llvm::dbgs().
Referenced by llvm::SampleContextTracker::dump().
getAllChildContext()
std::map< uint64_t, ContextTrieNode > & llvm::ContextTrieNode::getAllChildContext ()
Definition at line 113 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor(), llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph(), and llvm::SampleContextTracker::promoteMergeContextSamplesTree().
getCallSiteLoc()
LineLocation llvm::ContextTrieNode::getCallSiteLoc () const
Definition at line 138 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor(), and llvm::SampleContextTracker::promoteMergeContextSamplesTree().
getChildContext()
ContextTrieNode * llvm::ContextTrieNode::getChildContext (const LineLocation & CallSite, StringRef ChildName)
Definition at line 31 of file SampleContextTracker.cpp.
References llvm::StringRef::empty(), llvm::sampleprof::FunctionSamples::getCallSiteHash(), and uint64_t.
Referenced by llvm::SampleContextTracker::getOrCreateContextPath(), and llvm::SampleContextTracker::promoteMergeContextSamplesTree().
getFuncName()
StringRef llvm::ContextTrieNode::getFuncName () const
Definition at line 117 of file SampleContextTracker.cpp.
getFunctionSamples()
FunctionSamples * llvm::ContextTrieNode::getFunctionSamples () const
Definition at line 119 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getCalleeContextSamplesFor(), llvm::SampleContextTracker::getContextSamplesFor(), getHottestChildContext(), llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor(), llvm::SampleContextTracker::promoteMergeContextSamplesTree(), and llvm::SampleContextTracker::SampleContextTracker().
getFunctionSize()
std::optional< uint32_t > llvm::ContextTrieNode::getFunctionSize () const
Definition at line 127 of file SampleContextTracker.cpp.
getHottestChildContext()
ContextTrieNode * llvm::ContextTrieNode::getHottestChildContext (const LineLocation & CallSite)
Definition at line 44 of file SampleContextTracker.cpp.
References getFunctionSamples(), llvm::sampleprof::FunctionSamples::getTotalSamples(), and uint64_t.
getOrCreateChildContext()
ContextTrieNode * llvm::ContextTrieNode::getOrCreateChildContext (const LineLocation & CallSite, StringRef ChildName, bool AllowCreate = true)
Definition at line 180 of file SampleContextTracker.cpp.
References assert(), llvm::sampleprof::FunctionSamples::getCallSiteHash(), and uint64_t.
Referenced by llvm::SampleContextTracker::getOrCreateContextPath().
getParentContext()
ContextTrieNode * llvm::ContextTrieNode::getParentContext () const
Definition at line 140 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getContextSamplesFor().
removeChildContext()
void llvm::ContextTrieNode::removeChildContext (const LineLocation & CallSite, StringRef ChildName)
Definition at line 106 of file SampleContextTracker.cpp.
References llvm::sampleprof::FunctionSamples::getCallSiteHash(), and uint64_t.
setCallSiteLoc()
void llvm::ContextTrieNode::setCallSiteLoc (const LineLocation & Loc)
Definition at line 148 of file SampleContextTracker.cpp.
setFunctionSamples()
void llvm::ContextTrieNode::setFunctionSamples (FunctionSamples * FSamples)
Definition at line 123 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::SampleContextTracker().
setParentContext()
void llvm::ContextTrieNode::setParentContext (ContextTrieNode * Parent)
Definition at line 144 of file SampleContextTracker.cpp.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SampleContextTracker.h
lib/Transforms/IPO/SampleContextTracker.cpp