LLVM: llvm::ConstraintSystem Class Reference
llvm::ConstraintSystem Class Reference
#include "llvm/Analysis/ConstraintSystem.h"
Public Member Functions
ConstraintSystem ()
ConstraintSystem (const DenseMap< Value *, unsigned > &Value2Index)
bool addVariableRow (ArrayRef< int64_t > R)
DenseMap< Value *, unsigned > & getValue2Index ()
const DenseMap< Value *, unsigned > & getValue2Index () const
bool addVariableRowFill (ArrayRef< int64_t > R)
bool mayHaveSolution ()
Returns true if there may be a solution for the constraints in the system.
bool isConditionImplied (SmallVector< int64_t, 8 > R) const
SmallVector< int64_t > getLastConstraint () const
void popLastConstraint ()
void popLastNVariables (unsigned N)
unsigned size () const
Returns the number of rows in the constraint system.
void dump () const
Print the constraints in the system.
Static Public Member Functions
static SmallVector< int64_t, 8 > negate (SmallVector< int64_t, 8 > R)
Detailed Description
Definition at line 23 of file ConstraintSystem.h.
Constructor & Destructor Documentation
ConstraintSystem() [1/2]
llvm::ConstraintSystem::ConstraintSystem () inline
Definition at line 70 of file ConstraintSystem.h.
ConstraintSystem() [2/2]
llvm::ConstraintSystem::ConstraintSystem (const DenseMap< Value *, unsigned > & Value2Index) inline
Definition at line 71 of file ConstraintSystem.h.
Member Function Documentation
addVariableRow()
bool llvm::ConstraintSystem::addVariableRow (ArrayRef< int64_t > R) inline
Definition at line 74 of file ConstraintSystem.h.
References llvm::abs(), llvm::all_of(), llvm::ArrayRef(), assert(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::enumerate(), llvm::APIntOps::GreatestCommonDivisor(), and move.
Referenced by addVariableRowFill().
addVariableRowFill()
bool llvm::ConstraintSystem::addVariableRowFill (ArrayRef< int64_t > R) inline
Definition at line 102 of file ConstraintSystem.h.
References addVariableRow(), llvm::all_of(), llvm::ArrayRef(), and llvm::max().
Referenced by dumpConstraint().
dump()
void ConstraintSystem::dump () const
Print the constraints in the system.
Definition at line 165 of file ConstraintSystem.cpp.
References llvm::dbgs(), I, LLVM_DEBUG, S, and llvm::to_string().
Referenced by dumpConstraint(), and mayHaveSolution().
getLastConstraint()
SmallVector<int64_t> llvm::ConstraintSystem::getLastConstraint () const inline
Definition at line 126 of file ConstraintSystem.h.
References assert().
getValue2Index() [1/2]
DenseMap<Value *, unsigned>& llvm::ConstraintSystem::getValue2Index () inline
Definition at line 97 of file ConstraintSystem.h.
getValue2Index() [2/2]
const DenseMap<Value *, unsigned>& llvm::ConstraintSystem::getValue2Index () const inline
Definition at line 98 of file ConstraintSystem.h.
isConditionImplied()
bool ConstraintSystem::isConditionImplied (SmallVector< int64_t, 8 > R) const
Definition at line 200 of file ConstraintSystem.cpp.
References llvm::all_of(), llvm::ArrayRef(), and negate().
mayHaveSolution()
bool ConstraintSystem::mayHaveSolution ()
Returns true if there may be a solution for the constraints in the system.
Definition at line 192 of file ConstraintSystem.cpp.
References llvm::dbgs(), dump(), and LLVM_DEBUG.
negate()
static SmallVector<int64_t, 8> llvm::ConstraintSystem::negate (SmallVector< int64_t, 8 > R) inline static
Definition at line 115 of file ConstraintSystem.h.
Referenced by checkAndReplaceCondition(), and isConditionImplied().
popLastConstraint()
void llvm::ConstraintSystem::popLastConstraint () inline
Definition at line 134 of file ConstraintSystem.h.
popLastNVariables()
void llvm::ConstraintSystem::popLastNVariables (unsigned N) inline
Definition at line 135 of file ConstraintSystem.h.
References assert(), and N.
size()
unsigned llvm::ConstraintSystem::size () const inline
Returns the number of rows in the constraint system.
Definition at line 141 of file ConstraintSystem.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/ConstraintSystem.h
lib/Analysis/ConstraintSystem.cpp