LLVM: llvm::codeview::TypeCollection Class Reference
llvm::codeview::TypeCollection Class Reference abstract
#include "llvm/DebugInfo/CodeView/TypeCollection.h"
Public Member Functions
virtual ~TypeCollection ()=default
bool empty ()
virtual std::optional< TypeIndex > getFirst ()=0
virtual std::optional< TypeIndex > getNext (TypeIndex Prev)=0
virtual CVType getType (TypeIndex Index)=0
virtual StringRef getTypeName (TypeIndex Index)=0
virtual bool contains (TypeIndex Index)=0
virtual uint32_t size ()=0
virtual uint32_t capacity ()=0
virtual bool replaceType (TypeIndex &Index, CVType Data, bool Stabilize)=0
template<typename TFunc >
void ForEachRecord (TFunc Func)
Detailed Description
Definition at line 18 of file TypeCollection.h.
Constructor & Destructor Documentation
~TypeCollection()
virtual llvm::codeview::TypeCollection::~TypeCollection () virtual default
Member Function Documentation
capacity()
virtual uint32_t llvm::codeview::TypeCollection::capacity () pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
contains()
virtual bool llvm::codeview::TypeCollection::contains (TypeIndex Index) pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
empty()
bool llvm::codeview::TypeCollection::empty () inline
Definition at line 22 of file TypeCollection.h.
References size().
Referenced by llvm::codeview::TypeTableCollection::getFirst(), llvm::codeview::AppendingTypeTableBuilder::getFirst(), llvm::codeview::MergingTypeTableBuilder::getFirst(), and llvm::codeview::GlobalTypeTableBuilder::getFirst().
ForEachRecord()
template<typename TFunc > void llvm::codeview::TypeCollection::ForEachRecord (TFunc Func) inline
Definition at line 34 of file TypeCollection.h.
References getFirst(), getNext(), getType(), and N.
getFirst()
virtual std::optional<TypeIndex> llvm::codeview::TypeCollection::getFirst () pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by ForEachRecord().
getNext()
virtual std::optional<TypeIndex> llvm::codeview::TypeCollection::getNext (TypeIndex Prev) pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by ForEachRecord().
getType()
virtual CVType llvm::codeview::TypeCollection::getType (TypeIndex Index) pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by ForEachRecord().
getTypeName()
virtual StringRef llvm::codeview::TypeCollection::getTypeName (TypeIndex Index) pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
replaceType()
virtual bool llvm::codeview::TypeCollection::replaceType (TypeIndex & Index, CVType Data, bool Stabilize) pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
size()
virtual uint32_t llvm::codeview::TypeCollection::size () pure virtual
Implemented in llvm::codeview::LazyRandomTypeCollection, llvm::codeview::GlobalTypeTableBuilder, llvm::codeview::MergingTypeTableBuilder, llvm::codeview::AppendingTypeTableBuilder, and llvm::codeview::TypeTableCollection.
Referenced by empty(), and llvm::codeview::TypeDumpVisitor::visitTypeBegin().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeCollection.h