LLVM: llvm::DICompileUnit Class Reference
llvm::DICompileUnit Class Reference
Compile unit.
#include "llvm/IR/DebugInfoMetadata.h"
Public Types
enum DebugEmissionKind : unsigned {
NoDebug = 0, FullDebug, LineTablesOnly, DebugDirectivesOnly,
LastEmissionKind = DebugDirectivesOnly
}
enum DebugNameTableKind : unsigned { DebugNameTableKind::Default = 0, DebugNameTableKind::GNU = 1, DebugNameTableKind::None = 2, DebugNameTableKind::LastDebugNameTableKind = None }
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic, FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
DEFINE_MDNODE_GET_DISTINCT_TEMPORARY (DICompileUnit,(unsigned SourceLanguage, DIFile *File, StringRef Producer, bool IsOptimized, StringRef Flags, unsigned RuntimeVersion, StringRef SplitDebugFilename, DebugEmissionKind EmissionKind, DICompositeTypeArray EnumTypes, DIScopeArray RetainedTypes, DIGlobalVariableExpressionArray GlobalVariables, DIImportedEntityArray ImportedEntities, DIMacroNodeArray Macros, uint64_t DWOId, bool SplitDebugInlining, bool DebugInfoForProfiling, DebugNameTableKind NameTableKind, bool RangesBaseAddress, StringRef SysRoot, StringRef SDK),(SourceLanguage, File, Producer, IsOptimized, Flags, RuntimeVersion, SplitDebugFilename, EmissionKind, EnumTypes, RetainedTypes, GlobalVariables, ImportedEntities, Macros, DWOId, SplitDebugInlining, DebugInfoForProfiling,(unsigned) NameTableKind, RangesBaseAddress, SysRoot, SDK)) DEFINE_MDNODE_GET_DISTINCT_TEMPORARY(DICompileUnit
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SDK TempDICompileUnit clone () const
unsigned getSourceLanguage () const
bool isOptimized () const
unsigned getRuntimeVersion () const
DebugEmissionKind getEmissionKind () const
bool isDebugDirectivesOnly () const
bool getDebugInfoForProfiling () const
DebugNameTableKind getNameTableKind () const
bool getRangesBaseAddress () const
StringRef getProducer () const
StringRef getFlags () const
StringRef getSplitDebugFilename () const
DICompositeTypeArray getEnumTypes () const
DIScopeArray getRetainedTypes () const
DIGlobalVariableExpressionArray getGlobalVariables () const
DIImportedEntityArray getImportedEntities () const
DIMacroNodeArray getMacros () const
uint64_t getDWOId () const
void setDWOId (uint64_t DwoId)
bool getSplitDebugInlining () const
void setSplitDebugInlining (bool SplitDebugInlining)
StringRef getSysRoot () const
StringRef getSDK () const
MDString * getRawProducer () const
MDString * getRawFlags () const
MDString * getRawSplitDebugFilename () const
Metadata * getRawEnumTypes () const
Metadata * getRawRetainedTypes () const
Metadata * getRawGlobalVariables () const
Metadata * getRawImportedEntities () const
Metadata * getRawMacros () const
MDString * getRawSysRoot () const
MDString * getRawSDK () const
void replaceEnumTypes (DICompositeTypeArray N)
Replace arrays.
void replaceRetainedTypes (DITypeArray N)
void replaceGlobalVariables (DIGlobalVariableExpressionArray N)
void replaceImportedEntities (DIImportedEntityArray N)
void replaceMacros (DIMacroNodeArray N)
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
StringRef getName () const
DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static std::optional< DebugEmissionKind > getEmissionKind (StringRef Str)
static const char * emissionKindString (DebugEmissionKind EK)
static std::optional< DebugNameTableKind > getNameTableKind (StringRef Str)
static const char * nameTableKindString (DebugNameTableKind PK)
static void get ()=delete
static void getIfExists ()=delete
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
unsigned Metadata * File
unsigned Metadata MDString * Producer
unsigned Metadata MDString bool IsOptimized
unsigned Metadata MDString bool MDString * Flags
unsigned Metadata MDString bool MDString unsigned RuntimeVersion
unsigned Metadata MDString bool MDString unsigned MDString * SplitDebugFilename
unsigned Metadata MDString bool MDString unsigned MDString unsigned EmissionKind
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata * EnumTypes
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata * RetainedTypes
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata * GlobalVariables
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata * ImportedEntities
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata * Macros
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t DWOId
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool SplitDebugInlining
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool DebugInfoForProfiling
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned NameTableKind
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool RangesBaseAddress
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString * SysRoot
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString * SDK
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SourceLanguage
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString File
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString Producer
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString IsOptimized
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString Flags
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString RuntimeVersion
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SplitDebugFilename
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString EmissionKind
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString EnumTypes
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString RetainedTypes
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString GlobalVariables
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString ImportedEntities
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString Macros
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString DWOId
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SplitDebugInlining
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString DebugInfoForProfiling
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString NameTableKind
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString RangesBaseAddress
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SysRoot
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Compile unit.
Definition at line 1363 of file DebugInfoMetadata.h.
Member Enumeration Documentation
DebugEmissionKind
enum llvm::DICompileUnit::DebugEmissionKind : unsigned
Enumerator
NoDebug
FullDebug
LineTablesOnly
DebugDirectivesOnly
LastEmissionKind
Definition at line 1368 of file DebugInfoMetadata.h.
DebugNameTableKind
enum llvm::DICompileUnit::DebugNameTableKind : unsigned strong
Enumerator
Default
GNU
None
LastDebugNameTableKind
Definition at line 1376 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DICompileUnit::classof (const Metadata * MD) inline static
Definition at line 1558 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString SDK TempDICompileUnit llvm::DICompileUnit::clone () const inline
Definition at line 1483 of file DebugInfoMetadata.h.
DEFINE_MDNODE_GET_DISTINCT_TEMPORARY()
llvm::DICompileUnit::DEFINE_MDNODE_GET_DISTINCT_TEMPORARY (DICompileUnit , (unsigned SourceLanguage, DIFile *File, StringRef Producer, bool IsOptimized, StringRef Flags, unsigned RuntimeVersion, StringRef SplitDebugFilename, DebugEmissionKind EmissionKind, DICompositeTypeArray EnumTypes, DIScopeArray RetainedTypes, DIGlobalVariableExpressionArray GlobalVariables, DIImportedEntityArray ImportedEntities, DIMacroNodeArray Macros, uint64_t DWOId, bool SplitDebugInlining, bool DebugInfoForProfiling, DebugNameTableKind NameTableKind, bool RangesBaseAddress, StringRef SysRoot, StringRef SDK) , (SourceLanguage, File, Producer, IsOptimized, Flags, RuntimeVersion, SplitDebugFilename, EmissionKind, EnumTypes, RetainedTypes, GlobalVariables, ImportedEntities, Macros, DWOId, SplitDebugInlining, DebugInfoForProfiling,(unsigned) NameTableKind, RangesBaseAddress, SysRoot, SDK))
emissionKindString()
const char * DICompileUnit::emissionKindString (DebugEmissionKind EK) static
Definition at line 915 of file DebugInfoMetadata.cpp.
References DebugDirectivesOnly, FullDebug, LineTablesOnly, and NoDebug.
get()
static void llvm::DICompileUnit::get () static delete
getDebugInfoForProfiling()
bool llvm::DICompileUnit::getDebugInfoForProfiling () const inline
Definition at line 1494 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::applySubprogramAttributes(), and llvm::DwarfDebug::endFunctionImpl().
getDWOId()
uint64_t llvm::DICompileUnit::getDWOId () const inline
Definition at line 1517 of file DebugInfoMetadata.h.
getEmissionKind() [1/2]
DebugEmissionKind llvm::DICompileUnit::getEmissionKind () const inline
Definition at line 1488 of file DebugInfoMetadata.h.
Referenced by llvm::LLParser::parseMDField().
getEmissionKind() [2/2]
std::optional< DICompileUnit::DebugEmissionKind > DICompileUnit::getEmissionKind (StringRef Str) static
Definition at line 897 of file DebugInfoMetadata.cpp.
References llvm::StringSwitch< T, R >::Case(), DebugDirectivesOnly, llvm::StringSwitch< T, R >::Default(), FullDebug, LineTablesOnly, and NoDebug.
Referenced by llvm::DwarfDebug::endFunctionImpl(), and llvm::DwarfCompileUnit::includeMinimalInlineScopes().
getEnumTypes()
DICompositeTypeArray llvm::DICompileUnit::getEnumTypes () const inline
Definition at line 1502 of file DebugInfoMetadata.h.
References getRawEnumTypes().
Referenced by llvm::DIBuilder::DIBuilder().
getFlags()
StringRef llvm::DICompileUnit::getFlags () const inline
Definition at line 1500 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getGlobalVariables()
DIGlobalVariableExpressionArray llvm::DICompileUnit::getGlobalVariables () const inline
Definition at line 1508 of file DebugInfoMetadata.h.
References getRawGlobalVariables().
Referenced by llvm::DIBuilder::DIBuilder().
getIfExists()
static void llvm::DICompileUnit::getIfExists () static delete
getImportedEntities()
DIImportedEntityArray llvm::DICompileUnit::getImportedEntities () const inline
Definition at line 1511 of file DebugInfoMetadata.h.
References getRawImportedEntities().
Referenced by llvm::DIBuilder::DIBuilder().
getMacros()
DIMacroNodeArray llvm::DICompileUnit::getMacros () const inline
Definition at line 1514 of file DebugInfoMetadata.h.
References getRawMacros().
Referenced by llvm::DIBuilder::DIBuilder().
getNameTableKind() [1/2]
DebugNameTableKind llvm::DICompileUnit::getNameTableKind () const inline
Definition at line 1495 of file DebugInfoMetadata.h.
Referenced by llvm::LLParser::parseMDField().
getNameTableKind() [2/2]
std::optional< DICompileUnit::DebugNameTableKind > DICompileUnit::getNameTableKind (StringRef Str) static
Definition at line 907 of file DebugInfoMetadata.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), Default, GNU, and None.
Referenced by llvm::DwarfCompileUnit::hasDwarfPubSections().
getProducer()
StringRef llvm::DICompileUnit::getProducer () const inline
Definition at line 1499 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getRangesBaseAddress()
bool llvm::DICompileUnit::getRangesBaseAddress () const inline
Definition at line 1498 of file DebugInfoMetadata.h.
getRawEnumTypes()
Metadata* llvm::DICompileUnit::getRawEnumTypes () const inline
Definition at line 1531 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getEnumTypes().
getRawFlags()
MDString* llvm::DICompileUnit::getRawFlags () const inline
Definition at line 1527 of file DebugInfoMetadata.h.
getRawGlobalVariables()
Metadata* llvm::DICompileUnit::getRawGlobalVariables () const inline
Definition at line 1533 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getGlobalVariables().
getRawImportedEntities()
Metadata* llvm::DICompileUnit::getRawImportedEntities () const inline
Definition at line 1534 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getImportedEntities().
getRawMacros()
Metadata* llvm::DICompileUnit::getRawMacros () const inline
Definition at line 1535 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getMacros().
getRawProducer()
MDString* llvm::DICompileUnit::getRawProducer () const inline
Definition at line 1526 of file DebugInfoMetadata.h.
getRawRetainedTypes()
Metadata* llvm::DICompileUnit::getRawRetainedTypes () const inline
Definition at line 1532 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getRetainedTypes().
getRawSDK()
MDString* llvm::DICompileUnit::getRawSDK () const inline
Definition at line 1537 of file DebugInfoMetadata.h.
getRawSplitDebugFilename()
MDString* llvm::DICompileUnit::getRawSplitDebugFilename () const inline
Definition at line 1528 of file DebugInfoMetadata.h.
getRawSysRoot()
MDString* llvm::DICompileUnit::getRawSysRoot () const inline
Definition at line 1536 of file DebugInfoMetadata.h.
getRetainedTypes()
DIScopeArray llvm::DICompileUnit::getRetainedTypes () const inline
Definition at line 1505 of file DebugInfoMetadata.h.
References getRawRetainedTypes().
Referenced by llvm::DIBuilder::DIBuilder().
getRuntimeVersion()
unsigned llvm::DICompileUnit::getRuntimeVersion () const inline
Definition at line 1487 of file DebugInfoMetadata.h.
getSDK()
StringRef llvm::DICompileUnit::getSDK () const inline
Definition at line 1524 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getSourceLanguage()
unsigned llvm::DICompileUnit::getSourceLanguage () const inline
Definition at line 1485 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfUnit::getLanguage().
getSplitDebugFilename()
StringRef llvm::DICompileUnit::getSplitDebugFilename () const inline
Definition at line 1501 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
getSplitDebugInlining()
bool llvm::DICompileUnit::getSplitDebugInlining () const inline
Definition at line 1519 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfDebug::endFunctionImpl().
getSysRoot()
StringRef llvm::DICompileUnit::getSysRoot () const inline
Definition at line 1523 of file DebugInfoMetadata.h.
References llvm::DINode::getStringOperand().
isDebugDirectivesOnly()
bool llvm::DICompileUnit::isDebugDirectivesOnly () const inline
Definition at line 1491 of file DebugInfoMetadata.h.
References DebugDirectivesOnly.
Referenced by llvm::DwarfUnit::addString(), llvm::DwarfFile::emitUnit(), llvm::DwarfDebug::endFunctionImpl(), llvm::DwarfCompileUnit::hasDwarfPubSections(), and llvm::DwarfCompileUnit::initStmtList().
isOptimized()
bool llvm::DICompileUnit::isOptimized () const inline
Definition at line 1486 of file DebugInfoMetadata.h.
nameTableKindString()
const char * DICompileUnit::nameTableKindString (DebugNameTableKind PK) static
Definition at line 929 of file DebugInfoMetadata.cpp.
References Default, GNU, and None.
replaceEnumTypes()
void llvm::DICompileUnit::replaceEnumTypes (DICompositeTypeArray N) inline
Replace arrays.
If this isUniqued() and not isResolved(), it will be RAUW'ed and deleted on a uniquing collision. In practice, uniquing collisions on DICompileUnit should be fairly rare.
Definition at line 1545 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
Referenced by llvm::DIBuilder::finalize().
replaceGlobalVariables()
void llvm::DICompileUnit::replaceGlobalVariables (DIGlobalVariableExpressionArray N) inline
Definition at line 1549 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
Referenced by llvm::DIBuilder::finalize().
replaceImportedEntities()
void llvm::DICompileUnit::replaceImportedEntities (DIImportedEntityArray N) inline
Definition at line 1552 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
Referenced by llvm::DIBuilder::finalize().
replaceMacros()
void llvm::DICompileUnit::replaceMacros (DIMacroNodeArray N) inline
Definition at line 1555 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
Referenced by llvm::DIBuilder::finalize().
replaceRetainedTypes()
void llvm::DICompileUnit::replaceRetainedTypes (DITypeArray N) inline
Definition at line 1548 of file DebugInfoMetadata.h.
References N, and llvm::MDNode::replaceOperandWith().
Referenced by llvm::DIBuilder::finalize().
setDWOId()
void llvm::DICompileUnit::setDWOId (uint64_t DwoId) inline
Definition at line 1518 of file DebugInfoMetadata.h.
setSplitDebugInlining()
void llvm::DICompileUnit::setSplitDebugInlining (bool SplitDebugInlining) inline
Definition at line 1520 of file DebugInfoMetadata.h.
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 1364 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 1365 of file DebugInfoMetadata.h.
Member Data Documentation
DebugInfoForProfiling [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool llvm::DICompileUnit::DebugInfoForProfiling
Definition at line 1475 of file DebugInfoMetadata.h.
DebugInfoForProfiling [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::DebugInfoForProfiling
Definition at line 1481 of file DebugInfoMetadata.h.
DWOId [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t llvm::DICompileUnit::DWOId
Definition at line 1474 of file DebugInfoMetadata.h.
DWOId [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::DWOId
Definition at line 1480 of file DebugInfoMetadata.h.
EmissionKind [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned llvm::DICompileUnit::EmissionKind
Definition at line 1472 of file DebugInfoMetadata.h.
EmissionKind [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::EmissionKind
Definition at line 1479 of file DebugInfoMetadata.h.
EnumTypes [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata* llvm::DICompileUnit::EnumTypes
Definition at line 1472 of file DebugInfoMetadata.h.
EnumTypes [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::EnumTypes
Definition at line 1479 of file DebugInfoMetadata.h.
File [1/2]
unsigned Metadata* llvm::DICompileUnit::File
Definition at line 1470 of file DebugInfoMetadata.h.
File [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::File
Definition at line 1478 of file DebugInfoMetadata.h.
Flags [1/2]
unsigned Metadata MDString bool MDString* llvm::DICompileUnit::Flags
Definition at line 1471 of file DebugInfoMetadata.h.
Flags [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::Flags
Definition at line 1478 of file DebugInfoMetadata.h.
GlobalVariables [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata* llvm::DICompileUnit::GlobalVariables
Definition at line 1473 of file DebugInfoMetadata.h.
GlobalVariables [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::GlobalVariables
Definition at line 1480 of file DebugInfoMetadata.h.
ImportedEntities [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata* llvm::DICompileUnit::ImportedEntities
Definition at line 1474 of file DebugInfoMetadata.h.
ImportedEntities [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::ImportedEntities
Definition at line 1480 of file DebugInfoMetadata.h.
IsOptimized [1/2]
unsigned Metadata MDString bool llvm::DICompileUnit::IsOptimized
Definition at line 1471 of file DebugInfoMetadata.h.
IsOptimized [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::IsOptimized
Definition at line 1478 of file DebugInfoMetadata.h.
Macros [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata* llvm::DICompileUnit::Macros
Definition at line 1474 of file DebugInfoMetadata.h.
Macros [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::Macros
Definition at line 1480 of file DebugInfoMetadata.h.
NameTableKind [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned llvm::DICompileUnit::NameTableKind
Definition at line 1476 of file DebugInfoMetadata.h.
NameTableKind [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::NameTableKind
Definition at line 1481 of file DebugInfoMetadata.h.
Producer [1/2]
unsigned Metadata MDString* llvm::DICompileUnit::Producer
Definition at line 1470 of file DebugInfoMetadata.h.
Producer [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::Producer
Definition at line 1478 of file DebugInfoMetadata.h.
RangesBaseAddress [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool llvm::DICompileUnit::RangesBaseAddress
Definition at line 1476 of file DebugInfoMetadata.h.
RangesBaseAddress [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::RangesBaseAddress
Definition at line 1481 of file DebugInfoMetadata.h.
RetainedTypes [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata* llvm::DICompileUnit::RetainedTypes
Definition at line 1473 of file DebugInfoMetadata.h.
RetainedTypes [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::RetainedTypes
Definition at line 1479 of file DebugInfoMetadata.h.
RuntimeVersion [1/2]
unsigned Metadata MDString bool MDString unsigned llvm::DICompileUnit::RuntimeVersion
Definition at line 1471 of file DebugInfoMetadata.h.
RuntimeVersion [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::RuntimeVersion
Definition at line 1478 of file DebugInfoMetadata.h.
SDK
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString* llvm::DICompileUnit::SDK
Definition at line 1477 of file DebugInfoMetadata.h.
SourceLanguage
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::SourceLanguage
Definition at line 1478 of file DebugInfoMetadata.h.
SplitDebugFilename [1/2]
unsigned Metadata MDString bool MDString unsigned MDString* llvm::DICompileUnit::SplitDebugFilename
Definition at line 1472 of file DebugInfoMetadata.h.
SplitDebugFilename [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::SplitDebugFilename
Definition at line 1479 of file DebugInfoMetadata.h.
SplitDebugInlining [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool llvm::DICompileUnit::SplitDebugInlining
Definition at line 1475 of file DebugInfoMetadata.h.
SplitDebugInlining [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::SplitDebugInlining
Definition at line 1480 of file DebugInfoMetadata.h.
SysRoot [1/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString* llvm::DICompileUnit::SysRoot
Definition at line 1476 of file DebugInfoMetadata.h.
SysRoot [2/2]
unsigned Metadata MDString bool MDString unsigned MDString unsigned Metadata Metadata Metadata Metadata Metadata uint64_t bool bool unsigned bool MDString MDString llvm::DICompileUnit::SysRoot
Definition at line 1481 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp