LLVM: llvm::FaultMapParser Class Reference
llvm::FaultMapParser Class Reference
A parser for the __llvm_faultmaps section generated by the FaultMaps class declared in llvm/CodeGen/FaultMaps.h.
#include "llvm/Object/FaultMapParser.h"
Classes
class FunctionFaultInfoAccessor
class FunctionInfoAccessor
Public Types
enum FaultKind { FaultingLoad = 1, FaultingLoadStore, FaultingStore, FaultKindMax }
Public Member Functions
FaultMapParser (const uint8_t *Begin, const uint8_t *End)
FaultMapVersionType getFaultMapVersion () const
NumFunctionsType getNumFunctions () const
FunctionInfoAccessor getFirstFunctionInfo () const
Detailed Description
A parser for the __llvm_faultmaps section generated by the FaultMaps class declared in llvm/CodeGen/FaultMaps.h.
This parser is version locked with with the __llvm_faultmaps section generated by the version of LLVM that includes it. No guarantees are made with respect to forward or backward compatibility.
Definition at line 25 of file FaultMapParser.h.
Member Enumeration Documentation
FaultKind
enum llvm::FaultMapParser::FaultKind
Enumerator
FaultingLoad
FaultingLoadStore
FaultingStore
FaultKindMax
Definition at line 49 of file FaultMapParser.h.
Constructor & Destructor Documentation
FaultMapParser()
llvm::FaultMapParser::FaultMapParser (const uint8_t * Begin, const uint8_t * End) inline explicit
Definition at line 138 of file FaultMapParser.h.
Member Function Documentation
getFaultMapVersion()
FaultMapVersionType llvm::FaultMapParser::getFaultMapVersion () const inline
Definition at line 141 of file FaultMapParser.h.
References assert(), P, and llvm::IndexedInstrProf::Version.
Referenced by llvm::operator<<().
getFirstFunctionInfo()
FunctionInfoAccessor llvm::FaultMapParser::getFirstFunctionInfo () const inline
Definition at line 151 of file FaultMapParser.h.
References P.
Referenced by llvm::operator<<().
getNumFunctions()
NumFunctionsType llvm::FaultMapParser::getNumFunctions () const inline
Definition at line 147 of file FaultMapParser.h.
References P.
Referenced by llvm::operator<<().
The documentation for this class was generated from the following file:
include/llvm/Object/FaultMapParser.h