LLVM: llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator Class Reference
llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator Class Reference
#include "llvm/ADT/IntervalMap.h"
Public Types
using iterator_category = std::bidirectional_iterator_tag
using value_type = ValT
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
const_iterator ()=default
const_iterator - Create an iterator that isn't pointing anywhere.
void setMap (const IntervalMap &m)
setMap - Change the map iterated over.
bool valid () const
valid - Return true if the current position is valid, false for end().
bool atBegin () const
atBegin - Return true if the current position is the first map entry.
const KeyT & start () const
start - Return the beginning of the current interval.
const KeyT & stop () const
stop - Return the end of the current interval.
const ValT & value () const
value - Return the mapped value at the current interval.
const ValT & operator* () const
bool operator== (const const_iterator &RHS) const
bool operator!= (const const_iterator &RHS) const
void goToBegin ()
goToBegin - Move to the first interval in map.
void goToEnd ()
goToEnd - Move beyond the last interval in map.
const_iterator & operator++ ()
preincrement - Move to the next interval.
const_iterator operator++ (int)
postincrement - Don't do that!
const_iterator & operator-- ()
predecrement - Move to the previous interval.
const_iterator operator-- (int)
postdecrement - Don't do that!
void find (KeyT x)
find - Move to the first interval with stop >= x, or end().
void advanceTo (KeyT x)
advanceTo - Move to the first interval with stop >= x, or end().
Protected Member Functions
const_iterator (const IntervalMap &map)
bool branched () const
void setRoot (unsigned Offset)
void pathFillFind (KeyT x)
pathFillFind - Complete path by searching for x.
void treeFind (KeyT x)
treeFind - Find in a branched tree.
void treeAdvanceTo (KeyT x)
treeAdvanceTo - Find position after the current one.
KeyT & unsafeStart () const
unsafeStart - Writable access to start() for iterator.
KeyT & unsafeStop () const
unsafeStop - Writable access to stop() for iterator.
ValT & unsafeValue () const
unsafeValue - Writable access to value() for iterator.
Protected Attributes
IntervalMap * map = nullptr
IntervalMapImpl::Path path
Friends
class IntervalMap
Detailed Description
template<typename KeyT, typename ValT, unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>>
class llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator
Definition at line 1343 of file IntervalMap.h.
Member Typedef Documentation
difference_type
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::difference_type = std::ptrdiff_t
Definition at line 1349 of file IntervalMap.h.
iterator_category
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::iterator_category = std::bidirectional_iterator_tag
Definition at line 1347 of file IntervalMap.h.
pointer
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::pointer = value_type *
Definition at line 1350 of file IntervalMap.h.
reference
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::reference = value_type &
Definition at line 1351 of file IntervalMap.h.
value_type
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> using llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::value_type = ValT
Definition at line 1348 of file IntervalMap.h.
Constructor & Destructor Documentation
const_iterator() [1/2]
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::const_iterator (const IntervalMap & map) inline explicit protected
Definition at line 1361 of file IntervalMap.h.
const_iterator() [2/2]
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::const_iterator () default
const_iterator - Create an iterator that isn't pointing anywhere.
Member Function Documentation
advanceTo()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::advanceTo (KeyT x) inline
advanceTo - Move to the first interval with stop >= x, or end().
The search is started from the current position, and no earlier positions can be found. This is much faster than find() for small moves.
Definition at line 1494 of file IntervalMap.h.
References llvm::IntervalMapImpl::LeafNode< KeyT, ValT, N, Traits >::findFrom(), llvm::IntervalMapImpl::Path::leafOffset(), and x.
atBegin()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::atBegin () const inline
atBegin - Return true if the current position is the first map entry.
Definition at line 1413 of file IntervalMap.h.
References llvm::IntervalMapImpl::Path::atBegin().
branched()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::branched () const inline protected
Definition at line 1364 of file IntervalMap.h.
References assert().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert().
find()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::find (KeyT x) inline
find - Move to the first interval with stop >= x, or end().
This is a full search from the root, the current position is ignored.
Definition at line 1484 of file IntervalMap.h.
References llvm::IntervalMapImpl::LeafNode< KeyT, ValT, N, Traits >::findFrom(), and x.
goToBegin()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::goToBegin () inline
goToBegin - Move to the first interval in map.
Definition at line 1440 of file IntervalMap.h.
References llvm::IntervalMapImpl::Path::fillLeft().
goToEnd()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::goToEnd () inline
goToEnd - Move beyond the last interval in map.
Definition at line 1447 of file IntervalMap.h.
operator!=()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator!= (const const_iterator & RHS) const inline
Definition at line 1435 of file IntervalMap.h.
References llvm::operator==(), and RHS.
operator*()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const ValT& llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator* () const inline
Definition at line 1424 of file IntervalMap.h.
operator++() [1/2]
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const_iterator& llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++ () inline
preincrement - Move to the next interval.
Definition at line 1452 of file IntervalMap.h.
References assert(), llvm::IntervalMapImpl::Path::leafOffset(), llvm::IntervalMapImpl::Path::leafSize(), and llvm::IntervalMapImpl::Path::moveRight().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::operator++().
operator++() [2/2]
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const_iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++ (int) inline
postincrement - Don't do that!
Definition at line 1460 of file IntervalMap.h.
operator--() [1/2]
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const_iterator& llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator-- () inline
predecrement - Move to the previous interval.
Definition at line 1467 of file IntervalMap.h.
References llvm::IntervalMapImpl::Path::leafOffset(), and llvm::IntervalMapImpl::Path::moveLeft().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::operator--().
operator--() [2/2]
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const_iterator llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator-- (int) inline
postdecrement - Don't do that!
Definition at line 1476 of file IntervalMap.h.
References llvm::ARM::operator--().
operator==()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator== (const const_iterator & RHS) const inline
Definition at line 1426 of file IntervalMap.h.
References assert(), llvm::IntervalMapImpl::Path::leafOffset(), and RHS.
pathFillFind()
template<typename KeyT , typename ValT , unsigned N, typename Traits > void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::pathFillFind (KeyT x) protected
pathFillFind - Complete path by searching for x.
Parameters
x Key to search for.
Definition at line 1509 of file IntervalMap.h.
References llvm::IntervalMapImpl::NodeRef::get(), i, p, llvm::IntervalMapImpl::LeafNode< KeyT, ValT, N, Traits >::safeFind(), llvm::IntervalMapImpl::NodeRef::subtree(), and x.
setMap()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::setMap (const IntervalMap & m) inline
setMap - Change the map iterated over.
This call must be followed by a call to goToBegin(), goToEnd(), or find()
Definition at line 1407 of file IntervalMap.h.
setRoot()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::setRoot (unsigned Offset) inline protected
Definition at line 1369 of file IntervalMap.h.
References llvm::Offset, and llvm::IntervalMapImpl::Path::setRoot().
start()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const KeyT& llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::start () const inline
start - Return the beginning of the current interval.
Definition at line 1416 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStop(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
stop()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const KeyT& llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::stop () const inline
stop - Return the end of the current interval.
Definition at line 1419 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStop(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
treeAdvanceTo()
template<typename KeyT , typename ValT , unsigned N, typename Traits > void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::treeAdvanceTo (KeyT x) protected
treeAdvanceTo - Find position after the current one.
Parameters
x Key to search for.
Definition at line 1533 of file IntervalMap.h.
References l, llvm::IntervalMapImpl::LeafNode< KeyT, ValT, N, Traits >::stop(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, N, Traits >::stop(), and x.
treeFind()
template<typename KeyT , typename ValT , unsigned N, typename Traits > void llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::treeFind (KeyT x) protected
treeFind - Find in a branched tree.
Parameters
x Key to search for.
Definition at line 1523 of file IntervalMap.h.
References x.
unsafeStart()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> KeyT& llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStart () const inline protected
unsafeStart - Writable access to start() for iterator.
Definition at line 1381 of file IntervalMap.h.
References assert(), llvm::IntervalMapImpl::Path::leaf(), llvm::IntervalMapImpl::Path::leafOffset(), llvm::IntervalMapImpl::LeafNode< KeyT, ValT, N, Traits >::start(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::start().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStart().
unsafeStop()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> KeyT& llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStop () const inline protected
unsafeStop - Writable access to stop() for iterator.
Definition at line 1388 of file IntervalMap.h.
References assert(), llvm::IntervalMapImpl::Path::leaf(), llvm::IntervalMapImpl::Path::leafOffset(), llvm::IntervalMapImpl::LeafNode< KeyT, ValT, N, Traits >::stop(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::stop().
unsafeValue()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> ValT& llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeValue () const inline protected
unsafeValue - Writable access to value() for iterator.
Definition at line 1395 of file IntervalMap.h.
References assert(), llvm::IntervalMapImpl::Path::leaf(), llvm::IntervalMapImpl::Path::leafOffset(), and llvm::IntervalMapImpl::LeafNode< KeyT, ValT, N, Traits >::value().
valid()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> bool llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::valid () const inline
valid - Return true if the current position is valid, false for end().
Definition at line 1410 of file IntervalMap.h.
References llvm::IntervalMapImpl::Path::valid().
Referenced by llvm::IntervalMapOverlaps< MapA, MapB >::advanceTo().
value()
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> const ValT& llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::value () const inline
value - Return the mapped value at the current interval.
Definition at line 1422 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStart(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStop().
Friends And Related Function Documentation
IntervalMap
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> friend class IntervalMap friend
Definition at line 1344 of file IntervalMap.h.
Member Data Documentation
map
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> IntervalMap* llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::map = nullptr protected
Definition at line 1355 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert().
path
template<typename KeyT , typename ValT , unsigned N = IntervalMapImpl::NodeSizer<KeyT, ValT>::LeafSize, typename Traits = IntervalMapInfo<KeyT>> IntervalMapImpl::Path llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::path protected
Definition at line 1359 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert().
The documentation for this class was generated from the following file:
include/llvm/ADT/IntervalMap.h