LLVM: llvm::ScheduleMetrics Class Reference
llvm::ScheduleMetrics Class Reference
#include "Target/AMDGPU/GCNSchedStrategy.h"
Public Member Functions
ScheduleMetrics ()
ScheduleMetrics (unsigned L, unsigned BC)
unsigned getLength () const
unsigned getBubbles () const
unsigned getMetric () const
Static Public Attributes
static const unsigned ScaleFactor = 100
Detailed Description
Definition at line 139 of file GCNSchedStrategy.h.
Constructor & Destructor Documentation
ScheduleMetrics() [1/2]
llvm::ScheduleMetrics::ScheduleMetrics () inline
Definition at line 144 of file GCNSchedStrategy.h.
ScheduleMetrics() [2/2]
llvm::ScheduleMetrics::ScheduleMetrics (unsigned L, unsigned BC) inline
Definition at line 145 of file GCNSchedStrategy.h.
Member Function Documentation
getBubbles()
unsigned llvm::ScheduleMetrics::getBubbles () const inline
Definition at line 148 of file GCNSchedStrategy.h.
Referenced by llvm::operator<<().
getLength()
unsigned llvm::ScheduleMetrics::getLength () const inline
Definition at line 147 of file GCNSchedStrategy.h.
Referenced by llvm::operator<<().
getMetric()
unsigned llvm::ScheduleMetrics::getMetric () const inline
Definition at line 149 of file GCNSchedStrategy.h.
References ScaleFactor.
Referenced by llvm::operator<<(), and llvm::UnclusteredHighRPStage::shouldRevertScheduling().
Member Data Documentation
ScaleFactor
const unsigned ScheduleMetrics::ScaleFactor = 100 static
Definition at line 155 of file GCNSchedStrategy.h.
Referenced by getMetric(), llvm::GCNSchedStage::getScheduleMetrics(), llvm::operator<<(), and llvm::UnclusteredHighRPStage::shouldRevertScheduling().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSchedStrategy.h
lib/Target/AMDGPU/GCNSchedStrategy.cpp