LLVM: LiveDebugValues::DbgOpIDMap Class Reference
LiveDebugValues::DbgOpIDMap Class Reference
Class storing the complete set of values that are observed by DbgValues within the current function.
#include "CodeGen/LiveDebugValues/InstrRefBasedImpl.h"
Public Member Functions
DbgOpID insert (DbgOp Op)
If Op does not already exist in this map, it is inserted and the corresponding DbgOpID is returned.
DbgOp find (DbgOpID ID) const
Returns the DbgOp associated with ID.
void clear ()
Detailed Description
Class storing the complete set of values that are observed by DbgValues within the current function.
Allows 2-way lookup, with find returning the Op for a given ID and insert returning the ID for a given Op (creating one if none exists).
Definition at line 371 of file InstrRefBasedImpl.h.
Member Function Documentation
clear()
void LiveDebugValues::DbgOpIDMap::clear () inline
Definition at line 401 of file InstrRefBasedImpl.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::clear(), and llvm::SmallVectorImpl< T >::clear().
find()
DbgOp LiveDebugValues::DbgOpIDMap::find (DbgOpID ID) const inline
Returns the DbgOp associated with ID.
Should only be used for IDs returned from calling insert from this map or DbgOpID::UndefID.
Definition at line 393 of file InstrRefBasedImpl.h.
References LiveDebugValues::DbgOpID::UndefID.
Referenced by LiveDebugValues::DbgOpID::dump(), TransferTracker::loadInlocs(), and TransferTracker::loadVarInloc().
insert()
DbgOpID LiveDebugValues::DbgOpIDMap::insert (DbgOp Op) inline
If Op does not already exist in this map, it is inserted and the corresponding DbgOpID is returned.
If Op already exists in this map, then no change is made and the existing ID for Op is returned. Calling this with the undef DbgOp will always return DbgOpID::UndefID.
Definition at line 384 of file InstrRefBasedImpl.h.
References LiveDebugValues::DbgOpID::UndefID.
The documentation for this class was generated from the following file:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.h