LLVM: llvm::DIELocList Class Reference
llvm::DIELocList Class Reference
Represents a pointer to a location list in the debug_loc section.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIELocList (size_t I)
size_t getValue () const
Grab the current index out.
void emitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit label value.
unsigned sizeOf (const dwarf::FormParams &FormParams, dwarf::Form Form) const
void print (raw_ostream &O) const
Detailed Description
Represents a pointer to a location list in the debug_loc section.
Definition at line 332 of file DIE.h.
Constructor & Destructor Documentation
DIELocList()
llvm::DIELocList::DIELocList (size_t I) inline
Definition at line 337 of file DIE.h.
Member Function Documentation
emitValue()
void DIELocList::emitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit label value.
Definition at line 838 of file DIE.cpp.
References llvm::AsmPrinter::emitDwarfSymbolReference(), llvm::AsmPrinter::emitULEB128(), llvm::DwarfDebug::getDebugLocs(), llvm::AsmPrinter::getDwarfDebug(), llvm::DebugLocStream::getList(), llvm::DebugLocStream::List::Label, and llvm::DwarfDebug::useSplitDwarf().
getValue()
size_t llvm::DIELocList::getValue () const inline
Grab the current index out.
Definition at line 340 of file DIE.h.
print()
LLVM_DUMP_METHOD void DIELocList::print (raw_ostream & O) const
Definition at line 849 of file DIE.cpp.
References llvm::RISCVFenceField::O.
sizeOf()
unsigned DIELocList::sizeOf (const dwarf::FormParams & FormParams, dwarf::Form Form) const
Definition at line 814 of file DIE.cpp.
References assert(), llvm::dwarf::DWARF64, llvm::dwarf::FormParams::Format, llvm::dwarf::FormParams::getDwarfOffsetByteSize(), llvm::getULEB128Size(), and llvm_unreachable.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp