LLVM: llvm::CSKYRegisterInfo Class Reference
llvm::CSKYRegisterInfo Class Reference
#include "Target/CSKY/CSKYRegisterInfo.h"
Public Member Functions
CSKYRegisterInfo ()
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID id) const override
const uint32_t * getNoPreservedMask () const override
BitVector getReservedRegs (const MachineFunction &MF) const override
Register getFrameRegister (const MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
bool eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool useFPForScavengingIndex (const MachineFunction &MF) const override
Detailed Description
Definition at line 24 of file CSKYRegisterInfo.h.
Constructor & Destructor Documentation
CSKYRegisterInfo()
CSKYRegisterInfo::CSKYRegisterInfo ()
Definition at line 26 of file CSKYRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
bool CSKYRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS) const override
Definition at line 182 of file CSKYRegisterInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Define, DL, llvm::MachineBasicBlock::erase(), llvm::ISD::FrameIndex, llvm::MachineInstrBuilder::getInstr(), llvm::getKillRegState(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::CSKYSubtarget::hasE2(), IsLegalOffset(), llvm::RegState::Kill, MBB, MI, MRI, llvm::Offset, llvm::report_fatal_error(), and TII.
getCalleeSavedRegs()
const MCPhysReg * CSKYRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 87 of file CSKYRegisterInfo.cpp.
References llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasFnAttribute(), llvm::CSKYSubtarget::hasFPUv2DoubleFloat(), llvm::CSKYSubtarget::hasFPUv2SingleFloat(), llvm::CSKYSubtarget::hasFPUv3DoubleFloat(), and llvm::CSKYSubtarget::hasFPUv3SingleFloat().
getCallPreservedMask()
const uint32_t * CSKYRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID id) const override
Definition at line 30 of file CSKYRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::CSKYSubtarget::hasFPUv2DoubleFloat(), llvm::CSKYSubtarget::hasFPUv2SingleFloat(), llvm::CSKYSubtarget::hasFPUv3DoubleFloat(), and llvm::CSKYSubtarget::hasFPUv3SingleFloat().
getFrameRegister()
Register CSKYRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 40 of file CSKYRegisterInfo.cpp.
References llvm::TargetFrameLowering::hasFP().
getNoPreservedMask()
const uint32_t * CSKYRegisterInfo::getNoPreservedMask () const override
Definition at line 82 of file CSKYRegisterInfo.cpp.
getReservedRegs()
BitVector CSKYRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 45 of file CSKYRegisterInfo.cpp.
References assert(), llvm::MachineFunction::getSubtarget(), llvm::CSKYFrameLowering::hasBP(), llvm::CSKYSubtarget::hasE2(), llvm::CSKYFrameLowering::hasFP(), llvm::CSKYSubtarget::hasHighRegisters(), i, and llvm::Reserved.
requiresFrameIndexScavenging()
bool llvm::CSKYRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline override
Definition at line 42 of file CSKYRegisterInfo.h.
requiresRegisterScavenging()
bool llvm::CSKYRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
Definition at line 46 of file CSKYRegisterInfo.h.
useFPForScavengingIndex()
bool llvm::CSKYRegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const inline override
Definition at line 50 of file CSKYRegisterInfo.h.
The documentation for this class was generated from the following files:
lib/Target/CSKY/CSKYRegisterInfo.h
lib/Target/CSKY/CSKYRegisterInfo.cpp