LLVM: llvm::BinOpInit Class Reference
llvm::BinOpInit Class Reference
!op (X, Y) - Combine two inits.
#include "llvm/TableGen/Record.h"
Public Types
enum BinaryOp : uint8_t {
ADD, SUB, MUL, DIV,
AND, OR, XOR, SHL,
SRA, SRL, LISTCONCAT, LISTSPLAT,
LISTREMOVE, STRCONCAT, INTERLEAVE, CONCAT,
EQ, NE, LE, LT,
GE, GT, SETDAGOP
}
Public Member Functions
BinOpInit (const BinOpInit &)=delete
BinOpInit & operator= (const BinOpInit &)=delete
void Profile (FoldingSetNodeID &ID) const
OpInit * clone (ArrayRef< Init * > Operands) const override
unsigned getNumOperands () const override
Init * getOperand (unsigned i) const override
BinaryOp getOpcode () const
Init * getLHS () const
Init * getRHS () const
std::optional< bool > CompareInit (unsigned Opc, Init *LHS, Init *RHS) const
Init * Fold (Record *CurRec) const
Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
std::string getAsString () const override
Convert this value to a literal form.
Public Member Functions inherited from llvm::OpInit
OpInit (const OpInit &)=delete
OpInit & operator= (OpInit &)=delete
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This function is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
Is this a complete value with no unset (uninitialized) subvalues?
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static BinOpInit * get (BinaryOp opc, Init *lhs, Init *rhs, RecTy *Type)
static Init * getStrConcat (Init *lhs, Init *rhs)
static Init * getListConcat (TypedInit *lhs, Init *rhs)
Static Public Member Functions inherited from llvm::OpInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First, IK_FirstTypedInit, IK_BitInit, IK_BitsInit,
IK_DagInit, IK_DefInit, IK_FieldInit, IK_IntInit,
IK_ListInit, IK_FirstOpInit, IK_BinOpInit, IK_TernOpInit,
IK_UnOpInit, IK_LastOpInit, IK_CondOpInit, IK_FoldOpInit,
IK_IsAOpInit, IK_ExistsOpInit, IK_AnonymousNameInit, IK_StringInit,
IK_VarInit, IK_VarListElementInit, IK_VarBitInit, IK_VarDefInit,
IK_LastTypedInit, IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::OpInit
OpInit (InitKind K, RecTy *Type, uint8_t Opc)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
!op (X, Y) - Combine two inits.
Definition at line 835 of file Record.h.
Member Enumeration Documentation
BinaryOp
enum llvm::BinOpInit::BinaryOp : uint8_t
Enumerator
ADD
SUB
MUL
DIV
AND
OR
XOR
SHL
SRA
SRL
LISTCONCAT
LISTSPLAT
LISTREMOVE
STRCONCAT
INTERLEAVE
CONCAT
EQ
NE
LE
LT
GE
GT
SETDAGOP
Definition at line 837 of file Record.h.
Constructor & Destructor Documentation
BinOpInit()
llvm::BinOpInit::BinOpInit (const BinOpInit &) delete
Member Function Documentation
classof()
static bool llvm::BinOpInit::classof (const Init * I) inline static
Definition at line 873 of file Record.h.
References I, and llvm::Init::IK_BinOpInit.
clone()
OpInit* llvm::BinOpInit::clone (ArrayRef< Init * > Operands) const inline override virtual
Implements llvm::OpInit.
Definition at line 885 of file Record.h.
References assert(), get(), getOpcode(), llvm::TypedInit::getType(), and Operands.
CompareInit()
std::optional< bool > BinOpInit::CompareInit (unsigned Opc, Init * LHS, Init * RHS) const
Definition at line 1040 of file Record.cpp.
References EQ, GE, llvm::IntRecTy::get(), llvm::TypedInit::getRecordKeeper(), llvm::IntInit::getValue(), llvm::StringInit::getValue(), GT, LE, LHS, llvm_unreachable, LT, NE, llvm::Init::Opc, and RHS.
Referenced by Fold().
Fold()
Init * BinOpInit::Fold (Record * CurRec) const
Definition at line 1116 of file Record.cpp.
References ADD, AND, llvm::append_range(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, CompareInit(), CONCAT, ConcatStringInits(), llvm::Init::convertInitializerTo(), llvm::tgtok::Dag, DIV, llvm::numbers::e, EQ, GE, llvm::IntRecTy::get(), llvm::UnsetInit::get(), llvm::BitInit::get(), llvm::IntInit::get(), llvm::ListInit::get(), llvm::DagInit::get(), llvm::DagInit::getArg(), llvm::DagInit::getArgName(), llvm::DagInit::getAsString(), llvm::DefInit::getDef(), llvm::ListInit::getElementType(), llvm::Record::getLoc(), llvm::DagInit::getNumArgs(), getOpcode(), llvm::DagInit::getOperator(), llvm::TypedInit::getRecordKeeper(), llvm::Value::getType(), llvm::IntInit::getValue(), GT, i, INT64_MIN, INTERLEAVE, interleaveIntList(), interleaveStringList(), LE, List, LISTCONCAT, LISTREMOVE, LISTSPLAT, llvm_unreachable, LT, MUL, NE, OR, llvm::PrintFatalError(), SETDAGOP, SHL, SRA, SRL, STRCONCAT, SUB, uint64_t, and XOR.
get()
BinOpInit * BinOpInit::get (BinaryOp opc, Init * lhs, Init * rhs, RecTy * Type) static
Definition at line 943 of file Record.cpp.
References llvm::detail::RecordKeeperImpl::Allocator, I, LHS, llvm::Init::Opc, ProfileBinOpInit(), RHS, and llvm::detail::RecordKeeperImpl::TheBinOpInitPool.
Referenced by clone(), getListConcat(), getStrConcat(), and resolveReferences().
getAsString()
std::string BinOpInit::getAsString () const override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 1294 of file Record.cpp.
References ADD, AND, CONCAT, DIV, EQ, GE, llvm::Init::getAsString(), getOpcode(), GT, INTERLEAVE, LE, LISTCONCAT, LISTREMOVE, LISTSPLAT, LT, MUL, NE, OR, SETDAGOP, SHL, SRA, SRL, STRCONCAT, SUB, and XOR.
getLHS()
Init* llvm::BinOpInit::getLHS () const inline
Definition at line 901 of file Record.h.
References LHS.
Referenced by getOperand(), and Profile().
getListConcat()
Init * BinOpInit::getListConcat (TypedInit * lhs, Init * rhs) static
Definition at line 1030 of file Record.cpp.
References assert(), ConcatListInits(), get(), llvm::Value::getType(), LHS, LISTCONCAT, and RHS.
getNumOperands()
unsigned llvm::BinOpInit::getNumOperands () const inline override virtual
Implements llvm::OpInit.
Definition at line 891 of file Record.h.
getOpcode()
BinaryOp llvm::BinOpInit::getOpcode () const inline
Definition at line 900 of file Record.h.
References llvm::Init::Opc.
Referenced by clone(), Fold(), getAsString(), Profile(), and resolveReferences().
getOperand()
Init* llvm::BinOpInit::getOperand (unsigned i) const inline override virtual
Implements llvm::OpInit.
Definition at line 892 of file Record.h.
References getLHS(), getRHS(), i, and llvm_unreachable.
getRHS()
Init* llvm::BinOpInit::getRHS () const inline
Definition at line 902 of file Record.h.
References RHS.
Referenced by getOperand(), and Profile().
getStrConcat()
Init * BinOpInit::getStrConcat (Init * lhs, Init * rhs) static
Definition at line 1013 of file Record.cpp.
References ConcatStringInits(), llvm::StringRecTy::get(), get(), llvm::Init::getRecordKeeper(), and STRCONCAT.
operator=()
BinOpInit& llvm::BinOpInit::operator= (const BinOpInit &) delete
Profile()
void BinOpInit::Profile (FoldingSetNodeID & ID) const
Definition at line 957 of file Record.cpp.
References getLHS(), getOpcode(), getRHS(), llvm::TypedInit::getType(), and ProfileBinOpInit().
resolveReferences()
Init * BinOpInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1284 of file Record.cpp.
References get(), getOpcode(), llvm::TypedInit::getType(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp