LLVM: llvm::objcopy::elf::IHexSectionWriterBase Class Reference
llvm::objcopy::elf::IHexSectionWriterBase Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
IHexSectionWriterBase (WritableMemoryBuffer &Buf)
uint64_t getBufferOffset () const
Error visit (const Section &Sec) final
Error visit (const OwnedDataSection &Sec) final
Error visit (const StringTableSection &Sec) override
Error visit (const DynamicRelocationSection &Sec) final
Error visit (const SymbolTableSection &Sec) override
Error visit (const RelocationSection &Sec) override
Error visit (const GnuDebugLinkSection &Sec) override
Error visit (const GroupSection &Sec) override
Error visit (const SectionIndexSection &Sec) override
Error visit (const CompressedSection &Sec) override
Error visit (const DecompressedSection &Sec) override
Public Member Functions inherited from llvm::objcopy::elf::BinarySectionWriter
virtual ~BinarySectionWriter ()
Error visit (const SymbolTableSection &Sec) override
Error visit (const RelocationSection &Sec) override
Error visit (const GnuDebugLinkSection &Sec) override
Error visit (const GroupSection &Sec) override
Error visit (const SectionIndexSection &Sec) override
Error visit (const CompressedSection &Sec) override
Error visit (const DecompressedSection &Sec) override
BinarySectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionWriter
virtual ~SectionWriter ()=default
SectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionVisitor
virtual ~SectionVisitor ()=default
Protected Member Functions
void writeSection (const SectionBase *Sec, ArrayRef< uint8_t > Data)
virtual void writeData (uint8_t Type, uint16_t Addr, ArrayRef< uint8_t > Data)
Protected Attributes
uint64_t Offset = 0
Protected Attributes inherited from llvm::objcopy::elf::SectionWriter
WritableMemoryBuffer & Out
Detailed Description
Definition at line 268 of file ELFObject.h.
Constructor & Destructor Documentation
IHexSectionWriterBase()
llvm::objcopy::elf::IHexSectionWriterBase::IHexSectionWriterBase (WritableMemoryBuffer & Buf) inline explicit
Definition at line 287 of file ELFObject.h.
Member Function Documentation
getBufferOffset()
uint64_t llvm::objcopy::elf::IHexSectionWriterBase::getBufferOffset () const inline
Definition at line 290 of file ELFObject.h.
References Offset.
visit() [1/11]
Error BinarySectionWriter::visit override
Definition at line 504 of file ELFObject.cpp.
visit() [2/11]
Error BinarySectionWriter::visit override
Definition at line 473 of file ELFObject.cpp.
visit() [3/11]
Error IHexSectionWriterBase::visit (const DynamicRelocationSection & Sec) final virtual
Reimplemented from llvm::objcopy::elf::SectionWriter.
Definition at line 404 of file ELFObject.cpp.
References llvm::Error::success().
visit() [4/11]
Error BinarySectionWriter::visit override
Definition at line 160 of file ELFObject.cpp.
visit() [5/11]
Error BinarySectionWriter::visit override
Definition at line 165 of file ELFObject.cpp.
visit() [6/11]
Error IHexSectionWriterBase::visit (const OwnedDataSection & Sec) final virtual
Reimplemented from llvm::objcopy::elf::SectionWriter.
Definition at line 389 of file ELFObject.cpp.
References llvm::Error::success().
visit() [7/11]
Error BinarySectionWriter::visit override
Definition at line 154 of file ELFObject.cpp.
visit() [8/11]
Error IHexSectionWriterBase::visit (const Section & Sec) final virtual
Reimplemented from llvm::objcopy::elf::SectionWriter.
Definition at line 384 of file ELFObject.cpp.
References llvm::Error::success().
visit() [9/11]
Error BinarySectionWriter::visit override
Definition at line 142 of file ELFObject.cpp.
visit() [10/11]
Error IHexSectionWriterBase::visit (const StringTableSection & Sec) override virtual
Reimplemented from llvm::objcopy::elf::SectionWriter.
Reimplemented in llvm::objcopy::elf::IHexSectionWriter.
Definition at line 394 of file ELFObject.cpp.
References assert(), llvm::StringTableBuilder::getSize(), llvm::objcopy::elf::SectionBase::Size, and llvm::Error::success().
visit() [11/11]
Error BinarySectionWriter::visit override
Definition at line 148 of file ELFObject.cpp.
writeData()
void IHexSectionWriterBase::writeData (uint8_t Type, uint16_t Addr, ArrayRef< uint8_t > Data) protected virtual
Reimplemented in llvm::objcopy::elf::IHexSectionWriter.
Definition at line 379 of file ELFObject.cpp.
References llvm::Data.
writeSection()
void IHexSectionWriterBase::writeSection (const SectionBase * Sec, ArrayRef< uint8_t > Data) protected
Definition at line 335 of file ELFObject.cpp.
References Addr, assert(), llvm::Data, llvm::min(), sectionPhysicalAddr(), llvm::objcopy::elf::SectionBase::Size, uint64_t, and writeData().
Member Data Documentation
Offset
uint64_t llvm::objcopy::elf::IHexSectionWriterBase::Offset = 0 protected
Definition at line 281 of file ELFObject.h.
Referenced by getBufferOffset().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp