LLVM: llvm::FileCollector::PathCanonicalizer Class Reference
llvm::FileCollector::PathCanonicalizer Class Reference
Helper utility that encapsulates the logic for canonicalizing a virtual path and a path to copy from.
#include "llvm/Support/FileCollector.h"
Classes
struct PathStorage
Public Member Functions
PathStorage canonicalize (StringRef SrcPath)
Canonicalize a pair of virtual and real paths.
Detailed Description
Helper utility that encapsulates the logic for canonicalizing a virtual path and a path to copy from.
Definition at line 73 of file FileCollector.h.
Member Function Documentation
canonicalize()
FileCollector::PathCanonicalizer::PathStorage FileCollector::PathCanonicalizer::canonicalize (StringRef SrcPath)
Canonicalize a pair of virtual and real paths.
Definition at line 105 of file FileCollector.cpp.
References llvm::FileCollector::PathCanonicalizer::PathStorage::CopyFrom, makeAbsolute(), llvm::sys::path::remove_dots(), and llvm::FileCollector::PathCanonicalizer::PathStorage::VirtualPath.
Referenced by llvm::FileCollector::addFileImpl().
The documentation for this class was generated from the following files:
include/llvm/Support/FileCollector.h
lib/Support/FileCollector.cpp