LLVM: llvm::InlineCost Class Reference
llvm::InlineCost Class Reference
Represents the cost of inlining a function.
#include "llvm/Analysis/InlineCost.h"
Public Member Functions
operator bool () const
Test whether the inline cost is low enough for inlining.
bool isAlways () const
bool isNever () const
bool isVariable () const
int getCost () const
Get the inline cost estimate.
int getThreshold () const
Get the threshold against which the cost was computed.
int getStaticBonusApplied () const
Get the amount of StaticBonus applied.
std::optional< CostBenefitPair > getCostBenefit () const
Get the cost-benefit pair which was computed by cost-benefit analysis.
const char * getReason () const
Get the reason of Always or Never.
int getCostDelta () const
Get the cost delta from the threshold for inlining.
Static Public Member Functions
static InlineCost get (int Cost, int Threshold, int StaticBonus=0)
static InlineCost getAlways (const char *Reason, std::optional< CostBenefitPair > CostBenefit=std::nullopt)
static InlineCost getNever (const char *Reason, std::optional< CostBenefitPair > CostBenefit=std::nullopt)
Detailed Description
Represents the cost of inlining a function.
This supports special values for functions which should "always" or "never" be inlined. Otherwise, the cost represents a unitless amount; smaller values increase the likelihood of the function being inlined.
Objects of this type also provide the adjusted threshold for inlining based on the information available for a particular callsite. They can be directly tested to determine if inlining should occur given the cost and threshold for this cost metric.
Definition at line 89 of file InlineCost.h.
Member Function Documentation
get()
static InlineCost llvm::InlineCost::get (int Cost, int Threshold, int StaticBonus = 0) inline static
Definition at line 119 of file InlineCost.h.
References assert(), and Cost.
Referenced by llvm::getInlineCost().
getAlways()
static InlineCost llvm::InlineCost::getAlways (const char * Reason, std::optional< CostBenefitPair > CostBenefit = std::nullopt) inline static
Definition at line 125 of file InlineCost.h.
References CostBenefit.
Referenced by llvm::ReplayInlineAdvisor::getAdviceImpl(), llvm::getInlineCost(), and llvm::AlwaysInlinerPass::run().
getCost()
int llvm::InlineCost::getCost () const inline
Get the inline cost estimate.
It is an error to call this on an "always" or "never" InlineCost.
Definition at line 144 of file InlineCost.h.
References assert(), Cost, and isVariable().
Referenced by getCostDelta(), llvm::operator<<(), shouldBeDeferred(), and llvm::shouldInline().
getCostBenefit()
std::optional<CostBenefitPair> llvm::InlineCost::getCostBenefit () const inline
Get the cost-benefit pair which was computed by cost-benefit analysis.
Definition at line 162 of file InlineCost.h.
References CostBenefit.
getCostDelta()
int llvm::InlineCost::getCostDelta () const inline
Get the cost delta from the threshold for inlining.
Only valid if the cost is of the variable kind. Returns a negative value if the cost is too high to inline.
Definition at line 174 of file InlineCost.h.
References getCost().
Referenced by shouldBeDeferred().
getNever()
static InlineCost llvm::InlineCost::getNever (const char * Reason, std::optional< CostBenefitPair > CostBenefit = std::nullopt) inline static
Definition at line 130 of file InlineCost.h.
References CostBenefit.
Referenced by llvm::getInlineCost().
getReason()
const char* llvm::InlineCost::getReason () const inline
Get the reason of Always or Never.
Definition at line 165 of file InlineCost.h.
References assert(), and isVariable().
Referenced by llvm::operator<<().
getStaticBonusApplied()
int llvm::InlineCost::getStaticBonusApplied () const inline
Get the amount of StaticBonus applied.
Definition at line 156 of file InlineCost.h.
References assert(), and isVariable().
getThreshold()
int llvm::InlineCost::getThreshold () const inline
Get the threshold against which the cost was computed.
Definition at line 150 of file InlineCost.h.
References assert(), and isVariable().
Referenced by llvm::operator<<().
isAlways()
bool llvm::InlineCost::isAlways () const inline
Definition at line 138 of file InlineCost.h.
References Cost.
Referenced by llvm::emitInlinedIntoBasedOnCost(), isVariable(), llvm::operator<<(), shouldBeDeferred(), and llvm::shouldInline().
isNever()
bool llvm::InlineCost::isNever () const inline
Definition at line 139 of file InlineCost.h.
References Cost.
Referenced by isVariable(), llvm::operator<<(), and llvm::shouldInline().
isVariable()
bool llvm::InlineCost::isVariable () const inline
Definition at line 140 of file InlineCost.h.
References isAlways(), and isNever().
Referenced by getCost(), getReason(), getStaticBonusApplied(), and getThreshold().
operator bool()
llvm::InlineCost::operator bool () const inline explicit
Test whether the inline cost is low enough for inlining.
Definition at line 136 of file InlineCost.h.
References Cost.
The documentation for this class was generated from the following file:
include/llvm/Analysis/InlineCost.h