LLVM: llvm::MapVector< KeyT, ValueT, MapType, VectorType > Class Template Reference
llvm::MapVector< KeyT, ValueT, MapType, VectorType > Class Template Reference
This class implements a map that also provides access to all stored values in a deterministic order.
#include "llvm/ADT/MapVector.h"
Public Types
using key_type = KeyT
using value_type = typename VectorType::value_type
using size_type = typename VectorType::size_type
using iterator = typename VectorType::iterator
using const_iterator = typename VectorType::const_iterator
using reverse_iterator = typename VectorType::reverse_iterator
using const_reverse_iterator = typename VectorType::const_reverse_iterator
Public Member Functions
VectorType takeVector ()
Clear the MapVector and return the underlying vector.
size_type size () const
void reserve (size_type NumEntries)
Grow the MapVector so that it can contain at least NumEntries items before resizing again.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
bool empty () const
std::pair< KeyT, ValueT > & front ()
const std::pair< KeyT, ValueT > & front () const
std::pair< KeyT, ValueT > & back ()
const std::pair< KeyT, ValueT > & back () const
void clear ()
void swap (MapVector &RHS)
ValueT & operator[] (const KeyT &Key)
ValueT lookup (const KeyT &Key) const
std::pair< iterator, bool > insert (const std::pair< KeyT, ValueT > &KV)
std::pair< iterator, bool > insert (std::pair< KeyT, ValueT > &&KV)
size_type count (const KeyT &Key) const
iterator find (const KeyT &Key)
const_iterator find (const KeyT &Key) const
void pop_back ()
Remove the last element from the vector.
VectorType::iterator erase (typename VectorType::iterator Iterator)
Remove the element given by Iterator.
size_type erase (const KeyT &Key)
Remove all elements with the key value Key.
template<class Predicate >
void remove_if (Predicate Pred)
Remove the elements that match the predicate.
template<class Function >
void remove_if (Function Pred)
Detailed Description
template<typename KeyT, typename ValueT, typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>>
class llvm::MapVector< KeyT, ValueT, MapType, VectorType >
This class implements a map that also provides access to all stored values in a deterministic order.
The values are kept in a std::vector and the mapping is done with DenseMap from Keys to indexes in that vector.
Definition at line 37 of file MapVector.h.
Member Typedef Documentation
const_iterator
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> using llvm::MapVector< KeyT, ValueT, MapType, VectorType >::const_iterator = typename VectorType::const_iterator
Definition at line 51 of file MapVector.h.
const_reverse_iterator
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> using llvm::MapVector< KeyT, ValueT, MapType, VectorType >::const_reverse_iterator = typename VectorType::const_reverse_iterator
Definition at line 53 of file MapVector.h.
iterator
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> using llvm::MapVector< KeyT, ValueT, MapType, VectorType >::iterator = typename VectorType::iterator
Definition at line 50 of file MapVector.h.
key_type
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> using llvm::MapVector< KeyT, ValueT, MapType, VectorType >::key_type = KeyT
Definition at line 46 of file MapVector.h.
reverse_iterator
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> using llvm::MapVector< KeyT, ValueT, MapType, VectorType >::reverse_iterator = typename VectorType::reverse_iterator
Definition at line 52 of file MapVector.h.
size_type
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> using llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size_type = typename VectorType::size_type
Definition at line 48 of file MapVector.h.
value_type
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> using llvm::MapVector< KeyT, ValueT, MapType, VectorType >::value_type = typename VectorType::value_type
Definition at line 47 of file MapVector.h.
Member Function Documentation
back() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> std::pair<KeyT, ValueT>& llvm::MapVector< KeyT, ValueT, MapType, VectorType >::back () inline
Definition at line 86 of file MapVector.h.
back() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> const std::pair<KeyT, ValueT>& llvm::MapVector< KeyT, ValueT, MapType, VectorType >::back () const inline
Definition at line 87 of file MapVector.h.
begin() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::begin () inline
Definition at line 70 of file MapVector.h.
Referenced by llvm::DbgValueHistoryMap::begin(), llvm::DbgLabelInstrMap::begin(), findMostPopularDest(), llvm::MapVector< AssertingVH< Instruction >, AssertingVH< Value > >::insert(), and llvm::ScheduleDAGInstrs::insertBarrierChain().
begin() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> const_iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::begin () const inline
Definition at line 71 of file MapVector.h.
clear()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> void llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear () inline
Definition at line 89 of file MapVector.h.
Referenced by ARM64ProcessEpilogs(), ARMEmitUnwindInfo(), llvm::DbgValueHistoryMap::clear(), llvm::DbgLabelInstrMap::clear(), llvm::ScheduleDAGInstrs::Value2SUsMap::clear(), LiveDebugValues::VLocTracker::clear(), and llvm::StackMaps::reset().
count()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> size_type llvm::MapVector< KeyT, ValueT, MapType, VectorType >::count (const KeyT & Key) const inline
Definition at line 143 of file MapVector.h.
Referenced by llvm::SIMachineFunctionInfo::allocateWWMSpill(), llvm::checkDebugInfoMetadata(), llvm::collectDebugInfoMetadata(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::LoopVectorizationLegality::isInductionPhi(), and llvm::LoopVectorizationLegality::isReductionVariable().
empty()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> bool llvm::MapVector< KeyT, ValueT, MapType, VectorType >::empty () const inline
Definition at line 80 of file MapVector.h.
Referenced by llvm::InterleavedAccessInfo::analyzeInterleaving(), decomposeGEP(), llvm::DbgValueHistoryMap::empty(), llvm::DbgLabelInstrMap::empty(), getSalvageOpsForGEP(), llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes(), interpretNextInstr(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), and llvm::writeIndex().
end() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end () inline
Definition at line 72 of file MapVector.h.
Referenced by llvm::ScheduleDAGInstrs::addChainDependencies(), llvm::MCLineSection::addEndEntry(), ARM64ProcessEpilogs(), ARMEmitUnwindInfo(), checkFunctions(), checkInstructions(), checkVars(), llvm::DbgValueHistoryMap::end(), llvm::DbgLabelInstrMap::end(), llvm::MapVector< AssertingVH< Instruction >, AssertingVH< Value > >::erase(), llvm::SPIRVDuplicatesTrackerBase< const llvm::Type * >::find(), findMostPopularDest(), llvm::MapVector< AssertingVH< Instruction >, AssertingVH< Value > >::insert(), llvm::ScheduleDAGInstrs::insertBarrierChain(), llvm::insertDebugValuesForPHIs(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), and llvm::lto::thinBackend().
end() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> const_iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end () const inline
Definition at line 73 of file MapVector.h.
erase() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> size_type llvm::MapVector< KeyT, ValueT, MapType, VectorType >::erase (const KeyT & Key) inline
Remove all elements with the key value Key.
Returns the number of elements removed.
Definition at line 193 of file MapVector.h.
erase() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> VectorType::iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::erase (typename VectorType::iterator Iterator) inline
Remove the element given by Iterator.
Returns an iterator to the element following the one which was removed, which may be end().
Note
This is a deceivingly expensive operation (linear time). It's usually better to use remove_if() if possible.
Definition at line 174 of file MapVector.h.
Referenced by collectCallSiteParameters(), llvm::MapVector< AssertingVH< Instruction >, AssertingVH< Value > >::erase(), interpretValues(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), and llvm::VPlan::removeLiveOut().
find() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find (const KeyT & Key) inline
Definition at line 148 of file MapVector.h.
Referenced by llvm::ScheduleDAGInstrs::addChainDependencies(), llvm::MCLineSection::addEndEntry(), ARM64ProcessEpilogs(), ARMEmitUnwindInfo(), checkFunctions(), checkInstructions(), checkVars(), llvm::LoopVectorizationCostModel::collectElementTypesForWidening(), llvm::MapVector< AssertingVH< Instruction >, AssertingVH< Value > >::erase(), llvm::SPIRVDuplicatesTrackerBase< const llvm::Type * >::find(), llvm::LoopVectorizationLegality::getIntOrFpInductionDescriptor(), llvm::LoopVectorizationLegality::getPointerInductionDescriptor(), llvm::insertDebugValuesForPHIs(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::lto::thinBackend(), and llvm::VPRecipeBuilder::tryToCreateWidenRecipe().
find() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> const_iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find (const KeyT & Key) const inline
Definition at line 154 of file MapVector.h.
front() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> std::pair<KeyT, ValueT>& llvm::MapVector< KeyT, ValueT, MapType, VectorType >::front () inline
Definition at line 84 of file MapVector.h.
Referenced by GEPToVectorIndex().
front() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> const std::pair<KeyT, ValueT>& llvm::MapVector< KeyT, ValueT, MapType, VectorType >::front () const inline
Definition at line 85 of file MapVector.h.
insert() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> std::pair<iterator, bool> llvm::MapVector< KeyT, ValueT, MapType, VectorType >::insert (const std::pair< KeyT, ValueT > & KV) inline
Definition at line 118 of file MapVector.h.
Referenced by addAllTypesFromDWP(), addToFwdRegWorklist(), llvm::SCCPInstVisitor::addTrackedFunction(), llvm::SIMachineFunctionInfo::allocateWWMSpill(), llvm::checkDebugInfoMetadata(), collectCallSiteParameters(), llvm::collectDebugInfoMetadata(), llvm::GEPOperator::collectOffset(), LiveDebugValues::VLocTracker::considerOverlaps(), LiveDebugValues::VLocTracker::defVar(), llvm::insertDebugValuesForPHIs(), and runImpl().
insert() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> std::pair<iterator, bool> llvm::MapVector< KeyT, ValueT, MapType, VectorType >::insert (std::pair< KeyT, ValueT > && KV) inline
Definition at line 130 of file MapVector.h.
lookup()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> ValueT llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup (const KeyT & Key) const inline
Definition at line 111 of file MapVector.h.
Referenced by ARM64ProcessEpilogs(), and ARMEmitUnwindInfo().
operator[]()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> ValueT& llvm::MapVector< KeyT, ValueT, MapType, VectorType >::operator[] (const KeyT & Key) inline
Definition at line 99 of file MapVector.h.
Referenced by llvm::ScheduleDAGInstrs::Value2SUsMap::insert().
pop_back()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> void llvm::MapVector< KeyT, ValueT, MapType, VectorType >::pop_back () inline
Remove the last element from the vector.
Definition at line 161 of file MapVector.h.
rbegin() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> reverse_iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::rbegin () inline
Definition at line 75 of file MapVector.h.
Referenced by llvm::InterleavedAccessInfo::analyzeInterleaving().
rbegin() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> const_reverse_iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::rbegin () const inline
Definition at line 76 of file MapVector.h.
remove_if() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> template<class Function > void llvm::MapVector< KeyT, ValueT, MapType, VectorType >::remove_if (Function Pred)
Definition at line 210 of file MapVector.h.
remove_if() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> template<class Predicate > void llvm::MapVector< KeyT, ValueT, MapType, VectorType >::remove_if (Predicate Pred)
Remove the elements that match the predicate.
Erase all elements that match Pred in a single pass. Takes linear time.
Referenced by llvm::ScheduleDAGInstrs::insertBarrierChain().
rend() [1/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> reverse_iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::rend () inline
Definition at line 77 of file MapVector.h.
Referenced by llvm::InterleavedAccessInfo::analyzeInterleaving().
rend() [2/2]
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> const_reverse_iterator llvm::MapVector< KeyT, ValueT, MapType, VectorType >::rend () const inline
Definition at line 78 of file MapVector.h.
reserve()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> void llvm::MapVector< KeyT, ValueT, MapType, VectorType >::reserve (size_type NumEntries) inline
Grow the MapVector so that it can contain at least NumEntries items before resizing again.
Definition at line 65 of file MapVector.h.
size()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> size_type llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size () const inline
Definition at line 61 of file MapVector.h.
Referenced by llvm::OpenMPIRBuilder::applySimd(), clusterSortPtrAccesses(), llvm::collectDebugInfoMetadata(), GEPToVectorIndex(), llvm::AArch64TTIImpl::preferPredicateOverEpilogue(), and llvm::writeIndex().
swap()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> void llvm::MapVector< KeyT, ValueT, MapType, VectorType >::swap (MapVector< KeyT, ValueT, MapType, VectorType > & RHS) inline
Definition at line 94 of file MapVector.h.
takeVector()
template<typename KeyT , typename ValueT , typename MapType = DenseMap<KeyT, unsigned>, typename VectorType = std::vector<std::pair<KeyT, ValueT>>> VectorType llvm::MapVector< KeyT, ValueT, MapType, VectorType >::takeVector () inline
Clear the MapVector and return the underlying vector.
Definition at line 56 of file MapVector.h.
Referenced by computeFunctionSummary().
The documentation for this class was generated from the following file:
include/llvm/ADT/MapVector.h