LLVM: llvm::ARMConstantPoolValue Class Reference
llvm::ARMConstantPoolValue Class Reference
ARMConstantPoolValue - ARM specific constantpool value.
#include "Target/ARM/ARMConstantPoolValue.h"
Public Member Functions
~ARMConstantPoolValue () override
ARMCP::ARMCPModifier getModifier () const
StringRef getModifierText () const
bool hasModifier () const
bool mustAddCurrentAddress () const
unsigned getLabelId () const
unsigned char getPCAdjustment () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isLSDA () const
bool isMachineBasicBlock () const
bool isPromotedGlobal () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
virtual bool hasSameValue (ARMConstantPoolValue *ACPV)
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
bool equals (const ARMConstantPoolValue *A) const
void print (raw_ostream &O) const override
print - Implement operator<<
void print (raw_ostream *O) const
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Protected Member Functions
ARMConstantPoolValue (Type *Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
ARMConstantPoolValue (LLVMContext &C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Detailed Description
ARMConstantPoolValue - ARM specific constantpool value.
This is used to represent PC-relative displacement between the address of the load instruction and the constant being loaded, i.e. (&GV-(LPIC+8)).
Definition at line 61 of file ARMConstantPoolValue.h.
Constructor & Destructor Documentation
ARMConstantPoolValue() [1/2]
ARMConstantPoolValue::ARMConstantPoolValue (Type * Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress) protected
Definition at line 33 of file ARMConstantPoolValue.cpp.
ARMConstantPoolValue() [2/2]
ARMConstantPoolValue::ARMConstantPoolValue (LLVMContext & C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress) protected
Definition at line 42 of file ARMConstantPoolValue.cpp.
~ARMConstantPoolValue()
ARMConstantPoolValue::~ARMConstantPoolValue () override default
Member Function Documentation
addSelectionDAGCSEId()
void ARMConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Reimplemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, and llvm::ARMConstantPoolConstant.
Definition at line 81 of file ARMConstantPoolValue.cpp.
Referenced by llvm::ARMConstantPoolConstant::addSelectionDAGCSEId(), llvm::ARMConstantPoolSymbol::addSelectionDAGCSEId(), and llvm::ARMConstantPoolMBB::addSelectionDAGCSEId().
dump()
LLVM_DUMP_METHOD void ARMConstantPoolValue::dump () const
Definition at line 102 of file ARMConstantPoolValue.cpp.
References llvm::errs().
equals()
bool llvm::ARMConstantPoolValue::equals (const ARMConstantPoolValue * A) const inline
Definition at line 123 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMConstantPoolConstant::equals(), llvm::ARMConstantPoolSymbol::equals(), and llvm::ARMConstantPoolMBB::equals().
getExistingMachineCPValue()
int ARMConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Reimplemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, and llvm::ARMConstantPoolConstant.
Definition at line 75 of file ARMConstantPoolValue.cpp.
References llvm_unreachable.
getExistingMachineCPValueImpl()
template<typename Derived > int llvm::ARMConstantPoolValue::getExistingMachineCPValueImpl (MachineConstantPool * CP, Align Alignment) inline protected
Definition at line 79 of file ARMConstantPoolValue.h.
References llvm::HexagonISD::CP, llvm::numbers::e, llvm::getAlign(), and i.
getLabelId()
unsigned llvm::ARMConstantPoolValue::getLabelId () const inline
Definition at line 104 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
getModifier()
ARMCP::ARMCPModifier llvm::ARMConstantPoolValue::getModifier () const inline
Definition at line 98 of file ARMConstantPoolValue.h.
Referenced by duplicateCPV(), and llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
getModifierText()
StringRef ARMConstantPoolValue::getModifierText () const
Definition at line 53 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::GOT_PREL, llvm::ARMCP::GOTTPOFF, llvm_unreachable, llvm::ARMCP::no_modifier, llvm::ARMCP::SBREL, llvm::ARMCP::SECREL, llvm::ARMCP::TLSGD, and llvm::ARMCP::TPOFF.
Referenced by print().
getPCAdjustment()
unsigned char llvm::ARMConstantPoolValue::getPCAdjustment () const inline
Definition at line 105 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
hasModifier()
bool llvm::ARMConstantPoolValue::hasModifier () const inline
Definition at line 100 of file ARMConstantPoolValue.h.
References llvm::ARMCP::no_modifier.
hasSameValue()
bool ARMConstantPoolValue::hasSameValue (ARMConstantPoolValue * ACPV) virtual
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
Reimplemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, and llvm::ARMConstantPoolConstant.
Definition at line 87 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::CPExtSymbol, and llvm::ARMCP::CPValue.
Referenced by llvm::ARMConstantPoolConstant::hasSameValue(), llvm::ARMConstantPoolSymbol::hasSameValue(), llvm::ARMConstantPoolMBB::hasSameValue(), and llvm::ARMBaseInstrInfo::produceSameValue().
isBlockAddress()
bool llvm::ARMConstantPoolValue::isBlockAddress () const inline
Definition at line 109 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPBlockAddress.
Referenced by llvm::ARMConstantPoolConstant::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
isExtSymbol()
bool llvm::ARMConstantPoolValue::isExtSymbol () const inline
Definition at line 108 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPExtSymbol.
Referenced by llvm::ARMConstantPoolSymbol::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
isGlobalValue()
bool llvm::ARMConstantPoolValue::isGlobalValue () const inline
Definition at line 107 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPValue.
Referenced by llvm::ARMConstantPoolConstant::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
isLSDA()
bool llvm::ARMConstantPoolValue::isLSDA () const inline
Definition at line 110 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPLSDA.
Referenced by llvm::ARMConstantPoolConstant::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
isMachineBasicBlock()
bool llvm::ARMConstantPoolValue::isMachineBasicBlock () const inline
Definition at line 111 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPMachineBasicBlock.
Referenced by llvm::ARMConstantPoolMBB::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
isPromotedGlobal()
bool llvm::ARMConstantPoolValue::isPromotedGlobal () const inline
Definition at line 112 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPPromotedGlobal.
Referenced by llvm::ARMConstantPoolConstant::classof(), and llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
mustAddCurrentAddress()
bool llvm::ARMConstantPoolValue::mustAddCurrentAddress () const inline
Definition at line 102 of file ARMConstantPoolValue.h.
Referenced by duplicateCPV(), and llvm::ARMAsmPrinter::emitMachineConstantPoolValue().
print() [1/2]
void ARMConstantPoolValue::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Reimplemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, and llvm::ARMConstantPoolConstant.
Definition at line 107 of file ARMConstantPoolValue.cpp.
References getModifierText(), llvm::RISCVFenceField::O, and unsigned.
Referenced by llvm::operator<<(), llvm::ARMConstantPoolConstant::print(), llvm::ARMConstantPoolSymbol::print(), and llvm::ARMConstantPoolMBB::print().
print() [2/2]
void llvm::ARMConstantPoolValue::print (raw_ostream * O) const inline
Definition at line 130 of file ARMConstantPoolValue.h.
References llvm::RISCVFenceField::O, and print().
Referenced by print().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMConstantPoolValue.h
lib/Target/ARM/ARMConstantPoolValue.cpp