LLVM: llvm::orc::GDBJITDebugInfoRegistrationPlugin Class Reference
llvm::orc::GDBJITDebugInfoRegistrationPlugin Class Reference
For each object containing debug info, installs JITLink passes to synthesize a debug object and then register it via the GDB JIT-registration interface.
#include "llvm/ExecutionEngine/Orc/DebuggerSupportPlugin.h"
Classes
class DebugSectionSynthesizer
Public Member Functions
GDBJITDebugInfoRegistrationPlugin (ExecutorAddr RegisterActionAddr)
Error notifyFailed (MaterializationResponsibility &MR) override
Error notifyRemovingResources (JITDylib &JD, ResourceKey K) override
void notifyTransferringResources (JITDylib &JD, ResourceKey DstKey, ResourceKey SrcKey) override
void modifyPassConfig (MaterializationResponsibility &MR, jitlink::LinkGraph &LG, jitlink::PassConfiguration &PassConfig) override
Public Member Functions inherited from llvm::orc::ObjectLinkingLayer::Plugin
virtual ~Plugin ()
virtual void notifyMaterializing (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::JITLinkContext &Ctx, MemoryBufferRef InputObject)
virtual void notifyLoaded (MaterializationResponsibility &MR)
virtual Error notifyEmitted (MaterializationResponsibility &MR)
virtual SyntheticSymbolDependenciesMap getSyntheticSymbolDependencies (MaterializationResponsibility &MR)
Return any dependencies that synthetic symbols (e.g.
Static Public Member Functions
static Expected< std::unique_ptr< GDBJITDebugInfoRegistrationPlugin > > Create (ExecutionSession &ES, JITDylib &ProcessJD, const Triple &TT)
Additional Inherited Members
Public Types inherited from llvm::orc::ObjectLinkingLayer::Plugin
using JITLinkSymbolSet = DenseSet< jitlink::Symbol * >
using SyntheticSymbolDependenciesMap = DenseMap< SymbolStringPtr, JITLinkSymbolSet >
Detailed Description
For each object containing debug info, installs JITLink passes to synthesize a debug object and then register it via the GDB JIT-registration interface.
Currently MachO only. For ELF use DebugObjectManagerPlugin. These two plugins will be merged in the near future.
Definition at line 28 of file DebuggerSupportPlugin.h.
Constructor & Destructor Documentation
GDBJITDebugInfoRegistrationPlugin()
llvm::orc::GDBJITDebugInfoRegistrationPlugin::GDBJITDebugInfoRegistrationPlugin (ExecutorAddr RegisterActionAddr) inline
Definition at line 40 of file DebuggerSupportPlugin.h.
Member Function Documentation
Create()
Expected< std::unique_ptr< GDBJITDebugInfoRegistrationPlugin > > llvm::orc::GDBJITDebugInfoRegistrationPlugin::Create (ExecutionSession & ES, JITDylib & ProcessJD, const Triple & TT) static
Definition at line 372 of file DebuggerSupportPlugin.cpp.
References Addr, llvm::orc::ExecutionSession::intern(), and llvm::orc::ExecutionSession::lookup().
modifyPassConfig()
void llvm::orc::GDBJITDebugInfoRegistrationPlugin::modifyPassConfig (MaterializationResponsibility & MR, jitlink::LinkGraph & LG, jitlink::PassConfiguration & PassConfig) override virtual
Reimplemented from llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 400 of file DebuggerSupportPlugin.cpp.
References llvm::dbgs(), llvm::jitlink::LinkGraph::getName(), llvm::Triple::getObjectFormat(), llvm::jitlink::LinkGraph::getTargetTriple(), LLVM_DEBUG, llvm::Triple::MachO, and llvm::Triple::str().
notifyFailed()
Error llvm::orc::GDBJITDebugInfoRegistrationPlugin::notifyFailed (MaterializationResponsibility & MR) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 387 of file DebuggerSupportPlugin.cpp.
References llvm::Error::success().
notifyRemovingResources()
Error llvm::orc::GDBJITDebugInfoRegistrationPlugin::notifyRemovingResources (JITDylib & JD, ResourceKey K) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 392 of file DebuggerSupportPlugin.cpp.
References llvm::Error::success().
notifyTransferringResources()
void llvm::orc::GDBJITDebugInfoRegistrationPlugin::notifyTransferringResources (JITDylib & JD, ResourceKey DstKey, ResourceKey SrcKey) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 397 of file DebuggerSupportPlugin.cpp.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/DebuggerSupportPlugin.h
lib/ExecutionEngine/Orc/DebuggerSupportPlugin.cpp