LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4 Class Reference
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerMsgPackV4 ()=default
~MetadataStreamerMsgPackV4 ()=default
void begin (const Module &Mod, const IsaInfo::AMDGPUTargetID &TargetID) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3
MetadataStreamerMsgPackV3 ()=default
~MetadataStreamerMsgPackV3 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()=default
Protected Member Functions
void emitVersion () override
void emitTargetID (const IsaInfo::AMDGPUTargetID &TargetID)
Protected Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3
void dump (StringRef HSAMetadataString) const
void verify (StringRef HSAMetadataString) const
std::optional< StringRef > getAccessQualifier (StringRef AccQual) const
std::optional< StringRef > getAddressSpaceQualifier (unsigned AddressSpace) const
StringRef getValueKind (Type *Ty, StringRef TypeQual, StringRef BaseTypeName) const
std::string getTypeName (Type *Ty, bool Signed) const
msgpack::ArrayDocNode getWorkGroupDimensions (MDNode *Node) const
msgpack::MapDocNode getHSAKernelProps (const MachineFunction &MF, const SIProgramInfo &ProgramInfo, unsigned CodeObjectVersion) const
void emitPrintf (const Module &Mod)
void emitKernelLanguage (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelAttrs (const Function &Func, msgpack::MapDocNode Kern) override
void emitKernelArgs (const MachineFunction &MF, msgpack::MapDocNode Kern)
void emitKernelArg (const Argument &Arg, unsigned &Offset, msgpack::ArrayDocNode Args)
void emitKernelArg (const DataLayout &DL, Type *Ty, Align Alignment, StringRef ValueKind, unsigned &Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign=std::nullopt, StringRef Name="", StringRef TypeName="", StringRef BaseTypeName="", StringRef AccQual="", StringRef TypeQual="")
void emitHiddenKernelArgs (const MachineFunction &MF, unsigned &Offset, msgpack::ArrayDocNode Args) override
msgpack::DocNode & getRootMetadata (StringRef Key)
msgpack::DocNode & getHSAMetadataRoot ()
Additional Inherited Members
Protected Attributes inherited from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3
std::unique_ptr< msgpack::Document > HSAMetadataDoc
Detailed Description
Definition at line 137 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerMsgPackV4()
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::MetadataStreamerMsgPackV4 () default
~MetadataStreamerMsgPackV4()
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::~MetadataStreamerMsgPackV4 () default
Member Function Documentation
begin()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::begin (const Module & Mod, const IsaInfo::AMDGPUTargetID & TargetID) override virtual
Reimplemented from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3.
Definition at line 988 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitPrintf(), emitTargetID(), emitVersion(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getRootMetadata(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::HSAMetadataDoc, and Mod.
emitTargetID()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitTargetID (const IsaInfo::AMDGPUTargetID & TargetID) protected
Definition at line 982 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getRootMetadata(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::HSAMetadataDoc, and llvm::AMDGPU::IsaInfo::AMDGPUTargetID::toString().
Referenced by begin().
emitVersion()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitVersion () override protected virtual
Reimplemented from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5.
Definition at line 975 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getRootMetadata(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::HSAMetadataDoc, llvm::IndexedInstrProf::Version, llvm::AMDGPU::HSAMD::VersionMajorV4, and llvm::AMDGPU::HSAMD::VersionMinorV4.
Referenced by begin().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp