LLVM: llvm::RISCVDAGToDAGISel Class Reference
llvm::RISCVDAGToDAGISel Class Reference
#include "Target/RISCV/RISCVISelDAGToDAG.h"
Public Member Functions
RISCVDAGToDAGISel ()=delete
RISCVDAGToDAGISel (RISCVTargetMachine &TargetMachine, CodeGenOpt::Level OptLevel)
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
void PreprocessISelDAG () override
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
void PostprocessISelDAG () override
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
void Select (SDNode *Node) override
Main hook for targets to transform nodes into machine nodes.
bool SelectInlineAsmMemoryOperand (const SDValue &Op, unsigned ConstraintID, std::vector< SDValue > &OutOps) override
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint.
bool SelectAddrFrameIndex (SDValue Addr, SDValue &Base, SDValue &Offset)
bool SelectFrameAddrRegImm (SDValue Addr, SDValue &Base, SDValue &Offset)
bool SelectAddrRegImm (SDValue Addr, SDValue &Base, SDValue &Offset)
bool tryShrinkShlLogicImm (SDNode *Node)
bool selectShiftMask (SDValue N, unsigned ShiftWidth, SDValue &ShAmt)
bool selectShiftMaskXLen (SDValue N, SDValue &ShAmt)
bool selectShiftMask32 (SDValue N, SDValue &ShAmt)
bool selectSExtBits (SDValue N, unsigned Bits, SDValue &Val)
template<unsigned Bits>
bool selectSExtBits (SDValue N, SDValue &Val)
bool selectZExtBits (SDValue N, unsigned Bits, SDValue &Val)
template<unsigned Bits>
bool selectZExtBits (SDValue N, SDValue &Val)
bool selectSHXADDOp (SDValue N, unsigned ShAmt, SDValue &Val)
Look for various patterns that can be done with a SHL that can be folded into a SHXADD.
template<unsigned ShAmt>
bool selectSHXADDOp (SDValue N, SDValue &Val)
bool selectSHXADD_UWOp (SDValue N, unsigned ShAmt, SDValue &Val)
Look for various patterns that can be done with a SHL that can be folded into a SHXADD_UW.
template<unsigned ShAmt>
bool selectSHXADD_UWOp (SDValue N, SDValue &Val)
bool hasAllNBitUsers (SDNode *Node, unsigned Bits, const unsigned Depth=0) const
bool hasAllHUsers (SDNode *Node) const
bool hasAllWUsers (SDNode *Node) const
bool selectVLOp (SDValue N, SDValue &VL)
bool selectVSplat (SDValue N, SDValue &SplatVal)
bool selectVSplatSimm5 (SDValue N, SDValue &SplatVal)
bool selectVSplatUimm5 (SDValue N, SDValue &SplatVal)
bool selectVSplatSimm5Plus1 (SDValue N, SDValue &SplatVal)
bool selectVSplatSimm5Plus1NonZero (SDValue N, SDValue &SplatVal)
bool selectFPImm (SDValue N, SDValue &Imm)
bool selectRVVSimm5 (SDValue N, unsigned Width, SDValue &Imm)
template<unsigned Width>
bool selectRVVSimm5 (SDValue N, SDValue &Imm)
void addVectorLoadStoreOperands (SDNode *Node, unsigned SEWImm, const SDLoc &DL, unsigned CurOp, bool IsMasked, bool IsStridedOrIndexed, SmallVectorImpl< SDValue > &Operands, bool IsLoad=false, MVT *IndexVT=nullptr)
void selectVLSEG (SDNode *Node, bool IsMasked, bool IsStrided)
void selectVLSEGFF (SDNode *Node, bool IsMasked)
void selectVLXSEG (SDNode *Node, bool IsMasked, bool IsOrdered)
void selectVSSEG (SDNode *Node, bool IsMasked, bool IsStrided)
void selectVSXSEG (SDNode *Node, bool IsMasked, bool IsOrdered)
void selectVSETVLI (SDNode *Node)
Public Member Functions inherited from llvm::SelectionDAGISel
SelectionDAGISel (char &ID, TargetMachine &tm, CodeGenOpt::Level OL=CodeGenOpt::Default)
~SelectionDAGISel () override
const TargetLowering * getTargetLowering () const
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual void emitFunctionEntryCode ()
virtual bool IsProfitableToFold (SDValue N, SDNode *U, SDNode *Root) const
IsProfitableToFold - Returns true if it's profitable to fold the specific operand node N of U during instruction selection that starts at Root.
bool CheckAndMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckAndMask - The isel is trying to match something like (and X, 255).
bool CheckOrMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
CheckOrMask - The isel is trying to match something like (or X, 255).
virtual bool CheckPatternPredicate (unsigned PredNo) const
CheckPatternPredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicate (SDNode *N, unsigned PredNo) const
CheckNodePredicate - This function is generated by tblgen in the target.
virtual bool CheckNodePredicateWithOperands (SDNode *N, unsigned PredNo, const SmallVectorImpl< SDValue > &Operands) const
CheckNodePredicateWithOperands - This function is generated by tblgen in the target.
virtual bool CheckComplexPattern (SDNode *Root, SDNode *Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > &Result)
virtual SDValue RunSDNodeXForm (SDValue V, unsigned XFormNo)
void SelectCodeCommon (SDNode *NodeToMatch, const unsigned char *MatcherTable, unsigned TableSize)
virtual bool ComplexPatternFuncMutatesDAG () const
Return true if complex patterns for this target can mutate the DAG.
bool mayRaiseFPException (SDNode *Node) const
Return whether the node may raise an FP exception.
bool isOrEquivalentToAdd (const SDNode *N) const
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Member Functions
static RISCVCC::CondCode getRISCVCCForIntCC (ISD::CondCode CC)
Static Public Member Functions inherited from llvm::SelectionDAGISel
static bool IsLegalToFold (SDValue N, SDNode *U, SDNode *Root, CodeGenOpt::Level OptLevel, bool IgnoreChains=false)
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root.
static void InvalidateNodeId (SDNode *N)
static int getUninvalidatedNodeId (SDNode *N)
static void EnforceNodeIdInvariant (SDNode *N)
static int getNumFixedFromVariadicInfo (unsigned Flags)
getNumFixedFromVariadicInfo - Transform an EmitNode flags word into the number of fixed arity values that should be skipped when copying from the root.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Public Types inherited from llvm::SelectionDAGISel
enum BuiltinOpcodes {
OPC_Scope, OPC_RecordNode, OPC_RecordChild0, OPC_RecordChild1,
OPC_RecordChild2, OPC_RecordChild3, OPC_RecordChild4, OPC_RecordChild5,
OPC_RecordChild6, OPC_RecordChild7, OPC_RecordMemRef, OPC_CaptureGlueInput,
OPC_MoveChild, OPC_MoveChild0, OPC_MoveChild1, OPC_MoveChild2,
OPC_MoveChild3, OPC_MoveChild4, OPC_MoveChild5, OPC_MoveChild6,
OPC_MoveChild7, OPC_MoveParent, OPC_CheckSame, OPC_CheckChild0Same,
OPC_CheckChild1Same, OPC_CheckChild2Same, OPC_CheckChild3Same, OPC_CheckPatternPredicate,
OPC_CheckPredicate, OPC_CheckPredicateWithOperands, OPC_CheckOpcode, OPC_SwitchOpcode,
OPC_CheckType, OPC_CheckTypeRes, OPC_SwitchType, OPC_CheckChild0Type,
OPC_CheckChild1Type, OPC_CheckChild2Type, OPC_CheckChild3Type, OPC_CheckChild4Type,
OPC_CheckChild5Type, OPC_CheckChild6Type, OPC_CheckChild7Type, OPC_CheckInteger,
OPC_CheckChild0Integer, OPC_CheckChild1Integer, OPC_CheckChild2Integer, OPC_CheckChild3Integer,
OPC_CheckChild4Integer, OPC_CheckCondCode, OPC_CheckChild2CondCode, OPC_CheckValueType,
OPC_CheckComplexPat, OPC_CheckAndImm, OPC_CheckOrImm, OPC_CheckImmAllOnesV,
OPC_CheckImmAllZerosV, OPC_CheckFoldableChainNode, OPC_EmitInteger, OPC_EmitStringInteger,
OPC_EmitRegister, OPC_EmitRegister2, OPC_EmitConvertToTarget, OPC_EmitMergeInputChains,
OPC_EmitMergeInputChains1_0, OPC_EmitMergeInputChains1_1, OPC_EmitMergeInputChains1_2, OPC_EmitCopyToReg,
OPC_EmitCopyToReg2, OPC_EmitNodeXForm, OPC_EmitNode, OPC_EmitNode0,
OPC_EmitNode1, OPC_EmitNode2, OPC_MorphNodeTo, OPC_MorphNodeTo0,
OPC_MorphNodeTo1, OPC_MorphNodeTo2, OPC_CompleteMatch, OPC_Coverage
}
enum {
OPFL_None = 0, OPFL_Chain = 1, OPFL_GlueInput = 2, OPFL_GlueOutput = 4,
OPFL_MemRefs = 8, OPFL_Variadic0 = 1<<4, OPFL_Variadic1 = 2<<4, OPFL_Variadic2 = 3<<4,
OPFL_Variadic3 = 4<<4, OPFL_Variadic4 = 5<<4, OPFL_Variadic5 = 6<<4, OPFL_Variadic6 = 7<<4,
OPFL_VariadicInfo = OPFL_Variadic6
}
Public Attributes inherited from llvm::SelectionDAGISel
TargetMachine & TM
const TargetLibraryInfo * LibInfo
std::unique_ptr< FunctionLoweringInfo > FuncInfo
SwiftErrorValueTracking * SwiftError
MachineFunction * MF
MachineRegisterInfo * RegInfo
SelectionDAG * CurDAG
std::unique_ptr< SelectionDAGBuilder > SDB
AAResults * AA = nullptr
AssumptionCache * AC = nullptr
GCFunctionInfo * GFI = nullptr
CodeGenOpt::Level OptLevel
const TargetInstrInfo * TII
const TargetLowering * TLI
bool FastISelFailed
SmallPtrSet< const Instruction *, 4 > ElidedArgCopyInstrs
std::unique_ptr< OptimizationRemarkEmitter > ORE
Current optimization remark emitter.
Protected Member Functions inherited from llvm::SelectionDAGISel
void ReplaceUses (SDValue F, SDValue T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceUses (const SDValue *F, const SDValue *T, unsigned Num)
ReplaceUses - replace all uses of the old nodes F with the use of the new nodes T.
void ReplaceUses (SDNode *F, SDNode *T)
ReplaceUses - replace all uses of the old node F with the use of the new node T.
void ReplaceNode (SDNode *F, SDNode *T)
Replace all uses of F with T, then remove F from the DAG.
void SelectInlineAsmMemoryOperands (std::vector< SDValue > &Ops, const SDLoc &DL)
SelectInlineAsmMemoryOperands - Calls to this are automatically generated by tblgen.
virtual StringRef getPatternForIndex (unsigned index)
getPatternForIndex - Patterns selected by tablegen during ISEL
virtual StringRef getIncludePathForIndex (unsigned index)
getIncludePathForIndex - get the td source location of pattern instantiation
bool shouldOptForSize (const MachineFunction *MF) const
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes inherited from llvm::SelectionDAGISel
unsigned DAGSize = 0
DAGSize - Size of DAG being instruction selected.
Detailed Description
Definition at line 24 of file RISCVISelDAGToDAG.h.
Constructor & Destructor Documentation
RISCVDAGToDAGISel() [1/2]
llvm::RISCVDAGToDAGISel::RISCVDAGToDAGISel () delete
RISCVDAGToDAGISel() [2/2]
llvm::RISCVDAGToDAGISel::RISCVDAGToDAGISel (RISCVTargetMachine & TargetMachine, CodeGenOpt::Level OptLevel) inline explicit
Definition at line 32 of file RISCVISelDAGToDAG.h.
Member Function Documentation
addVectorLoadStoreOperands()
void RISCVDAGToDAGISel::addVectorLoadStoreOperands (SDNode * Node, unsigned SEWImm, const SDLoc & DL, unsigned CurOp, bool IsMasked, bool IsStridedOrIndexed, SmallVectorImpl< SDValue > & Operands, bool IsLoad = false, MVT * IndexVT = nullptr)
Definition at line 266 of file RISCVISelDAGToDAG.cpp.
getRISCVCCForIntCC()
static RISCVCC::CondCode llvm::RISCVDAGToDAGISel::getRISCVCCForIntCC (ISD::CondCode CC) inline static
Definition at line 118 of file RISCVISelDAGToDAG.h.
References CC, llvm::RISCVCC::COND_EQ, llvm::RISCVCC::COND_GE, llvm::RISCVCC::COND_GEU, llvm::RISCVCC::COND_LT, llvm::RISCVCC::COND_LTU, llvm::RISCVCC::COND_NE, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, and llvm::ISD::SETULT.
hasAllHUsers()
bool llvm::RISCVDAGToDAGISel::hasAllHUsers (SDNode * Node) const inline
Definition at line 84 of file RISCVISelDAGToDAG.h.
References hasAllNBitUsers().
hasAllNBitUsers()
bool RISCVDAGToDAGISel::hasAllNBitUsers (SDNode * Node, unsigned Bits, const unsigned Depth = 0) const
Definition at line 2356 of file RISCVISelDAGToDAG.cpp.
Referenced by hasAllHUsers(), and hasAllWUsers().
hasAllWUsers()
bool llvm::RISCVDAGToDAGISel::hasAllWUsers (SDNode * Node) const inline
Definition at line 85 of file RISCVISelDAGToDAG.h.
References hasAllNBitUsers().
PostprocessISelDAG()
void RISCVDAGToDAGISel::PostprocessISelDAG () override virtual
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
Reimplemented from llvm::SelectionDAGISel.
Definition at line 152 of file RISCVISelDAGToDAG.cpp.
References llvm::SelectionDAG::allnodes_begin(), llvm::SelectionDAG::allnodes_end(), llvm::SelectionDAGISel::CurDAG, llvm::NVPTXISD::Dummy, llvm::SelectionDAG::getRoot(), N, llvm::SelectionDAG::RemoveDeadNodes(), and llvm::SelectionDAG::setRoot().
PreprocessISelDAG()
void RISCVDAGToDAGISel::PreprocessISelDAG () override virtual
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
Reimplemented from llvm::SelectionDAGISel.
Definition at line 60 of file RISCVISelDAGToDAG.cpp.
References Align, llvm::SelectionDAG::allnodes_begin(), llvm::SelectionDAG::allnodes_end(), assert(), llvm::SelectionDAGISel::CurDAG, llvm::dbgs(), DL, llvm::TypeSize::Fixed(), llvm::SelectionDAGISel::FuncInfo, llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::SelectionDAG::getVTList(), llvm::MachinePointerInfo::getWithOffset(), llvm::RISCVSubtarget::getXLenVT(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_W_CHAIN, llvm::MVT::isInteger(), llvm::MVT::isScalableVector(), LLVM_DEBUG, llvm::SelectionDAGISel::MF, llvm::MachineMemOperand::MOLoad, N, llvm::MVT::Other, llvm::SelectionDAG::RemoveDeadNodes(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SPLAT_VECTOR, llvm::RISCVISD::SPLAT_VECTOR_SPLIT_I64_VL, llvm::SelectionDAGISel::TLI, llvm::ISD::TokenFactor, llvm::RISCVISD::VFMV_V_F_VL, and llvm::RISCVISD::VMV_V_X_VL.
runOnMachineFunction()
bool llvm::RISCVDAGToDAGISel::runOnMachineFunction (MachineFunction & MF) inline override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Reimplemented from llvm::SelectionDAGISel.
Definition at line 36 of file RISCVISelDAGToDAG.h.
References llvm::MachineFunction::getSubtarget(), llvm::SelectionDAGISel::MF, and llvm::SelectionDAGISel::runOnMachineFunction().
Select()
void RISCVDAGToDAGISel::Select (SDNode * N) override virtual
Main hook for targets to transform nodes into machine nodes.
Implements llvm::SelectionDAGISel.
Definition at line 664 of file RISCVISelDAGToDAG.cpp.
SelectAddrFrameIndex()
bool RISCVDAGToDAGISel::SelectAddrFrameIndex (SDValue Addr, SDValue & Base, SDValue & Offset)
Definition at line 1906 of file RISCVISelDAGToDAG.cpp.
References Addr, llvm::sampleprof::Base, llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::RISCVSubtarget::getXLenVT(), and llvm::Offset.
Referenced by SelectAddrRegImm(), and SelectFrameAddrRegImm().
SelectAddrRegImm()
bool RISCVDAGToDAGISel::SelectAddrRegImm (SDValue Addr, SDValue & Base, SDValue & Offset)
Definition at line 2011 of file RISCVISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::RISCVISD::ADD_LO, Addr, assert(), llvm::sampleprof::Base, llvm::commonAlignment(), llvm::SelectionDAGISel::CurDAG, DL, llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValueType(), llvm::SelectionDAG::isBaseWithConstantOffset(), isWorthFoldingAdd(), llvm::Offset, SelectAddrFrameIndex(), and selectConstantAddr().
selectFPImm()
bool RISCVDAGToDAGISel::selectFPImm (SDValue N, SDValue & Imm)
Definition at line 2611 of file RISCVISelDAGToDAG.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), llvm::SelectionDAGISel::CurDAG, DL, llvm::MVT::f64, llvm::APInt::getSExtValue(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDNode::getValueType(), llvm::RISCVSubtarget::getXLenVT(), llvm::RISCVMatInt::Imm, llvm::RISCVSubtarget::is64Bit(), llvm::APFloat::isNegZero(), llvm::APFloat::isPosZero(), N, and selectImm().
SelectFrameAddrRegImm()
bool RISCVDAGToDAGISel::SelectFrameAddrRegImm (SDValue Addr, SDValue & Base, SDValue & Offset)
Definition at line 1918 of file RISCVISelDAGToDAG.cpp.
References Addr, llvm::sampleprof::Base, llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::RISCVSubtarget::getXLenVT(), llvm::SelectionDAG::isBaseWithConstantOffset(), llvm::Offset, and SelectAddrFrameIndex().
SelectInlineAsmMemoryOperand()
bool RISCVDAGToDAGISel::SelectInlineAsmMemoryOperand (const SDValue & Op, unsigned ConstraintID, std::vector< SDValue > & OutOps) override virtual
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint.
If this does not match or is not implemented, return true. The resultant operands (which will appear in the machine instruction) should be added to the OutOps vector.
Reimplemented from llvm::SelectionDAGISel.
Definition at line 1888 of file RISCVISelDAGToDAG.cpp.
References llvm::InlineAsm::Constraint_A, and llvm::InlineAsm::Constraint_m.
selectRVVSimm5() [1/2]
template<unsigned Width> bool llvm::RISCVDAGToDAGISel::selectRVVSimm5 (SDValue N, SDValue & Imm) inline
Definition at line 97 of file RISCVISelDAGToDAG.h.
References llvm::RISCVMatInt::Imm, N, and selectRVVSimm5().
selectRVVSimm5() [2/2]
bool RISCVDAGToDAGISel::selectRVVSimm5 (SDValue N, unsigned Width, SDValue & Imm)
Definition at line 2630 of file RISCVISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getTargetConstant(), llvm::RISCVSubtarget::getXLenVT(), llvm::RISCVMatInt::Imm, N, and llvm::SignExtend64().
Referenced by selectRVVSimm5().
selectSExtBits() [1/2]
template<unsigned Bits> bool llvm::RISCVDAGToDAGISel::selectSExtBits (SDValue N, SDValue & Val) inline
Definition at line 64 of file RISCVISelDAGToDAG.h.
References llvm::tgtok::Bits, N, and selectSExtBits().
selectSExtBits() [2/2]
bool RISCVDAGToDAGISel::selectSExtBits (SDValue N, unsigned Bits, SDValue & Val)
Definition at line 2168 of file RISCVISelDAGToDAG.cpp.
References llvm::tgtok::Bits, llvm::SelectionDAG::ComputeNumSignBits(), llvm::SelectionDAGISel::CurDAG, llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::getSizeInBits(), N, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND_INREG, and llvm::ISD::SRA.
Referenced by selectSExtBits().
selectShiftMask()
bool RISCVDAGToDAGISel::selectShiftMask (SDValue N, unsigned ShiftWidth, SDValue & ShAmt)
Definition at line 2101 of file RISCVISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, assert(), llvm::SelectionDAG::computeKnownBits(), llvm::SelectionDAGISel::CurDAG, DL, llvm::APInt::getBitWidth(), llvm::SDValue::getConstantOperandAPInt(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::MVT::i64, llvm::RISCVMatInt::Imm, llvm::isPowerOf2_32(), llvm::APInt::isSubsetOf(), N, llvm::ISD::SUB, uint64_t, and llvm::KnownBits::Zero.
Referenced by selectShiftMask32(), and selectShiftMaskXLen().
selectShiftMask32()
bool llvm::RISCVDAGToDAGISel::selectShiftMask32 (SDValue N, SDValue & ShAmt) inline
Definition at line 59 of file RISCVISelDAGToDAG.h.
References N, and selectShiftMask().
selectShiftMaskXLen()
bool llvm::RISCVDAGToDAGISel::selectShiftMaskXLen (SDValue N, SDValue & ShAmt) inline
Definition at line 56 of file RISCVISelDAGToDAG.h.
References llvm::RISCVSubtarget::getXLen(), N, and selectShiftMask().
selectSHXADD_UWOp() [1/2]
template<unsigned ShAmt> bool llvm::RISCVDAGToDAGISel::selectSHXADD_UWOp (SDValue N, SDValue & Val) inline
Definition at line 78 of file RISCVISelDAGToDAG.h.
References N, and selectSHXADD_UWOp().
selectSHXADD_UWOp() [2/2]
bool RISCVDAGToDAGISel::selectSHXADD_UWOp (SDValue N, unsigned ShAmt, SDValue & Val)
Look for various patterns that can be done with a SHL that can be folded into a SHXADD_UW.
ShAmt contains 1, 2, or 3 and is set based on which SHXADD_UW we are trying to match.
Definition at line 2313 of file RISCVISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::countl_zero(), llvm::countr_zero(), llvm::SelectionDAGISel::CurDAG, DL, llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::hasOneUse(), llvm::isShiftedMask_64(), llvm::BitmaskEnumDetail::Mask(), N, llvm::ISD::SHL, and uint64_t.
Referenced by selectSHXADD_UWOp().
selectSHXADDOp() [1/2]
template<unsigned ShAmt> bool llvm::RISCVDAGToDAGISel::selectSHXADDOp (SDValue N, SDValue & Val) inline
Definition at line 73 of file RISCVISelDAGToDAG.h.
References N, and selectSHXADDOp().
selectSHXADDOp() [2/2]
bool RISCVDAGToDAGISel::selectSHXADDOp (SDValue N, unsigned ShAmt, SDValue & Val)
Look for various patterns that can be done with a SHL that can be folded into a SHXADD.
ShAmt contains 1, 2, or 3 and is set based on which SHXADD we are trying to match.
Definition at line 2218 of file RISCVISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::bit_width(), C1, llvm::countr_zero(), llvm::SelectionDAGISel::CurDAG, DL, llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::RISCVSubtarget::getXLen(), llvm::SDValue::hasOneUse(), llvm::isShiftedMask_64(), llvm::BitmaskEnumDetail::Mask(), N, llvm::ISD::SHL, llvm::ISD::SRL, and uint64_t.
Referenced by selectSHXADDOp().
selectVLOp()
bool RISCVDAGToDAGISel::selectVLOp (SDValue N, SDValue & VL)
Definition at line 2508 of file RISCVISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, getReg(), llvm::SelectionDAG::getTargetConstant(), N, and llvm::RISCV::VLMaxSentinel.
selectVLSEG()
void RISCVDAGToDAGISel::selectVLSEG (SDNode * Node, bool IsMasked, bool IsStrided)
Definition at line 313 of file RISCVISelDAGToDAG.cpp.
selectVLSEGFF()
void RISCVDAGToDAGISel::selectVLSEGFF (SDNode * Node, bool IsMasked)
Definition at line 356 of file RISCVISelDAGToDAG.cpp.
selectVLXSEG()
void RISCVDAGToDAGISel::selectVLXSEG (SDNode * Node, bool IsMasked, bool IsOrdered)
Definition at line 401 of file RISCVISelDAGToDAG.cpp.
selectVSETVLI()
void RISCVDAGToDAGISel::selectVSETVLI (SDNode * Node)
Definition at line 529 of file RISCVISelDAGToDAG.cpp.
selectVSplat()
bool RISCVDAGToDAGISel::selectVSplat (SDValue N, SDValue & SplatVal)
Definition at line 2532 of file RISCVISelDAGToDAG.cpp.
References assert(), N, and llvm::RISCVISD::VMV_V_X_VL.
selectVSplatSimm5()
bool RISCVDAGToDAGISel::selectVSplatSimm5 (SDValue N, SDValue & SplatVal)
Definition at line 2575 of file RISCVISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::RISCVMatInt::Imm, N, and selectVSplatSimmHelper().
selectVSplatSimm5Plus1()
bool RISCVDAGToDAGISel::selectVSplatSimm5Plus1 (SDValue N, SDValue & SplatVal)
Definition at line 2580 of file RISCVISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::RISCVMatInt::Imm, N, and selectVSplatSimmHelper().
selectVSplatSimm5Plus1NonZero()
bool RISCVDAGToDAGISel::selectVSplatSimm5Plus1NonZero (SDValue N, SDValue & SplatVal)
Definition at line 2586 of file RISCVISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::RISCVMatInt::Imm, N, and selectVSplatSimmHelper().
selectVSplatUimm5()
bool RISCVDAGToDAGISel::selectVSplatUimm5 (SDValue N, SDValue & SplatVal)
Definition at line 2594 of file RISCVISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, llvm::SelectionDAG::getTargetConstant(), llvm::RISCVSubtarget::getXLenVT(), N, and llvm::RISCVISD::VMV_V_X_VL.
selectVSSEG()
void RISCVDAGToDAGISel::selectVSSEG (SDNode * Node, bool IsMasked, bool IsStrided)
Definition at line 455 of file RISCVISelDAGToDAG.cpp.
selectVSXSEG()
void RISCVDAGToDAGISel::selectVSXSEG (SDNode * Node, bool IsMasked, bool IsOrdered)
Definition at line 487 of file RISCVISelDAGToDAG.cpp.
selectZExtBits() [1/2]
template<unsigned Bits> bool llvm::RISCVDAGToDAGISel::selectZExtBits (SDValue N, SDValue & Val) inline
Definition at line 68 of file RISCVISelDAGToDAG.h.
References llvm::tgtok::Bits, N, and selectZExtBits().
selectZExtBits() [2/2]
bool RISCVDAGToDAGISel::selectZExtBits (SDValue N, unsigned Bits, SDValue & Val)
Definition at line 2197 of file RISCVISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::tgtok::Bits, llvm::SelectionDAGISel::CurDAG, llvm::APInt::getBitsSetFrom(), llvm::MVT::getSizeInBits(), llvm::BitmaskEnumDetail::Mask(), llvm::SelectionDAG::MaskedValueIsZero(), and N.
Referenced by selectZExtBits().
tryShrinkShlLogicImm()
bool RISCVDAGToDAGISel::tryShrinkShlLogicImm (SDNode * Node)
Definition at line 586 of file RISCVISelDAGToDAG.cpp.
Member Data Documentation
ID
char RISCVDAGToDAGISel::ID = 0 static
Definition at line 28 of file RISCVISelDAGToDAG.h.
The documentation for this class was generated from the following files:
lib/Target/RISCV/RISCVISelDAGToDAG.h
lib/Target/RISCV/RISCVISelDAGToDAG.cpp