LLVM: llvm::LoongArchSubtarget Class Reference
llvm::LoongArchSubtarget Class Reference
#include "Target/LoongArch/LoongArchSubtarget.h"
Public Member Functions
LoongArchSubtarget (const Triple &TT, StringRef CPU, StringRef TuneCPU, StringRef FS, StringRef ABIName, const TargetMachine &TM)
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
const LoongArchFrameLowering * getFrameLowering () const override
const LoongArchInstrInfo * getInstrInfo () const override
const LoongArchRegisterInfo * getRegisterInfo () const override
const LoongArchTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool is64Bit () const
bool hasBasicF () const
bool hasBasicD () const
bool hasExtLSX () const
bool hasExtLASX () const
bool hasExtLVZ () const
bool hasExtLBT () const
bool hasLaGlobalWithPcrel () const
bool hasLaGlobalWithAbs () const
bool hasLaLocalWithAbs () const
MVT getGRLenVT () const
unsigned getGRLen () const
LoongArchABI::ABI getTargetABI () const
Detailed Description
Definition at line 32 of file LoongArchSubtarget.h.
Constructor & Destructor Documentation
LoongArchSubtarget()
LoongArchSubtarget::LoongArchSubtarget (const Triple & TT, StringRef CPU, StringRef TuneCPU, StringRef FS, StringRef ABIName, const TargetMachine & TM)
Definition at line 57 of file LoongArchSubtarget.cpp.
Member Function Documentation
getFrameLowering()
const LoongArchFrameLowering* llvm::LoongArchSubtarget::getFrameLowering () const inline override
Definition at line 71 of file LoongArchSubtarget.h.
getGRLen()
unsigned llvm::LoongArchSubtarget::getGRLen () const inline
Definition at line 95 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::decomposeMulByConstant(), llvm::LoongArchTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::LoongArchTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::LoongArchTargetLowering::LoongArchTargetLowering(), llvm::LoongArchTargetLowering::LowerFormalArguments(), and llvm::LoongArchDAGToDAGISel::selectShiftMaskGRLen().
getGRLenVT()
MVT llvm::LoongArchSubtarget::getGRLenVT () const inline
Definition at line 94 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::LoongArchTargetLowering(), llvm::LoongArchTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerFormalArguments(), performANDCombine(), performORCombine(), performSRLCombine(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::LoongArchDAGToDAGISel::SelectBaseAddr(), and llvm::LoongArchDAGToDAGISel::SelectInlineAsmMemoryOperand().
getInstrInfo()
const LoongArchInstrInfo* llvm::LoongArchSubtarget::getInstrInfo () const inline override
Definition at line 74 of file LoongArchSubtarget.h.
References InstrInfo.
Referenced by llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::LoongArchFrameLowering::emitPrologue(), and llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized().
getRegisterInfo()
const LoongArchRegisterInfo* llvm::LoongArchSubtarget::getRegisterInfo () const inline override
Definition at line 75 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchFrameLowering::emitEpilogue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::LoongArchTargetLowering::getRegisterByName(), llvm::LoongArchFrameLowering::hasBP(), llvm::LoongArchTargetLowering::LoongArchTargetLowering(), llvm::LoongArchTargetLowering::LowerCall(), and llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized().
getSelectionDAGInfo()
const SelectionDAGTargetInfo* llvm::LoongArchSubtarget::getSelectionDAGInfo () const inline override
Definition at line 81 of file LoongArchSubtarget.h.
getTargetABI()
LoongArchABI::ABI llvm::LoongArchSubtarget::getTargetABI () const inline
Definition at line 96 of file LoongArchSubtarget.h.
getTargetLowering()
const LoongArchTargetLowering* llvm::LoongArchSubtarget::getTargetLowering () const inline override
Definition at line 78 of file LoongArchSubtarget.h.
hasBasicD()
bool llvm::LoongArchSubtarget::hasBasicD () const inline
Definition at line 86 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::LoongArchTargetLowering().
hasBasicF()
bool llvm::LoongArchSubtarget::hasBasicF () const inline
Definition at line 85 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchRegisterInfo::getReservedRegs(), llvm::LoongArchTargetLowering::LoongArchTargetLowering(), needScavSlotForCFR(), and llvm::LoongArchTargetLowering::ReplaceNodeResults().
hasExtLASX()
bool llvm::LoongArchSubtarget::hasExtLASX () const inline
Definition at line 88 of file LoongArchSubtarget.h.
hasExtLBT()
bool llvm::LoongArchSubtarget::hasExtLBT () const inline
Definition at line 90 of file LoongArchSubtarget.h.
hasExtLSX()
bool llvm::LoongArchSubtarget::hasExtLSX () const inline
Definition at line 87 of file LoongArchSubtarget.h.
hasExtLVZ()
bool llvm::LoongArchSubtarget::hasExtLVZ () const inline
Definition at line 89 of file LoongArchSubtarget.h.
hasLaGlobalWithAbs()
bool llvm::LoongArchSubtarget::hasLaGlobalWithAbs () const inline
Definition at line 92 of file LoongArchSubtarget.h.
hasLaGlobalWithPcrel()
bool llvm::LoongArchSubtarget::hasLaGlobalWithPcrel () const inline
Definition at line 91 of file LoongArchSubtarget.h.
hasLaLocalWithAbs()
bool llvm::LoongArchSubtarget::hasLaLocalWithAbs () const inline
Definition at line 93 of file LoongArchSubtarget.h.
is64Bit()
bool llvm::LoongArchSubtarget::is64Bit () const inline
Definition at line 84 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::LoongArchTargetLowering::LoongArchTargetLowering(), llvm::LoongArchInstrInfo::movImm(), and llvm::LoongArchTargetLowering::ReplaceNodeResults().
ParseSubtargetFeatures()
void llvm::LoongArchSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
The documentation for this class was generated from the following files:
lib/Target/LoongArch/LoongArchSubtarget.h
lib/Target/LoongArch/LoongArchSubtarget.cpp