LLVM: llvm::LazyValueInfo Class Reference
llvm::LazyValueInfo Class Reference
This pass computes, caches, and vends lazy value constraint information.
#include "llvm/Analysis/LazyValueInfo.h"
Public Types
enum Tristate { Unknown = -1, False = 0, True = 1 }
This is used to return true/false/dunno results.
Public Member Functions
~LazyValueInfo ()
LazyValueInfo ()=default
LazyValueInfo (AssumptionCache *AC_, const DataLayout *DL_, TargetLibraryInfo *TLI_)
LazyValueInfo (LazyValueInfo &&Arg)
LazyValueInfo & operator= (LazyValueInfo &&Arg)
Tristate getPredicateOnEdge (unsigned Pred, Value *V, Constant *C, BasicBlock *FromBB, BasicBlock *ToBB, Instruction *CxtI=nullptr)
Determine whether the specified value comparison with a constant is known to be true or false on the specified CFG edge.
Tristate getPredicateAt (unsigned Pred, Value *V, Constant *C, Instruction *CxtI, bool UseBlockValue)
Determine whether the specified value comparison with a constant is known to be true or false at the specified instruction.
Tristate getPredicateAt (unsigned Pred, Value *LHS, Value *RHS, Instruction *CxtI, bool UseBlockValue)
Determine whether the specified value comparison is known to be true or false at the specified instruction.
Constant * getConstant (Value *V, Instruction *CxtI)
Determine whether the specified value is known to be a constant at the specified instruction.
ConstantRange getConstantRange (Value *V, Instruction *CxtI, bool UndefAllowed=true)
Return the ConstantRange constraint that is known to hold for the specified value at the specified instruction.
ConstantRange getConstantRangeAtUse (const Use &U, bool UndefAllowed=true)
Return the ConstantRange constraint that is known to hold for the value at a specific use-site.
Constant * getConstantOnEdge (Value *V, BasicBlock *FromBB, BasicBlock *ToBB, Instruction *CxtI=nullptr)
Determine whether the specified value is known to be a constant on the specified edge.
ConstantRange getConstantRangeOnEdge (Value *V, BasicBlock *FromBB, BasicBlock *ToBB, Instruction *CxtI=nullptr)
Return the ConstantRage constraint that is known to hold for the specified value on the specified edge.
void threadEdge (BasicBlock *PredBB, BasicBlock *OldSucc, BasicBlock *NewSucc)
Inform the analysis cache that we have threaded an edge from PredBB to OldSucc to be from PredBB to NewSucc instead.
void eraseBlock (BasicBlock *BB)
Inform the analysis cache that we have erased a block.
void clear (const Module *M)
Complete flush all previously computed values.
void printLVI (Function &F, DominatorTree &DTree, raw_ostream &OS)
Print the \LazyValueInfo Analysis.
void releaseMemory ()
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
Handle invalidation events in the new pass manager.
Friends
class LazyValueInfoWrapperPass
Detailed Description
This pass computes, caches, and vends lazy value constraint information.
Definition at line 31 of file LazyValueInfo.h.
Member Enumeration Documentation
Tristate
enum llvm::LazyValueInfo::Tristate
This is used to return true/false/dunno results.
Enumerator
Unknown
False
True
Definition at line 60 of file LazyValueInfo.h.
Constructor & Destructor Documentation
~LazyValueInfo()
LazyValueInfo::~LazyValueInfo ()
Definition at line 1573 of file LazyValueInfo.cpp.
References releaseMemory().
LazyValueInfo() [1/3]
llvm::LazyValueInfo::LazyValueInfo () default
LazyValueInfo() [2/3]
llvm::LazyValueInfo::LazyValueInfo (AssumptionCache * AC_, const DataLayout * DL_, TargetLibraryInfo * TLI_) inline
Definition at line 42 of file LazyValueInfo.h.
LazyValueInfo() [3/3]
llvm::LazyValueInfo::LazyValueInfo (LazyValueInfo && Arg) inline
Definition at line 45 of file LazyValueInfo.h.
References Arg.
Member Function Documentation
clear()
void LazyValueInfo::clear (const Module * M)
Complete flush all previously computed values.
Definition at line 1970 of file LazyValueInfo.cpp.
References getImpl(), and M.
eraseBlock()
void LazyValueInfo::eraseBlock (BasicBlock * BB)
Inform the analysis cache that we have erased a block.
Definition at line 1964 of file LazyValueInfo.cpp.
References BB, and getImpl().
getConstant()
Constant * LazyValueInfo::getConstant (Value * V, Instruction * CxtI)
Determine whether the specified value is known to be a constant at the specified instruction.
Return null if not.
Definition at line 1618 of file LazyValueInfo.cpp.
References BB, llvm::ConstantInt::get(), llvm::Value::getContext(), getImpl(), llvm::Instruction::getParent(), llvm::ConstantRange::getSingleElement(), and isKnownNonConstant().
Referenced by getConstantAt(), processCallSite(), processMemAccess(), and processSelect().
getConstantOnEdge()
Constant * LazyValueInfo::getConstantOnEdge (Value * V, BasicBlock * FromBB, BasicBlock * ToBB, Instruction * CxtI = nullptr)
Determine whether the specified value is known to be a constant on the specified edge.
Return null if not.
Definition at line 1700 of file LazyValueInfo.cpp.
References llvm::ConstantInt::get(), llvm::Value::getContext(), getImpl(), llvm::BasicBlock::getModule(), llvm::ConstantRange::getSingleElement(), and M.
Referenced by getValueOnEdge(), and simplifyCommonValuePhi().
getConstantRange()
ConstantRange LazyValueInfo::getConstantRange (Value * V, Instruction * CxtI, bool UndefAllowed = true)
Return the ConstantRange constraint that is known to hold for the specified value at the specified instruction.
This may only be called on integer-typed Values.
Definition at line 1637 of file LazyValueInfo.cpp.
References assert(), BB, getImpl(), llvm::Type::getIntegerBitWidth(), llvm::Instruction::getParent(), llvm::Value::getType(), and llvm::Type::isIntegerTy().
Referenced by getConstantRangeAtUse(), processBinOp(), and processICmp().
getConstantRangeAtUse()
ConstantRange LazyValueInfo::getConstantRangeAtUse (const Use & U, bool UndefAllowed = true)
Return the ConstantRange constraint that is known to hold for the value at a specific use-site.
Definition at line 1655 of file LazyValueInfo.cpp.
References llvm::Use::get(), getConstantRange(), getEdgeValueLocal(), llvm::Use::getUser(), getValueFromCondition(), I, llvm::ConstantRange::intersectWith(), llvm::isSafeToSpeculativelyExecute(), PHI, SI, and llvm::Value::use_begin().
Referenced by processAnd(), processAShr(), processSDivOrSRem(), processSExt(), processUDivOrURem(), and willNotOverflow().
getConstantRangeOnEdge()
ConstantRange LazyValueInfo::getConstantRangeOnEdge (Value * V, BasicBlock * FromBB, BasicBlock * ToBB, Instruction * CxtI = nullptr)
Return the ConstantRage constraint that is known to hold for the specified value on the specified edge.
This may be only be called on integer-typed Values.
Definition at line 1717 of file LazyValueInfo.cpp.
References assert(), getImpl(), llvm::Type::getIntegerBitWidth(), llvm::BasicBlock::getModule(), llvm::Value::getType(), and M.
getPredicateAt() [1/2]
LazyValueInfo::Tristate LazyValueInfo::getPredicateAt (unsigned Pred, Value * LHS, Value * RHS, Instruction * CxtI, bool UseBlockValue)
Determine whether the specified value comparison is known to be true or false at the specified instruction.
While this takes two Value's, it still requires that one of them is a constant. Pred is a CmpInst predicate. If UseBlockValue is true, the block value is also taken into account.
Definition at line 1920 of file LazyValueInfo.cpp.
References False, llvm::ValueLatticeElement::getCompare(), getImpl(), getPredicateAt(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::ValueLatticeElement::isOverdefined(), LHS, M, llvm::CmpInst::makeCmpResultType(), P, RHS, True, and Unknown.
getPredicateAt() [2/2]
LazyValueInfo::Tristate LazyValueInfo::getPredicateAt (unsigned Pred, Value * V, Constant * C, Instruction * CxtI, bool UseBlockValue)
Determine whether the specified value comparison with a constant is known to be true or false at the specified instruction.
Pred is a CmpInst predicate. If UseBlockValue is true, the block value is also taken into account.
Definition at line 1816 of file LazyValueInfo.cpp.
References BB, DL, llvm::numbers::e, False, getImpl(), llvm::Instruction::getModule(), llvm::Instruction::getParent(), getPredicateOnEdge(), getPredicateResult(), llvm::Value::getType(), i, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::isKnownNonZero(), llvm::Type::isPointerTy(), M, PHI, llvm::pred_begin(), llvm::pred_end(), llvm::MipsISD::Ret, llvm::Value::stripPointerCastsSameRepresentation(), True, and Unknown.
Referenced by constantFoldCmp(), getConstantAt(), getPredicateAt(), processAbsIntrinsic(), processCallSite(), processMinMaxIntrinsic(), and processSwitch().
getPredicateOnEdge()
LazyValueInfo::Tristate LazyValueInfo::getPredicateOnEdge (unsigned Pred, Value * V, Constant * C, BasicBlock * FromBB, BasicBlock * ToBB, Instruction * CxtI = nullptr)
Determine whether the specified value comparison with a constant is known to be true or false on the specified CFG edge.
Pred is a CmpInst predicate.
Definition at line 1805 of file LazyValueInfo.cpp.
References getImpl(), llvm::BasicBlock::getModule(), getPredicateResult(), and M.
Referenced by getPredicateAt(), and getValueOnEdge().
invalidate()
bool LazyValueInfo::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Handle invalidation events in the new pass manager.
Definition at line 1583 of file LazyValueInfo.cpp.
References llvm::PreservedAnalyses::getChecker().
operator=()
LazyValueInfo& llvm::LazyValueInfo::operator= (LazyValueInfo && Arg) inline
Definition at line 49 of file LazyValueInfo.h.
References Arg, DL, and releaseMemory().
printLVI()
void LazyValueInfo::printLVI (Function & F, DominatorTree & DTree, raw_ostream & OS)
Print the \LazyValueInfo Analysis.
We pass in the DTree that is required for identifying which basic blocks we can solve/print for, in the LVIPrinter.
Definition at line 1976 of file LazyValueInfo.cpp.
References F, getImpl(), and OS.
releaseMemory()
void LazyValueInfo::releaseMemory ()
Definition at line 1575 of file LazyValueInfo.cpp.
References getImpl().
Referenced by operator=(), llvm::LazyValueInfoWrapperPass::releaseMemory(), and ~LazyValueInfo().
threadEdge()
void LazyValueInfo::threadEdge (BasicBlock * PredBB, BasicBlock * OldSucc, BasicBlock * NewSucc)
Inform the analysis cache that we have threaded an edge from PredBB to OldSucc to be from PredBB to NewSucc instead.
Definition at line 1956 of file LazyValueInfo.cpp.
References getImpl(), and llvm::BasicBlock::getModule().
Friends And Related Function Documentation
LazyValueInfoWrapperPass
friend class LazyValueInfoWrapperPass friend
Definition at line 32 of file LazyValueInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LazyValueInfo.h
lib/Analysis/LazyValueInfo.cpp