LLVM: llvm::APByteStreamer Class Reference
llvm::APByteStreamer Class Reference final
#include "CodeGen/AsmPrinter/ByteStreamer.h"
Public Member Functions
APByteStreamer (AsmPrinter &Asm)
void emitInt8 (uint8_t Byte, const Twine &Comment) override
void emitSLEB128 (uint64_t DWord, const Twine &Comment) override
void emitULEB128 (uint64_t DWord, const Twine &Comment, unsigned PadTo) override
unsigned emitDIERef (const DIE &D) override
Additional Inherited Members
Protected Member Functions inherited from llvm::ByteStreamer
~ByteStreamer ()=default
ByteStreamer (const ByteStreamer &)=default
ByteStreamer ()=default
Detailed Description
Definition at line 39 of file ByteStreamer.h.
Constructor & Destructor Documentation
APByteStreamer()
llvm::APByteStreamer::APByteStreamer (AsmPrinter & Asm) inline
Definition at line 44 of file ByteStreamer.h.
Member Function Documentation
emitDIERef()
unsigned llvm::APByteStreamer::emitDIERef (const DIE & D) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 58 of file ByteStreamer.h.
References assert(), D, emitULEB128(), llvm::Offset, uint64_t, and ULEB128PadSize.
emitInt8()
void llvm::APByteStreamer::emitInt8 (uint8_t Byte, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 45 of file ByteStreamer.h.
References llvm::AsmPrinter::emitInt8(), and llvm::AsmPrinter::OutStreamer.
emitSLEB128()
void llvm::APByteStreamer::emitSLEB128 (uint64_t DWord, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 49 of file ByteStreamer.h.
References llvm::AsmPrinter::emitSLEB128(), and llvm::AsmPrinter::OutStreamer.
emitULEB128()
void llvm::APByteStreamer::emitULEB128 (uint64_t DWord, const Twine & Comment, unsigned PadTo) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 53 of file ByteStreamer.h.
References llvm::AsmPrinter::emitULEB128(), and llvm::AsmPrinter::OutStreamer.
Referenced by emitDIERef().
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/ByteStreamer.h