LLVM: llvm::MCInstBuilder Class Reference
llvm::MCInstBuilder Class Reference
#include "llvm/MC/MCInstBuilder.h"
Public Member Functions
MCInstBuilder (unsigned Opcode)
Create a new MCInstBuilder for an MCInst with a specific opcode.
MCInstBuilder & addReg (unsigned Reg)
Add a new register operand.
MCInstBuilder & addImm (int64_t Val)
Add a new integer immediate operand.
MCInstBuilder & addSFPImm (uint32_t Val)
Add a new single floating point immediate operand.
MCInstBuilder & addDFPImm (uint64_t Val)
Add a new floating point immediate operand.
MCInstBuilder & addExpr (const MCExpr *Val)
Add a new MCExpr operand.
MCInstBuilder & addInst (const MCInst *Val)
Add a new MCInst operand.
MCInstBuilder & addOperand (const MCOperand &Op)
Add an operand.
operator MCInst & ()
Detailed Description
Definition at line 21 of file MCInstBuilder.h.
Constructor & Destructor Documentation
MCInstBuilder()
llvm::MCInstBuilder::MCInstBuilder (unsigned Opcode) inline
Create a new MCInstBuilder for an MCInst with a specific opcode.
Definition at line 26 of file MCInstBuilder.h.
References llvm::MCInst::setOpcode().
Member Function Documentation
addDFPImm()
MCInstBuilder& llvm::MCInstBuilder::addDFPImm (uint64_t Val) inline
Add a new floating point immediate operand.
Definition at line 49 of file MCInstBuilder.h.
References llvm::MCInst::addOperand(), and llvm::MCOperand::createDFPImm().
addExpr()
MCInstBuilder& llvm::MCInstBuilder::addExpr (const MCExpr * Val) inline
Add a new MCExpr operand.
Definition at line 55 of file MCInstBuilder.h.
References llvm::MCInst::addOperand(), and llvm::MCOperand::createExpr().
Referenced by llvm::SystemZAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), and llvm::X86AsmPrinter::emitInstruction().
addImm()
MCInstBuilder& llvm::MCInstBuilder::addImm (int64_t Val) inline
Add a new integer immediate operand.
Definition at line 37 of file MCInstBuilder.h.
References llvm::MCInst::addOperand(), and llvm::MCOperand::createImm().
Referenced by llvm::SystemZAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::CSKYMCCodeEmitter::encodeInstruction(), llvm::CSKYMCCodeEmitter::expandJBTF(), llvm::CSKYMCCodeEmitter::expandNEG(), llvm::CSKYMCCodeEmitter::expandRSUBI(), llvm::Thumb1InstrInfo::getNop(), llvm::Thumb2InstrInfo::getNop(), llvm::RISCVInstrInfo::getNop(), llvm::AArch64InstrInfo::getNop(), llvm::HexagonInstrInfo::getNop(), lowerRIEfLow(), lowerRIHigh(), lowerRILow(), lowerSubvectorLoad(), lowerSubvectorStore(), and llvm::ARMAsmPrinter::runOnMachineFunction().
addInst()
MCInstBuilder& llvm::MCInstBuilder::addInst (const MCInst * Val) inline
Add a new MCInst operand.
Definition at line 61 of file MCInstBuilder.h.
References llvm::MCInst::addOperand(), and llvm::MCOperand::createInst().
Referenced by llvm::HexagonInstrInfo::getNop().
addOperand()
MCInstBuilder& llvm::MCInstBuilder::addOperand (const MCOperand & Op) inline
Add an operand.
Definition at line 67 of file MCInstBuilder.h.
References llvm::MCInst::addOperand().
Referenced by llvm::CSKYMCCodeEmitter::encodeInstruction(), llvm::CSKYMCCodeEmitter::expandJBTF(), llvm::CSKYMCCodeEmitter::expandNEG(), and llvm::CSKYMCCodeEmitter::expandRSUBI().
addReg()
MCInstBuilder& llvm::MCInstBuilder::addReg (unsigned Reg) inline
Add a new register operand.
Definition at line 31 of file MCInstBuilder.h.
References llvm::MCInst::addOperand(), and llvm::MCOperand::createReg().
Referenced by llvm::SystemZAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::Thumb2InstrInfo::getNop(), llvm::Thumb1InstrInfo::getNop(), llvm::RISCVInstrInfo::getNop(), lowerRIEfLow(), lowerRIHigh(), lowerRILow(), lowerSubvectorLoad(), lowerSubvectorStore(), and llvm::ARMAsmPrinter::runOnMachineFunction().
addSFPImm()
MCInstBuilder& llvm::MCInstBuilder::addSFPImm (uint32_t Val) inline
Add a new single floating point immediate operand.
Definition at line 43 of file MCInstBuilder.h.
References llvm::MCInst::addOperand(), and llvm::MCOperand::createSFPImm().
operator MCInst &()
llvm::MCInstBuilder::operator MCInst & () inline
Definition at line 72 of file MCInstBuilder.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCInstBuilder.h