LLVM: llvm::CSKYMCInstLower Class Reference
llvm::CSKYMCInstLower Class Reference
#include "Target/CSKY/CSKYMCInstLower.h"
Public Member Functions
CSKYMCInstLower (MCContext &Ctx, AsmPrinter &Printer)
void Lower (const MachineInstr *MI, MCInst &OutMI) const
bool lowerOperand (const MachineOperand &MO, MCOperand &MCOp) const
MCOperand lowerSymbolOperand (const MachineOperand &MO, MCSymbol *Sym) const
Detailed Description
Definition at line 21 of file CSKYMCInstLower.h.
Constructor & Destructor Documentation
CSKYMCInstLower()
CSKYMCInstLower::CSKYMCInstLower (MCContext & Ctx, AsmPrinter & Printer)
Definition at line 24 of file CSKYMCInstLower.cpp.
Member Function Documentation
Lower()
void CSKYMCInstLower::Lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 27 of file CSKYMCInstLower.cpp.
References llvm::MCInst::addOperand(), lowerOperand(), MI, and llvm::MCInst::setOpcode().
Referenced by llvm::CSKYAsmPrinter::emitInstruction().
lowerOperand()
bool CSKYMCInstLower::lowerOperand (const MachineOperand & MO, MCOperand & MCOp) const
Definition at line 76 of file CSKYMCInstLower.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getMCSymbol(), llvm::MachineOperand::getReg(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImplicit(), llvm_unreachable, lowerSymbolOperand(), llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_MCSymbol, llvm::MachineOperand::MO_Register, and llvm::MachineOperand::MO_RegisterMask.
Referenced by Lower().
lowerSymbolOperand()
MCOperand CSKYMCInstLower::lowerSymbolOperand (const MachineOperand & MO, MCSymbol * Sym) const
Definition at line 37 of file CSKYMCInstLower.cpp.
References llvm::CSKYMCExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCOperand::createExpr(), llvm::MachineOperand::getTargetFlags(), llvm_unreachable, llvm::CSKYII::MO_ADDR32, llvm::CSKYII::MO_ADDR_HI16, llvm::CSKYII::MO_ADDR_LO16, llvm::CSKYII::MO_GOT32, llvm::CSKYII::MO_GOTOFF, llvm::CSKYII::MO_None, llvm::CSKYII::MO_PLT32, llvm::AsmPrinter::OutContext, llvm::CSKYMCExpr::VK_CSKY_ADDR, llvm::CSKYMCExpr::VK_CSKY_ADDR_HI16, llvm::CSKYMCExpr::VK_CSKY_ADDR_LO16, llvm::CSKYMCExpr::VK_CSKY_GOT, llvm::CSKYMCExpr::VK_CSKY_GOTOFF, llvm::CSKYMCExpr::VK_CSKY_None, llvm::CSKYMCExpr::VK_CSKY_PLT, and llvm::MCSymbolRefExpr::VK_None.
Referenced by lowerOperand().
The documentation for this class was generated from the following files:
lib/Target/CSKY/CSKYMCInstLower.h
lib/Target/CSKY/CSKYMCInstLower.cpp