LLVM: llvm::object::COFFImportFile Class Reference
llvm::object::COFFImportFile Class Reference
#include "llvm/Object/COFFImportFile.h"
Public Member Functions
COFFImportFile (MemoryBufferRef Source)
void moveSymbolNext (DataRefImpl &Symb) const override
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
Expected< uint32_t > getSymbolFlags (DataRefImpl Symb) const override
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
bool is64Bit () const override
const coff_import_header * getCOFFImportHeader () const
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
virtual Error initContent ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isOffloadFile () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static bool classof (Binary const *V)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context, bool InitContent=true)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static bool isSymbolicFile (file_magic Type, const LLVMContext *Context)
Static Public Member Functions inherited from llvm::object::Binary
static Error checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Additional Inherited Members
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_COFFImportFile, ID_IR,
ID_TapiUniversal, ID_TapiFile, ID_Minidump, ID_WinRes,
ID_Offload, ID_StartObjects, ID_COFF, ID_XCOFF32,
ID_XCOFF64, ID_ELF32L, ID_ELF32B, ID_ELF64L,
ID_ELF64B, ID_MachO32L, ID_MachO32B, ID_MachO64L,
ID_MachO64B, ID_Wasm, ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 29 of file COFFImportFile.h.
Constructor & Destructor Documentation
COFFImportFile()
llvm::object::COFFImportFile::COFFImportFile (MemoryBufferRef Source) inline
Definition at line 31 of file COFFImportFile.h.
Member Function Documentation
classof()
static bool llvm::object::COFFImportFile::classof (Binary const * V) inline static
Definition at line 34 of file COFFImportFile.h.
References llvm::object::Binary::isCOFFImportFile().
getCOFFImportHeader()
const coff_import_header* llvm::object::COFFImportFile::getCOFFImportHeader () const inline
Definition at line 61 of file COFFImportFile.h.
References llvm::object::Binary::Data, and llvm::MemoryBufferRef::getBufferStart().
getSymbolFlags()
Expected<uint32_t> llvm::object::COFFImportFile::getSymbolFlags (DataRefImpl Symb) const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 45 of file COFFImportFile.h.
References llvm::object::BasicSymbolRef::SF_Global.
is64Bit()
bool llvm::object::COFFImportFile::is64Bit () const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 59 of file COFFImportFile.h.
moveSymbolNext()
void llvm::object::COFFImportFile::moveSymbolNext (DataRefImpl & Symb) const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 36 of file COFFImportFile.h.
References llvm::object::DataRefImpl::p.
printSymbolName()
Error llvm::object::COFFImportFile::printSymbolName (raw_ostream & OS, DataRefImpl Symb) const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 38 of file COFFImportFile.h.
References llvm::object::Binary::Data, llvm::MemoryBufferRef::getBufferStart(), OS, llvm::object::DataRefImpl::p, and llvm::Error::success().
symbol_begin()
basic_symbol_iterator llvm::object::COFFImportFile::symbol_begin () const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 49 of file COFFImportFile.h.
symbol_end()
basic_symbol_iterator llvm::object::COFFImportFile::symbol_end () const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 53 of file COFFImportFile.h.
References llvm::object::DataRefImpl::p.
The documentation for this class was generated from the following file:
include/llvm/Object/COFFImportFile.h