LLVM: llvm::ReachingDefAnalysis Class Reference
llvm::ReachingDefAnalysis Class Reference
This class provides the reaching def analysis.
#include "llvm/CodeGen/ReachingDefAnalysis.h"
Public Member Functions
ReachingDefAnalysis ()
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
bool runOnMachineFunction (MachineFunction &MF) override
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
MachineFunctionProperties getRequiredProperties () const override
void reset ()
Re-run the analysis.
void init ()
Initialize data structures.
void traverse ()
Traverse the machine function, mapping definitions.
int getReachingDef (MachineInstr *MI, MCRegister PhysReg) const
Provides the instruction id of the closest reaching def instruction of PhysReg that reaches MI, relative to the begining of MI's basic block.
bool hasSameReachingDef (MachineInstr *A, MachineInstr *B, MCRegister PhysReg) const
Return whether A and B use the same def of PhysReg.
bool isReachingDefLiveOut (MachineInstr *MI, MCRegister PhysReg) const
Return whether the reaching def for MI also is live out of its parent block.
MachineInstr * getLocalLiveOutMIDef (MachineBasicBlock *MBB, MCRegister PhysReg) const
Return the local MI that produces the live out value for PhysReg, or nullptr for a non-live out or non-local def.
MachineInstr * getUniqueReachingMIDef (MachineInstr *MI, MCRegister PhysReg) const
If a single MachineInstr creates the reaching definition, then return it.
MachineInstr * getMIOperand (MachineInstr *MI, unsigned Idx) const
If a single MachineInstr creates the reaching definition, for MIs operand at Idx, then return it.
MachineInstr * getMIOperand (MachineInstr *MI, MachineOperand &MO) const
If a single MachineInstr creates the reaching definition, for MIs MO, then return it.
bool hasLocalDefBefore (MachineInstr *MI, MCRegister PhysReg) const
Provide whether the register has been defined in the same basic block as, and before, MI.
bool isRegUsedAfter (MachineInstr *MI, MCRegister PhysReg) const
Return whether the given register is used after MI, whether it's a local use or a live out.
bool isRegDefinedAfter (MachineInstr *MI, MCRegister PhysReg) const
Return whether the given register is defined after MI.
int getClearance (MachineInstr *MI, MCRegister PhysReg) const
Provides the clearance - the number of instructions since the closest reaching def instuction of PhysReg that reaches MI.
void getReachingLocalUses (MachineInstr *MI, MCRegister PhysReg, InstSet &Uses) const
Provides the uses, in the same block as MI, of register that MI defines.
void getLiveOuts (MachineBasicBlock *MBB, MCRegister PhysReg, InstSet &Defs, BlockSet &VisitedBBs) const
Search MBB for a definition of PhysReg and insert it into Defs.
void getLiveOuts (MachineBasicBlock *MBB, MCRegister PhysReg, InstSet &Defs) const
bool getLiveInUses (MachineBasicBlock *MBB, MCRegister PhysReg, InstSet &Uses) const
For the given block, collect the instructions that use the live-in value of the provided register.
void getGlobalUses (MachineInstr *MI, MCRegister PhysReg, InstSet &Uses) const
Collect the users of the value stored in PhysReg, which is defined by MI.
void getGlobalReachingDefs (MachineInstr *MI, MCRegister PhysReg, InstSet &Defs) const
Collect all possible definitions of the value stored in PhysReg, which is used by MI.
bool isSafeToMoveForwards (MachineInstr *From, MachineInstr *To) const
Return whether From can be moved forwards to just before To.
bool isSafeToMoveBackwards (MachineInstr *From, MachineInstr *To) const
Return whether From can be moved backwards to just after To.
void collectKilledOperands (MachineInstr *MI, InstSet &Dead) const
Assuming MI is dead, recursively search the incoming operands which are killed by MI and collect those that would become dead.
bool isSafeToRemove (MachineInstr *MI, InstSet &ToRemove) const
Return whether removing this instruction will have no effect on the program, returning the redundant use-def chain.
bool isSafeToRemove (MachineInstr *MI, InstSet &ToRemove, InstSet &Ignore) const
Return whether removing this instruction will have no effect on the program, ignoring the possible effects on some instructions, returning the redundant use-def chain.
bool isSafeToDefRegAt (MachineInstr *MI, MCRegister PhysReg) const
Return whether a MachineInstr could be inserted at MI and safely define the given register without affecting the program.
bool isSafeToDefRegAt (MachineInstr *MI, MCRegister PhysReg, InstSet &Ignore) const
Return whether a MachineInstr could be inserted at MI and safely define the given register without affecting the program, ignoring any effects on the provided instructions.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
This class provides the reaching def analysis.
Definition at line 69 of file ReachingDefAnalysis.h.
Constructor & Destructor Documentation
ReachingDefAnalysis()
llvm::ReachingDefAnalysis::ReachingDefAnalysis () inline
Definition at line 113 of file ReachingDefAnalysis.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeReachingDefAnalysisPass().
Member Function Documentation
collectKilledOperands()
void ReachingDefAnalysis::collectKilledOperands (MachineInstr * MI, InstSet & Dead) const
Assuming MI is dead, recursively search the incoming operands which are killed by MI and collect those that would become dead.
Definition at line 649 of file ReachingDefAnalysis.cpp.
References llvm::RegState::Dead, llvm::tgtok::Def, getGlobalUses(), getMIOperand(), IsDead, isValidRegDef(), isValidRegUse(), mayHaveSideEffects(), MI, llvm::set_is_subset(), and Uses.
Referenced by if().
getAnalysisUsage()
void llvm::ReachingDefAnalysis::getAnalysisUsage (AnalysisUsage & AU) const inline override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 118 of file ReachingDefAnalysis.h.
References llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getClearance()
int ReachingDefAnalysis::getClearance (MachineInstr * MI, MCRegister PhysReg) const
Provides the clearance - the number of instructions since the closest reaching def instuction of PhysReg that reaches MI.
Definition at line 320 of file ReachingDefAnalysis.cpp.
References assert(), getReachingDef(), and MI.
getGlobalReachingDefs()
void ReachingDefAnalysis::getGlobalReachingDefs (MachineInstr * MI, MCRegister PhysReg, InstSet & Defs) const
Collect all possible definitions of the value stored in PhysReg, which is used by MI.
Definition at line 400 of file ReachingDefAnalysis.cpp.
References llvm::tgtok::Def, getLiveOuts(), getUniqueReachingMIDef(), llvm::SmallPtrSetImpl< PtrType >::insert(), MBB, and MI.
Referenced by producesFalseLanesZero().
getGlobalUses()
void ReachingDefAnalysis::getGlobalUses (MachineInstr * MI, MCRegister PhysReg, InstSet & Uses) const
Collect the users of the value stored in PhysReg, which is defined by MI.
Definition at line 375 of file ReachingDefAnalysis.cpp.
References llvm::append_range(), llvm::SmallPtrSetImpl< PtrType >::count(), getLiveInUses(), getLocalLiveOutMIDef(), getReachingLocalUses(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MachineBasicBlock::isLiveIn(), MBB, MI, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MachineBasicBlock::successors(), and Uses.
Referenced by collectKilledOperands(), and isSafeToDefRegAt().
getLiveInUses()
bool ReachingDefAnalysis::getLiveInUses (MachineBasicBlock * MBB, MCRegister PhysReg, InstSet & Uses) const
For the given block, collect the instructions that use the live-in value of the provided register.
Return whether the value is still live on exit.
Definition at line 356 of file ReachingDefAnalysis.cpp.
References llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getLastNonDebugInstr(), getReachingDef(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), llvm::instructionsWithoutDebug(), isReachingDefLiveOut(), isValidRegUseOf(), llvm::Last, MBB, MI, and Uses.
Referenced by getGlobalUses().
getLiveOuts() [1/2]
void ReachingDefAnalysis::getLiveOuts (MachineBasicBlock * MBB, MCRegister PhysReg, InstSet & Defs) const
Definition at line 412 of file ReachingDefAnalysis.cpp.
References getLiveOuts(), and MBB.
getLiveOuts() [2/2]
void ReachingDefAnalysis::getLiveOuts (MachineBasicBlock * MBB, MCRegister PhysReg, InstSet & Defs, BlockSet & VisitedBBs) const
Search MBB for a definition of PhysReg and insert it into Defs.
If no definition is found, recursively search the predecessor blocks for them.
Definition at line 418 of file ReachingDefAnalysis.cpp.
References llvm::LivePhysRegs::addLiveOuts(), llvm::LivePhysRegs::available(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::tgtok::Def, getLocalLiveOutMIDef(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::SmallPtrSetImpl< PtrType >::insert(), MBB, and llvm::MachineBasicBlock::predecessors().
Referenced by getGlobalReachingDefs(), getLiveOuts(), and getUniqueReachingMIDef().
getLocalLiveOutMIDef()
MachineInstr * ReachingDefAnalysis::getLocalLiveOutMIDef (MachineBasicBlock * MBB, MCRegister PhysReg) const
Return the local MI that produces the live out value for PhysReg, or nullptr for a non-live out or non-local def.
Definition at line 527 of file ReachingDefAnalysis.cpp.
References llvm::LivePhysRegs::addLiveOuts(), llvm::LivePhysRegs::available(), llvm::tgtok::Def, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineBasicBlock::getParent(), getReachingDef(), llvm::MachineFunction::getRegInfo(), isValidRegDefOf(), llvm::Last, and MBB.
Referenced by getGlobalUses(), getLiveOuts(), and isRegDefinedAfter().
getMIOperand() [1/2]
MachineInstr * ReachingDefAnalysis::getMIOperand (MachineInstr * MI, MachineOperand & MO) const
If a single MachineInstr creates the reaching definition, for MIs MO, then return it.
Otherwise return null.
Definition at line 464 of file ReachingDefAnalysis.cpp.
References assert(), llvm::MachineOperand::getReg(), getUniqueReachingMIDef(), llvm::MachineOperand::isReg(), and MI.
getMIOperand() [2/2]
MachineInstr * ReachingDefAnalysis::getMIOperand (MachineInstr * MI, unsigned Idx) const
If a single MachineInstr creates the reaching definition, for MIs operand at Idx, then return it.
Otherwise return null.
Definition at line 458 of file ReachingDefAnalysis.cpp.
References assert(), getUniqueReachingMIDef(), and MI.
Referenced by collectKilledOperands().
getReachingDef()
int ReachingDefAnalysis::getReachingDef (MachineInstr * MI, MCRegister PhysReg) const
Provides the instruction id of the closest reaching def instruction of PhysReg that reaches MI, relative to the begining of MI's basic block.
Definition at line 263 of file ReachingDefAnalysis.cpp.
References assert(), llvm::tgtok::Def, llvm::max(), and MI.
Referenced by getClearance(), getLiveInUses(), getLocalLiveOutMIDef(), hasLocalDefBefore(), hasSameReachingDef(), isReachingDefLiveOut(), and isRegDefinedAfter().
getReachingLocalUses()
void ReachingDefAnalysis::getReachingLocalUses (MachineInstr * MI, MCRegister PhysReg, InstSet & Uses) const
Provides the uses, in the same block as MI, of register that MI defines.
This does not consider live-outs.
Definition at line 331 of file ReachingDefAnalysis.cpp.
References llvm::tgtok::Def, llvm::MachineBasicBlock::end(), isValidRegUseOf(), MBB, MI, and Uses.
Referenced by getGlobalUses().
getRequiredProperties()
MachineFunctionProperties llvm::ReachingDefAnalysis::getRequiredProperties () const inline override virtual
Reimplemented from llvm::MachineFunctionPass.
Definition at line 125 of file ReachingDefAnalysis.h.
References llvm::MachineFunctionProperties::NoVRegs, llvm::MachineFunctionProperties::set(), and llvm::MachineFunctionProperties::TracksLiveness.
getUniqueReachingMIDef()
MachineInstr * ReachingDefAnalysis::getUniqueReachingMIDef (MachineInstr * MI, MCRegister PhysReg) const
If a single MachineInstr creates the reaching definition, then return it.
Otherwise return null.
Definition at line 438 of file ReachingDefAnalysis.cpp.
References llvm::SmallPtrSetImpl< PtrType >::begin(), getLiveOuts(), MI, llvm::MachineBasicBlock::predecessors(), and llvm::SmallPtrSetImplBase::size().
Referenced by getGlobalReachingDefs(), and getMIOperand().
hasLocalDefBefore()
bool ReachingDefAnalysis::hasLocalDefBefore (MachineInstr * MI, MCRegister PhysReg) const
Provide whether the register has been defined in the same basic block as, and before, MI.
Definition at line 326 of file ReachingDefAnalysis.cpp.
References getReachingDef(), and MI.
hasSameReachingDef()
bool ReachingDefAnalysis::hasSameReachingDef (MachineInstr * A, MachineInstr * B, MCRegister PhysReg) const
Return whether A and B use the same def of PhysReg.
Definition at line 291 of file ReachingDefAnalysis.cpp.
References B, and getReachingDef().
init()
void ReachingDefAnalysis::init ()
Initialize data structures.
Definition at line 236 of file ReachingDefAnalysis.cpp.
References llvm::MachineFunction::getNumBlockIDs(), llvm::MCRegisterInfo::getNumRegUnits(), llvm::SmallVectorImpl< T >::resize(), and llvm::LoopTraversal::traverse().
Referenced by reset(), and runOnMachineFunction().
isReachingDefLiveOut()
bool ReachingDefAnalysis::isReachingDefLiveOut (MachineInstr * MI, MCRegister PhysReg) const
Return whether the reaching def for MI also is live out of its parent block.
Definition at line 505 of file ReachingDefAnalysis.cpp.
References llvm::LivePhysRegs::addLiveOuts(), llvm::LivePhysRegs::available(), llvm::tgtok::Def, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineBasicBlock::getParent(), getReachingDef(), llvm::MachineFunction::getRegInfo(), isValidRegDefOf(), llvm::Last, MBB, and MI.
Referenced by getLiveInUses().
isRegDefinedAfter()
bool ReachingDefAnalysis::isRegDefinedAfter (MachineInstr * MI, MCRegister PhysReg) const
Return whether the given register is defined after MI.
Definition at line 491 of file ReachingDefAnalysis.cpp.
References llvm::tgtok::Def, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getLastNonDebugInstr(), getLocalLiveOutMIDef(), getReachingDef(), llvm::Last, MBB, and MI.
Referenced by isSafeToDefRegAt().
isRegUsedAfter()
bool ReachingDefAnalysis::isRegUsedAfter (MachineInstr * MI, MCRegister PhysReg) const
Return whether the given register is used after MI, whether it's a local use or a live out.
Definition at line 470 of file ReachingDefAnalysis.cpp.
References llvm::LivePhysRegs::addLiveOuts(), llvm::LivePhysRegs::available(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineBasicBlock::instr_rbegin(), llvm::MachineBasicBlock::instr_rend(), llvm::instructionsWithoutDebug(), llvm::Last, MBB, MI, and llvm::LivePhysRegs::stepBackward().
Referenced by isSafeToDefRegAt().
isSafeToDefRegAt() [1/2]
bool ReachingDefAnalysis::isSafeToDefRegAt (MachineInstr * MI, MCRegister PhysReg) const
Return whether a MachineInstr could be inserted at MI and safely define the given register without affecting the program.
Definition at line 681 of file ReachingDefAnalysis.cpp.
References Ignore, and MI.
isSafeToDefRegAt() [2/2]
bool ReachingDefAnalysis::isSafeToDefRegAt (MachineInstr * MI, MCRegister PhysReg, InstSet & Ignore) const
Return whether a MachineInstr could be inserted at MI and safely define the given register without affecting the program, ignoring any effects on the provided instructions.
Definition at line 687 of file ReachingDefAnalysis.cpp.
References llvm::tgtok::Def, E, llvm::MachineBasicBlock::end(), getGlobalUses(), I, Ignore, isRegDefinedAfter(), isRegUsedAfter(), isValidRegDefOf(), MBB, MI, llvm::set_is_subset(), and Uses.
isSafeToMoveBackwards()
bool ReachingDefAnalysis::isSafeToMoveBackwards (MachineInstr * From, MachineInstr * To) const
Return whether From can be moved backwards to just after To.
Definition at line 595 of file ReachingDefAnalysis.cpp.
References E, From, and I.
isSafeToMoveForwards()
bool ReachingDefAnalysis::isSafeToMoveForwards (MachineInstr * From, MachineInstr * To) const
Return whether From can be moved forwards to just before To.
Definition at line 585 of file ReachingDefAnalysis.cpp.
References E, From, and I.
isSafeToRemove() [1/2]
bool ReachingDefAnalysis::isSafeToRemove (MachineInstr * MI, InstSet & ToRemove) const
Return whether removing this instruction will have no effect on the program, returning the redundant use-def chain.
Definition at line 605 of file ReachingDefAnalysis.cpp.
References Ignore, MI, and ToRemove.
Referenced by isSafeToRemove().
isSafeToRemove() [2/2]
bool ReachingDefAnalysis::isSafeToRemove (MachineInstr * MI, InstSet & ToRemove, InstSet & Ignore) const
Return whether removing this instruction will have no effect on the program, ignoring the possible effects on some instructions, returning the redundant use-def chain.
Definition at line 613 of file ReachingDefAnalysis.cpp.
References Ignore, isSafeToRemove(), MI, and ToRemove.
releaseMemory()
void ReachingDefAnalysis::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 222 of file ReachingDefAnalysis.cpp.
References llvm::SmallVectorImpl< T >::clear().
Referenced by reset().
reset()
void ReachingDefAnalysis::reset ()
Re-run the analysis.
Definition at line 230 of file ReachingDefAnalysis.cpp.
References init(), releaseMemory(), and traverse().
runOnMachineFunction()
bool ReachingDefAnalysis::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 213 of file ReachingDefAnalysis.cpp.
References llvm::dbgs(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), init(), LLVM_DEBUG, and traverse().
traverse()
void ReachingDefAnalysis::traverse ()
Traverse the machine function, mapping definitions.
Definition at line 245 of file ReachingDefAnalysis.cpp.
References assert(), and llvm::tgtok::Def.
Referenced by reset(), and runOnMachineFunction().
Member Data Documentation
ID
char ReachingDefAnalysis::ID = 0 static
Definition at line 111 of file ReachingDefAnalysis.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ReachingDefAnalysis.h
lib/CodeGen/ReachingDefAnalysis.cpp