LLVM: llvm::mca::ResourceManager Class Reference
llvm::mca::ResourceManager Class Reference
A resource manager for processor resource units and groups.
#include "llvm/MCA/HardwareUnits/ResourceManager.h"
Public Member Functions
ResourceManager (const MCSchedModel &SM)
virtual ~ResourceManager ()=default
void setCustomStrategy (std::unique_ptr< ResourceStrategy > S, unsigned ResourceID)
ResourceStateEvent canBeDispatched (uint64_t ConsumedBuffers) const
unsigned resolveResourceMask (uint64_t Mask) const
void reserveBuffers (uint64_t ConsumedBuffers)
void releaseBuffers (uint64_t ConsumedBuffers)
void reserveResource (uint64_t ResourceID)
void releaseResource (uint64_t ResourceID)
uint64_t checkAvailability (const InstrDesc &Desc) const
uint64_t getProcResUnitMask () const
uint64_t getAvailableProcResUnits () const
void issueInstruction (const InstrDesc &Desc, SmallVectorImpl< std::pair< ResourceRef, ResourceCycles >> &Pipes)
void cycleEvent (SmallVectorImpl< ResourceRef > &ResourcesFreed)
void dump () const
Detailed Description
A resource manager for processor resource units and groups.
This class owns all the ResourceState objects, and it is responsible for acting on requests from a Scheduler by updating the internal state of ResourceState objects. This class doesn't know about instruction itineraries and functional units. In future, it can be extended to support itineraries too through the same public interface.
Definition at line 311 of file ResourceManager.h.
Constructor & Destructor Documentation
ResourceManager()
llvm::mca::ResourceManager::ResourceManager (const MCSchedModel & SM)
Definition at line 111 of file ResourceManager.cpp.
References llvm::mca::computeProcResourceMasks(), E, llvm::MCSchedModel::getNumProcResourceKinds(), llvm::MCSchedModel::getProcResource(), llvm::mca::getResourceStateIndex(), llvm::mca::getStrategyFor(), I, Index, llvm::mca::ResourceState::isAResourceGroup(), llvm::BitmaskEnumDetail::Mask(), and uint64_t.
~ResourceManager()
virtual llvm::mca::ResourceManager::~ResourceManager () virtual default
Member Function Documentation
canBeDispatched()
ResourceStateEvent llvm::mca::ResourceManager::canBeDispatched (uint64_t ConsumedBuffers) const
Definition at line 245 of file ResourceManager.cpp.
References llvm::mca::RS_BUFFER_AVAILABLE, llvm::mca::RS_BUFFER_UNAVAILABLE, and llvm::mca::RS_RESERVED.
checkAvailability()
uint64_t llvm::mca::ResourceManager::checkAvailability (const InstrDesc & Desc) const
Definition at line 282 of file ResourceManager.cpp.
References llvm::bit_floor(), E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::mca::ResourceState::getReadyMask(), llvm::mca::getResourceStateIndex(), llvm::mca::InstrDesc::HasPartiallyOverlappingGroups, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::mca::ResourceState::isAResourceGroup(), llvm::mca::ResourceState::isReady(), it, llvm::popcount(), llvm::mca::InstrDesc::Resources, uint64_t, and llvm::mca::InstrDesc::UsedProcResGroups.
cycleEvent()
void llvm::mca::ResourceManager::cycleEvent (SmallVectorImpl< ResourceRef > & ResourcesFreed)
Definition at line 374 of file ResourceManager.cpp.
References llvm::ISD::BR, llvm::SmallVectorImpl< T >::erase(), llvm::popcount(), and releaseResource().
Referenced by llvm::mca::InOrderIssueStage::cycleStart().
dump()
void llvm::mca::ResourceManager::dump () const inline
Definition at line 438 of file ResourceManager.h.
getAvailableProcResUnits()
uint64_t llvm::mca::ResourceManager::getAvailableProcResUnits () const inline
Definition at line 429 of file ResourceManager.h.
getProcResUnitMask()
uint64_t llvm::mca::ResourceManager::getProcResUnitMask () const inline
Definition at line 428 of file ResourceManager.h.
issueInstruction()
void llvm::mca::ResourceManager::issueInstruction (const InstrDesc & Desc, SmallVectorImpl< std::pair< ResourceRef, ResourceCycles >> & Pipes)
Definition at line 347 of file ResourceManager.cpp.
References assert(), llvm::mca::CycleSegment::begin(), llvm::popcount(), releaseResource(), reserveResource(), llvm::mca::InstrDesc::Resources, and llvm::mca::CycleSegment::size().
releaseBuffers()
void llvm::mca::ResourceManager::releaseBuffers (uint64_t ConsumedBuffers)
Definition at line 270 of file ResourceManager.cpp.
References llvm::mca::getResourceStateIndex(), and uint64_t.
releaseResource()
void llvm::mca::ResourceManager::releaseResource (uint64_t ResourceID)
Definition at line 402 of file ResourceManager.cpp.
References llvm::mca::ResourceState::clearReserved(), llvm::mca::getResourceStateIndex(), Index, llvm::mca::ResourceState::isADispatchHazard(), and llvm::mca::ResourceState::isAResourceGroup().
Referenced by cycleEvent(), and issueInstruction().
reserveBuffers()
void llvm::mca::ResourceManager::reserveBuffers (uint64_t ConsumedBuffers)
Definition at line 253 of file ResourceManager.cpp.
References assert(), llvm::mca::getResourceStateIndex(), llvm::mca::RS_BUFFER_AVAILABLE, and uint64_t.
reserveResource()
void llvm::mca::ResourceManager::reserveResource (uint64_t ResourceID)
Definition at line 393 of file ResourceManager.cpp.
References assert(), llvm::mca::getResourceStateIndex(), Index, llvm::mca::ResourceState::isAResourceGroup(), llvm::mca::ResourceState::isReserved(), and llvm::mca::ResourceState::setReserved().
Referenced by issueInstruction().
resolveResourceMask()
unsigned llvm::mca::ResourceManager::resolveResourceMask (uint64_t Mask) const
Definition at line 166 of file ResourceManager.cpp.
References llvm::mca::getResourceStateIndex(), and llvm::BitmaskEnumDetail::Mask().
setCustomStrategy()
void llvm::mca::ResourceManager::setCustomStrategy (std::unique_ptr< ResourceStrategy > S, unsigned ResourceID) inline
Definition at line 391 of file ResourceManager.h.
References assert(), move, and S.
The documentation for this class was generated from the following files:
include/llvm/MCA/HardwareUnits/ResourceManager.h
lib/MCA/HardwareUnits/ResourceManager.cpp