LLVM: llvm::AMDGPU::IsaInfo::AMDGPUTargetID Class Reference
llvm::AMDGPU::IsaInfo::AMDGPUTargetID Class Reference
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Member Functions
AMDGPUTargetID (const MCSubtargetInfo &STI)
~AMDGPUTargetID ()=default
bool isXnackSupported () const
bool isXnackOnOrAny () const
bool isXnackOnOrOff () const
TargetIDSetting getXnackSetting () const
void setCodeObjectVersion (unsigned COV)
void setXnackSetting (TargetIDSetting NewXnackSetting)
Sets xnack setting to NewXnackSetting.
bool isSramEccSupported () const
bool isSramEccOnOrAny () const
bool isSramEccOnOrOff () const
TargetIDSetting getSramEccSetting () const
void setSramEccSetting (TargetIDSetting NewSramEccSetting)
Sets sramecc setting to NewSramEccSetting.
void setTargetIDFromFeaturesString (StringRef FS)
void setTargetIDFromTargetIDStream (StringRef TargetID)
std::string toString () const
Detailed Description
Definition at line 126 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
AMDGPUTargetID()
llvm::AMDGPU::IsaInfo::AMDGPUTargetID::AMDGPUTargetID (const MCSubtargetInfo & STI) explicit
Definition at line 631 of file AMDGPUBaseInfo.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), llvm::FeatureBitset::test(), and llvm::AMDGPU::IsaInfo::Unsupported.
~AMDGPUTargetID()
llvm::AMDGPU::IsaInfo::AMDGPUTargetID::~AMDGPUTargetID () default
Member Function Documentation
getSramEccSetting()
TargetIDSetting llvm::AMDGPU::IsaInfo::AMDGPUTargetID::getSramEccSetting () const inline
Returns
The current sramecc TargetIDSetting, possible options are "Unsupported", "Any", "Off", and "On".
Definition at line 190 of file AMDGPUBaseInfo.h.
Referenced by llvm::GCNSubtarget::initializeSubtargetDependencies(), isSramEccOnOrOff(), and toString().
getXnackSetting()
TargetIDSetting llvm::AMDGPU::IsaInfo::AMDGPUTargetID::getXnackSetting () const inline
Returns
The current xnack TargetIDSetting, possible options are "Unsupported", "Any", "Off", and "On".
Definition at line 157 of file AMDGPUBaseInfo.h.
Referenced by llvm::GCNSubtarget::initializeSubtargetDependencies(), isXnackOnOrOff(), and toString().
isSramEccOnOrAny()
bool llvm::AMDGPU::IsaInfo::AMDGPUTargetID::isSramEccOnOrAny () const inline
Returns
True if the current sramecc setting is "On" or "Any".
Definition at line 176 of file AMDGPUBaseInfo.h.
References llvm::AMDGPU::IsaInfo::Any, and llvm::AMDGPU::IsaInfo::On.
Referenced by llvm::GCNSubtarget::d16PreservesUnusedBits(), and toString().
isSramEccOnOrOff()
bool llvm::AMDGPU::IsaInfo::AMDGPUTargetID::isSramEccOnOrOff () const inline
Returns
True if current sramecc setting is "On" or "Off", false otherwise.
Definition at line 183 of file AMDGPUBaseInfo.h.
References getSramEccSetting(), llvm::AMDGPU::IsaInfo::Off, and llvm::AMDGPU::IsaInfo::On.
isSramEccSupported()
bool llvm::AMDGPU::IsaInfo::AMDGPUTargetID::isSramEccSupported () const inline
Returns
True if the current sramecc setting is not "Unsupported".
Definition at line 171 of file AMDGPUBaseInfo.h.
References llvm::AMDGPU::IsaInfo::Unsupported.
Referenced by setTargetIDFromFeaturesString().
isXnackOnOrAny()
bool llvm::AMDGPU::IsaInfo::AMDGPUTargetID::isXnackOnOrAny () const inline
Returns
True if the current xnack setting is "On" or "Any".
Definition at line 143 of file AMDGPUBaseInfo.h.
References llvm::AMDGPU::IsaInfo::Any, and llvm::AMDGPU::IsaInfo::On.
Referenced by llvm::GCNSubtarget::isXNACKEnabled(), and toString().
isXnackOnOrOff()
bool llvm::AMDGPU::IsaInfo::AMDGPUTargetID::isXnackOnOrOff () const inline
Returns
True if current xnack setting is "On" or "Off", false otherwise.
Definition at line 150 of file AMDGPUBaseInfo.h.
References getXnackSetting(), llvm::AMDGPU::IsaInfo::Off, and llvm::AMDGPU::IsaInfo::On.
isXnackSupported()
bool llvm::AMDGPU::IsaInfo::AMDGPUTargetID::isXnackSupported () const inline
Returns
True if the current xnack setting is not "Unsupported".
Definition at line 138 of file AMDGPUBaseInfo.h.
References llvm::AMDGPU::IsaInfo::Unsupported.
Referenced by setTargetIDFromFeaturesString().
setCodeObjectVersion()
void llvm::AMDGPU::IsaInfo::AMDGPUTargetID::setCodeObjectVersion (unsigned COV) inline
Definition at line 161 of file AMDGPUBaseInfo.h.
setSramEccSetting()
void llvm::AMDGPU::IsaInfo::AMDGPUTargetID::setSramEccSetting (TargetIDSetting NewSramEccSetting) inline
Sets sramecc setting to NewSramEccSetting.
Definition at line 195 of file AMDGPUBaseInfo.h.
setTargetIDFromFeaturesString()
void llvm::AMDGPU::IsaInfo::AMDGPUTargetID::setTargetIDFromFeaturesString (StringRef FS)
Definition at line 640 of file AMDGPUBaseInfo.cpp.
References llvm::errs(), llvm::X86AS::FS, llvm::SubtargetFeatures::getFeatures(), isSramEccSupported(), isXnackSupported(), llvm::AMDGPU::IsaInfo::Off, and llvm::AMDGPU::IsaInfo::On.
Referenced by llvm::GCNSubtarget::initializeSubtargetDependencies().
setTargetIDFromTargetIDStream()
void llvm::AMDGPU::IsaInfo::AMDGPUTargetID::setTargetIDFromTargetIDStream (StringRef TargetID)
Definition at line 708 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::IsaInfo::getTargetIDSettingFromFeatureString(), and llvm::StringRef::split().
setXnackSetting()
void llvm::AMDGPU::IsaInfo::AMDGPUTargetID::setXnackSetting (TargetIDSetting NewXnackSetting) inline
Sets xnack setting to NewXnackSetting.
Definition at line 166 of file AMDGPUBaseInfo.h.
toString()
std::string llvm::AMDGPU::IsaInfo::AMDGPUTargetID::toString () const
Returns
String representation of an object.
Definition at line 720 of file AMDGPUBaseInfo.cpp.
References llvm::Triple::AMDHSA, llvm::AMDGPU::AMDHSA_COV2, llvm::AMDGPU::AMDHSA_COV3, llvm::AMDGPU::AMDHSA_COV4, llvm::AMDGPU::AMDHSA_COV5, llvm::raw_ostream::flush(), llvm::MCSubtargetInfo::getCPU(), llvm::AMDGPU::getIsaVersion(), llvm::Triple::getOS(), getSramEccSetting(), llvm::MCSubtargetInfo::getTargetTriple(), getXnackSetting(), isSramEccOnOrAny(), isXnackOnOrAny(), llvm::AMDGPU::IsaInfo::Off, llvm::AMDGPU::IsaInfo::On, llvm::report_fatal_error(), llvm::StringRef::str(), and llvm::IndexedInstrProf::Version.
Referenced by llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitTargetID().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp