LLVM: NewPMDebugifyPass Class Reference
NewPMDebugifyPass Class Reference
#include "llvm/Transforms/Utils/Debugify.h"
Public Member Functions
NewPMDebugifyPass (enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass="", DebugInfoPerPass *DebugInfoBeforePass=nullptr)
llvm::PreservedAnalyses run (llvm::Module &M, llvm::ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< NewPMDebugifyPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< NewPMDebugifyPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 104 of file Debugify.h.
Constructor & Destructor Documentation
NewPMDebugifyPass()
NewPMDebugifyPass::NewPMDebugifyPass (enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, llvm::StringRef NameOfWrappedPass = "", DebugInfoPerPass * DebugInfoBeforePass = nullptr) inline
Definition at line 109 of file Debugify.h.
Member Function Documentation
run()
PreservedAnalyses NewPMDebugifyPass::run (llvm::Module & M, llvm::ModuleAnalysisManager & AM)
Definition at line 974 of file Debugify.cpp.
References llvm::PreservedAnalyses::all(), llvm::applyDebugifyMetadata(), llvm::collectDebugInfoMetadata(), M, Mode, and SyntheticDebugInfo.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/Debugify.h
lib/Transforms/Utils/Debugify.cpp