LLVM: llvm::SparcTargetAsmStreamer Class Reference
llvm::SparcTargetAsmStreamer Class Reference
#include "Target/Sparc/MCTargetDesc/SparcTargetStreamer.h"
Public Member Functions
SparcTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS)
void emitSparcRegisterIgnore (unsigned reg) override
Emit ".register <reg>, #ignore".
void emitSparcRegisterScratch (unsigned reg) override
Emit ".register <reg>, #scratch".
Public Member Functions inherited from llvm::SparcTargetStreamer
SparcTargetStreamer (MCStreamer &S)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 31 of file SparcTargetStreamer.h.
Constructor & Destructor Documentation
SparcTargetAsmStreamer()
SparcTargetAsmStreamer::SparcTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS)
Definition at line 25 of file SparcTargetStreamer.cpp.
Member Function Documentation
emitSparcRegisterIgnore()
void SparcTargetAsmStreamer::emitSparcRegisterIgnore (unsigned reg) override virtual
Emit ".register <reg>, #ignore".
Reimplemented from llvm::SparcTargetStreamer.
Definition at line 29 of file SparcTargetStreamer.cpp.
References llvm::SparcInstPrinter::getRegisterName(), llvm::StringRef::lower(), and OS.
emitSparcRegisterScratch()
void SparcTargetAsmStreamer::emitSparcRegisterScratch (unsigned reg) override virtual
Emit ".register <reg>, #scratch".
Reimplemented from llvm::SparcTargetStreamer.
Definition at line 35 of file SparcTargetStreamer.cpp.
References llvm::SparcInstPrinter::getRegisterName(), llvm::StringRef::lower(), and OS.
The documentation for this class was generated from the following files:
lib/Target/Sparc/MCTargetDesc/SparcTargetStreamer.h
lib/Target/Sparc/MCTargetDesc/SparcTargetStreamer.cpp