LLVM: llvm::NVPTXInstPrinter Class Reference
llvm::NVPTXInstPrinter Class Reference
#include "Target/NVPTX/MCTargetDesc/NVPTXInstPrinter.h"
Public Member Functions
NVPTXInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printRegName (raw_ostream &OS, MCRegister Reg) const override
Print the assembler register name.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &OS) override
Print the specified MCInst to the specified raw_ostream.
std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI) override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printCvtMode (const MCInst *MI, int OpNum, raw_ostream &O, const char *Modifier=nullptr)
void printCmpMode (const MCInst *MI, int OpNum, raw_ostream &O, const char *Modifier=nullptr)
void printLdStCode (const MCInst *MI, int OpNum, raw_ostream &O, const char *Modifier=nullptr)
void printMmaCode (const MCInst *MI, int OpNum, raw_ostream &O, const char *Modifier=nullptr)
void printMemOperand (const MCInst *MI, int OpNum, raw_ostream &O, const char *Modifier=nullptr)
void printProtoIdent (const MCInst *MI, int OpNum, raw_ostream &O, const char *Modifier=nullptr)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
Detailed Description
Definition at line 22 of file NVPTXInstPrinter.h.
Constructor & Destructor Documentation
NVPTXInstPrinter()
NVPTXInstPrinter::NVPTXInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI)
Definition at line 30 of file NVPTXInstPrinter.cpp.
Member Function Documentation
getMnemonic()
std::pair<const char *, uint64_t> llvm::NVPTXInstPrinter::getMnemonic (const MCInst * MI) override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
getRegisterName()
static const char* llvm::NVPTXInstPrinter::getRegisterName (MCRegister Reg) static
Referenced by printRegName().
printCmpMode()
void NVPTXInstPrinter::printCmpMode (const MCInst * MI, int OpNum, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 155 of file NVPTXInstPrinter.cpp.
References llvm::NVPTX::PTXCmpMode::BASE_MASK, llvm::NVPTX::PTXCmpMode::EQ, llvm::NVPTX::PTXCmpMode::EQU, llvm::NVPTX::PTXCmpMode::FTZ_FLAG, llvm::NVPTX::PTXCmpMode::GE, llvm::MCOperand::getImm(), llvm::NVPTX::PTXCmpMode::GEU, llvm::NVPTX::PTXCmpMode::GT, llvm::NVPTX::PTXCmpMode::GTU, llvm::NVPTX::PTXCmpMode::HI, llvm::NVPTX::PTXCmpMode::HS, llvm::RISCVMatInt::Imm, llvm::NVPTX::PTXCmpMode::LE, llvm::NVPTX::PTXCmpMode::LEU, llvm_unreachable, llvm::NVPTX::PTXCmpMode::LO, llvm::NVPTX::PTXCmpMode::LS, llvm::NVPTX::PTXCmpMode::LT, llvm::NVPTX::PTXCmpMode::LTU, MI, llvm::NVPTX::PTXCmpMode::NE, llvm::NVPTX::PTXCmpMode::NEU, llvm::NVPTX::PTXCmpMode::NotANumber, llvm::NVPTX::PTXCmpMode::NUM, and llvm::RISCVFenceField::O.
printCvtMode()
void NVPTXInstPrinter::printCvtMode (const MCInst * MI, int OpNum, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 98 of file NVPTXInstPrinter.cpp.
References llvm::NVPTX::PTXCvtMode::BASE_MASK, llvm::NVPTX::PTXCvtMode::FTZ_FLAG, llvm::MCOperand::getImm(), llvm::RISCVMatInt::Imm, llvm_unreachable, MI, llvm::NVPTX::PTXCvtMode::NONE, llvm::RISCVFenceField::O, llvm::NVPTX::PTXCvtMode::RELU_FLAG, llvm::NVPTX::PTXCvtMode::RM, llvm::NVPTX::PTXCvtMode::RMI, llvm::NVPTX::PTXCvtMode::RN, llvm::NVPTX::PTXCvtMode::RNA, llvm::NVPTX::PTXCvtMode::RNI, llvm::NVPTX::PTXCvtMode::RP, llvm::NVPTX::PTXCvtMode::RPI, llvm::NVPTX::PTXCvtMode::RZ, llvm::NVPTX::PTXCvtMode::RZI, and llvm::NVPTX::PTXCvtMode::SAT_FLAG.
printInst()
void NVPTXInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 75 of file NVPTXInstPrinter.cpp.
References MI, OS, llvm::MCInstPrinter::printAnnotation(), and printInstruction().
printInstruction()
void llvm::NVPTXInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
Referenced by printInst().
printLdStCode()
void NVPTXInstPrinter::printLdStCode (const MCInst * MI, int OpNum, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 228 of file NVPTXInstPrinter.cpp.
References llvm::NVPTX::PTXLdStInstCode::CONSTANT, llvm::NVPTX::PTXLdStInstCode::Float, llvm::NVPTX::PTXLdStInstCode::GENERIC, llvm::MCOperand::getImm(), llvm::NVPTX::PTXLdStInstCode::GLOBAL, llvm::RISCVMatInt::Imm, int, llvm_unreachable, llvm::NVPTX::PTXLdStInstCode::LOCAL, MI, llvm::RISCVFenceField::O, llvm::NVPTX::PTXLdStInstCode::PARAM, llvm::NVPTX::PTXLdStInstCode::SHARED, llvm::NVPTX::PTXLdStInstCode::Signed, llvm::NVPTX::PTXLdStInstCode::Unsigned, llvm::NVPTX::PTXLdStInstCode::Untyped, llvm::NVPTX::PTXLdStInstCode::V2, and llvm::NVPTX::PTXLdStInstCode::V4.
printMemOperand()
void NVPTXInstPrinter::printMemOperand (const MCInst * MI, int OpNum, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 294 of file NVPTXInstPrinter.cpp.
References MI, llvm::RISCVFenceField::O, and printOperand().
printMmaCode()
void NVPTXInstPrinter::printMmaCode (const MCInst * MI, int OpNum, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 280 of file NVPTXInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::RISCVMatInt::Imm, int, llvm_unreachable, MI, and llvm::RISCVFenceField::O.
printOperand()
void NVPTXInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 84 of file NVPTXInstPrinter.cpp.
References assert(), llvm::MCInstPrinter::formatImm(), llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::markup(), MI, llvm::RISCVFenceField::O, and printRegName().
Referenced by printMemOperand().
printProtoIdent()
void NVPTXInstPrinter::printProtoIdent (const MCInst * MI, int OpNum, raw_ostream & O, const char * Modifier = nullptr)
Definition at line 310 of file NVPTXInstPrinter.cpp.
References assert(), llvm::MCSymbol::getName(), MI, and llvm::RISCVFenceField::O.
printRegName()
void NVPTXInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 34 of file NVPTXInstPrinter.cpp.
References getRegisterName(), OS, and llvm::report_fatal_error().
Referenced by printOperand().
The documentation for this class was generated from the following files:
lib/Target/NVPTX/MCTargetDesc/NVPTXInstPrinter.h
lib/Target/NVPTX/MCTargetDesc/NVPTXInstPrinter.cpp