LLVM: AMDGPUPreLegalizerCombinerHelper Class Reference
AMDGPUPreLegalizerCombinerHelper Class Reference
Classes
struct ClampI64ToI16MatchInfo
Public Member Functions
AMDGPUPreLegalizerCombinerHelper (MachineIRBuilder &B, AMDGPUCombinerHelper &Helper)
bool matchClampI64ToI16 (MachineInstr &MI, MachineRegisterInfo &MRI, MachineFunction &MF, ClampI64ToI16MatchInfo &MatchInfo)
void applyClampI64ToI16 (MachineInstr &MI, const ClampI64ToI16MatchInfo &MatchInfo)
Protected Attributes
MachineIRBuilder & B
MachineFunction & MF
MachineRegisterInfo & MRI
AMDGPUCombinerHelper & Helper
Detailed Description
Definition at line 34 of file AMDGPUPreLegalizerCombiner.cpp.
Constructor & Destructor Documentation
AMDGPUPreLegalizerCombinerHelper()
AMDGPUPreLegalizerCombinerHelper::AMDGPUPreLegalizerCombinerHelper (MachineIRBuilder & B, AMDGPUCombinerHelper & Helper) inline
Definition at line 42 of file AMDGPUPreLegalizerCombiner.cpp.
Member Function Documentation
applyClampI64ToI16()
void AMDGPUPreLegalizerCombinerHelper::applyClampI64ToI16 (MachineInstr & MI, const ClampI64ToI16MatchInfo & MatchInfo)
Definition at line 121 of file AMDGPUPreLegalizerCombiner.cpp.
References assert(), B, llvm::LegacyLegalizeActions::Bitcast, AMDGPUPreLegalizerCombinerHelper::ClampI64ToI16MatchInfo::Cmp1, AMDGPUPreLegalizerCombinerHelper::ClampI64ToI16MatchInfo::Cmp2, llvm::LLT::fixed_vector(), llvm::max(), MI, llvm::min(), AMDGPUPreLegalizerCombinerHelper::ClampI64ToI16MatchInfo::Origin, and llvm::LLT::scalar().
matchClampI64ToI16()
bool AMDGPUPreLegalizerCombinerHelper::matchClampI64ToI16 (MachineInstr & MI, MachineRegisterInfo & MRI, MachineFunction & MF, ClampI64ToI16MatchInfo & MatchInfo)
Definition at line 60 of file AMDGPUPreLegalizerCombiner.cpp.
References llvm::abs(), assert(), llvm::sampleprof::Base, AMDGPUPreLegalizerCombinerHelper::ClampI64ToI16MatchInfo::Cmp1, AMDGPUPreLegalizerCombinerHelper::ClampI64ToI16MatchInfo::Cmp2, llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GSMax(), llvm::MIPatternMatch::m_GSMin(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), llvm::max(), MI, llvm::MIPatternMatch::mi_match(), llvm::min(), MRI, AMDGPUPreLegalizerCombinerHelper::ClampI64ToI16MatchInfo::Origin, and llvm::LLT::scalar().
Member Data Documentation
B
MachineIRBuilder& AMDGPUPreLegalizerCombinerHelper::B protected
Definition at line 36 of file AMDGPUPreLegalizerCombiner.cpp.
Helper
AMDGPUCombinerHelper& AMDGPUPreLegalizerCombinerHelper::Helper protected
Definition at line 39 of file AMDGPUPreLegalizerCombiner.cpp.
MF
MachineFunction& AMDGPUPreLegalizerCombinerHelper::MF protected
Definition at line 37 of file AMDGPUPreLegalizerCombiner.cpp.
MRI
MachineRegisterInfo& AMDGPUPreLegalizerCombinerHelper::MRI protected
Definition at line 38 of file AMDGPUPreLegalizerCombiner.cpp.
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/AMDGPUPreLegalizerCombiner.cpp