LLVM: llvm::LoopSinkPass Class Reference
llvm::LoopSinkPass Class Reference
A pass that does profile-guided sinking of instructions into loops.
#include "llvm/Transforms/Scalar/LoopSink.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Public Member Functions inherited from llvm::PassInfoMixin< LoopSinkPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopSinkPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A pass that does profile-guided sinking of instructions into loops.
This is a function pass as it shouldn't be composed into any kind of unified loop pass pipeline. The goal of it is to sink code into loops that is loop invariant but only required within the loop body when doing so reduces the global expected dynamic frequency with which it executes. A classic example is an extremely cold branch within a loop body.
We do this as a separate pass so that during normal optimization all invariant operations can be held outside the loop body to simplify fundamental analyses and transforms of the loop.
Definition at line 33 of file LoopSink.h.
Member Function Documentation
run()
PreservedAnalyses LoopSinkPass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 325 of file LoopSink.cpp.
References llvm::PreservedAnalyses::all(), llvm::AMDGPUISD::BFI, llvm::LoopInfoBase< BlockT, LoopT >::empty(), F, FAM, llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInPreorder(), llvm::BasicBlock::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::Function::hasProfileData(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::PreservedAnalyses::preserve(), llvm::PreservedAnalyses::preserveSet(), sinkLoopInvariantInstructions(), and llvm::VerifyMemorySSA.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopSink.h
lib/Transforms/Scalar/LoopSink.cpp