LLVM: llvm::logicalview::LVSymbol Class Reference
llvm::logicalview::LVSymbol Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVSymbol.h"
Public Member Functions
LVSymbol ()
LVSymbol (const LVSymbol &)=delete
LVSymbol & operator= (const LVSymbol &)=delete
~LVSymbol ()=default
KIND (LVSymbolKind, IsCallSiteParameter)
KIND (LVSymbolKind, IsConstant)
KIND (LVSymbolKind, IsInheritance)
KIND (LVSymbolKind, IsMember)
KIND (LVSymbolKind, IsParameter)
KIND (LVSymbolKind, IsUnspecified)
KIND (LVSymbolKind, IsVariable)
PROPERTY (Property, HasLocation)
PROPERTY (Property, FillGaps)
const char * kind () const override
LVSymbol * getReference () const
void setReference (LVSymbol *Symbol) override
void setReference (LVElement *Element) override
void setLinkageName (StringRef LinkageName) override
StringRef getLinkageName () const override
size_t getLinkageNameIndex () const override
uint32_t getBitSize () const override
void setBitSize (uint32_t Size) override
std::string getValue () const override
void setValue (StringRef Value) override
size_t getValueIndex () const override
void addLocationConstant (dwarf::Attribute Attr, LVUnsigned Constant, uint64_t LocDescOffset)
void addLocationOperands (LVSmall Opcode, uint64_t Operand1, uint64_t Operand2)
void addLocation (dwarf::Attribute Attr, LVAddress LowPC, LVAddress HighPC, LVUnsigned SectionOffset, uint64_t LocDescOffset, bool CallSiteLocation=false)
void fillLocationGaps ()
void getLocations (LVLocations &LocationList, LVValidLocation ValidLocation, bool RecordInvalid=false)
void getLocations (LVLocations &LocationList) const
void calculateCoverage ()
unsigned getCoverageFactor () const
void setCoverageFactor (unsigned Value)
float getCoveragePercentage () const
void setCoveragePercentage (float Value)
void printLocations (raw_ostream &OS, bool Full=true) const
StringRef resolveReferencesChain ()
void resolveName () override
void resolveReferences () override
bool equals (const LVSymbol *Symbol) const
void report (LVComparePass Pass) override
void print (raw_ostream &OS, bool Full=true) const override
void printExtra (raw_ostream &OS, bool Full=true) const override
void dump () const override
Public Member Functions inherited from llvm::logicalview::LVElement
LVElement (LVSubclassID ID)
LVElement (const LVElement &)=delete
LVElement & operator= (const LVElement &)=delete
virtual ~LVElement ()=default
LVSubclassID getSubclassID () const
PROPERTY (Property, IsLine)
PROPERTY (Property, IsScope)
PROPERTY (Property, IsSymbol)
PROPERTY (Property, IsType)
PROPERTY (Property, IsEnumClass)
PROPERTY (Property, IsExternal)
PROPERTY (Property, HasType)
PROPERTY (Property, HasAugmentedName)
PROPERTY (Property, IsTypedefReduced)
PROPERTY (Property, IsArrayResolved)
PROPERTY (Property, IsMemberPointerResolved)
PROPERTY (Property, IsTemplateResolved)
PROPERTY (Property, IsInlined)
PROPERTY (Property, IsInlinedAbstract)
PROPERTY (Property, InvalidFilename)
PROPERTY (Property, HasReference)
PROPERTY (Property, HasReferenceAbstract)
PROPERTY (Property, HasReferenceExtension)
PROPERTY (Property, HasReferenceSpecification)
PROPERTY (Property, QualifiedResolved)
PROPERTY (Property, IncludeInPrint)
PROPERTY (Property, IsStatic)
PROPERTY (Property, TransformName)
PROPERTY (Property, IsScoped)
PROPERTY (Property, IsNested)
PROPERTY (Property, IsScopedAlready)
PROPERTY (Property, IsArtificial)
PROPERTY (Property, IsReferencedType)
PROPERTY (Property, IsSystem)
PROPERTY (Property, OffsetFromTypeIndex)
PROPERTY (Property, IsAnonymous)
bool isNamed () const override
bool isTyped () const override
bool isFiled () const override
bool getIsKindType () const
bool getIsKindScope () const
StringRef getName () const override
void setName (StringRef ElementName) override
StringRef getPathname () const
void setFilename (StringRef Filename)
void setQualifiedName (StringRef Name)
StringRef getQualifiedName () const
size_t getNameIndex () const
size_t getQualifiedNameIndex () const
StringRef getTypeName () const
virtual StringRef getProducer () const
virtual void setProducer (StringRef ProducerName)
virtual bool isCompileUnit () const
virtual bool isRoot () const
virtual void setReference (LVScope *Scope)
virtual void setReference (LVType *Type)
virtual uint32_t getCallLineNumber () const
virtual void setCallLineNumber (uint32_t Number)
virtual size_t getCallFilenameIndex () const
virtual void setCallFilenameIndex (size_t Index)
size_t getFilenameIndex () const
void setFilenameIndex (size_t Index)
void setFile (LVElement *Reference=nullptr)
virtual bool isBase () const
virtual bool isTemplateParam () const
virtual int64_t getCount () const
virtual void setCount (int64_t Value)
virtual int64_t getLowerBound () const
virtual void setLowerBound (int64_t Value)
virtual int64_t getUpperBound () const
virtual void setUpperBound (int64_t Value)
virtual std::pair< unsigned, unsigned > getBounds () const
virtual void setBounds (unsigned Lower, unsigned Upper)
virtual uint32_t getDiscriminator () const
virtual void setDiscriminator (uint32_t Value)
uint32_t getAccessibilityCode () const
void setAccessibilityCode (uint32_t Access)
StringRef accessibilityString (uint32_t Access=dwarf::DW_ACCESS_private) const
uint32_t getInlineCode () const
void setInlineCode (uint32_t Code)
StringRef inlineCodeString (uint32_t Code) const
uint32_t getVirtualityCode () const
void setVirtualityCode (uint32_t Virtuality)
StringRef virtualityString (uint32_t Virtuality=dwarf::DW_VIRTUALITY_none) const
StringRef externalString () const
LVElement * getType () const
LVType * getTypeAsType () const
LVScope * getTypeAsScope () const
void setType (LVElement *Element=nullptr)
void setGenericType (LVElement *Element)
StringRef getTypeQualifiedName () const
StringRef typeAsString () const
std::string typeOffsetAsString () const
std::string discriminatorAsString () const
LVScope * traverseParents (LVScopeGetFunction GetFunction) const
LVScope * getFunctionParent () const
virtual LVScope * getCompileUnitParent () const
void printReference (raw_ostream &OS, bool Full, LVElement *Parent) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent, LVScope *Scope) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent) const
void resolveFullname (LVElement *BaseType, StringRef Name=emptyString())
void generateName (std::string &Prefix) const
void generateName ()
virtual bool removeElement (LVElement *Element)
virtual void updateLevel (LVScope *Parent, bool Moved=false)
virtual void resolve ()
virtual void resolveExtra ()
void resolveParents ()
bool referenceMatch (const LVElement *Element) const
bool equals (const LVElement *Element) const
Public Member Functions inherited from llvm::logicalview::LVObject
LVObject ()
LVObject & operator= (const LVObject &)=delete
virtual ~LVObject ()=default
PROPERTY (Property, IsLocation)
PROPERTY (Property, IsGlobalReference)
PROPERTY (Property, IsGeneratedName)
PROPERTY (Property, IsResolved)
PROPERTY (Property, IsResolvedName)
PROPERTY (Property, IsDiscarded)
PROPERTY (Property, IsOptimized)
PROPERTY (Property, IsAdded)
PROPERTY (Property, IsMatched)
PROPERTY (Property, IsMissing)
PROPERTY (Property, IsMissingLink)
PROPERTY (Property, IsInCompare)
PROPERTY (Property, IsFileFromReference)
PROPERTY (Property, IsLineFromReference)
PROPERTY (Property, HasMoved)
PROPERTY (Property, HasPattern)
PROPERTY (Property, IsFinalized)
PROPERTY (Property, IsReferenced)
PROPERTY (Property, HasCodeViewLocation)
bool isLined () const
dwarf::Tag getTag () const
void setTag (dwarf::Tag Tag)
dwarf::Attribute getAttr () const
void setAttr (dwarf::Attribute Attr)
LVSmall getOpcode () const
void setOpcode (LVSmall Opcode)
LVOffset getOffset () const
void setOffset (LVOffset DieOffset)
LVLevel getLevel () const
void setLevel (LVLevel Level)
LVElement * getParent () const
LVScope * getParentScope () const
LVSymbol * getParentSymbol () const
void setParent (LVScope *Scope)
void setParent (LVSymbol *Symbol)
void resetParent ()
virtual LVAddress getLowerAddress () const
virtual void setLowerAddress (LVAddress Address)
virtual LVAddress getUpperAddress () const
virtual void setUpperAddress (LVAddress Address)
uint32_t getLineNumber () const
void setLineNumber (uint32_t Number)
std::string indentAsString () const
std::string indentAsString (LVLevel Level) const
virtual std::string noLineAsString (bool ShowZero) const
virtual std::string lineNumberAsString (bool ShowZero=false) const
std::string lineNumberAsStringStripped (bool ShowZero=false) const
virtual Error doPrint (bool Split, bool Match, bool Print, raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full, StringRef Name, LVObject *Parent, StringRef Value, bool UseQuotes=false, bool PrintRef=false) const
void markBranchAsMissing ()
uint64_t getID () const
Static Public Member Functions
static bool classof (const LVElement *Element)
static LVSymbolDispatch & getDispatch ()
static bool parametersMatch (const LVSymbols *References, const LVSymbols *Targets)
static void getParameters (const LVSymbols *Symbols, LVSymbols *Parameters)
static void markMissingParents (const LVSymbols *References, const LVSymbols *Targets)
static bool equals (const LVSymbols *References, const LVSymbols *Targets)
Static Public Member Functions inherited from llvm::logicalview::LVElement
static LVElementDispatch & getDispatch ()
Additional Inherited Members
Protected Member Functions inherited from llvm::logicalview::LVElement
void printFileIndex (raw_ostream &OS, bool Full=true) const override
Protected Member Functions inherited from llvm::logicalview::LVObject
std::string lineAsString (uint32_t LineNumber, LVHalf Discriminator, bool ShowZero) const
std::string referenceAsString (uint32_t LineNumber, bool Spaces) const
Protected Attributes inherited from llvm::logicalview::LVElement
LVElement * ElementType = nullptr
Detailed Description
Definition at line 36 of file LVSymbol.h.
Constructor & Destructor Documentation
LVSymbol() [1/2]
llvm::logicalview::LVSymbol::LVSymbol () inline
Definition at line 70 of file LVSymbol.h.
References llvm::logicalview::LV_SYMBOL.
LVSymbol() [2/2]
llvm::logicalview::LVSymbol::LVSymbol (const LVSymbol &) delete
~LVSymbol()
llvm::logicalview::LVSymbol::~LVSymbol () default
Member Function Documentation
addLocation()
void LVSymbol::addLocation (dwarf::Attribute Attr, LVAddress LowPC, LVAddress HighPC, LVUnsigned SectionOffset, uint64_t LocDescOffset, bool CallSiteLocation = false)
Definition at line 65 of file LVSymbol.cpp.
References llvm::logicalview::LVLocation::addObject(), llvm::logicalview::LVObject::Attr, llvm::logicalview::getReader(), llvm::logicalview::LVObject::setAttr(), and llvm::logicalview::LVObject::setParent().
Referenced by addLocationConstant().
addLocationConstant()
void LVSymbol::addLocationConstant (dwarf::Attribute Attr, LVUnsigned Constant, uint64_t LocDescOffset)
Definition at line 92 of file LVSymbol.cpp.
References addLocation(), addLocationOperands(), llvm::logicalview::LVObject::Attr, and llvm::logicalview::LVLocationMemberOffset.
addLocationOperands()
void LVSymbol::addLocationOperands (LVSmall Opcode, uint64_t Operand1, uint64_t Operand2)
Definition at line 85 of file LVSymbol.cpp.
References llvm::logicalview::LVLocation::addObject(), and llvm::logicalview::LVObject::Opcode.
Referenced by addLocationConstant().
calculateCoverage()
void LVSymbol::calculateCoverage ()
Definition at line 192 of file LVSymbol.cpp.
References llvm::logicalview::LVScopeCompileUnit::addInvalidCoverage(), llvm::logicalview::LVLocation::calculateCoverage(), llvm::logicalview::LVScope::getCoverageFactor(), llvm::logicalview::LVObject::getParentScope(), llvm::logicalview::getReaderCompileUnit(), llvm::logicalview::options(), llvm::logicalview::LVScope::outermostParent(), and llvm::logicalview::LVObject::Scope.
Referenced by getLocations().
classof()
static bool llvm::logicalview::LVSymbol::classof (const LVElement * Element) inline static
Definition at line 78 of file LVSymbol.h.
References llvm::logicalview::LVObject::Element, llvm::logicalview::LVElement::getSubclassID(), and llvm::logicalview::LV_SYMBOL.
dump()
void llvm::logicalview::LVSymbol::dump () const inline override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 188 of file LVSymbol.h.
References llvm::dbgs(), and print().
equals() [1/2]
bool LVSymbol::equals (const LVSymbol * Symbol) const
Definition at line 357 of file LVSymbol.cpp.
References llvm::logicalview::LVElement::equals(), getReference(), llvm::logicalview::LVElement::referenceMatch(), and llvm::logicalview::LVObject::Symbol.
Referenced by parametersMatch().
equals() [2/2]
bool LVSymbol::equals (const LVSymbols * References, const LVSymbols * Targets) static
Definition at line 371 of file LVSymbol.cpp.
fillLocationGaps()
void LVSymbol::fillLocationGaps ()
Definition at line 127 of file LVSymbol.cpp.
References llvm::logicalview::LVObject::getParentScope(), llvm::logicalview::LVScope::getRanges(), and llvm::logicalview::Ranges.
getBitSize()
uint32_t llvm::logicalview::LVSymbol::getBitSize () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 114 of file LVSymbol.h.
Referenced by printExtra().
getCoverageFactor()
unsigned llvm::logicalview::LVSymbol::getCoverageFactor () const inline
Definition at line 146 of file LVSymbol.h.
Referenced by llvm::logicalview::LVLocation::print().
getCoveragePercentage()
float llvm::logicalview::LVSymbol::getCoveragePercentage () const inline
Definition at line 148 of file LVSymbol.h.
Referenced by llvm::logicalview::LVLocation::print().
getDispatch()
static LVSymbolDispatch& llvm::logicalview::LVSymbol::getDispatch () inline static
Definition at line 161 of file LVSymbol.h.
Referenced by llvm::logicalview::LVPatterns::LVPatterns().
getLinkageName()
StringRef llvm::logicalview::LVSymbol::getLinkageName () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 109 of file LVSymbol.h.
References llvm::logicalview::LVStringPool::getString(), and llvm::logicalview::getStringPool().
getLinkageNameIndex()
size_t llvm::logicalview::LVSymbol::getLinkageNameIndex () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 112 of file LVSymbol.h.
Referenced by printExtra().
getLocations() [1/2]
void LVSymbol::getLocations (LVLocations & LocationList) const
Definition at line 183 of file LVSymbol.cpp.
References llvm::logicalview::Location.
getLocations() [2/2]
void LVSymbol::getLocations (LVLocations & LocationList, LVValidLocation ValidLocation, bool RecordInvalid = false)
Definition at line 168 of file LVSymbol.cpp.
References calculateCoverage(), and llvm::logicalview::Location.
Referenced by llvm::logicalview::LVScope::getLocations().
getParameters()
void LVSymbol::getParameters (const LVSymbols * Symbols, LVSymbols * Parameters) static
Definition at line 350 of file LVSymbol.cpp.
References llvm::logicalview::LVObject::Symbol.
Referenced by parametersMatch().
getReference()
LVSymbol* llvm::logicalview::LVSymbol::getReference () const inline
Definition at line 96 of file LVSymbol.h.
References llvm::logicalview::Reference.
Referenced by llvm::logicalview::LVScope::addMissingElements(), equals(), printExtra(), resolveReferences(), and resolveReferencesChain().
getValue()
std::string llvm::logicalview::LVSymbol::getValue () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 118 of file LVSymbol.h.
References llvm::logicalview::getStringPool().
Referenced by printExtra().
getValueIndex()
size_t llvm::logicalview::LVSymbol::getValueIndex () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 124 of file LVSymbol.h.
kind()
const char * LVSymbol::kind () const override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 36 of file LVSymbol.cpp.
Referenced by markMissingParents(), and printExtra().
KIND() [1/7]
llvm::logicalview::LVSymbol::KIND (LVSymbolKind , IsCallSiteParameter)
KIND() [2/7]
llvm::logicalview::LVSymbol::KIND (LVSymbolKind , IsConstant)
KIND() [3/7]
llvm::logicalview::LVSymbol::KIND (LVSymbolKind , IsInheritance)
KIND() [4/7]
llvm::logicalview::LVSymbol::KIND (LVSymbolKind , IsMember)
KIND() [5/7]
llvm::logicalview::LVSymbol::KIND (LVSymbolKind , IsParameter)
KIND() [6/7]
llvm::logicalview::LVSymbol::KIND (LVSymbolKind , IsUnspecified)
KIND() [7/7]
llvm::logicalview::LVSymbol::KIND (LVSymbolKind , IsVariable)
markMissingParents()
void LVSymbol::markMissingParents (const LVSymbols * References, const LVSymbols * Targets) static
Definition at line 283 of file LVSymbol.cpp.
References llvm::dbgs(), llvm::logicalview::formattedKind(), llvm::logicalview::formattedName(), llvm::logicalview::LVElement::getName(), llvm::Target::getName(), kind(), LLVM_DEBUG, and llvm::logicalview::LVObject::markBranchAsMissing().
operator=()
LVSymbol& llvm::logicalview::LVSymbol::operator= (const LVSymbol &) delete
parametersMatch()
bool LVSymbol::parametersMatch (const LVSymbols * References, const LVSymbols * Targets) static
Definition at line 335 of file LVSymbol.cpp.
References equals(), and getParameters().
Referenced by llvm::logicalview::LVScopeFunction::equals().
print()
void LVSymbol::print (raw_ostream & OS, bool Full = true) const override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 393 of file LVSymbol.cpp.
References llvm::logicalview::getReader(), llvm::logicalview::getReaderCompileUnit(), llvm::logicalview::LVScopeCompileUnit::incrementPrintedSymbols(), OS, llvm::logicalview::LVObject::print(), and printExtra().
Referenced by dump().
printExtra()
void LVSymbol::printExtra (raw_ostream & OS, bool Full = true) const override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 401 of file LVSymbol.cpp.
References llvm::logicalview::LVElement::accessibilityString(), Attributes, llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_public, llvm::logicalview::LVElement::externalString(), llvm::logicalview::formatAttributes(), llvm::logicalview::formattedKind(), llvm::logicalview::formattedName(), llvm::logicalview::formattedNames(), getBitSize(), getLinkageNameIndex(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVObject::getParentScope(), getReference(), llvm::logicalview::LVElement::getTypeQualifiedName(), getValue(), kind(), llvm::logicalview::options(), OS, llvm::logicalview::LVLocation::print(), llvm::logicalview::LVElement::printLinkageName(), llvm::logicalview::LVElement::printReference(), llvm::logicalview::LVObject::Symbol, llvm::logicalview::LVElement::typeAsString(), llvm::logicalview::LVElement::typeOffsetAsString(), and llvm::logicalview::LVElement::virtualityString().
Referenced by print().
printLocations()
void LVSymbol::printLocations (raw_ostream & OS, bool Full = true) const
Definition at line 387 of file LVSymbol.cpp.
References llvm::logicalview::Location, and OS.
PROPERTY() [1/2]
llvm::logicalview::LVSymbol::PROPERTY (Property , FillGaps)
PROPERTY() [2/2]
llvm::logicalview::LVSymbol::PROPERTY (Property , HasLocation)
report()
void LVSymbol::report (LVComparePass Pass) override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 383 of file LVSymbol.cpp.
References llvm::logicalview::getComparator(), and llvm::logicalview::LVCompare::printItem().
resolveName()
void LVSymbol::resolveName () override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 222 of file LVSymbol.cpp.
References llvm::logicalview::patterns(), llvm::logicalview::LVElement::resolveName(), and llvm::logicalview::LVPatterns::resolvePatternMatch().
resolveReferences()
void LVSymbol::resolveReferences () override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 233 of file LVSymbol.cpp.
References llvm::logicalview::LVObject::Element, getReference(), llvm::logicalview::LVElement::getType(), llvm::logicalview::Reference, llvm::logicalview::LVElement::resolve(), resolveReferencesChain(), llvm::logicalview::LVElement::setFile(), llvm::logicalview::LVElement::setGenericType(), and llvm::logicalview::LVElement::setType().
resolveReferencesChain()
StringRef LVSymbol::resolveReferencesChain ()
Definition at line 274 of file LVSymbol.cpp.
References llvm::logicalview::LVElement::getName(), getReference(), llvm::logicalview::LVElement::isNamed(), and llvm::logicalview::LVElement::setName().
Referenced by resolveReferences().
setBitSize()
void llvm::logicalview::LVSymbol::setBitSize (uint32_t Size) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 115 of file LVSymbol.h.
setCoverageFactor()
void llvm::logicalview::LVSymbol::setCoverageFactor (unsigned Value) inline
Definition at line 147 of file LVSymbol.h.
setCoveragePercentage()
void llvm::logicalview::LVSymbol::setCoveragePercentage (float Value) inline
Definition at line 149 of file LVSymbol.h.
setLinkageName()
void llvm::logicalview::LVSymbol::setLinkageName (StringRef LinkageName) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 106 of file LVSymbol.h.
References llvm::logicalview::LVStringPool::getIndex(), llvm::logicalview::getStringPool(), and llvm::LinkageName.
setReference() [1/2]
void llvm::logicalview::LVSymbol::setReference (LVElement * Element) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 101 of file LVSymbol.h.
References assert(), llvm::logicalview::LVObject::Element, and setReference().
setReference() [2/2]
void llvm::logicalview::LVSymbol::setReference (LVSymbol * Symbol) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 97 of file LVSymbol.h.
References llvm::logicalview::Reference, and llvm::logicalview::LVObject::Symbol.
Referenced by llvm::logicalview::LVScope::addMissingElements(), and setReference().
setValue()
void llvm::logicalview::LVSymbol::setValue (StringRef Value) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 121 of file LVSymbol.h.
References llvm::logicalview::LVStringPool::getIndex(), and llvm::logicalview::getStringPool().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVSymbol.h
lib/DebugInfo/LogicalView/Core/LVSymbol.cpp