LLVM: llvm::DIEExpr Class Reference
llvm::DIEExpr Class Reference
An expression DIE.
#include "llvm/CodeGen/DIE.h"
Public Member Functions
DIEExpr (const MCExpr *E)
const MCExpr * getValue () const
Get MCExpr.
void emitValue (const AsmPrinter *AP, dwarf::Form Form) const
EmitValue - Emit expression value.
unsigned sizeOf (const dwarf::FormParams &FormParams, dwarf::Form Form) const
SizeOf - Determine size of expression value in bytes.
void print (raw_ostream &O) const
Detailed Description
An expression DIE.
Definition at line 201 of file DIE.h.
Constructor & Destructor Documentation
DIEExpr()
llvm::DIEExpr::DIEExpr (const MCExpr * E) inline explicit
Definition at line 205 of file DIE.h.
Member Function Documentation
emitValue()
void DIEExpr::emitValue (const AsmPrinter * AP, dwarf::Form Form) const
EmitValue - Emit expression value.
Definition at line 460 of file DIE.cpp.
References llvm::AsmPrinter::emitDebugValue(), llvm::AsmPrinter::getDwarfFormParams(), and sizeOf().
getValue()
const MCExpr* llvm::DIEExpr::getValue () const inline
Get MCExpr.
Definition at line 208 of file DIE.h.
print()
LLVM_DUMP_METHOD void DIEExpr::print (raw_ostream & O) const
Definition at line 481 of file DIE.cpp.
References llvm::RISCVFenceField::O.
sizeOf()
unsigned DIEExpr::sizeOf (const dwarf::FormParams & FormParams, dwarf::Form Form) const
SizeOf - Determine size of expression value in bytes.
Definition at line 466 of file DIE.cpp.
References llvm::dwarf::FormParams::getDwarfOffsetByteSize(), and llvm_unreachable.
Referenced by emitValue().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp