LLVM: llvm::SCCPPass Class Reference
llvm::SCCPPass Class Reference
This pass performs function-level constant propagation and merging.
#include "llvm/Transforms/Scalar/SCCP.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< SCCPPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SCCPPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
This pass performs function-level constant propagation and merging.
Definition at line 38 of file SCCP.h.
Member Function Documentation
run()
PreservedAnalyses SCCPPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 127 of file SCCP.cpp.
References llvm::PreservedAnalyses::all(), DL, F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::DomTreeUpdater::Lazy, and runSCCP().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/SCCP.h
lib/Transforms/Scalar/SCCP.cpp