LLVM: llvm::ErrorDiagnostic Class Reference
llvm::ErrorDiagnostic Class Reference
Class to represent an error holding a diagnostic with location information used when printing it.
#include "FileCheck/FileCheckImpl.h"
Public Member Functions
ErrorDiagnostic (SMDiagnostic &&Diag, SMRange Range)
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
void log (raw_ostream &OS) const override
Print diagnostic associated with this error when printing the error.
StringRef getMessage () const
SMRange getRange () const
Public Member Functions inherited from llvm::ErrorInfo< ErrorDiagnostic >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual std::string message () const
Return the error message as a string.
virtual const void * dynamicClassID () const =0
template<typename ErrorInfoT >
bool isA () const
Static Public Member Functions
static Error get (const SourceMgr &SM, SMLoc Loc, const Twine &ErrMsg, SMRange Range=std::nullopt)
static Error get (const SourceMgr &SM, StringRef Buffer, const Twine &ErrMsg)
Static Public Member Functions inherited from llvm::ErrorInfo< ErrorDiagnostic >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Static Public Attributes
static char ID = 0
Detailed Description
Class to represent an error holding a diagnostic with location information used when printing it.
Definition at line 536 of file FileCheckImpl.h.
Constructor & Destructor Documentation
ErrorDiagnostic()
llvm::ErrorDiagnostic::ErrorDiagnostic (SMDiagnostic && Diag, SMRange Range) inline
Definition at line 544 of file FileCheckImpl.h.
Member Function Documentation
convertToErrorCode()
std::error_code llvm::ErrorDiagnostic::convertToErrorCode () const inline override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 547 of file FileCheckImpl.h.
References llvm::inconvertibleErrorCode().
get() [1/2]
static Error llvm::ErrorDiagnostic::get (const SourceMgr & SM, SMLoc Loc, const Twine & ErrMsg, SMRange Range = std::nullopt) inline static
Definition at line 557 of file FileCheckImpl.h.
References llvm::SourceMgr::DK_Error, and llvm::SourceMgr::GetMessage().
Referenced by llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parseVariable(), and llvm::ExpressionFormat::valueFromStringRepr().
get() [2/2]
static Error llvm::ErrorDiagnostic::get (const SourceMgr & SM, StringRef Buffer, const Twine & ErrMsg) inline static
Definition at line 563 of file FileCheckImpl.h.
References llvm::StringRef::data(), and llvm::SMLoc::getFromPointer().
getMessage()
StringRef llvm::ErrorDiagnostic::getMessage () const inline
Definition at line 554 of file FileCheckImpl.h.
References llvm::SMDiagnostic::getMessage().
getRange()
SMRange llvm::ErrorDiagnostic::getRange () const inline
Definition at line 555 of file FileCheckImpl.h.
log()
void llvm::ErrorDiagnostic::log (raw_ostream & OS) const inline override virtual
Print diagnostic associated with this error when printing the error.
Implements llvm::ErrorInfoBase.
Definition at line 552 of file FileCheckImpl.h.
References OS, and llvm::SMDiagnostic::print().
Member Data Documentation
ID
char ErrorDiagnostic::ID = 0 static
Definition at line 542 of file FileCheckImpl.h.
The documentation for this class was generated from the following files:
lib/FileCheck/FileCheckImpl.h
lib/FileCheck/FileCheck.cpp