LLVM: llvm::DbgValueLocEntry Class Reference
llvm::DbgValueLocEntry Class Reference
A single location or constant within a variable location description, with either a single entry (with an optional DIExpression) used for a DBG_VALUE, or a list of entries used for a DBG_VALUE_LIST.
#include "CodeGen/AsmPrinter/DebugLocEntry.h"
Public Member Functions
DbgValueLocEntry (int64_t i)
DbgValueLocEntry (const ConstantFP *CFP)
DbgValueLocEntry (const ConstantInt *CIP)
DbgValueLocEntry (MachineLocation Loc)
DbgValueLocEntry (TargetIndexLocation Loc)
bool isLocation () const
bool isIndirectLocation () const
bool isTargetIndexLocation () const
bool isInt () const
bool isConstantFP () const
bool isConstantInt () const
int64_t getInt () const
const ConstantFP * getConstantFP () const
const ConstantInt * getConstantInt () const
MachineLocation getLoc () const
TargetIndexLocation getTargetIndexLocation () const
LLVM_DUMP_METHOD void dump () const
Friends
bool operator== (const DbgValueLocEntry &, const DbgValueLocEntry &)
Compare two DbgValueLocEntries for equality.
Detailed Description
A single location or constant within a variable location description, with either a single entry (with an optional DIExpression) used for a DBG_VALUE, or a list of entries used for a DBG_VALUE_LIST.
Definition at line 40 of file DebugLocEntry.h.
Constructor & Destructor Documentation
DbgValueLocEntry() [1/5]
llvm::DbgValueLocEntry::DbgValueLocEntry (int64_t i) inline
Definition at line 67 of file DebugLocEntry.h.
References i.
DbgValueLocEntry() [2/5]
llvm::DbgValueLocEntry::DbgValueLocEntry (const ConstantFP * CFP) inline
Definition at line 68 of file DebugLocEntry.h.
References CFP.
DbgValueLocEntry() [3/5]
llvm::DbgValueLocEntry::DbgValueLocEntry (const ConstantInt * CIP) inline
Definition at line 71 of file DebugLocEntry.h.
References CIP.
DbgValueLocEntry() [4/5]
llvm::DbgValueLocEntry::DbgValueLocEntry (MachineLocation Loc) inline
Definition at line 74 of file DebugLocEntry.h.
DbgValueLocEntry() [5/5]
llvm::DbgValueLocEntry::DbgValueLocEntry (TargetIndexLocation Loc) inline
Definition at line 75 of file DebugLocEntry.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void llvm::DbgValueLocEntry::dump () const inline
Definition at line 95 of file DebugLocEntry.h.
References llvm::dbgs(), llvm::Value::dump(), llvm::MachineLocation::getReg(), isConstantFP(), isConstantInt(), llvm::MachineLocation::isIndirect(), isLocation(), and Loc.
getConstantFP()
const ConstantFP* llvm::DbgValueLocEntry::getConstantFP () const inline
Definition at line 89 of file DebugLocEntry.h.
getConstantInt()
const ConstantInt* llvm::DbgValueLocEntry::getConstantInt () const inline
Definition at line 90 of file DebugLocEntry.h.
getInt()
int64_t llvm::DbgValueLocEntry::getInt () const inline
Definition at line 88 of file DebugLocEntry.h.
getLoc()
MachineLocation llvm::DbgValueLocEntry::getLoc () const inline
Definition at line 91 of file DebugLocEntry.h.
References Loc.
Referenced by llvm::DbgValueLoc::isEquivalent().
getTargetIndexLocation()
TargetIndexLocation llvm::DbgValueLocEntry::getTargetIndexLocation () const inline
Definition at line 92 of file DebugLocEntry.h.
References TIL.
isConstantFP()
bool llvm::DbgValueLocEntry::isConstantFP () const inline
Definition at line 86 of file DebugLocEntry.h.
Referenced by dump().
isConstantInt()
bool llvm::DbgValueLocEntry::isConstantInt () const inline
Definition at line 87 of file DebugLocEntry.h.
Referenced by dump().
isIndirectLocation()
bool llvm::DbgValueLocEntry::isIndirectLocation () const inline
Definition at line 79 of file DebugLocEntry.h.
References llvm::MachineLocation::isIndirect(), and Loc.
isInt()
bool llvm::DbgValueLocEntry::isInt () const inline
Definition at line 85 of file DebugLocEntry.h.
isLocation()
bool llvm::DbgValueLocEntry::isLocation () const inline
Definition at line 78 of file DebugLocEntry.h.
Referenced by llvm::DbgValueLoc::DbgValueLoc(), dump(), and llvm::DbgValueLoc::isEquivalent().
isTargetIndexLocation()
bool llvm::DbgValueLocEntry::isTargetIndexLocation () const inline
Definition at line 82 of file DebugLocEntry.h.
Friends And Related Function Documentation
operator==
bool operator== (const DbgValueLocEntry & A, const DbgValueLocEntry & B) friend
Compare two DbgValueLocEntries for equality.
Definition at line 256 of file DebugLocEntry.h.
Member Data Documentation
CFP
const ConstantFP* llvm::DbgValueLocEntry::CFP
Definition at line 55 of file DebugLocEntry.h.
Referenced by DbgValueLocEntry().
CIP
const ConstantInt* llvm::DbgValueLocEntry::CIP
Definition at line 56 of file DebugLocEntry.h.
Referenced by DbgValueLocEntry().
Int
int64_t llvm::DbgValueLocEntry::Int
Definition at line 54 of file DebugLocEntry.h.
Loc
MachineLocation llvm::DbgValueLocEntry::Loc
Or a location in the machine frame.
Definition at line 61 of file DebugLocEntry.h.
Referenced by dump(), getLoc(), and isIndirectLocation().
TIL
TargetIndexLocation llvm::DbgValueLocEntry::TIL
Or a location from target specific location.
Definition at line 63 of file DebugLocEntry.h.
Referenced by getTargetIndexLocation().
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/DebugLocEntry.h