LLVM: llvm::GenericSSAContext< MachineFunction > Class Reference
llvm::GenericSSAContext< MachineFunction > Class Reference
#include "llvm/CodeGen/MachineSSAContext.h"
Public Types
using BlockT = MachineBasicBlock
using FunctionT = MachineFunction
using InstructionT = MachineInstr
using ValueRefT = Register
using ConstValueRefT = Register
using DominatorTreeT = DominatorTreeBase< BlockT, false >
Public Member Functions
void setFunction (MachineFunction &Fn)
MachineFunction * getFunction () const
MachineBasicBlock * getDefBlock (Register) const
Get the defining block of a value.
Printable print (const MachineBasicBlock *Block) const
Printable print (const MachineInstr *Inst) const
Printable print (Register Value) const
Static Public Member Functions
static MachineBasicBlock * getEntryBlock (MachineFunction &F)
static void appendBlockDefs (SmallVectorImpl< Register > &defs, const MachineBasicBlock &block)
static void appendBlockTerms (SmallVectorImpl< MachineInstr * > &terms, MachineBasicBlock &block)
static void appendBlockTerms (SmallVectorImpl< const MachineInstr * > &terms, const MachineBasicBlock &block)
static bool isConstantValuePhi (const MachineInstr &Phi)
Static Public Attributes
static const Register ValueRefNull {}
Detailed Description
Definition at line 37 of file MachineSSAContext.h.
Member Typedef Documentation
BlockT
using llvm::GenericSSAContext< MachineFunction >::BlockT = MachineBasicBlock
Definition at line 42 of file MachineSSAContext.h.
ConstValueRefT
using llvm::GenericSSAContext< MachineFunction >::ConstValueRefT = Register
Definition at line 46 of file MachineSSAContext.h.
DominatorTreeT
using llvm::GenericSSAContext< MachineFunction >::DominatorTreeT = DominatorTreeBase<BlockT, false>
Definition at line 48 of file MachineSSAContext.h.
FunctionT
using llvm::GenericSSAContext< MachineFunction >::FunctionT = MachineFunction
Definition at line 43 of file MachineSSAContext.h.
InstructionT
using llvm::GenericSSAContext< MachineFunction >::InstructionT = MachineInstr
Definition at line 44 of file MachineSSAContext.h.
ValueRefT
using llvm::GenericSSAContext< MachineFunction >::ValueRefT = Register
Definition at line 45 of file MachineSSAContext.h.
Member Function Documentation
appendBlockDefs()
void MachineSSAContext::appendBlockDefs (SmallVectorImpl< Register > & defs, const MachineBasicBlock & block) static
Definition at line 42 of file MachineSSAContext.cpp.
References block, instr, and op.
appendBlockTerms() [1/2]
void MachineSSAContext::appendBlockTerms (SmallVectorImpl< const MachineInstr * > & terms, const MachineBasicBlock & block) static
Definition at line 35 of file MachineSSAContext.cpp.
References block.
appendBlockTerms() [2/2]
static void llvm::GenericSSAContext< MachineFunction >::appendBlockTerms (SmallVectorImpl< MachineInstr * > & terms, MachineBasicBlock & block) static
getDefBlock()
MachineBasicBlock * MachineSSAContext::getDefBlock (Register value) const
Get the defining block of a value.
Definition at line 53 of file MachineSSAContext.cpp.
References llvm::MachineBasicBlock::getParent().
getEntryBlock()
MachineBasicBlock * MachineSSAContext::getEntryBlock (MachineFunction & F) static
Definition at line 31 of file MachineSSAContext.cpp.
References F.
getFunction()
MachineFunction* llvm::GenericSSAContext< MachineFunction >::getFunction () const inline
Definition at line 51 of file MachineSSAContext.h.
isConstantValuePhi()
bool MachineSSAContext::isConstantValuePhi (const MachineInstr & Phi) static
Definition at line 59 of file MachineSSAContext.cpp.
References llvm::MachineInstr::isConstantValuePHI().
print() [1/3]
Printable MachineSSAContext::print (const MachineBasicBlock * Block) const
Definition at line 63 of file MachineSSAContext.cpp.
print() [2/3]
Printable MachineSSAContext::print (const MachineInstr * Inst) const
Definition at line 69 of file MachineSSAContext.cpp.
References I.
print() [3/3]
Printable MachineSSAContext::print (Register Value) const
Definition at line 73 of file MachineSSAContext.cpp.
References llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::MachineRegisterInfo::getUniqueVRegDef(), MRI, and llvm::printReg().
setFunction()
void MachineSSAContext::setFunction (MachineFunction & Fn)
Definition at line 26 of file MachineSSAContext.cpp.
References llvm::MachineFunction::getRegInfo().
Member Data Documentation
ValueRefNull
const Register MachineSSAContext::ValueRefNull {} static
Definition at line 47 of file MachineSSAContext.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineSSAContext.h
lib/CodeGen/MachineSSAContext.cpp