LLVM: llvm::legacy::FunctionPassManager Class Reference
llvm::legacy::FunctionPassManager Class Reference
FunctionPassManager manages FunctionPasses.
#include "llvm/IR/LegacyPassManager.h"
Public Member Functions
FunctionPassManager (Module *M)
FunctionPassManager ctor - This initializes the pass manager.
~FunctionPassManager () override
void add (Pass *P) override
Add a pass to the queue of passes to run.
bool run (Function &F)
run - Execute all of the passes scheduled for execution.
bool doInitialization ()
doInitialization - Run all of the initializers for the function passes.
bool doFinalization ()
doFinalization - Run all of the finalizers for the function passes.
Public Member Functions inherited from llvm::legacy::PassManagerBase
virtual ~PassManagerBase ()
Detailed Description
FunctionPassManager manages FunctionPasses.
Definition at line 71 of file LegacyPassManager.h.
Constructor & Destructor Documentation
FunctionPassManager()
llvm::legacy::FunctionPassManager::FunctionPassManager (Module * M) explicit
FunctionPassManager ctor - This initializes the pass manager.
Create new Function pass manager.
It needs, but does not take ownership of, the specified Module.
Definition at line 1322 of file LegacyPassManager.cpp.
References M, llvm::Pass::setResolver(), and llvm::PMDataManager::setTopLevelManager().
~FunctionPassManager()
llvm::legacy::FunctionPassManager::~FunctionPassManager () override
Definition at line 1331 of file LegacyPassManager.cpp.
Member Function Documentation
add()
void llvm::legacy::FunctionPassManager::add (Pass * P) override virtual
Add a pass to the queue of passes to run.
This passes ownership of the Pass to the PassManager. When the PassManager is destroyed, the pass will be destroyed as well, so there is no need to delete the pass. This may even destroy the pass right away if it is found to be redundant. This implies that all passes MUST be allocated with 'new'.
Implements llvm::legacy::PassManagerBase.
Definition at line 1335 of file LegacyPassManager.cpp.
References llvm::legacy::FunctionPassManagerImpl::add(), and P.
Referenced by invokeFunctionPass(), llvm::lintFunction(), and llvm::PassManagerBuilder::populateFunctionPassManager().
doFinalization()
bool llvm::legacy::FunctionPassManager::doFinalization ()
doFinalization - Run all of the finalizers for the function passes.
Definition at line 1359 of file LegacyPassManager.cpp.
References llvm::legacy::FunctionPassManagerImpl::doFinalization().
Referenced by invokeFunctionPass().
doInitialization()
bool llvm::legacy::FunctionPassManager::doInitialization ()
doInitialization - Run all of the initializers for the function passes.
Definition at line 1353 of file LegacyPassManager.cpp.
References llvm::legacy::FunctionPassManagerImpl::doInitialization().
Referenced by invokeFunctionPass().
run()
bool llvm::legacy::FunctionPassManager::run (Function & F)
run - Execute all of the passes scheduled for execution.
Keep track of whether any of the passes modifies the function, and if so, return true.
Definition at line 1343 of file LegacyPassManager.cpp.
References F, llvm::handleAllErrors(), and llvm::legacy::FunctionPassManagerImpl::run().
Referenced by invokeFunctionPass(), and llvm::lintFunction().
The documentation for this class was generated from the following files:
include/llvm/IR/LegacyPassManager.h
lib/IR/LegacyPassManager.cpp