LLVM: llvm::DINode Class Reference
llvm::DINode Class Reference
Tagged DWARF-like metadata node.
#include "llvm/IR/DebugInfoMetadata.h"
Public Types
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic, FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Protected Member Functions
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Tagged DWARF-like metadata node.
A metadata node with a DWARF tag (i.e., a constant named DW_TAG_*, defined in llvm/BinaryFormat/Dwarf.h). Called DINode because it's potentially used for non-DWARF output.
Definition at line 130 of file DebugInfoMetadata.h.
Member Enumeration Documentation
DIFlags
enum llvm::DINode::DIFlags : uint32_t
Debug info flags.
The three accessibility flags are mutually exclusive and rolled together in the first two bits.
Enumerator
FlagAccessibility
FlagPtrToMemberRep
Definition at line 169 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
DINode()
llvm::DINode::DINode (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2 = std::nullopt) inline protected
Definition at line 135 of file DebugInfoMetadata.h.
References assert(), and llvm::Metadata::SubclassData16.
~DINode()
llvm::DINode::~DINode () protected default
Member Function Documentation
classof()
static bool llvm::DINode::classof (const Metadata * MD) inline static
Definition at line 189 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
getCanonicalMDString()
static MDString* llvm::DINode::getCanonicalMDString (LLVMContext & Context, StringRef S) inline static protected
Definition at line 153 of file DebugInfoMetadata.h.
References Context, llvm::MDString::get(), and S.
getFlag()
DINode::DIFlags DINode::getFlag (StringRef Flag) static
Definition at line 219 of file DebugInfoMetadata.cpp.
References llvm::StringSwitch< T, R >::Default().
Referenced by llvm::LLParser::parseMDField().
getFlagString()
StringRef DINode::getFlagString (DIFlags Flag) static
Definition at line 226 of file DebugInfoMetadata.cpp.
getOperandAs()
template<class Ty > Ty* llvm::DINode::getOperandAs (unsigned I) const inline protected
Definition at line 143 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand(), and I.
getStringOperand()
StringRef llvm::DINode::getStringOperand (unsigned I) const inline protected
Definition at line 147 of file DebugInfoMetadata.h.
References I, and S.
Referenced by llvm::DIGlobalVariable::getDisplayName(), llvm::DICompileUnit::getFlags(), llvm::DIObjCProperty::getGetterName(), llvm::GenericDINode::getHeader(), llvm::DICompositeType::getIdentifier(), llvm::DIGlobalVariable::getLinkageName(), llvm::DIEnumerator::getName(), llvm::DIType::getName(), llvm::DINamespace::getName(), llvm::DITemplateParameter::getName(), llvm::DIVariable::getName(), llvm::DICommonBlock::getName(), llvm::DILabel::getName(), llvm::DIObjCProperty::getName(), llvm::DICompileUnit::getProducer(), llvm::DICompileUnit::getSDK(), llvm::DIObjCProperty::getSetterName(), llvm::DICompileUnit::getSplitDebugFilename(), and llvm::DICompileUnit::getSysRoot().
getTag()
dwarf::Tag DINode::getTag () const
Definition at line 217 of file DebugInfoMetadata.cpp.
References llvm::Metadata::SubclassData16.
Referenced by llvm::DwarfUnit::createTypeDIE(), llvm::BTFDebug::endModule(), llvm::DebugHandlerBase::getBaseTypeSize(), getCommonClassOptions(), llvm::DIDerivedType::getConstant(), llvm::DIDerivedType::getDiscriminantValue(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), getRecordKind(), llvm::DIDerivedType::getStorageOffsetInBits(), llvm::DIDerivedType::getVBPtrOffset(), isFloatDIType(), llvm::DebugHandlerBase::isUnsignedDIType(), and stripQualifiers().
setTag()
void llvm::DINode::setTag (unsigned Tag) inline protected
Allow subclasses to mutate the tag.
Definition at line 160 of file DebugInfoMetadata.h.
References llvm::Metadata::SubclassData16.
Referenced by llvm::DIType::mutate().
splitFlags()
DINode::DIFlags DINode::splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > & SplitFlags) static
Split up a flags bitfield.
Split Flags into SplitFlags, a vector of its components. Returns any remaining (unrecognized) bits.
Definition at line 236 of file DebugInfoMetadata.cpp.
References FlagAccessibility, and FlagPtrToMemberRep.
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 131 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 132 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp