LLVM: llvm::objcopy::MultiFormatConfig Class Reference
llvm::objcopy::MultiFormatConfig Class Reference abstract
#include "llvm/ObjCopy/MultiFormatConfig.h"
Public Member Functions
virtual ~MultiFormatConfig ()
virtual const CommonConfig & getCommonConfig () const =0
virtual Expected< const ELFConfig & > getELFConfig () const =0
virtual Expected< const COFFConfig & > getCOFFConfig () const =0
virtual Expected< const MachOConfig & > getMachOConfig () const =0
virtual Expected< const WasmConfig & > getWasmConfig () const =0
virtual Expected< const XCOFFConfig & > getXCOFFConfig () const =0
Detailed Description
Definition at line 24 of file MultiFormatConfig.h.
Constructor & Destructor Documentation
~MultiFormatConfig()
virtual llvm::objcopy::MultiFormatConfig::~MultiFormatConfig () inline virtual
Definition at line 26 of file MultiFormatConfig.h.
Member Function Documentation
getCOFFConfig()
virtual Expected<const COFFConfig &> llvm::objcopy::MultiFormatConfig::getCOFFConfig () const pure virtual
Implemented in llvm::objcopy::ConfigManager.
Referenced by llvm::objcopy::executeObjcopyOnBinary().
getCommonConfig()
virtual const CommonConfig& llvm::objcopy::MultiFormatConfig::getCommonConfig () const pure virtual
Implemented in llvm::objcopy::ConfigManager.
Referenced by llvm::objcopy::executeObjcopyOnArchive(), llvm::objcopy::executeObjcopyOnBinary(), and llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary().
getELFConfig()
virtual Expected<const ELFConfig &> llvm::objcopy::MultiFormatConfig::getELFConfig () const pure virtual
Implemented in llvm::objcopy::ConfigManager.
Referenced by llvm::objcopy::executeObjcopyOnBinary().
getMachOConfig()
virtual Expected<const MachOConfig &> llvm::objcopy::MultiFormatConfig::getMachOConfig () const pure virtual
Implemented in llvm::objcopy::ConfigManager.
Referenced by llvm::objcopy::executeObjcopyOnBinary(), and llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary().
getWasmConfig()
virtual Expected<const WasmConfig &> llvm::objcopy::MultiFormatConfig::getWasmConfig () const pure virtual
Implemented in llvm::objcopy::ConfigManager.
Referenced by llvm::objcopy::executeObjcopyOnBinary().
getXCOFFConfig()
virtual Expected<const XCOFFConfig &> llvm::objcopy::MultiFormatConfig::getXCOFFConfig () const pure virtual
Implemented in llvm::objcopy::ConfigManager.
Referenced by llvm::objcopy::executeObjcopyOnBinary().
The documentation for this class was generated from the following file:
include/llvm/ObjCopy/MultiFormatConfig.h