LLVM: llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle > Class Template Reference
llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle > Class Template Reference
reg_begin/reg_end - Provide iteration support to walk over all definitions and uses of a register within the MachineFunction that corresponds to this MachineRegisterInfo object.
#include "llvm/CodeGen/MachineRegisterInfo.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = MachineOperand
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
defusechain_iterator ()=default
bool operator== (const defusechain_iterator &x) const
bool operator!= (const defusechain_iterator &x) const
bool atEnd () const
atEnd - return true if this iterator is equal to reg_end() on the value.
defusechain_iterator & operator++ ()
defusechain_iterator operator++ (int)
unsigned getOperandNo () const
getOperandNo - Return the operand # of this MachineOperand in its MachineInstr.
MachineOperand & operator* () const
MachineOperand * operator-> () const
Friends
class MachineRegisterInfo
Detailed Description
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle>
class llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >
reg_begin/reg_end - Provide iteration support to walk over all definitions and uses of a register within the MachineFunction that corresponds to this MachineRegisterInfo object.
defusechain_iterator - This class provides iterator support for machine operands in the function that use or define a specific register.
If ReturnUses is true it returns uses of registers, if ReturnDefs is true it returns defs. If neither are true then you are silly and it always returns end(). If SkipDebug is true it skips uses marked Debug when incrementing.
Definition at line 288 of file MachineRegisterInfo.h.
Member Typedef Documentation
difference_type
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> using llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::difference_type = std::ptrdiff_t
Definition at line 1035 of file MachineRegisterInfo.h.
iterator_category
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> using llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::iterator_category = std::forward_iterator_tag
Definition at line 1033 of file MachineRegisterInfo.h.
pointer
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> using llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::pointer = value_type *
Definition at line 1036 of file MachineRegisterInfo.h.
reference
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> using llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::reference = value_type &
Definition at line 1037 of file MachineRegisterInfo.h.
value_type
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> using llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::value_type = MachineOperand
Definition at line 1034 of file MachineRegisterInfo.h.
Constructor & Destructor Documentation
defusechain_iterator()
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::defusechain_iterator () default
Member Function Documentation
atEnd()
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> bool llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::atEnd () const inline
atEnd - return true if this iterator is equal to reg_end() on the value.
Definition at line 1084 of file MachineRegisterInfo.h.
getOperandNo()
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> unsigned llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::getOperandNo () const inline
getOperandNo - Return the operand # of this MachineOperand in its MachineInstr.
Definition at line 1112 of file MachineRegisterInfo.h.
References assert().
Referenced by llvm::FastISel::tryToFoldLoad().
operator!=()
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> bool llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator!= (const defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle > & x) const inline
Definition at line 1079 of file MachineRegisterInfo.h.
References llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator==(), and x.
operator*()
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> MachineOperand& llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator* () const inline
Definition at line 1118 of file MachineRegisterInfo.h.
References assert().
operator++() [1/2]
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> defusechain_iterator& llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator++ () inline
Definition at line 1087 of file MachineRegisterInfo.h.
References assert(), llvm::getBundleStart(), and P.
operator++() [2/2]
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> defusechain_iterator llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator++ (int) inline
Definition at line 1106 of file MachineRegisterInfo.h.
operator->()
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> MachineOperand* llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator-> () const inline
Definition at line 1123 of file MachineRegisterInfo.h.
References assert().
operator==()
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> bool llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator== (const defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle > & x) const inline
Definition at line 1076 of file MachineRegisterInfo.h.
References x.
Referenced by llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator!=().
Friends And Related Function Documentation
MachineRegisterInfo
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug, bool ByOperand, bool ByInstr, bool ByBundle> friend class MachineRegisterInfo friend
Definition at line 1030 of file MachineRegisterInfo.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/MachineRegisterInfo.h