LLVM: llvm::SCEVExpanderCleaner Class Reference
llvm::SCEVExpanderCleaner Class Reference
Helper to remove instructions inserted during SCEV expansion, unless they are marked as used.
#include "llvm/Transforms/Utils/ScalarEvolutionExpander.h"
Public Member Functions
SCEVExpanderCleaner (SCEVExpander &Expander)
~SCEVExpanderCleaner ()
void markResultUsed ()
Indicate that the result of the expansion is used.
void cleanup ()
Detailed Description
Helper to remove instructions inserted during SCEV expansion, unless they are marked as used.
Definition at line 510 of file ScalarEvolutionExpander.h.
Constructor & Destructor Documentation
SCEVExpanderCleaner()
llvm::SCEVExpanderCleaner::SCEVExpanderCleaner (SCEVExpander & Expander) inline
Definition at line 518 of file ScalarEvolutionExpander.h.
~SCEVExpanderCleaner()
llvm::SCEVExpanderCleaner::~SCEVExpanderCleaner () inline
Definition at line 521 of file ScalarEvolutionExpander.h.
References cleanup().
Member Function Documentation
cleanup()
void SCEVExpanderCleaner::cleanup ()
Definition at line 2649 of file ScalarEvolutionExpander.cpp.
References llvm::all_of(), assert(), llvm::SmallPtrSetImplBase::clear(), llvm::PoisonValue::get(), I, and llvm::reverse().
Referenced by ~SCEVExpanderCleaner().
markResultUsed()
void llvm::SCEVExpanderCleaner::markResultUsed () inline
Indicate that the result of the expansion is used.
Definition at line 524 of file ScalarEvolutionExpander.h.
Referenced by ReduceLoopStrength().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/ScalarEvolutionExpander.h
lib/Transforms/Utils/ScalarEvolutionExpander.cpp