LLVM: llvm::VPRegionBlock Class Reference
llvm::VPRegionBlock Class Reference
VPRegionBlock represents a collection of VPBasicBlocks and VPRegionBlocks which form a Single-Entry-Single-Exiting subgraph of the output IR CFG.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPRegionBlock (VPBlockBase *Entry, VPBlockBase *Exiting, const std::string &Name="", bool IsReplicator=false)
VPRegionBlock (const std::string &Name="", bool IsReplicator=false)
~VPRegionBlock () override
const VPBlockBase * getEntry () const
VPBlockBase * getEntry ()
void setEntry (VPBlockBase *EntryBlock)
Set EntryBlock as the entry VPBlockBase of this VPRegionBlock.
const VPBlockBase * getExiting () const
VPBlockBase * getExiting ()
void setExiting (VPBlockBase *ExitingBlock)
Set ExitingBlock as the exiting VPBlockBase of this VPRegionBlock.
VPBasicBlock * getPreheaderVPBB ()
Returns the pre-header VPBasicBlock of the loop region.
bool isReplicator () const
An indicator whether this region is to generate multiple replicated instances of output IR corresponding to its VPBlockBases.
void execute (VPTransformState *State) override
The method which generates the output IR instructions that correspond to this VPRegionBlock, thereby "executing" the VPlan.
void dropAllReferences (VPValue *NewValue) override
Replace all operands of VPUsers in the block with NewValue and also replaces all uses of VPValues defined in the block with NewValue.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print this VPRegionBlock to O (recursively), prefixing all lines with Indent.
virtual void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const=0
Print plain-text dump of this VPBlockBase to O, prefixing all lines with Indent.
void print (raw_ostream &O) const
Print plain-text dump of this VPlan to O.
Public Member Functions inherited from llvm::VPBlockBase
virtual ~VPBlockBase ()=default
const std::string & getName () const
void setName (const Twine &newName)
unsigned getVPBlockID () const
VPRegionBlock * getParent ()
const VPRegionBlock * getParent () const
VPlan * getPlan ()
const VPlan * getPlan () const
void setPlan (VPlan *ParentPlan)
Sets the pointer of the plan containing the block.
void setParent (VPRegionBlock *P)
const VPBasicBlock * getEntryBasicBlock () const
VPBasicBlock * getEntryBasicBlock ()
const VPBasicBlock * getExitingBasicBlock () const
VPBasicBlock * getExitingBasicBlock ()
const VPBlocksTy & getSuccessors () const
VPBlocksTy & getSuccessors ()
iterator_range< VPBlockBase ** > successors ()
const VPBlocksTy & getPredecessors () const
VPBlocksTy & getPredecessors ()
VPBlockBase * getSingleSuccessor () const
VPBlockBase * getSinglePredecessor () const
size_t getNumSuccessors () const
size_t getNumPredecessors () const
VPBlockBase * getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
VPBlockBase * getEnclosingBlockWithPredecessors ()
const VPBlocksTy & getHierarchicalSuccessors ()
VPBlockBase * getSingleHierarchicalSuccessor ()
const VPBlocksTy & getHierarchicalPredecessors ()
VPBlockBase * getSingleHierarchicalPredecessor ()
void setOneSuccessor (VPBlockBase *Successor)
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
void setTwoSuccessors (VPBlockBase *IfTrue, VPBlockBase *IfFalse)
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
void setPredecessors (ArrayRef< VPBlockBase * > NewPreds)
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
void clearPredecessors ()
Remove all the predecessor of this block.
void clearSuccessors ()
Remove all the successors of this block.
bool isLegalToHoistInto ()
Return true if it is legal to hoist instructions into this block.
void printAsOperand (raw_ostream &OS, bool PrintType) const
void print (raw_ostream &O) const
Print plain-text dump of this VPlan to O.
void printSuccessors (raw_ostream &O, const Twine &Indent) const
Print the successors of this block to O, prefixing all lines with Indent.
LLVM_DUMP_METHOD void dump () const
Dump this VPBlockBase to dbgs().
Static Public Member Functions
static bool classof (const VPBlockBase *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::VPBlockBase
static void deleteCFG (VPBlockBase *Entry)
Delete all blocks reachable from a given VPBlockBase, inclusive.
Additional Inherited Members
Public Types inherited from llvm::VPBlockBase
using VPBlockTy = enum { VPBasicBlockSC, VPRegionBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
using VPBlocksTy = SmallVectorImpl< VPBlockBase * >
Protected Member Functions inherited from llvm::VPBlockBase
VPBlockBase (const unsigned char SC, const std::string &N)
Detailed Description
VPRegionBlock represents a collection of VPBasicBlocks and VPRegionBlocks which form a Single-Entry-Single-Exiting subgraph of the output IR CFG.
A VPRegionBlock may indicate that its contents are to be replicated several times. This is designed to support predicated scalarization, in which a scalar if-then code structure needs to be generated VF * UF times. Having this replication indicator helps to keep a single model for multiple candidate VF's. The actual replication takes place only once the desired VF and UF have been determined.
Definition at line 2069 of file VPlan.h.
Constructor & Destructor Documentation
VPRegionBlock() [1/2]
llvm::VPRegionBlock::VPRegionBlock (VPBlockBase * Entry, VPBlockBase * Exiting, const std::string & Name = "", bool IsReplicator = false) inline
Definition at line 2082 of file VPlan.h.
References assert(), llvm::VPBlockBase::getSuccessors(), and llvm::VPBlockBase::setParent().
VPRegionBlock() [2/2]
llvm::VPRegionBlock::VPRegionBlock (const std::string & Name = "", bool IsReplicator = false) inline
Definition at line 2091 of file VPlan.h.
~VPRegionBlock()
llvm::VPRegionBlock::~VPRegionBlock () inline override
Definition at line 2095 of file VPlan.h.
References llvm::VPBlockBase::deleteCFG().
Member Function Documentation
classof()
static bool llvm::VPRegionBlock::classof (const VPBlockBase * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 2104 of file VPlan.h.
References llvm::VPBlockBase::getVPBlockID().
dropAllReferences()
void VPRegionBlock::dropAllReferences (VPValue * NewValue) override virtual
Replace all operands of VPUsers in the block with NewValue and also replaces all uses of VPValues defined in the block with NewValue.
Implements llvm::VPBlockBase.
Definition at line 509 of file VPlan.cpp.
References llvm::vp_depth_first_shallow().
execute()
void VPRegionBlock::execute (VPTransformState * State) override virtual
The method which generates the output IR instructions that correspond to this VPRegionBlock, thereby "executing" the VPlan.
Implements llvm::VPBlockBase.
Definition at line 516 of file VPlan.cpp.
getEntry() [1/2]
VPBlockBase* llvm::VPRegionBlock::getEntry () inline
Definition at line 2109 of file VPlan.h.
getEntry() [2/2]
const VPBlockBase* llvm::VPRegionBlock::getEntry () const inline
Definition at line 2108 of file VPlan.h.
Referenced by llvm::VPlanTransforms::adjustFixedOrderRecurrences(), and llvm::VPBlockBase::getEnclosingBlockWithPredecessors().
getExiting() [1/2]
VPBlockBase* llvm::VPRegionBlock::getExiting () inline
Definition at line 2121 of file VPlan.h.
getExiting() [2/2]
const VPBlockBase* llvm::VPRegionBlock::getExiting () const inline
Definition at line 2120 of file VPlan.h.
Referenced by llvm::VPBlockBase::getEnclosingBlockWithSuccessors(), and properlyDominates().
getPreheaderVPBB()
VPBasicBlock* llvm::VPRegionBlock::getPreheaderVPBB () inline
Returns the pre-header VPBasicBlock of the loop region.
Definition at line 2133 of file VPlan.h.
References assert(), llvm::VPBlockBase::getExitingBasicBlock(), llvm::VPBlockBase::getSinglePredecessor(), and isReplicator().
Referenced by llvm::VPTransformState::CFGState::getPreheaderBBFor().
isReplicator()
bool llvm::VPRegionBlock::isReplicator () const inline
An indicator whether this region is to generate multiple replicated instances of output IR corresponding to its VPBlockBases.
Definition at line 2140 of file VPlan.h.
Referenced by getPreheaderVPBB().
print() [1/3]
void llvm::VPBlockBase::print inline
Print plain-text dump of this VPlan to O.
Definition at line 619 of file VPlan.h.
print() [2/3]
void VPRegionBlock::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print this VPRegionBlock to O (recursively), prefixing all lines with Indent.
SlotTracker is used to print unnamed VPValue's using consequtive numbers.
Note that the numbering is applied to the whole VPlan, so printing individual regions is consistent with the whole VPlan printing.
Implements llvm::VPBlockBase.
Definition at line 568 of file VPlan.cpp.
References getName(), llvm::RISCVFenceField::O, and llvm::vp_depth_first_shallow().
print() [3/3]
virtual void llvm::VPBlockBase::print
Print plain-text dump of this VPBlockBase to O, prefixing all lines with Indent.
SlotTracker is used to print unnamed VPValue's using consequtive numbers.
Note that the numbering is applied to the whole VPlan, so printing individual blocks is consistent with the whole VPlan printing.
setEntry()
void llvm::VPRegionBlock::setEntry (VPBlockBase * EntryBlock) inline
Set EntryBlock as the entry VPBlockBase of this VPRegionBlock.
EntryBlock must have no predecessors.
Definition at line 2113 of file VPlan.h.
References assert(), llvm::VPBlockBase::getPredecessors(), and llvm::VPBlockBase::setParent().
setExiting()
void llvm::VPRegionBlock::setExiting (VPBlockBase * ExitingBlock) inline
Set ExitingBlock as the exiting VPBlockBase of this VPRegionBlock.
ExitingBlock must have no successors.
Definition at line 2125 of file VPlan.h.
References assert(), llvm::VPBlockBase::getSuccessors(), and llvm::VPBlockBase::setParent().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp