LLVM: llvm::InstrProfRecordWriterTrait Class Reference
llvm::InstrProfRecordWriterTrait Class Reference
Public Types
using key_type = StringRef
using key_type_ref = StringRef
using data_type = const InstrProfWriter::ProfilingData *const
using data_type_ref = const InstrProfWriter::ProfilingData *const
using hash_value_type = uint64_t
using offset_type = uint64_t
Public Member Functions
InstrProfRecordWriterTrait ()=default
void EmitKey (raw_ostream &Out, key_type_ref K, offset_type N)
void EmitData (raw_ostream &Out, key_type_ref, data_type_ref V, offset_type)
Static Public Member Functions
static hash_value_type ComputeHash (key_type_ref K)
static std::pair< offset_type, offset_type > EmitKeyDataLength (raw_ostream &Out, key_type_ref K, data_type_ref V)
Public Attributes
support::endianness ValueProfDataEndianness = support::little
InstrProfSummaryBuilder * SummaryBuilder
InstrProfSummaryBuilder * CSSummaryBuilder
Detailed Description
Definition at line 97 of file InstrProfWriter.cpp.
Member Typedef Documentation
data_type
using llvm::InstrProfRecordWriterTrait::data_type = const InstrProfWriter::ProfilingData *const
Definition at line 102 of file InstrProfWriter.cpp.
data_type_ref
using llvm::InstrProfRecordWriterTrait::data_type_ref = const InstrProfWriter::ProfilingData *const
Definition at line 103 of file InstrProfWriter.cpp.
hash_value_type
using llvm::InstrProfRecordWriterTrait::hash_value_type = uint64_t
Definition at line 105 of file InstrProfWriter.cpp.
key_type
using llvm::InstrProfRecordWriterTrait::key_type = StringRef
Definition at line 99 of file InstrProfWriter.cpp.
key_type_ref
using llvm::InstrProfRecordWriterTrait::key_type_ref = StringRef
Definition at line 100 of file InstrProfWriter.cpp.
offset_type
using llvm::InstrProfRecordWriterTrait::offset_type = uint64_t
Definition at line 106 of file InstrProfWriter.cpp.
Constructor & Destructor Documentation
InstrProfRecordWriterTrait()
llvm::InstrProfRecordWriterTrait::InstrProfRecordWriterTrait () default
Member Function Documentation
ComputeHash()
static hash_value_type llvm::InstrProfRecordWriterTrait::ComputeHash (key_type_ref K) inline static
Definition at line 114 of file InstrProfWriter.cpp.
References llvm::IndexedInstrProf::ComputeHash().
EmitData()
void llvm::InstrProfRecordWriterTrait::EmitData (raw_ostream & Out, key_type_ref , data_type_ref V, offset_type) inline
Definition at line 146 of file InstrProfWriter.cpp.
References llvm::InstrProfSummaryBuilder::addRecord(), llvm::InstrProfRecord::Counts, llvm::NamedInstrProfRecord::hasCSFlagInHash(), I, llvm::ProfOStream::LE, llvm::support::little, S, support(), uint64_t, llvm::support::endian::Writer::write(), and llvm::raw_ostream::write().
EmitKey()
void llvm::InstrProfRecordWriterTrait::EmitKey (raw_ostream & Out, key_type_ref K, offset_type N) inline
Definition at line 142 of file InstrProfWriter.cpp.
References llvm::StringRef::data(), N, and llvm::raw_ostream::write().
EmitKeyDataLength()
static std::pair<offset_type, offset_type> llvm::InstrProfRecordWriterTrait::EmitKeyDataLength (raw_ostream & Out, key_type_ref K, data_type_ref V) inline static
Definition at line 119 of file InstrProfWriter.cpp.
References llvm::InstrProfRecord::Counts, getSize(), llvm::ProfOStream::LE, llvm::support::little, M, N, llvm::StringRef::size(), support(), uint64_t, and llvm::support::endian::Writer::write().
Member Data Documentation
CSSummaryBuilder
InstrProfSummaryBuilder* llvm::InstrProfRecordWriterTrait::CSSummaryBuilder
Definition at line 110 of file InstrProfWriter.cpp.
SummaryBuilder
InstrProfSummaryBuilder* llvm::InstrProfRecordWriterTrait::SummaryBuilder
Definition at line 109 of file InstrProfWriter.cpp.
ValueProfDataEndianness
support::endianness llvm::InstrProfRecordWriterTrait::ValueProfDataEndianness = support::little
Definition at line 108 of file InstrProfWriter.cpp.
Referenced by llvm::InstrProfWriter::setValueProfDataEndianness().
The documentation for this class was generated from the following file:
lib/ProfileData/InstrProfWriter.cpp