LLVM: llvm::FunctionAnalysisManagerCGSCCProxy::Result Class Reference
llvm::FunctionAnalysisManagerCGSCCProxy::Result Class Reference
#include "llvm/Analysis/CGSCCPassManager.h"
Public Member Functions
Result ()
Result (FunctionAnalysisManager &FAM)
void updateFAM (FunctionAnalysisManager &FAM)
FunctionAnalysisManager & getManager ()
Accessor for the analysis manager.
bool invalidate (LazyCallGraph::SCC &C, const PreservedAnalyses &PA, CGSCCAnalysisManager::Invalidator &Inv)
Detailed Description
Definition at line 395 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
Result() [1/2]
llvm::FunctionAnalysisManagerCGSCCProxy::Result::Result () inline explicit
Definition at line 397 of file CGSCCPassManager.h.
Result() [2/2]
llvm::FunctionAnalysisManagerCGSCCProxy::Result::Result (FunctionAnalysisManager & FAM) inline explicit
Definition at line 398 of file CGSCCPassManager.h.
References FAM.
Member Function Documentation
getManager()
FunctionAnalysisManager& llvm::FunctionAnalysisManagerCGSCCProxy::Result::getManager () inline
Accessor for the analysis manager.
Definition at line 402 of file CGSCCPassManager.h.
References assert().
invalidate()
bool llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate (LazyCallGraph::SCC & C, const PreservedAnalyses & PA, CGSCCAnalysisManager::Invalidator & Inv)
Definition at line 688 of file CGSCCPassManager.cpp.
References llvm::PreservedAnalyses::abandon(), llvm::PreservedAnalyses::allAnalysesInSetPreserved(), llvm::PreservedAnalyses::areAllPreserved(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::PreservedAnalyses::getChecker(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), and N.
updateFAM()
void llvm::FunctionAnalysisManagerCGSCCProxy::Result::updateFAM (FunctionAnalysisManager & FAM) inline
Definition at line 400 of file CGSCCPassManager.h.
References FAM.
The documentation for this class was generated from the following files:
include/llvm/Analysis/CGSCCPassManager.h
lib/Analysis/CGSCCPassManager.cpp