LLVM: llvm::pdb::NativeEnumLineNumbers Class Reference
llvm::pdb::NativeEnumLineNumbers Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeEnumLineNumbers.h"
Public Member Functions
NativeEnumLineNumbers (std::vector< NativeLineNumber > LineNums)
uint32_t getChildCount () const override
ChildTypePtr getChildAtIndex (uint32_t Index) const override
ChildTypePtr getNext () override
void reset () override
Public Member Functions inherited from llvm::pdb::IPDBEnumChildren< IPDBLineNumber >
virtual ~IPDBEnumChildren ()=default
virtual uint32_t getChildCount () const=0
Additional Inherited Members
Public Types inherited from llvm::pdb::IPDBEnumChildren< IPDBLineNumber >
using ChildTypePtr = std::unique_ptr< IPDBLineNumber >
using MyType = IPDBEnumChildren< IPDBLineNumber >
Detailed Description
Definition at line 20 of file NativeEnumLineNumbers.h.
Constructor & Destructor Documentation
NativeEnumLineNumbers()
NativeEnumLineNumbers::NativeEnumLineNumbers (std::vector< NativeLineNumber > LineNums) explicit
Definition at line 21 of file NativeEnumLineNumbers.cpp.
References llvm::codeview::Lines.
Member Function Documentation
getChildAtIndex()
std::unique_ptr< IPDBLineNumber > NativeEnumLineNumbers::getChildAtIndex (uint32_t Index) const override virtual
Implements llvm::pdb::IPDBEnumChildren< IPDBLineNumber >.
Definition at line 30 of file NativeEnumLineNumbers.cpp.
References getChildCount(), and N.
Referenced by getNext().
getChildCount()
uint32_t NativeEnumLineNumbers::getChildCount () const override
Definition at line 25 of file NativeEnumLineNumbers.cpp.
Referenced by getChildAtIndex().
getNext()
std::unique_ptr< IPDBLineNumber > NativeEnumLineNumbers::getNext () override virtual
Implements llvm::pdb::IPDBEnumChildren< IPDBLineNumber >.
Definition at line 36 of file NativeEnumLineNumbers.cpp.
References getChildAtIndex().
reset()
void NativeEnumLineNumbers::reset () override virtual
Implements llvm::pdb::IPDBEnumChildren< IPDBLineNumber >.
Definition at line 40 of file NativeEnumLineNumbers.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeEnumLineNumbers.h
lib/DebugInfo/PDB/Native/NativeEnumLineNumbers.cpp