LLVM: llvm::PseudoProbeHandler Class Reference
llvm::PseudoProbeHandler Class Reference
#include "CodeGen/AsmPrinter/PseudoProbePrinter.h"
Public Member Functions
PseudoProbeHandler (AsmPrinter *A)
~PseudoProbeHandler () override
void emitPseudoProbe (uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attr, const DILocation *DebugLoc)
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g.
void endModule () override
Emit all sections that should come after the content.
void beginFunction (const MachineFunction *MF) override
Gather pre-function debug information.
void endFunction (const MachineFunction *MF) override
Gather post-function debug information.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void beginModule (Module *M)
virtual void markFunctionEnd ()
virtual void beginBasicBlockSection (const MachineBasicBlock &MBB)
Process the beginning of a new basic-block-section within a function.
virtual void endBasicBlockSection (const MachineBasicBlock &MBB)
Process the end of a basic-block-section within a function.
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
Detailed Description
Definition at line 24 of file PseudoProbePrinter.h.
Constructor & Destructor Documentation
PseudoProbeHandler()
llvm::PseudoProbeHandler::PseudoProbeHandler (AsmPrinter * A) inline
Definition at line 31 of file PseudoProbePrinter.h.
~PseudoProbeHandler()
PseudoProbeHandler::~PseudoProbeHandler () override default
Member Function Documentation
beginFunction()
void llvm::PseudoProbeHandler::beginFunction (const MachineFunction * MF) inline override virtual
Gather pre-function debug information.
Every beginFunction(MF) call should be followed by an endFunction(MF) call.
Implements llvm::AsmPrinterHandler.
Definition at line 40 of file PseudoProbePrinter.h.
beginInstruction()
void llvm::PseudoProbeHandler::beginInstruction (const MachineInstr * MI) inline override virtual
Process beginning of an instruction.
Implements llvm::AsmPrinterHandler.
Definition at line 42 of file PseudoProbePrinter.h.
emitPseudoProbe()
void PseudoProbeHandler::emitPseudoProbe (uint64_t Guid, uint64_t Index, uint64_t Type, uint64_t Attr, const DILocation * DebugLoc)
Definition at line 25 of file PseudoProbePrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::SmallVectorImpl< T >::emplace_back(), llvm::PseudoProbeDwarfDiscriminator::extractProbeIndex(), llvm::GlobalValue::getGUID(), llvm::DIScope::getName(), llvm::DIScope::getScope(), llvm::AsmPrinter::OutStreamer, llvm::reverse(), and uint64_t.
Referenced by llvm::AsmPrinter::emitPseudoProbe().
endFunction()
void llvm::PseudoProbeHandler::endFunction (const MachineFunction * MF) inline override virtual
Gather post-function debug information.
Implements llvm::AsmPrinterHandler.
Definition at line 41 of file PseudoProbePrinter.h.
endInstruction()
void llvm::PseudoProbeHandler::endInstruction () inline override virtual
Process end of an instruction.
Implements llvm::AsmPrinterHandler.
Definition at line 43 of file PseudoProbePrinter.h.
endModule()
void llvm::PseudoProbeHandler::endModule () inline override virtual
Emit all sections that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 39 of file PseudoProbePrinter.h.
setSymbolSize()
void llvm::PseudoProbeHandler::setSymbolSize (const MCSymbol * Sym, uint64_t Size) inline override virtual
For symbols that have a size designated (e.g.
common symbols), this tracks that size.
Implements llvm::AsmPrinterHandler.
Definition at line 38 of file PseudoProbePrinter.h.
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/PseudoProbePrinter.h
lib/CodeGen/AsmPrinter/PseudoProbePrinter.cpp