LLVM: llvm::MCSection Class Reference
llvm::MCSection Class Reference abstract
Instances of this class represent a uniqued identifier for a section in the current translation unit.
#include "llvm/MC/MCSection.h"
Public Types
enum SectionVariant {
SV_COFF = 0, SV_ELF, SV_GOFF, SV_MachO,
SV_Wasm, SV_XCOFF, SV_SPIRV, SV_DXContainer
}
enum BundleLockStateType { NotBundleLocked, BundleLocked, BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
using FragmentListType = iplist< MCFragment >
using const_iterator = FragmentListType::const_iterator
using iterator = FragmentListType::iterator
using const_reverse_iterator = FragmentListType::const_reverse_iterator
using reverse_iterator = FragmentListType::reverse_iterator
Public Member Functions
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
StringRef getName () const
SectionKind getKind () const
SectionVariant getVariant () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
Align getAlign () const
void setAlignment (Align Value)
void ensureMinAlignment (Align MinAlignment)
Makes sure that Alignment is at least MinAlignment.
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleLocked () const
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
MCSection::FragmentListType & getFragmentList ()
const MCSection::FragmentListType & getFragmentList () const
const MCDummyFragment & getDummyFragment () const
MCDummyFragment & getDummyFragment ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
MCSection::iterator getSubsectionInsertionPoint (unsigned Subsection)
void dump () const
virtual void printSwitchToSection (const MCAsmInfo &MAI, const Triple &T, raw_ostream &OS, const MCExpr *Subsection) const =0
virtual bool useCodeAlign () const =0
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
virtual bool isVirtualSection () const =0
Check whether this section is "virtual", that is has no actual object file contents.
virtual StringRef getVirtualSectionKind () const
void addPendingLabel (MCSymbol *label, unsigned Subsection=0)
Add a pending label for the requested subsection.
void flushPendingLabels (MCFragment *F, uint64_t FOffset=0, unsigned Subsection=0)
Associate all pending labels in a subsection with a fragment.
void flushPendingLabels ()
Associate all pending labels with empty data fragments.
Static Public Member Functions
static FragmentListType MCSection::* getSublistAccess (MCFragment *)
Support for MCFragment::getNextNode().
Static Public Attributes
static constexpr unsigned NonUniqueID = ~0U
Protected Member Functions
MCSection (SectionVariant V, StringRef Name, SectionKind K, MCSymbol *Begin)
~MCSection ()
Protected Attributes
StringRef Name
SectionVariant Variant
SectionKind Kind
Detailed Description
Instances of this class represent a uniqued identifier for a section in the current translation unit.
The MCContext class uniques and creates these.
Definition at line 39 of file MCSection.h.
Member Typedef Documentation
const_iterator
using llvm::MCSection::const_iterator = FragmentListType::const_iterator
Definition at line 63 of file MCSection.h.
const_reverse_iterator
using llvm::MCSection::const_reverse_iterator = FragmentListType::const_reverse_iterator
Definition at line 66 of file MCSection.h.
FragmentListType
using llvm::MCSection::FragmentListType = iplist<MCFragment>
Definition at line 61 of file MCSection.h.
iterator
using llvm::MCSection::iterator = FragmentListType::iterator
Definition at line 64 of file MCSection.h.
reverse_iterator
using llvm::MCSection::reverse_iterator = FragmentListType::reverse_iterator
Definition at line 67 of file MCSection.h.
Member Enumeration Documentation
BundleLockStateType
enum llvm::MCSection::BundleLockStateType
Express the state of bundle locked groups while emitting code.
Enumerator
NotBundleLocked
BundleLocked
BundleLockedAlignToEnd
Definition at line 55 of file MCSection.h.
SectionVariant
enum llvm::MCSection::SectionVariant
Enumerator
SV_COFF
SV_ELF
SV_GOFF
SV_MachO
SV_Wasm
SV_XCOFF
SV_SPIRV
SV_DXContainer
Definition at line 43 of file MCSection.h.
Constructor & Destructor Documentation
MCSection() [1/2]
MCSection::MCSection (SectionVariant V, StringRef Name, SectionKind K, MCSymbol * Begin) protected
Definition at line 23 of file MCSection.cpp.
~MCSection()
MCSection::~MCSection () protected default
MCSection() [2/2]
llvm::MCSection::MCSection (const MCSection &) delete
Member Function Documentation
addPendingLabel()
void MCSection::addPendingLabel (MCSymbol * label, unsigned Subsection = 0)
Add a pending label for the requested subsection.
This label will be associated with a fragment in flushPendingLabels()
Definition at line 91 of file MCSection.cpp.
Referenced by llvm::MCObjectStreamer::addPendingLabel(), and llvm::MCObjectStreamer::flushPendingLabels().
begin() [1/2]
iterator llvm::MCSection::begin () inline
Definition at line 185 of file MCSection.h.
Referenced by dump(), and llvm::MCAssembler::layout().
begin() [2/2]
const_iterator llvm::MCSection::begin () const inline
Definition at line 186 of file MCSection.h.
dump()
LLVM_DUMP_METHOD void MCSection::dump () const
Definition at line 127 of file MCSection.cpp.
References begin(), end(), llvm::errs(), it, and OS.
end() [1/2]
iterator llvm::MCSection::end () inline
Definition at line 188 of file MCSection.h.
Referenced by dump(), and getSubsectionInsertionPoint().
end() [2/2]
const_iterator llvm::MCSection::end () const inline
Definition at line 189 of file MCSection.h.
ensureMinAlignment()
void llvm::MCSection::ensureMinAlignment (Align MinAlignment) inline
Makes sure that Alignment is at least MinAlignment.
Definition at line 144 of file MCSection.h.
Referenced by llvm::MCWinCOFFStreamer::emitCOFFSafeSEH(), llvm::MCWinCOFFStreamer::emitCOFFSymbolIndex(), llvm::MCObjectStreamer::emitValueToAlignment(), and llvm::MipsTargetELFStreamer::finish().
flushPendingLabels() [1/2]
void MCSection::flushPendingLabels ()
Associate all pending labels with empty data fragments.
One fragment will be created for each subsection as necessary.
Definition at line 112 of file MCSection.cpp.
References F, getFragmentList(), getSubsectionInsertionPoint(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::insert().
flushPendingLabels() [2/2]
void MCSection::flushPendingLabels (MCFragment * F, uint64_t FOffset = 0, unsigned Subsection = 0)
Associate all pending labels in a subsection with a fragment.
Definition at line 95 of file MCSection.cpp.
References llvm::SmallVectorImpl< T >::erase(), and F.
Referenced by llvm::MCObjectStreamer::flushPendingLabels().
getAlign()
Align llvm::MCSection::getAlign () const inline
Definition at line 140 of file MCSection.h.
Referenced by addData(), getAlignment(), and llvm::MachObjectWriter::getPaddingSize().
getBeginSymbol() [1/2]
MCSymbol* llvm::MCSection::getBeginSymbol () inline
Definition at line 129 of file MCSection.h.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), llvm::DwarfUnit::addRnglistsBase(), llvm::DwarfCompileUnit::addScopeRangeList(), llvm::DwarfUnit::addStringOffsetsStart(), llvm::DwarfCompileUnit::applyStmtList(), llvm::MCContext::createELFRelSection(), llvm::DwarfUnit::emitCommonHeader(), llvm::MCObjectFileInfo::getBBAddrMapSection(), getBeginSymbol(), llvm::MCObjectFileInfo::getKCFITrapSection(), llvm::MCObjectFileInfo::getPCSection(), llvm::MCObjectFileInfo::getStackSizesSection(), llvm::DwarfCompileUnit::initStmtList(), and llvm::MCDwarfLineStr::MCDwarfLineStr().
getBeginSymbol() [2/2]
const MCSymbol* llvm::MCSection::getBeginSymbol () const inline
Definition at line 130 of file MCSection.h.
References getBeginSymbol().
getBundleLockState()
BundleLockStateType llvm::MCSection::getBundleLockState () const inline
Definition at line 155 of file MCSection.h.
Referenced by llvm::MCELFStreamer::emitBundleUnlock().
getDummyFragment() [1/2]
MCDummyFragment& llvm::MCSection::getDummyFragment () inline
Definition at line 183 of file MCSection.h.
getDummyFragment() [2/2]
const MCDummyFragment& llvm::MCSection::getDummyFragment () const inline
Definition at line 182 of file MCSection.h.
getEndSymbol()
MCSymbol * MCSection::getEndSymbol (MCContext & Ctx)
Definition at line 29 of file MCSection.cpp.
References llvm::MCContext::createTempSymbol().
getFragmentList() [1/2]
MCSection::FragmentListType& llvm::MCSection::getFragmentList () inline
Definition at line 172 of file MCSection.h.
Referenced by flushPendingLabels(), getFragmentList(), llvm::MCAsmLayout::getSectionAddressSize(), getSubsectionInsertionPoint(), llvm::MCObjectStreamer::insert(), llvm::MCAssembler::layout(), llvm::MCFragment::MCFragment(), and llvm::MachObjectWriter::writeObject().
getFragmentList() [2/2]
const MCSection::FragmentListType& llvm::MCSection::getFragmentList () const inline
Definition at line 173 of file MCSection.h.
References getFragmentList().
getKind()
SectionKind llvm::MCSection::getKind () const inline
Definition at line 125 of file MCSection.h.
References Kind.
Referenced by llvm::MCContext::getAssociativeCOFFSection(), llvm::MCSectionXCOFF::printSwitchToSection(), llvm::MCSectionCOFF::useCodeAlign(), and llvm::MCSectionXCOFF::useCodeAlign().
getLayoutOrder()
unsigned llvm::MCSection::getLayoutOrder () const inline
Definition at line 152 of file MCSection.h.
Referenced by llvm::MachObjectWriter::getPaddingSize().
getName()
StringRef llvm::MCSection::getName () const inline
Definition at line 124 of file MCSection.h.
References Name.
Referenced by addData(), llvm::BTFDebug::beginFunctionImpl(), canGoAfterDWARF(), canUseLocalRelocation(), llvm::MCObjectStreamer::emitInstruction(), llvm::MCContext::getAssociativeCOFFSection(), llvm::TargetLoweringObjectFileELF::getSectionForMachineBasicBlock(), llvm::MCAsmInfoDarwin::isSectionAtomizableBySymbols(), llvm::MCSectionGOFF::printSwitchToSection(), llvm::MCSectionWasm::printSwitchToSection(), llvm::MCSectionMachO::printSwitchToSection(), llvm::MCSectionCOFF::printSwitchToSection(), llvm::MCSectionELF::printSwitchToSection(), and llvm::MCSectionXCOFF::printSwitchToSection().
getOrdinal()
unsigned llvm::MCSection::getOrdinal () const inline
Definition at line 149 of file MCSection.h.
getSublistAccess()
static FragmentListType MCSection::* llvm::MCSection::getSublistAccess (MCFragment *) inline static
Support for MCFragment::getNextNode().
Definition at line 178 of file MCSection.h.
getSubsectionInsertionPoint()
MCSection::iterator MCSection::getSubsectionInsertionPoint (unsigned Subsection)
Definition at line 59 of file MCSection.cpp.
References end(), F, getFragmentList(), llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), llvm::lower_bound(), and MI.
Referenced by flushPendingLabels().
getVariant()
SectionVariant llvm::MCSection::getVariant () const inline
Definition at line 127 of file MCSection.h.
References Variant.
getVirtualSectionKind()
StringRef MCSection::getVirtualSectionKind () const virtual
Reimplemented in llvm::MCSectionELF, and llvm::MCSectionCOFF.
Definition at line 89 of file MCSection.cpp.
Referenced by llvm::MCObjectStreamer::emitInstruction().
hasEnded()
bool MCSection::hasEnded () const
Definition at line 35 of file MCSection.cpp.
References llvm::MCSymbol::isInSection().
hasInstructions()
bool llvm::MCSection::hasInstructions () const inline
Definition at line 166 of file MCSection.h.
Referenced by llvm::MCObjectStreamer::mayHaveInstructions().
isBundleGroupBeforeFirstInst()
bool llvm::MCSection::isBundleGroupBeforeFirstInst () const inline
Definition at line 159 of file MCSection.h.
Referenced by llvm::MCELFStreamer::emitBundleUnlock().
isBundleLocked()
bool llvm::MCSection::isBundleLocked () const inline
Definition at line 157 of file MCSection.h.
References NotBundleLocked.
isRegistered()
bool llvm::MCSection::isRegistered () const inline
Definition at line 169 of file MCSection.h.
Referenced by llvm::AArch64TargetStreamer::emitNoteSection().
isVirtualSection()
virtual bool llvm::MCSection::isVirtualSection () const pure virtual
Check whether this section is "virtual", that is has no actual object file contents.
Implemented in llvm::MCSectionXCOFF, llvm::MCSectionELF, llvm::MCSectionCOFF, llvm::MCSectionMachO, llvm::MCSectionWasm, llvm::MCSectionGOFF, llvm::MCSectionSPIRV, and llvm::MCSectionDXContainer.
Referenced by llvm::AsmPrinter::emitGlobalVariable(), llvm::MCObjectStreamer::emitInstruction(), llvm::MachObjectWriter::getPaddingSize(), llvm::MCAsmLayout::getSectionFileSize(), and llvm::MCAssembler::writeSectionData().
operator=()
MCSection& llvm::MCSection::operator= (const MCSection &) delete
printSwitchToSection()
virtual void llvm::MCSection::printSwitchToSection (const MCAsmInfo & MAI, const Triple & T, raw_ostream & OS, const MCExpr * Subsection) const pure virtual
Implemented in llvm::MCSectionXCOFF, llvm::MCSectionELF, llvm::MCSectionCOFF, llvm::MCSectionMachO, llvm::MCSectionWasm, llvm::MCSectionGOFF, llvm::MCSectionSPIRV, and llvm::MCSectionDXContainer.
setAlignment()
void llvm::MCSection::setAlignment (Align Value) inline
Definition at line 141 of file MCSection.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::DwarfStreamer::emitSwiftAST(), and llvm::DwarfStreamer::emitSwiftReflectionSection().
setBeginSymbol()
void llvm::MCSection::setBeginSymbol (MCSymbol * Sym) inline
Definition at line 133 of file MCSection.h.
References assert().
setBundleGroupBeforeFirstInst()
void llvm::MCSection::setBundleGroupBeforeFirstInst (bool IsFirst) inline
Definition at line 162 of file MCSection.h.
Referenced by llvm::MCELFStreamer::emitBundleLock().
setBundleLockState()
void MCSection::setBundleLockState (BundleLockStateType NewState)
Definition at line 39 of file MCSection.cpp.
References BundleLockedAlignToEnd, NotBundleLocked, and llvm::report_fatal_error().
Referenced by llvm::MCELFStreamer::emitBundleLock(), and llvm::MCELFStreamer::emitBundleUnlock().
setHasInstructions()
void llvm::MCSection::setHasInstructions (bool Value) inline
Definition at line 167 of file MCSection.h.
setIsRegistered()
void llvm::MCSection::setIsRegistered (bool Value) inline
Definition at line 170 of file MCSection.h.
setLayoutOrder()
void llvm::MCSection::setLayoutOrder (unsigned Value) inline
Definition at line 153 of file MCSection.h.
Referenced by llvm::MCAssembler::layout().
setOrdinal()
void llvm::MCSection::setOrdinal (unsigned Value) inline
Definition at line 150 of file MCSection.h.
Referenced by llvm::MCAssembler::layout().
useCodeAlign()
virtual bool llvm::MCSection::useCodeAlign () const pure virtual
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
Implemented in llvm::MCSectionXCOFF, llvm::MCSectionELF, llvm::MCSectionCOFF, llvm::MCSectionMachO, llvm::MCSectionWasm, llvm::MCSectionGOFF, llvm::MCSectionSPIRV, and llvm::MCSectionDXContainer.
Referenced by llvm::MCAssembler::computeFragmentSize().
Member Data Documentation
Kind
SectionKind llvm::MCSection::Kind protected
Definition at line 115 of file MCSection.h.
Referenced by getKind(), and llvm::MCSectionWasm::isWasmData().
Name
StringRef llvm::MCSection::Name protected
Definition at line 113 of file MCSection.h.
Referenced by getName(), llvm::MCSectionCOFF::isImplicitlyDiscardable(), llvm::MCSectionWasm::shouldOmitSectionDirective(), llvm::MCSectionCOFF::shouldOmitSectionDirective(), and llvm::MCSectionELF::shouldOmitSectionDirective().
NonUniqueID
constexpr unsigned llvm::MCSection::NonUniqueID = ~0U static constexpr
Definition at line 41 of file MCSection.h.
Referenced by llvm::MCContext::createELFGroupSection(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::AsmPrinter::emitXRayTable(), llvm::MCContext::getELFSection(), llvm::TargetLoweringObjectFileELF::getSectionForLSDA(), and llvm::MCSectionELF::isUnique().
Variant
SectionVariant llvm::MCSection::Variant protected
Definition at line 114 of file MCSection.h.
Referenced by getVariant().
The documentation for this class was generated from the following files:
include/llvm/MC/MCSection.h
lib/MC/MCSection.cpp