LLVM: llvm::detail::enumerator< R > Class Template Reference
llvm::detail::enumerator< R > Class Template Reference
#include "llvm/ADT/STLExtras.h"
Public Member Functions
enumerator (R &&Range)
enumerator_iter< R > begin ()
enumerator_iter< R > begin () const
enumerator_iter< R > end ()
enumerator_iter< R > end () const
Detailed Description
template<typename R>
class llvm::detail::enumerator< R >
Definition at line 2219 of file STLExtras.h.
Constructor & Destructor Documentation
enumerator()
template<typename R > llvm::detail::enumerator< R >::enumerator (R && Range) inline explicit
Definition at line 2221 of file STLExtras.h.
Member Function Documentation
begin() [1/2]
template<typename R > enumerator_iter<R> llvm::detail::enumerator< R >::begin () inline
Definition at line 2223 of file STLExtras.h.
References llvm::sys::path::begin().
begin() [2/2]
template<typename R > enumerator_iter<R> llvm::detail::enumerator< R >::begin () const inline
Definition at line 2226 of file STLExtras.h.
References llvm::sys::path::begin().
end() [1/2]
template<typename R > enumerator_iter<R> llvm::detail::enumerator< R >::end () inline
Definition at line 2230 of file STLExtras.h.
References llvm::sys::path::end().
end() [2/2]
template<typename R > enumerator_iter<R> llvm::detail::enumerator< R >::end () const inline
Definition at line 2233 of file STLExtras.h.
References llvm::sys::path::end().
The documentation for this class was generated from the following file:
include/llvm/ADT/STLExtras.h