LLVM: llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > Class Template Reference
llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > Class Template Reference
The class represents the base of a range of indexed_accessor_iterators.
#include "llvm/ADT/STLExtras.h"
Classes
class iterator
An iterator element of this range.
Public Types
using RangeBaseT = indexed_accessor_range_base
Public Member Functions
indexed_accessor_range_base (iterator begin, iterator end)
indexed_accessor_range_base (const iterator_range< iterator > &range)
indexed_accessor_range_base (BaseT base, ptrdiff_t count)
iterator begin () const
iterator end () const
ReferenceT operator[] (size_t Index) const
ReferenceT front () const
ReferenceT back () const
size_t size () const
Return the size of this range.
bool empty () const
Return if the range is empty.
DerivedT slice (size_t n, size_t m) const
Drop the first N elements, and keep M elements.
DerivedT drop_front (size_t n=1) const
Drop the first n elements.
DerivedT drop_back (size_t n=1) const
Drop the last n elements.
DerivedT take_front (size_t n=1) const
Take the first n elements.
DerivedT take_back (size_t n=1) const
Take the last n elements.
template<typename RangeT , typename = std::enable_if_t<std::is_constructible< RangeT, iterator_range<iterator>>::value>>
operator RangeT () const
Allow conversion to any type accepting an iterator_range.
const BaseT & getBase () const
Returns the base of this range.
Protected Member Functions
indexed_accessor_range_base (const indexed_accessor_range_base &)=default
indexed_accessor_range_base (indexed_accessor_range_base &&)=default
indexed_accessor_range_base & operator= (const indexed_accessor_range_base &)=default
Protected Attributes
BaseT base
The base that owns the provided range of values.
ptrdiff_t count
The size from the owning range.
Friends
template<typename OtherT >
bool operator== (const indexed_accessor_range_base &lhs, const OtherT &rhs)
Compare this range with another.
template<typename OtherT >
bool operator!= (const indexed_accessor_range_base &lhs, const OtherT &rhs)
Detailed Description
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &>
class llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >
The class represents the base of a range of indexed_accessor_iterators.
It provides support for many different range functionalities, e.g. drop_front/slice/etc.. Derived range classes must implement the following static methods:
ReferenceT dereference_iterator(const BaseT &base, ptrdiff_t index)
Dereference an iterator pointing to the base object at the given index.
BaseT offset_base(const BaseT &base, ptrdiff_t index)
Return a new base that is offset from the provide base by 'index' elements.
Definition at line 1272 of file STLExtras.h.
Member Typedef Documentation
RangeBaseT
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> using llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::RangeBaseT = indexed_accessor_range_base
Definition at line 1274 of file STLExtras.h.
Constructor & Destructor Documentation
indexed_accessor_range_base() [1/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (iterator begin, iterator end) inline
Definition at line 1294 of file STLExtras.h.
indexed_accessor_range_base() [2/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (const iterator_range< iterator > & range) inline
Definition at line 1297 of file STLExtras.h.
indexed_accessor_range_base() [3/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (BaseT base, ptrdiff_t count) inline
Definition at line 1299 of file STLExtras.h.
indexed_accessor_range_base() [4/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &) protected default
indexed_accessor_range_base() [5/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &&) protected default
Member Function Documentation
back()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> ReferenceT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::back () const inline
Definition at line 1312 of file STLExtras.h.
begin()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> iterator llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin () const inline
Definition at line 1302 of file STLExtras.h.
drop_back()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_back (size_t n = 1) const inline
Drop the last n elements.
Definition at line 1347 of file STLExtras.h.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::take_front().
drop_front()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front (size_t n = 1) const inline
Drop the first n elements.
Definition at line 1342 of file STLExtras.h.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::take_back().
empty()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> bool llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::empty () const inline
Return if the range is empty.
Definition at line 1333 of file STLExtras.h.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::back(), and llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::front().
end()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> iterator llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::end () const inline
Definition at line 1303 of file STLExtras.h.
front()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> ReferenceT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::front () const inline
Definition at line 1308 of file STLExtras.h.
getBase()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> const BaseT& llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::getBase () const inline
Returns the base of this range.
Definition at line 1372 of file STLExtras.h.
operator RangeT()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> template<typename RangeT , typename = std::enable_if_t<std::is_constructible< RangeT, iterator_range<iterator>>::value>> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator RangeT () const inline
Allow conversion to any type accepting an iterator_range.
Definition at line 1367 of file STLExtras.h.
operator=()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> indexed_accessor_range_base& llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator= (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &) protected default
operator[]()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> ReferenceT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator[] (size_t Index) const inline
Definition at line 1304 of file STLExtras.h.
size()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> size_t llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size () const inline
Return the size of this range.
Definition at line 1330 of file STLExtras.h.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::back(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::drop_back(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::drop_front(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::empty(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::operator[](), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::slice(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::take_back(), and llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::take_front().
slice()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::slice (size_t n, size_t m) const inline
Drop the first N elements, and keep M elements.
Definition at line 1336 of file STLExtras.h.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::drop_front().
take_back()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_back (size_t n = 1) const inline
Take the last n elements.
Definition at line 1359 of file STLExtras.h.
take_front()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_front (size_t n = 1) const inline
Take the first n elements.
Definition at line 1353 of file STLExtras.h.
Friends And Related Function Documentation
operator!=
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> template<typename OtherT > bool operator!= (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > & lhs, const OtherT & rhs) friend
Definition at line 1324 of file STLExtras.h.
operator==
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> template<typename OtherT > bool operator== (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > & lhs, const OtherT & rhs) friend
Compare this range with another.
Definition at line 1319 of file STLExtras.h.
Member Data Documentation
base
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> BaseT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::base protected
The base that owns the provided range of values.
Definition at line 1387 of file STLExtras.h.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::begin(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::drop_back(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::end(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::getBase(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::operator[](), and llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::slice().
count
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> ptrdiff_t llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::count protected
The size from the owning range.
Definition at line 1389 of file STLExtras.h.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::end(), and llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::size().
The documentation for this class was generated from the following file:
include/llvm/ADT/STLExtras.h