LLVM: llvm::OptPassGateInstrumentation Class Reference
llvm::OptPassGateInstrumentation Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
OptPassGateInstrumentation (LLVMContext &Context)
bool shouldRun (StringRef PassName, Any IR)
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Detailed Description
Definition at line 77 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
OptPassGateInstrumentation()
llvm::OptPassGateInstrumentation::OptPassGateInstrumentation (LLVMContext & Context) inline
Definition at line 81 of file StandardInstrumentations.h.
References Context.
Member Function Documentation
registerCallbacks()
void OptPassGateInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 831 of file StandardInstrumentations.cpp.
References llvm::LLVMContext::getOptPassGate(), IR, llvm::OptPassGate::isEnabled(), PassName, PIC, llvm::PassInstrumentationCallbacks::registerShouldRunOptionalPassCallback(), and shouldRun().
shouldRun()
bool OptPassGateInstrumentation::shouldRun (StringRef PassName, Any IR)
Definition at line 810 of file StandardInstrumentations.cpp.
References assert(), llvm::errorCodeToError(), llvm::LLVMContext::getOptPassGate(), IR, M, OptBisectPrintIRPath, OS, PassName, llvm::report_fatal_error(), and llvm::OptPassGate::shouldRunPass().
Referenced by registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp