LLVM: llvm::ValueLatticeElement Class Reference
llvm::ValueLatticeElement Class Reference
This class represents lattice values for constants.
#include "llvm/Analysis/ValueLattice.h"
Classes
struct MergeOptions
Struct to control some aspects related to merging constant ranges.
Public Member Functions
ValueLatticeElement ()
~ValueLatticeElement ()
ValueLatticeElement (const ValueLatticeElement &Other)
ValueLatticeElement (ValueLatticeElement &&Other)
ValueLatticeElement & operator= (const ValueLatticeElement &Other)
ValueLatticeElement & operator= (ValueLatticeElement &&Other)
bool isUndef () const
bool isUnknown () const
bool isUnknownOrUndef () const
bool isConstant () const
bool isNotConstant () const
bool isConstantRangeIncludingUndef () const
bool isConstantRange (bool UndefAllowed=true) const
Returns true if this value is a constant range.
bool isOverdefined () const
Constant * getConstant () const
Constant * getNotConstant () const
const ConstantRange & getConstantRange (bool UndefAllowed=true) const
Returns the constant range for this value.
std::optional< APInt > asConstantInteger () const
bool markOverdefined ()
bool markUndef ()
bool markConstant (Constant *V, bool MayIncludeUndef=false)
bool markNotConstant (Constant *V)
bool markConstantRange (ConstantRange NewR, MergeOptions Opts=MergeOptions())
Mark the object as constant range with NewR.
bool mergeIn (const ValueLatticeElement &RHS, MergeOptions Opts=MergeOptions())
Updates this object to approximate both this object and RHS.
Constant * getCompare (CmpInst::Predicate Pred, Type *Ty, const ValueLatticeElement &Other, const DataLayout &DL) const
true, false or undef constants, or nullptr if the comparison cannot be evaluated.
unsigned getNumRangeExtensions () const
void setNumRangeExtensions (unsigned N)
Static Public Member Functions
static ValueLatticeElement get (Constant *C)
static ValueLatticeElement getNot (Constant *C)
static ValueLatticeElement getRange (ConstantRange CR, bool MayIncludeUndef=false)
static ValueLatticeElement getOverdefined ()
Detailed Description
This class represents lattice values for constants.
FIXME: This is basically just for bringup, this can be made a lot more rich in the future.
Definition at line 29 of file ValueLattice.h.
Constructor & Destructor Documentation
ValueLatticeElement() [1/3]
llvm::ValueLatticeElement::ValueLatticeElement () inline
Definition at line 148 of file ValueLattice.h.
Referenced by operator=().
~ValueLatticeElement()
llvm::ValueLatticeElement::~ValueLatticeElement () inline
Definition at line 150 of file ValueLattice.h.
ValueLatticeElement() [2/3]
llvm::ValueLatticeElement::ValueLatticeElement (const ValueLatticeElement & Other) inline
Definition at line 152 of file ValueLattice.h.
References ConstVal, Other, and Range.
ValueLatticeElement() [3/3]
llvm::ValueLatticeElement::ValueLatticeElement (ValueLatticeElement && Other) inline
Definition at line 171 of file ValueLattice.h.
References ConstVal, move, Other, and Range.
Member Function Documentation
asConstantInteger()
std::optional<APInt> llvm::ValueLatticeElement::asConstantInteger () const inline
Definition at line 278 of file ValueLattice.h.
References getConstant(), getConstantRange(), llvm::ConstantRange::getSingleElement(), isConstant(), and isConstantRange().
Referenced by getEdgeValueLocal().
get()
static ValueLatticeElement llvm::ValueLatticeElement::get (Constant * C) inline static
Definition at line 203 of file ValueLattice.h.
References markConstant(), and markUndef().
Referenced by getEdgeValueLocal(), and getValueFromICmpCondition().
getCompare()
Constant * llvm::ValueLatticeElement::getCompare (CmpInst::Predicate Pred, Type * Ty, const ValueLatticeElement & Other, const DataLayout & DL) const
true, false or undef constants, or nullptr if the comparison cannot be evaluated.
Definition at line 14 of file ValueLattice.cpp.
References llvm::ConstantFoldCompareInstOperands(), DL, getConstant(), getConstantRange(), llvm::ConstantInt::getFalse(), llvm::CmpInst::getInversePredicate(), getNotConstant(), llvm::ConstantInt::getTrue(), llvm::CmpInst::ICMP_NE, isConstant(), isConstantRange(), llvm::ICmpInst::isEquality(), isNotConstant(), isUndef(), isUnknown(), and Other.
Referenced by llvm::LazyValueInfo::getPredicateAt().
getConstant()
Constant* llvm::ValueLatticeElement::getConstant () const inline
Definition at line 258 of file ValueLattice.h.
References assert(), ConstVal, and isConstant().
Referenced by asConstantInteger(), getCompare(), llvm::SCCPInstVisitor::getConstant(), getPredicateResult(), markConstant(), mergeIn(), and llvm::operator<<().
getConstantRange()
const ConstantRange& llvm::ValueLatticeElement::getConstantRange (bool UndefAllowed = true) const inline
Returns the constant range for this value.
Use UndefAllowed to exclude non-singleton constant ranges that may also be undef. Note that this function also returns a range if the range may include undef, but only contains a single element. In that case, it can be replaced by a constant.
Definition at line 272 of file ValueLattice.h.
References assert(), isConstantRange(), and Range.
Referenced by asConstantInteger(), getCompare(), llvm::SCCPInstVisitor::getConstant(), getConstantRange(), getConstantRangeOrFull(), getEdgeValueLocal(), getPredicateResult(), hasSingleValue(), llvm::SCCPSolver::isConstant(), markConstantRange(), mergeIn(), llvm::operator<<(), and runIPSCCP().
getNot()
static ValueLatticeElement llvm::ValueLatticeElement::getNot (Constant * C) inline static
Definition at line 211 of file ValueLattice.h.
References assert(), and markNotConstant().
Referenced by getValueFromICmpCondition(), and getValueFromMetadata().
getNotConstant()
Constant* llvm::ValueLatticeElement::getNotConstant () const inline
Definition at line 263 of file ValueLattice.h.
References assert(), ConstVal, and isNotConstant().
Referenced by getCompare(), getPredicateResult(), markNotConstant(), mergeIn(), and llvm::operator<<().
getNumRangeExtensions()
unsigned llvm::ValueLatticeElement::getNumRangeExtensions () const inline
Definition at line 458 of file ValueLattice.h.
getOverdefined()
static ValueLatticeElement llvm::ValueLatticeElement::getOverdefined () inline static
Definition at line 234 of file ValueLattice.h.
References markOverdefined().
Referenced by constantFoldUser(), getFromRangeMetadata(), getRange(), getValueFromCondition(), getValueFromConditionImpl(), getValueFromICmpCondition(), getValueFromMetadata(), and getValueFromOverflowCondition().
getRange()
static ValueLatticeElement llvm::ValueLatticeElement::getRange (ConstantRange CR, bool MayIncludeUndef = false) inline static
Definition at line 217 of file ValueLattice.h.
References getOverdefined(), llvm::ConstantRange::isEmptySet(), llvm::ConstantRange::isFullSet(), markConstantRange(), markUndef(), and move.
Referenced by constantFoldUser(), getEdgeValueLocal(), getFromRangeMetadata(), getValueFromICmpCondition(), getValueFromMetadata(), getValueFromOverflowCondition(), getValueFromSimpleICmpCondition(), and intersect().
isConstant()
bool llvm::ValueLatticeElement::isConstant () const inline
Definition at line 243 of file ValueLattice.h.
Referenced by asConstantInteger(), getCompare(), getConstant(), llvm::SCCPInstVisitor::getConstant(), getPredicateResult(), hasSingleValue(), llvm::SCCPSolver::isConstant(), markConstant(), and mergeIn().
isConstantRange()
bool llvm::ValueLatticeElement::isConstantRange (bool UndefAllowed = true) const inline
Returns true if this value is a constant range.
Use UndefAllowed to exclude non-singleton constant ranges that may also be undef. Note that this function also returns true if the range may include undef, but only contains a single element. In that case, it can be replaced by a constant.
Definition at line 252 of file ValueLattice.h.
References llvm::ConstantRange::isSingleElement(), and Range.
Referenced by asConstantInteger(), getCompare(), llvm::SCCPInstVisitor::getConstant(), getConstantRange(), getConstantRange(), getConstantRangeOrFull(), getPredicateResult(), hasSingleValue(), llvm::SCCPSolver::isConstant(), markConstantRange(), mergeIn(), llvm::operator<<(), and runIPSCCP().
isConstantRangeIncludingUndef()
bool llvm::ValueLatticeElement::isConstantRangeIncludingUndef () const inline
Definition at line 245 of file ValueLattice.h.
Referenced by markConstantRange(), llvm::operator<<(), and runIPSCCP().
isNotConstant()
bool llvm::ValueLatticeElement::isNotConstant () const inline
Definition at line 244 of file ValueLattice.h.
Referenced by getCompare(), getNotConstant(), getPredicateResult(), markNotConstant(), mergeIn(), and llvm::operator<<().
isOverdefined()
bool llvm::ValueLatticeElement::isOverdefined () const inline
Definition at line 256 of file ValueLattice.h.
Referenced by getEdgeValueLocal(), llvm::LazyValueInfo::getPredicateAt(), getValueFromConditionImpl(), markOverdefined(), mergeIn(), and llvm::operator<<().
isUndef()
bool llvm::ValueLatticeElement::isUndef () const inline
Definition at line 240 of file ValueLattice.h.
Referenced by getCompare(), markConstant(), markConstantRange(), markUndef(), mergeIn(), and llvm::operator<<().
isUnknown()
bool llvm::ValueLatticeElement::isUnknown () const inline
Definition at line 241 of file ValueLattice.h.
Referenced by getCompare(), markConstant(), markConstantRange(), markNotConstant(), markUndef(), mergeIn(), llvm::operator<<(), and llvm::SCCPInstVisitor::resolvedUndefsIn().
isUnknownOrUndef()
bool llvm::ValueLatticeElement::isUnknownOrUndef () const inline
Definition at line 242 of file ValueLattice.h.
Referenced by llvm::SCCPSolver::isOverdefined(), and runIPSCCP().
markConstant()
bool llvm::ValueLatticeElement::markConstant (Constant * V, bool MayIncludeUndef = false) inline
Definition at line 304 of file ValueLattice.h.
References assert(), ConstVal, getConstant(), isConstant(), isUndef(), isUnknown(), markConstantRange(), and markUndef().
Referenced by get(), and mergeIn().
markConstantRange()
bool llvm::ValueLatticeElement::markConstantRange (ConstantRange NewR, MergeOptions Opts = MergeOptions()) inline
Mark the object as constant range with NewR.
If the object is already a constant range, nothing changes if the existing range is equal to NewR and the tag. Otherwise NewR must be a superset of the existing range or the object must be undef. The tag is set to constant_range_including_undef if either the existing value or the new range may include undef.
Definition at line 350 of file ValueLattice.h.
References assert(), llvm::ConstantRange::contains(), getConstantRange(), isConstantRange(), isConstantRangeIncludingUndef(), llvm::ConstantRange::isEmptySet(), llvm::ConstantRange::isFullSet(), isUndef(), isUnknown(), markOverdefined(), move, and Range.
Referenced by getRange(), markConstant(), markNotConstant(), and mergeIn().
markNotConstant()
bool llvm::ValueLatticeElement::markNotConstant (Constant * V) inline
Definition at line 324 of file ValueLattice.h.
References assert(), ConstVal, getNotConstant(), isNotConstant(), isUnknown(), and markConstantRange().
Referenced by getNot().
markOverdefined()
bool llvm::ValueLatticeElement::markOverdefined () inline
Definition at line 287 of file ValueLattice.h.
References isOverdefined().
Referenced by getOverdefined(), markConstantRange(), and mergeIn().
markUndef()
bool llvm::ValueLatticeElement::markUndef () inline
Definition at line 295 of file ValueLattice.h.
References assert(), isUndef(), and isUnknown().
Referenced by get(), getRange(), and markConstant().
mergeIn()
bool llvm::ValueLatticeElement::mergeIn (const ValueLatticeElement & RHS, MergeOptions Opts = MergeOptions()) inline
Updates this object to approximate both this object and RHS.
Returns true if this object has been changed.
Definition at line 388 of file ValueLattice.h.
References assert(), getConstant(), getConstantRange(), getNotConstant(), isConstant(), isConstantRange(), isNotConstant(), isOverdefined(), isUndef(), isUnknown(), markConstant(), markConstantRange(), markOverdefined(), move, RHS, and llvm::ConstantRange::unionWith().
Referenced by getValueFromConditionImpl().
operator=() [1/2]
ValueLatticeElement& llvm::ValueLatticeElement::operator= (const ValueLatticeElement & Other) inline
Definition at line 191 of file ValueLattice.h.
References Other, and ValueLatticeElement().
operator=() [2/2]
ValueLatticeElement& llvm::ValueLatticeElement::operator= (ValueLatticeElement && Other) inline
Definition at line 197 of file ValueLattice.h.
References move, Other, and ValueLatticeElement().
setNumRangeExtensions()
void llvm::ValueLatticeElement::setNumRangeExtensions (unsigned N) inline
Definition at line 459 of file ValueLattice.h.
References N.
Member Data Documentation
ConstVal
Constant* llvm::ValueLatticeElement::ConstVal
Definition at line 89 of file ValueLattice.h.
Referenced by getConstant(), getNotConstant(), markConstant(), markNotConstant(), and ValueLatticeElement().
Range
ConstantRange llvm::ValueLatticeElement::Range
Definition at line 90 of file ValueLattice.h.
Referenced by getConstantRange(), isConstantRange(), markConstantRange(), and ValueLatticeElement().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ValueLattice.h
lib/Analysis/ValueLattice.cpp