LLVM: llvm::LoopRotatePass Class Reference
llvm::LoopRotatePass Class Reference
A simple loop rotation transformation.
#include "llvm/Transforms/Scalar/LoopRotation.h"
Public Member Functions
LoopRotatePass (bool EnableHeaderDuplication=true, bool PrepareForLTO=false)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Public Member Functions inherited from llvm::PassInfoMixin< LoopRotatePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopRotatePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A simple loop rotation transformation.
Definition at line 24 of file LoopRotation.h.
Constructor & Destructor Documentation
LoopRotatePass()
LoopRotatePass::LoopRotatePass (bool EnableHeaderDuplication = true, bool PrepareForLTO = false)
Definition at line 42 of file LoopRotation.cpp.
Member Function Documentation
run()
PreservedAnalyses LoopRotatePass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 46 of file LoopRotation.cpp.
References llvm::LoopStandardAnalysisResults::AC, llvm::PreservedAnalyses::all(), DefaultRotationThreshold, DL, llvm::LoopStandardAnalysisResults::DT, llvm::getBestSimplifyQuery(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getLoopPassPreservedAnalyses(), llvm::BasicBlock::getModule(), llvm::hasVectorizeTransformation(), llvm::LoopStandardAnalysisResults::LI, llvm::LoopRotation(), llvm::LoopStandardAnalysisResults::MSSA, PrepareForLTOOption, llvm::LoopStandardAnalysisResults::SE, llvm::TM_ForcedByUser, llvm::LoopStandardAnalysisResults::TTI, llvm::MemorySSA::verifyMemorySSA(), and llvm::VerifyMemorySSA.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopRotation.h
lib/Transforms/Scalar/LoopRotation.cpp