LLVM: llvm::M68kMachineFunctionInfo Class Reference
llvm::M68kMachineFunctionInfo Class Reference
#include "Target/M68k/M68kMachineFunction.h"
Public Member Functions
M68kMachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
bool getRestoreBasePointer () const
void setRestoreBasePointer (const MachineFunction *MF)
int getRestoreBasePointerOffset () const
unsigned getCalleeSavedFrameSize () const
void setCalleeSavedFrameSize (unsigned bytes)
unsigned getBytesToPopOnReturn () const
void setBytesToPopOnReturn (unsigned bytes)
int getRAIndex () const
void setRAIndex (int Index)
int getTCReturnAddrDelta () const
void setTCReturnAddrDelta (int delta)
unsigned getGlobalBaseReg () const
void setGlobalBaseReg (unsigned Reg)
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
bool getHasPushSequences () const
void setHasPushSequences (bool HasPush)
unsigned getSRetReturnReg () const
void setSRetReturnReg (unsigned Reg)
unsigned getArgumentStackSize () const
void setArgumentStackSize (unsigned size)
SmallVectorImpl< ForwardedRegister > & getForwardedMustTailRegParms ()
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
Definition at line 23 of file M68kMachineFunction.h.
Constructor & Destructor Documentation
M68kMachineFunctionInfo()
llvm::M68kMachineFunctionInfo::M68kMachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline explicit
Definition at line 69 of file M68kMachineFunction.h.
Member Function Documentation
clone()
MachineFunctionInfo * M68kMachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 22 of file M68kMachineFunction.cpp.
References llvm::MachineFunction::cloneInfo().
getArgumentStackSize()
unsigned llvm::M68kMachineFunctionInfo::getArgumentStackSize () const inline
Definition at line 105 of file M68kMachineFunction.h.
getBytesToPopOnReturn()
unsigned llvm::M68kMachineFunctionInfo::getBytesToPopOnReturn () const inline
Definition at line 84 of file M68kMachineFunction.h.
getCalleeSavedFrameSize()
unsigned llvm::M68kMachineFunctionInfo::getCalleeSavedFrameSize () const inline
Definition at line 81 of file M68kMachineFunction.h.
Referenced by llvm::M68kFrameLowering::emitEpilogue(), and llvm::M68kFrameLowering::emitPrologue().
getForwardedMustTailRegParms()
SmallVectorImpl<ForwardedRegister>& llvm::M68kMachineFunctionInfo::getForwardedMustTailRegParms () inline
Definition at line 108 of file M68kMachineFunction.h.
getGlobalBaseReg()
unsigned llvm::M68kMachineFunctionInfo::getGlobalBaseReg () const inline
Definition at line 93 of file M68kMachineFunction.h.
Referenced by llvm::M68kInstrInfo::getGlobalBaseReg().
getHasPushSequences()
bool llvm::M68kMachineFunctionInfo::getHasPushSequences () const inline
Definition at line 99 of file M68kMachineFunction.h.
Referenced by llvm::M68kFrameLowering::eliminateCallFramePseudoInstr().
getRAIndex()
int llvm::M68kMachineFunctionInfo::getRAIndex () const inline
Definition at line 87 of file M68kMachineFunction.h.
getRestoreBasePointer()
bool llvm::M68kMachineFunctionInfo::getRestoreBasePointer () const inline
Definition at line 77 of file M68kMachineFunction.h.
Referenced by llvm::M68kFrameLowering::emitPrologue().
getRestoreBasePointerOffset()
int llvm::M68kMachineFunctionInfo::getRestoreBasePointerOffset () const inline
Definition at line 79 of file M68kMachineFunction.h.
Referenced by llvm::M68kFrameLowering::emitPrologue().
getSRetReturnReg()
unsigned llvm::M68kMachineFunctionInfo::getSRetReturnReg () const inline
Definition at line 102 of file M68kMachineFunction.h.
getTCReturnAddrDelta()
int llvm::M68kMachineFunctionInfo::getTCReturnAddrDelta () const inline
Definition at line 90 of file M68kMachineFunction.h.
Referenced by llvm::M68kFrameLowering::assignCalleeSavedSpillSlots(), llvm::M68kFrameLowering::determineCalleeSaves(), llvm::M68kFrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitPrologue(), and llvm::M68kFrameLowering::getFrameIndexReference().
getVarArgsFrameIndex()
int llvm::M68kMachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 96 of file M68kMachineFunction.h.
setArgumentStackSize()
void llvm::M68kMachineFunctionInfo::setArgumentStackSize (unsigned size) inline
Definition at line 106 of file M68kMachineFunction.h.
References llvm::size().
setBytesToPopOnReturn()
void llvm::M68kMachineFunctionInfo::setBytesToPopOnReturn (unsigned bytes) inline
Definition at line 85 of file M68kMachineFunction.h.
setCalleeSavedFrameSize()
void llvm::M68kMachineFunctionInfo::setCalleeSavedFrameSize (unsigned bytes) inline
Definition at line 82 of file M68kMachineFunction.h.
Referenced by llvm::M68kFrameLowering::emitPrologue().
setGlobalBaseReg()
void llvm::M68kMachineFunctionInfo::setGlobalBaseReg (unsigned Reg) inline
Definition at line 94 of file M68kMachineFunction.h.
Referenced by llvm::M68kInstrInfo::getGlobalBaseReg().
setHasPushSequences()
void llvm::M68kMachineFunctionInfo::setHasPushSequences (bool HasPush) inline
Definition at line 100 of file M68kMachineFunction.h.
setRAIndex()
void llvm::M68kMachineFunctionInfo::setRAIndex (int Index) inline
Definition at line 88 of file M68kMachineFunction.h.
References Index.
setRestoreBasePointer()
void llvm::M68kMachineFunctionInfo::setRestoreBasePointer (const MachineFunction * MF)
setSRetReturnReg()
void llvm::M68kMachineFunctionInfo::setSRetReturnReg (unsigned Reg) inline
Definition at line 103 of file M68kMachineFunction.h.
setTCReturnAddrDelta()
void llvm::M68kMachineFunctionInfo::setTCReturnAddrDelta (int delta) inline
Definition at line 91 of file M68kMachineFunction.h.
setVarArgsFrameIndex()
void llvm::M68kMachineFunctionInfo::setVarArgsFrameIndex (int Index) inline
Definition at line 97 of file M68kMachineFunction.h.
References Index.
The documentation for this class was generated from the following files:
lib/Target/M68k/M68kMachineFunction.h
lib/Target/M68k/M68kMachineFunction.cpp