LLVM: llvm::logicalview::LVOptions Class Reference
llvm::logicalview::LVOptions Class Reference
#include "llvm/DebugInfo/LogicalView/Core/LVOptions.h"
Public Member Functions
void resetFilenameIndex ()
bool changeFilenameIndex (size_t Index)
LVOptions ()=default
LVOptions (const LVOptions &)=default
LVOptions & operator= (const LVOptions &)=default
~LVOptions ()=default
void resolveDependencies ()
size_t indentationSize () const
ATTRIBUTE_OPTION (All)
ATTRIBUTE_OPTION (Argument)
ATTRIBUTE_OPTION (Base)
ATTRIBUTE_OPTION (Coverage)
ATTRIBUTE_OPTION (Directories)
ATTRIBUTE_OPTION (Discarded)
ATTRIBUTE_OPTION (Discriminator)
ATTRIBUTE_OPTION (Encoded)
ATTRIBUTE_OPTION (Extended)
ATTRIBUTE_OPTION (Filename)
ATTRIBUTE_OPTION (Files)
ATTRIBUTE_OPTION (Format)
ATTRIBUTE_OPTION (Gaps)
ATTRIBUTE_OPTION (Generated)
ATTRIBUTE_OPTION (Global)
ATTRIBUTE_OPTION (Inserted)
ATTRIBUTE_OPTION (Level)
ATTRIBUTE_OPTION (Linkage)
ATTRIBUTE_OPTION (Location)
ATTRIBUTE_OPTION (Local)
ATTRIBUTE_OPTION (Offset)
ATTRIBUTE_OPTION (Pathname)
ATTRIBUTE_OPTION (Producer)
ATTRIBUTE_OPTION (Publics)
ATTRIBUTE_OPTION (Qualified)
ATTRIBUTE_OPTION (Qualifier)
ATTRIBUTE_OPTION (Range)
ATTRIBUTE_OPTION (Reference)
ATTRIBUTE_OPTION (Register)
ATTRIBUTE_OPTION (Standard)
ATTRIBUTE_OPTION (Subrange)
ATTRIBUTE_OPTION (System)
ATTRIBUTE_OPTION (Typename)
ATTRIBUTE_OPTION (Underlying)
ATTRIBUTE_OPTION (Zero)
BOOL_FUNCTION (Attribute, Added)
BOOL_FUNCTION (Attribute, AnyLocation)
BOOL_FUNCTION (Attribute, AnySource)
BOOL_FUNCTION (Attribute, Missing)
COMPARE_OPTION (All)
COMPARE_OPTION (Lines)
COMPARE_OPTION (Scopes)
COMPARE_OPTION (Symbols)
COMPARE_OPTION (Types)
BOOL_FUNCTION (Compare, Context)
BOOL_FUNCTION (Compare, Execute)
BOOL_FUNCTION (Compare, Print)
OUTPUT_OPTION (All)
OUTPUT_OPTION (Split)
OUTPUT_OPTION (Text)
OUTPUT_OPTION (Json)
STD_STRING_FUNCTION (Output, Folder)
UNSIGNED_FUNCTION (Output, Level)
LVSortMode getSortMode () const
void setSortMode (LVSortMode SortMode)
PRINT_OPTION (All)
PRINT_OPTION (Elements)
PRINT_OPTION (Instructions)
PRINT_OPTION (Lines)
PRINT_OPTION (Scopes)
PRINT_OPTION (Sizes)
PRINT_OPTION (Symbols)
PRINT_OPTION (Summary)
PRINT_OPTION (Types)
PRINT_OPTION (Warnings)
BOOL_FUNCTION (Print, AnyElement)
BOOL_FUNCTION (Print, AnyLine)
BOOL_FUNCTION (Print, Execute)
BOOL_FUNCTION (Print, Formatting)
BOOL_FUNCTION (Print, Offset)
BOOL_FUNCTION (Print, SizesSummary)
REPORT_OPTION (All)
REPORT_OPTION (Children)
REPORT_OPTION (List)
REPORT_OPTION (Parents)
REPORT_OPTION (View)
BOOL_FUNCTION (Report, AnyView)
BOOL_FUNCTION (Report, Execute)
BOOL_FUNCTION (Select, IgnoreCase)
BOOL_FUNCTION (Select, UseRegex)
BOOL_FUNCTION (Select, Execute)
BOOL_FUNCTION (Select, GenericKind)
BOOL_FUNCTION (Select, GenericPattern)
BOOL_FUNCTION (Select, OffsetPattern)
WARNING_OPTION (All)
WARNING_OPTION (Coverages)
WARNING_OPTION (Lines)
WARNING_OPTION (Locations)
WARNING_OPTION (Ranges)
INTERNAL_OPTION (All)
INTERNAL_OPTION (Cmdline)
INTERNAL_OPTION (ID)
INTERNAL_OPTION (Integrity)
INTERNAL_OPTION (None)
INTERNAL_OPTION (Tag)
BOOL_FUNCTION (General, CollectRanges)
void print (raw_ostream &OS) const
void dump () const
Static Public Member Functions
static LVOptions * getOptions ()
static void setOptions (LVOptions *Options)
Public Attributes
LVAttribute Attribute
LVCompare Compare
LVOutput Output
LVPrint Print
LVReport Report
LVSelect Select
LVWarning Warning
LVInternal Internal
LVGeneral General
Detailed Description
Definition at line 197 of file LVOptions.h.
Constructor & Destructor Documentation
LVOptions() [1/2]
llvm::logicalview::LVOptions::LVOptions () default
LVOptions() [2/2]
llvm::logicalview::LVOptions::LVOptions (const LVOptions &) default
~LVOptions()
llvm::logicalview::LVOptions::~LVOptions () default
Member Function Documentation
ATTRIBUTE_OPTION() [1/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (All)
ATTRIBUTE_OPTION() [2/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Argument)
ATTRIBUTE_OPTION() [3/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Base)
ATTRIBUTE_OPTION() [4/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Coverage)
ATTRIBUTE_OPTION() [5/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Directories)
ATTRIBUTE_OPTION() [6/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Discarded)
ATTRIBUTE_OPTION() [7/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Discriminator)
ATTRIBUTE_OPTION() [8/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Encoded)
ATTRIBUTE_OPTION() [9/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Extended)
ATTRIBUTE_OPTION() [10/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Filename)
ATTRIBUTE_OPTION() [11/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Files)
ATTRIBUTE_OPTION() [12/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Format)
ATTRIBUTE_OPTION() [13/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Gaps)
ATTRIBUTE_OPTION() [14/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Generated)
ATTRIBUTE_OPTION() [15/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Global)
ATTRIBUTE_OPTION() [16/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Inserted)
ATTRIBUTE_OPTION() [17/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Level)
ATTRIBUTE_OPTION() [18/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Linkage)
ATTRIBUTE_OPTION() [19/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Local)
ATTRIBUTE_OPTION() [20/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Location)
ATTRIBUTE_OPTION() [21/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Offset)
ATTRIBUTE_OPTION() [22/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Pathname)
ATTRIBUTE_OPTION() [23/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Producer)
ATTRIBUTE_OPTION() [24/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Publics)
ATTRIBUTE_OPTION() [25/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Qualified)
ATTRIBUTE_OPTION() [26/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Qualifier)
ATTRIBUTE_OPTION() [27/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Range)
ATTRIBUTE_OPTION() [28/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Reference)
ATTRIBUTE_OPTION() [29/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Register)
ATTRIBUTE_OPTION() [30/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Standard)
ATTRIBUTE_OPTION() [31/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Subrange)
ATTRIBUTE_OPTION() [32/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (System)
ATTRIBUTE_OPTION() [33/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Typename)
ATTRIBUTE_OPTION() [34/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Underlying)
ATTRIBUTE_OPTION() [35/35]
llvm::logicalview::LVOptions::ATTRIBUTE_OPTION (Zero)
BOOL_FUNCTION() [1/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Attribute , Added)
BOOL_FUNCTION() [2/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Attribute , AnyLocation)
BOOL_FUNCTION() [3/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Attribute , AnySource)
BOOL_FUNCTION() [4/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Attribute , Missing)
BOOL_FUNCTION() [5/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Compare , Context)
BOOL_FUNCTION() [6/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Compare , Execute)
BOOL_FUNCTION() [7/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Compare , Print)
BOOL_FUNCTION() [8/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (General , CollectRanges)
BOOL_FUNCTION() [9/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Print , AnyElement)
BOOL_FUNCTION() [10/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Print , AnyLine)
BOOL_FUNCTION() [11/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Print , Execute)
BOOL_FUNCTION() [12/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Print , Formatting)
BOOL_FUNCTION() [13/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Print , Offset)
BOOL_FUNCTION() [14/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Print , SizesSummary)
BOOL_FUNCTION() [15/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Report , AnyView)
BOOL_FUNCTION() [16/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Report , Execute)
BOOL_FUNCTION() [17/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Select , Execute)
BOOL_FUNCTION() [18/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Select , GenericKind)
BOOL_FUNCTION() [19/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Select , GenericPattern)
BOOL_FUNCTION() [20/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Select , IgnoreCase)
BOOL_FUNCTION() [21/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Select , OffsetPattern)
BOOL_FUNCTION() [22/22]
llvm::logicalview::LVOptions::BOOL_FUNCTION (Select , UseRegex)
changeFilenameIndex()
bool llvm::logicalview::LVOptions::changeFilenameIndex (size_t Index) inline
Definition at line 289 of file LVOptions.h.
References Index.
COMPARE_OPTION() [1/5]
llvm::logicalview::LVOptions::COMPARE_OPTION (All)
COMPARE_OPTION() [2/5]
llvm::logicalview::LVOptions::COMPARE_OPTION (Lines)
COMPARE_OPTION() [3/5]
llvm::logicalview::LVOptions::COMPARE_OPTION (Scopes)
COMPARE_OPTION() [4/5]
llvm::logicalview::LVOptions::COMPARE_OPTION (Symbols)
COMPARE_OPTION() [5/5]
llvm::logicalview::LVOptions::COMPARE_OPTION (Types)
dump()
void llvm::logicalview::LVOptions::dump () const inline
Definition at line 441 of file LVOptions.h.
References llvm::dbgs(), and print().
Referenced by resolveDependencies().
getOptions()
LVOptions * LVOptions::getOptions () static
Definition at line 26 of file LVOptions.cpp.
References Options.
Referenced by llvm::logicalview::options().
getSortMode()
LVSortMode llvm::logicalview::LVOptions::getSortMode () const inline
Definition at line 382 of file LVOptions.h.
References Output.
indentationSize()
size_t llvm::logicalview::LVOptions::indentationSize () const inline
Definition at line 312 of file LVOptions.h.
Referenced by llvm::logicalview::LVRange::print(), and llvm::logicalview::LVScopeCompileUnit::printLocalNames().
INTERNAL_OPTION() [1/6]
llvm::logicalview::LVOptions::INTERNAL_OPTION (All)
INTERNAL_OPTION() [2/6]
llvm::logicalview::LVOptions::INTERNAL_OPTION (Cmdline)
INTERNAL_OPTION() [3/6]
llvm::logicalview::LVOptions::INTERNAL_OPTION (ID)
INTERNAL_OPTION() [4/6]
llvm::logicalview::LVOptions::INTERNAL_OPTION (Integrity)
INTERNAL_OPTION() [5/6]
llvm::logicalview::LVOptions::INTERNAL_OPTION (None)
INTERNAL_OPTION() [6/6]
llvm::logicalview::LVOptions::INTERNAL_OPTION (Tag)
operator=()
LVOptions& llvm::logicalview::LVOptions::operator= (const LVOptions &) default
OUTPUT_OPTION() [1/4]
llvm::logicalview::LVOptions::OUTPUT_OPTION (All)
OUTPUT_OPTION() [2/4]
llvm::logicalview::LVOptions::OUTPUT_OPTION (Json)
OUTPUT_OPTION() [3/4]
llvm::logicalview::LVOptions::OUTPUT_OPTION (Split)
OUTPUT_OPTION() [4/4]
llvm::logicalview::LVOptions::OUTPUT_OPTION (Text)
print()
void LVOptions::print (raw_ostream & OS) const
Definition at line 283 of file LVOptions.cpp.
References Options, and OS.
Referenced by dump().
PRINT_OPTION() [1/10]
llvm::logicalview::LVOptions::PRINT_OPTION (All)
PRINT_OPTION() [2/10]
llvm::logicalview::LVOptions::PRINT_OPTION (Elements)
PRINT_OPTION() [3/10]
llvm::logicalview::LVOptions::PRINT_OPTION (Instructions)
PRINT_OPTION() [4/10]
llvm::logicalview::LVOptions::PRINT_OPTION (Lines)
PRINT_OPTION() [5/10]
llvm::logicalview::LVOptions::PRINT_OPTION (Scopes)
PRINT_OPTION() [6/10]
llvm::logicalview::LVOptions::PRINT_OPTION (Sizes)
PRINT_OPTION() [7/10]
llvm::logicalview::LVOptions::PRINT_OPTION (Summary)
PRINT_OPTION() [8/10]
llvm::logicalview::LVOptions::PRINT_OPTION (Symbols)
PRINT_OPTION() [9/10]
llvm::logicalview::LVOptions::PRINT_OPTION (Types)
PRINT_OPTION() [10/10]
llvm::logicalview::LVOptions::PRINT_OPTION (Warnings)
REPORT_OPTION() [1/5]
llvm::logicalview::LVOptions::REPORT_OPTION (All)
REPORT_OPTION() [2/5]
llvm::logicalview::LVOptions::REPORT_OPTION (Children)
REPORT_OPTION() [3/5]
llvm::logicalview::LVOptions::REPORT_OPTION (List)
REPORT_OPTION() [4/5]
llvm::logicalview::LVOptions::REPORT_OPTION (Parents)
REPORT_OPTION() [5/5]
llvm::logicalview::LVOptions::REPORT_OPTION (View)
resetFilenameIndex()
void llvm::logicalview::LVOptions::resetFilenameIndex () inline
Definition at line 288 of file LVOptions.h.
Referenced by llvm::logicalview::LVScopeCompileUnit::printExtra().
resolveDependencies()
void LVOptions::resolveDependencies ()
Definition at line 29 of file LVOptions.cpp.
References dump(), llvm::logicalview::Line, LLVM_DEBUG, and setSortMode().
setOptions()
void LVOptions::setOptions (LVOptions * Options) static
Definition at line 27 of file LVOptions.cpp.
References Options.
Referenced by llvm::logicalview::setOptions().
setSortMode()
void llvm::logicalview::LVOptions::setSortMode (LVSortMode SortMode) inline
Definition at line 383 of file LVOptions.h.
References Output.
Referenced by resolveDependencies().
STD_STRING_FUNCTION()
llvm::logicalview::LVOptions::STD_STRING_FUNCTION (Output , Folder)
UNSIGNED_FUNCTION()
llvm::logicalview::LVOptions::UNSIGNED_FUNCTION (Output , Level)
WARNING_OPTION() [1/5]
llvm::logicalview::LVOptions::WARNING_OPTION (All)
WARNING_OPTION() [2/5]
llvm::logicalview::LVOptions::WARNING_OPTION (Coverages)
WARNING_OPTION() [3/5]
llvm::logicalview::LVOptions::WARNING_OPTION (Lines)
WARNING_OPTION() [4/5]
llvm::logicalview::LVOptions::WARNING_OPTION (Locations)
WARNING_OPTION() [5/5]
llvm::logicalview::LVOptions::WARNING_OPTION (Ranges)
Member Data Documentation
Attribute
LVAttribute llvm::logicalview::LVOptions::Attribute
Definition at line 314 of file LVOptions.h.
Compare
LVCompare llvm::logicalview::LVOptions::Compare
Definition at line 315 of file LVOptions.h.
General
LVGeneral llvm::logicalview::LVOptions::General
Definition at line 322 of file LVOptions.h.
Internal
LVInternal llvm::logicalview::LVOptions::Internal
Definition at line 321 of file LVOptions.h.
Output
LVOutput llvm::logicalview::LVOptions::Output
Definition at line 316 of file LVOptions.h.
Referenced by getSortMode(), and setSortMode().
Print
LVPrint llvm::logicalview::LVOptions::Print
Definition at line 317 of file LVOptions.h.
Report
LVReport llvm::logicalview::LVOptions::Report
Definition at line 318 of file LVOptions.h.
Select
LVSelect llvm::logicalview::LVOptions::Select
Definition at line 319 of file LVOptions.h.
Warning
LVWarning llvm::logicalview::LVOptions::Warning
Definition at line 320 of file LVOptions.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVOptions.h
lib/DebugInfo/LogicalView/Core/LVOptions.cpp