LLVM: llvm::TargetTransformInfoImplBase Class Reference
llvm::TargetTransformInfoImplBase Class Reference
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
#include "llvm/Analysis/TargetTransformInfoImpl.h"
Public Member Functions
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)=default
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind) const
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
unsigned getInliningThresholdMultiplier () const
unsigned adjustInliningThreshold (const CallBase *CB) const
int getInlinerVectorBonusPercent () const
InstructionCost getMemcpyCost (const Instruction *I) const
BranchProbability getPredictableBranchThreshold () const
bool hasBranchDivergence () const
bool useGPUDivergenceAnalysis () const
bool isSourceOfDivergence (const Value *V) const
bool isAlwaysUniform (const Value *V) const
unsigned getFlatAddressSpace () const
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool isNoopAddrSpaceCast (unsigned, unsigned) const
bool canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const
unsigned getAssumedAddrSpace (const Value *V) const
bool isSingleThreaded () const
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLoweredToCall (const Function *F) const
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo) const
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, LoopVectorizationLegality *LVL, InterleavedAccessInfo *IAI) const
TailFoldingStyle getPreferredTailFoldingStyle () const
std::optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const
std::optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const
std::optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &, OptimizationRemarkEmitter *) const
void getPeelingPreferences (Loop *, ScalarEvolution &, TTI::PeelingPreferences &) const
bool isLegalAddImmediate (int64_t Imm) const
bool isLegalICmpImmediate (int64_t Imm) const
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr) const
bool isLSRCostLess (const TTI::LSRCost &C1, const TTI::LSRCost &C2) const
bool isNumRegsMajorCostOfLSR () const
bool isProfitableLSRChainElement (Instruction *I) const
bool canMacroFuseCmp () const
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo) const
TTI::AddressingModeKind getPreferredAddressingMode (const Loop *L, ScalarEvolution *SE) const
bool isLegalMaskedStore (Type *DataType, Align Alignment) const
bool isLegalMaskedLoad (Type *DataType, Align Alignment) const
bool isLegalNTStore (Type *DataType, Align Alignment) const
bool isLegalNTLoad (Type *DataType, Align Alignment) const
bool isLegalBroadcastLoad (Type *ElementTy, ElementCount NumElements) const
bool isLegalMaskedScatter (Type *DataType, Align Alignment) const
bool isLegalMaskedGather (Type *DataType, Align Alignment) const
bool forceScalarizeMaskedGather (VectorType *DataType, Align Alignment) const
bool forceScalarizeMaskedScatter (VectorType *DataType, Align Alignment) const
bool isLegalMaskedCompressStore (Type *DataType) const
bool isLegalAltInstr (VectorType *VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector &OpcodeMask) const
bool isLegalMaskedExpandLoad (Type *DataType) const
bool enableOrderedReductions () const
bool hasDivRemOp (Type *DataType, bool IsSigned) const
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace) const
bool prefersVectorizedAddressing () const
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const
bool LSRWithInstrQueries () const
bool isTruncateFree (Type *Ty1, Type *Ty2) const
bool isProfitableToHoist (Instruction *I) const
bool useAA () const
bool isTypeLegal (Type *Ty) const
unsigned getRegUsageForType (Type *Ty) const
bool shouldBuildLookupTables () const
bool shouldBuildLookupTablesForConstant (Constant *C) const
bool shouldBuildRelLookupTables () const
bool useColdCCForColdCall (Function &F) const
InstructionCost getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind) const
InstructionCost getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
bool supportsEfficientVectorElementLoadStore () const
bool supportsTailCalls () const
bool supportsTailCallFor (const CallBase *CB) const
bool enableAggressiveInterleaving (bool LoopHasReductions) const
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableSelectOptimize () const
bool enableInterleavedAccessVectorization () const
bool enableMaskedInterleavedAccessVectorization () const
bool isFPVectorizationPotentiallyUnsafe () const
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned *Fast) const
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) const
bool haveFastSqrt (Type *Ty) const
bool isExpensiveToSpeculativelyExecute (const Instruction *I)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty) const
InstructionCost getFPOpCost (Type *Ty) const
InstructionCost getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty) const
InstructionCost getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
InstructionCost getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr) const
InstructionCost getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
unsigned getNumberOfRegisters (unsigned ClassID) const
unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
const char * getRegisterClassName (unsigned ClassID) const
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
unsigned getMinVectorRegisterBitWidth () const
std::optional< unsigned > getMaxVScale () const
std::optional< unsigned > getVScaleForTuning () const
bool shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const
ElementCount getMinimumVF (unsigned ElemWidth, bool IsScalable) const
unsigned getMaximumVF (unsigned ElemWidth, unsigned Opcode) const
unsigned getStoreMinimumVF (unsigned VF, Type *, Type *) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader) const
unsigned getCacheLineSize () const
std::optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
std::optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
unsigned getPrefetchDistance () const
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const
unsigned getMaxPrefetchIterationsAhead () const
bool enableWritePrefetching () const
bool shouldPrefetchAddressSpace (unsigned AS) const
unsigned getMaxInterleaveFactor (unsigned VF) const
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info, TTI::OperandValueInfo Opd2Info, ArrayRef< const Value * > Args, const Instruction *CxtI=nullptr) const
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *Ty, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType *SubTp, ArrayRef< const Value * > Args=std::nullopt) const
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index) const
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, TTI::TargetCostKind CostKind, unsigned Index, Value *Op0, Value *Op1) const
InstructionCost getVectorInstrCost (const Instruction &I, Type *Val, TTI::TargetCostKind CostKind, unsigned Index) const
unsigned getReplicationShuffleCost (Type *EltTy, int ReplicationFactor, int VF, const APInt &DemandedDstElts, TTI::TargetCostKind CostKind)
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo, const Instruction *I) const
InstructionCost getVPMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const
InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond, bool UseMaskForGaps) const
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
unsigned getNumberOfParts (Type *Tp) const
InstructionCost getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *) const
InstructionCost getArithmeticReductionCost (unsigned, VectorType *, std::optional< FastMathFlags > FMF, TTI::TargetCostKind) const
InstructionCost getMinMaxReductionCost (VectorType *, VectorType *, bool, TTI::TargetCostKind) const
InstructionCost getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type *ResTy, VectorType *Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const
InstructionCost getMulAccReductionCost (bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind) const
InstructionCost getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) const
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType) const
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign, std::optional< uint32_t > AtomicElementSize) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign, std::optional< uint32_t > AtomicCpySize) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areTypesABICompatible (const Function *Caller, const Function *Callee, const ArrayRef< Type * > &Types) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeReduction (const RecurrenceDescriptor &RdxDesc, ElementCount VF) const
bool isElementTypeLegalForScalableVector (Type *Ty) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool preferInLoopReduction (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool preferPredicatedReductionSelect (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool preferEpilogueVectorization () const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
unsigned getMinTripCountTailFoldingThreshold () const
bool supportsScalableVectors () const
bool enableScalableVectorization () const
bool hasActiveVectorLength (unsigned Opcode, Type *DataType, Align Alignment) const
TargetTransformInfo::VPLegalization getVPLegalizationStrategy (const VPIntrinsic &PI) const
Protected Types
typedef TargetTransformInfo TTI
Protected Member Functions
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned) const
bool isStridedAccess (const SCEV *Ptr) const
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr) const
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance) const
Protected Attributes
const DataLayout & DL
Detailed Description
Base class for use as a mix-in that aids implementing a TargetTransformInfo-compatible class.
Definition at line 34 of file TargetTransformInfoImpl.h.
Member Typedef Documentation
TTI
typedef TargetTransformInfo llvm::TargetTransformInfoImplBase::TTI protected
Definition at line 36 of file TargetTransformInfoImpl.h.
Constructor & Destructor Documentation
TargetTransformInfoImplBase() [1/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const DataLayout & DL) inline explicit protected
Definition at line 40 of file TargetTransformInfoImpl.h.
TargetTransformInfoImplBase() [2/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (const TargetTransformInfoImplBase & Arg) default
TargetTransformInfoImplBase() [3/3]
llvm::TargetTransformInfoImplBase::TargetTransformInfoImplBase (TargetTransformInfoImplBase && Arg) inline
Definition at line 45 of file TargetTransformInfoImpl.h.
Member Function Documentation
adjustInliningThreshold()
unsigned llvm::TargetTransformInfoImplBase::adjustInliningThreshold (const CallBase * CB) const inline
Definition at line 72 of file TargetTransformInfoImpl.h.
allowsMisalignedMemoryAccesses()
bool llvm::TargetTransformInfoImplBase::allowsMisalignedMemoryAccesses (LLVMContext & Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, unsigned * Fast) const inline
Definition at line 373 of file TargetTransformInfoImpl.h.
areInlineCompatible()
bool llvm::TargetTransformInfoImplBase::areInlineCompatible (const Function * Caller, const Function * Callee) const inline
Definition at line 768 of file TargetTransformInfoImpl.h.
References Callee.
areTypesABICompatible()
bool llvm::TargetTransformInfoImplBase::areTypesABICompatible (const Function * Caller, const Function * Callee, const ArrayRef< Type * > & Types) const inline
Definition at line 776 of file TargetTransformInfoImpl.h.
References Callee.
Referenced by llvm::PPCTTIImpl::areTypesABICompatible(), and llvm::X86TTIImpl::areTypesABICompatible().
canHaveNonUndefGlobalInitializerInAddressSpace()
bool llvm::TargetTransformInfoImplBase::canHaveNonUndefGlobalInitializerInAddressSpace (unsigned AS) const inline
Definition at line 106 of file TargetTransformInfoImpl.h.
canMacroFuseCmp()
bool llvm::TargetTransformInfoImplBase::canMacroFuseCmp () const inline
Definition at line 228 of file TargetTransformInfoImpl.h.
canSaveCmp()
bool llvm::TargetTransformInfoImplBase::canSaveCmp (Loop * L, BranchInst ** BI, ScalarEvolution * SE, LoopInfo * LI, DominatorTree * DT, AssumptionCache * AC, TargetLibraryInfo * LibInfo) const inline
Definition at line 230 of file TargetTransformInfoImpl.h.
collectFlatAddressOperands()
bool llvm::TargetTransformInfoImplBase::collectFlatAddressOperands (SmallVectorImpl< int > & OpIndexes, Intrinsic::ID IID) const inline
Definition at line 100 of file TargetTransformInfoImpl.h.
enableAggressiveInterleaving()
bool llvm::TargetTransformInfoImplBase::enableAggressiveInterleaving (bool LoopHasReductions) const inline
Definition at line 356 of file TargetTransformInfoImpl.h.
enableInterleavedAccessVectorization()
bool llvm::TargetTransformInfoImplBase::enableInterleavedAccessVectorization () const inline
Definition at line 367 of file TargetTransformInfoImpl.h.
enableMaskedInterleavedAccessVectorization()
bool llvm::TargetTransformInfoImplBase::enableMaskedInterleavedAccessVectorization () const inline
Definition at line 369 of file TargetTransformInfoImpl.h.
enableMemCmpExpansion()
TTI::MemCmpExpansionOptions llvm::TargetTransformInfoImplBase::enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const inline
Definition at line 360 of file TargetTransformInfoImpl.h.
enableOrderedReductions()
bool llvm::TargetTransformInfoImplBase::enableOrderedReductions () const inline
Definition at line 293 of file TargetTransformInfoImpl.h.
enableScalableVectorization()
bool llvm::TargetTransformInfoImplBase::enableScalableVectorization () const inline
Definition at line 851 of file TargetTransformInfoImpl.h.
enableSelectOptimize()
bool llvm::TargetTransformInfoImplBase::enableSelectOptimize () const inline
Definition at line 365 of file TargetTransformInfoImpl.h.
enableWritePrefetching()
bool llvm::TargetTransformInfoImplBase::enableWritePrefetching () const inline
Definition at line 491 of file TargetTransformInfoImpl.h.
forceScalarizeMaskedGather()
bool llvm::TargetTransformInfoImplBase::forceScalarizeMaskedGather (VectorType * DataType, Align Alignment) const inline
Definition at line 275 of file TargetTransformInfoImpl.h.
forceScalarizeMaskedScatter()
bool llvm::TargetTransformInfoImplBase::forceScalarizeMaskedScatter (VectorType * DataType, Align Alignment) const inline
Definition at line 279 of file TargetTransformInfoImpl.h.
getAddressComputationCost()
InstructionCost llvm::TargetTransformInfoImplBase::getAddressComputationCost (Type * Tp, ScalarEvolution * , const SCEV *) const inline
Definition at line 697 of file TargetTransformInfoImpl.h.
getArithmeticInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::TargetCostKind CostKind, TTI::OperandValueInfo Opd1Info, TTI::OperandValueInfo Opd2Info, ArrayRef< const Value * > Args, const Instruction * CxtI = nullptr) const inline
Definition at line 496 of file TargetTransformInfoImpl.h.
References CostKind, llvm::Type::getScalarType(), llvm::Type::isFloatingPointTy(), llvm::TargetTransformInfo::TCC_Expensive, and llvm::TargetTransformInfo::TCK_Latency.
getArithmeticReductionCost()
InstructionCost llvm::TargetTransformInfoImplBase::getArithmeticReductionCost (unsigned , VectorType * , std::optional< FastMathFlags > FMF, TTI::TargetCostKind) const inline
Definition at line 702 of file TargetTransformInfoImpl.h.
getAssumedAddrSpace()
unsigned llvm::TargetTransformInfoImplBase::getAssumedAddrSpace (const Value * V) const inline
Definition at line 110 of file TargetTransformInfoImpl.h.
getAtomicMemIntrinsicMaxElementSize()
unsigned llvm::TargetTransformInfoImplBase::getAtomicMemIntrinsicMaxElementSize () const inline
Definition at line 734 of file TargetTransformInfoImpl.h.
getCacheAssociativity()
std::optional<unsigned> llvm::TargetTransformInfoImplBase::getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const inline
Definition at line 473 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCacheAssociativity().
getCacheLineSize()
unsigned llvm::TargetTransformInfoImplBase::getCacheLineSize () const inline
Definition at line 460 of file TargetTransformInfoImpl.h.
getCacheSize()
std::optional<unsigned> llvm::TargetTransformInfoImplBase::getCacheSize (TargetTransformInfo::CacheLevel Level) const inline
Definition at line 462 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::L1D, llvm::TargetTransformInfo::L2D, and llvm_unreachable.
getCallInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const inline
Definition at line 688 of file TargetTransformInfoImpl.h.
getCastInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction * I) const inline
Definition at line 531 of file TargetTransformInfoImpl.h.
References DL, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::DataLayout::getTypeSizeInBits(), llvm::DataLayout::isLegalInteger(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost().
getCFInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline
Definition at line 575 of file TargetTransformInfoImpl.h.
References CostKind, PHI, and llvm::TargetTransformInfo::TCK_RecipThroughput.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCFInstrCost().
getCmpSelInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction * I) const inline
Definition at line 584 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCmpSelInstrCost().
getConstantStrideStep()
const SCEVConstant* llvm::TargetTransformInfoImplBase::getConstantStrideStep (ScalarEvolution * SE, const SCEV * Ptr) const inline protected
Definition at line 926 of file TargetTransformInfoImpl.h.
References llvm::SCEVAddRecExpr::getStepRecurrence(), isStridedAccess(), and Ptr.
Referenced by llvm::X86TTIImpl::getAddressComputationCost(), and isConstantStridedAccessLessThan().
getCostOfKeepingLiveOverCall()
InstructionCost llvm::TargetTransformInfoImplBase::getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const inline
Definition at line 726 of file TargetTransformInfoImpl.h.
getDataLayout()
const DataLayout& llvm::TargetTransformInfoImplBase::getDataLayout () const inline
Definition at line 47 of file TargetTransformInfoImpl.h.
References DL.
Referenced by adjustInliningThresholdUsingCallee(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getEstimatedNumberOfCaseClusters(), llvm::HexagonTTIImpl::getInstructionCost(), and llvm::RISCVTTIImpl::getIntImmCost().
getEstimatedNumberOfCaseClusters()
unsigned llvm::TargetTransformInfoImplBase::getEstimatedNumberOfCaseClusters (const SwitchInst & SI, unsigned & JTSize, ProfileSummaryInfo * PSI, BlockFrequencyInfo * BFI) const inline
Definition at line 61 of file TargetTransformInfoImpl.h.
References llvm::AMDGPUISD::BFI, and SI.
getExtendedReductionCost()
InstructionCost llvm::TargetTransformInfoImplBase::getExtendedReductionCost (unsigned Opcode, bool IsUnsigned, Type * ResTy, VectorType * Ty, std::optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind) const inline
Definition at line 713 of file TargetTransformInfoImpl.h.
getExtractWithExtendCost()
InstructionCost llvm::TargetTransformInfoImplBase::getExtractWithExtendCost (unsigned Opcode, Type * Dst, VectorType * VecTy, unsigned Index) const inline
Definition at line 569 of file TargetTransformInfoImpl.h.
getFlatAddressSpace()
unsigned llvm::TargetTransformInfoImplBase::getFlatAddressSpace () const inline
Definition at line 98 of file TargetTransformInfoImpl.h.
getFPOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getFPOpCost (Type * Ty) const inline
Definition at line 389 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
getGatherScatterOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getGatherScatterOpCost (unsigned Opcode, Type * DataTy, const Value * Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) const inline
Definition at line 631 of file TargetTransformInfoImpl.h.
getGEPCost()
InstructionCost llvm::TargetTransformInfoImplBase::getGEPCost (Type * PointeeType, const Value * Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind) const inline
Definition at line 49 of file TargetTransformInfoImpl.h.
getGISelRematGlobalCost()
unsigned llvm::TargetTransformInfoImplBase::getGISelRematGlobalCost () const inline
Definition at line 845 of file TargetTransformInfoImpl.h.
getInlinerVectorBonusPercent()
int llvm::TargetTransformInfoImplBase::getInlinerVectorBonusPercent () const inline
Definition at line 74 of file TargetTransformInfoImpl.h.
getInliningThresholdMultiplier()
unsigned llvm::TargetTransformInfoImplBase::getInliningThresholdMultiplier () const inline
Definition at line 71 of file TargetTransformInfoImpl.h.
getInterleavedMemoryOpCost()
unsigned llvm::TargetTransformInfoImplBase::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond, bool UseMaskForGaps) const inline
Definition at line 639 of file TargetTransformInfoImpl.h.
getIntImmCodeSizeCost()
InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty) const inline
Definition at line 393 of file TargetTransformInfoImpl.h.
getIntImmCost()
InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCost (const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const inline
Definition at line 398 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Basic.
Referenced by llvm::PPCTTIImpl::getIntImmCost().
getIntImmCostInst()
InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind, Instruction * Inst = nullptr) const inline
Definition at line 403 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::PPCTTIImpl::getIntImmCostInst().
getIntImmCostIntrin()
InstructionCost llvm::TargetTransformInfoImplBase::getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind) const inline
Definition at line 410 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::PPCTTIImpl::getIntImmCostIntrin().
getIntrinsicInstrCost()
InstructionCost llvm::TargetTransformInfoImplBase::getIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind) const inline
Definition at line 646 of file TargetTransformInfoImpl.h.
References llvm::IntrinsicCostAttributes::getID().
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost().
getLoadStoreVecRegBitWidth()
unsigned llvm::TargetTransformInfoImplBase::getLoadStoreVecRegBitWidth (unsigned AddrSpace) const inline
Definition at line 794 of file TargetTransformInfoImpl.h.
getLoadVectorFactor()
unsigned llvm::TargetTransformInfoImplBase::getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType * VecTy) const inline
Definition at line 817 of file TargetTransformInfoImpl.h.
getMaskedMemoryOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const inline
Definition at line 625 of file TargetTransformInfoImpl.h.
getMaximumVF()
unsigned llvm::TargetTransformInfoImplBase::getMaximumVF (unsigned ElemWidth, unsigned Opcode) const inline
Definition at line 451 of file TargetTransformInfoImpl.h.
getMaxInterleaveFactor()
unsigned llvm::TargetTransformInfoImplBase::getMaxInterleaveFactor (unsigned VF) const inline
Definition at line 494 of file TargetTransformInfoImpl.h.
getMaxPrefetchIterationsAhead()
unsigned llvm::TargetTransformInfoImplBase::getMaxPrefetchIterationsAhead () const inline
Definition at line 490 of file TargetTransformInfoImpl.h.
getMaxVScale()
std::optional<unsigned> llvm::TargetTransformInfoImplBase::getMaxVScale () const inline
Definition at line 439 of file TargetTransformInfoImpl.h.
getMemcpyCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMemcpyCost (const Instruction * I) const inline
Definition at line 76 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::TCC_Expensive.
getMemcpyLoopLoweringType()
Type* llvm::TargetTransformInfoImplBase::getMemcpyLoopLoweringType (LLVMContext & Context, Value * Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign, std::optional< uint32_t > AtomicElementSize) const inline
Definition at line 749 of file TargetTransformInfoImpl.h.
References Context, llvm::Type::getInt8Ty(), and llvm::Type::getIntNTy().
getMemcpyLoopResidualLoweringType()
void llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > & OpsOut, LLVMContext & Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign, std::optional< uint32_t > AtomicCpySize) const inline
Definition at line 757 of file TargetTransformInfoImpl.h.
References Context, llvm::Type::getIntNTy(), and i.
Referenced by llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType().
getMemoryOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, TTI::OperandValueInfo OpInfo, const Instruction * I) const inline
Definition at line 610 of file TargetTransformInfoImpl.h.
getMinimumVF()
ElementCount llvm::TargetTransformInfoImplBase::getMinimumVF (unsigned ElemWidth, bool IsScalable) const inline
Definition at line 447 of file TargetTransformInfoImpl.h.
References llvm::ElementCount::get().
getMinMaxReductionCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMinMaxReductionCost (VectorType * , VectorType * , bool , TTI::TargetCostKind) const inline
Definition at line 708 of file TargetTransformInfoImpl.h.
getMinPrefetchStride()
unsigned llvm::TargetTransformInfoImplBase::getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const inline
Definition at line 485 of file TargetTransformInfoImpl.h.
getMinTripCountTailFoldingThreshold()
unsigned llvm::TargetTransformInfoImplBase::getMinTripCountTailFoldingThreshold () const inline
Definition at line 847 of file TargetTransformInfoImpl.h.
getMinVectorRegisterBitWidth()
unsigned llvm::TargetTransformInfoImplBase::getMinVectorRegisterBitWidth () const inline
Definition at line 437 of file TargetTransformInfoImpl.h.
getMulAccReductionCost()
InstructionCost llvm::TargetTransformInfoImplBase::getMulAccReductionCost (bool IsUnsigned, Type * ResTy, VectorType * Ty, TTI::TargetCostKind CostKind) const inline
Definition at line 720 of file TargetTransformInfoImpl.h.
getNumberOfParts()
unsigned llvm::TargetTransformInfoImplBase::getNumberOfParts (Type * Tp) const inline
Definition at line 695 of file TargetTransformInfoImpl.h.
getNumberOfRegisters()
unsigned llvm::TargetTransformInfoImplBase::getNumberOfRegisters (unsigned ClassID) const inline
Definition at line 416 of file TargetTransformInfoImpl.h.
Referenced by llvm::WebAssemblyTTIImpl::getNumberOfRegisters().
getOperandsScalarizationOverhead()
InstructionCost llvm::TargetTransformInfoImplBase::getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const inline
Definition at line 342 of file TargetTransformInfoImpl.h.
getOrCreateResultFromMemIntrinsic()
Value* llvm::TargetTransformInfoImplBase::getOrCreateResultFromMemIntrinsic (IntrinsicInst * Inst, Type * ExpectedType) const inline
Definition at line 743 of file TargetTransformInfoImpl.h.
getPeelingPreferences()
void llvm::TargetTransformInfoImplBase::getPeelingPreferences (Loop * , ScalarEvolution & , TTI::PeelingPreferences &) const inline
Definition at line 202 of file TargetTransformInfoImpl.h.
getPopcntSupport()
TTI::PopcntSupportKind llvm::TargetTransformInfoImplBase::getPopcntSupport (unsigned IntTyWidthInBit) const inline
Definition at line 379 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::PSK_Software.
getPredicatedAddrSpace()
std::pair<const Value *, unsigned> llvm::TargetTransformInfoImplBase::getPredicatedAddrSpace (const Value * V) const inline
Definition at line 115 of file TargetTransformInfoImpl.h.
getPredictableBranchThreshold()
BranchProbability llvm::TargetTransformInfoImplBase::getPredictableBranchThreshold () const inline
Definition at line 86 of file TargetTransformInfoImpl.h.
getPreferredAddressingMode()
TTI::AddressingModeKind llvm::TargetTransformInfoImplBase::getPreferredAddressingMode (const Loop * L, ScalarEvolution * SE) const inline
Definition at line 237 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::AMK_None.
getPreferredTailFoldingStyle()
TailFoldingStyle llvm::TargetTransformInfoImplBase::getPreferredTailFoldingStyle () const inline
Definition at line 174 of file TargetTransformInfoImpl.h.
References llvm::DataWithoutLaneMask.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getPreferredTailFoldingStyle().
getPrefetchDistance()
unsigned llvm::TargetTransformInfoImplBase::getPrefetchDistance () const inline
Definition at line 484 of file TargetTransformInfoImpl.h.
getRegisterBitWidth()
TypeSize llvm::TargetTransformInfoImplBase::getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const inline
Definition at line 433 of file TargetTransformInfoImpl.h.
References llvm::TypeSize::getFixed().
getRegisterClassForType()
unsigned llvm::TargetTransformInfoImplBase::getRegisterClassForType (bool Vector, Type * Ty = nullptr) const inline
Definition at line 418 of file TargetTransformInfoImpl.h.
References Vector.
getRegisterClassName()
const char* llvm::TargetTransformInfoImplBase::getRegisterClassName (unsigned ClassID) const inline
Definition at line 422 of file TargetTransformInfoImpl.h.
getRegUsageForType()
unsigned llvm::TargetTransformInfoImplBase::getRegUsageForType (Type * Ty) const inline
Definition at line 324 of file TargetTransformInfoImpl.h.
getReplicationShuffleCost()
unsigned llvm::TargetTransformInfoImplBase::getReplicationShuffleCost (Type * EltTy, int ReplicationFactor, int VF, const APInt & DemandedDstElts, TTI::TargetCostKind CostKind) inline
Definition at line 604 of file TargetTransformInfoImpl.h.
getScalarizationOverhead()
InstructionCost llvm::TargetTransformInfoImplBase::getScalarizationOverhead (VectorType * Ty, const APInt & DemandedElts, bool Insert, bool Extract, TTI::TargetCostKind CostKind) const inline
Definition at line 334 of file TargetTransformInfoImpl.h.
getScalingFactorCost()
InstructionCost llvm::TargetTransformInfoImplBase::getScalingFactorCost (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const inline
Definition at line 303 of file TargetTransformInfoImpl.h.
References isLegalAddressingMode().
getShuffleCost()
InstructionCost llvm::TargetTransformInfoImplBase::getShuffleCost (TTI::ShuffleKind Kind, VectorType * Ty, ArrayRef< int > Mask, TTI::TargetCostKind CostKind, int Index, VectorType * SubTp, ArrayRef< const Value * > Args = std::nullopt) const inline
Definition at line 525 of file TargetTransformInfoImpl.h.
getStoreMinimumVF()
unsigned llvm::TargetTransformInfoImplBase::getStoreMinimumVF (unsigned VF, Type * , Type *) const inline
Definition at line 452 of file TargetTransformInfoImpl.h.
getStoreVectorFactor()
unsigned llvm::TargetTransformInfoImplBase::getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType * VecTy) const inline
Definition at line 823 of file TargetTransformInfoImpl.h.
getTgtMemIntrinsic()
bool llvm::TargetTransformInfoImplBase::getTgtMemIntrinsic (IntrinsicInst * Inst, MemIntrinsicInfo & Info) const inline
Definition at line 730 of file TargetTransformInfoImpl.h.
getUnrollingPreferences()
void llvm::TargetTransformInfoImplBase::getUnrollingPreferences (Loop * , ScalarEvolution & , TTI::UnrollingPreferences & , OptimizationRemarkEmitter *) const inline
Definition at line 198 of file TargetTransformInfoImpl.h.
getVectorInstrCost() [1/2]
InstructionCost llvm::TargetTransformInfoImplBase::getVectorInstrCost (const Instruction & I, Type * Val, TTI::TargetCostKind CostKind, unsigned Index) const inline
Definition at line 598 of file TargetTransformInfoImpl.h.
getVectorInstrCost() [2/2]
InstructionCost llvm::TargetTransformInfoImplBase::getVectorInstrCost (unsigned Opcode, Type * Val, TTI::TargetCostKind CostKind, unsigned Index, Value * Op0, Value * Op1) const inline
Definition at line 591 of file TargetTransformInfoImpl.h.
getVPLegalizationStrategy()
TargetTransformInfo::VPLegalization llvm::TargetTransformInfoImplBase::getVPLegalizationStrategy (const VPIntrinsic & PI) const inline
Definition at line 859 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::VPLegalization::Convert, and llvm::TargetTransformInfo::VPLegalization::Discard.
getVPMemoryOpCost()
InstructionCost llvm::TargetTransformInfoImplBase::getVPMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction * I) const inline
Definition at line 618 of file TargetTransformInfoImpl.h.
Referenced by llvm::PPCTTIImpl::getVPMemoryOpCost().
getVScaleForTuning()
std::optional<unsigned> llvm::TargetTransformInfoImplBase::getVScaleForTuning () const inline
Definition at line 440 of file TargetTransformInfoImpl.h.
hasActiveVectorLength()
bool llvm::TargetTransformInfoImplBase::hasActiveVectorLength (unsigned Opcode, Type * DataType, Align Alignment) const inline
Definition at line 853 of file TargetTransformInfoImpl.h.
hasBranchDivergence()
bool llvm::TargetTransformInfoImplBase::hasBranchDivergence () const inline
Definition at line 90 of file TargetTransformInfoImpl.h.
hasDivRemOp()
bool llvm::TargetTransformInfoImplBase::hasDivRemOp (Type * DataType, bool IsSigned) const inline
Definition at line 295 of file TargetTransformInfoImpl.h.
hasVolatileVariant()
bool llvm::TargetTransformInfoImplBase::hasVolatileVariant (Instruction * I, unsigned AddrSpace) const inline
Definition at line 297 of file TargetTransformInfoImpl.h.
haveFastSqrt()
bool llvm::TargetTransformInfoImplBase::haveFastSqrt (Type * Ty) const inline
Definition at line 383 of file TargetTransformInfoImpl.h.
instCombineIntrinsic()
std::optional<Instruction *> llvm::TargetTransformInfoImplBase::instCombineIntrinsic (InstCombiner & IC, IntrinsicInst & II) const inline
Definition at line 178 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::instCombineIntrinsic().
isAlwaysUniform()
bool llvm::TargetTransformInfoImplBase::isAlwaysUniform (const Value * V) const inline
Definition at line 96 of file TargetTransformInfoImpl.h.
isConstantStridedAccessLessThan()
bool llvm::TargetTransformInfoImplBase::isConstantStridedAccessLessThan (ScalarEvolution * SE, const SCEV * Ptr, int64_t MergeDistance) const inline protected
Definition at line 934 of file TargetTransformInfoImpl.h.
References llvm::SCEVConstant::getAPInt(), llvm::APInt::getBitWidth(), getConstantStrideStep(), llvm::APInt::getSExtValue(), and Ptr.
Referenced by llvm::ARMTTIImpl::getAddressComputationCost().
isElementTypeLegalForScalableVector()
bool llvm::TargetTransformInfoImplBase::isElementTypeLegalForScalableVector (Type * Ty) const inline
Definition at line 815 of file TargetTransformInfoImpl.h.
isExpensiveToSpeculativelyExecute()
bool llvm::TargetTransformInfoImplBase::isExpensiveToSpeculativelyExecute (const Instruction * I) inline
Definition at line 385 of file TargetTransformInfoImpl.h.
isFCmpOrdCheaperThanFCmpZero()
bool llvm::TargetTransformInfoImplBase::isFCmpOrdCheaperThanFCmpZero (Type * Ty) const inline
Definition at line 387 of file TargetTransformInfoImpl.h.
isFPVectorizationPotentiallyUnsafe()
bool llvm::TargetTransformInfoImplBase::isFPVectorizationPotentiallyUnsafe () const inline
Definition at line 371 of file TargetTransformInfoImpl.h.
isHardwareLoopProfitable()
bool llvm::TargetTransformInfoImplBase::isHardwareLoopProfitable (Loop * L, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * LibInfo, HardwareLoopInfo & HWLoopInfo) const inline
Definition at line 160 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isHardwareLoopProfitable().
isIndexedLoadLegal()
bool llvm::TargetTransformInfoImplBase::isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type * Ty, const DataLayout & DL) const inline
Definition at line 784 of file TargetTransformInfoImpl.h.
isIndexedStoreLegal()
bool llvm::TargetTransformInfoImplBase::isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type * Ty, const DataLayout & DL) const inline
Definition at line 789 of file TargetTransformInfoImpl.h.
isLegalAddImmediate()
bool llvm::TargetTransformInfoImplBase::isLegalAddImmediate (int64_t Imm) const inline
Definition at line 205 of file TargetTransformInfoImpl.h.
isLegalAddressingMode()
bool llvm::TargetTransformInfoImplBase::isLegalAddressingMode (Type * Ty, GlobalValue * BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction * I = nullptr) const inline
Definition at line 209 of file TargetTransformInfoImpl.h.
Referenced by llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), and getScalingFactorCost().
isLegalAltInstr()
bool llvm::TargetTransformInfoImplBase::isLegalAltInstr (VectorType * VecTy, unsigned Opcode0, unsigned Opcode1, const SmallBitVector & OpcodeMask) const inline
Definition at line 286 of file TargetTransformInfoImpl.h.
isLegalBroadcastLoad()
bool llvm::TargetTransformInfoImplBase::isLegalBroadcastLoad (Type * ElementTy, ElementCount NumElements) const inline
Definition at line 263 of file TargetTransformInfoImpl.h.
isLegalICmpImmediate()
bool llvm::TargetTransformInfoImplBase::isLegalICmpImmediate (int64_t Imm) const inline
Definition at line 207 of file TargetTransformInfoImpl.h.
isLegalMaskedCompressStore()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedCompressStore (Type * DataType) const inline
Definition at line 284 of file TargetTransformInfoImpl.h.
isLegalMaskedExpandLoad()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedExpandLoad (Type * DataType) const inline
Definition at line 291 of file TargetTransformInfoImpl.h.
isLegalMaskedGather()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedGather (Type * DataType, Align Alignment) const inline
Definition at line 271 of file TargetTransformInfoImpl.h.
isLegalMaskedLoad()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedLoad (Type * DataType, Align Alignment) const inline
Definition at line 245 of file TargetTransformInfoImpl.h.
isLegalMaskedScatter()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedScatter (Type * DataType, Align Alignment) const inline
Definition at line 267 of file TargetTransformInfoImpl.h.
isLegalMaskedStore()
bool llvm::TargetTransformInfoImplBase::isLegalMaskedStore (Type * DataType, Align Alignment) const inline
Definition at line 241 of file TargetTransformInfoImpl.h.
isLegalNTLoad()
bool llvm::TargetTransformInfoImplBase::isLegalNTLoad (Type * DataType, Align Alignment) const inline
Definition at line 256 of file TargetTransformInfoImpl.h.
References DL, llvm::DataLayout::getTypeStoreSize(), and llvm::isPowerOf2_32().
Referenced by llvm::AArch64TTIImpl::isLegalNTLoad().
isLegalNTStore()
bool llvm::TargetTransformInfoImplBase::isLegalNTStore (Type * DataType, Align Alignment) const inline
Definition at line 249 of file TargetTransformInfoImpl.h.
References DL, llvm::DataLayout::getTypeStoreSize(), and llvm::isPowerOf2_32().
Referenced by llvm::AArch64TTIImpl::isLegalNTStoreLoad().
isLegalToVectorizeLoad()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeLoad (LoadInst * LI) const inline
Definition at line 796 of file TargetTransformInfoImpl.h.
isLegalToVectorizeLoadChain()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const inline
Definition at line 800 of file TargetTransformInfoImpl.h.
isLegalToVectorizeReduction()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeReduction (const RecurrenceDescriptor & RdxDesc, ElementCount VF) const inline
Definition at line 810 of file TargetTransformInfoImpl.h.
isLegalToVectorizeStore()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeStore (StoreInst * SI) const inline
Definition at line 798 of file TargetTransformInfoImpl.h.
isLegalToVectorizeStoreChain()
bool llvm::TargetTransformInfoImplBase::isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const inline
Definition at line 805 of file TargetTransformInfoImpl.h.
isLoweredToCall()
bool llvm::TargetTransformInfoImplBase::isLoweredToCall (const Function * F) const inline
Definition at line 124 of file TargetTransformInfoImpl.h.
References assert(), and F.
Referenced by llvm::WebAssemblyTTIImpl::getUnrollingPreferences(), llvm::SystemZTTIImpl::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getUnrollingPreferences(), and llvm::ARMTTIImpl::isLoweredToCall().
isLSRCostLess()
bool llvm::TargetTransformInfoImplBase::isLSRCostLess (const TTI::LSRCost & C1, const TTI::LSRCost & C2) const inline
Definition at line 217 of file TargetTransformInfoImpl.h.
References llvm::TargetTransformInfo::LSRCost::AddRecCost, C1, llvm::TargetTransformInfo::LSRCost::ImmCost, llvm::TargetTransformInfo::LSRCost::NumBaseAdds, llvm::TargetTransformInfo::LSRCost::NumIVMuls, llvm::TargetTransformInfo::LSRCost::NumRegs, llvm::TargetTransformInfo::LSRCost::ScaleCost, and llvm::TargetTransformInfo::LSRCost::SetupCost.
Referenced by llvm::PPCTTIImpl::isLSRCostLess(), and llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isLSRCostLess().
isNoopAddrSpaceCast()
bool llvm::TargetTransformInfoImplBase::isNoopAddrSpaceCast (unsigned , unsigned) const inline
Definition at line 105 of file TargetTransformInfoImpl.h.
isNumRegsMajorCostOfLSR()
bool llvm::TargetTransformInfoImplBase::isNumRegsMajorCostOfLSR () const inline
Definition at line 224 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isNumRegsMajorCostOfLSR().
isProfitableLSRChainElement()
bool llvm::TargetTransformInfoImplBase::isProfitableLSRChainElement (Instruction * I) const inline
Definition at line 226 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isProfitableLSRChainElement().
isProfitableToHoist()
bool llvm::TargetTransformInfoImplBase::isProfitableToHoist (Instruction * I) const inline
Definition at line 318 of file TargetTransformInfoImpl.h.
isSingleThreaded()
bool llvm::TargetTransformInfoImplBase::isSingleThreaded () const inline
Definition at line 112 of file TargetTransformInfoImpl.h.
isSourceOfDivergence()
bool llvm::TargetTransformInfoImplBase::isSourceOfDivergence (const Value * V) const inline
Definition at line 94 of file TargetTransformInfoImpl.h.
isStridedAccess()
bool llvm::TargetTransformInfoImplBase::isStridedAccess (const SCEV * Ptr) const inline protected
Definition at line 922 of file TargetTransformInfoImpl.h.
References Ptr.
Referenced by llvm::X86TTIImpl::getAddressComputationCost(), and getConstantStrideStep().
isTruncateFree()
bool llvm::TargetTransformInfoImplBase::isTruncateFree (Type * Ty1, Type * Ty2) const inline
Definition at line 316 of file TargetTransformInfoImpl.h.
isTypeLegal()
bool llvm::TargetTransformInfoImplBase::isTypeLegal (Type * Ty) const inline
Definition at line 322 of file TargetTransformInfoImpl.h.
LSRWithInstrQueries()
bool llvm::TargetTransformInfoImplBase::LSRWithInstrQueries () const inline
Definition at line 314 of file TargetTransformInfoImpl.h.
minRequiredElementSize()
unsigned llvm::TargetTransformInfoImplBase::minRequiredElementSize (const Value * Val, bool & isSigned) const inline protected
Definition at line 868 of file TargetTransformInfoImpl.h.
References llvm::numbers::e, llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), i, isSigned(), and llvm::max().
Referenced by llvm::X86TTIImpl::getArithmeticInstrCost().
preferEpilogueVectorization()
bool llvm::TargetTransformInfoImplBase::preferEpilogueVectorization () const inline
Definition at line 839 of file TargetTransformInfoImpl.h.
preferInLoopReduction()
bool llvm::TargetTransformInfoImplBase::preferInLoopReduction (unsigned Opcode, Type * Ty, TTI::ReductionFlags Flags) const inline
Definition at line 829 of file TargetTransformInfoImpl.h.
preferPredicatedReductionSelect()
bool llvm::TargetTransformInfoImplBase::preferPredicatedReductionSelect (unsigned Opcode, Type * Ty, TTI::ReductionFlags Flags) const inline
Definition at line 834 of file TargetTransformInfoImpl.h.
preferPredicateOverEpilogue()
bool llvm::TargetTransformInfoImplBase::preferPredicateOverEpilogue (Loop * L, LoopInfo * LI, ScalarEvolution & SE, AssumptionCache & AC, TargetLibraryInfo * TLI, DominatorTree * DT, LoopVectorizationLegality * LVL, InterleavedAccessInfo * IAI) const inline
Definition at line 166 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::preferPredicateOverEpilogue().
prefersVectorizedAddressing()
bool llvm::TargetTransformInfoImplBase::prefersVectorizedAddressing () const inline
Definition at line 301 of file TargetTransformInfoImpl.h.
rewriteIntrinsicWithAddressSpace()
Value* llvm::TargetTransformInfoImplBase::rewriteIntrinsicWithAddressSpace (IntrinsicInst * II, Value * OldV, Value * NewV) const inline
Definition at line 119 of file TargetTransformInfoImpl.h.
shouldBuildLookupTables()
bool llvm::TargetTransformInfoImplBase::shouldBuildLookupTables () const inline
Definition at line 326 of file TargetTransformInfoImpl.h.
shouldBuildLookupTablesForConstant()
bool llvm::TargetTransformInfoImplBase::shouldBuildLookupTablesForConstant (Constant * C) const inline
Definition at line 328 of file TargetTransformInfoImpl.h.
shouldBuildRelLookupTables()
bool llvm::TargetTransformInfoImplBase::shouldBuildRelLookupTables () const inline
Definition at line 330 of file TargetTransformInfoImpl.h.
shouldConsiderAddressTypePromotion()
bool llvm::TargetTransformInfoImplBase::shouldConsiderAddressTypePromotion (const Instruction & I, bool & AllowPromotionWithoutCommonHeader) const inline
Definition at line 454 of file TargetTransformInfoImpl.h.
shouldExpandReduction()
bool llvm::TargetTransformInfoImplBase::shouldExpandReduction (const IntrinsicInst * II) const inline
Definition at line 843 of file TargetTransformInfoImpl.h.
shouldMaximizeVectorBandwidth()
bool llvm::TargetTransformInfoImplBase::shouldMaximizeVectorBandwidth (TargetTransformInfo::RegisterKind K) const inline
Definition at line 443 of file TargetTransformInfoImpl.h.
shouldPrefetchAddressSpace()
bool llvm::TargetTransformInfoImplBase::shouldPrefetchAddressSpace (unsigned AS) const inline
Definition at line 492 of file TargetTransformInfoImpl.h.
simplifyDemandedUseBitsIntrinsic()
std::optional<Value *> llvm::TargetTransformInfoImplBase::simplifyDemandedUseBitsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedMask, KnownBits & Known, bool & KnownBitsComputed) const inline
Definition at line 184 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::simplifyDemandedUseBitsIntrinsic().
simplifyDemandedVectorEltsIntrinsic()
std::optional<Value *> llvm::TargetTransformInfoImplBase::simplifyDemandedVectorEltsIntrinsic (InstCombiner & IC, IntrinsicInst & II, APInt DemandedElts, APInt & UndefElts, APInt & UndefElts2, APInt & UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const inline
Definition at line 190 of file TargetTransformInfoImpl.h.
Referenced by llvm::BasicTTIImplBase< AMDGPUTTIImpl >::simplifyDemandedVectorEltsIntrinsic().
supportsEfficientVectorElementLoadStore()
bool llvm::TargetTransformInfoImplBase::supportsEfficientVectorElementLoadStore () const inline
Definition at line 348 of file TargetTransformInfoImpl.h.
supportsScalableVectors()
bool llvm::TargetTransformInfoImplBase::supportsScalableVectors () const inline
Definition at line 849 of file TargetTransformInfoImpl.h.
supportsTailCallFor()
bool llvm::TargetTransformInfoImplBase::supportsTailCallFor (const CallBase * CB) const inline
Definition at line 352 of file TargetTransformInfoImpl.h.
References supportsTailCalls().
supportsTailCalls()
bool llvm::TargetTransformInfoImplBase::supportsTailCalls () const inline
Definition at line 350 of file TargetTransformInfoImpl.h.
Referenced by supportsTailCallFor().
useAA()
bool llvm::TargetTransformInfoImplBase::useAA () const inline
Definition at line 320 of file TargetTransformInfoImpl.h.
useColdCCForColdCall()
bool llvm::TargetTransformInfoImplBase::useColdCCForColdCall (Function & F) const inline
Definition at line 332 of file TargetTransformInfoImpl.h.
useGPUDivergenceAnalysis()
bool llvm::TargetTransformInfoImplBase::useGPUDivergenceAnalysis () const inline
Definition at line 92 of file TargetTransformInfoImpl.h.
Member Data Documentation
DL
const DataLayout& llvm::TargetTransformInfoImplBase::DL protected
Definition at line 38 of file TargetTransformInfoImpl.h.
Referenced by getCastInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), getDataLayout(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getEstimatedNumberOfCaseClusters(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getFPOpCost(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getRegUsageForType(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getScalingFactorCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getStoreMinimumVF(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeLegalizationCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::haveFastSqrt(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isIndexedLoadLegal(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isIndexedStoreLegal(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isLegalAddressingMode(), isLegalNTLoad(), isLegalNTStore(), and llvm::BasicTTIImplBase< AMDGPUTTIImpl >::isTypeLegal().
The documentation for this class was generated from the following file:
include/llvm/Analysis/TargetTransformInfoImpl.h