LLVM: llvm::object::COFFObjectFile Class Reference
llvm::object::COFFObjectFile Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
uintptr_t getSymbolTable () const
uint16_t getMachine () const
uint16_t getSizeOfOptionalHeader () const
uint16_t getCharacteristics () const
uint32_t getTimeDateStamp () const
uint32_t getNumberOfSections () const
uint32_t getPointerToSymbolTable () const
uint32_t getRawNumberOfSymbols () const
uint32_t getNumberOfSymbols () const
uint32_t getStringTableSize () const
const export_directory_table_entry * getExportTable () const
const coff_load_configuration32 * getLoadConfig32 () const
const coff_load_configuration64 * getLoadConfig64 () const
StringRef getRelocationTypeName (uint16_t Type) const
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
section_iterator section_begin () const override
section_iterator section_end () const override
bool is64Bit () const override
const coff_section * getCOFFSection (const SectionRef &Section) const
COFFSymbolRef getCOFFSymbol (const DataRefImpl &Ref) const
COFFSymbolRef getCOFFSymbol (const SymbolRef &Symbol) const
const coff_relocation * getCOFFRelocation (const RelocationRef &Reloc) const
unsigned getSectionID (SectionRef Sec) const
unsigned getSymbolSectionID (SymbolRef Sym) const
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
Triple::ArchType getArch () const override
Expected< uint64_t > getStartAddress () const override
Expected< SubtargetFeatures > getFeatures () const override
import_directory_iterator import_directory_begin () const
import_directory_iterator import_directory_end () const
delay_import_directory_iterator delay_import_directory_begin () const
delay_import_directory_iterator delay_import_directory_end () const
export_directory_iterator export_directory_begin () const
export_directory_iterator export_directory_end () const
base_reloc_iterator base_reloc_begin () const
base_reloc_iterator base_reloc_end () const
const debug_directory * debug_directory_begin () const
const debug_directory * debug_directory_end () const
iterator_range< import_directory_iterator > import_directories () const
iterator_range< delay_import_directory_iterator > delay_import_directories () const
iterator_range< export_directory_iterator > export_directories () const
iterator_range< base_reloc_iterator > base_relocs () const
iterator_range< const debug_directory * > debug_directories () const
const coff_tls_directory32 * getTLSDirectory32 () const
const coff_tls_directory64 * getTLSDirectory64 () const
const dos_header * getDOSHeader () const
const coff_file_header * getCOFFHeader () const
const coff_bigobj_file_header * getCOFFBigObjHeader () const
const pe32_header * getPE32Header () const
const pe32plus_header * getPE32PlusHeader () const
const data_directory * getDataDirectory (uint32_t index) const
Expected< const coff_section * > getSection (int32_t index) const
Expected< COFFSymbolRef > getSymbol (uint32_t index) const
template<typename T >
Error getAuxSymbol (uint32_t index, const T *&Res) const
Expected< StringRef > getSymbolName (COFFSymbolRef Symbol) const
Expected< StringRef > getSymbolName (const coff_symbol_generic *Symbol) const
ArrayRef< uint8_t > getSymbolAuxData (COFFSymbolRef Symbol) const
uint32_t getSymbolIndex (COFFSymbolRef Symbol) const
size_t getSymbolTableEntrySize () const
ArrayRef< coff_relocation > getRelocations (const coff_section *Sec) const
Expected< StringRef > getSectionName (const coff_section *Sec) const
uint64_t getSectionSize (const coff_section *Sec) const
Error getSectionContents (const coff_section *Sec, ArrayRef< uint8_t > &Res) const
uint64_t getImageBase () const
Error getVaPtr (uint64_t VA, uintptr_t &Res) const
Error getRvaPtr (uint32_t Rva, uintptr_t &Res, const char *ErrorContext=nullptr) const
Error getRvaAndSizeAsBytes (uint32_t RVA, uint32_t Size, ArrayRef< uint8_t > &Contents, const char *ErrorContext=nullptr) const
Given an RVA base and size, returns a valid array of bytes or an error code if the RVA and size is not contained completely within a valid section.
Error getHintName (uint32_t Rva, uint16_t &Hint, StringRef &Name) const
Error getDebugPDBInfo (const debug_directory *DebugDir, const codeview::DebugInfo *&Info, StringRef &PDBFileName) const
Get PDB information out of a codeview debug directory entry.
Error getDebugPDBInfo (const codeview::DebugInfo *&Info, StringRef &PDBFileName) const
Get PDB information from an executable.
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
bool is64 () const
StringRef mapDebugSectionName (StringRef Name) const override
Maps a debug section name to a standard DWARF section name.
template<typename coff_symbol_type >
const coff_symbol_type * toSymb (DataRefImpl Ref) const
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
section_iterator_range sections () const
virtual bool hasDebugInfo () const
virtual std::optional< StringRef > tryGetCPUName () const
virtual void setARMSubArch (Triple &TheTriple) const
Triple makeTriple () const
Create a triple from the data in this object file.
bool isReflectionSectionStrippable (llvm::binaryformat::Swift5ReflectionSectionKind ReflectionSectionKind) const
True if the reflection section can be stripped by the linker.
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
virtual Error initContent ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isOffloadFile () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static Expected< std::unique_ptr< COFFObjectFile > > create (MemoryBufferRef Object)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type, bool InitContent=true)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object, bool InitContent=true)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context, bool InitContent=true)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static bool isSymbolicFile (file_magic Type, const LLVMContext *Context)
Static Public Member Functions inherited from llvm::object::Binary
static Error checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Protected Member Functions
void moveSymbolNext (DataRefImpl &Symb) const override
Expected< StringRef > getSymbolName (DataRefImpl Symb) const override
Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const override
uint32_t getSymbolAlignment (DataRefImpl Symb) const override
uint64_t getSymbolValueImpl (DataRefImpl Symb) const override
uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const override
Expected< uint32_t > getSymbolFlags (DataRefImpl Symb) const override
Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const override
Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const override
void moveSectionNext (DataRefImpl &Sec) const override
Expected< StringRef > getSectionName (DataRefImpl Sec) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionIndex (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
bool isSectionCompressed (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
bool isDebugSection (DataRefImpl Sec) const override
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
void moveRelocationNext (DataRefImpl &Rel) const override
uint64_t getRelocationOffset (DataRefImpl Rel) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
uint64_t getRelocationType (DataRefImpl Rel) const override
void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual Expected< section_iterator > getRelocatedSection (DataRefImpl Sec) const
virtual llvm::binaryformat::Swift5ReflectionSectionKind mapReflectionSectionNameToEnumValue (StringRef SectionName) const
Expected< uint64_t > getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Friends
class ImportDirectoryEntryRef
class ExportDirectoryEntryRef
Additional Inherited Members
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_COFFImportFile, ID_IR,
ID_TapiUniversal, ID_TapiFile, ID_Minidump, ID_WinRes,
ID_Offload, ID_StartObjects, ID_COFF, ID_XCOFF32,
ID_XCOFF64, ID_ELF32L, ID_ELF32B, ID_ELF64L,
ID_ELF64B, ID_MachO32L, ID_MachO32B, ID_MachO64L,
ID_MachO64B, ID_Wasm, ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 788 of file COFF.h.
Member Function Documentation
base_reloc_begin()
base_reloc_iterator COFFObjectFile::base_reloc_begin () const
Definition at line 995 of file COFFObjectFile.cpp.
Referenced by base_relocs().
base_reloc_end()
base_reloc_iterator COFFObjectFile::base_reloc_end () const
Definition at line 999 of file COFFObjectFile.cpp.
Referenced by base_relocs().
base_relocs()
iterator_range< base_reloc_iterator > COFFObjectFile::base_relocs () const
Definition at line 1062 of file COFFObjectFile.cpp.
References base_reloc_begin(), base_reloc_end(), and llvm::make_range().
classof()
static bool llvm::object::COFFObjectFile::classof (const Binary * v) inline static
Definition at line 1109 of file COFF.h.
References llvm::object::Binary::isCOFF().
create()
Expected< std::unique_ptr< COFFObjectFile > > COFFObjectFile::create (MemoryBufferRef Object) static
Definition at line 760 of file COFFObjectFile.cpp.
References E, move, and llvm::Object.
Referenced by llvm::object::ObjectFile::createCOFFObjectFile(), and getCOFFFileMachine().
debug_directories()
iterator_range<const debug_directory *> llvm::object::COFFObjectFile::debug_directories () const inline
Definition at line 1009 of file COFF.h.
References debug_directory_begin(), debug_directory_end(), and llvm::make_range().
debug_directory_begin()
const debug_directory* llvm::object::COFFObjectFile::debug_directory_begin () const inline
Definition at line 997 of file COFF.h.
Referenced by debug_directories().
debug_directory_end()
const debug_directory* llvm::object::COFFObjectFile::debug_directory_end () const inline
Definition at line 1000 of file COFF.h.
Referenced by debug_directories().
delay_import_directories()
iterator_range< delay_import_directory_iterator > COFFObjectFile::delay_import_directories () const
Definition at line 1052 of file COFFObjectFile.cpp.
References delay_import_directory_begin(), delay_import_directory_end(), and llvm::make_range().
delay_import_directory_begin()
delay_import_directory_iterator COFFObjectFile::delay_import_directory_begin () const
Definition at line 956 of file COFFObjectFile.cpp.
Referenced by delay_import_directories().
delay_import_directory_end()
delay_import_directory_iterator COFFObjectFile::delay_import_directory_end () const
Definition at line 962 of file COFFObjectFile.cpp.
Referenced by delay_import_directories().
export_directories()
iterator_range< export_directory_iterator > COFFObjectFile::export_directories () const
Definition at line 1058 of file COFFObjectFile.cpp.
References export_directory_begin(), export_directory_end(), and llvm::make_range().
export_directory_begin()
export_directory_iterator COFFObjectFile::export_directory_begin () const
Definition at line 968 of file COFFObjectFile.cpp.
References ExportDirectoryEntryRef.
Referenced by export_directories().
export_directory_end()
export_directory_iterator COFFObjectFile::export_directory_end () const
Definition at line 973 of file COFFObjectFile.cpp.
References llvm::object::export_directory_table_entry::AddressTableEntries, ExportDirectoryEntryRef, and llvm::Ref.
Referenced by export_directories().
getArch()
Triple::ArchType COFFObjectFile::getArch () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1024 of file COFFObjectFile.cpp.
References llvm::Triple::aarch64, getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64EC, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::Triple::thumb, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by getBytesInAddress().
getAuxSymbol()
template<typename T > Error llvm::object::COFFObjectFile::getAuxSymbol (uint32_t index, const T *& Res) const inline
Definition at line 1047 of file COFF.h.
References E, getSymbol(), index, S, llvm::Error::success(), and T.
getBytesInAddress()
uint8_t COFFObjectFile::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 1003 of file COFFObjectFile.cpp.
References llvm::Triple::aarch64, getArch(), and llvm::Triple::x86_64.
getCharacteristics()
uint16_t llvm::object::COFFObjectFile::getCharacteristics () const inline
Definition at line 866 of file COFF.h.
References llvm::object::coff_file_header::Characteristics, llvm::object::coff_file_header::isImportLibrary(), and llvm_unreachable.
getCOFFBigObjHeader()
const coff_bigobj_file_header* llvm::object::COFFObjectFile::getCOFFBigObjHeader () const inline
Definition at line 1027 of file COFF.h.
getCOFFHeader()
const coff_file_header* llvm::object::COFFObjectFile::getCOFFHeader () const inline
Definition at line 1026 of file COFF.h.
getCOFFRelocation()
const coff_relocation * COFFObjectFile::getCOFFRelocation (const RelocationRef & Reloc) const
Definition at line 1257 of file COFFObjectFile.cpp.
References llvm::object::RelocationRef::getRawDataRefImpl().
getCOFFSection()
const coff_section * COFFObjectFile::getCOFFSection (const SectionRef & Section) const
Definition at line 1240 of file COFFObjectFile.cpp.
Referenced by llvm::jitlink::COFFLinkGraphBuilder::forEachRelocation(), getRvaAndSizeAsBytes(), and getRvaPtr().
getCOFFSymbol() [1/2]
COFFSymbolRef COFFObjectFile::getCOFFSymbol (const DataRefImpl & Ref) const
Definition at line 1244 of file COFFObjectFile.cpp.
References llvm_unreachable, and llvm::Ref.
Referenced by llvm::orc::getCOFFObjectFileSymbolInfo(), getCOFFSymbol(), getCommonSymbolSizeImpl(), getSymbolAddress(), getSymbolAlignment(), getSymbolFlags(), getSymbolSection(), getSymbolSectionID(), getSymbolType(), and getSymbolValueImpl().
getCOFFSymbol() [2/2]
COFFSymbolRef COFFObjectFile::getCOFFSymbol (const SymbolRef & Symbol) const
Definition at line 1252 of file COFFObjectFile.cpp.
References getCOFFSymbol().
getCommonSymbolSizeImpl()
uint64_t COFFObjectFile::getCommonSymbolSizeImpl (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 241 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getValue(), and llvm::Ref.
getDataDirectory()
const data_directory * COFFObjectFile::getDataDirectory (uint32_t index) const
Definition at line 1066 of file COFFObjectFile.cpp.
References assert(), Index, llvm::object::pe32_header::NumberOfRvaAndSize, and llvm::object::pe32plus_header::NumberOfRvaAndSize.
Referenced by llvm::object::ExportDirectoryEntryRef::isForwarder().
getDebugPDBInfo() [1/2]
Error llvm::object::COFFObjectFile::getDebugPDBInfo (const codeview::DebugInfo *& Info, StringRef & PDBFileName) const
Get PDB information from an executable.
If the information is not present, Info will be set to nullptr and PDBFileName will be empty. An error is returned only on corrupt object files. Convenience accessor that can be used if the debug directory is not already handy.
getDebugPDBInfo() [2/2]
Error llvm::object::COFFObjectFile::getDebugPDBInfo (const debug_directory * DebugDir, const codeview::DebugInfo *& Info, StringRef & PDBFileName) const
Get PDB information out of a codeview debug directory entry.
Referenced by getPdbPathFromExe().
getDOSHeader()
const dos_header* llvm::object::COFFObjectFile::getDOSHeader () const inline
Definition at line 1020 of file COFF.h.
References llvm::object::ObjectFile::base().
Referenced by getSectionSize().
getExportTable()
const export_directory_table_entry* llvm::object::COFFObjectFile::getExportTable () const inline
Definition at line 917 of file COFF.h.
getFeatures()
Expected<SubtargetFeatures> llvm::object::COFFObjectFile::getFeatures () const inline override virtual
Implements llvm::object::ObjectFile.
Definition at line 985 of file COFF.h.
getFileFormatName()
StringRef COFFObjectFile::getFileFormatName () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1007 of file COFFObjectFile.cpp.
References getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64EC, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, and llvm::COFF::IMAGE_FILE_MACHINE_I386.
getHintName()
Error COFFObjectFile::getHintName (uint32_t Rva, uint16_t & Hint, StringRef & Name) const
Definition at line 535 of file COFFObjectFile.cpp.
References E, getRvaPtr(), Ptr, and llvm::Error::success().
getImageBase()
uint64_t COFFObjectFile::getImageBase () const
Definition at line 455 of file COFFObjectFile.cpp.
References llvm::object::pe32_header::ImageBase, and llvm::object::pe32plus_header::ImageBase.
Referenced by getSectionAddress(), getSymbolAddress(), and getVaPtr().
getLoadConfig32()
const coff_load_configuration32* llvm::object::COFFObjectFile::getLoadConfig32 () const inline
Definition at line 921 of file COFF.h.
References assert(), and is64().
getLoadConfig64()
const coff_load_configuration64* llvm::object::COFFObjectFile::getLoadConfig64 () const inline
Definition at line 926 of file COFF.h.
References assert(), and is64().
getMachine()
uint16_t llvm::object::COFFObjectFile::getMachine () const inline
Definition at line 848 of file COFF.h.
References llvm_unreachable, llvm::object::coff_file_header::Machine, and llvm::object::coff_bigobj_file_header::Machine.
Referenced by getArch(), getFileFormatName(), and getRelocationTypeName().
getNumberOfSections()
uint32_t llvm::object::COFFObjectFile::getNumberOfSections () const inline
Definition at line 884 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::NumberOfSections, and llvm::object::coff_bigobj_file_header::NumberOfSections.
Referenced by llvm::orc::getCOFFObjectFileSymbolInfo(), getSection(), and section_end().
getNumberOfSymbols()
uint32_t llvm::object::COFFObjectFile::getNumberOfSymbols () const inline
Definition at line 909 of file COFF.h.
References getRawNumberOfSymbols().
Referenced by getRelocationSymbol(), getSymbol(), getSymbolAuxData(), and getSymbolIndex().
getPE32Header()
const pe32_header* llvm::object::COFFObjectFile::getPE32Header () const inline
Definition at line 1030 of file COFF.h.
getPE32PlusHeader()
const pe32plus_header* llvm::object::COFFObjectFile::getPE32PlusHeader () const inline
Definition at line 1031 of file COFF.h.
getPointerToSymbolTable()
uint32_t llvm::object::COFFObjectFile::getPointerToSymbolTable () const inline
Definition at line 892 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::PointerToSymbolTable, and llvm::object::coff_bigobj_file_header::PointerToSymbolTable.
Referenced by getSymbolAuxData(), and toSymb().
getRawNumberOfSymbols()
uint32_t llvm::object::COFFObjectFile::getRawNumberOfSymbols () const inline
Definition at line 901 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, llvm::object::coff_file_header::NumberOfSymbols, and llvm::object::coff_bigobj_file_header::NumberOfSymbols.
Referenced by getNumberOfSymbols().
getRelocationOffset()
uint64_t COFFObjectFile::getRelocationOffset (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1215 of file COFFObjectFile.cpp.
getRelocations()
ArrayRef< coff_relocation > COFFObjectFile::getRelocations (const coff_section * Sec) const
Definition at line 1262 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, getFirstReloc(), and getNumberOfRelocations().
getRelocationSymbol()
symbol_iterator COFFObjectFile::getRelocationSymbol (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1220 of file COFFObjectFile.cpp.
References getNumberOfSymbols(), llvm_unreachable, llvm::Ref, symbol_end(), and llvm::object::ObjectFile::SymbolRef.
getRelocationType()
uint64_t COFFObjectFile::getRelocationType (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1234 of file COFFObjectFile.cpp.
getRelocationTypeName() [1/2]
void llvm::object::COFFObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override protected virtual
Implements llvm::object::ObjectFile.
getRelocationTypeName() [2/2]
StringRef COFFObjectFile::getRelocationTypeName (uint16_t Type) const
Definition at line 1271 of file COFFObjectFile.cpp.
References getMachine(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64EC, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMAGE_REL_AMD64_ABSOLUTE, llvm::COFF::IMAGE_REL_AMD64_ADDR32, llvm::COFF::IMAGE_REL_AMD64_ADDR32NB, llvm::COFF::IMAGE_REL_AMD64_ADDR64, llvm::COFF::IMAGE_REL_AMD64_PAIR, llvm::COFF::IMAGE_REL_AMD64_REL32, llvm::COFF::IMAGE_REL_AMD64_REL32_1, llvm::COFF::IMAGE_REL_AMD64_REL32_2, llvm::COFF::IMAGE_REL_AMD64_REL32_3, llvm::COFF::IMAGE_REL_AMD64_REL32_4, llvm::COFF::IMAGE_REL_AMD64_REL32_5, llvm::COFF::IMAGE_REL_AMD64_SECREL, llvm::COFF::IMAGE_REL_AMD64_SECREL7, llvm::COFF::IMAGE_REL_AMD64_SECTION, llvm::COFF::IMAGE_REL_AMD64_SREL32, llvm::COFF::IMAGE_REL_AMD64_SSPAN32, llvm::COFF::IMAGE_REL_AMD64_TOKEN, llvm::COFF::IMAGE_REL_ARM64_ABSOLUTE, llvm::COFF::IMAGE_REL_ARM64_ADDR32, llvm::COFF::IMAGE_REL_ARM64_ADDR32NB, llvm::COFF::IMAGE_REL_ARM64_ADDR64, llvm::COFF::IMAGE_REL_ARM64_BRANCH14, llvm::COFF::IMAGE_REL_ARM64_BRANCH19, llvm::COFF::IMAGE_REL_ARM64_BRANCH26, llvm::COFF::IMAGE_REL_ARM64_PAGEBASE_REL21, llvm::COFF::IMAGE_REL_ARM64_PAGEOFFSET_12A, llvm::COFF::IMAGE_REL_ARM64_PAGEOFFSET_12L, llvm::COFF::IMAGE_REL_ARM64_REL21, llvm::COFF::IMAGE_REL_ARM64_REL32, llvm::COFF::IMAGE_REL_ARM64_SECREL, llvm::COFF::IMAGE_REL_ARM64_SECREL_HIGH12A, llvm::COFF::IMAGE_REL_ARM64_SECREL_LOW12A, llvm::COFF::IMAGE_REL_ARM64_SECREL_LOW12L, llvm::COFF::IMAGE_REL_ARM64_SECTION, llvm::COFF::IMAGE_REL_ARM64_TOKEN, llvm::COFF::IMAGE_REL_ARM_ABSOLUTE, llvm::COFF::IMAGE_REL_ARM_ADDR32, llvm::COFF::IMAGE_REL_ARM_ADDR32NB, llvm::COFF::IMAGE_REL_ARM_BLX11, llvm::COFF::IMAGE_REL_ARM_BLX23T, llvm::COFF::IMAGE_REL_ARM_BLX24, llvm::COFF::IMAGE_REL_ARM_BRANCH11, llvm::COFF::IMAGE_REL_ARM_BRANCH20T, llvm::COFF::IMAGE_REL_ARM_BRANCH24, llvm::COFF::IMAGE_REL_ARM_BRANCH24T, llvm::COFF::IMAGE_REL_ARM_MOV32A, llvm::COFF::IMAGE_REL_ARM_MOV32T, llvm::COFF::IMAGE_REL_ARM_PAIR, llvm::COFF::IMAGE_REL_ARM_REL32, llvm::COFF::IMAGE_REL_ARM_SECREL, llvm::COFF::IMAGE_REL_ARM_SECTION, llvm::COFF::IMAGE_REL_ARM_TOKEN, llvm::COFF::IMAGE_REL_I386_ABSOLUTE, llvm::COFF::IMAGE_REL_I386_DIR16, llvm::COFF::IMAGE_REL_I386_DIR32, llvm::COFF::IMAGE_REL_I386_DIR32NB, llvm::COFF::IMAGE_REL_I386_REL16, llvm::COFF::IMAGE_REL_I386_REL32, llvm::COFF::IMAGE_REL_I386_SECREL, llvm::COFF::IMAGE_REL_I386_SECREL7, llvm::COFF::IMAGE_REL_I386_SECTION, llvm::COFF::IMAGE_REL_I386_SEG12, llvm::COFF::IMAGE_REL_I386_TOKEN, and LLVM_COFF_SWITCH_RELOC_TYPE_NAME.
getRvaAndSizeAsBytes()
Error COFFObjectFile::getRvaAndSizeAsBytes (uint32_t RVA, uint32_t Size, ArrayRef< uint8_t > & Contents, const char * ErrorContext = nullptr) const
Given an RVA base and size, returns a valid array of bytes or an error code if the RVA and size is not contained completely within a valid section.
Definition at line 507 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::createStringError(), getCOFFSection(), llvm::object::parse_failed, S, llvm::object::ObjectFile::sections(), and llvm::Error::success().
getRvaPtr()
Error COFFObjectFile::getRvaPtr (uint32_t Rva, uintptr_t & Res, const char * ErrorContext = nullptr) const
Definition at line 473 of file COFFObjectFile.cpp.
References Addr, llvm::object::ObjectFile::base(), llvm::createStringError(), getCOFFSection(), llvm::object::parse_failed, S, llvm::object::ObjectFile::sections(), and llvm::Error::success().
Referenced by llvm::object::ExportDirectoryEntryRef::getDllName(), llvm::object::ExportDirectoryEntryRef::getExportRVA(), llvm::object::ExportDirectoryEntryRef::getForwardTo(), getHintName(), llvm::object::DelayImportDirectoryEntryRef::getImportAddress(), llvm::object::ImportDirectoryEntryRef::getName(), llvm::object::DelayImportDirectoryEntryRef::getName(), llvm::object::ImportedSymbolRef::getOrdinal(), llvm::object::ExportDirectoryEntryRef::getSymbolName(), llvm::object::ImportedSymbolRef::getSymbolName(), and getVaPtr().
getSection()
Expected< const coff_section * > COFFObjectFile::getSection (int32_t index) const
Definition at line 1077 of file COFFObjectFile.cpp.
References llvm::createStringError(), getNumberOfSections(), llvm::COFF::isReservedSectionNumber(), and llvm::object::parse_failed.
Referenced by llvm::orc::getCOFFObjectFileSymbolInfo(), getSymbolAddress(), and getSymbolSection().
getSectionAddress()
uint64_t COFFObjectFile::getSectionAddress (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 275 of file COFFObjectFile.cpp.
References getImageBase(), llvm::Ref, uint64_t, and llvm::object::coff_section::VirtualAddress.
getSectionAlignment()
uint64_t COFFObjectFile::getSectionAlignment (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 302 of file COFFObjectFile.cpp.
References llvm::object::coff_section::getAlignment(), and llvm::Ref.
getSectionContents() [1/2]
Error COFFObjectFile::getSectionContents (const coff_section * Sec, ArrayRef< uint8_t > & Res) const
Definition at line 1188 of file COFFObjectFile.cpp.
References llvm::ArrayRef(), llvm::object::ObjectFile::base(), llvm::object::Binary::checkOffset(), llvm::object::Binary::Data, E, getSectionSize(), llvm::object::coff_section::PointerToRawData, llvm::COFF::SectionSize, and llvm::Error::success().
getSectionContents() [2/2]
Expected<ArrayRef<uint8_t> > llvm::object::COFFObjectFile::getSectionContents (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
getSectionID()
unsigned COFFObjectFile::getSectionID (SectionRef Sec) const
Definition at line 342 of file COFFObjectFile.cpp.
References assert(), llvm::object::SectionRef::getRawDataRefImpl(), and llvm::object::DataRefImpl::p.
getSectionIndex()
uint64_t COFFObjectFile::getSectionIndex (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 285 of file COFFObjectFile.cpp.
getSectionName() [1/2]
Expected< StringRef > COFFObjectFile::getSectionName (const coff_section * Sec) const
Definition at line 1151 of file COFFObjectFile.cpp.
References llvm::createStringError(), decodeBase64StringEntry(), llvm::object::coff_section::Name, llvm::COFF::NameSize, llvm::object::parse_failed, and llvm::StringRef::split().
getSectionName() [2/2]
Expected<StringRef> llvm::object::COFFObjectFile::getSectionName (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Referenced by llvm::jitlink::COFFLinkGraphBuilder::forEachRelocation(), and isDebugSection().
getSectionSize() [1/2]
uint64_t COFFObjectFile::getSectionSize (const coff_section * Sec) const
Definition at line 1172 of file COFFObjectFile.cpp.
References getDOSHeader(), llvm::min(), llvm::object::coff_section::SizeOfRawData, and llvm::object::coff_section::VirtualSize.
getSectionSize() [2/2]
uint64_t llvm::object::COFFObjectFile::getSectionSize (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Referenced by getSectionContents().
getSizeOfOptionalHeader()
uint16_t llvm::object::COFFObjectFile::getSizeOfOptionalHeader () const inline
Definition at line 856 of file COFF.h.
References llvm::object::coff_file_header::isImportLibrary(), llvm_unreachable, and llvm::object::coff_file_header::SizeOfOptionalHeader.
getStartAddress()
Expected< uint64_t > COFFObjectFile::getStartAddress () const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 1040 of file COFFObjectFile.cpp.
References llvm::object::pe32_header::AddressOfEntryPoint.
getStringTableSize()
uint32_t llvm::object::COFFObjectFile::getStringTableSize () const inline
Definition at line 915 of file COFF.h.
getSymbol()
Expected<COFFSymbolRef> llvm::object::COFFObjectFile::getSymbol (uint32_t index) const inline
Definition at line 1036 of file COFF.h.
References llvm::errorCodeToError(), getNumberOfSymbols(), index, and llvm::object::parse_failed.
Referenced by getAuxSymbol().
getSymbolAddress()
Expected< uint64_t > COFFObjectFile::getSymbolAddress (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 166 of file COFFObjectFile.cpp.
References llvm::cantFail(), getCOFFSymbol(), getImageBase(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::object::ObjectFile::getSymbolValue(), llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::COFF::isReservedSectionNumber(), llvm::Ref, and uint64_t.
getSymbolAlignment()
uint32_t COFFObjectFile::getSymbolAlignment (DataRefImpl Symb) const override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 159 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getValue(), llvm::min(), llvm::PowerOf2Ceil(), llvm::Ref, and uint64_t.
getSymbolAuxData()
ArrayRef< uint8_t > COFFObjectFile::getSymbolAuxData (COFFSymbolRef Symbol) const
Definition at line 1118 of file COFFObjectFile.cpp.
References llvm::ArrayRef(), assert(), llvm::object::ObjectFile::base(), getNumberOfSymbols(), getPointerToSymbolTable(), getSymbolTableEntrySize(), and llvm::report_fatal_error().
getSymbolFlags()
Expected< uint32_t > COFFObjectFile::getSymbolFlags (DataRefImpl Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 210 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::object::COFFSymbolRef::getWeakExternal(), llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::COFF::IMAGE_WEAK_EXTERN_SEARCH_ALIAS, llvm::object::COFFSymbolRef::isCommon(), llvm::object::COFFSymbolRef::isExternal(), llvm::object::COFFSymbolRef::isFileRecord(), llvm::object::COFFSymbolRef::isSectionDefinition(), llvm::object::COFFSymbolRef::isUndefined(), llvm::object::COFFSymbolRef::isWeakExternal(), llvm::Ref, llvm::object::BasicSymbolRef::SF_Absolute, llvm::object::BasicSymbolRef::SF_Common, llvm::object::BasicSymbolRef::SF_FormatSpecific, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Undefined, and llvm::object::BasicSymbolRef::SF_Weak.
getSymbolIndex()
uint32_t COFFObjectFile::getSymbolIndex (COFFSymbolRef Symbol) const
Definition at line 1140 of file COFFObjectFile.cpp.
References assert(), getNumberOfSymbols(), getSymbolTable(), getSymbolTableEntrySize(), and Index.
getSymbolName() [1/3]
Expected< StringRef > COFFObjectFile::getSymbolName (COFFSymbolRef Symbol) const
Definition at line 1099 of file COFFObjectFile.cpp.
References getSymbolName().
getSymbolName() [2/3]
Expected< StringRef > COFFObjectFile::getSymbolName (const coff_symbol_generic * Symbol) const
Definition at line 1104 of file COFFObjectFile.cpp.
References llvm::COFF::NameSize.
getSymbolName() [3/3]
Expected<StringRef> llvm::object::COFFObjectFile::getSymbolName (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Referenced by getSymbolName().
getSymbolSection()
Expected< section_iterator > COFFObjectFile::getSymbolSection (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 247 of file COFFObjectFile.cpp.
References getCOFFSymbol(), getSection(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::COFF::isReservedSectionNumber(), llvm::Ref, llvm::MipsISD::Ret, section_end(), llvm::object::ObjectFile::SectionRef, and llvm::Expected< T >::takeError().
getSymbolSectionID()
unsigned COFFObjectFile::getSymbolSectionID (SymbolRef Sym) const
Definition at line 259 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::BasicSymbolRef::getRawDataRefImpl(), and llvm::object::COFFSymbolRef::getSectionNumber().
getSymbolTable()
uintptr_t llvm::object::COFFObjectFile::getSymbolTable () const inline
Definition at line 840 of file COFF.h.
Referenced by getSymbolIndex(), and symbol_begin().
getSymbolTableEntrySize()
size_t llvm::object::COFFObjectFile::getSymbolTableEntrySize () const inline
Definition at line 1062 of file COFF.h.
References llvm_unreachable.
Referenced by getSymbolAuxData(), and getSymbolIndex().
getSymbolType()
Expected< SymbolRef::Type > COFFObjectFile::getSymbolType (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 187 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getComplexType(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::COFF::IMAGE_SYM_DEBUG, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::object::COFFSymbolRef::isAnyUndefined(), llvm::object::COFFSymbolRef::isCommon(), llvm::object::COFFSymbolRef::isFileRecord(), llvm::COFF::isReservedSectionNumber(), llvm::object::COFFSymbolRef::isSectionDefinition(), llvm::Ref, llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_File, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, and llvm::object::SymbolRef::ST_Unknown.
getSymbolValueImpl()
uint64_t COFFObjectFile::getSymbolValueImpl (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 155 of file COFFObjectFile.cpp.
References getCOFFSymbol(), llvm::object::COFFSymbolRef::getValue(), and llvm::Ref.
getTimeDateStamp()
uint32_t llvm::object::COFFObjectFile::getTimeDateStamp () const inline
Definition at line 876 of file COFF.h.
References llvm_unreachable, llvm::object::coff_file_header::TimeDateStamp, and llvm::object::coff_bigobj_file_header::TimeDateStamp.
getTLSDirectory32()
const coff_tls_directory32* llvm::object::COFFObjectFile::getTLSDirectory32 () const inline
Definition at line 1013 of file COFF.h.
getTLSDirectory64()
const coff_tls_directory64* llvm::object::COFFObjectFile::getTLSDirectory64 () const inline
Definition at line 1016 of file COFF.h.
getVaPtr()
Error COFFObjectFile::getVaPtr (uint64_t VA, uintptr_t & Res) const
Definition at line 465 of file COFFObjectFile.cpp.
References Addr, assert(), getImageBase(), getRvaPtr(), and uint64_t.
import_directories()
iterator_range< import_directory_iterator > COFFObjectFile::import_directories () const
Definition at line 1047 of file COFFObjectFile.cpp.
References import_directory_begin(), import_directory_end(), and llvm::make_range().
import_directory_begin()
import_directory_iterator COFFObjectFile::import_directory_begin () const
Definition at line 941 of file COFFObjectFile.cpp.
References import_directory_end(), ImportDirectoryEntryRef, and llvm::object::coff_import_directory_table_entry::isNull().
Referenced by import_directories().
import_directory_end()
import_directory_iterator COFFObjectFile::import_directory_end () const
Definition at line 950 of file COFFObjectFile.cpp.
References ImportDirectoryEntryRef.
Referenced by import_directories(), and import_directory_begin().
is64()
bool llvm::object::COFFObjectFile::is64 () const inline
Definition at line 1105 of file COFF.h.
Referenced by llvm::object::DelayImportDirectoryEntryRef::getImportAddress(), getLoadConfig32(), and getLoadConfig64().
is64Bit()
bool llvm::object::COFFObjectFile::is64Bit () const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 972 of file COFF.h.
isDebugSection()
bool COFFObjectFile::isDebugSection (DataRefImpl Sec) const override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 331 of file COFFObjectFile.cpp.
References llvm::consumeError(), llvm::Expected< T >::get(), getSectionName(), llvm::Ref, and llvm::Expected< T >::takeError().
isRelocatableObject()
bool COFFObjectFile::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 1375 of file COFFObjectFile.cpp.
isSectionBSS()
bool COFFObjectFile::isSectionBSS (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 321 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, and llvm::Ref.
isSectionCompressed()
bool COFFObjectFile::isSectionCompressed (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 307 of file COFFObjectFile.cpp.
isSectionData()
bool COFFObjectFile::isSectionData (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 316 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, and llvm::Ref.
isSectionText()
bool COFFObjectFile::isSectionText (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 311 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, llvm::COFF::IMAGE_SCN_CNT_CODE, and llvm::Ref.
isSectionVirtual()
bool COFFObjectFile::isSectionVirtual (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 349 of file COFFObjectFile.cpp.
References llvm::object::coff_section::PointerToRawData, and llvm::Ref.
mapDebugSectionName()
StringRef COFFObjectFile::mapDebugSectionName (StringRef Name) const override virtual
Maps a debug section name to a standard DWARF section name.
Reimplemented from llvm::object::ObjectFile.
Definition at line 1379 of file COFFObjectFile.cpp.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
moveRelocationNext()
void COFFObjectFile::moveRelocationNext (DataRefImpl & Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1210 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
moveSectionNext()
void COFFObjectFile::moveSectionNext (DataRefImpl & Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 264 of file COFFObjectFile.cpp.
References llvm::Ref.
moveSymbolNext()
void COFFObjectFile::moveSymbolNext (DataRefImpl & Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 136 of file COFFObjectFile.cpp.
section_begin()
section_iterator COFFObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 981 of file COFFObjectFile.cpp.
References llvm::MipsISD::Ret, and llvm::object::ObjectFile::SectionRef.
section_end()
section_iterator COFFObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 987 of file COFFObjectFile.cpp.
References getNumberOfSections(), llvm::object::coff_file_header::isImportLibrary(), llvm::MipsISD::Ret, and llvm::object::ObjectFile::SectionRef.
Referenced by getSymbolSection().
section_rel_begin()
relocation_iterator COFFObjectFile::section_rel_begin (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 396 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::sys::path::begin(), llvm::object::Binary::Data, getFirstReloc(), llvm::Ref, llvm::object::ObjectFile::RelocationRef, llvm::report_fatal_error(), llvm::MipsISD::Ret, and llvm::object::coff_section::VirtualAddress.
section_rel_end()
relocation_iterator COFFObjectFile::section_rel_end (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 406 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, getFirstReloc(), getNumberOfRelocations(), I, llvm::Ref, llvm::object::ObjectFile::RelocationRef, and llvm::MipsISD::Ret.
symbol_begin()
basic_symbol_iterator COFFObjectFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 928 of file COFFObjectFile.cpp.
References getSymbolTable(), llvm::MipsISD::Ret, and llvm::object::ObjectFile::SymbolRef.
symbol_end()
basic_symbol_iterator COFFObjectFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 934 of file COFFObjectFile.cpp.
References llvm::MipsISD::Ret, and llvm::object::ObjectFile::SymbolRef.
Referenced by getRelocationSymbol().
toSymb()
template<typename coff_symbol_type > const coff_symbol_type* llvm::object::COFFObjectFile::toSymb (DataRefImpl Ref) const
Definition at line 102 of file COFFObjectFile.cpp.
References Addr, assert(), llvm::object::ObjectFile::base(), llvm::object::Binary::checkOffset(), llvm::object::Binary::Data, getPointerToSymbolTable(), and llvm::Ref.
Friends And Related Function Documentation
ExportDirectoryEntryRef
friend class ExportDirectoryEntryRef friend
Definition at line 793 of file COFF.h.
Referenced by export_directory_begin(), and export_directory_end().
ImportDirectoryEntryRef
friend class ImportDirectoryEntryRef friend
Definition at line 792 of file COFF.h.
Referenced by import_directory_begin(), and import_directory_end().
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp