LLVM: TransferTracker Class Reference
TransferTracker Class Reference
Tracker for converting machine value locations and variable values into variable locations (the output of LiveDebugValues), recorded as DBG_VALUEs specifying block live-in locations and transfers within blocks.
Classes
class LocationAndQuality
struct ResolvedDbgValue
Stores the resolved operands (machine locations and constants) and qualifying meta-information needed to construct a concrete DBG_VALUE-like instruction.
struct Transfer
Record of all changes in variable locations at a block position.
struct UseBeforeDef
Record of a use-before-def: created when a value that's live-in to the current block isn't available in any machine location, but it will be defined in this block.
Public Types
enum LocationQuality : unsigned char {
LocationQuality::Illegal = 0, LocationQuality::Register, LocationQuality::CalleeSavedRegister, LocationQuality::SpillSlot,
LocationQuality::Best = SpillSlot
}
Public Member Functions
TransferTracker (const TargetInstrInfo *TII, MLocTracker *MTracker, MachineFunction &MF, const TargetRegisterInfo &TRI, const BitVector &CalleeSavedRegs, const TargetPassConfig &TPC)
bool isCalleeSaved (LocIdx L) const
std::optional< LocationQuality > getLocQualityIfBetter (LocIdx L, LocationQuality Min) const
void loadVarInloc (MachineBasicBlock &MBB, DbgOpIDMap &DbgOpStore, const DenseMap< ValueIDNum, LocationAndQuality > &ValueToLoc, DebugVariable Var, DbgValue Value)
For a variable Var with the live-in value Value, attempts to resolve the DbgValue to a concrete DBG_VALUE, emitting that value and loading the tracking information to track Var throughout the block.
void loadInlocs (MachineBasicBlock &MBB, ValueTable &MLocs, DbgOpIDMap &DbgOpStore, const SmallVectorImpl< std::pair< DebugVariable, DbgValue >> &VLocs, unsigned NumLocs)
Load object with live-in variable values.
void addUseBeforeDef (const DebugVariable &Var, const DbgValueProperties &Properties, const SmallVectorImpl< DbgOp > &DbgOps, unsigned Inst)
Record that Var has value ID, a value that becomes available later in the function.
void checkInstForNewValues (unsigned Inst, MachineBasicBlock::iterator pos)
After the instruction at index Inst and position pos has been processed, check whether it defines a variable value in a use-before-def.
void flushDbgValues (MachineBasicBlock::iterator Pos, MachineBasicBlock *MBB)
Helper to move created DBG_VALUEs into Transfers collection.
bool isEntryValueVariable (const DebugVariable &Var, const DIExpression *Expr) const
bool isEntryValueValue (const ValueIDNum &Val) const
bool recoverAsEntryValue (const DebugVariable &Var, const DbgValueProperties &Prop, const ValueIDNum &Num)
void redefVar (const MachineInstr &MI)
Change a variable value after encountering a DBG_VALUE inside a block.
void redefVar (const MachineInstr &MI, const DbgValueProperties &Properties, SmallVectorImpl< ResolvedDbgOp > &NewLocs)
Handle a change in variable location within a block.
void clobberMloc (LocIdx MLoc, MachineBasicBlock::iterator Pos, bool MakeUndef=true)
Account for a location mloc being clobbered.
void clobberMloc (LocIdx MLoc, ValueIDNum OldValue, MachineBasicBlock::iterator Pos, bool MakeUndef=true)
Overload that takes an explicit value OldValue for when the value in MLoc has changed and the TransferTracker's locations have not been updated yet.
void transferMlocs (LocIdx Src, LocIdx Dst, MachineBasicBlock::iterator Pos)
Transfer variables based on Src to be based on Dst.
MachineInstrBuilder emitMOLoc (const MachineOperand &MO, const DebugVariable &Var, const DbgValueProperties &Properties)
Public Attributes
const TargetInstrInfo * TII
const TargetLowering * TLI
MLocTracker * MTracker
This machine location tracker is assumed to always contain the up-to-date value mapping for all machine locations.
MachineFunction & MF
bool ShouldEmitDebugEntryValues
SmallVector< Transfer, 32 > Transfers
Collection of transfers (DBG_VALUEs) to be inserted.
SmallVector< ValueIDNum, 32 > VarLocs
Local cache of what-value-is-in-what-LocIdx.
DenseMap< LocIdx, SmallSet< DebugVariable, 4 > > ActiveMLocs
Map from LocIdxes to which DebugVariables are based that location.
DenseMap< DebugVariable, ResolvedDbgValue > ActiveVLocs
Map from DebugVariable to it's current location and qualifying meta information.
SmallVector< MachineInstr *, 4 > PendingDbgValues
Temporary cache of DBG_VALUEs to be entered into the Transfers collection.
DenseMap< unsigned, SmallVector< UseBeforeDef, 1 > > UseBeforeDefs
Map from instruction index (within the block) to the set of UseBeforeDefs that become defined at that instruction.
DenseSet< DebugVariable > UseBeforeDefVariables
The set of variables that are in UseBeforeDefs and can become a location once the relevant value is defined.
const TargetRegisterInfo & TRI
const BitVector & CalleeSavedRegs
Detailed Description
Tracker for converting machine value locations and variable values into variable locations (the output of LiveDebugValues), recorded as DBG_VALUEs specifying block live-in locations and transfers within blocks.
Operating on a per-block basis, this class takes a (pre-loaded) MLocTracker and must be initialized with the set of variable values that are live-in to the block. The caller then repeatedly calls process(). TransferTracker picks out variable locations for the live-in variable values (if there is a location) and creates the corresponding DBG_VALUEs. Then, as the block is stepped through, transfers of values between machine locations are identified and if profitable, a DBG_VALUE created.
This is where debug use-before-defs would be resolved: a variable with an unavailable value could materialize in the middle of a block, when the value becomes available. Or, we could detect clobbers and re-specify the variable in a backup location. (XXX these are unimplemented).
Definition at line 177 of file InstrRefBasedImpl.cpp.
Member Enumeration Documentation
LocationQuality
enum TransferTracker::LocationQuality : unsigned char strong
Enumerator
Illegal
Register
CalleeSavedRegister
SpillSlot
Best
Definition at line 293 of file InstrRefBasedImpl.cpp.
Constructor & Destructor Documentation
TransferTracker()
TransferTracker::TransferTracker (const TargetInstrInfo * TII, MLocTracker * MTracker, MachineFunction & MF, const TargetRegisterInfo & TRI, const BitVector & CalleeSavedRegs, const TargetPassConfig & TPC) inline
Definition at line 268 of file InstrRefBasedImpl.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::TargetPassConfig::getTM(), and TM.
Member Function Documentation
addUseBeforeDef()
void TransferTracker::addUseBeforeDef (const DebugVariable & Var, const DbgValueProperties & Properties, const SmallVectorImpl< DbgOp > & DbgOps, unsigned Inst) inline
Record that Var has value ID, a value that becomes available later in the function.
Definition at line 489 of file InstrRefBasedImpl.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
checkInstForNewValues()
void TransferTracker::checkInstForNewValues (unsigned Inst, MachineBasicBlock::iterator pos) inline
After the instruction at index Inst and position pos has been processed, check whether it defines a variable value in a use-before-def.
If so, and the variable value hasn't changed since the start of the block, create a DBG_VALUE.
Definition at line 500 of file InstrRefBasedImpl.cpp.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), LiveDebugValues::MLocTracker::emitLoc(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::empty(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), LiveDebugValues::LocIdx::isIllegal(), and LiveDebugValues::MLocTracker::locations().
clobberMloc() [1/2]
void TransferTracker::clobberMloc (LocIdx MLoc, MachineBasicBlock::iterator Pos, bool MakeUndef = true) inline
Account for a location mloc being clobbered.
Examine the variable locations that will be terminated: and try to recover them by using another location. Optionally, given MakeUndef, emit a DBG_VALUE to explicitly terminate a location if it can't be recovered.
Definition at line 773 of file InstrRefBasedImpl.cpp.
References LiveDebugValues::LocIdx::asU64(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find().
clobberMloc() [2/2]
void TransferTracker::clobberMloc (LocIdx MLoc, ValueIDNum OldValue, MachineBasicBlock::iterator Pos, bool MakeUndef = true) inline
Overload that takes an explicit value OldValue for when the value in MLoc has changed and the TransferTracker's locations have not been updated yet.
Definition at line 786 of file InstrRefBasedImpl.cpp.
References assert(), LiveDebugValues::LocIdx::asU64(), LiveDebugValues::MLocTracker::emitLoc(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), LiveDebugValues::ValueIDNum::EmptyValue, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::erase(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), llvm::SmallVectorImpl< T >::insert(), LiveDebugValues::MLocTracker::locations(), LiveDebugValues::LocIdx::MakeIllegalLoc(), and llvm::replace_copy().
emitMOLoc()
MachineInstrBuilder TransferTracker::emitMOLoc (const MachineOperand & MO, const DebugVariable & Var, const DbgValueProperties & Properties) inline
Definition at line 919 of file InstrRefBasedImpl.cpp.
References llvm::BuildMI(), LiveDebugValues::DbgValueProperties::DIExpr, DL, llvm::MDNode::get(), llvm::MDNode::getContext(), llvm::DebugVariable::getInlinedAt(), llvm::DILocalVariable::getScope(), llvm::DebugVariable::getVariable(), LiveDebugValues::DbgValueProperties::Indirect, and TII.
flushDbgValues()
void TransferTracker::flushDbgValues (MachineBasicBlock::iterator Pos, MachineBasicBlock * MBB) inline
Helper to move created DBG_VALUEs into Transfers collection.
Definition at line 581 of file InstrRefBasedImpl.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::getBundleStart(), llvm::MachineBasicBlock::instr_begin(), and MBB.
getLocQualityIfBetter()
std::optional<LocationQuality> TransferTracker::getLocQualityIfBetter (LocIdx L, LocationQuality Min) const inline
Definition at line 322 of file InstrRefBasedImpl.cpp.
References LiveDebugValues::LocIdx::isIllegal(), LiveDebugValues::MLocTracker::isSpill(), and Register.
isCalleeSaved()
bool TransferTracker::isCalleeSaved (LocIdx L) const inline
Definition at line 278 of file InstrRefBasedImpl.cpp.
References llvm::MCRegAliasIterator::isValid(), LiveDebugValues::MLocTracker::LocIdxToLocID, LiveDebugValues::MLocTracker::NumRegs, llvm::BitVector::test(), and TRI.
isEntryValueValue()
bool TransferTracker::isEntryValueValue (const ValueIDNum & Val) const inline
Definition at line 610 of file InstrRefBasedImpl.cpp.
References FP, LiveDebugValues::ValueIDNum::getBlock(), llvm::TargetRegisterInfo::getFrameRegister(), LiveDebugValues::ValueIDNum::getLoc(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), LiveDebugValues::ValueIDNum::isPHI(), LiveDebugValues::MLocTracker::isSpill(), LiveDebugValues::MLocTracker::LocIdxToLocID, and TRI.
isEntryValueVariable()
bool TransferTracker::isEntryValueVariable (const DebugVariable & Var, const DIExpression * Expr) const inline
Definition at line 596 of file InstrRefBasedImpl.cpp.
References llvm::DebugVariable::getInlinedAt(), llvm::DIExpression::getNumElements(), llvm::DebugVariable::getVariable(), llvm::DIExpression::isDeref(), and llvm::DILocalVariable::isParameter().
loadInlocs()
void TransferTracker::loadInlocs (MachineBasicBlock & MBB, ValueTable & MLocs, DbgOpIDMap & DbgOpStore, const SmallVectorImpl< std::pair< DebugVariable, DbgValue >> & VLocs, unsigned NumLocs) inline
Load object with live-in variable values.
mlocs contains the live-in values in each machine location, while vlocs the live-in variable values. This method picks variable locations for the live-in variables, creates DBG_VALUEs and puts them in Transfers, then prepares the other object fields to track variable locations as we step through the block. FIXME: could just examine mloctracker instead of passing in mlocs?
Definition at line 432 of file InstrRefBasedImpl.cpp.
References LiveDebugValues::LocIdx::asU64(), llvm::MachineBasicBlock::begin(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::clear(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::clear(), llvm::SmallVectorImpl< T >::clear(), LiveDebugValues::DbgValue::Def, LiveDebugValues::ValueIDNum::EmptyValue, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), LiveDebugValues::DbgOpIDMap::find(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), LiveDebugValues::MLocTracker::locations(), MBB, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::reserve(), and llvm::SmallVectorImpl< T >::reserve().
loadVarInloc()
void TransferTracker::loadVarInloc (MachineBasicBlock & MBB, DbgOpIDMap & DbgOpStore, const DenseMap< ValueIDNum, LocationAndQuality > & ValueToLoc, DebugVariable Var, DbgValue Value) inline
For a variable Var with the live-in value Value, attempts to resolve the DbgValue to a concrete DBG_VALUE, emitting that value and loading the tracking information to track Var throughout the block.
ValueToLoc is a map containing the best known location for every ValueIDNum that Value may use. MBB is the basic block that we are loading the live-in value for. DbgOpStore is the map containing the DbgOpID->DbgOp mapping needed to determine the values used by Value.
Definition at line 346 of file InstrRefBasedImpl.cpp.
References LiveDebugValues::MLocTracker::emitLoc(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), LiveDebugValues::DbgOpIDMap::find(), LiveDebugValues::ValueIDNum::getBlock(), LiveDebugValues::ValueIDNum::getInst(), llvm::MachineBasicBlock::getNumber(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), LiveDebugValues::ValueIDNum::isPHI(), M, llvm::max(), and MBB.
recoverAsEntryValue()
bool TransferTracker::recoverAsEntryValue (const DebugVariable & Var, const DbgValueProperties & Prop, const ValueIDNum & Num) inline
Definition at line 625 of file InstrRefBasedImpl.cpp.
References llvm::DIExpression::convertToNonVariadicExpression(), llvm::MachineOperand::CreateReg(), LiveDebugValues::DbgValueProperties::DIExpr, llvm::DIExpression::EntryValue, LiveDebugValues::ValueIDNum::getLoc(), LiveDebugValues::DbgValueProperties::Indirect, LiveDebugValues::DbgValueProperties::IsVariadic, LiveDebugValues::MLocTracker::LocIdxToLocID, and llvm::DIExpression::prepend().
redefVar() [1/2]
void TransferTracker::redefVar (const MachineInstr & MI) inline
Change a variable value after encountering a DBG_VALUE inside a block.
Definition at line 666 of file InstrRefBasedImpl.cpp.
References llvm::all_of(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::erase(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::MachineOperand::getReg(), LiveDebugValues::MLocTracker::getRegMLoc(), llvm::MachineOperand::isReg(), and MI.
redefVar() [2/2]
void TransferTracker::redefVar (const MachineInstr & MI, const DbgValueProperties & Properties, SmallVectorImpl< ResolvedDbgOp > & NewLocs) inline
Handle a change in variable location within a block.
Terminate the variables current location, and record the value it now refers to, so that we can detect location transfers later on.
Definition at line 704 of file InstrRefBasedImpl.cpp.
References LiveDebugValues::LocIdx::asU64(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::clear(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::erase(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), MI, P, and LiveDebugValues::MLocTracker::readMLoc().
transferMlocs()
void TransferTracker::transferMlocs (LocIdx Src, LocIdx Dst, MachineBasicBlock::iterator Pos) inline
Transfer variables based on Src to be based on Dst.
This handles both register copies as well as spills and restores. Creates DBG_VALUEs describing the movement.
Definition at line 881 of file InstrRefBasedImpl.cpp.
References assert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::clear(), LiveDebugValues::MLocTracker::emitLoc(), LiveDebugValues::ValueIDNum::EmptyValue, EmulateOldLDV, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), MI, LiveDebugValues::MLocTracker::readMLoc(), and replace().
Member Data Documentation
ActiveMLocs
DenseMap<LocIdx, SmallSet<DebugVariable, 4> > TransferTracker::ActiveMLocs
Map from LocIdxes to which DebugVariables are based that location.
Mantained while stepping through the block. Not accurate if VarLocs[Idx] != MTracker->LocIdxToIDNum[Idx].
Definition at line 230 of file InstrRefBasedImpl.cpp.
ActiveVLocs
DenseMap<DebugVariable, ResolvedDbgValue> TransferTracker::ActiveVLocs
Map from DebugVariable to it's current location and qualifying meta information.
To be used in conjunction with ActiveMLocs to construct enough information for the DBG_VALUEs for a particular LocIdx.
Definition at line 235 of file InstrRefBasedImpl.cpp.
CalleeSavedRegs
const BitVector& TransferTracker::CalleeSavedRegs
Definition at line 266 of file InstrRefBasedImpl.cpp.
MF
MachineFunction& TransferTracker::MF
Definition at line 185 of file InstrRefBasedImpl.cpp.
MTracker
MLocTracker* TransferTracker::MTracker
This machine location tracker is assumed to always contain the up-to-date value mapping for all machine locations.
TransferTracker only reads information from it. (XXX make it const?)
Definition at line 184 of file InstrRefBasedImpl.cpp.
PendingDbgValues
SmallVector<MachineInstr *, 4> TransferTracker::PendingDbgValues
Temporary cache of DBG_VALUEs to be entered into the Transfers collection.
Definition at line 238 of file InstrRefBasedImpl.cpp.
ShouldEmitDebugEntryValues
bool TransferTracker::ShouldEmitDebugEntryValues
Definition at line 186 of file InstrRefBasedImpl.cpp.
TII
const TargetInstrInfo* TransferTracker::TII
Definition at line 179 of file InstrRefBasedImpl.cpp.
TLI
const TargetLowering* TransferTracker::TLI
Definition at line 180 of file InstrRefBasedImpl.cpp.
Transfers
SmallVector<Transfer, 32> TransferTracker::Transfers
Collection of transfers (DBG_VALUEs) to be inserted.
Definition at line 219 of file InstrRefBasedImpl.cpp.
TRI
const TargetRegisterInfo& TransferTracker::TRI
Definition at line 265 of file InstrRefBasedImpl.cpp.
UseBeforeDefs
DenseMap<unsigned, SmallVector<UseBeforeDef, 1> > TransferTracker::UseBeforeDefs
Map from instruction index (within the block) to the set of UseBeforeDefs that become defined at that instruction.
Definition at line 258 of file InstrRefBasedImpl.cpp.
UseBeforeDefVariables
DenseSet<DebugVariable> TransferTracker::UseBeforeDefVariables
The set of variables that are in UseBeforeDefs and can become a location once the relevant value is defined.
An element being erased from this collection prevents the use-before-def materializing.
Definition at line 263 of file InstrRefBasedImpl.cpp.
VarLocs
SmallVector<ValueIDNum, 32> TransferTracker::VarLocs
Local cache of what-value-is-in-what-LocIdx.
Used to identify differences between TransferTrackers view of variable locations and MLocTrackers. For example, MLocTracker observes all clobbers, but TransferTracker lazily does not.
Definition at line 225 of file InstrRefBasedImpl.cpp.
The documentation for this class was generated from the following file:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.cpp