LLVM: llvm::orc::DynamicLibrarySearchGenerator Class Reference
llvm::orc::DynamicLibrarySearchGenerator Class Reference
A utility class to expose symbols found via dlsym to the JIT.
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
Public Types
using SymbolPredicate = std::function< bool(const SymbolStringPtr &)>
Public Member Functions
DynamicLibrarySearchGenerator (sys::DynamicLibrary Dylib, char GlobalPrefix, SymbolPredicate Allow=SymbolPredicate())
Create a DynamicLibrarySearchGenerator that searches for symbols in the given sys::DynamicLibrary.
Error tryToGenerate (LookupState &LS, LookupKind K, JITDylib &JD, JITDylibLookupFlags JDLookupFlags, const SymbolLookupSet &Symbols) override
DefinitionGenerators should override this method to insert new definitions into the parent JITDylib.
Public Member Functions inherited from llvm::orc::DefinitionGenerator
virtual ~DefinitionGenerator ()
Static Public Member Functions
static Expected< std::unique_ptr< DynamicLibrarySearchGenerator > > Load (const char *FileName, char GlobalPrefix, SymbolPredicate Allow=SymbolPredicate())
Permanently loads the library at the given path and, on success, returns a DynamicLibrarySearchGenerator that will search it for symbol definitions in the library.
static Expected< std::unique_ptr< DynamicLibrarySearchGenerator > > GetForCurrentProcess (char GlobalPrefix, SymbolPredicate Allow=SymbolPredicate())
Creates a DynamicLibrarySearchGenerator that searches for symbols in the current process.
Detailed Description
A utility class to expose symbols found via dlsym to the JIT.
If an instance of this class is attached to a JITDylib as a fallback definition generator, then any symbol found in the given DynamicLibrary that passes the 'Allow' predicate will be added to the JITDylib.
Definition at line 221 of file ExecutionUtils.h.
Member Typedef Documentation
SymbolPredicate
using llvm::orc::DynamicLibrarySearchGenerator::SymbolPredicate = std::function<bool(const SymbolStringPtr &)>
Definition at line 223 of file ExecutionUtils.h.
Constructor & Destructor Documentation
DynamicLibrarySearchGenerator()
llvm::orc::DynamicLibrarySearchGenerator::DynamicLibrarySearchGenerator (sys::DynamicLibrary Dylib, char GlobalPrefix, SymbolPredicate Allow = SymbolPredicate())
Create a DynamicLibrarySearchGenerator that searches for symbols in the given sys::DynamicLibrary.
If the Allow predicate is given then only symbols matching the predicate will be searched for. If the predicate is not given then all symbols will be searched for.
Definition at line 223 of file ExecutionUtils.cpp.
Member Function Documentation
GetForCurrentProcess()
static Expected<std::unique_ptr<DynamicLibrarySearchGenerator> > llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess (char GlobalPrefix, SymbolPredicate Allow = SymbolPredicate()) inline static
Creates a DynamicLibrarySearchGenerator that searches for symbols in the current process.
Definition at line 244 of file ExecutionUtils.h.
References GlobalPrefix, Load(), and move.
Referenced by LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess().
Load()
Expected< std::unique_ptr< DynamicLibrarySearchGenerator > > llvm::orc::DynamicLibrarySearchGenerator::Load (const char * FileName, char GlobalPrefix, SymbolPredicate Allow = SymbolPredicate()) static
Permanently loads the library at the given path and, on success, returns a DynamicLibrarySearchGenerator that will search it for symbol definitions in the library.
On failure returns the reason the library failed to load.
Definition at line 229 of file ExecutionUtils.cpp.
References llvm::sys::DynamicLibrary::getPermanentLibrary(), GlobalPrefix, llvm::inconvertibleErrorCode(), llvm::Lib, and move.
Referenced by GetForCurrentProcess(), and LLVMOrcCreateDynamicLibrarySearchGeneratorForPath().
tryToGenerate()
Error llvm::orc::DynamicLibrarySearchGenerator::tryToGenerate (LookupState & LS, LookupKind K, JITDylib & JD, JITDylibLookupFlags JDLookupFlags, const SymbolLookupSet & LookupSet) override virtual
DefinitionGenerators should override this method to insert new definitions into the parent JITDylib.
K specifies the kind of this lookup. JD specifies the target JITDylib being searched, and JDLookupFlags specifies whether the search should match against hidden symbols. Finally, Symbols describes the set of unresolved symbols and their associated lookup flags.
Implements llvm::orc::DefinitionGenerator.
Definition at line 239 of file ExecutionUtils.cpp.
References llvm::orc::absoluteSymbols(), Addr, llvm::orc::JITDylib::define(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::JITSymbolFlags::Exported, llvm::sys::DynamicLibrary::getAddressOfSymbol(), move, and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ExecutionUtils.h
lib/ExecutionEngine/Orc/ExecutionUtils.cpp