LLVM: llvm::MBFIWrapper Class Reference
llvm::MBFIWrapper Class Reference
#include "llvm/CodeGen/MBFIWrapper.h"
Public Member Functions
MBFIWrapper (const MachineBlockFrequencyInfo &I)
BlockFrequency getBlockFreq (const MachineBasicBlock *MBB) const
void setBlockFreq (const MachineBasicBlock *MBB, BlockFrequency F)
std::optional< uint64_t > getBlockProfileCount (const MachineBasicBlock *MBB) const
raw_ostream & printBlockFreq (raw_ostream &OS, const MachineBasicBlock *MBB) const
raw_ostream & printBlockFreq (raw_ostream &OS, const BlockFrequency Freq) const
void view (const Twine &Name, bool isSimple=true)
uint64_t getEntryFreq () const
const MachineBlockFrequencyInfo & getMBFI ()
Detailed Description
Definition at line 27 of file MBFIWrapper.h.
Constructor & Destructor Documentation
MBFIWrapper()
llvm::MBFIWrapper::MBFIWrapper (const MachineBlockFrequencyInfo & I) inline
Definition at line 29 of file MBFIWrapper.h.
Member Function Documentation
getBlockFreq()
BlockFrequency MBFIWrapper::getBlockFreq (const MachineBasicBlock * MBB) const
Definition at line 20 of file MBFIWrapper.cpp.
References llvm::MachineBlockFrequencyInfo::getBlockFreq(), I, and MBB.
Referenced by printBlockFreq(), and llvm::shouldOptimizeForSize().
getBlockProfileCount()
std::optional< uint64_t > MBFIWrapper::getBlockProfileCount (const MachineBasicBlock * MBB) const
Definition at line 35 of file MBFIWrapper.cpp.
References llvm::MachineBlockFrequencyInfo::getBlockProfileCount(), llvm::MachineBlockFrequencyInfo::getProfileCountFromFreq(), I, and MBB.
getEntryFreq()
uint64_t MBFIWrapper::getEntryFreq () const
Definition at line 60 of file MBFIWrapper.cpp.
References llvm::MachineBlockFrequencyInfo::getEntryFreq().
getMBFI()
const MachineBlockFrequencyInfo& llvm::MBFIWrapper::getMBFI () inline
Definition at line 42 of file MBFIWrapper.h.
Referenced by llvm::shouldOptimizeForSize().
printBlockFreq() [1/2]
raw_ostream & MBFIWrapper::printBlockFreq (raw_ostream & OS, const BlockFrequency Freq) const
Definition at line 51 of file MBFIWrapper.cpp.
References OS, and llvm::MachineBlockFrequencyInfo::printBlockFreq().
printBlockFreq() [2/2]
raw_ostream & MBFIWrapper::printBlockFreq (raw_ostream & OS, const MachineBasicBlock * MBB) const
Definition at line 46 of file MBFIWrapper.cpp.
References getBlockFreq(), MBB, OS, and llvm::MachineBlockFrequencyInfo::printBlockFreq().
setBlockFreq()
void MBFIWrapper::setBlockFreq (const MachineBasicBlock * MBB, BlockFrequency F)
Definition at line 29 of file MBFIWrapper.cpp.
References F, and MBB.
view()
void MBFIWrapper::view (const Twine & Name, bool isSimple = true)
Definition at line 56 of file MBFIWrapper.cpp.
References isSimple(), and llvm::MachineBlockFrequencyInfo::view().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MBFIWrapper.h
lib/CodeGen/MBFIWrapper.cpp