LLVM: llvm::pdb::NativeLineNumber Class Reference
llvm::pdb::NativeLineNumber Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeLineNumber.h"
Public Member Functions
NativeLineNumber (const NativeSession &Session, const codeview::LineInfo Line, uint32_t ColumnNumber, uint32_t Length, uint32_t Section, uint32_t Offset, uint32_t SrcFileId, uint32_t CompilandId)
uint32_t getLineNumber () const override
uint32_t getLineNumberEnd () const override
uint32_t getColumnNumber () const override
uint32_t getColumnNumberEnd () const override
uint32_t getAddressSection () const override
uint32_t getAddressOffset () const override
uint32_t getRelativeVirtualAddress () const override
uint64_t getVirtualAddress () const override
uint32_t getLength () const override
uint32_t getSourceFileId () const override
uint32_t getCompilandId () const override
bool isStatement () const override
Public Member Functions inherited from llvm::pdb::IPDBLineNumber
virtual ~IPDBLineNumber ()
Detailed Description
Definition at line 20 of file NativeLineNumber.h.
Constructor & Destructor Documentation
NativeLineNumber()
NativeLineNumber::NativeLineNumber (const NativeSession & Session, const codeview::LineInfo Line, uint32_t ColumnNumber, uint32_t Length, uint32_t Section, uint32_t Offset, uint32_t SrcFileId, uint32_t CompilandId) explicit
Definition at line 15 of file NativeLineNumber.cpp.
Member Function Documentation
getAddressOffset()
uint32_t NativeLineNumber::getAddressOffset () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 36 of file NativeLineNumber.cpp.
getAddressSection()
uint32_t NativeLineNumber::getAddressSection () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 34 of file NativeLineNumber.cpp.
getColumnNumber()
uint32_t NativeLineNumber::getColumnNumber () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 30 of file NativeLineNumber.cpp.
getColumnNumberEnd()
uint32_t NativeLineNumber::getColumnNumberEnd () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 32 of file NativeLineNumber.cpp.
getCompilandId()
uint32_t NativeLineNumber::getCompilandId () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 50 of file NativeLineNumber.cpp.
getLength()
uint32_t NativeLineNumber::getLength () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 46 of file NativeLineNumber.cpp.
getLineNumber()
uint32_t NativeLineNumber::getLineNumber () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 24 of file NativeLineNumber.cpp.
References llvm::codeview::LineInfo::getStartLine().
getLineNumberEnd()
uint32_t NativeLineNumber::getLineNumberEnd () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 26 of file NativeLineNumber.cpp.
References llvm::codeview::LineInfo::getEndLine().
getRelativeVirtualAddress()
uint32_t NativeLineNumber::getRelativeVirtualAddress () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 38 of file NativeLineNumber.cpp.
References llvm::pdb::NativeSession::getRVAFromSectOffset().
getSourceFileId()
uint32_t NativeLineNumber::getSourceFileId () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 48 of file NativeLineNumber.cpp.
getVirtualAddress()
uint64_t NativeLineNumber::getVirtualAddress () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 42 of file NativeLineNumber.cpp.
References llvm::pdb::NativeSession::getVAFromSectOffset().
isStatement()
bool NativeLineNumber::isStatement () const override virtual
Implements llvm::pdb::IPDBLineNumber.
Definition at line 52 of file NativeLineNumber.cpp.
References llvm::codeview::LineInfo::isStatement().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeLineNumber.h
lib/DebugInfo/PDB/Native/NativeLineNumber.cpp