LLVM: llvm::MCSectionXCOFF Class Reference
llvm::MCSectionXCOFF Class Reference final
#include "llvm/MC/MCSectionXCOFF.h"
Public Member Functions
~MCSectionXCOFF ()
XCOFF::StorageMappingClass getMappingClass () const
XCOFF::StorageClass getStorageClass () const
XCOFF::VisibilityType getVisibilityType () const
XCOFF::SymbolType getCSectType () const
MCSymbolXCOFF * getQualNameSymbol () const
void printSwitchToSection (const MCAsmInfo &MAI, const Triple &T, raw_ostream &OS, const MCExpr *Subsection) const override
bool useCodeAlign () const override
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
bool isVirtualSection () const override
Check whether this section is "virtual", that is has no actual object file contents.
StringRef getSymbolTableName () const
bool isMultiSymbolsAllowed () const
bool isCsect () const
bool isDwarfSect () const
std::optional< XCOFF::DwarfSectionSubtypeFlags > getDwarfSubtypeFlags () const
std::optional< XCOFF::CsectProperties > getCsectProp () const
Public Member Functions inherited from llvm::MCSection
MCSection (const MCSection &)=delete
MCSection & operator= (const MCSection &)=delete
StringRef getName () const
SectionKind getKind () const
SectionVariant getVariant () const
MCSymbol * getBeginSymbol ()
const MCSymbol * getBeginSymbol () const
void setBeginSymbol (MCSymbol *Sym)
MCSymbol * getEndSymbol (MCContext &Ctx)
bool hasEnded () const
Align getAlign () const
void setAlignment (Align Value)
void ensureMinAlignment (Align MinAlignment)
Makes sure that Alignment is at least MinAlignment.
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleLocked () const
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
bool hasInstructions () const
void setHasInstructions (bool Value)
bool isRegistered () const
void setIsRegistered (bool Value)
MCSection::FragmentListType & getFragmentList ()
const MCSection::FragmentListType & getFragmentList () const
const MCDummyFragment & getDummyFragment () const
MCDummyFragment & getDummyFragment ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
MCSection::iterator getSubsectionInsertionPoint (unsigned Subsection)
void dump () const
virtual StringRef getVirtualSectionKind () const
void addPendingLabel (MCSymbol *label, unsigned Subsection=0)
Add a pending label for the requested subsection.
void flushPendingLabels (MCFragment *F, uint64_t FOffset=0, unsigned Subsection=0)
Associate all pending labels in a subsection with a fragment.
void flushPendingLabels ()
Associate all pending labels with empty data fragments.
Static Public Member Functions
static bool classof (const MCSection *S)
Static Public Member Functions inherited from llvm::MCSection
static FragmentListType MCSection::* getSublistAccess (MCFragment *)
Support for MCFragment::getNextNode().
Friends
class MCContext
Additional Inherited Members
Public Types inherited from llvm::MCSection
enum SectionVariant {
SV_COFF = 0, SV_ELF, SV_GOFF, SV_MachO,
SV_Wasm, SV_XCOFF, SV_SPIRV, SV_DXContainer
}
enum BundleLockStateType { NotBundleLocked, BundleLocked, BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
using FragmentListType = iplist< MCFragment >
using const_iterator = FragmentListType::const_iterator
using iterator = FragmentListType::iterator
using const_reverse_iterator = FragmentListType::const_reverse_iterator
using reverse_iterator = FragmentListType::reverse_iterator
Static Public Attributes inherited from llvm::MCSection
static constexpr unsigned NonUniqueID = ~0U
Protected Member Functions inherited from llvm::MCSection
MCSection (SectionVariant V, StringRef Name, SectionKind K, MCSymbol *Begin)
~MCSection ()
Protected Attributes inherited from llvm::MCSection
StringRef Name
SectionVariant Variant
SectionKind Kind
Detailed Description
Definition at line 32 of file MCSectionXCOFF.h.
Constructor & Destructor Documentation
~MCSectionXCOFF()
MCSectionXCOFF::~MCSectionXCOFF () default
Member Function Documentation
classof()
static bool llvm::MCSectionXCOFF::classof (const MCSection * S) inline static
Definition at line 92 of file MCSectionXCOFF.h.
References S, and llvm::MCSection::SV_XCOFF.
getCsectProp()
std::optional<XCOFF::CsectProperties> llvm::MCSectionXCOFF::getCsectProp () const inline
Definition at line 124 of file MCSectionXCOFF.h.
getCSectType()
XCOFF::SymbolType llvm::MCSectionXCOFF::getCSectType () const inline
Definition at line 106 of file MCSectionXCOFF.h.
References assert(), and isCsect().
Referenced by printSwitchToSection().
getDwarfSubtypeFlags()
std::optional<XCOFF::DwarfSectionSubtypeFlags> llvm::MCSectionXCOFF::getDwarfSubtypeFlags () const inline
Definition at line 121 of file MCSectionXCOFF.h.
Referenced by printSwitchToSection().
getMappingClass()
XCOFF::StorageMappingClass llvm::MCSectionXCOFF::getMappingClass () const inline
Definition at line 96 of file MCSectionXCOFF.h.
References assert(), and isCsect().
Referenced by printSwitchToSection().
getQualNameSymbol()
MCSymbolXCOFF* llvm::MCSectionXCOFF::getQualNameSymbol () const inline
Definition at line 110 of file MCSectionXCOFF.h.
Referenced by createMCSymbolForTlsGetAddr(), and transformCallee().
getStorageClass()
XCOFF::StorageClass llvm::MCSectionXCOFF::getStorageClass () const inline
Definition at line 100 of file MCSectionXCOFF.h.
getSymbolTableName()
StringRef llvm::MCSectionXCOFF::getSymbolTableName () const inline
Definition at line 117 of file MCSectionXCOFF.h.
Referenced by llvm::MCSymbolXCOFF::getRepresentedCsect().
getVisibilityType()
XCOFF::VisibilityType llvm::MCSectionXCOFF::getVisibilityType () const inline
Definition at line 103 of file MCSectionXCOFF.h.
isCsect()
bool llvm::MCSectionXCOFF::isCsect () const inline
Definition at line 119 of file MCSectionXCOFF.h.
Referenced by getCSectType(), getMappingClass(), isVirtualSection(), and printSwitchToSection().
isDwarfSect()
bool llvm::MCSectionXCOFF::isDwarfSect () const inline
Definition at line 120 of file MCSectionXCOFF.h.
Referenced by isVirtualSection(), and printSwitchToSection().
isMultiSymbolsAllowed()
bool llvm::MCSectionXCOFF::isMultiSymbolsAllowed () const inline
Definition at line 118 of file MCSectionXCOFF.h.
isVirtualSection()
bool MCSectionXCOFF::isVirtualSection () const override virtual
Check whether this section is "virtual", that is has no actual object file contents.
Implements llvm::MCSection.
Definition at line 123 of file MCSectionXCOFF.cpp.
References assert(), isCsect(), isDwarfSect(), and llvm::XCOFF::XTY_CM.
printSwitchToSection()
void MCSectionXCOFF::printSwitchToSection (const MCAsmInfo & MAI, const Triple & T, raw_ostream & OS, const MCExpr * Subsection) const override virtual
Implements llvm::MCSection.
Definition at line 26 of file MCSectionXCOFF.cpp.
References assert(), llvm::format(), getCSectType(), getDwarfSubtypeFlags(), llvm::MCSection::getKind(), getMappingClass(), llvm::MCSection::getName(), llvm::MCAsmInfo::getPrivateLabelPrefix(), isCsect(), isDwarfSect(), OS, llvm::report_fatal_error(), llvm::XCOFF::XMC_BS, llvm::XCOFF::XMC_DS, llvm::XCOFF::XMC_PR, llvm::XCOFF::XMC_RO, llvm::XCOFF::XMC_RW, llvm::XCOFF::XMC_TC, llvm::XCOFF::XMC_TC0, llvm::XCOFF::XMC_TD, llvm::XCOFF::XMC_TE, llvm::XCOFF::XMC_TL, llvm::XCOFF::XMC_UL, and llvm::XCOFF::XTY_CM.
useCodeAlign()
bool MCSectionXCOFF::useCodeAlign () const override virtual
Return true if a .align directive should use "optimized nops" to fill instead of 0s.
Implements llvm::MCSection.
Definition at line 121 of file MCSectionXCOFF.cpp.
References llvm::MCSection::getKind(), and llvm::SectionKind::isText().
Friends And Related Function Documentation
MCContext
friend class MCContext friend
Definition at line 33 of file MCSectionXCOFF.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCSectionXCOFF.h
lib/MC/MCSectionXCOFF.cpp