LLVM: llvm::MachineFunction Class Reference
llvm::MachineFunction Class Reference
#include "llvm/CodeGen/MachineFunction.h"
Classes
struct ArgRegPair
Structure used to represent pair of argument number after call lowering and register used to transfer that argument.
class DebugPHIRegallocPos
Location of a PHI instruction that is also a debug-info variable value, for the duration of register allocation.
class DebugSubstitution
Replacement definition for a debug instruction reference.
class Delegate
struct VariableDbgInfo
Public Types
using CallSiteInfo = SmallVector< ArgRegPair, 1 >
Vector of call argument and its forwarding register.
using CallSiteInfoImpl = SmallVectorImpl< ArgRegPair >
using VariableDbgInfoMapTy = SmallVector< VariableDbgInfo, 4 >
using DebugInstrOperandPair = std::pair< unsigned, unsigned >
Pair of instruction number and operand number.
using iterator = BasicBlockListType::iterator
using const_iterator = BasicBlockListType::const_iterator
using const_reverse_iterator = BasicBlockListType::const_reverse_iterator
using reverse_iterator = BasicBlockListType::reverse_iterator
using OperandCapacity = ArrayRecycler< MachineOperand >::Capacity
Public Member Functions
MachineFunction (Function &F, const LLVMTargetMachine &Target, const TargetSubtargetInfo &STI, unsigned FunctionNum, MachineModuleInfo &MMI)
MachineFunction (const MachineFunction &)=delete
MachineFunction & operator= (const MachineFunction &)=delete
~MachineFunction ()
void reset ()
Reset the instance as if it was just created.
void resetDelegate (Delegate *delegate)
Reset the currently registered delegate - otherwise assert.
void setDelegate (Delegate *delegate)
Set the delegate.
void setObserver (GISelChangeObserver *O)
GISelChangeObserver * getObserver () const
MachineModuleInfo & getMMI () const
MCContext & getContext () const
MCSection * getSection () const
Returns the Section this function belongs to.
void setSection (MCSection *S)
Indicates the Section this function belongs to.
PseudoSourceValueManager & getPSVManager () const
const DataLayout & getDataLayout () const
Return the DataLayout attached to the Module associated to this MF.
Function & getFunction ()
Return the LLVM function that this machine code represents.
const Function & getFunction () const
Return the LLVM function that this machine code represents.
StringRef getName () const
getName - Return the name of the corresponding LLVM function.
unsigned getFunctionNumber () const
getFunctionNumber - Return a unique ID for the current function.
bool hasBBSections () const
Returns true if this function has basic block sections enabled.
bool hasBBLabels () const
Returns true if basic block labels are to be generated for this function.
void setBBSectionsType (BasicBlockSection V)
void assignBeginEndSections ()
Assign IsBeginSection IsEndSection fields for basic blocks in this function.
const LLVMTargetMachine & getTarget () const
getTarget - Return the target machine this machine code is compiled with
const TargetSubtargetInfo & getSubtarget () const
getSubtarget - Return the subtarget for which this machine code is being compiled.
template<typename STC >
const STC & getSubtarget () const
getSubtarget - This method returns a pointer to the specified type of TargetSubtargetInfo.
MachineRegisterInfo & getRegInfo ()
getRegInfo - Return information about the registers currently in use.
const MachineRegisterInfo & getRegInfo () const
MachineFrameInfo & getFrameInfo ()
getFrameInfo - Return the frame info object for the current function.
const MachineFrameInfo & getFrameInfo () const
const MachineJumpTableInfo * getJumpTableInfo () const
getJumpTableInfo - Return the jump table info object for the current function.
MachineJumpTableInfo * getJumpTableInfo ()
MachineJumpTableInfo * getOrCreateJumpTableInfo (unsigned JTEntryKind)
getOrCreateJumpTableInfo - Get the JumpTableInfo for this function, if it does already exist, allocate one.
MachineConstantPool * getConstantPool ()
getConstantPool - Return the constant pool object for the current function.
const MachineConstantPool * getConstantPool () const
const WasmEHFuncInfo * getWasmEHFuncInfo () const
getWasmEHFuncInfo - Return information about how the current function uses Wasm exception handling.
WasmEHFuncInfo * getWasmEHFuncInfo ()
const WinEHFuncInfo * getWinEHFuncInfo () const
getWinEHFuncInfo - Return information about how the current function uses Windows exception handling.
WinEHFuncInfo * getWinEHFuncInfo ()
Align getAlignment () const
getAlignment - Return the alignment of the function.
void setAlignment (Align A)
setAlignment - Set the alignment of the function.
void ensureAlignment (Align A)
ensureAlignment - Make sure the function is at least A bytes aligned.
bool exposesReturnsTwice () const
exposesReturnsTwice - Returns true if the function calls setjmp or any other similar functions with attribute "returns twice" without having the attribute itself.
void setExposesReturnsTwice (bool B)
setCallsSetJmp - Set a flag that indicates if there's a call to a "returns twice" function.
bool hasInlineAsm () const
Returns true if the function contains any inline assembly.
void setHasInlineAsm (bool B)
Set a flag that indicates that the function contains inline assembly.
bool hasWinCFI () const
void setHasWinCFI (bool v)
bool needsFrameMoves () const
True if this function needs frame moves for debug or exceptions.
const MachineFunctionProperties & getProperties () const
Get the function properties.
MachineFunctionProperties & getProperties ()
template<typename Ty >
Ty * getInfo ()
getInfo - Keep track of various per-function pieces of information for backends that would like to do so.
template<typename Ty >
const Ty * getInfo () const
template<typename Ty >
Ty * cloneInfo (const Ty &Old)
void initTargetMachineFunctionInfo (const TargetSubtargetInfo &STI)
Initialize the target specific MachineFunctionInfo.
MachineFunctionInfo * cloneInfoFrom (const MachineFunction &OrigMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB)
DenormalMode getDenormalMode (const fltSemantics &FPType) const
Returns the denormal handling type for the default rounding mode of the function.
MachineBasicBlock * getBlockNumbered (unsigned N) const
getBlockNumbered - MachineBasicBlocks are automatically numbered when they are inserted into the machine function.
bool shouldSplitStack () const
Should we be emitting segmented stack stuff for the function.
unsigned getNumBlockIDs () const
getNumBlockIDs - Return the number of MBB ID's allocated.
void RenumberBlocks (MachineBasicBlock *MBBFrom=nullptr)
RenumberBlocks - This discards all of the MachineBasicBlock numbers and recomputes them.
void print (raw_ostream &OS, const SlotIndexes *=nullptr) const
print - Print out the MachineFunction in a format suitable for debugging to the specified stream.
void viewCFG () const
viewCFG - This function is meant for use from the debugger.
void viewCFGOnly () const
viewCFGOnly - This function is meant for use from the debugger.
void dump () const
dump - Print the current MachineFunction to cerr, useful for debugger use.
bool verify (Pass *p=nullptr, const char *Banner=nullptr, bool AbortOnError=true) const
Run the current MachineFunction through the machine code verifier, useful for debugger use.
Register addLiveIn (MCRegister PReg, const TargetRegisterClass *RC)
addLiveIn - Add the specified physical register as a live-in value and create a corresponding virtual register for it.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
unsigned size () const
bool empty () const
const MachineBasicBlock & front () const
MachineBasicBlock & front ()
const MachineBasicBlock & back () const
MachineBasicBlock & back ()
void push_back (MachineBasicBlock *MBB)
void push_front (MachineBasicBlock *MBB)
void insert (iterator MBBI, MachineBasicBlock *MBB)
void splice (iterator InsertPt, iterator MBBI)
void splice (iterator InsertPt, MachineBasicBlock *MBB)
void splice (iterator InsertPt, iterator MBBI, iterator MBBE)
void remove (iterator MBBI)
void remove (MachineBasicBlock *MBBI)
void erase (iterator MBBI)
void erase (MachineBasicBlock *MBBI)
template<typename Comp >
void sort (Comp comp)
unsigned getInstructionCount () const
Return the number of MachineInstrs in this MachineFunction.
unsigned addToMBBNumbering (MachineBasicBlock *MBB)
Adds the MBB to the internal numbering.
void removeFromMBBNumbering (unsigned N)
removeFromMBBNumbering - Remove the specific machine basic block from our tracker, this is only really to be used by the MachineBasicBlock implementation.
MachineInstr * CreateMachineInstr (const MCInstrDesc &MCID, DebugLoc DL, bool NoImplicit=false)
CreateMachineInstr - Allocate a new MachineInstr.
MachineInstr * CloneMachineInstr (const MachineInstr *Orig)
Create a new MachineInstr which is a copy of Orig, identical in all ways except the instruction has no parent, prev, or next.
MachineInstr & cloneMachineInstrBundle (MachineBasicBlock &MBB, MachineBasicBlock::iterator InsertBefore, const MachineInstr &Orig)
Clones instruction or the whole instruction bundle Orig and insert into MBB before InsertBefore.
void deleteMachineInstr (MachineInstr *MI)
DeleteMachineInstr - Delete the given MachineInstr.
MachineBasicBlock * CreateMachineBasicBlock (const BasicBlock *bb=nullptr)
CreateMachineBasicBlock - Allocate a new MachineBasicBlock.
void deleteMachineBasicBlock (MachineBasicBlock *MBB)
DeleteMachineBasicBlock - Delete the given MachineBasicBlock.
MachineMemOperand * getMachineMemOperand (MachinePointerInfo PtrInfo, MachineMemOperand::Flags f, uint64_t s, Align base_alignment, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr, SyncScope::ID SSID=SyncScope::System, AtomicOrdering Ordering=AtomicOrdering::NotAtomic, AtomicOrdering FailureOrdering=AtomicOrdering::NotAtomic)
getMachineMemOperand - Allocate a new MachineMemOperand.
MachineMemOperand * getMachineMemOperand (MachinePointerInfo PtrInfo, MachineMemOperand::Flags f, LLT MemTy, Align base_alignment, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr, SyncScope::ID SSID=SyncScope::System, AtomicOrdering Ordering=AtomicOrdering::NotAtomic, AtomicOrdering FailureOrdering=AtomicOrdering::NotAtomic)
MachineMemOperand * getMachineMemOperand (const MachineMemOperand *MMO, int64_t Offset, LLT Ty)
getMachineMemOperand - Allocate a new MachineMemOperand by copying an existing one, adjusting by an offset and using the given size.
MachineMemOperand * getMachineMemOperand (const MachineMemOperand *MMO, int64_t Offset, uint64_t Size)
MachineMemOperand * getMachineMemOperand (const MachineMemOperand *MMO, const MachinePointerInfo &PtrInfo, uint64_t Size)
getMachineMemOperand - Allocate a new MachineMemOperand by copying an existing one, replacing only the MachinePointerInfo and size.
MachineMemOperand * getMachineMemOperand (const MachineMemOperand *MMO, const MachinePointerInfo &PtrInfo, LLT Ty)
MachineMemOperand * getMachineMemOperand (const MachineMemOperand *MMO, const AAMDNodes &AAInfo)
Allocate a new MachineMemOperand by copying an existing one, replacing only AliasAnalysis information.
MachineMemOperand * getMachineMemOperand (const MachineMemOperand *MMO, MachineMemOperand::Flags Flags)
Allocate a new MachineMemOperand by copying an existing one, replacing the flags.
MachineOperand * allocateOperandArray (OperandCapacity Cap)
Allocate an array of MachineOperands.
void deallocateOperandArray (OperandCapacity Cap, MachineOperand *Array)
Dellocate an array of MachineOperands and recycle the memory.
uint32_t * allocateRegMask ()
Allocate and initialize a register mask with NumRegister bits.
ArrayRef< int > allocateShuffleMask (ArrayRef< int > Mask)
MachineInstr::ExtraInfo * createMIExtraInfo (ArrayRef< MachineMemOperand * > MMOs, MCSymbol *PreInstrSymbol=nullptr, MCSymbol *PostInstrSymbol=nullptr, MDNode *HeapAllocMarker=nullptr, MDNode *PCSections=nullptr, uint32_t CFIType=0)
Allocate and construct an extra info structure for a MachineInstr.
const char * createExternalSymbolName (StringRef Name)
Allocate a string and populate it with the given external symbol name.
MCSymbol * getJTISymbol (unsigned JTI, MCContext &Ctx, bool isLinkerPrivate=false) const
getJTISymbol - Return the MCSymbol for the specified non-empty jump table.
MCSymbol * getPICBaseSymbol () const
getPICBaseSymbol - Return a function-local symbol to represent the PIC base.
const std::vector< MCCFIInstruction > & getFrameInstructions () const
Returns a reference to a list of cfi instructions in the function's prologue.
unsigned addFrameInst (const MCCFIInstruction &Inst)
const std::vector< MCSymbol * > & getLongjmpTargets () const
Returns a reference to a list of symbols immediately following calls to _setjmp in the function.
void addLongjmpTarget (MCSymbol *Target)
Add the specified symbol to the list of valid longjmp targets for Windows Control Flow Guard.
const std::vector< MCSymbol * > & getCatchretTargets () const
Returns a reference to a list of symbols that we have catchrets.
void addCatchretTarget (MCSymbol *Target)
Add the specified symbol to the list of valid catchret targets for Windows EHCont Guard.
void setVariableDbgInfo (const DILocalVariable *Var, const DIExpression *Expr, int Slot, const DILocation *Loc)
Collect information used to emit debugging information of a variable.
VariableDbgInfoMapTy & getVariableDbgInfo ()
const VariableDbgInfoMapTy & getVariableDbgInfo () const
void addCallArgsForwardingRegs (const MachineInstr *CallI, CallSiteInfoImpl &&CallInfo)
Start tracking the arguments passed to the call CallI.
const CallSiteInfoMap & getCallSitesInfo () const
unsigned getNewDebugInstrNum ()
Static Public Member Functions
static BasicBlockListType MachineFunction::* getSublistAccess (MachineBasicBlock *)
Support for MachineBasicBlock::getNextNode().
Public Attributes
VariableDbgInfoMapTy VariableDbgInfos
unsigned DebugInstrNumberingCount = 0
A count of how many instructions in the function have had numbers assigned to them.
SmallVector< DebugSubstitution, 8 > DebugValueSubstitutions
Debug value substitutions: a collection of DebugSubstitution objects, recording changes in where a value is defined.
DenseMap< unsigned, DebugPHIRegallocPos > DebugPHIPositions
Map of debug instruction numbers to the position of their PHI instructions during register allocation.
bool UseDebugInstrRef = false
Flag for whether this function contains DBG_VALUEs (false) or DBG_INSTR_REF (true).
Friends
struct ilist_traits< MachineInstr >
Exception Handling
bool callsEHReturn () const
void setCallsEHReturn (bool b)
bool callsUnwindInit () const
void setCallsUnwindInit (bool b)
bool hasEHCatchret () const
void setHasEHCatchret (bool V)
bool hasEHScopes () const
void setHasEHScopes (bool V)
bool hasEHFunclets () const
void setHasEHFunclets (bool V)
LandingPadInfo & getOrCreateLandingPadInfo (MachineBasicBlock *LandingPad)
Find or create an LandingPadInfo for the specified MachineBasicBlock.
const std::vector< LandingPadInfo > & getLandingPads () const
Return a reference to the landing pad info for the current function.
void addInvoke (MachineBasicBlock *LandingPad, MCSymbol *BeginLabel, MCSymbol *EndLabel)
Provide the begin and end labels of an invoke style call and associate it with a try landing pad block.
MCSymbol * addLandingPad (MachineBasicBlock *LandingPad)
Add a new panding pad, and extract the exception handling information from the landingpad instruction.
unsigned getTypeIDFor (const GlobalValue *TI)
Return the type id for the specified typeinfo. This is function wide.
int getFilterIDFor (ArrayRef< unsigned > TyIds)
Return the id of the filter encoded by TyIds. This is function wide.
void setCallSiteLandingPad (MCSymbol *Sym, ArrayRef< unsigned > Sites)
Map the landing pad's EH symbol to the call site indexes.
bool hasAnyWasmLandingPadIndex () const
Return if there is any wasm exception handling.
void setWasmLandingPadIndex (const MachineBasicBlock *LPad, unsigned Index)
Map the landing pad to its index. Used for Wasm exception handling.
bool hasWasmLandingPadIndex (const MachineBasicBlock *LPad) const
Returns true if the landing pad has an associate index in wasm EH.
unsigned getWasmLandingPadIndex (const MachineBasicBlock *LPad) const
Get the index in wasm EH for a given landing pad.
bool hasAnyCallSiteLandingPad () const
SmallVectorImpl< unsigned > & getCallSiteLandingPad (MCSymbol *Sym)
Get the call site indexes for a landing pad EH symbol.
bool hasCallSiteLandingPad (MCSymbol *Sym)
Return true if the landing pad Eh symbol has an associated call site.
bool hasAnyCallSiteLabel () const
void setCallSiteBeginLabel (MCSymbol *BeginLabel, unsigned Site)
Map the begin label for a call site.
unsigned getCallSiteBeginLabel (MCSymbol *BeginLabel) const
Get the call site number for a begin label.
bool hasCallSiteBeginLabel (MCSymbol *BeginLabel) const
Return true if the begin label has a call site number associated with it.
void addCodeViewAnnotation (MCSymbol *Label, MDNode *MD)
Record annotations associated with a particular label.
ArrayRef< std::pair< MCSymbol *, MDNode * > > getCodeViewAnnotations () const
const std::vector< const GlobalValue * > & getTypeInfos () const
Return a reference to the C++ typeinfo for the current function.
const std::vector< unsigned > & getFilterIds () const
Return a reference to the typeids encoding filters used in the current function.
Exception Handling
const static unsigned int DebugOperandMemNumber = 1000000
A reserved operand number representing the instructions memory operand, for instructions that have a stack spill fused into them.
void setDebugInstrNumberingCount (unsigned Num)
Set value of DebugInstrNumberingCount field.
void makeDebugValueSubstitution (DebugInstrOperandPair, DebugInstrOperandPair, unsigned SubReg=0)
Create a substitution between one <instr,operand> value to a different, new value.
void substituteDebugValuesForInst (const MachineInstr &Old, MachineInstr &New, unsigned MaxOperand=UINT_MAX)
Create substitutions for any tracked values in Old, to point at New.
DebugInstrOperandPair salvageCopySSA (MachineInstr &MI, DenseMap< Register, DebugInstrOperandPair > &DbgPHICache)
Find the underlying defining instruction / operand for a COPY instruction while in SSA form.
DebugInstrOperandPair salvageCopySSAImpl (MachineInstr &MI)
void finalizeDebugInstrRefs ()
Finalise any partially emitted debug instructions.
bool shouldUseDebugInstrRef () const
Determine whether, in the current machine configuration, we should use instruction referencing or not.
bool useDebugInstrRef () const
Returns true if the function's variable locations are tracked with instruction referencing.
void setUseDebugInstrRef (bool UseInstrRef)
Set whether this function will use instruction referencing or not.
void eraseCallSiteInfo (const MachineInstr *MI)
Following functions update call site info.
void copyCallSiteInfo (const MachineInstr *Old, const MachineInstr *New)
Copy the call site info from Old to \ New.
void moveCallSiteInfo (const MachineInstr *Old, const MachineInstr *New)
Move the call site info from Old to \New call site info.
Detailed Description
Definition at line 258 of file MachineFunction.h.
Member Typedef Documentation
CallSiteInfo
using llvm::MachineFunction::CallSiteInfo = SmallVector<ArgRegPair, 1>
Vector of call argument and its forwarding register.
Definition at line 444 of file MachineFunction.h.
CallSiteInfoImpl
using llvm::MachineFunction::CallSiteInfoImpl = SmallVectorImpl<ArgRegPair>
Definition at line 445 of file MachineFunction.h.
const_iterator
using llvm::MachineFunction::const_iterator = BasicBlockListType::const_iterator
Definition at line 853 of file MachineFunction.h.
const_reverse_iterator
using llvm::MachineFunction::const_reverse_iterator = BasicBlockListType::const_reverse_iterator
Definition at line 854 of file MachineFunction.h.
DebugInstrOperandPair
using llvm::MachineFunction::DebugInstrOperandPair = std::pair<unsigned, unsigned>
Pair of instruction number and operand number.
Definition at line 478 of file MachineFunction.h.
iterator
using llvm::MachineFunction::iterator = BasicBlockListType::iterator
Definition at line 852 of file MachineFunction.h.
OperandCapacity
using llvm::MachineFunction::OperandCapacity = ArrayRecycler<MachineOperand>::Capacity
Definition at line 1024 of file MachineFunction.h.
reverse_iterator
using llvm::MachineFunction::reverse_iterator = BasicBlockListType::reverse_iterator
Definition at line 855 of file MachineFunction.h.
VariableDbgInfoMapTy
using llvm::MachineFunction::VariableDbgInfoMapTy = SmallVector<VariableDbgInfo, 4>
Definition at line 465 of file MachineFunction.h.
Constructor & Destructor Documentation
MachineFunction() [1/2]
MachineFunction::MachineFunction (Function & F, const LLVMTargetMachine & Target, const TargetSubtargetInfo & STI, unsigned FunctionNum, MachineModuleInfo & MMI)
Definition at line 162 of file MachineFunction.cpp.
References F.
MachineFunction() [2/2]
llvm::MachineFunction::MachineFunction (const MachineFunction &) delete
~MachineFunction()
MachineFunction::~MachineFunction ()
Definition at line 242 of file MachineFunction.cpp.
Member Function Documentation
addCallArgsForwardingRegs()
void llvm::MachineFunction::addCallArgsForwardingRegs (const MachineInstr * CallI, CallSiteInfoImpl && CallInfo) inline
Start tracking the arguments passed to the call CallI.
Definition at line 1238 of file MachineFunction.h.
References assert(), llvm::MachineInstr::isCandidateForCallSiteEntry(), move, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by llvm::MIRParserImpl::initializeCallSiteInfo().
addCatchretTarget()
void llvm::MachineFunction::addCatchretTarget (MCSymbol * Target) inline
Add the specified symbol to the list of valid catchret targets for Windows EHCont Guard.
Definition at line 1097 of file MachineFunction.h.
addCodeViewAnnotation()
void llvm::MachineFunction::addCodeViewAnnotation (MCSymbol * Label, MDNode * MD) inline
Record annotations associated with a particular label.
Definition at line 1205 of file MachineFunction.h.
addFrameInst()
unsigned MachineFunction::addFrameInst (const MCCFIInstruction & Inst)
Definition at line 317 of file MachineFunction.cpp.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), buildCFAOffs(), llvm::X86FrameLowering::BuildCFI(), buildDefCFAReg(), llvm::AArch64InstrInfo::buildOutlinedFrame(), convertCalleeSaveRestoreToSPPrePostIncDec(), emitCalleeSavedRestores(), EmitCfiOffset(), EmitDefCfaOffset(), EmitDefCfaRegister(), llvm::AArch64FrameLowering::emitEpilogue(), emitFrameOffsetAdj(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), emitShadowCallStackEpilogue(), emitShadowCallStackPrologue(), llvm::PPCFrameLowering::inlineStackProbe(), insertCFISameValue(), InsertReturnAddressAuth(), llvm::AArch64FrameLowering::resetCFIToInitialState(), llvm::CFIFixup::runOnMachineFunction(), and signOutlinedFunction().
addInvoke()
void MachineFunction::addInvoke (MachineBasicBlock * LandingPad, MCSymbol * BeginLabel, MCSymbol * EndLabel)
Provide the begin and end labels of an invoke style call and associate it with a try landing pad block.
Definition at line 756 of file MachineFunction.cpp.
References llvm::LandingPadInfo::BeginLabels, llvm::LandingPadInfo::EndLabels, and getOrCreateLandingPadInfo().
addLandingPad()
MCSymbol * MachineFunction::addLandingPad (MachineBasicBlock * LandingPad)
Add a new panding pad, and extract the exception handling information from the landingpad instruction.
Returns the label ID for the landing pad entry.
Definition at line 763 of file MachineFunction.cpp.
References assert(), llvm::MCContext::createTempSymbol(), llvm::MachineBasicBlock::getBasicBlock(), getFilterIDFor(), llvm::BasicBlock::getFirstNonPHI(), getOrCreateLandingPadInfo(), getTypeIDFor(), I, llvm::LandingPadInfo::LandingPadLabel, llvm::Value::stripPointerCasts(), and llvm::LandingPadInfo::TypeIds.
addLiveIn()
Register MachineFunction::addLiveIn (MCRegister PReg, const TargetRegisterClass * RC)
addLiveIn - Add the specified physical register as a live-in value and create a corresponding virtual register for it.
Add the specified physical register as a live-in value and create a corresponding virtual register for it.
Definition at line 694 of file MachineFunction.cpp.
References llvm::MachineRegisterInfo::addLiveIn(), assert(), llvm::TargetRegisterClass::contains(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineRegisterInfo::getLiveInVirtReg(), llvm::MachineRegisterInfo::getRegClass(), getRegInfo(), llvm::TargetRegisterClass::hasSubClassEq(), and MRI.
Referenced by allocateFixedSGPRInputImpl(), allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), allocateSGPR32InputImpl(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), llvm::SITargetLowering::allocateSystemSGPRs(), allocateVGPR32Input(), llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::getFunctionLiveInPhysReg(), getv64i1Argument(), handleMustTailForwardedRegisters(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), and LowerRETURNADDR().
addLongjmpTarget()
void llvm::MachineFunction::addLongjmpTarget (MCSymbol * Target) inline
Add the specified symbol to the list of valid longjmp targets for Windows Control Flow Guard.
Definition at line 1087 of file MachineFunction.h.
addToMBBNumbering()
unsigned llvm::MachineFunction::addToMBBNumbering (MachineBasicBlock * MBB) inline
Adds the MBB to the internal numbering.
Returns the unique number assigned to the MBB.
Definition at line 925 of file MachineFunction.h.
References MBB.
allocateOperandArray()
MachineOperand* llvm::MachineFunction::allocateOperandArray (OperandCapacity Cap) inline
Allocate an array of MachineOperands.
This is only intended for use by internal MachineInstr functions.
Definition at line 1028 of file MachineFunction.h.
References llvm::ArrayRecycler< T, Align >::allocate(), and Allocator.
Referenced by llvm::MachineInstr::addOperand().
allocateRegMask()
uint32_t * MachineFunction::allocateRegMask ()
Allocate and initialize a register mask with NumRegister bits.
Definition at line 562 of file MachineFunction.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::MCRegisterInfo::getNumRegs(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineOperand::getRegMaskSize(), getSubtarget(), and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::AArch64RegisterInfo::UpdateCustomCallPreservedMask().
allocateShuffleMask()
ArrayRef< int > MachineFunction::allocateShuffleMask (ArrayRef< int > Mask)
Definition at line 570 of file MachineFunction.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::copy(), and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::MachineIRBuilder::buildShuffleVector().
assignBeginEndSections()
void MachineFunction::assignBeginEndSections ()
Assign IsBeginSection IsEndSection fields for basic blocks in this function.
This method iterates over the basic blocks and assigns their IsBeginSection and IsEndSection fields.
This must be called after MBB layout is finalized and the SectionID's are assigned to MBBs.
Definition at line 366 of file MachineFunction.cpp.
References back(), begin(), E, end(), front(), llvm::MachineBasicBlock::getSectionID(), MBBI, llvm::MachineBasicBlock::setIsBeginSection(), and llvm::MachineBasicBlock::setIsEndSection().
Referenced by llvm::MIRParserImpl::initializeMachineFunction().
back() [1/2]
MachineBasicBlock& llvm::MachineFunction::back () inline
Definition at line 885 of file MachineFunction.h.
back() [2/2]
const MachineBasicBlock& llvm::MachineFunction::back () const inline
Definition at line 884 of file MachineFunction.h.
Referenced by appendEndToFunction(), assignBeginEndSections(), llvm::EHStreamer::computeCallSiteTable(), llvm::AsmPrinter::emitFunctionBody(), and maybeRewriteToFallthrough().
begin() [1/2]
iterator llvm::MachineFunction::begin () inline
Definition at line 870 of file MachineFunction.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), assignBeginEndSections(), collectCallSiteParameters(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), createFrameHelperMachineFunction(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), getBBFallenThrough(), getOrCreateFrameHelper(), llvm::MachineLoop::getTopBlock(), llvm::MIRParserImpl::initializeCallSiteInfo(), llvm::MachineBasicBlock::isEntryBlock(), isFunctionEntryBlock(), llvm::GraphTraits< DOTMachineFuncInfo * >::nodes_begin(), ProfitableToMerge(), RenumberBlocks(), llvm::CFIFixup::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), and verifyCTRBranch().
begin() [2/2]
const_iterator llvm::MachineFunction::begin () const inline
Definition at line 871 of file MachineFunction.h.
callsEHReturn()
bool llvm::MachineFunction::callsEHReturn () const inline
Definition at line 1104 of file MachineFunction.h.
Referenced by llvm::XCoreFrameLowering::determineCalleeSaves(), findDeadCallerSavedReg(), llvm::X86RegisterInfo::findDeadCallerSavedReg(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86FrameLowering::hasFP(), and llvm::MIRPrinter::print().
callsUnwindInit()
bool llvm::MachineFunction::callsUnwindInit () const inline
Definition at line 1107 of file MachineFunction.h.
Referenced by llvm::XCoreFrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::X86FrameLowering::hasFP(), and llvm::MIRPrinter::print().
cloneInfo()
template<typename Ty > Ty* llvm::MachineFunction::cloneInfo (const Ty & Old) inline
Definition at line 779 of file MachineFunction.h.
References Allocator, and assert().
Referenced by llvm::MipsFunctionInfo::clone(), llvm::NVPTXMachineFunctionInfo::clone(), llvm::ARCFunctionInfo::clone(), llvm::VEMachineFunctionInfo::clone(), llvm::CSKYMachineFunctionInfo::clone(), llvm::SparcMachineFunctionInfo::clone(), llvm::LoongArchMachineFunctionInfo::clone(), llvm::LanaiMachineFunctionInfo::clone(), llvm::SystemZMachineFunctionInfo::clone(), llvm::MSP430MachineFunctionInfo::clone(), llvm::HexagonMachineFunctionInfo::clone(), llvm::XCoreFunctionInfo::clone(), llvm::AVRMachineFunctionInfo::clone(), llvm::WebAssemblyFunctionInfo::clone(), llvm::M68kMachineFunctionInfo::clone(), llvm::RISCVMachineFunctionInfo::clone(), llvm::X86MachineFunctionInfo::clone(), llvm::PPCFunctionInfo::clone(), llvm::ARMFunctionInfo::clone(), llvm::AArch64FunctionInfo::clone(), and llvm::SIMachineFunctionInfo::clone().
cloneInfoFrom()
MachineFunctionInfo* llvm::MachineFunction::cloneInfoFrom (const MachineFunction & OrigMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) inline
Definition at line 788 of file MachineFunction.h.
References Allocator, assert(), and llvm::MachineFunctionInfo::clone().
CloneMachineInstr()
MachineInstr * MachineFunction::CloneMachineInstr (const MachineInstr * Orig)
Create a new MachineInstr which is a copy of Orig, identical in all ways except the instruction has no parent, prev, or next.
Create a new MachineInstr which is a copy of the 'Orig' instruction, identical in all ways except the instruction has no parent, prev, or next.
Bundling flags are reset.
Note: Clones a single instruction, not whole instruction bundles. Does not perform target specific adjustments; consider using TargetInstrInfo::duplicate() instead.
Definition at line 390 of file MachineFunction.cpp.
Referenced by llvm::SwingSchedulerDAG::applyInstrChange(), llvm::WebAssemblyDebugValueManager::clone(), cloneMachineInstrBundle(), llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::SwingSchedulerDAG::fixupRegisterOverlaps(), for(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::PeelSingleBlockLoop(), performSink(), llvm::ARMBaseInstrInfo::reMaterialize(), llvm::X86InstrInfo::reMaterialize(), llvm::TargetInstrInfo::reMaterialize(), and llvm::RegBankSelect::repairReg().
cloneMachineInstrBundle()
MachineInstr & MachineFunction::cloneMachineInstrBundle (MachineBasicBlock & MBB, MachineBasicBlock::iterator InsertBefore, const MachineInstr & Orig)
Clones instruction or the whole instruction bundle Orig and insert into MBB before InsertBefore.
Note: Does not perform target specific adjustments; consider using TargetInstrInfo::duplicate() intead.
Definition at line 395 of file MachineFunction.cpp.
References llvm::MachineInstr::bundleWithPred(), CloneMachineInstr(), copyCallSiteInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), I, llvm::MachineBasicBlock::insert(), MBB, and llvm::MachineInstr::shouldUpdateCallSiteInfo().
Referenced by llvm::TargetInstrInfo::duplicate().
copyCallSiteInfo()
void MachineFunction::copyCallSiteInfo (const MachineInstr * Old, const MachineInstr * New)
Copy the call site info from Old to \ New.
Its usage is when we are making a copy of the instruction that will be inserted at different point of the instruction stream.
Definition at line 884 of file MachineFunction.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), eraseCallSiteInfo(), getCallInstr(), and llvm::MachineInstr::shouldUpdateCallSiteInfo().
Referenced by cloneMachineInstrBundle().
createExternalSymbolName()
const char * MachineFunction::createExternalSymbolName (StringRef Name)
Allocate a string and populate it with the given external symbol name.
Definition at line 555 of file MachineFunction.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), and llvm::copy().
Referenced by addAsmInstr(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::HexagonInstrInfo::expandPostRAPseudo(), and llvm::WebAssemblyFrameLowering::writeSPToGlobal().
CreateMachineBasicBlock()
MachineBasicBlock * MachineFunction::CreateMachineBasicBlock (const BasicBlock * bb = nullptr)
CreateMachineBasicBlock - Allocate a new MachineBasicBlock.
Allocate a new MachineBasicBlock.
Use this instead of ‘new MachineBasicBlock’.
Definition at line 446 of file MachineFunction.cpp.
References bb, llvm::Labels, llvm::List, MBB, and llvm::MachineBasicBlock::setBBID().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::SwitchCG::SwitchLowering::buildJumpTable(), createFrameHelperMachineFunction(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::SystemZ::emitBlockAfter(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::emitProbedAlloca(), emitReadCycleWidePseudo(), emitXBegin(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::SelectionDAGBuilder::FindMergedConditions(), INITIALIZE_PASS(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::SystemZXPLINKFrameLowering::inlineStackProbe(), insertDivByZeroTrap(), loadM0FromVGPR(), llvm::PeelSingleBlockLoop(), llvm::ARMBlockPlacement::revertWhileToDoLoop(), llvm::IRTranslator::runOnMachineFunction(), llvm::FunctionLoweringInfo::set(), split(), llvm::MachineBasicBlock::splitAt(), splitBlockForLoop(), llvm::MachineBasicBlock::SplitCriticalEdge(), splitEdge(), and splitMBB().
CreateMachineInstr()
MachineInstr * MachineFunction::CreateMachineInstr (const MCInstrDesc & MCID, DebugLoc DL, bool NoImplicit = false)
CreateMachineInstr - Allocate a new MachineInstr.
Allocate a new MachineInstr. Use this instead of ‘new MachineInstr’.
Use this instead of ‘new MachineInstr’.
Definition at line 380 of file MachineFunction.cpp.
References DL, and move.
Referenced by llvm::BuildMI(), llvm::HexagonPacketizerList::canPromoteToDotNew(), llvm::HexagonHazardRecognizer::EmitInstruction(), foldPatchpoint(), FuseInst(), FuseTwoAddrInst(), llvm::HexagonHazardRecognizer::getHazardType(), LowerCallResults(), llvm::HexagonPacketizerList::tryAllocateResourcesForConstExt(), and llvm::X86InstrInfo::unfoldMemoryOperand().
createMIExtraInfo()
MachineInstr::ExtraInfo * MachineFunction::createMIExtraInfo (ArrayRef< MachineMemOperand * > MMOs, MCSymbol * PreInstrSymbol = nullptr, MCSymbol * PostInstrSymbol = nullptr, MDNode * HeapAllocMarker = nullptr, MDNode * PCSections = nullptr, uint32_t CFIType = 0)
Allocate and construct an extra info structure for a MachineInstr.
This is allocated on the function's allocator and so lives the life of the function.
Definition at line 546 of file MachineFunction.cpp.
deallocateOperandArray()
void llvm::MachineFunction::deallocateOperandArray (OperandCapacity Cap, MachineOperand * Array) inline
Dellocate an array of MachineOperands and recycle the memory.
This is only intended for use by internal MachineInstr functions. Cap must be the same capacity that was used to allocate the array.
Definition at line 1035 of file MachineFunction.h.
References llvm::ArrayRecycler< T, Align >::deallocate().
Referenced by llvm::MachineInstr::addOperand(), and deleteMachineInstr().
deleteMachineBasicBlock()
void MachineFunction::deleteMachineBasicBlock (MachineBasicBlock * MBB)
DeleteMachineBasicBlock - Delete the given MachineBasicBlock.
Delete the given MachineBasicBlock.
Definition at line 460 of file MachineFunction.cpp.
References assert(), llvm::MachineBasicBlock::getParent(), MBB, and llvm::MachineJumpTableInfo::RemoveMBBFromJumpTables().
Referenced by llvm::IRTranslator::runOnMachineFunction().
deleteMachineInstr()
void MachineFunction::deleteMachineInstr (MachineInstr * MI)
DeleteMachineInstr - Delete the given MachineInstr.
Delete the given MachineInstr.
This function also serves as the MachineInstr destructor - the real ~MachineInstr() destructor must be empty.
Definition at line 425 of file MachineFunction.cpp.
References assert(), deallocateOperandArray(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and MI.
Referenced by llvm::HexagonPacketizerList::canPromoteToDotNew(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::SwingSchedulerDAG::finishBlock(), llvm::HexagonHazardRecognizer::getHazardType(), popRegsFromStack(), and llvm::HexagonPacketizerList::tryAllocateResourcesForConstExt().
dump()
LLVM_DUMP_METHOD void MachineFunction::dump () const
dump - Print the current MachineFunction to cerr, useful for debugger use.
Definition at line 577 of file MachineFunction.cpp.
References llvm::dbgs(), and print().
Referenced by llvm::A57ChainingConstraint::apply().
empty()
bool llvm::MachineFunction::empty () const inline
Definition at line 881 of file MachineFunction.h.
Referenced by llvm::rdf::DataFlowGraph::build(), llvm::SITargetLowering::finalizeLowering(), and RenumberBlocks().
end() [1/2]
iterator llvm::MachineFunction::end () inline
Definition at line 872 of file MachineFunction.h.
Referenced by assignBeginEndSections(), bbHasFallthrough(), BBHasFallthrough(), canFallThroughTo(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), FixTail(), getNextBlock(), jumpTableFollowsTB(), llvm::GraphTraits< DOTMachineFuncInfo * >::nodes_end(), RenumberBlocks(), llvm::CFIFixup::runOnMachineFunction(), llvm::MachineBasicBlock::SplitCriticalEdge(), and verifyCFIntrinsic().
end() [2/2]
const_iterator llvm::MachineFunction::end () const inline
Definition at line 873 of file MachineFunction.h.
ensureAlignment()
void llvm::MachineFunction::ensureAlignment (Align A) inline
ensureAlignment - Make sure the function is at least A bytes aligned.
Definition at line 726 of file MachineFunction.h.
Referenced by llvm::ARMBasicBlockUtils::computeBlockSize(), and llvm::R600AsmPrinter::runOnMachineFunction().
erase() [1/2]
void llvm::MachineFunction::erase (iterator MBBI) inline
Definition at line 904 of file MachineFunction.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), and MBBI.
Referenced by llvm::MachineBasicBlock::eraseFromParent().
erase() [2/2]
void llvm::MachineFunction::erase (MachineBasicBlock * MBBI) inline
Definition at line 905 of file MachineFunction.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::erase(), and MBBI.
eraseCallSiteInfo()
void MachineFunction::eraseCallSiteInfo (const MachineInstr * MI)
Following functions update call site info.
They should be called before removing, replacing or copying call instruction. Erase the call site info for MI. It is used to remove a call instruction from the instruction stream.
Definition at line 872 of file MachineFunction.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), getCallInstr(), and MI.
Referenced by copyCallSiteInfo(), moveCallSiteInfo(), and llvm::TargetInstrInfo::ReplaceTailWithBranchTo().
exposesReturnsTwice()
bool llvm::MachineFunction::exposesReturnsTwice () const inline
exposesReturnsTwice - Returns true if the function calls setjmp or any other similar functions with attribute "returns twice" without having the attribute itself.
Definition at line 734 of file MachineFunction.h.
Referenced by llvm::CodeViewDebug::beginFunctionImpl(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::needsFP(), and llvm::MIRPrinter::print().
finalizeDebugInstrRefs()
void MachineFunction::finalizeDebugInstrRefs ()
Finalise any partially emitted debug instructions.
These are DBG_INSTR_REF instructions where we only knew the vreg of the value they use, not the instruction that defines that vreg. Once isel finishes, we should have enough information for every DBG_INSTR_REF to point at an instruction (or DBG_PHI).
Definition at line 1135 of file MachineFunction.cpp.
References assert(), llvm::MachineRegisterInfo::def_instr_begin(), DefMI, llvm::TargetSubtargetInfo::getInstrInfo(), getSubtarget(), llvm::MachineRegisterInfo::hasOneDef(), MBB, MI, salvageCopySSA(), and TII.
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
front() [1/2]
MachineBasicBlock& llvm::MachineFunction::front () inline
Definition at line 883 of file MachineFunction.h.
front() [2/2]
const MachineBasicBlock& llvm::MachineFunction::front () const inline
Definition at line 882 of file MachineFunction.h.
Referenced by assignBeginEndSections(), llvm::WinException::beginFunction(), llvm::EHStreamer::computeCallSiteTable(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::EHStreamer::emitExceptionTable(), llvm::AsmPrinter::emitFunctionBody(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::X86AsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), findScratchNonCalleeSaveRegister(), llvm::getEHScopeMembership(), llvm::rdf::FuncNode::getEntryBlock(), llvm::GraphTraits< DOTMachineFuncInfo * >::getEntryNode(), llvm::getFunctionLiveInPhysReg(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::VEInstrInfo::getGlobalBaseReg(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::SlotIndexes::insertMBBInMaps(), isAlwaysIndirectTarget(), isSignExtendedW(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), PrevCrossBBInst(), llvm::SystemZELFFrameLowering::processFunctionBeforeFrameFinalized(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::rdf::CopyPropagation::run(), llvm::ARMBlockPlacement::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::sortBasicBlocksAndUpdateBranches(), and updateLiveness().
getAlignment()
Align llvm::MachineFunction::getAlignment () const inline
getAlignment - Return the alignment of the function.
Definition at line 720 of file MachineFunction.h.
Referenced by llvm::WinException::beginFunclet(), llvm::MipsAsmPrinter::emitFunctionEntryLabel(), and llvm::MIRPrinter::print().
getBlockNumbered()
MachineBasicBlock* llvm::MachineFunction::getBlockNumbered (unsigned N) const inline
getBlockNumbered - MachineBasicBlocks are automatically numbered when they are inserted into the machine function.
The block number for a machine basic block can be found by using the MBB::getNumber method, this method provides the inverse mapping.
Definition at line 805 of file MachineFunction.h.
References assert(), and N.
Referenced by llvm::ARMBasicBlockUtils::adjustBBOffsetsAfter(), llvm::SplitAnalysis::getFirstSplitPoint(), llvm::SplitAnalysis::getLastSplitPoint(), llvm::WebAssemblyFunctionInfo::initializeBaseYamlFields(), llvm::LiveRangeCalc::isJointlyDominated(), llvm::SPIRVCallLowering::lowerCall(), maybeUpdateTerminator(), and llvm::LiveVariables::recomputeForSingleDefVirtReg().
getCallSiteBeginLabel()
unsigned llvm::MachineFunction::getCallSiteBeginLabel (MCSymbol * BeginLabel) const inline
Get the call site number for a begin label.
Definition at line 1193 of file MachineFunction.h.
References assert(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::lookup().
Referenced by llvm::EHStreamer::computeCallSiteTable().
getCallSiteLandingPad()
SmallVectorImpl<unsigned>& llvm::MachineFunction::getCallSiteLandingPad (MCSymbol * Sym) inline
Get the call site indexes for a landing pad EH symbol.
Definition at line 1172 of file MachineFunction.h.
References assert().
getCallSitesInfo()
const CallSiteInfoMap& llvm::MachineFunction::getCallSitesInfo () const inline
Definition at line 1247 of file MachineFunction.h.
Referenced by collectCallSiteParameters(), and llvm::MIRPrinter::convertCallSiteObjects().
getCatchretTargets()
const std::vector<MCSymbol *>& llvm::MachineFunction::getCatchretTargets () const inline
Returns a reference to a list of symbols that we have catchrets.
Used to construct the catchret target table used by Windows EHCont Guard.
Definition at line 1091 of file MachineFunction.h.
Referenced by llvm::WinException::endFunction().
getCodeViewAnnotations()
ArrayRef<std::pair<MCSymbol *, MDNode *> > llvm::MachineFunction::getCodeViewAnnotations () const inline
Definition at line 1209 of file MachineFunction.h.
getConstantPool() [1/2]
MachineConstantPool* llvm::MachineFunction::getConstantPool () inline
getConstantPool - Return the constant pool object for the current function.
Definition at line 704 of file MachineFunction.h.
References ConstantPool.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), duplicateCPV(), llvm::WebAssemblyAsmPrinter::emitConstantPool(), llvm::AsmPrinter::emitConstantPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::PPCInstrInfo::finalizeInsInstrs(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::PPCInstrInfo::getConstantFromConstantPool(), llvm::AsmPrinter::GetCPISymbol(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::XCoreInstrInfo::loadImmediate(), llvm::LegalizerHelper::lowerFConstant(), llvm::MIRPrinter::print(), llvm::ARMBaseInstrInfo::produceSameValue(), llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), and llvm::MipsAsmPrinter::runOnMachineFunction().
getConstantPool() [2/2]
const MachineConstantPool* llvm::MachineFunction::getConstantPool () const inline
Definition at line 705 of file MachineFunction.h.
References ConstantPool.
getContext()
MCContext& llvm::MachineFunction::getContext () const inline
Definition at line 624 of file MachineFunction.h.
Referenced by llvm::ModuloScheduleTestAnnotater::annotate(), llvm::MipsAsmPrinter::emitFunctionBodyStart(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::AsmPrinter::emitPCSections(), llvm::AsmPrinter::emitPCSectionsLabel(), llvm::MachineBasicBlock::getBBIDOrNumber(), llvm::MachineBasicBlock::getEHCatchretSymbol(), llvm::MachineBasicBlock::getEndSymbol(), llvm::PPCFunctionInfo::getGlobalEPSymbol(), llvm::PPCFunctionInfo::getLocalEPSymbol(), getMCSymbolForMBB(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::PPCFunctionInfo::getTOCOffsetSymbol(), llvm::SIInstrInfo::insertIndirectBranch(), LowerCallResults(), llvm::SystemZAsmPrinter::PrintAsmOperand(), and llvm::X86AsmPrinter::runOnMachineFunction().
getDataLayout()
const DataLayout & MachineFunction::getDataLayout () const
Return the DataLayout attached to the Module associated to this MF.
Definition at line 292 of file MachineFunction.cpp.
References llvm::Module::getDataLayout(), and llvm::GlobalValue::getParent().
Referenced by llvm::X86TargetLowering::BuildFILD(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::LoongArchTargetLowering::CanLowerReturn(), llvm::RISCVTargetLowering::CanLowerReturn(), CC_AArch64_Custom_Block(), CC_ARM_AAPCS_Custom_Aggregate(), llvm::CallLowering::checkReturnTypeForCallConv(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), llvm::FunctionLoweringInfo::CreateRegs(), llvm::SystemZXPLINKFrameLowering::determineFrameLayout(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MipsAsmPrinter::emitInstruction(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::AsmPrinter::emitJumpTableInfo(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::InstructionSelector::executeMatchTable(), llvm::PPCInstrInfo::finalizeInsInstrs(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::AsmPrinter::GetCPISymbol(), llvm::SelectionDAG::getDataLayout(), llvm::PPCFunctionInfo::getGlobalEPSymbol(), getJTISymbol(), llvm::PPCFunctionInfo::getLocalEPSymbol(), llvm::WebAssemblyFrameLowering::getLocalForStackObject(), llvm::SwiftErrorValueTracking::getOrCreateVReg(), llvm::SwiftErrorValueTracking::getOrCreateVRegDefAt(), getPICBaseSymbol(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::AsmPrinter::GetSizeOfEncodedValue(), llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::M68kMCInstLower::GetSymbolFromOperand(), llvm::PPCFunctionInfo::getTOCOffsetSymbol(), llvm::MachinePointerInfo::getUnknownStack(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), llvm::MipsCallLowering::lowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::X86CallLowering::lowerFormalArguments(), llvm::ARMCallLowering::lowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerFRAMEADDR(), llvm::MipsCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), llvm::X86TargetLowering::markLibCallAttributes(), llvm::CombinerHelper::matchLoadOrCombine(), llvm::CombinerHelper::matchPtrAddZero(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::AsmPrinter::PrintSpecial(), processDbgDeclare(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::SITargetLowering::requiresUniformRegister(), and llvm::FunctionLoweringInfo::set().
getDenormalMode()
DenormalMode MachineFunction::getDenormalMode (const fltSemantics & FPType) const
Returns the denormal handling type for the default rounding mode of the function.
Definition at line 307 of file MachineFunction.cpp.
References llvm::Function::getDenormalMode().
Referenced by llvm::TargetLowering::expandIS_FPCLASS(), llvm::SelectionDAG::getDenormalMode(), and llvm::NVPTXTargetLowering::useF32FTZ().
getFilterIDFor()
int MachineFunction::getFilterIDFor (ArrayRef< unsigned > TyIds)
Return the id of the filter encoded by TyIds. This is function wide.
Definition at line 822 of file MachineFunction.cpp.
References llvm::append_range(), i, j(), and llvm::ArrayRef< T >::size().
Referenced by addLandingPad().
getFilterIds()
const std::vector<unsigned>& llvm::MachineFunction::getFilterIds () const inline
Return a reference to the typeids encoding filters used in the current function.
Definition at line 1220 of file MachineFunction.h.
Referenced by llvm::EHStreamer::computeActionsTable(), llvm::EHStreamer::emitExceptionTable(), and llvm::EHStreamer::emitTypeInfos().
getFrameInfo() [1/2]
MachineFrameInfo& llvm::MachineFunction::getFrameInfo () inline
getFrameInfo - Return the frame info object for the current function.
This object contains information about objects allocated on the stack frame of the current function in an abstract way.
Definition at line 688 of file MachineFunction.h.
Referenced by addCalleeSavedRegs(), llvm::addFrameReference(), llvm::M68k::addFrameReference(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::LiveRegUnits::addLiveOuts(), llvm::LivePhysRegs::addLiveOutsNoPristines(), llvm::M68k::addMemOperand(), llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::SIFrameLowering::allocateScavengingFrameIndexesNearIncomingSP(), llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPRLane(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::SIMachineFunctionInfo::allocateWWMSpill(), allSGPRSpillsAreDead(), llvm::SystemZELFFrameLowering::assignCalleeSavedSpillSlots(), llvm::ARCFrameLowering::assignCalleeSavedSpillSlots(), llvm::AArch64FrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::M68kFrameLowering::assignCalleeSavedSpillSlots(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZXPLINKFrameLowering::assignCalleeSavedSpillSlots(), llvm::PPCFrameLowering::assignCalleeSavedSpillSlots(), llvm::VirtRegMap::assignVirt2StackSlot(), llvm::CodeViewDebug::beginFunctionImpl(), buildEpilogRestore(), llvm::X86TargetLowering::BuildFILD(), buildPrologSpill(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), CalculateTailCallArgDest(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::M68kRegisterInfo::canRealignStack(), llvm::X86RegisterInfo::canRealignStack(), llvm::ARMFrameLowering::canSimplifyCallFramePseudos(), llvm::AArch64FrameLowering::canUseRedZone(), llvm::BaseIndexOffset::computeAliasing(), computeCalleeSaveRegisterPairs(), llvm::GISelKnownBits::computeKnownAlignment(), llvm::TargetLowering::computeKnownBitsForFrameIndex(), llvm::MIRPrinter::convertStackObjects(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::XCoreFunctionInfo::createFPSpillSlot(), llvm::MipsFunctionInfo::createISRRegFI(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::LegalizerHelper::createStackTemporary(), llvm::SelectionDAG::CreateStackTemporary(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::CSKYFrameLowering::determineCalleeSaves(), llvm::LanaiFrameLowering::determineCalleeSaves(), llvm::XCoreFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::SystemZELFFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::HexagonFrameLowering::determineCalleeSaves(), llvm::M68kFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::SystemZXPLINKFrameLowering::determineFrameLayout(), llvm::PPCFrameLowering::determineFrameLayoutAndUpdate(), llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), llvm::TargetOptions::DisableFramePointerElim(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::M68kRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Spills(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), emitCalleeSavedRestores(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::LoongArchFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::SystemZELFFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SystemZXPLINKFrameLowering::emitEpilogue(), llvm::MipsAsmPrinter::emitFrameDirective(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::AVRFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), emitSCSEpilogue(), emitSCSPrologue(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::AsmPrinter::emitStackSizeSection(), llvm::AsmPrinter::emitStackUsage(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), enableAllocFrameElim(), llvm::CCState::ensureMaxAlignment(), llvm::BaseIndexOffset::equalBaseIndex(), llvm::MipsFrameLowering::estimateStackSize(), llvm::VEInstrInfo::expandGetStackTopPseudo(), llvm::ARMTargetLowering::finalizeLowering(), fixupFuncForFI(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getAddressForMemoryInput(), llvm::TargetFrameLowering::getCalleeSaves(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::LoongArchFrameLowering::getFirstSPAdjustAmount(), llvm::RISCVFrameLowering::getFirstSPAdjustAmount(), getFPOffset(), getFRAMEADDR(), getFrameIndexMMO(), llvm::R600FrameLowering::getFrameIndexReference(), llvm::NVPTXFrameLowering::getFrameIndexReference(), llvm::MipsSEFrameLowering::getFrameIndexReference(), llvm::SIFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::CSKYFrameLowering::getFrameIndexReference(), llvm::SparcFrameLowering::getFrameIndexReference(), llvm::LoongArchFrameLowering::getFrameIndexReference(), llvm::VEFrameLowering::getFrameIndexReference(), llvm::HexagonFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::M68kFrameLowering::getFrameIndexReference(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::AArch64FrameLowering::getFrameIndexReferencePreferSP(), llvm::X86FrameLowering::getFrameIndexReferencePreferSP(), llvm::X86FrameLowering::getFrameIndexReferenceSP(), llvm::ARMBankConflictHazardRecognizer::getHazardType(), llvm::R600InstrInfo::getIndirectIndexBegin(), llvm::R600InstrInfo::getIndirectIndexEnd(), llvm::AArch64RegisterInfo::getLocalAddressRegister(), llvm::WebAssemblyFrameLowering::getLocalForStackObject(), getMachineMemOperand(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), llvm::MipsInstrInfo::GetMemOperand(), getMemsetStores(), llvm::RISCVMachineFunctionInfo::getMoveF64FrameIndex(), llvm::MipsFunctionInfo::getMoveF64ViaSpillFI(), getNonLibcallCSI(), llvm::SystemZELFFrameLowering::getOrCreateFramePointerSaveIndex(), llvm::AArch64InstrInfo::getOutliningTypeImpl(), llvm::ARMBaseInstrInfo::getOutliningTypeImpl(), llvm::ARMBaseRegisterInfo::getRegPressureLimit(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MachineInstr::getRestoreSize(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::AArch64FrameLowering::getSEHFrameIndexOffset(), llvm::MachineInstr::getSpillSize(), getStackOffset(), llvm::RISCVFrameLowering::getStackSizeWithRVVPadding(), GetTLSADDR(), getVGPRSpillLaneOrTempRegister(), llvm::X86FrameLowering::getWin64EHFrameIndexRef(), llvm::AArch64FrameLowering::getWinEHFuncletFrameSize(), handleMustTailForwardedRegisters(), llvm::LanaiRegisterInfo::hasBasePointer(), llvm::M68kRegisterInfo::hasBasePointer(), llvm::SIRegisterInfo::hasBasePointer(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::X86RegisterInfo::hasBasePointer(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::MipsFrameLowering::hasBP(), llvm::VEFrameLowering::hasBP(), llvm::RISCVFrameLowering::hasBP(), llvm::LoongArchFrameLowering::hasBP(), llvm::CSKYFrameLowering::hasBP(), llvm::AVRFrameLowering::hasFP(), llvm::MipsFrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::VEFrameLowering::hasFP(), llvm::WebAssemblyFrameLowering::hasFP(), llvm::RISCVFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::LoongArchFrameLowering::hasFP(), llvm::ARCFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::CSKYFrameLowering::hasFP(), llvm::SystemZELFFrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::HexagonFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::PPCFrameLowering::hasFP(), llvm::M68kFrameLowering::hasFP(), llvm::SystemZXPLINKFrameLowering::hasFP(), llvm::AVRFrameLowering::hasReservedCallFrame(), llvm::MipsSEFrameLowering::hasReservedCallFrame(), llvm::SparcFrameLowering::hasReservedCallFrame(), llvm::Thumb1FrameLowering::hasReservedCallFrame(), llvm::Mips16FrameLowering::hasReservedCallFrame(), llvm::LoongArchFrameLowering::hasReservedCallFrame(), llvm::WebAssemblyFrameLowering::hasReservedCallFrame(), llvm::MSP430FrameLowering::hasReservedCallFrame(), llvm::RISCVFrameLowering::hasReservedCallFrame(), llvm::ARMFrameLowering::hasReservedCallFrame(), llvm::AArch64FrameLowering::hasReservedCallFrame(), llvm::CSKYFrameLowering::hasReservedCallFrame(), llvm::X86FrameLowering::hasReservedCallFrame(), llvm::M68kFrameLowering::hasReservedCallFrame(), llvm::inferAlignFromPtrInfo(), llvm::SelectionDAG::InferPtrAlign(), llvm::SIMachineFunctionInfo::initializeBaseYamlFields(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::CallLowering::insertSRetOutgoingArgument(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), isConsecutiveLSLoc(), llvm::MachineInstr::isDereferenceableInvariantLoad(), llvm::XCoreFunctionInfo::isLargeFrame(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), isXPLeafCandidate(), llvm::LoongArchInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::M68kInstrInfo::loadRegFromStackSlot(), llvm::X86InstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlotNoUpd(), llvm::AMDGPUTargetLowering::loadStackInputValue(), LowerAsSplatVectorLoad(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::LanaiTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), lowerFRAMEADDR(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), llvm::LanaiTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), llvm::HexagonTargetLowering::LowerRETURNADDR(), lowerRETURNADDR(), LowerRETURNADDR(), llvm::AMDGPUCallLowering::lowerTailCall(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::VETargetLowering::lowerVASTART(), LowerVASTART(), llvm::SparcTargetLowering::makeAddress(), llvm::Mips16InstrInfo::makeFrame(), llvm::MachineInstr::mayAlias(), llvm::AArch64Subtarget::mirFileLoaded(), llvm::HexagonFrameLowering::needsAligna(), llvm::PPCFrameLowering::needsFP(), llvm::RISCVRegisterInfo::needsFrameBaseReg(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::X86FrameLowering::needsFrameIndexResolution(), llvm::M68kFrameLowering::needsFrameIndexResolution(), llvm::TargetFrameLowering::needsFrameIndexResolution(), llvm::WebAssemblyFrameLowering::needsPrologForEH(), needsShadowCallStackPrologueEpilogue(), llvm::SystemZELFFrameLowering::orderFrameObjects(), llvm::AArch64FrameLowering::orderFrameObjects(), llvm::X86FrameLowering::orderFrameObjects(), llvm::SGPRSpillBuilder::prepare(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::MIRPrinter::print(), llvm::MIPrinter::print(), llvm::MachineInstr::print(), printMemOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized(), llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized(), llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized(), llvm::ARCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZELFFrameLowering::processFunctionBeforeFrameFinalized(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZXPLINKFrameLowering::processFunctionBeforeFrameFinalized(), llvm::recomputeLivenessFlags(), requiresAAPCSFrameRecord(), llvm::SIRegisterInfo::requiresFrameIndexReplacementScavenging(), llvm::PPCRegisterInfo::requiresFrameIndexScavenging(), llvm::SIRegisterInfo::requiresRegisterScavenging(), llvm::SIFrameLowering::requiresStackPointerReference(), reservePrivateMemoryRegs(), llvm::AArch64FrameLowering::resetCFIToInitialState(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), llvm::Mips16InstrInfo::restoreFrame(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::AVRFrameAnalyzer::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::HexagonDAGToDAGISel::SelectAddrFI(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), llvm::FastISel::selectStackmap(), llvm::FunctionLoweringInfo::set(), setAlignFlagsForFI(), llvm::AsmPrinter::SetupMachineFunction(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::TargetRegisterInfo::shouldRealignStack(), llvm::AArch64FunctionInfo::shouldSignReturnAddress(), llvm::yaml::SIMachineFunctionInfo::SIMachineFunctionInfo(), llvm::Mips16FrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::LoongArchFrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::ARMSubtarget::splitFramePointerPush(), llvm::CriticalAntiDepBreaker::StartBlock(), llvm::AggressiveAntiDepBreaker::StartBlock(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::M68kInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlotNoUpd(), tryToElideArgumentCopy(), unpack64(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), updateLiveness(), llvm::HexagonPacketizerList::useCalleesSP(), llvm::HexagonPacketizerList::useCallersSP(), llvm::SIMachineFunctionInfo::usesAGPRs(), llvm::RISCVMachineFunctionInfo::useSaveRestoreLibCalls(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and WindowsRequiresStackProbe().
getFrameInfo() [2/2]
const MachineFrameInfo& llvm::MachineFunction::getFrameInfo () const inline
Definition at line 689 of file MachineFunction.h.
getFrameInstructions()
const std::vector<MCCFIInstruction>& llvm::MachineFunction::getFrameInstructions () const inline
Returns a reference to a list of cfi instructions in the function's prologue.
Used to construct frame maps for debug and exception handling comsumers.
Definition at line 1072 of file MachineFunction.h.
Referenced by llvm::AsmPrinter::emitCFIInstruction(), and llvm::X86FrameLowering::mergeSPUpdates().
getFunction() [1/2]
Function& llvm::MachineFunction::getFunction () inline
Return the LLVM function that this machine code represents.
Definition at line 638 of file MachineFunction.h.
References F.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), AlignBlocks(), allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateSpecialInputSGPRs(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::MachineOptimizationRemarkEmitter::allowExtraAnalysis(), llvm::NVPTXTargetLowering::allowUnsafeFPMath(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::CombinerHelper::applyCombineConstantFoldFpUnary(), llvm::AMDGPUCallLowering::areCalleeOutgoingArgsTailCallable(), llvm::SystemZELFFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZXPLINKFrameLowering::assignCalleeSavedSpillSlots(), llvm::DwarfCFIException::beginBasicBlockSection(), llvm::WinException::beginFunclet(), llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::BTFDebug::beginFunctionImpl(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::DwarfDebug::beginFunctionImpl(), llvm::DwarfDebug::beginInstruction(), llvm::MachineIRBuilder::buildFConstant(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::TargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildSREMPow2(), llvm::AArch64CallLowering::canLowerReturn(), llvm::X86CallLowering::canLowerReturn(), llvm::AArch64TargetLowering::canMergeStoresTo(), llvm::X86TargetLowering::canMergeStoresTo(), llvm::TargetRegisterInfo::canRealignStack(), llvm::AArch64FrameLowering::canUseRedZone(), CC_X86_Intr(), checkNumAlignedDPRCS2Regs(), llvm::CallLowering::checkReturnTypeForCallConv(), collectCallSiteParameters(), combineFMA(), combineFMADDSUB(), combineFMinNumFMaxNum(), combineFneg(), combineMul(), combineStore(), combineVectorSizedSetCCEquality(), computeCalleeSaveRegisterPairs(), llvm::SITargetLowering::computeKnownAlignForTargetInstr(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), convertImplicitDefToConstZero(), llvm::MIRPrinter::convertMachineMetadataNodes(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::createMemLibcall(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::CallLowering::determineAndHandleAssignments(), llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::CSKYFrameLowering::determineCalleeSaves(), llvm::XCoreFrameLowering::determineCalleeSaves(), llvm::SystemZELFFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::TargetOptions::DisableFramePointerElim(), llvm::AMDGPUCallLowering::doCallerAndCalleePassArgsTheSameWay(), duplicateCPV(), llvm::M68kFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::MachineOptimizationRemarkEmitter::emit(), llvm::AsmPrinter::emitBasicBlockStart(), EmitCmp(), emitConstantSizeRepmov(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::LoongArchFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::SystemZELFFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::EHStreamer::emitExceptionTable(), llvm::emitFrameOffset(), llvm::AsmPrinter::emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::MipsAsmPrinter::emitFunctionBodyStart(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), llvm::ARMAsmPrinter::emitFunctionEntryLabel(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::AsmPrinter::emitFunctionEntryLabel(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitHiddenKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), llvm::DwarfDebug::emitInitialLocDirective(), llvm::AsmPrinter::emitInitialRawDwarfLocDirective(), llvm::AsmPrinter::emitJumpTableInfo(), llvm::X86AsmPrinter::emitKCFITypeId(), llvm::AsmPrinter::emitKCFITypeId(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernel(), llvm::AMDGPU::HSAMD::MetadataStreamerYamlV2::emitKernel(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernelArgs(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitNonHSAIntrinsicError(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::AsmPrinter::emitPCSections(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), emitRemovedIntrinsicError(), llvm::AArch64RegisterInfo::emitReservedArgRegCallError(), emitSCSEpilogue(), emitSCSPrologue(), llvm::AsmPrinter::emitStackUsage(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), llvm::AsmPrinter::emitXRayTable(), enableAllocFrameElim(), llvm::ARMFrameLowering::enableCalleeSaveSkip(), llvm::HexagonFrameLowering::enableCalleeSaveSkip(), llvm::TargetFrameLowering::enableCalleeSaveSkip(), llvm::LoongArchFrameLowering::enableShrinkWrapping(), llvm::RISCVFrameLowering::enableShrinkWrapping(), llvm::X86FrameLowering::enableShrinkWrapping(), llvm::ARMException::endFunction(), llvm::AIXException::endFunction(), llvm::WinException::endFunction(), llvm::CodeViewDebug::endFunctionImpl(), llvm::DwarfDebug::endFunctionImpl(), errorUnsupported(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::AArch64InstrInfo::expandPostRAPseudo(), fail(), llvm::AArch64CallLowering::fallBackToDAGISel(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::generateEnqueueInst(), llvm::VERegisterInfo::getCalleeSavedRegs(), llvm::LoongArchRegisterInfo::getCalleeSavedRegs(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::RISCVRegisterInfo::getCalleeSavedRegs(), llvm::CSKYRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::SIRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::SystemZELFRegisters::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::X86RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::AArch64RegisterInfo::getCallPreservedMask(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::SystemZELFRegisters::getCallPreservedMask(), llvm::ARMBaseRegisterInfo::getCallPreservedMask(), llvm::AArch64RegisterInfo::getDarwinCalleeSavedRegs(), llvm::AArch64RegisterInfo::getDarwinCallPreservedMask(), llvm::MachineIRBuilder::getDataLayout(), llvm::SIInstrInfo::getDSShaderTypeValue(), llvm::getEHScopeMembership(), getFPOffset(), llvm::AArch64FrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::AsmPrinter::getFunctionCFISectionType(), llvm::SIMachineFunctionInfo::getGITPtrLoReg(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::ARMSubtarget::getGPRAllocationOrder(), llvm::X86RegisterInfo::getGPRsForTailCall(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getHSAKernelProps(), llvm::AMDGPUTargetLowering::getImplicitParameterOffset(), llvm::PerFunctionMIParsingState::getIRValue(), getLoadStackGuard(), llvm::GCNSubtarget::getMaxNumSGPRs(), llvm::GCNSubtarget::getMaxNumVGPRs(), getMCSymbolForMBB(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getName(), llvm::GCNSubtarget::getNSAThreshold(), llvm::AMDGPUSubtarget::getOccupancyWithLocalMemSize(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::getOrCreateSPIRVDeviceEventPointer(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVTypeByName(), llvm::VETargetLowering::getPICJumpTableRelocBase(), getRecipEstimateForFunc(), getRegistersForValue(), llvm::SIRegisterInfo::getRegPressureLimit(), llvm::SystemZELFFrameLowering::getRegSpillOffset(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::M68kRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::getSampledImageType(), GetScratchRegister(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::SystemZTargetLowering::getStackProbeSize(), llvm::PPCTargetLowering::getStackProbeSize(), llvm::X86TargetLowering::getStackProbeSize(), llvm::X86TargetLowering::getStackProbeSymbolName(), llvm::AArch64RegisterInfo::getStrictlyReservedRegs(), llvm::SelectionDAG::getSymbolFunctionGlobalAddress(), GetSymbolRef(), llvm::RISCVInstrInfo::getVLENFactoredAmount(), llvm::CallLowering::handleAssignments(), handleMustTailForwardedRegisters(), llvm::X86FrameLowering::has128ByteRedZone(), hasDebugInfo(), llvm::HexagonFrameLowering::hasFP(), llvm::SystemZTargetLowering::hasInlineStackProbe(), llvm::PPCTargetLowering::hasInlineStackProbe(), llvm::X86TargetLowering::hasInlineStackProbe(), hasInstrProfHashMismatch(), HasNestArgument(), hasReturnsTwiceAttr(), llvm::HexagonEvaluator::HexagonEvaluator(), llvm::ARMSubtarget::ignoreCSRForAllocationOrder(), llvm::inferAlignFromPtrInfo(), llvm::SelectionDAG::init(), llvm::PreRARematStage::initGCNSchedStage(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::LexicalScopes::initialize(), INITIALIZE_PASS(), llvm::MIRParserImpl::initializeConstantPool(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::SystemZELFFrameLowering::inlineStackProbe(), InsertReturnAddressAuth(), interpretValues(), llvm::X86RegisterInfo::isArgumentRegister(), llvm::AArch64RegisterInfo::isArgumentRegister(), llvm::AArch64RegisterInfo::isAsmClobberable(), isCallableFunction(), llvm::TargetRegisterInfo::isCalleeSavedPhysReg(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::AMDGPUCallLowering::isEligibleForTailCallOptimization(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), llvm::SparcTargetLowering::IsEligibleForTailCallOptimization(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::RISCVInstrInfo::isFunctionSafeToOutlineFrom(), llvm::AArch64InstrInfo::isFunctionSafeToOutlineFrom(), llvm::ARMBaseInstrInfo::isFunctionSafeToOutlineFrom(), llvm::X86InstrInfo::isFunctionSafeToOutlineFrom(), isLibCallInTailPosition(), isMinSize(), isNoReturnDef(), isOptNone(), isOptSize(), llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isXPLeafCandidate(), knownBitsForWorkitemID(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::SIInstrInfo::legalizeOperands(), llvm::AMDGPULegalizerInfo::legalizeTrapHsaQueuePtr(), llvm::LegalizerHelper::libcall(), llvm::SIMachineFunctionInfo::limitOccupancy(), llvm::MachineBasicBlock::liveout_begin(), llvm::XCoreInstrInfo::loadImmediate(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::AMDGPUCallLowering::lowerCall(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::CallLowering::lowerCall(), llvm::AsmPrinter::lowerConstant(), llvm::AMDGPUTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::LegalizerHelper::lowerFConstant(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::InlineAsmLowering::lowerInlineAsm(), LowerInterruptReturn(), llvm::LegalizerHelper::lowerLoad(), llvm::MipsCallLowering::lowerReturn(), llvm::PPCCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), llvm::M68kCallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::LegalizerHelper::lowerStore(), llvm::AMDGPUCallLowering::lowerTailCall(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVACOPY(), llvm::SparcTargetLowering::makeAddress(), llvm::X86TargetLowering::markLibCallAttributes(), llvm::CombinerHelper::matchLoadOrCombine(), llvm::TargetInstrInfo::mergeOutliningCandidateAttributes(), needFuncLabels(), llvm::AArch64FunctionInfo::needsAsyncDwarfUnwindInfo(), llvm::PPCFrameLowering::needsFP(), llvm::WebAssemblyFrameLowering::needsPrologForEH(), needsPrologueENDBR(), llvm::AsmPrinter::needsSEHMoves(), needsShadowCallStackPrologueEpilogue(), needsWinCFI(), llvm::OptLevelChanger::OptLevelChanger(), parseGlobalValue(), parseIRValue(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::AMDGPUCallLowering::passSpecialInputs(), llvm::SITargetLowering::passSpecialInputs(), performBRCONDCombine(), llvm::RISCVTargetLowering::preferredShiftLegalizationStrategy(), llvm::AArch64TargetLowering::preferredShiftLegalizationStrategy(), llvm::X86TargetLowering::preferredShiftLegalizationStrategy(), llvm::MIRPrinter::print(), llvm::MIPrinter::print(), print(), llvm::MachineBasicBlock::print(), llvm::MachineInstr::print(), printMemOperand(), llvm::SystemZELFFrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), produceCompactUnwindFrame(), ProfitableToMerge(), promoteToConstantPool(), reduceVMULWidth(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), reportIllegalCopy(), reservePrivateMemoryRegs(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreWinEHStackPointersInParent(), llvm::CallLowering::resultsCompatible(), llvm::MIRProfileLoader::runOnFunction(), llvm::ARMBlockPlacement::runOnMachineFunction(), llvm::InstructionSelect::runOnMachineFunction(), llvm::BreakFalseDeps::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), AMDGPUDAGToDAGISel::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), llvm::MachineOptimizationRemarkEmitterPass::runOnMachineFunction(), llvm::RegBankSelect::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::RAGreedy::selectOrSplit(), llvm::SwiftErrorValueTracking::setFunction(), llvm::AsmPrinter::SetupMachineFunction(), llvm::TargetLoweringObjectFileXCOFF::ShouldEmitEHBlock(), shouldGenerateInlineTPLoop(), shouldLowerMemFuncForSize(), llvm::InstructionSelector::shouldOptForSize(), llvm::shouldOptForSize(), llvm::FastISel::shouldOptForSize(), llvm::SelectionDAG::shouldOptForSize(), llvm::RISCVInstrInfo::shouldOutlineFromFunctionByDefault(), llvm::AArch64InstrInfo::shouldOutlineFromFunctionByDefault(), llvm::ARMBaseInstrInfo::shouldOutlineFromFunctionByDefault(), llvm::TargetRegisterInfo::shouldRealignStack(), llvm::TargetLoweringObjectFileXCOFF::ShouldSetSSPCanaryBitInTB(), shouldSplitStack(), llvm::TailDuplicator::shouldTailDuplicate(), llvm::TargetLowering::SimplifySetCC(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::ARMSubtarget::splitFramePointerPush(), splitStores(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64TargetLowering::supportSplitCSR(), transformCallee(), unpackFromRegLoc(), llvm::SystemZELFFrameLowering::usePackedStack(), llvm::SIMachineFunctionInfo::usesAGPRs(), llvm::RISCVMachineFunctionInfo::useSaveRestoreLibCalls(), llvm::R600InstrInfo::usesTextureCache(), llvm::R600InstrInfo::usesVertexCache(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), WarnSize(), llvm::LegalizerHelper::widenScalar(), WindowsRequiresStackProbe(), windowsRequiresStackProbe(), and llvm::OptLevelChanger::~OptLevelChanger().
getFunction() [2/2]
const Function& llvm::MachineFunction::getFunction () const inline
Return the LLVM function that this machine code represents.
Definition at line 641 of file MachineFunction.h.
References F.
getFunctionNumber()
unsigned llvm::MachineFunction::getFunctionNumber () const inline
getFunctionNumber - Return a unique ID for the current function.
Definition at line 647 of file MachineFunction.h.
Referenced by llvm::NVPTXFrameLowering::emitPrologue(), llvm::MachineBasicBlock::getEHCatchretSymbol(), llvm::TargetLoweringObjectFileXCOFF::getEHInfoTableSymbol(), llvm::MachineBasicBlock::getEndSymbol(), llvm::AsmPrinter::getFunctionNumber(), llvm::PPCFunctionInfo::getGlobalEPSymbol(), getJTISymbol(), llvm::PPCFunctionInfo::getLocalEPSymbol(), getPICBaseSymbol(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::PPCFunctionInfo::getTOCOffsetSymbol(), and llvm::VETargetLowering::lowerINTRINSIC_WO_CHAIN().
getInfo() [1/2]
template<typename Ty > Ty* llvm::MachineFunction::getInfo () inline
getInfo - Keep track of various per-function pieces of information for backends that would like to do so.
Definition at line 770 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), allSGPRSpillsAreDead(), llvm::WebAssemblyInstrInfo::analyzeBranch(), llvm::AMDGPURegisterBankInfo::applyMappingDynStackAlloc(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPUCallLowering::areCalleeOutgoingArgsTailCallable(), llvm::ARMBasicBlockUtils::ARMBasicBlockUtils(), llvm::SIFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZELFFrameLowering::assignCalleeSavedSpillSlots(), llvm::AArch64FrameLowering::assignCalleeSavedSpillSlots(), llvm::ARMFrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::M68kFrameLowering::assignCalleeSavedSpillSlots(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZXPLINKFrameLowering::assignCalleeSavedSpillSlots(), buildGitPtr(), llvm::AArch64InstrInfo::buildOutlinedFrame(), buildScratchExecCopy(), llvm::SIRegisterInfo::buildSpillLoadStore(), CalculateTailCallSPDiff(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::X86FrameLowering::canSimplifyCallFramePseudos(), canSpillOnFrameIndexAccess(), llvm::RISCVFrameLowering::canUseAsEpilogue(), llvm::X86FrameLowering::canUseAsEpilogue(), llvm::RISCVFrameLowering::canUseAsPrologue(), llvm::X86FrameLowering::canUseAsPrologue(), llvm::AArch64FrameLowering::canUseRedZone(), checkNumAlignedDPRCS2Regs(), computeCalleeSaveRegisterPairs(), llvm::RISCVTargetMachine::convertFuncInfoToYAML(), llvm::AArch64TargetMachine::convertFuncInfoToYAML(), llvm::WebAssemblyTargetMachine::convertFuncInfoToYAML(), llvm::GCNTargetMachine::convertFuncInfoToYAML(), llvm::SIFrameLowering::determineCalleeSaves(), llvm::SparcFrameLowering::determineCalleeSaves(), llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::CSKYFrameLowering::determineCalleeSaves(), llvm::VEFrameLowering::determineCalleeSaves(), llvm::XCoreFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::SystemZELFFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::HexagonFrameLowering::determineCalleeSaves(), llvm::M68kFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), duplicateCPV(), llvm::ARCFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::M68kFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitBuildPairF64Pseudo(), llvm::SIFrameLowering::emitCSRSpillRestores(), llvm::SIFrameLowering::emitCSRSpillStores(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::LoongArchFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::SystemZELFFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SystemZXPLINKFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogueInsns(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::X86AsmPrinter::emitFunctionBodyStart(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::AVRFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologueInsns(), emitSCSEpilogue(), emitSCSPrologue(), emitShadowCallStackEpilogue(), emitSplitF64Pseudo(), llvm::ARMFrameLowering::enableShrinkWrapping(), llvm::PPCFrameLowering::enableShrinkWrapping(), llvm::AArch64FrameLowering::enableStackSlotScavenging(), estimateRSStackSizeLimit(), ExpandMOVImmSExti8(), llvm::SITargetLowering::finalizeLowering(), fixupFuncForFI(), getArgumentStackToRestore(), llvm::AVRRegisterInfo::getCalleeSavedRegs(), llvm::HexagonRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::X86RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::ARMFrameLowering::getCalleeSaves(), getCallOpcode(), llvm::AArch64RegisterInfo::getDarwinCalleeSavedRegs(), llvm::WebAssemblyFrameLowering::getDwarfFrameBase(), llvm::RISCVFrameLowering::getFirstSPAdjustAmount(), getFPOffset(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::CSKYFrameLowering::getFrameIndexReference(), llvm::SparcFrameLowering::getFrameIndexReference(), llvm::LoongArchFrameLowering::getFrameIndexReference(), llvm::HexagonFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::M68kFrameLowering::getFrameIndexReference(), llvm::AArch64FrameLowering::getFrameIndexReferencePreferSP(), llvm::X86FrameLowering::getFrameIndexReferencePreferSP(), llvm::WebAssemblyRegisterInfo::getFrameRegister(), llvm::SIRegisterInfo::getFrameRegister(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::VEInstrInfo::getGlobalBaseReg(), llvm::M68kInstrInfo::getGlobalBaseReg(), llvm::X86InstrInfo::getGlobalBaseReg(), llvm::MipsTargetLowering::getGlobalReg(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getHSAKernelProps(), llvm::AMDGPUTargetLowering::getImplicitParameterOffset(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::ARMBaseInstrInfo::getInstSizeInBytes(), getLibCallID(), llvm::WebAssemblyFrameLowering::getLocalForStackObject(), llvm::GCNSubtarget::getMaxNumSGPRs(), llvm::GCNSubtarget::getMaxNumVGPRs(), llvm::AMDGPUSubtarget::getOccupancyWithLocalMemSize(), llvm::SystemZELFFrameLowering::getOrCreateFramePointerSaveIndex(), llvm::AArch64InstrInfo::getOutliningTypeImpl(), llvm::SIRegisterInfo::getRegPressureLimit(), llvm::GCNSubtarget::getReservedNumSGPRs(), llvm::HexagonRegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::SIRegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::RISCVFrameLowering::getStackSizeWithRVVPadding(), getSVEStackSize(), llvm::SITargetLowering::getTgtMemIntrinsic(), getVGPRSpillLaneOrTempRegister(), llvm::X86FrameLowering::getWin64EHFrameIndexRef(), llvm::AArch64FrameLowering::getWinEHFuncletFrameSize(), llvm::X86FrameLowering::getWinEHParentFrameOffset(), handleMustTailForwardedRegisters(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::X86RegisterInfo::hasBasePointer(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::AVRFrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::HexagonFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), hasFP32Denormals(), hasFP64FP16Denormals(), llvm::VEFrameLowering::hasGOT(), hasNonRISpills(), llvm::X86FrameLowering::hasReservedCallFrame(), llvm::M68kFrameLowering::hasReservedCallFrame(), llvm::RISCVRegisterInfo::hasReservedSpillSlot(), llvm::PPCRegisterInfo::hasReservedSpillSlot(), hasSpills(), indirectCopyToAGPR(), llvm::GCNSchedStrategy::initialize(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), InsertReturnAddressAuth(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::AArch64InstrInfo::isFunctionSafeToOutlineFrom(), llvm::ARMBaseInstrInfo::isFunctionSafeToOutlineFrom(), llvm::X86InstrInfo::isFunctionSafeToOutlineFrom(), llvm::SITargetLowering::isKnownNeverNaNForTargetNode(), llvm::ARMBaseInstrInfo::isPredicable(), isSignExtendedW(), llvm::PPCInstrInfo::isSignOrZeroExtended(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeMinNumMaxNum(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlotNoUpd(), llvm::MipsCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::AMDGPUCallLowering::lowerCall(), llvm::SITargetLowering::LowerCall(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerINTRINSIC_W_CHAIN(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::AMDGPUCallLowering::lowerTailCall(), LowerToTLSLocalDynamicModel(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), llvm::LanaiTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), llvm::VETargetLowering::lowerVASTART(), llvm::HexagonTargetLowering::LowerVASTART(), LowerVASTART(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), MustSaveLR(), llvm::PPCFrameLowering::needsFP(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::X86FrameLowering::needsFrameIndexResolution(), llvm::M68kFrameLowering::needsFrameIndexResolution(), llvm::AMDGPUMIRFormatter::parseCustomPseudoSourceValue(), llvm::RISCVTargetMachine::parseMachineFunctionInfo(), llvm::AArch64TargetMachine::parseMachineFunctionInfo(), llvm::WebAssemblyTargetMachine::parseMachineFunctionInfo(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::AMDGPUCallLowering::passSpecialInputs(), popRegsFromStack(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized(), llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZELFFrameLowering::processFunctionBeforeFrameFinalized(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameIndicesReplaced(), promoteToConstantPool(), llvm::Thumb2InstrInfo::ReplaceTailWithBranchTo(), llvm::SIRegisterInfo::requiresRegisterScavenging(), llvm::SIFrameLowering::requiresStackPointerReference(), llvm::AArch64FrameLowering::resetCFIToInitialState(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::ARMFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::restoreStatusRegister(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), llvm::R600AsmPrinter::runOnMachineFunction(), llvm::WebAssemblyAsmPrinter::runOnMachineFunction(), llvm::M68kAsmPrinter::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), llvm::AVRFrameAnalyzer::runOnMachineFunction(), llvm::GCNIterativeScheduler::scheduleILP(), llvm::GCNIterativeScheduler::scheduleLegacyMaxOccupancy(), llvm::GCNIterativeScheduler::scheduleMinReg(), llvm::HexagonDAGToDAGISel::SelectFrameIndex(), setUsesTOCBasePtr(), llvm::SIRegisterInfo::shouldRealignStack(), signOutlinedFunction(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), spillsCR(), spillVGPRtoAGPR(), llvm::ARMSubtarget::splitFramePushPop(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::AMDGPUTargetLowering::storeStackInputValue(), llvm::SITargetLowering::supportSplitCSR(), llvm::GCNIterativeScheduler::tryMaximizeOccupancy(), unpackFromRegLoc(), unstackifyVRegsUsedInSplitBB(), and llvm::AArch64RegisterInfo::useFPForScavengingIndex().
getInfo() [2/2]
template<typename Ty > const Ty* llvm::MachineFunction::getInfo () const inline
Definition at line 775 of file MachineFunction.h.
getInstructionCount()
unsigned llvm::MachineFunction::getInstructionCount () const inline
Return the number of MachineInstrs in this MachineFunction.
Definition at line 913 of file MachineFunction.h.
References InstrCount, and MBB.
getJTISymbol()
MCSymbol * MachineFunction::getJTISymbol (unsigned JTI, MCContext & Ctx, bool isLinkerPrivate = false) const
getJTISymbol - Return the MCSymbol for the specified non-empty jump table.
Return the MCSymbol for the specified non-empty jump table.
If isLinkerPrivate is specified, an 'l' label is returned, otherwise a normal 'L' label is returned.
Definition at line 719 of file MachineFunction.cpp.
References assert(), DL, getDataLayout(), getFunctionNumber(), llvm::MCContext::getOrCreateSymbol(), llvm::cl::Prefix, and size().
Referenced by llvm::AsmPrinter::GetJTISymbol(), llvm::M68kTargetLowering::getPICJumpTableRelocBaseExpr(), and llvm::TargetLowering::getPICJumpTableRelocBaseExpr().
getJumpTableInfo() [1/2]
MachineJumpTableInfo* llvm::MachineFunction::getJumpTableInfo () inline
Definition at line 696 of file MachineFunction.h.
getJumpTableInfo() [2/2]
const MachineJumpTableInfo* llvm::MachineFunction::getJumpTableInfo () const inline
getJumpTableInfo - Return the jump table info object for the current function.
This object contains information about jump tables in the current function. If the current function has no jump tables, this will return null.
Definition at line 695 of file MachineFunction.h.
Referenced by llvm::ARMAsmPrinter::emitJumpTableAddrs(), llvm::AsmPrinter::emitJumpTableInfo(), llvm::ARMAsmPrinter::emitJumpTableInsts(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), llvm::BranchFolder::OptimizeFunction(), and llvm::MIRPrinter::print().
getLandingPads()
const std::vector<LandingPadInfo>& llvm::MachineFunction::getLandingPads () const inline
Return a reference to the landing pad info for the current function.
Definition at line 1123 of file MachineFunction.h.
Referenced by llvm::DwarfCFIException::beginFunction(), llvm::WinException::beginFunction(), llvm::SystemZELFFrameLowering::determineCalleeSaves(), llvm::M68kFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::EHStreamer::emitExceptionTable(), llvm::WasmException::endFunction(), llvm::ARMException::endFunction(), needFuncLabels(), and llvm::TargetLoweringObjectFileXCOFF::ShouldEmitEHBlock().
getLongjmpTargets()
const std::vector<MCSymbol *>& llvm::MachineFunction::getLongjmpTargets () const inline
Returns a reference to a list of symbols immediately following calls to _setjmp in the function.
Used to construct the longjmp target table used by Windows Control Flow Guard.
Definition at line 1081 of file MachineFunction.h.
Referenced by llvm::WinCFGuard::endFunction().
getMachineMemOperand() [1/8]
MachineMemOperand * MachineFunction::getMachineMemOperand (const MachineMemOperand * MMO, const AAMDNodes & AAInfo)
Allocate a new MachineMemOperand by copying an existing one, replacing only AliasAnalysis information.
MachineMemOperands are owned by the MachineFunction and need not be explicitly deallocated.
Definition at line 525 of file MachineFunction.cpp.
References llvm::MachineMemOperand::getBaseAlign(), llvm::MachineMemOperand::getFailureOrdering(), llvm::MachineMemOperand::getFlags(), llvm::MachineMemOperand::getOffset(), llvm::MachineMemOperand::getPseudoValue(), llvm::MachineMemOperand::getRanges(), llvm::MachineMemOperand::getSize(), llvm::MachineMemOperand::getSuccessOrdering(), llvm::MachineMemOperand::getSyncScopeID(), and llvm::MachineMemOperand::getValue().
getMachineMemOperand() [2/8]
MachineMemOperand * MachineFunction::getMachineMemOperand (const MachineMemOperand * MMO, const MachinePointerInfo & PtrInfo, LLT Ty)
Definition at line 497 of file MachineFunction.cpp.
References llvm::MachineMemOperand::getBaseAlign(), llvm::MachineMemOperand::getFailureOrdering(), llvm::MachineMemOperand::getFlags(), llvm::MachineMemOperand::getSuccessOrdering(), and llvm::MachineMemOperand::getSyncScopeID().
getMachineMemOperand() [3/8]
MachineMemOperand * MachineFunction::getMachineMemOperand (const MachineMemOperand * MMO, const MachinePointerInfo & PtrInfo, uint64_t Size)
getMachineMemOperand - Allocate a new MachineMemOperand by copying an existing one, replacing only the MachinePointerInfo and size.
MachineMemOperands are owned by the MachineFunction and need not be explicitly deallocated.
Definition at line 489 of file MachineFunction.cpp.
References llvm::MachineMemOperand::getBaseAlign(), llvm::MachineMemOperand::getFailureOrdering(), llvm::MachineMemOperand::getFlags(), llvm::MachineMemOperand::getSuccessOrdering(), and llvm::MachineMemOperand::getSyncScopeID().
getMachineMemOperand() [4/8]
MachineMemOperand * MachineFunction::getMachineMemOperand (const MachineMemOperand * MMO, int64_t Offset, LLT Ty)
getMachineMemOperand - Allocate a new MachineMemOperand by copying an existing one, adjusting by an offset and using the given size.
MachineMemOperands are owned by the MachineFunction and need not be explicitly deallocated.
Definition at line 506 of file MachineFunction.cpp.
References llvm::commonAlignment(), llvm::MachineMemOperand::getAAInfo(), llvm::MachineMemOperand::getBaseAlign(), llvm::MachineMemOperand::getFailureOrdering(), llvm::MachineMemOperand::getFlags(), llvm::MachineMemOperand::getPointerInfo(), llvm::MachineMemOperand::getSuccessOrdering(), llvm::MachineMemOperand::getSyncScopeID(), llvm::MachinePointerInfo::getWithOffset(), llvm::PointerUnion< PTs >::isNull(), llvm::Offset, and llvm::MachinePointerInfo::V.
getMachineMemOperand() [5/8]
MachineMemOperand* llvm::MachineFunction::getMachineMemOperand (const MachineMemOperand * MMO, int64_t Offset, uint64_t Size) inline
Definition at line 995 of file MachineFunction.h.
References getMachineMemOperand(), llvm::Offset, and llvm::LLT::scalar().
getMachineMemOperand() [6/8]
MachineMemOperand * MachineFunction::getMachineMemOperand (const MachineMemOperand * MMO, MachineMemOperand::Flags Flags)
Allocate a new MachineMemOperand by copying an existing one, replacing the flags.
MachineMemOperands are owned by the MachineFunction and need not be explicitly deallocated.
Definition at line 538 of file MachineFunction.cpp.
References llvm::MachineMemOperand::getAAInfo(), llvm::MachineMemOperand::getBaseAlign(), llvm::MachineMemOperand::getFailureOrdering(), llvm::MachineMemOperand::getPointerInfo(), llvm::MachineMemOperand::getRanges(), llvm::MachineMemOperand::getSize(), llvm::MachineMemOperand::getSuccessOrdering(), and llvm::MachineMemOperand::getSyncScopeID().
getMachineMemOperand() [7/8]
MachineMemOperand * MachineFunction::getMachineMemOperand (MachinePointerInfo PtrInfo, MachineMemOperand::Flags f, LLT MemTy, Align base_alignment, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr, SyncScope::ID SSID = SyncScope::System, AtomicOrdering Ordering = AtomicOrdering::NotAtomic, AtomicOrdering FailureOrdering = AtomicOrdering::NotAtomic)
Definition at line 479 of file MachineFunction.cpp.
References f().
getMachineMemOperand() [8/8]
MachineMemOperand * MachineFunction::getMachineMemOperand (MachinePointerInfo PtrInfo, MachineMemOperand::Flags f, uint64_t s, Align base_alignment, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr, SyncScope::ID SSID = SyncScope::System, AtomicOrdering Ordering = AtomicOrdering::NotAtomic, AtomicOrdering FailureOrdering = AtomicOrdering::NotAtomic)
getMachineMemOperand - Allocate a new MachineMemOperand.
MachineMemOperands are owned by the MachineFunction and need not be explicitly deallocated.
Definition at line 469 of file MachineFunction.cpp.
References f(), and s.
Referenced by llvm::addFrameReference(), llvm::M68k::addFrameReference(), llvm::M68k::addMemOperand(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), llvm::CombinerHelper::applySextInRegOfLoad(), M68kOutgoingArgHandler::assignValueToAddress(), buildEpilogRestore(), llvm::X86TargetLowering::BuildFILD(), llvm::MachineIRBuilder::buildLoad(), llvm::MachineIRBuilder::buildLoadFromOffset(), buildPrologSpill(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::MachineIRBuilder::buildStore(), llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), llvm::CallLowering::ValueHandler::copyArgumentMemory(), llvm::FastISel::createMachineMemOperandFor(), emitBuildPairF64Pseudo(), llvm::AArch64SelectionDAGInfo::EmitMOPS(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::X86FrameLowering::emitPrologue(), emitSplitF64Pseudo(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), EmitUnrolledSetTag(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::HexagonInstrInfo::expandPostRAPseudo(), extractLoadMMOs(), extractStoreMMOs(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), getBROADCAST_LOAD(), getFrameIndexMMO(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLoadVP(), getMachineMemOperand(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MipsInstrInfo::GetMemOperand(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getStridedLoadVP(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getTruncStoreVP(), llvm::SelectionDAG::getTruncStridedStoreVP(), llvm::SystemZELFFrameLowering::inlineStackProbe(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeLoad(), llvm::AMDGPULegalizerInfo::legalizeSBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeTrapHsaQueuePtr(), llvm::LoongArchInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlotNoUpd(), llvm::LegalizerHelper::lowerFConstant(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::LegalizerHelper::lowerLoad(), lowerShuffleAsBroadcast(), llvm::LegalizerHelper::lowerStore(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerVECTOR_SHUFFLE(), llvm::CombinerHelper::matchLoadOrCombine(), narrowExtractedVectorLoad(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::LegalizerHelper::reduceLoadStoreWidth(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), and llvm::PPCInstrInfo::storeRegToStackSlotNoUpd().
getMMI()
MachineModuleInfo& llvm::MachineFunction::getMMI () const inline
Definition at line 623 of file MachineFunction.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::DwarfCFIException::beginFunction(), buildDefCFAReg(), llvm::M68kFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMovesFullCFA(), llvm::MachineInstr::emitError(), emitErrorMsg(), llvm::Mips16FrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::enableShrinkWrapping(), llvm::X86TargetLowering::expandIndirectJTBranch(), llvm::TargetLoweringObjectFileXCOFF::getEHInfoTableSymbol(), llvm::AArch64InstrInfo::getOutliningTypeImpl(), llvm::ARMBaseInstrInfo::getOutliningTypeImpl(), llvm::TailDuplicator::initMF(), llvm::PPCFrameLowering::inlineStackProbe(), needFuncLabels(), needsFrameMoves(), recoverFramePointer(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and transformCallee().
getName()
StringRef MachineFunction::getName () const
getName - Return the name of the corresponding LLVM function.
Definition at line 582 of file MachineFunction.cpp.
References getFunction(), and llvm::Value::getName().
Referenced by llvm::ARMBasicBlockUtils::adjustBBOffsetsAfter(), llvm::HexagonFrameLowering::assignCalleeSavedSpillSlots(), llvm::VirtRegAuxInfo::calculateSpillWeightsAndHints(), llvm::Combiner::combineMachineInstrs(), llvm::ARCFrameLowering::determineCalleeSaves(), llvm::ARCFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::ARCFrameLowering::emitEpilogue(), emitErrorMsg(), llvm::AsmPrinter::emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::X86AsmPrinter::emitKCFITypeId(), llvm::VEFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::AsmPrinter::emitStackUsage(), getBBClusterInfoForFunction(), llvm::MachineBasicBlock::getFullName(), llvm::DOTGraphTraits< DOTMachineFuncInfo * >::getGraphName(), llvm::TargetLoweringObjectFileELF::getSectionForMachineBasicBlock(), llvm::MachineBasicBlock::getSymbol(), llvm::GCNSchedStage::initGCNRegion(), INITIALIZE_PASS(), llvm::MIRParserImpl::initializeCallSiteInfo(), llvm::RISCVInstrInfo::insertOutlinedCall(), llvm::AArch64InstrInfo::insertOutlinedCall(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), llvm::X86InstrInfo::insertOutlinedCall(), llvm::VETargetLowering::LowerCustomJumpTableEntry(), LowerDYNAMIC_STACKALLOC(), llvm::MLPriorityAdvisor::MLPriorityAdvisor(), llvm::MachineCycleInfoWrapperPass::print(), llvm::MIRPrinter::print(), print(), llvm::ARCFrameLowering::processFunctionBeforeFrameFinalized(), reportFastISelFailure(), reportGISelDiagnostic(), llvm::PPCRegisterInfo::requiresFrameIndexScavenging(), llvm::ARCFrameLowering::restoreCalleeSavedRegisters(), llvm::ThunkInserter< Derived, InsertedThunksTy >::run(), llvm::ARMBlockPlacement::runOnMachineFunction(), llvm::InstructionSelect::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::Localizer::runOnMachineFunction(), llvm::LoadStoreOpt::runOnMachineFunction(), llvm::RAGreedy::runOnMachineFunction(), llvm::RegBankSelect::runOnMachineFunction(), llvm::VLIWMachineScheduler::schedule(), llvm::MIRParserImpl::setupRegisterInfo(), llvm::ARCFrameLowering::spillCalleeSavedRegisters(), viewCFG(), viewCFGOnly(), writeGadgetGraph(), and writeMCFGToDotFile().
getNewDebugInstrNum()
unsigned llvm::MachineFunction::getNewDebugInstrNum () inline
Definition at line 1269 of file MachineFunction.h.
Referenced by llvm::MachineInstr::getDebugInstrNum().
getNumBlockIDs()
unsigned llvm::MachineFunction::getNumBlockIDs () const inline
getNumBlockIDs - Return the number of MBB ID's allocated.
Definition at line 815 of file MachineFunction.h.
Referenced by llvm::ARMBasicBlockUtils::adjustBBOffsetsAfter(), llvm::ARMBasicBlockUtils::computeAllBlockSizes(), llvm::HexagonFrameLowering::emitPrologue(), llvm::ReachingDefAnalysis::init(), llvm::LiveRangeCalc::isJointlyDominated(), maybeUpdateTerminator(), llvm::LiveRangeCalc::resetLiveOutMap(), llvm::CFIFixup::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::sortBasicBlocksAndUpdateBranches(), sortBlocks(), llvm::LoopTraversal::traverse(), and llvm::MachineTraceMetrics::verifyAnalysis().
getObserver()
GISelChangeObserver* llvm::MachineFunction::getObserver () const inline
Definition at line 621 of file MachineFunction.h.
Referenced by llvm::constrainOperandRegClass().
getOrCreateJumpTableInfo()
MachineJumpTableInfo * MachineFunction::getOrCreateJumpTableInfo (unsigned EntryKind)
getOrCreateJumpTableInfo - Get the JumpTableInfo for this function, if it does already exist, allocate one.
Get the JumpTableInfo for this function.
If it does not already exist, allocate one.
Definition at line 299 of file MachineFunction.cpp.
Referenced by llvm::SwitchCG::SwitchLowering::buildJumpTable(), and llvm::MIRParserImpl::initializeJumpTableInfo().
getOrCreateLandingPadInfo()
LandingPadInfo & MachineFunction::getOrCreateLandingPadInfo (MachineBasicBlock * LandingPad)
Find or create an LandingPadInfo for the specified MachineBasicBlock.
Definition at line 744 of file MachineFunction.cpp.
References i, llvm::LandingPadInfo::LandingPadBlock, and N.
Referenced by addInvoke(), and addLandingPad().
getPICBaseSymbol()
MCSymbol * MachineFunction::getPICBaseSymbol () const
getPICBaseSymbol - Return a function-local symbol to represent the PIC base.
Return a function-local symbol to represent the PIC base.
Definition at line 734 of file MachineFunction.cpp.
References DL, getDataLayout(), getFunctionNumber(), and llvm::MCContext::getOrCreateSymbol().
Referenced by llvm::X86AsmPrinter::emitInstruction(), llvm::X86TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::PPCTargetLowering::getPICJumpTableRelocBaseExpr(), and GetSymbolRef().
getProperties() [1/2]
MachineFunctionProperties& llvm::MachineFunction::getProperties () inline
Definition at line 764 of file MachineFunction.h.
getProperties() [2/2]
const MachineFunctionProperties& llvm::MachineFunction::getProperties () const inline
Get the function properties.
Definition at line 763 of file MachineFunction.h.
Referenced by llvm::Combiner::combineMachineInstrs(), createFrameHelperMachineFunction(), createPHIsForSelects(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::MachineRegisterInfo::invalidateLiveness(), llvm::MachineRegisterInfo::isSSA(), llvm::MachineRegisterInfo::leaveSSA(), llvm::MachineBasicBlock::liveout_begin(), llvm::MIRPrinter::print(), print(), llvm::reportGISelFailure(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::Localizer::runOnMachineFunction(), llvm::LoadStoreOpt::runOnMachineFunction(), llvm::RegBankSelect::runOnMachineFunction(), llvm::scavengeFrameVirtualRegs(), and llvm::MachineRegisterInfo::tracksLiveness().
getPSVManager()
PseudoSourceValueManager& llvm::MachineFunction::getPSVManager () const inline
Definition at line 632 of file MachineFunction.h.
Referenced by llvm::MipsFunctionInfo::callPtrInfo(), llvm::MachinePointerInfo::getConstantPool(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachinePointerInfo::getGOT(), llvm::MachinePointerInfo::getJumpTable(), and llvm::MachinePointerInfo::getStack().
getRegInfo() [1/2]
MachineRegisterInfo& llvm::MachineFunction::getRegInfo () inline
getRegInfo - Return information about the registers currently in use.
Definition at line 682 of file MachineFunction.h.
Referenced by addCalleeSavedRegs(), addConstantsToTrack(), addImplicitDefs(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::MachineBasicBlock::addLiveIn(), addLiveIn(), addLiveIn(), llvm::addLiveIns(), AdjustBaseAndOffset(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::RISCVRegisterInfo::adjustReg(), allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), allocateVGPR32Input(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::ARMBaseInstrInfo::analyzeLoopForPipelining(), llvm::PPCInstrInfo::analyzeLoopForPipelining(), llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::AMDGPUCallLowering::areCalleeOutgoingArgsTailCallable(), llvm::PPCFrameLowering::assignCalleeSavedSpillSlots(), llvm::VirtRegMap::assignVirt2StackSlot(), attemptDebugCopyProp(), buildGitPtr(), buildScratchExecCopy(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::VirtRegAuxInfo::calculateSpillWeightsAndHints(), canCombine(), canCombineFPFusedMultiply(), canCompareBeNewValueJump(), llvm::AArch64InstrInfo::canInsertSelect(), llvm::SystemZInstrInfo::canInsertSelect(), llvm::SIInstrInfo::canInsertSelect(), llvm::X86InstrInfo::canInsertSelect(), llvm::PPCInstrInfo::canInsertSelect(), llvm::MipsRegisterInfo::canRealignStack(), llvm::M68kRegisterInfo::canRealignStack(), llvm::X86RegisterInfo::canRealignStack(), llvm::ARMBaseRegisterInfo::canRealignStack(), canRenameUpToDef(), llvm::checkVOPDRegConstraints(), llvm::X86InstrInfo::classifyLEAReg(), combineFPFusedMultiply(), llvm::Combiner::combineMachineInstrs(), llvm::HexagonBlockRanges::computeDeadMap(), llvm::computeLiveIns(), computeLiveOuts(), llvm::constrainSelectedInstRegOperands(), llvm::SIInstrInfo::convertNonUniformIfRegion(), llvm::SIInstrInfo::convertNonUniformLoopRegion(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::WebAssemblyInstrInfo::copyPhysReg(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::AllocationOrder::create(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), createFrameHelperMachineFunction(), createLaneMaskReg(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), createPostIncLoadStore(), createTypeVReg(), llvm::HexagonInstrInfo::createVR(), llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::CSKYFrameLowering::determineCalleeSaves(), llvm::XCoreFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::HexagonFrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::VETargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::SIFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), emitFrameOffsetAdj(), emitFROUND(), emitIndirectDst(), emitIndirectSrc(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::AVRFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), emitReadCycleWidePseudo(), llvm::VETargetLowering::emitSjLjDispatchBlock(), emitThumbRegPlusImmInReg(), emitXBegin(), llvm::InstructionSelector::executeMatchTable(), llvm::SIInstrInfo::expandMovDPP64(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), extractRsrcPtr(), llvm::PPCInstrInfo::finalizeInsInstrs(), llvm::SITargetLowering::finalizeLowering(), llvm::TargetLoweringBase::finalizeLowering(), llvm::findPHICopyInsertPoint(), findScratchNonCalleeSaveRegister(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), foldConstantsIntoIntrinsics(), llvm::PPCInstrInfo::foldFrameOffset(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::SIInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), forceReg(), llvm::GCNHazardRecognizer::GCNHazardRecognizer(), llvm::RISCVInstrInfo::genAlternativeCodeSequence(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), generateAssignInstrs(), genIndexedMultiply(), llvm::SIInstrInfo::getAddNoCarry(), llvm::TargetRegisterInfo::getAllocatableSet(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::FunctionLoweringInfo::getCatchPadExceptionPointerVReg(), llvm::PPCInstrInfo::getConstantFromConstantPool(), llvm::AMDGPURegisterBankInfo::getDefaultMappingAllVGPR(), llvm::AMDGPURegisterBankInfo::getDefaultMappingSOP(), llvm::AMDGPURegisterBankInfo::getDefaultMappingVOP(), llvm::PPCInstrInfo::getFMAPatterns(), getFMULPatterns(), getFoldableImm(), llvm::getFunctionLiveInPhysReg(), llvm::MipsFunctionInfo::getGlobalBaseReg(), llvm::CSKYInstrInfo::getGlobalBaseReg(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::M68kInstrInfo::getGlobalBaseReg(), llvm::X86InstrInfo::getGlobalBaseReg(), llvm::R600InstrInfo::getIndirectIndexBegin(), GetInitialOffset(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::PPCRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMappingForLoad(), llvm::RegisterBankInfo::getInstrMappingImpl(), llvm::ReachingDefAnalysis::getLiveOuts(), llvm::ReachingDefAnalysis::getLocalLiveOutMIDef(), LiveDebugValues::MLocTracker::getLocSizeInBits(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeByOpcode(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVArrayType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getOrCreateUndef(), llvm::SwiftErrorValueTracking::getOrCreateVReg(), llvm::SwiftErrorValueTracking::getOrCreateVRegDefAt(), llvm::AArch64InstrInfo::getOutlinableRanges(), llvm::MachineFrameInfo::getPristineRegs(), getPrologueDeath(), llvm::RISCVRegisterInfo::getRegAllocationHints(), llvm::PPCRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::SIInstrInfo::getRegClass(), getRegClass(), getRegistersForValue(), getRegTy(), getVGPRSpillLaneOrTempRegister(), llvm::RISCVInstrInfo::getVLENFactoredAmount(), llvm::PerFunctionMIParsingState::getVRegInfo(), llvm::PerFunctionMIParsingState::getVRegInfoNamed(), llvm::VirtRegMap::grow(), llvm::CallLowering::handleAssignments(), llvm::TargetInstrInfo::hasReassociableOperands(), llvm::RISCVInstrInfo::hasReassociableSibling(), llvm::TargetInstrInfo::hasReassociableSibling(), llvm::SIInstrInfo::hasVGPRUses(), indirectCopyToAGPR(), llvm::RegPressureTracker::init(), llvm::RegBankSelect::init(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::TailDuplicator::initMF(), llvm::VEInstrInfo::insertBranch(), insertCSRSaves(), llvm::SIInstrInfo::insertEQ(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertNE(), llvm::AArch64InstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::SIInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), llvm::SIInstrInfo::insertVectorSelect(), isACalleeSavedRegister(), llvm::SIRegisterInfo::isAsmClobberable(), isCallerPreservedOrConstPhysReg(), llvm::SITargetLowering::isCanonicalized(), llvm::isCycleInvariant(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::MachineLoop::isLoopInvariant(), isLUIADDI(), llvm::ARMBaseInstrInfo::isMBBSafeToOutlineFrom(), isNonFoldablePartialRegisterLoad(), llvm::SIInstrInfo::isOperandLegal(), llvm::ReachingDefAnalysis::isReachingDefLiveOut(), llvm::X86InstrInfo::isReallyTriviallyReMaterializable(), llvm::ReachingDefAnalysis::isRegUsedAfter(), llvm::AMDGPURegisterBankInfo::isSALUMapping(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), isSignExtendedW(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isSSA(), llvm::SIInstrInfo::isVGPRCopy(), IsWritingToVCCR(), isXPLeafCandidate(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::Legalizer::legalizeMachineFunction(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), loadM0FromVGPR(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::X86InstrInfo::loadStoreTileReg(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::AMDGPUCallLowering::lowerCall(), llvm::CallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResults(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::PPCCallLowering::lowerFormalArguments(), llvm::X86CallLowering::lowerFormalArguments(), llvm::ARMCallLowering::lowerFormalArguments(), llvm::M68kCallLowering::lowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::MipsCallLowering::lowerReturn(), llvm::PPCCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::M68kCallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerTailCall(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), llvm::PPCRegisterInfo::lowerWACCRestore(), llvm::PPCRegisterInfo::lowerWACCSpilling(), llvm::machineFunctionIsIllegal(), llvm::CombinerHelper::matchCombineConstPtrAddToI2P(), llvm::RISCVRegisterInfo::materializeFrameBaseRegister(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::SIRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::SIInstrInfo::materializeImmediate(), llvm::PPCInstrInfo::materializeImmPostRA(), llvm::SIInstrInfo::moveFlatAddrToVGPR(), llvm::SIInstrInfo::moveToVALU(), llvm::CSKYInstrInfo::movImm(), MustSaveLR(), llvm::RISCVRegisterInfo::needsFrameBaseReg(), needToReserveScavengingSpillSlots(), llvm::PPCInstrInfo::optimizeCmpPostRA(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::BranchFolder::OptimizeFunction(), llvm::MIRParserImpl::parseRegisterInfo(), llvm::AMDGPUCallLowering::passSpecialInputs(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::VETargetLowering::prepareMBB(), llvm::VETargetLowering::prepareSymbol(), llvm::MIRPrinter::print(), llvm::MIPrinter::print(), llvm::MachineBasicBlock::print(), PrintNodeInfo(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZELFFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameIndicesReplaced(), processInstrsWithTypeFolding(), processSwitches(), propagateLocalCopies(), llvm::SwiftErrorValueTracking::propagateVRegs(), pushRegsToStack(), llvm::TargetInstrInfo::reassociateOps(), llvm::recomputeLivenessFlags(), rescheduleCanonically(), reservePrivateMemoryRegs(), llvm::GCNRPTracker::reset(), llvm::LiveRangeCalc::reset(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::restoreStatusRegister(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteT2FrameIndex(), llvm::InstructionSelect::runOnMachineFunction(), llvm::WebAssemblyAsmPrinter::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::scavengeFrameVirtualRegs(), llvm::FunctionLoweringInfo::set(), llvm::GenericSSAContext< MachineFunction >::setFunction(), llvm::GISelCSEInfo::setMF(), llvm::MachineIRBuilder::setMF(), llvm::X86MachineFunctionInfo::setRestoreBasePointer(), llvm::AMDGPUInstructionSelector::setupMF(), llvm::MIRParserImpl::setupRegisterInfo(), shouldPreventUndefRegUpdateMemFold(), llvm::PPCInstrInfo::shouldReduceRegisterPressure(), llvm::TargetRegisterInfo::shouldRegionSplitForVirtReg(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::M68kFrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), spillVGPRtoAGPR(), llvm::MachineBasicBlock::SplitCriticalEdge(), splitMBB(), llvm::SIMachineFunctionInfo::splitWWMSpillRegisters(), llvm::stableHashValue(), llvm::CriticalAntiDepBreaker::StartBlock(), llvm::AggressiveAntiDepBreaker::StartBlock(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::tryFoldSPUpdateIntoPushPop(), tryToFindRegisterToRename(), unpack64(), unpackF64OnRV32DSoftABI(), unpackFromRegLoc(), unstackifyVRegsUsedInSplitBB(), llvm::AArch64RegisterInfo::UpdateCustomCalleeSavedRegs(), UpdateOperandRegClass(), updateOperandRegConstraints(), llvm::ARMBaseRegisterInfo::updateRegAllocHint(), llvm::SIMachineFunctionInfo::usesAGPRs(), llvm::RegisterBankInfo::InstructionMapping::verify(), and llvm::SIInstrInfo::verifyInstruction().
getRegInfo() [2/2]
const MachineRegisterInfo& llvm::MachineFunction::getRegInfo () const inline
Definition at line 683 of file MachineFunction.h.
getSection()
MCSection* llvm::MachineFunction::getSection () const inline
Returns the Section this function belongs to.
Definition at line 627 of file MachineFunction.h.
Referenced by llvm::AsmPrinter::emitBBAddrMapSection(), llvm::AsmPrinter::emitFunctionBody(), llvm::AsmPrinter::emitKCFITrapEntry(), llvm::AsmPrinter::emitPCSections(), and llvm::TargetLoweringObjectFileELF::getSectionForMachineBasicBlock().
getSublistAccess()
static BasicBlockListType MachineFunction::* llvm::MachineFunction::getSublistAccess (MachineBasicBlock *) inline static
Support for MachineBasicBlock::getNextNode().
Definition at line 859 of file MachineFunction.h.
getSubtarget() [1/2]
const TargetSubtargetInfo& llvm::MachineFunction::getSubtarget () const inline
getSubtarget - Return the subtarget for which this machine code is being compiled.
Definition at line 672 of file MachineFunction.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfCompileUnit::addComplexAddress(), addImplicitDefs(), llvm::MachineBasicBlock::addLiveIn(), addLiveInRegs(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::ScheduleDAGInstrs::addPhysRegDeps(), addSavedGPR(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::RISCVRegisterInfo::adjustReg(), allocateRegMask(), llvm::SIFrameLowering::allocateScavengingFrameIndexesNearIncomingSP(), llvm::TargetFrameLowering::allocateScavengingFrameIndexesNearIncomingSP(), llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPRLane(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::ARMBaseInstrInfo::analyzeBranch(), analyzeCompressibleUses(), llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::A57ChainingConstraint::apply(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::AMDGPURegisterBankInfo::applyMappingDynStackAlloc(), llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::AMDGPUCallLowering::areCalleeOutgoingArgsTailCallable(), llvm::ARMBasicBlockUtils::ARMBasicBlockUtils(), llvm::SIFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZXPLINKFrameLowering::assignCalleeSavedSpillSlots(), attemptDebugCopyProp(), llvm::DebugHandlerBase::beginFunction(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::DwarfDebug::beginInstruction(), buildAnyextOrCopy(), llvm::MachineIRBuilder::buildBoolExtInReg(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::ScheduleDAGInstrs::buildSchedGraph(), buildScratchExecCopy(), llvm::calculateDbgEntityHistory(), llvm::calculateRegAllocScore(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::LoongArchTargetLowering::CanLowerReturn(), llvm::HexagonTargetLowering::CanLowerReturn(), llvm::RISCVTargetLowering::CanLowerReturn(), cannotCoexistAsymm(), llvm::HexagonPacketizerList::canPromoteToDotCur(), llvm::MipsRegisterInfo::canRealignStack(), llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::MachineBasicBlock::canSplitCriticalEdge(), llvm::AArch64FrameLowering::canUseAsPrologue(), llvm::X86FrameLowering::canUseAsPrologue(), llvm::AArch64FrameLowering::canUseRedZone(), CC_AArch64_Custom_Block(), CC_AIX(), CC_ARM_AAPCS_Custom_Aggregate(), CC_MipsO32(), llvm::CC_SystemZ_I128Indirect(), CC_X86_64_VectorCall(), CC_X86_Intr(), CC_X86_VectorCallAssignRegister(), checkNumAlignedDPRCS2Regs(), llvm::checkVOPDRegConstraints(), combineFPFusedMultiply(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), computeLiveOuts(), llvm::MachineFrameInfo::computeMaxCallFrameSize(), llvm::TargetSchedModel::computeOutputLatency(), llvm::MIRPrinter::convertCallSiteObjects(), llvm::GCNTargetMachine::convertFuncInfoToYAML(), llvm::MIRPrinter::convertStackObjects(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::createBURRListDAGScheduler(), llvm::createDefaultScheduler(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::ARM::createFastISel(), llvm::PPC::createFastISel(), llvm::XCoreFunctionInfo::createFPSpillSlot(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::MipsFunctionInfo::createISRRegFI(), createLaneMaskReg(), llvm::createLibcall(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::createMemLibcall(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::createSourceListDAGScheduler(), llvm::SelectionDAG::CreateStackTemporary(), llvm::PPCInstrInfo::CreateTargetPostRAHazardRecognizer(), createTuple(), llvm::MipsInstrInfo::describeLoadedValue(), llvm::AArch64InstrInfo::describeLoadedValue(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::SIFrameLowering::determineCalleeSaves(), llvm::MipsSEFrameLowering::determineCalleeSaves(), llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::CSKYFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::SystemZELFFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::HexagonFrameLowering::determineCalleeSaves(), llvm::SystemZXPLINKFrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::SIFrameLowering::determineCalleeSavesSGPR(), llvm::SystemZXPLINKFrameLowering::determineFrameLayout(), llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), llvm::TargetOptions::DisableFramePointerElim(), llvm::AMDGPUCallLowering::doCallerAndCalleePassArgsTheSameWay(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::WebAssemblyFrameLowering::eliminateCallFramePseudoInstr(), llvm::AVRFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::ARCFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::VERegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), emitBuildPairF64Pseudo(), emitCalleeSavedRestores(), emitComments(), llvm::SIFrameLowering::emitCSRSpillRestores(), llvm::SIFrameLowering::emitCSRSpillStores(), llvm::DwarfDebug::emitDebugLocValue(), emitDebugValueComment(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::SIFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARCFrameLowering::emitEpilogue(), llvm::WebAssemblyFrameLowering::emitEpilogue(), llvm::SystemZELFFrameLowering::emitEpilogue(), llvm::SystemZXPLINKFrameLowering::emitEpilogue(), llvm::MipsAsmPrinter::emitFrameDirective(), emitFrameOffsetAdj(), llvm::AsmPrinter::emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::emitFunctionBodyStart(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitHiddenKernelArgs(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), llvm::AsmPrinter::emitImplicitDef(), llvm::R600AsmPrinter::emitInstruction(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::SystemZAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::AsmPrinter::emitJumpTableInfo(), llvm::AMDGPU::HSAMD::MetadataStreamerYamlV2::emitKernel(), emitKill(), llvm::ThumbRegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitLoadM0FromVGPRLoop(), emitLoadSRsrcFromVGPRLoop(), llvm::PPCDispatchGroupSBHazardRecognizer::EmitNoop(), llvm::AsmPrinter::emitNops(), llvm::AVRFrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::ARCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), emitPrologueEpilogueSPUpdate(), emitReadCycleWidePseudo(), emitSCSEpilogue(), emitSCSPrologue(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), emitSplitF64Pseudo(), llvm::X86FrameLowering::emitSPUpdate(), llvm::X86FrameLowering::emitStackProbe(), EmitTailCallStoreFPAndRetAddr(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemmove(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::WebAssemblySelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), emitThumbRegPlusImmInReg(), llvm::AsmPrinter::emitXRayTable(), enableAllocFrameElim(), llvm::HexagonFrameLowering::enableCalleeSaveSkip(), llvm::PPCFrameLowering::enableShrinkWrapping(), estimateRSStackSizeLimit(), llvm::MachineFrameInfo::estimateStackSize(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::VEInstrInfo::expandGetStackTopPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), expandXorFP(), llvm::AArch64RegisterInfo::explainReservedReg(), llvm::AArch64CallLowering::fallBackToDAGISel(), llvm::finalizeBundle(), finalizeDebugInstrRefs(), llvm::SITargetLowering::finalizeLowering(), findScratchNonCalleeSaveRegister(), finishStackBlock(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), generateEndPgm(), genIndexedMultiply(), llvm::AMDGPUSubtarget::get(), llvm::PPCRegisterInfo::getBaseRegister(), getBBAddrMapMetadata(), llvm::getBLRCallOpcode(), llvm::getBLXOpcode(), llvm::getBLXpredOpcode(), llvm::MachineIRBuilder::getBoolExtOp(), llvm::LoongArchRegisterInfo::getCalleeSavedRegs(), llvm::RISCVRegisterInfo::getCalleeSavedRegs(), llvm::AVRRegisterInfo::getCalleeSavedRegs(), llvm::CSKYRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::SystemZXPLINK64Registers::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::SystemZELFRegisters::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::SystemZRegisterInfo::getCalleeSavedRegs(), llvm::TargetFrameLowering::getCalleeSaves(), llvm::RISCVRegisterInfo::getCallPreservedMask(), llvm::CSKYRegisterInfo::getCallPreservedMask(), llvm::LoongArchRegisterInfo::getCallPreservedMask(), llvm::AVRRegisterInfo::getCallPreservedMask(), llvm::AArch64RegisterInfo::getCallPreservedMask(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::SystemZXPLINK64Registers::getCallPreservedMask(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::SystemZELFRegisters::getCallPreservedMask(), llvm::ARMBaseRegisterInfo::getCallPreservedMask(), llvm::SystemZRegisterInfo::getCallPreservedMask(), llvm::AArch64RegisterInfo::getCustomEHPadPreservedMask(), llvm::AArch64RegisterInfo::getDarwinCalleeSavedRegs(), llvm::AArch64RegisterInfo::getDarwinCallPreservedMask(), llvm::TargetFrameLowering::getDwarfFrameBase(), llvm::getEHScopeMembership(), llvm::MachineBasicBlock::getFallThrough(), getFPOffset(), llvm::WebAssemblyFrameLowering::getFPReg(), llvm::R600FrameLowering::getFrameIndexReference(), llvm::SIFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::CSKYFrameLowering::getFrameIndexReference(), llvm::SparcFrameLowering::getFrameIndexReference(), llvm::LoongArchFrameLowering::getFrameIndexReference(), llvm::HexagonFrameLowering::getFrameIndexReference(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::AArch64FrameLowering::getFrameIndexReferencePreferSP(), llvm::AVRRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::M68kRegisterInfo::getFrameRegister(), llvm::SystemZRegisterInfo::getFrameRegister(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::SIMachineFunctionInfo::getGITPtrLoReg(), getGlobalBaseRegClass(), llvm::ARMHazardRecognizerFPMLx::getHazardType(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::getHSAKernelProps(), llvm::R600InstrInfo::getIndirectIndexEnd(), GetInitialOffset(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::PPCRegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::RegisterBankInfo::getInstrMappingImpl(), llvm::MSP430InstrInfo::getInstSizeInBytes(), llvm::AVRInstrInfo::getInstSizeInBytes(), llvm::ThumbRegisterInfo::getLargestLegalSuperClass(), llvm::AVRRegisterInfo::getLargestLegalSuperClass(), llvm::X86RegisterInfo::getLargestLegalSuperClass(), llvm::PPCRegisterInfo::getLargestLegalSuperClass(), llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass(), getLoadStoreOffsetSizeInBits(), llvm::WebAssemblyFrameLowering::getLocalForStackObject(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::MipsFunctionInfo::getMoveF64ViaSpillFI(), getMSAMapping(), llvm::WebAssemblyFrameLowering::getOpcAdd(), llvm::WebAssemblyFrameLowering::getOpcAnd(), llvm::WebAssemblyFrameLowering::getOpcConst(), llvm::WebAssemblyFrameLowering::getOpcGlobGet(), llvm::WebAssemblyFrameLowering::getOpcGlobSet(), llvm::WebAssemblyFrameLowering::getOpcSub(), llvm::SPIRVGlobalRegistry::getOrCreateConstInt(), getOrCreateFrameHelper(), llvm::SPIRVGlobalRegistry::getOrCreateUndef(), llvm::RISCVInstrInfo::getOutliningTypeImpl(), llvm::HexagonEvaluator::getPhysRegBitWidth(), llvm::SparcRegisterInfo::getPointerRegClass(), llvm::ThumbRegisterInfo::getPointerRegClass(), llvm::WebAssemblyRegisterInfo::getPointerRegClass(), llvm::MipsRegisterInfo::getPointerRegClass(), llvm::X86RegisterInfo::getPointerRegClass(), llvm::MachineFrameInfo::getPristineRegs(), llvm::X86RegisterInfo::getPtrSizedFrameRegister(), llvm::X86RegisterInfo::getPtrSizedStackRegister(), llvm::SelectionDAG::getReducedAlign(), llvm::PPCRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::SystemZTargetLowering::getRegisterByName(), llvm::RISCVRegisterInfo::getRegisterCostTableIndex(), getRegistersForValue(), llvm::MipsRegisterInfo::getRegPressureLimit(), llvm::PPCRegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::ARMBaseRegisterInfo::getRegPressureLimit(), llvm::SystemZELFFrameLowering::getRegSpillOffset(), getRegTy(), llvm::R600RegisterInfo::getReservedRegs(), llvm::SparcRegisterInfo::getReservedRegs(), llvm::RISCVRegisterInfo::getReservedRegs(), llvm::CSKYRegisterInfo::getReservedRegs(), llvm::AVRRegisterInfo::getReservedRegs(), llvm::LoongArchRegisterInfo::getReservedRegs(), llvm::HexagonRegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::M68kRegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::SystemZRegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::getReservedRegs(), getScavSlotsNumForRVV(), getSchedRegions(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::AArch64FrameLowering::getSEHFrameIndexOffset(), llvm::ARMBaseRegisterInfo::getSjLjDispatchPreservedMask(), llvm::X86InstrInfo::getSPAdjust(), llvm::TargetInstrInfo::getSPAdjust(), llvm::WebAssemblyFrameLowering::getSPReg(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::AArch64RegisterInfo::getStrictlyReservedRegs(), llvm::SelectionDAG::getSubtarget(), llvm::AsmPrinter::getSubtargetInfo(), GetSymbolRef(), getTargetIndexName(), llvm::CombinerHelper::getTargetLowering(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::gettBLXrOpcode(), llvm::AArch64RegisterInfo::getThisReturnPreservedMask(), llvm::ARMBaseRegisterInfo::getThisReturnPreservedMask(), llvm::ARMBaseRegisterInfo::getTLSCallPreservedMask(), getVGPRSpillLaneOrTempRegister(), llvm::CCState::HandleByVal(), llvm::X86FrameLowering::has128ByteRedZone(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::SparcFrameLowering::hasFP(), llvm::VEFrameLowering::hasFP(), llvm::RISCVFrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::LoongArchFrameLowering::hasFP(), llvm::ARCFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::CSKYFrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::HexagonFrameLowering::hasFP(), hasRVVFrameObject(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::RegPressureTracker::init(), llvm::RegBankSelect::init(), llvm::PreRARematStage::initGCNSchedStage(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::R600SchedStrategy::initialize(), llvm::GCNSchedStrategy::initialize(), llvm::ConvergingVLIWScheduler::initialize(), llvm::GenericScheduler::initialize(), llvm::PostGenericScheduler::initialize(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::TailDuplicator::initMF(), llvm::SystemZELFFrameLowering::inlineStackProbe(), llvm::SystemZXPLINKFrameLowering::inlineStackProbe(), insertCSRRestores(), insertCSRSaves(), insertDivByZeroTrap(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), InsertReturnAddressAuth(), insertSEH(), InsertSEH(), insertUndefLaneMask(), interpretValues(), llvm::X86RegisterInfo::isArgumentRegister(), llvm::AArch64RegisterInfo::isArgumentRegister(), llvm::RISCVRegisterInfo::isAsmClobberable(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), llvm::isCycleInvariant(), llvm::AMDGPUCallLowering::isEligibleForTailCallOptimization(), llvm::X86RegisterInfo::isFixedRegister(), llvm::ARMFrameLowering::isFPReserved(), llvm::ARMBaseRegisterInfo::isInlineAsmReadOnlyReg(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), llvm::MachineLoop::isLoopInvariant(), isNonFoldablePartialRegisterLoad(), llvm::ARMBaseInstrInfo::isPredicable(), isRegOtherThanSPAndFP(), llvm::TargetInstrInfo::isSchedulingBoundary(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isTargetWindows(), isXPLeafCandidate(), llvm::ARMFrameLowering::keepFramePointer(), llvm::SIMachineFunctionInfo::limitOccupancy(), llvm::MachineBasicBlock::liveout_begin(), loadM0FromVGPR(), llvm::PPCRegisterInfo::lowerACCRestore(), llvm::PPCRegisterInfo::lowerACCSpilling(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::AMDGPUCallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), LowerCallResults(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::SITargetLowering::lowerDYNAMIC_STACKALLOCImpl(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerDynamicAreaOffset(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::PPCRegisterInfo::lowerOctWordSpilling(), llvm::AMDGPUAsmPrinter::lowerOperand(), llvm::PPCRegisterInfo::lowerPrepareProbedAlloca(), llvm::PPCRegisterInfo::lowerQuadwordRestore(), llvm::PPCRegisterInfo::lowerQuadwordSpilling(), llvm::X86CallLowering::lowerReturn(), llvm::SPIRVCallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), lowerRISCVVMachineInstrToMCInst(), llvm::AMDGPUCallLowering::lowerTailCall(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::RISCVRegisterInfo::lowerVSPILL(), llvm::PPCRegisterInfo::lowerWACCRestore(), llvm::PPCRegisterInfo::lowerWACCSpilling(), llvm::machineFunctionIsIllegal(), matchFoldGlobalOffset(), llvm::CombinerHelper::matchNotCmp(), AMDGPUPostLegalizerCombinerHelper::matchRemoveFcanonicalize(), llvm::RISCVRegisterInfo::materializeFrameBaseRegister(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::MachineInstr::mayAlias(), needScavSlotForCFR(), needsShadowCallStackPrologueEpilogue(), llvm::SystemZELFFrameLowering::orderFrameObjects(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::AMDGPUCallLowering::passSpecialInputs(), llvm::PPCDispatchGroupSBHazardRecognizer::PreEmitNoops(), llvm::SystemZInstrInfo::prepareCompareSwapOperands(), llvm::PPCRegisterInfo::prepareDynamicAlloca(), llvm::MIRPrinter::print(), llvm::MIPrinter::print(), llvm::MachineFrameInfo::print(), print(), llvm::MachineBasicBlock::print(), llvm::MachineInstr::print(), llvm::AVRAsmPrinter::PrintAsmOperand(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::AMDGPUAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::GCNIterativeScheduler::printRegions(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::GCNIterativeScheduler::printSchedRP(), llvm::MachineOperand::printTargetFlags(), llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::ARCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZXPLINKFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameIndicesReplaced(), produceCompactUnwindFrame(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::TargetInstrInfo::reassociateOps(), llvm::MachineRegisterInfo::recomputeRegClass(), reduceDbgValsForwardScan(), replaceDominatedUses(), replaceFI(), replaceFrameIndex(), requiresAAPCSFrameRecord(), llvm::PPCRegisterInfo::requiresFrameIndexScavenging(), llvm::PPCRegisterInfo::requiresVirtualBaseRegisters(), llvm::R600InstrInfo::reserveIndirectRegisters(), reservePrivateMemoryRegs(), llvm::AArch64FrameLowering::resetCFIToInitialState(), llvm::MipsTargetMachine::resetSubtarget(), llvm::ThumbRegisterInfo::resolveFrameIndex(), llvm::AArch64RegisterInfo::resolveFrameIndex(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::AVRFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::XCoreFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::CSKYFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), restoreCRs(), llvm::restoreStatusRegister(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::CFIFixup::runOnMachineFunction(), llvm::LoongArchDAGToDAGISel::runOnMachineFunction(), llvm::RISCVDAGToDAGISel::runOnMachineFunction(), llvm::HexagonAsmPrinter::runOnMachineFunction(), llvm::MipsDAGToDAGISel::runOnMachineFunction(), llvm::ARMBlockPlacement::runOnMachineFunction(), llvm::HexagonDAGToDAGISel::runOnMachineFunction(), llvm::InsertNOPLoad::runOnMachineFunction(), llvm::NVPTXDAGToDAGISel::runOnMachineFunction(), llvm::InstructionSelect::runOnMachineFunction(), llvm::WebAssemblyAsmPrinter::runOnMachineFunction(), llvm::CSKYAsmPrinter::runOnMachineFunction(), llvm::DetectRoundChange::runOnMachineFunction(), llvm::BreakFalseDeps::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::FixAllFDIVSQRT::runOnMachineFunction(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::LiveStacks::runOnMachineFunction(), AMDGPUDAGToDAGISel::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::ReachingDefAnalysis::runOnMachineFunction(), llvm::MipsAsmPrinter::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::Mips16RegisterInfo::saveScavengerRegister(), llvm::ScheduleDAGInstrs::ScheduleDAGInstrs(), llvm::GCNIterativeScheduler::scheduleILP(), llvm::GCNIterativeScheduler::scheduleLegacyMaxOccupancy(), llvm::GCNIterativeScheduler::scheduleMinReg(), llvm::GCNIterativeScheduler::scheduleRegion(), llvm::HexagonConvergingVLIWScheduler::SchedulingCost(), selectI64Imm(), llvm::FunctionLoweringInfo::set(), setAliasRegs(), setCallTargetReg(), llvm::SwiftErrorValueTracking::setFunction(), llvm::MachineIRBuilder::setMF(), llvm::X86MachineFunctionInfo::setRestoreBasePointer(), llvm::AMDGPUInstructionSelector::setupMF(), llvm::MIRParserImpl::setupRegisterInfo(), llvm::HexagonRegisterInfo::shouldCoalesce(), llvm::TargetRegisterInfo::shouldRealignStack(), llvm::TargetRegisterInfo::shouldRegionSplitForVirtReg(), shouldUseFrameHelper(), signOutlinedFunction(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), llvm::MachineBasicBlock::SkipPHIsLabelsAndDebug(), llvm::GCNIterativeScheduler::sortRegionsByPressure(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::LoongArchFrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::RISCVFrameLowering::spillCalleeSavedRegisters(), llvm::CSKYFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::MachineBasicBlock::splitAt(), llvm::MachineBasicBlock::SplitCriticalEdge(), splitMBB(), TransferTracker::TransferTracker(), llvm::AArch64GISelUtils::tryEmitBZero(), llvm::GCNIterativeScheduler::tryMaximizeOccupancy(), llvm::X86InstrInfo::unfoldMemoryOperand(), unstackifyVRegsUsedInSplitBB(), llvm::AArch64RegisterInfo::UpdateCustomCalleeSavedRegs(), llvm::AArch64RegisterInfo::UpdateCustomCallPreservedMask(), updateLiveIn(), UpdateOperandRegClass(), llvm::DwarfCompileUnit::updateSubprogramScopeDIEImpl(), llvm::MachineBasicBlock::updateTerminator(), llvm::HexagonRegisterInfo::useFPForScavengingIndex(), llvm::ThumbRegisterInfo::useFPForScavengingIndex(), llvm::AArch64RegisterInfo::useFPForScavengingIndex(), llvm::SystemZELFFrameLowering::usePackedStack(), llvm::RISCVMachineFunctionInfo::useSaveRestoreLibCalls(), llvm::RegisterBankInfo::InstructionMapping::verify(), llvm::VLIWPacketizerList::VLIWPacketizerList(), windowsRequiresStackProbe(), and llvm::WebAssemblyFrameLowering::writeSPToGlobal().
getSubtarget() [2/2]
template<typename STC > const STC& llvm::MachineFunction::getSubtarget () const inline
getSubtarget - This method returns a pointer to the specified type of TargetSubtargetInfo.
In debug builds, it verifies that the object being returned is of the correct type.
Definition at line 677 of file MachineFunction.h.
getTarget()
const LLVMTargetMachine& llvm::MachineFunction::getTarget () const inline
getTarget - Return the target machine this machine code is compiled with
Definition at line 668 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), AlignBlocks(), llvm::NVPTXTargetLowering::allowFMA(), llvm::NVPTXTargetLowering::allowUnsafeFPMath(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::MachineBasicBlock::canSplitCriticalEdge(), llvm::X86FrameLowering::canUseLEAForSPInEpilogue(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::MipsTargetLowering::createFastISel(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::AsmPrinter::emitPCSections(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::AsmPrinter::emitStackSizeSection(), llvm::AsmPrinter::emitStackUsage(), llvm::TargetFrameLowering::enableCFIFixup(), ExpandMOVImmSExti8(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::AMDGPUSubtarget::get(), llvm::HexagonFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::NVPTXRegisterInfo::getFrameLocalRegister(), llvm::NVPTXRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::X86InstrInfo::getGlobalBaseReg(), getGlobalBaseRegClass(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::LoongArchInstrInfo::getInstSizeInBytes(), llvm::ARCInstrInfo::getInstSizeInBytes(), llvm::MSP430InstrInfo::getInstSizeInBytes(), llvm::AVRInstrInfo::getInstSizeInBytes(), llvm::CSKYInstrInfo::getInstSizeInBytes(), llvm::RISCVInstrInfo::getInstSizeInBytes(), llvm::MipsInstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::getInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), llvm::PPCInstrInfo::getInstSizeInBytes(), llvm::SIInstrInfo::getInstSizeInBytes(), llvm::HexagonInstrInfo::getSize(), llvm::MipsFrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::VEFrameLowering::hasFP(), llvm::RISCVFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::LoongArchFrameLowering::hasFP(), llvm::ARCFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::CSKYFrameLowering::hasFP(), llvm::SystemZELFFrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::HexagonFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::M68kFrameLowering::hasFP(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::MIRParserImpl::initializeCallSiteInfo(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::AArch64InstrInfo::isAssociativeAndCommutative(), isCombineInstrCandidateFP(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::AMDGPUCallLowering::isEligibleForTailCallOptimization(), llvm::AArch64InstrInfo::isFunctionSafeToOutlineFrom(), llvm::isKnownNeverNaN(), isOptNone(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::MipsCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::SITargetLowering::LowerCall(), llvm::CallLowering::lowerCall(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerTailCall(), matchFoldGlobalOffset(), llvm::AArch64FunctionInfo::needsDwarfUnwindInfo(), llvm::PPCFrameLowering::needsFP(), needsFrameMoves(), llvm::WebAssemblyFrameLowering::needsPrologForEH(), needsPrologueENDBR(), needsWinCFI(), llvm::AMDGPUMIRFormatter::parseCustomPseudoSourceValue(), llvm::MIRPrinter::print(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), promoteToConstantPool(), llvm::InstructionSelect::runOnMachineFunction(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::AsmPrinter::SetupMachineFunction(), shouldLowerMemFuncForSize(), shouldUseDebugInstrRef(), llvm::ARMSubtarget::splitFramePointerPush(), llvm::ARMSubtarget::splitFramePushPop(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIEImpl().
getTypeIDFor()
unsigned MachineFunction::getTypeIDFor (const GlobalValue * TI)
Return the type id for the specified typeinfo. This is function wide.
Definition at line 814 of file MachineFunction.cpp.
References i, and N.
Referenced by addLandingPad().
getTypeInfos()
const std::vector<const GlobalValue *>& llvm::MachineFunction::getTypeInfos () const inline
Return a reference to the C++ typeinfo for the current function.
Definition at line 1214 of file MachineFunction.h.
Referenced by llvm::EHStreamer::emitExceptionTable(), and llvm::EHStreamer::emitTypeInfos().
getVariableDbgInfo() [1/2]
VariableDbgInfoMapTy& llvm::MachineFunction::getVariableDbgInfo () inline
Definition at line 1232 of file MachineFunction.h.
Referenced by llvm::MIRPrinter::convertStackObjects().
getVariableDbgInfo() [2/2]
const VariableDbgInfoMapTy& llvm::MachineFunction::getVariableDbgInfo () const inline
Definition at line 1233 of file MachineFunction.h.
getWasmEHFuncInfo() [1/2]
WasmEHFuncInfo* llvm::MachineFunction::getWasmEHFuncInfo () inline
Definition at line 711 of file MachineFunction.h.
getWasmEHFuncInfo() [2/2]
const WasmEHFuncInfo* llvm::MachineFunction::getWasmEHFuncInfo () const inline
getWasmEHFuncInfo - Return information about how the current function uses Wasm exception handling.
Returns null for functions that don't use wasm exception handling.
Definition at line 710 of file MachineFunction.h.
Referenced by llvm::WebAssemblyFunctionInfo::initializeBaseYamlFields(), llvm::WebAssemblyExceptionInfo::recalculate(), llvm::FunctionLoweringInfo::set(), and llvm::yaml::WebAssemblyFunctionInfo::WebAssemblyFunctionInfo().
getWasmLandingPadIndex()
unsigned llvm::MachineFunction::getWasmLandingPadIndex (const MachineBasicBlock * LPad) const inline
Get the index in wasm EH for a given landing pad.
Definition at line 1162 of file MachineFunction.h.
References assert(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::lookup().
Referenced by llvm::WasmException::computeCallSiteTable().
getWinEHFuncInfo() [1/2]
WinEHFuncInfo* llvm::MachineFunction::getWinEHFuncInfo () inline
Definition at line 717 of file MachineFunction.h.
getWinEHFuncInfo() [2/2]
const WinEHFuncInfo* llvm::MachineFunction::getWinEHFuncInfo () const inline
getWinEHFuncInfo - Return information about how the current function uses Windows exception handling.
Returns null for functions that don't use funclets for exception handling.
Definition at line 716 of file MachineFunction.h.
Referenced by llvm::WinException::beginFunction(), llvm::X86FrameLowering::emitPrologue(), MarkEHGuard(), MarkEHRegistrationNode(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), and llvm::FunctionLoweringInfo::set().
hasAnyCallSiteLabel()
bool llvm::MachineFunction::hasAnyCallSiteLabel () const inline
Definition at line 1183 of file MachineFunction.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::empty().
hasAnyCallSiteLandingPad()
bool llvm::MachineFunction::hasAnyCallSiteLandingPad () const inline
Definition at line 1167 of file MachineFunction.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::empty().
hasAnyWasmLandingPadIndex()
bool llvm::MachineFunction::hasAnyWasmLandingPadIndex () const inline
Return if there is any wasm exception handling.
Definition at line 1147 of file MachineFunction.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::empty().
hasBBLabels()
bool llvm::MachineFunction::hasBBLabels () const inline
Returns true if basic block labels are to be generated for this function.
Definition at line 657 of file MachineFunction.h.
References llvm::Labels.
Referenced by llvm::AsmPrinter::emitFunctionBody(), and llvm::AsmPrinter::SetupMachineFunction().
hasBBSections()
bool llvm::MachineFunction::hasBBSections () const inline
Returns true if this function has basic block sections enabled.
Definition at line 650 of file MachineFunction.h.
References llvm::All, llvm::List, and llvm::Preset.
Referenced by assignSections(), llvm::MachineBasicBlock::getSymbol(), and llvm::MIRParserImpl::initializeMachineFunction().
hasCallSiteBeginLabel()
bool llvm::MachineFunction::hasCallSiteBeginLabel (MCSymbol * BeginLabel) const inline
Return true if the begin label has a call site number associated with it.
Definition at line 1200 of file MachineFunction.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::count().
hasCallSiteLandingPad()
bool llvm::MachineFunction::hasCallSiteLandingPad (MCSymbol * Sym) inline
Return true if the landing pad Eh symbol has an associated call site.
Definition at line 1179 of file MachineFunction.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::empty().
hasEHCatchret()
bool llvm::MachineFunction::hasEHCatchret () const inline
Definition at line 1110 of file MachineFunction.h.
Referenced by llvm::MIRPrinter::print().
hasEHFunclets()
bool llvm::MachineFunction::hasEHFunclets () const inline
Definition at line 1116 of file MachineFunction.h.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::WinException::beginFunction(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), llvm::WinException::endFunction(), getFixedObjectSize(), llvm::AArch64RegisterInfo::getLocalAddressRegister(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::AArch64FrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), needFuncLabels(), llvm::MIRPrinter::print(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::processFunctionBeforeFrameIndicesReplaced(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
hasEHScopes()
bool llvm::MachineFunction::hasEHScopes () const inline
Definition at line 1113 of file MachineFunction.h.
Referenced by llvm::getEHScopeMembership(), and llvm::MIRPrinter::print().
hasInlineAsm()
bool llvm::MachineFunction::hasInlineAsm () const inline
Returns true if the function contains any inline assembly.
Definition at line 745 of file MachineFunction.h.
Referenced by llvm::CodeViewDebug::beginFunctionImpl(), llvm::PPCRegisterInfo::getReservedRegs(), and llvm::SelectionDAGISel::runOnMachineFunction().
hasWasmLandingPadIndex()
bool llvm::MachineFunction::hasWasmLandingPadIndex (const MachineBasicBlock * LPad) const inline
Returns true if the landing pad has an associate index in wasm EH.
Definition at line 1157 of file MachineFunction.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::count().
Referenced by llvm::WasmException::computeCallSiteTable(), and llvm::WasmException::endFunction().
hasWinCFI()
bool llvm::MachineFunction::hasWinCFI () const inline
Definition at line 754 of file MachineFunction.h.
Referenced by llvm::WinException::beginFunction(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::ARMFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86AsmPrinter::emitInstruction(), and llvm::MIRPrinter::print().
initTargetMachineFunctionInfo()
void MachineFunction::initTargetMachineFunctionInfo (const TargetSubtargetInfo & STI)
Initialize the target specific MachineFunctionInfo.
Definition at line 236 of file MachineFunction.cpp.
References assert().
Referenced by llvm::MachineModuleInfo::getOrCreateMachineFunction().
insert()
void llvm::MachineFunction::insert (iterator MBBI, MachineBasicBlock * MBB) inline
Definition at line 889 of file MachineFunction.h.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::insert(), MBB, and MBBI.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), createFrameHelperMachineFunction(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::SystemZ::emitBlockAfter(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::emitProbedAlloca(), emitReadCycleWidePseudo(), emitXBegin(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::SelectionDAGBuilder::FindMergedConditions(), INITIALIZE_PASS(), llvm::PPCFrameLowering::inlineStackProbe(), insertDivByZeroTrap(), loadM0FromVGPR(), llvm::PeelSingleBlockLoop(), llvm::ARMBlockPlacement::revertWhileToDoLoop(), split(), llvm::MachineBasicBlock::splitAt(), splitBlockForLoop(), llvm::MachineBasicBlock::SplitCriticalEdge(), splitEdge(), and splitMBB().
makeDebugValueSubstitution()
void MachineFunction::makeDebugValueSubstitution (DebugInstrOperandPair A, DebugInstrOperandPair B, unsigned SubReg = 0)
Create a substitution between one <instr,operand> value to a different, new value.
Definition at line 925 of file MachineFunction.cpp.
References A, assert(), B, DebugOperandMemNumber, and DebugValueSubstitutions.
Referenced by substituteDebugValuesForInst().
moveCallSiteInfo()
void MachineFunction::moveCallSiteInfo (const MachineInstr * Old, const MachineInstr * New)
Move the call site info from Old to \New call site info.
This function is used when we are replacing one call instruction with another one to the same callee.
Definition at line 902 of file MachineFunction.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), eraseCallSiteInfo(), getCallInstr(), move, and llvm::MachineInstr::shouldUpdateCallSiteInfo().
needsFrameMoves()
bool MachineFunction::needsFrameMoves () const
True if this function needs frame moves for debug or exceptions.
Definition at line 628 of file MachineFunction.cpp.
References llvm::TargetOptions::ForceDwarfFrameSection, getMMI(), getTarget(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::Function::needsUnwindTableEntry(), and llvm::TargetMachine::Options.
Referenced by llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::TargetFrameLowering::enableCFIFixup(), ExpandMOVImmSExti8(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::AArch64FunctionInfo::needsDwarfUnwindInfo(), llvm::XCoreRegisterInfo::needsFrameMoves(), and llvm::ARCRegisterInfo::needsFrameMoves().
operator=()
MachineFunction& llvm::MachineFunction::operator= (const MachineFunction &) delete
print()
void MachineFunction::print (raw_ostream & OS, const SlotIndexes * Indexes = nullptr) const
print - Print out the MachineFunction in a format suitable for debugging to the specified stream.
Definition at line 586 of file MachineFunction.cpp.
References BB, E, getFunction(), getName(), getParent(), getProperties(), llvm::TargetSubtargetInfo::getRegisterInfo(), getSubtarget(), I, llvm::ModuleSlotTracker::incorporateFunction(), llvm::MachineRegisterInfo::livein_begin(), llvm::MachineRegisterInfo::livein_empty(), llvm::MachineRegisterInfo::livein_end(), OS, llvm::MachineJumpTableInfo::print(), llvm::MachineFunctionProperties::print(), llvm::MachineFrameInfo::print(), llvm::printReg(), and TRI.
Referenced by dump(), and llvm::SelectionDAGISel::runOnMachineFunction().
push_back()
void llvm::MachineFunction::push_back (MachineBasicBlock * MBB) inline
Definition at line 887 of file MachineFunction.h.
References MBB, and llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back().
Referenced by llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::SystemZXPLINKFrameLowering::inlineStackProbe(), llvm::IRTranslator::runOnMachineFunction(), and llvm::FunctionLoweringInfo::set().
push_front()
void llvm::MachineFunction::push_front (MachineBasicBlock * MBB) inline
Definition at line 888 of file MachineFunction.h.
References MBB, and llvm::iplist_impl< IntrusiveListT, TraitsT >::push_front().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), and llvm::X86FrameLowering::adjustForSegmentedStacks().
rbegin() [1/2]
reverse_iterator llvm::MachineFunction::rbegin () inline
Definition at line 875 of file MachineFunction.h.
Referenced by llvm::AsmPrinter::emitCFIInstruction().
rbegin() [2/2]
const_reverse_iterator llvm::MachineFunction::rbegin () const inline
Definition at line 876 of file MachineFunction.h.
remove() [1/2]
void llvm::MachineFunction::remove (iterator MBBI) inline
Definition at line 902 of file MachineFunction.h.
References MBBI, and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
Referenced by llvm::MachineBasicBlock::removeFromParent(), and llvm::IRTranslator::runOnMachineFunction().
remove() [2/2]
void llvm::MachineFunction::remove (MachineBasicBlock * MBBI) inline
Definition at line 903 of file MachineFunction.h.
References MBBI, and llvm::iplist_impl< IntrusiveListT, TraitsT >::remove().
removeFromMBBNumbering()
void llvm::MachineFunction::removeFromMBBNumbering (unsigned N) inline
removeFromMBBNumbering - Remove the specific machine basic block from our tracker, this is only really to be used by the MachineBasicBlock implementation.
Definition at line 933 of file MachineFunction.h.
References assert(), and N.
rend() [1/2]
reverse_iterator llvm::MachineFunction::rend () inline
Definition at line 877 of file MachineFunction.h.
rend() [2/2]
const_reverse_iterator llvm::MachineFunction::rend () const inline
Definition at line 878 of file MachineFunction.h.
RenumberBlocks()
void MachineFunction::RenumberBlocks (MachineBasicBlock * MBB = nullptr)
RenumberBlocks - This discards all of the MachineBasicBlock numbers and recomputes them.
This discards all of the MachineBasicBlock numbers and recomputes them.
This guarantees that the MBB numbers are sequential, dense, and match the ordering of the blocks within the function. If a specific MachineBasicBlock is specified, only that block and those after it are renumbered.
Definition at line 326 of file MachineFunction.cpp.
References assert(), begin(), E, empty(), end(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getNumber(), MBB, MBBI, and llvm::MachineBasicBlock::setNumber().
Referenced by llvm::ARMBlockPlacement::revertWhileToDoLoop(), llvm::ARMBlockPlacement::runOnMachineFunction(), and sortBlocks().
reset()
void llvm::MachineFunction::reset () inline
Reset the instance as if it was just created.
Definition at line 597 of file MachineFunction.h.
References clear(), and llvm::cl::init().
resetDelegate()
void llvm::MachineFunction::resetDelegate (Delegate * delegate) inline
Reset the currently registered delegate - otherwise assert.
Definition at line 603 of file MachineFunction.h.
References assert().
Referenced by llvm::RAIIDelegateInstaller::~RAIIDelegateInstaller().
salvageCopySSA()
auto MachineFunction::salvageCopySSA (MachineInstr & MI, DenseMap< Register, DebugInstrOperandPair > & DbgPHICache)
Find the underlying defining instruction / operand for a COPY instruction while in SSA form.
Copies do not actually define values – they move them between registers. Labelling a COPY-like instruction with an instruction number is to be avoided as it makes value numbers non-unique later in compilation. This method follows the definition chain for any sequence of COPY-like instructions to find whatever non-COPY-like instruction defines the copied value; or for parameters, creates a DBG_PHI on entry. May insert instructions into the entry block! MI The copy-like instruction to salvage. DbgPHICache A container to cache already-solved COPYs.
Returns
An instruction/operand pair identifying the defining value.
Definition at line 965 of file MachineFunction.cpp.
References assert(), MI, and TII.
Referenced by finalizeDebugInstrRefs().
salvageCopySSAImpl()
auto MachineFunction::salvageCopySSAImpl (MachineInstr & MI)
Definition at line 990 of file MachineFunction.cpp.
References assert(), Builder, llvm::BuildMI(), llvm::MachineRegisterInfo::def_begin(), llvm::MachineInstr::getDebugInstrNum(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineOperand::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::MachineRegisterInfo::hasOneDef(), llvm::MachineInstr::isCopyLike(), llvm_unreachable, llvm::make_range(), MI, MRI, llvm::MachineInstr::operands(), P, llvm::TargetRegisterInfo::regsOverlap(), llvm::reverse(), SubReg, TII, and TRI.
setAlignment()
void llvm::MachineFunction::setAlignment (Align A) inline
setAlignment - Set the alignment of the function.
Definition at line 723 of file MachineFunction.h.
Referenced by llvm::MIRParserImpl::initializeMachineFunction(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
setBBSectionsType()
void llvm::MachineFunction::setBBSectionsType (BasicBlockSection V) inline
Definition at line 661 of file MachineFunction.h.
Referenced by llvm::MIRParserImpl::initializeMachineFunction().
setCallsEHReturn()
void llvm::MachineFunction::setCallsEHReturn (bool b) inline
Definition at line 1105 of file MachineFunction.h.
References b.
Referenced by llvm::MIRParserImpl::initializeMachineFunction().
setCallSiteBeginLabel()
void llvm::MachineFunction::setCallSiteBeginLabel (MCSymbol * BeginLabel, unsigned Site) inline
Map the begin label for a call site.
Definition at line 1188 of file MachineFunction.h.
setCallSiteLandingPad()
void MachineFunction::setCallSiteLandingPad (MCSymbol * Sym, ArrayRef< unsigned > Sites)
Map the landing pad's EH symbol to the call site indexes.
Definition at line 809 of file MachineFunction.cpp.
References llvm::ArrayRef< T >::begin(), and llvm::ArrayRef< T >::end().
setCallsUnwindInit()
void llvm::MachineFunction::setCallsUnwindInit (bool b) inline
Definition at line 1108 of file MachineFunction.h.
References b.
Referenced by llvm::MIRParserImpl::initializeMachineFunction().
setDebugInstrNumberingCount()
void MachineFunction::setDebugInstrNumberingCount (unsigned Num)
Set value of DebugInstrNumberingCount field.
Avoid using this unless you're deserializing this data.
Definition at line 921 of file MachineFunction.cpp.
References DebugInstrNumberingCount.
setDelegate()
void llvm::MachineFunction::setDelegate (Delegate * delegate) inline
Set the delegate.
resetDelegate must be called before attempting to set.
Definition at line 611 of file MachineFunction.h.
References assert().
Referenced by llvm::RAIIDelegateInstaller::RAIIDelegateInstaller().
setExposesReturnsTwice()
void llvm::MachineFunction::setExposesReturnsTwice (bool B) inline
setCallsSetJmp - Set a flag that indicates if there's a call to a "returns twice" function.
Definition at line 740 of file MachineFunction.h.
References B.
Referenced by llvm::MIRParserImpl::initializeMachineFunction(), and llvm::SelectionDAGISel::runOnMachineFunction().
setHasEHCatchret()
void llvm::MachineFunction::setHasEHCatchret (bool V) inline
Definition at line 1111 of file MachineFunction.h.
Referenced by llvm::MIRParserImpl::initializeMachineFunction().
setHasEHFunclets()
void llvm::MachineFunction::setHasEHFunclets (bool V) inline
Definition at line 1117 of file MachineFunction.h.
Referenced by llvm::MIRParserImpl::initializeMachineFunction(), and llvm::FunctionLoweringInfo::set().
setHasEHScopes()
void llvm::MachineFunction::setHasEHScopes (bool V) inline
Definition at line 1114 of file MachineFunction.h.
Referenced by llvm::MIRParserImpl::initializeMachineFunction(), and llvm::FunctionLoweringInfo::set().
setHasInlineAsm()
void llvm::MachineFunction::setHasInlineAsm (bool B) inline
Set a flag that indicates that the function contains inline assembly.
Definition at line 750 of file MachineFunction.h.
References B.
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
setHasWinCFI()
void llvm::MachineFunction::setHasWinCFI (bool v) inline
Definition at line 757 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::MIRParserImpl::initializeMachineFunction(), and llvm::X86FrameLowering::processFunctionBeforeFrameFinalized().
setObserver()
void llvm::MachineFunction::setObserver (GISelChangeObserver * O) inline
Definition at line 619 of file MachineFunction.h.
References llvm::RISCVFenceField::O.
Referenced by llvm::RAIIMFObserverInstaller::RAIIMFObserverInstaller(), and llvm::RAIIMFObserverInstaller::~RAIIMFObserverInstaller().
setSection()
void llvm::MachineFunction::setSection (MCSection * S) inline
Indicates the Section this function belongs to.
Definition at line 630 of file MachineFunction.h.
References S.
setUseDebugInstrRef()
void MachineFunction::setUseDebugInstrRef (bool UseInstrRef)
Set whether this function will use instruction referencing or not.
Definition at line 1219 of file MachineFunction.cpp.
References UseDebugInstrRef.
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
setVariableDbgInfo()
void llvm::MachineFunction::setVariableDbgInfo (const DILocalVariable * Var, const DIExpression * Expr, int Slot, const DILocation * Loc) inline
Collect information used to emit debugging information of a variable.
Definition at line 1227 of file MachineFunction.h.
References llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::MIRParserImpl::parseStackObjectsDebugInfo(), and processDbgDeclare().
setWasmLandingPadIndex()
void llvm::MachineFunction::setWasmLandingPadIndex (const MachineBasicBlock * LPad, unsigned Index) inline
Map the landing pad to its index. Used for Wasm exception handling.
Definition at line 1152 of file MachineFunction.h.
References Index.
Referenced by mapWasmLandingPadIndex().
shouldSplitStack()
bool MachineFunction::shouldSplitStack () const
Should we be emitting segmented stack stuff for the function.
Definition at line 312 of file MachineFunction.cpp.
References getFunction(), and llvm::Function::hasFnAttribute().
Referenced by llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::enableShrinkWrapping(), and llvm::AsmPrinter::SetupMachineFunction().
shouldUseDebugInstrRef()
bool MachineFunction::shouldUseDebugInstrRef () const
Determine whether, in the current machine configuration, we should use instruction referencing or not.
Definition at line 1197 of file MachineFunction.cpp.
References llvm::debuginfoShouldUseDebugInstrRef(), F, getTarget(), and llvm::CodeGenOpt::None.
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
size()
unsigned llvm::MachineFunction::size () const inline
Definition at line 880 of file MachineFunction.h.
Referenced by llvm::AsmPrinter::emitBBAddrMapSection(), getJTISymbol(), llvm::MIRParserImpl::initializeCallSiteInfo(), llvm::InstructionSelect::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), and llvm::GraphTraits< DOTMachineFuncInfo * >::size().
sort()
template<typename Comp > void llvm::MachineFunction::sort (Comp comp) inline
Definition at line 908 of file MachineFunction.h.
splice() [1/3]
void llvm::MachineFunction::splice (iterator InsertPt, iterator MBBI) inline
Definition at line 892 of file MachineFunction.h.
References MBBI, and llvm::iplist_impl< IntrusiveListT, TraitsT >::splice().
Referenced by llvm::MachineBasicBlock::moveAfter(), and llvm::MachineBasicBlock::moveBefore().
splice() [2/3]
void llvm::MachineFunction::splice (iterator InsertPt, iterator MBBI, iterator MBBE) inline
Definition at line 898 of file MachineFunction.h.
References MBBI, and llvm::iplist_impl< IntrusiveListT, TraitsT >::splice().
splice() [3/3]
void llvm::MachineFunction::splice (iterator InsertPt, MachineBasicBlock * MBB) inline
Definition at line 895 of file MachineFunction.h.
References MBB, and llvm::iplist_impl< IntrusiveListT, TraitsT >::splice().
substituteDebugValuesForInst()
void MachineFunction::substituteDebugValuesForInst (const MachineInstr & Old, MachineInstr & New, unsigned MaxOperand = UINT_MAX)
Create substitutions for any tracked values in Old, to point at New.
Needed when we re-create an instruction during optimization, which has the same signature (i.e., def operands in the same place) but a modified instruction type, flags, or otherwise. An example: X86 moves are sometimes transformed into equivalent LEAs. If the two instructions are not the same opcode, limit which operands to examine for substitutions to the first N operands by setting MaxOperand.
Definition at line 936 of file MachineFunction.cpp.
References assert(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), I, makeDebugValueSubstitution(), llvm::min(), and llvm::MachineInstr::peekDebugInstrNum().
useDebugInstrRef()
bool MachineFunction::useDebugInstrRef () const
Returns true if the function's variable locations are tracked with instruction referencing.
Definition at line 1215 of file MachineFunction.cpp.
References UseDebugInstrRef.
Referenced by llvm::InstrEmitter::InstrEmitter(), llvm::MIRPrinter::print(), and llvm::SelectionDAGISel::runOnMachineFunction().
verify()
bool MachineFunction::verify (Pass * p = nullptr, const char * Banner = nullptr, bool AbortOnError = true) const
Run the current MachineFunction through the machine code verifier, useful for debugger use.
Returns
true if no problems were found.
Definition at line 342 of file MachineVerifier.cpp.
References p, llvm::report_fatal_error(), and verify().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::RegScavenger::forward(), llvm::MIRParserImpl::initializeMachineFunction(), and verify().
viewCFG()
void MachineFunction::viewCFG () const
viewCFG - This function is meant for use from the debugger.
You can just say 'call F->viewCFG()' and a ghostview window should pop up from the program, displaying the CFG of the current function with the code for each basic block inside. This depends on there being a 'dot' and 'gv' program in your path.
Definition at line 672 of file MachineFunction.cpp.
References llvm::errs(), getName(), and llvm::ViewGraph().
viewCFGOnly()
void MachineFunction::viewCFGOnly () const
viewCFGOnly - This function is meant for use from the debugger.
It works just like viewCFG, but it does not include the contents of basic blocks into the nodes, just the label. If you are only interested in the CFG this can make the graph smaller.
Definition at line 682 of file MachineFunction.cpp.
References llvm::errs(), getName(), and llvm::ViewGraph().
Friends And Related Function Documentation
ilist_traits< MachineInstr >
friend struct ilist_traits< MachineInstr > friend
Definition at line 462 of file MachineFunction.h.
Member Data Documentation
DebugInstrNumberingCount
unsigned llvm::MachineFunction::DebugInstrNumberingCount = 0
A count of how many instructions in the function have had numbers assigned to them.
Used for debug value tracking, to determine the next instruction number.
Definition at line 471 of file MachineFunction.h.
Referenced by setDebugInstrNumberingCount().
DebugOperandMemNumber
const unsigned MachineFunction::DebugOperandMemNumber = 1000000 static
A reserved operand number representing the instructions memory operand, for instructions that have a stack spill fused into them.
Definition at line 587 of file MachineFunction.h.
Referenced by makeDebugValueSubstitution().
DebugPHIPositions
DenseMap<unsigned, DebugPHIRegallocPos> llvm::MachineFunction::DebugPHIPositions
Map of debug instruction numbers to the position of their PHI instructions during register allocation.
See DebugPHIRegallocPos.
Definition at line 528 of file MachineFunction.h.
DebugValueSubstitutions
SmallVector<DebugSubstitution, 8> llvm::MachineFunction::DebugValueSubstitutions
Debug value substitutions: a collection of DebugSubstitution objects, recording changes in where a value is defined.
For example, when one instruction is substituted for another. Keeping a record allows recovery of variable locations after compilation finishes.
Definition at line 510 of file MachineFunction.h.
Referenced by makeDebugValueSubstitution(), and llvm::MIRPrinter::print().
UseDebugInstrRef
bool llvm::MachineFunction::UseDebugInstrRef = false
Flag for whether this function contains DBG_VALUEs (false) or DBG_INSTR_REF (true).
Definition at line 532 of file MachineFunction.h.
Referenced by setUseDebugInstrRef(), and useDebugInstrRef().
VariableDbgInfos
VariableDbgInfoMapTy llvm::MachineFunction::VariableDbgInfos
Definition at line 466 of file MachineFunction.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineFunction.h
lib/CodeGen/MachineFunction.cpp
lib/CodeGen/MachineVerifier.cpp