LLVM: llvm::MCPseudoProbeBase Class Reference
llvm::MCPseudoProbeBase Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
MCPseudoProbeBase (uint64_t G, uint64_t I, uint64_t At, uint8_t T)
bool isEntry () const
uint64_t getGuid () const
uint64_t getIndex () const
uint8_t getAttributes () const
uint8_t getType () const
bool isBlock () const
bool isIndirectCall () const
bool isDirectCall () const
bool isCall () const
void setAttributes (uint8_t Attr)
Protected Attributes
uint64_t Guid
uint64_t Index
uint8_t Attributes
uint8_t Type
Static Protected Attributes
const static uint32_t PseudoProbeFirstId = 1
Detailed Description
Definition at line 107 of file MCPseudoProbe.h.
Constructor & Destructor Documentation
MCPseudoProbeBase()
llvm::MCPseudoProbeBase::MCPseudoProbeBase (uint64_t G, uint64_t I, uint64_t At, uint8_t T) inline
Definition at line 119 of file MCPseudoProbe.h.
References T.
Member Function Documentation
getAttributes()
uint8_t llvm::MCPseudoProbeBase::getAttributes () const inline
Definition at line 128 of file MCPseudoProbe.h.
References Attributes.
Referenced by llvm::MCPseudoProbeInlineTree::emit().
getGuid()
uint64_t llvm::MCPseudoProbeBase::getGuid () const inline
Definition at line 124 of file MCPseudoProbe.h.
References Guid.
Referenced by llvm::MCPseudoProbeInlineTree::addPseudoProbe(), llvm::MCPseudoProbeInlineTree::emit(), and llvm::MCPseudoProbeDecoder::getInlineContextForProbe().
getIndex()
uint64_t llvm::MCPseudoProbeBase::getIndex () const inline
Definition at line 126 of file MCPseudoProbe.h.
References Index.
Referenced by llvm::MCPseudoProbeDecoder::getInlineContextForProbe().
getType()
uint8_t llvm::MCPseudoProbeBase::getType () const inline
Definition at line 130 of file MCPseudoProbe.h.
References Type.
isBlock()
bool llvm::MCPseudoProbeBase::isBlock () const inline
Definition at line 132 of file MCPseudoProbe.h.
References llvm::Block.
isCall()
bool llvm::MCPseudoProbeBase::isCall () const inline
Definition at line 144 of file MCPseudoProbe.h.
References isDirectCall(), and isIndirectCall().
isDirectCall()
bool llvm::MCPseudoProbeBase::isDirectCall () const inline
Definition at line 140 of file MCPseudoProbe.h.
References llvm::DirectCall.
Referenced by isCall().
isEntry()
bool llvm::MCPseudoProbeBase::isEntry () const inline
Definition at line 122 of file MCPseudoProbe.h.
References PseudoProbeFirstId.
isIndirectCall()
bool llvm::MCPseudoProbeBase::isIndirectCall () const inline
Definition at line 136 of file MCPseudoProbe.h.
References llvm::IndirectCall.
Referenced by isCall().
setAttributes()
void llvm::MCPseudoProbeBase::setAttributes (uint8_t Attr) inline
Definition at line 146 of file MCPseudoProbe.h.
References Attributes.
Member Data Documentation
Attributes
uint8_t llvm::MCPseudoProbeBase::Attributes protected
Definition at line 111 of file MCPseudoProbe.h.
Referenced by getAttributes(), llvm::MCPseudoProbe::MCPseudoProbe(), and setAttributes().
Guid
uint64_t llvm::MCPseudoProbeBase::Guid protected
Definition at line 109 of file MCPseudoProbe.h.
Referenced by getGuid().
Index
uint64_t llvm::MCPseudoProbeBase::Index protected
Definition at line 110 of file MCPseudoProbe.h.
Referenced by getIndex().
PseudoProbeFirstId
const static uint32_t llvm::MCPseudoProbeBase::PseudoProbeFirstId = 1 static protected
Definition at line 116 of file MCPseudoProbe.h.
Referenced by isEntry().
Type
uint8_t llvm::MCPseudoProbeBase::Type protected
Definition at line 112 of file MCPseudoProbe.h.
Referenced by getType().
The documentation for this class was generated from the following file:
include/llvm/MC/MCPseudoProbe.h