LLVM: llvm::InlineAsm Class Reference
llvm::InlineAsm Class Reference final
#include "llvm/IR/InlineAsm.h"
Classes
struct ConstraintInfo
struct SubConstraintInfo
Public Types
enum AsmDialect { AD_ATT, AD_Intel }
enum ConstraintPrefix { isInput, isOutput, isClobber, isLabel }
enum : uint32_t {
Op_InputChain = 0, Op_AsmString = 1, Op_MDNode = 2, Op_ExtraInfo = 3,
Op_FirstOperand = 4, MIOp_AsmString = 0, MIOp_ExtraInfo = 1, MIOp_FirstOperand = 2,
Extra_HasSideEffects = 1, Extra_IsAlignStack = 2, Extra_AsmDialect = 4, Extra_MayLoad = 8,
Extra_MayStore = 16, Extra_IsConvergent = 32, Kind_RegUse = 1, Kind_RegDef = 2,
Kind_RegDefEarlyClobber = 3, Kind_Clobber = 4, Kind_Imm = 5, Kind_Mem = 6,
Kind_Func = 7, Constraint_Unknown = 0, Constraint_es, Constraint_i,
Constraint_k, Constraint_m, Constraint_o, Constraint_v,
Constraint_A, Constraint_Q, Constraint_R, Constraint_S,
Constraint_T, Constraint_Um, Constraint_Un, Constraint_Uq,
Constraint_Us, Constraint_Ut, Constraint_Uv, Constraint_Uy,
Constraint_X, Constraint_Z, Constraint_ZB, Constraint_ZC,
Constraint_Zy, Constraint_p, Constraint_ZQ, Constraint_ZR,
Constraint_ZS, Constraint_ZT, Constraints_Max = Constraint_ZT, Constraints_ShiftAmount = 16,
Flag_MatchingOperand = 0x80000000
}
using ConstraintCodeVector = std::vector< std::string >
using SubConstraintInfoVector = std::vector< SubConstraintInfo >
using ConstraintInfoVector = std::vector< ConstraintInfo >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
InlineAsm (const InlineAsm &)=delete
InlineAsm & operator= (const InlineAsm &)=delete
bool hasSideEffects () const
bool isAlignStack () const
AsmDialect getDialect () const
bool canThrow () const
PointerType * getType () const
getType - InlineAsm's are always pointers.
FunctionType * getFunctionType () const
getFunctionType - InlineAsm's are always pointers to functions.
const std::string & getAsmString () const
const std::string & getConstraintString () const
void collectAsmStrs (SmallVectorImpl< StringRef > &AsmStrs) const
ConstraintInfoVector ParseConstraints () const
ParseConstraints - Parse the constraints of this inlineasm object, returning them the same way that ParseConstraints(str) does.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static InlineAsm * get (FunctionType *Ty, StringRef AsmString, StringRef Constraints, bool hasSideEffects, bool isAlignStack=false, AsmDialect asmDialect=AD_ATT, bool canThrow=false)
InlineAsm::get - Return the specified uniqued inline asm string.
static Error verify (FunctionType *Ty, StringRef Constraints)
This static method can be used by the parser to check to see if the specified constraint string is legal for the type.
static ConstraintInfoVector ParseConstraints (StringRef ConstraintString)
ParseConstraints - Split up the constraint string into the specific constraints and their prefixes.
static bool classof (const Value *V)
static unsigned getFlagWord (unsigned Kind, unsigned NumOps)
static bool isRegDefKind (unsigned Flag)
static bool isImmKind (unsigned Flag)
static bool isMemKind (unsigned Flag)
static bool isFuncKind (unsigned Flag)
static bool isRegDefEarlyClobberKind (unsigned Flag)
static bool isClobberKind (unsigned Flag)
static unsigned getFlagWordForMatchingOp (unsigned InputFlag, unsigned MatchedOperandNo)
getFlagWordForMatchingOp - Augment an existing flag word returned by getFlagWord with information indicating that this input operand is tied to a previous output operand.
static unsigned getFlagWordForRegClass (unsigned InputFlag, unsigned RC)
getFlagWordForRegClass - Augment an existing flag word returned by getFlagWord with the required register class for the following register operands.
static unsigned getFlagWordForMem (unsigned InputFlag, unsigned Constraint)
Augment an existing flag word returned by getFlagWord with the constraint code for a memory constraint.
static unsigned convertMemFlagWordToMatchingFlagWord (unsigned InputFlag)
static unsigned getKind (unsigned Flags)
static unsigned getMemoryConstraintID (unsigned Flag)
static unsigned getNumOperandRegisters (unsigned Flag)
getNumOperandRegisters - Extract the number of registers field from the inline asm operand flag.
static bool isUseOperandTiedToDef (unsigned Flag, unsigned &Idx)
isUseOperandTiedToDef - Return true if the flag of the inline asm operand indicates it is an use operand that's matched to a def operand.
static bool hasRegClassConstraint (unsigned Flag, unsigned &RC)
hasRegClassConstraint - Returns true if the flag contains a register class constraint.
static std::vector< StringRef > getExtraInfoNames (unsigned ExtraInfo)
static StringRef getKindName (unsigned Kind)
static StringRef getMemConstraintName (unsigned Constraint)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Friends
struct InlineAsmKeyType
class ConstantUniqueMap< InlineAsm >
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * >> &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Definition at line 33 of file InlineAsm.h.
Member Typedef Documentation
ConstraintCodeVector
using llvm::InlineAsm::ConstraintCodeVector = std::vector<std::string>
Definition at line 101 of file InlineAsm.h.
ConstraintInfoVector
using llvm::InlineAsm::ConstraintInfoVector = std::vector<ConstraintInfo>
Definition at line 120 of file InlineAsm.h.
SubConstraintInfoVector
using llvm::InlineAsm::SubConstraintInfoVector = std::vector<SubConstraintInfo>
Definition at line 118 of file InlineAsm.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint32_t
Enumerator
Op_InputChain
Op_AsmString
Op_MDNode
Op_ExtraInfo
Op_FirstOperand
MIOp_AsmString
MIOp_ExtraInfo
MIOp_FirstOperand
Extra_HasSideEffects
Extra_IsAlignStack
Extra_AsmDialect
Extra_MayLoad
Extra_MayStore
Extra_IsConvergent
Kind_RegUse
Kind_RegDef
Kind_RegDefEarlyClobber
Kind_Clobber
Kind_Imm
Kind_Mem
Kind_Func
Constraint_Unknown
Constraint_es
Constraint_i
Constraint_k
Constraint_m
Constraint_o
Constraint_v
Constraint_A
Constraint_Q
Constraint_R
Constraint_S
Constraint_T
Constraint_Um
Constraint_Un
Constraint_Uq
Constraint_Us
Constraint_Ut
Constraint_Uv
Constraint_Uy
Constraint_X
Constraint_Z
Constraint_ZB
Constraint_ZC
Constraint_Zy
Constraint_p
Constraint_ZQ
Constraint_ZR
Constraint_ZS
Constraint_ZT
Constraints_Max
Constraints_ShiftAmount
Flag_MatchingOperand
Definition at line 216 of file InlineAsm.h.
AsmDialect
enum llvm::InlineAsm::AsmDialect
Enumerator
AD_ATT
AD_Intel
Definition at line 35 of file InlineAsm.h.
ConstraintPrefix
enum llvm::InlineAsm::ConstraintPrefix
Enumerator
isInput
isOutput
isClobber
isLabel
Definition at line 94 of file InlineAsm.h.
Constructor & Destructor Documentation
InlineAsm()
llvm::InlineAsm::InlineAsm (const InlineAsm &) delete
Member Function Documentation
canThrow()
bool llvm::InlineAsm::canThrow () const inline
Definition at line 73 of file InlineAsm.h.
Referenced by get().
classof()
static bool llvm::InlineAsm::classof (const Value * V) inline static
Definition at line 195 of file InlineAsm.h.
References llvm::Value::getValueID().
collectAsmStrs()
void InlineAsm::collectAsmStrs (SmallVectorImpl< StringRef > & AsmStrs) const
Definition at line 62 of file InlineAsm.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::StringRef::empty(), and llvm::StringRef::split().
convertMemFlagWordToMatchingFlagWord()
static unsigned llvm::InlineAsm::convertMemFlagWordToMatchingFlagWord (unsigned InputFlag) inline static
Definition at line 346 of file InlineAsm.h.
References assert(), Constraints_ShiftAmount, and isMemKind().
get()
InlineAsm * InlineAsm::get (FunctionType * Ty, StringRef AsmString, StringRef Constraints, bool hasSideEffects, bool isAlignStack = false, AsmDialect asmDialect = AD_ATT, bool canThrow = false) static
InlineAsm::get - Return the specified uniqued inline asm string.
Definition at line 43 of file InlineAsm.cpp.
References canThrow(), llvm::Type::getContext(), llvm::PointerType::getUnqual(), hasSideEffects(), llvm::LLVMContextImpl::InlineAsms, isAlignStack(), and llvm::LLVMContext::pImpl.
Referenced by emitInlineAsm(), LLVMConstInlineAsm(), and LLVMGetInlineAsm().
getAsmString()
const std::string& llvm::InlineAsm::getAsmString () const inline
Definition at line 85 of file InlineAsm.h.
getConstraintString()
const std::string& llvm::InlineAsm::getConstraintString () const inline
Definition at line 86 of file InlineAsm.h.
getDialect()
AsmDialect llvm::InlineAsm::getDialect () const inline
Definition at line 72 of file InlineAsm.h.
getExtraInfoNames()
static std::vector<StringRef> llvm::InlineAsm::getExtraInfoNames (unsigned ExtraInfo) inline static
Definition at line 390 of file InlineAsm.h.
References AD_ATT, AD_Intel, Extra_AsmDialect, Extra_HasSideEffects, Extra_IsAlignStack, Extra_IsConvergent, Extra_MayLoad, and Extra_MayStore.
Referenced by llvm::TargetInstrInfo::createMIROperandComment().
getFlagWord()
static unsigned llvm::InlineAsm::getFlagWord (unsigned Kind, unsigned NumOps) inline static
Definition at line 293 of file InlineAsm.h.
References assert(), Kind_Func, and Kind_RegUse.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), llvm::InlineAsmLowering::lowerInlineAsm(), and llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands().
getFlagWordForMatchingOp()
static unsigned llvm::InlineAsm::getFlagWordForMatchingOp (unsigned InputFlag, unsigned MatchedOperandNo) inline static
getFlagWordForMatchingOp - Augment an existing flag word returned by getFlagWord with information indicating that this input operand is tied to a previous output operand.
Definition at line 313 of file InlineAsm.h.
References assert(), and Flag_MatchingOperand.
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), and llvm::InlineAsmLowering::lowerInlineAsm().
getFlagWordForMem()
static unsigned llvm::InlineAsm::getFlagWordForMem (unsigned InputFlag, unsigned Constraint) inline static
Augment an existing flag word returned by getFlagWord with the constraint code for a memory constraint.
Definition at line 337 of file InlineAsm.h.
References assert(), Constraints_Max, Constraints_ShiftAmount, isFuncKind(), and isMemKind().
Referenced by llvm::InlineAsmLowering::lowerInlineAsm(), and llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands().
getFlagWordForRegClass()
static unsigned llvm::InlineAsm::getFlagWordForRegClass (unsigned InputFlag, unsigned RC) inline static
getFlagWordForRegClass - Augment an existing flag word returned by getFlagWord with the required register class for the following register operands.
A tied use operand cannot have a register class, use the register class from the def operand instead.
Definition at line 325 of file InlineAsm.h.
References assert(), isImmKind(), and isMemKind().
Referenced by llvm::RegsForValue::AddInlineAsmOperands(), and llvm::InlineAsmLowering::lowerInlineAsm().
getFunctionType()
FunctionType * InlineAsm::getFunctionType () const
getFunctionType - InlineAsm's are always pointers to functions.
Definition at line 58 of file InlineAsm.cpp.
getKind()
static unsigned llvm::InlineAsm::getKind (unsigned Flags) inline static
Definition at line 351 of file InlineAsm.h.
Referenced by llvm::TargetInstrInfo::createMIROperandComment(), llvm::MachineInstr::getRegClassConstraint(), isClobberKind(), isFuncKind(), isImmKind(), isMemKind(), isRegDefEarlyClobberKind(), isRegDefKind(), llvm::HexagonTargetLowering::LowerINLINEASM(), and llvm::MachineInstr::print().
getKindName()
static StringRef llvm::InlineAsm::getKindName (unsigned Kind) inline static
Definition at line 414 of file InlineAsm.h.
References Kind_Clobber, Kind_Func, Kind_Imm, Kind_Mem, Kind_RegDef, Kind_RegDefEarlyClobber, Kind_RegUse, and llvm_unreachable.
Referenced by llvm::TargetInstrInfo::createMIROperandComment(), and llvm::MachineInstr::print().
getMemConstraintName()
static StringRef llvm::InlineAsm::getMemConstraintName (unsigned Constraint) inline static
Definition at line 434 of file InlineAsm.h.
References Constraint_es, Constraint_i, Constraint_k, Constraint_m, Constraint_o, Constraint_p, Constraint_Q, Constraint_R, Constraint_S, Constraint_T, Constraint_Um, Constraint_Un, Constraint_Uq, Constraint_Us, Constraint_Ut, Constraint_Uv, Constraint_Uy, Constraint_v, Constraint_X, Constraint_Z, Constraint_ZB, Constraint_ZC, Constraint_ZQ, Constraint_ZR, Constraint_ZS, Constraint_ZT, Constraint_Zy, and llvm_unreachable.
Referenced by llvm::TargetInstrInfo::createMIROperandComment(), and llvm::MachineInstr::print().
getMemoryConstraintID()
static unsigned llvm::InlineAsm::getMemoryConstraintID (unsigned Flag) inline static
Definition at line 355 of file InlineAsm.h.
References assert(), Constraints_ShiftAmount, isFuncKind(), and isMemKind().
Referenced by llvm::TargetInstrInfo::createMIROperandComment(), getLoadStoreOffsetSizeInBits(), llvm::MachineInstr::print(), and llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands().
getNumOperandRegisters()
static unsigned llvm::InlineAsm::getNumOperandRegisters (unsigned Flag) inline static
getNumOperandRegisters - Extract the number of registers field from the inline asm operand flag.
Definition at line 363 of file InlineAsm.h.
Referenced by EmitInlineAsmStr(), llvm::MachineInstr::findInlineAsmFlagIdx(), findMatchingInlineAsmOperand(), llvm::MachineInstr::findTiedOperandIdx(), getNumOpRegs(), llvm::HexagonTargetLowering::LowerINLINEASM(), llvm::MachineInstr::print(), llvm::AVRAsmPrinter::PrintAsmMemoryOperand(), llvm::AVRAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::MipsAsmPrinter::PrintAsmOperand(), and llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands().
getType()
PointerType* llvm::InlineAsm::getType () const inline
getType - InlineAsm's are always pointers.
Definition at line 77 of file InlineAsm.h.
References llvm::Value::getType().
hasRegClassConstraint()
static bool llvm::InlineAsm::hasRegClassConstraint (unsigned Flag, unsigned & RC) inline static
hasRegClassConstraint - Returns true if the flag contains a register class constraint.
Sets RC to the register class ID.
Definition at line 378 of file InlineAsm.h.
References Flag_MatchingOperand, and High.
Referenced by llvm::TargetInstrInfo::createMIROperandComment(), llvm::MachineInstr::getRegClassConstraint(), llvm::MachineInstr::print(), and llvm::ARMAsmPrinter::PrintAsmOperand().
hasSideEffects()
bool llvm::InlineAsm::hasSideEffects () const inline
Definition at line 70 of file InlineAsm.h.
Referenced by get().
isAlignStack()
bool llvm::InlineAsm::isAlignStack () const inline
Definition at line 71 of file InlineAsm.h.
Referenced by get().
isClobberKind()
static bool llvm::InlineAsm::isClobberKind (unsigned Flag) inline static
Definition at line 306 of file InlineAsm.h.
References getKind(), and Kind_Clobber.
isFuncKind()
static bool llvm::InlineAsm::isFuncKind (unsigned Flag) inline static
Definition at line 302 of file InlineAsm.h.
References getKind(), and Kind_Func.
Referenced by getFlagWordForMem(), getMemoryConstraintID(), and llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands().
isImmKind()
static bool llvm::InlineAsm::isImmKind (unsigned Flag) inline static
Definition at line 300 of file InlineAsm.h.
References getKind(), and Kind_Imm.
Referenced by llvm::TargetInstrInfo::createMIROperandComment(), getFlagWordForRegClass(), and llvm::MachineInstr::print().
isMemKind()
static bool llvm::InlineAsm::isMemKind (unsigned Flag) inline static
Definition at line 301 of file InlineAsm.h.
References getKind(), and Kind_Mem.
Referenced by convertMemFlagWordToMatchingFlagWord(), llvm::TargetInstrInfo::createMIROperandComment(), EmitInlineAsmStr(), findMatchingInlineAsmOperand(), getFlagWordForMem(), getFlagWordForRegClass(), getMemoryConstraintID(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::MachineInstr::print(), and llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands().
isRegDefEarlyClobberKind()
static bool llvm::InlineAsm::isRegDefEarlyClobberKind (unsigned Flag) inline static
Definition at line 303 of file InlineAsm.h.
References getKind(), and Kind_RegDefEarlyClobber.
Referenced by findMatchingInlineAsmOperand(), and llvm::InlineAsmLowering::lowerInlineAsm().
isRegDefKind()
static bool llvm::InlineAsm::isRegDefKind (unsigned Flag) inline static
Definition at line 299 of file InlineAsm.h.
References getKind(), and Kind_RegDef.
Referenced by findMatchingInlineAsmOperand(), and llvm::InlineAsmLowering::lowerInlineAsm().
isUseOperandTiedToDef()
static bool llvm::InlineAsm::isUseOperandTiedToDef (unsigned Flag, unsigned & Idx) inline static
isUseOperandTiedToDef - Return true if the flag of the inline asm operand indicates it is an use operand that's matched to a def operand.
Definition at line 369 of file InlineAsm.h.
References Flag_MatchingOperand.
Referenced by llvm::TargetInstrInfo::createMIROperandComment(), llvm::MachineInstr::findTiedOperandIdx(), llvm::MachineInstr::print(), llvm::ARMAsmPrinter::PrintAsmOperand(), and llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands().
operator=()
InlineAsm& llvm::InlineAsm::operator= (const InlineAsm &) delete
ParseConstraints() [1/2]
ConstraintInfoVector llvm::InlineAsm::ParseConstraints () const inline
ParseConstraints - Parse the constraints of this inlineasm object, returning them the same way that ParseConstraints(str) does.
Definition at line 190 of file InlineAsm.h.
Referenced by verify().
ParseConstraints() [2/2]
InlineAsm::ConstraintInfoVector InlineAsm::ParseConstraints (StringRef ConstraintString) static
ParseConstraints - Split up the constraint string into the specific constraints and their prefixes.
If this returns an empty vector, and if the constraint string itself isn't empty, there was an error parsing.
Definition at line 235 of file InlineAsm.cpp.
References llvm::StringRef::begin(), E, llvm::StringRef::end(), llvm::find(), I, and Info.
verify()
Error InlineAsm::verify (FunctionType * Ty, StringRef Constraints) static
This static method can be used by the parser to check to see if the specified constraint string is legal for the type.
Definition at line 273 of file InlineAsm.cpp.
References llvm::StringRef::empty(), llvm::StructType::getNumElements(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getReturnType(), isClobber, isInput, isLabel, isOutput, llvm::Type::isStructTy(), llvm::FunctionType::isVarArg(), llvm::Type::isVoidTy(), makeStringError(), ParseConstraints(), and llvm::Error::success().
Friends And Related Function Documentation
ConstantUniqueMap< InlineAsm >
friend class ConstantUniqueMap< InlineAsm > friend
Definition at line 42 of file InlineAsm.h.
InlineAsmKeyType
friend struct InlineAsmKeyType friend
Definition at line 41 of file InlineAsm.h.
The documentation for this class was generated from the following files:
include/llvm/IR/InlineAsm.h
lib/IR/InlineAsm.cpp