LLVM: llvm::DILocation Class Reference
llvm::DILocation Class Reference
Debug location.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
void replaceOperandWith (unsigned I, Metadata *New)=delete
DEFINE_MDNODE_GET (DILocation,(unsigned Line, unsigned Column, Metadata *Scope, Metadata *InlinedAt=nullptr, bool ImplicitCode=false),(Line, Column, Scope, InlinedAt, ImplicitCode)) DEFINE_MDNODE_GET(DILocation
const DILocation * cloneWithDiscriminator (unsigned Discriminator) const
Returns a new DILocation with updated Discriminator.
std::optional< const DILocation * > cloneWithBaseDiscriminator (unsigned BD) const
Returns a new DILocation with updated base discriminator BD.
unsigned getDuplicationFactor () const
Returns the duplication factor stored in the discriminator, or 1 if no duplication factor (or 0) is encoded.
unsigned getCopyIdentifier () const
Returns the copy identifier stored in the discriminator.
unsigned getBaseDiscriminator () const
Returns the base discriminator stored in the discriminator.
std::optional< const DILocation * > cloneByMultiplyingDuplicationFactor (unsigned DF) const
Returns a new DILocation with duplication factor DF * current duplication factor encoded in the discriminator.
Metadata * getRawScope () const
Metadata * getRawInlinedAt () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool isPseudoProbeDiscriminator (unsigned Discriminator)
static const DILocation * getMergedLocation (const DILocation *LocA, const DILocation *LocB)
When two instructions are combined into a single instruction we also need to combine the original locations into a single location.
static const DILocation * getMergedLocations (ArrayRef< const DILocation * > Locs)
Try to combine the vector of locations passed as input in a single one.
static unsigned getMaskedDiscriminator (unsigned D, unsigned B)
Return the masked discriminator value for an input discrimnator value D (i.e.
static unsigned getBaseDiscriminatorBits ()
Return the bits used for base discriminators.
static unsigned getBaseDiscriminatorFromDiscriminator (unsigned D, bool IsFSDiscriminator=false)
Returns the base discriminator for a given encoded discriminator D.
static std::optional< unsigned > encodeDiscriminator (unsigned BD, unsigned DF, unsigned CI)
Raw encoding of the discriminator.
static void decodeDiscriminator (unsigned D, unsigned &BD, unsigned &DF, unsigned &CI)
Raw decoder for values in an encoded discriminator D.
static unsigned getDuplicationFactorFromDiscriminator (unsigned D)
Returns the duplication factor for a given encoded discriminator D, or 1 if no value or 0 is encoded.
static unsigned getCopyIdentifierFromDiscriminator (unsigned D)
Returns the copy identifier for a given encoded discriminator D.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
unsigned Line
unsigned unsigned Column
unsigned unsigned DILocalScope * Scope
unsigned unsigned DILocalScope DILocation * InlinedAt = nullptr
unsigned unsigned DILocalScope DILocation bool ImplicitCode
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued, Distinct, Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Debug location.
A debug location in source code, used for debug info and otherwise.
Definition at line 1605 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DILocation::classof (const Metadata * MD) inline static
Definition at line 1845 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
cloneByMultiplyingDuplicationFactor()
std::optional< const DILocation * > llvm::DILocation::cloneByMultiplyingDuplicationFactor (unsigned DF) const inline
Returns a new DILocation with duplication factor DF * current duplication factor encoded in the discriminator.
The current duplication factor is as defined by getDuplicationFactor(). Returns std::nullopt if encoding failed.
Definition at line 2297 of file DebugInfoMetadata.h.
References assert(), cloneWithDiscriminator(), D, DF, llvm::EnableFSDiscriminator, encodeDiscriminator(), getBaseDiscriminator(), getCopyIdentifier(), and getDuplicationFactor().
Referenced by llvm::VPTransformState::setDebugLocFromInst().
cloneWithBaseDiscriminator()
std::optional< const DILocation * > llvm::DILocation::cloneWithBaseDiscriminator (unsigned BD) const inline
Returns a new DILocation with updated base discriminator BD.
Only the base discriminator is set in the new DILocation, the other encoded values are elided. If the discriminator cannot be encoded, the function returns std::nullopt.
Definition at line 2278 of file DebugInfoMetadata.h.
References cloneWithDiscriminator(), D, decodeDiscriminator(), DF, llvm::EnableFSDiscriminator, encodeDiscriminator(), and getBaseDiscriminator().
Referenced by addDiscriminators().
cloneWithDiscriminator()
const DILocation * llvm::DILocation::cloneWithDiscriminator (unsigned Discriminator) const inline
Returns a new DILocation with updated Discriminator.
Definition at line 2248 of file DebugInfoMetadata.h.
References llvm::MDNode::get(), llvm::MDNode::getContext(), llvm::DIScope::getScope(), getScope(), and Scope.
Referenced by cloneByMultiplyingDuplicationFactor(), cloneWithBaseDiscriminator(), and llvm::setProbeDistributionFactor().
decodeDiscriminator()
void DILocation::decodeDiscriminator (unsigned D, unsigned & BD, unsigned & DF, unsigned & CI) static
Raw decoder for values in an encoded discriminator D.
Definition at line 210 of file DebugInfoMetadata.cpp.
References D, DF, getNextComponentInDiscriminator(), and getUnsignedFromPrefixEncoding().
Referenced by cloneWithBaseDiscriminator(), and encodeDiscriminator().
DEFINE_MDNODE_GET()
llvm::DILocation::DEFINE_MDNODE_GET (DILocation , (unsigned Line, unsigned Column, Metadata *Scope, Metadata *InlinedAt=nullptr, bool ImplicitCode=false) , (Line, Column, Scope, InlinedAt, ImplicitCode))
encodeDiscriminator()
std::optional< unsigned > DILocation::encodeDiscriminator (unsigned BD, unsigned DF, unsigned CI) static
Raw encoding of the discriminator.
APIs such as cloneWithDuplicationFactor have certain special case behavior (e.g. treating empty duplication factor as the value '1'). This API, in conjunction with cloneWithDiscriminator, may be used to encode the raw values provided.
BD: base discriminator DF: duplication factor CI: copy index
The return is std::nullopt if the values cannot be encoded in 32 bits - for example, values for BD or DF larger than 12 bits. Otherwise, the return is the encoded value.
Definition at line 177 of file DebugInfoMetadata.cpp.
References decodeDiscriminator(), DF, encodeComponent(), encodingBits(), I, llvm::MipsISD::Ret, and uint64_t.
Referenced by cloneByMultiplyingDuplicationFactor(), and cloneWithBaseDiscriminator().
getBaseDiscriminator()
unsigned llvm::DILocation::getBaseDiscriminator () const inline
Returns the base discriminator stored in the discriminator.
Definition at line 2264 of file DebugInfoMetadata.h.
References llvm::EnableFSDiscriminator, and getBaseDiscriminatorFromDiscriminator().
Referenced by cloneByMultiplyingDuplicationFactor(), cloneWithBaseDiscriminator(), llvm::sampleprof::FunctionSamples::getCallSiteIdentifier(), and llvm::SampleProfileLoaderBaseImpl< MachineBasicBlock >::getInstWeightImpl().
getBaseDiscriminatorBits()
static unsigned llvm::DILocation::getBaseDiscriminatorBits () inline static
Return the bits used for base discriminators.
Definition at line 1789 of file DebugInfoMetadata.h.
References llvm::getBaseFSBitEnd().
Referenced by getBaseDiscriminatorFromDiscriminator().
getBaseDiscriminatorFromDiscriminator()
static unsigned llvm::DILocation::getBaseDiscriminatorFromDiscriminator (unsigned D, bool IsFSDiscriminator = false) inline static
Returns the base discriminator for a given encoded discriminator D.
Definition at line 1793 of file DebugInfoMetadata.h.
References D, getBaseDiscriminatorBits(), getMaskedDiscriminator(), and getUnsignedFromPrefixEncoding().
Referenced by getBaseDiscriminator().
getCopyIdentifier()
unsigned llvm::DILocation::getCopyIdentifier () const inline
Returns the copy identifier stored in the discriminator.
Definition at line 2273 of file DebugInfoMetadata.h.
References getCopyIdentifierFromDiscriminator().
Referenced by cloneByMultiplyingDuplicationFactor().
getCopyIdentifierFromDiscriminator()
static unsigned llvm::DILocation::getCopyIdentifierFromDiscriminator (unsigned D) inline static
Returns the copy identifier for a given encoded discriminator D.
Definition at line 1833 of file DebugInfoMetadata.h.
References D, getNextComponentInDiscriminator(), and getUnsignedFromPrefixEncoding().
Referenced by getCopyIdentifier().
getDuplicationFactor()
unsigned llvm::DILocation::getDuplicationFactor () const inline
Returns the duplication factor stored in the discriminator, or 1 if no duplication factor (or 0) is encoded.
Definition at line 2269 of file DebugInfoMetadata.h.
References getDuplicationFactorFromDiscriminator().
Referenced by cloneByMultiplyingDuplicationFactor().
getDuplicationFactorFromDiscriminator()
static unsigned llvm::DILocation::getDuplicationFactorFromDiscriminator (unsigned D) inline static
Returns the duplication factor for a given encoded discriminator D, or 1 if no value or 0 is encoded.
Definition at line 1822 of file DebugInfoMetadata.h.
References D, llvm::EnableFSDiscriminator, getNextComponentInDiscriminator(), getUnsignedFromPrefixEncoding(), and llvm::MipsISD::Ret.
Referenced by getDuplicationFactor().
getMaskedDiscriminator()
static unsigned llvm::DILocation::getMaskedDiscriminator (unsigned D, unsigned B) inline static
Return the masked discriminator value for an input discrimnator value D (i.e.
zero out the (B+1)-th and above bits for D (B is 0-base).
Definition at line 1784 of file DebugInfoMetadata.h.
References B, D, and llvm::getN1Bits().
Referenced by getBaseDiscriminatorFromDiscriminator().
getMergedLocation()
const DILocation * DILocation::getMergedLocation (const DILocation * LocA, const DILocation * LocB) static
When two instructions are combined into a single instruction we also need to combine the original locations into a single location.
When the locations are the same we can use either location. When they differ, we need a third location which is distinct from either. If they share a common scope, use this scope and compare the line/column pair of the locations with the common scope:
if both match, keep the line and column;
if only the line number matches, keep the line and set the column as 0;
otherwise set line and column as 0. If they do not share a common scope the location is ambiguous and can't be represented in a line entry. In this case, set line and column as 0 and use the scope of any location.
LocA LocB: The locations to be merged.
Definition at line 108 of file DebugInfoMetadata.cpp.
References llvm::MDNode::get(), llvm::MDNode::getContext(), Line, llvm::AArch64CC::LS, and S.
Referenced by llvm::Instruction::applyMergedLocation(), combineFPFusedMultiply(), llvm::MachineBasicBlock::findBranchDebugLoc(), getMergedLocations(), llvm::InstCombinerImpl::mergeStoreIntoSuccessor(), performBlockTailMerging(), and performSink().
getMergedLocations()
const DILocation * DILocation::getMergedLocations (ArrayRef< const DILocation * > Locs) static
Try to combine the vector of locations passed as input in a single one.
This function applies getMergedLocation() repeatedly left-to-right.
Locs: The locations to be merged.
Definition at line 94 of file DebugInfoMetadata.cpp.
References llvm::drop_begin(), llvm::ArrayRef< T >::empty(), getMergedLocation(), and llvm::ArrayRef< T >::size().
getRawInlinedAt()
Metadata* llvm::DILocation::getRawInlinedAt () const inline
Definition at line 1839 of file DebugInfoMetadata.h.
References llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
getRawScope()
Metadata* llvm::DILocation::getRawScope () const inline
Definition at line 1838 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
isPseudoProbeDiscriminator()
static bool llvm::DILocation::isPseudoProbeDiscriminator (unsigned Discriminator) inline static
Definition at line 1726 of file DebugInfoMetadata.h.
Referenced by llvm::extractProbeFromDiscriminator(), and llvm::setProbeDistributionFactor().
replaceOperandWith()
void llvm::DILocation::replaceOperandWith (unsigned I, Metadata * New) delete
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 1606 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 1607 of file DebugInfoMetadata.h.
Member Data Documentation
Column
unsigned unsigned llvm::DILocation::Column
Definition at line 1642 of file DebugInfoMetadata.h.
ImplicitCode
unsigned unsigned DILocalScope DILocation bool llvm::DILocation::ImplicitCode
Definition at line 1644 of file DebugInfoMetadata.h.
InlinedAt
unsigned unsigned DILocalScope DILocation* llvm::DILocation::InlinedAt = nullptr
Definition at line 1643 of file DebugInfoMetadata.h.
Line
unsigned llvm::DILocation::Line
Definition at line 1642 of file DebugInfoMetadata.h.
Referenced by getMergedLocation().
Scope
unsigned unsigned DILocalScope* llvm::DILocation::Scope
Definition at line 1642 of file DebugInfoMetadata.h.
Referenced by cloneWithDiscriminator().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp