LLVM: llvm::WebAssemblyRegisterInfo Class Reference
llvm::WebAssemblyRegisterInfo Class Reference final
#include "Target/WebAssembly/WebAssemblyRegisterInfo.h"
Public Member Functions
WebAssemblyRegisterInfo (const Triple &TT)
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
const uint32_t * getNoPreservedMask () const override
Detailed Description
Definition at line 28 of file WebAssemblyRegisterInfo.h.
Constructor & Destructor Documentation
WebAssemblyRegisterInfo()
WebAssemblyRegisterInfo::WebAssemblyRegisterInfo (const Triple & TT) explicit
Definition at line 35 of file WebAssemblyRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
bool WebAssemblyRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 53 of file WebAssemblyRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::tgtok::Def, llvm::ISD::FrameIndex, llvm::MachineFunction::getFrameInfo(), getFrameRegister(), llvm::MachineOperand::getImm(), llvm::WebAssembly::getNamedOperandIdx(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::WebAssemblyFrameLowering::getOpcAdd(), llvm::WebAssemblyFrameLowering::getOpcConst(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterInfo::getPointerRegClass(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::Register::isVirtual(), llvm::max(), MBB, MI, MRI, llvm::Offset, llvm::MachineOperand::setImm(), TII, and uint64_t.
getCalleeSavedRegs()
const MCPhysReg * WebAssemblyRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 39 of file WebAssemblyRegisterInfo.cpp.
getFrameRegister()
Register WebAssemblyRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 140 of file WebAssemblyRegisterInfo.cpp.
References llvm::WebAssemblyFunctionInfo::getFrameBaseVreg(), llvm::MachineFunction::getInfo(), llvm::WebAssemblyFrameLowering::hasFP(), and llvm::Triple::isArch64Bit().
Referenced by eliminateFrameIndex().
getNoPreservedMask()
const uint32_t* llvm::WebAssemblyRegisterInfo::getNoPreservedMask () const inline override
Definition at line 48 of file WebAssemblyRegisterInfo.h.
getPointerRegClass()
const TargetRegisterClass * WebAssemblyRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
Definition at line 154 of file WebAssemblyRegisterInfo.cpp.
References assert(), llvm::MachineFunction::getSubtarget(), and llvm::WebAssemblySubtarget::hasAddr64().
getReservedRegs()
BitVector WebAssemblyRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 45 of file WebAssemblyRegisterInfo.cpp.
References llvm::Reserved.
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyRegisterInfo.h
lib/Target/WebAssembly/WebAssemblyRegisterInfo.cpp