LLVM: llvm::LoopUnrollPass Class Reference
llvm::LoopUnrollPass Class Reference
Loop unroll pass that will support both full and partial unrolling.
#include "llvm/Transforms/Scalar/LoopUnrollPass.h"
Public Member Functions
LoopUnrollPass (LoopUnrollOptions UnrollOpts={})
This uses the target information (or flags) to control the thresholds for different unrolling stategies but supports all of them.
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< LoopUnrollPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopUnrollPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Loop unroll pass that will support both full and partial unrolling.
It is a function pass to have access to function and module analyses. It will also put loops into canonical form (simplified and LCSSA).
Definition at line 133 of file LoopUnrollPass.h.
Constructor & Destructor Documentation
LoopUnrollPass()
llvm::LoopUnrollPass::LoopUnrollPass (LoopUnrollOptions UnrollOpts = {}) inline explicit
This uses the target information (or flags) to control the thresholds for different unrolling stategies but supports all of them.
Definition at line 139 of file LoopUnrollPass.h.
Member Function Documentation
printPipeline()
void LoopUnrollPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 1650 of file LoopUnrollPass.cpp.
References llvm::LoopUnrollOptions::AllowPartial, llvm::LoopUnrollOptions::AllowPeeling, llvm::LoopUnrollOptions::AllowProfileBasedPeeling, llvm::LoopUnrollOptions::AllowRuntime, llvm::LoopUnrollOptions::AllowUpperBound, llvm::LoopUnrollOptions::FullUnrollMaxCount, llvm::LoopUnrollOptions::OptLevel, and OS.
run()
PreservedAnalyses LoopUnrollPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 1564 of file LoopUnrollPass.cpp.
References llvm::PreservedAnalyses::all(), llvm::LoopUnrollOptions::AllowPartial, llvm::LoopUnrollOptions::AllowPeeling, llvm::LoopUnrollOptions::AllowProfileBasedPeeling, llvm::LoopUnrollOptions::AllowRuntime, llvm::LoopUnrollOptions::AllowUpperBound, llvm::appendLoopsToWorklist(), llvm::AMDGPUISD::BFI, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear(), llvm::PriorityWorklist< T, SmallVector< T, N >, SmallDenseMap< T, ptrdiff_t > >::empty(), llvm::LoopInfoBase< BlockT, LoopT >::empty(), F, llvm::LoopUnrollOptions::ForgetSCEV, llvm::formLCSSARecursively(), llvm::LoopUnrollOptions::FullUnrollMaxCount, llvm::FullyUnrolled, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::getLoopPassPreservedAnalyses(), llvm::Loop::getName(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), LAM, llvm::LoopUnrollOptions::OnlyWhenForced, llvm::LoopUnrollOptions::OptLevel, llvm::PriorityWorklist< T, SmallVector< T, N >, SmallDenseMap< T, ptrdiff_t > >::pop_back_val(), llvm::simplifyLoop(), tryToUnrollLoop(), llvm::Unmodified, and llvm::LoopBase< BlockT, LoopT >::verifyLoop().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopUnrollPass.h
lib/Transforms/Scalar/LoopUnrollPass.cpp