LLVM: llvm::hlsl::FrontendResource Class Reference
llvm::hlsl::FrontendResource Class Reference
#include "llvm/Frontend/HLSL/HLSLResource.h"
Public Member Functions
FrontendResource (MDNode *E)
FrontendResource (GlobalVariable *GV, StringRef TypeStr, ResourceKind RK, uint32_t ResIndex, uint32_t Space)
GlobalVariable * getGlobalVariable ()
StringRef getSourceType ()
uint32_t getResourceKind ()
uint32_t getResourceIndex ()
uint32_t getSpace ()
MDNode * getMetadata ()
Detailed Description
Definition at line 57 of file HLSLResource.h.
Constructor & Destructor Documentation
FrontendResource() [1/2]
llvm::hlsl::FrontendResource::FrontendResource (MDNode * E) inline
Definition at line 61 of file HLSLResource.h.
References assert().
FrontendResource() [2/2]
FrontendResource::FrontendResource (GlobalVariable * GV, StringRef TypeStr, ResourceKind RK, uint32_t ResIndex, uint32_t Space)
Definition at line 46 of file HLSLResource.cpp.
References B, llvm::ValueAsMetadata::get(), llvm::ConstantAsMetadata::get(), llvm::MDString::get(), llvm::MDNode::get(), and llvm::Value::getContext().
Member Function Documentation
getGlobalVariable()
GlobalVariable * FrontendResource::getGlobalVariable ()
Definition at line 21 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
getMetadata()
MDNode* llvm::hlsl::FrontendResource::getMetadata () inline
Definition at line 73 of file HLSLResource.h.
getResourceIndex()
uint32_t FrontendResource::getResourceIndex ()
Definition at line 35 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
getResourceKind()
uint32_t llvm::hlsl::FrontendResource::getResourceKind ()
getSourceType()
StringRef FrontendResource::getSourceType ()
Definition at line 26 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
getSpace()
uint32_t FrontendResource::getSpace ()
Definition at line 40 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
The documentation for this class was generated from the following files:
include/llvm/Frontend/HLSL/HLSLResource.h
lib/Frontend/HLSL/HLSLResource.cpp