LLVM: llvm::LoongArchMCExpr Class Reference
llvm::LoongArchMCExpr Class Reference
#include "Target/LoongArch/MCTargetDesc/LoongArchMCExpr.h"
Public Types
enum VariantKind {
VK_LoongArch_None, VK_LoongArch_CALL, VK_LoongArch_CALL_PLT, VK_LoongArch_B16,
VK_LoongArch_B21, VK_LoongArch_B26, VK_LoongArch_ABS_HI20, VK_LoongArch_ABS_LO12,
VK_LoongArch_ABS64_LO20, VK_LoongArch_ABS64_HI12, VK_LoongArch_PCALA_HI20, VK_LoongArch_PCALA_LO12,
VK_LoongArch_PCALA64_LO20, VK_LoongArch_PCALA64_HI12, VK_LoongArch_GOT_PC_HI20, VK_LoongArch_GOT_PC_LO12,
VK_LoongArch_GOT64_PC_LO20, VK_LoongArch_GOT64_PC_HI12, VK_LoongArch_GOT_HI20, VK_LoongArch_GOT_LO12,
VK_LoongArch_GOT64_LO20, VK_LoongArch_GOT64_HI12, VK_LoongArch_TLS_LE_HI20, VK_LoongArch_TLS_LE_LO12,
VK_LoongArch_TLS_LE64_LO20, VK_LoongArch_TLS_LE64_HI12, VK_LoongArch_TLS_IE_PC_HI20, VK_LoongArch_TLS_IE_PC_LO12,
VK_LoongArch_TLS_IE64_PC_LO20, VK_LoongArch_TLS_IE64_PC_HI12, VK_LoongArch_TLS_IE_HI20, VK_LoongArch_TLS_IE_LO12,
VK_LoongArch_TLS_IE64_LO20, VK_LoongArch_TLS_IE64_HI12, VK_LoongArch_TLS_LD_PC_HI20, VK_LoongArch_TLS_LD_HI20,
VK_LoongArch_TLS_GD_PC_HI20, VK_LoongArch_TLS_GD_HI20, VK_LoongArch_Invalid
}
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
VariantKind getKind () const
const MCExpr * getSubExpr () const
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static const LoongArchMCExpr * create (const MCExpr *Expr, VariantKind Kind, MCContext &Ctx)
static bool classof (const MCExpr *E)
static StringRef getVariantKindName (VariantKind Kind)
static VariantKind getVariantKindForName (StringRef name)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Definition at line 23 of file LoongArchMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::LoongArchMCExpr::VariantKind
Enumerator
VK_LoongArch_None
VK_LoongArch_CALL
VK_LoongArch_CALL_PLT
VK_LoongArch_B16
VK_LoongArch_B21
VK_LoongArch_B26
VK_LoongArch_ABS_HI20
VK_LoongArch_ABS_LO12
VK_LoongArch_ABS64_LO20
VK_LoongArch_ABS64_HI12
VK_LoongArch_PCALA_HI20
VK_LoongArch_PCALA_LO12
VK_LoongArch_PCALA64_LO20
VK_LoongArch_PCALA64_HI12
VK_LoongArch_GOT_PC_HI20
VK_LoongArch_GOT_PC_LO12
VK_LoongArch_GOT64_PC_LO20
VK_LoongArch_GOT64_PC_HI12
VK_LoongArch_GOT_HI20
VK_LoongArch_GOT_LO12
VK_LoongArch_GOT64_LO20
VK_LoongArch_GOT64_HI12
VK_LoongArch_TLS_LE_HI20
VK_LoongArch_TLS_LE_LO12
VK_LoongArch_TLS_LE64_LO20
VK_LoongArch_TLS_LE64_HI12
VK_LoongArch_TLS_IE_PC_HI20
VK_LoongArch_TLS_IE_PC_LO12
VK_LoongArch_TLS_IE64_PC_LO20
VK_LoongArch_TLS_IE64_PC_HI12
VK_LoongArch_TLS_IE_HI20
VK_LoongArch_TLS_IE_LO12
VK_LoongArch_TLS_IE64_LO20
VK_LoongArch_TLS_IE64_HI12
VK_LoongArch_TLS_LD_PC_HI20
VK_LoongArch_TLS_LD_HI20
VK_LoongArch_TLS_GD_PC_HI20
VK_LoongArch_TLS_GD_HI20
VK_LoongArch_Invalid
Definition at line 25 of file LoongArchMCExpr.h.
Member Function Documentation
classof()
static bool llvm::LoongArchMCExpr::classof (const MCExpr * E) inline static
Definition at line 91 of file LoongArchMCExpr.h.
References E, and llvm::MCExpr::Target.
create()
const LoongArchMCExpr * LoongArchMCExpr::create (const MCExpr * Expr, VariantKind Kind, MCContext & Ctx) static
Definition at line 29 of file LoongArchMCExpr.cpp.
Referenced by lowerSymbolOperand().
evaluateAsRelocatableImpl()
bool LoongArchMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 45 of file LoongArchMCExpr.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), llvm::MCValue::get(), llvm::MCValue::getConstant(), getKind(), getSubExpr(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), and VK_LoongArch_None.
findAssociatedFragment()
MCFragment* llvm::LoongArchMCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 85 of file LoongArchMCExpr.h.
References llvm::MCExpr::findAssociatedFragment(), and getSubExpr().
fixELFSymbolsInTLSFixups()
void LoongArchMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 211 of file LoongArchMCExpr.cpp.
References llvm::HexStyle::Asm, fixELFSymbolsInTLSFixupsImpl(), getKind(), getSubExpr(), VK_LoongArch_TLS_GD_HI20, VK_LoongArch_TLS_GD_PC_HI20, VK_LoongArch_TLS_IE_HI20, VK_LoongArch_TLS_IE_PC_HI20, VK_LoongArch_TLS_LD_HI20, VK_LoongArch_TLS_LD_PC_HI20, and VK_LoongArch_TLS_LE_HI20.
getKind()
VariantKind llvm::LoongArchMCExpr::getKind () const inline
Definition at line 78 of file LoongArchMCExpr.h.
Referenced by evaluateAsRelocatableImpl(), fixELFSymbolsInTLSFixups(), and printImpl().
getSubExpr()
const MCExpr* llvm::LoongArchMCExpr::getSubExpr () const inline
Definition at line 79 of file LoongArchMCExpr.h.
Referenced by evaluateAsRelocatableImpl(), findAssociatedFragment(), fixELFSymbolsInTLSFixups(), and visitUsedExpr().
getVariantKindForName()
LoongArchMCExpr::VariantKind LoongArchMCExpr::getVariantKindForName (StringRef name) static
Definition at line 144 of file LoongArchMCExpr.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), name, VK_LoongArch_ABS64_HI12, VK_LoongArch_ABS64_LO20, VK_LoongArch_ABS_HI20, VK_LoongArch_ABS_LO12, VK_LoongArch_B16, VK_LoongArch_B21, VK_LoongArch_B26, VK_LoongArch_CALL_PLT, VK_LoongArch_GOT64_HI12, VK_LoongArch_GOT64_LO20, VK_LoongArch_GOT64_PC_HI12, VK_LoongArch_GOT64_PC_LO20, VK_LoongArch_GOT_HI20, VK_LoongArch_GOT_LO12, VK_LoongArch_GOT_PC_HI20, VK_LoongArch_GOT_PC_LO12, VK_LoongArch_Invalid, VK_LoongArch_PCALA64_HI12, VK_LoongArch_PCALA64_LO20, VK_LoongArch_PCALA_HI20, VK_LoongArch_PCALA_LO12, VK_LoongArch_TLS_GD_HI20, VK_LoongArch_TLS_GD_PC_HI20, VK_LoongArch_TLS_IE64_HI12, VK_LoongArch_TLS_IE64_LO20, VK_LoongArch_TLS_IE64_PC_HI12, VK_LoongArch_TLS_IE64_PC_LO20, VK_LoongArch_TLS_IE_HI20, VK_LoongArch_TLS_IE_LO12, VK_LoongArch_TLS_IE_PC_HI20, VK_LoongArch_TLS_IE_PC_LO12, VK_LoongArch_TLS_LD_HI20, VK_LoongArch_TLS_LD_PC_HI20, VK_LoongArch_TLS_LE64_HI12, VK_LoongArch_TLS_LE64_LO20, VK_LoongArch_TLS_LE_HI20, and VK_LoongArch_TLS_LE_LO12.
getVariantKindName()
StringRef LoongArchMCExpr::getVariantKindName (VariantKind Kind) static
Definition at line 64 of file LoongArchMCExpr.cpp.
References llvm_unreachable, VK_LoongArch_ABS64_HI12, VK_LoongArch_ABS64_LO20, VK_LoongArch_ABS_HI20, VK_LoongArch_ABS_LO12, VK_LoongArch_B16, VK_LoongArch_B21, VK_LoongArch_B26, VK_LoongArch_CALL_PLT, VK_LoongArch_GOT64_HI12, VK_LoongArch_GOT64_LO20, VK_LoongArch_GOT64_PC_HI12, VK_LoongArch_GOT64_PC_LO20, VK_LoongArch_GOT_HI20, VK_LoongArch_GOT_LO12, VK_LoongArch_GOT_PC_HI20, VK_LoongArch_GOT_PC_LO12, VK_LoongArch_PCALA64_HI12, VK_LoongArch_PCALA64_LO20, VK_LoongArch_PCALA_HI20, VK_LoongArch_PCALA_LO12, VK_LoongArch_TLS_GD_HI20, VK_LoongArch_TLS_GD_PC_HI20, VK_LoongArch_TLS_IE64_HI12, VK_LoongArch_TLS_IE64_LO20, VK_LoongArch_TLS_IE64_PC_HI12, VK_LoongArch_TLS_IE64_PC_LO20, VK_LoongArch_TLS_IE_HI20, VK_LoongArch_TLS_IE_LO12, VK_LoongArch_TLS_IE_PC_HI20, VK_LoongArch_TLS_IE_PC_LO12, VK_LoongArch_TLS_LD_HI20, VK_LoongArch_TLS_LD_PC_HI20, VK_LoongArch_TLS_LE64_HI12, VK_LoongArch_TLS_LE64_LO20, VK_LoongArch_TLS_LE_HI20, and VK_LoongArch_TLS_LE_LO12.
Referenced by printImpl().
printImpl()
void LoongArchMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 33 of file LoongArchMCExpr.cpp.
References getKind(), getVariantKindName(), OS, llvm::MCExpr::print(), VK_LoongArch_CALL, and VK_LoongArch_None.
visitUsedExpr()
void LoongArchMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 60 of file LoongArchMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
lib/Target/LoongArch/MCTargetDesc/LoongArchMCExpr.h
lib/Target/LoongArch/MCTargetDesc/LoongArchMCExpr.cpp