LLVM: DOTFuncMSSAInfo Class Reference
DOTFuncMSSAInfo Class Reference
Public Member Functions
DOTFuncMSSAInfo (const Function &F, MemorySSA &MSSA)
const Function * getFunction ()
MemorySSAAnnotatedWriter & getWriter ()
Detailed Description
Definition at line 2234 of file MemorySSA.cpp.
Constructor & Destructor Documentation
DOTFuncMSSAInfo()
DOTFuncMSSAInfo::DOTFuncMSSAInfo (const Function & F, MemorySSA & MSSA) inline
Definition at line 2240 of file MemorySSA.cpp.
Member Function Documentation
getFunction()
const Function* DOTFuncMSSAInfo::getFunction () inline
Definition at line 2243 of file MemorySSA.cpp.
References F.
Referenced by llvm::GraphTraits< DOTFuncMSSAInfo * >::getEntryNode(), llvm::DOTGraphTraits< DOTFuncMSSAInfo * >::getGraphName(), llvm::GraphTraits< DOTFuncMSSAInfo * >::nodes_begin(), llvm::GraphTraits< DOTFuncMSSAInfo * >::nodes_end(), and llvm::GraphTraits< DOTFuncMSSAInfo * >::size().
getWriter()
MemorySSAAnnotatedWriter& DOTFuncMSSAInfo::getWriter () inline
Definition at line 2244 of file MemorySSA.cpp.
The documentation for this class was generated from the following file:
lib/Analysis/MemorySSA.cpp