LLVM: llvm::pdb::NativeSourceFile Class Reference
llvm::pdb::NativeSourceFile Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeSourceFile.h"
Public Member Functions
NativeSourceFile (NativeSession &Session, uint32_t FileId, const codeview::FileChecksumEntry &Checksum)
std::string getFileName () const override
uint32_t getUniqueId () const override
std::string getChecksum () const override
PDB_Checksum getChecksumType () const override
std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > getCompilands () const override
Public Member Functions inherited from llvm::pdb::IPDBSourceFile
virtual ~IPDBSourceFile ()
void dump (raw_ostream &OS, int Indent) const
Detailed Description
Definition at line 22 of file NativeSourceFile.h.
Constructor & Destructor Documentation
NativeSourceFile()
NativeSourceFile::NativeSourceFile (NativeSession & Session, uint32_t FileId, const codeview::FileChecksumEntry & Checksum) explicit
Definition at line 17 of file NativeSourceFile.cpp.
Member Function Documentation
getChecksum()
std::string NativeSourceFile::getChecksum () const override virtual
Implements llvm::pdb::IPDBSourceFile.
Definition at line 38 of file NativeSourceFile.cpp.
References llvm::codeview::FileChecksumEntry::Checksum, llvm::StringRef::str(), and llvm::dwarf::toStringRef().
getChecksumType()
PDB_Checksum NativeSourceFile::getChecksumType () const override virtual
Implements llvm::pdb::IPDBSourceFile.
Definition at line 42 of file NativeSourceFile.cpp.
References llvm::codeview::FileChecksumEntry::Kind.
getCompilands()
std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > NativeSourceFile::getCompilands () const override virtual
Implements llvm::pdb::IPDBSourceFile.
Definition at line 47 of file NativeSourceFile.cpp.
getFileName()
std::string NativeSourceFile::getFileName () const override virtual
Implements llvm::pdb::IPDBSourceFile.
Definition at line 21 of file NativeSourceFile.cpp.
References llvm::consumeError(), llvm::codeview::FileChecksumEntry::FileNameOffset, llvm::pdb::NativeSession::getPDBFile(), llvm::pdb::PDBFile::getStringTable(), and llvm::ARM_MB::ST.
getUniqueId()
uint32_t NativeSourceFile::getUniqueId () const override virtual
Implements llvm::pdb::IPDBSourceFile.
Definition at line 36 of file NativeSourceFile.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeSourceFile.h
lib/DebugInfo/PDB/Native/NativeSourceFile.cpp