LLVM: llvm::LiveRegMatrix Class Reference
llvm::LiveRegMatrix Class Reference
#include "llvm/CodeGen/LiveRegMatrix.h"
Public Types
enum InterferenceKind { IK_Free = 0, IK_VirtReg, IK_RegUnit, IK_RegMask }
Public Member Functions
LiveRegMatrix ()
void invalidateVirtRegs ()
Invalidate cached interference queries after modifying virtual register live ranges.
InterferenceKind checkInterference (const LiveInterval &VirtReg, MCRegister PhysReg)
Check for interference before assigning VirtReg to PhysReg.
bool checkInterference (SlotIndex Start, SlotIndex End, MCRegister PhysReg)
Check for interference in the segment [Start, End) that may prevent assignment to PhysReg.
void assign (const LiveInterval &VirtReg, MCRegister PhysReg)
Assign VirtReg to PhysReg.
void unassign (const LiveInterval &VirtReg)
Unassign VirtReg from its PhysReg.
bool isPhysRegUsed (MCRegister PhysReg) const
Returns true if the given PhysReg has any live intervals assigned.
bool checkRegMaskInterference (const LiveInterval &VirtReg, MCRegister PhysReg=MCRegister::NoRegister)
Check for regmask interference only.
bool checkRegUnitInterference (const LiveInterval &VirtReg, MCRegister PhysReg)
Check for regunit interference only.
LiveIntervalUnion::Query & query (const LiveRange &LR, MCRegister RegUnit)
Query a line of the assigned virtual register matrix directly.
LiveIntervalUnion * getLiveUnions ()
Directly access the live interval unions per regunit.
Register getOneVReg (unsigned PhysReg) const
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 40 of file LiveRegMatrix.h.
Member Enumeration Documentation
InterferenceKind
enum llvm::LiveRegMatrix::InterferenceKind
Enumerator
IK_Free
No interference, go ahead and assign.
IK_VirtReg
Virtual register interference.
There are interfering virtual registers assigned to PhysReg or its aliases. This interference could be resolved by unassigning those other virtual registers.
IK_RegUnit
Register unit interference.
A fixed live range is in the way, typically argument registers for a call. This can't be resolved by unassigning other virtual registers.
IK_RegMask
RegMask interference.
The live range is crossing an instruction with a regmask operand that doesn't preserve PhysReg. This typically means VirtReg is live across a call, and PhysReg isn't call-preserved.
Definition at line 83 of file LiveRegMatrix.h.
Constructor & Destructor Documentation
LiveRegMatrix()
Live Register false LiveRegMatrix::LiveRegMatrix ()
Definition at line 46 of file LiveRegMatrix.cpp.
Member Function Documentation
assign()
void LiveRegMatrix::assign (const LiveInterval & VirtReg, MCRegister PhysReg)
Assign VirtReg to PhysReg.
This will mark VirtReg's live range as occupied in the LiveRegMatrix and update VirtRegMap. The live range is expected to be available in PhysReg.
Definition at line 104 of file LiveRegMatrix.cpp.
References assert(), llvm::VirtRegMap::assignVirt2Phys(), llvm::dbgs(), foreachUnit(), llvm::VirtRegMap::hasPhys(), LLVM_DEBUG, llvm::printReg(), llvm::printRegUnit(), and llvm::LiveInterval::reg().
Referenced by llvm::RegAllocBase::allocatePhysRegs().
checkInterference() [1/2]
LiveRegMatrix::InterferenceKind LiveRegMatrix::checkInterference (const LiveInterval & VirtReg, MCRegister PhysReg)
Check for interference before assigning VirtReg to PhysReg.
If this function returns IK_Free, it is legal to assign(VirtReg, PhysReg). When there is more than one kind of interference, the InterferenceKind with the highest enum value is returned.
Definition at line 186 of file LiveRegMatrix.cpp.
References llvm::LiveIntervalUnion::Query::checkInterference(), checkRegMaskInterference(), checkRegUnitInterference(), llvm::LiveRange::empty(), foreachUnit(), IK_Free, IK_RegMask, IK_RegUnit, IK_VirtReg, and query().
checkInterference() [2/2]
bool LiveRegMatrix::checkInterference (SlotIndex Start, SlotIndex End, MCRegister PhysReg)
Check for interference in the segment [Start, End) that may prevent assignment to PhysReg.
If this function returns true, there is interference in the segment [Start, End) of some other interval already assigned to PhysReg. If this function returns false, PhysReg is free at the segment [Start, End).
Definition at line 210 of file LiveRegMatrix.cpp.
checkRegMaskInterference()
bool LiveRegMatrix::checkRegMaskInterference (const LiveInterval & VirtReg, MCRegister PhysReg = MCRegister::NoRegister)
Check for regmask interference only.
Return true if VirtReg crosses a regmask operand that clobbers PhysReg. If PhysReg is null, check if VirtReg crosses any regmask operands.
Definition at line 146 of file LiveRegMatrix.cpp.
References llvm::LiveIntervals::checkRegMaskInterference(), llvm::BitVector::clear(), llvm::BitVector::empty(), llvm::LiveInterval::reg(), and llvm::BitVector::test().
Referenced by checkInterference().
checkRegUnitInterference()
bool LiveRegMatrix::checkRegUnitInterference (const LiveInterval & VirtReg, MCRegister PhysReg)
Check for regunit interference only.
Return true if VirtReg overlaps a fixed assignment of one of PhysRegs's register units.
Definition at line 164 of file LiveRegMatrix.cpp.
References llvm::HexagonISD::CP, llvm::LiveRange::empty(), foreachUnit(), llvm::LiveIntervals::getRegUnit(), llvm::LiveIntervals::getSlotIndexes(), and llvm::LiveInterval::reg().
Referenced by checkInterference().
getLiveUnions()
LiveIntervalUnion* llvm::LiveRegMatrix::getLiveUnions () inline
Directly access the live interval unions per regunit.
This returns an array indexed by the regunit number.
Definition at line 157 of file LiveRegMatrix.h.
References Matrix.
Referenced by llvm::RegAllocEvictionAdvisor::canReassign(), and llvm::RAGreedy::runOnMachineFunction().
getOneVReg()
Register LiveRegMatrix::getOneVReg (unsigned PhysReg) const
Definition at line 240 of file LiveRegMatrix.cpp.
References llvm::MCRegister::NoRegister, and llvm::LiveInterval::reg().
invalidateVirtRegs()
void llvm::LiveRegMatrix::invalidateVirtRegs () inline
Invalidate cached interference queries after modifying virtual register live ranges.
Interference checks may return stale information unless caches are invalidated.
Definition at line 81 of file LiveRegMatrix.h.
Referenced by llvm::RegAllocBase::allocatePhysRegs().
isPhysRegUsed()
bool LiveRegMatrix::isPhysRegUsed (MCRegister PhysReg) const
Returns true if the given PhysReg has any live intervals assigned.
Definition at line 138 of file LiveRegMatrix.cpp.
Referenced by llvm::RegAllocEvictionAdvisor::isUnusedCalleeSavedReg().
query()
LiveIntervalUnion::Query & LiveRegMatrix::query (const LiveRange & LR, MCRegister RegUnit)
Query a line of the assigned virtual register matrix directly.
Use MCRegUnitIterator to enumerate all regunits in the desired PhysReg. This returns a reference to an internal Query data structure that is only valid until the next query() call.
Definition at line 178 of file LiveRegMatrix.cpp.
References llvm::LiveIntervalUnion::Query::init().
Referenced by checkInterference().
unassign()
void LiveRegMatrix::unassign (const LiveInterval & VirtReg)
Unassign VirtReg from its PhysReg.
Assuming that VirtReg was previously assigned to a PhysReg, this undoes the assignment and updates VirtRegMap accordingly.
Definition at line 121 of file LiveRegMatrix.cpp.
References llvm::VirtRegMap::clearVirt(), llvm::dbgs(), foreachUnit(), llvm::VirtRegMap::getPhys(), LLVM_DEBUG, llvm::printReg(), llvm::printRegUnit(), and llvm::LiveInterval::reg().
Member Data Documentation
ID
char LiveRegMatrix::ID = 0 static
Definition at line 66 of file LiveRegMatrix.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveRegMatrix.h
lib/CodeGen/LiveRegMatrix.cpp