LLVM: lib/Transforms/Coroutines/CoroSplit.cpp File Reference
CoroSplit.cpp File Reference
#include "llvm/Transforms/Coroutines/CoroSplit.h"
#include "CoroInstr.h"
#include "CoroInternal.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PriorityWorklist.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/LazyCallGraph.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/CallGraphUpdater.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <iterator>
Macros
#define DEBUG_TYPE "coro-split"
Functions
static void maybeFreeRetconStorage (IRBuilder<> &Builder, const coro::Shape &Shape, Value *FramePtr, CallGraph *CG)
static bool replaceCoroEndAsync (AnyCoroEndInst *End)
Replace an llvm.coro.end.async.
static void replaceFallthroughCoroEnd (AnyCoroEndInst *End, const coro::Shape &Shape, Value *FramePtr, bool InResume, CallGraph *CG)
Replace a non-unwind call to llvm.coro.end.
static void markCoroutineAsDone (IRBuilder<> &Builder, const coro::Shape &Shape, Value *FramePtr)
static void replaceUnwindCoroEnd (AnyCoroEndInst *End, const coro::Shape &Shape, Value *FramePtr, bool InResume, CallGraph *CG)
Replace an unwind call to llvm.coro.end.
static void replaceCoroEnd (AnyCoroEndInst *End, const coro::Shape &Shape, Value *FramePtr, bool InResume, CallGraph *CG)
static void createResumeEntryBlock (Function &F, coro::Shape &Shape)
static FunctionType * getFunctionTypeFromAsyncSuspend (AnyCoroSuspendInst *Suspend)
static Function * createCloneDeclaration (Function &OrigF, coro::Shape &Shape, const Twine &Suffix, Module::iterator InsertBefore, AnyCoroSuspendInst *ActiveSuspend)
static void replaceSwiftErrorOps (Function &F, coro::Shape &Shape, ValueToValueMapTy *VMap)
static void addFramePointerAttrs (AttributeList &Attrs, LLVMContext &Context, unsigned ParamIndex, uint64_t Size, Align Alignment, bool NoAlias)
static void addAsyncContextAttrs (AttributeList &Attrs, LLVMContext &Context, unsigned ParamIndex)
static void addSwiftSelfAttrs (AttributeList &Attrs, LLVMContext &Context, unsigned ParamIndex)
static Function * createClone (Function &F, const Twine &Suffix, coro::Shape &Shape, CoroCloner::Kind FKind)
static void updateAsyncFuncPointerContextSize (coro::Shape &Shape)
static void replaceFrameSizeAndAlignment (coro::Shape &Shape)
static void setCoroInfo (Function &F, coro::Shape &Shape, ArrayRef< Function * > Fns)
static void updateCoroFrame (coro::Shape &Shape, Function *ResumeFn, Function *DestroyFn, Function *CleanupFn)
static void postSplitCleanup (Function &F)
static void scanPHIsAndUpdateValueMap (Instruction *Prev, BasicBlock *NewBlock, DenseMap< Value *, Value * > &ResolvedValues)
static bool simplifyTerminatorLeadingToRet (Instruction *InitialInst)
static bool shouldBeMustTail (const CallInst &CI, const Function &F)
static void addMustTailToCoroResumes (Function &F, TargetTransformInfo &TTI)
static void handleNoSuspendCoroutine (coro::Shape &Shape)
static bool hasCallsInBlockBetween (Instruction *From, Instruction *To)
static bool hasCallsInBlocksBetween (BasicBlock *SaveBB, BasicBlock *ResDesBB)
static bool hasCallsBetween (Instruction *Save, Instruction *ResumeOrDestroy)
static bool simplifySuspendPoint (CoroSuspendInst *Suspend, CoroBeginInst *CoroBegin)
static void simplifySuspendPoints (coro::Shape &Shape)
static void splitSwitchCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones, TargetTransformInfo &TTI)
static void replaceAsyncResumeFunction (CoroSuspendAsyncInst *Suspend, Value *Continuation)
static void coerceArguments (IRBuilder<> &Builder, FunctionType *FnTy, ArrayRef< Value * > FnArgs, SmallVectorImpl< Value * > &CallArgs)
Coerce the arguments in FnArgs according to FnTy in CallArgs.
static void splitAsyncCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones)
static void splitRetconCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones)
static coro::Shape splitCoroutine (Function &F, SmallVectorImpl< Function * > &Clones, TargetTransformInfo &TTI, bool OptimizeFrame, std::function< bool(Instruction &)> MaterializableCallback)
static void removeCoroEnds (const coro::Shape &Shape)
Remove calls to llvm.coro.end in the original function.
static void updateCallGraphAfterCoroutineSplit (LazyCallGraph::Node &N, const coro::Shape &Shape, const SmallVectorImpl< Function * > &Clones, LazyCallGraph::SCC &C, LazyCallGraph &CG, CGSCCAnalysisManager &AM, CGSCCUpdateResult &UR, FunctionAnalysisManager &FAM)
static void replacePrepare (CallInst *Prepare, LazyCallGraph &CG, LazyCallGraph::SCC &C)
Replace a call to llvm.coro.prepare.retcon.
static bool replaceAllPrepares (Function *PrepareFn, LazyCallGraph &CG, LazyCallGraph::SCC &C)
static void addPrepareFunction (const Module &M, SmallVectorImpl< Function * > &Fns, StringRef Name)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coro-split"
Definition at line 77 of file CoroSplit.cpp.
Function Documentation
addAsyncContextAttrs()
static void addAsyncContextAttrs (AttributeList & Attrs, LLVMContext & Context, unsigned ParamIndex) static
Definition at line 859 of file CoroSplit.cpp.
References llvm::AttrBuilder::addAttribute(), Attrs, and Context.
addFramePointerAttrs()
static void addFramePointerAttrs (AttributeList & Attrs, LLVMContext & Context, unsigned ParamIndex, uint64_t Size, Align Alignment, bool NoAlias) static
Definition at line 844 of file CoroSplit.cpp.
References llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addAttribute(), llvm::AttrBuilder::addDereferenceableAttr(), Attrs, and Context.
addMustTailToCoroResumes()
static void addMustTailToCoroResumes (Function & F, TargetTransformInfo & TTI) static
Definition at line 1379 of file CoroSplit.cpp.
References F, I, llvm::instructions(), llvm::removeUnreachableBlocks(), shouldBeMustTail(), simplifyTerminatorLeadingToRet(), llvm::TargetTransformInfo::supportsTailCallFor(), and llvm::CallInst::TCK_MustTail.
Referenced by splitSwitchCoroutine().
addPrepareFunction()
static void addPrepareFunction (const Module & M, SmallVectorImpl< Function * > & Fns, StringRef Name) static
Definition at line 2099 of file CoroSplit.cpp.
References M.
Referenced by llvm::CoroSplitPass::run().
addSwiftSelfAttrs()
static void addSwiftSelfAttrs (AttributeList & Attrs, LLVMContext & Context, unsigned ParamIndex) static
Definition at line 866 of file CoroSplit.cpp.
References llvm::AttrBuilder::addAttribute(), Attrs, and Context.
coerceArguments()
static void coerceArguments (IRBuilder<> & Builder, FunctionType * FnTy, ArrayRef< Value * > FnArgs, SmallVectorImpl< Value * > & CallArgs) static
Coerce the arguments in FnArgs according to FnTy in CallArgs.
Definition at line 1660 of file CoroSplit.cpp.
References assert(), Builder, getType(), llvm::FunctionType::params(), and llvm::ArrayRef< T >::size().
Referenced by llvm::coro::createMustTailCall().
createClone()
static Function* createClone (Function & F, const Twine & Suffix, coro::Shape & Shape, CoroCloner::Kind FKind) static
Definition at line 1092 of file CoroSplit.cpp.
References F.
Referenced by splitSwitchCoroutine().
createCloneDeclaration()
static Function* createCloneDeclaration (Function & OrigF, coro::Shape & Shape, const Twine & Suffix, Module::iterator InsertBefore, AnyCoroSuspendInst * ActiveSuspend) static
Definition at line 507 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Async, llvm::Function::Create(), getFunctionTypeFromAsyncSuspend(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::coro::Shape::getResumeFunctionType(), and M.
Referenced by splitRetconCoroutine().
createResumeEntryBlock()
static void createResumeEntryBlock (Function & F, coro::Shape & Shape) static
Definition at line 358 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, llvm::coro::Shape::CoroSuspends, llvm::BasicBlock::Create(), llvm::PHINode::Create(), F, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::ConstantTokenNone::get(), llvm::coro::Shape::getIndex(), llvm::coro::Shape::getIndexType(), llvm::coro::Shape::getSwitchIndexField(), llvm::coro::Shape::SwitchLoweringStorage::HasUnwindCoroEnd, markCoroutineAsDone(), llvm::coro::Shape::SwitchLoweringStorage::ResumeEntryBlock, llvm::coro::Shape::SwitchLoweringStorage::ResumeSwitch, S, llvm::coro::Switch, and llvm::coro::Shape::SwitchLowering.
Referenced by splitSwitchCoroutine().
getFunctionTypeFromAsyncSuspend()
static FunctionType* getFunctionTypeFromAsyncSuspend (AnyCoroSuspendInst * Suspend) static
Definition at line 499 of file CoroSplit.cpp.
References Context, llvm::FunctionType::get(), llvm::Function::getContext(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), and llvm::Type::getVoidTy().
Referenced by createCloneDeclaration().
handleNoSuspendCoroutine()
static void handleNoSuspendCoroutine (coro::Shape & Shape) static
Definition at line 1404 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Async, Builder, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::FrameAlign, llvm::coro::Shape::FrameTy, llvm::UndefValue::get(), llvm::AnyCoroIdInst::getCoroAlloc(), llvm::CoroBeginInst::getId(), llvm::coro::replaceCoroFree(), llvm::coro::Retcon, llvm::coro::RetconOnce, and llvm::coro::Switch.
Referenced by splitCoroutine().
hasCallsBetween()
static bool hasCallsBetween (Instruction * Save, Instruction * ResumeOrDestroy) static
Definition at line 1480 of file CoroSplit.cpp.
References llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getParent(), hasCallsInBlockBetween(), and hasCallsInBlocksBetween().
Referenced by simplifySuspendPoint().
hasCallsInBlockBetween()
static bool hasCallsInBlockBetween (Instruction * From, Instruction * To) static
Definition at line 1439 of file CoroSplit.cpp.
References From, and I.
Referenced by hasCallsBetween(), and hasCallsInBlocksBetween().
hasCallsInBlocksBetween()
static bool hasCallsInBlocksBetween (BasicBlock * SaveBB, BasicBlock * ResDesBB) static
Definition at line 1451 of file CoroSplit.cpp.
References BB, llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::SmallPtrSetImpl< PtrType >::erase(), hasCallsInBlockBetween(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::predecessors().
Referenced by hasCallsBetween().
markCoroutineAsDone()
static void markCoroutineAsDone (IRBuilder<> & Builder, const coro::Shape & Shape, Value * FramePtr) static
Definition at line 291 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, llvm::coro::Shape::FrameTy, llvm::ConstantPointerNull::get(), llvm::StructType::getTypeAtIndex(), llvm::coro::Shape::SwitchFieldIndex::Resume, and llvm::coro::Switch.
Referenced by createResumeEntryBlock().
maybeFreeRetconStorage()
static void maybeFreeRetconStorage (IRBuilder<> & Builder, const coro::Shape & Shape, Value * FramePtr, CallGraph * CG) static
Definition at line 169 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, llvm::coro::Shape::emitDealloc(), llvm::coro::Shape::RetconLoweringStorage::IsFrameInlineInStorage, llvm::coro::Retcon, llvm::coro::Shape::RetconLowering, and llvm::coro::RetconOnce.
postSplitCleanup()
static void postSplitCleanup (Function & F) static
Definition at line 1201 of file CoroSplit.cpp.
References llvm::errs(), F, llvm::removeUnreachableBlocks(), llvm::report_fatal_error(), and llvm::verifyFunction().
Referenced by splitSwitchCoroutine().
removeCoroEnds()
static void removeCoroEnds (const coro::Shape & Shape) static
Remove calls to llvm.coro.end in the original function.
Definition at line 1997 of file CoroSplit.cpp.
Referenced by updateCallGraphAfterCoroutineSplit().
replaceAllPrepares()
static bool replaceAllPrepares (Function * PrepareFn, LazyCallGraph & CG, LazyCallGraph::SCC & C) static
Definition at line 2086 of file CoroSplit.cpp.
References llvm::make_early_inc_range(), P, replacePrepare(), and llvm::Value::uses().
Referenced by llvm::CoroSplitPass::run().
replaceAsyncResumeFunction()
static void replaceAsyncResumeFunction (CoroSuspendAsyncInst * Suspend, Value * Continuation) static
Definition at line 1645 of file CoroSplit.cpp.
References Builder, Context, llvm::UndefValue::get(), llvm::Function::getContext(), llvm::Type::getInt8PtrTy(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::CoroSuspendAsyncInst::getResumeFunction(), llvm::CoroSuspendAsyncInst::ResumeFunctionArg, and llvm::User::setOperand().
replaceCoroEnd()
static void replaceCoroEnd (AnyCoroEndInst * End, const coro::Shape & Shape, Value * FramePtr, bool InResume, CallGraph * CG) static
Definition at line 343 of file CoroSplit.cpp.
replaceCoroEndAsync()
static bool replaceCoroEndAsync (AnyCoroEndInst * End) static
Replace an llvm.coro.end.async.
Will inline the must tail call function call if there is one.
Returns
true if cleanup of the coro.end block is needed, false otherwise.
Definition at line 183 of file CoroSplit.cpp.
replaceFallthroughCoroEnd()
static void replaceFallthroughCoroEnd (AnyCoroEndInst * End, const coro::Shape & Shape, Value * FramePtr, bool InResume, CallGraph * CG) static
Replace a non-unwind call to llvm.coro.end.
Definition at line 226 of file CoroSplit.cpp.
replaceFrameSizeAndAlignment()
static void replaceFrameSizeAndAlignment (coro::Shape & Shape) static
Definition at line 1114 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Async, llvm::coro::Shape::CoroAligns, llvm::coro::Shape::CoroSizes, DL, llvm::Instruction::eraseFromParent(), llvm::coro::Shape::FrameAlign, llvm::coro::Shape::FrameTy, llvm::ConstantInt::get(), llvm::Value::getType(), M, llvm::Value::replaceAllUsesWith(), updateAsyncFuncPointerContextSize(), and llvm::Align::value().
Referenced by splitCoroutine().
replacePrepare()
static void replacePrepare (CallInst * Prepare, LazyCallGraph & CG, LazyCallGraph::SCC & C) static
Replace a call to llvm.coro.prepare.retcon.
Definition at line 2050 of file CoroSplit.cpp.
References llvm::Instruction::eraseFromParent(), llvm::CallBase::getArgOperand(), llvm::make_early_inc_range(), llvm::Value::replaceAllUsesWith(), llvm::Value::stripPointerCasts(), and llvm::Value::uses().
Referenced by replaceAllPrepares().
replaceSwiftErrorOps()
static void replaceSwiftErrorOps (Function & F, coro::Shape & Shape, ValueToValueMapTy * VMap) static
Definition at line 620 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, Arg, assert(), llvm::coro::Async, Builder, llvm::coro::Shape::CoroSuspends, F, llvm::Value::getType(), and llvm::coro::Shape::SwiftErrorOps.
Referenced by splitCoroutine().
replaceUnwindCoroEnd()
static void replaceUnwindCoroEnd (AnyCoroEndInst * End, const coro::Shape & Shape, Value * FramePtr, bool InResume, CallGraph * CG) static
Replace an unwind call to llvm.coro.end.
Definition at line 305 of file CoroSplit.cpp.
scanPHIsAndUpdateValueMap()
static void scanPHIsAndUpdateValueMap (Instruction * Prev, BasicBlock * NewBlock, DenseMap< Value *, Value * > & ResolvedValues) static
Definition at line 1216 of file CoroSplit.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::Instruction::getParent(), llvm::BasicBlock::phis(), and VI.
Referenced by simplifyTerminatorLeadingToRet().
setCoroInfo()
static void setCoroInfo (Function & F, coro::Shape & Shape, ArrayRef< Function * > Fns) static
Definition at line 1151 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::AMDGPU::HSAMD::Kernel::Key::Args, assert(), llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), F, llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::Type::getInt8PtrTy(), llvm::GlobalValue::getParent(), llvm::ConstantExpr::getPointerCast(), llvm::coro::Shape::getSwitchCoroId(), llvm::GlobalValue::getType(), M, llvm::GlobalValue::PrivateLinkage, llvm::CoroIdInst::setInfo(), and llvm::coro::Switch.
Referenced by splitSwitchCoroutine().
shouldBeMustTail()
static bool shouldBeMustTail (const CallInst & CI, const Function & F) static
Definition at line 1344 of file CoroSplit.cpp.
References Attrs, F, llvm::CallBase::getAttributes(), llvm::CallBase::getCallingConv(), llvm::CallBase::getFunctionType(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::Type::getPointerAddressSpace(), llvm::FunctionType::getReturnType(), llvm::CallBase::isInlineAsm(), llvm::Type::isPointerTy(), and llvm::Type::isVoidTy().
Referenced by addMustTailToCoroResumes().
simplifySuspendPoint()
static bool simplifySuspendPoint (CoroSuspendInst * Suspend, CoroBeginInst * CoroBegin) static
Definition at line 1505 of file CoroSplit.cpp.
References Callee, llvm::BranchInst::Create(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getCalledOperand(), llvm::CoroSuspendInst::getCoroSave(), llvm::Instruction::getParent(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::BasicBlock::getSinglePredecessor(), hasCallsBetween(), I, llvm::Value::replaceAllUsesWith(), and llvm::Value::stripPointerCasts().
Referenced by simplifySuspendPoints().
simplifySuspendPoints()
static void simplifySuspendPoints (coro::Shape & Shape) static
Definition at line 1565 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, llvm::coro::Shape::SwitchLoweringStorage::HasFinalSuspend, I, llvm::max(), N, S, SI, simplifySuspendPoint(), std::swap(), llvm::coro::Switch, and llvm::coro::Shape::SwitchLowering.
Referenced by splitCoroutine().
simplifyTerminatorLeadingToRet()
static bool simplifyTerminatorLeadingToRet (Instruction * InitialInst) static
Definition at line 1233 of file CoroSplit.cpp.
References assert(), BB, llvm::ISD::BR, Cond, llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldTerminator(), DL, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::Module::getDataLayout(), llvm::BasicBlock::getFirstNonPHIOrDbgOrLifetime(), llvm::Instruction::getModule(), llvm::Instruction::getParent(), I, llvm::isInstructionTriviallyDead(), llvm::BasicBlock::removePredecessor(), llvm::ReplaceInstWithInst(), scanPHIsAndUpdateValueMap(), and SI.
Referenced by addMustTailToCoroResumes().
splitAsyncCoroutine()
static void splitAsyncCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones) static
Definition at line 1691 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), llvm::coro::Async, llvm::coro::Shape::AsyncLowering, Builder, Context, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, F, llvm::coro::Shape::AsyncLoweringStorage::FrameOffset, llvm::coro::Shape::FramePtr, llvm::CoroBeginInst::getId(), llvm::Type::getInt8PtrTy(), llvm::Type::getInt8Ty(), llvm::TrackingVH< ValueTy >::getValPtr(), llvm::Value::replaceAllUsesWith(), and llvm::SmallVectorImpl< T >::reserve().
Referenced by splitCoroutine().
splitCoroutine()
static coro::Shape splitCoroutine (Function & F, SmallVectorImpl< Function * > & Clones, TargetTransformInfo & TTI, bool OptimizeFrame, std::function< bool(Instruction &)> MaterializableCallback) static
Definition at line 1933 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Async, BB, llvm::coro::buildCoroutineFrame(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, F, handleNoSuspendCoroutine(), I, llvm::coro::Shape::OptimizeFrame, llvm::removeUnreachableBlocks(), replaceFrameSizeAndAlignment(), replaceSwiftErrorOps(), llvm::coro::Retcon, llvm::coro::RetconOnce, llvm::coro::salvageDebugInfo(), simplifySuspendPoints(), splitAsyncCoroutine(), splitRetconCoroutine(), splitSwitchCoroutine(), and llvm::coro::Switch.
Referenced by llvm::CoroSplitPass::run().
splitRetconCoroutine()
static void splitRetconCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones) static
Definition at line 1788 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), llvm::MCID::Branch, Builder, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, llvm::BasicBlock::Create(), createCloneDeclaration(), DL, llvm::numbers::e, E, llvm::coro::Shape::emitAlloc(), F, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::UndefValue::get(), llvm::CoroBeginInst::getId(), llvm::Type::getPointerTo(), llvm::coro::Shape::getRetconResultTypes(), llvm::Value::getType(), llvm::TrackingVH< ValueTy >::getValPtr(), i, I, llvm::coro::Shape::RetconLoweringStorage::IsFrameInlineInStorage, llvm::Value::replaceAllUsesWith(), llvm::SmallVectorImpl< T >::reserve(), llvm::coro::Retcon, llvm::coro::Shape::RetconLowering, llvm::coro::RetconOnce, and llvm::coro::Shape::RetconLoweringStorage::ReturnBlock.
Referenced by splitCoroutine().
splitSwitchCoroutine()
static void splitSwitchCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones, TargetTransformInfo & TTI) static
Definition at line 1606 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, addMustTailToCoroResumes(), assert(), createClone(), createResumeEntryBlock(), F, postSplitCleanup(), setCoroInfo(), llvm::TargetTransformInfo::supportsTailCalls(), llvm::coro::Switch, and updateCoroFrame().
Referenced by splitCoroutine().
updateAsyncFuncPointerContextSize()
static void updateAsyncFuncPointerContextSize (coro::Shape & Shape) static
Definition at line 1099 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), llvm::coro::Async, llvm::coro::Shape::AsyncLoweringStorage::AsyncFuncPointer, llvm::coro::Shape::AsyncLowering, llvm::coro::Shape::AsyncLoweringStorage::ContextSize, llvm::ConstantInt::get(), llvm::ConstantStruct::get(), llvm::GlobalVariable::getInitializer(), and llvm::GlobalVariable::setInitializer().
Referenced by replaceFrameSizeAndAlignment().
updateCallGraphAfterCoroutineSplit()
static void updateCallGraphAfterCoroutineSplit (LazyCallGraph::Node & N, const coro::Shape & Shape, const SmallVectorImpl< Function * > & Clones, LazyCallGraph::SCC & C, LazyCallGraph & CG, CGSCCAnalysisManager & AM, CGSCCUpdateResult & UR, FunctionAnalysisManager & FAM) static
Definition at line 2003 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Shape::CoroBegin, removeCoroEnds(), and llvm::coro::Switch.
Referenced by llvm::CoroSplitPass::run().
updateCoroFrame()
static void updateCoroFrame (coro::Shape & Shape, Function * ResumeFn, Function * DestroyFn, Function * CleanupFn) static
Definition at line 1175 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, llvm::coro::Shape::SwitchFieldIndex::Destroy, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::AnyCoroIdInst::getCoroAlloc(), llvm::coro::Shape::getInsertPtAfterFramePtr(), llvm::coro::Shape::getSwitchCoroId(), llvm::coro::Shape::SwitchFieldIndex::Resume, and llvm::coro::Switch.
Referenced by splitSwitchCoroutine().