LLVM: lib/Transforms/Scalar/CorrelatedValuePropagation.cpp File Reference
CorrelatedValuePropagation.cpp File Reference
#include "llvm/Transforms/Scalar/CorrelatedValuePropagation.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LazyValueInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/Local.h"
#include <cassert>
#include <optional>
#include <utility>
Macros
#define DEBUG_TYPE "correlated-value-propagation"
Enumerations
enum Domain { Domain::NonNegative, Domain::NonPositive, Domain::Unknown }
Functions
STATISTIC (NumPhis, "Number of phis propagated")
STATISTIC (NumPhiCommon, "Number of phis deleted via common incoming value")
STATISTIC (NumSelects, "Number of selects propagated")
STATISTIC (NumMemAccess, "Number of memory access targets propagated")
STATISTIC (NumCmps, "Number of comparisons propagated")
STATISTIC (NumReturns, "Number of return values propagated")
STATISTIC (NumDeadCases, "Number of switch cases removed")
STATISTIC (NumSDivSRemsNarrowed, "Number of sdivs/srems whose width was decreased")
STATISTIC (NumSDivs, "Number of sdiv converted to udiv")
STATISTIC (NumUDivURemsNarrowed, "Number of udivs/urems whose width was decreased")
STATISTIC (NumAShrsConverted, "Number of ashr converted to lshr")
STATISTIC (NumAShrsRemoved, "Number of ashr removed")
STATISTIC (NumSRems, "Number of srem converted to urem")
STATISTIC (NumSExt, "Number of sext converted to zext")
STATISTIC (NumSICmps, "Number of signed icmp preds simplified to unsigned")
STATISTIC (NumAnd, "Number of ands removed")
STATISTIC (NumNW, "Number of no-wrap deductions")
STATISTIC (NumNSW, "Number of no-signed-wrap deductions")
STATISTIC (NumNUW, "Number of no-unsigned-wrap deductions")
STATISTIC (NumAddNW, "Number of no-wrap deductions for add")
STATISTIC (NumAddNSW, "Number of no-signed-wrap deductions for add")
STATISTIC (NumAddNUW, "Number of no-unsigned-wrap deductions for add")
STATISTIC (NumSubNW, "Number of no-wrap deductions for sub")
STATISTIC (NumSubNSW, "Number of no-signed-wrap deductions for sub")
STATISTIC (NumSubNUW, "Number of no-unsigned-wrap deductions for sub")
STATISTIC (NumMulNW, "Number of no-wrap deductions for mul")
STATISTIC (NumMulNSW, "Number of no-signed-wrap deductions for mul")
STATISTIC (NumMulNUW, "Number of no-unsigned-wrap deductions for mul")
STATISTIC (NumShlNW, "Number of no-wrap deductions for shl")
STATISTIC (NumShlNSW, "Number of no-signed-wrap deductions for shl")
STATISTIC (NumShlNUW, "Number of no-unsigned-wrap deductions for shl")
STATISTIC (NumAbs, "Number of llvm.abs intrinsics removed")
STATISTIC (NumOverflows, "Number of overflow checks removed")
STATISTIC (NumSaturating, "Number of saturating arithmetics converted to normal arithmetics")
STATISTIC (NumNonNull, "Number of function pointer arguments marked non-null")
STATISTIC (NumMinMax, "Number of llvm.[us]{min,max} intrinsics removed")
STATISTIC (NumUDivURemsNarrowedExpanded, "Number of bound udiv's/urem's expanded")
INITIALIZE_PASS_BEGIN (CorrelatedValuePropagation, "correlated-propagation", "Value Propagation", false, false) INITIALIZE_PASS_END(CorrelatedValuePropagation
static bool processSelect (SelectInst *S, LazyValueInfo *LVI)
static bool simplifyCommonValuePhi (PHINode *P, LazyValueInfo *LVI, DominatorTree *DT)
Try to simplify a phi with constant incoming values that match the edge values of a non-constant value on all other edges: bb0: isnull = icmp eq i8* x, null br i1 isnull, label bb2, label bb1 bb1: br label bb2 bb2: r = phi i8* [ x, bb1 ], [ null, bb0 ] --> r = x.
static Value * getValueOnEdge (LazyValueInfo *LVI, Value *Incoming, BasicBlock *From, BasicBlock *To, Instruction *CxtI)
static bool processPHI (PHINode *P, LazyValueInfo *LVI, DominatorTree *DT, const SimplifyQuery &SQ)
static bool processMemAccess (Instruction *I, LazyValueInfo *LVI)
static bool processICmp (ICmpInst *Cmp, LazyValueInfo *LVI)
static bool constantFoldCmp (CmpInst *Cmp, LazyValueInfo *LVI)
See if LazyValueInfo's ability to exploit edge conditions or range information is sufficient to prove this comparison.
static bool processCmp (CmpInst *Cmp, LazyValueInfo *LVI)
static bool processSwitch (SwitchInst *I, LazyValueInfo *LVI, DominatorTree *DT)
Simplify a switch instruction by removing cases which can never fire.
static bool willNotOverflow (BinaryOpIntrinsic *BO, LazyValueInfo *LVI)
static void setDeducedOverflowingFlags (Value *V, Instruction::BinaryOps Opcode, bool NewNSW, bool NewNUW)
static bool processBinOp (BinaryOperator *BinOp, LazyValueInfo *LVI)
static bool processAbsIntrinsic (IntrinsicInst *II, LazyValueInfo *LVI)
static bool processMinMaxIntrinsic (MinMaxIntrinsic *MM, LazyValueInfo *LVI)
static bool processOverflowIntrinsic (WithOverflowInst *WO, LazyValueInfo *LVI)
static bool processSaturatingInst (SaturatingInst *SI, LazyValueInfo *LVI)
static bool processCallSite (CallBase &CB, LazyValueInfo *LVI)
Infer nonnull attributes for the arguments at the specified callsite.
static Domain getDomain (const ConstantRange &CR)
static bool narrowSDivOrSRem (BinaryOperator *Instr, const ConstantRange &LCR, const ConstantRange &RCR)
Try to shrink a sdiv/srem's width down to the smallest power of two that's sufficient to contain its operands.
static bool expandUDivOrURem (BinaryOperator *Instr, const ConstantRange &XCR, const ConstantRange &YCR)
static bool narrowUDivOrURem (BinaryOperator *Instr, const ConstantRange &XCR, const ConstantRange &YCR)
Try to shrink a udiv/urem's width down to the smallest power of two that's sufficient to contain its operands.
static bool processUDivOrURem (BinaryOperator *Instr, LazyValueInfo *LVI)
static bool processSRem (BinaryOperator *SDI, const ConstantRange &LCR, const ConstantRange &RCR, LazyValueInfo *LVI)
static bool processSDiv (BinaryOperator *SDI, const ConstantRange &LCR, const ConstantRange &RCR, LazyValueInfo *LVI)
See if LazyValueInfo's ability to exploit edge conditions or range information is sufficient to prove the signs of both operands of this SDiv.
static bool processSDivOrSRem (BinaryOperator *Instr, LazyValueInfo *LVI)
static bool processAShr (BinaryOperator *SDI, LazyValueInfo *LVI)
static bool processSExt (SExtInst *SDI, LazyValueInfo *LVI)
static bool processAnd (BinaryOperator *BinOp, LazyValueInfo *LVI)
static Constant * getConstantAt (Value *V, Instruction *At, LazyValueInfo *LVI)
static bool runImpl (Function &F, LazyValueInfo *LVI, DominatorTree *DT, const SimplifyQuery &SQ)
Variables
static cl::opt< bool > CanonicalizeICmpPredicatesToUnsigned ("canonicalize-icmp-predicates-to-unsigned", cl::init(true), cl::Hidden, cl::desc("Enables canonicalization of signed relational predicates to " "unsigned (e.g. sgt => ugt)"))
correlated propagation
correlated Value Propagation
correlated Value false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "correlated-value-propagation"
Definition at line 51 of file CorrelatedValuePropagation.cpp.
Enumeration Type Documentation
Domain
enum Domain strong
Enumerator
NonNegative
NonPositive
Unknown
Definition at line 696 of file CorrelatedValuePropagation.cpp.
Function Documentation
constantFoldCmp()
static bool constantFoldCmp (CmpInst * Cmp, LazyValueInfo * LVI) static
See if LazyValueInfo's ability to exploit edge conditions or range information is sufficient to prove this comparison.
Even for local conditions, this can sometimes prove conditions instcombine can't by exploiting range information.
Definition at line 343 of file CorrelatedValuePropagation.cpp.
References llvm::ConstantInt::get(), llvm::LazyValueInfo::getPredicateAt(), llvm::Value::getType(), llvm::CmpInst::makeCmpResultType(), and llvm::LazyValueInfo::Unknown.
Referenced by processCmp().
expandUDivOrURem()
static bool expandUDivOrURem (BinaryOperator * Instr, const ConstantRange & XCR, const ConstantRange & YCR) static
Definition at line 755 of file CorrelatedValuePropagation.cpp.
References assert(), B, llvm::Instruction::eraseFromParent(), llvm::ConstantRange::getBitWidth(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ConstantRange::icmp(), llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, llvm::ConstantRange::isAllNegative(), llvm::Type::isVectorTy(), llvm::Value::replaceAllUsesWith(), llvm::Value::takeName(), llvm::ConstantRange::umul_sat(), X, and Y.
Referenced by processUDivOrURem().
getConstantAt()
static Constant* getConstantAt (Value * V, Instruction * At, LazyValueInfo * LVI) static
Definition at line 1118 of file CorrelatedValuePropagation.cpp.
References llvm::LazyValueInfo::getConstant(), llvm::ConstantInt::getFalse(), llvm::LazyValueInfo::getPredicateAt(), llvm::ConstantInt::getTrue(), llvm::LazyValueInfo::True, and llvm::LazyValueInfo::Unknown.
Referenced by runImpl().
getDomain()
static Domain getDomain (const ConstantRange & CR) static
Definition at line 698 of file CorrelatedValuePropagation.cpp.
References llvm::ConstantRange::getBitWidth(), llvm::APInt::getNullValue(), llvm::ConstantRange::icmp(), llvm::CmpInst::ICMP_SLE, llvm::ConstantRange::isAllNonNegative(), NonNegative, NonPositive, and Unknown.
Referenced by collectMDInDomain(), llvm::MDNode::getMostGenericAliasScope(), processSDiv(), and processSRem().
getValueOnEdge()
static Value* getValueOnEdge (LazyValueInfo * LVI, Value * Incoming, BasicBlock * From, BasicBlock * To, Instruction * CxtI) static
Definition at line 218 of file CorrelatedValuePropagation.cpp.
References llvm::LazyValueInfo::False, From, llvm::LazyValueInfo::getConstantOnEdge(), llvm::LazyValueInfo::getPredicateOnEdge(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::Type::isVectorTy(), and SI.
Referenced by processPHI().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (CorrelatedValuePropagation , "correlated-propagation" , "Value Propagation" , false , false)
narrowSDivOrSRem()
static bool narrowSDivOrSRem (BinaryOperator * Instr, const ConstantRange & LCR, const ConstantRange & RCR) static
Try to shrink a sdiv/srem's width down to the smallest power of two that's sufficient to contain its operands.
Definition at line 708 of file CorrelatedValuePropagation.cpp.
References assert(), B, llvm::ConstantRange::contains(), llvm::Instruction::eraseFromParent(), llvm::APInt::getAllOnes(), llvm::Value::getContext(), llvm::Type::getIntegerBitWidth(), llvm::Type::getIntNTy(), llvm::ConstantRange::getMinSignedBits(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::APInt::getSignedMinValue(), llvm::Value::getType(), llvm::Instruction::isExact(), llvm::Type::isVectorTy(), LHS, llvm::max(), llvm::PowerOf2Ceil(), llvm::Value::replaceAllUsesWith(), RHS, and llvm::APInt::sext().
Referenced by processSDivOrSRem().
narrowUDivOrURem()
static bool narrowUDivOrURem (BinaryOperator * Instr, const ConstantRange & XCR, const ConstantRange & YCR) static
Try to shrink a udiv/urem's width down to the smallest power of two that's sufficient to contain its operands.
Definition at line 828 of file CorrelatedValuePropagation.cpp.
References assert(), B, llvm::Instruction::eraseFromParent(), llvm::ConstantRange::getActiveBits(), llvm::Value::getContext(), llvm::Type::getIntegerBitWidth(), llvm::Type::getIntNTy(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Instruction::isExact(), llvm::Type::isVectorTy(), LHS, llvm::max(), llvm::PowerOf2Ceil(), llvm::Value::replaceAllUsesWith(), and RHS.
Referenced by processUDivOrURem().
processAbsIntrinsic()
static bool processAbsIntrinsic (IntrinsicInst * II, LazyValueInfo * LVI) static
Definition at line 501 of file CorrelatedValuePropagation.cpp.
References assert(), B, llvm::Instruction::eraseFromParent(), llvm::LazyValueInfo::False, llvm::ConstantInt::get(), llvm::CallBase::getArgOperand(), llvm::Value::getContext(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::LazyValueInfo::getPredicateAt(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignedMinValue(), llvm::ConstantInt::getTrue(), processBinOp(), llvm::Value::replaceAllUsesWith(), llvm::CallBase::setArgOperand(), llvm::LazyValueInfo::True, llvm::LazyValueInfo::Unknown, and X.
Referenced by processCallSite().
processAnd()
static bool processAnd (BinaryOperator * BinOp, LazyValueInfo * LVI) static
Definition at line 1093 of file CorrelatedValuePropagation.cpp.
References llvm::Instruction::eraseFromParent(), llvm::LazyValueInfo::getConstantRangeAtUse(), llvm::User::getOperand(), llvm::User::getOperandUse(), llvm::Value::getType(), llvm::ConstantRange::getUnsignedMax(), llvm::Type::isVectorTy(), LHS, llvm::Value::replaceAllUsesWith(), RHS, and llvm::APInt::ule().
Referenced by runImpl().
processAShr()
static bool processAShr (BinaryOperator * SDI, LazyValueInfo * LVI) static
Definition at line 1006 of file CorrelatedValuePropagation.cpp.
References llvm::ConstantRange::contains(), llvm::Instruction::eraseFromParent(), llvm::LazyValueInfo::getConstantRangeAtUse(), llvm::Instruction::getDebugLoc(), llvm::Type::getIntegerBitWidth(), llvm::User::getOperand(), llvm::User::getOperandUse(), llvm::Value::getType(), llvm::ConstantRange::isAllNonNegative(), llvm::Instruction::isExact(), llvm::Type::isVectorTy(), llvm::Value::replaceAllUsesWith(), and uint64_t.
Referenced by runImpl().
processBinOp()
static bool processBinOp (BinaryOperator * BinOp, LazyValueInfo * LVI) static
Definition at line 1055 of file CorrelatedValuePropagation.cpp.
References llvm::ConstantRange::contains(), llvm::LazyValueInfo::getConstantRange(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoUnsignedWrap(), llvm::Type::isVectorTy(), LHS, llvm::ConstantRange::makeGuaranteedNoWrapRegion(), RHS, and setDeducedOverflowingFlags().
Referenced by processAbsIntrinsic(), processOverflowIntrinsic(), processSaturatingInst(), and runImpl().
processCallSite()
static bool processCallSite (CallBase & CB, LazyValueInfo * LVI) static
Infer nonnull attributes for the arguments at the specified callsite.
Definition at line 619 of file CorrelatedValuePropagation.cpp.
References llvm::abs(), llvm::AttributeList::addParamAttribute(), llvm::CallBase::arg_size(), llvm::CallBase::args(), assert(), llvm::LazyValueInfo::False, llvm::Use::get(), llvm::Attribute::get(), llvm::ConstantPointerNull::get(), llvm::CallBase::getAttributes(), llvm::LazyValueInfo::getConstant(), llvm::Value::getContext(), llvm::CallBase::getIntrinsicID(), llvm::CallBase::getOperandBundle(), llvm::LazyValueInfo::getPredicateAt(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::Type::isVectorTy(), llvm::LLVMContext::OB_deopt, llvm::CallBase::paramHasAttr(), processAbsIntrinsic(), processMinMaxIntrinsic(), processOverflowIntrinsic(), processSaturatingInst(), llvm::Use::set(), llvm::CallBase::setAttributes(), SI, and willNotOverflow().
Referenced by runImpl().
processCmp()
static bool processCmp (CmpInst * Cmp, LazyValueInfo * LVI) static
Definition at line 360 of file CorrelatedValuePropagation.cpp.
References constantFoldCmp(), and processICmp().
Referenced by runImpl().
processICmp()
static bool processICmp (ICmpInst * Cmp, LazyValueInfo * LVI) static
Definition at line 313 of file CorrelatedValuePropagation.cpp.
References CanonicalizeICmpPredicatesToUnsigned, llvm::LazyValueInfo::getConstantRange(), and llvm::ConstantRange::getEquivalentPredWithFlippedSignedness().
Referenced by processCmp().
processMemAccess()
static bool processMemAccess (Instruction * I, LazyValueInfo * LVI) static
Definition at line 296 of file CorrelatedValuePropagation.cpp.
References llvm::LazyValueInfo::getConstant(), and I.
Referenced by runImpl().
processMinMaxIntrinsic()
static bool processMinMaxIntrinsic (MinMaxIntrinsic * MM, LazyValueInfo * LVI) static
Definition at line 558 of file CorrelatedValuePropagation.cpp.
References llvm::Instruction::eraseFromParent(), llvm::MinMaxIntrinsic::getLHS(), llvm::CmpInst::getNonStrictPredicate(), llvm::User::getOperand(), llvm::MinMaxIntrinsic::getPredicate(), llvm::LazyValueInfo::getPredicateAt(), llvm::MinMaxIntrinsic::getRHS(), llvm::Value::replaceAllUsesWith(), and llvm::LazyValueInfo::Unknown.
Referenced by processCallSite().
processOverflowIntrinsic()
static bool processOverflowIntrinsic (WithOverflowInst * WO, LazyValueInfo * LVI) static
Definition at line 572 of file CorrelatedValuePropagation.cpp.
References B, llvm::Instruction::eraseFromParent(), llvm::ConstantStruct::get(), llvm::PoisonValue::get(), llvm::BinaryOpIntrinsic::getBinaryOp(), llvm::ConstantInt::getFalse(), llvm::BinaryOpIntrinsic::getLHS(), llvm::Value::getName(), llvm::BinaryOpIntrinsic::getRHS(), llvm::Value::getType(), llvm::BinaryOpIntrinsic::isSigned(), processBinOp(), llvm::Value::replaceAllUsesWith(), setDeducedOverflowingFlags(), llvm::ARM_MB::ST, and Struct.
Referenced by processCallSite().
processPHI()
static bool processPHI (PHINode * P, LazyValueInfo * LVI, DominatorTree * DT, const SimplifyQuery & SQ) static
Definition at line 265 of file CorrelatedValuePropagation.cpp.
References BB, llvm::numbers::e, getValueOnEdge(), i, P, simplifyCommonValuePhi(), and llvm::simplifyInstruction().
Referenced by runImpl().
processSaturatingInst()
static bool processSaturatingInst (SaturatingInst * SI, LazyValueInfo * LVI) static
Definition at line 598 of file CorrelatedValuePropagation.cpp.
References llvm::BinaryOperator::Create(), processBinOp(), llvm::Instruction::setDebugLoc(), setDeducedOverflowingFlags(), and SI.
Referenced by processCallSite().
processSDiv()
static bool processSDiv (BinaryOperator * SDI, const ConstantRange & LCR, const ConstantRange & RCR, LazyValueInfo * LVI) static
See if LazyValueInfo's ability to exploit edge conditions or range information is sufficient to prove the signs of both operands of this SDiv.
If this is the case, replace the SDiv with a UDiv. Even for local conditions, this can sometimes prove conditions instcombine can't by exploiting range information.
Definition at line 939 of file CorrelatedValuePropagation.cpp.
References assert(), llvm::BinaryOperator::CreateNeg(), D, llvm::Instruction::eraseFromParent(), llvm::Instruction::getDebugLoc(), getDomain(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Instruction::isExact(), llvm::Type::isVectorTy(), NonNegative, processUDivOrURem(), llvm::Value::replaceAllUsesWith(), and Unknown.
Referenced by processSDivOrSRem().
processSDivOrSRem()
static bool processSDivOrSRem (BinaryOperator * Instr, LazyValueInfo * LVI) static
Definition at line 986 of file CorrelatedValuePropagation.cpp.
References assert(), llvm::LazyValueInfo::getConstantRangeAtUse(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperandUse(), llvm::Value::getType(), llvm::Type::isVectorTy(), narrowSDivOrSRem(), processSDiv(), and processSRem().
Referenced by runImpl().
processSelect()
static bool processSelect (SelectInst * S, LazyValueInfo * LVI) static
Definition at line 137 of file CorrelatedValuePropagation.cpp.
References llvm::LazyValueInfo::getConstant(), llvm::ConstantInt::isOne(), and S.
Referenced by runImpl().
processSExt()
static bool processSExt (SExtInst * SDI, LazyValueInfo * LVI) static
Definition at line 1037 of file CorrelatedValuePropagation.cpp.
References llvm::sampleprof::Base, llvm::CastInst::CreateZExtOrBitCast(), llvm::Instruction::eraseFromParent(), llvm::LazyValueInfo::getConstantRangeAtUse(), llvm::Instruction::getDebugLoc(), llvm::User::getOperandUse(), llvm::Value::getType(), llvm::ConstantRange::isAllNonNegative(), llvm::Type::isVectorTy(), and llvm::Value::replaceAllUsesWith().
Referenced by runImpl().
processSRem()
static bool processSRem (BinaryOperator * SDI, const ConstantRange & LCR, const ConstantRange & RCR, LazyValueInfo * LVI) static
Definition at line 880 of file CorrelatedValuePropagation.cpp.
References llvm::ConstantRange::abs(), assert(), llvm::BinaryOperator::CreateNeg(), D, llvm::Instruction::eraseFromParent(), llvm::Instruction::getDebugLoc(), getDomain(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ConstantRange::icmp(), llvm::CmpInst::ICMP_ULT, llvm::Type::isVectorTy(), NonNegative, NonPositive, processUDivOrURem(), llvm::Value::replaceAllUsesWith(), and Unknown.
Referenced by processSDivOrSRem().
processSwitch()
static bool processSwitch (SwitchInst * I, LazyValueInfo * LVI, DominatorTree * DT) static
Simplify a switch instruction by removing cases which can never fire.
If the uselessness of a case could be determined locally then constant propagation would already have figured it out. Instead, walk the predecessors and statically evaluate cases based on information available on that edge. Cases that cannot fire no matter what the incoming edge can safely be removed. If a case fires on every incoming edge then the entire switch can be removed and replaced with a branch to the case destination.
Definition at line 378 of file CorrelatedValuePropagation.cpp.
References llvm::DomTreeUpdater::applyUpdatesPermissive(), BB, Cond, llvm::ConstantFoldTerminator(), llvm::DominatorTreeBase< BasicBlock, false >::Delete, llvm::LazyValueInfo::False, llvm::LazyValueInfo::getPredicateAt(), I, llvm::CmpInst::ICMP_EQ, llvm::DomTreeUpdater::Lazy, llvm::BasicBlock::removePredecessor(), SI, llvm::successors(), and llvm::LazyValueInfo::True.
Referenced by llvm::PredicateInfoBuilder::buildPredicateInfo(), and runImpl().
processUDivOrURem()
static bool processUDivOrURem (BinaryOperator * Instr, LazyValueInfo * LVI) static
Definition at line 866 of file CorrelatedValuePropagation.cpp.
References assert(), expandUDivOrURem(), llvm::LazyValueInfo::getConstantRangeAtUse(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperandUse(), llvm::Value::getType(), llvm::Type::isVectorTy(), and narrowUDivOrURem().
Referenced by processSDiv(), processSRem(), and runImpl().
runImpl()
static bool runImpl (Function & F, LazyValueInfo * LVI, DominatorTree * DT, const SimplifyQuery & SQ) static
Definition at line 1141 of file CorrelatedValuePropagation.cpp.
References llvm::MCID::Add, BB, llvm::MCID::Call, llvm::depth_first(), F, getConstantAt(), llvm::SPII::Load, llvm::make_early_inc_range(), Mul, PHI, processAnd(), processAShr(), processBinOp(), processCallSite(), processCmp(), processMemAccess(), processPHI(), processSDivOrSRem(), processSelect(), processSExt(), processSwitch(), processUDivOrURem(), llvm::MipsISD::Ret, Select, llvm::SPII::Store, and llvm::M68kBeads::Term.
Referenced by llvm::CorrelatedValuePropagationPass::run().
setDeducedOverflowingFlags()
static void setDeducedOverflowingFlags (Value * V, Instruction::BinaryOps Opcode, bool NewNSW, bool NewNUW) static
Definition at line 449 of file CorrelatedValuePropagation.cpp.
References llvm::MCID::Add, llvm_unreachable, and Mul.
Referenced by processBinOp(), processOverflowIntrinsic(), and processSaturatingInst().
simplifyCommonValuePhi()
static bool simplifyCommonValuePhi (PHINode * P, LazyValueInfo * LVI, DominatorTree * DT) static
Try to simplify a phi with constant incoming values that match the edge values of a non-constant value on all other edges: bb0: isnull = icmp eq i8* x, null br i1 isnull, label bb2, label bb1 bb1: br label bb2 bb2: r = phi i8* [ x, bb1 ], [ null, bb0 ] --> r = x.
Definition at line 167 of file CorrelatedValuePropagation.cpp.
References llvm::DominatorTree::dominates(), llvm::numbers::e, llvm::LazyValueInfo::getConstantOnEdge(), i, llvm::isGuaranteedNotToBePoison(), and P.
Referenced by processPHI().
STATISTIC() [1/37]
STATISTIC (NumAbs , "Number of llvm.abs intrinsics removed")
STATISTIC() [2/37]
STATISTIC (NumAddNSW , "Number of no-signed-wrap deductions for add")
STATISTIC() [3/37]
STATISTIC (NumAddNUW , "Number of no-unsigned-wrap deductions for add")
STATISTIC() [4/37]
STATISTIC (NumAddNW , "Number of no-wrap deductions for add")
STATISTIC() [5/37]
STATISTIC (NumAnd , "Number of ands removed")
STATISTIC() [6/37]
STATISTIC (NumAShrsConverted , "Number of ashr converted to lshr")
STATISTIC() [7/37]
STATISTIC (NumAShrsRemoved , "Number of ashr removed")
STATISTIC() [8/37]
STATISTIC (NumCmps , "Number of comparisons propagated")
STATISTIC() [9/37]
STATISTIC (NumDeadCases , "Number of switch cases removed")
STATISTIC() [10/37]
STATISTIC (NumMemAccess , "Number of memory access targets propagated")
STATISTIC() [11/37]
STATISTIC (NumMinMax , "Number of llvm.{min,max} intrinsics removed" [us])
STATISTIC() [12/37]
STATISTIC (NumMulNSW , "Number of no-signed-wrap deductions for mul")
STATISTIC() [13/37]
STATISTIC (NumMulNUW , "Number of no-unsigned-wrap deductions for mul")
STATISTIC() [14/37]
STATISTIC (NumMulNW , "Number of no-wrap deductions for mul")
STATISTIC() [15/37]
STATISTIC (NumNonNull , "Number of function pointer arguments marked non-null")
STATISTIC() [16/37]
STATISTIC (NumNSW , "Number of no-signed-wrap deductions")
STATISTIC() [17/37]
STATISTIC (NumNUW , "Number of no-unsigned-wrap deductions")
STATISTIC() [18/37]
STATISTIC (NumNW , "Number of no-wrap deductions")
STATISTIC() [19/37]
STATISTIC (NumOverflows , "Number of overflow checks removed")
STATISTIC() [20/37]
STATISTIC (NumPhiCommon , "Number of phis deleted via common incoming value")
STATISTIC() [21/37]
STATISTIC (NumPhis , "Number of phis propagated")
STATISTIC() [22/37]
STATISTIC (NumReturns , "Number of return values propagated")
STATISTIC() [23/37]
STATISTIC (NumSaturating , "Number of saturating arithmetics converted to normal arithmetics")
STATISTIC() [24/37]
STATISTIC (NumSDivs , "Number of sdiv converted to udiv")
STATISTIC() [25/37]
STATISTIC (NumSDivSRemsNarrowed , "Number of sdivs/srems whose width was decreased")
STATISTIC() [26/37]
STATISTIC (NumSelects , "Number of selects propagated")
STATISTIC() [27/37]
STATISTIC (NumSExt , "Number of sext converted to zext")
STATISTIC() [28/37]
STATISTIC (NumShlNSW , "Number of no-signed-wrap deductions for shl")
STATISTIC() [29/37]
STATISTIC (NumShlNUW , "Number of no-unsigned-wrap deductions for shl")
STATISTIC() [30/37]
STATISTIC (NumShlNW , "Number of no-wrap deductions for shl")
STATISTIC() [31/37]
STATISTIC (NumSICmps , "Number of signed icmp preds simplified to unsigned")
STATISTIC() [32/37]
STATISTIC (NumSRems , "Number of srem converted to urem")
STATISTIC() [33/37]
STATISTIC (NumSubNSW , "Number of no-signed-wrap deductions for sub")
STATISTIC() [34/37]
STATISTIC (NumSubNUW , "Number of no-unsigned-wrap deductions for sub")
STATISTIC() [35/37]
STATISTIC (NumSubNW , "Number of no-wrap deductions for sub")
STATISTIC() [36/37]
STATISTIC (NumUDivURemsNarrowed , "Number of udivs/urems whose width was decreased")
STATISTIC() [37/37]
STATISTIC (NumUDivURemsNarrowedExpanded , "Number of bound udiv's/urem's expanded")
willNotOverflow()
static bool willNotOverflow (BinaryOpIntrinsic * BO, LazyValueInfo * LVI) static
Definition at line 441 of file CorrelatedValuePropagation.cpp.
References llvm::ConstantRange::contains(), llvm::BinaryOpIntrinsic::getBinaryOp(), llvm::LazyValueInfo::getConstantRangeAtUse(), llvm::BinaryOpIntrinsic::getNoWrapKind(), llvm::User::getOperandUse(), and llvm::ConstantRange::makeGuaranteedNoWrapRegion().
Referenced by processCallSite().
Variable Documentation
CanonicalizeICmpPredicatesToUnsigned
cl::opt<bool> CanonicalizeICmpPredicatesToUnsigned("canonicalize-icmp-predicates-to-unsigned", cl::init(true), cl::Hidden, cl::desc("Enables canonicalization of signed relational predicates to " "unsigned (e.g. sgt => ugt)")) static
Referenced by processICmp().
false
correlated Value false
Definition at line 130 of file CorrelatedValuePropagation.cpp.
propagation
correlated propagation
Definition at line 129 of file CorrelatedValuePropagation.cpp.
Propagation
correlated Value Propagation
Definition at line 130 of file CorrelatedValuePropagation.cpp.