LLVM: lib/Support/CrashRecoveryContext.cpp File Reference
CrashRecoveryContext.cpp File Reference
#include "llvm/Support/CrashRecoveryContext.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ExitCodes.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/thread.h"
#include <cassert>
#include <mutex>
#include <setjmp.h>
#include <signal.h>
Functions
static void installExceptionOrSignalHandlers ()
static void uninstallExceptionOrSignalHandlers ()
static void CrashRecoverySignalHandler (int Signal)
static void setThreadBackgroundPriority ()
static bool hasThreadBackgroundPriority ()
static void RunSafelyOnThread_Dispatch (void *UserData)
Variables
static const int Signals []
static const unsigned NumSignals = std::size(Signals)
static struct sigaction PrevActions [NumSignals]
Function Documentation
CrashRecoverySignalHandler()
static void CrashRecoverySignalHandler (int Signal) static
Definition at line 352 of file CrashRecoveryContext.cpp.
References llvm::CrashRecoveryContext::Disable().
Referenced by installExceptionOrSignalHandlers().
hasThreadBackgroundPriority()
static bool hasThreadBackgroundPriority () static
Definition at line 486 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::RunSafelyOnThread().
installExceptionOrSignalHandlers()
static void installExceptionOrSignalHandlers () static
Definition at line 393 of file CrashRecoveryContext.cpp.
References CrashRecoverySignalHandler(), i, NumSignals, PrevActions, and Signals.
Referenced by llvm::CrashRecoveryContext::Enable().
RunSafelyOnThread_Dispatch()
static void RunSafelyOnThread_Dispatch (void * UserData) static
Definition at line 503 of file CrashRecoveryContext.cpp.
References Info, and setThreadBackgroundPriority().
Referenced by llvm::CrashRecoveryContext::RunSafelyOnThread().
setThreadBackgroundPriority()
static void setThreadBackgroundPriority () static
Definition at line 480 of file CrashRecoveryContext.cpp.
Referenced by RunSafelyOnThread_Dispatch().
uninstallExceptionOrSignalHandlers()
static void uninstallExceptionOrSignalHandlers () static
Definition at line 405 of file CrashRecoveryContext.cpp.
References i, NumSignals, PrevActions, and Signals.
Referenced by llvm::CrashRecoveryContext::Disable().
Variable Documentation
NumSignals
const unsigned NumSignals = std::size(Signals) static
Definition at line 349 of file CrashRecoveryContext.cpp.
Referenced by installExceptionOrSignalHandlers(), and uninstallExceptionOrSignalHandlers().
PrevActions
struct sigaction PrevActions[NumSignals] static
Definition at line 350 of file CrashRecoveryContext.cpp.
Referenced by installExceptionOrSignalHandlers(), and uninstallExceptionOrSignalHandlers().
Signals
const int Signals[] static
Initial value:
=
    { SIGABRT, SIGBUS, SIGFPE, SIGILL, SIGSEGV, SIGTRAP }
Definition at line 347 of file CrashRecoveryContext.cpp.
Referenced by installExceptionOrSignalHandlers(), and uninstallExceptionOrSignalHandlers().