LLVM: lib/Target/CSKY/CSKYISelDAGToDAG.cpp File Reference
CSKYISelDAGToDAG.cpp File Reference
#include "CSKY.h"
#include "CSKYSubtarget.h"
#include "CSKYTargetMachine.h"
#include "MCTargetDesc/CSKYMCTargetDesc.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "CSKYGenDAGISel.inc"
Macros
#define DEBUG_TYPE "csky-isel"
#define PASS_NAME "CSKY DAG->DAG Pattern Instruction Selection"
Functions
static SDValue InvertCarryFlag (const CSKYSubtarget *Subtarget, SelectionDAG *DAG, SDLoc Dl, SDValue OldCarry)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "csky-isel"
Definition at line 23 of file CSKYISelDAGToDAG.cpp.
PASS_NAME
#define PASS_NAME "CSKY DAG->DAG Pattern Instruction Selection"
Definition at line 24 of file CSKYISelDAGToDAG.cpp.
Function Documentation
InvertCarryFlag()
static SDValue InvertCarryFlag (const CSKYSubtarget * Subtarget, SelectionDAG * DAG, SDLoc Dl, SDValue OldCarry) static
Definition at line 327 of file CSKYISelDAGToDAG.cpp.
References llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::CSKYSubtarget::has2E3(), llvm::CSKYSubtarget::hasE2(), and llvm::MVT::i32.