LLVM: lib/Target/CSKY/CSKYRegisterInfo.cpp File Reference
CSKYRegisterInfo.cpp File Reference
#include "CSKYRegisterInfo.h"
#include "CSKY.h"
#include "CSKYSubtarget.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/MC/MCContext.h"
#include "CSKYGenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
Functions
static bool IsLegalOffset (const CSKYInstrInfo *TII, MachineInstr *MI, int &Offset)
Macro Definition Documentation
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 21 of file CSKYRegisterInfo.cpp.
Function Documentation
IsLegalOffset()
static bool IsLegalOffset (const CSKYInstrInfo * TII, MachineInstr * MI, int & Offset) static
Definition at line 108 of file CSKYRegisterInfo.cpp.
References llvm::abs(), llvm::CSKYII::AddrMode16B, llvm::CSKYII::AddrMode16H, llvm::CSKYII::AddrMode16W, llvm::CSKYII::AddrMode32B, llvm::CSKYII::AddrMode32H, llvm::CSKYII::AddrMode32SDF, llvm::CSKYII::AddrMode32WD, llvm::CSKYII::AddrModeMask, assert(), i, llvm_unreachable, llvm::BitmaskEnumDetail::Mask(), MI, llvm::Offset, TII, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::CSKYRegisterInfo::eliminateFrameIndex().