LLVM: lib/Target/CSKY/CSKYTargetMachine.cpp File Reference
CSKYTargetMachine.cpp File Reference
#include "CSKYTargetMachine.h"
#include "CSKY.h"
#include "CSKYMachineFunctionInfo.h"
#include "CSKYSubtarget.h"
#include "CSKYTargetObjectFile.h"
#include "TargetInfo/CSKYTargetInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include <optional>
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeCSKYTarget ()
static std::string computeDataLayout (const Triple &TT)
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & TT) static
Definition at line 36 of file CSKYTargetMachine.cpp.
References llvm::MipsISD::Ret.
LLVMInitializeCSKYTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeCSKYTarget ()
Definition at line 28 of file CSKYTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheCSKYTarget(), llvm::initializeCSKYConstantIslandsPass(), llvm::initializeCSKYDAGToDAGISelPass(), and X.