LLVM: lib/Target/CSKY/MCTargetDesc/CSKYAsmBackend.cpp File Reference
CSKYAsmBackend.cpp File Reference
#include "CSKYAsmBackend.h"
#include "MCTargetDesc/CSKYMCTargetDesc.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "csky-asmbackend"
Functions
static uint64_t adjustFixupValue (const MCFixup &Fixup, uint64_t Value, MCContext &Ctx)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "csky-asmbackend"
Definition at line 19 of file CSKYAsmBackend.cpp.
Function Documentation
adjustFixupValue()
static uint64_t adjustFixupValue (const MCFixup & Fixup, uint64_t Value, MCContext & Ctx) static
Definition at line 86 of file CSKYAsmBackend.cpp.
References Fixup, llvm::CSKY::fixup_csky_addr32, llvm::CSKY::fixup_csky_got32, llvm::CSKY::fixup_csky_got_imm18_scale4, llvm::CSKY::fixup_csky_gotoff, llvm::CSKY::fixup_csky_gotpc, llvm::CSKY::fixup_csky_pcrel_imm10_scale2, llvm::CSKY::fixup_csky_pcrel_imm16_scale2, llvm::CSKY::fixup_csky_pcrel_imm18_scale2, llvm::CSKY::fixup_csky_pcrel_imm26_scale2, llvm::CSKY::fixup_csky_pcrel_uimm16_scale4, llvm::CSKY::fixup_csky_pcrel_uimm7_scale4, llvm::CSKY::fixup_csky_pcrel_uimm8_scale4, llvm::CSKY::fixup_csky_plt32, llvm::CSKY::fixup_csky_plt_imm18_scale4, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::isIntN(), llvm::isUIntN(), llvm_unreachable, llvm::MCContext::reportError(), and x3.
Referenced by llvm::CSKYAsmBackend::applyFixup().