LLVM: lib/Transforms/Utils/Debugify.cpp File Reference
Debugify.cpp File Reference
#include "llvm/Transforms/Utils/Debugify.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/DIBuilder.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassInstrumentation.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/JSON.h"
#include <optional>
Macros
#define DEBUG_TYPE "debugify"
Functions
static bool applyDebugify (Function &F, enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, DebugInfoPerPass *DebugInfoBeforePass=nullptr, StringRef NameOfWrappedPass="")
static bool applyDebugify (Module &M, enum DebugifyMode Mode=DebugifyMode::SyntheticDebugInfo, DebugInfoPerPass *DebugInfoBeforePass=nullptr, StringRef NameOfWrappedPass="")
static bool checkFunctions (const DebugFnMap &DIFunctionsBefore, const DebugFnMap &DIFunctionsAfter, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array &Bugs)
static bool checkInstructions (const DebugInstMap &DILocsBefore, const DebugInstMap &DILocsAfter, const WeakInstValueMap &InstToDelete, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array &Bugs)
static bool checkVars (const DebugVarMap &DIVarsBefore, const DebugVarMap &DIVarsAfter, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array &Bugs)
static void writeJSON (StringRef OrigDIVerifyBugsReportFilePath, StringRef FileNameFromCU, StringRef NameOfWrappedPass, llvm::json::Array &Bugs)
ModulePass * createDebugifyModulePass (enum DebugifyMode Mode, llvm::StringRef NameOfWrappedPass, DebugInfoPerPass *DebugInfoBeforePass)
FunctionPass * createDebugifyFunctionPass (enum DebugifyMode Mode, llvm::StringRef NameOfWrappedPass, DebugInfoPerPass *DebugInfoBeforePass)
ModulePass * createCheckDebugifyModulePass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap *StatsMap, enum DebugifyMode Mode, DebugInfoPerPass *DebugInfoBeforePass, StringRef OrigDIVerifyBugsReportFilePath)
FunctionPass * createCheckDebugifyFunctionPass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap *StatsMap, enum DebugifyMode Mode, DebugInfoPerPass *DebugInfoBeforePass, StringRef OrigDIVerifyBugsReportFilePath)
static bool isIgnoredPass (StringRef PassID)
Variables
static RegisterPass< DebugifyModulePass > DM ("debugify", "Attach debug info to everything")
static RegisterPass< CheckDebugifyModulePass > CDM ("check-debugify", "Check debug info from -debugify")
static RegisterPass< DebugifyFunctionPass > DF ("debugify-function", "Attach debug info to a function")
static RegisterPass< CheckDebugifyFunctionPass > CDF ("check-debugify-function", "Check debug info from -debugify-function")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "debugify"
Definition at line 32 of file Debugify.cpp.
Function Documentation
applyDebugify() [1/2]
static bool applyDebugify (Function & F, enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, DebugInfoPerPass * DebugInfoBeforePass = nullptr, StringRef NameOfWrappedPass = "") static
Definition at line 217 of file Debugify.cpp.
References llvm::applyDebugifyMetadata(), assert(), llvm::collectDebugInfoMetadata(), F, M, llvm::make_range(), Mode, and SyntheticDebugInfo.
Referenced by llvm::DebugifyEachInstrumentation::registerCallbacks().
applyDebugify() [2/2]
static bool applyDebugify (Module & M, enum DebugifyMode Mode = DebugifyMode::SyntheticDebugInfo, DebugInfoPerPass * DebugInfoBeforePass = nullptr, StringRef NameOfWrappedPass = "") static
Definition at line 233 of file Debugify.cpp.
References llvm::applyDebugifyMetadata(), llvm::collectDebugInfoMetadata(), M, Mode, and SyntheticDebugInfo.
checkFunctions()
static bool checkFunctions (const DebugFnMap & DIFunctionsBefore, const DebugFnMap & DIFunctionsAfter, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array & Bugs) static
Definition at line 375 of file Debugify.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), F, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), and llvm::json::Array::push_back().
Referenced by llvm::checkDebugInfoMetadata().
checkInstructions()
static bool checkInstructions (const DebugInstMap & DILocsBefore, const DebugInstMap & DILocsAfter, const WeakInstValueMap & InstToDelete, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array & Bugs) static
Definition at line 417 of file Debugify.cpp.
References BB, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), llvm::Instruction::getOpcodeName(), and llvm::json::Array::push_back().
Referenced by llvm::checkDebugInfoMetadata().
checkVars()
static bool checkVars (const DebugVarMap & DIVarsBefore, const DebugVarMap & DIVarsAfter, StringRef NameOfWrappedPass, StringRef FileNameFromCU, bool ShouldWriteIntoJSON, llvm::json::Array & Bugs) static
Definition at line 478 of file Debugify.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), getName(), llvm::Value::getName(), getSubprogram(), and llvm::json::Array::push_back().
Referenced by llvm::checkDebugInfoMetadata().
createCheckDebugifyFunctionPass()
FunctionPass* createCheckDebugifyFunctionPass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap * StatsMap, enum DebugifyMode Mode, DebugInfoPerPass * DebugInfoBeforePass, StringRef OrigDIVerifyBugsReportFilePath)
Definition at line 997 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createCheckDebugifyModulePass()
ModulePass* createCheckDebugifyModulePass (bool Strip, StringRef NameOfWrappedPass, DebugifyStatsMap * StatsMap, enum DebugifyMode Mode, DebugInfoPerPass * DebugInfoBeforePass, StringRef OrigDIVerifyBugsReportFilePath)
Definition at line 985 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createDebugifyFunctionPass()
FunctionPass* createDebugifyFunctionPass (enum DebugifyMode Mode, llvm::StringRef NameOfWrappedPass, DebugInfoPerPass * DebugInfoBeforePass)
Definition at line 965 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
createDebugifyModulePass()
ModulePass* createDebugifyModulePass (enum DebugifyMode Mode, llvm::StringRef NameOfWrappedPass, DebugInfoPerPass * DebugInfoBeforePass)
Definition at line 955 of file Debugify.cpp.
References assert(), Mode, OriginalDebugInfo, and SyntheticDebugInfo.
Referenced by llvm::DebugifyCustomPassManager::add().
isIgnoredPass()
static bool isIgnoredPass (StringRef PassID) static
Definition at line 1022 of file Debugify.cpp.
References llvm::isSpecialPass().
Referenced by llvm::DebugifyEachInstrumentation::registerCallbacks().
writeJSON()
static void writeJSON (StringRef OrigDIVerifyBugsReportFilePath, StringRef FileNameFromCU, StringRef NameOfWrappedPass, llvm::json::Array & Bugs) static
Definition at line 511 of file Debugify.cpp.
References llvm::errs(), move, llvm::sys::fs::OF_Append, llvm::sys::fs::OF_TextWithCRLF, and PassName.
Referenced by llvm::checkDebugInfoMetadata().
Variable Documentation
CDF
RegisterPass<CheckDebugifyFunctionPass> CDF("check-debugify-function", "Check debug info from -debugify-function") static
CDM
RegisterPass<CheckDebugifyModulePass> CDM("check-debugify", "Check debug info from -debugify") static
DF
RegisterPass<DebugifyFunctionPass> DF("debugify-function", "Attach debug info to a function") static
Referenced by llvm::DILocation::cloneByMultiplyingDuplicationFactor(), llvm::DILocation::cloneWithBaseDiscriminator(), llvm::DILocation::decodeDiscriminator(), llvm::MCFragment::dump(), llvm::DWARFContext::dump(), llvm::MCELFStreamer::emitBundleLock(), llvm::MCELFStreamer::emitBundleUnlock(), llvm::MCObjectStreamer::emitBytes(), llvm::MCWinCOFFStreamer::emitCOFFImgRel32(), llvm::MCWinCOFFStreamer::emitCOFFSecRel32(), llvm::MCWinCOFFStreamer::emitCOFFSectionIndex(), llvm::MCObjectStreamer::emitDTPRel32Value(), llvm::MCObjectStreamer::emitDTPRel64Value(), llvm::MCObjectStreamer::emitFill(), llvm::MCObjectStreamer::emitGPRel32Value(), llvm::MCObjectStreamer::emitGPRel64Value(), llvm::MCXCOFFStreamer::emitInstToData(), llvm::MCWinCOFFStreamer::emitInstToData(), llvm::MCObjectStreamer::emitLabelAtPos(), llvm::MCObjectStreamer::emitNops(), llvm::MCObjectStreamer::emitRelocDirective(), llvm::MCObjectStreamer::emitTPRel32Value(), llvm::MCObjectStreamer::emitTPRel64Value(), RISCVELFStreamer::emitValueImpl(), llvm::MCObjectStreamer::emitValueImpl(), llvm::DILocation::encodeDiscriminator(), llvm::RISCVAsmBackend::evaluateTargetFixup(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::MCAsmBackend::fixupNeedsRelaxationAdvanced(), llvm::DWARFContext::getDebugFrame(), llvm::DWARFContext::getEHFrame(), getOffsetAndDataFragment(), llvm::RISCVMCExpr::getPCRelHiFixup(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::MCInstrInfo::InitMCInstrInfo(), isRightAfterData(), llvm::MCAssembler::layout(), llvm::RISCVAsmBackend::relaxDwarfCFA(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), llvm::DominanceFrontierAnalysis::run(), llvm::RegionInfoAnalysis::run(), llvm::RegionInfoPass::runOnFunction(), llvm::MachineRegionInfoPass::runOnMachineFunction(), and llvm::MCAssembler::writeSectionData().
DM
RegisterPass<DebugifyModulePass> DM("debugify", "Attach debug info to everything") static
Referenced by llvm::PMDataManager::add(), llvm::rdf::DataFlowGraph::build(), llvm::pdb::UDTLayoutBase::initializeChildren(), llvm::PPC::isXXPERMDIShuffleMask(), and llvm::PMTopLevelManager::schedulePass().