LLVM: lib/Demangle/Demangle.cpp File Reference
Demangle.cpp File Reference
#include "llvm/Demangle/Demangle.h"
#include <cstdlib>
#include <cstring>
Functions
static bool isItaniumEncoding (const char *S)
static bool isRustEncoding (const char *S)
static bool isDLangEncoding (const std::string &MangledName)
Function Documentation
isDLangEncoding()
static bool isDLangEncoding (const std::string & MangledName) static
Definition at line 24 of file Demangle.cpp.
Referenced by llvm::nonMicrosoftDemangle().
isItaniumEncoding()
static bool isItaniumEncoding (const char * S) static
Definition at line 17 of file Demangle.cpp.
References S.
Referenced by llvm::nonMicrosoftDemangle().
isRustEncoding()
static bool isRustEncoding (const char * S) static
Definition at line 22 of file Demangle.cpp.
References S.
Referenced by llvm::nonMicrosoftDemangle().