LLVM: lib/Target/DirectX/DirectXTargetMachine.cpp File Reference
DirectXTargetMachine.cpp File Reference
#include "DirectXTargetMachine.h"
#include "DXILResourceAnalysis.h"
#include "DXILShaderFlags.h"
#include "DXILWriter/DXILWriterPass.h"
#include "DirectX.h"
#include "DirectXSubtarget.h"
#include "DirectXTargetTransformInfo.h"
#include "TargetInfo/DirectXTargetInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/MC/MCSectionDXContainer.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Passes/PassBuilder.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include <optional>
Classes
class DXILTargetObjectFile
class DirectXPassConfig
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeDirectXTarget ()
Detailed Description
This file contains DirectX target initializer.
Definition in file DirectXTargetMachine.cpp.
Function Documentation
LLVMInitializeDirectXTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeDirectXTarget ()
Definition at line 39 of file DirectXTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheDirectXTarget(), llvm::initializeDXILOpLoweringLegacyPass(), llvm::initializeDXILPrepareModulePass(), llvm::initializeDXILResourceWrapperPass(), llvm::initializeDXILTranslateMetadataPass(), llvm::initializeEmbedDXILPassPass(), llvm::initializeShaderFlagsAnalysisWrapperPass(), llvm::initializeWriteDXILPassPass(), and X.