LLVM: lib/CodeGen/AsmPrinter/DwarfCompileUnit.cpp File Reference
DwarfCompileUnit.cpp File Reference
#include "DwarfCompileUnit.h"
#include "AddressPool.h"
#include "DwarfExpression.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/DIE.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <iterator>
#include <optional>
#include <string>
#include <utility>
Functions
static dwarf::Tag GetCompileUnitType (UnitKind Kind, DwarfDebug *DW)
static SmallVector< const DIVariable *, 2 > dependencies (DbgVariable *Var)
Return all DIVariables that appear in count: expressions.
static SmallVector< DbgVariable *, 8 > sortLocalVars (SmallVectorImpl< DbgVariable * > &Input)
Sort local variables so that variables appearing inside of helper expressions come first.
Function Documentation
dependencies()
static SmallVector<const DIVariable *, 2> dependencies (DbgVariable * Var) static
Return all DIVariables that appear in count: expressions.
Definition at line 918 of file DwarfCompileUnit.cpp.
References llvm::DbgVariable::getType(), and llvm::ARM_MB::ST.
Referenced by sortLocalVars().
GetCompileUnitType()
static dwarf::Tag GetCompileUnitType (UnitKind Kind, DwarfDebug * DW) static
Definition at line 44 of file DwarfCompileUnit.cpp.
References llvm::DwarfDebug::getDwarfVersion(), and llvm::Skeleton.
sortLocalVars()
static SmallVector<DbgVariable *, 8> sortLocalVars (SmallVectorImpl< DbgVariable * > & Input) static
Sort local variables so that variables appearing inside of helper expressions come first.
Definition at line 964 of file DwarfCompileUnit.cpp.
References assert(), llvm::detail::DenseSetImpl< ValueT, SmallDenseMap< ValueT, detail::DenseSetEmpty, 4, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::count(), dependencies(), llvm::detail::DenseSetImpl< ValueT, SmallDenseMap< ValueT, detail::DenseSetEmpty, 4, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::lookup(), and llvm::reverse().
Referenced by llvm::DwarfCompileUnit::createAndAddScopeChildren().