LLVM: lib/DebugInfo/DWARF/DWARFUnit.cpp File Reference
DWARFUnit.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFAbbreviationDeclaration.h"
#include "llvm/DebugInfo/DWARF/DWARFCompileUnit.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugInfoEntry.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugLoc.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugRangeList.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugRnglists.h"
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
#include "llvm/DebugInfo/DWARF/DWARFExpression.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/DebugInfo/DWARF/DWARFListTable.h"
#include "llvm/DebugInfo/DWARF/DWARFObject.h"
#include "llvm/DebugInfo/DWARF/DWARFSection.h"
#include "llvm/DebugInfo/DWARF/DWARFTypeUnit.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Path.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <utility>
#include <vector>
Functions
static Expected< StrOffsetsContributionDescriptor > parseDWARF64StringOffsetsTableHeader (DWARFDataExtractor &DA, uint64_t Offset)
static Expected< StrOffsetsContributionDescriptor > parseDWARF32StringOffsetsTableHeader (DWARFDataExtractor &DA, uint64_t Offset)
static Expected< StrOffsetsContributionDescriptor > parseDWARFStringOffsetsTableHeader (DWARFDataExtractor &DA, llvm::dwarf::DwarfFormat Format, uint64_t Offset)
Function Documentation
parseDWARF32StringOffsetsTableHeader()
static Expected<StrOffsetsContributionDescriptor> parseDWARF32StringOffsetsTableHeader (DWARFDataExtractor & DA, uint64_t Offset) static
Definition at line 1094 of file DWARFUnit.cpp.
References llvm::createStringError(), llvm::AArch64PACKey::DA, llvm::dwarf::DW_LENGTH_lo_reserved, llvm::dwarf::DWARF32, llvm::invalid_argument, llvm::Offset, and llvm::IndexedInstrProf::Version.
Referenced by parseDWARFStringOffsetsTableHeader().
parseDWARF64StringOffsetsTableHeader()
static Expected<StrOffsetsContributionDescriptor> parseDWARF64StringOffsetsTableHeader (DWARFDataExtractor & DA, uint64_t Offset) static
Definition at line 1076 of file DWARFUnit.cpp.
References llvm::createStringError(), llvm::AArch64PACKey::DA, llvm::dwarf::DW_LENGTH_DWARF64, llvm::dwarf::DWARF64, llvm::invalid_argument, llvm::Offset, uint64_t, and llvm::IndexedInstrProf::Version.
Referenced by parseDWARFStringOffsetsTableHeader().
parseDWARFStringOffsetsTableHeader()
static Expected<StrOffsetsContributionDescriptor> parseDWARFStringOffsetsTableHeader (DWARFDataExtractor & DA, llvm::dwarf::DwarfFormat Format, uint64_t Offset) static
Definition at line 1111 of file DWARFUnit.cpp.
References llvm::createStringError(), llvm::AArch64PACKey::DA, llvm::dwarf::DWARF32, llvm::dwarf::DWARF64, llvm::invalid_argument, llvm::Offset, parseDWARF32StringOffsetsTableHeader(), parseDWARF64StringOffsetsTableHeader(), and llvm::StrOffsetsContributionDescriptor::validateContributionSize().
Referenced by llvm::DWARFUnit::determineStringOffsetsTableContribution(), and llvm::DWARFUnit::determineStringOffsetsTableContributionDWO().