LLVM: lib/Target/DirectX/DXILOpBuilder.cpp File Reference
DXILOpBuilder.cpp File Reference
#include "DXILOpBuilder.h"
#include "DXILConstants.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/DXILOperationCommon.h"
#include "llvm/Support/ErrorHandling.h"
#include "DXILOperation.inc"
Classes
struct OpCodeProperty
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
llvm::dxil
Macros
#define DXIL_OP_OPERATION_TABLE
Functions
static const char * getOverloadTypeName (OverloadKind Kind)
static OverloadKind getOverloadKind (Type *Ty)
static std::string getTypeName (OverloadKind Kind, Type *Ty)
static std::string constructOverloadName (OverloadKind Kind, Type *Ty, const OpCodeProperty &Prop)
static std::string constructOverloadTypeName (OverloadKind Kind, StringRef TypeName)
static StructType * getOrCreateStructType (StringRef Name, ArrayRef< Type * > EltTys, LLVMContext &Ctx)
static StructType * getResRetType (Type *OverloadTy, LLVMContext &Ctx)
static StructType * getHandleType (LLVMContext &Ctx)
static Type * getTypeFromParameterKind (ParameterKind Kind, Type *OverloadTy)
static FunctionType * getDXILOpFunctionType (const OpCodeProperty *Prop, Type *OverloadTy)
static FunctionCallee getOrCreateDXILOpFunction (dxil::OpCode DXILOp, Type *OverloadTy, Module &M)
Variables
constexpr StringLiteral DXILOpNamePrefix = "dx.op."
Macro Definition Documentation
DXIL_OP_OPERATION_TABLE
#define DXIL_OP_OPERATION_TABLE
Definition at line 144 of file DXILOpBuilder.cpp.
Function Documentation
constructOverloadName()
static std::string constructOverloadName (OverloadKind Kind, Type * Ty, const OpCodeProperty & Prop) static
Definition at line 148 of file DXILOpBuilder.cpp.
References DXILOpNamePrefix, and llvm::getTypeName().
Referenced by getOrCreateDXILOpFunction().
constructOverloadTypeName()
static std::string constructOverloadTypeName (OverloadKind Kind, StringRef TypeName) static
Definition at line 158 of file DXILOpBuilder.cpp.
References assert(), getOverloadTypeName(), and llvm::AMDGPU::HSAMD::Kernel::Arg::Key::TypeName.
Referenced by getResRetType().
getDXILOpFunctionType()
static FunctionType* getDXILOpFunctionType (const OpCodeProperty * Prop, Type * OverloadTy) static
Definition at line 223 of file DXILOpBuilder.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::FunctionType::get(), getTypeFromParameterKind(), I, and OpCodeProperty::NumOfParameters.
Referenced by getOrCreateDXILOpFunction().
getHandleType()
static StructType* getHandleType (LLVMContext & Ctx) static
Definition at line 185 of file DXILOpBuilder.cpp.
References llvm::Type::getInt8PtrTy(), and getOrCreateStructType().
Referenced by getTypeFromParameterKind().
getOrCreateDXILOpFunction()
static FunctionCallee getOrCreateDXILOpFunction (dxil::OpCode DXILOp, Type * OverloadTy, Module & M) static
Definition at line 237 of file DXILOpBuilder.cpp.
References constructOverloadName(), getDXILOpFunctionType(), getOverloadKind(), llvm_unreachable, M, and OpCodeProperty::OverloadTys.
Referenced by llvm::dxil::DXILOpBuilder::createDXILOpCall().
getOrCreateStructType()
static StructType* getOrCreateStructType (StringRef Name, ArrayRef< Type * > EltTys, LLVMContext & Ctx) static
Definition at line 167 of file DXILOpBuilder.cpp.
References llvm::StructType::create(), llvm::StructType::getTypeByName(), and llvm::ARM_MB::ST.
Referenced by getHandleType(), and getResRetType().
getOverloadKind()
static OverloadKind getOverloadKind (Type * Ty) static
Definition at line 69 of file DXILOpBuilder.cpp.
References llvm::tgtok::Bits, llvm::Type::DoubleTyID, llvm::Type::FloatTyID, llvm::IntegerType::getBitWidth(), llvm::Type::getTypeID(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, llvm_unreachable, llvm::Type::PointerTyID, llvm::Type::StructTyID, and llvm::Type::VoidTyID.
Referenced by getOrCreateDXILOpFunction(), and getResRetType().
getOverloadTypeName()
static const char* getOverloadTypeName (OverloadKind Kind) static
Definition at line 42 of file DXILOpBuilder.cpp.
References llvm_unreachable.
Referenced by constructOverloadTypeName(), and getTypeName().
getResRetType()
static StructType* getResRetType (Type * OverloadTy, LLVMContext & Ctx) static
Definition at line 177 of file DXILOpBuilder.cpp.
References constructOverloadTypeName(), llvm::Type::getInt32Ty(), getOrCreateStructType(), getOverloadKind(), and llvm::AMDGPU::HSAMD::Kernel::Arg::Key::TypeName.
Referenced by getTypeFromParameterKind().
getTypeFromParameterKind()
static Type* getTypeFromParameterKind (ParameterKind Kind, Type * OverloadTy) static
Definition at line 189 of file DXILOpBuilder.cpp.
References llvm::dxil::DOUBLE, llvm::dxil::DXIL_HANDLE, llvm::dxil::FLOAT, llvm::Type::getContext(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getHalfTy(), getHandleType(), llvm::Type::getInt16Ty(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), getResRetType(), llvm::Type::getVoidTy(), llvm::dxil::HALF, llvm::dxil::I1, llvm::dxil::I16, llvm::dxil::I32, llvm::dxil::I64, llvm::dxil::I8, llvm_unreachable, llvm::dxil::OVERLOAD, llvm::dxil::RESOURCE_RET, and llvm::dxil::VOID.
Referenced by getDXILOpFunctionType().
getTypeName()
static std::string getTypeName (OverloadKind Kind, Type * Ty) static
Definition at line 109 of file DXILOpBuilder.cpp.
References getOverloadTypeName(), OS, llvm::Type::print(), and llvm::ARM_MB::ST.
Variable Documentation
DXILOpNamePrefix
constexpr StringLiteral DXILOpNamePrefix = "dx.op." constexpr
Definition at line 22 of file DXILOpBuilder.cpp.
Referenced by constructOverloadName().