LLVM: lib/ObjCopy/ELF/ELFObjcopy.cpp File Reference
ELFObjcopy.cpp File Reference
#include "llvm/ObjCopy/ELF/ELFObjcopy.h"
#include "ELFObject.h"
#include "llvm/ADT/BitmaskEnum.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/ObjCopy/CommonConfig.h"
#include "llvm/ObjCopy/ELF/ELFConfig.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Object/ELFTypes.h"
#include "llvm/Object/Error.h"
#include "llvm/Option/Option.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Memory.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdlib>
#include <functional>
#include <iterator>
#include <memory>
#include <string>
#include <system_error>
#include <utility>
Typedefs
using SectionPred = std::function< bool(const SectionBase &Sec)>
Functions
static bool isDebugSection (const SectionBase &Sec)
static bool isDWOSection (const SectionBase &Sec)
static bool onlyKeepDWOPred (const Object &Obj, const SectionBase &Sec)
static uint64_t getNewShfFlags (SectionFlag AllFlags)
static uint64_t getSectionFlagsPreserveMask (uint64_t OldFlags, uint64_t NewFlags)
static void setSectionFlagsAndType (SectionBase &Sec, SectionFlag Flags)
static ElfType getOutputElfType (const Binary &Bin)
static ElfType getOutputElfType (const MachineInfo &MI)
static std::unique_ptr< Writer > createELFWriter (const CommonConfig &Config, Object &Obj, raw_ostream &Out, ElfType OutputElfType)
static std::unique_ptr< Writer > createWriter (const CommonConfig &Config, Object &Obj, raw_ostream &Out, ElfType OutputElfType)
template<class... Ts>
static Error makeStringError (std::error_code EC, const Twine &Msg, Ts &&...Args)
static Error dumpSectionToFile (StringRef SecName, StringRef Filename, Object &Obj)
static bool isCompressable (const SectionBase &Sec)
static Error replaceDebugSections (Object &Obj, function_ref< bool(const SectionBase &)> ShouldReplace, function_ref< Expected< SectionBase * >(const SectionBase *)> AddSection)
static bool isAArch64MappingSymbol (const Symbol &Sym)
static bool isArmMappingSymbol (const Symbol &Sym)
static bool isRequiredByABISymbol (const Object &Obj, const Symbol &Sym)
static bool isUnneededSymbol (const Symbol &Sym)
static Error updateAndRemoveSymbols (const CommonConfig &Config, const ELFConfig &ELFConfig, Object &Obj)
static Error replaceAndRemoveSections (const CommonConfig &Config, const ELFConfig &ELFConfig, Object &Obj)
static void addSymbol (Object &Obj, const NewSymbolInfo &SymInfo, uint8_t DefaultVisibility)
static Error handleUserSection (const NewSectionInfo &NewSection, function_ref< Error(StringRef, ArrayRef< uint8_t >)> F)
static Error handleArgs (const CommonConfig &Config, const ELFConfig &ELFConfig, Object &Obj)
static Error writeOutput (const CommonConfig &Config, Object &Obj, raw_ostream &Out, ElfType OutputElfType)
Typedef Documentation
SectionPred
using SectionPred = std::function<bool(const SectionBase &Sec)>
Definition at line 52 of file ELFObjcopy.cpp.
Function Documentation
addSymbol()
static void addSymbol (Object & Obj, const NewSymbolInfo & SymInfo, uint8_t DefaultVisibility) static
Definition at line 530 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::SectionBase::Addr, llvm::objcopy::elf::SymbolTableSection::addSymbol(), llvm::TargetStackID::Default, llvm::ARMBuildAttrs::File, llvm::objcopy::elf::Object::findSection(), llvm::cl::Hidden, llvm::ARMBuildAttrs::Section, llvm::ELF::SHN_ABS, llvm::ELF::STB_GLOBAL, llvm::ELF::STB_LOCAL, llvm::ELF::STB_WEAK, llvm::ELF::STT_FILE, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, llvm::ELF::STV_DEFAULT, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_PROTECTED, llvm::objcopy::elf::SYMBOL_SIMPLE_INDEX, llvm::objcopy::elf::Object::SymbolTable, and uint64_t.
Referenced by handleArgs().
createELFWriter()
static std::unique_ptr<Writer> createELFWriter (const CommonConfig & Config, Object & Obj, raw_ostream & Out, ElfType OutputElfType) static
Definition at line 133 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::ELFT_ELF32BE, llvm::objcopy::elf::ELFT_ELF32LE, llvm::objcopy::elf::ELFT_ELF64BE, llvm::objcopy::elf::ELFT_ELF64LE, llvm_unreachable, llvm::objcopy::CommonConfig::OnlyKeepDebug, and llvm::objcopy::CommonConfig::StripSections.
Referenced by createWriter().
createWriter()
static std::unique_ptr<Writer> createWriter (const CommonConfig & Config, Object & Obj, raw_ostream & Out, ElfType OutputElfType) static
Definition at line 154 of file ELFObjcopy.cpp.
References createELFWriter(), and llvm::objcopy::CommonConfig::OutputFormat.
Referenced by writeOutput().
dumpSectionToFile()
static Error dumpSectionToFile (StringRef SecName, StringRef Filename, Object & Obj) static
Definition at line 174 of file ELFObjcopy.cpp.
References copy, llvm::FileOutputBuffer::create(), llvm::createStringError(), E, move, llvm::objcopy::elf::Object::sections(), llvm::ELF::SHT_NOBITS, llvm::StringRef::str(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by handleArgs().
getNewShfFlags()
static uint64_t getNewShfFlags (SectionFlag AllFlags) static
Definition at line 71 of file ELFObjcopy.cpp.
References llvm::objcopy::SecAlloc, llvm::objcopy::SecCode, llvm::objcopy::SecExclude, llvm::objcopy::SecMerge, llvm::objcopy::SecReadonly, llvm::objcopy::SecStrings, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_WRITE, and uint64_t.
Referenced by setSectionFlagsAndType().
getOutputElfType() [1/2]
static ElfType getOutputElfType (const Binary & Bin) static
Definition at line 112 of file ELFObjcopy.cpp.
References llvm::Bin, llvm::objcopy::elf::ELFT_ELF32BE, llvm::objcopy::elf::ELFT_ELF32LE, llvm::objcopy::elf::ELFT_ELF64BE, llvm::objcopy::elf::ELFT_ELF64LE, llvm::isa(), and llvm_unreachable.
Referenced by llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnIHex(), and llvm::objcopy::elf::executeObjcopyOnRawBinary().
getOutputElfType() [2/2]
static ElfType getOutputElfType (const MachineInfo & MI) static
Definition at line 125 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::ELFT_ELF32BE, llvm::objcopy::elf::ELFT_ELF32LE, llvm::objcopy::elf::ELFT_ELF64BE, llvm::objcopy::elf::ELFT_ELF64LE, and MI.
getSectionFlagsPreserveMask()
static uint64_t getSectionFlagsPreserveMask (uint64_t OldFlags, uint64_t NewFlags) static
Definition at line 88 of file ELFObjcopy.cpp.
References llvm::ELF::SHF_COMPRESSED, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_INFO_LINK, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_MASKOS, llvm::ELF::SHF_MASKPROC, llvm::ELF::SHF_TLS, and uint64_t.
Referenced by setSectionFlagsAndType().
handleArgs()
static Error handleArgs (const CommonConfig & Config, const ELFConfig & ELFConfig, Object & Obj) static
Definition at line 599 of file ELFObjcopy.cpp.
References llvm::objcopy::CommonConfig::AddGnuDebugLink, llvm::objcopy::elf::Object::addNewSymbolTable(), llvm::objcopy::CommonConfig::AddSection, llvm::objcopy::elf::Object::addSection(), addSymbol(), llvm::objcopy::CommonConfig::AllocSectionsPrefix, llvm::objcopy::ELFConfig::AllowBrokenLinks, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::count(), llvm::Data, llvm::objcopy::CommonConfig::DumpSection, dumpSectionToFile(), E, llvm::StringMapImpl::empty(), llvm::StringRef::empty(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::end(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::objcopy::elf::Object::Entry, llvm::objcopy::ELFConfig::EntryExpr, llvm::objcopy::CommonConfig::ExtractDWO, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::find(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::objcopy::elf::SectionBase::Flags, llvm::objcopy::CommonConfig::GnuDebugLinkCRC32, handleUserSection(), I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::objcopy::elf::Object::Machine, llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::SectionRename::NewFlags, llvm::objcopy::SectionFlagsUpdate::NewFlags, llvm::objcopy::SectionRename::NewName, llvm::objcopy::ELFConfig::NewSymbolVisibility, llvm::objcopy::CommonConfig::OnlyKeepDebug, llvm::objcopy::elf::Object::OSABI, llvm::objcopy::CommonConfig::OutputArch, llvm::objcopy::elf::Object::removeSections(), replaceAndRemoveSections(), llvm::AMDGPU::ElfNote::SectionName, llvm::objcopy::elf::Object::sections(), llvm::objcopy::CommonConfig::SectionsToRename, llvm::objcopy::CommonConfig::SetSectionAlignment, llvm::objcopy::CommonConfig::SetSectionFlags, setSectionFlagsAndType(), llvm::objcopy::CommonConfig::SetSectionType, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, SI, llvm::objcopy::CommonConfig::SplitDWO, llvm::Error::success(), llvm::objcopy::CommonConfig::SymbolsToAdd, llvm::objcopy::elf::Object::SymbolTable, llvm::objcopy::elf::SectionBase::Type, updateAndRemoveSymbols(), llvm::objcopy::CommonConfig::UpdateSection, and llvm::objcopy::elf::Object::updateSection().
Referenced by llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnIHex(), and llvm::objcopy::elf::executeObjcopyOnRawBinary().
handleUserSection()
static Error handleUserSection (const NewSectionInfo & NewSection, function_ref< Error(StringRef, ArrayRef< uint8_t >)> F) static
Definition at line 584 of file ELFObjcopy.cpp.
References llvm::Data, F, llvm::objcopy::NewSectionInfo::SectionData, and llvm::objcopy::NewSectionInfo::SectionName.
Referenced by handleArgs().
isAArch64MappingSymbol()
static bool isAArch64MappingSymbol (const Symbol & Sym) static
Definition at line 227 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::Symbol::Binding, llvm::objcopy::elf::Symbol::getShndx(), llvm::objcopy::elf::Symbol::Name, llvm::ELF::SHN_UNDEF, llvm::ELF::STB_LOCAL, llvm::ELF::STT_NOTYPE, and llvm::objcopy::elf::Symbol::Type.
Referenced by isRequiredByABISymbol().
isArmMappingSymbol()
static bool isArmMappingSymbol (const Symbol & Sym) static
Definition at line 237 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::Symbol::Binding, llvm::objcopy::elf::Symbol::getShndx(), llvm::objcopy::elf::Symbol::Name, llvm::ELF::SHN_UNDEF, llvm::ELF::STB_LOCAL, llvm::ELF::STT_NOTYPE, and llvm::objcopy::elf::Symbol::Type.
Referenced by isRequiredByABISymbol().
isCompressable()
static bool isCompressable (const SectionBase & Sec) static
Definition at line 198 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::SectionBase::Flags, llvm::objcopy::elf::SectionBase::Name, llvm::ELF::SHF_COMPRESSED, and llvm::StringRef::startswith().
isDebugSection()
static bool isDebugSection (const SectionBase & Sec) static
Definition at line 54 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::SectionBase::Name, and llvm::StringRef::startswith().
Referenced by llvm::object::XCOFFObjectFile::getSymbolType(), and replaceAndRemoveSections().
isDWOSection()
static bool isDWOSection (const SectionBase & Sec) static
Definition at line 58 of file ELFObjcopy.cpp.
References llvm::StringRef::endswith(), and llvm::objcopy::elf::SectionBase::Name.
Referenced by onlyKeepDWOPred(), and replaceAndRemoveSections().
isRequiredByABISymbol()
static bool isRequiredByABISymbol (const Object & Obj, const Symbol & Sym) static
Definition at line 249 of file ELFObjcopy.cpp.
References llvm::ELF::EM_AARCH64, llvm::ELF::EM_ARM, isAArch64MappingSymbol(), isArmMappingSymbol(), llvm::objcopy::elf::Object::isRelocatable(), and llvm::objcopy::elf::Object::Machine.
Referenced by updateAndRemoveSymbols().
isUnneededSymbol()
static bool isUnneededSymbol (const Symbol & Sym) static
Definition at line 262 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::Symbol::Binding, llvm::objcopy::elf::Symbol::getShndx(), llvm::objcopy::elf::Symbol::Referenced, llvm::ELF::SHN_UNDEF, llvm::ELF::STB_LOCAL, llvm::ELF::STT_SECTION, and llvm::objcopy::elf::Symbol::Type.
Referenced by updateAndRemoveSymbols().
makeStringError()
template<class... Ts> static Error makeStringError (std::error_code EC, const Twine & Msg, Ts &&... Args) static
Definition at line 168 of file ELFObjcopy.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::createStringError(), and llvm::AMDGPU::SendMsg::Msg.
onlyKeepDWOPred()
static bool onlyKeepDWOPred (const Object & Obj, const SectionBase & Sec) static
Definition at line 62 of file ELFObjcopy.cpp.
References isDWOSection(), and llvm::objcopy::elf::Object::SectionNames.
Referenced by replaceAndRemoveSections().
replaceAndRemoveSections()
static Error replaceAndRemoveSections (const CommonConfig & Config, const ELFConfig & ELFConfig, Object & Obj) static
Definition at line 368 of file ELFObjcopy.cpp.
References llvm::objcopy::ELFConfig::AllowBrokenLinks, llvm::objcopy::CommonConfig::CompressionType, E, llvm::objcopy::NameMatcher::empty(), llvm::objcopy::elf::SymbolTableSection::empty(), llvm::objcopy::CommonConfig::ExtractDWO, llvm::objcopy::CommonConfig::ExtractMainPartition, llvm::objcopy::CommonConfig::ExtractPartition, llvm::objcopy::elf::SymbolTableSection::getStrTab(), isDebugSection(), isDWOSection(), llvm::objcopy::ELFConfig::KeepFileSymbols, llvm::objcopy::CommonConfig::KeepSection, llvm::objcopy::NameMatcher::matches(), llvm::None, onlyKeepDWOPred(), llvm::objcopy::CommonConfig::OnlySection, llvm::objcopy::elf::Object::removeSections(), llvm::objcopy::elf::Object::SectionNames, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_ARM_ATTRIBUTES, llvm::ELF::SHT_LLVM_PART_EHDR, llvm::ELF::SHT_LLVM_PART_PHDR, llvm::ELF::SHT_REL, llvm::ELF::SHT_RELA, llvm::ELF::SHT_STRTAB, llvm::ELF::SHT_SYMTAB, llvm::StringRef::startswith(), llvm::objcopy::CommonConfig::StripAll, llvm::objcopy::CommonConfig::StripAllGNU, llvm::objcopy::CommonConfig::StripDebug, llvm::objcopy::CommonConfig::StripDWO, llvm::objcopy::CommonConfig::StripNonAlloc, llvm::objcopy::CommonConfig::StripSections, llvm::objcopy::CommonConfig::StripUnneeded, llvm::objcopy::CommonConfig::SymbolsToKeep, llvm::objcopy::elf::Object::SymbolTable, and llvm::objcopy::CommonConfig::ToRemove.
Referenced by handleArgs().
replaceDebugSections()
static Error replaceDebugSections (Object & Obj, function_ref< bool(const SectionBase &)> ShouldReplace, function_ref< Expected< SectionBase * >(const SectionBase *)> AddSection) static
Definition at line 203 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::Object::replaceSections(), S, llvm::objcopy::elf::Object::sections(), and llvm::Expected< T >::takeError().
setSectionFlagsAndType()
static void setSectionFlagsAndType (SectionBase & Sec, SectionFlag Flags) static
Definition at line 100 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::SectionBase::Flags, getNewShfFlags(), getSectionFlagsPreserveMask(), llvm::objcopy::SecContents, llvm::objcopy::SecLoad, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_PROGBITS, and llvm::objcopy::elf::SectionBase::Type.
Referenced by handleArgs().
updateAndRemoveSymbols()
static Error updateAndRemoveSymbols (const CommonConfig & Config, const ELFConfig & ELFConfig, Object & Obj) static
Definition at line 268 of file ELFObjcopy.cpp.
References llvm::objcopy::elf::Symbol::Binding, llvm::objcopy::CommonConfig::DiscardMode, llvm::StringRef::empty(), llvm::objcopy::NameMatcher::empty(), llvm::objcopy::elf::Symbol::getShndx(), I, if(), llvm::objcopy::elf::Symbol::isCommon(), llvm::objcopy::elf::Object::isRelocatable(), isRequiredByABISymbol(), isUnneededSymbol(), llvm::objcopy::ELFConfig::KeepFileSymbols, llvm::objcopy::ELFConfig::LocalizeHidden, llvm::objcopy::NameMatcher::matches(), llvm::objcopy::elf::Symbol::Name, llvm::objcopy::CommonConfig::OnlySection, llvm::objcopy::elf::Symbol::Referenced, llvm::objcopy::elf::Object::removeSymbols(), llvm::objcopy::elf::Object::sections(), llvm::ELF::SHN_UNDEF, llvm::StringRef::startswith(), llvm::ELF::STB_GLOBAL, llvm::ELF::STB_LOCAL, llvm::ELF::STB_WEAK, llvm::objcopy::CommonConfig::StripAll, llvm::objcopy::CommonConfig::StripAllGNU, llvm::objcopy::CommonConfig::StripDebug, llvm::objcopy::CommonConfig::StripUnneeded, llvm::ELF::STT_FILE, llvm::ELF::STT_SECTION, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, llvm::Error::success(), llvm::objcopy::CommonConfig::SymbolsPrefix, llvm::objcopy::CommonConfig::SymbolsToGlobalize, llvm::objcopy::CommonConfig::SymbolsToKeep, llvm::objcopy::CommonConfig::SymbolsToKeepGlobal, llvm::objcopy::CommonConfig::SymbolsToLocalize, llvm::objcopy::CommonConfig::SymbolsToRemove, llvm::objcopy::CommonConfig::SymbolsToRename, llvm::objcopy::CommonConfig::SymbolsToWeaken, llvm::objcopy::elf::Object::SymbolTable, llvm::objcopy::elf::Symbol::Type, llvm::objcopy::CommonConfig::UnneededSymbolsToRemove, llvm::objcopy::elf::SymbolTableSection::updateSymbols(), llvm::objcopy::elf::Symbol::Visibility, and llvm::objcopy::CommonConfig::Weaken.
Referenced by handleArgs().
writeOutput()
static Error writeOutput (const CommonConfig & Config, Object & Obj, raw_ostream & Out, ElfType OutputElfType) static
Definition at line 760 of file ELFObjcopy.cpp.
References createWriter(), E, llvm::objcopy::elf::Writer::finalize(), and llvm::objcopy::elf::Writer::write().
Referenced by llvm::objcopy::elf::executeObjcopyOnBinary(), llvm::objcopy::elf::executeObjcopyOnIHex(), and llvm::objcopy::elf::executeObjcopyOnRawBinary().