LLVM: lib/Object/ELFObjectFile.cpp File Reference
ELFObjectFile.cpp File Reference
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Object/ELF.h"
#include "llvm/Object/ELFTypes.h"
#include "llvm/Object/Error.h"
#include "llvm/Support/ARMAttributeParser.h"
#include "llvm/Support/ARMBuildAttributes.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/RISCVAttributeParser.h"
#include "llvm/Support/RISCVAttributes.h"
#include "llvm/Support/RISCVISAInfo.h"
#include "llvm/TargetParser/Triple.h"
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <utility>
Functions
template<class ELFT >
static Expected< std::unique_ptr< ELFObjectFile< ELFT > > > createPtr (MemoryBufferRef Object, bool InitContent)
template<class ELFT >
static Expected< std::vector< BBAddrMap > > readBBAddrMapImpl (const ELFFile< ELFT > &EF, std::optional< unsigned > TextSectionIndex)
template<class ELFT >
static Expected< std::vector< VersionEntry > > readDynsymVersionsImpl (const ELFFile< ELFT > &EF, ELFObjectFileBase::elf_symbol_iterator_range Symbols)
Function Documentation
createPtr()
template<class ELFT > static Expected<std::unique_ptr<ELFObjectFile<ELFT> > > createPtr (MemoryBufferRef Object, bool InitContent) static
Definition at line 64 of file ELFObjectFile.cpp.
References llvm::object::ELFObjectFile< ELFT >::create(), E, move, llvm::Object, and llvm::MipsISD::Ret.
readBBAddrMapImpl()
template<class ELFT > static Expected<std::vector<BBAddrMap> > readBBAddrMapImpl (const ELFFile< ELFT > & EF, std::optional< unsigned > TextSectionIndex) static
Definition at line 681 of file ELFObjectFile.cpp.
References llvm::cantFail(), llvm::object::createError(), llvm::object::describe(), move, Shdr, llvm::ELF::SHT_LLVM_BB_ADDR_MAP, llvm::ELF::SHT_LLVM_BB_ADDR_MAP_V0, llvm::Expected< T >::takeError(), and llvm::toString().
Referenced by llvm::object::ELFObjectFileBase::readBBAddrMap().
readDynsymVersionsImpl()
template<class ELFT > static Expected<std::vector<VersionEntry> > readDynsymVersionsImpl (const ELFFile< ELFT > & EF, ELFObjectFileBase::elf_symbol_iterator_range Symbols) static
Definition at line 711 of file ELFObjectFile.cpp.
References llvm::cantFail(), llvm::object::createError(), llvm::object::describe(), I, llvm::MipsISD::Ret, llvm::object::BasicSymbolRef::SF_Undefined, Shdr, llvm::ELF::SHT_GNU_verdef, llvm::ELF::SHT_GNU_verneed, llvm::ELF::SHT_GNU_versym, llvm::Expected< T >::takeError(), and llvm::toString().
Referenced by llvm::object::ELFObjectFileBase::readDynsymVersions().