LLVM: lib/Transforms/Utils/EntryExitInstrumenter.cpp File Reference
EntryExitInstrumenter.cpp File Reference
#include "llvm/Transforms/Utils/EntryExitInstrumenter.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Transforms/Utils.h"
Functions
static void insertCall (Function &CurFn, StringRef Func, Instruction *InsertionPt, DebugLoc DL)
static bool runOnFunction (Function &F, bool PostInlining)
Function Documentation
insertCall()
static void insertCall (Function & CurFn, StringRef Func, Instruction * InsertionPt, DebugLoc DL) static
Definition at line 25 of file EntryExitInstrumenter.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::CallInst::Create(), DL, llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::ConstantExpr::getBitCast(), llvm::BasicBlock::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Type::getPointerTo(), llvm::Type::getVoidTy(), llvm::GlobalValue::InternalLinkage, llvm::Triple::isOSAIX(), M, llvm::report_fatal_error(), and llvm::Instruction::setDebugLoc().
Referenced by runOnFunction().
runOnFunction()
static bool runOnFunction (Function & F, bool PostInlining) static
Definition at line 85 of file EntryExitInstrumenter.cpp.
References BB, DL, llvm::StringRef::empty(), F, llvm::MDNode::get(), and insertCall().
Referenced by INITIALIZE_PASS(), llvm::EntryExitInstrumenterPass::run(), and llvm::AssignmentTrackingPass::run().