LLVM: lib/CodeGen/AsmPrinter/ErlangGCPrinter.cpp File Reference
ErlangGCPrinter.cpp File Reference
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/GCMetadata.h"
#include "llvm/CodeGen/GCMetadataPrinter.h"
#include "llvm/IR/BuiltinGCs.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Variables
static GCMetadataPrinterRegistry::Add< ErlangGCPrinter > X ("erlang", "erlang-compatible garbage collector")
Variable Documentation
X
GCMetadataPrinterRegistry::Add<ErlangGCPrinter> X("erlang", "erlang-compatible garbage collector") static
Examples
/home/cambricon/llvm/llvm-project/llvm/include/llvm/Transforms/Utils/Local.h.
Referenced by llvm::abs(), llvm::AbsoluteDifference(), llvm::ConstantRange::add(), llvm::cl::parser< const PassInfo * >::addLiteralOption(), llvm::AddOverflow(), llvm::ScheduleDAGTopologicalSort::AddPred(), llvm::ScheduleDAGTopologicalSort::AddPredQueued(), llvm::AllocatorList< Token >::AllocatorList(), annotateNonNullAndDereferenceable(), AMDGPUCombinerHelper::applyFoldableFneg(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), AMDGPUPostLegalizerCombinerHelper::applySelectFCmpToFMinToFMaxLegacy(), llvm::CombinerHelper::applyXorOfAndWithSameReg(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), canAlwaysEvaluateInType(), canonicalizeBitSelect(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeInsertSplat(), canonicalizeLogicFirst(), canonicalizeSaturatedAdd(), llvm::capacity_in_bytes(), CheckAndCreateOffsetAdd(), checkForNegativeOperand(), llvm::checkVOPDRegConstraints(), clusterSortPtrAccesses(), collectBitParts(), combineADDCARRYDiamond(), combineAddOrSubToADCOrSBB(), combineAndMaskToShift(), combineAndNotIntoANDNP(), combineAndShuffleNot(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineShiftAnd1ToBitTest(), combineShiftOfShiftedLogic(), combineSubABS(), combineVectorShiftImm(), combineVectorSizedSetCCEquality(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::ScaledNumber< uint64_t >::compare(), CompareSCEVComplexity(), llvm::ComputeEditDistance(), llvm::FoldingSetTrait< SDVTListNode >::ComputeHash(), llvm::FoldingSetTrait< SCEV >::ComputeHash(), llvm::DefaultFoldingSetTrait< SCEVPredicate >::ComputeHash(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::ComputeHash(), llvm::FoldingSetTrait< SCEVPredicate >::ComputeHash(), computeKnownBitsFromOperator(), ComputeNumSignBitsImpl(), llvm::codeview::consume(), llvm::Trace::contains(), createAArch64MCInstrInfo(), createAArch64MCRegisterInfo(), createAMDGPUMCInstrInfo(), createAMDGPUMCRegisterInfo(), createARCMCInstrInfo(), createARCMCRegisterInfo(), createARMMCInstrInfo(), createARMMCRegisterInfo(), llvm::OpenMPIRBuilder::createAtomicCapture(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicUpdate(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::createAVRMCInstrInfo(), createAVRMCRegisterInfo(), createBPFMCInstrInfo(), createBPFMCRegisterInfo(), llvm::createGCNMCRegisterInfo(), llvm::createHexagonMCInstrInfo(), createHexagonMCRegisterInfo(), llvm::Hexagon_MC::createHexagonMCSubtargetInfo(), createLanaiMCInstrInfo(), createLanaiMCRegisterInfo(), createLoongArchMCInstrInfo(), createLoongArchMCRegisterInfo(), createM68kMCInstrInfo(), createM68kMCRegisterInfo(), createMCInstrInfo(), createMCRegisterInfo(), createMipsMCInstrInfo(), createMipsMCRegisterInfo(), createMSP430MCInstrInfo(), createMSP430MCRegisterInfo(), createNodeForSelectViaUMinSeq(), createNVPTXMCInstrInfo(), createNVPTXMCRegisterInfo(), createPPCMCInstrInfo(), createPPCMCRegisterInfo(), llvm::createR600MCInstrInfo(), createRISCVMCInstrInfo(), createRISCVMCRegisterInfo(), createSparcMCInstrInfo(), createSparcMCRegisterInfo(), createSPIRVMCInstrInfo(), createSPIRVMCRegisterInfo(), createSystemZMCInstrInfo(), createSystemZMCRegisterInfo(), createVEMCInstrInfo(), createVEMCRegisterInfo(), createX86MCInstrInfo(), createX86MCRegisterInfo(), createXCoreMCInstrInfo(), createXCoreMCRegisterInfo(), createXtensaMCInstrInfo(), createXtensaMCRegisterInfo(), llvm::decomposeBitTestICmp(), decomposeBitTestICmp(), llvm::DIEValue::DIEValue(), dropRedundantMaskingOfLeftShiftInput(), llvm::MCDwarfFrameEmitter::Emit(), emitOrXorXorTree(), emitTransformedIndex(), llvm::FoldingSetTrait< SDVTListNode >::Equals(), llvm::FoldingSetTrait< SCEV >::Equals(), llvm::DefaultFoldingSetTrait< SCEVPredicate >::Equals(), llvm::FoldingSetTrait< SCEVPredicate >::Equals(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Equals(), llvm::PriorityWorklist< llvm::LazyCallGraph::SCC *, SmallVector< llvm::LazyCallGraph::SCC *, N >, SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t > >::erase(), expandLog(), expandLog10(), expandLog2(), expandUDivOrURem(), factorizeFAddFSub(), factorizeLerp(), factorizeMathWithShlOps(), llvm::LiveRange::find(), llvm::OnDiskChainedHashTable< Info >::find_hashed(), findGCD(), FindInOperandList(), foldAddToAshr(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpsWithConstEq(), foldBitCastBitwiseLogic(), foldBitCastSelect(), foldBoxMultiply(), foldCastShuffle(), foldClampRangeOfTwo(), foldComplexAndOrPatterns(), foldCSELOfCSEL(), foldCSELofCTTZ(), foldCtpop(), foldCttzCtlz(), foldExtendedSignBitTest(), foldFabsWithFcmpZero(), foldFDivConstantDividend(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAddOpConst(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpOrConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUDivConstant(), llvm::InstCombinerImpl::foldICmpUsingBoolRange(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldICmpWithHighBitMask(), foldICmpWithLowBitMaskedVal(), foldICmpWithMinMax(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldICmpXNegX(), llvm::InstCombinerImpl::foldICmpXorConstant(), llvm::InstCombinerImpl::foldICmpXorShiftConst(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldIDivShl(), foldInsEltIntoIdentityShuffle(), foldInsEltIntoSplat(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), foldIsPowerOf2(), foldIsPowerOf2OrZero(), llvm::InstCombinerImpl::foldItoFPtoI(), foldLoadsRecursive(), foldLogicCastConstant(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), foldMinMaxSharedOp(), foldMulShl1(), llvm::InstCombinerImpl::foldMultiplicationOverflowCheck(), foldNotXor(), foldNoWrapAdd(), foldSelectBinOpIdentity(), foldSelectICmpAndAnd(), foldSelectICmpLshrAshr(), foldSelectOfConstantsUsingSra(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleOfSelectShuffle(), foldSelectShuffleWith1Binop(), foldSelectWithBinaryOp(), foldSelectZeroOrMul(), foldSetCCWithFunnelShift(), foldSetCCWithRotate(), foldSetClearBits(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), foldShuffledIntrinsicOperands(), foldShuffleOfConcatUndefs(), foldShuffleOfUnaryOps(), foldShuffleWithInsert(), llvm::InstCombinerImpl::foldSignBitTest(), foldSignedTruncationCheck(), foldSubOfMinMax(), foldToUnsignedSaturatedAdd(), foldTruncInsEltPair(), foldTruncShuffle(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), llvm::FmtAlign::format(), llvm::format_provider< T, std::enable_if_t< detail::use_char_formatter< T >::value > >::format(), llvm::PMDataManager::freePass(), llvm::frexp(), genConstMult(), llvm::APSInt::get(), llvm::get_hashable_data(), llvm::ScalarEvolution::getAddExpr(), llvm::Trace::getBlockIndex(), llvm::DenseMapInfo< ImmutableList< T >, void >::getHashValue(), getHashValueImpl(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::AMDGPU::VOPD::InstInfo::getInvalidCompOperandIndex(), getKnownSign(), getLimitedPrecisionExp2(), llvm::objcopy::elf::IHexRecord::getLine(), llvm::TargetLowering::getNegatedExpression(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::APSInt::getUnsigned(), llvm::SDNode::getVTList(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::HandleSDNode::HandleSDNode(), llvm::TargetLoweringBase::hasAndNot(), llvm::HexagonTargetLowering::hasBitTest(), llvm::RISCVTargetLowering::hasBitTest(), llvm::X86TargetLowering::hasBitTest(), hoistFNegAboveFMulFDiv(), hoistInsEltConst(), INITIALIZE_PASS(), llvm::PriorityWorklist< llvm::LazyCallGraph::SCC *, SmallVector< llvm::LazyCallGraph::SCC *, N >, SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t > >::insert(), llvm::SetVector< llvm::MCSection *, SmallVector< llvm::MCSection *, N >, SmallDenseSet< llvm::MCSection *, N > >::insert(), llvm::isa_and_nonnull(), llvm::isa_and_present(), llvm::isCheckForZeroAndMulWithOverflow(), isDivZero(), isEqualImpl(), llvm::X86MCExpr::isEqualTo(), llvm::HexagonBlockRanges::IndexType::isInstr(), llvm::isKnownNegation(), isKnownToBeAPowerOfTwo(), isMatchingReloc(), isOrXorXorTree(), isSimpleCastedPHI(), llvm::isSplatValue(), isTruePredicate(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM32Impl(), LLVMInitializeAArch64AsmParser(), LLVMInitializeAArch64AsmPrinter(), LLVMInitializeAArch64Target(), LLVMInitializeAArch64TargetInfo(), LLVMInitializeAArch64TargetMC(), LLVMInitializeAMDGPUTarget(), LLVMInitializeAMDGPUTargetMC(), LLVMInitializeARCAsmPrinter(), LLVMInitializeARCTarget(), LLVMInitializeARCTargetInfo(), LLVMInitializeARCTargetMC(), LLVMInitializeARMAsmParser(), LLVMInitializeARMAsmPrinter(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeARMTargetMC(), LLVMInitializeAVRAsmParser(), LLVMInitializeAVRAsmPrinter(), llvm::LLVMInitializeAVRTarget(), LLVMInitializeAVRTargetInfo(), LLVMInitializeAVRTargetMC(), LLVMInitializeBPFAsmParser(), LLVMInitializeBPFAsmPrinter(), LLVMInitializeBPFTarget(), LLVMInitializeBPFTargetInfo(), LLVMInitializeBPFTargetMC(), LLVMInitializeCSKYAsmParser(), LLVMInitializeCSKYAsmPrinter(), LLVMInitializeCSKYTarget(), LLVMInitializeCSKYTargetInfo(), LLVMInitializeDirectXAsmPrinter(), LLVMInitializeDirectXTarget(), LLVMInitializeDirectXTargetInfo(), LLVMInitializeDirectXTargetMC(), LLVMInitializeHexagonAsmParser(), LLVMInitializeHexagonAsmPrinter(), LLVMInitializeHexagonTarget(), LLVMInitializeHexagonTargetInfo(), LLVMInitializeHexagonTargetMC(), LLVMInitializeLanaiAsmPrinter(), LLVMInitializeLanaiTargetInfo(), LLVMInitializeLanaiTargetMC(), LLVMInitializeLoongArchAsmParser(), LLVMInitializeLoongArchAsmPrinter(), LLVMInitializeLoongArchTarget(), LLVMInitializeLoongArchTargetInfo(), LLVMInitializeM68kAsmParser(), LLVMInitializeM68kAsmPrinter(), LLVMInitializeM68kTarget(), LLVMInitializeM68kTargetInfo(), LLVMInitializeM68kTargetMC(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsAsmPrinter(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializeMipsTargetMC(), LLVMInitializeMSP430AsmParser(), LLVMInitializeMSP430AsmPrinter(), LLVMInitializeMSP430Target(), LLVMInitializeMSP430TargetInfo(), LLVMInitializeMSP430TargetMC(), LLVMInitializeNVPTXAsmPrinter(), LLVMInitializeNVPTXTarget(), LLVMInitializeNVPTXTargetInfo(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetInfo(), LLVMInitializeRISCVAsmPrinter(), LLVMInitializeRISCVTarget(), LLVMInitializeRISCVTargetInfo(), LLVMInitializeSparcAsmPrinter(), LLVMInitializeSparcTarget(), LLVMInitializeSparcTargetInfo(), LLVMInitializeSparcTargetMC(), LLVMInitializeSPIRVAsmPrinter(), LLVMInitializeSPIRVTarget(), LLVMInitializeSPIRVTargetInfo(), LLVMInitializeSPIRVTargetMC(), LLVMInitializeSystemZAsmParser(), LLVMInitializeSystemZAsmPrinter(), LLVMInitializeSystemZTarget(), LLVMInitializeSystemZTargetInfo(), LLVMInitializeVEAsmPrinter(), LLVMInitializeVETarget(), LLVMInitializeVETargetInfo(), LLVMInitializeVETargetMC(), LLVMInitializeWebAssemblyAsmParser(), LLVMInitializeWebAssemblyAsmPrinter(), LLVMInitializeWebAssemblyTarget(), LLVMInitializeWebAssemblyTargetInfo(), LLVMInitializeWebAssemblyTargetMC(), LLVMInitializeX86AsmParser(), LLVMInitializeX86AsmPrinter(), LLVMInitializeX86Target(), LLVMInitializeX86TargetInfo(), LLVMInitializeX86TargetMC(), LLVMInitializeXCoreAsmPrinter(), LLVMInitializeXCoreTarget(), LLVMInitializeXCoreTargetInfo(), LLVMInitializeXCoreTargetMC(), LLVMInitializeXtensaAsmParser(), LLVMInitializeXtensaTargetInfo(), LowerADDSAT_SUBSAT(), llvm::HexagonTargetLowering::LowerAddSubCarry(), lowerAddSubToHorizontalOp(), LowerCTTZ(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), lowerFPToIntToFP(), llvm::AMDGPUTargetLowering::LowerFREM(), llvm::AMDGPUTargetLowering::LowerFROUND(), llvm::LegalizerHelper::lowerFunnelShiftAsShifts(), llvm::LegalizerHelper::lowerFunnelShiftWithInverse(), llvm::LegalizerHelper::lowerIntrinsicRound(), LowerPARITY(), LowerSDIV_v4i8(), llvm::VETargetLowering::lowerToVVP(), llvm::HexagonTargetLowering::LowerUAddSubO(), llvm::AMDGPUTargetLowering::LowerUDIVREM(), llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_FNegNSZ(), llvm::PatternMatch::m_UnOp(), llvm::codeview::CodeViewRecordIO::mapEnum(), llvm::codeview::CodeViewRecordIO::mapVectorN(), llvm::PatternMatch::NotForbidUndef_match< ValTy >::match(), MatchBinaryOp(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), matchFunnelShift(), llvm::CombinerHelper::matchFunnelShiftToRotate(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), matchIntPart(), matchLogicBlend(), llvm::CombinerHelper::matchRedundantBinOpInEquality(), llvm::CombinerHelper::matchRedundantNegOperands(), llvm::CombinerHelper::matchSubAddSameReg(), llvm::CombinerHelper::matchXorOfAndWithSameReg(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), mergeEltWithShuffle(), MinOptional(), moveAddAfterMinMax(), llvm::MulOverflow(), narrowExtractedVectorBinOp(), narrowInsElt(), narrowUDivURem(), narrowVectorSelect(), llvm::neg(), llvm::TrackingMDRef::operator!=(), llvm::DwarfStringPoolEntryRef::operator!=(), llvm::DITypeRefArray::iterator::operator!=(), llvm::TypedTrackingMDRef< MDNode >::operator!=(), llvm::bfi_detail::BlockMass::operator!=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator!=(), llvm::OnDiskChainedHashTable< Info >::iterator::operator!=(), llvm::ScaledNumber< uint64_t >::operator!=(), llvm::DIFile::ChecksumInfo< T >::operator!=(), llvm::TypedMDOperandIterator< T >::operator!=(), llvm::DIExpression::expr_op_iterator::operator!=(), llvm::SSAUpdaterTraits< LDVSSAUpdater >::PHI_iterator::operator!=(), llvm::ScaledNumber< uint64_t >::operator*=(), llvm::bfi_detail::BlockMass::operator+=(), llvm::ScaledNumber< uint64_t >::operator+=(), llvm::bfi_detail::BlockMass::operator-=(), llvm::ScaledNumber< uint64_t >::operator-=(), llvm::ScaledNumber< uint64_t >::operator/=(), llvm::bfi_detail::BlockMass::operator<(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator<(), llvm::ScaledNumber< uint64_t >::operator<(), llvm::bfi_detail::operator<<(), llvm::operator<<(), llvm::bfi_detail::BlockMass::operator<=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator<=(), llvm::ScaledNumber< uint64_t >::operator<=(), llvm::TrackingMDRef::operator=(), llvm::simple_ilist< MachineInstr, Options... >::operator=(), llvm::TypedTrackingMDRef< MDNode >::operator=(), llvm::AllocatorList< Token >::operator=(), llvm::iplist_impl< simple_ilist< llvm::AliasSet, Options... >, ilist_traits< llvm::AliasSet > >::operator=(), llvm::iplist< llvm::PredicateBase >::operator=(), llvm::DIEValue::operator=(), llvm::TrackingMDRef::operator==(), llvm::DwarfStringPoolEntryRef::operator==(), llvm::DITypeRefArray::iterator::operator==(), llvm::TypedTrackingMDRef< MDNode >::operator==(), llvm::bfi_detail::BlockMass::operator==(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator==(), llvm::OnDiskChainedHashTable< Info >::iterator::operator==(), llvm::ConstantAggrKeyType< ConstantClass >::operator==(), llvm::InlineAsmKeyType::operator==(), llvm::ConstantExprKeyType::operator==(), llvm::ScaledNumber< uint64_t >::operator==(), llvm::DIFile::ChecksumInfo< T >::operator==(), llvm::IntrusiveBackList< T >::iterator::operator==(), llvm::IntrusiveBackList< T >::const_iterator::operator==(), llvm::TypedMDOperandIterator< T >::operator==(), llvm::DIExpression::expr_op_iterator::operator==(), llvm::SSAUpdaterTraits< LDVSSAUpdater >::PHI_iterator::operator==(), llvm::bfi_detail::BlockMass::operator>(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator>(), llvm::ScaledNumber< uint64_t >::operator>(), llvm::bfi_detail::BlockMass::operator>=(), llvm::BlockFrequencyInfoImplBase::BlockNode::operator>=(), llvm::ScaledNumber< uint64_t >::operator>=(), operator|=(), OptimizeAndOrXor(), optimizeBranch(), optimizeDivRem(), optimizeTrigReflections(), optimizeWhile(), llvm::IRSimilarity::IRSimilarityCandidate::overlap(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), PerformExtractEltCombine(), performMulCombine(), PerformPREDICATE_CASTCombine(), llvm::AMDGPUTargetLowering::performShlCombine(), PerformSHLSimplify(), performSubAddMULCombine(), PerformSubCSINCCombine(), performUzpCombine(), processAbsIntrinsic(), llvm::FoldingSetTrait< SDVTListNode >::Profile(), llvm::FoldingSetTrait< SCEV >::Profile(), llvm::DefaultFoldingSetTrait< SCEVPredicate >::Profile(), llvm::FoldingSetTrait< SCEVPredicate >::Profile(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Profile(), llvm::FoldingSetTrait< T * >::Profile(), llvm::FoldingSetTrait< T, std::enable_if_t< std::is_enum< T >::value > >::Profile(), llvm::ImutProfileInfo< T >::Profile(), llvm::ImutProfileInteger< T >::Profile(), llvm::ImutProfileInfo< bool >::Profile(), llvm::ImutProfileInfo< T * >::Profile(), pushAddIntoCmovOfConsts(), reassociateFCmps(), reassociateForUses(), reassociateMinMaxWithConstantInOperand(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), ReconstructTruncateFromBuildVector(), llvm::SetVector< llvm::MCSection *, SmallVector< llvm::MCSection *, N >, SmallDenseSet< llvm::MCSection *, N > >::remove(), ReplaceAddWithADDP(), rotl64(), llvm::LPPassManager::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::FPPassManager::runOnFunction(), llvm::SaturatingAdd(), llvm::SaturatingMultiply(), llvm::SaturatingMultiplyAdd(), scalarizeBinOpOfSplats(), llvm::scalbn(), llvm::detail::scalbn(), llvm::cl::ExpansionContext::setCurrentDir(), llvm::cl::ExpansionContext::setMarkEOLs(), llvm::cl::ExpansionContext::setRelativeNames(), llvm::cl::ExpansionContext::setSearchDirs(), llvm::cl::ExpansionContext::setVFS(), llvm::TargetLoweringBase::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::AArch64TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::X86TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), llvm::TargetLowering::ShrinkDemandedOp(), llvm::SignExtend32(), llvm::SignExtend64(), llvm::simple_ilist< MachineInstr, Options... >::simple_ilist(), llvm::InstCombinerImpl::SimplifyAddWithRemainder(), simplifyAndInst(), simplifyAndOfICmps(), simplifyAndOrOfICmpsWithCtpop(), simplifyAndOrOfICmpsWithLimitConst(), simplifyAndOrOfICmpsWithZero(), simplifyAShrInst(), simplifyBinaryIntrinsic(), llvm::InstCombinerImpl::simplifyBinOpSplats(), simplifyCmpSelOfMaxMin(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyDivRem(), simplifyFAddInst(), simplifyFDivInst(), simplifyFMAFMul(), simplifyFNegInst(), llvm::SelectionDAG::simplifyFPBinop(), simplifyFSubInst(), simplifyICmpOfBools(), simplifyICmpWithConstant(), simplifyIntrinsic(), simplifyLogicOfAddSub(), simplifyLShrInst(), simplifyMulInst(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), simplifyOrInst(), simplifyOrLogic(), simplifyOrOfICmps(), simplifySelectBitTest(), simplifySelectInst(), simplifySelectWithFakeICmpEq(), simplifySelectWithICmpCond(), llvm::SelectionDAG::simplifyShift(), simplifyShift(), simplifyShlInst(), simplifySRemInst(), simplifySubInst(), simplifyUnaryIntrinsic(), simplifyUnsignedRangeCheck(), simplifyXorInst(), sinkNotIntoXor(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), strongerOrdering(), llvm::ConstantRange::sub(), llvm::SubOverflow(), llvm::simple_ilist< MachineInstr, Options... >::swap(), takeLog2(), toHexStr(), toOctal(), llvm::TrackingMDRef::TrackingMDRef(), translateExtract(), TruncIfPossible(), TryDistrubutionADDVecReduce(), tryLowerToSLI(), trySimplifyICmpWithAdds(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitBranchInst(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFNeg(), llvm::InstCombinerImpl::visitFPTrunc(), llvm::InstCombinerImpl::visitFRem(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitLShr(), visitMaskedMerge(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSDiv(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitURem(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), and wrap().