LLVM: lib/CodeGen/ExpandLargeDivRem.cpp File Reference
ExpandLargeDivRem.cpp File Reference
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/PassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Utils/IntegerDivision.h"
Functions
static bool isConstantPowerOfTwo (llvm::Value *V, bool SignedOp)
static bool isSigned (unsigned int Opcode)
static bool runImpl (Function &F, const TargetLowering &TLI)
INITIALIZE_PASS_BEGIN (ExpandLargeDivRemLegacyPass, "expand-large-div-rem", "Expand large div/rem", false, false) INITIALIZE_PASS_END(ExpandLargeDivRemLegacyPass
Variables
static cl::opt< unsigned > ExpandDivRemBits ("expand-div-rem-bits", cl::Hidden, cl::init(llvm::IntegerType::MAX_INT_BITS), cl::desc("div and rem instructions on integers with " "more than <N> bits are expanded."))
expand large div rem
expand large div Expand large div false
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ExpandLargeDivRemLegacyPass , "expand-large-div-rem" , "Expand large div/rem" , false , false)
isConstantPowerOfTwo()
static bool isConstantPowerOfTwo (llvm::Value * V, bool SignedOp) static
Definition at line 41 of file ExpandLargeDivRem.cpp.
References llvm::APInt::isNegative(), and llvm::APInt::isPowerOf2().
Referenced by runImpl().
isSigned()
static bool isSigned (unsigned int Opcode) static
Definition at line 52 of file ExpandLargeDivRem.cpp.
Referenced by llvm::APInt::APInt(), llvm::detail::IEEEFloat::convertFromAPInt(), llvm::detail::IEEEFloat::convertFromSignExtendedInteger(), llvm::detail::IEEEFloat::convertFromZeroExtendedInteger(), llvm::detail::IEEEFloat::convertToInteger(), llvm::InstSimplifyFolder::CreateIntCast(), llvm::NoFolder::CreateIntCast(), llvm::ConstantFolder::CreateIntCast(), llvm::TargetFolder::CreateIntCast(), llvm::IRBuilderBase::CreateIntCast(), llvm::CastInst::CreateIntegerCast(), DecodeBFLabelOperand(), evaluateICmpRelation(), llvm::InstCombinerImpl::EvaluateInDifferentType(), llvm::ConstantInt::get(), llvm::ScalarEvolution::getConstant(), getDivRemArgList(), getDivRemLibcall(), llvm::APSInt::getExtValue(), llvm::ConstantExpr::getIntegerCast(), llvm::HexagonInstrInfo::getMaxValue(), llvm::HexagonInstrInfo::getMinValue(), llvm::BinaryOpIntrinsic::getNoWrapKind(), llvm::InstCombinerImpl::insertRangeTest(), isExtendedBUILD_VECTOR(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), llvm::APSInt::isNegative(), llvm::APSInt::isRepresentableByInt64(), LLVMConstIntCast(), LowerUMULO_SMULO(), llvm::TargetTransformInfoImplBase::minRequiredElementSize(), PerformVCVTCombine(), PerformVDIVCombine(), llvm::APInt::print(), llvm::APInt::roundToDouble(), runImpl(), llvm::APFloatBase::semanticsIntSizeInBits(), and llvm::APSInt::toString().
runImpl()
static bool runImpl (Function & F, const TargetLowering & TLI) static
Definition at line 56 of file ExpandLargeDivRem.cpp.
References llvm::expandDivision(), ExpandDivRemBits, llvm::expandRemainder(), F, llvm::TargetLoweringBase::getMaxDivRemBitWidthSupported(), I, llvm::instructions(), isConstantPowerOfTwo(), isSigned(), llvm::IntegerType::MAX_INT_BITS, Modified, and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by llvm::MergeICmpsPass::run(), llvm::LowerInvokePass::run(), llvm::ObjCARCAPElimPass::run(), llvm::ObjCARCExpandPass::run(), llvm::SLPVectorizerPass::run(), llvm::NaryReassociatePass::run(), llvm::TLSVariableHoistPass::run(), llvm::JumpThreadingPass::run(), llvm::ConstantHoistingPass::run(), llvm::GVNPass::run(), llvm::RewriteSymbolPass::run(), llvm::LoopVersioningPass::run(), and llvm::SROAPass::run().
Variable Documentation
ExpandDivRemBits
cl::opt<unsigned> ExpandDivRemBits("expand-div-rem-bits", cl::Hidden, cl::init(llvm::IntegerType::MAX_INT_BITS), cl::desc("div and rem instructions on integers with " "more than <N> bits are expanded.")) static
Referenced by runImpl().
false
expand large div Expand large div false
Definition at line 135 of file ExpandLargeDivRem.cpp.
rem
expand large div Expand large div rem
Definition at line 134 of file ExpandLargeDivRem.cpp.
Referenced by llvm::SchedBoundary::init().