LLVM: lib/Target/AMDGPU/GCNHazardRecognizer.cpp File Reference
GCNHazardRecognizer.cpp File Reference
#include "GCNHazardRecognizer.h"
#include "GCNSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/TargetParser/TargetParser.h"
Typedefs
typedef function_ref< bool(const MachineInstr &, int WaitStates)> IsExpiredFn
typedef function_ref< unsigned int(const MachineInstr &)> GetNumWaitStatesFn
Enumerations
enum HazardFnResult { HazardFound, HazardExpired, NoHazardFound }
Functions
static bool shouldRunLdsBranchVmemWARHazardFixup (const MachineFunction &MF, const GCNSubtarget &ST)
static bool isDivFMas (unsigned Opcode)
static bool isSGetReg (unsigned Opcode)
static bool isSSetReg (unsigned Opcode)
static bool isRWLane (unsigned Opcode)
static bool isRFE (unsigned Opcode)
static bool isSMovRel (unsigned Opcode)
static bool isDGEMM (unsigned Opcode)
static bool isXDL (const GCNSubtarget &ST, const MachineInstr &MI)
static bool isSendMsgTraceDataOrGDS (const SIInstrInfo &TII, const MachineInstr &MI)
static bool isPermlane (const MachineInstr &MI)
static bool isLdsDma (const MachineInstr &MI)
static unsigned getHWReg (const SIInstrInfo *TII, const MachineInstr &RegInstr)
static void insertNoopsInBundle (MachineInstr *MI, const SIInstrInfo &TII, unsigned Quantity)
template<typename StateT >
static bool hasHazard (StateT State, function_ref< HazardFnResult(StateT &, const MachineInstr &)> IsHazard, function_ref< void(StateT &, const MachineInstr &)> UpdateState, const MachineBasicBlock *MBB, MachineBasicBlock::const_reverse_instr_iterator I, DenseSet< const MachineBasicBlock * > &Visited)
static int getWaitStatesSince (GCNHazardRecognizer::IsHazardFn IsHazard, const MachineBasicBlock *MBB, MachineBasicBlock::const_reverse_instr_iterator I, int WaitStates, IsExpiredFn IsExpired, DenseSet< const MachineBasicBlock * > &Visited, GetNumWaitStatesFn GetNumWaitStates=SIInstrInfo::getNumWaitStates)
static int getWaitStatesSince (GCNHazardRecognizer::IsHazardFn IsHazard, const MachineInstr *MI, IsExpiredFn IsExpired)
static void addRegUnits (const SIRegisterInfo &TRI, BitVector &BV, MCRegister Reg)
static void addRegsToSet (const SIRegisterInfo &TRI, iterator_range< MachineInstr::const_mop_iterator > Ops, BitVector &Set)
static bool breaksSMEMSoftClause (MachineInstr *MI)
static bool breaksVMEMSoftClause (MachineInstr *MI)
static bool isStoreCountWaitZero (const MachineInstr &I)
Variables
static cl::opt< unsigned, false, MFMAPaddingRatioParser > MFMAPaddingRatio ("amdgpu-mfma-padding-ratio", cl::init(0), cl::Hidden, cl::desc("Fill a percentage of the latency between " "neighboring MFMA with s_nops."))
Typedef Documentation
GetNumWaitStatesFn
typedef function_ref<unsigned int(const MachineInstr &)> GetNumWaitStatesFn
Definition at line 448 of file GCNHazardRecognizer.cpp.
IsExpiredFn
typedef function_ref<bool(const MachineInstr &, int WaitStates)> IsExpiredFn
Definition at line 447 of file GCNHazardRecognizer.cpp.
Enumeration Type Documentation
HazardFnResult
enum HazardFnResult
Enumerator
HazardFound
HazardExpired
NoHazardFound
Definition at line 445 of file GCNHazardRecognizer.cpp.
Function Documentation
addRegsToSet()
static void addRegsToSet (const SIRegisterInfo & TRI, iterator_range< MachineInstr::const_mop_iterator > Ops, BitVector & Set) static
Definition at line 595 of file GCNHazardRecognizer.cpp.
References addRegUnits(), and TRI.
addRegUnits()
static void addRegUnits (const SIRegisterInfo & TRI, BitVector & BV, MCRegister Reg) static
Definition at line 589 of file GCNHazardRecognizer.cpp.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::BitVector::set(), and TRI.
Referenced by addRegsToSet().
breaksSMEMSoftClause()
static bool breaksSMEMSoftClause (MachineInstr * MI) static
Definition at line 610 of file GCNHazardRecognizer.cpp.
References llvm::SIInstrInfo::isSMRD(), and MI.
breaksVMEMSoftClause()
static bool breaksVMEMSoftClause (MachineInstr * MI) static
Definition at line 614 of file GCNHazardRecognizer.cpp.
References llvm::SIInstrInfo::isFLAT(), llvm::SIInstrInfo::isVMEM(), and MI.
getHWReg()
static unsigned getHWReg (const SIInstrInfo * TII, const MachineInstr & RegInstr) static
Definition at line 174 of file GCNHazardRecognizer.cpp.
References llvm::MachineOperand::getImm(), llvm::AMDGPU::Hwreg::ID_MASK_, and TII.
getWaitStatesSince() [1/2]
static int getWaitStatesSince (GCNHazardRecognizer::IsHazardFn IsHazard, const MachineBasicBlock * MBB, MachineBasicBlock::const_reverse_instr_iterator I, int WaitStates, IsExpiredFn IsExpired, DenseSet< const MachineBasicBlock * > & Visited, GetNumWaitStatesFn GetNumWaitStates = SIInstrInfo::getNumWaitStates) static
Definition at line 495 of file GCNHazardRecognizer.cpp.
References E, I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::MachineBasicBlock::instr_rend(), llvm::max(), MBB, llvm::min(), llvm::MachineBasicBlock::predecessors(), and llvm::RISCVFenceField::W.
Referenced by getWaitStatesSince().
getWaitStatesSince() [2/2]
static int getWaitStatesSince (GCNHazardRecognizer::IsHazardFn IsHazard, const MachineInstr * MI, IsExpiredFn IsExpired) static
Definition at line 531 of file GCNHazardRecognizer.cpp.
References getWaitStatesSince(), and MI.
hasHazard()
template<typename StateT > static bool hasHazard (StateT State, function_ref< HazardFnResult(StateT &, const MachineInstr &)> IsHazard, function_ref< void(StateT &, const MachineInstr &)> UpdateState, const MachineBasicBlock * MBB, MachineBasicBlock::const_reverse_instr_iterator I, DenseSet< const MachineBasicBlock * > & Visited) static
Definition at line 453 of file GCNHazardRecognizer.cpp.
References E, HazardExpired, HazardFound, I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::MachineBasicBlock::instr_rend(), MBB, and llvm::MachineBasicBlock::predecessors().
insertNoopsInBundle()
static void insertNoopsInBundle (MachineInstr * MI, const SIInstrInfo & TII, unsigned Quantity) static
Definition at line 259 of file GCNHazardRecognizer.cpp.
References llvm::MachineInstrBuilder::addImm(), Arg, llvm::BuildMI(), MI, llvm::min(), and TII.
isDGEMM()
static bool isDGEMM (unsigned Opcode) static
Definition at line 118 of file GCNHazardRecognizer.cpp.
References llvm::AMDGPU::getMAIIsDGEMM().
Referenced by isXDL().
isDivFMas()
static bool isDivFMas (unsigned Opcode) static
Definition at line 79 of file GCNHazardRecognizer.cpp.
Referenced by llvm::GCNHazardRecognizer::getHazardType(), and llvm::GCNHazardRecognizer::PreEmitNoopsCommon().
isLdsDma()
static bool isLdsDma (const MachineInstr & MI) static
Definition at line 169 of file GCNHazardRecognizer.cpp.
References llvm::SIInstrInfo::isFLAT(), llvm::SIInstrInfo::isMUBUF(), llvm::SIInstrInfo::isVALU(), and MI.
Referenced by llvm::GCNHazardRecognizer::getHazardType(), and llvm::GCNHazardRecognizer::PreEmitNoopsCommon().
isPermlane()
static bool isPermlane (const MachineInstr & MI) static
Definition at line 163 of file GCNHazardRecognizer.cpp.
References MI.
isRFE()
static bool isRFE (unsigned Opcode) static
Definition at line 102 of file GCNHazardRecognizer.cpp.
Referenced by llvm::GCNHazardRecognizer::getHazardType(), and llvm::GCNHazardRecognizer::PreEmitNoopsCommon().
isRWLane()
static bool isRWLane (unsigned Opcode) static
Definition at line 98 of file GCNHazardRecognizer.cpp.
Referenced by llvm::GCNHazardRecognizer::getHazardType(), and llvm::GCNHazardRecognizer::PreEmitNoopsCommon().
isSendMsgTraceDataOrGDS()
static bool isSendMsgTraceDataOrGDS (const SIInstrInfo & TII, const MachineInstr & MI) static
Definition at line 137 of file GCNHazardRecognizer.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), MI, and TII.
Referenced by llvm::GCNHazardRecognizer::getHazardType(), and llvm::GCNHazardRecognizer::PreEmitNoopsCommon().
isSGetReg()
static bool isSGetReg (unsigned Opcode) static
Definition at line 83 of file GCNHazardRecognizer.cpp.
Referenced by llvm::GCNHazardRecognizer::getHazardType(), and llvm::GCNHazardRecognizer::PreEmitNoopsCommon().
isSMovRel()
static bool isSMovRel (unsigned Opcode) static
Definition at line 106 of file GCNHazardRecognizer.cpp.
Referenced by llvm::GCNHazardRecognizer::getHazardType(), and llvm::GCNHazardRecognizer::PreEmitNoopsCommon().
isSSetReg()
static bool isSSetReg (unsigned Opcode) static
Definition at line 87 of file GCNHazardRecognizer.cpp.
Referenced by llvm::GCNHazardRecognizer::getHazardType(), and llvm::GCNHazardRecognizer::PreEmitNoopsCommon().
isStoreCountWaitZero()
static bool isStoreCountWaitZero (const MachineInstr & I) static
Definition at line 1334 of file GCNHazardRecognizer.cpp.
References I.
isXDL()
static bool isXDL (const GCNSubtarget & ST, const MachineInstr & MI) static
Definition at line 122 of file GCNHazardRecognizer.cpp.
References llvm::AMDGPU::getMAIIsGFX940XDL(), isDGEMM(), llvm::SIInstrInfo::isMAI(), MI, and llvm::ARM_MB::ST.
shouldRunLdsBranchVmemWARHazardFixup()
static bool shouldRunLdsBranchVmemWARHazardFixup (const MachineFunction & MF, const GCNSubtarget & ST) static
Definition at line 1313 of file GCNHazardRecognizer.cpp.
References llvm::SIInstrInfo::isDS(), llvm::SIInstrInfo::isSegmentSpecificFLAT(), llvm::SIInstrInfo::isVMEM(), MBB, MI, and llvm::ARM_MB::ST.
Referenced by llvm::GCNHazardRecognizer::GCNHazardRecognizer().
Variable Documentation
MFMAPaddingRatio
cl::opt<unsigned, false, MFMAPaddingRatioParser> MFMAPaddingRatio("amdgpu-mfma-padding-ratio", cl::init(0), cl::Hidden, cl::desc("Fill a percentage of the latency between " "neighboring MFMA with s_nops.")) static