LLVM: lib/Target/AMDGPU/GCNSchedStrategy.cpp File Reference
GCNSchedStrategy.cpp File Reference
#include "GCNSchedStrategy.h"
#include "AMDGPUIGroupLP.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
Classes
struct EarlierIssuingCycle
Macros
#define DEBUG_TYPE "machine-scheduler"
Generally, the reason for having multiple scheduling stages is to account for the kernel-wide effect of register usage on occupancy.
Functions
static void printScheduleModel (std::set< std::pair< MachineInstr *, unsigned >, EarlierIssuingCycle > &ReadyCycles)
static bool hasIGLPInstrs (ScheduleDAGInstrs *DAG)
Variables
static cl::opt< bool > DisableUnclusterHighRP ("amdgpu-disable-unclustred-high-rp-reschedule", cl::Hidden, cl::desc("Disable unclustred high register pressure " "reduction scheduling stage."), cl::init(false))
static cl::opt< unsigned > ScheduleMetricBias ("amdgpu-schedule-metric-bias", cl::Hidden, cl::desc("Sets the bias which adds weight to occupancy vs latency. Set it to " "100 to chase the occupancy only."), cl::init(10))
Detailed Description
This contains a MachineSchedStrategy implementation for maximizing wave occupancy on GCN hardware.
This pass will apply multiple scheduling stages to the same function. Regions are first recorded in GCNScheduleDAGMILive::schedule. The actual entry point for the scheduling of those regions is GCNScheduleDAGMILive::runSchedStages.
Definition in file GCNSchedStrategy.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Generally, the reason for having multiple scheduling stages is to account for the kernel-wide effect of register usage on occupancy.
Usually, only a few scheduling regions will have register pressure high enough to limit occupancy for the kernel, so constraints can be relaxed to improve ILP in other regions.
Definition at line 31 of file GCNSchedStrategy.cpp.
Function Documentation
hasIGLPInstrs()
static bool hasIGLPInstrs (ScheduleDAGInstrs * DAG) static
Definition at line 1519 of file GCNSchedStrategy.cpp.
References llvm::any_of(), llvm::ScheduleDAGInstrs::begin(), llvm::ScheduleDAGInstrs::end(), and MI.
Referenced by llvm::GCNPostScheduleDAGMILive::schedule().
printScheduleModel()
static void printScheduleModel (std::set< std::pair< MachineInstr *, unsigned >, EarlierIssuingCycle > & ReadyCycles) static
Definition at line 984 of file GCNSchedStrategy.cpp.
References llvm::dbgs(), and I.
Referenced by llvm::GCNSchedStage::getScheduleMetrics().
Variable Documentation
DisableUnclusterHighRP
cl::opt<bool> DisableUnclusterHighRP("amdgpu-disable-unclustred-high-rp-reschedule", cl::Hidden, cl::desc("Disable unclustred high register pressure " "reduction scheduling stage."), cl::init(false)) static
Referenced by llvm::UnclusteredHighRPStage::initGCNSchedStage().
ScheduleMetricBias
cl::opt<unsigned> ScheduleMetricBias("amdgpu-schedule-metric-bias", cl::Hidden, cl::desc("Sets the bias which adds weight to occupancy vs latency. Set it to " "100 to chase the occupancy only."), cl::init(10)) static
Referenced by llvm::UnclusteredHighRPStage::shouldRevertScheduling().