LLVM: lib/CodeGen/GlobalISel/GISelKnownBits.cpp File Reference
GISelKnownBits.cpp File Reference
#include "llvm/CodeGen/GlobalISel/GISelKnownBits.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/IR/Module.h"
Macros
#define DEBUG_TYPE "gisel-known-bits"
Provides analysis for querying information about KnownBits during GISel passes.
Functions
INITIALIZE_PASS (GISelKnownBitsAnalysis, DEBUG_TYPE, "Analysis for ComputingKnownBits", false, true) GISelKnownBits
static LLVM_ATTRIBUTE_UNUSED void dumpResult (const MachineInstr &MI, const KnownBits &Known, unsigned Depth)
static KnownBits extractBits (unsigned BitWidth, const KnownBits &SrcOpKnown, const KnownBits &OffsetKnown, const KnownBits &WidthKnown)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "gisel-known-bits"
Provides analysis for querying information about KnownBits during GISel passes.
Definition at line 22 of file GISelKnownBits.cpp.
Function Documentation
dumpResult()
static LLVM_ATTRIBUTE_UNUSED void dumpResult (const MachineInstr & MI, const KnownBits & Known, unsigned Depth) static
Definition at line 92 of file GISelKnownBits.cpp.
References llvm::dbgs(), llvm::Depth, MI, llvm::KnownBits::One, llvm::toString(), and llvm::KnownBits::Zero.
Referenced by llvm::GISelKnownBits::computeKnownBitsImpl().
extractBits()
static KnownBits extractBits (unsigned BitWidth, const KnownBits & SrcOpKnown, const KnownBits & OffsetKnown, const KnownBits & WidthKnown) static
Definition at line 124 of file GISelKnownBits.cpp.
References llvm::BitWidth, llvm::APInt::getBitsSetFrom(), llvm::APInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::KnownBits::getMaxValue(), llvm::KnownBits::getMinValue(), llvm::KnownBits::lshr(), and llvm::BitmaskEnumDetail::Mask().
Referenced by combineX86ShufflesRecursively(), and llvm::GISelKnownBits::computeKnownBitsImpl().
INITIALIZE_PASS()
INITIALIZE_PASS (GISelKnownBitsAnalysis , DEBUG_TYPE , "Analysis for ComputingKnownBits" , false , true)
Definition at line 28 of file GISelKnownBits.cpp.