LLVM: Dwarf constants parsing functions
Dwarf constants parsing functions
These functions map their strings back to the corresponding enumeration value or return 0 if there is none, except for these exceptions:
Functions
unsigned llvm::dwarf::getTag (StringRef TagString)
unsigned llvm::dwarf::getOperationEncoding (StringRef OperationEncodingString)
unsigned llvm::dwarf::getVirtuality (StringRef VirtualityString)
unsigned llvm::dwarf::getLanguage (StringRef LanguageString)
unsigned llvm::dwarf::getCallingConvention (StringRef LanguageString)
unsigned llvm::dwarf::getAttributeEncoding (StringRef EncodingString)
unsigned llvm::dwarf::getMacinfo (StringRef MacinfoString)
unsigned llvm::dwarf::getMacro (StringRef MacroString)
Detailed Description
These functions map their strings back to the corresponding enumeration value or return 0 if there is none, except for these exceptions:
getTag() returns DW_TAG_invalid on invalid input.
getVirtuality() returns DW_VIRTUALITY_invalid on invalid input.
getMacinfo() returns DW_MACINFO_invalid on invalid input.
Function Documentation
getAttributeEncoding()
unsigned llvm::dwarf::getAttributeEncoding (StringRef EncodingString)
Definition at line 208 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default().
Referenced by llvm::LLParser::parseMDField().
getCallingConvention()
unsigned llvm::dwarf::getCallingConvention (StringRef LanguageString)
Definition at line 405 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default().
Referenced by llvm::LLParser::parseMDField().
getLanguage()
unsigned llvm::dwarf::getLanguage (StringRef LanguageString)
Definition at line 338 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default(), and llvm::dwarf::LanguageString().
Referenced by llvm::LLParser::parseMDField().
getMacinfo()
unsigned llvm::dwarf::getMacinfo (StringRef MacinfoString)
Definition at line 477 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::dwarf::DW_MACINFO_define, llvm::dwarf::DW_MACINFO_end_file, llvm::dwarf::DW_MACINFO_invalid, llvm::dwarf::DW_MACINFO_start_file, llvm::dwarf::DW_MACINFO_undef, llvm::dwarf::DW_MACINFO_vendor_ext, and llvm::dwarf::MacinfoString().
Referenced by llvm::LLParser::parseMDField().
getMacro()
unsigned llvm::dwarf::getMacro (StringRef MacroString)
Definition at line 509 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default(), llvm::dwarf::DW_MACINFO_invalid, and llvm::dwarf::MacroString().
getOperationEncoding()
unsigned llvm::dwarf::getOperationEncoding (StringRef OperationEncodingString)
Definition at line 161 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::dwarf::DW_OP_LLVM_arg, llvm::dwarf::DW_OP_LLVM_convert, llvm::dwarf::DW_OP_LLVM_entry_value, llvm::dwarf::DW_OP_LLVM_fragment, llvm::dwarf::DW_OP_LLVM_implicit_pointer, llvm::dwarf::DW_OP_LLVM_tag_offset, and llvm::dwarf::OperationEncodingString().
getTag()
unsigned llvm::dwarf::getTag (StringRef TagString)
Definition at line 32 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default(), llvm::dwarf::DW_TAG_invalid, and llvm::dwarf::TagString().
Referenced by llvm::DWARFDie::dump(), llvm::DWARFAbbreviationDeclaration::dump(), llvm::DWARFDie::getFullName(), llvm::DWARFDie::getTypeSize(), llvm::DWARFDie::isSubprogramDIE(), llvm::DWARFDie::isSubroutineDIE(), and llvm::LLParser::parseMDField().
getVirtuality()
unsigned llvm::dwarf::getVirtuality (StringRef VirtualityString)
Definition at line 319 of file Dwarf.cpp.
References llvm::StringSwitch< T, R >::Default(), llvm::dwarf::DW_VIRTUALITY_invalid, and llvm::dwarf::VirtualityString().
Referenced by llvm::LLParser::parseMDField().