LLVM: query interface.
query interface.
Retrieve the Function with VFShape Shape.
Functions
Function * llvm::VFDatabase::getVectorizedFunction (const VFShape &Shape) const
Detailed Description
Retrieve the Function with VFShape Shape.
Function Documentation
getVectorizedFunction()
Function* llvm::VFDatabase::getVectorizedFunction (const VFShape & Shape) const inline
Definition at line 284 of file VectorUtils.h.
References llvm::CallBase::getCalledFunction(), llvm::VFShape::getScalarShape(), Info, and M.
Referenced by llvm::LoopVectorizationCostModel::getVectorCallCost(), and getVectorCallCosts().