LLVM: Comdats
Comdats
LLVM-C: C interface to LLVM » Core
Enumerations
enum LLVMComdatSelectionKind {
LLVMAnyComdatSelectionKind, LLVMExactMatchComdatSelectionKind, LLVMLargestComdatSelectionKind, LLVMNoDeduplicateComdatSelectionKind,
LLVMSameSizeComdatSelectionKind
}
Functions
LLVMComdatRef LLVMGetOrInsertComdat (LLVMModuleRef M, const char *Name)
Return the Comdat in the module with the specified name.
LLVMComdatRef LLVMGetComdat (LLVMValueRef V)
Get the Comdat assigned to the given global object.
void LLVMSetComdat (LLVMValueRef V, LLVMComdatRef C)
Assign the Comdat to the given global object.
LLVMComdatSelectionKind LLVMGetComdatSelectionKind (LLVMComdatRef C)
void LLVMSetComdatSelectionKind (LLVMComdatRef C, LLVMComdatSelectionKind Kind)
Detailed Description
Enumeration Type Documentation
LLVMComdatSelectionKind
enum LLVMComdatSelectionKind
Enumerator
LLVMAnyComdatSelectionKind
The linker may choose any COMDAT.
LLVMExactMatchComdatSelectionKind
The data referenced by the COMDAT must be the same.
LLVMLargestComdatSelectionKind
The linker will choose the largest COMDAT.
LLVMNoDeduplicateComdatSelectionKind
No deduplication is performed.
LLVMSameSizeComdatSelectionKind
The data referenced by the COMDAT must be the same size.
Definition at line 29 of file Comdat.h.
Function Documentation
LLVMGetComdat()
LLVMComdatRef LLVMGetComdat (LLVMValueRef V)
Get the Comdat assigned to the given global object.
See also
llvm::GlobalObject::getComdat()
Definition at line 38 of file Comdat.cpp.
References G, and llvm::wrap().
LLVMGetComdatSelectionKind()
LLVMComdatSelectionKind LLVMGetComdatSelectionKind (LLVMComdatRef C)
Definition at line 48 of file Comdat.cpp.
References llvm::Comdat::Any, llvm::Comdat::ExactMatch, llvm::Comdat::Largest, llvm_unreachable, LLVMAnyComdatSelectionKind, LLVMExactMatchComdatSelectionKind, LLVMLargestComdatSelectionKind, LLVMNoDeduplicateComdatSelectionKind, LLVMSameSizeComdatSelectionKind, llvm::Comdat::NoDeduplicate, llvm::Comdat::SameSize, and llvm::unwrap().
LLVMGetOrInsertComdat()
LLVMComdatRef LLVMGetOrInsertComdat (LLVMModuleRef M, const char * Name)
Return the Comdat in the module with the specified name.
It is created if it didn't already exist.
See also
llvm::Module::getOrInsertComdat()
Definition at line 34 of file Comdat.cpp.
References M, llvm::unwrap(), and llvm::wrap().
LLVMSetComdat()
void LLVMSetComdat (LLVMValueRef V, LLVMComdatRef C)
Assign the Comdat to the given global object.
See also
llvm::GlobalObject::setComdat()
Definition at line 43 of file Comdat.cpp.
References G, and llvm::unwrap().
LLVMSetComdatSelectionKind()
void LLVMSetComdatSelectionKind (LLVMComdatRef C, LLVMComdatSelectionKind Kind)
Definition at line 64 of file Comdat.cpp.
References llvm::Comdat::Any, llvm::Comdat::ExactMatch, llvm::Comdat::Largest, LLVMAnyComdatSelectionKind, LLVMExactMatchComdatSelectionKind, LLVMLargestComdatSelectionKind, LLVMNoDeduplicateComdatSelectionKind, LLVMSameSizeComdatSelectionKind, llvm::Comdat::NoDeduplicate, llvm::Comdat::SameSize, llvm::Comdat::setSelectionKind(), and llvm::unwrap().