LLVM: Predicates to tune DWARF for a given debugger.
Predicates to tune DWARF for a given debugger.
Returns whether we are "tuning" for a given debugger.
Functions
bool llvm::DwarfDebug::tuneForGDB () const
bool llvm::DwarfDebug::tuneForLLDB () const
bool llvm::DwarfDebug::tuneForSCE () const
bool llvm::DwarfDebug::tuneForDBX () const
Detailed Description
Returns whether we are "tuning" for a given debugger.
Function Documentation
tuneForDBX()
bool llvm::DwarfDebug::tuneForDBX () const inline
Definition at line 832 of file DwarfDebug.h.
References llvm::DBX.
Referenced by llvm::DwarfDebug::DwarfDebug().
tuneForGDB()
bool llvm::DwarfDebug::tuneForGDB () const inline
Definition at line 829 of file DwarfDebug.h.
References llvm::GDB.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfDebug::DwarfDebug(), and llvm::DwarfCompileUnit::hasDwarfPubSections().
tuneForLLDB()
bool llvm::DwarfDebug::tuneForLLDB () const inline
Definition at line 830 of file DwarfDebug.h.
References llvm::LLDB.
Referenced by llvm::DwarfDebug::DwarfDebug(), and llvm::DwarfCompileUnit::useGNUAnalogForDwarf5Feature().
tuneForSCE()
bool llvm::DwarfDebug::tuneForSCE () const inline
Definition at line 831 of file DwarfDebug.h.
References llvm::SCE.
Referenced by llvm::DwarfDebug::DwarfDebug().