LLVM: Debug Information
Debug Information
LLVM-C: C interface to LLVM » Core
This file declares the C API endpoints for generating DWARF Debug Info.
Typedefs
typedef unsigned LLVMMetadataKind
typedef unsigned LLVMDWARFTypeEncoding
An LLVM DWARF type encoding.
Enumerations
enum LLVMDIFlags {
LLVMDIFlagZero = 0, LLVMDIFlagPrivate = 1, LLVMDIFlagProtected = 2, LLVMDIFlagPublic = 3,
LLVMDIFlagFwdDecl = 1 << 2, LLVMDIFlagAppleBlock = 1 << 3, LLVMDIFlagReservedBit4 = 1 << 4, LLVMDIFlagVirtual = 1 << 5,
LLVMDIFlagArtificial = 1 << 6, LLVMDIFlagExplicit = 1 << 7, LLVMDIFlagPrototyped = 1 << 8, LLVMDIFlagObjcClassComplete = 1 << 9,
LLVMDIFlagObjectPointer = 1 << 10, LLVMDIFlagVector = 1 << 11, LLVMDIFlagStaticMember = 1 << 12, LLVMDIFlagLValueReference = 1 << 13,
LLVMDIFlagRValueReference = 1 << 14, LLVMDIFlagReserved = 1 << 15, LLVMDIFlagSingleInheritance = 1 << 16, LLVMDIFlagMultipleInheritance = 2 << 16,
LLVMDIFlagVirtualInheritance = 3 << 16, LLVMDIFlagIntroducedVirtual = 1 << 18, LLVMDIFlagBitField = 1 << 19, LLVMDIFlagNoReturn = 1 << 20,
LLVMDIFlagTypePassByValue = 1 << 22, LLVMDIFlagTypePassByReference = 1 << 23, LLVMDIFlagEnumClass = 1 << 24, LLVMDIFlagFixedEnum = LLVMDIFlagEnumClass,
LLVMDIFlagThunk = 1 << 25, LLVMDIFlagNonTrivial = 1 << 26, LLVMDIFlagBigEndian = 1 << 27, LLVMDIFlagLittleEndian = 1 << 28,
LLVMDIFlagIndirectVirtualBase = (1 << 2) | (1 << 5), LLVMDIFlagAccessibility, LLVMDIFlagPtrToMemberRep
}
Debug info flags.
enum LLVMDWARFSourceLanguage {
LLVMDWARFSourceLanguageC89, LLVMDWARFSourceLanguageC, LLVMDWARFSourceLanguageAda83, LLVMDWARFSourceLanguageC_plus_plus,
LLVMDWARFSourceLanguageCobol74, LLVMDWARFSourceLanguageCobol85, LLVMDWARFSourceLanguageFortran77, LLVMDWARFSourceLanguageFortran90,
LLVMDWARFSourceLanguagePascal83, LLVMDWARFSourceLanguageModula2, LLVMDWARFSourceLanguageJava, LLVMDWARFSourceLanguageC99,
LLVMDWARFSourceLanguageAda95, LLVMDWARFSourceLanguageFortran95, LLVMDWARFSourceLanguagePLI, LLVMDWARFSourceLanguageObjC,
LLVMDWARFSourceLanguageObjC_plus_plus, LLVMDWARFSourceLanguageUPC, LLVMDWARFSourceLanguageD, LLVMDWARFSourceLanguagePython,
LLVMDWARFSourceLanguageOpenCL, LLVMDWARFSourceLanguageGo, LLVMDWARFSourceLanguageModula3, LLVMDWARFSourceLanguageHaskell,
LLVMDWARFSourceLanguageC_plus_plus_03, LLVMDWARFSourceLanguageC_plus_plus_11, LLVMDWARFSourceLanguageOCaml, LLVMDWARFSourceLanguageRust,
LLVMDWARFSourceLanguageC11, LLVMDWARFSourceLanguageSwift, LLVMDWARFSourceLanguageJulia, LLVMDWARFSourceLanguageDylan,
LLVMDWARFSourceLanguageC_plus_plus_14, LLVMDWARFSourceLanguageFortran03, LLVMDWARFSourceLanguageFortran08, LLVMDWARFSourceLanguageRenderScript,
LLVMDWARFSourceLanguageBLISS, LLVMDWARFSourceLanguageKotlin, LLVMDWARFSourceLanguageZig, LLVMDWARFSourceLanguageCrystal,
LLVMDWARFSourceLanguageC_plus_plus_17, LLVMDWARFSourceLanguageC_plus_plus_20, LLVMDWARFSourceLanguageC17, LLVMDWARFSourceLanguageFortran18,
LLVMDWARFSourceLanguageAda2005, LLVMDWARFSourceLanguageAda2012, LLVMDWARFSourceLanguageMips_Assembler, LLVMDWARFSourceLanguageGOOGLE_RenderScript,
LLVMDWARFSourceLanguageBORLAND_Delphi
}
Source languages known by DWARF.
enum LLVMDWARFEmissionKind { LLVMDWARFEmissionNone = 0, LLVMDWARFEmissionFull, LLVMDWARFEmissionLineTablesOnly }
The amount of debug information to emit.
enum {
LLVMMDStringMetadataKind, LLVMConstantAsMetadataMetadataKind, LLVMLocalAsMetadataMetadataKind, LLVMDistinctMDOperandPlaceholderMetadataKind,
LLVMMDTupleMetadataKind, LLVMDILocationMetadataKind, LLVMDIExpressionMetadataKind, LLVMDIGlobalVariableExpressionMetadataKind,
LLVMGenericDINodeMetadataKind, LLVMDISubrangeMetadataKind, LLVMDIEnumeratorMetadataKind, LLVMDIBasicTypeMetadataKind,
LLVMDIDerivedTypeMetadataKind, LLVMDICompositeTypeMetadataKind, LLVMDISubroutineTypeMetadataKind, LLVMDIFileMetadataKind,
LLVMDICompileUnitMetadataKind, LLVMDISubprogramMetadataKind, LLVMDILexicalBlockMetadataKind, LLVMDILexicalBlockFileMetadataKind,
LLVMDINamespaceMetadataKind, LLVMDIModuleMetadataKind, LLVMDITemplateTypeParameterMetadataKind, LLVMDITemplateValueParameterMetadataKind,
LLVMDIGlobalVariableMetadataKind, LLVMDILocalVariableMetadataKind, LLVMDILabelMetadataKind, LLVMDIObjCPropertyMetadataKind,
LLVMDIImportedEntityMetadataKind, LLVMDIMacroMetadataKind, LLVMDIMacroFileMetadataKind, LLVMDICommonBlockMetadataKind,
LLVMDIStringTypeMetadataKind, LLVMDIGenericSubrangeMetadataKind, LLVMDIArgListMetadataKind, LLVMDIAssignIDMetadataKind
}
The kind of metadata nodes.
enum LLVMDWARFMacinfoRecordType {
LLVMDWARFMacinfoRecordTypeDefine = 0x01, LLVMDWARFMacinfoRecordTypeMacro = 0x02, LLVMDWARFMacinfoRecordTypeStartFile = 0x03, LLVMDWARFMacinfoRecordTypeEndFile = 0x04,
LLVMDWARFMacinfoRecordTypeVendorExt = 0xff
}
Describes the kind of macro declaration used for LLVMDIBuilderCreateMacro.
Functions
unsigned LLVMDebugMetadataVersion (void)
The current debug metadata version number.
unsigned LLVMGetModuleDebugMetadataVersion (LLVMModuleRef Module)
The version of debug metadata that's present in the provided Module.
LLVMBool LLVMStripModuleDebugInfo (LLVMModuleRef Module)
Strip debug info in the module if it exists.
LLVMDIBuilderRef LLVMCreateDIBuilderDisallowUnresolved (LLVMModuleRef M)
Construct a builder for a module, and do not allow for unresolved nodes attached to the module.
LLVMDIBuilderRef LLVMCreateDIBuilder (LLVMModuleRef M)
Construct a builder for a module and collect unresolved nodes attached to the module in order to resolve cycles during a call to LLVMDIBuilderFinalize.
void LLVMDisposeDIBuilder (LLVMDIBuilderRef Builder)
Deallocates the DIBuilder and everything it owns.
void LLVMDIBuilderFinalize (LLVMDIBuilderRef Builder)
Construct any deferred debug info descriptors.
void LLVMDIBuilderFinalizeSubprogram (LLVMDIBuilderRef Builder, LLVMMetadataRef Subprogram)
Finalize a specific subprogram.
LLVMMetadataRef LLVMDIBuilderCreateCompileUnit (LLVMDIBuilderRef Builder, LLVMDWARFSourceLanguage Lang, LLVMMetadataRef FileRef, const char *Producer, size_t ProducerLen, LLVMBool isOptimized, const char *Flags, size_t FlagsLen, unsigned RuntimeVer, const char *SplitName, size_t SplitNameLen, LLVMDWARFEmissionKind Kind, unsigned DWOId, LLVMBool SplitDebugInlining, LLVMBool DebugInfoForProfiling, const char *SysRoot, size_t SysRootLen, const char *SDK, size_t SDKLen)
A CompileUnit provides an anchor for all debugging information generated during this instance of compilation.
LLVMMetadataRef LLVMDIBuilderCreateFile (LLVMDIBuilderRef Builder, const char *Filename, size_t FilenameLen, const char *Directory, size_t DirectoryLen)
Create a file descriptor to hold debugging information for a file.
LLVMMetadataRef LLVMDIBuilderCreateModule (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, const char *Name, size_t NameLen, const char *ConfigMacros, size_t ConfigMacrosLen, const char *IncludePath, size_t IncludePathLen, const char *APINotesFile, size_t APINotesFileLen)
Creates a new descriptor for a module with the specified parent scope.
LLVMMetadataRef LLVMDIBuilderCreateNameSpace (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, const char *Name, size_t NameLen, LLVMBool ExportSymbols)
Creates a new descriptor for a namespace with the specified parent scope.
LLVMMetadataRef LLVMDIBuilderCreateFunction (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, const char *LinkageName, size_t LinkageNameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool IsLocalToUnit, LLVMBool IsDefinition, unsigned ScopeLine, LLVMDIFlags Flags, LLVMBool IsOptimized)
Create a new descriptor for the specified subprogram.
LLVMMetadataRef LLVMDIBuilderCreateLexicalBlock (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned Column)
Create a descriptor for a lexical block with the specified parent context.
LLVMMetadataRef LLVMDIBuilderCreateLexicalBlockFile (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Discriminator)
Create a descriptor for a lexical block with a new file attached.
LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromNamespace (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef NS, LLVMMetadataRef File, unsigned Line)
Create a descriptor for an imported namespace.
LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromAlias (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef ImportedEntity, LLVMMetadataRef File, unsigned Line, LLVMMetadataRef *Elements, unsigned NumElements)
Create a descriptor for an imported module that aliases another imported entity descriptor.
LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromModule (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef M, LLVMMetadataRef File, unsigned Line, LLVMMetadataRef *Elements, unsigned NumElements)
Create a descriptor for an imported module.
LLVMMetadataRef LLVMDIBuilderCreateImportedDeclaration (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef Decl, LLVMMetadataRef File, unsigned Line, const char *Name, size_t NameLen, LLVMMetadataRef *Elements, unsigned NumElements)
Create a descriptor for an imported function, type, or variable.
LLVMMetadataRef LLVMDIBuilderCreateDebugLocation (LLVMContextRef Ctx, unsigned Line, unsigned Column, LLVMMetadataRef Scope, LLVMMetadataRef InlinedAt)
Creates a new DebugLocation that describes a source location.
unsigned LLVMDILocationGetLine (LLVMMetadataRef Location)
Get the line number of this debug location.
unsigned LLVMDILocationGetColumn (LLVMMetadataRef Location)
Get the column number of this debug location.
LLVMMetadataRef LLVMDILocationGetScope (LLVMMetadataRef Location)
Get the local scope associated with this debug location.
LLVMMetadataRef LLVMDILocationGetInlinedAt (LLVMMetadataRef Location)
Get the "inline at" location associated with this debug location.
LLVMMetadataRef LLVMDIScopeGetFile (LLVMMetadataRef Scope)
Get the metadata of the file associated with a given scope.
const char * LLVMDIFileGetDirectory (LLVMMetadataRef File, unsigned *Len)
Get the directory of a given file.
const char * LLVMDIFileGetFilename (LLVMMetadataRef File, unsigned *Len)
Get the name of a given file.
const char * LLVMDIFileGetSource (LLVMMetadataRef File, unsigned *Len)
Get the source of a given file.
LLVMMetadataRef LLVMDIBuilderGetOrCreateTypeArray (LLVMDIBuilderRef Builder, LLVMMetadataRef *Data, size_t NumElements)
Create a type array.
LLVMMetadataRef LLVMDIBuilderCreateSubroutineType (LLVMDIBuilderRef Builder, LLVMMetadataRef File, LLVMMetadataRef *ParameterTypes, unsigned NumParameterTypes, LLVMDIFlags Flags)
Create subroutine type.
LLVMMetadataRef LLVMDIBuilderCreateMacro (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, unsigned Line, LLVMDWARFMacinfoRecordType RecordType, const char *Name, size_t NameLen, const char *Value, size_t ValueLen)
Create debugging information entry for a macro.
LLVMMetadataRef LLVMDIBuilderCreateTempMacroFile (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, unsigned Line, LLVMMetadataRef File)
Create debugging information temporary entry for a macro file.
LLVMMetadataRef LLVMDIBuilderCreateEnumerator (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen, int64_t Value, LLVMBool IsUnsigned)
Create debugging information entry for an enumerator.
LLVMMetadataRef LLVMDIBuilderCreateEnumerationType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMMetadataRef *Elements, unsigned NumElements, LLVMMetadataRef ClassTy)
Create debugging information entry for an enumeration.
LLVMMetadataRef LLVMDIBuilderCreateUnionType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef *Elements, unsigned NumElements, unsigned RunTimeLang, const char *UniqueId, size_t UniqueIdLen)
Create debugging information entry for a union.
LLVMMetadataRef LLVMDIBuilderCreateArrayType (LLVMDIBuilderRef Builder, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef *Subscripts, unsigned NumSubscripts)
Create debugging information entry for an array.
LLVMMetadataRef LLVMDIBuilderCreateVectorType (LLVMDIBuilderRef Builder, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef *Subscripts, unsigned NumSubscripts)
Create debugging information entry for a vector type.
LLVMMetadataRef LLVMDIBuilderCreateUnspecifiedType (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen)
Create a DWARF unspecified type.
LLVMMetadataRef LLVMDIBuilderCreateBasicType (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen, uint64_t SizeInBits, LLVMDWARFTypeEncoding Encoding, LLVMDIFlags Flags)
Create debugging information entry for a basic type.
LLVMMetadataRef LLVMDIBuilderCreatePointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeTy, uint64_t SizeInBits, uint32_t AlignInBits, unsigned AddressSpace, const char *Name, size_t NameLen)
Create debugging information entry for a pointer.
LLVMMetadataRef LLVMDIBuilderCreateStructType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, LLVMMetadataRef *Elements, unsigned NumElements, unsigned RunTimeLang, LLVMMetadataRef VTableHolder, const char *UniqueId, size_t UniqueIdLen)
Create debugging information entry for a struct.
LLVMMetadataRef LLVMDIBuilderCreateMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty)
Create debugging information entry for a member.
LLVMMetadataRef LLVMDIBuilderCreateStaticMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, LLVMMetadataRef Type, LLVMDIFlags Flags, LLVMValueRef ConstantVal, uint32_t AlignInBits)
Create debugging information entry for a C++ static data member.
LLVMMetadataRef LLVMDIBuilderCreateMemberPointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeType, LLVMMetadataRef ClassType, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags)
Create debugging information entry for a pointer to member.
LLVMMetadataRef LLVMDIBuilderCreateObjCIVar (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty, LLVMMetadataRef PropertyNode)
Create debugging information entry for Objective-C instance variable.
LLVMMetadataRef LLVMDIBuilderCreateObjCProperty (LLVMDIBuilderRef Builder, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, const char *GetterName, size_t GetterNameLen, const char *SetterName, size_t SetterNameLen, unsigned PropertyAttributes, LLVMMetadataRef Ty)
Create debugging information entry for Objective-C property.
LLVMMetadataRef LLVMDIBuilderCreateObjectPointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef Type)
Create a uniqued DIType* clone with FlagObjectPointer and FlagArtificial set.
LLVMMetadataRef LLVMDIBuilderCreateQualifiedType (LLVMDIBuilderRef Builder, unsigned Tag, LLVMMetadataRef Type)
Create debugging information entry for a qualified type, e.g.
LLVMMetadataRef LLVMDIBuilderCreateReferenceType (LLVMDIBuilderRef Builder, unsigned Tag, LLVMMetadataRef Type)
Create debugging information entry for a c++ style reference or rvalue reference type.
LLVMMetadataRef LLVMDIBuilderCreateNullPtrType (LLVMDIBuilderRef Builder)
Create C++11 nullptr type.
LLVMMetadataRef LLVMDIBuilderCreateTypedef (LLVMDIBuilderRef Builder, LLVMMetadataRef Type, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Scope, uint32_t AlignInBits)
Create debugging information entry for a typedef.
LLVMMetadataRef LLVMDIBuilderCreateInheritance (LLVMDIBuilderRef Builder, LLVMMetadataRef Ty, LLVMMetadataRef BaseTy, uint64_t BaseOffset, uint32_t VBPtrOffset, LLVMDIFlags Flags)
Create debugging information entry to establish inheritance relationship between two types.
LLVMMetadataRef LLVMDIBuilderCreateForwardDecl (LLVMDIBuilderRef Builder, unsigned Tag, const char *Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint32_t AlignInBits, const char *UniqueIdentifier, size_t UniqueIdentifierLen)
Create a permanent forward-declared type.
LLVMMetadataRef LLVMDIBuilderCreateReplaceableCompositeType (LLVMDIBuilderRef Builder, unsigned Tag, const char *Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, const char *UniqueIdentifier, size_t UniqueIdentifierLen)
Create a temporary forward-declared type.
LLVMMetadataRef LLVMDIBuilderCreateBitFieldMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint64_t OffsetInBits, uint64_t StorageOffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Type)
Create debugging information entry for a bit field member.
LLVMMetadataRef LLVMDIBuilderCreateClassType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, LLVMMetadataRef *Elements, unsigned NumElements, LLVMMetadataRef VTableHolder, LLVMMetadataRef TemplateParamsNode, const char *UniqueIdentifier, size_t UniqueIdentifierLen)
Create debugging information entry for a class.
LLVMMetadataRef LLVMDIBuilderCreateArtificialType (LLVMDIBuilderRef Builder, LLVMMetadataRef Type)
Create a uniqued DIType* clone with FlagArtificial set.
const char * LLVMDITypeGetName (LLVMMetadataRef DType, size_t *Length)
Get the name of this DIType.
uint64_t LLVMDITypeGetSizeInBits (LLVMMetadataRef DType)
Get the size of this DIType in bits.
uint64_t LLVMDITypeGetOffsetInBits (LLVMMetadataRef DType)
Get the offset of this DIType in bits.
uint32_t LLVMDITypeGetAlignInBits (LLVMMetadataRef DType)
Get the alignment of this DIType in bits.
unsigned LLVMDITypeGetLine (LLVMMetadataRef DType)
Get the source line where this DIType is declared.
LLVMDIFlags LLVMDITypeGetFlags (LLVMMetadataRef DType)
Get the flags associated with this DIType.
LLVMMetadataRef LLVMDIBuilderGetOrCreateSubrange (LLVMDIBuilderRef Builder, int64_t LowerBound, int64_t Count)
Create a descriptor for a value range.
LLVMMetadataRef LLVMDIBuilderGetOrCreateArray (LLVMDIBuilderRef Builder, LLVMMetadataRef *Data, size_t NumElements)
Create an array of DI Nodes.
LLVMMetadataRef LLVMDIBuilderCreateExpression (LLVMDIBuilderRef Builder, uint64_t *Addr, size_t Length)
Create a new descriptor for the specified variable which has a complex address expression for its address.
LLVMMetadataRef LLVMDIBuilderCreateConstantValueExpression (LLVMDIBuilderRef Builder, uint64_t Value)
Create a new descriptor for the specified variable that does not have an address, but does have a constant value.
LLVMMetadataRef LLVMDIBuilderCreateGlobalVariableExpression (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, const char *Linkage, size_t LinkLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool LocalToUnit, LLVMMetadataRef Expr, LLVMMetadataRef Decl, uint32_t AlignInBits)
Create a new descriptor for the specified variable.
uint16_t LLVMGetDINodeTag (LLVMMetadataRef MD)
Get the dwarf::Tag of a DINode.
LLVMMetadataRef LLVMDIGlobalVariableExpressionGetVariable (LLVMMetadataRef GVE)
Retrieves the DIVariable associated with this global variable expression.
LLVMMetadataRef LLVMDIGlobalVariableExpressionGetExpression (LLVMMetadataRef GVE)
Retrieves the DIExpression associated with this global variable expression.
LLVMMetadataRef LLVMDIVariableGetFile (LLVMMetadataRef Var)
Get the metadata of the file associated with a given variable.
LLVMMetadataRef LLVMDIVariableGetScope (LLVMMetadataRef Var)
Get the metadata of the scope associated with a given variable.
unsigned LLVMDIVariableGetLine (LLVMMetadataRef Var)
Get the source line where this DIVariable is declared.
LLVMMetadataRef LLVMTemporaryMDNode (LLVMContextRef Ctx, LLVMMetadataRef *Data, size_t NumElements)
Create a new temporary MDNode.
void LLVMDisposeTemporaryMDNode (LLVMMetadataRef TempNode)
Deallocate a temporary node.
void LLVMMetadataReplaceAllUsesWith (LLVMMetadataRef TempTargetMetadata, LLVMMetadataRef Replacement)
Replace all uses of temporary metadata.
LLVMMetadataRef LLVMDIBuilderCreateTempGlobalVariableFwdDecl (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, const char *Linkage, size_t LnkLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool LocalToUnit, LLVMMetadataRef Decl, uint32_t AlignInBits)
Create a new descriptor for the specified global variable that is temporary and meant to be RAUWed.
LLVMValueRef LLVMDIBuilderInsertDeclareBefore (LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr)
Insert a new llvm.dbg.declare intrinsic call before the given instruction.
LLVMValueRef LLVMDIBuilderInsertDeclareAtEnd (LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block)
Insert a new llvm.dbg.declare intrinsic call at the end of the given basic block.
LLVMValueRef LLVMDIBuilderInsertDbgValueBefore (LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr)
Insert a new llvm.dbg.value intrinsic call before the given instruction.
LLVMValueRef LLVMDIBuilderInsertDbgValueAtEnd (LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block)
Insert a new llvm.dbg.value intrinsic call at the end of the given basic block.
LLVMMetadataRef LLVMDIBuilderCreateAutoVariable (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool AlwaysPreserve, LLVMDIFlags Flags, uint32_t AlignInBits)
Create a new descriptor for a local auto variable.
LLVMMetadataRef LLVMDIBuilderCreateParameterVariable (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char *Name, size_t NameLen, unsigned ArgNo, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool AlwaysPreserve, LLVMDIFlags Flags)
Create a new descriptor for a function parameter variable.
LLVMMetadataRef LLVMGetSubprogram (LLVMValueRef Func)
Get the metadata of the subprogram attached to a function.
void LLVMSetSubprogram (LLVMValueRef Func, LLVMMetadataRef SP)
Set the subprogram attached to a function.
unsigned LLVMDISubprogramGetLine (LLVMMetadataRef Subprogram)
Get the line associated with a given subprogram.
LLVMMetadataRef LLVMInstructionGetDebugLoc (LLVMValueRef Inst)
Get the debug location for the given instruction.
void LLVMInstructionSetDebugLoc (LLVMValueRef Inst, LLVMMetadataRef Loc)
Set the debug location for the given instruction.
LLVMMetadataKind LLVMGetMetadataKind (LLVMMetadataRef Metadata)
Obtain the enumerated type of a Metadata instance.
Detailed Description
This file declares the C API endpoints for generating DWARF Debug Info.
Note: This interface is experimental. It is NOT stable, and may be changed without warning.
Typedef Documentation
LLVMDWARFTypeEncoding
typedef unsigned LLVMDWARFTypeEncoding
An LLVM DWARF type encoding.
Definition at line 189 of file DebugInfo.h.
LLVMMetadataKind
typedef unsigned LLVMMetadataKind
Definition at line 184 of file DebugInfo.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
The kind of metadata nodes.
Enumerator
LLVMMDStringMetadataKind
LLVMConstantAsMetadataMetadataKind
LLVMLocalAsMetadataMetadataKind
LLVMDistinctMDOperandPlaceholderMetadataKind
LLVMMDTupleMetadataKind
LLVMDILocationMetadataKind
LLVMDIExpressionMetadataKind
LLVMDIGlobalVariableExpressionMetadataKind
LLVMGenericDINodeMetadataKind
LLVMDISubrangeMetadataKind
LLVMDIEnumeratorMetadataKind
LLVMDIBasicTypeMetadataKind
LLVMDIDerivedTypeMetadataKind
LLVMDICompositeTypeMetadataKind
LLVMDISubroutineTypeMetadataKind
LLVMDIFileMetadataKind
LLVMDICompileUnitMetadataKind
LLVMDISubprogramMetadataKind
LLVMDILexicalBlockMetadataKind
LLVMDILexicalBlockFileMetadataKind
LLVMDINamespaceMetadataKind
LLVMDIModuleMetadataKind
LLVMDITemplateTypeParameterMetadataKind
LLVMDITemplateValueParameterMetadataKind
LLVMDIGlobalVariableMetadataKind
LLVMDILocalVariableMetadataKind
LLVMDILabelMetadataKind
LLVMDIObjCPropertyMetadataKind
LLVMDIImportedEntityMetadataKind
LLVMDIMacroMetadataKind
LLVMDIMacroFileMetadataKind
LLVMDICommonBlockMetadataKind
LLVMDIStringTypeMetadataKind
LLVMDIGenericSubrangeMetadataKind
LLVMDIArgListMetadataKind
LLVMDIAssignIDMetadataKind
Definition at line 146 of file DebugInfo.h.
LLVMDIFlags
enum LLVMDIFlags
Debug info flags.
Enumerator
LLVMDIFlagZero
LLVMDIFlagPrivate
LLVMDIFlagProtected
LLVMDIFlagPublic
LLVMDIFlagFwdDecl
LLVMDIFlagAppleBlock
LLVMDIFlagReservedBit4
LLVMDIFlagVirtual
LLVMDIFlagArtificial
LLVMDIFlagExplicit
LLVMDIFlagPrototyped
LLVMDIFlagObjcClassComplete
LLVMDIFlagObjectPointer
LLVMDIFlagVector
LLVMDIFlagStaticMember
LLVMDIFlagLValueReference
LLVMDIFlagRValueReference
LLVMDIFlagReserved
LLVMDIFlagSingleInheritance
LLVMDIFlagMultipleInheritance
LLVMDIFlagVirtualInheritance
LLVMDIFlagIntroducedVirtual
LLVMDIFlagBitField
LLVMDIFlagNoReturn
LLVMDIFlagTypePassByValue
LLVMDIFlagTypePassByReference
LLVMDIFlagEnumClass
LLVMDIFlagFixedEnum
LLVMDIFlagThunk
LLVMDIFlagNonTrivial
LLVMDIFlagBigEndian
LLVMDIFlagLittleEndian
LLVMDIFlagIndirectVirtualBase
LLVMDIFlagAccessibility
LLVMDIFlagPtrToMemberRep
Definition at line 34 of file DebugInfo.h.
LLVMDWARFEmissionKind
enum LLVMDWARFEmissionKind
The amount of debug information to emit.
Enumerator
LLVMDWARFEmissionNone
LLVMDWARFEmissionFull
LLVMDWARFEmissionLineTablesOnly
Definition at line 137 of file DebugInfo.h.
LLVMDWARFMacinfoRecordType
enum LLVMDWARFMacinfoRecordType
Describes the kind of macro declaration used for LLVMDIBuilderCreateMacro.
See also
llvm::dwarf::MacinfoRecordType
Note
Values are from DW_MACINFO_* constants in the DWARF specification.
Enumerator
LLVMDWARFMacinfoRecordTypeDefine
LLVMDWARFMacinfoRecordTypeMacro
LLVMDWARFMacinfoRecordTypeStartFile
LLVMDWARFMacinfoRecordTypeEndFile
LLVMDWARFMacinfoRecordTypeVendorExt
Definition at line 196 of file DebugInfo.h.
LLVMDWARFSourceLanguage
enum LLVMDWARFSourceLanguage
Source languages known by DWARF.
Enumerator
LLVMDWARFSourceLanguageC89
LLVMDWARFSourceLanguageC
LLVMDWARFSourceLanguageAda83
LLVMDWARFSourceLanguageC_plus_plus
LLVMDWARFSourceLanguageCobol74
LLVMDWARFSourceLanguageCobol85
LLVMDWARFSourceLanguageFortran77
LLVMDWARFSourceLanguageFortran90
LLVMDWARFSourceLanguagePascal83
LLVMDWARFSourceLanguageModula2
LLVMDWARFSourceLanguageJava
LLVMDWARFSourceLanguageC99
LLVMDWARFSourceLanguageAda95
LLVMDWARFSourceLanguageFortran95
LLVMDWARFSourceLanguagePLI
LLVMDWARFSourceLanguageObjC
LLVMDWARFSourceLanguageObjC_plus_plus
LLVMDWARFSourceLanguageUPC
LLVMDWARFSourceLanguageD
LLVMDWARFSourceLanguagePython
LLVMDWARFSourceLanguageOpenCL
LLVMDWARFSourceLanguageGo
LLVMDWARFSourceLanguageModula3
LLVMDWARFSourceLanguageHaskell
LLVMDWARFSourceLanguageC_plus_plus_03
LLVMDWARFSourceLanguageC_plus_plus_11
LLVMDWARFSourceLanguageOCaml
LLVMDWARFSourceLanguageRust
LLVMDWARFSourceLanguageC11
LLVMDWARFSourceLanguageSwift
LLVMDWARFSourceLanguageJulia
LLVMDWARFSourceLanguageDylan
LLVMDWARFSourceLanguageC_plus_plus_14
LLVMDWARFSourceLanguageFortran03
LLVMDWARFSourceLanguageFortran08
LLVMDWARFSourceLanguageRenderScript
LLVMDWARFSourceLanguageBLISS
LLVMDWARFSourceLanguageKotlin
LLVMDWARFSourceLanguageZig
LLVMDWARFSourceLanguageCrystal
LLVMDWARFSourceLanguageC_plus_plus_17
LLVMDWARFSourceLanguageC_plus_plus_20
LLVMDWARFSourceLanguageC17
LLVMDWARFSourceLanguageFortran18
LLVMDWARFSourceLanguageAda2005
LLVMDWARFSourceLanguageAda2012
LLVMDWARFSourceLanguageMips_Assembler
LLVMDWARFSourceLanguageGOOGLE_RenderScript
LLVMDWARFSourceLanguageBORLAND_Delphi
Definition at line 78 of file DebugInfo.h.
Function Documentation
LLVMCreateDIBuilder()
LLVMDIBuilderRef LLVMCreateDIBuilder (LLVMModuleRef M)
Construct a builder for a module and collect unresolved nodes attached to the module in order to resolve cycles during a call to LLVMDIBuilderFinalize.
Definition at line 1009 of file DebugInfo.cpp.
References M, llvm::unwrap(), and llvm::wrap().
LLVMCreateDIBuilderDisallowUnresolved()
LLVMDIBuilderRef LLVMCreateDIBuilderDisallowUnresolved (LLVMModuleRef M)
Construct a builder for a module, and do not allow for unresolved nodes attached to the module.
Definition at line 1005 of file DebugInfo.cpp.
References M, llvm::unwrap(), and llvm::wrap().
LLVMDebugMetadataVersion()
unsigned LLVMDebugMetadataVersion (void)
The current debug metadata version number.
Definition at line 1001 of file DebugInfo.cpp.
References llvm::DEBUG_METADATA_VERSION.
LLVMDIBuilderCreateArrayType()
LLVMMetadataRef LLVMDIBuilderCreateArrayType (LLVMDIBuilderRef Builder, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef * Subscripts, unsigned NumSubscripts)
Create debugging information entry for an array.
Parameters
Builder The DIBuilder.
Size Array size.
AlignInBits Alignment.
Ty Element type.
Subscripts Subscripts.
NumSubscripts Number of subscripts.
Definition at line 1272 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateArtificialType()
LLVMMetadataRef LLVMDIBuilderCreateArtificialType (LLVMDIBuilderRef Builder, LLVMMetadataRef Type)
Create a uniqued DIType* clone with FlagArtificial set.
Parameters
Builder The DIBuilder.
Type The underlying type.
Definition at line 1506 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateAutoVariable()
LLVMMetadataRef LLVMDIBuilderCreateAutoVariable (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool AlwaysPreserve, LLVMDIFlags Flags, uint32_t AlignInBits)
Create a new descriptor for a local auto variable.
Parameters
Builder The DIBuilder.
Scope The local scope the variable is declared in.
Name Variable name.
NameLen Length of variable name.
File File where this variable is defined.
LineNo Line number.
Ty Metadata describing the type of the variable.
AlwaysPreserve If true, this descriptor will survive optimizations.
Flags Flags.
AlignInBits Variable alignment.
Definition at line 1676 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateBasicType()
LLVMMetadataRef LLVMDIBuilderCreateBasicType (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen, uint64_t SizeInBits, LLVMDWARFTypeEncoding Encoding, LLVMDIFlags Flags)
Create debugging information entry for a basic type.
Parameters
Builder The DIBuilder.
Name Type name.
NameLen Length of type name.
SizeInBits Size of the type.
Encoding DWARF encoding code, e.g. LLVMDWARFTypeEncoding_float.
Flags Flags to encode optional attribute like endianity
Definition at line 1294 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateBitFieldMemberType()
LLVMMetadataRef LLVMDIBuilderCreateBitFieldMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint64_t OffsetInBits, uint64_t StorageOffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Type)
Create debugging information entry for a bit field member.
Parameters
Builder The DIBuilder.
Scope Member scope.
Name Member name.
NameLen Length of member name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
OffsetInBits Member offset.
StorageOffsetInBits Member storage offset.
Flags Flags to encode member attribute.
Type Parent type.
Definition at line 1470 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateClassType()
LLVMMetadataRef LLVMDIBuilderCreateClassType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, LLVMMetadataRef * Elements, unsigned NumElements, LLVMMetadataRef VTableHolder, LLVMMetadataRef TemplateParamsNode, const char * UniqueIdentifier, size_t UniqueIdentifierLen)
Create debugging information entry for a class.
Parameters
Scope Scope in which this class is defined.
Name Class name.
NameLen The length of the C string passed to Name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
OffsetInBits Member offset.
Flags Flags to encode member attribute, e.g. private.
DerivedFrom Debug info of the base class of this type.
Elements Class members.
NumElements Number of class elements.
VTableHolder Debug info of the base class that contains vtable for this type. This is used in DW_AT_containing_type. See DWARF documentation for more info.
TemplateParamsNode Template type parameters.
UniqueIdentifier A unique identifier for the type.
UniqueIdentifierLen Length of the unique identifier.
Definition at line 1485 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateCompileUnit()
LLVMMetadataRef LLVMDIBuilderCreateCompileUnit (LLVMDIBuilderRef Builder, LLVMDWARFSourceLanguage Lang, LLVMMetadataRef FileRef, const char * Producer, size_t ProducerLen, LLVMBool isOptimized, const char * Flags, size_t FlagsLen, unsigned RuntimeVer, const char * SplitName, size_t SplitNameLen, LLVMDWARFEmissionKind Kind, unsigned DWOId, LLVMBool SplitDebugInlining, LLVMBool DebugInfoForProfiling, const char * SysRoot, size_t SysRootLen, const char * SDK, size_t SDKLen)
A CompileUnit provides an anchor for all debugging information generated during this instance of compilation.
Parameters
Lang Source programming language, eg. LLVMDWARFSourceLanguageC99
FileRef File info.
Producer Identify the producer of debugging information and code. Usually this is a compiler version string.
ProducerLen The length of the C string passed to Producer.
isOptimized A boolean flag which indicates whether optimization is enabled or not.
Flags This string lists command line options. This string is directly embedded in debug info output which may be used by a tool analyzing generated debugging information.
FlagsLen The length of the C string passed to Flags.
RuntimeVer This indicates runtime version for languages like Objective-C.
SplitName The name of the file that we'll split debug info out into.
SplitNameLen The length of the C string passed to SplitName.
Kind The kind of debug information to generate.
DWOId The DWOId if this is a split skeleton compile unit.
SplitDebugInlining Whether to emit inline debug info.
DebugInfoForProfiling Whether to emit extra debug info for profile collection.
SysRoot The Clang system root (value of -isysroot).
SysRootLen The length of the C string passed to SysRoot.
SDK The SDK. On Darwin, the last component of the sysroot.
SDKLen The length of the C string passed to SDK.
Definition at line 1034 of file DebugInfo.cpp.
References Builder, llvm::DICompileUnit::Default, map_from_llvmDWARFsourcelanguage(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateConstantValueExpression()
LLVMMetadataRef LLVMDIBuilderCreateConstantValueExpression (LLVMDIBuilderRef Builder, uint64_t Value)
Create a new descriptor for the specified variable that does not have an address, but does have a constant value.
Parameters
Builder The DIBuilder.
Value The constant value.
Definition at line 1567 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateDebugLocation()
LLVMMetadataRef LLVMDIBuilderCreateDebugLocation (LLVMContextRef Ctx, unsigned Line, unsigned Column, LLVMMetadataRef Scope, LLVMMetadataRef InlinedAt)
Creates a new DebugLocation that describes a source location.
Parameters
Line The line in the source file.
Column The column in the source file.
Scope The scope in which the location resides.
InlinedAt The scope where this location was inlined, if at all. (optional).
Note
If the item to which this location is attached cannot be attributed to a source line, pass 0 for the line and column.
Definition at line 1168 of file DebugInfo.cpp.
References llvm::MDNode::get(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateEnumerationType()
LLVMMetadataRef LLVMDIBuilderCreateEnumerationType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMMetadataRef * Elements, unsigned NumElements, LLVMMetadataRef ClassTy)
Create debugging information entry for an enumeration.
Parameters
Builder The DIBuilder.
Scope Scope in which this enumeration is defined.
Name Enumeration name.
NameLen Length of enumeration name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
Elements Enumeration elements.
NumElements Number of enumeration elements.
ClassTy Underlying type of a C++11/ObjC fixed enum.
Definition at line 1244 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateEnumerator()
LLVMMetadataRef LLVMDIBuilderCreateEnumerator (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen, int64_t Value, LLVMBool IsUnsigned)
Create debugging information entry for an enumerator.
Parameters
Builder The DIBuilder.
Name Enumerator name.
NameLen Length of enumerator name.
Value Enumerator value.
IsUnsigned True if the value is unsigned.
Definition at line 1236 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateExpression()
LLVMMetadataRef LLVMDIBuilderCreateExpression (LLVMDIBuilderRef Builder, uint64_t * Addr, size_t Length)
Create a new descriptor for the specified variable which has a complex address expression for its address.
Parameters
Builder The DIBuilder.
Addr An array of complex address operations.
Length Length of the address operation array.
Definition at line 1560 of file DebugInfo.cpp.
References Addr, Builder, llvm::Length, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateFile()
LLVMMetadataRef LLVMDIBuilderCreateFile (LLVMDIBuilderRef Builder, const char * Filename, size_t FilenameLen, const char * Directory, size_t DirectoryLen)
Create a file descriptor to hold debugging information for a file.
Parameters
Builder The DIBuilder.
Filename File name.
FilenameLen The length of the C string passed to Filename.
Directory Directory.
DirectoryLen The length of the C string passed to Directory.
Definition at line 1055 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateForwardDecl()
LLVMMetadataRef LLVMDIBuilderCreateForwardDecl (LLVMDIBuilderRef Builder, unsigned Tag, const char * Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint32_t AlignInBits, const char * UniqueIdentifier, size_t UniqueIdentifierLen)
Create a permanent forward-declared type.
Parameters
Builder The DIBuilder.
Tag A unique tag for this type.
Name Type name.
NameLen Length of type name.
Scope Type scope.
File File where this type is defined.
Line Line number where this type is defined.
RuntimeLang Indicates runtime version for languages like Objective-C.
SizeInBits Member size.
AlignInBits Member alignment.
UniqueIdentifier A unique identifier for the type.
UniqueIdentifierLen Length of the unique identifier.
Definition at line 1412 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateFunction()
LLVMMetadataRef LLVMDIBuilderCreateFunction (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, const char * LinkageName, size_t LinkageNameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool IsLocalToUnit, LLVMBool IsDefinition, unsigned ScopeLine, LLVMDIFlags Flags, LLVMBool IsOptimized)
Create a new descriptor for the specified subprogram.
Parameters
Builder The DIBuilder.
Scope Function scope.
Name Function name.
NameLen Length of enumeration name.
LinkageName Mangled function name.
LinkageNameLen Length of linkage name.
File File where this variable is defined.
LineNo Line number.
Ty Function type.
IsLocalToUnit True if this function is not externally visible.
IsDefinition True if this is a function definition.
ScopeLine Set to the beginning of the scope this starts
Flags E.g.: LLVMDIFlagLValueReference. These flags are used to emit dwarf attributes.
IsOptimized True if optimization is ON.
Definition at line 1083 of file DebugInfo.cpp.
References Builder, llvm::LinkageName, map_from_llvmDIFlags(), pack_into_DISPFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateGlobalVariableExpression()
LLVMMetadataRef LLVMDIBuilderCreateGlobalVariableExpression (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, const char * Linkage, size_t LinkLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool LocalToUnit, LLVMMetadataRef Expr, LLVMMetadataRef Decl, uint32_t AlignInBits)
Create a new descriptor for the specified variable.
Parameters
Scope Variable scope.
Name Name of the variable.
NameLen The length of the C string passed to Name.
Linkage Mangled name of the variable.
LinkLen The length of the C string passed to Linkage.
File File where this variable is defined.
LineNo Line number.
Ty Variable Type.
LocalToUnit Boolean flag indicate whether this variable is externally visible or not.
Expr The location of the global relative to the attached GlobalVariable.
Decl Reference to the corresponding declaration. variables.
AlignInBits Variable alignment(or 0 if no alignment attr was specified)
Definition at line 1572 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateImportedDeclaration()
LLVMMetadataRef LLVMDIBuilderCreateImportedDeclaration (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef Decl, LLVMMetadataRef File, unsigned Line, const char * Name, size_t NameLen, LLVMMetadataRef * Elements, unsigned NumElements)
Create a descriptor for an imported function, type, or variable.
Suitable for e.g. FORTRAN-style USE declarations.
Parameters
Builder The DIBuilder.
Scope The scope this module is imported into.
Decl The declaration (or definition) of a function, type, or variable.
File File where the declaration is located.
Line Line number of the declaration.
Name A name that uniquely identifies this imported declaration.
NameLen The length of the C string passed to Name.
Elements Renamed elements.
NumElements Number of renamed elements.
Definition at line 1154 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateImportedModuleFromAlias()
LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromAlias (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef ImportedEntity, LLVMMetadataRef File, unsigned Line, LLVMMetadataRef * Elements, unsigned NumElements)
Create a descriptor for an imported module that aliases another imported entity descriptor.
Parameters
Builder The DIBuilder.
Scope The scope this module is imported into
ImportedEntity Previous imported entity to alias.
File File where the declaration is located.
Line Line number of the declaration.
Elements Renamed elements.
NumElements Number of renamed elements.
Definition at line 1128 of file DebugInfo.cpp.
References Builder, createImportedModule(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateImportedModuleFromModule()
LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromModule (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef M, LLVMMetadataRef File, unsigned Line, LLVMMetadataRef * Elements, unsigned NumElements)
Create a descriptor for an imported module.
Parameters
Builder The DIBuilder.
Scope The scope this module is imported into
M The module being imported here
File File where the declaration is located.
Line Line number of the declaration.
Elements Renamed elements.
NumElements Number of renamed elements.
Definition at line 1141 of file DebugInfo.cpp.
References Builder, createImportedModule(), M, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateImportedModuleFromNamespace()
LLVMMetadataRef LLVMDIBuilderCreateImportedModuleFromNamespace (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef NS, LLVMMetadataRef File, unsigned Line)
Create a descriptor for an imported namespace.
Suitable for e.g. C++ using declarations.
Parameters
Builder The DIBuilder.
Scope The scope this module is imported into
File File where the declaration is located.
Line Line number of the declaration.
Definition at line 1117 of file DebugInfo.cpp.
References Builder, createImportedModule(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateInheritance()
LLVMMetadataRef LLVMDIBuilderCreateInheritance (LLVMDIBuilderRef Builder, LLVMMetadataRef Ty, LLVMMetadataRef BaseTy, uint64_t BaseOffset, uint32_t VBPtrOffset, LLVMDIFlags Flags)
Create debugging information entry to establish inheritance relationship between two types.
Parameters
Builder The DIBuilder.
Ty Original type.
BaseTy Base type. Ty is inherits from base.
BaseOffset Base offset.
VBPtrOffset Virtual base pointer offset.
Flags Flags to describe inheritance attribute, e.g. private
Definition at line 1402 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateLexicalBlock()
LLVMMetadataRef LLVMDIBuilderCreateLexicalBlock (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned Column)
Create a descriptor for a lexical block with the specified parent context.
Parameters
Builder The DIBuilder.
Scope Parent lexical block.
File Source file.
Line The line in the source file.
Column The column in the source file.
Definition at line 1098 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateLexicalBlockFile()
LLVMMetadataRef LLVMDIBuilderCreateLexicalBlockFile (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Discriminator)
Create a descriptor for a lexical block with a new file attached.
Parameters
Builder The DIBuilder.
Scope Lexical block.
File Source file.
Discriminator DWARF path discriminator value.
Definition at line 1107 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateMacro()
LLVMMetadataRef LLVMDIBuilderCreateMacro (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, unsigned Line, LLVMDWARFMacinfoRecordType RecordType, const char * Name, size_t NameLen, const char * Value, size_t ValueLen)
Create debugging information entry for a macro.
Parameters
Builder The DIBuilder.
ParentMacroFile Macro parent (could be NULL).
Line Source line number where the macro is defined.
RecordType DW_MACINFO_define or DW_MACINFO_undef.
Name Macro name.
NameLen Macro name length.
Value Macro value.
ValueLen Macro value length.
Definition at line 1216 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateMemberPointerType()
LLVMMetadataRef LLVMDIBuilderCreateMemberPointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeType, LLVMMetadataRef ClassType, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags)
Create debugging information entry for a pointer to member.
Parameters
Builder The DIBuilder.
PointeeType Type pointed to by this pointer.
ClassType Type for which this pointer points to members of.
SizeInBits Size.
AlignInBits Alignment.
Flags Flags.
Definition at line 1457 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateMemberType()
LLVMMetadataRef LLVMDIBuilderCreateMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty)
Create debugging information entry for a member.
Parameters
Builder The DIBuilder.
Scope Member scope.
Name Member name.
NameLen Length of member name.
File File where this member is defined.
LineNo Line number.
SizeInBits Member size.
AlignInBits Member alignment.
OffsetInBits Member offset.
Flags Flags to encode member attribute, e.g. private
Ty Parent type.
Definition at line 1328 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateModule()
LLVMMetadataRef LLVMDIBuilderCreateModule (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, const char * Name, size_t NameLen, const char * ConfigMacros, size_t ConfigMacrosLen, const char * IncludePath, size_t IncludePathLen, const char * APINotesFile, size_t APINotesFileLen)
Creates a new descriptor for a module with the specified parent scope.
Parameters
Builder The DIBuilder.
ParentScope The parent scope containing this module declaration.
Name Module name.
NameLen The length of the C string passed to Name.
ConfigMacros A space-separated shell-quoted list of -D macro definitions as they would appear on a command line.
ConfigMacrosLen The length of the C string passed to ConfigMacros.
IncludePath The path to the module map file.
IncludePathLen The length of the C string passed to IncludePath.
APINotesFile The path to an API notes file for the module.
APINotesFileLen The length of the C string passed to APINotestFile.
Definition at line 1063 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateNameSpace()
LLVMMetadataRef LLVMDIBuilderCreateNameSpace (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentScope, const char * Name, size_t NameLen, LLVMBool ExportSymbols)
Creates a new descriptor for a namespace with the specified parent scope.
Parameters
Builder The DIBuilder.
ParentScope The parent scope containing this module declaration.
Name NameSpace name.
NameLen The length of the C string passed to Name.
ExportSymbols Whether or not the namespace exports symbols, e.g. this is true of C++ inline namespaces.
Definition at line 1075 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateNullPtrType()
LLVMMetadataRef LLVMDIBuilderCreateNullPtrType (LLVMDIBuilderRef Builder)
Create C++11 nullptr type.
Parameters
Builder The DIBuilder.
Definition at line 1452 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateObjCIVar()
LLVMMetadataRef LLVMDIBuilderCreateObjCIVar (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, uint64_t SizeInBits, uint32_t AlignInBits, uint64_t OffsetInBits, LLVMDIFlags Flags, LLVMMetadataRef Ty, LLVMMetadataRef PropertyNode)
Create debugging information entry for Objective-C instance variable.
Parameters
Builder The DIBuilder.
Name Member name.
NameLen The length of the C string passed to Name.
File File where this member is defined.
LineNo Line number.
SizeInBits Member size.
AlignInBits Member alignment.
OffsetInBits Member offset.
Flags Flags to encode member attribute, e.g. private
Ty Parent type.
PropertyNode Property associated with this ivar.
Definition at line 1358 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateObjCProperty()
LLVMMetadataRef LLVMDIBuilderCreateObjCProperty (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, const char * GetterName, size_t GetterNameLen, const char * SetterName, size_t SetterNameLen, unsigned PropertyAttributes, LLVMMetadataRef Ty)
Create debugging information entry for Objective-C property.
Parameters
Builder The DIBuilder.
Name Property name.
NameLen The length of the C string passed to Name.
File File where this property is defined.
LineNo Line number.
GetterName Name of the Objective C property getter selector.
GetterNameLen The length of the C string passed to GetterName.
SetterName Name of the Objective C property setter selector.
SetterNameLen The length of the C string passed to SetterName.
PropertyAttributes Objective C property attributes.
Ty Type.
Definition at line 1372 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateObjectPointerType()
LLVMMetadataRef LLVMDIBuilderCreateObjectPointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef Type)
Create a uniqued DIType* clone with FlagObjectPointer and FlagArtificial set.
Parameters
Builder The DIBuilder.
Type The underlying type to which this pointer points.
Definition at line 1386 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateParameterVariable()
LLVMMetadataRef LLVMDIBuilderCreateParameterVariable (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, unsigned ArgNo, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool AlwaysPreserve, LLVMDIFlags Flags)
Create a new descriptor for a function parameter variable.
Parameters
Builder The DIBuilder.
Scope The local scope the variable is declared in.
Name Variable name.
NameLen Length of variable name.
ArgNo Unique argument number for this variable; starts at 1.
File File where this variable is defined.
LineNo Line number.
Ty Metadata describing the type of the variable.
AlwaysPreserve If true, this descriptor will survive optimizations.
Flags Flags.
Definition at line 1686 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreatePointerType()
LLVMMetadataRef LLVMDIBuilderCreatePointerType (LLVMDIBuilderRef Builder, LLVMMetadataRef PointeeTy, uint64_t SizeInBits, uint32_t AlignInBits, unsigned AddressSpace, const char * Name, size_t NameLen)
Create debugging information entry for a pointer.
Parameters
Builder The DIBuilder.
PointeeTy Type pointed by this pointer.
SizeInBits Size.
AlignInBits Alignment. (optional, pass 0 to ignore)
AddressSpace DWARF address space. (optional, pass 0 to ignore)
Name Pointer type name. (optional)
NameLen Length of pointer type name. (optional)
Definition at line 1303 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateQualifiedType()
LLVMMetadataRef LLVMDIBuilderCreateQualifiedType (LLVMDIBuilderRef Builder, unsigned Tag, LLVMMetadataRef Type)
Create debugging information entry for a qualified type, e.g.
'const int'.
Parameters
Builder The DIBuilder.
Tag Tag identifying type, e.g. LLVMDWARFTypeQualifier_volatile_type
Type Base Type.
Definition at line 1438 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateReferenceType()
LLVMMetadataRef LLVMDIBuilderCreateReferenceType (LLVMDIBuilderRef Builder, unsigned Tag, LLVMMetadataRef Type)
Create debugging information entry for a c++ style reference or rvalue reference type.
Parameters
Builder The DIBuilder.
Tag Tag identifying type,
Type Base Type.
Definition at line 1445 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateReplaceableCompositeType()
LLVMMetadataRef LLVMDIBuilderCreateReplaceableCompositeType (LLVMDIBuilderRef Builder, unsigned Tag, const char * Name, size_t NameLen, LLVMMetadataRef Scope, LLVMMetadataRef File, unsigned Line, unsigned RuntimeLang, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, const char * UniqueIdentifier, size_t UniqueIdentifierLen)
Create a temporary forward-declared type.
Parameters
Builder The DIBuilder.
Tag A unique tag for this type.
Name Type name.
NameLen Length of type name.
Scope Type scope.
File File where this type is defined.
Line Line number where this type is defined.
RuntimeLang Indicates runtime version for languages like Objective-C.
SizeInBits Member size.
AlignInBits Member alignment.
Flags Flags.
UniqueIdentifier A unique identifier for the type.
UniqueIdentifierLen Length of the unique identifier.
Definition at line 1424 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateStaticMemberType()
LLVMMetadataRef LLVMDIBuilderCreateStaticMemberType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, LLVMMetadataRef Type, LLVMDIFlags Flags, LLVMValueRef ConstantVal, uint32_t AlignInBits)
Create debugging information entry for a C++ static data member.
Parameters
Builder The DIBuilder.
Scope Member scope.
Name Member name.
NameLen Length of member name.
File File where this member is declared.
LineNumber Line number.
Type Type of the static member.
Flags Flags to encode member attribute, e.g. private.
ConstantVal Const initializer of the member.
AlignInBits Member alignment.
Definition at line 1345 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateStructType()
LLVMMetadataRef LLVMDIBuilderCreateStructType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef DerivedFrom, LLVMMetadataRef * Elements, unsigned NumElements, unsigned RunTimeLang, LLVMMetadataRef VTableHolder, const char * UniqueId, size_t UniqueIdLen)
Create debugging information entry for a struct.
Parameters
Builder The DIBuilder.
Scope Scope in which this struct is defined.
Name Struct name.
NameLen Struct name length.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
Flags Flags to encode member attribute, e.g. private
Elements Struct elements.
NumElements Number of struct elements.
RunTimeLang Optional parameter, Objective-C runtime version.
VTableHolder The object containing the vtable for the struct.
UniqueId A unique identifier for the struct.
UniqueIdLen Length of the unique identifier for the struct.
Definition at line 1312 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateSubroutineType()
LLVMMetadataRef LLVMDIBuilderCreateSubroutineType (LLVMDIBuilderRef Builder, LLVMMetadataRef File, LLVMMetadataRef * ParameterTypes, unsigned NumParameterTypes, LLVMDIFlags Flags)
Create subroutine type.
Parameters
Builder The DIBuilder.
File The file in which the subroutine resides.
ParameterTypes An array of subroutine parameter types. This includes return type at 0th index.
NumParameterTypes The number of parameter types in ParameterTypes
Flags E.g.: LLVMDIFlagLValueReference. These flags are used to emit dwarf attributes.
Definition at line 1549 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateTempGlobalVariableFwdDecl()
LLVMMetadataRef LLVMDIBuilderCreateTempGlobalVariableFwdDecl (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, const char * Linkage, size_t LnkLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Ty, LLVMBool LocalToUnit, LLVMMetadataRef Decl, uint32_t AlignInBits)
Create a new descriptor for the specified global variable that is temporary and meant to be RAUWed.
Parameters
Scope Variable scope.
Name Name of the variable.
NameLen The length of the C string passed to Name.
Linkage Mangled name of the variable.
LnkLen The length of the C string passed to Linkage.
File File where this variable is defined.
LineNo Line number.
Ty Variable Type.
LocalToUnit Boolean flag indicate whether this variable is externally visible or not.
Decl Reference to the corresponding declaration.
AlignInBits Variable alignment(or 0 if no alignment attr was specified)
Definition at line 1622 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateTempMacroFile()
LLVMMetadataRef LLVMDIBuilderCreateTempMacroFile (LLVMDIBuilderRef Builder, LLVMMetadataRef ParentMacroFile, unsigned Line, LLVMMetadataRef File)
Create debugging information temporary entry for a macro file.
List of macro node direct children will be calculated by DIBuilder, using the ParentMacroFile relationship.
Parameters
Builder The DIBuilder.
ParentMacroFile Macro parent (could be NULL).
Line Source line number where the macro file is included.
File File descriptor containing the name of the macro file.
Definition at line 1229 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateTypedef()
LLVMMetadataRef LLVMDIBuilderCreateTypedef (LLVMDIBuilderRef Builder, LLVMMetadataRef Type, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNo, LLVMMetadataRef Scope, uint32_t AlignInBits)
Create debugging information entry for a typedef.
Parameters
Builder The DIBuilder.
Type Original type.
Name Typedef name.
File File where this type is defined.
LineNo Line number.
Scope The surrounding context for the typedef.
Definition at line 1392 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateUnionType()
LLVMMetadataRef LLVMDIBuilderCreateUnionType (LLVMDIBuilderRef Builder, LLVMMetadataRef Scope, const char * Name, size_t NameLen, LLVMMetadataRef File, unsigned LineNumber, uint64_t SizeInBits, uint32_t AlignInBits, LLVMDIFlags Flags, LLVMMetadataRef * Elements, unsigned NumElements, unsigned RunTimeLang, const char * UniqueId, size_t UniqueIdLen)
Create debugging information entry for a union.
Parameters
Builder The DIBuilder.
Scope Scope in which this union is defined.
Name Union name.
NameLen Length of union name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
Flags Flags to encode member attribute, e.g. private
Elements Union elements.
NumElements Number of union elements.
RunTimeLang Optional parameter, Objective-C runtime version.
UniqueId A unique identifier for the union.
UniqueIdLen Length of unique identifier.
Definition at line 1256 of file DebugInfo.cpp.
References Builder, map_from_llvmDIFlags(), llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateUnspecifiedType()
LLVMMetadataRef LLVMDIBuilderCreateUnspecifiedType (LLVMDIBuilderRef Builder, const char * Name, size_t NameLen)
Create a DWARF unspecified type.
Parameters
Builder The DIBuilder.
Name The unspecified type's name.
NameLen Length of type name.
Definition at line 1339 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderCreateVectorType()
LLVMMetadataRef LLVMDIBuilderCreateVectorType (LLVMDIBuilderRef Builder, uint64_t Size, uint32_t AlignInBits, LLVMMetadataRef Ty, LLVMMetadataRef * Subscripts, unsigned NumSubscripts)
Create debugging information entry for a vector type.
Parameters
Builder The DIBuilder.
Size Vector size.
AlignInBits Alignment.
Ty Element type.
Subscripts Subscripts.
NumSubscripts Number of subscripts.
Definition at line 1283 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderFinalize()
void LLVMDIBuilderFinalize (LLVMDIBuilderRef Builder)
Construct any deferred debug info descriptors.
Definition at line 1025 of file DebugInfo.cpp.
References Builder, and llvm::unwrap().
LLVMDIBuilderFinalizeSubprogram()
void LLVMDIBuilderFinalizeSubprogram (LLVMDIBuilderRef Builder, LLVMMetadataRef Subprogram)
Finalize a specific subprogram.
No new variables may be added to this subprogram afterwards.
Definition at line 1029 of file DebugInfo.cpp.
References Builder, and llvm::unwrap().
LLVMDIBuilderGetOrCreateArray()
LLVMMetadataRef LLVMDIBuilderGetOrCreateArray (LLVMDIBuilderRef Builder, LLVMMetadataRef * Data, size_t NumElements)
Create an array of DI Nodes.
Parameters
Builder The DIBuilder.
Data The DI Node elements.
NumElements Number of DI Node elements.
Definition at line 1701 of file DebugInfo.cpp.
References Builder, llvm::Data, llvm::get(), llvm::Length, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderGetOrCreateSubrange()
LLVMMetadataRef LLVMDIBuilderGetOrCreateSubrange (LLVMDIBuilderRef Builder, int64_t LowerBound, int64_t Count)
Create a descriptor for a value range.
Parameters
Builder The DIBuilder.
LowerBound Lower bound of the subrange, e.g. 0 for C, 1 for Fortran.
Count Count of elements in the subrange.
Definition at line 1696 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderGetOrCreateTypeArray()
LLVMMetadataRef LLVMDIBuilderGetOrCreateTypeArray (LLVMDIBuilderRef Builder, LLVMMetadataRef * Data, size_t NumElements)
Create a type array.
Parameters
Builder The DIBuilder.
Data The type elements.
NumElements Number of type elements.
Definition at line 1541 of file DebugInfo.cpp.
References Builder, llvm::get(), llvm::Length, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderInsertDbgValueAtEnd()
LLVMValueRef LLVMDIBuilderInsertDbgValueAtEnd (LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block)
Insert a new llvm.dbg.value intrinsic call at the end of the given basic block.
If the basic block has a terminator instruction, the intrinsic is inserted before that terminator instruction.
Parameters
Builder The DIBuilder.
Val The value of the variable.
VarInfo The variable's debug info descriptor.
Expr A complex location expression for the variable.
DebugLoc Debug info location.
Block Basic block acting as a location for the new intrinsic.
Definition at line 1664 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderInsertDbgValueBefore()
LLVMValueRef LLVMDIBuilderInsertDbgValueBefore (LLVMDIBuilderRef Builder, LLVMValueRef Val, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr)
Insert a new llvm.dbg.value intrinsic call before the given instruction.
Parameters
Builder The DIBuilder.
Val The value of the variable.
VarInfo The variable's debug info descriptor.
Expr A complex location expression for the variable.
DebugLoc Debug info location.
Instr Instruction acting as a location for the new intrinsic.
Definition at line 1652 of file DebugInfo.cpp.
References Builder, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderInsertDeclareAtEnd()
LLVMValueRef LLVMDIBuilderInsertDeclareAtEnd (LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMBasicBlockRef Block)
Insert a new llvm.dbg.declare intrinsic call at the end of the given basic block.
If the basic block has a terminator instruction, the intrinsic is inserted before that terminator instruction.
Parameters
Builder The DIBuilder.
Storage The storage of the variable to declare.
VarInfo The variable's debug info descriptor.
Expr A complex location expression for the variable.
DebugLoc Debug info location.
Block Basic block acting as a location for the new intrinsic.
Definition at line 1643 of file DebugInfo.cpp.
References Builder, DL, llvm::unwrap(), and llvm::wrap().
LLVMDIBuilderInsertDeclareBefore()
LLVMValueRef LLVMDIBuilderInsertDeclareBefore (LLVMDIBuilderRef Builder, LLVMValueRef Storage, LLVMMetadataRef VarInfo, LLVMMetadataRef Expr, LLVMMetadataRef DebugLoc, LLVMValueRef Instr)
Insert a new llvm.dbg.declare intrinsic call before the given instruction.
Parameters
Builder The DIBuilder.
Storage The storage of the variable to declare.
VarInfo The variable's debug info descriptor.
Expr A complex location expression for the variable.
DebugLoc Debug info location.
Instr Instruction acting as a location for the new intrinsic.
Definition at line 1634 of file DebugInfo.cpp.
References Builder, DL, llvm::unwrap(), and llvm::wrap().
LLVMDIFileGetDirectory()
const char* LLVMDIFileGetDirectory (LLVMMetadataRef File, unsigned * Len)
Get the directory of a given file.
Parameters
File The file object.
Len The length of the returned string.
See also
DIFile::getDirectory()
Definition at line 1195 of file DebugInfo.cpp.
LLVMDIFileGetFilename()
const char* LLVMDIFileGetFilename (LLVMMetadataRef File, unsigned * Len)
Get the name of a given file.
Parameters
File The file object.
Len The length of the returned string.
See also
DIFile::getFilename()
Definition at line 1201 of file DebugInfo.cpp.
LLVMDIFileGetSource()
const char* LLVMDIFileGetSource (LLVMMetadataRef File, unsigned * Len)
Get the source of a given file.
Parameters
File The file object.
Len The length of the returned string.
See also
DIFile::getSource()
Definition at line 1207 of file DebugInfo.cpp.
LLVMDIGlobalVariableExpressionGetExpression()
LLVMMetadataRef LLVMDIGlobalVariableExpressionGetExpression (LLVMMetadataRef GVE)
Retrieves the DIExpression associated with this global variable expression.
Parameters
GVE The global variable expression.
See also
llvm::DIGlobalVariableExpression::getExpression()
Definition at line 1588 of file DebugInfo.cpp.
References llvm::wrap().
LLVMDIGlobalVariableExpressionGetVariable()
LLVMMetadataRef LLVMDIGlobalVariableExpressionGetVariable (LLVMMetadataRef GVE)
Retrieves the DIVariable associated with this global variable expression.
Parameters
GVE The global variable expression.
See also
llvm::DIGlobalVariableExpression::getVariable()
Definition at line 1584 of file DebugInfo.cpp.
References llvm::wrap().
LLVMDILocationGetColumn()
unsigned LLVMDILocationGetColumn (LLVMMetadataRef Location)
Get the column number of this debug location.
Parameters
Location The debug location.
See also
DILocation::getColumn()
Definition at line 1179 of file DebugInfo.cpp.
LLVMDILocationGetInlinedAt()
LLVMMetadataRef LLVMDILocationGetInlinedAt (LLVMMetadataRef Location)
Get the "inline at" location associated with this debug location.
Parameters
Location The debug location.
See also
DILocation::getInlinedAt()
Definition at line 1187 of file DebugInfo.cpp.
References llvm::wrap().
LLVMDILocationGetLine()
unsigned LLVMDILocationGetLine (LLVMMetadataRef Location)
Get the line number of this debug location.
Parameters
Location The debug location.
See also
DILocation::getLine()
Definition at line 1175 of file DebugInfo.cpp.
LLVMDILocationGetScope()
LLVMMetadataRef LLVMDILocationGetScope (LLVMMetadataRef Location)
Get the local scope associated with this debug location.
Parameters
Location The debug location.
See also
DILocation::getScope()
Definition at line 1183 of file DebugInfo.cpp.
References getScope(), and llvm::wrap().
LLVMDIScopeGetFile()
LLVMMetadataRef LLVMDIScopeGetFile (LLVMMetadataRef Scope)
Get the metadata of the file associated with a given scope.
Parameters
Scope The scope object.
See also
DIScope::getFile()
Definition at line 1191 of file DebugInfo.cpp.
References llvm::wrap().
LLVMDisposeDIBuilder()
void LLVMDisposeDIBuilder (LLVMDIBuilderRef Builder)
Deallocates the DIBuilder and everything it owns.
Note
You must call LLVMDIBuilderFinalize before this
Definition at line 1021 of file DebugInfo.cpp.
References Builder, and llvm::unwrap().
LLVMDisposeTemporaryMDNode()
void LLVMDisposeTemporaryMDNode (LLVMMetadataRef TempNode)
Deallocate a temporary node.
Calls replaceAllUsesWith(nullptr) before deleting, so any remaining references will be reset.
Parameters
TempNode The temporary metadata node.
Definition at line 1611 of file DebugInfo.cpp.
References llvm::MDNode::deleteTemporary().
LLVMDISubprogramGetLine()
unsigned LLVMDISubprogramGetLine (LLVMMetadataRef Subprogram)
Get the line associated with a given subprogram.
Parameters
Subprogram The subprogram object.
See also
DISubprogram::getLine()
Definition at line 1716 of file DebugInfo.cpp.
LLVMDITypeGetAlignInBits()
uint32_t LLVMDITypeGetAlignInBits (LLVMMetadataRef DType)
Get the alignment of this DIType in bits.
Parameters
DType The DIType.
See also
DIType::getAlignInBits()
Definition at line 1529 of file DebugInfo.cpp.
LLVMDITypeGetFlags()
LLVMDIFlags LLVMDITypeGetFlags (LLVMMetadataRef DType)
Get the flags associated with this DIType.
Parameters
DType The DIType.
See also
DIType::getFlags()
Definition at line 1537 of file DebugInfo.cpp.
References getFlags(), and map_to_llvmDIFlags().
LLVMDITypeGetLine()
unsigned LLVMDITypeGetLine (LLVMMetadataRef DType)
Get the source line where this DIType is declared.
Parameters
DType The DIType.
See also
DIType::getLine()
Definition at line 1533 of file DebugInfo.cpp.
LLVMDITypeGetName()
const char* LLVMDITypeGetName (LLVMMetadataRef DType, size_t * Length)
Get the name of this DIType.
Parameters
DType The DIType.
Length The length of the returned string.
See also
DIType::getName()
Definition at line 1515 of file DebugInfo.cpp.
References llvm::Length.
LLVMDITypeGetOffsetInBits()
uint64_t LLVMDITypeGetOffsetInBits (LLVMMetadataRef DType)
Get the offset of this DIType in bits.
Parameters
DType The DIType.
See also
DIType::getOffsetInBits()
Definition at line 1525 of file DebugInfo.cpp.
LLVMDITypeGetSizeInBits()
uint64_t LLVMDITypeGetSizeInBits (LLVMMetadataRef DType)
Get the size of this DIType in bits.
Parameters
DType The DIType.
See also
DIType::getSizeInBits()
Definition at line 1521 of file DebugInfo.cpp.
LLVMDIVariableGetFile()
LLVMMetadataRef LLVMDIVariableGetFile (LLVMMetadataRef Var)
Get the metadata of the file associated with a given variable.
Parameters
Var The variable object.
See also
DIVariable::getFile()
Definition at line 1593 of file DebugInfo.cpp.
References llvm::wrap().
LLVMDIVariableGetLine()
unsigned LLVMDIVariableGetLine (LLVMMetadataRef Var)
Get the source line where this DIVariable is declared.
Parameters
Var The DIVariable.
See also
DIVariable::getLine()
Definition at line 1601 of file DebugInfo.cpp.
LLVMDIVariableGetScope()
LLVMMetadataRef LLVMDIVariableGetScope (LLVMMetadataRef Var)
Get the metadata of the scope associated with a given variable.
Parameters
Var The variable object.
See also
DIVariable::getScope()
Definition at line 1597 of file DebugInfo.cpp.
References getScope(), and llvm::wrap().
LLVMGetDINodeTag()
uint16_t LLVMGetDINodeTag (LLVMMetadataRef MD)
Get the dwarf::Tag of a DINode.
Definition at line 1511 of file DebugInfo.cpp.
LLVMGetMetadataKind()
LLVMMetadataKind LLVMGetMetadataKind (LLVMMetadataRef Metadata)
Obtain the enumerated type of a Metadata instance.
See also
llvm::Metadata::getMetadataID()
Definition at line 1731 of file DebugInfo.cpp.
References LLVMGenericDINodeMetadataKind, and llvm::unwrap().
LLVMGetModuleDebugMetadataVersion()
unsigned LLVMGetModuleDebugMetadataVersion (LLVMModuleRef Module)
The version of debug metadata that's present in the provided Module.
Definition at line 1013 of file DebugInfo.cpp.
References llvm::getDebugMetadataVersionFromModule(), M, and llvm::unwrap().
LLVMGetSubprogram()
LLVMMetadataRef LLVMGetSubprogram (LLVMValueRef Func)
Get the metadata of the subprogram attached to a function.
See also
llvm::Function::getSubprogram()
Definition at line 1708 of file DebugInfo.cpp.
References getSubprogram(), and llvm::wrap().
LLVMInstructionGetDebugLoc()
LLVMMetadataRef LLVMInstructionGetDebugLoc (LLVMValueRef Inst)
Get the debug location for the given instruction.
See also
llvm::Instruction::getDebugLoc()
Definition at line 1720 of file DebugInfo.cpp.
References getDebugLoc(), and llvm::wrap().
LLVMInstructionSetDebugLoc()
void LLVMInstructionSetDebugLoc (LLVMValueRef Inst, LLVMMetadataRef Loc)
Set the debug location for the given instruction.
To clear the location metadata of the given instruction, pass NULL to Loc.
See also
llvm::Instruction::setDebugLoc()
Definition at line 1724 of file DebugInfo.cpp.
LLVMMetadataReplaceAllUsesWith()
void LLVMMetadataReplaceAllUsesWith (LLVMMetadataRef TempTargetMetadata, LLVMMetadataRef Replacement)
Replace all uses of temporary metadata.
Parameters
TempTargetMetadata The temporary metadata node.
Replacement The replacement metadata node.
Definition at line 1615 of file DebugInfo.cpp.
LLVMSetSubprogram()
void LLVMSetSubprogram (LLVMValueRef Func, LLVMMetadataRef SP)
Set the subprogram attached to a function.
See also
llvm::Function::setSubprogram()
Definition at line 1712 of file DebugInfo.cpp.
LLVMStripModuleDebugInfo()
LLVMBool LLVMStripModuleDebugInfo (LLVMModuleRef Module)
Strip debug info in the module if it exists.
To do this, we remove all calls to the debugger intrinsics and any named metadata for debugging. We also remove debug locations for instructions. Return true if module is modified.
Definition at line 1017 of file DebugInfo.cpp.
References M, llvm::StripDebugInfo(), and llvm::unwrap().
LLVMTemporaryMDNode()
LLVMMetadataRef LLVMTemporaryMDNode (LLVMContextRef Ctx, LLVMMetadataRef * Data, size_t NumElements)
Create a new temporary MDNode.
Suitable for use in constructing cyclic MDNode structures. A temporary MDNode is not uniqued, may be RAUW'd, and must be manually deleted with LLVMDisposeTemporaryMDNode.
Parameters
Ctx The context in which to construct the temporary node.
Data The metadata elements.
NumElements Number of metadata elements.
Definition at line 1605 of file DebugInfo.cpp.
References llvm::Data, llvm::MDTuple::getTemporary(), llvm::release, llvm::unwrap(), and llvm::wrap().