LLVM: IR Reader
IR Reader
LLVM-C: C interface to LLVM » Core
Functions
LLVMBool LLVMParseIRInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef *OutM, char **OutMessage)
Read LLVM IR from a memory buffer and convert it into an in-memory Module object.
Detailed Description
Function Documentation
LLVMParseIRInContext()
LLVMBool LLVMParseIRInContext (LLVMContextRef ContextRef, LLVMMemoryBufferRef MemBuf, LLVMModuleRef * OutM, char ** OutMessage)
Read LLVM IR from a memory buffer and convert it into an in-memory Module object.
Returns 0 on success. Optionally returns a human-readable description of any errors that occurred during parsing IR. OutMessage must be disposed with LLVMDisposeMessage.
See also
llvm::ParseIR()
Definition at line 112 of file IRReader.cpp.
References llvm::raw_ostream::flush(), llvm::parseIR(), llvm::SMDiagnostic::print(), llvm::release, llvm::unwrap(), and llvm::wrap().