LLVM: User value
User value
LLVM-C: C interface to LLVM » Core » Values
Function in this group pertain to LLVMValueRef instances that descent from llvm::User. This includes constants, instructions, and operators.
Functions
LLVMValueRef LLVMGetOperand (LLVMValueRef Val, unsigned Index)
Obtain an operand at a specific index in a llvm::User value.
LLVMUseRef LLVMGetOperandUse (LLVMValueRef Val, unsigned Index)
Obtain the use of an operand at a specific index in a llvm::User value.
void LLVMSetOperand (LLVMValueRef User, unsigned Index, LLVMValueRef Val)
Set an operand at a specific index in a llvm::User value.
int LLVMGetNumOperands (LLVMValueRef Val)
Obtain the number of operands in a llvm::User value.
Detailed Description
Function in this group pertain to LLVMValueRef instances that descent from llvm::User. This includes constants, instructions, and operators.
Function Documentation
LLVMGetNumOperands()
int LLVMGetNumOperands (LLVMValueRef Val)
Obtain the number of operands in a llvm::User value.
See also
llvm::User::getNumOperands()
Definition at line 1093 of file Core.cpp.
References LLVMGetMDNodeNumOperands(), and llvm::unwrap().
LLVMGetOperand()
LLVMValueRef LLVMGetOperand (LLVMValueRef Val, unsigned Index)
Obtain an operand at a specific index in a llvm::User value.
See also
llvm::User::getOperand()
Definition at line 1070 of file Core.cpp.
References assert(), llvm::Value::getContext(), getMDNodeOperandImpl(), llvm::unwrap(), and llvm::wrap().
LLVMGetOperandUse()
LLVMUseRef LLVMGetOperandUse (LLVMValueRef Val, unsigned Index)
Obtain the use of an operand at a specific index in a llvm::User value.
See also
llvm::User::getOperandUse()
Definition at line 1084 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMSetOperand()
void LLVMSetOperand (LLVMValueRef User, unsigned Index, LLVMValueRef Val)
Set an operand at a specific index in a llvm::User value.
See also
llvm::User::setOperand()
Definition at line 1089 of file Core.cpp.
References llvm::unwrap().