LLVM: Interprocedural transformations
Interprocedural transformations
LLVM-C: C interface to LLVM » Transforms
Functions
void LLVMAddConstantMergePass (LLVMPassManagerRef PM)
See llvm::createConstantMergePass function.
void LLVMAddDeadArgEliminationPass (LLVMPassManagerRef PM)
See llvm::createDeadArgEliminationPass function.
void LLVMAddFunctionAttrsPass (LLVMPassManagerRef PM)
See llvm::createFunctionAttrsPass function.
void LLVMAddAlwaysInlinerPass (LLVMPassManagerRef PM)
See llvm::createAlwaysInlinerPass function.
void LLVMAddGlobalDCEPass (LLVMPassManagerRef PM)
See llvm::createGlobalDCEPass function.
Detailed Description
Function Documentation
LLVMAddAlwaysInlinerPass()
void LLVMAddAlwaysInlinerPass (LLVMPassManagerRef PM)
See llvm::createAlwaysInlinerPass function.
Definition at line 59 of file IPO.cpp.
References llvm::createAlwaysInlinerLegacyPass(), and llvm::unwrap().
LLVMAddConstantMergePass()
void LLVMAddConstantMergePass (LLVMPassManagerRef PM)
See llvm::createConstantMergePass function.
Definition at line 47 of file IPO.cpp.
References llvm::createConstantMergePass(), and llvm::unwrap().
LLVMAddDeadArgEliminationPass()
void LLVMAddDeadArgEliminationPass (LLVMPassManagerRef PM)
See llvm::createDeadArgEliminationPass function.
Definition at line 51 of file IPO.cpp.
References llvm::createDeadArgEliminationPass(), and llvm::unwrap().
LLVMAddFunctionAttrsPass()
void LLVMAddFunctionAttrsPass (LLVMPassManagerRef PM)
See llvm::createFunctionAttrsPass function.
Definition at line 55 of file IPO.cpp.
References llvm::createPostOrderFunctionAttrsLegacyPass(), and llvm::unwrap().
LLVMAddGlobalDCEPass()
void LLVMAddGlobalDCEPass (LLVMPassManagerRef PM)
See llvm::createGlobalDCEPass function.
Definition at line 63 of file IPO.cpp.
References llvm::createGlobalDCEPass(), and llvm::unwrap().