LLVM: Initialization Routines
Initialization Routines
LLVM-C: C interface to LLVM
Functions
void LLVMInitializeCore (LLVMPassRegistryRef R)
void LLVMInitializeTransformUtils (LLVMPassRegistryRef R)
LLVMInitializeTransformUtils - C binding for initializeTransformUtilsPasses.
void LLVMInitializeScalarOpts (LLVMPassRegistryRef R)
void LLVMInitializeVectorization (LLVMPassRegistryRef R)
void LLVMInitializeInstCombine (LLVMPassRegistryRef R)
void LLVMInitializeIPO (LLVMPassRegistryRef R)
void LLVMInitializeAnalysis (LLVMPassRegistryRef R)
void LLVMInitializeIPA (LLVMPassRegistryRef R)
void LLVMInitializeCodeGen (LLVMPassRegistryRef R)
void LLVMInitializeTarget (LLVMPassRegistryRef R)
Detailed Description
This module contains routines used to initialize the LLVM system.
Function Documentation
LLVMInitializeAnalysis()
void LLVMInitializeAnalysis (LLVMPassRegistryRef R)
Definition at line 88 of file Analysis.cpp.
References llvm::initializeAnalysis(), and llvm::unwrap().
LLVMInitializeCodeGen()
void LLVMInitializeCodeGen (LLVMPassRegistryRef R)
Definition at line 144 of file CodeGen.cpp.
References llvm::initializeCodeGen(), and llvm::unwrap().
LLVMInitializeCore()
void LLVMInitializeCore (LLVMPassRegistryRef R)
Definition at line 56 of file Core.cpp.
References llvm::initializeCore(), and llvm::unwrap().
LLVMInitializeInstCombine()
void LLVMInitializeInstCombine (LLVMPassRegistryRef R)
Definition at line 4755 of file InstructionCombining.cpp.
References llvm::initializeInstructionCombiningPassPass(), and llvm::unwrap().
LLVMInitializeIPA()
void LLVMInitializeIPA (LLVMPassRegistryRef R)
Definition at line 92 of file Analysis.cpp.
References llvm::initializeAnalysis(), and llvm::unwrap().
LLVMInitializeIPO()
void LLVMInitializeIPO (LLVMPassRegistryRef R)
Definition at line 43 of file IPO.cpp.
References llvm::initializeIPO(), and llvm::unwrap().
LLVMInitializeScalarOpts()
void LLVMInitializeScalarOpts (LLVMPassRegistryRef R)
Definition at line 107 of file Scalar.cpp.
References llvm::initializeScalarOpts(), llvm::RISCVFenceField::R, and llvm::unwrap().
LLVMInitializeTarget()
void LLVMInitializeTarget (LLVMPassRegistryRef R)
Definition at line 43 of file Target.cpp.
References llvm::initializeTarget(), llvm::RISCVFenceField::R, and llvm::unwrap().
LLVMInitializeTransformUtils()
void LLVMInitializeTransformUtils (LLVMPassRegistryRef R)
LLVMInitializeTransformUtils - C binding for initializeTransformUtilsPasses.
Definition at line 50 of file Utils.cpp.
References llvm::initializeTransformUtils(), and llvm::unwrap().
LLVMInitializeVectorization()
void LLVMInitializeVectorization (LLVMPassRegistryRef R)
Definition at line 31 of file Vectorize.cpp.
References llvm::initializeVectorization(), and llvm::unwrap().