LLVM: lib/Target/Hexagon/MCTargetDesc/HexagonMCTargetDesc.cpp File Reference
HexagonMCTargetDesc.cpp File Reference
#include "MCTargetDesc/HexagonMCTargetDesc.h"
#include "HexagonDepArch.h"
#include "HexagonTargetStreamer.h"
#include "MCTargetDesc/HexagonInstPrinter.h"
#include "MCTargetDesc/HexagonMCAsmInfo.h"
#include "MCTargetDesc/HexagonMCELFStreamer.h"
#include "MCTargetDesc/HexagonMCInstrInfo.h"
#include "TargetInfo/HexagonTargetInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <mutex>
#include <new>
#include <string>
#include <unordered_map>
#include "HexagonGenInstrInfo.inc"
#include "HexagonGenSubtargetInfo.inc"
#include "HexagonGenRegisterInfo.inc"
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
llvm::HexagonFUnits
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static StringRef HexagonGetArchVariant ()
bool llvm::HexagonFUnits::isSlot0Only (unsigned units)
static MCRegisterInfo * createHexagonMCRegisterInfo (const Triple &TT)
static MCAsmInfo * createHexagonMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstPrinter * createHexagonMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createMCAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *IP, bool IsVerboseAsm)
static MCStreamer * createMCStreamer (Triple const &T, MCContext &Context, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCTargetStreamer * createHexagonObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCTargetStreamer * createHexagonNullTargetStreamer (MCStreamer &S)
static void LLVM_ATTRIBUTE_UNUSED clearFeature (MCSubtargetInfo *STI, uint64_t F)
static bool LLVM_ATTRIBUTE_UNUSED checkFeature (MCSubtargetInfo *STI, uint64_t F)
static bool isCPUValid (StringRef CPU)
static MCInstrAnalysis * createHexagonMCInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeHexagonTargetMC ()
Variables
cl::opt< Hexagon::ArchEnum > EnableHVX ("mhvx", cl::desc("Enable Hexagon Vector eXtensions"), cl::values(clEnumValN(Hexagon::ArchEnum::V60, "v60", "Build for HVX v60"), clEnumValN(Hexagon::ArchEnum::V62, "v62", "Build for HVX v62"), clEnumValN(Hexagon::ArchEnum::V65, "v65", "Build for HVX v65"), clEnumValN(Hexagon::ArchEnum::V66, "v66", "Build for HVX v66"), clEnumValN(Hexagon::ArchEnum::V67, "v67", "Build for HVX v67"), clEnumValN(Hexagon::ArchEnum::V68, "v68", "Build for HVX v68"), clEnumValN(Hexagon::ArchEnum::V69, "v69", "Build for HVX v69"), clEnumValN(Hexagon::ArchEnum::V71, "v71", "Build for HVX v71"), clEnumValN(Hexagon::ArchEnum::V73, "v73", "Build for HVX v73"), clEnumValN(Hexagon::ArchEnum::Generic, "", "")), cl::init(Hexagon::ArchEnum::NoArch), cl::ValueOptional)
static cl::opt< bool > DisableHVX ("mno-hvx", cl::Hidden, cl::desc("Disable Hexagon Vector eXtensions"))
static cl::opt< bool > EnableHvxIeeeFp ("mhvx-ieee-fp", cl::Hidden, cl::desc("Enable HVX IEEE floating point extensions"))
static cl::opt< bool > EnableHexagonCabac ("mcabac", cl::desc("tbd"), cl::init(false))
static StringRef DefaultArch = "hexagonv60"
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 49 of file HexagonMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 48 of file HexagonMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 55 of file HexagonMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 52 of file HexagonMCTargetDesc.cpp.
Function Documentation
checkFeature()
static bool LLVM_ATTRIBUTE_UNUSED checkFeature (MCSubtargetInfo * STI, uint64_t F) static
Definition at line 371 of file HexagonMCTargetDesc.cpp.
References F, and llvm::MCSubtargetInfo::getFeatureBits().
Referenced by llvm::Hexagon_MC::createHexagonMCSubtargetInfo().
clearFeature()
static void LLVM_ATTRIBUTE_UNUSED clearFeature (MCSubtargetInfo * STI, uint64_t F) static
Definition at line 366 of file HexagonMCTargetDesc.cpp.
References F, llvm::MCSubtargetInfo::getFeatureBits(), and llvm::MCSubtargetInfo::ToggleFeature().
createHexagonMCAsmInfo()
static MCAsmInfo* createHexagonMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 317 of file HexagonMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), and MRI.
Referenced by LLVMInitializeHexagonTargetMC().
createHexagonMCInstPrinter()
static MCInstPrinter* createHexagonMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 330 of file HexagonMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeHexagonTargetMC().
createHexagonMCInstrAnalysis()
static MCInstrAnalysis* createHexagonMCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 651 of file HexagonMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeHexagonTargetMC().
createHexagonMCRegisterInfo()
static MCRegisterInfo* createHexagonMCRegisterInfo (const Triple & TT) static
Definition at line 310 of file HexagonMCTargetDesc.cpp.
References X.
createHexagonNullTargetStreamer()
static MCTargetStreamer* createHexagonNullTargetStreamer (MCStreamer & S) static
Definition at line 362 of file HexagonMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeHexagonTargetMC().
createHexagonObjectTargetStreamer()
static MCTargetStreamer* createHexagonObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 358 of file HexagonMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeHexagonTargetMC().
createMCAsmTargetStreamer()
static MCTargetStreamer* createMCAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * IP, bool IsVerboseAsm) static
Definition at line 343 of file HexagonMCTargetDesc.cpp.
References OS, and S.
Referenced by LLVMInitializeHexagonTargetMC().
createMCStreamer()
static MCStreamer* createMCStreamer (Triple const & T, MCContext & Context, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 348 of file HexagonMCTargetDesc.cpp.
References Context, llvm::createHexagonELFStreamer(), Emitter, and move.
Referenced by LLVMInitializeHexagonTargetMC().
HexagonGetArchVariant()
static StringRef HexagonGetArchVariant () static
Definition at line 123 of file HexagonMCTargetDesc.cpp.
Referenced by llvm::Hexagon_MC::selectHexagonCPU().
isCPUValid()
static bool isCPUValid (StringRef CPU) static
Definition at line 440 of file HexagonMCTargetDesc.cpp.
References llvm::Hexagon::getCpu().
Referenced by llvm::Hexagon_MC::createHexagonMCSubtargetInfo().
LLVMInitializeHexagonTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeHexagonTargetMC ()
Definition at line 656 of file HexagonMCTargetDesc.cpp.
References llvm::createHexagonAsmBackend(), createHexagonMCAsmInfo(), llvm::createHexagonMCCodeEmitter(), createHexagonMCInstPrinter(), createHexagonMCInstrAnalysis(), llvm::createHexagonMCInstrInfo(), llvm::createHexagonMCRegisterInfo(), llvm::Hexagon_MC::createHexagonMCSubtargetInfo(), createHexagonNullTargetStreamer(), createHexagonObjectTargetStreamer(), createMCAsmTargetStreamer(), createMCStreamer(), llvm::getTheHexagonTarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), and X.
Variable Documentation
DefaultArch
StringRef DefaultArch = "hexagonv60" static
Definition at line 121 of file HexagonMCTargetDesc.cpp.
Referenced by llvm::Hexagon_MC::selectHexagonCPU().
DisableHVX
cl::opt<bool> DisableHVX("mno-hvx", cl::Hidden, cl::desc("Disable Hexagon Vector eXtensions")) static
EnableHexagonCabac
cl::opt<bool> EnableHexagonCabac("mcabac", cl::desc("tbd"), cl::init(false)) static
EnableHVX
cl::opt<Hexagon::ArchEnum> EnableHVX("mhvx", cl::desc("Enable Hexagon Vector eXtensions"), cl::values(clEnumValN(Hexagon::ArchEnum::V60, "v60", "Build for HVX v60"), clEnumValN(Hexagon::ArchEnum::V62, "v62", "Build for HVX v62"), clEnumValN(Hexagon::ArchEnum::V65, "v65", "Build for HVX v65"), clEnumValN(Hexagon::ArchEnum::V66, "v66", "Build for HVX v66"), clEnumValN(Hexagon::ArchEnum::V67, "v67", "Build for HVX v67"), clEnumValN(Hexagon::ArchEnum::V68, "v68", "Build for HVX v68"), clEnumValN(Hexagon::ArchEnum::V69, "v69", "Build for HVX v69"), clEnumValN(Hexagon::ArchEnum::V71, "v71", "Build for HVX v71"), clEnumValN(Hexagon::ArchEnum::V73, "v73", "Build for HVX v73"), clEnumValN(Hexagon::ArchEnum::Generic, "", "")), cl::init(Hexagon::ArchEnum::NoArch), cl::ValueOptional)
EnableHvxIeeeFp
cl::opt<bool> EnableHvxIeeeFp("mhvx-ieee-fp", cl::Hidden, cl::desc("Enable HVX IEEE floating point extensions")) static