LLVM: lib/DebugInfo/PDB/Native/InputFile.cpp File Reference
InputFile.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/InputFile.h"
#include "llvm/BinaryFormat/Magic.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/CodeView/LazyRandomTypeCollection.h"
#include "llvm/DebugInfo/CodeView/StringsAndChecksums.h"
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
#include "llvm/DebugInfo/PDB/Native/DbiStream.h"
#include "llvm/DebugInfo/PDB/Native/FormatUtil.h"
#include "llvm/DebugInfo/PDB/Native/LinePrinter.h"
#include "llvm/DebugInfo/PDB/Native/NativeSession.h"
#include "llvm/DebugInfo/PDB/Native/PDBFile.h"
#include "llvm/DebugInfo/PDB/Native/PDBStringTable.h"
#include "llvm/DebugInfo/PDB/Native/RawError.h"
#include "llvm/DebugInfo/PDB/Native/TpiStream.h"
#include "llvm/DebugInfo/PDB/PDB.h"
#include "llvm/Object/COFF.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/FormatVariadic.h"
Functions
static bool isCodeViewDebugSubsection (object::SectionRef Section, StringRef Name, BinaryStreamReader &Reader)
static bool isDebugSSection (object::SectionRef Section, DebugSubsectionArray &Subsections)
static bool isDebugTSection (SectionRef Section, CVTypeArray &Types)
static std::string formatChecksumKind (FileChecksumKind Kind)
template<typename... Args>
static void formatInternal (LinePrinter &Printer, bool Append, Args &&...args)
static bool isMyCode (const SymbolGroup &Group)
Function Documentation
formatChecksumKind()
static std::string formatChecksumKind (FileChecksumKind Kind) static
Definition at line 138 of file InputFile.cpp.
References llvm::pdb::formatUnknownEnum(), llvm::None, and RETURN_CASE.
Referenced by llvm::pdb::SymbolGroup::formatFromChecksumsOffset(), and llvm::pdb::SymbolGroup::formatFromFileName().
formatInternal()
template<typename... Args> static void formatInternal (LinePrinter & Printer, bool Append, Args &&... args) static
Definition at line 149 of file InputFile.cpp.
References args, and Printer.
Referenced by llvm::pdb::SymbolGroup::formatFromChecksumsOffset(), and llvm::pdb::SymbolGroup::formatFromFileName().
isCodeViewDebugSubsection()
static bool isCodeViewDebugSubsection (object::SectionRef Section, StringRef Name, BinaryStreamReader & Reader) inline static
Definition at line 92 of file InputFile.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::cantFail(), llvm::consumeError(), llvm::COFF::DEBUG_SECTION_MAGIC, llvm::support::little, llvm::msf::Magic, llvm::BinaryStreamReader::readInteger(), and llvm::Expected< T >::takeError().
Referenced by isDebugSSection(), and isDebugTSection().
isDebugSSection()
static bool isDebugSSection (object::SectionRef Section, DebugSubsectionArray & Subsections) inline static
Definition at line 119 of file InputFile.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::cantFail(), isCodeViewDebugSubsection(), and llvm::BinaryStreamReader::readArray().
Referenced by llvm::pdb::SymbolGroup::SymbolGroup().
isDebugTSection()
static bool isDebugTSection (SectionRef Section, CVTypeArray & Types) static
Definition at line 129 of file InputFile.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), llvm::cantFail(), isCodeViewDebugSubsection(), and llvm::BinaryStreamReader::readArray().
Referenced by llvm::pdb::InputFile::hasTypes().
isMyCode()
static bool isMyCode (const SymbolGroup & Group) static
Definition at line 558 of file InputFile.cpp.
References llvm::pdb::SymbolGroup::getFile(), llvm::pdb::InputFile::isObj(), and llvm::pdb::SymbolGroup::name().
Referenced by llvm::pdb::shouldDumpSymbolGroup().