LLVM: lib/ProfileData/InstrProfReader.cpp File Reference
InstrProfReader.cpp File Reference
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/ProfileData/MemProf.h"
#include "llvm/ProfileData/ProfileCommon.h"
#include "llvm/ProfileData/SymbolRemappingReader.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SwapByteOrder.h"
#include "llvm/Support/VirtualFileSystem.h"
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <memory>
#include <system_error>
#include <utility>
#include <vector>
Classes
class llvm::InstrProfReaderItaniumRemapper< HashTableImpl >
A remapper that applies remappings based on a symbol remapping file.
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define CHECK_LINE_END(Line)
#define READ_NUM(Str, Dst)
#define VP_READ_ADVANCE(Val)
Typedefs
using data_type = InstrProfLookupTrait::data_type
using offset_type = InstrProfLookupTrait::offset_type
Functions
static InstrProfKind getProfileKindFromVersion (uint64_t Version)
static Expected< std::unique_ptr< MemoryBuffer > > setupMemoryBuffer (const Twine &Filename, vfs::FileSystem &FS)
static Error initializeReader (InstrProfReader &Reader)
static Error readBinaryIdsInternal (const MemoryBuffer &DataBuffer, const uint64_t BinaryIdsSize, const uint8_t *BinaryIdsStart, std::vector< llvm::object::BuildID > &BinaryIds, const llvm::support::endianness Endian)
Read a list of binary ids from a profile that consist of a.
static Error printBinaryIdsInternal (raw_ostream &OS, const MemoryBuffer &DataBuffer, uint64_t BinaryIdsSize, const uint8_t *BinaryIdsStart, llvm::support::endianness Endian)
Macro Definition Documentation
CHECK_LINE_END
#define CHECK_LINE_END (Line)
Value:
  if (Line.is_at_end())                                                        \
    return error(instrprof_error::truncated);
READ_NUM
#define READ_NUM (Str, Dst)
Value:
  if ((Str).getAsInteger(10, (Dst)))                                           \
    return error(instrprof_error::malformed);
VP_READ_ADVANCE
#define VP_READ_ADVANCE (Val)
Value:
  CHECK_LINE_END(Line);                                                        \
  uint32_t Val;                                                                \
  READ_NUM((*Line), (Val));                                                    \
  Line++;
Typedef Documentation
data_type
using data_type = InstrProfLookupTrait::data_type
Definition at line 681 of file InstrProfReader.cpp.
offset_type
using offset_type = InstrProfLookupTrait::offset_type
Definition at line 682 of file InstrProfReader.cpp.
Function Documentation
getProfileKindFromVersion()
static InstrProfKind getProfileKindFromVersion (uint64_t Version) static
Definition at line 43 of file InstrProfReader.cpp.
References llvm::ContextSensitive, llvm::FunctionEntryInstrumentation, llvm::FunctionEntryOnly, llvm::IRInstrumentation, llvm::MemProf, llvm::SingleByteCoverage, llvm::Unknown, and llvm::IndexedInstrProf::Version.
Referenced by llvm::RawInstrProfReader< IntPtrT >::getProfileKind(), and llvm::InstrProfReaderIndex< HashTableImpl >::getProfileKind().
initializeReader()
static Error initializeReader (InstrProfReader & Reader) static
Definition at line 75 of file InstrProfReader.cpp.
References llvm::InstrProfReader::readHeader().
Referenced by llvm::InstrProfReader::create(), and llvm::IndexedInstrProfReader::create().
printBinaryIdsInternal()
static Error printBinaryIdsInternal (raw_ostream & OS, const MemoryBuffer & DataBuffer, uint64_t BinaryIdsSize, const uint8_t * BinaryIdsStart, llvm::support::endianness Endian) static
Definition at line 141 of file InstrProfReader.cpp.
References E, Endian, llvm::format(), I, OS, readBinaryIdsInternal(), llvm::Error::success(), and uint64_t.
Referenced by llvm::RawInstrProfReader< IntPtrT >::printBinaryIds(), and llvm::IndexedInstrProfReader::printBinaryIds().
readBinaryIdsInternal()
static Error readBinaryIdsInternal (const MemoryBuffer & DataBuffer, const uint64_t BinaryIdsSize, const uint8_t * BinaryIdsStart, std::vector< llvm::object::BuildID > & BinaryIds, const llvm::support::endianness Endian) static
Read a list of binary ids from a profile that consist of a.
uint64_t binary id length b. uint8_t binary id data c. uint8_t padding (if necessary) This function is shared between raw and indexed profiles. Raw profiles are in host-endian format, and indexed profiles are in little-endian format. So, this function takes an argument indicating the associated endian format to read the binary ids correctly.
Definition at line 88 of file InstrProfReader.cpp.
References llvm::Error::success(), and support().
Referenced by printBinaryIdsInternal(), llvm::RawInstrProfReader< IntPtrT >::readBinaryIds(), and llvm::IndexedInstrProfReader::readBinaryIds().
setupMemoryBuffer()
static Expected<std::unique_ptr<MemoryBuffer> > setupMemoryBuffer (const Twine & Filename, vfs::FileSystem & FS) static
Definition at line 67 of file InstrProfReader.cpp.
References llvm::errorCodeToError(), llvm::X86AS::FS, llvm::MemoryBuffer::getSTDIN(), and move.
Referenced by llvm::InstrProfReader::create(), and llvm::IndexedInstrProfReader::create().