LLVM: lib/IR/Instructions.cpp File Reference
Instructions.cpp File Reference
#include "llvm/IR/Instructions.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/ProfDataUtils.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/ModRef.h"
#include "llvm/Support/TypeSize.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <optional>
#include <vector>
Functions
static bool IsConstantOne (Value *val)
IsConstantOne - Return true only if val is constant int 1.
static Instruction * createMalloc (Instruction *InsertBefore, BasicBlock *InsertAtEnd, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize, ArrayRef< OperandBundleDef > OpB, Function *MallocF, const Twine &Name)
static Instruction * createFree (Value *Source, ArrayRef< OperandBundleDef > Bundles, Instruction *InsertBefore, BasicBlock *InsertAtEnd)
static Value * getAISize (LLVMContext &Context, Value *Amt)
static Align computeAllocaDefaultAlign (Type *Ty, BasicBlock *BB)
static Align computeAllocaDefaultAlign (Type *Ty, Instruction *I)
static Align computeLoadStoreDefaultAlign (Type *Ty, BasicBlock *BB)
static Align computeLoadStoreDefaultAlign (Type *Ty, Instruction *I)
template<typename IndexTy >
static Type * getIndexedTypeInternal (Type *Ty, ArrayRef< IndexTy > IdxList)
static Value * createPlaceholderForShuffleVector (Value *V)
static bool isSingleSourceMaskImpl (ArrayRef< int > Mask, int NumOpElts)
static bool isIdentityMaskImpl (ArrayRef< int > Mask, int NumOpElts)
static bool isReplicationMaskWithParams (ArrayRef< int > Mask, int ReplicationFactor, int VF)
Variables
static cl::opt< bool > DisableI2pP2iOpt ("disable-i2p-p2i-opt", cl::init(false), cl::desc("Disables inttoptr/ptrtoint roundtrip optimization"))
Function Documentation
computeAllocaDefaultAlign() [1/2]
static Align computeAllocaDefaultAlign (Type * Ty, BasicBlock * BB) static
Definition at line 1453 of file Instructions.cpp.
References assert(), BB, and DL.
Referenced by computeAllocaDefaultAlign().
computeAllocaDefaultAlign() [2/2]
static Align computeAllocaDefaultAlign (Type * Ty, Instruction * I) static
Definition at line 1461 of file Instructions.cpp.
References assert(), computeAllocaDefaultAlign(), and I.
computeLoadStoreDefaultAlign() [1/2]
static Align computeLoadStoreDefaultAlign (Type * Ty, BasicBlock * BB) static
Definition at line 1535 of file Instructions.cpp.
References assert(), BB, and DL.
Referenced by computeLoadStoreDefaultAlign().
computeLoadStoreDefaultAlign() [2/2]
static Align computeLoadStoreDefaultAlign (Type * Ty, Instruction * I) static
Definition at line 1543 of file Instructions.cpp.
References assert(), computeLoadStoreDefaultAlign(), and I.
createFree()
static Instruction* createFree (Value * Source, ArrayRef< OperandBundleDef > Bundles, Instruction * InsertBefore, BasicBlock * InsertAtEnd) static
Definition at line 900 of file Instructions.cpp.
References assert(), BB, llvm::CallInst::Create(), F, llvm::FunctionCallee::getCallee(), llvm::Type::getInt8PtrTy(), llvm::Instruction::getParent(), llvm::Type::getVoidTy(), M, and llvm::Sched::Source.
Referenced by llvm::CallInst::CreateFree().
createMalloc()
static Instruction* createMalloc (Instruction * InsertBefore, BasicBlock * InsertAtEnd, Type * IntPtrTy, Type * AllocTy, Value * AllocSize, Value * ArraySize, ArrayRef< OperandBundleDef > OpB, Function * MallocF, const Twine & Name) static
Definition at line 770 of file Instructions.cpp.
References assert(), BB, llvm::CallInst::Create(), llvm::CastInst::CreateIntegerCast(), CreateMul(), llvm::BasicBlock::end(), F, llvm::ConstantInt::get(), llvm::FunctionCallee::getCallee(), llvm::Type::getInt8PtrTy(), llvm::ConstantExpr::getIntegerCast(), llvm::ConstantExpr::getMul(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Instruction::insertInto(), IsConstantOne(), llvm::Type::isVoidTy(), M, llvm::CallBase::setCallingConv(), and llvm::CallInst::setTailCall().
Referenced by llvm::CallInst::CreateMalloc().
createPlaceholderForShuffleVector()
static Value* createPlaceholderForShuffleVector (Value * V) static
Definition at line 2050 of file Instructions.cpp.
References assert(), llvm::PoisonValue::get(), and llvm::Value::getType().
getAISize()
static Value* getAISize (LLVMContext & Context, Value * Amt) static
Definition at line 1441 of file Instructions.cpp.
References assert(), Context, llvm::ConstantInt::get(), llvm::Type::getInt32Ty(), llvm::Value::getType(), and llvm::Type::isIntegerTy().
getIndexedTypeInternal()
template<typename IndexTy > static Type* getIndexedTypeInternal (Type * Ty, ArrayRef< IndexTy > IdxList) static
Definition at line 1889 of file Instructions.cpp.
References llvm::ArrayRef< T >::empty(), llvm::GetElementPtrInst::getTypeAtIndex(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::GetElementPtrInst::getIndexedType().
IsConstantOne()
static bool IsConstantOne (Value * val) static
IsConstantOne - Return true only if val is constant int 1.
Definition at line 764 of file Instructions.cpp.
References assert(), llvm::ConstantInt::isOne(), and val.
Referenced by createMalloc().
isIdentityMaskImpl()
static bool isIdentityMaskImpl (ArrayRef< int > Mask, int NumOpElts) static
Definition at line 2308 of file Instructions.cpp.
References i, isSingleSourceMaskImpl(), and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::ShuffleVectorInst::isConcat(), llvm::ShuffleVectorInst::isIdentityMask(), llvm::ShuffleVectorInst::isIdentityWithExtract(), llvm::ShuffleVectorInst::isIdentityWithPadding(), and llvm::ShuffleVectorInst::isInsertSubvectorMask().
isReplicationMaskWithParams()
static bool isReplicationMaskWithParams (ArrayRef< int > Mask, int ReplicationFactor, int VF) static
Definition at line 2603 of file Instructions.cpp.
References llvm::all_of(), assert(), llvm::BitmaskEnumDetail::Mask(), llvm::seq(), llvm::ArrayRef< T >::size(), and llvm::UndefMaskElem.
Referenced by llvm::ShuffleVectorInst::isReplicationMask().
isSingleSourceMaskImpl()
static bool isSingleSourceMaskImpl (ArrayRef< int > Mask, int NumOpElts) static
Definition at line 2284 of file Instructions.cpp.
References assert(), I, and llvm::BitmaskEnumDetail::Mask().
Referenced by llvm::ShuffleVectorInst::isExtractSubvectorMask(), isIdentityMaskImpl(), llvm::ShuffleVectorInst::isInsertSubvectorMask(), and llvm::ShuffleVectorInst::isSingleSourceMask().
Variable Documentation
DisableI2pP2iOpt
cl::opt<bool> DisableI2pP2iOpt("disable-i2p-p2i-opt", cl::init(false), cl::desc("Disables inttoptr/ptrtoint roundtrip optimization")) static
Referenced by llvm::CastInst::isEliminableCastPair().