LLVM: lib/IR/IRBuilder.cpp File Reference
IRBuilder.cpp File Reference
#include "llvm/IR/IRBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/NoFolder.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include <cassert>
#include <cstdint>
#include <optional>
#include <vector>
#include "llvm/IR/ConstrainedOps.def"
Macros
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
#define INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC)
Functions
static MaybeAlign getAlign (Value *Ptr)
template<typename T0 >
static std::vector< Value * > getStatepointArgs (IRBuilderBase &B, uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs)
template<typename T1 , typename T2 , typename T3 >
static std::vector< OperandBundleDef > getStatepointBundles (std::optional< ArrayRef< T1 >> TransitionArgs, std::optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs)
template<typename T0 , typename T1 , typename T2 , typename T3 >
static CallInst * CreateGCStatepointCallCommon (IRBuilderBase *Builder, uint64_t ID, uint32_t NumPatchBytes, FunctionCallee ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs, std::optional< ArrayRef< T1 >> TransitionArgs, std::optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs, const Twine &Name)
template<typename T0 , typename T1 , typename T2 , typename T3 >
static InvokeInst * CreateGCStatepointInvokeCommon (IRBuilderBase *Builder, uint64_t ID, uint32_t NumPatchBytes, FunctionCallee ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, uint32_t Flags, ArrayRef< T0 > InvokeArgs, std::optional< ArrayRef< T1 >> TransitionArgs, std::optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs, const Twine &Name)
Macro Definition Documentation
INSTRUCTION [1/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:                                \
    HasRoundingMD = ROUND_MODE;                             \
    break;
INSTRUCTION [2/2]
#define INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC)
Value:
  case Intrinsic::INTRINSIC:                                \
    HasRoundingMD = ROUND_MODE;                             \
    break;
Function Documentation
CreateGCStatepointCallCommon()
template<typename T0 , typename T1 , typename T2 , typename T3 > static CallInst* CreateGCStatepointCallCommon (IRBuilderBase * Builder, uint64_t ID, uint32_t NumPatchBytes, FunctionCallee ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs, std::optional< ArrayRef< T1 >> TransitionArgs, std::optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs, const Twine & Name) static
Definition at line 794 of file IRBuilder.cpp.
References llvm::CallBase::addParamAttr(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, llvm::Attribute::get(), llvm::FunctionCallee::getCallee(), llvm::Intrinsic::getDeclaration(), llvm::FunctionCallee::getFunctionType(), getStatepointArgs(), getStatepointBundles(), getType(), and M.
CreateGCStatepointInvokeCommon()
template<typename T0 , typename T1 , typename T2 , typename T3 > static InvokeInst* CreateGCStatepointInvokeCommon (IRBuilderBase * Builder, uint64_t ID, uint32_t NumPatchBytes, FunctionCallee ActualInvokee, BasicBlock * NormalDest, BasicBlock * UnwindDest, uint32_t Flags, ArrayRef< T0 > InvokeArgs, std::optional< ArrayRef< T1 >> TransitionArgs, std::optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs, const Twine & Name) static
Definition at line 848 of file IRBuilder.cpp.
References llvm::CallBase::addParamAttr(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, Builder, llvm::Attribute::get(), llvm::FunctionCallee::getCallee(), llvm::Intrinsic::getDeclaration(), llvm::FunctionCallee::getFunctionType(), getStatepointArgs(), getStatepointBundles(), getType(), and M.
getAlign()
static MaybeAlign getAlign (Value * Ptr) static
Definition at line 529 of file IRBuilder.cpp.
References llvm::RISCVFenceField::O, and Ptr.
getStatepointArgs()
template<typename T0 > static std::vector<Value *> getStatepointArgs (IRBuilderBase & B, uint64_t ID, uint32_t NumPatchBytes, Value * ActualCallee, uint32_t Flags, ArrayRef< T0 > CallArgs) static
Definition at line 752 of file IRBuilder.cpp.
References llvm::append_range(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, B, and llvm::ArrayRef< T >::size().
Referenced by CreateGCStatepointCallCommon(), and CreateGCStatepointInvokeCommon().
getStatepointBundles()
template<typename T1 , typename T2 , typename T3 > static std::vector<OperandBundleDef> getStatepointBundles (std::optional< ArrayRef< T1 >> TransitionArgs, std::optional< ArrayRef< T2 >> DeoptArgs, ArrayRef< T3 > GCArgs) static
Definition at line 771 of file IRBuilder.cpp.
References llvm::append_range(), and llvm::ArrayRef< T >::size().
Referenced by CreateGCStatepointCallCommon(), and CreateGCStatepointInvokeCommon().