LLVM: lib/FuzzMutate/IRMutator.cpp File Reference
IRMutator.cpp File Reference
#include "llvm/FuzzMutate/IRMutator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/FuzzMutate/Operations.h"
#include "llvm/FuzzMutate/Random.h"
#include "llvm/FuzzMutate/RandomIRBuilder.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/FMF.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Transforms/Scalar/DCE.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <optional>
Functions
static void createEmptyFunction (Module &M)
static void eliminateDeadCode (Function &F)
static uint64_t getUniqueCaseValue (SmallSet< uint64_t, 4 > &CasesTaken, uint64_t MaxValue, RandomIRBuilder &IB)
Return a case value that is not already taken to make sure we don't have two cases with same value.
Function Documentation
createEmptyFunction()
static void createEmptyFunction (Module & M) static
Definition at line 34 of file IRMutator.cpp.
References BB, Context, llvm::BasicBlock::Create(), llvm::Function::Create(), llvm::ReturnInst::Create(), llvm::GlobalValue::ExternalLinkage, F, llvm::FunctionType::get(), llvm::Type::getVoidTy(), and M.
Referenced by llvm::IRMutationStrategy::mutate().
eliminateDeadCode()
static void eliminateDeadCode (Function & F) static
Definition at line 80 of file IRMutator.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::registerPass(), and llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run().
Referenced by llvm::InjectorIRStrategy::mutate(), and llvm::InstDeleterIRStrategy::mutate().
getUniqueCaseValue()
static uint64_t getUniqueCaseValue (SmallSet< uint64_t, 4 > & CasesTaken, uint64_t MaxValue, RandomIRBuilder & IB) static
Return a case value that is not already taken to make sure we don't have two cases with same value.
Definition at line 342 of file IRMutator.cpp.
References llvm::SmallSet< T, N, C >::count(), llvm::AArch64PACKey::IB, llvm::SmallSet< T, N, C >::insert(), and uint64_t.
Referenced by llvm::InsertCFGStrategy::mutate().