LLVM: lib/ExecutionEngine/Orc/TargetProcess/JITLoaderGDB.cpp File Reference
JITLoaderGDB.cpp File Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderGDB.h"
#include "llvm/ExecutionEngine/JITSymbol.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/FormatVariadic.h"
#include <cstdint>
#include <mutex>
#include <utility>
Classes
struct jit_code_entry
struct jit_descriptor
Macros
#define DEBUG_TYPE "orc"
Enumerations
enum jit_actions_t {
JIT_NOACTION = 0, JIT_REGISTER_FN, JIT_UNREGISTER_FN, JIT_NOACTION = 0,
JIT_REGISTER_FN, JIT_UNREGISTER_FN
}
Functions
LLVM_ATTRIBUTE_NOINLINE void __jit_debug_register_code ()
static void registerJITLoaderGDBImpl (const char *ObjAddr, size_t Size)
orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char *Data, size_t Size)
orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char *Data, uint64_t Size)
Variables
static constexpr uint32_t JitDescriptorVersion = 1
struct jit_descriptor __jit_debug_descriptor
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "orc"
Definition at line 19 of file JITLoaderGDB.cpp.
Enumeration Type Documentation
jit_actions_t
enum jit_actions_t
Enumerator
JIT_NOACTION
JIT_REGISTER_FN
JIT_UNREGISTER_FN
JIT_NOACTION
JIT_REGISTER_FN
JIT_UNREGISTER_FN
Definition at line 27 of file JITLoaderGDB.cpp.
Function Documentation
__jit_debug_register_code()
LLVM_ATTRIBUTE_NOINLINE void __jit_debug_register_code ()
Definition at line 57 of file JITLoaderGDB.cpp.
Referenced by registerJITLoaderGDBImpl().
llvm_orc_registerJITLoaderGDBAllocAction()
orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char * Data, size_t Size)
Definition at line 104 of file JITLoaderGDB.cpp.
References llvm::Data, handle, llvm::RISCVFenceField::R, registerJITLoaderGDBImpl(), llvm::release, Size, and llvm::Error::success().
llvm_orc_registerJITLoaderGDBWrapper()
orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char * Data, uint64_t Size)
Definition at line 117 of file JITLoaderGDB.cpp.
References llvm::Data, handle, llvm::RISCVFenceField::R, registerJITLoaderGDBImpl(), llvm::release, Size, and llvm::Error::success().
registerJITLoaderGDBImpl()
static void registerJITLoaderGDBImpl (const char * ObjAddr, size_t Size) static
Definition at line 70 of file JITLoaderGDB.cpp.
References __jit_debug_descriptor, __jit_debug_register_code(), jit_descriptor::action_flag, llvm::dbgs(), E, jit_descriptor::first_entry, llvm::formatv(), JIT_REGISTER_FN, LLVM_DEBUG, jit_code_entry::prev_entry, jit_descriptor::relevant_entry, and Size.
Referenced by llvm_orc_registerJITLoaderGDBAllocAction(), and llvm_orc_registerJITLoaderGDBWrapper().
Variable Documentation
__jit_debug_descriptor
struct jit_descriptor __jit_debug_descriptor
Initial value:
= {JitDescriptorVersion, 0,
                                                nullptr, nullptr}
Definition at line 52 of file JITLoaderGDB.cpp.
Referenced by registerJITLoaderGDBImpl().
JitDescriptorVersion
constexpr uint32_t JitDescriptorVersion = 1 static constexpr
Definition at line 22 of file JITLoaderGDB.cpp.