LLVM: lib/Target/Lanai/LanaiTargetMachine.cpp File Reference
LanaiTargetMachine.cpp File Reference
#include "LanaiTargetMachine.h"
#include "Lanai.h"
#include "LanaiMachineFunctionInfo.h"
#include "LanaiTargetObjectFile.h"
#include "LanaiTargetTransformInfo.h"
#include "TargetInfo/LanaiTargetInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Target/TargetOptions.h"
#include <optional>
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
void llvm::initializeLanaiMemAluCombinerPass (PassRegistry &)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiTarget ()
static std::string computeDataLayout ()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
Function Documentation
computeDataLayout()
static std::string computeDataLayout () static
Definition at line 43 of file LanaiTargetMachine.cpp.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 54 of file LanaiTargetMachine.cpp.
References llvm::Reloc::PIC_, and llvm::AArch64::RM.
LLVMInitializeLanaiTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiTarget ()
Definition at line 35 of file LanaiTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheLanaiTarget(), and llvm::initializeLanaiDAGToDAGISelPass().