LLVM: lib/Target/Lanai/MCTargetDesc/LanaiMCTargetDesc.cpp File Reference
LanaiMCTargetDesc.cpp File Reference
#include "LanaiMCTargetDesc.h"
#include "LanaiInstPrinter.h"
#include "LanaiMCAsmInfo.h"
#include "TargetInfo/LanaiTargetInfo.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/TargetParser/Triple.h"
#include <cstdint>
#include <string>
#include "LanaiGenInstrInfo.inc"
#include "LanaiGenSubtargetInfo.inc"
#include "LanaiGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createLanaiMCInstrInfo ()
static MCRegisterInfo * createLanaiMCRegisterInfo (const Triple &)
static MCSubtargetInfo * createLanaiMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCStreamer * createMCStreamer (const Triple &T, MCContext &Context, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCInstPrinter * createLanaiMCInstPrinter (const Triple &, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCRelocationInfo * createLanaiElfRelocation (const Triple &TheTriple, MCContext &Ctx)
static MCInstrAnalysis * createLanaiInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 31 of file LanaiMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 30 of file LanaiMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 37 of file LanaiMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 34 of file LanaiMCTargetDesc.cpp.
Function Documentation
createLanaiElfRelocation()
static MCRelocationInfo* createLanaiElfRelocation (const Triple & TheTriple, MCContext & Ctx) static
Definition at line 85 of file LanaiMCTargetDesc.cpp.
References llvm::createMCRelocationInfo().
Referenced by LLVMInitializeLanaiTargetMC().
createLanaiInstrAnalysis()
static MCInstrAnalysis* createLanaiInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 126 of file LanaiMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeLanaiTargetMC().
createLanaiMCInstPrinter()
static MCInstPrinter* createLanaiMCInstPrinter (const Triple & , unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 75 of file LanaiMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeLanaiTargetMC().
createLanaiMCInstrInfo()
static MCInstrInfo* createLanaiMCInstrInfo () static
Definition at line 42 of file LanaiMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeLanaiTargetMC().
createLanaiMCRegisterInfo()
static MCRegisterInfo* createLanaiMCRegisterInfo (const Triple &) static
Definition at line 48 of file LanaiMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeLanaiTargetMC().
createLanaiMCSubtargetInfo()
static MCSubtargetInfo* createLanaiMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 55 of file LanaiMCTargetDesc.cpp.
References llvm::X86AS::FS.
Referenced by LLVMInitializeLanaiTargetMC().
createMCStreamer()
static MCStreamer* createMCStreamer (const Triple & T, MCContext & Context, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 63 of file LanaiMCTargetDesc.cpp.
References Context, llvm::createELFStreamer(), Emitter, llvm_unreachable, and move.
Referenced by LLVMInitializeLanaiTargetMC().
LLVMInitializeLanaiTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLanaiTargetMC ()
Definition at line 130 of file LanaiMCTargetDesc.cpp.
References llvm::createLanaiAsmBackend(), createLanaiElfRelocation(), createLanaiInstrAnalysis(), llvm::createLanaiMCCodeEmitter(), createLanaiMCInstPrinter(), createLanaiMCInstrInfo(), createLanaiMCRegisterInfo(), createLanaiMCSubtargetInfo(), createMCStreamer(), llvm::getTheLanaiTarget(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCRelocationInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), and X.