LLVM: lib/Analysis/LazyValueInfo.cpp File Reference
LazyValueInfo.cpp File Reference
#include "llvm/Analysis/LazyValueInfo.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueLattice.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/AssemblyAnnotationWriter.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "lazy-value-info"
Typedefs
typedef PointerIntPair< Value *, 1, bool > CondValue
Functions
INITIALIZE_PASS_BEGIN (LazyValueInfoWrapperPass, "lazy-value-info", "Lazy Value Information Analysis", false, true) INITIALIZE_PASS_END(LazyValueInfoWrapperPass
FunctionPass * llvm::createLazyValueInfoPass ()
createLazyValueInfoPass - This creates an instance of the LazyValueInfo pass.
static bool hasSingleValue (const ValueLatticeElement &Val)
Returns true if this lattice value represents at most one possible value.
static ValueLatticeElement intersect (const ValueLatticeElement &A, const ValueLatticeElement &B)
Combine two sets of facts about the same value into a single set of facts.
static ValueLatticeElement getFromRangeMetadata (Instruction *BBI)
static void AddNonNullPointer (Value *Ptr, NonNullPointerSet &PtrSet)
static void AddNonNullPointersByInstruction (Instruction *I, NonNullPointerSet &PtrSet)
static ValueLatticeElement getValueFromCondition (Value *Val, Value *Cond, bool isTrueDest=true)
static ConstantRange getConstantRangeOrFull (const ValueLatticeElement &Val, Type *Ty, const DataLayout &DL)
static bool matchICmpOperand (APInt &Offset, Value *LHS, Value *Val, ICmpInst::Predicate Pred)
static ValueLatticeElement getValueFromSimpleICmpCondition (CmpInst::Predicate Pred, Value *RHS, const APInt &Offset)
Get value range for a "(Val + Offset) Pred RHS" condition.
static ValueLatticeElement getValueFromICmpCondition (Value *Val, ICmpInst *ICI, bool isTrueDest)
static ValueLatticeElement getValueFromOverflowCondition (Value *Val, WithOverflowInst *WO, bool IsTrueDest)
static std::optional< ValueLatticeElement > getValueFromConditionImpl (Value *Val, CondValue CondVal, bool isRevisit, SmallDenseMap< CondValue, ValueLatticeElement > &Visited, SmallVectorImpl< CondValue > &Worklist)
static bool usesOperand (User *Usr, Value *Op)
static bool isOperationFoldable (User *Usr)
static ValueLatticeElement constantFoldUser (User *Usr, Value *Op, const APInt &OpConstVal, const DataLayout &DL)
static std::optional< ValueLatticeElement > getEdgeValueLocal (Value *Val, BasicBlock *BBFrom, BasicBlock *BBTo)
Compute the value of Val on the edge BBFrom -> BBTo.
static LazyValueInfoImpl & getImpl (void *&PImpl, AssumptionCache *AC, const Module *M)
This lazily constructs the LazyValueInfoImpl.
static bool isKnownNonConstant (Value *V)
Returns true if we can statically tell that this value will never be a "useful" constant.
static LazyValueInfo::Tristate getPredicateResult (unsigned Pred, Constant *C, const ValueLatticeElement &Val, const DataLayout &DL, TargetLibraryInfo *TLI)
INITIALIZE_PASS_BEGIN (LazyValueInfoPrinter, "print-lazy-value-info", "Lazy Value Info Printer Pass", false, false) INITIALIZE_PASS_END(LazyValueInfoPrinter
Variables
static const unsigned MaxProcessedPerValue = 500
lazy value info
lazy value Lazy Value Information Analysis
lazy value Lazy Value Information false
print lazy value Lazy Value Info Printer Pass
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lazy-value-info"
Definition at line 44 of file LazyValueInfo.cpp.
Typedef Documentation
CondValue
typedef PointerIntPair<Value *, 1, bool> CondValue
Definition at line 1172 of file LazyValueInfo.cpp.
Function Documentation
AddNonNullPointer()
static void AddNonNullPointer (Value * Ptr, NonNullPointerSet & PtrSet) static
Definition at line 636 of file LazyValueInfo.cpp.
References llvm::getUnderlyingObject(), and Ptr.
Referenced by AddNonNullPointersByInstruction().
AddNonNullPointersByInstruction()
static void AddNonNullPointersByInstruction (Instruction * I, NonNullPointerSet & PtrSet) static
Definition at line 642 of file LazyValueInfo.cpp.
References AddNonNullPointer(), I, MI, and S.
constantFoldUser()
static ValueLatticeElement constantFoldUser (User * Usr, Value * Op, const APInt & OpConstVal, const DataLayout & DL) static
Definition at line 1288 of file LazyValueInfo.cpp.
References assert(), DL, llvm::CastInst::getDestTy(), llvm::Constant::getIntegerValue(), llvm::BinaryOperator::getOpcode(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::ValueLatticeElement::getOverdefined(), llvm::ValueLatticeElement::getRange(), isOperationFoldable(), LHS, RHS, llvm::simplifyBinOp(), and llvm::simplifyCastInst().
Referenced by getEdgeValueLocal().
getConstantRangeOrFull()
static ConstantRange getConstantRangeOrFull (const ValueLatticeElement & Val, Type * Ty, const DataLayout & DL) static
Definition at line 801 of file LazyValueInfo.cpp.
References DL, llvm::ValueLatticeElement::getConstantRange(), and llvm::ValueLatticeElement::isConstantRange().
getEdgeValueLocal()
static std::optional<ValueLatticeElement> getEdgeValueLocal (Value * Val, BasicBlock * BBFrom, BasicBlock * BBTo) static
Compute the value of Val on the edge BBFrom -> BBTo.
Returns false if Val is not constrained on the edge. Result is unspecified if return value is false.
Definition at line 1322 of file LazyValueInfo.cpp.
References llvm::ValueLatticeElement::asConstantInteger(), assert(), llvm::BitWidth, constantFoldUser(), llvm::ConstantRange::difference(), DL, llvm::ConstantInt::get(), llvm::ValueLatticeElement::get(), llvm::ValueLatticeElement::getConstantRange(), llvm::Value::getContext(), llvm::Module::getDataLayout(), llvm::Type::getInt1Ty(), llvm::Type::getIntegerBitWidth(), llvm::BasicBlock::getModule(), llvm::ValueLatticeElement::getRange(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), getValueFromCondition(), i, isOperationFoldable(), llvm::ValueLatticeElement::isOverdefined(), move, SI, llvm::ConstantRange::unionWith(), and usesOperand().
Referenced by llvm::LazyValueInfo::getConstantRangeAtUse().
getFromRangeMetadata()
static ValueLatticeElement getFromRangeMetadata (Instruction * BBI) static
Definition at line 559 of file LazyValueInfo.cpp.
References llvm::MCID::Call, llvm::getConstantRangeFromMetadata(), llvm::Instruction::getMetadata(), llvm::Instruction::getOpcode(), llvm::ValueLatticeElement::getOverdefined(), llvm::ValueLatticeElement::getRange(), llvm::Value::getType(), and llvm::SPII::Load.
getImpl()
static LazyValueInfoImpl& getImpl (void *& PImpl, AssumptionCache * AC, const Module * M) static
This lazily constructs the LazyValueInfoImpl.
Definition at line 1542 of file LazyValueInfo.cpp.
References assert(), DL, llvm::Intrinsic::getName(), and M.
Referenced by llvm::AttributeList::addParamAttribute(), llvm::LazyValueInfo::clear(), llvm::LazyValueInfo::eraseBlock(), llvm::AttributeList::get(), llvm::MDTuple::get(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::LazyValueInfo::getConstantRange(), llvm::LazyValueInfo::getConstantRangeOnEdge(), llvm::DIAssignID::getDistinct(), llvm::MDTuple::getDistinct(), llvm::MDTuple::getIfExists(), llvm::LazyValueInfo::getPredicateAt(), llvm::LazyValueInfo::getPredicateOnEdge(), llvm::DIAssignID::getTemporary(), llvm::MDTuple::getTemporary(), llvm::LazyValueInfo::printLVI(), llvm::LazyValueInfo::releaseMemory(), llvm::LazyValueInfoWrapperPass::runOnFunction(), and llvm::LazyValueInfo::threadEdge().
getPredicateResult()
static LazyValueInfo::Tristate getPredicateResult (unsigned Pred, Constant * C, const ValueLatticeElement & Val, const DataLayout & DL, TargetLibraryInfo * TLI) static
Definition at line 1738 of file LazyValueInfo.cpp.
References llvm::ConstantFoldCompareInstOperands(), llvm::ConstantRange::contains(), DL, llvm::LazyValueInfo::False, llvm::ValueLatticeElement::getConstant(), llvm::ValueLatticeElement::getConstantRange(), llvm::ValueLatticeElement::getNotConstant(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::ConstantRange::inverse(), llvm::ValueLatticeElement::isConstant(), llvm::ValueLatticeElement::isConstantRange(), llvm::ValueLatticeElement::isNotConstant(), llvm::Constant::isNullValue(), llvm::ConstantRange::isSingleElement(), llvm::ConstantRange::makeExactICmpRegion(), llvm::LazyValueInfo::True, and llvm::LazyValueInfo::Unknown.
Referenced by llvm::LazyValueInfo::getPredicateAt(), and llvm::LazyValueInfo::getPredicateOnEdge().
getValueFromCondition()
ValueLatticeElement getValueFromCondition (Value * Val, Value * Cond, bool isTrueDest = true) static
Definition at line 1240 of file LazyValueInfo.cpp.
References assert(), Cond, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::ValueLatticeElement::getOverdefined(), getValueFromConditionImpl(), and llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::try_emplace().
Referenced by llvm::LazyValueInfo::getConstantRangeAtUse(), and getEdgeValueLocal().
getValueFromConditionImpl()
static std::optional<ValueLatticeElement> getValueFromConditionImpl (Value * Val, CondValue CondVal, bool isRevisit, SmallDenseMap< CondValue, ValueLatticeElement > & Visited, SmallVectorImpl< CondValue > & Worklist) static
Definition at line 1174 of file LazyValueInfo.cpp.
References assert(), Cond, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, 4, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::ExtractValueInst::getAggregateOperand(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), llvm::ExtractValueInst::getNumIndices(), llvm::ValueLatticeElement::getOverdefined(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer(), getValueFromICmpCondition(), getValueFromOverflowCondition(), llvm::ExtractValueInst::idx_begin(), intersect(), llvm::ValueLatticeElement::isOverdefined(), llvm::PatternMatch::m_LogicalAnd(), llvm::PatternMatch::m_LogicalOr(), llvm::MIPatternMatch::m_Not(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::ValueLatticeElement::mergeIn(), and N.
Referenced by getValueFromCondition().
getValueFromICmpCondition()
static ValueLatticeElement getValueFromICmpCondition (Value * Val, ICmpInst * ICI, bool isTrueDest) static
Definition at line 1081 of file LazyValueInfo.cpp.
References llvm::BitWidth, llvm::ConstantRange::fromKnownBits(), llvm::ValueLatticeElement::get(), llvm::CmpInst::getInversePredicate(), llvm::ConstantRange::getNonEmpty(), llvm::ValueLatticeElement::getNot(), llvm::APInt::getOneBitSet(), llvm::User::getOperand(), llvm::ValueLatticeElement::getOverdefined(), llvm::CmpInst::getPredicate(), llvm::ValueLatticeElement::getRange(), llvm::Type::getScalarSizeInBits(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::ConstantRange::getUnsignedMin(), getValueFromSimpleICmpCondition(), llvm::APInt::getZero(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::ConstantRange::isEmptySet(), llvm::ICmpInst::isEquality(), llvm::Type::isIntegerTy(), LHS, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::ConstantRange::makeExactICmpRegion(), llvm::BitmaskEnumDetail::Mask(), llvm::PatternMatch::match(), matchICmpOperand(), llvm::Offset, llvm::KnownBits::One, RHS, llvm::KnownBits::Zero, and llvm::APInt::zext().
Referenced by getValueFromConditionImpl().
getValueFromOverflowCondition()
static ValueLatticeElement getValueFromOverflowCondition (Value * Val, WithOverflowInst * WO, bool IsTrueDest) static
Definition at line 1151 of file LazyValueInfo.cpp.
References llvm::BinaryOpIntrinsic::getBinaryOp(), llvm::BinaryOpIntrinsic::getLHS(), llvm::BinaryOpIntrinsic::getNoWrapKind(), llvm::ValueLatticeElement::getOverdefined(), llvm::ValueLatticeElement::getRange(), llvm::BinaryOpIntrinsic::getRHS(), llvm::ConstantRange::inverse(), llvm::PatternMatch::m_APInt(), llvm::ConstantRange::makeExactNoWrapRegion(), and llvm::PatternMatch::match().
Referenced by getValueFromConditionImpl().
getValueFromSimpleICmpCondition()
static ValueLatticeElement getValueFromSimpleICmpCondition (CmpInst::Predicate Pred, Value * RHS, const APInt & Offset) static
Get value range for a "(Val + Offset) Pred RHS" condition.
Definition at line 1066 of file LazyValueInfo.cpp.
References llvm::getConstantRangeFromMetadata(), llvm::Type::getIntegerBitWidth(), llvm::ValueLatticeElement::getRange(), llvm::Value::getType(), I, llvm::ConstantRange::makeAllowedICmpRegion(), llvm::Offset, RHS, and llvm::ConstantRange::subtract().
Referenced by getValueFromICmpCondition().
hasSingleValue()
static bool hasSingleValue (const ValueLatticeElement & Val) static
Returns true if this lattice value represents at most one possible value.
This is as precise as any lattice value can get while still representing reachable code.
Definition at line 70 of file LazyValueInfo.cpp.
References llvm::ValueLatticeElement::getConstantRange(), llvm::ValueLatticeElement::isConstant(), llvm::ValueLatticeElement::isConstantRange(), and llvm::ConstantRange::isSingleElement().
Referenced by intersect().
INITIALIZE_PASS_BEGIN() [1/2]
INITIALIZE_PASS_BEGIN (LazyValueInfoPrinter , "print-lazy-value-info" , "Lazy Value Info Printer Pass" , false , false)
INITIALIZE_PASS_BEGIN() [2/2]
INITIALIZE_PASS_BEGIN (LazyValueInfoWrapperPass , "lazy-value-info" , "Lazy Value Information Analysis" , false , true)
intersect()
static ValueLatticeElement intersect (const ValueLatticeElement & A, const ValueLatticeElement & B) static
Combine two sets of facts about the same value into a single set of facts.
Note that this method is not suitable for merging facts along different paths in a CFG; that's what the mergeIn function is for. This is for merging facts gathered about the same value at the same location through two independent means. Notes:
This method does not promise to return the most precise possible lattice value implied by A and B. It is allowed to return any lattice element which is at least as strong as either A or B (unless our facts conflict, see below).
Due to unreachable code, the intersection of two lattice values could be contradictory. If this happens, we return some valid lattice value so as not confuse the rest of LVI. Ideally, we'd always return Undefined, but we do not make this guarantee. TODO: This would be a useful enhancement.
Definition at line 95 of file LazyValueInfo.cpp.
References B, llvm::ValueLatticeElement::getRange(), hasSingleValue(), and move.
Referenced by getValueFromConditionImpl().
isKnownNonConstant()
static bool isKnownNonConstant (Value * V) static
Returns true if we can statically tell that this value will never be a "useful" constant.
In practice, this means we've got something like an alloca or a malloc call for which a comparison against a constant can only be guarding dead code. Note that we are potentially giving up some precision in dead code (a constant result) in favour of avoiding a expensive search for a easily answered common query.
Definition at line 1610 of file LazyValueInfo.cpp.
References llvm::Value::stripPointerCasts().
Referenced by llvm::LazyValueInfo::getConstant().
isOperationFoldable()
static bool isOperationFoldable (User * Usr) static
Definition at line 1280 of file LazyValueInfo.cpp.
Referenced by constantFoldUser(), and getEdgeValueLocal().
matchICmpOperand()
static bool matchICmpOperand (APInt & Offset, Value * LHS, Value * Val, ICmpInst::Predicate Pred) static
Definition at line 1032 of file LazyValueInfo.cpp.
References llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, LHS, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_c_And(), llvm::PatternMatch::m_c_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), and llvm::Offset.
Referenced by getValueFromICmpCondition().
usesOperand()
static bool usesOperand (User * Usr, Value * Op) static
Definition at line 1272 of file LazyValueInfo.cpp.
References llvm::is_contained(), and llvm::User::operands().
Referenced by getEdgeValueLocal().
Variable Documentation
Analysis
lazy value Lazy Value Information Analysis
Definition at line 59 of file LazyValueInfo.cpp.
false
print lazy value Lazy Value Info Printer false
Definition at line 59 of file LazyValueInfo.cpp.
info
print lazy value info
Definition at line 58 of file LazyValueInfo.cpp.
Referenced by ARM64EmitRuntimeFunction(), ARM64EmitUnwindInfo(), ARM64EmitUnwindInfoForSegment(), ARM64FindSegmentsInFunction(), ARM64ProcessEpilogs(), ARMEmitRuntimeFunction(), ARMEmitUnwindInfo(), checkARM64PackedEpilog(), checkARMPackedEpilog(), EmitRuntimeFunction(), llvm::Win64EH::UnwindEmitter::EmitUnwindInfo(), llvm::Win64EH::ARMUnwindEmitter::EmitUnwindInfo(), llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo(), EmitUnwindInfo(), findLiveReferences(), FindMatchingEpilog(), llvm::CCState::getInRegsParamInfo(), llvm::TargetLowering::getMultipleConstraintMatchWeight(), llvm::SparcTargetLowering::getSingleConstraintMatchWeight(), llvm::AVRTargetLowering::getSingleConstraintMatchWeight(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::ARMTargetLowering::getSingleConstraintMatchWeight(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::TargetLowering::getSingleConstraintMatchWeight(), insertParsePoints(), recomputeLiveInValues(), llvm::MachO::swapStruct(), tryARM64PackedUnwind(), and tryARMPackedUnwind().
MaxProcessedPerValue
const unsigned MaxProcessedPerValue = 500 static
Definition at line 48 of file LazyValueInfo.cpp.
Pass
print lazy value Lazy Value Info Printer Pass
Definition at line 2067 of file LazyValueInfo.cpp.
Referenced by analyzeFunction(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::slpvectorizer::BoUpSLP::VLOperands::reorder(), llvm::SanitizerBinaryMetadataPass::run(), llvm::PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runSinglePass(), and llvm::MIRProfileLoader::setFSPass().