LLVM: lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp File Reference
LegalizeFloatTypes.cpp File Reference
#include "LegalizeTypes.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "legalize-types"
Functions
static RTLIB::Libcall GetFPLibCall (EVT VT, RTLIB::Libcall Call_F32, RTLIB::Libcall Call_F64, RTLIB::Libcall Call_F80, RTLIB::Libcall Call_F128, RTLIB::Libcall Call_PPCF128)
GetFPLibCall - Return the right libcall for the given floating point type.
static RTLIB::Libcall findFPToIntLibcall (EVT SrcVT, EVT RetVT, EVT &Promoted, bool Signed)
static ISD::NodeType GetPromotionOpcode (EVT OpVT, EVT RetVT)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "legalize-types"
Definition at line 27 of file LegalizeFloatTypes.cpp.
Function Documentation
findFPToIntLibcall()
static RTLIB::Libcall findFPToIntLibcall (EVT SrcVT, EVT RetVT, EVT & Promoted, bool Signed) static
Definition at line 948 of file LegalizeFloatTypes.cpp.
References llvm::EVT::bitsGE(), llvm::MVT::FIRST_INTEGER_VALUETYPE, llvm::RTLIB::getFPTOSINT(), llvm::RTLIB::getFPTOUINT(), llvm::MVT::LAST_INTEGER_VALUETYPE, and Signed.
GetFPLibCall()
static RTLIB::Libcall GetFPLibCall (EVT VT, RTLIB::Libcall Call_F32, RTLIB::Libcall Call_F64, RTLIB::Libcall Call_F80, RTLIB::Libcall Call_F128, RTLIB::Libcall Call_PPCF128) static
GetFPLibCall - Return the right libcall for the given floating point type.
FIXME: This is a local version of RTLIB::getFPLibCall that should be refactored away (see RTLIB::getPOWI for an example).
Definition at line 32 of file LegalizeFloatTypes.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, and llvm::MVT::ppcf128.
GetPromotionOpcode()
static ISD::NodeType GetPromotionOpcode (EVT OpVT, EVT RetVT) static
Definition at line 2074 of file LegalizeFloatTypes.cpp.
References llvm::MVT::bf16, llvm::ISD::BF16_TO_FP, llvm::MVT::f16, llvm::ISD::FP16_TO_FP, llvm::ISD::FP_TO_BF16, llvm::ISD::FP_TO_FP16, and llvm::report_fatal_error().