LLVM: lib/DebugInfo/PDB/Native/LinePrinter.cpp File Reference
LinePrinter.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/LinePrinter.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/DebugInfo/CodeView/LazyRandomTypeCollection.h"
#include "llvm/DebugInfo/MSF/MSFCommon.h"
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
#include "llvm/DebugInfo/PDB/IPDBLineNumber.h"
#include "llvm/DebugInfo/PDB/Native/InputFile.h"
#include "llvm/DebugInfo/PDB/Native/NativeSession.h"
#include "llvm/DebugInfo/PDB/Native/PDBFile.h"
#include "llvm/DebugInfo/PDB/UDTLayout.h"
#include "llvm/Object/COFF.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatAdapters.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Regex.h"
#include <algorithm>
Functions
static std::vector< Run > computeBlockRuns (uint32_t BlockSize, const msf::MSFStreamLayout &Layout)
static std::pair< Run, uint64_t > findRun (uint64_t Offset, ArrayRef< Run > Runs)
Function Documentation
computeBlockRuns()
static std::vector<Run> computeBlockRuns (uint32_t BlockSize, const msf::MSFStreamLayout & Layout) static
Definition at line 143 of file LinePrinter.cpp.
References assert(), llvm::ArrayRef< T >::back(), llvm::msf::MSFStreamLayout::Blocks, BlockSize, llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), llvm::msf::MSFStreamLayout::Length, llvm::min(), and uint64_t.
Referenced by llvm::pdb::LinePrinter::formatMsfStreamData().
findRun()
static std::pair<Run, uint64_t> findRun (uint64_t Offset, ArrayRef< Run > Runs) static
Definition at line 171 of file LinePrinter.cpp.
References llvm_unreachable.
Referenced by llvm::pdb::LinePrinter::formatMsfStreamData().