LLVM: lib/Target/LoongArch/LoongArchISelLowering.cpp File Reference
LoongArchISelLowering.cpp File Reference
#include "LoongArchISelLowering.h"
#include "LoongArch.h"
#include "LoongArchMachineFunctionInfo.h"
#include "LoongArchRegisterInfo.h"
#include "LoongArchSubtarget.h"
#include "LoongArchTargetMachine.h"
#include "MCTargetDesc/LoongArchBaseInfo.h"
#include "MCTargetDesc/LoongArchMCTargetDesc.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/RuntimeLibcalls.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicsLoongArch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "LoongArchGenAsmMatcher.inc"
Macros
#define DEBUG_TYPE "loongarch-isel-lowering"
#define IOCSRRD_CASE(NAME, NODE)
#define IOCSRWR_CASE(NAME, NODE)
#define ASRT_LE_GT_CASE(NAME)
#define CRC_CASE_EXT_BINARYOP(NAME, NODE)
#define CRC_CASE_EXT_UNARYOP(NAME, NODE)
#define CSR_CASE(ID)
#define IOCSRRD_CASE(NAME, NODE)
#define NODE_NAME_CASE(node)
#define GET_REGISTER_MATCHER
Functions
STATISTIC (NumTailCalls, "Number of tail calls")
static SDValue getTargetNode (GlobalAddressSDNode *N, SDLoc DL, EVT Ty, SelectionDAG &DAG, unsigned Flags)
static SDValue getTargetNode (BlockAddressSDNode *N, SDLoc DL, EVT Ty, SelectionDAG &DAG, unsigned Flags)
static SDValue getTargetNode (ConstantPoolSDNode *N, SDLoc DL, EVT Ty, SelectionDAG &DAG, unsigned Flags)
static SDValue getTargetNode (JumpTableSDNode *N, SDLoc DL, EVT Ty, SelectionDAG &DAG, unsigned Flags)
static SDValue emitIntrinsicWithChainErrorMessage (SDValue Op, StringRef ErrorMsg, SelectionDAG &DAG)
static SDValue emitIntrinsicErrorMessage (SDValue Op, StringRef ErrorMsg, SelectionDAG &DAG)
static LoongArchISD::NodeType getLoongArchWOpcode (unsigned Opcode)
static SDValue customLegalizeToWOp (SDNode *N, SelectionDAG &DAG, int NumOp, unsigned ExtOpc=ISD::ANY_EXTEND)
static SDValue performANDCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const LoongArchSubtarget &Subtarget)
static SDValue performSRLCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const LoongArchSubtarget &Subtarget)
static SDValue performORCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const LoongArchSubtarget &Subtarget)
static SDValue performBITREV_WCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const LoongArchSubtarget &Subtarget)
static MachineBasicBlock * insertDivByZeroTrap (MachineInstr &MI, MachineBasicBlock *MBB)
static bool CC_LoongArchAssign2GRLen (unsigned GRLen, CCState &State, CCValAssign VA1, ISD::ArgFlagsTy ArgFlags1, unsigned ValNo2, MVT ValVT2, MVT LocVT2, ISD::ArgFlagsTy ArgFlags2)
static bool CC_LoongArch (const DataLayout &DL, LoongArchABI::ABI ABI, unsigned ValNo, MVT ValVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState &State, bool IsFixed, bool IsRet, Type *OrigTy)
static SDValue convertLocVTToValVT (SelectionDAG &DAG, SDValue Val, const CCValAssign &VA, const SDLoc &DL)
static SDValue unpackFromRegLoc (SelectionDAG &DAG, SDValue Chain, const CCValAssign &VA, const SDLoc &DL, const LoongArchTargetLowering &TLI)
static SDValue unpackFromMemLoc (SelectionDAG &DAG, SDValue Chain, const CCValAssign &VA, const SDLoc &DL)
static SDValue convertValVTToLocVT (SelectionDAG &DAG, SDValue Val, const CCValAssign &VA, const SDLoc &DL)
static bool CC_LoongArch_GHC (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState &State)
static Align getPrefTypeAlign (EVT VT, SelectionDAG &DAG)
static Intrinsic::ID getIntrinsicForMaskedAtomicRMWBinOp (unsigned GRLen, AtomicRMWInst::BinOp BinOp)
Variables
static cl::opt< bool > ZeroDivCheck ("loongarch-check-zero-division", cl::Hidden, cl::desc("Trap on integer division by zero."), cl::init(false))
const MCPhysReg ArgGPRs []
const MCPhysReg ArgFPR32s []
const MCPhysReg ArgFPR64s []
Macro Definition Documentation
ASRT_LE_GT_CASE
#define ASRT_LE_GT_CASE (NAME)
Value:
  case Intrinsic::loongarch_##NAME: {                                          \
    if (!Subtarget.is64Bit()) {                                                \
      DAG.getContext()->emitError(Op->getOperationName(0) +                    \
                                  " requires target: loongarch64");            \
      return Op.getOperand(0);                                                 \
    }                                                                          \
    return Op;                                                                 \
  }
CRC_CASE_EXT_BINARYOP
#define CRC_CASE_EXT_BINARYOP (NAME, NODE)
Value:
  case Intrinsic::loongarch_##NAME: {                                          \
    Results.push_back(DAG.getNode(                                             \
        ISD::TRUNCATE, DL, VT,                                                 \
        DAG.getNode(                                                           \
            LoongArchISD::NODE, DL, MVT::i64,                                  \
            DAG.getNode(ISD::ANY_EXTEND, DL, MVT::i64, Op2),                   \
            DAG.getNode(ISD::ANY_EXTEND, DL, MVT::i64, N->getOperand(3)))));   \
    Results.push_back(N->getOperand(0));                                       \
    break;                                                                     \
  }
CRC_CASE_EXT_UNARYOP
#define CRC_CASE_EXT_UNARYOP (NAME, NODE)
Value:
  case Intrinsic::loongarch_##NAME: {                                          \
    Results.push_back(                                                         \
        DAG.getNode(ISD::TRUNCATE, DL, VT,                                     \
                    DAG.getNode(LoongArchISD::NODE, DL, MVT::i64, Op2,         \
                                DAG.getNode(ISD::ANY_EXTEND, DL, MVT::i64,     \
                                            N->getOperand(3)))));              \
    Results.push_back(N->getOperand(0));                                       \
    break;                                                                     \
  }
CSR_CASE
#define CSR_CASE (ID)
Value:
  case Intrinsic::loongarch_##ID: {                                            \
    if (!Subtarget.is64Bit()) {                                                \
      DAG.getContext()->emitError(Name + " requires target: loongarch64");     \
      Results.push_back(DAG.getUNDEF(VT));                                     \
      Results.push_back(N->getOperand(0));                                     \
    }                                                                          \
    break;                                                                     \
  }
DEBUG_TYPE
#define DEBUG_TYPE "loongarch-isel-lowering"
Definition at line 33 of file LoongArchISelLowering.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 3103 of file LoongArchISelLowering.cpp.
IOCSRRD_CASE [1/2]
#define IOCSRRD_CASE (NAME, NODE)
Value:
  case Intrinsic::loongarch_##NAME: {                                          \
    return DAG.getMergeValues(                                                 \
        {DAG.getNode(LoongArchISD::NODE, DL, GRLenVT, Op0, Op.getOperand(2)),  \
         Op0},                                                                 \
        DL);                                                                   \
  }
IOCSRRD_CASE [2/2]
#define IOCSRRD_CASE (NAME, NODE)
Value:
  case Intrinsic::loongarch_##NAME: {                                          \
    Results.push_back(DAG.getNode(                                             \
        ISD::TRUNCATE, DL, N->getValueType(0),                                 \
        DAG.getNode(LoongArchISD::NODE, DL, MVT::i64, Op0,                     \
                    DAG.getNode(ISD::ANY_EXTEND, DL, MVT::i64, Op2))));        \
    Results.push_back(N->getOperand(0));                                       \
    break;                                                                     \
  }
IOCSRWR_CASE
#define IOCSRWR_CASE (NAME, NODE)
Value:
  case Intrinsic::loongarch_##NAME: {                                          \
    SDValue Op3 = Op.getOperand(3);                                            \
    if (Subtarget.is64Bit())                                                   \
      return DAG.getNode(LoongArchISD::NODE, DL, MVT::Other, Op0,              \
                         DAG.getNode(ISD::ANY_EXTEND, DL, MVT::i64, Op2),      \
                         DAG.getNode(ISD::ANY_EXTEND, DL, MVT::i64, Op3));     \
    else                                                                       \
      return DAG.getNode(LoongArchISD::NODE, DL, MVT::Other, Op0, Op2, Op3);   \
  }
NODE_NAME_CASE
#define NODE_NAME_CASE (node)
Value:
  case LoongArchISD::node:                                                     \
    return "LoongArchISD::" #node;
Function Documentation
CC_LoongArch()
static bool CC_LoongArch (const DataLayout & DL, LoongArchABI::ABI ABI, unsigned ValNo, MVT ValVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState & State, bool IsFixed, bool IsRet, Type * OrigTy) static
Definition at line 1887 of file LoongArchISelLowering.cpp.
References ABI, llvm::LoongArchABI::ABI_ILP32D, llvm::LoongArchABI::ABI_ILP32F, llvm::LoongArchABI::ABI_ILP32S, llvm::LoongArchABI::ABI_LP64D, llvm::LoongArchABI::ABI_LP64F, llvm::LoongArchABI::ABI_LP64S, llvm::CCState::addLoc(), Align, llvm::CCState::AllocateReg(), llvm::CCState::AllocateStack(), ArgFPR32s, ArgFPR64s, ArgGPRs, assert(), llvm::CCValAssign::BCvt, CC_LoongArchAssign2GRLen(), llvm::SmallVectorImpl< T >::clear(), DL, llvm::MVT::f32, llvm::MVT::f64, llvm::CCValAssign::Full, llvm::CCState::getFirstUnallocated(), llvm::CCValAssign::getMem(), llvm::ISD::ArgFlagsTy::getNonZeroOrigAlign(), llvm::CCValAssign::getPending(), llvm::CCState::getPendingArgFlags(), llvm::CCState::getPendingLocs(), llvm::CCValAssign::getReg(), llvm::MVT::i32, llvm::MVT::i64, llvm::CCValAssign::Indirect, llvm::MVT::isFloatingPoint(), llvm::MVT::isScalarInteger(), llvm::ISD::ArgFlagsTy::isSplit(), llvm::ISD::ArgFlagsTy::isSplitEnd(), llvm_unreachable, llvm::report_fatal_error(), and size.
Referenced by llvm::LoongArchTargetLowering::CanLowerReturn(), llvm::LoongArchTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerFormalArguments(), and llvm::LoongArchTargetLowering::LowerReturn().
CC_LoongArch_GHC()
static bool CC_LoongArch_GHC (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState & State) static
Definition at line 2156 of file LoongArchISelLowering.cpp.
References llvm::CCState::addLoc(), llvm::CCState::AllocateReg(), llvm::MVT::f32, llvm::MVT::f64, llvm::CCValAssign::getReg(), llvm::MVT::i32, llvm::MVT::i64, and llvm::report_fatal_error().
Referenced by llvm::LoongArchTargetLowering::LowerCall(), and llvm::LoongArchTargetLowering::LowerFormalArguments().
CC_LoongArchAssign2GRLen()
static bool CC_LoongArchAssign2GRLen (unsigned GRLen, CCState & State, CCValAssign VA1, ISD::ArgFlagsTy ArgFlags1, unsigned ValNo2, MVT ValVT2, MVT LocVT2, ISD::ArgFlagsTy ArgFlags2) static
Definition at line 1851 of file LoongArchISelLowering.cpp.
References llvm::CCState::addLoc(), Align, llvm::CCState::AllocateReg(), llvm::CCState::AllocateStack(), ArgGPRs, llvm::CCValAssign::Full, llvm::CCValAssign::getLocVT(), llvm::CCValAssign::getMem(), llvm::ISD::ArgFlagsTy::getNonZeroOrigAlign(), llvm::CCValAssign::getReg(), llvm::CCValAssign::getValNo(), llvm::CCValAssign::getValVT(), and llvm::max().
Referenced by CC_LoongArch().
convertLocVTToValVT()
static SDValue convertLocVTToValVT (SelectionDAG & DAG, SDValue Val, const CCValAssign & VA, const SDLoc & DL) static
Definition at line 2077 of file LoongArchISelLowering.cpp.
References llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, DL, llvm::MVT::f32, llvm::CCValAssign::Full, llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getNode(), llvm::CCValAssign::getValVT(), llvm::MVT::i64, llvm::CCValAssign::Indirect, llvm_unreachable, and llvm::LoongArchISD::MOVGR2FR_W_LA64.
Referenced by llvm::LoongArchTargetLowering::LowerCall(), and unpackFromRegLoc().
convertValVTToLocVT()
static SDValue convertValVTToLocVT (SelectionDAG & DAG, SDValue Val, const CCValAssign & VA, const SDLoc & DL) static
Definition at line 2137 of file LoongArchISelLowering.cpp.
References llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, DL, llvm::MVT::f32, llvm::CCValAssign::Full, llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getNode(), llvm::CCValAssign::getValVT(), llvm::MVT::i64, llvm_unreachable, and llvm::LoongArchISD::MOVFR2GR_S_LA64.
Referenced by llvm::LoongArchTargetLowering::LowerCall(), and llvm::LoongArchTargetLowering::LowerReturn().
customLegalizeToWOp()
static SDValue customLegalizeToWOp (SDNode * N, SelectionDAG & DAG, int NumOp, unsigned ExtOpc = ISD::ANY_EXTEND) static
Definition at line 996 of file LoongArchISelLowering.cpp.
References DL, getLoongArchWOpcode(), llvm::SelectionDAG::getNode(), llvm::MVT::i64, llvm_unreachable, N, and llvm::ISD::TRUNCATE.
Referenced by llvm::LoongArchTargetLowering::ReplaceNodeResults().
emitIntrinsicErrorMessage()
static SDValue emitIntrinsicErrorMessage (SDValue Op, StringRef ErrorMsg, SelectionDAG & DAG) static
Definition at line 733 of file LoongArchISelLowering.cpp.
References llvm::LLVMContext::emitError(), and llvm::SelectionDAG::getContext().
emitIntrinsicWithChainErrorMessage()
static SDValue emitIntrinsicWithChainErrorMessage (SDValue Op, StringRef ErrorMsg, SelectionDAG & DAG) static
Definition at line 600 of file LoongArchISelLowering.cpp.
References llvm::LLVMContext::emitError(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getMergeValues(), and llvm::SelectionDAG::getUNDEF().
getIntrinsicForMaskedAtomicRMWBinOp()
static Intrinsic::ID getIntrinsicForMaskedAtomicRMWBinOp (unsigned GRLen, AtomicRMWInst::BinOp BinOp) static
Definition at line 2800 of file LoongArchISelLowering.cpp.
References llvm::AtomicRMWInst::Add, llvm_unreachable, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, and llvm::AtomicRMWInst::Xchg.
Referenced by llvm::LoongArchTargetLowering::emitMaskedAtomicRMWIntrinsic().
getLoongArchWOpcode()
static LoongArchISD::NodeType getLoongArchWOpcode (unsigned Opcode) static
Definition at line 970 of file LoongArchISelLowering.cpp.
References llvm::LoongArchISD::CLZ_W, llvm::ISD::CTLZ, llvm::ISD::CTTZ, llvm::LoongArchISD::CTZ_W, llvm_unreachable, llvm::ISD::ROTL, llvm::LoongArchISD::ROTL_W, llvm::ISD::ROTR, llvm::LoongArchISD::ROTR_W, llvm::ISD::SHL, llvm::LoongArchISD::SLL_W, llvm::ISD::SRA, llvm::LoongArchISD::SRA_W, llvm::ISD::SRL, and llvm::LoongArchISD::SRL_W.
Referenced by customLegalizeToWOp().
getPrefTypeAlign()
static Align getPrefTypeAlign (EVT VT, SelectionDAG & DAG) static
Definition at line 2407 of file LoongArchISelLowering.cpp.
References llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::DataLayout::getPrefTypeAlign(), and llvm::EVT::getTypeForEVT().
Referenced by llvm::SelectionDAG::CreateStackTemporary(), and llvm::LoongArchTargetLowering::LowerCall().
getTargetNode() [1/4]
static SDValue getTargetNode (BlockAddressSDNode * N, SDLoc DL, EVT Ty, SelectionDAG & DAG, unsigned Flags) static
Definition at line 448 of file LoongArchISelLowering.cpp.
References llvm::SelectionDAG::getTargetBlockAddress(), and N.
getTargetNode() [2/4]
static SDValue getTargetNode (ConstantPoolSDNode * N, SDLoc DL, EVT Ty, SelectionDAG & DAG, unsigned Flags) static
Definition at line 454 of file LoongArchISelLowering.cpp.
References llvm::SelectionDAG::getTargetConstantPool(), and N.
getTargetNode() [3/4]
static SDValue getTargetNode (GlobalAddressSDNode * N, SDLoc DL, EVT Ty, SelectionDAG & DAG, unsigned Flags) static
Definition at line 443 of file LoongArchISelLowering.cpp.
References DL, llvm::SelectionDAG::getTargetGlobalAddress(), and N.
getTargetNode() [4/4]
static SDValue getTargetNode (JumpTableSDNode * N, SDLoc DL, EVT Ty, SelectionDAG & DAG, unsigned Flags) static
Definition at line 460 of file LoongArchISelLowering.cpp.
References llvm::SelectionDAG::getTargetJumpTable(), and N.
insertDivByZeroTrap()
static MachineBasicBlock* insertDivByZeroTrap (MachineInstr & MI, MachineBasicBlock * MBB) static
Definition at line 1680 of file LoongArchISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::LoongArchISD::BREAK, llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), DL, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getBasicBlock(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::getKillRegState(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::insert(), llvm::MachineOperand::isKill(), MBB, MI, llvm::MachineOperand::setIsKill(), TII, and ZeroDivCheck.
performANDCombine()
static SDValue performANDCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const LoongArchSubtarget & Subtarget) static
Definition at line 1325 of file LoongArchISelLowering.cpp.
References llvm::LoongArchISD::BSTRPICK, DL, llvm::SelectionDAG::getConstant(), llvm::LoongArchSubtarget::getGRLenVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getSizeInBits(), llvm::ConstantSDNode::getZExtValue(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::isShiftedMask_64(), N, llvm::ISD::SRA, llvm::ISD::SRL, and uint64_t.
Referenced by llvm::LoongArchTargetLowering::PerformDAGCombine().
performBITREV_WCombine()
static SDValue performBITREV_WCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const LoongArchSubtarget & Subtarget) static
Definition at line 1648 of file LoongArchISelLowering.cpp.
References llvm::LoongArchISD::BITREV_4B, llvm::SelectionDAG::getNode(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), N, and llvm::LoongArchISD::REVB_2W.
Referenced by llvm::LoongArchTargetLowering::PerformDAGCombine().
performORCombine()
static SDValue performORCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const LoongArchSubtarget & Subtarget) static
Definition at line 1429 of file LoongArchISelLowering.cpp.
References llvm::ISD::AND, llvm::LoongArchISD::BSTRINS, llvm::SelectionDAG::computeKnownBits(), llvm::dbgs(), DL, llvm::SelectionDAG::getConstant(), llvm::LoongArchSubtarget::getGRLenVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ConstantSDNode::getSExtValue(), llvm::EVT::getSizeInBits(), llvm::ConstantSDNode::getZExtValue(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::isShiftedMask_64(), llvm::APInt::isSubsetOf(), LLVM_DEBUG, N, llvm::ISD::SHL, llvm::ISD::SRL, std::swap(), and llvm::KnownBits::Zero.
Referenced by llvm::LoongArchTargetLowering::PerformDAGCombine().
performSRLCombine()
static SDValue performSRLCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const LoongArchSubtarget & Subtarget) static
Definition at line 1388 of file LoongArchISelLowering.cpp.
References llvm::ISD::AND, llvm::LoongArchISD::BSTRPICK, DL, llvm::SelectionDAG::getConstant(), llvm::LoongArchSubtarget::getGRLenVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::ConstantSDNode::getZExtValue(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::isShiftedMask_64(), N, and uint64_t.
Referenced by llvm::LoongArchTargetLowering::PerformDAGCombine().
STATISTIC()
STATISTIC (NumTailCalls , "Number of tail calls")
unpackFromMemLoc()
static SDValue unpackFromMemLoc (SelectionDAG & DAG, SDValue Chain, const CCValAssign & VA, const SDLoc & DL) static
Definition at line 2112 of file LoongArchISelLowering.cpp.
References llvm::CCValAssign::BCvt, llvm::MachineFrameInfo::CreateFixedObject(), DL, llvm::CCValAssign::Full, llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getExtLoad(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MVT::getIntegerVT(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::DataLayout::getPointerSizeInBits(), llvm::EVT::getStoreSize(), llvm::CCValAssign::getValVT(), llvm::CCValAssign::Indirect, llvm_unreachable, and llvm::ISD::NON_EXTLOAD.
Referenced by llvm::LoongArchTargetLowering::LowerFormalArguments().
unpackFromRegLoc()
static SDValue unpackFromRegLoc (SelectionDAG & DAG, SDValue Chain, const CCValAssign & VA, const SDLoc & DL, const LoongArchTargetLowering & TLI) static
Definition at line 2095 of file LoongArchISelLowering.cpp.
References llvm::MachineRegisterInfo::addLiveIn(), convertLocVTToValVT(), llvm::MachineRegisterInfo::createVirtualRegister(), DL, llvm::SelectionDAG::getCopyFromReg(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), and llvm::EVT::getSimpleVT().
Referenced by llvm::LoongArchTargetLowering::LowerFormalArguments().
Variable Documentation
ArgFPR32s
const MCPhysReg ArgFPR32s[]
Initial value:
= {LoongArch::F0, LoongArch::F1, LoongArch::F2,
                               LoongArch::F3, LoongArch::F4, LoongArch::F5,
                               LoongArch::F6, LoongArch::F7}
Definition at line 1841 of file LoongArchISelLowering.cpp.
Referenced by CC_LoongArch().
ArgFPR64s
const MCPhysReg ArgFPR64s[]
Initial value:
= {
    LoongArch::F0_64, LoongArch::F1_64, LoongArch::F2_64, LoongArch::F3_64,
    LoongArch::F4_64, LoongArch::F5_64, LoongArch::F6_64, LoongArch::F7_64}
Definition at line 1845 of file LoongArchISelLowering.cpp.
Referenced by CC_LoongArch().
ArgGPRs
const MCPhysReg ArgGPRs[]
Initial value:
= {LoongArch::R4,  LoongArch::R5, LoongArch::R6,
                             LoongArch::R7,  LoongArch::R8, LoongArch::R9,
                             LoongArch::R10, LoongArch::R11}
Definition at line 1836 of file LoongArchISelLowering.cpp.
Referenced by llvm::CC_CSKY_ABIV2_SOFT_64(), CC_LoongArch(), CC_LoongArchAssign2GRLen(), llvm::LoongArchTargetLowering::LowerFormalArguments(), and llvm::Ret_CSKY_ABIV2_SOFT_64().
ZeroDivCheck
cl::opt<bool> ZeroDivCheck("loongarch-check-zero-division", cl::Hidden, cl::desc("Trap on integer division by zero."), cl::init(false)) static
Referenced by insertDivByZeroTrap().