LLVM: lib/Target/LoongArch/MCTargetDesc/LoongArchMCTargetDesc.cpp File Reference
LoongArchMCTargetDesc.cpp File Reference
#include "LoongArchMCTargetDesc.h"
#include "LoongArchBaseInfo.h"
#include "LoongArchELFStreamer.h"
#include "LoongArchInstPrinter.h"
#include "LoongArchMCAsmInfo.h"
#include "TargetInfo/LoongArchTargetInfo.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "LoongArchGenInstrInfo.inc"
#include "LoongArchGenRegisterInfo.inc"
#include "LoongArchGenSubtargetInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_REGINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Functions
static MCRegisterInfo * createLoongArchMCRegisterInfo (const Triple &TT)
static MCInstrInfo * createLoongArchMCInstrInfo ()
static MCSubtargetInfo * createLoongArchMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCAsmInfo * createLoongArchMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstPrinter * createLoongArchMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createLoongArchObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCInstrAnalysis * createLoongArchInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 32 of file LoongArchMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 31 of file LoongArchMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 35 of file LoongArchMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 38 of file LoongArchMCTargetDesc.cpp.
Function Documentation
createLoongArchInstrAnalysis()
static MCInstrAnalysis* createLoongArchInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 111 of file LoongArchMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeLoongArchTargetMC().
createLoongArchMCAsmInfo()
static MCAsmInfo* createLoongArchMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 62 of file LoongArchMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), and MRI.
Referenced by LLVMInitializeLoongArchTargetMC().
createLoongArchMCInstPrinter()
static MCInstPrinter* createLoongArchMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 75 of file LoongArchMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeLoongArchTargetMC().
createLoongArchMCInstrInfo()
static MCInstrInfo* createLoongArchMCInstrInfo () static
Definition at line 49 of file LoongArchMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeLoongArchTargetMC().
createLoongArchMCRegisterInfo()
static MCRegisterInfo* createLoongArchMCRegisterInfo (const Triple & TT) static
Definition at line 43 of file LoongArchMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeLoongArchTargetMC().
createLoongArchMCSubtargetInfo()
static MCSubtargetInfo* createLoongArchMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 56 of file LoongArchMCTargetDesc.cpp.
References llvm::StringRef::empty(), and llvm::X86AS::FS.
Referenced by LLVMInitializeLoongArchTargetMC().
createLoongArchObjectTargetStreamer()
static MCTargetStreamer* createLoongArchObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 84 of file LoongArchMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getTargetTriple(), llvm::Triple::isOSBinFormatELF(), and S.
Referenced by LLVMInitializeLoongArchTargetMC().
LLVMInitializeLoongArchTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchTargetMC ()
Definition at line 126 of file LoongArchMCTargetDesc.cpp.
References llvm::createLoongArchAsmBackend(), llvm::createLoongArchELFStreamer(), createLoongArchInstrAnalysis(), createLoongArchMCAsmInfo(), llvm::createLoongArchMCCodeEmitter(), createLoongArchMCInstPrinter(), createLoongArchMCInstrInfo(), createLoongArchMCRegisterInfo(), createLoongArchMCSubtargetInfo(), createLoongArchObjectTargetStreamer(), llvm::getTheLoongArch32Target(), llvm::getTheLoongArch64Target(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCAsmInfo(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), and llvm::TargetRegistry::RegisterObjectTargetStreamer().