LLVM: lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp File Reference
LoongArchDisassembler.cpp File Reference
#include "MCTargetDesc/LoongArchBaseInfo.h"
#include "MCTargetDesc/LoongArchMCTargetDesc.h"
#include "TargetInfo/LoongArchTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Endian.h"
#include "LoongArchGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "loongarch-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
Functions
static MCDisassembler * createLoongArchDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchDisassembler ()
static DecodeStatus DecodeGPRRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR32RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR64RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCFRRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFCSRRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned N, int P = 0>
static DecodeStatus decodeUImmOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N, unsigned S = 0>
static DecodeStatus decodeSImmOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loongarch-disassembler"
Definition at line 28 of file LoongArchDisassembler.cpp.
Typedef Documentation
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 30 of file LoongArchDisassembler.cpp.
Function Documentation
createLoongArchDisassembler()
static MCDisassembler* createLoongArchDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 44 of file LoongArchDisassembler.cpp.
Referenced by LLVMInitializeLoongArchDisassembler().
DecodeCFRRegisterClass()
static DecodeStatus DecodeCFRRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 85 of file LoongArchDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFCSRRegisterClass()
static DecodeStatus DecodeFCSRRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 94 of file LoongArchDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR32RegisterClass()
static DecodeStatus DecodeFPR32RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 67 of file LoongArchDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR64RegisterClass()
static DecodeStatus DecodeFPR64RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 76 of file LoongArchDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeGPRRegisterClass()
static DecodeStatus DecodeGPRRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 58 of file LoongArchDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
decodeSImmOperand()
template<unsigned N, unsigned S = 0> static DecodeStatus decodeSImmOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 113 of file LoongArchDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, S, and llvm::MCDisassembler::Success.
decodeUImmOperand()
template<unsigned N, int P = 0> static DecodeStatus decodeUImmOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 104 of file LoongArchDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, P, and llvm::MCDisassembler::Success.
LLVMInitializeLoongArchDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchDisassembler ()
Definition at line 50 of file LoongArchDisassembler.cpp.
References createLoongArchDisassembler(), llvm::getTheLoongArch32Target(), llvm::getTheLoongArch64Target(), and llvm::TargetRegistry::RegisterMCDisassembler().