LLVM: lib/Target/LoongArch/LoongArchTargetMachine.cpp File Reference
LoongArchTargetMachine.cpp File Reference
#include "LoongArchTargetMachine.h"
#include "LoongArch.h"
#include "LoongArchMachineFunctionInfo.h"
#include "MCTargetDesc/LoongArchBaseInfo.h"
#include "TargetInfo/LoongArchTargetInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include <optional>
Macros
#define DEBUG_TYPE "loongarch"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchTarget ()
static std::string computeDataLayout (const Triple &TT)
static Reloc::Model getEffectiveRelocModel (const Triple &TT, std::optional< Reloc::Model > RM)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loongarch"
Definition at line 26 of file LoongArchTargetMachine.cpp.
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & TT) static
Definition at line 37 of file LoongArchTargetMachine.cpp.
References assert().
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (const Triple & TT, std::optional< Reloc::Model > RM) static
Definition at line 44 of file LoongArchTargetMachine.cpp.
References llvm::AArch64::RM, and llvm::Reloc::Static.
LLVMInitializeLoongArchTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeLoongArchTarget ()
Definition at line 28 of file LoongArchTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheLoongArch32Target(), llvm::getTheLoongArch64Target(), llvm::initializeLoongArchDAGToDAGISelPass(), llvm::initializeLoongArchPreRAExpandPseudoPass(), X, and Y.