LLVM: lib/Target/M68k/Disassembler/M68kDisassembler.cpp File Reference
M68kDisassembler.cpp File Reference
#include "M68k.h"
#include "M68kRegisterInfo.h"
#include "M68kSubtarget.h"
#include "MCTargetDesc/M68kMCCodeEmitter.h"
#include "MCTargetDesc/M68kMCTargetDesc.h"
#include "TargetInfo/M68kTargetInfo.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/ErrorHandling.h"
#include "M68kGenDisassemblerTable.inc"
Classes
struct M68kDisassembler
A disassembler class for M68k.
Macros
#define DEBUG_TYPE "m68k-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
Functions
static DecodeStatus DecodeRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDR32RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDR16RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDR8RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAR32RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAR16RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeXR32RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeXR16RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCCRCRegisterClass (MCInst &Inst, APInt &Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeImm32 (MCInst &Inst, uint64_t Imm, uint64_t Address, const void *Decoder)
static MCDisassembler * createM68kDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeM68kDisassembler ()
Variables
static const unsigned RegisterDecode []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "m68k-disassembler"
Definition at line 31 of file M68kDisassembler.cpp.
Typedef Documentation
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 33 of file M68kDisassembler.cpp.
Function Documentation
createM68kDisassembler()
static MCDisassembler* createM68kDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 143 of file M68kDisassembler.cpp.
Referenced by LLVMInitializeM68kDisassembler().
DecodeAR16RegisterClass()
static DecodeStatus DecodeAR16RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 73 of file M68kDisassembler.cpp.
References DecodeRegisterClass().
DecodeAR32RegisterClass()
static DecodeStatus DecodeAR32RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 67 of file M68kDisassembler.cpp.
References DecodeRegisterClass().
DecodeCCRCRegisterClass()
static DecodeStatus DecodeCCRCRegisterClass (MCInst & Inst, APInt & Insn, uint64_t Address, const void * Decoder) static
Definition at line 91 of file M68kDisassembler.cpp.
References llvm_unreachable.
DecodeDR16RegisterClass()
static DecodeStatus DecodeDR16RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 55 of file M68kDisassembler.cpp.
References DecodeRegisterClass().
DecodeDR32RegisterClass()
static DecodeStatus DecodeDR32RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 49 of file M68kDisassembler.cpp.
References DecodeRegisterClass().
DecodeDR8RegisterClass()
static DecodeStatus DecodeDR8RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 61 of file M68kDisassembler.cpp.
References DecodeRegisterClass().
DecodeImm32()
static DecodeStatus DecodeImm32 (MCInst & Inst, uint64_t Imm, uint64_t Address, const void * Decoder) static
Definition at line 97 of file M68kDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and Success.
DecodeRegisterClass()
static DecodeStatus DecodeRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 41 of file M68kDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), Fail, RegisterDecode, and Success.
Referenced by DecodeAR16RegisterClass(), DecodeAR32RegisterClass(), DecodeDR16RegisterClass(), DecodeDR32RegisterClass(), DecodeDR8RegisterClass(), DecodeXR16RegisterClass(), and DecodeXR32RegisterClass().
DecodeXR16RegisterClass()
static DecodeStatus DecodeXR16RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 85 of file M68kDisassembler.cpp.
References DecodeRegisterClass().
DecodeXR32RegisterClass()
static DecodeStatus DecodeXR32RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 79 of file M68kDisassembler.cpp.
References DecodeRegisterClass().
LLVMInitializeM68kDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeM68kDisassembler ()
Definition at line 149 of file M68kDisassembler.cpp.
References createM68kDisassembler(), llvm::getTheM68kTarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
Variable Documentation
RegisterDecode
const unsigned RegisterDecode[] static
Initial value:
= {
    M68k::D0, M68k::D1, M68k::D2, M68k::D3, M68k::D4, M68k::D5,
    M68k::D6, M68k::D7, M68k::A0, M68k::A1, M68k::A2, M68k::A3,
    M68k::A4, M68k::A5, M68k::A6, M68k::SP,
}
Definition at line 35 of file M68kDisassembler.cpp.
Referenced by DecodeRegisterClass().