LLVM: lib/Target/M68k/M68kISelDAGToDAG.cpp File Reference
M68kISelDAGToDAG.cpp File Reference
#include "M68k.h"
#include "M68kMachineFunction.h"
#include "M68kRegisterInfo.h"
#include "M68kTargetMachine.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "M68kGenDAGISel.inc"
Macros
#define DEBUG_TYPE "m68k-isel"
#define PASS_NAME "M68k DAG->DAG Pattern Instruction Selection"
Functions
static bool doesDispFitFI (M68kISelAddressMode &AM)
static bool doesDispFit (M68kISelAddressMode &AM, int64_t Val)
static bool isAddressBase (const SDValue &N)
Detailed Description
This file defines an instruction selector for the M68K target.
Definition in file M68kISelDAGToDAG.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "m68k-isel"
Definition at line 41 of file M68kISelDAGToDAG.cpp.
PASS_NAME
#define PASS_NAME "M68k DAG->DAG Pattern Instruction Selection"
Definition at line 42 of file M68kISelDAGToDAG.cpp.
Function Documentation
doesDispFit()
static bool doesDispFit (M68kISelAddressMode & AM, int64_t Val) static
Definition at line 366 of file M68kISelDAGToDAG.cpp.
References llvm::isIntN().
doesDispFitFI()
static bool doesDispFitFI (M68kISelAddressMode & AM) static
Definition at line 359 of file M68kISelDAGToDAG.cpp.
References llvm::isIntN().
isAddressBase()
static bool isAddressBase (const SDValue & N) static
Definition at line 734 of file M68kISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::any_of(), llvm::M68kISD::GLOBAL_BASE_REG, N, llvm::M68kISD::Wrapper, and llvm::M68kISD::WrapperPC.