LLVM: lib/CodeGen/MachineModuleInfoImpls.cpp File Reference
MachineModuleInfoImpls.cpp File Reference
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/MC/MCSymbol.h"
Typedefs
using PairTy = std::pair< MCSymbol *, MachineModuleInfoImpl::StubValueTy >
Functions
static int SortSymbolPair (const PairTy *LHS, const PairTy *RHS)
Typedef Documentation
PairTy
using PairTy = std::pair<MCSymbol *, MachineModuleInfoImpl::StubValueTy>
Definition at line 30 of file MachineModuleInfoImpls.cpp.
Function Documentation
SortSymbolPair()
static int SortSymbolPair (const PairTy * LHS, const PairTy * RHS) static
Definition at line 31 of file MachineModuleInfoImpls.cpp.
References llvm::StringRef::compare(), llvm::Value::getName(), LHS, and RHS.
Referenced by llvm::MachineModuleInfoImpl::getSortedStubs().