LLVM: lib/ObjCopy/MachO/MachOObjcopy.cpp File Reference
MachOObjcopy.cpp File Reference
#include "llvm/ObjCopy/MachO/MachOObjcopy.h"
#include "Archive.h"
#include "MachOReader.h"
#include "MachOWriter.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ObjCopy/CommonConfig.h"
#include "llvm/ObjCopy/MachO/MachOConfig.h"
#include "llvm/ObjCopy/MultiFormatConfig.h"
#include "llvm/ObjCopy/ObjCopy.h"
#include "llvm/Object/ArchiveWriter.h"
#include "llvm/Object/MachOUniversal.h"
#include "llvm/Object/MachOUniversalWriter.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileOutputBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SmallVectorMemoryBuffer.h"
Typedefs
using SectionPred = std::function< bool(const std::unique_ptr< Section > &Sec)>
using LoadCommandPred = std::function< bool(const LoadCommand &LC)>
Functions
static bool isLoadCommandWithPayloadString (const LoadCommand &LC)
static StringRef getPayloadString (const LoadCommand &LC)
static Error removeSections (const CommonConfig &Config, Object &Obj)
static void markSymbols (const CommonConfig &, Object &Obj)
static void updateAndRemoveSymbols (const CommonConfig &Config, const MachOConfig &MachOConfig, Object &Obj)
template<typename LCType >
static void updateLoadCommandPayloadString (LoadCommand &LC, StringRef S)
static LoadCommand buildRPathLoadCommand (StringRef Path)
static Error processLoadCommands (const MachOConfig &MachOConfig, Object &Obj)
static Error dumpSectionToFile (StringRef SecName, StringRef Filename, Object &Obj)
static Error addSection (const NewSectionInfo &NewSection, Object &Obj)
static Expected< Section & > findSection (StringRef SecName, Object &O)
static Error updateSection (const NewSectionInfo &NewSection, Object &O)
static Error isValidMachOCannonicalName (StringRef Name)
static Error handleArgs (const CommonConfig &Config, const MachOConfig &MachOConfig, Object &Obj)
Typedef Documentation
LoadCommandPred
using LoadCommandPred = std::function<bool(const LoadCommand &LC)>
Definition at line 33 of file MachOObjcopy.cpp.
SectionPred
using SectionPred = std::function<bool(const std::unique_ptr<Section> &Sec)>
Definition at line 32 of file MachOObjcopy.cpp.
Function Documentation
addSection()
static Error addSection (const NewSectionInfo & NewSection, Object & Obj) static
Definition at line 300 of file MachOObjcopy.cpp.
References Addr, llvm::objcopy::macho::Object::addSegment(), llvm::alignTo(), llvm::objcopy::macho::Section::Content, llvm::objcopy::macho::LoadCommand::getSegmentName(), llvm::objcopy::macho::LoadCommand::getSegmentVMAddr(), llvm::objcopy::macho::Object::LoadCommands, llvm::max(), llvm::objcopy::macho::Object::NewSectionsContents, S, llvm::StringSaver::save(), llvm::objcopy::NewSectionInfo::SectionData, llvm::objcopy::NewSectionInfo::SectionName, llvm::objcopy::macho::LoadCommand::Sections, llvm::objcopy::macho::Section::Size, llvm::StringRef::size(), llvm::StringRef::split(), llvm::Error::success(), and uint64_t.
Referenced by handleArgs().
buildRPathLoadCommand()
static LoadCommand buildRPathLoadCommand (StringRef Path) static
Definition at line 137 of file MachOObjcopy.cpp.
References llvm::alignTo(), llvm::MachO::rpath_command::cmd, llvm::MachO::rpath_command::cmdsize, copy, llvm::objcopy::macho::LoadCommand::MachOLoadCommand, llvm::MachO::rpath_command::path, and llvm::objcopy::macho::LoadCommand::Payload.
Referenced by processLoadCommands().
dumpSectionToFile()
static Error dumpSectionToFile (StringRef SecName, StringRef Filename, Object & Obj) static
Definition at line 278 of file MachOObjcopy.cpp.
References llvm::copy(), llvm::FileOutputBuffer::create(), llvm::createStringError(), E, llvm::objcopy::macho::Object::LoadCommands, move, llvm::objcopy::macho::LoadCommand::Sections, llvm::StringRef::str(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by handleArgs().
findSection()
static Expected<Section &> findSection (StringRef SecName, Object & O) static
Definition at line 330 of file MachOObjcopy.cpp.
References assert(), llvm::createStringError(), llvm::find_if(), llvm::invalid_argument, llvm::RISCVFenceField::O, llvm::StringRef::split(), and llvm::StringRef::str().
Referenced by updateSection().
getPayloadString()
static StringRef getPayloadString (const LoadCommand & LC) static
Definition at line 46 of file MachOObjcopy.cpp.
References assert(), isLoadCommandWithPayloadString(), llvm::objcopy::macho::LoadCommand::Payload, and llvm::StringRef::rtrim().
Referenced by processLoadCommands().
handleArgs()
static Error handleArgs (const CommonConfig & Config, const MachOConfig & MachOConfig, Object & Obj) static
Definition at line 392 of file MachOObjcopy.cpp.
References llvm::objcopy::CommonConfig::AddSection, addSection(), llvm::objcopy::CommonConfig::DumpSection, dumpSectionToFile(), E, isValidMachOCannonicalName(), llvm::objcopy::macho::Object::LoadCommands, markSymbols(), processLoadCommands(), removeSections(), llvm::AMDGPU::ElfNote::SectionName, llvm::objcopy::NewSectionInfo::SectionName, llvm::objcopy::macho::LoadCommand::Sections, llvm::objcopy::CommonConfig::StripAll, llvm::Error::success(), updateAndRemoveSymbols(), llvm::objcopy::CommonConfig::UpdateSection, and updateSection().
Referenced by llvm::objcopy::macho::executeObjcopyOnBinary().
isLoadCommandWithPayloadString()
static bool isLoadCommandWithPayloadString (const LoadCommand & LC) static
Definition at line 36 of file MachOObjcopy.cpp.
References llvm::objcopy::macho::LoadCommand::MachOLoadCommand.
Referenced by getPayloadString(), and updateLoadCommandPayloadString().
isValidMachOCannonicalName()
static Error isValidMachOCannonicalName (StringRef Name) static
Definition at line 373 of file MachOObjcopy.cpp.
References llvm::createStringError(), llvm::invalid_argument, and llvm::Error::success().
Referenced by handleArgs().
markSymbols()
static void markSymbols (const CommonConfig & , Object & Obj) static
Definition at line 86 of file MachOObjcopy.cpp.
References llvm::objcopy::macho::Object::IndirectSymTable, llvm::objcopy::macho::IndirectSymbolEntry::Symbol, and llvm::objcopy::macho::IndirectSymbolTable::Symbols.
Referenced by handleArgs().
processLoadCommands()
static Error processLoadCommands (const MachOConfig & MachOConfig, Object & Obj) static
Definition at line 149 of file MachOObjcopy.cpp.
References buildRPathLoadCommand(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::contains(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::count(), llvm::createStringError(), E, llvm::StringRef::empty(), llvm::objcopy::MachOConfig::EmptySegmentsToRemove, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::erase(), getPayloadString(), llvm::objcopy::macho::LoadCommand::getSegmentName(), llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::objcopy::MachOConfig::InstallNamesToUpdate, llvm::invalid_argument, llvm::objcopy::macho::Object::LoadCommands, llvm::objcopy::macho::LoadCommand::MachOLoadCommand, llvm::objcopy::MachOConfig::RemoveAllRpaths, llvm::objcopy::macho::Object::removeLoadCommands(), llvm::objcopy::MachOConfig::RPathsToRemove, llvm::objcopy::MachOConfig::RPathsToUpdate, llvm::objcopy::MachOConfig::RPathToAdd, llvm::objcopy::MachOConfig::RPathToPrepend, llvm::objcopy::macho::LoadCommand::Sections, llvm::objcopy::MachOConfig::SharedLibId, llvm::StringRef::str(), llvm::Error::success(), and llvm::objcopy::macho::Object::updateLoadCommandIndexes().
Referenced by handleArgs().
removeSections()
static Error removeSections (const CommonConfig & Config, Object & Obj) static
Definition at line 55 of file MachOObjcopy.cpp.
References llvm::objcopy::NameMatcher::empty(), llvm::objcopy::NameMatcher::matches(), llvm::objcopy::CommonConfig::OnlySection, llvm::objcopy::macho::Object::removeSections(), llvm::objcopy::CommonConfig::StripAll, llvm::objcopy::CommonConfig::StripDebug, and llvm::objcopy::CommonConfig::ToRemove.
Referenced by handleArgs().
updateAndRemoveSymbols()
static void updateAndRemoveSymbols (const CommonConfig & Config, const MachOConfig & MachOConfig, Object & Obj) static
Definition at line 93 of file MachOObjcopy.cpp.
References llvm::objcopy::All, llvm::objcopy::CommonConfig::DiscardMode, llvm::objcopy::macho::MachHeader::Flags, llvm::objcopy::macho::Object::Header, I, llvm::objcopy::MachOConfig::KeepUndefined, llvm::MachO::MH_DYLDLINK, N, llvm::MachO::N_EXT, llvm::objcopy::macho::SymbolEntry::Name, llvm::MachO::REFERENCED_DYNAMICALLY, llvm::objcopy::macho::SymbolTable::removeSymbols(), llvm::objcopy::CommonConfig::StripAll, llvm::objcopy::MachOConfig::StripSwiftSymbols, llvm::objcopy::macho::Object::SwiftVersion, llvm::objcopy::CommonConfig::SymbolsToRename, and llvm::objcopy::macho::Object::SymTable.
Referenced by handleArgs().
updateLoadCommandPayloadString()
template<typename LCType > static void updateLoadCommandPayloadString (LoadCommand & LC, StringRef S) static
Definition at line 126 of file MachOObjcopy.cpp.
References llvm::alignTo(), assert(), copy, isLoadCommandWithPayloadString(), llvm::objcopy::macho::LoadCommand::MachOLoadCommand, llvm::objcopy::macho::LoadCommand::Payload, and S.
updateSection()
static Error updateSection (const NewSectionInfo & NewSection, Object & O) static
Definition at line 354 of file MachOObjcopy.cpp.
References llvm::objcopy::macho::Section::Content, llvm::createStringError(), findSection(), llvm::invalid_argument, llvm::RISCVFenceField::O, llvm::objcopy::NewSectionInfo::SectionData, llvm::objcopy::NewSectionInfo::SectionName, llvm::objcopy::macho::Section::Size, llvm::StringRef::size(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by handleArgs().