LLVM: lib/CodeGen/MachineLateInstrsCleanup.cpp File Reference
MachineLateInstrsCleanup.cpp File Reference
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "machine-latecleanup"
Functions
STATISTIC (NumRemoved, "Number of redundant instructions removed.")
INITIALIZE_PASS (MachineLateInstrsCleanup, DEBUG_TYPE, "Machine Late Instructions Cleanup Pass", false, false) bool MachineLateInstrsCleanup
static void clearKillsForDef (Register Reg, MachineBasicBlock *MBB, MachineBasicBlock::iterator I, BitVector &VisitedPreds, const TargetRegisterInfo *TRI)
static void removeRedundantDef (MachineInstr *MI, const TargetRegisterInfo *TRI)
static bool isCandidate (const MachineInstr *MI, Register &DefedReg, Register FrameReg)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-latecleanup"
Definition at line 35 of file MachineLateInstrsCleanup.cpp.
Function Documentation
clearKillsForDef()
static void clearKillsForDef (Register Reg, MachineBasicBlock * MBB, MachineBasicBlock::iterator I, BitVector & VisitedPreds, const TargetRegisterInfo * TRI) static
Definition at line 105 of file MachineLateInstrsCleanup.cpp.
References llvm::MachineBasicBlock::addLiveIn(), assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::getNumber(), I, llvm::MachineBasicBlock::isLiveIn(), MBB, llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::predecessors(), llvm::TargetRegisterInfo::regsOverlap(), llvm::BitVector::set(), llvm::BitVector::test(), and TRI.
Referenced by removeRedundantDef().
INITIALIZE_PASS()
INITIALIZE_PASS (MachineLateInstrsCleanup , DEBUG_TYPE , "Machine Late Instructions Cleanup Pass" , false , false)
Definition at line 79 of file MachineLateInstrsCleanup.cpp.
References MBB, TII, and TRI.
isCandidate()
static bool isCandidate (const MachineInstr * MI, Register & DefedReg, Register FrameReg) static
Definition at line 149 of file MachineLateInstrsCleanup.cpp.
References llvm::numbers::e, llvm::MachineOperand::getReg(), i, llvm::MachineOperand::isCImm(), llvm::MachineOperand::isCPI(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isFPImm(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isSymbol(), llvm::Register::isValid(), MI, and llvm::MCRegister::NoRegister.
removeRedundantDef()
static void removeRedundantDef (MachineInstr * MI, const TargetRegisterInfo * TRI) static
Definition at line 135 of file MachineLateInstrsCleanup.cpp.
References clearKillsForDef(), MI, and TRI.
STATISTIC()
STATISTIC (NumRemoved , "Number of redundant instructions removed.")