LLVM: lib/CodeGen/MacroFusion.cpp File Reference
MacroFusion.cpp File Reference
#include "llvm/CodeGen/MacroFusion.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/CodeGen/ScheduleDAGInstrs.h"
#include "llvm/CodeGen/ScheduleDAGMutation.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "machine-scheduler"
Functions
STATISTIC (NumFused, "Number of instr pairs fused")
static bool isHazard (const SDep &Dep)
static SUnit * getPredClusterSU (const SUnit &SU)
Variables
static cl::opt< bool > EnableMacroFusion ("misched-fusion", cl::Hidden, cl::desc("Enable scheduling for macro fusion."), cl::init(true))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Definition at line 25 of file MacroFusion.cpp.
Function Documentation
getPredClusterSU()
static SUnit* getPredClusterSU (const SUnit & SU) static
Definition at line 38 of file MacroFusion.cpp.
References llvm::SUnit::Preds, and SI.
Referenced by llvm::hasLessThanNumFused().
isHazard()
static bool isHazard (const SDep & Dep) static
Definition at line 34 of file MacroFusion.cpp.
References llvm::SDep::Anti, llvm::SDep::getKind(), and llvm::SDep::Output.
Referenced by llvm::fuseInstructionPair().
STATISTIC()
STATISTIC (NumFused , "Number of instr pairs fused")
Variable Documentation
EnableMacroFusion
cl::opt<bool> EnableMacroFusion("misched-fusion", cl::Hidden, cl::desc("Enable scheduling for macro fusion."), cl::init(true)) static
Referenced by llvm::createBranchMacroFusionDAGMutation(), and llvm::createMacroFusionDAGMutation().