LLVM: lib/MC/MCInstPrinter.cpp File Reference
MCInstPrinter.cpp File Reference
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <cinttypes>
#include <cstdint>
Functions
static bool matchAliasCondition (const MCInst &MI, const MCSubtargetInfo *STI, const MCRegisterInfo &MRI, unsigned &OpIdx, const AliasMatchingData &M, const AliasPatternCond &C, bool &OrPredicateResult)
static bool needsLeadingZero (uint64_t Value)
Function Documentation
matchAliasCondition()
static bool matchAliasCondition (const MCInst & MI, const MCSubtargetInfo * STI, const MCRegisterInfo & MRI, unsigned & OpIdx, const AliasMatchingData & M, const AliasPatternCond & C, bool & OrPredicateResult) static
Definition at line 63 of file MCInstPrinter.cpp.
References llvm::TargetRegisterClass::contains(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::AliasPatternCond::K_Custom, llvm::AliasPatternCond::K_EndOrFeatures, llvm::AliasPatternCond::K_Feature, llvm::AliasPatternCond::K_Ignore, llvm::AliasPatternCond::K_Imm, llvm::AliasPatternCond::K_NegFeature, llvm::AliasPatternCond::K_OrFeature, llvm::AliasPatternCond::K_OrNegFeature, llvm::AliasPatternCond::K_Reg, llvm::AliasPatternCond::K_RegClass, llvm::AliasPatternCond::K_TiedReg, llvm_unreachable, M, MI, MRI, and llvm::FeatureBitset::test().
Referenced by llvm::MCInstPrinter::matchAliasPatterns().
needsLeadingZero()
static bool needsLeadingZero (uint64_t Value) static
Definition at line 182 of file MCInstPrinter.cpp.
References uint64_t.
Referenced by llvm::MCInstPrinter::formatHex().