LLVM: lib/MC/MCPseudoProbe.cpp File Reference
MCPseudoProbe.cpp File Reference
#include "llvm/MC/MCPseudoProbe.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFragment.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <limits>
#include <memory>
#include <sstream>
#include <vector>
Macros
#define DEBUG_TYPE "mcpseudoprobe"
Functions
static const MCExpr * buildSymbolDiff (MCObjectStreamer *MCOS, const MCSymbol *A, const MCSymbol *B)
static StringRef getProbeFNameForGUID (const GUIDProbeFunctionMap &GUID2FuncMAP, uint64_t GUID)
Variables
static const char * PseudoProbeTypeStr [3]
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mcpseudoprobe"
Definition at line 29 of file MCPseudoProbe.cpp.
Function Documentation
buildSymbolDiff()
static const MCExpr* buildSymbolDiff (MCObjectStreamer * MCOS, const MCSymbol * A, const MCSymbol * B) static
Definition at line 38 of file MCPseudoProbe.cpp.
References B, Context, llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::create(), llvm::MCStreamer::getContext(), llvm::MCBinaryExpr::Sub, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCPseudoProbe::emit().
getProbeFNameForGUID()
static StringRef getProbeFNameForGUID (const GUIDProbeFunctionMap & GUID2FuncMAP, uint64_t GUID) static
Definition at line 256 of file MCPseudoProbe.cpp.
References assert(), and llvm::StringRef::find().
Referenced by llvm::MCDecodedPseudoProbe::getInlineContext(), and llvm::MCDecodedPseudoProbe::print().
Variable Documentation
PseudoProbeTypeStr
const char* PseudoProbeTypeStr[3] static
Initial value:
= {"Block", "IndirectCall",
                                            "DirectCall"}
Definition at line 299 of file MCPseudoProbe.cpp.
Referenced by llvm::MCDecodedPseudoProbe::print().