LLVM: lib/Transforms/Utils/MemoryOpRemark.cpp File Reference
MemoryOpRemark.cpp File Reference
#include "llvm/Transforms/Utils/MemoryOpRemark.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include <optional>
Functions
static void inlineVolatileOrAtomicWithExtraArgs (bool *Inline, bool Volatile, bool Atomic, DiagnosticInfoIROptimization &R)
static std::optional< uint64_t > getSizeInBytes (std::optional< uint64_t > SizeInBits)
static std::optional< StringRef > nameOrNone (const Value *V)
Function Documentation
getSizeInBytes()
static std::optional<uint64_t> getSizeInBytes (std::optional< uint64_t > SizeInBits) static
Definition at line 149 of file MemoryOpRemark.cpp.
Referenced by getTypePartition().
inlineVolatileOrAtomicWithExtraArgs()
static void inlineVolatileOrAtomicWithExtraArgs (bool * Inline, bool Volatile, bool Atomic, DiagnosticInfoIROptimization & R) static
Definition at line 127 of file MemoryOpRemark.cpp.
nameOrNone()
static std::optional<StringRef> nameOrNone (const Value * V) static
Definition at line 302 of file MemoryOpRemark.cpp.
References llvm::Value::getName(), and llvm::Value::hasName().