LLVM: lib/DebugInfo/CodeView/MergingTypeTableBuilder.cpp File Reference
MergingTypeTableBuilder.cpp File Reference
#include "llvm/DebugInfo/CodeView/MergingTypeTableBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/CodeView/ContinuationRecordBuilder.h"
#include "llvm/DebugInfo/CodeView/TypeHashing.h"
#include "llvm/DebugInfo/CodeView/TypeIndex.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/ErrorHandling.h"
#include <cassert>
#include <cstdint>
#include <cstring>
Functions
static ArrayRef< uint8_t > stabilize (BumpPtrAllocator &Alloc, ArrayRef< uint8_t > Data)
Function Documentation
stabilize()
static ArrayRef<uint8_t> stabilize (BumpPtrAllocator & Alloc, ArrayRef< uint8_t > Data) inline static
Definition at line 77 of file MergingTypeTableBuilder.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::ArrayRef(), llvm::Data, and memcpy().
Referenced by llvm::codeview::MergingTypeTableBuilder::insertRecordAs(), and llvm::codeview::MergingTypeTableBuilder::replaceType().