LLVM: lib/Demangle/MicrosoftDemangleNodes.cpp File Reference
MicrosoftDemangleNodes.cpp File Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
#include "llvm/Demangle/Utility.h"
#include <cctype>
#include <string>
Macros
#define OUTPUT_ENUM_CLASS_VALUE(Enum, Value, Desc)
Functions
static void outputSpaceIfNecessary (OutputBuffer &OB)
static void outputSingleQualifier (OutputBuffer &OB, Qualifiers Q)
static bool outputQualifierIfPresent (OutputBuffer &OB, Qualifiers Q, Qualifiers Mask, bool NeedSpace)
static void outputQualifiers (OutputBuffer &OB, Qualifiers Q, bool SpaceBefore, bool SpaceAfter)
static void outputCallingConvention (OutputBuffer &OB, CallingConv CC)
Macro Definition Documentation
OUTPUT_ENUM_CLASS_VALUE
#define OUTPUT_ENUM_CLASS_VALUE (Enum, Value, Desc)
Value:
  case Enum::Value:                                                            \
    OB << Desc;                                                                \
    break;
Definition at line 21 of file MicrosoftDemangleNodes.cpp.
Function Documentation
outputCallingConvention()
static void outputCallingConvention (OutputBuffer & OB, CallingConv CC) static
Definition at line 78 of file MicrosoftDemangleNodes.cpp.
References CC, llvm::ms_demangle::Cdecl, llvm::ms_demangle::Clrcall, llvm::ms_demangle::Eabi, llvm::ms_demangle::Fastcall, llvm::X86II::OB, outputSpaceIfNecessary(), llvm::ms_demangle::Pascal, llvm::ms_demangle::Regcall, llvm::ms_demangle::Stdcall, llvm::ms_demangle::Swift, llvm::ms_demangle::SwiftAsync, llvm::ms_demangle::Thiscall, and llvm::ms_demangle::Vectorcall.
Referenced by llvm::ms_demangle::FunctionSignatureNode::outputPre(), and llvm::ms_demangle::PointerTypeNode::outputPre().
outputQualifierIfPresent()
static bool outputQualifierIfPresent (OutputBuffer & OB, Qualifiers Q, Qualifiers Mask, bool NeedSpace) static
Definition at line 52 of file MicrosoftDemangleNodes.cpp.
References llvm::BitmaskEnumDetail::Mask(), llvm::X86II::OB, and outputSingleQualifier().
Referenced by outputQualifiers().
outputQualifiers()
static void outputQualifiers (OutputBuffer & OB, Qualifiers Q, bool SpaceBefore, bool SpaceAfter) static
Definition at line 64 of file MicrosoftDemangleNodes.cpp.
References llvm::X86II::OB, outputQualifierIfPresent(), llvm::ms_demangle::Q_Const, llvm::ms_demangle::Q_None, llvm::ms_demangle::Q_Restrict, and llvm::ms_demangle::Q_Volatile.
Referenced by llvm::ms_demangle::SpecialTableSymbolNode::output(), llvm::ms_demangle::PrimitiveTypeNode::outputPre(), llvm::ms_demangle::PointerTypeNode::outputPre(), llvm::ms_demangle::TagTypeNode::outputPre(), and llvm::ms_demangle::ArrayTypeNode::outputPre().
outputSingleQualifier()
static void outputSingleQualifier (OutputBuffer & OB, Qualifiers Q) static
Definition at line 36 of file MicrosoftDemangleNodes.cpp.
References llvm::X86II::OB, llvm::ms_demangle::Q_Const, llvm::ms_demangle::Q_Restrict, and llvm::ms_demangle::Q_Volatile.
Referenced by outputQualifierIfPresent().
outputSpaceIfNecessary()
static void outputSpaceIfNecessary (OutputBuffer & OB) static
Definition at line 27 of file MicrosoftDemangleNodes.cpp.
References llvm::X86II::OB.
Referenced by llvm::ms_demangle::VariableSymbolNode::output(), llvm::ms_demangle::FunctionSymbolNode::output(), outputCallingConvention(), and llvm::ms_demangle::PointerTypeNode::outputPre().