LLVM: lib/Target/Mips/Mips16InstrInfo.cpp File Reference
Mips16InstrInfo.cpp File Reference
#include "Mips16InstrInfo.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iterator>
#include <vector>
Macros
#define DEBUG_TYPE "mips16-instrinfo"
Functions
static void addSaveRestoreRegs (MachineInstrBuilder &MIB, ArrayRef< CalleeSavedInfo > CSI, unsigned Flags=0)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips16-instrinfo"
Definition at line 40 of file Mips16InstrInfo.cpp.
Function Documentation
addSaveRestoreRegs()
static void addSaveRestoreRegs (MachineInstrBuilder & MIB, ArrayRef< CalleeSavedInfo > CSI, unsigned Flags = 0) static
Definition at line 184 of file Mips16InstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::numbers::e, i, llvm_unreachable, RA, and llvm::ArrayRef< T >::size().
Referenced by llvm::Mips16InstrInfo::makeFrame(), and llvm::Mips16InstrInfo::restoreFrame().