LLVM: lib/Target/Mips/Disassembler/MipsDisassembler.cpp File Reference
MipsDisassembler.cpp File Reference
#include "MCTargetDesc/MipsMCTargetDesc.h"
#include "Mips.h"
#include "TargetInfo/MipsTargetInfo.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include "MipsGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "mips-disassembler"
Typedefs
using DecodeStatus = MCDisassembler::DecodeStatus
Functions
static DecodeStatus DecodeGPR64RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCPU16RegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRMM16RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRMM16ZeroRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRMM16MovePRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePtrRegisterClass (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeDSPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFGR64RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFGR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCCRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFCCRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFGRCCRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeHWRegsRegisterClass (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAFGR64RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeACC64DSPRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeHI32DSPRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLO32DSPRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMSA128BRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMSA128HRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMSA128WRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMSA128DRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMSACtrlRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCOP0RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCOP2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchTarget (MCInst &Inst, unsigned Offset, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchTarget1SImm16 (MCInst &Inst, unsigned Offset, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeJumpTarget (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchTarget21 (MCInst &Inst, unsigned Offset, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchTarget21MM (MCInst &Inst, unsigned Offset, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchTarget26 (MCInst &Inst, unsigned Offset, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchTarget7MM (MCInst &Inst, unsigned Offset, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchTarget10MM (MCInst &Inst, unsigned Offset, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchTargetMM (MCInst &Inst, unsigned Offset, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBranchTarget26MM (MCInst &Inst, unsigned Offset, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeJumpTargetMM (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeJumpTargetXMM (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMem (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemEVA (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLoadByte15 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCacheOp (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCacheeOp_CacheOpR6 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCacheOpMM (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePrefeOpMM (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSyncI (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSyncI_MM (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSynciR6 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMSA128Mem (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemMMImm4 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemMMSPImm5Lsl2 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemMMGPImm7Lsl2 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemMMReglistImm4Lsl2 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemMMImm9 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemMMImm12 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMemMMImm16 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFMem (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFMemMMR2 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFMem2 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFMem3 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFMemCop2R6 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFMemCop2MMR6 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSpecial3LlSc (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeAddiur2Simm7 (MCInst &Inst, unsigned Value, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLi16Imm (MCInst &Inst, unsigned Value, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodePOOL16BEncodedField (MCInst &Inst, unsigned Value, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned Bits, int Offset, int Scale>
static DecodeStatus DecodeUImmWithOffsetAndScale (MCInst &Inst, unsigned Value, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned Bits, int Offset>
static DecodeStatus DecodeUImmWithOffset (MCInst &Inst, unsigned Value, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned Bits, int Offset = 0, int ScaleBy = 1>
static DecodeStatus DecodeSImmWithOffsetAndScale (MCInst &Inst, unsigned Value, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeInsSize (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSimm19Lsl2 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSimm18Lsl3 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSimm9SP (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeANDI16Imm (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSimm23Lsl2 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeINSVE_DF (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
INSVE_[BHWD] have an implicit operand that the generated decoder doesn't handle.
template<typename InsnType >
static DecodeStatus DecodeDAHIDATIMMR6 (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeDAHIDATI (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeAddiGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodePOP35GroupBranchMMR6 (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeDaddiGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodePOP37GroupBranchMMR6 (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodePOP65GroupBranchMMR6 (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodePOP75GroupBranchMMR6 (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeBlezlGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeBgtzlGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeBgtzGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeBlezGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeBgtzGroupBranchMMR6 (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeBlezGroupBranchMMR6 (MCInst &MI, InsnType insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeDINS (MCInst &MI, InsnType Insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeDEXT (MCInst &MI, InsnType Insn, uint64_t Address, const MCDisassembler *Decoder)
template<typename InsnType >
static DecodeStatus DecodeCRC (MCInst &MI, InsnType Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRegListOperand (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRegListOperand16 (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMovePRegPair (MCInst &Inst, unsigned RegPair, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeMovePOperands (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFIXMEInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static MCDisassembler * createMipsDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
static MCDisassembler * createMipselDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsDisassembler ()
static unsigned getReg (const MCDisassembler *D, unsigned RC, unsigned RegNo)
static DecodeStatus readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn, bool IsBigEndian)
Read two bytes from the ArrayRef and return 16 bit halfword sorted according to the given endianness.
static DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn, bool IsBigEndian, bool IsMicroMips)
Read four bytes from the ArrayRef and return 32 bit word sorted according to the given endianness.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-disassembler"
Definition at line 34 of file MipsDisassembler.cpp.
Typedef Documentation
DecodeStatus
using DecodeStatus = MCDisassembler::DecodeStatus
Definition at line 36 of file MipsDisassembler.cpp.
Function Documentation
createMipsDisassembler()
static MCDisassembler* createMipsDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 493 of file MipsDisassembler.cpp.
Referenced by LLVMInitializeMipsDisassembler().
createMipselDisassembler()
static MCDisassembler* createMipselDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 500 of file MipsDisassembler.cpp.
Referenced by LLVMInitializeMipsDisassembler().
DecodeACC64DSPRegisterClass()
static DecodeStatus DecodeACC64DSPRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1993 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeAddiGroupBranch()
template<typename InsnType > static DecodeStatus DecodeAddiGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 604 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeAddiur2Simm7()
static DecodeStatus DecodeAddiur2Simm7 (MCInst & Inst, unsigned Value, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2203 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeAFGR64RegisterClass()
static DecodeStatus DecodeAFGR64RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1982 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeANDI16Imm()
static DecodeStatus DecodeANDI16Imm (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2290 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), Insn, and llvm::MCDisassembler::Success.
DecodeBgtzGroupBranch()
template<typename InsnType > static DecodeStatus DecodeBgtzGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 915 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBgtzGroupBranchMMR6()
template<typename InsnType > static DecodeStatus DecodeBgtzGroupBranchMMR6 (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2430 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBgtzlGroupBranch()
template<typename InsnType > static DecodeStatus DecodeBgtzlGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 871 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBlezGroupBranch()
template<typename InsnType > static DecodeStatus DecodeBlezGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 964 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBlezGroupBranchMMR6()
template<typename InsnType > static DecodeStatus DecodeBlezGroupBranchMMR6 (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2479 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBlezlGroupBranch()
template<typename InsnType > static DecodeStatus DecodeBlezlGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 828 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBranchTarget()
static DecodeStatus DecodeBranchTarget (MCInst & Inst, unsigned Offset, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2103 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeBranchTarget10MM()
static DecodeStatus DecodeBranchTarget10MM (MCInst & Inst, unsigned Offset, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2162 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeBranchTarget1SImm16()
static DecodeStatus DecodeBranchTarget1SImm16 (MCInst & Inst, unsigned Offset, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2111 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeBranchTarget21()
static DecodeStatus DecodeBranchTarget21 (MCInst & Inst, unsigned Offset, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2127 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeBranchTarget21MM()
static DecodeStatus DecodeBranchTarget21MM (MCInst & Inst, unsigned Offset, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2136 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeBranchTarget26()
static DecodeStatus DecodeBranchTarget26 (MCInst & Inst, unsigned Offset, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2145 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeBranchTarget26MM()
static DecodeStatus DecodeBranchTarget26MM (MCInst & Inst, unsigned Offset, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2178 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeBranchTarget7MM()
static DecodeStatus DecodeBranchTarget7MM (MCInst & Inst, unsigned Offset, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2154 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeBranchTargetMM()
static DecodeStatus DecodeBranchTargetMM (MCInst & Inst, unsigned Offset, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2170 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeCacheeOp_CacheOpR6()
static DecodeStatus DecodeCacheeOp_CacheOpR6 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1565 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeCacheOp()
static DecodeStatus DecodeCacheOp (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1518 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeCacheOpMM()
static DecodeStatus DecodeCacheOpMM (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1533 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeCCRRegisterClass()
static DecodeStatus DecodeCCRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1431 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeCOP0RegisterClass()
static DecodeStatus DecodeCOP0RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2081 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeCOP2RegisterClass()
static DecodeStatus DecodeCOP2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2092 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeCPU16RegsRegisterClass()
static DecodeStatus DecodeCPU16RegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1338 of file MipsDisassembler.cpp.
References llvm::MCDisassembler::Fail.
DecodeCRC()
template<typename InsnType > static DecodeStatus DecodeCRC (MCInst & MI, InsnType Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1092 of file MipsDisassembler.cpp.
References llvm::MCOperand::createReg(), getReg(), Insn, MI, and llvm::MCDisassembler::Success.
DecodeDaddiGroupBranch()
template<typename InsnType > static DecodeStatus DecodeDaddiGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 677 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeDAHIDATI()
template<typename InsnType > static DecodeStatus DecodeDAHIDATI (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 590 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), llvm::RISCVMatInt::Imm, MI, and llvm::MCDisassembler::Success.
DecodeDAHIDATIMMR6()
template<typename InsnType > static DecodeStatus DecodeDAHIDATIMMR6 (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 575 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), llvm::RISCVMatInt::Imm, MI, and llvm::MCDisassembler::Success.
DecodeDEXT()
template<typename InsnType > static DecodeStatus DecodeDEXT (MCInst & MI, InsnType Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1008 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm_unreachable, MI, and llvm::MCDisassembler::Success.
DecodeDINS()
template<typename InsnType > static DecodeStatus DecodeDINS (MCInst & MI, InsnType Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1050 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm_unreachable, MI, and llvm::MCDisassembler::Success.
DecodeDSPRRegisterClass()
static DecodeStatus DecodeDSPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1403 of file MipsDisassembler.cpp.
References DecodeGPR32RegisterClass().
DecodeFCCRegisterClass()
static DecodeStatus DecodeFCCRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1441 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeFGR32RegisterClass()
static DecodeStatus DecodeFGR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1420 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeFGR64RegisterClass()
static DecodeStatus DecodeFGR64RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1409 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeFGRCCRegisterClass()
static DecodeStatus DecodeFGRCCRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1451 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeFIXMEInstruction()
static DecodeStatus DecodeFIXMEInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2524 of file MipsDisassembler.cpp.
References llvm::MCDisassembler::Fail.
DecodeFMem()
static DecodeStatus DecodeFMem (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1850 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeFMem2()
static DecodeStatus DecodeFMem2 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1885 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeFMem3()
static DecodeStatus DecodeFMem3 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1901 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeFMemCop2MMR6()
static DecodeStatus DecodeFMemCop2MMR6 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1934 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeFMemCop2R6()
static DecodeStatus DecodeFMemCop2R6 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1917 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeFMemMMR2()
static DecodeStatus DecodeFMemMMR2 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1866 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeGPR32RegisterClass()
static DecodeStatus DecodeGPR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1384 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeDSPRRegisterClass(), and DecodePtrRegisterClass().
DecodeGPR64RegisterClass()
static DecodeStatus DecodeGPR64RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1343 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodePtrRegisterClass().
DecodeGPRMM16MovePRegisterClass()
static DecodeStatus DecodeGPRMM16MovePRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1375 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeMovePOperands().
DecodeGPRMM16RegisterClass()
static DecodeStatus DecodeGPRMM16RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1354 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeMemMMImm4().
DecodeGPRMM16ZeroRegisterClass()
static DecodeStatus DecodeGPRMM16ZeroRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1365 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeMemMMImm4().
DecodeHI32DSPRegisterClass()
static DecodeStatus DecodeHI32DSPRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2004 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeHWRegsRegisterClass()
static DecodeStatus DecodeHWRegsRegisterClass (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1972 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeInsSize()
static DecodeStatus DecodeInsSize (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2251 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), Insn, int, and llvm::MCDisassembler::Success.
DecodeINSVE_DF()
template<typename InsnType > static DecodeStatus DecodeINSVE_DF (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
INSVE_[BHWD] have an implicit operand that the generated decoder doesn't handle.
Definition at line 527 of file MipsDisassembler.cpp.
References assert(), llvm::MCOperand::createImm(), DecodeMSA128BRegisterClass(), DecodeMSA128DRegisterClass(), DecodeMSA128HRegisterClass(), DecodeMSA128WRegisterClass(), llvm::MCDisassembler::Fail, llvm_unreachable, MI, llvm::MCDisassembler::Success, uint64_t, and unsigned.
DecodeJumpTarget()
static DecodeStatus DecodeJumpTarget (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2119 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Insn, and llvm::MCDisassembler::Success.
DecodeJumpTargetMM()
static DecodeStatus DecodeJumpTargetMM (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2187 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Insn, and llvm::MCDisassembler::Success.
DecodeJumpTargetXMM()
static DecodeStatus DecodeJumpTargetXMM (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2195 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Insn, and llvm::MCDisassembler::Success.
DecodeLi16Imm()
static DecodeStatus DecodeLi16Imm (MCInst & Inst, unsigned Value, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2215 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeLO32DSPRegisterClass()
static DecodeStatus DecodeLO32DSPRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2015 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeLoadByte15()
static DecodeStatus DecodeLoadByte15 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1501 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMem()
static DecodeStatus DecodeMem (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1462 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCInst::getOpcode(), getReg(), Insn, llvm::Offset, llvm::PPCISD::SC, and llvm::MCDisassembler::Success.
DecodeMemEVA()
static DecodeStatus DecodeMemEVA (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1482 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCInst::getOpcode(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMemMMGPImm7Lsl2()
static DecodeStatus DecodeMemMMGPImm7Lsl2 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1740 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMemMMImm12()
static DecodeStatus DecodeMemMMImm12 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1799 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeRegListOperand(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMemMMImm16()
static DecodeStatus DecodeMemMMImm16 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1833 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMemMMImm4()
static DecodeStatus DecodeMemMMImm4 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1668 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), DecodeGPRMM16RegisterClass(), DecodeGPRMM16ZeroRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMemMMImm9()
static DecodeStatus DecodeMemMMImm9 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1779 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCInst::getOpcode(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMemMMReglistImm4Lsl2()
static DecodeStatus DecodeMemMMReglistImm4Lsl2 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1755 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), DecodeRegListOperand16(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMemMMSPImm5Lsl2()
static DecodeStatus DecodeMemMMSPImm5Lsl2 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1725 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMovePOperands()
static DecodeStatus DecodeMovePOperands (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2353 of file MipsDisassembler.cpp.
References DecodeGPRMM16MovePRegisterClass(), DecodeMovePRegPair(), llvm::MCDisassembler::Fail, Insn, and llvm::MCDisassembler::Success.
DecodeMovePRegPair()
static DecodeStatus DecodeMovePRegPair (MCInst & Inst, unsigned RegPair, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2379 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by DecodeMovePOperands().
DecodeMSA128BRegisterClass()
static DecodeStatus DecodeMSA128BRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2026 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeINSVE_DF().
DecodeMSA128DRegisterClass()
static DecodeStatus DecodeMSA128DRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2059 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeINSVE_DF().
DecodeMSA128HRegisterClass()
static DecodeStatus DecodeMSA128HRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2037 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeINSVE_DF().
DecodeMSA128Mem()
static DecodeStatus DecodeMSA128Mem (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1621 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeMSA128WRegisterClass()
static DecodeStatus DecodeMSA128WRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2048 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeINSVE_DF().
DecodeMSACtrlRegisterClass()
static DecodeStatus DecodeMSACtrlRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2070 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodePOOL16BEncodedField()
static DecodeStatus DecodePOOL16BEncodedField (MCInst & Inst, unsigned Value, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2225 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodePOP35GroupBranchMMR6()
template<typename InsnType > static DecodeStatus DecodePOP35GroupBranchMMR6 (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 643 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodePOP37GroupBranchMMR6()
template<typename InsnType > static DecodeStatus DecodePOP37GroupBranchMMR6 (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 716 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodePOP65GroupBranchMMR6()
template<typename InsnType > static DecodeStatus DecodePOP65GroupBranchMMR6 (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 750 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodePOP75GroupBranchMMR6()
template<typename InsnType > static DecodeStatus DecodePOP75GroupBranchMMR6 (MCInst & MI, InsnType insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 789 of file MipsDisassembler.cpp.
References llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), llvm::RISCVMatInt::Imm, MI, llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodePrefeOpMM()
static DecodeStatus DecodePrefeOpMM (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1549 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodePtrRegisterClass()
static DecodeStatus DecodePtrRegisterClass (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1394 of file MipsDisassembler.cpp.
References DecodeGPR32RegisterClass(), and DecodeGPR64RegisterClass().
DecodeRegListOperand()
static DecodeStatus DecodeRegListOperand (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2301 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, i, Insn, RA, and llvm::MCDisassembler::Success.
Referenced by DecodeMemMMImm12().
DecodeRegListOperand16()
static DecodeStatus DecodeRegListOperand16 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2329 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCInst::getOpcode(), i, Insn, RA, and llvm::MCDisassembler::Success.
Referenced by DecodeMemMMReglistImm4Lsl2().
DecodeSimm18Lsl3()
static DecodeStatus DecodeSimm18Lsl3 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2269 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Insn, and llvm::MCDisassembler::Success.
DecodeSimm19Lsl2()
static DecodeStatus DecodeSimm19Lsl2 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2262 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Insn, and llvm::MCDisassembler::Success.
DecodeSimm23Lsl2()
static DecodeStatus DecodeSimm23Lsl2 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2422 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Insn, and llvm::MCDisassembler::Success.
DecodeSimm9SP()
static DecodeStatus DecodeSimm9SP (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2276 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Insn, and llvm::MCDisassembler::Success.
DecodeSImmWithOffsetAndScale()
template<unsigned Bits, int Offset = 0, int ScaleBy = 1> static DecodeStatus DecodeSImmWithOffsetAndScale (MCInst & Inst, unsigned Value, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2244 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeSpecial3LlSc()
static DecodeStatus DecodeSpecial3LlSc (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1951 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCInst::getOpcode(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeSyncI()
static DecodeStatus DecodeSyncI (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1581 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeSyncI_MM()
static DecodeStatus DecodeSyncI_MM (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1594 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, llvm::Offset, and llvm::MCDisassembler::Success.
DecodeSynciR6()
static DecodeStatus DecodeSynciR6 (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 1608 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), getReg(), Insn, and llvm::MCDisassembler::Success.
DecodeUImmWithOffset()
template<unsigned Bits, int Offset> static DecodeStatus DecodeUImmWithOffset (MCInst & Inst, unsigned Value, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 352 of file MipsDisassembler.cpp.
DecodeUImmWithOffsetAndScale()
template<unsigned Bits, int Offset, int Scale> static DecodeStatus DecodeUImmWithOffsetAndScale (MCInst & Inst, unsigned Value, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 2234 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::tgtok::Bits, llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
getReg()
static unsigned getReg (const MCDisassembler * D, unsigned RC, unsigned RegNo) static
Definition at line 521 of file MipsDisassembler.cpp.
References llvm::MCRegisterClass::begin(), D, and llvm::MCRegisterInfo::getRegClass().
Referenced by AddNodeIDCustom(), XtensaOperand::addRegOperands(), applyBuildVectorToDup(), llvm::CombinerHelper::applyCombineDivRem(), llvm::CombinerHelper::applyCombineInsertVecElts(), applyExtractVecEltPairwiseAdd(), AMDGPUCombinerHelper::applyFoldableFneg(), llvm::CombinerHelper::applyFoldBinOpIntoSelect(), llvm::CombinerHelper::applyShiftOfShiftedLogic(), buildCopyToRegs(), llvm::CSEMIRBuilder::buildInstr(), llvm::PPCInstrInfo::canInsertSelect(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), canRenameUpToDef(), llvm::GISelKnownBits::computeKnownBitsImpl(), conversionLibcall(), DecodeACC64DSPRegisterClass(), DecodeAddiGroupBranch(), DecodeAFGR64RegisterClass(), DecodeBgtzGroupBranch(), DecodeBgtzGroupBranchMMR6(), DecodeBgtzlGroupBranch(), DecodeBlezGroupBranch(), DecodeBlezGroupBranchMMR6(), DecodeBlezlGroupBranch(), DecodeCacheeOp_CacheOpR6(), DecodeCacheOp(), DecodeCacheOpMM(), DecodeCCRRegisterClass(), DecodeCOP0RegisterClass(), DecodeCOP2RegisterClass(), DecodeCRC(), DecodeDaddiGroupBranch(), DecodeDAHIDATI(), DecodeDAHIDATIMMR6(), DecodeDEXT(), DecodeDINS(), DecodeFCCRegisterClass(), DecodeFGR32RegisterClass(), DecodeFGR64RegisterClass(), DecodeFGRCCRegisterClass(), DecodeFMem(), DecodeFMem2(), DecodeFMem3(), DecodeFMemCop2MMR6(), DecodeFMemCop2R6(), DecodeFMemMMR2(), DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), DecodeGPRMM16MovePRegisterClass(), DecodeGPRMM16RegisterClass(), DecodeGPRMM16ZeroRegisterClass(), DecodeHI32DSPRegisterClass(), DecodeLO32DSPRegisterClass(), DecodeLoadByte15(), DecodeMem(), DecodeMemEVA(), DecodeMemMMGPImm7Lsl2(), DecodeMemMMImm12(), DecodeMemMMImm16(), DecodeMemMMImm9(), DecodeMemMMSPImm5Lsl2(), DecodeMSA128BRegisterClass(), DecodeMSA128DRegisterClass(), DecodeMSA128HRegisterClass(), DecodeMSA128Mem(), DecodeMSA128WRegisterClass(), DecodeMSACtrlRegisterClass(), DecodePOP35GroupBranchMMR6(), DecodePOP37GroupBranchMMR6(), DecodePOP65GroupBranchMMR6(), DecodePOP75GroupBranchMMR6(), DecodePrefeOpMM(), DecodeSpecial3LlSc(), DecodeSyncI(), DecodeSyncI_MM(), DecodeSynciR6(), llvm::SIInstrInfo::expandMovDPP64(), llvm::LegalizerHelper::fewerElementsVectorReductions(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), getMaxCalleeSavedReg(), getUnderlyingArgRegs(), getVectorFCMP(), llvm::XCoreInstrInfo::insertBranch(), llvm::HexagonInstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::MachineInstr::isConstantValuePHI(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::AMDGPULegalizerInfo::legalizeBufferAtomic(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::LegalizerHelper::lowerDIVREM(), llvm::LegalizerHelper::lowerFunnelShiftWithInverse(), llvm::AArch64CallLowering::lowerReturn(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFMulToFMadOrFMA(), mayCombineMisaligned(), llvm::LegalizerHelper::narrowScalar(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::TargetInstrInfo::PredicateInstruction(), XtensaOperand::print(), llvm::RegisterBankInfo::OperandsMapper::print(), llvm::PPCInstrInfo::reverseBranchCondition(), llvm::RISCVDAGToDAGISel::selectVLOp(), llvm::SystemZRegisterInfo::shouldCoalesce(), simpleLibcall(), and llvm::PPCInstrInfo::SubsumesPredicate().
LLVMInitializeMipsDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsDisassembler ()
Definition at line 507 of file MipsDisassembler.cpp.
References createMipsDisassembler(), createMipselDisassembler(), llvm::getTheMips64elTarget(), llvm::getTheMips64Target(), llvm::getTheMipselTarget(), llvm::getTheMipsTarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
readInstruction16()
static DecodeStatus readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn, bool IsBigEndian) static
Read two bytes from the ArrayRef and return 16 bit halfword sorted according to the given endianness.
Definition at line 1107 of file MipsDisassembler.cpp.
References llvm::MCDisassembler::Fail, Insn, llvm::ArrayRef< T >::size(), and llvm::MCDisassembler::Success.
readInstruction32()
static DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn, bool IsBigEndian, bool IsMicroMips) static
Read four bytes from the ArrayRef and return 32 bit word sorted according to the given endianness.
Definition at line 1127 of file MipsDisassembler.cpp.
References llvm::MCDisassembler::Fail, Insn, llvm::ArrayRef< T >::size(), and llvm::MCDisassembler::Success.