LLVM: lib/Analysis/MLInlineAdvisor.cpp File Reference
MLInlineAdvisor.cpp File Reference
#include "llvm/Analysis/MLInlineAdvisor.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/FunctionPropertiesAnalysis.h"
#include "llvm/Analysis/InlineCost.h"
#include "llvm/Analysis/InlineModelFeatureMaps.h"
#include "llvm/Analysis/InteractiveModelRunner.h"
#include "llvm/Analysis/LazyCallGraph.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MLModelRunner.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ReleaseModeModelRunner.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "inline-ml"
#define POPULATE_NAMES(_, NAME) TensorSpec::createSpec<int64_t>(NAME, {1}),
#define POPULATE_NAMES(_, NAME, __) TensorSpec::createSpec<int64_t>(NAME, {1}),
Typedefs
using CompiledModelType = NoopSavedModelImpl
Functions
CallBase * getInlinableCS (Instruction &I)
Variables
static cl::opt< std::string > InteractiveChannelBaseName ("inliner-interactive-channel-base", cl::Hidden, cl::desc("Base file path for the interactive mode. The incoming filename should " "have the name <inliner-interactive-channel-base>.in, while the " "outgoing name should be <inliner-interactive-channel-base>.out"))
static cl::opt< float > SizeIncreaseThreshold ("ml-advisor-size-increase-threshold", cl::Hidden, cl::desc("Maximum factor by which expected native size may increase before " "blocking any further inlining."), cl::init(2.0))
static cl::opt< bool > KeepFPICache ("ml-advisor-keep-fpi-cache", cl::Hidden, cl::desc("For test - keep the ML Inline advisor's FunctionPropertiesInfo cache"), cl::init(false))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inline-ml"
Definition at line 67 of file MLInlineAdvisor.cpp.
POPULATE_NAMES [1/2]
#define POPULATE_NAMES (_, NAME) TensorSpec::createSpec<int64_t>(NAME, {1}),
POPULATE_NAMES [2/2]
#define POPULATE_NAMES (_, NAME, __) TensorSpec::createSpec<int64_t>(NAME, {1}),
Typedef Documentation
CompiledModelType
using CompiledModelType = NoopSavedModelImpl
Definition at line 47 of file MLInlineAdvisor.cpp.
Function Documentation
getInlinableCS()
CallBase* getInlinableCS (Instruction & I)
Definition at line 101 of file MLInlineAdvisor.cpp.
References Callee, and I.
Referenced by llvm::MLInlineAdvisor::MLInlineAdvisor().
Variable Documentation
InteractiveChannelBaseName
cl::opt<std::string> InteractiveChannelBaseName("inliner-interactive-channel-base", cl::Hidden, cl::desc("Base file path for the interactive mode. The incoming filename should " "have the name <inliner-interactive-channel-base>.in, while the " "outgoing name should be <inliner-interactive-channel-base>.out")) static
Referenced by llvm::getReleaseModeAdvisor().
KeepFPICache
cl::opt<bool> KeepFPICache("ml-advisor-keep-fpi-cache", cl::Hidden, cl::desc("For test - keep the ML Inline advisor's FunctionPropertiesInfo cache"), cl::init(false)) static
Referenced by llvm::MLInlineAdvisor::onPassExit().
SizeIncreaseThreshold
cl::opt<float> SizeIncreaseThreshold("ml-advisor-size-increase-threshold", cl::Hidden, cl::desc("Maximum factor by which expected native size may increase before " "blocking any further inlining."), cl::init(2.0)) static
Referenced by llvm::MLInlineAdvisor::onSuccessfulInlining().