LLVM: lib/Analysis/ModuleDebugInfoPrinter.cpp File Reference
ModuleDebugInfoPrinter.cpp File Reference
#include "llvm/Analysis/ModuleDebugInfoPrinter.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/PassManager.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
INITIALIZE_PASS (ModuleDebugInfoLegacyPrinter, "module-debuginfo", "Decodes module-level debug info", false, true) ModulePass *llvm
static void printFile (raw_ostream &O, StringRef Filename, StringRef Directory, unsigned Line=0)
static void printModuleDebugInfo (raw_ostream &O, const Module *M, const DebugInfoFinder &Finder)
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (ModuleDebugInfoLegacyPrinter , "module-debuginfo" , "Decodes module-level debug info" , false , true)
Definition at line 49 of file ModuleDebugInfoPrinter.cpp.
printFile()
static void printFile (raw_ostream & O, StringRef Filename, StringRef Directory, unsigned Line = 0) static
Definition at line 61 of file ModuleDebugInfoPrinter.cpp.
References llvm::StringRef::empty(), and llvm::RISCVFenceField::O.
Referenced by printModuleDebugInfo().
printModuleDebugInfo()
static void printModuleDebugInfo (raw_ostream & O, const Module * M, const DebugInfoFinder & Finder) static
Definition at line 74 of file ModuleDebugInfoPrinter.cpp.
References llvm::dwarf::AttributeEncodingString(), llvm::DebugInfoFinder::compile_units(), llvm::DebugInfoFinder::global_variables(), llvm::dwarf::LanguageString(), llvm::RISCVFenceField::O, printFile(), S, llvm::DebugInfoFinder::subprograms(), llvm::dwarf::TagString(), and llvm::DebugInfoFinder::types().
Referenced by llvm::ModuleDebugInfoPrinterPass::run().