LLVM: gen-inline-oz-test-model Namespace Reference
gen-inline-oz-test-model Namespace Reference
Functions
def get_input_signature ()
def get_output_signature ()
def get_output_spec ()
def get_output_spec_path (path)
def build_mock_model (path, signature)
def get_signature ()
def main (argv)
Variables
string POLICY_DECISION_LABEL = 'inlining_decision'
string POLICY_OUTPUT_SPEC
Function Documentation
build_mock_model()
def gen-inline-oz-test-model.build_mock_model (path, signature)
Build and save the mock model with the given signature
Definition at line 102 of file gen-inline-oz-test-model.py.
References get_output_spec_path(), and print().
Referenced by main().
get_input_signature()
def gen-inline-oz-test-model.get_input_signature ()
Returns the list of features for LLVM inlining.
Definition at line 33 of file gen-inline-oz-test-model.py.
Referenced by get_signature().
get_output_signature()
def gen-inline-oz-test-model.get_output_signature ()
Definition at line 91 of file gen-inline-oz-test-model.py.
Referenced by get_signature().
get_output_spec()
def gen-inline-oz-test-model.get_output_spec ()
Definition at line 95 of file gen-inline-oz-test-model.py.
Referenced by get_signature().
get_output_spec_path()
def gen-inline-oz-test-model.get_output_spec_path (path)
Definition at line 98 of file gen-inline-oz-test-model.py.
Referenced by build_mock_model().
get_signature()
def gen-inline-oz-test-model.get_signature ()
Definition at line 118 of file gen-inline-oz-test-model.py.
References get_input_signature(), get_output_signature(), and get_output_spec().
Referenced by llvm::pdb::DIARawSymbol.getSignature(), and main().
main()
def gen-inline-oz-test-model.main (argv)
Definition at line 126 of file gen-inline-oz-test-model.py.
References build_mock_model(), get_signature(), and print().
Variable Documentation
POLICY_DECISION_LABEL
string gen-inline-oz-test-model.POLICY_DECISION_LABEL = 'inlining_decision'
Definition at line 14 of file gen-inline-oz-test-model.py.
POLICY_OUTPUT_SPEC
string gen-inline-oz-test-model.POLICY_OUTPUT_SPEC
Initial value:
 =  """
 [
     {
         "logging_name": "inlining_decision",
         "tensor_spec": {
             "name": "StatefulPartitionedCall",
             "port": 0,
             "type": "int64_t",
             "shape": [
                 1
             ]
         }
     }
 ]
 """
Definition at line 15 of file gen-inline-oz-test-model.py.