LLVM: llvm::ARM_MC Namespace Reference
llvm::ARM_MC Namespace Reference
Functions
std::string ParseARMTriple (const Triple &TT, StringRef CPU)
void initLLVMToCVRegMapping (MCRegisterInfo *MRI)
bool isPredicated (const MCInst &MI, const MCInstrInfo *MCII)
bool isCPSRDefined (const MCInst &MI, const MCInstrInfo *MCII)
template<class Inst >
bool isLDMBaseRegInList (const Inst &MI)
uint64_t evaluateBranchTarget (const MCInstrDesc &InstDesc, uint64_t Addr, int64_t Imm)
MCSubtargetInfo * createARMMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
Create a ARM MCSubtargetInfo instance.
Function Documentation
createARMMCSubtargetInfo()
MCSubtargetInfo * llvm::ARM_MC::createARMMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS)
Create a ARM MCSubtargetInfo instance.
This is exposed so Asm parser, etc. do not need to go through TargetRegistry.
Definition at line 205 of file ARMMCTargetDesc.cpp.
References llvm::X86AS::FS, and ParseARMTriple().
Referenced by LLVMInitializeARMTargetMC().
evaluateBranchTarget()
uint64_t llvm::ARM_MC::evaluateBranchTarget (const MCInstrDesc & InstDesc, uint64_t Addr, int64_t Imm)
Definition at line 187 of file ARMMCTargetDesc.cpp.
References Addr, llvm::ARMII::FormMask, llvm::MCInstrDesc::getOpcode(), llvm::RISCVMatInt::Imm, llvm::Offset, llvm::ARMII::ThumbFrm, llvm::MCInstrDesc::TSFlags, uint64_t, and x3.
Referenced by llvm::ARMInstPrinter::printOperand().
initLLVMToCVRegMapping()
void llvm::ARM_MC::initLLVMToCVRegMapping (MCRegisterInfo * MRI)
Definition at line 224 of file ARMMCTargetDesc.cpp.
References I, MRI, R2, R4, and R6.
Referenced by llvm::ARMBaseRegisterInfo::ARMBaseRegisterInfo(), and createARMMCRegisterInfo().
isCPSRDefined()
bool llvm::ARM_MC::isCPSRDefined (const MCInst & MI, const MCInstrInfo * MCII)
Definition at line 176 of file ARMMCTargetDesc.cpp.
References llvm::MCInstrInfo::get(), llvm::MCOperand::getReg(), I, llvm::MCOperand::isReg(), MI, and llvm::MCInstrDesc::operands().
isLDMBaseRegInList()
template<class Inst > bool llvm::ARM_MC::isLDMBaseRegInList (const Inst & MI)
Definition at line 48 of file ARMMCTargetDesc.h.
References E, I, and MI.
isPredicated()
bool llvm::ARM_MC::isPredicated (const MCInst & MI, const MCInstrInfo * MCII)
Definition at line 170 of file ARMMCTargetDesc.cpp.
References llvm::ARMCC::AL, llvm::MCInstrDesc::findFirstPredOperandIdx(), llvm::MCInstrInfo::get(), and MI.
Referenced by llvm::ARCInstrInfo::analyzeBranch(), llvm::InterleavedAccessInfo::analyzeInterleaving(), llvm::HexagonMCInstrInfo::predicateInfo(), and producesFalseLanesZero().
ParseARMTriple()
std::string llvm::ARM_MC::ParseARMTriple (const Triple & TT, StringRef CPU)
Definition at line 142 of file ARMMCTargetDesc.cpp.
References llvm::StringRef::empty(), llvm::ARM::getArchName(), and llvm::ARM::parseArch().
Referenced by createARMMCSubtargetInfo().