LLVM: llvm::memprof Namespace Reference
llvm::memprof Namespace Reference
Classes
struct AllocationInfo
class CallStack
Helper class to iterate through stack ids in both metadata (memprof MIB and callsite) and the corresponding ThinLTO summary data structures (CallsiteInfo and MIBInfo).
class CallStackTrie
Class to build a trie of call stack contexts for a particular profiled allocation call, along with their associated allocation types.
struct Frame
class FrameLookupTrait
class FrameWriterTrait
struct IndexedAllocationInfo
struct IndexedMemProfRecord
struct MemProfRecord
struct PortableMemInfoBlock
class RawMemProfReader
class RecordLookupTrait
class RecordWriterTrait
Typedefs
using MemProfSchema = llvm::SmallVector< Meta, static_cast< int >(Meta::Size)>
using FrameId = uint64_t
using CallStackMap = llvm::DenseMap< uint64_t, llvm::SmallVector< uint64_t > >
Enumerations
enum Meta : uint64_t { Meta::Start = 0, Meta::MIBEntryDef, Meta::Size }
Functions
AllocationType getAllocType (uint64_t MaxAccessCount, uint64_t MinSize, uint64_t MinLifetime)
Return the allocation type for a given set of memory profile values.
MDNode * buildCallstackMetadata (ArrayRef< uint64_t > CallStack, LLVMContext &Ctx)
Build callstack metadata from the provided list of call stack ids.
MDNode * getMIBStackNode (const MDNode *MIB)
Returns the stack node from an MIB metadata node.
AllocationType getMIBAllocType (const MDNode *MIB)
Returns the allocation type from an MIB metadata node.
Expected< MemProfSchema > readMemProfSchema (const unsigned char *&Buffer)
Typedef Documentation
CallStackMap
using llvm::memprof::CallStackMap = typedef llvm::DenseMap<uint64_t, llvm::SmallVector<uint64_t> >
Definition at line 36 of file RawMemProfReader.h.
FrameId
using llvm::memprof::FrameId = typedef uint64_t
Definition at line 138 of file MemProf.h.
MemProfSchema
using llvm::memprof::MemProfSchema = typedef llvm::SmallVector<Meta, static_cast<int>(Meta::Size)>
Definition at line 27 of file MemProf.h.
Enumeration Type Documentation
Meta
enum llvm::memprof::Meta : uint64_t strong
Enumerator
Start
MIBEntryDef
Size
Definition at line 19 of file MemProf.h.
Function Documentation
buildCallstackMetadata()
MDNode * llvm::memprof::buildCallstackMetadata (ArrayRef< uint64_t > CallStack, LLVMContext & Ctx)
Build callstack metadata from the provided list of call stack ids.
Returns the resulting metadata node.
Definition at line 44 of file MemoryProfileInfo.cpp.
References llvm::ConstantInt::get(), llvm::ValueAsMetadata::get(), llvm::MDNode::get(), and llvm::Type::getInt64Ty().
Referenced by addCallsiteMetadata(), and createMIBNode().
getAllocType()
AllocationType llvm::memprof::getAllocType (uint64_t MaxAccessCount, uint64_t MinSize, uint64_t MinLifetime)
Return the allocation type for a given set of memory profile values.
Definition at line 34 of file MemoryProfileInfo.cpp.
References llvm::Cold, MemProfAccessesPerByteColdThreshold, MemProfMinLifetimeColdThreshold, and llvm::NotCold.
Referenced by addCallStack().
getMIBAllocType()
AllocationType llvm::memprof::getMIBAllocType (const MDNode * MIB)
Returns the allocation type from an MIB metadata node.
Definition at line 61 of file MemoryProfileInfo.cpp.
References assert(), llvm::Cold, llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and llvm::NotCold.
Referenced by llvm::memprof::CallStackTrie::addCallStack(), and computeFunctionSummary().
getMIBStackNode()
MDNode * llvm::memprof::getMIBStackNode (const MDNode * MIB)
Returns the stack node from an MIB metadata node.
Definition at line 55 of file MemoryProfileInfo.cpp.
References assert(), llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
Referenced by llvm::memprof::CallStackTrie::addCallStack(), computeFunctionSummary(), and propagateMemProfHelper().
readMemProfSchema()
Expected< MemProfSchema > llvm::memprof::readMemProfSchema (const unsigned char *& Buffer)
Definition at line 84 of file MemProf.cpp.
References I, llvm::malformed, Ptr, Size, support(), and uint64_t.
Referenced by llvm::IndexedInstrProfReader::readHeader().