LLVM: llvm::DomTreeBuilder Namespace Reference
llvm::DomTreeBuilder Namespace Reference
Classes
struct SemiNCAInfo
Typedefs
using BBDomTree = DomTreeBase< BasicBlock >
using BBPostDomTree = PostDomTreeBase< BasicBlock >
using BBUpdates = ArrayRef< llvm::cfg::Update< BasicBlock * > >
using BBDomTreeGraphDiff = GraphDiff< BasicBlock *, false >
using BBPostDomTreeGraphDiff = GraphDiff< BasicBlock *, true >
Functions
template void Calculate< BBDomTree > (BBDomTree &DT)
template void CalculateWithUpdates< BBDomTree > (BBDomTree &DT, BBUpdates U)
template void Calculate< BBPostDomTree > (BBPostDomTree &DT)
template void InsertEdge< BBDomTree > (BBDomTree &DT, BasicBlock *From, BasicBlock *To)
template void InsertEdge< BBPostDomTree > (BBPostDomTree &DT, BasicBlock *From, BasicBlock *To)
template void DeleteEdge< BBDomTree > (BBDomTree &DT, BasicBlock *From, BasicBlock *To)
template void DeleteEdge< BBPostDomTree > (BBPostDomTree &DT, BasicBlock *From, BasicBlock *To)
template void ApplyUpdates< BBDomTree > (BBDomTree &DT, BBDomTreeGraphDiff &, BBDomTreeGraphDiff *)
template void ApplyUpdates< BBPostDomTree > (BBPostDomTree &DT, BBPostDomTreeGraphDiff &, BBPostDomTreeGraphDiff *)
template bool Verify< BBDomTree > (const BBDomTree &DT, BBDomTree::VerificationLevel VL)
template bool Verify< BBPostDomTree > (const BBPostDomTree &DT, BBPostDomTree::VerificationLevel VL)
template<typename DomTreeT >
void Calculate (DomTreeT &DT)
template<typename DomTreeT >
void CalculateWithUpdates (DomTreeT &DT, ArrayRef< typename DomTreeT::UpdateType > Updates)
template<typename DomTreeT >
void InsertEdge (DomTreeT &DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
template<typename DomTreeT >
void DeleteEdge (DomTreeT &DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
template<typename DomTreeT >
void ApplyUpdates (DomTreeT &DT, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > &PreViewCFG, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > *PostViewCFG)
template<typename DomTreeT >
bool Verify (const DomTreeT &DT, typename DomTreeT::VerificationLevel VL)
Typedef Documentation
BBDomTree
using llvm::DomTreeBuilder::BBDomTree = typedef DomTreeBase<BasicBlock>
Definition at line 57 of file Dominators.h.
BBDomTreeGraphDiff
using llvm::DomTreeBuilder::BBDomTreeGraphDiff = typedef GraphDiff<BasicBlock *, false>
Definition at line 62 of file Dominators.h.
BBPostDomTree
using llvm::DomTreeBuilder::BBPostDomTree = typedef PostDomTreeBase<BasicBlock>
Definition at line 58 of file Dominators.h.
BBPostDomTreeGraphDiff
using llvm::DomTreeBuilder::BBPostDomTreeGraphDiff = typedef GraphDiff<BasicBlock *, true>
Definition at line 63 of file Dominators.h.
BBUpdates
using llvm::DomTreeBuilder::BBUpdates = typedef ArrayRef<llvm::cfg::Update<BasicBlock *> >
Definition at line 60 of file Dominators.h.
Function Documentation
ApplyUpdates()
template<typename DomTreeT > void llvm::DomTreeBuilder::ApplyUpdates (DomTreeT & DT, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > & PreViewCFG, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > * PostViewCFG)
Definition at line 1591 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates().
Referenced by llvm::DominatorTreeBase< BasicBlock, false >::applyUpdates().
ApplyUpdates< BBDomTree >()
template void llvm::DomTreeBuilder::ApplyUpdates< BBDomTree > (BBDomTree & DT, BBDomTreeGraphDiff & , BBDomTreeGraphDiff *)
ApplyUpdates< BBPostDomTree >()
template void llvm::DomTreeBuilder::ApplyUpdates< BBPostDomTree > (BBPostDomTree & DT, BBPostDomTreeGraphDiff & , BBPostDomTreeGraphDiff *)
Calculate()
template<typename DomTreeT > void llvm::DomTreeBuilder::Calculate (DomTreeT & DT)
Definition at line 1561 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch().
Referenced by llvm::DominatorTreeBase< BasicBlock, false >::recalculate().
Calculate< BBDomTree >()
template void llvm::DomTreeBuilder::Calculate< BBDomTree > (BBDomTree & DT)
Calculate< BBPostDomTree >()
template void llvm::DomTreeBuilder::Calculate< BBPostDomTree > (BBPostDomTree & DT)
CalculateWithUpdates()
template<typename DomTreeT > void llvm::DomTreeBuilder::CalculateWithUpdates (DomTreeT & DT, ArrayRef< typename DomTreeT::UpdateType > Updates)
Definition at line 1566 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch().
Referenced by llvm::DominatorTreeBase< BasicBlock, false >::recalculate().
CalculateWithUpdates< BBDomTree >()
template void llvm::DomTreeBuilder::CalculateWithUpdates< BBDomTree > (BBDomTree & DT, BBUpdates U)
DeleteEdge()
template<typename DomTreeT > void llvm::DomTreeBuilder::DeleteEdge (DomTreeT & DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
Definition at line 1584 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), From, and std::swap().
Referenced by llvm::DominatorTreeBase< BasicBlock, false >::deleteEdge().
DeleteEdge< BBDomTree >()
template void llvm::DomTreeBuilder::DeleteEdge< BBDomTree > (BBDomTree & DT, BasicBlock * From, BasicBlock * To)
DeleteEdge< BBPostDomTree >()
template void llvm::DomTreeBuilder::DeleteEdge< BBPostDomTree > (BBPostDomTree & DT, BasicBlock * From, BasicBlock * To)
InsertEdge()
template<typename DomTreeT > void llvm::DomTreeBuilder::InsertEdge (DomTreeT & DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
Definition at line 1577 of file GenericDomTreeConstruction.h.
References From, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), and std::swap().
Referenced by llvm::DominatorTreeBase< BasicBlock, false >::insertEdge().
InsertEdge< BBDomTree >()
template void llvm::DomTreeBuilder::InsertEdge< BBDomTree > (BBDomTree & DT, BasicBlock * From, BasicBlock * To)
InsertEdge< BBPostDomTree >()
template void llvm::DomTreeBuilder::InsertEdge< BBPostDomTree > (BBPostDomTree & DT, BasicBlock * From, BasicBlock * To)
Verify()
template<typename DomTreeT > bool llvm::DomTreeBuilder::Verify (const DomTreeT & DT, typename DomTreeT::VerificationLevel VL)
Definition at line 1600 of file GenericDomTreeConstruction.h.
References llvm::codeview::Basic, and llvm::JumpTable::Full.
Referenced by llvm::DominatorTreeBase< BasicBlock, false >::verify().
Verify< BBDomTree >()
template bool llvm::DomTreeBuilder::Verify< BBDomTree > (const BBDomTree & DT, BBDomTree::VerificationLevel VL)
Verify< BBPostDomTree >()
template bool llvm::DomTreeBuilder::Verify< BBPostDomTree > (const BBPostDomTree & DT, BBPostDomTree::VerificationLevel VL)