LLVM: llvm::objcopy::wasm Namespace Reference
llvm::objcopy::wasm Namespace Reference
Classes
struct Object
class Reader
struct Section
class Writer
Typedefs
using SectionPred = std::function< bool(const Section &Sec)>
Functions
Error executeObjcopyOnBinary (const CommonConfig &Config, const WasmConfig &, object::WasmObjectFile &In, raw_ostream &Out)
Apply the transformations described by Config and WasmConfig to In and writes the result into Out.
static bool isDebugSection (const Section &Sec)
static bool isLinkerSection (const Section &Sec)
static bool isNameSection (const Section &Sec)
static bool isCommentSection (const Section &Sec)
static Error dumpSectionToFile (StringRef SecName, StringRef Filename, Object &Obj)
static void removeSections (const CommonConfig &Config, Object &Obj)
static Error handleArgs (const CommonConfig &Config, Object &Obj)
Typedef Documentation
SectionPred
using llvm::objcopy::wasm::SectionPred = typedef std::function<bool(const Section &Sec)>
Definition at line 22 of file WasmObjcopy.cpp.
Function Documentation
dumpSectionToFile()
static Error llvm::objcopy::wasm::dumpSectionToFile (StringRef SecName, StringRef Filename, Object & Obj) static
Definition at line 40 of file WasmObjcopy.cpp.
References llvm::ArrayRef< T >::begin(), llvm::objcopy::wasm::Section::Contents, copy, llvm::FileOutputBuffer::create(), llvm::createStringError(), E, llvm::ArrayRef< T >::end(), llvm::invalid_argument, move, llvm::objcopy::wasm::Section::Name, llvm::objcopy::wasm::Object::Sections, llvm::ArrayRef< T >::size(), llvm::StringRef::str(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by handleArgs().
executeObjcopyOnBinary()
Error llvm::objcopy::wasm::executeObjcopyOnBinary (const CommonConfig & Config, const WasmConfig & , object::WasmObjectFile & In, raw_ostream & Out)
Apply the transformations described by Config and WasmConfig to In and writes the result into Out.
Returns
any Error encountered whilst performing the operation.
Definition at line 144 of file WasmObjcopy.cpp.
References assert(), llvm::objcopy::wasm::Reader::create(), llvm::createFileError(), E, llvm::Expected< T >::get(), handleArgs(), llvm::tgtok::In, llvm::objcopy::CommonConfig::InputFilename, move, llvm::objcopy::CommonConfig::OutputFilename, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::objcopy::wasm::Writer::write().
Referenced by llvm::objcopy::executeObjcopyOnBinary().
handleArgs()
static Error llvm::objcopy::wasm::handleArgs (const CommonConfig & Config, Object & Obj) static
Definition at line 112 of file WasmObjcopy.cpp.
References llvm::objcopy::CommonConfig::AddSection, llvm::objcopy::wasm::Object::addSectionWithOwnedContents(), llvm::objcopy::wasm::Section::Contents, llvm::createFileError(), llvm::objcopy::CommonConfig::DumpSection, dumpSectionToFile(), E, llvm::MemoryBuffer::getMemBufferCopy(), move, llvm::objcopy::wasm::Section::Name, removeSections(), llvm::objcopy::NewSectionInfo::SectionData, llvm::objcopy::NewSectionInfo::SectionName, llvm::objcopy::wasm::Section::SectionType, llvm::Error::success(), and llvm::wasm::WASM_SEC_CUSTOM.
Referenced by executeObjcopyOnBinary().
isCommentSection()
static bool llvm::objcopy::wasm::isCommentSection (const Section & Sec) static
Definition at line 36 of file WasmObjcopy.cpp.
References llvm::objcopy::wasm::Section::Name.
Referenced by removeSections().
isDebugSection()
static bool llvm::objcopy::wasm::isDebugSection (const Section & Sec) static
Definition at line 24 of file WasmObjcopy.cpp.
References llvm::objcopy::wasm::Section::Name, and llvm::StringRef::startswith().
Referenced by removeSections().
isLinkerSection()
static bool llvm::objcopy::wasm::isLinkerSection (const Section & Sec) static
Definition at line 28 of file WasmObjcopy.cpp.
References llvm::objcopy::wasm::Section::Name, and llvm::StringRef::startswith().
Referenced by removeSections().
isNameSection()
static bool llvm::objcopy::wasm::isNameSection (const Section & Sec) static
Definition at line 32 of file WasmObjcopy.cpp.
References llvm::objcopy::wasm::Section::Name.
Referenced by removeSections().
removeSections()
static void llvm::objcopy::wasm::removeSections (const CommonConfig & Config, Object & Obj) static
Definition at line 60 of file WasmObjcopy.cpp.
References llvm::objcopy::NameMatcher::empty(), isCommentSection(), isDebugSection(), isLinkerSection(), isNameSection(), llvm::objcopy::CommonConfig::KeepSection, llvm::objcopy::NameMatcher::matches(), llvm::objcopy::CommonConfig::OnlyKeepDebug, llvm::objcopy::CommonConfig::OnlySection, llvm::objcopy::wasm::Object::removeSections(), llvm::objcopy::CommonConfig::StripAll, llvm::objcopy::CommonConfig::StripDebug, and llvm::objcopy::CommonConfig::ToRemove.
Referenced by handleArgs().