LLVM: llvm::yaml Namespace Reference
llvm::yaml Namespace Reference
Classes
struct AArch64FunctionInfo
class AliasNode
Represents an alias to a Node with an anchor.
class basic_collection_iterator
This is an iterator abstraction over YAML collections shared by both sequences and maps.
class BinaryRef
Specialized YAMLIO scalar type for representing a binary blob.
class BlockScalarNode
A block scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
struct BlockScalarTraits< BlockStringValue >
struct BlockScalarTraits< MinidumpYAML::BlockStringRef >
struct BlockScalarTraits< Module >
This struct serializes the LLVM IR module.
struct BlockScalarTraits< StringBlockVal >
struct BlockStringValue
struct CallSiteInfo
Serializable representation of CallSiteInfo.
struct CustomMappingTraits< BBNumberMap >
struct CustomMappingTraits< GlobalValueSummaryMapTy >
struct CustomMappingTraits< MapDocNode >
YAMLIO for MapDocNode.
struct CustomMappingTraits< std::map< std::vector< uint64_t >, WholeProgramDevirtResolution::ByArg > >
struct CustomMappingTraits< std::map< uint64_t, WholeProgramDevirtResolution > >
struct CustomMappingTraits< TypeIdSummaryMapTy >
struct DebugValueSubstitution
Serializable representation of debug value substitutions.
class Document
A YAML Stream is a sequence of Documents.
class document_iterator
Iterator abstraction for Documents over a Stream.
struct DocumentListTraits< std::vector< const MachO::InterfaceFile * > >
struct FixedMachineStackObject
Serializable representation of the fixed stack object from the MachineFrameInfo class.
struct FlowStringValue
struct FrameIndex
A serializaable representation of a reference to a stack object or fixed stack object.
struct FunctionSummaryYaml
class KeyValueNode
A key and value pair.
struct MachineConstantPoolValue
struct MachineFrameInfo
Serializable representation of MachineFrameInfo.
struct MachineFunction
struct MachineFunctionInfo
Targets should override this in a way that mirrors the implementation of llvm::MachineFunctionInfo.
struct MachineFunctionLiveIn
struct MachineJumpTable
struct MachineStackObject
Serializable representation of stack object from the MachineFrameInfo class.
struct MappingContextTraits< MetadataSection, MetadataSection::Option >
struct MappingContextTraits< minidump::MemoryDescriptor, BinaryRef >
class MappingNode
Represents a YAML map created from either a block map for a flow map.
struct MappingTraits
struct MappingTraits< AArch64FunctionInfo >
struct MappingTraits< ArchYAML::Archive >
struct MappingTraits< ArchYAML::Archive::Child >
struct MappingTraits< Argument >
Implement this as a mapping for now to get proper quotation for the value.
struct MappingTraits< CallSiteInfo >
struct MappingTraits< CallSiteInfo::ArgRegPair >
struct MappingTraits< COFF::AuxiliarybfAndefSymbol >
struct MappingTraits< COFF::AuxiliaryCLRToken >
struct MappingTraits< COFF::AuxiliaryFunctionDefinition >
struct MappingTraits< COFF::AuxiliarySectionDefinition >
struct MappingTraits< COFF::AuxiliaryWeakExternal >
struct MappingTraits< COFF::DataDirectory >
struct MappingTraits< COFF::header >
struct MappingTraits< COFFYAML::Object >
struct MappingTraits< COFFYAML::PEHeader >
struct MappingTraits< COFFYAML::Relocation >
struct MappingTraits< COFFYAML::Section >
struct MappingTraits< COFFYAML::Symbol >
struct MappingTraits< const InterfaceFile * >
struct MappingTraits< DebugValueSubstitution >
struct MappingTraits< DXContainerYAML::DXILProgram >
struct MappingTraits< DXContainerYAML::FileHeader >
struct MappingTraits< DXContainerYAML::Object >
struct MappingTraits< DXContainerYAML::Part >
struct MappingTraits< DXContainerYAML::PSVInfo >
struct MappingTraits< DXContainerYAML::ResourceBindInfo >
struct MappingTraits< DXContainerYAML::ShaderFlags >
struct MappingTraits< DXContainerYAML::ShaderHash >
struct MappingTraits< DXContainerYAML::VersionTuple >
struct MappingTraits< ELFYAML::ARMIndexTableEntry >
struct MappingTraits< ELFYAML::BBAddrMapEntry >
struct MappingTraits< ELFYAML::BBAddrMapEntry::BBEntry >
struct MappingTraits< ELFYAML::CallGraphEntryWeight >
struct MappingTraits< ELFYAML::DynamicEntry >
struct MappingTraits< ELFYAML::FileHeader >
struct MappingTraits< ELFYAML::GnuHashHeader >
struct MappingTraits< ELFYAML::LinkerOption >
struct MappingTraits< ELFYAML::NoteEntry >
struct MappingTraits< ELFYAML::Object >
struct MappingTraits< ELFYAML::ProgramHeader >
struct MappingTraits< ELFYAML::Relocation >
struct MappingTraits< ELFYAML::SectionHeader >
struct MappingTraits< ELFYAML::SectionOrType >
struct MappingTraits< ELFYAML::StackSizeEntry >
struct MappingTraits< ELFYAML::Symbol >
struct MappingTraits< ELFYAML::VerdefEntry >
struct MappingTraits< ELFYAML::VernauxEntry >
struct MappingTraits< ELFYAML::VerneedEntry >
struct MappingTraits< ExportSection >
struct MappingTraits< FixedMachineStackObject >
struct MappingTraits< FunctionSummary::ConstVCall >
struct MappingTraits< FunctionSummary::VFuncId >
struct MappingTraits< FunctionSummaryYaml >
struct MappingTraits< HSAMD::Metadata >
struct MappingTraits< IFSStub >
YAML traits for ELFStub objects.
struct MappingTraits< IFSStubTriple >
YAML traits for ELFStubTriple objects.
struct MappingTraits< IFSSymbol >
YAML traits for ELFSymbol.
struct MappingTraits< IFSTarget >
struct MappingTraits< InstrProfCorrelator::CorrelationData >
struct MappingTraits< InstrProfCorrelator::Probe >
struct MappingTraits< Kernel::Arg::Metadata >
struct MappingTraits< Kernel::Attrs::Metadata >
struct MappingTraits< Kernel::CodeProps::Metadata >
struct MappingTraits< Kernel::DebugProps::Metadata >
struct MappingTraits< Kernel::Metadata >
struct MappingTraits< LeafRecordBase >
struct MappingTraits< LocalVariableAddrGap >
struct MappingTraits< LocalVariableAddrRange >
struct MappingTraits< MachineConstantPoolValue >
struct MappingTraits< MachineFrameInfo >
struct MappingTraits< MachineFunction >
struct MappingTraits< MachineFunctionLiveIn >
struct MappingTraits< MachineJumpTable >
struct MappingTraits< MachineJumpTable::Entry >
struct MappingTraits< MachineStackObject >
struct MappingTraits< MachO::build_tool_version >
struct MappingTraits< MachO::dylib >
struct MappingTraits< MachO::fvmlib >
struct MappingTraits< MachO::section >
struct MappingTraits< MachO::section_64 >
struct MappingTraits< MachOYAML::BindOpcode >
struct MappingTraits< MachOYAML::DataInCodeEntry >
struct MappingTraits< MachOYAML::ExportEntry >
struct MappingTraits< MachOYAML::FatArch >
struct MappingTraits< MachOYAML::FatHeader >
struct MappingTraits< MachOYAML::FileHeader >
struct MappingTraits< MachOYAML::LinkEditData >
struct MappingTraits< MachOYAML::LoadCommand >
struct MappingTraits< MachOYAML::NListEntry >
struct MappingTraits< MachOYAML::Object >
struct MappingTraits< MachOYAML::RebaseOpcode >
struct MappingTraits< MachOYAML::Relocation >
struct MappingTraits< MachOYAML::Section >
struct MappingTraits< MachOYAML::UniversalBinary >
struct MappingTraits< MemberRecordBase >
struct MappingTraits< ModuleSummaryIndex >
struct MappingTraits< OffloadYAML::Binary >
struct MappingTraits< OffloadYAML::Binary::Member >
struct MappingTraits< OffloadYAML::Binary::StringEntry >
struct MappingTraits< RemarkLocation >
struct MappingTraits< remarks::Remark * >
struct MappingTraits< RISCVMachineFunctionInfo >
struct MappingTraits< SIArgument >
struct MappingTraits< SIArgumentInfo >
struct MappingTraits< SIMachineFunctionInfo >
struct MappingTraits< SIMode >
struct MappingTraits< std::unique_ptr< ELFYAML::Chunk > >
struct MappingTraits< std::unique_ptr< MachineFunctionInfo > >
struct MappingTraits< std::unique_ptr< MinidumpYAML::Stream > >
struct MappingTraits< std::unique_ptr< WasmYAML::Section > >
struct MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >
struct MappingTraits< SymbolRecordBase >
struct MappingTraits< SymbolSection >
struct MappingTraits< TypeIdSummary >
struct MappingTraits< TypeTestResolution >
struct MappingTraits< UmbrellaSection >
struct MappingTraits< UndefinedSection >
struct MappingTraits< UUIDv4 >
struct MappingTraits< VirtualRegisterDefinition >
struct MappingTraits< WasmYAML::Comdat >
struct MappingTraits< WasmYAML::ComdatEntry >
struct MappingTraits< WasmYAML::DataSegment >
struct MappingTraits< WasmYAML::DylinkExportInfo >
struct MappingTraits< WasmYAML::DylinkImportInfo >
struct MappingTraits< WasmYAML::ElemSegment >
struct MappingTraits< WasmYAML::Export >
struct MappingTraits< WasmYAML::FeatureEntry >
struct MappingTraits< WasmYAML::FileHeader >
struct MappingTraits< WasmYAML::Function >
struct MappingTraits< WasmYAML::Global >
struct MappingTraits< WasmYAML::Import >
struct MappingTraits< WasmYAML::InitExpr >
struct MappingTraits< WasmYAML::InitFunction >
struct MappingTraits< WasmYAML::Limits >
struct MappingTraits< WasmYAML::LocalDecl >
struct MappingTraits< WasmYAML::NameEntry >
struct MappingTraits< WasmYAML::Object >
struct MappingTraits< WasmYAML::ProducerEntry >
struct MappingTraits< WasmYAML::Relocation >
struct MappingTraits< WasmYAML::SegmentInfo >
struct MappingTraits< WasmYAML::Signature >
struct MappingTraits< WasmYAML::SymbolInfo >
struct MappingTraits< WasmYAML::Table >
struct MappingTraits< WebAssemblyFunctionInfo >
struct MappingTraits< WholeProgramDevirtResolution >
struct MappingTraits< WholeProgramDevirtResolution::ByArg >
struct MappingTraits< XCOFFYAML::AuxiliaryHeader >
struct MappingTraits< XCOFFYAML::FileHeader >
struct MappingTraits< XCOFFYAML::Object >
struct MappingTraits< XCOFFYAML::Relocation >
struct MappingTraits< XCOFFYAML::Section >
struct MappingTraits< XCOFFYAML::StringTable >
struct MappingTraits< XCOFFYAML::Symbol >
struct MappingTraits< xray::YAMLXRayFileHeader >
struct MappingTraits< xray::YAMLXRayRecord >
struct MappingTraits< xray::YAMLXRaySledEntry >
struct MappingTraits< xray::YAMLXRayTrace >
struct MappingTraits< YamlObjectFile >
class Node
Abstract base class for all Nodes.
struct NSectionFlags
class NullNode
A null value.
struct PolymorphicTraits< DocNode >
YAMLIO for DocNode.
struct RISCVMachineFunctionInfo
struct ScalarBitSetTraits< COFF::Characteristics >
struct ScalarBitSetTraits< COFF::DLLCharacteristics >
struct ScalarBitSetTraits< COFF::SectionCharacteristics >
struct ScalarBitSetTraits< ELFYAML::ELF_EF >
struct ScalarBitSetTraits< ELFYAML::ELF_PF >
struct ScalarBitSetTraits< ELFYAML::ELF_SHF >
struct ScalarBitSetTraits< ELFYAML::MIPS_AFL_ASE >
struct ScalarBitSetTraits< ELFYAML::MIPS_AFL_FLAGS1 >
struct ScalarBitSetTraits< MachO::ArchitectureSet >
struct ScalarBitSetTraits< TBDFlags >
struct ScalarBitSetTraits< WasmYAML::LimitFlags >
struct ScalarBitSetTraits< WasmYAML::SegmentFlags >
struct ScalarBitSetTraits< WasmYAML::SymbolFlags >
struct ScalarBitSetTraits< XCOFF::SectionTypeFlags >
struct ScalarEnumerationTraits< AccessQualifier >
struct ScalarEnumerationTraits< AddressSpaceQualifier >
struct ScalarEnumerationTraits< COFF::MachineTypes >
struct ScalarEnumerationTraits< COFF::RelocationTypeAMD64 >
struct ScalarEnumerationTraits< COFF::RelocationTypeI386 >
struct ScalarEnumerationTraits< COFF::RelocationTypesARM >
struct ScalarEnumerationTraits< COFF::RelocationTypesARM64 >
struct ScalarEnumerationTraits< COFF::SymbolBaseType >
struct ScalarEnumerationTraits< COFF::SymbolComplexType >
struct ScalarEnumerationTraits< COFF::SymbolStorageClass >
struct ScalarEnumerationTraits< COFF::WindowsSubsystem >
struct ScalarEnumerationTraits< COFFYAML::AuxSymbolType >
struct ScalarEnumerationTraits< COFFYAML::COMDATType >
struct ScalarEnumerationTraits< COFFYAML::WeakExternalCharacteristics >
struct ScalarEnumerationTraits< ELFYAML::ELF_DYNTAG >
struct ScalarEnumerationTraits< ELFYAML::ELF_ELFCLASS >
struct ScalarEnumerationTraits< ELFYAML::ELF_ELFDATA >
struct ScalarEnumerationTraits< ELFYAML::ELF_ELFOSABI >
struct ScalarEnumerationTraits< ELFYAML::ELF_EM >
struct ScalarEnumerationTraits< ELFYAML::ELF_ET >
struct ScalarEnumerationTraits< ELFYAML::ELF_NT >
struct ScalarEnumerationTraits< ELFYAML::ELF_PT >
struct ScalarEnumerationTraits< ELFYAML::ELF_REL >
struct ScalarEnumerationTraits< ELFYAML::ELF_RSS >
struct ScalarEnumerationTraits< ELFYAML::ELF_SHN >
struct ScalarEnumerationTraits< ELFYAML::ELF_SHT >
struct ScalarEnumerationTraits< ELFYAML::ELF_STB >
struct ScalarEnumerationTraits< ELFYAML::ELF_STT >
struct ScalarEnumerationTraits< ELFYAML::MIPS_ABI_FP >
struct ScalarEnumerationTraits< ELFYAML::MIPS_AFL_EXT >
struct ScalarEnumerationTraits< ELFYAML::MIPS_AFL_REG >
struct ScalarEnumerationTraits< ELFYAML::MIPS_ISA >
struct ScalarEnumerationTraits< FixedMachineStackObject::ObjectType >
struct ScalarEnumerationTraits< IFSSymbolType >
YAML traits for ELFSymbolType.
struct ScalarEnumerationTraits< MachineJumpTableInfo::JTEntryKind >
struct ScalarEnumerationTraits< MachineStackObject::ObjectType >
struct ScalarEnumerationTraits< MachO::BindOpcode >
struct ScalarEnumerationTraits< MachO::LoadCommandType >
struct ScalarEnumerationTraits< MachO::ObjCConstraintType >
struct ScalarEnumerationTraits< MachO::RebaseOpcode >
struct ScalarEnumerationTraits< object::ImageKind >
struct ScalarEnumerationTraits< object::OffloadKind >
struct ScalarEnumerationTraits< TargetStackID::Value >
struct ScalarEnumerationTraits< TypeTestResolution::Kind >
struct ScalarEnumerationTraits< ValueKind >
struct ScalarEnumerationTraits< ValueType >
struct ScalarEnumerationTraits< WasmYAML::ComdatKind >
struct ScalarEnumerationTraits< WasmYAML::ExportKind >
struct ScalarEnumerationTraits< WasmYAML::FeaturePolicyPrefix >
struct ScalarEnumerationTraits< WasmYAML::Opcode >
struct ScalarEnumerationTraits< WasmYAML::RelocType >
struct ScalarEnumerationTraits< WasmYAML::SectionType >
struct ScalarEnumerationTraits< WasmYAML::SymbolKind >
struct ScalarEnumerationTraits< WasmYAML::TableType >
struct ScalarEnumerationTraits< WasmYAML::ValueType >
struct ScalarEnumerationTraits< WholeProgramDevirtResolution::ByArg::Kind >
struct ScalarEnumerationTraits< WholeProgramDevirtResolution::Kind >
struct ScalarEnumerationTraits< XCOFF::CFileStringType >
struct ScalarEnumerationTraits< XCOFF::StorageClass >
struct ScalarEnumerationTraits< XCOFF::StorageMappingClass >
struct ScalarEnumerationTraits< XCOFFYAML::AuxSymbolType >
struct ScalarEnumerationTraits< xray::RecordTypes >
struct ScalarEnumerationTraits< xray::SledEntry::FunctionKinds >
class ScalarNode
A scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
struct ScalarTraits< Align >
struct ScalarTraits< BinaryRef >
struct ScalarTraits< char_16 >
struct ScalarTraits< ELFYAML::YAMLFlowString >
struct ScalarTraits< ELFYAML::YAMLIntUInt >
struct ScalarTraits< FixedSizeHex< N > >
struct ScalarTraits< FixedSizeString< N > >
struct ScalarTraits< FlowStringRef >
struct ScalarTraits< FlowStringValue >
struct ScalarTraits< FrameIndex >
struct ScalarTraits< IFSBitWidthType >
struct ScalarTraits< IFSEndiannessType >
struct ScalarTraits< MachO::Architecture >
struct ScalarTraits< MachO::PackedVersion >
struct ScalarTraits< MachO::PlatformSet >
struct ScalarTraits< MaybeAlign >
struct ScalarTraits< StOtherPiece >
struct ScalarTraits< StringValue >
struct ScalarTraits< SwiftVersion >
struct ScalarTraits< Target >
struct ScalarTraits< UnsignedValue >
struct ScalarTraits< UUID >
struct ScalarTraits< uuid_t >
class Scanner
Scans YAML tokens from a MemoryBuffer.
struct SequenceElementTraits< ELFYAML::YAMLFlowString >
struct SequenceElementTraits< InstrProfCorrelator::Probe >
struct SequenceElementTraits< StOtherPiece >
class SequenceNode
Represents a YAML sequence created from either a block sequence for a flow sequence.
struct SequenceTraits< ArrayDocNode >
YAMLIO for ArrayNode.
struct SequenceTraits< ArrayRef< T > >
ArrayRef is not really compatible with the YAMLTraits.
struct SIArgument
struct SIArgumentInfo
struct SIMachineFunctionInfo
struct SIMode
class Stream
This class represents a YAML stream potentially containing multiple documents.
struct StringBlockVal
Helper struct for multiline string block literals.
struct StringValue
A wrapper around std::string which contains a source range that's being set during parsing.
struct TaggedScalarTraits< ScalarDocNode >
YAMLIO for ScalarDocNode.
struct Token
Token - A single YAML token.
struct UnsignedValue
A wrapper around unsigned which contains a source range that's being set during parsing.
struct VirtualRegisterDefinition
struct WebAssemblyFunctionInfo
struct YamlObjectFile
Typedefs
using char_16 = char[16]
using uuid_t = raw_ostream::uuid_t
using ErrorHandler = llvm::function_ref< void(const Twine &Msg)>
using BBNumberMap = DenseMap< int, int >
Functions
bool operator== (const BinaryRef &LHS, const BinaryRef &RHS)
bool yaml2archive (ArchYAML::Archive &Doc, raw_ostream &Out, ErrorHandler EH)
bool yaml2coff (COFFYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
bool yaml2elf (ELFYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH, uint64_t MaxSize)
bool yaml2macho (YamlObjectFile &Doc, raw_ostream &Out, ErrorHandler EH)
bool yaml2minidump (MinidumpYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
bool yaml2offload (OffloadYAML::Binary &Doc, raw_ostream &Out, ErrorHandler EH)
bool yaml2wasm (WasmYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
bool yaml2xcoff (XCOFFYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
bool yaml2dxcontainer (DXContainerYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH)
bool convertYAML (Input &YIn, raw_ostream &Out, ErrorHandler ErrHandler, unsigned DocNum=1, uint64_t MaxSize=UINT64_MAX)
std::unique_ptr< object::ObjectFile > yaml2ObjectFile (SmallVectorImpl< char > &Storage, StringRef Yaml, ErrorHandler ErrHandler)
Convenience function for tests.
bool dumpTokens (StringRef Input, raw_ostream &)
Dump all the tokens in this stream to OS.
bool scanTokens (StringRef Input)
Scans all tokens in input without outputting anything.
std::string escape (StringRef Input, bool EscapePrintable=true)
Escape Input for a double quoted scalar; if EscapePrintable is true, all UTF8 sequences will be escaped, if EscapePrintable is false, those UTF8 sequences encoding printable unicode scalars will not be escaped, but emitted verbatim.
std::optional< bool > parseBool (StringRef S)
Parse S as a bool according to https://yaml.org/type/bool.html.
template<class CollectionType >
CollectionType::iterator begin (CollectionType &C)
template<class CollectionType >
void skip (CollectionType &C)
static void commonSectionMapping (IO &IO, ELFYAML::Section &Section)
static void sectionMapping (IO &IO, ELFYAML::DynamicSection &Section)
static void sectionMapping (IO &IO, ELFYAML::RawContentSection &Section)
static void sectionMapping (IO &IO, ELFYAML::BBAddrMapSection &Section)
static void sectionMapping (IO &IO, ELFYAML::StackSizesSection &Section)
static void sectionMapping (IO &IO, ELFYAML::HashSection &Section)
static void sectionMapping (IO &IO, ELFYAML::NoteSection &Section)
static void sectionMapping (IO &IO, ELFYAML::GnuHashSection &Section)
static void sectionMapping (IO &IO, ELFYAML::NoBitsSection &Section)
static void sectionMapping (IO &IO, ELFYAML::VerdefSection &Section)
static void sectionMapping (IO &IO, ELFYAML::SymverSection &Section)
static void sectionMapping (IO &IO, ELFYAML::VerneedSection &Section)
static void sectionMapping (IO &IO, ELFYAML::RelocationSection &Section)
static void sectionMapping (IO &IO, ELFYAML::RelrSection &Section)
static void groupSectionMapping (IO &IO, ELFYAML::GroupSection &Group)
static void sectionMapping (IO &IO, ELFYAML::SymtabShndxSection &Section)
static void sectionMapping (IO &IO, ELFYAML::AddrsigSection &Section)
static void fillMapping (IO &IO, ELFYAML::Fill &Fill)
static void sectionHeaderTableMapping (IO &IO, ELFYAML::SectionHeaderTable &SHT)
static void sectionMapping (IO &IO, ELFYAML::LinkerOptionsSection &Section)
static void sectionMapping (IO &IO, ELFYAML::DependentLibrariesSection &Section)
static void sectionMapping (IO &IO, ELFYAML::CallGraphProfileSection &Section)
static void sectionMapping (IO &IO, ELFYAML::ARMIndexTableSection &Section)
static void sectionMapping (IO &IO, ELFYAML::MipsABIFlags &Section)
static StringRef getStringValue (IO &IO, const char *Key)
static void setStringValue (IO &IO, const char *Key, StringRef Val)
static bool isInteger (StringRef Val)
template<typename StructType >
void mapLoadCommandData (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::segment_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::segment_command_64 > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::dylib_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::rpath_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::dylinker_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::sub_framework_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::sub_umbrella_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::sub_client_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::sub_library_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
template<>
void mapLoadCommandData< MachO::build_version_command > (IO &IO, MachOYAML::LoadCommand &LoadCommand)
static void commonSectionMapping (IO &IO, WasmYAML::Section &Section)
static void sectionMapping (IO &IO, WasmYAML::DylinkSection &Section)
static void sectionMapping (IO &IO, WasmYAML::NameSection &Section)
static void sectionMapping (IO &IO, WasmYAML::LinkingSection &Section)
static void sectionMapping (IO &IO, WasmYAML::ProducersSection &Section)
static void sectionMapping (IO &IO, WasmYAML::TargetFeaturesSection &Section)
static void sectionMapping (IO &IO, WasmYAML::CustomSection &Section)
static void sectionMapping (IO &IO, WasmYAML::TypeSection &Section)
static void sectionMapping (IO &IO, WasmYAML::ImportSection &Section)
static void sectionMapping (IO &IO, WasmYAML::FunctionSection &Section)
static void sectionMapping (IO &IO, WasmYAML::TableSection &Section)
static void sectionMapping (IO &IO, WasmYAML::MemorySection &Section)
static void sectionMapping (IO &IO, WasmYAML::TagSection &Section)
static void sectionMapping (IO &IO, WasmYAML::GlobalSection &Section)
static void sectionMapping (IO &IO, WasmYAML::ExportSection &Section)
static void sectionMapping (IO &IO, WasmYAML::StartSection &Section)
static void sectionMapping (IO &IO, WasmYAML::ElemSection &Section)
static void sectionMapping (IO &IO, WasmYAML::CodeSection &Section)
static void sectionMapping (IO &IO, WasmYAML::DataSection &Section)
static void sectionMapping (IO &IO, WasmYAML::DataCountSection &Section)
static void auxSymMapping (IO &IO, XCOFFYAML::CsectAuxEnt &AuxSym, bool Is64)
static void auxSymMapping (IO &IO, XCOFFYAML::FileAuxEnt &AuxSym)
static void auxSymMapping (IO &IO, XCOFFYAML::BlockAuxEnt &AuxSym, bool Is64)
static void auxSymMapping (IO &IO, XCOFFYAML::FunctionAuxEnt &AuxSym, bool Is64)
static void auxSymMapping (IO &IO, XCOFFYAML::ExcpetionAuxEnt &AuxSym)
static void auxSymMapping (IO &IO, XCOFFYAML::SectAuxEntForDWARF &AuxSym)
static void auxSymMapping (IO &IO, XCOFFYAML::SectAuxEntForStat &AuxSym)
bool convertYAML (yaml::Input &YIn, raw_ostream &Out, ErrorHandler ErrHandler, unsigned DocNum, uint64_t MaxSize)
Typedef Documentation
BBNumberMap
using llvm::yaml::BBNumberMap = typedef DenseMap<int, int>
Definition at line 188 of file WebAssemblyMachineFunctionInfo.h.
char_16
using llvm::yaml::char_16 = typedef char[16]
Definition at line 298 of file MachOYAML.h.
ErrorHandler
using llvm::yaml::ErrorHandler = typedef llvm::function_ref<void(const Twine &Msg)>
Definition at line 63 of file yaml2obj.h.
uuid_t
using llvm::yaml::uuid_t = typedef raw_ostream::uuid_t
Definition at line 308 of file MachOYAML.h.
Function Documentation
auxSymMapping() [1/7]
static void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::BlockAuxEnt & AuxSym, bool Is64) static
Definition at line 248 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::BlockAuxEnt::LineNum, llvm::XCOFFYAML::BlockAuxEnt::LineNumHi, and llvm::XCOFFYAML::BlockAuxEnt::LineNumLo.
auxSymMapping() [2/7]
static void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::CsectAuxEnt & AuxSym, bool Is64) static
Definition at line 228 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::CsectAuxEnt::ParameterHashIndex, llvm::XCOFFYAML::CsectAuxEnt::SectionOrLength, llvm::XCOFFYAML::CsectAuxEnt::SectionOrLengthHi, llvm::XCOFFYAML::CsectAuxEnt::SectionOrLengthLo, llvm::XCOFFYAML::CsectAuxEnt::StabInfoIndex, llvm::XCOFFYAML::CsectAuxEnt::StabSectNum, llvm::XCOFFYAML::CsectAuxEnt::StorageMappingClass, llvm::XCOFFYAML::CsectAuxEnt::SymbolAlignmentAndType, and llvm::XCOFFYAML::CsectAuxEnt::TypeChkSectNum.
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >::mapping().
auxSymMapping() [3/7]
static void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::ExcpetionAuxEnt & AuxSym) static
Definition at line 266 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::ExcpetionAuxEnt::OffsetToExceptionTbl, llvm::XCOFFYAML::ExcpetionAuxEnt::SizeOfFunction, and llvm::XCOFFYAML::ExcpetionAuxEnt::SymIdxOfNextBeyond.
auxSymMapping() [4/7]
static void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::FileAuxEnt & AuxSym) static
Definition at line 243 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::FileAuxEnt::FileNameOrString, and llvm::XCOFFYAML::FileAuxEnt::FileStringType.
auxSymMapping() [5/7]
static void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::FunctionAuxEnt & AuxSym, bool Is64) static
Definition at line 257 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::FunctionAuxEnt::OffsetToExceptionTbl, llvm::XCOFFYAML::FunctionAuxEnt::PtrToLineNum, llvm::XCOFFYAML::FunctionAuxEnt::SizeOfFunction, and llvm::XCOFFYAML::FunctionAuxEnt::SymIdxOfNextBeyond.
auxSymMapping() [6/7]
static void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::SectAuxEntForDWARF & AuxSym) static
Definition at line 272 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::SectAuxEntForDWARF::LengthOfSectionPortion, and llvm::XCOFFYAML::SectAuxEntForDWARF::NumberOfRelocEnt.
auxSymMapping() [7/7]
static void llvm::yaml::auxSymMapping (IO & IO, XCOFFYAML::SectAuxEntForStat & AuxSym) static
Definition at line 277 of file XCOFFYAML.cpp.
References llvm::XCOFFYAML::SectAuxEntForStat::NumberOfLineNum, llvm::XCOFFYAML::SectAuxEntForStat::NumberOfRelocEnt, and llvm::XCOFFYAML::SectAuxEntForStat::SectionLength.
begin()
template<class CollectionType > CollectionType::iterator llvm::yaml::begin (CollectionType & C)
Definition at line 390 of file YAMLParser.h.
References assert(), and ret().
Referenced by llvm::yaml::MappingNode::begin(), llvm::yaml::SequenceNode::begin(), and skip().
commonSectionMapping() [1/2]
static void llvm::yaml::commonSectionMapping (IO & IO, ELFYAML::Section & Section) static
Definition at line 1325 of file ELFYAML.cpp.
References assert().
Referenced by groupSectionMapping(), and sectionMapping().
commonSectionMapping() [2/2]
static void llvm::yaml::commonSectionMapping (IO & IO, WasmYAML::Section & Section) static
Definition at line 45 of file WasmYAML.cpp.
convertYAML() [1/2]
bool llvm::yaml::convertYAML (Input & YIn, raw_ostream & Out, ErrorHandler ErrHandler, unsigned DocNum = 1, uint64_t MaxSize = UINT64_MAX)
Referenced by yaml2ObjectFile().
convertYAML() [2/2]
bool llvm::yaml::convertYAML (yaml::Input & YIn, raw_ostream & Out, ErrorHandler ErrHandler, unsigned DocNum, uint64_t MaxSize)
Definition at line 21 of file yaml2obj.cpp.
References yaml2archive(), yaml2coff(), yaml2dxcontainer(), yaml2elf(), yaml2macho(), yaml2minidump(), yaml2offload(), yaml2wasm(), and yaml2xcoff().
dumpTokens()
bool llvm::yaml::dumpTokens (StringRef Input, raw_ostream & OS)
Dump all the tokens in this stream to OS.
Returns
true if there was an error, false otherwise.
Definition at line 600 of file YAMLParser.cpp.
References llvm::yaml::Scanner::getNext(), OS, llvm::yaml::Token::TK_Alias, llvm::yaml::Token::TK_Anchor, llvm::yaml::Token::TK_BlockEnd, llvm::yaml::Token::TK_BlockEntry, llvm::yaml::Token::TK_BlockMappingStart, llvm::yaml::Token::TK_BlockScalar, llvm::yaml::Token::TK_BlockSequenceStart, llvm::yaml::Token::TK_DocumentEnd, llvm::yaml::Token::TK_DocumentStart, llvm::yaml::Token::TK_Error, llvm::yaml::Token::TK_FlowEntry, llvm::yaml::Token::TK_FlowMappingEnd, llvm::yaml::Token::TK_FlowMappingStart, llvm::yaml::Token::TK_FlowSequenceEnd, llvm::yaml::Token::TK_FlowSequenceStart, llvm::yaml::Token::TK_Key, llvm::yaml::Token::TK_Scalar, llvm::yaml::Token::TK_StreamEnd, llvm::yaml::Token::TK_StreamStart, llvm::yaml::Token::TK_Tag, llvm::yaml::Token::TK_TagDirective, llvm::yaml::Token::TK_Value, and llvm::yaml::Token::TK_VersionDirective.
escape()
std::string llvm::yaml::escape (StringRef Input, bool EscapePrintable = true)
Escape Input for a double quoted scalar; if EscapePrintable is true, all UTF8 sequences will be escaped, if EscapePrintable is false, those UTF8 sequences encoding printable unicode scalars will not be escaped, but emitted verbatim.
Definition at line 697 of file YAMLParser.cpp.
References llvm::append_range(), llvm::StringRef::begin(), decodeUTF8(), llvm::numbers::e, encodeUTF8(), llvm::StringRef::end(), i, and llvm::sys::unicode::isPrintable().
fillMapping()
static void llvm::yaml::fillMapping (IO & IO, ELFYAML::Fill & Fill) static
Definition at line 1457 of file ELFYAML.cpp.
References llvm::ELFYAML::Chunk::Name, llvm::ELFYAML::Chunk::Offset, llvm::ELFYAML::Fill::Pattern, and llvm::ELFYAML::Fill::Size.
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping().
getStringValue()
static StringRef llvm::yaml::getStringValue (IO & IO, const char * Key) static
Definition at line 1518 of file ELFYAML.cpp.
Referenced by llvm::AttributeImpl::getValueAsString(), llvm::yaml::MappingTraits< ELFYAML::ARMIndexTableEntry >::mapping(), and llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping().
groupSectionMapping()
static void llvm::yaml::groupSectionMapping (IO & IO, ELFYAML::GroupSection & Group) static
Definition at line 1441 of file ELFYAML.cpp.
References commonSectionMapping(), llvm::ELFYAML::GroupSection::Members, and llvm::ELFYAML::GroupSection::Signature.
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping().
isInteger()
static bool llvm::yaml::isInteger (StringRef Val) static
Definition at line 1528 of file ELFYAML.cpp.
References llvm::StringRef::getAsInteger().
Referenced by emitConjunctionRec(), llvm::NVPTXTargetLowering::LowerCall(), llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping(), and llvm::PatchLocation::set().
mapLoadCommandData()
template<typename StructType > void llvm::yaml::mapLoadCommandData (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 219 of file MachOYAML.cpp.
mapLoadCommandData< MachO::build_version_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::build_version_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 276 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Tools.
mapLoadCommandData< MachO::dylib_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::dylib_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 234 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content.
mapLoadCommandData< MachO::dylinker_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::dylinker_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 246 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content.
mapLoadCommandData< MachO::rpath_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::rpath_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 240 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content.
mapLoadCommandData< MachO::segment_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::segment_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 222 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Sections.
mapLoadCommandData< MachO::segment_command_64 >()
template<> void llvm::yaml::mapLoadCommandData< MachO::segment_command_64 > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 228 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Sections.
mapLoadCommandData< MachO::sub_client_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::sub_client_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 264 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content.
mapLoadCommandData< MachO::sub_framework_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::sub_framework_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 252 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content.
mapLoadCommandData< MachO::sub_library_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::sub_library_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 270 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content.
mapLoadCommandData< MachO::sub_umbrella_command >()
template<> void llvm::yaml::mapLoadCommandData< MachO::sub_umbrella_command > (IO & IO, MachOYAML::LoadCommand & LoadCommand)
Definition at line 258 of file MachOYAML.cpp.
References llvm::MachOYAML::LoadCommand::Content.
operator==()
bool llvm::yaml::operator== (const BinaryRef & LHS, const BinaryRef & RHS) inline
Definition at line 98 of file YAML.h.
References LHS, and RHS.
parseBool()
std::optional< bool > llvm::yaml::parseBool (StringRef S)
Parse S as a bool according to https://yaml.org/type/bool.html.
Definition at line 763 of file YAMLParser.cpp.
References S.
scanTokens()
bool llvm::yaml::scanTokens (StringRef Input)
Scans all tokens in input without outputting anything.
This is used for benchmarking the tokenizer.
Returns
true if there was an error, false otherwise.
Definition at line 684 of file YAMLParser.cpp.
References llvm::yaml::Scanner::getNext(), llvm::yaml::Token::TK_Error, and llvm::yaml::Token::TK_StreamEnd.
sectionHeaderTableMapping()
static void llvm::yaml::sectionHeaderTableMapping (IO & IO, ELFYAML::SectionHeaderTable & SHT) static
Definition at line 1464 of file ELFYAML.cpp.
References llvm::ELFYAML::SectionHeaderTable::Excluded, llvm::ELFYAML::SectionHeaderTable::NoHeaders, llvm::ELFYAML::Chunk::Offset, and llvm::ELFYAML::SectionHeaderTable::Sections.
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping().
sectionMapping() [1/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::AddrsigSection & Section) static
Definition at line 1452 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [2/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::ARMIndexTableSection & Section) static
Definition at line 1493 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [3/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::BBAddrMapSection & Section) static
Definition at line 1373 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [4/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::CallGraphProfileSection & Section) static
Definition at line 1483 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [5/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::DependentLibrariesSection & Section) static
Definition at line 1477 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [6/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::DynamicSection & Section) static
Definition at line 1352 of file ELFYAML.cpp.
References commonSectionMapping().
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< WasmYAML::Section > >::mapping(), and llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping().
sectionMapping() [7/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::GnuHashSection & Section) static
Definition at line 1402 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [8/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::HashSection & Section) static
Definition at line 1384 of file ELFYAML.cpp.
References assert(), and commonSectionMapping().
sectionMapping() [9/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::LinkerOptionsSection & Section) static
Definition at line 1472 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [10/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::MipsABIFlags & Section) static
Definition at line 1498 of file ELFYAML.cpp.
References llvm::Mips::AFL_EXT_NONE, llvm::Mips::AFL_REG_NONE, commonSectionMapping(), and llvm::Mips::Val_GNU_MIPS_ABI_FP_ANY.
sectionMapping() [11/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::NoBitsSection & Section) static
Definition at line 1409 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [12/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::NoteSection & Section) static
Definition at line 1396 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [13/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::RawContentSection & Section) static
Definition at line 1357 of file ELFYAML.cpp.
References assert(), and commonSectionMapping().
sectionMapping() [14/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::RelocationSection & Section) static
Definition at line 1430 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [15/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::RelrSection & Section) static
Definition at line 1436 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [16/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::StackSizesSection & Section) static
Definition at line 1379 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [17/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::SymtabShndxSection & Section) static
Definition at line 1447 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [18/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::SymverSection & Section) static
Definition at line 1419 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [19/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::VerdefSection & Section) static
Definition at line 1413 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [20/39]
static void llvm::yaml::sectionMapping (IO & IO, ELFYAML::VerneedSection & Section) static
Definition at line 1424 of file ELFYAML.cpp.
References commonSectionMapping().
sectionMapping() [21/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::CodeSection & Section) static
Definition at line 150 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [22/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::CustomSection & Section) static
Definition at line 94 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [23/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::DataCountSection & Section) static
Definition at line 160 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [24/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::DataSection & Section) static
Definition at line 155 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [25/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::DylinkSection & Section) static
Definition at line 50 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [26/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::ElemSection & Section) static
Definition at line 145 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [27/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::ExportSection & Section) static
Definition at line 135 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [28/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::FunctionSection & Section) static
Definition at line 110 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [29/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::GlobalSection & Section) static
Definition at line 130 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [30/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::ImportSection & Section) static
Definition at line 105 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [31/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::LinkingSection & Section) static
Definition at line 70 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [32/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::MemorySection & Section) static
Definition at line 120 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [33/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::NameSection & Section) static
Definition at line 62 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [34/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::ProducersSection & Section) static
Definition at line 80 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [35/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::StartSection & Section) static
Definition at line 140 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [36/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::TableSection & Section) static
Definition at line 115 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [37/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::TagSection & Section) static
Definition at line 125 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [38/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::TargetFeaturesSection & Section) static
Definition at line 88 of file WasmYAML.cpp.
References commonSectionMapping().
sectionMapping() [39/39]
static void llvm::yaml::sectionMapping (IO & IO, WasmYAML::TypeSection & Section) static
Definition at line 100 of file WasmYAML.cpp.
References commonSectionMapping().
setStringValue()
static void llvm::yaml::setStringValue (IO & IO, const char * Key, StringRef Val) static
Definition at line 1524 of file ELFYAML.cpp.
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping().
skip()
template<class CollectionType > void llvm::yaml::skip (CollectionType & C)
Definition at line 398 of file YAMLParser.h.
References assert(), begin(), llvm::numbers::e, and i.
Referenced by llvm::yaml::MappingNode::skip(), and llvm::yaml::SequenceNode::skip().
yaml2archive()
bool llvm::yaml::yaml2archive (ArchYAML::Archive & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 20 of file ArchiveEmitter.cpp.
References llvm::ArchYAML::Archive::Content, llvm::StringRef::data(), I, llvm::ArchYAML::Archive::Magic, llvm::ArchYAML::Archive::Members, P, llvm::StringRef::size(), and llvm::raw_ostream::write().
Referenced by convertYAML().
yaml2coff()
bool llvm::yaml::yaml2coff (COFFYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 595 of file COFFEmitter.cpp.
References llvm::HexagonISD::CP, layoutCOFF(), layoutOptionalHeader(), and writeCOFF().
Referenced by convertYAML().
yaml2dxcontainer()
bool llvm::yaml::yaml2dxcontainer (DXContainerYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 232 of file DXContainerEmitter.cpp.
Referenced by convertYAML().
yaml2elf()
bool llvm::yaml::yaml2elf (ELFYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH, uint64_t MaxSize)
Definition at line 1987 of file ELFEmitter.cpp.
References llvm::ELFYAML::FileHeader::Class, llvm::ELFYAML::FileHeader::Data, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, and llvm::ELFYAML::Object::Header.
Referenced by convertYAML().
yaml2macho()
bool llvm::yaml::yaml2macho (YamlObjectFile & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 746 of file MachOEmitter.cpp.
Referenced by convertYAML().
yaml2minidump()
bool llvm::yaml::yaml2minidump (MinidumpYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 230 of file MinidumpEmitter.cpp.
References llvm::ArrayRef(), llvm::enumerate(), llvm::MinidumpYAML::Object::Header, layout(), llvm::minidump::Header::NumberOfStreams, llvm::minidump::Header::StreamDirectoryRVA, and llvm::MinidumpYAML::Object::Streams.
Referenced by convertYAML().
yaml2ObjectFile()
std::unique_ptr< object::ObjectFile > llvm::yaml::yaml2ObjectFile (SmallVectorImpl< char > & Storage, StringRef Yaml, ErrorHandler ErrHandler)
Convenience function for tests.
Definition at line 65 of file yaml2obj.cpp.
References llvm::SmallVectorImpl< T >::clear(), convertYAML(), llvm::object::ObjectFile::createObjectFile(), move, OS, llvm::Expected< T >::takeError(), and llvm::toString().
yaml2offload()
bool llvm::yaml::yaml2offload (OffloadYAML::Binary & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 21 of file OffloadEmitter.cpp.
References llvm::OffloadYAML::Binary::Members.
Referenced by convertYAML().
yaml2wasm()
bool llvm::yaml::yaml2wasm (WasmYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 678 of file WasmEmitter.cpp.
Referenced by convertYAML().
yaml2xcoff()
bool llvm::yaml::yaml2xcoff (XCOFFYAML::Object & Doc, raw_ostream & Out, ErrorHandler EH)
Definition at line 779 of file XCOFFEmitter.cpp.
Referenced by convertYAML().