LLVM: shuffles Namespace Reference
shuffles Namespace Reference
Typedefs
using MaskT = SmallVector< int, 128 >
Functions
ArrayRef< int > lo (ArrayRef< int > Vuu)
ArrayRef< int > hi (ArrayRef< int > Vuu)
MaskT vshuffvdd (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Rt)
MaskT vdealvdd (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Rt)
MaskT vpack (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Size, bool TakeOdd)
MaskT vshuff (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Size, bool TakeOdd)
MaskT vdeal (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Size, bool TakeOdd)
MaskT vdealb4w (ArrayRef< int > Vu, ArrayRef< int > Vv)
template<typename ShuffFunc , typename... OptArgs>
auto mask (ShuffFunc S, unsigned Length, OptArgs... args) -> MaskT
Typedef Documentation
MaskT
using shuffles::MaskT = typedef SmallVector<int, 128>
Definition at line 805 of file HexagonISelDAGToDAGHVX.cpp.
Function Documentation
hi()
ArrayRef<int> shuffles::hi (ArrayRef< int > Vuu)
Definition at line 814 of file HexagonISelDAGToDAGHVX.cpp.
References llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::take_back().
Referenced by combineX86ShuffleChainWithExtract(), EmitHiLo(), emitHiLo(), llvm::HexagonEvaluator::evaluate(), parseHexOcta(), resolveTargetShuffleInputsAndMask(), and vdeal().
lo()
ArrayRef<int> shuffles::lo (ArrayRef< int > Vuu)
Definition at line 813 of file HexagonISelDAGToDAGHVX.cpp.
References llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::take_front().
Referenced by combineX86ShuffleChainWithExtract(), EmitHiLo(), emitHiLo(), llvm::HexagonEvaluator::evaluate(), llvm::Mips16InstrInfo::loadImmediate(), parseHexOcta(), resolveTargetShuffleInputsAndMask(), and vdeal().
mask()
template<typename ShuffFunc , typename... OptArgs> auto shuffles::mask (ShuffFunc S, unsigned Length, OptArgs... args) -> MaskT
Definition at line 903 of file HexagonISelDAGToDAGHVX.cpp.
References args, llvm::Length, and S.
Referenced by llvm::AVRAsmBackend::applyFixup(), blend_epi16(), DecodeIT(), foo(), get_cpu_features(), llvm::DomainValue::getCommonDomains(), llvm::APInt::insertBits(), load_counters(), load_counters16(), load_counters4(), load_counters8(), llvm::PatternMatch::m_Shuffle(), llvm::HexagonEvaluator::mask(), llvm::APInt::setBits(), llvm::APInt::tcDivide(), and llvm::APInt::tcExtract().
vdeal()
MaskT shuffles::vdeal (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Size, bool TakeOdd)
Definition at line 884 of file HexagonISelDAGToDAGHVX.cpp.
References hi(), lo(), llvm::ArrayRef< T >::size(), vdealvdd(), and vpack().
vdealb4w()
MaskT shuffles::vdealb4w (ArrayRef< int > Vu, ArrayRef< int > Vv)
Definition at line 890 of file HexagonISelDAGToDAGHVX.cpp.
References llvm::numbers::e, i, and llvm::ArrayRef< T >::size().
vdealvdd()
MaskT shuffles::vdealvdd (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Rt)
Definition at line 836 of file HexagonISelDAGToDAGHVX.cpp.
References llvm::ArrayRef< T >::begin(), copy, llvm::ArrayRef< T >::end(), i, llvm::Offset, llvm::ArrayRef< T >::size(), std::swap(), llvm::MutableArrayRef< T >::take_back(), and llvm::MutableArrayRef< T >::take_front().
Referenced by vdeal().
vpack()
MaskT shuffles::vpack (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Size, bool TakeOdd)
Definition at line 856 of file HexagonISelDAGToDAGHVX.cpp.
References b, llvm::numbers::e, i, and llvm::ArrayRef< T >::size().
Referenced by vdeal().
vshuff()
MaskT shuffles::vshuff (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Size, bool TakeOdd)
Definition at line 871 of file HexagonISelDAGToDAGHVX.cpp.
References b, llvm::numbers::e, i, and llvm::ArrayRef< T >::size().
vshuffvdd()
MaskT shuffles::vshuffvdd (ArrayRef< int > Vu, ArrayRef< int > Vv, unsigned Rt)
Definition at line 816 of file HexagonISelDAGToDAGHVX.cpp.
References llvm::ArrayRef< T >::begin(), copy, llvm::ArrayRef< T >::end(), i, llvm::Offset, llvm::ArrayRef< T >::size(), std::swap(), llvm::MutableArrayRef< T >::take_back(), and llvm::MutableArrayRef< T >::take_front().