LLVM: llvm::sys::locale Namespace Reference
llvm::sys::locale Namespace Reference
Functions
int columnWidth (StringRef s)
bool isPrint (int c)
Function Documentation
columnWidth()
int llvm::sys::locale::columnWidth (StringRef s)
Definition at line 9 of file Locale.cpp.
References llvm::sys::unicode::columnWidthUTF8().
Referenced by buildFixItLine().
isPrint()
bool llvm::sys::locale::isPrint (int c)
Definition at line 13 of file Locale.cpp.
References llvm::sys::unicode::isPrintable().
Referenced by llvm::isHeader(), isPrintableString(), llvm::raw_ostream::operator<<(), PrintByteList(), and llvm::raw_ostream::write_escaped().