LLVM: llvm::compression Namespace Reference
llvm::compression Namespace Reference
Namespaces
zlib
zstd
Classes
struct Params
Enumerations
enum Format { Format::Zlib, Format::Zstd }
Functions
Format formatFor (DebugCompressionType Type)
const char * getReasonIfUnsupported (Format F)
void compress (Params P, ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > &Output)
Error decompress (DebugCompressionType T, ArrayRef< uint8_t > Input, uint8_t *Output, size_t UncompressedSize)
Error decompress (Format F, ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > &Output, size_t UncompressedSize)
Error decompress (DebugCompressionType T, ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > &Output, size_t UncompressedSize)
Enumeration Type Documentation
Format
enum llvm::compression::Format strong
Enumerator
Zlib
Zstd
Definition at line 76 of file Compression.h.
Function Documentation
compress()
void llvm::compression::compress (Params P, ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > & Output)
Definition at line 46 of file Compression.cpp.
References llvm::compression::zlib::compress(), llvm::compression::zstd::compress(), P, Zlib, and Zstd.
Referenced by llvm::objcopy::elf::CompressedSection::CompressedSection().
decompress() [1/3]
Error llvm::compression::decompress (DebugCompressionType T, ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > & Output, size_t UncompressedSize)
Definition at line 81 of file Compression.cpp.
References decompress(), and formatFor().
decompress() [2/3]
Error llvm::compression::decompress (DebugCompressionType T, ArrayRef< uint8_t > Input, uint8_t * Output, size_t UncompressedSize)
Definition at line 58 of file Compression.cpp.
References llvm::compression::zlib::decompress(), llvm::compression::zstd::decompress(), formatFor(), llvm_unreachable, Zlib, and Zstd.
Referenced by llvm::object::Decompressor::decompress(), decompress(), and llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit().
decompress() [3/3]
Error llvm::compression::decompress (compression::Format F, ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > & Output, size_t UncompressedSize)
Definition at line 69 of file Compression.cpp.
References llvm::compression::zlib::decompress(), llvm::compression::zstd::decompress(), F, llvm_unreachable, Zlib, and Zstd.
formatFor()
Format llvm::compression::formatFor (DebugCompressionType Type) inline
Definition at line 81 of file Compression.h.
References llvm_unreachable, llvm::None, llvm::Zlib, Zlib, llvm::Zstd, and Zstd.
Referenced by decompress(), and llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit().
getReasonIfUnsupported()
const char * llvm::compression::getReasonIfUnsupported (compression::Format F)
Definition at line 30 of file Compression.cpp.
References F, llvm::compression::zlib::isAvailable(), llvm::compression::zstd::isAvailable(), llvm_unreachable, Zlib, and Zstd.
Referenced by llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit().