LLVM: llvm::adl_detail Namespace Reference
llvm::adl_detail Namespace Reference
Functions
template<typename ContainerTy >
decltype(auto) adl_begin (ContainerTy &&container)
template<typename ContainerTy >
decltype(auto) adl_end (ContainerTy &&container)
template<typename T >
void adl_swap (T &&lhs, T &&rhs) noexcept(noexcept(swap(std::declval< T >(), std::declval< T >())))
Function Documentation
adl_begin()
template<typename ContainerTy > decltype(auto) llvm::adl_detail::adl_begin (ContainerTy && container)
Definition at line 341 of file STLExtras.h.
References llvm::sys::path::begin().
Referenced by llvm::adl_begin().
adl_end()
template<typename ContainerTy > decltype(auto) llvm::adl_detail::adl_end (ContainerTy && container)
Definition at line 348 of file STLExtras.h.
References llvm::sys::path::end().
Referenced by llvm::adl_end().
adl_swap()
template<typename T > void llvm::adl_detail::adl_swap (T && lhs, T && rhs) noexcept
Definition at line 355 of file STLExtras.h.
References std::swap().
Referenced by llvm::adl_swap().