LLVM: llvm::AArch64_MC Namespace Reference
llvm::AArch64_MC Namespace Reference
Functions
void initLLVMToCVRegMapping (MCRegisterInfo *MRI)
bool isQForm (const MCInst &MI, const MCInstrInfo *MCII)
bool isFpOrNEON (const MCInst &MI, const MCInstrInfo *MCII)
Function Documentation
initLLVMToCVRegMapping()
void llvm::AArch64_MC::initLLVMToCVRegMapping (MCRegisterInfo * MRI)
Definition at line 66 of file AArch64MCTargetDesc.cpp.
References I, and MRI.
Referenced by llvm::AArch64RegisterInfo::AArch64RegisterInfo(), and createAArch64MCRegisterInfo().
isFpOrNEON()
bool llvm::AArch64_MC::isFpOrNEON (const MCInst & MI, const MCInstrInfo * MCII)
Definition at line 310 of file AArch64MCTargetDesc.cpp.
References llvm::any_of(), and MI.
isQForm()
bool llvm::AArch64_MC::isQForm (const MCInst & MI, const MCInstrInfo * MCII)
Definition at line 303 of file AArch64MCTargetDesc.cpp.
References llvm::any_of(), and MI.