LLVM: llvm::LoongArchABI Namespace Reference
llvm::LoongArchABI Namespace Reference
Enumerations
enum ABI {
ABI_ILP32S, ABI_ILP32F, ABI_ILP32D, ABI_LP64S,
ABI_LP64F, ABI_LP64D, ABI_Unknown
}
Functions
ABI computeTargetABI (const Triple &TT, StringRef ABIName)
ABI getTargetABI (StringRef ABIName)
MCRegister getBPReg ()
Enumeration Type Documentation
ABI
enum llvm::LoongArchABI::ABI
Enumerator
ABI_ILP32S
ABI_ILP32F
ABI_ILP32D
ABI_LP64S
ABI_LP64F
ABI_LP64D
ABI_Unknown
Definition at line 47 of file LoongArchBaseInfo.h.
Function Documentation
computeTargetABI()
ABI llvm::LoongArchABI::computeTargetABI (const Triple & TT, StringRef ABIName)
Definition at line 24 of file LoongArchBaseInfo.cpp.
References ABI_ILP32D, ABI_ILP32F, ABI_ILP32S, ABI_LP64D, ABI_LP64F, ABI_LP64S, ABI_Unknown, llvm::StringRef::empty(), llvm::errs(), and getTargetABI().
Referenced by llvm::LoongArchTargetELFStreamer::LoongArchTargetELFStreamer().
getBPReg()
MCRegister llvm::LoongArchABI::getBPReg ()
Definition at line 96 of file LoongArchBaseInfo.cpp.
Referenced by llvm::LoongArchFrameLowering::determineCalleeSaves(), llvm::LoongArchFrameLowering::getFrameIndexReference(), and llvm::LoongArchRegisterInfo::getReservedRegs().
getTargetABI()
ABI llvm::LoongArchABI::getTargetABI (StringRef ABIName)
Definition at line 83 of file LoongArchBaseInfo.cpp.
References ABI_ILP32D, ABI_ILP32F, ABI_ILP32S, ABI_LP64D, ABI_LP64F, ABI_LP64S, ABI_Unknown, llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
Referenced by llvm::LoongArchTargetLowering::CanLowerReturn(), llvm::RISCVTargetLowering::CanLowerReturn(), computeTargetABI(), and llvm::LoongArchTargetMachine::getSubtargetImpl().