LLVM: llvm::RISCVFeatures Namespace Reference
llvm::RISCVFeatures Namespace Reference
Functions
void validate (const Triple &TT, const FeatureBitset &FeatureBits)
llvm::Expected< std::unique_ptr< RISCVISAInfo > > parseFeatureBits (bool IsRV64, const FeatureBitset &FeatureBits)
Function Documentation
parseFeatureBits()
llvm::Expected< std::unique_ptr< RISCVISAInfo > > llvm::RISCVFeatures::parseFeatureBits (bool IsRV64, const FeatureBitset & FeatureBits)
Definition at line 112 of file RISCVBaseInfo.cpp.
References llvm::RISCVISAInfo::isSupportedExtensionFeature(), llvm::RISCVISAInfo::parseFeatures(), and llvm::RISCVFeatureKV.
Referenced by llvm::RISCVABI::computeTargetABI(), and llvm::RISCVTargetStreamer::emitTargetAttributes().
validate()
void llvm::RISCVFeatures::validate (const Triple & TT, const FeatureBitset & FeatureBits)
Definition at line 99 of file RISCVBaseInfo.cpp.
References llvm::report_fatal_error().
Referenced by llvm::RISCVAsmBackend::RISCVAsmBackend().