LLVM: llvm::Hexagon_MC Namespace Reference
llvm::Hexagon_MC Namespace Reference
Functions
StringRef selectHexagonCPU (StringRef CPU)
FeatureBitset completeHVXFeatures (const FeatureBitset &FB)
MCSubtargetInfo * createHexagonMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
Create a Hexagon MCSubtargetInfo instance.
const MCSubtargetInfo * getArchSubtarget (MCSubtargetInfo const *STI)
void addArchSubtarget (MCSubtargetInfo const *STI, StringRef FS)
unsigned GetELFFlags (const MCSubtargetInfo &STI)
llvm::ArrayRef< MCPhysReg > GetVectRegRev ()
Function Documentation
addArchSubtarget()
void llvm::Hexagon_MC::addArchSubtarget (MCSubtargetInfo const * STI, StringRef FS)
Definition at line 582 of file HexagonMCTargetDesc.cpp.
References assert(), llvm::StringRef::contains(), createHexagonMCSubtargetInfo(), llvm::X86AS::FS, llvm::MCSubtargetInfo::getCPU(), llvm::MCSubtargetInfo::getTargetTriple(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by createHexagonMCSubtargetInfo(), and llvm::HexagonSubtarget::HexagonSubtarget().
completeHVXFeatures()
FeatureBitset llvm::Hexagon_MC::completeHVXFeatures (const FeatureBitset & FB)
Definition at line 466 of file HexagonMCTargetDesc.cpp.
References F, S, llvm::FeatureBitset::set(), and llvm::FeatureBitset::test().
Referenced by createHexagonMCSubtargetInfo(), and llvm::HexagonSubtarget::initializeSubtargetDependencies().
createHexagonMCSubtargetInfo()
MCSubtargetInfo * llvm::Hexagon_MC::createHexagonMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS)
Create a Hexagon MCSubtargetInfo instance.
This is exposed so Asm parser, etc. do not need to go through TargetRegistry.
Definition at line 533 of file HexagonMCTargetDesc.cpp.
References addArchSubtarget(), checkFeature(), completeHVXFeatures(), llvm::StringRef::equals(), llvm::errs(), exit(), llvm::StringRef::find(), llvm::X86AS::FS, llvm::HexagonDisableDuplex, isCPUValid(), llvm::FeatureBitset::reset(), llvm::FeatureBitset::set(), llvm::StringRef::str(), and X.
Referenced by addArchSubtarget(), and LLVMInitializeHexagonTargetMC().
getArchSubtarget()
const MCSubtargetInfo * llvm::Hexagon_MC::getArchSubtarget (MCSubtargetInfo const * STI)
Definition at line 458 of file HexagonMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getCPU().
Referenced by llvm::HexagonMCInstrInfo::canonicalizePacket().
GetELFFlags()
unsigned llvm::Hexagon_MC::GetELFFlags (const MCSubtargetInfo & STI)
Definition at line 594 of file HexagonMCTargetDesc.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::ELF::EF_HEXAGON_MACH_V5, llvm::ELF::EF_HEXAGON_MACH_V55, llvm::ELF::EF_HEXAGON_MACH_V60, llvm::ELF::EF_HEXAGON_MACH_V62, llvm::ELF::EF_HEXAGON_MACH_V65, llvm::ELF::EF_HEXAGON_MACH_V66, llvm::ELF::EF_HEXAGON_MACH_V67, llvm::ELF::EF_HEXAGON_MACH_V67T, llvm::ELF::EF_HEXAGON_MACH_V68, llvm::ELF::EF_HEXAGON_MACH_V69, llvm::ELF::EF_HEXAGON_MACH_V71, llvm::ELF::EF_HEXAGON_MACH_V71T, llvm::ELF::EF_HEXAGON_MACH_V73, and llvm::MCSubtargetInfo::getCPU().
GetVectRegRev()
llvm::ArrayRef< MCPhysReg > llvm::Hexagon_MC::GetVectRegRev ()
Definition at line 612 of file HexagonMCTargetDesc.cpp.
References llvm::ArrayRef().
Referenced by llvm::HexagonRegisterInfo::getReservedRegs().
selectHexagonCPU()
StringRef llvm::Hexagon_MC::selectHexagonCPU (StringRef CPU)
Definition at line 153 of file HexagonMCTargetDesc.cpp.
References DefaultArch, llvm::StringRef::empty(), HexagonGetArchVariant(), llvm::report_fatal_error(), and llvm::StringRef::split().
Referenced by llvm::createHexagonAsmBackend().