LLVM: llvm::RISCVMatInt Namespace Reference
llvm::RISCVMatInt Namespace Reference
Classes
class Inst
Typedefs
using InstSeq = SmallVector< Inst, 8 >
Enumerations
enum OpndKind { RegImm, Imm, RegReg, RegX0 }
Functions
InstSeq generateInstSeq (int64_t Val, const FeatureBitset &ActiveFeatures)
int getIntMatCost (const APInt &Val, unsigned Size, const FeatureBitset &ActiveFeatures, bool CompressionCost)
Typedef Documentation
InstSeq
using llvm::RISCVMatInt::InstSeq = typedef SmallVector<Inst, 8>
Definition at line 42 of file RISCVMatInt.h.
Enumeration Type Documentation
OpndKind
enum llvm::RISCVMatInt::OpndKind
Enumerator
RegImm
Imm
RegReg
RegX0
Definition at line 21 of file RISCVMatInt.h.
Function Documentation
generateInstSeq()
InstSeq llvm::RISCVMatInt::generateInstSeq (int64_t Val, const FeatureBitset & ActiveFeatures)
Definition at line 175 of file RISCVMatInt.cpp.
References assert(), llvm::tgtok::Bit, llvm::SmallVectorImpl< T >::clear(), llvm::countl_zero(), llvm::countr_zero(), llvm::SmallVectorImpl< T >::emplace_back(), extractRotateInfo(), generateInstSeqImpl(), llvm::Hi_32(), ll, llvm::Lo_32(), llvm::popcount(), and uint64_t.
Referenced by getIntMatCost(), lowerConstant(), llvm::RISCVInstrInfo::movImm(), selectConstantAddr(), selectImm(), and llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm().
getIntMatCost()
int llvm::RISCVMatInt::getIntMatCost (const APInt & Val, unsigned Size, const FeatureBitset & ActiveFeatures, bool CompressionCost)
Definition at line 374 of file RISCVMatInt.cpp.
References llvm::APInt::ashr(), Cost, generateInstSeq(), getInstSeqCost(), llvm::APInt::getSExtValue(), llvm::max(), and llvm::APInt::sextOrTrunc().
Referenced by llvm::RISCVTTIImpl::getIntImmCost(), llvm::RISCVTargetLowering::isDesirableToCommuteWithShift(), and llvm::RISCVTargetLowering::isFPImmLegal().