LLVM: llvm::AMDGPU::DepCtr Namespace Reference
llvm::AMDGPU::DepCtr Namespace Reference
Functions
int getDefaultDepCtrEncoding (const MCSubtargetInfo &STI)
bool isSymbolicDepCtrEncoding (unsigned Code, bool &HasNonDefaultVal, const MCSubtargetInfo &STI)
bool decodeDepCtr (unsigned Code, int &Id, StringRef &Name, unsigned &Val, bool &IsDefault, const MCSubtargetInfo &STI)
int encodeDepCtr (const StringRef Name, int64_t Val, unsigned &UsedOprMask, const MCSubtargetInfo &STI)
Variables
const CustomOperandVal DepCtrInfo []
const int DEP_CTR_SIZE
Function Documentation
decodeDepCtr()
bool llvm::AMDGPU::DepCtr::decodeDepCtr (unsigned Code, int & Id, StringRef & Name, unsigned & Val, bool & IsDefault, const MCSubtargetInfo & STI)
Definition at line 1488 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::decodeCustomOperand(), DEP_CTR_SIZE, and DepCtrInfo.
Referenced by llvm::AMDGPUInstPrinter::printDepCtr().
encodeDepCtr()
int llvm::AMDGPU::DepCtr::encodeDepCtr (const StringRef Name, int64_t Val, unsigned & UsedOprMask, const MCSubtargetInfo & STI)
Definition at line 1494 of file AMDGPUBaseInfo.cpp.
References DEP_CTR_SIZE, DepCtrInfo, and llvm::AMDGPU::encodeCustomOperand().
getDefaultDepCtrEncoding()
int llvm::AMDGPU::DepCtr::getDefaultDepCtrEncoding (const MCSubtargetInfo & STI)
Definition at line 1475 of file AMDGPUBaseInfo.cpp.
References DEP_CTR_SIZE, DepCtrInfo, and llvm::AMDGPU::getDefaultCustomOperandEncoding().
isSymbolicDepCtrEncoding()
bool llvm::AMDGPU::DepCtr::isSymbolicDepCtrEncoding (unsigned Code, bool & HasNonDefaultVal, const MCSubtargetInfo & STI)
Definition at line 1482 of file AMDGPUBaseInfo.cpp.
References DEP_CTR_SIZE, DepCtrInfo, and llvm::AMDGPU::isSymbolicCustomOperandEncoding().
Referenced by llvm::AMDGPUInstPrinter::printDepCtr().
Variable Documentation
DEP_CTR_SIZE
const int llvm::AMDGPU::DepCtr::DEP_CTR_SIZE
Initial value:
=
    static_cast<int>(sizeof(DepCtrInfo) / sizeof(CustomOperandVal))
Definition at line 30 of file AMDGPUAsmUtils.cpp.
Referenced by decodeDepCtr(), encodeDepCtr(), getDefaultDepCtrEncoding(), and isSymbolicDepCtrEncoding().
DepCtrInfo
const CustomOperandVal llvm::AMDGPU::DepCtr::DepCtrInfo
Initial value:
= {
  {{"depctr_hold_cnt"},  1,   1,    7,    1,   isGFX10_BEncoding},
  {{"depctr_sa_sdst"},   1,   1,    0,    1},
  {{"depctr_va_vdst"},  15,  15,   12,    4},
  {{"depctr_va_sdst"},   7,   7,    9,    3},
  {{"depctr_va_ssrc"},   1,   1,    8,    1},
  {{"depctr_va_vcc"},    1,   1,    1,    1},
  {{"depctr_vm_vsrc"},   7,   7,    2,    3},
}
Definition at line 18 of file AMDGPUAsmUtils.cpp.
Referenced by decodeDepCtr(), encodeDepCtr(), getDefaultDepCtrEncoding(), and isSymbolicDepCtrEncoding().