LLVM: llvm::vfs Namespace Reference
llvm::vfs Namespace Reference
Namespaces
detail
Classes
class directory_entry
A member of a directory, yielded by a directory_iterator.
class directory_iterator
An input iterator over the entries in a virtual path, similar to llvm::sys::fs::directory_iterator.
class File
Represents an open file.
class FileSystem
The virtual file system interface.
class InMemoryFileSystem
An in-memory file system.
class OverlayFileSystem
A file system that allows overlaying one AbstractFileSystem on top of another.
class ProxyFileSystem
By default, this delegates all calls to the underlying file system.
class recursive_directory_iterator
An input iterator over the recursive contents of a virtual path, similar to llvm::sys::fs::recursive_directory_iterator.
class RedirectingFileSystem
A virtual file system parsed from a YAML file.
class RedirectingFileSystemParser
A helper class to hold the common YAML parsing state.
class RedirectingFSDirIterImpl
Directory iterator implementation for RedirectingFileSystem's directory entries.
class Status
The result of a status operation.
struct YAMLVFSEntry
class YAMLVFSWriter
Functions
IntrusiveRefCntPtr< FileSystem > getRealFileSystem ()
Gets an vfs::FileSystem for the 'real' file system, as seen by the operating system.
std::unique_ptr< FileSystem > createPhysicalFileSystem ()
Create an vfs::FileSystem for the 'real' file system, as seen by the operating system.
llvm::sys::fs::UniqueID getNextVirtualUniqueID ()
Get a globally unique ID for a virtual file or directory.
std::unique_ptr< FileSystem > getVFSFromYAML (std::unique_ptr< llvm::MemoryBuffer > Buffer, llvm::SourceMgr::DiagHandlerTy DiagHandler, StringRef YAMLFilePath, void *DiagContext=nullptr, IntrusiveRefCntPtr< FileSystem > ExternalFS=getRealFileSystem())
Gets a FileSystem for a virtual file system described in YAML format.
void collectVFSFromYAML (std::unique_ptr< llvm::MemoryBuffer > Buffer, llvm::SourceMgr::DiagHandlerTy DiagHandler, StringRef YAMLFilePath, SmallVectorImpl< YAMLVFSEntry > &CollectedEntries, void *DiagContext=nullptr, IntrusiveRefCntPtr< FileSystem > ExternalFS=getRealFileSystem())
Collect all pairs of <virtual path, real path> entries from the YAMLFilePath.
static sys::fs::UniqueID getUniqueID (hash_code Hash)
static sys::fs::UniqueID getFileID (sys::fs::UniqueID Parent, llvm::StringRef Name, llvm::StringRef Contents)
static sys::fs::UniqueID getDirectoryID (sys::fs::UniqueID Parent, llvm::StringRef Name)
Function Documentation
collectVFSFromYAML()
void llvm::vfs::collectVFSFromYAML (std::unique_ptr< llvm::MemoryBuffer > Buffer, llvm::SourceMgr::DiagHandlerTy DiagHandler, StringRef YAMLFilePath, SmallVectorImpl< YAMLVFSEntry > & CollectedEntries, void * DiagContext = nullptr, IntrusiveRefCntPtr< FileSystem > ExternalFS = getRealFileSystem())
Collect all pairs of <virtual path, real path> entries from the YAMLFilePath.
This is used by the module dependency collector to forward the entries into the reproducer output VFS YAML file.
createPhysicalFileSystem()
std::unique_ptr< FileSystem > llvm::vfs::createPhysicalFileSystem ()
Create an vfs::FileSystem for the 'real' file system, as seen by the operating system.
It has its own working directory, independent of (but initially equal to) that of the process.
Definition at line 380 of file VirtualFileSystem.cpp.
getDirectoryID()
static sys::fs::UniqueID llvm::vfs::getDirectoryID (sys::fs::UniqueID Parent, llvm::StringRef Name) static
Definition at line 785 of file VirtualFileSystem.cpp.
References llvm::sys::fs::UniqueID::getFile(), getUniqueID(), and llvm::hash_combine().
Referenced by llvm::vfs::detail::NewInMemoryNodeInfo::makeStatus().
getFileID()
static sys::fs::UniqueID llvm::vfs::getFileID (sys::fs::UniqueID Parent, llvm::StringRef Name, llvm::StringRef Contents) static
Definition at line 780 of file VirtualFileSystem.cpp.
References llvm::sys::fs::UniqueID::getFile(), getUniqueID(), and llvm::hash_combine().
Referenced by llvm::vfs::detail::NewInMemoryNodeInfo::makeStatus().
getNextVirtualUniqueID()
UniqueID llvm::vfs::getNextVirtualUniqueID ()
Get a globally unique ID for a virtual file or directory.
Definition at line 2617 of file VirtualFileSystem.cpp.
References llvm::max().
Referenced by llvm::vfs::RedirectingFileSystemParser::lookupOrCreateEntry().
getRealFileSystem()
IntrusiveRefCntPtr< FileSystem > llvm::vfs::getRealFileSystem ()
Gets an vfs::FileSystem for the 'real' file system, as seen by the operating system.
The working directory is linked to the process's working directory. (This is usually thread-hostile).
Definition at line 375 of file VirtualFileSystem.cpp.
References llvm::X86AS::FS.
Referenced by llvm::OverlapStats::accumulateCounts(), llvm::FileCollectorBase::addDirectory(), llvm::MIRProfileLoaderPass::MIRProfileLoaderPass(), llvm::PGOInstrumentationUse::PGOInstrumentationUse(), llvm::SampleProfileLoaderPass::run(), llvm::SanitizerBinaryMetadataPass::run(), runNewPMPasses(), and llvm::SanitizerCoveragePass::SanitizerCoveragePass().
getUniqueID()
static sys::fs::UniqueID llvm::vfs::getUniqueID (hash_code Hash) static
Definition at line 776 of file VirtualFileSystem.cpp.
References llvm::max(), and uint64_t.
Referenced by getDirectoryID(), and getFileID().
getVFSFromYAML()
std::unique_ptr<FileSystem> llvm::vfs::getVFSFromYAML (std::unique_ptr< llvm::MemoryBuffer > Buffer, llvm::SourceMgr::DiagHandlerTy DiagHandler, StringRef YAMLFilePath, void * DiagContext = nullptr, IntrusiveRefCntPtr< FileSystem > ExternalFS = getRealFileSystem())
Gets a FileSystem for a virtual file system described in YAML format.