LLVM: false Namespace Reference
false Namespace Reference
Classes
class Chain
A Chain is a sequence of instructions that are linked together by an accumulation operand.
struct GCPtrLivenessData
struct GepNode
struct in_set
struct IntervalSorter
class LibCallsShrinkWrap
struct PartiallyConstructedSafepointRecord
struct RematerizlizationCandidateRecord
struct SingleLoopExtractor
SingleLoopExtractor - For bugpoint.
Typedefs
using DefiningValueMapTy = MapVector< Value *, Value * >
using IsKnownBaseMapTy = MapVector< Value *, bool >
using PointerToBaseTy = MapVector< Value *, Value * >
using StatepointLiveSetTy = SetVector< Value * >
using RematerializedValueMapTy = MapVector< AssertingVH< Instruction >, AssertingVH< Value > >
using RematCandTy = MapVector< Value *, RematerizlizationCandidateRecord >
Functions
raw_ostream & operator<< (raw_ostream &OS, const GepNode &GN)
template<typename NodeContainer >
void dump_node_container (raw_ostream &OS, const NodeContainer &S)
raw_ostream & operator<< (raw_ostream &OS, const NodeVect &S) LLVM_ATTRIBUTE_UNUSED
raw_ostream & operator<< (raw_ostream &OS, const NodeToUsesMap &M) LLVM_ATTRIBUTE_UNUSED
Typedef Documentation
DefiningValueMapTy
using false::DefiningValueMapTy = typedef MapVector<Value *, Value *>
Definition at line 266 of file RewriteStatepointsForGC.cpp.
IsKnownBaseMapTy
using false::IsKnownBaseMapTy = typedef MapVector<Value *, bool>
Definition at line 267 of file RewriteStatepointsForGC.cpp.
PointerToBaseTy
using false::PointerToBaseTy = typedef MapVector<Value *, Value *>
Definition at line 268 of file RewriteStatepointsForGC.cpp.
RematCandTy
using false::RematCandTy = typedef MapVector<Value *, RematerizlizationCandidateRecord>
Definition at line 299 of file RewriteStatepointsForGC.cpp.
RematerializedValueMapTy
using false::RematerializedValueMapTy = typedef MapVector<AssertingVH<Instruction>, AssertingVH<Value> >
Definition at line 271 of file RewriteStatepointsForGC.cpp.
StatepointLiveSetTy
using false::StatepointLiveSetTy = typedef SetVector<Value *>
Definition at line 269 of file RewriteStatepointsForGC.cpp.
Function Documentation
dump_node_container()
template<typename NodeContainer > void false::dump_node_container (raw_ostream & OS, const NodeContainer & S)
Definition at line 275 of file HexagonCommonGEP.cpp.
References E, I, OS, and S.
Referenced by operator<<().
operator<<() [1/3]
raw_ostream& false::operator<< (raw_ostream & OS, const GepNode & GN)
Definition at line 218 of file HexagonCommonGEP.cpp.
References false::GepNode::BaseVal, false::GepNode::Flags, llvm::Value::getName(), llvm::Type::getStructName(), llvm::Value::hasName(), false::GepNode::Idx, llvm::StructType::isLiteral(), llvm::Type::isStructTy(), OS, false::GepNode::Parent, and false::GepNode::PTy.
operator<<() [2/3]
raw_ostream & false::operator<< (raw_ostream & OS, const NodeToUsesMap & M)
Definition at line 291 of file HexagonCommonGEP.cpp.
References I, M, and OS.
operator<<() [3/3]
raw_ostream & false::operator<< (raw_ostream & OS, const NodeVect & S)
Definition at line 284 of file HexagonCommonGEP.cpp.
References dump_node_container(), OS, and S.