LLVM: llvm::mc Namespace Reference
llvm::mc Namespace Reference
Classes
struct RegisterMCTargetOptionsFlags
Create this object with static storage to register mc-related command line options.
Functions
bool getRelaxAll ()
std::optional< bool > getExplicitRelaxAll ()
bool getIncrementalLinkerCompatible ()
int getDwarfVersion ()
bool getDwarf64 ()
EmitDwarfUnwindType getEmitDwarfUnwind ()
bool getShowMCInst ()
bool getFatalWarnings ()
bool getNoWarn ()
bool getNoDeprecatedWarn ()
bool getNoTypeCheck ()
std::string getABIName ()
std::string getAsSecureLogFile ()
MCTargetOptions InitMCTargetOptionsFromFlags ()
Function Documentation
getABIName()
std::string llvm::mc::getABIName ()
Referenced by InitMCTargetOptionsFromFlags().
getAsSecureLogFile()
std::string llvm::mc::getAsSecureLogFile ()
Referenced by InitMCTargetOptionsFromFlags().
getDwarf64()
bool llvm::mc::getDwarf64 ()
Referenced by InitMCTargetOptionsFromFlags().
getDwarfVersion()
int llvm::mc::getDwarfVersion ()
Referenced by InitMCTargetOptionsFromFlags().
getEmitDwarfUnwind()
EmitDwarfUnwindType llvm::mc::getEmitDwarfUnwind ()
Referenced by InitMCTargetOptionsFromFlags().
getExplicitRelaxAll()
std::optional<bool> llvm::mc::getExplicitRelaxAll ()
getFatalWarnings()
bool llvm::mc::getFatalWarnings ()
Referenced by InitMCTargetOptionsFromFlags().
getIncrementalLinkerCompatible()
bool llvm::mc::getIncrementalLinkerCompatible ()
Referenced by InitMCTargetOptionsFromFlags().
getNoDeprecatedWarn()
bool llvm::mc::getNoDeprecatedWarn ()
Referenced by InitMCTargetOptionsFromFlags().
getNoTypeCheck()
bool llvm::mc::getNoTypeCheck ()
Referenced by InitMCTargetOptionsFromFlags().
getNoWarn()
bool llvm::mc::getNoWarn ()
Referenced by InitMCTargetOptionsFromFlags().
getRelaxAll()
bool llvm::mc::getRelaxAll ()
Referenced by llvm::MCELFStreamer::emitBundleLock(), llvm::MCELFStreamer::emitBundleUnlock(), llvm::MCObjectStreamer::emitInstToFragment(), llvm::MCObjectStreamer::emitLabel(), and InitMCTargetOptionsFromFlags().
getShowMCInst()
bool llvm::mc::getShowMCInst ()
Referenced by InitMCTargetOptionsFromFlags().
InitMCTargetOptionsFromFlags()
MCTargetOptions llvm::mc::InitMCTargetOptionsFromFlags ()
Definition at line 125 of file MCTargetOptionsCommandFlags.cpp.
References getABIName(), getAsSecureLogFile(), getDwarf64(), getDwarfVersion(), getEmitDwarfUnwind(), getFatalWarnings(), getIncrementalLinkerCompatible(), getNoDeprecatedWarn(), getNoTypeCheck(), getNoWarn(), getRelaxAll(), getShowMCInst(), and Options.
Referenced by llvm::DwarfStreamer::init(), and llvm::codegen::InitTargetOptionsFromCodeGenFlags().