LLVM: llvm::compression::zstd Namespace Reference
llvm::compression::zstd Namespace Reference
Functions
bool isAvailable ()
void compress (ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > &CompressedBuffer, int Level=DefaultCompression)
Error decompress (ArrayRef< uint8_t > Input, uint8_t *Output, size_t &UncompressedSize)
Error decompress (ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > &Output, size_t UncompressedSize)
Variables
constexpr int NoCompression = -5
constexpr int BestSpeedCompression = 1
constexpr int DefaultCompression = 5
constexpr int BestSizeCompression = 12
Function Documentation
compress()
void llvm::compression::zstd::compress (ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > & CompressedBuffer, int Level = DefaultCompression)
Definition at line 207 of file Compression.cpp.
References llvm_unreachable.
Referenced by llvm::compression::compress().
decompress() [1/2]
Error llvm::compression::zstd::decompress (ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > & Output, size_t UncompressedSize)
Definition at line 215 of file Compression.cpp.
References llvm_unreachable.
decompress() [2/2]
Error llvm::compression::zstd::decompress (ArrayRef< uint8_t > Input, uint8_t * Output, size_t & UncompressedSize)
Definition at line 211 of file Compression.cpp.
References llvm_unreachable.
Referenced by llvm::compression::decompress().
isAvailable()
bool llvm::compression::zstd::isAvailable ()
Definition at line 206 of file Compression.cpp.
Referenced by llvm::compression::getReasonIfUnsupported().
Variable Documentation
BestSizeCompression
constexpr int llvm::compression::zstd::BestSizeCompression = 12 constexpr
Definition at line 60 of file Compression.h.
BestSpeedCompression
constexpr int llvm::compression::zstd::BestSpeedCompression = 1 constexpr
Definition at line 58 of file Compression.h.
DefaultCompression
constexpr int llvm::compression::zstd::DefaultCompression = 5 constexpr
Definition at line 59 of file Compression.h.
NoCompression
constexpr int llvm::compression::zstd::NoCompression = -5 constexpr
Definition at line 57 of file Compression.h.