LLVM: llvm::msf Namespace Reference
llvm::msf Namespace Reference
Classes
class IMSFFile
class MappedBlockStream
MappedBlockStream represents data stored in an MSF file into chunks of a particular size (called the Block Size), and whose chunks may not be necessarily contiguous.
class MSFBuilder
class MSFError
Base class for errors originating when parsing raw PDB files.
struct MSFLayout
class MSFStreamLayout
Describes the layout of a stream in an MSF layout.
struct SuperBlock
class WritableMappedBlockStream
Enumerations
enum msf_error_code {
msf_error_code::unspecified = 1, msf_error_code::insufficient_buffer, msf_error_code::size_overflow_4096, msf_error_code::size_overflow_8192,
msf_error_code::size_overflow_16384, msf_error_code::size_overflow_32768, msf_error_code::not_writable, msf_error_code::no_stream,
msf_error_code::invalid_format, msf_error_code::block_in_use
}
Functions
MSFStreamLayout getFpmStreamLayout (const MSFLayout &Msf, bool IncludeUnusedFpmData=false, bool AltFpm=false)
Determine the layout of the FPM stream, given the MSF layout.
bool isValidBlockSize (uint32_t Size)
uint64_t getMaxFileSizeFromBlockSize (uint32_t Size)
Given the specified block size, returns the maximum possible file size.
uint32_t getMinimumBlockCount ()
uint32_t getFirstUnreservedBlock ()
uint64_t bytesToBlocks (uint64_t NumBytes, uint64_t BlockSize)
uint64_t blockToOffset (uint64_t BlockNumber, uint64_t BlockSize)
uint32_t getFpmIntervalLength (const MSFLayout &L)
uint32_t getNumFpmIntervals (uint32_t BlockSize, uint32_t NumBlocks, bool IncludeUnusedFpmData, int FpmNumber)
Given an MSF with the specified block size and number of blocks, determine how many pieces the specified Fpm is split into.
uint32_t getNumFpmIntervals (const MSFLayout &L, bool IncludeUnusedFpmData=false, bool AltFpm=false)
Error validateSuperBlock (const SuperBlock &SB)
const std::error_category & MSFErrCategory ()
std::error_code make_error_code (msf_error_code E)
Variables
static const char Magic []
Enumeration Type Documentation
msf_error_code
enum llvm::msf::msf_error_code strong
Enumerator
unspecified
insufficient_buffer
size_overflow_4096
size_overflow_8192
size_overflow_16384
size_overflow_32768
not_writable
no_stream
invalid_format
block_in_use
Definition at line 16 of file MSFError.h.
Function Documentation
blockToOffset()
uint64_t llvm::msf::blockToOffset (uint64_t BlockNumber, uint64_t BlockSize) inline
Definition at line 135 of file MSFCommon.h.
References BlockSize.
Referenced by llvm::msf::MSFBuilder::commit(), llvm::pdb::PDBFile::getBlockData(), llvm::msf::MappedBlockStream::readLongestContiguousChunk(), and llvm::msf::WritableMappedBlockStream::writeBytes().
bytesToBlocks()
uint64_t llvm::msf::bytesToBlocks (uint64_t NumBytes, uint64_t BlockSize) inline
Definition at line 131 of file MSFCommon.h.
References BlockSize, and llvm::divideCeil().
Referenced by llvm::msf::MSFBuilder::addStream(), llvm::msf::MSFBuilder::generateLayout(), llvm::pdb::PDBFile::getNumDirectoryBlocks(), llvm::pdb::PDBFile::parseStreamData(), llvm::msf::MSFBuilder::setStreamSize(), and validateSuperBlock().
getFirstUnreservedBlock()
uint32_t llvm::msf::getFirstUnreservedBlock () inline
Definition at line 129 of file MSFCommon.h.
getFpmIntervalLength()
uint32_t llvm::msf::getFpmIntervalLength (const MSFLayout & L) inline
Definition at line 139 of file MSFCommon.h.
References llvm::msf::SuperBlock::BlockSize, and llvm::msf::MSFLayout::SB.
Referenced by getFpmStreamLayout().
getFpmStreamLayout()
MSFStreamLayout llvm::msf::getFpmStreamLayout (const MSFLayout & Msf, bool IncludeUnusedFpmData = false, bool AltFpm = false)
Determine the layout of the FPM stream, given the MSF layout.
An FPM stream spans 1 or more blocks, each at equally spaced intervals throughout the file.
Definition at line 62 of file MSFCommon.cpp.
References llvm::msf::MSFLayout::alternateFpmBlock(), llvm::msf::MSFStreamLayout::Blocks, llvm::msf::SuperBlock::BlockSize, llvm::divideCeil(), getFpmIntervalLength(), getNumFpmIntervals(), I, llvm::msf::MSFStreamLayout::Length, llvm::msf::MSFLayout::mainFpmBlock(), llvm::msf::SuperBlock::NumBlocks, and llvm::msf::MSFLayout::SB.
Referenced by llvm::msf::MappedBlockStream::createFpmStream(), llvm::msf::WritableMappedBlockStream::createFpmStream(), and llvm::pdb::PDBFile::getFpmStreamLayout().
getMaxFileSizeFromBlockSize()
uint64_t llvm::msf::getMaxFileSizeFromBlockSize (uint32_t Size) inline
Given the specified block size, returns the maximum possible file size.
Block Size | Max File Size <= 4096 | 4GB 8192 | 8GB 16384 | 16GB 32768 | 32GB Size - the block size of the MSF
Definition at line 111 of file MSFCommon.h.
References uint64_t.
Referenced by llvm::msf::MSFBuilder::commit().
getMinimumBlockCount()
uint32_t llvm::msf::getMinimumBlockCount () inline
Definition at line 125 of file MSFCommon.h.
Referenced by llvm::msf::MSFBuilder::create().
getNumFpmIntervals() [1/2]
uint32_t llvm::msf::getNumFpmIntervals (const MSFLayout & L, bool IncludeUnusedFpmData = false, bool AltFpm = false) inline
Definition at line 171 of file MSFCommon.h.
References llvm::msf::MSFLayout::alternateFpmBlock(), llvm::msf::SuperBlock::BlockSize, getNumFpmIntervals(), llvm::msf::MSFLayout::mainFpmBlock(), llvm::msf::SuperBlock::NumBlocks, and llvm::msf::MSFLayout::SB.
getNumFpmIntervals() [2/2]
uint32_t llvm::msf::getNumFpmIntervals (uint32_t BlockSize, uint32_t NumBlocks, bool IncludeUnusedFpmData, int FpmNumber) inline
Given an MSF with the specified block size and number of blocks, determine how many pieces the specified Fpm is split into.
BlockSize - the block size of the MSF NumBlocks - the total number of blocks in the MSF IncludeUnusedFpmData - When true, this will count every block that is both in the file and matches the form of an FPM block, even if some of those FPM blocks are unused (a single FPM block can describe the allocation status of up to 32,767 blocks, although one appears only every 4,096 blocks). So there are 8x as many blocks that match the form as there are blocks that are necessary to describe the allocation status of the file. When this parameter is false, these extraneous trailing blocks are not counted.
Definition at line 155 of file MSFCommon.h.
References assert(), BlockSize, and llvm::divideCeil().
Referenced by getFpmStreamLayout(), and getNumFpmIntervals().
isValidBlockSize()
bool llvm::msf::isValidBlockSize (uint32_t Size) inline
Definition at line 90 of file MSFCommon.h.
Referenced by llvm::msf::MSFBuilder::create(), and validateSuperBlock().
make_error_code()
std::error_code llvm::msf::make_error_code (msf_error_code E) inline
Definition at line 40 of file MSFError.h.
References E, and MSFErrCategory().
MSFErrCategory()
const std::error_category & llvm::msf::MSFErrCategory ()
Definition at line 52 of file MSFError.cpp.
Referenced by make_error_code().
validateSuperBlock()
Error llvm::msf::validateSuperBlock (const SuperBlock & SB)
Definition at line 19 of file MSFCommon.cpp.
References llvm::msf::SuperBlock::BlockMapAddr, llvm::msf::SuperBlock::BlockSize, bytesToBlocks(), llvm::msf::SuperBlock::FreeBlockMapBlock, invalid_format, isValidBlockSize(), Magic, llvm::msf::SuperBlock::MagicBytes, memcmp, llvm::msf::SuperBlock::NumBlocks, llvm::msf::SuperBlock::NumDirectoryBytes, llvm::Error::success(), and uint64_t.
Referenced by llvm::pdb::PDBFile::parseFileHeaders().
Variable Documentation
Magic
const char llvm::msf::Magic[] static
Initial value:
= {'M',  'i',  'c',    'r', 'o', 's',  'o',  'f',
                             't',  ' ',  'C',    '/', 'C', '+',  '+',  ' ',
                             'M',  'S',  'F',    ' ', '7', '.',  '0',  '0',
                             '\r', '\n', '\x1a', 'D', 'S', '\0', '\0', '\0'}
Definition at line 23 of file MSFCommon.h.
Referenced by analyzeHeader(), appendFile(), llvm::CombinerHelper::buildUDivUsingMul(), llvm::pdb::NativeSession::createFromExe(), llvm::jitlink::createLinkGraphFromCOFFObject(), llvm::jitlink::createLinkGraphFromMachOObject(), llvm::jitlink::createLinkGraphFromObject(), llvm::object::ObjectFile::createMachOObjectFile(), llvm::CodeViewYAML::fromDebugS(), llvm::msf::MSFBuilder::generateLayout(), getMemsetValue(), llvm::memprof::RawMemProfReader::hasFormat(), llvm::RawInstrProfReader< IntPtrT >::hasFormat(), llvm::IndexedInstrProfReader::hasFormat(), llvm::sampleprof::SampleProfileReaderRawBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderExtBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderCompactBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderGCC::hasFormat(), llvm::identify_magic(), initializeOptionalHeader(), isCodeViewDebugSubsection(), loadPdbFile(), llvm::pdb::InputFile::open(), llvm::sampleprof::SampleProfileReaderBinary::readMagicIdent(), startswith(), and validateSuperBlock().