LLVM: llvm::compression::zlib Namespace Reference
llvm::compression::zlib Namespace Reference
Functions
bool isAvailable ()
void compress (ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > &CompressedBuffer, int Level=DefaultCompression)
Error decompress (ArrayRef< uint8_t > Input, uint8_t *Output, size_t &UncompressedSize)
Error decompress (ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > &Output, size_t UncompressedSize)
Variables
constexpr int NoCompression = 0
constexpr int BestSpeedCompression = 1
constexpr int DefaultCompression = 6
constexpr int BestSizeCompression = 9
Function Documentation
compress()
void llvm::compression::zlib::compress (ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > & CompressedBuffer, int Level = DefaultCompression)
Definition at line 107 of file Compression.cpp.
References __msan_unpoison, assert(), llvm::ArrayRef< T >::data(), llvm::report_bad_alloc_error(), llvm::SmallVectorImpl< T >::resize_for_overwrite(), llvm::ArrayRef< T >::size(), and llvm::SmallVectorImpl< T >::truncate().
Referenced by llvm::collectPGOFuncNameStrings(), llvm::compression::compress(), and llvm::coverage::CoverageFilenamesSectionWriter::write().
decompress() [1/2]
Error llvm::compression::zlib::decompress (ArrayRef< uint8_t > Input, SmallVectorImpl< uint8_t > & Output, size_t UncompressedSize)
Definition at line 135 of file Compression.cpp.
References decompress(), E, llvm::SmallVectorImpl< T >::resize_for_overwrite(), and llvm::SmallVectorImpl< T >::truncate().
decompress() [2/2]
Error llvm::compression::zlib::decompress (ArrayRef< uint8_t > Input, uint8_t * Output, size_t & UncompressedSize)
Definition at line 123 of file Compression.cpp.
References __msan_unpoison, convertZlibCodeToString(), llvm::ArrayRef< T >::data(), llvm::inconvertibleErrorCode(), llvm::ArrayRef< T >::size(), llvm::Error::success(), and llvm::RISCVRVC::uncompress().
Referenced by decompress(), llvm::compression::decompress(), and llvm::readPGOFuncNameStrings().
isAvailable()
bool llvm::compression::zlib::isAvailable ()
Definition at line 105 of file Compression.cpp.
Referenced by llvm::collectPGOFuncNameStrings(), llvm::compression::getReasonIfUnsupported(), llvm::readPGOFuncNameStrings(), and llvm::coverage::CoverageFilenamesSectionWriter::write().
Variable Documentation
BestSizeCompression
constexpr int llvm::compression::zlib::BestSizeCompression = 9 constexpr
Definition at line 39 of file Compression.h.
Referenced by llvm::collectPGOFuncNameStrings(), and llvm::coverage::CoverageFilenamesSectionWriter::write().
BestSpeedCompression
constexpr int llvm::compression::zlib::BestSpeedCompression = 1 constexpr
Definition at line 37 of file Compression.h.
DefaultCompression
constexpr int llvm::compression::zlib::DefaultCompression = 6 constexpr
Definition at line 38 of file Compression.h.
NoCompression
constexpr int llvm::compression::zlib::NoCompression = 0 constexpr
Definition at line 36 of file Compression.h.