LLVM: llvm::BitmaskEnumDetail Namespace Reference
llvm::BitmaskEnumDetail Namespace Reference
Functions
template<typename E >
constexpr std::underlying_type_t< E > Mask ()
Get a bitmask with 1s in all places up to the high-order bit of E's largest value.
template<typename E >
constexpr std::underlying_type_t< E > Underlying (E Val)
Check that Val is in range for E, and return Val cast to E's underlying type.
constexpr unsigned bitWidth (uint64_t Value)
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>>
constexpr E operator~ (E Val)
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>>
constexpr E operator| (E LHS, E RHS)
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>>
constexpr E operator& (E LHS, E RHS)
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>>
constexpr E operator^ (E LHS, E RHS)
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>>
E & operator|= (E &LHS, E RHS)
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>>
E & operator&= (E &LHS, E RHS)
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>>
E & operator^= (E &LHS, E RHS)
Function Documentation
bitWidth()
constexpr unsigned llvm::BitmaskEnumDetail::bitWidth (uint64_t Value) constexpr
Definition at line 97 of file BitmaskEnum.h.
Referenced by llvm::APFloat::convertToInteger().
Mask()
template<typename E > constexpr std::underlying_type_t<E> llvm::BitmaskEnumDetail::Mask () constexpr
Get a bitmask with 1s in all places up to the high-order bit of E's largest value.
Definition at line 80 of file BitmaskEnum.h.
References llvm::NextPowerOf2().
Referenced by BoUpSLP::ShuffleInstructionBuilder::add(), llvm::DwarfExpression::addAnd(), addConstantComments(), addMask(), llvm::MachineInstrBuilder::addRegMask(), llvm::LiveRegUnits::addRegMasked(), llvm::SIMachineFunctionInfo::addWorkGroupIDY(), llvm::SIMachineFunctionInfo::addWorkGroupIDZ(), llvm::M68kInstrInfo::AddZExt(), adjustForRedundantAnd(), adjustForTestUnderMask(), llvm::PPCRegisterInfo::adjustStackMapLiveOutMask(), llvm::X86RegisterInfo::adjustStackMapLiveOutMask(), adjustSubwordCmp(), llvm::MachineFunction::allocateRegMask(), llvm::MachineFunction::allocateShuffleMask(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), llvm::SITargetLowering::allocateSpecialInputVGPRs(), llvm::SITargetLowering::allocateSpecialInputVGPRsFixed(), allocateVGPR32Input(), llvm::SystemZInstrInfo::analyzeCompare(), llvm::HexagonInstrInfo::analyzeCompare(), llvm::PPCInstrInfo::analyzeCompare(), llvm::MipsAsmBackend::applyFixup(), ApplyX86MaskOn1BitsVec(), llvm::lowertypetests::BitSetBuilder::build(), buildCallOperands(), buildFromShuffleMostly(), llvm::TargetLowering::buildLegalVectorShuffle(), buildShuffleEntryMask(), llvm::MachineIRBuilder::buildShuffleVector(), buildUseMask(), llvm::MachineIRBuilder::buildZExtInReg(), calculatePreExtendType(), canCreateUndefOrPoison(), canEvaluateShiftedShift(), canEvaluateShuffled(), canEvaluateTruncated(), canLowerByDroppingElements(), canonicalizeInsertSplat(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeShuffleMaskWithCommute(), canonicalizeShuffleMaskWithHorizOp(), canonicalizeShuffleWithBinOps(), canUseShiftPair(), canWidenShuffleElements(), llvm::APInt::clearBit(), llvm::SmallBitVector::clearBitsInMask(), llvm::BitVector::clearBitsInMask(), llvm::SmallBitVector::clearBitsNotInMask(), llvm::BitVector::clearBitsNotInMask(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), collectHWRegs(), collectShuffleElements(), collectSingleShuffleElements(), combine_CC(), combineAddOfPMADDWD(), combineAnd(), combineBasicSADPattern(), combineCMP(), combineConcatVectorOfExtracts(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineDeMorganOfBoolean(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFP_ROUND(), combineGatherScatter(), combineINSERT_SUBVECTOR(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), combineMaskedLoad(), combineMaskedStore(), combineMinMaxReduction(), combineMulToPMULDQ(), combineOr(), combineRedundantDWordShuffle(), combineSelect(), combineShiftAnd1ToBitTest(), combineShiftLeft(), combineShuffleOfBitcast(), combineShuffleOfConcatUndef(), combineShuffleToAnyExtendVectorInreg(), combineShuffleToFMAddSub(), combineShuffleToZeroExtendVectorInReg(), combineTargetShuffle(), combineTruncationShuffle(), combineVectorTruncationWithPACKUS(), combineVPDPBUSDPattern(), combineX86GatherScatter(), combineX86ShuffleChain(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), commitFpm(), llvm::InstCombinerImpl::commonCastTransforms(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::X86InstrInfo::commuteInstructionImpl(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::ShuffleVectorInst::commuteShuffleMask(), llvm::TargetRegisterInfo::composeSubRegIndexLaneMask(), computeExtractCost(), computeGREVOrGORC(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::computeKnownBitsFromRangeMetadata(), llvm::GISelKnownBits::computeNumSignBits(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), computeRecurrenceType(), llvm::SelectionDAG::computeVectorKnownZeroElements(), computeZeroableShuffleElements(), conjugateICmpMask(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::APFixedPoint::convert(), convertFixedMaskToScalableVector(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), llvm::detail::TrailingZerosCounter< T, SizeOfT >::count(), llvm::createBitMaskForGaps(), llvm::mca::InstrBuilder::createInstruction(), llvm::createInterleaveMask(), llvm::IRBuilderBase::CreateMaskedCompressStore(), llvm::IRBuilderBase::CreateMaskedExpandLoad(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::IRBuilderBase::CreateMaskedStore(), createPackShuffleMask(), llvm::MachineOperand::CreateRegLiveOut(), llvm::MachineOperand::CreateRegMask(), llvm::createSequentialMask(), llvm::MachineOperand::CreateShuffleMask(), createShuffleMaskFromVSELECT(), createShuffleStride(), llvm::IRBuilderBase::CreateShuffleVector(), llvm::createSplat2ShuffleMask(), llvm::createStrideMask(), createTblShuffleForZExt(), llvm::createUnaryMask(), llvm::createUnpackShuffleMask(), llvm::IRBuilderBase::CreateVectorSplice(), llvm::mca::ExecuteStage::cycleEnd(), DecodeMSRMask(), DecodePRFMRegInstruction(), llvm::decomposeBitTestICmp(), decomposeBitTestICmp(), llvm::RISCVInstrInfo::decomposeMachineOperandsTargetFlags(), llvm::AArch64InstrInfo::decomposeMachineOperandsTargetFlags(), llvm::ARMBaseInstrInfo::decomposeMachineOperandsTargetFlags(), llvm::PPCInstrInfo::decomposeMachineOperandsTargetFlags(), Status::delta(), detectShiftUntilBitTestIdiom(), llvm::DWARFContext::dump(), elementPairIsContiguous(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::LoongArchTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::RISCVTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::LoongArchTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::RISCVTargetLowering::emitMaskedAtomicRMWIntrinsic(), EmitMaskedTruncSStore(), llvm::UnwindOpcodeAssembler::EmitRegSave(), EmitX86ScalarSelect(), EmitX86Select(), llvm::AArch64TargetLowering::EmitZero(), equalizeVectorShuffleLengths(), evaluateInDifferentElementOrder(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::M68kInstrInfo::ExpandMOVEM(), llvm::AArch64_IMM::expandMOVImm(), expandMOVImmSimple(), expandV4F32ToV2F64(), llvm::TargetLowering::expandVPBITREVERSE(), llvm::TargetLowering::expandVPBSWAP(), extractBits(), extractShiftForRotate(), extractVector(), fcmpToClassTest(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), llvm::AMDGPUFunctionArgInfo::fixedABILayout(), foldAnyOrAllBitsSet(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), foldConstantInsEltIntoShuffle(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpWithTrunc(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldInsSequenceIntoSplat(), llvm::InstCombinerImpl::foldIRemByPowerOfTwoToBitTest(), foldLogOpOfMaskedICmps(), foldMaskAndShiftToExtract(), foldMaskAndShiftToScale(), foldMaskedShiftToBEXTR(), foldMaskedShiftToScaledMask(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleOfSelectShuffle(), foldSelectShuffleWith1Binop(), foldShiftedShift(), foldShuffledIntrinsicOperands(), foldShuffleOfConcatUndefs(), llvm::InstSimplifyFolder::FoldShuffleVector(), llvm::ConstantFolder::FoldShuffleVector(), llvm::TargetFolder::FoldShuffleVector(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldTruncShuffle(), llvm::InstCombinerImpl::foldVectorBinop(), foreachUnit(), genShuffleBland(), getARClassRegisterMask(), getAVX2GatherNode(), llvm::getBitwiseNotOperand(), getBoolVecFromMask(), getCmpOperandFoldingProfit(), getDefaultVLOps(), getDemandedSrcElements(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), llvm::SelectionDAG::getExtLoadVP(), llvm::SelectionDAG::getExtStridedLoadVP(), getFauxShuffleMask(), llvm::DWARFUnitIndex::getFromHash(), getGatherNode(), llvm::VECustomDAG::getGatherScatterAddress(), getGeneralPermuteNode(), getHalfShuffleMask(), getInstReadLaneMask(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getIntrinsicInstrCost(), llvm::VECustomDAG::getLegalReductionOpVVP(), llvm::SelectionDAG::getLoadVP(), llvm::ShuffleVectorSDNode::getMask(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedStore(), llvm::ShuffleVectorSDNode::getMaskElt(), getMaskForArgs(), getMaskNode(), getMOVL(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SIRegisterInfo::getNumCoveredRegs(), llvm::MipsTargetLowering::getOpndList(), getPack(), getPrefetchNode(), getPSHUFShuffleMask(), llvm::rdf::PhysicalRegisterInfo::getRefForUnit(), llvm::RegScavenger::getRegsAvailable(), llvm::mca::Scheduler::getResourceID(), llvm::mca::getResourceStateIndex(), getScalarMaskingNode(), getScatterNode(), llvm::SelectionDAG::getSetCCVP(), getShiftedValue(), getShuffleComment(), llvm::SystemZTTIImpl::getShuffleCost(), llvm::RISCVTTIImpl::getShuffleCost(), llvm::X86TTIImpl::getShuffleCost(), llvm::GCNTTIImpl::getShuffleCost(), llvm::ARMTTIImpl::getShuffleCost(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getShuffleCost(), llvm::TargetTransformInfo::getShuffleCost(), llvm::getShuffleDemandedElts(), llvm::ShuffleVectorInst::getShuffleMask(), getShuffleMaskIndexOfOneElementFromOp0IntoOp1(), llvm::getShuffleMaskWithWidestElts(), llvm::ConstantExpr::getShuffleVector(), llvm::getSplatIndex(), llvm::ShuffleVectorSDNode::getSplatIndex(), llvm::Constant::getSplatValue(), llvm::SelectionDAG::getStoreVP(), llvm::SelectionDAG::getStridedLoadVP(), llvm::SelectionDAG::getStridedStoreVP(), getSVEPredicateBitCast(), getTargetConstantBitsFromNode(), getTargetShuffleAndZeroables(), getTargetShuffleInputs(), getTargetShuffleMask(), getTargetVShiftNode(), getTestUnderMaskCond(), llvm::SelectionDAG::getTruncStoreVP(), llvm::SelectionDAG::getTruncStridedStoreVP(), getUnpackh(), getUnpackl(), getUsefulBitsFromBFM(), getUsefulBitsFromOrWithShiftedReg(), getV4X86ShuffleImm(), getV4X86ShuffleImm8ForMask(), getValueFromICmpCondition(), getVectorMaskingNode(), llvm::SelectionDAG::getVectorShuffle(), getVectorShuffle(), llvm::SelectionDAG::getVPLogicalNOT(), llvm::SelectionDAG::getVPPtrExtOrTrunc(), llvm::SelectionDAG::getVPZExtOrTrunc(), getVSlidedown(), getVSlideup(), getX86MaskVec(), group2Shuffle(), hasIdenticalHalvesShuffleMask(), haveNoCommonBitsSetCommutative(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::improveShuffleKindFromMask(), llvm::TargetLowering::IncrementMemoryAddress(), llvm::mca::initializeUsedResources(), llvm::SIInstrInfo::insertIndirectBranch(), insertInteger(), insertSEH(), insertVector(), llvm::PPCTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::GCNTTIImpl::instCombineIntrinsic(), instCombineLD1GatherIndex(), instCombineST1ScatterIndex(), instCombineSVECmpNE(), instrumentMaskedLoadOrStore(), Status::intersect(), llvm::inversePermutation(), is128BitLaneCrossingShuffleMask(), is128BitLaneRepeatedShuffleMask(), is128BitUnpackShuffleMask(), is256BitLaneRepeatedShuffleMask(), isAddSubOrSubAdd(), isAddSubOrSubAddMask(), isAlternatingShuffMask(), llvm::GCNTTIImpl::isAlwaysUniform(), isAnyInRange(), isAnyZero(), isAnyZeroOrUndef(), isBroadcastShuffleMask(), Status::isCombinable(), Status::isCompatible(), isConcatMask(), isConstantIntVector(), isCTTZTable(), isDeInterleaveMask(), isDeInterleaveMaskOfFactor(), isDeinterleavingMask(), llvm::MCInstrAnalysis::isDependencyBreaking(), llvm::TargetSubtargetInfo::isDependencyBreaking(), isElementRotate(), isExtractHiElt(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), isFixedVectorShuffle(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), llvm::X86TargetLowering::isGuaranteedNotToBeUndefOrPoisonForTargetNode(), isHorizontalBinOp(), isIdentity(), llvm::ShuffleVectorInst::isIdentityMask(), isIdentityMaskImpl(), llvm::ShuffleVectorInst::isIdentityWithPadding(), llvm::ShuffleVectorInst::isInsertSubvectorMask(), isInterleaveShuffle(), isInterleavingMask(), isKnownNonZero(), isLaneCrossingShuffleMask(), IsLegalOffset(), isLowHalfOnly(), llvm::RISCVTargetLowering::isMaskAndCmp0FoldingBeneficial(), llvm::SystemZTargetLowering::isMaskAndCmp0FoldingBeneficial(), llvm::ARMTargetLowering::isMaskAndCmp0FoldingBeneficial(), llvm::AArch64TargetLowering::isMaskAndCmp0FoldingBeneficial(), isMultiLaneShuffleMask(), isNonZeroElementsInOrder(), isNoopOrBroadcastShuffleMask(), isNoopShuffleMask(), llvm::ShuffleVectorInst::isOneUseSingleSourceMask(), isReInterleaveMask(), isRepeatedNonIdentityClusteredMask(), isRepeatedShuffleMask(), isRepeatedTargetShuffleMask(), llvm::ShuffleVectorInst::isReplicationMask(), isReplicationMaskWithParams(), llvm::ShuffleVectorInst::isReverseMask(), llvm::ShuffleVectorInst::isSelectMask(), isSequentialOrUndefInRange(), isSequentialOrUndefOrZeroInRange(), isShiftedMask(), isShuffleEquivalent(), isShuffleExtractingFromLHS(), isShuffleMaskInputInPlace(), isSingleSHUFPSMask(), llvm::ShuffleVectorInst::isSingleSourceMask(), isSingleSourceMaskImpl(), llvm::ShuffleVectorSDNode::isSplat(), llvm::SelectionDAG::isSplatValue(), llvm::ShuffleVectorInst::isSpliceMask(), llvm::AArch64_AM::isSVECpyImm(), isTargetShuffleEquivalent(), llvm::ShuffleVectorInst::isTransposeMask(), isUndef(), isUndefInRange(), isUndefLowerHalf(), isUndefOrEqual(), isUndefOrInRange(), isUndefOrZeroInRange(), isUndefOrZeroOrInRange(), isUndefUpperHalf(), isUnpackWdShuffleMask(), llvm::ShuffleVectorInst::isValidOperands(), llvm::X86TargetLowering::isVectorClearMaskLegal(), llvm::SystemZVectorConstantInfo::isVectorConstantLegal(), isVMOVModifiedImm(), llvm::ShuffleVectorInst::isZeroEltSplatMask(), llvm::TargetLowering::LegalizeSetCCCondCode(), LLVMBuildShuffleVector(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::AMDGPUTargetLowering::loadInputValue(), lower128BitShuffle(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), lower256BitShuffle(), lower512BitShuffle(), LowerAsSplatVectorLoad(), LowerBITREVERSE_XOP(), llvm::LegalizerHelper::lowerBswap(), lowerBUILD_VECTOR(), LowerBuildVectorv4x32(), llvm::AArch64CallLowering::lowerCall(), llvm::AMDGPUCallLowering::lowerCall(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerEXTEND_VECTOR_INREG(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), llvm::SparcTargetLowering::LowerF128Compare(), LowerFABSorFNEG(), lowerFP_TO_INT_SAT(), LowerFunnelShift(), llvm::LegalizerHelper::lowerFunnelShiftAsShifts(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::LegalizerHelper::lowerInsert(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINSERT_VECTOR_ELT_i1(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), LowerINTRINSIC_W_CHAIN(), llvm::LegalizerHelper::lowerISFPCLASS(), LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), LowerMSTORE(), LowerMULH(), llvm::RISCVTargetLowering::LowerOperation(), lowerReductionSeq(), LowerShiftByScalarImmediate(), lowerShuffleAsBitBlend(), lowerShuffleAsBitMask(), lowerShuffleAsBitRotate(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsLanePermuteAndPermute(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsSplitOrBlend(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVALIGN(), lowerShuffleAsVTRUNC(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleOfExtractsAsVperm(), lowerShufflePairAsUNPCKAndPermute(), lowerShuffleToEXPAND(), llvm::LegalizerHelper::lowerShuffleVector(), lowerShuffleWithPACK(), lowerShuffleWithPERMV(), lowerShuffleWithPSHUFB(), lowerShuffleWithSHUFPD(), lowerShuffleWithSHUFPS(), lowerShuffleWithSSE4A(), lowerShuffleWithUndefHalf(), lowerShuffleWithUNPCK(), lowerShuffleWithUNPCK256(), lowerShuffleWithVPMOV(), llvm::AMDGPUCallLowering::lowerTailCall(), lowerToAddSubOrFMAddSub(), llvm::VETargetLowering::lowerToTLSGeneralDynamicModel(), llvm::VETargetLowering::lowerToVVP(), lowerV16F32Shuffle(), lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV4X128Shuffle(), lowerV64I8Shuffle(), lowerV8F16Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLEAsVNSRL(), lowerVECTOR_SHUFFLEAsVSlidedown(), LowerVECTOR_SHUFFLEUsingOneOff(), LowerVectorAllZero(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorIntrinsicScalars(), lowerVSELECTtoVectorShuffle(), LowerVSETCC(), llvm::VETargetLowering::lowerVVP_GATHER_SCATTER(), llvm::VETargetLowering::lowerVVP_LOAD_STORE(), llvm::SelectionDAG::MaskedValueIsAllOnes(), llvm::GISelKnownBits::maskedValueIsZero(), llvm::MaskedValueIsZero(), llvm::InstCombiner::MaskedValueIsZero(), llvm::SelectionDAG::MaskedValueIsZero(), MaskedValueIsZero(), llvm::SCEVWrapPredicate::maskFlags(), llvm::ScalarEvolution::maskFlags(), llvm::maskIsAllOneOrUndef(), llvm::maskIsAllZeroOrUndef(), maskMatters(), llvm::DwarfExpression::maskSubRegister(), llvm::PatternMatch::match(), llvm::PatternMatch::m_Mask::match(), llvm::PatternMatch::m_ZeroMask::match(), llvm::PatternMatch::m_SpecificMask::match(), llvm::PatternMatch::m_SplatOrUndefMask::match(), match1BitShuffleAsKSHIFT(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), llvm::CombinerHelper::matchCombineShuffleVector(), matchEXT(), matchFunnelShift(), matchLogicBlend(), llvm::CombinerHelper::matchNarrowBinopFeedingAnd(), matchRotateHalf(), matchShuffleAsBitRotate(), matchShuffleAsBlend(), matchShuffleAsByteRotate(), matchShuffleAsElementRotate(), matchShuffleAsEXTRQ(), matchShuffleAsInsertPS(), matchShuffleAsINSERTQ(), matchShuffleAsShift(), matchShuffleAsVTRUNC(), matchShuffleWithSHUFPD(), matchSplatAsGather(), AMDGPUPostLegalizerCombinerHelper::matchUCharToFloat(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), llvm::CombinerHelper::matchUndefShuffleVectorMask(), MatchVectorAllZeroTest(), Status::merge(), mergeEltWithShuffle(), Status::mergeUnknown(), llvm::MCSymbol::modifyFlags(), llvm::LegalizerHelper::moreElementsVectorShuffle(), narrowShuffle(), llvm::narrowShuffleMaskElts(), llvm::BitVector::operator<<=(), Status::operator==(), llvm::BitVector::operator>>=(), llvm::FeatureBitset::operator[](), llvm::BitVector::operator[](), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), optimizeLogicalImm(), outputQualifierIfPresent(), packSegmentMask(), parseRegMask(), partitionShuffleOfConcats(), performANDCombine(), PerformANDCombine(), PerformBFICombine(), performBSPExpandForSVE(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performExtractsShuffleAction(), performFP_TO_INTCombine(), performMaskedGatherScatterCombine(), performMSTORECombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformMVEVMULLCombine(), performORCombine(), PerformORCombineToBFI(), PerformReduceShuffleCombine(), performSelectCombine(), PerformSHLSimplify(), llvm::AMDGPUTargetLowering::performSrlCombine(), performSVEAndCombine(), performTruncateCombine(), performUnpackCombine(), PerformVECREDUCE_ADDCombine(), llvm::possiblyDemandedEltsInMask(), prepareTS1AM(), llvm::MachineOperand::print(), llvm::VPInterleaveRecipe::print(), llvm::VPBranchOnMaskRecipe::print(), printBitField(), llvm::ARMInstPrinter::printMSRMaskOperand(), llvm::AArch64InstPrinter::printRangePrefetchAlias(), PrintShuffleMask(), printSwizzleBitmask(), llvm::MachineOperand::printTargetFlags(), llvm::ARMInstPrinter::printThumbITMask(), llvm::ARMInstPrinter::printVPTMask(), llvm::AArch64_AM::processLogicalImmediate(), llvm::processShuffleMasks(), llvm::SimpleBitstreamCursor::Read(), llvm::SimpleBitstreamCursor::ReadVBR(), llvm::SimpleBitstreamCursor::ReadVBR64(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::AArch64TargetLowering::ReconstructShuffle(), reorderOrder(), reorderReuses(), llvm::reorderScalars(), ReplaceAddWithADDP(), llvm::RISCVTargetLowering::ReplaceNodeResults(), replaceShuffleOfInsert(), llvm::Thumb2InstrInfo::ReplaceTailWithBranchTo(), llvm::BitVector::reset(), llvm::SmallBitVector::reset(), llvm::mca::ResourceManager::resolveResourceMask(), resolveTargetShuffleFromZeroables(), resolveTargetShuffleInputsAndMask(), resolveZeroablesFromTargetShuffle(), llvm::mca::ResourceManager::ResourceManager(), llvm::M68kFrameLowering::restoreCalleeSavedRegisters(), llvm::rewriteARMFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteT2FrameIndex(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), scaleShuffleElements(), SelectPairHalf(), llvm::HvxSelector::selectShuffle(), llvm::RISCVDAGToDAGISel::selectSHXADD_UWOp(), llvm::RISCVDAGToDAGISel::selectSHXADDOp(), selectUmullSmull(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::RISCVDAGToDAGISel::selectZExtBits(), llvm::LoongArchDAGToDAGISel::selectZExti32(), llvm::BitVector::set(), llvm::SmallBitVector::set(), llvm::APInt::setBit(), llvm::SmallBitVector::setBitsInMask(), llvm::BitVector::setBitsInMask(), llvm::SmallBitVector::setBitsNotInMask(), llvm::BitVector::setBitsNotInMask(), llvm::MachineInstr::setFlags(), llvm::Function::setIsMaterializable(), llvm::ShuffleVectorInst::setShuffleMask(), llvm::mca::Instruction::setUsedBuffers(), shouldUseAndMask(), ShrinkLoadReplaceStoreWithStore(), llvm::ShuffleVectorConstantExpr::ShuffleVectorConstantExpr(), llvm::ShuffleVectorInst::ShuffleVectorInst(), simplifyAndInst(), simplifyBinaryIntrinsic(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::ARMTargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), simplifySelectWithFakeICmpEq(), llvm::TargetLowering::SimplifySetCC(), simplifyShuffleOfShuffle(), llvm::simplifyShuffleVectorInst(), simplifyShuffleVectorInst(), simplifyX86MaskedLoad(), simplifyX86MaskedStore(), llvm::M68kFrameLowering::spillCalleeSavedRegisters(), splitAndLowerShuffle(), splitMask(), Status::Status(), stripConstantMask(), stripModuloOnShift(), SwapN(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), translateSetCCForBranch(), truncateVectorWithPACK(), tryCombineCRC32(), llvm::LegalizationArtifactCombiner::tryCombineZExt(), tryDemorganOfBooleanCondition(), tryFormConcatFromShuffle(), tryPromoteAllocaToVector(), trySequenceOfOnes(), tryToMergePartialOverlappingStores(), tryWidenMaskForShuffle(), unrollVectorShift(), llvm::AArch64RegisterInfo::UpdateCustomCallPreservedMask(), updateImm(), updateLiveIn(), upgradeMaskedCompare(), UpgradeMaskedLoad(), upgradeMaskedMove(), UpgradeMaskedStore(), UpgradeMaskToInt(), upgradePMULDQ(), UpgradeX86ALIGNIntrinsics(), UpgradeX86BinaryIntrinsics(), upgradeX86ConcatShift(), upgradeX86Rotate(), llvm::mca::DefaultResourceStrategy::used(), vectorizeExtractedCast(), llvm::LiveInterval::verify(), llvm::InstCombinerImpl::visitAShr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitInsertElementInst(), llvm::InstCombinerImpl::visitLShr(), llvm::InstCombinerImpl::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::InstCombinerImpl::visitSRem(), llvm::widenShuffleMaskElts(), write32AArch64Addr(), llvm::write32AArch64Addr(), and llvm::writeIndex().
operator&()
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>> constexpr E llvm::BitmaskEnumDetail::operator& (E LHS, E RHS) constexpr
Definition at line 112 of file BitmaskEnum.h.
References E, LHS, RHS, and Underlying().
operator&=()
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>> E& llvm::BitmaskEnumDetail::operator&= (E & LHS, E RHS)
Definition at line 131 of file BitmaskEnum.h.
References LHS, and RHS.
operator^()
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>> constexpr E llvm::BitmaskEnumDetail::operator^ (E LHS, E RHS) constexpr
Definition at line 117 of file BitmaskEnum.h.
References E, LHS, RHS, and Underlying().
operator^=()
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>> E& llvm::BitmaskEnumDetail::operator^= (E & LHS, E RHS)
Definition at line 137 of file BitmaskEnum.h.
References LHS, and RHS.
operator|()
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>> constexpr E llvm::BitmaskEnumDetail::operator| (E LHS, E RHS) constexpr
Definition at line 107 of file BitmaskEnum.h.
References E, LHS, RHS, and Underlying().
operator|=()
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>> E& llvm::BitmaskEnumDetail::operator|= (E & LHS, E RHS)
Definition at line 125 of file BitmaskEnum.h.
References LHS, and RHS.
operator~()
template<typename E , typename = std::enable_if_t<is_bitmask_enum<E>::value>> constexpr E llvm::BitmaskEnumDetail::operator~ (E Val) constexpr
Definition at line 102 of file BitmaskEnum.h.
References E, and Underlying().
Underlying()
template<typename E > constexpr std::underlying_type_t<E> llvm::BitmaskEnumDetail::Underlying (E Val) constexpr
Check that Val is in range for E, and return Val cast to E's underlying type.
Definition at line 90 of file BitmaskEnum.h.
References assert().
Referenced by operator&(), operator^(), operator|(), and operator~().