LLVM: llvm::orc::rt_bootstrap Namespace Reference
llvm::orc::rt_bootstrap Namespace Reference
Classes
class ExecutorSharedMemoryMapperService
class SimpleExecutorDylibManager
Simple page-based allocator.
class SimpleExecutorMemoryManager
Simple page-based allocator.
Functions
template<typename WriteT , typename SPSWriteT >
static llvm::orc::shared::CWrapperFunctionResult writeUIntsWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionResult writeBuffersWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionResult runAsMainWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionResult runAsVoidFunctionWrapper (const char *ArgData, size_t ArgSize)
static llvm::orc::shared::CWrapperFunctionResult runAsIntFunctionWrapper (const char *ArgData, size_t ArgSize)
void addTo (StringMap< ExecutorAddr > &M)
Function Documentation
addTo()
void llvm::orc::rt_bootstrap::addTo (StringMap< ExecutorAddr > & M)
Definition at line 80 of file OrcRTBootstrap.cpp.
References llvm::orc::rt::DeregisterEHFrameSectionWrapperName, llvm::orc::ExecutorAddr::fromPtr(), llvm_orc_deregisterEHFrameSectionWrapper(), llvm_orc_registerEHFrameSectionWrapper(), M, llvm::orc::rt::MemoryWriteBuffersWrapperName, llvm::orc::rt::MemoryWriteUInt16sWrapperName, llvm::orc::rt::MemoryWriteUInt32sWrapperName, llvm::orc::rt::MemoryWriteUInt64sWrapperName, llvm::orc::rt::MemoryWriteUInt8sWrapperName, llvm::orc::rt::RegisterEHFrameSectionWrapperName, runAsIntFunctionWrapper(), llvm::orc::rt::RunAsIntFunctionWrapperName, runAsMainWrapper(), llvm::orc::rt::RunAsMainWrapperName, runAsVoidFunctionWrapper(), llvm::orc::rt::RunAsVoidFunctionWrapperName, writeBuffersWrapper(), and writeUIntsWrapper().
Referenced by llvm::orc::SimpleRemoteEPCServer::defaultBootstrapSymbols().
runAsIntFunctionWrapper()
static llvm::orc::shared::CWrapperFunctionResult llvm::orc::rt_bootstrap::runAsIntFunctionWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 70 of file OrcRTBootstrap.cpp.
References Arg, handle, llvm::release, llvm::orc::runAsIntFunction(), and llvm::orc::ExecutorAddr::toPtr().
Referenced by addTo().
runAsMainWrapper()
static llvm::orc::shared::CWrapperFunctionResult llvm::orc::rt_bootstrap::runAsMainWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 49 of file OrcRTBootstrap.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, handle, int, llvm::release, llvm::orc::runAsMain(), and llvm::orc::ExecutorAddr::toPtr().
Referenced by addTo().
runAsVoidFunctionWrapper()
static llvm::orc::shared::CWrapperFunctionResult llvm::orc::rt_bootstrap::runAsVoidFunctionWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 60 of file OrcRTBootstrap.cpp.
References handle, llvm::release, llvm::orc::runAsVoidFunction(), and llvm::orc::ExecutorAddr::toPtr().
Referenced by addTo().
writeBuffersWrapper()
static llvm::orc::shared::CWrapperFunctionResult llvm::orc::rt_bootstrap::writeBuffersWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 37 of file OrcRTBootstrap.cpp.
References handle, memcpy(), llvm::release, and llvm::RISCVFenceField::W.
Referenced by addTo().
writeUIntsWrapper()
template<typename WriteT , typename SPSWriteT > static llvm::orc::shared::CWrapperFunctionResult llvm::orc::rt_bootstrap::writeUIntsWrapper (const char * ArgData, size_t ArgSize) static
Definition at line 26 of file OrcRTBootstrap.cpp.
References handle, llvm::release, and llvm::RISCVFenceField::W.
Referenced by addTo().