LLVM: llvm::RISCVRVC Namespace Reference
llvm::RISCVRVC Namespace Reference
Functions
bool compress (MCInst &OutInst, const MCInst &MI, const MCSubtargetInfo &STI)
bool uncompress (MCInst &OutInst, const MCInst &MI, const MCSubtargetInfo &STI)
Function Documentation
compress()
bool llvm::RISCVRVC::compress (MCInst & OutInst, const MCInst & MI, const MCSubtargetInfo & STI)
Definition at line 207 of file RISCVBaseInfo.cpp.
References MI.
uncompress()
bool llvm::RISCVRVC::uncompress (MCInst & OutInst, const MCInst & MI, const MCSubtargetInfo & STI)
Definition at line 212 of file RISCVBaseInfo.cpp.
References MI.
Referenced by llvm::compression::zlib::decompress(), llvm::RISCVInstPrinter::printInst(), and llvm::RISCVAsmBackend::relaxInstruction().