LLVM: llvm::detail Namespace Reference
llvm::detail Namespace Reference
Classes
class AlignAdapter
class AllocatorHolder
class AllocatorHolder< Alloc & >
struct AnalysisPassConcept
Abstract concept of an analysis pass.
struct AnalysisPassModel
Wrapper to model the analysis pass concept.
struct AnalysisResultConcept
Abstract concept of an analysis result.
struct AnalysisResultModel
Wrapper to model the analysis result concept.
struct AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, InvalidatorT, false >
Specialization of AnalysisResultModel which provides the default invalidate functionality.
struct AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, InvalidatorT, true >
Specialization of AnalysisResultModel which delegates invalidate handling to ResultT.
class BCField
Convenience base for all kinds of bitcode abbreviation fields.
class BCRecordCoding
Helper class for dealing with a scalar element in the middle of a record.
class BCRecordCoding< BCArray< ElementTy > >
Helper class for dealing with an array at the end of a record.
class BCRecordCoding< BCBlob >
Helper class for dealing with a blob at the end of a record.
class BCRecordCoding< ElementTy >
Helper class for dealing with a scalar element at the end of a record.
struct CanOutputToOStream
struct CheckedInt
class concat_range
Helper to store a sequence of ranges being concatenated and access them.
struct ConstantLog2
A tiny meta function to compute the log2 of a compile time constant.
struct ConstantLog2< 1 >
union copy_construction_triviality_helper
Internal utility to detect trivial copy construction.
struct declval< std::ostream & >()<< std::declval< T >())> >
struct DenseMapPair
struct DenseSetEmpty
class DenseSetImpl
Base class for DenseSet and DenseSmallSet.
class DenseSetPair
struct detector
struct detector< std::void_t< Op< Args... > >, Op, Args... >
class DoubleAPFloat
class enumerator
class enumerator_iter
class ErrorAdapter
struct ErrorHolder
class ErrorMatchesMono
class ErrorMessageMatches
struct ExpectedHolder
class first_or_second_type
Return a reference to the first or second member of a reference.
class format_adapter
struct fwd_or_bidi_tag
Helper which sets its type member to forward_iterator_tag if the category of IterT does not derive from bidirectional_iterator_tag, and to bidirectional_iterator_tag otherwise.
struct fwd_or_bidi_tag_impl
struct fwd_or_bidi_tag_impl< true >
class has_FormatProvider
class has_StreamOperator
struct HasPointerLikeTypeTraits
struct HasPointerLikeTypeTraits< T, decltype((sizeof(PointerLikeTypeTraits< T >)+sizeof(T)), void())>
class HelperFunctions
class IEEEFloat
class indexed_accessor_range_base
The class represents the base of a range of indexed_accessor_iterators.
struct is_array
A type trait whose value field is true if the given type is a BCArray (of any element kind).
struct is_cstring
struct IsPointerLike
struct IsPointerLike< T * >
struct last_type
A type trait whose type field is the last of its template parameters.
struct last_type< Head >
struct LeadingZerosCounter
class missing_format_adapter
union move_construction_triviality_helper
Internal utility to detect trivial move construction.
class PadAdapter
struct PassConcept
Template for the abstract base class used to dispatch polymorphically over pass objects.
struct PassModel
A template wrapper used to implement the polymorphic API.
struct PointerSumTypeHelper
A helper template for implementing PointerSumType.
struct PopulationCounter
struct PopulationCounter< T, 8 >
class provider_format_adapter
class PtrUseVisitorBase
Implementation of non-dependent functionality for PtrUseVisitor.
struct range_item_has_provider
struct RecordKeeperImpl
This class represents the internal implementation of the RecordKeeper.
class RepeatAdapter
struct result_pair
class ResultHasInvalidateMethod
SFINAE metafunction for computing whether ResultT provides an invalidate member function.
struct SafeIntIterator
class scope_exit
class stream_operator_format_adapter
class StringMapEntryMatcher
class StringMapEntryMatcherImpl
struct TrailingZerosCounter
union trivial_helper
struct TypesAreDistinct
struct TypesAreDistinct< T >
class TypeSwitchBase
class UniqueFunctionBase
struct unit
struct unit< std::micro >
struct unit< std::milli >
struct unit< std::nano >
struct unit< std::ratio< 1 > >
struct unit< std::ratio< 3600 > >
struct unit< std::ratio< 60 > >
struct use_char_formatter
struct use_double_formatter
struct use_integral_formatter
struct use_pointer_formatter
struct use_string_formatter
struct uses_format_member
struct uses_format_provider
struct uses_missing_provider
struct uses_stream_operator
class ValueIsMatcher
class ValueMatchesMono
class ValueMatchesPoly
struct Visitor
struct Visitor< HeadT >
struct Visitor< HeadT, TailTs... >
struct zip_common
struct zip_first
class zip_longest_iterator
class zip_longest_range
class zip_shortest
struct ZipLongestItemType
struct ZipLongestTupleType
class zippy
struct ZipTupleType
Typedefs
template<typename T >
using EnableIfTrivial = std::enable_if_t< llvm::is_trivially_move_constructible< T >::value &&std::is_trivially_destructible< T >::value >
template<typename CallableT , typename ThisT >
using EnableUnlessSameType = std::enable_if_t<!std::is_same< remove_cvref_t< CallableT >, ThisT >::value >
template<typename CallableT , typename Ret , typename... Params>
using EnableIfCallable = std::enable_if_t< std::disjunction< std::is_void< Ret >, std::is_same< decltype(std::declval< CallableT >()(std::declval< Params >()...)), Ret >, std::is_same< const decltype(std::declval< CallableT >()(std::declval< Params >()...)), Ret >, std::is_convertible< decltype(std::declval< CallableT >()(std::declval< Params >()...)), Ret > >::value >
template<typename RangeT >
using IterOfRange = decltype(std::begin(std::declval< RangeT & >()))
template<typename RangeT >
using ValueOfRange = std::remove_reference_t< decltype(*std::begin(std::declval< RangeT & >()))>
template<typename ZipType , typename... Iters>
using zip_traits = iterator_facade_base< ZipType, std::common_type_t< std::bidirectional_iterator_tag, typename std::iterator_traits< Iters >::iterator_category... >, typename ZipTupleType< Iters... >::type, typename std::iterator_traits< std::tuple_element_t< 0, std::tuple< Iters... > >>::difference_type, typename ZipTupleType< Iters... >::type *, typename ZipTupleType< Iters... >::type >
template<typename T >
using sort_trivially_copyable = std::conjunction< std::is_pointer< T >, std::is_trivially_copyable< typename std::iterator_traits< T >::value_type > >
template<typename... Types>
using has_blob = std::is_same< BCBlob, typename last_type< int, Types... >::type >
A type trait whose value field is true if the last type is BCBlob.
template<typename... Types>
using has_array = is_array< typename last_type< int, Types... >::type >
A type trait whose value field is true if the last type is a BCArray (of any element kind).
template<typename OptionalDerived , typename Default >
using SelfType = std::conditional_t< std::is_same< OptionalDerived, void >::value, Default, OptionalDerived >
A helper to derive the type to use with Self for cast traits, when the provided CRTP derived type is allowed to be void.
template<typename IterT >
using IterValue = typename std::iterator_traits< IterT >::value_type
Functions
hash_code hash_value (const IEEEFloat &Arg)
int ilogb (const IEEEFloat &Arg)
IEEEFloat scalbn (IEEEFloat X, int Exp, IEEEFloat::roundingMode)
IEEEFloat frexp (const IEEEFloat &Val, int &Exp, IEEEFloat::roundingMode RM)
hash_code hash_value (const DoubleAPFloat &Arg)
static unsigned combineHashValue (unsigned a, unsigned b)
Simplistic combination of 32-bit hash values into 32-bit hash values.
template<typename ValueT , typename MapTy , typename ValueInfoT >
bool operator== (const DenseSetImpl< ValueT, MapTy, ValueInfoT > &LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > &RHS)
Equality comparison for DenseSet.
template<typename ValueT , typename MapTy , typename ValueInfoT >
bool operator!= (const DenseSetImpl< ValueT, MapTy, ValueInfoT > &LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > &RHS)
Inequality comparison for DenseSet.
template<typename T , typename U >
bool canTypeFitValue (const U Value)
template<typename Iter >
Iter next_or_end (const Iter &I, const Iter &End)
template<typename Iter >
auto deref_or_none (const Iter &I, const Iter &End) -> std::optional< std::remove_const_t< std::remove_reference_t< decltype(*I)>>>
template<std::size_t i, typename R >
decltype(auto) get (const result_pair< R > &Pair)
template<typename Predicate , typename... Args>
bool all_of_zip_predicate_first (Predicate &&P, Args &&...args)
template<typename... ArgsThenPredicate, size_t... InputIndexes>
bool all_of_zip_predicate_last (std::tuple< ArgsThenPredicate... > argsThenPredicate, std::index_sequence< InputIndexes... >)
template<typename FieldTy >
static void emitOps (llvm::BitCodeAbbrev &abbrev)
Attaches the last field to an abbreviation.
template<typename FieldTy , typename Next , typename... Rest>
static void emitOps (llvm::BitCodeAbbrev &abbrev)
Attaches fields to an abbreviation.
template<typename PassT , typename IRUnitT , typename AnalysisManagerT , typename... ArgTs, size_t... Ns>
PassT::Result getAnalysisResultUnpackTuple (AnalysisManagerT &AM, IRUnitT &IR, std::tuple< ArgTs... > Args, std::index_sequence< Ns... >)
Actual unpacker of extra arguments in getAnalysisResult, passes only those tuple arguments that are mentioned in index_sequence.
template<typename PassT , typename IRUnitT , typename... AnalysisArgTs, typename... MainArgTs>
PassT::Result getAnalysisResult (AnalysisManager< IRUnitT, AnalysisArgTs... > &AM, IRUnitT &IR, std::tuple< MainArgTs... > Args)
Helper for partial unpacking of extra arguments in getAnalysisResult.
void printBumpPtrAllocatorStats (unsigned NumSlabs, size_t BytesAllocated, size_t TotalMemory)
template<typename T >
bool isPresent (const T &t)
template<typename T >
decltype(auto) unwrapValue (T &t)
template<typename Range >
auto reverse_if_helper (Range &&R, std::integral_constant< bool, false >)
template<typename Range >
auto reverse_if_helper (Range &&R, std::integral_constant< bool, true >)
template<bool B, typename Range >
auto reverse_if (Range &&R)
template<typename T >
std::enable_if_t< uses_format_member< T >::value, T > build_format_adapter (T &&Item)
template<typename T >
std::enable_if_t< uses_format_provider< T >::value, provider_format_adapter< T > > build_format_adapter (T &&Item)
template<typename T >
std::enable_if_t< uses_stream_operator< T >::value, stream_operator_format_adapter< T > > build_format_adapter (T &&Item)
template<typename T >
std::enable_if_t< uses_missing_provider< T >::value, missing_format_adapter< T > > build_format_adapter (T &&)
ErrorHolder TakeError (Error Err)
template<typename T >
ExpectedHolder< T > TakeExpected (Expected< T > &Exp)
template<typename T >
ExpectedHolder< T > TakeExpected (Expected< T > &&Exp)
void PrintTo (const ErrorHolder &Err, std::ostream *Out)
template<typename T >
void PrintTo (const ExpectedHolder< T > &Item, std::ostream *Out)
static void tcSetLeastSignificantBits (APInt::WordType *dst, unsigned parts, unsigned bits)
DoubleAPFloat scalbn (const DoubleAPFloat &Arg, int Exp, APFloat::roundingMode RM)
DoubleAPFloat frexp (const DoubleAPFloat &Arg, int &Exp, APFloat::roundingMode RM)
Typedef Documentation
EnableIfCallable
template<typename CallableT , typename Ret , typename... Params> using llvm::detail::EnableIfCallable = typedef std::enable_if_t<std::disjunction< std::is_void<Ret>, std::is_same<decltype(std::declval<CallableT>()(std::declval<Params>()...)), Ret>, std::is_same<const decltype(std::declval<CallableT>()(std::declval<Params>()...)), Ret>, std::is_convertible<decltype(std::declval<CallableT>()(std::declval<Params>()...)), Ret> >::value>
Definition at line 77 of file FunctionExtras.h.
EnableIfTrivial
template<typename T > using llvm::detail::EnableIfTrivial = typedef std::enable_if_t<llvm::is_trivially_move_constructible<T>::value && std::is_trivially_destructible<T>::value>
Definition at line 63 of file FunctionExtras.h.
EnableUnlessSameType
template<typename CallableT , typename ThisT > using llvm::detail::EnableUnlessSameType = typedef std::enable_if_t<!std::is_same<remove_cvref_t<CallableT>, ThisT>::value>
Definition at line 66 of file FunctionExtras.h.
has_array
template<typename... Types> using llvm::detail::has_array = typedef is_array<typename last_type<int, Types...>::type>
A type trait whose value field is true if the last type is a BCArray (of any element kind).
Definition at line 350 of file BitcodeConvenience.h.
has_blob
template<typename... Types> using llvm::detail::has_blob = typedef std::is_same<BCBlob, typename last_type<int, Types...>::type>
A type trait whose value field is true if the last type is BCBlob.
Definition at line 332 of file BitcodeConvenience.h.
IterOfRange
template<typename RangeT > using llvm::detail::IterOfRange = typedef decltype(std::begin(std::declval<RangeT &>()))
Definition at line 56 of file STLExtras.h.
IterValue
template<typename IterT > using llvm::detail::IterValue = typedef typename std::iterator_traits<IterT>::value_type
Definition at line 325 of file FormatProviders.h.
SelfType
template<typename OptionalDerived , typename Default > using llvm::detail::SelfType = typedef std::conditional_t<std::is_same<OptionalDerived, void>::value, Default, OptionalDerived>
A helper to derive the type to use with Self for cast traits, when the provided CRTP derived type is allowed to be void.
Definition at line 323 of file Casting.h.
sort_trivially_copyable
template<typename T > using llvm::detail::sort_trivially_copyable = typedef std::conjunction< std::is_pointer<T>, std::is_trivially_copyable<typename std::iterator_traits<T>::value_type> >
Definition at line 1677 of file STLExtras.h.
ValueOfRange
template<typename RangeT > using llvm::detail::ValueOfRange = typedef std::remove_reference_t<decltype(*std::begin(std::declval<RangeT &>()))>
Definition at line 60 of file STLExtras.h.
zip_traits
template<typename ZipType , typename... Iters> using llvm::detail::zip_traits = typedef iterator_facade_base< ZipType, std::common_type_t< std::bidirectional_iterator_tag, typename std::iterator_traits<Iters>::iterator_category...>, typename ZipTupleType<Iters...>::type, typename std::iterator_traits< std::tuple_element_t<0, std::tuple<Iters...> >>::difference_type, typename ZipTupleType<Iters...>::type *, typename ZipTupleType<Iters...>::type>
Definition at line 762 of file STLExtras.h.
Function Documentation
all_of_zip_predicate_first()
template<typename Predicate , typename... Args> bool llvm::detail::all_of_zip_predicate_first (Predicate && P, Args &&... args)
Definition at line 2271 of file STLExtras.h.
References llvm::cl::apply(), args, llvm::sys::path::end(), it, P, z, and llvm::zip().
Referenced by all_of_zip_predicate_last().
all_of_zip_predicate_last()
template<typename... ArgsThenPredicate, size_t... InputIndexes> bool llvm::detail::all_of_zip_predicate_last (std::tuple< ArgsThenPredicate... > argsThenPredicate, std::index_sequence< InputIndexes... >)
Definition at line 2286 of file STLExtras.h.
References all_of_zip_predicate_first().
Referenced by llvm::all_of_zip().
build_format_adapter() [1/4]
template<typename T > std::enable_if_t<uses_missing_provider<T>::value, missing_format_adapter<T> > llvm::detail::build_format_adapter (T &&)
Definition at line 157 of file FormatVariadicDetails.h.
build_format_adapter() [2/4]
template<typename T > std::enable_if_t<uses_format_member<T>::value, T> llvm::detail::build_format_adapter (T && Item)
Definition at line 132 of file FormatVariadicDetails.h.
Referenced by llvm::detail::AlignAdapter< T >::format(), llvm::detail::PadAdapter< T >::format(), llvm::detail::RepeatAdapter< T >::format(), and llvm::formatv().
build_format_adapter() [3/4]
template<typename T > std::enable_if_t<uses_format_provider<T>::value, provider_format_adapter<T> > llvm::detail::build_format_adapter (T && Item)
Definition at line 138 of file FormatVariadicDetails.h.
build_format_adapter() [4/4]
template<typename T > std::enable_if_t<uses_stream_operator<T>::value, stream_operator_format_adapter<T> > llvm::detail::build_format_adapter (T && Item)
Definition at line 145 of file FormatVariadicDetails.h.
canTypeFitValue()
template<typename T , typename U > bool llvm::detail::canTypeFitValue (const U Value)
Definition at line 113 of file Sequence.h.
References llvm::max(), and llvm::min().
combineHashValue()
static unsigned llvm::detail::combineHashValue (unsigned a, unsigned b) inline static
Simplistic combination of 32-bit hash values into 32-bit hash values.
Definition at line 30 of file DenseMapInfo.h.
References b, and uint64_t.
Referenced by llvm::ScalarEvolution::FoldID::computeHash(), llvm::DenseMapInfo< std::pair< const MCSymbol *, MCSymbolRefExpr::VariantKind > >::getHashValue(), llvm::DenseMapInfo< VersionTuple >::getHashValue(), llvm::DenseMapInfo< std::pair< T, U > >::getHashValue(), llvm::DenseMapInfo< std::variant< Ts... > >::getHashValue(), llvm::DenseMapInfo< AA::RangeTy >::getHashValue(), and llvm::DenseMapInfo< std::tuple< Ts... > >::getHashValueImpl().
deref_or_none()
template<typename Iter > auto llvm::detail::deref_or_none (const Iter & I, const Iter & End) -> std::optional< std::remove_const_t<std::remove_reference_t<decltype(*I)>>>
Definition at line 927 of file STLExtras.h.
emitOps() [1/2]
template<typename FieldTy > static void llvm::detail::emitOps (llvm::BitCodeAbbrev & abbrev) static
Attaches the last field to an abbreviation.
This is the base case for emitOps.
See also
BCRecordLayout::emitAbbrev
Definition at line 166 of file BitcodeConvenience.h.
Referenced by llvm::BCGenericRecordLayout< BCLiteral< RecordCode >, Fields... >::emitAbbrev(), and emitOps().
emitOps() [2/2]
template<typename FieldTy , typename Next , typename... Rest> static void llvm::detail::emitOps (llvm::BitCodeAbbrev & abbrev) static
Attaches fields to an abbreviation.
This is the recursive case for emitOps.
See also
BCRecordLayout::emitAbbrev
Definition at line 176 of file BitcodeConvenience.h.
References emitOps().
frexp() [1/2]
DoubleAPFloat llvm::detail::frexp (const DoubleAPFloat & Arg, int & Exp, APFloat::roundingMode RM)
Definition at line 5317 of file APFloat.cpp.
References Arg, assert(), llvm::APFloatBase::fcNormal, First, frexp(), move, llvm::AArch64::RM, scalbn(), and llvm::semPPCDoubleDouble.
frexp() [2/2]
IEEEFloat llvm::detail::frexp (const IEEEFloat & Val, int & Exp, IEEEFloat::roundingMode RM)
Definition at line 4734 of file APFloat.cpp.
References llvm::APFloatBase::IEK_Inf, llvm::APFloatBase::IEK_NaN, llvm::APFloatBase::IEK_Zero, ilogb(), llvm::Quiet, llvm::AArch64::RM, and scalbn().
Referenced by frexp().
get()
template<std::size_t i, typename R > decltype(auto) llvm::detail::get (const result_pair< R > & Pair)
Definition at line 2171 of file STLExtras.h.
References i.
getAnalysisResult()
template<typename PassT , typename IRUnitT , typename... AnalysisArgTs, typename... MainArgTs> PassT::Result llvm::detail::getAnalysisResult (AnalysisManager< IRUnitT, AnalysisArgTs... > & AM, IRUnitT & IR, std::tuple< MainArgTs... > Args)
Helper for partial unpacking of extra arguments in getAnalysisResult.
Arguments passed in tuple come from PassManager, so they might have extra arguments after those AnalysisManager's ExtraArgTs ones that we need to pass to getResult.
Definition at line 439 of file PassManager.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, getAnalysisResultUnpackTuple(), and IR.
getAnalysisResultUnpackTuple()
template<typename PassT , typename IRUnitT , typename AnalysisManagerT , typename... ArgTs, size_t... Ns> PassT::Result llvm::detail::getAnalysisResultUnpackTuple (AnalysisManagerT & AM, IRUnitT & IR, std::tuple< ArgTs... > Args, std::index_sequence< Ns... >)
Actual unpacker of extra arguments in getAnalysisResult, passes only those tuple arguments that are mentioned in index_sequence.
Definition at line 424 of file PassManager.h.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, and IR.
Referenced by getAnalysisResult().
hash_value() [1/2]
hash_code llvm::detail::hash_value (const DoubleAPFloat & Arg)
Definition at line 5171 of file APFloat.cpp.
References Arg, llvm::hash_combine(), and hash_value().
hash_value() [2/2]
hash_code llvm::detail::hash_value (const IEEEFloat & Arg)
Note that the use of hash codes for floating point values is in general frought with peril. Equality is hard to define for these values. For example, should negative and positive zero hash to different codes? Are they equal or not? This hash value implementation specifically emphasizes producing different codes for different inputs in order to be used in canonicalization and memoization. As such, equality is bitwiseIsEqual, and 0 != -0.
Definition at line 3358 of file APFloat.cpp.
References Arg, llvm::hash_combine(), and llvm::hash_combine_range().
Referenced by hash_value().
ilogb()
int llvm::detail::ilogb (const IEEEFloat & Arg)
Because the radix of APFloat is 2, this is equivalent to floor(log2(x)). For special APFloat values, this returns special error codes:
NaN -> IEK_NaN 0 -> IEK_Zero Inf -> IEK_Inf
Definition at line 4695 of file APFloat.cpp.
References Arg, llvm::APFloatBase::IEK_Inf, llvm::APFloatBase::IEK_NaN, llvm::APFloatBase::IEK_Zero, llvm::lfExactlyZero, and llvm::APFloatBase::rmNearestTiesToEven.
Referenced by llvm::InstCombinerImpl::foldFCmpIntToFPConst(), frexp(), and llvm::isKnownNeverInfinity().
isPresent()
template<typename T > bool llvm::detail::isPresent (const T & t) inline
Definition at line 630 of file Casting.h.
References T.
Referenced by llvm::cast_if_present(), llvm::dyn_cast(), llvm::dyn_cast_if_present(), and llvm::isa_and_present().
next_or_end()
template<typename Iter > Iter llvm::detail::next_or_end (const Iter & I, const Iter & End)
Definition at line 920 of file STLExtras.h.
operator!=()
template<typename ValueT , typename MapTy , typename ValueInfoT > bool llvm::detail::operator!= (const DenseSetImpl< ValueT, MapTy, ValueInfoT > & LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > & RHS)
Inequality comparison for DenseSet.
Equivalent to !(LHS == RHS). See operator== for performance notes.
Definition at line 259 of file DenseSet.h.
References LHS, and RHS.
operator==()
template<typename ValueT , typename MapTy , typename ValueInfoT > bool llvm::detail::operator== (const DenseSetImpl< ValueT, MapTy, ValueInfoT > & LHS, const DenseSetImpl< ValueT, MapTy, ValueInfoT > & RHS)
Equality comparison for DenseSet.
Iterates over elements of LHS confirming that each element is also a member of RHS, and that RHS contains no additional values. Equivalent to N calls to RHS.count. Amortized complexity is linear, worst case is O(N^2) (if every hash collides).
Definition at line 243 of file DenseSet.h.
References E, LHS, and RHS.
printBumpPtrAllocatorStats()
void llvm::detail::printBumpPtrAllocatorStats (unsigned NumSlabs, size_t BytesAllocated, size_t TotalMemory)
Definition at line 20 of file Allocator.cpp.
References llvm::errs().
Referenced by llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::PrintStats().
PrintTo() [1/2]
void llvm::detail::PrintTo (const ErrorHolder & Err, std::ostream * Out) inline
Definition at line 38 of file SupportHelpers.h.
Referenced by PrintTo().
PrintTo() [2/2]
template<typename T > void llvm::detail::PrintTo (const ExpectedHolder< T > & Item, std::ostream * Out)
Definition at line 53 of file SupportHelpers.h.
References llvm::detail::ExpectedHolder< T >::Exp, PrintTo(), and llvm::detail::ErrorHolder::Success().
reverse_if()
template<bool B, typename Range > auto llvm::detail::reverse_if (Range && R)
Definition at line 46 of file CFGDiff.h.
References reverse_if_helper().
reverse_if_helper() [1/2]
template<typename Range > auto llvm::detail::reverse_if_helper (Range && R, std::integral_constant< bool, false >)
Definition at line 37 of file CFGDiff.h.
Referenced by reverse_if().
reverse_if_helper() [2/2]
template<typename Range > auto llvm::detail::reverse_if_helper (Range && R, std::integral_constant< bool, true >)
Definition at line 42 of file CFGDiff.h.
References llvm::reverse().
scalbn() [1/2]
DoubleAPFloat llvm::detail::scalbn (const DoubleAPFloat & Arg, int Exp, APFloat::roundingMode RM)
Definition at line 5310 of file APFloat.cpp.
References Arg, assert(), llvm::AArch64::RM, scalbn(), and llvm::semPPCDoubleDouble.
scalbn() [2/2]
IEEEFloat llvm::detail::scalbn (IEEEFloat X, int Exp, IEEEFloat::roundingMode RoundingMode)
Definition at line 4713 of file APFloat.cpp.
References llvm::lfExactlyZero, and X.
Referenced by frexp(), and scalbn().
TakeError()
llvm::detail::ErrorHolder llvm::detail::TakeError (llvm::Error Err)
Definition at line 15 of file Error.cpp.
Referenced by TakeExpected().
TakeExpected() [1/2]
template<typename T > ExpectedHolder<T> llvm::detail::TakeExpected (Expected< T > && Exp)
Definition at line 26 of file Error.h.
References TakeExpected().
TakeExpected() [2/2]
template<typename T > ExpectedHolder<T> llvm::detail::TakeExpected (Expected< T > & Exp)
Definition at line 22 of file Error.h.
References TakeError().
Referenced by TakeExpected().
tcSetLeastSignificantBits()
static void llvm::detail::tcSetLeastSignificantBits (APInt::WordType * dst, unsigned parts, unsigned bits) static
Definition at line 1454 of file APFloat.cpp.
References llvm::APInt::APINT_BITS_PER_WORD, bits, and i.
Referenced by llvm::detail::IEEEFloat::convertToInteger().
unwrapValue()
template<typename T > decltype(auto) llvm::detail::unwrapValue (T & t) inline
Definition at line 636 of file Casting.h.
References llvm::ValueIsPresent< T, Enable >::unwrapValue().
Referenced by llvm::cast_if_present(), and llvm::dyn_cast_if_present().