LLVM: llvm::orc::shared::detail Namespace Reference
llvm::orc::shared::detail Namespace Reference
Classes
class AsyncCallResultHelper
class ResultDeserializer
class ResultDeserializer< SPSError, Error >
class ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >
class ResultSerializer
class ResultSerializer< SPSRetTagT, Error >
class ResultSerializer< SPSRetTagT, ErrorSuccess >
class ResultSerializer< SPSRetTagT, Expected< T > >
struct SPSSerializableError
Helper type for serializing Errors.
struct SPSSerializableExpected
Helper type for serializing Expected<T>s.
class WrapperFunctionAsyncHandlerHelper
class WrapperFunctionAsyncHandlerHelper< RetT(*)(ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionAsyncHandlerHelper< RetT(ClassT::*)(ArgTs...) const, ResultSerializer, SPSTagTs... >
class WrapperFunctionAsyncHandlerHelper< RetT(ClassT::*)(ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionAsyncHandlerHelper< RetT(SendResultT, ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionHandlerCaller
class WrapperFunctionHandlerCaller< void >
class WrapperFunctionHandlerHelper
class WrapperFunctionHandlerHelper< RetT(*)(ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionHandlerHelper< RetT(ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionHandlerHelper< RetT(ClassT::*)(ArgTs...) const, ResultSerializer, SPSTagTs... >
class WrapperFunctionHandlerHelper< RetT(ClassT::*)(ArgTs...), ResultSerializer, SPSTagTs... >
Functions
SPSSerializableError toSPSSerializable (Error Err)
Error fromSPSSerializable (SPSSerializableError BSE)
template<typename T >
SPSSerializableExpected< T > toSPSSerializable (Expected< T > E)
template<typename T >
Expected< T > fromSPSSerializable (SPSSerializableExpected< T > BSE)
template<typename SPSArgListT , typename... ArgTs>
WrapperFunctionResult serializeViaSPSToWrapperFunctionResult (const ArgTs &...Args)
Function Documentation
fromSPSSerializable() [1/2]
Error llvm::orc::shared::detail::fromSPSSerializable (SPSSerializableError BSE) inline
Definition at line 624 of file SimplePackedSerialization.h.
References llvm::orc::shared::detail::SPSSerializableError::ErrMsg, llvm::orc::shared::detail::SPSSerializableError::HasError, llvm::inconvertibleErrorCode(), and llvm::Error::success().
Referenced by llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::deserialize().
fromSPSSerializable() [2/2]
template<typename T > Expected<T> llvm::orc::shared::detail::fromSPSSerializable (SPSSerializableExpected< T > BSE)
Definition at line 639 of file SimplePackedSerialization.h.
References llvm::orc::shared::detail::SPSSerializableExpected< T >::ErrMsg, llvm::orc::shared::detail::SPSSerializableExpected< T >::HasValue, llvm::inconvertibleErrorCode(), move, and llvm::orc::shared::detail::SPSSerializableExpected< T >::Value.
serializeViaSPSToWrapperFunctionResult()
template<typename SPSArgListT , typename... ArgTs> WrapperFunctionResult llvm::orc::shared::detail::serializeViaSPSToWrapperFunctionResult (const ArgTs &... Args)
Definition at line 173 of file WrapperFunctionUtils.h.
References llvm::orc::shared::WrapperFunctionResult::allocate(), llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::orc::shared::WrapperFunctionResult::createOutOfBandError(), llvm::X86II::OB, and size.
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call(), and llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::callAsync().
toSPSSerializable() [1/2]
SPSSerializableError llvm::orc::shared::detail::toSPSSerializable (Error Err) inline
Definition at line 618 of file SimplePackedSerialization.h.
Referenced by llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > >::serialize().
toSPSSerializable() [2/2]
template<typename T > SPSSerializableExpected<T> llvm::orc::shared::detail::toSPSSerializable (Expected< T > E)
Definition at line 631 of file SimplePackedSerialization.h.
References E, move, T, and llvm::toString().