LLVM: llvm::objcopy::xcoff Namespace Reference
llvm::objcopy::xcoff Namespace Reference
Classes
struct Object
struct Section
struct Symbol
class XCOFFReader
class XCOFFWriter
Functions
Error executeObjcopyOnBinary (const CommonConfig &Config, const XCOFFConfig &, object::XCOFFObjectFile &In, raw_ostream &Out)
Apply the transformations described by Config and XCOFFConfig to In and writes the result into Out.
static Error handleArgs (const CommonConfig &Config, Object &Obj)
Function Documentation
executeObjcopyOnBinary()
Error llvm::objcopy::xcoff::executeObjcopyOnBinary (const CommonConfig & Config, const XCOFFConfig & , object::XCOFFObjectFile & In, raw_ostream & Out)
Apply the transformations described by Config and XCOFFConfig to In and writes the result into Out.
Returns
any Error encountered whilst performing the operation.
Definition at line 27 of file XCOFFObjcopy.cpp.
References assert(), llvm::objcopy::xcoff::XCOFFReader::create(), llvm::createFileError(), E, llvm::Expected< T >::get(), handleArgs(), llvm::tgtok::In, llvm::objcopy::CommonConfig::InputFilename, move, llvm::objcopy::CommonConfig::OutputFilename, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::objcopy::xcoff::XCOFFWriter::write().
Referenced by llvm::objcopy::executeObjcopyOnBinary().
handleArgs()
static Error llvm::objcopy::xcoff::handleArgs (const CommonConfig & Config, Object & Obj) static
Definition at line 23 of file XCOFFObjcopy.cpp.
References llvm::Error::success().
Referenced by executeObjcopyOnBinary().