LLVM: llvm::coro Namespace Reference
llvm::coro Namespace Reference
Classes
struct LowererBase
struct Shape
Enumerations
enum ABI { ABI::Switch, ABI::Retcon, ABI::RetconOnce, ABI::Async }
Functions
bool declaresAnyIntrinsic (const Module &M)
bool declaresIntrinsics (const Module &M, const std::initializer_list< StringRef >)
void replaceCoroFree (CoroIdInst *CoroId, bool Elide)
void salvageDebugInfo (SmallDenseMap< llvm::Value *, llvm::AllocaInst *, 4 > &DbgPtrAllocaCache, DbgVariableIntrinsic *DVI, bool OptimizeFrame)
Recover a dbg.declare prepared by the frontend and emit an alloca holding a pointer to the coroutine frame.
bool defaultMaterializable (Instruction &V)
Default materializable callback.
void buildCoroutineFrame (Function &F, Shape &Shape, const std::function< bool(Instruction &)> &MaterializableCallback)
CallInst * createMustTailCall (DebugLoc Loc, Function *MustTailCallFn, ArrayRef< Value * > Arguments, IRBuilder<> &)
Enumeration Type Documentation
ABI
enum llvm::coro::ABI strong
Enumerator
Switch
The "resume-switch" lowering, where there are separate resume and destroy functions that are shared between all suspend points.
The coroutine frame implicitly stores the resume and destroy functions, the current index, and any promise value.
Retcon
The "returned-continuation" lowering, where each suspend point creates a single continuation function that is used for both resuming and destroying.
Does not support promises.
RetconOnce
The "unique returned-continuation" lowering, where each suspend point creates a single continuation function that is used for both resuming and destroying.
Does not support promises. The function is known to suspend at most once during its execution, and the return value of the continuation is void.
Async
The "async continuation" lowering, where each suspend point creates a single continuation function.
The continuation function is available as an intrinsic.
Definition at line 46 of file CoroInternal.h.
Function Documentation
buildCoroutineFrame()
void llvm::coro::buildCoroutineFrame (Function & F, Shape & Shape, const std::function< bool(Instruction &)> & MaterializableCallback)
Definition at line 2957 of file CoroFrame.cpp.
References A, llvm::coro::Shape::ABI, llvm::AMDGPU::HSAMD::Kernel::Key::Args, Arguments, Builder, llvm::MCID::Call, cleanupSinglePredPHIs(), llvm::CoroIdInst::clearPromise(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroEnds, llvm::coro::Shape::CoroSuspends, createMustTailCall(), doRematerializations(), llvm::ArrayRef< T >::drop_front(), eliminateSwiftError(), F, llvm::coro::Shape::getSwitchCoroId(), I, instructions, isCoroutineStructureIntrinsic(), isLocalAlloca(), llvm::coro::Shape::SwitchLoweringStorage::PromiseAlloca, rewritePHIs(), sinkLifetimeStartMarkers(), splitAround(), and llvm::coro::Shape::SwitchLowering.
Referenced by splitCoroutine().
createMustTailCall()
CallInst * llvm::coro::createMustTailCall (DebugLoc Loc, Function * MustTailCallFn, ArrayRef< Value * > Arguments, IRBuilder<> & Builder)
Definition at line 1675 of file CoroSplit.cpp.
References Arguments, Builder, coerceArguments(), llvm::Function::getCallingConv(), llvm::Function::getFunctionType(), llvm::MipsISD::TailCall, and llvm::CallInst::TCK_MustTail.
Referenced by buildCoroutineFrame().
declaresAnyIntrinsic()
bool llvm::coro::declaresAnyIntrinsic (const Module & M)
Definition at line 105 of file Coroutines.cpp.
References assert(), CoroIntrinsics, isCoroutineIntrinsicName(), and M.
Referenced by llvm::CoroConditionalWrapper::run().
declaresIntrinsics()
bool llvm::coro::declaresIntrinsics (const Module & M, const std::initializer_list< StringRef > List)
Definition at line 117 of file Coroutines.cpp.
References assert(), isCoroutineIntrinsicName(), List, and M.
Referenced by declaresCoroCleanupIntrinsics(), declaresCoroEarlyIntrinsics(), and declaresCoroElideIntrinsics().
defaultMaterializable()
bool llvm::coro::defaultMaterializable (Instruction & V)
Default materializable callback.
Definition at line 2218 of file CoroFrame.cpp.
replaceCoroFree()
void llvm::coro::replaceCoroFree (CoroIdInst * CoroId, bool Elide)
Definition at line 130 of file Coroutines.cpp.
References llvm::ConstantPointerNull::get(), llvm::Value::getContext(), llvm::Type::getInt8PtrTy(), and llvm::Value::users().
Referenced by handleNoSuspendCoroutine().
salvageDebugInfo()
void llvm::coro::salvageDebugInfo (SmallDenseMap< llvm::Value *, llvm::AllocaInst *, 4 > & DbgPtrAllocaCache, DbgVariableIntrinsic * DVI, bool OptimizeFrame)
Recover a dbg.declare prepared by the frontend and emit an alloca holding a pointer to the coroutine frame.
Definition at line 2805 of file CoroFrame.cpp.
References Arg, Builder, F, llvm::DbgVariableIntrinsic::getExpression(), llvm::Instruction::getFunction(), llvm::DIExpression::getNumLocationOperands(), llvm::Value::getType(), llvm::DbgVariableIntrinsic::getVariableLocationOp(), I, llvm::Instruction::moveBefore(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::salvageDebugInfoImpl(), and llvm::DbgVariableIntrinsic::setExpression().
Referenced by splitCoroutine().