LLVM: llvm::dxbc Namespace Reference
llvm::dxbc Namespace Reference
Namespaces
PSV
Classes
struct AmplificationPSVInfo
struct BitcodeHeader
struct ContainerVersion
struct DomainPSVInfo
struct GeometryPSVInfo
struct Hash
struct Header
struct HullPSVInfo
struct MeshPSVInfo
struct PartHeader
Use this type to describe the size and type of a DXIL container part.
union PipelinePSVInfo
struct PixelPSVInfo
struct ProgramHeader
struct ShaderHash
struct VertexPSVInfo
Enumerations
enum HashFlags : uint32_t { HashFlags::None = 0, HashFlags::IncludesSource = 1 }
enum PartType { PartType::Unknown = 0 }
enum FeatureFlags : uint64_t
Functions
Triple::EnvironmentType getShaderStage (uint32_t Kind)
PartType parsePartType (StringRef S)
Enumeration Type Documentation
FeatureFlags
enum llvm::dxbc::FeatureFlags : uint64_t strong
Definition at line 144 of file DXContainer.h.
HashFlags
enum llvm::dxbc::HashFlags : uint32_t strong
Enumerator
None
IncludesSource
Definition at line 50 of file DXContainer.h.
PartType
enum llvm::dxbc::PartType strong
Enumerator
Unknown
Definition at line 138 of file DXContainer.h.
Function Documentation
getShaderStage()
Triple::EnvironmentType llvm::dxbc::getShaderStage (uint32_t Kind) inline
Definition at line 40 of file DXContainer.h.
References llvm::Triple::Amplification, assert(), and llvm::Triple::Pixel.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), and llvm::object::DirectX::PSVRuntimeInfo::parse().
parsePartType()
dxbc::PartType llvm::dxbc::parsePartType (StringRef S)
Definition at line 20 of file DXContainer.cpp.
References llvm::StringSwitch< T, R >::Default(), S, and Unknown.