LLVM: llvm::dxil::PointerTypeAnalysis Namespace Reference
llvm::dxil::PointerTypeAnalysis Namespace Reference
An analysis to compute the PointerTypes for pointers in a Module.
Functions
PointerTypeMap run (const Module &M)
Compute the PointerTypeMap for the module M.
Detailed Description
An analysis to compute the PointerTypes for pointers in a Module.
Since this analysis is only run during codegen and the new pass manager doesn't support codegen passes, this is wrtten as a function in a namespace. It is very simple to transform it into a proper analysis pass. This code relies on typed pointers existing as LLVM types, but could be migrated to a custom Type if PointerType loses typed support.
Function Documentation
run()
PointerTypeMap llvm::dxil::PointerTypeAnalysis::run (const Module & M)
Compute the PointerTypeMap for the module M.
Definition at line 189 of file PointerTypeAnalysis.cpp.
References B, classifyGlobalCtorPointerType(), F, G, I, and M.
Referenced by llvm::jitlink::createLookupContinuation(), and llvm::WholeProgramDevirtPass::run().