LLVM: llvm::WebAssembly Namespace Reference
llvm::WebAssembly Namespace Reference
Classes
class ConcreteSortRegion
class SortRegion
class SortRegionInfo
Enumerations
enum Tag { CPP_EXCEPTION = 0, C_LONGJMP = 1 }
enum Fixups {
fixup_sleb128_i32 = FirstTargetFixupKind, fixup_sleb128_i64, fixup_uleb128_i32, fixup_uleb128_i64,
LastTargetFixupKind, NumTargetFixupKinds = LastTargetFixupKind - FirstTargetFixupKind
}
enum OperandType {
OPERAND_BASIC_BLOCK = MCOI::OPERAND_FIRST_TARGET, OPERAND_LOCAL, OPERAND_GLOBAL, OPERAND_I32IMM,
OPERAND_I64IMM, OPERAND_F32IMM, OPERAND_F64IMM, OPERAND_VEC_I8IMM,
OPERAND_VEC_I16IMM, OPERAND_VEC_I32IMM, OPERAND_VEC_I64IMM, OPERAND_FUNCTION32,
OPERAND_OFFSET32, OPERAND_OFFSET64, OPERAND_P2ALIGN, OPERAND_SIGNATURE,
OPERAND_TYPEINDEX, OPERAND_TAG, OPERAND_BRLIST, OPERAND_TABLE
}
enum BlockType : unsigned {
BlockType::Invalid = 0x00, BlockType::Void = 0x40, BlockType::I32 = unsigned(wasm::ValType::I32), BlockType::I64 = unsigned(wasm::ValType::I64),
BlockType::F32 = unsigned(wasm::ValType::F32), BlockType::F64 = unsigned(wasm::ValType::F64), BlockType::V128 = unsigned(wasm::ValType::V128), BlockType::Externref = unsigned(wasm::ValType::EXTERNREF),
BlockType::Funcref = unsigned(wasm::ValType::FUNCREF), BlockType::Multivalue = 0xffff
}
Used as immediate MachineOperands for block signatures.
enum WasmAddressSpace : unsigned { WASM_ADDRESS_SPACE_DEFAULT = 0, WASM_ADDRESS_SPACE_VAR = 1, WASM_ADDRESS_SPACE_EXTERNREF = 10, WASM_ADDRESS_SPACE_FUNCREF = 20 }
enum TargetIndex {
TI_LOCAL, TI_GLOBAL_FIXED, TI_OPERAND_STACK, TI_GLOBAL_RELOC,
TI_LOCAL_INDIRECT
}
Functions
unsigned GetDefaultP2AlignAny (unsigned Opc)
Return the default p2align value for a load or store with the given opcode.
unsigned GetDefaultP2Align (unsigned Opc)
bool isArgument (unsigned Opc)
bool isCopy (unsigned Opc)
bool isTee (unsigned Opc)
bool isCallDirect (unsigned Opc)
bool isCallIndirect (unsigned Opc)
bool isBrTable (const MachineInstr &MI)
bool isMarker (unsigned Opc)
bool isCatch (unsigned Opc)
bool isLocalGet (unsigned Opc)
bool isLocalSet (unsigned Opc)
bool isLocalTee (unsigned Opc)
int getStackOpcode (unsigned short Opcode)
int getRegisterOpcode (unsigned short Opcode)
int getWasm64Opcode (unsigned short Opcode)
bool isDefaultAddressSpace (unsigned AS)
bool isWasmVarAddressSpace (unsigned AS)
bool isValidAddressSpace (unsigned AS)
bool isFuncrefType (const Type *Ty)
bool isExternrefType (const Type *Ty)
bool isRefType (const Type *Ty)
bool isRefType (wasm::ValType Type)
std::optional< wasm::ValType > parseType (StringRef Type)
BlockType parseBlockType (StringRef Type)
MVT parseMVT (StringRef Type)
const char * anyTypeToString (unsigned Type)
const char * typeToString (wasm::ValType Type)
std::string typeListToString (ArrayRef< wasm::ValType > List)
std::string signatureToString (const wasm::WasmSignature *Sig)
wasm::ValType toValType (MVT Type)
wasm::ValType regClassToValType (unsigned RC)
wasm::ValType regClassToValType (const TargetRegisterClass *RC)
void wasmSymbolSetType (MCSymbolWasm *Sym, const Type *GlobalVT, const SmallVector< MVT, 1 > &VTs)
Sets a Wasm Symbol Type.
bool isChild (const MachineInstr &MI, const WebAssemblyFunctionInfo &MFI)
Test whether MI is a child of some other node in an expression tree.
bool mayThrow (const MachineInstr &MI)
const MachineOperand & getCalleeOp (const MachineInstr &MI)
Returns the operand number of a callee, assuming the argument is a call instruction.
MCSymbolWasm * getOrCreateFunctionTableSymbol (MCContext &Ctx, const WebAssemblySubtarget *Subtarget)
Returns the __indirect_function_table, for use in call_indirect and in function bitcasts.
MCSymbolWasm * getOrCreateFuncrefCallTableSymbol (MCContext &Ctx, const WebAssemblySubtarget *Subtarget)
Returns the __funcref_call_table, for use in funcref calls when lowered to table.set + call_indirect.
MachineInstr * findCatch (MachineBasicBlock *EHPad)
Find a catch instruction from an EH pad.
unsigned getCopyOpcodeForRegClass (const TargetRegisterClass *RC)
Returns the appropriate copy opcode for the given register class.
int16_t getNamedOperandIdx (uint16_t Opcode, uint16_t NamedIndex)
FastISel * createFastISel (FunctionLoweringInfo &funcInfo, const TargetLibraryInfo *libInfo)
Variables
static const unsigned Nop = 0x01
Instruction opcodes emitted via means other than CodeGen.
static const unsigned End = 0x0b
cl::opt< bool > WasmEnableEmEH
cl::opt< bool > WasmEnableEmSjLj
cl::opt< bool > WasmEnableEH
cl::opt< bool > WasmEnableSjLj
const char *const ClangCallTerminateFn
const char *const CxaBeginCatchFn = "__cxa_begin_catch"
const char *const CxaRethrowFn = "__cxa_rethrow"
const char *const StdTerminateFn = "_ZSt9terminatev"
const char *const PersonalityWrapperFn
Enumeration Type Documentation
BlockType
enum llvm::WebAssembly::BlockType : unsigned strong
Used as immediate MachineOperands for block signatures.
Enumerator
Invalid
Void
I32
I64
F32
F64
V128
Externref
Funcref
Multivalue
Definition at line 30 of file WebAssemblyTypeUtilities.h.
Fixups
enum llvm::WebAssembly::Fixups
Enumerator
fixup_sleb128_i32
fixup_sleb128_i64
fixup_uleb128_i32
fixup_uleb128_i64
LastTargetFixupKind
NumTargetFixupKinds
Definition at line 16 of file WebAssemblyFixupKinds.h.
OperandType
enum llvm::WebAssembly::OperandType
Enumerator
OPERAND_BASIC_BLOCK
Basic block label in a branch construct.
OPERAND_LOCAL
Local index.
OPERAND_GLOBAL
Global index.
OPERAND_I32IMM
32-bit integer immediates.
OPERAND_I64IMM
64-bit integer immediates.
OPERAND_F32IMM
32-bit floating-point immediates.
OPERAND_F64IMM
64-bit floating-point immediates.
OPERAND_VEC_I8IMM
8-bit vector lane immediate
OPERAND_VEC_I16IMM
16-bit vector lane immediate
OPERAND_VEC_I32IMM
32-bit vector lane immediate
OPERAND_VEC_I64IMM
64-bit vector lane immediate
OPERAND_FUNCTION32
32-bit unsigned function indices.
OPERAND_OFFSET32
32-bit unsigned memory offsets.
OPERAND_OFFSET64
64-bit unsigned memory offsets.
OPERAND_P2ALIGN
p2align immediate for load and store address alignment.
OPERAND_SIGNATURE
signature immediate for block/loop.
OPERAND_TYPEINDEX
type signature immediate for call_indirect.
OPERAND_TAG
Tag index.
OPERAND_BRLIST
A list of branch targets for br_list.
OPERAND_TABLE
32-bit unsigned table number.
Definition at line 39 of file WebAssemblyMCTargetDesc.h.
Tag
enum llvm::WebAssembly::Tag
Enumerator
CPP_EXCEPTION
C_LONGJMP
Definition at line 27 of file WasmEHFuncInfo.h.
TargetIndex
enum llvm::WebAssembly::TargetIndex
Enumerator
TI_LOCAL
TI_GLOBAL_FIXED
TI_OPERAND_STACK
TI_GLOBAL_RELOC
TI_LOCAL_INDIRECT
Definition at line 88 of file WebAssembly.h.
WasmAddressSpace
enum llvm::WebAssembly::WasmAddressSpace : unsigned
Enumerator
WASM_ADDRESS_SPACE_DEFAULT
WASM_ADDRESS_SPACE_VAR
WASM_ADDRESS_SPACE_EXTERNREF
WASM_ADDRESS_SPACE_FUNCREF
Definition at line 48 of file WebAssemblyTypeUtilities.h.
Function Documentation
anyTypeToString()
const char * llvm::WebAssembly::anyTypeToString (unsigned Type)
Definition at line 77 of file WebAssemblyTypeUtilities.cpp.
References llvm::wasm::WASM_TYPE_EXTERNREF, llvm::wasm::WASM_TYPE_F32, llvm::wasm::WASM_TYPE_F64, llvm::wasm::WASM_TYPE_FUNC, llvm::wasm::WASM_TYPE_FUNCREF, llvm::wasm::WASM_TYPE_I32, llvm::wasm::WASM_TYPE_I64, llvm::wasm::WASM_TYPE_NORESULT, and llvm::wasm::WASM_TYPE_V128.
Referenced by llvm::WebAssemblyInstPrinter::printWebAssemblySignatureOperand(), and typeToString().
createFastISel()
FastISel * llvm::WebAssembly::createFastISel (FunctionLoweringInfo & funcInfo, const TargetLibraryInfo * libInfo)
Definition at line 1432 of file WebAssemblyFastISel.cpp.
findCatch()
MachineInstr * llvm::WebAssembly::findCatch (MachineBasicBlock * EHPad)
Find a catch instruction from an EH pad.
Returns null if no catch instruction found or the catch is in an invalid location.
Definition at line 170 of file WebAssemblyUtilities.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), isCatch(), llvm::MachineBasicBlock::isEHPad(), and isMarker().
getCalleeOp()
const MachineOperand & llvm::WebAssembly::getCalleeOp (const MachineInstr & MI)
Returns the operand number of a callee, assuming the argument is a call instruction.
Definition at line 108 of file WebAssemblyUtilities.cpp.
References llvm::AArch64ISD::CALL, llvm_unreachable, and MI.
Referenced by llvm::WebAssemblyInstrInfo::getCalleeOperand(), mayThrow(), and queryCallee().
getCopyOpcodeForRegClass()
unsigned llvm::WebAssembly::getCopyOpcodeForRegClass (const TargetRegisterClass * RC)
Returns the appropriate copy opcode for the given register class.
Definition at line 183 of file WebAssemblyUtilities.cpp.
References assert(), llvm::TargetRegisterClass::getID(), and llvm_unreachable.
Referenced by llvm::WebAssemblyInstrInfo::copyPhysReg(), and unstackifyVRegsUsedInSplitBB().
GetDefaultP2Align()
unsigned llvm::WebAssembly::GetDefaultP2Align (unsigned Opc) inline
Definition at line 267 of file WebAssemblyMCTargetDesc.h.
References Align, GetDefaultP2AlignAny(), and llvm_unreachable.
Referenced by llvm::WebAssemblyInstPrinter::printWebAssemblyP2AlignOperand(), and rewriteP2Align().
GetDefaultP2AlignAny()
unsigned llvm::WebAssembly::GetDefaultP2AlignAny (unsigned Opc) inline
Return the default p2align value for a load or store with the given opcode.
Definition at line 138 of file WebAssemblyMCTargetDesc.h.
References WASM_LOAD_STORE.
Referenced by GetDefaultP2Align().
getNamedOperandIdx()
int16_t llvm::WebAssembly::getNamedOperandIdx (uint16_t Opcode, uint16_t NamedIndex)
Referenced by llvm::WebAssemblyRegisterInfo::eliminateFrameIndex().
getOrCreateFuncrefCallTableSymbol()
MCSymbolWasm * llvm::WebAssembly::getOrCreateFuncrefCallTableSymbol (MCContext & Ctx, const WebAssemblySubtarget * Subtarget)
Returns the __funcref_call_table, for use in funcref calls when lowered to table.set + call_indirect.
Definition at line 144 of file WebAssemblyUtilities.cpp.
References llvm::MCContext::getOrCreateSymbol(), llvm::WebAssemblySubtarget::hasReferenceTypes(), llvm::MCSymbolWasm::isFunctionTable(), llvm::MCContext::lookupSymbol(), llvm::MCContext::reportError(), llvm::MCSymbolWasm::setOmitFromLinkingSection(), llvm::MCSymbolWasm::setTableType(), llvm::MCSymbolWasm::setType(), llvm::MCSymbolWasm::setWeak(), llvm::wasm::WASM_SYMBOL_TYPE_TABLE, and llvm::wasm::WASM_TYPE_FUNCREF.
Referenced by LowerCallResults().
getOrCreateFunctionTableSymbol()
MCSymbolWasm * llvm::WebAssembly::getOrCreateFunctionTableSymbol (MCContext & Ctx, const WebAssemblySubtarget * Subtarget)
Returns the __indirect_function_table, for use in call_indirect and in function bitcasts.
Definition at line 125 of file WebAssemblyUtilities.cpp.
References llvm::MCContext::getOrCreateSymbol(), llvm::WebAssemblySubtarget::hasReferenceTypes(), llvm::MCSymbolWasm::isFunctionTable(), llvm::MCContext::lookupSymbol(), llvm::MCContext::reportError(), llvm::MCSymbolWasm::setFunctionTable(), llvm::MCSymbolWasm::setOmitFromLinkingSection(), and llvm::MCSymbol::setUndefined().
Referenced by llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), and LowerCallResults().
getRegisterOpcode()
int llvm::WebAssembly::getRegisterOpcode (unsigned short Opcode)
Referenced by llvm::WebAssemblyAsmTypeCheck::typeCheck().
getStackOpcode()
int llvm::WebAssembly::getStackOpcode (unsigned short Opcode)
Referenced by removeRegisterOperands().
getWasm64Opcode()
int llvm::WebAssembly::getWasm64Opcode (unsigned short Opcode)
isArgument()
bool llvm::WebAssembly::isArgument (unsigned Opc) inline
Definition at line 275 of file WebAssemblyMCTargetDesc.h.
Referenced by llvm::WebAssemblyFrameLowering::emitPrologue(), and hasArgumentDef().
isBrTable()
bool llvm::WebAssembly::isBrTable (const MachineInstr & MI) inline
Definition at line 375 of file WebAssemblyMCTargetDesc.h.
References MI.
isCallDirect()
bool llvm::WebAssembly::isCallDirect (unsigned Opc) inline
Definition at line 351 of file WebAssemblyMCTargetDesc.h.
References llvm::AArch64ISD::CALL.
isCallIndirect()
bool llvm::WebAssembly::isCallIndirect (unsigned Opc) inline
Definition at line 363 of file WebAssemblyMCTargetDesc.h.
Referenced by llvm::WebAssemblyMCInstLower::lower(), and mayThrow().
isCatch()
bool llvm::WebAssembly::isCatch (unsigned Opc) inline
Definition at line 407 of file WebAssemblyMCTargetDesc.h.
Referenced by findCatch(), and isSafeToMove().
isChild()
bool llvm::WebAssembly::isChild (const MachineInstr & MI, const WebAssemblyFunctionInfo & MFI)
Test whether MI is a child of some other node in an expression tree.
Definition at line 53 of file WebAssemblyUtilities.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), llvm::WebAssemblyFunctionInfo::isVRegStackified(), and MI.
isCopy()
bool llvm::WebAssembly::isCopy (unsigned Opc) inline
Definition at line 307 of file WebAssemblyMCTargetDesc.h.
isDefaultAddressSpace()
bool llvm::WebAssembly::isDefaultAddressSpace (unsigned AS) inline
Definition at line 62 of file WebAssemblyTypeUtilities.h.
References WASM_ADDRESS_SPACE_DEFAULT.
Referenced by isValidAddressSpace().
isExternrefType()
bool llvm::WebAssembly::isExternrefType (const Type * Ty) inline
Definition at line 76 of file WebAssemblyTypeUtilities.h.
References llvm::Type::getPointerAddressSpace(), and WASM_ADDRESS_SPACE_EXTERNREF.
Referenced by isRefType(), and wasmSymbolSetType().
isFuncrefType()
bool llvm::WebAssembly::isFuncrefType (const Type * Ty) inline
Definition at line 71 of file WebAssemblyTypeUtilities.h.
References llvm::Type::getPointerAddressSpace(), and WASM_ADDRESS_SPACE_FUNCREF.
Referenced by isRefType(), and wasmSymbolSetType().
isLocalGet()
bool llvm::WebAssembly::isLocalGet (unsigned Opc) inline
Definition at line 419 of file WebAssemblyMCTargetDesc.h.
isLocalSet()
bool llvm::WebAssembly::isLocalSet (unsigned Opc) inline
Definition at line 441 of file WebAssemblyMCTargetDesc.h.
Referenced by llvm::WebAssemblyInstrInfo::isExplicitTargetIndexDef().
isLocalTee()
bool llvm::WebAssembly::isLocalTee (unsigned Opc) inline
Definition at line 463 of file WebAssemblyMCTargetDesc.h.
Referenced by llvm::WebAssemblyInstrInfo::isExplicitTargetIndexDef().
isMarker()
bool llvm::WebAssembly::isMarker (unsigned Opc) inline
Definition at line 387 of file WebAssemblyMCTargetDesc.h.
References llvm::bitc::END_BLOCK, and llvm::AMDGPUISD::LOOP.
Referenced by findCatch().
isRefType() [1/2]
bool llvm::WebAssembly::isRefType (const Type * Ty) inline
Definition at line 81 of file WebAssemblyTypeUtilities.h.
References isExternrefType(), and isFuncrefType().
Referenced by wasmSymbolSetType().
isRefType() [2/2]
bool llvm::WebAssembly::isRefType (wasm::ValType Type) inline
Definition at line 85 of file WebAssemblyTypeUtilities.h.
References llvm::wasm::EXTERNREF, and llvm::wasm::FUNCREF.
isTee()
bool llvm::WebAssembly::isTee (unsigned Opc) inline
Definition at line 329 of file WebAssemblyMCTargetDesc.h.
Referenced by unstackifyVRegsUsedInSplitBB().
isValidAddressSpace()
bool llvm::WebAssembly::isValidAddressSpace (unsigned AS) inline
Definition at line 68 of file WebAssemblyTypeUtilities.h.
References isDefaultAddressSpace(), and isWasmVarAddressSpace().
isWasmVarAddressSpace()
bool llvm::WebAssembly::isWasmVarAddressSpace (unsigned AS) inline
Definition at line 65 of file WebAssemblyTypeUtilities.h.
References WASM_ADDRESS_SPACE_VAR.
Referenced by llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::WebAssemblyFrameLowering::getLocalForStackObject(), isValidAddressSpace(), and IsWebAssemblyGlobal().
mayThrow()
bool llvm::WebAssembly::mayThrow (const MachineInstr & MI)
Definition at line 64 of file WebAssemblyUtilities.cpp.
References assert(), CxaBeginCatchFn, F, getCalleeOp(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getSymbolName(), isCallIndirect(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isSymbol(), MI, PersonalityWrapperFn, and StdTerminateFn.
parseBlockType()
WebAssembly::BlockType llvm::WebAssembly::parseBlockType (StringRef Type)
Definition at line 45 of file WebAssemblyTypeUtilities.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), Externref, F32, F64, Funcref, I32, I64, Invalid, V128, and Void.
parseMVT()
MVT llvm::WebAssembly::parseMVT (StringRef Type)
Definition at line 59 of file WebAssemblyTypeUtilities.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::MVT::externref, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::funcref, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::INVALID_SIMPLE_VALUE_TYPE, llvm::MVT::v16i8, llvm::MVT::v2i64, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by llvm::WebAssemblyFunctionInfo::initializeBaseYamlFields().
parseType()
std::optional< wasm::ValType > llvm::WebAssembly::parseType (StringRef Type)
Definition at line 24 of file WebAssemblyTypeUtilities.cpp.
References llvm::wasm::EXTERNREF, llvm::wasm::F32, llvm::wasm::F64, llvm::wasm::FUNCREF, llvm::wasm::I32, llvm::wasm::I64, and llvm::wasm::V128.
regClassToValType() [1/2]
wasm::ValType llvm::WebAssembly::regClassToValType (const TargetRegisterClass * RC)
Definition at line 172 of file WebAssemblyTypeUtilities.cpp.
References assert(), llvm::TargetRegisterClass::getID(), and regClassToValType().
regClassToValType() [2/2]
wasm::ValType llvm::WebAssembly::regClassToValType (unsigned RC)
Definition at line 151 of file WebAssemblyTypeUtilities.cpp.
References llvm::wasm::EXTERNREF, llvm::wasm::F32, llvm::wasm::F64, llvm::wasm::FUNCREF, llvm::wasm::I32, llvm::wasm::I64, llvm_unreachable, and llvm::wasm::V128.
Referenced by llvm::WebAssemblyMCInstLower::lower(), regClassToValType(), and llvm::WebAssemblyAsmTypeCheck::typeCheck().
signatureToString()
std::string llvm::WebAssembly::signatureToString (const wasm::WasmSignature * Sig)
Definition at line 116 of file WebAssemblyTypeUtilities.cpp.
References llvm::wasm::WasmSignature::Params, llvm::wasm::WasmSignature::Returns, S, and typeListToString().
Referenced by llvm::WebAssemblyTargetAsmStreamer::emitFunctionType(), llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction(), llvm::WebAssemblyInstPrinter::printOperand(), and llvm::WebAssemblyInstPrinter::printWebAssemblySignatureOperand().
toValType()
wasm::ValType llvm::WebAssembly::toValType (MVT Type)
Definition at line 125 of file WebAssemblyTypeUtilities.cpp.
References llvm::MVT::externref, llvm::wasm::EXTERNREF, llvm::MVT::f32, llvm::wasm::F32, llvm::MVT::f64, llvm::wasm::F64, llvm::MVT::funcref, llvm::wasm::FUNCREF, llvm::MVT::i32, llvm::wasm::I32, llvm::MVT::i64, llvm::wasm::I64, llvm_unreachable, llvm::wasm::V128, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by llvm::valTypesFromMVTs(), and wasmSymbolSetType().
typeListToString()
std::string llvm::WebAssembly::typeListToString (ArrayRef< wasm::ValType > List)
Definition at line 106 of file WebAssemblyTypeUtilities.cpp.
References List, S, and typeToString().
Referenced by llvm::WebAssemblyTargetAsmStreamer::emitTagType(), and signatureToString().
typeToString()
const char * llvm::WebAssembly::typeToString (wasm::ValType Type)
Definition at line 102 of file WebAssemblyTypeUtilities.cpp.
References anyTypeToString().
Referenced by llvm::WebAssemblyTargetAsmStreamer::emitGlobalType(), llvm::WebAssemblyTargetAsmStreamer::emitTableType(), printTypes(), and typeListToString().
wasmSymbolSetType()
void llvm::WebAssembly::wasmSymbolSetType (MCSymbolWasm * Sym, const Type * GlobalVT, const SmallVector< MVT, 1 > & VTs)
Sets a Wasm Symbol Type.
Definition at line 177 of file WebAssemblyTypeUtilities.cpp.
References assert(), llvm::wasm::EXTERNREF, llvm::wasm::FUNCREF, llvm::Type::getArrayElementType(), llvm::MCSymbolWasm::getType(), llvm::Type::isArrayTy(), isExternrefType(), isFuncrefType(), isRefType(), llvm::report_fatal_error(), llvm::MCSymbolWasm::setGlobalType(), llvm::MCSymbolWasm::setTableType(), llvm::MCSymbolWasm::setType(), toValType(), llvm::wasm::WASM_SYMBOL_TYPE_GLOBAL, and llvm::wasm::WASM_SYMBOL_TYPE_TABLE.
Referenced by llvm::WebAssemblyAsmPrinter::emitGlobalVariable().
Variable Documentation
ClangCallTerminateFn
const char* const llvm::WebAssembly::ClangCallTerminateFn
CxaBeginCatchFn
const char *const llvm::WebAssembly::CxaBeginCatchFn = "__cxa_begin_catch"
Definition at line 46 of file WebAssemblyUtilities.cpp.
Referenced by mayThrow().
CxaRethrowFn
const char *const llvm::WebAssembly::CxaRethrowFn = "__cxa_rethrow"
Definition at line 47 of file WebAssemblyUtilities.cpp.
End
const unsigned llvm::WebAssembly::End = 0x0b static
Definition at line 135 of file WebAssemblyMCTargetDesc.h.
Nop
const unsigned llvm::WebAssembly::Nop = 0x01 static
Instruction opcodes emitted via means other than CodeGen.
Definition at line 134 of file WebAssemblyMCTargetDesc.h.
Referenced by llvm::avoidZeroOffsetLandingPad(), llvm::AsmPrinter::emitNops(), llvm::X86InstrInfo::getNop(), llvm::HexagonInstrInfo::getNop(), llvm::PPCInstrInfo::getNop(), and llvm::HexagonMCInstrInfo::padEndloop().
PersonalityWrapperFn
const char *const llvm::WebAssembly::PersonalityWrapperFn
Initial value:
=
    "_Unwind_Wasm_CallPersonality"
Definition at line 49 of file WebAssemblyUtilities.cpp.
Referenced by mayThrow().
StdTerminateFn
const char *const llvm::WebAssembly::StdTerminateFn = "_ZSt9terminatev"
Definition at line 48 of file WebAssemblyUtilities.cpp.
Referenced by mayThrow().
WasmEnableEH
cl::opt< bool > llvm::WebAssembly::WasmEnableEH
Referenced by basicCheckForEHAndSjLj(), and llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo().
WasmEnableEmEH
cl::opt< bool > llvm::WebAssembly::WasmEnableEmEH
Referenced by basicCheckForEHAndSjLj(), and llvm::WebAssemblyAsmPrinter::emitDecls().
WasmEnableEmSjLj
cl::opt< bool > llvm::WebAssembly::WasmEnableEmSjLj
Referenced by basicCheckForEHAndSjLj(), and llvm::WebAssemblyAsmPrinter::emitDecls().
WasmEnableSjLj
cl::opt< bool > llvm::WebAssembly::WasmEnableSjLj
Referenced by basicCheckForEHAndSjLj(), canLongjmp(), and llvm::WebAssemblyMCAsmInfo::WebAssemblyMCAsmInfo().