LLVM: llvm::sampleprof Namespace Reference
llvm::sampleprof Namespace Reference
Classes
class CSProfileConverter
class DefaultFunctionPruningStrategy
class FunctionPruningStrategy
When writing a profile with size limit, user may want to use a different strategy to reduce function count other than dropping functions with fewest samples first.
class FunctionSamples
Representation of the samples collected for a function.
struct LineLocation
Represents the relative location of an instruction.
struct LineLocationHash
class ProfiledCallGraph
struct ProfiledCallGraphEdge
struct ProfiledCallGraphNode
class ProfileSymbolList
ProfileSymbolList records the list of function symbols shown up in the binary used to generate the profile.
class SampleContext
struct SampleContextFrame
struct SampleContextFrameHash
class SampleContextTrimmer
SampleContextTrimmer impelements helper functions to trim, merge cold context profiles.
class SampleProfileReader
Sample-based profile reader.
class SampleProfileReaderBinary
class SampleProfileReaderCompactBinary
class SampleProfileReaderExtBinary
class SampleProfileReaderExtBinaryBase
SampleProfileReaderExtBinaryBase/SampleProfileWriterExtBinaryBase defines the basic structure of the extensible binary format.
class SampleProfileReaderGCC
class SampleProfileReaderItaniumRemapper
SampleProfileReaderItaniumRemapper remaps the profile data from a sample profile data reader, by applying a provided set of equivalences between components of the symbol names in the profile.
class SampleProfileReaderRawBinary
class SampleProfileReaderText
class SampleProfileWriter
Sample-based profile writer. Base class.
class SampleProfileWriterBinary
Sample-based profile writer (binary format).
class SampleProfileWriterCompactBinary
class SampleProfileWriterExtBinary
class SampleProfileWriterExtBinaryBase
class SampleProfileWriterRawBinary
class SampleProfileWriterText
Sample-based profile writer (text format).
class SampleRecord
Representation of a single sample record.
class SampleSorter
Sort a LocationT->SampleT map by LocationT.
struct SecHdrTableEntry
Typedefs
using SampleContextFrameVector = SmallVector< SampleContextFrame, 1 >
using SampleContextFrames = ArrayRef< SampleContextFrame >
using BodySampleMap = std::map< LineLocation, SampleRecord >
using FunctionSamplesMap = std::map< std::string, FunctionSamples, std::less<> >
using CallsiteSampleMap = std::map< LineLocation, FunctionSamplesMap >
using SampleProfileMap = std::unordered_map< SampleContext, FunctionSamples, SampleContext::Hash >
using NameFunctionSamples = std::pair< SampleContext, const FunctionSamples * >
using InlineCallStack = SmallVector< FunctionSamples *, 10 >
Enumerations
enum SampleProfileFormat {
SPF_None = 0, SPF_Text = 0x1, SPF_Compact_Binary = 0x2, SPF_GCC = 0x3,
SPF_Ext_Binary = 0x4, SPF_Binary = 0xff
}
enum SecType {
SecInValid = 0, SecProfSummary = 1, SecNameTable = 2, SecProfileSymbolList = 3,
SecFuncOffsetTable = 4, SecFuncMetadata = 5, SecCSNameTable = 6, SecFuncProfileFirst = 32,
SecLBRProfile = SecFuncProfileFirst
}
enum SecCommonFlags : uint32_t { SecCommonFlags::SecFlagInValid = 0, SecCommonFlags::SecFlagCompress = (1 << 0), SecCommonFlags::SecFlagFlat = (1 << 1) }
enum SecNameTableFlags : uint32_t { SecNameTableFlags::SecFlagInValid = 0, SecNameTableFlags::SecFlagMD5Name = (1 << 0), SecNameTableFlags::SecFlagFixedLengthMD5 = (1 << 1), SecNameTableFlags::SecFlagUniqSuffix = (1 << 2) }
enum SecProfSummaryFlags : uint32_t {
SecProfSummaryFlags::SecFlagInValid = 0, SecProfSummaryFlags::SecFlagPartial = (1 << 0), SecProfSummaryFlags::SecFlagFullContext = (1 << 1), SecProfSummaryFlags::SecFlagFSDiscriminator = (1 << 2),
SecProfSummaryFlags::SecFlagIsPreInlined = (1 << 4)
}
enum SecFuncMetadataFlags : uint32_t { SecFuncMetadataFlags::SecFlagInvalid = 0, SecFuncMetadataFlags::SecFlagIsProbeBased = (1 << 0), SecFuncMetadataFlags::SecFlagHasAttribute = (1 << 1) }
enum SecFuncOffsetFlags : uint32_t { SecFuncOffsetFlags::SecFlagInvalid = 0, SecFuncOffsetFlags::SecFlagOrdered = (1 << 0) }
enum ContextStateMask {
UnknownContext = 0x0, RawContext = 0x1, SyntheticContext = 0x2, InlinedContext = 0x4,
MergedContext = 0x8
}
enum ContextAttributeMask { ContextNone = 0x0, ContextWasInlined = 0x1, ContextShouldBeInlined = 0x2, ContextDuplicatedIntoBase }
enum HistType {
HIST_TYPE_INTERVAL, HIST_TYPE_POW2, HIST_TYPE_SINGLE_VALUE, HIST_TYPE_CONST_DELTA,
HIST_TYPE_INDIR_CALL, HIST_TYPE_AVERAGE, HIST_TYPE_IOR, HIST_TYPE_INDIR_CALL_TOPN
}
enum SectionLayout { DefaultLayout, CtxSplitLayout, NumOfLayout }
enum FSDiscriminatorPass {
Base = 0, Pass0 = 0, Pass1 = 1, Pass2 = 2,
Pass3 = 3, Pass4 = 4, PassLast = 4
}
Functions
static uint64_t SPMagic (SampleProfileFormat Format=SPF_Binary)
static StringRef getRepInFormat (StringRef Name, bool UseMD5, std::string &GUIDBuf)
Get the proper representation of a string according to whether the current Format uses MD5 to represent the string.
static uint64_t SPVersion ()
static std::string getSecName (SecType Type)
template<class SecFlagType >
static void verifySecFlag (SecType Type, SecFlagType Flag)
template<class SecFlagType >
static void addSecFlag (SecHdrTableEntry &Entry, SecFlagType Flag)
template<class SecFlagType >
static void removeSecFlag (SecHdrTableEntry &Entry, SecFlagType Flag)
template<class SecFlagType >
static bool hasSecFlag (const SecHdrTableEntry &Entry, SecFlagType Flag)
raw_ostream & operator<< (raw_ostream &OS, const LineLocation &Loc)
raw_ostream & operator<< (raw_ostream &OS, const SampleRecord &Sample)
static hash_code hash_value (const SampleContextFrame &arg)
static hash_code hash_value (const SampleContext &arg)
raw_ostream & operator<< (raw_ostream &OS, const FunctionSamples &FS)
void sortFuncProfiles (const SampleProfileMap &ProfileMap, std::vector< NameFunctionSamples > &SortedProfiles)
Variables
const std::array< SmallVector< SecHdrTableEntry, 8 >, NumOfLayout > ExtBinaryHdrLayoutTable
Typedef Documentation
BodySampleMap
using llvm::sampleprof::BodySampleMap = typedef std::map<LineLocation, SampleRecord>
Definition at line 715 of file SampleProf.h.
CallsiteSampleMap
using llvm::sampleprof::CallsiteSampleMap = typedef std::map<LineLocation, FunctionSamplesMap>
Definition at line 719 of file SampleProf.h.
FunctionSamplesMap
using llvm::sampleprof::FunctionSamplesMap = typedef std::map<std::string, FunctionSamples, std::less<> >
Definition at line 718 of file SampleProf.h.
InlineCallStack
using llvm::sampleprof::InlineCallStack = typedef SmallVector<FunctionSamples *, 10>
Definition at line 849 of file SampleProfReader.h.
NameFunctionSamples
using llvm::sampleprof::NameFunctionSamples = typedef std::pair<SampleContext, const FunctionSamples *>
Definition at line 1224 of file SampleProf.h.
SampleContextFrames
using llvm::sampleprof::SampleContextFrames = typedef ArrayRef<SampleContextFrame>
Definition at line 499 of file SampleProf.h.
SampleContextFrameVector
using llvm::sampleprof::SampleContextFrameVector = typedef SmallVector<SampleContextFrame, 1>
Definition at line 498 of file SampleProf.h.
SampleProfileMap
using llvm::sampleprof::SampleProfileMap = typedef std::unordered_map<SampleContext, FunctionSamples, SampleContext::Hash>
Definition at line 1222 of file SampleProf.h.
Enumeration Type Documentation
ContextAttributeMask
enum llvm::sampleprof::ContextAttributeMask
Enumerator
ContextNone
ContextWasInlined
ContextShouldBeInlined
ContextDuplicatedIntoBase
Definition at line 455 of file SampleProf.h.
ContextStateMask
enum llvm::sampleprof::ContextStateMask
Enumerator
UnknownContext
RawContext
SyntheticContext
InlinedContext
MergedContext
Definition at line 446 of file SampleProf.h.
FSDiscriminatorPass
enum llvm::sampleprof::FSDiscriminatorPass
Enumerator
Base
Pass0
Pass1
Pass2
Pass3
Pass4
PassLast
Definition at line 57 of file Discriminator.h.
HistType
enum llvm::sampleprof::HistType
Enumerator
HIST_TYPE_INTERVAL
HIST_TYPE_POW2
HIST_TYPE_SINGLE_VALUE
HIST_TYPE_CONST_DELTA
HIST_TYPE_INDIR_CALL
HIST_TYPE_AVERAGE
HIST_TYPE_IOR
HIST_TYPE_INDIR_CALL_TOPN
Definition at line 853 of file SampleProfReader.h.
SampleProfileFormat
enum llvm::sampleprof::SampleProfileFormat
Enumerator
SPF_None
SPF_Text
SPF_Compact_Binary
SPF_GCC
SPF_Ext_Binary
SPF_Binary
Definition at line 90 of file SampleProf.h.
SecCommonFlags
enum llvm::sampleprof::SecCommonFlags : uint32_t strong
Enumerator
SecFlagInValid
SecFlagCompress
SecFlagFlat
Definition at line 172 of file SampleProf.h.
SecFuncMetadataFlags
enum llvm::sampleprof::SecFuncMetadataFlags : uint32_t strong
Enumerator
SecFlagInvalid
SecFlagIsProbeBased
SecFlagHasAttribute
Definition at line 209 of file SampleProf.h.
SecFuncOffsetFlags
enum llvm::sampleprof::SecFuncOffsetFlags : uint32_t strong
Enumerator
SecFlagInvalid
SecFlagOrdered
Definition at line 215 of file SampleProf.h.
SecNameTableFlags
enum llvm::sampleprof::SecNameTableFlags : uint32_t strong
Enumerator
SecFlagInValid
SecFlagMD5Name
SecFlagFixedLengthMD5
SecFlagUniqSuffix
Definition at line 182 of file SampleProf.h.
SecProfSummaryFlags
enum llvm::sampleprof::SecProfSummaryFlags : uint32_t strong
Enumerator
SecFlagInValid
SecFlagPartial
SecFlagPartial means the profile is for common/shared code.
The common profile is usually merged from profiles collected from running other targets.
SecFlagFullContext
SecFlagContext means this is context-sensitive flat profile for CSSPGO.
SecFlagFSDiscriminator
SecFlagFSDiscriminator means this profile uses flow-sensitive discriminators.
SecFlagIsPreInlined
SecFlagIsPreInlined means this profile contains ShouldBeInlined contexts thus this is CS preinliner computed.
Definition at line 192 of file SampleProf.h.
SectionLayout
enum llvm::sampleprof::SectionLayout
Enumerator
DefaultLayout
CtxSplitLayout
NumOfLayout
Definition at line 29 of file SampleProfWriter.h.
SecType
enum llvm::sampleprof::SecType
Enumerator
SecInValid
SecProfSummary
SecNameTable
SecProfileSymbolList
SecFuncOffsetTable
SecFuncMetadata
SecCSNameTable
SecFuncProfileFirst
SecLBRProfile
Definition at line 121 of file SampleProf.h.
Function Documentation
addSecFlag()
template<class SecFlagType > static void llvm::sampleprof::addSecFlag (SecHdrTableEntry & Entry, SecFlagType Flag) inline static
Definition at line 251 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileWriterExtBinaryBase::addSectionFlag().
getRepInFormat()
static StringRef llvm::sampleprof::getRepInFormat (StringRef Name, bool UseMD5, std::string & GUIDBuf) inline static
Get the proper representation of a string according to whether the current Format uses MD5 to represent the string.
Definition at line 108 of file SampleProf.h.
References llvm::GlobalValue::getGUID(), and llvm::to_string().
Referenced by llvm::sampleprof::FunctionSamples::findFunctionSamplesAt(), llvm::SampleContextTracker::getBaseSamplesFor(), llvm::SampleContextTracker::getCalleeContextSamplesFor(), llvm::sampleprof::SampleProfileReader::getOrCreateSamplesFor(), and llvm::sampleprof::SampleProfileReader::getSamplesFor().
getSecName()
static std::string llvm::sampleprof::getSecName (SecType Type) inline static
Definition at line 134 of file SampleProf.h.
References SecCSNameTable, SecFuncMetadata, SecFuncOffsetTable, SecInValid, SecLBRProfile, SecNameTable, SecProfileSymbolList, and SecProfSummary.
hash_value() [1/2]
static hash_code llvm::sampleprof::hash_value (const SampleContext & arg) inline static
Definition at line 707 of file SampleProf.h.
References llvm::sampleprof::SampleContext::getContextFrames(), llvm::sampleprof::SampleContext::getName(), llvm::sampleprof::SampleContext::hasContext(), and hash_value().
hash_value() [2/2]
static hash_code llvm::sampleprof::hash_value (const SampleContextFrame & arg) inline static
Definition at line 493 of file SampleProf.h.
References llvm::sampleprof::LineLocation::Discriminator, llvm::sampleprof::SampleContextFrame::FuncName, llvm::hash_combine(), llvm::sampleprof::LineLocation::LineOffset, and llvm::sampleprof::SampleContextFrame::Location.
Referenced by llvm::sampleprof::SampleContext::getHashCode(), and hash_value().
hasSecFlag()
template<class SecFlagType > static bool llvm::sampleprof::hasSecFlag (const SecHdrTableEntry & Entry, SecFlagType Flag) inline static
Definition at line 267 of file SampleProf.h.
operator<<() [1/3]
raw_ostream & llvm::sampleprof::operator<< (raw_ostream & OS, const FunctionSamples & FS)
Definition at line 195 of file SampleProf.cpp.
References llvm::X86AS::FS, and OS.
operator<<() [2/3]
raw_ostream & llvm::sampleprof::operator<< (raw_ostream & OS, const LineLocation & Loc)
Definition at line 111 of file SampleProf.cpp.
References OS, and llvm::sampleprof::LineLocation::print().
operator<<() [3/3]
raw_ostream & llvm::sampleprof::operator<< (raw_ostream & OS, const SampleRecord & Sample)
Definition at line 148 of file SampleProf.cpp.
References OS, and llvm::sampleprof::SampleRecord::print().
removeSecFlag()
template<class SecFlagType > static void llvm::sampleprof::removeSecFlag (SecHdrTableEntry & Entry, SecFlagType Flag) inline static
Definition at line 259 of file SampleProf.h.
sortFuncProfiles()
void llvm::sampleprof::sortFuncProfiles (const SampleProfileMap & ProfileMap, std::vector< NameFunctionSamples > & SortedProfiles)
Definition at line 201 of file SampleProf.cpp.
References assert(), B, I, and llvm::stable_sort().
Referenced by llvm::sampleprof::DefaultFunctionPruningStrategy::DefaultFunctionPruningStrategy(), llvm::sampleprof::SampleProfileReader::dump(), llvm::sampleprof::SampleProfileReader::dumpJson(), and llvm::sampleprof::SampleProfileWriter::writeFuncProfiles().
SPMagic()
static uint64_t llvm::sampleprof::SPMagic (SampleProfileFormat Format = SPF_Binary) inline static
Definition at line 99 of file SampleProf.h.
References uint64_t.
Referenced by llvm::sampleprof::SampleProfileReaderRawBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderExtBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderCompactBinary::hasFormat(), and llvm::sampleprof::SampleProfileWriterBinary::writeMagicIdent().
SPVersion()
static uint64_t llvm::sampleprof::SPVersion () inline static
Definition at line 116 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileReaderBinary::readMagicIdent(), and llvm::sampleprof::SampleProfileWriterBinary::writeMagicIdent().
verifySecFlag()
template<class SecFlagType > static void llvm::sampleprof::verifySecFlag (SecType Type, SecFlagType Flag) inline static
Definition at line 224 of file SampleProf.h.
References llvm_unreachable, SecFuncMetadata, SecFuncOffsetTable, SecNameTable, and SecProfSummary.
Variable Documentation
ExtBinaryHdrLayoutTable
const std::array<SmallVector<SecHdrTableEntry, 8>, NumOfLayout> llvm::sampleprof::ExtBinaryHdrLayoutTable
Initial value:
= {
        SmallVector<SecHdrTableEntry, 8>({{SecProfSummary, 0, 0, 0, 0},
                                          {SecNameTable, 0, 0, 0, 0},
                                          {SecCSNameTable, 0, 0, 0, 0},
                                          {SecFuncOffsetTable, 0, 0, 0, 0},
                                          {SecLBRProfile, 0, 0, 0, 0},
                                          {SecProfileSymbolList, 0, 0, 0, 0},
                                          {SecFuncMetadata, 0, 0, 0, 0}}),
        SmallVector<SecHdrTableEntry, 8>({{SecProfSummary, 0, 0, 0, 0},
                                          {SecNameTable, 0, 0, 0, 0},
                                          {SecFuncOffsetTable, 0, 0, 0, 0},
                                          {SecLBRProfile, 0, 0, 0, 0},
                                          {SecFuncOffsetTable, 0, 0, 0, 0},
                                          {SecLBRProfile, 0, 0, 0, 0},
                                          {SecProfileSymbolList, 0, 0, 0, 0},
                                          {SecFuncMetadata, 0, 0, 0, 0}}),
}
Definition at line 227 of file SampleProfWriter.h.