LLVM: llvm::logicalview Namespace Reference
llvm::logicalview Namespace Reference
Classes
class LVBinaryReader
class LVCompare
struct LVCounter
class LVDoubleMap
class LVElement
class LVELFReader
class LVLine
class LVLineAssembler
class LVLineDebug
class LVLocation
class LVLocationSymbol
class LVObject
class LVOperation
class LVOptions
class LVPatterns
class LVProperties
class LVRange
class LVRangeEntry
class LVReader
The logical reader owns of all the logical elements created during the debug information parsing.
class LVReaderHandler
class LVScope
class LVScopeAggregate
class LVScopeAlias
class LVScopeArray
class LVScopeCompileUnit
class LVScopeEnumeration
class LVScopeFormalPack
class LVScopeFunction
class LVScopeFunctionInlined
class LVScopeFunctionType
class LVScopeNamespace
class LVScopeRoot
class LVScopeTemplatePack
class LVSplitContext
class LVStringPool
class LVSymbol
class LVSymbolTable
struct LVSymbolTableEntry
class LVType
class LVTypeDefinition
class LVTypeEnumerator
class LVTypeImport
class LVTypeParam
class LVTypeSubrange
Typedefs
using LVPassEntry = std::tuple< LVReader *, LVElement *, LVComparePass >
using LVPassTable = std::vector< LVPassEntry >
using LVElementKindSet = std::set< LVElementKind >
using LVElementDispatch = std::map< LVElementKind, LVElementGetFunction >
using LVElementRequest = std::vector< LVElementGetFunction >
using LVLineKindSet = std::set< LVLineKind >
using LVLineDispatch = std::map< LVLineKind, LVLineGetFunction >
using LVLineRequest = std::vector< LVLineGetFunction >
using LVLineRange = std::pair< LVLine *, LVLine * >
using LVSectionIndex = uint64_t
using LVAddress = uint64_t
using LVHalf = uint16_t
using LVLevel = uint32_t
using LVOffset = uint64_t
using LVSigned = int64_t
using LVUnsigned = uint64_t
using LVSmall = uint8_t
using LVElementSetFunction = void(LVElement::*)()
using LVElementGetFunction = bool(LVElement::*)() const
using LVLineSetFunction = void(LVLine::*)()
using LVLineGetFunction = bool(LVLine::*)() const
using LVObjectSetFunction = void(LVObject::*)()
using LVObjectGetFunction = bool(LVObject::*)() const
using LVScopeSetFunction = void(LVScope::*)()
using LVScopeGetFunction = bool(LVScope::*)() const
using LVSymbolSetFunction = void(LVSymbol::*)()
using LVSymbolGetFunction = bool(LVSymbol::*)() const
using LVTypeSetFunction = void(LVType::*)()
using LVTypeGetFunction = bool(LVType::*)() const
using LVElements = SmallVector< LVElement *, 8 >
using LVLines = SmallVector< LVLine *, 8 >
using LVLocations = SmallVector< LVLocation *, 8 >
using LVOperations = SmallVector< LVOperation *, 8 >
using LVScopes = SmallVector< LVScope *, 8 >
using LVSymbols = SmallVector< LVSymbol *, 8 >
using LVTypes = SmallVector< LVType *, 8 >
using LVOffsets = SmallVector< LVOffset, 8 >
using LVValidLocation = bool(LVLocation::*)()
using LVOffsetSet = std::set< uint64_t >
using LVAttributeKindSet = std::set< LVAttributeKind >
using LVCompareKindSet = std::set< LVCompareKind >
using LVOutputKindSet = std::set< LVOutputKind >
using LVPrintKindSet = std::set< LVPrintKind >
using LVReportKindSet = std::set< LVReportKind >
using LVWarningKindSet = std::set< LVWarningKind >
using LVInternalKindSet = std::set< LVInternalKind >
using LVAddressRange = std::pair< LVAddress, LVAddress >
using LVRangeEntries = std::vector< LVRangeEntry >
using LVNameInfo = std::pair< LVAddress, uint64_t >
using LVPublicNames = std::map< LVScope *, LVNameInfo >
using LVPublicAddresses = std::map< LVAddress, LVNameInfo >
using LVScopeKindSet = std::set< LVScopeKind >
using LVScopeDispatch = std::map< LVScopeKind, LVScopeGetFunction >
using LVScopeRequest = std::vector< LVScopeGetFunction >
using LVOffsetElementMap = std::map< LVOffset, LVElement * >
using LVOffsetLinesMap = std::map< LVOffset, LVLines >
using LVOffsetLocationsMap = std::map< LVOffset, LVLocations >
using LVOffsetSymbolMap = std::map< LVOffset, LVSymbol * >
using LVTagOffsetsMap = std::map< dwarf::Tag, LVOffsets >
using LVSortValue = int
using LVSortFunction = LVSortValue(*)(const LVObject *LHS, const LVObject *RHS)
using LVSymbolKindSet = std::set< LVSymbolKind >
using LVSymbolDispatch = std::map< LVSymbolKind, LVSymbolGetFunction >
using LVSymbolRequest = std::vector< LVSymbolGetFunction >
using LVTypeKindSelection = std::set< LVTypeKind >
using LVTypeDispatch = std::map< LVTypeKind, LVTypeGetFunction >
using LVTypeRequest = std::vector< LVTypeGetFunction >
using LVReaders = std::vector< std::unique_ptr< LVReader > >
using ArgVector = std::vector< std::string >
using PdbOrObj = PointerUnion< object::ObjectFile *, pdb::PDBFile * >
using AttributeSpec = DWARFAbbreviationDeclaration::AttributeSpec
Enumerations
enum LVSubclassID : unsigned char {
LVSubclassID::LV_ELEMENT, LVSubclassID::LV_LINE_FIRST, LVSubclassID::LV_LINE, LVSubclassID::LV_LINE_DEBUG,
LVSubclassID::LV_LINE_ASSEMBLER, LVSubclassID::LV_LINE_LAST, LVSubclassID::lV_SCOPE_FIRST, LVSubclassID::LV_SCOPE,
LVSubclassID::LV_SCOPE_AGGREGATE, LVSubclassID::LV_SCOPE_ALIAS, LVSubclassID::LV_SCOPE_ARRAY, LVSubclassID::LV_SCOPE_COMPILE_UNIT,
LVSubclassID::LV_SCOPE_ENUMERATION, LVSubclassID::LV_SCOPE_FORMAL_PACK, LVSubclassID::LV_SCOPE_FUNCTION, LVSubclassID::LV_SCOPE_FUNCTION_INLINED,
LVSubclassID::LV_SCOPE_FUNCTION_TYPE, LVSubclassID::LV_SCOPE_NAMESPACE, LVSubclassID::LV_SCOPE_ROOT, LVSubclassID::LV_SCOPE_TEMPLATE_PACK,
LVSubclassID::LV_SCOPE_LAST, LVSubclassID::LV_SYMBOL_FIRST, LVSubclassID::LV_SYMBOL, LVSubclassID::LV_SYMBOL_LAST,
LVSubclassID::LV_TYPE_FIRST, LVSubclassID::LV_TYPE, LVSubclassID::LV_TYPE_DEFINITION, LVSubclassID::LV_TYPE_ENUMERATOR,
LVSubclassID::LV_TYPE_IMPORT, LVSubclassID::LV_TYPE_PARAM, LVSubclassID::LV_TYPE_SUBRANGE, LVSubclassID::LV_TYPE_LAST
}
enum LVElementKind { LVElementKind::Discarded, LVElementKind::Global, LVElementKind::Optimized, LVElementKind::LastEntry }
enum LVLineKind {
LVLineKind::IsBasicBlock, LVLineKind::IsDiscriminator, LVLineKind::IsEndSequence, LVLineKind::IsEpilogueBegin,
LVLineKind::IsLineDebug, LVLineKind::IsLineAssembler, LVLineKind::IsNewStatement, LVLineKind::IsPrologueEnd,
LVLineKind::IsAlwaysStepInto, LVLineKind::IsNeverStepInto, LVLineKind::LastEntry
}
enum LVBinaryType { LVBinaryType::NONE, LVBinaryType::ELF, LVBinaryType::COFF }
enum LVComparePass { LVComparePass::Missing, LVComparePass::Added }
enum LVAttributeKind {
LVAttributeKind::All, LVAttributeKind::Argument, LVAttributeKind::Base, LVAttributeKind::Coverage,
LVAttributeKind::Directories, LVAttributeKind::Discarded, LVAttributeKind::Discriminator, LVAttributeKind::Encoded,
LVAttributeKind::Extended, LVAttributeKind::Filename, LVAttributeKind::Files, LVAttributeKind::Format,
LVAttributeKind::Gaps, LVAttributeKind::Generated, LVAttributeKind::Global, LVAttributeKind::Inserted,
LVAttributeKind::Level, LVAttributeKind::Linkage, LVAttributeKind::Local, LVAttributeKind::Location,
LVAttributeKind::Offset, LVAttributeKind::Pathname, LVAttributeKind::Producer, LVAttributeKind::Publics,
LVAttributeKind::Qualified, LVAttributeKind::Qualifier, LVAttributeKind::Range, LVAttributeKind::Reference,
LVAttributeKind::Register, LVAttributeKind::Standard, LVAttributeKind::Subrange, LVAttributeKind::System,
LVAttributeKind::Typename, LVAttributeKind::Underlying, LVAttributeKind::Zero
}
enum LVCompareKind {
LVCompareKind::All, LVCompareKind::Lines, LVCompareKind::Scopes, LVCompareKind::Symbols,
LVCompareKind::Types
}
enum LVOutputKind { LVOutputKind::All, LVOutputKind::Split, LVOutputKind::Json, LVOutputKind::Text }
enum LVPrintKind {
LVPrintKind::All, LVPrintKind::Elements, LVPrintKind::Instructions, LVPrintKind::Lines,
LVPrintKind::Scopes, LVPrintKind::Sizes, LVPrintKind::Symbols, LVPrintKind::Summary,
LVPrintKind::Types, LVPrintKind::Warnings
}
enum LVReportKind {
LVReportKind::All, LVReportKind::Children, LVReportKind::List, LVReportKind::Parents,
LVReportKind::View
}
enum LVWarningKind {
LVWarningKind::All, LVWarningKind::Coverages, LVWarningKind::Lines, LVWarningKind::Locations,
LVWarningKind::Ranges
}
enum LVInternalKind {
LVInternalKind::All, LVInternalKind::Cmdline, LVInternalKind::ID, LVInternalKind::Integrity,
LVInternalKind::None, LVInternalKind::Tag
}
enum LVScopeKind {
LVScopeKind::IsAggregate, LVScopeKind::IsArray, LVScopeKind::IsBlock, LVScopeKind::IsCallSite,
LVScopeKind::IsCatchBlock, LVScopeKind::IsClass, LVScopeKind::IsCompileUnit, LVScopeKind::IsEntryPoint,
LVScopeKind::IsEnumeration, LVScopeKind::IsFunction, LVScopeKind::IsFunctionType, LVScopeKind::IsInlinedFunction,
LVScopeKind::IsLabel, LVScopeKind::IsLexicalBlock, LVScopeKind::IsMember, LVScopeKind::IsNamespace,
LVScopeKind::IsRoot, LVScopeKind::IsStructure, LVScopeKind::IsSubprogram, LVScopeKind::IsTemplate,
LVScopeKind::IsTemplateAlias, LVScopeKind::IsTemplatePack, LVScopeKind::IsTryBlock, LVScopeKind::IsUnion,
LVScopeKind::LastEntry
}
enum LVSortMode {
LVSortMode::None = 0, LVSortMode::Kind, LVSortMode::Line, LVSortMode::Name,
LVSortMode::Offset
}
enum LVSymbolKind {
LVSymbolKind::IsCallSiteParameter, LVSymbolKind::IsConstant, LVSymbolKind::IsInheritance, LVSymbolKind::IsMember,
LVSymbolKind::IsParameter, LVSymbolKind::IsUnspecified, LVSymbolKind::IsVariable, LVSymbolKind::LastEntry
}
enum LVTypeKind {
LVTypeKind::IsBase, LVTypeKind::IsConst, LVTypeKind::IsEnumerator, LVTypeKind::IsImport,
LVTypeKind::IsImportDeclaration, LVTypeKind::IsImportModule, LVTypeKind::IsPointer, LVTypeKind::IsPointerMember,
LVTypeKind::IsReference, LVTypeKind::IsRestrict, LVTypeKind::IsRvalueReference, LVTypeKind::IsSubrange,
LVTypeKind::IsTemplateParam, LVTypeKind::IsTemplateTemplateParam, LVTypeKind::IsTemplateTypeParam, LVTypeKind::IsTemplateValueParam,
LVTypeKind::IsTypedef, LVTypeKind::IsUnaligned, LVTypeKind::IsUnspecified, LVTypeKind::IsVolatile,
LVTypeKind::IsModifier, LVTypeKind::LastEntry
}
Functions
LVCompare & getComparator ()
StringRef typeNone ()
StringRef typeVoid ()
StringRef typeInt ()
StringRef typeUnknown ()
StringRef emptyString ()
LVOptions & options ()
void setOptions (LVOptions *Options)
LVPatterns & patterns ()
LVReader & getReader ()
LVSplitContext & getReaderSplitContext ()
LVScopeCompileUnit * getReaderCompileUnit ()
LVSortFunction getSortFunction ()
LVSortValue compareKind (const LVObject *LHS, const LVObject *RHS)
LVSortValue compareLine (const LVObject *LHS, const LVObject *RHS)
LVSortValue compareName (const LVObject *LHS, const LVObject *RHS)
LVSortValue compareOffset (const LVObject *LHS, const LVObject *RHS)
LVSortValue compareRange (const LVObject *LHS, const LVObject *RHS)
LVSortValue sortByKind (const LVObject *LHS, const LVObject *RHS)
LVSortValue sortByLine (const LVObject *LHS, const LVObject *RHS)
LVSortValue sortByName (const LVObject *LHS, const LVObject *RHS)
LVStringPool & getStringPool ()
FormattedNumber hexValue (uint64_t N, unsigned Width=HEX_WIDTH, bool Upper=false)
std::string hexString (uint64_t Value, size_t Width=HEX_WIDTH)
std::string hexSquareString (uint64_t Value)
template<typename... Args>
std::string formatAttributes (const StringRef First, Args... Others)
template<typename MapType , typename KeyType , typename ValueType >
void addItem (MapType *Map, KeyType Key, ValueType Value)
std::string transformPath (StringRef Path)
std::string flattenedFilePath (StringRef Path)
std::string formattedKind (StringRef Kind)
std::string formattedName (StringRef Name)
std::string formattedNames (StringRef Name1, StringRef Name2)
uint16_t getCodeViewOperationCode (uint8_t Code)
Variables
const LVSmall LVLocationMemberOffset = 0
const LVAddress MaxAddress = std::numeric_limits<uint64_t>::max()
constexpr LVSectionIndex UndefinedSectionIndex = 0
const int HEX_WIDTH = 12
constexpr bool UpdateHighAddress = false
Typedef Documentation
ArgVector
using llvm::logicalview::ArgVector = typedef std::vector<std::string>
Definition at line 31 of file LVReaderHandler.h.
AttributeSpec
using llvm::logicalview::AttributeSpec = typedef DWARFAbbreviationDeclaration::AttributeSpec
Definition at line 31 of file LVELFReader.h.
LVAddress
using llvm::logicalview::LVAddress = typedef uint64_t
Definition at line 37 of file LVObject.h.
LVAddressRange
using llvm::logicalview::LVAddressRange = typedef std::pair<LVAddress, LVAddress>
Definition at line 23 of file LVRange.h.
LVAttributeKindSet
using llvm::logicalview::LVAttributeKindSet = typedef std::set<LVAttributeKind>
Definition at line 131 of file LVOptions.h.
LVCompareKindSet
using llvm::logicalview::LVCompareKindSet = typedef std::set<LVCompareKind>
Definition at line 140 of file LVOptions.h.
LVElementDispatch
using llvm::logicalview::LVElementDispatch = typedef std::map<LVElementKind, LVElementGetFunction>
Definition at line 64 of file LVElement.h.
LVElementGetFunction
using llvm::logicalview::LVElementGetFunction = typedef bool (LVElement::*)() const
Definition at line 65 of file LVObject.h.
LVElementKindSet
using llvm::logicalview::LVElementKindSet = typedef std::set<LVElementKind>
Definition at line 63 of file LVElement.h.
LVElementRequest
using llvm::logicalview::LVElementRequest = typedef std::vector<LVElementGetFunction>
Definition at line 65 of file LVElement.h.
LVElements
using llvm::logicalview::LVElements = typedef SmallVector<LVElement *, 8>
Definition at line 77 of file LVObject.h.
LVElementSetFunction
using llvm::logicalview::LVElementSetFunction = typedef void (LVElement::*)()
Definition at line 64 of file LVObject.h.
LVHalf
using llvm::logicalview::LVHalf = typedef uint16_t
Definition at line 38 of file LVObject.h.
LVInternalKindSet
using llvm::logicalview::LVInternalKindSet = typedef std::set<LVInternalKind>
Definition at line 190 of file LVOptions.h.
LVLevel
using llvm::logicalview::LVLevel = typedef uint32_t
Definition at line 39 of file LVObject.h.
LVLineDispatch
using llvm::logicalview::LVLineDispatch = typedef std::map<LVLineKind, LVLineGetFunction>
Definition at line 36 of file LVLine.h.
LVLineGetFunction
using llvm::logicalview::LVLineGetFunction = typedef bool (LVLine::*)() const
Definition at line 67 of file LVObject.h.
LVLineKindSet
using llvm::logicalview::LVLineKindSet = typedef std::set<LVLineKind>
Definition at line 35 of file LVLine.h.
LVLineRange
using llvm::logicalview::LVLineRange = typedef std::pair<LVLine *, LVLine *>
Definition at line 22 of file LVLocation.h.
LVLineRequest
using llvm::logicalview::LVLineRequest = typedef std::vector<LVLineGetFunction>
Definition at line 37 of file LVLine.h.
LVLines
using llvm::logicalview::LVLines = typedef SmallVector<LVLine *, 8>
Definition at line 78 of file LVObject.h.
LVLineSetFunction
using llvm::logicalview::LVLineSetFunction = typedef void (LVLine::*)()
Definition at line 66 of file LVObject.h.
LVLocations
using llvm::logicalview::LVLocations = typedef SmallVector<LVLocation *, 8>
Definition at line 79 of file LVObject.h.
LVNameInfo
using llvm::logicalview::LVNameInfo = typedef std::pair<LVAddress, uint64_t>
Definition at line 29 of file LVScope.h.
LVObjectGetFunction
using llvm::logicalview::LVObjectGetFunction = typedef bool (LVObject::*)() const
Definition at line 69 of file LVObject.h.
LVObjectSetFunction
using llvm::logicalview::LVObjectSetFunction = typedef void (LVObject::*)()
Definition at line 68 of file LVObject.h.
LVOffset
using llvm::logicalview::LVOffset = typedef uint64_t
Definition at line 40 of file LVObject.h.
LVOffsetElementMap
using llvm::logicalview::LVOffsetElementMap = typedef std::map<LVOffset, LVElement *>
Definition at line 66 of file LVScope.h.
LVOffsetLinesMap
using llvm::logicalview::LVOffsetLinesMap = typedef std::map<LVOffset, LVLines>
Definition at line 67 of file LVScope.h.
LVOffsetLocationsMap
using llvm::logicalview::LVOffsetLocationsMap = typedef std::map<LVOffset, LVLocations>
Definition at line 68 of file LVScope.h.
LVOffsets
using llvm::logicalview::LVOffsets = typedef SmallVector<LVOffset, 8>
Definition at line 85 of file LVObject.h.
LVOffsetSet
using llvm::logicalview::LVOffsetSet = typedef std::set<uint64_t>
Definition at line 92 of file LVOptions.h.
LVOffsetSymbolMap
using llvm::logicalview::LVOffsetSymbolMap = typedef std::map<LVOffset, LVSymbol *>
Definition at line 69 of file LVScope.h.
LVOperations
using llvm::logicalview::LVOperations = typedef SmallVector<LVOperation *, 8>
Definition at line 80 of file LVObject.h.
LVOutputKindSet
using llvm::logicalview::LVOutputKindSet = typedef std::set<LVOutputKind>
Definition at line 148 of file LVOptions.h.
LVPassEntry
using llvm::logicalview::LVPassEntry = typedef std::tuple<LVReader *, LVElement *, LVComparePass>
Definition at line 25 of file LVCompare.h.
LVPassTable
using llvm::logicalview::LVPassTable = typedef std::vector<LVPassEntry>
Definition at line 26 of file LVCompare.h.
LVPrintKindSet
using llvm::logicalview::LVPrintKindSet = typedef std::set<LVPrintKind>
Definition at line 162 of file LVOptions.h.
LVPublicAddresses
using llvm::logicalview::LVPublicAddresses = typedef std::map<LVAddress, LVNameInfo>
Definition at line 31 of file LVScope.h.
LVPublicNames
using llvm::logicalview::LVPublicNames = typedef std::map<LVScope *, LVNameInfo>
Definition at line 30 of file LVScope.h.
LVRangeEntries
using llvm::logicalview::LVRangeEntries = typedef std::vector<LVRangeEntry>
Definition at line 47 of file LVRange.h.
LVReaders
using llvm::logicalview::LVReaders = typedef std::vector<std::unique_ptr<LVReader> >
Definition at line 30 of file LVReaderHandler.h.
LVReportKindSet
using llvm::logicalview::LVReportKindSet = typedef std::set<LVReportKind>
Definition at line 171 of file LVOptions.h.
LVScopeDispatch
using llvm::logicalview::LVScopeDispatch = typedef std::map<LVScopeKind, LVScopeGetFunction>
Definition at line 63 of file LVScope.h.
LVScopeGetFunction
using llvm::logicalview::LVScopeGetFunction = typedef bool (LVScope::*)() const
Definition at line 71 of file LVObject.h.
LVScopeKindSet
using llvm::logicalview::LVScopeKindSet = typedef std::set<LVScopeKind>
Definition at line 62 of file LVScope.h.
LVScopeRequest
using llvm::logicalview::LVScopeRequest = typedef std::vector<LVScopeGetFunction>
Definition at line 64 of file LVScope.h.
LVScopes
using llvm::logicalview::LVScopes = typedef SmallVector<LVScope *, 8>
Definition at line 81 of file LVObject.h.
LVScopeSetFunction
using llvm::logicalview::LVScopeSetFunction = typedef void (LVScope::*)()
Definition at line 70 of file LVObject.h.
LVSectionIndex
using llvm::logicalview::LVSectionIndex = typedef uint64_t
Definition at line 36 of file LVObject.h.
LVSigned
using llvm::logicalview::LVSigned = typedef int64_t
Definition at line 41 of file LVObject.h.
LVSmall
using llvm::logicalview::LVSmall = typedef uint8_t
Definition at line 43 of file LVObject.h.
LVSortFunction
using llvm::logicalview::LVSortFunction = typedef LVSortValue (*)(const LVObject *LHS, const LVObject *RHS)
Definition at line 33 of file LVSort.h.
LVSortValue
using llvm::logicalview::LVSortValue = typedef int
Definition at line 31 of file LVSort.h.
LVSymbolDispatch
using llvm::logicalview::LVSymbolDispatch = typedef std::map<LVSymbolKind, LVSymbolGetFunction>
Definition at line 33 of file LVSymbol.h.
LVSymbolGetFunction
using llvm::logicalview::LVSymbolGetFunction = typedef bool (LVSymbol::*)() const
Definition at line 73 of file LVObject.h.
LVSymbolKindSet
using llvm::logicalview::LVSymbolKindSet = typedef std::set<LVSymbolKind>
Definition at line 32 of file LVSymbol.h.
LVSymbolRequest
using llvm::logicalview::LVSymbolRequest = typedef std::vector<LVSymbolGetFunction>
Definition at line 34 of file LVSymbol.h.
LVSymbols
using llvm::logicalview::LVSymbols = typedef SmallVector<LVSymbol *, 8>
Definition at line 82 of file LVObject.h.
LVSymbolSetFunction
using llvm::logicalview::LVSymbolSetFunction = typedef void (LVSymbol::*)()
Definition at line 72 of file LVObject.h.
LVTagOffsetsMap
using llvm::logicalview::LVTagOffsetsMap = typedef std::map<dwarf::Tag, LVOffsets>
Definition at line 70 of file LVScope.h.
LVTypeDispatch
using llvm::logicalview::LVTypeDispatch = typedef std::map<LVTypeKind, LVTypeGetFunction>
Definition at line 47 of file LVType.h.
LVTypeGetFunction
using llvm::logicalview::LVTypeGetFunction = typedef bool (LVType::*)() const
Definition at line 75 of file LVObject.h.
LVTypeKindSelection
using llvm::logicalview::LVTypeKindSelection = typedef std::set<LVTypeKind>
Definition at line 46 of file LVType.h.
LVTypeRequest
using llvm::logicalview::LVTypeRequest = typedef std::vector<LVTypeGetFunction>
Definition at line 48 of file LVType.h.
LVTypes
using llvm::logicalview::LVTypes = typedef SmallVector<LVType *, 8>
Definition at line 83 of file LVObject.h.
LVTypeSetFunction
using llvm::logicalview::LVTypeSetFunction = typedef void (LVType::*)()
Definition at line 74 of file LVObject.h.
LVUnsigned
using llvm::logicalview::LVUnsigned = typedef uint64_t
Definition at line 42 of file LVObject.h.
LVValidLocation
using llvm::logicalview::LVValidLocation = typedef bool (LVLocation::*)()
Definition at line 93 of file LVObject.h.
LVWarningKindSet
using llvm::logicalview::LVWarningKindSet = typedef std::set<LVWarningKind>
Definition at line 180 of file LVOptions.h.
PdbOrObj
using llvm::logicalview::PdbOrObj = typedef PointerUnion<object::ObjectFile *, pdb::PDBFile *>
Definition at line 32 of file LVReaderHandler.h.
Enumeration Type Documentation
LVAttributeKind
enum llvm::logicalview::LVAttributeKind strong
Enumerator
All
Argument
Base
Coverage
Directories
Discarded
Discriminator
Encoded
Extended
Filename
Files
Format
Gaps
Generated
Global
Inserted
Level
Linkage
Local
Location
Offset
Pathname
Producer
Publics
Qualified
Qualifier
Range
Reference
Register
Standard
Subrange
System
Typename
Underlying
Zero
Definition at line 94 of file LVOptions.h.
LVBinaryType
enum llvm::logicalview::LVBinaryType strong
Enumerator
NONE
ELF
COFF
Definition at line 89 of file LVObject.h.
LVCompareKind
enum llvm::logicalview::LVCompareKind strong
Enumerator
All
Lines
Scopes
Symbols
Types
Definition at line 133 of file LVOptions.h.
LVComparePass
enum llvm::logicalview::LVComparePass strong
Enumerator
Missing
Added
Definition at line 90 of file LVObject.h.
LVElementKind
enum llvm::logicalview::LVElementKind strong
Enumerator
Discarded
Global
Optimized
LastEntry
Definition at line 62 of file LVElement.h.
LVInternalKind
enum llvm::logicalview::LVInternalKind strong
Enumerator
All
Cmdline
ID
Integrity
None
Tag
Definition at line 182 of file LVOptions.h.
LVLineKind
enum llvm::logicalview::LVLineKind strong
Enumerator
IsBasicBlock
IsDiscriminator
IsEndSequence
IsEpilogueBegin
IsLineDebug
IsLineAssembler
IsNewStatement
IsPrologueEnd
IsAlwaysStepInto
IsNeverStepInto
LastEntry
Definition at line 22 of file LVLine.h.
LVOutputKind
enum llvm::logicalview::LVOutputKind strong
Enumerator
All
Split
Json
Text
Definition at line 142 of file LVOptions.h.
LVPrintKind
enum llvm::logicalview::LVPrintKind strong
Enumerator
All
Elements
Instructions
Lines
Scopes
Sizes
Symbols
Summary
Types
Warnings
Definition at line 150 of file LVOptions.h.
LVReportKind
enum llvm::logicalview::LVReportKind strong
Enumerator
All
Children
List
Parents
View
Definition at line 164 of file LVOptions.h.
LVScopeKind
enum llvm::logicalview::LVScopeKind strong
Enumerator
IsAggregate
IsArray
IsBlock
IsCallSite
IsCatchBlock
IsClass
IsCompileUnit
IsEntryPoint
IsEnumeration
IsFunction
IsFunctionType
IsInlinedFunction
IsLabel
IsLexicalBlock
IsMember
IsNamespace
IsRoot
IsStructure
IsSubprogram
IsTemplate
IsTemplateAlias
IsTemplatePack
IsTryBlock
IsUnion
LastEntry
Definition at line 35 of file LVScope.h.
LVSortMode
enum llvm::logicalview::LVSortMode strong
Enumerator
None
Kind
Line
Name
Offset
Definition at line 22 of file LVSort.h.
LVSubclassID
enum llvm::logicalview::LVSubclassID : unsigned char strong
Enumerator
LV_ELEMENT
LV_LINE_FIRST
LV_LINE
LV_LINE_DEBUG
LV_LINE_ASSEMBLER
LV_LINE_LAST
lV_SCOPE_FIRST
LV_SCOPE
LV_SCOPE_AGGREGATE
LV_SCOPE_ALIAS
LV_SCOPE_ARRAY
LV_SCOPE_COMPILE_UNIT
LV_SCOPE_ENUMERATION
LV_SCOPE_FORMAL_PACK
LV_SCOPE_FUNCTION
LV_SCOPE_FUNCTION_INLINED
LV_SCOPE_FUNCTION_TYPE
LV_SCOPE_NAMESPACE
LV_SCOPE_ROOT
LV_SCOPE_TEMPLATE_PACK
LV_SCOPE_LAST
LV_SYMBOL_FIRST
LV_SYMBOL
LV_SYMBOL_LAST
LV_TYPE_FIRST
LV_TYPE
LV_TYPE_DEFINITION
LV_TYPE_ENUMERATOR
LV_TYPE_IMPORT
LV_TYPE_PARAM
LV_TYPE_SUBRANGE
LV_TYPE_LAST
Definition at line 27 of file LVElement.h.
LVSymbolKind
enum llvm::logicalview::LVSymbolKind strong
Enumerator
IsCallSiteParameter
IsConstant
IsInheritance
IsMember
IsParameter
IsUnspecified
IsVariable
LastEntry
Definition at line 22 of file LVSymbol.h.
LVTypeKind
enum llvm::logicalview::LVTypeKind strong
Enumerator
IsBase
IsConst
IsEnumerator
IsImport
IsImportDeclaration
IsImportModule
IsPointer
IsPointerMember
IsReference
IsRestrict
IsRvalueReference
IsSubrange
IsTemplateParam
IsTemplateTemplateParam
IsTemplateTypeParam
IsTemplateValueParam
IsTypedef
IsUnaligned
IsUnspecified
IsVolatile
IsModifier
LastEntry
Definition at line 22 of file LVType.h.
LVWarningKind
enum llvm::logicalview::LVWarningKind strong
Enumerator
All
Coverages
Lines
Locations
Ranges
Definition at line 173 of file LVOptions.h.
Function Documentation
addItem()
template<typename MapType , typename KeyType , typename ValueType > void llvm::logicalview::addItem (MapType * Map, KeyType Key, ValueType Value)
Definition at line 133 of file LVSupport.h.
compareKind()
LVSortValue llvm::logicalview::compareKind (const LVObject * LHS, const LVObject * RHS)
Definition at line 27 of file LVSort.cpp.
References LHS, and RHS.
compareLine()
LVSortValue llvm::logicalview::compareLine (const LVObject * LHS, const LVObject * RHS)
Definition at line 33 of file LVSort.cpp.
References LHS, and RHS.
compareName()
LVSortValue llvm::logicalview::compareName (const LVObject * LHS, const LVObject * RHS)
Definition at line 39 of file LVSort.cpp.
References llvm::Value::getName(), LHS, and RHS.
compareOffset()
LVSortValue llvm::logicalview::compareOffset (const LVObject * LHS, const LVObject * RHS)
Definition at line 45 of file LVSort.cpp.
References LHS, and RHS.
Referenced by getSortFunction().
compareRange()
LVSortValue llvm::logicalview::compareRange (const LVObject * LHS, const LVObject * RHS)
Definition at line 51 of file LVSort.cpp.
References LHS, and RHS.
Referenced by llvm::logicalview::LVScope::sort().
emptyString()
StringRef llvm::logicalview::emptyString ()
Definition at line 32 of file LVObject.cpp.
Referenced by llvm::logicalview::LVElement::resolveFullname().
flattenedFilePath()
std::string llvm::logicalview::flattenedFilePath (StringRef Path)
Definition at line 50 of file LVSupport.cpp.
References transform.
Referenced by llvm::logicalview::LVSplitContext::open().
formatAttributes()
template<typename... Args> std::string llvm::logicalview::formatAttributes (const StringRef First, Args... Others)
Definition at line 119 of file LVSupport.h.
References First, and List.
Referenced by llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVTypeImport::printExtra(), and llvm::logicalview::LVScopeFunction::printExtra().
formattedKind()
std::string llvm::logicalview::formattedKind (StringRef Kind) inline
Definition at line 212 of file LVSupport.h.
Referenced by llvm::logicalview::LVElement::equals(), llvm::logicalview::LVLine::markMissingParents(), llvm::logicalview::LVType::markMissingParents(), llvm::logicalview::LVSymbol::markMissingParents(), llvm::logicalview::LVScope::markMissingParents(), llvm::logicalview::LVRange::print(), llvm::logicalview::LVLineDebug::printExtra(), llvm::logicalview::LVType::printExtra(), llvm::logicalview::LVLineAssembler::printExtra(), llvm::logicalview::LVTypeDefinition::printExtra(), llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVTypeEnumerator::printExtra(), llvm::logicalview::LVTypeImport::printExtra(), llvm::logicalview::LVTypeParam::printExtra(), llvm::logicalview::LVTypeSubrange::printExtra(), llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeArray::printExtra(), llvm::logicalview::LVScopeCompileUnit::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), llvm::logicalview::LVScopeFormalPack::printExtra(), llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVScopeNamespace::printExtra(), llvm::logicalview::LVScopeRoot::printExtra(), llvm::logicalview::LVScopeTemplatePack::printExtra(), llvm::logicalview::LVScopeCompileUnit::printLocalNames(), and llvm::logicalview::LVScopeCompileUnit::printWarnings().
formattedName()
std::string llvm::logicalview::formattedName (StringRef Name) inline
Definition at line 216 of file LVSupport.h.
Referenced by llvm::logicalview::LVElement::equals(), llvm::logicalview::LVCompare::execute(), llvm::logicalview::LVType::markMissingParents(), llvm::logicalview::LVSymbol::markMissingParents(), llvm::logicalview::LVScope::markMissingParents(), llvm::logicalview::LVRange::print(), llvm::logicalview::LVObject::printAttributes(), llvm::logicalview::LVLineDebug::printExtra(), llvm::logicalview::LVType::printExtra(), llvm::logicalview::LVLineAssembler::printExtra(), llvm::logicalview::LVTypeDefinition::printExtra(), llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVTypeEnumerator::printExtra(), llvm::logicalview::LVTypeImport::printExtra(), llvm::logicalview::LVTypeParam::printExtra(), llvm::logicalview::LVTypeSubrange::printExtra(), llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeArray::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), llvm::logicalview::LVScopeFormalPack::printExtra(), llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVScopeNamespace::printExtra(), llvm::logicalview::LVScopeRoot::printExtra(), llvm::logicalview::LVScopeTemplatePack::printExtra(), llvm::logicalview::LVElement::printFileIndex(), llvm::logicalview::LVScopeCompileUnit::printLocalNames(), and llvm::logicalview::LVScopeCompileUnit::printWarnings().
formattedNames()
std::string llvm::logicalview::formattedNames (StringRef Name1, StringRef Name2) inline
Definition at line 220 of file LVSupport.h.
Referenced by llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVTypeParam::printExtra(), llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), and llvm::logicalview::LVScopeFunction::printExtra().
getCodeViewOperationCode()
uint16_t llvm::logicalview::getCodeViewOperationCode (uint8_t Code) inline
Definition at line 237 of file LVSupport.h.
Referenced by llvm::logicalview::LVOperation::getOperandsCodeViewInfo().
getComparator()
LVCompare& llvm::logicalview::getComparator () inline
Definition at line 84 of file LVCompare.h.
References llvm::logicalview::LVCompare::getInstance().
Referenced by llvm::logicalview::LVLine::report(), llvm::logicalview::LVType::report(), llvm::logicalview::LVSymbol::report(), and llvm::logicalview::LVScope::report().
getReader()
LVReader& llvm::logicalview::getReader () inline
Definition at line 328 of file LVReader.h.
References llvm::logicalview::LVReader::getInstance().
Referenced by llvm::logicalview::LVScopeCompileUnit::addedElement(), llvm::logicalview::LVSymbol::addLocation(), llvm::logicalview::LVScope::addMissingElements(), llvm::logicalview::LVLocationSymbol::addObject(), llvm::logicalview::LVScope::addObject(), llvm::logicalview::LVScope::doPrint(), llvm::logicalview::LVScopeRoot::doPrintMatches(), llvm::logicalview::LVSymbolTable::getIndex(), llvm::logicalview::LVOperation::getOperandsCodeViewInfo(), llvm::logicalview::LVOperation::getOperandsDWARFInfo(), getReaderCompileUnit(), getReaderSplitContext(), llvm::logicalview::LVLine::print(), llvm::logicalview::LVType::print(), llvm::logicalview::LVLocation::print(), llvm::logicalview::LVSymbol::print(), llvm::logicalview::LVScope::print(), llvm::logicalview::LVScopeCompileUnit::print(), llvm::logicalview::LVElement::printLinkageName(), llvm::logicalview::LVScopeCompileUnit::printSizes(), llvm::logicalview::LVScopeRoot::processRangeInformation(), llvm::logicalview::LVScope::resolveElements(), llvm::logicalview::LVElement::setFile(), llvm::logicalview::LVScopeFunction::setName(), and llvm::logicalview::LVSymbolTable::update().
getReaderCompileUnit()
LVScopeCompileUnit* llvm::logicalview::getReaderCompileUnit () inline
Definition at line 332 of file LVReader.h.
References llvm::logicalview::LVReader::getCompileUnit(), and getReader().
Referenced by llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVSymbol::calculateCoverage(), llvm::logicalview::LVLine::print(), llvm::logicalview::LVType::print(), llvm::logicalview::LVSymbol::print(), llvm::logicalview::LVScope::print(), and llvm::logicalview::LVLocation::validateRanges().
getReaderSplitContext()
LVSplitContext& llvm::logicalview::getReaderSplitContext () inline
Definition at line 329 of file LVReader.h.
References getReader(), and llvm::logicalview::LVReader::getSplitContext().
Referenced by llvm::logicalview::LVScope::doPrint(), and llvm::logicalview::LVScopeRoot::doPrintMatches().
getSortFunction()
LVSortFunction llvm::logicalview::getSortFunction ()
Definition at line 100 of file LVSort.cpp.
References compareOffset(), Kind, Line, Name, None, Offset, options(), sortByKind(), sortByLine(), and sortByName().
Referenced by llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), and llvm::logicalview::LVScope::sort().
getStringPool()
LVStringPool & llvm::logicalview::getStringPool ()
Definition at line 27 of file LVSupport.cpp.
Referenced by llvm::logicalview::LVScopeCompileUnit::addFilename(), llvm::logicalview::LVScopeCompileUnit::getCompilationDirectory(), llvm::logicalview::LVScopeAggregate::getEncodedArgs(), llvm::logicalview::LVScopeFunction::getEncodedArgs(), llvm::logicalview::LVScopeRoot::getFileFormatName(), llvm::logicalview::LVScopeCompileUnit::getFilename(), llvm::logicalview::LVSymbol::getLinkageName(), llvm::logicalview::LVScopeFunction::getLinkageName(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVElement::getPathname(), llvm::logicalview::LVScopeCompileUnit::getProducer(), llvm::logicalview::LVElement::getQualifiedName(), getStringIndex(), llvm::logicalview::LVSymbol::getValue(), llvm::logicalview::LVTypeEnumerator::getValue(), llvm::logicalview::LVTypeParam::getValue(), llvm::logicalview::LVScopeCompileUnit::printLocalNames(), llvm::logicalview::LVScopeCompileUnit::setCompilationDirectory(), llvm::logicalview::LVScopeAggregate::setEncodedArgs(), llvm::logicalview::LVScopeFunction::setEncodedArgs(), llvm::logicalview::LVScopeRoot::setFileFormatName(), llvm::logicalview::LVSymbol::setLinkageName(), llvm::logicalview::LVScopeFunction::setLinkageName(), llvm::logicalview::LVElement::setName(), llvm::logicalview::LVScopeCompileUnit::setProducer(), llvm::logicalview::LVElement::setQualifiedName(), llvm::logicalview::LVSymbol::setValue(), llvm::logicalview::LVTypeEnumerator::setValue(), and llvm::logicalview::LVTypeParam::setValue().
hexSquareString()
std::string llvm::logicalview::hexSquareString (uint64_t Value) inline
Definition at line 113 of file LVSupport.h.
References hexString().
Referenced by llvm::logicalview::LVScope::addMissingElements(), llvm::logicalview::LVElement::equals(), llvm::logicalview::LVScope::markMissingParents(), llvm::logicalview::LVObject::printAttributes(), llvm::logicalview::LVScopeCompileUnit::printWarnings(), and llvm::logicalview::LVElement::typeOffsetAsString().
hexString()
std::string llvm::logicalview::hexString (uint64_t Value, size_t Width = HEX_WIDTH) inline
Definition at line 105 of file LVSupport.h.
References hexValue(), and llvm::raw_string_ostream::str().
Referenced by llvm::logicalview::LVLocation::getIntervalInfo(), llvm::logicalview::LVOperation::getOperandsCodeViewInfo(), llvm::logicalview::LVOperation::getOperandsDWARFInfo(), hexSquareString(), llvm::logicalview::LVLocation::printRaw(), and llvm::logicalview::LVScopeCompileUnit::printWarnings().
hexValue()
FormattedNumber llvm::logicalview::hexValue (uint64_t N, unsigned Width = HEX_WIDTH, bool Upper = false) inline
Definition at line 99 of file LVSupport.h.
References llvm::format_hex(), N, and llvm::Upper.
Referenced by llvm::logicalview::LVBinaryReader::createInstructions(), hexString(), llvm::logicalview::LVBinaryReader::processLines(), and llvm::logicalview::LVRange::startSearch().
options()
LVOptions& llvm::logicalview::options () inline
Definition at line 445 of file LVOptions.h.
References llvm::logicalview::LVOptions::getOptions().
Referenced by llvm::logicalview::LVPatterns::addGenericPatterns(), llvm::logicalview::LVPatterns::addPatterns(), llvm::logicalview::LVSymbol::calculateCoverage(), llvm::logicalview::LVLocation::calculateCoverage(), llvm::logicalview::LVPatterns::clear(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVReader::createScopes(), llvm::logicalview::LVElement::discriminatorAsString(), llvm::logicalview::LVReader::doLoad(), llvm::logicalview::LVScope::doPrint(), llvm::logicalview::LVReader::doPrint(), llvm::logicalview::LVScopeRoot::doPrintMatches(), llvm::logicalview::LVScope::equalNumberOfChildren(), llvm::logicalview::LVElement::equals(), llvm::logicalview::LVScopeFunction::equals(), llvm::logicalview::LVCompare::execute(), llvm::logicalview::LVLocation::getIntervalInfo(), llvm::logicalview::LVType::getParameters(), getSortFunction(), getStringIndex(), llvm::logicalview::LVScopeCompileUnit::incrementPrintedLines(), llvm::logicalview::LVScopeCompileUnit::incrementPrintedScopes(), llvm::logicalview::LVScopeCompileUnit::incrementPrintedSymbols(), llvm::logicalview::LVScopeCompileUnit::incrementPrintedTypes(), llvm::logicalview::LVObject::indentAsString(), llvm::logicalview::LVObject::lineAsString(), llvm::logicalview::LVCompare::LVCompare(), llvm::logicalview::LVTypeParam::LVTypeParam(), llvm::logicalview::LVLine::noLineAsString(), llvm::logicalview::LVReader::notifyAddedElement(), llvm::logicalview::LVRange::print(), llvm::logicalview::LVLocation::print(), llvm::logicalview::LVScope::print(), llvm::logicalview::LVScopeCompileUnit::print(), llvm::logicalview::LVScope::printActiveRanges(), llvm::logicalview::LVObject::printAttributes(), llvm::logicalview::LVPatterns::printElement(), llvm::logicalview::LVScope::printEncodedArgs(), llvm::logicalview::LVLineDebug::printExtra(), llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVScopeCompileUnit::printExtra(), llvm::logicalview::LVScopeRoot::printExtra(), llvm::logicalview::LVElement::printFileIndex(), llvm::logicalview::LVCompare::printItem(), llvm::logicalview::LVElement::printLinkageName(), llvm::logicalview::LVScopeCompileUnit::printLocalNames(), llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), llvm::logicalview::LVPatterns::printObject(), llvm::logicalview::LVElement::printReference(), llvm::logicalview::LVReader::printScopes(), llvm::logicalview::LVScopeCompileUnit::printSizes(), llvm::logicalview::LVScopeCompileUnit::printSummary(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVScopeRoot::processRangeInformation(), llvm::logicalview::LVScopeCompileUnit::processRangeLocationCoverage(), llvm::logicalview::LVScopeCompileUnit::propagatePatternMatch(), llvm::logicalview::LVTypeDefinition::resolveExtra(), llvm::logicalview::LVType::resolveName(), llvm::logicalview::LVElement::resolveName(), llvm::logicalview::LVScopeFunction::resolveReferences(), llvm::logicalview::LVScope::resolveTemplate(), llvm::logicalview::LVElement::setFile(), llvm::logicalview::LVElement::setGenericType(), llvm::logicalview::LVScope::traverseParentsAndChildren(), llvm::logicalview::LVElement::typeOffsetAsString(), and llvm::logicalview::LVPatterns::updateReportOptions().
patterns()
LVPatterns& llvm::logicalview::patterns () inline
Definition at line 640 of file LVOptions.h.
References llvm::logicalview::LVPatterns::getPatterns().
Referenced by llvm::logicalview::LVReader::doLoad(), llvm::logicalview::LVReader::doPrintLine(), llvm::logicalview::LVReader::doPrintLocation(), llvm::logicalview::LVReader::doPrintScope(), llvm::logicalview::LVReader::doPrintSymbol(), llvm::logicalview::LVReader::doPrintType(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVType::resolveName(), llvm::logicalview::LVSymbol::resolveName(), and llvm::logicalview::LVScope::resolveName().
setOptions()
void llvm::logicalview::setOptions (LVOptions * Options) inline
Definition at line 446 of file LVOptions.h.
References Options, and llvm::logicalview::LVOptions::setOptions().
Referenced by llvm::logicalview::LVReaderHandler::LVReaderHandler().
sortByKind()
LVSortValue llvm::logicalview::sortByKind (const LVObject * LHS, const LVObject * RHS)
Definition at line 65 of file LVSort.cpp.
References llvm::Value::getName(), llvm::Left, LHS, RHS, and Right.
Referenced by getSortFunction().
sortByLine()
LVSortValue llvm::logicalview::sortByLine (const LVObject * LHS, const LVObject * RHS)
Definition at line 77 of file LVSort.cpp.
References llvm::Value::getName(), llvm::Left, LHS, RHS, and Right.
Referenced by getSortFunction().
sortByName()
LVSortValue llvm::logicalview::sortByName (const LVObject * LHS, const LVObject * RHS)
Definition at line 89 of file LVSort.cpp.
References llvm::Value::getName(), llvm::Left, LHS, RHS, and Right.
Referenced by getSortFunction().
transformPath()
std::string llvm::logicalview::transformPath (StringRef Path)
Definition at line 33 of file LVSupport.cpp.
References replace(), and transform.
Referenced by getStringIndex().
typeInt()
StringRef llvm::logicalview::typeInt ()
Definition at line 30 of file LVObject.cpp.
typeNone()
StringRef llvm::logicalview::typeNone ()
Definition at line 28 of file LVObject.cpp.
typeUnknown()
StringRef llvm::logicalview::typeUnknown ()
Definition at line 31 of file LVObject.cpp.
typeVoid()
StringRef llvm::logicalview::typeVoid ()
Definition at line 29 of file LVObject.cpp.
Referenced by llvm::logicalview::LVElement::resolveFullname(), and llvm::logicalview::LVElement::typeAsString().
Variable Documentation
HEX_WIDTH
const int llvm::logicalview::HEX_WIDTH = 12
Definition at line 98 of file LVSupport.h.
LVLocationMemberOffset
const LVSmall llvm::logicalview::LVLocationMemberOffset = 0
Definition at line 25 of file LVLocation.h.
Referenced by llvm::logicalview::LVSymbol::addLocationConstant(), and llvm::logicalview::LVOperation::getOperandsDWARFInfo().
MaxAddress
const LVAddress llvm::logicalview::MaxAddress = std::numeric_limits<uint64_t>::max()
Definition at line 87 of file LVObject.h.
Referenced by llvm::logicalview::LVRange::clear().
UndefinedSectionIndex
constexpr LVSectionIndex llvm::logicalview::UndefinedSectionIndex = 0 constexpr
Definition at line 28 of file LVReader.h.
Referenced by llvm::logicalview::LVSymbolTable::update().
UpdateHighAddress
constexpr bool llvm::logicalview::UpdateHighAddress = false constexpr
Definition at line 32 of file LVBinaryReader.h.