LLVM: lib/DebugInfo/PDB/Native/NativeInlineSiteSymbol.cpp File Reference
NativeInlineSiteSymbol.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/NativeInlineSiteSymbol.h"
#include "llvm/DebugInfo/CodeView/DebugInlineeLinesSubsection.h"
#include "llvm/DebugInfo/CodeView/LazyRandomTypeCollection.h"
#include "llvm/DebugInfo/CodeView/SymbolRecord.h"
#include "llvm/DebugInfo/CodeView/TypeDeserializer.h"
#include "llvm/DebugInfo/PDB/Native/ModuleDebugStream.h"
#include "llvm/DebugInfo/PDB/Native/NativeEnumLineNumbers.h"
#include "llvm/DebugInfo/PDB/Native/NativeLineNumber.h"
#include "llvm/DebugInfo/PDB/Native/NativeSession.h"
#include "llvm/DebugInfo/PDB/Native/PDBFile.h"
#include "llvm/DebugInfo/PDB/Native/SymbolCache.h"
#include "llvm/DebugInfo/PDB/Native/TpiStream.h"
#include "llvm/DebugInfo/PDB/PDBExtras.h"
Functions
static std::optional< InlineeSourceLine > findInlineeByTypeIndex (TypeIndex Id, ModuleDebugStreamRef &ModS)
Function Documentation
findInlineeByTypeIndex()
static std::optional<InlineeSourceLine> findInlineeByTypeIndex (TypeIndex Id, ModuleDebugStreamRef & ModS) static
Definition at line 44 of file NativeInlineSiteSymbol.cpp.
References llvm::consumeError(), llvm::codeview::EC, llvm::pdb::ModuleDebugStreamRef::getSubsectionsArray(), llvm::codeview::InlineeLines, move, and llvm::X86AS::SS.
Referenced by llvm::pdb::NativeInlineSiteSymbol::findInlineeLinesByVA().