LLVM: lib/DebugInfo/PDB/Native/NativeSession.cpp File Reference
NativeSession.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/NativeSession.h"
#include "llvm/BinaryFormat/Magic.h"
#include "llvm/DebugInfo/MSF/MSFCommon.h"
#include "llvm/DebugInfo/MSF/MappedBlockStream.h"
#include "llvm/DebugInfo/PDB/IPDBEnumChildren.h"
#include "llvm/DebugInfo/PDB/IPDBSourceFile.h"
#include "llvm/DebugInfo/PDB/Native/DbiModuleDescriptor.h"
#include "llvm/DebugInfo/PDB/Native/DbiModuleList.h"
#include "llvm/DebugInfo/PDB/Native/DbiStream.h"
#include "llvm/DebugInfo/PDB/Native/ISectionContribVisitor.h"
#include "llvm/DebugInfo/PDB/Native/ModuleDebugStream.h"
#include "llvm/DebugInfo/PDB/Native/NativeEnumInjectedSources.h"
#include "llvm/DebugInfo/PDB/Native/NativeExeSymbol.h"
#include "llvm/DebugInfo/PDB/Native/PDBFile.h"
#include "llvm/DebugInfo/PDB/Native/RawConstants.h"
#include "llvm/DebugInfo/PDB/Native/RawError.h"
#include "llvm/DebugInfo/PDB/Native/RawTypes.h"
#include "llvm/DebugInfo/PDB/Native/SymbolCache.h"
#include "llvm/DebugInfo/PDB/PDBSymbol.h"
#include "llvm/DebugInfo/PDB/PDBSymbolCompiland.h"
#include "llvm/DebugInfo/PDB/PDBSymbolExe.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/COFF.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/BinaryByteStream.h"
#include "llvm/Support/BinaryStreamArray.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include <algorithm>
#include <cassert>
#include <memory>
#include <utility>
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
llvm::codeview
Functions
static DbiStream * getDbiStreamPtr (PDBFile &File)
static Expected< std::unique_ptr< PDBFile > > loadPdbFile (StringRef PdbPath, std::unique_ptr< BumpPtrAllocator > &Allocator)
static Expected< std::string > getPdbPathFromExe (StringRef ExePath)
Function Documentation
getDbiStreamPtr()
static DbiStream* getDbiStreamPtr (PDBFile & File) static
Definition at line 56 of file NativeSession.cpp.
References llvm::consumeError(), llvm::ARMBuildAttrs::File, llvm::Expected< T >::get(), and llvm::Expected< T >::takeError().
Referenced by llvm::pdb::NativeSession::getModuleDebugStream(), and llvm::pdb::NativeSession::getRVAFromSectOffset().
getPdbPathFromExe()
static Expected<std::string> getPdbPathFromExe (StringRef ExePath) static
Definition at line 131 of file NativeSession.cpp.
References llvm::object::createBinary(), E, llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::pdb::invalid_format, move, and llvm::Expected< T >::takeError().
Referenced by llvm::pdb::NativeSession::createFromExe(), and llvm::pdb::NativeSession::searchForPdb().
loadPdbFile()
static Expected<std::unique_ptr<PDBFile> > loadPdbFile (StringRef PdbPath, std::unique_ptr< BumpPtrAllocator > & Allocator) static
Definition at line 92 of file NativeSession.cpp.
References Allocator, llvm::ARMBuildAttrs::File, llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), llvm::identify_magic(), llvm::support::little, llvm::msf::Magic, move, and llvm::file_magic::pdb.
Referenced by llvm::pdb::NativeSession::createFromExe(), llvm::pdb::NativeSession::createFromPdbPath(), and llvm::pdb::NativeSession::searchForPdb().