LLVM: lib/Target/NVPTX/NVPTXLowerArgs.cpp File Reference
NVPTXLowerArgs.cpp File Reference
#include "MCTargetDesc/NVPTXBaseInfo.h"
#include "NVPTX.h"
#include "NVPTXTargetMachine.h"
#include "NVPTXUtilities.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include <numeric>
#include <queue>
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "nvptx-lower-args"
Functions
void llvm::initializeNVPTXLowerArgsPass (PassRegistry &)
INITIALIZE_PASS_BEGIN (NVPTXLowerArgs, "nvptx-lower-args", "Lower arguments (NVPTX)", false, false) INITIALIZE_PASS_END(NVPTXLowerArgs
nvptx lower Lower arguments (NVPTX)"
nvptx lower Lower static false void convertToParamAS (Value *OldUser, Value *Param)
static void adjustByValArgAlignment (Argument *Arg, Value *ArgInParamAS, const NVPTXTargetLowering *TLI)
Variables
nvptx lower args
nvptx lower Lower false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvptx-lower-args"
Definition at line 106 of file NVPTXLowerArgs.cpp.
Function Documentation
adjustByValArgAlignment()
static void adjustByValArgAlignment (Argument * Arg, Value * ArgInParamAS, const NVPTXTargetLowering * TLI) static
Definition at line 239 of file NVPTXLowerArgs.cpp.
References llvm::ADDRESS_SPACE_PARAM, Arg, assert(), llvm::dbgs(), DL, gcd(), llvm::Attribute::get(), llvm::NVPTXTargetLowering::getFunctionParamOptimizedAlign(), llvm::APInt::getLimitedValue(), llvm::APInt::getZero(), I, LLVM_DEBUG, llvm_unreachable, llvm::SPII::Load, llvm::max(), llvm::Offset, uint64_t, and llvm::Align::value().
arguments()
nvptx lower Lower arguments (NVPTX)
convertToParamAS()
nvptx lower Lower static false void convertToParamAS (Value * OldUser, Value * Param) static
Definition at line 169 of file NVPTXLowerArgs.cpp.
References llvm::ADDRESS_SPACE_PARAM, assert(), llvm::CastInst::Create(), llvm::GetElementPtrInst::Create(), GEP, llvm::PointerType::getWithSamePointeeType(), I, llvm_unreachable, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::reverse().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (NVPTXLowerArgs , "nvptx-lower-args" , "Lower arguments (NVPTX)" , false , false)
Variable Documentation
args
nvptx lower args
Definition at line 146 of file NVPTXLowerArgs.cpp.
Referenced by llvm::LegalityPredicates::all(), llvm::detail::all_of_zip_predicate_first(), llvm::LegalityPredicates::any(), llvm::hashing::detail::hash_combine_recursive_helper::combine(), llvm::DisplayGraph(), ExecGraphViewer(), formatInternal(), llvm::DagInit::get(), getOrCreateCachedOptional(), llvm::hash_combine(), lle_X_scanf(), lle_X_sscanf(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::make(), llvm::ARMTargetLowering::makeDMB(), shuffles::mask(), llvm::thread::thread(), UpgradeIntrinsicFunction1(), writeWholeProgramDevirtResolutionByArg(), llvm::zip(), llvm::zip_equal(), llvm::zip_first(), and llvm::zip_longest().
false
nvptx lower Lower false
Definition at line 147 of file NVPTXLowerArgs.cpp.