LLVM: lib/Target/NVPTX/NVPTXPrologEpilogPass.cpp File Reference
NVPTXPrologEpilogPass.cpp File Reference
#include "NVPTX.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "nvptx-prolog-epilog"
Functions
static void AdjustStackOffset (MachineFrameInfo &MFI, int FrameIdx, bool StackGrowsDown, int64_t &Offset, Align &MaxAlign)
AdjustStackOffset - Helper function used to adjust the stack frame offset.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvptx-prolog-epilog"
Definition at line 29 of file NVPTXPrologEpilogPass.cpp.
Function Documentation
AdjustStackOffset()
static void AdjustStackOffset (MachineFrameInfo & MFI, int FrameIdx, bool StackGrowsDown, int64_t & Offset, Align & MaxAlign) inline static
AdjustStackOffset - Helper function used to adjust the stack frame offset.
Definition at line 111 of file NVPTXPrologEpilogPass.cpp.
References llvm::alignTo(), llvm::dbgs(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), LLVM_DEBUG, llvm::max(), llvm::Offset, and llvm::MachineFrameInfo::setObjectOffset().