LLVM: lib/Target/NVPTX/NVPTXAsmPrinter.cpp File Reference
NVPTXAsmPrinter.cpp File Reference
#include "NVPTXAsmPrinter.h"
#include "MCTargetDesc/NVPTXBaseInfo.h"
#include "MCTargetDesc/NVPTXInstPrinter.h"
#include "MCTargetDesc/NVPTXMCAsmInfo.h"
#include "MCTargetDesc/NVPTXTargetStreamer.h"
#include "NVPTX.h"
#include "NVPTXMCExpr.h"
#include "NVPTXMachineFunctionInfo.h"
#include "NVPTXRegisterInfo.h"
#include "NVPTXSubtarget.h"
#include "NVPTXTargetMachine.h"
#include "NVPTXUtilities.h"
#include "TargetInfo/NVPTXTargetInfo.h"
#include "cl_common_defines.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/NativeFormatting.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Transforms/Utils/UnrollLoop.h"
#include <cassert>
#include <cstdint>
#include <cstring>
#include <new>
#include <string>
#include <utility>
#include <vector>
Macros
#define DEPOTNAME "__local_depot"
Functions
static void DiscoverDependentGlobals (const Value *V, DenseSet< const GlobalVariable * > &Globals)
DiscoverDependentGlobals - Return a set of GlobalVariables on which V depends.
static void VisitGlobalVariableForEmission (const GlobalVariable *GV, SmallVectorImpl< const GlobalVariable * > &Order, DenseSet< const GlobalVariable * > &Visited, DenseSet< const GlobalVariable * > &Visiting)
VisitGlobalVariableForEmission - Add GV to the list of GlobalVariable instances to be emitted, but only after any dependents have been added first.s.
static bool usedInGlobalVarDef (const Constant *C)
static bool usedInOneFunc (const User *U, Function const *&oneFunc)
static bool canDemoteGlobalVar (const GlobalVariable *gv, Function const *&f)
static bool useFuncSeen (const Constant *C, DenseMap< const Function *, bool > &seenMap)
static bool isEmptyXXStructor (GlobalVariable *GV)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeNVPTXAsmPrinter ()
Macro Definition Documentation
DEPOTNAME
#define DEPOTNAME "__local_depot"
Definition at line 95 of file NVPTXAsmPrinter.cpp.
Function Documentation
canDemoteGlobalVar()
static bool canDemoteGlobalVar (const GlobalVariable * gv, Function const *& f) static
Definition at line 672 of file NVPTXAsmPrinter.cpp.
References llvm::ADDRESS_SPACE_SHARED, f(), llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getType(), llvm::GlobalValue::hasInternalLinkage(), and usedInOneFunc().
DiscoverDependentGlobals()
static void DiscoverDependentGlobals (const Value * V, DenseSet< const GlobalVariable * > & Globals) static
DiscoverDependentGlobals - Return a set of GlobalVariables on which V depends.
Definition at line 100 of file NVPTXAsmPrinter.cpp.
References llvm::numbers::e, i, and llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert().
Referenced by VisitGlobalVariableForEmission().
isEmptyXXStructor()
static bool isEmptyXXStructor (GlobalVariable * GV) static
Definition at line 765 of file NVPTXAsmPrinter.cpp.
References llvm::GlobalVariable::getInitializer(), and llvm::User::getNumOperands().
Referenced by llvm::NVPTXAsmPrinter::doInitialization().
LLVMInitializeNVPTXAsmPrinter()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeNVPTXAsmPrinter ()
Definition at line 2225 of file NVPTXAsmPrinter.cpp.
References llvm::getTheNVPTXTarget32(), llvm::getTheNVPTXTarget64(), X, and Y.
usedInGlobalVarDef()
static bool usedInGlobalVarDef (const Constant * C) static
Definition at line 625 of file NVPTXAsmPrinter.cpp.
References llvm::Value::users().
usedInOneFunc()
static bool usedInOneFunc (const User * U, Function const *& oneFunc) static
Definition at line 641 of file NVPTXAsmPrinter.cpp.
References instr, and llvm::Value::users().
Referenced by canDemoteGlobalVar().
useFuncSeen()
static bool useFuncSeen (const Constant * C, DenseMap< const Function *, bool > & seenMap) static
Definition at line 690 of file NVPTXAsmPrinter.cpp.
References bb, caller(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), I, and llvm::Value::users().
VisitGlobalVariableForEmission()
static void VisitGlobalVariableForEmission (const GlobalVariable * GV, SmallVectorImpl< const GlobalVariable * > & Order, DenseSet< const GlobalVariable * > & Visited, DenseSet< const GlobalVariable * > & Visiting) static
VisitGlobalVariableForEmission - Add GV to the list of GlobalVariable instances to be emitted, but only after any dependents have been added first.s.
Definition at line 117 of file NVPTXAsmPrinter.cpp.
References llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::count(), DiscoverDependentGlobals(), llvm::numbers::e, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::erase(), llvm::User::getNumOperands(), llvm::User::getOperand(), i, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), and llvm::report_fatal_error().