LLVM: lib/Target/NVPTX/MCTargetDesc/NVPTXMCTargetDesc.cpp File Reference
NVPTXMCTargetDesc.cpp File Reference
#include "NVPTXMCTargetDesc.h"
#include "NVPTXInstPrinter.h"
#include "NVPTXMCAsmInfo.h"
#include "NVPTXTargetStreamer.h"
#include "TargetInfo/NVPTXTargetInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "NVPTXGenInstrInfo.inc"
#include "NVPTXGenSubtargetInfo.inc"
#include "NVPTXGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createNVPTXMCInstrInfo ()
static MCRegisterInfo * createNVPTXMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createNVPTXMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCInstPrinter * createNVPTXMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &, MCInstPrinter *, bool)
static MCTargetStreamer * createNullTargetStreamer (MCStreamer &S)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeNVPTXTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 26 of file NVPTXMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 25 of file NVPTXMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 32 of file NVPTXMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 29 of file NVPTXMCTargetDesc.cpp.
Function Documentation
createNullTargetStreamer()
static MCTargetStreamer* createNullTargetStreamer (MCStreamer & S) static
Definition at line 69 of file NVPTXMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCInstPrinter()
static MCInstPrinter* createNVPTXMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 53 of file NVPTXMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCInstrInfo()
static MCInstrInfo* createNVPTXMCInstrInfo () static
Definition at line 35 of file NVPTXMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCRegisterInfo()
static MCRegisterInfo* createNVPTXMCRegisterInfo (const Triple & TT) static
Definition at line 41 of file NVPTXMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCSubtargetInfo()
static MCSubtargetInfo* createNVPTXMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 49 of file NVPTXMCTargetDesc.cpp.
References llvm::X86AS::FS.
Referenced by LLVMInitializeNVPTXTargetMC().
createTargetAsmStreamer()
static MCTargetStreamer* createTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & , MCInstPrinter * , bool) static
Definition at line 63 of file NVPTXMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeNVPTXTargetMC().
LLVMInitializeNVPTXTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeNVPTXTargetMC ()
Definition at line 74 of file NVPTXMCTargetDesc.cpp.
References createNullTargetStreamer(), createNVPTXMCInstPrinter(), createNVPTXMCInstrInfo(), createNVPTXMCRegisterInfo(), createNVPTXMCSubtargetInfo(), createTargetAsmStreamer(), llvm::getTheNVPTXTarget32(), llvm::getTheNVPTXTarget64(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), and X.