LLVM: lib/Target/NVPTX/NVVMReflect.cpp File Reference
NVVMReflect.cpp File Reference
#include "NVPTX.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_os_ostream.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include <sstream>
#include <string>
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define NVVM_REFLECT_FUNCTION "__nvvm_reflect"
#define NVVM_REFLECT_OCL_FUNCTION "__nvvm_reflect_ocl"
#define DEBUG_TYPE "nvptx-reflect"
Functions
void llvm::initializeNVVMReflectPass (PassRegistry &)
INITIALIZE_PASS (NVVMReflect, "nvvm-reflect", "Replace occurrences of __nvvm_reflect() calls with 0/1", false, false) static bool runNVVMReflect(Function &F
if (F.getName()==NVVM_REFLECT_FUNCTION||F.getName()==NVVM_REFLECT_OCL_FUNCTION)
for (Instruction &I :instructions(F))
for (Instruction *I :ToRemove) I -> eraseFromParent()
return ToRemove size () > 0
Variables
static cl::opt< bool > NVVMReflectEnabled ("nvvm-reflect-enable", cl::init(true), cl::Hidden, cl::desc("NVVM reflection, enabled by default"))
unsigned SmVersion
SmallVector< Instruction *, 4 > ToRemove
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvptx-reflect"
Definition at line 47 of file NVVMReflect.cpp.
NVVM_REFLECT_FUNCTION
#define NVVM_REFLECT_FUNCTION "__nvvm_reflect"
Definition at line 42 of file NVVMReflect.cpp.
NVVM_REFLECT_OCL_FUNCTION
#define NVVM_REFLECT_OCL_FUNCTION "__nvvm_reflect_ocl"
Definition at line 43 of file NVVMReflect.cpp.
Function Documentation
for() [1/2]
for (Instruction &I :instructionsF)
Definition at line 118 of file NVVMReflect.cpp.
References assert(), Callee, llvm::dbgs(), F, llvm::ConstantInt::get(), I, LLVM_DEBUG, NVVM_REFLECT_FUNCTION, NVVM_REFLECT_OCL_FUNCTION, llvm::StringRef::size(), SmVersion, llvm::StringRef::substr(), and ToRemove.
for() [2/2]
for (Instruction *I :ToRemove) -> eraseFromParent()
if()
if (F. getName() = = NVVM_REFLECT_FUNCTION || F.getName() == NVVM_REFLECT_OCL_FUNCTION)
Definition at line 82 of file NVVMReflect.cpp.
References assert(), and F.
INITIALIZE_PASS()
INITIALIZE_PASS (NVVMReflect , "nvvm-reflect" , "Replace occurrences of __nvvm_reflect() calls with 0/1" , false , false) &
size()
return ToRemove size ()
Definition at line 166 of file README.txt.
Referenced by llvm::TargetLoweringBase::addRegisterClass(), AnalyzeArguments(), llvm::analyzeArguments(), llvm::analyzeReturnValues(), llvm::ARMBaseInstrInfo::ARMBaseInstrInfo(), canLowerByDroppingElements(), CC_LoongArch(), CC_PPC32_SPE_CustomSplitFP64(), CC_PPC32_SPE_RetF64(), CC_PPC32_SVR4_Custom_AlignArgRegs(), CC_PPC32_SVR4_Custom_AlignFPArgRegs(), CC_PPC32_SVR4_Custom_SkipLastArgRegsPPCF128(), CC_RISCV(), CC_SkipOdd(), CC_X86_32_MCUInReg(), llvm::PPCInstrInfo::ClobbersPredicate(), llvm::orc::shared::WrapperFunctionCall::Create(), DecodeARRegisterClass(), DecodeCtrRegs64RegisterClass(), DecodeCtrRegsRegisterClass(), DecodeGuestRegs64RegisterClass(), DecodeGuestRegsRegisterClass(), DecodePRRegsRegisterClass(), DecodeSRRegisterClass(), DecodeSysRegs64RegisterClass(), DecodeSysRegsRegisterClass(), llvm::MCDwarfLineTableHeader::Emit(), llvm::BitstreamWriter::EmitRecord(), enlarge(), llvm::ModuleSummaryIndex::exportToDot(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), llvm::VEFrameLowering::getCalleeSavedSpillSlots(), llvm::ARMFrameLowering::getCalleeSavedSpillSlots(), llvm::HexagonFrameLowering::getCalleeSavedSpillSlots(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), llvm::TargetLoweringBase::getCondCodeAction(), llvm::X86::getFeaturePriority(), llvm::MipsAsmBackend::getFixupKindInfo(), llvm::LoongArchAsmBackend::getFixupKindInfo(), llvm::RISCVAsmBackend::getFixupKindInfo(), llvm::MCAsmBackend::getFixupKindInfo(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLoweringBase::getOperationAction(), llvm::TargetLoweringBase::getRegisterType(), llvm::object::MachOObjectFile::getRelocationTypeName(), llvm::R600RegisterInfo::getSubRegFromChannel(), getSystemRegistryString(), llvm::TargetLoweringBase::getTypeConversion(), hasAttributeProperty(), llvm::TargetLoweringBase::hasTargetDAGCombine(), INITIALIZE_PASS(), llvm::TargetLoweringBase::isTypeLegal(), llvm::LanaiTargetLowering::LowerMUL(), needStackSlotPassParameters(), llvm::Triple::normalize(), operator new(), llvm::SparcInstPrinter::printMembarTag(), llvm::orc::shared::detail::serializeViaSPSToWrapperFunctionResult(), llvm::TargetLoweringBase::setCondCodeAction(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::orc::shared::SPSSerializationTraits< SPSRemoteSymbolLookupSetElement, SymbolLookupSet::value_type >::size(), llvm::orc::shared::SPSSerializationTraits< SPSMachOJITDylibDepInfo, MachOPlatform::MachOJITDylibDepInfo >::size(), llvm::orc::shared::SPSSerializationTraits< SPSRemoteSymbolLookup, ExecutorProcessControl::LookupRequest >::size(), llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddr, jitlink::JITLinkMemoryManager::FinalizedAlloc >::size(), llvm::orc::shared::SPSSerializationTraits< SPSAllocActionCallPair, AllocActionCallPair >::size(), llvm::orc::shared::SPSSerializationTraits< SPSAllocGroup, AllocGroup >::size(), llvm::orc::shared::SPSArgList< SPSTagT, SPSTagTs... >::size(), llvm::orc::shared::SPSSerializationTraits< SPSRemoteSymbolLookupSetElement, RemoteSymbolLookupSetElement >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSegFinalizeRequest, tpctypes::SegFinalizeRequest >::size(), llvm::orc::shared::SPSSerializationTraits< SPSRemoteSymbolLookup, RemoteSymbolLookup >::size(), llvm::orc::shared::SPSSerializationTraits< SPSFinalizeRequest, tpctypes::FinalizeRequest >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSimpleRemoteEPCExecutorInfo, SimpleRemoteEPCExecutorInfo >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSharedMemorySegFinalizeRequest, tpctypes::SharedMemorySegFinalizeRequest >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSharedMemoryFinalizeRequest, tpctypes::SharedMemoryFinalizeRequest >::size(), llvm::orc::shared::SPSSerializationTraits< SPSMemoryAccessUIntWrite< T >, tpctypes::UIntWrite< T > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddr, ExecutorAddr >::size(), llvm::orc::shared::SPSSerializationTraits< SPSELFPerObjectSectionsToRegister, ELFPerObjectSectionsToRegister >::size(), llvm::orc::shared::SPSSerializationTraits< SPSMemoryAccessBufferWrite, tpctypes::BufferWrite >::size(), llvm::orc::shared::SPSSerializationTraits< SPSExecutorAddrRange, ExecutorAddrRange >::size(), llvm::orc::shared::SPSSerializationTraits< SPSELFNixJITDylibInitializers, ELFNixJITDylibInitializers >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< char >, ArrayRef< char > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSTuple< SPSTagT1, SPSTagT2 >, std::pair< T1, T2 > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSOptional< SPSTagT >, std::optional< T > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSString, StringRef >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSError, detail::SPSSerializableError >::size(), llvm::orc::shared::SPSSerializationTraits< SPSExpected< SPSTagT >, detail::SPSSerializableExpected< T > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSWrapperFunctionCall, WrapperFunctionCall >::size(), llvm::orc::shared::SPSSerializationTraits< SPSExpected< SPSTagT >, detail::SPSSerializableError >::size(), llvm::orc::shared::SPSSerializationTraits< SPSExpected< SPSTagT >, T >::size(), llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic(), llvm::write_hex(), write_padding(), writeCOFF(), and llvm::writeIndexTable().
Variable Documentation
NVVMReflectEnabled
cl::opt<bool> NVVMReflectEnabled("nvvm-reflect-enable", cl::init(true), cl::Hidden, cl::desc("NVVM reflection, enabled by default")) static
SmVersion
unsigned SmVersion
Initial value:
{
  if (!NVVMReflectEnabled)
    return false
Definition at line 78 of file NVVMReflect.cpp.
Referenced by llvm::createNVVMIntrRangePass(), llvm::createNVVMReflectPass(), for(), llvm::NVPTXSubtarget::getSmVersion(), llvm::NVPTXSubtarget::hasAtomAddF64(), llvm::NVPTXSubtarget::hasAtomBitwise64(), llvm::NVPTXSubtarget::hasAtomMinMax64(), llvm::NVPTXSubtarget::hasAtomScope(), llvm::NVPTXSubtarget::hasFP16Math(), llvm::NVPTXSubtarget::hasHWROT32(), llvm::NVPTXSubtarget::hasLDG(), llvm::NVPTXSubtarget::hasNoReturn(), llvm::NVVMIntrRangePass::NVVMIntrRangePass(), llvm::NVVMReflectPass::NVVMReflectPass(), llvm::NVVMReflectPass::run(), and runNVVMIntrRange().
ToRemove
SmallVector<Instruction *, 4> ToRemove
Definition at line 90 of file NVVMReflect.cpp.
Referenced by for().