LLVM: lib/Object/Archive.cpp File Reference
Archive.cpp File Reference
#include "llvm/Object/Archive.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/Error.h"
#include "llvm/Support/Chrono.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Host.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <system_error>
Functions
static Error malformedError (Twine Msg)
static Error createMemberHeaderParseError (const AbstractArchiveMemberHeader *ArMemHeader, const char *RawHeaderPtr, uint64_t Size)
template<class T , std::size_t N>
StringRef getFieldRawString (const T(&Field)[N])
Expected< uint64_t > getArchiveMemberDecField (Twine FieldName, const StringRef RawField, const Archive *Parent, const AbstractArchiveMemberHeader *MemHeader)
Expected< uint64_t > getArchiveMemberOctField (Twine FieldName, const StringRef RawField, const Archive *Parent, const AbstractArchiveMemberHeader *MemHeader)
Function Documentation
createMemberHeaderParseError()
static Error createMemberHeaderParseError (const AbstractArchiveMemberHeader * ArMemHeader, const char * RawHeaderPtr, uint64_t Size) static
Definition at line 50 of file Archive.cpp.
References llvm::consumeError(), malformedError(), llvm::AMDGPU::SendMsg::Msg, llvm::Expected< T >::takeError(), and uint64_t.
getArchiveMemberDecField()
Expected<uint64_t> getArchiveMemberDecField (Twine FieldName, const StringRef RawField, const Archive * Parent, const AbstractArchiveMemberHeader * MemHeader)
Definition at line 173 of file Archive.cpp.
References llvm::StringRef::getAsInteger(), malformedError(), and uint64_t.
Referenced by llvm::object::AbstractArchiveMemberHeader::getGID(), llvm::object::AbstractArchiveMemberHeader::getLastModified(), llvm::object::BigArchiveMemberHeader::getNextOffset(), llvm::object::BigArchiveMemberHeader::getRawName(), llvm::object::BigArchiveMemberHeader::getRawNameSize(), llvm::object::ArchiveMemberHeader::getSize(), llvm::object::BigArchiveMemberHeader::getSize(), and llvm::object::AbstractArchiveMemberHeader::getUID().
getArchiveMemberOctField()
Expected<uint64_t> getArchiveMemberOctField (Twine FieldName, const StringRef RawField, const Archive * Parent, const AbstractArchiveMemberHeader * MemHeader)
Definition at line 191 of file Archive.cpp.
References llvm::StringRef::getAsInteger(), malformedError(), and uint64_t.
Referenced by llvm::object::AbstractArchiveMemberHeader::getAccessMode().
getFieldRawString()
template<class T , std::size_t N> StringRef getFieldRawString (const T(&) Field[N])
Definition at line 65 of file Archive.cpp.
References N, and llvm::StringRef::rtrim().
Referenced by llvm::object::BigArchiveMemberHeader::getNextOffset(), llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::getRawAccessMode(), llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::getRawGID(), llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::getRawLastModified(), llvm::object::BigArchiveMemberHeader::getRawName(), llvm::object::BigArchiveMemberHeader::getRawNameSize(), llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::getRawUID(), llvm::object::ArchiveMemberHeader::getSize(), and llvm::object::BigArchiveMemberHeader::getSize().
malformedError()
static Error malformedError (Twine Msg) static
Definition at line 43 of file Archive.cpp.
References move, llvm::AMDGPU::SendMsg::Msg, and llvm::object::parse_failed.
Referenced by createMemberHeaderParseError(), getArchiveMemberDecField(), getArchiveMemberOctField(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::Archive::Child::getNext(), llvm::object::ArchiveMemberHeader::getRawName(), and llvm::object::BigArchiveMemberHeader::getRawName().