LLVM: lib/Object/DXContainer.cpp File Reference
DXContainer.cpp File Reference
#include "llvm/Object/DXContainer.h"
#include "llvm/BinaryFormat/DXContainer.h"
#include "llvm/Object/Error.h"
#include "llvm/Support/FormatVariadic.h"
Functions
static Error parseFailed (const Twine &Msg)
template<typename T >
static Error readStruct (StringRef Buffer, const char *Src, T &Struct)
template<typename T >
static Error readInteger (StringRef Buffer, const char *Src, T &Val, Twine Str="structure")
Function Documentation
parseFailed()
static Error parseFailed (const Twine & Msg) static
Definition at line 17 of file DXContainer.cpp.
References llvm::AMDGPU::SendMsg::Msg, and llvm::object::parse_failed.
Referenced by readInteger(), and readStruct().
readInteger()
template<typename T > static Error readInteger (StringRef Buffer, const char * Src, T & Val, Twine Str = "structure") static
Definition at line 35 of file DXContainer.cpp.
References llvm::StringRef::begin(), llvm::StringRef::end(), llvm::sys::IsBigEndianHost, memcpy(), parseFailed(), llvm::Error::success(), and llvm::sys::swapByteOrder().
readStruct()
template<typename T > static Error readStruct (StringRef Buffer, const char * Src, T & Struct) static
Definition at line 22 of file DXContainer.cpp.
References llvm::StringRef::begin(), llvm::StringRef::end(), llvm::sys::IsBigEndianHost, memcpy(), parseFailed(), Struct, and llvm::Error::success().