LLVM: lib/Support/OptimizedStructLayout.cpp File Reference
OptimizedStructLayout.cpp File Reference
#include "llvm/Support/OptimizedStructLayout.h"
#include <optional>
Typedefs
using Field = OptimizedStructLayoutField
Functions
static void checkValidLayout (ArrayRef< Field > Fields, uint64_t Size, Align MaxAlign)
Typedef Documentation
Field
using Field = OptimizedStructLayoutField
Definition at line 18 of file OptimizedStructLayout.cpp.
Function Documentation
checkValidLayout()
static void checkValidLayout (ArrayRef< Field > Fields, uint64_t Size, Align MaxAlign) static
Definition at line 21 of file OptimizedStructLayout.cpp.
References llvm::OptimizedStructLayoutField::Alignment, assert(), llvm::OptimizedStructLayoutField::getEndOffset(), llvm::OptimizedStructLayoutField::hasFixedOffset(), llvm::isAligned(), llvm::max(), llvm::OptimizedStructLayoutField::Offset, and uint64_t.
Referenced by llvm::performOptimizedStructLayout().