LLVM: lib/Transforms/Instrumentation/PGOInstrumentation.cpp File Reference
PGOInstrumentation.cpp File Reference
#include "llvm/Transforms/Instrumentation/PGOInstrumentation.h"
#include "CFGMST.h"
#include "ValueProfileCollector.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/ADT/iterator.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/MemoryProfileInfo.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/EHPersonalities.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/ProfDataUtils.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/Support/BLAKE3.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/CRC.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/DOTGraphTraits.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/HashBuilder.h"
#include "llvm/Support/VirtualFileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/MisExpect.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <map>
#include <memory>
#include <numeric>
#include <optional>
#include <set>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include "llvm/ProfileData/InstrProfData.inc"
Classes
struct llvm::GraphTraits< PGOUseFunc * >
struct llvm::DOTGraphTraits< PGOUseFunc * >
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "pgo-instrumentation"
#define VALUE_PROF_KIND(Enumerator, Value, Descr) Descr,
Typedefs
using ProfileCount = Function::ProfileCount
using VPCandidateInfo = ValueProfileCollector::CandidateInfo
Functions
STATISTIC (NumOfPGOInstrument, "Number of edges instrumented.")
STATISTIC (NumOfPGOSelectInsts, "Number of select instruction instrumented.")
STATISTIC (NumOfPGOMemIntrinsics, "Number of mem intrinsics instrumented.")
STATISTIC (NumOfPGOEdge, "Number of edges.")
STATISTIC (NumOfPGOBB, "Number of basic-blocks.")
STATISTIC (NumOfPGOSplit, "Number of critical edge splits.")
STATISTIC (NumOfPGOFunc, "Number of functions having valid profile counts.")
STATISTIC (NumOfPGOMismatch, "Number of functions having mismatch profile.")
STATISTIC (NumOfPGOMissing, "Number of functions without profile.")
STATISTIC (NumOfMemProfMissing, "Number of functions without memory profile.")
STATISTIC (NumOfPGOICall, "Number of indirect call value instrumentations.")
STATISTIC (NumOfCSPGOInstrument, "Number of edges instrumented in CSPGO.")
STATISTIC (NumOfCSPGOSelectInsts, "Number of select instruction instrumented in CSPGO.")
STATISTIC (NumOfCSPGOMemIntrinsics, "Number of mem intrinsics instrumented in CSPGO.")
STATISTIC (NumOfCSPGOEdge, "Number of edges in CSPGO.")
STATISTIC (NumOfCSPGOBB, "Number of basic-blocks in CSPGO.")
STATISTIC (NumOfCSPGOSplit, "Number of critical edge splits in CSPGO.")
STATISTIC (NumOfCSPGOFunc, "Number of functions having valid profile counts in CSPGO.")
STATISTIC (NumOfCSPGOMismatch, "Number of functions having mismatch profile in CSPGO.")
STATISTIC (NumOfCSPGOMissing, "Number of functions without profile in CSPGO.")
cl::opt< bool > llvm::NoPGOWarnMismatch ("no-pgo-warn-mismatch", cl::init(false), cl::Hidden, cl::desc("Use this option to turn off/on " "warnings about profile cfg mismatch."))
static std::string getBranchCondString (Instruction *TI)
static GlobalVariable * createIRLevelProfileFlagVar (Module &M, bool IsCS)
static bool canRenameComdat (Function &F, std::unordered_multimap< Comdat *, GlobalValue * > &ComdatMembers)
static void populateEHOperandBundle (VPCandidateInfo &Cand, DenseMap< BasicBlock *, ColorVector > &BlockColors, SmallVectorImpl< OperandBundleDef > &OpBundles)
static void instrumentOneFunc (Function &F, Module *M, TargetLibraryInfo &TLI, BranchProbabilityInfo *BPI, BlockFrequencyInfo *BFI, std::unordered_multimap< Comdat *, GlobalValue * > &ComdatMembers, bool IsCS)
static uint64_t sumEdgeCount (const ArrayRef< PGOUseEdge * > Edges)
static void annotateFunctionWithHashMismatch (Function &F, LLVMContext &ctx)
static void addCallsiteMetadata (Instruction &I, std::vector< uint64_t > &InlinedCallStack, LLVMContext &Ctx)
static uint64_t computeStackId (GlobalValue::GUID Function, uint32_t LineOffset, uint32_t Column)
static uint64_t computeStackId (const memprof::Frame &Frame)
static void addCallStack (CallStackTrie &AllocTrie, const AllocationInfo *AllocInfo)
static bool stackFrameIncludesInlinedCallStack (ArrayRef< Frame > ProfileCallStack, ArrayRef< uint64_t > InlinedCallStack, unsigned StartIndex=0)
static bool isIndirectBrTarget (BasicBlock *BB)
static void collectComdatMembers (Module &M, std::unordered_multimap< Comdat *, GlobalValue * > &ComdatMembers)
static bool skipPGO (const Function &F)
static bool InstrumentAllFunctions (Module &M, function_ref< TargetLibraryInfo &(Function &)> LookupTLI, function_ref< BranchProbabilityInfo *(Function &)> LookupBPI, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI, bool IsCS)
static void fixFuncEntryCount (PGOUseFunc &Func, LoopInfo &LI, BranchProbabilityInfo &NBPI)
static void verifyFuncBFI (PGOUseFunc &Func, LoopInfo &LI, BranchProbabilityInfo &NBPI, uint64_t HotCountThreshold, uint64_t ColdCountThreshold)
static bool annotateAllFunctions (Module &M, StringRef ProfileFileName, StringRef ProfileRemappingFileName, vfs::FileSystem &FS, function_ref< TargetLibraryInfo &(Function &)> LookupTLI, function_ref< BranchProbabilityInfo *(Function &)> LookupBPI, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI, ProfileSummaryInfo *PSI, bool IsCS)
static std::string getSimpleNodeName (const BasicBlock *Node)
void llvm::setIrrLoopHeaderMetadata (Module *M, Instruction *TI, uint64_t Count)
Variables
static cl::opt< std::string > PGOTestProfileFile ("pgo-test-profile-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("Specify the path of profile data file. This is" "mainly for test purpose."))
static cl::opt< std::string > PGOTestProfileRemappingFile ("pgo-test-profile-remapping-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("Specify the path of profile remapping file. This is mainly for " "test purpose."))
static cl::opt< bool > DisableValueProfiling ("disable-vp", cl::init(false), cl::Hidden, cl::desc("Disable Value Profiling"))
static cl::opt< unsigned > MaxNumAnnotations ("icp-max-annotations", cl::init(3), cl::Hidden, cl::desc("Max number of annotations for a single indirect " "call callsite"))
static cl::opt< unsigned > MaxNumMemOPAnnotations ("memop-max-annotations", cl::init(4), cl::Hidden, cl::desc("Max number of preicise value annotations for a single memop" "intrinsic"))
static cl::opt< bool > DoComdatRenaming ("do-comdat-renaming", cl::init(false), cl::Hidden, cl::desc("Append function hash to the name of COMDAT function to avoid " "function hash mismatch due to the preinliner"))
static cl::opt< bool > PGOWarnMissing ("pgo-warn-missing-function", cl::init(false), cl::Hidden, cl::desc("Use this option to turn on/off " "warnings about missing profile data for " "functions."))
static cl::opt< bool > NoPGOWarnMismatchComdatWeak ("no-pgo-warn-mismatch-comdat-weak", cl::init(true), cl::Hidden, cl::desc("The option is used to turn on/off " "warnings about hash mismatch for comdat " "or weak functions."))
static cl::opt< bool > PGOInstrSelect ("pgo-instr-select", cl::init(true), cl::Hidden, cl::desc("Use this option to turn on/off SELECT " "instruction instrumentation. "))
static cl::opt< PGOViewCountsType > PGOViewRawCounts ("pgo-view-raw-counts", cl::Hidden, cl::desc("A boolean option to show CFG dag or text " "with raw profile counts from " "profile data. See also option " "-pgo-view-counts. To limit graph " "display to only one function, use " "filtering option -view-bfi-func-name."), cl::values(clEnumValN(PGOVCT_None, "none", "do not show."), clEnumValN(PGOVCT_Graph, "graph", "show a graph."), clEnumValN(PGOVCT_Text, "text", "show in text.")))
static cl::opt< bool > PGOInstrMemOP ("pgo-instr-memop", cl::init(true), cl::Hidden, cl::desc("Use this option to turn on/off " "memory intrinsic size profiling."))
static cl::opt< bool > EmitBranchProbability ("pgo-emit-branch-prob", cl::init(false), cl::Hidden, cl::desc("When this option is on, the annotated " "branch probability will be emitted as " "optimization remarks: -{Rpass|" "pass-remarks}=pgo-instrumentation"))
static cl::opt< bool > PGOInstrumentEntry ("pgo-instrument-entry", cl::init(false), cl::Hidden, cl::desc("Force to instrument function entry basicblock."))
static cl::opt< bool > PGOFunctionEntryCoverage ("pgo-function-entry-coverage", cl::Hidden, cl::desc("Use this option to enable function entry coverage instrumentation."))
static cl::opt< bool > PGOFixEntryCount ("pgo-fix-entry-count", cl::init(true), cl::Hidden, cl::desc("Fix function entry count in profile use."))
static cl::opt< bool > PGOVerifyHotBFI ("pgo-verify-hot-bfi", cl::init(false), cl::Hidden, cl::desc("Print out the non-match BFI count if a hot raw profile count " "becomes non-hot, or a cold raw profile count becomes hot. " "The print is enabled under -Rpass-analysis=pgo, or " "internal option -pass-remakrs-analysis=pgo."))
static cl::opt< bool > PGOVerifyBFI ("pgo-verify-bfi", cl::init(false), cl::Hidden, cl::desc("Print out mismatched BFI counts after setting profile metadata " "The print is enabled under -Rpass-analysis=pgo, or " "internal option -pass-remakrs-analysis=pgo."))
static cl::opt< unsigned > PGOVerifyBFIRatio ("pgo-verify-bfi-ratio", cl::init(2), cl::Hidden, cl::desc("Set the threshold for pgo-verify-bfi: only print out " "mismatched BFI if the difference percentage is greater than " "this value (in percentage)."))
static cl::opt< unsigned > PGOVerifyBFICutoff ("pgo-verify-bfi-cutoff", cl::init(5), cl::Hidden, cl::desc("Set the threshold for pgo-verify-bfi: skip the counts whose " "profile count value is below."))
static cl::opt< std::string > PGOTraceFuncHash ("pgo-trace-func-hash", cl::init("-"), cl::Hidden, cl::value_desc("function name"), cl::desc("Trace the hash of the function with this name."))
static cl::opt< unsigned > PGOFunctionSizeThreshold ("pgo-function-size-threshold", cl::Hidden, cl::desc("Do not instrument functions smaller than this threshold."))
static cl::opt< bool > MatchMemProf ("pgo-match-memprof", cl::init(true), cl::Hidden, cl::desc("Perform matching and annotation of memprof profiles."))
static cl::opt< unsigned > PGOFunctionCriticalEdgeThreshold ("pgo-critical-edge-threshold", cl::init(20000), cl::Hidden, cl::desc("Do not instrument functions with the number of critical edges " " greater than this threshold."))
static cl::opt< bool > PGOOldCFGHashing ("pgo-instr-old-cfg-hashing", cl::init(false), cl::Hidden, cl::desc("Use the old CFG function hashing"))
static const char * ValueProfKindDescr []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "pgo-instrumentation"
Definition at line 137 of file PGOInstrumentation.cpp.
VALUE_PROF_KIND
#define VALUE_PROF_KIND (Enumerator, Value, Descr) Descr,
Typedef Documentation
ProfileCount
using ProfileCount = Function::ProfileCount
Definition at line 134 of file PGOInstrumentation.cpp.
VPCandidateInfo
using VPCandidateInfo = ValueProfileCollector::CandidateInfo
Definition at line 135 of file PGOInstrumentation.cpp.
Function Documentation
addCallsiteMetadata()
static void addCallsiteMetadata (Instruction & I, std::vector< uint64_t > & InlinedCallStack, LLVMContext & Ctx) static
Definition at line 1247 of file PGOInstrumentation.cpp.
References llvm::memprof::buildCallstackMetadata(), and I.
addCallStack()
static void addCallStack (CallStackTrie & AllocTrie, const AllocationInfo * AllocInfo) static
Definition at line 1269 of file PGOInstrumentation.cpp.
References llvm::memprof::CallStackTrie::addCallStack(), computeStackId(), and llvm::memprof::getAllocType().
annotateAllFunctions()
static bool annotateAllFunctions (Module & M, StringRef ProfileFileName, StringRef ProfileRemappingFileName, vfs::FileSystem & FS, function_ref< TargetLibraryInfo &(Function &)> LookupTLI, function_ref< BranchProbabilityInfo *(Function &)> LookupBPI, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI, ProfileSummaryInfo * PSI, bool IsCS) static
Definition at line 2061 of file PGOInstrumentation.cpp.
References llvm::AMDGPUISD::BFI, llvm::CallingConv::Cold, ColdCountThreshold, collectComdatMembers(), llvm::IndexedInstrProfReader::create(), llvm::StringRef::data(), llvm::dbgs(), llvm::DS_Warning, E, F, fixFuncEntryCount(), llvm::X86AS::FS, llvm::cl::Option::getNumOccurrences(), llvm::ProfileSummaryInfo::getOrCompColdCountThreshold(), llvm::ProfileSummaryInfo::getOrCompHotCountThreshold(), llvm::handleAllErrors(), LLVM_DEBUG, M, llvm::ErrorInfoBase::message(), move, llvm::AMDGPU::SendMsg::Msg, llvm::InstrProfRecord::NotPseudo, llvm::Function::PCT_Real, PGOFixEntryCount, PGOInstrumentEntry, llvm::PGOVCT_Graph, llvm::PGOVCT_None, llvm::PGOVCT_Text, PGOVerifyBFI, PGOVerifyHotBFI, llvm::PGOViewCounts, PGOViewRawCounts, llvm::InstrProfRecord::PseudoHot, llvm::ProfileSummary::PSK_CSInstr, llvm::ProfileSummary::PSK_Instr, llvm::ProfileSummaryInfo::refresh(), skipPGO(), llvm::SplitIndirectBrCriticalEdges(), uint64_t, verifyFuncBFI(), llvm::ViewBlockFreqFuncName, llvm::ViewGraph(), and llvm::WriteGraph().
Referenced by llvm::PGOInstrumentationUse::run().
annotateFunctionWithHashMismatch()
static void annotateFunctionWithHashMismatch (Function & F, LLVMContext & ctx) static
Definition at line 1226 of file PGOInstrumentation.cpp.
References llvm::MDBuilder::createString(), F, llvm::MDTuple::get(), N, and llvm::MDNode::operands().
canRenameComdat()
static bool canRenameComdat (Function & F, std::unordered_multimap< Comdat *, GlobalValue * > & ComdatMembers) static
Definition at line 669 of file PGOInstrumentation.cpp.
References assert(), llvm::canRenameComdatFunc(), DoComdatRenaming, F, and llvm::make_range().
collectComdatMembers()
static void collectComdatMembers (Module & M, std::unordered_multimap< Comdat *, GlobalValue * > & ComdatMembers) static
Definition at line 1840 of file PGOInstrumentation.cpp.
References DoComdatRenaming, F, and M.
Referenced by annotateAllFunctions(), and InstrumentAllFunctions().
computeStackId() [1/2]
static uint64_t computeStackId (const memprof::Frame & Frame) static
Definition at line 1265 of file PGOInstrumentation.cpp.
References llvm::memprof::Frame::Column, computeStackId(), llvm::memprof::Frame::Function, and llvm::memprof::Frame::LineOffset.
computeStackId() [2/2]
static uint64_t computeStackId (GlobalValue::GUID Function, uint32_t LineOffset, uint32_t Column) static
Definition at line 1254 of file PGOInstrumentation.cpp.
References llvm::HashBuilderImpl< HasherT, Endianness >::add(), llvm::HashBuilderBase< HasherT >::final(), llvm::support::little, memcpy(), and uint64_t.
Referenced by addCallStack(), computeStackId(), and stackFrameIncludesInlinedCallStack().
createIRLevelProfileFlagVar()
static GlobalVariable* createIRLevelProfileFlagVar (Module & M, bool IsCS) static
Definition at line 374 of file PGOInstrumentation.cpp.
References llvm::DebugInfoCorrelate, llvm::GlobalValue::ExternalLinkage, llvm::Type::getInt64Ty(), llvm::Constant::getIntegerValue(), llvm::GlobalValue::HiddenVisibility, M, PGOFunctionEntryCoverage, PGOInstrumentEntry, uint64_t, llvm::tgtok::VarName, and llvm::GlobalValue::WeakAnyLinkage.
Referenced by InstrumentAllFunctions(), and llvm::PGOInstrumentationGenCreateVar::run().
fixFuncEntryCount()
static void fixFuncEntryCount (PGOUseFunc & Func, LoopInfo & LI, BranchProbabilityInfo & NBPI) static
Definition at line 1940 of file PGOInstrumentation.cpp.
References llvm::lltok::APFloat, assert(), llvm::APFloatBase::cmpEqual, llvm::APFloatBase::cmpGreaterThan, llvm::dbgs(), F, llvm::BlockFrequencyInfo::getBlockProfileCount(), llvm::APFloat::getZero(), llvm::APFloatBase::IEEEdouble(), LLVM_DEBUG, llvm::Function::PCT_Real, llvm::APFloatBase::rmNearestTiesToEven, and uint64_t.
Referenced by annotateAllFunctions().
getBranchCondString()
static std::string getBranchCondString (Instruction * TI) static
Definition at line 336 of file PGOInstrumentation.cpp.
References Cond, llvm::raw_ostream::flush(), llvm::BranchInst::getCondition(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getPredicateName(), llvm::Value::getType(), llvm::BranchInst::isConditional(), llvm::ConstantInt::isMinusOne(), llvm::ConstantInt::isOne(), llvm::ConstantInt::isZero(), OS, llvm::Type::print(), result, and RHS.
Referenced by llvm::setProfMetadata().
getSimpleNodeName()
static std::string getSimpleNodeName (const BasicBlock * Node) static
Definition at line 2291 of file PGOInstrumentation.cpp.
InstrumentAllFunctions()
static bool InstrumentAllFunctions (Module & M, function_ref< TargetLibraryInfo &(Function &)> LookupTLI, function_ref< BranchProbabilityInfo *(Function &)> LookupBPI, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI, bool IsCS) static
Definition at line 1888 of file PGOInstrumentation.cpp.
References llvm::AMDGPUISD::BFI, collectComdatMembers(), createIRLevelProfileFlagVar(), F, instrumentOneFunc(), M, and skipPGO().
Referenced by llvm::PGOInstrumentationGen::run().
instrumentOneFunc()
static void instrumentOneFunc (Function & F, Module * M, TargetLibraryInfo & TLI, BranchProbabilityInfo * BPI, BlockFrequencyInfo * BFI, std::unordered_multimap< Comdat *, GlobalValue * > & ComdatMembers, bool IsCS) static
Definition at line 851 of file PGOInstrumentation.cpp.
References assert(), llvm::AMDGPUISD::BFI, Builder, llvm::classifyEHPersonality(), llvm::colorEHFunclets(), llvm::dbgs(), DisableValueProfiling, llvm::BasicBlock::end(), F, llvm::ConstantInt::get(), llvm::ConstantExpr::getBitCast(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getFirstInsertionPt(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), I, llvm::isFuncletEHPersonality(), LLVM_DEBUG, M, PGOFunctionEntryCoverage, PGOInstrMemOP, PGOInstrumentEntry, populateEHOperandBundle(), llvm::SplitIndirectBrCriticalEdges(), and ValueProfKindDescr.
Referenced by InstrumentAllFunctions().
isIndirectBrTarget()
static bool isIndirectBrTarget (BasicBlock * BB) static
Definition at line 1717 of file PGOInstrumentation.cpp.
References BB, and llvm::predecessors().
populateEHOperandBundle()
static void populateEHOperandBundle (VPCandidateInfo & Cand, DenseMap< BasicBlock *, ColorVector > & BlockColors, SmallVectorImpl< OperandBundleDef > & OpBundles) static
Definition at line 821 of file PGOInstrumentation.cpp.
References llvm::ValueProfileCollector::CandidateInfo::AnnotatedInst, assert(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::TinyPtrVector< EltTy >::front(), llvm::Instruction::isEHPad(), llvm::LLVMContext::OB_funclet, and llvm::TinyPtrVector< EltTy >::size().
Referenced by instrumentOneFunc().
skipPGO()
static bool skipPGO (const Function & F) static
Definition at line 1857 of file PGOInstrumentation.cpp.
References BB, llvm::dbgs(), E, F, llvm::Instruction::getNumSuccessors(), I, llvm::isCriticalEdge(), LLVM_DEBUG, PGOFunctionCriticalEdgeThreshold, and PGOFunctionSizeThreshold.
Referenced by annotateAllFunctions(), and InstrumentAllFunctions().
stackFrameIncludesInlinedCallStack()
static bool stackFrameIncludesInlinedCallStack (ArrayRef< Frame > ProfileCallStack, ArrayRef< uint64_t > InlinedCallStack, unsigned StartIndex = 0) static
Definition at line 1285 of file PGOInstrumentation.cpp.
References llvm::ArrayRef< T >::begin(), computeStackId(), llvm::ArrayRef< T >::end(), and uint64_t.
STATISTIC() [1/20]
STATISTIC (NumOfCSPGOBB , "Number of basic-blocks in CSPGO.")
STATISTIC() [2/20]
STATISTIC (NumOfCSPGOEdge , "Number of edges in CSPGO.")
STATISTIC() [3/20]
STATISTIC (NumOfCSPGOFunc , "Number of functions having valid profile counts in CSPGO.")
STATISTIC() [4/20]
STATISTIC (NumOfCSPGOInstrument , "Number of edges instrumented in CSPGO.")
STATISTIC() [5/20]
STATISTIC (NumOfCSPGOMemIntrinsics , "Number of mem intrinsics instrumented in CSPGO.")
STATISTIC() [6/20]
STATISTIC (NumOfCSPGOMismatch , "Number of functions having mismatch profile in CSPGO.")
STATISTIC() [7/20]
STATISTIC (NumOfCSPGOMissing , "Number of functions without profile in CSPGO.")
STATISTIC() [8/20]
STATISTIC (NumOfCSPGOSelectInsts , "Number of select instruction instrumented in CSPGO.")
STATISTIC() [9/20]
STATISTIC (NumOfCSPGOSplit , "Number of critical edge splits in CSPGO.")
STATISTIC() [10/20]
STATISTIC (NumOfMemProfMissing , "Number of functions without memory profile.")
STATISTIC() [11/20]
STATISTIC (NumOfPGOBB , "Number of basic-blocks.")
STATISTIC() [12/20]
STATISTIC (NumOfPGOEdge , "Number of edges.")
STATISTIC() [13/20]
STATISTIC (NumOfPGOFunc , "Number of functions having valid profile counts.")
STATISTIC() [14/20]
STATISTIC (NumOfPGOICall , "Number of indirect call value instrumentations.")
STATISTIC() [15/20]
STATISTIC (NumOfPGOInstrument , "Number of edges instrumented.")
STATISTIC() [16/20]
STATISTIC (NumOfPGOMemIntrinsics , "Number of mem intrinsics instrumented.")
STATISTIC() [17/20]
STATISTIC (NumOfPGOMismatch , "Number of functions having mismatch profile.")
STATISTIC() [18/20]
STATISTIC (NumOfPGOMissing , "Number of functions without profile.")
STATISTIC() [19/20]
STATISTIC (NumOfPGOSelectInsts , "Number of select instruction instrumented.")
STATISTIC() [20/20]
STATISTIC (NumOfPGOSplit , "Number of critical edge splits.")
sumEdgeCount()
static uint64_t sumEdgeCount (const ArrayRef< PGOUseEdge * > Edges) static
Definition at line 1017 of file PGOInstrumentation.cpp.
References E, llvm::Total, and uint64_t.
verifyFuncBFI()
static void verifyFuncBFI (PGOUseFunc & Func, LoopInfo & LI, BranchProbabilityInfo & NBPI, uint64_t HotCountThreshold, uint64_t ColdCountThreshold) static
Definition at line 1987 of file PGOInstrumentation.cpp.
References ColdCountThreshold, DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), F, llvm::BlockFrequencyInfo::getBlockProfileCount(), llvm::AMDGPU::SendMsg::Msg, PGOVerifyBFICutoff, PGOVerifyBFIRatio, PGOVerifyHotBFI, llvm::Remark, and uint64_t.
Referenced by annotateAllFunctions().
Variable Documentation
DisableValueProfiling
cl::opt<bool> DisableValueProfiling("disable-vp", cl::init(false), cl::Hidden, cl::desc("Disable Value Profiling")) static
Referenced by instrumentOneFunc().
DoComdatRenaming
cl::opt<bool> DoComdatRenaming("do-comdat-renaming", cl::init(false), cl::Hidden, cl::desc("Append function hash to the name of COMDAT function to avoid " "function hash mismatch due to the preinliner")) static
Referenced by canRenameComdat(), and collectComdatMembers().
EmitBranchProbability
cl::opt<bool> EmitBranchProbability("pgo-emit-branch-prob", cl::init(false), cl::Hidden, cl::desc("When this option is on, the annotated " "branch probability will be emitted as " "optimization remarks: -{Rpass|" "pass-remarks}=pgo-instrumentation")) static
Referenced by llvm::setProfMetadata().
MatchMemProf
cl::opt<bool> MatchMemProf("pgo-match-memprof", cl::init(true), cl::Hidden, cl::desc("Perform matching and annotation of memprof profiles.")) static
MaxNumAnnotations
cl::opt<unsigned> MaxNumAnnotations("icp-max-annotations", cl::init(3), cl::Hidden, cl::desc("Max number of annotations for a single indirect " "call callsite")) static
MaxNumMemOPAnnotations
cl::opt<unsigned> MaxNumMemOPAnnotations("memop-max-annotations", cl::init(4), cl::Hidden, cl::desc("Max number of preicise value annotations for a single memop" "intrinsic")) static
NoPGOWarnMismatchComdatWeak
cl::opt<bool> NoPGOWarnMismatchComdatWeak("no-pgo-warn-mismatch-comdat-weak", cl::init(true), cl::Hidden, cl::desc("The option is used to turn on/off " "warnings about hash mismatch for comdat " "or weak functions.")) static
PGOFixEntryCount
cl::opt<bool> PGOFixEntryCount("pgo-fix-entry-count", cl::init(true), cl::Hidden, cl::desc("Fix function entry count in profile use.")) static
Referenced by annotateAllFunctions().
PGOFunctionCriticalEdgeThreshold
cl::opt<unsigned> PGOFunctionCriticalEdgeThreshold("pgo-critical-edge-threshold", cl::init(20000), cl::Hidden, cl::desc("Do not instrument functions with the number of critical edges " " greater than this threshold.")) static
Referenced by skipPGO().
PGOFunctionEntryCoverage
cl::opt<bool> PGOFunctionEntryCoverage("pgo-function-entry-coverage", cl::Hidden, cl::desc("Use this option to enable function entry coverage instrumentation.")) static
Referenced by createIRLevelProfileFlagVar(), and instrumentOneFunc().
PGOFunctionSizeThreshold
cl::opt<unsigned> PGOFunctionSizeThreshold("pgo-function-size-threshold", cl::Hidden, cl::desc("Do not instrument functions smaller than this threshold.")) static
Referenced by skipPGO().
PGOInstrMemOP
cl::opt<bool> PGOInstrMemOP("pgo-instr-memop", cl::init(true), cl::Hidden, cl::desc("Use this option to turn on/off " "memory intrinsic size profiling.")) static
Referenced by instrumentOneFunc().
PGOInstrSelect
cl::opt<bool> PGOInstrSelect("pgo-instr-select", cl::init(true), cl::Hidden, cl::desc("Use this option to turn on/off SELECT " "instruction instrumentation. ")) static
PGOInstrumentEntry
cl::opt<bool> PGOInstrumentEntry("pgo-instrument-entry", cl::init(false), cl::Hidden, cl::desc("Force to instrument function entry basicblock.")) static
Referenced by annotateAllFunctions(), createIRLevelProfileFlagVar(), and instrumentOneFunc().
PGOOldCFGHashing
cl::opt<bool> PGOOldCFGHashing("pgo-instr-old-cfg-hashing", cl::init(false), cl::Hidden, cl::desc("Use the old CFG function hashing")) static
PGOTestProfileFile
cl::opt<std::string> PGOTestProfileFile("pgo-test-profile-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("Specify the path of profile data file. This is" "mainly for test purpose.")) static
Referenced by llvm::PGOInstrumentationUse::PGOInstrumentationUse().
PGOTestProfileRemappingFile
cl::opt<std::string> PGOTestProfileRemappingFile("pgo-test-profile-remapping-file", cl::init(""), cl::Hidden, cl::value_desc("filename"), cl::desc("Specify the path of profile remapping file. This is mainly for " "test purpose.")) static
Referenced by llvm::PGOInstrumentationUse::PGOInstrumentationUse().
PGOTraceFuncHash
cl::opt<std::string> PGOTraceFuncHash("pgo-trace-func-hash", cl::init("-"), cl::Hidden, cl::value_desc("function name"), cl::desc("Trace the hash of the function with this name.")) static
PGOVerifyBFI
cl::opt<bool> PGOVerifyBFI("pgo-verify-bfi", cl::init(false), cl::Hidden, cl::desc("Print out mismatched BFI counts after setting profile metadata " "The print is enabled under -Rpass-analysis=pgo, or " "internal option -pass-remakrs-analysis=pgo.")) static
Referenced by annotateAllFunctions().
PGOVerifyBFICutoff
cl::opt<unsigned> PGOVerifyBFICutoff("pgo-verify-bfi-cutoff", cl::init(5), cl::Hidden, cl::desc("Set the threshold for pgo-verify-bfi: skip the counts whose " "profile count value is below.")) static
Referenced by verifyFuncBFI().
PGOVerifyBFIRatio
cl::opt<unsigned> PGOVerifyBFIRatio("pgo-verify-bfi-ratio", cl::init(2), cl::Hidden, cl::desc("Set the threshold for pgo-verify-bfi: only print out " "mismatched BFI if the difference percentage is greater than " "this value (in percentage).")) static
Referenced by verifyFuncBFI().
PGOVerifyHotBFI
cl::opt<bool> PGOVerifyHotBFI("pgo-verify-hot-bfi", cl::init(false), cl::Hidden, cl::desc("Print out the non-match BFI count if a hot raw profile count " "becomes non-hot, or a cold raw profile count becomes hot. " "The print is enabled under -Rpass-analysis=pgo, or " "internal option -pass-remakrs-analysis=pgo.")) static
Referenced by annotateAllFunctions(), and verifyFuncBFI().
PGOViewRawCounts
cl::opt<PGOViewCountsType> PGOViewRawCounts("pgo-view-raw-counts", cl::Hidden, cl::desc("A boolean option to show CFG dag or text " "with raw profile counts from " "profile data. See also option " "-pgo-view-counts. To limit graph " "display to only one function, use " "filtering option -view-bfi-func-name."), cl::values(clEnumValN(PGOVCT_None, "none", "do not show."), clEnumValN(PGOVCT_Graph, "graph", "show a graph."), clEnumValN(PGOVCT_Text, "text", "show in text."))) static
Referenced by annotateAllFunctions().
PGOWarnMissing
cl::opt<bool> PGOWarnMissing("pgo-warn-missing-function", cl::init(false), cl::Hidden, cl::desc("Use this option to turn on/off " "warnings about missing profile data for " "functions.")) static
ValueProfKindDescr
const char* ValueProfKindDescr[] static
Initial value:
= {
#define VALUE_PROF_KIND(Enumerator, Value, Descr)
}
Definition at line 367 of file PGOInstrumentation.cpp.
Referenced by instrumentOneFunc().