LLVM: lib/Target/DirectX/DirectXIRPasses/PointerTypeAnalysis.cpp File Reference
PointerTypeAnalysis.cpp File Reference
#include "PointerTypeAnalysis.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
Functions
static Type * classifyConstantWithOpaquePtr (const Constant *C, PointerTypeMap &Map)
static void classifyGlobalCtorPointerType (const GlobalVariable &GV, PointerTypeMap &Map)
Function Documentation
classifyConstantWithOpaquePtr()
static Type* classifyConstantWithOpaquePtr (const Constant * C, PointerTypeMap & Map) static
Definition at line 120 of file PointerTypeAnalysis.cpp.
References assert(), llvm::SmallVectorImpl< T >::emplace_back(), F, llvm::TypedPointerType::get(), llvm::StructType::get(), llvm::ArrayType::get(), llvm::VectorType::get(), llvm::Constant::getAggregateElement(), llvm::Type::getInt8Ty(), llvm::Type::getPointerAddressSpace(), and I.
Referenced by classifyGlobalCtorPointerType().
classifyGlobalCtorPointerType()
static void classifyGlobalCtorPointerType (const GlobalVariable & GV, PointerTypeMap & Map) static
Definition at line 178 of file PointerTypeAnalysis.cpp.
References classifyConstantWithOpaquePtr(), llvm::TypedPointerType::get(), llvm::GlobalVariable::getInitializer(), llvm::Type::getPointerAddressSpace(), and llvm::GlobalValue::getType().
Referenced by llvm::dxil::PointerTypeAnalysis::run().