LLVM: lib/Transforms/Instrumentation/PoisonChecking.cpp File Reference
PoisonChecking.cpp File Reference
#include "llvm/Transforms/Instrumentation/PoisonChecking.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "poison-checking"
Functions
static bool isConstantFalse (Value *V)
static Value * buildOrChain (IRBuilder<> &B, ArrayRef< Value * > Ops)
static void generateCreationChecksForBinOp (Instruction &I, SmallVectorImpl< Value * > &Checks)
static void generateCreationChecks (Instruction &I, SmallVectorImpl< Value * > &Checks)
Given an instruction which can produce poison on non-poison inputs (i.e.
static Value * getPoisonFor (DenseMap< Value *, Value * > &ValToPoison, Value *V)
static void CreateAssert (IRBuilder<> &B, Value *Cond)
static void CreateAssertNot (IRBuilder<> &B, Value *Cond)
static bool rewrite (Function &F)
Variables
static cl::opt< bool > LocalCheck ("poison-checking-function-local", cl::init(false), cl::desc("Check that returns are non-poison (for testing)"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "poison-checking"
Definition at line 69 of file PoisonChecking.cpp.
Function Documentation
buildOrChain()
static Value* buildOrChain (IRBuilder<> & B, ArrayRef< Value * > Ops) static
Definition at line 84 of file PoisonChecking.cpp.
References B, llvm::drop_begin(), i, isConstantFalse(), and llvm::ArrayRef< T >::size().
Referenced by rewrite().
CreateAssert()
static void CreateAssert (IRBuilder<> & B, Value * Cond) static
Definition at line 236 of file PoisonChecking.cpp.
References assert(), B, Cond, llvm::Type::getInt1Ty(), llvm::Type::getVoidTy(), and M.
Referenced by CreateAssertNot().
CreateAssertNot()
static void CreateAssertNot (IRBuilder<> & B, Value * Cond) static
Definition at line 250 of file PoisonChecking.cpp.
References assert(), B, Cond, and CreateAssert().
Referenced by rewrite().
generateCreationChecks()
static void generateCreationChecks (Instruction & I, SmallVectorImpl< Value * > & Checks) static
Given an instruction which can produce poison on non-poison inputs (i.e.
canCreatePoison returns true), generate runtime checks to produce boolean indicators of when poison would result.
Definition at line 181 of file PoisonChecking.cpp.
References B, Check, generateCreationChecksForBinOp(), llvm::ConstantInt::get(), llvm::Value::getType(), I, and llvm::CmpInst::ICMP_UGE.
Referenced by rewrite().
generateCreationChecksForBinOp()
static void generateCreationChecksForBinOp (Instruction & I, SmallVectorImpl< Value * > & Checks) static
Definition at line 98 of file PoisonChecking.cpp.
References llvm::MCID::Add, assert(), B, Check, llvm::ConstantInt::get(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), I, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, LHS, Mul, and RHS.
Referenced by generateCreationChecks().
getPoisonFor()
static Value* getPoisonFor (DenseMap< Value *, Value * > & ValToPoison, Value * V) static
Definition at line 222 of file PoisonChecking.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::Value::getContext(), and llvm::ConstantInt::getFalse().
Referenced by rewrite().
isConstantFalse()
static bool isConstantFalse (Value * V) static
Definition at line 77 of file PoisonChecking.cpp.
References assert(), llvm::Value::getType(), and llvm::Type::isIntegerTy().
Referenced by buildOrChain().
rewrite()
static bool rewrite (Function & F) static
Definition at line 255 of file PoisonChecking.cpp.
References B, BB, buildOrChain(), llvm::canCreatePoison(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::count(), llvm::PHINode::Create(), CreateAssertNot(), F, generateCreationChecks(), llvm::UndefValue::get(), llvm::getGuaranteedNonPoisonOps(), llvm::Type::getInt1Ty(), getPoisonFor(), i, I, llvm::SmallPtrSetImpl< PtrType >::insert(), LocalCheck, and llvm::propagatesPoison().
Referenced by llvm::ScalarEvolution::convertSCEVToAddRecWithPredicates(), llvm::ScalarEvolution::getLosslessPtrToIntExpr(), llvm::ScalarEvolution::rewriteUsingPredicate(), llvm::PoisonCheckingPass::run(), and llvm::ScalarEvolution::SplitIntoInitAndPostInc().
Variable Documentation
LocalCheck
cl::opt<bool> LocalCheck("poison-checking-function-local", cl::init(false), cl::desc("Check that returns are non-poison (for testing)")) static
Referenced by rewrite().