LLVM: lib/Target/PowerPC/MCTargetDesc/PPCMCTargetDesc.cpp File Reference
PPCMCTargetDesc.cpp File Reference
#include "MCTargetDesc/PPCMCTargetDesc.h"
#include "MCTargetDesc/PPCInstPrinter.h"
#include "MCTargetDesc/PPCMCAsmInfo.h"
#include "PPCELFStreamer.h"
#include "PPCTargetStreamer.h"
#include "PPCXCOFFStreamer.h"
#include "TargetInfo/PowerPCTargetInfo.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionXCOFF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCSymbolXCOFF.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"
#include "PPCGenInstrInfo.inc"
#include "PPCGenSubtargetInfo.inc"
#include "PPCGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createPPCMCInstrInfo ()
static MCRegisterInfo * createPPCMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createPPCMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCAsmInfo * createPPCMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TheTriple, const MCTargetOptions &Options)
static MCStreamer * createPPCELFStreamer (const Triple &T, MCContext &Context, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCStreamer * createPPCXCOFFStreamer (const Triple &T, MCContext &Context, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCTargetStreamer * createAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool isVerboseAsm)
static MCTargetStreamer * createNullTargetStreamer (MCStreamer &S)
static MCTargetStreamer * createObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCInstPrinter * createPPCMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCInstrAnalysis * createPPCMCInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializePowerPCTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 51 of file PPCMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 50 of file PPCMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 57 of file PPCMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 54 of file PPCMCTargetDesc.cpp.
Function Documentation
createAsmTargetStreamer()
static MCTargetStreamer* createAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint, bool isVerboseAsm) static
Definition at line 348 of file PPCMCTargetDesc.cpp.
References OS, and S.
Referenced by LLVMInitializePowerPCTargetMC().
createNullTargetStreamer()
static MCTargetStreamer* createNullTargetStreamer (MCStreamer & S) static
Definition at line 355 of file PPCMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializePowerPCTargetMC().
createObjectTargetStreamer()
static MCTargetStreamer* createObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 360 of file PPCMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getTargetTriple(), and S.
Referenced by LLVMInitializePowerPCTargetMC().
createPPCELFStreamer()
static MCStreamer* createPPCELFStreamer (const Triple & T, MCContext & Context, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 119 of file PPCMCTargetDesc.cpp.
References Context, llvm::createPPCELFStreamer(), Emitter, and move.
createPPCMCAsmInfo()
static MCAsmInfo* createPPCMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TheTriple, const MCTargetOptions & Options) static
Definition at line 97 of file PPCMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::Triple::getArch(), llvm::Triple::isOSBinFormatXCOFF(), MRI, llvm::Triple::ppc64, and llvm::Triple::ppc64le.
Referenced by LLVMInitializePowerPCTargetMC().
createPPCMCInstPrinter()
static MCInstPrinter* createPPCMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 369 of file PPCMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializePowerPCTargetMC().
createPPCMCInstrAnalysis()
static MCInstrAnalysis* createPPCMCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 398 of file PPCMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializePowerPCTargetMC().
createPPCMCInstrInfo()
static MCInstrInfo* createPPCMCInstrInfo () static
Definition at line 65 of file PPCMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializePowerPCTargetMC().
createPPCMCRegisterInfo()
static MCRegisterInfo* createPPCMCRegisterInfo (const Triple & TT) static
Definition at line 71 of file PPCMCTargetDesc.cpp.
References llvm::Triple::ppc64, llvm::Triple::ppc64le, RA, and X.
Referenced by LLVMInitializePowerPCTargetMC().
createPPCMCSubtargetInfo()
static MCSubtargetInfo* createPPCMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 82 of file PPCMCTargetDesc.cpp.
References llvm::X86AS::FS.
Referenced by LLVMInitializePowerPCTargetMC().
createPPCXCOFFStreamer()
static MCStreamer* createPPCXCOFFStreamer (const Triple & T, MCContext & Context, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 127 of file PPCMCTargetDesc.cpp.
References Context, llvm::createPPCXCOFFStreamer(), Emitter, and move.
LLVMInitializePowerPCTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializePowerPCTargetMC ()
Definition at line 402 of file PPCMCTargetDesc.cpp.
References createAsmTargetStreamer(), createNullTargetStreamer(), createObjectTargetStreamer(), llvm::createPPCAsmBackend(), llvm::createPPCELFStreamer(), createPPCMCAsmInfo(), llvm::createPPCMCCodeEmitter(), createPPCMCInstPrinter(), createPPCMCInstrAnalysis(), createPPCMCInstrInfo(), createPPCMCRegisterInfo(), createPPCMCSubtargetInfo(), llvm::createPPCXCOFFStreamer(), llvm::getThePPC32LETarget(), llvm::getThePPC32Target(), llvm::getThePPC64LETarget(), llvm::getThePPC64Target(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), and llvm::TargetRegistry::RegisterXCOFFStreamer().