LLVM: lib/Target/PowerPC/PPCTargetTransformInfo.cpp File Reference
PPCTargetTransformInfo.cpp File Reference
#include "PPCTargetTransformInfo.h"
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/CostTable.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSchedule.h"
#include "llvm/IR/IntrinsicsPowerPC.h"
#include "llvm/IR/ProfDataUtils.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include "llvm/Transforms/Utils/Local.h"
#include <optional>
Macros
#define DEBUG_TYPE "ppctti"
Functions
static bool isMMAType (Type *Ty)
Variables
static cl::opt< bool > DisablePPCConstHoist ("disable-ppc-constant-hoisting", cl::desc("disable constant hoisting on PPC"), cl::init(false), cl::Hidden)
static cl::opt< bool > EnablePPCColdCC ("ppc-enable-coldcc", cl::Hidden, cl::init(false), cl::desc("Enable using coldcc calling conv for cold " "internal functions"))
static cl::opt< bool > LsrNoInsnsCost ("ppc-lsr-no-insns-cost", cl::Hidden, cl::init(false), cl::desc("Do not add instruction count to lsr cost model"))
static cl::opt< unsigned > SmallCTRLoopThreshold ("min-ctr-loop-threshold", cl::init(4), cl::Hidden, cl::desc("Loops with a constant trip count smaller than " "this value will not use the count register."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppctti"
Definition at line 28 of file PPCTargetTransformInfo.cpp.
Function Documentation
isMMAType()
static bool isMMAType (Type * Ty) static
Definition at line 320 of file PPCTargetTransformInfo.cpp.
References llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isVectorTy().
Referenced by llvm::PPCTTIImpl::vectorCostAdjustmentFactor().
Variable Documentation
DisablePPCConstHoist
cl::opt<bool> DisablePPCConstHoist("disable-ppc-constant-hoisting", cl::desc("disable constant hoisting on PPC"), cl::init(false), cl::Hidden) static
Referenced by llvm::PPCTTIImpl::getIntImmCost(), llvm::PPCTTIImpl::getIntImmCostInst(), and llvm::PPCTTIImpl::getIntImmCostIntrin().
EnablePPCColdCC
cl::opt<bool> EnablePPCColdCC("ppc-enable-coldcc", cl::Hidden, cl::init(false), cl::desc("Enable using coldcc calling conv for cold " "internal functions")) static
Referenced by llvm::PPCTTIImpl::useColdCCForColdCall().
LsrNoInsnsCost
cl::opt<bool> LsrNoInsnsCost("ppc-lsr-no-insns-cost", cl::Hidden, cl::init(false), cl::desc("Do not add instruction count to lsr cost model")) static
Referenced by llvm::PPCTTIImpl::isLSRCostLess().
SmallCTRLoopThreshold
cl::opt<unsigned> SmallCTRLoopThreshold("min-ctr-loop-threshold", cl::init(4), cl::Hidden, cl::desc("Loops with a constant trip count smaller than " "this value will not use the count register.")) static
Referenced by llvm::PPCTTIImpl::isHardwareLoopProfitable().