LLVM: lib/CodeGen/ReachingDefAnalysis.cpp File Reference
ReachingDefAnalysis.cpp File Reference
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/ReachingDefAnalysis.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "reaching-deps-analysis"
Functions
INITIALIZE_PASS (ReachingDefAnalysis, DEBUG_TYPE, "ReachingDefAnalysis", false, true) static bool isValidReg(const MachineOperand &MO)
static bool isValidRegUse (const MachineOperand &MO)
static bool isValidRegUseOf (const MachineOperand &MO, MCRegister PhysReg, const TargetRegisterInfo *TRI)
static bool isValidRegDef (const MachineOperand &MO)
static bool isValidRegDefOf (const MachineOperand &MO, MCRegister PhysReg, const TargetRegisterInfo *TRI)
static bool mayHaveSideEffects (MachineInstr &MI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "reaching-deps-analysis"
Definition at line 19 of file ReachingDefAnalysis.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (ReachingDefAnalysis , DEBUG_TYPE , "ReachingDefAnalysis" , false , true) const &
Definition at line 22 of file ReachingDefAnalysis.cpp.
isValidRegDef()
static bool isValidRegDef (const MachineOperand & MO) static
Definition at line 40 of file ReachingDefAnalysis.cpp.
References llvm::MachineOperand::isDef().
Referenced by llvm::ReachingDefAnalysis::collectKilledOperands(), and isValidRegDefOf().
isValidRegDefOf()
static bool isValidRegDefOf (const MachineOperand & MO, MCRegister PhysReg, const TargetRegisterInfo * TRI) static
Definition at line 44 of file ReachingDefAnalysis.cpp.
References llvm::MachineOperand::getReg(), isValidRegDef(), llvm::TargetRegisterInfo::regsOverlap(), and TRI.
Referenced by llvm::ReachingDefAnalysis::getLocalLiveOutMIDef(), llvm::ReachingDefAnalysis::isReachingDefLiveOut(), and llvm::ReachingDefAnalysis::isSafeToDefRegAt().
isValidRegUse()
static bool isValidRegUse (const MachineOperand & MO) static
Definition at line 29 of file ReachingDefAnalysis.cpp.
References llvm::MachineOperand::isUse().
Referenced by llvm::ReachingDefAnalysis::collectKilledOperands(), and isValidRegUseOf().
isValidRegUseOf()
static bool isValidRegUseOf (const MachineOperand & MO, MCRegister PhysReg, const TargetRegisterInfo * TRI) static
Definition at line 33 of file ReachingDefAnalysis.cpp.
References llvm::MachineOperand::getReg(), isValidRegUse(), llvm::TargetRegisterInfo::regsOverlap(), and TRI.
Referenced by llvm::ReachingDefAnalysis::getLiveInUses(), and llvm::ReachingDefAnalysis::getReachingLocalUses().
mayHaveSideEffects()
static bool mayHaveSideEffects (MachineInstr & MI) static
Definition at line 546 of file ReachingDefAnalysis.cpp.
References MI.
Referenced by llvm::ReachingDefAnalysis::collectKilledOperands(), and isEphemeralValueOf().