LLVM: lib/ExecutionEngine/Orc/TargetProcess/RegisterEHFrames.cpp File Reference
RegisterEHFrames.cpp File Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/RegisterEHFrames.h"
#include "llvm/Config/config.h"
#include "llvm/ExecutionEngine/JITSymbol.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/FormatVariadic.h"
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
llvm::orc
Macros
#define DEBUG_TYPE "orc"
Functions
void llvm::orc::__register_frame (const void *)
void llvm::orc::__deregister_frame (const void *)
Error llvm::orc::registerFrameWrapper (const void *P)
Error llvm::orc::deregisterFrameWrapper (const void *P)
Error llvm::orc::registerEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Register frames in the given eh-frame section with libunwind.
Error llvm::orc::deregisterEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Unregister frames in the given eh-frame section with libunwind.
static Error registerEHFrameWrapper (ExecutorAddrRange EHFrame)
static Error deregisterEHFrameWrapper (ExecutorAddrRange EHFrame)
orc::shared::CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (const char *Data, uint64_t Size)
orc::shared::CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (const char *Data, uint64_t Size)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "orc"
Definition at line 21 of file RegisterEHFrames.cpp.
Function Documentation
deregisterEHFrameWrapper()
static Error deregisterEHFrameWrapper (ExecutorAddrRange EHFrame) static
Definition at line 166 of file RegisterEHFrames.cpp.
References llvm::orc::deregisterEHFrameSection(), llvm::orc::ExecutorAddrRange::size(), llvm::orc::ExecutorAddrRange::Start, and llvm::orc::ExecutorAddr::toPtr().
Referenced by llvm_orc_deregisterEHFrameSectionWrapper().
llvm_orc_deregisterEHFrameSectionWrapper()
orc::shared::CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (const char * Data, uint64_t Size)
Definition at line 179 of file RegisterEHFrames.cpp.
References llvm::Data, deregisterEHFrameWrapper(), and handle.
Referenced by llvm::orc::rt_bootstrap::addTo(), and llvm::orc::linkComponents().
llvm_orc_registerEHFrameSectionWrapper()
orc::shared::CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (const char * Data, uint64_t Size)
Definition at line 172 of file RegisterEHFrames.cpp.
References llvm::Data, handle, and registerEHFrameWrapper().
Referenced by llvm::orc::rt_bootstrap::addTo(), and llvm::orc::linkComponents().
registerEHFrameWrapper()
static Error registerEHFrameWrapper (ExecutorAddrRange EHFrame) static
Definition at line 161 of file RegisterEHFrames.cpp.
References llvm::orc::registerEHFrameSection(), llvm::orc::ExecutorAddrRange::size(), llvm::orc::ExecutorAddrRange::Start, and llvm::orc::ExecutorAddr::toPtr().
Referenced by llvm_orc_registerEHFrameSectionWrapper().