LLVM: include/llvm/ExecutionEngine/Orc/TargetProcess/RegisterEHFrames.h File Reference
RegisterEHFrames.h File Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
#include "llvm/Support/Error.h"
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
llvm::orc
Functions
Error llvm::orc::registerEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Register frames in the given eh-frame section with libunwind.
Error llvm::orc::deregisterEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Unregister frames in the given eh-frame section with libunwind.
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (const char *Data, uint64_t Size)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (const char *Data, uint64_t Size)
Function Documentation
llvm_orc_deregisterEHFrameSectionWrapper()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (const char * Data, uint64_t Size)
Definition at line 179 of file RegisterEHFrames.cpp.
References llvm::Data, deregisterEHFrameWrapper(), and handle.
Referenced by llvm::orc::rt_bootstrap::addTo(), and llvm::orc::linkComponents().
llvm_orc_registerEHFrameSectionWrapper()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (const char * Data, uint64_t Size)
Definition at line 172 of file RegisterEHFrames.cpp.
References llvm::Data, handle, and registerEHFrameWrapper().
Referenced by llvm::orc::rt_bootstrap::addTo(), and llvm::orc::linkComponents().