LLVM: lib/CodeGen/RemoveRedundantDebugValues.cpp File Reference
RemoveRedundantDebugValues.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Function.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/PassRegistry.h"
Macros
#define DEBUG_TYPE "removeredundantdebugvalues"
Functions
STATISTIC (NumRemovedBackward, "Number of DBG_VALUEs removed (backward scan)")
STATISTIC (NumRemovedForward, "Number of DBG_VALUEs removed (forward scan)")
INITIALIZE_PASS (RemoveRedundantDebugValues, DEBUG_TYPE, "Remove Redundant DEBUG_VALUE analysis", false, false) RemoveRedundantDebugValues
Default construct and initialize the pass.
static bool reduceDbgValsForwardScan (MachineBasicBlock &MBB)
static bool reduceDbgValsBackwardScan (MachineBasicBlock &MBB)
Detailed Description
The RemoveRedundantDebugValues pass removes redundant DBG_VALUEs that appear in MIR after the register allocator.
Definition in file RemoveRedundantDebugValues.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "removeredundantdebugvalues"
Definition at line 27 of file RemoveRedundantDebugValues.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RemoveRedundantDebugValues , DEBUG_TYPE , "Remove Redundant DEBUG_VALUE analysis" , false , false)
Default construct and initialize the pass.
Definition at line 63 of file RemoveRedundantDebugValues.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeRemoveRedundantDebugValuesPass().
reduceDbgValsBackwardScan()
static bool reduceDbgValsBackwardScan (MachineBasicBlock & MBB) static
Definition at line 156 of file RemoveRedundantDebugValues.cpp.
References llvm::detail::DenseSetImpl< ValueT, SmallDenseMap< ValueT, detail::DenseSetEmpty, 4, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::clear(), llvm::dbgs(), llvm::detail::DenseSetImpl< ValueT, SmallDenseMap< ValueT, detail::DenseSetEmpty, 4, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::erase(), llvm::detail::DenseSetImpl< ValueT, SmallDenseMap< ValueT, detail::DenseSetEmpty, 4, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::MachineOperand::isReg(), LLVM_DEBUG, MBB, MI, and llvm::reverse().
reduceDbgValsForwardScan()
static bool reduceDbgValsForwardScan (MachineBasicBlock & MBB) static
Definition at line 82 of file RemoveRedundantDebugValues.cpp.
References llvm::dbgs(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::erase(), llvm::SmallVectorImpl< T >::erase(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::isReg(), LLVM_DEBUG, MBB, MI, and TRI.
STATISTIC() [1/2]
STATISTIC (NumRemovedBackward , "Number of DBG_VALUEs removed (backward scan)")
STATISTIC() [2/2]
STATISTIC (NumRemovedForward , "Number of DBG_VALUEs removed (forward scan)")