LLVM: lib/Target/RISCV/RISCVSubtarget.cpp File Reference
RISCVSubtarget.cpp File Reference
#include "RISCVSubtarget.h"
#include "GISel/RISCVCallLowering.h"
#include "GISel/RISCVLegalizerInfo.h"
#include "GISel/RISCVRegisterBankInfo.h"
#include "RISCV.h"
#include "RISCVFrameLowering.h"
#include "RISCVMacroFusion.h"
#include "RISCVTargetMachine.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "RISCVGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "riscv-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Variables
static cl::opt< bool > EnableSubRegLiveness ("riscv-enable-subreg-liveness", cl::init(false), cl::Hidden)
static cl::opt< unsigned > RVVVectorLMULMax ("riscv-v-fixed-length-vector-lmul-max", cl::desc("The maximum LMUL value to use for fixed length vectors. " "Fractional LMUL values are not supported."), cl::init(8), cl::Hidden)
static cl::opt< bool > RISCVDisableUsingConstantPoolForLargeInts ("riscv-disable-using-constant-pool-for-large-ints", cl::desc("Disable using constant pool for large integers."), cl::init(false), cl::Hidden)
static cl::opt< unsigned > RISCVMaxBuildIntsCost ("riscv-max-build-ints-cost", cl::desc("The maximum cost used for building integers."), cl::init(0), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-subtarget"
Definition at line 26 of file RISCVSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 29 of file RISCVSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 28 of file RISCVSubtarget.cpp.
Variable Documentation
EnableSubRegLiveness
cl::opt<bool> EnableSubRegLiveness("riscv-enable-subreg-liveness", cl::init(false), cl::Hidden) static
Referenced by llvm::RISCVSubtarget::enableSubRegLiveness().
RISCVDisableUsingConstantPoolForLargeInts
cl::opt<bool> RISCVDisableUsingConstantPoolForLargeInts("riscv-disable-using-constant-pool-for-large-ints", cl::desc("Disable using constant pool for large integers."), cl::init(false), cl::Hidden) static
Referenced by llvm::RISCVSubtarget::useConstantPoolForLargeInts().
RISCVMaxBuildIntsCost
cl::opt<unsigned> RISCVMaxBuildIntsCost("riscv-max-build-ints-cost", cl::desc("The maximum cost used for building integers."), cl::init(0), cl::Hidden) static
Referenced by llvm::RISCVSubtarget::getMaxBuildIntsCost().
RVVVectorLMULMax
cl::opt<unsigned> RVVVectorLMULMax("riscv-v-fixed-length-vector-lmul-max", cl::desc("The maximum LMUL value to use for fixed length vectors. " "Fractional LMUL values are not supported."), cl::init(8), cl::Hidden) static
Referenced by llvm::RISCVSubtarget::getMaxLMULForFixedLengthVectors().