LLVM: lib/Target/RISCV/MCA/RISCVCustomBehaviour.cpp File Reference
RISCVCustomBehaviour.cpp File Reference
#include "RISCVCustomBehaviour.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "RISCVInstrInfo.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Debug.h"
#include "RISCVGenSearchableTables.inc"
Classes
struct RISCVVInversePseudosTable::PseudoInfo
Namespaces
RISCVVInversePseudosTable
llvm
This is an optimization pass for GlobalISel generic memory operations.
llvm::mca
Macros
#define DEBUG_TYPE "llvm-mca-riscv-custombehaviour"
#define GET_RISCVVInversePseudosTable_IMPL
#define GET_RISCVVInversePseudosTable_DECL
Functions
static InstrumentManager * createRISCVInstrumentManager (const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVTargetMCA ()
Extern function to initialize the targets for the RISCV backend.
Detailed Description
This file implements methods from the RISCVCustomBehaviour class.
Definition in file RISCVCustomBehaviour.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "llvm-mca-riscv-custombehaviour"
Definition at line 21 of file RISCVCustomBehaviour.cpp.
GET_RISCVVInversePseudosTable_DECL
#define GET_RISCVVInversePseudosTable_DECL
Definition at line 37 of file RISCVCustomBehaviour.cpp.
GET_RISCVVInversePseudosTable_IMPL
#define GET_RISCVVInversePseudosTable_IMPL
Definition at line 36 of file RISCVCustomBehaviour.cpp.
Function Documentation
createRISCVInstrumentManager()
static InstrumentManager* createRISCVInstrumentManager (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) static
Definition at line 137 of file RISCVCustomBehaviour.cpp.
Referenced by LLVMInitializeRISCVTargetMCA().
LLVMInitializeRISCVTargetMCA()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVTargetMCA ()
Extern function to initialize the targets for the RISCV backend.
Definition at line 143 of file RISCVCustomBehaviour.cpp.
References createRISCVInstrumentManager(), llvm::getTheRISCV32Target(), llvm::getTheRISCV64Target(), and llvm::TargetRegistry::RegisterInstrumentManager().