LLVM: lib/Target/RISCV/RISCVMergeBaseOffset.cpp File Reference
RISCVMergeBaseOffset.cpp File Reference
#include "RISCV.h"
#include "RISCVTargetMachine.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Debug.h"
#include "llvm/Target/TargetOptions.h"
#include <optional>
#include <set>
Macros
#define DEBUG_TYPE "riscv-merge-base-offset"
#define RISCV_MERGE_BASE_OFFSET_NAME "RISCV Merge Base Offset"
Functions
INITIALIZE_PASS (RISCVMergeBaseOffsetOpt, DEBUG_TYPE, RISCV_MERGE_BASE_OFFSET_NAME, false, false) bool RISCVMergeBaseOffsetOpt
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-merge-base-offset"
Definition at line 25 of file RISCVMergeBaseOffset.cpp.
RISCV_MERGE_BASE_OFFSET_NAME
#define RISCV_MERGE_BASE_OFFSET_NAME "RISCV Merge Base Offset"
Definition at line 26 of file RISCVMergeBaseOffset.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVMergeBaseOffsetOpt , DEBUG_TYPE , RISCV_MERGE_BASE_OFFSET_NAME , false , false)
Definition at line 70 of file RISCVMergeBaseOffset.cpp.
References assert(), llvm::dbgs(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::MachineRegisterInfo::hasOneUse(), llvm::MachineOperand::isCPI(), llvm::MachineOperand::isGlobal(), LLVM_DEBUG, llvm::RISCVII::MO_HI, llvm::RISCVII::MO_LO, llvm::MachineOperand::MO_MCSymbol, llvm::RISCVII::MO_PCREL_HI, llvm::RISCVII::MO_PCREL_LO, MRI, and llvm::MachineRegisterInfo::use_instr_begin().