LLVM: lib/Support/RISCVISAInfo.cpp File Reference
RISCVISAInfo.cpp File Reference
#include "llvm/Support/RISCVISAInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include <array>
#include <optional>
#include <string>
#include <vector>
Classes
struct ImpliedExtsEntry
struct CombinedExtsEntry
Functions
static bool stripExperimentalPrefix (StringRef &Ext)
static size_t findFirstNonVersionCharacter (StringRef Ext)
static std::optional< RISCVExtensionVersion > findDefaultVersion (StringRef ExtName)
static StringRef getExtensionTypeDesc (StringRef Ext)
static StringRef getExtensionType (StringRef Ext)
static std::optional< RISCVExtensionVersion > isExperimentalExtension (StringRef Ext)
static int singleLetterExtensionRank (char Ext)
static int multiLetterExtensionRank (const std::string &ExtName)
static Error getExtensionVersion (StringRef Ext, StringRef In, unsigned &Major, unsigned &Minor, unsigned &ConsumeLength, bool EnableExperimentalExtension, bool ExperimentalExtensionVersionCheck)
Variables
static constexpr StringLiteral AllStdExts = "mafdqlcbkjtpvnh"
static const RISCVSupportedExtension SupportedExtensions []
static const RISCVSupportedExtension SupportedExperimentalExtensions []
static const char * ImpliedExtsV [] = {"zvl128b", "zve64d", "f", "d"}
static const char * ImpliedExtsZfhmin [] = {"f"}
static const char * ImpliedExtsZfh [] = {"f"}
static const char * ImpliedExtsZdinx [] = {"zfinx"}
static const char * ImpliedExtsZhinxmin [] = {"zfinx"}
static const char * ImpliedExtsZhinx [] = {"zfinx"}
static const char * ImpliedExtsZve64d [] = {"zve64f"}
static const char * ImpliedExtsZve64f [] = {"zve64x", "zve32f"}
static const char * ImpliedExtsZve64x [] = {"zve32x", "zvl64b"}
static const char * ImpliedExtsZve32f [] = {"zve32x"}
static const char * ImpliedExtsZve32x [] = {"zvl32b"}
static const char * ImpliedExtsZvl65536b [] = {"zvl32768b"}
static const char * ImpliedExtsZvl32768b [] = {"zvl16384b"}
static const char * ImpliedExtsZvl16384b [] = {"zvl8192b"}
static const char * ImpliedExtsZvl8192b [] = {"zvl4096b"}
static const char * ImpliedExtsZvl4096b [] = {"zvl2048b"}
static const char * ImpliedExtsZvl2048b [] = {"zvl1024b"}
static const char * ImpliedExtsZvl1024b [] = {"zvl512b"}
static const char * ImpliedExtsZvl512b [] = {"zvl256b"}
static const char * ImpliedExtsZvl256b [] = {"zvl128b"}
static const char * ImpliedExtsZvl128b [] = {"zvl64b"}
static const char * ImpliedExtsZvl64b [] = {"zvl32b"}
static const char * ImpliedExtsZk [] = {"zkn", "zkt", "zkr"}
static const char * ImpliedExtsZkn []
static const char * ImpliedExtsZks [] = {"zbkb", "zbkc", "zbkx", "zksed", "zksh"}
static const char * ImpliedExtsZvfh [] = {"zve32f"}
static const char * ImpliedExtsXTHeadVdot [] = {"v"}
static const char * ImpliedExtsZcb [] = {"zca"}
static constexpr ImpliedExtsEntry ImpliedExts []
static constexpr CombinedExtsEntry CombineIntoExts []
Function Documentation
findDefaultVersion()
static std::optional<RISCVExtensionVersion> findDefaultVersion (StringRef ExtName) static
Definition at line 171 of file RISCVISAInfo.cpp.
References llvm::ArrayRef(), llvm::find_if(), SupportedExperimentalExtensions, and SupportedExtensions.
Referenced by getExtensionVersion(), and llvm::RISCVISAInfo::parseArchString().
findFirstNonVersionCharacter()
static size_t findFirstNonVersionCharacter (StringRef Ext) static
Definition at line 145 of file RISCVISAInfo.cpp.
References assert(), llvm::MipsISD::Ext, and isDigit().
Referenced by llvm::RISCVISAInfo::parseArchString().
getExtensionType()
static StringRef getExtensionType (StringRef Ext) static
Definition at line 207 of file RISCVISAInfo.cpp.
References llvm::MipsISD::Ext.
Referenced by llvm::RISCVISAInfo::parseArchString().
getExtensionTypeDesc()
static StringRef getExtensionTypeDesc (StringRef Ext) static
Definition at line 195 of file RISCVISAInfo.cpp.
References llvm::MipsISD::Ext.
Referenced by llvm::RISCVISAInfo::parseArchString().
getExtensionVersion()
static Error getExtensionVersion (StringRef Ext, StringRef In, unsigned & Major, unsigned & Minor, unsigned & ConsumeLength, bool EnableExperimentalExtension, bool ExperimentalExtensionVersionCheck) static
Definition at line 377 of file RISCVISAInfo.cpp.
References llvm::createStringError(), llvm::StringRef::empty(), llvm::MipsISD::Ext, findDefaultVersion(), llvm::StringRef::getAsInteger(), llvm::tgtok::In, llvm::invalid_argument, isDigit(), isExperimentalExtension(), llvm::RISCVISAInfo::isSupportedExtension(), llvm::StringRef::size(), llvm::StringRef::str(), and llvm::Error::success().
Referenced by llvm::RISCVISAInfo::parseArchString().
isExperimentalExtension()
static std::optional<RISCVExtensionVersion> isExperimentalExtension (StringRef Ext) static
Definition at line 220 of file RISCVISAInfo.cpp.
References llvm::sys::path::end(), llvm::MipsISD::Ext, llvm::find_if(), and SupportedExperimentalExtensions.
Referenced by getExtensionVersion(), llvm::RISCVISAInfo::toFeatures(), and llvm::RISCVISAInfo::toFeatureVector().
multiLetterExtensionRank()
static int multiLetterExtensionRank (const std::string & ExtName) static
Definition at line 288 of file RISCVISAInfo.cpp.
References assert(), llvm_unreachable, and singleLetterExtensionRank().
Referenced by llvm::RISCVISAInfo::compareExtension().
singleLetterExtensionRank()
static int singleLetterExtensionRank (char Ext) static
Definition at line 264 of file RISCVISAInfo.cpp.
References AllStdExts, llvm::MipsISD::Ext, llvm::StringRef::find(), llvm::StringRef::npos, and llvm::StringRef::size().
Referenced by llvm::RISCVISAInfo::compareExtension(), and multiLetterExtensionRank().
stripExperimentalPrefix()
static bool stripExperimentalPrefix (StringRef & Ext) static
Definition at line 134 of file RISCVISAInfo.cpp.
References llvm::MipsISD::Ext.
Referenced by llvm::RISCVISAInfo::hasExtension(), llvm::RISCVISAInfo::isSupportedExtensionFeature(), and llvm::RISCVISAInfo::parseFeatures().
Variable Documentation
AllStdExts
constexpr StringLiteral AllStdExts = "mafdqlcbkjtpvnh" static constexpr
Definition at line 40 of file RISCVISAInfo.cpp.
Referenced by llvm::RISCVISAInfo::parseArchString(), and singleLetterExtensionRank().
CombineIntoExts
constexpr CombinedExtsEntry CombineIntoExts[] static constexpr
Initial value:
= {
    {{"zk"}, {ImpliedExtsZk}},
    {{"zkn"}, {ImpliedExtsZkn}},
    {{"zks"}, {ImpliedExtsZks}},
}
Definition at line 924 of file RISCVISAInfo.cpp.
ImpliedExts
constexpr ImpliedExtsEntry ImpliedExts[] static constexpr
Initial value:
= {
    {{"v"}, {ImpliedExtsV}},
    {{"xtheadvdot"}, {ImpliedExtsXTHeadVdot}},
    {{"zcb"}, {ImpliedExtsZcb}},
    {{"zdinx"}, {ImpliedExtsZdinx}},
    {{"zfh"}, {ImpliedExtsZfh}},
    {{"zfhmin"}, {ImpliedExtsZfhmin}},
    {{"zhinx"}, {ImpliedExtsZhinx}},
    {{"zhinxmin"}, {ImpliedExtsZhinxmin}},
    {{"zk"}, {ImpliedExtsZk}},
    {{"zkn"}, {ImpliedExtsZkn}},
    {{"zks"}, {ImpliedExtsZks}},
    {{"zve32f"}, {ImpliedExtsZve32f}},
    {{"zve32x"}, {ImpliedExtsZve32x}},
    {{"zve64d"}, {ImpliedExtsZve64d}},
    {{"zve64f"}, {ImpliedExtsZve64f}},
    {{"zve64x"}, {ImpliedExtsZve64x}},
    {{"zvfh"}, {ImpliedExtsZvfh}},
    {{"zvl1024b"}, {ImpliedExtsZvl1024b}},
    {{"zvl128b"}, {ImpliedExtsZvl128b}},
    {{"zvl16384b"}, {ImpliedExtsZvl16384b}},
    {{"zvl2048b"}, {ImpliedExtsZvl2048b}},
    {{"zvl256b"}, {ImpliedExtsZvl256b}},
    {{"zvl32768b"}, {ImpliedExtsZvl32768b}},
    {{"zvl4096b"}, {ImpliedExtsZvl4096b}},
    {{"zvl512b"}, {ImpliedExtsZvl512b}},
    {{"zvl64b"}, {ImpliedExtsZvl64b}},
    {{"zvl65536b"}, {ImpliedExtsZvl65536b}},
    {{"zvl8192b"}, {ImpliedExtsZvl8192b}},
}
Definition at line 852 of file RISCVISAInfo.cpp.
ImpliedExtsV
const char* ImpliedExtsV[] = {"zvl128b", "zve64d", "f", "d"} static
Definition at line 810 of file RISCVISAInfo.cpp.
ImpliedExtsXTHeadVdot
const char* ImpliedExtsXTHeadVdot[] = {"v"} static
Definition at line 837 of file RISCVISAInfo.cpp.
ImpliedExtsZcb
const char* ImpliedExtsZcb[] = {"zca"} static
Definition at line 838 of file RISCVISAInfo.cpp.
ImpliedExtsZdinx
const char* ImpliedExtsZdinx[] = {"zfinx"} static
Definition at line 813 of file RISCVISAInfo.cpp.
ImpliedExtsZfh
const char* ImpliedExtsZfh[] = {"f"} static
Definition at line 812 of file RISCVISAInfo.cpp.
ImpliedExtsZfhmin
const char* ImpliedExtsZfhmin[] = {"f"} static
Definition at line 811 of file RISCVISAInfo.cpp.
ImpliedExtsZhinx
const char* ImpliedExtsZhinx[] = {"zfinx"} static
Definition at line 815 of file RISCVISAInfo.cpp.
ImpliedExtsZhinxmin
const char* ImpliedExtsZhinxmin[] = {"zfinx"} static
Definition at line 814 of file RISCVISAInfo.cpp.
ImpliedExtsZk
const char* ImpliedExtsZk[] = {"zkn", "zkt", "zkr"} static
Definition at line 832 of file RISCVISAInfo.cpp.
ImpliedExtsZkn
const char* ImpliedExtsZkn[] static
Initial value:
= {"zbkb", "zbkc", "zbkx",
                                       "zkne", "zknd", "zknh"}
Definition at line 833 of file RISCVISAInfo.cpp.
ImpliedExtsZks
const char* ImpliedExtsZks[] = {"zbkb", "zbkc", "zbkx", "zksed", "zksh"} static
Definition at line 835 of file RISCVISAInfo.cpp.
ImpliedExtsZve32f
const char* ImpliedExtsZve32f[] = {"zve32x"} static
Definition at line 819 of file RISCVISAInfo.cpp.
ImpliedExtsZve32x
const char* ImpliedExtsZve32x[] = {"zvl32b"} static
Definition at line 820 of file RISCVISAInfo.cpp.
ImpliedExtsZve64d
const char* ImpliedExtsZve64d[] = {"zve64f"} static
Definition at line 816 of file RISCVISAInfo.cpp.
ImpliedExtsZve64f
const char* ImpliedExtsZve64f[] = {"zve64x", "zve32f"} static
Definition at line 817 of file RISCVISAInfo.cpp.
ImpliedExtsZve64x
const char* ImpliedExtsZve64x[] = {"zve32x", "zvl64b"} static
Definition at line 818 of file RISCVISAInfo.cpp.
ImpliedExtsZvfh
const char* ImpliedExtsZvfh[] = {"zve32f"} static
Definition at line 836 of file RISCVISAInfo.cpp.
ImpliedExtsZvl1024b
const char* ImpliedExtsZvl1024b[] = {"zvl512b"} static
Definition at line 827 of file RISCVISAInfo.cpp.
ImpliedExtsZvl128b
const char* ImpliedExtsZvl128b[] = {"zvl64b"} static
Definition at line 830 of file RISCVISAInfo.cpp.
ImpliedExtsZvl16384b
const char* ImpliedExtsZvl16384b[] = {"zvl8192b"} static
Definition at line 823 of file RISCVISAInfo.cpp.
ImpliedExtsZvl2048b
const char* ImpliedExtsZvl2048b[] = {"zvl1024b"} static
Definition at line 826 of file RISCVISAInfo.cpp.
ImpliedExtsZvl256b
const char* ImpliedExtsZvl256b[] = {"zvl128b"} static
Definition at line 829 of file RISCVISAInfo.cpp.
ImpliedExtsZvl32768b
const char* ImpliedExtsZvl32768b[] = {"zvl16384b"} static
Definition at line 822 of file RISCVISAInfo.cpp.
ImpliedExtsZvl4096b
const char* ImpliedExtsZvl4096b[] = {"zvl2048b"} static
Definition at line 825 of file RISCVISAInfo.cpp.
ImpliedExtsZvl512b
const char* ImpliedExtsZvl512b[] = {"zvl256b"} static
Definition at line 828 of file RISCVISAInfo.cpp.
ImpliedExtsZvl64b
const char* ImpliedExtsZvl64b[] = {"zvl32b"} static
Definition at line 831 of file RISCVISAInfo.cpp.
ImpliedExtsZvl65536b
const char* ImpliedExtsZvl65536b[] = {"zvl32768b"} static
Definition at line 821 of file RISCVISAInfo.cpp.
ImpliedExtsZvl8192b
const char* ImpliedExtsZvl8192b[] = {"zvl4096b"} static
Definition at line 824 of file RISCVISAInfo.cpp.
SupportedExperimentalExtensions
const RISCVSupportedExtension SupportedExperimentalExtensions[] static
Initial value:
= {
    {"zihintntl", RISCVExtensionVersion{0, 2}},
    {"zca", RISCVExtensionVersion{1, 0}},
    {"zcb", RISCVExtensionVersion{1, 0}},
    {"zcd", RISCVExtensionVersion{1, 0}},
    {"zcf", RISCVExtensionVersion{1, 0}},
    {"zvfh", RISCVExtensionVersion{0, 1}},
    {"zawrs", RISCVExtensionVersion{1, 0}},
    {"ztso", RISCVExtensionVersion{0, 1}},
}
Definition at line 122 of file RISCVISAInfo.cpp.
Referenced by findDefaultVersion(), isExperimentalExtension(), llvm::RISCVISAInfo::isSupportedExtension(), llvm::RISCVISAInfo::isSupportedExtensionFeature(), llvm::RISCVISAInfo::parseFeatures(), and llvm::RISCVISAInfo::toFeatures().
SupportedExtensions
const RISCVSupportedExtension SupportedExtensions[] static
Definition at line 42 of file RISCVISAInfo.cpp.
Referenced by findDefaultVersion(), llvm::RISCVISAInfo::isSupportedExtension(), llvm::RISCVISAInfo::isSupportedExtensionFeature(), llvm::RISCVISAInfo::parseFeatures(), and llvm::RISCVISAInfo::toFeatures().