LLVM: lib/Target/RISCV/Disassembler/RISCVDisassembler.cpp File Reference
RISCVDisassembler.cpp File Reference
#include "MCTargetDesc/RISCVBaseInfo.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Endian.h"
#include "RISCVGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "riscv-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
Functions
static MCDisassembler * createRISCVDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVDisassembler ()
static DecodeStatus DecodeGPRRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR16RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR32RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR32CRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR64RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR64CRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRNoX0RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRNoX0X2RegisterClass (MCInst &Inst, uint64_t RegNo, uint32_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRCRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRPF64RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRM2RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRM4RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRM8RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeVMaskReg (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static void addImplySP (MCInst &Inst, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmNonZeroOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmNonZeroOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmOperandAndLsl1 (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeCLUIImmOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeFRMArg (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdRs1ImmZero (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdSImm (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdRs1UImm (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdRs2 (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdRs1Rs2 (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-disassembler"
Definition at line 28 of file RISCVDisassembler.cpp.
Typedef Documentation
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 30 of file RISCVDisassembler.cpp.
Function Documentation
addImplySP()
static void addImplySP (MCInst & Inst, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 263 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCInst::getOpcode().
Referenced by decodeSImmOperand(), and decodeUImmOperand().
createRISCVDisassembler()
static MCDisassembler* createRISCVDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 47 of file RISCVDisassembler.cpp.
Referenced by LLVMInitializeRISCVDisassembler().
decodeCLUIImmOperand()
static DecodeStatus decodeCLUIImmOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 331 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and llvm::MCDisassembler::Success.
DecodeFPR16RegisterClass()
static DecodeStatus DecodeFPR16RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 76 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR32CRegisterClass()
static DecodeStatus DecodeFPR32CRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 98 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR32RegisterClass()
static DecodeStatus DecodeFPR32RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 87 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR64CRegisterClass()
static DecodeStatus DecodeFPR64CRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 120 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR64RegisterClass()
static DecodeStatus DecodeFPR64RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 109 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
decodeFRMArg()
static DecodeStatus decodeFRMArg (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 342 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::RISCVMatInt::Imm, llvm::RISCVFPRndMode::isValidRoundingMode(), and llvm::MCDisassembler::Success.
DecodeGPRCRegisterClass()
static DecodeStatus DecodeGPRCRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 151 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeGPRNoX0RegisterClass()
static DecodeStatus DecodeGPRNoX0RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 131 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCDisassembler::Fail.
Referenced by DecodeGPRNoX0X2RegisterClass(), and decodeRVCInstrRdRs1ImmZero().
DecodeGPRNoX0X2RegisterClass()
static DecodeStatus DecodeGPRNoX0X2RegisterClass (MCInst & Inst, uint64_t RegNo, uint32_t Address, const MCDisassembler * Decoder) static
Definition at line 142 of file RISCVDisassembler.cpp.
References DecodeGPRNoX0RegisterClass(), and llvm::MCDisassembler::Fail.
DecodeGPRPF64RegisterClass()
static DecodeStatus DecodeGPRPF64RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 162 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeGPRRegisterClass()
static DecodeStatus DecodeGPRRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 61 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCSubtargetInfo::getFeatureBits(), llvm::MCDisassembler::getSubtargetInfo(), and llvm::MCDisassembler::Success.
Referenced by addImplySP(), DecodeGPRNoX0RegisterClass(), decodeRVCInstrRdRs1Rs2(), and decodeRVCInstrRdRs2().
decodeRVCInstrRdRs1ImmZero()
static DecodeStatus decodeRVCInstrRdRs1ImmZero (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 374 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), DecodeGPRNoX0RegisterClass(), llvm::MCInst::getOperand(), Insn, and llvm::MCDisassembler::Success.
decodeRVCInstrRdRs1Rs2()
static DecodeStatus decodeRVCInstrRdRs1Rs2 (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 421 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), DecodeGPRRegisterClass(), llvm::MCInst::getOperand(), Insn, and llvm::MCDisassembler::Success.
decodeRVCInstrRdRs1UImm()
static DecodeStatus decodeRVCInstrRdRs1UImm (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 398 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), llvm::MCInst::getOperand(), Insn, and llvm::MCDisassembler::Success.
decodeRVCInstrRdRs2()
static DecodeStatus decodeRVCInstrRdRs2 (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 411 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), Insn, and llvm::MCDisassembler::Success.
decodeRVCInstrRdSImm()
static DecodeStatus decodeRVCInstrRdSImm (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 386 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), Insn, and llvm::MCDisassembler::Success.
decodeSImmNonZeroOperand()
template<unsigned N> static DecodeStatus decodeSImmNonZeroOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 311 of file RISCVDisassembler.cpp.
References llvm::MCDisassembler::Fail, and llvm::RISCVMatInt::Imm.
decodeSImmOperand()
template<unsigned N> static DecodeStatus decodeSImmOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 300 of file RISCVDisassembler.cpp.
References addImplySP(), llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and llvm::MCDisassembler::Success.
decodeSImmOperandAndLsl1()
template<unsigned N> static DecodeStatus decodeSImmOperandAndLsl1 (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 320 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and llvm::MCDisassembler::Success.
decodeUImmNonZeroOperand()
template<unsigned N> static DecodeStatus decodeUImmNonZeroOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 291 of file RISCVDisassembler.cpp.
References llvm::MCDisassembler::Fail, and llvm::RISCVMatInt::Imm.
decodeUImmOperand()
template<unsigned N> static DecodeStatus decodeUImmOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 281 of file RISCVDisassembler.cpp.
References addImplySP(), llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::RISCVMatInt::Imm, and llvm::MCDisassembler::Success.
decodeVMaskReg()
static DecodeStatus decodeVMaskReg (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 244 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeVRM2RegisterClass()
static DecodeStatus DecodeVRM2RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 184 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), and llvm::MCDisassembler::Success.
DecodeVRM4RegisterClass()
static DecodeStatus DecodeVRM4RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 204 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), and llvm::MCDisassembler::Success.
DecodeVRM8RegisterClass()
static DecodeStatus DecodeVRM8RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 224 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), and llvm::MCDisassembler::Success.
DecodeVRRegisterClass()
static DecodeStatus DecodeVRRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 173 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
LLVMInitializeRISCVDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVDisassembler ()
Definition at line 53 of file RISCVDisassembler.cpp.
References createRISCVDisassembler(), llvm::getTheRISCV32Target(), llvm::getTheRISCV64Target(), and llvm::TargetRegistry::RegisterMCDisassembler().