LLVM: lib/Target/RISCV/RISCVFrameLowering.cpp File Reference
RISCVFrameLowering.cpp File Reference
#include "RISCVFrameLowering.h"
#include "RISCVMachineFunctionInfo.h"
#include "RISCVSubtarget.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/Support/LEB128.h"
#include <algorithm>
Functions
static void emitSCSPrologue (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL)
static void emitSCSEpilogue (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL)
static int getLibCallID (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static const char * getSpillLibCallName (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static const char * getRestoreLibCallName (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static Register getFPReg (const RISCVSubtarget &STI)
static Register getSPReg (const RISCVSubtarget &STI)
static SmallVector< CalleeSavedInfo, 8 > getNonLibcallCSI (const MachineFunction &MF, const std::vector< CalleeSavedInfo > &CSI)
static MCCFIInstruction createDefCFAExpression (const TargetRegisterInfo &TRI, Register Reg, uint64_t FixedOffset, uint64_t ScalableOffset)
static unsigned getScavSlotsNumForRVV (MachineFunction &MF)
static bool hasRVVFrameObject (const MachineFunction &MF)
static unsigned estimateFunctionSizeInBytes (const MachineFunction &MF, const RISCVInstrInfo &TII)
Function Documentation
createDefCFAExpression()
static MCCFIInstruction createDefCFAExpression (const TargetRegisterInfo & TRI, Register Reg, uint64_t FixedOffset, uint64_t ScalableOffset) static
Definition at line 347 of file RISCVFrameLowering.cpp.
References llvm::SmallString< InternalLen >::append(), assert(), llvm::MCCFIInstruction::createEscape(), llvm::encodeSLEB128(), llvm::encodeULEB128(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::printReg(), llvm::SmallString< InternalLen >::str(), and TRI.
emitSCSEpilogue()
static void emitSCSEpilogue (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL) static
Definition at line 83 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::RegState::Define, llvm::LLVMContext::diagnose(), DL, llvm::MachineInstr::FrameDestroy, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::Function::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::CalleeSavedInfo::getReg(), llvm::RISCVABI::getSCSPReg(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasFnAttribute(), llvm::ARM_MB::LD, MBB, MI, llvm::none_of(), llvm::MachineInstrBuilder::setMIFlag(), and TII.
Referenced by llvm::RISCVFrameLowering::emitEpilogue().
emitSCSPrologue()
static void emitSCSPrologue (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL) static
Definition at line 32 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::RegState::Define, llvm::LLVMContext::diagnose(), DL, llvm::MachineInstr::FrameSetup, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::Function::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::CalleeSavedInfo::getReg(), llvm::RISCVABI::getSCSPReg(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasFnAttribute(), MBB, MI, llvm::none_of(), llvm::MachineInstrBuilder::setMIFlag(), and TII.
Referenced by llvm::RISCVFrameLowering::emitPrologue().
estimateFunctionSizeInBytes()
static unsigned estimateFunctionSizeInBytes (const MachineFunction & MF, const RISCVInstrInfo & TII) static
Definition at line 1036 of file RISCVFrameLowering.cpp.
References MBB, MI, and TII.
Referenced by llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized().
getFPReg()
static Register getFPReg (const RISCVSubtarget & STI) static
Definition at line 295 of file RISCVFrameLowering.cpp.
Referenced by llvm::RISCVFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitPrologue(), and llvm::RISCVFrameLowering::getFrameIndexReference().
getLibCallID()
static int getLibCallID (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 137 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::Register::id(), llvm_unreachable, and llvm::max().
Referenced by llvm::RISCVFrameLowering::emitPrologue(), getRestoreLibCallName(), and getSpillLibCallName().
getNonLibcallCSI()
static SmallVector<CalleeSavedInfo, 8> getNonLibcallCSI (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 301 of file RISCVFrameLowering.cpp.
References llvm::TargetStackID::Default, llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::getStackID().
Referenced by llvm::RISCVFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), and llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
getRestoreLibCallName()
static const char* getRestoreLibCallName (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 203 of file RISCVFrameLowering.cpp.
References getLibCallID().
Referenced by llvm::RISCVFrameLowering::restoreCalleeSavedRegisters().
getScavSlotsNumForRVV()
static unsigned getScavSlotsNumForRVV (MachineFunction & MF) static
Definition at line 973 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::RISCVSubtarget::hasVInstructions(), llvm::RISCV::isRVVSpill(), llvm::max(), MBB, MI, and llvm::TargetStackID::ScalableVector.
Referenced by llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized().
getSpillLibCallName()
static const char* getSpillLibCallName (const MachineFunction & MF, const std::vector< CalleeSavedInfo > & CSI) static
Definition at line 176 of file RISCVFrameLowering.cpp.
References getLibCallID().
Referenced by llvm::RISCVFrameLowering::spillCalleeSavedRegisters().
getSPReg()
static Register getSPReg (const RISCVSubtarget & STI) static
Definition at line 298 of file RISCVFrameLowering.cpp.
Referenced by llvm::RISCVFrameLowering::emitEpilogue(), and llvm::RISCVFrameLowering::emitPrologue().
hasRVVFrameObject()
static bool hasRVVFrameObject (const MachineFunction & MF) static
Definition at line 1017 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getSubtarget().
Referenced by llvm::RISCVFrameLowering::hasReservedCallFrame(), and llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized().