LLVM: lib/Target/RISCV/RISCVMacroFusion.cpp File Reference
RISCVMacroFusion.cpp File Reference
#include "RISCVMacroFusion.h"
#include "RISCVSubtarget.h"
#include "llvm/CodeGen/MacroFusion.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
Functions
static bool isLUIADDI (const MachineInstr *FirstMI, const MachineInstr &SecondMI)
static bool shouldScheduleAdjacent (const TargetInstrInfo &TII, const TargetSubtargetInfo &TSI, const MachineInstr *FirstMI, const MachineInstr &SecondMI)
Function Documentation
isLUIADDI()
static bool isLUIADDI (const MachineInstr * FirstMI, const MachineInstr & SecondMI) static
Definition at line 25 of file RISCVMacroFusion.cpp.
References llvm::MachineInstr::getMF(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::MachineOperand::isReg(), llvm::Register::isVirtual(), and MRI.
Referenced by shouldScheduleAdjacent().
shouldScheduleAdjacent()
static bool shouldScheduleAdjacent (const TargetInstrInfo & TII, const TargetSubtargetInfo & TSI, const MachineInstr * FirstMI, const MachineInstr & SecondMI) static
Definition at line 59 of file RISCVMacroFusion.cpp.
References isLUIADDI(), and llvm::ARM_MB::ST.