LLVM: lib/Target/RISCV/RISCVGatherScatterLowering.cpp File Reference
RISCVGatherScatterLowering.cpp File Reference
#include "RISCV.h"
#include "RISCVTargetMachine.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsRISCV.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Transforms/Utils/Local.h"
#include <optional>
Macros
#define DEBUG_TYPE "riscv-gather-scatter-lowering"
Functions
INITIALIZE_PASS (RISCVGatherScatterLowering, DEBUG_TYPE, "RISCV gather/scatter lowering pass", false, false) FunctionPass *llvm
static std::pair< Value *, Value * > matchStridedConstant (Constant *StartC)
static std::pair< Value *, Value * > matchStridedStart (Value *Start, IRBuilder<> &Builder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-gather-scatter-lowering"
Definition at line 31 of file RISCVGatherScatterLowering.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVGatherScatterLowering , DEBUG_TYPE , "RISCV gather/scatter lowering pass" , false , false)
Definition at line 83 of file RISCVGatherScatterLowering.cpp.
matchStridedConstant()
static std::pair<Value *, Value *> matchStridedConstant (Constant * StartC) static
Definition at line 109 of file RISCVGatherScatterLowering.cpp.
References llvm::ConstantInt::get(), llvm::Constant::getAggregateElement(), llvm::Value::getType(), llvm::ConstantInt::getValue(), and i.
Referenced by matchStridedStart().
matchStridedStart()
static std::pair<Value *, Value *> matchStridedStart (Value * Start, IRBuilder<> & Builder) static
Definition at line 138 of file RISCVGatherScatterLowering.cpp.
References llvm::MCID::Add, Builder, llvm::ConstantInt::get(), llvm::getSplatValue(), llvm::PatternMatch::match(), and matchStridedConstant().