LLVM: lib/Target/AMDGPU/SIFrameLowering.cpp File Reference
SIFrameLowering.cpp File Reference
#include "SIFrameLowering.h"
#include "AMDGPU.h"
#include "GCNSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/Target/TargetMachine.h"
Classes
class llvm::PrologEpilogSGPRSpillBuilder
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "frame-info"
Functions
static MCRegister findUnusedRegister (MachineRegisterInfo &MRI, const LivePhysRegs &LiveRegs, const TargetRegisterClass &RC)
static MCRegister findScratchNonCalleeSaveRegister (MachineRegisterInfo &MRI, LivePhysRegs &LiveRegs, const TargetRegisterClass &RC, bool Unused=false)
static void getVGPRSpillLaneOrTempRegister (MachineFunction &MF, LivePhysRegs &LiveRegs, Register SGPR, const TargetRegisterClass &RC=AMDGPU::SReg_32_XM0_XEXECRegClass)
static void buildPrologSpill (const GCNSubtarget &ST, const SIRegisterInfo &TRI, const SIMachineFunctionInfo &FuncInfo, LivePhysRegs &LiveRegs, MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, Register SpillReg, int FI, Register FrameReg, int64_t DwordOff=0)
static void buildEpilogRestore (const GCNSubtarget &ST, const SIRegisterInfo &TRI, const SIMachineFunctionInfo &FuncInfo, LivePhysRegs &LiveRegs, MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, Register SpillReg, int FI, Register FrameReg, int64_t DwordOff=0)
static void buildGitPtr (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, const SIInstrInfo *TII, Register TargetReg)
static void initLiveRegs (LivePhysRegs &LiveRegs, const SIRegisterInfo &TRI, const SIMachineFunctionInfo *FuncInfo, MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, bool IsProlog)
static bool allStackObjectsAreDead (const MachineFrameInfo &MFI)
static unsigned getScratchScaleFactor (const GCNSubtarget &ST)
static Register buildScratchExecCopy (LivePhysRegs &LiveRegs, MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, bool IsProlog, bool EnableInactiveLanes)
static bool allSGPRSpillsAreDead (const MachineFunction &MF)
static bool frameTriviallyRequiresSP (const MachineFrameInfo &MFI)
Returns true if the frame will require a reference to the stack pointer.
Variables
static cl::opt< bool > EnableSpillVGPRToAGPR ("amdgpu-spill-vgpr-to-agpr", cl::desc("Enable spilling VGPRs to AGPRs"), cl::ReallyHidden, cl::init(true))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "frame-info"
Definition at line 21 of file SIFrameLowering.cpp.
Function Documentation
allSGPRSpillsAreDead()
static bool allSGPRSpillsAreDead (const MachineFunction & MF) static
Definition at line 1282 of file SIFrameLowering.cpp.
References llvm::SIMachineFunctionInfo::checkIndexInPrologEpilogSGPRSpills(), E, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getStackID(), I, llvm::MachineFrameInfo::isDeadObjectIndex(), and llvm::TargetStackID::SGPRSpill.
Referenced by llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
allStackObjectsAreDead()
static bool allStackObjectsAreDead (const MachineFrameInfo & MFI) static
Definition at line 515 of file SIFrameLowering.cpp.
References E, llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectIndexEnd(), I, and llvm::MachineFrameInfo::isDeadObjectIndex().
Referenced by llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), and llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().
buildEpilogRestore()
static void buildEpilogRestore (const GCNSubtarget & ST, const SIRegisterInfo & TRI, const SIMachineFunctionInfo & FuncInfo, LivePhysRegs & LiveRegs, MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, Register SpillReg, int FI, Register FrameReg, int64_t DwordOff = 0) static
Definition at line 147 of file SIFrameLowering.cpp.
References DL, llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), I, MBB, llvm::MachineMemOperand::MOLoad, llvm::ARM_MB::ST, and TRI.
Referenced by llvm::SIFrameLowering::emitCSRSpillRestores().
buildGitPtr()
static void buildGitPtr (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, const SIInstrInfo * TII, Register TargetReg) static
Definition at line 167 of file SIFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineRegisterInfo::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, llvm::SIMachineFunctionInfo::getGITPtrHigh(), llvm::SIMachineFunctionInfo::getGITPtrLoReg(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterInfo::getSubReg(), I, llvm::RegState::ImplicitDefine, MBB, TII, and TRI.
buildPrologSpill()
static void buildPrologSpill (const GCNSubtarget & ST, const SIRegisterInfo & TRI, const SIMachineFunctionInfo & FuncInfo, LivePhysRegs & LiveRegs, MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, Register SpillReg, int FI, Register FrameReg, int64_t DwordOff = 0) static
Definition at line 124 of file SIFrameLowering.cpp.
References llvm::LivePhysRegs::addReg(), DL, llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), I, llvm::MachineBasicBlock::isLiveIn(), MBB, llvm::MachineMemOperand::MOStore, llvm::LivePhysRegs::removeReg(), llvm::ARM_MB::ST, and TRI.
Referenced by llvm::SIFrameLowering::emitCSRSpillStores().
buildScratchExecCopy()
static Register buildScratchExecCopy (LivePhysRegs & LiveRegs, MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, bool IsProlog, bool EnableInactiveLanes) static
Definition at line 870 of file SIFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::LivePhysRegs::addReg(), llvm::BuildMI(), DL, findScratchNonCalleeSaveRegister(), llvm::MachineFunction::getInfo(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), initLiveRegs(), MBB, MBBI, MRI, llvm::report_fatal_error(), llvm::MachineOperand::setIsDead(), llvm::ARM_MB::ST, TII, and TRI.
Referenced by llvm::SIFrameLowering::emitCSRSpillRestores(), and llvm::SIFrameLowering::emitCSRSpillStores().
findScratchNonCalleeSaveRegister()
static MCRegister findScratchNonCalleeSaveRegister (MachineRegisterInfo & MRI, LivePhysRegs & LiveRegs, const TargetRegisterClass & RC, bool Unused = false) static
Definition at line 45 of file SIFrameLowering.cpp.
References llvm::LivePhysRegs::addReg(), llvm::LivePhysRegs::available(), findUnusedRegister(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), i, and MRI.
Referenced by buildScratchExecCopy(), llvm::SIFrameLowering::emitEpilogue(), and llvm::SIFrameLowering::emitPrologue().
findUnusedRegister()
static MCRegister findUnusedRegister (MachineRegisterInfo & MRI, const LivePhysRegs & LiveRegs, const TargetRegisterClass & RC) static
Definition at line 31 of file SIFrameLowering.cpp.
References llvm::LivePhysRegs::available(), llvm::MachineRegisterInfo::isPhysRegUsed(), and MRI.
Referenced by findScratchNonCalleeSaveRegister(), and getVGPRSpillLaneOrTempRegister().
frameTriviallyRequiresSP()
static bool frameTriviallyRequiresSP (const MachineFrameInfo & MFI) static
Returns true if the frame will require a reference to the stack pointer.
This is the set of conditions common to setting up the stack pointer in a kernel, and for using a frame pointer in a callable function.
FIXME: Should also check hasOpaqueSPAdjustment and if any inline asm references SP.
Definition at line 1702 of file SIFrameLowering.cpp.
References llvm::MachineFrameInfo::hasPatchPoint(), llvm::MachineFrameInfo::hasStackMap(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by llvm::SIFrameLowering::hasFP(), and llvm::SIFrameLowering::requiresStackPointerReference().
getScratchScaleFactor()
static unsigned getScratchScaleFactor (const GCNSubtarget & ST) static
Definition at line 578 of file SIFrameLowering.cpp.
References llvm::ARM_MB::ST.
Referenced by llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::SIFrameLowering::emitEpilogue(), and llvm::SIFrameLowering::emitPrologue().
getVGPRSpillLaneOrTempRegister()
static void getVGPRSpillLaneOrTempRegister (MachineFunction & MF, LivePhysRegs & LiveRegs, Register SGPR, const TargetRegisterClass & RC = AMDGPU::SReg_32_XM0_XEXECRegClass) static
Definition at line 67 of file SIFrameLowering.cpp.
References llvm::LivePhysRegs::addReg(), llvm::SIMachineFunctionInfo::addToPrologEpilogSGPRSpills(), llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPRLane(), llvm::COPY_TO_SCRATCH_SGPR, llvm::dbgs(), findUnusedRegister(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSpillToVGPRLanes(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterInfo::getSpillAlign(), llvm::TargetRegisterInfo::getSpillSize(), llvm::MachineFunction::getSubtarget(), LLVM_DEBUG, llvm::printReg(), llvm::MachineFrameInfo::RemoveStackObject(), llvm::TargetStackID::SGPRSpill, llvm::SPILL_TO_MEM, llvm::SPILL_TO_VGPR_LANE, llvm::ARM_MB::ST, and TRI.
Referenced by llvm::SIFrameLowering::determinePrologEpilogSGPRSaves().
initLiveRegs()
static void initLiveRegs (LivePhysRegs & LiveRegs, const SIRegisterInfo & TRI, const SIMachineFunctionInfo * FuncInfo, MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, bool IsProlog) static
Definition at line 192 of file SIFrameLowering.cpp.
References llvm::LivePhysRegs::addLiveIns(), llvm::LivePhysRegs::addLiveOuts(), llvm::LivePhysRegs::empty(), llvm::LivePhysRegs::init(), MBB, MBBI, llvm::LivePhysRegs::stepBackward(), and TRI.
Referenced by buildScratchExecCopy(), llvm::SIFrameLowering::emitEpilogue(), and llvm::SIFrameLowering::emitPrologue().
Variable Documentation
EnableSpillVGPRToAGPR
cl::opt<bool> EnableSpillVGPRToAGPR("amdgpu-spill-vgpr-to-agpr", cl::desc("Enable spilling VGPRs to AGPRs"), cl::ReallyHidden, cl::init(true)) static
Referenced by llvm::SIFrameLowering::emitPrologue(), and llvm::SIFrameLowering::processFunctionBeforeFrameFinalized().