LLVM: lib/Target/AMDGPU/SILowerControlFlow.cpp File Reference
SILowerControlFlow.cpp File Reference
#include "AMDGPU.h"
#include "GCNSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "si-lower-control-flow"
Functions
INITIALIZE_PASS (SILowerControlFlow, DEBUG_TYPE, "SI lower control flow", false, false) static void setImpSCCDefDead(MachineInstr &MI
assert (ImpDefSCC.getReg()==AMDGPU::SCC &&ImpDefSCC.isDef())
ImpDefSCC setIsDead (IsDead)
static bool isSimpleIf (const MachineInstr &MI, const MachineRegisterInfo *MRI)
Variables
static cl::opt< bool > RemoveRedundantEndcf ("amdgpu-remove-redundant-endcf", cl::init(true), cl::ReallyHidden)
bool IsDead
Detailed Description
This pass lowers the pseudo control flow instructions to real machine instructions.
All control flow is handled using predicated instructions and a predicate stack. Each Scalar ALU controls the operations of 64 Vector ALUs. The Scalar ALU can update the predicate for any of the Vector ALUs by writing to the 64-bit EXEC register (each bit corresponds to a single vector ALU). Typically, for predicates, a vector ALU will write to its bit of the VCC register (like EXEC VCC is 64-bits, one for each Vector ALU) and then the ScalarALU will AND the VCC register with the EXEC to update the predicates.
For example: vcc = V_CMP_GT_F32 vgpr1, vgpr2 sgpr0 = SI_IF vcc vgpr0 = V_ADD_F32 vgpr0, vgpr0 sgpr0 = SI_ELSE sgpr0 vgpr0 = V_SUB_F32 vgpr0, vgpr0 SI_END_CF sgpr0
becomes:
sgpr0 = S_AND_SAVEEXEC_B64 vcc // Save and update the exec mask sgpr0 = S_XOR_B64 sgpr0, exec // Clear live bits from saved exec mask S_CBRANCH_EXECZ label0 // This instruction is an optional // optimization which allows us to // branch if all the bits of // EXEC are zero. vgpr0 = V_ADD_F32 vgpr0, vgpr0 // Do the IF block of the branch
label0: sgpr0 = S_OR_SAVEEXEC_B64 sgpr0 // Restore the exec mask for the Then // block exec = S_XOR_B64 sgpr0, exec // Update the exec mask S_BRANCH_EXECZ label1 // Use our branch optimization // instruction again. vgpr0 = V_SUB_F32 vgpr0, vgpr // Do the THEN block label1: exec = S_OR_B64 exec, sgpr0 // Re-enable saved exec mask bits
Definition in file SILowerControlFlow.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-lower-control-flow"
Definition at line 63 of file SILowerControlFlow.cpp.
Function Documentation
assert()
assert (ImpDefSCC. getReg() = =AMDGPU::SCC &&ImpDefSCC.isDef())
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo(), llvm::AArch64RegisterBankInfo::AArch64RegisterBankInfo(), absoluteSymbolDiff(), llvm::AbstractCallSite::AbstractCallSite(), llvm::GEPOperator::accumulateConstantOffset(), llvm::LiveRegUnits::accumulateUsedDefed(), llvm::GCStatepointInst::actual_arg_begin(), llvm::GCStatepointInst::actual_arg_end(), llvm::orc::IRSymbolMapper::add(), llvm::StringTableBuilder::add(), llvm::orc::IRLayer::add(), llvm::orc::ObjectLayer::add(), llvm::orc::CtorDtorRunner::add(), llvm::SDDbgInfo::add(), false::Chain::add(), llvm::lto::LTO::add(), llvm::PMDataManager::add(), llvm::AliasSetTracker::add(), llvm::LiveRangeUpdater::add(), llvm::APFloat::add(), BoUpSLP::ShuffleInstructionBuilder::add(), llvm::ImutAVLFactory< ImutInfo >::add_internal(), llvm::cflaa::StratifiedSetsBuilder< T >::addAbove(), llvm::X86Operand::addAbsMemOperands(), llvm::jitlink::LinkGraph::addAbsoluteSymbol(), llvm::DWARFLinker::addAccelTableKind(), llvm::AA::PointerInfo::State::addAccess(), addAccessAttr(), llvm::orc::addAliases(), llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addAllocSizeAttrFromRawRepr(), llvm::DwarfUnit::addAnnotation(), llvm::Hexagon_MC::addArchSubtarget(), llvm::AttributeMask::addAttribute(), llvm::OpenMPIRBuilder::addAttributes(), llvm::SSAUpdaterBulk::AddAvailableValue(), llvm::SSAUpdater::AddAvailableValue(), llvm::X86Operand::addAVX512RCOperands(), llvm::ScheduleDAGInstrs::addBarrierChain(), llvm::DominanceFrontierBase< BasicBlock, false >::addBasicBlock(), llvm::LoopBase< BasicBlock, Loop >::addBasicBlockToLoop(), llvm::cflaa::StratifiedSetsBuilder< T >::addBelow(), llvm::LoopBase< BasicBlock, Loop >::addBlockEntry(), llvm::DwarfExpression::addBReg(), llvm::MachineFunction::addCallArgsForwardingRegs(), llvm::memprof::CallStackTrie::addCallStack(), llvm::SwitchInst::addCase(), llvm::SwitchInstProfUpdateWrapper::addCase(), llvm::cl::Option::addCategory(), llvm::DIE::addChild(), llvm::DIE::addChildFront(), llvm::LoopBase< BasicBlock, Loop >::addChildLoop(), llvm::LPMUpdater::addChildLoops(), llvm::RecordKeeper::addClass(), llvm::LandingPadInst::addClause(), llvm::addClonedBlockToLoopInfo(), AddCombineTo64bitMLAL(), addConditions(), addConstantComments(), llvm::DwarfExpression::addConstantFP(), addConstantsToTrack(), llvm::HexagonMCInstrInfo::addConstExtender(), llvm::jitlink::MachOLinkGraphBuilder::addCustomSectionParser(), llvm::SelectionDAGBuilder::addDanglingDebugInfo(), llvm::pdb::DbiStreamBuilder::addDbgStream(), llvm::SelectionDAG::AddDbgValue(), llvm::RecordKeeper::addDef(), llvm::jitlink::LinkGraph::addDefinedSymbol(), llvm::MachineRegisterInfo::addDelegate(), llvm::IndirectBrInst::addDestination(), llvm::FileCollectorBase::addDirectory(), llvm::MachineInstrBuilder::addDisp(), llvm::DomainValue::addDomain(), llvm::X86Operand::addDstIdxOperands(), llvm::jitlink::Block::addEdge(), llvm::PBQP::Graph< RegAllocSolverImpl >::addEdge(), llvm::PBQP::Graph< RegAllocSolverImpl >::addEdgeBypassingCostAllocator(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVRange::addEntry(), XtensaOperand::addExpr(), llvm::DwarfExpression::addExpression(), llvm::jitlink::LinkGraph::addExternalSymbol(), llvm::RecordKeeper::addExtraGlobal(), llvm::CodeViewContext::addFile(), llvm::DwarfExpression::addFragmentOffset(), llvm::addFullAddress(), llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::orc::JITDylib::addGenerator(), llvm::ExecutionEngine::addGlobalMapping(), llvm::X86Operand::addGR16orGR32orGR64Operands(), llvm::X86Operand::addGR32orGR64Operands(), llvm::CatchSwitchInst::addHandler(), llvm::SITargetLowering::AddIMGInit(), XtensaOperand::addImmOperands(), llvm::X86Operand::addImmOperands(), llvm::PMTopLevelManager::addImmutablePass(), llvm::DwarfCompileUnit::addImportedEntity(), addIncomingValuesToPHIs(), llvm::objcopy::elf::SectionIndexSection::addIndex(), llvm::orc::addInitSymbol(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::DbgLabelInstrMap::addInstr(), llvm::mca::MemoryGroup::addInstruction(), llvm::PressureDiffs::addInstruction(), llvm::WinEHFuncInfo::addIPToStateRange(), llvm::orc::LLJIT::addIRModule(), llvm::LiveIntervals::addKillFlags(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::MachineFunction::addLandingPad(), llvm::orc::LLLazyJIT::addLazyIRModule(), llvm::sys::DynamicLibrary::HandleSet::AddLibrary(), llvm::codeview::DebugLinesSubsection::addLineAndColumnInfo(), llvm::cl::parser< const PassInfo * >::addLiteralOption(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::addLiveIn(), addLiveInRegs(), llvm::addLiveIns(), llvm::VPlan::addLiveOut(), llvm::DwarfCompileUnit::addLocationAttribute(), addLoopMetadata(), llvm::DwarfExpression::addMachineRegExpression(), addMappingsFromTLI(), llvm::X86Operand::addMaskPairOperands(), llvm::X86Operand::addMemOffsOperands(), llvm::X86Operand::addMemOperands(), llvm::MachineInstrBuilder::addMetadata(), llvm::Value::addMetadata(), llvm::DbgVariable::addMMIEntry(), llvm::ModuleSymbolTable::addModule(), llvm::LTOCodeGenerator::addModule(), llvm::AccelTable< llvm::DWARF5AccelTableStaticData >::addName(), llvm::pdb::PDBFileBuilder::addNamedStream(), llvm::DominatorTreeBase< BasicBlock, false >::addNewBlock(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::addNewSection(), llvm::objcopy::elf::Object::addNewSymbolTable(), llvm::DataDependenceGraph::addNode(), llvm::GISelInstProfileBuilder::addNodeIDMachineOperand(), llvm::SymbolTableListTraits< ValueSubClass >::addNodeToList(), addNonConstUser(), llvm::IRMover::IdentifiedStructTypeSet::addNonOpaque(), addNoRecurseAttrsTopDown(), llvm::logicalview::LVScope::addObject(), llvm::orc::LLJIT::addObjectFile(), llvm::IRMover::IdentifiedStructTypeSet::addOpaque(), llvm::MachineInstr::addOperand(), addOperands(), addOpsFromMDNode(), llvm::CallBase::addParamAttr(), llvm::AttributeList::addParamAttribute(), llvm::TargetPassConfig::addPass(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::TargetPassConfig::addPassesToHandleExceptions(), llvm::CodeGenPassBuilder< DerivedT >::addPassesToHandleExceptions(), llvm::PassBuilder::addPGOInstrPassesForO0(), llvm::rdf::BlockNode::addPhi(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::SIScheduleBlock::addPred(), llvm::SUnit::addPred(), llvm::ScheduleDAGTopologicalSort::AddPred(), llvm::ScalarEvolution::ExitLimit::addPredicate(), llvm::MCPseudoProbeInlineTree::addPseudoProbe(), llvm::pdb::GSIStreamBuilder::addPublicSymbols(), llvm::LivePhysRegs::addReg(), llvm::MachineInstrBuilder::addReg(), llvm::DwarfExpression::addReg(), llvm::MachineRegisterInfo::addRegAllocationHint(), addRegDescribedVar(), llvm::TargetLoweringBase::addRegisterClass(), llvm::mca::RegisterFile::addRegisterRead(), llvm::mca::addRegisterReadWrite(), llvm::mca::RegisterFile::addRegisterWrite(), addRegLanes(), XtensaOperand::addRegOperands(), llvm::X86Operand::addRegOperands(), llvm::MachineRegisterInfo::addRegOperandToUseList(), llvm::RuntimeDyldImpl::addRelocationForSymbol(), addRequiredExtensionForVectorMULL(), AddRequiredExtensionForVMULL(), llvm::jitlink::Addressable::Addressable(), llvm::AddressRange::AddressRange(), llvm::DwarfUnit::addRnglistsBase(), llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::addRuntimeChecks(), llvm::M68kInstrInfo::AddSExt(), llvm::LPMUpdater::addSiblingLoops(), llvm::DwarfExpression::addSignedConstant(), llvm::DwarfUnit::addSourceLine(), llvm::LazyCallGraph::addSplitFunction(), llvm::LazyCallGraph::addSplitRefRecursiveFunctions(), llvm::X86Operand::addSrcIdxOperands(), llvm::AttrBuilder::addStackAlignmentAttr(), llvm::DwarfDebug::addStringTypeLoc(), llvm::RegionBase< RegionTraits< Function > >::addSubRegion(), llvm::SIScheduleBlock::addSucc(), llvm::mca::MemoryGroup::addSuccessor(), llvm::ScheduleDAGTopologicalSort::AddSUnitWithoutPredecessors(), llvm::Record::addSuperClass(), llvm::MachineOperand::addTargetFlag(), llvm::Record::addTemplateArg(), addToAccessGroupList(), llvm::AAPointerInfo::RangeList::addToAllOffsets(), llvm::DominanceFrontierBase< BasicBlock, false >::addToFrontier(), addToFwdRegWorklist(), llvm::HexagonPacketizerList::addToPacket(), llvm::WebAssemblyExceptionInfo::addTopLevelException(), llvm::LoopInfoBase< BasicBlock, Loop >::addTopLevelLoop(), addTryBlockMapEntry(), llvm::DwarfUnit::addType(), llvm::pdb::TpiStreamBuilder::addTypeRecord(), llvm::pdb::TpiStreamBuilder::addTypeRecords(), llvm::DwarfUnit::addUInt(), llvm::pdb::DbiModuleDescriptorBuilder::addUnmergedSymbols(), llvm::DwarfExpression::addUnsignedConstant(), llvm::SSAUpdaterBulk::AddUse(), llvm::MachineInstrBuilder::addUse(), llvm::mca::WriteState::addUser(), llvm::cl::list_storage< DataType, StorageClass >::addValue(), llvm::Record::addValue(), llvm::cl::bits_storage< DataType, StorageClass >::addValue(), llvm::DebugLocEntry::addValues(), llvm::TGLocalVarScope::addVar(), llvm::DbgVariableIntrinsic::addVariableLocationOps(), llvm::ConstraintSystem::addVariableRow(), addVariantDeclaration(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::addVirtualRoot(), llvm::VPlan::addVPValue(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), llvm::ScheduleDAGInstrs::addVRegUseDeps(), llvm::DwarfExpression::addWasmLocation(), llvm::cflaa::StratifiedSetsBuilder< T >::addWith(), AdjustBaseAndOffset(), llvm::ARMBasicBlockUtils::adjustBBOffsetsAfter(), AdjustBlendMask(), adjustByValArgAlignment(), adjustCostForPairing(), adjustDown(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::ARMAsmBackend::adjustFixupValue(), adjustFixupValue(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), llvm::adjustPqBits(), llvm::RISCVRegisterInfo::adjustReg(), llvm::IntervalMapImpl::adjustSiblingSizes(), llvm::X86RegisterInfo::adjustStackMapLiveOutMask(), adjustToIndexSize(), adjustUp(), llvm::MCRegisterInfo::DiffListIterator::advance(), llvm::RegPressureTracker::advance(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::coverage::CovMapFunctionRecordV3::advanceByOne(), llvm::PPCHazardRecognizer970::AdvanceCycle(), llvm::SmallPtrSetIteratorImpl::AdvanceIfNotValid(), llvm::GCNSchedStrategy::advanceStage(), llvm::SectionEntry::advanceStubOffset(), llvm::LiveRange::advanceTo(), llvm::BasicAAResult::alias(), llvm::LegalizerInfo::aliasActionDefinitions(), llvm::AliasSet::aliasesPointer(), llvm::LegalizeRuleSet::aliasTo(), llvm::Align::Align(), llvm::alignAddr(), llvm::alignDown(), llvm::alignTo(), llvm::alignToPowerOf2(), llvm::LoopSafetyInfo::allLoopPathsLeadToBlock(), llvm::ms_demangle::ArenaAllocator::alloc(), llvm::AllocaInst::AllocaInst(), llvm::ms_demangle::ArenaAllocator::allocArray(), llvm::sroa::AllocaSliceRewriter::AllocaSliceRewriter(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::allocate(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::Allocate(), allocateFixedSGPRInputImpl(), llvm::GVNExpression::AggregateValueExpression::allocateIntOperands(), llvm::AMDGPUMachineFunction::allocateKnownAddressLDSGlobal(), llvm::GVNExpression::BasicExpression::allocateOperands(), llvm::RegAllocBase::allocatePhysRegs(), allocateSGPR32InputImpl(), llvm::SIMachineFunctionInfo::allocateSGPRSpillToVGPRLane(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::SITargetLowering::allocateSystemSGPRs(), allocateVGPR32Input(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::StringMapEntryBase::allocateWithKey(), llvm::User::allocHungoffUses(), allocset(), llvm::ms_demangle::ArenaAllocator::allocUnalignedBuffer(), llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), allUsesOfLoadAndStores(), AllUsesOfValueWillTrapIfNull(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::AMDGPUAsmPrinter::AMDGPUAsmPrinter(), llvm::AMDGPULegalizerInfo::AMDGPULegalizerInfo(), llvm::AMDGPULibFunc::AMDGPULibFunc(), llvm::AMDGPURegisterBankInfo::AMDGPURegisterBankInfo(), llvm::ForwardDominanceFrontierBase< BasicBlock >::analyze(), Analyze_CC_Sparc64_Full(), Analyze_CC_Sparc64_Half(), AnalyzeArguments(), llvm::analyzeArguments(), llvm::ARCInstrInfo::analyzeBranch(), llvm::MSP430InstrInfo::analyzeBranch(), llvm::AVRInstrInfo::analyzeBranch(), llvm::ARMBaseInstrInfo::analyzeBranch(), llvm::AArch64InstrInfo::analyzeBranch(), llvm::SystemZInstrInfo::analyzeBranch(), llvm::M68kInstrInfo::AnalyzeBranchImpl(), llvm::AArch64InstrInfo::analyzeBranchPredicate(), llvm::X86InstrInfo::analyzeBranchPredicate(), analyzeCallOperands(), llvm::SystemZInstrInfo::analyzeCompare(), llvm::AArch64InstrInfo::analyzeCompare(), llvm::GenericUniformityAnalysisImpl< ContextT >::analyzeControlDivergence(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), analyzeGlobalAux(), llvm::InterleavedAccessInfo::analyzeInterleaving(), llvm::IRComparer< T >::analyzeIR(), llvm::BlockFrequencyInfoImplBase::analyzeIrreducible(), llvm::VNCoercion::analyzeLoadFromClobberingLoad(), analyzeLoopUnrollCost(), llvm::AnalyzePhysRegInBundle(), llvm::analyzeReturnValues(), llvm::RISCVInstrInfo::analyzeSelect(), llvm::LanaiInstrInfo::analyzeSelect(), llvm::ARMBaseInstrInfo::analyzeSelect(), llvm::TargetInstrInfo::analyzeSelect(), llvm::any_cast(), llvm::APFixedPoint::APFixedPoint(), llvm::APFloat::APFloat(), APIntToHexString(), llvm::SmallString< 256 >::append(), llvm::LiveRange::append(), llvm::DIExpression::append(), appendDigit(), llvm::objcopy::elf::OwnedDataSection::appendHexData(), llvm::DIExpression::appendOpsToArg(), llvm::appendReversedLoopsToWorklist(), llvm::mca::Pipeline::appendStage(), llvm::DIExpression::appendToStack(), llvm::SampleProfileInference< BT >::apply(), llvm::jitlink::BasicLayout::apply(), llvm::BitVector::apply(), llvm::ErrorHandlerTraits< Error(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< Error(&)(std::unique_ptr< ErrT >)>::apply(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::apply(), llvm::LegalizeRuleSet::apply(), llvm::CombinerHelper::applyAshShlToSextInreg(), llvm::CombinerHelper::applyBuildInstructionSteps(), AMDGPUPreLegalizerCombinerHelper::applyClampI64ToI16(), llvm::CombinerHelper::applyCombineConstantFoldFpUnary(), llvm::CombinerHelper::applyCombineDivRem(), llvm::CombinerHelper::applyCombineExtOfExt(), llvm::CombinerHelper::applyCombineI2PToP2I(), llvm::CombinerHelper::applyCombineMulByNegativeOne(), llvm::CombinerHelper::applyCombineMulToShl(), llvm::CombinerHelper::applyCombineP2IToI2P(), llvm::CombinerHelper::applyCombineShiftToUnmerge(), llvm::CombinerHelper::applyCombineTruncOfExt(), llvm::CombinerHelper::applyCombineUnmergeConstant(), llvm::CombinerHelper::applyCombineUnmergeMergeToPlainValues(), llvm::CombinerHelper::applyCombineUnmergeZExtToZExt(), AMDGPUPostLegalizerCombinerHelper::applyCvtF32UByteN(), applyDebugify(), llvm::RegisterBankInfo::applyDefaultMapping(), applyDupLane(), llvm::CombinerHelper::applyExtendThroughPhis(), llvm::RuntimeDyldImpl::applyExternalSymbolRelocations(), llvm::CombinerHelper::applyExtractAllEltsFromBuildVector(), llvm::CombinerHelper::applyExtractVecEltBuildVec(), applyExtractVecEltPairwiseAdd(), applyFConstantToConstant(), ApplyFeatureFlag(), llvm::CSKYAsmBackend::applyFixup(), llvm::LoongArchAsmBackend::applyFixup(), llvm::AVRAsmBackend::applyFixup(), llvm::ARMAsmBackend::applyFixup(), llvm::RISCVAsmBackend::applyFixup(), llvm::jitlink::i386::applyFixup(), llvm::jitlink::aarch64::applyFixup(), llvm::jitlink::x86_64::applyFixup(), applyFormTruncstore(), llvm::CombinerHelper::applyFunnelShiftToRotate(), applyICmpRedundantTrunc(), llvm::RegBankSelect::applyMapping(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::CombinerHelper::applyPtrAddImmedChain(), llvm::PBQP::applyR1(), llvm::PBQP::applyR2(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::applyRemapping(), llvm::CombinerHelper::applyRotateOutOfRange(), llvm::CombinerHelper::applySextInRegOfLoad(), llvm::CombinerHelper::applySextTruncSextLoad(), llvm::CombinerHelper::applyShiftImmedChain(), llvm::CombinerHelper::applyShiftOfShiftedLogic(), llvm::OpenMPIRBuilder::applySimd(), applySplitStoreZero128(), llvm::DwarfUnit::applySubprogramDefinitionAttributes(), llvm::CombinerHelper::applyTruncStoreMerge(), applyVAshrLshrImm(), applyVectorSextInReg(), llvm::OpenMPIRBuilder::applyWorkshareLoop(), llvm::APSInt::APSInt(), areCandidatesToMergeOrPair(), areCFlagsAccessedBetweenInstrs(), llvm::MemoryDepChecker::areDepsSafe(), llvm::SIInstrInfo::areLoadsFromSameBasePtr(), llvm::LanaiInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::AArch64InstrInfo::areMemAccessesTriviallyDisjoint(), llvm::RISCVInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::SIInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::PPCInstrInfo::areMemAccessesTriviallyDisjoint(), llvm::TargetInstrInfo::areMemAccessesTriviallyDisjoint(), areSlicesNextToEachOther(), areStridedAccessesIndependent(), llvm::CallLowering::ArgInfo::ArgInfo(), llvm::MachineFunction::ArgRegPair::ArgRegPair(), ARM64EmitUnwindCode(), ARM64EmitUnwindInfoForSegment(), ARM64ProcessEpilogs(), ARMEmitUnwindCode(), ARMEmitUnwindInfo(), llvm::ARMRegisterBankInfo::ARMRegisterBankInfo(), llvm::msgpack::ArrayDocNode::ArrayDocNode(), llvm::json::OStream::arrayEnd(), llvm::KnownBits::ashr(), llvm::APInt::ashrInPlace(), llvm::Register::asMCReg(), assertBranchOrSelectConditionHoisted(), assertCHRRegionsHaveBiasedBranchOrSelect(), llvm::Value::assertModuleIsMaterializedImpl(), llvm::CanonicalLoopInfo::assertOK(), llvm::SmallVectorTemplateCommon< T >::assertSafeToReferenceAfterResize(), AssertSorted(), llvm::BCLiteral< Value >::assertValid(), llvm::BCFixed< Width >::assertValid(), llvm::BCVBR< Width >::assertValid(), llvm::BCChar6::assertValid(), llvm::LiveRegMatrix::assign(), llvm::LiveRange::assign(), llvm::SystemZELFFrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZXPLINKFrameLowering::assignCalleeSavedSpillSlots(), llvm::MCStreamer::assignFragment(), llvm::RegBankSelect::assignInstr(), llvm::RegBankSelect::assignmentMatch(), llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::RegScavenger::assignRegToScavengingIndex(), assignSections(), llvm::SelectionDAG::AssignTopologicalOrder(), llvm::BitcodeReaderValueList::assignValue(), llvm::VirtRegMap::assignVirt2Phys(), llvm::VirtRegMap::assignVirt2StackSlot(), llvm::orc::AsynchronousSymbolQuery::AsynchronousSymbolQuery(), llvm::AtomicSDNode::AtomicSDNode(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::AttrBuilder::AttrBuilder(), llvm::json::OStream::attributeBegin(), llvm::json::OStream::attributeEnd(), llvm::AttributeListImpl::AttributeListImpl(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::AttributeSpec(), llvm::object::XCOFFObjectFile::auxiliaryHeader32(), llvm::object::XCOFFObjectFile::auxiliaryHeader64(), llvm::objcopy::coff::AuxSymbol::AuxSymbol(), StringView::back(), llvm::PriorityWorklist< llvm::LazyCallGraph::SCC *, SmallVector< llvm::LazyCallGraph::SCC *, N >, SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t > >::back(), llvm::SetVector< llvm::MCSection *, SmallVector< llvm::MCSection *, N >, SmallDenseSet< llvm::MCSection *, N > >::back(), llvm::memprof::CallStack< NodeT, IteratorT >::back(), PODSmallVector< Node *, 8 >::back(), llvm::StringRef::back(), OutputBuffer::back(), llvm::ArrayRef< uint64_t >::back(), llvm::TinyPtrVector< llvm::VPValue * >::back(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::back(), llvm::BitVector::back(), llvm::SmallBitVector::back(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::back(), llvm::BitstreamWriter::BackpatchWord(), llvm::PBQP::backpropagate(), llvm::RegScavenger::backward(), llvm::ImutAVLFactory< ImutInfo >::balanceTree(), llvm::codeview::ContinuationRecordBuilder::begin(), llvm::LoopBlocksTraversal::begin(), llvm::yaml::begin(), llvm::memprof::CallStack< NodeT, IteratorT >::beginAfterSharedPrefix(), llvm::DwarfCFIException::beginBasicBlockSection(), llvm::DwarfExpression::beginEntryValueExpression(), llvm::ARMException::beginFunction(), llvm::DebugHandlerBase::beginFunction(), llvm::BTFDebug::beginFunctionImpl(), llvm::CodeViewDebug::beginFunctionImpl(), llvm::DwarfDebug::beginFunctionImpl(), llvm::LiveRange::beginIndex(), llvm::DebugHandlerBase::beginInstruction(), llvm::DwarfDebug::beginInstruction(), llvm::DwarfDebug::beginModule(), llvm::LoopBlocksDFS::beginPostorder(), llvm::LoopBlocksDFS::beginRPO(), bigEndianByteAt(), llvm::ConstantRange::binaryOp(), llvm::BitCastInst::BitCastInst(), llvm::detail::IEEEFloat::bitcastToAPInt(), llvm::detail::DoubleAPFloat::bitcastToAPInt(), bitcastToVectorElement32(), llvm::yaml::ScalarBitSetTraits< ELFYAML::ELF_EF >::bitset(), llvm::EVT::bitsGE(), llvm::MVT::bitsGE(), llvm::EVT::bitsGT(), llvm::MVT::bitsGT(), llvm::EVT::bitsLE(), llvm::MVT::bitsLE(), llvm::EVT::bitsLT(), llvm::MVT::bitsLT(), llvm::remarks::BitstreamRemarkSerializer::BitstreamRemarkSerializer(), llvm::LoopAccessInfo::blockNeedsPredication(), llvm::LoopBase< BasicBlock, Loop >::blocks(), bothcases(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::branched(), llvm::BranchProbability::BranchProbability(), breakBackedgeIfNotTaken(), llvm::breakLoopBackedge(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), BrPHIToSelect(), llvm::rdf::DataFlowGraph::build(), llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata(), llvm::MachineIRBuilder::buildAtomicCmpXchg(), llvm::MachineIRBuilder::buildAtomicCmpXchgWithSuccess(), llvm::buildAtomicCompareExchangeInst(), llvm::buildAtomicFlagInst(), llvm::buildAtomicInitInst(), llvm::MachineIRBuilder::buildAtomicRMW(), llvm::buildAtomicRMWInst(), llvm::buildBarrierInst(), llvm::SwitchCG::SwitchLowering::buildBitTests(), llvm::MachineIRBuilder::buildBlockAddress(), llvm::MachineIRBuilder::buildBrCond(), llvm::MachineIRBuilder::buildBrIndirect(), llvm::MachineIRBuilder::buildBrJT(), buildCallOperands(), llvm::MachineIRBuilder::buildCast(), buildClonedLoopBlocks(), buildClonedLoops(), llvm::MachineIRBuilder::buildConstant(), llvm::SPIRVGlobalRegistry::buildConstantFP(), BuildConstantFromSCEV(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::MachineIRBuilder::buildConstantPool(), llvm::SPIRVGlobalRegistry::buildConstantSampler(), llvm::MachineIRBuilder::buildConstDbgValue(), buildCopyFromRegs(), buildCopyToRegs(), llvm::MachineIRBuilder::buildDbgLabel(), llvm::buildDbgValueForSpill(), llvm::MachineIRBuilder::buildDeleteTrailingVectorElements(), llvm::SPIRVGeneralDuplicatesTracker::buildDepsGraph(), llvm::MachineIRBuilder::buildDirectDbgValue(), llvm::MachineIRBuilder::buildDynStackAlloc(), llvm::buildEnqueueKernel(), BuildExactSDIV(), llvm::MachineIRBuilder::buildExtOrTrunc(), llvm::MachineIRBuilder::buildExtract(), buildExtractionBlockSet(), llvm::MachineIRBuilder::buildFConstant(), llvm::MachineIRBuilder::buildFIDbgValue(), buildFixItLine(), buildFrameDebugInfo(), llvm::MachineIRBuilder::buildFrameIndex(), buildFrameType(), llvm::PassBuilder::buildFunctionSimplificationPipeline(), llvm::MachineIRBuilder::buildGlobalValue(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::VPlanSlp::buildGraph(), llvm::MachineIRBuilder::buildIndirectDbgValue(), llvm::MachineIRBuilder::buildInsert(), llvm::CSEMIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstr(), llvm::SwitchCG::SwitchLowering::buildJumpTable(), llvm::MachineIRBuilder::buildLoad(), llvm::MachineIRBuilder::buildLoadInstr(), llvm::PassBuilder::buildLTOPreLinkDefaultPipeline(), llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildMergeValues(), llvm::BuildMI(), llvm::buildModuleSummaryIndex(), llvm::AMDGPULegalizerInfo::buildMultiply(), buildNew(), llvm::PassBuilder::buildO0DefaultPipeline(), llvm::DICompositeType::buildODRType(), llvm::AArch64InstrInfo::buildOutlinedFrame(), llvm::ARMBaseInstrInfo::buildOutlinedFrame(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), buildPCRelGlobalAddress(), llvm::PassBuilder::buildPerModuleDefaultPipeline(), llvm::opt::OptTable::buildPrefixChars(), llvm::SwitchInstProfUpdateWrapper::buildProfBranchWeightsMD(), llvm::MachineIRBuilder::buildPtrAdd(), llvm::AMDGPURegisterBankInfo::buildReadFirstLane(), llvm::LazyCallGraph::buildRefSCCs(), buildScalarSteps(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::TargetLowering::BuildSDIV(), llvm::CombinerHelper::buildSDivUsingMul(), llvm::SIInstrInfo::buildShrunkInst(), llvm::MachineIRBuilder::buildShuffleSplat(), llvm::MachineIRBuilder::buildShuffleVector(), llvm::orc::buildSimpleReexportsAliasMap(), llvm::R600InstrInfo::buildSlotOfVectorInstruction(), llvm::SIRegisterInfo::buildSpillLoadStore(), llvm::MachineIRBuilder::buildStore(), BuildSubAggregate(), llvm::PassBuilder::buildThinLTOPreLinkDefaultPipeline(), llvm::TargetLowering::BuildUDIV(), llvm::CombinerHelper::buildUDivUsingMul(), llvm::MachineIRBuilder::buildUnmerge(), llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::bumpCycle(), llvm::SchedBoundary::bumpCycle(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::SchedBoundary::bumpNode(), llvm::RegPressureTracker::bumpUpwardPressure(), llvm::HexagonMCInstrInfo::bundleInstructions(), llvm::MachineInstr::bundleWithPred(), llvm::MachineInstr::bundleWithSucc(), BURRSort(), llvm::APInt::byteSwap(), llvm::ARM::WinEH::RuntimeFunction::C(), llvm::cacheAnnotationFromMD(), llvm::CacheCost::CacheCost(), llvm::CachedHashStringRef::CachedHashStringRef(), CalcNodeSethiUllmanNumber(), calcPredicateUsingBooleans(), llvm::LiveIntervalCalc::calculate(), llvm::ForwardDominanceFrontierBase< BasicBlock >::calculate(), llvm::BranchProbabilityInfo::calculate(), calculateByteProvider(), llvm::calculateClrEHStateNumbers(), calculateCXXStateNumbers(), llvm::calculateDbgEntityHistory(), llvm::SelectionDAG::calculateDivergence(), llvm::MDNodeOpsKey::calculateHash(), llvm::R600InstrInfo::calculateIndirectAddress(), llvm::AMDGPUMachineFunction::calculateKnownAddressOfLDSGlobal(), calculateMMLEIndex(), calculatePrevailingSummary(), calculateSEHStateNumbers(), llvm::codeview::DebugInlineeLinesSubsection::calculateSerializedSize(), calculateStateNumbersForInvokes(), llvm::LiveRangeCalc::calculateValues(), calculateVectorIndex(), llvm::dwarf::CallFrameString(), llvm::Interpreter::callFunction(), callHasRegMask(), llvm::sampleprofutil::callsiteIsHot(), callsShareTOCBase(), llvm::EHStreamer::callToNoUnwindFunction(), llvm::orc::SimpleRemoteEPC::callWrapperAsync(), canBeFeederToNewValueJump(), llvm::Value::canBeFreed(), llvm::DwarfExpression::cancelEntryValue(), canClobberPhysRegDefs(), canCmpInstrBeRemoved(), canCombine(), llvm::ARMTargetLowering::canCombineStoreAndExtract(), canConvertValue(), canCreateAliasFor(), llvm::TargetLowering::canCreateUndefOrPoisonForTargetNode(), canEmitConjunction(), canEvaluateSExtd(), canEvaluateShiftedShift(), canEvaluateTruncated(), canExpandVectorCTPOP(), canFoldCopy(), canFoldIntoCSel(), llvm::InstCombiner::canFreelyInvertAllUsersOf(), canInstrSubstituteCmpInstr(), llvm::AAResults::canInstructionRangeModRef(), canLowerByDroppingElements(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::RegBankSelect::EdgeInsertPoint::canMaterialize(), canNotEvaluateInType(), canonicalizeAbs(), canonicalizeBitSelect(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeConstantArg0ToArg1(), llvm::sampleprof::SampleContextTrimmer::canonicalizeContextProfiles(), canonicalizeICmpBool(), canonicalizeLaneShuffleWithRepeatedOps(), canonicalizeSaturatedSubtract(), canonicalizeShuffleMaskWithCommute(), canonicalizeShuffleMaskWithHorizOp(), llvm::TargetLoweringBase::canOpTrap(), llvm::TargetInstrInfo::canPredicatePredicatedInstr(), llvm::HexagonPacketizerList::canPromoteToNewValueStore(), CanPropagatePredecessorsForPHIs(), canProveExitOnFirstIteration(), CanProveNotTakenFirstIteration(), canReduceVMulWidth(), llvm::LiveRangeEdit::canRematerializeAt(), canRenameComdat(), llvm::canRenameComdatFunc(), llvm::canReplacePointersIfEqual(), canRotateDeoptimizingLatchExit(), canSinkInstructions(), llvm::canSinkOrHoistInst(), canTransformAccumulatorRecursion(), llvm::X86FrameLowering::canUseAsEpilogue(), llvm::X86FrameLowering::canUseAsPrologue(), llvm::LoopVectorizationLegality::canVectorize(), CanWidenIV(), canWidenShuffleElements(), carryFlagToValue(), CasesAreContiguous(), llvm::PointerSumType< ExtraInfoInlineKinds, llvm::PointerSumTypeMember< EIIK_MMO, llvm::MachineMemOperand * >, llvm::PointerSumTypeMember< EIIK_PreInstrSymbol, llvm::MCSymbol * >, llvm::PointerSumTypeMember< EIIK_PostInstrSymbol, llvm::MCSymbol * >, llvm::PointerSumTypeMember< EIIK_OutOfLine, ExtraInfo * > >::cast(), llvm::cast(), llvm::cast_if_present(), CC_AArch64_Custom_Block(), CC_AIX(), CC_ARM_AAPCS_Custom_Aggregate(), CC_LoongArch(), CC_MipsO32(), CC_PPC32_SPE_CustomSplitFP64(), CC_RISCV(), CC_Sparc_Assign_SRet(), CC_X86_32_MCUInReg(), CC_X86_32_RegCall_Assign2Regs(), CC_X86_VectorCallAssignRegister(), chainLoadsAndStoresForMemcpy(), chainToBasePointerCost(), llvm::LLT::changeElementSize(), changeFPCCToANDAArch64CC(), llvm::DominatorTreeBase< BasicBlock, false >::changeImmediateDominator(), llvm::NVPTXTargetStreamer::changeSection(), llvm::MCObjectStreamer::changeSectionImpl(), llvm::MachineOperand::ChangeToDbgInstrRef(), llvm::MachineOperand::ChangeToES(), llvm::MachineOperand::ChangeToFPImmediate(), llvm::MachineOperand::ChangeToFrameIndex(), llvm::MachineOperand::ChangeToGA(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToMCSymbol(), llvm::LoopInfoBase< BasicBlock, Loop >::changeTopLevelLoop(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineOperand::ChangeToTargetIndex(), llvm::Attributor::changeUseAfterManifest(), llvm::EVT::changeVectorElementType(), llvm::MVT::changeVectorElementType(), llvm::MVT::changeVectorElementTypeToInteger(), CheckAndCreateOffsetAdd(), checkBasicSSA(), checkBiasedBranch(), checkBoolTestSetCCCombine(), checkChars(), checkClobberSanity(), checkDependency(), checkedGetHex(), llvm::Attributor::checkForAllCallSites(), llvm::checkForCycles(), checkFunctionMemoryAccess(), llvm::checkGEPType(), checkGlobalVariableScope(), checkHoistValue(), checkIfSafeAddSequence(), TransferTracker::checkInstForNewValues(), llvm::ARM::checkPartialMappings(), checkPHIs(), llvm::mca::RegisterFile::checkRAWHazards(), llvm::LiveIntervals::checkRegMaskInterference(), checkRegOnlyPHIInputs(), llvm::LiveRangeEdit::checkRematerializable(), CheckSame(), checkType(), checkValidLayout(), llvm::ARM::checkValueMappings(), checkVectorTypeForPromotion(), llvm::checkVOPDRegConstraints(), llvm::IDFCalculatorDetail::ChildrenGetterTy< BasicBlock, IsPostDom >::ChildrenGetterTy(), chooseConstraint(), ChooseConstraint(), chopOneUTF32(), clampDynamicVectorIndex(), llvm::LegalizeRuleSet::clampNumElements(), clampReturnedValueStates(), llvm::LegalizeRuleSet::clampScalar(), llvm::ConnectedVNInfoEqClasses::Classify(), classifyConstantWithOpaquePtr(), llvm::X86InstrInfo::classifyLEAReg(), llvm::FPPassManager::cleanup(), llvm::SCEVExpanderCleaner::cleanup(), llvm::StatepointLoweringState::clear(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::clear(), llvm::orc::JITDylib::clear(), llvm::rdf::DataFlowGraph::DefStack::clear_block(), clearAssumptionsOfUsers(), llvm::APInt::clearBit(), llvm::SCEVWrapPredicate::clearFlags(), clearKillsForDef(), llvm::ScheduleDAGInstrs::Value2SUsMap::clearList(), llvm::APInt::clearLowBits(), llvm::Value::clearMetadata(), llvm::MachineFrameInfo::clearObjectAllocation(), llvm::CoroIdInst::clearPromise(), llvm::MachineRegisterInfo::clearSimpleHint(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::VirtRegMap::clearVirt(), TransferTracker::clobberMloc(), llvm::MachineOperand::clobbersPhysReg(), llvm::UnOpInit::clone(), llvm::BinOpInit::clone(), llvm::TernOpInit::clone(), llvm::cloneAndAdaptNoAliasScopes(), llvm::CloneAndPruneIntoFromInst(), llvm::DILocation::cloneByMultiplyingDuplicationFactor(), cloneConstantExprWithNewAddressSpace(), llvm::CloneFunctionInto(), llvm::orc::cloneGlobalAliasDecl(), llvm::MachineFunction::cloneInfo(), llvm::MachineFunction::cloneInfoFrom(), llvm::MachineInstr::cloneInstrSymbols(), cloneInstructionInExitBlock(), CloneInstructionsIntoPredecessorBlockAndUpdateSSAUses(), CloneLoopBlocks(), cloneLoopNest(), llvm::cloneLoopWithPreheader(), llvm::MachineInstr::cloneMemRefs(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::orc::cloneToNewContext(), llvm::raw_fd_ostream::close(), llvm::RegPressureTracker::closeBottom(), llvm::LexicalScope::closeInsnRange(), llvm::RegPressureTracker::closeRegion(), llvm::RegPressureTracker::closeTop(), clusterSortPtrAccesses(), llvm::FunctionComparator::cmpBasicBlocks(), llvm::FunctionComparator::cmpConstants(), llvm::FunctionComparator::cmpTypes(), coalescable(), codegen(), coerceArguments(), llvm::VNCoercion::coerceAvailableValueToLoadType(), llvm::LegalizerHelper::coerceToScalar(), llvm::object::coffnamecpy(), llvm::OpenMPIRBuilder::collapseLoops(), collectCallSiteParameters(), collectConcatOps(), collectEHScopeMembers(), llvm::LoopVectorizationCostModel::collectElementTypesForWidening(), llvm::CodeMetrics::collectEphemeralValues(), collectEscapedLocals(), collectHomogenousInstGraphLoopInvariants(), collectHWRegs(), collectInsertionElements(), llvm::DDGNode::collectInstructions(), collectInstructionsInBetween(), collectMultiplyFactors(), llvm::GEPOperator::collectOffset(), llvm::collectPGOFuncNameStrings(), collectRegionsConstants(), collectShuffleElements(), collectSingleShuffleElements(), collectTransitivePredecessors(), collectUnswitchCandidates(), collectUnswitchCandidatesWithInjections(), llvm::AMDGPURegisterBankInfo::collectWaterfallOperands(), llvm::mca::RegisterFile::collectWrites(), llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >::CombinationGenerator(), combineAdd(), combineAnd(), combineAndNotIntoANDNP(), combineAndShuffleNot(), combineArithReduction(), combineBinOp_VLToVWBinOp_VL(), combineBitOpWithMOVMSK(), combineBitOpWithShift(), combineBMILogicOp(), combineBROADCAST_LOAD(), combineBVOfConsecutiveLoads(), combineCastedMaskArithmetic(), combineCMov(), combineCmpOp(), combineConcatVectorOfConcatVectors(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineCVTP2I_CVTTP2I(), combineExtractVectorElt(), combineExtractWithShuffle(), combineFaddCFmul(), combineFMA(), combineFMinFMax(), combineFOr(), combineFP_EXTEND(), combineFP_ROUND(), combineHorizOpWithShuffle(), llvm::InstCombinerImpl::combineLoadToNewType(), combineLoadToOperationType(), combineLogicBlendIntoConditionalNegate(), combineLogicBlendIntoPBLENDV(), llvm::Combiner::combineMachineInstrs(), combineMaskedLoadConstantMask(), combineMinMaxReduction(), combineMOVMSK(), combineMul(), combineOr(), combinePredicateReduction(), combinePTESTCC(), combineRedundantDWordShuffle(), combineRestoreSETHIi(), llvm::CombinerInfo::CombinerInfo(), llvm::PPCInstrInfo::combineRLWINM(), combineScalarAndWithMaskSetcc(), llvm::VETargetLowering::combineSelect(), llvm::VETargetLowering::combineSelectCC(), combineSetCC(), combineSetCCMOVMSK(), combineSextInRegCmov(), combineShiftAnd1ToBitTest(), combineShiftOfShiftedLogic(), combineShiftToAVG(), combineShiftToMULH(), combineShiftToPMULH(), combineShuffleOfSplatVal(), combineShuffleToZeroExtendVectorInReg(), combineSignExtendInReg(), combineSIntToFP(), combineStoreToNewValue(), combineStoreToValueType(), combineSub(), combineSubABS(), combineTargetShuffle(), combineToConsecutiveLoads(), combineToExtendBoolVectorInReg(), llvm::VETargetLowering::combineTRUNCATE(), combineTruncatedArithmetic(), combineTruncateWithSat(), combineVectorHADDSUB(), combineVectorInsert(), combineVectorPack(), combineVectorShiftImm(), combineVectorShiftVar(), combineVectorSizedSetCCEquality(), combineVSelectWithAllOnesOrZeros(), combinevXi1ConstantToInteger(), combineWeight(), combineX86AddSub(), combineX86INT_TO_FP(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), combineXorSubCTLZ(), llvm::Instruction::comesBefore(), llvm::json::OStream::comment(), llvm::pdb::InfoStreamBuilder::commit(), llvm::pdb::TpiStreamBuilder::commit(), llvm::pdb::PDBFileBuilder::commit(), llvm::mca::WriteRef::commit(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::pdb::DbiStreamBuilder::commit(), llvm::codeview::DebugLinesSubsection::commit(), commitFpm(), llvm::InstCombinerImpl::commonIDivTransforms(), llvm::yaml::commonSectionMapping(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::ShuffleVectorInst::commute(), llvm::TargetInstrInfo::commuteInstruction(), llvm::SIInstrInfo::commuteInstructionImpl(), llvm::TargetInstrInfo::commuteInstructionImpl(), llvm::RISCVInstrInfo::commuteInstructionImpl(), llvm::PPCInstrInfo::commuteInstructionImpl(), llvm::X86InstrInfo::commuteInstructionImpl(), llvm::ShuffleVectorInst::commuteShuffleMask(), commuteVPTERNLOG(), CompactSwizzlableVector(), llvm::FunctionComparator::compare(), llvm::detail::IEEEFloat::compare(), llvm::IRComparer< T >::compare(), llvm::APFloat::compare(), llvm::ICmpInst::compare(), llvm::detail::IEEEFloat::compareAbsoluteValue(), llvm::ScaledNumbers::compareImpl(), llvm::compareLoops(), llvm::MDNodeOpsKey::compareOps(), llvm::ValueDFS_Compare::comparePHIRelated(), CompareSCEVComplexity(), llvm::FunctionComparator::compareSignature(), llvm::APSInt::compareValues(), completeEphemeralValues(), llvm::InnerLoopVectorizer::completeLoopSkeleton(), llvm::HvxSelector::completeToPerfect(), llvm::BTFTypeDerived::completeType(), llvm::AMDGPU::VOPD::ComponentLayout::ComponentLayout(), llvm::AMDGPU::VOPD::ComponentProps::ComponentProps(), llvm::HexagonEvaluator::composeWithSubRegIndex(), llvm::compression::zlib::compress(), compress_chunks_parallel(), compress_parents_parallel(), compress_subtree_to_parent_node(), llvm::DivergenceAnalysisImpl::compute(), llvm::GenericCycleInfo< SSAContext >::compute(), llvm::GenericUniformityAnalysisImpl< ContextT >::compute(), llvm::EHStreamer::computeActionsTable(), computeAliasSummary(), computeAllocaDefaultAlign(), llvm::ComputeASanStackFrameLayout(), computeBlockRuns(), llvm::computeBundlePadding(), computeCalleeSaveRegisterPairs(), llvm::EHStreamer::computeCallSiteTable(), llvm::computeConstantRange(), computeConstraintToUse(), llvm::TargetLowering::ComputeConstraintToUse(), llvm::sampleprofutil::SampleCoverageTracker::computeCoverage(), llvm::ComputeCrossModuleImport(), llvm::ComputeCrossModuleImportForModuleFromIndex(), computeDataLayout(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), computeDomSubtreeCost(), computeExprForSpill(), computeForAddCarry(), llvm::KnownBits::computeForAddCarry(), llvm::MCAssembler::computeFragmentSize(), computeFunctionSummary(), computeHeuristicUnrollFactor(), computeImportForFunction(), ComputeImportForModule(), computeIndirectRegIndex(), llvm::TargetSchedModel::computeInstrLatency(), llvm::DivergencePropagator< ContextT >::computeJoinPoints(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::ComputeLinearIndex(), computeLiveInValues(), computeLiveOutSeed(), computeLoadStoreDefaultAlign(), llvm::SimpleLoopSafetyInfo::computeLoopSafetyInfo(), llvm::ICFLoopSafetyInfo::computeLoopSafetyInfo(), llvm::computeMachineUniformityInfo(), llvm::RegBankSelect::computeMapping(), llvm::MachineFrameInfo::computeMaxCallFrameSize(), llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::SelectionDAG::ComputeNumSignBits(), ComputeNumSignBits(), computeNumSignBitsBinOp(), llvm::RISCVTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::TargetLowering::ComputeNumSignBitsForTargetNode(), ComputeNumSignBitsImpl(), llvm::DIE::computeOffsetsAndAbbrevs(), computeOpenMPScheduleType(), llvm::EHStreamer::computePadMap(), llvm::computePeelCount(), llvm::rdf::Liveness::computePhiInfo(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), computePointerSize(), llvm::mca::computeProcResourceMasks(), llvm::RegisterClassInfo::computePSetLimit(), llvm::IndexedReference::computeRefCost(), llvm::TargetLoweringBase::computeRegisterProperties(), computeSpeculationCost(), llvm::LiveInterval::computeSubRangeUndefs(), llvm::SampleProfileSummaryBuilder::computeSummaryForProfiles(), llvm::MachObjectWriter::computeSymbolTable(), computeSymbolTableSize(), llvm::LegacyLegalizerInfo::computeTables(), llvm::MipsABIInfo::computeTargetABI(), computeTargetABI(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ComputeUnreachableDominators(), llvm::computeUnrollCount(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::SelectionDAG::computeVectorKnownZeroElements(), computeVTableFuncs(), computeZeroableShuffleElements(), concatenateTwoVectors(), llvm::concatenateVectors(), concatSubVectors(), llvm::DirectedGraph< NodeType, EdgeType >::connect(), llvm::VPBlockUtils::connectBlocks(), ConnectEpilog(), ConnectProlog(), llvm::sys::fs::mapped_file_region::const_data(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), llvm::DIExpression::constantFold(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldIntToFloat(), llvm::ConstantFoldTerminator(), llvm::ConstantFoldUnaryInstruction(), llvm::ConstantFoldUnaryOpOperand(), constantFoldUser(), llvm::ConstantRange::ConstantRange(), llvm::constrainOperandRegClass(), llvm::constrainSelectedInstRegOperands(), llvm::DwarfCompileUnit::constructCallSiteEntryDIE(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::LiveIntervalCalc::constructMainRangeFromSubranges(), llvm::LiveIntervals::constructMainRangeFromSubranges(), constructOverloadTypeName(), constructPointer(), llvm::DwarfCompileUnit::constructScopeDIE(), constructSegment(), ConstructSSAForLoadSet(), llvm::DwarfUnit::constructSubprogramArguments(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), constructSymbolEntry(), llvm::LoopBase< BasicBlock, Loop >::contains(), llvm::AttributeMask::contains(), llvm::LiveRange::Segment::containsInterval(), containsUnconditionalCallSafepoint(), llvm::ContextAndReplaceableUses::ContextAndReplaceableUses(), llvm::APFloat::convert(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::convertConstantExprsToInstructions(), llvm::ConvertDebugDeclareToDebugValue(), llvm::AMDGPUDisassembler::convertFMAanyK(), convertFPR32ToFPR64(), convertFPToInt(), llvm::detail::DoubleAPFloat::convertFromAPInt(), convertFromScalableVector(), llvm::detail::DoubleAPFloat::convertFromSignExtendedInteger(), llvm::detail::DoubleAPFloat::convertFromString(), llvm::detail::DoubleAPFloat::convertFromZeroExtendedInteger(), convertImageAddrToPacked(), convertImplicitDefToConstZero(), convertLocVTToValVT(), llvm::AMDGPUDisassembler::convertMacDPPInst(), llvm::InlineAsm::convertMemFlagWordToMatchingFlagWord(), convertMergedOpToPredOp(), llvm::AMDGPUDisassembler::convertMIMGInst(), llvm::SIInstrInfo::convertNonUniformIfRegion(), llvm::SIInstrInfo::convertNonUniformLoopRegion(), ConvertSelectToConcatVector(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), llvm::AMDGPU::convertSMRDOffsetUnits(), llvm::MIRPrinter::convertStackObjects(), llvm::detail::IEEEFloat::convertToDouble(), llvm::APFloat::convertToDouble(), llvm::detail::IEEEFloat::convertToFloat(), llvm::APFloat::convertToFloat(), llvm::detail::DoubleAPFloat::convertToHexString(), llvm::PPCInstrInfo::convertToImmediateForm(), llvm::detail::IEEEFloat::convertToInteger(), llvm::detail::DoubleAPFloat::convertToInteger(), convertToParamAS(), convertToScalableVector(), llvm::RISCVInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::SIInstrInfo::convertToThreeAddress(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::convertUTF8ToUTF16String(), llvm::ConvertUTF8toWide(), convertValue(), convertValVTToLocVT(), llvm::IntervalMapImpl::NodeBase< std::pair< IndexT, IndexT >, char, N >::copy(), llvm::MachineFunction::copyCallSiteInfo(), llvm::BranchProbabilityInfo::copyEdgeProbabilities(), llvm::SelectionDAG::copyExtraInfo(), llvm::Instruction::copyFastMathFlags(), copyFlags(), llvm::SmallPtrSetImplBase::CopyFrom(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::copyFrom(), llvm::AArch64InstrInfo::copyGPRRegTuple(), copyMustTailReturn(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::SPIRVInstrInfo::copyPhysReg(), llvm::CSKYInstrInfo::copyPhysReg(), llvm::ARCInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::M68kInstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysRegTuple(), copyPhysSubRegs(), copyRegOperand(), copySubReg(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), CopyToFromAsymmetricReg(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::InstrProfCorrelatorImpl< IntPtrT >::correlateProfileData(), costAndCollectOperands(), llvm::SchedBoundary::countResource(), countToEliminateCompares(), llvm::coverage::CoverageFilenamesSectionWriter::CoverageFilenamesSectionWriter(), llvm::coverage::CoverageMapError::CoverageMapError(), llvm::RegisterBank::covers(), llvm::ARM::WinEH::RuntimeFunctionARM64::CR(), llvm::symbolize::SymbolizableObjectFile::create(), llvm::orc::EPCEHFrameRegistrar::Create(), llvm::TargetMachineBuilder::create(), llvm::AllocationOrder::create(), llvm::MCFixup::create(), llvm::BinaryOperator::Create(), llvm::StructType::create(), llvm::orc::LocalIndirectStubsInfo< ORCABI >::create(), llvm::OnDiskChainedHashTable< Info >::Create(), llvm::InlineAsmKeyType::create(), llvm::CastInst::Create(), llvm::OnDiskIterableChainedHashTable< Info >::Create(), llvm::IntervalTree< LVAddress, LVScope * >::create(), llvm::GetElementPtrInst::Create(), llvm::vfs::RedirectingFileSystem::create(), llvm::CatchReturnInst::Create(), llvm::CleanupReturnInst::Create(), llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), createAArch64MCAsmInfo(), llvm::MatrixBuilder::CreateAdd(), llvm::ScalarEvolution::createAddRecFromPHIWithCasts(), llvm::IRBuilderBase::CreateAlignmentAssumption(), llvm::IRBuilderBase::CreateAnd(), createARMAsmBackend(), CreateAssert(), CreateAssertNot(), llvm::IRBuilderBase::CreateAssumption(), llvm::OpenMPIRBuilder::createAtomicCapture(), llvm::OpenMPIRBuilder::createAtomicCompare(), llvm::OpenMPIRBuilder::createAtomicRead(), llvm::OpenMPIRBuilder::createAtomicUpdate(), llvm::OpenMPIRBuilder::createAtomicWrite(), llvm::orc::ExecutionSession::createBareJITDylib(), llvm::DIBuilder::createBasicType(), llvm::createBitMaskForGaps(), llvm::InnerLoopVectorizer::createBitOrPointerCast(), llvm::VPRecipeBuilder::createBlockInMask(), llvm::MDBuilder::createBranchWeights(), llvm::objcarc::createCallInstWithColors(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalMappingFor(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), createCast(), createCheckDebugifyFunctionPass(), createCheckDebugifyModulePass(), llvm::DIBuilder::createClassType(), createCmpXchgInstFun(), llvm::DIBuilder::createCompileUnit(), llvm::ARMTargetLowering::createComplexDeinterleavingIR(), llvm::AArch64TargetLowering::createComplexDeinterleavingIR(), createCoroSave(), llvm::LiveIntervalCalc::createDeadDefs(), createDebugifyFunctionPass(), createDebugifyModulePass(), llvm::createDefaultScheduler(), createDefCFAExpression(), llvm::MemorySSA::createDefinedAccess(), llvm::DDGBuilder::createDefUseEdge(), llvm::VPRecipeBuilder::createEdgeMask(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::LiveIntervals::createEmptyInterval(), llvm::DIBuilder::createEnumerator(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), llvm::IRBuilderBase::CreateExtractInteger(), llvm::DDGBuilder::createFineGrainedNode(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::createFineGrainedNodes(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::CastInst::CreateFPCast(), llvm::MDBuilder::createFPMath(), llvm::DIExpression::createFragmentExpression(), createFrameHelperMachineFunction(), createFree(), llvm::CallInst::CreateFree(), llvm::DIBuilder::createFriend(), CreateGCRelocates(), createImportedModule(), llvm::MatrixBuilder::CreateIndexAssumption(), llvm::msf::MappedBlockStream::createIndexedStream(), llvm::msf::WritableMappedBlockStream::createIndexedStream(), createIndexMap(), llvm::InnerLoopVectorizer::createInductionResumeValue(), llvm::InnerLoopVectorizer::createInductionResumeValues(), llvm::DIBuilder::createInheritance(), llvm::mca::InstrBuilder::createInstruction(), llvm::logicalview::LVBinaryReader::createInstructions(), createInstructionShuffler(), llvm::CastInst::CreateIntegerCast(), llvm::IRBuilderBase::CreateIntrinsic(), createInvariantCond(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::orc::createJITLoaderGDBRegistrar(), llvm::MachineJumpTableInfo::createJumpTableIndex(), llvm::IRBuilderBase::CreateLaunderInvariantGroup(), llvm::orc::EPCIndirectionUtils::createLazyCallThroughManager(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::jitlink::createLinkGraphFromELFObject_aarch64(), llvm::jitlink::createLinkGraphFromELFObject_i386(), llvm::jitlink::createLinkGraphFromELFObject_loongarch(), llvm::jitlink::createLinkGraphFromELFObject_riscv(), llvm::IRBuilderBase::CreateLogicalAnd(), llvm::IRBuilderBase::CreateLogicalOr(), llvm::DIBuilder::createMacro(), createMalloc(), llvm::IRBuilderBase::CreateMaskedCompressStore(), llvm::IRBuilderBase::CreateMaskedExpandLoad(), llvm::IRBuilderBase::CreateMaskedGather(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedScatter(), llvm::IRBuilderBase::CreateMaskedStore(), createMaskInstrs(), createMCInstPrinter(), llvm::Target::createMCObjectStreamer(), llvm::createMCSymbolizer(), llvm::X86Operand::CreateMem(), llvm::createMemCpyLoopKnownSize(), llvm::createMemLibcall(), llvm::MemorySSAUpdater::createMemoryAccessAfter(), llvm::MemorySSAUpdater::createMemoryAccessBefore(), llvm::DDGBuilder::createMemoryEdge(), llvm::DIBuilder::createMethod(), llvm::RISCVInstrInfo::createMIROperandComment(), llvm::TargetInstrInfo::createMIROperandComment(), llvm::IRBuilderBase::CreateNAryOp(), createNaturalLoopInternal(), createNewIdReg(), llvm::ImutAVLFactory< ImutInfo >::createNode(), createNodeForSelectViaUMinSeq(), llvm::OpenMPIRBuilder::createOffloadEntriesAndInfoMetadata(), llvm::IRBuilderBase::CreateOr(), llvm::OpenMPIRBuilder::createOrderedDepend(), llvm::createOrderedReduction(), createPackShuffleMask(), llvm::OpenMPIRBuilder::createParallel(), llvm::DIBuilder::createParameterVariable(), llvm::PassInfo::createPass(), llvm::createPHIsForSplitLoopExit(), llvm::DDGBuilder::createPiBlock(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::createPiBlocks(), createPlaceholderForShuffleVector(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerCast(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::IRBuilderBase::CreatePreserveStructAccessIndex(), llvm::IRBuilderBase::CreatePreserveUnionAccessIndex(), createProfileFileNameVar(), llvm::IRBuilderBase::CreatePtrDiff(), llvm::MDBuilder::createRange(), llvm::OpenMPIRBuilder::createReductions(), llvm::DIBuilder::createReferenceType(), llvm::MachineOperand::CreateReg(), llvm::MachineOperand::CreateRegLiveOut(), llvm::MachineOperand::CreateRegMask(), llvm::VPRecipeBuilder::createReplicateRegion(), llvm::orc::JITDylib::createResourceTracker(), createResumeEntryBlock(), llvm::DDGBuilder::createRootedEdge(), llvm::DDGBuilder::createRootNode(), llvm::createSanitizerCtorAndInitFunctions(), llvm::MatrixBuilder::CreateScalarDiv(), createScratchRegisterForInstruction(), llvm::jitlink::LinkGraph::createSection(), llvm::OpenMPIRBuilder::createSections(), llvm::createSelectCmpTargetReduction(), llvm::IRBuilderBase::CreateSExtOrTrunc(), llvm::Attributor::createShallowWrapper(), createSPIRVMCInstPrinter(), llvm::createSplat2ShuffleMask(), llvm::MachineFrameInfo::CreateStackObject(), llvm::SelectionDAG::CreateStackTemporary(), llvm::createStepForVF(), CreateStepValue(), llvm::DIBuilder::createStringType(), llvm::IRBuilderBase::CreateStripInvariantGroup(), llvm::MatrixBuilder::CreateSub(), createSwitchStatement(), createTargetMachine(), llvm::PPCInstrInfo::CreateTargetPostRAHazardRecognizer(), llvm::OpenMPIRBuilder::createTask(), createTblForTrunc(), createTblShuffleForZExt(), llvm::DIBuilder::createTemplateTypeParameter(), createTemplateValueParameterHelper(), llvm::sys::fs::createTemporaryFile(), llvm::IRBuilderBase::CreateThreadLocalAddress(), llvm::ThunkInserter< Derived, InsertedThunksTy >::createThunkFunction(), createTileStore(), llvm::createTripCountSCEV(), createTuple(), llvm::createUnaryMask(), llvm::createUnpackShuffleMask(), llvm::DIBuilder::createUnspecifiedType(), createVariablePermute(), llvm::VectorBuilder::createVectorInstruction(), llvm::InnerLoopVectorizer::createVectorLoopSkeleton(), llvm::IRBuilderBase::CreateVectorSplat(), llvm::IRBuilderBase::CreateVectorSplice(), llvm::MachineRegisterInfo::createVirtualRegister(), CreateVPTBlock(), llvm::RegisterBankInfo::OperandsMapper::createVRegs(), llvm::IRBuilderBase::CreateVScale(), createWidenInductionRecipes(), llvm::X86_MC::createX86MCSubtargetInfo(), llvm::IRBuilderBase::CreateZExtOrTrunc(), llvm::sampleprof::CSProfileConverter::CSProfileConverter(), cvtVOP3DstOpSelOnly(), llvm::mca::Instruction::cycleEvent(), llvm::mca::EntryStage::cycleResume(), llvm::SMSchedule::cycleScheduled(), llvm::mca::DispatchStage::cycleStart(), llvm::mca::InOrderIssueStage::cycleStart(), darwinHasSinCos(), llvm::orc::shared::WrapperFunctionResult::data(), llvm::sys::fs::mapped_file_region::data(), llvm::CallBase::dataOperandHasImpliedAttr(), llvm::DbgCallSiteParam::DbgCallSiteParam(), DbgRewriteSalvageableDVIs(), LiveDebugValues::DbgValue::DbgValue(), llvm::DbgValueLoc::DbgValueLoc(), LiveDebugValues::DbgValueProperties::DbgValueProperties(), llvm::DCData::DCData(), llvm::CCState::DeallocateReg(), llvm::MachineInstr::debug_operands(), llvm::MCSymbol::declareCommon(), llvm::declareSanitizerInitFunction(), llvm::coro::declaresAnyIntrinsic(), llvm::coro::declaresIntrinsics(), llvm::RuntimeDyldMachOAArch64::decodeAddend(), DecodeANDI16Imm(), decodeB4constOperand(), decodeB4constuOperand(), decodeBase64StringEntry(), decodeBDAddr12Operand(), decodeBDAddr20Operand(), decodeBDLAddr12Len4Operand(), decodeBDLAddr12Len8Operand(), decodeBDRAddr12Operand(), decodeBDVAddr12Operand(), decodeBDXAddr12Operand(), decodeBDXAddr20Operand(), decodeBranchOperand(), decodeCallOperand(), llvm::BitCodeAbbrevOp::DecodeChar6(), decodeCLUIImmOperand(), decodeCRBitMOperand(), DecodeFixedType(), llvm::AMDGPUDisassembler::decodeFPImmed(), llvm::codeview::decodeFramePtrReg(), decodeFRMArg(), decodeImm12Operand(), decodeImm1_16Operand(), decodeImm8_sh8Operand(), decodeImm8Operand(), llvm::DecodeInsertElementMask(), DecodeINSVE_DF(), llvm::AMDGPUDisassembler::decodeIntImmed(), decodeJMPIXImmOperand(), decodeJumpOperand(), llvm::AMDGPUDisassembler::decodeKernelDescriptorDirective(), decodeL32ROperand(), decodeLLVMAttributesForBitcode(), llvm::AArch64_AM::decodeLogicalImmediate(), decodeLRW16Imm8(), llvm::AMDGPUDisassembler::decodeMandatoryLiteralConstant(), decodeMem16Operand(), decodeMem32Operand(), decodeMem8Operand(), DecodeMSA128Mem(), decodeMultiByteChar(), decodeOImmOperand(), llvm::decodePackedBCD(), decodePCDBLOperand(), llvm::DecodePSHUFBMask(), decodeRegisterClass(), DecodeRegSeqOperand(), DecodeRegSeqOperandD1(), DecodeRegSeqOperandD2(), DecodeRegSeqOperandF1(), DecodeRegSeqOperandF2(), decodeRVCInstrRdRs1ImmZero(), decodeRVCInstrRdRs1UImm(), decodeRVCInstrRdSImm(), llvm::AMDGPUDisassembler::decodeSDWAVopcDst(), decodeShimm1_31Operand(), decodeSImmOperand(), decodeSImmOperandAndLsl1(), llvm::AMDGPUDisassembler::decodeSrcOp(), DecodeT2Adr(), decodeUimm4Operand(), decodeUimm5Operand(), decodeUImmOperand(), llvm::DecodeVALIGNMask(), llvm::AMDGPUDisassembler::decodeVOPDDstYOp(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPPERMMask(), llvm::RISCVVType::decodeVSEW(), llvm::DecodeZeroExtendMask(), decomposeGEP(), llvm::AArch64InstrInfo::decomposeStackOffsetForDwarfOffsets(), llvm::AArch64InstrInfo::decomposeStackOffsetForFrameOffsets(), decreaseSetPressure(), llvm::def_chain(), llvm::orc::JITDylib::define(), definesFullReg(), LiveDebugValues::VLocTracker::defVar(), llvm::orc::LLJIT::deinitialize(), llvm::DeleteDeadBlocks(), llvm::deleteDeadLoop(), llvm::DominatorTreeBase< BasicBlock, false >::deleteEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), deleteLoopIfDead(), llvm::MachineFunction::deleteMachineBasicBlock(), llvm::MachineFunction::deleteMachineInstr(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::MDNode::deleteTemporary(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::denormalize(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::denormalize(), llvm::DependenceInfo::depends(), llvm::orc::ExecutionSession::deregisterResourceManager(), llvm::HexagonMCInstrInfo::deriveDuplex(), llvm::HexagonMCInstrInfo::deriveExtender(), llvm::HexagonMCInstrInfo::deriveSubInst(), llvm::InstCombinerImpl::Descale(), llvm::X86InstrInfo::describeLoadedValue(), llvm::TargetInstrInfo::describeLoadedValue(), describeMOVrrLoadedValue(), describeORRLoadedValue(), llvm::PPCSubtarget::descriptorEnvironmentPointerOffset(), llvm::PPCSubtarget::descriptorTOCAnchorOffset(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >::deserialize(), llvm::deserializeSectionKind(), llvm::ManagedStaticBase::destroy(), llvm::Constant::destroyConstant(), llvm::detachDeadBlocks(), detectPMADDUBSW(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), detectSSatPattern(), detectUSatPattern(), llvm::HexagonDAGToDAGISel::DetectUseSxtw(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::AArch64FrameLowering::determineCalleeSaves(), determineLastCalleeSave(), determineLiveOperandBitsAddCarry(), llvm::SIFrameLowering::determinePrologEpilogSGPRSaves(), llvm::DWARFUnit::determineStringOffsetsTableContribution(), llvm::DWARFUnit::determineStringOffsetsTableContributionDWO(), determineSVEStackObjectOffsets(), llvm::MCContext::diagnose(), llvm::LTOCodeGenerator::DiagnosticHandler(), llvm::DIEUnit::DIEUnit(), llvm::DIExpressionCursor::DIExpressionCursor(), llvm::DIMacroNode::DIMacroNode(), llvm::DINode::DINode(), llvm::vfs::directory_iterator::directory_iterator(), llvm::MachineRegisterInfo::disableCalleeSavedRegister(), llvm::VPBlockUtils::disconnectBlocks(), llvm::RegPressureTracker::discoverLiveInOrOut(), llvm::ModuleSummaryIndex::discoverNodes(), llvm::mca::Scheduler::dispatch(), llvm::mca::LSUnit::dispatch(), llvm::mca::Instruction::dispatch(), llvm::orc::ExecutionSession::dispatchTask(), llvm::IntervalMapImpl::distribute(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::BlockFrequencyInfoImplBase::distributeIrrLoopHeaderMass(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::DistributeRange(), llvm::SCEVDivision::divide(), llvm::LLT::divide(), llvm::detail::DoubleAPFloat::divide(), llvm::APFloat::divide(), llvm::ScaledNumbers::divide32(), llvm::ScaledNumbers::divide64(), llvm::CastInfoPointerUnionImpl< PTs >::doCast(), doemit(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::AsmPrinter::doFinalization(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), dofwd(), llvm::AsmPrinter::doInitialization(), doinsert(), llvm::isa_impl_cl< To, const std::unique_ptr< From > >::doit(), llvm::isa_impl_cl< To, From * >::doit(), llvm::isa_impl_cl< To, From *const >::doit(), llvm::isa_impl_cl< To, const From * >::doit(), llvm::isa_impl_cl< To, const From *const >::doit(), llvm::PostDominatorTree::dominates(), llvm::Trace::dominates(), llvm::LexicalScopes::dominates(), llvm::CombinerHelper::dominates(), llvm::DominatorTree::dominates(), llvm::DominatorTreeBase< BasicBlock, false >::dominates(), llvm::InstCombinerImpl::dominatesAllUses(), dominatesAllUsesOf(), doPromotion(), llvm::detail::DoubleAPFloat::DoubleAPFloat(), llvm::ArrayRef< uint64_t >::drop_back(), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::drop_back(), llvm::StringRef::drop_back(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::drop_back(), llvm::ArrayRef< uint64_t >::drop_front(), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::drop_front(), llvm::StringRef::drop_front(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::drop_front(), PODSmallVector< Node *, 8 >::dropBack(), llvm::Value::dropDroppableUsesIn(), llvm::Instruction::dropPoisonGeneratingFlags(), dropRedundantMaskingOfLeftShiftInput(), dropRegDescribedVar(), dropTypeTests(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::DomTreeUpdater::dump(), llvm::DWARFDebugNames::Entry::dump(), llvm::PBQP::RegAlloc::PBQPRAGraph::dump(), dumpApplePropertyAttribute(), llvm::PMTopLevelManager::dumpArguments(), dumpLocationExpr(), dumpLocationList(), dupl(), llvm::TargetInstrInfo::duplicate(), llvm::JumpThreadingPass::duplicateCondBranchOnPHIIntoPred(), duplicateCPV(), llvm::DuplicateInstructionsInSplitBetween(), llvm::DWARFExpression::DWARFExpression(), llvm::gsym::CUInfo::DWARFToGSYMFileIndex(), llvm::dyn_cast(), llvm::BitTracker::MachineEvaluator::eADD(), llvm::BitTracker::MachineEvaluator::eAND(), earlyExpandDIVFIX(), llvm::BitTracker::MachineEvaluator::eASL(), llvm::BitTracker::MachineEvaluator::eASR(), eat12Bytes(), eatBytes(), llvm::BitTracker::MachineEvaluator::eCLR(), llvm::ehAwareSplitEdge(), llvm::BitTracker::MachineEvaluator::eIMM(), llvm::BitTracker::MachineEvaluator::eINS(), llvm::yaml::SequenceTraits< ArrayRef< T > >::element(), elementPairIsContiguous(), llvm::object::elf_section_iterator::elf_section_iterator(), llvm::object::ELFRelocationRef::ELFRelocationRef(), llvm::object::ELFSectionRef::ELFSectionRef(), llvm::object::ELFSymbolRef::ELFSymbolRef(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::WebAssemblyFrameLowering::eliminateCallFramePseudoInstr(), llvm::AVRFrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::SystemZFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::ARCFrameLowering::eliminateCallFramePseudoInstr(), llvm::SIFrameLowering::eliminateCallFramePseudoInstr(), llvm::HexagonFrameLowering::eliminateCallFramePseudoInstr(), eliminateDeadSwitchCases(), EliminateDuplicatePHINodesSetBasedImpl(), llvm::BPFRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::LanaiRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::VERegisterInfo::eliminateFrameIndex(), llvm::WebAssemblyRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::CSKYRegisterInfo::eliminateFrameIndex(), llvm::AVRRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::ARCRegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), eliminateSwiftErrorAlloca(), llvm::BitTracker::MachineEvaluator::eLSR(), EltsFromConsecutiveLoads(), llvm::embedBitcodeInModule(), llvm::orc::ObjectTransformLayer::emit(), llvm::orc::IRTransformLayer::emit(), llvm::orc::IRCompileLayer::emit(), llvm::orc::RTDyldObjectLinkingLayer::emit(), llvm::orc::CompileOnDemandLayer::emit(), llvm::orc::ObjectLinkingLayer::emit(), llvm::remarks::BitstreamRemarkSerializer::emit(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::MCPseudoProbe::emit(), llvm::orc::IRSpeculationLayer::emit(), llvm::BitstreamWriter::Emit(), llvm::MCPseudoProbeInlineTree::emit(), llvm::MCDwarfLineTableHeader::Emit(), llvm::AppleAccelTableOffsetData::emit(), llvm::AppleAccelTableTypeData::emit(), llvm::AsmPrinter::XRayFunctionEntry::emit(), llvm::MCGenDwarfInfo::Emit(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::emitAMDGPUPrintfCall(), llvm::AArch64TargetWinCOFFStreamer::emitARM64WinCFIAddFP(), llvm::AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveFReg(), llvm::AArch64TargetWinCOFFStreamer::emitARM64WinCFISaveReg(), llvm::emitARMRegPlusImmediate(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitBasicBlockLoopComments(), llvm::AsmPrinter::emitBasicBlockStart(), llvm::AsmPrinter::emitBBAddrMapSection(), llvm::emitBinaryFloatFnCall(), emitBinaryFloatFnCallHelper(), llvm::BitstreamWriter::emitBlob(), emitBuildPairF64Pseudo(), llvm::MCELFStreamer::emitBundleAlignMode(), llvm::MCELFStreamer::emitBundleUnlock(), llvm::OpenMPIRBuilder::emitCancelationCheckImpl(), llvm::StringToOffsetTable::EmitCharArray(), EmitCMP(), EmitCmp(), emitComparison(), emitConditionalComparison(), emitConjunctionRec(), llvm::WebAssemblyAsmPrinter::emitConstantPool(), emitConstantSizeRepmov(), emitDarwinBCHeaderAndTrailer(), llvm::memprof::RecordWriterTrait::EmitData(), emitDbgAssign(), llvm::InstrEmitter::EmitDbgLabel(), llvm::InstrEmitter::EmitDbgValue(), llvm::InstrEmitter::EmitDbgValueFromSingleOp(), llvm::DWARFYAML::emitDebugAranges(), llvm::DWARFYAML::emitDebugGNUPubnames(), llvm::DWARFYAML::emitDebugGNUPubtypes(), llvm::DWARFYAML::emitDebugLoclists(), llvm::DwarfDebug::emitDebugLocValue(), llvm::DWARFYAML::emitDebugPubnames(), llvm::DWARFYAML::emitDebugPubtypes(), llvm::DWARFYAML::emitDebugRnglists(), llvm::DWARFYAML::emitDebugStrOffsets(), llvm::APByteStreamer::emitDIERef(), llvm::BufferByteStreamer::emitDIERef(), llvm::emitDWARF5AccelTable(), llvm::AsmPrinter::emitDwarfDIE(), llvm::AsmPrinter::emitDwarfLengthOrOffset(), llvm::AsmPrinter::emitDwarfStringOffset(), llvm::AsmPrinter::emitDwarfSymbolReference(), llvm::MCStreamer::emitDwarfUnitLength(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AMDGPUAsmPrinter::emitEndOfAsmFile(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::AVRFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::LoongArchFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::SystemZELFFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::M68kFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SystemZXPLINKFrameLowering::emitEpilogue(), llvm::LLVMContext::emitError(), llvm::EHStreamer::emitExceptionTable(), llvm::SITargetLowering::emitExpandAtomicRMW(), emitExternalFile(), llvm::MCObjectStreamer::emitFill(), llvm::emitFrameOffset(), emitFrameOffsetAdj(), emitFROUND(), llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart(), llvm::HexagonDAGToDAGISel::emitFunctionEntryCode(), llvm::WebAssemblyTargetAsmStreamer::emitFunctionType(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), llvm::ExecutionEngine::emitGlobals(), llvm::WebAssemblyTargetAsmStreamer::emitGlobalType(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::AsmPrinter::emitGlobalVariable(), emitIndirectDst(), llvm::AsmPrinter::emitInitialRawDwarfLocDirective(), llvm::HexagonMCELFStreamer::emitInstruction(), llvm::HexagonAsmPrinter::emitInstruction(), llvm::HexagonHazardRecognizer::EmitInstruction(), llvm::ARMAsmPrinter::emitInstruction(), llvm::SystemZHazardRecognizer::EmitInstruction(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::SystemZHazardRecognizer::emitInstruction(), llvm::X86AsmPrinter::emitInstruction(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::AVRTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::RISCVTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), emitIntrinsicWithCCAndChain(), llvm::MCStreamer::emitIntValue(), emitInvalidCostRemarks(), llvm::InnerLoopVectorizer::emitIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitIterationCountCheck(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV3::emitKernel(), emitKill(), llvm::MCStreamer::emitLabel(), llvm::MCObjectStreamer::emitLabelAtPos(), emitLoad(), llvm::ThumbRegisterInfo::emitLoadConstPool(), llvm::HexagonTargetLowering::emitLoadLinked(), emitLoadSRsrcFromVGPRLoop(), LiveDebugValues::MLocTracker::emitLoc(), llvm::DwarfStreamer::emitLocationsForUnit(), llvm::AArch64TargetLowering::EmitLoweredCatchRet(), llvm::CSKYAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::DwarfStreamer::emitMacroTables(), llvm::PPCTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::PPCTargetLowering::emitMaskedAtomicRMWIntrinsic(), emitMemMemImm(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaBlock(), llvm::EpilogueVectorizerEpilogueLoop::emitMinimumVectorEpilogueIterCountCheck(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), emitNop(), llvm::MCObjectStreamer::emitNops(), llvm::MCJIT::emitObject(), llvm::OpenMPIRBuilder::emitOffloadingArraysArgument(), emitOneV5FileEntry(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::AsmPrinter::emitPCSections(), emitPostLd(), emitPostSt(), llvm::PPCTargetLowering::emitProbedAlloca(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::SIFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::VEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::LanaiFrameLowering::emitPrologue(), llvm::WebAssemblyFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::M68kFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), emitRangeList(), emitReadCycleWidePseudo(), llvm::AsmPrinter::emitRemarksSection(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::emitSourceFileHeader(), llvm::AsmPrinter::emitSpecialLLVMGlobal(), emitSplitF64Pseudo(), llvm::X86FrameLowering::emitSPUpdate(), llvm::AsmPrinter::emitStackMaps(), emitStore(), llvm::HexagonTargetLowering::emitStoreConditional(), emitStrictFPComparison(), llvm::StringToOffsetTable::EmitString(), llvm::MCWasmStreamer::emitSymbolAttribute(), llvm::MCStreamer::emitSymbolValue(), llvm::emitT2RegPlusImmediate(), llvm::WebAssemblyTargetAsmStreamer::emitTableType(), llvm::WebAssemblyTargetAsmStreamer::emitTagType(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), emitTransformedIndex(), emitUnaryFloatFnCallHelper(), EmitUnwindInfo(), llvm::DIEBaseTypeRef::emitValue(), llvm::BitstreamWriter::EmitVBR(), llvm::BitstreamWriter::EmitVBR64(), EmitVectorComparison(), llvm::MCStreamer::emitVersionForTarget(), emitVFCVT_RM_MASK(), emitVFROUND_NOEXCEPT_MASK(), emitX86Nops(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::BlotMapVector< KeyT, ValueT >::empty(), llvm::AnalysisManager< MachineFunction >::empty(), llvm::jitlink::SectionRange::empty(), llvm::PPCTargetLowering::enableAggressiveFMAFusion(), enableAllocFrameElim(), llvm::ARMFrameLowering::enableCalleeSaveSkip(), llvm::HexagonFrameLowering::enableCalleeSaveSkip(), llvm::TargetFrameLowering::enableCalleeSaveSkip(), llvm::Automaton< uint64_t >::enableTranscription(), llvm::MCDwarfLineAddr::Encode(), llvm::RuntimeDyldMachOAArch64::encodeAddend(), llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc(), encodeBase64StringEntry(), encodeCounter(), llvm::CodeViewContext::encodeDefRange(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::HexagonMCCodeEmitter::encodeInstruction(), llvm::RISCVVType::encodeLMUL(), llvm::AArch64_AM::encodeLogicalImmediate(), llvm::ARM_AM::encodeNEONi16splat(), llvm::ARM_AM::encodeNEONi32splat(), llvm::gsym::encodeRange(), llvm::COFF::encodeSectionName(), llvm::RISCVVType::encodeSEW(), llvm::HexagonMCCodeEmitter::EncodeSingleInstruction(), llvm::RISCVVType::encodeVTYPE(), llvm::TimeTraceProfiler::end(), llvm::DbgValueHistoryMap::Entry::endEntry(), llvm::WasmException::endFunction(), llvm::AIXException::endFunction(), llvm::CodeViewDebug::endFunctionImpl(), llvm::DwarfDebug::endFunctionImpl(), llvm::LiveRange::endIndex(), llvm::DebugHandlerBase::endInstruction(), llvm::DwarfDebug::endModule(), llvm::codeview::CodeViewRecordIO::endRecord(), llvm::RegAllocBase::enqueue(), llvm::MachineFrameInfo::ensureMaxAlignment(), ensurePromotedGV(), ensureValueAvailableInSuccessor(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvAtEnd(), llvm::SplitEditor::enterIntvBefore(), llvm::SystemZPostRASchedStrategy::enterMBB(), llvm::ScheduleDAGInstrs::enterRegion(), llvm::ScheduleDAGMILive::enterRegion(), llvm::EnumAttributeImpl::EnumAttributeImpl(), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::EnumeratedArray(), llvm::yaml::ScalarEnumerationTraits< ELFYAML::ELF_SHT >::enumeration(), llvm::yaml::ScalarEnumerationTraits< ELFYAML::ELF_SHN >::enumeration(), llvm::yaml::ScalarEnumerationTraits< ELFYAML::ELF_REL >::enumeration(), llvm::yaml::ScalarEnumerationTraits< ELFYAML::ELF_DYNTAG >::enumeration(), llvm::BitTracker::MachineEvaluator::eORL(), llvm::EpilogueLoopVectorizationInfo::EpilogueLoopVectorizationInfo(), llvm::ARM::WinEH::ExceptionDataRecord::EpilogueScopes(), llvm::vfs::Status::equivalent(), llvm::sampleprof::DefaultFunctionPruningStrategy::Erase(), llvm::PriorityWorklist< llvm::LazyCallGraph::SCC *, SmallVector< llvm::LazyCallGraph::SCC *, N >, SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t > >::erase(), llvm::SetVector< llvm::MCSection *, SmallVector< llvm::MCSection *, N >, SmallDenseSet< llvm::MCSection *, N > >::erase(), llvm::MapVector< AssertingVH< Instruction >, AssertingVH< Value > >::erase(), llvm::simple_ilist< MachineInstr, Options... >::erase(), llvm::TinyPtrVector< llvm::VPValue * >::erase(), llvm::SparseSet< RootData >::erase(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::erase(), llvm::SmallVectorImpl< uint64_t >::erase(), llvm::LoopInfo::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::SmallPtrSetImplBase::erase_imp(), llvm::BranchProbabilityInfo::eraseBlock(), llvm::MachineFunction::eraseCallSiteInfo(), llvm::MachineInstr::eraseFromBundle(), llvm::VPRecipeBase::eraseFromParent(), llvm::MachineBasicBlock::eraseFromParent(), llvm::MachineInstr::eraseFromParent(), llvm::InstCombinerImpl::eraseInstFromFunction(), llvm::objcarc::EraseInstruction(), llvm::DominatorTreeBase< BasicBlock, false >::eraseNode(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode(), error(), llvm::MIRParserImpl::error(), llvm::BitTracker::MachineEvaluator::eSET(), llvm::BitTracker::MachineEvaluator::eSUB(), llvm::BitTracker::MachineEvaluator::eSXT(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::eval(), llvm::HexagonEvaluator::evaluate(), llvm::BitTracker::MachineEvaluator::evaluate(), llvm::SCEVAddRecExpr::evaluateAtIteration(), EvaluateConstantChrecAtConstant(), evaluateFCmpRelation(), llvm::Evaluator::EvaluateFunction(), evaluateICmpRelation(), evaluateInDifferentElementOrder(), evaluateMemOpAddrForAddrModeT2_i8s4(), llvm::JumpThreadingPass::evaluateOnPredecessorEdge(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerParameter(), llvm::ARM::WinEH::ExceptionDataRecord::ExceptionHandlerRVA(), llvm::ARM::WinEH::RuntimeFunction::ExceptionInformationRVA(), llvm::ARM::WinEH::RuntimeFunctionARM64::ExceptionInformationRVA(), llvm::execMayBeModifiedBeforeAnyUse(), llvm::execMayBeModifiedBeforeUse(), llvm::mca::EntryStage::execute(), llvm::mca::RetireStage::execute(), llvm::mca::ExecuteStage::execute(), llvm::mca::DispatchStage::execute(), llvm::mca::Instruction::execute(), llvm::VPInstruction::execute(), llvm::VPWidenCallRecipe::execute(), llvm::VPWidenGEPRecipe::execute(), llvm::VPWidenIntOrFpInductionRecipe::execute(), llvm::VPWidenPointerInductionRecipe::execute(), llvm::VPWidenPHIRecipe::execute(), llvm::VPReductionPHIRecipe::execute(), llvm::VPInterleaveRecipe::execute(), llvm::VPReductionRecipe::execute(), llvm::VPReplicateRecipe::execute(), llvm::VPBranchOnMaskRecipe::execute(), llvm::VPPredInstPHIRecipe::execute(), llvm::VPWidenMemoryInstructionRecipe::execute(), llvm::VPExpandSCEVRecipe::execute(), llvm::VPDerivedIVRecipe::execute(), llvm::VPBasicBlock::execute(), llvm::sys::ExecuteAndWait(), executeFCMP_BOOL(), executeFCMP_ORD(), executeFCMP_UNO(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::InstructionSelector::executeMatchTable(), llvm::sys::ExecuteNoWait(), llvm::objcopy::xcoff::executeObjcopyOnBinary(), llvm::objcopy::wasm::executeObjcopyOnBinary(), llvm::objcopy::coff::executeObjcopyOnBinary(), llvm::LoopVectorizationPlanner::executePlan(), executeSelectInst(), llvm::BitstreamWriter::ExitBlock(), llvm::ScalarEvolution::ExitLimit::ExitLimit(), llvm::BitTracker::MachineEvaluator::eXOR(), llvm::PeelingModuloScheduleExpander::expand(), Expand2AddrKreg(), Expand2AddrUndef(), Expand64BitShift(), ExpandBasePaths(), llvm::SCEVExpander::expandCodeForPredicate(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::TargetLowering::expandDIVREMByConstant(), llvm::TargetLowering::expandFixedPointDiv(), expandFP_TO_UINT_SSE(), ExpandHorizontalBinOp(), expandIntrinsicWChainHelper(), llvm::TargetLowering::expandIS_FPCLASS(), expandIToFP(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::SIInstrInfo::expandMovDPP64(), llvm::M68kInstrInfo::ExpandMOVEM(), llvm::AArch64_IMM::expandMOVImm(), ExpandMOVImmSExti8(), llvm::M68kInstrInfo::ExpandMOVSZX_RM(), llvm::M68kInstrInfo::ExpandMOVSZX_RR(), llvm::M68kInstrInfo::ExpandMOVX_RR(), llvm::TargetLowering::expandMUL(), llvm::TargetLowering::expandMUL_LOHI(), llvm::SparcInstrInfo::expandPostRAPseudo(), llvm::VEInstrInfo::expandPostRAPseudo(), llvm::HexagonInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::PPCInstrInfo::expandPostRAPseudo(), llvm::expandPredBlockMask(), ExpandREAD_REGISTER(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), expandSGPRCopy(), llvm::HexagonBlockRanges::expandToSubRegs(), expandUDivOrURem(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::TargetLowering::expandVPBITREVERSE(), llvm::ModuleSummaryIndex::exportToDot(), llvm::LiveRangeCalc::extend(), llvm::HexagonMCInstrInfo::extenderForIndex(), llvm::LexicalScope::extendInsnRange(), extendLow32IntoHigh32(), llvm::LiveIntervals::extendToIndices(), ExtendToType(), llvm::BitTracker::MachineEvaluator::eXTR(), llvm::RangeListEntry::extract(), llvm::DWARFDebugArangeSet::extract(), llvm::LiveIntervalUnion::extract(), llvm::DWARFListTableBase< DWARFDebugRnglist >::extract(), llvm::BitTracker::RegisterCell::extract(), extract128BitVector(), extract256BitVector(), llvm::AlignmentFromAssumptionsPass::extractAlignmentInfo(), ExtractBitFromMaskVector(), llvm::APInt::extractBits(), llvm::DecoderUInt128::extractBitsAsZExtValue(), llvm::APInt::extractBitsAsZExtValue(), extractBranchProbabilities(), llvm::extractBranchWeights(), llvm::CodeExtractor::extractCodeRegion(), ExtractConstantBytes(), llvm::extractConstantMask(), llvm::DWARFDebugInfoEntry::extractFast(), extractInteger(), extractMaskedValue(), extractMDNode(), llvm::DWARFDebugAddrTable::extractPreStandard(), llvm::extractProbeFromDiscriminator(), llvm::extractProfTotalWeight(), llvm::Instruction::extractProfTotalWeight(), llvm::DWARFUnit::extractRangeList(), extractShiftForRotate(), extractSubModule(), extractSubVector(), llvm::ExtractTypeInfo(), extractVector(), llvm::BitTracker::MachineEvaluator::eZXT(), llvm::ARM::WinEH::ExceptionDataRecord::F(), f64AssignAAPCS(), factorizeFAddFSub(), factorizeMathWithShlOps(), factorizeMinMaxTree(), llvm::orc::FailedToMaterialize::FailedToMaterialize(), llvm::FastISel::fastEmitInst_extractsubreg(), fcmpToClassTest(), llvm::LegalizerHelper::fewerElementsVector(), llvm::LegalizerHelper::fewerElementsVectorExtractInsertVectorElt(), llvm::LegalizerHelper::fewerElementsVectorMerge(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorReductions(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), llvm::LegalizerHelper::fewerElementsVectorUnmergeValues(), llvm::FileCollector::FileCollector(), llvm::object::XCOFFObjectFile::fileHeader32(), llvm::object::XCOFFObjectFile::fileHeader64(), llvm::BitTracker::RegisterCell::fill(), llvm::PeelingModuloScheduleExpander::filterInstructions(), llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc::finalize(), llvm::StringTableBuilder::finalize(), llvm::GISelWorkList< 8 >::finalize(), llvm::UnwindOpcodeAssembler::Finalize(), llvm::CallGraphUpdater::finalize(), llvm::DIBuilder::finalize(), llvm::OpenMPIRBuilder::finalize(), llvm::DebugLocEntry::finalize(), llvm::DwarfExpression::finalize(), llvm::SchedDFSImpl::finalize(), BoUpSLP::ShuffleInstructionBuilder::finalize(), llvm::orc::DebugObject::finalizeAsync(), llvm::RuntimeDyldImpl::finalizeAsync(), llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), llvm::finalizeBundle(), llvm::finalizeBundles(), llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc::FinalizedAlloc(), llvm::MachineFunction::finalizeDebugInstrRefs(), llvm::DwarfExpression::finalizeEntryValue(), llvm::RISCVInstrInfo::finalizeInsInstrs(), llvm::PPCInstrInfo::finalizeInsInstrs(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::SITargetLowering::finalizeLowering(), llvm::MCJIT::finalizeModule(), llvm::rdf::IndexedSet< const uint32_t * >::find(), llvm::pdb::HashTable< llvm::support::detail::packed_endian_specific_integral >::find_as(), llvm::SparseBitVectorElement< ElementSize >::find_next(), llvm::find_singleton_nested(), llvm::findAllocaForValue(), llvm::CodeExtractor::findAllocas(), llvm::PMTopLevelManager::findAnalysisPassInfo(), findBaseDefiningValue(), findBaseDefiningValueCached(), findBaseDefiningValueOfVector(), findBasePointers(), llvm::RegBankSelect::findBestMapping(), findBestNonTrivialUnswitchCandidate(), llvm::SwitchCG::SwitchLowering::findBitTestClusters(), findBuildAggregate(), llvm::orc::SpeculateQuery::findCalles(), FindCallSeqStart(), findCanonNumsForPHI(), llvm::WebAssembly::findCatch(), findCommonDominator(), llvm::MipsInstrInfo::findCommutedOpIndices(), llvm::RISCVInstrInfo::findCommutedOpIndices(), llvm::TargetInstrInfo::findCommutedOpIndices(), findCondCodeUseOperandIdxForBranchOrSelect(), llvm::OutlinableRegion::findCorrespondingBlockIn(), llvm::OutlinableRegion::findCorrespondingValueIn(), findDemandedEltsBySingleUser(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), llvm::FindEarliestCapture(), llvm::DGNode< NodeType, EdgeType >::findEdgesTo(), llvm::logicalview::LVScope::findEqualScope(), llvm::logicalview::LVScopeAggregate::findEqualScope(), llvm::logicalview::LVScopeFunction::findEqualScope(), llvm::logicalview::LVScopeNamespace::findEqualScope(), findExtractedInputToOverallInputMapping(), FindFirstNonCommonLetter(), findFirstNonVersionCharacter(), findForkedPointer(), llvm::IntervalMapImpl::LeafNode< uint64_t, uint16_t, N, IntervalMapHalfOpenInfo< uint64_t > >::findFrom(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, RootBranchCap, Traits >::findFrom(), findFuncPointers(), llvm::sampleprof::FunctionSamples::findFunctionSamples(), findGISelOptimalMemOpLowering(), llvm::DirectedGraph< NodeType, EdgeType >::findIncomingEdgesToNode(), llvm::SparseSet< RootData >::findIndex(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::findIndex(), llvm::LiveRange::findIndexesLiveAt(), llvm::sys::Process::FindInEnvPath(), llvm::MachineInstr::findInlineAsmFlagIdx(), llvm::FindInsertedValue(), llvm::SCEVExpander::findInsertPointAfter(), findIrreducibleHeaders(), llvm::SwitchCG::SwitchLowering::findJumpTables(), llvm::IntEqClasses::findLeader(), findLiveSetAtInst(), findLocationForEntrySafepoint(), FindLoopCounter(), FindMatchingEpilog(), findMatchingInlineAsmOperand(), llvm::findMaximalSubpartOfIllFormedUTF8Sequence(), findMemSDNode(), llvm::SelectionDAGBuilder::FindMergedConditions(), findMostPopularDest(), findmust(), llvm::opt::OptTable::findNearest(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::DominatorTreeBase< BasicBlock, false >::findNearestCommonDominator(), llvm::TargetLowering::findOptimalMemOpLowering(), llvm::findOptionMDForLoopID(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), findOrCreatePHIBlock(), findOrCreatePHIInBlock(), findOutputValueInRegion(), FindPHIForConditionForwarding(), llvm::orc::LocalIndirectStubsManager< TargetT >::findPointer(), FindPreallocatedCall(), findPreviousSpillSlot(), llvm::SIRegisterInfo::findReachingDef(), findRedundantFlagInstr(), findReturnsToZap(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::ScheduleDAGMI::findRootsAndBiasEdges(), llvm::findScalarElement(), findSection(), llvm::SSAUpdaterImpl< UpdaterT >::FindSingularVal(), findStartOfTree(), findStrip(), llvm::orc::LocalIndirectStubsManager< TargetT >::findStub(), findSurvivorBackwards(), llvm::sys::unicode::findSyllable(), llvm::jitlink::MachOLinkGraphBuilder::findSymbolByIndex(), findTargetSubtable(), llvm::MachineInstr::findTiedOperandIdx(), findUnwindDestinations(), llvm::FunctionPropertiesUpdater::finish(), llvm::SpillPlacement::finish(), llvm::SplitEditor::finish(), finishCallSiteParams(), llvm::ItaniumPartialDemangler::finishDemangle(), llvm::LoopBlocksTraversal::finishPostorder(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), firstch(), llvm::R600InstrInfo::fitsConstReadLimitations(), llvm::FixedPointSemantics::FixedPointSemantics(), llvm::FixedScalableVFPair::FixedScalableVFPair(), llvm::FixedStreamArray< PSHashRecord >::FixedStreamArray(), fixFuncEntryCount(), llvm::InnerLoopVectorizer::fixReduction(), fixRegionTerminator(), llvm::fixStackStores(), fixupCalleeSaveRestoreStackOffset(), fixupDebugInfoPostExtraction(), llvm::CompileUnit::fixupForwardReferences(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), llvm::InnerLoopVectorizer::fixupIVUsers(), fixupOrderingIndices(), fixupPHIOpBanks(), fixupVariableFloatArgs(), llvm::APInt::flipBit(), llvm::LiveRangeUpdater::flush(), llvm::MCObjectStreamer::flushPendingLabels(), llvm::LiveRange::flushSegmentSet(), fmed3AMDGCN(), llvm::AMDGPULibCalls::fold(), llvm::UnOpInit::Fold(), foldAddSubBoolOfMaskedVal(), foldAddSubOfSignBit(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), llvm::InstCombinerImpl::foldAllocaCmp(), foldAndOrOfSETCC(), foldAndToXor(), FoldBitCast(), foldBoolSelectToLogic(), FoldBUILD_VECTOR(), foldCastShuffle(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), foldComplexAndOrPatterns(), foldCONCAT_VECTORS(), llvm::SelectionDAG::FoldConstantArithmetic(), foldConstantCastPair(), foldConstantsIntoIntrinsics(), foldCSELofCTTZ(), foldCtpop(), foldCttzCtlz(), foldExtendedSignBitTest(), foldExtendVectorInregToExtendOfSubvector(), foldExtractSubvectorFromShuffleVector(), foldFabsWithFcmpZero(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), llvm::PPCInstrInfo::foldFrameOffset(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldICmpAddOpConst(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndShift(), llvm::InstCombinerImpl::foldICmpBinOp(), foldICmpIntrinsicWithIntrinsic(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpSelectConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), llvm::InstCombinerImpl::foldICmpShlConstConst(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpShrConstConst(), llvm::InstCombinerImpl::foldICmpUDivConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldICmpWithDominatingICmp(), foldICmpWithLowBitMaskedVal(), foldICmpWithTruncSignExtendedVal(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldIdentityExtractShuffle(), foldIdentityPaddedShuffles(), foldIDivShl(), foldImm(), llvm::VEInstrInfo::FoldImmediate(), llvm::SIInstrInfo::FoldImmediate(), llvm::FoldingSetBase::FoldingSetBase(), foldInsEltIntoIdentityShuffle(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::InstCombinerImpl::foldItoFPtoI(), foldLogicOfShifts(), foldLogicTreeOfShifts(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), foldMaskAndShiftToScale(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldOperationIntoSelectOperand(), foldOrToXor(), foldPatchpoint(), llvm::InstCombinerImpl::foldPHIArgBinOpIntoPHI(), foldSelectICmpAnd(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::foldSelectShuffle(), foldSelectShuffleOfSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftedShift(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), foldShiftOfShiftedBinOp(), foldShuffleWithInsert(), foldSignedTruncationCheck(), foldToUnsignedSaturatedAdd(), foldTruncShuffle(), foldTruncStoreOfExt(), FoldTwoEntryPHINode(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::foldVectorBinop(), foldVGPRCopyIntoRegSequence(), foldXorToXor(), for(), llvm::mca::Instruction::forceExecuted(), forceExpAbs(), forceRenaming(), llvm::AArch64Subtarget::forceStreamingCompatibleSVE(), llvm::forEachCallbackCallSite(), llvm::codeview::detail::GuidAdapter::format(), llvm::format_provider< T, std::enable_if_t< detail::use_integral_formatter< T >::value > >::format(), llvm::format_provider< std::chrono::duration< Rep, Period > >::format(), llvm::format_provider< T, std::enable_if_t< detail::use_string_formatter< T >::value > >::format(), llvm::format_hex(), llvm::format_hex_no_prefix(), llvm::pdb::LinePrinter::formatMsfStreamBlocks(), llvm::pdb::LinePrinter::formatMsfStreamData(), llvm::formDedicatedExitBlocks(), llvm::formLCSSA(), llvm::formLCSSAForInstructions(), formSplatFromShuffles(), llvm::RegScavenger::forward(), llvm::FPExtInst::FPExtInst(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPTruncInst::FPTruncInst(), llvm::ARM::WinEH::RuntimeFunctionARM64::FrameSize(), llvm::MachineRegisterInfo::freezeReservedRegs(), llvm::detail::frexp(), llvm::MCRegister::from(), llvm::CodeViewYAML::fromDebugH(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), llvm::JITSymbolFlags::fromGlobalValue(), llvm::IRSimilarity::IRSimilarityCandidate::fromGVN(), llvm::ConstantRange::fromKnownBits(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::fromSuccessorIndex(), StringView::front(), llvm::SetVector< llvm::MCSection *, SmallVector< llvm::MCSection *, N >, SmallDenseSet< llvm::MCSection *, N > >::front(), llvm::StringRef::front(), llvm::ArrayRef< uint64_t >::front(), llvm::TinyPtrVector< llvm::VPValue * >::front(), llvm::SmallVectorTemplateCommon< T >::front(), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::front(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::front(), llvm::hlsl::FrontendResource::FrontendResource(), llvm::IRPosition::function_scope(), llvm::FunctionCallee::FunctionCallee(), llvm::ARM::WinEH::RuntimeFunction::FunctionLength(), llvm::ARM::WinEH::RuntimeFunctionARM64::FunctionLength(), llvm::FunctionPropertiesUpdater::FunctionPropertiesUpdater(), llvm::detail::DoubleAPFloat::fusedMultiplyAdd(), llvm::APFloat::fusedMultiplyAdd(), FuseInst(), llvm::fuseInstructionPair(), llvm::gatherImportedSummariesForModule(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::TargetInstrInfo::genAlternativeCodeSequence(), generateAssignInstrs(), llvm::RuntimePointerChecking::generateChecks(), llvm::MCJIT::generateCodeForModule(), llvm::generateConvertInst(), generateCreationChecksForBinOp(), llvm::generateEnqueueInst(), generateEquivalentSub(), llvm::generateGroupInst(), llvm::generateImageMiscQueryInst(), llvm::generateImageSizeQueryInst(), llvm::RISCVMatInt::generateInstSeq(), generateInstSeqImpl(), llvm::SCEVExpander::generateOverflowCheck(), GeneratePerfectShuffle(), llvm::generateSpecConstantInst(), generateStackAdjustment(), llvm::orc::GenericNamedTaskImpl< FnT >::GenericNamedTaskImpl(), llvm::AArch64SysReg::genericRegisterString(), genFusedMultiply(), genFusedMultiplyAccNeg(), genFusedMultiplyIdxNeg(), genIndexedMultiply(), genLoopLimit(), genMaddR(), genNeg(), genShuffleBland(), genSubAdd2SubSub(), llvm::SignedDivisionByConstantInfo::get(), llvm::UnsignedDivisionByConstantInfo::get(), llvm::TypedPointerType::get(), llvm::rdf::IndexedSet< const uint32_t * >::get(), llvm::PatchLocation::get(), llvm::MCInstrInfo::get(), llvm::IntegerType::get(), llvm::objcarc::ARCRuntimeEntryPoints::get(), llvm::LayoutAlignElem::get(), llvm::InlineCost::get(), llvm::ConstantInt::get(), llvm::Attribute::get(), llvm::PointerUnion< llvm::LLVMContext *, llvm::ReplaceableMetadataImpl * >::get(), llvm::gsym::LineTable::get(), llvm::VPTransformState::get(), llvm::RecordRecTy::get(), llvm::pdb::HashTable< llvm::support::detail::packed_endian_specific_integral >::get(), llvm::StructType::get(), llvm::ConstantFP::get(), llvm::ImmutableGraphBuilder< GraphT >::get(), llvm::ConstantAggregateZero::get(), llvm::ValueAsMetadata::get(), llvm::ArrayType::get(), llvm::ConstantStruct::get(), llvm::AttributeList::get(), llvm::FixedVectorType::get(), llvm::ScalableVectorType::get(), llvm::PointerType::get(), llvm::ListInit::get(), llvm::ConstantTargetNone::get(), llvm::BlockAddress::get(), llvm::DSOLocalEquivalent::get(), llvm::NoCFIValue::get(), llvm::CondOpInit::get(), llvm::ConstantExpr::get(), llvm::DagInit::get(), llvm::SIRegisterInfo::get32BitRegister(), get64BitArgumentGPRs(), get64BitArgumentXMMs(), llvm::PPCMCCodeEmitter::get_crbitm_encoding(), llvm::PPC::get_VSPLTI_elt(), getAArch64XALUOOp(), llvm::DWARFDie::getAbbreviationDeclarationPtr(), llvm::DWARFYAML::Data::getAbbrevTableContentByIndex(), llvm::MipsTargetStreamer::getABI(), getAbsSetOperand(), llvm::ValueInfo::getAccessSpecifier(), llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::LegalizerInfo::getActionDefinitionsIdx(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::JITSymbol::getAddress(), llvm::DbgDeclareInst::getAddress(), llvm::DbgAddrIntrinsic::getAddress(), llvm::DbgAssignIntrinsic::getAddress(), llvm::jitlink::Symbol::getAddressable(), llvm::TargetTransformInfo::getAddressComputationCost(), llvm::AVR::getAddressSpace(), llvm::dwarf::UnwindLocation::getAddressSpace(), llvm::LLT::getAddressSpace(), llvm::MCCFIInstruction::getAddressSpace(), llvm::SectionEntry::getAddressWithOffset(), llvm::AddrLabelMap::getAddrLabelSymbolToEmit(), getAddrOffset(), llvm::PointerIntPair< llvm::IntrusiveBackListNode *, 1 >::getAddrOfPointer(), llvm::PointerUnion< llvm::LLVMContext *, llvm::ReplaceableMetadataImpl * >::getAddrOfPtr1(), llvm::PointerSumType< ExtraInfoInlineKinds, llvm::PointerSumTypeMember< EIIK_MMO, llvm::MachineMemOperand * >, llvm::PointerSumTypeMember< EIIK_PreInstrSymbol, llvm::MCSymbol * >, llvm::PointerSumTypeMember< EIIK_PostInstrSymbol, llvm::MCSymbol * >, llvm::PointerSumTypeMember< EIIK_OutOfLine, ExtraInfo * > >::getAddrOfZeroTagPointer(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::AMDGPULibFuncBase::getAddrSpaceFromEPtrKind(), getAdjustedPtr(), llvm::ReplayInlineAdvisor::getAdviceImpl(), GetAEABIUnwindPersonalityName(), llvm::CanonicalLoopInfo::getAfter(), llvm::CanonicalLoopInfo::getAfterIP(), llvm::Constant::getAggregateElement(), getAggregateNumElements(), llvm::AMDGPUDisassembler::getAgprClassId(), getAISize(), llvm::opt::Option::getAlias(), llvm::opt::Option::getAliasArgs(), llvm::AliasSummary::getAliasee(), llvm::AliasSummary::getAliaseeGUID(), llvm::AliasSummary::getAliaseeVI(), llvm::rdf::PhysicalRegisterInfo::getAliasSet(), llvm::Attribute::getAlignment(), llvm::RecordKeeper::getAllDerivedDefinitions(), llvm::Value::getAllMetadata(), getAllocatableSetForRC(), llvm::AllocaInst::getAllocationSize(), llvm::Attribute::getAllocKind(), llvm::Attribute::getAllocSizeArgs(), getAllocTypeAttributeString(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::jitlink::Block::getAlreadyMutableContent(), llvm::ARM_AM::getAM2Opc(), llvm::Pass::getAnalysis(), llvm::Pass::getAnalysisID(), llvm::Pass::getAnalysisIfAvailable(), llvm::ScalarEvolution::getAnyExtendExpr(), getAnyNonZeroConstInt(), llvm::AsmToken::getAPIntVal(), llvm::Function::getArg(), llvm::VarDefInit::getArg(), llvm::DagInit::getArg(), llvm::DagInit::getArgName(), llvm::Argument::getArgNo(), llvm::CallBase::getArgOperand(), llvm::CallBase::getArgOperandNo(), llvm::CallBase::getArgOperandUse(), llvm::getArgumentAliasingToReturnedPointer(), llvm::Intrinsic::IITDescriptor::getArgumentKind(), llvm::Intrinsic::IITDescriptor::getArgumentNumber(), llvm::AArch64_AM::getArithExtendImm(), llvm::PPCTTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::TargetTransformInfo::getArithmeticInstrCost(), llvm::RISCVTTIImpl::getArithmeticReductionCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::AArch64TTIImpl::getArithmeticReductionCost(), llvm::TargetTransformInfo::getArithmeticReductionCost(), llvm::AArch64TTIImpl::getArithmeticReductionCostSVE(), getARM64SubType(), getARMIndexedAddressParts(), getARMLoadDeprecationInfo(), getARMStoreDeprecationInfo(), getARMSubType(), llvm::msgpack::DocNode::getArray(), llvm::Type::getArrayElementType(), llvm::BTFDebug::getArrayIndexTypeId(), llvm::ConstantDataSequential::getAsCString(), llvm::ConstantExpr::getAsInstruction(), llvm::StringRef::getAsInteger(), llvm::SelectionDAG::getAssertAlign(), llvm::at::getAssignmentInsts(), llvm::at::getAssignmentMarkers(), llvm::IRPosition::getAssociatedArgument(), llvm::IRPosition::getAssociatedValue(), llvm::ConstantDataSequential::getAsString(), llvm::AMDGPUTargetMachine::getAssumedAddrSpace(), llvm::PotentialValuesState< MemberTy >::getAssumedSet(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::FunctionPointerLikeTypeTraits< 4, ReturnT(*)(ParamTs...)>::getAsVoidPointer(), llvm::coro::Shape::getAsyncCoroId(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getAtomicCmpSwap(), getAtomicLoad128Opcode(), llvm::objcarc::getAttachedARCFunctionKind(), llvm::DWARFAbbreviationDeclaration::getAttrByIndex(), llvm::AttrBuilder::getAttribute(), llvm::ValueEnumerator::getAttributeGroupID(), llvm::dxil::ValueEnumerator::getAttributeGroupID(), llvm::dxil::ValueEnumerator::getAttributeListID(), llvm::ValueEnumerator::getAttributeListID(), llvm::DWARFAbbreviationDeclaration::getAttributeValueFromOffset(), llvm::DWARFAbbreviationDeclaration::getAttrImplicitConstValueByIndex(), llvm::DWARFAbbreviationDeclaration::getAttrIsImplicitConstByIndex(), llvm::object::XCOFFCsectAuxRef::getAuxType64(), getAVX512Node(), llvm::CSKYMCCodeEmitter::getBareSymbolOpValue(), getBaseAddressRegister(), llvm::Intrinsic::getBaseName(), SpecialSubstitution::getBaseName(), llvm::WebAssemblyFunctionInfo::getBasePointerVreg(), llvm::DebugHandlerBase::getBaseTypeSize(), llvm::CFGMST< Edge, BBInfo >::getBBInfo(), llvm::RegionBase< RegionTraits< Function > >::getBBNode(), llvm::LoopVectorizationPlanner::getBestPlanFor(), llvm::ConstantExpr::getBinOpIdentity(), getBinOpsForFactorization(), llvm::BitInit::getBit(), llvm::BitsInit::getBit(), llvm::VarBitInit::getBit(), llvm::ConstantExpr::getBitCast(), llvm::APInt::getBitsNeeded(), llvm::SMTSort::getBitvectorSortSize(), llvm::KnownBits::getBitWidth(), llvm::pdb::Variant::getBitWidth(), llvm::jitlink::Symbol::getBlock(), llvm::CSKYConstantPoolConstant::getBlockAddress(), llvm::MachineOperand::getBlockAddress(), llvm::bfi_detail::getBlockName(), llvm::MachineFunction::getBlockNumbered(), llvm::LoopBase< BasicBlock, Loop >::getBlocks(), llvm::LoopBase< BasicBlock, Loop >::getBlocksSet(), llvm::getBlockStructInstr(), llvm::getBlockStructType(), llvm::LoopBase< BasicBlock, Loop >::getBlocksVector(), llvm::CanonicalLoopInfo::getBody(), llvm::CanonicalLoopInfo::getBodyIP(), llvm::msgpack::DocNode::getBool(), llvm::LoongArchInstrInfo::getBranchDestBlock(), llvm::CSKYInstrInfo::getBranchDestBlock(), llvm::RISCVInstrInfo::getBranchDestBlock(), getBranchHint(), getBranchInsertPoint(), llvm::BranchProbability::getBranchProbability(), llvm::CSKYMCCodeEmitter::getBranchSymbolOpValue(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget21OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValue(), llvm::MipsMCCodeEmitter::getBranchTarget26OpValueMM(), llvm::MipsMCCodeEmitter::getBranchTarget7OpValueMM(), GetBranchTargetEnforcement(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue(), getBranchTargetOpValue(), llvm::MipsMCCodeEmitter::getBranchTargetOpValue1SImm16(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueLsl2MMR6(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMM(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMMPC10(), llvm::MipsMCCodeEmitter::getBranchTargetOpValueMMR6(), getBranchWeight(), GetBranchWeights(), getBRccForPseudo(), llvm::AMDGPURegisterBankInfo::getBreakDownCost(), llvm::VECustomDAG::getBroadcast(), getBROADCAST_LOAD(), getBroadcastOpcode(), llvm::DWARFDebugNames::NameIndex::getBucketArrayEntry(), GetBucketPtr(), getBufferFormatWithCompCount(), llvm::SourceMgr::getBufferInfo(), getBuildDwordsVector(), getBundledDefMI(), getBundledUseMI(), llvm::HexagonInstrInfo::getBundleNoShuf(), llvm::CallBase::getBundleOperandsEndIndex(), llvm::CallBase::getBundleOperandsStartIndex(), llvm::CallBase::getBundleOpInfoForOperand(), llvm::ISD::ArgFlagsTy::getByRefSize(), getBytePosition(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::AnalysisManager< MachineFunction >::getCachedResult(), llvm::LazyBlockFrequencyInfo< llvm::Function, llvm::LazyBranchProbabilityInfoPass, llvm::LoopInfo, llvm::BlockFrequencyInfo >::getCalculated(), llvm::AbstractCallSite::getCallArgOperandNoForCallee(), llvm::IRSimilarity::IRInstructionData::getCalleeName(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::X86RegisterInfo::getCalleeSavedRegsViaCopy(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegsViaCopy(), llvm::PPCFrameLowering::getCalleeSavedSpillSlots(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::AbstractCallSite::getCalleeUseForCallback(), llvm::TargetTransformInfo::getCallInstrCost(), getCallOpcode(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::MCPseudoProbeDecoder::getCallProbeForAddr(), llvm::MachineFunction::getCallSiteBeginLabel(), llvm::MachineFunction::getCallSiteLandingPad(), llvm::CSKYMCCodeEmitter::getCallSymbolOpValue(), llvm::orc::LazyCallThroughManager::getCallThroughTrampoline(), llvm::AMDGPU::getCanonicalArchName(), llvm::sampleprof::FunctionSamples::getCanonicalFnName(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::SwitchInst::CaseHandleImpl< SwitchInst, ConstantInt, BasicBlock >::getCaseSuccessor(), llvm::SwitchInst::CaseHandleImpl< SwitchInst, ConstantInt, BasicBlock >::getCaseValue(), llvm::ConstantExpr::getCast(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::PPCTTIImpl::getCastInstrCost(), llvm::RISCVTTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::AArch64TTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCastInstrCost(), llvm::TargetTransformInfo::getCastInstrCost(), llvm::CastInst::getCastOpcode(), getCastsForInductionPHI(), llvm::TypedInit::getCastTo(), llvm::FunctionLoweringInfo::getCatchPadExceptionPointerVReg(), llvm::BitTracker::MachineEvaluator::getCell(), llvm::MachineOperand::getCFIIndex(), llvm::GCNTTIImpl::getCFInstrCost(), llvm::AArch64TTIImpl::getCFInstrCost(), llvm::TargetTransformInfo::getCFInstrCost(), llvm::objcopy::elf::IHexRecord::getChecksum(), llvm::DeclContextTree::getChildDeclContext(), getChunk(), llvm::MachineOperand::getCImm(), llvm::pdb::NativeTypePointer::getClassParentId(), llvm::ReachingDefAnalysis::getClearance(), llvm::MemDepResult::getClobber(), llvm::MemorySSAWalker::getClobberingMemoryAccess(), llvm::MemorySSA::ClobberWalkerBase::getClobberingMemoryAccessBase(), getCmp(), getCmpForPseudo(), getCmpOpsType(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getCmpSelInstrCost(), llvm::TargetTransformInfo::getCmpSelInstrCost(), llvm::pdb::DIAInjectedSource::getCode(), getCodeExtractorArguments(), llvm::gvn::AvailableValue::getCoercedLoadValue(), llvm::irsymtab::Symbol::getCOFFWeakExternalFallback(), llvm::DebugLoc::getCol(), llvm::PBQP::Matrix::getColAsVector(), llvm::PBQP::Matrix::getCols(), getComdatGVForCOFF(), llvm::ValueEnumerator::getComdatID(), llvm::irsymtab::Symbol::getCommonAlignment(), llvm::MCSymbol::getCommonAlignment(), llvm::RegionInfoBase< RegionTraits< Function > >::getCommonRegion(), llvm::irsymtab::Symbol::getCommonSize(), llvm::MCSymbol::getCommonSize(), llvm::TargetRegisterInfo::getCommonSuperRegClass(), llvm::object::ObjectFile::getCommonSymbolSize(), llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl(), llvm::ConstantExpr::getCompare(), llvm::ScalarEvolution::getComparePredicate(), getComparePreds(), getCompareSourceReg(), getCompoundInsn(), getCompoundOp(), llvm::HexagonInstrInfo::getCompoundOpcode(), getConcreteOpcode(), llvm::CondOpInit::getCond(), llvm::CanonicalLoopInfo::getCond(), GetCondCode(), llvm::TargetLoweringBase::getCondCodeAction(), llvm::BranchInst::getCondition(), llvm::SDDbgOperand::getConst(), llvm::KnownBits::getConstant(), llvm::ValueLatticeElement::getConstant(), llvm::SelectionDAG::getConstant(), llvm::DIDerivedType::getConstant(), llvm::getConstantDataArrayInfo(), llvm::SelectionDAG::getConstantDbgValue(), llvm::SelectionDAG::getConstantFP(), llvm::PPCInstrInfo::getConstantFromConstantPool(), llvm::StackMapParser< Endianness >::LocationAccessor::getConstantIndex(), llvm::ScalarEvolution::getConstantMaxTripCountFromArray(), llvm::SelectionDAG::getConstantPool(), getConstantRange(), llvm::LazyValueInfo::getConstantRange(), llvm::ValueLatticeElement::getConstantRange(), llvm::getConstantRangeFromMetadata(), llvm::LazyValueInfo::getConstantRangeOnEdge(), llvm::BuildVectorSDNode::getConstantRawBits(), llvm::ExecutionEngine::getConstantValue(), getConstantVector(), llvm::getConstFromIntrinsic(), getConstMetaVal(), llvm::CSKYMCCodeEmitter::getConstpoolSymbolOpValue(), llvm::ConstantPoolSDNode::getConstVal(), getConstVector(), llvm::legacy::FunctionPassManagerImpl::getContainedManager(), llvm::legacy::PassManagerImpl::getContainedManager(), llvm::LPPassManager::getContainedPass(), llvm::RGPassManager::getContainedPass(), llvm::FPPassManager::getContainedPass(), llvm::Type::getContainedType(), getContainerForFixedLengthVector(), llvm::IntervalTree< LVAddress, LVScope * >::getContaining(), llvm::RuntimeDyldChecker::MemoryRegionInfo::getContent(), llvm::jitlink::Block::getContent(), llvm::SampleContextTracker::getContextSamplesFor(), llvm::getContributionIndex(), getCopyFromParts(), getCopyFromPartsVector(), llvm::RegsForValue::getCopyFromRegs(), llvm::WebAssembly::getCopyOpcodeForRegClass(), getCopyToParts(), getCopyToPartsVector(), llvm::CoroSuspendInst::getCoroSave(), getCorrespondingDRegAndLane(), llvm::InlineCost::getCost(), llvm::DISubrange::getCount(), llvm::DIGenericSubrange::getCount(), llvm::DebugCounter::getCounterValue(), llvm::object::XCOFFSymbolRef::getCPUTypeIddForCFile(), getCRBitValue(), llvm::getCRFromCRBit(), llvm::MCSectionXCOFF::getCSectType(), llvm::RegOrConstant::getCst(), llvm::DWARFDebugNames::NameIndex::getCUOffset(), llvm::TGLexer::getCurBinaryIntVal(), llvm::TGLexer::getCurIntVal(), llvm::MCObjectStreamer::getCurrentFragment(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::GCNSchedStrategy::getCurrentStage(), llvm::mca::RetireControlUnit::getCurrentToken(), llvm::TGLexer::getCurStrVal(), llvm::GenericCycle< ContextT >::getCyclePreheader(), llvm::GCOVBlock::getCyclesCount(), llvm::AArch64RegisterInfo::getDarwinCalleeSavedRegs(), llvm::AArch64RegisterInfo::getDarwinCallPreservedMask(), llvm::object::COFFObjectFile::getDataDirectory(), llvm::CallBase::getDataOperandNo(), llvm::CSKYMCCodeEmitter::getDataSymbolOpValue(), getDbgIntrinsicValueImpl(), llvm::SelectionDAG::getDbgLabel(), LiveDebugValues::DbgValue::getDbgOpID(), llvm::SelectionDAG::getDbgValue(), llvm::SelectionDAG::getDbgValueList(), llvm::MachineInstr::getDebugExpressionOp(), llvm::DWARFUnit::getDebugInfoEntry(), llvm::MachineInstr::getDebugLabel(), getDebugLocValue(), llvm::MachineInstr::getDebugOffset(), llvm::MachineInstr::getDebugOperand(), llvm::MachineInstr::getDebugOperandIndex(), llvm::DIE::getDebugSectionOffset(), llvm::MachineInstr::getDebugVariableOp(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::VPIntrinsic::getDeclarationForParams(), getDecoderTable(), llvm::MemDepResult::getDef(), llvm::orc::JITDylib::getDefaultResourceTracker(), getDefaultScalableVLOps(), getDefaultVLOps(), llvm::PPCInstrInfo::getDefMIPostRA(), getDefRegMask(), getDemandedSrcElements(), GetDeoptBundleOperands(), getDeoptLowering(), llvm::DependenceGraphInfo< NodeType >::getDependencies(), llvm::SelectionDAG::GetDependentSplitDestVTs(), llvm::Argument::getDereferenceableBytes(), llvm::Attribute::getDereferenceableBytes(), llvm::Argument::getDereferenceableOrNullBytes(), llvm::Attribute::getDereferenceableOrNullBytes(), llvm::AMDGPU::MTBUFFormat::getDfmtName(), llvm::mca::MCAOperand::getDFPImm(), llvm::MCOperand::getDFPImm(), llvm::DWARFUnit::getDIEIndex(), llvm::FullDependence::getDirection(), llvm::DIDerivedType::getDiscriminantValue(), llvm::sampleprof::SampleProfileReader::getDiscriminatorMask(), llvm::PPCMCCodeEmitter::getDispRI34PCRelEncoding(), llvm::PPCMCCodeEmitter::getDispRIHashEncoding(), llvm::PPCMCCodeEmitter::getDispRIX16Encoding(), llvm::PPCMCCodeEmitter::getDispSPE2Encoding(), llvm::PPCMCCodeEmitter::getDispSPE4Encoding(), llvm::PPCMCCodeEmitter::getDispSPE8Encoding(), llvm::FullDependence::getDistance(), getDivRemArgList(), getDivRemLibcall(), llvm::LoopVectorizationCostModel::getDivRemSpeculationCost(), llvm::RuntimeDyldCOFF::getDLLImportOffset(), getDomPredecessorCondition(), llvm::DomTreeUpdater::getDomTree(), llvm::HexagonInstrInfo::getDotNewPredJumpOp(), llvm::HexagonInstrInfo::getDotOldOp(), llvm::VectorType::getDoubleElementsVectorType(), llvm::MemOp::getDstAlign(), GetDSubRegs(), llvm::SCCPInstVisitor::getDTU(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), getDwarfRegNum(), llvm::DwarfDebug::getDwarfSectionOffsetForm(), llvm::DWARFUnit::getDwarfStringOffsetsByteSize(), llvm::getDWARFUnitIndex(), getDynAllocaAmount(), llvm::HexagonTargetLowering::GetDynamicTLSAddr(), getEarliestInsertPos(), getEdgeKind(), llvm::BranchProbabilityInfo::getEdgeProbability(), getEdgeValueLocal(), getEffectivePPCCodeModel(), getEffectiveRelocModel(), llvm::ScalarEvolution::getEffectiveSCEVType(), getEHPadFromPredecessor(), GetEHSpillList(), llvm::XCoreFunctionInfo::getEHSpillSlot(), llvm::mca::RegisterFile::getElapsedCyclesFromWriteBack(), llvm::ListInit::getElement(), llvm::DIExpression::getElement(), llvm::ConstantDataSequential::getElementAsAPInt(), llvm::ConstantDataSequential::getElementAsDouble(), llvm::ConstantDataSequential::getElementAsFloat(), llvm::ConstantDataSequential::getElementAsInteger(), llvm::ListInit::getElementAsRecord(), llvm::StructLayout::getElementContainingOffset(), llvm::LLT::getElementCount(), getElementIndex(), llvm::StructLayout::getElementOffset(), llvm::LLT::getElementType(), llvm::StructType::getElementType(), llvm::InductionDescriptor::getElementType(), llvm::RISCVSubtarget::getELEN(), llvm::AVRSubtarget::getELFArch(), llvm::MCContext::getELFSection(), getEmscriptenInvokeSymbolName(), llvm::VPBlockBase::getEnclosingBlockWithPredecessors(), llvm::VPBlockBase::getEnclosingBlockWithSuccessors(), llvm::VPBasicBlock::getEnclosingLoopRegion(), getEncodedIntegerLength(), llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getEncodingData(), llvm::MCRegisterInfo::getEncodingValue(), llvm::OptimizedStructLayoutField::getEndOffset(), llvm::MachineTraceMetrics::getEnsemble(), llvm::RegionBase< RegionTraits< Function > >::getEnteringBlock(), llvm::jitlink::TableManager< PLTTableManager >::getEntryForTarget(), llvm::BlockFrequencyInfoImplBase::getEntryFreq(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::GetEntryNode(), getEntrySizeForKind(), llvm::PPCSubtarget::getEnvironmentPointerRegister(), llvm::AMDGPULibFuncBase::getEPtrKindFromAddrSpace(), llvm::SIRegisterInfo::getEquivalentAGPRClass(), llvm::ConstantRange::getEquivalentICmp(), llvm::AMDGPUTargetLowering::getEquivalentMemType(), llvm::SCEVSequentialMinMaxExpr::getEquivalentNonSequentialSCEVType(), llvm::ConstantRange::getEquivalentPredWithFlippedSignedness(), llvm::SIRegisterInfo::getEquivalentSGPRClass(), llvm::SIRegisterInfo::getEquivalentVGPRClass(), llvm::detail::IEEEFloat::getExactInverse(), llvm::detail::DoubleAPFloat::getExactInverse(), llvm::object::XCOFFObjectFile::getExceptionEntries(), llvm::orc::ExecutorProcessControl::getExecutionSession(), llvm::CanonicalLoopInfo::getExit(), llvm::getExitBlockHelper(), llvm::LoopBase< BasicBlock, Loop >::getExitBlocks(), llvm::LoopBase< BasicBlock, Loop >::getExitEdges(), llvm::LoopBase< BasicBlock, Loop >::getExitingBlock(), llvm::RegionBase< RegionTraits< Function > >::getExitingBlock(), llvm::LoopBase< BasicBlock, Loop >::getExitingBlocks(), getExpectedExitLoopLatchBranch(), llvm::AMDGPUSubtarget::getExplicitKernArgSize(), llvm::MCOperand::getExpr(), llvm::HexagonMCInstrInfo::getExpr(), llvm::RISCVMCAsmInfo::getExprForFDESymbol(), llvm::getExtDivCycle(), getEXTEND_VECTOR_INREG(), llvm::HexagonMCInstrInfo::getExtendableOperand(), llvm::VectorType::getExtendedElementVectorType(), llvm::object::getExtendedSymbolTableIndex(), llvm::Type::getExtendedType(), llvm::AArch64_AM::getExtendType(), getExtendTypeForNode(), getExtensionTo64Bits(), llvm::ConstantExpr::getExtractElement(), getExtractIndex(), llvm::TargetInstrInfo::getExtractSubregInputs(), llvm::ARMBaseInstrInfo::getExtractSubregLikeInputs(), llvm::AArch64TTIImpl::getExtractWithExtendCost(), llvm::TargetTransformInfo::getExtractWithExtendCost(), llvm::MCSchedModel::getExtraProcessorInfo(), llvm::APSInt::getExtValue(), llvm::AtomicSDNode::getFailureOrdering(), llvm::InlineResult::getFailureReason(), llvm::ConstantInt::getFalse(), llvm::Instruction::getFastMathFlags(), llvm::FaultMapParser::getFaultMapVersion(), getFauxShuffleMask(), llvm::ConstantExpr::getFCmp(), llvm::getFCmpCode(), getFD(), llvm::X86::getFeaturePriority(), getFeatures(), llvm::NearMissInfo::getFeatures(), llvm::X86::getFeaturesForCPU(), llvm::NewArchiveMember::getFile(), llvm::DWARFDebugLine::Prologue::getFileNameEntry(), llvm::pdb::InputFile::getFilePath(), llvm::jitlink::SectionRange::getFirstBlock(), llvm::DWARFUnit::getFirstChildEntry(), llvm::StatepointOpers::getFirstGCPtrIdx(), llvm::slpvectorizer::BoUpSLP::getFirstNodeMainOp(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::SystemZMC::getFirstReg(), llvm::InstructionPrecedenceTracking::getFirstSpecialInstruction(), llvm::IndexedReference::getFirstSubscript(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::getFixedValue(), llvm::CSKYAsmBackend::getFixupKindInfo(), llvm::ARMAsmBackend::getFixupKindInfo(), llvm::XtensaMCAsmBackend::getFixupKindInfo(), llvm::AVRAsmBackend::getFixupKindInfo(), llvm::MipsAsmBackend::getFixupKindInfo(), llvm::LoongArchAsmBackend::getFixupKindInfo(), llvm::RISCVAsmBackend::getFixupKindInfo(), llvm::MCAsmBackend::getFixupKindInfo(), llvm::R600InstrInfo::getFlagOp(), llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getFlagWordForMatchingOp(), llvm::InlineAsm::getFlagWordForMem(), llvm::InlineAsm::getFlagWordForRegClass(), llvm::CmpInst::getFlippedSignednessPredicate(), llvm::CmpInst::getFlippedStrictnessPredicate(), llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(), llvm::msgpack::DocNode::getFloat(), llvm::getFloatFn(), llvm::Type::getFloatingPointTy(), llvm::SMTSort::getFloatSortSize(), llvm::getFltSemanticForLLT(), llvm::getFMA3Group(), llvm::X86InstrInfo::getFMA3OpcodeToCommuteOperands(), llvm::PPCInstrInfo::getFMAPatterns(), getFMAPatterns(), getFoldedCast(), llvm::MemoryLocation::getForArgument(), llvm::MemoryLocation::getForDest(), llvm::DWARFDebugNames::NameIndex::getForeignTUSignature(), llvm::SourceMgr::getFormattedLocationNoOffset(), llvm::DWARFAbbreviationDeclaration::getFormByIndex(), llvm::MemoryLocation::getForSource(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), getFPBinOp(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), llvm::MachineOperand::getFPImm(), llvm::Type::getFPMantissaWidth(), llvm::TargetTransformInfo::getFPOpCost(), getFPReg(), getFPSequenceIfElementsMatch(), llvm::XCoreFunctionInfo::getFPSpillSlot(), getFPTernOp(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getFPTrunc(), llvm::MCAsmLayout::getFragmentOffset(), llvm::DIInliningInfo::getFrame(), llvm::X86InstrInfo::getFrameAdjustment(), llvm::WebAssemblyFunctionInfo::getFrameBaseLocal(), llvm::WebAssemblyFunctionInfo::getFrameBaseVreg(), llvm::SelectionDAG::getFrameIndexDbgValue(), llvm::DbgVariable::getFrameIndexExprs(), llvm::RISCVRegisterInfo::getFrameIndexInstrOffset(), llvm::SIRegisterInfo::getFrameIndexInstrOffset(), getFrameIndexOperandNum(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::CSKYFrameLowering::getFrameIndexReference(), llvm::HexagonFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::M68kFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReferencePreferSP(), llvm::SDDbgOperand::getFrameIx(), llvm::MSP430InstrInfo::getFramePoppedByCallee(), llvm::ARMBaseInstrInfo::getFramePred(), llvm::TargetInstrInfo::getFrameSize(), llvm::TargetInstrInfo::getFrameTotalSize(), llvm::getFSPassBitBegin(), llvm::getFSPassBitEnd(), llvm::X86AddressMode::getFullAddress(), llvm::object::Archive::Child::getFullName(), llvm::MCPseudoProbeDecoder::getFuncDescForGUID(), llvm::sampleprof::FunctionSamples::getFuncName(), llvm::SPIRV::ModuleAnalysisInfo::getFuncReg(), llvm::LazyCallGraph::Edge::getFunction(), llvm::CanonicalLoopInfo::getFunction(), llvm::TargetLoweringObjectFileXCOFF::getFunctionEntryPointSymbol(), llvm::FaultMapParser::FunctionInfoAccessor::getFunctionFaultInfoAt(), llvm::gsym::GsymReader::getFunctionInfo(), llvm::GCModuleInfo::getFunctionInfo(), llvm::getFunctionLiveInPhysReg(), llvm::NVPTXTargetLowering::getFunctionParamOptimizedAlign(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getGatherScatterOpCost(), llvm::TargetTransformInfo::getGatherScatterOpCost(), llvm::SelectionDAG::getGatherVP(), llvm::Function::getGC(), llvm::MCOperandInfo::getGenericImmIndex(), llvm::MCOperandInfo::getGenericTypeIndex(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getGEPCost(), llvm::ScalarEvolution::getGEPExpr(), llvm::DataLayout::getGEPIndicesForOffset(), llvm::ConstantExpr::getGetElementPtr(), llvm::MachineOperand::getGlobal(), llvm::SelectionDAG::getGlobalAddress(), llvm::AArch64MCInstLower::GetGlobalAddressSymbol(), llvm::X86InstrInfo::getGlobalBaseReg(), llvm::MCSymbolWasm::getGlobalType(), llvm::ModuleSummaryIndex::getGlobalValueSummary(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::getGOTEntry(), llvm::DOTGraphTraits< const DataDependenceGraph * >::getGraphName(), llvm::opt::Option::getGroup(), llvm::mca::LSUnitBase::getGroup(), llvm::CSKYConstantPoolConstant::getGV(), llvm::AsmPrinter::getGVAlignment(), llvm::IRSimilarity::IRSimilarityCandidate::getGVN(), getGVNForPHINode(), llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MachineModuleInfoELF::getGVStubEntry(), llvm::MachineModuleInfoCOFF::getGVStubEntry(), llvm::VectorType::getHalfElementsVectorType(), llvm::EVT::getHalfNumVectorElementsVT(), llvm::MVT::getHalfNumVectorElementsVT(), getHalfShuffleMask(), llvm::EVT::getHalfSizedIntegerVT(), getHalfSizedType(), llvm::DWARFDebugNames::NameIndex::getHashArrayEntry(), llvm::DenseMapInfo< CachedHashStringRef >::getHashValue(), llvm::DenseMapInfo< MemOpKey >::getHashValue(), llvm::DenseMapInfo< CachedHashString >::getHashValue(), llvm::IRSimilarity::IRInstructionDataTraits::getHashValue(), llvm::DenseMapInfo< ArrayRef< T >, void >::getHashValue(), getHashValueImpl(), llvm::ARMHazardRecognizerFPMLx::getHazardType(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::ImmutableList< T >::getHead(), llvm::gsym::GsymReader::getHeader(), llvm::CanonicalLoopInfo::getHeader(), llvm::object::MachOObjectFile::getHeader64(), llvm::BlockFrequencyInfoImplBase::LoopData::getHeaderIndex(), llvm::opt::Option::getHelpText(), getHexagonRegisterPair(), llvm::HexagonRegisterInfo::getHexagonSubRegIndex(), getHexDigit(), getHexUint(), llvm::object::import_lookup_table_entry< IntTy >::getHintNameRVA(), llvm::COFF::ImportLookupTableEntry32::getHintNameRVA(), llvm::ConstantExpr::getICmp(), llvm::getIConstantVRegVal(), llvm::getIConstVal(), llvm::IdentifyingPassPtr::getID(), llvm::opt::Option::getID(), llvm::MemoryAccess::getID(), llvm::codeview::DebugStringTableSubsection::getIdForString(), llvm::GetIfCondition(), llvm::ValueAsMetadata::getIfExists(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbol(), llvm::mca::MCAOperand::getImm(), llvm::MCOperand::getImm(), llvm::X86Operand::getImm(), XtensaOperand::getImm(), llvm::MachineOperand::getImm(), llvm::PPCMCCodeEmitter::getImm34Encoding(), llvm::CSKYMCCodeEmitter::getImmJMPIX(), llvm::CSKYMCCodeEmitter::getImmOpValue(), llvm::CSKYMCCodeEmitter::getImmOpValueIDLY(), llvm::CSKYMCCodeEmitter::getImmOpValueMSBSize(), llvm::CSKYMCCodeEmitter::getImmShiftOpValue(), llvm::ConstantDataSequential::getImpl(), getImpl(), llvm::AMDGPUSubtarget::getImplicitArgNumBytes(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::getImplicitConstValue(), llvm::PointerAlignElem::getInBits(), llvm::Loop::getIncomingAndBackEdge(), llvm::MemoryPhi::getIncomingBlock(), llvm::PHINode::getIncomingBlock(), llvm::MemoryPhi::getIncomingValueForBlock(), llvm::PHINode::getIncomingValueForBlock(), llvm::CoroSubFnInst::getIndex(), llvm::DwarfStringPoolEntryRef::getIndex(), llvm::ModifiedPostOrder< ContextT >::getIndex(), llvm::MachineOperand::getIndex(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedLoadVP(), llvm::SelectionDAG::getIndexedMaskedLoad(), llvm::SelectionDAG::getIndexedMaskedStore(), llvm::DataLayout::getIndexedOffsetInType(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getIndexedStoreVP(), llvm::SelectionDAG::getIndexedStridedLoadVP(), llvm::SelectionDAG::getIndexedStridedStoreVP(), llvm::getIndexExpressionsFromGEP(), llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::AMDGPU::VOPD::ComponentInfo::getIndexInParsedOperands(), llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfSrcInMCOperands(), llvm::AMDGPU::VOPD::ComponentLayout::getIndexOfSrcInParsedOperands(), llvm::coro::Shape::getIndexType(), llvm::DataLayout::getIndexType(), llvm::DataLayout::getIndexTypeSizeInBits(), llvm::CallBrInst::getIndirectDestLabel(), llvm::CallBrInst::getIndirectDestLabelUse(), llvm::SIInstrInfo::getIndirectRegWriteMovRelPseudo(), llvm::orc::getIndirectStubsBlockSizes(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), getIndirectThunkSymbol(), llvm::Loop::getInductionVariable(), llvm::CanonicalLoopInfo::getIndVar(), llvm::CanonicalLoopInfo::getIndVarType(), llvm::CoroIdInst::getInfo(), llvm::GlobalVariable::getInitializer(), llvm::MachineInstr::getInlineAsmDialect(), llvm::DebugLoc::getInlinedAt(), llvm::DWARFUnit::getInlinedChainForAddress(), llvm::pdb::PDBContext::getInliningInfoForAddress(), getInnerMostLoop(), getInputSegmentList(), llvm::CCState::getInRegsParamInfo(), INITIALIZE_PASS::InsertedPass::getInsertedPass(), llvm::ConstantExpr::getInsertElement(), llvm::Instruction::getInsertionPointAfterDef(), llvm::RegBankSelect::InsertPoint::getInsertMBB(), getInsertPointForUses(), llvm::TargetInstrInfo::getInsertSubregInputs(), llvm::ARMBaseInstrInfo::getInsertSubregLikeInputs(), llvm::MCOperand::getInst(), llvm::IdentifyingPassPtr::getInstance(), llvm::SIInstrInfo::getInstBundleSize(), llvm::SUnit::getInstr(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::MipsRegisterBankInfo::getInstrMapping(), llvm::PPCRegisterBankInfo::getInstrMapping(), llvm::X86RegisterBankInfo::getInstrMapping(), llvm::AArch64RegisterBankInfo::getInstrMapping(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::RegisterBankInfo::getInstrMappingImpl(), getInstrName(), llvm::RegisterBankInfo::getInstrPossibleMappings(), llvm::MachineOperand::getInstrRefInstrIndex(), llvm::MachineOperand::getInstrRefOpIndex(), llvm::MachineTraceMetrics::Trace::getInstrSlack(), getInstrStrFromOpNo(), llvm::AArch64Disassembler::getInstruction(), llvm::AMDGPUDisassembler::getInstruction(), llvm::TargetTransformInfo::getInstructionCost(), llvm::TargetTransformInfoImplCRTPBase< AMDGPUTTIImpl >::getInstructionCost(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), llvm::SimpleDDGNode::getInstructions(), llvm::AArch64InstrInfo::getInstSizeInBytes(), getInstSizeInBytes(), llvm::msgpack::DocNode::getInt(), llvm::getIntDivCycle(), llvm::VectorType::getInteger(), llvm::ConstantExpr::getIntegerCast(), llvm::SystemZTTIImpl::getInterleavedMemoryOpCost(), llvm::PPCTTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::AArch64TTIImpl::getInterleavedMemoryOpCost(), llvm::TargetTransformInfo::getInterleavedMemoryOpCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::LiveStacks::getInterval(), llvm::LiveStacks::getIntervalRegClass(), llvm::TargetTransformInfo::getIntImmCodeSizeCost(), llvm::SystemZTTIImpl::getIntImmCost(), llvm::LanaiTTIImpl::getIntImmCost(), llvm::PPCTTIImpl::getIntImmCost(), llvm::RISCVTTIImpl::getIntImmCost(), llvm::AArch64TTIImpl::getIntImmCost(), llvm::ARMTTIImpl::getIntImmCost(), llvm::X86TTIImpl::getIntImmCost(), llvm::TargetTransformInfo::getIntImmCost(), llvm::SystemZTTIImpl::getIntImmCostInst(), llvm::PPCTTIImpl::getIntImmCostInst(), llvm::RISCVTTIImpl::getIntImmCostInst(), llvm::AArch64TTIImpl::getIntImmCostInst(), llvm::X86TTIImpl::getIntImmCostInst(), llvm::TargetTransformInfo::getIntImmCostInst(), llvm::SystemZTTIImpl::getIntImmCostIntrin(), llvm::PPCTTIImpl::getIntImmCostIntrin(), llvm::AArch64TTIImpl::getIntImmCostIntrin(), llvm::X86TTIImpl::getIntImmCostIntrin(), llvm::TargetTransformInfo::getIntImmCostIntrin(), getIntOperandFromRegisterString(), getIntOperandsFromRegisterString(), llvm::DataLayout::getIntPtrType(), llvm::MachineOperand::getIntrinsicID(), llvm::TargetTransformInfo::getIntrinsicInstrCost(), getIntrinsicNameImpl(), getIntSequenceIfElementsMatch(), llvm::ConstantExpr::getIntToPtr(), llvm::AsmToken::getIntVal(), getInvariantGroupClobberingInstruction(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), llvm::SyncDependenceAnalysis::getJoinBlocks(), llvm::GenericSyncDependenceAnalysis< ContextT >::getJoinBlocks(), llvm::MachineFunction::getJTISymbol(), llvm::MipsMCCodeEmitter::getJumpOffset16OpValue(), llvm::SelectionDAG::getJumpTable(), llvm::SwitchCG::getJumpTableNumCases(), llvm::SwitchCG::getJumpTableRange(), llvm::MipsMCCodeEmitter::getJumpTargetOpValue(), llvm::MipsMCCodeEmitter::getJumpTargetOpValueMM(), getJumpThreadDuplicationCost(), getKernelArgAttribute(), llvm::X86::getKeyFeature(), llvm::opt::Option::getKind(), llvm::LazyCallGraph::Edge::getKind(), llvm::AttributeImpl::getKindAsEnum(), llvm::Attribute::getKindAsEnum(), llvm::AttributeImpl::getKindAsString(), llvm::Attribute::getKindAsString(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MCFixup::getKindForSizeInBits(), llvm::GISelKnownBits::getKnownBits(), llvm::VPLane::getKnownLane(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::getKnownScalarFactor(), getKnownUndefForVectorBinop(), llvm::DebugHandlerBase::getLabelBeforeInsn(), llvm::DwarfCompileUnit::getLabelBegin(), llvm::object::XCOFFSymbolRef::getLanguageIdForCFile(), llvm::jitlink::SectionRange::getLastBlock(), llvm::DWARFUnit::getLastChildEntry(), llvm::ConstraintSystem::getLastConstraint(), llvm::IndexedReference::getLastSubscript(), llvm::RegPressureTracker::getLastUsedLanes(), llvm::DWARFDebugLine::Prologue::getLastValidFileIndex(), llvm::CanonicalLoopInfo::getLatch(), llvm::LatencyPriorityQueue::getLatency(), llvm::ResourcePriorityQueue::getLatency(), getLatestInsertPos(), llvm::SCCPInstVisitor::getLatticeValueFor(), llvm::orc::EPCIndirectionUtils::getLazyCallThroughManager(), getLdStRegOp(), llvm::EquivalenceClasses< llvm::Instruction * >::getLeaderValue(), getLeftShift(), llvm::VECustomDAG::getLegalReductionOpVVP(), llvm::pdb::NativeTypePointer::getLength(), llvm::PBQP::Vector::getLength(), llvm::ScaledNumbers::getLgImpl(), llvm::getLibcallSignature(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::DebugLoc::getLine(), llvm::objcopy::elf::IHexRecord::getLine(), llvm::SourceMgr::getLineAndColumn(), llvm::pdb::PDBContext::getLineInfoForAddress(), llvm::cflaa::StratifiedSets< T >::getLink(), llvm::BinOpInit::getListConcat(), llvm::BitCodeAbbrevOp::getLiteralValue(), llvm::VPValue::getLiveInIRValue(), llvm::getLiveLaneMask(), llvm::RegPressureTracker::getLiveLanesAt(), llvm::StackLifetime::getLiveRange(), llvm::RegPressureTracker::getLiveThroughAt(), llvm::getLLTForType(), llvm::mca::RISCVLMULInstrument::getLMUL(), llvm::RISCVTargetLowering::getLMUL(), getLMUL1VT(), llvm::SelectionDAG::getLoad(), llvm::SectionEntry::getLoadAddressWithOffset(), llvm::object::COFFObjectFile::getLoadConfig32(), llvm::object::COFFObjectFile::getLoadConfig64(), llvm::TargetLoweringBase::getLoadExtAction(), llvm::getLoadStoreAddressSpace(), llvm::getLoadStoreAlignment(), getLoadStoreRegOpcode(), llvm::getLoadStoreType(), llvm::VNCoercion::getLoadValueForLoad(), llvm::SelectionDAG::getLoadVP(), llvm::MachineFrameInfo::getLocalFrameObjectMap(), getLocalFunctionMetadata(), llvm::SlotTracker::getLocalSlot(), llvm::DWARFDebugNames::NameIndex::getLocalTUOffset(), LiveDebugValues::MLocTracker::getLocID(), llvm::orc::ThreadSafeContext::getLock(), llvm::LoopNest::getLoop(), llvm::LoopBase< BasicBlock, Loop >::getLoopDepth(), llvm::Loop::getLoopGuardBranch(), llvm::SCCPInstVisitor::getLoopInfo(), llvm::ScalarEvolution::getLoopInvariantPredicate(), llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), llvm::LoopBase< BasicBlock, Loop >::getLoopLatches(), llvm::LoopBase< BasicBlock, Loop >::getLoopPredecessor(), llvm::LoopBase< BasicBlock, Loop >::getLoopPreheader(), llvm::LoopNest::getLoopsAtDepth(), llvm::LoopInfoBase< BasicBlock, Loop >::getLoopsInReverseSiblingPreorder(), llvm::ScalarEvolution::getLosslessPtrToIntExpr(), llvm::DISubrange::getLowerBound(), llvm::DIGenericSubrange::getLowerBound(), llvm::XCoreFunctionInfo::getLRSpillSlot(), llvm::jitlink::EHFrameCFIBlockInspector::getLSDAEdge(), llvm::LexicalScopes::getMachineBasicBlocks(), llvm::ConstantPoolSDNode::getMachineCPVal(), llvm::VirtRegMap::getMachineFunction(), llvm::getMachineInstrType(), llvm::SDNode::getMachineOpcode(), llvm::HexagonMCCodeEmitter::getMachineOpValue(), llvm::PPCMCCodeEmitter::getMachineOpValue(), llvm::MipsMCCodeEmitter::getMachineOpValue(), getMachoBuildVersionPlatformType(), getMachoBuildVersionSupportedOS(), llvm::MCContext::getMachOSection(), getMachoVersionMinLoadCommandType(), getMaddPatterns(), llvm::SourceMgr::getMainFileID(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::getManager(), llvm::AMDGPU::VOPD::ComponentProps::getMandatoryLiteralCompOperandIndex(), llvm::ExecutionEngine::getMangledName(), llvm::msgpack::DocNode::getMap(), llvm::MCSectionXCOFF::getMappingClass(), llvm::VPBranchOnMaskRecipe::getMask(), llvm::VECustomDAG::getMaskBroadcast(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::TargetTransformInfo::getMaskedMemoryOpCost(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), getMaskedTypeForICmpPair(), llvm::ShuffleVectorSDNode::getMaskElt(), getMaskNode(), getMaskTypeFor(), llvm::TargetLowering::AsmOperandInfo::getMatchedOperand(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), llvm::RegPressureTracker::getMaxDownwardPressureDelta(), llvm::M68kRegisterInfo::getMaximalPhysRegClass(), llvm::IndexedInstrProfReader::getMaximumFunctionCount(), llvm::MachineRegisterInfo::getMaxLaneMaskForVReg(), llvm::RISCVSubtarget::getMaxLMULForFixedLengthVectors(), llvm::AMDGPU::IsaInfo::getMaxNumSGPRs(), llvm::AMDGPU::IsaInfo::getMaxNumVGPRs(), llvm::GEPOperator::getMaxPreservedAlignment(), llvm::RegPressureTracker::getMaxPressureDelta(), llvm::RISCVSubtarget::getMaxRVVVectorSizeInBits(), llvm::AArch64Subtarget::getMaxSVEVectorSizeInBits(), llvm::RegPressureTracker::getMaxUpwardPressureDelta(), llvm::HexagonMCInstrInfo::getMaxValue(), llvm::AMDGPU::IsaInfo::getMaxWorkGroupsPerCU(), llvm::MachineIRBuilder::getMBB(), llvm::MachineOperand::getMBB(), llvm::SlotIndexes::getMBBFromIndex(), llvm::MCContext::getMCDwarfLineTable(), llvm::MachineOperand::getMCSymbol(), llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction(), getMCSymbolForMBB(), llvm::DwarfDebug::getMD5AsBytes(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::X86Operand::getMemBaseReg(), llvm::SelectionDAG::getMemcpy(), llvm::TargetTransformInfo::getMemcpyCost(), getMemcpyLoadsAndStores(), llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType(), llvm::X86Operand::getMemDefaultBaseReg(), llvm::X86Operand::getMemDisp(), llvm::MipsMCCodeEmitter::getMemEncoding(), llvm::MipsMCCodeEmitter::getMemEncodingMMGPImm7Lsl2(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm11(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm12(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm16(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4Lsl1(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4Lsl2(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm4sp(), llvm::MipsMCCodeEmitter::getMemEncodingMMImm9(), llvm::MipsMCCodeEmitter::getMemEncodingMMSPImm5Lsl2(), llvm::X86Operand::getMemFrontendSize(), llvm::X86Operand::getMemIndexReg(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::gvn::AvailableValue::getMemIntrinValue(), llvm::orc::ExecutorProcessControl::getMemMgr(), llvm::X86Operand::getMemModeSize(), getMemmoveLoadsAndStores(), llvm::AArch64InstrInfo::getMemOpBaseRegImmOfsOffsetOperand(), llvm::SIInstrInfo::getMemOperandsWithOffsetWidth(), llvm::AArch64InstrInfo::getMemOperandWithOffsetWidth(), getMemOpKey(), llvm::orc::ExecutorProcessControl::getMemoryAccess(), llvm::SourceMgr::getMemoryBuffer(), llvm::InlineAsm::getMemoryConstraintID(), llvm::Attribute::getMemoryEffects(), llvm::SystemZTTIImpl::getMemoryOpCost(), llvm::HexagonTTIImpl::getMemoryOpCost(), llvm::PPCTTIImpl::getMemoryOpCost(), llvm::X86TTIImpl::getMemoryOpCost(), llvm::TargetTransformInfo::getMemoryOpCost(), llvm::X86_MC::X86MCInstrAnalysis::getMemoryOperandRelocationOffset(), llvm::X86Operand::getMemScale(), llvm::X86Operand::getMemSegReg(), llvm::SelectionDAG::getMemset(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), llvm::RISCVII::getMergeOpNum(), llvm::SourceMgr::GetMessage(), llvm::Value::getMetadata(), llvm::MachineOperand::getMetadata(), llvm::ValueEnumerator::getMetadataID(), llvm::dxil::ValueEnumerator::getMetadataID(), llvm::opt::Option::getMetaVar(), llvm::MachineIRBuilder::getMF(), llvm::memprof::getMIBAllocType(), llvm::memprof::getMIBStackNode(), llvm::ValueDFS_Compare::getMiddleDef(), getMinAnalyzeableBackedgeTakenCount(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::RegisterBankInfo::getMinimalPhysRegClass(), llvm::TargetRegisterInfo::getMinimalPhysRegClassLLT(), llvm::HexagonTTIImpl::getMinimumVF(), llvm::X86TTIImpl::getMinMaxCost(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::AArch64TTIImpl::getMinMaxReductionCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::TargetTransformInfo::getMinMaxReductionCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getMinMaxReductionCost(), llvm::AMDGPU::IsaInfo::getMinNumSGPRs(), llvm::AMDGPU::IsaInfo::getMinNumVGPRs(), llvm::RISCVSubtarget::getMinRVVVectorSizeInBits(), llvm::AArch64Subtarget::getMinSVEVectorSizeInBits(), llvm::ScalarEvolution::GetMinTrailingZeros(), llvm::HexagonMCInstrInfo::getMinValue(), llvm::ReachingDefAnalysis::getMIOperand(), GetMnemonic(), llvm::codeview::getModifiedType(), getModifier(), llvm::BasicAAResult::getModRefInfo(), llvm::AAResults::getModRefInfo(), llvm::BasicAAResult::getModRefInfoMask(), llvm::ModuleSummaryIndex::getModule(), llvm::pdb::NativeSession::getModuleDebugStream(), llvm::pdb::DbiModuleList::getModuleDescriptor(), llvm::ModuleSummaryIndex::getModuleHash(), llvm::ScalarEvolution::getMonotonicPredicateType(), llvm::APIntOps::GetMostSignificantDifferentBit(), llvm::MipsMCCodeEmitter::getMovePRegSingleOpValue(), getMSAMapping(), llvm::AMDGPU::SendMsg::getMsgOpName(), getMul24(), llvm::ScalarEvolution::getMulExpr(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), llvm::DIInliningInfo::getMutableFrame(), getMVEIndexedAddressParts(), llvm::getN1Bits(), llvm::Intrinsic::getName(), llvm::MCInstrInfo::getName(), llvm::opt::Option::getName(), llvm::StructType::getName(), llvm::TargetLibraryInfo::getName(), llvm::jitlink::Symbol::getName(), llvm::coverage::InstantiationGroup::getName(), llvm::DIScope::getName(), llvm::DWARFDebugNames::NameIndex::getNameTableEntry(), getNameWithPrefixImpl(), getNarrowTypeBreakDown(), llvm::ConstantExpr::getNeg(), llvm::LoopNest::getNestDepth(), getNewAlignment(), getNewDefiningAccessForClone(), llvm::HexagonMCInstrInfo::getNewValueOperand(), llvm::HexagonMCInstrInfo::getNewValueOperand2(), llvm::codeview::TypeTableCollection::getNext(), llvm::FaultMapParser::FunctionInfoAccessor::getNextFunctionInfo(), llvm::HexagonBlockRanges::InstrIndexMap::getNextIndex(), llvm::StackMaps::getNextMetaArgIdx(), llvm::rdf::RefNode::getNextRef(), llvm::rdf::DataFlowGraph::getNextRelated(), llvm::SchedBoundary::getNextResourceCycle(), llvm::PatchPointOpers::getNextScratchIdx(), llvm::rdf::DataFlowGraph::getNextShadow(), llvm::GCNSchedStrategy::getNextStage(), llvm::Automaton< uint64_t >::getNfaPaths(), llvm::AMDGPU::MTBUFFormat::getNfmtName(), llvm::LazyCallGraph::Edge::getNode(), llvm::SUnit::getNode(), llvm::RegionBase< RegionTraits< Function > >::getNode(), llvm::SelectionDAG::getNode(), llvm::RegionNodeBase< RegionTraits< Function > >::getNodeAs(), llvm::PiBlockDDGNode::getNodes(), llvm::DDGBuilder::getNodesInPiBlock(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::Type::getNonOpaquePointerElementType(), llvm::ISD::ArgFlagsTy::getNonZeroByValAlign(), llvm::ScalarEvolution::getNoopOrAnyExtend(), llvm::ScalarEvolution::getNoopOrSignExtend(), llvm::ScalarEvolution::getNoopOrZeroExtend(), llvm::ValueLatticeElement::getNot(), llvm::ConstantExpr::getNot(), llvm::ValueLatticeElement::getNotConstant(), llvm::ScalarEvolution::getNotSCEV(), getNumAllocatableRegsForConstraints(), llvm::LoopBase< BasicBlock, Loop >::getNumBackEdges(), llvm::object::COFFSymbolRef::getNumberOfAuxSymbols(), llvm::PPCTTIImpl::getNumberOfRegisters(), llvm::LoopBase< BasicBlock, Loop >::getNumBlocks(), llvm::msf::getNumFpmIntervals(), llvm::DIExpression::getNumLocationOperands(), getNumMicroOpsSwiftLdSt(), llvm::GCStatepointInst::getNumPatchBytes(), llvm::TargetLoweringBase::getNumRegisters(), llvm::getNumSizeComponents(), llvm::LatencyPriorityQueue::getNumSolelyBlockNodes(), llvm::ResourcePriorityQueue::getNumSolelyBlockNodes(), llvm::CallBase::getNumSubclassExtraOperandsDynamic(), getNumVectorRegs(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectAllocation(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineFrameInfo::getObjectSSPLayout(), llvm::AMDGPUSubtarget::getOccupancyWithLocalMemSize(), llvm::DICompositeType::getODRTypeIfExists(), llvm::DWPStringPool::getOffset(), llvm::DWARFDie::getOffset(), llvm::StringTableBuilder::getOffset(), llvm::AliasResult::getOffset(), llvm::StackMapParser< Endianness >::LocationAccessor::getOffset(), llvm::MCSymbol::getOffset(), llvm::MachineOperand::getOffset(), llvm::MCCFIInstruction::getOffset(), llvm::DIE::getOffset(), llvm::LifetimeSDNode::getOffset(), llvm::ARMBasicBlockUtils::getOffsetOf(), llvm::codeview::LazyRandomTypeCollection::getOffsetOfType(), llvm::RISCVRegisterInfo::getOffsetOpcodes(), llvm::AArch64RegisterInfo::getOffsetOpcodes(), llvm::TargetRegisterInfo::getOffsetOpcodes(), llvm::CSKYMCCodeEmitter::getOImmOpValue(), getOnesVector(), llvm::rdf::RefNode::getOp(), llvm::NearMissInfo::getOpcode(), llvm::LegacyLegalizerInfo::getOpcodeIdxForOpcode(), llvm::LegalizerInfo::getOpcodeIdxForOpcode(), getOpcodeName(), llvm::MemoryBuffer::getOpenFileSlice(), getOpenMPMonotonicityScheduleType(), getOpenMPOrderingScheduleType(), llvm::SCEVCastExpr::getOperand(), llvm::GVNExpression::BasicExpression::getOperand(), llvm::User::getOperand(), llvm::SCEVNAryExpr::getOperand(), llvm::VPUser::getOperand(), llvm::SCEVUDivExpr::getOperand(), llvm::MachineInstr::getOperand(), llvm::UnOpInit::getOperand(), llvm::SDNode::getOperand(), llvm::MDNode::getOperand(), llvm::NamedMDNode::getOperand(), llvm::CallBase::getOperandBundle(), llvm::CallBase::getOperandBundleAt(), llvm::LLVMContextImpl::getOperandBundleTagID(), llvm::NearMissInfo::getOperandClass(), llvm::NearMissInfo::getOperandError(), llvm::NearMissInfo::getOperandIndex(), llvm::MachineOperand::getOperandNo(), llvm::SDNode::use_iterator::getOperandNo(), llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::getOperandNo(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getOperandsScalarizationOverhead(), llvm::User::getOperandUse(), llvm::MipsTargetLowering::getOpndList(), getOpRefinementSteps(), llvm::SIInstrInfo::getOpSize(), getOptimalRepmovsType(), llvm::opt::OptTable::getOption(), llvm::VPlan::getOrAddVPValue(), llvm::ConstantUniqueMap< llvm::ConstantExpr >::getOrCreate(), llvm::LexicalScopes::getOrCreateAbstractScope(), llvm::ContextTrieNode::getOrCreateChildContext(), llvm::sampleprof::CSProfileConverter::FrameNode::getOrCreateChildFrame(), llvm::SPIRVGlobalRegistry::getOrCreateConsIntArray(), llvm::SPIRVGlobalRegistry::getOrCreateConsIntVector(), llvm::SPIRVGlobalRegistry::getOrCreateConstInt(), llvm::SampleContextTracker::getOrCreateContextPath(), getOrCreateDebugLoc(), getOrCreateFixedStackObject(), getOrCreateFrameHelper(), llvm::getOrCreateFunctionComdat(), llvm::pdb::SymbolCache::getOrCreateGlobalSymbolByOffset(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::OpenMPIRBuilder::getOrCreateInternalVariable(), llvm::LiveStacks::getOrCreateInterval(), getOrCreateLogFile(), GetOrCreateOffsetCache(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunctionPtr(), llvm::sampleprof::SampleProfileReader::getOrCreateSamplesFor(), llvm::getOrCreateSanitizerCtorAndInitFunctions(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::MCContext::getOrCreateSymbol(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::SPIRVGlobalRegistry::getOrCreateUndef(), llvm::InformationCache::getOrCreateUniqueBlockExecutionSet(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::getOrderedReduction(), llvm::AllocationOrder::getOrderLimitEnd(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::getOrdinal(), llvm::object::import_lookup_table_entry< IntTy >::getOrdinal(), llvm::COFF::ImportLookupTableEntry32::getOrdinal(), llvm::OptimizationRemarkEmitterWrapperPass::getORE(), llvm::MachineOptimizationRemarkEmitterPass::getORE(), llvm::getOrEnforceKnownAlignment(), llvm::ISD::InputArg::getOrigArgIndex(), getOriginalFunctionType(), llvm::CallGraph::getOrInsertFunction(), llvm::Module::getOrInsertGlobal(), llvm::EquivalenceClasses< llvm::Instruction * >::getOrInsertLeaderValue(), llvm::getOrInsertLibFunc(), llvm::LLVMContextImpl::getOrInsertSyncScopeID(), llvm::ModuleSummaryIndex::getOrInsertValueInfo(), getOrInsertValueProfilingCall(), getOuterLoopLatchCmp(), llvm::AArch64InstrInfo::getOutlinableRanges(), llvm::TargetInstrInfo::getOutliningType(), llvm::AArch64InstrInfo::getOutliningTypeImpl(), getOutputChainFromCallSeq(), getOutputSegmentMap(), llvm::Intrinsic::IITDescriptor::getOverloadArgNumber(), llvm::rdf::InstrNode::getOwner(), llvm::VECustomDAG::getPack(), getPack(), getPackedVectorTypeFromPredicateType(), llvm::HexagonShuffler::GetPacketSummary(), llvm::HvxSelector::getPairVT(), llvm::Argument::getParamAlign(), llvm::CallBase::getParamAttr(), llvm::Argument::getParamByRefType(), llvm::Argument::getParamByValType(), llvm::Argument::getParamInAllocaType(), llvm::Argument::getParamStructRetType(), llvm::LiveRangeEdit::getParent(), llvm::logicalview::LVObject::getParent(), llvm::DWARFUnit::getParentEntry(), llvm::MCCVFunctionInfo::getParentFuncId(), llvm::SourceMgr::getParentIncludeLoc(), llvm::logicalview::LVObject::getParentScope(), llvm::logicalview::LVObject::getParentSymbol(), llvm::LessRecordRegister::RecordParts::getPart(), llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance(), llvm::MCSectionWasm::getPassive(), llvm::PMDataManager::getPassManagerType(), getPayloadString(), llvm::pdb::SymbolGroup::getPdbModuleStream(), getPerfectShuffleCost(), getPermuteMask(), llvm::jitlink::EHFrameCFIBlockInspector::getPersonalityEdge(), llvm::Function::getPersonalityFn(), llvm::memoryaccess_def_iterator_base< MemoryAccess >::getPhiArgBlock(), llvm::PeelingModuloScheduleExpander::getPhiCanonicalReg(), getPHIDeps(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), getPHIDestReg(), getPHINumInputs(), getPHIPred(), getPhiRegs(), getPHISourceReg(), llvm::VirtRegMap::getPhys(), getPhysicalRegisterVT(), llvm::DataDependenceGraph::getPiBlock(), llvm::VETargetLowering::getPICJumpTableRelocBase(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::getPLTStub(), llvm::PluginLoader::getPlugin(), llvm::RegBankSelect::InsertPoint::getPoint(), llvm::VPIntrinsic::getPointerAlignment(), llvm::Value::getPointerAlignment(), llvm::ScalarEvolution::getPointerBase(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), llvm::Value::getPointerDereferenceableBytes(), getPointerOperands(), llvm::WebAssemblyRegisterInfo::getPointerRegClass(), llvm::getPointersDiff(), llvm::SPIRVGlobalRegistry::getPointerStorageClass(), llvm::SimpleBitstreamCursor::getPointerToBit(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::WebAssemblyTTIImpl::getPopcntSupport(), llvm::SystemZTTIImpl::getPopcntSupport(), llvm::PPCTTIImpl::getPopcntSupport(), llvm::RISCVTTIImpl::getPopcntSupport(), llvm::AArch64TTIImpl::getPopcntSupport(), llvm::X86TTIImpl::getPopcntSupport(), llvm::GCNTTIImpl::getPopcntSupport(), llvm::cl::list< DataType, StorageClass, ParserClass >::getPosition(), llvm::cl::bits< DataType, Storage, ParserClass >::getPosition(), llvm::DomTreeUpdater::getPostDomTree(), llvm::SCEVAddRecExpr::getPostIncExpr(), getPostIncrementOperand(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), llvm::LoopBlocksDFS::getPostorder(), getPotentialCopiesOfMemoryValue(), llvm::X86MachineFunctionInfo::getPreallocatedArgOffsets(), llvm::X86MachineFunctionInfo::getPreallocatedStackSize(), llvm::rdf::PhiUseNode::getPredecessor(), llvm::getPredForFCmpCode(), llvm::IRSimilarity::IRInstructionData::getPredicate(), llvm::VPCmpIntrinsic::getPredicate(), llvm::MachineOperand::getPredicate(), getPredicatedRegister(), llvm::NearMissInfo::getPredicateError(), getPredicateForFixedLengthVector(), getPredicateForScalableVector(), llvm::HexagonInstrInfo::getPredReg(), getPredState(), llvm::X86Operand::getPrefix(), llvm::Function::getPrefixData(), llvm::CanonicalLoopInfo::getPreheader(), llvm::CanonicalLoopInfo::getPreheaderIP(), llvm::VPRegionBlock::getPreheaderVPBB(), llvm::RegPressureTracker::getPressureAfterInst(), llvm::HexagonBlockRanges::InstrIndexMap::getPrevIndex(), llvm::DWARFUnit::getPreviousSiblingEntry(), llvm::Type::getPrimitiveSizeInBits(), getProbeFNameForGUID(), llvm::MCSchedModel::getProcResource(), llvm::MachineTraceMetrics::getProcResourceCycles(), llvm::MachineTraceMetrics::Ensemble::getProcResourceDepths(), llvm::MachineTraceMetrics::Ensemble::getProcResourceHeights(), llvm::ProfileSummaryInfo::getProfileCount(), llvm::AVR::getProgramMemoryBank(), llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSaveRestoreInfo(), llvm::Function::getPrologueData(), getPromotedVectorElementType(), getPromotedVTForPredicate(), llvm::NVPTXTargetLowering::getPrototype(), llvm::PressureChange::getPSet(), getPSHUFShuffleMask(), getPTest(), getPtr(), llvm::getPtrStride(), llvm::ConstantExpr::getPtrToInt(), llvm::ScalarEvolution::getPtrToIntExpr(), GetQuadraticEquation(), llvm::AttrBuilder::getRawIntAttr(), llvm::object::ArchiveMemberHeader::getRawName(), getRC32(), llvm::ReachingDefAnalysis::getReachingDef(), llvm::InlineCost::getReason(), llvm::TargetInstrInfo::getReassociationOpcodes(), llvm::VPRecipeBuilder::getRecipe(), getReciprocalOpName(), llvm::RecurrenceDescriptor::getRecurrenceIdentity(), getReducedType(), llvm::InnerLoopVectorizer::getReductionResumeValue(), llvm::Intrinsic::IITDescriptor::getRefArgNumber(), llvm::MCOperand::getReg(), llvm::mca::MCAOperand::getReg(), llvm::DstOp::getReg(), llvm::X86Operand::getReg(), llvm::SDep::getReg(), XtensaOperand::getReg(), llvm::RegOrConstant::getReg(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegAllocationHint(), llvm::RISCVRegisterInfo::getRegAllocationHints(), llvm::PPCRegisterInfo::getRegAllocationHints(), llvm::MachineRegisterInfo::getRegAllocationHints(), llvm::RegisterBankInfo::getRegBank(), llvm::RegisterBankInfo::getRegBankFromConstraints(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), llvm::MCRegisterInfo::getRegClass(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClass(), llvm::MachineInstr::getRegClassConstraint(), llvm::MachineInstr::getRegClassConstraintEffect(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SIRegisterInfo::getRegClassForSizeOnBank(), getRegClassForSVT(), getRegClassFromGRPhysReg(), llvm::SparcTargetLowering::getRegForInlineAsmConstraint(), llvm::RISCVTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::object::Elf_Mips_Options< ELFT >::getRegInfo(), llvm::MCRegisterClass::getRegister(), llvm::ArgDescriptor::getRegister(), llvm::MCCFIInstruction::getRegister(), llvm::MCCFIInstruction::getRegister2(), getRegisterByIndex(), llvm::X86TargetLowering::getRegisterByName(), llvm::TargetRegisterInfo::getRegisterCosts(), llvm::cl::getRegisteredOptions(), getRegisterName(), getRegistersForValue(), llvm::TargetLoweringBase::getRegisterType(), llvm::MachineOperand::getRegLiveOut(), llvm::MachineOperand::getRegMask(), LiveDebugValues::MLocTracker::getRegMLoc(), llvm::AMDGPU::getRegOperandSize(), getRegOrUndef(), llvm::rdf::RefNode::getRegRef(), llvm::CSKYMCCodeEmitter::getRegSeqImmOpValue(), llvm::TargetInstrInfo::getRegSequenceInputs(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), llvm::getRegSequenceSubReg(), llvm::TargetRegisterInfo::getRegSizeInBits(), llvm::SIRegisterInfo::getRegSplitParts(), llvm::getRegState(), llvm::getRegSubRegPair(), getRegTy(), llvm::object::ELFObjectFile< ELFT >::getRel(), llvm::object::ELFObjectFile< ELFT >::getRela(), llvm::rdf::DataFlowGraph::getRelatedRefs(), llvm::jitlink::Edge::getRelocation(), llvm::object::MachOObjectFile::getRelocationOffset(), llvm::object::getRelocationResolver(), getRelocType32(), getRelocType64(), llvm::CCState::getRemainingRegParmsForType(), llvm::RegBankSelect::getRepairCost(), llvm::BuildVectorSDNode::getRepeatedSequence(), GetReplicateRegion(), llvm::X86TTIImpl::getReplicationShuffleCost(), llvm::TargetTransformInfo::getReplicationShuffleCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getReplicationShuffleCost(), llvm::MCSymbolXCOFF::getRepresentedCsect(), llvm::CSKYRegisterInfo::getReservedRegs(), llvm::RISCVRegisterInfo::getReservedRegs(), llvm::LoongArchRegisterInfo::getReservedRegs(), llvm::SIRegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::MachineRegisterInfo::getReservedRegs(), llvm::SDDbgOperand::getResNo(), llvm::AMDGPUResourceUsageAnalysis::getResourceInfo(), llvm::MachineTraceMetrics::getResources(), llvm::mca::getResourceStateIndex(), llvm::NumericSubstitution::getResult(), llvm::AnalysisManager< MachineFunction >::getResult(), llvm::GetElementPtrInst::getResultElementType(), getRetComponentType(), llvm::coro::Shape::getRetconCoroId(), llvm::coro::Shape::getRetconResultTypes(), llvm::coro::Shape::getRetconResumeTypes(), llvm::ARCFunctionInfo::getReturnStackOffset(), llvm::XCoreFunctionInfo::getReturnStackOffset(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::getRInfo(), llvm::jitlink::getRISCVPCRelHi20(), llvm::DominanceFrontierBase< BasicBlock, false >::getRoot(), llvm::DependenceGraphInfo< NodeType >::getRoot(), llvm::DominatorTreeBase< BasicBlock, false >::getRoot(), llvm::EVT::getRoundIntegerType(), llvm::PBQP::Matrix::getRowAsVector(), llvm::PBQP::Matrix::getRows(), llvm::getRuntimeVFAsFloat(), getSafeDivisor(), llvm::InstCombiner::getSafeVectorConstantForBinop(), getSalvageOpsForCopy(), getSalvageOpsForGEP(), getSalvageOpsForTrunc(), getSameOpcode(), llvm::getSamplerName(), llvm::GlobalValue::getSanitizerMetadata(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getScalarizationOverhead(), getScalarMaskingNode(), llvm::SPIRVGlobalRegistry::getScalarOrVectorBitWidth(), llvm::getScalarReductionOpcode(), getScalarSizeInBits(), llvm::FixedPointSemantics::getScale(), getScaledOffsetForBitWidth(), llvm::TargetTransformInfo::getScalingFactorCost(), getScalingFactorCost(), llvm::SelectionDAG::getScatterVP(), llvm::ScalarEvolution::getSCEV(), llvm::MCSchedModel::getSchedClassDesc(), llvm::MCSubtargetInfo::getSchedModelForCPU(), llvm::DebugLoc::getScope(), llvm::DIScope::getScope(), llvm::codeview::getScopeEndOffset(), llvm::codeview::getScopeParentOffset(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getScoreAtLevelRec(), llvm::SIRegisterInfo::getScratchInstrOffset(), llvm::SDDbgOperand::getSDNode(), llvm::MCSymbol::getSection(), llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), llvm::jitlink::MachOLinkGraphBuilder::getSectionByIndex(), llvm::RuntimeDyld::getSectionContent(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileXCOFF::getSectionForConstant(), llvm::TargetLoweringObjectFileXCOFF::getSectionForExternalReference(), llvm::TargetLoweringObjectFileXCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileELF::getSectionForMachineBasicBlock(), llvm::object::COFFObjectFile::getSectionID(), llvm::RuntimeDyld::getSectionLoadAddress(), llvm::object::COFFSymbolRef::getSectionNumber(), llvm::object::XCOFFCsectAuxRef::getSectionOrLength32(), llvm::object::XCOFFCsectAuxRef::getSectionOrLength64(), llvm::Function::getSectionPrefix(), llvm::logicalview::LVBinaryReader::getSectionRanges(), llvm::object::MachOObjectFile::getSectionRawFinalSegmentName(), llvm::object::MachOObjectFile::getSectionRawName(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::SelectionDAG::getSelect(), llvm::ConstantExpr::getSelect(), llvm::ReservoirSampler< T, GenT >::getSelection(), llvm::PBQP::Solution::getSelection(), llvm::gvn::AvailableValue::getSelectValue(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::SelectionDAG::getSetCC(), llvm::AVRTargetLowering::getSetCCResultType(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SelectionDAG::getSetCCVP(), llvm::RISCVVType::getSEWLMULRatio(), llvm::RISCVII::getSEWOpNum(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSExtOrTrunc(), llvm::APInt::getSExtValue(), llvm::mca::MCAOperand::getSFPImm(), llvm::MCOperand::getSFPImm(), llvm::AMDGPUDisassembler::getSgprClassId(), llvm::dxbc::getShaderStage(), llvm::GetShadowBytes(), llvm::GetShadowBytesAfterScope(), llvm::VirtRegMap::getShape(), getShape(), llvm::SelectionDAG::getShiftAmountConstant(), llvm::TargetLoweringBase::getShiftAmountTy(), getShiftedValue(), llvm::AArch64_AM::getShifterImm(), llvm::objcopy::elf::Symbol::getShndx(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), getShuffleComment(), llvm::X86TTIImpl::getShuffleCost(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::TargetTransformInfo::getShuffleCost(), getShuffleDemandedElts(), llvm::getShuffleDemandedElts(), getShuffleHalfVectors(), llvm::MachineOperand::getShuffleMask(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::getShuffleReduction(), getShuffleScalarElt(), llvm::ConstantExpr::getShuffleVector(), llvm::DWARFUnit::getSiblingEntry(), llvm::CmpInst::getSignedPredicate(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::ScalarEvolution::getSignExtendExprImpl(), GetSignReturnAddress(), llvm::MipsMCCodeEmitter::getSimm18Lsl3Encoding(), llvm::MipsMCCodeEmitter::getSimm19Lsl2Encoding(), llvm::MipsMCCodeEmitter::getSimm23Lsl2Encoding(), llvm::MachineRegisterInfo::getSimpleHint(), llvm::codeview::TypeIndex::getSimpleKind(), llvm::codeview::TypeIndex::getSimpleMode(), llvm::gvn::AvailableValue::getSimpleValue(), llvm::EVT::getSimpleVT(), llvm::lto::InputFile::getSingleBitcodeModule(), llvm::DbgVariable::getSingleExpression(), getSingleSchedPred(), llvm::Twine::getSingleStringRef(), llvm::HvxSelector::getSingleVT(), llvm::ConstantExpr::getSIToFP(), llvm::HexagonInstrInfo::getSize(), llvm::DIE::getSize(), llvm::LifetimeSDNode::getSize(), llvm::RegisterBankInfo::getSizeInBits(), llvm::codeview::getSizeInBytesForTypeIndex(), llvm::MipsMCCodeEmitter::getSizeInsEncoding(), llvm::StackMapParser< Endianness >::LocationAccessor::getSmallConstant(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), llvm::AMDGPU::getSMRDEncodedOffset(), llvm::ARM_AM::getSOImmTwoPartSecond(), getSortedConstantKeys(), llvm::SuccIterator< InstructionT, BlockT >::getSource(), llvm::pdb::SymbolCache::getSourceFileById(), getSPDenormModeValue(), llvm::SystemZSubtarget::getSpecialRegisters(), getSpillFunctionFor(), LiveDebugValues::MLocTracker::getSpillMLoc(), llvm::M68kRegisterInfo::getSpillRegisterOrder(), llvm::getSPIRVStringOperand(), llvm::SPIRVGlobalRegistry::getSPIRVTypeID(), llvm::APInt::getSplat(), llvm::ConstantDataVector::getSplat(), llvm::SelectionDAG::getSplat(), llvm::SelectionDAG::getSplatBuildVector(), llvm::PPC::getSplatIdxForPPCMnemonics(), llvm::getSplatIndex(), llvm::ShuffleVectorSDNode::getSplatIndex(), llvm::SelectionDAG::getSplatSourceVector(), llvm::Constant::getSplatValue(), llvm::BuildVectorSDNode::getSplatValue(), llvm::SelectionDAG::getSplatVector(), llvm::DependenceInfo::getSplitIteration(), llvm::MemOp::getSrcAlign(), llvm::R600InstrInfo::getSrcs(), llvm::object::XCOFFCsectAuxRef::getStabInfoIndex32(), llvm::object::XCOFFCsectAuxRef::getStabSectNum32(), llvm::Attribute::getStackAlignment(), llvm::DataLayout::getStackAlignment(), llvm::ModuleSummaryIndex::getStackIdAtIndex(), llvm::ArgDescriptor::getStackOffset(), llvm::SystemZTargetLowering::getStackProbeSize(), llvm::PPCTargetLowering::getStackProbeSize(), llvm::VirtRegMap::getStackSlot(), llvm::TargetInstrInfo::getStackSlotRange(), getStartOrEndSlot(), llvm::GCProjectionInst::getStatepoint(), llvm::InlineCost::getStaticBonusApplied(), llvm::VPIntrinsic::getStaticVectorLength(), llvm::SelectionDAG::getStepVector(), getStepVector(), llvm::MCSymbolXCOFF::getStorageClass(), llvm::object::COFFSymbolRef::getStorageClass(), llvm::TargetLoweringObjectFileXCOFF::getStorageClassForGlobal(), llvm::DIDerivedType::getStorageOffsetInBits(), llvm::SelectionDAG::getStore(), llvm::VPWidenMemoryInstructionRecipe::getStoredValue(), llvm::RISCVTTIImpl::getStoreImmCost(), getStoreOffset(), getStoreTarget(), llvm::SelectionDAG::getStoreVP(), getSToVPermuted(), llvm::SelectionDAG::getStrictFPExtendOrRound(), llvm::AArch64RegisterInfo::getStrictlyReservedRegs(), llvm::DISubrange::getStride(), llvm::DIGenericSubrange::getStride(), llvm::SelectionDAG::getStridedLoadVP(), llvm::SelectionDAG::getStridedStoreVP(), llvm::pdb::NamedStreamMap::getString(), llvm::msgpack::DocNode::getString(), llvm::MDString::getString(), llvm::AsmToken::getStringContents(), llvm::codeview::DebugStringTableSubsection::getStringForId(), llvm::DWARFUnit::getStringOffsetsBase(), llvm::pdb::PDBFile::getStringTable(), llvm::object::COFFSymbolRef::getStringTableOffset(), llvm::SCCPInstVisitor::getStructLatticeValueFor(), llvm::getStructTM(), llvm::TargetRegisterInfo::getSubClassWithSubReg(), llvm::ScheduleDAGTopologicalSort::GetSubGraph(), llvm::LoopBase< BasicBlock, Loop >::getSubLoops(), llvm::LoopBase< BasicBlock, Loop >::getSubLoopsVector(), getSubprogram(), llvm::MachineOperand::getSubReg(), llvm::MCRegisterInfo::getSubReg(), llvm::R600RegisterInfo::getSubRegFromChannel(), llvm::SIRegisterInfo::getSubRegFromChannel(), llvm::MCRegisterInfo::getSubRegIdxOffset(), llvm::MCRegisterInfo::getSubRegIdxSize(), llvm::MCRegisterInfo::getSubRegIndex(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), llvm::TargetRegisterInfo::getSubRegIndexName(), llvm::RegionBase< RegionTraits< Function > >::getSubRegionNode(), llvm::IndexedReference::getSubscript(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::AsmPrinter::getSubtargetInfo(), llvm::SchedDFSResult::getSubtreeID(), llvm::BranchInst::getSuccessor(), llvm::SwitchInst::getSuccessor(), llvm::InvokeInst::getSuccessor(), llvm::CallBrInst::getSuccessor(), llvm::CatchSwitchInst::getSuccessor(), llvm::SwitchInst::CaseHandleImpl< SwitchInst, ConstantInt, BasicBlock >::getSuccessorIndex(), llvm::DCData::getSuccessorLabel(), llvm::GetSuccessorNumber(), getSuccState(), llvm::APInt::getSufficientBitsNeeded(), llvm::ScaledNumbers::getSum(), llvm::IndexedInstrProfReader::getSummary(), llvm::getSurfaceName(), getSVECalleeSaveSlotRange(), getSVEContainerType(), getSVEPredicateBitCast(), llvm::coro::Shape::getSwitchCoroId(), llvm::coro::Shape::getSwitchIndexField(), llvm::coro::Shape::getSwitchResumePointerType(), llvm::DwarfStringPoolEntryRef::getSymbol(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::getSymbol(), llvm::object::COFFObjectFile::getSymbolAuxData(), llvm::object::XCOFFObjectFile::getSymbolAuxType(), llvm::pdb::SymbolCache::getSymbolById(), llvm::objcopy::macho::SymbolTable::getSymbolByIndex(), llvm::object::TapiFile::getSymbolFlags(), GetSymbolFromOperand(), llvm::M68kMCInstLower::GetSymbolFromOperand(), llvm::SelectionDAG::getSymbolFunctionGlobalAddress(), llvm::object::ExceptionSectionEntry< AddressType >::getSymbolIndex(), llvm::object::COFFObjectFile::getSymbolIndex(), llvm::MachineOperand::getSymbolName(), GetSymbolRef(), llvm::RuntimeDyld::getSymbolSectionID(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), getSymTab(), llvm::TextInstrProfReader::getSymtab(), llvm::RawInstrProfReader< IntPtrT >::getSymtab(), getT2IndexedAddressParts(), llvm::ARM_AM::getT2SOImmTwoPartFirst(), llvm::ARM_AM::getT2SOImmTwoPartSecond(), llvm::MCSymbolWasm::getTableType(), getTagSymNode(), getTargetConstantBitsFromNode(), llvm::RISCVTargetLowering::getTargetConstantFromLoad(), llvm::X86TargetLowering::getTargetConstantFromLoad(), getTargetIndexName(), getTargetShuffleAndZeroables(), getTargetShuffleMask(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getTestBitReg(), getTestUnderMaskCond(), llvm::getTextureName(), llvm::AArch64RegisterInfo::getThisReturnPreservedMask(), llvm::MachineModuleInfoMachO::getThreadLocalGVStubEntry(), llvm::InlineCost::getThreshold(), llvm::MachineIRBuilder::getTII(), llvm::AArch64RegisterInfo::getTLSCallPreservedMask(), llvm::ARMBaseRegisterInfo::getTLSCallPreservedMask(), llvm::PPCSubtarget::getTOCPointerRegister(), llvm::X86Operand::getToken(), XtensaOperand::getToken(), getTransSwizzle(), llvm::object::ExceptionSectionEntry< AddressType >::getTrapInstAddr(), llvm::CanonicalLoopInfo::getTripCount(), llvm::ScalarEvolution::getTripCountFromExitCount(), llvm::ConstantInt::getTrue(), getTrueOrFalseValue(), llvm::ConstantExpr::getTrunc(), llvm::VectorType::getTruncatedElementVectorType(), getTruncatedUSUBSAT(), llvm::ScalarEvolution::getTruncateExpr(), llvm::ScalarEvolution::getTruncateOrNoop(), llvm::ScalarEvolution::getTruncateOrSignExtend(), llvm::ScalarEvolution::getTruncateOrZeroExtend(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTruncStoreAction(), llvm::SelectionDAG::getTruncStoreVP(), llvm::SelectionDAG::getTruncStridedStoreVP(), llvm::AMDGPUDisassembler::getTtmpClassId(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), getTwoPredecessors(), llvm::codeview::TypeTableCollection::getType(), llvm::pdb::TpiStream::getType(), llvm::codeview::LazyRandomTypeCollection::getType(), llvm::object::COFFSymbolRef::getType(), llvm::StructType::getTypeAtIndex(), llvm::AttrBuilder::getTypeAttr(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), llvm::TargetLoweringBase::getTypeConversion(), llvm::ConstantStruct::getTypeForElements(), llvm::EVT::getTypeForEVT(), llvm::AMDGPUTargetLowering::getTypeForExtReturn(), llvm::SPIRVGlobalRegistry::getTypeForSPIRVType(), getTypeFromTypeIdx(), llvm::BitcodeReaderValueList::getTypeID(), llvm::dxil::ValueEnumerator::getTypeID(), llvm::ValueEnumerator::getTypeID(), llvm::BTFDebug::getTypeId(), llvm::getTypeName(), llvm::getTypePacking(), getTypePartition(), llvm::DataLayout::getTypeSizeInBits(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::TargetLoweringBase::getTypeToExpandTo(), llvm::TargetLoweringBase::getTypeToPromoteTo(), llvm::ScalarEvolution::getUDivExpr(), llvm::MipsMCCodeEmitter::getUImm3Mod8Encoding(), llvm::MipsMCCodeEmitter::getUImm4AndValue(), llvm::MipsMCCodeEmitter::getUImm5Lsl2Encoding(), llvm::MipsMCCodeEmitter::getUImmWithOffsetEncoding(), llvm::msgpack::DocNode::getUInt(), llvm::ConstantExpr::getUIToFP(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), getUnderlyingExtractedFromVec(), llvm::getUnderlyingObject(), getUnderlyingObjectFromInt(), getUnderlyingObjectsForInstr(), llvm::logicalview::LVTypeDefinition::getUnderlyingType(), getUniformBase(), llvm::AAPointerInfo::RangeList::getUnique(), llvm::getUniqueExitBlocksHelper(), llvm::Constant::getUniqueInteger(), llvm::LoopBase< BasicBlock, Loop >::getUniqueNonLatchExitBlocks(), llvm::ScalarEvolution::getUnknown(), getUnmergeResults(), llvm::VECustomDAG::getUnpack(), llvm::MCSymbolXCOFF::getUnqualifiedName(), getUnrollAndJammedLoopSize(), UnrollCostEstimator::getUnrolledLoopSize(), llvm::GetUnrollMetadata(), llvm::CmpInst::getUnsignedPredicate(), llvm::WasmEHFuncInfo::getUnwindDest(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::WasmEHFuncInfo::getUnwindSrcs(), llvm::DISubrange::getUpperBound(), llvm::DIGenericSubrange::getUpperBound(), llvm::RegPressureTracker::getUpwardPressureDelta(), llvm::ScalarEvolution::getURemExpr(), llvm::MachineInstr::getUsedDebugRegs(), getUsedNZCV(), getUsedRegMask(), llvm::DFAPacketizer::getUsedResources(), llvm::Attribute::getUWTableKind(), getV4X86ShuffleImm(), getv64i1Argument(), llvm::CondOpInit::getVal(), llvm::SelectionDAG::getValidMaximumShiftAmountConstant(), llvm::SelectionDAG::getValidMinimumShiftAmountConstant(), llvm::SelectionDAG::getValidShiftAmountConstant(), llvm::TrackingVH< Value >::getValPtr(), llvm::pdb::NativeSymbolEnumerator::getValue(), llvm::ScheduleDAGSDNodes::RegDefIter::GetValue(), llvm::LocationSize::getValue(), llvm::ValueInfo::getValue(), llvm::object::COFFSymbolRef::getValue(), llvm::cl::OptionValueCopy< cl::boolOrDefault >::getValue(), llvm::AttributeImpl::getValueAsBool(), llvm::Attribute::getValueAsBool(), llvm::AttributeImpl::getValueAsInt(), llvm::Attribute::getValueAsInt(), llvm::AttributeImpl::getValueAsString(), llvm::Attribute::getValueAsString(), llvm::AttributeImpl::getValueAsType(), llvm::Attribute::getValueAsType(), getValueFromBundleOpInfo(), getValueFromCondition(), getValueFromConditionImpl(), llvm::ValueEnumerator::getValueID(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::Value::getValueName(), llvm::MCCFIInstruction::getValues(), llvm::PhiValues::getValuesForPhi(), llvm::SDNode::getValueType(), llvm::object::COFFObjectFile::getVaPtr(), llvm::WebAssemblyFunctionInfo::getVarargBufferVreg(), llvm::DbgVariableIntrinsic::getVariableLocationOp(), llvm::MCSymbol::getVariableValue(), getVariantMatchScore(), llvm::LiveVariables::getVarInfo(), llvm::DIDerivedType::getVBPtrOffset(), GetVBR(), llvm::GlobalObject::getVCallVisibility(), llvm::RISCVII::getVecPolicyOpNum(), llvm::HexagonMCInstrInfo::GetVecRegPairIndices(), llvm::SystemZTTIImpl::getVectorBitmaskConversionCost(), llvm::EVT::getVectorElementCount(), llvm::LegalizerHelper::getVectorElementPointer(), llvm::EVT::getVectorElementType(), getVectorFCMP(), llvm::PPCTTIImpl::getVectorInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), llvm::RISCVTTIImpl::getVectorInstrCost(), llvm::TargetTransformInfo::getVectorInstrCost(), llvm::LoopVectorizationCostModel::getVectorIntrinsicCost(), llvm::HexagonSubtarget::getVectorLength(), llvm::EVT::getVectorNumElements(), getVectorShiftImm(), llvm::SelectionDAG::getVectorShuffle(), getVectorShuffleOpcode(), llvm::TargetLowering::getVectorSubVecPointer(), llvm::SystemZTTIImpl::getVectorTruncCost(), llvm::VFABI::getVectorVariantNames(), llvm::AMDGPUDisassembler::getVgprClassId(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm::slpvectorizer::BoUpSLP::VLOperands::getVL(), getVLDSTRegisterUpdateOpcode(), llvm::RISCVInstrInfo::getVLENFactoredAmount(), getVLOperand(), llvm::RISCVII::getVLOpNum(), llvm::AMDGPU::getVOPDComponents(), llvm::PPCTTIImpl::getVPMemoryOpCost(), llvm::VPDef::getVPSingleValue(), llvm::VPDef::getVPValue(), llvm::VPlan::getVPValue(), llvm::SDDbgOperand::getVReg(), llvm::SelectionDAG::getVRegDbgValue(), llvm::MachineRegisterInfo::getVRegDef(), llvm::PerFunctionMIParsingState::getVRegInfoNamed(), llvm::RegisterBankInfo::OperandsMapper::getVRegs(), llvm::getVRegSubRegDef(), llvm::SelectionDAG::getVScale(), llvm::Attribute::getVScaleRangeMax(), llvm::Attribute::getVScaleRangeMin(), getVShift(), llvm::PPCMCCodeEmitter::getVSRpEvenEncoding(), llvm::WebAssemblyFunctionInfo::getWAReg(), llvm::WebAssemblyFunctionInfo::getWARegStackId(), llvm::MachineFunction::getWasmLandingPadIndex(), getWFCountLimitedByGPR(), llvm::getWhileLoopStartTargetBB(), llvm::LoopVectorizationCostModel::getWideningCost(), llvm::LoopVectorizationCostModel::getWideningDecision(), llvm::Attribute::getWithAlignment(), llvm::Attribute::getWithAllocSizeArgs(), llvm::Attribute::getWithDereferenceableBytes(), llvm::Attribute::getWithDereferenceableOrNullBytes(), llvm::Type::getWithNewBitWidth(), llvm::Attribute::getWithNewType(), llvm::ConstantExpr::getWithOperands(), llvm::Attribute::getWithStackAlignment(), llvm::SIMachineFunctionInfo::getWorkGroupIDSGPR(), llvm::mca::WriteRef::getWriteBackCycle(), llvm::MCSubtargetInfo::getWriteLatencyEntry(), llvm::AAPointerInfo::Access::getWrittenValue(), getX86MaskVec(), getX86SubType(), getX86XALUOOp(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef(), llvm::MCContext::getXCOFFSection(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::RuntimeDyldChecker::MemoryRegionInfo::getZeroFillLength(), llvm::SlotIndexes::getZeroIndex(), getZeroVector(), llvm::ConstantExpr::getZExt(), llvm::APInt::getZExtValue(), llvm::CodeViewYAML::GlobalHash::GlobalHash(), llvm::codeview::GloballyHashedType::GloballyHashedType(), llvm::GlobalsAAResult::GlobalsAAResult(), llvm::GlobalValueSummary::GlobalValueSummary(), llvm::GlobalVariable::GlobalVariable(), llvm::jitlink::ELFLinkGraphBuilder< object::ELF64LE >::graphifySections(), llvm::IntEqClasses::grow(), llvm::DenseMap< llvm::SmallVector< llvm::VPValue *, 4 >, llvm::VPInstruction *, BundleDenseMapInfo >::grow(), llvm::SmallDenseMap< const llvm::RecurrenceDescriptor *, unsigned, N >::grow(), llvm::User::growHungoffUses(), guessCharByteSize(), llvm::ARM::WinEH::RuntimeFunction::H(), llvm::ARM::WinEH::RuntimeFunctionARM64::H(), llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleAddNode(), llvm::DotCfgChangeReporter::handleAfter(), llvm::CallLowering::handleAssignments(), llvm::MipsTargetLowering::HandleByVal(), HandleByValArgument(), HandleCallsInBlockInlinedThroughInvoke(), llvm::DIArgList::handleChangedOperand(), llvm::AMDGPULegalizerInfo::handleD16VData(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::ValueAsMetadata::handleDeletion(), handleDiagnostic(), llvm::CrashRecoveryContext::HandleExit(), llvm::DotCfgChangeReporter::handleFiltered(), llvm::DotCfgChangeReporter::handleFunctionCompare(), llvm::DotCfgChangeReporter::handleIgnored(), llvm::TextChangeReporter< IRDataT< EmptyData > >::handleInitialIR(), llvm::DotCfgChangeReporter::handleInitialIR(), HandleInlinedEHPad(), llvm::DotCfgChangeReporter::handleInvalidated(), llvm::ChangeReporter< IRDataT< EmptyData > >::handleInvalidatedPass(), llvm::ChangeReporter< IRDataT< EmptyData > >::handleIRAfterPass(), handleMemIntrinsicPtrUse(), llvm::orc::SimpleRemoteEPC::handleMessage(), llvm::orc::SimpleRemoteEPCServer::handleMessage(), handleMiddleInst(), llvm::LiveIntervals::handleMove(), llvm::LiveIntervals::handleMoveIntoNewBundle(), handleMustTailForwardedRegisters(), llvm::Constant::handleOperandChange(), llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), HandlePrefixedOrGroupedOption(), llvm::ValueAsMetadata::handleRAUW(), llvm::GISelCSEInfo::handleRecordedInst(), llvm::VPRecipeBuilder::handleReplication(), llvm::LiveVariables::HandleVirtRegUse(), llvm::X86FrameLowering::has128ByteRedZone(), llvm::mdconst::hasa(), llvm::AliasSummary::hasAliasee(), llvm::Instruction::hasAllowContract(), llvm::Instruction::hasAllowReassoc(), llvm::Instruction::hasAllowReciprocal(), hasAnyUnrollPragma(), llvm::SDNode::hasAnyUseOfValue(), llvm::Instruction::hasApproxFunc(), llvm::Instruction::hasAtomicLoad(), llvm::Instruction::hasAtomicStore(), llvm::hasAttributeInAssume(), hasAttributeProperty(), llvm::DWARFDie::hasChildren(), llvm::DbgVariable::hasComplexAddress(), hasConditionalTerminator(), llvm::scc_iterator< GraphT, GT >::hasCycle(), hasDebugInfo(), llvm::DomainValue::hasDomain(), llvm::DWARFDebugLine::Prologue::hasFileAtIndex(), llvm::SubtargetFeatures::hasFlag(), llvm::CallBase::hasFnAttr(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors(), hasFPAssociativeFlags(), llvm::ItaniumPartialDemangler::hasFunctionQualifiers(), llvm::hashing::detail::hash_combine_range_impl(), llvm::hash_value(), llvm::pdb::hashTagRecord(), hasIdenticalHalvesShuffleMask(), llvm::RawInstrProfReader< IntPtrT >::hasMemoryProfile(), hasMoreThanOneUseOtherThanLLVMUsed(), hasMustTailCallers(), llvm::GCNSchedStrategy::hasNextStage(), llvm::Instruction::hasNoInfs(), llvm::Instruction::hasNoNaNs(), llvm::DbgValueHistoryMap::hasNonEmptyLocation(), llvm::Instruction::hasNoSignedZeros(), llvm::SDNode::hasNUsesOfValue(), hasOneUse(), llvm::Attribute::hasParentContext(), llvm::AttributeSet::hasParentContext(), llvm::AttributeList::hasParentContext(), llvm::hasPartialIVCondition(), llvm::pdb::PDBFile::hasPDBInjectedSourceStream(), llvm::pdb::PDBFile::hasPDBStringTable(), llvm::MachineInstr::hasProperty(), llvm::X86InstrInfo::hasReassociableOperands(), llvm::HexagonPacketizerList::hasRegMaskDependence(), llvm::AMDGPU::VOPD::ComponentProps::hasRegSrcOperand(), llvm::OpenMPIRBuilderConfig::hasRequiresUnifiedSharedMemory(), hasSameExtUse(), hasSingleAllocType(), llvm::IndexedReference::hasSpacialReuse(), llvm::TargetLoweringBase::hasTargetDAGCombine(), llvm::IndexedReference::hasTemporalReuse(), hasTocDataAttr(), hasUseOtherThanLLVMUsed(), llvm::VFShape::hasValidParameterList(), hasVectorBeenPadded(), haveCommonPrefix(), llvm::haveNoCommonBitsSet(), llvm::SelectionDAG::haveNoCommonBitsSet(), haveSameOperands(), haveSameSpecialState(), llvm::HexagonLowerToMC(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), llvm::HexagonSubtarget::HexagonSubtarget(), hoistAndMergeSGPRInits(), hoistLoopToNewParent(), llvm::hoistRegion(), hoistValue(), llvm::HUerrBound(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::identifyKnownAlignedObject(), llvm::BumpPtrAllocatorImpl< MallocAllocator, 65536 >::identifyKnownObject(), llvm::DebugHandlerBase::identifyScopeMarkers(), llvm::IDFCalculator< IsPostDom >::IDFCalculator(), if(), IfNeededExtSP(), IfNeededLDAWSP(), llvm::HexagonInstrInfo::immediateExtend(), llvm::LegalizeRuleSet::immIdx(), llvm::FunctionImporter::importFunctions(), llvm::GCNRegPressure::inc(), IncomingValuesAreCompatible(), llvm::ValueEnumerator::incorporateFunction(), incorporateNewSCCRange(), IncorporateWeight(), increaseSetPressure(), llvm::vfs::directory_iterator::increment(), llvm::vfs::recursive_directory_iterator::increment(), llvm::TargetLowering::IncrementMemoryAddress(), llvm::Register::index2StackSlot(), llvm::Register::index2VirtReg(), llvm::IndexedReference::IndexedReference(), indirectCopyToAGPR(), llvm::MemoryBuffer::init(), llvm::StringMapImpl::init(), llvm::FunctionVarLocs::init(), llvm::Timer::init(), llvm::RegPressureTracker::init(), llvm::RegBankSelect::init(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::initEmpty(), llvm::PreRARematStage::initGCNSchedStage(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::GenericUniformityAnalysisImpl< ContextT >::initialize(), llvm::codeview::DebugInlineeLinesSubsectionRef::initialize(), llvm::R600SchedStrategy::initialize(), llvm::StackProtectorDescriptor::initialize(), llvm::orc::SharedMemoryMapper::initialize(), llvm::orc::LLJIT::initialize(), initialize(), llvm::ConvergingVLIWScheduler::initialize(), llvm::GenericScheduler::initialize(), INITIALIZE_PASS(), llvm::PMDataManager::initializeAnalysisImpl(), llvm::pdb::UDTLayoutBase::initializeChildren(), llvm::DbgVariable::initializeDbgValue(), llvm::MIRParserImpl::initializeMachineFunction(), llvm::DbgVariable::initializeMMI(), llvm::FunctionLoweringInfo::InitializeRegForValue(), llvm::GCNSubtarget::initializeSubtargetDependencies(), llvm::MipsSubtarget::initializeSubtargetDependencies(), llvm::AMDGPUTargetStreamer::initializeTargetID(), llvm::mca::initializeUsedResources(), llvm::RegPressureTracker::initLiveThru(), llvm::TailDuplicator::initMF(), llvm::ScheduleDAGSDNodes::InitNumRegDefsLeft(), llvm::ResourceManager::initProcResourceVectors(), llvm::ScheduleDAGMILive::initQueues(), llvm::ScheduleDAGMILive::initRegPressure(), llvm::MachineFunction::initTargetMachineFunctionInfo(), llvm::WebAssemblyFunctionInfo::initWARegs(), injectPendingInvariantConditions(), llvm::InlineFunction(), inlineGetBaseAndOffset(), inlineHistoryIncludes(), inlineRetainOrClaimRVCalls(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::yaml::ScalarTraits< SwiftVersion >::input(), llvm::GISelWorkList< 8 >::insert(), llvm::PriorityWorklist< llvm::LazyCallGraph::SCC *, SmallVector< llvm::LazyCallGraph::SCC *, N >, SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t > >::insert(), OutputBuffer::insert(), llvm::IRBuilderBase::Insert(), llvm::StringMap< uint64_t >::insert(), llvm::TinyPtrVector< llvm::VPValue * >::insert(), llvm::BitTracker::RegisterCell::insert(), llvm::RuntimePointerChecking::insert(), llvm::IntervalTree< LVAddress, LVScope * >::insert(), llvm::SmallVectorImpl< uint64_t >::insert(), llvm::MachineBasicBlock::insert(), llvm::VPBasicBlock::insert(), insert128BitVector(), insert1BitVector(), llvm::VPRecipeBase::insertAfter(), llvm::MachineBasicBlock::insertAfter(), llvm::MachineBasicBlock::insertAfterBundle(), llvm::objcarc::BundledRetainClaimRVs::insertAfterInvokes(), llvm::insertAssignInstr(), llvm::ScheduleDAGInstrs::insertBarrierChain(), llvm::VPRecipeBase::insertBefore(), insertBitcasts(), llvm::DecoderUInt128::insertBits(), llvm::APInt::insertBits(), llvm::VPBlockUtils::insertBlockAfter(), llvm::BPFInstrInfo::insertBranch(), llvm::XCoreInstrInfo::insertBranch(), llvm::ARCInstrInfo::insertBranch(), llvm::CSKYInstrInfo::insertBranch(), llvm::WebAssemblyInstrInfo::insertBranch(), llvm::NVPTXInstrInfo::insertBranch(), llvm::LoongArchInstrInfo::insertBranch(), llvm::MSP430InstrInfo::insertBranch(), llvm::MipsInstrInfo::insertBranch(), llvm::VEInstrInfo::insertBranch(), llvm::SparcInstrInfo::insertBranch(), llvm::RISCVInstrInfo::insertBranch(), llvm::AVRInstrInfo::insertBranch(), llvm::HexagonInstrInfo::insertBranch(), llvm::LanaiInstrInfo::insertBranch(), llvm::ARMBaseInstrInfo::insertBranch(), llvm::R600InstrInfo::insertBranch(), llvm::AArch64InstrInfo::insertBranch(), llvm::SystemZInstrInfo::insertBranch(), llvm::M68kInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::X86InstrInfo::insertBranch(), llvm::PPCInstrInfo::insertBranch(), insertCandidatesWithPendingInjections(), insertCSRRestores(), insertCSRSaves(), llvm::DIBuilder::insertDbgAssign(), llvm::insertDebugValuesForPHIs(), llvm::DominatorTreeBase< BasicBlock, false >::insertEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), llvm::LazyCallGraph::insertEdge(), insertFoldCacheEntry(), InsertFPConstInst(), llvm::IntervalMapImpl::LeafNode< uint64_t, uint16_t, N, IntervalMapHalfOpenInfo< uint64_t > >::insertFrom(), llvm::MachineModuleInfo::insertFunction(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::RISCVInstrInfo::insertIndirectBranch(), llvm::SIInstrInfo::insertIndirectBranch(), insertInteger(), llvm::LazyCallGraph::RefSCC::insertInternalRefEdge(), llvm::Instruction::insertInto(), llvm::BasicBlock::insertInto(), llvm::ScopedHashTable< K, V, DenseMapInfo< K >, MallocAllocator >::insertIntoScope(), insertLifetimeMarkersSurroundingCall(), llvm::SlotIndexes::insertMachineInstrInMaps(), insertMaskedValue(), llvm::LiveIntervals::insertMBBInMaps(), llvm::SlotIndexes::insertMBBInMaps(), llvm::insertMultibyteShift(), llvm::InstCombiner::InsertNewInstBefore(), InsertNewValueIntoMap(), llvm::FoldingSetBase::InsertNode(), llvm::FoldingSetImpl< ContextualFoldingSet< T, Ctx >, T >::InsertNode(), llvm::MipsInstrInfo::insertNop(), insertNopBeforeInstruction(), llvm::LazyCallGraph::RefSCC::insertOutgoingEdge(), llvm::AArch64InstrInfo::insertOutlinedCall(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), insertParsePoints(), llvm::TargetPassConfig::insertPass(), insertPHI(), llvm::InstCombinerImpl::insertRangeTest(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::codeview::AppendingTypeTableBuilder::insertRecord(), llvm::codeview::MergingTypeTableBuilder::insertRecord(), llvm::codeview::GlobalTypeTableBuilder::insertRecord(), llvm::codeview::MergingTypeTableBuilder::insertRecordAs(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), insertRelocationStores(), insertRematerializationStores(), llvm::SIInstrInfo::insertReturn(), llvm::objcarc::BundledRetainClaimRVs::insertRVCallWithColors(), InsertSafepointPoll(), llvm::AArch64InstrInfo::insertSelect(), llvm::SystemZInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), insertSinCosCall(), InsertSPConstInst(), insertSpills(), llvm::CallLowering::insertSRetIncomingArgument(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), insertSubVector(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialRefEdge(), llvm::VPBlockUtils::insertTwoBlocksAfter(), insertUniqueBackedgeBlock(), llvm::MemorySSAUpdater::insertUse(), insertValues(), insertVector(), llvm::SIInstrInfo::insertVectorSelect(), llvm::MachineRegisterInfo::insertVRegByName(), llvm::RISCVMatInt::Inst::Inst(), llvm::install_bad_alloc_error_handler(), llvm::install_fatal_error_handler(), llvm::install_out_of_memory_new_handler(), llvm::PPCTTIImpl::instCombineIntrinsic(), llvm::ARMTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::HexagonBlockRanges::InstrIndexMap::InstrIndexMap(), llvm::RegBankSelect::InstrInsertPoint::InstrInsertPoint(), llvm::InstrProfError::InstrProfError(), llvm::HexagonMCInstrInfo::instruction(), llvm::Instruction::Instruction(), llvm::mca::Scheduler::instructionCheck(), instructionClobbersQuery(), llvm::SampleProfileProber::instrumentOneFunc(), instrumentOneFunc(), inSubLoop(), llvm::GVNExpression::AggregateValueExpression::int_op_push_back(), llvm::IntAttributeImpl::IntAttributeImpl(), llvm::orc::MaterializationUnit::Interface::Interface(), llvm::LoopVectorizationCostModel::interleavedAccessCanBeWidened(), llvm::InterleaveGroup< InstTy >::InterleaveGroup(), llvm::rdf::CopyPropagation::interpretAsCopy(), llvm::intersectAccessGroups(), llvm::DWARFAddressRange::intersects(), llvm::APInt::intersects(), IntersectSignedRange(), IntersectUnsignedRange(), llvm::rdf::RegisterAggr::intersectWith(), llvm::ConstantRange::intersectWith(), llvm::CoalescingBitVector< IndexT >::intersectWithComplement(), llvm::IntervalData< PointT, ValueT >::IntervalData(), llvm::LiveIntervals::intervalIsInOneMBB(), llvm::IntervalMap< uint64_t, uint16_t, 8, IntervalMapHalfOpenInfo< uint64_t > >::IntervalMap(), llvm::IntervalPartition::IntervalPartition(), llvm::MipsSERegisterInfo::intRegClass(), llvm::Mips16RegisterInfo::intRegClass(), llvm::ConstantRange::intrinsic(), llvm::IntToPtrInst::IntToPtrInst(), llvm::BitVector::invalid(), llvm::SmallBitVector::invalid(), llvm::MachineTraceMetrics::Ensemble::invalidate(), llvm::AnalysisManager< MachineFunction >::invalidate(), llvm::InterleavedAccessInfo::invalidateGroups(), llvm::InterleavedAccessInfo::invalidateGroupsRequiringScalarEpilogue(), llvm::HexagonInstrInfo::invertAndChangeJumpTarget(), llvm::invertCondition(), invertFPCondCodeUser(), invokeFunctionPass(), llvm::IRSimilarity::IRInstructionMapper::IRInstructionMapper(), llvm::orc::IRMaterializationUnit::IRMaterializationUnit(), llvm::IROutliner::IROutliner(), llvm::IRSimilarity::IRSimilarityCandidate::IRSimilarityCandidate(), llvm::BitTracker::BitValue::is(), llvm::X86_MC::is32BitMemOperand(), llvm::ARMSubtarget::isAAPCS16_ABI(), llvm::ARMSubtarget::isAAPCS_ABI(), llvm::Triple::isAArch64(), llvm::isAArch64FrameOffsetLegal(), llvm::HexagonMCInstrInfo::IsABranchingInst(), llvm::jitlink::Symbol::isAbsolute(), IsAcceptableTarget(), isAddConstantOp(), llvm::AArch64InstrInfo::isAddImmediate(), isAddressExpression(), isAddSubOrSubAdd(), llvm::MachineFrameInfo::isAliasedObjectIndex(), isAligned(), llvm::StackLifetime::isAliveAfter(), isAllocSiteRemovable(), llvm::KnownBits::isAllOnes(), isAlternateInstruction(), isAMCompletelyFolded(), llvm::Triple::isAndroidVersionLT(), isAngleBracketString(), llvm::Loop::isAnnotatedParallel(), llvm::ARMSubtarget::isAPCS_ABI(), llvm::CallBase::isArgOperand(), llvm::scc_iterator< GraphT, GT >::isAtEnd(), isBackwardPropagatableCopy(), llvm::MCOperand::isBareSymbolRef(), llvm::DWARFDebugRangeList::RangeListEntry::isBaseAddressSelectionEntry(), llvm::ScalarEvolution::isBasicBlockEntryGuardedByCond(), llvm::InstructionOrdering::isBefore(), IsBetterFallthrough(), isBigEndian(), isBitfieldDstMask(), isBitfieldExtractOpFromAnd(), isBitfieldExtractOpFromSExtInReg(), isBitfieldExtractOpFromShr(), isBitfieldPositioningOp(), isBitfieldPositioningOpFromAnd(), isBitfieldPositioningOpFromShl(), llvm::AArch64InstrInfo::isBranchOffsetInRange(), llvm::SIInstrInfo::isBranchOffsetInRange(), IsBranchOnlyBlock(), llvm::HexagonMCInstrInfo::isBundle(), llvm::CallBase::isBundleOperand(), llvm::isBytewiseValue(), llvm::LazyCallGraph::Edge::isCall(), llvm::AbstractCallSite::isCallee(), llvm::TargetRegisterInfo::isCalleeSavedPhysReg(), llvm::PPCRegisterInfo::isCallerPreservedPhysReg(), llvm::AArch64InstrInfo::isCandidateToMergeOrPair(), llvm::rdf::TargetOperandInfo::isClobbering(), isCmpSameOrSwapped(), llvm::CoalescerPair::isCoalescable(), llvm::MapResolver::isComplete(), isCondRelevantToAnyCallArgument(), llvm::KnownBits::isConstant(), isConstantFalse(), IsConstantOne(), llvm::MachineRegisterInfo::isConstantPhysReg(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::MachineInstr::isConstantValuePHI(), llvm::HexagonMCInstrInfo::isConstExtended(), llvm::HexagonInstrInfo::isConstExtended(), llvm::isConstOrConstSplat(), isContractableFMUL(), isConvertibleToVMV_V_V(), isCopyFeedingInvariantStore(), isCopyFromRegOfInlineAsm(), llvm::isCriticalEdge(), isCrossCopy(), llvm::isCycleInvariant(), llvm::CallBase::isDataOperand(), llvm::LazyCallGraph::Node::isDead(), llvm::MachineOperand::isDead(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineOperand::isDebug(), llvm::GlobalValue::isDeclaration(), llvm::MachineOperand::isDef(), llvm::rdf::RefNode::isDef(), llvm::jitlink::Symbol::isDefined(), llvm::isDereferenceableAndAlignedInLoop(), isDereferenceableAndAlignedPointer(), llvm::AMDGPUTargetLowering::isDesirableToCommuteWithShift(), llvm::RISCVTargetLowering::isDesirableToCommuteWithShift(), llvm::AArch64TargetLowering::isDesirableToCommuteWithShift(), llvm::ARMTargetLowering::isDesirableToCommuteWithShift(), llvm::AArch64TargetLowering::isDesirableToCommuteXorWithShift(), llvm::ARMTargetLowering::isDesirableToCommuteXorWithShift(), isDispOrCDisp8(), llvm::MachineOperand::isEarlyClobber(), IsElementEquivalent(), isElementRotate(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::CastInst::isEliminableCastPair(), llvm::OpenMPIRBuilderConfig::isEmbedded(), llvm::SubtargetFeatures::isEnabled(), llvm::BasicBlock::isEntryBlock(), isEpilogProfitable(), llvm::DenseMapInfo< ValueInfo >::isEqual(), llvm::IRSimilarity::IRInstructionDataTraits::isEqual(), isEqualImpl(), isEvenReg(), isExplicitVecOuterLoop(), llvm::AArch64InstrInfo::isExtendLikelyToBeFolded(), llvm::jitlink::Symbol::isExternal(), llvm::TargetLoweringBase::isExtLoad(), isExtractHiElt(), llvm::HexagonTargetLowering::isExtractSubvectorCheap(), llvm::ShuffleVectorInst::isExtractSubvectorMask(), llvm::MipsCCState::isF128SoftLibCall(), llvm::AMDGPUTargetLowering::isFAbsFree(), llvm::TargetLoweringBase::isFAbsFree(), llvm::Instruction::isFast(), isFloatDIType(), llvm::TargetLoweringBase::isFMADLegal(), llvm::AMDGPUTargetLowering::isFNegFree(), llvm::TargetLoweringBase::isFNegFree(), llvm::AMDGPU::isFoldableLiteralV216(), llvm::TargetLoweringBase::isFPExtFoldable(), llvm::PPCTargetLowering::isFPExtFree(), llvm::TargetLoweringBase::isFPExtFree(), llvm::InductionDescriptor::isFPInductionPHI(), llvm::AArch64InstrInfo::isFPRCopy(), llvm::RISCVRegisterInfo::isFrameOffsetLegal(), llvm::AArch64RegisterInfo::isFrameOffsetLegal(), llvm::PPCRegisterInfo::isFrameOffsetLegal(), llvm::ARMBaseRegisterInfo::isFrameOffsetLegal(), llvm::ItaniumPartialDemangler::isFunction(), llvm::ProfileSummaryInfo::isFunctionHotnessUnknown(), isGCPointerType(), isGEPKnownNonNull(), llvm::AArch64InstrInfo::isGPRCopy(), isGPRShadowAligned(), llvm::AArch64InstrInfo::isGPRZero(), llvm::TargetLowering::isGuaranteedNotToBeUndefOrPoisonForTargetNode(), llvm::isGuaranteedToTransferExecutionToSuccessor(), llvm::SCEVExpander::isHighCostExpansion(), llvm::SystemZ::isHighReg(), llvm::AllocationOrder::isHint(), isHorizontalBinOp(), isHorizontalBinOpPart(), isI32InsnAllUses(), llvm::MachineInstr::isIdenticalTo(), llvm::ShuffleVectorInst::isIdentityMask(), isIdentityValue(), isImm(), llvm::PPCInstrInfo::isImmInstrEligibleForFolding(), llvm::SIInstrInfo::isImmOperandLegal(), llvm::MachineFrameInfo::isImmutableObjectIndex(), llvm::MachineOperand::isImplicit(), llvm::isImpliedByDomCondition(), isImpliedCondAndOr(), llvm::isImpliedCondition(), isIndirectBranchOpcode(), llvm::isIndirectCall(), llvm::InductionDescriptor::isInductionPHI(), llvm::AMDGPU::isInlinableLiteralV216(), llvm::ARMBaseRegisterInfo::isInlineAsmReadOnlyReg(), llvm::SIInstrInfo::isInlineConstant(), llvm::HexagonMCInstrInfo::isInnerLoop(), isInRage(), llvm::ShuffleVectorInst::isInsertSubvectorMask(), llvm::detail::DoubleAPFloat::isInteger(), isInterleaveShuffle(), llvm::MachineOperand::isInternalRead(), isIntExtFree(), isInvalidVOPDY(), llvm::MachineBlockFrequencyInfo::isIrrLoopHeader(), llvm::BlockFrequencyInfo::isIrrLoopHeader(), llvm::MachineOperand::isKill(), llvm::AMDGPU::isKImmOperand(), isKnownBase(), isKnownExactCastIntToFP(), llvm::isKnownNegation(), llvm::isKnownNeverInfinity(), llvm::isKnownNeverNaN(), llvm::TargetLowering::isKnownNeverNaNForTargetNode(), llvm::SelectionDAG::isKnownNeverZero(), llvm::SelectionDAG::isKnownNeverZeroFloat(), isKnownNonNullFromDominatingCondition(), isKnownNonZero(), isKnownNonZeroFromAssume(), isKnownToBeAPowerOfTwo(), llvm::ScalarEvolution::isKnownViaInduction(), isLaneCrossingShuffleMask(), isLdOffsetInRangeOfSt(), isLdStSafeToCluster(), llvm::CombinerHelper::isLegal(), llvm::X86TTIImpl::isLegalAltInstr(), IsLegalOffset(), llvm::BasicBlock::isLegalToHoistInto(), llvm::HexagonPacketizerList::isLegalToPacketizeTogether(), llvm::isLegalToPromote(), llvm::HexagonPacketizerList::isLegalToPruneDependencies(), llvm::SIInstrInfo::isLegalVSrcOperand(), llvm::PPCTargetMachine::isLittleEndian(), llvm::jitlink::Symbol::isLive(), llvm::AAIsDead::isLiveInstSet(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), isLoadStoreSizeLegal(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), llvm::SMSchedule::isLoopCarried(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), isLoopCounter(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), llvm::LoopBase< BasicBlock, Loop >::isLoopExiting(), llvm::MachineLoop::isLoopInvariant(), llvm::LoopBase< BasicBlock, Loop >::isLoopLatch(), isLoopNeverExecuted(), llvm::TargetTransformInfoImplBase::isLoweredToCall(), isLowHalfOnly(), llvm::AMDGPUDisassembler::isMacDPP(), llvm::orc::isMachOInitializerSection(), llvm::Triple::isMacOSXVersionLT(), llvm::isManaged(), llvm::APInt::isMask(), llvm::TargetLowering::AsmOperandInfo::isMatchingInputConstraint(), isMatchingOrAlias(), llvm::APInt::isMaxSignedValue(), llvm::AAPointerInfo::Access::isMayAccess(), llvm::X86Operand::isMaybeDirectBranchDest(), llvm::ARMBaseInstrInfo::isMBBSafeToOutlineFrom(), llvm::MemOp::isMemcpyStrSrc(), llvm::X86Operand::isMemIndexReg(), llvm::HexagonMCInstrInfo::isMemReorderDisabled(), llvm::RecurrenceDescriptor::isMinMaxPattern(), isMinMaxWithLoads(), llvm::APInt::isMinSignedValue(), isMultiLaneShuffleMask(), isMultiple(), llvm::AAPointerInfo::Access::isMustAccess(), isNByteElemShuffleMask(), llvm::APInt::isNegatedPowerOf2(), llvm::ExpressionValue::isNegative(), llvm::ARM_AM::isNEONBytesplat(), AliasScopeTracker::isNoAliasScopeDeclDead(), isNonZeroElementsInOrder(), llvm::X86TargetMachine::isNoopAddrSpaceCast(), llvm::CastInst::isNoopCast(), isNoopPtrIntCastPair(), isNoopShuffleMask(), IsNullTerminatedString(), llvm::MachineFrameInfo::isObjectPreAllocated(), llvm::MachineFrameInfo::isObjectSExt(), llvm::MachineFrameInfo::isObjectZExt(), isOneDimensionalArray(), isOnlyCopiedFromConstantMemory(), isOnlyReachableViaThisEdge(), llvm::SIInstrInfo::isOperandLegal(), llvm::MachineInstr::isOperandSubregIdx(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), llvm::SplitAnalysis::isOriginalEndpoint(), llvm::HexagonMCInstrInfo::isOuterLoop(), llvm::isOverflowIntrinsicNoWrap(), isPackedVectorType(), isPartialOverwrite(), llvm::M68kInstrInfo::isPCRelRegisterOperandLegal(), llvm::FullDependence::isPeelFirst(), llvm::FullDependence::isPeelLast(), llvm::R600RegisterInfo::isPhysRegLiveAcrossClauses(), isPlainlyKilled(), isPointerBitcastEqualTo(), isPointerValueDeadOnEntryToFunction(), llvm::CastIsPossible< To, std::optional< From > >::isPossible(), llvm::isPotentiallyReachable(), llvm::APInt::isPowerOf2(), llvm::CombinerHelper::isPredecessor(), llvm::HexagonInstrInfo::isPredicatedNew(), isPredicatedOnPHI(), llvm::HexagonInstrInfo::isPredicatedTrue(), llvm::HexagonInstrInfo::isPredictedTaken(), llvm::isProcessableCondBI(), isProfitableChain(), llvm::PPCTargetLowering::isProfitableToHoist(), llvm::LoopVectorizationCostModel::isProfitableToScalarize(), llvm::AVR::isProgramMemoryAddress(), isReachableAmongDominated(), llvm::DominatorTreeBase< BasicBlock, false >::isReachableFromEntry(), llvm::ValueInfo::isReadOnly(), llvm::isReadOnlyData(), llvm::SchedulingPriorityQueue::isReady(), isRealSpill(), llvm::RecurrenceDescriptor::isRecurrenceInstr(), isReg(), llvm::M68kSubtarget::isRegisterReservedByUser(), llvm::RISCVSubtarget::isRegisterReservedByUser(), llvm::VirtRegAuxInfo::isRematerializable(), llvm::MachineOperand::isRenamable(), isRepeatedByteSequence(), isRepeatedShuffleMask(), isRepeatedTargetShuffleMask(), llvm::ShuffleVectorInst::isReplicationMask(), isReplicationMaskWithParams(), llvm::isRequiredForExecution(), isReturnNonNull(), llvm::ShuffleVectorInst::isReverseMask(), isREVMask(), llvm::Loop::isRotatedForm(), isSafeDecreasingBound(), isSafeForNoNTrivialUnswitching(), isSafeIncreasingBound(), isSafeLoadOfSelectToSpeculate(), isSafeToMove(), llvm::isSafeToSpeculativelyExecuteWithOpcode(), isSafeToTruncateWideIVType(), llvm::isSampler(), llvm::LLT::isScalable(), llvm::FullDependence::isScalar(), llvm::LoopVectorizationCostModel::isScalarAfterVectorization(), llvm::SPIRVGlobalRegistry::isScalarOfType(), llvm::SPIRVGlobalRegistry::isScalarOrVectorOfType(), llvm::SPIRVGlobalRegistry::isScalarOrVectorSigned(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), llvm::ShuffleVectorInst::isSelectMask(), llvm::LegalizationArtifactCombiner::ArtifactValueFinder::isSequenceFromUnmerge(), isSeveralBitsPositioningOpFromShl(), llvm::SIInstrInfo::isSGPRStackAccess(), isShiftedMask(), isShuffleEquivalent(), isShuffleMaskInputInPlace(), isSignedMinMaxClamp(), isSignedMinMaxIntrinsicClamp(), isSimilarDispOp(), isSimpleVIDSequence(), isSingleSHUFPSMask(), llvm::ShuffleVectorInst::isSingleSourceMask(), isSingleSourceMaskImpl(), llvm::AMDGPU::isSISrcFPOperand(), llvm::AMDGPU::isSISrcInlinableOperand(), llvm::AMDGPU::isSISrcOperand(), llvm::ConstantRange::isSizeStrictlySmallerThan(), llvm::ItaniumPartialDemangler::isSpecialName(), llvm::MachineFrameInfo::isSpillSlotObjectIndex(), llvm::APInt::isSplat(), llvm::PPC::isSplatShuffleMask(), llvm::isSplatValue(), llvm::SelectionDAG::isSplatValue(), llvm::TargetLowering::isSplatValueForTargetNode(), llvm::ShuffleVectorInst::isSpliceMask(), llvm::FullDependence::isSplitable(), llvm::SIInstrInfo::isStackAccess(), llvm::StatepointLoweringState::isStackSlotAllocated(), llvm::MachineFrameInfo::isStatepointSpillSlotObjectIndex(), llvm::SCCPInstVisitor::isStructLatticeConstant(), isSubset(), llvm::APInt::isSubsetOf(), llvm::mca::ResourceManager::issueInstruction(), llvm::isSurface(), llvm::OpenMPIRBuilderConfig::isTargetCodegen(), isTargetShuffleEquivalent(), isTerminalReg(), llvm::isTexture(), llvm::MachineOperand::isTied(), isTileDef(), llvm::isTLIScalarize(), llvm::ShuffleVectorInst::isTransposeMask(), llvm::GlobPattern::isTrivialMatchAll(), isTruncateOf(), llvm::TargetLoweringBase::isTypeLegal(), isUnalignedMemmoryAccess(), llvm::AA::RangeTy::isUnassigned(), isUncondBranchOpcode(), llvm::MachineOperand::isUndef(), llvm::SelectionDAG::isUndef(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), llvm::vputils::isUniformAfterVectorization(), llvm::isUniformLoop(), llvm::AAPointerInfo::RangeList::isUnknown(), llvm::DebugHandlerBase::isUnsignedDIType(), llvm::MachineOperand::isUse(), llvm::rdf::RefNode::isUse(), isValidClauseInst(), isValidDisp(), isValidDPP8(), llvm::AMDGPU::SendMsg::isValidMsgOp(), llvm::AMDGPU::SendMsg::isValidMsgStream(), llvm::HexagonInstrInfo::isValidOffset(), llvm::SMSchedule::isValidSchedule(), llvm::PPCInstrInfo::isValidToBeChangedReg(), IsValueFullyAvailableInBlock(), llvm::ConstantFPSDNode::isValueValidForType(), llvm::MachineFrameInfo::isVariableSizedObjectIndex(), isVariantApplicableInContextHelper(), isVECTOR_SHUFFLE_SPLATI(), isVectorLikeInstWithConstOps(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), llvm::ISD::isVectorShrinkable(), llvm::SIInstrInfo::isVGPRCopy(), llvm::MCSectionXCOFF::isVirtualSection(), isVMerge(), isVMOVModifiedImm(), IsVPNOTEquivalent(), llvm::isVREVMask(), llvm::RISCVTargetLowering::isVScaleKnownToBeAPowerOfTwo(), isVShiftLImm(), isVShiftRImm(), llvm::jitlink::Symbol::isWeaklyReferenced(), isWideDUPMask(), isWideTypeMask(), isWorthFoldingIntoOrrWithShift(), isWorthFoldingSHL(), llvm::ValueInfo::isWriteOnly(), llvm::mca::WriteRef::isWriteZero(), isXXBRShuffleMaskHelper(), llvm::PPC::isXXPERMDIShuffleMask(), llvm::PPC::isXXSLDWIShuffleMask(), llvm::KnownBits::isZero(), llvm::ShuffleVectorInst::isZeroEltSplatMask(), llvm::RuntimeDyldChecker::MemoryRegionInfo::isZeroFill(), iterativelySimplifyCFG(), llvm::jitlink::JITLinker< ELFJITLinker_riscv >::JITLinkerBase(), llvm::jitTargetAddressToPointer(), llvm::IntEqClasses::join(), llvm::LiveRange::join(), llvm::SchedDFSImpl::joinPredSubtree(), llvm::SystemZTargetLowering::joinRegisterPartsIntoValue(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), llvm::SimpleBitstreamCursor::JumpToBit(), llvm::sys::fs::TempFile::keep(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::keep_back(), llvm::BinaryStreamRefBase< WritableBinaryStreamRef, WritableBinaryStream >::keep_front(), KnuthDiv(), llvm::ARM::WinEH::RuntimeFunction::L(), llvm::MCAssembler::layout(), layoutCOFF(), llvm::MCAsmLayout::layoutFragment(), layoutSegments(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvAtTop(), llvm::SplitEditor::leaveIntvBefore(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::AMDGPULegalizerInfo::legalizeBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeBuildVector(), llvm::AMDGPULegalizerInfo::legalizeBVHIntrinsic(), llvm::MipsLegalizerInfo::legalizeCustom(), llvm::ARMLegalizerInfo::legalizeCustom(), llvm::SPIRVLegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeFceil(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeFPTOI(), llvm::AMDGPULegalizerInfo::legalizeFrint(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeKernargMemParameter(), llvm::Legalizer::legalizeMachineFunction(), llvm::AMDGPULegalizerInfo::legalizeMul(), llvm::SIInstrInfo::legalizeOperands(), llvm::VETargetLowering::legalizePackedAVL(), llvm::TargetLowering::LegalizeSetCCCondCode(), llvm::cfg::LegalizeUpdates(), llvm::vfs::recursive_directory_iterator::level(), llvm::MCAsmLexer::Lex(), llvm::LexicalScope::LexicalScope(), lexStringConstant(), llvm::codeview::limitSymbolArrayToScope(), llvm::line_iterator::line_iterator(), LinearizeExprTree(), llvm::remarks::RemarkLinker::link(), llvm::DWARFLinker::link(), llvm::lintFunction(), llvm::symbolize::JSONPrinter::listBegin(), llvm::symbolize::JSONPrinter::listEnd(), littleEndianByteAt(), llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::liveout_begin(), llvm::LiveRange::LiveRange(), lle_X_atexit(), lle_X_fprintf(), lle_X_scanf(), lle_X_sscanf(), llvm_map_to_intrinsic_id(), llvm_regerror(), llvm_regexec(), llvm::LLVMContext::LLVMContext(), LLVMDisasmInstruction(), LLVMExecutionEngineGetErrMsg(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetDebugLocLine(), LLVMGetMetadata(), LLVMGetOperand(), LLVMInsertExistingBasicBlockAfterInsertBlock(), LLVMMDNodeInContext(), LLVMOrcCreateDumpObjects(), LLVMOrcCreateDynamicLibrarySearchGeneratorForPath(), LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess(), LLVMOrcCreateLLJIT(), LLVMOrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks(), LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager(), LLVMOrcCreateStaticLibrarySearchGeneratorForPath(), LLVMOrcExecutionSessionLookup(), LLVMOrcJITTargetMachineBuilderDetectHost(), LLVMOrcLLJITLookup(), LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener(), loadBinaryFormat(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::AMDGPUTargetLowering::loadInputValue(), llvm::LoadInst::LoadInst(), llvm::LoadIntFromMemory(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::M68kInstrInfo::loadRegFromStackSlot(), llvm::X86InstrInfo::loadRegFromStackSlot(), llvm::MemorySSA::locallyDominates(), llvm::DbgVariableIntrinsic::location_ops(), LiveDebugValues::MLocTracker::locIDToSpill(), LiveDebugValues::MLocTracker::locIDToSpillIdx(), LiveDebugValues::LocIdx::LocIdx(), llvm::sys::SmartRWMutex< true >::lock(), llvm::FileError::log(), lookForCompound(), llvm::TargetRegisterInfo::lookThruCopyLike(), llvm::TargetRegisterInfo::lookThruSingleUseCopyChain(), llvm::BitTracker::lookup(), llvm::sys::DynamicLibrary::HandleSet::Lookup(), llvm::gsym::GsymReader::lookup(), llvm::AppleAcceleratorTable::Entry::lookup(), llvm::GVNPass::ValueTable::lookup(), llvm::DWARFDebugNames::Entry::lookup(), llvm::BlockAddress::lookup(), llvm::orc::ExecutionSession::lookup(), lookupFoldTableImpl(), llvm::orc::Platform::lookupInitSymbols(), llvm::Function::lookupIntrinsicID(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), LookupNEONLdSt(), llvm::lookupOrParseBuiltinImageType(), lookupRelaxTableImpl(), lowBitMask(), llvm::SPIRVMCInstLower::lower(), llvm::WebAssemblyMCInstLower::lower(), llvm::M68kMCInstLower::Lower(), llvm::LegalizerHelper::lower(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), lower512BitShuffle(), LowerABS(), llvm::PPCRegisterInfo::lowerACCRestore(), LowerADDRSPACECAST(), LowerADDSAT_SUBSAT(), lowerAddSub(), lowerAddSubToHorizontalOp(), LowerAndToBT(), LowerANY_EXTEND(), llvm::FastISel::lowerArguments(), llvm::InlineAsmLowering::lowerAsmOperandForConstraint(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerATOMIC_FENCE(), lowerAtomicArith(), llvm::TargetLowering::lowerAtomicLoadAsLoadSDNode(), llvm::TargetLowering::lowerAtomicStoreAsStoreSDNode(), LowerAVXCONCAT_VECTORS(), LowerAVXExtend(), llvm::HexagonTargetLowering::LowerBITCAST(), LowerBITCAST(), llvm::LegalizerHelper::lowerBitCount(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), LowerBR_CC(), LowerBSWAP(), lowerBUILD_VECTOR(), LowerBUILD_VECTOR_i1(), LowerBUILD_VECTORvXi1(), lowerBuildVectorAsBroadcast(), LowerBuildVectorAsInsert(), LowerBuildVectorOfFPExt(), LowerBuildVectorOfFPTrunc(), LowerBuildVectorv4x32(), llvm::SPIRV::lowerBuiltin(), llvm::SPIRV::lowerBuiltinType(), llvm::SPIRVCallLowering::lowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::VETargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::CallLowering::lowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallFromStatepointLoweringInfo(), lowerCallResult(), LowerCallResult(), LowerCallResults(), llvm::FastISel::lowerCallTo(), LowerCMP_SWAP(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS_i1(), LowerCONCAT_VECTORSvXi1(), lowerConstant(), llvm::HexagonTargetLowering::LowerConstantPool(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), LowerCTPOP(), LowerCTTZ(), llvm::VETargetLowering::LowerCustomJumpTableEntry(), llvm::RISCVTargetLowering::LowerCustomJumpTableEntry(), llvm::X86TargetLowering::LowerCustomJumpTableEntry(), llvm::TargetLoweringObjectFileELF::lowerDSOLocalEquivalent(), lowerDSPIntr(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), LowerEXTEND_VECTOR_INREG(), LowerEXTRACT_SUBVECTOR(), llvm::VETargetLowering::lowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_i1(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerF128Load(), LowerF128Store(), LowerF64Op(), LowerFABSorFNEG(), LowerFCOPYSIGN(), LowerFGETSIGN(), LowerFNEGorFABS(), llvm::SPIRVCallLowering::lowerFormalArguments(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), LowerFP16_TO_FP(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), LowerFP_TO_FP16(), llvm::AMDGPUTargetLowering::LowerFP_TO_INT64(), lowerFP_TO_INT_SAT(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), llvm::AMDGPUTargetLowering::LowerFRINT(), LowerFSINCOS(), llvm::AMDGPUTargetLowering::LowerFTRUNC(), LowerFunnelShift(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerHorizontalByteSum(), LowerI64IntToFP16(), LowerI64IntToFP_AVX512DQ(), lowerIncomingStatepointValue(), llvm::InlineAsmLowering::lowerInlineAsm(), LowerINSERT_SUBVECTOR(), llvm::VETargetLowering::lowerINSERT_VECTOR_ELT(), LowerINSERT_VECTOR_ELT_i1(), lowerINT_TO_FP_vXi64(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), LowerINTRINSIC_W_CHAIN(), llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerIntrinsicToFunction(), LowerIntVSETCC_AVX512(), llvm::SelectionDAGBuilder::lowerInvokable(), LowerLargeShift(), lowerLLVMIntrinsicName(), llvm::LegalizerHelper::lowerLoad(), llvm::MipsTargetLowering::lowerLOAD(), LowerLoad(), lowerLoadF128(), lowerLoadI1(), llvm::LegalizerHelper::lowerMemCpyFamily(), llvm::LegalizerHelper::lowerMemcpyInline(), LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), LowerMSTORE(), LowerMUL(), LowerMULH(), LowerNegateToMultiply(), lowerObjCCall(), llvm::lowerObjectSizeCall(), llvm::PPCRegisterInfo::lowerOctWordSpilling(), llvm::ARMAsmPrinter::lowerOperand(), llvm::R600TargetLowering::LowerOperation(), llvm::ARCTargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::RISCVTargetLowering::LowerOperation(), llvm::AArch64TargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperationWrapper(), llvm::TargetLowering::LowerOperationWrapper(), llvm::LowerPPCMachineOperandToMCOperand(), LowerPredicateLoad(), LowerPredicateStore(), LowerPREFETCH(), llvm::PPCRegisterInfo::lowerPrepareProbedAlloca(), llvm::PPCRegisterInfo::lowerQuadwordRestore(), lowerRegToMasks(), llvm::X86CallLowering::lowerReturn(), llvm::AArch64CallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::CallLowering::lowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerReverse_VECTOR_SHUFFLE(), lowerRISCVVMachineInstrToMCInst(), LowerRotate(), LowerSCALAR_TO_VECTOR(), lowerScalarSplat(), LowerSDIV(), LowerSELECT_CC(), llvm::HexagonTargetLowering::LowerSETCC(), LowerSETCCCARRY(), LowerShift(), LowerShiftByScalarImmediate(), llvm::MSP430TargetLowering::LowerShifts(), llvm::LanaiTargetLowering::LowerSHL_PARTS(), llvm::LegalizerHelper::lowerShlSat(), lowerShuffleAsBitBlend(), lowerShuffleAsBlend(), lowerShuffleAsBlendAndPermute(), lowerShuffleAsBlendOfPSHUFBs(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsDecomposedShuffleMerge(), lowerShuffleAsElementInsertion(), lowerShuffleAsInsertPS(), lowerShuffleAsLanePermuteAndRepeatedMask(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsLanePermuteAndSHUFP(), lowerShuffleAsPermuteAndUnpack(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsShift(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleAsSplitOrBlend(), lowerShuffleAsTruncBroadcast(), lowerShuffleAsUNPCKAndPermute(), lowerShuffleAsVALIGN(), lowerShuffleAsVTRUNC(), lowerShuffleAsVTRUNCAndUnpack(), lowerShuffleAsZeroOrAnyExtend(), lowerShuffleOfExtractsAsVperm(), lowerShufflePairAsUNPCKAndPermute(), lowerShuffleToEXPAND(), llvm::LegalizerHelper::lowerShuffleVector(), lowerShuffleWithPACK(), lowerShuffleWithPSHUFB(), lowerShuffleWithSHUFPD(), lowerShuffleWithUndefHalf(), lowerShuffleWithVPMOV(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), LowerSIGN_EXTEND(), llvm::AMDGPUTargetLowering::LowerSIGN_EXTEND_INREG(), LowerSIGN_EXTEND_Mask(), llvm::AMDGPUTargetLowering::LowerSINT_TO_FP(), LowerSINT_TO_FP(), llvm::SelectionDAGBuilder::LowerStatepoint(), lowerStatepointMetaArgs(), llvm::VETargetLowering::lowerSTORE(), LowerSTORE(), LowerStore(), lowerStoreF128(), lowerStoreI1(), LowerSVEIntrinsicEXT(), llvm::AArch64MCInstLower::LowerSymbolOperand(), llvm::AArch64MCInstLower::lowerSymbolOperandCOFF(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), llvm::AMDGPUCallLowering::lowerTailCall(), LowerToHorizontalOp(), llvm::VETargetLowering::lowerToVVP(), LowerTruncatei1(), LowerTruncateToBTST(), LowerTruncateVecI1(), LowerTruncateVectorStore(), llvm::LegalizerHelper::lowerU64ToF32BitOps(), llvm::HexagonTargetLowering::LowerUAddSubO(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), llvm::AMDGPUTargetLowering::LowerUINT_TO_FP(), LowerUINT_TO_FP(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), LowerUMULO_SMULO(), lowerUnalignedIntStore(), llvm::HexagonTargetLowering::LowerUnalignedLoad(), lowerV16F32Shuffle(), lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV32I16Shuffle(), lowerV32I8Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV4X128Shuffle(), lowerV64I8Shuffle(), lowerV8F16Shuffle(), lowerV8F32Shuffle(), lowerV8F64Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), lowerV8I64Shuffle(), llvm::HexagonTargetLowering::LowerVACOPY(), LowerVACOPY(), LowerVecReduce(), llvm::HexagonTargetLowering::LowerVECTOR_SHIFT(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_i1(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVectorAllZero(), LowerVectorCTLZ(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTPOP(), LowerVectorCTPOPInRegLUT(), lowerVectorFCMP(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), LowerVectorINT_TO_FP(), lowerVectorIntrinsicScalars(), llvm::RISCVRegisterInfo::lowerVRELOAD(), llvm::HexagonTargetLowering::LowerVSELECT(), LowerVSETCC(), llvm::RISCVRegisterInfo::lowerVSPILL(), llvm::VETargetLowering::lowerVVP_LOAD_STORE(), LowerWRITE_REGISTER(), LowerXALUO(), LowerZERO_EXTEND(), LowerZERO_EXTEND_Mask(), llvm::LSBaseSDNode::LSBaseSDNode(), llvm::KnownBits::lshr(), llvm::APInt::lshrInPlace(), llvm::MachineInstrBundleIterator< const MachineInstr >::MachineInstrBundleIterator(), llvm::MachineInstrSpan::MachineInstrSpan(), llvm::MachineMemOperand::MachineMemOperand(), llvm::msf::MSFLayout::mainFpmBlock(), llvm::jitlink::LinkGraph::makeAbsolute(), makeAllConstantUsesInstructions(), llvm::MachineFunction::makeDebugValueSubstitution(), llvm::jitlink::LinkGraph::makeDefined(), makeDstOps(), llvm::SelectionDAG::makeEquivalentMemoryOrdering(), llvm::ConstantRange::makeExactICmpRegion(), llvm::jitlink::LinkGraph::makeExternal(), llvm::makeFollowupLoopID(), llvm::ConstantRange::makeGuaranteedNoWrapRegion(), llvm::makeGuardControlFlowExplicit(), llvm::opt::InputArgList::MakeIndex(), llvm::detail::DoubleAPFloat::makeLargest(), makeMergeable(), llvm::LPAC::makePostOp(), llvm::LPAC::makePreOp(), llvm::detail::IEEEFloat::makeQuiet(), makeReducible(), llvm::rdf::DataFlowGraph::makeRegRef(), llvm::ContextAndReplaceableUses::makeReplaceable(), llvm::detail::DoubleAPFloat::makeSmallest(), llvm::detail::DoubleAPFloat::makeSmallestNormalized(), makeStatepointExplicit(), makeStatepointExplicitImpl(), llvm::orc::makeStub(), llvm::coro::LowererBase::makeSubFnCall(), makeVisible(), llvm::json::ObjectMapper::map(), mapArgRegToOffsetAIX(), llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset(), llvm::msgpack::MapDocNode::MapDocNode(), mapInputsToGVNs(), mapNameAndUniqueName(), llvm::json::ObjectMapper::mapOptional(), llvm::yaml::MappingTraits< remarks::Remark * >::mapping(), llvm::yaml::MappingTraits< ArchYAML::Archive >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary::StringEntry >::mapping(), llvm::yaml::MappingTraits< ArchYAML::Archive::Child >::mapping(), llvm::yaml::MappingTraits< OffloadYAML::Binary::Member >::mapping(), llvm::yaml::MappingTraits< RemarkLocation >::mapping(), llvm::yaml::MappingTraits< Argument >::mapping(), llvm::yaml::MappingTraits< std::unique_ptr< XCOFFYAML::AuxSymbolEnt > >::mapping(), llvm::yaml::MappingTraits< ExportSection >::mapping(), llvm::yaml::MappingTraits< UndefinedSection >::mapping(), llvm::yaml::MappingTraits< const InterfaceFile * >::mapping(), llvm::yaml::MappingTraits< ELFYAML::FileHeader >::mapping(), llvm::yaml::MappingTraits< ELFYAML::StackSizeEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::BBAddrMapEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::BBAddrMapEntry::BBEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::GnuHashHeader >::mapping(), llvm::yaml::MappingTraits< ELFYAML::DynamicEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::NoteEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::VerdefEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::VerneedEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::VernauxEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::LinkerOption >::mapping(), llvm::yaml::MappingTraits< ELFYAML::CallGraphEntryWeight >::mapping(), llvm::yaml::MappingTraits< ELFYAML::Relocation >::mapping(), llvm::yaml::MappingTraits< ELFYAML::ARMIndexTableEntry >::mapping(), llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping(), llvm::yaml::MappingTraits< ELFYAML::Object >::mapping(), llvm::VPLane::mapToCacheIndex(), llvm::IRSimilarity::IRInstructionMapper::mapToLegalUnsigned(), mapWasmLandingPadIndex(), llvm::SCCPInstVisitor::markArgInFuncSpecialization(), llvm::MachineFrameInfo::markAsStatepointSpillSlotObjectIndex(), llvm::ValueLatticeElement::markConstant(), llvm::ValueLatticeElement::markConstantRange(), llvm::SampleContextTracker::markContextSamplesInlined(), markCoroutineAsDone(), llvm::GenericUniformityAnalysisImpl< ContextT >::markDefsDivergent(), llvm::DivergenceAnalysisImpl::markDivergent(), llvm::Attributor::markLiveInternalFunction(), llvm::LPPassManager::markLoopAsDeleted(), llvm::LPMUpdater::markLoopAsDeleted(), llvm::ValueLatticeElement::markNotConstant(), markRegisterParameterAttributes(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::markSectionStart(), llvm::mca::ResourceState::markSubResourceAsUsed(), llvm::ValueLatticeElement::markUndef(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::BitTracker::MachineEvaluator::mask(), llvm::MaskedGatherScatterSDNode::MaskedGatherScatterSDNode(), llvm::MaskedLoadStoreSDNode::MaskedLoadStoreSDNode(), llvm::SCEVWrapPredicate::maskFlags(), llvm::maskIsAllOneOrUndef(), llvm::maskIsAllZeroOrUndef(), llvm::DwarfExpression::maskSubRegister(), llvm::maskTrailingOnes(), llvm::Regex::match(), llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal >::match(), llvm::PatternMatch::LogicalOp_match< LHS, RHS, Opcode, Commutable >::match(), matchAArch64MulConstCombine(), matchAccessTags(), llvm::CombinerHelper::matchAddEToAddO(), llvm::CombinerHelper::matchAddOBy0(), llvm::CombinerHelper::matchAddSubSameReg(), matchAdjustICmpImmAndPred(), llvm::MCInstPrinter::matchAliasPatterns(), llvm::CombinerHelper::matchAndOrDisjointMask(), llvm::CombinerHelper::matchAshrShlToSextInreg(), matchBinaryPermuteShuffle(), llvm::CombinerHelper::matchBitfieldExtractFromAnd(), llvm::CombinerHelper::matchBitfieldExtractFromSExtInReg(), llvm::CombinerHelper::matchBitfieldExtractFromShr(), llvm::CombinerHelper::matchBitfieldExtractFromShrAnd(), matchBSwapHWordOrAndAnd(), matchBuildVectorToDup(), AMDGPUPreLegalizerCombinerHelper::matchClampI64ToI16(), llvm::CombinerHelper::matchCombineAddP2IToPtrAdd(), llvm::CombinerHelper::matchCombineAnyExtTrunc(), llvm::CombinerHelper::matchCombineConcatVectors(), llvm::CombinerHelper::matchCombineExtOfExt(), llvm::CombinerHelper::matchCombineFAbsOfFNeg(), llvm::CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), llvm::CombinerHelper::matchCombineFSubFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA(), llvm::CombinerHelper::matchCombineI2PToP2I(), llvm::CombinerHelper::matchCombineInsertVecElts(), llvm::CombinerHelper::matchCombineLoadWithAndMask(), llvm::CombinerHelper::matchCombineMulToShl(), llvm::CombinerHelper::matchCombineShiftToUnmerge(), llvm::CombinerHelper::matchCombineShlOfExtend(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::CombinerHelper::matchCombineTruncOfExt(), llvm::CombinerHelper::matchCombineTruncOfShift(), llvm::CombinerHelper::matchCombineUnmergeMergeToPlainValues(), llvm::CombinerHelper::matchCombineUnmergeWithDeadLanesToTrunc(), llvm::CombinerHelper::matchCombineUnmergeZExtToZExt(), llvm::CombinerHelper::matchCombineZextTrunc(), matchDeMorgansLaws(), matchDup(), matchDupFromBuildVector(), matchDupLane(), matchEXT(), llvm::CombinerHelper::matchExtendThroughPhis(), llvm::CombinerHelper::matchExtractAllEltsFromBuildVector(), llvm::CombinerHelper::matchExtractVecEltBuildVec(), matchFConstantToConstant(), llvm::fuzzerop::matchFirstType(), matchFoldGlobalOffset(), matchFormTruncstore(), llvm::CombinerHelper::matchFsubToFneg(), matchFunnelShift(), llvm::CombinerHelper::matchFunnelShiftToRotate(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), matchICmpRedundantTrunc(), llvm::CombinerHelper::matchICmpToLHSKnownBits(), llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), MatchingStackOffset(), matchINS(), llvm::CombinerHelper::matchInsertExtractVecEltOutOfBounds(), matchIntrinsicType(), matchLoadAndBytePosition(), AMDGPUDAGToDAGISel::matchLoadD16FromBuildVector(), llvm::CombinerHelper::matchLoadOrCombine(), matchMinMaxOfMinMax(), llvm::CombinerHelper::matchMulOBy0(), llvm::CombinerHelper::matchMulOBy2(), matchMutateAnyExtToZExt(), llvm::CombinerHelper::matchNarrowBinopFeedingAnd(), llvm::CombinerHelper::matchNotCmp(), llvm::CombinerHelper::matchOptBrCondByInvertingCond(), matchOrConcat(), llvm::CombinerHelper::matchOrShiftToFunnelShift(), llvm::CombinerHelper::matchOverlappingAnd(), matchPMADDWD(), matchPMADDWD_2(), llvm::CombinerHelper::matchPtrAddZero(), llvm::CombinerHelper::matchRedundantAnd(), llvm::CombinerHelper::matchRedundantBinOpInEquality(), llvm::CombinerHelper::matchRedundantNegOperands(), llvm::CombinerHelper::matchRedundantOr(), matchRegisterNameHelper(), matchREV(), llvm::CombinerHelper::matchRotateOutOfRange(), llvm::fuzzerop::matchScalarOfFirstType(), matchScalarReduction(), llvm::ScaledNumbers::matchScales(), llvm::CombinerHelper::matchSDivByConst(), llvm::CombinerHelper::matchSelectSameVal(), llvm::CombinerHelper::matchSextInRegOfLoad(), llvm::CombinerHelper::matchSextTruncSextLoad(), llvm::CombinerHelper::matchShiftImmedChain(), llvm::CombinerHelper::matchShiftOfShiftedLogic(), matchShuffleAsBitRotate(), matchShuffleAsBlend(), matchShuffleAsElementRotate(), matchShuffleAsEXTRQ(), matchShuffleAsInsertPS(), matchShuffleAsINSERTQ(), matchShuffleWithPACK(), matchShuffleWithSHUFPD(), matchShuffleWithUNPCK(), llvm::CombinerHelper::matchSimplifySelectToMinMax(), llvm::CombinerHelper::matchSubAddSameReg(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), matchTRN(), llvm::CombinerHelper::matchTruncStoreMerge(), AMDGPUPostLegalizerCombinerHelper::matchUCharToFloat(), llvm::CombinerHelper::matchUDivByConst(), llvm::CombinerHelper::matchUMulHToLShr(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), llvm::CombinerHelper::matchUndefSelectCmp(), llvm::CombinerHelper::matchUndefShuffleVectorMask(), llvm::CombinerHelper::matchUndefStore(), matchUZP(), matchVAshrLshrImm(), MatchVectorAllZeroTest(), matchVectorSextInReg(), llvm::CombinerHelper::matchXorOfAndWithSameReg(), matchZeroExtendFromS32(), matchZip(), llvm::gvn::AvailableValue::MaterializeAdjustedValue(), llvm::PPCInstrInfo::materializeImmPostRA(), llvm::MachineIRBuilder::materializePtrAdd(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), llvm::maxIntN(), llvm::maxUIntN(), mayBeAccessToSubobjectOf(), llvm::MaybeAlign::MaybeAlign(), maybeFreeRetconStorage(), maybeLexRegister(), maybeUpdateTerminator(), llvm::X86::mayFoldLoadIntoBroadcastFromMem(), llvm::VPRecipeBase::mayHaveSideEffects(), mayLoadFromGOTOrConstantPool(), llvm::VPRecipeBase::mayReadFromMemory(), llvm::WebAssembly::mayThrow(), mayUseP9Setb(), llvm::VPRecipeBase::mayWriteToMemory(), llvm::RegBankSelect::MBBInsertPoint::MBBInsertPoint(), mccase(), llvm::MCExpr::MCExpr(), mcinvert(), llvm::MCLOHDirective::MCLOHDirective(), llvm::MCPseudoProbe::MCPseudoProbe(), llvm::MCRegUnitIterator::MCRegUnitIterator(), llvm::MCRegUnitRootIterator::MCRegUnitRootIterator(), llvm::BitTracker::RegisterCell::meet(), MemOperandsHaveAlias(), llvm::object::MinidumpFile::MemoryInfoIterator::MemoryInfoIterator(), llvm::LoopVectorizationCostModel::memoryInstructionCanBeWidened(), memoryIsNotModifiedBetween(), llvm::MemorySSA::MemorySSA(), llvm::MemSDNode::MemSDNode(), memVTFromLoadIntrData(), memVTFromLoadIntrReturn(), llvm::HexagonBlockRanges::IndexRange::merge(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::MergeBlockSuccessorsIntoGivenBlocks(), llvm::MDBuilder::mergeCallbackEncodings(), MergeCompatibleInvokesImpl(), mergeConditionalStoreToAddress(), llvm::Instruction::mergeDIAssignID(), mergeEltWithShuffle(), llvm::ValueLatticeElement::mergeIn(), llvm::DDGBuilder::mergeNodes(), mergeOperations(), llvm::VPlanTransforms::mergeReplicateRegionsIntoSuccessors(), llvm::AliasSet::mergeSetIn(), llvm::X86FrameLowering::mergeSPUpdates(), llvm::M68kFrameLowering::mergeSPUpdates(), llvm::Constant::mergeUndefsWith(), llvm::LiveRange::MergeValueNumberInto(), mergeVectorRegsToResultRegs(), llvm::remarks::YAMLStrTabRemarkSerializer::metaSerializer(), llvm::remarks::BitstreamRemarkSerializer::metaSerializer(), llvm::MIBundleBuilder::MIBundleBuilder(), MIIsInTerminatorSequence(), llvm::AArch64FunctionInfo::MILOHDirective::MILOHDirective(), llvm::PBQP::Vector::minIndex(), llvm::minIntN(), llvm::MipsLegalizerInfo::MipsLegalizerInfo(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsSubtarget::MipsSubtarget(), llvm::MIRAddFSDiscriminators::MIRAddFSDiscriminators(), llvm::MIRProfileLoaderPass::MIRProfileLoaderPass(), llvm::MLInlineAdvisor::MLInlineAdvisor(), llvm::MLModelRunner::MLModelRunner(), LiveDebugValues::MLocTracker::MLocTracker(), llvm::MLPriorityAdvisor::MLPriorityAdvisor(), llvm::detail::IEEEFloat::mod(), llvm::detail::DoubleAPFloat::mod(), llvm::APFloat::mod(), llvm::MCSymbol::modifyFlags(), modRMByte(), llvm::LegalizerHelper::moreElementsVectorPhi(), moreEltsToNext32Bit(), llvm::ConstantDataArraySlice::move(), moveAddAfterMinMax(), llvm::MemorySSAUpdater::moveAllAfterMergeBlocks(), llvm::MemorySSAUpdater::moveAllAfterSpliceBlocks(), llvm::ARMBlockPlacement::moveBasicBlock(), llvm::Instruction::moveBefore(), moveBelowOrigChain(), llvm::MachineFunction::moveCallSiteInfo(), llvm::SIInstrInfo::moveFlatAddrToVGPR(), llvm::DenseMapBase< DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >::moveFromOldBuckets(), llvm::orc::moveFunctionBody(), llvm::orc::moveGlobalVariableInitializer(), moveInstrOut(), moveLCSSAPhis(), llvm::IntervalMapImpl::NodeBase< std::pair< IndexT, IndexT >, char, N >::moveLeft(), llvm::IntervalMapImpl::Path::moveLeft(), llvm::LoopInfo::movementPreservesLCSSAForm(), llvm::object::ExportEntry::moveNext(), llvm::object::MachOChainedFixupEntry::moveNext(), moveOperands(), llvm::MachineRegisterInfo::moveOperands(), llvm::IntervalMapImpl::NodeBase< std::pair< IndexT, IndexT >, char, N >::moveRight(), llvm::IntervalMapImpl::Path::moveRight(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::MemorySSA::moveTo(), llvm::LoopBase< BasicBlock, Loop >::moveToHeader(), llvm::mca::Stage::moveToTheNextStage(), llvm::SIInstrInfo::moveToVALU(), MoveVPNOTBeforeFirstUser(), llvm::LoongArchInstrInfo::movImm(), llvm::RISCVInstrInfo::movImm(), MSA2OpIntrinsicToGeneric(), MSA3OpIntrinsicToGeneric(), llvm::APFixedPoint::mul(), llvm::KnownBits::mul(), llvm::KnownBits::mulhs(), llvm::KnownBits::mulhu(), multiLetterExtensionRank(), llvm::APInt::multiplicativeInverse(), llvm::detail::DoubleAPFloat::multiply(), llvm::APFloat::multiply(), mustBeUnreachableFunction(), llvm::InstDeleterIRStrategy::mutate(), llvm::InsertCFGStrategy::mutate(), llvm::DIType::mutate(), narrowExtractedVectorBinOp(), narrowExtractedVectorLoad(), narrowExtractedVectorSelect(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarBasic(), narrowSDivOrSRem(), llvm::narrowShuffleMaskElts(), llvm::LegacyLegalizerInfo::narrowToSmallerAndWidenToSmallest(), narrowUDivOrURem(), llvm::sys::path::native(), llvm::pdb::NativeTypePointer::NativeTypePointer(), needCarryOrOverflowFlag(), llvm::X86_MC::needsAddressSizeOverride(), llvm::RISCVRegisterInfo::needsFrameBaseReg(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), needsLFTR(), llvm::remarks::RemarkStreamer::needsSection(), needStackSlotPassParameters(), negateFMAOpcode(), negateICmpIfUsedByBranchOrSelectOnly(), llvm::RandomIRBuilder::newSource(), llvm::ScheduleDAGSDNodes::newSUnit(), llvm::ScheduleDAGInstrs::newSUnit(), llvm::detail::IEEEFloat::next(), llvm::detail::DoubleAPFloat::next(), llvm::symbolize::MarkupParser::nextNode(), NextPossibleSolution(), nextRealType(), llvm::rdf::NodeAllocator::NodeAllocator(), llvm::IntervalMapImpl::NodeRef::NodeRef(), llvm::HexagonInstrInfo::nonDbgBundleSize(), nonnewline(), llvm::nonStrictlyPostDominate(), llvm::Triple::normalize(), llvm::BlockFrequencyInfoImplBase::Distribution::normalize(), NormalizeBuildVector(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4(), normalizeForInvokeSafepoint(), llvm::cflaa::StratifiedSetsBuilder< T >::noteAttributes(), llvm::DAGTypeLegalizer::NoteDeletion(), llvm::orc::EHFrameRegistrationPlugin::notifyEmitted(), llvm::mca::WriteRef::notifyExecuted(), llvm::mca::ExecuteStage::notifyInstructionIssued(), llvm::orc::DebugObjectManagerPlugin::notifyMaterializing(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState(), llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >::numCombinations(), llvm::pdb::InputFile::obj(), llvm::json::OStream::objectEnd(), llvm::json::ObjectKey::ObjectKey(), llvm::CriticalAntiDepBreaker::Observe(), llvm::AggressiveAntiDepBreaker::Observe(), llvm::DotCfgChangeReporter::omitAfter(), llvm::OnDiskChainedHashTable< Info >::OnDiskChainedHashTable(), llvm::MachineBlockFrequencyInfo::onEdgeSplit(), oneUseDominatesOtherUses(), llvm::mca::MemoryGroup::onGroupExecuted(), llvm::mca::MemoryGroup::onGroupIssued(), llvm::mca::RetireControlUnit::onInstructionExecuted(), llvm::mca::MemoryGroup::onInstructionExecuted(), llvm::mca::RegisterFile::onInstructionExecuted(), llvm::mca::LSUnitBase::onInstructionExecuted(), llvm::mca::MemoryGroup::onInstructionIssued(), llvm::mca::WriteState::onInstructionIssued(), llvm::mca::LSUnitBase::onInstructionRetired(), llvm::VPUser::onlyFirstLaneUsed(), llvm::VPInstruction::onlyFirstLaneUsed(), llvm::VPBlendRecipe::onlyFirstLaneUsed(), llvm::VPInterleaveRecipe::onlyFirstLaneUsed(), llvm::VPReplicateRecipe::onlyFirstLaneUsed(), llvm::VPWidenMemoryInstructionRecipe::onlyFirstLaneUsed(), llvm::VPCanonicalIVPHIRecipe::onlyFirstLaneUsed(), llvm::VPDerivedIVRecipe::onlyFirstLaneUsed(), llvm::VPScalarIVStepsRecipe::onlyFirstLaneUsed(), llvm::PPCInstrInfo::onlyFoldImmediate(), onlyZeroFlagUsed(), llvm::MLInlineAdvisor::onPassEntry(), llvm::MLInlineAdvisor::onPassExit(), llvm::MLInlineAdvisor::onSuccessfulInlining(), llvm::GVNExpression::BasicExpression::op_push_back(), llvm::logicalview::LVSplitContext::open(), llvm::OpenMPIRBuilderConfig::openMPOffloadMandatory(), llvm::RegisterBankInfo::OperandsMapper::OperandsMapper(), llvm::orc::ThreadSafeModule::operator bool(), llvm::BitTracker::BitValue::operator bool(), llvm::GlobalVariable::operator delete(), llvm::User::operator delete(), llvm::mca::ResourceCycles::operator double(), operator new(), llvm::StringSwitch< T, R >::operator R(), llvm::TypeSwitch< T, ResultT >::operator ResultT(), llvm::HexagonBlockRanges::IndexType::operator unsigned(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator ValueT *(), llvm::const_set_bits_iterator_impl< BitVectorT >::operator!=(), llvm::operator!=(), llvm::APSInt::operator%(), llvm::APSInt::operator%=(), llvm::APSInt::operator&(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::operator&=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::operator&=(), llvm::APSInt::operator&=(), llvm::APInt::operator&=(), llvm::AAPointerInfo::Access::operator&=(), llvm::SystemZTargetStreamer::CmpMCInst::operator()(), llvm::orc::BlockFreqQuery::operator()(), llvm::ValueDFS_Compare::operator()(), llvm::CodeGenPassBuilder< DerivedT >::AddIRPass::operator()(), llvm::LessRecordRegister::operator()(), llvm::deref< T >::operator()(), llvm::AllocationOrder::Iterator::operator*(), llvm::pdb::HashTableIterator< ValueT >::operator*(), llvm::PredIterator< Ptr, USE_iterator >::operator*(), llvm::orc::CtorDtorIterator::operator*(), llvm::ValueHandleBase::operator*(), llvm::object::MinidumpFile::MemoryInfoIterator::operator*(), llvm::memprof::CallStack< NodeT, IteratorT >::CallStackIterator::operator*(), llvm::ScopedHashTableIterator< K, V, KInfo >::operator*(), llvm::scc_iterator< GraphT, GT >::operator*(), llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator*(), llvm::ilist_iterator< OptionsT, IsReverse, IsConst >::operator*(), llvm::pdb::SymbolGroupIterator::operator*(), llvm::operator*(), llvm::SampleContextTracker::Iterator::operator*(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator*(), llvm::VarStreamArrayIterator< ValueType, Extractor >::operator*(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::operator*(), llvm::AliasSet::iterator::operator*(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator*(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator*(), llvm::SmallPtrSetIterator< PtrTy >::operator*(), llvm::APSInt::operator*(), llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator*(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator*(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator*(), llvm::filter_iterator_base< WrappedIteratorT, PredicateT, std::bidirectional_iterator_tag >::operator*(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator*(), llvm::object::Elf_Note_Iterator_Impl< ELFT >::operator*(), llvm::TargetRegistry::iterator::operator*(), llvm::SDNode::use_iterator::operator*(), llvm::APInt::operator*(), llvm::MCRegAliasIterator::operator*(), llvm::jitlink::LinkGraph::nested_collection_iterator< OuterItrT, InnerItrT, T, getInnerRange >::operator*(), llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator*(), llvm::memoryaccess_def_iterator_base< MemoryAccess >::operator*(), llvm::MachineRegisterInfo::defusechain_instr_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator*(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator*(), llvm::upward_defs_iterator::operator*(), llvm::BranchProbability::operator*=(), llvm::APSInt::operator*=(), llvm::PBQP::Matrix::operator+(), llvm::APSInt::operator+(), llvm::HexagonBlockRanges::IndexType::operator++(), llvm::PredIterator< Ptr, USE_iterator >::operator++(), llvm::sys::path::const_iterator::operator++(), llvm::orc::StaticInitGVIterator::operator++(), llvm::fallible_iterator< Underlying >::operator++(), llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator++(), llvm::MIBundleOperandIteratorBase< const MachineOperand >::operator++(), llvm::ScopedHashTableIterator< K, V, KInfo >::operator++(), llvm::pdb::SymbolGroupIterator::operator++(), llvm::SampleContextTracker::Iterator::operator++(), llvm::AliasSet::iterator::operator++(), llvm::MCRegisterInfo::mc_difflist_iterator< mc_subreg_iterator >::operator++(), llvm::SmallPtrSetIterator< PtrTy >::operator++(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator++(), llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator++(), llvm::BasicBlock::phi_iterator_impl< PHINodeT, BBIteratorT >::operator++(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator++(), llvm::coverage::FunctionRecordIterator::operator++(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator++(), llvm::yaml::document_iterator::operator++(), llvm::early_inc_iterator_impl< WrappedIteratorT >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::object::Elf_Note_Iterator_Impl< ELFT >::operator++(), llvm::TargetRegistry::iterator::operator++(), llvm::SDNode::use_iterator::operator++(), llvm::MCRegUnitRootIterator::operator++(), llvm::MCRegAliasIterator::operator++(), llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator++(), llvm::memoryaccess_def_iterator_base< MemoryAccess >::operator++(), llvm::MachineRegisterInfo::defusechain_instr_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator++(), llvm::SuperRegClassIterator::operator++(), llvm::upward_defs_iterator::operator++(), llvm::PSetIterator::operator++(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator++(), llvm::BitMaskClassIterator::operator++(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++(), llvm::detail::enumerator_iter< R >::operator++(), llvm::pdb::DbiModuleSourceFilesIterator::operator+=(), llvm::PBQP::Vector::operator+=(), llvm::BranchProbability::operator+=(), llvm::PBQP::Matrix::operator+=(), llvm::SuccIterator< InstructionT, BlockT >::operator+=(), llvm::APSInt::operator+=(), llvm::APInt::operator+=(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::operator+=(), llvm::pdb::DbiModuleSourceFilesIterator::operator-(), llvm::SuccIterator< InstructionT, BlockT >::operator-(), llvm::APSInt::operator-(), llvm::FixedStreamArrayIterator< PSHashRecord >::operator-(), llvm::indexed_accessor_iterator< iterator, BaseT, T, PointerT, ReferenceT >::operator-(), llvm::SDNodeIterator::operator-(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::operator-(), llvm::fallible_iterator< Underlying >::operator--(), llvm::ARM::operator--(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator--(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator--(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::pdb::DbiModuleSourceFilesIterator::operator-=(), llvm::BranchProbability::operator-=(), llvm::codeview::TypeIndex::operator-=(), llvm::APSInt::operator-=(), llvm::FixedStreamArrayIterator< PSHashRecord >::operator-=(), llvm::APInt::operator-=(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::operator-=(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator->(), llvm::filter_iterator_base< WrappedIteratorT, PredicateT, std::bidirectional_iterator_tag >::operator->(), llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug, ByOperand, ByInstr, ByBundle >::operator->(), llvm::DenseMapIterator< KeyT, ValueT, KeyInfoT, Bucket, IsConst >::operator->(), llvm::APSInt::operator/(), llvm::BranchProbability::operator/=(), llvm::APSInt::operator/=(), llvm::pdb::DbiModuleSourceFilesIterator::operator<(), llvm::opt::operator<(), llvm::AttributeImpl::operator<(), llvm::ValID::operator<(), llvm::object::SectionRef::operator<(), llvm::RetainedKnowledge::operator<(), llvm::APSInt::operator<(), llvm::BranchProbability::operator<(), llvm::SuccIterator< InstructionT, BlockT >::operator<(), llvm::operator<(), llvm::FixedStreamArrayIterator< PSHashRecord >::operator<(), llvm::indexed_accessor_iterator< iterator, BaseT, T, PointerT, ReferenceT >::operator<(), llvm::SwitchInst::CaseIteratorImpl< CaseHandleT >::operator<(), llvm::sys::operator<<(), llvm::PBQP::operator<<(), llvm::orc::operator<<(), llvm::raw_ostream::operator<<(), llvm::operator<<(), llvm::BitVector::operator<<=(), llvm::APInt::operator<<=(), llvm::APSInt::operator<=(), llvm::BranchProbability::operator<=(), llvm::PointerEmbeddedInt< IntT, Bits >::operator=(), llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc::operator=(), llvm::Timer::operator=(), llvm::APInt::operator=(), llvm::pdb::DbiModuleSourceFilesIterator::operator==(), llvm::PBQP::Vector::operator==(), llvm::const_set_bits_iterator_impl< BitVectorT >::operator==(), llvm::AllocationOrder::Iterator::operator==(), llvm::orc::CtorDtorIterator::operator==(), llvm::RegisterBank::operator==(), llvm::RNSuccIterator< NodeRef, BlockT, RegionT >::operator==(), llvm::PBQP::Matrix::operator==(), llvm::object::MachORebaseEntry::operator==(), llvm::APSInt::operator==(), llvm::VarStreamArrayIterator< ValueType, Extractor >::operator==(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator==(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::operator==(), llvm::object::Archive::Child::operator==(), llvm::rdf::RegisterAggr::rr_iterator::operator==(), llvm::object::MachOBindEntry::operator==(), llvm::operator==(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::iterator_base< SMSPtrTy >::operator==(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator==(), llvm::FixedStreamArrayIterator< PSHashRecord >::operator==(), llvm::rdf::NodeAddr< llvm::rdf::FuncNode * >::operator==(), llvm::yaml::basic_collection_iterator< BaseT, ValueT >::operator==(), llvm::IntervalMapImpl::NodeRef::operator==(), LiveDebugValues::MLocTracker::MLocIterator::operator==(), AllocaSlices::partition_iterator::operator==(), llvm::APInt::operator==(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator==(), llvm::SwitchInst::CaseHandleImpl< SwitchInst, ConstantInt, BasicBlock >::operator==(), llvm::APSInt::operator>(), llvm::BranchProbability::operator>(), llvm::APSInt::operator>=(), llvm::BranchProbability::operator>=(), llvm::BlockFrequency::operator>>=(), llvm::BitVector::operator>>=(), llvm::IndexedMap< unsigned, llvm::VirtReg2IndexFunctor >::operator[](), llvm::EnumeratedArray< ValueType, Enumeration, LargestEnum, IndexType, Size >::operator[](), llvm::BitcodeReaderValueList::operator[](), llvm::PBQP::Vector::operator[](), llvm::UniqueVector< DebugVariable >::operator[](), llvm::IntEqClasses::operator[](), llvm::AddressRangesBase< AddressRangeValuePair >::operator[](), llvm::object::DataRegion< T >::operator[](), llvm::CallGraph::operator[](), llvm::SetVector< llvm::MCSection *, SmallVector< llvm::MCSection *, N >, SmallDenseSet< llvm::MCSection *, N > >::operator[](), PODSmallVector< Node *, 8 >::operator[](), llvm::PBQP::Matrix::operator[](), llvm::LiveIntervalUnion::Array::operator[](), llvm::PressureDiffs::operator[](), llvm::CallGraphNode::operator[](), llvm::TinyPtrVector< llvm::VPValue * >::operator[](), llvm::StringRef::operator[](), llvm::msgpack::MapDocNode::operator[](), llvm::ArrayRef< uint64_t >::operator[](), llvm::LazyCallGraph::EdgeSequence::operator[](), llvm::FixedStreamArray< PSHashRecord >::operator[](), llvm::SmallVectorTemplateCommon< T >::operator[](), llvm::BitTracker::RegisterCell::operator[](), llvm::dwarf::UnwindTable::operator[](), llvm::BitVector::operator[](), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::operator[](), llvm::MCRegisterInfo::operator[](), llvm::SmallBitVector::operator[](), llvm::AMDGPU::VOPD::InstInfo::operator[](), llvm::APInt::operator[](), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::operator[](), llvm::APSInt::operator^(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::operator^=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::operator^=(), llvm::APSInt::operator^=(), llvm::APInt::operator^=(), llvm::APSInt::operator|(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::operator|=(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::operator|=(), llvm::APSInt::operator|=(), llvm::APInt::operator|=(), llvm::cl::applicator< MiscFlags >::opt(), OptimizeAndOrXor(), OptimizeAwayTrappingUsesOfLoads(), llvm::LibCallSimplifier::optimizeCall(), llvm::PPCInstrInfo::optimizeCmpPostRA(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::SIInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::AArch64InstrInfo::optimizeCondBranch(), optimizeDivRem(), llvm::OptimizedStructLayoutField::OptimizedStructLayoutField(), OptimizeExtractBits(), llvm::VPlanTransforms::optimizeForVFAndUF(), llvm::jitlink::i386::optimizeGOTAndStubAccesses(), llvm::jitlink::x86_64::optimizeGOTAndStubAccesses(), llvm::X86InstrInfo::optimizeLoadInstr(), optimizeLogicalImm(), optimizeLoopExitWithUnknownExitCount(), llvm::RISCVInstrInfo::optimizeSelect(), llvm::LanaiInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::optimizeSelect(), optimizeVectorResizeWithIntegerBitCasts(), llvm::opt::Option::Option(), llvm::opt::OptTable::OptTable(), othercase(), llvm::RegionBase< RegionTraits< Function > >::outermostLoopInRegion(), outputHex(), llvm::ms_demangle::ArrayTypeNode::outputOneDimension(), llvm::ms_demangle::PointerTypeNode::outputPre(), llvm::outs(), overflowFlagToValue(), llvm::ConstantRange::overflowingBinaryOp(), llvm::InstrProfRecord::overlap(), llvm::LiveRange::overlaps(), llvm::IntervalMap< uint64_t, uint16_t, 8, IntervalMapHalfOpenInfo< uint64_t > >::overlaps(), llvm::LiveRange::overlapsFrom(), llvm::InstrProfRecord::overlapValueProfData(), p_bracket(), p_ere(), p_ere_exp(), p_simp_re(), llvm::bitfields_details::Compressor< T, Bits, bool >::pack(), llvm::bitfields_details::Compressor< T, Bits, false >::pack(), packAllocSizeArgs(), packCmovGroup(), llvm::ARM::WinEH::RuntimeFunction::PackedUnwindData(), llvm::ARM::WinEH::RuntimeFunctionARM64::PackedUnwindData(), llvm::VLIWPacketizerList::PacketizeMIs(), packImage16bitOpsToDwords(), llvm::PseudoProbeDwarfDiscriminator::packProbeData(), packSegmentMask(), llvm::HexagonMCInstrInfo::padEndloop(), llvm::CallBase::paramHasAttr(), llvm::DWARFDebugLine::Prologue::parse(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::objcopy::elf::IHexRecord::parse(), llvm::DWARFDebugLine::LineTable::parse(), ParseBFI(), parseCond(), parseCondBranch(), llvm::TargetLowering::ParseConstraints(), llvm::RISCVISAInfo::parseFeatures(), parseInt(), llvm::LLParser::parseMDField(), llvm::DWARFDebugLine::SectionParser::parseNext(), llvm::detail::HelperFunctions::parseNumericPrecision(), llvm::XCOFF::parseParmsTypeWithVecInfo(), llvm::MIRParserImpl::parseRegisterInfo(), parseRegisterNumber(), llvm::formatv_object_base::parseReplacementItem(), llvm::pdb::PDBFile::parseStreamData(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseTemplateParam(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::parseUnresolvedName(), llvm::partAsHex(), partitionShuffleOfConcats(), llvm::AMDGPUCallLowering::passSpecialInputs(), llvm::SITargetLowering::passSpecialInputs(), Passv64i1ArgInRegs(), llvm::PatchPointOpers::PatchPointOpers(), llvm::pdb::InputFile::pdb(), llvm::BinaryStreamReader::peek(), llvm::mca::IncrementalSourceMgr::peekNext(), llvm::mca::CircularSourceMgr::peekNext(), llvm::yaml::Scanner::peekNext(), llvm::MCAsmLexer::peekTok(), llvm::peelLoop(), llvm::PeelingModuloScheduleExpander::peelPrologAndEpilogs(), llvm::PeelSingleBlockLoop(), PerformADDCombineWithOperands(), performAddCSelIntoCSinc(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), performBITREVERSECombine(), performBlockTailMerging(), performBRCONDCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performConcatVectorsCombine(), performCustomAdjustments(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performExtractsShuffleAction(), performExtractVectorEltCombine(), llvm::AMDGPUTargetLowering::performFAbsCombine(), performFirstTrueTestVectorCombine(), performGatherLoadCombine(), performGLD1Combine(), PerformHWLoopCombine(), performLastTrueTestVectorCombine(), performMaskedGatherScatterCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), llvm::performOptimizedStructLayout(), performORCombine(), PerformREMCombine(), performScatterStoreCombine(), performSelectCombine(), performSetccAddFolding(), performSETCCCombine(), performSetccMergeZeroCombine(), performSignExtendInRegCombine(), performSignExtendSetCCCombine(), performSpliceCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), performSRACombine(), performSubsToAndsCombine(), performTBZCombine(), PerformTruncatingStoreCombine(), performUnpackCombine(), PerformVECREDUCE_ADDCombine(), performVectorExtendCombine(), performVectorExtendToFPCombine(), performVectorShiftCombine(), PerformVQDMULHCombine(), llvm::PGOOptions::PGOOptions(), llvm::InstCombinerImpl::PHIArgMergedDebugLoc(), PhiHasDebugValue(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::PiBlockDDGNode::PiBlockDDGNode(), llvm::GCNSchedStrategy::pickNode(), llvm::SystemZPostRASchedStrategy::pickNode(), llvm::ConvergingVLIWScheduler::pickNode(), llvm::GenericScheduler::pickNode(), llvm::PostGenericScheduler::pickNode(), llvm::GCNSchedStrategy::pickNodeBidirectional(), llvm::GenericScheduler::pickNodeBidirectional(), llvm::ConvergingVLIWScheduler::pickNodeBidrectional(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::pickOnlyChoice(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::PluginInlineAdvisorAnalysis::PluginInlineAdvisorAnalysis(), llvm::LLT::pointer(), llvm::PointerMayBeCaptured(), llvm::PointerMayBeCapturedBefore(), llvm::rdf::DataFlowGraph::DefStack::pop(), llvm::sys::fs::recursive_directory_iterator::pop(), PODSmallVector< Node *, 8 >::pop_back(), llvm::PriorityWorklist< llvm::LazyCallGraph::SCC *, SmallVector< llvm::LazyCallGraph::SCC *, N >, SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t > >::pop_back(), llvm::SetVector< llvm::MCSection *, SmallVector< llvm::MCSection *, N >, SmallDenseSet< llvm::MCSection *, N > >::pop_back(), llvm::iplist_impl< simple_ilist< llvm::AliasSet, Options... >, ilist_traits< llvm::AliasSet > >::pop_back(), llvm::BitVector::pop_back(), llvm::SmallBitVector::pop_back(), llvm::SmallVectorImpl< uint64_t >::pop_back_n(), llvm::GISelWorkList< 8 >::pop_back_val(), llvm::iplist_impl< simple_ilist< llvm::AliasSet, Options... >, ilist_traits< llvm::AliasSet > >::pop_front(), StringView::popFront(), llvm::ConstraintSystem::popLastNVariables(), llvm::TGParser::PopLocalScope(), popRegsFromStack(), AbstractManglingParser< ManglingParser< Alloc >, Alloc >::popTrailingNodeArray(), llvm::CallBase::populateBundleOperandInfos(), llvm::SelectionDAGBuilder::populateCallLoweringInfo(), populateDependencyMatrix(), populateEHOperandBundle(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), populateWorklist(), llvm::GraphDiff< NodePtr, InverseGraph >::popUpdateForIncrementalUpdates(), llvm::possiblyDemandedEltsInMask(), llvm::LazyCallGraph::postorder_ref_scc_begin(), llvm::LazyCallGraph::postorder_ref_scc_end(), llvm::powerOf5(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::HexagonInstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::TargetInstrInfo::PredicateInstruction(), predictValueUseListOrder(), llvm::ARMTTIImpl::preferPredicateOverEpilogue(), llvm::orc::SharedMemoryMapper::prepare(), llvm::SGPRSpillBuilder::prepare(), llvm::SystemZInstrInfo::prepareCompareSwapOperands(), prepareDescriptorIndirectCall(), llvm::prepareTempFiles(), llvm::VPlan::prepareToExecute(), llvm::PrepareToSplitEntryBlock(), llvm::TargetRegisterInfo::prependOffsetExpression(), llvm::DIExpression::prependOpcodes(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::X86InstrInfo::preservesZeroValueInReg(), llvm::PressureChange::PressureChange(), llvm::prettyPrintBaseTypeRef(), llvm::Align::previous(), llvm::format_object_base::print(), llvm::RegisterBank::print(), llvm::DWARFExpression::Operation::print(), llvm::BranchProbabilityInfo::print(), llvm::MIPrinter::print(), llvm::LLT::print(), llvm::MachineOperand::print(), llvm::MachineMemOperand::print(), llvm::GenericUniformityAnalysisImpl< ContextT >::print(), llvm::LiveRange::print(), llvm::LiveRangeUpdater::print(), llvm::MachineInstr::print(), llvm::ARMInstPrinter::printAddrMode2Operand(), llvm::ARMInstPrinter::printAddrMode3Operand(), llvm::AArch64InstPrinter::printAddSubImm(), llvm::AArch64InstPrinter::printAMIndexedWB(), llvm::AVRAsmPrinter::PrintAsmMemoryOperand(), llvm::ARMAsmPrinter::PrintAsmMemoryOperand(), llvm::MipsAsmPrinter::PrintAsmMemoryOperand(), llvm::AVRAsmPrinter::PrintAsmOperand(), llvm::WebAssemblyAsmPrinter::PrintAsmOperand(), llvm::LoongArchInstPrinter::printAtomicMemOp(), llvm::ARMInstPrinter::printBankedRegOperand(), llvm::AArch64InstPrinter::printBarriernXSOption(), llvm::ARMInstPrinter::printBitfieldInvMaskImmOperand(), llvm::HexagonInstPrinter::printBrtarget(), PrintByteList(), llvm::printCompactDWARFExpr(), llvm::CSKYInstPrinter::printConstpool(), printCustomRegMask(), llvm::PreservedCFGCheckerInstrumentation::CFG::printDiff(), llvm::cl::Option::printEnumValHelpStr(), printExpr(), llvm::RISCVInstPrinter::printFenceArg(), llvm::SystemZInstPrinter::printFormattedRegName(), printFormattedRegName(), llvm::CSKYInstPrinter::printFPR(), llvm::cl::Option::printHelpStr(), llvm::LanaiInstPrinter::printHi16AndImmOperand(), llvm::LanaiInstPrinter::printHi16ImmOperand(), llvm::AMDGPUInstPrinter::printIfSet(), llvm::AArch64InstPrinter::printImm8OptLsl(), llvm::PPCInstPrinter::printImmZeroOperand(), llvm::AVRMCExpr::printImpl(), printImplicitRegisterFlag(), llvm::SourceMgr::PrintIncludeStack(), llvm::ARMInstPrinter::printInst(), llvm::SPIRVInstPrinter::printInst(), llvm::HexagonInstPrinter::printInst(), llvm::PPCInstPrinter::printInst(), llvm::WebAssemblyInstPrinter::printInst(), llvm::AArch64AppleInstPrinter::printInst(), printLine(), llvm::R600InstPrinter::printLiteral(), llvm::printLLVMNameWithoutPrefix(), llvm::LanaiInstPrinter::printLo16AndImmOperand(), llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), llvm::AArch64InstPrinter::printMatrix(), llvm::AArch64InstPrinter::printMatrixTile(), llvm::AArch64InstPrinter::printMatrixTileVector(), llvm::LanaiInstPrinter::printMemImmOperand(), llvm::X86ATTInstPrinter::printMemOffset(), llvm::X86IntelInstPrinter::printMemOffset(), llvm::BPFInstPrinter::printMemOperand(), printMemoryBaseRegister(), printMemoryImmediateOffset(), llvm::X86ATTInstPrinter::printMemReference(), llvm::X86IntelInstPrinter::printMemReference(), llvm::LanaiInstPrinter::printMemRrOperand(), llvm::SourceMgr::PrintMessage(), llvm::ARMInstPrinter::printMveSaturateOp(), llvm::BPFInstPrinter::printOperand(), llvm::LanaiInstPrinter::printOperand(), llvm::SPIRVInstPrinter::printOperand(), llvm::RISCVInstPrinter::printOperand(), llvm::CSKYInstPrinter::printOperand(), llvm::NVPTXInstPrinter::printOperand(), llvm::VEInstPrinter::printOperand(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::X86ATTInstPrinter::printOperand(), llvm::SparcInstPrinter::printOperand(), llvm::X86IntelInstPrinter::printOperand(), llvm::ARMInstPrinter::printOperand(), llvm::PPCInstPrinter::printOperand(), llvm::AArch64InstPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::cl::generic_parser_base::printOptionInfo(), llvm::X86InstPrinterCommon::printPCRelImm(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::printPipeline(), llvm::ARMInstPrinter::printPKHASRShiftImm(), llvm::ARMInstPrinter::printPKHLSLShiftImm(), llvm::AArch64InstPrinter::printPredicateAsCounter(), llvm::PPCInstPrinter::printPredicateOperand(), llvm::NVPTXInstPrinter::printProtoIdent(), llvm::AArch64InstPrinter::printRangePrefetchAlias(), printRegImmShift(), llvm::ARMInstPrinter::printRegisterList(), llvm::WebAssemblyInstPrinter::printRegName(), llvm::printRegUnit(), llvm::AArch64InstPrinter::printRegWithShiftExtend(), llvm::ARMInstPrinter::printRotImmOperand(), llvm::PPCInstPrinter::printS34ImmOperand(), llvm::ARMInstPrinter::printSBitModifierOperand(), llvm::ARMInstPrinter::printSORegRegOperand(), llvm::MIPrinter::printStackObjectReference(), llvm::AArch64InstPrinter::printSVCROp(), llvm::MCSectionMachO::printSwitchToSection(), llvm::MCSectionCOFF::printSwitchToSection(), llvm::MCSectionELF::printSwitchToSection(), llvm::MCSectionXCOFF::printSwitchToSection(), llvm::object::TapiFile::printSymbolName(), llvm::ARMAsmPrinter::PrintSymbolOperand(), llvm::AsmPrinter::PrintSymbolOperand(), llvm::AArch64InstPrinter::printSysAlias(), llvm::AArch64InstPrinter::printSysCROperand(), llvm::AArch64InstPrinter::printSyspAlias(), llvm::AArch64InstPrinter::printSyspXzrPair(), llvm::ARMInstPrinter::printT2AddrModeImm8s4OffsetOperand(), llvm::ARMInstPrinter::printT2AddrModeImm8s4Operand(), llvm::ARMInstPrinter::printT2AddrModeSoRegOperand(), llvm::ARMInstPrinter::printT2SOOperand(), llvm::MachineOperand::printTargetFlags(), llvm::ARMInstPrinter::printThumbITMask(), llvm::PPCInstPrinter::printU10ImmOperand(), llvm::PPCInstPrinter::printU12ImmOperand(), llvm::PPCInstPrinter::printU1ImmOperand(), llvm::PPCInstPrinter::printU2ImmOperand(), llvm::PPCInstPrinter::printU3ImmOperand(), llvm::PPCInstPrinter::printU4ImmOperand(), llvm::PPCInstPrinter::printU5ImmOperand(), llvm::PPCInstPrinter::printU6ImmOperand(), llvm::PPCInstPrinter::printU7ImmOperand(), llvm::AArch64InstPrinter::printUImm12Offset(), llvm::X86ATTInstPrinter::printVecCompareInstr(), llvm::X86IntelInstPrinter::printVecCompareInstr(), llvm::RISCVInstPrinter::printVMaskReg(), llvm::ARMInstPrinter::printVPTMask(), llvm::AArch64InstPrinter::printVRegOperand(), printWithSpacePadding(), llvm::RISCVInstPrinter::printZeroOffsetMemOp(), priorNonDebug(), processAbsIntrinsic(), llvm::JumpThreadingPass::processBranchOnXOR(), processCallSite(), processDbgDeclare(), llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), processInstr(), processInternalGlobal(), llvm::logicalview::LVBinaryReader::processLines(), llvm::AArch64_AM::processLogicalImmediate(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), processPhiNode(), processPSInputArgs(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachO::processScatteredVANILLA(), processSDiv(), processSDivOrSRem(), llvm::processShuffleMasks(), processSRem(), processSwitches(), llvm::JumpThreadingPass::processThreadableEdges(), processUDivOrURem(), processUMulZExtIdiom(), llvm::xray::FileBasedRecordProducer::produce(), llvm::AttributeImpl::Profile(), ProfileCondOpInit(), ProfileDagInit(), llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph(), ProfitableToMerge(), profitableToRotateLoopExitingLatch(), llvm::PrologEpilogSGPRSpillBuilder::PrologEpilogSGPRSpillBuilder(), llvm::promoteCall(), llvm::InstCombinerImpl::PromoteCastOfAllocation(), llvm::promoteLoopAccessesToScalars(), PromoteMaskArithmetic(), llvm::HexagonPacketizerList::promoteToDotCur(), llvm::HexagonPacketizerList::promoteToDotNew(), llvm::ModuleSummaryIndex::propagateAttributes(), propagateAttributesToRefs(), propagateMemProfHelper(), propagateSPIRVType(), llvm::SwiftErrorValueTracking::propagateVRegs(), ProvideOption(), llvm::DXContainerYAML::PSVInfo::PSVInfo(), llvm::PtrToIntInst::PtrToIntInst(), llvm::InstructionWorklist::push(), llvm::PMStack::push(), llvm::TinyPtrVector< llvm::VPValue * >::push_back(), llvm::msgpack::ArrayDocNode::push_back(), llvm::IntrusiveBackListBase::push_back(), llvm::AAPointerInfo::RangeList::push_back(), llvm::IntrusiveBackListBase::push_front(), PushArgMD(), llvm::BitTracker::MachineEvaluator::putCell(), llvm::raw_pwrite_stream::pwrite(), query(), llvm::ARM::WinEH::RuntimeFunction::R(), llvm::AAPointerInfo::RangeList::RangeList(), rangeMetadataExcludesValue(), llvm::json::OStream::rawValueEnd(), llvm::BitTracker::reached(), llvm::SimpleBitstreamCursor::Read(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy >::read(), llvm::raw_fd_stream::read(), readAbbreviatedField(), llvm::BinaryStreamReader::readArray(), llvm::support::endian::readAtBitAlignment(), llvm::BinaryStreamReader::readCString(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles(), llvm::GCOVFile::readGCDA(), readImmediate(), llvm::sampleprof::SampleProfileReaderText::readImpl(), llvm::sampleprof::SampleProfileReaderGCC::readImpl(), LiveDebugValues::MLocTracker::readMLoc(), llvm::memprof::RawMemProfReader::readNextRecord(), llvm::OnDiskChainedHashTable< Info >::readNumBucketsAndEntries(), llvm::BitstreamCursor::readRecord(), llvm::MachineOperand::readsReg(), llvm::pdb::ModuleDebugStreamRef::readSymbolAtOffset(), llvm::SimpleBitstreamCursor::ReadVBR(), llvm::SimpleBitstreamCursor::ReadVBR64(), reassociateFCmps(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), llvm::OutlinableRegion::reattachCandidate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), rebasedHexDigitToNumber(), rebuildLoopAfterUnswitch(), llvm::WebAssemblyExceptionInfo::recalculate(), llvm::BuildVectorSDNode::recastRawBits(), llvm::GCNUpwardRPTracker::recede(), llvm::RegPressureTracker::recede(), llvm::RegPressureTracker::recedeSkipDebugValues(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), llvm::recomputeLivenessFlags(), recomputeLoopBlockSet(), llvm::recomputeVPTBlockMask(), reconnectPhis(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReconstructTruncateFromBuildVector(), llvm::PMDataManager::recordAvailableAnalysis(), llvm::ImportedFunctionsInliningStatistics::recordInline(), llvm::StackMaps::recordPatchPoint(), llvm::VPRecipeBuilder::recordRecipeOf(), llvm::MachineDominatorTree::recordSplitCriticalEdge(), llvm::StackMaps::recordStackMap(), llvm::StackMaps::recordStatepoint(), llvm::MLInlineAdvice::recordUnattemptedInliningImpl(), llvm::RecordVal::RecordVal(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), redirectTo(), redirectToHub(), redirectValuesFromPredecessorsToPhi(), reduceBuildVecToShuffleWithZero(), llvm::ScheduleDAGInstrs::reduceHugeMemNodeMaps(), ReduceLoopStrength(), reduceMaskedLoadToScalarLoad(), ReduceSwitchRange(), llvm::OpenMPIRBuilder::ReductionInfo::ReductionInfo(), llvm::MachineMemOperand::refineAlignment(), llvm::ARM::WinEH::RuntimeFunction::Reg(), llvm::WebAssembly::regClassToValType(), llvm::ARM::WinEH::RuntimeFunctionARM64::RegF(), llvm::ARM::WinEH::RuntimeFunctionARM64::RegI(), regIsPICBase(), llvm::Attributor::registerAA(), llvm::PassRegistry::registerAnalysisGroup(), llvm::AssumptionCache::registerAssumption(), llvm::PrintPassInstrumentation::registerCallbacks(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::DotCfgChangeReporter::registerCallbacks(), llvm::Attributor::registerForUpdate(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::orc::ExecutionSession::registerJITDispatchHandlers(), llvm::orc::RTDyldObjectLinkingLayer::registerJITEventListener(), llvm::ManagedStaticBase::RegisterManagedStatic(), registerPartialPipelineCallback(), llvm::PassRegistry::registerPass(), llvm::TargetRegistry::RegisterTarget(), llvm::OffloadEntriesInfoManager::registerTargetRegionEntryInfo(), llvm::WebAssemblyAsmPrinter::regToString(), llvm::objcarc::ProvenanceAnalysis::related(), llvm::RISCVAsmBackend::relaxDwarfCFA(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), llvm::RISCVAsmBackend::relaxInstruction(), llvm::RefCountedBase< Derived >::Release(), llvm::ThreadSafeRefCountedBase< ResourceTracker >::Release(), llvm::ImutAVLTree< ImutInfo >::release(), llvm::ConvergingVLIWScheduler::releaseBottomNode(), llvm::mca::ResourceState::releaseBuffer(), llvm::ReleaseModeModelRunner< TGen >::ReleaseModeModelRunner(), llvm::SchedBoundary::releaseNode(), llvm::mca::ResourceState::releaseSubResource(), llvm::ModuleSummaryIndex::releaseTemporaryMemory(), llvm::pdb::PDBStringTable::reload(), relocationViaAlloca(), llvm::StatepointLoweringState::relocCallVisited(), llvm::detail::IEEEFloat::remainder(), llvm::detail::DoubleAPFloat::remainder(), llvm::APFloat::remainder(), llvm::Intrinsic::remangleIntrinsicFunction(), llvm::LiveRangeEdit::rematerializeAt(), rematerializeChain(), rematerializeLiveValues(), rematerializeLiveValuesAtUses(), remomveUndefDbgAssignsFromEntryBlock(), llvm::GISelWorkList< 8 >::remove(), llvm::LatencyPriorityQueue::remove(), llvm::ResourcePriorityQueue::remove(), llvm::SetVector< llvm::MCSection *, SmallVector< llvm::MCSection *, N >, SmallDenseSet< llvm::MCSection *, N > >::remove(), llvm::ConstantUniqueMap< llvm::ConstantExpr >::remove(), llvm::MachineBasicBlock::remove(), llvm::orc::JITDylib::remove(), llvm::ImutAVLFactory< ImutInfo >::remove_internal(), llvm::jitlink::LinkGraph::removeAbsoluteSymbol(), llvm::AttrBuilder::removeAttribute(), llvm::DominanceFrontierBase< BasicBlock, false >::removeBlock(), llvm::jitlink::LinkGraph::removeBlock(), llvm::LoopBase< BasicBlock, Loop >::removeBlockFromLoop(), removeBlockFromLoops(), llvm::MemorySSAUpdater::removeBlocks(), llvm::BPFInstrInfo::removeBranch(), llvm::WebAssemblyInstrInfo::removeBranch(), llvm::XCoreInstrInfo::removeBranch(), llvm::ARCInstrInfo::removeBranch(), llvm::NVPTXInstrInfo::removeBranch(), llvm::MSP430InstrInfo::removeBranch(), llvm::MipsInstrInfo::removeBranch(), llvm::VEInstrInfo::removeBranch(), llvm::SparcInstrInfo::removeBranch(), llvm::LanaiInstrInfo::removeBranch(), llvm::HexagonInstrInfo::removeBranch(), llvm::ARMBaseInstrInfo::removeBranch(), llvm::R600InstrInfo::removeBranch(), llvm::SystemZInstrInfo::removeBranch(), llvm::M68kInstrInfo::removeBranch(), llvm::X86InstrInfo::removeBranch(), llvm::PPCInstrInfo::removeBranch(), llvm::CallGraphNode::removeCallEdgeFor(), llvm::SwitchInst::removeCase(), llvm::SwitchInstProfUpdateWrapper::removeCase(), llvm::LoopBase< BasicBlock, Loop >::removeChildLoop(), llvm::FastISel::removeDeadCode(), RemoveDeadConstant(), llvm::LazyCallGraph::removeDeadFunction(), llvm::jitlink::LinkGraph::removeDefinedSymbol(), llvm::IndirectBrInst::removeDestination(), llvm::LazyCallGraph::removeEdge(), removeEmptyCleanup(), llvm::jitlink::LinkGraph::removeExternalSymbol(), llvm::MachineInstr::removeFromBundle(), llvm::DominanceFrontierBase< BasicBlock, false >::removeFromFrontier(), llvm::orc::JITDylib::removeFromLinkOrder(), llvm::MemorySSA::removeFromLookups(), llvm::MachineFunction::removeFromMBBNumbering(), llvm::VPRecipeBase::removeFromParent(), llvm::MachineBasicBlock::removeFromParent(), llvm::MachineInstr::removeFromParent(), RemoveFromReverseMap(), llvm::ValueHandleBase::RemoveFromUseList(), llvm::CallGraph::removeFunctionFromModule(), llvm::orc::JITDylib::removeGenerator(), llvm::PHINode::removeIncomingValue(), llvm::InstructionPrecedenceTracking::removeInstruction(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::orc::ExecutionSession::removeJITDylib(), llvm::StringMapImpl::RemoveKey(), llvm::cl::parser< const PassInfo * >::removeLiteralOption(), llvm::LoopInfoBase< BasicBlock, Loop >::removeLoop(), llvm::SlotIndexes::removeMachineInstrFromMaps(), removeMapRegEntry(), llvm::rdf::CodeNode::removeMember(), llvm::MemorySSAUpdater::removeMemoryAccess(), llvm::ImutAVLFactory< ImutInfo >::removeMinBinding(), llvm::SCCPSolver::removeNonFeasibleEdges(), llvm::CallGraphNode::removeOneAbstractEdgeTo(), llvm::MachineInstr::removeOperand(), llvm::LazyCallGraph::RefSCC::removeOutgoingEdge(), llvm::CallBase::removeParamAttr(), llvm::ScalarEvolution::removePointerBase(), RemovePreallocated(), llvm::SUnit::removePred(), llvm::BasicBlock::removePredecessor(), llvm::ConvergingVLIWScheduler::VLIWSchedBoundary::removeReady(), llvm::SchedBoundary::removeReady(), removeRedundantInsertVectorElt(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots(), llvm::LivePhysRegs::removeReg(), removeRegisterOperands(), llvm::mca::RegisterFile::removeRegisterWrite(), removeRegLanes(), llvm::MachineRegisterInfo::removeRegOperandFromUseList(), llvm::jitlink::LinkGraph::removeSection(), llvm::objcopy::elf::DynamicRelocationSection::removeSectionReferences(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), llvm::RegionBase< RegionTraits< Function > >::removeSubRegion(), llvm::MachineBasicBlock::removeSuccessor(), removeUndefDbgLocsFromEntryBlock(), llvm::removeUnreachableBlocks(), RemoveUnusedGlue(), llvm::LiveVariables::removeVirtualRegisterDead(), llvm::LiveVariables::removeVirtualRegisterKilled(), llvm::LiveVariables::removeVirtualRegistersKilled(), llvm::VPlan::removeVPValueFor(), llvm::LiveIntervals::removeVRegDefAt(), llvm::MachineFunction::RenumberBlocks(), llvm::LiveRange::RenumberValues(), llvm::slpvectorizer::BoUpSLP::VLOperands::reorder(), reorderOrder(), reorderReuses(), llvm::reorderScalars(), ReorganizeVector(), llvm::RegBankSelect::RepairingPlacement::RepairingPlacement(), llvm::RegBankSelect::repairReg(), repeat(), replace(), ReplaceAddWithADDP(), llvm::replaceAllDbgUsesWith(), llvm::ReplaceableMetadataImpl::replaceAllUsesWith(), llvm::MDNode::replaceAllUsesWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::replaceAndRecursivelySimplify(), llvm::DIExpression::replaceArg(), replaceArgumentUses(), ReplaceATOMIC_LOAD_128Results(), llvm::X86InstrInfo::replaceBranchWithTailCall(), replaceCalledFunction(), llvm::CallGraphNode::replaceCallEdge(), llvm::LoopBase< BasicBlock, Loop >::replaceChildLoopWith(), ReplaceCMP_SWAP_128Results(), ReplaceCMP_SWAP_64Results(), replaceConstants(), llvm::replaceDbgDeclare(), replaceDominatedUsesWith(), llvm::InstCombinerImpl::replacedSelectWithOperand(), llvm::HexagonMCInstrInfo::replaceDuplex(), llvm::DICompositeType::replaceElements(), llvm::DIMacroFile::replaceElements(), llvm::RegionBase< RegionTraits< Function > >::replaceExit(), replaceFoldableUses(), replaceFrameIndex(), llvm::PHINode::replaceIncomingBlockWith(), llvm::orc::JITDylib::replaceInLinkOrder(), llvm::PPCInstrInfo::replaceInstrOperandWithImm(), llvm::CombinerHelper::replaceInstWithConstant(), llvm::CombinerHelper::replaceInstWithFConstant(), llvm::ReplaceInstWithInst(), llvm::CombinerHelper::replaceInstWithUndef(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), replaceLoopInvariantUses(), replaceLoopPHINodesWithPreheaderValues(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::MachineJumpTableInfo::ReplaceMBBInJumpTable(), llvm::MachineJumpTableInfo::ReplaceMBBInJumpTables(), llvm::CallGraphSCC::ReplaceNode(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::LazyCallGraph::RefSCC::replaceNodeFunction(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::RISCVTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::replaceNonLocalUsesWith(), replaceOneDbgValueForAlloca(), llvm::ConstantUniqueMap< llvm::ConstantExpr >::replaceOperandsInPlace(), llvm::CombinerHelper::replaceRegOpWith(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::DILexicalBlockBase::replaceScope(), llvm::objcopy::elf::Object::replaceSections(), replaceShuffleOfInsert(), llvm::replaceSignedInst(), llvm::CombinerHelper::replaceSingleDefInstWithOperand(), llvm::CombinerHelper::replaceSingleDefInstWithReg(), llvm::MachineBasicBlock::replaceSuccessor(), replaceSwiftErrorOps(), replaceTargetsFromPHINode(), llvm::codeview::AppendingTypeTableBuilder::replaceType(), llvm::codeview::MergingTypeTableBuilder::replaceType(), llvm::codeview::GlobalTypeTableBuilder::replaceType(), llvm::Constant::replaceUndefsWith(), llvm::MachineBasicBlock::ReplaceUsesOfBlockWith(), llvm::User::replaceUsesOfWith(), llvm::Value::replaceUsesOutsideBlock(), llvm::Value::replaceUsesWithIf(), llvm::DistinctMDOperandPlaceholder::replaceUseWith(), llvm::BitcodeReaderValueList::replaceValueWithoutRAUW(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), replaceWithConstant(), replaceWithTileLoad(), replaceWithTLIFunction(), reportMayClobberedLoad(), llvm::InterleaveGroup< InstTy >::requiresScalarEpilogue(), llvm::SIFrameLowering::requiresStackPointerReference(), llvm::LoopBase< BasicBlock, Loop >::reserveBlocks(), llvm::mca::ResourceState::reserveBuffer(), llvm::mca::ResourceManager::reserveBuffers(), reservePreviousStackSlotForValue(), reservePrivateMemoryRegs(), llvm::MachineRegisterInfo::reserveReg(), llvm::mca::ResourceManager::reserveResource(), llvm::StatepointLoweringState::reserveStackSlot(), llvm::VPTransformState::reset(), llvm::BitVector::reset(), llvm::SmallBitVector::reset(), llvm::SchedBoundary::reset(), llvm::AllocatorList< Token >::resetAlloc(), llvm::MachineRegisterInfo::resetDelegate(), llvm::MachineFunction::resetDelegate(), resetVRegCycle(), llvm::MDNode::resize(), llvm::MDNode::resolve(), llvm::object::resolveARM(), llvm::MDNode::resolveCycles(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), llvm::ThumbRegisterInfo::resolveFrameIndex(), llvm::RISCVRegisterInfo::resolveFrameIndex(), llvm::AArch64RegisterInfo::resolveFrameIndex(), llvm::SIRegisterInfo::resolveFrameIndex(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), llvm::logicalview::LVElement::resolveFullname(), resolveFwdRef(), llvm::BitsInit::resolveReferences(), llvm::RuntimeDyldMachOX86_64::resolveRelocation(), llvm::RuntimeDyldCOFFX86_64::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), llvm::RuntimeDyldCOFFI386::resolveRelocation(), llvm::RuntimeDyldCOFFThumb::resolveRelocation(), llvm::RuntimeDyldMachOARM::resolveRelocation(), llvm::RuntimeDyldCOFFAArch64::resolveRelocation(), llvm::RuntimeDyldMachOAArch64::resolveRelocation(), llvm::TargetSchedModel::resolveSchedClass(), resolveTargetShuffleFromZeroables(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::AVRFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::XCoreFrameLowering::restoreCalleeSavedRegisters(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::CSKYFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::GCNIterativeScheduler::OverrideLegacyStrategy::restoreOrder(), restorePreTransformState(), RestoreSpillList(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), llvm::CCState::resultsCompatible(), llvm::ARM::WinEH::RuntimeFunction::Ret(), llvm::DIBuilder::retainType(), llvm::mca::Instruction::retire(), llvm::mca::RetireControlUnit::RetireControlUnit(), llvm::MetadataTracking::retrack(), llvm::SmallPtrSetIteratorImpl::RetreatIfNotValid(), returnEdge(), llvm::LoopBase< BasicBlock, Loop >::reverseBlock(), llvm::MSP430InstrInfo::reverseBranchCondition(), llvm::WebAssemblyInstrInfo::reverseBranchCondition(), llvm::CSKYInstrInfo::reverseBranchCondition(), llvm::MipsInstrInfo::reverseBranchCondition(), llvm::LoongArchInstrInfo::reverseBranchCondition(), llvm::SparcInstrInfo::reverseBranchCondition(), llvm::XCoreInstrInfo::reverseBranchCondition(), llvm::ARCInstrInfo::reverseBranchCondition(), llvm::AVRInstrInfo::reverseBranchCondition(), llvm::RISCVInstrInfo::reverseBranchCondition(), llvm::LanaiInstrInfo::reverseBranchCondition(), llvm::HexagonInstrInfo::reverseBranchCondition(), llvm::SystemZInstrInfo::reverseBranchCondition(), llvm::X86InstrInfo::reverseBranchCondition(), llvm::PPCInstrInfo::reverseBranchCondition(), llvm::HexagonInstrInfo::reversePrediction(), RevertWhileLoopSetup(), llvm::RevertWhileLoopStartLR(), llvm::ARMBlockPlacement::revertWhileToDoLoop(), llvm::SSAUpdaterBulk::RewriteAllUses(), llvm::rewriteARMFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::rewriteLoopExitValues(), rewriteMaterializableInstructions(), rewriteMemOpOfSelect(), rewriteP2Align(), rewritePHINodesForExitAndUnswitchedBlocks(), rewritePHINodesForUnswitchedExitBlock(), rewritePHIs(), rewriteSelectInstMemOps(), llvm::rewriteT2FrameIndex(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), llvm::RISCVTargetLowering::RISCVTargetLowering(), llvm::RNSuccIterator< FlatIt< NodeRef >, BlockT, RegionT >::RNSuccIterator(), llvm::APInt::roundToDouble(), llvm::detail::IEEEFloat::roundToIntegral(), llvm::detail::DoubleAPFloat::roundToIntegral(), llvm::KCFIPass::run(), llvm::rdf::CopyPropagation::run(), llvm::ModuleInlinerPass::run(), llvm::LoopBoundSplitPass::run(), llvm::BitTracker::run(), llvm::PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::mca::Pipeline::run(), llvm::ThinLTOCodeGenerator::run(), llvm::InstCombinerImpl::run(), llvm::ReassociatePass::run(), llvm::InlinerPass::run(), llvm::JumpThreadingPass::run(), llvm::GenericCycleInfoCompute< ContextT >::run(), llvm::orc::CtorDtorRunner::run(), llvm::MachineFunctionPassManager::run(), llvm::LoadAndStorePromoter::run(), llvm::DominatorTreeVerifierPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::FunctionAnalysisManagerCGSCCProxy::run(), llvm::FunctionToLoopPassAdaptor::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::DevirtSCCRepeatedPass::run(), runAttributorOnFunctions(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::JumpThreadingPass::runImpl(), llvm::TLSVariableHoistPass::runImpl(), runImpl(), runIPSCCP(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::IntervalPartition::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::StackProtector::runOnFunction(), llvm::AMDGPURegBankSelect::runOnMachineFunction(), llvm::CFIFixup::runOnMachineFunction(), llvm::InstructionSelect::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), AMDGPUDAGToDAGISel::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), runPass(), llvm::CrashRecoveryContext::RunSafely(), llvm::RuntimeDyldCOFF::RuntimeDyldCOFF(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithLoopNestPasses(), llvm::IntervalMapImpl::LeafNode< uint64_t, uint16_t, N, IntervalMapHalfOpenInfo< uint64_t > >::safeFind(), llvm::IntervalMapImpl::BranchNode< KeyT, ValT, RootBranchCap, Traits >::safeFind(), llvm::MachineFunction::salvageCopySSA(), llvm::MachineFunction::salvageCopySSAImpl(), salvageDbgAssignAddress(), llvm::salvageDebugInfo(), llvm::SelectionDAG::salvageDebugInfo(), llvm::salvageDebugInfoForDbgValue(), llvm::salvageDebugInfoForDbgValues(), salvageDebugInfoFromEmptyBlock(), SalvageDVI(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), llvm::sampleprof::SampleContext::SampleContext(), llvm::SampleContextTracker::SampleContextTracker(), llvm::SPIRV::SampledImageTypeDescriptor::SampledImageTypeDescriptor(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::SampleProfileReaderItaniumRemapper(), scalarizeExtEltFP(), llvm::InnerLoopVectorizer::scalarizeInstruction(), scalarizeMaskedScatter(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::LLT::scalarOrVector(), llvm::detail::scalbn(), scale(), llvm::InstrProfRecord::scale(), llvm::APIntOps::ScaleBitMask(), llvm::scaleBranchCount(), scaleShuffleElements(), scavengeFrameVirtualRegsInBlock(), llvm::RegScavenger::scavengeRegister(), llvm::RegScavenger::scavengeRegisterBackwards(), scavengeVReg(), llvm::scc_member_iterator< GraphT, GT >::scc_member_iterator(), llvm::SCEVComparePredicate::SCEVComparePredicate(), llvm::SCEVMinMaxExpr::SCEVMinMaxExpr(), llvm::SCEVSequentialMinMaxExpr::SCEVSequentialMinMaxExpr(), llvm::VLIWMachineScheduler::schedule(), llvm::SIScheduleBlock::schedule(), llvm::GCNIterativeScheduler::OverrideLegacyStrategy::schedule(), llvm::SwingSchedulerDAG::schedule(), llvm::ScheduleDAGMI::schedule(), llvm::SIScheduleDAGMI::schedule(), llvm::ScheduleDAGMILive::schedule(), llvm::GCNIterativeScheduler::scheduleBest(), llvm::GCNIterativeScheduler::scheduleLegacyMaxOccupancy(), llvm::ScheduleDAGMILive::scheduleMI(), llvm::PMTopLevelManager::schedulePass(), llvm::GCNIterativeScheduler::scheduleRegion(), llvm::SDDbgValue::SDDbgValue(), llvm::SDep::SDep(), llvm::SDLoc::SDLoc(), llvm::SDNode::SDNode(), llvm::SDValue::SDValue(), SDValueToConstBool(), llvm::yaml::sectionMapping(), llvm::object::XCOFFObjectFile::sections32(), llvm::object::XCOFFObjectFile::sections64(), llvm::raw_fd_ostream::seek(), llvm::LiveRange::Segment::Segment(), llvm::AMDGPUInstructionSelector::select(), AMDGPUDAGToDAGISel::Select(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), AMDGPUDAGToDAGISel::SelectBuildVector(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::HexagonDAGToDAGISel::SelectConstant(), selectConstantAddr(), selectCopy(), selectELFSectionForGlobal(), selectExplicitSectionGlobal(), llvm::HexagonDAGToDAGISel::SelectExtractSubvector(), llvm::HvxSelector::selectExtractSubvector(), llvm::RISCVDAGToDAGISel::selectFPImm(), selectI64ImmDirect(), selectIncomingValueForBlock(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::SelectionDAGISel::SelectInlineAsmMemoryOperands(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::FastISel::selectIntrinsicCall(), llvm::SplitEditor::selectIntv(), selectMergeValues(), SelectMSA3OpIntrinsic(), llvm::PPCTargetLowering::SelectOptimalAddrMode(), llvm::FastISel::selectPatchpoint(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::LoongArchDAGToDAGISel::selectShiftMask(), llvm::RISCVDAGToDAGISel::selectShiftMask(), llvm::HvxSelector::selectShuffle(), llvm::FastISel::selectStackmap(), llvm::EngineBuilder::selectTarget(), selectUnmergeValues(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::RISCVDAGToDAGISel::selectVSplat(), selectVSplatSimmHelper(), separateNestedLoop(), llvm::orc::shared::SPSSerializationTraits< SPSExpected< SPSTagT >, detail::SPSSerializableError >::serialize(), serializePublic(), llvm::serializeSectionKind(), llvm::StackMaps::serializeToStackMapSection(), llvm::PatchLocation::set(), llvm::SMEAttrs::set(), llvm::CoalescingBitVector< IndexT >::set(), llvm::PointerSumType< ExtraInfoInlineKinds, llvm::PointerSumTypeMember< EIIK_MMO, llvm::MachineMemOperand * >, llvm::PointerSumTypeMember< EIIK_PreInstrSymbol, llvm::MCSymbol * >, llvm::PointerSumTypeMember< EIIK_PostInstrSymbol, llvm::MCSymbol * >, llvm::PointerSumTypeMember< EIIK_OutOfLine, ExtraInfo * > >::set(), llvm::FunctionLoweringInfo::set(), llvm::VPTransformState::set(), llvm::BitVector::set(), llvm::SmallBitVector::set(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::LegacyLegalizerInfo::setAction(), llvm::DbgAssignIntrinsic::setAddress(), llvm::OffloadEntriesInfoManager::OffloadEntryInfo::setAddress(), llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBit(), llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBytes(), llvm::GlobalAlias::setAliasee(), llvm::GlobalObject::setAlignment(), llvm::jitlink::Block::setAlignment(), llvm::object::coff_tls_directory< IntTy >::setAlignment(), llvm::jitlink::Block::setAlignmentOffset(), llvm::CallLowering::setArgFlags(), llvm::CallBase::setArgOperand(), llvm::cl::Option::setArgStr(), llvm::TargetLoweringBase::ArgListEntry::setAttributes(), llvm::TargetLibraryInfoImpl::setAvailableWithName(), llvm::MachineBasicBlock::setBBID(), llvm::wholeprogramdevirt::AccumBitVector::setBE(), llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBit(), llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBytes(), llvm::MCSection::setBeginSymbol(), llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::wholeprogramdevirt::AccumBitVector::setBit(), llvm::APInt::setBit(), llvm::APInt::setBits(), llvm::APInt::setBitsWithWrap(), llvm::BlockFrequencyInfo::setBlockFreq(), llvm::BlockFrequencyInfo::setBlockFreqAndScale(), llvm::StructType::setBody(), llvm::MIRProfileLoader::setBranchProbs(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), setBranchWeights(), llvm::pdb::BulkPublic::setBucketIdx(), llvm::MCAssembler::setBundleAlignSize(), llvm::HexagonInstrInfo::setBundleNoShuf(), llvm::ISD::ArgFlagsTy::setByRefSize(), llvm::ISD::ArgFlagsTy::setByValSize(), llvm::CallBase::setCalledFunction(), llvm::IRSimilarity::IRInstructionData::setCalleeName(), llvm::Function::setCallingConv(), llvm::CatchReturnInst::setCatchPad(), llvm::CatchPadInst::setCatchSwitch(), llvm::MachineOperand::setCImm(), llvm::CleanupReturnInst::setCleanupPad(), llvm::MCCVLoc::setColumn(), llvm::MCDwarfLoc::setColumn(), llvm::MCSymbol::setCommon(), llvm::logicalview::LVReader::setCompileUnit(), llvm::TargetLoweringBase::setCondCodeAction(), llvm::BranchInst::setCondition(), llvm::IRBuilderBase::setConstrainedFPFunctionAttr(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setContent(), llvm::jitlink::Block::setContent(), llvm::sampleprof::SampleContext::setContext(), setCoroInfo(), llvm::CoroIdInst::setCoroutineSelf(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::vfs::InMemoryFileSystem::setCurrentWorkingDirectory(), llvm::mca::ResourceManager::setCustomStrategy(), LiveDebugValues::DbgValue::setDbgOpIDs(), llvm::MachineInstr::setDebugLoc(), llvm::MachineInstr::setDebugValueUndef(), llvm::MachinePassRegistry< FunctionPassCtor >::setDefault(), llvm::IRBuilderBase::setDefaultConstrainedExcept(), llvm::IRBuilderBase::setDefaultConstrainedRounding(), llvm::MachineFunction::setDelegate(), llvm::MCSymbolMachO::setDesc(), llvm::MemIntrinsicBase< AnyMemIntrinsic >::setDest(), llvm::MCOperand::setDFPImm(), llvm::GlobalValue::setDLLStorageClass(), llvm::DWARFUnitHeader::setDWOId(), llvm::AMDGPUMachineFunction::setDynLDSAlign(), llvm::BranchProbabilityInfo::setEdgeProbability(), llvm::AtomicMemIntrinsic::setElementSizeInBytes(), llvm::mca::WriteState::setEliminated(), llvm::VPRegionBlock::setEntry(), llvm::Function::setEntryCount(), llvm::InlineAsmIdentifierInfo::setEnum(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), llvm::orc::LLJITBuilderSetters< LLLazyJIT, LLLazyJITBuilder, LLLazyJITBuilderState >::setExecutorProcessControl(), llvm::VPRegionBlock::setExiting(), llvm::MCOperand::setExpr(), llvm::AtomicCmpXchgInst::setFailureOrdering(), llvm::Instruction::setFast(), llvm::Instruction::setFastMathFlags(), llvm::VPInstruction::setFastMathFlags(), llvm::pdb::BulkPublic::setFlags(), llvm::MCDwarfLoc::setFlags(), llvm::SCEVWrapPredicate::setFlags(), llvm::MCSymbol::setFlags(), llvm::ModuleSummaryIndex::setFlags(), llvm::MCOperand::setFPImm(), llvm::MachineOperand::setFPImm(), llvm::MCSymbol::setFragment(), llvm::X86InstrInfo::setFrameAdjustment(), llvm::SIMachineFunctionInfo::setFrameOffsetReg(), llvm::MIRProfileLoader::setFSPass(), llvm::SwiftErrorValueTracking::setFunction(), llvm::MCContext::setGenDwarfRootFile(), llvm::GlobalObject::setGlobalObjectSubClassData(), llvm::GlobalValue::setGlobalValueSubClassData(), llvm::User::setGlobalVariableNumOperands(), llvm::jitlink::COFFLinkGraphBuilder::setGraphBlock(), llvm::jitlink::ELFLinkGraphBuilder< object::ELF64LE >::setGraphBlock(), llvm::jitlink::COFFLinkGraphBuilder::setGraphSymbol(), llvm::jitlink::ELFLinkGraphBuilder< object::ELF64LE >::setGraphSymbol(), llvm::Instruction::setHasAllowContract(), llvm::Instruction::setHasAllowReassoc(), llvm::Instruction::setHasAllowReciprocal(), llvm::Instruction::setHasApproxFunc(), llvm::Instruction::setHasNoInfs(), llvm::Instruction::setHasNoNaNs(), llvm::Instruction::setHasNoSignedZeros(), llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion::setID(), llvm::DomTreeNodeBase< VPBlockBase >::setIDom(), llvm::MCOperand::setImm(), llvm::MachineOperand::setImm(), llvm::R600InstrInfo::setImmOperand(), llvm::MachineOperand::setImplicit(), llvm::MemoryPhi::setIncomingBlock(), llvm::MemoryPhi::setIncomingValue(), llvm::PHINode::setIncomingValue(), llvm::PHINode::setIncomingValueForBlock(), llvm::MachineOperand::setIndex(), setInfoSVEStN(), llvm::GlobalVariable::setInitializer(), llvm::cl::list< DataType, StorageClass, ParserClass >::setInitialValues(), llvm::HexagonMCInstrInfo::setInnerLoop(), llvm::VPBuilder::setInsertPoint(), llvm::IRBuilderBase::SetInsertPoint(), llvm::SCEVExpander::setInsertPoint(), llvm::MachineIRBuilder::setInsertPt(), llvm::MCOperand::setInst(), llvm::MachineIRBuilder::setInstr(), llvm::SUnit::setInstr(), llvm::MachineOperand::setInstrRefInstrIndex(), llvm::MachineOperand::setInstrRefOpIndex(), llvm::MachineOperand::setIntrinsicID(), llvm::MCDwarfLoc::setIsa(), llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setIsDebug(), llvm::MachineOperand::setIsDef(), llvm::MachineOperand::setIsEarlyClobber(), llvm::MachineFrameInfo::setIsImmutableObjectIndex(), llvm::MachineOperand::setIsInternalRead(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setIsRenamable(), llvm::MachineOperand::setIsUndef(), llvm::SCEVExpander::setIVIncInsertPos(), false::Chain::setKill(), setKnownBase(), llvm::InlineAsmIdentifierInfo::setLabel(), llvm::MCBoundaryAlignFragment::setLastFragment(), llvm::PMTopLevelManager::setLastUser(), llvm::wholeprogramdevirt::AccumBitVector::setLE(), llvm::MemIntrinsicBase< AnyMemIntrinsic >::setLength(), setLimitsForBinOp(), setLimitsForIntrinsic(), llvm::jitlink::Symbol::setLinkage(), llvm::orc::JITDylib::setLinkOrder(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::StatepointLoweringState::setLocation(), llvm::Loop::setLoopID(), setM0ToIndexFromSGPR(), llvm::Module::setMaterializer(), llvm::MachineIRBuilder::setMBB(), llvm::MachineOperand::setMBB(), llvm::ISD::ArgFlagsTy::setMemAlign(), llvm::DwarfExpression::setMemoryLocationKind(), setMemoryPhiValueForBlock(), llvm::HexagonMCInstrInfo::setMemReorderDisabled(), llvm::MachineOperand::setMetadata(), llvm::SGPRSpillBuilder::setMI(), LiveDebugValues::MLocTracker::setMLoc(), llvm::LTOCodeGenerator::setModule(), llvm::HexagonMCExpr::setMustExtend(), llvm::HexagonMCExpr::setMustNotExtend(), llvm::jitlink::Block::setMutableContent(), llvm::DominatorTreeBase< BasicBlock, false >::setNewRoot(), llvm::mca::Stage::setNextInSequence(), llvm::SUnit::setNode(), llvm::User::setNumHungOffUseOperands(), llvm::MachineFrameInfo::setObjectAlignment(), llvm::MachineFrameInfo::setObjectOffset(), llvm::MachineFrameInfo::setObjectSExt(), llvm::MachineFrameInfo::setObjectSize(), llvm::MachineFrameInfo::setObjectSSPLayout(), llvm::MachineFrameInfo::setObjectZExt(), llvm::MCSymbol::setOffset(), llvm::MachineOperand::setOffset(), llvm::VPBlockBase::setOneSuccessor(), llvm::LLVMContextImpl::setOpaquePointers(), llvm::GVNExpression::BasicExpression::setOperand(), llvm::User::setOperand(), llvm::MDNode::setOperand(), llvm::NamedMDNode::setOperand(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetPassConfig::setOpt(), llvm::LTOCodeGenerator::setOptLevel(), llvm::AtomicRMWInst::setOrdering(), llvm::ISD::ArgFlagsTy::setOrigAlign(), llvm::MCSymbolELF::setOther(), llvm::HexagonMCInstrInfo::setOuterLoop(), llvm::LoopBase< BasicBlock, Loop >::setParentLoop(), llvm::FuncletPadInst::setParentPad(), llvm::ProfileSummary::setPartialProfileRatio(), llvm::MCSectionWasm::setPassive(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::objcopy::macho::RelocationInfo::setPlainRelocationSymbolNum(), llvm::VPBlockBase::setPlan(), llvm::SCEVExpander::setPostInc(), llvm::rdf::PhiUseNode::setPredecessor(), llvm::VPBlockBase::setPredecessors(), llvm::MachineOperand::setPredicate(), llvm::setProbeDistributionFactor(), llvm::RuntimeDyld::setProcessAllSections(), llvm::setProfileInfoAfterUnrolling(), llvm::setProfMetadata(), llvm::ValueInfo::setReadOnly(), llvm::VPRecipeBuilder::setRecipe(), llvm::PBQP::RegAlloc::NodeMetadata::setReductionState(), llvm::logicalview::LVSymbol::setReference(), llvm::MCOperand::setReg(), llvm::SDep::setReg(), llvm::MachineRegisterInfo::setRegAllocationHint(), llvm::MipsRegisterBankInfo::setRegBank(), llvm::MachineRegisterInfo::setRegClass(), llvm::CoalescerPair::setRegisters(), llvm::MachineOperand::setRegMask(), llvm::rdf::RefNode::setRegRef(), setRegsToType(), llvm::MCSymbolXCOFF::setRepresentedCsect(), llvm::Pass::setResolver(), llvm::ARCFunctionInfo::setReturnStackOffset(), llvm::XCoreFunctionInfo::setReturnStackOffset(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::setRInfo(), llvm::SelectionDAG::setRoot(), llvm::jitlink::Symbol::setScope(), llvm::SIMachineFunctionInfo::setScratchRSrcReg(), llvm::DIEUnit::setSection(), llvm::MCSectionCOFF::setSelection(), llvm::MCOperand::setSFPImm(), llvm::DomainValue::setSingleDomain(), llvm::jitlink::Symbol::setSize(), llvm::PBQP::Graph< RegAllocSolverImpl >::setSolver(), llvm::MemTransferBase< AnyMemIntrinsic >::setSource(), llvm::X86InstrInfo::setSpecialOperandAttr(), setSpecialRefs(), llvm::MachineFrameInfo::setStackID(), llvm::SIMachineFunctionInfo::setStackPtrOffsetReg(), llvm::ModuloSchedule::setStage(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStop(), llvm::Type::setSubclassData(), llvm::MachineOperand::setSubReg(), llvm::DwarfExpression::setSubRegisterPiece(), llvm::BranchInst::setSuccessor(), llvm::SwitchInst::setSuccessor(), llvm::InvokeInst::setSuccessor(), llvm::CallBrInst::setSuccessor(), llvm::CatchSwitchInst::setSuccessor(), llvm::CatchReturnInst::setSuccessor(), llvm::AtomicCmpXchgInst::setSuccessOrdering(), llvm::MachineBasicBlock::setSuccProbability(), llvm::LoongArchTargetStreamer::setTargetABI(), llvm::RISCVTargetStreamer::setTargetABI(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setTargetAddress(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::MachineOperand::setTargetFlags(), llvm::MCAsmParser::setTargetParser(), llvm::GlobalValue::setThreadLocalMode(), llvm::X86Operand::setTokenValue(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::VPBlockBase::setTwoSuccessors(), llvm::VPlan::setUF(), llvm::VPValue::setUnderlyingValue(), llvm::SparseSet< RootData >::setUniverse(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::setUniverse(), llvm::SelectionDAGBuilder::setUnusedArgValue(), llvm::CatchSwitchInst::setUnwindDest(), llvm::CleanupReturnInst::setUnwindDest(), setupBranchForGuard(), llvm::AsmPrinter::SetupMachineFunction(), llvm::PackedVectorBase< T, BitNum, BitVectorTy, false >::setValue(), llvm::PackedVectorBase< T, BitNum, BitVectorTy, true >::setValue(), llvm::SelectionDAGBuilder::setValue(), llvm::MemSetBase< AnyMemIntrinsic >::setValue(), llvm::RecordVal::setValue(), llvm::SwitchInst::CaseHandle::setValue(), llvm::Value::setValueName(), llvm::InlineAsmIdentifierInfo::setVar(), llvm::MCSymbol::setVariableValue(), llvm::VFABI::setVectorVariantNames(), llvm::VPlan::setVF(), llvm::MCSymbolELF::setVisibility(), llvm::object::Elf_Sym_Impl< ELFT >::setVisibility(), llvm::GlobalValue::setVisibility(), llvm::RegisterBankInfo::OperandsMapper::setVRegs(), llvm::GlobalVarSummary::setVTableFuncs(), llvm::WebAssemblyFunctionInfo::setWAReg(), llvm::jitlink::Symbol::setWeaklyReferenced(), llvm::setWidenableBranchCond(), llvm::LoopVectorizationCostModel::setWideningDecision(), llvm::ValueInfo::setWriteOnly(), llvm::RuntimeDyldChecker::MemoryRegionInfo::setZeroFill(), llvm::APInt::sext(), llvm::KnownBits::sextInReg(), llvm::SExtInst::SExtInst(), llvm::SGPRSpillBuilder::SGPRSpillBuilder(), shiftRightAndRound(), llvm::KnownBits::shl(), llvm::TargetMachine::shouldAssumeDSOLocal(), shouldClusterFI(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::PPCInstrInfo::shouldClusterMemOps(), llvm::SystemZRegisterInfo::shouldCoalesce(), llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::ARMTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::AArch64TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::PPCTargetLowering::shouldConvertConstantLoadToIntImm(), llvm::X86TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::GISelCSEInfo::shouldCSE(), llvm::TargetLoweringObjectFileXCOFF::ShouldEmitEHBlock(), llvm::shouldEmitPTXNoReturn(), llvm::NVPTXTargetLowering::shouldExpandAtomicRMWInIR(), shouldFoldCondBranchesToCommonDestination(), llvm::MipsTargetLowering::shouldFoldConstantShiftPairToMask(), llvm::AArch64TargetLowering::shouldFoldConstantShiftPairToMask(), llvm::ARMTargetLowering::shouldFoldConstantShiftPairToMask(), llvm::X86TargetLowering::shouldFoldConstantShiftPairToMask(), llvm::ARMAsmBackend::shouldForceRelocation(), shouldFullUnroll(), llvm::shouldFuncOptimizeForSizeImpl(), llvm::AMDGPU::shouldLowerLDSToStruct(), llvm::AArch64TTIImpl::shouldMaximizeVectorBandwidth(), llvm::shouldOptimizeForSize(), llvm::AArch64TargetLowering::shouldReduceLoadWidth(), llvm::X86TargetLowering::shouldReduceLoadWidth(), llvm::PPCInstrInfo::shouldReduceRegisterPressure(), shouldRewriteStatepointsIn(), llvm::OptPassGateInstrumentation::shouldRun(), llvm::OptBisect::shouldRunPass(), llvm::SIInstrInfo::shouldScheduleLoadsNear(), llvm::ARMBaseInstrInfo::shouldScheduleLoadsNear(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), ShouldSignWithBKey(), shouldSplit(), shouldSplitOnPredicatedArgument(), shouldTagGlobal(), llvm::TailDuplicator::shouldTailDuplicate(), llvm::MachineRegisterInfo::shouldTrackSubRegLiveness(), shouldTryInjectBasingOnMetadata(), shouldUseFrameHelper(), ShrinkDemandedConstant(), llvm::TargetLowering::ShrinkDemandedOp(), shrinkInsertElt(), llvm::BitcodeReaderValueList::shrinkTo(), llvm::LiveIntervals::shrinkToUses(), llvm::ShuffleVectorConstantExpr::ShuffleVectorConstantExpr(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::ConstantRange::signExtend(), llvm::SignExtend32(), llvm::SignExtend64(), llvm::SimpleDDGNode::SimpleDDGNode(), llvm::codeview::TypeIndex::simpleTypeName(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::simplify(), simplifyAMDGCNImageIntrinsic(), llvm::InstCombinerImpl::SimplifyAnyMemSet(), llvm::InstCombinerImpl::SimplifyAnyMemTransfer(), simplifyAssociativeBinOp(), SimplifyBSwap(), SimplifyCondBranchToCondBranch(), llvm::simplifyConstrainedFPCall(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TTIImpl::simplifyDemandedVectorEltsIntrinsic(), simplifyFCmpInst(), simplifyFunctionCFG(), simplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithBinOp(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyInstructionWithOperands(), simplifyLogicOfAddSub(), llvm::simplifyLoop(), simplifyLoopInst(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), llvm::TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), simplifyOneLoop(), simplifyOrLogic(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), simplifyRelocatesOffABase(), simplifySelectInst(), llvm::TargetLowering::SimplifySetCC(), simplifySetCCWithCTPOP(), simplifyShift(), SimplifyShortImmForm(), SimplifyShortMoveForm(), simplifyShuffleOfShuffle(), simplifyShuffleVectorInst(), simplifySuspendPoints(), simplifyTerminatorLeadingToRet(), simplifyWithOpReplaced(), simplifyX86addcarry(), simplifyX86immShift(), simplifyX86insertps(), simplifyX86pack(), simplifyX86pshufb(), simplifyX86varShift(), simplifyX86vpermilvar(), simplifyX86vpermv(), sink(), sinkAndCmp0Expression(), llvm::SinkAndHoistLICMFlags::SinkAndHoistLICMFlags(), SinkCast(), sinkCmpExpression(), SinkCommonCodeFromPredecessors(), sinkInstruction(), sinkLastInstruction(), sinkLifetimeStartMarkers(), sinkLoopInvariantInstructions(), sinkRecurrenceUsersAfterPrevious(), llvm::sinkRegion(), SinkShiftAndTruncate(), sinkThroughTriviallyReplaceablePHI(), llvm::SIRegisterInfo::SIRegisterInfo(), llvm::SIScheduleBlockScheduler::SIScheduleBlockScheduler(), llvm::SIToFPInst::SIToFPInst(), llvm::SuffixTreeNode::size(), llvm::orc::shared::WrapperFunctionResult::size(), llvm::SparseMultiSet< VReg2SUnit, VirtReg2IndexFunctor >::size(), llvm::sroa::Partition::size(), llvm::orc::shared::SPSSerializationTraits< SPSExpected< SPSTagT >, detail::SPSSerializableError >::size(), llvm::sys::fs::mapped_file_region::size(), llvm::DIELocList::sizeOf(), llvm::DWARFDebugLine::SectionParser::skip(), llvm::yaml::skip(), skipAlignedDPRCS2Spills(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::codeview::CodeViewRecordIO::skipPadding(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), llvm::MachineBasicBlock::SkipPHIsLabelsAndDebug(), llvm::BitstreamCursor::skipRecord(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), llvm::ArrayRef< uint64_t >::slice(), llvm::MutableArrayRef< llvm::coverage::CounterMappingRegion >::slice(), llvm::detail::indexed_accessor_range_base< DerivedT, std::pair< BaseT, ptrdiff_t >, T, T *, T & >::slice(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), slotForIndex(), llvm::SlotIndex::SlotIndex(), smallData(), llvm::SmallPtrSetImpl< const BlockT * >::SmallPtrSetImplBase(), llvm::SMFixIt::SMFixIt(), llvm::SMRange::SMRange(), llvm::TargetLowering::softenSetCCOperands(), solveDIType(), SolveLinEquationWithOverflow(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::SwitchCG::sortAndRangeify(), llvm::sortBasicBlocksAndUpdateBranches(), llvm::sampleprof::sortFuncProfiles(), sortLocalVars(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::sortNodesTopologically(), llvm::sortPtrAccesses(), llvm::Value::sortUseList(), speculateSelectInstLoads(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), spillIncomingStatepointValue(), spillRegPairs(), llvm::SIRegisterInfo::spillSGPR(), splatSplitI64WithVL(), llvm::BasicBlock::splice(), llvm::Function::splice(), llvm::spliceBB(), llvm::BinaryStreamWriter::split(), split(), llvm::BinaryStreamReader::split(), llvm::DominatorTreeBase< BasicBlock, false >::Split(), llvm::AMDGPURegisterBankInfo::split64BitValueForMapping(), SplitAndExtendv16i1(), splitAndLowerShuffle(), splitAsyncCoroutine(), llvm::VPBasicBlock::splitAt(), llvm::BasicBlock::splitBasicBlock(), llvm::BasicBlock::splitBasicBlockBefore(), llvm::SITargetLowering::splitBinaryVectorOp(), splitBlock(), llvm::jitlink::LinkGraph::splitBlock(), SplitBlockImpl(), SplitBlockPredecessorsImpl(), splitCallSite(), llvm::OutlinableRegion::splitCandidate(), llvm::splitCodeGen(), llvm::SplitCriticalEdge(), llvm::MachineBasicBlock::SplitCriticalEdge(), splitEdge(), llvm::SplitEdge(), llvm::SelectionDAG::SplitEVL(), llvm::SIInstrInfo::splitFlatOffset(), llvm::ScalarEvolution::SplitIntoInitAndPostInc(), splitIntVSETCC(), llvm::SplitKnownCriticalEdge(), SplitLandingPadPredecessorsImpl(), llvm::formatv_object_base::splitLiteralAndReplacement(), splitMask(), splitMBB(), SplitOpsAndApply(), llvm::VETargetLowering::splitPackedLoadStore(), splitPredecessorsOfLoopExit(), llvm::AVRRegisterInfo::splitReg(), splitRetconCoroutine(), splitStoreSplat(), llvm::MachineBasicBlock::splitSuccessor(), splitSwitchCoroutine(), llvm::SITargetLowering::splitTernaryVectorOp(), llvm::CallLowering::splitToValueTypes(), llvm::SITargetLowering::splitUnaryVectorOp(), splitUnequalType(), llvm::SystemZTargetLowering::splitValueIntoRegisterParts(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::AMDGPUTargetLowering::splitVector(), llvm::SelectionDAG::SplitVector(), splitVector(), splitVectorIntBinary(), splitVectorIntUnary(), llvm::VETargetLowering::splitVectorOp(), splitVectorStore(), llvm::APInt::sqrt(), SRAGlobal(), llvm::KnownBits::srem(), llvm::stableHashValue(), llvm::ARM::WinEH::RuntimeFunction::StackAdjust(), llvm::WebAssemblyFunctionInfo::stackifyVReg(), StackMallocSizeClass(), llvm::StackMapOpers::StackMapOpers(), llvm::StackMapParser< Endianness >::StackMapParser(), llvm::Register::stackSlot2Index(), llvm::IntervalMap< uint64_t, uint16_t, 8, IntervalMapHalfOpenInfo< uint64_t > >::start(), llvm::rdf::DataFlowGraph::DefStack::start_block(), llvm::AggressiveAntiDepBreaker::StartBlock(), llvm::DbgValueHistoryMap::startDbgValue(), llvm::FastISel::startNewBlock(), llvm::StatepointLoweringState::startNewStatepoint(), llvm::Timer::startTimer(), llvm::Function::stealArgumentListFrom(), llvm::CallGraphNode::stealCalledFunctionsFrom(), llvm::LivePhysRegs::stepForward(), StepOverPredicatedInstrs(), llvm::IntervalMap< uint64_t, uint16_t, 8, IntervalMapHalfOpenInfo< uint64_t > >::stop(), llvm::Timer::stopTimer(), llvm::RecordKeeper::stopTimer(), llvm::MDNode::storeDistinctInContext(), llvm::StoreIntToMemory(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::M68kInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), StrengthenNoWrapFlags(), stripAndComputeConstantOffsets(), stripDebugDeclareImpl(), llvm::stripDebugifyMetadata(), stripDebugLocFromLoopID(), stripLoopMDLoc(), stripNonValidData(), stripTrailingZeros(), stripValuesNotDefiningMask(), llvm::BitTracker::subst(), llvm::MachineFunction::substituteDebugValuesForInst(), substituteSimpleCopyRegs(), llvm::MachineOperand::substPhysReg(), StringView::substr(), llvm::MachineOperand::substVirtReg(), llvm::PPCInstrInfo::SubsumesPredicate(), llvm::SubsumingPositionIterator::SubsumingPositionIterator(), llvm::ConstantRange::subtract(), llvm::mca::CycleSegment::subtract(), llvm::APFloat::subtract(), llvm::SmallPtrSetImplBase::swap(), llvm::iplist_impl< simple_ilist< llvm::AliasSet, Options... >, ilist_traits< llvm::AliasSet > >::swap(), swapMIOperands(), llvm::SIInstrInfo::swapSourceModifiers(), llvm::BranchInst::swapSuccessors(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::LazyCallGraph::RefSCC::switchOutgoingEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchOutgoingEdgeToRef(), llvm::MCStreamer::switchSection(), llvm::MCStreamer::switchSectionNoChange(), llvm::RegBankSelect::RepairingPlacement::switchTo(), SwitchToLookupTable(), llvm::IRMover::IdentifiedStructTypeSet::switchToNonOpaque(), llvm::LazyCallGraph::RefSCC::switchTrivialInternalEdgeToRef(), llvm::object::SymbolRef::SymbolRef(), llvm::orc::SymbolsCouldNotBeRemoved::SymbolsCouldNotBeRemoved(), llvm::orc::SymbolsNotFound::SymbolsNotFound(), llvm::orc::SymbolStringPtr::SymbolStringPtr(), llvm::SystemZVectorConstantInfo::SystemZVectorConstantInfo(), llvm::InstrProfError::take(), llvm::Value::takeName(), llvm::ContextAndReplaceableUses::takeReplaceableUses(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::AArch64TargetLowering::targetShrinkDemandedConstant(), llvm::APInt::tcAdd(), llvm::APInt::tcDivide(), llvm::APInt::tcExtract(), llvm::APInt::tcFullMultiply(), llvm::APInt::tcMultiply(), llvm::APInt::tcMultiplyPart(), llvm::APInt::tcSet(), llvm::APInt::tcSubtract(), llvm::orc::COFFPlatform::teardownJITDylib(), llvm::orc::MachOPlatform::teardownJITDylib(), llvm::CoalescingBitVector< IndexT >::test(), llvm::lto::thinBackend(), llvm::thinLTOFinalizeInModule(), llvm::thinLTOInternalizeModule(), threadBinOpOverPHI(), threadBinOpOverSelect(), threadCmpOverPHI(), threadCmpOverSelect(), llvm::JumpThreadingPass::threadEdge(), llvm::JumpThreadingPass::threadGuard(), llvm::orc::ThreadSafeContext::ThreadSafeContext(), llvm::JumpThreadingPass::threadThroughTwoBasicBlocks(), llvm::MachineInstr::tieOperands(), llvm::OpenMPIRBuilder::tileLoops(), llvm::Timer::Timer(), llvm::TimerGroup::TimerGroup(), llvm::timeTraceProfilerInitialize(), llvm::timeTraceProfilerWrite(), llvm::pdb::Variant::toAPFloat(), llvm::pdb::Variant::toAPSInt(), llvm::codeview::TypeIndex::toArrayIndex(), llvm::CodeViewYAML::toCodeViewSubsectionList(), llvm::CodeViewYAML::toDebugH(), llvm::CodeViewYAML::toDebugT(), llvm::object::ELFObjectFile< ELFT >::toDRI(), toHexStr(), llvm::BitTracker::MachineEvaluator::toInt(), llvm::ScaledNumber< uint64_t >::toInt(), tokenizeWindowsCommandLineImpl(), llvm::orc::ExecutorAddr::toPtr(), toString(), llvm::detail::IEEEFloat::toString(), llvm::detail::DoubleAPFloat::toString(), llvm::APInt::toString(), toStringAPFloat(), llvm::object::COFFObjectFile::toSymb(), llvm::object::XCOFFObjectFile::toSymbolRef(), llvm::objcopy::macho::MachOWriter::totalSize(), toUTF8(), llvm::orc::ImplSymbolMap::trackImpls(), LiveDebugValues::MLocTracker::trackRegister(), llvm::ilist_base< EnableSentinelTracking >::transferBeforeImpl(), llvm::SelectionDAG::transferDbgValues(), llvm::DeadLaneDetector::transferDefinedLanes(), TransferTracker::transferMlocs(), llvm::ilist_callback_traits< MachineBasicBlock >::transferNodesFromList(), llvm::DeadLaneDetector::transferUsedLanes(), transformCallee(), translateDstIndex(), translateExtract(), translateShiftImm(), translateSrcIndex(), llvm::PHITransAddr::translateValue(), llvm::PBQP::Matrix::transpose(), llvm::ReachingDefAnalysis::traverse(), llvm::ImmutableGraphBuilder< GraphT >::trim(), llvm::trimBlockToPageSize(), llvm::APInt::trunc(), llvm::ConstantRange::truncate(), llvm::SmallVectorImpl< uint64_t >::truncate(), truncateScalarIntegerArg(), truncateToSize(), truncateVectorWithNARROW(), truncateVectorWithPACK(), llvm::TruncInst::TruncInst(), llvm::APInt::truncSSat(), llvm::APInt::truncUSat(), llvm::StringMap< uint64_t >::try_emplace(), tryAdjustICmpImmAndPred(), tryARMPackedUnwind(), llvm::RegBankSelect::tryAvoidingSplit(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), llvm::LegalizationArtifactCombiner::tryCombineAnyExt(), TryCombineBaseUpdate(), llvm::LegalizationArtifactCombiner::tryCombineExtract(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), tryCombineLongOpWithDup(), llvm::LegalizationArtifactCombiner::tryCombineSExt(), tryCombineToEXTR(), llvm::LegalizationArtifactCombiner::tryCombineTrunc(), llvm::LegalizationArtifactCombiner::tryCombineUnmergeValues(), llvm::LegalizationArtifactCombiner::tryCombineZExt(), llvm::HexagonMCInstrInfo::tryCompound(), llvm::AMDGPUDisassembler::tryDecodeInst(), llvm::tryDelinearizeFixedSizeImpl(), llvm::VFABI::tryDemangleForVFABI(), llvm::AArch64GISelUtils::tryEmitBZero(), llvm::DWARFUnit::tryExtractDIEsIfNeeded(), tryFactorization(), llvm::LegalizationArtifactCombiner::tryFoldImplicitDef(), llvm::tryFoldSPUpdateIntoPushPop(), llvm::LegalizationArtifactCombiner::tryFoldUnmergeCast(), llvm::MCDwarfLineTableHeader::tryGetFile(), llvm::codeview::LazyRandomTypeCollection::tryGetType(), tryInterleave(), tryLowerToSLI(), tryOrrWithShift(), tryPromoteAllocaToVector(), llvm::tryPromoteCall(), trySequenceOfOnes(), trySwapICmpOperands(), trySwitchToSelect(), llvm::VPRecipeBuilder::tryToCreateWidenRecipe(), tryToElideArgumentCopy(), tryToFoldExtendOfConstant(), tryToFoldExtendSelectLoad(), llvm::FastISel::tryToFoldLoad(), llvm::orc::EPCDynamicLibrarySearchGenerator::tryToGenerate(), llvm::orc::ReexportsGenerator::tryToGenerate(), TryToMergeLandingPad(), tryToMergePartialOverlappingStores(), tryToMoveFreeBeforeNullTest(), llvm::SCCPSolver::tryToReplaceWithConstant(), tryToShorten(), tryToShortenBegin(), tryToShortenEnd(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), tryToUnrollLoop(), turnToExplicitForm(), llvm::Twine::Twine(), llvm::WebAssemblyAsmTypeCheck::typeCheck(), llvm::RecTy::typeIsConvertibleTo(), llvm::codeview::TypeServer2Record::TypeServer2Record(), TypeSizeToSizeIndex(), llvm::KnownBits::udiv(), llvm::APInt::udiv(), llvm::APInt::udivrem(), llvm::UIToFPInst::UIToFPInst(), llvm::ulpsFromBoundary(), llvm::MachineInstr::unbundleFromPred(), llvm::MachineInstr::unbundleFromSucc(), llvm::PotentialValuesState< MemberTy >::undefIsContained(), llvm::BitmaskEnumDetail::Underlying(), unescapeQuotedString(), llvm::sys::UnicodeCharSet::UnicodeCharSet(), unifyLoopExits(), llvm::AggressiveAntiDepState::UnionGroups(), llvm::EquivalenceClasses< llvm::Instruction * >::unionSets(), llvm::ConstantRange::unionWith(), llvm::pdb::InputFile::unknown(), llvm::sys::SmartMutex< false >::unlock(), llvm::sys::SmartRWMutex< true >::unlock(), llvm::sys::SmartRWMutex< true >::unlock_shared(), llvm::MemoryPhi::unorderedDeleteIncoming(), llvm::MemoryPhi::unorderedDeleteIncomingIf(), unpack64(), unpackF64OnRV32DSoftABI(), unpackV2S16ToS32(), llvm::AssumptionCache::unregisterAssumption(), llvm::orc::RTDyldObjectLinkingLayer::unregisterJITEventListener(), unrollAndJamCountPragmaValue(), llvm::UnrollAndJamLoop(), unrollCountPragmaValue(), llvm::UnrollLoop(), llvm::OpenMPIRBuilder::unrollLoopPartial(), llvm::UnrollRuntimeLoopRemainder(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::UnrollVectorOverflowOp(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStop(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeValue(), llvm::PBQP::Graph< RegAllocSolverImpl >::unsetSolver(), unsignedImmDecoder(), unswitchBestCondition(), unswitchLoop(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), llvm::MetadataTracking::untrack(), llvm::SHA1::update(), llvm::SHA256::update(), UpdateAnalysisInformation(), updateAsyncFuncPointerContextSize(), llvm::Record::updateClassLoc(), updateCoroFrame(), UpdateCPSRUse(), llvm::MachineRegisterInfo::updateDbgUsersToReg(), UpdateDbgValueInst(), llvm::MachineTraceMetrics::Ensemble::updateDepth(), llvm::mca::Instruction::updateDispatched(), updateDVIWithLocation(), updateDVIWithLocations(), llvm::MemorySSAUpdater::updateForClonedLoop(), llvm::AddrLabelMap::UpdateForRAUWBlock(), llvm::ExecutionEngine::updateGlobalMapping(), updateIDTMetaData(), llvm::updateIndexWPDForExports(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion(), llvm::PointerIntPairInfo< PointerT, IntBits, PtrTraits >::updateInt(), updateLatchBranchWeightsForRemainderLoop(), updateLoadCommandPayloadString(), updateLoopMetadataDebugLocationsImpl(), updateMemprofMetadata(), llvm::SelectionDAG::UpdateNodeOperands(), llvm::HexagonPacketizerList::updateOffset(), updateOperandIfDifferent(), UpdateOperandRegClass(), updateOperands(), llvm::VFShape::updateParam(), llvm::mca::Instruction::updatePending(), llvm::updatePhiNodes(), llvm::PointerIntPairInfo< PointerT, IntBits, PtrTraits >::updatePointer(), llvm::orc::LocalIndirectStubsManager< TargetT >::updatePointer(), updatePostorderSequenceForEdgeInsertion(), llvm::ScheduleDAGMILive::updatePressureDiffs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion(), llvm::DwarfCompileUnit::updateSubprogramScopeDIEImpl(), updateSuccessor(), llvm::MachineBasicBlock::updateTerminator(), llvm::UpgradeCallsToIntrinsic(), llvm::UpgradeIntrinsicCall(), llvm::UpgradeIntrinsicFunction(), UpgradeIntrinsicFunction1(), upgradeLoopTag(), llvm::UpgradeModuleFlags(), UpgradeX86ALIGNIntrinsics(), llvm::KnownBits::urem(), llvm::APInt::urem(), llvm::AArch64RegisterInfo::useFPForScavengingIndex(), llvm::User::User(), llvm::GCStrategy::useRS4GC(), useRVVForFixedLengthVectorVT(), usesExtendedRegister(), llvm::VPUser::usesScalars(), llvm::VPLiveOut::usesScalars(), llvm::VPReplicateRecipe::usesScalars(), llvm::VPBranchOnMaskRecipe::usesScalars(), llvm::VPPredInstPHIRecipe::usesScalars(), llvm::ValID::ValID(), llvm::PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander(), llvm::MachineIRBuilder::validateBinaryOp(), llvm::BasicBlock::validateInstrOrdering(), llvm::MachineIRBuilder::validateSelectOp(), llvm::MachineIRBuilder::validateShiftOp(), llvm::MachineBasicBlock::validateSuccProbs(), llvm::ImutAVLTree< ImutInfo >::validateTree(), llvm::MachineIRBuilder::validateTruncExt(), llvm::MachineIRBuilder::validateUnaryOp(), validThroughout(), llvm::Value::Value(), llvm::json::Value::Value(), llvm::ValueAsMetadata::ValueAsMetadata(), valueCoversEntireFragment(), llvm::ValueHandleBase::ValueIsDeleted(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::object::Elf_GnuHash_Impl< ELFT >::values(), llvm::LLT::vector(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), VectorizePTXValueVTs(), llvm::RegisterBank::verify(), llvm::RegisterBankInfo::PartialMapping::verify(), llvm::RegisterBankInfo::ValueMapping::verify(), llvm::RegisterBankInfo::InstructionMapping::verify(), llvm::MachineTraceMetrics::Ensemble::verify(), llvm::LiveRange::verify(), llvm::LiveInterval::verify(), llvm::LoopInfoBase< BasicBlock, Loop >::verify(), llvm::ScalarEvolution::verify(), llvm::AAPointerInfo::Access::verify(), llvm::PostDominatorTreeWrapperPass::verifyAnalysis(), llvm::MachineTraceMetrics::verifyAnalysis(), llvm::DominatorTreeWrapperPass::verifyAnalysis(), verifyBlocksInRegion(), verifyCompareConds(), llvm::SelectionDAG::VerifyDAGDivergence(), llvm::MemorySSA::verifyDominationNumbers(), llvm::VPlanVerifier::verifyHierarchicalCFG(), llvm::SIInstrInfo::verifyInstruction(), llvm::mca::verifyInstructionEliminated(), llvm::verifyIntrinsicTables(), llvm::LoopBase< BasicBlock, Loop >::verifyLoop(), llvm::LoopBase< BasicBlock, Loop >::verifyLoopNest(), llvm::AnalysisManager< MachineFunction >::verifyNotInvalidated(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::MemorySSA::verifyPrevDefInPhis(), llvm::GVNPass::ValueTable::verifyRemoved(), verifySameBranchInstructions(), llvm::ScheduleDAG::VerifyScheduledDAG(), llvm::ScheduleDAGSDNodes::VerifyScheduledSequence(), VerifySDNode(), verifyTables(), llvm::MachineRegisterInfo::verifyUseList(), llvm::versionCallSite(), llvm::LoopVersioning::versionLoop(), llvm::VFRange::VFRange(), viewRegionInfo(), violatesLegacyMultiExitLoopCheck(), llvm::Register::virtReg2Index(), llvm::BitTracker::visit(), Node::visit(), llvm::objcopy::elf::IHexSectionWriterBase::visit(), llvm::objcopy::elf::IHexSectionWriter::visit(), llvm::xray::RecordInitializer::visit(), llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >::visit(), llvm::sroa::AllocaSliceRewriter::visit(), llvm::Interpreter::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombinerImpl::visitAllocSite(), llvm::InstCombinerImpl::visitAnd(), llvm::Interpreter::visitAShr(), llvm::InstCombinerImpl::visitAtomicRMWInst(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), visitDomSubTree(), llvm::jitlink::loongarch::GOTTableManager::visitEdge(), llvm::jitlink::i386::GOTTableManager::visitEdge(), llvm::jitlink::aarch64::GOTTableManager::visitEdge(), llvm::jitlink::x86_64::GOTTableManager::visitEdge(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::SelectionDAGBuilder::visitJumpTable(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::InstCombinerImpl::visitLoadInst(), llvm::InstCombinerImpl::visitLShr(), llvm::Interpreter::visitLShr(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberEnd(), llvm::PtrUseVisitor< SliceBuilder >::visitPtr(), llvm::InstCombinerImpl::visitPtrToInt(), llvm::pdb::DbiStream::visitSectionContributions(), llvm::InstCombinerImpl::visitSExt(), llvm::Interpreter::visitShl(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::InstCombinerImpl::visitStoreInst(), llvm::InstCombinerImpl::visitSub(), llvm::SelectionDAGBuilder::visitSwitchCase(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::codeview::SymbolSerializer::visitSymbolBegin(), llvm::codeview::SymbolDeserializer::visitSymbolBegin(), llvm::codeview::SymbolSerializer::visitSymbolEnd(), llvm::codeview::SymbolDeserializer::visitSymbolEnd(), llvm::InstCombinerImpl::visitTrunc(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), llvm::codeview::TypeDeserializer::visitTypeBegin(), llvm::codeview::TypeRecordMapping::visitTypeEnd(), llvm::codeview::TypeDeserializer::visitTypeEnd(), llvm::InstCombinerImpl::visitUnconditionalBranchInst(), llvm::InstCombinerImpl::visitUnreachableInst(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), llvm::VLIWResourceModel::VLIWResourceModel(), llvm::VPBaseLoadStoreSDNode::VPBaseLoadStoreSDNode(), llvm::VPBlendRecipe::VPBlendRecipe(), llvm::VPGatherScatterSDNode::VPGatherScatterSDNode(), llvm::VPlanTransforms::VPInstructionsToVPRecipes(), llvm::VPReductionPHIRecipe::VPReductionPHIRecipe(), llvm::VPRegionBlock::VPRegionBlock(), llvm::ThreadPool::wait(), wasEscaped(), llvm::WebAssembly::wasmSymbolSetType(), llvm::WholeProgramDevirtPass::WholeProgramDevirtPass(), widen96To128(), widen_1(), widen_8_16(), widenAbs(), widenCtPop(), llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad(), llvm::LegalizerHelper::widenScalar(), llvm::widenShuffleMaskElts(), widenSubVector(), llvm::LegacyLegalizerInfo::widenToLargerTypesAndNarrowToLargest(), widenVec(), llvm::widenWidenableBranch(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::orc::JITDylib::withLinkOrderDo(), llvm::orc::ThreadSafeModule::withModuleDo(), llvm::SparseBitVectorElement< ElementSize >::word(), llvm::coverage::CoverageMappingWriter::write(), llvm::orc::shared::SPSOutputBuffer::write(), llvm::msgpack::Writer::write(), llvm::StringTableBuilder::write(), llvm::TimeTraceProfiler::write(), llvm::raw_ostream::write(), llvm::write32AArch64Ldr(), llvm::writeArchiveToStream(), WriteAsOperandInternal(), llvm::support::endian::writeAtBitAlignment(), llvm::ifs::writeBinaryStub(), writeCOFF(), WriteConstantInternal(), llvm::sampleprof::SampleProfileWriterBinary::writeContextIdx(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeCSNameTableSection(), llvm::msgpack::Writer::writeExt(), writeFragment(), llvm::MCAssembler::writeFragmentPadding(), writeFunctionHeapProfileRecords(), writeFunctionTypeMetadataRecords(), llvm::sampleprof::SampleProfileWriterBinary::writeHeader(), writeHexDigit(), llvm::writeIndex(), llvm::orc::OrcAArch64::writeIndirectStubsBlock(), llvm::orc::OrcX86_64_Base::writeIndirectStubsBlock(), llvm::orc::OrcI386::writeIndirectStubsBlock(), llvm::orc::OrcMips32_Base::writeIndirectStubsBlock(), llvm::orc::OrcMips64::writeIndirectStubsBlock(), llvm::orc::OrcRiscv64::writeIndirectStubsBlock(), llvm::orc::OrcLoongArch64::writeIndirectStubsBlock(), llvm::codeview::ContinuationRecordBuilder::writeMemberType(), llvm::dxil::BitcodeWriter::writeModule(), llvm::BitcodeWriter::writeModule(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeNameTableSection(), llvm::AVRAsmBackend::writeNopData(), llvm::MachObjectWriter::writeObject(), llvm::orc::EPCIndirectionUtils::writeResolverBlock(), llvm::orc::OrcI386::writeResolverCode(), llvm::MachObjectWriter::writeSection(), llvm::objcopy::elf::IHexSectionWriterBase::writeSection(), llvm::MCAssembler::writeSectionData(), llvm::gsym::FileWriter::writeSLEB(), llvm::mca::ReadState::writeStartEvent(), llvm::BitcodeWriter::writeStrtab(), llvm::BitcodeWriter::writeSymtab(), llvm::BitcodeWriter::writeThinLinkBitcode(), writeToResolutionFile(), llvm::orc::OrcI386::writeTrampolines(), llvm::orc::OrcMips32_Base::writeTrampolines(), llvm::gsym::FileWriter::writeULEB(), llvm::object::writeUniversalBinaryToStream(), writeWithCommas(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), llvm::X86RegisterBankInfo::X86RegisterBankInfo(), X86SelectAddress(), llvm::X86TargetLowering::X86TargetLowering(), llvm::object::XCOFFSymbolRef::XCOFFSymbolRef(), llvm::reassociate::XorOpnd::XorOpnd(), llvm::InstructionWorklist::zap(), llvm::ConstantRange::zeroExtend(), llvm::APInt::zext(), llvm::ZExtInst::ZExtInst(), llvm::zip_equal(), llvm::zip_first(), llvm::AddrLabelMap::~AddrLabelMap(), llvm::ms_demangle::ArenaAllocator::~ArenaAllocator(), llvm::ArrayRecycler< llvm::MachineOperand >::~ArrayRecycler(), llvm::AsmPrinter::~AsmPrinter(), llvm::BasicBlock::~BasicBlock(), llvm::BitcodeWriter::~BitcodeWriter(), llvm::BitstreamWriter::~BitstreamWriter(), llvm::CallGraphNode::~CallGraphNode(), llvm::ChangeReporter< IRDataT< EmptyData > >::~ChangeReporter(), llvm::SelectionDAG::DAGUpdateListener::~DAGUpdateListener(), llvm::orc::ExecutionSession::~ExecutionSession(), llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc::~FinalizedAlloc(), llvm::TrailingObjects< BaseTy, TrailingTys >::FixedSizeStorageOwner::~FixedSizeStorageOwner(), llvm::InlineAdvice::~InlineAdvice(), llvm::InlineAdvisor::~InlineAdvisor(), llvm::Instruction::~Instruction(), llvm::jitlink::InProcessMemoryManager::IPInFlightAlloc::~IPInFlightAlloc(), llvm::parallel::detail::Latch::~Latch(), llvm::LazyValueInfoWrapperPass::~LazyValueInfoWrapperPass(), llvm::LLVMContextImpl::~LLVMContextImpl(), llvm::orc::ObjectLinkingLayer::~ObjectLinkingLayer(), llvm::OpenMPIRBuilder::~OpenMPIRBuilder(), llvm::json::OStream::~OStream(), llvm::PredicateInfo::~PredicateInfo(), llvm::PrettyStackTraceEntry::~PrettyStackTraceEntry(), llvm::PrintCrashIRInstrumentation::~PrintCrashIRInstrumentation(), llvm::PrintIRInstrumentation::~PrintIRInstrumentation(), llvm::raw_ostream::~raw_ostream(), llvm::Recycler< FinalizedAllocInfo, sizeof(FinalizedAllocInfo), alignof(FinalizedAllocInfo) >::~Recycler(), llvm::RefCountedBase< Derived >::~RefCountedBase(), llvm::ReplaceableMetadataImpl::~ReplaceableMetadataImpl(), llvm::orc::RTDyldObjectLinkingLayer::~RTDyldObjectLinkingLayer(), llvm::ScalarEvolution::~ScalarEvolution(), llvm::SCEVExpander::~SCEVExpander(), llvm::ScopedHashTable< K, V, DenseMapInfo< K >, MallocAllocator >::~ScopedHashTable(), llvm::ScopedHashTableScope< K, V, KInfo, AllocatorTy >::~ScopedHashTableScope(), AbstractManglingParser< Derived, Alloc >::ScopedTemplateParamList::~ScopedTemplateParamList(), llvm::SelectionDAG::~SelectionDAG(), BoUpSLP::ShuffleInstructionBuilder::~ShuffleInstructionBuilder(), llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::~SimpleExecutorDylibManager(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::~SimpleExecutorMemoryManager(), llvm::orc::SimpleRemoteEPC::~SimpleRemoteEPC(), llvm::SoftInstrProfErrors::~SoftInstrProfErrors(), llvm::orc::SymbolStringPool::~SymbolStringPool(), llvm::TaskQueue::~TaskQueue(), llvm::sys::fs::TempFile::~TempFile(), llvm::ThreadSafeRefCountedBase< ResourceTracker >::~ThreadSafeRefCountedBase(), llvm::Value::~Value(), llvm::ValueSymbolTable::~ValueSymbolTable(), llvm::VPDef::~VPDef(), and llvm::VPValue::~VPValue().
INITIALIZE_PASS()
INITIALIZE_PASS (SILowerControlFlow , DEBUG_TYPE , "SI lower control flow" , false , false) &
isSimpleIf()
static bool isSimpleIf (const MachineInstr & MI, const MachineRegisterInfo * MRI) static
Definition at line 196 of file SILowerControlFlow.cpp.
References llvm::MachineInstr::getOpcode(), MI, MRI, llvm::MachineRegisterInfo::use_instr_nodbg_begin(), and llvm::MachineRegisterInfo::use_instr_nodbg_end().
setIsDead()
ImpDefSCC setIsDead (IsDead)
Variable Documentation
IsDead
bool IsDead
Initial value:
{
  MachineOperand &ImpDefSCC = MI.getOperand(3)
Definition at line 168 of file SILowerControlFlow.cpp.
Referenced by llvm::rdf::DeadCodeElimination::collect(), llvm::ReachingDefAnalysis::collectKilledOperands(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::Liveness::getAllReachedUses(), rematerializeCheapDef(), and swapRegAndNonRegOperand().
RemoveRedundantEndcf
cl::opt<bool> RemoveRedundantEndcf("amdgpu-remove-redundant-endcf", cl::init(true), cl::ReallyHidden) static