LLVM: lib/Target/AMDGPU/SIMachineFunctionInfo.cpp File Reference
SIMachineFunctionInfo.cpp File Reference
#include "SIMachineFunctionInfo.h"
#include "AMDGPUTargetMachine.h"
#include "AMDGPUSubtarget.h"
#include "SIRegisterInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/MIRParser/MIParser.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include <cassert>
#include <optional>
#include <vector>
Macros
#define MAX_LANES 64
Functions
const GCNTargetMachine & getTM (const GCNSubtarget *STI)
static yaml::StringValue regToString (Register Reg, const TargetRegisterInfo &TRI)
static std::optional< yaml::SIArgumentInfo > convertArgumentInfo (const AMDGPUFunctionArgInfo &ArgInfo, const TargetRegisterInfo &TRI)
Macro Definition Documentation
MAX_LANES
#define MAX_LANES 64
Definition at line 28 of file SIMachineFunctionInfo.cpp.
Function Documentation
convertArgumentInfo()
static std::optional<yaml::SIArgumentInfo> convertArgumentInfo (const AMDGPUFunctionArgInfo & ArgInfo, const TargetRegisterInfo & TRI) static
Definition at line 572 of file SIMachineFunctionInfo.cpp.
References Arg, llvm::yaml::SIArgument::createArgument(), llvm::yaml::SIArgumentInfo::DispatchID, llvm::yaml::SIArgumentInfo::DispatchPtr, llvm::yaml::SIArgumentInfo::FlatScratchInit, llvm::yaml::SIArgumentInfo::ImplicitArgPtr, llvm::yaml::SIArgumentInfo::ImplicitBufferPtr, llvm::yaml::SIArgumentInfo::KernargSegmentPtr, llvm::yaml::SIArgumentInfo::LDSKernelId, llvm::yaml::SIArgument::Mask, OS, llvm::printReg(), llvm::yaml::SIArgumentInfo::PrivateSegmentBuffer, llvm::yaml::SIArgumentInfo::PrivateSegmentSize, llvm::yaml::SIArgumentInfo::PrivateSegmentWaveByteOffset, llvm::yaml::SIArgumentInfo::QueuePtr, llvm::yaml::SIArgument::RegisterName, llvm::yaml::SIArgument::StackOffset, TRI, llvm::yaml::StringValue::Value, llvm::yaml::SIArgumentInfo::WorkGroupIDX, llvm::yaml::SIArgumentInfo::WorkGroupIDY, llvm::yaml::SIArgumentInfo::WorkGroupIDZ, llvm::yaml::SIArgumentInfo::WorkGroupInfo, llvm::yaml::SIArgumentInfo::WorkItemIDX, llvm::yaml::SIArgumentInfo::WorkItemIDY, and llvm::yaml::SIArgumentInfo::WorkItemIDZ.
getTM()
const GCNTargetMachine& getTM (const GCNSubtarget * STI)
Definition at line 32 of file SIMachineFunctionInfo.cpp.
References llvm::GCNSubtarget::getTargetLowering(), and llvm::TargetLoweringBase::getTargetMachine().
regToString()
static yaml::StringValue regToString (Register Reg, const TargetRegisterInfo & TRI) static
Definition at line 561 of file SIMachineFunctionInfo.cpp.
References OS, llvm::printReg(), TRI, and llvm::yaml::StringValue::Value.
Referenced by llvm::yaml::SIMachineFunctionInfo::SIMachineFunctionInfo().