LLVM: lib/DebugInfo/CodeView/SimpleTypeSerializer.cpp File Reference
SimpleTypeSerializer.cpp File Reference
#include "llvm/DebugInfo/CodeView/SimpleTypeSerializer.h"
#include "llvm/DebugInfo/CodeView/CVRecord.h"
#include "llvm/DebugInfo/CodeView/RecordSerialization.h"
#include "llvm/DebugInfo/CodeView/TypeRecordMapping.h"
#include "llvm/Support/BinaryStreamWriter.h"
#include "llvm/DebugInfo/CodeView/CodeViewTypes.def"
Macros
#define TYPE_RECORD(EnumName, EnumVal, Name)
#define TYPE_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName)
#define MEMBER_RECORD(EnumName, EnumVal, Name)
#define MEMBER_RECORD_ALIAS(EnumName, EnumVal, Name, AliasName)
Functions
static void addPadding (BinaryStreamWriter &Writer)
Macro Definition Documentation
MEMBER_RECORD
#define MEMBER_RECORD (EnumName, EnumVal, Name)
Definition at line 66 of file SimpleTypeSerializer.cpp.
MEMBER_RECORD_ALIAS
#define MEMBER_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName)
Definition at line 67 of file SimpleTypeSerializer.cpp.
TYPE_RECORD
#define TYPE_RECORD (EnumName, EnumVal, Name)
Value:
  template ArrayRef<uint8_t> llvm::codeview::SimpleTypeSerializer::serialize(  \
      Name##Record &Record);
Definition at line 62 of file SimpleTypeSerializer.cpp.
TYPE_RECORD_ALIAS
#define TYPE_RECORD_ALIAS (EnumName, EnumVal, Name, AliasName)
Definition at line 65 of file SimpleTypeSerializer.cpp.
Function Documentation
addPadding()
static void addPadding (BinaryStreamWriter & Writer) static
Definition at line 18 of file SimpleTypeSerializer.cpp.
References Align, llvm::cantFail(), llvm::BinaryStreamWriter::getOffset(), and llvm::BinaryStreamWriter::writeInteger().
Referenced by llvm::codeview::SimpleTypeSerializer::serialize().