LLVM: lib/Target/SPIRV/SPIRVSubtarget.cpp File Reference
SPIRVSubtarget.cpp File Reference
#include "SPIRVSubtarget.h"
#include "SPIRV.h"
#include "SPIRVGlobalRegistry.h"
#include "SPIRVLegalizerInfo.h"
#include "SPIRVRegisterBankInfo.h"
#include "SPIRVTargetMachine.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/TargetParser/Host.h"
#include "SPIRVGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "spirv-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Functions
static bool isAtLeastVer (uint32_t Target, uint32_t VerToCompareTo)
static unsigned computePointerSize (const Triple &TT)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-subtarget"
Definition at line 24 of file SPIRVSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 27 of file SPIRVSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 26 of file SPIRVSubtarget.cpp.
Function Documentation
computePointerSize()
static unsigned computePointerSize (const Triple & TT) static
Definition at line 35 of file SPIRVSubtarget.cpp.
References assert(), and llvm::Triple::spirv32.
isAtLeastVer()
static bool isAtLeastVer (uint32_t Target, uint32_t VerToCompareTo) static
Definition at line 31 of file SPIRVSubtarget.cpp.
Referenced by llvm::SPIRVSubtarget::canDirectlyComparePointers(), llvm::SPIRVSubtarget::isAtLeastOpenCLVer(), and llvm::SPIRVSubtarget::isAtLeastSPIRVVer().