LLVM: lib/Target/SPIRV/MCTargetDesc/SPIRVMCTargetDesc.cpp File Reference
SPIRVMCTargetDesc.cpp File Reference
#include "SPIRVMCTargetDesc.h"
#include "SPIRVInstPrinter.h"
#include "SPIRVMCAsmInfo.h"
#include "SPIRVTargetStreamer.h"
#include "TargetInfo/SPIRVTargetInfo.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "SPIRVGenInstrInfo.inc"
#include "SPIRVGenSubtargetInfo.inc"
#include "SPIRVGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createSPIRVMCInstrInfo ()
static MCRegisterInfo * createSPIRVMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createSPIRVMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCStreamer * createSPIRVMCStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCTargetStreamer * createTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &, MCInstPrinter *, bool)
static MCInstPrinter * createSPIRVMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCInstrAnalysis * createSPIRVInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSPIRVTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 25 of file SPIRVMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 24 of file SPIRVMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 31 of file SPIRVMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 28 of file SPIRVMCTargetDesc.cpp.
Function Documentation
createSPIRVInstrAnalysis()
static MCInstrAnalysis* createSPIRVInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 86 of file SPIRVMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeSPIRVTargetMC().
createSPIRVMCInstPrinter()
static MCInstPrinter* createSPIRVMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 67 of file SPIRVMCTargetDesc.cpp.
References assert(), and MRI.
Referenced by LLVMInitializeSPIRVTargetMC().
createSPIRVMCInstrInfo()
static MCInstrInfo* createSPIRVMCInstrInfo () static
Definition at line 36 of file SPIRVMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeSPIRVTargetMC().
createSPIRVMCRegisterInfo()
static MCRegisterInfo* createSPIRVMCRegisterInfo (const Triple & TT) static
Definition at line 42 of file SPIRVMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeSPIRVTargetMC().
createSPIRVMCStreamer()
static MCStreamer* createSPIRVMCStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 53 of file SPIRVMCTargetDesc.cpp.
References llvm::createSPIRVStreamer(), Emitter, and move.
Referenced by LLVMInitializeSPIRVTargetMC().
createSPIRVMCSubtargetInfo()
static MCSubtargetInfo* createSPIRVMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 48 of file SPIRVMCTargetDesc.cpp.
References llvm::X86AS::FS.
Referenced by LLVMInitializeSPIRVTargetMC().
createTargetAsmStreamer()
static MCTargetStreamer* createTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & , MCInstPrinter * , bool) static
Definition at line 61 of file SPIRVMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeSPIRVTargetMC().
LLVMInitializeSPIRVTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSPIRVTargetMC ()
Definition at line 90 of file SPIRVMCTargetDesc.cpp.
References llvm::createSPIRVAsmBackend(), createSPIRVInstrAnalysis(), llvm::createSPIRVMCCodeEmitter(), createSPIRVMCInstPrinter(), createSPIRVMCInstrInfo(), createSPIRVMCRegisterInfo(), createSPIRVMCStreamer(), createSPIRVMCSubtargetInfo(), createTargetAsmStreamer(), llvm::getTheSPIRV32Target(), llvm::getTheSPIRV64Target(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterSPIRVStreamer(), and X.