LLVM: lib/Target/SPIRV/SPIRVPrepareFunctions.cpp File Reference
SPIRVPrepareFunctions.cpp File Reference
#include "SPIRV.h"
#include "SPIRVTargetMachine.h"
#include "SPIRVUtils.h"
#include "llvm/CodeGen/IntrinsicLowering.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/LowerMemIntrinsics.h"
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
void llvm::initializeSPIRVPrepareFunctionsPass (PassRegistry &)
INITIALIZE_PASS (SPIRVPrepareFunctions, "prepare-functions", "SPIRV prepare functions", false, false) Function *SPIRVPrepareFunctions
std::string lowerLLVMIntrinsicName (IntrinsicInst *II)
static Function * getOrCreateFunction (Module *M, Type *RetTy, ArrayRef< Type * > ArgTypes, StringRef Name)
static void lowerIntrinsicToFunction (Module *M, IntrinsicInst *Intrinsic)
static void lowerFunnelShifts (Module *M, IntrinsicInst *FSHIntrinsic)
static void buildUMulWithOverflowFunc (Module *M, Function *UMulFunc)
static void lowerUMulWithOverflow (Module *M, IntrinsicInst *UMulIntrinsic)
static void substituteIntrinsicCalls (Module *M, Function *F)
Function Documentation
buildUMulWithOverflowFunc()
static void buildUMulWithOverflowFunc (Module * M, Function * UMulFunc) static
Definition at line 268 of file SPIRVPrepareFunctions.cpp.
References llvm::BasicBlock::Create(), llvm::IRBuilderBase::CreateICmpNE(), llvm::IRBuilderBase::CreateInsertValue(), llvm::IRBuilderBase::CreateNUWMul(), llvm::IRBuilderBase::CreateRet(), llvm::IRBuilderBase::CreateUDiv(), llvm::Function::empty(), llvm::PoisonValue::get(), llvm::Function::getArg(), llvm::Function::getReturnType(), M, and Mul.
Referenced by lowerUMulWithOverflow().
getOrCreateFunction()
static Function* getOrCreateFunction (Module * M, Type * RetTy, ArrayRef< Type * > ArgTypes, StringRef Name) static
Definition at line 131 of file SPIRVPrepareFunctions.cpp.
References llvm::Function::Create(), llvm::GlobalValue::ExternalLinkage, F, llvm::FunctionType::get(), M, llvm::Function::setCallingConv(), llvm::GlobalValue::setDSOLocal(), and llvm::CallingConv::SPIR_FUNC.
Referenced by lowerFunnelShifts(), and lowerUMulWithOverflow().
INITIALIZE_PASS()
INITIALIZE_PASS (SPIRVPrepareFunctions , "prepare-functions" , "SPIRV prepare functions" , false , false)
Definition at line 57 of file SPIRVPrepareFunctions.cpp.
References llvm::NamedMDNode::addOperand(), llvm::any_of(), Arg, llvm::Function::arg_begin(), B, llvm::CloneFunctionInto(), llvm::Function::Create(), F, llvm::FunctionType::get(), llvm::MDString::get(), llvm::MDNode::get(), llvm::Function::getFunctionType(), llvm::Value::getName(), llvm::LocalChangesOnly, llvm::make_early_inc_range(), and llvm::Value::takeName().
lowerFunnelShifts()
static void lowerFunnelShifts (Module * M, IntrinsicInst * FSHIntrinsic) static
Definition at line 208 of file SPIRVPrepareFunctions.cpp.
References llvm::BitWidth, llvm::BasicBlock::Create(), llvm::IRBuilderBase::CreateLShr(), llvm::IRBuilderBase::CreateOr(), llvm::IRBuilderBase::CreateRet(), llvm::IRBuilderBase::CreateShl(), llvm::IRBuilderBase::CreateSub(), llvm::IRBuilderBase::CreateURem(), llvm::IRBuilderBase::CreateVectorSplat(), llvm::Function::empty(), llvm::Function::getArg(), llvm::VectorType::getElementType(), llvm::CallBase::getFunctionType(), llvm::IRBuilderBase::getInt(), llvm::Type::getIntegerBitWidth(), llvm::IntrinsicInst::getIntrinsicID(), llvm::FixedVectorType::getNumElements(), getOrCreateFunction(), llvm::FunctionType::getReturnType(), llvm::Function::getReturnType(), lowerLLVMIntrinsicName(), M, llvm::FunctionType::params(), and llvm::CallBase::setCalledFunction().
Referenced by substituteIntrinsicCalls().
lowerIntrinsicToFunction()
static void lowerIntrinsicToFunction (Module * M, IntrinsicInst * Intrinsic) static
Definition at line 145 of file SPIRVPrepareFunctions.cpp.
References assert(), llvm::BasicBlock::Create(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilderBase::CreateRet(), llvm::IRBuilderBase::CreateRetVoid(), llvm::expandMemSetAsLoop(), F, R600_InstFlag::FC, llvm::IntrinsicLowering::LowerIntrinsicCall(), lowerLLVMIntrinsicName(), M, and llvm::Value::setName().
Referenced by substituteIntrinsicCalls().
lowerLLVMIntrinsicName()
std::string lowerLLVMIntrinsicName (IntrinsicInst * II)
Definition at line 122 of file SPIRVPrepareFunctions.cpp.
References assert(), llvm::CallBase::getCalledFunction(), llvm::Value::getName(), replace(), and llvm::StringRef::str().
Referenced by lowerFunnelShifts(), lowerIntrinsicToFunction(), and lowerUMulWithOverflow().
lowerUMulWithOverflow()
static void lowerUMulWithOverflow (Module * M, IntrinsicInst * UMulIntrinsic) static
Definition at line 291 of file SPIRVPrepareFunctions.cpp.
References buildUMulWithOverflowFunc(), llvm::CallBase::getFunctionType(), getOrCreateFunction(), llvm::FunctionType::getReturnType(), lowerLLVMIntrinsicName(), M, llvm::FunctionType::params(), and llvm::CallBase::setCalledFunction().
Referenced by substituteIntrinsicCalls().
substituteIntrinsicCalls()
static void substituteIntrinsicCalls (Module * M, Function * F) static
Definition at line 304 of file SPIRVPrepareFunctions.cpp.
References BB, F, I, llvm::Function::isIntrinsic(), lowerFunnelShifts(), lowerIntrinsicToFunction(), lowerUMulWithOverflow(), and M.