LLVM: lib/Target/SPIRV/SPIRVInstructionSelector.cpp File Reference
SPIRVInstructionSelector.cpp File Reference
#include "SPIRV.h"
#include "SPIRVGlobalRegistry.h"
#include "SPIRVInstrInfo.h"
#include "SPIRVRegisterBankInfo.h"
#include "SPIRVRegisterInfo.h"
#include "SPIRVTargetMachine.h"
#include "SPIRVUtils.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelector.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelectorImpl.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/Support/Debug.h"
#include "SPIRVGenGlobalISel.inc"
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "spirv-isel"
#define GET_GLOBALISEL_PREDICATE_BITSET
#define GET_GLOBALISEL_PREDICATES_DECL
#define GET_GLOBALISEL_TEMPORARIES_DECL
#define GET_GLOBALISEL_IMPL
#define GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Typedefs
using ExtInstList = std::vector< std::pair< SPIRV::InstructionSet::InstructionSet, uint32_t > >
Functions
static bool isImm (const MachineOperand &MO, MachineRegisterInfo *MRI)
bool isTypeFoldingSupported (unsigned Opcode)
static SPIRV::Scope::Scope getScope (SyncScope::ID Ord)
static void addMemoryOperands (MachineMemOperand *MemOp, MachineInstrBuilder &MIB)
static void addMemoryOperands (uint64_t Flags, MachineInstrBuilder &MIB)
static bool isGenericCastablePtr (SPIRV::StorageClass::StorageClass SC)
static unsigned getFCmpOpcode (unsigned PredNum)
static unsigned getICmpOpcode (unsigned PredNum)
static unsigned getPtrCmpOpcode (unsigned Pred)
static unsigned getBoolCmpOpcode (unsigned PredNum)
static int64_t foldImm (const MachineOperand &MO, MachineRegisterInfo *MRI)
InstructionSelector * llvm::createSPIRVInstructionSelector (const SPIRVTargetMachine &TM, const SPIRVSubtarget &Subtarget, const RegisterBankInfo &RBI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-isel"
Definition at line 30 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_IMPL
#define GET_GLOBALISEL_IMPL
Definition at line 185 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATE_BITSET
#define GET_GLOBALISEL_PREDICATE_BITSET
Definition at line 41 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATES_DECL
#define GET_GLOBALISEL_PREDICATES_DECL
Definition at line 64 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_PREDICATES_INIT
GET_GLOBALISEL_TEMPORARIES_DECL
#define GET_GLOBALISEL_TEMPORARIES_DECL
Definition at line 68 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_TEMPORARIES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Typedef Documentation
ExtInstList
using ExtInstList = std::vector<std::pair<SPIRV::InstructionSet::InstructionSet, uint32_t> >
Definition at line 37 of file SPIRVInstructionSelector.cpp.
Function Documentation
addMemoryOperands() [1/2]
static void addMemoryOperands (MachineMemOperand * MemOp, MachineInstrBuilder & MIB) static
Definition at line 562 of file SPIRVInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm(), and llvm::None.
addMemoryOperands() [2/2]
static void addMemoryOperands (uint64_t Flags, MachineInstrBuilder & MIB) static
Definition at line 579 of file SPIRVInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm(), and llvm::None.
foldImm()
static int64_t foldImm (const MachineOperand & MO, MachineRegisterInfo * MRI) static
Definition at line 1228 of file SPIRVInstructionSelector.cpp.
References assert(), llvm::MachineOperand::getCImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), llvm::ConstantInt::getZExtValue(), and MRI.
getBoolCmpOpcode()
static unsigned getBoolCmpOpcode (unsigned PredNum) static
Definition at line 934 of file SPIRVInstructionSelector.cpp.
References llvm_unreachable.
getFCmpOpcode()
static unsigned getFCmpOpcode (unsigned PredNum) static
Definition at line 858 of file SPIRVInstructionSelector.cpp.
References llvm_unreachable.
getICmpOpcode()
static unsigned getICmpOpcode (unsigned PredNum) static
Definition at line 894 of file SPIRVInstructionSelector.cpp.
References llvm_unreachable.
getPtrCmpOpcode()
static unsigned getPtrCmpOpcode (unsigned Pred) static
Definition at line 922 of file SPIRVInstructionSelector.cpp.
References llvm_unreachable.
getScope()
static SPIRV::Scope::Scope getScope (SyncScope::ID Ord) static
Definition at line 551 of file SPIRVInstructionSelector.cpp.
References llvm_unreachable, SingleThread, and llvm::SyncScope::System.
Referenced by llvm::DILocation::cloneWithDiscriminator(), LLVMDILocationGetScope(), and LLVMDIVariableGetScope().
isGenericCastablePtr()
static bool isGenericCastablePtr (SPIRV::StorageClass::StorageClass SC) static
Definition at line 784 of file SPIRVInstructionSelector.cpp.
References llvm::PPCISD::SC.
isImm()
static bool isImm (const MachineOperand & MO, MachineRegisterInfo * MRI) static
Definition at line 1218 of file SPIRVInstructionSelector.cpp.
References assert(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineOperand::isReg(), and MRI.
Referenced by llvm::VEInstrInfo::insertBranch(), llvm::HexagonInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::SIInstrInfo::insertVectorSelect(), XtensaOperand::isImm12(), XtensaOperand::isImm12m(), XtensaOperand::isImm16_31(), XtensaOperand::isImm1_16(), XtensaOperand::isImm8(), XtensaOperand::isImm8_sh8(), XtensaOperand::isImm8n_7(), IsMemoryAssignmentError(), isMergeableLdStUpdate(), XtensaOperand::isOffset4m32(), XtensaOperand::isOffset8m16(), XtensaOperand::isOffset8m32(), XtensaOperand::isOffset8m8(), llvm::MachineInstr::isOperandSubregIdx(), XtensaOperand::isShimm1_31(), XtensaOperand::isUimm4(), XtensaOperand::isUimm5(), llvm::HexagonInstrInfo::reverseBranchCondition(), and llvm::SIInstrInfo::reverseBranchCondition().
isTypeFoldingSupported()
bool isTypeFoldingSupported (unsigned Opcode)
Definition at line 53 of file SPIRVLegalizerInfo.cpp.