LLVM: lib/Target/SPIRV/MCTargetDesc/SPIRVInstPrinter.cpp File Reference
SPIRVInstPrinter.cpp File Reference
#include "SPIRVInstPrinter.h"
#include "SPIRV.h"
#include "SPIRVBaseInfo.h"
#include "llvm/CodeGen/Register.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "SPIRVGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static void printExpr (const MCExpr *Expr, raw_ostream &O)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 29 of file SPIRVInstPrinter.cpp.
Function Documentation
printExpr()
static void printExpr (const MCExpr * Expr, raw_ostream & O) static
Definition at line 242 of file SPIRVInstPrinter.cpp.
References assert(), llvm::MCSymbolRefExpr::getKind(), llvm::RISCVFenceField::O, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::SPIRVInstPrinter::printOperand().