LLVM: lib/Target/SPIRV/SPIRVTargetMachine.cpp File Reference
SPIRVTargetMachine.cpp File Reference
#include "SPIRVTargetMachine.h"
#include "SPIRV.h"
#include "SPIRVCallLowering.h"
#include "SPIRVGlobalRegistry.h"
#include "SPIRVLegalizerInfo.h"
#include "SPIRVTargetObjectFile.h"
#include "SPIRVTargetTransformInfo.h"
#include "TargetInfo/SPIRVTargetInfo.h"
#include "llvm/CodeGen/GlobalISel/IRTranslator.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
#include "llvm/CodeGen/GlobalISel/Legalizer.h"
#include "llvm/CodeGen/GlobalISel/RegBankSelect.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Pass.h"
#include "llvm/Target/TargetOptions.h"
#include <optional>
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSPIRVTarget ()
static std::string computeDataLayout (const Triple &TT)
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & TT) static
Definition at line 46 of file SPIRVTargetMachine.cpp.
References llvm::Triple::spirv32.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 55 of file SPIRVTargetMachine.cpp.
References llvm::Reloc::PIC_, and llvm::AArch64::RM.
LLVMInitializeSPIRVTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSPIRVTarget ()
Definition at line 36 of file SPIRVTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheSPIRV32Target(), llvm::getTheSPIRV64Target(), llvm::initializeGlobalISel(), llvm::initializeSPIRVModuleAnalysisPass(), X, and Y.