LLVM: lib/Target/SPIRV/SPIRVCallLowering.cpp File Reference
SPIRVCallLowering.cpp File Reference
#include "SPIRVCallLowering.h"
#include "MCTargetDesc/SPIRVBaseInfo.h"
#include "SPIRV.h"
#include "SPIRVBuiltins.h"
#include "SPIRVGlobalRegistry.h"
#include "SPIRVISelLowering.h"
#include "SPIRVRegisterInfo.h"
#include "SPIRVSubtarget.h"
#include "SPIRVUtils.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/Support/ModRef.h"
Functions
static uint32_t getFunctionControl (const Function &F)
static ConstantInt * getConstInt (MDNode *MD, unsigned NumOp)
static FunctionType * getOriginalFunctionType (const Function &F)
static MDString * getKernelArgAttribute (const Function &KernelFunction, unsigned ArgIdx, const StringRef AttributeName)
static SPIRV::AccessQualifier::AccessQualifier getArgAccessQual (const Function &F, unsigned ArgIdx)
static std::vector< SPIRV::Decoration::Decoration > getKernelArgTypeQual (const Function &KernelFunction, unsigned ArgIdx)
static Type * getArgType (const Function &F, unsigned ArgIdx)
Function Documentation
getArgAccessQual()
static SPIRV::AccessQualifier::AccessQualifier getArgAccessQual (const Function & F, unsigned ArgIdx) static
Definition at line 172 of file SPIRVCallLowering.cpp.
References llvm::StringRef::compare(), F, getKernelArgAttribute(), llvm::MDString::getString(), and llvm::CallingConv::SPIR_KERNEL.
Referenced by llvm::SPIRVCallLowering::lowerFormalArguments().
getArgType()
static Type* getArgType (const Function & F, unsigned ArgIdx) static
Definition at line 197 of file SPIRVCallLowering.cpp.
References llvm::StructType::create(), llvm::StringRef::endswith(), F, getKernelArgAttribute(), getOriginalFunctionType(), llvm::FunctionType::getParamType(), llvm::MDString::getString(), llvm::StructType::getTypeByName(), llvm::isSpecialOpaqueType(), llvm::CallingConv::SPIR_KERNEL, and llvm::StringRef::str().
Referenced by llvm::SPIRVCallLowering::lowerFormalArguments().
getConstInt()
static ConstantInt* getConstInt (MDNode * MD, unsigned NumOp) static
Definition at line 70 of file SPIRVCallLowering.cpp.
References llvm::MDNode::getNumOperands(), and llvm::MDNode::getOperand().
Referenced by getOriginalFunctionType().
getFunctionControl()
static uint32_t getFunctionControl (const Function & F) static
Definition at line 52 of file SPIRVCallLowering.cpp.
References llvm::MemoryEffects::doesNotAccessMemory(), F, and llvm::MemoryEffects::onlyReadsMemory().
getKernelArgAttribute()
static MDString* getKernelArgAttribute (const Function & KernelFunction, unsigned ArgIdx, const StringRef AttributeName) static
Definition at line 120 of file SPIRVCallLowering.cpp.
References assert(), llvm::Function::getCallingConv(), and llvm::CallingConv::SPIR_KERNEL.
Referenced by getArgAccessQual(), getArgType(), and getKernelArgTypeQual().
getKernelArgTypeQual()
static std::vector<SPIRV::Decoration::Decoration> getKernelArgTypeQual (const Function & KernelFunction, unsigned ArgIdx) static
Definition at line 189 of file SPIRVCallLowering.cpp.
References llvm::StringRef::compare(), getKernelArgAttribute(), and llvm::MDString::getString().
Referenced by llvm::SPIRVCallLowering::lowerFormalArguments().
getOriginalFunctionType()
static FunctionType* getOriginalFunctionType (const Function & F) static
Definition at line 82 of file SPIRVCallLowering.cpp.
References Arg, assert(), F, llvm::find_if(), llvm::FunctionType::get(), getConstInt(), llvm::MDNode::getOperand(), and N.
Referenced by getArgType(), llvm::SPIRVCallLowering::lowerCall(), and llvm::SPIRVCallLowering::lowerFormalArguments().