LLVM: lib/CodeGen/SelectionDAG/StatepointLowering.cpp File Reference
StatepointLowering.cpp File Reference
#include "StatepointLowering.h"
#include "SelectionDAGBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/GCMetadata.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/RuntimeLibcalls.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GCStrategy.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <tuple>
#include <utility>
Macros
#define DEBUG_TYPE "statepoint-lowering"
Typedefs
typedef FunctionLoweringInfo::StatepointRelocationRecord RecordType
Functions
STATISTIC (NumSlotsAllocatedForStatepoints, "Number of stack slots allocated for statepoints")
STATISTIC (NumOfStatepoints, "Number of statepoint nodes encountered")
STATISTIC (StatepointMaxSlotsRequired, "Maximum number of stack slots required for a singe statepoint")
static void pushStackMapConstant (SmallVectorImpl< SDValue > &Ops, SelectionDAGBuilder &Builder, uint64_t Value)
static std::optional< int > findPreviousSpillSlot (const Value *Val, SelectionDAGBuilder &Builder, int LookUpDepth)
Utility function for reservePreviousStackSlotForValue.
static bool willLowerDirectly (SDValue Incoming)
Return true if-and-only-if the given SDValue can be lowered as either a constant argument or a stack reference.
static void reservePreviousStackSlotForValue (const Value *IncomingValue, SelectionDAGBuilder &Builder)
Try to find existing copies of the incoming values in stack slots used for statepoint spilling.
static std::pair< SDValue, SDNode * > lowerCallFromStatepointLoweringInfo (SelectionDAGBuilder::StatepointLoweringInfo &SI, SelectionDAGBuilder &Builder)
Extract call from statepoint, lower it and return pointer to the call node.
static MachineMemOperand * getMachineMemOperand (MachineFunction &MF, FrameIndexSDNode &FI)
static std::tuple< SDValue, SDValue, MachineMemOperand * > spillIncomingStatepointValue (SDValue Incoming, SDValue Chain, SelectionDAGBuilder &Builder)
Spill a value incoming to the statepoint.
static void lowerIncomingStatepointValue (SDValue Incoming, bool RequireSpillSlot, SmallVectorImpl< SDValue > &Ops, SmallVectorImpl< MachineMemOperand * > &MemRefs, SelectionDAGBuilder &Builder)
Lower a single value incoming to a statepoint node.
static bool isGCValue (const Value *V, SelectionDAGBuilder &Builder)
Return true if value V represents the GC value.
static void lowerStatepointMetaArgs (SmallVectorImpl< SDValue > &Ops, SmallVectorImpl< MachineMemOperand * > &MemRefs, SmallVectorImpl< SDValue > &GCPtrs, DenseMap< SDValue, int > &LowerAsVReg, SelectionDAGBuilder::StatepointLoweringInfo &SI, SelectionDAGBuilder &Builder)
Lower deopt state and gc pointer arguments of the statepoint.
static std::pair< const GCResultInst *, const GCResultInst * > getGCResultLocality (const GCStatepointInst &S)
Return two gc.results if present.
Variables
cl::opt< bool > UseRegistersForDeoptValues ("use-registers-for-deopt-values", cl::Hidden, cl::init(false), cl::desc("Allow using registers for non pointer deopt args"))
cl::opt< bool > UseRegistersForGCPointersInLandingPad ("use-registers-for-gc-values-in-landing-pad", cl::Hidden, cl::init(false), cl::desc("Allow using registers for gc pointer in landing pad"))
cl::opt< unsigned > MaxRegistersForGCPointers ("max-registers-for-gc-values", cl::Hidden, cl::init(0), cl::desc("Max number of VRegs allowed to pass GC pointer meta args in"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "statepoint-lowering"
Definition at line 57 of file StatepointLowering.cpp.
Typedef Documentation
RecordType
typedef FunctionLoweringInfo::StatepointRelocationRecord RecordType
Definition at line 77 of file StatepointLowering.cpp.
Function Documentation
findPreviousSpillSlot()
static std::optional<int> findPreviousSpillSlot (const Value * Val, SelectionDAGBuilder & Builder, int LookUpDepth) static
Utility function for reservePreviousStackSlotForValue.
Tries to find stack slot index to which we have spilled value for previous statepoints. LookUpDepth specifies maximum DFS depth this function is allowed to look.
Definition at line 161 of file StatepointLowering.cpp.
References assert(), Builder, and llvm::FunctionLoweringInfo::StatepointRelocationRecord::Spill.
Referenced by reservePreviousStackSlotForValue().
getGCResultLocality()
static std::pair<const GCResultInst*, const GCResultInst*> getGCResultLocality (const GCStatepointInst & S) static
Return two gc.results if present.
First result is a block local gc.result, second result is a non-block local gc.result. Corresponding entry will be nullptr if not present.
Definition at line 996 of file StatepointLowering.cpp.
References S.
Referenced by llvm::SelectionDAGBuilder::LowerStatepoint().
getMachineMemOperand()
static MachineMemOperand* getMachineMemOperand (MachineFunction & MF, FrameIndexSDNode & FI) static
Definition at line 357 of file StatepointLowering.cpp.
References llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::FrameIndexSDNode::getIndex(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, and llvm::MachineMemOperand::MOVolatile.
Referenced by llvm::MachineFunction::getMachineMemOperand(), lowerIncomingStatepointValue(), lowerStatepointMetaArgs(), and spillIncomingStatepointValue().
isGCValue()
static bool isGCValue (const Value * V, SelectionDAGBuilder & Builder) static
Return true if value V represents the GC value.
The behavior is conservative in case it is not sure that value is not GC the function returns true.
Definition at line 501 of file StatepointLowering.cpp.
References Builder, and llvm::Value::getType().
Referenced by llvm::SelectionDAGBuilder::LowerStatepoint(), and lowerStatepointMetaArgs().
lowerCallFromStatepointLoweringInfo()
static std::pair<SDValue, SDNode *> lowerCallFromStatepointLoweringInfo (SelectionDAGBuilder::StatepointLoweringInfo & SI, SelectionDAGBuilder & Builder) static
Extract call from statepoint, lower it and return pointer to the call node.
Also update NodeMap so that getValue(statepoint) will reference lowered call result
Definition at line 320 of file StatepointLowering.cpp.
References assert(), Builder, llvm::ISD::CALLSEQ_END, llvm::ISD::CopyFromReg, llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::ISD::LOAD, and SI.
Referenced by llvm::SelectionDAGBuilder::LowerAsSTATEPOINT().
lowerIncomingStatepointValue()
static void lowerIncomingStatepointValue (SDValue Incoming, bool RequireSpillSlot, SmallVectorImpl< SDValue > & Ops, SmallVectorImpl< MachineMemOperand * > & MemRefs, SelectionDAGBuilder & Builder) static
Lower a single value incoming to a statepoint node.
This value can be either a deopt value or a gc value, the handling is the same. We special case constants and allocas, then fall back to spilling if required.
Definition at line 423 of file StatepointLowering.cpp.
References assert(), Builder, getMachineMemOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDValue::isUndef(), llvm_unreachable, pushStackMapConstant(), spillIncomingStatepointValue(), and willLowerDirectly().
Referenced by lowerStatepointMetaArgs().
lowerStatepointMetaArgs()
static void lowerStatepointMetaArgs (SmallVectorImpl< SDValue > & Ops, SmallVectorImpl< MachineMemOperand * > & MemRefs, SmallVectorImpl< SDValue > & GCPtrs, DenseMap< SDValue, int > & LowerAsVReg, SelectionDAGBuilder::StatepointLoweringInfo & SI, SelectionDAGBuilder & Builder) static
Lower deopt state and gc pointer arguments of the statepoint.
The actual lowering is described in lowerIncomingStatepointValue. This function is responsible for lowering everything in the right position and playing some tricks to avoid redundant stack manipulation where possible. On completion, 'Ops' will contain ready to use operands for machine code statepoint. The chain nodes will have already been created and the DAG root will be set to the last value spilled (if any were).
Definition at line 519 of file StatepointLowering.cpp.
References llvm::SmallVectorImpl< T >::append(), Arg, assert(), llvm::sampleprof::Base, Builder, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::count(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), llvm::DeoptLiveIn, llvm::SDValue::dump(), getMachineMemOperand(), llvm::SDValue::getNode(), llvm::SDValue::getValueType(), i, llvm::MVT::i64, llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::insert(), llvm::SmallSet< T, N, C >::insert(), isGCValue(), llvm::EVT::isVector(), LLVM_DEBUG, lowerIncomingStatepointValue(), MaxRegistersForGCPointers, pushStackMapConstant(), reservePreviousStackSlotForValue(), SI, llvm::SetVector< T, SmallVector< T, N >, SmallDenseSet< T, N > >::size(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::size(), uint64_t, UseRegistersForDeoptValues, UseRegistersForGCPointersInLandingPad, and willLowerDirectly().
Referenced by llvm::SelectionDAGBuilder::LowerAsSTATEPOINT().
pushStackMapConstant()
static void pushStackMapConstant (SmallVectorImpl< SDValue > & Ops, SelectionDAGBuilder & Builder, uint64_t Value) static
Definition at line 79 of file StatepointLowering.cpp.
References Builder, and llvm::MVT::i64.
Referenced by llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerIncomingStatepointValue(), and lowerStatepointMetaArgs().
reservePreviousStackSlotForValue()
static void reservePreviousStackSlotForValue (const Value * IncomingValue, SelectionDAGBuilder & Builder) static
Try to find existing copies of the incoming values in stack slots used for statepoint spilling.
If we can find a spill slot for the incoming value, mark that slot as allocated, and reuse the same slot for this safepoint. This helps to avoid series of loads and stores that only serve to reshuffle values on the stack between calls.
Definition at line 270 of file StatepointLowering.cpp.
References assert(), Builder, llvm::find(), findPreviousSpillSlot(), llvm::SDValue::getNode(), llvm::Offset, and willLowerDirectly().
Referenced by lowerStatepointMetaArgs().
spillIncomingStatepointValue()
static std::tuple<SDValue, SDValue, MachineMemOperand*> spillIncomingStatepointValue (SDValue Incoming, SDValue Chain, SelectionDAGBuilder & Builder) static
Spill a value incoming to the statepoint.
It might be either part of vmstate or gcstate. In both cases unconditionally spill it on the stack unless it is a null constant. Return pair with first element being frame index containing saved value and second element with outgoing chain from the emitted store
Definition at line 375 of file StatepointLowering.cpp.
References assert(), Builder, llvm::MachinePointerInfo::getFixedStack(), getMachineMemOperand(), llvm::SDValue::getNode(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), and llvm::MachineMemOperand::MOStore.
Referenced by lowerIncomingStatepointValue().
STATISTIC() [1/3]
STATISTIC (NumOfStatepoints , "Number of statepoint nodes encountered")
STATISTIC() [2/3]
STATISTIC (NumSlotsAllocatedForStatepoints , "Number of stack slots allocated for statepoints")
STATISTIC() [3/3]
STATISTIC (StatepointMaxSlotsRequired , "Maximum number of stack slots required for a singe statepoint")
willLowerDirectly()
static bool willLowerDirectly (SDValue Incoming) static
Return true if-and-only-if the given SDValue can be lowered as either a constant argument or a stack reference.
The key point is that the value doesn't need to be spilled or tracked as a vreg use.
Definition at line 248 of file StatepointLowering.cpp.
References llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), and llvm::SDValue::isUndef().
Referenced by lowerIncomingStatepointValue(), lowerStatepointMetaArgs(), and reservePreviousStackSlotForValue().
Variable Documentation
MaxRegistersForGCPointers
cl::opt<unsigned> MaxRegistersForGCPointers("max-registers-for-gc-values", cl::Hidden, cl::init(0), cl::desc("Max number of VRegs allowed to pass GC pointer meta args in"))
Referenced by lowerStatepointMetaArgs().
UseRegistersForDeoptValues
cl::opt<bool> UseRegistersForDeoptValues("use-registers-for-deopt-values", cl::Hidden, cl::init(false), cl::desc("Allow using registers for non pointer deopt args"))
Referenced by lowerStatepointMetaArgs().
UseRegistersForGCPointersInLandingPad
cl::opt<bool> UseRegistersForGCPointersInLandingPad("use-registers-for-gc-values-in-landing-pad", cl::Hidden, cl::init(false), cl::desc("Allow using registers for gc pointer in landing pad"))
Referenced by lowerStatepointMetaArgs().