LLVM: lib/Transforms/IPO/StripSymbols.cpp File Reference
StripSymbols.cpp File Reference
#include "llvm/Transforms/IPO/StripSymbols.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/TypeFinder.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/Local.h"
Functions
static bool OnlyUsedBy (Value *V, Value *Usr)
OnlyUsedBy - Return true if V is only used by Usr.
static void RemoveDeadConstant (Constant *C)
static void StripSymtab (ValueSymbolTable &ST, bool PreserveDbgInfo)
static void StripTypeNames (Module &M, bool PreserveDbgInfo)
static void findUsedValues (GlobalVariable *LLVMUsed, SmallPtrSetImpl< const GlobalValue * > &UsedValues)
Find values that are marked as llvm.used.
static bool StripSymbolNames (Module &M, bool PreserveDbgInfo)
StripSymbolNames - Strip symbol names.
static bool stripDebugDeclareImpl (Module &M)
static void collectCUsWithScope (const DIScope *Scope, std::set< DICompileUnit * > &LiveCUs, SmallPtrSet< const DIScope *, 8 > &VisitedScopes)
Collects compilation units referenced by functions or lexical scopes.
static void collectCUsForInlinedFuncs (const DILocation *Loc, std::set< DICompileUnit * > &LiveCUs, SmallPtrSet< const DIScope *, 8 > &VisitedScopes)
static bool stripDeadDebugInfoImpl (Module &M)
Function Documentation
collectCUsForInlinedFuncs()
static void collectCUsForInlinedFuncs (const DILocation * Loc, std::set< DICompileUnit * > & LiveCUs, SmallPtrSet< const DIScope *, 8 > & VisitedScopes) static
Definition at line 208 of file StripSymbols.cpp.
References collectCUsWithScope().
Referenced by stripDeadDebugInfoImpl().
collectCUsWithScope()
static void collectCUsWithScope (const DIScope * Scope, std::set< DICompileUnit * > & LiveCUs, SmallPtrSet< const DIScope *, 8 > & VisitedScopes) static
Collects compilation units referenced by functions or lexical scopes.
Accepts any DIScope and uses recursive bottom-up approach to reach either DISubprogram or DILexicalBlockBase.
Definition at line 183 of file StripSymbols.cpp.
References llvm::DILocalScope::getSubprogram(), and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by collectCUsForInlinedFuncs(), and stripDeadDebugInfoImpl().
findUsedValues()
static void findUsedValues (GlobalVariable * LLVMUsed, SmallPtrSetImpl< const GlobalValue * > & UsedValues) static
Find values that are marked as llvm.used.
Definition at line 101 of file StripSymbols.cpp.
References llvm::numbers::e, llvm::GlobalVariable::getInitializer(), llvm::User::getNumOperands(), llvm::User::getOperand(), i, llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::Value::stripPointerCasts().
Referenced by StripSymbolNames().
OnlyUsedBy()
static bool OnlyUsedBy (Value * V, Value * Usr) static
OnlyUsedBy - Return true if V is only used by Usr.
Definition at line 42 of file StripSymbols.cpp.
References llvm::Value::users().
Referenced by RemoveDeadConstant().
RemoveDeadConstant()
static void RemoveDeadConstant (Constant * C) static
Definition at line 50 of file StripSymbols.cpp.
References assert(), llvm::RISCVFenceField::O, OnlyUsedBy(), and Operands.
Referenced by stripDebugDeclareImpl().
stripDeadDebugInfoImpl()
static bool stripDeadDebugInfoImpl (Module & M) static
Definition at line 217 of file StripSymbols.cpp.
References llvm::NamedMDNode::addOperand(), llvm::SmallVectorImpl< T >::clear(), llvm::NamedMDNode::clearOperands(), collectCUsForInlinedFuncs(), collectCUsWithScope(), E, F, llvm::MDTuple::get(), I, llvm::detail::DenseSetImpl< ValueT, DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, DenseMapInfo< ValueT > >::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::inst_begin(), llvm::inst_end(), and M.
Referenced by llvm::StripDeadDebugInfoPass::run().
stripDebugDeclareImpl()
static bool stripDebugDeclareImpl (Module & M) static
Definition at line 141 of file StripSymbols.cpp.
References assert(), llvm::Instruction::eraseFromParent(), llvm::Function::eraseFromParent(), llvm::CallBase::getArgOperand(), M, llvm::RecursivelyDeleteTriviallyDeadInstructions(), RemoveDeadConstant(), llvm::Value::use_empty(), and llvm::Value::user_back().
Referenced by llvm::StripDebugDeclarePass::run().
StripSymbolNames()
static bool StripSymbolNames (Module & M, bool PreserveDbgInfo) static
StripSymbolNames - Strip symbol names.
Definition at line 115 of file StripSymbols.cpp.
References llvm::SmallPtrSetImpl< PtrType >::contains(), findUsedValues(), I, M, StripSymtab(), and StripTypeNames().
Referenced by llvm::StripSymbolsPass::run(), and llvm::StripNonDebugSymbolsPass::run().
StripSymtab()
static void StripSymtab (ValueSymbolTable & ST, bool PreserveDbgInfo) static
Definition at line 73 of file StripSymbols.cpp.
References llvm::Value::getName(), llvm::Value::setName(), llvm::ARM_MB::ST, llvm::StringRef::startswith(), and VI.
Referenced by StripSymbolNames().
StripTypeNames()
static void StripTypeNames (Module & M, bool PreserveDbgInfo) static
Definition at line 86 of file StripSymbols.cpp.
References M, and llvm::TypeFinder::run().
Referenced by StripSymbolNames().