LLVM: lib/Support/StringMap.cpp File Reference
StringMap.cpp File Reference
#include "llvm/ADT/StringMap.h"
#include "llvm/Support/DJB.h"
#include "llvm/Support/MathExtras.h"
Functions
static unsigned getMinBucketToReserveForEntries (unsigned NumEntries)
Returns the number of buckets to allocate to ensure that the DenseMap can accommodate NumEntries without need to grow().
static StringMapEntryBase ** createTable (unsigned NewNumBuckets)
static unsigned * getHashTable (StringMapEntryBase **TheTable, unsigned NumBuckets)
Function Documentation
createTable()
static StringMapEntryBase** createTable (unsigned NewNumBuckets) inline static
Definition at line 30 of file StringMap.cpp.
References llvm::safe_calloc().
Referenced by llvm::StringMapImpl::init(), and llvm::StringMapImpl::RehashTable().
getHashTable()
static unsigned* getHashTable (StringMapEntryBase ** TheTable, unsigned NumBuckets) inline static
Definition at line 40 of file StringMap.cpp.
Referenced by llvm::StringMapImpl::FindKey(), llvm::StringMapImpl::LookupBucketFor(), and llvm::StringMapImpl::RehashTable().
getMinBucketToReserveForEntries()
static unsigned getMinBucketToReserveForEntries (unsigned NumEntries) inline static
Returns the number of buckets to allocate to ensure that the DenseMap can accommodate NumEntries without need to grow().
Definition at line 21 of file StringMap.cpp.
References llvm::NextPowerOf2().
Referenced by llvm::DenseMap< llvm::SmallVector< llvm::VPValue *, 4 >, llvm::VPInstruction *, BundleDenseMapInfo >::init(), and llvm::StringMapImpl::StringMapImpl().