LLVM: AttributeComparator Struct Reference
AttributeComparator Struct Reference
Attribute comparator that only compares attribute keys.
Public Member Functions
bool operator() (Attribute A0, Attribute A1) const
bool operator() (Attribute A0, Attribute::AttrKind Kind) const
bool operator() (Attribute A0, StringRef Kind) const
Detailed Description
Attribute comparator that only compares attribute keys.
Enum attributes are sorted before string attributes.
Definition at line 1650 of file Attributes.cpp.
Member Function Documentation
operator()() [1/3]
bool AttributeComparator::operator() (Attribute A0, Attribute A1) const inline
Definition at line 1651 of file Attributes.cpp.
References llvm::Attribute::getKindAsEnum(), llvm::Attribute::getKindAsString(), and llvm::Attribute::isStringAttribute().
operator()() [2/3]
bool AttributeComparator::operator() (Attribute A0, Attribute::AttrKind Kind) const inline
Definition at line 1664 of file Attributes.cpp.
References llvm::Attribute::getKindAsEnum(), and llvm::Attribute::isStringAttribute().
operator()() [3/3]
bool AttributeComparator::operator() (Attribute A0, StringRef Kind) const inline
Definition at line 1669 of file Attributes.cpp.
References llvm::Attribute::getKindAsString(), and llvm::Attribute::isStringAttribute().
The documentation for this struct was generated from the following file:
lib/IR/Attributes.cpp