LLVM: llvm::ms_demangle::NodeArrayNode Struct Reference
llvm::ms_demangle::NodeArrayNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
NodeArrayNode ()
void output (OutputBuffer &OB, OutputFlags Flags) const override
void output (OutputBuffer &OB, OutputFlags Flags, StringView Separator) const
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
std::string toString (OutputFlags Flags=OF_Default) const
Public Attributes
Node ** Nodes = nullptr
size_t Count = 0
Detailed Description
Definition at line 514 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
NodeArrayNode()
llvm::ms_demangle::NodeArrayNode::NodeArrayNode () inline
Definition at line 515 of file MicrosoftDemangleNodes.h.
Member Function Documentation
output() [1/2]
void NodeArrayNode::output (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::Node.
Definition at line 156 of file MicrosoftDemangleNodes.cpp.
References llvm::X86II::OB.
Referenced by llvm::ms_demangle::QualifiedNameNode::output(), llvm::ms_demangle::FunctionSignatureNode::outputPost(), and llvm::ms_demangle::IdentifierNode::outputTemplateParameters().
output() [2/2]
void NodeArrayNode::output (OutputBuffer & OB, OutputFlags Flags, StringView Separator) const
Definition at line 160 of file MicrosoftDemangleNodes.cpp.
References Count, I, Nodes, llvm::X86II::OB, and llvm::ms_demangle::Node::output().
Member Data Documentation
Count
size_t llvm::ms_demangle::NodeArrayNode::Count = 0
Definition at line 522 of file MicrosoftDemangleNodes.h.
Referenced by llvm::ms_demangle::QualifiedNameNode::getUnqualifiedIdentifier(), output(), llvm::ms_demangle::ArrayTypeNode::outputDimensionsImpl(), and synthesizeQualifiedName().
Nodes
Node** llvm::ms_demangle::NodeArrayNode::Nodes = nullptr
Definition at line 521 of file MicrosoftDemangleNodes.h.
Referenced by llvm::ms_demangle::QualifiedNameNode::getUnqualifiedIdentifier(), output(), llvm::ms_demangle::ArrayTypeNode::outputDimensionsImpl(), and synthesizeQualifiedName().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp