LLVM: llvm::ValueDFS_Compare Struct Reference
llvm::ValueDFS_Compare Struct Reference
Public Member Functions
ValueDFS_Compare (DominatorTree &DT)
bool operator() (const ValueDFS &A, const ValueDFS &B) const
std::pair< BasicBlock *, BasicBlock * > getBlockEdge (const ValueDFS &VD) const
bool comparePHIRelated (const ValueDFS &A, const ValueDFS &B) const
Value * getMiddleDef (const ValueDFS &VD) const
const Instruction * getDefOrUser (const Value *Def, const Use *U) const
bool localComesBefore (const ValueDFS &A, const ValueDFS &B) const
Public Attributes
DominatorTree & DT
Detailed Description
Definition at line 120 of file PredicateInfo.cpp.
Constructor & Destructor Documentation
ValueDFS_Compare()
llvm::ValueDFS_Compare::ValueDFS_Compare (DominatorTree & DT) inline
Definition at line 122 of file PredicateInfo.cpp.
Member Function Documentation
comparePHIRelated()
bool llvm::ValueDFS_Compare::comparePHIRelated (const ValueDFS & A, const ValueDFS & B) const inline
Definition at line 162 of file PredicateInfo.cpp.
References assert(), B, llvm::DomTreeNodeBase< NodeT >::getDFSNumIn(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode().
getBlockEdge()
std::pair<BasicBlock *, BasicBlock *> llvm::ValueDFS_Compare::getBlockEdge (const ValueDFS & VD) const inline
Definition at line 152 of file PredicateInfo.cpp.
References llvm::ValueDFS::Def, PHI, llvm::ValueDFS::PInfo, and llvm::ValueDFS::U.
getDefOrUser()
const Instruction* llvm::ValueDFS_Compare::getDefOrUser (const Value * Def, const Use * U) const inline
Definition at line 216 of file PredicateInfo.cpp.
References llvm::tgtok::Def.
getMiddleDef()
Value* llvm::ValueDFS_Compare::getMiddleDef (const ValueDFS & VD) const inline
Definition at line 195 of file PredicateInfo.cpp.
References assert(), llvm::ValueDFS::Def, llvm::ValueDFS::PInfo, and llvm::ValueDFS::U.
localComesBefore()
bool llvm::ValueDFS_Compare::localComesBefore (const ValueDFS & A, const ValueDFS & B) const inline
Definition at line 224 of file PredicateInfo.cpp.
References B, and llvm::valueComesBefore().
operator()()
bool llvm::ValueDFS_Compare::operator() (const ValueDFS & A, const ValueDFS & B) const inline
Definition at line 124 of file PredicateInfo.cpp.
References assert(), B, llvm::LN_Last, and llvm::LN_Middle.
Member Data Documentation
DT
DominatorTree& llvm::ValueDFS_Compare::DT
Definition at line 121 of file PredicateInfo.cpp.
The documentation for this struct was generated from the following file:
lib/Transforms/Utils/PredicateInfo.cpp