LLVM: llvm::Intrinsic::IITDescriptor Struct Reference
llvm::Intrinsic::IITDescriptor Struct Reference
This is a type descriptor which explains the type requirements of an intrinsic.
#include "llvm/IR/Intrinsics.h"
Public Types
enum IITDescriptorKind {
Void, VarArg, MMX, Token,
Metadata, Half, BFloat, Float,
Double, Quad, Integer, Vector,
Pointer, Struct, Argument, ExtendArgument,
TruncArgument, HalfVecArgument, SameVecWidthArgument, PtrToArgument,
PtrToElt, VecOfAnyPtrsToElt, VecElementArgument, Subdivide2Argument,
Subdivide4Argument, VecOfBitcastsToInt, AMX, PPCQuad,
AnyPtrToElt
}
enum ArgKind {
AK_Any, AK_AnyInteger, AK_AnyFloat, AK_AnyVector,
AK_AnyPointer, AK_MatchType = 7
}
Public Member Functions
unsigned getArgumentNumber () const
ArgKind getArgumentKind () const
unsigned getOverloadArgNumber () const
unsigned getRefArgNumber () const
Static Public Member Functions
static IITDescriptor get (IITDescriptorKind K, unsigned Field)
static IITDescriptor get (IITDescriptorKind K, unsigned short Hi, unsigned short Lo)
static IITDescriptor getVector (unsigned Width, bool IsScalable)
Public Attributes
enum llvm::Intrinsic::IITDescriptor::IITDescriptorKind Kind
union {
unsigned Integer_Width
unsigned Float_Width
unsigned Pointer_AddressSpace
unsigned Struct_NumElements
unsigned Argument_Info
ElementCount Vector_Width
};
Detailed Description
This is a type descriptor which explains the type requirements of an intrinsic.
This is returned by getIntrinsicInfoTableEntries.
Definition at line 110 of file Intrinsics.h.
Member Enumeration Documentation
ArgKind
enum llvm::Intrinsic::IITDescriptor::ArgKind
Enumerator
AK_Any
AK_AnyInteger
AK_AnyFloat
AK_AnyVector
AK_AnyPointer
AK_MatchType
Definition at line 152 of file Intrinsics.h.
IITDescriptorKind
enum llvm::Intrinsic::IITDescriptor::IITDescriptorKind
Enumerator
Void
VarArg
MMX
Token
Metadata
Half
BFloat
Float
Double
Quad
Integer
Vector
Pointer
Struct
Argument
ExtendArgument
TruncArgument
HalfVecArgument
SameVecWidthArgument
PtrToArgument
PtrToElt
VecOfAnyPtrsToElt
VecElementArgument
Subdivide2Argument
Subdivide4Argument
VecOfBitcastsToInt
AMX
PPCQuad
AnyPtrToElt
Definition at line 111 of file Intrinsics.h.
Member Function Documentation
get() [1/2]
static IITDescriptor llvm::Intrinsic::IITDescriptor::get (IITDescriptorKind K, unsigned Field) inline static
Definition at line 191 of file Intrinsics.h.
Referenced by DecodeIITType().
get() [2/2]
static IITDescriptor llvm::Intrinsic::IITDescriptor::get (IITDescriptorKind K, unsigned short Hi, unsigned short Lo) inline static
Definition at line 196 of file Intrinsics.h.
getArgumentKind()
ArgKind llvm::Intrinsic::IITDescriptor::getArgumentKind () const inline
Definition at line 170 of file Intrinsics.h.
References Argument_Info, assert(), ExtendArgument, HalfVecArgument, Kind, PtrToArgument, SameVecWidthArgument, Subdivide2Argument, Subdivide4Argument, TruncArgument, VecElementArgument, and VecOfBitcastsToInt.
Referenced by matchIntrinsicType().
getArgumentNumber()
unsigned llvm::Intrinsic::IITDescriptor::getArgumentNumber () const inline
Definition at line 161 of file Intrinsics.h.
References Argument_Info, assert(), ExtendArgument, HalfVecArgument, Kind, PtrToArgument, PtrToElt, SameVecWidthArgument, Subdivide2Argument, Subdivide4Argument, TruncArgument, VecElementArgument, and VecOfBitcastsToInt.
getOverloadArgNumber()
unsigned llvm::Intrinsic::IITDescriptor::getOverloadArgNumber () const inline
Definition at line 182 of file Intrinsics.h.
References AnyPtrToElt, Argument_Info, assert(), Kind, and VecOfAnyPtrsToElt.
getRefArgNumber()
unsigned llvm::Intrinsic::IITDescriptor::getRefArgNumber () const inline
Definition at line 186 of file Intrinsics.h.
References AnyPtrToElt, Argument_Info, assert(), Kind, and VecOfAnyPtrsToElt.
getVector()
static IITDescriptor llvm::Intrinsic::IITDescriptor::getVector (unsigned Width, bool IsScalable) inline static
Definition at line 203 of file Intrinsics.h.
References llvm::ElementCount::get(), and Vector.
Referenced by DecodeIITType().
Member Data Documentation
@291
union { ... }
Argument_Info
unsigned llvm::Intrinsic::IITDescriptor::Argument_Info
Definition at line 148 of file Intrinsics.h.
Referenced by getArgumentKind(), getArgumentNumber(), getOverloadArgNumber(), and getRefArgNumber().
Float_Width
unsigned llvm::Intrinsic::IITDescriptor::Float_Width
Definition at line 145 of file Intrinsics.h.
Integer_Width
unsigned llvm::Intrinsic::IITDescriptor::Integer_Width
Definition at line 144 of file Intrinsics.h.
Kind
enum llvm::Intrinsic::IITDescriptor::IITDescriptorKind llvm::Intrinsic::IITDescriptor::Kind
Referenced by getArgumentKind(), getArgumentNumber(), getOverloadArgNumber(), getRefArgNumber(), and matchIntrinsicType().
Pointer_AddressSpace
unsigned llvm::Intrinsic::IITDescriptor::Pointer_AddressSpace
Definition at line 146 of file Intrinsics.h.
Struct_NumElements
unsigned llvm::Intrinsic::IITDescriptor::Struct_NumElements
Definition at line 147 of file Intrinsics.h.
Referenced by matchIntrinsicType().
Vector_Width
ElementCount llvm::Intrinsic::IITDescriptor::Vector_Width
Definition at line 149 of file Intrinsics.h.
The documentation for this struct was generated from the following file:
include/llvm/IR/Intrinsics.h