LLVM: llvm::PotentialValuesState< MemberTy > Struct Template Reference
llvm::PotentialValuesState< MemberTy > Struct Template Reference
A class for a set state.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using SetTy = SmallSetVector< MemberTy, 8 >
Public Member Functions
PotentialValuesState ()
PotentialValuesState (bool IsValid)
bool isValidState () const override
See AbstractState::isValidState(...)
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
PotentialValuesState & getAssumed ()
Return the assumed state.
const PotentialValuesState & getAssumed () const
const SetTy & getAssumedSet () const
Return this set.
bool undefIsContained () const
Returns whether this state contains an undef value or not.
bool operator== (const PotentialValuesState &RHS) const
void unionAssumed (const MemberTy &C)
Union assumed set with the passed value.
void unionAssumed (const PotentialValuesState &PVS)
Union assumed set with assumed set of the passed state PVS.
void unionAssumedWithUndef ()
Union assumed set with an undef value.
PotentialValuesState operator^= (const PotentialValuesState &PVS)
"Clamp" this state with PVS.
PotentialValuesState operator&= (const PotentialValuesState &PVS)
bool contains (const MemberTy &V) const
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Static Public Member Functions
static PotentialValuesState getBestState ()
Return empty set as the best state of potential values.
static PotentialValuesState getBestState (const PotentialValuesState &PVS)
static PotentialValuesState getWorstState ()
Return full set as the worst state of potential values.
Static Public Attributes
static unsigned MaxPotentialValues = 0
Maximum number of potential values to be tracked.
Protected Member Functions
SetTy & getAssumedSet ()
Detailed Description
template<typename MemberTy>
struct llvm::PotentialValuesState< MemberTy >
A class for a set state.
The assumed boolean state indicates whether the corresponding set is full set or not. If the assumed state is false, this is the worst state. The worst state (invalid state) of set of potential values is when the set contains every possible value (i.e. we cannot in any way limit the value that the target position can take). That never happens naturally, we only force it. As for the conditions under which we force it, see AAPotentialConstantValues.
Definition at line 4523 of file Attributor.h.
Member Typedef Documentation
SetTy
template<typename MemberTy > using llvm::PotentialValuesState< MemberTy >::SetTy = SmallSetVector<MemberTy, 8>
Definition at line 4524 of file Attributor.h.
Constructor & Destructor Documentation
PotentialValuesState() [1/2]
template<typename MemberTy > llvm::PotentialValuesState< MemberTy >::PotentialValuesState () inline
Definition at line 4526 of file Attributor.h.
Referenced by llvm::PotentialValuesState< MemberTy >::getBestState(), and llvm::PotentialValuesState< MemberTy >::getWorstState().
PotentialValuesState() [2/2]
template<typename MemberTy > llvm::PotentialValuesState< MemberTy >::PotentialValuesState (bool IsValid) inline
Definition at line 4528 of file Attributor.h.
Member Function Documentation
contains()
template<typename MemberTy > bool llvm::PotentialValuesState< MemberTy >::contains (const MemberTy & V) const inline
Definition at line 4614 of file Attributor.h.
References llvm::SetVector< T, Vector, Set >::contains(), llvm::PotentialValuesState< MemberTy >::isValidState(), and true.
getAssumed() [1/2]
template<typename MemberTy > PotentialValuesState& llvm::PotentialValuesState< MemberTy >::getAssumed () inline
Return the assumed state.
Definition at line 4548 of file Attributor.h.
getAssumed() [2/2]
template<typename MemberTy > const PotentialValuesState& llvm::PotentialValuesState< MemberTy >::getAssumed () const inline
Definition at line 4549 of file Attributor.h.
getAssumedSet() [1/2]
template<typename MemberTy > SetTy& llvm::PotentialValuesState< MemberTy >::getAssumedSet () inline protected
Definition at line 4619 of file Attributor.h.
References assert(), and llvm::PotentialValuesState< MemberTy >::isValidState().
getAssumedSet() [2/2]
template<typename MemberTy > const SetTy& llvm::PotentialValuesState< MemberTy >::getAssumedSet () const inline
Return this set.
We should check whether this set is valid or not by isValidState() before calling this function.
Definition at line 4553 of file Attributor.h.
References assert(), and llvm::PotentialValuesState< MemberTy >::isValidState().
Referenced by llvm::AAPotentialConstantValues::getAssumedConstant().
getBestState() [1/2]
template<typename MemberTy > static PotentialValuesState llvm::PotentialValuesState< MemberTy >::getBestState () inline static
Return empty set as the best state of potential values.
Definition at line 4579 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy >::PotentialValuesState().
Referenced by llvm::PotentialValuesState< MemberTy >::getBestState().
getBestState() [2/2]
template<typename MemberTy > static PotentialValuesState llvm::PotentialValuesState< MemberTy >::getBestState (const PotentialValuesState< MemberTy > & PVS) inline static
Definition at line 4583 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy >::getBestState().
getWorstState()
template<typename MemberTy > static PotentialValuesState llvm::PotentialValuesState< MemberTy >::getWorstState () inline static
Return full set as the worst state of potential values.
Definition at line 4588 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy >::PotentialValuesState().
indicateOptimisticFixpoint()
template<typename MemberTy > ChangeStatus llvm::PotentialValuesState< MemberTy >::indicateOptimisticFixpoint () inline override virtual
See AbstractState::indicateOptimisticFixpoint(...)
Implements llvm::AbstractState.
Definition at line 4543 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::indicateOptimisticFixpoint().
indicatePessimisticFixpoint()
template<typename MemberTy > ChangeStatus llvm::PotentialValuesState< MemberTy >::indicatePessimisticFixpoint () inline override virtual
See AbstractState::indicatePessimisticFixpoint(...)
Implements llvm::AbstractState.
Definition at line 4538 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::indicatePessimisticFixpoint().
isAtFixpoint()
template<typename MemberTy > bool llvm::PotentialValuesState< MemberTy >::isAtFixpoint () const inline override virtual
See AbstractState::isAtFixpoint(...)
Implements llvm::AbstractState.
Definition at line 4535 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::isAtFixpoint().
isValidState()
template<typename MemberTy > bool llvm::PotentialValuesState< MemberTy >::isValidState () const inline override virtual
See AbstractState::isValidState(...)
Implements llvm::AbstractState.
Definition at line 4532 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::isValidState().
Referenced by llvm::PotentialValuesState< MemberTy >::contains(), llvm::AAPotentialConstantValues::getAssumedConstant(), llvm::PotentialValuesState< MemberTy >::getAssumedSet(), llvm::PotentialValuesState< MemberTy >::operator==(), and llvm::PotentialValuesState< MemberTy >::undefIsContained().
operator&=()
template<typename MemberTy > PotentialValuesState llvm::PotentialValuesState< MemberTy >::operator&= (const PotentialValuesState< MemberTy > & PVS) inline
Definition at line 4608 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy >::unionAssumed().
operator==()
template<typename MemberTy > bool llvm::PotentialValuesState< MemberTy >::operator== (const PotentialValuesState< MemberTy > & RHS) const inline
Definition at line 4564 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy >::isValidState(), RHS, and llvm::PotentialValuesState< MemberTy >::undefIsContained().
operator^=()
template<typename MemberTy > PotentialValuesState llvm::PotentialValuesState< MemberTy >::operator^= (const PotentialValuesState< MemberTy > & PVS) inline
"Clamp" this state with PVS.
Definition at line 4602 of file Attributor.h.
References llvm::PotentialValuesState< MemberTy >::unionAssumed().
undefIsContained()
template<typename MemberTy > bool llvm::PotentialValuesState< MemberTy >::undefIsContained () const inline
Returns whether this state contains an undef value or not.
Definition at line 4559 of file Attributor.h.
References assert(), and llvm::PotentialValuesState< MemberTy >::isValidState().
Referenced by llvm::AAPotentialConstantValues::getAssumedConstant(), and llvm::PotentialValuesState< MemberTy >::operator==().
unionAssumed() [1/2]
template<typename MemberTy > void llvm::PotentialValuesState< MemberTy >::unionAssumed (const MemberTy & C) inline
Union assumed set with the passed value.
Definition at line 4593 of file Attributor.h.
Referenced by llvm::PotentialValuesState< MemberTy >::operator&=(), and llvm::PotentialValuesState< MemberTy >::operator^=().
unionAssumed() [2/2]
template<typename MemberTy > void llvm::PotentialValuesState< MemberTy >::unionAssumed (const PotentialValuesState< MemberTy > & PVS) inline
Union assumed set with assumed set of the passed state PVS.
Definition at line 4596 of file Attributor.h.
unionAssumedWithUndef()
template<typename MemberTy > void llvm::PotentialValuesState< MemberTy >::unionAssumedWithUndef () inline
Union assumed set with an undef value.
Definition at line 4599 of file Attributor.h.
Member Data Documentation
MaxPotentialValues
unsigned llvm::PotentialLLVMValuesState::MaxPotentialValues = 0 static
Maximum number of potential values to be tracked.
This is set by -attributor-max-potential-values command line option
Definition at line 4576 of file Attributor.h.
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp