LLVM: llvm::MCDwarfLineTableHeader Struct Reference
llvm::MCDwarfLineTableHeader Struct Reference
#include "llvm/MC/MCDwarf.h"
Public Member Functions
MCDwarfLineTableHeader ()=default
Expected< unsigned > tryGetFile (StringRef &Directory, StringRef &FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber=0)
std::pair< MCSymbol *, MCSymbol * > Emit (MCStreamer *MCOS, MCDwarfLineTableParams Params, std::optional< MCDwarfLineStr > &LineStr) const
std::pair< MCSymbol *, MCSymbol * > Emit (MCStreamer *MCOS, MCDwarfLineTableParams Params, ArrayRef< char > SpecialOpcodeLengths, std::optional< MCDwarfLineStr > &LineStr) const
void resetMD5Usage ()
void trackMD5Usage (bool MD5Used)
bool isMD5UsageConsistent () const
void setRootFile (StringRef Directory, StringRef FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source)
void resetFileTable ()
Public Attributes
MCSymbol * Label = nullptr
SmallVector< std::string, 3 > MCDwarfDirs
SmallVector< MCDwarfFile, 3 > MCDwarfFiles
StringMap< unsigned > SourceIdMap
std::string CompilationDir
MCDwarfFile RootFile
bool HasSource = false
Detailed Description
Definition at line 257 of file MCDwarf.h.
Constructor & Destructor Documentation
MCDwarfLineTableHeader()
llvm::MCDwarfLineTableHeader::MCDwarfLineTableHeader () default
Member Function Documentation
Emit() [1/2]
std::pair< MCSymbol *, MCSymbol * > MCDwarfLineTableHeader::Emit (MCStreamer * MCOS, MCDwarfLineTableParams Params, ArrayRef< char > SpecialOpcodeLengths, std::optional< MCDwarfLineStr > & LineStr) const
Definition at line 481 of file MCDwarf.cpp.
References llvm::MCContext::createTempSymbol(), DWARF2_LINE_DEFAULT_IS_STMT, llvm::MCDwarfLineTableParams::DWARF2LineBase, llvm::MCDwarfLineTableParams::DWARF2LineRange, llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitDwarfLineStartLabel(), llvm::MCStreamer::emitDwarfUnitLength(), llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt8(), llvm::MCStreamer::emitLabel(), llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCodePointerSize(), llvm::MCStreamer::getContext(), llvm::MCContext::getDwarfFormat(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::MCContext::getDwarfVersion(), llvm::MCAsmInfo::getMinInstAlignment(), Label, llvm::Length, and llvm::ArrayRef< T >::size().
Emit() [2/2]
std::pair< MCSymbol *, MCSymbol * > MCDwarfLineTableHeader::Emit (MCStreamer * MCOS, MCDwarfLineTableParams Params, std::optional< MCDwarfLineStr > & LineStr) const
Definition at line 293 of file MCDwarf.cpp.
References llvm::ArrayRef(), assert(), llvm::MCDwarfLineTableParams::DWARF2LineOpcodeBase, and size.
Referenced by llvm::MCDwarfDwoLineTable::Emit(), and llvm::MCDwarfLineTable::emitCU().
isMD5UsageConsistent()
bool llvm::MCDwarfLineTableHeader::isMD5UsageConsistent () const inline
Definition at line 291 of file MCDwarf.h.
References MCDwarfFiles.
resetFileTable()
void llvm::MCDwarfLineTableHeader::resetFileTable () inline
Definition at line 307 of file MCDwarf.h.
References llvm::SmallVectorImpl< T >::clear(), HasSource, MCDwarfDirs, MCDwarfFiles, llvm::MCDwarfFile::Name, resetMD5Usage(), and RootFile.
resetMD5Usage()
void llvm::MCDwarfLineTableHeader::resetMD5Usage () inline
Definition at line 283 of file MCDwarf.h.
Referenced by resetFileTable().
setRootFile()
void llvm::MCDwarfLineTableHeader::setRootFile (StringRef Directory, StringRef FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source) inline
Definition at line 295 of file MCDwarf.h.
References llvm::MCDwarfFile::Checksum, CompilationDir, llvm::MCDwarfFile::DirIndex, HasSource, llvm::MCDwarfFile::Name, RootFile, llvm::MCDwarfFile::Source, llvm::Sched::Source, and trackMD5Usage().
trackMD5Usage()
void llvm::MCDwarfLineTableHeader::trackMD5Usage (bool MD5Used) inline
Definition at line 287 of file MCDwarf.h.
Referenced by setRootFile(), and tryGetFile().
tryGetFile()
Expected< unsigned > MCDwarfLineTableHeader::tryGetFile (StringRef & Directory, StringRef & FileName, std::optional< MD5::MD5Result > Checksum, std::optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber = 0)
Definition at line 579 of file MCDwarf.cpp.
References assert(), CompilationDir, llvm::StringRef::empty(), llvm::sys::path::filename(), llvm::find(), HasSource, llvm::inconvertibleErrorCode(), llvm::StringMap< ValueTy, AllocatorTy >::insert(), isRootFile(), MCDwarfDirs, MCDwarfFiles, llvm::sys::path::parent_path(), RootFile, llvm::Sched::Source, SourceIdMap, llvm::dwarf::toStringRef(), and trackMD5Usage().
Referenced by llvm::MCDwarfLineTable::tryGetFile().
Member Data Documentation
CompilationDir
std::string llvm::MCDwarfLineTableHeader::CompilationDir
Definition at line 262 of file MCDwarf.h.
Referenced by setRootFile(), and tryGetFile().
HasSource
bool llvm::MCDwarfLineTableHeader::HasSource = false
Definition at line 264 of file MCDwarf.h.
Referenced by resetFileTable(), setRootFile(), and tryGetFile().
Label
MCSymbol* llvm::MCDwarfLineTableHeader::Label = nullptr
Definition at line 258 of file MCDwarf.h.
Referenced by Emit().
MCDwarfDirs
SmallVector<std::string, 3> llvm::MCDwarfLineTableHeader::MCDwarfDirs
Definition at line 259 of file MCDwarf.h.
Referenced by resetFileTable(), and tryGetFile().
MCDwarfFiles
SmallVector<MCDwarfFile, 3> llvm::MCDwarfLineTableHeader::MCDwarfFiles
Definition at line 260 of file MCDwarf.h.
Referenced by isMD5UsageConsistent(), resetFileTable(), and tryGetFile().
RootFile
MCDwarfFile llvm::MCDwarfLineTableHeader::RootFile
Definition at line 263 of file MCDwarf.h.
Referenced by resetFileTable(), setRootFile(), and tryGetFile().
SourceIdMap
StringMap<unsigned> llvm::MCDwarfLineTableHeader::SourceIdMap
Definition at line 261 of file MCDwarf.h.
Referenced by tryGetFile().
The documentation for this struct was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp