LLVM: llvm::rdf::DataFlowGraph::DefStack Struct Reference
llvm::rdf::DataFlowGraph::DefStack Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Types
using iterator = Iterator
Public Member Functions
DefStack ()=default
bool empty () const
iterator top () const
iterator bottom () const
unsigned size () const
void push (NodeAddr< DefNode * > DA)
void pop ()
void start_block (NodeId N)
void clear_block (NodeId N)
Friends
struct Iterator
Detailed Description
Definition at line 673 of file RDFGraph.h.
Member Typedef Documentation
iterator
using llvm::rdf::DataFlowGraph::DefStack::iterator = Iterator
Definition at line 709 of file RDFGraph.h.
Constructor & Destructor Documentation
DefStack()
llvm::rdf::DataFlowGraph::DefStack::DefStack () default
Member Function Documentation
bottom()
iterator llvm::rdf::DataFlowGraph::DefStack::bottom () const inline
Definition at line 712 of file RDFGraph.h.
References Iterator.
Referenced by empty(), and size().
clear_block()
void DataFlowGraph::DefStack::clear_block (NodeId N)
Definition at line 704 of file RDFGraph.cpp.
References assert(), N, and P.
empty()
bool llvm::rdf::DataFlowGraph::DefStack::empty () const inline
Definition at line 676 of file RDFGraph.h.
References bottom(), and top().
pop()
void DataFlowGraph::DefStack::pop ()
Definition at line 689 of file RDFGraph.cpp.
References assert(), and P.
push()
void llvm::rdf::DataFlowGraph::DefStack::push (NodeAddr< DefNode * > DA) inline
Definition at line 715 of file RDFGraph.h.
References llvm::AArch64PACKey::DA.
size()
unsigned DataFlowGraph::DefStack::size () const
Definition at line 679 of file RDFGraph.cpp.
References bottom(), E, I, S, and top().
start_block()
void DataFlowGraph::DefStack::start_block (NodeId N)
Definition at line 696 of file RDFGraph.cpp.
References assert(), and N.
top()
iterator llvm::rdf::DataFlowGraph::DefStack::top () const inline
Definition at line 711 of file RDFGraph.h.
References Iterator.
Referenced by empty(), and size().
Friends And Related Function Documentation
Iterator
friend struct Iterator friend
Definition at line 721 of file RDFGraph.h.
Referenced by bottom(), and top().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp