LLVM: llvm::AMDGPUUseNativeCallsPass Struct Reference
llvm::AMDGPUUseNativeCallsPass Struct Reference
#include "Target/AMDGPU/AMDGPU.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUUseNativeCallsPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUUseNativeCallsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 71 of file AMDGPU.h.
Member Function Documentation
run()
PreservedAnalyses AMDGPUUseNativeCallsPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 1750 of file AMDGPULibCalls.cpp.
References llvm::PreservedAnalyses::all(), BB, Callee, E, F, llvm::CallBase::getCalledFunction(), I, llvm::AMDGPULibCalls::initNativeFuncs(), llvm::PreservedAnalyses::none(), UseNative, and llvm::AMDGPULibCalls::useNative().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPU.h
lib/Target/AMDGPU/AMDGPULibCalls.cpp