LLVM: llvm::AA::PointerInfo::State Struct Reference
llvm::AA::PointerInfo::State Struct Reference
A type to track pointer/struct usage and accesses for AAPointerInfo.
Public Types
using OffsetBinsTy = DenseMap< RangeTy, SmallSet< unsigned, 4 > >
using const_bin_iterator = OffsetBinsTy::const_iterator
Public Member Functions
State ()=default
State (State &&SIS)=default
const State & getAssumed () const
bool isValidState () const override
See AbstractState::isValidState().
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint().
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint().
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint().
State & operator= (const State &R)
State & operator= (State &&R)
ChangeStatus addAccess (Attributor &A, const AAPointerInfo::RangeList &Ranges, Instruction &I, std::optional< Value * > Content, AAPointerInfo::AccessKind Kind, Type *Ty, Instruction *RemoteI=nullptr)
Add a new Access to the state at offset Offset and with size Size.
const_bin_iterator begin () const
const_bin_iterator end () const
const AAPointerInfo::Access & getAccess (unsigned Index) const
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Static Public Member Functions
static State getBestState (const State &SIS)
Return the best possible representable state.
static State getWorstState (const State &SIS)
Return the worst possible representable state.
Protected Member Functions
bool forallInterferingAccesses (AA::RangeTy Range, function_ref< bool(const AAPointerInfo::Access &, bool)> CB) const
See AAPointerInfo::forallInterferingAccesses.
bool forallInterferingAccesses (Instruction &I, function_ref< bool(const AAPointerInfo::Access &, bool)> CB, AA::RangeTy &Range) const
See AAPointerInfo::forallInterferingAccesses.
Protected Attributes
SmallVector< AAPointerInfo::Access > AccessList
OffsetBinsTy OffsetBins
DenseMap< const Instruction *, SmallVector< unsigned > > RemoteIMap
Detailed Description
A type to track pointer/struct usage and accesses for AAPointerInfo.
Definition at line 727 of file AttributorAttributes.cpp.
Member Typedef Documentation
const_bin_iterator
using llvm::AA::PointerInfo::State::const_bin_iterator = OffsetBinsTy::const_iterator
Definition at line 796 of file AttributorAttributes.cpp.
OffsetBinsTy
using llvm::AA::PointerInfo::State::OffsetBinsTy = DenseMap<RangeTy, SmallSet<unsigned, 4> >
Definition at line 794 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
State() [1/2]
llvm::AA::PointerInfo::State::State () default
Referenced by llvm::AA::PointerInfo::State::getBestState().
State() [2/2]
llvm::AA::PointerInfo::State::State (State && SIS) default
Member Function Documentation
addAccess()
ChangeStatus llvm::AA::PointerInfo::State::addAccess (Attributor & A, const AAPointerInfo::RangeList & Ranges, Instruction & I, std::optional< Value * > Content, AAPointerInfo::AccessKind Kind, Type * Ty, Instruction * RemoteI = nullptr)
Add a new Access to the state at offset Offset and with size Size.
The access is associated with I, writes Content (if anything), and is of kind Kind. If an Access already exists for the same I and same RemoteI, the two are combined, potentially losing information about offset and size. The resulting access must now be moved from its original OffsetBin to the bin for its new offset.
\Returns CHANGED, if the state changed, UNCHANGED otherwise.
Definition at line 870 of file AttributorAttributes.cpp.
References A, llvm::AA::PointerInfo::State::AccessList, assert(), llvm::Bin, Content, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::dbgs(), llvm::AAPointerInfo::Access::getRanges(), I, Index, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), LLVM_DEBUG, llvm::AA::PointerInfo::State::OffsetBins, llvm::AA::PointerInfo::State::RemoteIMap, llvm::set_difference(), and ToRemove.
begin()
const_bin_iterator llvm::AA::PointerInfo::State::begin () const inline
Definition at line 797 of file AttributorAttributes.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), and llvm::AA::PointerInfo::State::OffsetBins.
end()
const_bin_iterator llvm::AA::PointerInfo::State::end () const inline
Definition at line 798 of file AttributorAttributes.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::AA::PointerInfo::State::OffsetBins.
forallInterferingAccesses() [1/2]
bool llvm::AA::PointerInfo::State::forallInterferingAccesses (AA::RangeTy Range, function_ref< bool(const AAPointerInfo::Access &, bool)> CB) const inline protected
See AAPointerInfo::forallInterferingAccesses.
Definition at line 822 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList, Index, llvm::AA::PointerInfo::State::isValidState(), and llvm::AA::PointerInfo::State::OffsetBins.
Referenced by llvm::AA::PointerInfo::State::forallInterferingAccesses().
forallInterferingAccesses() [2/2]
bool llvm::AA::PointerInfo::State::forallInterferingAccesses (Instruction & I, function_ref< bool(const AAPointerInfo::Access &, bool)> CB, AA::RangeTy & Range) const inline protected
See AAPointerInfo::forallInterferingAccesses.
Definition at line 843 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList, llvm::AA::PointerInfo::State::forallInterferingAccesses(), I, llvm::AA::PointerInfo::State::isValidState(), and llvm::AA::PointerInfo::State::RemoteIMap.
getAccess()
const AAPointerInfo::Access& llvm::AA::PointerInfo::State::getAccess (unsigned Index) const inline
Definition at line 800 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList, and Index.
getAssumed()
const State& llvm::AA::PointerInfo::State::getAssumed () const inline
Definition at line 741 of file AttributorAttributes.cpp.
getBestState()
static State llvm::AA::PointerInfo::State::getBestState (const State & SIS) inline static
Return the best possible representable state.
Definition at line 729 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::State().
getWorstState()
static State llvm::AA::PointerInfo::State::getWorstState (const State & SIS) inline static
Return the worst possible representable state.
Definition at line 732 of file AttributorAttributes.cpp.
indicateOptimisticFixpoint()
ChangeStatus llvm::AA::PointerInfo::State::indicateOptimisticFixpoint () inline override virtual
See AbstractState::indicateOptimisticFixpoint().
Implements llvm::AbstractState.
Definition at line 750 of file AttributorAttributes.cpp.
References llvm::UNCHANGED.
indicatePessimisticFixpoint()
ChangeStatus llvm::AA::PointerInfo::State::indicatePessimisticFixpoint () inline override virtual
See AbstractState::indicatePessimisticFixpoint().
Implements llvm::AbstractState.
Definition at line 756 of file AttributorAttributes.cpp.
References llvm::CHANGED.
isAtFixpoint()
bool llvm::AA::PointerInfo::State::isAtFixpoint () const inline override virtual
See AbstractState::isAtFixpoint().
Implements llvm::AbstractState.
Definition at line 747 of file AttributorAttributes.cpp.
isValidState()
bool llvm::AA::PointerInfo::State::isValidState () const inline override virtual
See AbstractState::isValidState().
Implements llvm::AbstractState.
Definition at line 744 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::State::forallInterferingAccesses().
operator=() [1/2]
State& llvm::AA::PointerInfo::State::operator= (const State & R) inline
Definition at line 761 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList, llvm::AA::PointerInfo::State::OffsetBins, and llvm::AA::PointerInfo::State::RemoteIMap.
operator=() [2/2]
State& llvm::AA::PointerInfo::State::operator= (State && R) inline
Definition at line 771 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList, llvm::AA::PointerInfo::State::OffsetBins, llvm::AA::PointerInfo::State::RemoteIMap, and std::swap().
Member Data Documentation
AccessList
SmallVector<AAPointerInfo::Access> llvm::AA::PointerInfo::State::AccessList protected
Definition at line 817 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::State::addAccess(), llvm::AA::PointerInfo::State::forallInterferingAccesses(), llvm::AA::PointerInfo::State::getAccess(), and llvm::AA::PointerInfo::State::operator=().
OffsetBins
OffsetBinsTy llvm::AA::PointerInfo::State::OffsetBins protected
Definition at line 818 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::State::addAccess(), llvm::AA::PointerInfo::State::begin(), llvm::AA::PointerInfo::State::end(), llvm::AA::PointerInfo::State::forallInterferingAccesses(), and llvm::AA::PointerInfo::State::operator=().
RemoteIMap
DenseMap<const Instruction *, SmallVector<unsigned> > llvm::AA::PointerInfo::State::RemoteIMap protected
Definition at line 819 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::State::addAccess(), llvm::AA::PointerInfo::State::forallInterferingAccesses(), and llvm::AA::PointerInfo::State::operator=().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp