LLVM: llvm::rdf::CodeNode Struct Reference
llvm::rdf::CodeNode Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Member Functions
template<typename T >
T getCode () const
void setCode (void *C)
NodeAddr< NodeBase * > getFirstMember (const DataFlowGraph &G) const
NodeAddr< NodeBase * > getLastMember (const DataFlowGraph &G) const
void addMember (NodeAddr< NodeBase * > NA, const DataFlowGraph &G)
void addMemberAfter (NodeAddr< NodeBase * > MA, NodeAddr< NodeBase * > NA, const DataFlowGraph &G)
void removeMember (NodeAddr< NodeBase * > NA, const DataFlowGraph &G)
NodeList members (const DataFlowGraph &G) const
template<typename Predicate >
NodeList members_if (Predicate P, const DataFlowGraph &G) const
Public Member Functions inherited from llvm::rdf::NodeBase
NodeBase ()=default
uint16_t getType () const
uint16_t getKind () const
uint16_t getFlags () const
NodeId getNext () const
uint16_t getAttrs () const
void setAttrs (uint16_t A)
void setFlags (uint16_t F)
void append (NodeAddr< NodeBase * > NA)
void init ()
void setNext (NodeId N)
Additional Inherited Members
Protected Attributes inherited from llvm::rdf::NodeBase
uint16_t Attrs
uint16_t Reserved
NodeId Next
union {
Ref_struct Ref
Code_struct Code
};
Detailed Description
Definition at line 591 of file RDFGraph.h.
Member Function Documentation
addMember()
void CodeNode::addMember (NodeAddr< NodeBase * > NA, const DataFlowGraph & G)
Definition at line 472 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeBase::Code, llvm::rdf::NodeBase::Code_struct::FirstM, G, getLastMember(), llvm::rdf::NodeAddr< T >::Id, llvm::rdf::DataFlowGraph::id(), llvm::rdf::NodeBase::Code_struct::LastM, ML, and llvm::rdf::NodeBase::setNext().
Referenced by llvm::rdf::BlockNode::addPhi(), and llvm::rdf::DataFlowGraph::build().
addMemberAfter()
void CodeNode::addMemberAfter (NodeAddr< NodeBase * > MA, NodeAddr< NodeBase * > NA, const DataFlowGraph & G)
Definition at line 485 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeBase::append(), llvm::rdf::NodeBase::Code, llvm::rdf::NodeAddr< T >::Id, and llvm::rdf::NodeBase::Code_struct::LastM.
Referenced by llvm::rdf::BlockNode::addPhi().
getCode()
template<typename T > T llvm::rdf::CodeNode::getCode () const inline
Definition at line 592 of file RDFGraph.h.
References llvm::rdf::NodeBase::Code, llvm::rdf::NodeBase::Code_struct::CP, and T.
getFirstMember()
NodeAddr< NodeBase * > CodeNode::getFirstMember (const DataFlowGraph & G) const
Definition at line 458 of file RDFGraph.cpp.
References llvm::rdf::DataFlowGraph::addr(), llvm::rdf::NodeBase::Code, llvm::rdf::NodeBase::Code_struct::FirstM, and G.
Referenced by llvm::rdf::BlockNode::addPhi(), members_if(), and removeMember().
getLastMember()
NodeAddr< NodeBase * > CodeNode::getLastMember (const DataFlowGraph & G) const
Definition at line 465 of file RDFGraph.cpp.
References llvm::rdf::DataFlowGraph::addr(), llvm::rdf::NodeBase::Code, G, and llvm::rdf::NodeBase::Code_struct::LastM.
Referenced by addMember().
members()
NodeList CodeNode::members (const DataFlowGraph & G) const
Definition at line 525 of file RDFGraph.cpp.
References G, and members_if().
Referenced by llvm::rdf::DataFlowGraph::build(), llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), and llvm::rdf::Liveness::getNearestAliasedRef().
members_if()
template<typename Predicate > NodeList llvm::rdf::CodeNode::members_if (Predicate P, const DataFlowGraph & G) const
Definition at line 915 of file RDFGraph.h.
References G, getFirstMember(), M, and P.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::FuncNode::findBlock(), members(), and llvm::rdf::CopyPropagation::run().
removeMember()
void CodeNode::removeMember (NodeAddr< NodeBase * > NA, const DataFlowGraph & G)
Definition at line 493 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), assert(), llvm::rdf::NodeBase::Code, llvm::rdf::NodeBase::Code_struct::FirstM, G, getFirstMember(), llvm::rdf::NodeBase::getNext(), llvm::rdf::NodeAddr< T >::Id, llvm::rdf::NodeBase::Code_struct::LastM, llvm_unreachable, and llvm::rdf::NodeBase::setNext().
Referenced by llvm::rdf::DeadCodeElimination::erase().
setCode()
void llvm::rdf::CodeNode::setCode (void * C) inline
Definition at line 595 of file RDFGraph.h.
References llvm::rdf::NodeBase::Code, and llvm::rdf::NodeBase::Code_struct::CP.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp