LLVM: llvm::CallLowering::ValueAssigner Struct Reference
llvm::CallLowering::ValueAssigner Struct Reference
Argument handling is mostly uniform between the four places that make these decisions: function formal arguments, call instruction args, call instruction returns and function returns.
#include "llvm/CodeGen/GlobalISel/CallLowering.h"
Public Member Functions
ValueAssigner (bool IsIncoming, CCAssignFn *AssignFn_, CCAssignFn *AssignFnVarArg_=nullptr)
virtual ~ValueAssigner ()=default
bool isIncomingArgumentHandler () const
Returns true if the handler is dealing with incoming arguments, i.e.
virtual bool assignArg (unsigned ValNo, EVT OrigVT, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, const ArgInfo &Info, ISD::ArgFlagsTy Flags, CCState &State)
Wrap call to (typically tablegenerated CCAssignFn).
CCAssignFn * getAssignFn (bool IsVarArg) const
Select the appropriate assignment function depending on whether this is a variadic call.
Public Attributes
CCAssignFn * AssignFn
Assignment function to use for a general call.
CCAssignFn * AssignFnVarArg
Assignment function to use for a variadic call.
uint64_t StackOffset = 0
Stack offset for next argument.
Detailed Description
Argument handling is mostly uniform between the four places that make these decisions: function formal arguments, call instruction args, call instruction returns and function returns.
However, once a decision has been made on where an argument should go, exactly what happens can vary slightly. This class abstracts the differences.
ValueAssigner should not depend on any specific function state, and only determine the types and locations for arguments.
Definition at line 161 of file CallLowering.h.
Constructor & Destructor Documentation
ValueAssigner()
llvm::CallLowering::ValueAssigner::ValueAssigner (bool IsIncoming, CCAssignFn * AssignFn_, CCAssignFn * AssignFnVarArg_ = nullptr) inline
Definition at line 162 of file CallLowering.h.
References AssignFn, and AssignFnVarArg.
~ValueAssigner()
virtual llvm::CallLowering::ValueAssigner::~ValueAssigner () virtual default
Member Function Documentation
assignArg()
virtual bool llvm::CallLowering::ValueAssigner::assignArg (unsigned ValNo, EVT OrigVT, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, const ArgInfo & Info, ISD::ArgFlagsTy Flags, CCState & State) inline virtual
Wrap call to (typically tablegenerated CCAssignFn).
This may be overridden to track additional state information as arguments are assigned or apply target specific hacks around the legacy infrastructure.
Definition at line 185 of file CallLowering.h.
References getAssignFn(), llvm::CCState::getNextStackOffset(), and llvm::CCState::isVarArg().
Referenced by llvm::CallLowering::determineAssignments().
getAssignFn()
CCAssignFn* llvm::CallLowering::ValueAssigner::getAssignFn (bool IsVarArg) const inline
Select the appropriate assignment function depending on whether this is a variadic call.
Definition at line 208 of file CallLowering.h.
References AssignFn, and AssignFnVarArg.
Referenced by assignArg().
isIncomingArgumentHandler()
bool llvm::CallLowering::ValueAssigner::isIncomingArgumentHandler () const inline
Returns true if the handler is dealing with incoming arguments, i.e.
those that move values from some physical location to vregs.
Definition at line 177 of file CallLowering.h.
Member Data Documentation
AssignFn
CCAssignFn* llvm::CallLowering::ValueAssigner::AssignFn
Assignment function to use for a general call.
Definition at line 196 of file CallLowering.h.
Referenced by getAssignFn(), and ValueAssigner().
AssignFnVarArg
CCAssignFn* llvm::CallLowering::ValueAssigner::AssignFnVarArg
Assignment function to use for a variadic call.
This is usually the same as AssignFn on most targets.
Definition at line 200 of file CallLowering.h.
Referenced by getAssignFn(), and ValueAssigner().
StackOffset
uint64_t llvm::CallLowering::ValueAssigner::StackOffset = 0
Stack offset for next argument.
At the end of argument evaluation, this is typically the total stack size.
Definition at line 204 of file CallLowering.h.
Referenced by llvm::ARMCallLowering::lowerCall(), llvm::M68kCallLowering::lowerCall(), and llvm::AMDGPUCallLowering::lowerFormalArguments().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/GlobalISel/CallLowering.h
lib/CodeGen/GlobalISel/CallLowering.cpp