LLVM: llvm::coro::Shape Struct Reference
llvm::coro::Shape Struct Reference
#include "Transforms/Coroutines/CoroInternal.h"
Classes
struct AsyncLoweringStorage
struct RetconLoweringStorage
struct SwitchFieldIndex
struct SwitchLoweringStorage
Public Member Functions
CoroIdInst * getSwitchCoroId () const
AnyCoroIdRetconInst * getRetconCoroId () const
CoroIdAsyncInst * getAsyncCoroId () const
unsigned getSwitchIndexField () const
IntegerType * getIndexType () const
ConstantInt * getIndex (uint64_t Value) const
PointerType * getSwitchResumePointerType () const
FunctionType * getResumeFunctionType () const
ArrayRef< Type * > getRetconResultTypes () const
ArrayRef< Type * > getRetconResumeTypes () const
CallingConv::ID getResumeFunctionCC () const
AllocaInst * getPromiseAlloca () const
Instruction * getInsertPtAfterFramePtr () const
Value * emitAlloc (IRBuilder<> &Builder, Value *Size, CallGraph *CG) const
Allocate memory according to the rules of the active lowering.
void emitDealloc (IRBuilder<> &Builder, Value *Ptr, CallGraph *CG) const
Deallocate memory according to the rules of the active lowering.
Shape ()=default
Shape (Function &F, bool OptimizeFrame=false)
void buildFrom (Function &F)
Public Attributes
CoroBeginInst * CoroBegin
SmallVector< AnyCoroEndInst *, 4 > CoroEnds
SmallVector< CoroSizeInst *, 2 > CoroSizes
SmallVector< CoroAlignInst *, 2 > CoroAligns
SmallVector< AnyCoroSuspendInst *, 4 > CoroSuspends
SmallVector< CallInst *, 2 > SwiftErrorOps
coro::ABI ABI
StructType * FrameTy
Align FrameAlign
uint64_t FrameSize
Value * FramePtr
BasicBlock * AllocaSpillBlock
bool OptimizeFrame
This would only be true if optimization are enabled.
union {
SwitchLoweringStorage SwitchLowering
RetconLoweringStorage RetconLowering
AsyncLoweringStorage AsyncLowering
};
Detailed Description
Definition at line 73 of file CoroInternal.h.
Constructor & Destructor Documentation
Shape() [1/2]
llvm::coro::Shape::Shape () default
Shape() [2/2]
llvm::coro::Shape::Shape (Function & F, bool OptimizeFrame = false) inline explicit
Definition at line 257 of file CoroInternal.h.
References F.
Member Function Documentation
buildFrom()
void coro::Shape::buildFrom (Function & F)
Definition at line 172 of file Coroutines.cpp.
References llvm::coro::Async, llvm::changeToUnreachable(), clear(), createCoroSave(), llvm::Type::dump(), E, F, llvm::UndefValue::get(), llvm::Type::getInt8PtrTy(), I, llvm::instructions(), llvm::CastInst::isBitCastable(), llvm::Type::isVoidTy(), llvm_unreachable, llvm::NVPTXISD::Prototype, llvm::report_fatal_error(), llvm::coro::Retcon, llvm::coro::RetconOnce, SI, llvm::ArrayRef< T >::size(), std::swap(), llvm::coro::Switch, and llvm::RegState::Undef.
emitAlloc()
Value * coro::Shape::emitAlloc (IRBuilder<> & Builder, Value * Size, CallGraph * CG) const
Allocate memory according to the rules of the active lowering.
Parameters
CG - if non-null, will be updated for the new call
Definition at line 453 of file Coroutines.cpp.
References addCallToCallGraph(), llvm::coro::Async, Builder, llvm_unreachable, propagateCallAttrsFromCallee(), llvm::coro::Retcon, llvm::coro::RetconOnce, and llvm::coro::Switch.
Referenced by splitRetconCoroutine().
emitDealloc()
void coro::Shape::emitDealloc (IRBuilder<> & Builder, Value * Ptr, CallGraph * CG) const
Deallocate memory according to the rules of the active lowering.
Parameters
CG - if non-null, will be updated for the new call
Definition at line 476 of file Coroutines.cpp.
References addCallToCallGraph(), llvm::coro::Async, Builder, llvm_unreachable, propagateCallAttrsFromCallee(), Ptr, llvm::coro::Retcon, llvm::coro::RetconOnce, and llvm::coro::Switch.
Referenced by maybeFreeRetconStorage().
getAsyncCoroId()
CoroIdAsyncInst* llvm::coro::Shape::getAsyncCoroId () const inline
Definition at line 157 of file CoroInternal.h.
References assert(), llvm::coro::Async, and llvm::CoroBeginInst::getId().
getIndex()
ConstantInt* llvm::coro::Shape::getIndex (uint64_t Value) const inline
Definition at line 172 of file CoroInternal.h.
References llvm::ConstantInt::get().
Referenced by createResumeEntryBlock().
getIndexType()
IntegerType* llvm::coro::Shape::getIndexType () const inline
Definition at line 167 of file CoroInternal.h.
References assert(), llvm::StructType::getElementType(), and llvm::coro::Switch.
Referenced by createResumeEntryBlock().
getInsertPtAfterFramePtr()
Instruction* llvm::coro::Shape::getInsertPtAfterFramePtr () const inline
Definition at line 240 of file CoroInternal.h.
References I.
Referenced by buildFrameDebugInfo(), insertSpills(), and updateCoroFrame().
getPromiseAlloca()
AllocaInst* llvm::coro::Shape::getPromiseAlloca () const inline
Definition at line 234 of file CoroInternal.h.
References llvm::coro::Switch.
Referenced by buildFrameDebugInfo(), and buildFrameType().
getResumeFunctionCC()
CallingConv::ID llvm::coro::Shape::getResumeFunctionCC () const inline
Definition at line 220 of file CoroInternal.h.
References llvm::coro::Async, llvm::CallingConv::Fast, llvm_unreachable, llvm::coro::Retcon, llvm::coro::RetconOnce, and llvm::coro::Switch.
getResumeFunctionType()
FunctionType* llvm::coro::Shape::getResumeFunctionType () const inline
Definition at line 182 of file CoroInternal.h.
References llvm::coro::Async, llvm::FunctionType::get(), llvm::Type::getContext(), llvm::Type::getPointerTo(), llvm::Type::getVoidTy(), llvm_unreachable, llvm::coro::Retcon, llvm::coro::RetconOnce, and llvm::coro::Switch.
Referenced by createCloneDeclaration().
getRetconCoroId()
AnyCoroIdRetconInst* llvm::coro::Shape::getRetconCoroId () const inline
Definition at line 151 of file CoroInternal.h.
References assert(), llvm::CoroBeginInst::getId(), llvm::coro::Retcon, and llvm::coro::RetconOnce.
Referenced by buildFrameType().
getRetconResultTypes()
ArrayRef<Type*> llvm::coro::Shape::getRetconResultTypes () const inline
Definition at line 198 of file CoroInternal.h.
References assert(), llvm::Instruction::getFunction(), llvm::Function::getFunctionType(), llvm::coro::Retcon, and llvm::coro::RetconOnce.
Referenced by splitRetconCoroutine().
getRetconResumeTypes()
ArrayRef<Type*> llvm::coro::Shape::getRetconResumeTypes () const inline
Definition at line 211 of file CoroInternal.h.
References assert(), llvm::coro::Retcon, and llvm::coro::RetconOnce.
getSwitchCoroId()
CoroIdInst* llvm::coro::Shape::getSwitchCoroId () const inline
Definition at line 146 of file CoroInternal.h.
References assert(), llvm::CoroBeginInst::getId(), and llvm::coro::Switch.
Referenced by llvm::coro::buildCoroutineFrame(), setCoroInfo(), and updateCoroFrame().
getSwitchIndexField()
unsigned llvm::coro::Shape::getSwitchIndexField () const inline
Definition at line 162 of file CoroInternal.h.
References assert(), and llvm::coro::Switch.
Referenced by createResumeEntryBlock().
getSwitchResumePointerType()
PointerType* llvm::coro::Shape::getSwitchResumePointerType () const inline
Definition at line 176 of file CoroInternal.h.
References assert(), llvm::StructType::getElementType(), and llvm::coro::Switch.
Member Data Documentation
@627
union { ... }
ABI
coro::ABI llvm::coro::Shape::ABI
Definition at line 96 of file CoroInternal.h.
Referenced by llvm::coro::buildCoroutineFrame(), buildFrameDebugInfo(), buildFrameType(), collectFrameAlloca(), createCloneDeclaration(), createResumeEntryBlock(), handleNoSuspendCoroutine(), insertSpills(), markCoroutineAsDone(), maybeFreeRetconStorage(), replaceFrameSizeAndAlignment(), replaceSwiftErrorOps(), setCoroInfo(), simplifySuspendPoints(), splitAsyncCoroutine(), splitCoroutine(), splitRetconCoroutine(), splitSwitchCoroutine(), updateAsyncFuncPointerContextSize(), updateCallGraphAfterCoroutineSplit(), and updateCoroFrame().
AllocaSpillBlock
BasicBlock* llvm::coro::Shape::AllocaSpillBlock
Definition at line 102 of file CoroInternal.h.
Referenced by clear(), and insertSpills().
AsyncLowering
AsyncLoweringStorage llvm::coro::Shape::AsyncLowering
Definition at line 143 of file CoroInternal.h.
Referenced by buildFrameType(), splitAsyncCoroutine(), and updateAsyncFuncPointerContextSize().
CoroAligns
SmallVector<CoroAlignInst *, 2> llvm::coro::Shape::CoroAligns
Definition at line 77 of file CoroInternal.h.
Referenced by replaceFrameSizeAndAlignment().
CoroBegin
CoroBeginInst* llvm::coro::Shape::CoroBegin
Definition at line 74 of file CoroInternal.h.
Referenced by llvm::coro::buildCoroutineFrame(), clear(), collectFrameAlloca(), createFramePtr(), handleNoSuspendCoroutine(), insertSpills(), simplifySuspendPoints(), splitAsyncCoroutine(), splitCoroutine(), splitRetconCoroutine(), and updateCallGraphAfterCoroutineSplit().
CoroEnds
SmallVector<AnyCoroEndInst *, 4> llvm::coro::Shape::CoroEnds
Definition at line 75 of file CoroInternal.h.
Referenced by llvm::coro::buildCoroutineFrame(), and clear().
CoroSizes
SmallVector<CoroSizeInst *, 2> llvm::coro::Shape::CoroSizes
Definition at line 76 of file CoroInternal.h.
Referenced by clear(), and replaceFrameSizeAndAlignment().
CoroSuspends
SmallVector<AnyCoroSuspendInst *, 4> llvm::coro::Shape::CoroSuspends
Definition at line 78 of file CoroInternal.h.
Referenced by llvm::coro::buildCoroutineFrame(), buildFrameType(), clear(), collectFrameAlloca(), createResumeEntryBlock(), eliminateSwiftErrorArgument(), replaceSwiftErrorOps(), llvm::CoroSplitPass::run(), simplifySuspendPoints(), sinkLifetimeStartMarkers(), splitAsyncCoroutine(), splitCoroutine(), and splitRetconCoroutine().
FrameAlign
Align llvm::coro::Shape::FrameAlign
Definition at line 99 of file CoroInternal.h.
Referenced by buildFrameDebugInfo(), buildFrameType(), handleNoSuspendCoroutine(), and replaceFrameSizeAndAlignment().
FramePtr
Value* llvm::coro::Shape::FramePtr
Definition at line 101 of file CoroInternal.h.
Referenced by buildFrameDebugInfo(), clear(), createFramePtr(), createResumeEntryBlock(), insertSpills(), splitAsyncCoroutine(), splitRetconCoroutine(), and updateCoroFrame().
FrameSize
uint64_t llvm::coro::Shape::FrameSize
Definition at line 100 of file CoroInternal.h.
Referenced by buildFrameDebugInfo(), and buildFrameType().
FrameTy
StructType* llvm::coro::Shape::FrameTy
Definition at line 98 of file CoroInternal.h.
Referenced by buildFrameDebugInfo(), clear(), createFramePtr(), createResumeEntryBlock(), handleNoSuspendCoroutine(), insertSpills(), markCoroutineAsDone(), replaceFrameSizeAndAlignment(), splitRetconCoroutine(), and updateCoroFrame().
OptimizeFrame
bool llvm::coro::Shape::OptimizeFrame
This would only be true if optimization are enabled.
Definition at line 105 of file CoroInternal.h.
Referenced by insertSpills(), and splitCoroutine().
RetconLowering
RetconLoweringStorage llvm::coro::Shape::RetconLowering
Definition at line 142 of file CoroInternal.h.
Referenced by buildFrameType(), maybeFreeRetconStorage(), and splitRetconCoroutine().
SwiftErrorOps
SmallVector<CallInst*, 2> llvm::coro::Shape::SwiftErrorOps
Definition at line 79 of file CoroInternal.h.
Referenced by emitGetSwiftErrorValue(), emitSetSwiftErrorValue(), and replaceSwiftErrorOps().
SwitchLowering
SwitchLoweringStorage llvm::coro::Shape::SwitchLowering
Definition at line 141 of file CoroInternal.h.
Referenced by llvm::coro::buildCoroutineFrame(), buildFrameDebugInfo(), buildFrameType(), collectFrameAlloca(), createResumeEntryBlock(), insertSpills(), and simplifySuspendPoints().
The documentation for this struct was generated from the following files:
lib/Transforms/Coroutines/CoroInternal.h
lib/Transforms/Coroutines/Coroutines.cpp