LLVM: llvm::VPlanTransforms Struct Reference
llvm::VPlanTransforms Struct Reference
#include "Transforms/Vectorize/VPlanTransforms.h"
Static Public Member Functions
static void VPInstructionsToVPRecipes (Loop *OrigLoop, VPlanPtr &Plan, function_ref< const InductionDescriptor *(PHINode *)> GetIntOrFpInductionDescriptor, SmallPtrSetImpl< Instruction * > &DeadInstructions, ScalarEvolution &SE, const TargetLibraryInfo &TLI)
Replaces the VPInstructions in Plan with corresponding widen recipes.
static bool sinkScalarOperands (VPlan &Plan)
static bool mergeReplicateRegionsIntoSuccessors (VPlan &Plan)
Merge replicate regions in their successor region, if a replicate region is connected to a successor replicate region with the same predicate by a single, empty VPBasicBlock.
static bool mergeBlocksIntoPredecessors (VPlan &Plan)
Remove redundant VPBasicBlocks by merging them into their predecessor if the predecessor has a single successor.
static void removeRedundantInductionCasts (VPlan &Plan)
Remove redundant casts of inductions.
static void removeRedundantCanonicalIVs (VPlan &Plan)
Try to replace VPWidenCanonicalIVRecipes with a widened canonical IV recipe, if it exists.
static void removeDeadRecipes (VPlan &Plan)
static void optimizeInductions (VPlan &Plan, ScalarEvolution &SE)
If any user of a VPWidenIntOrFpInductionRecipe needs scalar values, provide them by building scalar steps off of the canonical scalar IV and update the original IV's users.
static void removeRedundantExpandSCEVRecipes (VPlan &Plan)
Remove redundant EpxandSCEVRecipes in Plan's entry block by replacing them with already existing recipes expanding the same SCEV expression.
static void adjustFixedOrderRecurrences (VPlan &Plan, VPBuilder &Builder)
Sink users of fixed-order recurrences after the recipe defining their previous value.
static void optimizeForVFAndUF (VPlan &Plan, ElementCount BestVF, unsigned BestUF, PredicatedScalarEvolution &PSE)
Optimize Plan based on BestVF and BestUF.
Detailed Description
Definition at line 30 of file VPlanTransforms.h.
Member Function Documentation
adjustFixedOrderRecurrences()
void VPlanTransforms::adjustFixedOrderRecurrences (VPlan & Plan, VPBuilder & Builder) static
Sink users of fixed-order recurrences after the recipe defining their previous value.
Then introduce FirstOrderRecurrenceSplice VPInstructions to combine the value from the recurrence phis and previous values. The current implementation assumes all users can be sunk after the previous value, which is enforced by earlier legality checks.
Definition at line 675 of file VPlanTransforms.cpp.
References assert(), Builder, llvm::VPInstruction::FirstOrderRecurrenceSplice, llvm::X86ISD::FOR, llvm::VPRegionBlock::getEntry(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBasicBlock::getFirstNonPhi(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::VPRecipeBase::getParent(), GetReplicateRegion(), llvm::VPlan::getVectorLoopRegion(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBasicBlock::phis(), llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate(), and sinkRecurrenceUsersAfterPrevious().
mergeBlocksIntoPredecessors()
bool VPlanTransforms::mergeBlocksIntoPredecessors (VPlan & Plan) static
Remove redundant VPBasicBlocks by merging them into their predecessor if the predecessor has a single successor.
Definition at line 317 of file VPlanTransforms.cpp.
References llvm::VPBlockUtils::connectBlocks(), llvm::VPBlockUtils::disconnectBlocks(), llvm::VPBasicBlock::end(), llvm::VPlan::getEntry(), llvm::make_early_inc_range(), llvm::to_vector(), and llvm::vp_depth_first_deep().
mergeReplicateRegionsIntoSuccessors()
bool VPlanTransforms::mergeReplicateRegionsIntoSuccessors (VPlan & Plan) static
Merge replicate regions in their successor region, if a replicate region is connected to a successor replicate region with the same predicate by a single, empty VPBasicBlock.
Definition at line 229 of file VPlanTransforms.cpp.
References assert(), llvm::VPBlockUtils::connectBlocks(), llvm::SetVector< T, Vector, Set >::contains(), llvm::VPBlockUtils::disconnectBlocks(), E, llvm::VPlan::getEntry(), llvm::VPBasicBlock::getFirstNonPhi(), getPredicatedMask(), getPredicatedThenBlock(), llvm::VPBlockBase::getSingleSuccessor(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::make_early_inc_range(), llvm::reverse(), llvm::to_vector(), llvm::VPValue::users(), and llvm::vp_depth_first_deep().
optimizeForVFAndUF()
void VPlanTransforms::optimizeForVFAndUF (VPlan & Plan, ElementCount BestVF, unsigned BestUF, PredicatedScalarEvolution & PSE) static
Optimize Plan based on BestVF and BestUF.
This may restrict the resulting plan to BestVF and BestUF.
Definition at line 498 of file VPlanTransforms.cpp.
References llvm::VPBasicBlock::appendRecipe(), assert(), llvm::VPBasicBlock::back(), llvm::VPInstruction::BranchOnCond, llvm::VPInstruction::BranchOnCount, canSimplifyBranchOnCond(), llvm::createTripCountSCEV(), llvm::VPlan::getCanonicalIV(), llvm::ScalarEvolution::getConstant(), llvm::ScalarEvolution::getContext(), llvm::VPBlockBase::getExitingBasicBlock(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::VPValue::getLiveInIRValue(), llvm::VPlan::getOrAddExternalDef(), llvm::PredicatedScalarEvolution::getSE(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::ConstantInt::getTrue(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::VPlan::getVectorLoopRegion(), llvm::VPlan::hasUF(), llvm::VPlan::hasVF(), llvm::CmpInst::ICMP_ULE, llvm::ScalarEvolution::isKnownPredicate(), llvm::SCEV::isZero(), llvm::VPlan::setUF(), llvm::VPlan::setVF(), and llvm::M68kBeads::Term.
Referenced by llvm::LoopVectorizationPlanner::executePlan().
optimizeInductions()
void VPlanTransforms::optimizeInductions (VPlan & Plan, ScalarEvolution & SE) static
If any user of a VPWidenIntOrFpInductionRecipe needs scalar values, provide them by building scalar steps off of the canonical scalar IV and update the original IV's users.
This is an optional optimization to reduce the needs of vector extracts.
Definition at line 426 of file VPlanTransforms.cpp.
References E, llvm::VPlan::getCanonicalIV(), llvm::VPValue::getDefiningRecipe(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBasicBlock::getFirstNonPhi(), llvm::ElementCount::getFixed(), llvm::VPUser::getNumOperands(), llvm::VPUser::getOperand(), llvm::vputils::getOrCreateVPValueForSCEVExpr(), llvm::VPlan::getVectorLoopRegion(), llvm::VPlan::hasVF(), I, llvm::VPBasicBlock::insert(), llvm::VPCanonicalIVPHIRecipe::isCanonical(), llvm::none_of(), llvm::VPBasicBlock::phis(), llvm::VPUser::setOperand(), ToRemove, Users, and llvm::VPUser::usesScalars().
removeDeadRecipes()
void VPlanTransforms::removeDeadRecipes (VPlan & Plan) static
Definition at line 409 of file VPlanTransforms.cpp.
References llvm::any_of(), llvm::VPlan::getEntry(), llvm::make_early_inc_range(), and llvm::reverse().
removeRedundantCanonicalIVs()
void VPlanTransforms::removeRedundantCanonicalIVs (VPlan & Plan) static
Try to replace VPWidenCanonicalIVRecipes with a widened canonical IV recipe, if it exists.
Definition at line 376 of file VPlanTransforms.cpp.
References llvm::VPRecipeBase::eraseFromParent(), llvm::VPlan::getCanonicalIV(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPWidenCanonicalIVRecipe::getScalarType(), llvm::VPlan::getVectorLoopRegion(), llvm::vputils::onlyFirstLaneUsed(), llvm::VPBasicBlock::phis(), llvm::VPValue::replaceAllUsesWith(), and llvm::VPValue::users().
removeRedundantExpandSCEVRecipes()
void VPlanTransforms::removeRedundantExpandSCEVRecipes (VPlan & Plan) static
Remove redundant EpxandSCEVRecipes in Plan's entry block by replacing them with already existing recipes expanding the same SCEV expression.
Definition at line 472 of file VPlanTransforms.cpp.
References llvm::VPlan::getEntry(), llvm::VPBlockBase::getEntryBasicBlock(), I, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), and llvm::make_early_inc_range().
removeRedundantInductionCasts()
void VPlanTransforms::removeRedundantInductionCasts (VPlan & Plan) static
Remove redundant casts of inductions.
Such redundant casts are casts of induction variables that can be ignored, because we already proved that the casted phi is equal to the uncasted phi in the vectorized loop. There is no need to vectorize the cast - the same value can be used for both the phi and casts in the vector loop.
Definition at line 344 of file VPlanTransforms.cpp.
References llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPlan::getVectorLoopRegion(), llvm::VPDef::getVPSingleValue(), IV, llvm::VPBasicBlock::phis(), llvm::VPValue::replaceAllUsesWith(), llvm::reverse(), and llvm::VPValue::users().
sinkScalarOperands()
bool VPlanTransforms::sinkScalarOperands (VPlan & Plan) static
Definition at line 111 of file VPlanTransforms.cpp.
References llvm::all_of(), llvm::tgtok::Def, llvm::VPlan::getEntry(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBlockBase::getExitingBasicBlock(), llvm::VPBasicBlock::getFirstNonPhi(), llvm::VPRecipeBase::getParent(), llvm::VPBlockBase::getSingleSuccessor(), llvm::VPBlockBase::getSuccessors(), llvm::VPDef::getVPSingleValue(), llvm::VPlan::hasScalarVFOnly(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::VPRecipeBase::mayHaveSideEffects(), llvm::VPRecipeBase::mayReadOrWriteMemory(), llvm::VPRecipeBase::moveBefore(), llvm::VPUser::operands(), llvm::SetVector< T, Vector, Set >::size(), llvm::to_vector(), llvm::VPValue::users(), and llvm::vp_depth_first_deep().
VPInstructionsToVPRecipes()
void VPlanTransforms::VPInstructionsToVPRecipes (Loop * OrigLoop, VPlanPtr & Plan, function_ref< const InductionDescriptor *(PHINode *)> GetIntOrFpInductionDescriptor, SmallPtrSetImpl< Instruction * > & DeadInstructions, ScalarEvolution & SE, const TargetLibraryInfo & TLI) static
Replaces the VPInstructions in Plan with corresponding widen recipes.
Definition at line 26 of file VPlanTransforms.cpp.
References assert(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::tgtok::Def, llvm::VPDef::definedValues(), GEP, llvm::getLoadStorePointerOperand(), llvm::VPDef::getNumDefinedValues(), llvm::vputils::getOrCreateVPValueForSCEVExpr(), llvm::ScalarEvolution::getSCEV(), llvm::VPValue::getUnderlyingValue(), llvm::getVectorIntrinsicIDForCall(), llvm::VPDef::getVPSingleValue(), llvm::VPRecipeBase::insertBefore(), llvm::ScalarEvolution::isLoopInvariant(), llvm::SPII::Load, llvm::make_early_inc_range(), llvm::make_range(), llvm::User::operands(), llvm::VPValue::replaceAllUsesWith(), SI, llvm::SPII::Store, and llvm::M68kBeads::Term.
The documentation for this struct was generated from the following files:
lib/Transforms/Vectorize/VPlanTransforms.h
lib/Transforms/Vectorize/VPlanTransforms.cpp