LLVM: llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable > Struct Template Reference
llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable > Struct Template Reference
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
CompareOp_match (const Pred_P &Pred, const LHS_P &LHS, const RHS_P &RHS)
template<typename OpTy >
bool match (const MachineRegisterInfo &MRI, OpTy &&Op)
Public Attributes
Pred_P P
LHS_P L
RHS_P R
Detailed Description
template<typename Pred_P, typename LHS_P, typename RHS_P, unsigned Opcode, bool Commutable = false>
struct llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >
Definition at line 643 of file MIPatternMatch.h.
Constructor & Destructor Documentation
CompareOp_match()
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode, bool Commutable = false> llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::CompareOp_match (const Pred_P & Pred, const LHS_P & LHS, const RHS_P & RHS) inline
Definition at line 648 of file MIPatternMatch.h.
Member Function Documentation
match()
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode, bool Commutable = false> template<typename OpTy > bool llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::match (const MachineRegisterInfo & MRI, OpTy && Op) inline
Definition at line 652 of file MIPatternMatch.h.
References llvm::MCID::Commutable, llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getPredicate(), llvm::MachineOperand::getReg(), llvm::CmpInst::getSwappedPredicate(), llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::L, LHS, llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::mi_match(), MRI, llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::P, llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::R, and RHS.
Member Data Documentation
L
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode, bool Commutable = false> LHS_P llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::L
Definition at line 645 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::match().
P
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode, bool Commutable = false> Pred_P llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::P
Definition at line 644 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::match().
R
template<typename Pred_P , typename LHS_P , typename RHS_P , unsigned Opcode, bool Commutable = false> RHS_P llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::R
Definition at line 646 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::CompareOp_match< Pred_P, LHS_P, RHS_P, Opcode, Commutable >::match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h