LLVM: llvm::IRSimilarity::IRInstructionDataTraits Struct Reference
llvm::IRSimilarity::IRInstructionDataTraits Struct Reference
#include "llvm/Analysis/IRSimilarityIdentifier.h"
Static Public Member Functions
static IRInstructionData * getEmptyKey ()
static IRInstructionData * getTombstoneKey ()
static unsigned getHashValue (const IRInstructionData *E)
static bool isEqual (const IRInstructionData *LHS, const IRInstructionData *RHS)
Detailed Description
Definition at line 312 of file IRSimilarityIdentifier.h.
Member Function Documentation
getEmptyKey()
static IRInstructionData* llvm::IRSimilarity::IRInstructionDataTraits::getEmptyKey () inline static
Definition at line 313 of file IRSimilarityIdentifier.h.
Referenced by isEqual().
getHashValue()
static unsigned llvm::IRSimilarity::IRInstructionDataTraits::getHashValue (const IRInstructionData * E) inline static
Definition at line 318 of file IRSimilarityIdentifier.h.
References assert(), E, and llvm::hash_value().
getTombstoneKey()
static IRInstructionData* llvm::IRSimilarity::IRInstructionDataTraits::getTombstoneKey () inline static
Definition at line 314 of file IRSimilarityIdentifier.h.
Referenced by isEqual().
isEqual()
static bool llvm::IRSimilarity::IRInstructionDataTraits::isEqual (const IRInstructionData * LHS, const IRInstructionData * RHS) inline static
Definition at line 324 of file IRSimilarityIdentifier.h.
References assert(), getEmptyKey(), getTombstoneKey(), llvm::IRSimilarity::isClose(), LHS, and RHS.
The documentation for this struct was generated from the following file:
include/llvm/Analysis/IRSimilarityIdentifier.h