LLVM: llvm::SCEVDivision Struct Reference
llvm::SCEVDivision Struct Reference
#include "llvm/Analysis/ScalarEvolutionDivision.h"
Public Member Functions
void visitPtrToIntExpr (const SCEVPtrToIntExpr *Numerator)
void visitTruncateExpr (const SCEVTruncateExpr *Numerator)
void visitZeroExtendExpr (const SCEVZeroExtendExpr *Numerator)
void visitSignExtendExpr (const SCEVSignExtendExpr *Numerator)
void visitUDivExpr (const SCEVUDivExpr *Numerator)
void visitSMaxExpr (const SCEVSMaxExpr *Numerator)
void visitUMaxExpr (const SCEVUMaxExpr *Numerator)
void visitSMinExpr (const SCEVSMinExpr *Numerator)
void visitUMinExpr (const SCEVUMinExpr *Numerator)
void visitSequentialUMinExpr (const SCEVSequentialUMinExpr *Numerator)
void visitUnknown (const SCEVUnknown *Numerator)
void visitCouldNotCompute (const SCEVCouldNotCompute *Numerator)
void visitConstant (const SCEVConstant *Numerator)
void visitAddRecExpr (const SCEVAddRecExpr *Numerator)
void visitAddExpr (const SCEVAddExpr *Numerator)
void visitMulExpr (const SCEVMulExpr *Numerator)
Public Member Functions inherited from llvm::SCEVVisitor< SCEVDivision, void >
void visit (const SCEV *S)
void visitCouldNotCompute (const SCEVCouldNotCompute *S)
Static Public Member Functions
static void divide (ScalarEvolution &SE, const SCEV *Numerator, const SCEV *Denominator, const SCEV **Quotient, const SCEV **Remainder)
Detailed Description
Definition at line 26 of file ScalarEvolutionDivision.h.
Member Function Documentation
divide()
void SCEVDivision::divide (ScalarEvolution & SE, const SCEV * Numerator, const SCEV * Denominator, const SCEV ** Quotient, const SCEV ** Remainder) static
Definition at line 55 of file ScalarEvolutionDivision.cpp.
References assert(), D, llvm::SCEV::isOne(), and llvm::SCEV::isZero().
Referenced by llvm::computeAccessFunctions(), llvm::findArrayDimensions(), findArrayDimensionsRec(), visitAddExpr(), visitAddRecExpr(), and visitMulExpr().
visitAddExpr()
void SCEVDivision::visitAddExpr (const SCEVAddExpr * Numerator)
Definition at line 146 of file ScalarEvolutionDivision.cpp.
References divide(), llvm::ScalarEvolution::getAddExpr(), llvm::SCEV::getType(), and llvm::SCEVNAryExpr::operands().
visitAddRecExpr()
void SCEVDivision::visitAddRecExpr (const SCEVAddRecExpr * Numerator)
Definition at line 129 of file ScalarEvolutionDivision.cpp.
References divide(), llvm::ScalarEvolution::getAddRecExpr(), llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEV::getType(), and llvm::SCEVAddRecExpr::isAffine().
visitConstant()
void SCEVDivision::visitConstant (const SCEVConstant * Numerator)
Definition at line 108 of file ScalarEvolutionDivision.cpp.
References D, llvm::SCEVConstant::getAPInt(), llvm::APInt::getBitWidth(), llvm::ScalarEvolution::getConstant(), llvm::APInt::sdivrem(), and llvm::APInt::sext().
visitCouldNotCompute()
void llvm::SCEVDivision::visitCouldNotCompute (const SCEVCouldNotCompute * Numerator) inline
Definition at line 47 of file ScalarEvolutionDivision.h.
visitMulExpr()
void SCEVDivision::visitMulExpr (const SCEVMulExpr * Numerator)
Definition at line 172 of file ScalarEvolutionDivision.cpp.
References divide(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEV::getType(), llvm::SCEV::isZero(), llvm::SCEVNAryExpr::operands(), and llvm::SCEVParameterRewriter::rewrite().
visitPtrToIntExpr()
void llvm::SCEVDivision::visitPtrToIntExpr (const SCEVPtrToIntExpr * Numerator) inline
Definition at line 36 of file ScalarEvolutionDivision.h.
visitSequentialUMinExpr()
void llvm::SCEVDivision::visitSequentialUMinExpr (const SCEVSequentialUMinExpr * Numerator) inline
Definition at line 45 of file ScalarEvolutionDivision.h.
visitSignExtendExpr()
void llvm::SCEVDivision::visitSignExtendExpr (const SCEVSignExtendExpr * Numerator) inline
Definition at line 39 of file ScalarEvolutionDivision.h.
visitSMaxExpr()
void llvm::SCEVDivision::visitSMaxExpr (const SCEVSMaxExpr * Numerator) inline
Definition at line 41 of file ScalarEvolutionDivision.h.
visitSMinExpr()
void llvm::SCEVDivision::visitSMinExpr (const SCEVSMinExpr * Numerator) inline
Definition at line 43 of file ScalarEvolutionDivision.h.
visitTruncateExpr()
void llvm::SCEVDivision::visitTruncateExpr (const SCEVTruncateExpr * Numerator) inline
Definition at line 37 of file ScalarEvolutionDivision.h.
visitUDivExpr()
void llvm::SCEVDivision::visitUDivExpr (const SCEVUDivExpr * Numerator) inline
Definition at line 40 of file ScalarEvolutionDivision.h.
visitUMaxExpr()
void llvm::SCEVDivision::visitUMaxExpr (const SCEVUMaxExpr * Numerator) inline
Definition at line 42 of file ScalarEvolutionDivision.h.
visitUMinExpr()
void llvm::SCEVDivision::visitUMinExpr (const SCEVUMinExpr * Numerator) inline
Definition at line 44 of file ScalarEvolutionDivision.h.
visitUnknown()
void llvm::SCEVDivision::visitUnknown (const SCEVUnknown * Numerator) inline
Definition at line 46 of file ScalarEvolutionDivision.h.
visitZeroExtendExpr()
void llvm::SCEVDivision::visitZeroExtendExpr (const SCEVZeroExtendExpr * Numerator) inline
Definition at line 38 of file ScalarEvolutionDivision.h.
The documentation for this struct was generated from the following files:
include/llvm/Analysis/ScalarEvolutionDivision.h
lib/Analysis/ScalarEvolutionDivision.cpp