LLVM: llvm::APFloatBase Struct Reference
llvm::APFloatBase Struct Reference
A self-contained host- and target-independent arbitrary-precision floating-point software implementation.
#include "llvm/ADT/APFloat.h"
Public Types
enum cmpResult { cmpLessThan, cmpEqual, cmpGreaterThan, cmpUnordered }
IEEE-754R 5.11: Floating Point Comparison Relations.
enum opStatus {
opOK = 0x00, opInvalidOp = 0x01, opDivByZero = 0x02, opOverflow = 0x04,
opUnderflow = 0x08, opInexact = 0x10
}
IEEE-754R 7: Default exception handling.
enum fltCategory { fcInfinity, fcNaN, fcNormal, fcZero }
Category of internally-represented number.
enum uninitializedTag { uninitialized }
Convenience enum used to construct an uninitialized APFloat.
enum IlogbErrorKinds { IEK_Zero = INT_MIN + 1, IEK_NaN = INT_MIN, IEK_Inf = INT_MAX }
Enumeration of ilogb error results.
typedef APInt::WordType integerPart
typedef int32_t ExponentType
A signed type to represent a floating point numbers unbiased exponent.
using roundingMode = llvm::RoundingMode
IEEE-754R 4.3: Rounding-direction attributes.
Static Public Member Functions
static unsigned int semanticsPrecision (const fltSemantics &)
static ExponentType semanticsMinExponent (const fltSemantics &)
static ExponentType semanticsMaxExponent (const fltSemantics &)
static unsigned int semanticsSizeInBits (const fltSemantics &)
static unsigned int semanticsIntSizeInBits (const fltSemantics &, bool)
static unsigned getSizeInBits (const fltSemantics &Sem)
Returns the size of the floating point number (in bits) in the given semantics.
Static Public Attributes
static constexpr unsigned integerPartWidth = APInt::APINT_BITS_PER_WORD
static constexpr roundingMode rmNearestTiesToEven
static constexpr roundingMode rmTowardPositive = RoundingMode::TowardPositive
static constexpr roundingMode rmTowardNegative = RoundingMode::TowardNegative
static constexpr roundingMode rmTowardZero = RoundingMode::TowardZero
static constexpr roundingMode rmNearestTiesToAway
Floating Point Semantics.
enum Semantics {
S_IEEEhalf, S_BFloat, S_IEEEsingle, S_IEEEdouble,
S_IEEEquad, S_PPCDoubleDouble, S_Float8E5M2, S_Float8E5M2FNUZ,
S_Float8E4M3FN, S_Float8E4M3FNUZ, S_x87DoubleExtended, S_MaxSemantics = S_x87DoubleExtended
}
static const llvm::fltSemantics & EnumToSemantics (Semantics S)
static Semantics SemanticsToEnum (const llvm::fltSemantics &Sem)
static const fltSemantics & IEEEhalf () LLVM_READNONE
static const fltSemantics & BFloat () LLVM_READNONE
static const fltSemantics & IEEEsingle () LLVM_READNONE
static const fltSemantics & IEEEdouble () LLVM_READNONE
static const fltSemantics & IEEEquad () LLVM_READNONE
static const fltSemantics & PPCDoubleDouble () LLVM_READNONE
static const fltSemantics & Float8E5M2 () LLVM_READNONE
static const fltSemantics & Float8E5M2FNUZ () LLVM_READNONE
static const fltSemantics & Float8E4M3FN () LLVM_READNONE
static const fltSemantics & Float8E4M3FNUZ () LLVM_READNONE
static const fltSemantics & x87DoubleExtended () LLVM_READNONE
static const fltSemantics & Bogus () LLVM_READNONE
A Pseudo fltsemantic used to construct APFloats that cannot conflict with anything real.
Detailed Description
A self-contained host- and target-independent arbitrary-precision floating-point software implementation.
APFloat uses bignum integer arithmetic as provided by static functions in the APInt class. The library will work with bignum integers whose parts are any unsigned type at least 16 bits wide, but 64 bits is recommended.
Written for clarity rather than speed, in particular with a view to use in the front-end of a cross compiler so that target arithmetic can be correctly performed on the host. Performance should nonetheless be reasonable, particularly for its intended use. It may be useful as a base implementation for a run-time library during development of a faster target-specific one.
All 5 rounding modes in the IEEE-754R draft are handled correctly for all implemented operations. Currently implemented operations are add, subtract, multiply, divide, fused-multiply-add, conversion-to-float, conversion-to-integer and conversion-from-integer. New rounding modes (e.g. away from zero) can be added with three or four lines of code.
Four formats are built-in: IEEE single precision, double precision, quadruple precision, and x87 80-bit extended double (when operating with full extended precision). Adding a new format that obeys IEEE semantics only requires adding two lines of code: a declaration and definition of the format.
All operations return the status of that operation as an exception bit-mask, so multiple operations can be done consecutively with their results or-ed together. The returned status can be useful for compiler diagnostics; e.g., inexact, underflow and overflow can be easily diagnosed on constant folding, and compiler optimizers can determine what exceptions would be raised by folding operations and optimize, or perhaps not optimize, accordingly.
At present, underflow tininess is detected after rounding; it should be straight forward to add support for the before-rounding case too.
The library reads hexadecimal floating point numbers as per C99, and correctly rounds if necessary according to the specified rounding mode. Syntax is required to have been validated by the caller. It also converts floating point numbers to hexadecimal text as per the C99 a and A conversions. The output precision (or alternatively the natural minimal precision) can be specified; if the requested precision is less than the natural precision the output is correctly rounded for the specified rounding mode.
It also reads decimal floating point numbers and correctly rounds according to the specified rounding mode.
Conversion to decimal text is not currently implemented.
Non-zero finite numbers are represented internally as a sign bit, a 16-bit signed exponent, and the significand as an array of integer parts. After normalization of a number of precision P the exponent is within the range of the format, and if the number is not denormal the P-th bit of the significand is set as an explicit integer bit. For denormals the most significant bit is shifted right so that the exponent is maintained at the format's minimum, so that the smallest denormal has just the least significant bit of the significand set. The sign of zeroes and infinities is significant; the exponent and significand of such numbers is not stored, but has a known implicit (deterministic) value: 0 for the significands, 0 for zero exponent, all 1 bits for infinity exponent. For NaNs the sign and significand are deterministic, although not really meaningful, and preserved in non-conversion operations. The exponent is implicitly all 1 bits.
APFloat does not provide any exception handling beyond default exception handling. We represent Signaling NaNs via IEEE-754R 2008 6.2.1 should clause by encoding Signaling NaNs with the first bit of its trailing significand as 0.
TODO
Some features that may or may not be worth adding:
Binary to decimal conversion (hard).
Optional ability to detect underflow tininess before rounding.
New formats: x87 in single and double precision mode (IEEE apart from extended exponent range) (hard).
New operations: sqrt, IEEE remainder, C90 fmod, nexttoward.
Definition at line 142 of file APFloat.h.
Member Typedef Documentation
ExponentType
typedef int32_t llvm::APFloatBase::ExponentType
A signed type to represent a floating point numbers unbiased exponent.
Definition at line 147 of file APFloat.h.
integerPart
typedef APInt::WordType llvm::APFloatBase::integerPart
Definition at line 143 of file APFloat.h.
roundingMode
using llvm::APFloatBase::roundingMode = llvm::RoundingMode
IEEE-754R 4.3: Rounding-direction attributes.
Definition at line 215 of file APFloat.h.
Member Enumeration Documentation
cmpResult
enum llvm::APFloatBase::cmpResult
IEEE-754R 5.11: Floating Point Comparison Relations.
Enumerator
cmpLessThan
cmpEqual
cmpGreaterThan
cmpUnordered
Definition at line 207 of file APFloat.h.
fltCategory
enum llvm::APFloatBase::fltCategory
Category of internally-represented number.
Enumerator
fcInfinity
fcNaN
fcNormal
fcZero
Definition at line 243 of file APFloat.h.
IlogbErrorKinds
enum llvm::APFloatBase::IlogbErrorKinds
Enumeration of ilogb error results.
Enumerator
IEK_Zero
IEK_NaN
IEK_Inf
Definition at line 256 of file APFloat.h.
opStatus
enum llvm::APFloatBase::opStatus
IEEE-754R 7: Default exception handling.
opUnderflow or opOverflow are always returned or-ed with opInexact.
APFloat models this behavior specified by IEEE-754: "For operations producing results in floating-point format, the default result of an operation that signals the invalid operation exception shall be a quiet NaN."
Enumerator
opOK
opInvalidOp
opDivByZero
opOverflow
opUnderflow
opInexact
Definition at line 233 of file APFloat.h.
Semantics
enum llvm::APFloatBase::Semantics
Enumerator
S_IEEEhalf
S_BFloat
S_IEEEsingle
S_IEEEdouble
S_IEEEquad
S_PPCDoubleDouble
S_Float8E5M2
S_Float8E5M2FNUZ
S_Float8E4M3FN
S_Float8E4M3FNUZ
S_x87DoubleExtended
S_MaxSemantics
Definition at line 151 of file APFloat.h.
uninitializedTag
enum llvm::APFloatBase::uninitializedTag
Convenience enum used to construct an uninitialized APFloat.
Enumerator
uninitialized
Definition at line 251 of file APFloat.h.
Member Function Documentation
BFloat()
const fltSemantics & llvm::APFloatBase::BFloat () static
Definition at line 241 of file APFloat.cpp.
References llvm::semBFloat.
Referenced by EnumToSemantics(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::ConstantDataSequential::getElementAsAPFloat(), llvm::Type::getFloatingPointTy(), llvm::Type::getFltSemantics(), llvm::SelectionDAG::getNode(), llvm::ConstantFP::isValueValidForType(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), WriteConstantInternal(), and llvm::X86TargetLowering::X86TargetLowering().
Bogus()
const fltSemantics & llvm::APFloatBase::Bogus () static
A Pseudo fltsemantic used to construct APFloats that cannot conflict with anything real.
Definition at line 265 of file APFloat.cpp.
References llvm::semBogus.
Referenced by llvm::DenseMapAPFloatKeyInfo::getEmptyKey(), and llvm::DenseMapAPFloatKeyInfo::getTombstoneKey().
EnumToSemantics()
const llvm::fltSemantics & llvm::APFloatBase::EnumToSemantics (Semantics S) static
Definition at line 182 of file APFloat.cpp.
References BFloat(), Float8E4M3FN(), Float8E4M3FNUZ(), Float8E5M2(), Float8E5M2FNUZ(), IEEEdouble(), IEEEhalf(), IEEEquad(), IEEEsingle(), llvm_unreachable, PPCDoubleDouble(), S, S_BFloat, S_Float8E4M3FN, S_Float8E4M3FNUZ, S_Float8E5M2, S_Float8E5M2FNUZ, S_IEEEdouble, S_IEEEhalf, S_IEEEquad, S_IEEEsingle, S_PPCDoubleDouble, S_x87DoubleExtended, and x87DoubleExtended().
Float8E4M3FN()
const fltSemantics & llvm::APFloatBase::Float8E4M3FN () static
Definition at line 258 of file APFloat.cpp.
References llvm::semFloat8E4M3FN.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E4M3FNUZ()
const fltSemantics & llvm::APFloatBase::Float8E4M3FNUZ () static
Definition at line 259 of file APFloat.cpp.
References llvm::semFloat8E4M3FNUZ.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E5M2()
const fltSemantics & llvm::APFloatBase::Float8E5M2 () static
Definition at line 254 of file APFloat.cpp.
References llvm::semFloat8E5M2.
Referenced by EnumToSemantics(), and SemanticsToEnum().
Float8E5M2FNUZ()
const fltSemantics & llvm::APFloatBase::Float8E5M2FNUZ () static
Definition at line 255 of file APFloat.cpp.
References llvm::semFloat8E5M2FNUZ.
Referenced by EnumToSemantics(), and SemanticsToEnum().
getSizeInBits()
unsigned llvm::APFloatBase::getSizeInBits (const fltSemantics & Sem) static
Returns the size of the floating point number (in bits) in the given semantics.
Definition at line 314 of file APFloat.cpp.
References llvm::fltSemantics::sizeInBits.
Referenced by llvm::MachineIRBuilder::buildFConstant().
IEEEdouble()
const fltSemantics & llvm::APFloatBase::IEEEdouble () static
Definition at line 247 of file APFloat.cpp.
References llvm::semIEEEdouble.
Referenced by combineBitcast(), constantFoldFpUnary(), convertIntToDoubleImm(), emitDebugValueComment(), EnumToSemantics(), llvm::SelectionDAG::EVTToAPFloatSemantics(), fixFuncEntryCount(), getConstantVector(), getConstVector(), llvm::ConstantDataSequential::getElementAsAPFloat(), llvm::Type::getFloatingPointTy(), llvm::getFltSemanticForLLT(), llvm::Type::getFltSemantics(), llvm::SelectionDAG::getNode(), isInv2Pi(), llvm::ConstantFP::isValueValidForType(), llvm::AMDGPULegalizerInfo::legalizeFrint(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), LLVMConstRealGetDouble(), llvm::LegalizerHelper::lowerFPTOUI(), llvm::AMDGPUTargetLowering::LowerFRINT(), llvm::ARMAsmPrinter::lowerOperand(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), llvm::SDNode::print_details(), llvm::NVPTXFloatMCExpr::printImpl(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), shrinkFPConstant(), and WriteConstantInternal().
IEEEhalf()
const fltSemantics & llvm::APFloatBase::IEEEhalf () static
Definition at line 238 of file APFloat.cpp.
References llvm::semIEEEhalf.
Referenced by canSafelyConvertTo16Bit(), EnumToSemantics(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::getAPFloatFromSize(), getConstantVector(), llvm::ConstantDataSequential::getElementAsAPFloat(), llvm::Type::getFloatingPointTy(), llvm::getFltSemanticForLLT(), llvm::Type::getFltSemantics(), llvm::SelectionDAG::getNode(), isInv2Pi(), llvm::ConstantFP::isValueValidForType(), llvm::NVPTXFloatMCExpr::printImpl(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), shrinkFPConstant(), simplifyNvvmIntrinsic(), WriteConstantInternal(), and llvm::X86TargetLowering::X86TargetLowering().
IEEEquad()
const fltSemantics & llvm::APFloatBase::IEEEquad () static
Definition at line 250 of file APFloat.cpp.
References llvm::semIEEEquad.
Referenced by EnumToSemantics(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::Type::getFloatingPointTy(), llvm::getFltSemanticForLLT(), llvm::Type::getFltSemantics(), llvm::SelectionDAG::getNode(), llvm::ConstantFP::isValueValidForType(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), llvm::SystemZVectorConstantInfo::SystemZVectorConstantInfo(), WriteConstantInternal(), and llvm::X86TargetLowering::X86TargetLowering().
IEEEsingle()
const fltSemantics & llvm::APFloatBase::IEEEsingle () static
Definition at line 244 of file APFloat.cpp.
References llvm::semIEEEsingle.
Referenced by llvm::checkConvertToNonDenormSingle(), combineFaddCFmul(), llvm::convertToNonDenormSingle(), EnumToSemantics(), llvm::SelectionDAG::EVTToAPFloatSemantics(), fpModeMatchesGlobalFPAtomicMode(), llvm::generateReadImageInst(), getConstantVector(), getConstVector(), llvm::Function::getDenormalMode(), llvm::ConstantDataSequential::getElementAsAPFloat(), getF32Constant(), llvm::Type::getFloatingPointTy(), llvm::getFltSemanticForLLT(), llvm::Type::getFltSemantics(), llvm::SelectionDAG::getNode(), isInv2Pi(), llvm::ConstantFP::isValueValidForType(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), llvm::LegalizerHelper::lowerFPTOUI(), lowerUINT_TO_FP_vXi32(), llvm::SDNode::print_details(), llvm::NVPTXFloatMCExpr::printImpl(), llvm::WebAssemblyInstPrinter::printOperand(), llvm::APFixedPoint::promoteFloatSemantics(), SemanticsToEnum(), shrinkFPConstant(), simplifyNvvmIntrinsic(), llvm::pdb::Variant::toAPFloat(), llvm::NVPTXTargetLowering::useF32FTZ(), valueHasFloatPrecision(), and WriteConstantInternal().
PPCDoubleDouble()
const fltSemantics & llvm::APFloatBase::PPCDoubleDouble () static
Definition at line 251 of file APFloat.cpp.
References llvm::semPPCDoubleDouble.
Referenced by EnumToSemantics(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::Type::getFloatingPointTy(), llvm::Type::getFltSemantics(), llvm::ConstantFP::isValueValidForType(), SemanticsToEnum(), and WriteConstantInternal().
semanticsIntSizeInBits()
unsigned int llvm::APFloatBase::semanticsIntSizeInBits (const fltSemantics & semantics, bool isSigned) static
Definition at line 303 of file APFloat.cpp.
References isSigned(), semantics, and semanticsMaxExponent().
Referenced by canEvaluateTruncated(), and isSaturatingMinMax().
semanticsMaxExponent()
APFloatBase::ExponentType llvm::APFloatBase::semanticsMaxExponent (const fltSemantics & semantics) static
Definition at line 293 of file APFloat.cpp.
References semantics.
Referenced by llvm::FunctionComparator::cmpAPFloats(), and semanticsIntSizeInBits().
semanticsMinExponent()
APFloatBase::ExponentType llvm::APFloatBase::semanticsMinExponent (const fltSemantics & semantics) static
Definition at line 297 of file APFloat.cpp.
References semantics.
Referenced by llvm::FunctionComparator::cmpAPFloats().
semanticsPrecision()
unsigned int llvm::APFloatBase::semanticsPrecision (const fltSemantics & semantics) static
Definition at line 289 of file APFloat.cpp.
References semantics.
Referenced by llvm::FunctionComparator::cmpAPFloats(), FoldIntToFPToInt(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), llvm::detail::IEEEFloat::roundToIntegral(), and llvm::InstCombinerImpl::visitFAdd().
semanticsSizeInBits()
unsigned int llvm::APFloatBase::semanticsSizeInBits (const fltSemantics & semantics) static
Definition at line 300 of file APFloat.cpp.
References semantics.
Referenced by llvm::FunctionComparator::cmpAPFloats().
SemanticsToEnum()
APFloatBase::Semantics llvm::APFloatBase::SemanticsToEnum (const llvm::fltSemantics & Sem) static
Definition at line 211 of file APFloat.cpp.
References BFloat(), Float8E4M3FN(), Float8E4M3FNUZ(), Float8E5M2(), Float8E5M2FNUZ(), IEEEdouble(), IEEEhalf(), IEEEquad(), IEEEsingle(), llvm_unreachable, PPCDoubleDouble(), S_BFloat, S_Float8E4M3FN, S_Float8E4M3FNUZ, S_Float8E5M2, S_Float8E5M2FNUZ, S_IEEEdouble, S_IEEEhalf, S_IEEEquad, S_IEEEsingle, S_PPCDoubleDouble, S_x87DoubleExtended, and x87DoubleExtended().
x87DoubleExtended()
const fltSemantics & llvm::APFloatBase::x87DoubleExtended () static
Definition at line 262 of file APFloat.cpp.
References llvm::semX87DoubleExtended.
Referenced by EnumToSemantics(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::ExecutionEngine::getConstantValue(), llvm::Type::getFloatingPointTy(), llvm::Type::getFltSemantics(), llvm::ConstantFP::isValueValidForType(), SemanticsToEnum(), toStringAPFloat(), WriteConstantInternal(), and llvm::X86TargetLowering::X86TargetLowering().
Member Data Documentation
integerPartWidth
constexpr unsigned llvm::APFloatBase::integerPartWidth = APInt::APINT_BITS_PER_WORD static constexpr
Definition at line 144 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::convertFromSignExtendedInteger(), llvm::lostFractionThroughTruncation(), llvm::detail::IEEEFloat::makeLargest(), llvm::partAsHex(), llvm::partCountForBits(), and llvm::ulpsFromBoundary().
rmNearestTiesToAway
constexpr RoundingMode llvm::APFloatBase::rmNearestTiesToAway static constexpr
Initial value:
=
                                                RoundingMode::NearestTiesToAway
Definition at line 222 of file APFloat.h.
Referenced by llvm::FixedPointSemantics::fitsInFloatSemantics().
rmNearestTiesToEven
constexpr RoundingMode llvm::APFloatBase::rmNearestTiesToEven static constexpr
Initial value:
=
                                                RoundingMode::NearestTiesToEven
Definition at line 217 of file APFloat.h.
Referenced by llvm::APFloat::APFloat(), llvm::checkConvertToNonDenormSingle(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldFPBinOp(), constantFoldFpUnary(), llvm::ConstantFoldIntToFloat(), llvm::APFloat::convertToDouble(), llvm::APFixedPoint::convertToFloat(), llvm::APFloat::convertToFloat(), llvm::convertToNonDenormSingle(), emitDebugValueComment(), fitsInFPType(), fixFuncEntryCount(), llvm::SelectionDAG::foldConstantFPMath(), llvm::InstCombinerImpl::foldFCmpIntToFPConst(), llvm::ConstantFP::get(), llvm::getAPFloatFromSize(), llvm::StringRef::getAsDouble(), llvm::SelectionDAG::getConstantFP(), llvm::ExecutionEngine::getConstantValue(), llvm::detail::IEEEFloat::getExactInverse(), llvm::SelectionDAG::getNode(), llvm::detail::IEEEFloat::IEEEFloat(), llvm::detail::ilogb(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::ConstantFP::isExactlyValue(), llvm::APFloat::isExactlyValue(), llvm::ConstantFP::isValueValidForType(), llvm::ConstantFPSDNode::isValueValidForType(), LLVMConstRealGetDouble(), llvm::LegalizerHelper::lowerFPTOUI(), LowerFROUND(), lowerFTRUNC_FCEIL_FFLOOR_FROUND(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), llvm::detail::IEEEFloat::mod(), llvm::APFloat::operator*(), llvm::APFloat::operator+(), llvm::APFloat::operator-(), llvm::APFloat::operator/(), llvm::NVPTXFloatMCExpr::printImpl(), llvm::detail::IEEEFloat::remainder(), llvm::detail::IEEEFloat::roundToIntegral(), toString(), valueHasFloatPrecision(), llvm::InstCombinerImpl::visitFCmpInst(), WriteConstantInternal(), and llvm::X86TargetLowering::X86TargetLowering().
rmTowardNegative
constexpr RoundingMode llvm::APFloatBase::rmTowardNegative = RoundingMode::TowardNegative static constexpr
Definition at line 220 of file APFloat.h.
Referenced by llvm::detail::IEEEFloat::fusedMultiplyAdd(), and llvm::SelectionDAG::getNode().
rmTowardPositive
constexpr RoundingMode llvm::APFloatBase::rmTowardPositive = RoundingMode::TowardPositive static constexpr
Definition at line 219 of file APFloat.h.
Referenced by llvm::SelectionDAG::getNode().
rmTowardZero
constexpr RoundingMode llvm::APFloatBase::rmTowardZero = RoundingMode::TowardZero static constexpr
Definition at line 221 of file APFloat.h.
Referenced by canSafelyConvertTo16Bit(), llvm::ConstantFoldCastInstruction(), llvm::APFixedPoint::convertToFloat(), ConvertToSInt(), llvm::BuildVectorSDNode::getConstantFPSplatPow2ToLog2Int(), llvm::ExecutionEngine::getConstantValue(), llvm::APFixedPoint::getFromFloatValue(), llvm::SelectionDAG::getNode(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::PPCTargetLowering::isFPImmLegal(), llvm::detail::IEEEFloat::isInteger(), and llvm::ARMAsmPrinter::lowerOperand().
The documentation for this struct was generated from the following files:
include/llvm/ADT/APFloat.h
lib/Support/APFloat.cpp