LLVM: llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable > Struct Template Reference
llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable > Struct Template Reference
#include "llvm/IR/PatternMatch.h"
Public Types
using PredType = Pred_t
Public Member Functions
MaxMin_match (const LHS_t &LHS, const RHS_t &RHS)
template<typename OpTy >
bool match (OpTy *V)
Public Attributes
LHS_t L
RHS_t R
Detailed Description
template<typename CmpInst_t, typename LHS_t, typename RHS_t, typename Pred_t, bool Commutable = false>
struct llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >
Definition at line 1748 of file PatternMatch.h.
Member Typedef Documentation
PredType
template<typename CmpInst_t , typename LHS_t , typename RHS_t , typename Pred_t , bool Commutable = false> using llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::PredType = Pred_t
Definition at line 1749 of file PatternMatch.h.
Constructor & Destructor Documentation
MaxMin_match()
template<typename CmpInst_t , typename LHS_t , typename RHS_t , typename Pred_t , bool Commutable = false> llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::MaxMin_match (const LHS_t & LHS, const RHS_t & RHS) inline
Definition at line 1755 of file PatternMatch.h.
Member Function Documentation
match()
template<typename CmpInst_t , typename LHS_t , typename RHS_t , typename Pred_t , bool Commutable = false> template<typename OpTy > bool llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match (OpTy * V) inline
Definition at line 1757 of file PatternMatch.h.
References llvm::MCID::Commutable, llvm::tgtok::FalseVal, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::L, LHS, llvm::PatternMatch::match(), llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::R, RHS, SI, llvm::APIntOps::smax(), llvm::APIntOps::smin(), llvm::tgtok::TrueVal, llvm::APIntOps::umax(), and llvm::APIntOps::umin().
Member Data Documentation
L
template<typename CmpInst_t , typename LHS_t , typename RHS_t , typename Pred_t , bool Commutable = false> LHS_t llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::L
Definition at line 1750 of file PatternMatch.h.
Referenced by llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match().
R
template<typename CmpInst_t , typename LHS_t , typename RHS_t , typename Pred_t , bool Commutable = false> RHS_t llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::R
Definition at line 1751 of file PatternMatch.h.
Referenced by llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t, Commutable >::match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h