LLVM: llvm::yaml::WebAssemblyFunctionInfo Struct Reference
llvm::yaml::WebAssemblyFunctionInfo Struct Reference final
#include "Target/WebAssembly/WebAssemblyMachineFunctionInfo.h"
Public Member Functions
WebAssemblyFunctionInfo ()=default
WebAssemblyFunctionInfo (const llvm::MachineFunction &MF, const llvm::WebAssemblyFunctionInfo &MFI)
void mappingImpl (yaml::IO &YamlIO) override
~WebAssemblyFunctionInfo ()=default
Public Member Functions inherited from llvm::yaml::MachineFunctionInfo
virtual ~MachineFunctionInfo ()=default
virtual void mappingImpl (IO &YamlIO)
Public Attributes
std::vector< FlowStringValue > Params
std::vector< FlowStringValue > Results
bool CFGStackified = false
BBNumberMap SrcToUnwindDest
Detailed Description
Definition at line 190 of file WebAssemblyMachineFunctionInfo.h.
Constructor & Destructor Documentation
WebAssemblyFunctionInfo() [1/2]
llvm::yaml::WebAssemblyFunctionInfo::WebAssemblyFunctionInfo () default
WebAssemblyFunctionInfo() [2/2]
yaml::WebAssemblyFunctionInfo::WebAssemblyFunctionInfo (const llvm::MachineFunction & MF, const llvm::WebAssemblyFunctionInfo & MFI)
Definition at line 123 of file WebAssemblyMachineFunctionInfo.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::MachineBasicBlock::getNumber(), llvm::WebAssemblyFunctionInfo::getParams(), llvm::WebAssemblyFunctionInfo::getResults(), llvm::MachineFunction::getWasmEHFuncInfo(), llvm::SmallPtrSetImpl< PtrType >::insert(), MBB, Params, Results, and SrcToUnwindDest.
~WebAssemblyFunctionInfo()
llvm::yaml::WebAssemblyFunctionInfo::~WebAssemblyFunctionInfo () default
Member Function Documentation
mappingImpl()
void yaml::WebAssemblyFunctionInfo::mappingImpl (yaml::IO & YamlIO) override
Definition at line 150 of file WebAssemblyMachineFunctionInfo.cpp.
References YamlIO.
Member Data Documentation
CFGStackified
bool llvm::yaml::WebAssemblyFunctionInfo::CFGStackified = false
Definition at line 193 of file WebAssemblyMachineFunctionInfo.h.
Referenced by llvm::WebAssemblyFunctionInfo::initializeBaseYamlFields(), and llvm::yaml::MappingTraits< WebAssemblyFunctionInfo >::mapping().
Params
std::vector<FlowStringValue> llvm::yaml::WebAssemblyFunctionInfo::Params
Definition at line 191 of file WebAssemblyMachineFunctionInfo.h.
Referenced by llvm::WebAssemblyFunctionInfo::initializeBaseYamlFields(), llvm::yaml::MappingTraits< WebAssemblyFunctionInfo >::mapping(), and WebAssemblyFunctionInfo().
Results
std::vector<FlowStringValue> llvm::yaml::WebAssemblyFunctionInfo::Results
Definition at line 192 of file WebAssemblyMachineFunctionInfo.h.
Referenced by llvm::WebAssemblyFunctionInfo::initializeBaseYamlFields(), llvm::yaml::MappingTraits< WebAssemblyFunctionInfo >::mapping(), and WebAssemblyFunctionInfo().
SrcToUnwindDest
BBNumberMap llvm::yaml::WebAssemblyFunctionInfo::SrcToUnwindDest
Definition at line 196 of file WebAssemblyMachineFunctionInfo.h.
Referenced by llvm::WebAssemblyFunctionInfo::initializeBaseYamlFields(), llvm::yaml::MappingTraits< WebAssemblyFunctionInfo >::mapping(), and WebAssemblyFunctionInfo().
The documentation for this struct was generated from the following files:
lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.h
lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.cpp