LLVM: llvm::GraphTraits< const DataDependenceGraph * > Struct Reference
llvm::GraphTraits< const DataDependenceGraph * > Struct Reference
#include "llvm/Analysis/DDG.h"
Public Types
using nodes_iterator = DataDependenceGraph::const_iterator
Public Types inherited from llvm::GraphTraits< const DDGNode * >
using NodeRef = const DDGNode *
using ChildIteratorType = mapped_iterator< DDGNode::const_iterator, decltype(&DDGGetTargetNode)>
using ChildEdgeIteratorType = DDGNode::const_iterator
Static Public Member Functions
static NodeRef getEntryNode (const DataDependenceGraph *DG)
static nodes_iterator nodes_begin (const DataDependenceGraph *DG)
static nodes_iterator nodes_end (const DataDependenceGraph *DG)
Static Public Member Functions inherited from llvm::GraphTraits< const DDGNode * >
static const DDGNode * DDGGetTargetNode (const DGEdge< DDGNode, DDGEdge > *P)
static NodeRef getEntryNode (NodeRef N)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static ChildEdgeIteratorType child_edge_begin (NodeRef N)
static ChildEdgeIteratorType child_edge_end (NodeRef N)
Detailed Description
Definition at line 554 of file DDG.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< const DataDependenceGraph * >::nodes_iterator = DataDependenceGraph::const_iterator
Definition at line 556 of file DDG.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< const DataDependenceGraph * >::getEntryNode (const DataDependenceGraph * DG) inline static
Definition at line 557 of file DDG.h.
References llvm::DependenceGraphInfo< NodeType >::getRoot().
nodes_begin()
static nodes_iterator llvm::GraphTraits< const DataDependenceGraph * >::nodes_begin (const DataDependenceGraph * DG) inline static
Definition at line 560 of file DDG.h.
References llvm::DirectedGraph< NodeType, EdgeType >::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< const DataDependenceGraph * >::nodes_end (const DataDependenceGraph * DG) inline static
Definition at line 563 of file DDG.h.
References llvm::DirectedGraph< NodeType, EdgeType >::end().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/DDG.h