LLVM: llvm::GraphTraits< DataDependenceGraph * > Struct Reference
llvm::GraphTraits< DataDependenceGraph * > Struct Reference
#include "llvm/Analysis/DDG.h"
Public Types
using nodes_iterator = DataDependenceGraph::iterator
Public Types inherited from llvm::GraphTraits< DDGNode * >
using NodeRef = DDGNode *
using ChildIteratorType = mapped_iterator< DDGNode::iterator, decltype(&DDGGetTargetNode)>
using ChildEdgeIteratorType = DDGNode::iterator
Static Public Member Functions
static NodeRef getEntryNode (DataDependenceGraph *DG)
static nodes_iterator nodes_begin (DataDependenceGraph *DG)
static nodes_iterator nodes_end (DataDependenceGraph *DG)
Static Public Member Functions inherited from llvm::GraphTraits< DDGNode * >
static DDGNode * DDGGetTargetNode (DGEdge< DDGNode, DDGEdge > *P)
static NodeRef getEntryNode (NodeRef N)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
static ChildEdgeIteratorType child_edge_begin (NodeRef N)
static ChildEdgeIteratorType child_edge_end (NodeRef N)
Detailed Description
Definition at line 514 of file DDG.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< DataDependenceGraph * >::nodes_iterator = DataDependenceGraph::iterator
Definition at line 515 of file DDG.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< DataDependenceGraph * >::getEntryNode (DataDependenceGraph * DG) inline static
Definition at line 516 of file DDG.h.
References llvm::DependenceGraphInfo< NodeType >::getRoot().
nodes_begin()
static nodes_iterator llvm::GraphTraits< DataDependenceGraph * >::nodes_begin (DataDependenceGraph * DG) inline static
Definition at line 519 of file DDG.h.
References llvm::DirectedGraph< NodeType, EdgeType >::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< DataDependenceGraph * >::nodes_end (DataDependenceGraph * DG) inline static
Definition at line 522 of file DDG.h.
References llvm::DirectedGraph< NodeType, EdgeType >::end().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/DDG.h