LLVM: llvm::memprof::PortableMemInfoBlock Struct Reference
llvm::memprof::PortableMemInfoBlock Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
PortableMemInfoBlock ()=default
PortableMemInfoBlock (const MemInfoBlock &Block)
PortableMemInfoBlock (const MemProfSchema &Schema, const unsigned char *Ptr)
void deserialize (const MemProfSchema &Schema, const unsigned char *Ptr)
void serialize (const MemProfSchema &Schema, raw_ostream &OS) const
void printYAML (raw_ostream &OS) const
void clear ()
bool operator== (const PortableMemInfoBlock &Other) const
bool operator!= (const PortableMemInfoBlock &Other) const
Static Public Member Functions
static MemProfSchema getSchema ()
static constexpr size_t serializedSize ()
Detailed Description
Definition at line 32 of file MemProf.h.
Constructor & Destructor Documentation
PortableMemInfoBlock() [1/3]
llvm::memprof::PortableMemInfoBlock::PortableMemInfoBlock () default
Referenced by clear().
PortableMemInfoBlock() [2/3]
llvm::memprof::PortableMemInfoBlock::PortableMemInfoBlock (const MemInfoBlock & Block) inline explicit
Definition at line 34 of file MemProf.h.
PortableMemInfoBlock() [3/3]
llvm::memprof::PortableMemInfoBlock::PortableMemInfoBlock (const MemProfSchema & Schema, const unsigned char * Ptr) inline
Definition at line 40 of file MemProf.h.
References deserialize(), and Ptr.
Member Function Documentation
clear()
void llvm::memprof::PortableMemInfoBlock::clear () inline
Definition at line 99 of file MemProf.h.
References PortableMemInfoBlock().
deserialize()
void llvm::memprof::PortableMemInfoBlock::deserialize (const MemProfSchema & Schema, const unsigned char * Ptr) inline
Definition at line 46 of file MemProf.h.
References llvm_unreachable, and support().
Referenced by PortableMemInfoBlock().
getSchema()
static MemProfSchema llvm::memprof::PortableMemInfoBlock::getSchema () inline static
Definition at line 102 of file MemProf.h.
References List.
operator!=()
bool llvm::memprof::PortableMemInfoBlock::operator!= (const PortableMemInfoBlock & Other) const inline
Definition at line 119 of file MemProf.h.
References operator==(), and Other.
operator==()
bool llvm::memprof::PortableMemInfoBlock::operator== (const PortableMemInfoBlock & Other) const inline
Definition at line 110 of file MemProf.h.
Referenced by operator!=(), llvm::memprof::Frame::operator!=(), and llvm::memprof::IndexedAllocationInfo::operator!=().
printYAML()
void llvm::memprof::PortableMemInfoBlock::printYAML (raw_ostream & OS) const inline
Definition at line 85 of file MemProf.h.
References OS.
serialize()
void llvm::memprof::PortableMemInfoBlock::serialize (const MemProfSchema & Schema, raw_ostream & OS) const inline
Definition at line 66 of file MemProf.h.
References llvm::AArch64CC::LE, llvm::support::little, llvm_unreachable, OS, and support().
serializedSize()
static constexpr size_t llvm::memprof::PortableMemInfoBlock::serializedSize () inline static constexpr
Definition at line 123 of file MemProf.h.
Referenced by llvm::memprof::IndexedAllocationInfo::serializedSize().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h