LLVM: llvm::rdf::RegisterAggr Struct Reference
llvm::rdf::RegisterAggr Struct Reference
#include "llvm/CodeGen/RDFRegisters.h"
Classes
struct rr_iterator
Public Member Functions
RegisterAggr (const PhysicalRegisterInfo &pri)
RegisterAggr (const RegisterAggr &RG)=default
unsigned count () const
bool empty () const
bool hasAliasOf (RegisterRef RR) const
bool hasCoverOf (RegisterRef RR) const
bool operator== (const RegisterAggr &A) const
RegisterAggr & insert (RegisterRef RR)
RegisterAggr & insert (const RegisterAggr &RG)
RegisterAggr & intersect (RegisterRef RR)
RegisterAggr & intersect (const RegisterAggr &RG)
RegisterAggr & clear (RegisterRef RR)
RegisterAggr & clear (const RegisterAggr &RG)
RegisterRef intersectWith (RegisterRef RR) const
RegisterRef clearIn (RegisterRef RR) const
RegisterRef makeRegRef () const
size_t hash () const
void print (raw_ostream &OS) const
rr_iterator rr_begin () const
rr_iterator rr_end () const
Static Public Member Functions
static bool isCoverOf (RegisterRef RA, RegisterRef RB, const PhysicalRegisterInfo &PRI)
Detailed Description
Definition at line 168 of file RDFRegisters.h.
Constructor & Destructor Documentation
RegisterAggr() [1/2]
llvm::rdf::RegisterAggr::RegisterAggr (const PhysicalRegisterInfo & pri) inline
Definition at line 169 of file RDFRegisters.h.
Referenced by clear(), clearIn(), intersect(), and isCoverOf().
RegisterAggr() [2/2]
llvm::rdf::RegisterAggr::RegisterAggr (const RegisterAggr & RG) default
Member Function Documentation
clear() [1/2]
RegisterAggr & RegisterAggr::clear (const RegisterAggr & RG)
Definition at line 305 of file RDFRegisters.cpp.
References llvm::BitVector::reset().
clear() [2/2]
RegisterAggr & RegisterAggr::clear (RegisterRef RR)
Definition at line 301 of file RDFRegisters.cpp.
References insert(), and RegisterAggr().
clearIn()
RegisterRef RegisterAggr::clearIn (RegisterRef RR) const
Definition at line 320 of file RDFRegisters.cpp.
References RegisterAggr().
Referenced by llvm::rdf::Liveness::computePhiInfo().
count()
unsigned llvm::rdf::RegisterAggr::count () const inline
Definition at line 173 of file RDFRegisters.h.
References llvm::BitVector::count().
empty()
bool llvm::rdf::RegisterAggr::empty () const inline
Definition at line 174 of file RDFRegisters.h.
References llvm::BitVector::none().
hasAliasOf()
bool RegisterAggr::hasAliasOf (RegisterRef RR) const
Definition at line 245 of file RDFRegisters.cpp.
References llvm::BitVector::anyCommon(), llvm::rdf::PhysicalRegisterInfo::getMaskUnits(), llvm::rdf::PhysicalRegisterInfo::getTRI(), llvm::rdf::PhysicalRegisterInfo::isRegMaskId(), llvm::MCRegUnitMaskIterator::isValid(), llvm::rdf::RegisterRef::Mask, P, llvm::rdf::RegisterRef::Reg, and llvm::BitVector::test().
Referenced by llvm::rdf::Liveness::computePhiInfo().
hasCoverOf()
bool RegisterAggr::hasCoverOf (RegisterRef RR) const
Definition at line 258 of file RDFRegisters.cpp.
References llvm::rdf::PhysicalRegisterInfo::getMaskUnits(), llvm::rdf::PhysicalRegisterInfo::getTRI(), llvm::rdf::PhysicalRegisterInfo::isRegMaskId(), llvm::MCRegUnitMaskIterator::isValid(), llvm::rdf::RegisterRef::Mask, P, llvm::rdf::RegisterRef::Reg, and llvm::BitVector::test().
Referenced by llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::Liveness::getAllReachedUses(), and llvm::rdf::Liveness::getAllReachingDefs().
hash()
size_t llvm::rdf::RegisterAggr::hash () const inline
Definition at line 198 of file RDFRegisters.h.
insert() [1/2]
RegisterAggr & RegisterAggr::insert (const RegisterAggr & RG)
Definition at line 287 of file RDFRegisters.cpp.
insert() [2/2]
RegisterAggr & RegisterAggr::insert (RegisterRef RR)
Definition at line 273 of file RDFRegisters.cpp.
References llvm::rdf::PhysicalRegisterInfo::getMaskUnits(), llvm::rdf::PhysicalRegisterInfo::getTRI(), llvm::rdf::PhysicalRegisterInfo::isRegMaskId(), llvm::MCRegUnitMaskIterator::isValid(), llvm::rdf::RegisterRef::Mask, P, llvm::rdf::RegisterRef::Reg, and llvm::BitVector::set().
Referenced by llvm::rdf::DataFlowGraph::build(), clear(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::Liveness::getAllReachedUses(), llvm::rdf::Liveness::getAllReachingDefs(), and intersect().
intersect() [1/2]
RegisterAggr & RegisterAggr::intersect (const RegisterAggr & RG)
Definition at line 296 of file RDFRegisters.cpp.
intersect() [2/2]
RegisterAggr & RegisterAggr::intersect (RegisterRef RR)
Definition at line 292 of file RDFRegisters.cpp.
References insert(), and RegisterAggr().
intersectWith()
RegisterRef RegisterAggr::intersectWith (RegisterRef RR) const
Definition at line 310 of file RDFRegisters.cpp.
References assert().
Referenced by llvm::rdf::Liveness::computePhiInfo().
isCoverOf()
static bool llvm::rdf::RegisterAggr::isCoverOf (RegisterRef RA, RegisterRef RB, const PhysicalRegisterInfo & PRI) inline static
Definition at line 182 of file RDFRegisters.h.
References RA, and RegisterAggr().
Referenced by llvm::rdf::Liveness::getAllReachingDefs().
makeRegRef()
RegisterRef RegisterAggr::makeRegRef () const
Definition at line 324 of file RDFRegisters.cpp.
References F, llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::LaneBitmask::getAll(), llvm::rdf::PhysicalRegisterInfo::getTRI(), llvm::rdf::PhysicalRegisterInfo::getUnitAliases(), I, M, P, and llvm::BitVector::test().
operator==()
bool llvm::rdf::RegisterAggr::operator== (const RegisterAggr & A) const inline
Definition at line 178 of file RDFRegisters.h.
References isEqual().
print()
void RegisterAggr::print (raw_ostream & OS) const
Definition at line 360 of file RDFRegisters.cpp.
References llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::rdf::PhysicalRegisterInfo::getTRI(), OS, and llvm::printRegUnit().
rr_begin()
rr_iterator llvm::rdf::RegisterAggr::rr_begin () const inline
Definition at line 237 of file RDFRegisters.h.
Referenced by llvm::rdf::DataFlowGraph::build(), llvm::rdf::Liveness::computeLiveIns(), and llvm::rdf::Liveness::resetLiveIns().
rr_end()
rr_iterator llvm::rdf::RegisterAggr::rr_end () const inline
Definition at line 240 of file RDFRegisters.h.
Referenced by llvm::rdf::DataFlowGraph::build(), llvm::rdf::Liveness::computeLiveIns(), and llvm::rdf::Liveness::resetLiveIns().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFRegisters.h
lib/CodeGen/RDFRegisters.cpp