LLVM: llvm::MIPatternMatch::SpecificConstantOrSplatMatch Struct Reference
llvm::MIPatternMatch::SpecificConstantOrSplatMatch Struct Reference
Matcher for a specific constant or constant splat.
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
SpecificConstantOrSplatMatch (int64_t RequestedVal)
bool match (const MachineRegisterInfo &MRI, Register Reg)
Public Attributes
int64_t RequestedVal
Detailed Description
Matcher for a specific constant or constant splat.
Definition at line 216 of file MIPatternMatch.h.
Constructor & Destructor Documentation
SpecificConstantOrSplatMatch()
llvm::MIPatternMatch::SpecificConstantOrSplatMatch::SpecificConstantOrSplatMatch (int64_t RequestedVal) inline
Definition at line 218 of file MIPatternMatch.h.
Member Function Documentation
match()
bool llvm::MIPatternMatch::SpecificConstantOrSplatMatch::match (const MachineRegisterInfo & MRI, Register Reg) inline
Definition at line 220 of file MIPatternMatch.h.
References llvm::isBuildVectorConstantSplat(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::mi_match(), MRI, and RequestedVal.
Member Data Documentation
RequestedVal
int64_t llvm::MIPatternMatch::SpecificConstantOrSplatMatch::RequestedVal
Definition at line 217 of file MIPatternMatch.h.
Referenced by match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h