LLVM: llvm::rdf::Liveness Struct Reference
llvm::rdf::Liveness Struct Reference
#include "llvm/CodeGen/RDFLiveness.h"
Classes
struct LiveMapType
Public Types
using NodeRef = detail::NodeRef
using NodeRefSet = std::unordered_set< NodeRef >
using RefMap = std::unordered_map< RegisterId, NodeRefSet >
Public Member Functions
Liveness (MachineRegisterInfo &mri, const DataFlowGraph &g)
NodeList getAllReachingDefs (RegisterRef RefRR, NodeAddr< RefNode * > RefA, bool TopShadows, bool FullChain, const RegisterAggr &DefRRs)
NodeList getAllReachingDefs (NodeAddr< RefNode * > RefA)
NodeList getAllReachingDefs (RegisterRef RefRR, NodeAddr< RefNode * > RefA)
NodeSet getAllReachedUses (RegisterRef RefRR, NodeAddr< DefNode * > DefA, const RegisterAggr &DefRRs)
NodeSet getAllReachedUses (RegisterRef RefRR, NodeAddr< DefNode * > DefA)
std::pair< NodeSet, bool > getAllReachingDefsRec (RegisterRef RefRR, NodeAddr< RefNode * > RefA, NodeSet &Visited, const NodeSet &Defs)
NodeAddr< RefNode * > getNearestAliasedRef (RegisterRef RefRR, NodeAddr< InstrNode * > IA)
Find the nearest ref node aliased to RefRR, going upwards in the data flow, starting from the instruction immediately preceding Inst.
LiveMapType & getLiveMap ()
const LiveMapType & getLiveMap () const
const RefMap & getRealUses (NodeId P) const
void computePhiInfo ()
void computeLiveIns ()
void resetLiveIns ()
void resetKills ()
void resetKills (MachineBasicBlock *B)
void trace (bool T)
Detailed Description
Definition at line 59 of file RDFLiveness.h.
Member Typedef Documentation
NodeRef
using llvm::rdf::Liveness::NodeRef = detail::NodeRef
Definition at line 75 of file RDFLiveness.h.
NodeRefSet
using llvm::rdf::Liveness::NodeRefSet = std::unordered_set<NodeRef>
Definition at line 76 of file RDFLiveness.h.
RefMap
using llvm::rdf::Liveness::RefMap = std::unordered_map<RegisterId, NodeRefSet>
Definition at line 77 of file RDFLiveness.h.
Constructor & Destructor Documentation
Liveness()
llvm::rdf::Liveness::Liveness (MachineRegisterInfo & mri, const DataFlowGraph & g) inline
Definition at line 79 of file RDFLiveness.h.
Member Function Documentation
computeLiveIns()
void Liveness::computeLiveIns ()
Definition at line 736 of file RDFLiveness.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), B, BB, llvm::SetVector< T, Vector, Set >::begin(), computePhiInfo(), D, llvm::dbgs(), E, llvm::MachineDominanceFrontier::end(), llvm::SetVector< T, Vector, Set >::end(), llvm::MachineDominanceFrontier::find(), getAllReachingDefs(), llvm::rdf::DataFlowGraph::getFunc(), llvm::rdf::DataFlowGraph::getLiveIns(), llvm::rdf::DataFlowGraph::getMF(), llvm::rdf::PhiUseNode::getPredecessor(), llvm::rdf::RefNode::getReachingDef(), llvm::rdf::DataFlowGraph::getRelatedRefs(), i, I, llvm::AArch64PACKey::IA, llvm::rdf::NodeAddr< T >::Id, llvm::SetVector< T, Vector, Set >::insert(), llvm::rdf::DataFlowGraph::IsCode(), llvm::rdf::DataFlowGraph::IsRef(), llvm::rdf::CodeNode::members(), llvm::rdf::CodeNode::members_if(), P, llvm::rdf::NodeAttrs::Phi, llvm::rdf::Print(), llvm::printMBBReference(), RA, llvm::rdf::RegisterAggr::rr_begin(), llvm::rdf::RegisterAggr::rr_end(), S, llvm::SetVector< T, Vector, Set >::size(), llvm::sort(), llvm::X86II::TA, TM, and llvm::rdf::NodeAttrs::Use.
computePhiInfo()
void Liveness::computePhiInfo ()
Definition at line 463 of file RDFLiveness.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), llvm::append_range(), assert(), llvm::rdf::RegisterAggr::clearIn(), D, llvm::AArch64PACKey::DA, llvm::dbgs(), llvm::rdf::NodeAttrs::Dead, llvm::rdf::NodeAttrs::Def, F, getAllReachingDefs(), llvm::rdf::DataFlowGraph::getFunc(), llvm::rdf::RefNode::getReachingDef(), llvm::rdf::RefNode::getRegRef(), llvm::rdf::DataFlowGraph::getRelatedRefs(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), i, I, llvm::rdf::NodeAddr< T >::Id, llvm::SetVector< T, Vector, Set >::insert(), llvm::rdf::RegisterAggr::insert(), llvm::rdf::RegisterAggr::intersectWith(), llvm::rdf::DataFlowGraph::IsCode(), IsDead, llvm::rdf::DataFlowGraph::IsRef(), M, llvm::rdf::PhysicalRegisterInfo::mapTo(), llvm::rdf::CodeNode::members(), llvm::rdf::CodeNode::members_if(), P, llvm::rdf::NodeAttrs::Phi, llvm::rdf::NodeAttrs::PhiRef, llvm::rdf::Print(), llvm::AArch64::RP, S, llvm::SetVector< T, Vector, Set >::size(), llvm::X86AS::SS, llvm::rdf::NodeAttrs::Undef, llvm::rdf::NodeAttrs::Use, and Uses.
Referenced by computeLiveIns().
getAllReachedUses() [1/2]
NodeSet llvm::rdf::Liveness::getAllReachedUses (RegisterRef RefRR, NodeAddr< DefNode * > DefA) inline
Definition at line 98 of file RDFLiveness.h.
References getAllReachedUses().
getAllReachedUses() [2/2]
NodeSet Liveness::getAllReachedUses (RegisterRef RefRR, NodeAddr< DefNode * > DefA, const RegisterAggr & DefRRs)
Definition at line 417 of file RDFLiveness.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), llvm::rdf::PhysicalRegisterInfo::alias(), D, llvm::AArch64PACKey::DA, llvm::rdf::NodeAttrs::Dead, llvm::rdf::NodeBase::getFlags(), llvm::rdf::DefNode::getReachedDef(), llvm::rdf::DefNode::getReachedUse(), llvm::rdf::RegisterAggr::hasCoverOf(), llvm::rdf::RegisterAggr::insert(), IsDead, llvm::rdf::DataFlowGraph::IsPreservingDef(), llvm::rdf::NodeAttrs::Undef, and Uses.
Referenced by getAllReachedUses().
getAllReachingDefs() [1/3]
NodeList llvm::rdf::Liveness::getAllReachingDefs (NodeAddr< RefNode * > RefA) inline
Definition at line 86 of file RDFLiveness.h.
References llvm::rdf::NodeAddr< T >::Addr, and getAllReachingDefs().
getAllReachingDefs() [2/3]
NodeList llvm::rdf::Liveness::getAllReachingDefs (RegisterRef RefRR, NodeAddr< RefNode * > RefA) inline
Definition at line 91 of file RDFLiveness.h.
References getAllReachingDefs().
getAllReachingDefs() [3/3]
NodeList Liveness::getAllReachingDefs (RegisterRef RefRR, NodeAddr< RefNode * > RefA, bool TopShadows, bool FullChain, const RegisterAggr & DefRRs)
Definition at line 108 of file RDFLiveness.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), llvm::rdf::PhysicalRegisterInfo::alias(), llvm::append_range(), assert(), B, BB, llvm::SmallSet< T, N, C >::count(), llvm::AArch64PACKey::DA, llvm::rdf::NodeAttrs::Dead, llvm::rdf::NodeAttrs::Def, E, llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::end(), llvm::erase_if(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::find(), llvm::rdf::BlockNode::getCode(), llvm::rdf::NodeBase::getFlags(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::rdf::NodeBase::getKind(), llvm::rdf::RefNode::getOwner(), llvm::rdf::InstrNode::getOwner(), llvm::MachineInstr::getParent(), llvm::rdf::DataFlowGraph::getRelatedRefs(), llvm::rdf::RegisterAggr::hasCoverOf(), i, llvm::AArch64PACKey::IA, llvm::rdf::NodeAddr< T >::Id, llvm::tgtok::In, llvm::SetVector< T, Vector, Set >::insert(), llvm::SmallSet< T, N, C >::insert(), llvm::rdf::RegisterAggr::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >, KeyT, ValueT, DenseMapInfo< KeyT >, llvm::detail::DenseMapPair< KeyT, ValueT > >::insert(), llvm::rdf::DataFlowGraph::IsCode(), llvm::rdf::RegisterAggr::isCoverOf(), llvm::rdf::DataFlowGraph::IsPreservingDef(), llvm_unreachable, MBB, N, llvm::X86II::OB, llvm::rdf::NodeAttrs::Phi, llvm::rdf::NodeAttrs::PhiRef, llvm::rdf::NodeAttrs::Preserving, llvm::MachineDominatorTree::properlyDominates(), llvm::reverse(), S, llvm::SetVector< T, Vector, Set >::size(), llvm::sort(), llvm::rdf::NodeAttrs::Stmt, llvm::X86II::TA, and llvm::rdf::NodeAttrs::Undef.
Referenced by computeLiveIns(), computePhiInfo(), and getAllReachingDefs().
getAllReachingDefsRec()
std::pair< NodeSet, bool > Liveness::getAllReachingDefsRec (RegisterRef RefRR, NodeAddr< RefNode * > RefA, NodeSet & Visited, const NodeSet & Defs)
Definition at line 308 of file RDFLiveness.cpp.
References MaxRecNest.
getLiveMap() [1/2]
LiveMapType& llvm::rdf::Liveness::getLiveMap () inline
Definition at line 108 of file RDFLiveness.h.
getLiveMap() [2/2]
const LiveMapType& llvm::rdf::Liveness::getLiveMap () const inline
Definition at line 109 of file RDFLiveness.h.
getNearestAliasedRef()
NodeAddr< RefNode * > Liveness::getNearestAliasedRef (RegisterRef RefRR, NodeAddr< InstrNode * > IA)
Find the nearest ref node aliased to RefRR, going upwards in the data flow, starting from the instruction immediately preceding Inst.
Definition at line 360 of file RDFLiveness.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::PhysicalRegisterInfo::alias(), B, BB, llvm::rdf::NodeAttrs::Clobbering, E, llvm::find_if(), llvm::rdf::DataFlowGraph::findBlock(), llvm::rdf::BlockNode::getCode(), llvm::MachineDominatorTree::getNode(), I, llvm::AArch64PACKey::IA, llvm::rdf::NodeAddr< T >::Id, llvm::MipsISD::Ins, llvm::rdf::DataFlowGraph::IsDef(), llvm::make_range(), llvm::rdf::CodeNode::members(), and N.
getRealUses()
const RefMap& llvm::rdf::Liveness::getRealUses (NodeId P) const inline
Definition at line 111 of file RDFLiveness.h.
References F, and P.
resetKills() [1/2]
void Liveness::resetKills ()
Definition at line 904 of file RDFLiveness.cpp.
References B, and llvm::rdf::DataFlowGraph::getMF().
resetKills() [2/2]
void Liveness::resetKills (MachineBasicBlock * B)
Definition at line 909 of file RDFLiveness.cpp.
References B, llvm::MCRegisterInfo::getNumRegs(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), I, llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegAliasIterator::isValid(), M, MI, llvm::BitVector::reset(), llvm::reverse(), S, llvm::BitVector::set(), and SI.
resetLiveIns()
void Liveness::resetLiveIns ()
Definition at line 889 of file RDFLiveness.cpp.
References B, llvm::rdf::DataFlowGraph::getMF(), I, llvm::make_range(), llvm::rdf::RegisterAggr::rr_begin(), and llvm::rdf::RegisterAggr::rr_end().
trace()
void llvm::rdf::Liveness::trace (bool T) inline
Definition at line 122 of file RDFLiveness.h.
References T.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFLiveness.h
lib/CodeGen/RDFLiveness.cpp