LLVM: llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false > Struct Template Reference
llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false > Struct Template Reference
#include "llvm/Object/ELFTypes.h"
Public Member Functions
uint32_t getRInfo (bool isMips64EL) const
void setRInfo (uint32_t R, bool IsMips64EL)
uint32_t getSymbol (bool isMips64EL) const
unsigned char getType (bool isMips64EL) const
void setSymbol (uint32_t s, bool IsMips64EL)
void setType (unsigned char t, bool IsMips64EL)
void setSymbolAndType (uint32_t s, unsigned char t, bool IsMips64EL)
Public Attributes
Elf_Addr r_offset
Elf_Word r_info
Static Public Attributes
static const bool IsRela = false
Detailed Description
template<endianness TargetEndianness>
struct llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >
Definition at line 385 of file ELFTypes.h.
Member Function Documentation
getRInfo()
template<endianness TargetEndianness> uint32_t llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::getRInfo (bool isMips64EL) const inline
Definition at line 391 of file ELFTypes.h.
References assert(), and isMips64EL().
getSymbol()
template<endianness TargetEndianness> uint32_t llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::getSymbol (bool isMips64EL) const inline
Definition at line 402 of file ELFTypes.h.
References isMips64EL().
getType()
template<endianness TargetEndianness> unsigned char llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::getType (bool isMips64EL) const inline
Definition at line 405 of file ELFTypes.h.
References isMips64EL().
setRInfo()
template<endianness TargetEndianness> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::setRInfo (uint32_t R, bool IsMips64EL) inline
Definition at line 395 of file ELFTypes.h.
References assert().
setSymbol()
template<endianness TargetEndianness> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::setSymbol (uint32_t s, bool IsMips64EL) inline
Definition at line 408 of file ELFTypes.h.
References getType(), and s.
setSymbolAndType()
template<endianness TargetEndianness> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::setSymbolAndType (uint32_t s, unsigned char t, bool IsMips64EL) inline
Definition at line 414 of file ELFTypes.h.
References s.
setType()
template<endianness TargetEndianness> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::setType (unsigned char t, bool IsMips64EL) inline
Definition at line 411 of file ELFTypes.h.
Member Data Documentation
IsRela
template<endianness TargetEndianness> const bool llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::IsRela = false static
Definition at line 387 of file ELFTypes.h.
r_info
template<endianness TargetEndianness> Elf_Word llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::r_info
Definition at line 389 of file ELFTypes.h.
r_offset
template<endianness TargetEndianness> Elf_Addr llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::r_offset
Definition at line 388 of file ELFTypes.h.
The documentation for this struct was generated from the following file:
include/llvm/Object/ELFTypes.h