LLVM: llvm::mcdxbc::PSVRuntimeInfo Struct Reference
llvm::mcdxbc::PSVRuntimeInfo Struct Reference
#include "llvm/MC/DXContainerPSVInfo.h"
Public Member Functions
void write (raw_ostream &OS, uint32_t Version=std::numeric_limits< uint32_t >::max()) const
void swapBytes (Triple::EnvironmentType Stage)
Public Attributes
dxbc::PSV::v2::RuntimeInfo BaseData
std::vector< dxbc::PSV::v2::ResourceBindInfo > Resources
Detailed Description
Definition at line 30 of file DXContainerPSVInfo.h.
Member Function Documentation
swapBytes()
void llvm::mcdxbc::PSVRuntimeInfo::swapBytes (Triple::EnvironmentType Stage) inline
Definition at line 40 of file DXContainerPSVInfo.h.
References BaseData, Resources, and llvm::dxbc::PSV::v2::RuntimeInfo::swapBytes().
write()
void PSVRuntimeInfo::write (raw_ostream & OS, uint32_t Version = std::numeric_limits<uint32_t>::max()) const
Definition at line 17 of file DXContainerPSVInfo.cpp.
References llvm::sys::IsBigEndianHost, OS, llvm::sys::swapByteOrder(), llvm::IndexedInstrProf::Version, and llvm::raw_ostream::write().
Member Data Documentation
BaseData
dxbc::PSV::v2::RuntimeInfo llvm::mcdxbc::PSVRuntimeInfo::BaseData
Definition at line 31 of file DXContainerPSVInfo.h.
Referenced by swapBytes().
Resources
std::vector<dxbc::PSV::v2::ResourceBindInfo> llvm::mcdxbc::PSVRuntimeInfo::Resources
Definition at line 32 of file DXContainerPSVInfo.h.
Referenced by swapBytes().
The documentation for this struct was generated from the following files:
include/llvm/MC/DXContainerPSVInfo.h
lib/MC/DXContainerPSVInfo.cpp