LLVM: llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator Struct Reference
llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator Struct Reference
#include "llvm/Object/DXContainer.h"
Public Member Functions
iterator (const ResourceArray &A, const char *C)
iterator (const iterator &)=default
value_type operator* ()
iterator operator++ ()
iterator operator++ (int)
iterator operator-- ()
iterator operator-- (int)
bool operator== (const iterator I)
bool operator!= (const iterator I)
Public Attributes
StringRef Data
size_t Stride
const char * Current
Detailed Description
Definition at line 44 of file DXContainer.h.
Constructor & Destructor Documentation
iterator() [1/2]
llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::iterator (const ResourceArray & A, const char * C) inline
Definition at line 49 of file DXContainer.h.
iterator() [2/2]
llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::iterator (const iterator &) default
Member Function Documentation
operator!=()
bool llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::operator!= (const iterator I) inline
Definition at line 91 of file DXContainer.h.
References I.
operator*()
value_type llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::operator* () inline
Definition at line 53 of file DXContainer.h.
References Current, Data, llvm::StringRef::end(), llvm::sys::IsBigEndianHost, memcpy(), Stride, and llvm::dxbc::PSV::v2::ResourceBindInfo::swapBytes().
operator++() [1/2]
iterator llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::operator++ () inline
Definition at line 66 of file DXContainer.h.
References Current, Data, llvm::StringRef::end(), and Stride.
operator++() [2/2]
iterator llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::operator++ (int) inline
Definition at line 72 of file DXContainer.h.
operator--() [1/2]
iterator llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::operator-- () inline
Definition at line 78 of file DXContainer.h.
References llvm::StringRef::begin(), Current, Data, and Stride.
operator--() [2/2]
iterator llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::operator-- (int) inline
Definition at line 84 of file DXContainer.h.
operator==()
bool llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::operator== (const iterator I) inline
Definition at line 90 of file DXContainer.h.
References Current, and I.
Member Data Documentation
Current
const char* llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::Current
Definition at line 47 of file DXContainer.h.
Referenced by operator*(), operator++(), operator--(), and operator==().
Data
StringRef llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::Data
Definition at line 45 of file DXContainer.h.
Referenced by operator*(), operator++(), and operator--().
Stride
size_t llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::Stride
Definition at line 46 of file DXContainer.h.
Referenced by operator*(), operator++(), and operator--().
The documentation for this struct was generated from the following file:
include/llvm/Object/DXContainer.h