LLVM: llvm::RegisterBankInfo::ValueMapping Struct Reference
llvm::RegisterBankInfo::ValueMapping Struct Reference
Helper struct that represents how a value is mapped through different register banks.
#include "llvm/CodeGen/RegisterBankInfo.h"
Public Member Functions
ValueMapping ()
The default constructor creates an invalid (isValid() == false) instance.
ValueMapping (const PartialMapping *BreakDown, unsigned NumBreakDowns)
Initialize a ValueMapping with the given parameter.
const PartialMapping * begin () const
Iterators through the PartialMappings.
const PartialMapping * end () const
bool partsAllUniform () const
bool isValid () const
Check if this ValueMapping is valid.
bool verify (unsigned MeaningfulBitWidth) const
Verify that this mapping makes sense for a value of MeaningfulBitWidth.
void dump () const
Print this on dbgs() stream.
void print (raw_ostream &OS) const
Print this on OS;.
Public Attributes
const PartialMapping * BreakDown
How the value is broken down between the different register banks.
unsigned NumBreakDowns
Number of partial mapping to break down this value.
Detailed Description
Helper struct that represents how a value is mapped through different register banks.
Note
: So far we do not have any users of the complex mappings (mappings with more than one partial mapping), but when we do, we would have needed to duplicate partial mappings. The alternative could be to use an array of pointers of partial mapping (i.e., PartialMapping **BreakDown) and duplicate the pointers instead.
E.g., Let say we have a 32-bit add and a <2 x 32-bit> vadd. We can expand the <2 x 32-bit> add into 2 x 32-bit add.
Currently the TableGen-like file would look like:
PartialMapping[] = {
/*32-bit add*/      {0, 32, GPR}, // Scalar entry repeated for first
                                  // vec elt.
/*2x32-bit add*/    {0, 32, GPR}, {32, 32, GPR},
/*<2x32-bit> vadd*/ {0, 64, VPR}
}; // PartialMapping duplicated.
ValueMapping[] {
  /*plain 32-bit add*/       {&PartialMapping[0], 1},
  /*expanded vadd on 2xadd*/ {&PartialMapping[1], 2},
  /*plain <2x32-bit> vadd*/  {&PartialMapping[3], 1}
};
With the array of pointer, we would have:
PartialMapping[] = {
/*32-bit add lower */ { 0, 32, GPR},
/*32-bit add upper */ {32, 32, GPR},
/*<2x32-bit> vadd */  { 0, 64, VPR}
}; // No more duplication.
BreakDowns[] = {
/*AddBreakDown*/   &PartialMapping[0],
/*2xAddBreakDown*/ &PartialMapping[0], &PartialMapping[1],
/*VAddBreakDown*/  &PartialMapping[2]
}; // Addresses of PartialMapping duplicated (smaller).
ValueMapping[] {
  /*plain 32-bit add*/       {&BreakDowns[0], 1},
  /*expanded vadd on 2xadd*/ {&BreakDowns[1], 2},
  /*plain <2x32-bit> vadd*/  {&BreakDowns[3], 1}
};
Given that a PartialMapping is actually small, the code size impact is actually a degradation. Moreover the compile time will be hit by the additional indirection. If PartialMapping gets bigger we may reconsider.
Definition at line 145 of file RegisterBankInfo.h.
Constructor & Destructor Documentation
ValueMapping() [1/2]
llvm::RegisterBankInfo::ValueMapping::ValueMapping () inline
The default constructor creates an invalid (isValid() == false) instance.
Definition at line 154 of file RegisterBankInfo.h.
ValueMapping() [2/2]
llvm::RegisterBankInfo::ValueMapping::ValueMapping (const PartialMapping * BreakDown, unsigned NumBreakDowns) inline
Initialize a ValueMapping with the given parameter.
BreakDown needs to have a life time at least as long as this instance.
Definition at line 159 of file RegisterBankInfo.h.
Member Function Documentation
begin()
const PartialMapping* llvm::RegisterBankInfo::ValueMapping::begin () const inline
Iterators through the PartialMappings.
Definition at line 163 of file RegisterBankInfo.h.
References BreakDown.
Referenced by llvm::RegisterBankInfo::OperandsMapper::createVRegs().
dump()
LLVM_DUMP_METHOD void RegisterBankInfo::ValueMapping::dump () const
Print this on dbgs() stream.
Definition at line 578 of file RegisterBankInfo.cpp.
References llvm::dbgs(), and llvm::print().
end()
const PartialMapping* llvm::RegisterBankInfo::ValueMapping::end () const inline
Definition at line 164 of file RegisterBankInfo.h.
References BreakDown, and NumBreakDowns.
Referenced by llvm::RegisterBankInfo::OperandsMapper::createVRegs().
isValid()
bool llvm::RegisterBankInfo::ValueMapping::isValid () const inline
Check if this ValueMapping is valid.
Definition at line 171 of file RegisterBankInfo.h.
References BreakDown, and NumBreakDowns.
partsAllUniform()
bool RegisterBankInfo::ValueMapping::partsAllUniform () const
Returns
true if all partial mappings are the same size and register bank.
Definition at line 535 of file RegisterBankInfo.cpp.
References llvm::sys::path::begin(), llvm::sys::path::end(), and First.
Referenced by llvm::RegBankSelect::repairReg().
print()
void RegisterBankInfo::ValueMapping::print (raw_ostream & OS) const
Print this on OS;.
Definition at line 584 of file RegisterBankInfo.cpp.
References OS.
Referenced by llvm::operator<<().
verify()
bool RegisterBankInfo::ValueMapping::verify (unsigned MeaningfulBitWidth) const
Verify that this mapping makes sense for a value of MeaningfulBitWidth.
Note
This method does not check anything when assertions are disabled.
Returns
True is the check was successful.
Definition at line 548 of file RegisterBankInfo.cpp.
References assert(), llvm::APInt::getBitsSet(), llvm::RegisterBankInfo::PartialMapping::getHighBitIdx(), llvm::APInt::isAllOnes(), llvm::max(), llvm::RegisterBankInfo::PartialMapping::StartIdx, and llvm::RegisterBankInfo::PartialMapping::verify().
Referenced by llvm::RegisterBankInfo::InstructionMapping::verify().
Member Data Documentation
BreakDown
const PartialMapping* llvm::RegisterBankInfo::ValueMapping::BreakDown
How the value is broken down between the different register banks.
Definition at line 147 of file RegisterBankInfo.h.
Referenced by llvm::RegBankSelect::applyMapping(), llvm::AMDGPURegisterBankInfo::applyMappingBFE(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), llvm::RegBankSelect::assignmentMatch(), begin(), llvm::ARM::checkValueMapping(), end(), llvm::AMDGPURegisterBankInfo::getBreakDownCost(), llvm::RegBankSelect::getRepairCost(), isValid(), and llvm::RegBankSelect::repairReg().
NumBreakDowns
unsigned llvm::RegisterBankInfo::ValueMapping::NumBreakDowns
Number of partial mapping to break down this value.
Definition at line 150 of file RegisterBankInfo.h.
Referenced by llvm::RegisterBankInfo::applyDefaultMapping(), llvm::RegBankSelect::applyMapping(), llvm::RegBankSelect::assignmentMatch(), llvm::ARM::checkValueMapping(), end(), llvm::AMDGPURegisterBankInfo::getBreakDownCost(), llvm::RegBankSelect::getRepairCost(), llvm::RegisterBankInfo::OperandsMapper::getVRegs(), isValid(), llvm::RegBankSelect::repairReg(), and llvm::RegBankSelect::tryAvoidingSplit().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RegisterBankInfo.h
lib/CodeGen/RegisterBankInfo.cpp