LLVM: llvm::SchedRemainder Struct Reference
llvm::SchedRemainder Struct Reference
Summarize the unscheduled region.
#include "llvm/CodeGen/MachineScheduler.h"
Public Member Functions
SchedRemainder ()
void reset ()
void init (ScheduleDAGMI *DAG, const TargetSchedModel *SchedModel)
Public Attributes
unsigned CriticalPath
unsigned CyclicCritPath
unsigned RemIssueCount
bool IsAcyclicLatencyLimited
SmallVector< unsigned, 16 > RemainingCounts
Detailed Description
Summarize the unscheduled region.
Definition at line 585 of file MachineScheduler.h.
Constructor & Destructor Documentation
SchedRemainder()
llvm::SchedRemainder::SchedRemainder () inline
Definition at line 598 of file MachineScheduler.h.
References reset().
Member Function Documentation
init()
void SchedRemainder::init (ScheduleDAGMI * DAG, const TargetSchedModel * SchedModel)
Definition at line 2185 of file MachineScheduler.cpp.
References llvm::SUnit::getInstr(), llvm::TargetSchedModel::getMicroOpFactor(), llvm::TargetSchedModel::getNumMicroOps(), llvm::TargetSchedModel::getNumProcResourceKinds(), llvm::TargetSchedModel::getResourceFactor(), llvm::ScheduleDAGInstrs::getSchedClass(), llvm::TargetSchedModel::getWriteProcResBegin(), llvm::TargetSchedModel::getWriteProcResEnd(), llvm::TargetSchedModel::hasInstrSchedModel(), RemainingCounts, RemIssueCount, reset(), llvm::SmallVectorImpl< T >::resize(), llvm::PPCISD::SC, and llvm::ScheduleDAG::SUnits.
Referenced by llvm::GenericScheduler::initialize(), and llvm::PostGenericScheduler::initialize().
reset()
void llvm::SchedRemainder::reset () inline
Definition at line 600 of file MachineScheduler.h.
References llvm::SmallVectorImpl< T >::clear(), CriticalPath, CyclicCritPath, IsAcyclicLatencyLimited, RemainingCounts, and RemIssueCount.
Referenced by init(), and SchedRemainder().
Member Data Documentation
CriticalPath
unsigned llvm::SchedRemainder::CriticalPath
Definition at line 587 of file MachineScheduler.h.
Referenced by llvm::GenericScheduler::checkAcyclicLatency(), llvm::GenericScheduler::registerRoots(), llvm::PostGenericScheduler::registerRoots(), reset(), and llvm::GenericSchedulerBase::setPolicy().
CyclicCritPath
unsigned llvm::SchedRemainder::CyclicCritPath
Definition at line 588 of file MachineScheduler.h.
Referenced by llvm::GenericScheduler::checkAcyclicLatency(), llvm::GenericScheduler::registerRoots(), and reset().
IsAcyclicLatencyLimited
bool llvm::SchedRemainder::IsAcyclicLatencyLimited
Definition at line 593 of file MachineScheduler.h.
Referenced by llvm::GenericScheduler::checkAcyclicLatency(), reset(), llvm::PPCPreRASchedStrategy::tryCandidate(), and llvm::GenericScheduler::tryCandidate().
RemainingCounts
SmallVector<unsigned, 16> llvm::SchedRemainder::RemainingCounts
Definition at line 596 of file MachineScheduler.h.
Referenced by llvm::SchedBoundary::countResource(), llvm::SchedBoundary::getOtherResourceCount(), init(), and reset().
RemIssueCount
unsigned llvm::SchedRemainder::RemIssueCount
Definition at line 591 of file MachineScheduler.h.
Referenced by llvm::SchedBoundary::bumpNode(), llvm::GenericScheduler::checkAcyclicLatency(), llvm::SchedBoundary::getOtherResourceCount(), init(), and reset().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/MachineScheduler.h
lib/CodeGen/MachineScheduler.cpp