LLVM: llvm::DenseMapInfo< ElementCount, void > Struct Reference
llvm::DenseMapInfo< ElementCount, void > Struct Reference
#include "llvm/Support/TypeSize.h"
Static Public Member Functions
static ElementCount getEmptyKey ()
static ElementCount getTombstoneKey ()
static unsigned getHashValue (const ElementCount &EltCnt)
static bool isEqual (const ElementCount &LHS, const ElementCount &RHS)
Detailed Description
Definition at line 419 of file TypeSize.h.
Member Function Documentation
getEmptyKey()
static ElementCount llvm::DenseMapInfo< ElementCount, void >::getEmptyKey () inline static
Definition at line 420 of file TypeSize.h.
References llvm::ElementCount::getScalable().
getHashValue()
static unsigned llvm::DenseMapInfo< ElementCount, void >::getHashValue (const ElementCount & EltCnt) inline static
Definition at line 426 of file TypeSize.h.
References llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), and llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable().
getTombstoneKey()
static ElementCount llvm::DenseMapInfo< ElementCount, void >::getTombstoneKey () inline static
Definition at line 423 of file TypeSize.h.
References llvm::ElementCount::getFixed().
isEqual()
static bool llvm::DenseMapInfo< ElementCount, void >::isEqual (const ElementCount & LHS, const ElementCount & RHS) inline static
Definition at line 433 of file TypeSize.h.
References LHS, and RHS.
The documentation for this struct was generated from the following file:
include/llvm/Support/TypeSize.h