LLVM: llvm::rdf::DataFlowGraph Struct Reference
llvm::rdf::DataFlowGraph Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Classes
struct DefStack
Public Types
using DefStackMap = std::unordered_map< RegisterId, DefStack >
Public Member Functions
DataFlowGraph (MachineFunction &mf, const TargetInstrInfo &tii, const TargetRegisterInfo &tri, const MachineDominatorTree &mdt, const MachineDominanceFrontier &mdf)
DataFlowGraph (MachineFunction &mf, const TargetInstrInfo &tii, const TargetRegisterInfo &tri, const MachineDominatorTree &mdt, const MachineDominanceFrontier &mdf, const TargetOperandInfo &toi)
NodeBase * ptr (NodeId N) const
template<typename T >
T ptr (NodeId N) const
NodeId id (const NodeBase *P) const
template<typename T >
NodeAddr< T > addr (NodeId N) const
NodeAddr< FuncNode * > getFunc () const
MachineFunction & getMF () const
const TargetInstrInfo & getTII () const
const TargetRegisterInfo & getTRI () const
const PhysicalRegisterInfo & getPRI () const
const MachineDominatorTree & getDT () const
const MachineDominanceFrontier & getDF () const
const RegisterAggr & getLiveIns () const
void build (unsigned Options=BuildOptions::None)
void pushAllDefs (NodeAddr< InstrNode * > IA, DefStackMap &DM)
void markBlock (NodeId B, DefStackMap &DefM)
void releaseBlock (NodeId B, DefStackMap &DefM)
PackedRegisterRef pack (RegisterRef RR)
PackedRegisterRef pack (RegisterRef RR) const
RegisterRef unpack (PackedRegisterRef PR) const
RegisterRef makeRegRef (unsigned Reg, unsigned Sub) const
RegisterRef makeRegRef (const MachineOperand &Op) const
NodeAddr< RefNode * > getNextRelated (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
NodeAddr< RefNode * > getNextShadow (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA, bool Create)
NodeAddr< RefNode * > getNextShadow (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
NodeList getRelatedRefs (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
NodeAddr< BlockNode * > findBlock (MachineBasicBlock *BB) const
void unlinkUse (NodeAddr< UseNode * > UA, bool RemoveFromOwner)
void unlinkDef (NodeAddr< DefNode * > DA, bool RemoveFromOwner)
Static Public Member Functions
template<uint16_t Kind>
static bool IsRef (const NodeAddr< NodeBase * > BA)
template<uint16_t Kind>
static bool IsCode (const NodeAddr< NodeBase * > BA)
static bool IsDef (const NodeAddr< NodeBase * > BA)
static bool IsUse (const NodeAddr< NodeBase * > BA)
static bool IsPhi (const NodeAddr< NodeBase * > BA)
static bool IsPreservingDef (const NodeAddr< DefNode * > DA)
Detailed Description
Definition at line 645 of file RDFGraph.h.
Member Typedef Documentation
DefStackMap
using llvm::rdf::DataFlowGraph::DefStackMap = std::unordered_map<RegisterId, DefStack>
Definition at line 737 of file RDFGraph.h.
Constructor & Destructor Documentation
DataFlowGraph() [1/2]
DataFlowGraph::DataFlowGraph (MachineFunction & mf, const TargetInstrInfo & tii, const TargetRegisterInfo & tri, const MachineDominatorTree & mdt, const MachineDominanceFrontier & mdf)
Definition at line 644 of file RDFGraph.cpp.
DataFlowGraph() [2/2]
DataFlowGraph::DataFlowGraph (MachineFunction & mf, const TargetInstrInfo & tii, const TargetRegisterInfo & tri, const MachineDominatorTree & mdt, const MachineDominanceFrontier & mdf, const TargetOperandInfo & toi)
Definition at line 652 of file RDFGraph.cpp.
Member Function Documentation
addr()
template<typename T > NodeAddr<T> llvm::rdf::DataFlowGraph::addr (NodeId N) const inline
Definition at line 660 of file RDFGraph.h.
References N.
Referenced by llvm::rdf::BlockNode::addPhi(), llvm::rdf::DeadCodeElimination::collect(), llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::DeadCodeElimination::erase(), llvm::rdf::Liveness::getAllReachedUses(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::rdf::CodeNode::getFirstMember(), llvm::rdf::CodeNode::getLastMember(), llvm::rdf::RefNode::getOwner(), llvm::rdf::InstrNode::getOwner(), llvm::rdf::CodeNode::removeMember(), and llvm::rdf::CopyPropagation::run().
build()
void DataFlowGraph::build (unsigned Options = BuildOptions::None)
Definition at line 869 of file RDFGraph.cpp.
References llvm::rdf::CodeNode::addMember(), llvm::rdf::NodeAddr< T >::Addr, assert(), B, llvm::AArch64PACKey::DA, DM, E, llvm::MachineFunction::empty(), findBlock(), llvm::rdf::BlockNode::getCode(), I, llvm::AArch64PACKey::IA, llvm::rdf::RegisterAggr::insert(), llvm::rdf::BuildOptions::KeepDeadPhis, llvm::MachineBasicBlock::liveins(), llvm::MachineRegisterInfo::liveins(), llvm::rdf::CodeNode::members(), MRI, Options, P, PB(), llvm::rdf::NodeAttrs::PhiRef, llvm::MachineBasicBlock::pred_empty(), llvm::rdf::NodeAttrs::Preserving, RA, llvm::rdf::RegisterAggr::rr_begin(), llvm::rdf::RegisterAggr::rr_end(), and llvm::MachineRegisterInfo::tracksLiveness().
findBlock()
NodeAddr<BlockNode*> llvm::rdf::DataFlowGraph::findBlock (MachineBasicBlock * BB) const inline
Definition at line 767 of file RDFGraph.h.
References BB.
Referenced by build(), and llvm::rdf::Liveness::getNearestAliasedRef().
getDF()
const MachineDominanceFrontier& llvm::rdf::DataFlowGraph::getDF () const inline
Definition at line 670 of file RDFGraph.h.
getDT()
const MachineDominatorTree& llvm::rdf::DataFlowGraph::getDT () const inline
Definition at line 669 of file RDFGraph.h.
getFunc()
NodeAddr<FuncNode*> llvm::rdf::DataFlowGraph::getFunc () const inline
Definition at line 664 of file RDFGraph.h.
Referenced by llvm::rdf::DeadCodeElimination::collect(), llvm::rdf::Liveness::computeLiveIns(), and llvm::rdf::Liveness::computePhiInfo().
getLiveIns()
const RegisterAggr& llvm::rdf::DataFlowGraph::getLiveIns () const inline
Definition at line 671 of file RDFGraph.h.
Referenced by llvm::rdf::Liveness::computeLiveIns().
getMF()
MachineFunction& llvm::rdf::DataFlowGraph::getMF () const inline
Definition at line 665 of file RDFGraph.h.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::resetKills(), llvm::rdf::Liveness::resetLiveIns(), and llvm::rdf::CopyPropagation::run().
getNextRelated()
NodeAddr< RefNode * > DataFlowGraph::getNextRelated (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
Definition at line 1140 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, assert(), llvm::rdf::PhiUseNode::getPredecessor(), llvm::AArch64PACKey::IA, RA, llvm::rdf::NodeAttrs::Stmt, llvm::X86II::TA, and llvm::rdf::NodeAttrs::Use.
Referenced by getRelatedRefs().
getNextShadow() [1/2]
NodeAddr< RefNode * > DataFlowGraph::getNextShadow (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
Definition at line 1222 of file RDFGraph.cpp.
References assert(), llvm::AArch64PACKey::IA, RA, llvm::rdf::NodeAttrs::Shadow, and llvm::X86II::TA.
getNextShadow() [2/2]
NodeAddr< RefNode * > DataFlowGraph::getNextShadow (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA, bool Create)
Definition at line 1201 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, assert(), llvm::AArch64PACKey::IA, RA, llvm::rdf::NodeBase::setFlags(), llvm::rdf::NodeAttrs::Shadow, and llvm::X86II::TA.
getPRI()
const PhysicalRegisterInfo& llvm::rdf::DataFlowGraph::getPRI () const inline
Definition at line 668 of file RDFGraph.h.
getRelatedRefs()
NodeList DataFlowGraph::getRelatedRefs (NodeAddr< InstrNode * > IA, NodeAddr< RefNode * > RA) const
Definition at line 1114 of file RDFGraph.cpp.
References assert(), getNextRelated(), llvm::AArch64PACKey::IA, and RA.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), and llvm::rdf::Liveness::getAllReachingDefs().
getTII()
const TargetInstrInfo& llvm::rdf::DataFlowGraph::getTII () const inline
Definition at line 666 of file RDFGraph.h.
getTRI()
const TargetRegisterInfo& llvm::rdf::DataFlowGraph::getTRI () const inline
Definition at line 667 of file RDFGraph.h.
Referenced by llvm::rdf::CopyPropagation::interpretAsCopy(), and llvm::rdf::CopyPropagation::run().
id()
NodeId DataFlowGraph::id (const NodeBase * P) const
Definition at line 774 of file RDFGraph.cpp.
References P.
Referenced by llvm::rdf::CodeNode::addMember().
IsCode()
template<uint16_t Kind> static bool llvm::rdf::DataFlowGraph::IsCode (const NodeAddr< NodeBase * > BA) inline static
Definition at line 791 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, and llvm::rdf::NodeAttrs::Code.
Referenced by llvm::rdf::DeadCodeElimination::collect(), llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::DeadCodeElimination::erase(), llvm::rdf::Liveness::getAllReachingDefs(), and llvm::rdf::CopyPropagation::run().
IsDef()
static bool llvm::rdf::DataFlowGraph::IsDef (const NodeAddr< NodeBase * > BA) inline static
Definition at line 796 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Def, and llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::DeadCodeElimination::collect(), llvm::rdf::DeadCodeElimination::erase(), llvm::rdf::Liveness::getNearestAliasedRef(), and llvm::rdf::CopyPropagation::run().
IsPhi()
static bool llvm::rdf::DataFlowGraph::IsPhi (const NodeAddr< NodeBase * > BA) inline static
Definition at line 806 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Code, and llvm::rdf::NodeAttrs::Phi.
IsPreservingDef()
static bool llvm::rdf::DataFlowGraph::IsPreservingDef (const NodeAddr< DefNode * > DA) inline static
Definition at line 811 of file RDFGraph.h.
References llvm::AArch64PACKey::DA, llvm::rdf::NodeAttrs::Preserving, and llvm::rdf::NodeAttrs::Undef.
Referenced by llvm::rdf::Liveness::getAllReachedUses(), and llvm::rdf::Liveness::getAllReachingDefs().
IsRef()
template<uint16_t Kind> static bool llvm::rdf::DataFlowGraph::IsRef (const NodeAddr< NodeBase * > BA) inline static
Definition at line 785 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, and llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::Liveness::computeLiveIns(), and llvm::rdf::Liveness::computePhiInfo().
IsUse()
static bool llvm::rdf::DataFlowGraph::IsUse (const NodeAddr< NodeBase * > BA) inline static
Definition at line 801 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Ref, and llvm::rdf::NodeAttrs::Use.
Referenced by llvm::rdf::DeadCodeElimination::erase().
makeRegRef() [1/2]
RegisterRef DataFlowGraph::makeRegRef (const MachineOperand & Op) const
Definition at line 976 of file RDFGraph.cpp.
References assert(), llvm::LaneBitmask::getAll(), llvm::rdf::PhysicalRegisterInfo::getRegMaskId(), and makeRegRef().
makeRegRef() [2/2]
RegisterRef DataFlowGraph::makeRegRef (unsigned Reg, unsigned Sub) const
Definition at line 967 of file RDFGraph.cpp.
References assert(), llvm::TargetRegisterInfo::getSubReg(), llvm::Register::isPhysicalRegister(), and llvm::rdf::PhysicalRegisterInfo::isRegMaskId().
Referenced by llvm::rdf::RefNode::getRegRef(), llvm::rdf::CopyPropagation::interpretAsCopy(), and makeRegRef().
markBlock()
void DataFlowGraph::markBlock (NodeId B, DefStackMap & DefM)
Definition at line 984 of file RDFGraph.cpp.
References B, and P.
pack() [1/2]
PackedRegisterRef llvm::rdf::DataFlowGraph::pack (RegisterRef RR) inline
Definition at line 744 of file RDFGraph.h.
References llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::rdf::RegisterRef::Mask, and llvm::rdf::RegisterRef::Reg.
Referenced by llvm::rdf::RefNode::setRegRef().
pack() [2/2]
PackedRegisterRef llvm::rdf::DataFlowGraph::pack (RegisterRef RR) const inline
Definition at line 747 of file RDFGraph.h.
References llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::rdf::RegisterRef::Mask, and llvm::rdf::RegisterRef::Reg.
ptr() [1/2]
NodeBase * DataFlowGraph::ptr (NodeId N) const
Definition at line 767 of file RDFGraph.cpp.
References N.
Referenced by ptr().
ptr() [2/2]
template<typename T > T llvm::rdf::DataFlowGraph::ptr (NodeId N) const inline
Definition at line 654 of file RDFGraph.h.
References N, ptr(), and T.
pushAllDefs()
void DataFlowGraph::pushAllDefs (NodeAddr< InstrNode * > IA, DefStackMap & DM)
Definition at line 1009 of file RDFGraph.cpp.
References llvm::AArch64PACKey::IA.
releaseBlock()
void DataFlowGraph::releaseBlock (NodeId B, DefStackMap & DefM)
Definition at line 991 of file RDFGraph.cpp.
References B, E, I, and P.
unlinkDef()
void llvm::rdf::DataFlowGraph::unlinkDef (NodeAddr< DefNode * > DA, bool RemoveFromOwner) inline
Definition at line 777 of file RDFGraph.h.
References llvm::AArch64PACKey::DA.
Referenced by llvm::rdf::DeadCodeElimination::erase().
unlinkUse()
void llvm::rdf::DataFlowGraph::unlinkUse (NodeAddr< UseNode * > UA, bool RemoveFromOwner) inline
Definition at line 771 of file RDFGraph.h.
Referenced by llvm::rdf::DeadCodeElimination::erase(), and llvm::rdf::CopyPropagation::run().
unpack()
RegisterRef llvm::rdf::DataFlowGraph::unpack (PackedRegisterRef PR) const inline
Definition at line 750 of file RDFGraph.h.
References llvm::rdf::LaneMaskIndex::getLaneMaskForIndex(), llvm::rdf::PackedRegisterRef::MaskId, and llvm::rdf::PackedRegisterRef::Reg.
Referenced by llvm::rdf::RefNode::getRegRef().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp