LLVM: llvm::AttributorCallGraph Struct Reference
llvm::AttributorCallGraph Struct Reference
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
AttributorCallGraph (Attributor &A)
virtual ~AttributorCallGraph ()=default
AACallEdgeIterator optimisticEdgesBegin () const override
AACallEdgeIterator optimisticEdgesEnd () const override
void populateAll () const
Force populate the entire call graph.
void print ()
Public Member Functions inherited from llvm::AACallGraphNode
AACallGraphNode (Attributor &A)
virtual ~AACallGraphNode ()=default
iterator_range< AACallEdgeIterator > optimisticEdgesRange () const
Iterator range for exploring the call graph.
Additional Inherited Members
Protected Attributes inherited from llvm::AACallGraphNode
Attributor & A
Reference to Attributor needed for GraphTraits implementation.
Detailed Description
Definition at line 4933 of file Attributor.h.
Constructor & Destructor Documentation
AttributorCallGraph()
llvm::AttributorCallGraph::AttributorCallGraph (Attributor & A) inline
Definition at line 4934 of file Attributor.h.
~AttributorCallGraph()
virtual llvm::AttributorCallGraph::~AttributorCallGraph () virtual default
Member Function Documentation
optimisticEdgesBegin()
AACallEdgeIterator llvm::AttributorCallGraph::optimisticEdgesBegin () const inline override virtual
Implements llvm::AACallGraphNode.
Definition at line 4937 of file Attributor.h.
References llvm::AACallGraphNode::A, and llvm::SetVector< T, Vector, Set >::begin().
optimisticEdgesEnd()
AACallEdgeIterator llvm::AttributorCallGraph::optimisticEdgesEnd () const inline override virtual
Implements llvm::AACallGraphNode.
Definition at line 4941 of file Attributor.h.
References llvm::AACallGraphNode::A, and llvm::SetVector< T, Vector, Set >::end().
populateAll()
void llvm::AttributorCallGraph::populateAll () const inline
Force populate the entire call graph.
Definition at line 4946 of file Attributor.h.
References llvm::AACallGraphNode::optimisticEdgesRange().
Referenced by llvm::Attributor::run().
print()
void AttributorCallGraph::print ()
Definition at line 11452 of file AttributorAttributes.cpp.
References outs, and llvm::WriteGraph().
Referenced by llvm::Attributor::run().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp