LLVM: llvm::objcopy::macho::Section Struct Reference
llvm::objcopy::macho::Section Struct Reference
#include "ObjCopy/MachO/MachOObject.h"
Public Member Functions
Section (StringRef SegName, StringRef SectName)
Section (StringRef SegName, StringRef SectName, StringRef Content)
MachO::SectionType getType () const
bool isVirtualSection () const
bool hasValidOffset () const
Public Attributes
uint32_t Index
std::string Segname
std::string Sectname
std::string CanonicalName
uint64_t Addr = 0
uint64_t Size = 0
std::optional< uint32_t > OriginalOffset
uint32_t Offset = 0
uint32_t Align = 0
uint32_t RelOff = 0
uint32_t NReloc = 0
uint32_t Flags = 0
uint32_t Reserved1 = 0
uint32_t Reserved2 = 0
uint32_t Reserved3 = 0
StringRef Content
std::vector< RelocationInfo > Relocations
Detailed Description
Definition at line 38 of file MachOObject.h.
Constructor & Destructor Documentation
Section() [1/2]
Section::Section (StringRef SegName, StringRef SectName)
Definition at line 16 of file MachOObject.cpp.
Section() [2/2]
Section::Section (StringRef SegName, StringRef SectName, StringRef Content)
Definition at line 20 of file MachOObject.cpp.
Member Function Documentation
getType()
MachO::SectionType llvm::objcopy::macho::Section::getType () const inline
Definition at line 63 of file MachOObject.h.
References Flags, and llvm::MachO::SECTION_TYPE.
Referenced by isVirtualSection().
hasValidOffset()
bool llvm::objcopy::macho::Section::hasValidOffset () const inline
Definition at line 73 of file MachOObject.h.
References isVirtualSection(), and OriginalOffset.
isVirtualSection()
bool llvm::objcopy::macho::Section::isVirtualSection () const inline
Definition at line 67 of file MachOObject.h.
References getType(), llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_THREAD_LOCAL_ZEROFILL, and llvm::MachO::S_ZEROFILL.
Referenced by hasValidOffset().
Member Data Documentation
Addr
uint64_t llvm::objcopy::macho::Section::Addr = 0
Definition at line 44 of file MachOObject.h.
Align
uint32_t llvm::objcopy::macho::Section::Align = 0
Definition at line 49 of file MachOObject.h.
CanonicalName
std::string llvm::objcopy::macho::Section::CanonicalName
Definition at line 43 of file MachOObject.h.
Content
StringRef llvm::objcopy::macho::Section::Content
Definition at line 56 of file MachOObject.h.
Referenced by addSection(), and updateSection().
Flags
uint32_t llvm::objcopy::macho::Section::Flags = 0
Definition at line 52 of file MachOObject.h.
Referenced by getType().
Index
uint32_t llvm::objcopy::macho::Section::Index
Definition at line 39 of file MachOObject.h.
NReloc
uint32_t llvm::objcopy::macho::Section::NReloc = 0
Definition at line 51 of file MachOObject.h.
Offset
uint32_t llvm::objcopy::macho::Section::Offset = 0
Definition at line 48 of file MachOObject.h.
OriginalOffset
std::optional<uint32_t> llvm::objcopy::macho::Section::OriginalOffset
Definition at line 47 of file MachOObject.h.
Referenced by hasValidOffset().
Relocations
std::vector<RelocationInfo> llvm::objcopy::macho::Section::Relocations
Definition at line 57 of file MachOObject.h.
RelOff
uint32_t llvm::objcopy::macho::Section::RelOff = 0
Definition at line 50 of file MachOObject.h.
Reserved1
uint32_t llvm::objcopy::macho::Section::Reserved1 = 0
Definition at line 53 of file MachOObject.h.
Reserved2
uint32_t llvm::objcopy::macho::Section::Reserved2 = 0
Definition at line 54 of file MachOObject.h.
Reserved3
uint32_t llvm::objcopy::macho::Section::Reserved3 = 0
Definition at line 55 of file MachOObject.h.
Sectname
std::string llvm::objcopy::macho::Section::Sectname
Definition at line 41 of file MachOObject.h.
Segname
std::string llvm::objcopy::macho::Section::Segname
Definition at line 40 of file MachOObject.h.
Size
uint64_t llvm::objcopy::macho::Section::Size = 0
Definition at line 45 of file MachOObject.h.
Referenced by addSection(), and updateSection().
The documentation for this struct was generated from the following files:
lib/ObjCopy/MachO/MachOObject.h
lib/ObjCopy/MachO/MachOObject.cpp