LLVM: AbstractManglingParser< Derived, Alloc >::OperatorInfo Struct Reference
AbstractManglingParser< Derived, Alloc >::OperatorInfo Struct Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Public Types
enum OIKind : unsigned char {
Prefix, Postfix, Binary, Array,
Member, New, Del, Call,
CCast, Conditional, NameOnly, NamedCast,
OfIdOp, Unnameable = NamedCast
}
Public Member Functions
constexpr OperatorInfo (const char(&E)[3], OIKind K, bool F, Node::Prec P, const char *N)
bool operator< (const OperatorInfo &Other) const
bool operator< (const char *Peek) const
bool operator== (const char *Peek) const
bool operator!= (const char *Peek) const
StringView getSymbol () const
StringView getName () const
OIKind getKind () const
bool getFlag () const
Node::Prec getPrecedence () const
Public Attributes
char Enc [2]
OIKind Kind
bool Flag: 1
Node::Prec Prec: 7
const char * Name
Detailed Description
template<typename Derived, typename Alloc>
struct AbstractManglingParser< Derived, Alloc >::OperatorInfo
Definition at line 2584 of file ItaniumDemangle.h.
Member Enumeration Documentation
OIKind
template<typename Derived , typename Alloc > enum AbstractManglingParser::OperatorInfo::OIKind : unsigned char
Enumerator
Prefix
Postfix
Binary
Array
Member
New
Del
Call
CCast
Conditional
NameOnly
NamedCast
OfIdOp
Unnameable
Definition at line 2585 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
OperatorInfo()
template<typename Derived , typename Alloc > constexpr AbstractManglingParser< Derived, Alloc >::OperatorInfo::OperatorInfo (const char(&) E[3], OIKind K, bool F, Node::Prec P, const char * N) inline constexpr
Definition at line 2610 of file ItaniumDemangle.h.
References E.
Member Function Documentation
getFlag()
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::OperatorInfo::getFlag () const inline
Definition at line 2639 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::Flag.
getKind()
template<typename Derived , typename Alloc > OIKind AbstractManglingParser< Derived, Alloc >::OperatorInfo::getKind () const inline
Definition at line 2638 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::Kind.
getName()
template<typename Derived , typename Alloc > StringView AbstractManglingParser< Derived, Alloc >::OperatorInfo::getName () const inline
Definition at line 2637 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::Name.
getPrecedence()
template<typename Derived , typename Alloc > Node::Prec AbstractManglingParser< Derived, Alloc >::OperatorInfo::getPrecedence () const inline
Definition at line 2640 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::Prec.
getSymbol()
template<typename Derived , typename Alloc > StringView AbstractManglingParser< Derived, Alloc >::OperatorInfo::getSymbol () const inline
Definition at line 2627 of file ItaniumDemangle.h.
References assert(), StringView::consumeFront(), StringView::dropFront(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::Kind, AbstractManglingParser< Derived, Alloc >::OperatorInfo::Name, StringView::startsWith(), and AbstractManglingParser< Derived, Alloc >::OperatorInfo::Unnameable.
operator!=()
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::OperatorInfo::operator!= (const char * Peek) const inline
Definition at line 2624 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::operator==().
operator<() [1/2]
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::OperatorInfo::operator< (const char * Peek) const inline
Definition at line 2618 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::Enc.
operator<() [2/2]
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::OperatorInfo::operator< (const OperatorInfo & Other) const inline
Definition at line 2615 of file ItaniumDemangle.h.
References Other.
operator==()
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::OperatorInfo::operator== (const char * Peek) const inline
Definition at line 2621 of file ItaniumDemangle.h.
References AbstractManglingParser< Derived, Alloc >::OperatorInfo::Enc.
Referenced by AbstractManglingParser< Derived, Alloc >::OperatorInfo::operator!=().
Member Data Documentation
Enc
template<typename Derived , typename Alloc > char AbstractManglingParser< Derived, Alloc >::OperatorInfo::Enc[2]
Definition at line 2603 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::OperatorInfo::operator<(), and AbstractManglingParser< Derived, Alloc >::OperatorInfo::operator==().
Flag
template<typename Derived , typename Alloc > bool AbstractManglingParser< Derived, Alloc >::OperatorInfo::Flag
Definition at line 2605 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::OperatorInfo::getFlag().
Kind
template<typename Derived , typename Alloc > OIKind AbstractManglingParser< Derived, Alloc >::OperatorInfo::Kind
Definition at line 2604 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::OperatorInfo::getKind(), and AbstractManglingParser< Derived, Alloc >::OperatorInfo::getSymbol().
Name
template<typename Derived , typename Alloc > const char* AbstractManglingParser< Derived, Alloc >::OperatorInfo::Name
Definition at line 2607 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::OperatorInfo::getName(), and AbstractManglingParser< Derived, Alloc >::OperatorInfo::getSymbol().
Prec
template<typename Derived , typename Alloc > Node::Prec AbstractManglingParser< Derived, Alloc >::OperatorInfo::Prec
Definition at line 2606 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::OperatorInfo::getPrecedence().
The documentation for this struct was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h