LLVM: llvm::DOTGraphTraits< DOTMachineFuncInfo * > Struct Reference
llvm::DOTGraphTraits< DOTMachineFuncInfo * > Struct Reference
#include "llvm/CodeGen/MachineCFGPrinter.h"
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const MachineBasicBlock *Node, DOTMachineFuncInfo *CFGInfo)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType >
std::string getNodeLabel (const void *, const GraphType &)
getNodeLabel - Given a node and a pointer to the top level graph, return the label to print in the node.
Static Public Member Functions
static void eraseComment (std::string &OutStr, unsigned &I, unsigned Idx)
static std::string getSimpleNodeLabel (const MachineBasicBlock *Node, DOTMachineFuncInfo *)
static std::string getCompleteNodeLabel (const MachineBasicBlock *Node, DOTMachineFuncInfo *, function_ref< void(raw_string_ostream &, const MachineBasicBlock &)> HandleBasicBlock=[](raw_string_ostream &OS, const MachineBasicBlock &Node) -> void { OS<< Node;}, function_ref< void(std::string &, unsigned &, unsigned)> HandleComment=eraseComment)
static std::string getGraphName (DOTMachineFuncInfo *CFGInfo)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType >
static std::string getGraphName (const GraphType &)
getGraphName - Return the label for the graph as a whole.
template<typename GraphType >
static std::string getGraphProperties (const GraphType &)
getGraphProperties - Return any custom properties that should be included in the top level graph structure for dot.
static bool renderGraphFromBottomUp ()
renderGraphFromBottomUp - If this function returns true, the graph is emitted bottom-up instead of top-down.
template<typename GraphType >
static bool isNodeHidden (const void *, const GraphType &)
isNodeHidden - If the function returns true, the given node is not displayed in the graph.
static bool renderNodesUsingHTML ()
template<typename GraphType >
static std::string getNodeIdentifierLabel (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeAttributes (const void *, const GraphType &)
If you want to specify custom node attributes, this is the place to do so.
template<typename EdgeIter , typename GraphType >
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
If you want to override the dot attributes printed for a particular edge, override this method.
template<typename EdgeIter >
static std::string getEdgeSourceLabel (const void *, EdgeIter)
getEdgeSourceLabel - If you want to label the edge source itself, implement this method.
template<typename EdgeIter >
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
edgeTargetsEdgeSource - This method returns true if this outgoing edge should actually target another edge source, not a node.
template<typename EdgeIter >
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
getEdgeTarget - If edgeTargetsEdgeSource returns true, this method is called to determine which outgoing edge of Node is the target of this edge.
static bool hasEdgeDestLabels ()
hasEdgeDestLabels - If this function returns true, the graph is able to provide labels for edge destinations.
static unsigned numEdgeDestLabels (const void *)
numEdgeDestLabels - If hasEdgeDestLabels, this function returns the number of incoming edge labels the given node has.
static std::string getEdgeDestLabel (const void *, unsigned)
getEdgeDestLabel - If hasEdgeDestLabels, this function returns the incoming edge label with the given index in the given node.
template<typename GraphType , typename GraphWriter >
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
addCustomGraphFeatures - If a graph is made up of more than just straight-forward nodes and edges, this is the place to put all of the custom stuff necessary.
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
Definition at line 54 of file MachineCFGPrinter.h.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< DOTMachineFuncInfo * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 56 of file MachineCFGPrinter.h.
Member Function Documentation
eraseComment()
static void llvm::DOTGraphTraits< DOTMachineFuncInfo * >::eraseComment (std::string & OutStr, unsigned & I, unsigned Idx) inline static
Definition at line 58 of file MachineCFGPrinter.h.
References I.
getCompleteNodeLabel()
static std::string llvm::DOTGraphTraits< DOTMachineFuncInfo * >::getCompleteNodeLabel (const MachineBasicBlock * Node, DOTMachineFuncInfo * , function_ref< void(raw_string_ostream &, const MachineBasicBlock &)> HandleBasicBlock = [](raw_string_ostream &OS, const MachineBasicBlock &Node) -> void { OS << Node; }, function_ref< void(std::string &, unsigned &, unsigned)> HandleComment = eraseComment) inline static
Definition at line 68 of file MachineCFGPrinter.h.
References OS.
getGraphName()
static std::string llvm::DOTGraphTraits< DOTMachineFuncInfo * >::getGraphName (DOTMachineFuncInfo * CFGInfo) inline static
Definition at line 87 of file MachineCFGPrinter.h.
References llvm::DOTMachineFuncInfo::getFunction(), llvm::MachineFunction::getName(), and llvm::StringRef::str().
getNodeLabel()
std::string llvm::DOTGraphTraits< DOTMachineFuncInfo * >::getNodeLabel (const MachineBasicBlock * Node, DOTMachineFuncInfo * CFGInfo) inline
Definition at line 79 of file MachineCFGPrinter.h.
References isSimple().
getSimpleNodeLabel()
static std::string llvm::DOTGraphTraits< DOTMachineFuncInfo * >::getSimpleNodeLabel (const MachineBasicBlock * Node, DOTMachineFuncInfo *) inline static
Definition at line 63 of file MachineCFGPrinter.h.
References llvm::SimpleNodeLabelString().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/MachineCFGPrinter.h