LLVM: llvm::AttributorCGSCCPass Struct Reference
llvm::AttributorCGSCCPass Struct Reference
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
PreservedAnalyses run (LazyCallGraph::SCC &C, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Public Member Functions inherited from llvm::PassInfoMixin< AttributorCGSCCPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AttributorCGSCCPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 3221 of file Attributor.h.
Member Function Documentation
run()
PreservedAnalyses AttributorCGSCCPass::run (LazyCallGraph::SCC & C, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Definition at line 3657 of file Attributor.cpp.
References llvm::PreservedAnalyses::all(), Allocator, llvm::SetVector< T, Vector, Set >::back(), llvm::SetVector< T, Vector, Set >::empty(), FAM, llvm::GlobalValue::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::CallGraphUpdater::initialize(), llvm::SetVector< T, Vector, Set >::insert(), M, N, llvm::PreservedAnalyses::preserve(), and runAttributorOnFunctions().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/Attributor.cpp