LLVM: llvm::PatternMatch::VScaleVal_match Struct Reference
llvm::PatternMatch::VScaleVal_match Struct Reference
Matches patterns for vscale.
#include "llvm/IR/PatternMatch.h"
Public Member Functions
VScaleVal_match (const DataLayout &DL)
template<typename ITy >
bool match (ITy *V)
Public Attributes
const DataLayout & DL
Detailed Description
Matches patterns for vscale.
This can either be a call to llvm.vscale or the constant expression ptrtoint(gep <vscale x 1 x i8>, <vscale x 1 x i8>* null, i32 1> under the right conditions determined by DataLayout.
Definition at line 2478 of file PatternMatch.h.
Constructor & Destructor Documentation
VScaleVal_match()
llvm::PatternMatch::VScaleVal_match::VScaleVal_match (const DataLayout & DL) inline
Definition at line 2480 of file PatternMatch.h.
Member Function Documentation
match()
template<typename ITy > bool llvm::PatternMatch::VScaleVal_match::match (ITy * V) inline
Definition at line 2482 of file PatternMatch.h.
References DL, GEP, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::DataLayout::getTypeAllocSizeInBits(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), and Ptr.
Member Data Documentation
DL
const DataLayout& llvm::PatternMatch::VScaleVal_match::DL
Definition at line 2479 of file PatternMatch.h.
Referenced by match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h