LLVM: llvm::dxbc::PSV::v2::RuntimeInfo Struct Reference
llvm::dxbc::PSV::v2::RuntimeInfo Struct Reference
#include "llvm/BinaryFormat/DXContainer.h"
Public Member Functions
void swapBytes ()
void swapBytes (Triple::EnvironmentType Stage)
Public Member Functions inherited from llvm::dxbc::PSV::v1::RuntimeInfo
void swapBytes ()
void swapBytes (Triple::EnvironmentType Stage)
Public Member Functions inherited from llvm::dxbc::PSV::v0::RuntimeInfo
void swapBytes ()
void swapBytes (Triple::EnvironmentType Stage)
Public Attributes
uint32_t NumThreadsX
uint32_t NumThreadsY
uint32_t NumThreadsZ
Public Attributes inherited from llvm::dxbc::PSV::v1::RuntimeInfo
uint8_t ShaderStage
uint8_t UsesViewID
GeometryExtraInfo GeomData
uint8_t SigInputElements
uint8_t SigOutputElements
uint8_t SigPatchConstOrPrimElements
uint8_t SigInputVectors
uint8_t SigOutputVectors [4]
Public Attributes inherited from llvm::dxbc::PSV::v0::RuntimeInfo
PipelinePSVInfo StageInfo
uint32_t MinimumWaveLaneCount
uint32_t MaximumWaveLaneCount
Detailed Description
Definition at line 349 of file DXContainer.h.
Member Function Documentation
swapBytes() [1/2]
void llvm::dxbc::PSV::v2::RuntimeInfo::swapBytes () inline
Definition at line 354 of file DXContainer.h.
References NumThreadsX, NumThreadsY, NumThreadsZ, and llvm::sys::swapByteOrder().
Referenced by llvm::mcdxbc::PSVRuntimeInfo::swapBytes().
swapBytes() [2/2]
void llvm::dxbc::PSV::v2::RuntimeInfo::swapBytes (Triple::EnvironmentType Stage) inline
Definition at line 360 of file DXContainer.h.
References llvm::dxbc::PSV::v1::RuntimeInfo::swapBytes().
Member Data Documentation
NumThreadsX
uint32_t llvm::dxbc::PSV::v2::RuntimeInfo::NumThreadsX
Definition at line 350 of file DXContainer.h.
Referenced by swapBytes().
NumThreadsY
uint32_t llvm::dxbc::PSV::v2::RuntimeInfo::NumThreadsY
Definition at line 351 of file DXContainer.h.
Referenced by swapBytes().
NumThreadsZ
uint32_t llvm::dxbc::PSV::v2::RuntimeInfo::NumThreadsZ
Definition at line 352 of file DXContainer.h.
Referenced by swapBytes().
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/DXContainer.h