LLVM: llvm::SPIRV::RequirementHandler Struct Reference
llvm::SPIRV::RequirementHandler Struct Reference
#include "Target/SPIRV/SPIRVModuleAnalysis.h"
Public Member Functions
RequirementHandler ()
void clear ()
unsigned getMinVersion () const
unsigned getMaxVersion () const
const CapabilityList & getMinimalCapabilities () const
const SmallSet< Extension::Extension, 4 > & getExtensions () const
void addCapabilities (const CapabilityList &ToAdd)
void addCapability (Capability::Capability ToAdd)
void addExtensions (const ExtensionList &ToAdd)
void addExtension (Extension::Extension ToAdd)
void addRequirements (const Requirements &Req)
void getAndAddRequirements (SPIRV::OperandCategory::OperandCategory Category, uint32_t i, const SPIRVSubtarget &ST)
void checkSatisfiable (const SPIRVSubtarget &ST) const
void initAvailableCapabilities (const SPIRVSubtarget &ST)
void addAvailableCaps (const CapabilityList &ToAdd)
bool isCapabilityAvailable (Capability::Capability Cap) const
Detailed Description
Definition at line 60 of file SPIRVModuleAnalysis.h.
Constructor & Destructor Documentation
RequirementHandler()
llvm::SPIRV::RequirementHandler::RequirementHandler () inline
Definition at line 73 of file SPIRVModuleAnalysis.h.
Member Function Documentation
addAvailableCaps()
void llvm::SPIRV::RequirementHandler::addAvailableCaps (const CapabilityList & ToAdd)
addCapabilities()
void llvm::SPIRV::RequirementHandler::addCapabilities (const CapabilityList & ToAdd)
Referenced by addCapability().
addCapability()
void llvm::SPIRV::RequirementHandler::addCapability (Capability::Capability ToAdd) inline
Definition at line 92 of file SPIRVModuleAnalysis.h.
References addCapabilities().
Referenced by llvm::SPIRVModuleAnalysis::runOnModule().
addExtension()
void llvm::SPIRV::RequirementHandler::addExtension (Extension::Extension ToAdd) inline
Definition at line 96 of file SPIRVModuleAnalysis.h.
References llvm::SmallSet< T, N, C >::insert().
addExtensions()
void llvm::SPIRV::RequirementHandler::addExtensions (const ExtensionList & ToAdd) inline
Definition at line 93 of file SPIRVModuleAnalysis.h.
References llvm::SmallSet< T, N, C >::insert().
addRequirements()
void llvm::SPIRV::RequirementHandler::addRequirements (const Requirements & Req)
checkSatisfiable()
void llvm::SPIRV::RequirementHandler::checkSatisfiable (const SPIRVSubtarget & ST) const
clear()
void llvm::SPIRV::RequirementHandler::clear () inline
Definition at line 74 of file SPIRVModuleAnalysis.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::clear(), llvm::SmallSet< T, N, C >::clear(), and llvm::SmallVectorImpl< T >::clear().
getAndAddRequirements()
void llvm::SPIRV::RequirementHandler::getAndAddRequirements (SPIRV::OperandCategory::OperandCategory Category, uint32_t i, const SPIRVSubtarget & ST)
getExtensions()
const SmallSet<Extension::Extension, 4>& llvm::SPIRV::RequirementHandler::getExtensions () const inline
Definition at line 85 of file SPIRVModuleAnalysis.h.
getMaxVersion()
unsigned llvm::SPIRV::RequirementHandler::getMaxVersion () const inline
Definition at line 83 of file SPIRVModuleAnalysis.h.
getMinimalCapabilities()
const CapabilityList& llvm::SPIRV::RequirementHandler::getMinimalCapabilities () const inline
Definition at line 84 of file SPIRVModuleAnalysis.h.
getMinVersion()
unsigned llvm::SPIRV::RequirementHandler::getMinVersion () const inline
Definition at line 82 of file SPIRVModuleAnalysis.h.
initAvailableCapabilities()
void llvm::SPIRV::RequirementHandler::initAvailableCapabilities (const SPIRVSubtarget & ST)
isCapabilityAvailable()
bool llvm::SPIRV::RequirementHandler::isCapabilityAvailable (Capability::Capability Cap) const inline
Definition at line 110 of file SPIRVModuleAnalysis.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains().
The documentation for this struct was generated from the following file:
lib/Target/SPIRV/SPIRVModuleAnalysis.h