LLVM: llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable > Struct Template Reference
llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable > Struct Template Reference
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
BinaryOpc_match (unsigned Opcode, const LHS_P &LHS, const RHS_P &RHS)
template<typename OpTy >
bool match (const MachineRegisterInfo &MRI, OpTy &&Op)
Public Attributes
unsigned Opc
LHS_P L
RHS_P R
Detailed Description
template<typename LHS_P, typename RHS_P, bool Commutable = false>
struct llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >
Definition at line 414 of file MIPatternMatch.h.
Constructor & Destructor Documentation
BinaryOpc_match()
template<typename LHS_P , typename RHS_P , bool Commutable = false> llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::BinaryOpc_match (unsigned Opcode, const LHS_P & LHS, const RHS_P & RHS) inline
Definition at line 419 of file MIPatternMatch.h.
Member Function Documentation
match()
template<typename LHS_P , typename RHS_P , bool Commutable = false> template<typename OpTy > bool llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::match (const MachineRegisterInfo & MRI, OpTy && Op) inline
Definition at line 422 of file MIPatternMatch.h.
References llvm::MCID::Commutable, llvm::MachineInstr::getNumDefs(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::L, llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::mi_match(), MRI, llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::Opc, and llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::R.
Member Data Documentation
L
template<typename LHS_P , typename RHS_P , bool Commutable = false> LHS_P llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::L
Definition at line 416 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::match().
Opc
template<typename LHS_P , typename RHS_P , bool Commutable = false> unsigned llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::Opc
Definition at line 415 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::match().
R
template<typename LHS_P , typename RHS_P , bool Commutable = false> RHS_P llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::R
Definition at line 417 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable >::match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h