LLVM: llvm::GraphTraits< DOTFuncInfo * > Struct Reference
llvm::GraphTraits< DOTFuncInfo * > Struct Reference
#include "llvm/Analysis/CFGPrinter.h"
Public Types
using nodes_iterator = pointer_iterator< Function::const_iterator >
Public Types inherited from llvm::GraphTraits< const BasicBlock * >
using NodeRef = const BasicBlock *
using ChildIteratorType = const_succ_iterator
Static Public Member Functions
static NodeRef getEntryNode (DOTFuncInfo *CFGInfo)
static nodes_iterator nodes_begin (DOTFuncInfo *CFGInfo)
static nodes_iterator nodes_end (DOTFuncInfo *CFGInfo)
static size_t size (DOTFuncInfo *CFGInfo)
Static Public Member Functions inherited from llvm::GraphTraits< const BasicBlock * >
static NodeRef getEntryNode (const BasicBlock *BB)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
Definition at line 102 of file CFGPrinter.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< DOTFuncInfo * >::nodes_iterator = pointer_iterator<Function::const_iterator>
Definition at line 108 of file CFGPrinter.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< DOTFuncInfo * >::getEntryNode (DOTFuncInfo * CFGInfo) inline static
Definition at line 103 of file CFGPrinter.h.
References llvm::Function::getEntryBlock(), and llvm::DOTFuncInfo::getFunction().
nodes_begin()
static nodes_iterator llvm::GraphTraits< DOTFuncInfo * >::nodes_begin (DOTFuncInfo * CFGInfo) inline static
Definition at line 110 of file CFGPrinter.h.
References llvm::Function::begin(), and llvm::DOTFuncInfo::getFunction().
nodes_end()
static nodes_iterator llvm::GraphTraits< DOTFuncInfo * >::nodes_end (DOTFuncInfo * CFGInfo) inline static
Definition at line 114 of file CFGPrinter.h.
References llvm::Function::end(), and llvm::DOTFuncInfo::getFunction().
size()
static size_t llvm::GraphTraits< DOTFuncInfo * >::size (DOTFuncInfo * CFGInfo) inline static
Definition at line 118 of file CFGPrinter.h.
References llvm::DOTFuncInfo::getFunction(), and llvm::Function::size().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/CFGPrinter.h