LLVM: llvm::memprof::Frame Struct Reference
llvm::memprof::Frame Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
Frame (const Frame &Other)
Frame (uint64_t Hash, uint32_t Off, uint32_t Col, bool Inline)
bool operator== (const Frame &Other) const
Frame & operator= (const Frame &Other)
bool operator!= (const Frame &Other) const
void serialize (raw_ostream &OS) const
void printYAML (raw_ostream &OS) const
FrameId hash () const
Static Public Member Functions
static Frame deserialize (const unsigned char *Ptr)
static constexpr size_t serializedSize ()
Public Attributes
GlobalValue::GUID Function
std::optional< std::string > SymbolName
uint32_t LineOffset
uint32_t Column
bool IsInlineFrame
Detailed Description
Definition at line 142 of file MemProf.h.
Constructor & Destructor Documentation
Frame() [1/2]
llvm::memprof::Frame::Frame (const Frame & Other) inline
Definition at line 157 of file MemProf.h.
References Other, and llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
Frame() [2/2]
llvm::memprof::Frame::Frame (uint64_t Hash, uint32_t Off, uint32_t Col, bool Inline) inline
Definition at line 165 of file MemProf.h.
Member Function Documentation
deserialize()
static Frame llvm::memprof::Frame::deserialize (const unsigned char * Ptr) inline static
Definition at line 204 of file MemProf.h.
References F, I, Ptr, support(), and uint64_t.
Referenced by llvm::memprof::FrameLookupTrait::ReadData().
hash()
FrameId llvm::memprof::Frame::hash () const inline
Definition at line 234 of file MemProf.h.
References Seed.
operator!=()
bool llvm::memprof::Frame::operator!= (const Frame & Other) const inline
Definition at line 184 of file MemProf.h.
References llvm::memprof::PortableMemInfoBlock::operator==(), and Other.
operator=()
Frame& llvm::memprof::Frame::operator= (const Frame & Other) inline
Definition at line 175 of file MemProf.h.
References Other, and llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
operator==()
bool llvm::memprof::Frame::operator== (const Frame & Other) const inline
Definition at line 168 of file MemProf.h.
References Other.
printYAML()
void llvm::memprof::Frame::printYAML (raw_ostream & OS) const inline
Definition at line 222 of file MemProf.h.
References OS, and llvm::AMDGPU::HSAMD::Kernel::Key::SymbolName.
serialize()
void llvm::memprof::Frame::serialize (raw_ostream & OS) const inline
Definition at line 187 of file MemProf.h.
References llvm::AArch64CC::LE, llvm::support::little, OS, support(), and uint64_t.
Referenced by llvm::memprof::FrameWriterTrait::EmitData().
serializedSize()
static constexpr size_t llvm::memprof::Frame::serializedSize () inline static constexpr
Definition at line 216 of file MemProf.h.
References Column, Function, IsInlineFrame, and LineOffset.
Referenced by llvm::memprof::FrameWriterTrait::EmitKeyDataLength().
Member Data Documentation
Column
uint32_t llvm::memprof::Frame::Column
Definition at line 153 of file MemProf.h.
Referenced by computeStackId(), and serializedSize().
Function
GlobalValue::GUID llvm::memprof::Frame::Function
Definition at line 145 of file MemProf.h.
Referenced by computeStackId(), and serializedSize().
IsInlineFrame
bool llvm::memprof::Frame::IsInlineFrame
Definition at line 155 of file MemProf.h.
Referenced by serializedSize().
LineOffset
uint32_t llvm::memprof::Frame::LineOffset
Definition at line 150 of file MemProf.h.
Referenced by computeStackId(), and serializedSize().
SymbolName
std::optional<std::string> llvm::memprof::Frame::SymbolName
Definition at line 148 of file MemProf.h.
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h