LLVM: llvm::AMDGPU::CustomOperandVal Struct Reference
llvm::AMDGPU::CustomOperandVal Struct Reference
#include "Target/AMDGPU/Utils/AMDGPUAsmUtils.h"
Public Member Functions
unsigned decode (unsigned Code) const
unsigned encode (unsigned Val) const
unsigned getMask () const
bool isValid (unsigned Val) const
bool isSupported (const MCSubtargetInfo &STI) const
Public Attributes
StringLiteral Name
unsigned Max
unsigned Default
unsigned Shift
unsigned Width
bool(* Cond)(const MCSubtargetInfo &STI) = nullptr
unsigned Mask = (1 << Width) - 1
Detailed Description
Definition at line 34 of file AMDGPUAsmUtils.h.
Member Function Documentation
decode()
unsigned llvm::AMDGPU::CustomOperandVal::decode (unsigned Code) const inline
Definition at line 43 of file AMDGPUAsmUtils.h.
References Mask, and Shift.
encode()
unsigned llvm::AMDGPU::CustomOperandVal::encode (unsigned Val) const inline
Definition at line 45 of file AMDGPUAsmUtils.h.
References Mask, and Shift.
getMask()
unsigned llvm::AMDGPU::CustomOperandVal::getMask () const inline
Definition at line 47 of file AMDGPUAsmUtils.h.
References Mask, and Shift.
isSupported()
bool llvm::AMDGPU::CustomOperandVal::isSupported (const MCSubtargetInfo & STI) const inline
Definition at line 51 of file AMDGPUAsmUtils.h.
References Cond.
isValid()
bool llvm::AMDGPU::CustomOperandVal::isValid (unsigned Val) const inline
Definition at line 49 of file AMDGPUAsmUtils.h.
References Max.
Member Data Documentation
Cond
bool(* llvm::AMDGPU::CustomOperandVal::Cond) (const MCSubtargetInfo &STI) = nullptr
Definition at line 40 of file AMDGPUAsmUtils.h.
Referenced by isSupported().
Default
unsigned llvm::AMDGPU::CustomOperandVal::Default
Definition at line 37 of file AMDGPUAsmUtils.h.
Mask
unsigned llvm::AMDGPU::CustomOperandVal::Mask = (1 << Width) - 1
Definition at line 41 of file AMDGPUAsmUtils.h.
Referenced by decode(), encode(), and getMask().
Max
unsigned llvm::AMDGPU::CustomOperandVal::Max
Definition at line 36 of file AMDGPUAsmUtils.h.
Referenced by isValid().
Name
StringLiteral llvm::AMDGPU::CustomOperandVal::Name
Definition at line 35 of file AMDGPUAsmUtils.h.
Shift
unsigned llvm::AMDGPU::CustomOperandVal::Shift
Definition at line 38 of file AMDGPUAsmUtils.h.
Referenced by decode(), encode(), and getMask().
Width
unsigned llvm::AMDGPU::CustomOperandVal::Width
Definition at line 39 of file AMDGPUAsmUtils.h.
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/Utils/AMDGPUAsmUtils.h