LLVM: llvm::dxbc::PSV::v0::RuntimeInfo Struct Reference
llvm::dxbc::PSV::v0::RuntimeInfo Struct Reference
#include "llvm/BinaryFormat/DXContainer.h"
Public Member Functions
void swapBytes ()
void swapBytes (Triple::EnvironmentType Stage)
Public Attributes
PipelinePSVInfo StageInfo
uint32_t MinimumWaveLaneCount
uint32_t MaximumWaveLaneCount
Detailed Description
Definition at line 277 of file DXContainer.h.
Member Function Documentation
swapBytes() [1/2]
void llvm::dxbc::PSV::v0::RuntimeInfo::swapBytes () inline
Definition at line 282 of file DXContainer.h.
References MaximumWaveLaneCount, MinimumWaveLaneCount, and llvm::sys::swapByteOrder().
Referenced by llvm::dxbc::PSV::v1::RuntimeInfo::swapBytes().
swapBytes() [2/2]
void llvm::dxbc::PSV::v0::RuntimeInfo::swapBytes (Triple::EnvironmentType Stage) inline
Definition at line 288 of file DXContainer.h.
References StageInfo, and llvm::dxbc::PipelinePSVInfo::swapBytes().
Member Data Documentation
MaximumWaveLaneCount
uint32_t llvm::dxbc::PSV::v0::RuntimeInfo::MaximumWaveLaneCount
Definition at line 280 of file DXContainer.h.
Referenced by swapBytes().
MinimumWaveLaneCount
uint32_t llvm::dxbc::PSV::v0::RuntimeInfo::MinimumWaveLaneCount
Definition at line 279 of file DXContainer.h.
Referenced by swapBytes().
StageInfo
PipelinePSVInfo llvm::dxbc::PSV::v0::RuntimeInfo::StageInfo
Definition at line 278 of file DXContainer.h.
Referenced by swapBytes().
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/DXContainer.h