LLVM: llvm::VectorizationFactor Struct Reference
llvm::VectorizationFactor Struct Reference
TODO: The following VectorizationFactor was pulled out of LoopVectorizationCostModel class.
#include "Transforms/Vectorize/LoopVectorizationPlanner.h"
Public Member Functions
VectorizationFactor (ElementCount Width, InstructionCost Cost, InstructionCost ScalarCost)
bool operator== (const VectorizationFactor &rhs) const
bool operator!= (const VectorizationFactor &rhs) const
Static Public Member Functions
static VectorizationFactor Disabled ()
Width 1 means no vectorization, cost 0 means uncomputed cost.
Public Attributes
ElementCount Width
Vector width with best cost.
InstructionCost Cost
Cost of the loop with that width.
InstructionCost ScalarCost
Cost of the scalar loop.
ElementCount MinProfitableTripCount
The minimum trip count required to make vectorization profitable, e.g.
Detailed Description
TODO: The following VectorizationFactor was pulled out of LoopVectorizationCostModel class.
LV also deals with VectorizerParams::VectorizationFactor and VectorizationCostTy. We need to streamline them. Information about vectorization costs.
Definition at line 188 of file LoopVectorizationPlanner.h.
Constructor & Destructor Documentation
VectorizationFactor()
llvm::VectorizationFactor::VectorizationFactor (ElementCount Width, InstructionCost Cost, InstructionCost ScalarCost) inline
Definition at line 202 of file LoopVectorizationPlanner.h.
Member Function Documentation
Disabled()
static VectorizationFactor llvm::VectorizationFactor::Disabled () inline static
Width 1 means no vectorization, cost 0 means uncomputed cost.
Definition at line 207 of file LoopVectorizationPlanner.h.
References llvm::ElementCount::getFixed().
Referenced by llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), and llvm::LoopVectorizationCostModel::selectEpilogueVectorizationFactor().
operator!=()
bool llvm::VectorizationFactor::operator!= (const VectorizationFactor & rhs) const inline
Definition at line 215 of file LoopVectorizationPlanner.h.
operator==()
bool llvm::VectorizationFactor::operator== (const VectorizationFactor & rhs) const inline
Definition at line 211 of file LoopVectorizationPlanner.h.
References Cost, and Width.
Member Data Documentation
Cost
InstructionCost llvm::VectorizationFactor::Cost
Cost of the loop with that width.
Definition at line 193 of file LoopVectorizationPlanner.h.
Referenced by operator==(), llvm::LoopVectorizePass::processLoop(), and llvm::LoopVectorizationCostModel::selectVectorizationFactor().
MinProfitableTripCount
ElementCount llvm::VectorizationFactor::MinProfitableTripCount
The minimum trip count required to make vectorization profitable, e.g.
due to runtime checks.
Definition at line 200 of file LoopVectorizationPlanner.h.
Referenced by llvm::LoopVectorizePass::processLoop().
ScalarCost
InstructionCost llvm::VectorizationFactor::ScalarCost
Cost of the scalar loop.
Definition at line 196 of file LoopVectorizationPlanner.h.
Referenced by llvm::LoopVectorizationCostModel::selectVectorizationFactor().
Width
ElementCount llvm::VectorizationFactor::Width
Vector width with best cost.
Definition at line 190 of file LoopVectorizationPlanner.h.
Referenced by operator==(), llvm::LoopVectorizePass::processLoop(), and llvm::LoopVectorizationCostModel::selectVectorizationFactor().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/LoopVectorizationPlanner.h