LLVM: llvm::ValueInfo Struct Reference
llvm::ValueInfo Struct Reference
Struct that holds a reference to a particular GUID in a global value summary.
#include "llvm/IR/ModuleSummaryIndex.h"
Public Types
enum Flags { HaveGV = 1, ReadOnly = 2, WriteOnly = 4 }
Public Member Functions
ValueInfo ()=default
ValueInfo (bool HaveGVs, const GlobalValueSummaryMapTy::value_type *R)
operator bool () const
GlobalValue::GUID getGUID () const
const GlobalValue * getValue () const
ArrayRef< std::unique_ptr< GlobalValueSummary > > getSummaryList () const
StringRef name () const
bool haveGVs () const
bool isReadOnly () const
bool isWriteOnly () const
unsigned getAccessSpecifier () const
bool isValidAccessSpecifier () const
void setReadOnly ()
void setWriteOnly ()
const GlobalValueSummaryMapTy::value_type * getRef () const
GlobalValue::VisibilityTypes getELFVisibility () const
Returns the most constraining visibility among summaries.
bool isDSOLocal (bool WithDSOLocalPropagation=false) const
Checks if all summaries are DSO local (have the flag set).
bool canAutoHide () const
Checks if all copies are eligible for auto-hiding (have flag set).
Public Attributes
PointerIntPair< const GlobalValueSummaryMapTy::value_type *, 3, int > RefAndFlags
Detailed Description
Struct that holds a reference to a particular GUID in a global value summary.
Definition at line 169 of file ModuleSummaryIndex.h.
Member Enumeration Documentation
Flags
enum llvm::ValueInfo::Flags
Enumerator
HaveGV
ReadOnly
WriteOnly
Definition at line 170 of file ModuleSummaryIndex.h.
Constructor & Destructor Documentation
ValueInfo() [1/2]
llvm::ValueInfo::ValueInfo () default
ValueInfo() [2/2]
llvm::ValueInfo::ValueInfo (bool HaveGVs, const GlobalValueSummaryMapTy::value_type * R) inline
Definition at line 175 of file ModuleSummaryIndex.h.
References RefAndFlags, llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setInt(), and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setPointer().
Member Function Documentation
canAutoHide()
bool ValueInfo::canAutoHide () const
Checks if all copies are eligible for auto-hiding (have flag set).
Definition at line 67 of file ModuleSummaryIndex.cpp.
References llvm::all_of(), and getSummaryList().
getAccessSpecifier()
unsigned llvm::ValueInfo::getAccessSpecifier () const inline
Definition at line 206 of file ModuleSummaryIndex.h.
References assert(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), isValidAccessSpecifier(), ReadOnly, RefAndFlags, and WriteOnly.
Referenced by setReadOnly(), and setWriteOnly().
getELFVisibility()
GlobalValue::VisibilityTypes ValueInfo::getELFVisibility () const
Returns the most constraining visibility among summaries.
The visibilities, ordered from least to most constraining, are: default, protected and hidden.
Definition at line 42 of file ModuleSummaryIndex.cpp.
References llvm::GlobalValue::DefaultVisibility, getSummaryList(), llvm::GlobalValue::HiddenVisibility, llvm::make_pointee_range(), llvm::GlobalValue::ProtectedVisibility, and S.
getGUID()
GlobalValue::GUID llvm::ValueInfo::getGUID () const inline
Definition at line 182 of file ModuleSummaryIndex.h.
References getRef().
Referenced by llvm::AliasSummary::getAliaseeGUID().
getRef()
const GlobalValueSummaryMapTy::value_type* llvm::ValueInfo::getRef () const inline
Definition at line 225 of file ModuleSummaryIndex.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer(), and RefAndFlags.
Referenced by getGUID(), getSummaryList(), getValue(), llvm::DenseMapInfo< ValueInfo >::isEqual(), name(), and operator bool().
getSummaryList()
ArrayRef<std::unique_ptr<GlobalValueSummary> > llvm::ValueInfo::getSummaryList () const inline
Definition at line 188 of file ModuleSummaryIndex.h.
References getRef().
Referenced by canAutoHide(), llvm::computeSyntheticCounts(), llvm::ModuleSummaryIndex::discoverNodes(), getELFVisibility(), llvm::AliasSummary::hasAliasee(), and isDSOLocal().
getValue()
const GlobalValue* llvm::ValueInfo::getValue () const inline
Definition at line 183 of file ModuleSummaryIndex.h.
References assert(), getRef(), and haveGVs().
haveGVs()
bool llvm::ValueInfo::haveGVs () const inline
Definition at line 197 of file ModuleSummaryIndex.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), HaveGV, and RefAndFlags.
Referenced by getValue(), llvm::DenseMapInfo< ValueInfo >::isEqual(), and name().
isDSOLocal()
bool ValueInfo::isDSOLocal (bool WithDSOLocalPropagation = false) const
Checks if all summaries are DSO local (have the flag set).
When DSOLocal propagation has been done, set the parameter to enable fast check.
Definition at line 54 of file ModuleSummaryIndex.cpp.
References llvm::all_of(), and getSummaryList().
isReadOnly()
bool llvm::ValueInfo::isReadOnly () const inline
Definition at line 198 of file ModuleSummaryIndex.h.
References assert(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), isValidAccessSpecifier(), ReadOnly, and RefAndFlags.
Referenced by resolveFwdRef().
isValidAccessSpecifier()
bool llvm::ValueInfo::isValidAccessSpecifier () const inline
Definition at line 210 of file ModuleSummaryIndex.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), ReadOnly, RefAndFlags, and WriteOnly.
Referenced by getAccessSpecifier(), isReadOnly(), and isWriteOnly().
isWriteOnly()
bool llvm::ValueInfo::isWriteOnly () const inline
Definition at line 202 of file ModuleSummaryIndex.h.
References assert(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), isValidAccessSpecifier(), RefAndFlags, and WriteOnly.
Referenced by resolveFwdRef().
name()
StringRef llvm::ValueInfo::name () const inline
Definition at line 192 of file ModuleSummaryIndex.h.
References getRef(), and haveGVs().
operator bool()
llvm::ValueInfo::operator bool () const inline explicit
Definition at line 180 of file ModuleSummaryIndex.h.
References getRef().
setReadOnly()
void llvm::ValueInfo::setReadOnly () inline
Definition at line 214 of file ModuleSummaryIndex.h.
References assert(), getAccessSpecifier(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), ReadOnly, RefAndFlags, and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setInt().
Referenced by resolveFwdRef().
setWriteOnly()
void llvm::ValueInfo::setWriteOnly () inline
Definition at line 220 of file ModuleSummaryIndex.h.
References assert(), getAccessSpecifier(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getInt(), RefAndFlags, llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::setInt(), and WriteOnly.
Referenced by resolveFwdRef().
Member Data Documentation
RefAndFlags
PointerIntPair<const GlobalValueSummaryMapTy::value_type *, 3, int> llvm::ValueInfo::RefAndFlags
Definition at line 172 of file ModuleSummaryIndex.h.
Referenced by getAccessSpecifier(), getRef(), haveGVs(), isReadOnly(), isValidAccessSpecifier(), isWriteOnly(), setReadOnly(), setWriteOnly(), and ValueInfo().
The documentation for this struct was generated from the following files:
include/llvm/IR/ModuleSummaryIndex.h
lib/IR/ModuleSummaryIndex.cpp