LLVM: llvm::InstrProfRecord Struct Reference
llvm::InstrProfRecord Struct Reference
Profiling information for a single function.
#include "llvm/ProfileData/InstrProf.h"
Public Types
enum CountPseudoKind { NotPseudo = 0, PseudoHot, PseudoWarm }
enum PseudoCountVal { HotFunctionVal = -1, WarmFunctionVal = -2 }
Public Member Functions
InstrProfRecord ()=default
InstrProfRecord (std::vector< uint64_t > Counts)
InstrProfRecord (InstrProfRecord &&)=default
InstrProfRecord (const InstrProfRecord &RHS)
InstrProfRecord & operator= (InstrProfRecord &&)=default
InstrProfRecord & operator= (const InstrProfRecord &RHS)
uint32_t getNumValueKinds () const
Return the number of value profile kinds with non-zero number of profile sites.
uint32_t getNumValueSites (uint32_t ValueKind) const
Return the number of instrumented sites for ValueKind.
uint32_t getNumValueData (uint32_t ValueKind) const
Return the total number of ValueData for ValueKind.
uint32_t getNumValueDataForSite (uint32_t ValueKind, uint32_t Site) const
Return the number of value data collected for ValueKind at profiling site: Site.
std::unique_ptr< InstrProfValueData[]> getValueForSite (uint32_t ValueKind, uint32_t Site, uint64_t *TotalC=nullptr) const
Return the array of profiled values at Site.
uint64_t getValueForSite (InstrProfValueData Dest[], uint32_t ValueKind, uint32_t Site) const
Get the target value/counts of kind ValueKind collected at site Site and store the result in array Dest.
void reserveSites (uint32_t ValueKind, uint32_t NumValueSites)
Reserve space for NumValueSites sites.
void addValueData (uint32_t ValueKind, uint32_t Site, InstrProfValueData *VData, uint32_t N, InstrProfSymtab *SymTab)
Add ValueData for ValueKind at value Site.
void merge (InstrProfRecord &Other, uint64_t Weight, function_ref< void(instrprof_error)> Warn)
Merge the counts in Other into this one.
void scale (uint64_t N, uint64_t D, function_ref< void(instrprof_error)> Warn)
Scale up profile counts (including value profile data) by a factor of (N / D).
void sortValueData ()
Sort value profile data (per site) by count.
void Clear ()
Clear value data entries and edge counters.
void clearValueData ()
Clear value data entries.
void accumulateCounts (CountSumOrPercent &Sum) const
Compute the sums of all counts and store in Sum.
void overlap (InstrProfRecord &Other, OverlapStats &Overlap, OverlapStats &FuncLevelOverlap, uint64_t ValueCutoff)
Compute the overlap b/w this IntrprofRecord and Other.
void overlapValueProfData (uint32_t ValueKind, InstrProfRecord &Src, OverlapStats &Overlap, OverlapStats &FuncLevelOverlap)
Compute the overlap of value profile counts.
CountPseudoKind getCountPseudoKind () const
void setPseudoCount (CountPseudoKind Kind)
Public Attributes
std::vector< uint64_t > Counts
Detailed Description
Profiling information for a single function.
Definition at line 730 of file InstrProf.h.
Member Enumeration Documentation
CountPseudoKind
enum llvm::InstrProfRecord::CountPseudoKind
Enumerator
NotPseudo
PseudoHot
PseudoWarm
Definition at line 827 of file InstrProf.h.
PseudoCountVal
enum llvm::InstrProfRecord::PseudoCountVal
Enumerator
HotFunctionVal
WarmFunctionVal
Definition at line 832 of file InstrProf.h.
Constructor & Destructor Documentation
InstrProfRecord() [1/4]
llvm::InstrProfRecord::InstrProfRecord () default
InstrProfRecord() [2/4]
llvm::InstrProfRecord::InstrProfRecord (std::vector< uint64_t > Counts) inline
Definition at line 734 of file InstrProf.h.
InstrProfRecord() [3/4]
llvm::InstrProfRecord::InstrProfRecord (InstrProfRecord &&) default
InstrProfRecord() [4/4]
llvm::InstrProfRecord::InstrProfRecord (const InstrProfRecord & RHS) inline
Definition at line 736 of file InstrProf.h.
Member Function Documentation
accumulateCounts()
void llvm::InstrProfRecord::accumulateCounts (CountSumOrPercent & Sum) const
Compute the sums of all counts and store in Sum.
Definition at line 536 of file InstrProf.cpp.
References Counts, llvm::CountSumOrPercent::CountSum, getNumValueDataForSite(), getNumValueSites(), getValueForSite(), I, llvm::CountSumOrPercent::NumEntries, uint64_t, and llvm::CountSumOrPercent::ValueCounts.
Referenced by overlap().
addValueData()
void llvm::InstrProfRecord::addValueData (uint32_t ValueKind, uint32_t Site, InstrProfValueData * VData, uint32_t N, InstrProfSymtab * SymTab)
Add ValueData for ValueKind at value Site.
Definition at line 789 of file InstrProf.cpp.
References I, and N.
Clear()
void llvm::InstrProfRecord::Clear () inline
Clear value data entries and edge counters.
Definition at line 807 of file InstrProf.h.
References clearValueData(), and Counts.
clearValueData()
void llvm::InstrProfRecord::clearValueData () inline
Clear value data entries.
Definition at line 813 of file InstrProf.h.
Referenced by Clear().
getCountPseudoKind()
CountPseudoKind llvm::InstrProfRecord::getCountPseudoKind () const inline
Definition at line 836 of file InstrProf.h.
References Counts, HotFunctionVal, NotPseudo, PseudoHot, PseudoWarm, uint64_t, and WarmFunctionVal.
Referenced by merge().
getNumValueData()
uint32_t llvm::InstrProfRecord::getNumValueData (uint32_t ValueKind) const inline
Return the total number of ValueData for ValueKind.
Definition at line 938 of file InstrProf.h.
References N.
getNumValueDataForSite()
uint32_t llvm::InstrProfRecord::getNumValueDataForSite (uint32_t ValueKind, uint32_t Site) const inline
Return the number of value data collected for ValueKind at profiling site: Site.
Definition at line 949 of file InstrProf.h.
Referenced by accumulateCounts(), llvm::annotateValueSite(), and getValueForSite().
getNumValueKinds()
uint32_t llvm::InstrProfRecord::getNumValueKinds () const inline
Return the number of value profile kinds with non-zero number of profile sites.
Definition at line 931 of file InstrProf.h.
getNumValueSites()
uint32_t llvm::InstrProfRecord::getNumValueSites (uint32_t ValueKind) const inline
Return the number of instrumented sites for ValueKind.
Definition at line 945 of file InstrProf.h.
Referenced by accumulateCounts(), overlap(), and overlapValueProfData().
getValueForSite() [1/2]
uint64_t llvm::InstrProfRecord::getValueForSite (InstrProfValueData Dest[], uint32_t ValueKind, uint32_t Site) const inline
Get the target value/counts of kind ValueKind collected at site Site and store the result in array Dest.
Return the total counts of all target values at this site.
Definition at line 971 of file InstrProf.h.
References I, llvm::SaturatingAdd(), and uint64_t.
getValueForSite() [2/2]
std::unique_ptr< InstrProfValueData[]> llvm::InstrProfRecord::getValueForSite (uint32_t ValueKind, uint32_t Site, uint64_t * TotalC = nullptr) const inline
Return the array of profiled values at Site.
If TotalC is not null, the total count of all target values at this site will be stored in *TotalC.
Definition at line 955 of file InstrProf.h.
References llvm::NVPTXISD::Dummy, getNumValueDataForSite(), N, and uint64_t.
Referenced by accumulateCounts(), and llvm::annotateValueSite().
merge()
void llvm::InstrProfRecord::merge (InstrProfRecord & Other, uint64_t Weight, function_ref< void(instrprof_error)> Warn)
Merge the counts in Other into this one.
Optionally scale merged counts by Weight.
Definition at line 709 of file InstrProf.cpp.
References llvm::count_mismatch, llvm::counter_overflow, Counts, E, getCountPseudoKind(), llvm::getInstrMaxCountValue(), I, NotPseudo, Other, PseudoHot, PseudoWarm, llvm::SaturatingMultiplyAdd(), setPseudoCount(), and uint64_t.
operator=() [1/2]
InstrProfRecord& llvm::InstrProfRecord::operator= (const InstrProfRecord & RHS) inline
Definition at line 742 of file InstrProf.h.
References Counts, and RHS.
operator=() [2/2]
InstrProfRecord& llvm::InstrProfRecord::operator= (InstrProfRecord &&) default
overlap()
void llvm::InstrProfRecord::overlap (InstrProfRecord & Other, OverlapStats & Overlap, OverlapStats & FuncLevelOverlap, uint64_t ValueCutoff)
Compute the overlap b/w this IntrprofRecord and Other.
Definition at line 605 of file InstrProf.cpp.
References accumulateCounts(), llvm::OverlapStats::addOneMismatch(), assert(), llvm::OverlapStats::Base, Counts, llvm::CountSumOrPercent::CountSum, E, getNumValueSites(), I, llvm::max(), llvm::CountSumOrPercent::NumEntries, Other, llvm::OverlapStats::Overlap, overlapValueProfData(), llvm::OverlapStats::score(), llvm::OverlapStats::Test, uint64_t, and llvm::OverlapStats::Valid.
Referenced by llvm::InstrProfWriter::overlapRecord(), and overlapValueProfData().
overlapValueProfData()
void llvm::InstrProfRecord::overlapValueProfData (uint32_t ValueKind, InstrProfRecord & Src, OverlapStats & Overlap, OverlapStats & FuncLevelOverlap)
Compute the overlap of value profile counts.
Definition at line 587 of file InstrProf.cpp.
References assert(), getNumValueSites(), I, Other, and overlap().
Referenced by overlap().
reserveSites()
void llvm::InstrProfRecord::reserveSites (uint32_t ValueKind, uint32_t NumValueSites) inline
Reserve space for NumValueSites sites.
Definition at line 985 of file InstrProf.h.
scale()
void llvm::InstrProfRecord::scale (uint64_t N, uint64_t D, function_ref< void(instrprof_error)> Warn)
Scale up profile counts (including value profile data) by a factor of (N / D).
Definition at line 760 of file InstrProf.cpp.
References assert(), llvm::counter_overflow, Counts, D, llvm::getInstrMaxCountValue(), N, and llvm::SaturatingMultiply().
setPseudoCount()
void llvm::InstrProfRecord::setPseudoCount (CountPseudoKind Kind) inline
Definition at line 844 of file InstrProf.h.
References Counts, HotFunctionVal, PseudoHot, PseudoWarm, uint64_t, and WarmFunctionVal.
Referenced by merge().
sortValueData()
void llvm::InstrProfRecord::sortValueData () inline
Sort value profile data (per site) by count.
Definition at line 800 of file InstrProf.h.
Member Data Documentation
Counts
std::vector<uint64_t> llvm::InstrProfRecord::Counts
Definition at line 731 of file InstrProf.h.
Referenced by accumulateCounts(), Clear(), llvm::InstrProfRecordWriterTrait::EmitData(), llvm::InstrProfRecordWriterTrait::EmitKeyDataLength(), getCountPseudoKind(), merge(), operator=(), overlap(), scale(), and setPseudoCount().
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/InstrProf.h
lib/ProfileData/InstrProf.cpp