LLVM: llvm::InlineCostAnnotationPrinterPass Struct Reference
llvm::InlineCostAnnotationPrinterPass Struct Reference
#include "llvm/Analysis/InlineCost.h"
Public Member Functions
InlineCostAnnotationPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Public Member Functions inherited from llvm::PassInfoMixin< InlineCostAnnotationPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Attributes
raw_ostream & OS
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< InlineCostAnnotationPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 338 of file InlineCost.h.
Constructor & Destructor Documentation
InlineCostAnnotationPrinterPass()
llvm::InlineCostAnnotationPrinterPass::InlineCostAnnotationPrinterPass (raw_ostream & OS) inline explicit
Definition at line 343 of file InlineCost.h.
Member Function Documentation
run()
PreservedAnalyses InlineCostAnnotationPrinterPass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 3146 of file InlineCost.cpp.
References llvm::PreservedAnalyses::all(), BB, DL, F, FAM, function, llvm::getInlineParams(), llvm::Value::getName(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), I, llvm::GlobalValue::isDeclaration(), M, OS, and PrintInstructionComments.
Member Data Documentation
OS
raw_ostream& llvm::InlineCostAnnotationPrinterPass::OS
Definition at line 340 of file InlineCost.h.
Referenced by run().
The documentation for this struct was generated from the following files:
include/llvm/Analysis/InlineCost.h
lib/Analysis/InlineCost.cpp