LLVM: llvm::LowerConstantIntrinsicsPass Struct Reference
llvm::LowerConstantIntrinsicsPass Struct Reference
#include "llvm/Transforms/Scalar/LowerConstantIntrinsics.h"
Public Member Functions
LowerConstantIntrinsicsPass ()=default
PreservedAnalyses run (Function &F, FunctionAnalysisManager &)
Run the pass over the function.
Public Member Functions inherited from llvm::PassInfoMixin< LowerConstantIntrinsicsPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LowerConstantIntrinsicsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 24 of file LowerConstantIntrinsics.h.
Constructor & Destructor Documentation
LowerConstantIntrinsicsPass()
llvm::LowerConstantIntrinsicsPass::LowerConstantIntrinsicsPass () explicit default
Member Function Documentation
run()
PreservedAnalyses LowerConstantIntrinsicsPass::run (Function & F, FunctionAnalysisManager & AM)
Run the pass over the function.
This will lower all remaining 'objectsize' and 'is.constant'` intrinsic calls in this function, even when the argument has no known size or is not a constant respectively. The resulting constant is propagated and conditional branches are resolved where possible. This complements the Instruction Simplification and Instruction Combination passes of the optimized pass chain.
Definition at line 155 of file LowerConstantIntrinsics.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), lowerConstantIntrinsics(), and llvm::PreservedAnalyses::preserve().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Scalar/LowerConstantIntrinsics.h
lib/Transforms/Scalar/LowerConstantIntrinsics.cpp