LLVM: llvm::GraphTraits< ProfiledCallGraph * > Struct Reference
llvm::GraphTraits< ProfiledCallGraph * > Struct Reference
#include "llvm/Transforms/IPO/ProfiledCallGraph.h"
Static Public Member Functions
static NodeRef getEntryNode (ProfiledCallGraph *PCG)
static ChildIteratorType nodes_begin (ProfiledCallGraph *PCG)
static ChildIteratorType nodes_end (ProfiledCallGraph *PCG)
Static Public Member Functions inherited from llvm::GraphTraits< ProfiledCallGraphNode * >
static NodeRef getEntryNode (NodeRef PCGN)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Additional Inherited Members
Public Types inherited from llvm::GraphTraits< ProfiledCallGraphNode * >
using NodeType = ProfiledCallGraphNode
using NodeRef = ProfiledCallGraphNode *
using EdgeType = NodeType::edge
using ChildIteratorType = NodeType::const_iterator
Detailed Description
Definition at line 196 of file ProfiledCallGraph.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< ProfiledCallGraph * >::getEntryNode (ProfiledCallGraph * PCG) inline static
Definition at line 198 of file ProfiledCallGraph.h.
References llvm::sampleprof::ProfiledCallGraph::getEntryNode().
nodes_begin()
static ChildIteratorType llvm::GraphTraits< ProfiledCallGraph * >::nodes_begin (ProfiledCallGraph * PCG) inline static
Definition at line 202 of file ProfiledCallGraph.h.
References llvm::sampleprof::ProfiledCallGraph::begin().
nodes_end()
static ChildIteratorType llvm::GraphTraits< ProfiledCallGraph * >::nodes_end (ProfiledCallGraph * PCG) inline static
Definition at line 206 of file ProfiledCallGraph.h.
References llvm::sampleprof::ProfiledCallGraph::end().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/ProfiledCallGraph.h