LLVM: llvm::ms_demangle::QualifiedNameNode Struct Reference
llvm::ms_demangle::QualifiedNameNode Struct Reference
#include "llvm/Demangle/MicrosoftDemangleNodes.h"
Public Member Functions
QualifiedNameNode ()
void output (OutputBuffer &OB, OutputFlags Flags) const override
IdentifierNode * getUnqualifiedIdentifier ()
Public Member Functions inherited from llvm::ms_demangle::Node
Node (NodeKind K)
virtual ~Node ()=default
NodeKind kind () const
std::string toString (OutputFlags Flags=OF_Default) const
Public Attributes
NodeArrayNode * Components = nullptr
Detailed Description
Definition at line 525 of file MicrosoftDemangleNodes.h.
Constructor & Destructor Documentation
QualifiedNameNode()
llvm::ms_demangle::QualifiedNameNode::QualifiedNameNode () inline
Definition at line 526 of file MicrosoftDemangleNodes.h.
Member Function Documentation
getUnqualifiedIdentifier()
IdentifierNode* llvm::ms_demangle::QualifiedNameNode::getUnqualifiedIdentifier () inline
Definition at line 532 of file MicrosoftDemangleNodes.h.
References Components, llvm::ms_demangle::NodeArrayNode::Count, and llvm::ms_demangle::NodeArrayNode::Nodes.
output()
void QualifiedNameNode::output (OutputBuffer & OB, OutputFlags Flags) const override virtual
Implements llvm::ms_demangle::Node.
Definition at line 628 of file MicrosoftDemangleNodes.cpp.
References Components, llvm::X86II::OB, and llvm::ms_demangle::NodeArrayNode::output().
Referenced by llvm::ms_demangle::DynamicStructorIdentifierNode::output(), llvm::ms_demangle::SymbolNode::output(), llvm::ms_demangle::SpecialTableSymbolNode::output(), llvm::ms_demangle::LocalStaticGuardVariableNode::output(), llvm::ms_demangle::VariableSymbolNode::output(), llvm::ms_demangle::FunctionSymbolNode::output(), and llvm::ms_demangle::PointerTypeNode::outputPre().
Member Data Documentation
Components
NodeArrayNode* llvm::ms_demangle::QualifiedNameNode::Components = nullptr
Definition at line 530 of file MicrosoftDemangleNodes.h.
Referenced by getUnqualifiedIdentifier(), output(), and synthesizeQualifiedName().
The documentation for this struct was generated from the following files:
include/llvm/Demangle/MicrosoftDemangleNodes.h
lib/Demangle/MicrosoftDemangleNodes.cpp