LLVM: llvm::LoopInterchangePass Struct Reference
llvm::LoopInterchangePass Struct Reference
#include "llvm/Transforms/Scalar/LoopInterchange.h"
Public Member Functions
PreservedAnalyses run (LoopNest &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Public Member Functions inherited from llvm::PassInfoMixin< LoopInterchangePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopInterchangePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 20 of file LoopInterchange.h.
Member Function Documentation
run()
PreservedAnalyses LoopInterchangePass::run (LoopNest & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U)
Definition at line 1719 of file LoopInterchange.cpp.
References llvm::LoopStandardAnalysisResults::AA, llvm::PreservedAnalyses::all(), CC, llvm::LoopStandardAnalysisResults::DT, F, llvm::CacheCost::getCacheCost(), llvm::getLoopPassPreservedAnalyses(), llvm::LoopNest::getOutermostLoop(), llvm::LoopNest::getParent(), llvm::LoopStandardAnalysisResults::LI, llvm::LPMUpdater::markLoopNestChanged(), and llvm::LoopStandardAnalysisResults::SE.
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Scalar/LoopInterchange.h
lib/Transforms/Scalar/LoopInterchange.cpp