LLVM: llvm::PreservedCFGCheckerInstrumentation::CFG Struct Reference
llvm::PreservedCFGCheckerInstrumentation::CFG Struct Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
CFG (const Function *F, bool TrackBBLifetime)
bool operator== (const CFG &G) const
bool isPoisoned () const
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &)
Static Public Member Functions
static void printDiff (raw_ostream &out, const CFG &Before, const CFG &After)
Public Attributes
std::optional< DenseMap< intptr_t, BBGuard > > BBGuards
DenseMap< const BasicBlock *, DenseMap< const BasicBlock *, unsigned > > Graph
Detailed Description
Definition at line 129 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
CFG()
PreservedCFGCheckerInstrumentation::CFG::CFG (const Function * F, bool TrackBBLifetime)
Definition at line 925 of file StandardInstrumentations.cpp.
References BB, BBGuards, F, Graph, and llvm::successors().
Member Function Documentation
invalidate()
bool PreservedCFGCheckerInstrumentation::CFG::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator &)
Definition at line 1052 of file StandardInstrumentations.cpp.
References llvm::PreservedAnalyses::getChecker().
isPoisoned()
bool llvm::PreservedCFGCheckerInstrumentation::CFG::isPoisoned () const inline
Definition at line 139 of file StandardInstrumentations.h.
References llvm::any_of(), BB, and BBGuards.
Referenced by operator==(), and printDiff().
operator==()
bool llvm::PreservedCFGCheckerInstrumentation::CFG::operator== (const CFG & G) const inline
Definition at line 135 of file StandardInstrumentations.h.
References G, Graph, and isPoisoned().
printDiff()
void PreservedCFGCheckerInstrumentation::CFG::printDiff (raw_ostream & out, const CFG & Before, const CFG & After) static
Definition at line 966 of file StandardInstrumentations.cpp.
References assert(), BB, Graph, isPoisoned(), and printBBName().
Referenced by llvm::PreservedCFGCheckerInstrumentation::registerCallbacks().
Member Data Documentation
BBGuards
std::optional<DenseMap<intptr_t, BBGuard> > llvm::PreservedCFGCheckerInstrumentation::CFG::BBGuards
Definition at line 130 of file StandardInstrumentations.h.
Referenced by CFG(), and isPoisoned().
Graph
DenseMap<const BasicBlock *, DenseMap<const BasicBlock *, unsigned> > llvm::PreservedCFGCheckerInstrumentation::CFG::Graph
Definition at line 131 of file StandardInstrumentations.h.
Referenced by CFG(), operator==(), and printDiff().
The documentation for this struct was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp