LLVM: llvm::AAExecutionDomain::ExecutionDomainTy Struct Reference
llvm::AAExecutionDomain::ExecutionDomainTy Struct Reference
Summary about the execution domain of a block or instruction.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using BarriersSetTy = SmallPtrSet< CallBase *, 2 >
using AssumesSetTy = SmallPtrSet< AssumeInst *, 4 >
Public Member Functions
void addAssumeInst (Attributor &A, AssumeInst &AI)
void addAlignedBarrier (Attributor &A, CallBase &CB)
void clearAssumeInstAndAlignedBarriers ()
Public Attributes
bool IsExecutedByInitialThreadOnly = true
bool IsReachedFromAlignedBarrierOnly = true
bool IsReachingAlignedBarrierOnly = true
bool EncounteredNonLocalSideEffect = false
BarriersSetTy AlignedBarriers
AssumesSetTy EncounteredAssumes
Detailed Description
Summary about the execution domain of a block or instruction.
Definition at line 5010 of file Attributor.h.
Member Typedef Documentation
AssumesSetTy
using llvm::AAExecutionDomain::ExecutionDomainTy::AssumesSetTy = SmallPtrSet<AssumeInst *, 4>
Definition at line 5012 of file Attributor.h.
BarriersSetTy
using llvm::AAExecutionDomain::ExecutionDomainTy::BarriersSetTy = SmallPtrSet<CallBase *, 2>
Definition at line 5011 of file Attributor.h.
Member Function Documentation
addAlignedBarrier()
void llvm::AAExecutionDomain::ExecutionDomainTy::addAlignedBarrier (Attributor & A, CallBase & CB) inline
Definition at line 5018 of file Attributor.h.
References AlignedBarriers, and llvm::SmallPtrSetImpl< PtrType >::insert().
addAssumeInst()
void llvm::AAExecutionDomain::ExecutionDomainTy::addAssumeInst (Attributor & A, AssumeInst & AI) inline
Definition at line 5014 of file Attributor.h.
References EncounteredAssumes, and llvm::SmallPtrSetImpl< PtrType >::insert().
clearAssumeInstAndAlignedBarriers()
void llvm::AAExecutionDomain::ExecutionDomainTy::clearAssumeInstAndAlignedBarriers () inline
Definition at line 5022 of file Attributor.h.
References AlignedBarriers, llvm::SmallPtrSetImplBase::clear(), and EncounteredAssumes.
Member Data Documentation
AlignedBarriers
BarriersSetTy llvm::AAExecutionDomain::ExecutionDomainTy::AlignedBarriers
Definition at line 5031 of file Attributor.h.
Referenced by addAlignedBarrier(), and clearAssumeInstAndAlignedBarriers().
EncounteredAssumes
AssumesSetTy llvm::AAExecutionDomain::ExecutionDomainTy::EncounteredAssumes
Definition at line 5032 of file Attributor.h.
Referenced by addAssumeInst(), and clearAssumeInstAndAlignedBarriers().
EncounteredNonLocalSideEffect
bool llvm::AAExecutionDomain::ExecutionDomainTy::EncounteredNonLocalSideEffect = false
Definition at line 5030 of file Attributor.h.
IsExecutedByInitialThreadOnly
bool llvm::AAExecutionDomain::ExecutionDomainTy::IsExecutedByInitialThreadOnly = true
Definition at line 5027 of file Attributor.h.
IsReachedFromAlignedBarrierOnly
bool llvm::AAExecutionDomain::ExecutionDomainTy::IsReachedFromAlignedBarrierOnly = true
Definition at line 5028 of file Attributor.h.
IsReachingAlignedBarrierOnly
bool llvm::AAExecutionDomain::ExecutionDomainTy::IsReachingAlignedBarrierOnly = true
Definition at line 5029 of file Attributor.h.
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h