LLVM: llvm::DenseMapInfo< std::tuple< Ts... > > Struct Template Reference
llvm::DenseMapInfo< std::tuple< Ts... > > Struct Template Reference
#include "llvm/ADT/DenseMapInfo.h"
Public Types
using Tuple = std::tuple< Ts... >
Static Public Member Functions
static Tuple getEmptyKey ()
static Tuple getTombstoneKey ()
template<unsigned I>
static unsigned getHashValueImpl (const Tuple &values, std::false_type)
template<unsigned I>
static unsigned getHashValueImpl (const Tuple &, std::true_type)
static unsigned getHashValue (const std::tuple< Ts... > &values)
template<unsigned I>
static bool isEqualImpl (const Tuple &lhs, const Tuple &rhs, std::false_type)
template<unsigned I>
static bool isEqualImpl (const Tuple &, const Tuple &, std::true_type)
static bool isEqual (const Tuple &lhs, const Tuple &rhs)
Detailed Description
template<typename... Ts>
struct llvm::DenseMapInfo< std::tuple< Ts... > >
Definition at line 244 of file DenseMapInfo.h.
Member Typedef Documentation
Tuple
template<typename... Ts> using llvm::DenseMapInfo< std::tuple< Ts... > >::Tuple = std::tuple<Ts...>
Definition at line 245 of file DenseMapInfo.h.
Member Function Documentation
getEmptyKey()
template<typename... Ts> static Tuple llvm::DenseMapInfo< std::tuple< Ts... > >::getEmptyKey () inline static
Definition at line 247 of file DenseMapInfo.h.
getHashValue()
template<typename... Ts> static unsigned llvm::DenseMapInfo< std::tuple< Ts... > >::getHashValue (const std::tuple< Ts... > & values) inline static
Definition at line 269 of file DenseMapInfo.h.
References llvm::cl::values().
getHashValueImpl() [1/2]
template<typename... Ts> template<unsigned I> static unsigned llvm::DenseMapInfo< std::tuple< Ts... > >::getHashValueImpl (const Tuple & , std::true_type) inline static
Definition at line 265 of file DenseMapInfo.h.
getHashValueImpl() [2/2]
template<typename... Ts> template<unsigned I> static unsigned llvm::DenseMapInfo< std::tuple< Ts... > >::getHashValueImpl (const Tuple & values, std::false_type) inline static
Definition at line 256 of file DenseMapInfo.h.
References llvm::detail::combineHashValue(), I, and llvm::cl::values().
getTombstoneKey()
template<typename... Ts> static Tuple llvm::DenseMapInfo< std::tuple< Ts... > >::getTombstoneKey () inline static
Definition at line 251 of file DenseMapInfo.h.
isEqual()
template<typename... Ts> static bool llvm::DenseMapInfo< std::tuple< Ts... > >::isEqual (const Tuple & lhs, const Tuple & rhs) inline static
Definition at line 287 of file DenseMapInfo.h.
isEqualImpl() [1/2]
template<typename... Ts> template<unsigned I> static bool llvm::DenseMapInfo< std::tuple< Ts... > >::isEqualImpl (const Tuple & , const Tuple & , std::true_type) inline static
Definition at line 283 of file DenseMapInfo.h.
isEqualImpl() [2/2]
template<typename... Ts> template<unsigned I> static bool llvm::DenseMapInfo< std::tuple< Ts... > >::isEqualImpl (const Tuple & lhs, const Tuple & rhs, std::false_type) inline static
Definition at line 275 of file DenseMapInfo.h.
References I, and isEqual().
The documentation for this struct was generated from the following file:
include/llvm/ADT/DenseMapInfo.h