LLVM: llvm::pdb::BulkPublic Struct Reference
llvm::pdb::BulkPublic Struct Reference
This struct is equivalent to codeview::PublicSym32, but it has been optimized for size to speed up bulk serialization and sorting operations during PDB writing.
#include "llvm/DebugInfo/PDB/Native/GSIStreamBuilder.h"
Public Member Functions
BulkPublic ()
void setFlags (codeview::PublicSymFlags F)
void setBucketIdx (uint16_t B)
StringRef getName () const
Public Attributes
const char * Name = nullptr
uint32_t NameLen = 0
uint32_t SymOffset = 0
uint32_t Offset = 0
uint16_t Segment = 0
uint16_t Flags: 4
uint16_t BucketIdx: 12
Detailed Description
This struct is equivalent to codeview::PublicSym32, but it has been optimized for size to speed up bulk serialization and sorting operations during PDB writing.
Definition at line 108 of file GSIStreamBuilder.h.
Constructor & Destructor Documentation
BulkPublic()
llvm::pdb::BulkPublic::BulkPublic () inline
Definition at line 109 of file GSIStreamBuilder.h.
Member Function Documentation
getName()
StringRef llvm::pdb::BulkPublic::getName () const inline
Definition at line 140 of file GSIStreamBuilder.h.
References Name, and NameLen.
Referenced by llvm::pdb::GSIStreamBuilder::addPublicSymbols(), computeAddrMap(), and llvm::pdb::GSIHashStreamBuilder::finalizeBuckets().
setBucketIdx()
void llvm::pdb::BulkPublic::setBucketIdx (uint16_t B) inline
Definition at line 135 of file GSIStreamBuilder.h.
References assert(), B, BucketIdx, and llvm::pdb::IPHR_HASH.
setFlags()
void llvm::pdb::BulkPublic::setFlags (codeview::PublicSymFlags F) inline
Definition at line 130 of file GSIStreamBuilder.h.
References assert(), F, and Flags.
Member Data Documentation
BucketIdx
uint16_t llvm::pdb::BulkPublic::BucketIdx
Definition at line 127 of file GSIStreamBuilder.h.
Referenced by llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), and setBucketIdx().
Flags
uint16_t llvm::pdb::BulkPublic::Flags
Definition at line 124 of file GSIStreamBuilder.h.
Referenced by setFlags().
Name
const char* llvm::pdb::BulkPublic::Name = nullptr
Definition at line 111 of file GSIStreamBuilder.h.
Referenced by getName().
NameLen
uint32_t llvm::pdb::BulkPublic::NameLen = 0
Definition at line 112 of file GSIStreamBuilder.h.
Referenced by getName().
Offset
uint32_t llvm::pdb::BulkPublic::Offset = 0
Definition at line 118 of file GSIStreamBuilder.h.
Referenced by computeAddrMap().
Segment
uint16_t llvm::pdb::BulkPublic::Segment = 0
Definition at line 121 of file GSIStreamBuilder.h.
Referenced by computeAddrMap().
SymOffset
uint32_t llvm::pdb::BulkPublic::SymOffset = 0
Definition at line 115 of file GSIStreamBuilder.h.
Referenced by llvm::pdb::GSIHashStreamBuilder::finalizeBuckets().
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/PDB/Native/GSIStreamBuilder.h