LLVM: llvm::TargetExtTypeKeyInfo Struct Reference
llvm::TargetExtTypeKeyInfo Struct Reference
#include "IR/LLVMContextImpl.h"
Classes
struct KeyTy
Static Public Member Functions
static TargetExtType * getEmptyKey ()
static TargetExtType * getTombstoneKey ()
static unsigned getHashValue (const KeyTy &Key)
static unsigned getHashValue (const TargetExtType *FT)
static bool isEqual (const KeyTy &LHS, const TargetExtType *RHS)
static bool isEqual (const TargetExtType *LHS, const TargetExtType *RHS)
Detailed Description
Definition at line 193 of file LLVMContextImpl.h.
Member Function Documentation
getEmptyKey()
static TargetExtType* llvm::TargetExtTypeKeyInfo::getEmptyKey () inline static
Definition at line 212 of file LLVMContextImpl.h.
Referenced by isEqual().
getHashValue() [1/2]
static unsigned llvm::TargetExtTypeKeyInfo::getHashValue (const KeyTy & Key) inline static
Definition at line 220 of file LLVMContextImpl.h.
References llvm::hash_combine(), and llvm::hash_combine_range().
Referenced by getHashValue().
getHashValue() [2/2]
static unsigned llvm::TargetExtTypeKeyInfo::getHashValue (const TargetExtType * FT) inline static
Definition at line 227 of file LLVMContextImpl.h.
References getHashValue().
getTombstoneKey()
static TargetExtType* llvm::TargetExtTypeKeyInfo::getTombstoneKey () inline static
Definition at line 216 of file LLVMContextImpl.h.
Referenced by isEqual().
isEqual() [1/2]
static bool llvm::TargetExtTypeKeyInfo::isEqual (const KeyTy & LHS, const TargetExtType * RHS) inline static
Definition at line 231 of file LLVMContextImpl.h.
References getEmptyKey(), getTombstoneKey(), LHS, and RHS.
isEqual() [2/2]
static bool llvm::TargetExtTypeKeyInfo::isEqual (const TargetExtType * LHS, const TargetExtType * RHS) inline static
Definition at line 237 of file LLVMContextImpl.h.
References LHS, and RHS.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h