LLVM: llvm::coverage::CovMapFunctionRecordV1< IntPtrT > Struct Template Reference
llvm::coverage::CovMapFunctionRecordV1< IntPtrT > Struct Template Reference
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Types
using ThisT = CovMapFunctionRecordV1< IntPtrT >
Public Member Functions
CovMapFunctionRecordV1 ()=delete
template<support::endianness Endian>
uint64_t getFuncHash () const
template<support::endianness Endian>
uint64_t getDataSize () const
template<support::endianness Endian>
IntPtrT getFuncNameRef () const
Return function lookup key. The value is consider opaque.
template<support::endianness Endian>
Error getFuncName (InstrProfSymtab &ProfileNames, StringRef &FuncName) const
Return the PGO name of the function.
template<support::endianness Endian>
std::pair< const char *, const ThisT * > advanceByOne (const char *MappingBuf) const
template<support::endianness Endian>
uint64_t getFilenamesRef () const
template<support::endianness Endian>
StringRef getCoverageMapping (const char *MappingBuf) const
Detailed Description
template<class IntPtrT>
struct llvm::coverage::CovMapFunctionRecordV1< IntPtrT >
Definition at line 837 of file CoverageMapping.h.
Member Typedef Documentation
ThisT
template<class IntPtrT > using llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::ThisT = CovMapFunctionRecordV1<IntPtrT>
Definition at line 838 of file CoverageMapping.h.
Constructor & Destructor Documentation
CovMapFunctionRecordV1()
template<class IntPtrT > llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::CovMapFunctionRecordV1 () delete
Member Function Documentation
advanceByOne()
template<class IntPtrT > template<support::endianness Endian> std::pair<const char *, const ThisT *> llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::advanceByOne (const char * MappingBuf) const inline
Definition at line 872 of file CoverageMapping.h.
getCoverageMapping()
template<class IntPtrT > template<support::endianness Endian> StringRef llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getCoverageMapping (const char * MappingBuf) const inline
Definition at line 881 of file CoverageMapping.h.
getDataSize()
template<class IntPtrT > template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getDataSize () const inline
Definition at line 850 of file CoverageMapping.h.
getFilenamesRef()
template<class IntPtrT > template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getFilenamesRef () const inline
Definition at line 876 of file CoverageMapping.h.
References llvm_unreachable.
getFuncHash()
template<class IntPtrT > template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getFuncHash () const inline
Definition at line 846 of file CoverageMapping.h.
getFuncName()
template<class IntPtrT > template<support::endianness Endian> Error llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getFuncName (InstrProfSymtab & ProfileNames, StringRef & FuncName) const inline
Return the PGO name of the function.
Definition at line 861 of file CoverageMapping.h.
References llvm::StringRef::empty(), llvm::InstrProfSymtab::getFuncName(), llvm::coverage::malformed, llvm::COFF::NameSize, and llvm::Error::success().
getFuncNameRef()
template<class IntPtrT > template<support::endianness Endian> IntPtrT llvm::coverage::CovMapFunctionRecordV1< IntPtrT >::getFuncNameRef () const inline
Return function lookup key. The value is consider opaque.
Definition at line 855 of file CoverageMapping.h.
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/Coverage/CoverageMapping.h