LLVM: llvm::sampleprof::CSProfileConverter::FrameNode Struct Reference
llvm::sampleprof::CSProfileConverter::FrameNode Struct Reference
#include "llvm/ProfileData/SampleProf.h"
Public Member Functions
FrameNode (StringRef FName=StringRef(), FunctionSamples *FSamples=nullptr, LineLocation CallLoc={0, 0})
FrameNode * getOrCreateChildFrame (const LineLocation &CallSite, StringRef CalleeName)
Public Attributes
std::map< uint64_t, FrameNode > AllChildFrames
StringRef FuncName
FunctionSamples * FuncSamples
LineLocation CallSiteLoc
Detailed Description
Definition at line 1283 of file SampleProf.h.
Constructor & Destructor Documentation
FrameNode()
llvm::sampleprof::CSProfileConverter::FrameNode::FrameNode (StringRef FName = StringRef(), FunctionSamples * FSamples = nullptr, LineLocation CallLoc = {0, 0}) inline
Definition at line 1284 of file SampleProf.h.
Referenced by getOrCreateChildFrame().
Member Function Documentation
getOrCreateChildFrame()
CSProfileConverter::FrameNode * CSProfileConverter::FrameNode::getOrCreateChildFrame (const LineLocation & CallSite, StringRef CalleeName)
Definition at line 465 of file SampleProf.cpp.
References AllChildFrames, assert(), FrameNode(), llvm::sampleprof::FunctionSamples::getCallSiteHash(), and uint64_t.
Member Data Documentation
AllChildFrames
std::map<uint64_t, FrameNode> llvm::sampleprof::CSProfileConverter::FrameNode::AllChildFrames
Definition at line 1287 of file SampleProf.h.
Referenced by getOrCreateChildFrame().
CallSiteLoc
LineLocation llvm::sampleprof::CSProfileConverter::FrameNode::CallSiteLoc
Definition at line 1296 of file SampleProf.h.
FuncName
StringRef llvm::sampleprof::CSProfileConverter::FrameNode::FuncName
Definition at line 1292 of file SampleProf.h.
FuncSamples
FunctionSamples* llvm::sampleprof::CSProfileConverter::FrameNode::FuncSamples
Definition at line 1294 of file SampleProf.h.
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/SampleProf.h
lib/ProfileData/SampleProf.cpp