LLVM: llvm::objcopy::coff::AuxSymbol Struct Reference
llvm::objcopy::coff::AuxSymbol Struct Reference
#include "ObjCopy/COFF/COFFObject.h"
Public Member Functions
AuxSymbol (ArrayRef< uint8_t > In)
ArrayRef< uint8_t > getRef () const
Public Attributes
uint8_t Opaque [sizeof(object::coff_symbol16)]
Detailed Description
Definition at line 69 of file COFFObject.h.
Constructor & Destructor Documentation
AuxSymbol()
llvm::objcopy::coff::AuxSymbol::AuxSymbol (ArrayRef< uint8_t > In) inline
Definition at line 70 of file COFFObject.h.
References assert(), copy, llvm::tgtok::In, and Opaque.
Member Function Documentation
getRef()
ArrayRef<uint8_t> llvm::objcopy::coff::AuxSymbol::getRef () const inline
Definition at line 75 of file COFFObject.h.
References Opaque.
Member Data Documentation
Opaque
uint8_t llvm::objcopy::coff::AuxSymbol::Opaque[sizeof(object::coff_symbol16)]
Definition at line 79 of file COFFObject.h.
Referenced by AuxSymbol(), and getRef().
The documentation for this struct was generated from the following file:
lib/ObjCopy/COFF/COFFObject.h