LLVM: llvm::DictScope Struct Reference
llvm::DictScope Struct Reference
#include "llvm/Support/ScopedPrinter.h"
Public Member Functions
DictScope ()=default
DictScope (ScopedPrinter &W)
DictScope (ScopedPrinter &W, StringRef N)
void setPrinter (ScopedPrinter &W) override
~DictScope ()
Public Member Functions inherited from llvm::DelimitedScope
DelimitedScope (ScopedPrinter &W)
DelimitedScope ()
virtual ~DelimitedScope ()=default
Additional Inherited Members
Public Attributes inherited from llvm::DelimitedScope
ScopedPrinter * W
Detailed Description
Definition at line 809 of file ScopedPrinter.h.
Constructor & Destructor Documentation
DictScope() [1/3]
llvm::DictScope::DictScope () explicit default
DictScope() [2/3]
llvm::DictScope::DictScope (ScopedPrinter & W) inline explicit
Definition at line 811 of file ScopedPrinter.h.
References llvm::ScopedPrinter::objectBegin(), and llvm::DelimitedScope::W.
DictScope() [3/3]
llvm::DictScope::DictScope (ScopedPrinter & W, StringRef N) inline
Definition at line 813 of file ScopedPrinter.h.
References N, llvm::ScopedPrinter::objectBegin(), and llvm::DelimitedScope::W.
~DictScope()
llvm::DictScope::~DictScope () inline
Definition at line 822 of file ScopedPrinter.h.
References llvm::ScopedPrinter::objectEnd(), and llvm::DelimitedScope::W.
Member Function Documentation
setPrinter()
void llvm::DictScope::setPrinter (ScopedPrinter & W) inline override virtual
Implements llvm::DelimitedScope.
Definition at line 817 of file ScopedPrinter.h.
References llvm::ScopedPrinter::objectBegin(), and llvm::DelimitedScope::W.
The documentation for this struct was generated from the following file:
include/llvm/Support/ScopedPrinter.h