LLVM: llvm::detail::zip_common< ZipType, Iters > Struct Template Reference
llvm::detail::zip_common< ZipType, Iters > Struct Template Reference
#include "llvm/ADT/STLExtras.h"
Public Types
using Base = zip_traits< ZipType, Iters... >
using value_type = typename Base::value_type
Public Types inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
using iterator_category = IteratorCategoryT
using value_type = T
using difference_type = DifferenceTypeT
using pointer = PointerT
using reference = ReferenceT
Public Member Functions
zip_common (Iters &&... ts)
value_type operator* () const
ZipType & operator++ ()
ZipType & operator-- ()
bool all_equals (zip_common &other)
Return true if all the iterator are matching other's iterators.
Public Member Functions inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
DerivedT operator+ (DifferenceTypeT n) const
DerivedT operator- (DifferenceTypeT n) const
DerivedT & operator++ ()
DerivedT operator++ (int)
DerivedT & operator-- ()
DerivedT operator-- (int)
bool operator!= (const DerivedT &RHS) const
bool operator> (const DerivedT &RHS) const
bool operator<= (const DerivedT &RHS) const
bool operator>= (const DerivedT &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (DifferenceTypeT n) const
Public Attributes
std::tuple< Iters... > iterators
Protected Member Functions
template<size_t... Ns>
value_type deref (std::index_sequence< Ns... >) const
template<size_t... Ns>
decltype(iterators) tup_inc (std::index_sequence< Ns... >) const
template<size_t... Ns>
decltype(iterators) tup_dec (std::index_sequence< Ns... >) const
template<size_t... Ns>
bool test_all_equals (const zip_common &other, std::index_sequence< Ns... >) const
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< DerivedT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT >
enum { IsRandomAccess, IsBidirectional }
Detailed Description
template<typename ZipType, typename... Iters>
struct llvm::detail::zip_common< ZipType, Iters >
Definition at line 765 of file STLExtras.h.
Member Typedef Documentation
Base
template<typename ZipType , typename... Iters> using llvm::detail::zip_common< ZipType, Iters >::Base = zip_traits<ZipType, Iters...>
Definition at line 766 of file STLExtras.h.
value_type
template<typename ZipType , typename... Iters> using llvm::detail::zip_common< ZipType, Iters >::value_type = typename Base::value_type
Definition at line 767 of file STLExtras.h.
Constructor & Destructor Documentation
zip_common()
template<typename ZipType , typename... Iters> llvm::detail::zip_common< ZipType, Iters >::zip_common (Iters &&... ts) inline
Definition at line 794 of file STLExtras.h.
Member Function Documentation
all_equals()
template<typename ZipType , typename... Iters> bool llvm::detail::zip_common< ZipType, Iters >::all_equals (zip_common< ZipType, Iters > & other) inline
Return true if all the iterator are matching other's iterators.
Definition at line 813 of file STLExtras.h.
deref()
template<typename ZipType , typename... Iters> template<size_t... Ns> value_type llvm::detail::zip_common< ZipType, Iters >::deref (std::index_sequence< Ns... >) const inline protected
Definition at line 772 of file STLExtras.h.
Referenced by llvm::detail::zip_common< zip_first< Iters... >, Iters... >::operator*().
operator*()
template<typename ZipType , typename... Iters> value_type llvm::detail::zip_common< ZipType, Iters >::operator* () const inline
Definition at line 796 of file STLExtras.h.
operator++()
template<typename ZipType , typename... Iters> ZipType& llvm::detail::zip_common< ZipType, Iters >::operator++ () inline
Definition at line 800 of file STLExtras.h.
operator--()
template<typename ZipType , typename... Iters> ZipType& llvm::detail::zip_common< ZipType, Iters >::operator-- () inline
Definition at line 805 of file STLExtras.h.
test_all_equals()
template<typename ZipType , typename... Iters> template<size_t... Ns> bool llvm::detail::zip_common< ZipType, Iters >::test_all_equals (const zip_common< ZipType, Iters > & other, std::index_sequence< Ns... >) const inline protected
Definition at line 787 of file STLExtras.h.
Referenced by llvm::detail::zip_common< zip_first< Iters... >, Iters... >::all_equals().
tup_dec()
template<typename ZipType , typename... Iters> template<size_t... Ns> decltype(iterators) llvm::detail::zip_common< ZipType, Iters >::tup_dec (std::index_sequence< Ns... >) const inline protected
Definition at line 782 of file STLExtras.h.
Referenced by llvm::detail::zip_common< zip_first< Iters... >, Iters... >::operator--().
tup_inc()
template<typename ZipType , typename... Iters> template<size_t... Ns> decltype(iterators) llvm::detail::zip_common< ZipType, Iters >::tup_inc (std::index_sequence< Ns... >) const inline protected
Definition at line 777 of file STLExtras.h.
Referenced by llvm::detail::zip_common< zip_first< Iters... >, Iters... >::operator++().
Member Data Documentation
iterators
template<typename ZipType , typename... Iters> std::tuple<Iters...> llvm::detail::zip_common< ZipType, Iters >::iterators
Definition at line 769 of file STLExtras.h.
Referenced by llvm::detail::zip_common< zip_first< Iters... >, Iters... >::deref(), llvm::detail::zip_common< zip_first< Iters... >, Iters... >::operator++(), llvm::detail::zip_common< zip_first< Iters... >, Iters... >::operator--(), llvm::detail::zip_common< zip_first< Iters... >, Iters... >::test_all_equals(), llvm::detail::zip_common< zip_first< Iters... >, Iters... >::tup_dec(), and llvm::detail::zip_common< zip_first< Iters... >, Iters... >::tup_inc().
The documentation for this struct was generated from the following file:
include/llvm/ADT/STLExtras.h