LLVM: llvm::yaml::FrameIndex Struct Reference
llvm::yaml::FrameIndex Struct Reference
A serializaable representation of a reference to a stack object or fixed stack object.
#include "llvm/CodeGen/MIRYamlMapping.h"
Public Member Functions
FrameIndex ()=default
FrameIndex (int FI, const llvm::MachineFrameInfo &MFI)
Expected< int > getFI (const llvm::MachineFrameInfo &MFI) const
Public Attributes
int FI
bool IsFixed
SMRange SourceRange
Detailed Description
A serializaable representation of a reference to a stack object or fixed stack object.
Definition at line 388 of file MIRYamlMapping.h.
Constructor & Destructor Documentation
FrameIndex() [1/2]
llvm::yaml::FrameIndex::FrameIndex () default
FrameIndex() [2/2]
FrameIndex::FrameIndex (int FI, const llvm::MachineFrameInfo & MFI)
Definition at line 22 of file MIRYamlMapping.cpp.
References FI, llvm::MachineFrameInfo::getObjectIndexBegin(), IsFixed, and llvm::MachineFrameInfo::isFixedObjectIndex().
Member Function Documentation
getFI()
Expected< int > FrameIndex::getFI (const llvm::MachineFrameInfo & MFI) const
Definition at line 30 of file MIRYamlMapping.cpp.
References FI, llvm::formatv(), llvm::MachineFrameInfo::getNumFixedObjects(), llvm::MachineFrameInfo::getNumObjects(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::inconvertibleErrorCode(), and IsFixed.
Member Data Documentation
FI
int llvm::yaml::FrameIndex::FI
Definition at line 392 of file MIRYamlMapping.h.
Referenced by FrameIndex(), getFI(), llvm::yaml::ScalarTraits< FrameIndex >::input(), and llvm::yaml::ScalarTraits< FrameIndex >::output().
IsFixed
bool llvm::yaml::FrameIndex::IsFixed
Definition at line 393 of file MIRYamlMapping.h.
Referenced by FrameIndex(), getFI(), llvm::yaml::ScalarTraits< FrameIndex >::input(), and llvm::yaml::ScalarTraits< FrameIndex >::output().
SourceRange
SMRange llvm::yaml::FrameIndex::SourceRange
Definition at line 394 of file MIRYamlMapping.h.
Referenced by llvm::yaml::ScalarTraits< FrameIndex >::input().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/MIRYamlMapping.h
lib/CodeGen/MIRYamlMapping.cpp