LLVM: llvm::DenseMapInfo< LocIdx > Struct Reference
llvm::DenseMapInfo< LocIdx > Struct Reference
#include "CodeGen/LiveDebugValues/InstrRefBasedImpl.h"
Static Public Member Functions
static LocIdx getEmptyKey ()
static LocIdx getTombstoneKey ()
static unsigned getHashValue (const LocIdx &Loc)
static bool isEqual (const LocIdx &A, const LocIdx &B)
Detailed Description
Definition at line 178 of file InstrRefBasedImpl.h.
Member Function Documentation
getEmptyKey()
static LocIdx llvm::DenseMapInfo< LocIdx >::getEmptyKey () inline static
Definition at line 179 of file InstrRefBasedImpl.h.
References LiveDebugValues::LocIdx::MakeIllegalLoc().
getHashValue()
static unsigned llvm::DenseMapInfo< LocIdx >::getHashValue (const LocIdx & Loc) inline static
Definition at line 182 of file InstrRefBasedImpl.h.
References LiveDebugValues::LocIdx::asU64().
getTombstoneKey()
static LocIdx llvm::DenseMapInfo< LocIdx >::getTombstoneKey () inline static
Definition at line 180 of file InstrRefBasedImpl.h.
References LiveDebugValues::LocIdx::MakeTombstoneLoc().
isEqual()
static bool llvm::DenseMapInfo< LocIdx >::isEqual (const LocIdx & A, const LocIdx & B) inline static
Definition at line 184 of file InstrRefBasedImpl.h.
References B.
The documentation for this struct was generated from the following file:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.h