LLVM: llvm::InlineAdvisorAnalysis::Result Struct Reference
llvm::InlineAdvisorAnalysis::Result Struct Reference
#include "llvm/Analysis/InlineAdvisor.h"
Public Member Functions
Result (Module &M, ModuleAnalysisManager &MAM)
bool invalidate (Module &, const PreservedAnalyses &PA, ModuleAnalysisManager::Invalidator &)
bool tryCreate (InlineParams Params, InliningAdvisorMode Mode, const ReplayInlinerSettings &ReplaySettings, InlineContext IC)
InlineAdvisor * getAdvisor () const
Detailed Description
Definition at line 322 of file InlineAdvisor.h.
Constructor & Destructor Documentation
Result()
llvm::InlineAdvisorAnalysis::Result::Result (Module & M, ModuleAnalysisManager & MAM) inline
Definition at line 323 of file InlineAdvisor.h.
References M, and MAM.
Member Function Documentation
getAdvisor()
InlineAdvisor* llvm::InlineAdvisorAnalysis::Result::getAdvisor () const inline
Definition at line 334 of file InlineAdvisor.h.
invalidate()
bool llvm::InlineAdvisorAnalysis::Result::invalidate (Module & , const PreservedAnalyses & PA, ModuleAnalysisManager::Invalidator &) inline
Definition at line 324 of file InlineAdvisor.h.
References llvm::PreservedAnalyses::getChecker().
tryCreate()
bool InlineAdvisorAnalysis::Result::tryCreate (InlineParams Params, InliningAdvisorMode Mode, const ReplayInlinerSettings & ReplaySettings, InlineContext IC)
Definition at line 202 of file InlineAdvisor.cpp.
References llvm::AArch64PACKey::DA, llvm::dbgs(), llvm::Default, llvm::Development, llvm::StringRef::empty(), FAM, llvm::Module::getContext(), getDefaultInlineAdvice(), llvm::getDevelopmentModeAdvisor(), llvm::getReleaseModeAdvisor(), llvm::getReplayInlineAdvisor(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PluginInlineAdvisorAnalysis::HasBeenRegistered, LLVM_DEBUG, Mode, move, llvm::Release, and llvm::ReplayInlinerSettings::ReplayFile.
The documentation for this struct was generated from the following files:
include/llvm/Analysis/InlineAdvisor.h
lib/Analysis/InlineAdvisor.cpp