LLVM: EnumAttr Struct Reference
EnumAttr Struct Reference
Static Public Member Functions
static bool isSet (const Function &Fn, Attribute::AttrKind Kind)
static void set (Function &Fn, Attribute::AttrKind Kind, bool Val)
Detailed Description
Definition at line 2074 of file Attributes.cpp.
Member Function Documentation
isSet()
static bool EnumAttr::isSet (const Function & Fn, Attribute::AttrKind Kind) inline static
Definition at line 2075 of file Attributes.cpp.
References llvm::Function::hasFnAttribute().
set()
static void EnumAttr::set (Function & Fn, Attribute::AttrKind Kind, bool Val) inline static
Definition at line 2080 of file Attributes.cpp.
References llvm::Function::addFnAttr(), and llvm::Function::removeFnAttr().
The documentation for this struct was generated from the following file:
lib/IR/Attributes.cpp