LLVM: llvm::CoroConditionalWrapper Struct Reference
llvm::CoroConditionalWrapper Struct Reference
#include "llvm/Transforms/Coroutines/CoroConditionalWrapper.h"
Public Member Functions
CoroConditionalWrapper (ModulePassManager &&)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< CoroConditionalWrapper >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< CoroConditionalWrapper >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 20 of file CoroConditionalWrapper.h.
Constructor & Destructor Documentation
CoroConditionalWrapper()
CoroConditionalWrapper::CoroConditionalWrapper (ModulePassManager && PM)
Definition at line 15 of file CoroConditionalWrapper.cpp.
Member Function Documentation
isRequired()
static bool llvm::CoroConditionalWrapper::isRequired () inline static
Definition at line 23 of file CoroConditionalWrapper.h.
printPipeline()
void CoroConditionalWrapper::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 26 of file CoroConditionalWrapper.cpp.
References OS, and llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::printPipeline().
run()
PreservedAnalyses CoroConditionalWrapper::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 18 of file CoroConditionalWrapper.cpp.
References llvm::PreservedAnalyses::all(), llvm::coro::declaresAnyIntrinsic(), M, and llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Coroutines/CoroConditionalWrapper.h
lib/Transforms/Coroutines/CoroConditionalWrapper.cpp