LLVM: llvm::ListScope Struct Reference
llvm::ListScope Struct Reference
#include "llvm/Support/ScopedPrinter.h"
Public Member Functions
ListScope ()=default
ListScope (ScopedPrinter &W)
ListScope (ScopedPrinter &W, StringRef N)
void setPrinter (ScopedPrinter &W) override
~ListScope ()
Public Member Functions inherited from llvm::DelimitedScope
DelimitedScope (ScopedPrinter &W)
DelimitedScope ()
virtual ~DelimitedScope ()=default
Additional Inherited Members
Public Attributes inherited from llvm::DelimitedScope
ScopedPrinter * W
Detailed Description
Definition at line 828 of file ScopedPrinter.h.
Constructor & Destructor Documentation
ListScope() [1/3]
llvm::ListScope::ListScope () explicit default
ListScope() [2/3]
llvm::ListScope::ListScope (ScopedPrinter & W) inline explicit
Definition at line 830 of file ScopedPrinter.h.
References llvm::ScopedPrinter::arrayBegin(), and llvm::DelimitedScope::W.
ListScope() [3/3]
llvm::ListScope::ListScope (ScopedPrinter & W, StringRef N) inline
Definition at line 832 of file ScopedPrinter.h.
References llvm::ScopedPrinter::arrayBegin(), N, and llvm::DelimitedScope::W.
~ListScope()
llvm::ListScope::~ListScope () inline
Definition at line 841 of file ScopedPrinter.h.
References llvm::ScopedPrinter::arrayEnd(), and llvm::DelimitedScope::W.
Member Function Documentation
setPrinter()
void llvm::ListScope::setPrinter (ScopedPrinter & W) inline override virtual
Implements llvm::DelimitedScope.
Definition at line 836 of file ScopedPrinter.h.
References llvm::ScopedPrinter::arrayBegin(), and llvm::DelimitedScope::W.
The documentation for this struct was generated from the following file:
include/llvm/Support/ScopedPrinter.h