LLVM: llvm::GraphTraits< AADepGraph * > Struct Reference
llvm::GraphTraits< AADepGraph * > Struct Reference
Public Types
using nodes_iterator = mapped_iterator< AADepGraphNode::DepSetTy::iterator, decltype(&DepGetVal)>
Public Types inherited from llvm::GraphTraits< AADepGraphNode * >
using NodeRef = AADepGraphNode *
using DepTy = PointerIntPair< AADepGraphNode *, 1 >
using EdgeRef = PointerIntPair< AADepGraphNode *, 1 >
using ChildIteratorType = mapped_iterator< AADepGraphNode::DepSetTy::iterator, decltype(&DepGetVal)>
using ChildEdgeIteratorType = AADepGraphNode::DepSetTy::iterator
Static Public Member Functions
static NodeRef getEntryNode (AADepGraph *DG)
static nodes_iterator nodes_begin (AADepGraph *DG)
static nodes_iterator nodes_end (AADepGraph *DG)
Static Public Member Functions inherited from llvm::GraphTraits< AADepGraphNode * >
static NodeRef getEntryNode (AADepGraphNode *DGN)
static NodeRef DepGetVal (const DepTy &DT)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
Definition at line 3708 of file Attributor.cpp.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< AADepGraph * >::nodes_iterator = mapped_iterator<AADepGraphNode::DepSetTy::iterator, decltype(&DepGetVal)>
Definition at line 3712 of file Attributor.cpp.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< AADepGraph * >::getEntryNode (AADepGraph * DG) inline static
Definition at line 3709 of file Attributor.cpp.
References llvm::AADepGraph::GetEntryNode().
nodes_begin()
static nodes_iterator llvm::GraphTraits< AADepGraph * >::nodes_begin (AADepGraph * DG) inline static
Definition at line 3714 of file Attributor.cpp.
References llvm::AADepGraph::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< AADepGraph * >::nodes_end (AADepGraph * DG) inline static
Definition at line 3716 of file Attributor.cpp.
References llvm::AADepGraph::end().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/Attributor.cpp