LLVM: llvm::mca::RegisterFile::RAWHazard Struct Reference
llvm::mca::RegisterFile::RAWHazard Struct Reference
#include "llvm/MCA/HardwareUnits/RegisterFile.h"
Public Member Functions
RAWHazard ()
bool isValid () const
bool hasUnknownCycles () const
Public Attributes
MCPhysReg RegisterID
int CyclesLeft
Detailed Description
Definition at line 239 of file RegisterFile.h.
Constructor & Destructor Documentation
RAWHazard()
llvm::mca::RegisterFile::RAWHazard::RAWHazard () inline
Definition at line 243 of file RegisterFile.h.
Member Function Documentation
hasUnknownCycles()
bool llvm::mca::RegisterFile::RAWHazard::hasUnknownCycles () const inline
Definition at line 245 of file RegisterFile.h.
References CyclesLeft.
Referenced by llvm::mca::checkRegisterHazard().
isValid()
bool llvm::mca::RegisterFile::RAWHazard::isValid () const inline
Definition at line 244 of file RegisterFile.h.
References RegisterID.
Referenced by llvm::mca::RegisterFile::checkRAWHazards(), and llvm::mca::checkRegisterHazard().
Member Data Documentation
CyclesLeft
int llvm::mca::RegisterFile::RAWHazard::CyclesLeft
Definition at line 241 of file RegisterFile.h.
Referenced by llvm::mca::RegisterFile::checkRAWHazards(), llvm::mca::checkRegisterHazard(), and hasUnknownCycles().
RegisterID
MCPhysReg llvm::mca::RegisterFile::RAWHazard::RegisterID
Definition at line 240 of file RegisterFile.h.
Referenced by llvm::mca::RegisterFile::checkRAWHazards(), and isValid().
The documentation for this struct was generated from the following file:
include/llvm/MCA/HardwareUnits/RegisterFile.h