LLVM: llvm::DecIntegerState< base_ty > Struct Template Reference
llvm::DecIntegerState< base_ty > Struct Template Reference
Specialization of the integer state for a decreasing value, hence 0 is the best state and ~0u the worst.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using base_t = base_ty
Public Types inherited from llvm::IntegerStateBase< uint32_t, 0, ~uint32_t(0)>
using base_t = uint32_t
Public Member Functions
DecIntegerState & takeAssumedMaximum (base_t Value)
Take maximum of assumed and Value.
DecIntegerState & takeKnownMinimum (base_t Value)
Take minimum of known and Value.
Public Member Functions inherited from llvm::IntegerStateBase< uint32_t, 0, ~uint32_t(0)>
IntegerStateBase ()=default
IntegerStateBase (base_t Assumed)
bool isValidState () const override
See AbstractState::isValidState() NOTE: For now we simply pretend that the worst possible state is invalid.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
base_t getKnown () const
Return the known state encoding.
base_t getAssumed () const
Return the assumed state encoding.
bool operator== (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Equality for IntegerStateBase.
bool operator!= (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Inequality for IntegerStateBase.
void operator^= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator+= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator|= (const IntegerStateBase< base_t, BestState, WorstState > &R)
void operator&= (const IntegerStateBase< base_t, BestState, WorstState > &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
virtual bool isValidState () const =0
Return if this abstract state is in a valid state.
virtual bool isAtFixpoint () const =0
Return if this abstract state is fixed, thus does not need to be updated if information changes as it cannot change itself.
Additional Inherited Members
Static Public Member Functions inherited from llvm::IntegerStateBase< uint32_t, 0, ~uint32_t(0)>
static constexpr base_t getBestState ()
Return the best possible representable state.
static constexpr base_t getBestState (const IntegerStateBase &)
static constexpr base_t getWorstState ()
Return the worst possible representable state.
static constexpr base_t getWorstState (const IntegerStateBase &)
Protected Member Functions inherited from llvm::IntegerStateBase< uint32_t, 0, ~uint32_t(0)>
virtual void handleNewAssumedValue (base_t Value)=0
Handle a new assumed value Value. Subtype dependent.
virtual void handleNewKnownValue (base_t Value)=0
Handle a new known value Value. Subtype dependent.
virtual void joinOR (base_t AssumedValue, base_t KnownValue)=0
Handle a value Value. Subtype dependent.
virtual void joinAND (base_t AssumedValue, base_t KnownValue)=0
Handle a new assumed value Value. Subtype dependent.
Protected Attributes inherited from llvm::IntegerStateBase< uint32_t, 0, ~uint32_t(0)>
base_t Known
The known state encoding in an integer of type base_t.
base_t Assumed
The assumed state encoding in an integer of type base_t.
Detailed Description
template<typename base_ty = uint32_t>
struct llvm::DecIntegerState< base_ty >
Specialization of the integer state for a decreasing value, hence 0 is the best state and ~0u the worst.
Definition at line 2675 of file Attributor.h.
Member Typedef Documentation
base_t
template<typename base_ty = uint32_t> using llvm::DecIntegerState< base_ty >::base_t = base_ty
Definition at line 2676 of file Attributor.h.
Member Function Documentation
takeAssumedMaximum()
template<typename base_ty = uint32_t> DecIntegerState& llvm::DecIntegerState< base_ty >::takeAssumedMaximum (base_t Value) inline
Take maximum of assumed and Value.
Definition at line 2679 of file Attributor.h.
References llvm::IntegerStateBase< uint32_t, 0, ~uint32_t(0)>::Assumed, llvm::IntegerStateBase< uint32_t, 0, ~uint32_t(0)>::Known, llvm::max(), and llvm::min().
takeKnownMinimum()
template<typename base_ty = uint32_t> DecIntegerState& llvm::DecIntegerState< base_ty >::takeKnownMinimum (base_t Value) inline
Take minimum of known and Value.
Definition at line 2686 of file Attributor.h.
References llvm::IntegerStateBase< uint32_t, 0, ~uint32_t(0)>::Assumed, llvm::IntegerStateBase< uint32_t, 0, ~uint32_t(0)>::Known, and llvm::min().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h