LLVM: llvm::MemOp Struct Reference
llvm::MemOp Struct Reference
#include "llvm/CodeGen/TargetLowering.h"
Public Member Functions
uint64_t size () const
Align getDstAlign () const
bool isFixedDstAlign () const
bool allowOverlap () const
bool isMemset () const
bool isMemcpy () const
bool isMemcpyWithFixedDstAlign () const
bool isZeroMemset () const
bool isMemcpyStrSrc () const
Align getSrcAlign () const
bool isSrcAligned (Align AlignCheck) const
bool isDstAligned (Align AlignCheck) const
bool isAligned (Align AlignCheck) const
Static Public Member Functions
static MemOp Copy (uint64_t Size, bool DstAlignCanChange, Align DstAlign, Align SrcAlign, bool IsVolatile, bool MemcpyStrSrc=false)
static MemOp Set (uint64_t Size, bool DstAlignCanChange, Align DstAlign, bool IsZeroMemset, bool IsVolatile)
Detailed Description
Definition at line 112 of file TargetLowering.h.
Member Function Documentation
allowOverlap()
bool llvm::MemOp::allowOverlap () const inline
Definition at line 164 of file TargetLowering.h.
Copy()
static MemOp llvm::MemOp::Copy (uint64_t Size, bool DstAlignCanChange, Align DstAlign, Align SrcAlign, bool IsVolatile, bool MemcpyStrSrc = false) inline static
Definition at line 130 of file TargetLowering.h.
Referenced by getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), and llvm::ARMTTIImpl::getNumMemOps().
getDstAlign()
Align llvm::MemOp::getDstAlign () const inline
Definition at line 159 of file TargetLowering.h.
References assert().
getSrcAlign()
Align llvm::MemOp::getSrcAlign () const inline
Definition at line 175 of file TargetLowering.h.
References assert(), and isMemcpy().
isAligned()
bool llvm::MemOp::isAligned (Align AlignCheck) const inline
Definition at line 185 of file TargetLowering.h.
References isDstAligned(), and isSrcAligned().
isDstAligned()
bool llvm::MemOp::isDstAligned (Align AlignCheck) const inline
Definition at line 182 of file TargetLowering.h.
References llvm::isAligned(), and llvm::Align::value().
Referenced by isAligned().
isFixedDstAlign()
bool llvm::MemOp::isFixedDstAlign () const inline
Definition at line 163 of file TargetLowering.h.
isMemcpy()
bool llvm::MemOp::isMemcpy () const inline
Definition at line 166 of file TargetLowering.h.
Referenced by getSrcAlign(), isMemcpyStrSrc(), and isMemcpyWithFixedDstAlign().
isMemcpyStrSrc()
bool llvm::MemOp::isMemcpyStrSrc () const inline
Definition at line 171 of file TargetLowering.h.
References assert(), and isMemcpy().
isMemcpyWithFixedDstAlign()
bool llvm::MemOp::isMemcpyWithFixedDstAlign () const inline
Definition at line 167 of file TargetLowering.h.
References isMemcpy().
isMemset()
bool llvm::MemOp::isMemset () const inline
Definition at line 165 of file TargetLowering.h.
Referenced by isSrcAligned(), and isZeroMemset().
isSrcAligned()
bool llvm::MemOp::isSrcAligned (Align AlignCheck) const inline
Definition at line 179 of file TargetLowering.h.
References llvm::isAligned(), isMemset(), and llvm::Align::value().
Referenced by isAligned().
isZeroMemset()
bool llvm::MemOp::isZeroMemset () const inline
Definition at line 170 of file TargetLowering.h.
References isMemset().
Set()
static MemOp llvm::MemOp::Set (uint64_t Size, bool DstAlignCanChange, Align DstAlign, bool IsZeroMemset, bool IsVolatile) inline static
Definition at line 145 of file TargetLowering.h.
Referenced by getMemcpyLoadsAndStores(), getMemsetStores(), and llvm::ARMTTIImpl::getNumMemOps().
size()
uint64_t llvm::MemOp::size () const inline
Definition at line 158 of file TargetLowering.h.
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/TargetLowering.h