LLVM: llvm::CodeViewDebug::LocalVarDef Struct Reference
llvm::CodeViewDebug::LocalVarDef Struct Reference
#include "CodeGen/AsmPrinter/CodeViewDebug.h"
Static Public Member Functions
static uint64_t toOpaqueValue (const LocalVarDef DR)
static LocalVarDef createFromOpaqueValue (uint64_t Val)
Public Attributes
int InMemory: 1
Indicates that variable data is stored in memory relative to the specified register.
int DataOffset: 31
Offset of variable data in memory.
uint16_t IsSubfield: 1
Non-zero if this is a piece of an aggregate.
uint16_t StructOffset: 15
Offset into aggregate.
uint16_t CVRegister
Register containing the data or the register base of the memory location containing the data.
Detailed Description
Definition at line 54 of file CodeViewDebug.h.
Member Function Documentation
createFromOpaqueValue()
static LocalVarDef llvm::CodeViewDebug::LocalVarDef::createFromOpaqueValue (uint64_t Val) inline static
Definition at line 78 of file CodeViewDebug.h.
References memcpy().
Referenced by llvm::DenseMapInfo< CodeViewDebug::LocalVarDef >::getEmptyKey(), and llvm::DenseMapInfo< CodeViewDebug::LocalVarDef >::getTombstoneKey().
toOpaqueValue()
static uint64_t llvm::CodeViewDebug::LocalVarDef::toOpaqueValue (const LocalVarDef DR) inline static
Definition at line 72 of file CodeViewDebug.h.
References memcpy(), and uint64_t.
Referenced by llvm::DenseMapInfo< CodeViewDebug::LocalVarDef >::getHashValue(), and llvm::DenseMapInfo< CodeViewDebug::LocalVarDef >::isEqual().
Member Data Documentation
CVRegister
uint16_t llvm::CodeViewDebug::LocalVarDef::CVRegister
Register containing the data or the register base of the memory location containing the data.
Definition at line 70 of file CodeViewDebug.h.
DataOffset
int llvm::CodeViewDebug::LocalVarDef::DataOffset
Offset of variable data in memory.
Definition at line 60 of file CodeViewDebug.h.
InMemory
int llvm::CodeViewDebug::LocalVarDef::InMemory
Indicates that variable data is stored in memory relative to the specified register.
Definition at line 57 of file CodeViewDebug.h.
IsSubfield
uint16_t llvm::CodeViewDebug::LocalVarDef::IsSubfield
Non-zero if this is a piece of an aggregate.
Definition at line 63 of file CodeViewDebug.h.
StructOffset
uint16_t llvm::CodeViewDebug::LocalVarDef::StructOffset
Offset into aggregate.
Definition at line 66 of file CodeViewDebug.h.
The documentation for this struct was generated from the following file:
lib/CodeGen/AsmPrinter/CodeViewDebug.h