LLVM: llvm::dxbc::PSV::v2::ResourceBindInfo Struct Reference
llvm::dxbc::PSV::v2::ResourceBindInfo Struct Reference
#include "llvm/BinaryFormat/DXContainer.h"
Public Member Functions
void swapBytes ()
Public Member Functions inherited from llvm::dxbc::PSV::v0::ResourceBindInfo
void swapBytes ()
Public Attributes
uint32_t Kind
uint32_t Flags
Public Attributes inherited from llvm::dxbc::PSV::v0::ResourceBindInfo
uint32_t Type
uint32_t Space
uint32_t LowerBound
uint32_t UpperBound
Detailed Description
Definition at line 365 of file DXContainer.h.
Member Function Documentation
swapBytes()
void llvm::dxbc::PSV::v2::ResourceBindInfo::swapBytes () inline
Definition at line 369 of file DXContainer.h.
References Flags, Kind, llvm::sys::swapByteOrder(), and llvm::dxbc::PSV::v0::ResourceBindInfo::swapBytes().
Referenced by llvm::object::DirectX::PSVRuntimeInfo::ResourceArray::iterator::operator*().
Member Data Documentation
Flags
uint32_t llvm::dxbc::PSV::v2::ResourceBindInfo::Flags
Definition at line 367 of file DXContainer.h.
Referenced by llvm::yaml::MappingTraits< DXContainerYAML::ResourceBindInfo >::mapping(), and swapBytes().
Kind
uint32_t llvm::dxbc::PSV::v2::ResourceBindInfo::Kind
Definition at line 366 of file DXContainer.h.
Referenced by llvm::yaml::MappingTraits< DXContainerYAML::ResourceBindInfo >::mapping(), and swapBytes().
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/DXContainer.h