LLVM: llvm::DXContainerYAML::PSVInfo Struct Reference
llvm::DXContainerYAML::PSVInfo Struct Reference
#include "llvm/ObjectYAML/DXContainerYAML.h"
Public Member Functions
void mapInfoForVersion (yaml::IO &IO)
PSVInfo ()
PSVInfo (const dxbc::PSV::v0::RuntimeInfo *P, uint16_t Stage)
PSVInfo (const dxbc::PSV::v1::RuntimeInfo *P)
PSVInfo (const dxbc::PSV::v2::RuntimeInfo *P)
Public Attributes
uint32_t Version
dxbc::PSV::v2::RuntimeInfo Info
std::vector< ResourceBindInfo > Resources
Detailed Description
Definition at line 76 of file DXContainerYAML.h.
Constructor & Destructor Documentation
PSVInfo() [1/4]
llvm::DXContainerYAML::PSVInfo::PSVInfo ()
Definition at line 46 of file DXContainerYAML.cpp.
References Info.
PSVInfo() [2/4]
llvm::DXContainerYAML::PSVInfo::PSVInfo (const dxbc::PSV::v0::RuntimeInfo * P, uint16_t Stage)
Definition at line 50 of file DXContainerYAML.cpp.
References assert(), Info, llvm::max(), memcpy(), P, and llvm::dxbc::PSV::v1::RuntimeInfo::ShaderStage.
PSVInfo() [3/4]
llvm::DXContainerYAML::PSVInfo::PSVInfo (const dxbc::PSV::v1::RuntimeInfo * P)
Definition at line 63 of file DXContainerYAML.cpp.
References Info, memcpy(), and P.
PSVInfo() [4/4]
llvm::DXContainerYAML::PSVInfo::PSVInfo (const dxbc::PSV::v2::RuntimeInfo * P)
Definition at line 69 of file DXContainerYAML.cpp.
References Info, memcpy(), and P.
Member Function Documentation
mapInfoForVersion()
void llvm::DXContainerYAML::PSVInfo::mapInfoForVersion (yaml::IO & IO)
Definition at line 170 of file DXContainerYAML.cpp.
References llvm::dxbc::PipelinePSVInfo::AS, llvm::dxbc::PixelPSVInfo::DepthOutput, llvm::dxbc::PipelinePSVInfo::DS, llvm::dxbc::getShaderStage(), llvm::dxbc::MeshPSVInfo::GroupSharedBytesDependentOnViewID, llvm::dxbc::MeshPSVInfo::GroupSharedBytesUsed, llvm::dxbc::PipelinePSVInfo::GS, llvm::dxbc::PipelinePSVInfo::HS, Info, llvm::dxbc::HullPSVInfo::InputControlPointCount, llvm::dxbc::DomainPSVInfo::InputControlPointCount, llvm::dxbc::GeometryPSVInfo::InputPrimitive, llvm::dxbc::MeshPSVInfo::MaxOutputPrimitives, llvm::dxbc::MeshPSVInfo::MaxOutputVertices, llvm::dxbc::PipelinePSVInfo::MS, llvm::dxbc::HullPSVInfo::OutputControlPointCount, llvm::dxbc::VertexPSVInfo::OutputPositionPresent, llvm::dxbc::DomainPSVInfo::OutputPositionPresent, llvm::dxbc::GeometryPSVInfo::OutputPositionPresent, llvm::dxbc::GeometryPSVInfo::OutputStreamMask, llvm::dxbc::GeometryPSVInfo::OutputTopology, llvm::dxbc::MeshPSVInfo::PayloadSizeInBytes, llvm::dxbc::AmplificationPSVInfo::PayloadSizeInBytes, llvm::dxbc::PipelinePSVInfo::PS, llvm::dxbc::PixelPSVInfo::SampleFrequency, llvm::dxbc::HullPSVInfo::TessellatorDomain, llvm::dxbc::DomainPSVInfo::TessellatorDomain, llvm::dxbc::HullPSVInfo::TessellatorOutputPrimitive, llvm::IndexedInstrProf::Version, and llvm::dxbc::PipelinePSVInfo::VS.
Referenced by llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping().
Member Data Documentation
Info
dxbc::PSV::v2::RuntimeInfo llvm::DXContainerYAML::PSVInfo::Info
Definition at line 82 of file DXContainerYAML.h.
Referenced by llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping(), and PSVInfo().
Resources
std::vector<ResourceBindInfo> llvm::DXContainerYAML::PSVInfo::Resources
Definition at line 83 of file DXContainerYAML.h.
Referenced by llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping().
Version
uint32_t llvm::DXContainerYAML::PSVInfo::Version
Definition at line 80 of file DXContainerYAML.h.
Referenced by llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping().
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/DXContainerYAML.h
lib/ObjectYAML/DXContainerYAML.cpp