LLVM: llvm::omp::OMPContext Struct Reference
llvm::omp::OMPContext Struct Reference
The context for a source location is made up of active property traits, e.g., device={kind(host)}, and constructs traits which describe the nesting in OpenMP constructs at the location.
#include "llvm/Frontend/OpenMP/OMPContext.h"
Public Member Functions
OMPContext (bool IsDeviceCompilation, Triple TargetTriple)
virtual ~OMPContext ()=default
void addTrait (TraitProperty Property)
void addTrait (TraitSet Set, TraitProperty Property)
virtual bool matchesISATrait (StringRef) const
Hook for users to check if an ISA trait matches.
Public Attributes
BitVector ActiveTraits = BitVector(unsigned(TraitProperty::Last) + 1)
SmallVector< TraitProperty, 8 > ConstructTraits
Detailed Description
The context for a source location is made up of active property traits, e.g., device={kind(host)}, and constructs traits which describe the nesting in OpenMP constructs at the location.
Definition at line 157 of file OMPContext.h.
Constructor & Destructor Documentation
OMPContext()
OMPContext::OMPContext (bool IsDeviceCompilation, Triple TargetTriple)
Definition at line 27 of file OMPContext.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::Triple::aarch64_be, ActiveTraits, llvm::Triple::amdgcn, llvm::Triple::arm, llvm::Triple::armeb, llvm::tgtok::Bit, llvm::dbgs(), DEBUG_TYPE, llvm::Triple::getArch(), llvm::omp::getOpenMPContextTraitPropertyFullName(), LLVM_DEBUG, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::nvptx, llvm::Triple::nvptx64, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::ppcle, llvm::BitVector::set(), llvm::BitVector::set_bits(), llvm::Triple::x86, and llvm::Triple::x86_64.
~OMPContext()
virtual llvm::omp::OMPContext::~OMPContext () virtual default
Member Function Documentation
addTrait() [1/2]
void llvm::omp::OMPContext::addTrait (TraitProperty Property) inline
Definition at line 161 of file OMPContext.h.
References llvm::omp::getOpenMPContextTraitSetForProperty().
addTrait() [2/2]
void llvm::omp::OMPContext::addTrait (TraitSet Set, TraitProperty Property) inline
Definition at line 164 of file OMPContext.h.
References ActiveTraits, ConstructTraits, and llvm::BitVector::set().
matchesISATrait()
virtual bool llvm::omp::OMPContext::matchesISATrait (StringRef) const inline virtual
Hook for users to check if an ISA trait matches.
The trait is described as the string that got parsed and it depends on the target and context if this matches or not.
Definition at line 173 of file OMPContext.h.
Member Data Documentation
ActiveTraits
BitVector llvm::omp::OMPContext::ActiveTraits = BitVector(unsigned(TraitProperty::Last) + 1)
Definition at line 175 of file OMPContext.h.
Referenced by addTrait(), isVariantApplicableInContextHelper(), and OMPContext().
ConstructTraits
SmallVector<TraitProperty, 8> llvm::omp::OMPContext::ConstructTraits
Definition at line 176 of file OMPContext.h.
Referenced by addTrait(), and isVariantApplicableInContextHelper().
The documentation for this struct was generated from the following files:
include/llvm/Frontend/OpenMP/OMPContext.h
lib/Frontend/OpenMP/OMPContext.cpp