LLVM: llvm::IndexedInstrProf::Summary Struct Reference
llvm::IndexedInstrProf::Summary Struct Reference
#include "llvm/ProfileData/InstrProf.h"
Classes
struct Entry
Public Types
enum SummaryFieldKind {
TotalNumFunctions = 0, TotalNumBlocks = 1, MaxFunctionCount = 2, MaxBlockCount = 3,
MaxInternalBlockCount = 4, TotalBlockCount = 5, NumKinds = TotalBlockCount + 1
}
Public Member Functions
Summary ()=delete
Summary (uint32_t Size)
void operator delete (void *ptr)
const uint64_t * getSummaryDataBase () const
uint64_t * getSummaryDataBase ()
const Entry * getCutoffEntryBase () const
Entry * getCutoffEntryBase ()
uint64_t get (SummaryFieldKind K) const
void set (SummaryFieldKind K, uint64_t V)
const Entry & getEntry (uint32_t I) const
void setEntry (uint32_t I, const ProfileSummaryEntry &E)
Static Public Member Functions
static uint32_t getSize (uint32_t NumSumFields, uint32_t NumCutoffEntries)
Public Attributes
uint64_t NumSummaryFields
uint64_t NumCutoffEntries
Detailed Description
Definition at line 1093 of file InstrProf.h.
Member Enumeration Documentation
SummaryFieldKind
enum llvm::IndexedInstrProf::Summary::SummaryFieldKind
Enumerator
TotalNumFunctions
The total number of functions instrumented.
TotalNumBlocks
Total number of instrumented blocks/edges.
MaxFunctionCount
The maximal execution count among all functions.
This field does not exist for profile data from IR based instrumentation.
MaxBlockCount
Max block count of the program.
MaxInternalBlockCount
Max internal block count of the program (excluding entry blocks).
TotalBlockCount
The sum of all instrumented block counts.
NumKinds
Definition at line 1103 of file InstrProf.h.
Constructor & Destructor Documentation
Summary() [1/2]
llvm::IndexedInstrProf::Summary::Summary () delete
Referenced by getSize().
Summary() [2/2]
llvm::IndexedInstrProf::Summary::Summary (uint32_t Size) inline
Definition at line 1127 of file InstrProf.h.
Member Function Documentation
get()
uint64_t llvm::IndexedInstrProf::Summary::get (SummaryFieldKind K) const inline
Definition at line 1153 of file InstrProf.h.
References getSummaryDataBase().
getCutoffEntryBase() [1/2]
Entry* llvm::IndexedInstrProf::Summary::getCutoffEntryBase () inline
Definition at line 1149 of file InstrProf.h.
References getSummaryDataBase(), and NumSummaryFields.
getCutoffEntryBase() [2/2]
const Entry* llvm::IndexedInstrProf::Summary::getCutoffEntryBase () const inline
Definition at line 1144 of file InstrProf.h.
References getSummaryDataBase(), and NumSummaryFields.
Referenced by getEntry(), and setEntry().
getEntry()
const Entry& llvm::IndexedInstrProf::Summary::getEntry (uint32_t I) const inline
Definition at line 1161 of file InstrProf.h.
References getCutoffEntryBase(), and I.
getSize()
static uint32_t llvm::IndexedInstrProf::Summary::getSize (uint32_t NumSumFields, uint32_t NumCutoffEntries) inline static
Definition at line 1131 of file InstrProf.h.
References NumCutoffEntries, Summary(), and uint64_t.
getSummaryDataBase() [1/2]
uint64_t* llvm::IndexedInstrProf::Summary::getSummaryDataBase () inline
Definition at line 1140 of file InstrProf.h.
References uint64_t.
getSummaryDataBase() [2/2]
const uint64_t* llvm::IndexedInstrProf::Summary::getSummaryDataBase () const inline
Definition at line 1136 of file InstrProf.h.
References uint64_t.
Referenced by get(), getCutoffEntryBase(), and set().
operator delete()
void llvm::IndexedInstrProf::Summary::operator delete (void * ptr) inline
Definition at line 1129 of file InstrProf.h.
set()
void llvm::IndexedInstrProf::Summary::set (SummaryFieldKind K, uint64_t V) inline
Definition at line 1157 of file InstrProf.h.
References getSummaryDataBase().
Referenced by setSummary().
setEntry()
void llvm::IndexedInstrProf::Summary::setEntry (uint32_t I, const ProfileSummaryEntry & E) inline
Definition at line 1163 of file InstrProf.h.
References llvm::IndexedInstrProf::Summary::Entry::Cutoff, E, getCutoffEntryBase(), I, llvm::IndexedInstrProf::Summary::Entry::MinBlockCount, and llvm::IndexedInstrProf::Summary::Entry::NumBlocks.
Referenced by setSummary().
Member Data Documentation
NumCutoffEntries
uint64_t llvm::IndexedInstrProf::Summary::NumCutoffEntries
Definition at line 1124 of file InstrProf.h.
Referenced by getSize(), and setSummary().
NumSummaryFields
uint64_t llvm::IndexedInstrProf::Summary::NumSummaryFields
Definition at line 1122 of file InstrProf.h.
Referenced by getCutoffEntryBase(), and setSummary().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/InstrProf.h