LLVM: llvm::PatternMatch::m_SplatOrUndefMask Struct Reference
llvm::PatternMatch::m_SplatOrUndefMask Struct Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
m_SplatOrUndefMask (int &SplatIndex)
bool match (ArrayRef< int > Mask)
Public Attributes
int & SplatIndex
Detailed Description
Definition at line 1535 of file PatternMatch.h.
Constructor & Destructor Documentation
m_SplatOrUndefMask()
llvm::PatternMatch::m_SplatOrUndefMask::m_SplatOrUndefMask (int & SplatIndex) inline
Definition at line 1537 of file PatternMatch.h.
Member Function Documentation
match()
bool llvm::PatternMatch::m_SplatOrUndefMask::match (ArrayRef< int > Mask) inline
Definition at line 1538 of file PatternMatch.h.
References llvm::all_of(), llvm::find_if(), First, llvm::BitmaskEnumDetail::Mask(), and SplatIndex.
Member Data Documentation
SplatIndex
int& llvm::PatternMatch::m_SplatOrUndefMask::SplatIndex
Definition at line 1536 of file PatternMatch.h.
Referenced by match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h