LLVM: llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD Struct Reference
llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD Struct Reference
Public Member Functions
NormalizedTBD (IO &IO)
NormalizedTBD (IO &IO, const InterfaceFile *&File)
TargetList synthesizeTargets (ArchitectureSet Architectures, const PlatformSet &Platforms)
const InterfaceFile * denormalize (IO &IO)
StringRef copyString (StringRef String)
Public Attributes
llvm::BumpPtrAllocator Allocator
std::vector< Architecture > Architectures
std::vector< UUID > UUIDs
PlatformSet Platforms
StringRef InstallName
PackedVersion CurrentVersion
PackedVersion CompatibilityVersion
SwiftVersion SwiftABIVersion {0}
ObjCConstraintType ObjCConstraint {ObjCConstraintType::None}
TBDFlags Flags {TBDFlags::None}
StringRef ParentUmbrella
std::vector< ExportSection > Exports
std::vector< UndefinedSection > Undefineds
Detailed Description
Definition at line 436 of file TextStub.cpp.
Constructor & Destructor Documentation
NormalizedTBD() [1/2]
llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::NormalizedTBD (IO & IO) inline explicit
Definition at line 437 of file TextStub.cpp.
NormalizedTBD() [2/2]
llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::NormalizedTBD (IO & IO, const InterfaceFile *& File) inline
Definition at line 438 of file TextStub.cpp.
References llvm::coverage::CurrentVersion, llvm::MachO::Symbol::getArchitectures(), llvm::MachO::Symbol::getKind(), llvm::MachO::Symbol::getName(), llvm::MachO::Symbol::isThreadLocalValue(), llvm::MachO::Symbol::isWeakDefined(), llvm::MachO::Symbol::isWeakReferenced(), Library, move, llvm::None, llvm::sort(), llvm::StringRef::str(), and llvm::MachO::TBD_V3.
Member Function Documentation
copyString()
StringRef llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::copyString (StringRef String) inline
Definition at line 722 of file TextStub.cpp.
References Allocator, memcpy(), and Ptr.
denormalize()
const InterfaceFile* llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::denormalize (IO & IO) inline
Definition at line 612 of file TextStub.cpp.
References assert(), llvm::coverage::CurrentVersion, llvm::Lib, llvm::MachO::TBD_V1, and llvm::MachO::TBD_V3.
synthesizeTargets()
TargetList llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::synthesizeTargets (ArchitectureSet Architectures, const PlatformSet & Platforms) inline
Definition at line 595 of file TextStub.cpp.
References llvm::SmallVectorImpl< T >::emplace_back(), llvm::MachO::ArchitectureSet::hasX86(), llvm::MachO::mapToPlatformType(), and llvm::MachO::PLATFORM_MACCATALYST.
Member Data Documentation
Allocator
llvm::BumpPtrAllocator llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::Allocator
Definition at line 721 of file TextStub.cpp.
Architectures
std::vector<Architecture> llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::Architectures
Definition at line 731 of file TextStub.cpp.
CompatibilityVersion
PackedVersion llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::CompatibilityVersion
Definition at line 736 of file TextStub.cpp.
CurrentVersion
PackedVersion llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::CurrentVersion
Definition at line 735 of file TextStub.cpp.
Exports
std::vector<ExportSection> llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::Exports
Definition at line 741 of file TextStub.cpp.
Flags
TBDFlags llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::Flags {TBDFlags::None}
Definition at line 739 of file TextStub.cpp.
InstallName
StringRef llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::InstallName
Definition at line 734 of file TextStub.cpp.
ObjCConstraint
ObjCConstraintType llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::ObjCConstraint {ObjCConstraintType::None}
Definition at line 738 of file TextStub.cpp.
ParentUmbrella
StringRef llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::ParentUmbrella
Definition at line 740 of file TextStub.cpp.
Platforms
PlatformSet llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::Platforms
Definition at line 733 of file TextStub.cpp.
SwiftABIVersion
SwiftVersion llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::SwiftABIVersion {0}
Definition at line 737 of file TextStub.cpp.
Undefineds
std::vector<UndefinedSection> llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::Undefineds
Definition at line 742 of file TextStub.cpp.
UUIDs
std::vector<UUID> llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::UUIDs
Definition at line 732 of file TextStub.cpp.
The documentation for this struct was generated from the following file:
lib/TextAPI/TextStub.cpp