LLVM: llvm::GraphTraits< DOTFuncMSSAInfo * > Struct Reference
llvm::GraphTraits< DOTFuncMSSAInfo * > Struct Reference
Public Types
using nodes_iterator = pointer_iterator< Function::const_iterator >
Public Types inherited from llvm::GraphTraits< const BasicBlock * >
using NodeRef = const BasicBlock *
using ChildIteratorType = const_succ_iterator
Static Public Member Functions
static NodeRef getEntryNode (DOTFuncMSSAInfo *CFGInfo)
static nodes_iterator nodes_begin (DOTFuncMSSAInfo *CFGInfo)
static nodes_iterator nodes_end (DOTFuncMSSAInfo *CFGInfo)
static size_t size (DOTFuncMSSAInfo *CFGInfo)
Static Public Member Functions inherited from llvm::GraphTraits< const BasicBlock * >
static NodeRef getEntryNode (const BasicBlock *BB)
static ChildIteratorType child_begin (NodeRef N)
static ChildIteratorType child_end (NodeRef N)
Detailed Description
Definition at line 2250 of file MemorySSA.cpp.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< DOTFuncMSSAInfo * >::nodes_iterator = pointer_iterator<Function::const_iterator>
Definition at line 2256 of file MemorySSA.cpp.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< DOTFuncMSSAInfo * >::getEntryNode (DOTFuncMSSAInfo * CFGInfo) inline static
Definition at line 2251 of file MemorySSA.cpp.
References llvm::Function::getEntryBlock(), and DOTFuncMSSAInfo::getFunction().
nodes_begin()
static nodes_iterator llvm::GraphTraits< DOTFuncMSSAInfo * >::nodes_begin (DOTFuncMSSAInfo * CFGInfo) inline static
Definition at line 2258 of file MemorySSA.cpp.
References llvm::Function::begin(), and DOTFuncMSSAInfo::getFunction().
nodes_end()
static nodes_iterator llvm::GraphTraits< DOTFuncMSSAInfo * >::nodes_end (DOTFuncMSSAInfo * CFGInfo) inline static
Definition at line 2262 of file MemorySSA.cpp.
References llvm::Function::end(), and DOTFuncMSSAInfo::getFunction().
size()
static size_t llvm::GraphTraits< DOTFuncMSSAInfo * >::size (DOTFuncMSSAInfo * CFGInfo) inline static
Definition at line 2266 of file MemorySSA.cpp.
References DOTFuncMSSAInfo::getFunction(), and llvm::Function::size().
The documentation for this struct was generated from the following file:
lib/Analysis/MemorySSA.cpp