LLVM: lib/Transforms/IPO/SyntheticCountsPropagation.cpp File Reference
SyntheticCountsPropagation.cpp File Reference
#include "llvm/Transforms/IPO/SyntheticCountsPropagation.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/SyntheticCountsUtils.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "synthetic-counts-propagation"
Typedefs
using Scaled64 = ScaledNumber< uint64_t >
using ProfileCount = Function::ProfileCount
Functions
cl::opt< int > llvm::InitialSyntheticCount ("initial-synthetic-count", cl::Hidden, cl::init(10), cl::desc("Initial value of synthetic entry count"))
static void initializeCounts (Module &M, function_ref< void(Function *, uint64_t)> SetCount)
Variables
static cl::opt< int > InlineSyntheticCount ("inline-synthetic-count", cl::Hidden, cl::init(15), cl::desc("Initial synthetic entry count for inline functions."))
Initial synthetic count assigned to inline functions.
static cl::opt< int > ColdSyntheticCount ("cold-synthetic-count", cl::Hidden, cl::init(5), cl::desc("Initial synthetic entry count for cold functions."))
Initial synthetic count assigned to cold functions.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "synthetic-counts-propagation"
Definition at line 40 of file SyntheticCountsPropagation.cpp.
Typedef Documentation
ProfileCount
using ProfileCount = Function::ProfileCount
Definition at line 38 of file SyntheticCountsPropagation.cpp.
Scaled64
using Scaled64 = ScaledNumber<uint64_t>
Definition at line 37 of file SyntheticCountsPropagation.cpp.
Function Documentation
initializeCounts()
static void initializeCounts (Module & M, function_ref< void(Function *, uint64_t)> SetCount) static
Definition at line 60 of file SyntheticCountsPropagation.cpp.
References llvm::CallingConv::Cold, ColdSyntheticCount, F, llvm::InitialSyntheticCount, InlineSyntheticCount, M, and uint64_t.
Referenced by llvm::SyntheticCountsPropagation::run().
Variable Documentation
ColdSyntheticCount
cl::opt<int> ColdSyntheticCount("cold-synthetic-count", cl::Hidden, cl::init(5), cl::desc("Initial synthetic entry count for cold functions.")) static
Initial synthetic count assigned to cold functions.
Referenced by initializeCounts().
InlineSyntheticCount
cl::opt<int> InlineSyntheticCount("inline-synthetic-count", cl::Hidden, cl::init(15), cl::desc("Initial synthetic entry count for inline functions.")) static
Initial synthetic count assigned to inline functions.
Referenced by initializeCounts().