LLVM: lib/Target/SystemZ/SystemZLongBranch.cpp File Reference
SystemZLongBranch.cpp File Reference
#include "SystemZ.h"
#include "SystemZInstrInfo.h"
#include "SystemZTargetMachine.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/Support/ErrorHandling.h"
#include <cassert>
#include <cstdint>
Macros
#define DEBUG_TYPE "systemz-long-branch"
Functions
STATISTIC (LongBranches, "Number of long branches.")
INITIALIZE_PASS (SystemZLongBranch, DEBUG_TYPE, "SystemZ Long Branch", false, false) void SystemZLongBranch
static unsigned getInstSizeInBytes (const MachineInstr &MI, const SystemZInstrInfo *TII)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemz-long-branch"
Definition at line 73 of file SystemZLongBranch.cpp.
Function Documentation
getInstSizeInBytes()
static unsigned getInstSizeInBytes (const MachineInstr & MI, const SystemZInstrInfo * TII) static
Definition at line 214 of file SystemZLongBranch.cpp.
References assert(), llvm::ISD::MEMBARRIER, MI, llvm::ISD::PATCHPOINT, llvm::ISD::STACKMAP, and TII.
INITIALIZE_PASS()
INITIALIZE_PASS (SystemZLongBranch , DEBUG_TYPE , "SystemZ Long Branch" , false , false)
Definition at line 176 of file SystemZLongBranch.cpp.
References llvm::alignTo(), llvm::Log2(), and uint64_t.
STATISTIC()
STATISTIC (LongBranches , "Number of long branches.")