LLVM: lib/Target/SystemZ/SystemZFrameLowering.cpp File Reference
SystemZFrameLowering.cpp File Reference
#include "SystemZFrameLowering.h"
#include "SystemZCallingConv.h"
#include "SystemZInstrBuilder.h"
#include "SystemZInstrInfo.h"
#include "SystemZMachineFunctionInfo.h"
#include "SystemZRegisterInfo.h"
#include "SystemZSubtarget.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Function.h"
#include "llvm/Target/TargetMachine.h"
Functions
static void addSavedGPR (MachineBasicBlock &MBB, MachineInstrBuilder &MIB, unsigned GPR64, bool IsImplicit)
static void emitIncrement (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, const DebugLoc &DL, Register Reg, int64_t NumBytes, const TargetInstrInfo *TII)
static void buildCFAOffs (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, int Offset, const SystemZInstrInfo *ZII)
static void buildDefCFAReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const DebugLoc &DL, unsigned Reg, const SystemZInstrInfo *ZII)
static bool isXPLeafCandidate (const MachineFunction &MF)
Function Documentation
addSavedGPR()
static void addSavedGPR (MachineBasicBlock & MBB, MachineInstrBuilder & MIB, unsigned GPR64, bool IsImplicit) static
Definition at line 312 of file SystemZFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::getImplRegState(), llvm::getKillRegState(), llvm::MachineBasicBlock::getParent(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetRegisterInfo::getSubReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::isLiveIn(), and MBB.
Referenced by llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), and llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters().
buildCFAOffs()
static void buildCFAOffs (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, int Offset, const SystemZInstrInfo * ZII) static
Definition at line 513 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::BuildMI(), llvm::MCCFIInstruction::cfiDefCfaOffset(), DL, llvm::MachineBasicBlock::getParent(), MBB, MBBI, and llvm::Offset.
Referenced by llvm::SystemZELFFrameLowering::emitPrologue(), and llvm::SystemZELFFrameLowering::inlineStackProbe().
buildDefCFAReg()
static void buildDefCFAReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, const DebugLoc & DL, unsigned Reg, const SystemZInstrInfo * ZII) static
Definition at line 524 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::BuildMI(), llvm::MCCFIInstruction::createDefCfaRegister(), DL, llvm::MachineModuleInfo::getContext(), llvm::MachineFunction::getMMI(), llvm::MachineBasicBlock::getParent(), llvm::MCContext::getRegisterInfo(), MBB, MBBI, and MRI.
Referenced by llvm::SystemZELFFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::inlineStackProbe(), and llvm::PPCFrameLowering::inlineStackProbe().
emitIncrement()
static void emitIncrement (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, const DebugLoc & DL, Register Reg, int64_t NumBytes, const TargetInstrInfo * TII) static
Definition at line 485 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, MBB, MBBI, MI, TII, and uint64_t.
Referenced by llvm::SystemZELFFrameLowering::emitEpilogue(), llvm::SystemZXPLINKFrameLowering::emitEpilogue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::SystemZXPLINKFrameLowering::emitPrologue(), and llvm::SystemZELFFrameLowering::inlineStackProbe().
isXPLeafCandidate()
static bool isXPLeafCandidate (const MachineFunction & MF) static
Definition at line 914 of file SystemZFrameLowering.cpp.
References llvm::MachineFrameInfo::adjustsStack(), llvm::MachineFrameInfo::estimateStackSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getRegInfo(), llvm::SystemZSubtarget::getSpecialRegisters(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasCalls(), llvm::Function::hasFnAttribute(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineRegisterInfo::isPhysRegModified(), and MRI.
Referenced by llvm::SystemZXPLINKFrameLowering::assignCalleeSavedSpillSlots().