LLVM: lib/Target/SystemZ/SystemZTargetTransformInfo.cpp File Reference
SystemZTargetTransformInfo.cpp File Reference
#include "SystemZTargetTransformInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/CostTable.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "systemztti"
Functions
static bool isUsedAsMemCpySource (const Value *V, bool &OtherUse)
static unsigned getScalarSizeInBits (Type *Ty)
static unsigned getNumVectorRegs (Type *Ty)
static unsigned getElSizeLog2Diff (Type *Ty0, Type *Ty1)
static Type * getCmpOpsType (const Instruction *I, unsigned VF=1)
static unsigned getOperandsExtensionCost (const Instruction *I)
static bool isBswapIntrinsicCall (const Value *V)
static int getVectorIntrinsicInstrCost (Intrinsic::ID ID, Type *RetTy)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemztti"
Definition at line 25 of file SystemZTargetTransformInfo.cpp.
Function Documentation
getCmpOpsType()
static Type* getCmpOpsType (const Instruction * I, unsigned VF = 1) static
Definition at line 716 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::FixedVectorType::get(), llvm::Type::getScalarType(), I, and llvm::Type::isVectorTy().
Referenced by llvm::SystemZTTIImpl::getBoolVecToIntConversionCost(), llvm::SystemZTTIImpl::getCastInstrCost(), and llvm::SystemZTTIImpl::getCmpSelInstrCost().
getElSizeLog2Diff()
static unsigned getElSizeLog2Diff (Type * Ty0, Type * Ty1) static
Definition at line 638 of file SystemZTargetTransformInfo.cpp.
References llvm::M68kBeads::Bits1, llvm::Type::getScalarSizeInBits(), and llvm::Log2_32().
Referenced by llvm::SystemZTTIImpl::getCastInstrCost(), llvm::SystemZTTIImpl::getVectorBitmaskConversionCost(), and llvm::SystemZTTIImpl::getVectorTruncCost().
getNumVectorRegs()
static unsigned getNumVectorRegs (Type * Ty) static
Definition at line 413 of file SystemZTargetTransformInfo.cpp.
References assert(), and getScalarSizeInBits().
Referenced by llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::SystemZTTIImpl::getBoolVecToIntConversionCost(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::SystemZTTIImpl::getInterleavedMemoryOpCost(), llvm::SystemZTTIImpl::getMemoryOpCost(), llvm::SystemZTTIImpl::getShuffleCost(), llvm::SystemZTTIImpl::getVectorBitmaskConversionCost(), getVectorIntrinsicInstrCost(), and llvm::SystemZTTIImpl::getVectorTruncCost().
getOperandsExtensionCost()
static unsigned getOperandsExtensionCost (const Instruction * I) static
Definition at line 909 of file SystemZTargetTransformInfo.cpp.
References I.
Referenced by llvm::SystemZTTIImpl::getCmpSelInstrCost().
getScalarSizeInBits()
static unsigned getScalarSizeInBits (Type * Ty) static
Definition at line 403 of file SystemZTargetTransformInfo.cpp.
References assert(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by llvm::MachineIRBuilder::buildConstant(), llvm::computeMinimumValueSizes(), llvm::SystemZTTIImpl::getInterleavedMemoryOpCost(), getNumVectorRegs(), llvm::SystemZTTIImpl::getVectorInstrCost(), llvm::SystemZTTIImpl::isFoldableLoad(), opMustUseVOP3Encoding(), llvm::InstCombinerImpl::visitLShr(), and llvm::InstCombinerImpl::visitZExt().
getVectorIntrinsicInstrCost()
static int getVectorIntrinsicInstrCost (Intrinsic::ID ID, Type * RetTy) static
Definition at line 1242 of file SystemZTargetTransformInfo.cpp.
References getNumVectorRegs(), and llvm::Type::isVectorTy().
Referenced by llvm::SystemZTTIImpl::getIntrinsicInstrCost().
isBswapIntrinsicCall()
static bool isBswapIntrinsicCall (const Value * V) static
Definition at line 1106 of file SystemZTargetTransformInfo.cpp.
References F, and I.
Referenced by llvm::SystemZTTIImpl::getMemoryOpCost().
isUsedAsMemCpySource()
static bool isUsedAsMemCpySource (const Value * V, bool & OtherUse) static
Definition at line 33 of file SystemZTargetTransformInfo.cpp.
References llvm::Value::users().
Referenced by llvm::SystemZTTIImpl::adjustInliningThreshold().