LLVM: lib/CodeGen/TargetInstrInfo.cpp File Reference
TargetInstrInfo.cpp File Reference
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/MachineCombinerPattern.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/MachineScheduler.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/CodeGen/ScoreboardHazardRecognizer.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSchedule.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInstrItineraries.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
static bool isAsmComment (const char *Str, const MCAsmInfo &MAI)
static const TargetRegisterClass * canFoldCopy (const MachineInstr &MI, unsigned FoldIdx)
static MachineInstr * foldPatchpoint (MachineFunction &MF, MachineInstr &MI, ArrayRef< unsigned > Ops, int FrameIndex, const TargetInstrInfo &TII)
static std::pair< bool, bool > mustSwapOperands (MachineCombinerPattern Pattern)
Variables
static cl::opt< bool > DisableHazardRecognizer ("disable-sched-hazard", cl::Hidden, cl::init(false), cl::desc("Disable hazard detection during preRA scheduling"))
Function Documentation
canFoldCopy()
static const TargetRegisterClass* canFoldCopy (const MachineInstr & MI, unsigned FoldIdx) static
Definition at line 441 of file TargetInstrInfo.cpp.
References assert(), llvm::TargetRegisterClass::contains(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineOperand::getSubReg(), llvm::TargetRegisterClass::hasSubClassEq(), llvm::Register::isPhysical(), llvm::Register::isVirtual(), MI, and MRI.
Referenced by llvm::TargetInstrInfo::foldMemoryOperand().
foldPatchpoint()
static MachineInstr* foldPatchpoint (MachineFunction & MF, MachineInstr & MI, ArrayRef< unsigned > Ops, int FrameIndex, const TargetInstrInfo & TII) static
Definition at line 492 of file TargetInstrInfo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), assert(), llvm::MachineFunction::CreateMachineInstr(), llvm::numbers::e, llvm::ISD::FrameIndex, llvm::MachineInstr::getNumOperands(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::getSubReg(), i, llvm::is_contained(), MI, llvm::report_fatal_error(), llvm::MachineInstr::tieOperands(), and TII.
Referenced by llvm::TargetInstrInfo::foldMemoryOperand().
isAsmComment()
static bool isAsmComment (const char * Str, const MCAsmInfo & MAI) static
Definition at line 80 of file TargetInstrInfo.cpp.
References llvm::StringRef::data(), llvm::MCAsmInfo::getCommentString(), and llvm::StringRef::size().
Referenced by llvm::TargetInstrInfo::getInlineAsmLength().
mustSwapOperands()
static std::pair<bool, bool> mustSwapOperands (MachineCombinerPattern Pattern) static
Definition at line 904 of file TargetInstrInfo.cpp.
References llvm_unreachable, llvm::REASSOC_AX_BY, llvm::REASSOC_AX_YB, llvm::REASSOC_XA_BY, and llvm::REASSOC_XA_YB.
Referenced by llvm::TargetInstrInfo::reassociateOps().
Variable Documentation
DisableHazardRecognizer
cl::opt<bool> DisableHazardRecognizer("disable-sched-hazard", cl::Hidden, cl::init(false), cl::desc("Disable hazard detection during preRA scheduling")) static
Referenced by llvm::TargetInstrInfo::usePreRAHazardRecognizer().