LLVM: lib/CodeGen/TargetLoweringObjectFileImpl.cpp File Reference
TargetLoweringObjectFileImpl.cpp File Reference
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/BinaryFormat/Wasm.h"
#include "llvm/CodeGen/BasicBlockSectionUtils.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PseudoProbe.h"
#include "llvm/IR/Type.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionGOFF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCSectionXCOFF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Support/Base64.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/TargetParser/Triple.h"
#include <cassert>
#include <string>
Functions
static void GetObjCImageInfo (Module &M, unsigned &Version, unsigned &Flags, StringRef &Section)
static SectionKind getELFKindForNamedSection (StringRef Name, SectionKind K)
static bool hasPrefix (StringRef SectionName, StringRef Prefix)
static unsigned getELFSectionType (StringRef Name, SectionKind K)
static unsigned getELFSectionFlags (SectionKind K)
static const Comdat * getELFComdat (const GlobalValue *GV)
static const MCSymbolELF * getLinkedToSymbol (const GlobalObject *GO, const TargetMachine &TM)
static unsigned getEntrySizeForKind (SectionKind Kind)
static StringRef getSectionPrefixForGlobal (SectionKind Kind)
Return the section prefix name used by options FunctionsSections and DataSections.
static SmallString< 128 > getELFSectionNameForGlobal (const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, unsigned EntrySize, bool UniqueSectionName)
static unsigned calcUniqueIDUpdateFlagsAndSize (const GlobalObject *GO, StringRef SectionName, SectionKind Kind, const TargetMachine &TM, MCContext &Ctx, Mangler &Mang, unsigned &Flags, unsigned &EntrySize, unsigned &NextUniqueID, const bool Retain, const bool ForceUnique)
Calculate an appropriate unique ID for a section, and update Flags, EntrySize and NextUniqueID where appropriate.
static MCSection * selectExplicitSectionGlobal (const GlobalObject *GO, SectionKind Kind, const TargetMachine &TM, MCContext &Ctx, Mangler &Mang, unsigned &NextUniqueID, bool Retain, bool ForceUnique)
static MCSectionELF * selectELFSectionForGlobal (MCContext &Ctx, const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, bool EmitUniqueSection, unsigned Flags, unsigned *NextUniqueID, const MCSymbolELF *AssociatedSymbol)
static MCSection * selectELFSectionForGlobal (MCContext &Ctx, const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, bool Retain, bool EmitUniqueSection, unsigned Flags, unsigned *NextUniqueID)
static MCSectionELF * getStaticStructorSection (MCContext &Ctx, bool UseInitArray, bool IsCtor, unsigned Priority, const MCSymbol *KeySym)
static void checkMachOComdat (const GlobalValue *GV)
static bool canUsePrivateLabel (const MCAsmInfo &AsmInfo, const MCSection &Section)
static unsigned getCOFFSectionFlags (SectionKind K, const TargetMachine &TM)
static const GlobalValue * getComdatGVForCOFF (const GlobalValue *GV)
static int getSelectionForCOFF (const GlobalValue *GV)
static StringRef getCOFFSectionNameForUniqueGlobal (SectionKind Kind)
static MCSectionCOFF * getCOFFStaticStructorSection (MCContext &Ctx, const Triple &T, bool IsCtor, unsigned Priority, const MCSymbol *KeySym, MCSectionCOFF *Default)
static std::string APIntToHexString (const APInt &AI)
static std::string scalarConstantToHexString (const Constant *C)
static const Comdat * getWasmComdat (const GlobalValue *GV)
static unsigned getWasmSectionFlags (SectionKind K)
static MCSectionWasm * selectWasmSectionForGlobal (MCContext &Ctx, const GlobalObject *GO, SectionKind Kind, Mangler &Mang, const TargetMachine &TM, bool EmitUniqueSection, unsigned *NextUniqueID)
Function Documentation
APIntToHexString()
static std::string APIntToHexString (const APInt & AI) static
Definition at line 1988 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::dwarf::toString(), and llvm::transform().
Referenced by scalarConstantToHexString().
calcUniqueIDUpdateFlagsAndSize()
static unsigned calcUniqueIDUpdateFlagsAndSize (const GlobalObject * GO, StringRef SectionName, SectionKind Kind, const TargetMachine & TM, MCContext & Ctx, Mangler & Mang, unsigned & Flags, unsigned & EntrySize, unsigned & NextUniqueID, const bool Retain, const bool ForceUnique) static
Calculate an appropriate unique ID for a section, and update Flags, EntrySize and NextUniqueID where appropriate.
Definition at line 685 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCAsmInfo::binutilsIsAtLeast(), llvm::MCContext::GenericSectionID, llvm::MCContext::getAsmInfo(), getELFSectionNameForGlobal(), llvm::MCContext::getELFUniqueIDForEntsize(), llvm::GlobalObject::getMetadata(), llvm::MCContext::isELFGenericMergeableSection(), llvm::MCContext::isELFImplicitMergeableSectionNamePrefix(), llvm::ELF::SHF_GNU_RETAIN, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_SUNW_NODISCARD, TM, and llvm::MCAsmInfo::useIntegratedAssembler().
Referenced by selectExplicitSectionGlobal().
canUsePrivateLabel()
static bool canUsePrivateLabel (const MCAsmInfo & AsmInfo, const MCSection & Section) static
Definition at line 1520 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCAsmInfo::isSectionAtomizableBySymbols().
Referenced by llvm::TargetLoweringObjectFileMachO::getNameWithPrefix().
checkMachOComdat()
static void checkMachOComdat (const GlobalValue * GV) static
Definition at line 1252 of file TargetLoweringObjectFileImpl.cpp.
References llvm::GlobalValue::getComdat(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
getCOFFSectionFlags()
static unsigned getCOFFSectionFlags (SectionKind K, const TargetMachine & TM) static
Definition at line 1550 of file TargetLoweringObjectFileImpl.cpp.
References llvm::COFF::IMAGE_SCN_CNT_CODE, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SCN_LNK_REMOVE, llvm::COFF::IMAGE_SCN_MEM_16BIT, llvm::COFF::IMAGE_SCN_MEM_DISCARDABLE, llvm::COFF::IMAGE_SCN_MEM_EXECUTE, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, llvm::SectionKind::isBSS(), llvm::SectionKind::isExclude(), llvm::SectionKind::isMetadata(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), isThumb(), llvm::SectionKind::isWriteable(), llvm::Triple::thumb, and TM.
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getCOFFSectionNameForUniqueGlobal()
static StringRef getCOFFSectionNameForUniqueGlobal (SectionKind Kind) static
Definition at line 1658 of file TargetLoweringObjectFileImpl.cpp.
Referenced by llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getCOFFStaticStructorSection()
static MCSectionCOFF* getCOFFStaticStructorSection (MCContext & Ctx, const Triple & T, bool IsCtor, unsigned Priority, const MCSymbol * KeySym, MCSectionCOFF * Default) static
Definition at line 1892 of file TargetLoweringObjectFileImpl.cpp.
References llvm::format(), llvm::MCContext::getAssociativeCOFFSection(), llvm::MCContext::getCOFFSection(), llvm::SectionKind::getData(), llvm::SectionKind::getReadOnly(), llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, and OS.
Referenced by llvm::TargetLoweringObjectFileCOFF::getStaticCtorSection(), and llvm::TargetLoweringObjectFileCOFF::getStaticDtorSection().
getComdatGVForCOFF()
static const GlobalValue* getComdatGVForCOFF (const GlobalValue * GV) static
Definition at line 1589 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::GlobalValue::getComdat(), llvm::Module::getNamedValue(), llvm::GlobalValue::getParent(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), getSelectionForCOFF(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getELFComdat()
static const Comdat* getELFComdat (const GlobalValue * GV) static
Definition at line 562 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, llvm::GlobalValue::getComdat(), llvm::Comdat::NoDeduplicate, and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileELF::getSectionForLSDA(), selectELFSectionForGlobal(), and selectExplicitSectionGlobal().
getELFKindForNamedSection()
static SectionKind getELFKindForNamedSection (StringRef Name, SectionKind K) static
Definition at line 459 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Triple::ELF, llvm::SectionKind::getBSS(), llvm::getInstrProfSectionName(), llvm::SectionKind::getMetadata(), llvm::SectionKind::getThreadBSS(), and llvm::SectionKind::getThreadData().
Referenced by selectExplicitSectionGlobal().
getELFSectionFlags()
static unsigned getELFSectionFlags (SectionKind K) static
Definition at line 532 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isExclude(), llvm::SectionKind::isExecuteOnly(), llvm::SectionKind::isMergeableConst(), llvm::SectionKind::isMergeableCString(), llvm::SectionKind::isMetadata(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), llvm::SectionKind::isWriteable(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_ARM_PURECODE, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_TLS, and llvm::ELF::SHF_WRITE.
Referenced by llvm::TargetLoweringObjectFileELF::getUniqueSectionForFunction(), selectExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
getELFSectionNameForGlobal()
static SmallString<128> getELFSectionNameForGlobal (const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, unsigned EntrySize, bool UniqueSectionName) static
Definition at line 632 of file TargetLoweringObjectFileImpl.cpp.
References F, llvm::Module::getDataLayout(), llvm::GlobalValue::getParent(), llvm::DataLayout::getPreferredAlign(), getSectionPrefixForGlobal(), llvm::cl::Prefix, TM, and llvm::Align::value().
Referenced by calcUniqueIDUpdateFlagsAndSize(), and selectELFSectionForGlobal().
getELFSectionType()
static unsigned getELFSectionType (StringRef Name, SectionKind K) static
Definition at line 507 of file TargetLoweringObjectFileImpl.cpp.
References hasPrefix(), llvm::SectionKind::isBSS(), llvm::SectionKind::isThreadBSS(), llvm::ELF::SHT_FINI_ARRAY, llvm::ELF::SHT_INIT_ARRAY, llvm::ELF::SHT_LLVM_OFFLOADING, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_PREINIT_ARRAY, and llvm::ELF::SHT_PROGBITS.
Referenced by selectELFSectionForGlobal(), and selectExplicitSectionGlobal().
getEntrySizeForKind()
static unsigned getEntrySizeForKind (SectionKind Kind) static
Definition at line 587 of file TargetLoweringObjectFileImpl.cpp.
References assert().
Referenced by selectELFSectionForGlobal(), selectExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal().
getLinkedToSymbol()
static const MCSymbolELF* getLinkedToSymbol (const GlobalObject * GO, const TargetMachine & TM) static
Definition at line 576 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MDOperand::get(), llvm::GlobalObject::getMetadata(), llvm::MDNode::getOperand(), and TM.
Referenced by selectELFSectionForGlobal(), and selectExplicitSectionGlobal().
GetObjCImageInfo()
static void GetObjCImageInfo (Module & M, unsigned & Version, unsigned & Flags, StringRef & Section) static
Definition at line 74 of file TargetLoweringObjectFileImpl.cpp.
References M, llvm::Module::Require, and llvm::IndexedInstrProf::Version.
Referenced by llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), and llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata().
getSectionPrefixForGlobal()
static StringRef getSectionPrefixForGlobal (SectionKind Kind) static
Return the section prefix name used by options FunctionsSections and DataSections.
Definition at line 613 of file TargetLoweringObjectFileImpl.cpp.
References llvm_unreachable.
Referenced by getELFSectionNameForGlobal(), and selectWasmSectionForGlobal().
getSelectionForCOFF()
static int getSelectionForCOFF (const GlobalValue * GV) static
Definition at line 1606 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, llvm::Comdat::ExactMatch, llvm::GlobalValue::getAliaseeObject(), llvm::GlobalValue::getComdat(), getComdatGVForCOFF(), llvm::COFF::IMAGE_COMDAT_SELECT_ANY, llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, llvm::COFF::IMAGE_COMDAT_SELECT_EXACT_MATCH, llvm::COFF::IMAGE_COMDAT_SELECT_LARGEST, llvm::COFF::IMAGE_COMDAT_SELECT_NODUPLICATES, llvm::COFF::IMAGE_COMDAT_SELECT_SAME_SIZE, llvm::Comdat::Largest, llvm::Comdat::NoDeduplicate, and llvm::Comdat::SameSize.
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
getStaticStructorSection()
static MCSectionELF* getStaticStructorSection (MCContext & Ctx, bool UseInitArray, bool IsCtor, unsigned Priority, const MCSymbol * KeySym) static
Definition at line 1056 of file TargetLoweringObjectFileImpl.cpp.
References llvm::format(), llvm::MCContext::getELFSection(), llvm::MCSymbol::getName(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_FINI_ARRAY, llvm::ELF::SHT_INIT_ARRAY, and llvm::ELF::SHT_PROGBITS.
Referenced by llvm::TargetLoweringObjectFileELF::getStaticCtorSection(), and llvm::TargetLoweringObjectFileELF::getStaticDtorSection().
getWasmComdat()
static const Comdat* getWasmComdat (const GlobalValue * GV) static
Definition at line 2070 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, llvm::GlobalValue::getComdat(), and llvm::report_fatal_error().
Referenced by llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), and selectWasmSectionForGlobal().
getWasmSectionFlags()
static unsigned getWasmSectionFlags (SectionKind K) static
Definition at line 2083 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isMergeableCString(), llvm::SectionKind::isThreadLocal(), llvm::wasm::WASM_SEG_FLAG_STRINGS, and llvm::wasm::WASM_SEG_FLAG_TLS.
Referenced by llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), and selectWasmSectionForGlobal().
hasPrefix()
static bool hasPrefix (StringRef SectionName, StringRef Prefix) static
Definition at line 502 of file TargetLoweringObjectFileImpl.cpp.
References llvm::cl::Prefix.
Referenced by getELFSectionType().
scalarConstantToHexString()
static std::string scalarConstantToHexString (const Constant * C) static
Definition at line 1999 of file TargetLoweringObjectFileImpl.cpp.
References APIntToHexString(), E, llvm::Type::getArrayNumElements(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getZero(), and I.
Referenced by llvm::TargetLoweringObjectFileCOFF::getSectionForConstant().
selectELFSectionForGlobal() [1/2]
static MCSectionELF* selectELFSectionForGlobal (MCContext & Ctx, const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, bool EmitUniqueSection, unsigned Flags, unsigned * NextUniqueID, const MCSymbolELF * AssociatedSymbol) static
Definition at line 839 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, llvm::MCContext::GenericSectionID, getELFComdat(), llvm::MCContext::getELFSection(), getELFSectionNameForGlobal(), getELFSectionType(), getEntrySizeForKind(), llvm::ELF::SHF_GROUP, and TM.
Referenced by llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileELF::getUniqueSectionForFunction(), selectELFSectionForGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
selectELFSectionForGlobal() [2/2]
static MCSection* selectELFSectionForGlobal (MCContext & Ctx, const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, bool Retain, bool EmitUniqueSection, unsigned Flags, unsigned * NextUniqueID) static
Definition at line 876 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::MCAsmInfo::binutilsIsAtLeast(), llvm::MCContext::getAsmInfo(), getLinkedToSymbol(), selectELFSectionForGlobal(), llvm::ELF::SHF_GNU_RETAIN, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_SUNW_NODISCARD, TM, and llvm::MCAsmInfo::useIntegratedAssembler().
selectExplicitSectionGlobal()
static MCSection* selectExplicitSectionGlobal (const GlobalObject * GO, SectionKind Kind, const TargetMachine & TM, MCContext & Ctx, Mangler & Mang, unsigned & NextUniqueID, bool Retain, bool ForceUnique) static
Definition at line 759 of file TargetLoweringObjectFileImpl.cpp.
References llvm::Comdat::Any, assert(), Attrs, llvm::MCAsmInfo::binutilsIsAtLeast(), calcUniqueIDUpdateFlagsAndSize(), llvm::LLVMContext::diagnose(), F, llvm::MCContext::getAsmInfo(), llvm::GlobalVariable::getAttributes(), llvm::Value::getContext(), getELFComdat(), getELFKindForNamedSection(), llvm::MCContext::getELFSection(), getELFSectionFlags(), getELFSectionType(), getEntrySizeForKind(), getLinkedToSymbol(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::GlobalObject::getSection(), llvm::Module::getSourceFileName(), llvm::GlobalVariable::hasImplicitSection(), llvm::ELF::SHF_GROUP, llvm::ELF::SHF_MERGE, TM, and llvm::MCAsmInfo::useIntegratedAssembler().
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileELF::getUniqueSectionForFunction().
selectWasmSectionForGlobal()
static MCSectionWasm* selectWasmSectionForGlobal (MCContext & Ctx, const GlobalObject * GO, SectionKind Kind, Mangler & Mang, const TargetMachine & TM, bool EmitUniqueSection, unsigned * NextUniqueID) static
Definition at line 2127 of file TargetLoweringObjectFileImpl.cpp.
References F, llvm::MCContext::GenericSectionID, getSectionPrefixForGlobal(), getWasmComdat(), llvm::MCContext::getWasmSection(), getWasmSectionFlags(), and TM.
Referenced by llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal().