LLVM: lib/Target/VE/VEAsmPrinter.cpp File Reference
VEAsmPrinter.cpp File Reference
#include "MCTargetDesc/VEInstPrinter.h"
#include "MCTargetDesc/VEMCExpr.h"
#include "MCTargetDesc/VETargetStreamer.h"
#include "TargetInfo/VETargetInfo.h"
#include "VE.h"
#include "VEInstrInfo.h"
#include "VETargetMachine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/IR/Mangler.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "ve-asmprinter"
Functions
static MCOperand createVEMCOperand (VEMCExpr::VariantKind Kind, MCSymbol *Sym, MCContext &OutContext)
static MCOperand createGOTRelExprOp (VEMCExpr::VariantKind Kind, MCSymbol *GOTLabel, MCContext &OutContext)
static void emitSIC (MCStreamer &OutStreamer, MCOperand &RD, const MCSubtargetInfo &STI)
static void emitBSIC (MCStreamer &OutStreamer, MCOperand &R1, MCOperand &R2, const MCSubtargetInfo &STI)
static void emitLEAzzi (MCStreamer &OutStreamer, MCOperand &Imm, MCOperand &RD, const MCSubtargetInfo &STI)
static void emitLEASLzzi (MCStreamer &OutStreamer, MCOperand &Imm, MCOperand &RD, const MCSubtargetInfo &STI)
static void emitLEAzii (MCStreamer &OutStreamer, MCOperand &RS1, MCOperand &Imm, MCOperand &RD, const MCSubtargetInfo &STI)
static void emitLEASLrri (MCStreamer &OutStreamer, MCOperand &RS1, MCOperand &RS2, MCOperand &Imm, MCOperand &RD, const MCSubtargetInfo &STI)
static void emitBinary (MCStreamer &OutStreamer, unsigned Opcode, MCOperand &RS1, MCOperand &Src2, MCOperand &RD, const MCSubtargetInfo &STI)
static void emitANDrm (MCStreamer &OutStreamer, MCOperand &RS1, MCOperand &Imm, MCOperand &RD, const MCSubtargetInfo &STI)
static void emitHiLo (MCStreamer &OutStreamer, MCSymbol *GOTSym, VEMCExpr::VariantKind HiKind, VEMCExpr::VariantKind LoKind, MCOperand &RD, MCContext &OutContext, const MCSubtargetInfo &STI)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeVEAsmPrinter ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ve-asmprinter"
Definition at line 37 of file VEAsmPrinter.cpp.
Function Documentation
createGOTRelExprOp()
static MCOperand createGOTRelExprOp (VEMCExpr::VariantKind Kind, MCSymbol * GOTLabel, MCContext & OutContext) static
Definition at line 78 of file VEAsmPrinter.cpp.
References llvm::VEMCExpr::create(), llvm::MCSymbolRefExpr::create(), and llvm::MCOperand::createExpr().
createVEMCOperand()
static MCOperand createVEMCOperand (VEMCExpr::VariantKind Kind, MCSymbol * Sym, MCContext & OutContext) static
Definition at line 71 of file VEAsmPrinter.cpp.
References llvm::VEMCExpr::create(), llvm::MCSymbolRefExpr::create(), and llvm::MCOperand::createExpr().
Referenced by emitHiLo().
emitANDrm()
static void emitANDrm (MCStreamer & OutStreamer, MCOperand & RS1, MCOperand & Imm, MCOperand & RD, const MCSubtargetInfo & STI) static
Definition at line 164 of file VEAsmPrinter.cpp.
References emitBinary(), and llvm::RISCVMatInt::Imm.
Referenced by emitHiLo().
emitBinary()
static void emitBinary (MCStreamer & OutStreamer, unsigned Opcode, MCOperand & RS1, MCOperand & Src2, MCOperand & RD, const MCSubtargetInfo & STI) static
Definition at line 153 of file VEAsmPrinter.cpp.
References llvm::MCInst::addOperand(), llvm::MCStreamer::emitInstruction(), and llvm::MCInst::setOpcode().
Referenced by emitANDrm().
emitBSIC()
static void emitBSIC (MCStreamer & OutStreamer, MCOperand & R1, MCOperand & R2, const MCSubtargetInfo & STI) static
Definition at line 93 of file VEAsmPrinter.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCStreamer::emitInstruction(), R2, and llvm::MCInst::setOpcode().
emitHiLo()
static void emitHiLo (MCStreamer & OutStreamer, MCSymbol * GOTSym, VEMCExpr::VariantKind HiKind, VEMCExpr::VariantKind LoKind, MCOperand & RD, MCContext & OutContext, const MCSubtargetInfo & STI) static
Definition at line 169 of file VEAsmPrinter.cpp.
References llvm::MCOperand::createImm(), createVEMCOperand(), emitANDrm(), emitLEASLzzi(), emitLEAzzi(), shuffles::hi(), shuffles::lo(), and llvm::M0().
emitLEASLrri()
static void emitLEASLrri (MCStreamer & OutStreamer, MCOperand & RS1, MCOperand & RS2, MCOperand & Imm, MCOperand & RD, const MCSubtargetInfo & STI) static
Definition at line 141 of file VEAsmPrinter.cpp.
References llvm::MCInst::addOperand(), llvm::MCStreamer::emitInstruction(), llvm::RISCVMatInt::Imm, and llvm::MCInst::setOpcode().
emitLEASLzzi()
static void emitLEASLzzi (MCStreamer & OutStreamer, MCOperand & Imm, MCOperand & RD, const MCSubtargetInfo & STI) static
Definition at line 117 of file VEAsmPrinter.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCStreamer::emitInstruction(), llvm::RISCVMatInt::Imm, and llvm::MCInst::setOpcode().
Referenced by emitHiLo().
emitLEAzii()
static void emitLEAzii (MCStreamer & OutStreamer, MCOperand & RS1, MCOperand & Imm, MCOperand & RD, const MCSubtargetInfo & STI) static
Definition at line 129 of file VEAsmPrinter.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCStreamer::emitInstruction(), llvm::RISCVMatInt::Imm, and llvm::MCInst::setOpcode().
emitLEAzzi()
static void emitLEAzzi (MCStreamer & OutStreamer, MCOperand & Imm, MCOperand & RD, const MCSubtargetInfo & STI) static
Definition at line 105 of file VEAsmPrinter.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCStreamer::emitInstruction(), llvm::RISCVMatInt::Imm, and llvm::MCInst::setOpcode().
Referenced by emitHiLo().
emitSIC()
static void emitSIC (MCStreamer & OutStreamer, MCOperand & RD, const MCSubtargetInfo & STI) static
Definition at line 85 of file VEAsmPrinter.cpp.
References llvm::MCInst::addOperand(), llvm::MCStreamer::emitInstruction(), and llvm::MCInst::setOpcode().
LLVMInitializeVEAsmPrinter()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeVEAsmPrinter ()
Definition at line 426 of file VEAsmPrinter.cpp.
References llvm::getTheVETarget(), and X.