LLVM: lib/Transforms/Vectorize/VPlanTransforms.cpp File Reference
VPlanTransforms.cpp File Reference
#include "VPlanTransforms.h"
#include "VPlanDominatorTree.h"
#include "VPRecipeBuilder.h"
#include "VPlanCFG.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Analysis/IVDescriptors.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/IR/Intrinsics.h"
Functions
VPValue * getPredicatedMask (VPRegionBlock *R)
If R is a region with a VPBranchOnMaskRecipe in the entry block, return the mask.
static VPBasicBlock * getPredicatedThenBlock (VPRegionBlock *R)
If R is a triangle region, return the 'then' block of the triangle.
static bool canSimplifyBranchOnCond (VPInstruction *Term)
static VPRegionBlock * GetReplicateRegion (VPRecipeBase *R)
static bool properlyDominates (const VPRecipeBase *A, const VPRecipeBase *B, VPDominatorTree &VPDT)
static void sinkRecurrenceUsersAfterPrevious (VPFirstOrderRecurrencePHIRecipe *FOR, VPRecipeBase *Previous, VPDominatorTree &VPDT)
Detailed Description
This file implements a set of utility VPlan to VPlan transformations.
Definition in file VPlanTransforms.cpp.
Function Documentation
canSimplifyBranchOnCond()
static bool canSimplifyBranchOnCond (VPInstruction * Term) static
Definition at line 489 of file VPlanTransforms.cpp.
References llvm::VPInstruction::ActiveLaneMask, llvm::VPInstruction::getOpcode(), llvm::VPUser::getOperand(), llvm::VPInstruction::Not, and llvm::M68kBeads::Term.
Referenced by llvm::VPlanTransforms::optimizeForVFAndUF().
getPredicatedMask()
VPValue* getPredicatedMask (VPRegionBlock * R)
If R is a region with a VPBranchOnMaskRecipe in the entry block, return the mask.
Definition at line 200 of file VPlanTransforms.cpp.
Referenced by llvm::VPlanTransforms::mergeReplicateRegionsIntoSuccessors().
getPredicatedThenBlock()
static VPBasicBlock* getPredicatedThenBlock (VPRegionBlock * R) static
If R is a triangle region, return the 'then' block of the triangle.
Definition at line 210 of file VPlanTransforms.cpp.
Referenced by llvm::VPlanTransforms::mergeReplicateRegionsIntoSuccessors().
GetReplicateRegion()
static VPRegionBlock* GetReplicateRegion (VPRecipeBase * R) static
Definition at line 539 of file VPlanTransforms.cpp.
References assert().
Referenced by llvm::VPlanTransforms::adjustFixedOrderRecurrences(), properlyDominates(), and sinkRecurrenceUsersAfterPrevious().
properlyDominates()
static bool properlyDominates (const VPRecipeBase * A, const VPRecipeBase * B, VPDominatorTree & VPDT) static
Definition at line 552 of file VPlanTransforms.cpp.
References B, llvm::VPRegionBlock::getExiting(), GetReplicateRegion(), llvm_unreachable, and llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates().
Referenced by sinkRecurrenceUsersAfterPrevious().
sinkRecurrenceUsersAfterPrevious()
static void sinkRecurrenceUsersAfterPrevious (VPFirstOrderRecurrencePHIRecipe * FOR, VPRecipeBase * Previous, VPDominatorTree & VPDT) static
Definition at line 582 of file VPlanTransforms.cpp.
References assert(), B, llvm::VPBlockUtils::connectBlocks(), llvm::VPBlockUtils::disconnectBlocks(), llvm::X86ISD::FOR, llvm::VPBasicBlock::getFirstNonPhi(), llvm::VPDef::getNumDefinedValues(), GetReplicateRegion(), llvm::BasicBlock::getSinglePredecessor(), llvm::VPDef::getVPSingleValue(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), properlyDominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate(), llvm::sort(), llvm::SplitBlock(), and llvm::VPValue::users().
Referenced by llvm::VPlanTransforms::adjustFixedOrderRecurrences().