LLVM: lib/Transforms/Scalar/WarnMissedTransforms.cpp File Reference
WarnMissedTransforms.cpp File Reference
#include "llvm/Transforms/Scalar/WarnMissedTransforms.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/InitializePasses.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
Macros
#define DEBUG_TYPE "transform-warning"
Functions
static void warnAboutLeftoverTransformations (Loop *L, OptimizationRemarkEmitter *ORE)
Emit warnings for forced (i.e.
static void warnAboutLeftoverTransformations (Function *F, LoopInfo *LI, OptimizationRemarkEmitter *ORE)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "transform-warning"
Definition at line 21 of file WarnMissedTransforms.cpp.
Function Documentation
warnAboutLeftoverTransformations() [1/2]
static void warnAboutLeftoverTransformations (Function * F, LoopInfo * LI, OptimizationRemarkEmitter * ORE) static
Definition at line 86 of file WarnMissedTransforms.cpp.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInPreorder(), and warnAboutLeftoverTransformations().
warnAboutLeftoverTransformations() [2/2]
static void warnAboutLeftoverTransformations (Loop * L, OptimizationRemarkEmitter * ORE) static
Emit warnings for forced (i.e.
user-defined) loop transformations which have still not been performed.
Definition at line 25 of file WarnMissedTransforms.cpp.
References llvm::dbgs(), DEBUG_TYPE, llvm::OptimizationRemarkEmitter::emit(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getOptionalElementCountLoopAttribute(), llvm::getOptionalIntLoopAttribute(), llvm::Loop::getStartLoc(), llvm::hasDistributeTransformation(), llvm::hasUnrollAndJamTransformation(), llvm::hasUnrollTransformation(), llvm::hasVectorizeTransformation(), LLVM_DEBUG, and llvm::TM_ForcedByUser.
Referenced by llvm::WarnMissedTransformationsPass::run(), and warnAboutLeftoverTransformations().