LLVM: lib/Target/WebAssembly/WebAssemblyISelLowering.cpp File Reference
WebAssemblyISelLowering.cpp File Reference
#include "WebAssemblyISelLowering.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "Utils/WebAssemblyTypeUtilities.h"
#include "Utils/WebAssemblyUtilities.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblySubtarget.h"
#include "WebAssemblyTargetMachine.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetOptions.h"
#include "WebAssemblyISD.def"
Macros
#define DEBUG_TYPE "wasm-lower"
#define HANDLE_NODETYPE(NODE)
#define HANDLE_MEM_NODETYPE(NODE) HANDLE_NODETYPE(NODE)
Functions
static MachineBasicBlock * LowerFPToInt (MachineInstr &MI, DebugLoc DL, MachineBasicBlock *BB, const TargetInstrInfo &TII, bool IsUnsigned, bool Int64, bool Float64, unsigned LoweredOpcode)
static MachineBasicBlock * LowerCallResults (MachineInstr &CallResults, DebugLoc DL, MachineBasicBlock *BB, const WebAssemblySubtarget *Subtarget, const TargetInstrInfo &TII)
static void fail (const SDLoc &DL, SelectionDAG &DAG, const char *Msg)
static bool callingConvSupported (CallingConv::ID CallConv)
static bool IsWebAssemblyGlobal (SDValue Op)
static std::optional< unsigned > IsWebAssemblyLocal (SDValue Op, SelectionDAG &DAG)
static SDValue LowerConvertLow (SDValue Op, SelectionDAG &DAG)
static SDValue unrollVectorShift (SDValue Op, SelectionDAG &DAG)
static SDValue performVECTOR_SHUFFLECombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
static SDValue performVectorExtendToFPCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
Convert ({u,s}itofp vec) --> ({u,s}itofp ({s,z}ext vec)) so it doesn't get split up into scalar instructions during legalization, and the vector extending instructions are selected in performVectorExtendCombine below.
static SDValue performVectorExtendCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
static SDValue performVectorTruncZeroCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
static SDValue extractSubVector (SDValue Vec, unsigned IdxVal, SelectionDAG &DAG, const SDLoc &DL, unsigned VectorWidth)
static SDValue truncateVectorWithNARROW (EVT DstVT, SDValue In, const SDLoc &DL, SelectionDAG &DAG)
static SDValue performTruncateCombine (SDNode *N, TargetLowering::DAGCombinerInfo &DCI)
Detailed Description
This file implements the WebAssemblyTargetLowering class.
Definition in file WebAssemblyISelLowering.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-lower"
Definition at line 43 of file WebAssemblyISelLowering.cpp.
HANDLE_MEM_NODETYPE
#define HANDLE_MEM_NODETYPE (NODE) HANDLE_NODETYPE(NODE)
HANDLE_NODETYPE
#define HANDLE_NODETYPE (NODE)
Value:
  case WebAssemblyISD::NODE:                                                   \
    return "WebAssemblyISD::" #NODE;
Function Documentation
callingConvSupported()
static bool callingConvSupported (CallingConv::ID CallConv) static
Definition at line 954 of file WebAssemblyISelLowering.cpp.
References llvm::CallingConv::C, llvm::CallingConv::Cold, llvm::CallingConv::CXX_FAST_TLS, llvm::CallingConv::Fast, llvm::CallingConv::PreserveAll, llvm::CallingConv::PreserveMost, llvm::CallingConv::Swift, and llvm::CallingConv::WASM_EmscriptenInvoke.
extractSubVector()
static SDValue extractSubVector (SDValue Vec, unsigned IdxVal, SelectionDAG & DAG, const SDLoc & DL, unsigned VectorWidth) static
Definition at line 2552 of file WebAssemblyISelLowering.cpp.
References assert(), llvm::ISD::BUILD_VECTOR, DL, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::isPowerOf2_32(), and llvm::SDNode::ops().
Referenced by truncateVectorWithNARROW().
fail()
static void fail (const SDLoc & DL, SelectionDAG & DAG, const char * Msg) static
Definition at line 947 of file WebAssemblyISelLowering.cpp.
References llvm::LLVMContext::diagnose(), DL, llvm::SelectionDAG::getContext(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), and llvm::AMDGPU::SendMsg::Msg.
IsWebAssemblyGlobal()
static bool IsWebAssemblyGlobal (SDValue Op) static
Definition at line 1450 of file WebAssemblyISelLowering.cpp.
References llvm::GlobalAddressSDNode::getAddressSpace(), and llvm::WebAssembly::isWasmVarAddressSpace().
IsWebAssemblyLocal()
static std::optional<unsigned> IsWebAssemblyLocal (SDValue Op, SelectionDAG & DAG) static
Definition at line 1457 of file WebAssemblyISelLowering.cpp.
References llvm::FrameIndexSDNode::getIndex(), llvm::WebAssemblyFrameLowering::getLocalForStackObject(), and llvm::SelectionDAG::getMachineFunction().
LowerCallResults()
static MachineBasicBlock* LowerCallResults (MachineInstr & CallResults, DebugLoc DL, MachineBasicBlock * BB, const WebAssemblySubtarget * Subtarget, const TargetInstrInfo & TII) static
Definition at line 529 of file WebAssemblyISelLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addSym(), assert(), BB, llvm::BuildMI(), llvm::AArch64ISD::CALL, llvm::MachineFunction::CreateMachineInstr(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::tgtok::Def, llvm::MachineInstr::defs(), DL, llvm::MachineInstr::eraseFromParent(), llvm::MachineFunction::getContext(), llvm::MachineInstrBuilder::getInstr(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::WebAssembly::getOrCreateFuncrefCallTableSymbol(), llvm::WebAssembly::getOrCreateFunctionTableSymbol(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::WebAssemblySubtarget::hasAddr64(), llvm::WebAssemblySubtarget::hasReferenceTypes(), llvm::MachineOperand::isReg(), MRI, llvm::MachineInstr::removeOperand(), llvm::MCSymbolWasm::setNoStrip(), TII, and llvm::MachineInstr::uses().
LowerConvertLow()
static SDValue LowerConvertLow (SDValue Op, SelectionDAG & DAG) static
Definition at line 1878 of file WebAssemblyISelLowering.cpp.
References DL, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FP_EXTEND, llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVectorShuffle(), Index, llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, llvm::MVT::v2f64, llvm::MVT::v4f32, and llvm::MVT::v4i32.
LowerFPToInt()
static MachineBasicBlock* LowerFPToInt (MachineInstr & MI, DebugLoc DL, MachineBasicBlock * BB, const TargetInstrInfo & TII, bool IsUnsigned, bool Int64, bool Float64, unsigned LoweredOpcode) static
Definition at line 435 of file WebAssemblyISelLowering.cpp.
References llvm::MachineInstrBuilder::addFPImm(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::And, BB, llvm::MachineBasicBlock::begin(), llvm::ISD::BR, llvm::BuildMI(), Context, llvm::MachineRegisterInfo::createVirtualRegister(), DL, double, F, llvm::AArch64CC::GE, llvm::ConstantFP::get(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::MachineRegisterInfo::getRegClass(), INT64_MIN, llvm::AArch64CC::LT, MI, MRI, PHI, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
performTruncateCombine()
static SDValue performTruncateCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 2632 of file WebAssemblyISelLowering.cpp.
References llvm::ISD::AND, llvm::TargetLowering::DAGCombinerInfo::DAG, DL, llvm::SelectionDAG::getConstant(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getVectorElementType(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::tgtok::In, llvm::EVT::is128BitVector(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm::BitmaskEnumDetail::Mask(), N, and truncateVectorWithNARROW().
performVECTOR_SHUFFLECombine()
static SDValue performVECTOR_SHUFFLECombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 2335 of file WebAssemblyISelLowering.cpp.
References llvm::LegacyLegalizeActions::Bitcast, llvm::ISD::BITCAST, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getBitcast(), llvm::SDValue::getSimpleValueType(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::MVT::is128BitVector(), N, and llvm::Shuffle.
performVectorExtendCombine()
static SDValue performVectorExtendCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 2386 of file WebAssemblyISelLowering.cpp.
References assert(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), N, llvm::ISD::SIGN_EXTEND, llvm::Sched::Source, llvm::MVT::v16i8, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::MVT::v8i8, and llvm::ISD::ZERO_EXTEND.
performVectorExtendToFPCombine()
static SDValue performVectorExtendToFPCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Convert ({u,s}itofp vec) --> ({u,s}itofp ({s,z}ext vec)) so it doesn't get split up into scalar instructions during legalization, and the vector extending instructions are selected in performVectorExtendCombine below.
Definition at line 2363 of file WebAssemblyISelLowering.cpp.
References assert(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getNode(), N, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, llvm::MVT::v2f64, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i8, llvm::MVT::v4f32, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i8, and llvm::ISD::ZERO_EXTEND.
performVectorTruncZeroCombine()
static SDValue performVectorTruncZeroCombine (SDNode * N, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 2433 of file WebAssemblyISelLowering.cpp.
References Concat, llvm::ISD::CONCAT_VECTORS, Conversion, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT_SAT, llvm::ISD::FP_TO_UINT_SAT, llvm::SelectionDAG::getNode(), llvm_unreachable, N, llvm::Sched::Source, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i32, llvm::MVT::v4f32, llvm::MVT::v4f64, and llvm::MVT::v4i32.
truncateVectorWithNARROW()
static SDValue truncateVectorWithNARROW (EVT DstVT, SDValue In, const SDLoc & DL, SelectionDAG & DAG) static
Definition at line 2581 of file WebAssemblyISelLowering.cpp.
References assert(), llvm::ISD::CONCAT_VECTORS, DL, extractSubVector(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getSizeInBits(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::tgtok::In, llvm::EVT::is128BitVector(), llvm::EVT::is256BitVector(), and llvm::isPowerOf2_32().
Referenced by performTruncateCombine().
unrollVectorShift()
static SDValue unrollVectorShift (SDValue Op, SelectionDAG & DAG) static
Definition at line 2255 of file WebAssemblyISelLowering.cpp.
References llvm::ISD::AND, llvm::EVT::bitsGE(), DL, llvm::SelectionDAG::ExtractVectorElements(), llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getValueType(), i, llvm::MVT::i32, llvm::BitmaskEnumDetail::Mask(), llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SRA, and llvm::SelectionDAG::UnrollVectorOp().