LLVM: lib/Target/WebAssembly/WebAssemblyISelDAGToDAG.cpp File Reference
WebAssemblyISelDAGToDAG.cpp File Reference
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "WebAssembly.h"
#include "WebAssemblyISelLowering.h"
#include "WebAssemblyTargetMachine.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/CodeGen/WasmEHFuncInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IntrinsicsWebAssembly.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "WebAssemblyGenDAGISel.inc"
Macros
#define DEBUG_TYPE "wasm-isel"
#define PASS_NAME "WebAssembly Instruction Selection"
Functions
static SDValue getTagSymNode (int Tag, SelectionDAG *DAG)
Detailed Description
This file defines an instruction selector for the WebAssembly target.
Definition in file WebAssemblyISelDAGToDAG.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-isel"
Definition at line 31 of file WebAssemblyISelDAGToDAG.cpp.
PASS_NAME
#define PASS_NAME "WebAssembly Instruction Selection"
Definition at line 32 of file WebAssemblyISelDAGToDAG.cpp.
Function Documentation
getTagSymNode()
static SDValue getTagSymNode (int Tag, SelectionDAG * DAG) static
Definition at line 102 of file WebAssemblyISelDAGToDAG.cpp.
References assert(), llvm::WebAssembly::C_LONGJMP, llvm::WebAssembly::CPP_EXCEPTION, llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getTargetExternalSymbol(), and llvm::SelectionDAG::getTargetLoweringInfo().