LLVM: lib/Target/WebAssembly/WebAssemblyTargetMachine.cpp File Reference
WebAssemblyTargetMachine.cpp File Reference
#include "WebAssemblyTargetMachine.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "TargetInfo/WebAssemblyTargetInfo.h"
#include "Utils/WebAssemblyUtilities.h"
#include "WebAssembly.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblyTargetObjectFile.h"
#include "WebAssemblyTargetTransformInfo.h"
#include "llvm/CodeGen/MIRParser/MIParser.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegAllocRegistry.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Function.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/LowerAtomicPass.h"
#include "llvm/Transforms/Utils.h"
#include <optional>
Macros
#define DEBUG_TYPE "wasm"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyTarget ()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM, const Triple &TT)
static void basicCheckForEHAndSjLj (TargetMachine *TM)
Variables
static cl::opt< bool > WasmDisableExplicitLocals ("wasm-disable-explicit-locals", cl::Hidden, cl::desc("WebAssembly: output implicit locals in" " instruction output for test purposes only."), cl::init(false))
Detailed Description
This file defines the WebAssembly-specific subclass of TargetMachine.
Definition in file WebAssemblyTargetMachine.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm"
Definition at line 38 of file WebAssemblyTargetMachine.cpp.
Function Documentation
basicCheckForEHAndSjLj()
static void basicCheckForEHAndSjLj (TargetMachine * TM) static
Definition at line 370 of file WebAssemblyTargetMachine.cpp.
References llvm::None, llvm::report_fatal_error(), TM, llvm::Wasm, llvm::WebAssembly::WasmEnableEH, llvm::WebAssembly::WasmEnableEmEH, llvm::WebAssembly::WasmEnableEmSjLj, and llvm::WebAssembly::WasmEnableSjLj.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM, const Triple & TT) static
Definition at line 92 of file WebAssemblyTargetMachine.cpp.
References llvm::AArch64::RM, and llvm::Reloc::Static.
LLVMInitializeWebAssemblyTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyTarget ()
Definition at line 50 of file WebAssemblyTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheWebAssemblyTarget32(), llvm::getTheWebAssemblyTarget64(), llvm::initializeFixFunctionBitcastsPass(), llvm::initializeLowerGlobalDtorsLegacyPassPass(), llvm::initializeOptimizeReturnedPass(), llvm::initializeWebAssemblyAddMissingPrototypesPass(), llvm::initializeWebAssemblyArgumentMovePass(), llvm::initializeWebAssemblyCFGSortPass(), llvm::initializeWebAssemblyCFGStackifyPass(), llvm::initializeWebAssemblyDAGToDAGISelPass(), llvm::initializeWebAssemblyDebugFixupPass(), llvm::initializeWebAssemblyExceptionInfoPass(), llvm::initializeWebAssemblyExplicitLocalsPass(), llvm::initializeWebAssemblyFixBrTableDefaultsPass(), llvm::initializeWebAssemblyFixIrreducibleControlFlowPass(), llvm::initializeWebAssemblyLateEHPreparePass(), llvm::initializeWebAssemblyLowerBrUnlessPass(), llvm::initializeWebAssemblyLowerEmscriptenEHSjLjPass(), llvm::initializeWebAssemblyLowerRefTypesIntPtrConvPass(), llvm::initializeWebAssemblyMCLowerPrePassPass(), llvm::initializeWebAssemblyMemIntrinsicResultsPass(), llvm::initializeWebAssemblyNullifyDebugValueListsPass(), llvm::initializeWebAssemblyOptimizeLiveIntervalsPass(), llvm::initializeWebAssemblyPeepholePass(), llvm::initializeWebAssemblyRegColoringPass(), llvm::initializeWebAssemblyRegNumberingPass(), llvm::initializeWebAssemblyRegStackifyPass(), llvm::initializeWebAssemblyReplacePhysRegsPass(), llvm::initializeWebAssemblySetP2AlignOperandsPass(), X, and Y.
Variable Documentation
WasmDisableExplicitLocals
cl::opt<bool> WasmDisableExplicitLocals("wasm-disable-explicit-locals", cl::Hidden, cl::desc("WebAssembly: output implicit locals in" " instruction output for test purposes only."), cl::init(false)) static