LLVM: lib/Target/X86/X86InstrFoldTables.cpp File Reference
X86InstrFoldTables.cpp File Reference
#include "X86InstrFoldTables.h"
#include "X86InstrInfo.h"
#include "llvm/ADT/STLExtras.h"
#include <atomic>
#include <vector>
#include "X86MemFoldTables.inc"
Functions
static const X86MemoryFoldTableEntry * lookupFoldTableImpl (ArrayRef< X86MemoryFoldTableEntry > Table, unsigned RegOp)
Variables
static const X86MemoryFoldTableEntry BroadcastFoldTable2 []
static const X86MemoryFoldTableEntry BroadcastFoldTable3 []
Function Documentation
lookupFoldTableImpl()
static const X86MemoryFoldTableEntry* lookupFoldTableImpl (ArrayRef< X86MemoryFoldTableEntry > Table, unsigned RegOp) static
Definition at line 308 of file X86InstrFoldTables.cpp.
References assert(), llvm::sys::path::begin(), BroadcastFoldTable2, BroadcastFoldTable3, llvm::Data, llvm::ArrayRef< T >::end(), llvm::sys::path::end(), llvm::is_sorted(), llvm::lower_bound(), and llvm::TB_NO_FORWARD.
Referenced by llvm::lookupFoldTable(), and llvm::lookupTwoAddrFoldTable().
Variable Documentation
BroadcastFoldTable2
const X86MemoryFoldTableEntry BroadcastFoldTable2[] static
Definition at line 37 of file X86InstrFoldTables.cpp.
Referenced by lookupFoldTableImpl().
BroadcastFoldTable3
const X86MemoryFoldTableEntry BroadcastFoldTable3[] static
Definition at line 190 of file X86InstrFoldTables.cpp.
Referenced by lookupFoldTableImpl().