LLVM: lib/Target/X86/X86InstCombineIntrinsic.cpp File Reference
X86InstCombineIntrinsic.cpp File Reference
#include "X86TargetTransformInfo.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include <optional>
Macros
#define DEBUG_TYPE "x86tti"
Functions
static Constant * getNegativeIsTrueBoolVec (Constant *V)
Return a constant boolean vector that has true elements in all positions where the input constant data vector has an element with the sign bit set.
static Value * getBoolVecFromMask (Value *Mask)
Convert the x86 XMM integer vector mask to a vector of bools based on each element's most significant bit (the sign bit).
static Instruction * simplifyX86MaskedLoad (IntrinsicInst &II, InstCombiner &IC)
static bool simplifyX86MaskedStore (IntrinsicInst &II, InstCombiner &IC)
static Value * simplifyX86immShift (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86varShift (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86pack (IntrinsicInst &II, InstCombiner::BuilderTy &Builder, bool IsSigned)
static Value * simplifyX86movmsk (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86addcarry (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86insertps (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
static Value * simplifyX86extrq (IntrinsicInst &II, Value *Op0, ConstantInt *CILength, ConstantInt *CIIndex, InstCombiner::BuilderTy &Builder)
Attempt to simplify SSE4A EXTRQ/EXTRQI instructions using constant folding or conversion to a shuffle vector.
static Value * simplifyX86insertq (IntrinsicInst &II, Value *Op0, Value *Op1, APInt APLength, APInt APIndex, InstCombiner::BuilderTy &Builder)
Attempt to simplify SSE4A INSERTQ/INSERTQI instructions using constant folding or conversion to a shuffle vector.
static Value * simplifyX86pshufb (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert pshufb* to shufflevector if the mask is constant.
static Value * simplifyX86vpermilvar (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert vpermilvar* to shufflevector if the mask is constant.
static Value * simplifyX86vpermv (const IntrinsicInst &II, InstCombiner::BuilderTy &Builder)
Attempt to convert vpermd/vpermps to shufflevector if the mask is constant.
Detailed Description
This file implements a TargetTransformInfo analysis pass specific to the X86 target machine. It uses the target's detailed information to provide more precise answers to certain TTI queries, while letting the target independent and default TTI implementations handle the rest.
Definition in file X86InstCombineIntrinsic.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86tti"
Definition at line 25 of file X86InstCombineIntrinsic.cpp.
Function Documentation
getBoolVecFromMask()
static Value* getBoolVecFromMask (Value * Mask) static
Convert the x86 XMM integer vector mask to a vector of bools based on each element's most significant bit (the sign bit).
Definition at line 39 of file X86InstCombineIntrinsic.cpp.
References getNegativeIsTrueBoolVec(), llvm::Value::getType(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Value(), llvm::BitmaskEnumDetail::Mask(), and llvm::PatternMatch::match().
Referenced by simplifyX86MaskedLoad(), and simplifyX86MaskedStore().
getNegativeIsTrueBoolVec()
static Constant* getNegativeIsTrueBoolVec (Constant * V) static
Return a constant boolean vector that has true elements in all positions where the input constant data vector has an element with the sign bit set.
Definition at line 29 of file X86InstCombineIntrinsic.cpp.
References llvm::ConstantExpr::getBitCast(), llvm::ConstantExpr::getICmp(), llvm::VectorType::getInteger(), llvm::Constant::getNullValue(), llvm::Value::getType(), and llvm::CmpInst::ICMP_SGT.
Referenced by getBoolVecFromMask(), and llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86addcarry()
static Value* simplifyX86addcarry (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 533 of file X86InstCombineIntrinsic.cpp.
References assert(), Builder, llvm::PoisonValue::get(), llvm::CallBase::getArgOperand(), llvm::Type::getStructElementType(), llvm::Value::getType(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_ZeroInt(), and llvm::PatternMatch::match().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86extrq()
static Value* simplifyX86extrq (IntrinsicInst & II, Value * Op0, ConstantInt * CILength, ConstantInt * CIIndex, InstCombiner::BuilderTy & Builder) static
Attempt to simplify SSE4A EXTRQ/EXTRQI instructions using constant folding or conversion to a shuffle vector.
Definition at line 619 of file X86InstCombineIntrinsic.cpp.
References llvm::AMDGPU::HSAMD::Kernel::Key::Args, llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::Value::getContext(), llvm::Type::getInt64Ty(), llvm::ConstantInt::getValue(), llvm::APInt::getZExtValue(), llvm::Length, uint64_t, and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86immShift()
static Value* simplifyX86immShift (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 120 of file X86InstCombineIntrinsic.cpp.
References assert(), llvm::BitWidth, Builder, llvm::computeKnownBits(), llvm::ConstantInt::get(), llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::APInt::getBitsSet(), llvm::Module::getDataLayout(), llvm::IntrinsicInst::getIntrinsicID(), llvm::KnownBits::getMaxValue(), llvm::KnownBits::getMinValue(), llvm::Instruction::getModule(), llvm::APInt::getOneBitSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), i, llvm::Type::isIntegerTy(), llvm::Type::isVectorTy(), llvm::KnownBits::isZero(), llvm::APInt::isZero(), llvm_unreachable, llvm::APInt::uge(), llvm::APInt::ult(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86insertps()
static Value* simplifyX86insertps (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 560 of file X86InstCombineIntrinsic.cpp.
References assert(), Builder, llvm::ConstantAggregateZero::get(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), i, llvm::RISCVMatInt::Imm, and x3.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86insertq()
static Value* simplifyX86insertq (IntrinsicInst & II, Value * Op0, Value * Op1, APInt APLength, APInt APIndex, InstCombiner::BuilderTy & Builder) static
Attempt to simplify SSE4A INSERTQ/INSERTQI instructions using constant folding or conversion to a shuffle vector.
Definition at line 710 of file X86InstCombineIntrinsic.cpp.
References llvm::APInt::getZExtValue(), llvm::Length, and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86MaskedLoad()
static Instruction* simplifyX86MaskedLoad (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 57 of file X86InstCombineIntrinsic.cpp.
References llvm::InstCombiner::Builder, llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::PointerType::get(), getBoolVecFromMask(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Value::getType(), llvm::BitmaskEnumDetail::Mask(), Ptr, and llvm::InstCombiner::replaceInstUsesWith().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86MaskedStore()
static bool simplifyX86MaskedStore (IntrinsicInst & II, InstCombiner & IC) static
Definition at line 87 of file X86InstCombineIntrinsic.cpp.
References Align, llvm::InstCombiner::Builder, llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::InstCombiner::eraseInstFromFunction(), llvm::PointerType::get(), getBoolVecFromMask(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), llvm::Value::getType(), llvm::BitmaskEnumDetail::Mask(), and Ptr.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86movmsk()
static Value* simplifyX86movmsk (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 504 of file X86InstCombineIntrinsic.cpp.
References Arg, Builder, llvm::CallBase::getArgOperand(), llvm::VectorType::getInteger(), llvm::Constant::getNullValue(), and llvm::Value::getType().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86pack()
static Value* simplifyX86pack (IntrinsicInst & II, InstCombiner::BuilderTy & Builder, bool IsSigned) static
Definition at line 438 of file X86InstCombineIntrinsic.cpp.
References assert(), Builder, llvm::UndefValue::get(), llvm::CallBase::getArgOperand(), llvm::Constant::getIntegerValue(), llvm::APInt::getLowBitsSet(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::Value::getType(), llvm::APInt::getZero(), llvm::APInt::sext(), and llvm::Shuffle.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86pshufb()
static Value* simplifyX86pshufb (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert pshufb* to shufflevector if the mask is constant.
Definition at line 803 of file X86InstCombineIntrinsic.cpp.
References llvm::ArrayRef(), assert(), Builder, llvm::Constant::getAggregateElement(), llvm::CallBase::getArgOperand(), llvm::Constant::getNullValue(), llvm::Value::getType(), I, Index, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86varShift()
static Value* simplifyX86varShift (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Definition at line 302 of file X86InstCombineIntrinsic.cpp.
References llvm::all_of(), assert(), llvm::BitWidth, Builder, llvm::computeKnownBits(), llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::CallBase::getArgOperand(), llvm::Module::getDataLayout(), llvm::Type::getIntegerBitWidth(), llvm::IntrinsicInst::getIntrinsicID(), llvm::KnownBits::getMaxValue(), llvm::Instruction::getModule(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::APInt::getZExtValue(), I, llvm_unreachable, llvm::APInt::uge(), and llvm::APInt::ult().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86vpermilvar()
static Value* simplifyX86vpermilvar (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert vpermilvar* to shufflevector if the mask is constant.
Definition at line 848 of file X86InstCombineIntrinsic.cpp.
References llvm::ArrayRef(), assert(), Builder, llvm::Constant::getAggregateElement(), llvm::CallBase::getArgOperand(), llvm::APInt::getLoBits(), llvm::Value::getType(), I, llvm::APInt::lshrInPlace(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().
simplifyX86vpermv()
static Value* simplifyX86vpermv (const IntrinsicInst & II, InstCombiner::BuilderTy & Builder) static
Attempt to convert vpermd/vpermps to shufflevector if the mask is constant.
Definition at line 895 of file X86InstCombineIntrinsic.cpp.
References llvm::ArrayRef(), assert(), Builder, llvm::Constant::getAggregateElement(), llvm::CallBase::getArgOperand(), llvm::Value::getType(), I, and Index.
Referenced by llvm::X86TTIImpl::instCombineIntrinsic().