LLVM: lib/Target/X86/MCTargetDesc/X86InstrRelaxTables.cpp File Reference
X86InstrRelaxTables.cpp File Reference
#include "X86InstrRelaxTables.h"
#include "X86InstrInfo.h"
#include "llvm/ADT/STLExtras.h"
#include <atomic>
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static const X86InstrRelaxTableEntry * lookupRelaxTableImpl (ArrayRef< X86InstrRelaxTableEntry > Table, unsigned ShortOp)
Variables
static const X86InstrRelaxTableEntry InstrRelaxTable []
Function Documentation
lookupRelaxTableImpl()
static const X86InstrRelaxTableEntry* lookupRelaxTableImpl (ArrayRef< X86InstrRelaxTableEntry > Table, unsigned ShortOp) static
Definition at line 95 of file X86InstrRelaxTables.cpp.
References assert(), llvm::sys::path::begin(), llvm::Data, llvm::ArrayRef< T >::end(), llvm::sys::path::end(), InstrRelaxTable, llvm::is_sorted(), and llvm::lower_bound().
Referenced by llvm::lookupRelaxTable().
Variable Documentation
InstrRelaxTable
const X86InstrRelaxTableEntry InstrRelaxTable[] static
Definition at line 24 of file X86InstrRelaxTables.cpp.
Referenced by llvm::lookupRelaxTable(), and lookupRelaxTableImpl().