LLVM: lib/Target/X86/X86RegisterInfo.cpp File Reference
X86RegisterInfo.cpp File Reference
#include "X86RegisterInfo.h"
#include "X86FrameLowering.h"
#include "X86MachineFunctionInfo.h"
#include "X86Subtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/LiveRegMatrix.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TileShapeInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "X86GenRegisterInfo.inc"
Macros
#define GET_REGINFO_TARGET_DESC
#define DEBUG_TYPE "tile-hint"
Functions
static bool CantUseSP (const MachineFrameInfo &MFI)
static bool tryOptimizeLEAtoMOV (MachineBasicBlock::iterator II)
static bool isFuncletReturnInstr (MachineInstr &MI)
static ShapeT getTileShape (Register VirtReg, VirtRegMap *VRM, const MachineRegisterInfo *MRI)
Variables
static cl::opt< bool > EnableBasePointer ("x86-use-base-pointer", cl::Hidden, cl::init(true), cl::desc("Enable use of a base pointer for complex stack frames"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "tile-hint"
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 41 of file X86RegisterInfo.cpp.
Function Documentation
CantUseSP()
static bool CantUseSP (const MachineFrameInfo & MFI) static
Definition at line 699 of file X86RegisterInfo.cpp.
References llvm::MachineFrameInfo::hasOpaqueSPAdjustment(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by llvm::X86RegisterInfo::canRealignStack(), and llvm::X86RegisterInfo::hasBasePointer().
getTileShape()
static ShapeT getTileShape (Register VirtReg, VirtRegMap * VRM, const MachineRegisterInfo * MRI) static
Definition at line 934 of file X86RegisterInfo.cpp.
References llvm::VirtRegMap::assignVirt2Shape(), llvm::tgtok::Def, llvm::MachineRegisterInfo::def_begin(), llvm::VirtRegMap::getShape(), llvm::VirtRegMap::hasShape(), llvm_unreachable, MI, and MRI.
Referenced by llvm::X86RegisterInfo::getRegAllocationHints().
isFuncletReturnInstr()
static bool isFuncletReturnInstr (MachineInstr & MI) static
Definition at line 770 of file X86RegisterInfo.cpp.
References llvm::ISD::CATCHRET, llvm::ISD::CLEANUPRET, llvm_unreachable, and MI.
Referenced by llvm::X86RegisterInfo::eliminateFrameIndex().
tryOptimizeLEAtoMOV()
static bool tryOptimizeLEAtoMOV (MachineBasicBlock::iterator II) static
Definition at line 745 of file X86RegisterInfo.cpp.
References llvm::HexagonInstrInfo::copyPhysReg(), llvm::getX86SubSuperRegister(), MI, and TII.
Referenced by llvm::X86RegisterInfo::eliminateFrameIndex().
Variable Documentation
EnableBasePointer
cl::opt<bool> EnableBasePointer("x86-use-base-pointer", cl::Hidden, cl::init(true), cl::desc("Enable use of a base pointer for complex stack frames")) static
Referenced by llvm::X86RegisterInfo::hasBasePointer().