LLVM: lib/Target/XCore/XCoreTargetMachine.cpp File Reference
XCoreTargetMachine.cpp File Reference
#include "XCoreTargetMachine.h"
#include "MCTargetDesc/XCoreMCTargetDesc.h"
#include "TargetInfo/XCoreTargetInfo.h"
#include "XCore.h"
#include "XCoreMachineFunctionInfo.h"
#include "XCoreTargetObjectFile.h"
#include "XCoreTargetTransformInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CodeGen.h"
#include <optional>
Functions
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
static CodeModel::Model getEffectiveXCoreCodeModel (std::optional< CodeModel::Model > CM)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreTarget ()
Function Documentation
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 29 of file XCoreTargetMachine.cpp.
References llvm::AArch64::RM, and llvm::Reloc::Static.
getEffectiveXCoreCodeModel()
static CodeModel::Model getEffectiveXCoreCodeModel (std::optional< CodeModel::Model > CM) static
Definition at line 34 of file XCoreTargetMachine.cpp.
References llvm::CodeModel::Large, llvm::report_fatal_error(), and llvm::CodeModel::Small.
LLVMInitializeXCoreTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreTarget ()
Definition at line 107 of file XCoreTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheXCoreTarget(), llvm::initializeXCoreDAGToDAGISelPass(), and X.