LLVM: lib/Target/XCore/Disassembler/XCoreDisassembler.cpp File Reference
XCoreDisassembler.cpp File Reference
#include "TargetInfo/XCoreTargetInfo.h"
#include "XCore.h"
#include "XCoreRegisterInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "XCoreGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "xcore-disassembler"
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
Functions
static bool readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint16_t &Insn)
static bool readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn)
static unsigned getReg (const MCDisassembler *D, unsigned RC, unsigned RegNo)
static DecodeStatus DecodeGRRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeBitpOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeNegImmOperand (MCInst &Inst, unsigned Val, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus Decode2RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus Decode2RImmInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeR2RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus Decode2RSrcDstInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRUSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRUSBitpInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeRUSSrcDstBitpInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL2RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeLR2RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus Decode3RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus Decode3RImmInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus Decode2RUSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus Decode2RUSBitpInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL3RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL3RSrcDstInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL2RUSInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL2RUSBitpInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL6RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL5RInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL4RSrcDstInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL4RSrcDstSrcDstInstruction (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus Decode2OpInstruction (unsigned Insn, unsigned &Op1, unsigned &Op2)
static DecodeStatus Decode3OpInstruction (unsigned Insn, unsigned &Op1, unsigned &Op2, unsigned &Op3)
static DecodeStatus Decode2OpInstructionFail (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL2OpInstructionFail (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeL5RInstructionFail (MCInst &Inst, unsigned Insn, uint64_t Address, const MCDisassembler *Decoder)
static MCDisassembler * createXCoreDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreDisassembler ()
Detailed Description
This file is part of the XCore Disassembler.
Definition in file XCoreDisassembler.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "xcore-disassembler"
Definition at line 26 of file XCoreDisassembler.cpp.
Typedef Documentation
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 28 of file XCoreDisassembler.cpp.
Function Documentation
createXCoreDisassembler()
static MCDisassembler* createXCoreDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 747 of file XCoreDisassembler.cpp.
Referenced by LLVMInitializeXCoreDisassembler().
Decode2OpInstruction()
static DecodeStatus Decode2OpInstruction (unsigned Insn, unsigned & Op1, unsigned & Op2) static
Definition at line 216 of file XCoreDisassembler.cpp.
References llvm::MCDisassembler::Fail, Insn, and llvm::MCDisassembler::Success.
Referenced by Decode2RImmInstruction(), Decode2RInstruction(), Decode2RSrcDstInstruction(), DecodeL2RInstruction(), DecodeL5RInstruction(), DecodeLR2RInstruction(), DecodeR2RInstruction(), DecodeRUSBitpInstruction(), DecodeRUSInstruction(), and DecodeRUSSrcDstBitpInstruction().
Decode2OpInstructionFail()
static DecodeStatus Decode2OpInstructionFail (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 249 of file XCoreDisassembler.cpp.
References Decode2RUSBitpInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), Decode3RInstruction(), llvm::MCDisassembler::Fail, Insn, and llvm::MCInst::setOpcode().
Referenced by Decode2RImmInstruction(), Decode2RInstruction(), Decode2RSrcDstInstruction(), DecodeR2RInstruction(), DecodeRUSBitpInstruction(), DecodeRUSInstruction(), and DecodeRUSSrcDstBitpInstruction().
Decode2RImmInstruction()
static DecodeStatus Decode2RImmInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 332 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Decode2RInstruction()
static DecodeStatus Decode2RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 319 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Decode2RSrcDstInstruction()
static DecodeStatus Decode2RSrcDstInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 358 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Decode2RUSBitpInstruction()
static DecodeStatus Decode2RUSBitpInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 550 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeBitpOperand(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Referenced by Decode2OpInstructionFail().
Decode2RUSInstruction()
static DecodeStatus Decode2RUSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 537 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Referenced by Decode2OpInstructionFail().
Decode3OpInstruction()
static DecodeStatus Decode3OpInstruction (unsigned Insn, unsigned & Op1, unsigned & Op2, unsigned & Op3) static
Definition at line 234 of file XCoreDisassembler.cpp.
References llvm::MCDisassembler::Fail, Insn, and llvm::MCDisassembler::Success.
Referenced by Decode2RUSBitpInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), Decode3RInstruction(), DecodeL2RUSBitpInstruction(), DecodeL2RUSInstruction(), DecodeL3RInstruction(), DecodeL3RSrcDstInstruction(), DecodeL4RSrcDstInstruction(), DecodeL4RSrcDstSrcDstInstruction(), DecodeL5RInstruction(), and DecodeL6RInstruction().
Decode3RImmInstruction()
static DecodeStatus Decode3RImmInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 524 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Referenced by Decode2OpInstructionFail().
Decode3RInstruction()
static DecodeStatus Decode3RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 511 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Referenced by Decode2OpInstructionFail().
DecodeBitpOperand()
static DecodeStatus DecodeBitpOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 196 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by Decode2RUSBitpInstruction(), DecodeL2RUSBitpInstruction(), DecodeRUSBitpInstruction(), and DecodeRUSSrcDstBitpInstruction().
DecodeGRRegsRegisterClass()
static DecodeStatus DecodeGRRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 176 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by Decode2RImmInstruction(), Decode2RInstruction(), Decode2RSrcDstInstruction(), Decode2RUSBitpInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), Decode3RInstruction(), DecodeL2RInstruction(), DecodeL2RUSBitpInstruction(), DecodeL2RUSInstruction(), DecodeL3RInstruction(), DecodeL3RSrcDstInstruction(), DecodeL4RSrcDstInstruction(), DecodeL4RSrcDstSrcDstInstruction(), DecodeL5RInstruction(), DecodeL6RInstruction(), DecodeLR2RInstruction(), DecodeR2RInstruction(), DecodeRUSBitpInstruction(), DecodeRUSInstruction(), and DecodeRUSSrcDstBitpInstruction().
DecodeL2OpInstructionFail()
static DecodeStatus DecodeL2OpInstructionFail (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 412 of file XCoreDisassembler.cpp.
References DecodeL2RUSBitpInstruction(), DecodeL2RUSInstruction(), DecodeL3RInstruction(), DecodeL3RSrcDstInstruction(), llvm::MCDisassembler::Fail, Insn, and llvm::MCInst::setOpcode().
Referenced by DecodeL2RInstruction(), and DecodeLR2RInstruction().
DecodeL2RInstruction()
static DecodeStatus DecodeL2RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 483 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), DecodeGRRegsRegisterClass(), DecodeL2OpInstructionFail(), Insn, S, and llvm::MCDisassembler::Success.
DecodeL2RUSBitpInstruction()
static DecodeStatus DecodeL2RUSBitpInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 606 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeBitpOperand(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Referenced by DecodeL2OpInstructionFail().
DecodeL2RUSInstruction()
static DecodeStatus DecodeL2RUSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 592 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Referenced by DecodeL2OpInstructionFail().
DecodeL3RInstruction()
static DecodeStatus DecodeL3RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 563 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Referenced by DecodeL2OpInstructionFail().
DecodeL3RSrcDstInstruction()
static DecodeStatus DecodeL3RSrcDstInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 577 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Referenced by DecodeL2OpInstructionFail().
DecodeL4RSrcDstInstruction()
static DecodeStatus DecodeL4RSrcDstInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 674 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
DecodeL4RSrcDstSrcDstInstruction()
static DecodeStatus DecodeL4RSrcDstSrcDstInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 694 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
DecodeL5RInstruction()
static DecodeStatus DecodeL5RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 654 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode3OpInstruction(), DecodeGRRegsRegisterClass(), DecodeL5RInstructionFail(), Insn, S, and llvm::MCDisassembler::Success.
DecodeL5RInstructionFail()
static DecodeStatus DecodeL5RInstructionFail (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 640 of file XCoreDisassembler.cpp.
References llvm::MCInst::clear(), DecodeL6RInstruction(), llvm::MCDisassembler::Fail, Insn, and llvm::MCInst::setOpcode().
Referenced by DecodeL5RInstruction().
DecodeL6RInstruction()
static DecodeStatus DecodeL6RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 620 of file XCoreDisassembler.cpp.
References Decode3OpInstruction(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
Referenced by DecodeL5RInstructionFail().
DecodeLR2RInstruction()
static DecodeStatus DecodeLR2RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 497 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), DecodeGRRegsRegisterClass(), DecodeL2OpInstructionFail(), Insn, S, and llvm::MCDisassembler::Success.
DecodeNegImmOperand()
static DecodeStatus DecodeNegImmOperand (MCInst & Inst, unsigned Val, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 208 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeR2RInstruction()
static DecodeStatus DecodeR2RInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 345 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
DecodeRRegsRegisterClass()
static DecodeStatus DecodeRRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 186 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeRUSBitpInstruction()
static DecodeStatus DecodeRUSBitpInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 385 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeBitpOperand(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
DecodeRUSInstruction()
static DecodeStatus DecodeRUSInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 372 of file XCoreDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
DecodeRUSSrcDstBitpInstruction()
static DecodeStatus DecodeRUSSrcDstBitpInstruction (MCInst & Inst, unsigned Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 399 of file XCoreDisassembler.cpp.
References Decode2OpInstruction(), Decode2OpInstructionFail(), DecodeBitpOperand(), DecodeGRRegsRegisterClass(), Insn, S, and llvm::MCDisassembler::Success.
getReg()
static unsigned getReg (const MCDisassembler * D, unsigned RC, unsigned RegNo) static
Definition at line 69 of file XCoreDisassembler.cpp.
References llvm::MCRegisterClass::begin(), D, and llvm::MCRegisterInfo::getRegClass().
Referenced by DecodeGRRegsRegisterClass(), and DecodeRRegsRegisterClass().
LLVMInitializeXCoreDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreDisassembler ()
Definition at line 753 of file XCoreDisassembler.cpp.
References createXCoreDisassembler(), llvm::getTheXCoreTarget(), and llvm::TargetRegistry::RegisterMCDisassembler().
readInstruction16()
static bool readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint16_t & Insn) static
Definition at line 44 of file XCoreDisassembler.cpp.
References Insn, and llvm::ArrayRef< T >::size().
readInstruction32()
static bool readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn) static
Definition at line 56 of file XCoreDisassembler.cpp.
References Insn, and llvm::ArrayRef< T >::size().