LLVM: lib/Target/XCore/MCTargetDesc/XCoreMCTargetDesc.cpp File Reference
XCoreMCTargetDesc.cpp File Reference
#include "MCTargetDesc/XCoreMCTargetDesc.h"
#include "MCTargetDesc/XCoreInstPrinter.h"
#include "MCTargetDesc/XCoreMCAsmInfo.h"
#include "TargetInfo/XCoreTargetInfo.h"
#include "XCoreTargetStreamer.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/raw_ostream.h"
#include "XCoreGenInstrInfo.inc"
#include "XCoreGenSubtargetInfo.inc"
#include "XCoreGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createXCoreMCInstrInfo ()
static MCRegisterInfo * createXCoreMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createXCoreMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCAsmInfo * createXCoreMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstPrinter * createXCoreMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool isVerboseAsm)
static MCTargetStreamer * createNullTargetStreamer (MCStreamer &S)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 32 of file XCoreMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 31 of file XCoreMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 38 of file XCoreMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 35 of file XCoreMCTargetDesc.cpp.
Function Documentation
createNullTargetStreamer()
static MCTargetStreamer* createNullTargetStreamer (MCStreamer & S) static
Definition at line 125 of file XCoreMCTargetDesc.cpp.
References S.
Referenced by LLVMInitializeXCoreTargetMC().
createTargetAsmStreamer()
static MCTargetStreamer* createTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint, bool isVerboseAsm) static
Definition at line 118 of file XCoreMCTargetDesc.cpp.
References OS, and S.
Referenced by LLVMInitializeXCoreTargetMC().
createXCoreMCAsmInfo()
static MCAsmInfo* createXCoreMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 58 of file XCoreMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), and llvm::MCCFIInstruction::cfiDefCfa().
Referenced by LLVMInitializeXCoreTargetMC().
createXCoreMCInstPrinter()
static MCInstPrinter* createXCoreMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 70 of file XCoreMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeXCoreTargetMC().
createXCoreMCInstrInfo()
static MCInstrInfo* createXCoreMCInstrInfo () static
Definition at line 41 of file XCoreMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeXCoreTargetMC().
createXCoreMCRegisterInfo()
static MCRegisterInfo* createXCoreMCRegisterInfo (const Triple & TT) static
Definition at line 47 of file XCoreMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeXCoreTargetMC().
createXCoreMCSubtargetInfo()
static MCSubtargetInfo* createXCoreMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 54 of file XCoreMCTargetDesc.cpp.
References llvm::X86AS::FS.
Referenced by LLVMInitializeXCoreTargetMC().
LLVMInitializeXCoreTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXCoreTargetMC ()
Definition at line 130 of file XCoreMCTargetDesc.cpp.
References createNullTargetStreamer(), createTargetAsmStreamer(), createXCoreMCAsmInfo(), createXCoreMCInstPrinter(), createXCoreMCInstrInfo(), createXCoreMCRegisterInfo(), createXCoreMCSubtargetInfo(), llvm::getTheXCoreTarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), and X.