LLVM: lib/Target/Xtensa/MCTargetDesc/XtensaInstPrinter.cpp File Reference
XtensaInstPrinter.cpp File Reference
#include "XtensaInstPrinter.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegister.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/raw_ostream.h"
#include "XtensaGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static void printExpr (const MCExpr *Expr, raw_ostream &OS)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 26 of file XtensaInstPrinter.cpp.
Function Documentation
printExpr()
static void printExpr (const MCExpr * Expr, raw_ostream & OS) static
Definition at line 30 of file XtensaInstPrinter.cpp.
References assert(), llvm::MCSymbolRefExpr::getKind(), llvm::MCSymbolRefExpr::getSymbol(), llvm::Offset, OS, llvm::report_fatal_error(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::XtensaInstPrinter::printOperand().