LLVM: lib/Target/Xtensa/MCTargetDesc/XtensaAsmBackend.cpp File Reference
XtensaAsmBackend.cpp File Reference
#include "MCTargetDesc/XtensaFixupKinds.h"
#include "MCTargetDesc/XtensaMCTargetDesc.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/raw_ostream.h"
Classes
class llvm::XtensaMCAsmBackend
Namespaces
llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static uint64_t adjustFixupValue (const MCFixup &Fixup, uint64_t Value, MCContext &Ctx)
static unsigned getSize (unsigned Kind)
Function Documentation
adjustFixupValue()
static uint64_t adjustFixupValue (const MCFixup & Fixup, uint64_t Value, MCContext & Ctx) static
Definition at line 81 of file XtensaAsmBackend.cpp.
References Fixup, llvm::Xtensa::fixup_xtensa_branch_12, llvm::Xtensa::fixup_xtensa_branch_6, llvm::Xtensa::fixup_xtensa_branch_8, llvm::Xtensa::fixup_xtensa_call_18, llvm::Xtensa::fixup_xtensa_jump_18, llvm::Xtensa::fixup_xtensa_l32r_16, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm_unreachable, llvm::Offset, llvm::MCContext::reportError(), and x3.
Referenced by llvm::XtensaMCAsmBackend::applyFixup().
getSize()
static unsigned getSize (unsigned Kind) static
Definition at line 134 of file XtensaAsmBackend.cpp.
References llvm::Xtensa::fixup_xtensa_branch_6, and llvm::FK_Data_4.
Referenced by AddNodeIDCustom(), llvm::XtensaMCAsmBackend::applyFixup(), llvm::DwarfUnit::emitCommonHeader(), llvm::InstrProfRecordWriterTrait::EmitKeyDataLength(), llvm::object::Archive::Child::getBuffer(), llvm::RISCVInstrInfo::getMemOperandWithOffsetWidth(), llvm::PPCInstrInfo::getMemOperandWithOffsetWidth(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), and llvm::MipsLegalizerInfo::legalizeCustom().