LLVM: lib/Support/xxhash.cpp File Reference
xxhash.cpp File Reference
#include "llvm/Support/xxhash.h"
#include "llvm/Support/Endian.h"
#include <stdlib.h>
Functions
static uint64_t rotl64 (uint64_t X, size_t R)
static uint64_t round (uint64_t Acc, uint64_t Input)
static uint64_t mergeRound (uint64_t Acc, uint64_t Val)
Variables
static const uint64_t PRIME64_1 = 11400714785074694791ULL
static const uint64_t PRIME64_2 = 14029467366897019727ULL
static const uint64_t PRIME64_3 = 1609587929392839161ULL
static const uint64_t PRIME64_4 = 9650029242287828579ULL
static const uint64_t PRIME64_5 = 2870177450012600261ULL
Function Documentation
mergeRound()
static uint64_t mergeRound (uint64_t Acc, uint64_t Val) static
Definition at line 63 of file xxhash.cpp.
References PRIME64_1, PRIME64_4, and round().
Referenced by llvm::xxHash64().
rotl64()
static uint64_t rotl64 (uint64_t X, size_t R) static
Definition at line 46 of file xxhash.cpp.
References X.
Referenced by round(), and llvm::xxHash64().
round()
static uint64_t round (uint64_t Acc, uint64_t Input) static
Definition at line 56 of file xxhash.cpp.
References PRIME64_1, PRIME64_2, and rotl64().
Referenced by llvm::canConstantFoldCallTo(), canCreateUndefOrPoison(), cannotBeOrderedLessThanZeroImpl(), llvm::sampleprof::DefaultFunctionPruningStrategy::Erase(), llvm::getHeatColor(), llvm::getIntrinsicForCallSite(), llvm::RISCVTTIImpl::getIntrinsicInstrCost(), llvm::BasicTTIImplBase< AMDGPUTTIImpl >::getTypeBasedIntrinsicInstrCost(), intrinsicHasPackedVectorBenefit(), isIdempotent(), llvm::isKnownNeverInfinity(), llvm::isKnownNeverNaN(), llvm::ARMTTIImpl::isLoweredToCall(), llvm::isTriviallyVectorizable(), llvm::IntrinsicLowering::LowerIntrinsicCall(), mergeRound(), removesFPFraction(), round_fn(), simplifyNvvmIntrinsic(), llvm::APInt::sqrt(), tryInterleave(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFPTrunc(), and llvm::xxHash64().
Variable Documentation
PRIME64_1
const uint64_t PRIME64_1 = 11400714785074694791ULL static
Definition at line 50 of file xxhash.cpp.
Referenced by mergeRound(), round(), and llvm::xxHash64().
PRIME64_2
const uint64_t PRIME64_2 = 14029467366897019727ULL static
Definition at line 51 of file xxhash.cpp.
Referenced by round(), and llvm::xxHash64().
PRIME64_3
const uint64_t PRIME64_3 = 1609587929392839161ULL static
Definition at line 52 of file xxhash.cpp.
Referenced by llvm::xxHash64().
PRIME64_4
const uint64_t PRIME64_4 = 9650029242287828579ULL static
Definition at line 53 of file xxhash.cpp.
Referenced by mergeRound(), and llvm::xxHash64().
PRIME64_5
const uint64_t PRIME64_5 = 2870177450012600261ULL static
Definition at line 54 of file xxhash.cpp.
Referenced by llvm::xxHash64().